### ISSUE TITLE
『Demanding』⟨Level: Extreme⟩ Sponsorship Demanding on Alipay/Wepay

### ISSUE THREAD

**Issue by phantastar** [vernesong/OpenClash#100]
`Background`
A common people who enjoys your application wanna shut up and be took money toward you for sponsorship in Alipay/Wepay. 

`Specific Demanding`
Alipay/Wepay QR Code for transferring money.

`Reason for Demanding`
That common people wanna make the new year cash useful for really meaningful stuff (sponsoring the producer of the OpenWRT plugin he mostly uses everyday. ) rather than sponsoring broadcasters in TikTok or something like that.

**Comment by zjdavid** [comment]
Alipay and Wepay are associated with real names, which means they are not safe.

**Comment by phantastar** [comment]
> Alipay and Wepay are associated with real names, which means they are not safe.

原来是这样, 我知道这个可能比较敏感, 所以才拿英文发(防止被中文关键字索引). 
不过国内的情况也不太容易兑换BTC贡献给作者, 所以我还想着贡献RMB呢.
