### ISSUE TITLE
0.41.02版本DNS转发错误

### ISSUE THREAD

**Issue by XingNian-www** [vernesong/OpenClash#1001]
0.41.02版本中无法正确识别clash的DNS监听端口
Dnsmasq里面的DNS转发一直是127.0.0.1#7874
不随配置文件变动

**Comment by pxw139** [comment]
即使手动修改了也会被修改回去,只能先把clash的DNS端口也修改成7874了

**Comment by LOVE2CMOL** [comment]
可以取消*本地DNS劫持
![Uploading image.png…]()

**Comment by LOVE2CMOL** [comment]
可以取消*本地DNS劫持
![image](https://user-images.githubusercontent.com/28857775/99823523-75b44c00-2b8f-11eb-9bf6-ffc0283f0b8b.png)

**Comment by pxw139** [comment]
实际上我就是需要这个功能，还是修改配置文件先凑合用了

LOVE2CMOL <notifications@github.com> 于 2020年11月21日周六 00:21写道：

**Comment by vernesong** [comment]
配置文件写的是什么端口？

**Comment by pxw139** [comment]
之前是1053，尝试改了10053啥的
可以确定不是端口冲突的原因

vernesong <notifications@github.com> 于 2020年11月21日周六 10:47写道：
