### ISSUE TITLE
0.41.02每次关闭-重新启动后，Yacd和Dashboard 控制面板记不住关闭前每个分组的选择

### ISSUE THREAD

**Issue by wrxx2019** [vernesong/OpenClash#1004]
Redir-Host（兼容）模式 ，每次关闭再运行，Yacd和Dashboard 控制面板下的每个分组总是会恢复到默认第一个选择，记不住关闭前的选择。0.40.15没有出现这个问题。不知道是不是和不同subconverter版本转换有关

**Comment by LOVE2CMOL** [comment]
你看下是不是你的自定义内容都没有生效，我的是配置文件的自定义部分没有生效，貌似是新版本的bug

**Comment by wrxx2019** [comment]
更新0.41.03后此问题已经解决。非常感谢！
