### ISSUE TITLE
0.41.02  配置文件校验失败，请检查配置文件后重试！

### ISSUE THREAD

**Issue by Skytostop** [vernesong/OpenClash#1005]
如何排查呢？

**Comment by Skytostop** [comment]
如何排查呢？

**Comment by Eintler** [comment]
遇到同样的问题，而且这个配置文件只要在默认的上面修改过，就报错。复位后也仍然报错。

**Comment by Skytostop** [comment]
> 遇到同样的问题，而且这个配置文件只要在默认的上面修改过，就报错。复位后也仍然报错。

我多试几次有时候会出来，又上传了以前的配置，但是启动clash后，显示网络检查：连接超时，醉～

**Comment by vernesong** [comment]
更新？

**Comment by emacsnt** [comment]
遇到相同问题，按照下面的方法解决
1，设定日志级别info
2，查看错误日志：yam格式检查错误，有tab字符
3，用文本编辑器编辑/etc/openclash/config/config.yaml，把tab替换成空字符串后，错误消失.

**Comment by zhangguanzhang** [comment]
大概14行有tab

**Comment by vernesong** [comment]
新版会报第几行有错误的

**Comment by anjue39** [comment]
这个现象至今依然存在，每次都出这样的提示
