### ISSUE TITLE
dashboard 打开是白板?不支持https？

### ISSUE THREAD

**Issue by LzwCracker** [vernesong/OpenClash#1010]
怎么处理啊~！
![image](https://user-images.githubusercontent.com/18252512/99890724-2f4d1300-2c9d-11eb-97b9-a4eb559f1c09.png)

**Comment by LzwCracker** [comment]
开启ssl就 无法访问了?

**Comment by vernesong** [comment]
面板不支持https

**Comment by Nebell** [comment]
表示http打开也这样，一片空白。

**Comment by vernesong** [comment]
确认登录信息正确，ctrl+f5刷新
