### ISSUE TITLE
启动不了

### ISSUE THREAD

**Issue by mmeiwenlong** [vernesong/OpenClash#1016]
![QQ截图20201122124411](https://user-images.githubusercontent.com/44661424/99894620-8e704f00-2cc0-11eb-8401-c28f9f14082f.png)

**Comment by mmeiwenlong** [comment]
![QQ截图20201122125059](https://user-images.githubusercontent.com/44661424/99894786-8a90fc80-2cc1-11eb-952e-c7e9cbb501aa.png)

**Comment by hcym** [comment]
刚刚安装的，上传配置，正常使用，就是一键生成不好使，可能方法不对

**Comment by vernesong** [comment]
> 刚刚安装的，上传配置，正常使用，就是一键生成不好使，可能方法不对

一键生成我这边用代理集测试没问题

**Comment by vernesong** [comment]
@mmeiwenlong 你第一个策略组里面没有节点信息

**Comment by hcym** [comment]
难怪，还是方法问题，我不会搞代理集，就输入几个节点，输出的配置只有节点没有规则，不折腾了，还是上传自己的配置也方便。😂

**Comment by vernesong** [comment]
> 难怪，还是方法问题，我不会搞代理集，就输入几个节点，输出的配置只有节点没有规则，不折腾了，还是上传自己的配置也方便。😂

我晚上看下

**Comment by mmeiwenlong** [comment]
![QQ截图20201122184828](https://user-images.githubusercontent.com/44661424/99901689-70701200-2cf3-11eb-9659-bf1aa54163df.png)
下载下来就可以。直接订阅就不行晕

**Comment by trotack** [comment]
同样。
老的openclash配置文件上传之后可以使用。订阅生成的不可以。看起来是通过openclash配置的信息无法写入配置文件导致。
将老配置文件中类似于自定义dns、fake-ip、自定义规则等信息手动复制到订阅生产的配置文件后，可以正常启动。
