### ISSUE TITLE
v0.41.03-beta 升级后所有原配置文件语法检查报错，启动失败！

### ISSUE THREAD

**Issue by laosuye** [vernesong/OpenClash#1021]
v0.41.03-beta 升级后所有原配置文件语法检查报错，启动失败！

**Comment by 404user** [comment]
我也是。。。

**Comment by laosuye** [comment]
2020-11-23 16:51:00 Error: Unable To Parse Config File, Please Check And Try Again!
2020-11-23 16:48:20 Config 【1123】Update Error

**Comment by wudj1967** [comment]
我也是这情况，回退v0.40.15-beta后正常

**Comment by vernesong** [comment]
装新依赖

**Comment by wudj1967** [comment]
ruby, ruby-yaml，老大是这两个依赖吗，我装了但不行，还是上面的报错

**Comment by vernesong** [comment]
opkg update && opkg install ruby-yaml

**Comment by laosuye** [comment]
重装v0.40.15-beta后正常

**Comment by wudj1967** [comment]
> opkg update && opkg install ruby-yaml

刚按您提供的方法更新了依赖，再更新v0.41.04-beta，更新完后还是报错
2020-11-23 17:40:08 Error: Unable To Parse Config File, Please Check And Try Again!
2020-11-23 17:39:55 OpenClash Update Successful
2020-11-23 17:40:05 Warning: OpenClash Now Disabled, Need Start From Luci Page, Exit...

**Comment by wudj1967** [comment]
所有配置文件都是“语法检查失败”

**Comment by 404user** [comment]
> opkg update && opkg install ruby-yaml

感谢，已经解决了

**Comment by vernesong** [comment]
> > opkg update && opkg install ruby-yaml
> 
> 
> 
> 刚按您提供的方法更新了依赖，再更新v0.41.04-beta，更新完后还是报错
> 
> 2020-11-23 17:40:08 Error: Unable To Parse Config File, Please Check And Try Again!
> 
> 2020-11-23 17:39:55 OpenClash Update Successful
> 
> 2020-11-23 17:40:05 Warning: OpenClash Now Disabled, Need Start From Luci Page, Exit...

先卸载原来的再重装

**Comment by mztzg** [comment]
我应该按照你的方法安装好ruby并更新好，解决了所有yalm都不能通过语法检查的问题，但是还有一些配置文件通不过，但是这些配置文件在windows clash里面是可以使用的。很诡异。很魔性。

**Comment by NameJun1990** [comment]
> > > opkg update && opkg install ruby-yaml
> > 
> > 
> > 刚按您提供的方法更新了依赖，再更新v0.41.04-beta，更新完后还是报错
> > 2020-11-23 17:40:08 Error: Unable To Parse Config File, Please Check And Try Again!
> > 2020-11-23 17:39:55 OpenClash Update Successful
> > 2020-11-23 17:40:05 Warning: OpenClash Now Disabled, Need Start From Luci Page, Exit...
> 
> 先卸载原来的再重装

新手小白，也是语法检查错误，请问卸载重装具体怎么操作。
