### ISSUE TITLE
请问下末尾总是会自动添加一些规则

### ISSUE THREAD

**Issue by kanyou** [vernesong/OpenClash#1023]
- DOMAIN-KEYWORD,tracker,DIRECT
- DOMAIN-KEYWORD,announce.php?passkey=,DIRECT
- DOMAIN-KEYWORD,torrent,DIRECT
- DOMAIN-KEYWORD,peer_id=,DIRECT
- DOMAIN-KEYWORD,info_hash,DIRECT
- DOMAIN-KEYWORD,get_peers,DIRECT
- DOMAIN-KEYWORD,find_node,DIRECT
- DOMAIN-KEYWORD,BitTorrent,DIRECT
- DOMAIN-KEYWORD,announce_peer,DIRECT
- MATCH,DIRECT
总是会自动添加这几行规则不知道是什么问题

**Comment by LOVE2CMOL** [comment]
一块是绕过bt的规则，对上网没有影响，bt绕过反而更好，除非有特殊需求
最后那一行你开启了这个就会自动添加
![image](https://user-images.githubusercontent.com/28857775/99994181-a5638e00-2df3-11eb-9578-8cb54562af37.png)

**Comment by kanyou** [comment]
> 一块是绕过bt的规则，对上网没有影响，bt绕过反而更好，除非有特殊需求
> 最后那一行你开启了这个就会自动添加
> ![image](https://user-images.githubusercontent.com/28857775/99994181-a5638e00-2df3-11eb-9578-8cb54562af37.png)

谢谢，我就是说怎么自动给我弄成match变成direct，原来是这样，谢谢了
