### ISSUE TITLE
规则数目太多会对访问速度造成影响吗

### ISSUE THREAD

**Issue by ForestL18** [vernesong/OpenClash#1025]
因为规则需要一条一条去匹配，匹配成功才停止，那规则数rules太多会对访问速度有影响吗，多少条规则比较合适呢

**Comment by LOVE2CMOL** [comment]
这个影响几何可以忽略不计吧。。。。。

**Comment by cnsunyour** [comment]
34000+规则无感路过

**Comment by ForestL18** [comment]
> 34000+规则无感路过

我使用了rule-set，里面有的规则集就有7万多条规则，不知道会不会对性能有影响

**Comment by hcym** [comment]
小机器肯定有影响，mtk的，ac58u之类的能感觉，就差一口气的往往就挂了，现在都是大家伙，没感觉。用的着就上，大多数用不着，我的就几百个，以前dnsmasq也是十万八千的规则，常用的三四千而已
