### ISSUE TITLE
UDP转发关闭无效

### ISSUE THREAD

**Issue by LostSmoch** [vernesong/OpenClash#1028]
升级最新版之后，所有与UDP有关的项目都不能加载，网速管家所有测速统统超时，把clash和配置文件的UDP转发都关掉了也无济于事。上一个版本本来也是这样，但我后来发现把UDP转发关掉，直连就没问题，新版不行
大佬搭救则个

**Comment by vernesong** [comment]
用tun呢？或者绕过大陆ip

**Comment by LostSmoch** [comment]
忘了说了我用的是fakeip，因为redirect不能扶墙，这个模式从控制面板里看连接是走的代理，但就是没速度
fakeIP之前把udp转发关了也能用，毕竟我扶墙需求好像没遇到对UDP有要求的
现在不行了，FAKEIP增强模式的udp开关根本没有效果，TUN模式只有speedtest能测速，除此以外都显示网络无连接，以我的知识也搞不清楚是什么流量
因为启动正常，日志也没什么异常，所以我也不知道该怎么反馈了

**Comment by LostSmoch** [comment]
已通过添加黑名单解决了部分，看样子是dns方面的问题，不过黑名单以外的还是统统不行
暂时可以满足需求了就不再追问如何解决，但还是希望作者先生下次更新可以修复，有生之年我也想见到完美运行的V1.0正式版
