### ISSUE TITLE
软路由DHCP服务，提供了DNS，openclas启动后，也有DNS服务，请问两者是如何工作的？如果DHCP服务不设置DNS，发现客户端是自动获取的路由器地址，感觉上网慢，这时候DNS是不是就交给了openclash

### ISSUE THREAD

**Issue by icucuio** [vernesong/OpenClash#1029]
**如果路由器在DHCP里面设置了DNS，客户端获取了DNS，感觉上网会快很多，网页秒开。
如果不是指DNS，客户端获取的DNS是路由器地址，就慢很多，
如果要使用openclash的话，到底需要不需要在DHCP里面设置DNS，如果设置，两者可以不同吗？
我发下有些时候，如果两个都设置了，会导致访问https网站时提示，不安全连接，是不是就是DNS导致的。
如果客户端上有DNS地址，openclash也有，那解析的时候到底时通过谁来的？**

**Comment by vernesong** [comment]
插件的dns接管下面设备的请求，dhcp下发路由地址即可，感觉慢就在插件里面自定义几个速度快的dns

**Comment by icucuio** [comment]
> 插件的dns接管下面设备的请求，dhcp下发路由地址即可，感觉慢就在插件里面自定义几个速度快的dns

我就按找推荐的设置的114 和 119.28 那个，但是我遇到的问题就是，刚开始有些网页打开一直转圈，app无法连接，然后往后用感觉又好点了，是不是openclash没有本地库来解析，然后逐渐学习和累积解析地址池？

**Comment by pillanangel** [comment]
设置劫持本地DNS试下。

**Comment by icucuio** [comment]
> 插件的dns接管下面设备的请求，dhcp下发路由地址即可，感觉慢就在插件里面自定义几个速度快的dns

我发现如果路由器提供的的DNS不是路由器地址，openclash的DNS好像不起作用，然后还会造成https网站无法访问，提示的错误就是不是安全链接，百度了下看了下原因是证书不匹配导致。http网站是正常访问的。
上面说的慢的情况，我发现启动“禁止DNSmasq缓存DNS”就变快了。
程序员可以看下。
之前反馈的softether VPN回家，现在也没有问题了
所以openclash DNS这块估计还是有问题的，建议可以看看
