### ISSUE TITLE
GeoIP近期难以更新, 以及缩小各种变量后可能的问题探究

### ISSUE THREAD

**Issue by phantastar** [vernesong/OpenClash#103]
### `系统`
OpenWRT X86_64原版
### `版本`
SNAPSHOT r11829-e3e939d8e6
### `问题`
12月31日早晨开始, GeoIP无限更新失败. 
### `尝试措施`
1. 重置系统+重装 → 解决失败
2. 停止OpenClash连接再更新 → 解决失败. 
3. 完全重装OpenClash → 解决失败. 
4. [根据以往issue的方法](https://github.com/vernesong/OpenClash/issues/62#issuecomment-554690071), WinSCP进入路由器目录更改参数 → 解决失败. 
### `可能的原因`
浏览器访问[MaxMind数据库](https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz)显示connection closed (wget也失败了), 推测问题在于MaxMind12月30号实行的[新条款](https://dev.maxmind.com/geoip/geoip2/geolite2/)限制了数据库访问. 
### `也许有用的信息`
[外网关于MaxMind替代品的讨论](https://www.quora.com/What-are-some-alternatives-to-MaxMinds-GeoIP-database)

**Comment by vernesong** [comment]
这个发新版本的时候会用其他镜像解决，短期无法更新不会有太大影响。
如果内核不支持，替代品的问题无从谈起

**Comment by phantastar** [comment]
> 这个发新版本的时候会用其他镜像解决，短期无法更新不会有太大影响。
> 如果内核不支持，替代品的问题无从谈起

那就麻烦您了🥳🥳🥳新年快乐！
