### ISSUE TITLE
"检测到DNS选项下的Nameserver未设置服务器，开始补全..."

### ISSUE THREAD

**Issue by 70599** [vernesong/OpenClash#1030]
在启动OpenClash时，会显示`检测到DNS选项下的Nameserver未设置服务器，开始补全...`
看了下`/etc/init.d/openclash`文件，貌似在这种情况下，会向配置文件填充默认的DNS服务器。

可是我在DNS设置页面里已经配置并启用了数个`NameServer`和`FallBack`，是哪里有问题吗？
![DNS](https://user-images.githubusercontent.com/5929170/100189968-4b181980-2f28-11eb-9fdb-9ce7232181a5.png)

**Comment by edwardldl** [comment]
上面应该要启用custom dns setting

**Comment by 70599** [comment]
这样应该算是启用的吧。
![custom dns](https://user-images.githubusercontent.com/5929170/100209300-a9eb8c00-2f44-11eb-9249-0695c3d1b862.png)

**Comment by vernesong** [comment]
启动机制变了，每次启动都会还原成初始配置文件，这个提示不用理会

**Comment by 70599** [comment]
意思就是说，DNS解析会用到我设置好的DNS服务器（而不是`/etc/init.d/openclash`里的默认的DNS服务器），对吗

**Comment by vernesong** [comment]
检测dns在前，修改自定义dns在后，最后启动就是自定义dns

**Comment by yubanmeiqin9048** [comment]
> 检测dns在前，修改自定义dns在后，最后启动就是自定义dns



> 启动机制变了，每次启动都会还原成初始配置文件，这个提示不用理会

如果我不想使用自定义DNS那么nameserver补全的时候是用的wan口获取到的DNS吗？
