### ISSUE TITLE
自行编译使用后运行模式没有Fake-IP

### ISSUE THREAD

**Issue by Tzwcard** [vernesong/OpenClash#1032]
硬件是NanoPi-R2S，固件是LEAN，在WSL2下编译进LEAN固件内。
![image](https://user-images.githubusercontent.com/12098388/100346551-fe633a00-301e-11eb-8e1b-d5e77860cda1.png)

**Comment by lifetyper** [comment]
![屏幕截图 2020-11-26 204621](https://user-images.githubusercontent.com/1171298/100352764-77b35a80-3028-11eb-9e37-42f884ce6ccd.png)
