### ISSUE TITLE
0.41.xx版本配置文件一直报错

### ISSUE THREAD

**Issue by zhnlanf** [vernesong/OpenClash#1033]
![image](https://user-images.githubusercontent.com/58921007/100388503-c206fc80-3065-11eb-9c0a-bfd2bdbefa17.png)
执行opkg update && opkg ruby-yaml也没有用，重新安装也没有用
0.40.XX之前的版本可以正常识别，但是运行时显示无法识别本地配置的DNS
这些配置在window端可以正常运行

**Comment by vernesong** [comment]
先卸载所有跟ruby有关的包然后，opkg update &&opkg insatall ruby-yaml

**Comment by hcym** [comment]
非要用新版本还是全新编译吧，加上相关依赖就ok，没有什么问题

**Comment by sanziliu** [comment]
0.41.xx （含）之后的所有版本问题，即使最新的 opennwrt 重新编译，总有些小小的磕磕绊绊。现在回退到v0.39.8-beta，感觉特别心平气和，稳定到似乎不存在

**Comment by zhnlanf** [comment]
> 0.41.xx （含）之后的所有版本问题，即使最新的 openwrt 重新编译，总有些小小的磕磕绊绊。现在回退到v0.39.8-beta，感觉特别心平气和，稳定到似乎不存在

可以发一下ipk包嘛

**Comment by sanziliu** [comment]
> > 0.41.xx （含）之后的所有版本问题，即使最新的 openwrt 重新编译，总有些小小的磕磕绊绊。现在回退到v0.39.8-beta，感觉特别心平气和，稳定到似乎不存在
> 
> 可以发一下ipk包嘛

https://github.com/vernesong/OpenClash/releases
你可以找找看，我是整个连 openwrt 回滚到这个版本

**Comment by zhnlanf** [comment]
> > > 0.41.xx （含）之后的所有版本问题，即使最新的 openwrt 重新编译，总有些小小的磕磕绊绊。现在回退到v0.39.8-beta，感觉特别心平气和，稳定到似乎不存在
> > 
> > 
> > 可以发一下ipk包嘛
> 
> https://github.com/vernesong/OpenClash/releases
> 你可以找找看，我是整个连 openwrt 回滚到这个版本
回退可以科学上网了，谢谢你和软件作者
