### ISSUE TITLE
Yacd-0.2.12控制面板logs

### ISSUE THREAD

**Issue by qin9125** [vernesong/OpenClash#1036]
再写一下吧，升级了40.15看到yacd也同步升级了0.2.12，特地去看了一下yacd面板的logs，还是老样子无论日志等级设置哪个logs依旧疯狂输出，还是您之前回退的0.2.5一切正常，不知道能修复还是考虑回退0.2.5，想问问能手动替换yacd吗？我只找到了源码，作者有没有编译过的yacd包给一个，我去手动替换，谢谢您的辛苦付出。

**Comment by hcym** [comment]
没有任何异常现象，和老版本也没有什么区别

**Comment by qin9125** [comment]
> 没有任何异常现象，和老版本也没有什么区别

就是这个yacd-logs你去看设置的静默但是一直输出日志，14版一直用的2.5旧版是正常的

**Comment by hcym** [comment]
黑糊糊的空白😂

**Comment by hcym** [comment]
14以前就是一个不能用，节点自动生成，今天.15还没试，反正我是习惯上传配置，规则也不多，感觉不错，什么日志都不看的，就看到鬼哭狼嚎的才学会看看，没输出

**Comment by ForestL18** [comment]
> 再写一下吧，升级了40.15看到yacd也同步升级了0.2.12，特地去看了一下yacd面板的logs，还是老样子无论日志等级设置哪个logs依旧疯狂输出，还是您之前回退的0.2.5一切正常，不知道能修复还是考虑回退0.2.5，想问问能手动替换yacd吗？我只找到了源码，作者有没有编译过的yacd包给一个，我去手动替换，谢谢您的辛苦付出。

我升级40.15后yacd没有升级，但是yacd里面的rules和logs都打不开了

**Comment by qin9125** [comment]
> > 再写一下吧，升级了40.15看到yacd也同步升级了0.2.12，特地去看了一下yacd面板的logs，还是老样子无论日志等级设置哪个logs依旧疯狂输出，还是您之前回退的0.2.5一切正常，不知道能修复还是考虑回退0.2.5，想问问能手动替换yacd吗？我只找到了源码，作者有没有编译过的yacd包给一个，我去手动替换，谢谢您的辛苦付出。
> 
> 我升级40.15后yacd没有升级，但是yacd里面的rules和logs都打不开了

哈哈，那你好叼的样子，我早晨升级到最新41.05，yacd跟随更新就这样logs静默但是日志疯狂输出
![image](https://user-images.githubusercontent.com/32502941/100448152-d93cfd00-30ec-11eb-9a77-9a72e68acafa.png)
强迫症不能忍回退了41.04，yacd变回25，世界清净了
![image](https://user-images.githubusercontent.com/32502941/100448245-fa055280-30ec-11eb-8dd0-bc0389417d9a.png)
![image](https://user-images.githubusercontent.com/32502941/100448264-feca0680-30ec-11eb-8d08-b5e7cde54a35.png)

**Comment by jongkhurunn** [comment]
额 我也是发现点到logs界面会输出日志。。还有选择新节点后 ip还一直保持着旧的= = 迷惑

**Comment by sekaiacg** [comment]
只要动了log等级，不管那个版本都疯狂输出
