### ISSUE TITLE
状态面板 IP.SB 一直显示 海外:查询中...

### ISSUE THREAD

**Issue by 0x5826** [vernesong/OpenClash#104]
打开chrome调试看到如下报错，浏览器的各种拦截插件已经都禁止或者加白了
openclash:843 GET https://ip.sb/addrinfo?callback=getIpsbIP net::ERR_ABORTED 500
openclash:747 Uncaught TypeError: Cannot read property '1' of null
    at RTCPeerConnection.pc.onicecandidate (openclash:747)

**Comment by lifetyper** [comment]
我看了一下，好像根本没写get ipsb ip的函数啊。。。。

**Comment by vernesong** [comment]
api接口调整，下版本会更新

**Comment by vernesong** [comment]
https://github.com/vernesong/OpenClash/blob/a2ef34caf4eec1ce90c894e3fdc80ee20e2e4684/luci-app-openclash/files/usr/lib/lua/luci/view/openclash/myip.htm#L354
