### ISSUE TITLE
无法在线更新geoip和内核

### ISSUE THREAD

**Issue by Eintler** [vernesong/OpenClash#1041]
geoip数据库，dev内核，tun内核，game内核全部显示下载失败，请检查网络或稍后再试！

**Comment by vernesong** [comment]
检查curl是否正常，如果开了仅允许内网，先关闭试试

**Comment by Eintler** [comment]
确实是缺少libwolfssl库导致的，多谢！

**Comment by YukawaMi** [comment]
> 确实是缺少libwolfssl库导致的，多谢！

你这个是怎么解决的

**Comment by Eintler** [comment]
Opkg install libwolfssl Best regards :)On Dec 1, 2020 2:07 PM, YukawaMi <notifications@github.com> wrote:



确实是缺少libwolfssl库导致的，多谢！



你这个是怎么解决的

**Comment by YukawaMi** [comment]
> Opkg install libwolfssl Best regards :)On Dec 1, 2020 2:07 PM, YukawaMi <notifications@github.com> wrote: 确实是缺少libwolfssl库导致的，多谢！ 你这个是怎么解决的 —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

opkg install libwolfssl

**Comment by amaztony** [comment]
我也遇到了，是curl问题；
opkg find libwolfssl*
然后opkg install一下搜到的包
