### ISSUE TITLE
软路由器安装openclash， 更新到41.05，无线路由只做AP使用， 关闭openclash后，发现全部无法上网，有遇到这样情况的吗？

### ISSUE THREAD

**Issue by icucuio** [vernesong/OpenClash#1043]
软路由Wan口拨号正常，外网ip显示连接，就是无法上网，如何诊断是哪里的问题？
感觉是DNS失效导致

**Comment by vernesong** [comment]
看看dnsmasq转发设置删除了吗

**Comment by icucuio** [comment]
> 看看dnsmasq转发设置删除了吗

在哪里看？我还是个小白

**Comment by vernesong** [comment]
![Uploading image.png…]()

**Comment by vernesong** [comment]
![image](https://user-images.githubusercontent.com/42875168/100514051-8aef3300-31ac-11eb-90e2-55c50a47efc5.png)

**Comment by icucuio** [comment]
> 看看dnsmasq转发设置删除了吗

果然是那样，停了openclash后，这个地方还保留设置，难怪无法上网
能不能软件可以再停止的时候，把这个设置还原呢？不然不知道的，会耽误好多时间找原因，还找不到

**Comment by vernesong** [comment]
正常情况下会删除啊，你看看什么情况下不会删除
