### ISSUE TITLE
新版 PC能访问 手机端 很多无法访问

### ISSUE THREAD

**Issue by hoowomg** [vernesong/OpenClash#1044]
规则没问题，PC端全部能正常访问，google, youtube,等，
手机有时候访问google提示证书有问题，Pinterest 也无法使用，但是开clash app是可以的。规则一样。
youtube也经常打不开，打开就无法播放视频。

**Comment by hoowomg** [comment]
还有就是telegram这种就完美出国，浏览器访问网页就出问题，手机端 。。

**Comment by b911ss** [comment]
你用的是N1吧

**Comment by vernesong** [comment]
检查dns相关，dns没到clash

**Comment by xxllllll** [comment]
> 还有就是telegram这种就完美出国，浏览器访问网页就出问题，手机端 。。

老哥，有没有解决？
