### ISSUE TITLE
树莓派4B开启不了

### ISSUE THREAD

**Issue by itnewgay** [vernesong/OpenClash#1046]
用的是树莓派4B刷的OPENWRT ,基本设置里内
![image](https://user-images.githubusercontent.com/43598975/100540456-6fe9f500-3278-11eb-87cf-fd24ed2dbf2d.png)
核该怎么去选择啊》[](url)

显示内核是 
![image](https://user-images.githubusercontent.com/43598975/100540637-6c0aa280-3279-11eb-914d-f94cfed34afd.png)

**Comment by itnewgay** [comment]
aarch64_cortex-a72  树莓派4B显示是这个CPU架构。

**Comment by hcym** [comment]
v8可以用，v2ray我也是用这个架构上传

**Comment by cnsunyour** [comment]
armv8
