### ISSUE TITLE
应用订阅配置失败

### ISSUE THREAD

**Issue by BruceLee569** [vernesong/OpenClash#1049]
请问筛选节点的遵循的什么语法格式？wiki中没有详细说明，我用示例格式`香港、台湾&bgp`会应用失败，报错信息如下：
```
Parse config error: proxy group[0]: `use` or `proxies` missing
```

不填或者填其他格式不会报错，比如`不限流量`成功，`不限流量、1倍`失败，或判断确定是用的中文的顿号么？

**Comment by vernesong** [comment]
![image](https://user-images.githubusercontent.com/42875168/100692212-4b4f6380-33c5-11eb-82de-05802dab5522.png)

**Comment by BruceLee569** [comment]
懂了，谢谢！格式示例容易有歧义🤣
