### ISSUE TITLE
GEOIP数据库下载链接变更

### ISSUE THREAD

**Issue by lifetyper** [vernesong/OpenClash#105]
旧的maxmind数据库直接下载地址已经失效，按照官方的要求，必须注册账号使用自己的license key下载数据库。

最后的下载地址类似："https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country&license_key=YOUR_KEY_HERE&suffix=tar.gz"

官方文档：https://dev.maxmind.com/geoip/geoipupdate/

不确定单个key是否可以大量下载，建议增加一个配置项，让用户自己填入自己的license key用于更新maxmind的数据库。

**Comment by lifetyper** [comment]
我现在是自己硬改/usr/share/openclash/openclash_ipdb.sh里的地址为我自己的下载地址

**Comment by lifetyper** [comment]
也可以参考luci-app-clash，改用Dreamacro的：https://github.com/Dreamacro/maxmind-geoip

**Comment by longkerdandy** [comment]
现在最新版openclash GEOIP Update是什么情况了？
