### ISSUE TITLE
网易云音乐解锁与fake-ip模式

### ISSUE THREAD

**Issue by qin9125** [vernesong/OpenClash#1051]
求助各位大佬，0.41.06 redir混合模式解锁网易云解锁一直正常，fake-ip混合只能听一会就解锁失效了，求问一下这个怎么搞？无论哪个模式都是一样的配置规则文件，是要改规则还是说哪里需要设置？

**Comment by vernesong** [comment]
咨询作者看插件需要用到哪些域名去查询，加到fakeip黑名单里去

**Comment by vernesong** [comment]
音乐这些ip一般走geoip了

**Comment by qin9125** [comment]
> 音乐这些ip一般走geoip了

测试了好几个固件，不行，开了fake-ip模式，解锁就失效，包括lean版内置网易解锁的，开fake-ip模式仍然一会失效，我记之前我是用加了规则解锁网易云的正常那是早之前的openclash版本，后面随着openclash更新规则也出现了解锁一会就失效我一直以为是规则挂了，转而用插件解锁，插件现在也是fake模式一会失效，是不是openclash后期版本fake模式与这类解锁冲突呢？只有Redir模式正常

**Comment by pikachullk** [comment]
https://github.com/project-openwrt/luci-app-unblockneteasemusic/issues/41#issuecomment-739255555
