### ISSUE TITLE
有一个问题想要问问大家，关于Nameserver和Fallback

### ISSUE THREAD

**Issue by Faramitas** [vernesong/OpenClash#1055]
这两个分别是在什么情况下会调用，redir-host与Fake-ip这两个模式下调用的方式是一样的吗？

**Comment by Faramitas** [comment]
我最近使用adguard，并且运行了两个，分别为127.0.0.1:7777 与 127.0.0.1:8888，分别对应国内DNS与国外DNS，我该如何设置才能实现国内的查询7777，而国外查询8888，我现在设置国内为127.0.0.1:7777（国内DNS），Fallback设置为8888（国外），但是在访问国外时，仍会查询7777，另外我使用的是redir-host（国内不过openclash那个模式）

**Comment by Nepmonts** [comment]
Fake-IP 模式下域名使用Nameserver进行DNS查询，被污染或命中规则则转发至代理服务器远端DNS解析。
Redir-Host模式下域名使用Nameserver进行DNS查询，等待返回结果后再尝试进行规则判定和连接，当判定需要代理时，使用Fallback组DNS的查询结果进行通讯。

**Comment by gogorush** [comment]
好像确实有这种问题，应该是fallbakc之后的dns查询没走代理，目前我自己的解决办法是把fallback里面的dns配置成自己在国内的代理，然后通过这种手段加速，不然这种国外访问不通过代理的方式太慢了。

**Comment by lnaxk** [comment]
= =如果你不查询国内的dns怎么知道哪些域名指向的是国外还是国内呢，只有先查询国内的dns给的是国外的ip后，才会再用国外的dns查询ip。
