### ISSUE TITLE
v4106同一个固件,同样的另一台R2s,昨天安装正常,今天安装报错,

### ISSUE THREAD

**Issue by chisenin** [vernesong/OpenClash#1056]
昨天(20201203)还正常安装的openclash0.41.06今天(20201204)安装出错了
返回个脚本错误Collected errors:
 * pkg_run_script: package "luci-app-openclash" preinst script returned status 1.
 * preinst_configure: Aborting installation of luci-app-openclash.
 * opkg_install_cmd: Cannot install package luci-app-openclash.
收集的错误：
  * pkg_run_script：包“ luci-app-openclash” preinst脚本返回状态1。
  * preinst_configure：中止安装luci-app-openclash。
  * opkg_install_cmd：无法安装软件包luci-app-openclash。

请教如何解决?尝试了重新下载/重置固件/重刷固件

**Comment by vernesong** [comment]
一般都是某个依赖的问题导致这个错误
opkg install --verbosity=3 /tmp/*.ipk
查看具体错误

**Comment by chisenin** [comment]
弄明白了，应该是固件的版本问题，安装之前只更新软件包列表，先装依赖就没问题，安装之前先执行了升级软件包的命令，再安装依赖，之后再安装openclash就出错。应该是升级软件包时升级了某些依赖，导致版本不符合。
