### ISSUE TITLE
41.06 配置文件启动bug，显示启用其实未启用，而是启用别的配置文件

### ISSUE THREAD

**Issue by icucuio** [vernesong/OpenClash#1059]
软件显示的是启用的 crossxyz ，实际并不是，crossxyz配置并没有被成功启动
![image](https://user-images.githubusercontent.com/69136587/101252588-29edcf00-3759-11eb-96a1-d502d60adaec.png)
日志里面也提示，retore 的是update配置文件
![image](https://user-images.githubusercontent.ccom/69136587/101252856-3e31cc00-3759-11eb-90e9-b022d8b70f5d.png)

**Comment by MrSeven590** [comment]
我的情况是，显示的是DNS自定义，但配置文件启动的是未修改的，导致dns出错，后面手动修改配置文件为自定义的dns之后才能正常上网
