### ISSUE TITLE
添加检测是否存在两个external-controller

### ISSUE THREAD

**Issue by HinataKato** [vernesong/OpenClash#106]
我管理面板死活连不上，排查半天才发现有两个external-controller

**Comment by vernesong** [comment]
有检测的，你发下配置，看是不是有特殊符号导致没有匹配到

**Comment by HinataKato** [comment]
> 有检测的，你发下配置，看是不是有特殊符号导致没有匹配到

是真的没有，的确是有两个external-controller，我手动删掉一个才能连上

**Comment by HinataKato** [comment]
![IMG_20200104_021127_957](https://user-images.githubusercontent.com/57648531/71740613-a4ea9d80-2e97-11ea-8cee-b6606001d3d3.jpg)
这个是我订阅转换带的默认配置，当时看的确有两个（

**Comment by vernesong** [comment]
https://github.com/vernesong/OpenClash/blob/fc89b9ccded76d2ecca4d7697ca3b53ff89faeac/luci-app-openclash/files/usr/share/openclash/yml_change.sh#L87
这几句不应该没起作用吧

**Comment by HinataKato** [comment]
> https://github.com/vernesong/OpenClash/blob/fc89b9ccded76d2ecca4d7697ca3b53ff89faeac/luci-app-openclash/files/usr/share/openclash/yml_change.sh#L87
> 
> 
> 这几句不应该没起作用吧

我之前看的时候一个在上，一个在下就很奇怪，我晚上看看能不能复现

**Comment by hsghost** [comment]
I feel that the `grep` command might have be fooled again by an output truncation, just like I advised in #69 .

**Comment by HinataKato** [comment]
> https://github.com/vernesong/OpenClash/blob/fc89b9ccded76d2ecca4d7697ca3b53ff89faeac/luci-app-openclash/files/usr/share/openclash/yml_change.sh#L87
> 
> 
> 这几句不应该没起作用吧

我手动测试了一下，把external-controller: 127.0.0.1:9090手动塞了个地方，的确被替换了，可能是我当时是通过下载配置来使用Clash的
