### ISSUE TITLE
配置文件提示“proxies is not a slice" 怎么回事？

### ISSUE THREAD

**Issue by icucuio** [vernesong/OpenClash#1061]
实在找不到原因了
提示在香港节点的位置 proxies is not a slice
![image](https://user-images.githubusercontent.com/69136587/101269860-13259780-37ae-11eb-8692-bfae6ff1724e.png)

**Comment by Estrell9** [comment]
您好，请问一下这个问题怎么进行解决

**Comment by Estrell9** [comment]
您好，请问一下这个问题怎么进行解决

**Comment by Estrell9** [comment]
您好，请问一下这个问题怎么进行解决

**Comment by Sherlocksuper** [comment]
我也遇到了，有解决办法吗
