### ISSUE TITLE
规则只有direct的情况下网络变差是因为dns设置有问题吗

### ISSUE THREAD

**Issue by smallst** [vernesong/OpenClash#1064]
最近的网络体验突然变得越来越差，今天试着将配置文件中的代理规则全部删除，只保留了
```
- MATCH,DIRECT
```
发现这种情况下理论上应该和不开 openclash 的网络情况是一致的对吧，但实际上比关闭 openclash 要差很多，比如打开bilibili时会出现几十个request无响应（或者响应慢）的情况。这种一般是什么原因呢？是dns劫持设置的不对吗？

**Comment by vernesong** [comment]
direct直接走本地网络出去，区别在于clash设置的几个dns，你多换几个试试

**Comment by smallst** [comment]
好的，如果选择不自定义dns是会使用端局通告的dns吗

**Comment by vernesong** [comment]
路由默认会启用dns，必须设置nameserver
