### ISSUE TITLE
41.06 更新geoip或者内核后，导致curl调用超时

### ISSUE THREAD

**Issue by Eintler** [vernesong/OpenClash#1065]
lean自带的ddns也显示为fakeip的198.18.0.1/16，transmission的tracker也连不上了。
求解。

**Comment by vernesong** [comment]
ddns在fakeip模式下需要在dns高级设置填写黑名单

**Comment by Eintler** [comment]
哦，我又看了一下，更新完后resolv.conf被修改完为了127.0.0.1了，导致ddns，包括transmission都无法访问外网了。
