### ISSUE TITLE
启用 connerHua(规则集）规则。。。for false:FalseClass  

### ISSUE THREAD

**Issue by Job28703** [vernesong/OpenClash#1067]
connerHua(规则集）规则。。。错误

2020-12-10 16:35:24 Set 198.18.0.1/16 REJECT Rule Error: undefined method `grep' for nil:NilClass
2020-12-10 16:35:24 Set lhie1 Rules Error: undefined method `has_key?' for false:FalseClass

**Comment by Job28703** [comment]
v0.41.06版本

**Comment by vernesong** [comment]
更新一下lhie1规则

**Comment by xpn282** [comment]
connerHua(规则集）规则更新后，不能使用，规则失效，Google，YouTube的上不了。使用lhie1规则没问题。
<img width="725" alt="截屏2020-12-11 上午10 50 17" src="https://user-images.githubusercontent.com/53807602/101855980-6711f100-3b9f-11eb-9136-679e3dfdd4be.png">
<img width="905" alt="截屏2020-12-11 上午10 50 37" src="https://user-images.githubusercontent.com/53807602/101855985-68dbb480-3b9f-11eb-83c0-b589e5ebe795.png">
<img width="908" alt="截屏2020-12-11 上午10 49 50" src="https://user-images.githubusercontent.com/53807602/101856025-785afd80-3b9f-11eb-843a-dbd6fbb73def.png">

**Comment by win28703** [comment]
就是规则更新后，不能使用Google，YouTube上。無論是redir或是fake 只要更新，不能使用Google，YouTube。v0.41.07版本也是一樣
