### ISSUE TITLE
开启openclash后，平板电脑都正常，手机翻不了墙....

### ISSUE THREAD

**Issue by xxllllll** [vernesong/OpenClash#1068]
开启openclash后，平板电脑都正常，手机翻不了墙
fake-ip模式 查看clash连接后发现平板电脑都是有域名的，但手机是IP段 这是为什么？
![image](https://user-images.githubusercontent.com/44605747/101874045-1613f400-3bc3-11eb-93d5-a8f3aba3c456.png)
![image](https://user-images.githubusercontent.com/44605747/101874084-23c97980-3bc3-11eb-93c9-e553855e8b68.png)
各位大佬有没有遇到这种事情过啊...

**Comment by xxllllll** [comment]
> 手机开了doh之类的安全dns吗

应该没有，而且后来发现mac和ipad解析出来是域名，win和android解析出来是ip段…人晕了

**Comment by magiccpp** [comment]
手机的DNS手动配置为软路由的IP试下

**Comment by xxllllll** [comment]
> 手机的DNS手动配置为软路由的IP试下

好像有点用处，我再试几天，谢谢

**Comment by zero8427** [comment]
后来这个问题解决了吗？现在我也遇到了

**Comment by leewei5202** [comment]
重启一下移动网络就行了，被运营商的dns污染了

**Comment by RichKyle** [comment]
我的移动设备都无法翻，只有PC可以。。。

**Comment by gogogogood** [comment]
我也一样

**Comment by Gao-HaoYuan** [comment]
> 重启一下移动网络就行了，被运营商的dns污染了

还真是，不过我是重启手机

**Comment by KeterCo** [comment]
手机WIFI设置里面，第一个dns改为114.114.114.114就好了。我是作为旁路由，所以第二个dns是主路由的IP。

**Comment by yibendao66** [comment]
我也是这个情况我都要崩溃了 我两个设备都这样 旁路由我没有用M开头那个内核就好用了不知道是咋回事

**Comment by guanfengde** [comment]
> 手机WIFI设置里面，第一个dns改为114.114.114.114就好了。我是作为旁路由，所以第二个dns是主路由的IP。

我这么试了下，解决了，但是原因是什么？没想通。

**Comment by KeterCo** [comment]
> 我这么试了下，解决了，但是原因是什么？没想通。



我的理解是openclash如果位于旁路由，你手机也连接了旁路由，那么，如果它没有开启旁路由监听53端口服务（dns代理转发服务），也就是说，你如果是DHCP，那dns请求直接就转发给了主路由，所以openclash失效。这是DHCP为什么不行。
至于如何开启监听53端口服务，我这里是参考步骤（共4步，不建议搞）：
1. 配置 OpenClash DNS 设置：
OpenClash → 设置 → DNS 设置中：
DNS 模式选择：Fake-IP 或 Redir-Host
勾选：启用 DNS 劫持
自定义监听端口为 53（或用 dnsmasq 代理）

2. 防火墙规则（旁路由上）
拦截所有设备对外的 DNS 请求（强制转发给旁路由）
iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53
iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53


3. 主路由 DHCP 设置调整：
DHCP 设置中，DNS服务器 填写旁路由的 IP（如 192.168.1.2），备用 DNS 留空。


4. 确认旁路由监听端口：
netstat -nlp | grep 53
应该能看到 0.0.0.0:53 被监听（如由 dnsmasq 或 Clash Core 接管）


第二个问题：
为什么主路由IP设置为第一个dns不能用，必须设置为114.114.114.114才可以用？

答：
主路由IP（假设是192.168.1.1）无法作为 DNS 服务中转或被 OpenClash 的旁路由截获处理。
即：手机的 DNS 请求发给主路由（192.168.1.1）时，OpenClash 无法“劫持”这类 DNS 请求。

而你设置为 114.114.114.114 时，可以生效，是因为手机的 DNS 请求被当作普通数据流量走旁路由转发出去了，整个 DNS 查询过程走的是 Clash 的代理规则。

如何解决：
方案一（不推荐）：在旁路由启用 DNS 劫持（iptables）
让旁路由强制拦截所有 53 端口请求，统一送入 Clash 处理。
旁路由执行：
iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53
iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53
> 前提：旁路由必须监听 53 端口（例如使用 dnsmasq 或 Clash DNS 模块），否则客户端会查不到 DNS。



方案二：DHCP 服务器指向旁路由做 DNS
关闭主路由的 DHCP
由旁路由提供 DHCP 服务（可以用 dnsmasq）
设置旁路由 IP 为默认网关和 DNS

这样手机/电脑 DHCP 自动获取 IP 后，DNS 和网关都指向旁路由，所有流量包括 DNS 都能被 Clash 接管。
