### ISSUE TITLE
有个疑问，开了这个必须玩游戏开加速器必须关闭openclash

### ISSUE THREAD

**Issue by b911ss** [vernesong/OpenClash#1070]
有个疑问，开了这个必须玩游戏开加速器必须关闭openclash，否则不会走加速器，或者走但是会掉线，用隔壁家的merlinclash就没有这问题，是相同的full规则模板，同一个机场，是我的设置问题吗？有没有大佬指点一下，会不会是openclasah的规则匹配有些不一样导致的呢

**Comment by vernesong** [comment]
可以看一下控制面板，如果流量是直连的就没问题

**Comment by yhl452493373** [comment]
udp转发关了

**Comment by b911ss** [comment]
> udp转发关了

谢谢

**Comment by b911ss** [comment]
> 可以看一下控制面板，如果流量是直连的就没问题

好的

**Comment by CuGooo** [comment]
请问老哥解决问题了吗？我用的是华硕官改，加速器是PC端的UU
