### ISSUE TITLE
第三方规则更新后，不能使用Google，YouTube上。無論是redir或是fake 只要規則更新，不能使用Google，YouTube

### ISSUE THREAD

**Issue by win28703** [vernesong/OpenClash#1071]
网站访问检查。。。。。。第三方规则更新后，不能使用Google，YouTube

**Comment by win28703** [comment]
16:35:24 Set 198.18.0.1/16 REJECT Rule Error: undefined method grep' for nil:NilClass 
 16:35:24 Set lhie1 Rules Error: undefined method has_key?' for false:FalseClass

v0.41.06,v0.41.07版本 出現,网站访问检查 YouTube 異常

**Comment by vernesong** [comment]
神机规则地址变了，等更新修复
