### ISSUE TITLE
最新版本安装ruby和ruby-yaml之后依然显示ruby依赖报错

### ISSUE THREAD

**Issue by aprilies** [vernesong/OpenClash#1073]
从命令行安装ruby和ruby-yaml之后，依然提示检查配置文件出错，重启路由器无用。
找不到解决方法，更新的是v0.41.08，dev和tun内核都是最新版本。只能回退到v0.40.15没开始用ruby的版本。

**Comment by dahuang0210** [comment]
同样问题+1，昨晚更新了4107，也是报这个错误。

**Comment by cnsunyour** [comment]
我之前也是，后来重新编译了固件，把 ruby 和 ruby-yaml 加了进去，就完全没问题了。

**Comment by hcym** [comment]
依赖还是编译的好用，

**Comment by konbar** [comment]
我也是回退到v0.40.15。。现在稳稳的。。。暂时不想升级到最新的版本了。。折腾好多次感觉还是回退到v0.40.15最好用。。

**Comment by nonokiss** [comment]
我上传到/tmp，目录下，cd /tmp 
然后 opkg install ruby-yaml*.ipk --force-depends，还是到网站上去下载，还是装不上。。。

**Comment by addwaj** [comment]
同样问题，启动客户端时提示ruby依赖未正常运行，并且配置文件状态显示为检查失败。通过文件传输方式安装的ruby和ruby-yaml。

**Comment by cnsunyour** [comment]
上面几位你们可能需要重新编译包含所有依赖的固件

**Comment by konbar** [comment]
是的，我已重新编译，改天试试最新版的。

**Comment by xuezhi420** [comment]
和我情况一样，

**Comment by vernesong** [comment]
ruby的依赖不止这两个，他们还依赖了其他包，如果是最近编译的固件一般直接 `opkg update` 然后 `opkg install ruby-yaml` 就行

**Comment by 523295116** [comment]
同样的问题，你们都解决了，啊？》

**Comment by aprilies** [comment]
> 同样的问题，你们都解决了，啊？》

我是重刷openwrt解决的

**Comment by ZerOri** [comment]
> 同样问题，启动客户端时提示ruby依赖未正常运行，并且配置文件状态显示为检查失败。通过文件传输方式安装的ruby和ruby-yaml。

请问哪里下载的

**Comment by tgfcer** [comment]
> > 同样的问题，你们都解决了，啊？》
> 
> 我是重刷openwrt解决的

要重刷新版本？

**Comment by tgfcer** [comment]
> ruby的依赖不止这两个，他们还依赖了其他包，如果是最近编译的固件一般直接 `opkg update` 然后 `opkg install ruby-yaml` 就行

大佬，如果是2020/9编译的固件呢？是不是安装ruby也没用？是不是要退回到0.37版本才能用？

**Comment by addwaj** [comment]
ruby依赖包不止两个，如果你的固件没有补上试试：ruby，ruby-bigdecimal，ruby-date，ruby-dbm，ruby-digest，ruby-enc，

  ruby-pstore，ruby-psych，ruby-stringio，ruby-strscan，ruby-yaml

**Comment by tgfcer** [comment]
> ruby依赖包不止两个，如果你的固件没有补上试试：ruby，ruby-bigdecimal，ruby-date，ruby-dbm，ruby-digest，ruby-enc，
> 
>   ruby-pstore，ruby-psych，ruby-stringio，ruby-strscan，ruby-yaml

谢谢，我回头试试

**Comment by ZerOri** [comment]
> ruby依赖包不止两个，如果你的固件没有补上试试：ruby，ruby-bigdecimal，ruby-date，ruby-dbm，ruby-digest，ruby-enc，
> 
>   ruby-pstore，ruby-psych，ruby-stringio，ruby-strscan，ruby-yaml

艹 ruby全家桶啊，难怪我装完首页的依赖还是不行。不过已经转投helloworld了，open clash实在有点难搞

**Comment by sunzy** [comment]
> > ruby依赖包不止两个，如果你的固件没有补上试试：ruby，ruby-bigdecimal，ruby-date，ruby-dbm，ruby-digest，ruby-enc，
> >   ruby-pstore，ruby-psych，ruby-stringio，ruby-strscan，ruby-yaml
> 
> 艹 ruby全家桶啊，难怪我装完首页的依赖还是不行。不过已经转投helloworld了，open clash实在有点难搞

我重装ruby、重新刷固件都不行。。
helloworld是什么？

**Comment by ZerOri** [comment]
> > > ruby依赖包不止两个，如果你的固件没有补上试试：ruby，ruby-bigdecimal，ruby-date，ruby-dbm，ruby-digest，ruby-enc，
> > >   ruby-pstore，ruby-psych，ruby-stringio，ruby-strscan，ruby-yaml
> > 
> > 
> > 艹 ruby全家桶啊，难怪我装完首页的依赖还是不行。不过已经转投helloworld了，open clash实在有点难搞
> 
> 我重装ruby、重新刷固件都不行。。
> helloworld是什么？

oc不编译固件刷入很难搞 hello world（vssr）相对简单很多

**Comment by wxxingkong** [comment]
> ruby 的依赖不止这两个，他们还依赖了很多其他的包，如果是最近的一般会直接`opkg update`然后`opkg install ruby-yaml`就行

感谢，按你说的方法来之后直接搞定了

**Comment by zerona2018** [comment]
ruby-dbm 这个 我opkg 装不上，其他的ruby 相关都已经安好了。能再看下ruby的相关软件吗？
