### ISSUE TITLE
最新41.08运行一段时间导致完全无法上网，软路由后台都无法进入

### ISSUE THREAD

**Issue by hououinkami** [vernesong/OpenClash#1075]
最新41.08下，运行一段时间后发现墙内墙外都无法上网，软路由后台也无法进入，重启软路由后正常，但过一段时间又如此，本来以为是系统问题昨天重刷系统后依然这样的问题，退后41.07后就正常了。
软路由运行的是LEDE

**Comment by Job28703** [comment]
之前測41.07 曾有此情況，但綁定網路接口（WAN）後，就不會了。

**Comment by hououinkami** [comment]
> 之前測41.07 曾有此情況，但綁定網路接口（WAN）後，就不會了。

请问如何操作呢？谢谢
