### ISSUE TITLE
PS4 怪物猎人 无法联机

### ISSUE THREAD

**Issue by PengDavin** [vernesong/OpenClash#1076]
目前遇到的情况：
1，不开启任何代理， 直连 ps4 nat 类型为 2，联机很不稳定，经常掉线 
2，开启fake-ip tun/game 模式， ps4 全局， 无法获取nat 类型， 无法联机
3，开启 redir-host tun/game，开udp转发，  ps4 nat类型为2 ， 无法联机
确认节点都支持udp

==============OpenClash 调试日志===========

生成时间: 2020-12-15 00:55:14
插件版本: v0.41.08-beta
隐私提示: 上传此日志前请注意检查、屏蔽公网IP、节点、密码等相关敏感信息

```

#===================== 系统信息 =====================#
主机型号: Intel(R) Celeron(R) CPU J1900 @ 1.99GHz : 4 Core 4 Thread
固件版本: OpenWrt SNAPSHOT r0-1cb353d
LuCI版本: git-20.256.12360-1a54222-1
内核版本: 5.4.72
处理器架构: x86_64

#此项在使用Tun模式时应为ACCEPT
防火墙转发: ACCEPT

#此项有值时建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: 

#此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 127.0.0.1#7874

#===================== 依赖检查 =====================#
dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
jsonfilter: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
iptables-mod-tproxy: 已安装
iptables-mod-extra: 已安装
libcap: 已安装
libcap-bin: 已安装
ruby: 已安装
ruby-yaml: 已安装
kmod-tun(TUN模式): 已安装
luci-compat(Luci-19.07): 已安装

#===================== 内核检查 =====================#
运行状态: 运行中
进程pid: 8617
运行权限: 8617: = cap_dac_override,cap_net_bind_service,cap_net_admin,cap_net_raw,cap_sys_resource+eip
运行用户: nobody
已选择的架构: linux-amd64

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 2020.11.23.g4474306
Tun内核文件: 存在
Tun内核运行权限: 正常

Game内核版本: v0.17.0-232-ge389e33
Game内核文件: 存在
Game内核运行权限: 正常

Dev内核版本: v1.3.0-2-g994cbff
Dev内核文件: 存在
Dev内核运行权限: 正常

#===================== 插件设置 =====================#
当前配置文件: /etc/openclash/config/nsfwCloud.yaml
启动配置文件: /etc/openclash/nsfwCloud.yaml
运行模式: fake-ip-tun
默认代理模式: rule
UDP流量转发(tproxy): 停用
DNS劫持: 启用
自定义DNS: 停用
IPV6-DNS解析: 停用
禁用Dnsmasq缓存: 启用
自定义规则: 启用
仅允许内网: 停用
仅代理命中规则流量: 启用
仅允许常用端口流量: 停用
绕过中国大陆IP: 停用

#启动异常时建议关闭此项后重试
混合节点: 停用
保留配置: 停用
第三方规则: 停用

**Comment by vernesong** [comment]
节点配置文件里udp: true写了没，没写只会直连，仅代理命中规则流量暂时停用测试

**Comment by PengDavin** [comment]
> 节点配置文件里udp: true写了没，没写只会直连，仅代理命中规则流量暂时停用测试

嗯，确认过节点配置都写udp: true了
![image](https://user-images.githubusercontent.com/12111412/102217891-2f48d780-3f18-11eb-9014-730b6b3e143d.png)

**Comment by vernesong** [comment]
SSR是否正常？我这边原因待查，暂时无设备测试

**Comment by PengDavin** [comment]
> SSR是否正常？我这边原因待查，暂时无设备测试

试过用SSRP或PW都是可以连接的，不过可能是某些节点速度问题导致有时会掉线
觉得网速还是clash稳一些因为会自动切换节点

**Comment by vernesong** [comment]
![image](https://user-images.githubusercontent.com/42875168/102351657-c332a600-3fe1-11eb-851d-5bf8da5be8a6.png)
他们跟这个模式原理相近，仅代理命中规则流量停用，测试时在控制面板可以看到连接情况

**Comment by PengDavin** [comment]
> ![image](https://user-images.githubusercontent.com/42875168/102351657-c332a600-3fe1-11eb-851d-5bf8da5be8a6.png)
> 他们跟这个模式原理相近，仅代理命中规则流量停用，测试时在控制面板可以看到连接情况

刚刚测试过了，还是不行
- 设置
![image](https://user-images.githubusercontent.com/12111412/102354849-11e23f00-3fe6-11eb-8713-f3e00a6d8c03.png)
- 连接情况 （配置规则用[带Urltest]转换模板）
![image](https://user-images.githubusercontent.com/12111412/102355042-481fbe80-3fe6-11eb-955d-ee527e901144.png)
- PS4网络连接测试
![image](https://user-images.githubusercontent.com/12111412/102355153-700f2200-3fe6-11eb-9d69-d0ee789e0fb6.png)
- 怪物猎人 游戏里无法联机

**Comment by vernesong** [comment]
可能是vmess的udp有问题，换个协议吧

**Comment by linchen123** [comment]
vmess 不行我试过 trojan 和 ss可以，我是直接 SRC-IP-CIDR,(ps4 ip) 让它全局翻 trojan+fake-ip 混合 
NAT2 很稳 怪物猎人 玩了一年多，当然你节点老丢包也不行

**Comment by PengDavin** [comment]
> vmess 不行我试过 trojan 和 ss可以，我是直接 SRC-IP-CIDR,(ps4 ip) 让它全局翻 trojan+fake-ip 混合
> NAT2 很稳 怪物猎人 玩了一年多，当然你节点老丢包也不行

唉。。可惜我买的机场好像没有trojan协议的节点
我试过在规则里添加【- SRC-IP-CIDR,192.168.50.100/32,Proxy】尝试让我的ps4走全局翻
可是好像不起作用，一看连接，几乎都是直连啊。。
![image](https://user-images.githubusercontent.com/12111412/102444378-0f262f00-4064-11eb-8625-3e364fdc8c36.png)

**Comment by linchen123** [comment]
- SRC-IP-CIDR,192.168.50.100/32, 指定一个节点的名字 
用ss/ssr也可以的

**Comment by PengDavin** [comment]
> * SRC-IP-CIDR,192.168.50.100/32, 指定一个节点的名字
>   用ss/ssr也可以的

谢谢回答，我用这个规则把ps4直连了，用fake-ip增强模式，算是联到机了，不过还是有点不稳定

**Comment by RebelliousWhiz** [comment]
> SSR是否正常？我这边原因待查，暂时无设备测试
 
@vernesong 

我手上有台闲置的ps4，可以提供给你测试使用。可以通过telegram @rebelliouswhiz联系我，或者rebelliouswhiz#outlook.com（替换#为@）。

给我发一封信息，随机一点的，我去除个人信息后在这里和你核对，然后安排寄送给你。

我支持过shadowsocks-manager的Gu，给shadowsocks-libev付钱请人改过bug，自认为口碑还行，就是不会修代码... 你可以找Gu问一下，他的telegram应该是公开的。

当然测试完要还给我😂

**Comment by vernesong** [comment]
问题已经解决了，vmess不行，谢谢支持

> > SSR是否正常？我这边原因待查，暂时无设备测试
> 
> @vernesong
> 
> 我手上有台闲置的ps4，可以提供给你测试使用。可以通过telegram @RebelliousWhiz联系我，或者rebelliouswhiz#outlook.com（替换#为@）。
> 
> 给我发一封信息，随机一点的，我去除个人信息后在这里和你核对，然后安排寄送给你。
> 
> 我支持过shadowsocks-manager的Gu，给shadowsocks-libev付钱请人改过bug，自认为口碑还行，就是不会修代码... 你可以找Gu问一下，他的telegram应该是公开的。
> 
> 当然测试完要还给我😂
