### ISSUE TITLE
旁路由要设置iptables吗？偶然发生无网络连接，或者看微信公众号里的图片和视频刷出不来

### ISSUE THREAD

**Issue by RockZhou8** [vernesong/OpenClash#1079]
宿主机，通过PVE虚拟化，搭建了一个主路由和旁路由，双软路由模式
主路由是gocloud高恪，1WAN和LAN1，开DHCP
旁路由是esir的openwrt 精品小包，网口全是LAN，接口中删掉了WAN，所有的LAN桥接到了一起，关DHCP
AP是红米AC2100，LAN口接到旁路由的LAN2口上
现在发现只要是开了openclash之后，刷微信的时候会偶然发生图片 和视频刷新不出来，其他app也会提示当前无网络连接
模式是fakeIP增强模式，没开UDP，代理模式rule
网上有人说旁路由的防火墙要设置iptables，规则如下
`iptables -t nat -I POSTROUTING -j MASQUERADE`
但是我设置之后，上述问题仍然会偶然发生
所以求个旁路由下openclash的食用方法，谢谢各位彦祖了

**Comment by vernesong** [comment]
不需要
先对照 https://github.com/vernesong/OpenClash/wiki/%E7%BD%91%E7%BB%9C%E8%BF%9E%E6%8E%A5%E5%BC%82%E5%B8%B8%E6%97%B6%E6%8E%92%E6%9F%A5%E5%8E%9F%E5%9B%A0 检查DNS劫持
然后进控制面板看日志提示为啥会断开链接

**Comment by RockZhou8** [comment]
> 不需要
> 先对照 https://github.com/vernesong/OpenClash/wiki/%E7%BD%91%E7%BB%9C%E8%BF%9E%E6%8E%A5%E5%BC%82%E5%B8%B8%E6%97%B6%E6%8E%92%E6%9F%A5%E5%8E%9F%E5%9B%A0 检查DNS劫持
> 然后进控制面板看日志提示为啥会断开链接

DNS劫持是对的，跟wiki里一直
刚刚看喜马拉雅的时候也出现白屏了，就立即去日志里看了
time="2020-12-16T12:04:16Z" level=info msg="[TCP] 192.168.1.241:56581 --> xdcs-collector.ximalaya.com match DomainSuffix(xdcs-collector.ximalaya.com) using 🛑 全球拦截[REJECT]"

**Comment by vernesong** [comment]
广告拦截我一般都是直连，reject有概率触发程序自动重试导致变卡

**Comment by RockZhou8** [comment]
> 广告拦截我一般都是直连，reject有概率触发程序自动重试导致变卡

全局拦截Direct 还是出现了微信里图片 视频刷不出来
我手动指定该手机直连试试
- SRC-IP-CIDR,192.168.1.200/32,DIRECT

**Comment by RockZhou8** [comment]
没想到还是会出问题，我 还是想别的办法吧，换固件之类的

**Comment by RockZhou8** [comment]
目前换了esir的旁路由版Openwrt，但还是出现了国内图片 视频出不来，或者淘宝、拼多多商品页面加载刷新不出来，在日志里，看到以下两条warning信息

[TCP] dial 🎯 全球直连 (match DomainSuffix/yangkeduo.com) to pinduoduoimg.yangkeduo.com error: dial tcp4 183.134.95.1:80: connect: no route to host


[TCP] dial 🎯 全球直连 (match DomainSuffix/qq.com) to dns.weixin.qq.com error: dial tcp4 109.244.169.60:443: i/o timeout

**Comment by vernesong** [comment]
旁路由lan口的dns也换一下，插件的DNS的也换几个本地靠谱的
