### ISSUE TITLE
你可以不用

### ISSUE THREAD

**Issue by capewang** [vernesong/OpenClash#1081]
你可以不用

_Originally posted by @Ahtaler in https://github.com/vernesong/OpenClash/issues/984#issuecomment-731490580_

是的我弄完bug什么的我就没用过了

**Comment by Ahtaler** [comment]
![image](https://user-images.githubusercontent.com/55629173/102242887-8610da00-3f35-11eb-8f0c-2c8d1904190f.png)
首先我要为这条Issues打扰大家做个道歉，原帖如下
https://github.com/vernesong/OpenClash/issues/984
我不知道为什么这么多人他单独把我提了出来XD
可能我就是那个“幸运儿”吧
大家晚安
抱歉

**Comment by capewang** [comment]
话说的漂亮

**Comment by Ahtaler** [comment]
那有本事你别关啊

**Comment by 1715173329** [comment]
> ![image](https://user-images.githubusercontent.com/55629173/102242887-8610da00-3f35-11eb-8f0c-2c8d1904190f.png)
> 首先我要为这条Issues打扰大家做个道歉，原帖如下
> #984
> 我不知道为什么这么多人他单独把我提了出来XD
> 可能我就是那个“幸运儿”吧
> 大家晚安
> 抱歉

何必道歉，司马玩意儿也就这能耐

**Comment by 1715173329** [comment]
不就就不用啊，稀罕你用啊¿搁这找存在感呢¿

**Comment by hyird** [comment]
不就就不用啊，稀罕你用啊¿搁这找存在感呢¿
