### ISSUE TITLE
读取配置无法获取服务器地址(已修复)，控制面板rules 空白

### ISSUE THREAD

**Issue by OleStore** [vernesong/OpenClash#1083]
![2020-12-16_221030](https://user-images.githubusercontent.com/1283711/102359335-9edbc700-3feb-11eb-9d88-ac8eb42b7d85.jpg)
@vernesong

**Comment by OleStore** [comment]
稍等，拉码编译一次

**Comment by OleStore** [comment]
服务器地址修复后正常 ，启动正常，但是控制面板rules 都是空白，导致无法出去
![2020-12-16_230858](https://user-images.githubusercontent.com/1283711/102366843-131a6880-3ff4-11eb-9d5f-d35735df20b6.jpg)
@vernesong

**Comment by vernesong** [comment]
好的，我再刷个版本

**Comment by OleStore** [comment]
感谢，问题解决
