### ISSUE TITLE
新版又出現Error: undefined method `grep' for nil:NilClass  無法上youtube

### ISSUE THREAD

**Issue by win28703** [vernesong/OpenClash#1084]
2020-12-17 00:49:30 Set 198.18.0.1/16 REJECT Rule Error: undefined method `grep' for nil:NilClass

**Comment by vernesong** [comment]
规则是空的？

**Comment by Job28703** [comment]
已經清空，再讀取就未出現Rule Error。但也是無法上youtube。V0.41.08是沒問題

**Comment by Job28703** [comment]
V0.41.08 試了B70及R2S ，youtube是OK 。但V0.41.12測，就是youtube無法啟動上網。。。。

**Comment by vernesong** [comment]
规则怎么设置的
