### ISSUE TITLE
中文翻译文件有误

### ISSUE THREAD

**Issue by lifetyper** [vernesong/OpenClash#1085]
最新的0.4.12版本，中文界面里的“服务器与策略组管理” tab，成了英文的“Servers and Groups”。现在是直接升级上来的，没有重新编译整个固件，不知道是不是这个原因。
![屏幕截图 2020-12-17 080453](https://user-images.githubusercontent.com/1171298/102421097-92348e80-403e-11eb-8043-2509d6ca3115.png)

**Comment by OleStore** [comment]
没有啊，我的翻译正常

**Comment by lifetyper** [comment]
> 没有啊，我的翻译正常

我升级了两台都这样，等下我重新编译固件试试
