### ISSUE TITLE
clash二进制文件在r4s上爆 illegal instruction

### ISSUE THREAD

**Issue by lifetyper** [vernesong/OpenClash#1087]
用[这里](https://forum.openwrt.org/t/nanopi-r4s-rk3399-4g-is-a-great-new-openwrt-device/79143/36) patch编译的固件，发现clash一直启动失败，后来发现安装的clash二进制文件都爆illegal instruction,用clash官方的二进制文件是正常的。
可能是固件问题，因为同样的这里的二进制文件在r2s上是可以执行成功的，这两cpu都是armv8的。

不知道会不会跟这个情况类似？
https://github.com/shynome/shynome.github.io/issues/17

还是我编译openwrt的时候需要设置什么选项或者增加什么内核组件呢？

**Comment by vernesong** [comment]
抽空搞个不压缩的下载地址，某些架构可能不支持upx压缩的内核

**Comment by skefy** [comment]
同问题，等待解决。

**Comment by lifetyper** [comment]
更新upx版本之后编译的版本已经可以正常运行了。
