### ISSUE TITLE
OpenClash自动清理防火墙规则

### ISSUE THREAD

**Issue by jamesbean08** [vernesong/OpenClash#1088]
没有注意是哪个版本开始，OpenClash有了一个53端口检测功能，发现系统53被劫持以后，会启动防火墙清理，在版界面上方会出现“发现53端口被劫持，清理防火墙规则...”

现在的问题是，我的网络设置是通过自定义防火墙转发所有dns查询到63端口的AdGuardHome，AGH再转发到53端口的dnsmasq，经过观察这个功能导致大部分设备的dns查询跳过了AGH直接进入了监听53的dnsmasq。请问有没有办法手动关闭这个功能？

**Comment by Job28703** [comment]
系统53被劫持是必需的

**Comment by jamesbean08** [comment]
> 系统53被劫持是必需的

不大明白你的意思，我的理解是openclash的dns设置里面劫持只是劫持dnsmasq下游使其成为dnsmasq的上游，理论上openclash不需要去管dnsmasq之前的dns查询步骤啊

**Comment by openips** [comment]
域名劫持是可选项 界面上去掉就行了

**Comment by jamesbean08** [comment]
> 域名劫持是可选项 界面上去掉就行了

回去我试一下关闭自动域名劫持。不过搜索之前的issue有看到说取消劫持的话每次重启会自动删除dnsmasq转发7874端口的设定。

**Comment by vernesong** [comment]
插件开劫持就会检测，你这种情况需要关闭插件的劫持选项

**Comment by jamesbean08** [comment]
> 插件开劫持就会检测，你这种情况需要关闭插件的劫持选项

目前关闭劫持，手动设置dnsmasq转发#7874正常
