### ISSUE TITLE
0.41.12 Redir-host（兼容模式）udp 转发失效

### ISSUE THREAD

**Issue by fishg** [vernesong/OpenClash#1089]
昨天升级到0.41.12 后， Redir-host（兼容模式）udp 转发失效，clash的连接信息里完全没有udp的请求了

**Comment by vernesong** [comment]
开绕过了吗？

**Comment by fishg** [comment]
> 开绕过了吗？

对，开了国内ip绕过

**Comment by vernesong** [comment]
对啊，绕过了是没有了啊，没到clash

**Comment by fishg** [comment]
> 对啊，绕过了是没有了啊，没到clash

发到海外的udp也没了？

**Comment by vernesong** [comment]
你开了绕过再试，没准海外IP识别成国内了

**Comment by fishg** [comment]
> 你开了绕过再试，没准海外IP识别成国内了

晚上回家我再试试，谢谢

**Comment by fishg** [comment]
回滚0.41.08好了
