### ISSUE TITLE
正常运行代理无效,但是手机端可以正常使用,Mac端不行

### ISSUE THREAD

**Issue by JazPiao** [vernesong/OpenClash#109]
<img width="994" alt="Screen Shot 2020-01-04 at 2 36 00 PM" src="https://user-images.githubusercontent.com/57001499/71760915-a18afc80-2eff-11ea-8740-e0bca64264ec.png">

手机端使用无任何问题. 但是 Mac 上无法使用代理

**Comment by vernesong** [comment]
https://github.com/vernesong/OpenClash/wiki
检查网关和dns
