### ISSUE TITLE
开启openclash后重启路由器，群晖不会自动在路由器upnp端口映射列表中。

### ISSUE THREAD

**Issue by extreme59** [vernesong/OpenClash#1091]
开启openclash自启后，启动路由器后upnp内没有群晖自动端口映射列表。
关闭openclash自启后重启路由器，群晖upnp端口映射正常了。
把群晖ip加入openclash黑名单不代理，开启openclash，重启路由器后群晖在路由器upnp端口映射正常。
我又想代理群晖，又想让群晖自动映射端口，这要怎么解决？

**Comment by icucuio** [comment]
兄弟，怎么把群晖ip加入openclash黑名单不代理？

**Comment by extreme59** [comment]
> 兄弟，怎么把群晖ip加入openclash黑名单不代理？
> 我现在也没法远程使用nas和访问家里的服务器数据库了。

在Issuse里搜群晖就能找到解决方法

**Comment by extreme59** [comment]
我的问题解决了，我试着把禁止DNS缓存选项关了就OK了

**Comment by new1943** [comment]
> 我的问题解决了，我试着把禁止DNS缓存选项关了就OK了

禁止DNS缓存在哪啊？没找到

**Comment by zouyong94** [comment]
禁止DNS缓存在哪啊？没找到
