### ISSUE TITLE
关于ssr节点

### ISSUE THREAD

**Issue by cthcl73** [vernesong/OpenClash#1093]
请问各位大神，openclash是不是对ssr节点支持不好？我已经升级到最新版0.41.12beta.仍然断流严重！谢谢大神们抽点时间回答我的问题

**Comment by vernesong** [comment]
内核的ssr确实存在断流问题，需要等待修复

**Comment by Nepmonts** [comment]
不是大佬的OpenClash对SSR支持不好😂，是因为Clash内核暂时对SSR支持不够好。可以去这里提问一下https://github.com/Dreamacro/clash/issues😀
