### ISSUE TITLE
如何禁止 openclash 自动更新

### ISSUE THREAD

**Issue by Jay54520** [vernesong/OpenClash#1095]
目前的版本对于我已经够用了，更新后可能不稳定。

**Comment by Sanly** [comment]
本身应该不会自动更新，我停在v0.40.7-beta好久了。

**Comment by lifetyper** [comment]
你的openclash能自动更新？

**Comment by Jay54520** [comment]
我的自动变成了 `v0.41.12-beta`

**Comment by Nepmonts** [comment]
不会自动更新，如果不适应新版本可以自己回退至旧版本。

**Comment by YukawaMi** [comment]
不存在后台自动静默升级的功能吧。。。。。。都是要手动的，你用的没问题就可以不管他了
