### ISSUE TITLE
无法更新新版本内核

### ISSUE THREAD

**Issue by Nepmonts** [vernesong/OpenClash#1097]
![image](https://user-images.githubusercontent.com/63834771/102686810-0761b880-4225-11eb-9a87-2d79d95b8bf5.png)
点击‘’检查并更新‘’系统显示更新完成，但是之后还是显示当前版本依然是以前旧版本。

**Comment by harveyhuangw** [comment]
0.41.12 我的貌似也是这样的

**Comment by lifetyper** [comment]
一样的问题，而且更新机制有问题，直接把我tun版本的clash更新没了。

**Comment by Nepmonts** [comment]
![image](https://user-images.githubusercontent.com/63834771/102691043-a77b0a00-4244-11eb-9e0c-70b994fe4c9b.png)
我想可能是因为这里还没有更新吧，等等大佬更新。

**Comment by icucuio** [comment]
遇到同样的问题，两个都存在
1）点击‘’检查并更新‘’系统显示更新完成，但是之后还是显示当前版本依然是以前旧版本。
2） 直接把我tun版本的clash更新没了。

**Comment by OleStore** [comment]
手动替换
https://github.com/vernesong/OpenClash/tree/master/core-lateset
