### ISSUE TITLE
[bug] 如果公网ip换了，不重启下openclash，网络就特别卡，需要手动重新启动下openclash，就网络就正常了，我想应该是DNS的问题

### ISSUE THREAD

**Issue by icucuio** [vernesong/OpenClash#1098]
[bug] 因为我家里的宽带服务商提供了动态公网IP，不定期会换，我发下如果公网ip换了，不重启下openclash，网络就特别卡，需要手动重新启动下openclash，就网络就正常了，我想应该是DNS的问题

**Comment by vernesong** [comment]
你要学会看控制面的日志
