### ISSUE TITLE
openclash开启以后，过一段时间就会显示语法检查错误而且会断网。必须得关闭然后重新启动路由器才可以再次打开。该装的依赖都装了，有什么解决办法么？

### ISSUE THREAD

**Issue by linjunjun231** [vernesong/OpenClash#1099]

**Comment by linjunjun231** [comment]
对了会出现ruby依赖异常，请确认是否正常。我有试过重新安装。但还是一样

**Comment by vernesong** [comment]
在什么情况下重启的？自动更新？

**Comment by linjunjun231** [comment]
> 在什么情况下重启的？自动更新？

是的，自动更新的时候的。更新不上然后就显示ruby依赖异常，检查失败,之后就断网

**Comment by mcgillkwok** [comment]
2020-12-20 20:07:06 Error: Ruby Works Abnormally, Please Check The Ruby Library Depends And Try Again!
2020-12-20 20:05:18 Warning: OpenClash Now Disabled, Need Start From Luci Page, Exit...

**Comment by vernesong** [comment]
这种不稳定的情况无法判断原因，建议还是重新刷个固件

**Comment by caliban511** [comment]
更新订阅时有一定机率发生类似情况，我这边也遇到过，报过类似错误：
Error: Updated Config 【sspool】 Has No Proxy Field, Update Exit...
看提示是订阅遇到问题，但其实没有任何问题，就是需要手动启动一下。
