### ISSUE TITLE
0.33.4 的更新过程存在比较严重的bug（疑），并且更新后dns解析失败

### ISSUE THREAD

**Issue by NV3S** [vernesong/OpenClash#11]
```
C:\Users\*>nslookup t.cn
服务器:  UnKnown
Address:  192.168.100.10

*** UnKnown 找不到 t.cn: Query refused

C:\Users\*>nslookup t.cn
服务器:  UnKnown
Address:  192.168.100.10

*** UnKnown 找不到 t.cn: Query refused
```
openwrt版本用了两个，A版本是OpenWrt R9.8.5（内核 4.19.62），另一个版本老一点R9.7.x（回滚掉了没抓住）。
192.168.100.10是旁路由的地址。
在之前版本中，从0.33.2-0.33.3，配置没有动过，运行正常，刚刚更新0.33.4以后网页无法打开.（配置等见图）

==============
另外刚刚在两个openwrt版本之间测试发现，在A版本，把ipk文件放到/tmp/upload执行opkg install直接安装0.33.4，会把/etc/openclash/clash干掉（之后在luci中点击启动会在线下载），在另一个版本中，把ipk放到/etc/openclash下install，当前整个目录被删除。
![2](https://user-images.githubusercontent.com/17755534/62568321-85871e80-b8bf-11e9-9312-82687e665b79.png)
![3](https://user-images.githubusercontent.com/17755534/62568323-861fb500-b8bf-11e9-91db-4f8097be9f8f.png)
![4](https://user-images.githubusercontent.com/17755534/62568324-861fb500-b8bf-11e9-9c2c-b6fa4b1f6fb3.png)
![5](https://user-images.githubusercontent.com/17755534/62568326-86b84b80-b8bf-11e9-826f-a3aa3f175f17.png)
![1](https://user-images.githubusercontent.com/17755534/62568327-86b84b80-b8bf-11e9-8e14-8dd6f3b43254.png)

**Comment by vernesong** [comment]
安装的问题，你如果点检查更新，应该不会有问题，自己用命令卸载默认会删除所有文件。
连接的问题，`iptables -t nat -nL --line-number` 看一下谁把53端口的流量拿走了
