### ISSUE TITLE
闪存大小不够，想这样挂软链可以吗？

### ISSUE THREAD

**Issue by Xr267** [vernesong/OpenClash#110]
![@4VWJ2 R3N0OYILM50G4}3P](https://user-images.githubusercontent.com/54162377/71765525-f2ffaf80-2f30-11ea-9119-3f3e144a7eec.png)
闪存大小不够用了，简单修改下，通过软链把内核和geoip数据库从tmp挂到/etc/openclash，实测可以正常使用。
这是我想到的一个办法，有大佬指教下，还可以怎么做吗？

**Comment by vernesong** [comment]
没问题，运行过程中这两个文件不会有变动
