### ISSUE TITLE
MWAN3导致YouTube无法访问

### ISSUE THREAD

**Issue by Conrad52** [vernesong/OpenClash#1100]
环境：
软路由：3865U，2G+16G
操作系统：eSir 20201201-欢庆12.1高大全固件
OpenWrt R20.10.20 GDQ v12.1[2020] Compiled by eSir / LuCI Master (git-20.256.12360-1a54222)
OpenClash版本：v0.41.12-beta，运行模式为：Fake-IP（增强）模式

现象：
终端访问YouTube网站，通过 Dashboard 控制面板 ，查看访问YouTube未匹配到对应策略，并且无法打开YouTube。
![image](https://user-images.githubusercontent.com/76394009/102713914-63e8d480-4306-11eb-9feb-e1ac9f42a068.png)

排查过程：
1、再次OpenClash按照油管作者视频进行配置，OpenClash状态正常。链接：https://www.youtube.com/watch?v=Pam8h1V6qaI

2、将OpenClash使用的配置文件，换到Clash for Windows v0.13.7上使用，终端能访问外网网站，正常打开YouTube，可得知配置文件无问题。
![image](https://user-images.githubusercontent.com/76394009/102713934-8d096500-4306-11eb-81ce-85a09a082168.png)

3、参考”网络连接异常时排查原因“，进行排查，并把DNS设置与解决方案二的DNS配置一样。
链接：https://github.com/vernesong/OpenClash/wiki/DNS%E8%AE%BE%E7%BD%AE
![image](https://user-images.githubusercontent.com/76394009/102713802-9e9e3d00-4305-11eb-8bfa-6a78de178453.png)

4、根据”网络连接异常时排查原因“文档，终端使用nslookup解析，回显无198.18.x.x地址，按照大佬 vernesong 的说法，软路由上存在gfw list之类的配置。
![image](https://user-images.githubusercontent.com/76394009/102713891-300daf00-4306-11eb-83ed-196820414946.png)

5、此时查找软路由上的GFW List之类的配置，发现在MWAN3分流助手下，存在此配置，将关闭后，使用nslookup解析。
![image](https://user-images.githubusercontent.com/76394009/102714018-10c35180-4307-11eb-96ac-3328f9633f38.png)
![image](https://user-images.githubusercontent.com/76394009/102714079-639d0900-4307-11eb-9830-6d26d7e0ab28.png)

6、nslookup解析出198.18.x.x的地址后，访问YouTube及外网地址正常。
![image](https://user-images.githubusercontent.com/76394009/102714597-a4e2e800-430a-11eb-93dd-a680eb566d97.png)
![image](https://user-images.githubusercontent.com/76394009/102714591-985e8f80-430a-11eb-9a4f-ce9f55e03c4e.png)

**Comment by openips** [comment]
翻墙节点配置地址黏连 这锅openclash不背 另外mwan的规则可能有问题

**Comment by Conrad52** [comment]
> 翻墙聚烯烃配置地址黏连这锅openclash不背另外mwan的规则可能有问题

我这是有两个ISP线路，所以用了MWAN3，然后再配置的OpenClash，这样的情况下造成的影响。
翻墙节点配置地址黏连 -------------这个在电脑上用同一个配置文件就不会喔，有什么判定方法吗。

**Comment by openips** [comment]
我移动联通电信都有 openclash使用完全正常 先研究一下mwan3怎么配置吧

**Comment by soarsky1991** [comment]
如何解决翻墙节点地址粘连的问题？
