### ISSUE TITLE
配置文件管理卡顿

### ISSUE THREAD

**Issue by FKPYW** [vernesong/OpenClash#1101]
OpenWrt版本：OpenWrt R20.12.12
主题：Argon
openclash版本：v0.41.12-beta
chrome版本： 89.0.4356.6

情况说明：

由于机场几个合并订阅加上规则多，导致配置文件较大。

从openclash处点击配置文件管理的时候，刷新很慢，经常卡死网页。

我怀疑应该是配置文件高亮导致的。因为打开页面需要刷新很久才会显示配置文件高亮。

能否添加一个开关，选择是否开启高亮。

谢谢大佬

**Comment by vernesong** [comment]
这是lua处理的问题，暂时没有太好的办法，高亮是在用户端浏览器执行的，跟这个无关

**Comment by FKPYW** [comment]
谢谢大佬
