### ISSUE TITLE
每次更新完订阅后都需要重新选择节点是怎么回事

### ISSUE THREAD

**Issue by SwordBahamut** [vernesong/OpenClash#1102]
都需要打开控制面板重新选择

**Comment by vernesong** [comment]
节点和策略组名字有特殊字符？

**Comment by SwordBahamut** [comment]
![image](https://user-images.githubusercontent.com/76435501/102874806-e8119800-447d-11eb-885b-d188fc998e82.png)
也没有吧

**Comment by SwordBahamut** [comment]
> 节点和策略组名字有特殊字符？

![image](https://user-images.githubusercontent.com/76435501/102874839-f52e8700-447d-11eb-9237-53360082d79d.png)
也没有吧

**Comment by vernesong** [comment]
手动还原有没有用？

**Comment by SwordBahamut** [comment]
![image](https://user-images.githubusercontent.com/76435501/102875111-53f40080-447e-11eb-9bdb-f1682ad5da8b.png)
![image](https://user-images.githubusercontent.com/76435501/102875185-71c16580-447e-11eb-8adc-6c8911de8acd.png)

这个也试过然后重新订阅 设置完之后还是需要重新选择

**Comment by vernesong** [comment]
![image](https://user-images.githubusercontent.com/42875168/102878250-edbdac80-4482-11eb-82ab-2b56ca66cdc8.png)
这两个按钮，由于每分钟会自动保存一次节点选择，你在控制面板选其他的后马上点还原看看有没有用

**Comment by SwordBahamut** [comment]
> ![image](https://user-images.githubusercontent.com/42875168/102878250-edbdac80-4482-11eb-82ab-2b56ca66cdc8.png)
> 这两个按钮，由于每分钟会自动保存一次节点选择，你在控制面板选其他的后马上点还原看看有没有用

![image](https://user-images.githubusercontent.com/76435501/102889172-1f3f7380-4495-11eb-861b-86f278c7f40c.png)
1.点了还原 然后控制面板没反应
2.选好节点以后保存选择，也没反应。只要是应用选择就不行了

**Comment by SwordBahamut** [comment]
> ![image](https://user-images.githubusercontent.com/42875168/102878250-edbdac80-4482-11eb-82ab-2b56ca66cdc8.png)
> 这两个按钮，由于每分钟会自动保存一次节点选择，你在控制面板选其他的后马上点还原看看有没有用

![image](https://user-images.githubusercontent.com/76435501/102890057-c1ac2680-4496-11eb-994e-7643142d4001.png)
即使选好节点后保存 只要点配置文件检查更新也会重置节点选择

**Comment by vernesong** [comment]
把你/etc/openclash/history/文件夹的内容发出来

**Comment by SwordBahamut** [comment]
> 把你/etc/openclash/history/文件夹的内容发出来

不好意思 前两天装修
[history.tar.gz](https://github.com/vernesong/OpenClash/files/5742127/history.tar.gz)
 这是history文件
