### ISSUE TITLE
openclash无法代理软路由自身流量

### ISSUE THREAD

**Issue by jallenlau** [vernesong/OpenClash#1103]
请教下，我的软路由无论是Fake-ip还是兼容模式，软路由均无法代理自身流量，ping google.com 等外网无法ping通！求大神解答。

**Comment by jallenlau** [comment]
fake-ip下任何网址都无法ping通

**Comment by emacsnt** [comment]
clash自己的问题，openclash无法解决的，回路循环，参考下面的帖子
[https://github.com/Dreamacro/clash/issues/158](https://github.com/Dreamacro/clash/issues/158)
