### ISSUE TITLE
配置文件订阅使用转换模板时无法正确获取节点信息

### ISSUE THREAD

**Issue by 1179098689** [vernesong/OpenClash#1104]
如题。。。

**Comment by OleStore** [comment]
最新源码编译的ipk无法获取节点信息？

**Comment by OleStore** [comment]
> 如题。。。

用最新源码编译测试，没问题

**Comment by 1179098689** [comment]
> [ipk]？



> > 如题。。。
> 
> 用最新源码编译测试,没问题

配置文件订阅+转换模板可以获得节点但是无法使用，但是使用其他的人的网页api转换就没问题

**Comment by OleStore** [comment]
> > [ipk]？
> 
> > > 如题。。。
> > 
> > 
> > 用最新源码编译测试,没问题
> 
> 配置文件订阅+转换模板可以获得节点但是无法使用，但是使用其他的人的网页api转换就没问题

用的哪个模板
