### ISSUE TITLE
[困难求解]编译中的问题

### ISSUE THREAD

**Issue by phantastar** [vernesong/OpenClash#111]
### 系统
Ubuntu 19.10 X64 Server
### 编译目标
openwrt-SNAPSHOT-r11889 X86_64 **(确定有附带luci-compat)**
### 发生时间
大约今天下午1:30
### 经过
1. `git clone https://github.com/vernesong/OpenClash.git` 到本地根目录
2. `luci-app-openclash`文件夹挪动到openwrt编译目录下`~/openwrt/feeds/luci/applications/`
3.    随系统编译 → 刷写并进入系统 → WinSCP放置clash+chmod0755
4.    插件UI操作起来没有异常 → 设置X64核心 → 设置Fake-ip → 设置DNS劫持+自定义DNS

**_5.    订阅配置永远失败_**
**_6.   关闭DNS劫持后再订阅 → 配置替换成功 → 仍旧显示不出来配置_**

> **_7.   上传本地yml格式配置 → UI错位+错位区域显示出错误日志_**
> ![微信截图_20200104162211](https://user-images.githubusercontent.com/25948362/71766249-d5364880-2f38-11ea-8dbc-2b33defd58e4.png)
```
500 内部服务器错误
对不起，服务器遇到未知错误。
/usr/lib/lua/luci/template.lua:97: Failed to execute template 'cbi/simpleform'.
A runtime error occurred: /usr/lib/lua/luci/template.lua:97: Failed to execute template 'cbi/tblsection'.
A runtime error occurred: /usr/lib/lua/luci/template.lua:74: Failed to load template 'cbi/other_button'.
Error while parsing template '/usr/lib/lua/luci/view/cbi/other_button.htm':
No such file or directory
stack traceback:
	[C]: in function 'error'
	/usr/lib/lua/luci/template.lua:74: in function '__init__'
	/usr/lib/lua/luci/util.lua:65: in function 'Template'
	/usr/lib/lua/luci/template.lua:27: in function 'render'
	/usr/lib/lua/luci/cbi.lua:257: in function 'render'
	/usr/lib/lua/luci/cbi.lua:1473: in function 'render'
	/usr/lib/lua/luci/model/cbi/openclash/client.lua:61: in function 'render'
	[string "/usr/lib/lua/luci/view/cbi/tblsection.htm"]:128: in main chunk
stack traceback:
	[C]: in function 'error'
	/usr/lib/lua/luci/template.lua:97: in function 
	(tail call): ?
	/usr/lib/lua/luci/cbi.lua:257: in function 'render'
	/usr/lib/lua/luci/cbi.lua:266: in function 'render_children'
	[string "/usr/lib/lua/luci/view/cbi/simpleform.htm"]:16: in main chunk
stack traceback:
	[C]: in function 'error'
	/usr/lib/lua/luci/template.lua:97: in function 
	(tail call): ?
	/usr/lib/lua/luci/cbi.lua:257: in function 'render'
	/usr/lib/lua/luci/cbi.lua:742: in function 'render'
	/usr/lib/lua/luci/dispatcher.lua:1373: in function '_form'
	/usr/lib/lua/luci/dispatcher.lua:919: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:892: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:440: in function
```

> **_8. 此时OpenClash日志如下:_**
> ![微信截图_20200104162341](https://user-images.githubusercontent.com/25948362/71766257-06167d80-2f39-11ea-9f75-03be32acd943.png)

### 曲线救国成功
1. 卸载luci-app-openclash后重启
2. 重装luci-app-openclash
3. 放置clash+chmod0755
4. 可以正常使用了

### `新年快乐!`

**Comment by vernesong** [comment]
无法判断，可能需要你确认一下是否会稳定出现这种问题

**Comment by zfh135072** [comment]
同样问题，x86-64平台，随系统编译
上传配置提示上传失败。
查看/etc/openclash/下没有config目录，手动创建后，再上传，就出现上面的500内部错误

**Comment by vernesong** [comment]
> 同样问题，x86-64平台，随系统编译
> 上传配置提示上传失败。
> 查看/etc/openclash/下没有config目录，手动创建后，再上传，就出现上面的500内部错误

没有config目录这个问题下午的推送没解决？

**Comment by zfh135072** [comment]
> 
> 
> > 同样问题，x86-64平台，随系统编译
> > 上传配置提示上传失败。
> > 查看/etc/openclash/下没有config目录，手动创建后，再上传，就出现上面的500内部错误
> 
> 没有config目录这个问题下午的推送没解决？

我是今天15:33左右随系统编译的，但是是在上个版本系统是直接更新固件的，不知道有没有影响，升级完，没有config目录

**Comment by vernesong** [comment]
> > > 同样问题，x86-64平台，随系统编译
> > > 上传配置提示上传失败。
> > > 查看/etc/openclash/下没有config目录，手动创建后，再上传，就出现上面的500内部错误
> > 
> > 
> > 没有config目录这个问题下午的推送没解决？
> 
> 我是今天15:33左右随系统编译的，但是是在上个版本系统上直接更新固件的，不知道有没有影响，升级完，没有config目录

目录在安装后会自动创建，目前还没有测试随系统编译的情况

**Comment by phantastar** [comment]
> 无法判断，可能需要你确认一下是否会稳定出现这种问题
重置系统后问题可以同样复现, 在openwrt皮肤下, 可以看到这样的错误提示: 
![微信截图_20200104224942](https://user-images.githubusercontent.com/25948362/71768291-cc9d3c80-2f4f-11ea-947d-7c75f5bae171.png)

**Comment by vernesong** [comment]
已修
```
OpenWrt SNAPSHOT r11892-663b1a1 / LuCI Master git-20.004.33955-4c4d6e2
```
测试通过

**Comment by phantastar** [comment]
> 已修
> 
> ```
> OpenWrt SNAPSHOT r11892-663b1a1 / LuCI Master git-20.004.33955-4c4d6e2
> ```
> 
> 测试通过

### 十分感谢! 
搭配r11895已经可用
![微信截图_20200105130928](https://user-images.githubusercontent.com/25948362/71775506-c98c6580-2fbc-11ea-8313-156977bd39cf.png)
