### ISSUE TITLE
远程无法访问nas，端口转发也没问题，自己分析原因，望版主能看到

### ISSUE THREAD

**Issue by icucuio** [vernesong/OpenClash#1111]
1） 软路由上安装openclash，用的版本是41.13 ，fake-ip 增强模式
2） Wan口试动态公网ip，通过软路由DDNS功能，可以实现域名正确被解析到wan口公网ip地址，可以直接ping 通域名，且ip地址与wan口一致
3） 软路由防火墙正确配置端口转发，把内网nas 端口转发给Wan口

**但是。。。。，远程通过域名+端口访问nas却无法访问！！！！！！！！！！！！！！！！！！**
分析原因，fakeip模式下，nas是通过fake ip 来实现外网连接，而openclash代理后，fakeip和nas 真实的内网ip 无法正确的匹配上，导致了当远程连接的时候，端口映射无法找的正确的nas地址，导致无法访问nas

我问了好多，但始终无法解决，不知哪个大神可以帮我下，甚至可以有偿
QQ 406801643

**Comment by vernesong** [comment]
ddns正常的话，请切换到redir模式，在全局设置下的访问控制禁止nas流量通过代理

**Comment by icucuio** [comment]
> ddns正常的话，请切换到redir模式，在全局设置下的访问控制禁止nas流量通过代理

可是我就想用fake ip 模式呢？ 一定要切换到redir模式下才可以正常吗？

**Comment by terenceng81** [comment]
fakeip tun模式 就解决问题了不是吗？

**Comment by icucuio** [comment]
> fakeip tun模式 就解决问题了不是吗？

谢谢了，真的切换完就解决了。

**Comment by Zeal599** [comment]
> fakeip tun模式 就解决问题了不是吗？

上来给您点赞
