### ISSUE TITLE
启动openclash后提示ruby依赖异常

### ISSUE THREAD

**Issue by senzige300** [vernesong/OpenClash#1112]
安装ruby和ruby-yaml安装不上，依赖也不会添加，哪位大神告诉一下啊，我的是N1软路由

**Comment by lnaxk** [comment]
n1 软件包刷新 然后搜索ruby即可

**Comment by senzige300** [comment]
找了啊，没有啊

**Comment by lnaxk** [comment]
> 找了啊，没有啊

你软件更新的时候上面显示已经刷新吗？你的软件源不对劲吧=

**Comment by senzige300** [comment]
> > 找了啊，没有啊
> 
> 你软件更新的时候上面显示已经刷新吗？你的软件源不对劲吧=

显示了啊，没有啊，在软件包那里吧

**Comment by lnaxk** [comment]
> 找了啊，没有啊

![image](https://user-images.githubusercontent.com/58036663/103132455-8fd9d080-46df-11eb-9e12-e952b6d0b57c.png)

**Comment by senzige300** [comment]
> > 找了啊，没有啊
> 
> ![图片](https://user-images.githubusercontent.com/58036663/103132455-8fd9d080-46df-11eb-9e12-e952b6d0b57c.png)

就是这里，没有。。。。。。。。

**Comment by b911ss** [comment]
ssh输入
opkg update
opkg install ruby
opkg install ruby-yaml
你升级最新版以后看看能不能用，我的过一会就会变成守护进程未运行，你试一下

**Comment by senzige300** [comment]
> > > 找了啊，没有啊
> > 
> > 
> > ![图片](https://user-images.githubusercontent.com/58036663/103132455-8fd9d080-46df-11eb-9e12-e952b6d0b57c.png)
> 
> 已经出来了，就安装那个ruby就可以了吗

现在可以正常启动opencalsh了，但是无法科学上网，而且他这个openclash首页那个ip地址，国内和国外的都一样啊，怎么破？

**Comment by lnaxk** [comment]
> > > > 找了啊，没有啊
> > > 
> > > 
> > > ![图片](https://user-images.githubusercontent.com/58036663/103132455-8fd9d080-46df-11eb-9e12-e952b6d0b57c.png)
> > 
> > 
> > 已经出来了，就安装那个ruby就可以了吗
> 
> 现在可以正常启动opencalsh了，但是无法科学上网，而且他这个openclash首页那个ip地址，国内和国外的都一样啊，怎么破？

节点啊_(:з」∠)_自己订阅你自己的节点

**Comment by lnaxk** [comment]
> > > > 找了啊，没有啊
> > > 
> > > 
> > > ![图片](https://user-images.githubusercontent.com/58036663/103132455-8fd9d080-46df-11eb-9e12-e952b6d0b57c.png)
> > 
> > 
> > 已经出来了，就安装那个ruby就可以了吗
> 
> 现在可以正常启动opencalsh了，但是无法科学上网，而且他这个openclash首页那个ip地址，国内和国外的都一样啊，怎么破？

wiki里详细的教程你可以看看

**Comment by matthuo333** [comment]
你的kernel版本是多少？
