### ISSUE TITLE
即使勾选了udp流量转发，依然无法代理udp流量

### ISSUE THREAD

**Issue by cjwddtc** [vernesong/OpenClash#1113]
redir-host兼容模式，勾选udp流量转发，订阅中所有的节点均手动添加了udp:true，开启后依然不会代理udp流量：

测试使用nc和远程服务器连接，在clash面板中能够看到ssh连接和nc的连接，但是如果使用udp模式，则在clash面板的connection中只能看到ssh的连接

底层上，iptables -t nat -L|grep udp，只有一条劫持53号端口的记录，显然这条是处理dns的。看上去好像就是并没有真实的开启udp的转发？

udp转发的开启是否有什么额外的限制？

**Comment by vernesong** [comment]
发调试日志

**Comment by cjwddtc** [comment]
我暂时改用其他插件了，等后续有机会再来发调试日志吧。
