### ISSUE TITLE
【bug】配置文件管理器里面修改yaml文件，当yaml比较大的时候，会无法修改，直接软路由都进不去了

### ISSUE THREAD

**Issue by icucuio** [vernesong/OpenClash#1116]
我的yaml文件时订阅来的，每次生成的都有1.4M，如果直接修改，保存和应用都会出现假死，软路由没有相应，管理界面再也进不去，只能重启软路由才可以

**Comment by bingfoon** [comment]
CPU性能弱，订阅时排除不常用的节点，减小配置文件体积。

**Comment by BarneyTTGumble** [comment]
> CPU性能弱，订阅时排除不常用的节点，减小配置文件体积。

请问I3205U 性能算弱吗？我订阅的YAML大概450kb，也偶尔出现楼主的情况。

**Comment by icucuio** [comment]
> > CPU性能弱，订阅时排除不常用的节点，减小配置文件体积。
> 
> 请问I3205U 性能算弱吗？我订阅的YAML大概450kb，也偶尔出现楼主的情况。

同意你，我的是i5-7200软路由，估计这个配置没有几个比这个还强的软路由了吧

**Comment by CaptainGod** [comment]
相同问题，HyperV宿主机+istoreOS软路由，更新配置文件就假死。宿主机i3-6100
