### ISSUE TITLE
更新完内核导致resolv.conf重置为localhost

### ISSUE THREAD

**Issue by Eintler** [vernesong/OpenClash#1118]
每次更新完内核或数据库后 /tmp/resolv.conf就会被重置为
search lan
nameserver 127.0.0.1
nameserver ::1

**Comment by vernesong** [comment]
这难道不正常？

**Comment by Eintler** [comment]
> 这难道不正常？

这样导致curl以及opkg update调用超时啊。

**Comment by vernesong** [comment]
插件没有更改这些内容的设定，建议你去lan口指定DNS
