### ISSUE TITLE
[bug] fake-ip(增强）fake-ip(tun) 和fake-ip(tun-混合） 三种模式特坑人了

### ISSUE THREAD

**Issue by icucuio** [vernesong/OpenClash#1119]
之前我反映的DDNS解析域名成功，加端口好访问nas不成功的案例，版主也帮我了，但是一致没有解决。一个群友终于提了一下切换fake-ip 模式试试，果然成功了。我花了差不多一个月的时间来弄，原来就是那么简单。但是也发现一些bug，还是故意的？

**以下都是在不改变任何其他设置的情况，但是单纯的切换模式的结果：
1） 在fake-ip增强模式下，无法访问nas，别的一切功能正常，好像速度最快。延时最低，尤其是F ——Q的时候
2） 切换到fake-ip（tun）模式，网络都无法访问了，这个需要版主解决下，这个issue很严重
3） 切换到fake-ip（tun-混合）的时候，成功远程访问nas，但是上网速度有些影响，明显域名解析慢点，延时增加**

![image](https://user-images.githubusercontent.com/69136587/103170330-60ad9580-487e-11eb-9520-c59275600d24.png)

**Comment by winxpp** [comment]
你可以开fake-ip增强模式但是代理设置里的“漏网之鱼”要设置成直连

我此处设置成走国外 群晖里的ddns（腾讯的ddns) 就是导致把域名解析到代理的IP上导致我无法通过域名访问NAS

**Comment by icucuio** [comment]
> 你可以开fake-ip增强模式但是代理设置里的“漏网之鱼”要设置成直连
> 
> 我此处设置成走国外 群晖里的ddns（腾讯的ddns) 就会导致把域名解析到代理的IP上导致我无法通过域名访问NAS

根本没有用，你说的我都试过，很多解决方法都没有成功

**Comment by jakeslee** [comment]
使用 fake ip 模式时，如果内网需要通过解析到公网（外网） IP 的域名来访问内网设备时，请将域名写到 OpenClash 的 全局设置 > DNS 设置 > Fake-IP 域名黑名单 里（运行模式需要为 Fake-IP，并启用 DNS高级设置）。

此外，需要做以下检查：

1. 域名是否正确解析到公网 IP
2. 在内网 dig 域名是否正确返回公网 IP

**Comment by zfh135072** [comment]
fake-ip（tun-混合）在最新版本上发v0.41.13上是真的上网很慢

**Comment by lbwstco** [comment]
checkip.synology.com
checkipv6.synology.com
checkport.synology.com
ddns.synology.com
account.synology.com

把这几个加到直连里

**Comment by shep2008** [comment]
这个问题都这么久到今天还是没解决呀

**Comment by Idealisten** [comment]
> checkip.synology.com checkipv6.synology.com checkport.synology.com ddns.synology.com account.synology.com
> 
> 把这几个加到直连里

亲测有用

**Comment by wakaka123wakaka** [comment]
我有一个APP，使用fake的增强模式就无法播放，切换成了tun模式立马就可以了。不知道啥原因。

**Comment by Idealisten** [comment]
应该是和UDP相关
wolalala ***@***.***>于2023年8月18日 周五02:22写道：

**Comment by aizaimosaou** [comment]
这个问题有解决吗？
