### ISSUE TITLE
建议添加自定义上游DNS服务器功能

### ISSUE THREAD

**Issue by aaaisan** [vernesong/OpenClash#112]
我的openwrt安装了SmartDNS,指定了Dnsmasq的上游服务器为SmartDNS，在openclash中停用了本地dns劫持后，启用了上游dns服务器，在设置中指定上游dns服务器为127.0.0.1:5335,还是会修改Dnsmasq的上游服务器为clash的

**Comment by vernesong** [comment]
![image](https://user-images.githubusercontent.com/42875168/71891223-1a4cbb80-3181-11ea-9929-ae17c3b7fdd5.png)
![image](https://user-images.githubusercontent.com/42875168/71891251-26d11400-3181-11ea-9e26-8ccc19956570.png)

**Comment by phantastar** [comment]
看这一篇
[OpenClash和SmartDNS搭配设置方法](https://conversun.com/2019/08/19/OpenClash-SmartDns/)
