### ISSUE TITLE
客户端v0.41.13-beta 存在两个问题

### ISSUE THREAD

**Issue by matthuo333** [vernesong/OpenClash#1121]
1. 看启动日志，每隔1分钟左右是需要update配置文件？ 现在每次都提示 “ Update Faild”， 属于正常么？
2. 每次重启oc， 配置策略ui面板的策略都被修改，不能保持上次设置的。

**Comment by vernesong** [comment]
建议检查curl，此日志是在尝试保存节点状态，然后提示保存失败

**Comment by matthuo333** [comment]
> 建议检查curl，此日志是在尝试保存节点状态，然后提示保存失败

curl 什么？ curl google.com 可以正常获得xml

**Comment by matthuo333** [comment]
关于每次重启oc， 策略不保存，在老客户端版本上也存在

**Comment by SwordBahamut** [comment]
我的之前没有 最近三个版本才有的

**Comment by vernesong** [comment]
具体命令在https://github.com/vernesong/OpenClash/blob/7695d88e64821d02a6acf3d794abb1ef6f9b0d17/luci-app-openclash/root/usr/share/openclash/openclash_history_get.sh#L18
你将最后的2>/dev/null去掉单独运行脚本可以看看报什么错误

**Comment by matthuo333** [comment]
将脚本文件的最后一行的2>/dev/null删除后，并运行，出现如下：（客户端版本：0.40.7）

![image](https://user-images.githubusercontent.com/55862904/103326736-ba83aa80-4a8c-11eb-8f03-e0afa3ee958e.png)

**Comment by vernesong** [comment]
ssh运行，看curl报什么错

**Comment by matthuo333** [comment]
![image](https://user-images.githubusercontent.com/55862904/103333519-27a53900-4aa9-11eb-8e19-e60fd774e26b.png)

**Comment by vernesong** [comment]
ssh运行脚本

**Comment by matthuo333** [comment]
之前运行过，在ssh中没报任何错
