### ISSUE TITLE
netch和openclash的问题

### ISSUE THREAD

**Issue by cthcl73** [vernesong/OpenClash#1124]
openclash运行在旁路由，不过打游戏掉线频繁。就在电脑端用netch代理游戏。问题来了，如果电脑通过旁路由这样的话游戏没法登陆。我在openclash策略里把游戏域名设定为直连也不能解决。请问有其他办法解决吗？谢谢

**Comment by vernesong** [comment]
流量发给代理了，建议仅代理命中规则流量

**Comment by cthcl73** [comment]
感谢回答，不过我刚试了一下还是不行！请问还有其他办法吗？

**Comment by cthcl73** [comment]
> 流量发给代理了，建议仅代理命中规则流量
感谢回答，不过我刚试了一下还是不行！请问还有其他办法吗？
