### ISSUE TITLE
求问怎么在默认规则上，增加一条自己的规则呢？

### ISSUE THREAD

**Issue by Wangshangy** [vernesong/OpenClash#1125]
不用第三方规则，机场自带规则也挺好用，想增加一条规则，例如 访问 XXX.COM这个网站的时候，走指定的某些线路。就像看NF的时候，机场会自动切换线路那样。。我在机场自带的配置文件里 怎么改都没有用。  在全局，自定义规则里添加，怎么都没法成功。请问怎么写规则，怎么设置才能成功呢。

**Comment by lifetyper** [comment]
直接写config.yaml文件里：
https://lancellc.gitbook.io/clash/clash-config-file/rules

**Comment by icolourful** [comment]
建议你把你自己写的规则发上来看看。。。。

**Comment by Wangshangy** [comment]
> 建议你把你自己写的规则发上来看看。。。。

-
    name: HBO
    type: select
    proxies:
      - V482U-2X-BGP-US-NBU*
      - V486U-2X-BGP-US-NBU*
      - V487U-2X-BGP-US-NBU*
      - V490U-2X-BGP-US-NBU*

rules:
##Custom Rules##
##
##Custom Rules End##
- DOMAIN-SUFFIX,smtp,DIRECT
- DOMAIN-KEYWORD,aria2,DIRECT


- DOMAIN-SUFFIX,hbomax.com,HBO
- DOMAIN-SUFFIX,hbo.com,HBO


想自动切一下看HBO，这样写的，， 在机场默认的yaml里加的这些，请大哥帮我看看，，

**Comment by JasinYip** [comment]
基本和楼上一样的配置，确实是没生效

**Comment by HuRongchuan** [comment]
注意一下语法规则，我是没看见前面的减号所以规则不生效，艸

**Comment by HuRongchuan** [comment]
井号后面的所有字符都要带上
