### ISSUE TITLE
节点采用解锁服务后，TV端仍检测到代理，怎么破

### ISSUE THREAD

**Issue by dzhl** [vernesong/OpenClash#1130]
前面已经由网友问类似问题，标题是“Netflix怎么总是被检测到代理 #230”，这个问题已经关闭，我没看出结论了，请了解此问题的朋友帮忙解答下，clash采用了解锁后的节点，手机端奈非app正常使用，神盾盒子端虽然能加载剧集，但播放时提示代理

**Comment by aguero119** [comment]
自己的节点问题

**Comment by vernesong** [comment]
我也是神盾，ihie1规则，提示代理一般是节点问题

**Comment by dzhl** [comment]
我的节点本身确实不支持奈非，我使用了DNS解锁，用dnsmasq分流，用在手机端clash或者v2rayNG上，都可以解锁奈非，用在openclash上却提示代理。

**Comment by vernesong** [comment]
链接日志正常吗

**Comment by bingfoon** [comment]
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/AmazonIp.list
试试把这个规则加入奈飞分组

**Comment by linianqing** [comment]
我也是这样，折腾了好久。目前只有ssr plus把盒子的ip添加到访问控制里，然后选择游戏增强模式就不会有问题，但是我又特别需要openclash的节点分流，所以求作者大佬看下访问控制那里能否也添加一个单独游戏模式的功能。

**Comment by vernesong** [comment]
clash的工作原理不一样，他会把域名给VPS去解析DNS，ssrp是在本地解析DNS，你这种情况可能还需要补充奈飞域名到VPS上的解析脚本里方便劫持

**Comment by dzhl** [comment]
> clash的工作原理不一样，他会把域名给VPS去解析DNS，ssrp是在本地解析DNS，你这种情况可能还需要补充奈飞域名到VPS上的解析脚本里方便劫持

我的解锁机是只有IPV6才能解锁奈非，IPV4不能解锁，解锁机上安装v2ray，中转机使用https://github.com/arloor/iptablesUtils脚本进行nat转发解锁机的端口，openclash打开TV端后，显示剧照，但是播放就是提示代理，同样节点，使用ssrp或者passwall，剧照都不显示，仍是未解锁状态

**Comment by linianqing** [comment]
> > clash的工作原理不一样，他会把域名给VPS去解析DNS，ssrp是在本地解析DNS，你这种情况可能还需要补充奈飞域名到VPS上的解析脚本里方便劫持
> 
> 我的解锁机是只有IPV6才能解锁奈非，IPV4不能解锁，解锁机上安装v2ray，中转机使用[https://github.com/arloor/iptablesUtils脚本进行nat转发解锁机的端口，openclash打开TV端后，显示剧照，但是播放就是提示代理，同样节点，使用ssrp或者passwall，剧照都不显示，仍是未解锁状态] 
我ipv4解锁都有问题更别说ipv6了，目前我想看netflix的话只能关掉openclash使用ssrplus。。。

**Comment by xshenmi** [comment]
> 
> 
> https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/AmazonIp.list
> 试试把这个规则加入奈飞分组

你好 ，能说下具体怎么额外给netflix分组添加规则吗？ 感谢。

**Comment by matthuo333** [comment]
我的情况挺奇怪的。 同一份规则，不通节点，首先连接火棒的无线就不同结果。对开始不能连接的节点，改用tun模式后，就可以正常连接火棒无线了。

**Comment by matthuo333** [comment]
另外，通过TUN模式，之前看似不OK的节点，也可以使得火棒无线正常连接。但是Netflix 又出现网络不通情况。

**Comment by matthuo333** [comment]
TUN模式下，导致都不按照规则走？在面板连接中没有看到任何流量

**Comment by matthuo333** [comment]
发现问题了，是自己的VPS的问题，将amazon的一个域名解析到一个奇怪的CDN上了。

**Comment by matthuo333** [comment]
对于检测到代理，和上述应该是两个问题。可是现在怎么都不能复现检测到代理的现象了。。。想解决此问题，却没了环境。。。

**Comment by matthuo333** [comment]
最后复现了。将楼上的规则加入NF组仍然不行，使用全局仍然不行。
其中有个疑问，看到8.8.8.8做为目的地址，通过match 后，往节点送。 会不会节点通过8.8.8.8解析后的，经火棒检验后不对？为什么一直要match 8.8.8.8呢？ 是否需要在配置文件的节点设置udp:true ?
节点本身是完全原生IP的，完全解锁NF。

**Comment by matthuo333** [comment]
> https://trick77.com/netflix-dns-unblocking-without-sni-xbox-360-ps3-samsung-tv/ 因为部分设备看的时候 nflxvideo.net 只会发送ip clash没嗅探导致无法触发dns解锁 可以利用只要开着clash就永久保存ip 域名对应关系的机能先把域名解析一遍就好了 [nf.zip](https://github.com/vernesong/OpenClash/files/7296617/nf.zip) clash 启动后 ssh里面 ash nf.sh nf.txt 就能全部解析一遍了 只要不是乱玩dns是给到clash解析的话 直接输入ip日志也会显示域名 触发给服务器域名达到dns解锁的功能 redir模式有效 fakeip没测试也许不行 ![nf](https://user-images.githubusercontent.com/50364156/136271241-f838cffe-ef7a-4040-97b5-c32f7ad029ad.gif)
> 
> nf.txt就收集了部分sg hk 德国的域名 其他国家需要自行添加

大神，“直接输入ip日志也会显示域名 触发给服务器域名”  这句没太理解，可否解释下？

**Comment by vernesong** [comment]
dev加了个IP补全，可以测试下效果

**Comment by dayuanpan** [comment]
> > dev加了个IP补全，可以测试下效果
> 
> 看了下好像只是规则补全ip? 其实不是ip规则不全问题 一般nf规则的 那些no-resolve的ip规则已经包括了 主要是近期nf封锁太厉害很少节点直接是原生ip换起来麻烦 都是dns解锁方便 原理是服务器把域名劫持解析成一台能看nf的机器ip来sni代理 又因clash核心没嗅探功能(用ssrp的ssr或者xray核心看一般是正常的) 除了苹果TV很大部分安卓盒子 tv盒子 游戏主机的奈菲客户端喜欢把nflxvideo域名整成ip让clash核心也认为是个ip直接发给代理服务器 服务器拿不到域名,解析不了sniproxy服务端的ip导致dns解锁失效了 目前只能提前把域名解析一遍让核心学习了哪个ip对应哪个域名来解决不发域名给代理解析的问题 其实只要clash核心不关 长时间看电脑手机的奈菲也能有差不多的学习效果

哈哈，活捉魅影大佬，前两天已经用了tg群里的txt文件，算是部分解决了，部分未解决可能有些影片播放时对应的IP地址不在文档里，导致不能转成域名，也就是目前无法全覆盖

**Comment by matthuo333** [comment]
有时抓包看到直接目的地址是ip，不是域名。查ip后，貌似是自己节点的区域的不详ip(看不出是nf的，感觉是cdn，不确定)。像这种ip，也是加入进来么？

**Comment by vernesong** [comment]
跑fast这个感觉也可以，用户手动测速一下然后我去内核读域名就行了

**Comment by vernesong** [comment]
肯定是有时效性的，因为客户端实际可能一直没有再次请求DNS的行为，Clash也没法永久缓存

**Comment by vernesong** [comment]
DEV分支编译一下，自己加一下域名到/usr/share/openclash/res/Netflix_Domains.list

**Comment by matthuo333** [comment]
> > > 正常播放的时候手动抓一下，把抓到的域名发出来
> > 
> > 
> > 面板日志打开后，文件是存在哪个路径？另外，如果更新最新的openclash 那个试验性功能打开可以协助记录吧？
> 
> 新版的手动抓取

有个场景就是远程VPN访问openclash，然后执行手动抓取，会失效吧？如果ssh 执行 fast 后，会效果一致么？

**Comment by vernesong** [comment]
流量过内核才能抓

**Comment by matthuo333** [comment]
> 流量过内核才能抓

需要必须从web 配置页触发启动才能抓么？如果先打开这个功能，然后单独启动fast.com， 可以么？ 抓取后，存在哪个路径下呢？

**Comment by vernesong** [comment]
点按钮根据提示操作啊，放在etc/openclash/custom/

**Comment by matthuo333** [comment]
因为是VPN连接，点击按钮后，新打开的fast.com是利用本地的网络，没有走远程的内核。所以通过SSH启动fast脚本，这样能否更新netflix.list？ 如果不行，手工添加行么？

**Comment by vernesong** [comment]
> 因为是VPN连接，点击按钮后，新打开的fast.com是利用本地的网络，没有走远程的内核。所以通过SSH启动fast脚本，这样能否更新netflix.list？ 如果不行，手工添加行么？

流量要走内核才抓的到，我是读内核的数据

**Comment by vernesong** [comment]
> 因为是VPN连接，点击按钮后，新打开的fast.com是利用本地的网络，没有走远程的内核。所以通过SSH启动fast脚本，这样能否更新netflix.list？ 如果不行，手工添加行么？

手动加到etc/openclash/custom/里面的neiflix文件

**Comment by matthuo333** [comment]
嗯，清楚了。同时借此再反馈其它流媒体情况。就是针对D+ 和 HBO Max , 有时会出现提前解析IP，导致按照规则路由到other,  想问下，什么情况下会提前解析，而不是在VPS端来做？

**Comment by vernesong** [comment]
disney和hbo的域名？

**Comment by vernesong** [comment]
服务器如果支持sni也不会有问题

**Comment by matthuo333** [comment]
> disney和hbo的域名？

当时看D+ 时抓到这些，直接在本地解析到IP。域名当时反查，当时没忘了保存。下次遇到，第一时间发出来
104.123.0.0/16
8.240.0.0/16
205.185.0.0/16

**Comment by matthuo333** [comment]
> 服务器如果支持sni也不会有问题

主要是路由到other中，不是特定代理，速度会有影响；如果指定代理，不同组又互有影响。

**Comment by matthuo333** [comment]
突然出现这样得地址：  occ-0-3594-325.1.nflxso.net  
另外，fast后出现具体IP，这个不能直接加到那个custom的文件中吧？

**Comment by dzhl** [comment]
有解决办法了吗

**Comment by dzhl** [comment]
最终什么办法呢，没看懂

**Comment by nameless3721** [comment]
> 最终什么办法呢，没看懂

最新版openclash使用meta内核开启域名探测试试吧

**Comment by yuchanns** [comment]
> [ACL4SSR/ACL4SSR@`master`/Clash/Ruleset/AmazonIp.list (raw)](https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/AmazonIp.list) 试试把这个规则加入奈飞分组

对我有效

**Comment by matthuo333** [comment]
感觉自动切换，会带来这个问题

**Comment by zqcccc** [comment]
clash 连上 v2ray，通过 v2ray 连代理就没有问题了
