### ISSUE TITLE
用上传配置成功开启openclash后,如何添加单节点并保存到上传的配置文件里?

### ISSUE THREAD

**Issue by aguero119** [vernesong/OpenClash#1131]
用上传配置成功开启openclash后,如何添加单节点并保存到上传的配置文件里?

**Comment by vernesong** [comment]
自己写yaml，或者去节点与策略组页面，先读取配置文件，然后添加节点信息，最后应用

**Comment by aguero119** [comment]
感觉有bug，照你的办法弄了之后，订阅如果有过滤节点的话，某些规则集会错乱。

vernesong <notifications@github.com> 于 2020年12月31日周四 14:39写道：

**Comment by hcym** [comment]
一直都是上传配置，要改节点增减广告规则或者变换加密格式也是改好再上传呗，从来没事，倒是内置的自动生成经常出差，有心理阴影了

**Comment by vernesong** [comment]
如果要订阅后保持策略组，请勾选保留配置

**Comment by Atianyi-1990** [comment]
> 如果要订阅后保持策略组，请勾选保留配置

保留策略组的配置，配置文件我修改过分流，上传修改后的配置文件是可以成功启动openclash的，然后我想更新下节点，就在订阅链接里输入机场链接，更新过程中节点，策略组全部替换成功，配置文件也提示写入成功，我就想用更新后的节点运用保存的策略组配置，然后点击启动openclash，但是启动openclash失败，提示DNS无法获取监听端口。要如何解决呢？
