### ISSUE TITLE
一直使用正常，今天突然不能进入luci界面了

### ISSUE THREAD

**Issue by txl263** [vernesong/OpenClash#1134]
/usr/lib/lua/luci/ccache.lua:70: error loading module 'luci.controller.openclash' from file '/usr/lib/lua/luci/controller/openclash.lua':
	/usr/lib/lua/luci/controller/openclash.lua:92: unexpected symbol near 'char(25)'
stack traceback:
	[C]: in function 'loader'
	/usr/lib/lua/luci/ccache.lua:70: in function </usr/lib/lua/luci/ccache.lua:61>
	[C]: in function 'require'
	/usr/lib/lua/luci/dispatcher.lua:575: in function 'createindex'
	/usr/lib/lua/luci/dispatcher.lua:602: in function 'createtree'
	/usr/lib/lua/luci/dispatcher.lua:266: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:127: in function </usr/lib/lua/luci/dispatcher.lua:126>

**Comment by txl263** [comment]
页面显示如上，功能正常

**Comment by lifetyper** [comment]
自己改了什么都不说，只能归咎为灵异事件。

**Comment by txl263** [comment]
> 自己改了什么都不说，只能归咎为灵异事件。

几个月了没有改过任何东西。。。

**Comment by txl263** [comment]
Clash v0.19.0-8-g2750c7e linux mips 2020年 04月 11日 星期六 17:37:56 UTC
也没有自动升级什么的。。

**Comment by lifetyper** [comment]
那有可能路由的硬盘文件损坏，试试重新刷机。

**Comment by txl263** [comment]
> 那有可能路由的硬盘文件损坏，试试重新刷机。

这倒有可能，系统我放在U盘上的 
重新刷机。。。想想就头大   当时在虚拟机里编译的，现在环境都没了

**Comment by ericshunhawk** [comment]
装了argon主题？

**Comment by txl263** [comment]
> 装了argon主题？

忘了，一直没修复，最近没有改动的需求就这么放着。。。。

**Comment by ericshunhawk** [comment]
> > 装了argon主题？
> 
> 忘了，一直没修复，最近没有改动的需求就这么放着。。。。

如果安装了argon主题又启用了openclash argon获取不到bing的贴图 就打不开luci界面

**Comment by jisukuke5** [comment]
> > > 装了argon主题？
> > 
> > 
> > 忘了，一直没修复，最近没有改动的需求就这么放着。。。。
> 
> 如果安装了argon主题又启用了openclash argon获取不到bing的贴图 就打不开luci界面

原来如此，我用WinSCP工具传了个背景照片到/www/luci-static/argon/background路径下，就能用了，谢谢大佬的点拨，原来只是Argon主题的问题

**Comment by muihiuwev** [comment]
> > > > 装了argon主题？
> > > 
> > > 
> > > 忘了，一直没修复，最近没有改动的需求就这么放着。。。。
> > 
> > 
> > 如果安装了argon主题又启用了openclash argon获取不到bing的贴图 就打不开luci界面
> 
> 原来如此，我用WinSCP工具传了个背景照片到/www/luci-static/argon/background路径下，就能用了，谢谢大佬的点拨，原来只是Argon主题的问题

这个有没有办法通过添加规则或设置解决？每次都要 ssh 停掉 openclash 才能进挺烦的，又不想换其他主题。

**Comment by jisukuke5** [comment]
> > > > > 装了argon主题？
> > > > 
> > > > 
> > > > 忘了，一直没修复，最近没有改动的需求就这么放着。。。。
> > > 
> > > 
> > > 如果安装了argon主题又启用了openclash argon获取不到bing的贴图 就打不开luci界面
> > 
> > 
> > 原来如此，我用WinSCP工具传了个背景照片到/www/luci-static/argon/background路径下，就能用了，谢谢大佬的点拨，原来只是Argon主题的问题
> 
> 这个有没有办法通过添加规则或设置解决？每次都要 ssh 停掉 openclash 才能进挺烦的，又不想换其他主题。

Argon主题的登录页面的背景是联网获取的，要设置规则的话，就规则写不代理背景图的来源？我没弄过，只能给这样的思路。我只是直接通过WinSCP工具传了个背景照片到/www/luci-static/argon/background路径下，设了个固定的背景图而已。

**Comment by muihiuwev** [comment]
> > > > > > 装了argon主题？
> > > > > 
> > > > > 
> > > > > 忘了，一直没修复，最近没有改动的需求就这么放着。。。。
> > > > 
> > > > 
> > > > 如果安装了argon主题又启用了openclash argon获取不到bing的贴图 就打不开luci界面
> > > 
> > > 
> > > 原来如此，我用WinSCP工具传了个背景照片到/www/luci-static/argon/background路径下，就能用了，谢谢大佬的点拨，原来只是Argon主题的问题
> > 
> > 
> > 这个有没有办法通过添加规则或设置解决？每次都要 ssh 停掉 openclash 才能进挺烦的，又不想换其他主题。
> 
> Argon主题的登录页面的背景是联网获取的，要设置规则的话，就规则写不代理背景图的来源？我没弄过，只能给这样的思路。我只是直接通过WinSCP工具传了个背景照片到/www/luci-static/argon/background路径下，设了个固定的背景图而已。

我上传之后不生效，是否需要在配置文件或者 luci 界面进行设置？对了，我 openclash 只有在 fake-ip 模式下才会这样，redir-host 模式不会。

**Comment by ericshunhawk** [comment]
> > > > > > > 装了argon主题？
> 
> > > > > > 
> 
> > > > > > 
> 
> > > > > > 忘了，一直没修复，最近没有改动的需求就这么放着。。。。
> 
> > > > > 
> 
> > > > > 
> 
> > > > > 如果安装了argon主题又启用了openclash argon获取不到bing的贴图 就打不开luci界面
> 
> > > > 
> 
> > > > 
> 
> > > > 原来如此，我用WinSCP工具传了个背景照片到/www/luci-static/argon/background路径下，就能用了，谢谢大佬的点拨，原来只是Argon主题的问题
> 
> > > 
> 
> > > 
> 
> > > 这个有没有办法通过添加规则或设置解决？每次都要 ssh 停掉 openclash 才能进挺烦的，又不想换其他主题。
> 
> > 
> 
> > Argon主题的登录页面的背景是联网获取的，要设置规则的话，就规则写不代理背景图的来源？我没弄过，只能给这样的思路。我只是直接通过WinSCP工具传了个背景照片到/www/luci-static/argon/background路径下，设了个固定的背景图而已。
> 
> 
> 
> 我上传之后不生效，是否需要在配置文件或者 luci 界面进行设置？对了，我 openclash 只有在 fake-ip 模式下才会这样，redir-host 模式不会。

把argon的config ipk卸载掉 就行了

**Comment by jisukuke5** [comment]
> > > > > > > 装了argon主题？
> > > > > > 
> > > > > > 
> > > > > > 忘了，一直没修复，最近没有改动的需求就这么放着。。。。
> > > > > 
> > > > > 
> > > > > 如果安装了argon主题又启用了openclash argon获取不到bing的贴图 就打不开luci界面
> > > > 
> > > > 
> > > > 原来如此，我用WinSCP工具传了个背景照片到/www/luci-static/argon/background路径下，就能用了，谢谢大佬的点拨，原来只是Argon主题的问题
> > > 
> > > 
> > > 这个有没有办法通过添加规则或设置解决？每次都要 ssh 停掉 openclash 才能进挺烦的，又不想换其他主题。
> > 
> > 
> > Argon主题的登录页面的背景是联网获取的，要设置规则的话，就规则写不代理背景图的来源？我没弄过，只能给这样的思路。我只是直接通过WinSCP工具传了个背景照片到/www/luci-static/argon/background路径下，设了个固定的背景图而已。
> 
> 我上传之后不生效，是否需要在配置文件或者 luci 界面进行设置？对了，我 openclash 只有在 fake-ip 模式下才会这样，redir-host 模式不会。

/www/luci-static/argon/background路径下有没有README.md？里面应该有提示可放什么文件作为背景图吧？确保上传好后重启一下或者刷新浏览器试试？

**Comment by muihiuwev** [comment]
> > > > > > > > 装了argon主题？
> > > > > > > 
> > > > > > > 
> > > > > > > 忘了，一直没修复，最近没有改动的需求就这么放着。。。。
> > > > > > 
> > > > > > 
> > > > > > 如果安装了argon主题又启用了openclash argon获取不到bing的贴图 就打不开luci界面
> > > > > 
> > > > > 
> > > > > 原来如此，我用WinSCP工具传了个背景照片到/www/luci-static/argon/background路径下，就能用了，谢谢大佬的点拨，原来只是Argon主题的问题
> > > > 
> > > > 
> > > > 这个有没有办法通过添加规则或设置解决？每次都要 ssh 停掉 openclash 才能进挺烦的，又不想换其他主题。
> > > 
> > > 
> > > Argon主题的登录页面的背景是联网获取的，要设置规则的话，就规则写不代理背景图的来源？我没弄过，只能给这样的思路。我只是直接通过WinSCP工具传了个背景照片到/www/luci-static/argon/background路径下，设了个固定的背景图而已。
> > 
> > 
> > 我上传之后不生效，是否需要在配置文件或者 luci 界面进行设置？对了，我 openclash 只有在 fake-ip 模式下才会这样，redir-host 模式不会。
> 
> /www/luci-static/argon/background路径下有没有README.md？里面应该有提示可放什么文件作为背景图吧？确保上传好后重启一下或者刷新浏览器试试？

background 这个文件夹是我自己新建的，原来没有，可能是 argon 版本的问题。

目前我在 openclash > 全局设置 > DNS 设置 > 启用高级设置 > 指定第二 DNS 服务器下方的第一个域名列表输入框中加入 bing.com ，能够正常获取图片了。第二 DNS 服务器的作用应该是跳出 fake-ip 模式，使用第二 DNS 服务器查询真实 DNS 并返回给客户端，与 redir-host 模式的工作方式一致。

**Comment by leonliuly** [comment]
> > > > > > > > 装了argon主题？
> > 
> > 
> > > > > > >
> > 
> > 
> > > > > > >
> > 
> > 
> > > > > > > 忘了，一直没修复，最近没有改动的需求就这么放着。。。。
> > 
> > 
> > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > > 如果安装了argon主题又启用了openclash argon获取不到bing的贴图 就打不开luci界面
> > 
> > 
> > > > >
> > 
> > 
> > > > >
> > 
> > 
> > > > > 原来如此，我用WinSCP工具传了个背景照片到/www/luci-static/argon/background路径下，就能用了，谢谢大佬的点拨，原来只是Argon主题的问题
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 这个有没有办法通过添加规则或设置解决？每次都要 ssh 停掉 openclash 才能进挺烦的，又不想换其他主题。
> > 
> > 
> > > 
> > 
> > 
> > > Argon主题的登录页面的背景是联网获取的，要设置规则的话，就规则写不代理背景图的来源？我没弄过，只能给这样的思路。我只是直接通过WinSCP工具传了个背景照片到/www/luci-static/argon/background路径下，设了个固定的背景图而已。
> > 
> > 
> > 我上传之后不生效，是否需要在配置文件或者 luci 界面进行设置？对了，我 openclash 只有在 fake-ip 模式下才会这样，redir-host 模式不会。
> 
> 把argon的config ipk卸载掉 就行了

怎么执行这个操作呀？
通过WinSCP工具传了个背景照片到/www/luci-static/argon/background路径，上传了背景图片仍然进不去 luci 界面
