### ISSUE TITLE
客户端手动/软件更新都失败

### ISSUE THREAD

**Issue by LionelZe** [vernesong/OpenClash#1138]
软件（客户端版本v0.40.14-beta）内选择客户端更新（v0.41.13-beta）失败，下载通过openwrt上传更新显示以下情况：

Multiple packages (luci-app-openclash and luci-app-openclash) providing same name marked HOLD or PREFER. Using latest. Installing luci-app-openclash (0.41.13-beta) to root... Installing libgmp10 (6.1.2-2) to root...

想问下该怎么处理。。。

**Comment by vernesong** [comment]
先把新依赖装好，卸载旧版本再装新版本

**Comment by LionelZe** [comment]
> 先把新依赖装好，卸载旧版本再装新版本

您好，想问下依赖在哪里下载哈？不好意思，我是小白

**Comment by LionelZe** [comment]
> 先把新依赖装好，卸载旧版本再装新版本

已经更新好了，谢谢
