### ISSUE TITLE
上传的配置文件会跑到proxy_provider外面

### ISSUE THREAD

**Issue by konbar** [vernesong/OpenClash#1141]
OpenWrt R20.12.12 已是内核5.4.85，最新编译的,依赖没问题，openclash最新版0.41.13上传的配置文件会跑到proxy_provider外面，同时proxy_provider里面也有一份，不知为什么？？但不会影响使用。。。只有每次通过SCP工具进行管理

**Comment by hcym** [comment]
不是网页直接上传吗，没什么事

**Comment by konbar** [comment]
> 不是网页直接上传吗，没什么事

找到问题了。，，配置文件的路径有问题path: "./proxy_provider改为path: ".就ok了。。。哈哈。。
