### ISSUE TITLE
使用最新版openclash 后无法在谷歌商店下载app

### ISSUE THREAD

**Issue by hongdou03** [vernesong/OpenClash#1142]
使用后无法在谷歌商店下载app 
 openwrt和安卓端开启后都不能下载谷歌商店的APP

**Comment by YukawaMi** [comment]
大概率节点自身的问题吧。。或者你策略？我一切正常，googleplay能用

**Comment by b911ss** [comment]
我也有这个问题，然后去goolge搜了一下，看他们说是ACL4SSR模板的问题，不知道啥情况，等等看

**Comment by jiatianxa** [comment]
把www.google.cn加入代理名单基本就可以了

**Comment by madman43** [comment]
ACL4SSR 的问题

**Comment by nicholas9698** [comment]
大概率是节点问题，有的香港节点会被识别为大陆，根本不返回内容
googleapis.cn
xn--ngstr-lra8j.com (商店下载地址)
将这两个域名自定义规则，换成日本、新加坡等其他地区的节点

**Comment by buildaworld** [comment]
尝试自定义规则里把googleapis.cn reject 但是它始终按配置文件里google 关键字走代理，好难受

**Comment by Lwenkun** [comment]
说下我的解决方法，在 **规则附加** tab 里面，添加如下两个规则：
![屏幕截图 2023-10-30 120950](https://github.com/vernesong/OpenClash/assets/15084367/b4c1b2a5-306b-49c7-8c9a-a8c5df0043da)
