### ISSUE TITLE
问个小白问题，希望不要被鄙视。

### ISSUE THREAD

**Issue by jinlianr** [vernesong/OpenClash#1147]
openclash里怎么添加自定义规则，我想增加两条自定义规则，命中关键词miele的全走代理 ，命中 关键词 netatmo的全 走直连。
我在全 局设置 - 规则 设置 里添加了两条如下规则：
- DOMAIN-KEYWORD, netatmo,Proxy
- DOMAIN-KEYWORD, miele,Direct
但是我在控制面板里看并没有生效。

**Comment by icolourful** [comment]
```
- DOMAIN-KEYWORD, netatmo,Direct
- DOMAIN-KEYWORD, miele,Proxy
```

Proxy怎么写还是看你规则。
我就直接用🐟 漏网之鱼代替proxy，🎯 全球直连代替Direct

**Comment by jinlianr** [comment]
> ```
> - DOMAIN-KEYWORD, netatmo,Direct
> - DOMAIN-KEYWORD, miele,Proxy
> ```
> 
> Proxy怎么写还是看你规则。
> 我就直接用🐟 漏网之鱼代替proxy，🎯 全球直连代替Direct

原谅我。没看懂。我就是想 实现 我 说的 两个关键词一个 走代理，一个走直连，求教。。。

**Comment by nemo2018** [comment]
这两个地方不是随便写，要完全匹配你的组名字，例如楼上那位提到的样子。
![image](https://user-images.githubusercontent.com/37334053/103870626-ecd57d80-5106-11eb-88f5-6756d86372d9.png)

**Comment by JunTsao** [comment]
> ```
> - DOMAIN-KEYWORD, netatmo,Direct
> - DOMAIN-KEYWORD, miele,Proxy
> ```
> 
> Proxy怎么写还是看你规则。
> 我就直接用🐟 漏网之鱼代替proxy，🎯 全球直连代替Direct

那个emoji表情是不是也要复制进去？我曾尝试过改规则🌍 国外媒体或者🇸🇬 狮城节点，但好像并没有效果就放弃了

**Comment by nemo2018** [comment]
对，那个表情也是名称的一部分，必须一点不差的用上，包括空格。
