### ISSUE TITLE
po2lm报错 无法make

### ISSUE THREAD

**Issue by angelfreedomv** [vernesong/OpenClash#1148]
mac环境编译固件
MacBook-Pro po2lmo % make && sudo make install
cc  -o src/po2lmo src/po2lmo.o src/template_lmo.o
install -m 755 src/po2lmo /usr/bin
install: /usr/bin/po2lmo: Operation not permitted
make: *** [install] Error 71

**Comment by wordscode** [comment]
make && sudo make install
Command 'make' not found, but can be installed with:
sudo apt install make        # version 4.3-4.1build1, or
sudo apt install make-guile  # version 4.3-4.1build1

执行sudo apt install make  后
make && sudo make install
cc    -c -o src/po2lmo.o src/po2lmo.c
make: cc: No such file or directory
make: *** [<builtin>: src/po2lmo.o] Error 127
还是报错？？
