### ISSUE TITLE
小白提问，关于育碧Ubisoft Connect联机问题

### ISSUE THREAD

**Issue by dahuang0210** [vernesong/OpenClash#1151]
在玩Anno 1800，只要开启openclash永远联机报错，或者是进游戏之后卡成ppt。关闭openclash后一切正常。我开放了443、14000、18000等游戏端口，也尝试了让玩游戏的电脑直连，但是依然有这个问题。简直崩溃，没有爬到相关的经验分享文，于是跑来提问。还请各位大佬轻拍，给点儿意见。感谢！

运行模式是fake-ip（混合），openclash订阅是X豚湾的接管配置文件。

**Comment by vernesong** [comment]
snat你要看看是不是通的，udp能不能转发出去，或者redir模式在访问控制里面绕过设备

**Comment by dahuang0210** [comment]
好滴，感谢大佬！我去尝试&学习一下！
