### ISSUE TITLE
openvpn客户端无法通过openclash上google

### ISSUE THREAD

**Issue by jxjxcw** [vernesong/OpenClash#1152]
ikuai+lede，ikuai开openvpn服务器端，客户端分配10.7.7.2；lede装openclash、adguard home。openclash接管dns服务，adguard做上级dns服务器。内网客户端上国内、国外都正常。openvpn客户端能上国内、国外不行，Dashboard 控制面板中连接没有openvpn客户端IP地址。
不知哪错了？

**Comment by vernesong** [comment]
koolshare的问题不好解答，没有专门去优化，且目前在koolshare上插件存在权限不够内核无法正常工作的情况

**Comment by jxjxcw** [comment]
谢谢！

**Comment by jxjxcw** [comment]
好的，谢谢！有时间我换个固件试试
