### ISSUE TITLE
Fake Ip 下 IP绑定域名错误

### ISSUE THREAD

**Issue by LouisYuL** [vernesong/OpenClash#1153]
访问google.com结果证书是 facebook的，盲猜 ip绑定域名出错，或者dns缓存的问题？
![image](https://user-images.githubusercontent.com/77185669/104103535-966e6780-52dd-11eb-8bcd-47e96a87703d.png)

**Comment by vernesong** [comment]
dns污染了应该

**Comment by LouisYuL** [comment]
后续都没有碰到，应该是dns污染了。 谢谢
