### ISSUE TITLE
Fake IP 和 规则匹配的顺序问题

### ISSUE THREAD

**Issue by LouisYuL** [vernesong/OpenClash#1154]
在Fake IP的黑名单中配置了 *.127.0.0.1.xip.io 之后， 日志中看到已经解析到 127.0.0.1了，但后续又命中了 规则中的 DOMAIN-SUFFIX xip.io, 导致请求还是走了代理，导致https证书出错
![image](https://user-images.githubusercontent.com/77185669/104104371-915fe700-52e2-11eb-96cf-b5a2232608c6.png)

**Comment by vernesong** [comment]
黑名单的作用是返回真实IP，但如果规则命中还是按照规则去处理，你在自定义规则里面指定xip.io直连就行了

**Comment by LouisYuL** [comment]
因为规则是第三方订阅然后通过内置的subconvert转换的，我在自定义规则里设置了好像不生效，请问是哪里设置错了吗？

![image](https://user-images.githubusercontent.com/77185669/104122060-b7869500-537d-11eb-8e0c-61ab04e2ee6b.png)

**Comment by LouisYuL** [comment]
> 黑名单的作用是返回真实IP，但如果规则命中还是按照规则去处理，你在自定义规则里面指定xip.io直连就行了

另外，既然已经获取到ip了， 是不是不去匹配域名规则，而是直接匹配ip的规则比较合理？

**Comment by vernesong** [comment]
规则格式写错了，前面还有横线没加

**Comment by LouisYuL** [comment]
> 规则格式写错了，前面还有横线没加

原来是这个原因 😓， 可以了，谢谢！

**Comment by LouisYuL** [comment]
不好意思，还是不行。刚刚是因为启动比较慢所以有一瞬间可以了。 现在日志里是看到 

2021-01-10 20:49:59 level=info msg="[TCP] 192.168.1.177:53853 --> rancher.127.0.0.1.xip.io match DomainSuffix(127.0.0.1.xip.io) using DIRECT"

但是看不到任何[DNS]相关的条目。

![image](https://user-images.githubusercontent.com/77185669/104123319-8dd16c00-5385-11eb-804b-d13551a0005c.png)

![image](https://user-images.githubusercontent.com/77185669/104123335-a0e43c00-5385-11eb-9cbe-bee7b359ffd4.png)

![image](https://user-images.githubusercontent.com/77185669/104123349-b8bbc000-5385-11eb-8804-ca1447a0ce4e.png)

**Comment by LouisYuL** [comment]
图里127.0.0.1.xip.io上面这两个域名， nslookup都能正常返回。 是不是fake ip解析到 dns 是127.0.0.1之后又做了一些特殊处理？ 访问 解析出来的ip会到网关(192.168.1.1), 也就是openwrt的管理界面

**Comment by vernesong** [comment]
![image](https://user-images.githubusercontent.com/42875168/104127744-d1849f80-539e-11eb-9f32-2246a6419810.png)
填这个，其他的不用填了，可以直接绕过clash解析

**Comment by LouisYuL** [comment]
填在上面和填在下面都试过了。一样不行。而且其他几个域名都绕过了， 只有 127.0.0.1.xip.io这个不行
![image](https://user-images.githubusercontent.com/77185669/104128342-0c3c0700-53a2-11eb-8d7d-e5a154f2ad47.png)
![image](https://user-images.githubusercontent.com/77185669/104128346-13fbab80-53a2-11eb-8d44-f82eace47432.png)

**Comment by LouisYuL** [comment]
感觉是对解析到127.0.0.1做了其他处理
![image](https://user-images.githubusercontent.com/77185669/104128501-d8151600-53a2-11eb-834e-9de0c0af218a.png)

![image](https://user-images.githubusercontent.com/77185669/104128516-f11dc700-53a2-11eb-93c8-1d36645bcde0.png)

**Comment by vernesong** [comment]
那就尝试用host吧，redir模式

**Comment by LouisYuL** [comment]
暂时直接在dnsmasq里解析掉了，就是luci不支持配置要ssh进去改有点麻烦
