### ISSUE TITLE
绑定网络接口具体是个什么作用？

### ISSUE THREAD

**Issue by smallst** [vernesong/OpenClash#1155]
自从有这个功能之后……
遇到的一个不确定的问题是，使用openclash一段时间后（通常能有大半个礼拜或者一个礼拜的样子？）网络会突然变得特卡，走不走代理的都这样。这种时候我一般切换一下绑定网络端口（就是停用和绑定拨号上网的口）就能恢复……然后持续一段时间，需要再次切换。
有点懵逼，也不确定具体是什么问题（不太会看是不是回环？）有没有什么办法定位和修复问题呢？

**Comment by vernesong** [comment]
看控制面板里的日志，日志等级调成debug
