### ISSUE TITLE
依赖dnsmasp-full无法安装

### ISSUE THREAD

**Issue by Ahtaler** [vernesong/OpenClash#1156]
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for dnsma
 *      kmod-nf-conntrack-netlink
 * opkg_install_cmd: Cannot install package dnsmasq-full.

dnsmasq-full的前置kmod-nf-conntrack-netlink无法找到
已更新软件源

**Comment by vernesong** [comment]
这种错误还是刷固件解决吧

**Comment by Ahtaler** [comment]
刷了，搞定了，正常使用
关掉了，谢谢
