### ISSUE TITLE
google提示异常流量

### ISSUE THREAD

**Issue by LouisYuL** [vernesong/OpenClash#1157]
原来在电脑上用clashx没出现过这个问题，换用openclash之后时常出现。
请问是url test频率太高了还是单纯的节点出了问题呢？
![image](https://user-images.githubusercontent.com/77185669/104122245-dafe0f80-537e-11eb-8bc9-f446dd655f7c.png)

**Comment by lifetyper** [comment]
你自己节点问题，尤其是机场。
