### ISSUE TITLE
Openclash启用后会隔一段时间掉线，希望咨询原因

### ISSUE THREAD

**Issue by Spanishisaka** [vernesong/OpenClash#1161]
Openclash启用后会隔一段时间掉线，期间网络都无法访问，重启后才能使用
日志显示：Watchdog: Clash Core Problem, Restart.
时间间隔大概是三到五小时左右一次。

路由器型号：红米AC2100
Xiaomi Redmi Router AC2100 (CpuMark : 5028.073410 Scores)
处理器架构：mipsel_24kc
固件版本：hfy166 Ver.D2021.01.04 / OpenWrt R20.12.12 / LuCI Master (git-20.343.54716-6fc079f)
内核版本：5.4.85
内核编译版本：mipsle-hardfloat

【系统日志节选】
Tue Jan 12 03:24:17 2021 daemon.warn odhcpd[1380]: A default route is present but there is no public prefix on lan thus we don't announce a default route!
Tue Jan 12 03:32:31 2021 daemon.warn odhcpd[1380]: A default route is present but there is no public prefix on lan thus we don't announce a default route!
Tue Jan 12 03:38:40 2021 daemon.warn odhcpd[1380]: A default route is present but there is no public prefix on lan thus we don't announce a default route!
Tue Jan 12 03:46:19 2021 daemon.warn odhcpd[1380]: A default route is present but there is no public prefix on lan thus we don't announce a default route!
Tue Jan 12 03:52:29 2021 daemon.warn odhcpd[1380]: A default route is present but there is no public prefix on lan thus we don't announce a default route!
Tue Jan 12 04:00:24 2021 daemon.warn odhcpd[1380]: A default route is present but there is no public prefix on lan thus we don't announce a default route!
Tue Jan 12 04:38:30 2021 user.info mwan3track[10883]: Check (ping) failed for target "114.114.114.114" on interface wan (eth0.1)
Tue Jan 12 04:38:36 2021 user.info mwan3track[10883]: Lost 1 ping(s) on interface wan (eth0.1)
Tue Jan 12 05:28:55 2021 daemon.err nlbwmon[2185]: Netlink receive failure: Out of memory
Tue Jan 12 05:28:55 2021 daemon.err nlbwmon[2185]: Unable to dump conntrack: No buffer space available
Tue Jan 12 08:17:13 2021 daemon.err nlbwmon[2185]: Netlink receive failure: Out of memory
Tue Jan 12 08:17:13 2021 daemon.err nlbwmon[2185]: Unable to dump conntrack: No buffer space available
Tue Jan 12 10:53:03 2021 daemon.err nlbwmon[2185]: Netlink receive failure: Out of memory
Tue Jan 12 10:53:03 2021 daemon.err nlbwmon[2185]: Unable to dump conntrack: No buffer space available
Tue Jan 12 13:27:50 2021 daemon.err nlbwmon[2185]: Netlink receive failure: Out of memory
Tue Jan 12 13:27:50 2021 daemon.err nlbwmon[2185]: Unable to dump conntrack: No buffer space available
Tue Jan 12 16:38:12 2021 daemon.err nlbwmon[2185]: Netlink receive failure: Out of memory
Tue Jan 12 16:38:12 2021 daemon.err nlbwmon[2185]: Unable to dump conntrack: No buffer space available
Tue Jan 12 19:22:37 2021 daemon.err nlbwmon[2185]: Netlink receive failure: Out of memory
Tue Jan 12 19:22:37 2021 daemon.err nlbwmon[2185]: Unable to dump conntrack: No buffer space available
Tue Jan 12 19:46:25 2021 daemon.err uhttpd[1871]: cucurl: (6) Couldncrul: (6) Couldn't resolve h'ostrl:  ('6s) Couldn't resolve host 'source.uto resolve host 'source.unnsurcsplapleas.sh.h.cucom'omn'
Tue Jan 12 19:46:25 2021 daemon.err uhttpd[1871]:
Tue Jan 12 19:46:25 2021 daemon.err uhttpd[1871]: splash.com'
Tue Jan 12 19:48:01 2021 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Tue Jan 12 19:48:01 2021 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Tue Jan 12 19:48:05 2021 daemon.info dnsmasq[25390]: Connected to system UBus
Tue Jan 12 19:48:05 2021 cron.err crond[25456]: crond (busybox 1.31.1) started, log level 5
Tue Jan 12 19:48:34 2021 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Tue Jan 12 19:48:34 2021 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Tue Jan 12 19:48:37 2021 daemon.info dnsmasq[26852]: Connected to system UBus
Tue Jan 12 20:13:20 2021 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Tue Jan 12 20:13:20 2021 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Tue Jan 12 20:13:24 2021 daemon.info dnsmasq[24370]: Connected to system UBus
Tue Jan 12 20:13:24 2021 cron.err crond[24412]: crond (busybox 1.31.1) started, log level 5
Tue Jan 12 20:13:49 2021 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Tue Jan 12 20:13:49 2021 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Tue Jan 12 20:13:52 2021 daemon.info dnsmasq[25655]: Connected to system UBus
Tue Jan 12 20:27:39 2021 daemon.err uhttpd[1871]:   %  % Total    % R Total    % Received % Xfered  Averageceived % Xferd  Average Speed   Tim e % T Spe    oetadl       % Received % Xferd  Average Speed   Time    Time     Time  Current
Tue Jan 12 20:27:39 2021 daemon.err uhttpd[1871]:                                  Dload  Upload   Total   Spent    Left  Speed
Tue Jan 12 20:27:39 2021 daemon.err uhttpd[1871]: 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Time     Time  Current
Tue Jan 12 20:27:39 2021 daemon.err uhttpd[1871]:                          Time    Time     Time  Current
Tue Jan 12 20:27:39 2021 daemon.err uhttpd[1871]:                                  Dload  Upload   Total   Spent    Left  Speed
Tue Jan 12 20:27:39 2021 daemon.err uhttpd[1871]: 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0       Dload  Upload   Total   Spent    Left  Speed
Tue Jan 12 20:27:41 2021 daemon.err uhttpd[1871]: 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100   228    0   228    0     0    189      0 --:--:--  0:00:01 --:--:--   205
Tue Jan 12 20:27:41 2021 daemon.err uhttpd[1871]: 
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100   228    0   228    0     0    183      0 --:--:--  0:00:01 --:--:--   196
Tue Jan 12 20:27:41 2021 daemon.err uhttpd[1871]: 
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100   154    0   154    0     0    120      0 --:--:--  0:00:01 --:--:--   130
Tue Jan 12 20:27:42 2021 daemon.err uhttpd[1871]: 
  0  183k    0  1368    0     0    660      0  0:04:45  0:00:02  0:04:43   660
  0 42912    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
 13  120k   13 16416    0     0   7674      0  0:00:16  0:00:02  0:00:14  7674
100 42912  100 42912    0     0  18962      0  0:00:02  0:00:02 --:--:--  246k
Tue Jan 12 20:27:42 2021 daemon.err uhttpd[1871]: 
100  120k  100  120k    0     0  51988      0  0:00:02  0:00:02 --:--:--  455k
Tue Jan 12 20:27:42 2021 daemon.err uhttpd[1871]: 
100  183k  100  183k    0     0  75788      0  0:00:02  0:00:02 --:--:--  443k

【Openclash日志节选】
2021-01-12 19:47:00 History:【橙SS.yaml】 Restore Successful
2021-01-12 19:46:59 level=info msg="Start initial compatible provider ✈️Telegram"
2021-01-12 19:46:59 level=info msg="Start initial compatible provider 🍎苹果服务"
2021-01-12 19:46:59 level=info msg="Start initial compatible provider 🎬Youtube"
2021-01-12 19:46:59 level=info msg="Start initial compatible provider 🔰国外流量"
2021-01-12 19:46:59 level=info msg="Start initial compatible provider 🚀直接连接"
2021-01-12 19:46:59 level=info msg="Start initial compatible provider ⚓️其他流量"
2021-01-12 19:46:59 level=info msg="Start initial compatible provider 🎬国外媒体"
2021-01-12 19:46:59 level=info msg="Start initial compatible provider 🎬Netflix"
2021-01-12 19:46:57 Watchdog: Clash Core Problem, Restart.
2021-01-12 09:08:16 History:【橙SS.yaml】 Restore Successful
2021-01-12 09:08:15 level=info msg="Start initial compatible provider 🔰国外流量"
2021-01-12 09:08:15 level=info msg="Start initial compatible provider 🚀直接连接"
2021-01-12 09:08:15 level=info msg="Start initial compatible provider 🎬Youtube"
2021-01-12 09:08:15 level=info msg="Start initial compatible provider 🎬国外媒体"
2021-01-12 09:08:15 level=info msg="Start initial compatible provider 🍎苹果服务"
2021-01-12 09:08:15 level=info msg="Start initial compatible provider ⚓️其他流量"
2021-01-12 09:08:15 level=info msg="Start initial compatible provider ✈️Telegram"
2021-01-12 09:08:15 level=info msg="Start initial compatible provider 🎬Netflix"
2021-01-12 09:08:13 Watchdog: Clash Core Problem, Restart.
2021-01-12 03:17:05 Warning: OpenClash Start Successful, Please Note That Network May Abnormal With IPV6's DHCP Server

**Comment by vernesong** [comment]
可能占资源被系统杀掉了。之前有人提过

**Comment by zgc** [comment]
r2s有类似的问题，突然cpu高负载，openclash的进程就没了，dns没有切换回去！！！重启一下openclash就好了。。。smartdns也有类似的情况！！！

**Comment by liofoil** [comment]
我用的软路由，tun内核大概过一天就乎会开始占用超高的cpu，网速没有影响，但是会发热，也是重启一下就好。luci和内核版本都是最新的。目前在用游戏模式没什么问题。
