### ISSUE TITLE
[请教]openclash的clash内核和Dreamacro的clash内核有何差别

### ISSUE THREAD

**Issue by emacsnt** [vernesong/OpenClash#1165]
openclash有自己的[TUN Premium](https://github.com/vernesong/OpenClash/releases/tag/TUN-Premium)版本，而Dreamacro的Premium并不开源， 请教OpenClash的TUN版本和原版的有何渊源？
另外，两者的release日期也不一样，是不是实现不一样？特性也不一样？

**Comment by vernesong** [comment]
没区别，只是在做分发

**Comment by emacsnt** [comment]
谢谢回复
Dreamacro 12月27日版本Premium文件size为[13824000](https://github.com/Dreamacro/clash/releases/download/premium/clash-linux-amd64-2020.12.27.gz)


而vernesong版本明显小很多，最新1月1日版本只有[3865704](https://github.com/vernesong/OpenClash/releases/download/TUN-Premium/clash-linux-amd64-2021.01.01.g0ab75c5.gz)

相同的版本怎么会差那么多？

**Comment by ttimasdf** [comment]
因为使用场景是路由器，所以作者把Clash Core套了个压缩壳，减小flash占用。如果担心程序和官方不一样，也可以从官方release下载下来（或者自己编译）自己套壳。压缩操作甚至可以直接在路由器上完成。

UPX压缩工具地址：https://github.com/upx/upx 。都是开源的

**Comment by ttimasdf** [comment]
tun_game 应该是来自 https://github.com/comzyh/clash/tree/add-water ，我记得在项目wiki还是releases还是哪里看到来着。猛的一翻还找不着了。。 要不作者加到FAQ里吧。。。

**Comment by emacsnt** [comment]
官方Premium不开源，不能自行编译？所以才来咨询Premium版本为何有差异，release版本不同。
