### ISSUE TITLE
*求助*clash pro的配置文件无法加载，

### ISSUE THREAD

**Issue by justincnn** [vernesong/OpenClash#1171]
具体内容如下：
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  nameserver:
    - 119.29.29.29
    - 223.5.5.5
    - 114.114.114.114
  fallback:
    - https://dns.google/dns-query
    - 101.102.103.104
    - 80.80.81.81
proxies:
  - name: "ss1"
    type: ss
    server: xxxxxx
    port: xxxxxxxx
    cipher: xxxxxxxx
    password: "xxxxxxxx"
    # udp: true
    
proxy-groups:
  - name: PROXY
    proxies:
      - ss1
      
    type: select
rule-providers:
  reject:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loya ... @release/reject.txt
    path: ./ruleset/reject.yaml
    interval: 86400
  icloud:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loya ... @release/icloud.txt
    path: ./ruleset/icloud.yaml
    interval: 86400
  apple:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loya ... s@release/apple.txt
    path: ./ruleset/apple.yaml
    interval: 86400
  google:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loya ... @release/google.txt
    path: ./ruleset/google.yaml
    interval: 86400
  proxy:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loya ... s@release/proxy.txt
    path: ./ruleset/proxy.yaml
    interval: 86400
  direct:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loya ... @release/direct.txt
    path: ./ruleset/direct.yaml
    interval: 86400
  gfw:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loya ... les@release/gfw.txt
    path: ./ruleset/gfw.yaml
    interval: 86400
  greatfire:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loya ... lease/greatfire.txt
    path: ./ruleset/greatfire.yaml
    interval: 86400
  tld-not-cn:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loya ... ease/tld-not-cn.txt
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400
  telegramcidr:
    type: http
    behavior: ipcidr
    url: https://cdn.jsdelivr.net/gh/Loya ... se/telegramcidr.txt
    path: ./ruleset/telegramcidr.yaml
    interval: 86400
  cncidr:
    type: http
    behavior: ipcidr
    url: https://cdn.jsdelivr.net/gh/Loya ... @release/cncidr.txt
    path: ./ruleset/cncidr.yaml
    interval: 86400
  lancidr:
    type: http
    behavior: ipcidr
    url: https://cdn.jsdelivr.net/gh/Loya ... release/lancidr.txt
    path: ./ruleset/lancidr.yaml
    interval: 86400
rules:
  - PROCESS-NAME,v2ray,DIRECT
  - PROCESS-NAME,Surge%203,DIRECT
  - PROCESS-NAME,ss-local,DIRECT
  - PROCESS-NAME,privoxy,DIRECT
  - PROCESS-NAME,trojan,DIRECT
  - PROCESS-NAME,trojan-go,DIRECT
  - PROCESS-NAME,naive,DIRECT
  - PROCESS-NAME,Thunder,DIRECT
  - PROCESS-NAME,DownloadService,DIRECT
  - PROCESS-NAME,qBittorrent,DIRECT
  - PROCESS-NAME,Transmission,DIRECT
  - PROCESS-NAME,fdm,DIRECT
  - PROCESS-NAME,aria2c,DIRECT
  - PROCESS-NAME,Folx,DIRECT
  - PROCESS-NAME,NetTransport,DIRECT
  - PROCESS-NAME,uTorrent,DIRECT
  - PROCESS-NAME,WebTorrent,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - RULE-SET,reject,REJECT
  - RULE-SET,tld-not-cn,PROXY
  - RULE-SET,gfw,PROXY
  - RULE-SET,greatfire,PROXY
  - RULE-SET,telegramcidr,PROXY
  - GEOIP,AE,PROXY
  - GEOIP,AU,PROXY
  - GEOIP,BR,PROXY
  - GEOIP,CA,PROXY
  - GEOIP,DE,PROXY
  - GEOIP,DK,PROXY
  - GEOIP,ES,PROXY
  - GEOIP,FI,PROXY
  - GEOIP,FR,PROXY
  - GEOIP,GB,PROXY
  - GEOIP,GR,PROXY
  - GEOIP,HK,PROXY
  - GEOIP,ID,PROXY
  - GEOIP,IL,PROXY
  - GEOIP,IN,PROXY
  - GEOIP,IQ,PROXY
  - GEOIP,IR,PROXY
  - GEOIP,IT,PROXY
  - GEOIP,JP,PROXY
  - GEOIP,KR,PROXY
  - GEOIP,MO,PROXY
  - GEOIP,MY,PROXY
  - GEOIP,NL,PROXY
  - GEOIP,NO,PROXY
  - GEOIP,NZ,PROXY
  - GEOIP,PH,PROXY
  - GEOIP,RU,PROXY
  - GEOIP,SA,PROXY
  - GEOIP,SG,PROXY
  - GEOIP,TH,PROXY
  - GEOIP,TR,PROXY
  - GEOIP,TW,PROXY
  - GEOIP,US,PROXY
  - GEOIP,VN,PROXY
  - MATCH,DIRECT

**Comment by vernesong** [comment]
报什么错

**Comment by justincnn** [comment]
> 报什么错
报错信息如下：

2021-01-23 12:23:13 Error: OpenClash Can Not Start, Try Use Raw Config Restart Again
time="2021-01-23T12:23:29+08:00" level=fatal msg="Parse config error: initial rule provider tld-not-cn error: yaml: unmarshal errors:\n  line 1: cannot unmarshal !!str `Invalid...` into provider.RuleSchema"
time="2021-01-23T12:23:28+08:00" level=info msg="Start initial rule provider tld-not-cn"
time="2021-01-23T12:23:28+08:00" level=info msg="Start initial compatible provider PROXY"
WARNING: libcap needs an update (cap=40 should have a name).
WARNING: libcap needs an update (cap=40 should have a name).
2021-01-23 12:23:13 Error: OpenClash Can Not Start, Try Use Backup Rules Start Again
time="2021-01-23T12:23:23+08:00" level=fatal msg="Parse config error: initial rule provider reject error: yaml: unmarshal errors:\n  line 1: cannot unmarshal !!str `Invalid...` into provider.RuleSchema"
time="2021-01-23T12:23:22+08:00" level=info msg="Start initial rule provider reject"
time="2021-01-23T12:23:22+08:00" level=info msg="Start initial compatible provider PROXY"
WARNING: libcap needs an update (cap=40 should have a name).
WARNING: libcap needs an update (cap=40 should have a name).

**Comment by vernesong** [comment]
规则集有问题，可能是没下载下来或者格式错误

**Comment by justincnn** [comment]
> 规则集有问题，可能是没下载下来或者格式错误

我用在mac的clashx pro一切都是正常的，没有任何问题，openclash不兼容clashx pro的配置？

**Comment by vernesong** [comment]
第一次使用会下载文件，自己检查规则集链接下来的文件是否正常
