### ISSUE TITLE
不能升级到最新版本为毛？

### ISSUE THREAD

**Issue by coolzhi** [vernesong/OpenClash#1175]
Upgrading luci-app-openclash on root from 0.41.05-beta to 0.41.14-beta...
Collected errors:
 * pkg_run_script: package "luci-app-openclash" preinst script returned status 1.
 * preinst_configure: Aborting installation of luci-app-openclash.
 * opkg_install_cmd: Cannot install package luci-app-openclash.

固件是Esir 的12.1高大全

**Comment by vernesong** [comment]
卸载重装
