### ISSUE TITLE
求教一些基本问题

### ISSUE THREAD

**Issue by crotoc** [vernesong/OpenClash#1177]
我的网络环境的基本情况是这样的：
网络是ATT，ATT光猫内网IP地址192.168.1.254，DHCP给所有连接它的设备，由于这台机器穿透能力一般，所以我在这台ATT光猫的接了一台netgear的路由，网线从光猫的LAN口到netgear的WAN口。netgear的内网是192.168.215.1，网关设置成192.168.1.254，然后家里的所有的设备通过netgear介入。

我想实现的目标是自动解锁国内视频网站和音乐网站的区域限制。为此，我弄了台腾讯的服务器，在国内的广州，上面已经建好了一个vess的服务器。

现在我碰到的一个问题是，有些app发送的请求直接是解析好的ip地址本身，而不是http的地址，这样在规则里面好像匹配不了。之前我是自己手动的通过ipset来弄一个集合，然后加一两条iptables的规则进行redirect，我想openclash应该自己能做到这一点，请问是如何实现呢？

我的配置文件如下：
---
redir-port: 7892
port: 7890
socks-port: 7891
mode: Rule
log-level: debug
external-controller: 0.0.0.0:9090
secret: 123456
allow-lan: true
bind-address: 0.0.0.0
hosts: 
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 127.0.0.1:7874
  fake-ip-filter: 
  nameserver:
  - 114.114.114.114
  fallback:
  - tls://8.8.8.8:853
  fallback-filter:
    geoip: true
    ipcidr:
    - 240.0.0.0/4

proxies:
- name: guangzhou
  type: vmess
  server: xxxx
  port: xxxx
  uuid: xxxx
  alterId: 64
  cipher: auto
  udp: true
  skip-cert-verify: true
  tls: false
  network: ws
  ws-path: "/"
  ws-headers:
    Host: xxxx

proxy-groups:
- name: Proxy
  type: select
  proxies:
  - mine
  - DIRECT
- name: Others
  type: select
  proxies:
  - DIRECT
  - REJECT
- name: AdBlock
  type: select
  proxies:
  - REJECT
  - DIRECT
- name: mine
  type: select
  proxies:
  - guangzhou

rules:
- DOMAIN,ip.cn,Proxy
- DOMAIN,myip.ipip.net,Proxy
- MATCH,DIRECT

求解答，非常感谢！

**Comment by wwxghh** [comment]
你可以找一些回国规则来配合OpenClash使用，也可以自己写规则，直接请求IP匹配不到规则可以用GEOIP解决，例如：
rules:
- DOMAIN-SUFFIX,cn,Proxy
- GEOIP,CN,Proxy
- MATCH,DIRECT

**Comment by vernesong** [comment]
确认下面设备的网关和DNS是192.168.215.1，不要开那些DNS加速，gfw列表之类的插件

**Comment by crotoc** [comment]
> 你可以找一些回国规则来配合OpenClash使用，也可以自己写规则，直接请求IP匹配不到规则可以用GEOIP解决，例如：
> rules:
> 
> * DOMAIN-SUFFIX,cn,Proxy
> * GEOIP,CN,Proxy
> * MATCH,DIRECT

谢谢你的建议！这是个很好的思路，就是实际情况是我的代理速度被限速，ping还巨高，不能给所有的国内网站都用。所以只能弄些视频网站。我找了好久的视频网站的设置，结果腾讯还好弄，iqiyi总是抽风，一会可以播，一会又说区域限制不能播，抓包抓了半天，完全看不出来是那个地址负责解锁，郁闷。腾讯简单多了，一下子就成功了，唉。

**Comment by crotoc** [comment]
> 确认下面设备的网关和DNS是192.168.215.1，不要开那些DNS加速，gfw列表之类的

可能是app自己会储存解好的ip。我在手机上直接使用clash同样的规则也是有时能解封有时不能解封。看了好几天抓的包，完全不得要领。不知道有没有大神对于读包比较在行，能帮忙看看到底要加哪些规则才能不抽风。现在加了两条：
- DOMAIN-SUFFIX,qy.net,Proxy
- DOMAIN-SUFFIX,iqiyi.com,Proxy

刚打开app能看，放到中间有时候会说播放错误，有时候会突然出现区域限制，完全不知道为啥。
大家帮忙出出建议，看看怎么能够找到正确的解锁思路。谢谢啦，需要的话我可以私下提供抓的包。

**Comment by wwxghh** [comment]
https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/ChinaMedia.list@crotoc

**Comment by crotoc** [comment]
> https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/ChinaMedia.list      @crotoc 

感谢，请问下这个user-agant openclash支持吗？我之前写了一条，好像启动不起来。

**Comment by wwxghh** [comment]
> > https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/ChinaMedia.list      @crotoc
> 
> 感谢，请问下这个user-agant openclash支持吗？我之前写了一条，好像启动不起来。

什么意思😂

**Comment by crotoc** [comment]
> > > https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/ChinaMedia.list      @crotoc
> > 
> > 感谢，请问下这个user-agant openclash支持吗？我之前写了一条，好像启动不起来。
> 
> 
> 什么意思😂，这里有https://acl4ssr-sub.github.io

就是这个网址里面的规则是这样的：

# Iqiyi 爱奇艺
USER-AGENT,QYPlayer*
USER-AGENT,iQIYI*
DOMAIN,intel-cache.m.iqiyi.com
DOMAIN,intel-cache.video.iqiyi.com

那个USER-AGENT的我之前尝试加了下，当时启动openclash会报错。所以不知道支不支持这样的规则。

**Comment by wwxghh** [comment]
> > > > https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/ChinaMedia.list      @crotoc
> > > 
> > > 
> > > 感谢，请问下这个user-agant openclash支持吗？我之前写了一条，好像启动不起来。
> > 
> > 
> > 什么意思😂，这里有https://acl4ssr-sub.github.io
> 
> 就是这个网址里面的规则是这样的：
> 
> # Iqiyi 爱奇艺
> USER-AGENT,QYPlayer*
> USER-AGENT,iQIYI*
> DOMAIN,intel-cache.m.iqiyi.com
> DOMAIN,intel-cache.video.iqiyi.com
> 
> 那个USER-AGENT的我之前尝试加了下，当时启动openclash会报错。所以不知道支不支持这样的规则。

No No No 那个不能加。
Clash规则example
rules:
  - DOMAIN-SUFFIX,google.com,auto
  - DOMAIN-KEYWORD,google,auto
  - DOMAIN,google.com,auto
  - DOMAIN-SUFFIX,ad.com,REJECT
  - SRC-IP-CIDR,192.168.1.201/32,DIRECT
  # optional param "no-resolve" for IP rules (GEOIP, IP-CIDR, IP-CIDR6)
  - IP-CIDR,127.0.0.0/8,DIRECT
  - GEOIP,CN,DIRECT
  - DST-PORT,80,DIRECT
  - SRC-PORT,7777,DIRECT
  - RULE-SET,apple,REJECT # Premium only
  - MATCH,auto

**Comment by crotoc** [comment]
> > > > > https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/ChinaMedia.list      @crotoc
> > > > 
> > > > 
> > > > 感谢，请问下这个user-agant openclash支持吗？我之前写了一条，好像启动不起来。
> > > 
> > > 
> > > 什么意思😂，这里有https://acl4ssr-sub.github.io
> > 
> > 就是这个网址里面的规则是这样的：
> > 
> > # Iqiyi 爱奇艺
> > USER-AGENT,QYPlayer*
> > USER-AGENT,iQIYI*
> > DOMAIN,intel-cache.m.iqiyi.com
> > DOMAIN,intel-cache.video.iqiyi.com
> > 
> > 那个USER-AGENT的我之前尝试加了下，当时启动openclash会报错。所以不知道支不支持这样的规则。
> 
> No No No 那个不能加。
> Clash规则Example
> rules:
>   - DOMAIN-SUFFIX,google.com,auto
>   - DOMAIN-KEYWORD,google,auto
>   - DOMAIN,google.com,auto
>   - DOMAIN-SUFFIX,ad.com,REJECT
>   - SRC-IP-CIDR,192.168.1.201/32,DIRECT
>   ＃optional param "no-resolve" for IP rules (GEOIP, IP-CIDR, IP-CIDR6)
>   - IP-CIDR,127.0.0.0/8,DIRECT
>   - GEOIP,CN,DIRECT
>   - DST-PORT,80,DIRECT
>   - SRC-PORT,7777,DIRECT
>   - RULE-SET,apple,REJECT # Premium only
>   - MATCH,auto
> 参见https://github.com/Dreamacro/clash/wiki/configuration

好的，谢谢解释，那我来试一试。一会来回复

**Comment by crotoc** [comment]
经过尝试一会，发现上面链接里面iqy的是无效的，看起来更像是iqy国际版的规则。里面有些包含inter的域名，从我抓的包里从来不会出现。经过多次尝试，我好像找到了一些规律：
1. 找到了一些用于刚开app时解锁的链接地址
2. 视频看到中间的时候会出现链接无法播放的提示，也会出现这一集能播，下一集出现区域限制的情况。我仔细看了下clash的包，发现app运行一段时间之后，app就不会使用domain进行访问，全部变成了ip地址访问，所以我借鉴上面那个链接中的cidr地址规则，添加了一些地址，就可以接着看了。
3. 比较郁闷的是这些地址会过段时间变一次，我也不知道规律，所以只能将就用用。
4. qy的电视盒客户端是完全另外一套domain，需要重新弄
5. 我使用的路由器如果打开openclash，速率从300到400m降低到60m，比较影响其他访问的性能，特别是云电脑的ping比较高，导致shadow这样的云游戏电脑没法使用，不知道这是否正常。

我回头整理一下，把我抓到的规则放上来。谢谢！
