### ISSUE TITLE
规则更改

### ISSUE THREAD

**Issue by xiaochong113** [vernesong/OpenClash#1178]
请问下我在规则文件里
最后FINAL的规则是
- MATCH,Proxy
然后openclash托管后就变成了
- "DST-PORT,80,Proxy"
- "DST-PORT,443,Proxy"
- "DST-PORT,22,Proxy"
- MATCH,DIRECT
最后的规则变成了直连

**Comment by manbading** [comment]
你是不是选了仅允许常用端口流量？

**Comment by xiaochong113** [comment]
> 你是不是选了仅允许常用端口流量？

我把仅命中代理规则取消了，然后就正常了。
