### ISSUE TITLE
Feature Request: 屏蔽外部第三方链接

### ISSUE THREAD

**Issue by ttimasdf** [vernesong/OpenClash#1180]
OpenClash在状态页面中，会向多个IP查询网站和国内网站发送HTTP请求。在提供便利之余，会将用户的外部IP、User Agent、内部IP或内网域名（通过Referer）全部泄露给这些网站。项目首页的 contributor icon 通过 githubusercontent.com 中转，姑且可以认为（[Ref](https://docs.github.com/en/github/authenticating-to-github/about-anonymized-image-urls)）这些资源引用是安全的。

希望本项目能够给用户提供一个选择，屏蔽外部链接，在有限的空间内减少隐私泄露风险。

对于其他和我有相同顾虑的用户，可以暂且使用以下 ADBlock 规则（uBlock Origin 同样适用）。除此之外，路由器管理若使用HTTPS访问，使用Yacd还需要在浏览器中对当前域名授予“不安全的内容”权限。

```
# 将 your.domain 替换为路由器IP或内网域名
# 将 10.0.0.1 替换为路由器IP。

# 屏蔽路由器所在域名下的所有请求
||*^$domain=router.intranet.your.domain
# 白名单本域名下的请求，即，屏蔽第三方
@@||intranet.your.domain^$domain=router.intranet.your.domain
# 白名单路由器IP的9090端口的XHR请求，这样Clash Dashboard也能用了。
@@||10.0.0.1:9090^$xhr,domain=router.intranet.your.domain
```

**Comment by vernesong** [comment]
只有访问qqwry.api.skk.moe是no-referrer-when-downgrade其他都是no-referrer
