### ISSUE TITLE
用FAKE-IP模式...打LOL 连不了语音...

### ISSUE THREAD

**Issue by LarsGor** [vernesong/OpenClash#1185]
换Redir-Host（兼容）模式就可以

**Comment by vernesong** [comment]
要开udp，不行就用tun

**Comment by LarsGor** [comment]
> 要开udp，不行就用tun

换了TUN同时开了UDP就可以了
还有个问题，我朋友那里设置FAKE-IP模式，连本地网都上不了，换回换Redir-Host（兼容）模式就可以，不知什么原因，他的软路由是D2550,我和他用相同的系统

**Comment by vernesong** [comment]
发日志

**Comment by Rakau** [comment]
我玩天刀也是这样，打开游戏提示连不上服务器，然后fake-ip模式发现Destination IP只要是域名都是空的

**Comment by LarsGor** [comment]
> 我玩天刀也是这样，打开游戏提示连不上服务器，然后fake-ip模式发现Destination IP只要是域名都是空的

有没试过用FAKE-IP(TUN)模式?

**Comment by Rakau** [comment]
没有试过

LarsGor <notifications@github.com> 于 2021年2月1日周一 00:33写道：
