### ISSUE TITLE
最近几个版本始终无法安装，有点抓狂了……

### ISSUE THREAD

**Issue by gungnirayu** [vernesong/OpenClash#1186]
之前是升级升不上来，后来重新编译了包含所有依赖的固件，全新安装还是不行，输出如下：
root@OpenWrt:/tmp# opkg install /tmp/luci-app-openclash_0.41.14-beta_all.ipk -V
opkg_conf_parse_file: Loading conf file /etc/opkg.conf.
opkg_conf_parse_file: Loading conf file /etc/opkg/customfeeds.conf.
opkg_conf_parse_file: Loading conf file /etc/opkg/distfeeds.conf.
pkg_hash_load_feeds:
pkg_hash_load_feeds:
pkg_hash_load_feeds:
pkg_hash_load_feeds:
pkg_hash_load_status_files:
pkg_info_preinstall_check: Updating file owner list.
Installing luci-app-openclash (0.41.14-beta) to root...
pkg_hash_fetch_best_installation_candidate: 2 matching pkgs for apkg=iptables:
pkg_hash_fetch_best_installation_candidate: iptables 1.8.4 x86_64
pkg_hash_fetch_best_installation_candidate: iptables 1.8.6 x86_64
pkg_hash_fetch_best_installation_candidate: 2 matching pkgs for apkg=dnsmasq-full:
pkg_hash_fetch_best_installation_candidate: dnsmasq-full 2.81 x86_64
pkg_hash_fetch_best_installation_candidate: dnsmasq-full 2.83 x86_64
pkg_hash_fetch_best_installation_candidate: 2 matching pkgs for apkg=coreutils:
pkg_hash_fetch_best_installation_candidate: coreutils 8.32 x86_64
pkg_hash_fetch_best_installation_candidate: coreutils 8.32 x86_64
pkg_hash_fetch_best_installation_candidate: 2 matching pkgs for apkg=coreutils-nohup:
pkg_hash_fetch_best_installation_candidate: coreutils-nohup 8.32 x86_64
pkg_hash_fetch_best_installation_candidate: coreutils-nohup 8.32 x86_64
pkg_hash_fetch_best_installation_candidate: 2 matching pkgs for apkg=bash:
pkg_hash_fetch_best_installation_candidate: bash 5.0 x86_64
pkg_hash_fetch_best_installation_candidate: bash 5.1 x86_64
pkg_hash_fetch_best_installation_candidate: 2 matching pkgs for apkg=curl:
pkg_hash_fetch_best_installation_candidate: curl 7.71.0 x86_64
pkg_hash_fetch_best_installation_candidate: curl 7.74.0 x86_64
pkg_hash_fetch_best_installation_candidate: 2 matching pkgs for apkg=ipset:
pkg_hash_fetch_best_installation_candidate: ipset 7.4 x86_64
pkg_hash_fetch_best_installation_candidate: ipset 7.6 x86_64
pkg_hash_fetch_best_installation_candidate: 2 matching pkgs for apkg=ip-full:
pkg_hash_fetch_best_installation_candidate: ip-full 5.7.0 x86_64
pkg_hash_fetch_best_installation_candidate: ip-full 5.10.0 x86_64
pkg_hash_fetch_best_installation_candidate: 2 matching pkgs for apkg=iptables-mod-tproxy:
pkg_hash_fetch_best_installation_candidate: iptables-mod-tproxy 1.8.4 x86_64
pkg_hash_fetch_best_installation_candidate: iptables-mod-tproxy 1.8.6 x86_64
pkg_hash_fetch_best_installation_candidate: 2 matching pkgs for apkg=iptables-mod-extra:
pkg_hash_fetch_best_installation_candidate: iptables-mod-extra 1.8.4 x86_64
pkg_hash_fetch_best_installation_candidate: iptables-mod-extra 1.8.6 x86_64
pkg_hash_fetch_best_installation_candidate: 2 matching pkgs for apkg=libcap:
pkg_hash_fetch_best_installation_candidate: libcap 2.36 x86_64
pkg_hash_fetch_best_installation_candidate: libcap 2.43 x86_64
pkg_hash_fetch_best_installation_candidate: 2 matching pkgs for apkg=ruby:
pkg_hash_fetch_best_installation_candidate: ruby 2.7.1 x86_64
pkg_hash_fetch_best_installation_candidate: ruby 2.7.2 x86_64
pkg_hash_fetch_best_installation_candidate: 2 matching pkgs for apkg=ruby-yaml:
pkg_hash_fetch_best_installation_candidate: ruby-yaml 2.7.1 x86_64
pkg_hash_fetch_best_installation_candidate: ruby-yaml 2.7.2 x86_64
pkg_run_script: Running script /tmp/opkg-IdElkF/luci-app-openclash-LGLkbO/preinst.
opkg_configure_packages: Configuring unpacked packages.
opkg_configure_packages: Reordering packages before configuring them...
write_status_files_if_changed: Writing status file.
pkg_write_changed_filelists: Saving changed filelists.
Collected errors:
 * pkg_run_script: package "luci-app-openclash" preinst script returned status 1.
 * preinst_configure: Aborting installation of luci-app-openclash.
 * opkg_install_cmd: Cannot install package luci-app-openclash.

然后强制升级所有依赖，再次安装报错依然如下……

root@OpenWrt:/tmp# opkg install /tmp/luci-app-openclash_0.41.14-beta_all.ipk --force-overwrite -V
opkg_conf_parse_file: Loading conf file /etc/opkg.conf.
opkg_conf_parse_file: Loading conf file /etc/opkg/customfeeds.conf.
opkg_conf_parse_file: Loading conf file /etc/opkg/distfeeds.conf.
pkg_hash_load_feeds:
pkg_hash_load_feeds:
pkg_hash_load_feeds:
pkg_hash_load_feeds:
pkg_hash_load_status_files:
pkg_info_preinstall_check: Updating file owner list.
Installing luci-app-openclash (0.41.14-beta) to root...
pkg_run_script: Running script /tmp/opkg-OmmBJc/luci-app-openclash-FGjDdD/preinst.
opkg_configure_packages: Configuring unpacked packages.
opkg_configure_packages: Reordering packages before configuring them...
write_status_files_if_changed: Writing status file.
pkg_write_changed_filelists: Saving changed filelists.
Collected errors:
 * pkg_run_script: package "luci-app-openclash" preinst script returned status 1.
 * preinst_configure: Aborting installation of luci-app-openclash.
 * opkg_install_cmd: Cannot install package luci-app-openclash.

实在是没辙了，哪位救救我！

**Comment by wwxghh** [comment]
可以尝试编译固件的时候把OpenClash一块编译进去。😁

**Comment by lifetyper** [comment]
你为啥不直接把openclash编译进去固件？

**Comment by LarsGor** [comment]
为啥不直接装个带OPENCLASH的OPENWRT....

**Comment by gungnirayu** [comment]
好吧……看来只能另寻出路了……

**Comment by yzc509** [comment]
我安装上了  但飞不出YOUTUBE 显示无网络 连接

**Comment by yzc509** [comment]
主机名 | OpenWrt
-- | --
主机型号 | Intel(R) Atom(TM) CPU D2550 @ 1.86GHz : 2 Core 4 Thread
CPU 信息 | 1861.843 MHz +48.0°C (crit = +100.0°C)
固件版本 | OpenWrt R21.1.18 / LuCI Master (git-20.343.54716-6fc079f)
内核版本 | 5.4.91

**Comment by yzc509** [comment]
iptables-mod-extra这个包安装不上

**Comment by harrysummer** [comment]
https://github.com/vernesong/OpenClash/issues/1137#issuecomment-778554158
