### ISSUE TITLE
自定义规则无法加载使用

### ISSUE THREAD

**Issue by Sanly** [vernesong/OpenClash#1187]
使用最新的0.41.14版本，运行模式为Fake-IP（tun-混合）模式。希望增加源IP直连模式，上传了规则文件Local Lan.yaml：
```
payload:
  - SRC-IP-CIDR,10.10.10.3/32
  - SRC-IP-CIDR,10.10.10.11/32
  - SRC-IP-CIDR,10.10.10.12/32
 ```
应用配置后，日志提示：level=fatal msg="Parse config error: initial rule provider Local Lan error: invalid CIDR address: SRC-IP-CIDR,10.10.10.3/32"，最终自定义配置加载失败。以上规则我在“v0.40.7-beta”版本使用过，没有问题，不知为何在新版本下就出现问题了。

**Comment by vernesong** [comment]
![image](https://user-images.githubusercontent.com/42875168/105839941-25cd8780-600d-11eb-965d-1be132d8a61a.png)

**Comment by Sanly** [comment]
是需要在IP段上加上单引号，还是说不需要添加“SRC-IP-CIDR”前缀？没看明白示例。

**Comment by Sanly** [comment]
知道问题在哪儿了，是规则类型选错了，应该选“classical”，而不是“ipcidr”。
