### ISSUE TITLE
该在luci界面修改配置还是上传yaml文件

### ISSUE THREAD

**Issue by Totuz** [vernesong/OpenClash#119]
首先谢谢你们的开发和分享。

第一次用clash，在openclash的配置上搞晕了。看过wiki和google，并没有解答我的疑惑。

使用openclash时，luci界面选项和yaml配置文件的优先级是怎样的关系？

上传了配置文件，切换配置重启后似乎没有按yaml配置文件生效（比如几个端口仍然是luci界面中的配置），如果luci优先于yaml配置文件，那么主界面为什么又会提示必须上传配置文件才能启动？

可以排除配置文件错误，debug日志输出没有异常。

望有朋友可以解惑，感谢！

**Comment by adamw92** [comment]
端口的部分，openclash的配置文件示例中已经明确的标注了，那部分内容会被openclash接管。
配置文件中的基础设置部分，原始配置文件怎么写都会被openclash按照luci中的设置进行接管的

**Comment by Totuz** [comment]
> 端口的部分，openclash的配置文件示例中已经明确的标注了，那部分内容会被openclash接管。
> 配置文件中的基础设置部分，原始配置文件怎么写都会被openclash按照luci中的设置进行接管的

感谢！
原来是这样，我一直把“此项将被接管”理解为配置文件会覆盖luci界面的设置，我糊涂了。
