### ISSUE TITLE
偶尔出现 主程序运行中 守护进程未启动的情况

### ISSUE THREAD

**Issue by LouisYuL** [vernesong/OpenClash#1190]
此时需要代理访问的网站都无法访问.
在YACD中看到仍有活动的链接, 但Host都是IP,没有域名.

![image](https://user-images.githubusercontent.com/77185669/106134700-dff5f800-61a1-11eb-9355-f0945d5b1042.png)

![image](https://user-images.githubusercontent.com/77185669/106134396-71189f00-61a1-11eb-8b28-fcf6aa1b01af.png)

最后几条日志
![image](https://user-images.githubusercontent.com/77185669/106134468-8988b980-61a1-11eb-959c-1f15c69b4717.png)

**Comment by ArriettyQAQ** [comment]
同遇到过
