### ISSUE TITLE
什么时候支持Xray?

### ISSUE THREAD

**Issue by icucuio** [vernesong/OpenClash#1195]
如题

**Comment by OleStore** [comment]
> 如题

你的去clash发帖

**Comment by leafsay** [comment]
[https://github.com/Dreamacro/clash/issues/1185#issuecomment-767305941](url)

**Comment by leafsay** [comment]
这个用的是clash内核，xray也是内核，这两个是同级的东西
你说的大概是要clash内核支持xtls，可以去内核作者那里提
