### ISSUE TITLE
有时候他自己更新订阅配置文件更新不了直接就翻不了，要手动关闭，再启动才正常

### ISSUE THREAD

**Issue by LarsGor** [vernesong/OpenClash#1196]
今天出门，回来翻不了，查了一下日志，更新失败，然后就这样定着，，要自己手动再启动，希望新版能加入检测，翻不了就重新更新，或者重新启动OpenClash

**Comment by vernesong** [comment]
更新失败不会重启插件，你说的具体什么情况

**Comment by LouisYuL** [comment]
> 更新失败不会重启插件，你说的具体什么情况

感觉和我说的这个是一个情况 #1190

**Comment by tsx3000** [comment]
我在ssh运行curl，看看是否缺少什么依赖，我这是缺少libwolfssl，安装就可以了
