### ISSUE TITLE
Openclash下载谷歌网盘里的文件时，一直提示网络错误

### ISSUE THREAD

**Issue by Faramitas** [vernesong/OpenClash#1197]
如题，我换成passwall或者SSRPlus，就正常了（大陆白名单模式）。
另外，我试过redir host和fake ip模式，都出现了网络错误。上传文件时也会出错，小文件（例如1M不到的文件）可以上传成功，但是大文件不行。

**Comment by vernesong** [comment]
内核的ssr有断流问题，等修复
