### ISSUE TITLE
DDNS成功解析公网ip,用手机外网尝试所有模式都无法访问家里个别映射了端口的设备

### ISSUE THREAD

**Issue by qiao112** [vernesong/OpenClash#1198]
![image](https://user-images.githubusercontent.com/45731546/106838210-cfc8a600-66d6-11eb-8b8f-f15401f62aa8.png)
图中圈起来的可以访问其他都不行

**Comment by qiao112** [comment]
iss里面所有方法都尝试了

**Comment by qiao112** [comment]
对了我是旁路由上开启的openclash主路由是高恪

**Comment by pillanangel** [comment]
如果主路由支持，请尝试更改默认服务端口或者设置端口转发，可能是ISP那边对常用低位端口做了限制。

**Comment by qiao112** [comment]
> 如果主路由支持，请尝试更改默认服务端口或者设置端口转发，可能是ISP那边对常用低位端口做了限制。

关闭openclash就能用

**Comment by vernesong** [comment]
nat了，在旁路有上也要设置下转发，主路由转发到旁路由，旁路有转发到客户端

**Comment by nevinee** [comment]
> nat了，在旁路有上也要设置下转发，主路由转发到旁路由，旁路有转发到客户端

大佬，这种情形旁路由上是从lan转发到lan吧？

**Comment by sjkhsl** [comment]
> nat了，在旁路有上也要设置下转发，主路由转发到旁路由，旁路有转发到客户端

我op就是主路由，开启openclash后没办法访问内网的除op的其他地址和端口～
