### ISSUE TITLE
两种模式下，只要走TUN的，游戏机NAT就会变中等或者严格，请解决下

### ISSUE THREAD

**Issue by Neilson8** [vernesong/OpenClash#1199]
我的是XBOX ONEX，裸联NAT开放，用了这个插件加速只要用到TUN内核，游戏机NAT就变严格，匹配不到人，求解决

**Comment by vernesong** [comment]
https://github.com/vernesong/OpenClash/issues/1076

**Comment by Neilson8** [comment]
> 我的是XBOX ONEX，裸联NAT开放，用了这个插件加速只要用到TUN内核，游戏机NAT就变严格，匹配不到人，求解决

我也是，解决了吗
