### ISSUE TITLE
配置文件【config】下载失败，请检查网络或稍后再试！

### ISSUE THREAD

**Issue by huoshenlaile** [vernesong/OpenClash#1201]
同issue #785 我也遇到了同样的问题，但是尝试了 # 785 的解决方案后无果，手动上传配置文件是正常的，但是不能订阅

**Comment by vernesong** [comment]
检查curl

**Comment by huoshenlaile** [comment]
> 检查curl

已经安装了, opkg install curl 输出是up to date了

**Comment by harveyhuangw** [comment]
我也是下载失败，curl 订阅地址出现这个问题，找了一圈没有找到解决办法  
curl: (35) ssl_handshake returned - mbedTLS: (-0x7780) SSL - A fatal alert message was received from our peer

**Comment by tsx3000** [comment]
我在ssh运行curl，看看是否缺少什么依赖，我这是缺少libwolfssl，安装就可以了

**Comment by YeC1213** [comment]
我的是都装了，还是不行。最后把订阅网站的最低允许tls版本从tls1.3改成tls1.2就好了。

**Comment by tayxxs** [comment]
同样的问题，还是curl的问题，是要映射下目录么
![image](https://user-images.githubusercontent.com/8893551/122784843-66dc7600-d2e5-11eb-81ed-c08952adec83.png)

**Comment by 911SnIpEr** [comment]
Keep curl & libcurl the same version.
