### ISSUE TITLE
错误: 无法获取DNS部分的监听端口设置, OpenClash 使用原始配置文件启动失败

### ISSUE THREAD

**Issue by LionelZe** [vernesong/OpenClash#1203]
> 2021-02-06 01:38:27 Error: Get DNS 'enhanced-mode' Option Error, OpenClash Can Not Start With Raw Config File
> 2021-02-06 01:38:27 Error: Get DNS 'listen' Option Error, OpenClash Can Not Start With Raw Config File
> 2021-02-06 01:38:27 Error: OpenClash Can Not Start, Try Use Raw Config Restart Again
> time="2021-02-06T01:39:11+08:00" level=fatal msg="Parse config error: proxy group[1]: '1 加入用户群: https://t.me/airkoryo' not found"
> 2021-02-06 01:38:27 Error: OpenClash Can Not Start, Try Use Backup Rules Start Again
> time="2021-02-06T01:39:04+08:00" level=fatal msg="Parse config error: proxy group[1]: '1 加入用户群: https://t.me/airkoryo' not found"
> 

想问下问题到底出现在哪里？

**Comment by vernesong** [comment]
Parse config error: proxy group[1]: '1 加入用户群: https://t.me/airkoryo' not found
配置文件有问题
