### ISSUE TITLE
为啥我的ruby无法启动，重新安装ruby还是报这个错

### ISSUE THREAD

**Issue by syniii** [vernesong/OpenClash#1206]
![image](https://user-images.githubusercontent.com/622440/107118512-820d9280-68bc-11eb-8b1f-1b746345e3cc.png)
为啥我的ruby无法启动，重新安装ruby还是报这个错。是不是要指定ruby的版本才可以？

**Comment by flyingzl** [comment]
```bash
opkg update
opkg --force-reinstall ruby
```
试试看

**Comment by vernesong** [comment]
系统指令符缺失，建议还是重新编译固件

**Comment by syniii** [comment]
要走重新编译这么复杂的么？  有没有人把这个so文件发给我，我覆盖看看。。。

**Comment by xiazeyu** [comment]
opkg install libruby2.7
