### ISSUE TITLE
[Issue]Dashboard Proxy Group及节点信息不刷新

### ISSUE THREAD

**Issue by JNN-W** [vernesong/OpenClash#1207]
最早在0.3x的版本上配置过一个yaml，这次更新了一个配置文件，但dashboard上的信息还是显示旧的配置，怎么刷新、修改dashboard端口、密码再刷新都没有用。把之前的yaml都删了也没有作用，但YACD是能正常显示新配置的。

后面卸载重新安装了最新版的0.41.14-beta，还是不行，又卸载后，手动把/etc下openclash所有文件删掉，把/usr/share下所有openclash文件删掉，还用find命令把所有能搜到的包含“openclash”的文件和目录都删了，重新安装openclash，重新从零开始配置，还是一样的问题。

不清楚哪里还有残留，实在没办法了求助一下。不过暂时不用dashboard只用yacd也是可以正常使用的。

**Comment by vernesong** [comment]
浏览器ctrl+f5重新登录dashboard

**Comment by JNN-W** [comment]
谢谢，ctrl+f5不起作用，即使改了密码也没有要重新登录的情况，直接就进到页面了。最后通过find -name "*clash*"|xargs rm -rfv彻底删掉所有clash相关的文件，再重新安装后就可以了。

**Comment by JNN-W** [comment]
不太常用github, 上面的星号被转义了。
