### ISSUE TITLE
请问有讨论组吗

### ISSUE THREAD

**Issue by rilyuuj** [vernesong/OpenClash#1211]
您好，请问是否有考虑组建tg等群组得想法，方便用户以及热心PR得开发者进行沟通？
水群也可以，主要是有这样讨论环境， 当然，一切以不影响到个人隐私为前提。
谢谢。

**Comment by treisrunut** [comment]
所以你是没有真正用过 OpenClash 吧？
或者你没看软件界面的字。自己关了吧。这样的低级 issue 。进了群估计也是方便伸手的多。而不是沟通交流。

**Comment by vernesong** [comment]
插件状态页面有图标链接
