### ISSUE TITLE
不使用tracker作爲DOMAIN-KEYWORD來過濾BT/P2P

### ISSUE THREAD

**Issue by Mr-Sheep** [vernesong/OpenClash#1213]
https://github.com/vernesong/OpenClash/blob/e6a064f07665a879f8f08a3499ce72f7c6c3145f/luci-app-openclash/root/usr/share/openclash/yml_rules_change.sh#L68

OpenClash在開啓`Rule Match Proxy Mode`和`Common Ports Proxy Mode`後會添加以下內容至`config.json`

```
- DOMAIN-KEYWORD,tracker,DIRECT
- DOMAIN-KEYWORD,announce.php?passkey=,DIRECT
- DOMAIN-KEYWORD,torrent,DIRECT
- DOMAIN-KEYWORD,peer_id=,DIRECT
- DOMAIN-KEYWORD,info_hash,DIRECT
```
由於Clash執行規則的順序是從上到下，添加第一條以後會放行部分廣告域名/數據跟蹤域名，如
```
tracker.sns.iqiyi.com
adeventtracker.spotify.com
epowernetworktrackerimages.s3.amazonaws.com
eviltracker.net
tracker.baidu.com
tracker.yhd.com
tracker.tgbus.com
```

對於BT的識別，是否可以使用`process-name`來判斷？

**Comment by vernesong** [comment]
路由上process-name只针对本机，放在最后拦截强度不够，没有太好的办法
