### ISSUE TITLE
fake-ip模式测速speedtest速度只有300m左右，speed已经设置不走代理。

### ISSUE THREAD

**Issue by zclpop** [vernesong/OpenClash#1215]
openclash上用fake-ip模式测速speedtest速度只有300m左右是什么问题啊 切换成redir模式速度就没问题 speedtest设置不走代理了，分别在两台设备上都这样测速，问题依旧

**Comment by lifetyper** [comment]
不走代理和不走clash是两个概念，可能是你路由器的性能不足。

**Comment by zclpop** [comment]
肯定不是性能不足，一台j4125，一台i7 9700t，这要还性能不足，我就无话可说了。

**Comment by vernesong** [comment]
单线程了吗，这个不好判断问题

**Comment by ShaoXinSen** [comment]
1G带宽, speedtest应该走的是直连(代理应该没这速度 手动滑稽)...

![Snipaste_2021-02-13_22-51-10](https://user-images.githubusercontent.com/13616801/107852873-06788c00-6e4e-11eb-8885-6e16710b59ca.jpg)
![Snipaste_2021-02-13_22-52-47](https://user-images.githubusercontent.com/13616801/107852906-36279400-6e4e-11eb-84e8-63998a4cb35c.jpg)

**Comment by MBRjun** [comment]
尝试路由器使用 SpeedTest CLI 测速

**Comment by wuabuhuan** [comment]
同样是楼主的问题
