### ISSUE TITLE
第三方规则不能正常使用

### ISSUE THREAD

**Issue by yaleyip** [vernesong/OpenClash#1217]
开启第三方规则lhie1，不少不被墙的外网无法访问。

问题从昨天晚上开始。
v0.41.14-beta

**Comment by OleStore** [comment]
> 开启第三方规则lhie1，不少不被墙的外网无法访问。
> 
> 问题从昨天晚上开始。
> v0.41.14-beta

https://github.com/vernesong/OpenClash/issues/1224
