### ISSUE TITLE
特定ip绕过openclash

### ISSUE THREAD

**Issue by roninriddle** [vernesong/OpenClash#1219]
已知两种办法。
1.通过ipables增加两条命令。无效。
iptables -t nat -I openclash -s 192.168.3.230/32 -j RETURN
iptables -t mangle -A openclash -s 192.168.3.230/32 -j RETURN
2.启用自定义规则，并增加如下规则。无效。
‘- SRC-IP-CIDR,192.168.3.230/32,DIRECT’

求解。。。

问题原因是小米猫眼无法连接，规则里没有关于小米的任何设置。于是想通过固定猫眼的ip，然后绕过openclash或者写一条规则，但是都没有实现。

**Comment by vernesong** [comment]
https://github.com/vernesong/OpenClash/issues/580

**Comment by roninriddle** [comment]
> #580
加一条自定义策略: - SRC-IP-CIDR,110.43.68.200/32,DIRECT

这个ip是什么？小米？src不是源ip么？

**Comment by roninriddle** [comment]
最终没找到问题。应该是依赖的原因。更换固件后解决。‘- SRC-IP-CIDR,192.168.3.230/32,DIRECT’
