### ISSUE TITLE
如何在这个项目下编译OpenClash

### ISSUE THREAD

**Issue by Doraemon2020** [vernesong/OpenClash#122]
博客：https://totoro.site/index.php/archives/70/
项目：https://github.com/skytotwo/NanoPi-R1S-Build-By-Actions
我按照文章步骤操作后依然没有把OC编译进包里，应该在哪一个位置增加内容呢？

**Comment by vernesong** [comment]
https://github.com/skytotwo/NanoPi-R1S-Build-By-Actions/blob/3eb1ce7bde360ab5dd9be9418d0bf1311a266803/r1s-h5-config#L3692
https://github.com/skytotwo/NanoPi-R1S-Build-By-Actions/blob/3eb1ce7bde360ab5dd9be9418d0bf1311a266803/OpenWrt-Build-Cli-H5.yml#L71
