### ISSUE TITLE
配置文件不存在，您已设置订阅信息，准备开始下载...

### ISSUE THREAD

**Issue by tiefengsun** [vernesong/OpenClash#1221]
填写订阅地址后启动openclash卡在“配置文件不存在，您已设置订阅信息，准备开始下载...”

**Comment by vernesong** [comment]
在配置文件订阅页面保存应用更新配置文件

**Comment by tgfcer** [comment]
大佬，0.42.02也是一直卡在这里不动，保存应用更新配置文件了。这几个链接导入到其他Clash客户端，都能用，有规则，请教是处在哪里的问题，设备是R2S。

**Comment by vernesong** [comment]
> 大佬，0.42.02也是一直卡在这里不动，保存应用更新配置文件了。这几个链接导入到其他Clash客户端，都能用，有规则，请教是处在哪里的问题，设备是R2S。

订阅那个页面应用配置会更新和启动，实在不行先上传吧，这个问题已经修复，还未发新版本
