### ISSUE TITLE
启动界面提示正常，但9090打不开，History:Update Faild

### ISSUE THREAD

**Issue by zlopen** [vernesong/OpenClash#1222]
小米r3g，基于openwrt的master branch，ssh上去看到一个clash进程是启动的，但实际上网dns都解析不了，想上9090看看，但界面也打不开，127.0.0.1:9090端口是打开的，curl根能看到hello，不知道该怎么解决
2021-02-18 21:13:25 History:【xxx.yaml】 Update Faild
2021-02-18 21:11:08 OpenClash Start Successful
2021-02-18 21:12:30 History:【xxx.yaml】 Restore Successful
2021-02-18 21:12:08 level=info msg="RESTful API listening at: 127.0.0.1:9090"
2021-02-18 21:12:08 level=info msg="HTTP proxy listening at: :7890"
2021-02-18 21:12:08 level=info msg="SOCKS proxy listening at: :7891"
2021-02-18 21:12:08 level=info msg="Start initial rule provider Japonx"
2021-02-18 21:12:07 level=info msg="Start initial rule provider Reject"
2021-02-18 21:12:07 level=info msg="Start initial rule provider Apple TV"
......
2021-02-18 21:12:06 level=info msg="Start initial compatible provider Domestic"
2021-02-18 21:12:06 level=info msg="Start initial compatible provider Others"
2021-02-18 21:12:06 level=info msg="Start initial compatible provider Proxies"
2021-02-18 21:12:06 level=info msg="Start initial compatible provider Auto - UrlTest"
2021-02-18 21:10:32 GEOIP Database Update Successful
2021-02-18 21:10:32 Chnroute Lists Update Successful
2021-02-18 21:10:32 OpenClash 【Tun】 Core Update Successful
2021-02-18 15:43:29 Warning: OpenClash Now Disabled, Need Start From Luci Page, Exit...

**Comment by vernesong** [comment]
```
curl -m 5 --retry 2 -w %{http_code}"\n" -H "Authorization: Bearer 123456" -H "Content-Type:application/json" -X GET http://192.168.1.1:9090/proxies
```

**Comment by zcluo** [comment]
我也是一样的问题X86
2021-02-19 22:21:55 History:【config.yaml】 Update Faild
2021-02-19 22:20:55 History:【config.yaml】 Update Faild
2021-02-19 22:19:55 History:【config.yaml】 Update Faild
2021-02-19 22:18:54 History:【config.yaml】 Update Faild

**Comment by zcluo** [comment]
curl: (7) Failed to connect to 10.0.0.1 port 9090: Connection refused
000

**Comment by zlopen** [comment]
# curl -m 5 --retry 2 -w %{http_code}"\n" -H "Authorization: Bearer 123456" -H "Content-Type:application/json" -X GET http://192.168.1.1
:9090/proxies
curl: (7) Failed to connect to 192.168.1.1 port 9090: Connection refused
如果我尝试127.0.0.1反而能有返回
# curl -m 5 --retry 2 -w %{http_code}"\n" -H "Authorization: Bearer 123456" -H "Content-Type:application/json" -X GET http://127.0.0.1:9
090/proxies
{"proxies":{"AdBlock":{"all":["REJECT","DIRECT","Proxies"],"history":[],"name":"AdBlock","now":"REJECT","type":"Selector"},"Apple":{"all":["DIRECT","Proxies"],......
看了一下端口监听，被挂在了127.0.0.1上
# netstat -anp | grep 9090
tcp        0      0 127.0.0.1:9090          0.0.0.0:*               LISTEN      9157/clash
界面里点Config Manage，看左右侧的external-controller都是127.0.0.1:9090，手工把左侧的改成192.168.1.1，commit & apply后，命令行下curl正常了，在浏览器里http://192.168.1.1:9090/proxies能看到json输出，但无论国内网站还是网外还是没法上网。
我暂时又切回了大概一个月前的正常版本，稍对比了一下，同样浏览器http://192.168.1.1:9090/proxies输出的是message	"Unauthorized"，Config Manage里能看到左侧是127.0.0.1，右侧貌似自动换成了192.168.1.1

**Comment by vernesong** [comment]
正常是external-controller: 0.0.0.0:9090，开了仅允许内网会改成external-controller: 192.168.1.1:9090

**Comment by zlopen** [comment]
允许内网倒是没Update failed了，但外网还是打不开，打开http://192.168.1.1:9090/ui时还是404 page not found

**Comment by msylgj** [comment]
类似问题, 最新2102的openwrt编译出来之后启动可以成功,但是配置里没有写入dnslisten的配置, 类似还有9090的配置和external-ui地址等依靠luci写入的配置都没有, 初步怀疑可能是ruby的版本从1907的2.6.6升级为2.7.2导致的,但暂未回滚测试.
目前仅测试手动补全配置后可以正常使用. 
@vernesong

**Comment by lifetyper** [comment]
昨天更新了最新的snapshot的官方openwrt版本也出现了一样的问题，openclash这段时间都没有任何版本变动和新的commit，估计时哪个package更新的问题。

**Comment by lifetyper** [comment]
> 
> 
> 类似问题, 最新2102的openwrt编译出来之后启动可以成功,但是配置里没有写入dnslisten的配置, 类似还有9090的配置和external-ui地址等依靠luci写入的配置都没有, 初步怀疑可能是ruby的版本从1907的2.6.6升级为2.7.2导致的,但暂未回滚测试.
> 目前仅测试手动补全配置后可以正常使用.
> @vernesong

应该不是ruby版本的问题，我之前正常使用的master branch的openwrt里的ruby已经是2.7.2版本（ruby 2.7.2p137 (2020-10-01 revision 5445e04352）了，可能是其他package更新导致的。

**Comment by vernesong** [comment]
ruby写不进去会有报错的，除非ruby本身有问题

**Comment by lifetyper** [comment]
发现这些段都漏掉了：
`fake-ip-filter:
XXXXXX所有fake ip段内容XXXX
`

`
mixed-port: 7893
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
secret: *******
bind-address: "*"
external-ui: "/usr/share/openclash/dashboard"
ipv6: false
tun:
  enable: true
  stack: system
  dns-hijack:
  - tcp://8.8.8.8:53
  - tcp://8.8.4.4:53
 `

**Comment by lifetyper** [comment]
贴个调试日志：
```
OpenClash 调试日志

生成时间: 2021-02-20 20:41:19
插件版本: v0.41.14-beta
隐私提示: 上传此日志前请注意检查、屏蔽公网IP、节点、密码等相关敏感信息

```

#===================== 系统信息 =====================#

主机型号: HARDKERNEL ODROID-H2
固件版本: OpenWrt SNAPSHOT r15851-31a06f8fcc
LuCI版本: git-21.032.71059-a567b3d
内核版本: 5.4.99
处理器架构: x86_64

#此项在使用Tun模式时应为ACCEPT
防火墙转发: ACCEPT

#此项有值时建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: 

#此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 127.0.0.1#7874

#===================== 依赖检查 =====================#

dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
jsonfilter: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
iptables-mod-tproxy: 已安装
kmod-ipt-tproxy: 已安装
iptables-mod-extra: 已安装
kmod-ipt-extra: 已安装
libcap: 已安装
libcap-bin: 已安装
ruby: 已安装
ruby-yaml: 已安装
ruby-psych: 已安装
ruby-pstore: 已安装
ruby-dbm: 已安装
kmod-tun(TUN模式): 已安装
luci-compat(Luci-19.07): 已安装

#===================== 内核检查 =====================#

运行状态: 运行中
进程pid: 15165
运行权限: 15165: cap_dac_override,cap_net_bind_service,cap_net_admin,cap_net_raw,cap_sys_resource=eip
运行用户: nobody
已选择的架构: linux-amd64

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 2021.01.01.g0ab75c5
Tun内核文件: 存在
Tun内核运行权限: 正常

Game内核版本: v0.17.0-232-ge389e33
Game内核文件: 存在
Game内核运行权限: 正常

Dev内核版本: v1.3.5-4-g6fedd7e
Dev内核文件: 存在
Dev内核运行权限: 正常

#===================== 插件设置 =====================#

当前配置文件: /etc/openclash/config/config.yaml
启动配置文件: /etc/openclash/config.yaml
运行模式: fake-ip-mix
默认代理模式: rule
UDP流量转发(tproxy): 停用
DNS劫持: 启用
自定义DNS: 停用
IPV6-DNS解析: 停用
禁用Dnsmasq缓存: 启用
自定义规则: 停用
仅允许内网: 停用
仅代理命中规则流量: 停用
仅允许常用端口流量: 停用
绕过中国大陆IP: 停用

#启动异常时建议关闭此项后重试
混合节点: 停用
保留配置: 停用

#启动异常时建议关闭此项后重试
第三方规则: 停用

#===================== 配置文件 =====================#

port: 7890
socks-port: 7891
redir-port: 7892
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:7874
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
  - 119.29.29.29
  - 223.5.5.5
  - 1.2.4.8
proxy-groups:
- name: FAST
  type: url-test
  proxies:
  - CN-HK1
  - CN-TW1
  - CN-US1
  - CN-HK2
  - PRO
  url: https://cp.cloudflare.com/generate_204
  interval: 1800
- name: HK
  type: url-test
  proxies:
  - CN-HK1
  - CN-HK2
  url: https://cp.cloudflare.com/generate_204
  interval: 86400
- name: TW
  type: url-test
  proxies:
  - CN-TW1
  url: https://cp.cloudflare.com/generate_204
  interval: 86400
- name: US
  type: url-test
  proxies:
  - CN-US1
  url: https://cp.cloudflare.com/generate_204
  interval: 86400
rules:
- RULE-SET,Hulu(By lhie1),US
- RULE-SET,PBS(By lhie1),US
- RULE-SET,Disney Plus,US
- RULE-SET,HBO(By lhie1),US
- RULE-SET,Line TV,TW
- RULE-SET,KKTV(By lhie1),TW
- RULE-SET,Bahamut(By lhie1),TW
- RULE-SET,广告规则(By lhie1),REJECT
- RULE-SET,隐私规则合集,REJECT
- RULE-SET,反劫持规则,REJECT
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- IP-CIDR,172.16.0.0/12,DIRECT
- IP-CIDR,192.168.0.0/16,DIRECT
- IP-CIDR,10.0.0.0/8,DIRECT
- IP-CIDR,100.64.0.0/10,DIRECT
- IP-CIDR,198.18.0.1/16,REJECT,no-resolve
- GEOIP,CN,DIRECT
- MATCH,FAST
rule-providers:
  反劫持规则:
    type: http
    behavior: classical
    path: "/etc/openclash/rule_provider/Hijacking.yaml"
    url: https://cdn.jsdelivr.net/gh/DivineEngine/Profiles@master/Clash/RuleSet/Guard/Hijacking.yaml
    interval: 86400
  隐私规则合集:
    type: http
    behavior: classical
    path: "/etc/openclash/rule_provider/Privacy.yaml"
    url: https://cdn.jsdelivr.net/gh/DivineEngine/Profiles@master/Clash/RuleSet/Guard/Privacy.yaml
    interval: 86400
  广告规则(By lhie1):
    type: http
    behavior: classical
    path: "/etc/openclash/rule_provider/Reject.yaml"
    url: https://cdn.jsdelivr.net/gh/lhie1/Rules@master/Clash/Provider/Reject.yaml
    interval: 86400
  Bahamut(By lhie1):
    type: http
    behavior: classical
    path: "/etc/openclash/rule_provider/Bahamut-lhie1.yaml"
    url: https://cdn.jsdelivr.net/gh/lhie1/Rules@master/Clash/Provider/Media/Bahamut.yaml
    interval: 86400
  KKTV(By lhie1):
    type: http
    behavior: classical
    path: "/etc/openclash/rule_provider/KKTV-lhie1.yaml"
    url: https://cdn.jsdelivr.net/gh/lhie1/Rules@master/Clash/Provider/Media/KKTV.yaml
    interval: 86400
  Line TV:
    type: http
    behavior: classical
    path: "/etc/openclash/rule_provider/Line TV.yaml"
    url: https://cdn.jsdelivr.net/gh/lhie1/Rules@master/Clash/Provider/Media/Line%20TV.yaml
    interval: 86400
  HBO(By lhie1):
    type: http
    behavior: classical
    path: "/etc/openclash/rule_provider/HBO-lhie1.yaml"
    url: https://cdn.jsdelivr.net/gh/lhie1/Rules@master/Clash/Provider/Media/HBO.yaml
    interval: 86400
  Disney Plus:
    type: http
    behavior: classical
    path: "/etc/openclash/rule_provider/Disney Plus.yaml"
    url: https://cdn.jsdelivr.net/gh/lhie1/Rules@master/Clash/Provider/Media/Disney%20Plus.yaml
    interval: 86400
  PBS(By lhie1):
    type: http
    behavior: classical
    path: "/etc/openclash/rule_provider/PBS-lhie1.yaml"
    url: https://cdn.jsdelivr.net/gh/lhie1/Rules@master/Clash/Provider/Media/PBS.yaml
    interval: 86400
  Hulu(By lhie1):
    type: http
    behavior: classical
    path: "/etc/openclash/rule_provider/Hulu-lhie1.yaml"
    url: https://cdn.jsdelivr.net/gh/lhie1/Rules@master/Clash/Provider/Media/Hulu.yaml
    interval: 86400
interface-name: eth0

#===================== 防火墙设置 =====================#

#NAT chain

# Generated by iptables-save v1.8.7 on Sat Feb 20 20:41:20 2021
*nat
:PREROUTING ACCEPT [3:156]
:INPUT ACCEPT [3:156]
:OUTPUT ACCEPT [21:1378]
:POSTROUTING ACCEPT [11:693]
:MINIUPNPD - [0:0]
:MINIUPNPD-POSTROUTING - [0:0]
:openclash - [0:0]
:openclash_output - [0:0]
:postrouting_lan_rule - [0:0]
:postrouting_rule - [0:0]
:postrouting_wan_rule - [0:0]
:prerouting_lan_rule - [0:0]
:prerouting_rule - [0:0]
:prerouting_wan_rule - [0:0]
:zone_lan_postrouting - [0:0]
:zone_lan_prerouting - [0:0]
:zone_wan_postrouting - [0:0]
:zone_wan_prerouting - [0:0]
-A PREROUTING -d 8.8.4.4/32 -p tcp -m tcp --dport 53 -j ACCEPT
-A PREROUTING -d 8.8.8.8/32 -p tcp -m tcp --dport 53 -j ACCEPT
-A PREROUTING -m comment --comment "!fw3: Custom prerouting rule chain" -j prerouting_rule
-A PREROUTING -i br-lan -m comment --comment "!fw3" -j zone_lan_prerouting
-A PREROUTING -i eth0 -m comment --comment "!fw3" -j zone_wan_prerouting
-A PREROUTING -p udp -m udp --dport 53 -m comment --comment dns_hijack -j REDIRECT --to-ports 53
-A PREROUTING -p tcp -m tcp --dport 53 -m comment --comment dns_hijack -j REDIRECT --to-ports 53
-A PREROUTING -p tcp -j openclash
-A OUTPUT -j openclash_output
-A POSTROUTING -s 198.18.0.0/24 -j MASQUERADE
-A POSTROUTING -o ztzlgmpcam -j MASQUERADE
-A POSTROUTING -m comment --comment "!fw3: Custom postrouting rule chain" -j postrouting_rule
-A POSTROUTING -o br-lan -m comment --comment "!fw3" -j zone_lan_postrouting
-A POSTROUTING -o eth0 -m comment --comment "!fw3" -j zone_wan_postrouting
-A openclash -m set --match-set localnetwork dst -j RETURN
-A openclash -p tcp -j REDIRECT --to-ports 7892
-A openclash_output -m set --match-set localnetwork dst -j RETURN
-A openclash_output -d 198.18.0.0/16 -p tcp -m owner ! --uid-owner 65534 -j REDIRECT --to-ports 7892
-A openclash_output -p tcp -m owner ! --uid-owner 65534 -j REDIRECT --to-ports 7892
-A zone_lan_postrouting -m comment --comment "!fw3: Custom lan postrouting rule chain" -j postrouting_lan_rule
-A zone_lan_prerouting -m comment --comment "!fw3: Custom lan prerouting rule chain" -j prerouting_lan_rule
-A zone_wan_postrouting -m comment --comment "!fw3: Custom wan postrouting rule chain" -j postrouting_wan_rule
-A zone_wan_postrouting -j MINIUPNPD-POSTROUTING
-A zone_wan_postrouting -m comment --comment "!fw3" -j MASQUERADE
-A zone_wan_prerouting -m comment --comment "!fw3: Custom wan prerouting rule chain" -j prerouting_wan_rule
-A zone_wan_prerouting -j MINIUPNPD
COMMIT
# Completed on Sat Feb 20 20:41:20 2021

#Mangle chain

# Generated by iptables-save v1.8.7 on Sat Feb 20 20:41:20 2021
*mangle
:PREROUTING ACCEPT [976:199533]
:INPUT ACCEPT [976:199533]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [1535:834933]
:POSTROUTING ACCEPT [1535:834933]
:openclash - [0:0]
:openclash_dns_hijack - [0:0]
:openclash_output - [0:0]
-A PREROUTING -p udp -j openclash
-A PREROUTING -p tcp -m tcp --dport 53 -j openclash_dns_hijack
-A FORWARD -o eth0 -p tcp -m tcp --tcp-flags SYN,RST SYN -m comment --comment "!fw3: Zone wan MTU fixing" -j TCPMSS --clamp-mss-to-pmtu
-A FORWARD -i eth0 -p tcp -m tcp --tcp-flags SYN,RST SYN -m comment --comment "!fw3: Zone wan MTU fixing" -j TCPMSS --clamp-mss-to-pmtu
-A OUTPUT -j openclash_output
-A openclash -p udp -m udp --dport 500 -j RETURN
-A openclash -p udp -m udp --dport 546 -j RETURN
-A openclash -p udp -m udp --dport 68 -j RETURN
-A openclash -m set --match-set localnetwork dst -j RETURN
-A openclash -j MARK --set-xmark 0x162/0xffffffff
-A openclash_dns_hijack -d 8.8.8.8/32 -j MARK --set-xmark 0x162/0xffffffff
-A openclash_dns_hijack -d 8.8.4.4/32 -j MARK --set-xmark 0x162/0xffffffff
-A openclash_output -p udp -m udp --sport 500 -j RETURN
-A openclash_output -p udp -m udp --sport 546 -j RETURN
-A openclash_output -p udp -m udp --sport 68 -j RETURN
-A openclash_output -m set --match-set localnetwork dst -j RETURN
-A openclash_output -d 198.18.0.0/16 -p udp -m owner ! --uid-owner 65534 -j MARK --set-xmark 0x162/0xffffffff
COMMIT
# Completed on Sat Feb 20 20:41:20 2021

#===================== IPSET状态 =====================#

Name: localnetwork

#===================== 路由表状态 =====================#

#route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.1.1     0.0.0.0         UG    0      0        0 eth0
10.242.0.0      0.0.0.0         255.255.0.0     U     0      0        0 ztzlgmpcam
192.168.1.0     0.0.0.0         255.255.255.0   U     0      0        0 eth0
192.168.22.0    10.242.100.130  255.255.255.0   UG    0      0        0 ztzlgmpcam
192.168.33.0    0.0.0.0         255.255.255.0   U     0      0        0 br-lan
192.168.44.0    10.242.100.99   255.255.255.0   UG    0      0        0 ztzlgmpcam
192.168.55.0    10.242.100.232  255.255.255.0   UG    0      0        0 ztzlgmpcam
192.168.66.0    10.242.100.37   255.255.255.0   UG    0      0        0 ztzlgmpcam
192.168.77.0    10.242.100.179  255.255.255.0   UG    0      0        0 ztzlgmpcam
192.168.88.0    10.242.100.216  255.255.255.0   UG    0      0        0 ztzlgmpcam
192.168.99.0    10.242.100.121  255.255.255.0   UG    0      0        0 ztzlgmpcam
#ip route list
default via 192.168.1.1 dev eth0 proto static src 192.168.1.3 
10.242.0.0/16 dev ztzlgmpcam proto kernel scope link src 10.242.100.69 
192.168.1.0/24 dev eth0 proto kernel scope link src 192.168.1.3 
192.168.22.0/24 via 10.242.100.130 dev ztzlgmpcam proto static 
192.168.33.0/24 dev br-lan proto kernel scope link src 192.168.33.1 linkdown 
192.168.44.0/24 via 10.242.100.99 dev ztzlgmpcam proto static 
192.168.55.0/24 via 10.242.100.232 dev ztzlgmpcam proto static 
192.168.66.0/24 via 10.242.100.37 dev ztzlgmpcam proto static 
192.168.77.0/24 via 10.242.100.179 dev ztzlgmpcam proto static 
192.168.88.0/24 via 10.242.100.216 dev ztzlgmpcam proto static 
192.168.99.0/24 via 10.242.100.121 dev ztzlgmpcam proto static 
#ip rule show
0:	from all lookup local
32765:	from all fwmark 0x162 lookup 354
32766:	from all lookup main
32767:	from all lookup default

#===================== Tun设备状态 =====================#

ztzlgmpcam: tap

#===================== 端口占用状态 =====================#

tcp        0      0 127.0.0.1:7890          0.0.0.0:*               LISTEN      15165/clash
tcp        0      0 127.0.0.1:7891          0.0.0.0:*               LISTEN      15165/clash
tcp        0      0 127.0.0.1:7892          0.0.0.0:*               LISTEN      15165/clash
udp        0      0 127.0.0.1:7891          0.0.0.0:*                           15165/clash
udp        0      0 127.0.0.1:7892          0.0.0.0:*                           15165/clash
udp        0      0 :::7874                 :::*                                15165/clash

#===================== 测试本机DNS查询 =====================#

Server:		127.0.0.1
Address:	127.0.0.1#53

Name:      www.baidu.com
Address 1: 198.18.0.3
*** Can't find www.baidu.com: No answer

#===================== resolv.conf.d =====================#

# Interface wan
nameserver 192.168.1.1
search Home

#===================== 测试本机网络连接 =====================#

HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: private, no-cache, no-store, proxy-revalidate, no-transform
Connection: keep-alive
Content-Length: 277
Content-Type: text/html
Date: Sat, 20 Feb 2021 12:41:20 GMT
Etag: "575e1f7c-115"
Last-Modified: Mon, 13 Jun 2016 02:50:36 GMT
Pragma: no-cache
Server: bfe/1.0.8.18


#===================== 测试本机网络下载 =====================#

HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 80
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: text/plain; charset=utf-8
ETag: "00cdb0532e41777645c9ad3e0a65a1b1ac87d6afaf72cf6e33d925dbbd05be97"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: D3C8:6544:298AD:312C2:6025BA84
Accept-Ranges: bytes
Date: Sat, 20 Feb 2021 12:41:21 GMT
Via: 1.1 varnish
X-Served-By: cache-hkg17924-HKG
X-Cache: HIT
X-Cache-Hits: 1
X-Timer: S1613824881.151652,VS0,VE1
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
X-Fastly-Request-ID: 250996d6ac476e992e12e29e4ca0c3b2c35e4e46
Expires: Sat, 20 Feb 2021 12:46:21 GMT
Source-Age: 105


#===================== 最近运行日志 =====================#

time="2021-02-20T12:40:29Z" level=info msg="Start initial compatible provider FAST"
time="2021-02-20T12:40:29Z" level=info msg="Start initial compatible provider HK"
time="2021-02-20T12:40:29Z" level=info msg="Start initial compatible provider US"
time="2021-02-20T12:40:29Z" level=info msg="Start initial compatible provider TW"
time="2021-02-20T12:40:29Z" level=info msg="Start initial rule provider 隐私规则合集"
time="2021-02-20T12:40:29Z" level=info msg="Start initial rule provider Line TV"
time="2021-02-20T12:40:29Z" level=info msg="Start initial rule provider PBS(By lhie1)"
time="2021-02-20T12:40:29Z" level=info msg="Start initial rule provider Bahamut(By lhie1)"
time="2021-02-20T12:40:29Z" level=info msg="Start initial rule provider Disney Plus"
time="2021-02-20T12:40:29Z" level=info msg="Start initial rule provider 反劫持规则"
time="2021-02-20T12:40:29Z" level=info msg="Start initial rule provider 广告规则(By lhie1)"
time="2021-02-20T12:40:29Z" level=info msg="Start initial rule provider KKTV(By lhie1)"
time="2021-02-20T12:40:29Z" level=info msg="Start initial rule provider HBO(By lhie1)"
time="2021-02-20T12:40:29Z" level=info msg="Start initial rule provider Hulu(By lhie1)"
time="2021-02-20T12:40:29Z" level=info msg="DNS server listening at: 0.0.0.0:7874"
time="2021-02-20T12:40:29Z" level=info msg="SOCKS proxy listening at: 127.0.0.1:7891"
time="2021-02-20T12:40:29Z" level=info msg="HTTP proxy listening at: 127.0.0.1:7890"
time="2021-02-20T12:40:29Z" level=info msg="Redir proxy listening at: 127.0.0.1:7892"
2021-02-20 20:40:44 History:【config.yaml】 Restore Successful
2021-02-20 20:40:20 OpenClash Start Successful
2021-02-20 20:40:47 History:【config.yaml】 Update Faild
time="2021-02-20T12:41:18Z" level=info msg="[TCP] 192.168.1.3:59106 --> raw.githubusercontent.com match Match() using FAST[CN-HK1]"
time="2021-02-20T12:41:20Z" level=info msg="[TCP] 192.168.1.3:49372 --> www.baidu.com match GeoIP(CN) using DIRECT"
time="2021-02-20T12:41:20Z" level=info msg="[TCP] 192.168.1.3:59114 --> raw.githubusercontent.com match Match() using FAST[CN-HK1]"

```

```

**Comment by yhl452493373** [comment]
同问题+1，根据一个编译的大佬的说法，似乎是openclash和最新的openwrt之间存在兼容性问题，需要等v大修复这个问题。。。

**Comment by vernesong** [comment]
不确定是什么问题，相关命令在/usr/share/openclash/yml_change.sh

**Comment by lifetyper** [comment]
我这里测了下，这个commit https://github.com/vernesong/OpenClash/commit/7ab26bc17c874f5c050b8cf3f2feef5c75fd7349 确实已经修复了这个bug了
