### ISSUE TITLE
Conflict with busybox1.33

### ISSUE THREAD

**Issue by chilldawn** [vernesong/OpenClash#1223]
Issue description: after updated busybox to version 1.33 from official source code , openclash couldn't work normally. And the DASHBOARD CONTROL PANEL would open with '404 page not found' error, while the Yacd Control Panel interface was just OK.

Please consider fixing this, thx~!

**Comment by Phillweston** [comment]
我没装busybox，但是遇到了跟上面一样的问题。
yacd面板可以正常打开，dashboard面板不能正常打开。
