### ISSUE TITLE
自定义规则与订阅规则重复项

### ISSUE THREAD

**Issue by tshunhu** [vernesong/OpenClash#1226]
自定义规则里面定义的行为和订阅里面重复的时候，自定义规则不起作用吗？

比如：

#===================== 自定义规则 二 =====================#
-DOMAIN-SUFFIX,bing.com,DIRECT

#===================== 配置文件 =====================#
rueles:
-DOMAIN-SUFFIX,bing.com,Proxies

这个时候bing.com的流量还是走代理，应该怎么才能覆盖配置文件自带的规则呢？谢谢

**Comment by vernesong** [comment]
加到自定义规则一

**Comment by tshunhu** [comment]
> 加到自定义规则一

谢谢！重启路由以后有效了！
