### ISSUE TITLE
在19.07版本代码下，GEOIP数据库下载失败

### ISSUE THREAD

**Issue by lifetyper** [vernesong/OpenClash#123]
之前一直用Lean的18.06版本编译，一切正常。
昨天换成官方的19.07正式版编译，其他运行都正常，就是数据库下载失败。

我直接把openclash_ipdb.sh里的wget下载命令抽出来在路由器执行，是可以成功下载数据库的，所以网络状况是没问题的。但在设置页面点击更新后却总是提示下载失败，而且/tmp目录下确实也没下载到数据库文件。

尝试过把wget下载的重试次数增加到5，但没效果，似乎命令根本没有等待足够的超时时间，很快就结束并返回了下载失败。

没什么头绪，可能是哪里的问题呢？

**Comment by vernesong** [comment]
wget 的quiet参数去掉直接运行脚本，看是什么错误提示

**Comment by lifetyper** [comment]
只看到wget下载成功的返回信息，别的都没有，/tmp/openclash_start.log文件也是空的。
```
root@OpenWrt:/tmp# ./openclash_ipdb.sh
--2020-01-19 16:41:16--  https://static.clash.to/GeoIP2/GeoIP2-Country.mmdb
Resolving static.clash.to... 198.18.0.26
Connecting to static.clash.to|198.18.0.26|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4255911 (4.1M) [application/octet-stream]
Saving to: '/tmp/Country.mmdb'

/tmp/Country.mmdb                  100%[==============================================================>]   4.06M  12.0MB/s    in 0.3s

2020-01-19 16:41:21 (12.0 MB/s) - '/tmp/Country.mmdb' saved [4255911/4255911]
```

**Comment by vernesong** [comment]
试试去掉开头的sh
https://github.com/vernesong/OpenClash/blob/e63668ac954ccbce41cd08867ea10958a72a0141/luci-app-openclash/files/usr/lib/lua/luci/model/cbi/openclash/settings.lua#L320

**Comment by lifetyper** [comment]
删掉sh也是一样的，感觉这个脚本就没完整执行完。

**Comment by tony1016** [comment]
不光是地理位置吧，我这里订阅、内核下载，都不行

**Comment by lifetyper** [comment]
因为问题很多，所以很早就退回18.06版本了，其他的下载确实也有问题，感觉就是下载脚本根本没执行完。

--

**Comment by peterwjp2017** [comment]
> 不光是地理位置吧，我这里订阅、内核下载，都不行

如果你使用的是Snapshot的版本编译的，请确保安装了wget

**Comment by tony1016** [comment]
并不是，stable版本

Peter Wang <notifications@github.com> 于 2020年2月4日周二 上午10:43写道：

**Comment by lifetyper** [comment]
这问题，并没有解决啊。。。

**Comment by tony1016** [comment]
似乎解决了，新版本用了curl,我用了发现没问题了

毕勤 <notifications@github.com> 于 2020年2月21日周五 下午5:32写道：

**Comment by lifetyper** [comment]
呃，看来我忘了装curl，回头再试试

--

**Comment by lifetyper** [comment]
我试了一下，核心程序更新是正常的，但geoip数据库的下载和之前是一样的，依然失败。
