### ISSUE TITLE
youtube无法连接到互联网

### ISSUE THREAD

**Issue by wanglovee** [vernesong/OpenClash#1232]
打开openclash之后其他网站都能访问，只有YouTube无法访问，请问这是什么问题？

**Comment by JessYi228** [comment]
https://github.com/vernesong/OpenClash/issues/212#issuecomment-596194084
我也只有YouTube不能看，但是照着这样整好了

**Comment by wanglovee** [comment]
> [#212 (comment)](https://github.com/vernesong/OpenClash/issues/212#issuecomment-596194084)
> 我也只有YouTube不能看，但是照着这样整好了

ipv6都关了也一样
