### ISSUE TITLE
英雄联盟 进游戏大概率延迟高  50ms以上（正常30ms左右）

### ISSUE THREAD

**Issue by Huppert96** [vernesong/OpenClash#1233]
如题，开着openclash玩英雄联盟，大概率会出现高延迟，50ms-100ms，正常的话是30ms左右，而且对游戏体验影响特别大，感觉不只是延迟高了，也会出现丢包的现象，直观感觉起来就是特别卡。

**Comment by Huppert96** [comment]
有时候退出游戏，重新连接之后就会恢复正常。  偶尔会出现（目前就遇到一两次）退出游戏重新连接也没法儿解决的情况。

**Comment by vernesong** [comment]
尝试混合模式

**Comment by Bruce-panruosong** [comment]
> 尝试混合模式

英雄联盟的是tcp连接，混合模式好像没什么用吧。。。

**Comment by vernesong** [comment]
> > 尝试混合模式
> 
> 英雄联盟的是tcp连接，混合模式好像没什么用吧。。。

绕过国内呢

**Comment by Pacio** [comment]
> > > 尝试混合模式
> > 
> > 
> > 英雄联盟的是tcp连接，混合模式好像没什么用吧。。。
> 
> 绕过国内呢

我也有这个问题，clash我适合很多种组合也没有plus+里面的gfw那种效果，就是能在走国外流量下载的时候不影响国内游戏的延迟，我这边测试游戏延迟都从个位数上升到了50ms左右
