### ISSUE TITLE
在配置文件管理界面，保存配置导致 LuCI 卡死

### ISSUE THREAD

**Issue by fanck0605** [vernesong/OpenClash#1235]
系统版本：openwrt-21.02-SNAPSHOT
LuCI版本：openwrt-21.02-SNAPSHOT
Clash版本：v0.42.01

在 **配置文件管理** 界面点击 **保存配置** 或 **应用配置** 按钮，会导致LuCI直接卡死，
无法再次进入任何后台界面，重启 uhttpd 才能恢复正常

**Comment by fanck0605** [comment]
![image](https://user-images.githubusercontent.com/28819315/108961343-2b70c880-76b2-11eb-8355-7ccbbf0b233f.png)

**Comment by fanck0605** [comment]
@vernesong 如果有空的话，可以帮忙排查一下吗。
特地又测试了一下，默认的模板配置点保存不会有问题，用了 ACL4SSR Online 模板转换出来的配置文件就会出现问题。

**Comment by fanck0605** [comment]
300KB 的配置文件过大，luci 卡死，与 OpenClash 无关。

**Comment by SWBMESSI** [comment]
luci卡死会自动恢复么，或者是需要什么处理

**Comment by bingoku** [comment]
跟 wget 有关，但 wget 其实是在下载 bing 的壁纸，这里会卡主，搞个定时任务 pgrep wget | xargs kill -9 不让下载壁纸就行了。

**Comment by WYC-2020** [comment]
搞得这么花里花哨，还动态下载壁纸

**Comment by WYC-2020** [comment]
要是没网络岂不是卡的连后台都进不去哈哈
