### ISSUE TITLE
Netflix等网站可以连接，但Google确无法连接youtube可打开，视频无法播放

### ISSUE THREAD

**Issue by denghulk** [vernesong/OpenClash#1236]
![image](https://user-images.githubusercontent.com/50483107/108751817-a4bacf00-757d-11eb-9bfd-5aeef3968ed8.png)

**Comment by vernesong** [comment]
https://github.com/vernesong/OpenClash/wiki/%E7%BD%91%E7%BB%9C%E8%BF%9E%E6%8E%A5%E5%BC%82%E5%B8%B8%E6%97%B6%E6%8E%92%E6%9F%A5%E5%8E%9F%E5%9B%A0

**Comment by denghulk** [comment]
谢谢大神，已解决。
openwrt系统，取消勾选如下位置后。问题解决。
![image](https://user-images.githubusercontent.com/50483107/109010376-a655d580-76ea-11eb-910a-f4c1a9d0a877.png)

**Comment by Edger** [comment]
> 谢谢大神，已解决。
> openwrt系统，取消勾选如下位置后。问题解决。
> ![image](https://user-images.githubusercontent.com/50483107/109010376-a655d580-76ea-11eb-910a-f4c1a9d0a877.png)

解决了，谢谢。
应该把这个方案指定才对的。

**Comment by shenyanshu** [comment]
> 谢谢大神，已解决。
> openwrt系统，取消勾选如下位置后。问题解决。
> ![image](https://user-images.githubusercontent.com/50483107/109010376-a655d580-76ea-11eb-910a-f4c1a9d0a877.png)

youtube每次播放一段时间后就会报错无法播放，用这个方法解决了
