### ISSUE TITLE
在开启混合模式之后带宽被限制到只有200Mbps

### ISSUE THREAD

**Issue by a936919** [vernesong/OpenClash#1237]
![image](https://user-images.githubusercontent.com/41937411/108806864-d9f70980-75dd-11eb-8f64-9740ba8ca84c.png)
只有把这个绕过中国大陆IP启用之后
才会恢复正常

**Comment by piaoyizy** [comment]
什么设备？？？？CPU？？？


饶过好像 是 ipset排除了大陆ip列表，开始后就不走clash了

**Comment by a936919** [comment]
N1

**Comment by lifetyper** [comment]
看看CPU是不是跑满了

**Comment by MBRjun** [comment]
一般是性能问题
