### ISSUE TITLE
求问，在Fak-Ip（增强）模式下，守望先锋（国服）无法连接到服务器

### ISSUE THREAD

**Issue by mercy90428** [vernesong/OpenClash#1238]
求解决方法，感谢！！！！

**Comment by MechanE** [comment]
遇到类似的问题，打开fakeip 打开udp转发，坦克世界 可以ping通服务器，但是无法连接，redir-hosts则没有这个问题

**Comment by lnaxk** [comment]
没有同样是fake ip 建议贴log才知道什么情况

**Comment by helllkz** [comment]
我也有类似问题，不过是CSGO，无法搜索到社区服务器，关闭Clash就好了，暂时还没试过其他模式

**Comment by Nymph2333** [comment]
> 遇到类似的问题，打开fakeip 打开udp转发，坦克世界 可以ping通服务器，但是无法连接，redir-hosts则没有这个问题

2024年了坦克世界还是有同样的问题

**Comment by coofly** [comment]
> > 遇到类似的问题，打开fakeip 打开udp转发，坦克世界 可以ping通服务器，但是无法连接，redir-hosts则没有这个问题
> 
> 2024年了坦克世界还是有同样的问题

https://github.com/vernesong/OpenClash/issues/1588
这里有解决办法
