### ISSUE TITLE
最新版本页面经常显示连接超时！！！

### ISSUE THREAD

**Issue by zxlhhyccc** [vernesong/OpenClash#124]
![image](https://user-images.githubusercontent.com/45259624/72815903-57956b00-3ca2-11ea-965a-47c1f50386b5.png)
![image](https://user-images.githubusercontent.com/45259624/72815908-5c5a1f00-3ca2-11ea-8a00-403c6c65c572.png)
![image](https://user-images.githubusercontent.com/45259624/72815923-60863c80-3ca2-11ea-8853-ba9e49919d7b.png)

**Comment by vernesong** [comment]
跟客户端关系不大，建议你用fake-ip，排除本地干扰
