### ISSUE TITLE
【建议】策略组配置中提供添加服务器选项

### ISSUE THREAD

**Issue by zane-ng** [vernesong/OpenClash#1246]
如题：目前和长久以来的版本只支持读取配置后，修改服务器信息时将其添加至某一策略组。

考虑到：1）服务器往往多于策略组；2）同一地区服务器更可能被用来组成某一策略组，则按照目前设置，创建策略组时会特别麻烦。

例如：假设用户有一项网络服务需要使用美国地区服务器，而其配置中有 10 个美国地区服务器。则当用户想创建一个仅有这些美国地区服务器的策略组时，他需要在概览和每个服务器节点配置之间至少往返十次，而且可能会忘记之前点过哪个。同时由于服务器节点列表很长，滚动也比较费劲。

相较之下，如果能够在编辑策略组时，直接添加 10 个服务器，就会快捷很多。这个功能可以参照现有游戏规则等自定义规则功能的下拉列表。

当然，最快速的方法可能时直接修改配置然后读取配置。但如果服务器节点本身可以在 UI 编辑其所属的策略组，那么同理策略组应当同样可以在 UI 编辑其所包含的服务器。

最后谢谢作者辛勤开发。祝生活愉快一切顺利。

**Comment by caliban511** [comment]
请教一下楼主，如何把获取到的节点加入到其中几个策略组中呢？我自己也试着建过，可惜不管怎么弄节点都不进组。

**Comment by zane-ng** [comment]
> 请教一下楼主，如何把获取到的节点加入到其中几个策略组中呢？我自己也试着建过，可惜不管怎么弄节点都不进组。

你好：
在「服务器与策略组管理」页中，导入服务器信息后，点击修改，可以将服务器加入某个策略组中。
然后须保存设置后使用本页的应用设置按钮。

**Comment by caliban511** [comment]
> > 请教一下楼主，如何把获取到的节点加入到其中几个策略组中呢？我自己也试着建过，可惜不管怎么弄节点都不进组。
> 
> 你好：
> 在「服务器与策略组管理」页中，导入服务器信息后，点击修改，可以将服务器加入某个策略组中。
> 然后须保存设置后使用本页的应用设置按钮。

谢谢，原来这里是这样用的。不过这就麻烦了，不能在更新订阅时直接自动套用，就不适合我这种几个订阅切换着使用的用户了，目前看来还是订阅时转换人家做好的更方便。
