### ISSUE TITLE
在内核mipsle 下，在版本更新下，新版内核更新后，都出现无法显示版本内容

### ISSUE THREAD

**Issue by Job28703** [vernesong/OpenClash#1247]
在内核mipsle 下，在版本更新下，新版内核更新后，都出现无法显示版本内容. 包括：
[dev] 最新内核版本
[TUN] 最新内核版本
[Game] 最新内核版本
最新客户端版本

**Comment by vernesong** [comment]
去官方那下载替换未压缩版本的内核

**Comment by caicaicai21** [comment]
我是自己编译的内核，upx最大压缩，运行正常
![image](https://user-images.githubusercontent.com/26214093/109377127-40449a80-7904-11eb-93a0-29a3774df89a.png)
但自动下载的内核无法运行，会卡住
![屏幕截图 2021-02-27 140500](https://user-images.githubusercontent.com/26214093/109377216-d973b100-7904-11eb-8a76-ca24f8769d94.png)
因为k2p闪存比较小（还没硬改），只能下载到内存，重启就会没了，所以希望可以查一下是什么原因呢。

**Comment by Job28703** [comment]
下载转存在 /etc/openclash/core/里，是有问题！！但用前几版V0.41.XX 的内核转存是没有问题，奇怪，只能用旧版内核。

**Comment by vernesong** [comment]
压缩参数的问题，你提供一下能用的压缩参数，我这边upx是3.96

**Comment by caicaicai21** [comment]
> 压缩参数的问题，你提供一下能用的压缩参数，我这边upx是3.96

我是Dreamacro的源码+z自修改的go-shadowsocks2直接make编译的，upx只是加了 --best 参数，upx版本是 3.95。clash是用golang 1.16编译的。

**Comment by caicaicai21** [comment]
我试了一下只使用 --ultra-brute 参数压缩，可以正常运行，体积比 --best 更小了，跟你提供的差不多大小
![image](https://user-images.githubusercontent.com/26214093/109390388-48c0c380-794c-11eb-99e5-5b638bfff31f.png)
![image](https://user-images.githubusercontent.com/26214093/109390392-58400c80-794c-11eb-9785-917edacaf901.png)

**Comment by Job28703** [comment]
V0.42.02 core 7.26 MB 导入后，更新版本则停留在（无法显示），下载解压汇入也是（无法显示）
V0.41.07 core 9.79 MB 导入后，不更新则显示旧版本
如上所说 参数压缩则可正常，不太可能？

**Comment by vernesong** [comment]
是3.96测试的吗？

**Comment by Job28703** [comment]
沒有用3.96，直接从V0.41.07 core里取出，COPY 到 V0.42.02 core里。不更新则显示旧版本，更新后就无法显示了！！这是何原因？

**Comment by p0tat05** [comment]
我也是 mipsle-softfloat 最新版core更新之后直接无法正常运行，手动安装v0.41.14的core之后可正常使用。
另外一台路由器 linux-armv7 的最新版core则正常。

**Comment by konbar** [comment]
我把内核用老版本[dev] 当前内核版本 v1.1.0-19-g8766287替换就正常了。。现在是0.42.02版就好好的了。。同样一直折腾我好几天了

**Comment by mkh310** [comment]
一样的，mipsle-softflaot更新内核之后无法识别也无法运行。折腾好几天了，有什么解决办法吗。谢谢

**Comment by p0tat05** [comment]
> 一样的，mipsle-softflaot更新内核之后无法识别也无法运行。折腾好几天了，有什么解决办法吗。谢谢

手动回退到v0.41.14版本的内核即可。在 https://github.com/vernesong/OpenClash/blob/v0.41.14-beta/core-lateset/dev/clash-linux-mipsle-softfloat.tar.gz?raw=true 下载，解压后放到 /etc/openclash/core 目录下。

**Comment by mkh310** [comment]
> > 一样的，mipsle-softflaot更新内核之后无法识别也无法运行。折腾好几天了，有什么解决办法吗。谢谢
> 
> 手动回退到v0.41.14版本的内核即可。在 https://github.com/vernesong/OpenClash/blob/v0.41.14-beta/core-lateset/dev/clash-linux-mipsle-softfloat.tar.gz?raw=true 下载，解压后放到 /etc/openclash/core 目录下。

十分感谢，以成功解决。

**Comment by Orokapei** [comment]
> 是3.96测试的吗？

这个问题以前也有版本出现过，当时使用git最新版本编译出来的upx再压缩是没有问题的= =

**Comment by 1715173329** [comment]
mips 需要用 upx 3.95 版本

**Comment by causlayer** [comment]
@imdlxx 回退到v0.41.14版本的内核也不行了，请问现在有可用的最新版本吗？
我现在用的openclash是0.45.35版本，谢谢
