### ISSUE TITLE
开启后智能猫眼就无法连接服务器

### ISSUE THREAD

**Issue by daohunliwei** [vernesong/OpenClash#1248]
各种方法都试了，规则，访问控制，切换模式，放行所有域名，都白搭，只要一开启clash就不行

**Comment by vegetable-zxq** [comment]
原来不止我自己这样，求个解决办法

**Comment by daohunliwei** [comment]
> 原来不止我自己这样，求个解决办法

我看了其他的issue，不止咱俩，而且每一个issue的方法我都试了，不适用于我，不起作用，这个问题可能根源一直没找到，其他issue也只是绕过去了

**Comment by yohaoquan** [comment]
我的红外遥控曾经也有过类似的问题。我的解决方法是在全局设置 -> 访问控制下将你的设备加入不走代理的局域网设备。建议用Mac地址

**Comment by daohunliwei** [comment]
> 我的红外遥控曾经也有过类似的问题。我的解决方法是在全局设置 -> 访问控制下将你的设备加入不走代理的局域网设备。建议用Mac地址

试过了，没有用，不管是ip还是mac，都不行

**Comment by roninriddle** [comment]
- SRC-IP-CIDR,ipipipip,DIRECT
可以连接，但是基本30秒重连一次，满电设备一天耗完，感觉是网络不稳定一直波动。
我觉得最好的办法是这个ip的流量就不通过openclash转发。应该是防火墙设置，但是没找到解决方案。

**Comment by trombonist852** [comment]
我也是 开了openclash鹿客猫眼就无法连接了，期待大神修复！

**Comment by roninriddle** [comment]
没做任何调整，时好时坏。有人有解决办法了么。
