### ISSUE TITLE
运行日志出现大量配置文件“Update Faild”错误

### ISSUE THREAD

**Issue by zzxjohn** [vernesong/OpenClash#1254]
如图，我的配置文件是本地上传的，并没有订阅任何链接，但是运行日志里每1分钟就会新增“ History:【clash-1.yaml】 Update Faild”错误一条，请问这是bug吗？谢谢！
<img width="971" alt="Screenshot 2021-03-05 at 7 50 17 AM" src="https://user-images.githubusercontent.com/9846060/110046728-862bb380-7d87-11eb-8414-3100c561b603.png">

**Comment by vernesong** [comment]
检查启动配置文件有没有设置external-controller:

**Comment by zzxjohn** [comment]
配置文件有设置external-controller
<img width="244" alt="Screenshot 2021-03-09 at 12 20 38 AM" src="https://user-images.githubusercontent.com/9846060/110349174-6a692b80-806d-11eb-90d1-855eea7dc1d6.png">

**Comment by vernesong** [comment]
控制面板能登陆吗？正常的话检查curl
