### ISSUE TITLE
如何能让路由器自身发起的流量出海？

### ISSUE THREAD

**Issue by matthuo333** [vernesong/OpenClash#1255]
请教大神，目前局域网中的其它设备经OP（Docker 运行的）后均可正常出海，但是OP中本身发起的流量确不行，比如OP中curl google.com， 一直未有反馈。 

一直查不出原因，请大神指点。

**Comment by vernesong** [comment]
检查libcap依赖

**Comment by matthuo333** [comment]
> 检查libcap依赖

![image](https://user-images.githubusercontent.com/55862904/110205098-888a2c80-7eb1-11eb-8398-edeea7623587.png)

**Comment by matthuo333** [comment]
另外，有推荐使用这里方法，不知可行？https://comzyh.gitbook.io/clash/real-ip-tun-example

**Comment by vernesong** [comment]
发调试日志

**Comment by matthuo333** [comment]
> 发调试日志

#===================== 依赖检查 =====================#
dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
jsonfilter: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
iptables-mod-tproxy: 已安装
kmod-tun(TUN模式): 已安装
luci-compat(Luci-19.07): 已安装

**Comment by matthuo333** [comment]
确实没有libcap

**Comment by matthuo333** [comment]
是需要安装？ 怎么安装呢？

**Comment by matthuo333** [comment]
貌似之前安装测试过，好像是内核版本低（3.14.29），没有装libcap成功

**Comment by vernesong** [comment]
老版本？用fakeip模式

**Comment by matthuo333** [comment]
用fake ip正常，但是NAT 后（建立了个SecureNAT），就访问不到openclash了

**Comment by vernesong** [comment]
主机名是域名的话要写到dns高级设置的黑名单里

**Comment by matthuo333** [comment]
> 主机名是域名的话要写到dns高级设置的黑名单里

这里说的主机名是指，我的拓扑是这样： 移动端出海应用 ->VPN客户端->VPN服务端->Open Clash ->VPS

其中VPN服务端建立SecureNAT, 在Redir模式下，VPN中的设备是可以访问到NAT后的设备，比如手机VPN(192.168.3.x) 可访问到Openwrt(192.168.1.x). 但是此时应该由于OP本身流量未出海，导致始终未走Clash.
改用Fake-ip模式后，就无法访问到OP了。

基于这个，你说的主机名是指？

**Comment by vernesong** [comment]
Openwrt跟服务端通信要用真实ip连接，clash因为会返回faleip，所以可能连接不了

**Comment by matthuo333** [comment]
> Openwrt跟服务端通信要用真实ip连接，clash因为会返回faleip，所以可能连接不了

那可否在Redir模式下，继续解这个问题？低版本安装libcap?

**Comment by vernesong** [comment]
你的服务端地址是不是域名？是就加到DNS高级设置里去

**Comment by matthuo333** [comment]
> 你的服务端地址是不是域名？是就加到DNS高级设置里去

嗯嗯，我先DD恢复下。。。文件系统被我改的乱七八糟了。 明天一早就继续试，谢谢大神哈

**Comment by matthuo333** [comment]
大神，成功了，真是感谢感谢！！

**Comment by matthuo333** [comment]
大神，补充一句，是不是目前这样设置下，在面板中无法看到流量监控了？目前没有了
