### ISSUE TITLE
关于dns的一些问题，请大佬看看

### ISSUE THREAD

**Issue by leter** [vernesong/OpenClash#1256]
我旁路由装的openClash
客户端的网关写的是旁路由的ip
dns写的却是主路由的ip
有以下几个问题：
1.翻墙访问youtube的话究竟用的是哪个dns服务器,是旁路由的还是主路由的？
2.如果把客户端的dns也设置成旁路由的，那么国内走直连的网址的ip是不是也是通过openClash的内置dns来获取的
3.dns请求究竟是在旁路由端本地发起的还是vps服务端发起的

**Comment by vernesong** [comment]
流量在旁路由就给到clash了，所有DNS都是clash来查询，需要代理的DNS都是在服务器上查询，其他走nameserver
