### ISSUE TITLE
安装openclash后在服务界面找不到

### ISSUE THREAD

**Issue by Xunflash** [vernesong/OpenClash#1258]
![image](https://user-images.githubusercontent.com/71567536/110153970-ae1a2600-7e1e-11eb-8711-89c11061d0e6.png)
小米路由器3刷openwrt，腾讯源，软件包里显示已经安装，清除tmp目录下indexcache也没用，重启也没用。tmp目录下已经存在clash的log文件了

**Comment by vernesong** [comment]
/etc/config/openclash文件有没有

**Comment by downDrop** [comment]
> / etc / config / openclash文件有没有

我的/etc/config/openclash目录下有但是服务里面没有

**Comment by Xunflash** [comment]
> /etc/config/openclash文件有没有

换固件了，但是可能是uhttpd和nginx冲突?我还尝试过把ssr plus卸载再装openclash，然后服务里面出现了openclash，反正就是很怪
