### ISSUE TITLE
Ruby报错

### ISSUE THREAD

**Issue by Synchronized1** [vernesong/OpenClash#1259]
1.在KoolShare LEDE(Openwrt Koolshare mod V2.31 r10822-50aa0525d1)下使用如下命令安装ruby依赖
  opkg update
  opkg install ruby
  opkg install ruby-yaml

2.安装后的包如下
ruby - 3.0.0-1
ruby-bigdecimal - 3.0.0-1
ruby-date - 3.0.0-1
ruby-dbm - 3.0.0-1
ruby-digest - 3.0.0-1
ruby-enc - 3.0.0-1
ruby-forwardable - 3.0.0-1
ruby-pstore - 3.0.0-1
ruby-psych - 3.0.0-1
ruby-stringio - 3.0.0-1
ruby-strscan - 3.0.0-1
ruby-yaml - 3.0.0-1

3.使用ruby -v 测试报错
![image](https://user-images.githubusercontent.com/58451554/110191083-bfd0ed00-7e61-11eb-857a-223864c3cf45.png)

![image](https://user-images.githubusercontent.com/58451554/110191212-340b9080-7e62-11eb-9ad6-55a434a5d45f.png)

没有找到这个错误的解决方案,请问各位大佬如果解决ruby依赖问题.

**Comment by vernesong** [comment]
之所以用这几个官方有的依赖就是怕不兼容，koolshare那边可以提意见预装，不然建议你用40.7的老版本
