### ISSUE TITLE
间歇性无法访问google.com

### ISSUE THREAD

**Issue by SuperAIdesu** [vernesong/OpenClash#126]
Fake-ip模式，间歇性无法访问google.com，此时其他所有网站访问正常，包括google.com.hk等。重启openclash可自动恢复。日志中无warning。最新版本，openwrt 19.07。

**Comment by vernesong** [comment]
DNS解析和连接都是发到服务器上进行的，此模式下的连接不稳定都首先需要你确认节点情况。
