### ISSUE TITLE
Ruby依赖异常，请确认Ruby依赖巩工作正常后重试。

### ISSUE THREAD

**Issue by tgfcer** [vernesong/OpenClash#1262]
大佬，这是啥错误撒

**Comment by BabXhwZUNBeTV** [comment]
> 请先安装好这些依赖: coreutils-nohup, bash, iptables, dnsmasq-full, curl, jsonfilter, ca-certificates, ipset, ip-full, iptables-mod-tproxy, iptables-mod-extra, libcap, libcap-bin, ruby, ruby-yaml

问问题请提供尽可能详尽的信息。包括及不限于 截图 文字 视频 。
先学习怎么提问题。
https://github.com/tvvocold/How-To-Ask-Questions-The-Smart-Way

根据你的问题 只能猜测 ruby ruby-yaml 没有安装或者异常 请重装这两个 ipk
