### ISSUE TITLE
ipv6与Netflix问题

### ISSUE THREAD

**Issue by YnSen** [vernesong/OpenClash#1265]
电信网络,爱快拨号并开启ipv6的dhcp（不开openwrt获取不到ipv6地址，openwrt已安装openclash所有需要的依赖），在openclash全局设置-dns设置-勾选了允许IPv6DNS解析（因为用ipv6地址做了ddns，关闭此项后打开openclash设备会访问不了ipv6地址），打开Netflix会显示Not Available，开始以为是规则的问题后来换了其他规则也显示Not Available，但是其他需要代理的网址都能正常访问，关闭IPv6DNS解析后，可以正常访问Netflix。请问改怎么设置才可以在勾选ipv6dns解析的情况下看Netflix

**Comment by vernesong** [comment]
进控制面板看连接日志

**Comment by YnSen** [comment]
> 进控制面板看连接日志

访问的时候打开Connections，浏览器访问Netflix流量不会过clash，但是在Windows下用app，Connections的活动链接里会显示走了规则的节点，有时会加载出页面但是无法观看视频，手机app打开也和windows app一样

**Comment by YnSen** [comment]
> 进控制面板看连接日志

time="2021-03-07T19:25:29+08:00" level=info msg="[TCP] 192.168.3.66:40194 --&gt; android.prod.cloud.netflix.com match DomainSuffix(netflix.com) using 🌍 国外媒体[🇭🇰 【ss香港5G-HKT-NF原生内网加密隧道-1.0x】03]"
time="2021-03-07T19:25:29+08:00" level=info msg="[TCP] 192.168.3.66:40192 --&gt; android.prod.cloud.netflix.com match DomainSuffix(netflix.com) using 🌍 国外媒体[🇭🇰 【ss香港5G-HKT-NF原生内网加密隧道-1.0x】03]"
time="2021-03-07T19:25:29+08:00" level=info msg="[TCP] 192.168.3.66:46102 --&gt; android-appboot.netflix.com match DomainSuffix(netflix.com) using 🌍 国外媒体[🇭🇰 【ss香港5G-HKT-NF原生内网加密隧道-1.0x】03]"
time="2021-03-07T19:25:19+08:00" level=info msg="[TCP] 192.168.3.66:48573 --&gt; android.prod.ftl.netflix.com match DomainSuffix(netflix.com) using 🌍 国外媒体[🇭🇰 【ss香港5G-HKT-NF原生内网加密隧道-1.0x】03]"
time="2021-03-07T19:25:04+08:00" level=info msg="[TCP] 192.168.3.60:2150 --&gt; win10.prod.http1.netflix.com match DomainSuffix(netflix.com) using 🌍 国外媒体[🇭🇰 【ss香港5G-HKT-NF原生内网加密隧道-1.0x】03]"

**Comment by vernesong** [comment]
插件关闭ipv6的解析，在DNS高级设置里面把第二DNS服务器设置为爱快的地址，下面域名写你的DDNS域名

**Comment by YnSen** [comment]
> 插件关闭ipv6的解析，在DNS高级设置里面把第二DNS服务器设置为爱快的地址，下面域名写你的DDNS域名

谢谢，已解决了，我用的是Redir-Host（兼容）模式，只是在第二DNS服务器设置的是IPv6的公共DNS，设置成爱快的地址没用i😅
