### ISSUE TITLE
请问Dashboard 控制面板能通过端口转发实现远程连接吗？

### ISSUE THREAD

**Issue by gcl52** [vernesong/OpenClash#1266]
我映射了9090端口，不能通过域名+端口打开Dashboard 控制面板，这样的话无法对节点进行管理，有什么办法吗，谢谢！

**Comment by vernesong** [comment]
怎么设置的也不说清楚我怎么解决？
路由能访问的话直接用yacd就行，不需要端口转发

**Comment by pillanangel** [comment]
Dashboard映射格式可以设置如下试试。
http://192.168.x.x:9090/ui/
不过貌似Yacd不能直接映射用。

**Comment by vernesong** [comment]
就是你访问luci的地址后面改成 http://192.168.x.x/luci-static/openclash

**Comment by gcl52** [comment]
谢谢

**Comment by vernesong** [comment]
yacd要单独映射9090端口，进去是luci地址后面加/luci-static/openclash，登陆是外部映射的9090的地址和端口
