### ISSUE TITLE
rule_provider下缓存的文件，不会更新

### ISSUE THREAD

**Issue by MXKecetyCN** [vernesong/OpenClash#1268]
反馈一个bug：rule_provider下缓存的文件，不会更新，甚至手动更新后，也是暂时的，openclash内rule_provider文件夹内的缓存也没更新
然后会时不时变回旧的yaml

**Comment by Eintler** [comment]
遇到同样问题,就是规则无法自动更新.

**Comment by MOOnLyer** [comment]
盲猜是路径问题
日志中有相关错误
Edit Provider Path Error: undefined method `values' for nil:NilClass

**Comment by MXKecetyCN** [comment]
> 盲猜是路径问题
> 日志中有相关错误
> Edit Provider Path Error: undefined method `values' for nil:NilClass

在路径/etc/openclash/rule_provider中替换yaml文件后，后续新启动都会采用替换后的文件

但是如果该规则文件通过Dashboard 控制面板-规则来刷新，只可临时更新（openclash重启后失效），并不会把/rule_provider里的文件替换

**Comment by iam7cn** [comment]
这个问题解决了吗？我也是有同样问题，必须每次把旧的代理集删除才能更新，路径也改为/rule_provider下，是不是权限问题啊？

**Comment by iam7cn** [comment]
> 这个问题解决了吗？我也是有同样问题，必须每次把旧的代理集删除才能更新，路径也改为/rule_provider下，是不是权限问题啊？

找到问题了，之前代理集更新地址在 ``` proxy_provider/test.yaml ``` 改成 ``` ./proxy_provider/test.yaml ```就没问题了
