### ISSUE TITLE
不建议为 Clash 的 tun 启用 IPv6 支持

### ISSUE THREAD

**Issue by Kr328** [vernesong/OpenClash#127]
https://github.com/vernesong/OpenClash/blob/bf97526bb8c909294c810e611664a9eca5a7468a/luci-app-openclash/files/etc/init.d/openclash#L777-L780

目前 Clash 的 tun 并不会正确的反馈 TCP 连接状态
在有 TCP 连接经过 tun 时 立即完成 TCP 握手
在某些 App 上 (屑 Ins
App 会在 TCP 握手完成后 认为 连接可用
某些 App 在认为 IPv6 可用后 **会只尝试IPv6连接 即使 连接立即被重置** (屑 Ins (二回啊二回

**Comment by Kr328** [comment]
顺便 感觉可以用 uidrange 来处理 tun (
毕竟 路由上 iptables 争夺太厉害了 (

参见 [此链接](https://github.com/Kr328/clash-tun-for-linux/blob/master/clash-setup-tun.sh)

**Comment by vernesong** [comment]
这块忘记加判断了，这几天返工，回头有空再测试下uidrange

**Comment by OG-C** [comment]
CFW建议启用ipv6吗？
