### ISSUE TITLE
DNS 查询出错

### ISSUE THREAD

**Issue by Eintler** [vernesong/OpenClash#1273]
# DNS
dns:
  listen: 127.0.0.1:7874
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
##Custom fake-ip-filter##
    - '*.lan'
    - 'time.windows.com'
    - 'time.nist.gov'
    - 'time.apple.com'
    - 'time.asia.apple.com'
    - '*.ntp.org.cn'
    - '*.openwrt.pool.ntp.org'
    - 'time1.cloud.tencent.com'
    - 'time.ustc.edu.cn'
    - 'pool.ntp.org'
    - 'ntp.ubuntu.com'
    - 'ntp.aliyun.com'
    - 'ntp1.aliyun.com'
    - 'ntp2.aliyun.com'
    - 'ntp3.aliyun.com'
    - 'ntp4.aliyun.com'
    - 'ntp5.aliyun.com'
    - 'ntp6.aliyun.com'
    - 'ntp7.aliyun.com'
    - 'time1.aliyun.com'
    - 'time2.aliyun.com'
    - 'time3.aliyun.com'
    - 'time4.aliyun.com'
    - 'time5.aliyun.com'
    - 'time6.aliyun.com'
    - 'time7.aliyun.com'
    - '*.time.edu.cn'
    - 'time1.apple.com'
    - 'time2.apple.com'
    - 'time3.apple.com'
    - 'time4.apple.com'
    - 'time5.apple.com'
    - 'time6.apple.com'
    - 'time7.apple.com'
    - 'time1.google.com'
    - 'time2.google.com'
    - 'time3.google.com'
    - 'time4.google.com'
    - 'music.163.com'
    - '*.music.163.com'
    - '*.126.net'
    - 'musicapi.taihe.com'
    - 'music.taihe.com'
    - 'songsearch.kugou.com'
    - 'trackercdn.kugou.com'
    - '*.kuwo.cn'
    - 'api-jooxtt.sanook.com'
    - 'api.joox.com'
    - 'joox.com'
    - 'y.qq.com'
    - '*.y.qq.com'
    - 'streamoc.music.tc.qq.com'
    - 'mobileoc.music.tc.qq.com'
    - 'isure.stream.qqmusic.qq.com'
    - 'dl.stream.qqmusic.qq.com'
    - 'aqqmusic.tc.qq.com'
    - 'amobile.music.tc.qq.com'
    - '*.xiami.com'
    - '*.music.migu.cn'
    - 'music.migu.cn'
    - '*.msftconnecttest.com'
    - '*.msftncsi.com'
    - 'localhost.ptlogin2.qq.com'
    - '+.srv.nintendo.net'
    - '+.stun.playstation.net'
    - 'xbox.*.microsoft.com'
    - '+.xboxlive.com'
    - 'proxy.golang.org'
    - 'stun.*.*'
    - 'stun.*.*.*'
    - 'heartbeat.belkin.com'
    - '*.linksys.com'
    - '*.linksyssmartwifi.com'
    - '+.github.com'
##Custom fake-ip-filter END##
  default-nameserver:
    - 114.114.114.114
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
  nameserver:
    - https://dns.alidns.com/dns-query
    - tls://dns.rubyfish.cn:853
    - 114.114.114.114
    - 223.5.5.5
  fallback:
    - tls://1.1.1.1
    - https://dns.cloudflare.com/dns-query
    - tls://dns.google
    - https://dns.google/dns-query
  fallback-filter:
    geoip: true # default
    ipcidr: # ips in these subnets will be considered polluted
      - 240.0.0.0/4
# rule

rules:  
  # 国内网站
  - DOMAIN-SUFFIX,cn,DIRECT
  - DOMAIN-KEYWORD,-cn,DIRECT

  # Custom
  - DOMAIN-SUFFIX,ea.com,DIRECT 
  - DOMAIN-KEYWORD,xbox,DIRECT
  - DOMAIN-KEYWORD,microsoft,DIRECT
  
  
  - PROCESS-NAME,v2ray,auto
  - PROCESS-NAME,Surge%203,auto
  - PROCESS-NAME,ss-local,auto
  - PROCESS-NAME,privoxy,auto
  - PROCESS-NAME,trojan,auto
  - PROCESS-NAME,trojan-go,auto
  - PROCESS-NAME,naive,auto
  - PROCESS-NAME,Thunder,DIRECT
  - PROCESS-NAME,DownloadService,DIRECT
  - PROCESS-NAME,qBittorrent,DIRECT
  - PROCESS-NAME,Transmission,DIRECT
  - PROCESS-NAME,fdm,DIRECT
  - PROCESS-NAME,aria2c,DIRECT
  - PROCESS-NAME,Folx,DIRECT
  - PROCESS-NAME,NetTransport,DIRECT
  - PROCESS-NAME,uTorrent,DIRECT
  - PROCESS-NAME,WebTorrent,DIRECT
  - DOMAIN,clash.razord.top,auto
  - DOMAIN,yacd.haishan.me,DIRECT
  - RULE-SET,reject,REJECT
  - RULE-SET,icloud,DIRECT
  - RULE-SET,apple,DIRECT
  - RULE-SET,proxy,auto
  - RULE-SET,direct,DIRECT
  - RULE-SET,gfw,auto
  - RULE-SET,greatfire,auto
  - RULE-SET,cncidr,DIRECT
  - RULE-SET,lancidr,DIRECT
  - GEOIP,HK,DIRECT,no-resolve
  - GEOIP,CN,DIRECT,no-resolve
  - MATCH,auto

一访问 DIRECT的网站就会报all dns requests failed *********** context deadline exceeded.

**Comment by vernesong** [comment]
顾名思义，查询超时，nameserver改改
