### ISSUE TITLE
openclash无法正常关闭

### ISSUE THREAD

**Issue by wuchen4588** [vernesong/OpenClash#1274]
我家软路由关闭openclash时候卡在dnsmasp重启不动了，每次关闭都靠killall指令杀掉

time="2021-03-01T03:24:02Z" level=info msg="Start initial compatible provider 📲 电报消息"
time="2021-03-01T03:24:02Z" level=info msg="Start initial compatible provider 🚀 节点选择"
time="2021-03-01T03:24:02Z" level=info msg="Start initial compatible provider 🎯 全球直连"
time="2021-03-01T03:24:02Z" level=info msg="Start initial compatible provider 🎥 奈飞节点"
time="2021-03-01T03:24:02Z" level=info msg="Start initial compatible provider 📢 谷歌FCM"
time="2021-03-01T03:24:02Z" level=info msg="Start initial compatible provider 🎥 奈飞视频"
time="2021-03-01T03:24:02Z" level=info msg="Start initial compatible provider 🚀 手动切换"
time="2021-03-01T03:24:02Z" level=info msg="Start initial compatible provider 🇯🇵 日本节点"
time="2021-03-01T03:24:02Z" level=info msg="Start initial compatible provider 🇸🇬 狮城节点"
time="2021-03-01T03:24:02Z" level=info msg="Start initial compatible provider 🎮 游戏平台"
time="2021-03-01T03:24:02Z" level=info msg="Start initial compatible provider 🛑 广告拦截"
time="2021-03-01T03:24:02Z" level=info msg="Start initial compatible provider 🌍 国外媒体"
time="2021-03-01T03:24:02Z" level=info msg="Start initial compatible provider 📺 巴哈姆特"
time="2021-03-01T03:24:02Z" level=info msg="Start initial compatible provider 🎶 网易音乐"
time="2021-03-01T03:24:02Z" level=info msg="Start initial compatible provider 🍃 应用净化"
time="2021-03-01T03:24:02Z" level=info msg="Start initial compatible provider 🇰🇷 韩国节点"
time="2021-03-01T03:24:02Z" level=info msg="Start initial compatible provider 🇭🇰 香港节点"
time="2021-03-01T03:24:02Z" level=info msg="Start initial compatible provider 🍎 苹果服务"
time="2021-03-01T03:24:02Z" level=info msg="Start initial compatible provider 📺 哔哩哔哩"
time="2021-03-01T03:24:02Z" level=info msg="Start initial compatible provider 📹 油管视频"
time="2021-03-01T03:24:02Z" level=info msg="Start initial compatible provider Ⓜ️ 微软服务"
time="2021-03-01T03:24:02Z" level=info msg="Start initial compatible provider Ⓜ️ 微软云盘"
time="2021-03-01T03:24:02Z" level=info msg="Start initial compatible provider 🌏 国内媒体"
time="2021-03-01T03:24:02Z" level=info msg="Start initial compatible provider 🇺🇲 美国节点"
time="2021-03-01T03:24:02Z" level=info msg="Start initial compatible provider 🇨🇳 台湾节点"
time="2021-03-01T03:24:02Z" level=info msg="Start initial compatible provider 🐟 漏网之鱼"
time="2021-03-01T03:24:02Z" level=info msg="DNS server listening at: 127.0.0.1:7874"
2021-03-01 11:24:09 History:【CNIX.yaml】 Restore Successful
2021-03-01 11:23:40 Warning: OpenClash Start Successful, Please Note That Network May Abnormal With IPV6's DHCP Server
2021-03-11 02:02:10 Reload OpenClash Firewall Rules
time="2021-03-10T23:29:09Z" level=info msg="Start initial compatible provider 🚀 手动切换"
time="2021-03-10T23:29:09Z" level=info msg="Start initial compatible provider 🎶 网易音乐"
time="2021-03-10T23:29:09Z" level=info msg="Start initial compatible provider 🌍 国外媒体"
time="2021-03-10T23:29:09Z" level=info msg="Start initial compatible provider Ⓜ️ 微软服务"
time="2021-03-10T23:29:09Z" level=info msg="Start initial compatible provider 🇯🇵 日本节点"
time="2021-03-10T23:29:09Z" level=info msg="Start initial compatible provider 🎥 奈飞视频"
time="2021-03-10T23:29:09Z" level=info msg="Start initial compatible provider 🍎 苹果服务"
time="2021-03-10T23:29:09Z" level=info msg="Start initial compatible provider 📺 哔哩哔哩"
time="2021-03-10T23:29:09Z" level=info msg="Start initial compatible provider 🌏 国内媒体"
time="2021-03-10T23:29:09Z" level=info msg="Start initial compatible provider 🇺🇲 美国节点"
time="2021-03-10T23:29:09Z" level=info msg="Start initial compatible provider 🇸🇬 狮城节点"
time="2021-03-10T23:29:09Z" level=info msg="Start initial compatible provider 🇨🇳 台湾节点"
time="2021-03-10T23:29:09Z" level=info msg="Start initial compatible provider 🇭🇰 香港节点"
time="2021-03-10T23:29:09Z" level=info msg="Start initial compatible provider 🚀 节点选择"
time="2021-03-10T23:29:09Z" level=info msg="Start initial compatible provider 🎯 全球直连"
time="2021-03-10T23:29:09Z" level=info msg="Start initial compatible provider 📢 谷歌FCM"
time="2021-03-10T23:29:09Z" level=info msg="Start initial compatible provider 🍃 应用净化"
time="2021-03-10T23:29:09Z" level=info msg="Start initial compatible provider 📺 巴哈姆特"
time="2021-03-10T23:29:09Z" level=info msg="Start initial compatible provider 📹 油管视频"
time="2021-03-10T23:29:09Z" level=info msg="Start initial compatible provider 🎮 游戏平台"
time="2021-03-10T23:29:09Z" level=info msg="Start initial compatible provider 🛑 广告拦截"
time="2021-03-10T23:29:09Z" level=info msg="Start initial compatible provider Ⓜ️ 微软云盘"
time="2021-03-10T23:29:09Z" level=info msg="Start initial compatible provider 🇰🇷 韩国节点"
time="2021-03-10T23:29:09Z" level=info msg="Start initial compatible provider 🎥 奈飞节点"
time="2021-03-10T23:29:09Z" level=info msg="Start initial compatible provider 🐟 漏网之鱼"
time="2021-03-10T23:29:09Z" level=info msg="Start initial compatible provider 📲 电报消息"
time="2021-03-10T23:29:09Z" level=info msg="DNS server listening at: 127.0.0.1:7874"
2021-03-11 07:29:17 History:【CNIX.yaml】 Restore Successful
2021-03-11 07:28:48 Warning: OpenClash Start Successful, Please Note That Network May Abnormal With IPV6's DHCP Server
time="2021-03-10T23:30:21Z" level=info msg="Start initial compatible provider 🇺🇲 美国节点"
time="2021-03-10T23:30:21Z" level=info msg="Start initial compatible provider 📺 巴哈姆特"
time="2021-03-10T23:30:21Z" level=info msg="Start initial compatible provider 🇸🇬 狮城节点"
time="2021-03-10T23:30:21Z" level=info msg="Start initial compatible provider 🇨🇳 台湾节点"
time="2021-03-10T23:30:21Z" level=info msg="Start initial compatible provider 🎮 游戏平台"
time="2021-03-10T23:30:21Z" level=info msg="Start initial compatible provider 📢 谷歌FCM"
time="2021-03-10T23:30:21Z" level=info msg="Start initial compatible provider 🚀 节点选择"
time="2021-03-10T23:30:21Z" level=info msg="Start initial compatible provider 🎥 奈飞节点"
time="2021-03-10T23:30:21Z" level=info msg="Start initial compatible provider 🍃 应用净化"
time="2021-03-10T23:30:21Z" level=info msg="Start initial compatible provider 📺 哔哩哔哩"
time="2021-03-10T23:30:21Z" level=info msg="Start initial compatible provider 📹 油管视频"
time="2021-03-10T23:30:21Z" level=info msg="Start initial compatible provider 🍎 苹果服务"
time="2021-03-10T23:30:21Z" level=info msg="Start initial compatible provider 🛑 广告拦截"
time="2021-03-10T23:30:21Z" level=info msg="Start initial compatible provider 🎶 网易音乐"
time="2021-03-10T23:30:21Z" level=info msg="Start initial compatible provider 🌍 国外媒体"
time="2021-03-10T23:30:21Z" level=info msg="Start initial compatible provider 🚀 手动切换"
time="2021-03-10T23:30:21Z" level=info msg="Start initial compatible provider 🇰🇷 韩国节点"
time="2021-03-10T23:30:21Z" level=info msg="Start initial compatible provider 🇯🇵 日本节点"
time="2021-03-10T23:30:21Z" level=info msg="Start initial compatible provider 🇭🇰 香港节点"
time="2021-03-10T23:30:21Z" level=info msg="Start initial compatible provider 🎯 全球直连"
time="2021-03-10T23:30:21Z" level=info msg="Start initial compatible provider 🌏 国内媒体"
time="2021-03-10T23:30:21Z" level=info msg="Start initial compatible provider 📲 电报消息"
time="2021-03-10T23:30:21Z" level=info msg="Start initial compatible provider Ⓜ️ 微软服务"
time="2021-03-10T23:30:21Z" level=info msg="Start initial compatible provider Ⓜ️ 微软云盘"
time="2021-03-10T23:30:21Z" level=info msg="Start initial compatible provider 🎥 奈飞视频"
time="2021-03-10T23:30:21Z" level=info msg="Start initial compatible provider 🐟 漏网之鱼"
time="2021-03-10T23:30:21Z" level=info msg="DNS server listening at: 127.0.0.1:7874"
2021-03-11 07:30:30 History:【CNIX.yaml】 Restore Successful
2021-03-11 07:29:59 Warning: OpenClash Start Successful, Please Note That Network May Abnormal With IPV6's DHCP Server
time="2021-03-11T02:12:53Z" level=info msg="Start initial compatible provider 🌍 国外媒体"
time="2021-03-11T02:12:53Z" level=info msg="Start initial compatible provider 📲 电报消息"
time="2021-03-11T02:12:53Z" level=info msg="Start initial compatible provider 🎶 网易音乐"
time="2021-03-11T02:12:53Z" level=info msg="Start initial compatible provider 📺 哔哩哔哩"
time="2021-03-11T02:12:53Z" level=info msg="Start initial compatible provider 🛑 广告拦截"
time="2021-03-11T02:12:53Z" level=info msg="Start initial compatible provider 🍃 应用净化"
time="2021-03-11T02:12:53Z" level=info msg="Start initial compatible provider 🇨🇳 台湾节点"
time="2021-03-11T02:12:53Z" level=info msg="Start initial compatible provider 🚀 节点选择"
time="2021-03-11T02:12:53Z" level=info msg="Start initial compatible provider 🎥 奈飞视频"
time="2021-03-11T02:12:53Z" level=info msg="Start initial compatible provider 🇺🇲 美国节点"
time="2021-03-11T02:12:53Z" level=info msg="Start initial compatible provider 🇯🇵 日本节点"
time="2021-03-11T02:12:53Z" level=info msg="Start initial compatible provider 🎯 全球直连"
time="2021-03-11T02:12:53Z" level=info msg="Start initial compatible provider 🎥 奈飞节点"
time="2021-03-11T02:12:53Z" level=info msg="Start initial compatible provider Ⓜ️ 微软云盘"
time="2021-03-11T02:12:53Z" level=info msg="Start initial compatible provider 📺 巴哈姆特"
time="2021-03-11T02:12:53Z" level=info msg="Start initial compatible provider 🚀 手动切换"
time="2021-03-11T02:12:53Z" level=info msg="Start initial compatible provider 🇰🇷 韩国节点"
time="2021-03-11T02:12:53Z" level=info msg="Start initial compatible provider 🍎 苹果服务"
time="2021-03-11T02:12:53Z" level=info msg="Start initial compatible provider 🌏 国内媒体"
time="2021-03-11T02:12:53Z" level=info msg="Start initial compatible provider 🎮 游戏平台"
time="2021-03-11T02:12:53Z" level=info msg="Start initial compatible provider 📹 油管视频"
time="2021-03-11T02:12:53Z" level=info msg="Start initial compatible provider Ⓜ️ 微软服务"
time="2021-03-11T02:12:53Z" level=info msg="Start initial compatible provider 🇸🇬 狮城节点"
time="2021-03-11T02:12:53Z" level=info msg="Start initial compatible provider 🐟 漏网之鱼"
time="2021-03-11T02:12:53Z" level=info msg="Start initial compatible provider 🇭🇰 香港节点"
time="2021-03-11T02:12:53Z" level=info msg="Start initial compatible provider 📢 谷歌FCM"
time="2021-03-11T02:12:53Z" level=info msg="DNS server listening at: 127.0.0.1:7874"
2021-03-11 10:13:02 History:【CNIX.yaml】 Restore Successful
2021-03-11 10:12:32 Warning: OpenClash Start Successful, Please Note That Network May Abnormal With IPV6's DHCP Server
time="2021-03-11T02:14:17Z" level=info msg="Start initial compatible provider 🚀 手动切换"
time="2021-03-11T02:14:17Z" level=info msg="Start initial compatible provider 🇰🇷 韩国节点"
time="2021-03-11T02:14:17Z" level=info msg="Start initial compatible provider 🇺🇲 美国节点"
time="2021-03-11T02:14:17Z" level=info msg="Start initial compatible provider 🚀 节点选择"
time="2021-03-11T02:14:17Z" level=info msg="Start initial compatible provider 🎯 全球直连"
time="2021-03-11T02:14:17Z" level=info msg="Start initial compatible provider 🛑 广告拦截"
time="2021-03-11T02:14:17Z" level=info msg="Start initial compatible provider Ⓜ️ 微软云盘"
time="2021-03-11T02:14:17Z" level=info msg="Start initial compatible provider 📲 电报消息"
time="2021-03-11T02:14:17Z" level=info msg="Start initial compatible provider 🇯🇵 日本节点"
time="2021-03-11T02:14:17Z" level=info msg="Start initial compatible provider 🇸🇬 狮城节点"
time="2021-03-11T02:14:17Z" level=info msg="Start initial compatible provider 🇨🇳 台湾节点"
time="2021-03-11T02:14:17Z" level=info msg="Start initial compatible provider 🌏 国内媒体"
time="2021-03-11T02:14:17Z" level=info msg="Start initial compatible provider Ⓜ️ 微软服务"
time="2021-03-11T02:14:17Z" level=info msg="Start initial compatible provider 📺 巴哈姆特"
time="2021-03-11T02:14:17Z" level=info msg="Start initial compatible provider 📺 哔哩哔哩"
time="2021-03-11T02:14:17Z" level=info msg="Start initial compatible provider 🎶 网易音乐"
time="2021-03-11T02:14:17Z" level=info msg="Start initial compatible provider 🎮 游戏平台"
time="2021-03-11T02:14:17Z" level=info msg="Start initial compatible provider 🌍 国外媒体"
time="2021-03-11T02:14:17Z" level=info msg="Start initial compatible provider 🎥 奈飞节点"
time="2021-03-11T02:14:17Z" level=info msg="Start initial compatible provider 📹 油管视频"
time="2021-03-11T02:14:17Z" level=info msg="Start initial compatible provider 🍎 苹果服务"
time="2021-03-11T02:14:17Z" level=info msg="Start initial compatible provider 🎥 奈飞视频"
time="2021-03-11T02:14:17Z" level=info msg="Start initial compatible provider 🇭🇰 香港节点"
time="2021-03-11T02:14:17Z" level=info msg="Start initial compatible provider 📢 谷歌FCM"
time="2021-03-11T02:14:17Z" level=info msg="Start initial compatible provider 🐟 漏网之鱼"
time="2021-03-11T02:14:17Z" level=info msg="Start initial compatible provider 🍃 应用净化"
time="2021-03-11T02:14:17Z" level=info msg="DNS server listening at: 127.0.0.1:7874"
2021-03-11 10:14:24 History:【CNIX.yaml】 Restore Successful
2021-03-11 10:13:56 Warning: OpenClash Start Successful, Please Note That Network May Abnormal With IPV6's DHCP Server
这是我在openclash里的log日志文件，各位大佬看下

**Comment by BabXhwZUNBeTV** [comment]
全局设置 调试日志 生成一份调试日志 上传 看看
还有最好再上传一份 openwrt 的系统日志

**Comment by wuchen4588** [comment]
草了，今天把openwrt重装了。算了，下次出bug提供下
