### ISSUE TITLE
小米R3G 更新内核失败，手动上传无法识别！

### ISSUE THREAD

**Issue by JohyC** [vernesong/OpenClash#1280]
## 1.关于我要提交的问题

没有类似的issue

### (1) 具体问题

A：
小米r3g 安装 luci-app-openclash_0.42.03-beta_all后，更新内核失败，手动上传也无法识别；
![image](https://user-images.githubusercontent.com/38210128/110888396-0a9da980-8327-11eb-874e-fd1fc2384289.png)

TUN内核 下载链接不存在；
（ https://github.com/vernesong/OpenClash/releases/download/TUN-Premium/clash-linux-mipsle-softfloat-2021.02.21.gz ）

### (2) 路由器型号和固件版本

A：
型号：Xiaomi Mi Router 3G
固件版本：OpenWrt R21.2.1 / LuCI Master (git-21.035.34289-13f96d1)
内核版本：5.4.101
### (3) 相关日志

A:
[OpenClash-2021-3-12-12-6-22.log](https://github.com/vernesong/OpenClash/files/6127553/OpenClash-2021-3-12-12-6-22.log)

**Comment by JohyC** [comment]
依赖没安装好！

**Comment by kmahyyg** [comment]
自行编译的 lean 固件经查无此问题。日志显示为缺少 libcap 和 libcap-bin，请查看 issue #839 进行修复。

**Comment by JohyC** [comment]
> 自行编译的 lean 固件经查无此问题。日志显示为缺少 libcap 和 libcap-bin，请查看 issue #839 进行修复。

libcap 和 libcap-bin依赖有安装。
问题出在curl上。
更新 curl到7.75.0-1后解决此问题。。。（没弄明白是为啥！）
