### ISSUE TITLE
这仓库大小属实离谱，1G+的.git目录

### ISSUE THREAD

**Issue by li-xunhuan** [vernesong/OpenClash#1283]
<img width="564" alt="openclash" src="https://user-images.githubusercontent.com/10476982/111012658-bf8f9f00-83d7-11eb-85ca-6074919ee498.png">

**Comment by ttimasdf** [comment]
这也能提个issue？？

**Comment by kmahyyg** [comment]
我觉得按照 git 的设计逻辑，二进制的确不应该这么放，如果是因为 jsdelivr 无法加速的 gh release 的问题，完全可以单独开一个分支，然后二进制放那个分支，之后每次 force push 即可。在开发上更为合理的做法是放到 release 中存档，方便用户回退。

目前我的解决方法是自己 clone 下来之后拷贝过去，clone 的时候添加参数 `--depth 1` 即可。
