### ISSUE TITLE
Bug: 项目内置的 fallback-filter 影响 dl.google.com 域名解析

### ISSUE THREAD

**Issue by ttimasdf** [vernesong/OpenClash#1285]
Android SDK 下载依赖于 dl.google.com 的正常访问。通过国内 DNS 正常解析到的 IP 是可用的，但是添加到 fallback-filter 里后，google.com 所有子域名都解析到国外谷歌的IP上了，但是某些 Clash 规则组会分的比较细，为 dl.google.com 添加了直连规则。两个选项冲突了。

从我个人经验来看，把谷歌从 DNS fallback 黑名单里移除，不会影响被污染域名的解析，因为现在的污染方式基本都是将谷歌的IP和FB、Twitter换着用，因此一个 `geoip:true` 再随便加两条已知的黑名单IP足矣。

ref:
https://github.com/vernesong/OpenClash/blob/20dceb9504baf11debdd56d2ed15bbba07de5c1b/luci-app-openclash/root/etc/init.d/openclash#L167-L190

**Comment by LittleTurtle2333** [comment]
对，那天我也是因为这个头大，试了好多dns地址，dl.google.com好了之后，又有另一个地址不行了。shellclash没这种情况，不过似乎对openwrt兼容性不好

**Comment by vernesong** [comment]
如何修改合适

**Comment by kmahyyg** [comment]
个人觉得这是用户自己的规则配置问题，openclash 无需干预，去掉此条，让用户自行按需添加即可，无需过度包办。不同区域的 dl.google 访问速度不同，我这里就完全无法直连，所以海外相关的所有域名都是代理。

**Comment by ttimasdf** [comment]
> 个人觉得这是用户自己的规则配置问题，openclash 无需干预，去掉此条，让用户自行按需添加即可，无需过度包办。不同区域的 dl.google 访问速度不同，我这里就完全无法直连，所以海外相关的所有域名都是代理。

@kmahyyg 你那里解析出来的 IP 是多少？看看是不是国内的IP？注意下DNS配置和端口劫持的配置。如果透过代理访问DNS（DoT、DoH之类的），解析出的地址都是国外的，加上直连规则肯定就访问不了了。

```bash
➜  ~ dig +short +tcp dl.google.com @114.114.114.114
58.254.137.225
➜  ~ dig +short +tcp dl.google.com @1.1.1.1
216.58.195.78
➜  ~ curl -v ip-api.com/58.254.137.225
*   Trying 208.95.112.1...
* TCP_NODELAY set
* Connected to ip-api.com (208.95.112.1) port 80 (#0)
> GET /58.254.137.225 HTTP/1.1
> Host: ip-api.com
> User-Agent: curl/7.58.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Mon, 15 Mar 2021 06:03:03 GMT
< Content-Type: text/plain; charset=utf-8
< Content-Length: 1205
< Access-Control-Allow-Origin: *
< X-Ttl: 60
< X-Rl: 44
<
{
  "status"       : "success",
  "continent"    : "Asia",
  "continentCode": "AS",
  "country"      : "China",
  "countryCode"  : "CN",
  "region"       : "GD",
  "regionName"   : "Guangdong",
  "city"         : "Guangzhou",
  "district"     : "Yuexiu Qu",
  "zip"          : "",
  "lat"          : 23.1277,
  "lon"          : 113.269,
  "timezone"     : "Asia/Shanghai",
  "offset"       : 28800,
  "currency"     : "CNY",
  "isp"          : "CNC Group CHINA169 Guangdong Province Network",
  "org"          : "",
  "as"           : "AS136958 China Unicom Guangdong IP network",
  "asname"       : "UNICOM-GuangZhou-IDC",
  "mobile"       : false,
  "proxy"        : false,
  "hosting"      : false,
  "query"        : "58.254.137.225"
}
* Connection #0 to host ip-api.com left intact
➜  ~ curl ip-api.com/216.58.195.78
{
  "status"       : "success",
  "continent"    : "North America",
  "continentCode": "NA",
  "country"      : "United States",
  "countryCode"  : "US",
  "region"       : "UT",
  "regionName"   : "Utah",
  "city"         : "Bluffdale",
  "district"     : "",
  "zip"          : "84065",
  "lat"          : 40.4953,
  "lon"          : -111.9439,
  "timezone"     : "America/Denver",
  "offset"       : -21600,
  "currency"     : "USD",
  "isp"          : "Google LLC",
  "org"          : "Google LLC",
  "as"           : "AS15169 Google LLC",
  "asname"       : "GOOGLE",
  "mobile"       : false,
  "proxy"        : false,
  "hosting"      : true,
  "query"        : "216.58.195.78"
}
```

**Comment by ttimasdf** [comment]
> 如何修改合适

1. 删掉 `- '+.google.com'` 即可解决。
2. 修改 `geoip: true` （可选）


如果只是针对墙的DNS污染的话，只保留一个 `geoip: true` 应该就足够了，`domain` 和 `ipcidr` 都是额外的黑名单配置，我个人使用体验来看，不加也没啥区别。 [Clash Wiki](https://github.com/Dreamacro/clash/wiki/configuration) 里的参考配置也是这么写的。对于一些 CDN 应该也有加速作用，因为对国内DNS返回的解析结果宽容度更高了。

**Comment by eggydutch** [comment]
> > 如何修改合适
> 
> 1. 删掉 `- '+.google.com'` 即可解决。
> 2. 修改 `geoip: true` （可选）
> 
> 如果只是针对墙的DNS污染的话，只保留一个 `geoip: true` 应该就足够了，`domain` 和 `ipcidr` 都是额外的黑名单配置，我个人使用体验来看，不加也没啥区别。 [Clash Wiki](https://github.com/Dreamacro/clash/wiki/configuration) 里的参考配置也是这么写的。对于一些 CDN 应该也有加速作用，因为对国内DNS返回的解析结果宽容度更高了。

最近两个月如果dns配置geoip: true的话，会出现很多国外网站dns无法解析的现象，自建的trojan节点也无法ping通及使用，这在之前是一直正常的。

现在需要把geoip: 改为false才可以正常解析及使用自检节点，这会是openclash的bug吗？

**Comment by eggydutch** [comment]
> > > 如何修改合适
> > 
> > 
> > 
> > 1. 删掉 `- '+.google.com'` 即可解决。
> > 2. 修改 `geoip: true` （可选）
> > 
> > 如果只是针对墙的DNS污染的话，只保留一个 `geoip: true` 应该就足够了，`domain` 和 `ipcidr` 都是额外的黑名单配置，我个人使用体验来看，不加也没啥区别。 [Clash Wiki](https://github.com/Dreamacro/clash/wiki/configuration) 里的参考配置也是这么写的。对于一些 CDN 应该也有加速作用，因为对国内DNS返回的解析结果宽容度更高了。
> 
> 最近两个月如果dns配置geoip: true的话，会出现很多国外网站dns无法解析的现象，自建的trojan节点也无法ping通及使用，这在之前是一直正常的。
> 
> 现在需要把geoip: 改为false才可以正常解析及使用自检节点，这会是openclash的bug吗？

把geoip的地址库更换成下面的Hackl0us的源后，dns改成geoip: true就正常了，看来是默认的ip库出了问题:

https://github.com/Hackl0us/GeoIP2-CN
