### ISSUE TITLE
设置好旁路由后，在clash监控窗口没有发现访问连接。

### ISSUE THREAD

**Issue by hjianhao** [vernesong/OpenClash#1288]
我用群晖NAS访问Tidal网站

我的Openwrt旁路由IP是192.168.1.2
我的主路由是192.168.1.1，在DHCP设置了指向旁路由。
![image](https://user-images.githubusercontent.com/6102007/111026992-6734bd80-8428-11eb-8176-005a17cc7c3f.png)

我的群晖使用静态IP，网关和DNS指向主路由
![image](https://user-images.githubusercontent.com/6102007/111027022-964b2f00-8428-11eb-9295-ff83f23b382f.png)

然后群晖访问tidal播放音乐时，在clash界面根本没有访问tidal连接
![image](https://user-images.githubusercontent.com/6102007/111027064-d4e0e980-8428-11eb-9421-3f1a8244d9f3.png)

我用相同的clash yaml配置在windows访问tidal时，可以看到连接
![image](https://user-images.githubusercontent.com/6102007/111027100-1d000c00-8429-11eb-951b-c128ec2b546f.png)

**Comment by vernesong** [comment]
群辉网关dns指向旁路由
