### ISSUE TITLE
我想在订阅的配置文件里加入一个自己的节点该怎么做？

### ISSUE THREAD

**Issue by xx791117** [vernesong/OpenClash#1290]
我想在订阅的配置文件里加入一个自己的节点该怎么做？我买了一个机场用了机场的订阅配置文件，我还有一个自己搭的服务器，我想在订阅更新时把我自己的节点也插入配置文件里，除了直接改配置文件，还有其他的简单操作方法吗？谢谢！

**Comment by vernesong** [comment]
服务器与策略组页面，先读取你的订阅文件，然后加上自定义节点后，勾选保留配置，再应用配置

**Comment by HenryLuoCN** [comment]
然而我实验了很多次，也更新到最新版本，在openclash运行的配置文件中始终找不到我自定义的规则，语法应该没错。
   DOMAIN-SUFFIX,aaaa.com,DIRECT

**Comment by HenryLuoCN** [comment]
头部和尾部两个框都测试过了，也重启了，都不生效，望大佬指点迷津。

**Comment by vernesong** [comment]
前面有横杠

**Comment by OoNanGeOo** [comment]
> 然而我实验了很多次，也更新到最新版本，在openclash运行的配置文件中始终找不到我自定义的规则，语法应该没错。
> DOMAIN-SUFFIX,aaaa.com,DIRECT
- DOMAIN-SUFFIX,aaaa.com,DIRECT

这个才是正确的

**Comment by calmcatcc** [comment]
> 

同问，请问解决了吗，求分享方法
