### ISSUE TITLE
全局设置页面无法打开

### ISSUE THREAD

**Issue by zhuohoudeputao** [vernesong/OpenClash#1291]
/usr/lib/lua/luci/dispatcher.lua:448: Failed to execute cbi dispatcher target for entry '/admin/services/openclash/settings'.
The called action terminated with an exception:
/usr/lib/lua/luci/model/cbi/openclash/settings.lua:298: attempt to call field '?' (a nil value)
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:448: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:195: in function </usr/lib/lua/luci/dispatcher.lua:194>

**Comment by kmahyyg** [comment]
可以尝试删除 openclash 和   /etc/config/openclash    /etc/openclash 后重新安装。

**Comment by zhuohoudeputao** [comment]
路由器版本 OpenWrt Barrier Breaker 14.07

包列表
Remove | base-files | 156-r42625
Remove | bash | 4.2-5
Remove | busybox | 1.22.1-2
Remove | ca-certificates | 20141019
Remove | coreutils | 8.16-1
Remove | coreutils-nohup | 8.16-1
Remove | curl | 7.38.0-1
Remove | dnsmasq | 2.71-4
Remove | dnsmasq-full | 2.71-5
Remove | dropbear | 2014.63-2
Remove | firewall | 2014-09-19
Remove | fstools | 2014-06-22-e0430f5c62f367e5a8e02755412977b02c3fc45e
Remove | hostapd-common | 2014-06-03-1
Remove | ip-full | 3.15.0-1
Remove | ip6tables | 1.4.21-1
Remove | ipset | 6.20.1-1
Remove | iptables | 1.4.21-1
Remove | iptables-mod-extra | 1.4.21-1
Remove | iptables-mod-tproxy | 1.4.21-1
Remove | iw | 3.15-1
Remove | jshn | 2014-08-04-dffbc09baf71b294185a36048166d00066d433b5
Remove | jsonfilter | 2014-06-19-cdc760c58077f44fc40adbbe41e1556a67c1b9a9
Remove | kernel | 3.10.49-1-0114c71ed85677c9c1e4911437af4743
Remove | kmod-ath | 3.10.49+2014-05-22-1
Remove | kmod-ath9k | 3.10.49+2014-05-22-1
Remove | kmod-ath9k-common | 3.10.49+2014-05-22-1
Remove | kmod-cfg80211 | 3.10.49+2014-05-22-1
Remove | kmod-crypto-aes | 3.10.49-1
Remove | kmod-crypto-arc4 | 3.10.49-1
Remove | kmod-crypto-core | 3.10.49-1
Remove | kmod-gpio-button-hotplug | 3.10.49-1
Remove | kmod-ip6tables | 3.10.49-1
Remove | kmod-ipt-conntrack | 3.10.49-1
Remove | kmod-ipt-core | 3.10.49-1
Remove | kmod-ipt-extra | 3.10.49-1
Remove | kmod-ipt-ipset | 3.10.49+6.20.1-1
Remove | kmod-ipt-nat | 3.10.49-1
Remove | kmod-ipt-nathelper | 3.10.49-1
Remove | kmod-ipt-tproxy | 3.10.49-1
Remove | kmod-ipv6 | 3.10.49-1
Remove | kmod-lib-crc-ccitt | 3.10.49-1
Remove | kmod-mac80211 | 3.10.49+2014-05-22-1
Remove | kmod-nfnetlink | 3.10.49-1
Remove | kmod-ppp | 3.10.49-1
Remove | kmod-pppoe | 3.10.49-1
Remove | kmod-pppox | 3.10.49-1
Remove | kmod-slhc | 3.10.49-1
Remove | kmod-tun | 3.10.49-1
Remove | libblobmsg-json | 2014-08-04-dffbc09baf71b294185a36048166d00066d433b5
Remove | libc | 0.9.33.2-1
Remove | libcap | 2.24-1
Remove | libcurl | 7.38.0-1
Remove | libgcc | 4.8-linaro-1
Remove | libgmp | 6.0.0-1
Remove | libip4tc | 1.4.21-1
Remove | libip6tc | 1.4.21-1
Remove | libiwinfo | 51
Remove | libiwinfo-lua | 51
Remove | libjson-c | 0.11-2
Remove | libjson-script | 2014-08-04-dffbc09baf71b294185a36048166d00066d433b5
Remove | liblua | 5.1.5-1
Remove | libmnl | 1.0.3-1
Remove | libncurses | 5.9-1
Remove | libnettle | 2.7.1-1
Remove | libnl-tiny | 0.1-3
Remove | libpolarssl | 1.3.9-2
Remove | libpthread | 0.9.33.2-1
Remove | libreadline | 6.2-1
Remove | librt | 0.9.33.2-1
Remove | libruby | 1.9.3-p545-1
Remove | libubox | 2014-08-04-dffbc09baf71b294185a36048166d00066d433b5
Remove | libubus | 2014-09-17-4c4f35cf2230d70b9ddd87638ca911e8a563f2f3
Remove | libubus-lua | 2014-09-17-4c4f35cf2230d70b9ddd87638ca911e8a563f2f3
Remove | libuci | 2014-04-11.1-1
Remove | libuci-lua | 2014-04-11.1-1
Remove | libxtables | 1.4.21-1
Remove | lua | 5.1.5-1
Remove | luci | 0.12+svn-r10530-1
Remove | luci-app-firewall | 0.12+svn-r10530-1
Remove | luci-app-openclash | 0.42.03-beta
Remove | luci-base | 0.12+svn-r10530-1
Remove | luci-lib-nixio | 0.12+svn-r10530-1
Remove | luci-mod-admin-full | 0.12+svn-r10530-1
Remove | luci-proto-ppp | 0.12+svn-r10530-1
Remove | luci-theme-bootstrap | 0.12+svn-r10530-1
Remove | mtd | 20
Remove | netifd | 2014-09-08-46c569989f984226916fec28dd8ef152a664043e
Remove | odhcp6c | 2014-08-25-0300fe7589a1701361735ac068e4b57bb1a1896f
Remove | odhcpd | 2014-08-23-24452e1e3e9adfd9d8e183db1aa589f77727f5a7
Remove | opkg | 9c97d5ecd795709c8584e972bfdf3aee3a5b846d-7
Remove | ppp | 2.4.7-2
Remove | ppp-mod-pppoe | 2.4.7-2
Remove | procd | 2014-09-15-c1a558f7d0c1e6c1ffa5a47d557a7b45205eef1d
Remove | ruby | 1.9.3-p545-1
Remove | ruby-yaml | 1.9.3-p545-1
Remove | scutclient | 1.6-0
Remove | swconfig | 10
Remove | terminfo | 5.9-1
Remove | uboot-envtools | 2014.04-4
Remove | ubox | 2014-09-16-5c45b560bc8c9e13682269ed963a8a4a65959518
Remove | ubus | 2014-09-17-4c4f35cf2230d70b9ddd87638ca911e8a563f2f3
Remove | ubusd | 2014-09-17-4c4f35cf2230d70b9ddd87638ca911e8a563f2f3
Remove | uci | 2014-04-11.1-1
Remove | uhttpd | 2014-08-25-dabd7dea6445aaa0e5b8d9add1872fa7393b3a85
Remove | uhttpd-mod-ubus | 2014-08-25-dabd7dea6445aaa0e5b8d9add1872fa7393b3a85
Remove | wpad-mini | 2014-06-03-1

**Comment by zhuohoudeputao** [comment]
尝试#536的方法解决，但是没找到对应版本的libreadline，架构是ar71xx，目前libreadline版本是6.2-1

**Comment by zhuohoudeputao** [comment]
> 可以尝试删除 openclash 和 /etc/config/openclash /etc/openclash 后重新安装。

谢谢，尝试了重新安装，仍然是这样的。

**Comment by vernesong** [comment]
固件太老了，luci的库不全
