### ISSUE TITLE
 mipsel 处理器架构下，更新大陆白名单后，网站访问检查，全都连接超时！！已经测试三四台，确定会连接超时，请名位注意！！

### ISSUE THREAD

**Issue by win28703** [vernesong/OpenClash#1292]
V0.42.03 mipsel 处理器架构下，更新大陆白名单后，网站访问检查，全都连接超时！！已经测试三四台，确定会连接超时，请名位注意！！
先不要作 更新大陆白名单！！

**Comment by gkl1368** [comment]
amd64 也会 而且是

**Comment by gkl1368** [comment]
> V0.42.03 mipsel 处理器架构下，更新大陆白名单后，网站访问检查，全都连接超时！！已经测试三四台，确定会连接超时，请名位注意！！
> 先不要作 更新大陆白名单！！

amd64 也会

**Comment by iPixelOldC** [comment]
瞅瞅日志里是不是clash启动失败（ssh手动连进去打./clash --version啥的也是无响应卡在那里？），如果你的问题和我一样，那就很好办了。作者压缩的clash给压缩坏了，自己去clash原作者那里下载一个，改名替换就行

**Comment by caliban511** [comment]
我也遇到过，自动更新经常出错，但每次手动更新的话都能成功。
