### ISSUE TITLE
希望能减小下Git的体积

### ISSUE THREAD

**Issue by ssrkaze** [vernesong/OpenClash#1295]
目前采用git clone下载下来的整个项目有2.18 GB，其中.git文件夹占了2.07 GB，能否考虑下减小体积？

**Comment by actg** [comment]
应该是之前的commit里面添加了太多二进制文件导致.git非常大，很难想象一个只有不到几兆的ipk包需要几个GB的编译环境

**Comment by zgc** [comment]
git clone --depth 1 -b master https://github.com/vernesong/OpenClash.git

**Comment by actg** [comment]
README里面提到的编译方法里面那步可以改成git pull --depth 1 origin master效果更好

**Comment by zcq100** [comment]
git clone -b master --depth 1 https://github.com/vernesong/OpenClash.git package/luci-app-openclash
