### ISSUE TITLE
更新后 游戏模式不可用

### ISSUE THREAD

**Issue by JoonSumisu** [vernesong/OpenClash#1296]
已选择编译版本 | linux-armv7 | 上次检查更新时间 | 2021-03-17 20:37:56
-- | -- | -- | --
处理器架构（OS） | arm_cortex-a7_neon-vfpv4 | 处理器架构（OPKG） | arm_cortex-a7_neon-vfpv4

 在更新了软件跟 两个内核后

[dev] 当前内核版本 | v1.4.2-1-g0976d27
[Game] 当前内核版本 | 20210310

game模式无法启动openclash，换成普通模式就可以正常启动

日志如下，抱歉新手学艺不精，没动怎么做好

2021-03-17 20:35:16 Error: Get General 'redir-port' Option Error, OpenClash Can Not Start With Raw Config File
2021-03-17 20:36:17 Warning: Multiple Restart Scripts Running, Exit...
2021-03-17 20:35:16 Error: Get DNS 'enhanced-mode' Option Error, OpenClash Can Not Start With Raw Config File
2021-03-17 20:35:16 Error: Get DNS 'listen' Option Error, OpenClash Can Not Start With Raw Config File
2021-03-17 20:35:16 Error: OpenClash Can Not Start, Try Use Raw Config Restart Again
	github.com/Dreamacro/clash/main.go:98 +0x370
main.main()
	github.com/Dreamacro/clash/hub/hub.go:48 +0xbc
github.com/Dreamacro/clash/hub.Parse(0x0, 0x0, 0x0, 0x6, 0x964c38)
	github.com/Dreamacro/clash/hub/executor/executor.go:74 +0x90
github.com/Dreamacro/clash/hub/executor.ApplyConfig(0x28ebac0, 0x5e5001)
	github.com/Dreamacro/clash/hub/executor/executor.go:210 +0x178
github.com/Dreamacro/clash/hub/executor.updateGeneral(0x289a070, 0x1)
	github.com/Dreamacro/clash/proxy/listener.go:311 +0x244
github.com/Dreamacro/clash/proxy.ReCreateTun(0x1, 0x282e3e0, 0xc, 0x282e400, 0xa, 0x0, 0x0)
	github.com/Dreamacro/clash/proxy/tun/tundns.go:263 +0x168
github.com/Dreamacro/clash/proxy/tun.(*tunAdapter).ReCreateDNSServer(0x2a6dde0, 0x291ceb0, 0x2a6dcb0, 0x282e400, 0xa, 0x0, 0x0)
	github.com/Dreamacro/clash/proxy/tun/tundns.go:175 +0x2f0
github.com/Dreamacro/clash/proxy/tun.CreateDNSServer(0x289e380, 0x291ceb0, 0x2a6dcb0, 0x2a94610, 0x10, 0x10, 0x35, 0x1, 0x0, 0x0, ...)
	gvisor.dev/gvisor@v0.0.0-00010101000000-000000000000/pkg/tcpip/adapters/gonet/gonet.go:70 +0x44
gvisor.dev/gvisor/pkg/tcpip/adapters/gonet.ListenTCP(0x289e380, 0x1, 0x0, 0x0, 0x35, 0x800, 0x0, 0x0, 0x0)
	gvisor.dev/gvisor@v0.0.0-00010101000000-000000000000/pkg/tcpip/stack/stack.go:861 +0x68
gvisor.dev/gvisor/pkg/tcpip/stack.(*Stack).NewEndpoint(0x289e380, 0x6, 0x800, 0x2a6f1e0, 0x0, 0x0, 0x2824bd0, 0x5e5448)
	gvisor.dev/gvisor@v0.0.0-00010101000000-000000000000/pkg/tcpip/transport/tcp/protocol.go:165 +0x30
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*protocol).NewEndpoint(0x2944270, 0x800, 0x2a6f1e0, 0x291d248, 0x53ac01, 0x2a6f101, 0x2a6f1e0)
	gvisor.dev/gvisor@v0.0.0-00010101000000-000000000000/pkg/tcpip/transport/tcp/endpoint.go:890 +0x1d8
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.newEndpoint(0x289e380, 0x800, 0x2a6f1e0, 0x284a480)
	gvisor.dev/gvisor@v0.0.0-00010101000000-000000000000/pkg/tcpip/socketops.go:607 +0x17c
gvisor.dev/gvisor/pkg/tcpip.(*SocketOptions).SetSendBufferSize(0x28ee9e8, 0x100000, 0x0, 0x0)
	runtime/internal/atomic/asm_arm.s:278 +0x14
runtime/internal/atomic.Store64(0x28eea54, 0x100000, 0x0)
	runtime/internal/atomic/unaligned.go:8 +0x24
runtime/internal/atomic.panicUnaligned()
goroutine 1 [running]:

panic: unaligned 64-bit atomic operation

**Comment by vernesong** [comment]
暂时用tun内核吧，等作者修复

**Comment by JoonSumisu** [comment]
感谢

**Comment by gui-li** [comment]
同样遇到该情况，请问修复了吗？ @vernesong
