### ISSUE TITLE
重启后能否自动选择之前的节点

### ISSUE THREAD

**Issue by ttyycool** [vernesong/OpenClash#13]
查询日志发现自动更新geoip后会进行一次重启，这样手动选择的节点就会被重置，能否增加一个类似win版本的自动选择功能呢？

**Comment by vernesong** [comment]
在路由端还没有找到好的方法读取当前配置，可能要等clash提供接口才行

**Comment by cjjdaq** [comment]
要是webui能对配置文件直接进行修改就好了

**Comment by zhfish** [comment]
clash有接口啊
https://clash.gitbook.io/doc/restful-api

**Comment by vernesong** [comment]
> clash有接口啊
> https://clash.gitbook.io/doc/restful-api

可以用lua配合xhr，暂未尝试

**Comment by asaketsu** [comment]
> cfw可以在更新订阅后可以保留规则配置选择，希望openclash也可以提供这个，不然每次都要重新选择节点

这个很重要

**Comment by thank243** [comment]
> cfw可以在更新订阅后可以保留规则配置选择，希望openclash也可以提供这个，不然每次都要重新选择节点

这个感觉是刚需。不然默认others都走proxy。如果有bt，机场直接炸了。

**Comment by bigbighill** [comment]
+1

**Comment by HeaIer** [comment]
重启后节点仍然被重置
