### ISSUE TITLE
为啥这里设好后一段时间 就会变成自动选择，固定不了

### ISSUE THREAD

**Issue by mmeiwenlong** [vernesong/OpenClash#130]
![photo_2020-02-05_16-25-37](https://user-images.githubusercontent.com/44661424/73824240-c4793b00-4834-11ea-8e59-d496222fa47b.jpg)
如图，我设为手动。但一会就自动跑回自动选择了。啥原因的

**Comment by IOQWE** [comment]
我也是，看运行日志不知为何会不断重启，然后重启后自动跳转第一个节点
<img width="906" alt="vivaldi_ksmkPmW4nZ" src="https://user-images.githubusercontent.com/60723549/73908480-c69ad280-48e4-11ea-87a9-959a96f0bfe5.png">

**Comment by vernesong** [comment]
tun模式还不稳定，如果频繁重启建议更换模式。
下个版本会加入保留节点配置重启

**Comment by TheAutomatic** [comment]
fake-ip模式，有时候也会遇到openclash自动重启，重启后就又恢复成自动选择了。用的最新的v0.36.7-beta
