### ISSUE TITLE
使用openclash无法观看学而思网课直播！

### ISSUE THREAD

**Issue by gcl52** [vernesong/OpenClash#1302]
openclash未fake-ip增强模式，无法观看学而思网课直播，回放可以看，请问这是怎么回事啊？

**Comment by Leo-Mu** [comment]
建议把所有可能的模式组合都试试看，搞明白哪些模式可以使用哪些模式不能使用。如果还有问题再按照 issue 规范注明 log 信息来问。

**Comment by caliban511** [comment]
加入白名单试试？
