### ISSUE TITLE
最新的openclash是否会严重影响网速？

### ISSUE THREAD

**Issue by smallst** [vernesong/OpenClash#1304]
目前在不开 openclash 的情况下用 speedtest.cn 测速得到的实时网速大约是 60m/s
开了 fake-ip 模式后同样测速得到的实时网速只有 1m/s
而开  redir-host 模式的话同样测速得到的结果大约是 0.2m/s

这有点过于不正常了。 印象中之前开 fake-ip 测速的结果和不开 openclash 的结果是比较接近的

**Comment by caliban511** [comment]
先手动加白名单试试？看看是不是不小心走了流量？

**Comment by smallst** [comment]
@caliban511 没有效果。。同时我也是体验到其他网站有速度差异才使用 speedtest.cn 进行测速的 :joy: 感到迷惑，要么我先回退几个版本测试一下

**Comment by smallst** [comment]
嗯。。更奇怪的是我最后把openclash关掉再重启了下路由器再启动就好了……orz
