### ISSUE TITLE
通过Dashboard 控制面板访问无问题，而使用yacd面板则存在问题

### ISSUE THREAD

**Issue by matthuo333** [vernesong/OpenClash#1307]
经由VPN方式远程访问到openclash集成的控制面板， 在输入VPN中的对应IP后，yacd面板提示未授权，而对于dashboard则无问题。

客户端版本： v0.40.7-beta

**Comment by irrocu** [comment]
同样的问题，Yacd面板点开后一片空白
![Snipaste_2021-03-23_14-47-35](https://user-images.githubusercontent.com/66506186/112105129-ff7c3080-8be6-11eb-90f1-98456d2bb186.jpg)

**Comment by cielpy** [comment]
v0.40.7-beta 之后已经有 20 多个版本发布了，可以更新到最新试一下？ @matthuo333 

> 同样的问题，Yacd面板点开后一片空白
> ![Snipaste_2021-03-23_14-47-35](https://user-images.githubusercontent.com/66506186/112105129-ff7c3080-8be6-11eb-90f1-98456d2bb186.jpg)

可以看一下控制台有什么报错 @irrocu
