### ISSUE TITLE
规则设置 - 自定义规则无效

### ISSUE THREAD

**Issue by getjake** [vernesong/OpenClash#1308]
version: v1.4.2-1-g0976d27

问题描述： 设置部分 IP-CIDR 直连，但是仍然会通过机场配置中的  - * 漏网之鱼 * 来通过代理链接

**Comment by vernesong** [comment]
看下运行配置里面是不是正常写入了自定义规则

**Comment by getjake** [comment]
<img width="953" alt="image" src="https://user-images.githubusercontent.com/54499510/112396529-42e7b380-8d3b-11eb-88e8-87c7af69f525.png">

在调试日子里能找到，但是在 dashboard 上面，并没有找到自定义规则。

**Comment by getjake** [comment]
`- IP-CIDR,x.x.x.x/32,🎯 全球直连,no-resolve`
用这种方式写就没问题了

**Comment by HenryLuoCN** [comment]
不能这样写？
-  DOMAIN-SUFFIX,cdn-apple.com,DIRECT
