### ISSUE TITLE
能用正则表达式对对订阅的节点进行自动挑选吗

### ISSUE THREAD

**Issue by irrocu** [vernesong/OpenClash#1309]
订阅的yaml文件策略组不符合我的要求，
手工修改不难，
但是每次节点更新变化了又得手工修改，很麻烦。

openclash能否支持[subconvert](https://github.com/tindy2013/subconverter)的功能呢，
能自动筛选节点组成新的策略组呢。

盼复。

**Comment by vernesong** [comment]
服务器与策略组页面，读取你的配置文件后按需修改，勾选保留配置，以后只会更新节点
