### ISSUE TITLE
关于规则、规则集策略的疑问

### ISSUE THREAD

**Issue by hayden-yin** [vernesong/OpenClash#1313]
准备更新软路由，从LEDE搬迁到openwrt，v2ray客户端选择了openclash。建了个学习用的服务器，关闭“一键生成配置文件”然后折腾了两天，简单的规则集策略能运行起来了。然后发现在设置的时候有些容易迷惑的地方，现在总结下来求证。
1、全局设置 -》 规则设置 -》 第三方规则：
    这一个选项似乎在“运行配置”文件里对应的是不是下面几条？
    - RULE-SET,Unbreak,DIRECT
    - RULE-SET,Streaming,proxy
    - RULE-SET,StreamingSE,DIRECT
    - RULE-SET,Global,proxy
    - RULE-SET,China,DIRECT
    勾选和不勾选这几条都没有变化。请问这个选项的作用是不是仅仅在于屏蔽掉了我自建的规则文件和对应的策略条目？
2、规则集与策略组管理 -》 第三方规则集与策略组管理：
    这里面能看到的初始的几个规则集，和上一个问题里的几个规则集是重复的，不过就是有了中文名字。我还可以为他们设置策略，这在配置文件里可以看出来，比如：
    - RULE-SET,国内域名白名单,DIRECT
    如果在优先的匹配顺序下可以覆盖上一个问题里的对应规则策略。如果没有反复对比的话还真没发现这之间的逻辑。
    这里的重点应该是可以选择自定义规则集，摸索下来应该是可以在规则集文件夹列自建规则集文件，但是语法格式必须包含“behavior”项目，这样就可以自建规则文件了。
3、上面提到的三个规则集策略的优先级：
         全局设置 -》 规则设置 -》 自定义规则
         全局设置 -》 规则设置 -》 第三方规则
         规则集与策略组管理 -》 第三方规则集与策略组管理 -》 自定义规则集
总体上吧，感觉规则集策略的设置方面多处设置项之间的关系还是不够清晰，翻看文档也没有一个整体性的逻辑描述。希望能在这里得到解惑，谢谢！！！

**Comment by super27035** [comment]
最好把你的“高级设置-调试日志“ 删掉私隐信息贴出来，这样才能帮你。

**Comment by hayden-yin** [comment]
> 最好把你的“高级设置-调试日志“ 删掉私隐信息贴出来，这样才能帮你。
谢谢。目前呢问题已经都有解决了，就是对于我们在设置中的规则、对应策略的相关项目，系统的处理方式。以及整个系统对于所有规则（第三方规则集、第三方规则、自定义规则集。。。）的互相逻辑。个人感觉通过设置界面进行管理的层次感不是很清晰，所以想找人讨论下

**Comment by cls1997** [comment]
同问。十分疑惑为何要将dl.google.com移除，chromecast激活需要连接该地址
