### ISSUE TITLE
关于fake ip的一些问题 ，希望能帮帮孩子。

### ISSUE THREAD

**Issue by lnaxk** [vernesong/OpenClash#1314]
> 最开始是用fakeip的tun混合模式，但是代理udp总有点断流，就是玩外网的游戏刚开始连接正常，后来就连接失败，国内游戏没有此问题，如飞车 、王者、吃鸡延迟都正常无连接失败情况，然后有天我突然换到了fakeip 增强模式下（节点没有变化，同一个节点），这个模式下外网游戏正常无断流和连接失败的情况，但是有个问题代理不了自身流量，截图放在下面。所以可能是固件的问题嘛，编译过自己的固件和拿别人估计，估计安装上openclash，但是无疑例外全是tcp io超时........（脑壳疼）。

       下图第一个为fakeip增强模式，很长时间都没有响应，第二个为tun模式无延迟直接返回。
![微信截图_20210326163111](https://user-images.githubusercontent.com/58036663/112604295-ee365c80-8e50-11eb-8b22-468d96470828.png)
      下面为日志和配置清单。

            主机型号: Intel(R) Celeron(R) CPU 3965U @ 2.20GHz : 1 Core 2 Thread
            固件版本: OpenWrt 19.07-SNAPSHOT r11439-cc0e8e1c06
            LuCI版本: git-5f7cb03-1
            内核版本: 4.14.221
            处理器架构: x86_64
            
            #此项在使用Tun模式时应为ACCEPT
            防火墙转发: ACCEPT
            
            #此项有值时建议到网络-接口-lan的设置中禁用IPV6的DHCP
            IPV6-DHCP: 
            
            #此项结果应仅有配置文件的DNS监听地址
            Dnsmasq转发设置: 127.0.0.1#7874
            
            #===================== 依赖检查 =====================#
            
            dnsmasq-full: 已安装
            coreutils: 已安装
            coreutils-nohup: 已安装
            bash: 已安装
            curl: 已安装
            jsonfilter: 已安装
            ca-certificates: 已安装
            ipset: 已安装
            ip-full: 已安装
            iptables-mod-tproxy: 已安装
            kmod-ipt-tproxy: 已安装
            iptables-mod-extra: 已安装
            kmod-ipt-extra: 已安装
            libcap: 已安装
            libcap-bin: 已安装
            ruby: 已安装
            ruby-yaml: 已安装
            ruby-psych: 已安装
            ruby-pstore: 已安装
            ruby-dbm: 已安装
            kmod-tun(TUN模式): 已安装
            luci-compat(Luci-19.07): 已安装
            
            #===================== 内核检查 =====================#
            
            运行状态: 运行中
            进程pid: 12617
            运行权限: 12617: cap_dac_override,cap_net_bind_service,cap_net_admin,cap_net_raw,cap_sys_resource=eip
            运行用户: nobody
            已选择的架构: linux-amd64
            
            #下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
            Tun内核版本: 2021.03.10
            Tun内核文件: 存在
            Tun内核运行权限: 正常
            
            Game内核版本: 20210310
            Game内核文件: 存在
            Game内核运行权限: 正常
            
            Dev内核版本: v1.4.2-7-gd759d16
            Dev内核文件: 存在
            Dev内核运行权限: 正常
            
            #===================== 插件设置 =====================#
            
            当前配置文件: /etc/openclash/config/lopa.yaml
            启动配置文件: /etc/openclash/lopa.yaml
            运行模式: fake-ip-mix
            默认代理模式: rule
            UDP流量转发(tproxy): 停用
            DNS劫持: 启用
            自定义DNS: 启用
            IPV6-DNS解析: 停用
            禁用Dnsmasq缓存: 启用
            自定义规则: 停用
            仅允许内网: 停用
            仅代理命中规则流量: 停用
            仅允许常用端口流量: 停用
            绕过中国大陆IP: 停用
            
            #启动异常时建议关闭此项后重试
            混合节点: 停用
            保留配置: 启用
            
            #启动异常时建议关闭此项后重试
            第三方规则: 停用

            #===================== 防火墙设置 =====================#
            
            #NAT chain
            
            # Generated by iptables-save v1.8.3 on Fri Mar 26 16:15:34 2021
            *nat
            :PREROUTING ACCEPT [259:35768]
            :INPUT ACCEPT [1667:104935]
            :OUTPUT ACCEPT [1507:103467]
            :POSTROUTING ACCEPT [644:55094]
            :MINIUPNPD - [0:0]
            :MINIUPNPD-POSTROUTING - [0:0]
            :openclash - [0:0]
            :openclash_output - [0:0]
            :postrouting_lan_rule - [0:0]
            :postrouting_rule - [0:0]
            :postrouting_wan_rule - [0:0]
            :prerouting_lan_rule - [0:0]
            :prerouting_rule - [0:0]
            :prerouting_wan_rule - [0:0]
            :zone_lan_postrouting - [0:0]
            :zone_lan_prerouting - [0:0]
            :zone_wan_postrouting - [0:0]
            :zone_wan_prerouting - [0:0]
            -A PREROUTING -d 8.8.4.4/32 -p tcp -m tcp --dport 53 -j ACCEPT
            -A PREROUTING -d 8.8.8.8/32 -p tcp -m tcp --dport 53 -j ACCEPT
            -A PREROUTING -m comment --comment "!fw3: Custom prerouting rule chain" -j prerouting_rule
            -A PREROUTING -i eth1 -m comment --comment "!fw3" -j zone_lan_prerouting
            -A PREROUTING -i eth0 -m comment --comment "!fw3" -j zone_wan_prerouting
            -A PREROUTING -p udp -m udp --dport 53 -j REDIRECT --to-ports 53
            -A PREROUTING -p udp -m udp --dport 53 -m comment --comment dns_hijack -j REDIRECT --to-ports 53
            -A PREROUTING -p tcp -m tcp --dport 53 -m comment --comment dns_hijack -j REDIRECT --to-ports 53
            -A PREROUTING -p tcp -j openclash
            -A OUTPUT -j openclash_output
            -A POSTROUTING -m comment --comment "!fw3: Custom postrouting rule chain" -j postrouting_rule
            -A POSTROUTING -o eth1 -m comment --comment "!fw3" -j zone_lan_postrouting
            -A POSTROUTING -o eth0 -m comment --comment "!fw3" -j zone_wan_postrouting
            -A openclash -m set --match-set localnetwork dst -j RETURN
            -A openclash -p tcp -j REDIRECT --to-ports 7892
            -A openclash_output -p tcp -m tcp --sport 1688 -j RETURN
            -A openclash_output -m set --match-set localnetwork dst -j RETURN
            -A zone_lan_postrouting -m comment --comment "!fw3: Custom lan postrouting rule chain" -j postrouting_lan_rule
            -A zone_lan_prerouting -m comment --comment "!fw3: Custom lan prerouting rule chain" -j prerouting_lan_rule
            -A zone_wan_postrouting -m comment --comment "!fw3: Custom wan postrouting rule chain" -j postrouting_wan_rule
            -A zone_wan_postrouting -j MINIUPNPD-POSTROUTING
            -A zone_wan_postrouting -m comment --comment "!fw3" -j FULLCONENAT
            -A zone_wan_prerouting -m comment --comment "!fw3: Custom wan prerouting rule chain" -j prerouting_wan_rule
            -A zone_wan_prerouting -m comment --comment "!fw3" -j FULLCONENAT
            -A zone_wan_prerouting -j MINIUPNPD
            COMMIT
            # Completed on Fri Mar 26 16:15:34 2021
            
            #Mangle chain
            
            # Generated by iptables-save v1.8.3 on Fri Mar 26 16:15:34 2021
            *mangle
            :PREROUTING ACCEPT [146719:242564621]
            :INPUT ACCEPT [144081:241938741]
            :FORWARD ACCEPT [2638:625880]
            :OUTPUT ACCEPT [126687:236957644]
            :POSTROUTING ACCEPT [129317:237583204]
            :openclash - [0:0]
            :openclash_dns_hijack - [0:0]
            :openclash_output - [0:0]
            -A PREROUTING -p udp -j openclash
            -A PREROUTING -p tcp -m tcp --dport 53 -j openclash_dns_hijack
            -A FORWARD -o eth0 -p tcp -m tcp --tcp-flags SYN,RST SYN -m comment --comment "!fw3: Zone wan MTU fixing" -j TCPMSS --clamp-mss-to-pmtu
            -A FORWARD -i eth0 -p tcp -m tcp --tcp-flags SYN,RST SYN -m comment --comment "!fw3: Zone wan MTU fixing" -j TCPMSS --clamp-mss-to-pmtu
            -A OUTPUT -j openclash_output
            -A openclash -p udp -m udp --dport 500 -j RETURN
            -A openclash -p udp -m udp --dport 546 -j RETURN
            -A openclash -p udp -m udp --dport 68 -j RETURN
            -A openclash -m set --match-set localnetwork dst -j RETURN
            -A openclash -j MARK --set-xmark 0x162/0xffffffff
            -A openclash_dns_hijack -d 8.8.8.8/32 -j MARK --set-xmark 0x162/0xffffffff
            -A openclash_dns_hijack -d 8.8.4.4/32 -j MARK --set-xmark 0x162/0xffffffff
            -A openclash_output -p udp -m udp --sport 500 -j RETURN
            -A openclash_output -p udp -m udp --sport 546 -j RETURN
            -A openclash_output -p udp -m udp --sport 68 -j RETURN
            -A openclash_output -m set --match-set localnetwork dst -j RETURN
            COMMIT
            # Completed on Fri Mar 26 16:15:34 2021
            
            #===================== IPSET状态 =====================#
            
            Name: music
            Name: localnetwork
            
            #===================== 路由表状态 =====================#
            
            #route -n
            Kernel IP routing table
            Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
            0.0.0.0         172.31.1.1      0.0.0.0         UG    0      0        0 eth0
            172.31.1.0      0.0.0.0         255.255.255.0   U     0      0        0 eth0
            192.168.31.0    0.0.0.0         255.255.255.0   U     0      0        0 eth1
            198.18.0.0      0.0.0.0         255.255.0.0     U     0      0        0 utun
            #ip route list
            default via 172.31.1.1 dev eth0 proto static src 172.31.1.4 
            172.31.1.0/24 dev eth0 proto kernel scope link src 172.31.1.4 
            192.168.31.0/24 dev eth1 proto kernel scope link src 192.168.31.200 
            198.18.0.0/16 dev utun proto kernel scope link src 198.18.0.1 
            #ip rule show
            0:	from all lookup local 
            32765:	from all fwmark 0x162 lookup 354 
            32766:	from all lookup main 
            32767:	from all lookup default 
            
            #===================== Tun设备状态 =====================#
            
            utun: tun pi filter
            
            #===================== 端口占用状态 =====================#
            
            tcp        0      0 192.168.31.200:7890     0.0.0.0:*               LISTEN      12617/clash
            tcp        0      0 192.168.31.200:7891     0.0.0.0:*               LISTEN      12617/clash
            tcp        0      0 192.168.31.200:7892     0.0.0.0:*               LISTEN      12617/clash
            tcp        0      0 192.168.31.200:7893     0.0.0.0:*               LISTEN      12617/clash
            tcp        0      0 198.18.0.1:7777         0.0.0.0:*               LISTEN      12617/clash
            tcp        0      0 192.168.31.200:9090     0.0.0.0:*               LISTEN      12617/clash
            udp        0      0 198.18.0.1:7777         0.0.0.0:*                           12617/clash
            udp        0      0 127.0.0.1:7874          0.0.0.0:*                           12617/clash
            udp        0      0 192.168.31.200:7891     0.0.0.0:*                           12617/clash
            udp        0      0 192.168.31.200:7892     0.0.0.0:*                           12617/clash
            udp        0      0 192.168.31.200:7893     0.0.0.0:*                           12617/clash
            udp        0      0 :::44617                :::*                                12617/clash
            udp        0      0 :::46687                :::*                                12617/clash
            udp        0      0 :::32866                :::*                                12617/clash
            udp        0      0 :::49254                :::*                                12617/clash
            udp        0      0 :::57971                :::*                                12617/clash
            udp        0      0 :::39548                :::*                                12617/clash
            udp        0      0 :::46724                :::*                                12617/clash
            udp        0      0 :::37561                :::*                                12617/clash
            udp        0      0 :::48345                :::*                                12617/clash
            udp        0      0 :::51958                :::*                                12617/clash
            udp        0      0 :::39210                :::*                                12617/clash
            udp        0      0 :::34622                :::*                                12617/clash
            udp        0      0 :::45912                :::*                                12617/clash
            udp        0      0 :::41310                :::*                                12617/clash
            udp        0      0 :::38250                :::*                                12617/clash
            udp        0      0 :::35242                :::*                                12617/clash
            udp        0      0 :::59332                :::*                                12617/clash
            udp        0      0 :::34254                :::*                                12617/clash
            udp        0      0 :::42960                :::*                                12617/clash
            udp        0      0 :::60894                :::*                                12617/clash
            udp        0      0 :::48618                :::*                                12617/clash
            udp        0      0 :::49148                :::*                                12617/clash
            udp        0      0 :::46623                :::*                                12617/clash
            
            #===================== 测试本机DNS查询 =====================#
            
            Server:		127.0.0.1
            Address:	127.0.0.1#53
            
            Name:      www.baidu.com
            Address 1: 198.18.0.52
            *** Can't find www.baidu.com: No answer
            
            #===================== resolv.conf.auto =====================#
            
            # Interface lan
            nameserver 192.168.31.200
            # Interface wan
            nameserver 172.31.1.1
            nameserver 172.31.1.1
            search *****.*****.***
            
            #===================== 测试本机网络连接 =====================#
            
            
            #===================== 测试本机网络下载 =====================#

**Comment by vernesong** [comment]
iptables-mod-extra 依赖不正常，建议重装

**Comment by lnaxk** [comment]
> iptables-mod-extra 依赖不正常，建议重装

感谢恢复，好像问题是解决了我在试几天辛苦您了。
