### ISSUE TITLE
安卓电视盒子安装的plex app无法联网

### ISSUE THREAD

**Issue by warrenhoo** [vernesong/OpenClash#1317]
1、正常使用dnsmasq，盒子plex app正常联网登录，进而访问到自己家的plex服务器。
2、路由再 打开ssr，大陆白名单模式，手动规则plex.com域名及子域名不代理，重启盒子去除盒子缓存的dns，盒子plex app 注销登录，再登录仍然可以正常访问。 GFW模式也是可以的。
 3、关闭ssr，打开openclash（ fake-ip，手动制定规则plex.com及其子域名不代理，勾选监听53端口），电脑手机等youtube google正常访问， 重启盒子去除盒子缓存的dns，再打开plex app，注销，再登录，提示无法联网。
4、openclash 切换到redir-host模式，重复上述步骤，仍然无法联网。
5、openclash里 切换回fake-ip模式，强制plex.com及其子域名 走代理，重复上述步骤，仍然无法联网。
6、opencash 切换到redir-host模式，强制plex.com及其子域名 走代理，重复上述步骤，仍然无法联网。
7、无奈关闭openclash，打开ssr，一切正常。
查看openclash yacd面板，其中plex.com 这个域名的destinationg ip是空的， 但好像经常访问的baidu.com也是空的，可能也不是这个原因。
无招了。
安卓手机、苹果手机 的plex app 又是正常的。 安卓电视盒子的plex app需要用手机或者电脑登录 plex.com/link 输入电视屏幕显示的验证码，可能就是这个步骤哪个网址解析不对头。

**Comment by vernesong** [comment]
ip是空的可能是dns查询失败了，你要看连接日志，开debug
