### ISSUE TITLE
自定义配置文件名不能带空格，否则报错

### ISSUE THREAD

**Issue by hackenfu** [vernesong/OpenClash#132]
今天订阅了几个新的配置后，突然运行不了，每次都显示第五步“清除dnsmaq缓存”就死活进行不下去了，开始怀疑是软件原因，反复重装，甚至重置了openwrt。。。还是不行
最后回退到不能多配置的0.35.6版本，没问题
猜测是不是今天新的配置的原因，在原来的“US BGP”中间加了一横“US-BGP”，果然可以了，然后保留这两个配置互相切换，前者不行，后者可以，看来自定义配置文件名不能带空格，大家要注意了
或者作者能不能修复该问题？谢谢

**Comment by vernesong** [comment]
好的
