### ISSUE TITLE
oculus quest2可以连接WiFi，但是显示“网络受到限制”，变成了砖头

### ISSUE THREAD

**Issue by anleguo** [vernesong/OpenClash#1320]
本人小白，r2s用了1个多月了吧，基本上是默认设置，手机、电脑、电视等使用openclash没有啥问题，但从亚马逊买的oculus quest2却不能上网，请明白人指点一下，谢谢！

**Comment by openips** [comment]
quest2用过 没问题 主路由为x64软路由

**Comment by anleguo** [comment]
节点问题吗？

**Comment by anleguo** [comment]
呵呵，和openclash无关，是oculus quest2自己的问题，WiFi用专用软件在手机或电脑上设置就好用了

**Comment by NengQian** [comment]
@anleguo  可以请教一下最后怎么解决的么，我也遇到了问题
