### ISSUE TITLE
如何禁止 redir-host 转发 ssh 连接？

### ISSUE THREAD

**Issue by ElmerZhang** [vernesong/OpenClash#1325]
我有两台服务器解析到同一个域名。
使用 IP ssh 到服务器时，redir-host 会随机转发到两台其中之一。
如何禁止 redir-host 转发这两个 IP？或者禁止转发 22 端口的连接？

**Comment by cielpy** [comment]
在 Clash 里设置直连可以吗

**Comment by ElmerZhang** [comment]
> 在 Clash 里设置直连可以吗

规则里加了 22 端口直连，不知道是我加的不对还是什么原因，没有用。
```
  - DST-PORT,22,DIRECT
```

**Comment by cielpy** [comment]
可以看一下命中了什么规则，Dashboard 可以看到

如果没有命中 DST-PORT 规则，应该是优先级问题

**Comment by vernesong** [comment]
加到顶部自定义规则里去

**Comment by biezhihua** [comment]
![image](https://user-images.githubusercontent.com/6761107/128980284-ed9e2356-15ae-46d5-834e-fe6ad308afc1.png)
