### ISSUE TITLE
不知能否支持 GRE（Generic Routing Encapsulation）协议

### ISSUE THREAD

**Issue by dickwu** [vernesong/OpenClash#1326]
因为公司内网是用的 GRE 协议弄的vpn，但是由于openclash 是全局流量接管的，不支持该协议，目前只能通过全局配置不走代理

**Comment by vernesong** [comment]
什么需求

**Comment by LyndonWu233** [comment]
也想要这个需求支持。如下图：
![image](https://user-images.githubusercontent.com/50765328/229059302-11e37e1f-b6f8-43c4-b29e-35c7508d768d.png)
关闭open clash之后在家里正常连接单位，开启open clash之后电脑就会出现这样子的信息。

**Comment by vernesong** [comment]
绕过国内不就行了吗
