### ISSUE TITLE
koolshare/openwrt(19.07) 下yacd控制面板无法打开

### ISSUE THREAD

**Issue by hitsmaxft** [vernesong/OpenClash#133]
Openwrt Koolshare mod V2.31 r10822-50aa0525d1

已选择编译版本 | linux-amd64 | 上次检查更新时间 | 2020-02-07 10:38:21
处理器架构（PROC） | x86_64 | 处理器架构（OPKG） | x86_64
当前内核版本 | 查询失败 | 当前客户端版本 | v0.36.4-beta

想用 openclash 提供的yacd控制面板， 但是无法正常使用

uhttpd 对 /openclash 路径的访问，返回了 500， js文件路径无法访问。

可能是 koolshare 这个版本对提供 http 服务有限制？

**Comment by zhangzhexx** [comment]
我的openwrt koolshare也是同样的现象

**Comment by yangyanch** [comment]
同样情况啊

**Comment by kongluoxing** [comment]
+1 500了

**Comment by hitsmaxft** [comment]
解决办法是手动创建到 /www/luci-static/openclash 

```
ln -s /usr/share/openclash/yacd /www/luci-static/openclash
```

访问页面 192.168.x.x/luci-static/openclash 

luci-static 是luci允许访问的静态文件路径。 估计还是访问控制了

**Comment by vernesong** [comment]
koolshare我没有研究，如果这样有用我会把链接统一改过去

**Comment by hitsmaxft** [comment]
最新的 openwrt也有相同的问题。 建议更改路径

**Comment by 72521** [comment]
emm，我本来用的好好的，升级了访问不到了，来看更新日志发现原来改了，路径改这么长了？。。如何自己定义这个路径？
