### ISSUE TITLE
“仅允许内网”功能对多LAN的支持需要优化

### ISSUE THREAD

**Issue by YueYue2002** [vernesong/OpenClash#1330]
我有三个防火墙区域：WAN、LAN、LAN2。且配置了允许LAN2访问互联网。
在openclash设置中配置了“仅允许内网”后，LAN可以正常使用clash，LAN2既无法访问国内网站也无法访问国外网站，但可以访问控制面板。
希望“仅允许内网”功能可以手动选择允许的防火墙区域，且不影响未选中的区域访问国内网站。

**Comment by vernesong** [comment]
这个功能是内核限制,你可以单独设置防火墙达到一样的效果
