### ISSUE TITLE
配置文件规则页面，选了洞主的，报错，点击任何页面都是这样的错误提示，请问要咋处理呢

### ISSUE THREAD

**Issue by tzbzl** [vernesong/OpenClash#1333]
由于以下错误，配置文件无法被加载：
uci: Parse error (option/list command found before the first section) at line 1, byte 1
option sub_convert '1'
	option template 'lhie1 洞主规则完整版'
	option emoji 'true'
	option udp 'true'
	option skip_cert_verify 'true'
	option sort 'true'
	option node_type 'true'

**Comment by tzbzl** [comment]
![Uploading 微信图片_20210405094023.png…]()

**Comment by vernesong** [comment]
内核更新页面下方重置按钮
