### ISSUE TITLE
 为什么我安装好了却没有服务那个界面出来的？

### ISSUE THREAD

**Issue by ikwen** [vernesong/OpenClash#1339]
我是这样安装的。
Install
Upload ipk file to tmp folder
cd /tmp
opkg update
opkg install luci-app-clash_v1.7.5.7_all.ipk
opkg install luci-app-clash_v1.7.5.7_all.ipk --force-depends

![111](https://user-images.githubusercontent.com/11069985/113750944-f5f1dd00-973d-11eb-804b-740737354ddb.PNG)

**Comment by lifetyper** [comment]
张三家的货你来李四家退款？
https://github.com/frainzy1477/luci-app-clash

**Comment by ikwen** [comment]
我想安装open clash ，我现在还不明白  clash 和open clash 有什么区别？百度google也搜不到.

**Comment by zhangj3** [comment]
建议你去https://github.com/frainzy1477/luci-app-clash提issue....

**Comment by stylophone** [comment]
这个问题我也发生了。看了一下log发现是Lua runtime没有安装，openclash的lua controller没有跑起来。解决方法是

opkg update
opkg install luci-compat

安装一下Lua runtime就有了

**Comment by UnlimitedWand** [comment]
遇到了同样的问题，openwrt退出登陆重新进就出现了

**Comment by xia0028** [comment]
我也遇到了

**Comment by donglisi** [comment]
我也遇到了，按照 https://comate.baidu.com/zh/page/0uyqmvemaj7 这个教程解决了，这里记录一下：

opkg install bash dnsmasq-full curl ca-bundle ip-full \
ruby ruby-yaml kmod-tun kmod-inet-diag unzip \
kmod-nft-tproxy luci-compat luci-base
