### ISSUE TITLE
Fake-IP(TUN)模式下steam下载缓慢

### ISSUE THREAD

**Issue by sealszzz** [vernesong/OpenClash#134]
Fake-IP(TUN)模式下steam下载缓慢，速度时高时低，切换到Redir-Host(TUN)模式下，速度满速下载。
steam规则为直连。

**Comment by vernesong** [comment]
tun内核目前fake模式下有点小问题，等待修复

**Comment by sakuraDan2023** [comment]
所以这个问题解决了吗？我怎么现在还是一样的问题呢，开TUN模式下速度很慢，开TUN混合，UDP走TUN，TCP走redir速度倒是满速

**Comment by vernesong** [comment]
设备性能问题

**Comment by sakuraDan2023** [comment]
> 

是嘛，可是我看我开了TUN模式后，cpu都没吃满，只有30%

**Comment by vernesong** [comment]
切换协议栈呢

**Comment by sakuraDan2023** [comment]
> 切换协议栈呢

一样的，system和gvisor都一样

**Comment by yegetables** [comment]
今天遇到了,fake-ip tun混合模式走的是DIRECT,但是速度只有几十kb,从system切换成gVisor协议栈后速度飙升,所以这个问题还存在居然

**Comment by chenguanliang3007** [comment]
覆写DNS设置里面在Fake-IP-Filter的黑名单中补充多一条即可“+.store.cdn.queniuqe.com“
