### ISSUE TITLE
TUN模式下腾讯会议等部分app无法连接

### ISSUE THREAD

**Issue by syq7970** [vernesong/OpenClash#1342]
[TUN] 当前内核版本 | 2021.03.10

当前客户端版本 | v0.42.03-beta

各种Fake-ip 混合和 Host模式都试了，只要开启了TUN，在腾讯会议App都提示无法连接，也无法进入会议室，并且玩国服游戏会丢包，有能解决的小伙伴么？目前只能暂时不开TUN模式。

**Comment by vernesong** [comment]
依赖装了没有，网络问题你几句话说不清楚
