### ISSUE TITLE
0.42.03版本修改服务器与策略组等配置后, 无法正常重启

### ISSUE THREAD

**Issue by msylgj** [vernesong/OpenClash#1343]
如题,首先正常运行的情况下后台看进程如下
![Snipaste_2021-04-08_16-40-24](https://user-images.githubusercontent.com/1388852/113997214-80dfee00-988a-11eb-879c-e8f7dbed43ee.png)

然后在luci修改服务器与策略组配置后点击应用配置(其实只需要点击页面中的应用配置按钮, 其它页面没有挨个试,应该都是一样的) , luci页面在设置FAKE-IP黑名单处卡住,如图
![Snipaste_2021-04-08_16-41-25](https://user-images.githubusercontent.com/1388852/113997569-dd430d80-988a-11eb-9668-e881a55314fb.png)

后台进程情况如图:
![Snipaste_2021-04-08_16-41-53](https://user-images.githubusercontent.com/1388852/113997595-e3d18500-988a-11eb-8b14-34f051f467fa.png)

要恢复的话需要手动kill掉restart的进程, 然后手动在luci页面关闭openclash一遍再启动openclash才可以. 
麻烦大佬抽空看一下..

**Comment by lifetyper** [comment]
好像是有这个问题，我都直接重启路由搞定的。

**Comment by msylgj** [comment]
fixed in 0.42.04 
https://github.com/vernesong/OpenClash/commit/38a2e8d5c712c3678a4682528edec5f82ee38a6c
