### ISSUE TITLE
移动网络的问题，求问大佬？

### ISSUE THREAD

**Issue by xzhqhfe** [vernesong/OpenClash#1353]
原来用的联通网好好的，这段时间试着用移动网用，一样的节点一样的设置就是无法访问所有外国网站。求问大佬是设置有变动还是网络的问题？

**Comment by vernesong** [comment]
进控制面板看连接日志

**Comment by xzhqhfe** [comment]
2021-04-13 21:44:00 OpenClash Start Successful
2021-04-13 21:44:25 Groups History:【Moneyfly.yaml】 Restore Successful
time="2021-04-13T21:44:19+08:00" level=info msg="DNS server listening at: 0.0.0.0:7874"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider encoreTVB"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider Telegram"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider Abema TV"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider Apple"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider DAZN"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider Japonx"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider iQiyi"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider Pornhub"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider ABC"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider Domestic IPs"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider YouTube"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider Apple News"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider myTV SUPER"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider Speedtest"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider Pandora"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider Reject"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider Special"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider Hulu"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider Letv"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider BBC iPlayer"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider Spotify"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider Netflix"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider KKBOX"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider Hulu Japan"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider Line TV"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider Bilibili"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider Youku"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider KKTV"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider Steam"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider Microsoft"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider Bahamut"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider Domestic"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider Disney Plus"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider ViuTV"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider Tencent Video"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider PROXY"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider Soundcloud"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider Amazon"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider HBO"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider PayPal"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider Netease Music"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider JOOX"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider Apple TV"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider PBS"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider Fox+"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider Fox Now"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial compatible provider Domestic"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial compatible provider Spotify"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial compatible provider Speedtest"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial compatible provider Microsoft"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial compatible provider AdBlock"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial compatible provider Steam"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial compatible provider Netflix"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial compatible provider Apple"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial compatible provider AsianTV"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial compatible provider Auto - UrlTest"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial compatible provider PayPal"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial compatible provider Telegram"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial compatible provider Proxy"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial compatible provider Youtube"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial compatible provider Others"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial compatible provider GlobalTV"

**Comment by xzhqhfe** [comment]
> 进入控制面板看连接日志

2021-04-13 21:44:00 OpenClash Start Successful
2021-04-13 21:44:25 Groups History:【Moneyfly.yaml】 Restore Successful
time="2021-04-13T21:44:19+08:00" level=info msg="DNS server listening at: 0.0.0.0:7874"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider encoreTVB"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider Telegram"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider Abema TV"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider Apple"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider DAZN"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider Japonx"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider iQiyi"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider Pornhub"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider ABC"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider Domestic IPs"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider YouTube"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider Apple News"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider myTV SUPER"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider Speedtest"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider Pandora"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider Reject"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider Special"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider Hulu"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider Letv"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider BBC iPlayer"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider Spotify"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider Netflix"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider KKBOX"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider Hulu Japan"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider Line TV"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider Bilibili"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider Youku"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider KKTV"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider Steam"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider Microsoft"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider Bahamut"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider Domestic"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider Disney Plus"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider ViuTV"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider Tencent Video"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider PROXY"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider Soundcloud"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider Amazon"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider HBO"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider PayPal"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider Netease Music"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider JOOX"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider Apple TV"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider PBS"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider Fox+"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial rule provider Fox Now"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial compatible provider Domestic"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial compatible provider Spotify"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial compatible provider Speedtest"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial compatible provider Microsoft"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial compatible provider AdBlock"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial compatible provider Steam"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial compatible provider Netflix"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial compatible provider Apple"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial compatible provider AsianTV"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial compatible provider Auto - UrlTest"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial compatible provider PayPal"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial compatible provider Telegram"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial compatible provider Proxy"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial compatible provider Youtube"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial compatible provider Others"
time="2021-04-13T21:44:19+08:00" level=info msg="Start initial compatible provider GlobalTV"

**Comment by vernesong** [comment]
控制面板，日志debug模式
