### ISSUE TITLE
哔哩哔哩无法走代理

### ISSUE THREAD

**Issue by ChingLin123** [vernesong/OpenClash#1354]
主路由开启openclash的情况下，设置哔哩哔哩走代理规则，局域网下的访问哔哩哔哩还是没有走代理。但是通过socks5的方式连接到路由器却可以走代理

**Comment by Galiathuss** [comment]
同样有这个问题

**Comment by xingmie** [comment]
我也有这个问题，感觉是规则的问题，用AsiaTV没用，全局就可以

**Comment by ChingLin123** [comment]
> 同样有这个问题

目前已解决，之前把那个绕过中国大陆IP打开了，现在把这关了就一切正常了

**Comment by ChingLin123** [comment]
> 我也有这个问题，感觉是规则的问题，用AsiaTV没用，全局就可以

目前已解决，之前把那个绕过中国大陆IP打开了，现在把这关了就一切正常了
