### ISSUE TITLE
libcap-bin绝迹了么？

### ISSUE THREAD

**Issue by gujiangjiang** [vernesong/OpenClash#1356]
上次安装还能从snapshot里面安装，今天重装了一下路由器，发现这货已经全网都下不到了，怎么回事？

release里面只有libcap，无libcap-bin
snapshot(2021-04-14 22:00)里面只有libcap-ng和libcap-ng-bin，这俩装上并没有用

已经Google和百度都搜过了，所有的下载链接打开均是404，无论是OpenWRT官网还是各镜像源，均消失不见了

请问现在还怎么解决这个问题？？？
![image](https://user-images.githubusercontent.com/13273955/114733765-38d33680-9d76-11eb-93b1-db444c966f89.png)
![image](https://user-images.githubusercontent.com/13273955/114733881-4b4d7000-9d76-11eb-99da-9d2b095fbf74.png)

**Comment by Vigroid** [comment]
See [here](https://downloads.openwrt.org/snapshots/packages/x86_64/base/)

Quoted from https://github.com/vernesong/OpenClash/issues/839#issuecomment-814505477

**Comment by Flammulinavelutipes** [comment]
> See [here](https://downloads.openwrt.org/snapshots/packages/x86_64/base/)
> 
> Quoted from [#839 (comment)](https://github.com/vernesong/OpenClash/issues/839#issuecomment-814505477)

你好，我是树莓派4B，我想问下你给的这个链接点进去之后，我应该选哪个分支？

**Comment by Flammulinavelutipes** [comment]
> See [here](https://downloads.openwrt.org/snapshots/packages/x86_64/base/)
> 
> Quoted from [#839 (comment)](https://github.com/vernesong/OpenClash/issues/839#issuecomment-814505477)

没事了我找到了，是aarch64_cortex-a72，打扰到你了
