### ISSUE TITLE
请问OpenClash能不能和AdGuard Home一起共存的？

### ISSUE THREAD

**Issue by euking18** [vernesong/OpenClash#1362]
设置好多天，各种组合搭配使用，同一个openwrt下，同时开启这两个插件，要么不能去广告，要么油管黑屏不能正常播放，请问怎么设置才正确？有懂的朋友可以指导一下吗？不要云回答，要成功设置的答案，我尝试搜索过许多答案无果。感谢🙏

**Comment by 1nfsr** [comment]
AdGuard Home做上游DNS 就可以了呀

**Comment by chyaww** [comment]
卧槽，找了好久原来根源在这里，谢谢老铁~~~~~

> AdGuard Home做上游DNS 就可以了呀

**Comment by euking18** [comment]
> 卧槽，找了好久原来根源在这里，谢谢老铁~~~~~亲测有效。。。
> 
> > AdGuard Home做上游DNS就可以了呀

怎么搞好的？请教一下，感谢🙏

**Comment by euking18** [comment]
> AdGuard Home做上游DNS 就可以了呀

请问是OpenClash下设置 adg为上游DNS服务器；
还是adg下 设置OpenClash为上游 DNS 服务器？

**Comment by 1nfsr** [comment]
> > AdGuard Home做上游DNS 就可以了呀
> 
> 请问是OpenClash下设置 adg为上游DNS服务器；
> 还是adg下 设置OpenClash为上游 DNS 服务器？
> adg的重定向又是如何选择

OpenClash下设置AdGuard Home为上游DNS 
我是这样设置的: 
 OpenClash下的所有上游DNS都删掉了,AdGuard Home 为唯一的上游DNS, 其他DNS去AdGuard Home里设置, AdGuard Home做为dnsmasq上游 或者不重定向

**Comment by euking18** [comment]
> > > AdGuard Home做上游DNS 就可以了呀
> > 
> > 
> > 请问是OpenClash下设置 adg为上游DNS服务器；
> > 还是adg下 设置OpenClash为上游 DNS 服务器？
> > adg的重定向又是如何选择
> 
> OpenClash下设置AdGuard Home为上游DNS
> 我是这样设置的:
> OpenClash下的所有上游DNS都删掉了,AdGuard Home 为唯一的上游DNS, 其他DNS去AdGuard Home里设置, AdGuard Home做为dnsmasq上游 或者不重定向

找过好多教程都不行，你这个好像是成功了，感谢兄弟。我再继续测试一段时间。。
-还有注意Clash规则设置问题，不然speedtext测速 速度减半还跑机场流量

**Comment by chyaww** [comment]
> > 卧槽，找了好久原来根源在这里，谢谢老铁~~~~~亲测有效。。。
> > > AdGuard Home做上游DNS就可以了呀
> 
> 怎么搞好的？请教一下，感谢🙏

> ### __openclash 全局设置 -dns设置 -自定义上游DNS服务器-127.0.0.1：52
52是我自定义的ad端口

**Comment by piaoyun** [comment]
我已经这样设置了。还是无法访问谷歌等网站呢
求大佬指点下。谢谢
![QQ截图20210422164947](https://user-images.githubusercontent.com/3724475/115685449-d0deaa80-a38a-11eb-88df-82a77f016188.jpg)
![QQ截图20210422164935](https://user-images.githubusercontent.com/3724475/115685458-d20fd780-a38a-11eb-8fe9-a0750be3d28f.jpg)

**Comment by euking18** [comment]
> > > AdGuard Home做上游DNS 就可以了呀
> > 
> > 
> > 请问是OpenClash下设置 adg为上游DNS服务器；
> > 还是adg下 设置OpenClash为上游 DNS 服务器？
> > adg的重定向又是如何选择
> 
> OpenClash下设置AdGuard Home为上游DNS
> 我是这样设置的:
> OpenClash下的所有上游DNS都删掉了,AdGuard Home 为唯一的上游DNS, 其他DNS去AdGuard Home里设置, AdGuard Home做为dnsmasq上游 或者不重定向

哥，经过我连续2天的使用发现一个问题：
我机场没有规则，我使用的是转换规则，选的是‘ACL4SSR 规则 Online Full‘（我不是指这条规则有问题）
访问google.com不了，但是可以正常访问google.com.hk，是哪里出现了问题，我搜索过许多答案都没有能解决的，openwrt下用别的软件都是正常打开google.com的，唯独openclash这里就是打不开。可以告诉我怎么解决吗？

**Comment by 1nfsr** [comment]
> > > > AdGuard Home做上游DNS 就可以了呀
> > > 
> > > 
> > > 请问是OpenClash下设置 adg为上游DNS服务器；
> > > 还是adg下 设置OpenClash为上游 DNS 服务器？
> > > adg的重定向又是如何选择
> > 
> > 
> > OpenClash下设置AdGuard Home为上游DNS
> > 我是这样设置的:
> > OpenClash下的所有上游DNS都删掉了,AdGuard Home 为唯一的上游DNS, 其他DNS去AdGuard Home里设置, AdGuard Home做为dnsmasq上游 或者不重定向
> 
> 哥，经过我连续2天的使用发现一个问题：
> 我机场没有规则，我使用的是转换规则，选的是‘ACL4SSR 规则 Online Full‘（我不是指这条规则有问题）
> 访问google.com不了，但是可以正常访问google.com.hk，是哪里出现了问题，我搜索过许多答案都没有能解决的，openwrt下用别的软件都是正常打开google.com的，唯独openclash这里就是打不开。可以告诉我怎么解决吗？

没碰到你这情况,你可以看下DNS解析,或者换下节点再试试

**Comment by hplee0120** [comment]
> > > > AdGuard Home做上游DNS 就可以了呀
> > > 
> > > 
> > > 请问是OpenClash下设置 adg为上游DNS服务器；
> > > 还是adg下 设置OpenClash为上游 DNS 服务器？
> > > adg的重定向又是如何选择
> > 
> > 
> > OpenClash下设置AdGuard Home为上游DNS
> > 我是这样设置的:
> > OpenClash下的所有上游DNS都删掉了,AdGuard Home 为唯一的上游DNS, 其他DNS去AdGuard Home里设置, AdGuard Home做为dnsmasq上游 或者不重定向
> 
> 哥，经过我连续2天的使用发现一个问题：
> 我机场没有规则，我使用的是转换规则，选的是‘ACL4SSR 规则 Online Full‘（我不是指这条规则有问题）
> 访问google.com不了，但是可以正常访问google.com.hk，是哪里出现了问题，我搜索过许多答案都没有能解决的，openwrt下用别的软件都是正常打开google.com的，唯独openclash这里就是打不开。可以告诉我怎么解决吗？

我使用的兼容模式，跟你遇到同样的情况，大多数服务正常，但是经常莫名其妙的google.com 打不开，大概排除了一下可能跟dns 有关，因为我默认fallback 就启用了谷歌和CF 这两个，就会出现上述情况，如果我将内置的那个红鱼的DoH 也启用，就能解决问题。我怀疑可能是当前网络环境对谷歌和CF 的dns 连通性导致的？而红鱼那个因为未被干扰所以正常。

**Comment by piaoyun** [comment]
已经放弃折腾了与AdGuard Home共存的问题。

换了好几个插件，都是要么国外网站打不开。passwall  helloworld等等

DNS重定向。上游，直接替换。等等。openwrt防火墙开放接口。

反正自己也搞不懂是哪里的问题。。

现在直接装2个openwrt。一个出国。一个DNS。内网DHCP。设置网关和DNS服务器。2台单独的。不影响。反正主路由器，性能过剩。

**Comment by tio-plato** [comment]
不应该ad做clash上游，应该clash做ad上游
clash关闭劫持dns，ad设置重定向53到ad，然后ad里dns设置填写127.0.0.1:7874（clash的dns端口）
因为clash在fake-ip模式下不是所有的dns请求都会发送到设置的dns

**Comment by woboo110** [comment]
> 已经放弃折腾了与AdGuard Home共存的问题。
> 
> 换了好几个插件，都是要么国外网站打不开。passwall helloworld等等
> 
> DNS重定向。上游，直接替换。等等。openwrt防火墙开放接口。
> 
> 反正自己也搞不懂是哪里的问题。。
> 
> 现在直接装2个openwrt。一个出国。一个DNS。内网DHCP。设置网关和DNS服务器。2台单独的。不影响。反正主路由器，性能过剩。

可以设置双adg，一个国内一个国外
![image](https://user-images.githubusercontent.com/68997087/117389683-4f0c8680-af1f-11eb-8d2e-6beb212e50e2.png)

**Comment by magic3584** [comment]
> 不应该ad做clash上游，应该clash做ad上游
> clash关闭劫持dns，ad设置重定向53到ad，然后ad里dns设置填写127.0.0.1:7874（clash的dns端口）
> 因为clash在fake-ip模式下不是所有的dns请求都会发送到设置的dns

大佬能否说的详细点？ adg 设置 53 提示端口占用了，是否跟防火墙还有关呢？

**Comment by tio-plato** [comment]
> > 不应该ad做clash上游，应该clash做ad上游
> > clash关闭劫持dns，ad设置重定向53到ad，然后ad里dns设置填写127.0.0.1:7874（clash的dns端口）
> > 因为clash在fake-ip模式下不是所有的dns请求都会发送到设置的dns
> 
> 大佬能否说的详细点？ adg 设置 53 提示端口占用了，是否跟防火墙还有关呢？

如果你是用的openwrt+ipk的adguard，防火墙不需要设置任何关于53端口的规则，ad这边选择重定向53到ad，然后应该就可以了，ad会处理好重定向的，反正我这边是这么设置的

**Comment by magic3584** [comment]
> > > 防火墙不需要设置任何关于53端口的规则
> > 
> > 
> > openwrt 是 F 大的，adguard 和 openclash 也都是固件里带的。
> > 防火墙规则如果是
> > iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53
> > iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53
> > 的话就没办法修改 adg 的端口。
> > 如果可以的话麻烦大佬看看这个 [v2ex.com/t/775957#reply1](https://www.v2ex.com/t/775957#reply1)
> 
> ![image](https://user-images.githubusercontent.com/60922756/117628151-6c558500-b1ab-11eb-96b6-0efe2044aa28.png)
> 你把adg设置成重定向，然后这两条规则注释掉。（我是旁路由模式的，防火墙除了一条旁路由的规则之外没别的了）
> 如果重定向不好用，你可以试下另外两个选项。**都不需要写任何防火墙规则**，adg会自动帮你解决的。
> 我是这么设置的，用起来没啥问题，如果在你那边不行我确实也不知道啥情况了。
> 那个v2ex帖子要登录才能看，我没账号看不到

感谢大佬，已经解决了

**Comment by w12928293** [comment]
> 不应该ad做clash上游，应该clash做ad上游
> clash关闭劫持dns，ad设置重定向53到ad，然后ad里dns设置填写127.0.0.1:7874（clash的dns端口）
> 因为clash在fake-ip模式下不是所有的dns请求都会发送到设置的dns

这个逻辑好像更清晰一些，目前调整了一下顺序，准备观察两天看看

**Comment by euking18** [comment]
> > > > > AdGuard Home 做上游DNS 就可以了呀
> > > > 
> > > > 
> > > > 所谓是OpenClash下设置adg为外部DNS服务器；
> > > > 还是adg下设置OpenClash为外部DNS服务器？
> > > > adg的发起者又是如何选择
> > > 
> > > 
> > > OpenClash下设置AdGuard Home为上游DNS
> > > 我是这样设置的：
> > > OpenClash下的所有上游DNS都掉了，AdGuard Home为唯一的上游DNS，其他DNS去Ad Home里设置，AdGuard Home做为dnsmasq上游或者不重定向
> > 
> > 
> > 哥，经过我连续 2 天的使用发现问题：
> > 我机场没有规则，我使用的是转换规则，选的是“ACL4SSR 规则在线完整”（我不是指规则有规则问题）
> > 访问 google.com，但是可以正常访问google.com.hk，是哪里出现了问题，我搜索过很多答案都没有能解决的，openwrt下用其他软件都可以正常打开google.com的，唯独openclash这里就是打不开。可以告诉我怎么解决吗？
> 
> 我使用的模式，因为遇到了同样的情况，大多数服务正常，但还有很多莫名其妙的原因google.com 打不开，大概排除可能跟dns 相关，我就可以启用谷歌和CF 这两个，即将出现的情况，我会建立的那个红鱼，如果可以的话，可以解决的问题。我怀疑可能是当前网络环境对歌和谷歌的网络环境导致的？

我找到问题的根源了，我解决了。百度了许多没有能解决的。你看看这样子设置是不是就OK了
https://blog.csdn.net/qq_41616600/article/details/107374256

**Comment by AlwaysOnline** [comment]
> 不应该ad做clash上游，应该clash做ad上游
> clash关闭劫持dns，ad设置重定向53到ad，然后ad里dns设置填写127.0.0.1:7874（clash的dns端口）
> 因为clash在fake-ip模式下不是所有的dns请求都会发送到设置的dns



127.0.0.1:7874 作为ADG的上游DNS，测试时提示：


服务器 "127.0.0.1:7874"：无法使用，请检查你输入的是否正确

**Comment by tio-plato** [comment]
> > 不应该ad做clash上游，应该clash做ad上游
> > clash关闭劫持dns，ad设置重定向53到ad，然后ad里dns设置填写127.0.0.1:7874（clash的dns端口）
> > 因为clash在fake-ip模式下不是所有的dns请求都会发送到设置的dns
> 
> 127.0.0.1:7874 作为ADG的上游DNS，测试时提示：
> 
> 服务器 "127.0.0.1:7874"：无法使用，请检查你输入的是否正确

测试是不通的，但是应该可以正常使用

**Comment by onepig22** [comment]
> 不应该ad做clash上游，应该clash做ad上游
> clash关闭劫持dns，ad设置重定向53到ad，然后ad里dns设置填写127.0.0.1:7874（clash的dns端口）
> 因为clash在fake-ip模式下不是所有的dns请求都会发送到设置的dns

你好 想问一下  op里面的上游路由器需要设置为clash的吗？
