### ISSUE TITLE
能在全局设置里面手动设置全局开启GEOIP吗

### ISSUE THREAD

**Issue by youyifentian** [vernesong/OpenClash#1365]
希望能添加全局开关GEOIP的功能，可以和订阅配置文件相结合一下，因为订阅里面本身没有设置GEOIP的话，经过订阅转换之后也没设置，想开启的话还得把配置文件下载下来重新编辑上传，或者直接编辑配置文件，但是订阅更新之后还得重新编辑，有点太麻烦了，希望能有一个全局设置GEOIP的功能，非常感谢

**Comment by vernesong** [comment]
自定义规则底部框不是可以加吗

**Comment by youyifentian** [comment]
> 自定义规则底部框不是可以加吗

dns:
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4


我这样写为啥不行啊，自定义规则的顶部和底部都填写，最后的配置文件还是geoip:false

**Comment by vernesong** [comment]
这里是dns部分，我说的是规则部分的geoip

**Comment by youyifentian** [comment]
> 这里是dns部分，我说的是规则部分的geoip

dns部分的geoip，设置true或者false，影响的是什么啊，这个我不太懂，规则那个geoip我已经明白了，非常感谢

**Comment by youyifentian** [comment]
[https://lancellc.gitbook.io/clash/clash-config-file/dns#geoip-default-true](url)

fallback-filter
Adjust fallback groups work ways.
geoip(Default: true)
If geoip is true, when geoip is CN, clash will use nameserver results. Otherwise, Clash will only use fallback results.


我已经明白这个DNS里的geoip是啥意思了，但是现在还是那个问题
虽然它说默认是true，但是我的订阅里面默认是开启的，我如果直接使用订阅，那没有问题，查看最后的配置文件确实开启了，
但是如果我使用订阅转换之后，这个转换之后的规则里面就没有dns设置，查看最后的配置文件就变成了geoip:false了，
我的意识就是怎样才能，即便在订阅里面没有设定geoip，仍然能手动设置它，
所以，上面我在自定义规则顶部和底部里面都写了dns的设置，但是不知道是我写的不对还是不能在那里面设置，反正就是无法实现dns的geoip:true，

所以，大神还是想请你看看怎样设置才好，非常感谢

**Comment by youyifentian** [comment]
换句话来说，按系统说明，它默认的是geoip:true，但是实际使用的时候却geoip:false，除非你的订阅里面明确写了getoip:true，最后配置文件才是true，而且除了手动更改配置文件之外，没有别的设置的地方了

**Comment by youyifentian** [comment]
#fallback-filter
   if [ -n "$(ruby_read "$CONFIG_FILE" "['dns']['fallback']")" ] && [ -z "$(ruby_read "$CONFIG_FILE" "['dns']['fallback-filter']")" ]; then
cat >> "$2" <<-EOF
  fallback-filter:
    geoip: false
    ipcidr:
      - 0.0.0.0/8
      - 10.0.0.0/8
      - 100.64.0.0/10
      - 127.0.0.0/8
      - 169.254.0.0/16
      - 172.16.0.0/12
      - 192.0.0.0/24
      - 192.0.2.0/24
      - 192.88.99.0/24
      - 192.168.0.0/16
      - 198.18.0.0/15
      - 198.51.100.0/24
      - 203.0.113.0/24
      - 224.0.0.0/4
      - 240.0.0.0/4
      - 255.255.255.255/32
    domain:
      - '+.google.com'
      - '+.facebook.com'
      - '+.youtube.com'
      - '+.githubusercontent.com'
EOF
   ruby_merge "$CONFIG_FILE" "['dns']" "$2"
   fi
}


你代码里面默认是false，不应该是true么。。。。。

**Comment by eggydutch** [comment]
> #fallback-filter
> if [ -n "$(ruby_read "$CONFIG_FILE" "['dns']['fallback']")" ] && [ -z "$(ruby_read "$CONFIG_FILE" "['dns']['fallback-filter']")" ]; then
> cat >> "$2" <<-EOF
> fallback-filter:
> geoip: false
> ipcidr:
> - 0.0.0.0/8
> - 10.0.0.0/8
> - 100.64.0.0/10
> - 127.0.0.0/8
> - 169.254.0.0/16
> - 172.16.0.0/12
> - 192.0.0.0/24
> - 192.0.2.0/24
> - 192.88.99.0/24
> - 192.168.0.0/16
> - 198.18.0.0/15
> - 198.51.100.0/24
> - 203.0.113.0/24
> - 224.0.0.0/4
> - 240.0.0.0/4
> - 255.255.255.255/32
> domain:
> - '+.google.com'
> - '+.facebook.com'
> - '+.youtube.com'
> - '+.githubusercontent.com'
> EOF
> ruby_merge "$CONFIG_FILE" "['dns']" "$2"
> fi
> }
> 
> 你代码里面默认是false，不应该是true么。。。。。

去年12月中的版本geoip默认改为false了

**Comment by youyifentian** [comment]
> > #fallback-filter
> > if [ -n "$(ruby_read "$CONFIG_FILE" "['dns']['fallback']")" ] && [ -z "$(ruby_read "$CONFIG_FILE" "['dns']['fallback-filter']")" ]; then
> > cat >> "$2" <<-EOF
> > fallback-filter:
> > geoip: false
> > ipcidr:
> > 
> > * 0.0.0.0/8
> > * 10.0.0.0/8
> > * 100.64.0.0/10
> > * 127.0.0.0/8
> > * 169.254.0.0/16
> > * 172.16.0.0/12
> > * 192.0.0.0/24
> > * 192.0.2.0/24
> > * 192.88.99.0/24
> > * 192.168.0.0/16
> > * 198.18.0.0/15
> > * 198.51.100.0/24
> > * 203.0.113.0/24
> > * 224.0.0.0/4
> > * 240.0.0.0/4
> > * 255.255.255.255/32
> >   domain:
> > * '+.google.com'
> > * '+.facebook.com'
> > * '+.youtube.com'
> > * '+.githubusercontent.com'
> >   EOF
> >   ruby_merge "$CONFIG_FILE" "['dns']" "$2"
> >   fi
> >   }
> > 
> > 你代码里面默认是false，不应该是true么。。。。。
> 
> 去年12月中的版本geoip默认改为false了

为什么啊

**Comment by vernesong** [comment]
配置文件里面有这段是不会覆盖的，你复制到配置文件里面再改成true就行了

**Comment by youyifentian** [comment]
> 配置文件里面有这段是不会覆盖的，你复制到配置文件里面再改成true就行了

这个我知道啊，但是现在用的配置文件都是订阅或者订阅转换，里面默认是不带这一项的，要弄得手动下载下来，在上传配置文件，而订阅你也懂得，更新有时候比较频繁，那每次都得手动下载、修改、在上传就很麻烦啦
