### ISSUE TITLE
openclash设置页面更新的规则集和Dashboard里更新的规则集不一样吗？

### ISSUE THREAD

**Issue by yanggis** [vernesong/OpenClash#1366]
openclash设置页面更新的规则集和Dashboard里更新的规则集不一样吗？
我在openclash设置页面下载了规则集，可以看到在rule-providers文件夹下看到对应文件会更新;但是在Dashboard里的规则页面点同意规则集更新后，在rule-providers看不到更新。

**Comment by vernesong** [comment]
你先确认配置文件里面有没有写进去
