### ISSUE TITLE
关于控制面板IP未设置和DNS的监听问题。

### ISSUE THREAD

**Issue by w0330t** [vernesong/OpenClash#1367]
1、控制面板IP未设置，这个一直都是红色，请问怎么解决
![image](https://user-images.githubusercontent.com/4970238/115941683-f8dc2400-a4d8-11eb-9973-91ce2898eeee.png)
2、我想把AdGuardHome用作下游dns配置，而AdGuardHome我安装在另外一台主机上，现在就出现了一个问题，配置写死了DNS的监听为127.0.0.1:8784，请问有什么办法可以把监听更改为0.0.0.0:8784？

**Comment by vernesong** [comment]
读不了ip跟固件有关，能登录就不必理会，ad你改oc插件的上游就行了

**Comment by w0330t** [comment]
ad做上游确实是一个办法，但是有个问题是我想用ad管理家里的网络连接。
或者说不用ad，大佬还有什么推荐的解决方案吗？

**Comment by w0330t** [comment]
> 读不了ip跟固件有关，能登录就不必理会，ad你改oc插件的上游就行了

![image](https://user-images.githubusercontent.com/4970238/117991173-6361e080-b370-11eb-95a2-4c20493f1bd6.png)
在升级了版本之后，YACD直接进不去了
