### ISSUE TITLE
请问这个ip识别是正常的吗？

### ISSUE THREAD

**Issue by Aryous** [vernesong/OpenClash#1368]
![image](https://user-images.githubusercontent.com/59194462/115944737-2e3d3d80-a4ea-11eb-8930-31d3b10d908c.jpeg)
IP识别有时候是大陆地区，有时候就跑到香港了

**Comment by Aryous** [comment]
请问为什么开启了openclash后，网页端的爱奇艺、优酷和腾讯等国内视频网站会提示地区版权限制无法观看呢？而移动端播放则没有问题。
另外非蜂窝数据版的iPad 里Apple Map的服务商会切换成tomtom，而非高德地图的数据，从而导致无法规划国内路线，不过这样的话可以查看国外的街景地图。
我的硬件设备是n1盒子，使用的是神机规则pro，看了一下分流应该没有问题，开启了DNS劫持。

**Comment by Galiathuss** [comment]
同样有这个问题，订阅的规则是没问题的，但是clash没办法定位正确的规则，b站会显示版权限制，

**Comment by Aryous** [comment]
> 同样有这个问题，订阅的规则是没问题的，但是clash没办法定位正确的规则，b站会显示版权限制，

我将final策略组选择直连之后可以在pc端网页版正常播放了，看上去像是分流的问题，但是奇怪的是，final指向proxy时，pc端网页版无法正常播放，iPad端网页版可以播放，不清楚是什么问题。

**Comment by Re2peR** [comment]
这个就是分流问题，你ipad端可能是开启了某些能分流的代理软件。。。

**Comment by Aryous** [comment]
> 这个就是分流问题，你ipad端可能是开启了某些能分流的代理软件。。。

事实上并没有，iPad直连软路由，openclash上的规则已经尝试过很多次了，均无效果，现在怀疑是DNS解析错误。
另：将Fina指向直连时可以正常播放，但是Google的某些服务就无法使用了。
目前使用的是Connershua神机规则Pro。
