### ISSUE TITLE
更新规则不完整导致配置错误

### ISSUE THREAD

**Issue by liyiecho** [vernesong/OpenClash#137]
今天早上起来，发现断网了，检查了一遍，原来是openclash导致的，主程序跟运行模式处于未启用状态，但是守护程序还在运行。然后下载了路由使用的配置文件，发现里面的规则不完整。应该是网络问题导致更新规则出错，以致于配置错误，导致机器没有网络，希望在更新规则前备份现有配置，如果发现错误，可以自动使用原配置。

**Comment by vernesong** [comment]
重启失败的情况下如果使用了第三方规则会尝试还原，watchdog只会尝试重启三次。
尽量避免几个更新任务同时进行
