### ISSUE TITLE
设置第三方规则时获取自定策略组失败

### ISSUE THREAD

**Issue by xingmie** [vernesong/OpenClash#1371]
用的是自己写的规则文件，基于Dler和洞主规则，因为经常要看动画疯，就在配置文件自己一个写了“Bahamut“的策略组放了一些台湾节点并更改了Rulset和script的设置，然后在全局设置中的设置第三方规则时，从配置文件获取自定策略组时并没有获取到Bahamut这个策略组，启动后看运行中的配置文件ruleset里面Bahamut仍然用的是GlobleTV的规则，运行日志中显示：2021-04-29 11:03:12 Groups History:【Dler-script.yaml】 Restore Successful
{"message":"Selector update error: proxy not exist"}
{"message":"Selector update error: proxy not exist"}
{"message":"Selector update error: proxy not exist"}

以上，不知道我描述清楚没有，是我的设置方法有问题还是其他原因，请指教，谢谢。

**Comment by vernesong** [comment]
配置文件没写对吧

**Comment by xingmie** [comment]
> 配置文件没写对吧

谢谢v大回复。
配置应该是对的，我后来自己摸索了一下，把那个设置第三方规则取消掉了，也就是说现在我的配置完全是自己写的，不通过软件的功能往里面再添加什么，这样以后策略组就正常了。
所以严格来说我此前是多此一举，因为本身用的script，也不需要再通过软件自动更新什么。
