### ISSUE TITLE
可否增加绕过国外IP

### ISSUE THREAD

**Issue by binken** [vernesong/OpenClash#1372]
可否考虑增加绕过国外IP

**Comment by vernesong** [comment]
用回国规则就行了啊，光绕过还是需要规则支持不然怎么用

**Comment by binken** [comment]
回国规则没问题， 但是国外的IP还是走OpenClash, 下行带宽受到影响。如果可以定义国外IP 不走OpenClash的话，就不受到影响。
目前测试下来，1G带宽，不走Openclash 可以达到900MB，但是走Openclash 直连，大概是600左右
