### ISSUE TITLE
IPIFY 国外 ip地址栏一直显示：查询中

### ISSUE THREAD

**Issue by lrgcx** [vernesong/OpenClash#1373]
![Xnip2021-05-03_12-27-19](https://user-images.githubusercontent.com/61493820/116841192-05fcbf80-ac0b-11eb-9dc4-eaf7a6b23710.jpg)

**Comment by ShowMarkK** [comment]
我也是 貌似之前没有这个情况的

**Comment by luoweihua7** [comment]
![image](https://user-images.githubusercontent.com/3157520/126957298-601eebb4-d78d-44f7-81ac-45a1b0029c18.png)
尝试关掉浏览器的去广告插件再试试
