### ISSUE TITLE
为什么每次开启clash YouTube都无法访问 等一段时间才正常

### ISSUE THREAD

**Issue by paladin4fan** [vernesong/OpenClash#1374]
Redir-Host+Rule模式
每次更新规则或者订阅导致重启clash之后，其他网站都可以正常使用
只有YouTube 在“运行状态”下是链接超时
浏览器访问则是打开YouTube主页 但是视频列表那里写着“您没有联网，请检查网络连接。”
F12的console里有非常多YouTube的资源提示连接已重置
切节点不管用 放置在那边过一阵子 大概就是吃顿饭的时间回来 就又正常了
其他需要代理的网站都是clash上线就能正常使用的

**Comment by OleStore** [comment]
> Redir-Host+Rule模式
> 每次更新规则或者订阅导致重启clash之后，其他网站都可以正常使用
> 只有YouTube 在“运行状态”下是链接超时
> 浏览器访问则是打开YouTube主页 但是视频列表那里写着“您没有联网，请检查网络连接。”
> F12的console里有非常多YouTube的资源提示连接已重置
> 切节点不管用 放置在那边过一阵子 大概就是吃顿饭的时间回来 就又正常了
> 其他需要代理的网站都是clash上线就能正常使用的

确实有这问题，看了日志，youtube不走代理，把其他或者落网之鱼改成手动模式，或者自动代理模式，就正常了，然后再改回来（直连或者走代理）

**Comment by paladin4fan** [comment]
> > Redir-Host+Rule模式
> > 每次更新规则或者订阅导致重启clash之后，其他网站都可以正常使用
> > 只有YouTube 在“运行状态”下是链接超时
> > 浏览器访问则是打开YouTube主页 但是视频列表那里写着“您没有联网，请检查网络连接。”
> > F12的console里有非常多YouTube的资源提示连接已重置
> > 切节点不管用 放置在那边过一阵子 大概就是吃顿饭的时间回来 就又正常了
> > 其他需要代理的网站都是clash上线就能正常使用的
> 
> 确实有这问题，看了日志，youtube不走代理，把其他或者落网之鱼改成手动模式，或者自动代理模式，就正常了，然后再改回来（直连或者走代理）

我漏网之鱼开节点也不行诶 照样要等着

**Comment by nameless3721** [comment]
因为没clash核心没sni嗅探全靠dns服务器拿域名 首次启动和重启没映射ip导致拿不了域名 可以自己清dns缓存加重开浏览器解决 控制台里面看得到 youtube googlevideo等域名才是正常的代理 (除非只有geoip cn的规则就请确保你的中国分流是正确的

**Comment by paladin4fan** [comment]
> 因为没clash核心没sni嗅探全靠dns服务器拿域名 首次启动和重启没映射ip导致拿不了域名 可以自己清dns缓存加重开浏览器解决 控制台里面看得到 youtube googlevideo等域名才是正常的代理 (除非只有geoip cn的规则就请确保你的中国分流是正确的

我在链接里看 访问youutbe是已经匹配了走节点的规则 但是 链接已重置的资源也是同个域名下的 就很奇怪

**Comment by matthuo333** [comment]
不但是油管，别的一样。netflix.com   打开后，再curl 或任何海外网站，直接大不开。和DNS有关，找不到原因

**Comment by cian179** [comment]
同样遇到这个问题

**Comment by bowenqiang** [comment]
同样问题。如果用fake-ip模式倒是可以油管视频秒开。但是fake-ip模式下遇到几个问题，1. bt流量不知道怎么不走代理；2. 部分游戏无法正常进入，比如和平精英；3. 百度网盘下载速度好像也有点影响。

**Comment by hpqqph** [comment]
同样问题，链接里面看走的规则和节点也都没错，但是非要等很久或者重启电脑才能上油管。而手机或者平板走wifi的客户端却没问题~

**Comment by bowenqiang** [comment]
我的问题发现了，只要把AdGuard Home关了就好了，视频秒开。可能是我的AdGuard Home DNS设置不是太正确。

**Comment by bluceli0** [comment]
> 问题，链接里面看走的规则和节点也都没错，但非要等国外的或者重启电脑才能上油管。而手机或者平板走wifi的客户端却没问题~

问题解决了吗，兄弟

**Comment by bluceli0** [comment]
> > 问题，链接里面看走的规则和节点也都没错，但非要等国外的而重启电脑才能上油管。手机或者平板走wifi的客户端却没问题~
> 
> 问题解决，兄弟

问题解决了吗

**Comment by bluceli0** [comment]
> 同样问题，链接里面看走的规则和节点也都没错，但是非要等很久或者重启电脑才能上油管。而手机或者平板走wifi的客户端却没问题~
找到问题了把网断了重新连接就行了或者禁用网络然后再重新启用网络希望还有别的办法

**Comment by paladin4fan** [comment]
> > > 问题，链接里面看走的规则和节点也都没错，但非要等国外的而重启电脑才能上油管。手机或者平板走wifi的客户端却没问题~
> > 
> > 
> > 问题解决，兄弟
> 
> 问题解决了吗
我现在用DNSForwarder做上游服务器 测试页面的油管变绿的速度会变快点 但是如果要重启插件后立即打开的话 得清DNS缓存和浏览器缓存

**Comment by bluceli0** [comment]
> > > > 问题，链接里面看走的规则和节点也都没错，但非要等国外的而重启电脑才能上油管。手机或者平板走wifi的客户端却没问题~
> > > 
> > > 
> > > 问题解决，兄弟
> > 
> > 
> > 问题解决了吗
> > 我现在用DNSForwarder做上游服务器 测试页面的油管变绿的速度会变快点 但是如果要重启插件后立即打开的话 得清DNS缓存和浏览器缓存

我直接断网重连，其他的不会，小白一个

**Comment by coolzhi** [comment]
passwall一样问题 ，用了adh
但是就PC浏览器上油管有这个问题，其他都好的
手机确没有问题

**Comment by matthuo333** [comment]
你的youtube 所用节点组 是urltest 或 fallback吧？如果是，应该不单是youtube有这个现象

**Comment by paladin4fan** [comment]
> 你的youtube 所用节点组 是urltest 或 fallback吧？如果是，应该不单是youtube有这个现象

没有 我不用自动节点

**Comment by Johnstfrank** [comment]
我遇到一样的问题，自从1月份以来就不时出现无法打开 Google 和 Youtube 的情况，偶尔能打开，但很不稳定，其他网站则不受影响可以秒开。手机端我用的是 Shadowrocket，所有网站都没有问题

无论是 Global/Rule/Direct 都没有办法

试过了清理 DNS 缓存的建议，没有太多改善。请问有朋友知道解决方法吗？感谢！

**Comment by John8848666** [comment]
其他网站都可以访问，唯独YouTube不能访问。奇怪

**Comment by John8848666** [comment]
> > 其他网站都可以访问，唯独YouTube不能访问。奇怪
> 
> 电脑端禁用网络连接，然后重新启用就行了，这个比较简单点

谢谢！已解决。

我之前用的是https://xmrth.com/提供的clash结点。尝试过dns flush无效果。最后随便换了一个其他的VPN就可以访问了。现在我猜测可能是xmrth提供的结点有问题

**Comment by fxzxmicah** [comment]
我觉得这个问题不是系统DNS缓存的问题，而是浏览器DNS缓存的问题，可以试试`edge://net-internals/#dns`或者`chrome://net-internals/#dns`上的`Clear Host Cache`选项，我还没有严格测试，但是感觉有效。

**Comment by CyEilo** [comment]
关闭"追加上游dns"可能有奇效

**Comment by leverule** [comment]
> 我觉得这个问题不是系统DNS缓存的问题，而是浏览器DNS缓存的问题，可以试试`edge://net-internals/#dns`或者`chrome://net-internals/#dns`上的`Clear Host Cache`选项，我还没有严格测试，但是感觉有效。

确实是这样，感谢！

**Comment by Neverplayed** [comment]
关闭浏览器“使用安全的DNS...."，也许有效，我刚是这样好的，我是EDGE

**Comment by Marscreeper1** [comment]
我也有查不多的问题，我把油猴里的一个youtube的拦截脚本关闭了就好了，可能有人和我一样，可以检查一下脚本
