### ISSUE TITLE
支持openwrt 21.02了吗

### ISSUE THREAD

**Issue by javierzhang0504** [vernesong/OpenClash#1377]
我看马上出21.02了，已经RC1了。
没敢升，不知道是否支持，有人试过没？
大神有没有计划何时支持

**Comment by pillanangel** [comment]
目测至少是依赖项目都已经算是21.02的标配，不像19.07里还需要单独编译或者用snapshot版本的。可以一战。

**Comment by superreyn** [comment]
我用的这个版本OpenWrt 21.02.0-rc1，openclash正常部署使用。

**Comment by read0n1y** [comment]
> 我用的这个版本OpenWrt 21.02.0-rc1，openclash正常部署使用。

然而我报错是这个
/usr/lib/lua/luci/dispatcher.lua:1347: module 'luci.cbi' not found:
	no field package.preload['luci.cbi']
	no file './luci/cbi.lua'
	no file '/usr/share/lua/luci/cbi.lua'
	no file '/usr/share/lua/luci/cbi/init.lua'
	no file '/usr/lib/lua/luci/cbi.lua'
	no file '/usr/lib/lua/luci/cbi/init.lua'
	no file './luci/cbi.so'
	no file '/usr/lib/lua/luci/cbi.so'
	no file '/usr/lib/lua/loadall.so'
	no file './luci.so'
	no file '/usr/lib/lua/luci.so'
	no file '/usr/lib/lua/loadall.so'
stack traceback:
	[C]: in function 'require'
	/usr/lib/lua/luci/dispatcher.lua:1347: in function '_cbi'
	/usr/lib/lua/luci/dispatcher.lua:1024: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:1000: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:479: in function </usr/lib/lua/luci/dispatcher.lua:478>

**Comment by superreyn** [comment]
这是哪里的报错？


我没有注意到这个报错，从你的报错上看提示文件不存在，应该是哪个依赖包没有安装上吧。
/usr/lib/lua/luci/dispatcher.lua:1347: module 'luci.cbi' not found:


在WEB UI里启动的报错？还是在哪个日志文件里的？
















在 2021-05-18 13:59:36，"read0n1y" ***@***.***> 写道：

我用的这个版本OpenWrt 21.02.0-rc1，openclash正常部署使用。

然而我报错是这个
/usr/lib/lua/luci/dispatcher.lua:1347: module 'luci.cbi' not found:
no field package.preload['luci.cbi']
no file './luci/cbi.lua'
no file '/usr/share/lua/luci/cbi.lua'
no file '/usr/share/lua/luci/cbi/init.lua'
no file '/usr/lib/lua/luci/cbi.lua'
no file '/usr/lib/lua/luci/cbi/init.lua'
no file './luci/cbi.so'
no file '/usr/lib/lua/luci/cbi.so'
no file '/usr/lib/lua/loadall.so'
no file './luci.so'
no file '/usr/lib/lua/luci.so'
no file '/usr/lib/lua/loadall.so'
stack traceback:
[C]: in function 'require'
/usr/lib/lua/luci/dispatcher.lua:1347: in function '_cbi'
/usr/lib/lua/luci/dispatcher.lua:1024: in function 'dispatch'
/usr/lib/lua/luci/dispatcher.lua:1000: in function 'dispatch'
/usr/lib/lua/luci/dispatcher.lua:479: in function </usr/lib/lua/luci/dispatcher.lua:478>

**Comment by ZericZhao** [comment]
> 这是哪里的报错？ 我没有注意到这个报错，从你的报错上看提示文件不存在，应该是哪个依赖包没有安装上吧。 /usr/lib/lua/luci/dispatcher.lua:1347: module 'luci.cbi' not found: 在WEB UI里启动的报错？还是在哪个日志文件里的？ 在 2021-05-18 13:59:36，"read0n1y" ***@***.***> 写道： 我用的这个版本OpenWrt 21.02.0-rc1，openclash正常部署使用。 然而我报错是这个 /usr/lib/lua/luci/dispatcher.lua:1347: module 'luci.cbi' not found: no field package.preload['luci.cbi'] no file './luci/cbi.lua' no file '/usr/share/lua/luci/cbi.lua' no file '/usr/share/lua/luci/cbi/init.lua' no file '/usr/lib/lua/luci/cbi.lua' no file '/usr/lib/lua/luci/cbi/init.lua' no file './luci/cbi.so' no file '/usr/lib/lua/luci/cbi.so' no file '/usr/lib/lua/loadall.so' no file './luci.so' no file '/usr/lib/lua/luci.so' no file '/usr/lib/lua/loadall.so' stack traceback: [C]: in function 'require' /usr/lib/lua/luci/dispatcher.lua:1347: in function '_cbi' /usr/lib/lua/luci/dispatcher.lua:1024: in function 'dispatch' /usr/lib/lua/luci/dispatcher.lua:1000: in function 'dispatch' /usr/lib/lua/luci/dispatcher.lua:479: in function </usr/lib/lua/luci/dispatcher.lua:478> — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

这位兄弟没装了luci-compat，我没装luci-compat这是这个报错，装上就正常了

**Comment by miy4mori** [comment]
42.06 我开始也无法打开页面，然后尝试安装luci-compat，21.02-rc3目前安装失败，最后莫名其妙打开了OpenClash页面。一脸问号？

```
root@OpenWrt:~# opkg install luci luci-base luci-compat
Package luci (git-20.074.84698-ead5e81) installed in root is up to date.
Package luci-base (git-21.163.64918-ba57ec5) installed in root is up to date.
Unknown package 'luci-compat'.
Collected errors:
 * opkg_install_cmd: Cannot install package luci-compat.
root@OpenWrt:~# opkg update
Downloading https://downloads.openwrt.org/releases/21.02.0-rc3/targets/ramips/mt                                                                                                                                                       7621/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_core
Downloading https://downloads.openwrt.org/releases/21.02.0-rc3/targets/ramips/mt                                                                                                                                                       7621/packages/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/releases/21.02.0-rc3/packages/mipsel_2                                                                                                                                                       4kc/base/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_base
Downloading https://downloads.openwrt.org/releases/21.02.0-rc3/packages/mipsel_2                                                                                                                                                       4kc/base/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/releases/21.02.0-rc3/packages/mipsel_2                                                                                                                                                       4kc/luci/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_luci
Downloading https://downloads.openwrt.org/releases/21.02.0-rc3/packages/mipsel_2                                                                                                                                                       4kc/luci/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/releases/21.02.0-rc3/packages/mipsel_2                                                                                                                                                       4kc/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_packages
Downloading https://downloads.openwrt.org/releases/21.02.0-rc3/packages/mipsel_2                                                                                                                                                       4kc/packages/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/releases/21.02.0-rc3/packages/mipsel_2                                                                                                                                                       4kc/routing/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_routing
Downloading https://downloads.openwrt.org/releases/21.02.0-rc3/packages/mipsel_2                                                                                                                                                       4kc/routing/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/releases/21.02.0-rc3/packages/mipsel_2                                                                                                                                                       4kc/telephony/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_telephony
Downloading https://downloads.openwrt.org/releases/21.02.0-rc3/packages/mipsel_2                                                                                                                                                       4kc/telephony/Packages.sig
Signature check passed.
root@OpenWrt:~# opkg install luci luci-base luci-compat
Package luci (git-20.074.84698-ead5e81) installed in root is up to date.
Package luci-base (git-21.163.64918-ba57ec5) installed in root is up to date.
Installing luci-compat (git-21.099.45066-7bb2fc4) to root...
Downloading https://downloads.openwrt.org/releases/21.02.0-rc3/packages/mipsel_2                                                                                                                                                       4kc/luci/luci-compat_git-21.099.45066-7bb2fc4_all.ipk
Configuring luci-compat.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency libiwinfo20210430 for luci-                                                                                                                                                       mod-status
```
