### ISSUE TITLE
老毛子用的clash和软件上的出来速度差距大

### ISSUE THREAD

**Issue by qaz492888660** [vernesong/OpenClash#1379]
用老毛子的clash最多跑到1W
电脑软件的clash可以跑到3W6差距很大看不了4K 
用的路由器是红米AC2100
![微信图片_20210508065328](https://user-images.githubusercontent.com/70562018/117515984-5dfc4300-afca-11eb-9e5c-edb6f20eccd8.png)
![微信图片_20210508065338](https://user-images.githubusercontent.com/70562018/117515994-648aba80-afca-11eb-9470-d29da65ab771.png)

**Comment by YukawaMi** [comment]
MTK就那么点性能。。别难为它了

**Comment by YukawaMi** [comment]
MTK就那么点性能。。别难为它了

**Comment by hcym** [comment]
哈哈，一律AP😂

**Comment by ldsoy** [comment]
一个桌面cpu一个一百多块的路由器cpu,这算力没法比啊

**Comment by ldsoy** [comment]
Ac2100当个ap就行了，而且当ap的话，2.4也不太好用

**Comment by zhangj3** [comment]
MTK就那么点性能。。别难为它了🙂
