### ISSUE TITLE
IPIFY 显示是本地服务商ip

### ISSUE THREAD

**Issue by samanhk2** [vernesong/OpenClash#1381]
IPIFY显示本地网络服务商IP，也就是电信的IP，油管不能打开，IP.SB 国外显示正常，部分国外网站可以打开，这是什么原因？

**Comment by lrgcx** [comment]
我这边ipify不显示ip一直显示查询中。奇怪！

**Comment by vernesong** [comment]
跟规则有关，有些配置规则会让IPIFY不走代理，外网不正常考虑dns是否下发正确，另外请提供调试日志

**Comment by wuleidao** [comment]
浏览器去广告插件造成的，把路由地址加入白名单即可

**Comment by wuleidao** [comment]
> 我这边ipify不显示ip一直显示查询中。奇怪！

**Comment by xiaoyaoyuxin** [comment]
> > 我这边ipify不显示ip一直显示查询中。奇怪！
> 
> 浏览器去广告插件造成的，把路由地址加入白名单即可

没想到居然是这个原因，解决了，多谢多谢！
