### ISSUE TITLE
服务器节点能否支持导入？

### ISSUE THREAD

**Issue by fjjking** [vernesong/OpenClash#1384]
不想使用转换的规则所以自己写了规则 但每次机场节点变动都需要更改配置文件上传
所以想使用服务器节点可视化更改比较省事 但是没有SSR://或者vmess://链接导入支持
能添加一个吗？万分感谢orz

**Comment by randyho** [comment]
使用proxy-provider就可以了吧，我就是只用openclash管基本配置，其他都是自己手写的

**Comment by fjjking** [comment]
我现在就是在用proxy-provider但是节点太多了每次机场更新改配置文件确实很麻烦。。

**Comment by vernesong** [comment]
最新版本勾选保留配置，订阅后只会更新节点信息

**Comment by fjjking** [comment]
非常感谢！
