### ISSUE TITLE
libcap and libcap-bin for cpu model: MIPS 1004Kc V2.15 

### ISSUE THREAD

**Issue by UchihaYuki** [vernesong/OpenClash#1389]
openclash version: luci-app-openclash_0.42.05-beta_all.ipk
device: Xiaomi Mi Router 4
cpu model: MIPS 1004Kc V2.15
OPENWRT_RELEASE="OpenWrt 19.07.2 r10947-65030d81f3"

Where can I download libcap and libcap-bin for cpu model "MIPS 1004Kc V2.15"? 

PS: In General Settings, there is no option for MIPS 1004Kc V2.15 as well, which one should I use instead?

**Comment by vernesong** [comment]
Try core which build for mipsle-softfloat, the version showing on the update page if correct core installed.
Download libcap and libcap-bin here https://mirrors.tencent.com/lede/snapshots/packages/mipsel_24kc/base/
