### ISSUE TITLE
编译后打开报错，安装IPK运行的话正常

### ISSUE THREAD

**Issue by dzsjjas** [vernesong/OpenClash#139]
500 内部服务器错误
对不起，服务器遇到未知错误。

/usr/lib/lua/luci/dispatcher.lua:381: Failed to execute function dispatcher target for entry '/admin/services/openclash'.
The called action terminated with an exception:
/usr/lib/lua/luci/dispatcher.lua:381: Failed to execute cbi dispatcher target for entry '/admin/services/openclash/client'.
The called action terminated with an exception:
/usr/lib/lua/luci/template.lua:55: Failed to execute template 'cbi/map'.
A runtime error occured: /usr/lib/lua/luci/template.lua:39: Failed to load template 'openclash/status'.
Error while parsing template '/usr/lib/lua/luci/view/openclash/status.htm':
Syntax error in /usr/lib/lua/luci/view/openclash/status.htm:1: unfinished string near '"'
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:381: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:95: in function

**Comment by vernesong** [comment]
先确认依赖，19.07的需要单独增加

**Comment by dzsjjas** [comment]
> 先确认依赖，19.07的需要单独增加

多谢，有空我再研究研究
