### ISSUE TITLE
OpenClash 能够对设备代理联网并且正常运行，但 OpenClash 和 OpenWrt 自身无法联网。

### ISSUE THREAD

**Issue by wclebb** [vernesong/OpenClash#1390]
首先非常感谢 OpenClash 各位贡献者。

————————

1、OpenClash 目前 （5月30日）v0.42.05-beta 这个版本，在我这里已经花掉了很长时间，主要是 dnsmasq 相关的问题或 「错误：Capsh异常，请尝试重新安装依赖【libcap】和相应的Capsh库，终止启动...」

尝试过此行命令，没用。
opkg remove dnsmasq && opkg install dnsmasq-full

搜了大量的例子和执行相关解决方案，很遗憾，没有一个是有用的。
对于我小白来说，解决这个问题已经花费很长时间。
后来我灵光一闪，没道理新人需要解决这个坑呀？
莫非，是因为版本的问题？

我把版本降级为 v0.42.04-beta ，重装一遍相关的依赖后，再装 OpenClash，然后各种在线无法执行，但只需要上传自己的离线文件后，执行成功。吗的，终于成功了。

2、正如题目说的那样，OpenClash 和 OpenWrt 都无法自身联网。
表现为，OpenWrt 无法通过 网络诊断的「网络工具」
IPv4 Ping 时，Ping 不通任何网络，包括国内，www.qq.com 之类的相关链接。
能 ping 通任何局域网内的设备。
[生成日志.txt](https://github.com/vernesong/OpenClash/files/6566343/default.txt)

OpenClash 各种需要在线执行的，比如 
· GEOIP 数据库
· 版本更新
· Config Update（配置文件订阅）等
均无法联网，需要写入 echo "nameserver 114.114.114.114">/tmp/resolv.conf
能在短暂时间内生效（我就是靠这个成功让 dev、TUN、Game 等执行更新）
但会在几秒后或 OpenClash 执行期间会让它返回到 nameserver 127.0.0.1

自定义上游 DNS 服务器 和 本地 DNS 劫持都有尝试关闭和开启，没有用。
这些虽然无法自身联网，但并不影响我可以在设备上代理流量。

只是我需要让 OpenWrt 和 OpenClash 自身能够联网，而不仅仅可以代理。

3、http://[OpenClash所在 IP]:9090/ui/#/connections 
没有日志记录，没有 连接记录
Yacd 控制面板 能查看日志和流量，但我比较想用 Dashboard 控制面板
是否有什么不对的操作？

4、滚动单条内容最好单独完整的提示。
对于我小白需要查询各种错误的问题来说，这个单条提示错误和其它相关的提示混合在一起很不容易复制和追查问题。需要一瞬间去抓住机会，截图或一秒内从左到右，并 cmd+c……

最好有单独一个记录窗口滚动且不清零的纪录（至少能复制错误的提示并搜索相关的例子会更简单一些）
然后建议提示的部分还是需要完整提示。

5、这些对于小白来说还是稍微有点困难（特别是0.42.05版本貌似有依赖问题）
如果可以，能够提供一键脚本可能会更简单一些。

虽然我后来发现 IPK 貌似自带检测的命令，但部分命令需要手动操作。
比如 OpenClash.sh 内容
检测当前的自身 OpenWrt 版本，opkg update 后然后安装一推所需要的依赖。
再 wget 后安装 ipk 等，这可能会减少一些小白操作步骤的错误。

综上，感谢耐心看到这里。
虽然不影响设备代理，但还是希望能够解决自身无法联网的问题，谢谢。

**Comment by vernesong** [comment]
尝试关一下ipv6，dnsmasq保留一个7874端口的就行了
