### ISSUE TITLE
OpenClash 第三方规则更新失败（请求更新内置规则）

### ISSUE THREAD

**Issue by my5xhni** [vernesong/OpenClash#1391]
open clash 非常好用，但是 最近出现了 第三方内置规则更新失败导致open clash 无法正常启动。
![image](https://user-images.githubusercontent.com/16264838/120354016-b78b2f80-c334-11eb-9d66-7fc8f476a561.png)
![image](https://user-images.githubusercontent.com/16264838/120354092-c376f180-c334-11eb-8fcd-8a27db973488.png)
同时发现目前官方内置的第三方规则年代久远，还容易出错能否肯定各位大佬出手，把订阅规则里面的第三方规则  更新到官方内置规则当中来呢（在线转换存在隐私风险）
![image](https://user-images.githubusercontent.com/16264838/120354526-151f7c00-c335-11eb-8e0b-8174d6532b09.png)
官方内置规则
![image](https://user-images.githubusercontent.com/16264838/120354654-31bbb400-c335-11eb-92e8-cc8787cd1a99.png)

**Comment by vernesong** [comment]
cdn国内访问应该没问题的

**Comment by my5xhni** [comment]
> cdn国内访问应该没问题的

我发帖的前一天和当天 确实 出现了访问异常，现在恢复正常了。  

我还发现了一个问题，不知道是不是因为我是萌新的关系 没找到正确的使用方法，所以还是反馈一下吧。
![Web capture_4-6-2021_181042_192 168 11 44](https://user-images.githubusercontent.com/16264838/120786690-1af9a500-c561-11eb-97c6-73bfb006b110.jpeg)
Game Video 2个策略是我自己DIY的，但是使用一键生成配置文件（混合节点），就会导致自己的DIY的策略被清理掉，只能先用一键生成成功之后，再自己添加自己的策略。

![Web capture_4-6-2021_182125_192 168 11 44](https://user-images.githubusercontent.com/16264838/120787515-04a01900-c562-11eb-8e65-4cefa79b2782.jpeg)

这个是PW的节点添加方式，在不用跳转页面的情况下，批量添加链接本地转换（只需要每个链接各自一行就OK），这个功能对于没有订阅的小朋友来说真的不要太友好。

最后，谢谢大佬的反馈，这个软件真的非常好用。如果还能再便利一点就更好了。
