### ISSUE TITLE
ruby 版本不兼容，导致服务无法正常启动

### ISSUE THREAD

**Issue by luoyuping** [vernesong/OpenClash#1395]
FriendlyWRT 19.07.1, r10911-c155900f66
openclash : 0.42.05-beta
ruby : 2.6.7-1

2021-06-05 18:31:13 OpenClash 【Dev】 Core Update Successful
2021-06-05 18:30:03 Error: Ruby Works Abnormally, Please Check The Ruby Library Depends And Try Again!
2021-06-05 18:29:08 Error: Ruby Works Abnormally, Please Check The Ruby Library Depends And Try Again!
2021-06-05 18:28:18 Error: Config Not Found

**Comment by luoyuping** [comment]
<img width="431" alt="Screen Shot 2021-06-05 at 9 26 10 PM" src="https://user-images.githubusercontent.com/5058548/120893232-c3346a00-c644-11eb-898b-a2df56443452.png">

**Comment by luoyuping** [comment]
root@FriendlyWrt:~# ruby -ryaml -E UTF-8 -e "YAML.load_file('/usr/share/openclash/res/default.yaml')"
Error relocating /usr/lib/libgmp.so.10: __gmp_asprintf_memory: symbol not found
Error relocating /usr/lib/libgmp.so.10: __gmp_asprintf_reps: symbol not found
Segmentation fault

**Comment by leeyeel** [comment]
me too, ruby 3.0.1也会提示ruby依赖问题
```
libruby3.0 - 3.0.0-1
ruby - 3.0.1-1
ruby-bigdecimal - 3.0.1-1
ruby-date - 3.0.1-1
ruby-dbm - 3.0.1-1
ruby-digest - 3.0.1-1
ruby-enc - 3.0.1-1
ruby-forwardable - 3.0.0-1
ruby-pstore - 3.0.0-1
ruby-psych - 3.0.1-1
ruby-stringio - 3.0.1-1
ruby-strscan - 3.0.1-1
ruby-yaml - 3.0.1-1
```

**Comment by fangker** [comment]
同样的问题同样的报错
