### ISSUE TITLE
Clash core的三点建议

### ISSUE THREAD

**Issue by wangxin6** [vernesong/OpenClash#14]
对于 clash core 的三点建议：
1. 把 clash core release 从当前的 OpenClash 转移到单独的 repositories
2. clash core release 编译为 ipk 安装文件 
3. 增加PI的支持。比如：aarch64_cortex-a53_armv8；arm_v7_ras_pi.ipk 等

**Comment by vernesong** [comment]
repositories其实frainzy1477那个就可以了，做不做IPK都是要做安装的步骤，暂时还不会考虑
aarch64_cortex-a53_armv8；arm_v7_ras_pi，这些内核都写了是arm的，你用对应内核就行了
