### ISSUE TITLE
启动openClash后 openvpn无法使用，防火墙的端口转发不起作用，关闭后除了路由器，都不能上网

### ISSUE THREAD

**Issue by windy0220** [vernesong/OpenClash#1401]
1. 启动openClash后， openvpn无法使用，我要连到办公区办公，openvpn始终无法连上
2. DDNS外网访问路由器没问题，但防火墙的端口转发不起作用，导致我连不上内网其他设备
3. 关闭OpenClash后除了路由器，都不能上网

关于第三点，我搜索了issues 说 dns没有删除，但我看我的openClash关闭后 dns转发是正常删除的。然而还是不能正常上网。

**Comment by Airren** [comment]
> 1. 启动openClash后， openvpn无法使用，我要连到办公区办公，openvpn始终无法连上
> 2. DDNS外网访问路由器没问题，但防火墙的端口转发不起作用，导致我连不上内网其他设备
> 3. 关闭OpenClash后除了路由器，都不能上网
> 
> 关于第三点，我搜索了issues 说 dns没有删除，但我看我的openClash关闭后 dns转发是正常删除的。然而还是不能正常上网。

openvpn的问题解决了吗，我最近也遇到了，解决了的话麻烦请教下~
