### ISSUE TITLE
大量同一连接导致连接数暴涨，死循环回环问题

### ISSUE THREAD

**Issue by RunStar99** [vernesong/OpenClash#141]
每次启动时必出现，长时间运行后随机出现。
求教可能导致这种死循环问题形成的原因及修复方式
<img width="1332" alt="截屏2020-02-12上午10 53 51" src="https://user-images.githubusercontent.com/46420475/74299192-e3bd1e80-4d86-11ea-86c1-c2bfd0c02d7e.png">

**Comment by vernesong** [comment]
看下general的配置

**Comment by RunStar99** [comment]
<img width="954" alt="截屏2020-02-13上午11 30 18" src="https://user-images.githubusercontent.com/46420475/74398990-3dd7e580-4e54-11ea-93eb-ee24ffe62d47.png">

**Comment by vernesong** [comment]
尝试在规则最后的`MATCH`前添加以下规则
`- IP-CIDR,198.18.0.1/16,REJECT,no-resolve`

**Comment by zhangzhexx** [comment]
> 尝试在规则最后的`MATCH`前添加以下规则
> `- IP-CIDR,198.18.0.1/16,REJECT,no-resolve`

添加了以上规则，并且已经把openclash升级到v0.36.6-beta，仍然出现大量以下日志：

time="2020-02-16T17:39:03Z" level=info msg="[TCP] 192.168.1.21:50056 --> 198.18.0.102 match IPCIDR using REJECT"
time="2020-02-16T17:39:04Z" level=info msg="[TCP] 192.168.1.21:50057 --> 198.18.0.102 match IPCIDR using REJECT"
time="2020-02-16T17:39:04Z" level=info msg="[TCP] 192.168.1.21:50058 --> 198.18.0.102 match IPCIDR using REJECT"
time="2020-02-16T17:39:05Z" level=info msg="[TCP] 192.168.1.21:50059 --> 198.18.0.102 match IPCIDR using REJECT"
time="2020-02-16T17:39:05Z" level=info msg="[TCP] 192.168.1.21:50060 --> 198.18.0.102 match IPCIDR using REJECT"
time="2020-02-16T17:39:06Z" level=info msg="[TCP] 192.168.1.21:50061 --> 198.18.0.102 match IPCIDR using REJECT"
time="2020-02-16T17:39:06Z" level=info msg="[TCP] 192.168.1.21:50062 --> 198.18.0.102 match IPCIDR using REJECT"
time="2020-02-16T17:39:07Z" level=info msg="[TCP] 192.168.1.21:50063 --> 198.18.0.102 match IPCIDR using REJECT"
time="2020-02-16T17:39:07Z" level=info msg="[TCP] 192.168.1.21:50065 --> 198.18.0.102 match IPCIDR using REJECT"
time="2020-02-16T17:39:08Z" level=info msg="[TCP] 192.168.1.21:50066 --> 198.18.0.102 match IPCIDR using REJECT"
time="2020-02-16T17:39:08Z" level=info msg="[TCP] 192.168.1.21:50067 --> 198.18.0.102 match IPCIDR using REJECT"
time="2020-02-16T17:39:09Z" level=info msg="[TCP] 192.168.1.21:50068 --> 198.18.0.102 match IPCIDR using REJECT"
time="2020-02-16T17:39:09Z" level=info msg="[TCP] 192.168.1.21:50069 --> 198.18.0.102 match IPCIDR using REJECT"
time="2020-02-16T17:39:10Z" level=info msg="[TCP] 192.168.1.21:50070 --> 198.18.0.102 match IPCIDR using REJECT"
