### ISSUE TITLE
5.10内核OpenWrt opkg install报错

### ISSUE THREAD

**Issue by yjh1996** [vernesong/OpenClash#1412]
![QQ截图20210620172352](https://user-images.githubusercontent.com/11804775/122668804-74fa9b80-d1ec-11eb-8095-51f754eb66ea.png)
![QQ截图20210620172404](https://user-images.githubusercontent.com/11804775/122668805-762bc880-d1ec-11eb-8206-4d2cbbafbf81.png)

使用5.10内核的Openwrt 安装OpenClash报错

**Comment by zhangj3** [comment]
编译openwrt的时候选上Openclash，没有问题，先用这种办法吧。。。

**Comment by zhouxiaolong920** [comment]
实话实说
人家作者是修改openclash的 bug 

pkg install 安装不上。。。和openclash无关吧，我要是作者。我肯定无语。
