### ISSUE TITLE
自定义规则配置错误之后好像clash了，连带着passwall都打不开

### ISSUE THREAD

**Issue by Easy1999** [vernesong/OpenClash#1417]
![image](https://user-images.githubusercontent.com/42054399/123262387-6680ec80-d52a-11eb-8643-d0db9765ab1a.png)
注意这里是全局设置，什么都没有了

![image](https://user-images.githubusercontent.com/42054399/123262480-80223400-d52a-11eb-8cbf-993643e42393.png)
连带passwall也变成了这个样子

**Comment by liofoil** [comment]
我之前也遇到过，而且网页后台都打不开，最方便的方法是重刷。。

**Comment by Easy1999** [comment]
> 我之前也遇到过，而且网页后台都打不开，最方便的方法是重刷。。

嗯嗯，我也重装了，只是来提个issue,希望能修复

**Comment by vernesong** [comment]
怎么复现
