### ISSUE TITLE
特定IP的特定端口绕过openclash

### ISSUE THREAD

**Issue by kevinfrancisjiang** [vernesong/OpenClash#1419]
各位大佬，由于使用nas进行PT，如何使nas的pt流量绕过代理，其他按规则来，比如qb/TR软件的端口进行直连。
如果使用‘- SRC-IP-CIDR,192.168.3.230/32,DIRECT’，就是全部直连了。

谢谢

**Comment by vernesong** [comment]
```
redir模式下,插件启动后执行
iptables -t mangle -I openclash -p udp -s 192.168.3.230 --sport 12345 -j RETURN
iptables -t nat -I openclash -p tcp -s 192.168.3.230 --sport 12345 -j RETURN
```
所有模式
用规则SRC-PORT,7777,DIRECT

**Comment by sunr1s6** [comment]
> ```
> redir模式下,插件启动后执行
> iptables -t mangle -I openclash -p udp -s 192.168.3.230 --sport 12345 -j RETURN
> iptables -t nat -I openclash -p tcp -s 192.168.3.230 --sport 12345 -j RETURN
> ```
> 
> 所有模式 用规则SRC-PORT,7777,DIRECT

请教下，这个命令是在openwrt的防火墙自定义规则里面添加吗？
