### ISSUE TITLE
能否增加路由器自身流量不经过clash的功能？

### ISSUE THREAD

**Issue by InsOnYou** [vernesong/OpenClash#1425]
目前clash会代理路由器自身的流量，容易发生自身回环流量爆炸的问题，还容易和路由器其他插件冲突。这个问题可以通过防火墙规则解决吗？

**Comment by vernesong** [comment]
流量回环建议绑定接口

**Comment by zane-ng** [comment]
在`全局设置`-`规则设置`当中有写明：

```
##此时IP为192.168.1.1和192.168.1.201的客户端流量走代理（策略），其余客户端不走代理
##因为Fake-IP模式下，IP地址为192.168.1.1的路由器自身流量可走代理（策略），所以需要排除

##仅设置路由器自身直连：
##- SRC-IP-CIDR,192.168.1.1/32,DIRECT
##- SRC-IP-CIDR,198.18.0.1/32,DIRECT
```
不知道是不是你想要的功能？

**Comment by InsOnYou** [comment]
自定义规则SRC-IP-CIDR只能设置直连，，流量还是会经过内核。似乎在防火墙里添加“iptables -t nat -A openclash -d 192.168.1.1/16 -j RETURN”就可以防止流量进入clash
