### ISSUE TITLE
开启游戏模式后，append上去的游戏规则和某些yaml格式不兼容

### ISSUE THREAD

**Issue by HoldOnBro** [vernesong/OpenClash#143]
![image](https://user-images.githubusercontent.com/16101088/74336467-43441a00-4dd9-11ea-89c6-96b7ed723097.png)
如图，subconverter生成的标准yaml格式文件对规则进行了两个空格的缩进，但是append上去的游戏规则没有相应的缩进，导致openclash对新生成的yaml文件加载失败

**Comment by HoldOnBro** [comment]
大佬考虑适配一下么

**Comment by HoldOnBro** [comment]
经测试，原本的规则有缩进的话，附加的游戏规则也缩进就行，如果原本的规则是没缩进的，那附加的游戏规则就保持现在的不缩进就行。

**Comment by vernesong** [comment]
https://github.com/vernesong/OpenClash/blob/4f99ceca855eee163d0f72628282d63704cb47cd/luci-app-openclash/files/usr/share/openclash/yml_rules_change.sh#L129
测试下这个命令是否生效

**Comment by HoldOnBro** [comment]
> https://github.com/vernesong/OpenClash/blob/4f99ceca855eee163d0f72628282d63704cb47cd/luci-app-openclash/files/usr/share/openclash/yml_rules_change.sh#L129
> 
> 
> 测试下这个命令是否生效

有效，原文件的缩进被删了。
https://github.com/vernesong/OpenClash/blob/7098a5085bee36806c8bd7c5c1ee3b682f29bb0f/luci-app-openclash/files/etc/init.d/openclash#L525
要是能在这里加个对前面规则是否缩进的判断，然后再写(缩进/不缩进)的游戏节点就好了。

**Comment by vernesong** [comment]
知道了，我加个判断就好
