### ISSUE TITLE
莫名其妙的自定义规则失效

### ISSUE THREAD

**Issue by MeowRay** [vernesong/OpenClash#1431]
手动添加了个服务器节点（然后又删了），后无论怎么样，自定义规则都完全失效了，

![QQ截图20210630004209](https://user-images.githubusercontent.com/29674595/123836341-2e1f4b00-d93c-11eb-99ed-7f8cc5ec553e.jpg)

![QQ截图20210630004219](https://user-images.githubusercontent.com/29674595/123836332-2bbcf100-d93c-11eb-972b-1cf36fd64227.jpg)

**Comment by vernesong** [comment]
日志

**Comment by kingzhong123** [comment]
我的更新了v0.42.06-beta后也是这样，提示
2021-06-30 12:16:57 Set Custom Rules Error: (/etc/openclash/custom/openclash_custom_rules.list): did not find expected '-' indicator while parsing a block collection at line 33 column 4
这个错误，实际上是有'-' 的，但是还是这样提示

**Comment by vernesong** [comment]
不应该，你最好删除重新写一遍

**Comment by MeowRay** [comment]
> 不应该，你最好删除重新写一遍

找到问题了，是SRC-IP的规则匹配不到导致失效，必须SRC-IP-CIDR XX/32才行，单IP的话有点不人性化。。建议加个匹配，还有在主控制台提示有错误，
还有FAKE-IP模式下作为二级路由会导致外网端口映射失效
