### ISSUE TITLE
关于openclash，想咨询一下逻辑和问题，求知道的回复一下

### ISSUE THREAD

**Issue by zhouxiaolong920** [vernesong/OpenClash#1434]
1. 开启ipv6之后，如油管，dns同时返回了ipv4和ipv6，openclash到底是用哪个连接呢？配置上，是否能自行配置，无论 ipv4还是v6，都可以走规则？
2. 关于dns解析。所有的dns解析。好像clash都会接管。它怎么知道某个站点是国内？还是国外？（有些站点，国内外都有），总得向哪个dns地址去查询，？走国外的dns，查国内的慢，而且向taobao之类的，国内外都有。
    2.1 这个问题的疑问是，如果运营商dns返回一个被污染的ip，在china_route_ip列表里面没有，openclash开始走代理，那么，肯定是走不通的啊。
    2.2 我要是权威机构，我强制让，各大运营商，阿里，腾讯，你们能用到的dns,全部污染（国外域名），查询到的ip地址都是错误的啊，国内dns查询，国外域名有意义吗？
    2.3 难道只能配置静态白名单，某个特定域名走直连，非特定域名（国外），只能走国外dns。

**Comment by vernesong** [comment]
规则里指明需要代理的都是服务器解析，未指明的代理走fallback，直连走nameserver
ipv6不代理，只负责解析dns

**Comment by zhouxiaolong920** [comment]
我去lede大神，竟然回复我了。。。

@vernesong 感谢，理解了。

**Comment by zhouxiaolong920** [comment]
大神竟然回复我了。。。

@vernesong 感谢，理解了。
