### ISSUE TITLE
期待更新支持trojan-go

### ISSUE THREAD

**Issue by garywu520** [vernesong/OpenClash#1436]
期待更新支持trojan-go, 如：支持CDN，shadowsocks aes加密设定

**Comment by vernesong** [comment]
https://github.com/ClashDotNetFramework/experimental-clash/releases

**Comment by OleStore** [comment]
居然支持vless 

> https://github.com/ClashDotNetFramework/experimental-clash/releases

**Comment by 70599** [comment]
> 居然支持vless
> 
> > https://github.com/ClashDotNetFramework/experimental-clash/releases

请问这个core怎么在本项目中使用？
