### ISSUE TITLE
【0.42.06 BUG】切换配置文件后，并不能启用，用的还是原来的配置文件，需要重新启动clash才可以

### ISSUE THREAD

**Issue by icucuio** [vernesong/OpenClash#1437]
如题
我遇到一个问题，就是切换配置文件不起作用

**Comment by vernesong** [comment]
切换完必须重启才能完成内核调用

**Comment by icucuio** [comment]
> 切换完必须重启才能完成内核调用

之前好像不需要啊？切换完自动就切换了，而且我看他的走的步骤就是在重启啊clash啊。
搞不懂，从什么版本开始编程需要重启的了。

**Comment by vernesong** [comment]
一直是这样的，还要应用，走一遍配置文件修改，不然内核不会生效，只会显示切换到了其他配置文件
