### ISSUE TITLE
OpenClash 启动成功，检测到您启用了IPV6的DHCP服务，可能会造成连接异常！

### ISSUE THREAD

**Issue by bb2** [vernesong/OpenClash#1438]
已经关了 网络-接口 里的 IPV6的DHCP服务，在其它设备上也没有接收到IPV6的DHCP信息，还是会在启动OpenClash时提示这个。

**Comment by vernesong** [comment]
上网正常不管就行了

**Comment by bb2** [comment]
👌

**Comment by bb2** [comment]
顺带一问，这是固定提示吗？好像去不掉

**Comment by MBRjun** [comment]
只要你开了IPv6就有这个警告 能正常上网就忽略掉这个

**Comment by MBRjun** [comment]
如果你没有IPv6（运营商不给你地址）就关了相关服务

**Comment by renjieQ** [comment]
已解决。请参考：
在openwrt中找到 network > interface > LAN edit > DHCP Server > IPV6 全部停用即可停用 LAN接口的服务， 如果存在多个LAN接口，则可能需要每一个接口都设置一下。
