### ISSUE TITLE
TUN模式下开启DNS劫持后DNS响应没有修改来源ip

### ISSUE THREAD

**Issue by bb2** [vernesong/OpenClash#1441]
nslookup www.baidu.com 8.8.8.8
;; reply from unexpected source: [我的内网ip]#58073, expected 8.8.8.8#53
;; reply from unexpected source: [我的内网ip]#58073, expected 8.8.8.8#53
;; reply from unexpected source: [我的内网ip]#58073, expected 8.8.8.8#53
;; connection timed out; no servers could be reached

因为劫持后响应没有修改来源ip导致nslookup解析失败，为什么，这是BUG还是特性。
这样的话如果某些Google App使用8.8.8.8解析时像nslookup一样严格验证，拒绝非指定DNS响应不是就没法劫持了吗。

**Comment by vernesong** [comment]
如何复现？我这边正常返回8.8.8.8的结果
