### ISSUE TITLE
无法正常科学上网

### ISSUE THREAD

**Issue by hackmln** [vernesong/OpenClash#1443]
我的openclash设置后能上youtube网页 但是放不了视频  Google也上不了  TG网站进不去  APP可以进去 不知道哪里出问题了 求大神指点 第一次用
<a href="https://imgtu.com/i/RcHnBD"><img src="https://z3.ax1x.com/2021/07/02/RcHnBD.jpg" alt="RcHnBD.jpg" border="0"></a>
<a href="https://imgtu.com/i/RcHZjK"><img src="https://z3.ax1x.com/2021/07/02/RcHZjK.jpg" alt="RcHZjK.jpg" border="0"></a>
<a href="https://imgtu.com/i/RcHVc6"><img src="https://z3.ax1x.com/2021/07/02/RcHVc6.jpg" alt="RcHVc6.jpg" border="0"></a>
<a href="https://imgtu.com/i/RcHmnO"><img src="https://z3.ax1x.com/2021/07/02/RcHmnO.jpg" alt="RcHmnO.jpg" border="0"></a>
<a href="https://imgtu.com/i/RcHuHe"><img src="https://z3.ax1x.com/2021/07/02/RcHuHe.jpg" alt="RcHuHe.jpg" border="0"></a>
<a href="https://imgtu.com/i/RcHMAH"><img src="https://z3.ax1x.com/2021/07/02/RcHMAH.jpg" alt="RcHMAH.jpg" border="0"></a>

**Comment by zane-ng** [comment]
1. 规则是否设置正确
2. 是否将设备的 DNS 指向 OpenClash 所在的设备
3. 以及检查一下 DNS 解析是否存在问题

**Comment by vernesong** [comment]
设备指定路由地址dns，不要开其他dns加速、解析插件
