### ISSUE TITLE
向Cloudflare CDN节点发起的vmess+wss访问会触发reset by peer

### ISSUE THREAD

**Issue by sswsproject** [vernesong/OpenClash#1444]
请参考 https://github.com/Dreamacro/clash/issues/1468 

打开openclash 后，cf相关地址的访问立刻被阻断，关闭openclash后，隔一会，原有阻断会恢复到能够访问。

**Comment by zgc** [comment]
同样的问题，但是属于内核的问题吧？

**Comment by sswsproject** [comment]
> 同样的问题，但是属于内核的问题吧？

是内核问题，但因为此项目直接使用了clash core，所以也是受影响的。所以开个issue可以跟踪一下。

**Comment by OleStore** [comment]
> > 同样的问题，但是属于内核的问题吧？
> 
> 是内核问题，但因为此项目直接使用了clash core，所以也是受影响的。所以开个issue可以跟踪一下。

官方内核更新了

**Comment by sswsproject** [comment]
clash core已修复#1468

**Comment by zgc** [comment]
我直接换成grpc了,一样可以套cf
