### ISSUE TITLE
[Bug]由Clash内核向Cloudflare CDN节点发起的vmess+wss访问会触发ban ip

### ISSUE THREAD

**Issue by Aaron-lv** [vernesong/OpenClash#1446]
https://github.com/Dreamacro/clash/issues/1468

**Comment by Aaron-lv** [comment]
https://github.com/Dreamacro/clash/commit/995aa7a8fc641fa00b44ad290ac59c3e4c2a565f

已修复，希望可以同步修复，谢谢

**Comment by Aaron-lv** [comment]
https://github.com/Dreamacro/clash/releases/tag/v1.6.5

**Comment by zgc** [comment]
直接换grpc吧，实测grpc好很多，也支持套cf

**Comment by Aaron-lv** [comment]
> 直接换grpc吧，实测grpc好很多，也支持套cf

暂时用Clash项目内核了

**Comment by zgc** [comment]
clash本身就支持grpc

**Comment by Aaron-lv** [comment]
https://github.com/vernesong/OpenClash/commit/0d84cc6cdd069bd98a80e0acf89f37954b198154

已修复
