### ISSUE TITLE
可以上网，但DOMAIN-SUFFIX 规则没有命中。

### ISSUE THREAD

**Issue by yhucao** [vernesong/OpenClash#1449]
调试日志如下：
#===================== 系统信息 =====================#

主机型号: Intel(R) Celeron(R) CPU N3150 @ 1.60GHz : 4 Core 4 Thread
固件版本: OpenWrt SPP v6-1[2021]
LuCI版本: git-21.114.56541-974fb04-1
内核版本: 5.4.122
处理器架构: x86_64

#此项在使用Tun模式时应为ACCEPT
防火墙转发: ACCEPT

#此项有值时建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: 

#此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 127.0.0.1#7874

#===================== 依赖检查 =====================#

dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
jsonfilter: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
iptables-mod-tproxy: 已安装
kmod-ipt-tproxy: 已安装
iptables-mod-extra: 已安装
kmod-ipt-extra: 已安装
libcap: 已安装
libcap-bin: 已安装
ruby: 已安装
ruby-yaml: 已安装
ruby-psych: 已安装
ruby-pstore: 已安装
ruby-dbm: 已安装
kmod-tun(TUN模式): 已安装
luci-compat(Luci-19.07): 已安装

#===================== 内核检查 =====================#

运行状态: 运行中
进程pid: 10768
运行权限: 10768: = cap_dac_override,cap_net_bind_service,cap_net_admin,cap_net_raw,cap_sys_resource+eip
运行用户: nobody
已选择的架构: linux-amd64

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 2021.05.08
Tun内核文件: 存在
Tun内核运行权限: 正常

Game内核版本: 20210310-63-gb2bbdf5
Game内核文件: 存在
Game内核运行权限: 正常

Dev内核版本: v1.6.0-12-gc35cb24
Dev内核文件: 存在
Dev内核运行权限: 正常

#===================== 插件设置 =====================#

当前配置文件: /etc/openclash/config/MyConfig2.yaml
启动配置文件: /etc/openclash/MyConfig2.yaml
运行模式: fake-ip
默认代理模式: rule
UDP流量转发(tproxy): 启用
DNS劫持: 启用
自定义DNS: 启用
IPV6-DNS解析: 停用
禁用Dnsmasq缓存: 停用
自定义规则: 停用
仅允许内网: 停用
仅代理命中规则流量: 停用
仅允许常用端口流量: 停用
绕过中国大陆IP: 停用

#启动异常时建议关闭此项后重试
混合节点: 停用
保留配置: 停用

#启动异常时建议关闭此项后重试
第三方规则: 停用

#===================== 配置文件 =====================#

port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: error
external-controller: 0.0.0.0:9090
proxies:
proxy-groups:
rules:
 - PROCESS-NAME,fdm,DIRECT,DIRECT
 - DOMAIN-SUFFIX,ipaddress.com,🌑Proxy
 - GEOIP,CN,🌐Direct
 - DOMAIN-SUFFIX,bilibili.com,🌐Direct
 - MATCH,,🧭Final,dns-failed
dns:
  nameserver:
  - 180.168.255.118
  - 202.96.209.5
  - 119.28.28.28
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  listen: 127.0.0.1:7874
  fake-ip-filter:
  - "*.lan"
  - time.windows.com
  - time.nist.gov
  - time.apple.com
  - time.asia.apple.com
  - "*.ntp.org.cn"
  - "*.openwrt.pool.ntp.org"
  - time1.cloud.tencent.com
  - time.ustc.edu.cn
  - pool.ntp.org
  - ntp.ubuntu.com
  - ntp.aliyun.com
  - ntp1.aliyun.com
  - ntp2.aliyun.com
  - ntp3.aliyun.com
  - ntp4.aliyun.com
  - ntp5.aliyun.com
  - ntp6.aliyun.com
  - ntp7.aliyun.com
  - time1.aliyun.com
  - time2.aliyun.com
  - time3.aliyun.com
  - time4.aliyun.com
  - time5.aliyun.com
  - time6.aliyun.com
  - time7.aliyun.com
  - "*.time.edu.cn"
  - time1.apple.com
  - time2.apple.com
  - time3.apple.com
  - time4.apple.com
  - time5.apple.com
  - time6.apple.com
  - time7.apple.com
  - time1.google.com
  - time2.google.com
  - time3.google.com
  - time4.google.com
  - music.163.com
  - "*.music.163.com"
  - "*.126.net"
  - musicapi.taihe.com
  - music.taihe.com
  - songsearch.kugou.com
  - trackercdn.kugou.com
  - "*.kuwo.cn"
  - api-jooxtt.sanook.com
  - api.joox.com
  - joox.com
  - y.qq.com
  - "*.y.qq.com"
  - streamoc.music.tc.qq.com
  - mobileoc.music.tc.qq.com
  - isure.stream.qqmusic.qq.com
  - dl.stream.qqmusic.qq.com
  - aqqmusic.tc.qq.com
  - amobile.music.tc.qq.com
  - "*.xiami.com"
  - "*.music.migu.cn"
  - music.migu.cn
  - "*.msftconnecttest.com"
  - "*.msftncsi.com"
  - localhost.ptlogin2.qq.com
  - "+.srv.nintendo.net"
  - "+.stun.playstation.net"
  - xbox.*.microsoft.com
  - "+.xboxlive.com"
  - proxy.golang.org
  - stun.*.*
  - stun.*.*.*
  - heartbeat.belkin.com
  - "*.linksys.com"
  - "*.linksyssmartwifi.com"
  - "+.battlenet.com.cn"
redir-port: 7892
mixed-port: 7893
bind-address: "*"
external-ui: "/usr/share/openclash/dashboard"
ipv6: false
profile:
  store-selected: true

#===================== 防火墙设置 =====================#

#NAT chain

*nat
:PREROUTING ACCEPT [93:10987]
:INPUT ACCEPT [141:14064]
:OUTPUT ACCEPT [110:7815]
:POSTROUTING ACCEPT [164:11055]
:MINIUPNPD - [0:0]
:MINIUPNPD-POSTROUTING - [0:0]
:openclash - [0:0]
:openclash_output - [0:0]
:postrouting_lan_rule - [0:0]
:postrouting_rule - [0:0]
:postrouting_vpn_rule - [0:0]
:postrouting_wan_rule - [0:0]
:prerouting_lan_rule - [0:0]
:prerouting_rule - [0:0]
:prerouting_vpn_rule - [0:0]
:prerouting_wan_rule - [0:0]
:zone_lan_postrouting - [0:0]
:zone_lan_prerouting - [0:0]
:zone_vpn_postrouting - [0:0]
:zone_vpn_prerouting - [0:0]
:zone_wan_postrouting - [0:0]
:zone_wan_prerouting - [0:0]
-A PREROUTING -d 8.8.4.4/32 -p tcp -m tcp --dport 53 -j REDIRECT --to-ports 7892
-A PREROUTING -d 8.8.8.8/32 -p tcp -m tcp --dport 53 -j REDIRECT --to-ports 7892
-A PREROUTING -p udp -m udp --dport 53 -j REDIRECT --to-ports 53
-A PREROUTING -p tcp -m tcp --dport 53 -j REDIRECT --to-ports 53
-A PREROUTING -m comment --comment "!fw3: Custom prerouting rule chain" -j prerouting_rule
-A PREROUTING -i br-lan -m comment --comment "!fw3" -j zone_lan_prerouting
-A PREROUTING -i eth1 -m comment --comment "!fw3" -j zone_wan_prerouting
-A PREROUTING -i tun0 -m comment --comment "!fw3" -j zone_vpn_prerouting
-A PREROUTING -p udp -m udp --dport 53 -m comment --comment dns_hijack -j REDIRECT --to-ports 1053
-A PREROUTING -p tcp -m tcp --dport 53 -m comment --comment dns_hijack -j REDIRECT --to-ports 1053
-A PREROUTING -p tcp -j openclash
-A OUTPUT -j openclash_output
-A POSTROUTING -m comment --comment "!fw3: Custom postrouting rule chain" -j postrouting_rule
-A POSTROUTING -o br-lan -m comment --comment "!fw3" -j zone_lan_postrouting
-A POSTROUTING -o eth1 -m comment --comment "!fw3" -j zone_wan_postrouting
-A POSTROUTING -o tun0 -m comment --comment "!fw3" -j zone_vpn_postrouting
-A openclash -m set --match-set localnetwork dst -j RETURN
-A openclash -p tcp -j REDIRECT --to-ports 7892
-A openclash_output -p tcp -m tcp --sport 1688 -j RETURN
-A openclash_output -p tcp -m tcp --sport 1194 -j RETURN
-A openclash_output -m set --match-set localnetwork dst -j RETURN
-A openclash_output -d 198.18.0.0/16 -p tcp -m owner ! --uid-owner 65534 -j REDIRECT --to-ports 7892
-A openclash_output -p tcp -m owner ! --uid-owner 65534 -j REDIRECT --to-ports 7892
-A zone_lan_postrouting -j MINIUPNPD-POSTROUTING
-A zone_lan_postrouting -m comment --comment "!fw3: Custom lan postrouting rule chain" -j postrouting_lan_rule
-A zone_lan_prerouting -j MINIUPNPD
-A zone_lan_prerouting -m comment --comment "!fw3: Custom lan prerouting rule chain" -j prerouting_lan_rule
-A zone_vpn_postrouting -m comment --comment "!fw3: Custom vpn postrouting rule chain" -j postrouting_vpn_rule
-A zone_vpn_postrouting -m comment --comment "!fw3" -j FULLCONENAT
-A zone_vpn_prerouting -m comment --comment "!fw3: Custom vpn prerouting rule chain" -j prerouting_vpn_rule
-A zone_vpn_prerouting -m comment --comment "!fw3" -j FULLCONENAT
-A zone_wan_postrouting -m comment --comment "!fw3: Custom wan postrouting rule chain" -j postrouting_wan_rule
-A zone_wan_postrouting -m comment --comment "!fw3" -j FULLCONENAT
-A zone_wan_prerouting -m comment --comment "!fw3: Custom wan prerouting rule chain" -j prerouting_wan_rule
-A zone_wan_prerouting -m comment --comment "!fw3" -j FULLCONENAT
COMMIT

#Mangle chain

*mangle
:PREROUTING ACCEPT [4818:8395736]
:INPUT ACCEPT [4752:8386284]
:FORWARD ACCEPT [62:9486]
:OUTPUT ACCEPT [4563:8717099]
:POSTROUTING ACCEPT [4628:8726681]
:RRDIPT_FORWARD - [0:0]
:RRDIPT_INPUT - [0:0]
:RRDIPT_OUTPUT - [0:0]
:openclash - [0:0]
-A PREROUTING -p udp -j openclash
-A INPUT -j RRDIPT_INPUT
-A FORWARD -j RRDIPT_FORWARD
-A FORWARD -o eth1 -p tcp -m tcp --tcp-flags SYN,RST SYN -m comment --comment "!fw3: Zone wan MTU fixing" -j TCPMSS --clamp-mss-to-pmtu
-A OUTPUT -j RRDIPT_OUTPUT
-A RRDIPT_FORWARD -s 192.168.1.105/32 -j RETURN
-A RRDIPT_FORWARD -d 192.168.1.105/32 -j RETURN
-A RRDIPT_FORWARD -s 192.168.1.121/32 -j RETURN
-A RRDIPT_FORWARD -d 192.168.1.121/32 -j RETURN
-A RRDIPT_FORWARD -s 192.168.1.135/32 -j RETURN
-A RRDIPT_FORWARD -d 192.168.1.135/32 -j RETURN
-A RRDIPT_FORWARD -s 192.168.1.1/32 -j RETURN
-A RRDIPT_FORWARD -d 192.168.1.1/32 -j RETURN
-A RRDIPT_FORWARD -s 192.168.1.163/32 -j RETURN
-A RRDIPT_FORWARD -d 192.168.1.163/32 -j RETURN
-A RRDIPT_FORWARD -s 192.168.1.166/32 -j RETURN
-A RRDIPT_FORWARD -d 192.168.1.166/32 -j RETURN
-A RRDIPT_FORWARD -s 192.168.1.182/32 -j RETURN
-A RRDIPT_FORWARD -d 192.168.1.182/32 -j RETURN
-A RRDIPT_FORWARD -s 192.168.1.198/32 -j RETURN
-A RRDIPT_FORWARD -d 192.168.1.198/32 -j RETURN
-A RRDIPT_FORWARD -s 169.254.105.193/32 -j RETURN
-A RRDIPT_FORWARD -d 169.254.105.193/32 -j RETURN
-A RRDIPT_INPUT -i eth0 -j RETURN
-A RRDIPT_OUTPUT -o eth0 -j RETURN
-A openclash -p udp -m udp --dport 1194 -j RETURN
-A openclash -p udp -m udp --dport 4500 -j RETURN
-A openclash -p udp -m udp --dport 500 -j RETURN
-A openclash -p udp -m udp --dport 500 -j RETURN
-A openclash -p udp -m udp --dport 546 -j RETURN
-A openclash -p udp -m udp --dport 68 -j RETURN
-A openclash -m set --match-set localnetwork dst -j RETURN
-A openclash -p udp -m udp --dport 53 -j RETURN
-A openclash -p udp -j TPROXY --on-port 7892 --on-ip 0.0.0.0 --tproxy-mark 0x162/0xffffffff
COMMIT

#===================== IPSET状态 =====================#

Name: music
Name: localnetwork
Name: shuntlist
Name: gfwlist
Name: chnroute
Name: blacklist
Name: shuntlist6
Name: gfwlist6
Name: chnroute6
Name: blacklist6

#===================== 路由表状态 =====================#

#route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.1.1     0.0.0.0         UG    0      0        0 br-lan
192.168.1.0     0.0.0.0         255.255.255.0   U     0      0        0 br-lan
#ip route list
default via 192.168.1.1 dev br-lan proto static 
192.168.1.0/24 dev br-lan proto kernel scope link src 192.168.1.3 
#ip rule show
0:	from all lookup local
32765:	from all fwmark 0x162 lookup 354
32766:	from all lookup main
32767:	from all lookup default

#===================== 端口占用状态 =====================#

tcp        0      0 :::9090                 :::*                    LISTEN      10768/clash
tcp        0      0 :::7890                 :::*                    LISTEN      10768/clash
tcp        0      0 :::7891                 :::*                    LISTEN      10768/clash
tcp        0      0 :::7892                 :::*                    LISTEN      10768/clash
tcp        0      0 :::7893                 :::*                    LISTEN      10768/clash
udp        0      0 127.0.0.1:7874          0.0.0.0:*                           10768/clash
udp        0      0 :::39071                :::*                                10768/clash
udp        0      0 :::46639                :::*                                10768/clash
udp        0      0 :::7891                 :::*                                10768/clash
udp        0      0 :::7892                 :::*                                10768/clash
udp        0      0 :::7893                 :::*                                10768/clash

#===================== 测试本机DNS查询 =====================#

Server:		127.0.0.1
Address:	127.0.0.1#53

Non-authoritative answer:
www.baidu.com	canonical name = www.a.shifen.com.
Name:	www.a.shifen.com
Address: 180.101.49.11
Name:	www.a.shifen.com
Address: 180.101.49.12

#===================== 测试本机网络连接 =====================#

HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: private, no-cache, no-store, proxy-revalidate, no-transform
Connection: keep-alive
Content-Length: 277
Content-Type: text/html
Date: Mon, 05 Jul 2021 00:10:23 GMT
Etag: "575e1f60-115"
Last-Modified: Mon, 13 Jun 2016 02:50:08 GMT
Pragma: no-cache
Server: bfe/1.0.8.18

#===================== 测试本机网络下载 =====================#

#===================== 最近运行日志 =====================#

2021-07-05 08:09:47 Because of No Rules Field, Stop Setting BT/P2P DIRECT Rules!
time="2021-07-05T00:09:52Z" level=info msg="Start initial compatible provider 🌑Proxy"
time="2021-07-05T00:09:52Z" level=info msg="Start initial compatible provider 🧭Final"
time="2021-07-05T00:09:52Z" level=info msg="Start initial compatible provider 🌐Direct"
time="2021-07-05T00:09:52Z" level=info msg="Start initial compatible provider ⛔️Reject"
2021-07-05 08:09:56 Groups History:【MyConfig2.yaml】 Restore Successful
2021-07-05 08:09:43 OpenClash Start Successful

情况描述：

可以上网，但自己写的域名规则始终不生效，查看Dashboard 中的连接看到所有流量不是走到了GEOIP,CN，就是匹配到了最后的Match，DOMAIN-SUFFIX规则无论直连还是代理都没有命中。而且连接中的域名列没有域名都是IP，因此怀疑是这个原因导致压根没有进行域名匹配，都是根据IP做的分流。
将日志级别调整为info以后看到：
“2021-07-05 08:25:01 level=info msg="[TCP] 192.168.1.182:7673 --> 95.217.141.226 match Match() using 🧭Final[]"”
没有其他报错，请教这种情况应该如何排查，或者是我哪里设置错了，谢谢！

**Comment by liofoil** [comment]
这种情况可能是因为openclash拿不到dns请求导致的，你去查查看自己的设备或者lan口有没有设置别的dns，如果有，请把它改回去

**Comment by yhucao** [comment]
> 这种情况可能是因为openclash拿不到dns请求导致的，你去查查看自己的设备或者lan口有没有设置别的dns，如果有，请把它改回去

我有在用AdGuardHome，确实可能是这个原因，我改了试试，谢谢！

**Comment by yhucao** [comment]
> 这种情况可能是因为openclash拿不到dns请求导致的，你去查查看自己的设备或者lan口有没有设置别的dns，如果有，请把它改回去

正常了，谢谢！
