### ISSUE TITLE
请问一下代理集的文件格式是什么样子？

### ISSUE THREAD

**Issue by WildSaCk** [vernesong/OpenClash#145]
能麻烦提供一下吗？想自己写脚本生成自动更新。ths

**Comment by vernesong** [comment]
模板里面有

**Comment by WildSaCk** [comment]
> 模板里面有

模板？貌似没找到啊，能麻烦说一下在那里吗？ths

**Comment by vernesong** [comment]
```
proxies:
# shadowsocks
# The supported ciphers(encrypt methods):
#   aes-128-gcm aes-192-gcm aes-256-gcm
#   aes-128-cfb aes-192-cfb aes-256-cfb
#   aes-128-ctr aes-192-ctr aes-256-ctr
#   rc4-md5 chacha20 chacha20-ietf xchacha20
#   chacha20-ietf-poly1305 xchacha20-ietf-poly1305
- { name: "ss1", type: ss, server: server, port: 443, cipher: chacha20-ietf-poly1305, password: "password", udp: true }

# old obfs configuration remove after prerelease
- name: "ss2"
  type: ss
  server: server
  port: 443
  cipher: chacha20-ietf-poly1305
  password: "password"
  plugin: obfs
  plugin-opts:
    mode: tls # or http
    # host: bing.com

- name: "ss3"
  type: ss
  server: server
  port: 443
  cipher: chacha20-ietf-poly1305
  password: "password"
  plugin: v2ray-plugin
  plugin-opts:
    mode: websocket # no QUIC now
    # tls: true # wss
    # skip-cert-verify: true
    # host: bing.com
    # path: "/"
    # headers:
    #   custom: value

# vmess
# cipher support auto/aes-128-gcm/chacha20-poly1305/none
- { name: "vmess", type: vmess, server: server, port: 443, uuid: uuid, alterId: 32, cipher: auto }
# with tls
- { name: "vmess", type: vmess, server: server, port: 443, uuid: uuid, alterId: 32, cipher: auto, tls: true }
# with tls and skip-cert-verify
- { name: "vmess", type: vmess, server: server, port: 443, uuid: uuid, alterId: 32, cipher: auto, tls: true, skip-cert-verify: true }
# with ws-path and ws-headers
- { name: "vmess", type: vmess, server: server, port: 443, uuid: uuid, alterId: 32, cipher: auto, network: ws, ws-path: /path, ws-headers: { Host: v2ray.com } }
# with ws + tls
- { name: "vmess", type: vmess, server: server, port: 443, uuid: uuid, alterId: 32, cipher: auto, network: ws, ws-path: /path, tls: true }

# socks5
- { name: "socks", type: socks5, server: server, port: 443 }
# socks5 with authentication
- { name: "socks", type: socks5, server: server, port: 443, username: "username", password: "password" }
# with tls
- { name: "socks", type: socks5, server: server, port: 443, tls: true }
# with tls and skip-cert-verify
- { name: "socks", type: socks5, server: server, port: 443, tls: true, skip-cert-verify: true }

# http
- { name: "http", type: http, server: server, port: 443 }
# http with authentication
- { name: "http", type: http, server: server, port: 443, username: "username", password: "password" }
# with tls (https)
- { name: "http", type: http, server: server, port: 443, tls: true }
# with tls (https) and skip-cert-verify
- { name: "http", type: http, server: server, port: 443, tls: true, skip-cert-verify: true }

**Comment by WildSaCk** [comment]
> ```
> proxies:
> # shadowsocks
> # The supported ciphers(encrypt methods):
> #   aes-128-gcm aes-192-gcm aes-256-gcm
> #   aes-128-cfb aes-192-cfb aes-256-cfb
> #   aes-128-ctr aes-192-ctr aes-256-ctr
> #   rc4-md5 chacha20 chacha20-ietf xchacha20
> #   chacha20-ietf-poly1305 xchacha20-ietf-poly1305
> - { name: "ss1", type: ss, server: server, port: 443, cipher: chacha20-ietf-poly1305, password: "password", udp: true }
> 
> # old obfs configuration remove after prerelease
> - name: "ss2"
>   type: ss
>   server: server
>   port: 443
>   cipher: chacha20-ietf-poly1305
>   password: "password"
>   plugin: obfs
>   plugin-opts:
>     mode: tls # or http
>     # host: bing.com
> 
> - name: "ss3"
>   type: ss
>   server: server
>   port: 443
>   cipher: chacha20-ietf-poly1305
>   password: "password"
>   plugin: v2ray-plugin
>   plugin-opts:
>     mode: websocket # no QUIC now
>     # tls: true # wss
>     # skip-cert-verify: true
>     # host: bing.com
>     # path: "/"
>     # headers:
>     #   custom: value
> 
> # vmess
> # cipher support auto/aes-128-gcm/chacha20-poly1305/none
> - { name: "vmess", type: vmess, server: server, port: 443, uuid: uuid, alterId: 32, cipher: auto }
> # with tls
> - { name: "vmess", type: vmess, server: server, port: 443, uuid: uuid, alterId: 32, cipher: auto, tls: true }
> # with tls and skip-cert-verify
> - { name: "vmess", type: vmess, server: server, port: 443, uuid: uuid, alterId: 32, cipher: auto, tls: true, skip-cert-verify: true }
> # with ws-path and ws-headers
> - { name: "vmess", type: vmess, server: server, port: 443, uuid: uuid, alterId: 32, cipher: auto, network: ws, ws-path: /path, ws-headers: { Host: v2ray.com } }
> # with ws + tls
> - { name: "vmess", type: vmess, server: server, port: 443, uuid: uuid, alterId: 32, cipher: auto, network: ws, ws-path: /path, tls: true }
> 
> # socks5
> - { name: "socks", type: socks5, server: server, port: 443 }
> # socks5 with authentication
> - { name: "socks", type: socks5, server: server, port: 443, username: "username", password: "password" }
> # with tls
> - { name: "socks", type: socks5, server: server, port: 443, tls: true }
> # with tls and skip-cert-verify
> - { name: "socks", type: socks5, server: server, port: 443, tls: true, skip-cert-verify: true }
> 
> # http
> - { name: "http", type: http, server: server, port: 443 }
> # http with authentication
> - { name: "http", type: http, server: server, port: 443, username: "username", password: "password" }
> # with tls (https)
> - { name: "http", type: http, server: server, port: 443, tls: true }
> # with tls (https) and skip-cert-verify
> - { name: "http", type: http, server: server, port: 443, tls: true, skip-cert-verify: true }
> ```

好的！十分感谢！
