### ISSUE TITLE
v0.42.06-beta 反复弹出对话框，无法进入控制面板

### ISSUE THREAD

**Issue by touchsola** [vernesong/OpenClash#1450]
v0.42.06-beta 点击【进入控制面板】后，弹出对话框，填入正确的【Host】IP及【端口】，【密钥】信息后，会再次弹出对话框，
此时【Host】里面的IP显示为0，看上去是IP无法保存，如下图，无法进入控制面板
![火狐截图_2021-07-05T02-58-32 934Z](https://user-images.githubusercontent.com/72115940/124412149-74cbd580-dd80-11eb-9f86-4049dc3a40fa.png)

**Comment by touchsola** [comment]
对比了一下新老版本v0.42.06-beta的浏览器地址栏，新版本显示的是
http://192.168.68.19:9090/ui/?host=0&port=9090&secret=123456#/proxies
旧版本v0.42.05-beta 是
http://192.168.68.19:9090/ui/#/proxies

**Comment by RikudouPatrickstar** [comment]
我这里也是这样，host=0，刚要提 issue。
似乎是这个 PR 有问题 [#1428](https://github.com/vernesong/OpenClash/pull/1428)，改回去之后能正常打开。

**Comment by touchsola** [comment]
> 
> 
> 我这里也是这样，host=0，刚要提 issue。
> 似乎是这个 PR 有问题 [#1428](https://github.com/vernesong/OpenClash/pull/1428)，应该是
> 
> ```
> '/ui/?host='+ (window.location.hostname || status.daip)
> ```

测试问题已修复，点击【进入控制面板】可以正常打开，谢谢
