### ISSUE TITLE
全局设置下的所有配置标签全部消失

### ISSUE THREAD

**Issue by stanleyblue** [vernesong/OpenClash#1451]
在配置过程中，可能的配置文件改动导致全局设置下所有的配置标签全部消失了。如何恢复？

OpenClash是否能够增加一个一键初始化的功能？

![image](https://user-images.githubusercontent.com/34419206/124483645-2a2c7680-dddd-11eb-9715-55f5f625a361.png)

**Comment by vernesong** [comment]
http://192.168.1.1/cgi-bin/luci/admin/services/openclash/restore

**Comment by stanleyblue** [comment]
感谢。下次再消失试试。原来还可以这么用插件

**Comment by stanleyblue** [comment]
感谢
