### ISSUE TITLE
openclash启用后我不能直接访问局域网的ip，比如我的ikuai，esxi等，

### ISSUE THREAD

**Issue by sarsmark-git** [vernesong/OpenClash#1452]
已经将本地ip段都设为直连也不行，但是关掉openclash后内网ip都能正常访问。

- IP-CIDR,192.76.5.0/24,DIRECT
- IP-CIDR,192.76.5.0/24,🎯 全球直连

192.76.5.*是我的内网ip段。

这个需要设置哪里？

**Comment by vernesong** [comment]
https://github.com/vernesong/OpenClash/blob/46e6b3be0c5484d72b415924dd56d120360c6a01/luci-app-openclash/root/etc/init.d/openclash#L1369

自己修改一下

**Comment by sarsmark-git** [comment]
谢谢，解决了，以后能否把这个放到某个设置项里来添加？

**Comment by VergilGao** [comment]
虽然但是，192.76.5.*是北美的ip段，你这样拿来直接当内网用虽然没啥问题，但是不太符合标准吧……
