### ISSUE TITLE
这是一个询问帖子，Dev内核1.6.5比前个版本1.6.0提升了什么，为何我的YouTube连接速度翻番

### ISSUE THREAD

**Issue by Faramitas** [vernesong/OpenClash#1453]
如题，几乎可以跟我用PC端Clash的速度的媲美了，之前那个版本好像最多12W(我的宽带环境下)，昨天更新到1.6.5，甚至可以达到26W，单纯好奇的询问一下V大。

**Comment by zgc** [comment]
内核问题应该去https://github.com/Dreamacro/clash提问
