### ISSUE TITLE
咨询：第三方规则与自定义规则的优先顺序

### ISSUE THREAD

**Issue by stanleyblue** [vernesong/OpenClash#1455]
文档里说，排在前面的规则是先执行，匹配后就不往下走了。
那自定义的规则怎么能够排在预定义或者第三方的规则前面？还是默认优先级一定是在最先的？？

感谢楼主有这么好的交流场所

**Comment by stanleyblue** [comment]
而且我在自定义规则的文本框里填入的规则，在配置文件管理-配置文件编辑的两个文本框里，并没有看见。这左右两个文本框是什么关系？自定义不在里面体现？

**Comment by stanleyblue** [comment]
有什么答复么？谢谢

**Comment by feng1992** [comment]
这个问题老铁解决了吗？
