### ISSUE TITLE
配置文件rules后面没有了

### ISSUE THREAD

**Issue by ydhydg** [vernesong/OpenClash#1456]
原来rules下面都有规则能正常运行的，但是更新完之后发现每次保存应用配置后，重启就发现rules后面的规则就不见了，试了很多次都是一样，请问怎么解决呢？
![image](https://user-images.githubusercontent.com/87065607/124729938-742f6c80-df43-11eb-9e7a-bc131d0d606d.png)
![image](https://user-images.githubusercontent.com/87065607/124730381-ddaf7b00-df43-11eb-88f0-30af4a316ea3.png)

**Comment by vernesong** [comment]
日志报什么错误

**Comment by ydhydg** [comment]
![截屏2021-07-13 02 11 09](https://user-images.githubusercontent.com/87065607/125335873-a3990b80-e37f-11eb-8f7f-6cc2d5bc708f.png)

**Comment by ydhydg** [comment]
但是我的配置文件是有的，只是在openclash上一启动，它就自动变没了

**Comment by vernesong** [comment]
建议更新一下，旧版本的问题不好找
