### ISSUE TITLE
【求助功能】openclash可以合并多个订阅的节点，下载生成一个yaml文件吗？

### ISSUE THREAD

**Issue by icucuio** [vernesong/OpenClash#1457]
如题

**Comment by vernesong** [comment]
订阅转换，多个地址用|连接

**Comment by icucuio** [comment]
> 订阅转换，多个地址用|连接

就是 订阅1|订阅2|订阅3......
这样写到一个地址里面吗？

**Comment by icucuio** [comment]
> 订阅转换，多个地址用|连接

合并我搞定了，谢谢

现在有另外一个问题，我想DIY下yaml文件，增加url-test 里面的tolerance，自带的订阅方式，没有这个，还得每次修改yaml，比较麻烦，怎么加？
