### ISSUE TITLE
安装v0.42.06-beta客户端后有个BUG

### ISSUE THREAD

**Issue by tomagag** [vernesong/OpenClash#1462]
使用v0.42.06-beta客户端运行，使用LAN连接openwrt设备的PC可以正常科学上网，但使用WIFI连接的手机、平板等设备只能使用APP翻墙，但打不开网页。回退至v0.42.05-beta客户端且未更改其他设置，手机平板等WIFI连接的设备回复正常

**Comment by vernesong** [comment]
给控制面板日志，可能是缓存问题

**Comment by tomagag** [comment]
> 给控制面板日志，可能是缓存问题

回退上个版本后日志被清了。这个BUG很奇怪 ，lan设备没问题，WIFI连接的设备会出现，而且APP用没问题，只是开不了网页

**Comment by a76yyyy** [comment]
> 回退上个版本后日志被清了。这个BUG很奇怪 ，lan设备没问题，WIFI连接的设备会出现，而且APP用没问题，只是开不了网页

我看到面板里手机看网页时对应ip下不显示域名，只显示dns解析后的ip，今天把内核更新到最新就好了，你可以试试

**Comment by tomagag** [comment]
> > 回退上个版本后日志被清了。这个BUG很奇怪 ，lan设备没问题，WIFI连接的设备会出现，而且APP用没问题，只是开不了网页
> 
> 我看到面板里手机看网页时对应ip下不显示域名，只显示dns解析后的ip，今天把内核更新到最新就好了，你可以试试

已重新安装内核和客户端，问题解决。感谢！

**Comment by a76yyyy** [comment]
> 已重新安装内核和客户端，问题解决。感谢！
(记录)我更新完过了一段时间又不能用了，后来发现是手机开了一个“私人dns”的选项，这样的dns不会走clash，如果你又遇到了类似问题，可以试一下关闭私人dns

**Comment by tomagag** [comment]
> > 已重新安装内核和客户端，问题解决。感谢！
> > (记录)我更新完过了一段时间又不能用了，后来发现是手机开了一个“私人dns”的选项，这样的dns不会走clash，如果你又遇到了类似问题，可以试一下关闭私人dns

私人DNS我看了一下我的手机，并未打开。
我现在2个地方的OPENWRT，有一个装回V0.42.05没问题，一个装V0.42.06目前没问题。昨天遇到情况的时候，同样的状态，关掉OPENCLASH客户端后用PASSWALL或HELLO WORLD，可以直接登录网页翻墙

**Comment by tomagag** [comment]
![Screenshot_2021-07-12-21-11-15-633_com android chrome](https://user-images.githubusercontent.com/85090720/125394910-fce35800-e3dc-11eb-90c2-b3dce1f115b2.jpg)
就是出现这个样子
