### ISSUE TITLE
在线订阅转换模板，提示配置文件节点校验失败

### ISSUE THREAD

**Issue by Biyanbin** [vernesong/OpenClash#1463]
带哥~!
我因为想要配置策略组，详细的自定义，所以勾选了在线订阅转换，尝试着将模板改为acl4ssr。
![image](https://user-images.githubusercontent.com/38453520/125185505-c29c7e00-e257-11eb-9846-8704dde27afa.png)
![QQ20210711-132554](https://user-images.githubusercontent.com/38453520/125185519-e069e300-e257-11eb-9513-7899c387ea6b.png)
但到了应用阶段，却总提示配置文件节点部分校验失败，尝试不使用代理下载配置文件……
![QQ20210711-133018](https://user-images.githubusercontent.com/38453520/125185522-e790f100-e257-11eb-872d-7c6b226524fa.png)
现在头已秃！

**Comment by vernesong** [comment]
订阅是什么类型的，可能不支持转换

**Comment by Biyanbin** [comment]
感谢回复，不过抱歉我不太懂是什么类型，要怎么看呢？另外如果我想要换个策略组该怎么办？也就是说，我只保留订阅中的节点，策略用acl4ssr online full那。因为那个策略可以按照区域划分节点，我比较需要这个。

**Comment by vernesong** [comment]
就是你这样操作啊，订阅地址直接填机场给的那个，不要填那些转个器给的地址

**Comment by Biyanbin** [comment]
我的那个地址就是机场给的那个，不勾选在线订阅转换就能顺利进行。但是 proxy-groups是固定的。如果想要更改模板，就得勾选在线订阅转换，订阅转换服务地址那就会有个默认值……然后就会失败……

**Comment by vernesong** [comment]
你第一张图里的订阅地址是转换后的地址，请截取url=这一个参数后面的地址填入

**Comment by Biyanbin** [comment]
我第一个订阅地址是这样的
https://subcon.dlj.tf/sub?target=clash&new_name=true&url=https%3A%2F%2Fsubscribe.hlasw.com%2Flink%2FLyNRBxIVCnaam5sS%3Fsub%3D1%26extend%3D1&insert=false&config=https%3A%2F%2Fraw.githubusercontent.com%2FACL4SSR%2FACL4SSR%2Fmaster%2FClash%2Fconfig%2FACL4SSR_Online.ini&inc………………

所以，您的意思是说我需要填入
https://%3A%2F%2Fsubscribe.hlasw.com%2Flink%2FLyNRBxIVCnaam5sS%3Fsub%3D1%26extend%3D1&insert=false&config=https%3A%…………

是这样吗？

**Comment by vernesong** [comment]
https://subscribe.hlasw.com/link/LyNRBxIVCnaam5sS?sub=1&extend=1

**Comment by Biyanbin** [comment]
我完全晕了…………这个是怎么得出来的呢……
biyanbin@live.com 您能发个邮件给我，我把完整的地址给您。

**Comment by tagcloud-hk** [comment]
> https://subscribe.hlasw.com/link/LyNRBxIVCnaam5sS?sub=1&extend=1

已封禁賬號，訂閱地址能隨便公開的？

**Comment by Biyanbin** [comment]
啊？哪个是订阅地址？我打的那个都不是完整的…

**Comment by vernesong** [comment]
> > https://subscribe.hlasw.com/link/LyNRBxIVCnaam5sS?sub=1&extend=1
> 
> 已封禁賬號，訂閱地址能隨便公開的？

忘记提醒了，我的错。。。

**Comment by stan1943** [comment]
> 啊？哪个是订阅地址？我打的那个都不是完整的…

你第一张图那个是你已经用了转换网址进行了转换了，不是机场原始的订阅地址。图一相当于openclash自带的转换再转换你已转换的原始订阅，套娃了。

**Comment by tomagag** [comment]
更换转换节点的服务地址试一下

**Comment by Raerl** [comment]
先启动别的梯子，再启动openclash就正常了

**Comment by weicaixian86** [comment]
> 带哥~! 我因为想要配置策略组，详细的自定义，所以勾选了在线订阅转换，尝试着将模板改为acl4ssr。 ![image](https://user-images.githubusercontent.com/38453520/125185505-c29c7e00-e257-11eb-9846-8704dde27afa.png) ![QQ20210711-132554](https://user-images.githubusercontent.com/38453520/125185519-e069e300-e257-11eb-9513-7899c387ea6b.png) 但到了应用阶段，却总提示配置文件节点部分校验失败，尝试不使用代理下载配置文件…… ![QQ20210711-133018](https://user-images.githubusercontent.com/38453520/125185522-e790f100-e257-11eb-872d-7c6b226524fa.png) 现在头已秃！

我已经发现了机场不支持造成。
