### ISSUE TITLE
两个控制面板都需要手动输入地址、端口、密码了

### ISSUE THREAD

**Issue by RikudouPatrickstar** [vernesong/OpenClash#1464]
应该是 [change: refine translations and bug fix](https://github.com/vernesong/OpenClash/commit/d01f510dc0697afced637b2004a5ca281a3dcf3e) 这个 commit 中对 status.html 的修改造成的。
`&& window.location.hostname == status.daip` 这个条件一般情况下应该都不会成立，删除这个条件后实测能够正常访问两个面板了。

**Comment by vernesong** [comment]
这个条件是判断内网访问的，如果status.daip获取错误或者是端口转发的话，因为环境特殊不再设置自动登录

**Comment by RikudouPatrickstar** [comment]
哦，原来是故意弄的呀。我还以为，一个设备名（openwrt.lan），一个IP地址（192.168.1.1），两个字符串不等是写错了呢。
