### ISSUE TITLE
请教各位大佬AdGuard Home和OpenClash如何搭配使用

### ISSUE THREAD

**Issue by OoNanGeOo** [vernesong/OpenClash#1465]
一直想让这两个插件搭配使用，但是设置来设置去，还是没搞定，麻烦有知道的详细说一下，小弟在这里不胜感激

1.AdGuard Home的设置恩山上的参考贴https://www.right.com.cn/forum/thread-4090928-1-1.html

2.OpenClash需要如何修改上游链接

麻烦各位大佬能否帮我分析一下AdGuard Home的这个帖子设置有没有问题

**Comment by vernesong** [comment]
https://github.com/vernesong/OpenClash/discussions/1420

**Comment by winxpp** [comment]
我最近也试过好几次 都是失败告终 感觉clash已经不错了 没必要加ADG了 我用ADG也就是用个DNS功能 我不需要去广告

**Comment by eyaeya** [comment]
我就是搭配使用的，按这样设置链路 路由器DNS -> ADG -> OpenClash。都在自定义DNS服务器部分设置。
在ADG可以看到每个接入终端的流量，在OpenClash中也可以。

**Comment by vernesong** [comment]
adg上游填oc的时候记得要关闭adg的缓存

**Comment by cutanzi1997** [comment]
不是DNS ---------- 高级模式DNS ----------- 填入127.0.0.1#6053吗
