### ISSUE TITLE
v2ray配置问题

### ISSUE THREAD

**Issue by jindx0713** [vernesong/OpenClash#147]
同样一份配置文件，在clashX中，v2ray可正常测速。在openclash中就无法连接。

找不到问题点在哪。。

同一个配置，在v2rayU/clashX中均可用。在openclash中就无法使用。

**Comment by vernesong** [comment]
openclash启动需要配置文件里各部分内容的顺序按照模板排列，否则会无法识别，一些缺的参数就会加不上去，另外启动时不会对服务器配置做修改。

**Comment by jindx0713** [comment]
> openclash启动需要配置文件里各部分内容的顺序按照模板排列，否则会无法识别，一些缺的参数就会加不上去，另外启动时不会对服务器配置做修改。

大概发现问题了，之前是ws+tls，openclash没办法正常使用，换到单纯的ws就可以了。

另外还有个问题就是，手动删除了/etc/openclash后，无法用命令重新安装和卸载了，低版本也不行。有什么其他办法可以处理吗？

**Comment by vernesong** [comment]
opkg remove --force-remove luci-app-openclash

**Comment by jindx0713** [comment]
> opkg remove --force-remove luci-app-openclash

Removing package luci-app-openclash from root...
uci: Entry not found
uci: Entry not found
OpenClash Already Stop
Collected errors:
 * pkg_run_script: package "luci-app-openclash" prerm script returned status 1.



另外ws+tls的问题，怎么和你复现一下，还是什么原因？

**Comment by Fengqing1999** [comment]
楼主解决问题了吗，我也是在v2ray端使用没有问题，在openclash里测速不行，全是黑色，之前内出现过这种情况。想问下怎么解决

**Comment by vernesong** [comment]
https://github.com/Dreamacro/clash/issues/401
https://github.com/Dreamacro/clash/issues/477

**Comment by jindx0713** [comment]
> 楼主解决问题了吗，我也是在v2ray端使用没有问题，在openclash里测速不行，全是黑色，之前内出现过这种情况。想问下怎么解决

没解决，懒得去查是不是nginx层面的问题了。换成ws不带tls就可以了。
