### ISSUE TITLE
YouTube视频无法加载 google无法访问ERR_TIMED_OUT

### ISSUE THREAD

**Issue by mn2xujiakun** [vernesong/OpenClash#1473]
在dashboard面板中查看链接发现都是ip没有域名，规则也都是漏网之鱼
![微信截图_20210715020121](https://user-images.githubusercontent.com/36425068/125675081-a85dea0c-c685-410c-82e9-d65b55922486.png)
![微信截图_20210715023345](https://user-images.githubusercontent.com/36425068/125675088-58325642-5209-455e-8627-bd62ae2bb612.png)
![微信截图_20210715023354](https://user-images.githubusercontent.com/36425068/125675094-c7989e83-4e85-4706-925f-332f971cc216.png)
![微信截图_20210715023515](https://user-images.githubusercontent.com/36425068/125675100-2dc551cd-a267-4b36-b08f-48dcedd84706.png)
![微信截图_20210715023545](https://user-images.githubusercontent.com/36425068/125675107-7b8b4a3d-e2c1-45d2-abf1-ae0b6742245f.png)
![微信截图_20210715023601](https://user-images.githubusercontent.com/36425068/125675110-07a07155-b68c-4baf-a4c0-849bd6a73e82.png)
![微信截图_20210715023618](https://user-images.githubusercontent.com/36425068/125675116-838b37dd-6966-44d3-aa09-470a5563c0ef.png)

**Comment by mn2xujiakun** [comment]
自己也试了fake ip模式   也是不行
现在在想是不是dns的问题
但是我参考之前已经解决过的一个issue去清空dns缓存依然不行

**Comment by vernesong** [comment]
不要开其他dns插件

**Comment by mn2xujiakun** [comment]
> 不要开其他dns插件

没有开其他dns插件  昨晚我发现禁用自己电脑的ipv6就可以了  可能因为电脑的ipv6的dns服务器还是主路由
