### ISSUE TITLE
[建议功能]代理某个类型的流量

### ISSUE THREAD

**Issue by fjjking** [vernesong/OpenClash#1476]
如题目，有些sstap游戏规则不是很完善又不想一个一个抓，用Proxifier把流量导向openclash的时候还要另外加规则才能代理.
能否加一个规则比如：-type,socks5,SSR
(PS:如果已经有这个功能了请告诉我，非常感谢作者)

**Comment by vernesong** [comment]
内核那边有类似的pr，可以自己编译替换

**Comment by fjjking** [comment]
谢谢提醒我去看看

**Comment by fjjking** [comment]
并没有看到？唯一一个还是网络相关的
https://github.com/Dreamacro/clash/pull/631
能指一条链接吗？

**Comment by fjjking** [comment]
我发现TUN模式下的script可以满足我的要求。。
