### ISSUE TITLE
如何写一条规则，一个内网IP对应一个节点呢？

### ISSUE THREAD

**Issue by vpscn2gmail** [vernesong/OpenClash#1477]
如题，内网的一个IP，对应着一个节点。。

**Comment by fjjking** [comment]
全局设置的规则设置里有示例
- SRC-IP-CIDR,192.168.1.201/32,DIRECT 匹配数据发起IP(直连)

**Comment by OoNanGeOo** [comment]
看规则！！！！2楼说的对
