### ISSUE TITLE
Add Redir IPv6 Support

### ISSUE THREAD

**Issue by hexin-lin-1024** [vernesong/OpenClash#1484]
似乎Clash内核已经可以处理一部分的IPv6请求，经测试Clash For Win下可以代理IPv6，或者考虑加入IPv6代理开关，留一个选择？

**Comment by hcym** [comment]
这个是刚需，移动宽带ipv6出口额度很大😂

**Comment by yangxcs** [comment]
https://github.com/vernesong/OpenClash/issues/1311#issuecomment-808727451
@vernesong 希望redir模式能尽快支持IPV6，等太久啦

**Comment by hexin-lin-1024** [comment]
> [#1311 (comment)](https://github.com/vernesong/OpenClash/issues/1311#issuecomment-808727451)
> @vernesong 希望redir模式能尽快支持IPV6，等太久啦

#1311 我照着改了一遍没成功，然后今天改了一整天也没出结果，这段应该是有点问题：
 if [ "$ipv6_enable" -eq 1 ]; then
      ip6tables -t mangle -N openclash
      ip6tables -t mangle -F openclash
      ip6tables -t mangle -A openclash -m set --match-set localnetwork6 dst -j RETURN
      ip6tables -t mangle -A PREROUTING -j openclash
      ip6tables -t mangle -N openclash_output
      ip6tables -t mangle -F openclash_output
      ip6tables -t mangle -A openclash_output -m set --match-set localnetwork6 dst -j RETURN
      ip6tables -t mangle -A OUTPUT -j openclash_output
      ip -6 rule add fwmark "$PROXY_FWMARK" table "$PROXY_ROUTE_TABLE"
      ip -6 route add local ::/0 dev lo table "$PROXY_ROUTE_TABLE"
      # 防止出现死循环
      ip6tables -t mangle -A openclash_output -p tcp -m owner ! --uid-owner 65534 -j MARK --set-xmark "$PROXY_FWMARK"
      ip6tables -t mangle -A openclash_output -p udp -m owner ! --uid-owner 65534 -j MARK --set-xmark "$PROXY_FWMARK"
      ip6tables -t mangle -A openclash -p tcp -m comment --comment "\'默认\'" -j TPROXY --on-port "$tproxy_port" --tproxy-mark "$PROXY_FWMARK"
      ip6tables -t mangle -A openclash -p udp -m comment --comment "\'默认\'" -j TPROXY --on-port "$tproxy_port" --tproxy-mark "$PROXY_FWMARK"
   fi 2>/dev/null

这段似乎还是有点问题，奈何我也不是很明白。没有办法，

if [ "$ipv6_enable" -eq 1 ]; then
      ip -6 rule add fwmark "$PROXY_FWMARK" table "$PROXY_ROUTE_TABLE"
      ip -6 route add local ::/0 dev lo table "$PROXY_ROUTE_TABLE"
      ip6tables -t mangle -N openclash
      ip6tables -t mangle -F openclash
      ip6tables -t mangle -A openclash -m set --match-set localnetwork6 dst -j RETURN
      ip6tables -t mangle -A openclash -p udp --dport 53 -j RETURN
      ip6tables -t mangle -A openclash -p tcp -m comment --comment "\'默认\'" -j TPROXY --on-port "$tproxy_port" --tproxy-mark "$PROXY_FWMARK"
      ip6tables -t mangle -A openclash -p udp -m comment --comment "\'默认\'" -j TPROXY --on-port "$tproxy_port" --tproxy-mark "$PROXY_FWMARK"
      ip6tables -t mangle -N openclash_output
      ip6tables -t mangle -F openclash_output
      ip6tables -t mangle -A openclash_output -m set --match-set localnetwork6 dst -j RETURN
      ip6tables -t mangle -A openclash_output -p udp --dport 53 -j RETURN
      ip6tables -t mangle -A openclash_output -p tcp -m owner ! --uid-owner 65534 -j MARK --set-mark "$PROXY_FWMARK"
      ip6tables -t mangle -A openclash_output -p udp -m owner ! --uid-owner 65534 -j MARK --set-mark "$PROXY_FWMARK"
      ip6tables -t mangle -A PREROUTING -j openclash
      ip6tables -t mangle -A OUTPUT -j openclash_output
   fi 2>/dev/null

改成这样之后能在日志里看到连接，但是访问ipv6资源时仍然超时。

**Comment by hexin-lin-1024** [comment]
> > [#1311 (comment)](https://github.com/vernesong/OpenClash/issues/1311#issuecomment-808727451)
> > @vernesong 希望redir模式能尽快支持IPV6，等太久啦
> 
> #1311 我照着改了一遍没成功，然后今天改了一整天也没出结果，这段应该是有点问题：
> if [ "$ipv6_enable" -eq 1 ]; then
> ip6tables -t mangle -N openclash
> ip6tables -t mangle -F openclash
> ip6tables -t mangle -A openclash -m set --match-set localnetwork6 dst -j RETURN
> ip6tables -t mangle -A PREROUTING -j openclash
> ip6tables -t mangle -N openclash_output
> ip6tables -t mangle -F openclash_output
> ip6tables -t mangle -A openclash_output -m set --match-set localnetwork6 dst -j RETURN
> ip6tables -t mangle -A OUTPUT -j openclash_output
> ip -6 rule add fwmark "$PROXY_FWMARK" table "$PROXY_ROUTE_TABLE"
> ip -6 route add local ::/0 dev lo table "$PROXY_ROUTE_TABLE"
> # 防止出现死循环
> ip6tables -t mangle -A openclash_output -p tcp -m owner ! --uid-owner 65534 -j MARK --set-xmark "$PROXY_FWMARK"
> ip6tables -t mangle -A openclash_output -p udp -m owner ! --uid-owner 65534 -j MARK --set-xmark "$PROXY_FWMARK"
> ip6tables -t mangle -A openclash -p tcp -m comment --comment "'默认'" -j TPROXY --on-port "$tproxy_port" --tproxy-mark "$PROXY_FWMARK"
> ip6tables -t mangle -A openclash -p udp -m comment --comment "'默认'" -j TPROXY --on-port "$tproxy_port" --tproxy-mark "$PROXY_FWMARK"
> fi 2>/dev/null
> 
> 这段似乎还是有点问题，奈何我也不是很明白。没有办法，
> 
> if [ "$ipv6_enable" -eq 1 ]; then
> ip -6 rule add fwmark "$PROXY_FWMARK" table "$PROXY_ROUTE_TABLE"
> ip -6 route add local ::/0 dev lo table "$PROXY_ROUTE_TABLE"
> ip6tables -t mangle -N openclash
> ip6tables -t mangle -F openclash
> ip6tables -t mangle -A openclash -m set --match-set localnetwork6 dst -j RETURN
> ip6tables -t mangle -A openclash -p tcp -m comment --comment "'默认'" -j TPROXY --on-port "$tproxy_port" --tproxy-mark "$PROXY_FWMARK"
> ip6tables -t mangle -A openclash -p udp -m comment --comment "'默认'" -j TPROXY --on-port "$tproxy_port" --tproxy-mark "$PROXY_FWMARK"
> ip6tables -t mangle -N openclash_output
> ip6tables -t mangle -F openclash_output
> ip6tables -t mangle -A openclash_output -m set --match-set localnetwork6 dst -j RETURN
> ip6tables -t mangle -A openclash_output -p tcp -m owner ! --uid-owner 0 -j MARK --set-xmark "$PROXY_FWMARK"
> ip6tables -t mangle -A openclash_output -p udp -m owner ! --uid-owner 0 -j MARK --set-xmark "$PROXY_FWMARK"
> ip6tables -t mangle -A PREROUTING -j openclash
> ip6tables -t mangle -A OUTPUT -j openclash_output
> fi 2>/dev/null
> 
> 求作者大大跟进 ipv6 问题 @vernesong

**Comment by yangxcs** [comment]
> > > [#1311 (comment)](https://github.com/vernesong/OpenClash/issues/1311#issuecomment-808727451)
> > > @vernesong 希望redir模式能尽快支持IPV6，等太久啦
> > 
> > 
> > #1311 我照着改了一遍没成功，然后今天改了一整天也没出结果，这段应该是有点问题：
> > if [ "$ipv6_enable" -eq 1 ]; then
> > ip6tables -t mangle -N openclash
> > ip6tables -t mangle -F openclash
> > ip6tables -t mangle -A openclash -m set --match-set localnetwork6 dst -j RETURN
> > ip6tables -t mangle -A PREROUTING -j openclash
> > ip6tables -t mangle -N openclash_output
> > ip6tables -t mangle -F openclash_output
> > ip6tables -t mangle -A openclash_output -m set --match-set localnetwork6 dst -j RETURN
> > ip6tables -t mangle -A OUTPUT -j openclash_output
> > ip -6 rule add fwmark "$PROXY_FWMARK" table "$PROXY_ROUTE_TABLE"
> > ip -6 route add local ::/0 dev lo table "$PROXY_ROUTE_TABLE"
> > # 防止出现死循环
> > ip6tables -t mangle -A openclash_output -p tcp -m owner ! --uid-owner 65534 -j MARK --set-xmark "$PROXY_FWMARK"
> > ip6tables -t mangle -A openclash_output -p udp -m owner ! --uid-owner 65534 -j MARK --set-xmark "$PROXY_FWMARK"
> > ip6tables -t mangle -A openclash -p tcp -m comment --comment "'默认'" -j TPROXY --on-port "$tproxy_port" --tproxy-mark "$PROXY_FWMARK"
> > ip6tables -t mangle -A openclash -p udp -m comment --comment "'默认'" -j TPROXY --on-port "$tproxy_port" --tproxy-mark "$PROXY_FWMARK"
> > fi 2>/dev/null
> > 这段似乎还是有点问题，奈何我也不是很明白。没有办法，
> > if [ "$ipv6_enable" -eq 1 ]; then
> > ip -6 rule add fwmark "$PROXY_FWMARK" table "$PROXY_ROUTE_TABLE"
> > ip -6 route add local ::/0 dev lo table "$PROXY_ROUTE_TABLE"
> > ip6tables -t mangle -N openclash
> > ip6tables -t mangle -F openclash
> > ip6tables -t mangle -A openclash -m set --match-set localnetwork6 dst -j RETURN
> > ip6tables -t mangle -A openclash -p tcp -m comment --comment "'默认'" -j TPROXY --on-port "$tproxy_port" --tproxy-mark "$PROXY_FWMARK"
> > ip6tables -t mangle -A openclash -p udp -m comment --comment "'默认'" -j TPROXY --on-port "$tproxy_port" --tproxy-mark "$PROXY_FWMARK"
> > ip6tables -t mangle -N openclash_output
> > ip6tables -t mangle -F openclash_output
> > ip6tables -t mangle -A openclash_output -m set --match-set localnetwork6 dst -j RETURN
> > ip6tables -t mangle -A openclash_output -p tcp -m owner ! --uid-owner 0 -j MARK --set-xmark "$PROXY_FWMARK"
> > ip6tables -t mangle -A openclash_output -p udp -m owner ! --uid-owner 0 -j MARK --set-xmark "$PROXY_FWMARK"
> > ip6tables -t mangle -A PREROUTING -j openclash
> > ip6tables -t mangle -A OUTPUT -j openclash_output
> > fi 2>/dev/null
> > 求作者大大跟进 ipv6 问题 @vernesong

你可以问问 @cielpy 如何解决
https://github.com/vernesong/OpenClash/pull/1318/files

**Comment by hexin-lin-1024** [comment]
如图示，并未使用OpenClash(是在OpenWRT里单独跑一个Clash)。
使用TProxy监听7895端口，不代理本机。成功让Clash接管IPv6。
![image](https://user-images.githubusercontent.com/87570146/129702379-ac6814c1-bae4-4171-a4ac-ed5e96fcd359.png)
等有空交个PR吧。

**Comment by hexin-lin-1024** [comment]
不方便测试，请问有没有人可以帮助我查看IPv6 UDP是否正常转发。(文件适用于0.43.01-beta)
[openclash.zip](https://github.com/vernesong/OpenClash/files/7000490/openclash.zip)
在配置文件中加入tproxy-port，解压ZIP文件后替换/etc/init.d/openclash，然后重启OpenClash即可。
在我的机器上，IPv6 [TCP]被正常接管并转发。

**Comment by cielpy** [comment]
https://github.com/vernesong/OpenClash/pull/1318 之前我写过相关的功能，并且自己测试是正常工作的，提了 PR，不过作者似乎没有意愿合并，现在我将这部分代码改后了自用的 luci-app-clash 里，用起来挺好的

https://github.com/cielpy/luci-app-clash/tree/master 自的 luci-app-clash 代码在这

**Comment by hexin-lin-1024** [comment]
> #1318 之前我写过相关的功能，并且自己测试是正常工作的，提了 PR，不过作者似乎没有意愿合并，现在我将这部分代码改后了自用的 luci-app-clash 里，用起来挺好的
> 
> https://github.com/cielpy/luci-app-clash/tree/master 自的 luci-app-clash 代码在这

感谢回复。#1318 的代码我用过，但是似乎在我的设备上不工作，然后我看到后面也没有动静了，又希望用上IPv6，就提了这个issue。感谢您提供的Clash，这对我来说是个好的解决方案。

**Comment by cielpy** [comment]
> > #1318 之前我写过相关的功能，并且自己测试是正常工作的，提了 PR，不过作者似乎没有意愿合并，现在我将这部分代码改后了自用的 luci-app-clash 里，用起来挺好的
> > https://github.com/cielpy/luci-app-clash/tree/master 自的 luci-app-clash 代码在这
> 
> 感谢回复。#1318 的代码我用过，但是似乎在我的设备上不工作，然后我看到后面也没有动静了，又希望用上 IPv6，就提了这个 issue。感谢您提供的 Clash，这对我来说是个好的解决方案。

你可以试用一下 luci-app-clash，#1318 里也有打好的包，其实是一样的

下面是我刚刚截图的，我的环境里，直接通过 IPv6 访问的情况，是可以正常访问的
![CleanShot 2021-08-17 at 23 23 41](https://user-images.githubusercontent.com/3138493/129754675-bf0e1075-e215-45e2-844d-94d4eda381f0.png)

**Comment by hexin-lin-1024** [comment]
> > > #1318 之前我写过相关的功能，并且自己测试是正常工作的，提了 PR，不过作者似乎没有意愿合并，现在我将这部分代码改后了自用的 luci-app-clash 里，用起来挺好的
> > > https://github.com/cielpy/luci-app-clash/tree/master 自的 luci-app-clash 代码在这
> > 
> > 
> > 感谢回复。#1318 的代码我用过，但是似乎在我的设备上不工作，然后我看到后面也没有动静了，又希望用上 IPv6，就提了这个 issue。感谢您提供的 Clash，这对我来说是个好的解决方案。
> 
> 你可以试用一下 luci-app-clash，#1318 里也有打好的包，其实是一样的
> 
> 下面是我刚刚截图的，我的环境里，直接通过 IPv6 访问的情况，是可以正常访问的
> ![CleanShot 2021-08-17 at 23 23 41](https://user-images.githubusercontent.com/3138493/129754675-bf0e1075-e215-45e2-844d-94d4eda381f0.png)

不知道为什么，我移植改动的代码到高版本的时候（包括直接使用#1318的包）总是打不开面板UI😂，还是换一个一劳永逸

**Comment by hexin-lin-1024** [comment]
> > > > #1318 之前我写过相关的功能，并且自己测试是正常工作的，提了 PR，不过作者似乎没有意愿合并，现在我将这部分代码改后了自用的 luci-app-clash 里，用起来挺好的
> > > > https://github.com/cielpy/luci-app-clash/tree/master 自的 luci-app-clash 代码在这
> > > 
> > > 
> > > 感谢回复。#1318 的代码我用过，但是似乎在我的设备上不工作，然后我看到后面也没有动静了，又希望用上 IPv6，就提了这个 issue。感谢您提供的 Clash，这对我来说是个好的解决方案。
> > 
> > 
> > 你可以试用一下 luci-app-clash，#1318 里也有打好的包，其实是一样的
> > 下面是我刚刚截图的，我的环境里，直接通过 IPv6 访问的情况，是可以正常访问的
> > ![CleanShot 2021-08-17 at 23 23 41](https://user-images.githubusercontent.com/3138493/129754675-bf0e1075-e215-45e2-844d-94d4eda381f0.png)
> 
> 不知道为什么，我移植改动的代码到高版本的时候（包括直接使用#1318的包）总是打不开面板UI😂，还是换一个一劳永逸

非常遗憾，它似乎并未工作。我不论在日志还是在连接中都找不到IPv6的踪迹。

**Comment by cielpy** [comment]
> > > > > #1318 之前我写过相关的功能，并且自己测试是正常工作的，提了 PR，不过作者似乎没有意愿合并，现在我将这部分代码改后了自用的 luci-app-clash 里，用起来挺好的
> > > > > https://github.com/cielpy/luci-app-clash/tree/master 自的 luci-app-clash 代码在这
> > > > 
> > > > 
> > > > 感谢回复。#1318 的代码我用过，但是似乎在我的设备上不工作，然后我看到后面也没有动静了，又希望用上 IPv6，就提了这个 issue。感谢您提供的 Clash，这对我来说是个好的解决方案。
> > > 
> > > 
> > > 你可以试用一下 luci-app-clash，#1318 里也有打好的包，其实是一样的
> > > 下面是我刚刚截图的，我的环境里，直接通过 IPv6 访问的情况，是可以正常访问的
> > > ![CleanShot 2021-08-17 at 23 23 41](https://user-images.githubusercontent.com/3138493/129754675-bf0e1075-e215-45e2-844d-94d4eda381f0.png)
> > 
> > 
> > 不知道为什么，我移植改动的代码到高版本的时候（包括直接使用 #1318 的包）总是打不开面板 UI😂，还是换一个一劳永逸
> 
> 非常遗憾，它似乎并未工作。我不论在日志还是在连接中都找不到 IPv6 的踪迹。

IPv6 默认是关闭的，需要手动打开，在设置-代理端口设置 页面，另外 DNS 也需要支持返回 AAAA 记录

**Comment by hexin-lin-1024** [comment]
> > > > > > #1318 之前我写过相关的功能，并且自己测试是正常工作的，提了 PR，不过作者似乎没有意愿合并，现在我将这部分代码改后了自用的 luci-app-clash 里，用起来挺好的
> > > > > > https://github.com/cielpy/luci-app-clash/tree/master 自的 luci-app-clash 代码在这
> > > > > 
> > > > > 
> > > > > 感谢回复。#1318 的代码我用过，但是似乎在我的设备上不工作，然后我看到后面也没有动静了，又希望用上 IPv6，就提了这个 issue。感谢您提供的 Clash，这对我来说是个好的解决方案。
> > > > 
> > > > 
> > > > 你可以试用一下 luci-app-clash，#1318 里也有打好的包，其实是一样的
> > > > 下面是我刚刚截图的，我的环境里，直接通过 IPv6 访问的情况，是可以正常访问的
> > > > ![CleanShot 2021-08-17 at 23 23 41](https://user-images.githubusercontent.com/3138493/129754675-bf0e1075-e215-45e2-844d-94d4eda381f0.png)
> > > 
> > > 
> > > 不知道为什么，我移植改动的代码到高版本的时候（包括直接使用 #1318 的包）总是打不开面板 UI😂，还是换一个一劳永逸
> > 
> > 
> > 非常遗憾，它似乎并未工作。我不论在日志还是在连接中都找不到 IPv6 的踪迹。
> 
> IPv6 默认是关闭的，需要手动打开，在设置-代理端口设置 页面，另外 DNS 也需要支持返回 AAAA 记录

DNS已经设置完成，不知道IPv6打开是不是指这里
![image](https://user-images.githubusercontent.com/87570146/129870330-4100bce4-bed4-4d99-9b9f-a233c5502418.png)
然而日志中没有任何关于IPv6的连接信息，我的使用方式是设定旁路网关，不作为主路由使用
![image](https://user-images.githubusercontent.com/87570146/129870575-3d4060ed-bfec-4081-9aef-2f1947f353cc.png)
不知是否有影响？
![image](https://user-images.githubusercontent.com/87570146/129871426-9cbe682d-dfb4-46ea-a78b-1486a8dec353.png)
此外注意到这段代码似乎没生效，因为Mangle表内容如下
![image](https://user-images.githubusercontent.com/87570146/129871563-b4a856c2-3317-480b-bf4b-07e627a4abd2.png)。

**Comment by hexin-lin-1024** [comment]
> > > > > > #1318 之前我写过相关的功能，并且自己测试是正常工作的，提了 PR，不过作者似乎没有意愿合并，现在我将这部分代码改后了自用的 luci-app-clash 里，用起来挺好的
> > > > > > https://github.com/cielpy/luci-app-clash/tree/master 自的 luci-app-clash 代码在这
> > > > > 
> > > > > 
> > > > > 感谢回复。#1318 的代码我用过，但是似乎在我的设备上不工作，然后我看到后面也没有动静了，又希望用上 IPv6，就提了这个 issue。感谢您提供的 Clash，这对我来说是个好的解决方案。
> > > > 
> > > > 
> > > > 你可以试用一下 luci-app-clash，#1318 里也有打好的包，其实是一样的
> > > > 下面是我刚刚截图的，我的环境里，直接通过 IPv6 访问的情况，是可以正常访问的
> > > > ![CleanShot 2021-08-17 at 23 23 41](https://user-images.githubusercontent.com/3138493/129754675-bf0e1075-e215-45e2-844d-94d4eda381f0.png)
> > > 
> > > 
> > > 不知道为什么，我移植改动的代码到高版本的时候（包括直接使用 #1318 的包）总是打不开面板 UI😂，还是换一个一劳永逸
> > 
> > 
> > 非常遗憾，它似乎并未工作。我不论在日志还是在连接中都找不到 IPv6 的踪迹。
> 
> IPv6 默认是关闭的，需要手动打开，在设置-代理端口设置 页面，另外 DNS 也需要支持返回 AAAA 记录

在我的机器上防火墙设置出现问题，（这应该不是程序的问题）因为我将条件改为真时也不进行操作，另外请您赐教#1318中openclash_output链的作用，我删了相关规则之后正常了。

**Comment by cielpy** [comment]
> > > > > > > #1318 之前我写过相关的功能，并且自己测试是正常工作的，提了 PR，不过作者似乎没有意愿合并，现在我将这部分代码改后了自用的 luci-app-clash 里，用起来挺好的
> > > > > > > https://github.com/cielpy/luci-app-clash/tree/master 自的 luci-app-clash 代码在这
> > > > > > 
> > > > > > 
> > > > > > 感谢回复。#1318 的代码我用过，但是似乎在我的设备上不工作，然后我看到后面也没有动静了，又希望用上 IPv6，就提了这个 issue。感谢您提供的 Clash，这对我来说是个好的解决方案。
> > > > > 
> > > > > 
> > > > > 你可以试用一下 luci-app-clash，#1318 里也有打好的包，其实是一样的
> > > > > 下面是我刚刚截图的，我的环境里，直接通过 IPv6 访问的情况，是可以正常访问的
> > > > > ![CleanShot 2021-08-17 at 23 23 41](https://user-images.githubusercontent.com/3138493/129754675-bf0e1075-e215-45e2-844d-94d4eda381f0.png)
> > > > 
> > > > 
> > > > 不知道为什么，我移植改动的代码到高版本的时候（包括直接使用 #1318 的包）总是打不开面板 UI😂，还是换一个一劳永逸
> > > 
> > > 
> > > 非常遗憾，它似乎并未工作。我不论在日志还是在连接中都找不到 IPv6 的踪迹。
> > 
> > 
> > IPv6 默认是关闭的，需要手动打开，在设置 - 代理端口设置 页面，另外 DNS 也需要支持返回 AAAA 记录
> 
> 在我的机器上防火墙设置出现问题，（这应该不是程序的问题）因为我将条件改为真时也不进行操作，另外请您赐教 #1318 中 openclash_output 链的作用，我删了相关规则之后正常了。

output 链的操作主要是为了代理路由器本身流量

**Comment by hexin-lin-1024** [comment]
> > > > > > > > #1318 之前我写过相关的功能，并且自己测试是正常工作的，提了 PR，不过作者似乎没有意愿合并，现在我将这部分代码改后了自用的 luci-app-clash 里，用起来挺好的
> > > > > > > > https://github.com/cielpy/luci-app-clash/tree/master 自的 luci-app-clash 代码在这
> > > > > > > 
> > > > > > > 
> > > > > > > 感谢回复。#1318 的代码我用过，但是似乎在我的设备上不工作，然后我看到后面也没有动静了，又希望用上 IPv6，就提了这个 issue。感谢您提供的 Clash，这对我来说是个好的解决方案。
> > > > > > 
> > > > > > 
> > > > > > 你可以试用一下 luci-app-clash，#1318 里也有打好的包，其实是一样的
> > > > > > 下面是我刚刚截图的，我的环境里，直接通过 IPv6 访问的情况，是可以正常访问的
> > > > > > ![CleanShot 2021-08-17 at 23 23 41](https://user-images.githubusercontent.com/3138493/129754675-bf0e1075-e215-45e2-844d-94d4eda381f0.png)
> > > > > 
> > > > > 
> > > > > 不知道为什么，我移植改动的代码到高版本的时候（包括直接使用 #1318 的包）总是打不开面板 UI😂，还是换一个一劳永逸
> > > > 
> > > > 
> > > > 非常遗憾，它似乎并未工作。我不论在日志还是在连接中都找不到 IPv6 的踪迹。
> > > 
> > > 
> > > IPv6 默认是关闭的，需要手动打开，在设置 - 代理端口设置 页面，另外 DNS 也需要支持返回 AAAA 记录
> > 
> > 
> > 在我的机器上防火墙设置出现问题，（这应该不是程序的问题）因为我将条件改为真时也不进行操作，另外请您赐教 #1318 中 openclash_output 链的作用，我删了相关规则之后正常了。
> 
> output 链的操作主要是为了代理路由器本身流量

感谢指教，最后还有一个疑问：使用我这个防火墙规则（跟您 #1318 中的几乎一样)
ip -6 rule add fwmark 1 table 106
ip -6 route add local ::/0 dev lo table 106
ip6tables -t mangle -N openclash
ip6tables -t mangle -A openclash -m set --match-set localnetwork6 dst -j RETURN
ip6tables -t mangle -A openclash -p tcp -j TPROXY --on-port 7895 --tproxy-mark 1
ip6tables -t mangle -A openclash -p udp -j TPROXY --on-port 7895 --tproxy-mark 1
ip6tables -t mangle -A PREROUTING -j openclash
可以正确代理IPv6，那么它对UDP的支持会有问题吗，以及在Clash中似乎不能识别域名，原因是什么？

**Comment by cielpy** [comment]
UDP 在这个功能里，不特殊

ip6tables -t mangle -A openclash -p udp -j TPROXY --on-port 7895 --tproxy-mark 1

有了一这条，就支持 UDP 了

clash 不能识别域名，一般是因为 DNS 没有交给 clash

clash 识别域名的原理是接收客户端的 DNS 请求，并把 IP 返回给客户端，并把域名和 IP 做一个缓存映射，接下来 clash 就可以根据客户端要访问的 IP在映射里查询，得到其想访问的域名

**Comment by hexin-lin-1024** [comment]
> UDP 在这个功能里，不特殊
> 
> ip6tables -t mangle -A openclash -p udp -j TPROXY --on-port 7895 --tproxy-mark 1
> 
> 有了一这条，就支持 UDP 了
> 
> clash 不能识别域名，一般是因为 DNS 没有交给 clash
> 
> clash 识别域名的原理是接收客户端的 DNS 请求，并把 IP 返回给客户端，并把域名和 IP 做一个缓存映射，接下来 clash 就可以根据客户端要访问的 IP在映射里查询，得到其想访问的域名

我目前的配置如下：
ipset create localnetwork hash:net
ipset add localnetwork 0.0.0.0/8
ipset add localnetwork 10.0.0.0/8
ipset add localnetwork 100.64.0.0/10
ipset add localnetwork 127.0.0.0/8
ipset add localnetwork 169.254.0.0/16
ipset add localnetwork 172.16.0.0/12
ipset add localnetwork 192.0.0.0/24
ipset add localnetwork 192.0.2.0/24
ipset add localnetwork 192.88.99.0/24
ipset add localnetwork 192.168.0.0/16
ipset add localnetwork 198.18.0.0/15
ipset add localnetwork 198.51.100.0/24
ipset add localnetwork 203.0.113.0/24
ipset add localnetwork 223.255.255.0/24
ipset add localnetwork 224.0.0.0/4
ipset add localnetwork 240.0.0.0/4
ipset add localnetwork 255.255.255.255/32
wan_ip4s=$(ifconfig | grep 'inet addr' | awk '{print $2}' | cut -d: -f2 | grep -vE "(^198.18|^192.168|^127.0)")
if [ -n "$wan_ip4s" ]; then
    for wan_ip4 in $wan_ip4s; do
        ipset add localnetwork "$wan_ip4"
    done
fi
ip rule add fwmark 1 table 100
ip route add local 0.0.0.0/0 dev lo table 100
iptables -t mangle -N openclash
iptables -t mangle -F openclash
#iptables -t mangle -A openclash -p udp --dport 7874 -j TPROXY --on-port 7874 --tproxy-mark 1
#iptables -t mangle -A openclash -p udp --dport 53 -j TPROXY --on-port 7874 --tproxy-mark 1
iptables -t mangle -A openclash -m set --match-set localnetwork dst -j RETURN
iptables -t mangle -A openclash -p tcp -j TPROXY --on-port 7895 --tproxy-mark 1
iptables -t mangle -A openclash -p udp -j TPROXY --on-port 7895 --tproxy-mark 1
iptables -t mangle -A PREROUTING -j openclash
ipset create localnetwork6 hash:net family inet6
ipset add localnetwork6 ::/128
ipset add localnetwork6 ::1/128
ipset add localnetwork6 ::ffff:0:0/96
ipset add localnetwork6 ::ffff:0:0:0/96
ipset add localnetwork6 64:ff9b::/96
ipset add localnetwork6 100::/64
ipset add localnetwork6 2001::/32
ipset add localnetwork6 2001:20::/28
ipset add localnetwork6 2001:db8::/32
ipset add localnetwork6 2002::/16
ipset add localnetwork6 fc00::/7
ipset add localnetwork6 fe80::/10
ipset add localnetwork6 ff00::/8
wan_ip6s=$(ifconfig | grep 'inet6 addr' | awk '{print $3}')
if [ -n "$wan_ip6s" ]; then
    for wan_ip6 in $wan_ip6s; do
        ipset add localnetwork6 "$wan_ip6"
    done
fi
ip -6 rule add fwmark 1 table 106
ip -6 route add local ::/0 dev lo table 106
ip6tables -t mangle -N openclash
ip6tables -t mangle -F openclash
#ip6tables -t mangle -A openclash -p udp --dport 7874 -j TPROXY --on-port 7874 --tproxy-mark 1
#ip6tables -t mangle -A openclash -p udp --dport 53 -j TPROXY --on-port 7874 --tproxy-mark 1
ip6tables -t mangle -A openclash -m set --match-set localnetwork6 dst -j RETURN
ip6tables -t mangle -A openclash -p tcp -j TPROXY --on-port 7895 --tproxy-mark 1
ip6tables -t mangle -A openclash -p udp -j TPROXY --on-port 7895 --tproxy-mark 1
ip6tables -t mangle -A PREROUTING -j openclash

Clash DNS监听7874，但是我现在Clash是完全识别不了域名的状态，请问应该怎么解决

**Comment by cielpy** [comment]
你 DNS 转发到 7874 了吗

**Comment by hexin-lin-1024** [comment]
> 你 DNS 转发到 7874 了吗

在DHCP/DNS中转发到127.0.0.1#7874

**Comment by vernesong** [comment]
#1318 @cielpy 可以重开，我有空再做下其他适配工作

**Comment by hcym** [comment]
感谢各位帅哥🤓

**Comment by hcym** [comment]
今天编的可以正常使用ipv6节点😂

**Comment by hexin-lin-1024** [comment]
#1318 already merged. Close issue.

**Comment by hexin-lin-1024** [comment]
> 今天编的可以正常使用ipv6节点😂

能给下ipk吗，不方便编译，谢谢🙏。
