### ISSUE TITLE
如何在机场订阅的基础上，修改部分网站的访问方式？

### ISSUE THREAD

**Issue by iamjimmycheng** [vernesong/OpenClash#1485]
如何在机场订阅的基础上，修改部分网站的访问方式？

有些网站想改成direct，不走代理，如果改了yaml，机场订阅更新后又会被覆盖，这要怎么修改呢？

**Comment by peach-water** [comment]
+1，同样的需求。

**Comment by icolourful** [comment]
规则设置里改

**Comment by peach-water** [comment]
怎么做，可以详细一点吗：

比如我想要用节点访问baidu.com(假设)，我应该在规则集添加哪些东西

之前单纯的在规则集与组策略管理添加一条，不太行。

**Comment by fjjking** [comment]
1.使用全局设置里面的规则设置
2.在服务器与策略组管理里点击保留配置（但是这样做会永远不更新机场的规则只会更新节点了 后续需要自己维护）
