### ISSUE TITLE
更新v0.42.08-beta 后出错

### ISSUE THREAD

**Issue by othelloYu** [vernesong/OpenClash#1487]
![屏幕截图 2021-07-21 223056](https://user-images.githubusercontent.com/66551982/126506302-a4fe33d1-8f9e-4c55-9afb-0b94dadf05f7.jpg)
**更新后打开openclash出错。**
/usr/lib/lua/luci/dispatcher.lua:469: Failed to execute function dispatcher target for entry '/admin/services/openclash'.
The called action terminated with an exception:
/usr/lib/lua/luci/dispatcher.lua:469: Failed to execute cbi dispatcher target for entry '/admin/services/openclash/client'.
The called action terminated with an exception:
/usr/lib/lua/luci/model/cbi/openclash/client.lua:56: bad argument #1 to 'sub' (string expected, got nil)
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:469: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:121: in function </usr/lib/lua/luci/dispatcher.lua:120>

**Comment by othelloYu** [comment]
好像触发错误的原因是：点击了如遇到配置丢失或者需要还原默认配置，请尝试访问地址: http://***.***.***.***/cgi-bin/luci/admin/services/openclash/restore

**Comment by HowardKwan** [comment]
同样遇到此问题，只得恢复备份才得以继续使用，尝试了几次，现在完全是不能点击版本更新这个页面了！！
