### ISSUE TITLE
openclash lua bug!  v0.42.08-beta

### ISSUE THREAD

**Issue by nawirwii** [vernesong/OpenClash#1488]
/usr/lib/lua/luci/dispatcher.lua:469: Failed to execute cbi dispatcher target for entry '/admin/services/openclash/config'.
The called action terminated with an exception:
/usr/lib/lua/luci/model/cbi/openclash/config.lua:333: bad argument #1 to 'basename' (string expected, got nil)
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:469: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:121: in function </usr/lib/lua/luci/dispatcher.lua:120>

**Comment by 507979716** [comment]
更新的都遇到了这个致命性的bug
