### ISSUE TITLE
openwrt openclash 更新到 v0.42.09-beta 出大问题了。。

### ISSUE THREAD

**Issue by peter123456789** [vernesong/OpenClash#1489]
openwrt openclash 更新到 v0.42.09-beta 出大问题了。。 如图：

![image](https://user-images.githubusercontent.com/12538824/126580364-c0d1989e-b6d4-4a31-97ce-5222f0a779fd.png)

**Comment by woaihsw** [comment]
是的, 强迫症好难受...

**Comment by zhengwenxiao** [comment]
把这个文件 最后一个字符s删掉就好了
/usr/share/openclash/res/openclash_version

**Comment by peter123456789** [comment]
不是每一个用户都有动手能力的、而且在客户端修改不是永久方案
