### ISSUE TITLE
[Feature] localnetwork 希望可以用户配置额外 notmatch.

### ISSUE THREAD

**Issue by Ariesly** [vernesong/OpenClash#1490]
1. 有些时候，网络中希望部分内网网段走clash规则. 比如: 比如桥连2个家这间的内网.
[luci-app-openclash/root/etc/init.d/openclash#L1362L1370](https://github.com/vernesong/OpenClash/blob/master/luci-app-openclash/root/etc/init.d/openclash#L1362L1370)

**Comment by vernesong** [comment]
路由表内的cidr自动添加

**Comment by Ariesly** [comment]
这里 cidr 是添加直连的
这边考虑的是需要部分地址经过clash的路由
如:
ipset add localnetwork 192.168.0.0/30 nomatch

**Comment by vernesong** [comment]
> 这里 cidr 是添加直连的 这边考虑的是需要部分地址经过clash的路由 如: ipset add localnetwork 192.168.0.0/30 nomatch

会用到的人不多，可以尝试自己修改脚本先用
