### ISSUE TITLE
上一次老大帮忙解决这个问题，以为添加本地dns就解决微信刷图慢的问题，其实是我无意中取消 禁用QUIC 这个选项然后一切都正常了

### ISSUE THREAD

**Issue by eason39** [vernesong/OpenClash#1493]
希望老大尽快修复这个问题 谢谢

**Comment by jiatianxa** [comment]
我这里朋友圈图片也是加载慢!

**Comment by eason39** [comment]
> 我这里朋友圈图片也是加载慢!

关闭禁用QUIC 试试

**Comment by eason39** [comment]
不过感觉禁用QUIC 开youtube是要慢一点

**Comment by vernesong** [comment]
不开就正常了？

**Comment by siren202101** [comment]
``
![QQ图片20210730233525](https://user-images.githubusercontent.com/80493699/127676968-efa07cfb-f958-42e7-8b00-da68b206e9b6.png)
我是这样解决的，不知道正不正确，反正没有微信加载转圈圈的问题

**Comment by eason39** [comment]
> 不开就正常了？

不开就正常了  图片秒刷

**Comment by eason39** [comment]
> ``
> ![QQ图片20210730233525](https://user-images.githubusercontent.com/80493699/127676968-efa07cfb-f958-42e7-8b00-da68b206e9b6.png)
> 我是这样解决的，不知道正不正确，反正没有微信加载转圈圈的问题
你也遇到微信图片转圈问题吗？

**Comment by w12928293** [comment]
> > 不开就正常了？
> 
> 不开就正常了 图片秒刷

原来是禁用QUIC的问题，困扰我好久了

**Comment by spacex715** [comment]
我这里测试了，之前也是微信图片打开巨慢，现在取消 禁用QUIC，微信图片什么的就能秒开了。

**Comment by saint369** [comment]
给这个问题困扰好久了··各种折腾。原来是这个原因。谢谢楼主

**Comment by pizzamx** [comment]
> 我这里测试了，之前也是微信图片打开巨慢，现在取消 禁用QUIC，微信图片什么的就能秒开了。

好像确实是啊，跟 DNS 没关系……
