### ISSUE TITLE
OpenClash 运行模式始终处于正在收集数据...	状态

### ISSUE THREAD

**Issue by LarkinZero** [vernesong/OpenClash#1496]
<img width="433" alt="Xnip2021-07-25_20-50-37" src="https://user-images.githubusercontent.com/6387162/126899679-5aab03d7-11c7-4f06-88b1-28c6111f0c4c.png">
v0.42.09

查看报错信息有这个404
![image](https://user-images.githubusercontent.com/6387162/126899749-314963f5-b988-4a48-8d74-cf41c9673074.png)

**Comment by vernesong** [comment]
看一下404错误具体返回的内容

**Comment by LarkinZero** [comment]
```
No page is registered at '/admin/services/openclash/dler_info'.
If this url belongs to an extension, make sure it is properly installed.
If the extension was recently installed, try removing the /tmp/luci-indexcache file.
```

**Comment by vernesong** [comment]
重启或者重装

**Comment by LarkinZero** [comment]
> 重启或者重装

重装后正常了
