### ISSUE TITLE
在线转换 建议加入 地区节点 分组功能

### ISSUE THREAD

**Issue by ltdstudio** [vernesong/OpenClash#1501]
建议在
编辑配置文件订阅信息
里面的 在线转换处加入  国家/地区 节点分类功能。（示例：https://sub.tsutsu.cc/  https://id9.cc/）
比如增加 香港 /日本 /美国 把 节点带有 香港 or hongkong/ 日本 or japan /美国 America us 的节点归一类。
不知道 clash.net 这个软件 是怎么做到的。
非常实用。比如我把我的机场全部导入到一个配置里面。选择香港分组，然后就自动测速选择香港最快的。可以不手动切换节点并且保持一直在香港区域。

我去看了下clash.net 的后端也是自己集成了（Clash .NET 1.2.3\Bin\SubConverter）。如果能够考虑把后端也集成了。感谢。

**Comment by vernesong** [comment]
如您有值得推荐的外部配置文件(订阅转换模板)，可以按照 /usr/share/openclash/res/sub_ini.list 的文件格式修改后提交PR

**Comment by siren202101** [comment]
> 建议在
> 编辑配置文件
> 处订阅信息里面的在线转换加入国家/地区节点分类功能。（示例：[https ](https://sub.tsutsu.cc/) [:](https://id9.cc/%EF%BC%89) //sub.tsutsu.cc/ [https://id9.cc/）](https://id9.cc/%EF%BC%89)
> 例如增加香港/日本/美国把节点伴随香港或香港/日本或日本美国美国我们的节点/糖果。
> 不知道冲突.net这个软件是怎么做到的。
> 非常实用。比如我把我的机场全部导入到一个配置里面。香港重点，然后就自动测速选择香港重点的。可以不手动切换节点并且一直保持在香港区域。
> 
> 我去下clash.net 的完整也是自己集成了（Clash .NET 1.2.3\Bin\SubConverter）。如果能够考虑的话也集成了。感谢。

分组的话我记得是根据您的节点名称来判定的，例如香港=HK,奈飞=NF,节点名包含这些信息会分类到相对于的分组里，在线订阅转换选择全分组重度用户就可以，SubConverter可以本地电脑直接打开windows版或软路由docker版，在openclash里自定义http://IP:25500/sub  ###是http:// 不是https://
windows版需要开放25500端口

**Comment by daveleeyee2022** [comment]
同求！希望朋友们提供节点国家分组的模板
