### ISSUE TITLE
设置局域网IP直连了但是有些却还是走代理

### ISSUE THREAD

**Issue by siren202101** [vernesong/OpenClash#1507]
- SRC-IP-CIDR,192.168.1.200/32,DIRECT
- SRC-IP-CIDR,192.168.1.1/32,DIRECT
设置完后192.168.1.1路由还是能curl -vv www.google.com
192.168.1.200这个设备的还是能打开油管
是不是因为我开启仅命中代理所以才这样？
![QQ截图20210729023137](https://user-images.githubusercontent.com/80493699/127678613-4ef09122-c4da-4646-956e-d95ecb1d8b87.png)

**Comment by vernesong** [comment]
根据日志分析，这样测不准
