### ISSUE TITLE
服务器与策略组管理

### ISSUE THREAD

**Issue by Karmylr** [vernesong/OpenClash#1509]
在配置文件从订阅链接处更新后，会按照服务器与策略组管理你设置的，自定义的策略租来修改配置文件。这是给非常强大的功能。但是我发现在更新订阅并且按照自己的带你租修改玩配置文件后，订阅链接里订阅不出来的（删掉的节点）还会被保留，需要手动点击清空服务器配置来清空，再订阅并修改一遍。这样有点麻烦。能不能在脚本里加上清空服务器配置这一项计划呢？

**Comment by vernesong** [comment]
1.enable keep setting
![image](https://user-images.githubusercontent.com/42875168/127779372-004db6cd-6613-4163-af4e-b7d21c3c67a3.png)
2.read your config
![image](https://user-images.githubusercontent.com/42875168/127779382-990f6581-8c13-4ac3-a6f7-77d2c055373d.png)
3.custom yourself and save
4.re subscribe immediately (let openclash know which proxy is not a manual added )
5.done
