### ISSUE TITLE
更新v0.36.6-beta并升级内核后网络频繁断流

### ISSUE THREAD

**Issue by necoic** [vernesong/OpenClash#151]
Yacd后台输入密码后无法跳转，Dashboard无法访问，网络频繁断流。

**Comment by bigbighill** [comment]
同样的问题

**Comment by vernesong** [comment]
日志呢？

**Comment by thank243** [comment]
Sun Feb 16 17:39:14 2020 kern.info kernel: [39589.250796] TCP: request_sock_TCP: Possible SYN flooding on port 53. Sending cookies.  Check SNMP counters.
Sun Feb 16 17:39:14 2020 kern.info kernel: [39589.272309] TCP: request_sock_TCP: Possible SYN flooding on port 7892. Sending cookies.  Check SNMP counters.

莫名其妙出现。。。

**Comment by vernesong** [comment]
我重新上传了内核和ipk，可能是压缩的问题

**Comment by necoic** [comment]
下载更新的内核和ipk问题解决
