### ISSUE TITLE
openclash开启后github连接不上

### ISSUE THREAD

**Issue by murongchenxing** [vernesong/OpenClash#152]
使用的k3路由器刷的lede系统，选择内核订阅配置并应用后YouTube，google等网站均可打开，但是打不开github，浏览器显示如下图：
![Inked123_LI](https://user-images.githubusercontent.com/34703295/74632336-16598380-519a-11ea-80bf-a4d8c77209e7.jpg)
如果电脑再单独开代理的话可以打开github，但是关了代理通过路由器的代理就打不开，路由器里openclash的网站访问检索里，github也是显示连接超时，但是同一局域网内的MacBook和手机都可以不另开代理打开github。
代理配置文件设置了domainkeyword匹配和domain域名匹配，通过看控制面板里的流量情况，电脑打开github时也是走的代理，如图：
![Inked1234_LI](https://user-images.githubusercontent.com/34703295/74632345-1c4f6480-519a-11ea-984c-ef1946c44bc4.jpg)
请问是什么原因，应该如何设置，谢谢。

**Comment by vernesong** [comment]
什么模式

**Comment by murongchenxing** [comment]
代理模式是rule策略代理，运行模式是fake ip（增强）模式。

**Comment by vernesong** [comment]
建议清理一下电脑dns缓存和切换一下节点，fake模式下的代理连接是交给节点在远程解析的，一般不存在污染。

**Comment by murongchenxing** [comment]
用ipconfig/flushdns清了一下，换了节点还是不行，同样的节点，路由器代理就不行，电脑的客户端就可以，也是很奇怪了。

**Comment by vernesong** [comment]
fake-ip模式，首先nslookup或者dig一下github的地址，获得一个fake-ip,然后crul一下
`crul -H "Host:www.github.com" fake-ip`

**Comment by murongchenxing** [comment]
是在cmd操作吗，试了一下好像还是不行，换用passwall了，还是谢谢你。

**Comment by vernesong** [comment]
路由ssh命令

**Comment by yaleyip** [comment]
我也遇到谷歌、脸书都行，就github不行。我是这么解决：
“全局设置-->DNS设置-->高级设置”，选取“关闭”，或者“开启”但保留默认黑名单DNS服务器114.114.114.114（估计其他服务器解析有问题）。

**Comment by jy1024898670-lang** [comment]
> fake-ip模式，首先nslookup或者dig一下github的地址，获得一个fake-ip,然后curl一下 `curl -H "Host:www.github.com" fake-ip`

非常有用！！！这是什么原理？加了host？
