### ISSUE TITLE
求教：虚拟机使用WiFi连接主路由的情况下无法联网，网线可以

### ISSUE THREAD

**Issue by ghgds** [vernesong/OpenClash#1521]
网络拓扑如图，主路由不方便拉网线到电脑，所以使用WiFi连接，但此时宿主机或手机设定网关到openclash，任何网络都无法访问。但如果宿主机改用网线连接主路由，则宿主机和手机网络正常，都可以走openclash。
请教大佬应该如何操作？
主路由Ax86U，宿主机Lenovo X230

![image](https://user-images.githubusercontent.com/31283292/128620694-890d3562-f909-4ba6-a33f-2c46c9825fbf.png)

**Comment by vernesong** [comment]
wifi接口跟lan桥接一下

**Comment by ghgds** [comment]
感谢大佬回复，请问是在宿主机按下图这么操作吗？
![image](https://user-images.githubusercontent.com/31283292/128651825-cb6a256e-dd01-40e8-9fda-7de08c46f25e.png)
