### ISSUE TITLE
求教，raw.githubusercontent.com网站打不开，单独添加自定义规则走PROXY也不行。

### ISSUE THREAD

**Issue by lengfwang** [vernesong/OpenClash#1522]
如题，OpenClash 透明代理时打不开raw.githubusercontent.com，设成全局模式没问题，单独添加了一个自定义规则也打不开：

 “- DOMAIN-SUFFIX,raw.githubusercontent.com,PROXY”

在路由器上查了下，发现DNS返回0.0.0.0.，应该是本地运营商污染后的地址，似乎没有走代理。

  有人遇到这个问题吗？谢谢

**Comment by liofoil** [comment]
用fakeip或者自己改国外dns啊

**Comment by vernesong** [comment]
dns设置打开fallback filter

**Comment by MBRjun** [comment]
DNS污染，自己改，国内比较好的是腾讯119.29.29.29，如果不嫌慢试试8.8.8.8（谷歌）
