### ISSUE TITLE
局域网内设置DMZ后，只要开启openclash后NAT就不正常了，如何处理

### ISSUE THREAD

**Issue by shu0802** [vernesong/OpenClash#1523]
x86软路由上openwrt设置局域网内设置DMZ后，只要开启openclash后NAT就不正常了，但是关闭openclash后NAT就正常了。各位有没有遇到，要如何解决这个问题。
![1628479126(1)](https://user-images.githubusercontent.com/43750373/128657719-6c2704ed-70e5-42aa-bfc5-c834859fe3a3.jpg)
![1628479017(1)](https://user-images.githubusercontent.com/43750373/128657737-ff9c9732-273f-4c57-b279-b0355b500e18.jpg)
![1628479072(1)](https://user-images.githubusercontent.com/43750373/128657747-a5e1b594-ab31-4ec5-842c-acdfcb2a6270.jpg)
![1628479193(1)](https://user-images.githubusercontent.com/43750373/128657757-84b01110-27f1-42d5-b4e4-16928cde3957.jpg)
![1628479242(1)](https://user-images.githubusercontent.com/43750373/128657764-25d34bba-9cd0-4f2a-9def-59889cda7463.jpg)
![1628479615(1)](https://user-images.githubusercontent.com/43750373/128657770-cbb31665-c9f9-4193-8f58-5b82f56e45ea.png)
![1628479762(1)](https://user-images.githubusercontent.com/43750373/128657776-6bc46ffb-f137-4b8f-b7c2-08789e1f0a9a.jpg)

**Comment by deepfish** [comment]
你好，問一下這個 NAT 類型在哪看？我現在也是遇到問題，ikuai 主路由（IP：10.0.0.1，網管：10.0.0.251），openwrt（ip：10.0.0.251，網關 10.0.0.1），開啟 Openclash 之後，網絡中設備經常打不開網頁，但是偶爾刷新一下就行了。

**Comment by shu0802** [comment]
ikuai主路由的NAT不会有问题吧。我是用的openwrt主路由。
