### ISSUE TITLE
自定义规则(访问控制)的问题

### ISSUE THREAD

**Issue by siren202101** [vernesong/OpenClash#1524]
自定义规则(访问控制)下方有两个编辑框，到底应该在那个里面编辑？
![0](https://user-images.githubusercontent.com/80493699/128661109-ae8dde23-545a-43c0-b6bd-de7a4e00a139.png)
![1](https://user-images.githubusercontent.com/80493699/128661120-08f76c9a-b28f-4ea5-a4a4-9b4fb9f8ab6d.png)

**Comment by deepfish** [comment]
兩個都可以，看優先級的。例如規則放頂部，配置文件中有規則，還是按頂部的走。如果放底部，配置文件有規則，那按照配置文件走。
