### ISSUE TITLE
一键生成配置文件功能失效

### ISSUE THREAD

**Issue by YOU-Y8** [vernesong/OpenClash#1537]
从0.42.4（或6，记不清）版本升级到0.42.10后发现原配置文件反复启动失败，然后没办法只能重置了配置文件。但是发现在一键生成配置文件页面选ihie1规则或者connershua规则模板点应用都没有任何反应了，查看日志也没有记录。尝试过降低版本，发现也不行。不知道ihie1规则模板是不是要联网读取，是不是出问题了？
![捕获](https://user-images.githubusercontent.com/73763161/129580342-808aec70-c75f-4708-8581-a8ffeca9e12c.PNG)

**Comment by vernesong** [comment]
为这边是正常的

**Comment by YOU-Y8** [comment]
> 我这边是正常的

升级openwrt固件后又正常了。。。所以故障原因还是不知道，以后只能不自己升级openwrt了。另外混合节点如果节点数量很多似乎会导致启动失败。循环很多次后删减节点才能启动。
