### ISSUE TITLE
新版本点击切换配置报错

### ISSUE THREAD

**Issue by icetea0822** [vernesong/OpenClash#1538]
昨天更新的新版本0.43.01后，点击页面右上角的当前配置文件，会报下面这个错
![image](https://user-images.githubusercontent.com/12151645/129656312-e852fa2a-f49b-4a6f-89f3-0b1f6e8bb18e.png)
另外看到新增加了备份openclash功能，但是回复配置的按钮没有找到。。

**Comment by OleStore** [comment]
> 昨天更新的新版本0.43.01后，点击页面右上角的当前配置文件，会报下面这个错
> ![image](https://user-images.githubusercontent.com/12151645/129656312-e852fa2a-f49b-4a6f-89f3-0b1f6e8bb18e.png)
> 另外看到新增加了备份openclash功能，但是回复配置的按钮没有找到。。

确实报错，不过不影响
