### ISSUE TITLE
Openclash配合AdGuard Home使用时的一个小问题

### ISSUE THREAD

**Issue by kkfuzi** [vernesong/OpenClash#1539]
最近Openwrt换用了Openclash + AdGuard Home，参考的是组内讨论：
https://github.com/vernesong/OpenClash/issues/99

基本设置是：
Openclash: Redir-host 兼容模式，取消本地DNS劫持，用自定义上游DNS服务器.
AdGuard Home: 使用53端口替代dnsmasq，上游DNS服务器唯一且指向OC，127.0.0.1:7874

使用正常，分流等功能都没问题。

但碰到一个小事故，前几天Openclash自动升级配置的时候因为配置文件里的一个rule error导致Openclash无法启动，于是局域网内DNS就出问题了。局域网内设备都无法访问域名网站。个人猜测是因为这样的配合设置，Openclash承担了唯一的局域网内DNS服务器功能，所以OC没启动的话DNS就挂了。

所以想请教一下，在Openclash和AdGuard Home这样的搭配下，有没有一个在Openclash无法启动的情况下还能保证上网功能的备用设置？如果在AGH的上游DNS里加上比如114或者其他公共DNS，好像会导致不稳定？

PS我目前是直接注释掉了防火墙的转发规则
iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53
iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53

谢谢。

**Comment by vernesong** [comment]
那就让OC转发到adg

**Comment by kkfuzi** [comment]
> 那就让OC转发到adg

谢谢回复。是不是可以理解成就把目前OC和ADH的顺序互换，OC的自定义上游DNS指到ADH，ADH填写上游DNS服务器完成解析？

这样的设计：
1. OC的DNS分流就不起作用了，完全看ADH的上游DNS服务器，在分流效率上会不会打折？
2. OC的比如Fake-IP模式下不是所有的DNS请求都会发送到设置的DNS，那会不会影响部分解析？

还是在纠结哪种选择更好。谢谢！

**Comment by vernesong** [comment]
分流不会影响，在clash已经完成，只是在adg无法看到客户端的情况
DNS其实只是辅助分流的作用，域名命中规则后会直接给代理解析，没有命中规则的才会走DNS按照国内外IP判断

**Comment by kkfuzi** [comment]
> 分流不会影响，在clash已经完成，只是在adg无法看到客户端的情况
> DNS其实只是辅助分流的作用，域名命中规则后会直接给代理解析，没有命中规则的才会走DNS按照国内外IP判断

了解了，谢谢老大！

**Comment by iceye2072** [comment]
> 分流不会影响，在clash已经完成，只是在adg无法看到客户端的情况
> DNS其实只是辅助分流的作用，域名命中规则后会直接给代理解析，没有命中规则的才会走DNS按照国内外IP判断

请问开启openclash以后，本地dhcp下的上游dns还用填ADH的dns吗？是不是OC已经劫持了所有dns流量了

**Comment by jikkyfu** [comment]
> > 分流不会影响，在clash已经完成，只是在adg无法看到客户端的情况
> > DNS其实只是辅助分流的作用，域名命中规则后会直接给代理解析，没有命中规则的才会走DNS按照国内外IP判断
> 
> 请问开启openclash以后，本地dhcp下的上游dns还用填ADH的dns吗？是不是OC已经劫持了所有dns流量了

本地的DNS应该被ADH劫持了

**Comment by taoqixfz** [comment]
@kkfuzi 问一下你弄完Clash和AdGuardHome之后，把路由器重启还能正常使用吗？
