### ISSUE TITLE
新版本界面上的一个小疑问（不影响功能使用）

### ISSUE THREAD

**Issue by liofoil** [vernesong/OpenClash#1540]
在0.43.01版本中，开启redir-host兼容模式，会在运行状态页面会出现三个点，似乎在加载什么，但又一直加载不出。不影响正常使用，甚至。。不确定这是不是装饰
![Screenshot 2021-08-17 181543](https://user-images.githubusercontent.com/53076556/129708723-bb5e2c0e-5229-4955-94e2-2245773256b3.png)
因为不确定这是不是bug，如果有必要，我会贴出更详细的日志

**Comment by liofoil** [comment]
似乎是原先的显示更多按钮，如果是作者的预期行为，我会立即关闭issue

**Comment by ForestL18** [comment]
的确是更多选项，但是看着很奇怪，感觉界面没有加载完一样

**Comment by 596142041** [comment]
昨晚更新之后也是同样的现象，以为是有什么一直在加载中

**Comment by Seth2333** [comment]
Fakeip 模式也有同样的情况

**Comment by liofoil** [comment]
新版本已更新，无修改，判定为预期行为
