### ISSUE TITLE
fake-ip访问节点自身 dns解析不出

### ISSUE THREAD

**Issue by hdchieh** [vernesong/OpenClash#1541]
我使用fake-ip模式无法访问到我作为proxy，同时又为管理界面的服务器。
这可能不算是一个bug，只是不太方便。
我换了个prefix解析到同一个ip可以访问，算是勉强解决了这个问题。

**Comment by vernesong** [comment]
dns高级设置

**Comment by hdchieh** [comment]
> dns高级设置

嗯 可以的。也就是说这不算一个bug是吧。谢谢

**Comment by vernesong** [comment]
DNS问题需要看下日志，可能是判定问题
