### ISSUE TITLE
开启openclash之后网速变慢

### ISSUE THREAD

**Issue by 596142041** [vernesong/OpenClash#1542]
在没有开启之前，使用speedtest测试能达到220M,开启之后进行测试只能达到50M,这是哪儿设置不对么

**Comment by vernesong** [comment]
性能瓶颈

**Comment by NathanDai** [comment]
我的也一样 fast只能跑2.5m cpu吃满一半
![image](https://user-images.githubusercontent.com/28701315/130309418-4186a1ba-2078-47a8-ad97-0e71b337888e.png)
