### ISSUE TITLE
磁力链接（magnet）无法下载

### ISSUE THREAD

**Issue by pizzamx** [vernesong/OpenClash#1544]
刚开始用 openclash，发现磁链无法连接服务器，现在只能先停用，连上服务器，再重新打开。下载不受影响。

网上搜了一圈没发现有这个问题的，不知道是不是哪里配置不对影响了 UDP 协议。冒昧提问，望高人指点，谢谢！

**Comment by wudj1967** [comment]
打开UDP流量转发

**Comment by pizzamx** [comment]
> 打开UDP流量转发

已经选中的。明白了，内核要选“Redir-Host（TUN-混合）模式”……多谢！
