### ISSUE TITLE
爱快主路由op旁路使用OpenClash.google打不开网飞却正常

### ISSUE THREAD

**Issue by 292905546** [vernesong/OpenClash#1545]
还有油管能打开 但是视频无法播放
有人说是op防火墙设置问题
本人小白有没有大神指点一下

**Comment by vernesong** [comment]
确保是clash解析DNS

**Comment by 292905546** [comment]
> 确保是冲突解析DNS

感谢大佬解答！可以指导一下怎么设置吗 谢谢

**Comment by vernesong** [comment]
保证你的DNS是给Clash解析的啊，不要被其他DNS插件或者DNS加速、分流啥的抢走了

**Comment by 292905546** [comment]
> 保证你的DNS是给Clash解析的啊，不要被其他DNS插件或者DNS加速、分流啥的抢走了

非常感谢！是爱快开启了DNS加速服务。关闭就好了！！
我爱快也是照搬网上教程设置的....
非常感谢 已经解决了
