### ISSUE TITLE
openclash升级后无法启动

### ISSUE THREAD

**Issue by lyricusark** [vernesong/OpenClash#1547]
openwrt里集成的openclash升级后就无法启动了，之前都没问题，就最近升级v0.43.01-beta及最新内核后就崩溃了，日志如下：

	github.com/Dreamacro/clash/listener/http/server.go:61 +0x84
created by github.com/Dreamacro/clash/listener/http.NewWithAuthenticate.func1
	github.com/Dreamacro/clash/listener/http/proxy.go:32 +0x2c8
github.com/Dreamacro/clash/listener/http.HandleConn({0x55f818, 0x4000106188}, 0x40000a66c0, 0x40000a4c10)
goroutine 83 [running]:

[signal SIGSEGV: segmentation violation code=0x1 addr=0xb8 pc=0x3c0c68]
panic: runtime error: invalid memory address or nil pointer dereference
2021-08-20 00:21:53 level=info msg="Start initial compatible provider Proxy"
2021-08-20 00:21:52 守护程序：检测到 Clash 内核崩溃，重启中...

尝试删除内核，重启设备均无法解决。

**Comment by rvdodo** [comment]
尝试使用：Redir-Host（TUN）模式【依赖kmod-tun】  启动，Redir-Host（兼容）模式会崩。原因未知，坐等小伙伴解答。

**Comment by vernesong** [comment]
需要更新内核

**Comment by lyricusark** [comment]
更新内核v1.6.5-29-g410772e后解决，谢大佬。
