### ISSUE TITLE
Openclash启动脚本把防火墙的默认forward改为accept的作用是？

### ISSUE THREAD

**Issue by paladin4fan** [vernesong/OpenClash#1548]
发现Openclash每次启动都会把防火墙默认forward规则设置为Accept
想请问这个设置的作用是什么
因为此处设置accept 外网通过IPV6地址可以访问任意内网设备的任意端口

**Comment by vernesong** [comment]
tun模式需要转发

**Comment by paladin4fan** [comment]
那自己创建一条禁止所有wan转发到lan的规则是不是不会影响到tun模式的运行

**Comment by vernesong** [comment]
已修改相关设置，不再直接accept所有转发
