### ISSUE TITLE
请支持v2ray的tcp+tls模式

### ISSUE THREAD

**Issue by lifansama** [vernesong/OpenClash#155]
现在的配置方法只支持ws，ws+tls，tcp模式
请添加对tcp+tls的支持

**Comment by Love4Taylor** [comment]
你该去上游提。

**Comment by lifansama** [comment]
> 你该去上游提。

上游支持啊，

> 你该去上游提。

上游支持啊，作者参考的那个Luci For Clash也支持啊

**Comment by Love4Taylor** [comment]
看了下确实，不过目前这个设定有点傻 https://github.com/Dreamacro/clash/issues/301

**Comment by lifansama** [comment]
> 看了下确实，不过目前这个设定有点傻 [Dreamacro/clash#301](https://github.com/Dreamacro/clash/issues/301)

我用 `{ name: "v2ray", type: vmess, server: example.com, port: 443, uuid: UUID, alterId: 0, cipher: none, skip-cert-verify: true, tls: true }` 
是可以正常用tcp+tls的
