### ISSUE TITLE
关与TUN模式问题请教

### ISSUE THREAD

**Issue by CrazyMouse** [vernesong/OpenClash#1550]
翻阅了网上的资料，还是没能搞明白，openclash安装在openwrt上面，已经能用fake-ip 模式作为代理了，为啥还要去折腾TUN模式呢？我的理解现在默认fake-ip模式就已经能好好的FQ，也就意味着该拦截代理的流量都正常了，那启动TUN模式是为了啥？希望大神能给解释一下。TUN/TAP的原理我都去查了，也都理解了，就是不理解为啥会有Fake-IP和Fake-IP（TUN）模式这两个选项

**Comment by vernesong** [comment]
流量路径不同，tun的延迟更低，但性能要求高

**Comment by CrazyMouse** [comment]
> 流量路径不同，tun的延迟更低，但性能要求高

麻烦再请教一下，tun的延迟更低是因为启用tun后iptables 配置规则少，只需要将流量直接引入tun，然后tun直接对接clash来处理，从而降低了内核的分流压力么？
