### ISSUE TITLE
取General部分的转发端口设置, OpenClash 使用原始配置文件启动失败

### ISSUE THREAD

**Issue by okpkyes** [vernesong/OpenClash#1551]
现在出现这个，openclash无法启动~~~取General部分的转发端口设置, OpenClash 使用原始配置文件启动失败

**Comment by okpkyes** [comment]
<html>
<body>


错误: 无法获取General部分的转发端口设置, OpenClash 使用原始配置文件启动失败
--


<br class="Apple-interchange-newline">
</body>
</html>

**Comment by vernesong** [comment]
这个是尝试启动失败的结果，还有其他错误信息在前面你没给出

**Comment by RodmanWang** [comment]
![20210822212918](https://user-images.githubusercontent.com/19368219/130357021-5af1cd5e-07a8-499d-8f68-baed7ef45ec4.jpg)
确实还有错误啊，用全新设置也会显示

**Comment by RodmanWang** [comment]
![20210822215243](https://user-images.githubusercontent.com/19368219/130357665-73b36661-0bf3-4aa2-85cd-81e4e03c3671.jpg)
下午修复了之后可以启动了，但是确实有这个错误，即使使用意见生成配置也一样，日志会提示这个错误，但是主界面会显示已运行，但实际无法使用翻墙。
