### ISSUE TITLE
今天源码编译的无法启动

### ISSUE THREAD

**Issue by RodmanWang** [vernesong/OpenClash#1553]
点启动后无任何反应，也没有日志出来，测试全新安装不用任何配置，点启动也是没反应，也不会提示失败。

**Comment by zgc** [comment]
执行/etc/init.d/openclash start
提示/etc/rc.common: /etc/init.d/openclash: line 1765: syntax error: unexpected "}" (expecting "fi")

**Comment by RodmanWang** [comment]
感谢大佬更新。
