### ISSUE TITLE
这啥啊

### ISSUE THREAD

**Issue by capewang** [vernesong/OpenClash#1556]
![image](https://user-images.githubusercontent.com/61097665/130363131-13a54158-c202-4c63-87c4-5b3f84a75741.png)
  
好东西？？？

**Comment by lifetyper** [comment]
https://github.com/vernesong/OpenClash/issues/984

**Comment by VergilGao** [comment]
https://www.systemtek.co.uk/2018/03/what-is-gvt2-com/

**Comment by Karmylr** [comment]
哟，不是说不用了吗
