### ISSUE TITLE
有没有大佬有订阅转换网站可以让steam下载流量走直连，steam社区走代理呀？或者告诉我怎么改QAQ

### ISSUE THREAD

**Issue by Melvingabriel** [vernesong/OpenClash#1558]

**Comment by vernesong** [comment]
lhie1规则

**Comment by KHDKR** [comment]
因为没找到相关的解决办法，只能自己摸索，有可能是错误的，请指正
按照我自己近几天的折腾，大概总结了一下
steam下载这个东西属实是玄学，要是下图这种情况，就一句
DOMAIN-SUFFIX,steamcontent.com,DIRECT
![image](https://user-images.githubusercontent.com/49939076/131254820-05a718a4-2f80-4f1f-b9f5-de4f4d4a8c2f.png)

但是要是下面这种情况，那就没办法了，只能让他自己分配，然后就大概率走漏网之鱼了
![image](https://user-images.githubusercontent.com/49939076/131253650-1e12a7db-f19d-4814-9187-eb4252f74359.png)

如果硬是要写一个规则，也可以，就按照我这里举例就是
IP-CIDR,153.254.86/22,DIRECT
不过写了这个规则就会出现新的问题，你看之前的图里下载是多线程的，但是写了这个规则之后就只能单线程了
![image](https://user-images.githubusercontent.com/49939076/131253096-c1d0e2c9-4bd7-422e-84fd-973c1c8049a3.png)

下载速度惊人
![image](https://user-images.githubusercontent.com/49939076/131253157-ec6474e5-4bf2-4b4b-b7ee-c95be48b2c9d.png)

**Comment by Melvingabriel** [comment]
> 因为没找到相关的解决办法，只能自己摸索，有可能是错误的，请指正
> 按照我自己近几天的折腾，大概总结了一下
> steam下载这个东西属实是玄学，要是下图这种情况，就一句
> DOMAIN-SUFFIX,steamcontent.com,DIRECT
> ![image](https://user-images.githubusercontent.com/49939076/131254820-05a718a4-2f80-4f1f-b9f5-de4f4d4a8c2f.png)
> 
> 但是要是下面这种情况，那就没办法了，只能让他自己分配，然后就大概率走漏网之鱼了
> ![image](https://user-images.githubusercontent.com/49939076/131253650-1e12a7db-f19d-4814-9187-eb4252f74359.png)
> 
> 如果硬是要写一个规则，也可以，就按照我这里举例就是
> IP-CIDR,153.254.86.0/22,DIRECT
> 不过写了这个规则就会出现新的问题，你看之前的图里下载是多线程的，但是写了这个规则之后就只能单线程了
> ![image](https://user-images.githubusercontent.com/49939076/131253096-c1d0e2c9-4bd7-422e-84fd-973c1c8049a3.png)
> 
> 下载速度惊人
> ![image](https://user-images.githubusercontent.com/49939076/131253157-ec6474e5-4bf2-4b4b-b7ee-c95be48b2c9d.png)

感谢分享：D
我现在是把
- DOMAIN-SUFFIX,ea.com, 全球直连
- DOMAIN-SUFFIX,tnt-ea.com, 全球直连
- DOMAIN-SUFFIX,xbox-live.com, 全球直连
- DOMAIN-SUFFIX,steampowered.com, 全球直连
- DOMAIN-SUFFIX,xboxlive.com, 全球直连
- DOMAIN-SUFFIX,kaspersky-labs.com, 全球直连
- DOMAIN-SUFFIX,nvidia.com, 全球直连
- DOMAIN-SUFFIX,ubi.com, 全球直连
- DOMAIN-SUFFIX,gamedownloads-rockstargames-com.akamaized.net, 全球直连
这些全部加入智联，感觉能好一些

**Comment by paladin4fan** [comment]
说明你正在使用的规则有问题 把steamcontent.com分到代理去了

**Comment by AoEiuV020** [comment]
把steam的所有ip都走代理就可以了，
https://github.com/AoEiuV020/SubConfig/commit/c677b5f95e2ffbabce1c5be8b1a2eb66292dbdbd
可以试试我的配置文件，
https://github.com/AoEiuV020/SubConfig/raw/c677b5f95e2ffbabce1c5be8b1a2eb66292dbdbd/subconverter.ini

**Comment by jyfcccac** [comment]
有没有人能利用nodejs来把我的单线程验号工具改成多线程得+q1817936614 800元找人做

**Comment by zhbsmdd** [comment]
> 把steam的所有ip都走直连就可以了，而且加上no-resolve不影响社区之类有域名的情况的分流， [AoEiuV020/SubConfig@c677b5f](https://github.com/AoEiuV020/SubConfig/commit/c677b5f95e2ffbabce1c5be8b1a2eb66292dbdbd) 可以试试我的配置文件， https://github.com/AoEiuV020/SubConfig/raw/c677b5f95e2ffbabce1c5be8b1a2eb66292dbdbd/subconverter.ini

**Comment by zhbsmdd** [comment]
> 把steam的所有ip都走直连就可以了，而且加上no-resolve不影响社区之类有域名的情况的分流， [AoEiuV020/SubConfig@c677b5f](https://github.com/AoEiuV020/SubConfig/commit/c677b5f95e2ffbabce1c5be8b1a2eb66292dbdbd) 可以试试我的配置文件， https://github.com/AoEiuV020/SubConfig/raw/c677b5f95e2ffbabce1c5be8b1a2eb66292dbdbd/subconverter.ini

小白想问问这个配置文件怎么用（尴尬）

**Comment by AoEiuV020** [comment]
配合订阅转换使用，参考这两个项目，
tindy2013/subconverter
CareyWang/sub-web
不过我的配置也不太行了现在，虽然直连，但速度可能上不去，原因不明，我现在都是关闭代理下载steam游戏的，

zhbsmdd ***@***.***> 于2022年11月30日周三 10:32写道：

**Comment by IntangibleW** [comment]
把steamserver.net及子域名设置直连
