### ISSUE TITLE
fake-ip switch没法联网问题

### ISSUE THREAD

**Issue by new1943** [vernesong/OpenClash#1559]
开启openclash，使用fake-ip混合模式，在switch中马车8的游戏没法联网，网络测试NAT类型为B，关了openclash后，网络测试NAT类型为A。

另外，群晖的也是，openwrt里装了miniupnpd，开了openclash后upnp联机测试没法联通，关了以后就正常了。

**Comment by vernesong** [comment]
用tun

**Comment by new1943** [comment]
> 用tun

我把所有设置还原成默认，选了fake-ip tun模式，问题依旧😂

**Comment by new1943** [comment]
> redir呢

刚把redir的四种模式都试了下，upnp和switch还是一样。😮‍💨我看之前的帖子里有说什么禁止dns缓存就可以。但我找了半天没找到。
