### ISSUE TITLE
如何避免节点域名被代理？

### ISSUE THREAD

**Issue by zgc** [vernesong/OpenClash#1560]
OpenClash是最新源码编译
使用规则模板的是神机规则
节点类型是vmess
启用了 仅代理命中规则流量 绕过中国大陆IP 和 仅允许常用端口流量

今天入手了一个节点，使用过程中发现流量一直双倍的扣，检查Dashboard面板的连接，发现节点的域名被代理，原因是我在手机开着surge，surge里面也使用了同样的节点，surge的流量被openclash代理了，我经常忘记关surge，怎样设置可以避免节点被代理？

**Comment by vernesong** [comment]
这个没办法，建议让surge连接wifi时自动关闭代理

**Comment by zgc** [comment]
添加了自定义规则之后就没再扣双倍流量了
- DOMAIN-SUFFIX,节点域名A,DIRECT
- DOMAIN-SUFFIX,节点域名B,DIRECT

**Comment by zgc** [comment]
> 这个没办法，建议让surge连接wifi时自动关闭代理

节点多了还挺麻烦的，希望大佬能加一下这个功能“代理节点直连”
