### ISSUE TITLE
Koolshare lede redir-host模式下udp流量无法转发的问题

### ISSUE THREAD

**Issue by A-Cepheus** [vernesong/OpenClash#1562]
开启openclash后warning级日志提示："Failed to start Redir UDP Listener: operation not permitted"
相应的redir端口也没有监听udp流量
后来不断试验发现tun内核使用redir模式及配置可以接收tproxy转发

**Comment by A-Cepheus** [comment]
看到了说koolshare不支持capsh，但是不明白为什么tun内核又可以使用

**Comment by A-Cepheus** [comment]
另外重做lede系统以后再安装 openclash的luci界面变成部分英文了 后来发现语言设置的是auto，但是设置为中文以后重装插件也还是部分英文

**Comment by vernesong** [comment]
koolshare的固件不会主动去兼容和修复bug，浪费时间
