### ISSUE TITLE
安装OpenClash后OpenWrt web网关无法正常加载

### ISSUE THREAD

**Issue by TerryFosky** [vernesong/OpenClash#1567]
安装完OpenClash后刷新页面发现OpenWrt控制面板无法加载了
版本为v0.43.01-beta
![image](https://user-images.githubusercontent.com/40736902/130660230-b8580460-6260-4c15-92f1-4ff89e39ae46.png)

**Comment by vernesong** [comment]
日志

**Comment by TerryFosky** [comment]
不好意思 一开始在Openwrt面板上传安装的出现了上面的情况 刚才手动安装成功了
