### ISSUE TITLE
切换配置文件后策略组配置不会更新

### ISSUE THREAD

**Issue by MeowRay** [vernesong/OpenClash#1569]
RT，切换配置文件后，策略组设置页面依然显示先前配置文件的
![image](https://user-images.githubusercontent.com/29674595/130799253-f1e3f9a1-04dd-4087-979a-bebbb637f710.png)
切换为df
![image](https://user-images.githubusercontent.com/29674595/130799292-34b2202f-2713-4dec-8350-3c639c8341a7.png)
实际的策略组
![image](https://user-images.githubusercontent.com/29674595/130799336-711ec4b5-95bf-4eb3-825b-08ffc9936e2f.png)

**Comment by vernesong** [comment]
这页的设置不会自动读取，需要手动读取

**Comment by MeowRay** [comment]
> 这页的设置不是自动读取来的，需要手动读取

在哪里手动读取

**Comment by MeowRay** [comment]
> 这页的设置不是自动读取来的，需要手动读取

那如何在保留每日订阅的策略组和服务器情况下而外添加自定义服务器节点呢？我添加后订阅一更新就没了
