### ISSUE TITLE
不走规则

### ISSUE THREAD

**Issue by hywang1230** [vernesong/OpenClash#157]
![image](https://user-images.githubusercontent.com/1239687/74958959-bf2b0b80-5444-11ea-9e1d-93fa143d5722.png)
设置了Fake-IP模式，访问百度、谷歌等都是显示IP、类型Redir，造成不能命中规则，这个是哪配置不对么

**Comment by vernesong** [comment]
开dns劫持，不要使用其他dns插件

**Comment by hywang1230** [comment]
设置了dns劫持，检查了没有其他dns插件，还是不行。路由器是旁路由，电脑的网关设置的是路由器的地址，电脑不设置代理，这种情况总是显示IP；如果电脑手动设置clash的代理，就能正常显示规则

**Comment by vernesong** [comment]
https://github.com/vernesong/OpenClash/wiki/%E7%BD%91%E7%BB%9C%E8%BF%9E%E6%8E%A5%E5%BC%82%E5%B8%B8%E6%97%B6%E6%8E%92%E6%9F%A5%E5%8E%9F%E5%9B%A0#%E4%B8%80dns%E8%AE%BE%E7%BD%AE%E9%94%99%E8%AF%AF

**Comment by hywang1230** [comment]
![image](https://user-images.githubusercontent.com/1239687/75044065-f5779200-54fb-11ea-87e6-37cb703bb39e.png)
大佬，这样是正常的么？

**Comment by vernesong** [comment]
vpn关了试下

**Comment by hywang1230** [comment]
![image](https://user-images.githubusercontent.com/1239687/75049171-b437b000-5504-11ea-92df-49ab7fec190d.png)
![image](https://user-images.githubusercontent.com/1239687/75049238-d3ced880-5504-11ea-9bd4-c56c97348719.png)
这样也是不行，😭

**Comment by vernesong** [comment]
这样就没问题了，你开百度日志里下显示什么？

**Comment by hywang1230** [comment]
![image](https://user-images.githubusercontent.com/1239687/75085220-e7f4f300-5561-11ea-8926-f0eaf0230641.png)
![image](https://user-images.githubusercontent.com/1239687/75085222-edead400-5561-11ea-967f-1f80a594ed22.png)
路由器：N1做旁路由，主路由WNDR4300，以接入点的模式接在光猫下面，和光猫一个IP段
网关：N1的地址，N1做DHCP
设备：MAC，本机无代理

![image](https://user-images.githubusercontent.com/1239687/75085281-8c773500-5562-11ea-9824-2aa93bc5d4fe.png)
设备：iPhone，本机有qx代理，使用的是ssid，连接Wi-Fi下代理模式是direct

![image](https://user-images.githubusercontent.com/1239687/75085296-ccd6b300-5562-11ea-8c17-541bd31012dc.png)
设备：iPhone，本机无代理

**Comment by vernesong** [comment]
检查设备下发的dns地址，要用n1的，你这种情况产生的原因就是dns没在N1上解析，在其他地方解析完了才传给clash
