### ISSUE TITLE
ipv6扶墙下，fakeip和redir模式的两难问题

### ISSUE THREAD

**Issue by tikkacn** [vernesong/OpenClash#1577]
本地用ipv6科学上网有特殊加成，基本可以跑满带宽，所以一般都用ipv6节点
本来正常使用fakeip模式，但是最近入手一个网心云，发现在这个模式下网心云收益超低，基本上传被限制在几百kb/s
换用redir模式网心云上传速度正常了，但是netflix又无法打开了，显示Not Available
已经给netflix设置了域名规则还是无效

大佬可有解决方案？小弟拜谢

**Comment by VergilGao** [comment]
我就是ipv6模式，用redir可以正常使用。
fakeip模式主要问题是我做一些nslookup之类的操作会返回奇怪的结果，我不是很喜欢，dns我用的smartdns来解决，没啥毛病。

**Comment by JamesLiu0802** [comment]
我是主路由负责拨号，旁路由的ipv6设置好以后，只能修改电脑的ipv6地址，但是安卓手机因为默认局域网网关设置，所以会出问题，最后使用dnschanger修改dns后，问题基本解决。

**Comment by tikkacn** [comment]
更新到9.5日发布的新版本后，貌似netflix正常了
继续观察中
