### ISSUE TITLE
MT7621频繁崩溃

### ISSUE THREAD

**Issue by jackadam1981** [vernesong/OpenClash#1579]
2021-08-28 16:19:07 第六步：删除 OpenClash 残留文件...
2021-08-28 16:19:02 第五步: 重启 Dnsmasq 程序...
2021-08-28 16:19:02 第四步: 关闭 Clash 主程序...
2021-08-28 16:19:02 第三步: 关闭 OpenClash 守护程序...
2021-08-28 16:19:00 第二步: 删除 OpenClash 防火墙规则...
2021-08-28 16:19:00 第一步: 备份当前策略组状态...
2021-08-28 16:19:00 OpenClash 开始关闭...
2021-08-28 16:19:00 守护程序：已尝试自动重启三次 Clash 内核，为防止频繁重启造成严重后果，OpenClash 将停止运行...
2021-08-29 00:17:57 level=info msg="Start initial compatible provider 🌍 国外媒体"
2021-08-29 00:17:57 level=info msg="Start initial compatible provider 📲 电报信息"
2021-08-29 00:17:57 level=info msg="Start initial compatible provider 🐟 漏网之鱼"
2021-08-29 00:17:57 level=info msg="Start initial compatible provider 🌏 国内媒体"
2021-08-29 00:17:57 level=info msg="Start initial compatible provider 🔰 节点选择"
2021-08-29 00:17:57 level=info msg="Start initial compatible provider 🎯 全球直连"
2021-08-29 00:17:57 level=info msg="Start initial compatible provider 🍎 苹果服务"
2021-08-29 00:17:57 level=info msg="Start initial compatible provider Ⓜ️ 微软服务"
2021-08-29 00:17:57 level=info msg="Start initial compatible provider 🛑 全球拦截"
2021-08-29 00:17:57 level=info msg="Start initial compatible provider ♻️ 自动选择"
2021-08-28 16:17:55 守护程序：检测到 Clash 内核崩溃，重启中...
2021-08-29 00:16:53 level=info msg="Start initial compatible provider 🛑 全球拦截"
2021-08-29 00:16:53 level=info msg="Start initial compatible provider 🔰 节点选择"
2021-08-29 00:16:53 level=info msg="Start initial compatible provider 🎯 全球直连"
2021-08-29 00:16:53 level=info msg="Start initial compatible provider Ⓜ️ 微软服务"
2021-08-29 00:16:53 level=info msg="Start initial compatible provider 🌏 国内媒体"
2021-08-29 00:16:53 level=info msg="Start initial compatible provider 🍎 苹果服务"
2021-08-29 00:16:53 level=info msg="Start initial compatible provider ♻️ 自动选择"
2021-08-29 00:16:53 level=info msg="Start initial compatible provider 🐟 漏网之鱼"
2021-08-29 00:16:53 level=info msg="Start initial compatible provider 📲 电报信息"
2021-08-29 00:16:53 level=info msg="Start initial compatible provider 🌍 国外媒体"
2021-08-28 16:16:48 守护程序：检测到 Clash 内核崩溃，重启中...
2021-08-29 00:15:34 level=info msg="Start initial compatible provider Ⓜ️ 微软服务"
2021-08-29 00:15:34 level=info msg="Start initial compatible provider 🌍 国外媒体"
2021-08-29 00:15:34 level=info msg="Start initial compatible provider ♻️ 自动选择"
2021-08-29 00:15:34 level=info msg="Start initial compatible provider 📲 电报信息"
2021-08-29 00:15:34 level=info msg="Start initial compatible provider 🐟 漏网之鱼"
2021-08-29 00:15:34 level=info msg="Start initial compatible provider 🔰 节点选择"
2021-08-29 00:15:34 level=info msg="Start initial compatible provider 🎯 全球直连"
2021-08-29 00:15:34 level=info msg="Start initial compatible provider 🛑 全球拦截"
2021-08-29 00:15:34 level=info msg="Start initial compatible provider 🌏 国内媒体"
2021-08-29 00:15:34 level=info msg="Start initial compatible provider 🍎 苹果服务"
2021-08-28 16:15:32 守护程序：检测到 Clash 内核崩溃，重启中...
2021-08-29 00:12:22 level=info msg="Start initial compatible provider 🔰 节点选择"
2021-08-29 00:12:22 level=info msg="Start initial compatible provider ♻️ 自动选择"
2021-08-29 00:12:22 level=info msg="Start initial compatible provider 📲 电报信息"
2021-08-29 00:12:22 level=info msg="Start initial compatible provider 🐟 漏网之鱼"
2021-08-29 00:12:22 level=info msg="Start initial compatible provider Ⓜ️ 微软服务"
2021-08-29 00:12:22 level=info msg="Start initial compatible provider 🍎 苹果服务"
2021-08-29 00:12:22 level=info msg="Start initial compatible provider 🌏 国内媒体"
2021-08-29 00:12:22 level=info msg="Start initial compatible provider 🌍 国外媒体"
2021-08-29 00:12:22 level=info msg="Start initial compatible provider 🎯 全球直连"
2021-08-29 00:12:22 level=info msg="Start initial compatible provider 🛑 全球拦截"
2021-08-28 16:12:19 守护程序：检测到 Clash 内核崩溃，重启中...
2021-08-29 00:09:07 level=info msg="RESTful API listening at: [::]:9090"
2021-08-29 00:09:07 level=info msg="Start initial compatible provider 🎯 全球直连"
2021-08-29 00:09:07 level=info msg="Start initial compatible provider Ⓜ️ 微软服务"
2021-08-29 00:09:07 level=info msg="Start initial compatible provider 📲 电报信息"
2021-08-29 00:09:07 level=info msg="Start initial compatible provider 🌏 国内媒体"
2021-08-29 00:09:07 level=info msg="Start initial compatible provider 🔰 节点选择"
2021-08-29 00:09:07 level=info msg="Start initial compatible provider ♻️ 自动选择"
2021-08-29 00:09:07 level=info msg="Start initial compatible provider 🐟 漏网之鱼"
2021-08-29 00:09:07 level=info msg="Start initial compatible provider 🌍 国外媒体"
2021-08-29 00:09:07 level=info msg="Start initial compatible provider 🛑 全球拦截"
2021-08-29 00:09:07 level=info msg="Start initial compatible provider 🍎 苹果服务"
2021-08-28 16:09:03 守护程序：检测到 Clash 内核崩溃，重启中...
2021-08-28 16:06:41 OpenClash 启动成功，请等待服务器上线！
2021-08-28 16:06:41 第十步: 添加计划任务,启动进程守护程序...
2021-08-28 16:06:36 第九步: 重启 Dnsmasq 程序...
2021-08-28 16:06:35 第八步: 设置防火墙规则...
2021-08-28 16:06:35 第七步: 设置控制面板...
2021-08-28 16:06:27 第六步: 等待主程序下载外部文件...
2021-08-29 00:06:26 level=info msg="Start initial compatible provider 🌍 国外媒体"
2021-08-29 00:06:26 level=info msg="Start initial compatible provider 🐟 漏网之鱼"
2021-08-29 00:06:26 level=info msg="Start initial compatible provider 🍎 苹果服务"
2021-08-29 00:06:26 level=info msg="Start initial compatible provider 🛑 全球拦截"
2021-08-29 00:06:26 level=info msg="Start initial compatible provider 🔰 节点选择"
2021-08-29 00:06:26 level=info msg="Start initial compatible provider 📲 电报信息"
2021-08-29 00:06:26 level=info msg="Start initial compatible provider 🌏 国内媒体"
2021-08-29 00:06:26 level=info msg="Start initial compatible provider Ⓜ️ 微软服务"
2021-08-29 00:06:26 level=info msg="Start initial compatible provider ♻️ 自动选择"
2021-08-29 00:06:26 level=info msg="Start initial compatible provider 🎯 全球直连"
2021-08-28 16:06:24 第五步: 检查内核启动状态...
2021-08-28 16:06:20 未检测到特殊配置，调用 Dev 内核启动...
2021-08-28 16:06:20 第四步: 启动主程序...
2021-08-28 16:05:39 第三步: 修改配置文件...
2021-08-28 16:05:35 第二步: 组件运行前检查...
2021-08-28 16:05:35 第一步: 获取配置...
2021-08-28 16:05:35 OpenClash 开始启动...

型号 | Xiaomi Redmi Router AC2100
架构 | MediaTek MT7621 ver:1 eco:3
固件版本 | OpenWrt 21.02.0-rc4 r16256-2d5ee43dc6 / LuCI openwrt-21.02 branch git-21.231.26241-422c175
内核版本 | 5.4.137

是CPU不够强悍么？

**Comment by vernesong** [comment]
没有报错基本都是系统原因，系统日志会有提示，建议重刷固件

**Comment by jackadam1981** [comment]
我再试试看。

**Comment by etc-snail** [comment]
df -h查看 多半是根目录 /下空间不足，最好有2M剩余空间。

**Comment by jackadam1981** [comment]
root@OpenWrt:~# df -h
Filesystem                Size      Used Available Use% Mounted on
/dev/root                 3.8M      3.8M         0 100% /rom
tmpfs                    59.7M    264.0K     59.4M   0% /tmp
/dev/ubi0_1              97.3M     48.0K     92.6M   0% /overlay
overlayfs:/overlay       97.3M     48.0K     92.6M   0% /
tmpfs                   512.0K         0    512.0K   0% /dev

REDMI AC2100   128M+128M

**Comment by jackadam1981** [comment]
安装完以后
root@OpenWrt:~# df -h
Filesystem                Size      Used Available Use% Mounted on
/dev/root                 3.8M      3.8M         0 100% /rom
tmpfs                    59.7M      1.3M     58.4M   2% /tmp
/dev/ubi0_1              97.3M     15.0M     77.6M  16% /overlay
overlayfs:/overlay       97.3M     15.0M     77.6M  16% /
tmpfs                   512.0K         0    512.0K   0% /dev

**Comment by jackadam1981** [comment]
[ 3280.752624] clash invoked oom-killer: gfp_mask=0x400dc0(GFP_KERNEL_ACCOUNT|__GFP_ZERO), order=1, oom_score_adj=0
[ 3280.763012] CPU: 3 PID: 28844 Comm: clash Not tainted 5.4.137 #0
[ 3280.769026] Stack : 00000000 80850000 00400dc0 8007dec4 00000000 00000000 00000000 00000000
[ 3280.777404]         00000000 00000000 00000000 00000000 00000000 00000001 86563bf8 412818de
[ 3280.785804]         86563c90 00000000 00000000 00000000 00000038 805eaf64 342e3520 3733312e
[ 3280.794269]         00000000 000000a3 00000000 000ba484 80000000 86563bd8 00000000 806e29a8
[ 3280.802638]         00000086 806c0000 00000240 00000001 00000003 8035c19c 0000000c 8082000c
[ 3280.810987]         ...
[ 3280.813445] Call Trace:
[ 3280.813461] [<8007dec4>] 0x8007dec4
[ 3280.819417] [<805eaf64>] 0x805eaf64
[ 3280.822943] [<8035c19c>] 0x8035c19c
[ 3280.826449] [<8000b05c>] 0x8000b05c
[ 3280.829937] [<8000b064>] 0x8000b064
[ 3280.833416] [<805d08a4>] 0x805d08a4
[ 3280.836903] [<8007a96c>] 0x8007a96c
[ 3280.840440] [<8010d9dc>] 0x8010d9dc
[ 3280.843952] [<8010e3dc>] 0x8010e3dc
[ 3280.847432] [<80132e10>] 0x80132e10
[ 3280.850923] [<80152bb0>] 0x80152bb0
[ 3280.854449] [<8010ea40>] 0x8010ea40
[ 3280.857936] [<801538a8>] 0x801538a8
[ 3280.861416] [<8005f824>] 0x8005f824
[ 3280.864960] [<800298ac>] 0x800298ac
[ 3280.868469] [<80023a70>] 0x80023a70
[ 3280.871977] [<8013d588>] 0x8013d588
[ 3280.875486] [<8002ad98>] 0x8002ad98
[ 3280.878991] [<8003a2e4>] 0x8003a2e4
[ 3280.882474] [<8002b124>] 0x8002b124
[ 3280.885959] [<8003a4cc>] 0x8003a4cc
[ 3280.889439] [<80014558>] 0x80014558
[ 3280.892928] 
[ 3280.897251] Mem-Info:
[ 3280.899674] active_anon:15877 inactive_anon:17 isolated_anon:0
[ 3280.899674]  active_file:124 inactive_file:262 isolated_file:0
[ 3280.899674]  unevictable:0 dirty:0 writeback:0 unstable:0
[ 3280.899674]  slab_reclaimable:788 slab_unreclaimable:4118
[ 3280.899674]  mapped:43 shmem:331 pagetables:147 bounce:0
[ 3280.899674]  free:4621 free_pcp:63 free_cma:0
[ 3280.935170] Node 0 active_anon:63508kB inactive_anon:68kB active_file:552kB inactive_file:1160kB unevictable:0kB isolated(anon):0kB isolated(file):0kB mapped:256kB dirty:0kB writeback:0kB shmem:1324kB writeback_tmp:0kB unstable:0kB all_unreclaimable? yes
[ 3280.957926] Normal free:18512kB min:16384kB low:20480kB high:24576kB active_anon:63508kB inactive_anon:68kB active_file:320kB inactive_file:808kB unevictable:0kB writepending:0kB present:131072kB managed:122236kB mlocked:0kB kernel_stack:1528kB pagetables:588kB bounce:0kB free_pcp:256kB local_pcp:152kB free_cma:0kB
[ 3280.985803] lowmem_reserve[]: 0 0 0
[ 3280.989306] Normal: 383*4kB (UMEH) 150*8kB (UMEH) 71*16kB (UMEH) 30*32kB (UMEH) 23*64kB (UMH) 6*128kB (UMEH) 4*256kB (U) 2*512kB (UE) 1*1024kB (U) 2*2048kB (UE) 1*4096kB (M) = 18332kB
[ 3281.005677] 806 total pagecache pages
[ 3281.009328] 0 pages in swap cache
[ 3281.012659] Swap cache stats: add 0, delete 0, find 0/0
[ 3281.017937] Free swap  = 0kB
[ 3281.022073] Total swap = 0kB
[ 3281.025041] 32768 pages RAM
[ 3281.027894] 0 pages HighMem/MovableOnly
[ 3281.031735] 2209 pages reserved
[ 3281.034881] Tasks state (memory values in pages):
[ 3281.039631] [  pid  ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
[ 3281.048280] [    680]    81   680      326       25    20480        0             0 ubusd
[ 3281.056462] [    681]     0   681      235        7    16384        0             0 askfirst
[ 3281.064954] [    715]     0   715      261        8    12288        0             0 urngd
[ 3281.073197] [   1050]     0  1050      865       82    16384        0             0 uhttpd
[ 3281.081525] [   1307]   514  1307      316        8    20480        0             0 logd
[ 3281.089629] [   1359]     0  1359      542       52    20480        0             0 rpcd
[ 3281.097761] [   1562]     0  1562      287        8    12288        0             0 dropbear
[ 3281.106266] [   1660]     0  1660      912       45    20480        0             0 hostapd
[ 3281.114705] [   1661]     0  1661      888       26    24576        0             0 wpa_supplicant
[ 3281.124928] [   1721]     0  1721      447       36    20480        0             0 netifd
[ 3281.133360] [   1777]     0  1777      370       30    16384        0             0 odhcpd
[ 3281.141709] [   2378]     0  2378      314        9    12288        0             0 ntpd
[ 3281.149877] [  10896]     0 10896      324       31    16384        0             0 pppd
[ 3281.158042] [  11046]     0 11046      267        8    12288        0             0 odhcp6c
[ 3281.166440] [  12814]     0 12814      302       11    16384        0             0 dropbear
[ 3281.174882] [  12815]     0 12815      315        6    20480        0             0 ash
[ 3281.182885] [  12825]     0 12825      302       24    16384        0             0 dropbear
[ 3281.191329] [  12826]     0 12826      316       14    16384        0             0 ash
[ 3281.199397] [  26685]     0 26685      314       10    16384        0             0 crond
[ 3281.207636] [  28780] 65534 28780   169018    13399    81920        0             0 clash
[ 3281.215841] [  29621]   453 29621      725       34    24576        0             0 dnsmasq
[ 3281.225262] [  29664]     0 29664      318       15    16384        0             0 sh
[ 3281.233293] [  12563]     0 12563      313        7    16384        0             0 sleep
[ 3281.241564] [  12686]     0 12686      935      355    16384        0             0 luci
[ 3281.249810] [  12705]     0 12705      902      307    16384        0             0 luci
[ 3281.258082] [  12707]     0 12707      902      339    20480        0             0 luci
[ 3281.266328] [  12770]     0 12770      264      122    16384        0             0 modprobe
[ 3281.274827] [  12776]     0 12776      313        7    12288        0             0 sh
[ 3281.282817] [  12778]     0 12778      313        7    12288        0             0 grep
[ 3281.291006] [  12780]     0 12780      314        7    20480        0             0 awk
[ 3281.299058] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/,task=clash,pid=28780,uid=65534
[ 3281.312165] Out of memory: Killed process 28780 (clash) total-vm:676072kB, anon-rss:53596kB, file-rss:0kB, shmem-rss:0kB, UID:65534 pgtables:80kB oom_score_adj:0
[ 3281.382622] oom_reaper: reaped process 28780 (clash), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
[ 3783.103373] clash invoked oom-killer: gfp_mask=0x400dc0(GFP_KERNEL_ACCOUNT|__GFP_ZERO), order=1, oom_score_adj=0
[ 3783.113695] CPU: 3 PID: 12969 Comm: clash Not tainted 5.4.137 #0
[ 3783.119715] Stack : 00000000 80850000 00400dc0 8007dec4 00000000 00000000 00000000 00000000
[ 3783.128094]         00000000 00000000 00000000 00000000 00000000 00000001 85071bf8 412818de
[ 3783.136462]         85071c90 00000000 00000000 00000000 00000038 805eaf64 342e3520 3733312e
[ 3783.144843]         00000000 000000bc 00000000 0001bc1f 80000000 85071bd8 00000000 806e29a8
[ 3783.153209]         00000181 806c0000 00000240 00000001 00000003 8035c19c 0000000c 8082000c
[ 3783.161575]         ...
[ 3783.164050] Call Trace:
[ 3783.164080] [<8007dec4>] 0x8007dec4
[ 3783.170057] [<805eaf64>] 0x805eaf64
[ 3783.173591] [<8035c19c>] 0x8035c19c
[ 3783.177113] [<8000b05c>] 0x8000b05c
[ 3783.180629] [<8000b064>] 0x8000b064
[ 3783.184143] [<805d08a4>] 0x805d08a4
[ 3783.187668] [<8007a96c>] 0x8007a96c
[ 3783.191197] [<8010d9dc>] 0x8010d9dc
[ 3783.194720] [<8010e3dc>] 0x8010e3dc
[ 3783.198237] [<80132e10>] 0x80132e10
[ 3783.201765] [<80152bb0>] 0x80152bb0
[ 3783.205296] [<8010ea40>] 0x8010ea40
[ 3783.208824] [<801538a8>] 0x801538a8
[ 3783.212353] [<8005f824>] 0x8005f824
[ 3783.215935] [<800298ac>] 0x800298ac
[ 3783.219450] [<80023a70>] 0x80023a70
[ 3783.222956] [<8013d588>] 0x8013d588
[ 3783.226463] [<8002ad98>] 0x8002ad98
[ 3783.229984] [<8003a2e4>] 0x8003a2e4
[ 3783.233503] [<8002b124>] 0x8002b124
[ 3783.237022] [<8003a4cc>] 0x8003a4cc
[ 3783.240540] [<80014558>] 0x80014558
[ 3783.244038] 
[ 3783.247526] Mem-Info:
[ 3783.249887] active_anon:14006 inactive_anon:17 isolated_anon:0
[ 3783.249887]  active_file:162 inactive_file:207 isolated_file:0
[ 3783.249887]  unevictable:0 dirty:0 writeback:0 unstable:0
[ 3783.249887]  slab_reclaimable:699 slab_unreclaimable:4284
[ 3783.249887]  mapped:40 shmem:332 pagetables:123 bounce:0
[ 3783.249887]  free:4363 free_pcp:144 free_cma:0
[ 3783.284461] Node 0 active_anon:56024kB inactive_anon:68kB active_file:648kB inactive_file:828kB unevictable:0kB isolated(anon):0kB isolated(file):0kB mapped:160kB dirty:0kB writeback:0kB shmem:1328kB writeback_tmp:0kB unstable:0kB all_unreclaimable? yes
[ 3783.306954] Normal free:16644kB min:16384kB low:20480kB high:24576kB active_anon:55856kB inactive_anon:68kB active_file:704kB inactive_file:916kB unevictable:0kB writepending:0kB present:131072kB managed:122236kB mlocked:0kB kernel_stack:1840kB pagetables:492kB bounce:0kB free_pcp:552kB local_pcp:156kB free_cma:0kB
[ 3783.334796] lowmem_reserve[]: 0 0 0
[ 3783.338431] Normal: 136*4kB (UMH) 221*8kB (UMH) 87*16kB (UMH) 35*32kB (MH) 32*64kB (UMH) 40*128kB (MH) 7*256kB (M) 1*512kB (U) 0*1024kB 1*2048kB (U) 0*4096kB = 16344kB
[ 3783.353505] 737 total pagecache pages
[ 3783.357217] 0 pages in swap cache
[ 3783.360575] Swap cache stats: add 0, delete 0, find 0/0
[ 3783.365867] Free swap  = 0kB
[ 3783.368800] Total swap = 0kB
[ 3783.371748] 32768 pages RAM
[ 3783.374559] 0 pages HighMem/MovableOnly
[ 3783.378415] 2209 pages reserved
[ 3783.382893] Tasks state (memory values in pages):
[ 3783.387728] [  pid  ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
[ 3783.396441] [    680]    81   680      326       25    20480        0             0 ubusd
[ 3783.404650] [    681]     0   681      235        7    16384        0             0 askfirst
[ 3783.413119] [    715]     0   715      261        8    12288        0             0 urngd
[ 3783.421319] [   1050]     0  1050      865       82    16384        0             0 uhttpd
[ 3783.429610] [   1307]   514  1307      316       31    20480        0             0 logd
[ 3783.437708] [   1359]     0  1359      542       52    20480        0             0 rpcd
[ 3783.445807] [   1562]     0  1562      287        8    12288        0             0 dropbear
[ 3783.454268] [   1660]     0  1660      912       46    20480        0             0 hostapd
[ 3783.462690] [   1661]     0  1661      888       26    24576        0             0 wpa_supplicant
[ 3783.471679] [   1721]     0  1721      447       36    20480        0             0 netifd
[ 3783.479983] [   1777]     0  1777      370       30    16384        0             0 odhcpd
[ 3783.489302] [   2378]     0  2378      314        9    12288        0             0 ntpd
[ 3783.497503] [  10896]     0 10896      324       31    16384        0             0 pppd
[ 3783.505631] [  11046]     0 11046      267        8    12288        0             0 odhcp6c
[ 3783.513995] [  26685]     0 26685      314       11    16384        0             0 crond
[ 3783.522182] [  29621]   453 29621      734       43    24576        0             0 dnsmasq
[ 3783.530547] [  29664]     0 29664      320       17    16384        0             0 sh
[ 3783.538494] [  12929] 65534 12929   168954    11542   118784        0             0 clash
[ 3783.546714] [  18204]     0 18204      313        7    12288        0             0 sleep
[ 3783.554895] [  18488]     0 18488      775      196    20480        0             0 luci
[ 3783.562992] [  18539]     0 18539      819       25    20480        0             0 curl
[ 3783.571137] [  18597]     0 18597      262       12    12288        0             0 modprobe
[ 3783.579653] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/,task=clash,pid=12929,uid=65534
[ 3783.594467] Out of memory: Killed process 12929 (clash) total-vm:675816kB, anon-rss:46168kB, file-rss:0kB, shmem-rss:0kB, UID:65534 pgtables:116kB oom_score_adj:0
[ 3783.656201] oom_reaper: reaped process 12929 (clash), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
[ 3917.500663] clash invoked oom-killer: gfp_mask=0xcc0(GFP_KERNEL), order=0, oom_score_adj=0
[ 3917.509099] CPU: 1 PID: 19372 Comm: clash Not tainted 5.4.137 #0
[ 3917.515094] Stack : 00000000 80850000 00000cc0 8007dec4 00000000 00000000 00000000 00000000
[ 3917.523448]         00000000 00000000 00000000 00000000 00000000 00000001 8643baf0 412818de
[ 3917.531796]         8643bb88 00000000 00000000 00000000 00000038 805eaf64 342e3520 3733312e
[ 3917.540142]         00000000 000000c2 00000000 0007c4ab 80000000 8643bad0 00000000 806e29a8
[ 3917.548488]         00000349 806c0000 00000240 00000000 00000003 8035c19c 00000004 80820004
[ 3917.556841]         ...
[ 3917.559293] Call Trace:
[ 3917.559314] [<8007dec4>] 0x8007dec4
[ 3917.565277] [<805eaf64>] 0x805eaf64
[ 3917.568769] [<8035c19c>] 0x8035c19c
[ 3917.572264] [<8000b05c>] 0x8000b05c
[ 3917.575746] [<8000b064>] 0x8000b064
[ 3917.579225] [<805d08a4>] 0x805d08a4
[ 3917.582705] [<8007a96c>] 0x8007a96c
[ 3917.586210] [<8010d9dc>] 0x8010d9dc
[ 3917.589713] [<8010e3dc>] 0x8010e3dc
[ 3917.593195] [<8010e9f0>] 0x8010e9f0
[ 3917.596752] [<8010ea40>] 0x8010ea40
[ 3917.600259] [<801538a8>] 0x801538a8
[ 3917.603777] [<80412d68>] 0x80412d68
[ 3917.607268] [<8041346c>] 0x8041346c
[ 3917.610761] [<804c54f4>] 0x804c54f4
[ 3917.614270] [<804c5ea0>] 0x804c5ea0
[ 3917.617751] [<80037384>] 0x80037384
[ 3917.621236] [<8040f0a4>] 0x8040f0a4
[ 3917.624716] [<80037920>] 0x80037920
[ 3917.628211] [<801770fc>] 0x801770fc
[ 3917.631690] [<80061c80>] 0x80061c80
[ 3917.635192] [<8017992c>] 0x8017992c
[ 3917.638668] [<805ec370>] 0x805ec370
[ 3917.642149] [<8019e240>] 0x8019e240
[ 3917.645635] [<80179bec>] 0x80179bec
[ 3917.649114] [<80014558>] 0x80014558
[ 3917.652598] 
[ 3917.654907] Mem-Info:
[ 3917.657308] active_anon:14364 inactive_anon:13 isolated_anon:0
[ 3917.657308]  active_file:366 inactive_file:445 isolated_file:29
[ 3917.657308]  unevictable:0 dirty:0 writeback:0 unstable:0
[ 3917.657308]  slab_reclaimable:721 slab_unreclaimable:4501
[ 3917.657308]  mapped:324 shmem:329 pagetables:125 bounce:0
[ 3917.657308]  free:4093 free_pcp:101 free_cma:0
[ 3917.689591] Node 0 active_anon:57456kB inactive_anon:52kB active_file:1464kB inactive_file:1780kB unevictable:0kB isolated(anon):0kB isolated(file):116kB mapped:1296kB dirty:0kB writeback:0kB shmem:1316kB writeback_tmp:0kB unstable:0kB all_unreclaimable? no
[ 3917.712401] Normal free:16372kB min:16384kB low:20480kB high:24576kB active_anon:57456kB inactive_anon:52kB active_file:1280kB inactive_file:2360kB unevictable:0kB writepending:0kB present:131072kB managed:122236kB mlocked:0kB kernel_stack:3208kB pagetables:500kB bounce:0kB free_pcp:400kB local_pcp:140kB free_cma:0kB
[ 3917.740433] lowmem_reserve[]: 0 0 0
[ 3917.744040] Normal: 190*4kB (UMEH) 137*8kB (UMEH) 55*16kB (UEH) 22*32kB (UMEH) 17*64kB (UME) 34*128kB (UMEH) 18*256kB (UM) 2*512kB (E) 2*1024kB (UE) 0*2048kB 0*4096kB = 16560kB
[ 3917.759955] 1177 total pagecache pages
[ 3917.763766] 0 pages in swap cache
[ 3917.767131] Swap cache stats: add 0, delete 0, find 0/0
[ 3917.772407] Free swap  = 0kB
[ 3917.775324] Total swap = 0kB
[ 3917.778249] 32768 pages RAM
[ 3917.781061] 0 pages HighMem/MovableOnly
[ 3917.784968] 2209 pages reserved
[ 3917.788157] Tasks state (memory values in pages):
[ 3917.792876] [  pid  ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
[ 3917.801545] [    680]    81   680      326       25    20480        0             0 ubusd
[ 3917.809751] [    681]     0   681      235        7    16384        0             0 askfirst
[ 3917.818240] [    715]     0   715      261        8    12288        0             0 urngd
[ 3917.826488] [   1050]     0  1050      865       82    16384        0             0 uhttpd
[ 3917.834816] [   1307]   514  1307      316       31    20480        0             0 logd
[ 3917.842943] [   1359]     0  1359      542       52    20480        0             0 rpcd
[ 3917.851097] [   1562]     0  1562      287        8    12288        0             0 dropbear
[ 3917.859558] [   1660]     0  1660      912       93    20480        0             0 hostapd
[ 3917.867926] [   1661]     0  1661      888       26    24576        0             0 wpa_supplicant
[ 3917.876922] [   1721]     0  1721      447       36    20480        0             0 netifd
[ 3917.885242] [   1777]     0  1777      370       56    16384        0             0 odhcpd
[ 3917.893575] [   2378]     0  2378      314        9    12288        0             0 ntpd
[ 3917.901731] [  10896]     0 10896      324       86    16384        0             0 pppd
[ 3917.909906] [  11046]     0 11046      267       13    12288        0             0 odhcp6c
[ 3917.918300] [  26685]     0 26685      314       11    16384        0             0 crond
[ 3917.926509] [  29621]   453 29621      734      135    24576        0             0 dnsmasq
[ 3917.934898] [  29664]     0 29664      320       16    16384        0             0 sh
[ 3917.942967] [  18940] 65534 18940   168954    10594   110592        0             0 clash
[ 3917.951284] [  20320]     0 20320      313        7    16384        0             0 sleep
[ 3917.959579] [  20605]     0 20605      749      166    12288        0             0 luci
[ 3917.967693] [  20606]     0 20606      749      167    20480        0             0 luci
[ 3917.975790] [  20612]     0 20612      559       79    20480        0             0 luci
[ 3917.983902] [  20613]     0 20613      424       85    12288        0             0 modprobe
[ 3917.992380] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/,task=clash,pid=18940,uid=65534
[ 3918.005590] Out of memory: Killed process 18940 (clash) total-vm:675816kB, anon-rss:42376kB, file-rss:0kB, shmem-rss:0kB, UID:65534 pgtables:108kB oom_score_adj:0
[ 3918.078691] oom_reaper: reaped process 18940 (clash), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB

似乎内核日志中这些是相关的。

**Comment by jackadam1981** [comment]
内存不足？

**Comment by jackadam1981** [comment]
![无标题](https://user-images.githubusercontent.com/28656671/131353887-9e665bf9-09be-420a-ba2b-80f8a392ac48.png)
似乎确定是内存不足造成的。
升级512M内存去，测试完再来汇报。

**Comment by etc-snail** [comment]
看到AC2100,似乎这本身就是有问题，搭载东芝闪存AC2100可能被你买到了。看看换下RAM是不是会好些。  [ 3281.017937] Free swap = 0kB
[ 3281.022073] Total swap = 0kB  
不要急到换flash, 插上U盘，挂载分区为/mnt/sda1（如果是的话）
#cp -r /etc/openclash /mnt/sda1/
#ls -l /mnt/sda1/  ##(有openclash就没问题)
#rm -rf  /etc/openclash/*
#ln -s /mnt/sda1/openclash/* /etc/openclash/
#ls -l /etc/openclash/   ##有相应文件就可以了
如果直接软连接openclash文件夹是启动不了的。
这样测试一下，能够启动成功，但是还是崩溃就是RAM 的问题，没有就是NAND flash颗粒问题，东芝的锅。

**Comment by etc-snail** [comment]
看到AC2100,似乎这本身就是有问题，搭载东芝闪存AC2100可能被你买到了。看看换下NAND flash是不是会好些。 [ 3281.017937] Free swap = 0kB
[ 3281.022073] Total swap = 0kB
不要急到换flash, 插上U盘，挂载分区为/mnt/sda1（如果是的话）
#cp -r /etc/openclash /mnt/sda1/
#ls -l /mnt/sda1/ ##(有openclash就没问题)
#rm -rf /etc/openclash/*
#ln -s /mnt/sda1/openclash/* /etc/openclash/
#ls -l /etc/openclash/ ##有相应文件就可以了
如果直接软连接openclash文件夹是启动不了的。
这样测试一下，能够启动成功，但是还是崩溃就是RAM 的问题，没有就是NAND flash颗粒问题，东芝的锅。

**Comment by jackadam1981** [comment]
ESMT 晶豪内存，也查过坏块。
没有优盘啊，这个不支持USB。

**Comment by etc-snail** [comment]
支持cifsd,挂载共享samba, 这个可以有
