### ISSUE TITLE
使用Fake-ip模式，与解锁网易云音乐插件冲突。

### ISSUE THREAD

**Issue by a936919** [vernesong/OpenClash#158]
使用Fake-ip模式在解锁网易云插件日志中，可以看到已经获取到歌曲信息，直接访问链接是可以播放的，但是客户端只转圈不播放 。使用Redir-Host模式恢复正常。

**Comment by a936919** [comment]
> 使用Fake-ip模式
> 在解锁网易云插件日志中，可以看到已经获取到歌曲信息，直接访问链接是可以播放的，但是客户端只转圈不播放 。使用Redir-Host模式恢复正常。
> ![S00221-06192366](https://user-images.githubusercontent.com/41937411/74985330-2dd28e00-5472-11ea-8872-eaa0c1454580.png)

**Comment by wtser** [comment]
fake 模式 网易云灰色解锁失效了

**Comment by heyuhao5566** [comment]
你好，朋友。
我也发现这个问题了，我用的ShadowSocksR Plus+做代理，也是和网易云解锁冲突！
不知道是什么原因，我只要关了ShadowSocksR Plus+，网易云解锁就又正常了
