### ISSUE TITLE
添加一些规则的时候域名前面是写+号还是*号？

### ISSUE THREAD

**Issue by siren202101** [vernesong/OpenClash#1585]
![20210830231911](https://user-images.githubusercontent.com/80493699/131363625-8c866b33-b68c-4783-af7e-6b0d6cafd01a.png)

像这种 星 号和+号到底有什么区别？
还有自定义Fallback-Filter：里添加的域名前面是用 星 号还是用+

**Comment by liofoil** [comment]
*.baidu.com只匹配www.baidu.com
+.baidu.com可以同时匹配baidu.com, www.baidu.com, a.b.baidu.com
无脑匹配用+就完事

**Comment by siren202101** [comment]
> *.baidu.com只匹配www.baidu.com
> +.baidu.com可以同时匹配baidu.com, [www.baidu.com](http://www.baidu.com) ,abbaidu.com
> 无脑匹配用+就完事

谢谢，我就喜欢无脑的

**Comment by hcym** [comment]
没注意的一种方法，记下试试看看
