### ISSUE TITLE
自定义规则超过一定的数量，每次保存都会一直等待响应。

### ISSUE THREAD

**Issue by a11thwn** [vernesong/OpenClash#159]
没有用第三方规则，没有自动生成，使用自动以规则，如果把整个gfwlist添加到自定义规则里面后，每次修改后点保存都会一直转圈圈，浏览器：正在等待192.168.8.1的响应。
最后只能进入ssh进行reboot。

![Image 3](https://user-images.githubusercontent.com/2621203/75002321-f4fcde00-549e-11ea-9efe-3551197b0c71.png)

**Comment by a11thwn** [comment]
有可能是固件的问题。

**Comment by vernesong** [comment]
写入有限制，会爆内存
