### ISSUE TITLE
FAKE ip模式下，怎么设置黑裙IP或者QB添加例外呢？

### ISSUE THREAD

**Issue by asnon** [vernesong/OpenClash#1592]
我设置了黑裙ip例外，或者是端口直连都没效果呢？
PS：只设置openwrt+openclash环境，没有其他插件DNS劫持或者转发

**Comment by vernesong** [comment]
怎么设置的

**Comment by asnon** [comment]
> 怎么设置的

![image](https://user-images.githubusercontent.com/34601728/132097810-7e466b58-3d3d-4683-82ca-ea30e135ca2c.png)
大佬，是这样设置的，您帮忙看看下~
