### ISSUE TITLE
IP-CIDR与SRC-IP-CIDR有什么区别？

### ISSUE THREAD

**Issue by siren202101** [vernesong/OpenClash#1596]
IP-CIDR：如果请求的IP地址在指定范围内，则规则匹配。
SRC-IP-CIDR：如果请求的客户端IP地址匹配，则规则匹配。
我在网上查到的，这个请求的IP地址和请求的客户端IP地址不一样吗？

**Comment by love4taylor** [comment]
你局域网内有一台 IP 地址为 192.168.1.100 的计算机正在访问 8.8.8.8 的 DNS 服务，此时 8.8.8.8 为 IP-CIDR，192.168.1.100 为 SRC-IP-CIDR

**Comment by lifetyper** [comment]
一个是目标IP，一个是源IP。

**Comment by MBRjun** [comment]
IP-CIDR是设置目标IP，比如你直接打开8.8.8.8，你的规则有"IP-CIDR,8.8.8.8/32,直连"，任何设备访问这个目标都过直连
IP-CIDR6同上，但是是IPv6
SRC-IP-CIDR是源，比如你局域网有一台设备，IP 192.168.1.1，你的规则有"SRC-IP-CIDR,192.168.1.1/32,直连"，这台设备所有请求都直连
