### ISSUE TITLE
0.43.03节点问题

### ISSUE THREAD

**Issue by aiwu12** [vernesong/OpenClash#1597]
手动添加节点后应用配置，配置文件里面找不到节点信息，控制面板也不显示,目前换回之前版本没有问题，是我固件的问题还是软件版本的问题呢

**Comment by aiwu12** [comment]
目前换回之前版本没有问题，是我固件的问题还是软件版本的问题呢

**Comment by thinker226** [comment]
我的情况是无法通过订阅地址更新节点和配置信息
用YAML文件导入能成功
但是节点全部连接失败
事实上节点是可用的
