### ISSUE TITLE
KoolShare LEDE 兼容问题

### ISSUE THREAD

**Issue by didez** [vernesong/OpenClash#16]
* 配置好后，若需要更新托管配置，修改托管参数并点击更新后貌似仅进行了重启
* 定时更新托管，规则，GEOIP 能否正常工作未知

**Comment by vernesong** [comment]
如果有重启就表示更新成功了，运行状态页面的更新日期也会变
没有更新不会进行重启

**Comment by didez** [comment]
问题貌似就出在这里
* 显示下载中日志的时间每次都相同
* 大概0.5秒之后日志提示正在重启dns
* 重启完成后，立即或等待几秒会提示配置文件下载失败

感觉像是没有检测到下载的进度，直接进入了重启的流程，于是反过来导致了下载的失败，lean 的固件一直都是正常的，可能还是 koolshare 的兼容问题

**Comment by vernesong** [comment]
主要koolshare并不在这个项目的维护范围内，有问题我也不会特意去修复的

**Comment by didez** [comment]
明白了, 已经换回 OpenWrt, 多谢提供这么优秀的项目

**Comment by shikkoku** [comment]
> 明白了, 已经换回 OpenWrt, 多谢提供这么优秀的项目

koolshare有另一个专门的项目叫koolclash。
