### ISSUE TITLE
求教dns8.8.8.8强制走代理

### ISSUE THREAD

**Issue by happy201807** [vernesong/OpenClash#160]
您好，Google nest需要8.8.8.8走代理才工作，请问如何配置，单纯规则- IP-CIDR,8.8.8.8/32,Proxy不起作用。请问正确的配置是？

**Comment by vernesong** [comment]
dns已经劫持的情况下，不需要设置任何dns走代理，如果无法使用，请观察内核日志，看设备工作时访问的链接是否走了代理，再添加相应规则

**Comment by vernesong** [comment]
看看在新版本的游戏模式下是否正常

**Comment by Yuanandyuan** [comment]
我也发现有这个问题，在redir-host tun 模式下，8.8.8.8乃至各种udp流量在日志里显示doesn't match any rule, using DIRECT，最后也不走代理。而切换成fake-ip tun就没有问题，非常奇怪

**Comment by vernesong** [comment]
> 我也发现有这个问题，在redir-host tun 模式下，8.8.8.8乃至各种udp流量在日志里显示doesn't match any rule, using DIRECT，最后也不走代理。而切换成fake-ip tun就没有问题，非常奇怪

跟8.8.8.8的通讯端口是什么

**Comment by Yuanandyuan** [comment]
> > 我也发现有这个问题，在redir-host tun 模式下，8.8.8.8乃至各种udp流量在日志里显示doesn't match any rule, using DIRECT，最后也不走代理。而切换成fake-ip tun就没有问题，非常奇怪
> 
> 跟8.8.8.8的通讯端口是什么

就是udp53端口，很玄学的是有时候又会走代理，可能是内核的bug。但我在debian上一样的配置又没有问题。。。。这就完全想不出其中的原因了，看看有没有人还这样吧，也许是我这里诡异的问题
P.s.文档里好像漏了ipset这个依赖
