### ISSUE TITLE
v0.43.04-beta国内流量不过内核（未开启绕过中国大陆IP）

### ISSUE THREAD

**Issue by Dormiveglia0** [vernesong/OpenClash#1601]
例如，在没有开启“绕过中国大陆IP”的情况下，在配置文件中写入“GEOIP,CN,全球直连”并设置策略为”DIRECT“，在控制面板的连接处查看会发现列表中并未有走“全球直连”的域名，即使尝试打开任意的国内网站例如bilibili也不会经过clash内核处理，“GEOIP,CN,全球直连”几乎是必写的规则这个bug会导致无法为国内域名单独设置规则。（再说明一下，并未开启绕过中国大陆IP）
v0.43.01-beta并未有此问题，v0.43.02-beta未测试，v0.43.03-beta、v0.43.04-beta均有此问题，且一旦触发该bug即使删除插件回退版本bug也会存在，尝试过使用winscp将文件夹名为openclash的都删除依旧无法解决（可能是我没有删干净的原因），目前我所知的唯一解决办法就是重刷固件再装入v0.43.01-beta版本的插件。

**Comment by gaohanping** [comment]
同样问题，我以为我设置问题

**Comment by warcns** [comment]
是的，同样的问题。

**Comment by fantasyroot** [comment]
+1

**Comment by zhangguanzhang** [comment]
+1  @vernesong

**Comment by zhangguanzhang** [comment]
@vernesong PTAL

**Comment by warcns** [comment]
v0.43.05 已解决。

**Comment by 21ki** [comment]
~~。~~

**Comment by michaelchen644** [comment]
绕过内核规则是通过修改防火墙实现的，因此可以从防火墙找原因
