### ISSUE TITLE
如何正确使用家庭版DNS？

### ISSUE THREAD

**Issue by ShuiHuo** [vernesong/OpenClash#1603]
Adguard Home 的 家长控制 功能因为不能正确访问他们的 DNS服务器导致失效（勾选这功能后所有网站都不能访问），现在想着在 Open Clash 中添加家庭版DNS服务器进行处理，但我将 `NameServer` 和 `FallBack` 都改成 `94.140.14.15`（AdGuard 的家庭保护 DNS）也没能成功拦截被识别出来（ https://reports.adguard.com ）的成人网站，所以正确的使用方式是怎样的？

**Comment by vernesong** [comment]
https://github.com/vernesong/OpenClash/discussions/1420

**Comment by ShuiHuo** [comment]
> #1420

设置差不多啊，就是`表 NAT`不太一样，不知道哪里不对，防火墙自定义里面全是注释，没有内容。
![表 NAT](https://user-images.githubusercontent.com/7471938/132261736-583b9199-0136-4b4e-b33a-bfd60156943a.png)
![OpenClash DNS设置](https://user-images.githubusercontent.com/7471938/132261742-9e7df1be-f06a-42e5-b01d-e4a6dd22ff9a.png)
![AdGuard Home 设置](https://user-images.githubusercontent.com/7471938/132261743-94cf2252-21b9-4108-95d8-1e836d444974.png)
![AdGuard Home DNS设置](https://user-images.githubusercontent.com/7471938/132261744-d4cc5382-e987-4aa5-a822-61d236277484.png)
