### ISSUE TITLE
大家的TUN模式能用吗？我的软路由链接直接爆掉，100%

### ISSUE THREAD

**Issue by gaohanping** [vernesong/OpenClash#1604]
TUN模式，软路由链接直接爆掉100%，版本是最新版的，老版本也不成，都是一个样子，过一会链接就会爆掉，愁死了![image](https://user-images.githubusercontent.com/82786011/132271527-5a442909-e468-4110-97bd-65a49c89cf6b.jpeg)

**Comment by kxdn3** [comment]
我不会爆掉，不过clash随机死了，得重新启动插件

**Comment by shenyanshu** [comment]
我的也是差不多，tun模式随机挂掉

**Comment by zgc** [comment]
> 我的也是差不多，tun模式随机挂掉

同样问题，感觉加了ipv6之后就没正常过

**Comment by r3yr3** [comment]
萨亚·朱加·蒙加拉米尼亚
