### ISSUE TITLE
v0.43.04 通过主机名访问时，无法访问控制面板

### ISSUE THREAD

**Issue by aueu** [vernesong/OpenClash#1605]
习惯用路由器的主机名访问，譬如 http://home.lan

通过主机名访问，如下

![Screen Shot 2021-09-07 at 9 35 54 AM](https://user-images.githubusercontent.com/1732266/132271099-23ee5c77-8a95-4dcc-ace1-c5d2fb6a1051.png)

通过 ip 访问时，则可以

![Screen Shot 2021-09-07 at 9 36 38 AM](https://user-images.githubusercontent.com/1732266/132271156-eac1e9fa-8aa3-4a33-904e-cd0763694a0a.png)

**Comment by realyn** [comment]
确实有这个问题
