### ISSUE TITLE
Did openclash support mwan3?

### ISSUE THREAD

**Issue by malikshi** [vernesong/OpenClash#1610]
Mwan3 using 0x3F00 see [Mwan3](https://github.com/openwrt/packages/blob/openwrt-19.07/net/mwan3/files/lib/mwan3/mwan3.sh) 
 Additional info [Qna](https://unix.stackexchange.com/questions/282993/how-to-add-marks-together-in-iptables-targets-mark-and-connmark) 
I tried url-test and load-balance in proxy groups the traffic going to only one wan. Usually the speed when using mwan3 1+1=2 but using openclash only got 1+1=1 ?

**Comment by vernesong** [comment]
not support yet

**Comment by malikshi** [comment]
> not support yet

Thank you for the info, openclash didn't conflict with the mark but the traffic usage only to one wan, you may check this

**Comment by malikshi** [comment]
With clash support outbound NIC, so i considered this issjes fixed
