### ISSUE TITLE
ipv6代理能否加个总开关？

### ISSUE THREAD

**Issue by tinnlux** [vernesong/OpenClash#1611]
当节点无ipv6地址的时候，就算本地网络有ipv6，dns设置里勾选允许IPV6类型DNS解析，也无法正常解析国内ipv6域名，只能通过输入ipv6地址访问。如果把设置里的“IPv6 流量代理”关闭，直接把本地ipv6的网络都关了，这样对于有访问纯ipv6地址的人来说还不如之前不支持ipv6代理的时候，能否加一个总开关，关闭以后是恢复到以前那样，clash完全不管ipv6的代理，ipv6走本地网络，能正常通过本地ipv6解析地址？

**Comment by Zyilin98** [comment]
+1 我更新到v0.43.04-beta 之后就发现我ipv6 也这样了
挺希望ipv6 不走代理 直接用本地网络的

**Comment by vernesong** [comment]
模式设置的ipv6代理和DNS设置的ipv6dns是分开的，不会存在你说的情况

**Comment by tinnlux** [comment]
> 模式设置的ipv6代理和DNS设置的ipv6dns是分开的，不会存在你说的情况

可是现在真的是无法解析ipv6域名。。不止我一个人遇到这个问题，我现在的现象是关闭模式设置的ipv6代理，就算开启dns设置的ipv6解析也一样是无法解析。您可以试一下，真的是这样。

**Comment by Zyilin98** [comment]
> 模式设置的ipv6代理和DNS设置的ipv6dns是分开的，不会存在你说的情况

我自己v0.43.04-beta版本的实验就是 允许IPV6类型DNS解析 打开ipv6代理 打开绕过大陆ipv6 这样一样没法正常访问大陆的ipv6网站 如果还得从规则里指定 无疑增加更多工作量
关闭ipv6代理 关闭绕过大陆ipv6 仅开启允许IPV6类型DNS解析 还是会出现无法访问的情况发生

**Comment by vernesong** [comment]
![image](https://user-images.githubusercontent.com/42875168/132671208-8ab5cb4d-b7ed-4252-a157-3e0d3566684c.png)
![image](https://user-images.githubusercontent.com/42875168/132671319-3c363db3-e0c2-48b7-8e3a-ceaaea4bbfa0.png)
![image](https://user-images.githubusercontent.com/42875168/132671381-6e820057-ea2d-4baf-bcd8-0c000ba67222.png)

**Comment by vernesong** [comment]
不启用v6代理，v6的流量规则就不会添加，你要确认一下是不是防火墙没清理干净
v6的dns是由dnsmasq转发给clash，确认dnsmasq开启了ipv6解析

**Comment by tinnlux** [comment]
> 不启用v6代理，v6的流量规则就不会添加，你要确认一下是不是防火墙没清理干净
> v6的dns是由dnsmasq转发给clash，确认dnsmasq开启了ipv6解析

ip.sb，ipv6-test这样的网站可以看到本机的ipv6地址啊，是无法访问别的纯ipv6域名网站，可以通过ipv6地址访问

**Comment by tinnlux** [comment]
> 不启用v6代理，v6的流量规则就不会添加，你要确认一下是不是防火墙没清理干净
> v6的dns是由dnsmasq转发给clash，确认dnsmasq开启了ipv6解析

> 

> 不启用v6代理，v6的流量规则就不会添加，你要确认一下是不是防火墙没清理干净
> v6的dns是由dnsmasq转发给clash，确认dnsmasq开启了ipv6解析

你ping -6 +域名，试试，是无法解析的

**Comment by Zyilin98** [comment]
> > 不启用v6代理，v6的流量规则就不会添加，你要确认一下是不是防火墙没清理干净
> > v6的dns是由dnsmasq转发给clash，确认dnsmasq开启了ipv6解析
> 
> ip.sb，ipv6-test这样的网站可以看到本机的ipv6地址啊，是无法访问别的纯ipv6域名网站，可以通过ipv6地址访问

我自己实验是用的清华tuna镜像站的ipv6地址 浏览器返回的错误是NXDOMAIN

**Comment by vernesong** [comment]
东北大学那个是纯6的啊

**Comment by vernesong** [comment]
speed.neu6.edu.cn

**Comment by tinnlux** [comment]
> > > 不启用v6代理，v6的流量规则就不会添加，你要确认一下是不是防火墙没清理干净
> > > v6的dns是由dnsmasq转发给clash，确认dnsmasq开启了ipv6解析
> > 
> > 
> > ip.sb，ipv6-test这样的网站可以看到本机的ipv6地址啊，是无法访问别的纯ipv6域名网站，可以通过ipv6地址访问
> 
> 我自己实验是用的清华tuna镜像站的ipv6地址 浏览器返回的错误是NXDOMAIN

是的，ip地址检测网站都能正常检测到本机ipv6地址，但是问题是路由器无法正常解析ipv6域名，你ping -6 加域名试试，把clqsh关了就能正常解析了

**Comment by Zyilin98** [comment]
> > > > 不启用v6代理，v6的流量规则就不会添加，你要确认一下是不是防火墙没清理干净
> > > > v6的dns是由dnsmasq转发给clash，确认dnsmasq开启了ipv6解析
> > > 
> > > 
> > > ip.sb，ipv6-test这样的网站可以看到本机的ipv6地址啊，是无法访问别的纯ipv6域名网站，可以通过ipv6地址访问
> > 
> > 
> > 我自己实验是用的清华tuna镜像站的ipv6地址 浏览器返回的错误是NXDOMAIN
> 
> 是的，ip地址检测网站都能正常检测到本机ipv6地址，但是问题是路由器无法正常解析ipv6域名，你ping -6 加域名试试，把clqsh关了就能正常解析了

一样 确实是这样
我一会按照作者的方法试一下

**Comment by vernesong** [comment]
![image](https://user-images.githubusercontent.com/42875168/132673061-e0eda32a-749e-473f-9810-c79b631e7f11.png)

**Comment by vernesong** [comment]
![image](https://user-images.githubusercontent.com/42875168/132673348-785686a3-a02b-49cf-890b-87e8e37c2e4e.png)

**Comment by vernesong** [comment]
![image](https://user-images.githubusercontent.com/42875168/132673586-cc4dbae0-74bf-4cf6-98df-38d1eff49f19.png)
![image](https://user-images.githubusercontent.com/42875168/132673606-2ba6d11f-f0f5-46cf-a863-1c6196617620.png)

**Comment by tinnlux** [comment]
这真的很奇怪。。难道是我编译的固件版本的事吗。

**Comment by tinnlux** [comment]
@vernesong 大佬你好，我复现了这个问题，在clash刚开始工作的时候是可以ping通ipv6域名的，但是当点换节点后会出现无法ping通的问题。

**Comment by tinnlux** [comment]
就是clash刚开始运行时，ipv6能正常运作，但是通过控制面板手动更换节点以后就无法解析ipv6的域名了，只能通过直接输入ipv6地址才可以访问。我不知道这个问题是我编译的openwrt master版本的问题还是其他原因引起的。

**Comment by Zyilin98** [comment]
> 就是clash刚开始运行时，ipv6能正常运作，但是通过控制面板手动更换节点以后就无法解析ipv6的域名了，只能通过直接输入ipv6地址才可以访问。我不知道这个问题是我编译的openwrt master版本的问题还是其他原因引起的。

我这边是完全正常的 更换节点也没问题 固件是用的别人编译的 已经提前把clash编译进去了

**Comment by tinnlux** [comment]
> > 就是clash刚开始运行时，ipv6能正常运作，但是通过控制面板手动更换节点以后就无法解析ipv6的域名了，只能通过直接输入ipv6地址才可以访问。我不知道这个问题是我编译的openwrt master版本的问题还是其他原因引起的。
> 
> 我这边是完全正常的 更换节点也没问题 固件是用的别人编译的 已经提前把clash编译进去了

你这边彻底好了啊╯︿╰。。那这样看来我这边是我固件的问题了。。但是我这边的情况是openclash加入ipv6支持以前是完全没问题的。。加了以后才这样，不行我自己把我本地这部分代码还原回去试试好了。。我宁愿不要ipv6代理。

**Comment by irrocu** [comment]
相同的问题，用了openclash快一年了， ipv6一切正常， 这次升级v0.43.05-beta，ipv6就不通了，关闭openclash就OK了，设置都是没有变过的，ipv6的代理和ipv6的dns都是没有勾选的。

**Comment by WangJiyuanYo** [comment]
客户端不关闭ipv6的情况下都不走代理。海外网站都打不开
