### ISSUE TITLE
dev tun game 内核具体差异是？

### ISSUE THREAD

**Issue by phlinhng** [vernesong/OpenClash#1612]
作者您好，我阅读了文档中[Fake-IP、Redir-Host模式选择](https://github.com/vernesong/OpenClash/wiki/%E5%B8%B8%E8%A7%84%E8%AE%BE%E7%BD%AE)，对三种内核有些不太理解的地方。
```
兼容: tcp 和 udp 都走 redir-host (fake-ip)
tun: tcp 和 udp 都走 clash_tun
游戏: tcp 和 udp 都走 clash_game
混合: tcp 走 redir-host (fake-ip), udp 走 clash_tun
```

请问这样理解对么？如果要追求 NAT 等级和 Switch 联机体验，应该选 tun 还是 game 模式呢？
tun 或 game 模式会影响一般上网场景（看视频、浏览网页）的 tcp 吞吐量么？

**Comment by MBRjun** [comment]
我想顺便问问如果节点不支持UDP，使用哪个好（

**Comment by vernesong** [comment]
内核的区别是功能支持与否，每次只会启动一个内核，模式只是区分流量走tproxy还是tun，节点不支持udp就会直连，打游戏用redir

**Comment by phlinhng** [comment]
謝謝作者回應。另外，我在 https://github.com/vernesong/OpenClash/issues/333 找到關於 game 內核的說明了。
