### ISSUE TITLE
旁路由使用OpenClash需要重置防火墙规则才能正确显示nat类型

### ISSUE THREAD

**Issue by MagicBoost** [vernesong/OpenClash#1615]
旁路由和主路由互相将对方IP指定为网关。
旁路由开启openclash后，switch的nat类型显示为F，重置防火墙规则后，nat类型显示为A。
旁路由不开启openclash，nat类型显示为A。
可以确定规则匹配到了，并且能够转发udp到代理服务器。
请问可以帮我解惑一下吗？

**Comment by vernesong** [comment]
主路由为什么要指定旁路由为网关

**Comment by MagicBoost** [comment]
> 主路由为什么要指定旁路由为网关

啊，是我表述错误了，不好意思。
主路由把dhcp关掉了，只有旁路由将主路由作为网关，旁路由作为其余设备网关。
