### ISSUE TITLE
用SSR Server或V2ray Server连回路由器翻墙，telegram客户端连不上。

### ISSUE THREAD

**Issue by kinddinosaur** [vernesong/OpenClash#162]
反映一个问题：
目前用的斐讯N1 openwrt，刷的是同步编译自近期LEAN大源码的固件。Openclash客户端v0.36.6-beta, 内核v0.17.1-28-gf3f8e7e。机场是V2RAY机场。使用的规则是第三方ihie1规则启动失败后自动启动的备用规则(内置的2种第三方规则都会启动失败然后切换到备用规则)。
存在问题：
N1上装了SSR Server或V2ray Server，开放端口，然后手机或PC通过V2rayN(G)连回路由器。此时手机浏览器、Youtube APP或PC浏览器可以翻墙。但是手机或PC上的Telegram APP不能连接。
如果直接用usb网卡把N1的网络接出第二网口，不用SSR Server或V2ray Server，让手机或PC作为N1路由器的客户端，则上述软件都可以翻墙。
不知道能否添加自定义规则，感觉是从SSR Server或V2ray Server代理回来的telegram流量不能识别。

**Comment by vernesong** [comment]
服务端翻墙的话前提是路由自身翻墙（fake-ip模式），由于Telegram APP的部分连接是ip形式直连，fake-ip模式下无法劫持这部分流量所有无法翻墙，你可以尝试一下步骤：
启动后：
```
ipset create telegram hash:net
ipset add telegram 91.108.4.0/22
ipset add telegram 91.108.8.0/22
ipset add telegram 91.108.12.0/22
ipset add telegram 91.108.16.0/22
ipset add telegram 91.108.56.0/22
ipset add telegram 149.154.160.0/20
iptables -t nat -A OUTPUT -p tcp -m set --match-set telegram dst -j REDIRECT --to-ports 7892
#7892是你配置文件里的redir-port
#确保以上ip地址在你的配置文件里是设置的走代理的规则，否则会引起回环导致死机。
```
关闭：
```
ipset destroy telegram >/dev/null 2>&1
iptables -t nat -D OUTPUT -p tcp -m set --match-set telegram dst -j REDIRECT --to-ports 7892

```
此问题暂时只能手动解决，等到clash能够完全处理自身流量时我会及时跟进。

**Comment by kinddinosaur** [comment]
多谢，辛苦!

**Comment by CrazyMouse** [comment]
我也有这个问题，想请教一下原理，我的连接方式如下

- 方式一：路由装openclash， fake-ip模式，路由上开启v2ray server，手机或PC代理连接到V2ray Server

- 方式二：手机或PC直接在局域网内不设置任何代理

现象：

- 方式一：大部分软件正常，但是Telegram无法连接

- 方式二：Telegram也能正常连接 

我的问题有两个：

1. 产生这个现象的原因是啥？是否有推荐解决方案？（需要V2ray Server做跳板的原因是想从其他地方跳回家里，走家里统一的数据出口）

2.这个问题是不是因为V2ray Server在路由上引起的，如果我单独在家里找个机器做V2ray Server，这个问题是不是能解决？（也就是说，我猜测这个问题是由于路由对于V2ray 接入的流量是本地流量，FakeIP对这种情况无法解决，不知道对不对）

以上是我的疑问，望不吝赐教，感激不尽

**Comment by vernesong** [comment]
clash和V2ray Server不在一个机器上就行了

**Comment by CrazyMouse** [comment]
@vernesong 非常感谢，问一下，这就是那个啥回环问题引起的么？

**Comment by vernesong** [comment]
上面说了，不能代理ip直连的链接，目前openwrt和clash的配合无法实现

**Comment by CrazyMouse** [comment]
> 上面说了，不能代理ip直连的链接，目前openwrt和clash的配合无法实现

我不太明白的是，为啥从路由的v2ray server过来的就不行，找个机器做跳板就可以了。理论上将，不管从哪来的，都是请求的IP连接啊，望大佬赐教

**Comment by vernesong** [comment]
因为暂时区分不了clash出来的流量，所以无法代理路由自身的ip流量，fakeip可以代理路由自身除ip直连的流量是因为客户端使用的是clash返回的fakeip发起的链接。

**Comment by CrazyMouse** [comment]
@vernesong 我仔细读了好几遍，对于我这个门外汉还是太难理解了，不管怎么说，谢谢您

**Comment by CrazyMouse** [comment]
发现一个很奇怪的问题，内网搞个机器做跳板机，从内网将它设置为代理，TG能正常使用，但是通过DDNS，从路由走端口映射进来，TG就不行了，twitter和油管都没问题

**Comment by AlfredWang777** [comment]
我使用的情况是：
Openclash+SSR Server（SSR plus）

关于tg不能被代理的问题，
我在用的方案是：
在tg中启动socks5代理，指向局域网中openclash宿主机地址及端口（如果使用有规则，将本地ip段相应规则删去）

**Comment by CrazyMouse** [comment]
> 我使用的情况是：
> Openclash+SSR Server（SSR plus）
> 
> 关于tg不能被代理的问题，
> 我在用的方案是：
> 在tg中启动socks5代理，指向局域网中openclash宿主机地址及端口（如果使用有规则，将本地ip段相应规则删去）

问题在于，我的openclash是安装在网关上的，还有就是，我使用的时候不在局域网内使用，通过外网跳进去的

**Comment by AlfredWang777** [comment]
> > 我使用的情况是：
> > Openclash+SSR Server（SSR plus）
> > 
> > 关于tg不能被代理的问题，
> > 我在用的方案是：
> > 在tg中启动socks5代理，指向局域网中openclash宿主机地址及端口（如果使用有规则，将本地ip段相应规则删去）
> 
> 问题在于，我的openclash是安装在网关上的，还有就是，我使用的时候不在局域网内使用，通过外网跳进去的

使用ssr plus 中的ssr server（本地服务器），以你的软路由为服务器对你的非局域网内客户端（如手机）服务。其中需要使用动态域名解析，将动态ip解析到你的主路由上（如有公网ip可忽略）。之后，在配置客户端即可实现非局域网内使用家中的上网环境。这样既可以使用openclash的各种规则，又可以使用固定宽带的上网环境。（解决tg不能连接：因为已经使用ssr实现了回家，直接在socks5代理中填写你的openclash ip地址及socks5端口号即可。）

**Comment by CrazyMouse** [comment]
> > > 我使用的情况是：
> > > Openclash+SSR Server（SSR plus）
> > > 关于tg不能被代理的问题，
> > > 我在用的方案是：
> > > 在tg中启动socks5代理，指向局域网中openclash宿主机地址及端口（如果使用有规则，将本地ip段相应规则删去）
> > 
> > 
> > 问题在于，我的openclash是安装在网关上的，还有就是，我使用的时候不在局域网内使用，通过外网跳进去的
> 
> 使用ssr plus 中的ssr server（本地服务器），以你的软路由为服务器对你的非局域网内客户端（如手机）服务。其中需要使用动态域名解析，将动态ip解析到你的主路由上（如有公网ip可忽略）。之后，在配置客户端即可实现非局域网内使用家中的上网环境。这样既可以使用openclash的各种规则，又可以使用固定宽带的上网环境。（解决tg不能连接：因为已经使用ssr实现了回家，直接在socks5代理中填写你的openclash ip地址及socks5端口号即可。）

是个不错的主意，我一直没搞明白的就是 ssr都回家到软路由了 为啥tg还要单独设置sockets代理。大致原因是clash无法区分自身流量 可是我上面的 通过局域网的一台机器做跳板 从外部进来也不行 这是个很诡异的地方

**Comment by AlfredWang777** [comment]
> > > > 我使用的情况是：
> > > > Openclash+SSR Server（SSR plus）
> > > > 关于tg不能被代理的问题，
> > > > 我在用的方案是：
> > > > 在tg中启动socks5代理，指向局域网中openclash宿主机地址及端口（如果使用有规则，将本地ip段相应规则删去）
> > > 
> > > 
> > > 问题在于，我的openclash是安装在网关上的，还有就是，我使用的时候不在局域网内使用，通过外网跳进去的
> > 
> > 使用ssr plus 中的ssr server（本地服务器），以你的软路由为服务器对你的非局域网内客户端（如手机）服务。其中需要使用动态域名解析，将动态ip解析到你的主路由上（如有公网ip可忽略）。之后，在配置客户端即可实现非局域网内使用家中的上网环境。这样既可以使用openclash的各种规则，又可以使用固定宽带的上网环境。（解决tg不能连接：因为已经使用ssr实现了回家，直接在socks5代理中填写你的openclash ip地址及socks5端口号即可。）
> 
> 是个不错的主意，我一直没搞明白的就是 ssr都回家到软路由了 为啥tg还要单独设置sockets代理。大致原因是clash无法区分自身流量 可是我上面的 通过局域网的一台机器做跳板 从外部进来也不行 这是个很诡异的地方

上面的方案我在用 你可以做参考 ：）

**Comment by lovelyOK** [comment]
> > > > > 我使用的情况是：
> > > > > Openclash+SSR Server（SSR plus）
> > > > > 关于tg不能被代理的问题，
> > > > > 我在用的方案是：
> > > > > 在tg中启动socks5代理，指向局域网中openclash宿主机地址及端口（如果使用有规则，将本地ip段相应规则删去）
> > > > 
> > > > 
> > > > 问题在于，我的openclash是安装在网关上的，还有就是，我使用的时候不在局域网内使用，通过外网跳进去的
> > > 
> > > 
> > > 使用ssr plus 中的ssr server（本地服务器），以你的软路由为服务器对你的非局域网内客户端（如手机）服务。其中需要使用动态域名解析，将动态ip解析到你的主路由上（如有公网ip可忽略）。之后，在配置客户端即可实现非局域网内使用家中的上网环境。这样既可以使用openclash的各种规则，又可以使用固定宽带的上网环境。（解决tg不能连接：因为已经使用ssr实现了回家，直接在socks5代理中填写你的openclash ip地址及socks5端口号即可。）
> > 
> > 
> > 是个不错的主意，我一直没搞明白的就是 ssr都回家到软路由了 为啥tg还要单独设置sockets代理。大致原因是clash无法区分自身流量 可是我上面的 通过局域网的一台机器做跳板 从外部进来也不行 这是个很诡异的地方
> 
> 上面的方案我在用 你可以做参考 ：）

你这个方案，有没有尝试过这样的场景：
路由器上端口转发8090至局域网的EMBY服务器做视频播放用。。。。外网用户，正常访问路由器公网IP:8090是可以正常显示页面的，但如果外网用户使用开启SSR连到路由器后，再访问公网IP:8090就无法打开页面了。
【我有这个现象】

**Comment by kinddinosaur** [comment]
新版openclash已经可以代理路由器自身流量了，感谢OC和CLASH的各位作者！

**Comment by Joker-lm** [comment]
> 

我也遇到这样的问题，请问你解决了吗？

**Comment by Joker-lm** [comment]
> 

这样做了也显示代理不可用

**Comment by Joker-lm** [comment]
> > > 我使用的情况是：
> > > Openclash+SSR Server（SSR plus）
> > > 关于tg不能被代理的问题，
> > > 我在用的方案是：
> > > 在tg中启动socks5代理，指向局域网中openclash宿主机地址及端口（如果使用有规则，将本地ip段相应规则删去）
> > 
> > 
> > 问题在于，我的openclash是安装在网关上的，还有就是，我使用的时候不在局域网内使用，通过外网跳进去的
> 
> 使用ssr plus 中的ssr server（本地服务器），以你的软路由为服务器对你的非局域网内客户端（如手机）服务。其中需要使用动态域名解析，将动态ip解析到你的主路由上（如有公网ip可忽略）。之后，在配置客户端即可实现非局域网内使用家中的上网环境。这样既可以使用openclash的各种规则，又可以使用固定宽带的上网环境。（解决tg不能连接：因为已经使用ssr实现了回家，直接在socks5代理中填写你的openclash ip地址及socks5端口号即可。）

域名加端口，提示代理不可用
