### ISSUE TITLE
openclash开启后 本地k8s集群DNS无法解析

### ISSUE THREAD

**Issue by jiminHuang** [vernesong/OpenClash#1623]
## 背景
- 旁路由192.168.0.254，开启openclash，设置DNS劫持与上游服务器
- 内网建立k8s集群
- 集群内使用coredns服务，转发集群外DNS到192.168.0.254

## 结果
![image](https://user-images.githubusercontent.com/7194287/132973813-b71a1610-378c-4086-aca4-ae04a5456cfa.png)
![image](https://user-images.githubusercontent.com/7194287/132973871-f6c27ba8-c4ff-4ced-b393-e8dd6ccbdf55.png)
1. 容器内外网域名解析 REFUSED
2. 直接指定DNS服务，解析正常
3. 关闭openclash后正常

一开始都没有想到是openclash的原因，请问可能是什么问题？

**Comment by zhangguanzhang** [comment]
劫持了dns的，iptables -t nat -S | grep 53

**Comment by jiminHuang** [comment]
> iptables -t nat -S | grep 53

执行结果如下

![image](https://user-images.githubusercontent.com/7194287/133915838-c20927cf-f866-44b5-b1ad-58c421c7e023.png)

抱歉，这一块我不太熟悉，为什么会导致DNS refused的结果出现？

**Comment by zgc** [comment]
一年前我也遇到过，我换成'Redir-Host（兼容）模式'就好了
