### ISSUE TITLE
保留策略组设置情况下，订阅失效后会导致 Parse config error: proxy group[1]: `use` or `proxies` missing"

### ISSUE THREAD

**Issue by MeowRay** [vernesong/OpenClash#1624]
使用订阅配置，保留其配置，订阅失效后，就没办法启动clash了
但我还有自己手动额外添加的节点
策略组理应跟服务器配置节点没有直接关联吧？或者难道策略组内必须至少要有一个节点么？能否在节点配置里添加一个始终为所有策略组默认的选项么？
![image](https://user-images.githubusercontent.com/29674595/132974381-5ebf073f-68e6-4fd4-964f-c2f44c7e78a9.png)
![image](https://user-images.githubusercontent.com/29674595/132974382-cf12c3c3-89d8-4b7b-98fa-683a870fb5fd.png)

**Comment by vernesong** [comment]
策略组必须配置一个节点或者DIRECT这样的策略
