### ISSUE TITLE
Clash 在防火墙中添加了对于 53 端口的拦截，导致 DNS 不可用

### ISSUE THREAD

**Issue by zhengcan** [vernesong/OpenClash#1630]
如果启用了 DNS 劫持，那么现在 OpenClash 会修改 iptables 防火墙，增加对于 53 端口的重定向拦截。
这个导致在同时使用 ADGuard 时，53 端口仅可以在 OpenWRT 本机使用，其他机器不可使用

```
Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination
1    REDIRECT   tcp  --  0.0.0.0/0            8.8.4.4              tcp dpt:53 redir ports 7892
2    REDIRECT   tcp  --  0.0.0.0/0            8.8.8.8              tcp dpt:53 redir ports 7892
3    REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:53 /* DNS Hijack */ redir ports 7874
4    REDIRECT   udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:53 /* DNS Hijack */ redir ports 7874
5    prerouting_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom prerouting rule chain */
6    zone_lan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
7    openclash  tcp  --  0.0.0.0/0            0.0.0.0/0
```

建议不要处理防火墙

**Comment by meowtech** [comment]
感谢告知，折腾了一下午也没弄清，现在终于知道问题出在哪里了。

**Comment by zhengcan** [comment]
这里备注一下临时修复语句：

```
iptables -t nat -L | grep DNS | awk '{a[i++]=$1} END {for (j=i-1;j>=0;) system("iptables -t nat -D PREROUTING "a[j--])}'
```

**Comment by zhangguanzhang** [comment]
clash是设置127.0.0.1:7874作为dnsmasq的上游的，你可以clash的上游用 adh，adh端口设置非53例如5300，然后clash上游 127.0.0.1:5300这样使用

**Comment by zhengcan** [comment]
> clash是设置127.0.0.1:7874作为dnsmasq的上游的，你可以clash的上游用 adh，adh端口设置非53例如5300，然后clash上游 127.0.0.1:5300这样使用

我现在是在 HomeLede 里面用，HomeLede 版本不算新
现在实际的 DNS 转发路径是 :53 -> ADH -> :54 -> Clash -> :7874/:6053/:7053
ADH 现在的版本没有改端口的界面，所以不折腾

**Comment by zhengcan** [comment]
另外，在使用 ADH 处理入站 DNS 查询时，没看到 Clash 有任何必要改防火墙
实测改一下防火墙配置后，世界就清净了

**Comment by zhangguanzhang** [comment]
> > clash是设置127.0.0.1:7874作为dnsmasq的上游的，你可以clash的上游用 adh，adh端口设置非53例如5300，然后clash上游 127.0.0.1:5300这样使用
> 
> 我现在是在 HomeLede 里面用，HomeLede 版本不算新
> 现在实际的 DNS 转发路径是 :53 -> ADH -> :54 -> Clash -> :7874/:6053/:7053
> ADH 现在的版本没有改端口的界面，所以不折腾

那你这样adh的dns over https啥的就没用上，clash在adh前面好些

**Comment by vernesong** [comment]
那就不要开劫持，我都劫持了你又开ADG去抢DNS干什么

**Comment by zhangguanzhang** [comment]
> 那就不要开劫持，我都劫持了你又开ADG去抢DNS干什么

adh没开劫持，我是dnsmasq 53，openclash劫持，openclash上游是adh的5300 udp。，如果openclash开劫持就dns不正常，取消劫持，dnsmasq上游写127.0.0.1#7874才正常

**Comment by zhengcan** [comment]
> 那就不要开劫持，我都劫持了你又开ADG去抢DNS干什么

不排除有兼容性问题。
在 HomeLede 里面，ADH 和 OpenClash 0.43.5-beta 一起用，那么按照我的解决方案改防火墙才能正常
如果跟 0.42.5-beta 一起用，那么相同的配置下就非常正常，并不需要动防火墙。

0.42.5-beta 下，防火墙如下：
```
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination
REDIRECT   tcp  --  anywhere             dns.google           tcp dpt:domain redir ports 7892
REDIRECT   tcp  --  anywhere             dns.google           tcp dpt:domain redir ports 7892
prerouting_rule  all  --  anywhere             anywhere             /* !fw3: Custom prerouting rule chain */
zone_lan_prerouting  all  --  anywhere             anywhere             /* !fw3 */
zone_docker_prerouting  all  --  anywhere             anywhere             /* !fw3 */
REDIRECT   udp  --  anywhere             anywhere             udp dpt:domain /* dns_hijack */ redir ports 54
REDIRECT   tcp  --  anywhere             anywhere             tcp dpt:domain /* dns_hijack */ redir ports 54
openclash  tcp  --  anywhere             anywhere
```

跟 0.43.5-beta 相比，dns_hijack 是转发到 54 端口的。似乎这是最关键的区别
