### ISSUE TITLE
界面下方图标

### ISSUE THREAD

**Issue by qin9125** [vernesong/OpenClash#1631]
![image](https://user-images.githubusercontent.com/32502941/133004162-c23e4313-6c1c-479b-9c71-bd57f1f278ac.png)
 v 总能调整一下让dc 的图标在不登录的情况下显示吗？强迫症好难受 dc 对我没用不登录的情况下，这个图标一直是破碎不显示的登录账号后就是好的，能修一下吗

**Comment by zlfzy** [comment]
确实逼死强迫症

**Comment by qin9125** [comment]
> 确实逼死强迫症

贼难受
