### ISSUE TITLE
新版Open Clash在N1盒子上，客户端无法使用ping命令

### ISSUE THREAD

**Issue by cs2021hv001** [vernesong/OpenClash#1633]
![QQ截图20210913133317](https://user-images.githubusercontent.com/89976757/133029071-cc922e08-5887-48e4-b92b-b79b3a92ac6d.png)
N1盒子上可以ping通国内域名，国外域名无法ping
客户端上国内域名、国外域名都无法ping通
Fake-IP和Redir-Host模式都试过
ping失败后路由器系统日志和OpenClash日志都没有什么记录

**Comment by zhangguanzhang** [comment]
这个ip是保留地址，你dns估计被运营商劫持了，用dns over http试试

**Comment by cs2021hv001** [comment]
> 这个ip是保留地址，你的dns估计被运营商劫持了，用dns over http缺陷

换了不行，刚也开一个吃灰的N1试了，开启OpenClash前可以ping通国内，一但打开OpenClash就ping不通了
打开X86也不行了，之前的版本我还ping过可以ping通的
DNS设置页面有  “追加上游DNS”这个后我也是刚试，还以为是N1的问题，原来X86也一样，现在ping百度都是假IP还不通了，之前都是真IP
![QQ截图20210913133317](https://user-images.githubusercontent.com/89976757/133036533-3803a443-6dbf-4c90-9d21-84f00064694d.png)

**Comment by cs2021hv001** [comment]
感觉是  “追加上游DNS”   这个功能导致的
我下载运行配置，把 “追加上游DNS”关闭，删除dns: 下的主路由IP 192.168.1.1
后可以ping通，但是和旧版的 ping国内的不同，国内也是假IP
![QQ截图20210913133317](https://user-images.githubusercontent.com/89976757/133051623-fb8e0c00-5c85-4742-bca3-2ec5bf4c0e58.png)
关键是新版本我这里不开启 “追加上游DNS” 功能无法翻墙
Fake-IP模式

**Comment by MBRjun** [comment]
> 这个ip是保留地址，你dns估计被运营商劫持了，用dns over http试试

亲，Fake-IP模式返回就是保留地址哦 198.18.0.0/15

**Comment by MBRjun** [comment]
> 感觉是 “追加上游DNS” 这个功能导致的
> 我下载运行配置，把 “追加上游DNS”关闭，删除dns: 下的主路由IP 192.168.1.1
> 把修改后的配置上传，关闭“追加上游DNS” 功能
> 后可以ping通，但是和旧版的 ping国内的不同，国内也是假IP
> ![QQ截图20210913133317](https://user-images.githubusercontent.com/89976757/133051623-fb8e0c00-5c85-4742-bca3-2ec5bf4c0e58.png)
> 关键是新版本我这里不开启 “追加上游DNS” 功能无法翻墙
> Fake-IP模式

追加上游我记得是在你已经设置的dns列表里再加上自动获取运营商的
198.18Ping不同检查路由器
如果Ping的非保留地址而且是国外被封的一般不通是正常的，ICMP不会代理

**Comment by MBRjun** [comment]
疑似Bug，因为我也出了这问题

**Comment by BiuZero** [comment]
Fake-IP模式就是这样的啊

不想要这样换Redir-Host模式
