### ISSUE TITLE
Rules port range

### ISSUE THREAD

**Issue by 18rudi** [vernesong/OpenClash#1639]
How to set rule with port range? example port 1000-1200

**Comment by vernesong** [comment]
```
script:
  code: |
    def main(ctx, metadata):
        port = int(metadata["dst_port"])
            if port <= 1000 and port >= 1200:
                ctx.log('[Script] matched Port Limit traffic use DIRECT')
                return "DIRECT"
```
Use the tun core and switch to script mode. The above rules can only restrict ports, you need to combine more rules to divert traffic.

Example [here](https://github.com/vernesong/OpenClash/blob/32b241ecf8aca5401e3a24de43e0ecf1fcf295b3/luci-app-openclash/root/usr/share/openclash/res/lhie1.yaml#L54)
