### ISSUE TITLE
open clash影响下游设备自动更新时间

### ISSUE THREAD

**Issue by shunlongyang** [vernesong/OpenClash#1642]
家里有一台电视，有一个笔记本电脑。当打开openclash之后，这两台设备都无法自动更新系统时间了。
以笔记本（Windows11，估计Windows10也一样）为例，复现 手段为：先把自动同步时间按钮关闭，手动随意设置个时间，然后再点打开，会一直在这个打开按钮转圈，时间也不更新。
clash的设置只加了一个订阅地址，其他都没动，从clash的连接里也没找到是哪个连接。有点怀疑是DNS或者UDP端口方面的问题，具体不太懂，求大家帮忙看下咋回事。

**Comment by MBRjun** [comment]
下游设备检查是否能连接NTP服务器
顺便问问，你使用的是 Fake-IP 吗

**Comment by shunlongyang** [comment]
> 下游设备检查是否能连接NTP服务器
> 顺便问问，你使用的是 Fake-IP 吗

不知道Windows和电视的服务器是什么，昨天又做了个实验：
1. 默认Redir-Host兼容模式  —— 时间无法更新
2. Redir-Host 混合模式  —— 时间可以更新
3. fake-ip模式混个模式 —— 时间可以更新
但是感觉fake-ip的模式下手机刷淘宝、PDD图片出来很慢
