### ISSUE TITLE
最新0.43.05微信聊天无法加载图片

### ISSUE THREAD

**Issue by mzl0408** [vernesong/OpenClash#1645]
升级0.43.05后微信聊天很多都无法加载图片，有的能出来但是速度很慢，退回0.43.04后一切都变好了。

**Comment by vernesong** [comment]
之前反馈是禁用quic的影响，新版已经不再屏蔽国内IP的QUIC，你也可以尝试关闭

**Comment by mzl0408** [comment]
> 之前反馈是禁用quic的影响，新版已经不再屏蔽国内IP的QUIC，你也可以尝试关闭

关闭之后还是存在问题

**Comment by caesarjing** [comment]
同样问题。禁用quic 有明显好转。
