### ISSUE TITLE
请教一个fake-ip模式的原理问题

### ISSUE THREAD

**Issue by shunlongyang** [vernesong/OpenClash#1649]
看了fake-ip和Redir-Host模式的区别，好像大概意思是
Redir-Host模式是会先查询DNS，fake-ip是代理客户端直接分配了一个fake ip。
那么疑问来了，路由器做代理使用fake-ip模式，那手机会不会在本地缓存这个fake ip，
当手机跟路由断开后使用移动网络的时候，直接进行ip请求岂不是会异常？
包括像华为手机可能会有同时使用移动网络配合WIFI加速的情况，是不是会有很多异常ip访问

**Comment by vernesong** [comment]
ttl给的很短，因为是保留地址，客户端不遵守的话，连接不上一般会重新进行连接，对使用会有影响

**Comment by MBRjun** [comment]
1.一般不会缓存很长，但是如果通过特殊方法/强制缓存在Fake-IP池更新后或换流量 一般是ADDRESS_UNREACHABLE，无法访问域名
2.不影响IP，IP直接转发

**Comment by MBRjun** [comment]
> 1.一般不会缓存很长，但是如果通过特殊方法/强制缓存在Fake-IP池更新后或换流量 一般是ADDRESS_UNREACHABLE，无法访问域名
> 2.不影响IP，IP直接转发

3. 移动网络+WiFi加速这种情况容易导致：移动数据不过代理，甚至根本上不了网（域名）
