### ISSUE TITLE
openclash环境下，手机端无法使用Hi-PDA app，SSL报错

### ISSUE THREAD

**Issue by xuesumin** [vernesong/OpenClash#165]
X64 LEAN固件下部署最新Openclash，clash托管模式
手机上打开Hi-pda论坛，无法连接，显示SSL Hanshake错误。
电脑端可以正常打开，科学上网也正常

**Comment by yangliu** [comment]
iOS 13.3 自带 Safari 测试了一下，并没有报SSL错误，你看看是不是openwrt 里还开启了什么广告过滤插件之类的东西。
