### ISSUE TITLE
连接中全是数字ip,手机电脑都不能联网

### ISSUE THREAD

**Issue by JefferyW1** [vernesong/OpenClash#1652]
查看控制面板连接

全是数字ip，规则不管用
手机，电脑，都不好用（国内正常）
油管只能加载页面，不能播放视频

规则是导入的电脑规则，同样的规则，电脑，手机端clash都可以正产使用

内核1.7.1，   客户端版本v0.43.05

**Comment by JefferyW1** [comment]
设置好了，困扰了好几天，今天发完帖子，又重新设置了下，好了，不知道改的哪，反正目前看来是能用了

**Comment by vernesong** [comment]
DNS要给CLASH解析

**Comment by JefferyW1** [comment]
> DNS要给CLASH解析

https://github.com/vernesong/OpenClash/discussions/1420
按照这个方法做的 去广告+clash
N1盒子，旁路由，主路由 ip 192.168.123.1，网关192.168.123.2 开启dhcp
                            N1盒子ip192.168.123.2 ，网关192.168.123.1 关闭dhcp

目前状况是  连接N1盒子的无线，就可以看油管，手机，电脑都行
                   连接主路由的无线，就不行

另外     实验性：绕过中国大陆IP，这个也不能打钩，打钩了，部分国外网站也不行

**Comment by vernesong** [comment]
主路由网关DNS填光猫或者上级地址，主路由可以下发旁路由网关和DNS给下面的客户端
