### ISSUE TITLE
N1做旁路由，手机，电脑可以正常访问油管，但是Google TV就不行

### ISSUE THREAD

**Issue by HellNocturne** [vernesong/OpenClash#1653]
设置的N1做旁路由，能正常使用，手机和电脑都能正常播放油管视频，GoogleTV的油管能正常加载视频信息和预览，但是点进去就直接黑屏。GoogleTV的奈非也能正常使用，就油管有问题。使用PassWall就没有任何问题，搞不明白问题出在哪。

**Comment by vernesong** [comment]
控制面板有没有域名链接信息，dns劫持是否生效了

**Comment by WangJiyuanYo** [comment]
我也遇到了这个问题，TV端浏览器也无法访问海外的网站

**Comment by vernesong** [comment]
我自己家里shield盒子是正常的
