### ISSUE TITLE
openclash的来源ip里出现非局域网ip。被盗用吗？如何实现和防范

### ISSUE THREAD

**Issue by beijiaoff** [vernesong/OpenClash#1656]
我的理解，openclash是为路由器下的设备服务的。我最近却发现有外网ip在蹭我的代理。
只要开启openclash服务，很快就有几个ip进来，很多突发访问，有时也有持续的下载速度。如图红框。
它们是怎么连上的，clash的代理端口并没有暴露在路由器外。
![image](https://user-images.githubusercontent.com/17904873/134684920-9aa39489-df16-4de4-b750-e043dd66bb39.png)

**Comment by davidwu111** [comment]
https://github.com/vernesong/OpenClash/issues/1648

**Comment by beijiaoff** [comment]
> #1648

感谢
