### ISSUE TITLE
游戏、混合模式下UDP流量不通

### ISSUE THREAD

**Issue by MBRjun** [vernesong/OpenClash#1659]
Fake-IP Dev内核 UDP转发关闭 可以正常使用UDP（国内）
换成TUN内核 UDP完全不可使用
请问能不能看看是什么原因，有解吗
![Snipaste_2021-09-25_18-50-27](https://user-images.githubusercontent.com/55020690/134768962-bc9d9ec4-e5fd-41d1-944b-89885315a782.png)

**Comment by vernesong** [comment]
日志没有看到连接信息，判断不了

**Comment by MBRjun** [comment]
> Fake-IP Dev内核 UDP转发关闭 可以正常使用UDP（国内）
> 换成TUN内核 UDP完全不可使用
> 请问能不能看看是什么原因，有解吗
> ![Snipaste_2021-09-25_18-50-27](https://user-images.githubusercontent.com/55020690/134768962-bc9d9ec4-e5fd-41d1-944b-89885315a782.png)



> 日志没有看到连接信息，判断不了

刚试了一下，TUN模式可以，**游戏**和**TUN混合**都不行，日志只有下面的
2021-09-27 03:30:14 level=info msg="[UDP] 192.168.65.2:64625 --> 139.196.15.30:22102 match GeoIP(CN) using 🇨🇳 国内网站[DIRECT]"
2021-09-27 03:30:13 level=info msg="[UDP] 192.168.67.4:28220 --> 39.105.86.43:32100 match GeoIP(CN) using 🇨🇳 国内网站[DIRECT]"

**Comment by abigchopstick** [comment]
我是TUN模式直接不能上网。

**Comment by elonj** [comment]
同样TUN模式直接不能上网
