### ISSUE TITLE
微信，telegram等软件如果不设置代理不能连接。

### ISSUE THREAD

**Issue by maxs98** [vernesong/OpenClash#1660]
微信，telegram等软件如果不设置代理不能连接。手机的微信没有设置代理的地方所以上不去微信。请问怎么配置才可以呢？

**Comment by maxs98** [comment]
fake ip 模式。

**Comment by vernesong** [comment]
https://github.com/vernesong/OpenClash/wiki/%E7%BD%91%E7%BB%9C%E8%BF%9E%E6%8E%A5%E5%BC%82%E5%B8%B8%E6%97%B6%E6%8E%92%E6%9F%A5%E5%8E%9F%E5%9B%A0

**Comment by maxs98** [comment]
问题已经找到了，由于我是旁路由运行openclash，主路由设置了DHCP并分配运营商提供的DNS，所以有所冲突。昨晚已经把DHCP配置在了旁路由openwrt里，问题已经解决。感谢vernesong的帮助了！
