### ISSUE TITLE
Openclash公网不能访问Yacd 控制面板	和 Dashboard 控制面板	

### ISSUE THREAD

**Issue by liaobadadi** [vernesong/OpenClash#1661]
环境：
openclash 客户端版本 v0.43.04-beta
Fake IP  模式，出国深造开启状态
直接安装在主路由上面使用，内网使用正常，最近对Wan口DDNS解析，想离家的时候监控下路由器，外网域名访问Openwrt正常。
外部控制已经写入自己的域名
![image](https://user-images.githubusercontent.com/61466838/134798287-3e7d3897-1258-48ad-abca-0891ea6b619e.png)

就是

- 打开Yacd 控制面板https://op.xxxxx.xyz/luci-static/openclash/ 
 
![image](https://user-images.githubusercontent.com/61466838/134798033-de785e1b-724c-4036-beeb-4e9e66504ac6.png)
尝试 https://op.xxxxx.xyz 密码，123456 都不行
 可以打开页面，但是API BASE URL 和secret 不知道怎么填写。

- 另外： 点击首页启动Dashboard 控制面板，没有反应，不知道怎么进去。

**大佬们，指导下，感谢感谢！**
@

**Comment by MBRjun** [comment]
试试给 外部控制 开端口转发？

**Comment by liaobadadi** [comment]
> 试试给 外部控制 开端口转发？
我Cloudflare 上面用的IPV6 解析，不需要额外端口转发吧，本身也是直连路由器的Wan口
