### ISSUE TITLE
Fake-IP TUN 无法上网 Can not write to tun: write /dev/net/tun: input/output error

### ISSUE THREAD

**Issue by MBRjun** [vernesong/OpenClash#1662]
TUN模式上不了网（混合/游戏没这个问题）具体点就是过几分钟访问全是超时，外网**没有日志**
如果客户端系统开HTTP代理就可以上网，但是内网会出502
![Screenshot_20210926-201356465](https://user-images.githubusercontent.com/55020690/134808510-6fef0ed6-fa8f-44fe-ac53-287342064783.jpg)

**Comment by MBRjun** [comment]
挺玄学，换成Gvisor网络栈暂时不会这样 请问两个有什么区别吗（

**Comment by MBRjun** [comment]
![Snipaste_2021-09-26_21-03-37](https://user-images.githubusercontent.com/55020690/134809361-917ba417-a9b7-4326-9d2f-2e570521ed2c.png)
有幸看到了日志，过几秒钟内网也炸掉了

**Comment by rheatin** [comment]
> ~挺玄学，换成Gvisor网络栈暂时不会这样 请问两个有什么区别吗（~ 收回这句话

好兄弟，解决了吗？我只有在fakeip 混合模式，国内才不卡（下载也不卡），但是这个模式，经常隔段时间就报这个错然后重启clash
