### ISSUE TITLE
OpenClash在启动的时候，一核有难、多核围观

### ISSUE THREAD

**Issue by InsOnYou** [vernesong/OpenClash#1663]
OpenClash运行在Bcm2711，ARM64版。因为添加了一定自定义规则，所以通常要花2分钟才能启动完成。启动的时候四个核心只有一个处于负载状态，CPU占用率也稳定在25%左右。
有办法优化启动脚本的运行速度吗？只要发生网络故障就断2分钟网还是会影响使用。

**Comment by vernesong** [comment]
可以优化，代价就是纯配置文件启动，或者使用provider的形式写配置文件，缩小配置文件的体积

**Comment by InsOnYou** [comment]
> 可以优化，代价就是纯配置文件启动，或者使用provider的形式写配置文件，缩小配置文件的体积

感谢，使用provider以后，现在启动时间在5秒左右。
