### ISSUE TITLE
openclash的大小问题

### ISSUE THREAD

**Issue by imy7** [vernesong/OpenClash#1664]
openclash文件有2.94G,为什么这个程序那么大.

**Comment by love4taylor** [comment]
我猜你说的是这个仓库整体？因为 Git 本身并不是为二进制文件托管而设计，日积月累的 commit 就造成整个仓库 clone 下来会很大。你可以在 clone 的时候添加 `--depth=1` 参数限定深度就行了。

**Comment by imy7** [comment]
谢谢!您的提示!
