### ISSUE TITLE
装完OpenClash网速变慢

### ISSUE THREAD

**Issue by Dragonflyx** [vernesong/OpenClash#167]
你好，有一个疑问：我家电信200M，装完OpenClash之后测速有线只剩100M，无线只剩50M，移除OpenClash变回正常，请问这么大影响正常吗？有没什么可能什么设置导致了这么大的带宽衰减？

**Comment by necoic** [comment]
你的机场是多少M的？

**Comment by necoic** [comment]
> 你好，有一个疑问：我家电信200M，装完OpenClash之后测速有线只剩100M，无线只剩50M，移除OpenClash变回正常，请问这么大影响正常吗？有没什么可能什么设置导致了这么大的带宽衰减？

你的机场是多少M的？

**Comment by Dragonflyx** [comment]
> > 你好，有一个疑问：我家电信200M，装完OpenClash之后测速有线只剩100M，无线只剩50M，移除OpenClash变回正常，请问这么大影响正常吗？有没什么可能什么设置导致了这么大的带宽衰减？
> 
> 你的机场是多少M的？

我选的是不限速的节点，我的疑问主要是，当开着openclash的时候，即使我没有开全局也会影响到国内网的网速吗？

**Comment by maddie** [comment]
如果流量在iptables中没有被RETURN而转发到了clash，clash里面即使是DIRECT规则也同样需要经过clash

你可以看看是不是CPU被吃满了，数据包处理不过来

**Comment by bressanon84** [comment]
> > > 你好，有一个疑问：我家电信200M，装完OpenClash之后测速有线只剩100M，无线只剩50M，移除OpenClash变回正常，请问这么大影响正常吗？有没什么可能什么设置导致了这么大的带宽衰减？
> > 
> > 
> > 你的机场是多少M的？
> 
> 我选的是不限速的节点，我的疑问主要是，当开着openclash的时候，即使我没有开全局也会影响到国内网速吗？

**Comment by bressanon84** [comment]
> > > 你好，有一个疑问：我家电信200M，装完OpenClash之后测速有线只剩100M，无线只剩50M，移除OpenClash变回正常，请问这么大影响正常吗？有没什么可能什么设置导致了这么大的带宽衰减？
> > 
> > 
> > 你的机场是多少M的？
> 
> 我选的是不限速的节点，我的疑问主要是，当开着openclash的时候，即使我没有开全局也会影响到国内网的网速吗？

问题解决了么？，有同样的问题，开着openclash测速只有20Mbps

**Comment by osxdiy** [comment]
我也是这种情，国内流量，没有必要经过CLASH

**Comment by bressanon84** [comment]
> 我也是这种情，国内流量，没有必要经过CLASH

重新安装OpenWrt已经解决了，直连测速可以跑满了。

**Comment by osxdiy** [comment]
测试了在增强模式下正常，在增强TUN模式下网速减了一倍

**Comment by Dragonflyx** [comment]
> 如果流量在iptables中没有被RETURN而转发到了clash，clash里面即使是DIRECT规则也同样需要经过clash
> 
> 你可以看看是不是CPU被吃满了，数据包处理不过来

CPU确实被吃满了，加了个旁路由，好了很多，但还是有20-30M的损失，可能还是跟没有iptable RETURN有关，不过目前还可以接受

**Comment by vernesong** [comment]
tun是会有损失的，内核吞吐还没优化好，普通模式也会吃cpu的性能，因为会走内核转发

**Comment by bluebabes** [comment]
兼容模式可以。速度测试起来比较正常， tun 是直接少一半
