### ISSUE TITLE
iptables-mod-extra

### ISSUE THREAD

**Issue by xiaofat1995** [vernesong/OpenClash#1675]
iptables-mod-extra这个依赖没有找到

**Comment by hcym** [comment]
编译时加的，后期安装没用过，mod模块几乎安装不上

**Comment by xiaofat1995** [comment]
可以出一个，试一试



---Original---
From: ***@***.***&gt;
Date: Sun, Oct 3, 2021 21:27 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [vernesong/OpenClash] iptables-mod-extra (#1675)




 
编译时加的，后期安装没用过，mod模块几乎安装不上
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by vernesong** [comment]
这个一般都是编译的时候加上的
