### ISSUE TITLE
同时启用 mwan3，v6 流量不会进 OpenClash

### ISSUE THREAD

**Issue by LisonFan** [vernesong/OpenClash#1676]
![image](https://user-images.githubusercontent.com/9424775/135760550-2f53d91d-f5ed-4f0e-b773-664a42b4992e.png)

![image](https://user-images.githubusercontent.com/9424775/135760335-3b03939d-ccdb-4478-b337-c729337a7a51.png)

不知道是不是和这条规则有关

**Comment by vernesong** [comment]
流量被mwan3拿走了，暂时还没去研究这个插件

**Comment by LisonFan** [comment]
> 流量被mwan3拿走了，暂时还没去研究这个插件

奇怪，我把 mwan3 给删了，yacd 看还是没有 v6 的相关日志
