### ISSUE TITLE
[建议] 修改 curl 方式为 curl + wget

### ISSUE THREAD

**Issue by chenglu** [vernesong/OpenClash#168]
今天折腾小米路由器 Pro，发现无法更新配置文件。
我排查了一下，发现第三方规则、GEOIP数据库都是无法更新的，所以我看了一下源码是通过 `curl` 获取远程文件并重命名到 `/tmp` 目录下的。

我 ssh 到路由器，试了一下 curl 似乎并不能正确下载，就用 wget 自己组了一个命令，并修改了本地的文件: `/usr/share/openclash/openclash.sh`，把 `curl` 部分逻辑使用 `wget` 替换，发现问题解决。

所以希望提出这个 Issue，看开发团队是否可以在获取远程资源的时候，同步使用 curl 和 wget 的一主一备的方式进行。

谢谢！

**Comment by vernesong** [comment]
因为还原配置调用api需要curl，如果你的curl无法使用的话，还是尽量去更新一下固件。或者暂时退回使用wget的旧版

**Comment by vernesong** [comment]
因为还原配置调用api需要curl，如果你的curl无法使用的话，还是尽量去更新一下固件。或者暂时退回使用wget的旧版

**Comment by chenglu** [comment]
好的，赞。谢谢回复！
