### ISSUE TITLE
建议增加自定义防火墙规则

### ISSUE THREAD

**Issue by paladin4fan** [vernesong/OpenClash#1680]
之前提交的关于ipv6和mwan3的小issue 在更新到0.43.06之后就似乎不需要手动在启动脚本里重启lan和mwan3了
#1622 
#1616 
然后发现了另一个小众的需求
开启IPv6代理之后，虽然有match-set localnetwork6 dst RETURN这条规则，但是从外网访问不了NAS。可以ping通但是无法访问任何web服务
开启绕过中国大陆IPv6之后 大陆IP可以正常访问NAS 但是白名单之外的地址依然不能访问
要自己添加防火墙规则 把NAS的web监听端口作为源端口的流量设置为RETURN
ip6tables -t mangle -I openclash -s {NAS的EUI64地址后缀}/::ffff:ffff:ffff:ffff -p tcp -m multiport --sport {web服务器的监听端口} -j RETURN

**Comment by vernesong** [comment]
路由上端口转发怎么设置的

**Comment by paladin4fan** [comment]
> 路由上端口转发怎么设置的

路由防火墙是在Traffic Rules里把NAS的对应端口放行
Port Forwards需要设置吗 DDNS绑定的是NAS的v6地址 用路由当代理的话要映射的端口是什么

**Comment by vernesong** [comment]
防火墙开放端口的设置截图给我测试

**Comment by paladin4fan** [comment]
![image](https://user-images.githubusercontent.com/34474436/136251827-31209a2a-4af4-4160-8977-791a2d424109.png)

**Comment by paladin4fan** [comment]
> 防火墙开放端口的设置截图给我测试

已经编译了最新版本的ipk试用 发现一个小问题
Traffic Rules设置中如果在同一条规则里同时勾选TCP+UDP 则openclash不会生成此规则对应端口的return

然后就是在读取traffic rules的时候能不能把地址这块也读取一下
虽然几率很小 但是会不会出现要代理访问的端口正好和这里放行的端口号一致的情况
或者 内网其他机器 要走代理的程序刚好随机到同个端口号
