### ISSUE TITLE
DNS解析问题

### ISSUE THREAD

**Issue by Benny-F** [vernesong/OpenClash#1682]
openclash在旁路由上，fake-ip模式，已经设置dns劫持。客户端指定IP地址，网关和dns服务器都指向旁路由，奇怪问题发生了，yacd监控里面可以看到iOS设备和Windows10电脑基于网址的分流，但是所有的安卓设备，手机、平板和电视机看到的都是IP地址。我已经崩溃了！

**Comment by vernesong** [comment]
禁止ipv6了？

**Comment by Benny-F** [comment]
对的，禁了ipv6，是这个原因？

**Comment by Benny-F** [comment]
> 禁止ipv6了？

对的，是这个原因？

**Comment by vernesong** [comment]
到不通设备看看网络的信息

**Comment by vernesong** [comment]
说明设备之间还有解析DNS的设备，尝试重启，另提供的信息太少，要自己排查

**Comment by vernesong** [comment]
你现在要思考的是DNS被哪一步截胡了，是不是自身启用了加密DNS还是其他设备插件干扰了，还是设备自己的缓存导致的

**Comment by Benny-F** [comment]
> 你现在要思考的是DNS被哪一步截胡了，是不是自身启用了加密DNS还是其他设备插件干扰了，还是设备自己的缓存导致的

谢谢，我再去排查一下。

**Comment by Benny-F** [comment]
> 你现在要思考的是DNS被哪一步截胡了，是不是自身启用了加密DNS还是其他设备插件干扰了，还是设备自己的缓存导致的

还没有用软路由的时候，在安卓系统的电视机上安装了clash来分流，当时网络很简单，dhcp获取，然后也出现问题，clash日志也只显示IP地址，后来在clash设置，覆写，DNS里面修改了两项，一个是策略里面强制启用，一个是增强模式里面Fake-IP至域名映射，这样clash日志里面显示网址了，问题解决。这个经验对您帮助我解决目前的问题有帮助吗？我刚刚在openwrt和open clash里面仔仔细细地检查了一遍，没有发现哪里可以截胡DNS解析。

**Comment by vernesong** [comment]
调试日志

**Comment by kingsey** [comment]
> > 主路由DHCP关了，其他不用动，旁路由开DHCP,旁路由自身lan的DNS和网关填主路由
> 
> 我要说完全没用，大佬是不是要和我一样疯了？哈哈哈

哈哈  这两天旁路由刚整起来，一模一样的问题，手头上的IQOO和小米都是。甚至用*#*#4636#*#*去查看wifi config发现手动修改的两个DNS后系统自己还加了一个114.114.114.114，就离谱。

**Comment by matthuo333** [comment]
借此问下，有些连接是在VPS解析，有些是在本地解析，这个依据什么判断？是依据规则没有筛掉就在本地解析？如果这样，IP就会走other， 有出现错误了。Disney+就遇到这样问题，有些影片走正常路由，有些直接IP走了other。试图在自定义加，但每次重启OC后，就又会有新的IP。 还望大神反馈

**Comment by kingsey** [comment]
在一通操作之后也不知道具体哪个操作成功实现安卓设备基于网址分流，期间经历了各种设备重启，甚至openwrt升级版本，本来一直好好的。但是...但是，几天前有一次意外断电，重启之后一切变回原样了，淦！完全想不通是哪里出的问题。

**Comment by magict4** [comment]
有些安卓设备会自动把 8.8.8.8 设置为 primary dns，你自己在wifi那里设置的 dns 只是 secondary dns。只要 8.8.8.8 没有挂，你自己设置的secondary dns 不会起作用，dns 还是会走 8.8.8.8。我的 FireTV 就有这个问题。

我自己的拓扑结构是 FireTV -> 旁路由 -> 主路由(DHCP)。FireTV的 secondary dns 设置成了旁路由的ip地址，旁路由安装了 OpenClash。然后我直接在旁路由把 8.8.8.8 给屏蔽了 ('IP-CIDR,8.8.8.8/32,REJECT,no-resolve')。这下子 FireTv 就会 fallback 到 secondary dns(旁路由)，然后 OpenClash 就能成功劫持所有来自 FireTV的 DNS 请求了。

**Comment by Benny-F** [comment]
非常感谢，我再去检查一下！

magict4 ***@***.***>于2023年6月5日 周一06:42写道：

**Comment by Benny-F** [comment]
> 有些安卓设备会自动把 8.8.8.8 设置为 primary dns，你自己在wifi那里设置的 dns 只是 secondary dns。只要 8.8.8.8 没有挂，你自己设置的secondary dns 不会起作用，dns 还是会走 8.8.8.8。我的 FireTV 就有这个问题。
> 
> 
> 
> 我自己的拓扑结构是 FireTV -> 旁路由 -> 主路由(DHCP)。FireTV的 secondary dns 设置成了旁路由的ip地址，旁路由安装了 OpenClash。然后我直接在旁路由把 8.8.8.8 给屏蔽了 ('IP-CIDR,8.8.8.8/32,REJECT,no-resolve')。这下子 FireTv 就会 fallback 到 secondary dns(旁路由)，然后 OpenClash 就能成功劫持所有来自 FireTV的 DNS 请求了。
> 
> 
> 
> 

我把主副DNS都指向软路由，成功解决，非常感谢！
