### ISSUE TITLE
win11 本地网络检测问题, no internet

### ISSUE THREAD

**Issue by richieliuse** [vernesong/OpenClash#1684]
系统更新至win11后发现本地网络检测会出现"no internet"提示，检查配置文件发现msftconnecttest已经在fake-ip-filter列表里面，不知道怎么解决。

p.s. fake-ip增强模式和混合模式都尝试过。

**Comment by MBRjun** [comment]
墙了...

**Comment by richieliuse** [comment]
> 经测试，将这两个域名走代理可以解决问题 [www.msftconnecttest.com](http://www.msftconnecttest.com) dns.msftncsi.com
> 
> 或者 DOMAIN-SUFFIX,msftconnecttest.com,🚀 节点选择 DOMAIN-SUFFIX,msftncsi.com,🚀 节点选择
> 
> 参考链接： [https://docs.microsoft.com/en-us/troubleshoot/windows-client/networking/internet-explorer-edge-open-connect-corporate-public-network#ncsi-active-probes-and-the-network-status-alert](url)

亲测有效，感谢！

依然没找到原因为什么关闭openclash就可以正常使用，并不是网址本身被墙。

**Comment by aguero119** [comment]
加了这两个走代理还是这样. wifi显示无internet. 当重启openclash后,问题解决. 但是不能每次重启啊.

**Comment by blizzardwj** [comment]
遇到同样的问题，wifi显示无internet，重启openclash后解决，但关闭电脑再开机又会wifi显示无internet

**Comment by vernesong** [comment]
上面两个地址走代理就行了，国内网络环境复杂

**Comment by hprandom** [comment]
我反而是把这两个网址设置成直连，才显示正常。

**Comment by imwx** [comment]
好像这两个网址直连代理都不重要，是要重启openclash才能解决

**Comment by MBRjun** [comment]
> 好像这两个网址直连代理都不重要，是要重启openclash才能解决

❓你这离谱了
你遇到 Fake-IP 缓存问题了？

**Comment by HimriZngz** [comment]
个人经验补充：如果在使用ipv6，则可以额外在[fake-ip-filter]中增加一行 `*.msftncsi.com` ，这样ipv6的网络连通性检测也可以通过了，强迫症满意离开。
