### ISSUE TITLE
[BUG] Script模式下time.now().hour返回值不正常

### ISSUE THREAD

**Issue by OnlyFor** [vernesong/OpenClash#1687]
测了一下openclash也有这个问题，[参考](https://github.com/Kr328/ClashForAndroid/issues/1154)，看了一下日志也是差8小时

**Comment by OnlyFor** [comment]
实测cfa在[2.4.10](https://github.com/Kr328/ClashForAndroid/releases/tag/v2.4.10)以后就修复了，可能不一定是上游的问题。。。。

**Comment by vernesong** [comment]
内核返回的是utc时间，下游没法改

**Comment by OnlyFor** [comment]
cfa修复日志显示是“fix time-zone”，openclash有可能通过调整时区来间接调整hour的取值吗？
