### ISSUE TITLE
WAN口重新连接，导致假死。

### ISSUE THREAD

**Issue by ziying321** [vernesong/OpenClash#1689]
openwrt 内核 5.4 branch
clash 内核版本 v1.7.1-3-g70c8605
客户端版本 v0.43.05-beta
FAKE-IP TUN模式

因为运营商会不定时断开，需要重新拨号，wan只要重新连接（自动或者手动），都会导致openclash假死。
绑定网络接口设置成停用或者wan都无法解决，运行日志显示 “重置 OpenClash 防火墙规则...”，5次以后假死。
需手动重启openclash才能恢复正常。

**Comment by ziying321** [comment]
怀疑和#1666 的问题一致，是否有解决办法？或者检测到wan口IP有变化，自动重启openclash

**Comment by xingmie** [comment]
这个问题，困扰我好久了，运营商经常在2-3点的时候重新wan口连接一次，我就发现自己网断了，然后就只能去关掉clash，等可以上网了，再重新打开clash

**Comment by philly1021** [comment]
> 这个问题，困扰我好久了，运营商经常在2-3点的时候重新wan口连接一次，我就发现自己网断了，然后就只能去关掉clash，等可以上网了，再重新打开clash 最少半年以上了这种状况，每次我每升级的openclash最新的版本

你可以试试我说的方案 绝对好使 或者直接整个定时重启

**Comment by BraveSail** [comment]
> 你可以试试我说的方案 绝对好使 或者直接整个定时重启
是可以了，感谢分享
