### ISSUE TITLE
请问局域网特定ip如何绕过clash

### ISSUE THREAD

**Issue by xufzh** [vernesong/OpenClash#169]
有电脑需要流量不经过clash，iptables看了半天有点绕，请指点下局域网某一ip需要绕过clash的iptables规则该如何写，谢谢

**Comment by shelbysam** [comment]
- SRC-IP-CIDR,<内网ip地址如192.168.1.100>/32,DIRECT

**Comment by xufzh** [comment]
> * SRC-IP-CIDR,<内网ip地址如192.168.1.100>/32,DIRECT

这个我知道的，我理解的是加了这条命令实际流量还是走了clash只不过clash选择了这个ip直连了，不知道理解的对不对。我是想的流量直接跳过clash这样的。。。

**Comment by yangliu** [comment]
只能使用路由表或 iptables 之类的排除。

**Comment by maddie** [comment]
`iptables -t nat -I openclash -s LAN_IP -j RETURN`

**Comment by vernesong** [comment]
redir模式启动后使用以下命令绕过
```
iptables -t nat -I openclash -d 192.168.1.12/32 -j RETURN
```

**Comment by xufzh** [comment]
好的，谢谢了，搭配smartdns把局域网指定ip的53重定向到smartdns的端口后用fake-ip也没问题啦

**Comment by minghaoboy** [comment]
> 好的，谢谢了，搭配smartdns把局域网指定ip的53重定向到smartdns的端口后用fake-ip也没问题啦

请问，具体如何操作

**Comment by wangkun-king** [comment]
#适用于fake-ip增强模式  配合smartdns  6053是smartdns 端口 
iptables -t nat -I PREROUTING -s 192.168.1.12/32  -p udp --dport 53 -j REDIRECT --to-ports 6053
iptables -t nat -I PREROUTING -s 192.168.1.12/32  -p tcp --dport 53 -j REDIRECT --to-ports 6053
iptables -t mangle -A openclash -s 192.168.1.12/32  -j RETURN

**Comment by de-conf** [comment]
为什么不修复这个bug呢?

**Comment by deepfish** [comment]
> > > 好的，谢谢了，搭配smartdns把局域网指定ip的53重定向到smartdns的端口后用fake-ip也没问题啦
> > 
> > 
> > 请问，具体如何操作
> 
> #适用于fake-ip增强模式 配合smartdns 6053是smartdns 端口
> iptables -t nat -I openclash -s 192.168.1.12/32 -j RETURN
> iptables -t nat -I PREROUTING -s 192.168.1.12/32 -p udp --dport 53 -j REDIRECT --to-ports 6053
> iptables -t nat -I PREROUTING -s 192.168.1.12/32 -p tcp --dport 53 -j REDIRECT --to-ports 6053
> #如有选中udp流量转发 需要添加如下项 绕过udp
> iptables -t mangle -A openclash -s 192.168.1.12/32 -j RETURN

你好，我想問問這個是需要安全 smartdns 後，並啟動該服務嗎？我現在 openclash 裝在旁路由（10.0.0.251）上，即使網關設置為主路由（10.0.0.1），但是流程還是走到 openclash 裡面了。openclash 使用 fake-ip 模式。

**Comment by mealied** [comment]
我也需要某些IP绕过openclash，但用了iptables命令后出现
no chain/target/match by that name iptables
请问大佬们这如何处理呢？

**Comment by wangkun-king** [comment]
> > > > 好的，谢谢了，搭配smartdns把局域网指定ip的53重定向到smartdns的端口后用fake-ip也没问题啦
> > > 
> > > 
> > > 请问，具体如何操作
> > 
> > 
> > #适用于fake-ip增强模式 配合smartdns 6053是smartdns 端口
> > iptables -t nat -I openclash -s 192.168.1.12/32 -j RETURN
> > iptables -t nat -I PREROUTING -s 192.168.1.12/32 -p udp --dport 53 -j REDIRECT --to-ports 6053
> > iptables -t nat -I PREROUTING -s 192.168.1.12/32 -p tcp --dport 53 -j REDIRECT --to-ports 6053
> > #如有选中udp流量转发 需要添加如下项 绕过udp
> > iptables -t mangle -A openclash -s 192.168.1.12/32 -j RETURN
> 
> 你好，我想問問這個是需要安全 smartdns 後，並啟動該服務嗎？我現在 openclash 裝在旁路由（10.0.0.251）上，即使網關設置為主路由（10.0.0.1），但是流程還是走到 openclash 裡面了。openclash 使用 fake-ip 模式。

你这情况应该是主路由的路由表的问题 对于你当前设备的ip下一跳是旁路由（10.0.0.251）
ps:主旁路由通过路由表分流 无需在旁路由上通过iptables绕过

**Comment by zxy67** [comment]
R2S作为主路由，想过滤原来的路由器的IP地址走直链，是不是不可以呀，用openclash，规则如下：
- SRC-IP-CIDR,192.168.3.17/32,DIRECT,像这样，因为R2S上没有192.168.3.17这个地址，只有原来路由器的地址

**Comment by wangkun-king** [comment]
> R2S作为主路由，想过滤原来的路由器的IP地址走直链，是不是不可以呀，用openclash，规则如下：
> 
> * SRC-IP-CIDR,192.168.3.17/32,DIRECT,像这样，因为R2S上没有192.168.3.17这个地址，只有原来路由器的地址

SRC-IP-CIDR 只是添加了openclash 软件内的流量规则 流量仍会进入到openrclash软件
如果你只是想接入R2S的设备（原来路由器ip）直连，使用此规则是可以的

**Comment by InsOnYou** [comment]
> redir模式启动后使用以下命令绕过
> 
> ```
> iptables -t nat -I openclash -s 192.168.1.12/32 -j RETURN
> ```

使用tun模式是不是这个方法就失效了？

**Comment by xibaluo** [comment]
> 

我用不用tune模式也是有问题，还是去到openclash了。
和楼主描述的问题一样。
看来无解了

**Comment by xibaluo** [comment]
> 

我加过了，不管是访问目标是IP还是域名，都没有生效，还是走了openclash，会是什么原因？

**Comment by xiaoyichao** [comment]
SwitchyOmega 大家用这个谷歌插件就可以解决，可以设置某些域名不走代理

**Comment by hinak0** [comment]
> redir模式启动后使用以下命令绕过
> 
> ```
> iptables -t nat -I openclash -s 192.168.1.12/32 -j RETURN
> ```

这样默认是只处理tcp流量对吗？还是所有流量？

**Comment by hinak0** [comment]
> > redir模式启动后使用以下命令绕过
> > ```
> > iptables -t nat -I openclash -s 192.168.1.12/32 -j RETURN
> > ```
> 
> 这样默认是只处理tcp流量对吗？还是所有流量？
规则上是全部协议，但是事实上目标网段的设备udp流量依然经过clash，究竟是怎么一回事呢？
![image](https://user-images.githubusercontent.com/96735231/205433654-01a2a42f-91aa-4da7-a6ed-cddc4e40e36b.png)
![image](https://user-images.githubusercontent.com/96735231/205433705-c4c85cc5-7a0b-49bb-be4d-f1ad869015e6.png)

**Comment by hinak0** [comment]
> > > redir模式启动后使用以下命令绕过
> > > ```
> > > iptables -t nat -I openclash -s 192.168.1.12/32 -j RETURN
> > > ```
> > 
> > 
> > 这样默认是只处理tcp流量对吗？还是所有流量？
> > 规则上是全部协议，但是事实上目标网段的设备udp流量依然经过clash，究竟是怎么一回事呢？
> > ![image](https://user-images.githubusercontent.com/96735231/205433654-01a2a42f-91aa-4da7-a6ed-cddc4e40e36b.png)
> > ![image](https://user-images.githubusercontent.com/96735231/205433705-c4c85cc5-7a0b-49bb-be4d-f1ad869015e6.png)

原来在prerouteing就只匹配了tcp,想让udp绕过代理,还需要其他方法

**Comment by garywu520** [comment]
```
#它包括SRC-IP和DIR-IP
IP-CIDR,<IP>/32,DIRECT
```

**Comment by xukecheng** [comment]
请问 nftables 该怎么处理？
