### ISSUE TITLE
redir-host模式下域名解析是本地还是发给代理服务器

### ISSUE THREAD

**Issue by paladin4fan** [vernesong/OpenClash#1695]
RT
Redir模式下是直接本地请求fallback+nameserver直接拿来用吗
还是命中的规则会把域名也丢给代理服务器解析呢

**Comment by vernesong** [comment]
域名命中规则DNS代理给服务器，其他IP类的和没中规则的本地查询再判断

**Comment by paladin4fan** [comment]
> 域名命中规则DNS代理给服务器，其他IP类的和没中规则的本地查询再判断

那就是说命中域名的规则 也会按分流策略服务器解析地址了
fallback组使用dnsforwarder之类的插件转发到代理服务器是不是没有什么意义

**Comment by paladin4fan** [comment]
> > > 域名命中规则DNS代理给服务器，其他IP类的和没中规则的本地查询再判断
> > 
> > 
> > 那就是说命中域名的规则 也会按分流策略服务器解析地址了
> > fallback组使用dnsforwarder之类的插件转发到代理服务器是不是没有什么意义
> 
> clash代理的协议，比如v2ray，ssr，socks都支持带域名转发，所以一个代理请求本质上clash不需要做dns解析，直接把请求转发出去，但是规则中如果有IP规则，那么会把请求中包含的域名用clash指定的dns服务器来解析，然后用解析到的ip比较规则，进行分流，其他的情况都通过match转发出去

也就是说 配置文件里含有ip规则的时候 即使命中了域名规则也是本地先解析一次然后还是把域名带着一起扔出去对吧
