### ISSUE TITLE
关闭openclash后再启动控制面板节点重置

### ISSUE THREAD

**Issue by aguero119** [vernesong/OpenClash#1699]
关闭openclash后再启动控制面板节点重置,请问这是什么问题.

**Comment by angwz** [comment]
我也遇到一样的问题，网上找遍了没有人解答，不过最后还是解决了，可以运行命令清楚OpenClash的缓存来解决
`rm -rf /etc/openclash/.cache /etc/openclash/cache.db /etc/openclash/history`
