### ISSUE TITLE
Google, Youtube 时断时连

### ISSUE THREAD

**Issue by twtjy2008** [vernesong/OpenClash#17]
发现一个问题，Google和Youtube经常出现打不开，ping不通的情况，手机谷歌商店无网络连接，但是不停地刷新一分钟左右之后可以连上Google和Youtube。过一两个小时之后又重复这个现象。当前网络是外网，关闭openclash访问Google和Youtube正常。

已经在Fake-IP黑名单加入了：
google.com
.google.com
youtube.com
.youtube.com

自定义DNS设为： 8.8.8.8

也在config.yml和自定义规则里都加入了
- DOMAIN-SUFFIX,google.com,DIRECT
- DOMAIN-KEYWORD,google,DIRECT
- DOMAIN,google.com,DIRECT
- DOMAIN-SUFFIX,youtube.com,DIRECT
- DOMAIN-KEYWORD,youtube,DIRECT
- DOMAIN,youtube.com,DIRECT

在config.yml还加入了
- GEOIP,US,DIRECT

在这样的设置下，依然出现Google和Youtube经常出现打不开，ping不通的情况，但是不停地刷新一分钟左右之后可以连上Google和Youtube的现象。

请问是我的使用方法不正确吗？如果不正确，应该如何设置才可以解决这个问题？谢谢！

**Comment by vernesong** [comment]
dns查询问题，尝试关闭路由器ipv6的dhcp服务
回国使用第三方回国规则，未匹配到规则的流量直连即可

**Comment by vernesong** [comment]
1. Fake-IP黑名单你不用加这些域名
2. 配置文件的上游dns服务器你尝试一下其他的
3. 测试路由器redir模式下自身访问是否正常

**Comment by vernesong** [comment]
那就有可能是和什么东西冲突了，redir模式下路由器自身的流量不会进过clash。
按照wiki的步骤，检查下你的防火墙规则

**Comment by twtjy2008** [comment]
把主路由重启，time out没有了，已经可以连通
