### ISSUE TITLE
开启Openclash后公网无法访问路由器

### ISSUE THREAD

**Issue by HinataKato** [vernesong/OpenClash#170]
我只能确定IPv6是无法访问的，从v0.36.3-beta开始，使用的内核是v0.18.0
公网访问时会被发链接重置，端口确定是通的试过ip6tables -t filter -F没用
（可能是所有端口都被OpenClash给返回拒绝了，因为我的HTTP代理也在开启后用不了

**Comment by vernesong** [comment]
因为dns劫持，如果配置文件没开ip6的dns解析是不会返回ip6的结果的

**Comment by HinataKato** [comment]
> 因为dns劫持，如果配置文件没开ip6的dns解析是不会返回ip6的结果的

我之前测试的时候就已经开了IPv6类型解析

**Comment by HinataKato** [comment]
> > 因为dns劫持，如果配置文件没开ip6的dns解析是不会返回ip6的结果的
> 
> 我之前测试的时候就已经开了IPv6类型解析

哦对了顺带提一句，仅允许内网关闭也没用

**Comment by vernesong** [comment]
> > 因为dns劫持，如果配置文件没开ip6的dns解析是不会返回ip6的结果的
> 
> 我之前测试的时候就已经开了IPv6类型解析

本地跟外网的ipv6连接正常吗？

**Comment by HinataKato** [comment]
> > > 因为dns劫持，如果配置文件没开ip6的dns解析是不会返回ip6的结果的
> > 
> > 
> > 我之前测试的时候就已经开了IPv6类型解析
> 
> 本地跟外网的ipv6连接正常吗？

IPv6-Test能过，而且我能直接流量打开我路由的luci
