### ISSUE TITLE
有个疑问，今天查日志的时候发现有个域名在fake模式的问题

### ISSUE THREAD

**Issue by lnaxk** [vernesong/OpenClash#1702]
data.mistat.xiaomi.com 这个域名在客户端向openclash请求的时候不会返回假ip，google这类到时正常的，也没有设置拦截这是为什么呢...

**Comment by lnaxk** [comment]
根据我的理解fake模式下，不管拦截不拦截的域名都应该返回假ip嘛。。。有点没懂。。

**Comment by kingsey** [comment]
dns监听为什么是127.0.0.1   感觉好怪哦  …(⊙_⊙;)…
旁路由 fake-ip 增强模式表示这个域名正常

**Comment by lnaxk** [comment]
> 旁路由 fake-ip 增强模式表示这个域名正常

那就神奇了...那是什么情况才会导致不给ip呢
