### ISSUE TITLE
最新Dev内核存在问题

### ISSUE THREAD

**Issue by ghost** [vernesong/OpenClash#1709]
今天把openclash更新到了最新版，Redir-Host（兼容）模式下YouTube视频一直转圈加载不出，但是主页以及评论可以正常加载，更新之前不存在这个问题，于是我把模式改成了Redir-Host（TUN）模式，问题解决了。更新之前任何模式都不存在问题。我看见dev内核有了更新，所以应该几乎可以肯定是最新版dev内核的问题，望排查，感谢。

**Comment by AXBNG** [comment]
看到作者把dev内核退回到之前版本了，所以关闭此反馈
