### ISSUE TITLE
某些网站出现建立连接失败的错误

### ISSUE THREAD

**Issue by shelbysam** [vernesong/OpenClash#171]
最近发现在启动OpenClash以后，某些网站会出现“建立安全连接失败”的报错，比如account.microsoft.com（但是多数网站就没问题，包括www.microsoft.com）。Firefox的具体报错如下：

> 连接到 account.microsoft.com 时发生错误。PR_CONNECT_RESET_ERROR
> 
>     由于不能验证所收到的数据是否可信，无法显示您想要查看的页面。
>     建议向此网站的管理员反馈这个问题。

如果用Chorme的话报错：

> 无法访问此网站连接已重置。
> 请试试以下办法：
> 
> 检查网络连接
> 检查代理服务器和防火墙
> 运行 Windows 网络诊断
> ERR_CONNECTION_RESET

不知应该如何配置解决？谢谢

**Comment by wangweiwei104** [comment]
同样的问题，包括go.microsoft.com

**Comment by yangqiceng** [comment]
同样的问题，包括apps.admob.com

**Comment by yangqiceng** [comment]
找到原因了，规则里被direct了，然后又被DNS污染了。
