### ISSUE TITLE
GEOIP与大陆白名单订阅有什么用？更新后像 SSR+ 一样自动分流吗？还是如何发挥作用？

### ISSUE THREAD

**Issue by andyczr** [vernesong/OpenClash#1716]
GEOIP可以用 - GEOIP,CN,DIRECT 来发挥作用
大陆白名单的ipcidr，需要用什么命令来使他发挥作用？
比如，我更新了Clang-CN这个大陆白名单规则，更新后，它有什么作用？像SSR+一样自动分流吗？

**Comment by mapledot** [comment]
> > 白名单是拿来绕过clash用的
> 
> 谢谢老大的回答，是否可以理解成 开启了 ”实验性：绕过中国大陆IP“后，白名单才生效？ 同时，因为 绕过中国大陆IP 后， Dashboard 控制面板 里面 就看不到连接国内的数据了，但是还是有一些走国内的会出现在里面 并显示Direct，比如今日头条，这是否表示这些出现在这里的还是会经过Clash的核心？（因为一旦经过核心，就会出现卡顿，连接慢。。。。）我要如何手动添加规则，让这些漏掉的也能 绕过中国大陆IP，并且不经过核心，不显示在Dashboard里面？
> 
> 还有，漏网之鱼 一般是选Direct还是Proxy？
> 
> 麻烦老大解答，谢谢！！！

clash对资源消耗本来就大，如果设备性能不行建议放弃clash改用别的客户端，不经过clash的ip需要维护大陆白名单文件，添加ip进去。漏网之鱼是没有匹配上规则的请求如何处理，根据你使用场景选择直连还是走代理。
