### ISSUE TITLE
Dev内核再次更新，很不幸问题依旧

### ISSUE THREAD

**Issue by ghost** [vernesong/OpenClash#1724]
上一次dev内核更新后google打不开，YouTube视频刷不出，之后作者回退了内核版本，我也关闭了议题。
今天内核再次更新，同样的问题再次出现，现在我只好改用tun模式，希望作者重视并修复。

PS：v1.7.1-5-gced9749完全没有问题，只在更新到v1.7.1-24-gebbc960之后才出现问题。

**Comment by dengke80622** [comment]
v1.7.1-24-gebbc960， redir-host导致youtube刷不出广告/视频，无法播放，评论之类的没问题。twitter/FB无法更新。
fake-ip下正常。。
隔壁同样的硬件/固件，v1.7.1-5-gced9749一切正常
