### ISSUE TITLE
能不能只在查询fallback组dns才停用ipv6解析？

### ISSUE THREAD

**Issue by qingxiwa** [vernesong/OpenClash#173]
国内有ipv6私人建博客，这个不用考虑梯子访问。梯子倒是要考虑ipv6能否实现代理的问题。所以能不能只在fallback组dns禁用ipv6解析。

dns查询之后，当判定需要代理时，使用fallback组DNS的查询结果进行通讯，这个时候禁用ipv6 aaaa解析就不影响梯子因各种问题不支持ipv6代理这个问题，也不会影响国内ipv6的访问

**Comment by Love4Taylor** [comment]
这个你得向上游反馈。

**Comment by qingxiwa** [comment]
这个功能是clash内核提供的？所以应该向clash内核反馈？

**Comment by Love4Taylor** [comment]
配置文件里有这么一段。
```
dns:
  ipv6: false
```

**Comment by qingxiwa** [comment]
好的，谢谢
