### ISSUE TITLE
最新dev内核莫名其妙的问题

### ISSUE THREAD

**Issue by AXBNG** [vernesong/OpenClash#1730]
内核从1715升级到17124之后，redir-host模式就打不开谷歌，youtube能打开但是视频加载不出，换成fake-ip模式正常，使用tun内核一切正常。
所有设置都没有任何改变，自定义上游dns为smartdns。
内核退回到1715之后一切恢复正常，莫名其妙。
系统是lean源码编译的，开了smartdns、多拨、去广告和openclash，尝试关闭其他插件问题依旧。
之前反馈过，但没有得到解决方法，只得到一些“我一切正常”“我没问题”的无用回复，本以为只有我出问题，但貌似也有其他人有同样问题，现在只能一头雾水地用tun内核。

**Comment by hgh188** [comment]
同样问题  回退一切正常

**Comment by gaohanping** [comment]
一样的问题，现在用tun模式

**Comment by wyychelsea** [comment]
一样，目前使用tun内核

**Comment by WYC-2020** [comment]
没事升他干嘛，我一直就没升过，这玩意懒得追

**Comment by wumode** [comment]
遇到同样问题，回退到1715内核正常了

**Comment by vernesong** [comment]
![image](https://user-images.githubusercontent.com/42875168/139578577-7d24ad91-e5fb-4382-a640-6853fa38f8a2.png)
确保fallback的DNS无污染

**Comment by javierzhang0504** [comment]
> 内核从1715升级到17124之后，redir-host模式就打不开谷歌，youtube能打开但是视频加载不出，换成fake-ip模式正常，使用tun内核一切正常。
> 
> 所有设置都没有任何改变，自定义上游dns为smartdns。
> 
> 内核退回到1715之后一切恢复正常，莫名其妙。
> 
> 系统是lean源码编译的，开了smartdns、多拨、去广告和openclash，尝试关闭其他插件问题依旧。
> 
> 之前反馈过，但没有得到解决方法，只得到一些“我一切正常”“我没问题”的无用回复，本以为只有我出问题，但貌似也有其他人有同样问题，现在只能一头雾水地用tun内核。

新版本没有fake-ip选项了怎么办？

**Comment by AXBNG** [comment]
> ![image](https://user-images.githubusercontent.com/42875168/139578577-7d24ad91-e5fb-4382-a640-6853fa38f8a2.png) 确保fallback的DNS无污染

谢谢回复，fake-ip模式也有个问题。https://bbs.360.cn/thread-16005307-1-1.html，这里面的下载链接在fake-ip模式下会出现网络错误

**Comment by AXBNG** [comment]
> > 内核从1715升级到17124之后，redir-host模式就打不开谷歌，youtube能打开但是视频加载不出，换成fake-ip模式正常，使用tun内核一切正常。
> > 所有设置都没有任何改变，自定义上游dns为smartdns。
> > 内核退回到1715之后一切恢复正常，莫名其妙。
> > 系统是lean源码编译的，开了smartdns、多拨、去广告和openclash，尝试关闭其他插件问题依旧。
> > 之前反馈过，但没有得到解决方法，只得到一些“我一切正常”“我没问题”的无用回复，本以为只有我出问题，但貌似也有其他人有同样问题，现在只能一头雾水地用tun内核。
> 
> 新版本没有fake-ip选项了怎么办？

有的，在 全局设置-模式设置 页面最下，“切换页面到fake-ip模式”

**Comment by javierzhang0504** [comment]
> > > 内核从1715升级到17124之后，redir-host模式就打不开谷歌，youtube能打开但是视频加载不出，换成fake-ip模式正常，使用tun内核一切正常。
> 
> > > 所有设置都没有任何改变，自定义上游dns为smartdns。
> 
> > > 内核退回到1715之后一切恢复正常，莫名其妙。
> 
> > > 系统是lean源码编译的，开了smartdns、多拨、去广告和openclash，尝试关闭其他插件问题依旧。
> 
> > > 之前反馈过，但没有得到解决方法，只得到一些“我一切正常”“我没问题”的无用回复，本以为只有我出问题，但貌似也有其他人有同样问题，现在只能一头雾水地用tun内核。
> 
> > 
> 
> > 新版本没有fake-ip选项了怎么办？
> 
> 
> 
> 有的，在 全局设置-模式设置 页面最下，“切换页面到fake-ip模式”

看到了感谢！但是更诡异的事情发生了。
我有两台软路由，都是官方openwrt
一台19.06一台21.02
openclash都是默认初始设置
19.06那台升级到最新内核毫无问题，一切正常。
21.02那台升级到最新内核无法访问google服务。

**Comment by AXBNG** [comment]
> > > > 内核从1715升级到17124之后，redir-host模式就打不开谷歌，youtube能打开但是视频加载不出，换成fake-ip模式正常，使用tun内核一切正常。
> > 
> > 
> > > > 所有设置都没有任何改变，自定义上游dns为smartdns。
> > 
> > 
> > > > 内核退回到1715之后一切恢复正常，莫名其妙。
> > 
> > 
> > > > 系统是lean源码编译的，开了smartdns、多拨、去广告和openclash，尝试关闭其他插件问题依旧。
> > 
> > 
> > > > 之前反馈过，但没有得到解决方法，只得到一些“我一切正常”“我没问题”的无用回复，本以为只有我出问题，但貌似也有其他人有同样问题，现在只能一头雾水地用tun内核。
> > 
> > 
> > > 
> > 
> > 
> > > 新版本没有fake-ip选项了怎么办？
> > 
> > 
> > 有的，在 全局设置-模式设置 页面最下，“切换页面到fake-ip模式”
> 
> 看到了感谢！但是更诡异的事情发生了。 我有两台软路由，都是官方openwrt 一台19.06一台21.02 openclash都是默认初始设置 19.06那台升级到最新内核毫无问题，一切正常。 21.02那台升级到最新内核无法访问google服务。

现在来看确实不同版本有区别，因为也有很多人升级内核之后依然正常，也有部分人和我一样新内核无法访问谷歌

**Comment by vernesong** [comment]
目前只有dev内核更新了，用dev内核的redir模式会这样
