### ISSUE TITLE
请问各位大神，如何能将OPENCLASH的规则放一边，让节点自动更新。

### ISSUE THREAD

**Issue by skwsun** [vernesong/OpenClash#1732]
我有一些网站需要走单独的固定的节点，如果让OPENCLASH自动更新链接的话每次都要重新改软路由。
另外我为了保证随时能用，有3个机场，好像默认只能更新一个或者只有一个，我该如何把3个机场捏一起更新呢？
但是如果自己写YAML的话那些机场又没事总换节点，过两天就死一大片，很难受。
有没有大神可以手把手的帮忙说一下如何将节点整合起来自动让它们自己更新，然后规则走我的。或者叠加我的。

**Comment by z-x-f** [comment]
proxy-providers和rule-providers看看，应该是你要的吧。

**Comment by skwsun** [comment]
> 代理提供者和规则提供者看看，应该是你要的吧。

我其实不是很懂，也不知道怎么搞。。。之前凭感觉弄都弄断了。。大佬能告诉一下么

**Comment by vernesong** [comment]
开订阅转换多个订阅用 | 连接

**Comment by InsOnYou** [comment]
服务器与策略组管理里导入节点和策略组，勾上保留配置。

**Comment by skwsun** [comment]
> 服务器与策略组管理里导入节点和策略组，勾上保留配置。

策略组好像不包括规则吧。。。。我就想保留策略组和规则，之前误打误撞保存过，好像规则会跑

**Comment by skwsun** [comment]
> 服务器与策略组管理里导入节点和策略组，勾上保留配置。



> 开订阅转换多个订阅用 | 连接

那个我试过，有时候不好使，我也不知道为什么，就是某家机场的节点都丢失，更新不出来，但是单独更新它又没问题。

**Comment by skwsun** [comment]
> 开订阅转换多个订阅用 | 连接

刚我又试了一下，直接就失败，提示
错误: 无法获取DNS部分的监听端口设置, OpenClash 使用原始配置文件启动失败
错误: 无法获取DNS部分的运行模式设置, OpenClash 使用原始配置文件启动失败
错误: 无法获取General部分的转发端口设置, OpenClash 使用原始配置文件启动失败

**Comment by aguero119** [comment]
那是你自己搞不懂rule provider
