### ISSUE TITLE
各位大佬。请教OPENCLASH如何能将多个机场的节点合并到一个里面用啊

### ISSUE THREAD

**Issue by skwsun** [vernesong/OpenClash#1733]
我有3个机场，用订阅转换合并成一个之后clash可以读取成功，所有节点合并，但是OPENCLASH就不行，提示

错误: 无法获取DNS部分的监听端口设置, OpenClash 使用原始配置文件启动失败
错误: 无法获取DNS部分的运行模式设置, OpenClash 使用原始配置文件启动失败
错误: 无法获取General部分的转发端口设置, OpenClash 使用原始配置文件启动失败

同时看配置文件管理页面，也没有节点，直接就是规则。

请教大神这种该如何处理啊。

**Comment by MBRjun** [comment]
提供內核日誌

**Comment by chinnsenn** [comment]
是不是转换订阅的时候，客户端选错了？
