### ISSUE TITLE
功能建议：希望对能在Yacd控制面板中实现节点拖拽，已方便管理

### ISSUE THREAD

**Issue by Kisoul** [vernesong/OpenClash#1736]
现在油管、奈菲等平台对节点的控制越来约严重，机场基本上都是通过更换IP来解决，所以规则中需要经常对节点进行管理，是不是能通过在Yacd控制面板中拖拽的实现对节点的管理？

**Comment by mapledot** [comment]
你需要去yacd面板作者那反馈需求

**Comment by Dark-Existed** [comment]
去 YACD 提 issue 并且这要看 clash 有没有相关 api 
你要去找的应该是这两个地方
也就是说提需求的话 你找错地方了 把 issue 关了吧
