### ISSUE TITLE
目前版本09，dev内核版本为1.7.1.24

### ISSUE THREAD

**Issue by Faramitas** [vernesong/OpenClash#1739]
模式为redirhost，google无法打开，youtube打开正常的，但是视频加载不出来，yacd规则规则匹配也没问题，但是使用fakeip模式就可以正常使用，但是我平时需要玩游戏，fakeip模式下， 某些手游和端游会连不上。

**Comment by Faramitas** [comment]
另外我自用的还没有更新至09版本，仍为08版本，dev版本也是1.7.1.5版本，尚未更新，一切正常

**Comment by Faramitas** [comment]
经测试，是dev内核问题。。。。。使用redirhost另外几个模式使用正常

**Comment by Faramitas** [comment]
V大跟dev内核的大佬提醒提醒呗

**Comment by 68cs** [comment]
> 经测试，是dev内核问题。。。。。使用redirhost另外几个模式使用正常

确实是这样，折腾了一通......

**Comment by asnon** [comment]
我也是。。还以为我设置问题。。各种固件全部弄了一遍。。最后发现是内核的问题。。现在用fake IP好像对流量的选择也好很多

**Comment by asnon** [comment]
> 模式为redirhost，google无法打开，youtube打开正常的，但是视频加载不出来，yacd规则规则匹配也没问题，但是使用fakeip模式就可以正常使用，但是我平时需要玩游戏，fakeip模式下， 某些手游和端游会连不上。
看把这几个ip直接放规则里直连试试，直接配置文件里改

**Comment by vernesong** [comment]
![image](https://user-images.githubusercontent.com/42875168/140597871-8d8888b6-2365-4f1d-85cc-5a6785f05819.png)
确保fallback的DNS无污染
