### ISSUE TITLE
可以打开youtube页面，但无法播放视频，一直转圈圈

### ISSUE THREAD

**Issue by iamjimmycheng** [vernesong/OpenClash#1740]
openclash客户端版本：v0.43.09
可以打开youtube页面，但无法播放视频，一直转圈圈
尝试过还原默认配置，问题依旧；
redir-host和fake-ip都试过，问题依旧；
更换多个不同的机场订阅，上述问题依旧；
同一订阅在openclash中无法正常使用，但在手机和win10客户端能够正常使用；

这是最新版openclash客户端的问题么？

**Comment by yang05130** [comment]
更新了最新的内核就这样了，

**Comment by yang05130** [comment]
不知道 咋样回滚回去

**Comment by iamjimmycheng** [comment]
我是小白，没办法自己编译，不懂得重装openclash，只能找个旧版本重刷整个openwrt了

**Comment by cmyehj** [comment]
v0.43.08 就有这个问题了，也不修改。我们自己解决不了，强制更新内核，果断放弃OPENCLASH

**Comment by LitCcc** [comment]
https://github.com/vernesong/OpenClash/tree/14a0fa362e0b143761b8f464e7d20e49b58c3cc2/core-lateset/dev

有问题的可以暂时切换回旧版dev内核

**Comment by iamjimmycheng** [comment]
楼上能不能指导一下，如何更换dev内核呢？

**Comment by LitCcc** [comment]
> 
> 
> 楼上能不能指导一下，如何更换dev内核呢？

下载对应结构的内核，在openclash-全局设置-版本更新找到自己dev内核的路径，ssh到路由器替换即可

**Comment by WYC-2020** [comment]
我是直接到clash内核的作者哪里clone过来然后修改了那个不传域名的情况，给你们一个拿去用吧，我测试完全没问题
[clash-linux-amd64-v1.8.0-1-g7b93763.gz](https://github.com/vernesong/OpenClash/files/7511178/clash-linux-amd64-v1.8.0-1-g7b93763.gz)

**Comment by AXBNG** [comment]
> 我是直接到clash内核的作者哪里clone过来然后修改了那个不传域名的情况，给你们一个拿去用吧，我测试完全没问题 [clash-linux-amd64-v1.8.0-1-g7b93763.gz](https://github.com/vernesong/OpenClash/files/7511178/clash-linux-amd64-v1.8.0-1-g7b93763.gz)

大佬指点一下如何修改可好，我的是armv8也想改一下，不然也是同样问题

**Comment by WYC-2020** [comment]
@AXBNG
[clash-linux-armv8.tar.gz](https://github.com/vernesong/OpenClash/files/7524690/clash-linux-armv8.tar.gz)
去官方的内核源码出修改一处commit pure

**Comment by WYC-2020** [comment]
@AXBNG 实在不知道的去我git 自己看，我刚开放了，一直在调试，现在是吧 tun 和非tun代码集成了，每次提交就会自动发布dev ，打分支的话会发布mster

**Comment by AXBNG** [comment]
> @AXBNG 实在不知道的去我git 自己看，我刚开放了，一直在调试，现在是吧 tun 和非tun代码集成了，每次提交就会自动发布dev ，打分支的话会发布mster

万分感谢！！！

**Comment by Ailmie** [comment]
很奇怪，我用Wmware虚拟机桥接了物理网卡，clash用的版本也一样，虚拟机的youtube播放正常，google正常，本机一直无法播放，google也有问题

**Comment by supen8012** [comment]
> https://github.com/vernesong/OpenClash/tree/14a0fa362e0b143761b8f464e7d20e49b58c3cc2/core-lateset/dev
> 
> 有问题的可以暂时切换回旧版dev内核

用回您这个链接的内核，不转圈了，能播放了！折腾好几天了，谢谢

**Comment by WYC-2020** [comment]
> > https://github.com/vernesong/OpenClash/tree/14a0fa362e0b143761b8f464e7d20e49b58c3cc2/core-lateset/dev
> > 有问题的可以暂时切换回旧版dev内核
> 
> 用回您这个链接的内核，不转圈了，能播放了！折腾好几天了，谢谢

确实老内核更加靠谱

**Comment by supen8012** [comment]
> > > https://github.com/vernesong/OpenClash/tree/14a0fa362e0b143761b8f464e7d20e49b58c3cc2/core-lateset/dev
> > > 有问题的可以暂时切换回旧版dev内核
> > 
> > 
> > 用回您这个链接的内核，不转圈了，能播放了！折腾好几天了，谢谢
> 
> 确实老内核更加靠谱

而且好像cpu占用也小一些，我目前的使用情况看，用最新版的，基本在50度左右，这个旧的大约42-46度

**Comment by loohalh** [comment]
换了旧版本内核，几个小时后又出现这样的问题了

**Comment by huang122124** [comment]
我mac的，Montery系统，梯子是Clash X 1.65.1，在Sarifi播放youtube没问题，在Chrome一直转圈圈，不知道是Chrome内核问题还是梯子问题

**Comment by huang122124** [comment]
> 我mac的，Montery系统，梯子是Clash X 1.65.1，在Sarifi播放youtube没问题，在Chrome一直转圈圈，不知道是Chrome内核问题还是梯子问题

刚把chrome和Clash X更新到最新，问题解决！

**Comment by DamienMM** [comment]
这个和内核没关系吧，禁用DNS相关选项用ad的DNS配置就这样了，如果改回去就可以了。原因应该出在DNS上，但是不知道具体原因是什么。
