### ISSUE TITLE
控制台端口无法设置

### ISSUE THREAD

**Issue by yusiwen** [vernesong/OpenClash#1743]
![微信截图_20211107170201](https://user-images.githubusercontent.com/3704932/140638837-2b286b65-462a-49bb-852b-3b7a7a511f29.png)

如图，我在配置文件里设置了`external-controller: 0.0.0.0:9090`， 但最终的配置文件里却是：`external-controller: '0.0.0.0:'`， 导致控制台没有监听任何端口，就无法连上Dashboard

请问各位大佬，这个问题怎么解决呀？谢谢啦!

Update:

我手工改了`/etc/openclash/config.yaml` , 把`external-controller: 0.0.0.0:` 改成 `external-controller: 0.0.0.0:9090`， 还是不行，控制台端口依然未设置， 如图：
![image](https://user-images.githubusercontent.com/3704932/140641212-7f431812-4b17-41cc-9acf-0afd5a5ae647.png)

不知道怎么办了。有其他的全局开关禁用了控制台了么？

**Comment by vernesong** [comment]
全局设置页面修改这个参数
