### ISSUE TITLE
github 无法访问

### ISSUE THREAD

**Issue by moekyo** [vernesong/OpenClash#1745]
![image](https://user-images.githubusercontent.com/12700243/140640836-4d3878c1-69ea-4413-bf05-1b0b5546e40b.png)
具体设置如下
![image](https://user-images.githubusercontent.com/12700243/140640890-92d01049-e0fe-4b44-887f-811182ffe23a.png)，如果电脑本地再打开 PC 版 Clash，github是正常访问的

**Comment by Ahtaler** [comment]
我也是这样，可能是内核吧

**Comment by vernesong** [comment]
dev内核的redir模式改成了本地查询IP后传给代理，请确保fallback的DNS无污染

**Comment by WYC-2020** [comment]
确保DNS无污染，应该怎么个确保法，什么操作步骤大佬说下呗

**Comment by moekyo** [comment]
> dev内核的redir模式改成了本地查询IP后传给代理，请确保fallback的DNS无污染

可以说说具体的操作吗，我在界面没找到**dev内核的redir模式**的相关设置项

**Comment by vernesong** [comment]
```
  - https://dns.cloudflare.com/dns-query
  - "[2001:da8::666]:53"
  - https://public.dns.iij.jp/dns-query
  - https://jp.tiar.app/dns-query
  - https://jp.tiarap.org/dns-query
  - tls://dot.tiar.app
```
试试这几个

**Comment by WYC-2020** [comment]
意思是说现在默认的dns被污染了才导致不能正确解析youtube和github？

**Comment by WYC-2020** [comment]
@vernesong  我理解代理是，以前发起域名请求的时候，会把域名发往我们自定义上游的所有dns进行解析，获取到ip，然后判断该ip是否需要代理，如果需要代理就走代理模式，不是就直连，现在这个clash到底改了一个什么逻辑，导致这样的问题，大佬能解释一下吗？如果是dns污染了，但是换成老版本的有可以了，dns这块没动，搞不明白

**Comment by vernesong** [comment]
新版内核现在不传域名给服务器解析

**Comment by WYC-2020** [comment]
@vernesong 不传域名？是直接传ip吧，那从域名解析到ip 这块是内核自己做了吗？他所使用的dns就是软件上面设置的fallback组了吧？如果是这样那以前的老内核，其实真正解析出github地址是nameserver这组吧，因为fallback 一直对于github是处于污染状态的，我这样理解对吧？

**Comment by vernesong** [comment]
以前命中规则的直接给代理解析

**Comment by WYC-2020** [comment]
@vernesong  ok。那现在redir域名规则还有用没

**Comment by moekyo** [comment]
目前我的DSN的设置是这样的，是需要怎么修改吗？
![image](https://user-images.githubusercontent.com/12700243/140871739-80d8bc08-eb15-4ad2-a5df-dcec944d815f.png)

**Comment by vernesong** [comment]
fallback组要改一下

**Comment by moekyo** [comment]
> fallback组要改一下

可以具体说说怎么改吗

**Comment by palemoky** [comment]
> ```
>   - https://dns.cloudflare.com/dns-query
>   - "[2001:da8::666]:53"
>   - https://public.dns.iij.jp/dns-query
>   - https://jp.tiar.app/dns-query
>   - https://jp.tiarap.org/dns-query
>   - tls://dot.tiar.app
> ```
> 
> 试试这几个

你好，我添加了这些配置，但仍有 DNS 报错，Google 和 YouTube 都无法打开

错误日志
```
2021-11-10 11:38:56 level=debug msg="[DNS] response msg empty: &dns.Msg{MsgHdr:dns.MsgHdr{Id:0x6977, Response:true, Opcode:0, Authoritative:false, Truncated:false, RecursionDesired:true, RecursionAvailable:true, Zero:false, AuthenticatedData:false, CheckingDisabled:false, Rcode:0}, Compress:false, Question:[]dns.Question{dns.Question{Name:\"71.153.32.111.in-addr.arpa.\", Qtype:0xc, Qclass:0x1}}, Answer:[]dns.RR(nil), Ns:[]dns.RR(nil), Extra:[]dns.RR(nil)}"
```
fallback 配置
![image](https://user-images.githubusercontent.com/21208635/141046074-19938534-a24b-4eb2-bee2-ef1366fc0951.png)

**Comment by vernesong** [comment]
国内那几个DOH应该是污染的用不了，不要加进去fallback

**Comment by iErics** [comment]
把国内 dns 仅留 114.114.114.114,
再留两条国外的
http://dns.google/dns-query  https
http://dns.cloudflare.com/dns-query
这两条国外的 dns 就够用了
应用配置后,断开网络再重新连接应该就好了
我是通过这种方法搞定的。

**Comment by wyjhebei** [comment]
我的也是这样，后来无意中打开电脑的host文件，发现有很多github相关联的地址，把这些地址都删除了。github就可以打开了。
