### ISSUE TITLE
openclash 配置完v2ray ws tls方式 出现404

### ISSUE THREAD

**Issue by DosLee** [vernesong/OpenClash#175]

**Comment by DosLee** [comment]
日志: 
# www.xxx.com是v2ray域名地址
2020-02-27 11:17:22[warning] dial Others error: Dial www.xxx.com error: 404 Not Found
2020-02-27 11:17:22[warning] dial Others error: Dial www.xxx.com error: 404 Not Found
2020-02-27 11:17:22[warning] dial Others error: Dial www.xxx.com error: 404 Not Found
2020-02-27 11:17:22[warning] dial Others error: Dial www.xxx.com error: 404 Not Found

配置文件:
redir-port: 7892
port: 7890
socks-port: 7891
mode: Rule
log-level: info
external-controller: 192.168.1.1:9090
secret: "123456"
allow-lan: true
bind-address: "192.168.1.1"
external-ui: "/usr/share/openclash/dashboard"
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  listen: 0.0.0.0:7874
  nameserver:
  - 114.114.114.114
  fallback:
  - tls://8.8.8.8:853
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4
#===================== OpenClash-General-Settings =====================#
Proxy:
- { name: "v2ray", type: vmess, server: www.xxx.com, port: 443, uuid: e29c22fa-7a32-4384-8516-ec7a9cafffff, alterId: 16, cipher: auto, network: ws, ws-path: /path, tls: true }

国内网站可以, 国外网站访问不成功.

**Comment by vernesong** [comment]
域名无法解析，更换

**Comment by DosLee** [comment]
@vernesong 域名是正常, 使用ssr plus解析正常.

**Comment by vernesong** [comment]
规则时判定动other组了，你可以加到规则了，让域名直连
