### ISSUE TITLE
nameserver setting for multiple Network interface?

### ISSUE THREAD

**Issue by malikshi** [vernesong/OpenClash#1753]
i just checked fake ip mode TUN and found this setting.
```sh
  nameserver:
  - 10.0.8.1
  - dhcp://"eth1"
  - https://1.1.1.1/dns-query
  - tls://8.8.8.8:853
  fallback:
  - https://cloudflare-dns.com/dns-query
  - tls://dns.google:853
  default-nameserver:
  - 10.0.8.1
  ```
where is menu for setting this area? i didn't found those menu in interface openclash
```sh
  - 10.0.8.1
  - dhcp://"eth1"

  default-nameserver:
  - 10.0.8.1
```

and is it possible to set-up multiple `nameserver` and `default-nameserver` from different network interfaces since i had more than 2 WAN connection

**Comment by vernesong** [comment]
![image](https://user-images.githubusercontent.com/42875168/141645841-32470638-f726-4f6d-a45b-325265ab1927.png)
 * Automatically identify the interface, multiple network interface would be added if exist(no tested yet)
 * Automatically add addresses in ip format from nameserver and fallback to default-nameserver

**Comment by malikshi** [comment]
Currently i have 2 WAN  interface(eth1 and wwan(wlan0)) with good connection, but only eth1 that detected. I checked 4 those options.

**Comment by vernesong** [comment]
* if find the dhcp interface, added only when proto is dhcp, and also try to add the gateway address(10.0.8.1)
* if not find the dhcp interface, would try to add the DNS address from wan interface which identify by system

 interface get by codes [here](https://github.com/vernesong/OpenClash/blob/c2b1a27f5fb83bd7165fa6784529fcf027319b1b/luci-app-openclash/root/usr/share/openclash/openclash_get_network.lua#L98)
