### ISSUE TITLE
错误：Ruby依赖异常，无法校验配置文件，请确认ruby依赖工作正常后重试！

### ISSUE THREAD

**Issue by ak48shine** [vernesong/OpenClash#1755]
错误：Ruby依赖异常，无法校验配置文件，请确认ruby依赖工作正常后重试！  请问这个怎么搞啊.....

**Comment by ccinoo** [comment]
升级后我也遇到这个问题，@ak48shine 你解决了吗？

**Comment by chainkite** [comment]
ruby -v看看是否正常
我的情况是：No such file or directory (needed by /usr/lib/ruby/ruby3.0-bin)
有个依赖前面没装成功：opkg install --force-overwrite libruby

@ak48shine @ccinoo

**Comment by Yumerakk** [comment]
更新路由器中已安装的带有ruby前缀的所有软件包，例如ruby-bigdecimal，ruby-date，ruby-dbm等等，使他们的版本号一致。之后重启路由器
@ak48shine @ccinoo
