### ISSUE TITLE
连接Ipv6地址的Shadowsocks服务器

### ISSUE THREAD

**Issue by yuedai** [vernesong/OpenClash#1756]
请问openclash支持连接ipv6地址的shadowsocks服务器么？有些vps走ipv6线路的延时比较低。我在openwrt 21.02 + openclash 0.43beta上试了一下，好像不支持Dns的AAAA记录.

各位大神能帮忙确认一下，是我配置文件填错了，还是openclash目前还不支持?

**Comment by hcym** [comment]
最近几个版本有点事，只有一个小版本支持好，再等等吧

**Comment by vernesong** [comment]
支持，打开DNS解析和v6代理

**Comment by yuedai** [comment]
多谢。搞定了。

跑个题问另一个问题，我可以根据DNS记录类型来决定走哪个服务器么？比如我有ss-1，ss-2两台代理。如果一个地址可以解析出ipv6 ip，我就把它扔给ss-1, 否则就扔给ss-2.

**Comment by vernesong** [comment]
不行
