### ISSUE TITLE
更新的配置文件【****】节点部分校验失败

### ISSUE THREAD

**Issue by jackadam1981** [vernesong/OpenClash#1759]
2021-11-16 00:27:17 错误：更新的配置文件【****】节点部分校验失败...
2021-11-16 00:27:07 错误：更新的配置文件【****】节点部分校验失败，尝试不使用代理下载配置文件...

有理由相信是由于一个通知类的节点校验失败了。
如：更新时间：*****
它不在排除无效节点中，尝试手动排除节点，仍然校验失败。

不知道校验逻辑是什么，是先排除节点再校验还是先校验，再排除。
校验规则也不知道。

求帮助。

**Comment by vernesong** [comment]
意思就是配置文件里面没有找到节点配置内容，内容是是空的或者下载的不是完整的配置文件

**Comment by jackadam1981** [comment]
V2rayN 使用相同的订阅是正常的。

**Comment by vernesong** [comment]
不是clash的订阅就打开订阅转换

**Comment by jackadam1981** [comment]
![image](https://user-images.githubusercontent.com/28656671/141824674-fd255bde-f6bd-4214-8acc-438e01ccf9a2.png)
开过了的。
![image](https://user-images.githubusercontent.com/28656671/141824972-6e9c2985-f539-4ee4-9f97-bf179225dd08.png)
怀疑是这个节点校验失败。

**Comment by vernesong** [comment]
不校验节点内容，只会看下载的文件里面有没有节点部分

**Comment by jackadam1981** [comment]
我把地址发你邮箱了，你试试看，看哪里出问题了。

**Comment by vernesong** [comment]
> 我把地址发你邮箱了，你试试看，看哪里出问题了。

哪来的邮箱

**Comment by jackadam1981** [comment]
git log

**Comment by jackadam1981** [comment]
罢了，贴这里吧
dm1lc3M6Ly9leUoySWpvZ0lqSWlMQ0FpY0hNaU9pQWlYSFUyTm1ZMFhIVTJOV0l3WEhVMFpUaGxPakV4TFRFNElESXdPakF3SUMxaWVTQkNkVXhwYm1zdWVIbDZMU0JjZFRSbFpUVmNkVFJsTUdKY2RUZ3lPREpjZFRjd1lqbGNkVFJsTUdSY2RUaGlZVEZjZFRaa05ERmNkVGt4WTJZaUxDQWlZV1JrSWpvZ0lseDFOR1kzWmx4MU56VXlPRngxTlRJMFpGeDFPR0ppTUZ4MU5XWTVOMXgxTmpabU5GeDFOalZpTUZ4MU9HSmhNbHgxT1RZd05TSXNJQ0p3YjNKMElqb2dJakFpTENBaWFXUWlPaUFpTm1FelltTmpNRGd0T1dNM055MDBZekF5TFRnME5HSXROR0UyT1RSak5HWXlabVZoSWl3Z0ltRnBaQ0k2SUNJd0lpd2dJbTVsZENJNklDSjBZM0FpTENBaWRIbHdaU0k2SUNKdWIyNWxJaXdnSW1odmMzUWlPaUFpSWl3Z0luQmhkR2dpT2lBaUlpd2dJblJzY3lJNklDSWlmUT09CnNzOi8vWVdWekxUSTFOaTFuWTIwNlVFTnVia2cyVTFGVGJtWnZVekkzQDQ2LjI5LjIxOC42OjgwOTEjZ2l0aHViLmNvbS9mcmVlZnElMjAtJTIwJUU2JThDJUFBJUU1JUE4JTgxJTIwJTIwMQp2bWVzczovL2V5SjJJam9nSWpJaUxDQWljSE1pT2lBaVoybDBhSFZpTG1OdmJTOW1jbVZsWm5FZ0xTQmNkVGRtT0dWY2RUVTJabVJEYkc5MVpFWnNZWEpsWEhVMU1UWmpYSFUxTTJZNFEwUk9YSFU0TWpneVhIVTNNR0k1SURJaUxDQWlZV1JrSWpvZ0lqRXdOQzR4T0M0Mk5DNHdJaXdnSW5CdmNuUWlPaUFpTkRReklpd2dJbWxrSWpvZ0lqRTVNemM1WkRKbUxUaGpOR1l0TkdSbVppMDRZMlptTFdObVpHTTFPRFprTkRsa015SXNJQ0poYVdRaU9pQWlNQ0lzSUNKdVpYUWlPaUFpZDNNaUxDQWlkSGx3WlNJNklDSnViMjVsSWl3Z0ltaHZjM1FpT2lBaWRYVjFkWE56TVRFdWJHbDFkMlZwTURFdWRHc2lMQ0FpY0dGMGFDSTZJQ0l2YkdsMWQyVnBJaXdnSW5Sc2N5STZJQ0owYkhNaUxDQWljMjVwSWpvZ0lpSjkKc3M6Ly9ZV1Z6TFRJMU5pMW5ZMjA2YmpoM05GTjBibUpXUkRsa2JWaFpialJCYW5RNE4wVkJAMTA3LjE1MC45NC4xMjozMTU3MiNnaXRodWIuY29tL2ZyZWVmcSUyMC0lMjAlRTYlOTYlQjAlRTglQTUlQkYlRTUlODUlQjBDYWNoZWROZXQlRTYlOTUlQjAlRTYlOEQlQUUlRTQlQjglQUQlRTUlQkYlODMlMjAzCnZtZXNzOi8vZXlKaFpHUWlPaUFpZGpZdWMzTnljM1ZpTG1OdmJTSXNJQ0poYVdRaU9pQXdMQ0FpYUc5emRDSTZJQ0lpTENBaWFXUWlPaUFpWlRVMFlUUTRNR010TnpkbE15MDBNV05oTFRobU9HSXRNVGRtWm1JMU1HUmlaREE0SWl3Z0ltNWxkQ0k2SUNKM2N5SXNJQ0p3WVhSb0lqb2dJaTl6YzNKemRXSWlMQ0FpY0c5eWRDSTZJQ0l4TmpnaUxDQWljSE1pT2lBaVoybDBhSFZpTG1OdmJTOW1jbVZsWm5FZ0xTQmNkVFV5WVRCY2RUWXlabVpjZFRVNU1qY2dJRFFpTENBaUlqb2dJbEpsYkdGNVh5MWNkV1E0TTJOY2RXUmtaVGhjZFdRNE0yTmNkV1JrWlRaRFFWODFNVGtpTENBaWRHeHpJam9nSW5Sc2N5SXNJQ0oySWpvZ0lqSWlmUT09CnZtZXNzOi8vZXlKMklqb2dJaklpTENBaWNITWlPaUFpWjJsMGFIVmlMbU52YlM5bWNtVmxabkVnTFNCY2RUZG1PR1ZjZFRVMlptUkRiRzkxWkVac1lYSmxYSFUxTVRaalhIVTFNMlk0UTBST1hIVTRNamd5WEhVM01HSTVJRFVpTENBaVlXUmtJam9nSW5ZNExuTnpjbk4xWWk1amIyMGlMQ0FpY0c5eWRDSTZJQ0k0TkRReklpd2dJbWxrSWpvZ0ltVTFOR0UwT0RCakxUYzNaVE10TkRGallTMDRaamhpTFRFM1ptWmlOVEJrWW1Rd09DSXNJQ0poYVdRaU9pQWlNQ0lzSUNKelkza2lPaUFpWVhWMGJ5SXNJQ0p1WlhRaU9pQWlkM01pTENBaWRIbHdaU0k2SUNKdWIyNWxJaXdnSW1odmMzUWlPaUFpSWl3Z0luQmhkR2dpT2lBaUwzTnpjbk4xWWlJc0lDSjBiSE1pT2lBaWRHeHpJaXdnSW5OdWFTSTZJQ0lpZlE9PQp2bWVzczovL2V5SmhaR1FpT2lBaU1UQXpMakV6T0M0M05TNHlNelVpTENBaVlXbGtJam9nSWpFaUxDQWlhRzl6ZENJNklDSXhNRE11TVRNNExqYzFMakl6TlNJc0lDSnBaQ0k2SUNJNFkyTmpNekExTWkwME9UUXhMVFEzWlRRdFlqZzFaaTFoTmpkbFlUY3haVE5tWlRZaUxDQWlibVYwSWpvZ0luZHpJaXdnSW5CaGRHZ2lPaUFpTDJOc2FXVnVkR0Z5WldFaUxDQWljRzl5ZENJNklDSTBORE1pTENBaWNITWlPaUFpWjJsMGFIVmlMbU52YlM5bWNtVmxabkVnTFNCY2RUZG1PR1ZjZFRVMlptUmNkVFV5WVRCY2RUVXlNamxjZFRjNU9HWmNkVFZqTTJOY2RUUmxPV0ZjZFRWa1pHVmNkVGhrTXpsY2RUVXlNamxjZFRnME9UbElkWEp5YVdOaGJtVWdSV3hsWTNSeWFXTmNkVFV4Tm1OY2RUVXpaamdnTmlJc0lDSjBiSE1pT2lBaWRHeHpJaXdnSW5SNWNHVWlPaUFpSWl3Z0luWWlPaUFpTWlKOQp2bWVzczovL2V5SmhaR1FpT2lBaWRqRXVjM055YzNWaUxtTnZiU0lzSUNKaGFXUWlPaUF3TENBaWFHOXpkQ0k2SUNJaUxDQWlhV1FpT2lBaU9USmhPVFZsTm1RdFkyWTRPUzAwTW1WbExUZ3hNVEF0TmpabVlXSTJPRGN4WlRKbUlpd2dJbTVsZENJNklDSjNjeUlzSUNKd1lYUm9Jam9nSWk5emMzSnpkV0lpTENBaWNHOXlkQ0k2SUNJeE5qZ2lMQ0FpY0hNaU9pQWlaMmwwYUhWaUxtTnZiUzltY21WbFpuRWdMU0JjZFRSbVl6UmNkVGRtTlRkY2RUWTFZV1pjZFRVeE5HSmNkVFl5WXpsY2RUWTFZV1pjZFRoaVptRmNkVFJsT1dGY2RUVmpNVFJjZFRZMVlXWmNkVFV4TkdKSExVTnZjbVVnVEdGaUlEY2lMQ0FpSWpvZ0lsSmxiR0Y1WHkxY2RXUTRNMk5jZFdSa1pqZGNkV1E0TTJOY2RXUmtabUZTVlY4MU1UVWlMQ0FpZEd4eklqb2dJblJzY3lJc0lDSjJJam9nSWpJaWZRPT0Kdm1lc3M6Ly9leUpoWkdRaU9pQWlkall1YzNOeWMzVmlMbU52YlNJc0lDSmhhV1FpT2lBd0xDQWlhRzl6ZENJNklDSWlMQ0FpYVdRaU9pQWlPVEpoT1RWbE5tUXRZMlk0T1MwME1tVmxMVGd4TVRBdE5qWm1ZV0kyT0RjeFpUSm1JaXdnSW01bGRDSTZJQ0ozY3lJc0lDSndZWFJvSWpvZ0lpOXpjM0p6ZFdJaUxDQWljRzl5ZENJNklDSXhOamdpTENBaWNITWlPaUFpWjJsMGFIVmlMbU52YlM5bWNtVmxabkVnTFNCY2RUVXlZVEJjZFRZeVptWmNkVFU1TWpjZ0lEZ2lMQ0FpSWpvZ0lsSmxiR0Y1WHkxY2RXUTRNMk5jZFdSa1pUaGNkV1E0TTJOY2RXUmtaVFpEUVY4MU1UQWlMQ0FpZEd4eklqb2dJblJzY3lJc0lDSjJJam9nSWpJaWZRPT0Kdm1lc3M6Ly9leUpoWkdRaU9pQWlkakV1YzNOeWMzVmlMbU52YlNJc0lDSmhhV1FpT2lBd0xDQWlhRzl6ZENJNklDSWlMQ0FpYVdRaU9pQWlaVFUwWVRRNE1HTXROemRsTXkwME1XTmhMVGhtT0dJdE1UZG1abUkxTUdSaVpEQTRJaXdnSW01bGRDSTZJQ0ozY3lJc0lDSndZWFJvSWpvZ0lpOXpjM0p6ZFdJaUxDQWljRzl5ZENJNklDSXhOamdpTENBaWNITWlPaUFpWjJsMGFIVmlMbU52YlM5bWNtVmxabkVnTFNCY2RUUm1ZelJjZFRkbU5UZGNkVFkxWVdaY2RUVXhOR0pjZFRZeVl6bGNkVFkxWVdaY2RUaGlabUZjZFRSbE9XRmNkVFZqTVRSY2RUWTFZV1pjZFRVeE5HSkhMVU52Y21VZ1RHRmlJRGtpTENBaUlqb2dJbEpsYkdGNVh5MWNkV1E0TTJOY2RXUmtaamRjZFdRNE0yTmNkV1JrWm1GU1ZWODFNVElpTENBaWRHeHpJam9nSW5Sc2N5SXNJQ0oySWpvZ0lqSWlmUT09CnZtZXNzOi8vZXlKb2IzTjBJam9nSWlJc0lDSndZWFJvSWpvZ0lpOW5aWFIzWldGMGFHVnlJaXdnSW5CdmNuUWlPaUFpTkRReklpd2dJblJzY3lJNklDSjBiSE1pTENBaWNITWlPaUFpWjJsMGFIVmlMbU52YlM5bWNtVmxabkVnTFNCY2RUZG1PR1ZjZFRVMlptUkRiRzkxWkVac1lYSmxYSFUxTVRaalhIVTFNMlk0UTBST1hIVTRNamd5WEhVM01HSTVJREV3SWl3Z0ltbGtJam9nSWpBeFltSmpOR00wTFRRNE1qUXRNVEZsWXkxaE16UXpMVEF3TURBeE56QXlNakF3T0NJc0lDSmhaR1FpT2lBaVlYQnBMbk56Wm5KbFpTNXlkU0lzSUNKMklqb2dJaklpTENBaVlXbGtJam9nSWpZMElpd2dJbTVsZENJNklDSjNjeUlzSUNKMGVYQmxJam9nSW01dmJtVWlmUT09Cg==

**Comment by vernesong** [comment]
说了订阅不会检查节点内容，只会检查下载的文件有没有proxies节点部分

**Comment by jackadam1981** [comment]
可能是订阅转换的版本太老了，我自己建了一个订阅转换，可以正常用了。

**Comment by zongolia** [comment]
我遇到和你一样的问题，但是我不确定我的解决办法对你有没有用。我在更新内核的时候选择的是developer而非master
![image](https://user-images.githubusercontent.com/49625421/204024325-a2b950f0-c8e3-4f05-9285-4ca91019329d.png)
希望对你有用

**Comment by fuyong2gh** [comment]
> 我遇到和你一样的问题，但是我不确定我的解决办法对你有没有用。我在更新内核的时候选择的是developer而非master ![image](https://user-images.githubusercontent.com/49625421/204024325-a2b950f0-c8e3-4f05-9285-4ca91019329d.png) 希望对你有用

R4S 骷髅头固件，用developer，可以解决问题！！！ 感谢感谢！！

**Comment by hatbhtbh** [comment]
我在J4125软路由插件openclash中，选择自动配置文件订阅总是不成功，手动应用配置就没有问题，附上截图求解答：
![X)95TKGMK2BE)0`E)2PK) T](https://user-images.githubusercontent.com/93958708/216217513-a46d5738-456f-4c0c-8ca4-084be89cca2d.png)
![HG%HJ_3IKD4 6FUX(H314ZU](https://user-images.githubusercontent.com/93958708/216217539-57926c07-37b9-4c42-850f-a78eac6fdab4.png)
![47 YAL3FQHEKKKU$GCE{ 1](https://user-images.githubusercontent.com/93958708/216217547-9e7ba21f-9bfd-4f1c-8d1e-085bed5deb0d.png)
![~WL9OQ(U6U@%CE$ PRC2TJS](https://user-images.githubusercontent.com/93958708/216217560-4cfff702-86bc-4bf6-8057-ee7cfd774db6.png)
![Z`VA~ NZ5 @053{O3F1HJW](https://user-images.githubusercontent.com/93958708/216217567-f78b0a34-0cbb-444d-858a-45a059eff07c.png)

**Comment by hatbhtbh** [comment]
![Z`VA~ NZ5 @053{O3F1HJW](https://user-images.githubusercontent.com/93958708/216217871-86ae211f-4193-4772-8aad-7c4644f174a5.png)

**Comment by hatbhtbh** [comment]
![~WL9OQ(U6U@%CE$ PRC2TJS](https://user-images.githubusercontent.com/93958708/216217938-39b44eee-bb71-40f4-adf9-20c3fdae18ae.png)

**Comment by hatbhtbh** [comment]
![V F6CL_Q~%5U)F@OELLF{$B](https://user-images.githubusercontent.com/93958708/216217958-0f99b7bc-f896-4d32-ad03-88b4dd3340f1.png)

**Comment by hatbhtbh** [comment]
![HG%HJ_3IKD4 6FUX(H314ZU](https://user-images.githubusercontent.com/93958708/216217981-684384e6-40b5-4d37-a4d7-f3165533ffd2.png)
