### ISSUE TITLE
配置文件中含有emoji启动失败

### ISSUE THREAD

**Issue by iLay1678** [vernesong/OpenClash#176]
time="2020-02-27T18:38:48+08:00" level=fatal msg="Parse config error: yaml: line 71: did not find expected key"
然后这一行代理组名称开头是emoji
删掉就没事

**Comment by vernesong** [comment]
具体是什么字符？

**Comment by iLay1678** [comment]
https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/config/ACL4SSR_Onlie.ini
这里面这种
