### ISSUE TITLE
fakeip tun混合模式，国内游戏tcp断连

### ISSUE THREAD

**Issue by Bruce-panruosong** [vernesong/OpenClash#1760]
![image](https://user-images.githubusercontent.com/52652627/142131924-fb0afe3f-e750-4254-bd65-58d75eae8223.png)
![image](https://user-images.githubusercontent.com/52652627/142131936-9076f016-83e8-4447-9150-f903cdac7f26.png)
![image](https://user-images.githubusercontent.com/52652627/142131979-87ef5d72-b61a-442a-bf6b-0efa91716d2b.png)
![image](https://user-images.githubusercontent.com/52652627/142131989-44c82b9e-4d66-4948-b0d3-ccc73d19590f.png)
![image](https://user-images.githubusercontent.com/52652627/142132021-e1a614f9-e0bc-42ac-bca8-b4dd60b446f7.png)
![image](https://user-images.githubusercontent.com/52652627/142132141-ea22f0bd-0f7c-49e3-8c96-7c37e33d2944.png)

已经反复排查，无dns错误问题。 Redir-host模式下一切正常。
但是更新最新dev内核之后，openclash面板看到的所有连接都是ip地址，规则里的域名分流失效。

**Comment by WYC-2020** [comment]
不要更新内核

**Comment by WYC-2020** [comment]
新版内核已经不传域名了，要么用修改版要么回归老的那个版本每个职业

**Comment by Bruce-panruosong** [comment]
> 新版内核已经不传域名了，要么用修改版要么回归老的那个版本内核

嗯，这已经找到老版准备替换了，谢谢

**Comment by Bruce-panruosong** [comment]
> 新版内核已经不传域名了，要么用修改版要么回归老的那个版本内核

那如果都只传ip，那所有基于域名的分流规则是不是都失效了。。。

**Comment by WYC-2020** [comment]
我的理解是的，最新版完全依赖上游dns的可靠性了，我自己修改了最新版本，你可以去拿来用

**Comment by vernesong** [comment]
目前只有dev内核的redir模式受影响，tun内核还没更新，你这个问题还要多观察一下

**Comment by Bruce-panruosong** [comment]
> 目前只有dev内核的redir模式受影响，tun内核还没更新，你这个问题还要多观察一下

以后redir会和cfw一样分两种模式么，一种远程解析，一种不远程解析。

**Comment by vernesong** [comment]
新内核redir模式就是本地解析，fakeip/http/socks不受影响

**Comment by CrazyMouse** [comment]
> 新版内核已经不传域名了，要么用修改版要么回归老的那个版本内核

新版本这么改的理由是啥，能帮忙解释一下么？

**Comment by WYC-2020** [comment]
@CrazyMouse  这个你去clash内核提交的地方看下吧，我记得有人问过，算了我给你复制过来吧
![image](https://user-images.githubusercontent.com/34025388/143218495-8b3b3952-3bdd-4b13-a9c7-34adb0958699.png)

**Comment by CrazyMouse** [comment]
> @CrazyMouse 这个你去clash内核提交的地方看下吧，我记得有人问过，算了我给你复制过来吧 ![image](https://user-images.githubusercontent.com/34025388/143218495-8b3b3952-3bdd-4b13-a9c7-34adb0958699.png)

感谢

**Comment by WYC-2020** [comment]
基本上我都是自己改回来用 @CrazyMouse

**Comment by CrazyMouse** [comment]
> 基本上我都是自己改回来用 @CrazyMouse

我不想折腾了，想把我之前编译的一个比较稳定的版本一直用着就好，另外请教一下，内核这么改了，我们有啥好办法避免这个坑么？除了你说的这种改回去

**Comment by WYC-2020** [comment]
这个没办法勒，毕竟v大更新内核也是拉取d大内核来编译更新的，他也不清楚会出什么问题，我这边目前的方法是，我自己同步d大内核并且编译打包，保证实时更新，然后v大的我修改了更新地址，从我这里更新，这样即保证了最新，也避免了那个问题

**Comment by WYC-2020** [comment]
@CrazyMouse

**Comment by CrazyMouse** [comment]
> 这个没办法勒，毕竟v大更新内核也是拉取d大内核来编译更新的，他也不清楚会出什么问题，我这边目前的方法是，我自己同步d大内核并且编译打包，保证实时更新，然后v大的我修改了更新地址，从我这里更新，这样即保证了最新，也避免了那个问题

我想我可能是刚才没有描述清楚。我是说，如果跟随大佬的更新逻辑，不支持传域名了，那么，我们有什么办法来保证redir使用的模式不会被dns污染？毕竟fake-ip有好多坑，好多app不识别

**Comment by WYC-2020** [comment]
这个v大不是说过了么，更新上游为无污染的

**Comment by Bruce-panruosong** [comment]
> > 这个没办法勒，毕竟v大更新内核也是拉取d大内核来编译更新的，他也不清楚会出什么问题，我这边目前的方法是，我自己同步d大内核并且编译打包，保证实时更新，然后v大的我修改了更新地址，从我这里更新，这样即保证了最新，也避免了那个问题
> 
> 我想我可能是刚才没有描述清楚。我是说，如果跟随大佬的更新逻辑，不支持传域名了，那么，我们有什么办法来保证redir使用的模式不会被dns污染？毕竟fake-ip有好多坑，好多app不识别

四个8 绝对不污染

**Comment by CrazyMouse** [comment]
> 

3Q

**Comment by CrazyMouse** [comment]
> > > 这个没办法勒，毕竟v大更新内核也是拉取d大内核来编译更新的，他也不清楚会出什么问题，我这边目前的方法是，我自己同步d大内核并且编译打包，保证实时更新，然后v大的我修改了更新地址，从我这里更新，这样即保证了最新，也避免了那个问题
> > 
> > 
> > 我想我可能是刚才没有描述清楚。我是说，如果跟随大佬的更新逻辑，不支持传域名了，那么，我们有什么办法来保证redir使用的模式不会被dns污染？毕竟fake-ip有好多坑，好多app不识别
> 
> 四个8 绝对不污染

3Q
