### ISSUE TITLE
luci界面特别卡是什么情况

### ISSUE THREAD

**Issue by VergilGao** [vernesong/OpenClash#1764]
一旦开启clash，luci界面就变得非常卡，要等好久才能全部加载完，虽然不经常访问，但是之前有时候要调试些参数的时候就让人非常的难受。

**Comment by vernesong** [comment]
负载正常吗

**Comment by VergilGao** [comment]
> 负载正常吗

负载一切正常，路由器型号是J4205，内存2G，用openwrt官方源码编译的，21.02分支。

刚才我重新云编译了一份，晚上回家再测试一下。

我说的这个问题应该是从我用这个库开始就一直有，但是我一直没在意这个问题，前段时间因为letsencrypt根证书过期，整个路由系统都出了一些小问题，我在挨个调试的时候，发现openclash这里luci界面的卡顿太影响了……于是我就换成vssr继续用了。
这两天觉得vssr还是不适合我，又换回来，所以才来这里反馈一下，看看是只有我有这个问题还是普遍现象。

**Comment by vernesong** [comment]
浏览器F12 网络标签， 时间项，看看耗时
