### ISSUE TITLE
v0.43.09-beta版本的自定义hosts无效

### ISSUE THREAD

**Issue by shookgao** [vernesong/OpenClash#1766]
模式选择redir，在自定义hosts里面设置了一条记录：`'time.android.com': 203.107.6.88`，发现未生效，去配置文件管理里面查看openclash修改后用于启动的配置文件里面也未有 hosts 这个条目，应该是个BUG，希望修复。

**Comment by WYC-2020** [comment]
试下回归老版本内核看下

**Comment by vernesong** [comment]
我这边是正常的，如果加不上日志会有提示
