### ISSUE TITLE
代理成功运行了，节点速率也好的，就是不能看外网

### ISSUE THREAD

**Issue by db992062117** [vernesong/OpenClash#1769]
代理成功运行了，节点速率也好的，就![QQ截图20211120225254](https://user-images.githubusercontent.com/70459120/142731396-66e85232-901d-4a5d-b952-917d7f3326c2.png)
![QQ截图20211120225306](https://user-images.githubusercontent.com/70459120/142731400-fca36734-9a8c-4200-9518-e760e3c94440.png)
是不能看外网，国内的是好的

**Comment by spirytuslove** [comment]
我也这个问题  你最后怎么解决的啊

**Comment by db992062117** [comment]
我还没解决。。。

**Comment by spirytuslove** [comment]
我的好了
