### ISSUE TITLE
无法访问 epicgames

### ISSUE THREAD

**Issue by SpaceEggs** [vernesong/OpenClash#178]
openclash 版本：0.36.6-beta
Redir-host 模式

## 问题描述

其他网站打开都是正常的，但是打开 [epicgames](https://www.epicgames.com/) 会提示重定向次数过多。

关了 openclash，在电脑上运行相同节点，是可以访问的。所以应该不是节点问题。

用手机也一样的报错，应该不是设备问题。

这个问题什么办法能解决吗？谢谢！

**Comment by vernesong** [comment]
我看了一下，规则判定直连的情况无法访问，是dns解析的问题，建议你添加自定义规则让他走代理

**Comment by SpaceEggs** [comment]
试了一下开全局的确是可以打开的。
非常感谢！

**Comment by SpaceEggs** [comment]
刚尝试了一下把电脑的 dns 改为 8.8.8.8 这种公网 dns 就可以使用了。
但是使用 openwrt 地址作为 dns 却不行。
Clash 依然是正常运行的
看了 wiki 好像没有对应的说明。想问一下终端的 dns 该怎么设置。

**Comment by vernesong** [comment]
dns用openwrt 地址就行了，访问不了是clash的上游dns返回了一个国内不可访问的地址导致
