### ISSUE TITLE
想给作者买杯咖啡，可惜买不了

### ISSUE THREAD

**Issue by lloyd18** [vernesong/OpenClash#1782]
为遵守国际法规，这笔交易已被拒绝。

![Snipaste_2021-11-27_17-08-17](https://user-images.githubusercontent.com/10294460/143675318-007951b7-e645-4c61-8608-e552e70c7eae.png)

**Comment by vernesong** [comment]
受限了吗难道

**Comment by pillanangel** [comment]
> 受限了吗难道

刚我也试着Paypal，确实如图一样，无法完成。

**Comment by dongzhenye** [comment]
> 受限了吗难道

希望提供新的支付方式，比心

**Comment by Karmylr** [comment]
啊这
