### ISSUE TITLE
希望添加新功能

### ISSUE THREAD

**Issue by Karmylr** [vernesong/OpenClash#1784]
![image](https://user-images.githubusercontent.com/69903376/143724410-6e41b9ef-5873-4ea3-9df3-ec6abd640fcc.png)
希望在图上的界面添加一个使用自己的ini文件的功能！真的很需要！

**Comment by Karmylr** [comment]
就是订阅链接转换用的ini。我有自己的分流需求，就自己写了ini（在线订阅链接转换用的配置文件）文件

**Comment by RainThings** [comment]
如果你有需要的话用自己搭一个subconverter后端就好了，没必要的。
最新版有自定义模板地址，ini传到路由www文件夹里直接填http://127.0.0.1/你的配置文件名.ini （127.0.0.1不行的话请用你访问luci的ip）

**Comment by Karmylr** [comment]
> 如果你有需要的话用自己搭一个subconverter后端就好了，没必要的。 最新版有自定义模板地址，ini传到路由www文件夹里直接填[http://127.0.0.1/你的配置文件名.ini](http://127.0.0.1/%E4%BD%A0%E7%9A%84%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E5%90%8D.ini) （127.0.0.1不行的话请用你访问luci的ip）

这样就需要一个linux来运行subconverter。我希望一个openwrt完事。因为我的机器性能并不好。用esxi搭建会很吃力

**Comment by vernesong** [comment]
上传到自己仓库引用链接不就行了

**Comment by WYC-2020** [comment]
openwrt还不是可以搭建subconverter,我就是op自己搭建的，然后openclash自己用本地的

**Comment by Karmylr** [comment]
> 上传到自己仓库引用链接不就行了

需要能自定义ini的功能

**Comment by RainThings** [comment]
你要的应该就是那个模板了吧，其实这个就是，下拉找到自定义。
![Screenshot_2021-11-28-21-17-10-464_com android chrome](https://user-images.githubusercontent.com/61218971/143769511-c14a8906-adb8-4f23-9e3a-8c4ee35bebe2.jpg)
![Screenshot_2021-11-28-21-17-43-052_com android chrome](https://user-images.githubusercontent.com/61218971/143769506-31147b6a-528c-4b82-a7d4-5180e5ca9dce.jpg)

**Comment by XinSSS** [comment]
和模板没关系，他的意思是固件内一条龙服务，不用再访问外部的在线订阅转换服务，固件内提供subconvert调用

**Comment by Karmylr** [comment]
> 上传到自己仓库引用链接不就行了

试过了。但是没用上ini
