### ISSUE TITLE
v0.44.01-beta更新的时候报错

### ISSUE THREAD

**Issue by doushixiaoshisa** [vernesong/OpenClash#1785]
v0.44.01-beta更新的时候报错，* pkg_run_script: package "luci-app-openclash" preinst script returned status 1.
-ash: 0.db: not found
* preinst_configure: Aborting installation of luci-app-openclash.
-ash: 0.db: not found
* opkg_install_cmd: Cannot install package luci-app-openclash.
-ash: 0.db: not found
root@OpenWrt:/tmp# -ash: 0.db: not found
-ash: -ash:: not found

**Comment by vernesong** [comment]
把/etc/openclash的文件删干净试试
