### ISSUE TITLE
OpenWrt启动后不会自动启动OpenClash

### ISSUE THREAD

**Issue by MeowRay** [vernesong/OpenClash#1787]
内核版本 | v1.7.1-24-gebbc960

OpenWrt启动后不会自动启动OpenClash，并且局域网所有设备 dns解析超时，造成无法上网，手动启动openclash后恢复正常

**Comment by vernesong** [comment]
是脚本没有启动还是什么原因，日志显示什么

**Comment by MeowRay** [comment]
> 是脚本没有启动还是什么原因，日志显示什么

openclash的日志内容为空

openwrt启动项是开的状态

**Comment by vernesong** [comment]
看看系统日志吧，不行就换固件
