### ISSUE TITLE
redir-host 和fake-ip 模式问题反馈

### ISSUE THREAD

**Issue by CrazyMouse** [vernesong/OpenClash#1789]
openclash version: v0.44.01-beta
clah_core version:  v1.8.0-7-g075d8ed
这两个都升级到最新版本了，路由器版本是 ：OpenWrt R21.11.11 / LuCI Master (git-21.329.83689-00cb491)
问题是如果我开redir-host 模式，那么youtube只显示播放列表、文字以及视频快照，视频无法播放；而twitter则是只显示文字，图片都没办法加载。
如果用fake-ip模式，youtube和twitter是好了，但是家里孩子在线上火花思维的就进不了课堂了，试了一下公司内部用的聊天工具也没有办法建立语音通话了，微信倒是还正常。我的机场是订阅的blinkload的，没有做任何的模版转换，不知道有没有哪位大佬知道这问题咋解决，万分感谢。

**Comment by vernesong** [comment]
DNS，fallback用无污染的，插件还原默认配置可以看到几个新预置的

**Comment by CrazyMouse** [comment]
> DNS，fallback用无污染的，插件还原默认配置可以看到几个新预置的

我试试，感谢大佬

**Comment by CrazyMouse** [comment]
> 

重置完，貌似正常了，感谢大佬，顺道请教一下，有没有地方有说明，整个clash或者openclash的工作原理和流程？有的话麻烦推荐一下，非常感谢

**Comment by Shsy** [comment]
> > 
> 
> 说明完了，貌似正常了，感谢大佬，顺道请教一下，有没有地方有，整个clashopenclash的工作原理和流程？有事麻烦推荐一下，非常感谢

你好  是 redir-host 模式正常了吗
我和你的情况类似 更新了最新内核 redir-host 模式会有问题，Fake-ip模式正常， 退回旧版本的内核 redir-host 模式就正常了。

**Comment by leahakira** [comment]
> > > 
> > 
> > 
> > 说明完了，貌似正常了，感谢大佬，顺道请教一下，有没有地方有，整个clashopenclash的工作原理和流程？有事麻烦推荐一下，非常感谢
> 
> 你好 是 redir-host 模式正常了吗 我和你的情况类似 更新了最新内核 redir-host 模式会有问题，Fake-ip模式正常， 退回旧版本的内核 redir-host 模式就正常了。

redir-host确实重置后能用了

**Comment by NathanDai** [comment]
> > > > 
> > > 
> > > 
> > > 说明完了，貌似正常了，感谢大佬，顺道请教一下，有没有地方有，整个clashopenclash的工作原理和流程？有事麻烦推荐一下，非常感谢
> > 
> > 
> > 你好 是 redir-host 模式正常了吗 我和你的情况类似 更新了最新内核 redir-host 模式会有问题，Fake-ip模式正常， 退回旧版本的内核 redir-host 模式就正常了。
> 
> redir-host确实重置后能用了

redir-host重置后修改dns后就不能用了

**Comment by WYC-2020** [comment]
这话题早就讨论过了

**Comment by CrazyMouse** [comment]
> > > 
> > 
> > 
> > 说明完了，貌似正常了，感谢大佬，顺道请教一下，有没有地方有，整个clashopenclash的工作原理和流程？有事麻烦推荐一下，非常感谢
> 
> 你好 是 redir-host 模式正常了吗 我和你的情况类似 更新了最新内核 redir-host 模式会有问题，Fake-ip模式正常， 退回旧版本的内核 redir-host 模式就正常了。

回复出厂设置就好了，然后配置重新订阅一下，完事

**Comment by CrazyMouse** [comment]
> 这话题早就讨论过了

是的，之前是讨论过，我现在回想可能是问题出在配置文件来来回回的修改可能哪些地方出了问题，然后彻底的回复出厂设置就好了，本质上就是fallback的dns不要被污染就解决问题了

**Comment by Shsy** [comment]
> > > > 
> > > 
> > > 
> > > 说明完了，貌似正常了，感谢大佬，顺道请教一下，有没有地方有，整个clashopenclash的工作原理和流程？有事麻烦推荐一下，非常感谢
> > 
> > 
> > 你好 是 redir-host 模式正常了吗 我和你的情况类似 更新了最新内核 redir-host 模式会有问题，Fake-ip模式正常， 退回旧版本的内核 redir-host 模式就正常了。
> 
> 回复出厂设置就好了，然后配置重新订阅一下，完事

确实 恢复出厂设置好了。不过 扶墙总是不稳定。还是恢复到旧内核了

**Comment by CrazyMouse** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 说明完了，貌似正常了，感谢大佬，顺道请教一下，有没有地方有，整个clashopenclash的工作原理和流程？有事麻烦推荐一下，非常感谢
> > > 
> > > 
> > > 你好 是 redir-host 模式正常了吗 我和你的情况类似 更新了最新内核 redir-host 模式会有问题，Fake-ip模式正常， 退回旧版本的内核 redir-host 模式就正常了。
> > 
> > 
> > 回复出厂设置就好了，然后配置重新订阅一下，完事
> 
> 确实 恢复出厂设置好了。不过 扶墙总是不稳定。还是恢复到旧内核了

嗯，我最近也遇到这个问题，又更新了最新版的应用和内核，可是还是cpu时不时的飙到50%以上，也不知道是谁的锅

**Comment by Shsy** [comment]
> ，我最近

不过现在用的旧版应用 和 旧版内核 挺稳的。

**Comment by Shsy** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > 说明完了，貌似正常了，感谢大佬，顺道请教一下，有没有地方有，整个clashopenclash的工作原理和流程？有事麻烦推荐一下，非常感谢
> > > > 
> > > > 
> > > > 你好 是 redir-host 模式正常了吗 我和你的情况类似 更新了最新内核 redir-host 模式会有问题，Fake-ip模式正常， 退回旧版本的内核 redir-host 模式就正常了。
> > > 
> > > 
> > > 回复出厂设置就好了，然后配置重新订阅一下，完事
> > 
> > 
> > 确实 恢复出厂设置好了。不过 扶墙总是不稳定。还是恢复到旧内核了
> 
> 嗯，我最近也遇到这个问题，又更新了最新版的应用和内核，可是还是cpu时不时的飙到50%以上，也不知道是谁的锅

不过现在用的旧版应用 和 旧版内核 挺稳的。

**Comment by CrazyMouse** [comment]
> > > > > > > 
> > > > > > 
> > > > > > 
> > > > > > 说明完了，貌似正常了，感谢大佬，顺道请教一下，有没有地方有，整个clashopenclash的工作原理和流程？有事麻烦推荐一下，非常感谢
> > > > > 
> > > > > 
> > > > > 你好 是 redir-host 模式正常了吗 我和你的情况类似 更新了最新内核 redir-host 模式会有问题，Fake-ip模式正常， 退回旧版本的内核 redir-host 模式就正常了。
> > > > 
> > > > 
> > > > 回复出厂设置就好了，然后配置重新订阅一下，完事
> > > 
> > > 
> > > 确实 恢复出厂设置好了。不过 扶墙总是不稳定。还是恢复到旧内核了
> > 
> > 
> > 嗯，我最近也遇到这个问题，又更新了最新版的应用和内核，可是还是cpu时不时的飙到50%以上，也不知道是谁的锅
> 
> 不过现在用的旧版应用 和 旧版内核 挺稳的。

我现在最新的应用和内核，但是每天半夜定时重启一下应用，两天了，还没发现有cpu特别高的情况，或许是我没注意到

**Comment by XinSSS** [comment]
@vernesong 
有个问题请教，我目前的模式是redir-host， DNS里， nameserver或者fallback必须有无污染的DNS解析服务吗？

```
  nameserver:
  - 223.5.5.5
  - 119.29.29.29
```
当我只设置了国内DNS， 发现上不了Google youtube等网站， 这个正常吗？
我记得曾经看过clash的一些说明， 好像是解析是国外网站走代理的时候，本地dns解析结果无效，通过远程解析，那实际情况和这个不一样啊？

**Comment by Charliecheung2** [comment]
> > > > > > > 
> > > > > > 
> > > > > > 
> > > > > > 说明完了，貌似正常了，感谢大佬，顺道请教一下，有没有地方有，整个clashopenclash的工作原理和流程？有事麻烦推荐一下，非常感谢
> > > > > 
> > > > > 
> > > > > 你好 是 redir-host 模式正常了吗 我和你的情况类似 更新了最新内核 redir-host 模式会有问题，Fake-ip模式正常， 退回旧版本的内核 redir-host 模式就正常了。
> > > > 
> > > > 
> > > > 回复出厂设置就好了，然后配置重新订阅一下，完事
> > > 
> > > 
> > > 确实 恢复出厂设置好了。不过 扶墙总是不稳定。还是恢复到旧内核了
> > 
> > 
> > 嗯，我最近也遇到这个问题，又更新了最新版的应用和内核，可是还是cpu时不时的飙到50%以上，也不知道是谁的锅
> 
> 不过现在用的旧版应用 和 旧版内核 挺稳的。

你用的那个版本的应用和内核？

**Comment by Charliecheung2** [comment]
> > > > > > > 
> > > > > > 
> > > > > > 
> > > > > > 说明完了，貌似正常了，感谢大佬，顺道请教一下，有没有地方有，整个clashopenclash的工作原理和流程？有事麻烦推荐一下，非常感谢
> > > > > 
> > > > > 
> > > > > 你好 是 redir-host 模式正常了吗 我和你的情况类似 更新了最新内核 redir-host 模式会有问题，Fake-ip模式正常， 退回旧版本的内核 redir-host 模式就正常了。
> > > > 
> > > > 
> > > > 回复出厂设置就好了，然后配置重新订阅一下，完事
> > > 
> > > 
> > > 确实 恢复出厂设置好了。不过 扶墙总是不稳定。还是恢复到旧内核了
> > 
> > 
> > 嗯，我最近也遇到这个问题，又更新了最新版的应用和内核，可是还是cpu时不时的飙到50%以上，也不知道是谁的锅
> 
> 不过现在用的旧版应用 和 旧版内核 挺稳的。

你用的那个版本的应用和内核？
