### ISSUE TITLE
求教：关于国内流量不经过内核

### ISSUE THREAD

**Issue by InsOnYou** [vernesong/OpenClash#1792]
因为redir-host没有远程DNS了，所以最近开始用Fake-IP模式。我希望Fake-IP模式里国内流量也不经过内核，所以将国内域名添加进第二DNS列表（返回真实IP）。

接下来是手动添加防火墙规则：
ipset create china_ip_route hash:net family inet hashsize 1024 maxelem 1000000
iptables -t nat -A openclash -m set --match-set china_ip_route dst -j RETURN
这样设置没有效果，流量还是经过了内核。

请问防火墙里要怎样添加规则才能让ipset的IP不经过内核呢？

**Comment by vernesong** [comment]
iptables -t nat -I openclash -m set --match-set china_ip_route dst -j RETURN

**Comment by InsOnYou** [comment]
> iptables -t nat -I openclash -m set --match-set china_ip_route dst -j RETURN

感谢解答，tun模式把nat换成mangle就可以了

**Comment by jayling1111** [comment]
看不懂啊，有没有大神详细说说
