### ISSUE TITLE
流媒体增强标签改进？

### ISSUE THREAD

**Issue by DockerCS** [vernesong/OpenClash#1793]
不知道可不可以提一个小小的意见？

流媒体标签很好用，但是现在奈菲和Disney Plus节点失效太快了，如果按照这个流媒体标签，我们的奈菲或者Disney账号就会满世界跑动。

需求：能不能设置地区在流媒体标签基础上设置地区标签，比如我首先选择台湾区的奈菲节点（台湾区有节点：台湾 1、台湾2和台湾3），那么只要台湾123这个三个节点没有全部失效，我们就在这三个节点里面切换。仅当台湾区的节点全部失效了，再轮换到别的区。

**Comment by vernesong** [comment]
建议你单独建立一个台湾的select策略组，再在奈飞的策略组里面嵌套一下，勾选展开策略组即可

**Comment by matthuo333** [comment]
借地问下，fallback 组和url-test组是不是在每次clash内核启动后，大约15分钟左右，按照各自检测规则的结果是不准的？
