### ISSUE TITLE
proxy provider filter未生效

### ISSUE THREAD

**Issue by lhn1989** [vernesong/OpenClash#1798]
在代理集配置中添加了"代理集节点筛选"的关键词，更新proxy provider发现过滤未生效
OpenClash版本：v0.44.01-beta
Dev内核版本: v1.8.0-7-g075d8ed

===================
节点名称信息：
- name: "\U0001F1ED\U0001F1F0 香港 [X1]"

代理集节点筛选：
香港

结果：
未把不包含“香港”关键词的节点过滤掉，所有节点都订阅到了

**Comment by vernesong** [comment]
目前只有dev内核支持

**Comment by lhn1989** [comment]
> 目前只有dev内核支持

明白了，多谢！

**Comment by lhn1989** [comment]
更新2021.12.07版本TUN内核后filter已经生效
