### ISSUE TITLE
奈飞TV下提示解锁工具

### ISSUE THREAD

**Issue by spirytuslove** [vernesong/OpenClash#1799]
问题情况手机端可以TV端有些影片提示代理 还了一个其他家的机场TV端就不提示代理  尝试手动抓取域名很多次都抓不完  而且会有重复的抓取到  尝试抓取到的添加在netflix_domains里面  然后更新规则  但是运行日志显示没有更新也没有提示更新成功的提示  是不是更新成功也不提示啊  还有为什么抓去了很多添加进去还是不行  会提示代理。。。

**Comment by vernesong** [comment]
抓取结果是自动去重保存的，规则更新时更新的我在仓库预置的域名

**Comment by vernesong** [comment]
你用香港新加坡这些地方的节点应该不会出现才对，域名都是全的

**Comment by spirytuslove** [comment]
大佬我是直接把抓取的域名放在了netflix_domains里面的啊  你的意思放里面如果再点流媒体增强里面的更新Netflix域名列表就会还原你仓库预置的域名是吗  那我如果抓取了域名不用更新就行了这样就算添加了新的是吗🥲

**Comment by spirytuslove** [comment]
我发现我新加坡自己抓了放你说的文件夹里面还是有的片子提示代理  但是换另一家新加坡节点就没这个问题。。。  而且抓取确实会抓到重复的域名不知道啥情况。。。

**Comment by matthuo333** [comment]
我也遇到。改成global, 仍然存在。有没有可能与上级路由器中IPV6 设置相关？
