### ISSUE TITLE
无法启动[斐逊K3/openwrt]

### ISSUE THREAD

**Issue by bzdouble** [vernesong/OpenClash#18]
页面显示如下，![image](https://user-images.githubusercontent.com/10475087/63828473-2fc30500-c999-11e9-8908-c727c080ac0a.png)
从ssh启动，提示out of range

**Comment by vernesong** [comment]
内核不对，当前内核版本查询失败

**Comment by bzdouble** [comment]
系统内核是4.40吧，你说的应该是openwrt的系统内核？

**Comment by vernesong** [comment]
clash内核，你重新装一下

**Comment by bzdouble** [comment]
2019-08-28 13:49:25 OpenClash Start Successful
2019-08-28 13:49:32 Watchdog: OpenClash Problem, Restart 
2019-08-28 13:49:38 OpenClash Can Not Start, Please Check The Error Info And Try Again
2019-08-28 14:05:33 OpenClash Can Not Start, Please Check The Error Info And Try Again
2019-08-28 14:05:22 OpenClash Core Update Successful
2019-08-31 09:09:02 OpenClash Can Not Start, Please Check The Error Info And Try Again

**Comment by vernesong** [comment]
当前内核版本号读出来了才能启动，没有其他信息了吗

**Comment by bzdouble** [comment]
日志里面没有其他信息了。
root@OpenWrt:~# cat /proc/cpuinfo
processor       : 0
model name      : ARMv7 Processor rev 0 (v7l)
BogoMIPS        : 1400.00
Features        : half thumb fastmult edsp tls 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x3
CPU part        : 0xc09
CPU revision    : 0

processor       : 1
model name      : ARMv7 Processor rev 0 (v7l)
BogoMIPS        : 1400.00
Features        : half thumb fastmult edsp tls 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x3
CPU part        : 0xc09
CPU revision    : 0

Hardware        : BCM5301X
Revision        : 0000
Serial          : 0000000000000000

**Comment by vernesong** [comment]
`/etc/openclash/clash -v`
这个命令返回版本信息表示内核正常，如果内核正常，你需要再提供启动后系统日志的错误信息
如果提供不了，我无法定位错误原因

**Comment by bzdouble** [comment]
root@OpenWrt:/tmp/log# /etc/openclash/clash -v
Illegal instruction

**Comment by bzdouble** [comment]
![image](https://user-images.githubusercontent.com/10475087/64218190-38fd2600-cef3-11e9-8613-65469c95a3c0.png)

**Comment by vernesong** [comment]
内核不对，重装或者确认好给了权限

**Comment by bzdouble** [comment]
-rwxrw-rw-    1 root     root         41115 Aug 17 13:19 ConnersHua.yaml
-rwxrw-rw-    1 root     root          2160 Aug 17 13:19 ConnersHua_return.yaml
-rw-r--r--    1 root     root       3899494 Aug 28 05:16 Country.mmdb
-rwxr-xr-x    1 root     root       2744000 Aug 31 14:21 clash
-rw-r--r--    1 root     root       2699392 Aug 21 11:20 clash-linux-armv7.tar.gz
-rw-r--r--    1 root     root         51492 Sep  4 09:04 config.bak
-rw-r--r--    1 root     root         51492 Sep  5 09:38 config.yaml
-rwxrw-rw-    1 root     root          6711 Aug 17 13:19 default.yaml
-rw-r--r--    1 root     root          2110 Sep  4 09:04 dnsmasq_fake_block.conf
-rwxrw-rw-    1 root     root         18340 Aug 17 13:19 lhie1.yaml
-rw-------    1 root     root            46 Aug 28 13:50 nohup.out
-rwxrw-rw-    1 root     root          6719 Aug 17 13:19 openclash_version

**Comment by caoc2008** [comment]
这个需要重新编译，github下载的版本k3无法运行

**Comment by bzdouble** [comment]
编译我不会哎，现学来得及吗？

**Comment by zxlhhyccc** [comment]
> 编译我不会哎，现学来得及吗？

K3请使用ramv5，不要使用6和7.。。。

**Comment by bzdouble** [comment]
> > 编译我不会哎，现学来得及吗？
> 
> K3请使用ramv5，不要使用6和7.。。。

真的吗？但是芯片构架我看是v7啊
