### ISSUE TITLE
更新客户端后Openclash消失

### ISSUE THREAD

**Issue by Ezekiel-Qiu** [vernesong/OpenClash#1801]
更新后就直接白屏，显示：
No page is registered at ' / admin/ services! openclash/ client'

If this url belongs to an extension, make sure it is properly installed.

If the extension was recently installed, try removing the 1 tmp/ luci- indexcache file.

**Comment by OUZYcn** [comment]
没有更新成功，去 系统 - 软件包 ，先 刷新软件包列表， 然后重新安装一次。
