### ISSUE TITLE
各大陆DNS设置哪些啊？

### ISSUE THREAD

**Issue by asnon** [vernesong/OpenClash#1803]
请教下大佬，DNS是用运营商的还是公共DNS啊，现在我是用114加一个运营商的，不知道大家怎么设置呢？谢谢

**Comment by qsrxmm818** [comment]
如果你本地运营商不投毒就运营商，再不济也别用114啊，阿里或者腾讯的DOH DOT不好嘛

**Comment by asnon** [comment]
> 

哈哈，好的，谢谢哈~~

**Comment by Mosney** [comment]
最好就是使用ISP的，如果ISP太难用可以考虑阿里和腾讯的，如果是移动家宽的话还可能是会直接劫持UDP53的普通DNS查询方式设置了也没意义
