### ISSUE TITLE
内网电脑虚拟机搭建的青龙无法外网访问

### ISSUE THREAD

**Issue by beilsn** [vernesong/OpenClash#1804]
把openclash关闭就能正常访问；
模式用的fake ip /混合/Rule模式。
请教大佬如何解决，谢谢！

**Comment by beilsn** [comment]
已解决！

**Comment by beilsn** [comment]
仍然未解决！

**Comment by Sanhom365** [comment]
我用的Redir-Host（TUN-混合）模式，也是一样的问题，而且给青龙使用的地址添加了黑名单，在自定义里规则里也添加了青龙的IP地址直连，但一启用OpenClash，运行青龙里的脚本就API错误，一关掉OpenClash就正常，这太头痛了，能不能鱼与熊掌不可兼得。

**Comment by shuffleer** [comment]
> 我用的Redir-Host（TUN-混合）模式，也是一样的问题，而且给青龙使用的地址添加了黑名单，在自定义里规则里也添加了青龙的IP地址直连，但一启用OpenClash，运行青龙里的脚本就API错误，一关掉OpenClash就正常，这太头痛了，能不能鱼与熊掌可兼得。

解决了吗
