### ISSUE TITLE
[功能建议]Fake-IP模式增加绕过国内IP

### ISSUE THREAD

**Issue by fjjking** [vernesong/OpenClash#1807]
最近切换到Fake-IP模式后发现没有Redir-Host的绕过国内IP的功能，希望能添加，谢谢作者！
以及Fake-IP模式下也没有 访问控制-不走代理的局域网设备

**Comment by paladin4fan** [comment]
Fake-IP应该是和IPv4的“绕过大陆地址”功能是冲突的
即使防火墙加上了return china-set也白搭
需要把所有大陆域名都塞到Fake-IP filter里，或者在路由器的下游dns里加配置文件 把这些大陆域名分流到其他DNS服务器而不是clash的dns端口

**Comment by Bitcion** [comment]
第二个需求hiboy的padavan固件可以实现
或者说在这个固件中，必须手动设置单个设备全局代理才能走代理，不进行设置的默认接入只能绕过代理
