### ISSUE TITLE
建议openclash主界面添加一开机启动选项控制路由器上电是否启动clash

### ISSUE THREAD

**Issue by bigbighill** [vernesong/OpenClash#181]
由于编译的固件中包含ssr plus passwall openclash,建议openclash主界面和这两个添加一开机启动选项控制路由器上电是否启动clash。

**Comment by vernesong** [comment]
启动后开机就会自动运行

**Comment by bigbighill** [comment]
> 启动后开机就会自动运行

因为固件中还包含ssr pllus、passwall这两个工具，希望Openclash增加总开关先项，由用户决定openclash是否会上电自启。

**Comment by xufzh** [comment]
关了就不会自动启动了吧，既然还有其他的工具，用哪个开哪个啊

**Comment by vernesong** [comment]
你既然开启了，上电就会自启，你关闭后，上电就不会自启，请问你的目的是什么？

**Comment by mymld2020** [comment]
求帮助我的每次都需要手动启动？？~~~怎么回事？有没有随系统启动的命令

**Comment by vernesong** [comment]
> 求帮助我的每次都需要手动启动？？~~~怎么回事？有没有随系统启动的命令
> 
> 

固件问题

**Comment by zhanglao10** [comment]
有没有可以用的脚本？
