### ISSUE TITLE
Redir-Host模式无法访问Netflix，Fake-IP降速严重

### ISSUE THREAD

**Issue by wtoxin** [vernesong/OpenClash#1810]
更新到0.44.03版openclash，Redir-Host模式下访问Netflix失效。查看clash连接日志，没有解析到域名netflix.com，取而代之的是userstylesapi.com，除此之外访问Google或其他服务正常。另外切换到Fake-IP模式网速严重下降，从500Mbps下降到不到100Mbps，设备使用的是R4S+ImmortalWrt

**Comment by InsOnYou** [comment]
Netflix有DNS检测，要使用节点当地的DNS才能解锁

**Comment by wtoxin** [comment]
> Netflix有DNS检测，要使用节点当地的DNS才能解锁
请问DNS应如何设置呢
