### ISSUE TITLE
最近这两三天出了什么幺蛾子

### ISSUE THREAD

**Issue by zhangj3** [vernesong/OpenClash#1811]
这两天用的Lean的OP编译的，拉了大佬的clash源码编译的OP固件

不管是开TUN还是兼容还是TUN-混合，谷歌上不去，油管首页打得开，里面视频播放不了

同样的订阅地址在客户端版本v0.43.09-beta [TUN] 当前内核版本 | 2021.09.15 没任何问题

请问是个例还是普遍现象？

**Comment by WYC-2020** [comment]
老内核试下

**Comment by zhangj3** [comment]
> 老内核试下

不知道哪里下载，烦请告知下，老哥

**Comment by zhangj3** [comment]
跟 这个情况类似 https://github.com/vernesong/OpenClash/issues/1775  怎么现在都流行fake-IP了吗？

**Comment by Charliecheung2** [comment]
一样的问题，也尝试过issue里提过的旧内核了，问题依旧。主要是地址里解析到的github和YouTube的ip，和国内，网易云的ip一样，用了face-ip也没有变好，要么是谷歌上不去能看油管。要么就是能上谷歌，但油管视频看不了

**Comment by SeanChengN** [comment]
油管评论、搜索、视频列表都能看，就是视频不能看

**Comment by paladin4fan** [comment]
用Redir的话需要想办法处理DNS防污染

**Comment by zhangj3** [comment]
> 油管评论、搜索、视频列表都能看，就是视频不能看

一样的问题

**Comment by zhangj3** [comment]
> 用Redir的话需要想办法处理DNS防污染

我手头有11个用Lean源码+大佬编译的OP固件，一直用redir都没问题
没有在openclash里设置复杂的，就填入订阅地址，在线转换，11个x86软路由都没问题，
感觉从这个月初开始的openclash源码变动比较大导致的这个问题 反应这个问题的不止我一个
这儿有个跟我类似 [https://github.com/vernesong/OpenClash/issues/1813](url)

我明天上传调试日志

**Comment by paladin4fan** [comment]
> 
这个倒是跟什么源码没有什么太大关系 我一直用的是openwrt官方预编译的固件
这次的版本更新主要是内核跟着clash更新了
Clash最后一版本内核更新里取消了在redir模式下把DNS发送给代理服务器进行解析的功能
现在你开redir模式 是从本机直连DNS服务器解析的 你需要把fallback组的dns服务器设置成确保没有污染的服务器

**Comment by Skyxim** [comment]
> > 
> 
> 这个倒是跟什么源码没有什么太大关系 我一直用的是openwrt官方预编译的固件 这次的版本更新主要是内核跟着clash更新了 Clash最后一版本内核更新里取消了在redir模式下把DNS发送给代理服务器进行解析的功能 现在你开redir模式 是从本机直连DNS服务器解析的 你需要把fallback组的dns服务器设置成确保没有污染的服务器

可以把redir-host改成normal，normal还是原来redir-host逻辑
dns:
  enable: true
  enhanced-mode: normal

**Comment by matthuo333** [comment]
> > 
> 
> 这个倒是跟什么源码没有什么太大关系 我一直用的是openwrt官方预编译的固件 这次的版本更新主要是内核跟着clash更新了 Clash最后一版本内核更新里取消了在redir模式下把DNS发送给代理服务器进行解析的功能 现在你开redir模式 是从本机直连DNS服务器解析的 你需要把fallback组的dns服务器设置成确保没有污染的服务器

如果是 Fake-ip , DNS机制也是这样？

**Comment by matthuo333** [comment]
借此反应另个，不知是不是和core更新为最新的有关。
就是fallback 组 和 urltest 在刚启动core后，完全没有按照标准来运行，乱选节点。有时，整个组的节点全部失效，但实际手动后是Ok的。
大约运行有15分钟到30分钟，貌似正常。

**Comment by paladin4fan** [comment]
> > > 
> > 
> > 
> > 这个倒是跟什么源码没有什么太大关系 我一直用的是openwrt官方预编译的固件 这次的版本更新主要是内核跟着clash更新了 Clash最后一版本内核更新里取消了在redir模式下把DNS发送给代理服务器进行解析的功能 现在你开redir模式 是从本机直连DNS服务器解析的 你需要把fallback组的dns服务器设置成确保没有污染的服务器
> 
> 如果是 Fake-ip , DNS机制也是这样？

不是 Fake-IP在命中规则的时候是代理服务器解析DNS

**Comment by zhangj3** [comment]
> > 
> 
> 这个倒是跟什么源码没有什么太大关系 我一直用的是openwrt官方预编译的固件 这次的版本更新主要是内核跟着clash更新了 Clash最后一版本内核更新里取消了在redir模式下把DNS发送给代理服务器进行解析的功能 现在你开redir模式 是从本机直连DNS服务器解析的 你需要把fallback组的dns服务器设置成确保没有污染的服务器

![image](https://user-images.githubusercontent.com/49198958/144781617-974fd066-6eaf-4e9f-b32a-85f1a4108ce6.png)

嗯  我直接勾选这个 也好了，不过据说不加normal模式的话  机场主设置的DNS解锁都失效了 不知真假，我这个问题是临时解决了，谢谢大佬

**Comment by paladin4fan** [comment]
> 

我是没在文档里看到enhace-mode还有normal这个选项
我暂时是套个娃用另一个插件查询dns 然后把这个插件的流量统统发送给代理服务器
