### ISSUE TITLE
在Redir-Host模式下 ，未命中规则的链接由NameServer组的DNS去查询吗？

### ISSUE THREAD

**Issue by Ezekiel-Qiu** [vernesong/OpenClash#1814]
在Redir-Host（兼容）模式下 
客户端进行通讯时DNS由Clash先进行并发查询，等待返回结果后再尝试进行规则判定和连接。
当判定需要代理时，使用fallback组DNS的查询结果进行通讯

 如果没命中规则不需要代理的怎么处理？
由NameServer组的DNS去查询吗？

**Comment by vernesong** [comment]
直连，如果命中fallbackfilter会使用fallback直连
