### ISSUE TITLE
开启了 OpenClash那么是否能开启Turbo ACC 网络加速设置里的DNS加速

### ISSUE THREAD

**Issue by liuchunxiao** [vernesong/OpenClash#1815]
如题。自己使用了OpenClash，功能正常，如果再开启Turbo ACC 网络加速设置里的DNS加速是否有必要。

另外，MWAN3 分流助手是由有必要设置？

主要是想着加快N1 软路由的DNS解析。

**Comment by asnon** [comment]
完全没有必要，要dns各自套娃么？

**Comment by InsOnYou** [comment]
不能，会冲突
