### ISSUE TITLE
启用openclash后，电视端奇异果无法加载首页，似乎部分域名不通。但是规则应该没问题

### ISSUE THREAD

**Issue by JosephCN** [vernesong/OpenClash#1816]
![image](https://user-images.githubusercontent.com/17092900/144701066-68a3f308-4425-4443-8457-92cdac4d8746.png)
各位小伙伴求助啊！

**Comment by vernesong** [comment]
规则不全

**Comment by JosephCN** [comment]
> 规则不全

您好，我用的是Dler Cloud的托管配置，所以规则不全的问题是Dler那边配置的有问题吗？

**Comment by JosephCN** [comment]
而且，我看到这条规则是Direct，为什么会导致开了Openclash这个地址就没有下载的数据了呢

**Comment by JosephCN** [comment]
同样的托管地址，在手机上用surge就是正常的
