### ISSUE TITLE
关于添加自定义节点的问题

### ISSUE THREAD

**Issue by Revincx** [vernesong/OpenClash#1818]
我想在订阅的配置文件基础之上添加一个自己的节点，但是在 服务器与策略组管理 -> 服务器节点配置 中添加节点之后，重新启动OpenClash，发现原有的配置的proxies和proxy-groups被清空，只剩下了我自己加的这个节点。但是下面的Rules里仍然有原有的策略组，所以导致了启动失败。
请问这是bug吗？如果不是的话该怎么实现添加自定义节点呢？

OpenClash 版本：0.44.03

**Comment by vernesong** [comment]
先读取配置文件
