### ISSUE TITLE
[Feature] 希望适配1.8.0的normal模式

### ISSUE THREAD

**Issue by Skyxim** [vernesong/OpenClash#1819]
clash 1.8.0 redir-host修改了行为变成不远程解析域名，但是其添加了一个normal模式，是原redir-host的逻辑可远程解析域名，希望增加适配
https://github.com/Dreamacro/clash/commit/81d5da51a3b0d84ed0a6f752c3e7c02e1065bce1#r60095695
判断逻辑https://github.com/Dreamacro/clash/blob/81d5da51a3b0d84ed0a6f752c3e7c02e1065bce1/constant/metadata.go#L92
现有模式https://github.com/Dreamacro/clash/blob/81d5da51a3b0d84ed0a6f752c3e7c02e1065bce1/constant/dns.go#L9

**Comment by zhangj3** [comment]
@vernesong  大佬，帮忙看下，谢谢
