### ISSUE TITLE
在OpenClash中手动修改配置文件并点击保存配置会导致整个路由后台失去响应

### ISSUE THREAD

**Issue by n0tva1id** [vernesong/OpenClash#182]
描述：
koolshare lede X86_64 V2.31
openclash v0.36.6-beta
尝试过一次直接在openclash的luci中修改配置文件，点击保存配置之后路由管理界面会失去响应，再次尝试访问管理后台无用。
重启lede后正常，并注意到配置文件没有被成功修改。

**Comment by vernesong** [comment]
特殊字符？我这边上万行写入没问题

**Comment by n0tva1id** [comment]
的确配置文件中有emoji符号

**Comment by vernesong** [comment]
那就本地改好了再上传吧

**Comment by n0tva1id** [comment]
好的👌
