### ISSUE TITLE
FakeIP解锁Netflix的问题

### ISSUE THREAD

**Issue by warcns** [vernesong/OpenClash#1828]
因为有PS5，所以之前一直使用redir模式，NF解锁也正常。昨天Dlercloud修改了nf解锁方式，hk线路解锁sg的nf，发现redir模式不生效，无论是电视还是电脑看到的都是nf自制剧。切换到fakeip模式后，nf解锁的问题解决，电视和电脑都可以通过openclash看到sg解锁nf。

但是在openclash的fakeip模式下，PS5会出现间歇断网的情况，表现为时不时的连不上PSN账号，打不开PSN商店，断Wi-Fi重新连接后可以解决一会儿。但过一会儿又无法连接psn。请问大佬有没有解决办法或者思路。

**Comment by paladin4fan** [comment]
1.换旧版本内核开redir模式
2.自己加一个插件转发DNS给代理服务器
3.找出PSN商店的域名放入FakeIP的filter里
提供三个不同的思路

**Comment by kurtn2005** [comment]
> 说的对，感谢提供思路。
> 
> 我在DNS设置的Fake-IP黑名单中添加了以下两个域名，似乎是解决了，我再观察一下效果。
> 
> *.playstation.net *.playstation.com

我想问问这个FakeIP黑名单起什么作用呢？

**Comment by paladin4fan** [comment]
> > 说的对，感谢提供思路。
> > 我在DNS设置的Fake-IP黑名单中添加了以下两个域名，似乎是解决了，我再观察一下效果。
> > *.playstation.net *.playstation.com
> 
> 我想问问这个FakeIP黑名单起什么作用呢？

名单里的域名不会使用假IP 而是返回真实IP

**Comment by warcns** [comment]
设置fakeip黑名单后有一些效果，但PS5商店还是会断流，不过坚持时间变长了，也没发现漏掉的域名，不是很明白为啥。。。

**Comment by paladin4fan** [comment]
> 设置fakeip黑名单后有一些效果，但PS5商店还是会断流，不过坚持时间变长了，也没发现漏掉的域名，不是很明白为啥。。。

不知道PS5的商店是不是有独立CDN域名存在  断网重连可以恢复的情况有点类似本地缓存

**Comment by warcns** [comment]
> > 设置fakeip黑名单后有一些效果，但PS5商店还是会断流，不过坚持时间变长了，也没发现漏掉的域名，不是很明白为啥。。。
> 
> 
> 
> 不知道PS5的商店是不是有独立CDN域名存在  断网重连可以恢复的情况有点类似本地缓存

不理解为啥，也检查ps5的链接了，也没有漏。就是还是会出现间歇性断流，以前用redir模式就没出现过。

**Comment by paladin4fan** [comment]
> > > 设置fakeip黑名单后有一些效果，但PS5商店还是会断流，不过坚持时间变长了，也没发现漏掉的域名，不是很明白为啥。。。
> > 
> > 
> > 不知道PS5的商店是不是有独立CDN域名存在  断网重连可以恢复的情况有点类似本地缓存
> 
> 不理解为啥，也检查ps5的链接了，也没有漏。就是还是会出现间歇性断流，以前用redir模式就没出现过。

我用FakeIP有可能出现CDN图床加载不出来 但是重开浏览器之后就正常了
你PS5的链接是怎么检查的

**Comment by warcns** [comment]
> > > > 设置fakeip黑名单后有一些效果，但PS5商店还是会断流，不过坚持时间变长了，也没发现漏掉的域名，不是很明白为啥。。。
> 
> > > 
> 
> > > 
> 
> > > 不知道PS5的商店是不是有独立CDN域名存在  断网重连可以恢复的情况有点类似本地缓存
> 
> > 
> 
> > 不理解为啥，也检查ps5的链接了，也没有漏。就是还是会出现间歇性断流，以前用redir模式就没出现过。
> 
> 
> 
> 我用FakeIP有可能出现CDN图床加载不出来 但是重开浏览器之后就正常了
> 
> 你PS5的链接是怎么检查的

看clash控制台里的ps5链接，也没啥特别的。

**Comment by paladin4fan** [comment]
> > > > > 设置fakeip黑名单后有一些效果，但PS5商店还是会断流，不过坚持时间变长了，也没发现漏掉的域名，不是很明白为啥。。。
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 不知道PS5的商店是不是有独立CDN域名存在  断网重连可以恢复的情况有点类似本地缓存
> > 
> > 
> > > 
> > 
> > 
> > > 不理解为啥，也检查ps5的链接了，也没有漏。就是还是会出现间歇性断流，以前用redir模式就没出现过。
> > 
> > 
> > 我用FakeIP有可能出现CDN图床加载不出来 但是重开浏览器之后就正常了
> > 你PS5的链接是怎么检查的
> 
> 看clash控制台里的ps5链接，也没啥特别的。

我有时Clash拿不到域名
可能得抓包看看 但是也不一定是这个原因

**Comment by warcns** [comment]
通过Fake-IP Tun混合模式，同时在DNS设置的Fake-IP黑名单中添加了以下两个域名，问题解决。
*.playstation.net
*.playstation.com

**Comment by xiaofeixia0511** [comment]
> 

有没有代码参考下
