### ISSUE TITLE
动态域名或公网IP访问问题。

### ISSUE THREAD

**Issue by klaus121** [vernesong/OpenClash#1830]
在外网动态域名登录时对比公网IP访问时区别。动态域名登陆界面多想内容不显示。
![be6b53e96e69d8300e911a3d2f078ec](https://user-images.githubusercontent.com/74805660/145174004-01825b48-8e7d-484d-8c34-949c244fc093.png)
![c37947aa5521b92c00c62e10f4785a7](https://user-images.githubusercontent.com/74805660/145174009-6bb9be54-4ec0-417e-ab67-9d2d00f59a0b.png)

**Comment by vernesong** [comment]
这是前端数据，跟本地环境有关

**Comment by klaus121** [comment]
> 这是前端数据，跟本地环境有关

好的。谢谢。
