### ISSUE TITLE
最新版本在“运行状态”下不显示IP检测，不显示保存设置和应用设置，不显示相关大佬头像，经查发现是client.lua文件引起，见截图！！！

### ISSUE THREAD

**Issue by zxlhhyccc** [vernesong/OpenClash#1831]
**client.lua中的代码只有部分生效，烦请dalao修复！！！**

**msaster分支下的目前状态只显示此部分：**

![image](https://user-images.githubusercontent.com/45259624/145337288-fb32b5a7-1493-48a0-80fb-7b64c65b8979.png)

**简单修改一下状态如下：**

![image](https://user-images.githubusercontent.com/45259624/145337674-435765b7-9e6d-4784-83a5-81c004992b23.png)

**Comment by WYC-2020** [comment]
@zxlhhyccc 应该不是这个问题，我这边最新编译的也能出来啊，是不是你主题或者其他什么导致了
![image](https://user-images.githubusercontent.com/34025388/145363261-d5277f02-9970-4f78-add6-47e78b140f71.png)

**Comment by zxlhhyccc** [comment]
> @zxlhhyccc 应该不是这个问题，我这边最新编译的也能出来啊，是不是你主题或者其他什么导致了 ![image](https://user-images.githubusercontent.com/34025388/145363379-2a99ca4e-54d6-4da9-b8db-91513a07cc1e.png)

你的能出来肯定不是master分支，而可能是18.06分支，我的不能出来是master分支出不来。。。。

**Comment by WYC-2020** [comment]
@zxlhhyccc 我就说什么master嘛，你是官方op，luci21吧，问题都没描述清楚，这样的话有可能，官方没玩过

**Comment by zxlhhyccc** [comment]
> @zxlhhyccc 我就说什么master嘛，你是官方op，luci21吧，问题都没描述清楚，这样的话有可能，官方没玩过

找到原因了，是截图这里没有全部起作用。。。希望dalao修复，我改了很久搞不定，dler_token不知道是干嘛的！
![image](https://user-images.githubusercontent.com/45259624/145425368-c8d847aa-a2a4-4ce2-b557-739b0c02d59d.png)

**Comment by WYC-2020** [comment]
@zxlhhyccc 那玩意没猜错的话是dler登录后的token,就这个玩意
![image](https://user-images.githubusercontent.com/34025388/145508838-ce38689a-3848-4d5a-b3cf-321660f85d71.png)

**Comment by sun5000** [comment]
12月6号编译的内核更新地址错误 arm指向i386了 造成内核启动失败 12月5日之前的没问题 官方openwrt
