### ISSUE TITLE
Fake-IP混合模式下，通过DIRECT的连接不能转发udp

### ISSUE THREAD

**Issue by warcns** [vernesong/OpenClash#1832]
大佬好，我的v0.44.03-beta的Fake-IP和tun混合模式下，通过DIRECT直连的连接不能转发udp，通过节点的udp转发就是正常的。不知道是为什么。

另外在Fake-IP增强模式下，Direct或通过节点的udp转发都正常。

**Comment by paladin4fan** [comment]
奇怪 我当前版本不管走不走节点 主要UDP转发了就不正常

**Comment by warcns** [comment]
> 奇怪 我当前版本不管走不走节点 主要UDP转发了就不正常

ps5需要udp转发… 不然也不怎么用这个。

**Comment by paladin4fan** [comment]
> > 奇怪 我当前版本不管走不走节点 主要UDP转发了就不正常
> 
> ps5需要udp转发… 不然也不怎么用这个。

我开转发discord上不去 不开udp转发裸连反而能上 就是延迟有点高

**Comment by warcns** [comment]
> > > 奇怪 我当前版本不管走不走节点 主要UDP转发了就不正常
> 
> > 
> 
> > ps5需要udp转发… 不然也不怎么用这个。
> 
> 
> 
> 我开转发discord上不去 不开udp转发裸连反而能上 就是延迟有点高

udp转发有没有走节点？还是直连的？

**Comment by paladin4fan** [comment]
> > > > 奇怪 我当前版本不管走不走节点 主要UDP转发了就不正常
> > 
> > 
> > > 
> > 
> > 
> > > ps5需要udp转发… 不然也不怎么用这个。
> > 
> > 
> > 我开转发discord上不去 不开udp转发裸连反而能上 就是延迟有点高
> 
> udp转发有没有走节点？还是直连的？

我开了转发 走不走节点都没有流量产生

**Comment by warcns** [comment]
> > > > > 奇怪 我当前版本不管走不走节点 主要UDP转发了就不正常
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > ps5需要udp转发… 不然也不怎么用这个。
> > > 
> > > 
> > > 我开转发discord上不去 不开udp转发裸连反而能上 就是延迟有点高
> > 
> > 
> > udp转发有没有走节点？还是直连的？
> 
> 我开了转发 走不走节点都没有流量产生

我的OpenWRT用的是lean的，集成的有Docker，之前的openclash版本只能用redir模式，在fakeip模式不能转发udp，用tun混合模式直接不能上网。

这次更新后f为了看nf只能切成fakeip增强模式，发现可以正常转发udp了。但是fakeip混合模式下，tun只能转发通过节点的udp，直连的udp转发不了，就很迷。

**Comment by paladin4fan** [comment]
> > > > > > 奇怪 我当前版本不管走不走节点 主要UDP转发了就不正常
> > > > 
> > > > 
> > > > > 
> > > > 
> > > > 
> > > > > ps5需要udp转发… 不然也不怎么用这个。
> > > > 
> > > > 
> > > > 我开转发discord上不去 不开udp转发裸连反而能上 就是延迟有点高
> > > 
> > > 
> > > udp转发有没有走节点？还是直连的？
> > 
> > 
> > 我开了转发 走不走节点都没有流量产生
> 
> 我的OpenWRT用的是lean的，集成的有Docker，之前的openclash版本只能用redir模式，在fakeip模式不能转发udp，用tun混合模式直接不能上网。
> 
> 这次更新后f为了看nf只能切成fakeip增强模式，发现可以正常转发udp了。但是fakeip混合模式下，tun只能转发通过节点的udp，直连的udp转发不了，就很迷。

我是官方固件+clash for Windows 只要开了TUN discord就只能登录不能链接语音频道

**Comment by M1A6I3L** [comment]
同样的问题，没开大陆ip不代理，11月28日更新后出现的，换回9.15的tun内核就好了。

**Comment by paladin4fan** [comment]
> 同样的问题，没开大陆ip不代理，11月28日更新后出现的，换回9.15的tun内核就好了。

老版本的TUN内核在哪找

**Comment by warcns** [comment]
> > 同样的问题，没开大陆ip不代理，11月28日更新后出现的，换回9.15的tun内核就好了。
> 
> 老版本的TUN内核在哪找

同问，请问在哪里可以下老板本的tun内核呢？

**Comment by M1A6I3L** [comment]
https://github.com/vernesong/OpenClash/tree/8ac637cf85a9c9c33efa6426285bd13d382f143b/core-lateset/premium

**Comment by warcns** [comment]
> 

我按你的方法，使用Fakeip增强模式，然后把UDP转发关掉，居然解决问题了，貌似PS5的商店也不断了，NAT类型也回到NAT2了。

关掉UDP转发后好像完全走的直连，openclash就不接管了。

**Comment by paladin4fan** [comment]
> > 
> 
> 我按你的方法，使用Fakeip增强模式，然后把UDP转发关掉，居然解决问题了，貌似PS5的商店也不断了，NAT类型也回到NAT2了。
> 
> 关掉UDP转发后好像完全走的直连，openclash就不接管了，在Clash控制台中就看不到UDP的连接了，但udp转发都是成功的。

我没测试增强模式关UDP的时候有没有走转发
我换了老版本的TUN内核开混合模式 discord也正常了 面板获取到了TUN->Direct的链接 有流量了

**Comment by paladin4fan** [comment]
> https://github.com/vernesong/OpenClash/tree/8ac637cf85a9c9c33efa6426285bd13d382f143b/core-lateset/premium

感谢
原来就在这个项目的子文件夹里 我还满地乱找

**Comment by warcns** [comment]
> > 我按你的方法，使用Fakeip增强模式，然后把UDP转发关掉，居然解决问题了，貌似PS5的商店也不断了，NAT类型也回到NAT2了。
> > 关掉UDP转发后好像完全走的直连，openclash就不接管了，在Clash控制台中就看不到UDP的连接了，但udp转发都是成功的。
> 
> 我没测试增强模式关UDP的时候有没有走转发 但是增强模式勾选UDP转发我就上不去Discord 我换了老版本的TUN内核开混合模式 discord也正常了 面板获取到了TUN->Direct的链接 有流量了

我测试了，我的tun模式完全无法使用，无论是新旧内核都不行。。。

**Comment by warcns** [comment]
经过大佬的回复问题已经解决。原因是旁路由使用的一条自定义防火墙规则，去掉之后，无论新老版本的tun内核都可以正常转发Direct或通过节点的udp了。

https://github.com/vernesong/OpenClash/issues/1835

**Comment by TioaChan** [comment]
> https://github.com/vernesong/OpenClash/tree/8ac637cf85a9c9c33efa6426285bd13d382f143b/core-lateset/premium

非常感谢，回退内核后discrod和开黑啦语音都正常了

**Comment by lbwstco** [comment]
> > https://github.com/vernesong/OpenClash/tree/8ac637cf85a9c9c33efa6426285bd13d382f143b/core-lateset/premium
> 
> 非常感谢，回退内核后discrod和开黑啦语音都正常了

请问回退到了哪个版本

**Comment by CuewarsTaner** [comment]
2023年还是遇到这养的问题，Discord的语音进不去，请问怎么解决

**Comment by crazypeng28** [comment]
我这几天也遇到这问题，登陆不了ps5账号，机子是日版用网线直连，r2s做主路由，系统openwrt 梯子openclash，能帮下解决吗

**Comment by duanzhouliang1688** [comment]
我是face-ip增强模式，把UDP流量转发关了，就可以支持UPD转发了，奇怪

**Comment by MagicAt12138** [comment]
相同问题，有大佬解决一下吗
