### ISSUE TITLE
最近的版本打开openclash后，电脑总是提示无法访问互联网

### ISSUE THREAD

**Issue by mzl0408** [vernesong/OpenClash#1839]
电脑是win11，最近的版本打开openclash后，一会就会提示无法访问互联网，但是能上网，只是个别网站不能上，已经测试过了，不是节点的问题，装回win10后也是同样的问题。

**Comment by konbar** [comment]
用老版本的内核试试..我也遇到路由升级后无法使用的情况,最后把老版本的内核加载后,一切OK了
[https://github.com/konbar/img/blob/main/%E6%97%A0%E6%A0%87%E9%A2%98.jpg?raw=true](url)

**Comment by vernesong** [comment]
windows系统联通性测试地址在有些地区需要代理才行

**Comment by Mosney** [comment]
可以根据 https://zhuanlan.zhihu.com/p/420019928 修改网络监测的地址

**Comment by OUZYcn** [comment]
> 可以根据 https://zhuanlan.zhihu.com/p/420019928 修改Windows网络检测的地址


Fake-IP域名黑名单 ，已经有如下设置的。 

```
#win10本地连接检测
*.msftconnecttest.com
*.msftncsi.com
msftconnecttest.com
msftncsi.com
```
在客户机上检查结果 dns.msftncsi.com 是正常解析。
```
PS C:\Users\ouzyc> nslookup dns.msftncsi.com
服务器:  UnKnown
Address:  192.168.1.250

名称:    dns.msftncsi.com
Address:  131.107.255.255
```
**但是如下两个不正常。咋搞？**

```
PS C:\Users\ouzyc> nslookup msftncsi.com
服务器:  UnKnown
Address:  192.168.1.250

名称:    msftncsi.com
```
```
PS C:\Users\ouzyc> nslookup ipv6.msftncsi.com
服务器:  UnKnown
Address:  192.168.1.250

名称:    ipv6.msftncsi.com
```

**Comment by OUZYcn** [comment]
查了下手册中关于wildcard的解释。
https://lancellc.gitbook.io/clash/clash-config-file/syntax#wildcard

改成如下OK了。 

```
#win10本地连接检测
+.msftconnecttest.com
+.msftncsi.com
```

**Comment by Kosette** [comment]
> **但是如下两个不正常。咋搞？**
> 
> ```
> PS C:\Users\ouzyc> nslookup msftncsi.com
> 服务器:  UnKnown
> Address:  192.168.1.250
> 
> 名称:    msftncsi.com
> ```
> 
> ```
> PS C:\Users\ouzyc> nslookup ipv6.msftncsi.com
> 服务器:  UnKnown
> Address:  192.168.1.250
> 
> 名称:    ipv6.msftncsi.com
> ```

`msftncsi.com` 本身就是没有解析的，`ipv6.msftncsi.com` 请确保能正常获得AAAA解析结果，这个域名只有AAAA解析，没有A解析。

**Comment by Haoyan2046** [comment]
> > **但是如下两个不正常。咋搞？**
> > ```
> > PS C:\Users\ouzyc> nslookup msftncsi.com
> > 服务器:  UnKnown
> > Address:  192.168.1.250
> > 
> > 名称:    msftncsi.com
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > PS C:\Users\ouzyc> nslookup ipv6.msftncsi.com
> > 服务器:  UnKnown
> > Address:  192.168.1.250
> > 
> > 名称:    ipv6.msftncsi.com
> > ```
> 
> `msftncsi.com` 本身就是没有解析的，`ipv6.msftncsi.com` 请确保能正常获得AAAA解析结果，这个域名只有AAAA解析，没有A解析。

确实，允许ipv6解析后就一切正常了，感谢

**Comment by driverCzn** [comment]
dns.msftncsi.com
fake-ip黑名单加入上面那个网址，点击“检查并更新”，等待openclash重新启动之后立即生效。

**Comment by gmmy1979** [comment]
我的也是，Fake-IP域名黑名单有：
#win10本地连接检测
+.msftconnecttest.com
+.msftncsi.com
能上网，爬墙也正常，就是显示地球
我在opclash规律里面添加了，这两条直连的，然后更新订阅，就可以了
DOMAIN-SUFFIX,msftconnecttest.com
DOMAIN-SUFFIX,msftncsi.com
