### ISSUE TITLE
openclash突然失效，但显示一切正常（非节点问题）

### ISSUE THREAD

**Issue by Passerby1011** [vernesong/OpenClash#1841]
openclash突然失效，但是显示一切正常
![屏幕截图 2021-12-14 043418](https://user-images.githubusercontent.com/63802758/145884585-371de534-d68d-474f-98ee-5d7d4d45243b.png)
但是所有节点测速均失效（节点以及配置没有任何问题我把配置下载到了本地测试了）
![image](https://user-images.githubusercontent.com/63802758/145884786-887c85f6-b52d-4a50-84dc-8f075386aee1.png)
还有就是yacd面板会打不开
![image](https://user-images.githubusercontent.com/63802758/145884848-234aef56-0f03-4df1-9736-bed90f9c5199.png)
一直是这个状态，
换过配置、路由重启过，内核删除重下过，是突然出现的，一开始用的好好的，用了很久了

**Comment by vernesong** [comment]
本机网络通吗？

**Comment by Passerby1011** [comment]
通，更新下载载了订阅，并且在测试时ping了百度没有问题

**Comment by vernesong** [comment]
发调试日志

**Comment by Passerby1011** [comment]
机子今天重刷了。。。。。。
