### ISSUE TITLE
[功能建议]建议可以对服务器节点列表进行批量操作、甚至可以增加测速功能，剔除慢节点

### ISSUE THREAD

**Issue by hubeiwmx** [vernesong/OpenClash#1844]
[功能建议]建议可以对服务器节点列表进行批量操作、甚至可以增加测速功能，剔除慢节点

**Comment by Mosney** [comment]
这种需求利用clash本身的url-test组就可以实现，至于根据下载速度选节点那是不现实的

**Comment by Mosney** [comment]
这种需求利用clash本身的url-test组就可以实现，至于根据下载速度选节点那是不现实的
