### ISSUE TITLE
V2Ray 是否支持 Mux 多路复用？

### ISSUE THREAD

**Issue by JasonWei512** [vernesong/OpenClash#1845]
代码里[有提及 Mux](https://github.com/vernesong/OpenClash/search?q=mux)，看上去似乎像是能通过修改 `/etc/openclash/config/config.yaml` 启用的样子，不过 Web UI 上没有找到配置项

**Comment by vernesong** [comment]
![image](https://user-images.githubusercontent.com/42875168/146429006-b1cb7d6f-72b9-4003-afaa-f4caff6f4cdb.png)
