### ISSUE TITLE
为什么url-test 非常不准？求大神指点

### ISSUE THREAD

**Issue by matthuo333** [vernesong/OpenClash#1846]
刚好遇到无效节点在url-test组， 这个组其它均有效。结果几乎每次test都要选择这个无效节点。这个是什么原因，怎么破呢？

配置如下：
- name: Auto - TUrlTest
    type: url-test
    url: http://www.msftconnecttest.com/connecttest.txt
    interval: 300
    tolerance: 100
    proxies:
    - "[VMess] XLC-AHTW"
    - "[VMess] GHK-AHTW"
    - "[VMess] ORC-CHSG-AHTW"

**Comment by vernesong** [comment]
url: http://www.msftconnecttest.com/connecttest.txt

换一个

**Comment by matthuo333** [comment]
有推荐的么？ 之前用那个默认的204发现也有问题，才换的这个。
