### ISSUE TITLE
PING延迟检测失败

### ISSUE THREAD

**Issue by PN62323424** [vernesong/OpenClash#1849]
FAKE-IP模式，其余无任何问题，也尝试添加了cfw-latency-url字段，但是一直检测延迟失败

**Comment by vernesong** [comment]
哪里的延迟检测

**Comment by PN62323424** [comment]
> 哪里的延迟检测

服务器&策略组管理-服务器节点配置

**Comment by vernesong** [comment]
这里是简单的ping，某些服务器禁止ping，可用性还是要看启动后的情况

**Comment by PN62323424** [comment]
> 这里是简单的ping，某些服务器禁止ping，可用性还是要看启动后的情况

启动后在yacd面板里是可以正常ping的，所以我奇怪为什么这里就一直显示失败，不知道哪里的问题
