### ISSUE TITLE
请问备用配置文件是储存在哪个位置

### ISSUE THREAD

**Issue by Old-Pussy** [vernesong/OpenClash#185]
想通过删除重新安装的方式清除所有配置，发现并不成功。openclash会启用上次卸载前的配置作为备用配置启动，请问这个备用配置储存在哪里。

**Comment by vernesong** [comment]
配置文件管理页面可以删除配置文件

**Comment by hackenfu** [comment]
> 想通过删除重新安装的方式清除所有配置，发现并不成功。openclash会启用上次卸载前的配置作为备用配置启动，请问这个备用配置储存在哪里。

好像etc/openclash/backup里有，但不知道是不是所谓的备份
