### ISSUE TITLE
开启openclash xbox无法联网

### ISSUE THREAD

**Issue by liuxiao0725** [vernesong/OpenClash#1851]
rt 哪位大佬知道为啥 只要开启openclash xbox就没办法上网了 fake ip增强模式 其余的什么都没设置

**Comment by crow1943** [comment]
同Fake ip下奈飞也是出现播放问题，提供有代理需要解锁，同网络下其他终端均正常

**Comment by eyaeya** [comment]
同问题，Dler托管规则

**Comment by mars704** [comment]
我也遇到相同问题，未解决。。
