### ISSUE TITLE
如何使命令提示符的tcping正确运行

### ISSUE THREAD

**Issue by jwstaceyOvO** [vernesong/OpenClash#1853]
PROCESS-NAME,tcp.exe,DIRECT
上面的规则实测无效
openclash开启时任意端口会被检测为开放并返回3ms内的延迟
在完全关闭openclash时才能正常检测端口开放并返回实际延迟

**Comment by Mosney** [comment]
这个应该是clash内核的操作，类似的应用都会失效，不管最后策略是直连还是走代理都会影响。应该是无解的吧，如果有解请务必告诉我
