### ISSUE TITLE
设置多isp负载均衡mwan3+mwan helper 与openclash 严重冲突无法上网

### ISSUE THREAD

**Issue by freeme2019** [vernesong/OpenClash#1854]
因为家里是两条不同营运商宽带，一旦在mwan3设置多isp负载均衡，openclash就无法正常访问外网（国内百度之类可以打开），google报错，油管无法播放，openclash设置中启用或关闭dns劫持、自定义dns以及搭配adguardhome ，甚至关闭mwan helper都试过了均无效。之前使用passwall很正常。请指教这是啥原因？

**Comment by vernesong** [comment]
mwan3应该不能用tun模式

**Comment by paladin4fan** [comment]
我把节点端口绑定在固定一条带宽上 TUN模式还算正常

**Comment by freeme2019** [comment]
主要是无法使用mwan3 helper 分流助手，好像会和openclash的dns机制起冲突，但不使用分流助手，多isp线路的优势就无法发挥，至少像我这样的小白觉得很难设置。

**Comment by Doublefire-Chen** [comment]
> 主要是无法使用mwan3 helper 分流助手，好像会和openclash的dns机制起冲突，但不使用分流助手，多isp线路的优势就无法发挥，至少像我这样的小白觉得很难设置。

我的情况是用OpenClash的redir-host兼容模式不会冲突，而用fake-ip增强模式就会冲突，mwan3的规则完全无效，但我想用fake-ip模式。有解决方案了欢迎一起学习交流。

**Comment by paladin4fan** [comment]
> 我把节点端口绑定在固定一条带宽上 TUN模式还算正常

FakeIP返回的目标IP都是私网网段的 你mwan3规则当然不生效
你只能手动维护一个白名单然后加上大陆域名白名单 要么让这些域名绕过openclash的DNS 要么设置里面让openclash对这些域名返回真实IP mwan3才能正确匹配规则

**Comment by Doublefire-Chen** [comment]
> FakeIP返回的目标IP都是私网网段的

也就说mwan3不会代理目标地址为198.18.0.1/16的流量即使我的规则里面目标地址是空着的？（我的理解是目标地址空着就是所有的地址都算，我只填了客户端地址，希望客户端走特定的出口）

**Comment by paladin4fan** [comment]
> > FakeIP返回的目标IP都是私网网段的
> 
> 也就说mwan3不会代理目标地址为198.18.0.1/16的流量即使我的规则里面目标地址是空着的？（我的理解是目标地址空着就是所有的地址都算，我只填了客户端地址，希望客户端走特定的出口）

但是你访问FakeIP地址的包会先被openclash代理
你可以试一下 开fakeip模式 访问IPv6地址查询网站 你的本机IPv6地址会变成路由的地址
Redir-host返回的才是你本机的地址

**Comment by Doublefire-Chen** [comment]
> 但是你访问FakeIP地址的包会先被openclash代理 你可以试一下 开fakeip模式 访问IPv6地址查询网站 你的本机IPv6地址会变成路由的地址 Redir-host返回的才是你本机的地址

我目前的网络环境是纯V4，V6与OpenClash冲突（上次折腾V6，V6网站直接就连过去了，我调用OpenAI的API，然后号就被永封了，从此再也不碰V6了，反正也不玩PT，没这需求）

我刚刚尝试加了filter，不知道是不是地方不对（全局设置>规则设置（访问控制）>自定义规则（访问控制）），还是没有效果
fake-ip-filter:
#  - '*.lan'
  - bbs.pku.edu.cn

**Comment by Doublefire-Chen** [comment]
> > 但是你访问FakeIP地址的包会先被openclash代理 你可以试一下 开fakeip模式 访问IPv6地址查询网站 你的本机IPv6地址会变成路由的地址 Redir-host返回的才是你本机的地址
> 
> 我目前的网络环境是纯V4，V6与OpenClash冲突（上次折腾V6，V6网站直接就连过去了，我调用OpenAI的API，然后号就被永封了，从此再也不碰V6了，反正也不玩PT，没这需求）
> 
> 我刚刚尝试加了filter，不知道是不是地方不对（全局设置>规则设置（访问控制）>自定义规则（访问控制）），还是没有效果
> 
> ```
> dns:
>   fake-ip-filter:
>     - bbs.pku.edu.cn
> ```

问题已解决，将插件更新到最新版本，有专门的地方配置fake-ip-filter，覆写设置>DNS设置>Fallback-Filter勾上>Fake-IP-Filter勾上然后自定义

**Comment by liuyandashen** [comment]
> > > 但是你访问FakeIP地址的包会先被openclash代理 你可以试一下 开fakeip模式 访问IPv6地址查询网站 你的本机IPv6地址会变成路由的地址 Redir-host返回的才是你本机的地址
> > 
> > 
> > 我目前的网络环境是纯V4，V6与OpenClash冲突（上次折腾V6，V6网站直接就连过去了，我调用OpenAI的API，然后号就被永封了，从此再也不碰V6了，反正也不玩PT，没这需求）
> > 我刚刚尝试加了filter，不知道是不是地方不对（全局设置>规则设置（访问控制）>自定义规则（访问控制）），还是没有效果
> > ```
> > dns:
> >   fake-ip-filter:
> >     - bbs.pku.edu.cn
> > ```
> 
> 问题已解决，将插件更新到最新版本，有专门的地方配置fake-ip-filter，覆写设置>DNS设置>Fallback-Filter勾上>Fake-IP-Filter勾上然后自定义

小白请教一下，自定义内容一般输入什么

**Comment by SheepAndWolf** [comment]
> > > 但是你访问FakeIP地址的包会先被openclash代理 你可以试一下 开fakeip模式 访问IPv6地址查询网站 你的本机IPv6地址会变成路由的地址 Redir-host返回的才是你本机的地址
> > 
> > 
> > 我目前的网络环境是纯V4，V6与OpenClash冲突（上次折腾V6，V6网站直接就连过去了，我调用OpenAI的API，然后号就被永封了，从此再也不碰V6了，反正也不玩PT，没这需求）
> > 我刚刚尝试加了filter，不知道是不是地方不对（全局设置>规则设置（访问控制）>自定义规则（访问控制）），还是没有效果
> > ```
> > dns:
> >   fake-ip-filter:
> >     - bbs.pku.edu.cn
> > ```
> 
> 问题已解决，将插件更新到最新版本，有专门的地方配置fake-ip-filter，覆写设置>DNS设置>Fallback-Filter勾上>Fake-IP-Filter勾上然后自定义

@liuyandashen 大佬，求教，能细说一下么，这个问题也困扰我好久了
