### ISSUE TITLE
国服英雄联盟支持

### ISSUE THREAD

**Issue by Ono99** [vernesong/OpenClash#1858]
使用了openclash之后，国服英雄联盟一直不稳定会断线，以及有时候会出现黑屏无法连回去的情况。

已经使用了redir-host 混合模式，请帮忙看下解决方案。

谢谢

**Comment by vernesong** [comment]
确定直连了吗

**Comment by aurorataro** [comment]
规则有问题，LOL客户端没有直连

**Comment by Ono99** [comment]
> 确定直连了吗

并不完全确认，可以看下规则。总是感觉不是太稳定，有现成的规则吗。

谢谢

**Comment by FKDXD** [comment]
如何设置联盟的规则直连？
