### ISSUE TITLE
不能观看Pluto TV ,  一直报错。

### ISSUE THREAD

**Issue by HZstd** [vernesong/OpenClash#1859]
报错：There was an error retrieving this content.        使用Shadowrocket和Clash x 都能正常使用pluto tv.  我推测是不是规则没加进去，直接用国内网访问去了，这个电视软件能看好多电视资源。

其他方面这个插件其他的非常强大，自从用了OpenClash，HBO Max， Disney +， Netflix，YouTube 再没报过错， 谢谢大佬们。

**Comment by 1104shark** [comment]
请问有没有圈x的pluto tv的规则 谢谢大佬
