### ISSUE TITLE
如何设置qbit 上传部分的流量不走梯子？

### ISSUE THREAD

**Issue by More500code** [vernesong/OpenClash#1860]
如题。用qbit下载东西的时候会有一部分种子需要用梯子的流量下载。之前没有设置上传分享的限制。一夜之间跑了1T机场流量 - -
应该如何设置才能避免这个问题呢？

**Comment by vernesong** [comment]
限制端口

**Comment by Mosney** [comment]
qbittorrent可以设置发起连接的端口范围，用clash的来源端口范围`SRC-PORT`来控制这部分流量
