### ISSUE TITLE
检测到CLASH内核崩溃 无限重启

### ISSUE THREAD

**Issue by cym422948** [vernesong/OpenClash#1863]
平台：X86  Lean的源码编译OpenWrt R21.10.1 OPENCLASH版本0.44.04-beta
以下为发生错误时的日志（倒序）
github.com/miekg/dns@v1.1.43/server.go:521 +0x485
created by github.com/miekg/dns.(*Server).serveUDP
	github.com/miekg/dns@v1.1.43/server.go:591 +0x185
github.com/miekg/dns.(*Server).serveUDPPacket(0xc0005ae120, 0xc000430cc0, {0xc000208200, 0x20, 0x200}, {0xcb38a0, 0xc0001be050}, 0xc000226120, {0x0, 0x0})
	github.com/miekg/dns@v1.1.43/server.go:651 +0x4da
github.com/miekg/dns.(*Server).serveDNS(0xc0005ae120, {0xc000208200, 0x20, 0xc0001e4778}, 0xc000370380)
	github.com/Dreamacro/clash/dns/server.go:34 +0x2f
github.com/Dreamacro/clash/dns.(*Server).ServeDNS(0xc000208200, {0xcb86c0, 0xc000370380}, 0xc000440480)
	github.com/Dreamacro/clash/dns/server.go:59 +0x151
github.com/Dreamacro/clash/dns.handlerWithContext(0xc000216240, 0xc000440480)
	github.com/Dreamacro/clash/dns/middleware.go:34 +0x179
github.com/Dreamacro/clash/dns.withHosts.func1.1(0xc0005fc6c0, 0xc000440480)
	github.com/Dreamacro/clash/dns/middleware.go:108 +0x37
github.com/Dreamacro/clash/dns.withFakeIP.func1.1(0xc0005fc6c0, 0xc000706390)
	github.com/Dreamacro/clash/dns/util.go:105 +0x175
github.com/Dreamacro/clash/dns.handleMsgWithFakeIP(0xc00020f2c0, 0xc000440480)
	github.com/Dreamacro/clash/component/fakeip/pool.go:44 +0x145
github.com/Dreamacro/clash/component/fakeip.(*Pool).Lookup(0xc00020f2c0, {0xc000706390, 0xe})
	github.com/Dreamacro/clash/component/fakeip/pool.go:124 +0x187
github.com/Dreamacro/clash/component/fakeip.(*Pool).get(0xc00020f2c0, {0xc000706390, 0xe})
	github.com/Dreamacro/clash/component/fakeip/cachefile.go:38 +0x7e
github.com/Dreamacro/clash/component/fakeip.(*cachefileStore).PutByIP(0xc0001be028, {0xc0008c2b10, 0xc0006a8b18, 0xe}, {0xc000706390, 0x7a7a6e632e6e6463})
	github.com/Dreamacro/clash/component/profile/cachefile/cache.go:79 +0x11b
github.com/Dreamacro/clash/component/profile/cachefile.(*CacheFile).PutFakeip(0xc0001be020, {0xc0008c2b10, 0x4, 0x4}, {0xc0008c2b20, 0xe, 0x10})
	go.etcd.io/bbolt@v1.3.6/db.go:819 +0x32b
go.etcd.io/bbolt.(*DB).Batch(0xc00039f200, 0xc0008bd100)
	go.etcd.io/bbolt@v1.3.6/db.go:741 +0x82
go.etcd.io/bbolt.(*DB).Update(0xafd300, 0xc0008bd100)
	github.com/Dreamacro/clash/component/profile/cachefile/cache.go:84 +0xa6
github.com/Dreamacro/clash/component/profile/cachefile.(*CacheFile).PutFakeip.func1(0xc000268000)
	go.etcd.io/bbolt@v1.3.6/bucket.go:304 +0x1a5
go.etcd.io/bbolt.(*Bucket).Put(0xc0008bd240, {0xc0008c2b10, 0x6, 0x4}, {0xc0008c2b20, 0x0, 0x10})
	go.etcd.io/bbolt@v1.3.6/cursor.go:369 +0x149
go.etcd.io/bbolt.(*Cursor).node(0xc000819870)
	go.etcd.io/bbolt@v1.3.6/node.go:77 +0x45
go.etcd.io/bbolt.(*node).childAt(0xc0008bd240, 0x2be)
	go.etcd.io/bbolt@v1.3.6/bucket.go:666 +0x1fa
go.etcd.io/bbolt.(*Bucket).node(0xc0008bd240, 0x1e6, 0xc000356230)
	go.etcd.io/bbolt@v1.3.6/node.go:171 +0x37c
go.etcd.io/bbolt.(*node).read(0xc0003562a0, 0x7f6073c08000)
	go.etcd.io/bbolt@v1.3.6/page.go:126
go.etcd.io/bbolt.(*leafPageElement).key(...)
	go.etcd.io/bbolt@v1.3.6/unsafe.go:27
go.etcd.io/bbolt.unsafeByteSlice(...)
goroutine 1394 [running]:
panic: runtime error: slice bounds out of range [::8589934590] with length 2147483647
2021-12-24 17:52:51 OpenClash 启动成功，请等待服务器上线！

**Comment by vernesong** [comment]
/etc/openclash/cache.db 删除重启

**Comment by cym422948** [comment]
> /etc/openclash/cache.db 删除重启

尝试无效 多方面寻找原因后发现使用订阅转换模板ACL4SSR online full后生成的配置文件一启动就崩溃 不适用订阅转换反而正常

**Comment by vernesong** [comment]
/etc/openclash/history 也清了，不行就卸载重启再重装

**Comment by 5ycloud** [comment]
近期此问题困扰很长时间，后来经过反复测试，发现就是更新新版后的Openclash在内存管理时溢出导致clash内核奔溃无限重启的，希望大佬能在后续版本优化解决。测试将openclash版本降级到OpenClash-0.44.06-beta版本替换Dev和tun内核文件后，问题解决！
