### ISSUE TITLE
Cannot filtrate traffic from telegram on Fakeip TUN pattern

### ISSUE THREAD

**Issue by Dabrit** [vernesong/OpenClash#1864]
## Device:     
R2C  

## Rom:   
DHDAXCW @ FusionWrt 20211201 R21.12.1 (2021-12-01) / LuCI Master (git-21.329.83689-00cb491)

## TUN kernel version:  
2021.11.08  

I started openclash normally and  in the yacd control panel - connections i can see all connection from my LAN devices's application but telegram.  
I've tried the same config.yaml file in other clash* such as cfa and its working well, not the rule problem.  
when i switch to enhance(增强)mode, it works well.

**Comment by vernesong** [comment]
tun mode will mark all traffic except the local dst, show me your firewall rules to confirm whether the traffic is hijacked by other rules
