### ISSUE TITLE
升级错误 Upgrading luci-app-openclash on root from 0.44.03-beta to 0.44.04-beta

### ISSUE THREAD

**Issue by Brianwho** [vernesong/OpenClash#1865]
opkg install *.ipk
Upgrading luci-app-openclash on root from 0.44.03-beta to 0.44.04-beta...
Collected errors:
 * pkg_run_script: package "luci-app-openclash" preinst script returned status 1.
 * preinst_configure: Aborting installation of luci-app-openclash.
 * opkg_install_cmd: Cannot install package luci-app-openclash.
 * 
使用 --force-depends 也不行
 opkg install *.ipk  --force-depends
Upgrading luci-app-openclash on root from 0.44.03-beta to 0.44.04-beta...
Collected errors:
 * pkg_run_script: package "luci-app-openclash" prerm script returned status 1.
 * prerm_upgrade_old_pkg: prerm script for package "luci-app-openclash" failed
 * opkg_install_cmd: Cannot install package luci-app-openclash.

**Comment by Brianwho** [comment]
型号 FriendlyElec NanoPi R2S 
架构 ARMv8 Processor rev 4 
固件版本 OpenWrt 21.02.1 r16325-88151b8303 / LuCI openwrt-21.02 branch git-21.340.48972-61cc3b1 

OpenWrt 官方系统，手动安装openclash

**Comment by vernesong** [comment]
卸载重装

**Comment by lingyunzhiss** [comment]
在 etc/下创建Openclash目录，再安装就可以解决。

**Comment by leafleave** [comment]
在 etc/下创建openclash目录,并设定权限为0777就可以了
