### ISSUE TITLE
openclash的yacd里的日志在刷新yacd之后就会消失。是不是就不占openwrt overlay空间了？

### ISSUE THREAD

**Issue by Karmylr** [vernesong/OpenClash#1868]
如题

**Comment by vernesong** [comment]
会占

**Comment by Karmylr** [comment]
> 会占

日志等级调回slient还会占吗？

**Comment by vernesong** [comment]
> > 会占
> 
> 日志等级调回slient还会占吗？

slient不会，有输出才会

**Comment by Karmylr** [comment]
> > > 会占
> > 
> > 
> > 日志等级调回slient还会占吗？
> 
> slient不会，有输出才会

是说已经刷出来的日志会不会因为调slient而被删除
