### ISSUE TITLE
错误: OpenClash 启动失败，尝试使用原始配置文件启动...

### ISSUE THREAD

**Issue by rayzhao-superman** [vernesong/OpenClash#1869]
![image](https://user-images.githubusercontent.com/76512978/147399738-48bb241c-90fc-4a1c-8401-de2f090c4789.png)
![image](https://user-images.githubusercontent.com/76512978/147399750-a1722066-c833-4d95-ab5f-c20159115b1b.png)

**Comment by vernesong** [comment]
地址内核直连访问不了，你可以手动下载放到/etc/openclash/rule_provider

**Comment by rayzhao-superman** [comment]
那直接下载访问，后期能在线更新么。或者有其他解决办法吗> 地址内核直连访问不了，你可以手动下载放到/etc/openclash/rule_provider

**Comment by vernesong** [comment]
编译新版本，自动帮你改cdn

**Comment by rayzhao-superman** [comment]
不会啊。哈哈😺> 编译新版本，自动帮你改cdn

**Comment by rayzhao-superman** [comment]
> 编译新版本，自动帮你改cdn

更新新版本后，问题解决了，规则可以获取到了，谢谢作者
