### ISSUE TITLE
能不能 Yacd Dashboard 检查到配置变化后，实时更新 Proxy Group 的 proxies 名字。

### ISSUE THREAD

**Issue by a8l1vy** [vernesong/OpenClash#187]
Yacd Dashboard 不管如何，都不刷新 Proxy Group 的 proxies 名字。
　　原先配置中
  -  name: Others
     type: select
     proxies:
       - DIRECT
       - Proxy
       - IPForeign
       - IPCN

　　首次打开配置文件读取一切正常，
　　发现配置不好，需要修改，
  -  name: Others
     type: select
     proxies:
       - Proxy
       - DIRECT

　　删除配置并重新导入（不管是在线导入还是本地导入）
　　Others被默认到DIRECT
　　在控制面板中可以选择Proxy，再次选择DIRECT，再次选择Proxy，这样才会生效。选一次当时不生效。
　　第一次这样点了三次后，1分钟之内生效了。过一会Others又被锁定到DIRECT。（debug的日志中就可以看到Others [ DIRECT ]   ）

　　而且，IPForeign 和 IPCN 一直存在。我在配置中都把这些组名字删除了。
　　即使我把Openclash删除，重启路由器，再安装Openclash，导入新配置依然是显示旧配置内部的组名字。

　　openwrt自编译：19.07.2
　　内核版本：4.14.171
　　编译只选择了openclash需要的依赖。还选择了字体，主题。其它都没有变动。

　　Openclash从IPK安装的
　　内核是20200223-66-gd7cdb7e（游戏模式的内核二，用的是fake-ip）
　　openclash: x86_64
　　fake-ip 增强
　　rule策略

　　已选择编译版本 | linux-amd64 | 上次检查更新时间 | 
　　处理器架构（PROC） | x86_64 | 处理器架构（OPKG） | x86_64
　　当前内核版本 | 20200223-66-gd7cdb7e | 当前客户端版本 | v0.36.7-beta
　　最新内核版本 | v0.18.0-3-gc4994d6 | 最新客户端版本 | v0.36.7-beta

　　好吧，我错了，在我花十几分钟编辑完刷新了一下 Yacd 和Dashboard 控制面板，发现组名字更新了。

　　能不能让　Yacd 和 Dashboard控制面板　检查到配置变化后，实时更新一下配置文件。
　　Openclash在默认主题 bootstrap 显示没有框框。
　　Openclash在主题 rosy 下，显示正常。
　　Openwrt 的主题 rosy ，在 Interfaces 界面设置里，框不够大，显示错位。（一直用 bootstrap ）
　　IPIFY已经查询不出来了。

**Comment by a8l1vy** [comment]
我改成redir-host，一直出现这个错误。有影响吗？
time="2020-03-02T12:24:59Z" level=debug msg="[DNS] response msg error: &dns.Msg{MsgHdr:dns.MsgHdr{Id:0x9ffa, Response:true, Opcode:0, Authoritative:false, Truncated:false, RecursionDesired:true, RecursionAvailable:true, Zero:false, AuthenticatedData:false, CheckingDisabled:false, Rcode:2}, Compress:false, Question:[]dns.Question{dns.Question{Name:\"44.78.144.219.in-addr.arpa.\", Qtype:0xc, Qclass:0x1}}, Answer:[]dns.RR(nil), Ns:[]dns.RR(nil), Extra:[]dns.RR(nil)}"

使用redir-host 或者tun，不启用【自定义上游DNS服务器】这个选项，什么页面都打不开。错误就是上面这个。配置里边编辑进去了 一样dns设置。

启用【自定义上游DNS服务器】选项，依然有上面这个错误，网页这些都可以打开了。

**Comment by vernesong** [comment]
控制面板读取配置是动态的，也就是说你每次进去都会刷新一次，你说的问题我还没有遇到，可以尝试在其他浏览器上确认，如果是代码的问题你可以去YACD的作者那边提下issue.
DNS设置Wiki里面都有推荐的模板，不影响访问的情况下，错误忽略即可

**Comment by a8l1vy** [comment]
感谢回复
