### ISSUE TITLE
v0.44.06版本第三方规则异常

### ISSUE THREAD

**Issue by jeffreymor** [vernesong/OpenClash#1879]
lhie1的规则之前是store.steampowered.com放到special规则集里直连的，前几天steam有波动后规则已经注释了这一行
![QQ截图20211228013557](https://user-images.githubusercontent.com/16572907/147495041-7b6afc24-e864-4b70-a462-9990c90d1215.jpg)
但是openclash这边还是会走直连，已经重复设置过第三方规则
![QQ截图20211228014127](https://user-images.githubusercontent.com/16572907/147495300-8b10e614-a64f-4c15-a52e-48891aeba121.jpg)
是没有正确的应用到最新的规则吗

**Comment by jeffreymor** [comment]
我又鼓捣了下，多次来回删除清空重新读取设置第三方规则，最后应该是正确用上了最新的规则了，store.steampowered.com没有再走直连了，请教一下如何定义重新设置第三方规则？今天我查看日志，规则自动更新后说不兼容没有再进行处理等待版本更新，然后更新到最新的版本后，第三方规则那边检测更新是一直是提示无更新的，然后后续就是无论怎么设置都有上面说的问题，是不是其中某一环出了问题导致最新的规则没有被应用上？

**Comment by vernesong** [comment]
provider需要单独更新，去控制面板刷新

**Comment by jeffreymor** [comment]
我找了下面板貌似没找到，不确定遗漏了哪个地方，麻烦详细说明一下感谢！

**Comment by jeffreymor** [comment]
刚找到面板规则页右侧有按钮可以更新

**Comment by 404user** [comment]
我的也是更新不了，规则全空了。请问是怎么解决的？
