### ISSUE TITLE
网页端Netflix的内容比ATV上面的多

### ISSUE THREAD

**Issue by lurne** [vernesong/OpenClash#1880]
如题，跟软件版本无关，观察了很多天依然如此

在浏览器中可以添加一些香港电影到我的片单及正常播放，但是ATV上面既无法搜到也看不到这些内容。各位大佬们，这会是哪里的问题呢

开启关闭流媒体增强也没有变化

**Comment by vernesong** [comment]
ATV只支持服务器采用IPV4的解锁节点

**Comment by lurne** [comment]
> 

诶，对噢。刚刚从日志，以及串流活动里发现这个事情了……

呃，大佬，这个有解么……

**Comment by lurne** [comment]
> ATV只支持服务器采用IPV4的解锁节点

诶，对噢。刚刚从日志，以及串流活动里发现这个事情了……

呃，大佬，这个有解么……

**Comment by lurne** [comment]
> 你可以试试用relay策略组，创建中继到机场的某个原生节点

现在这个已经是原生的了……

**Comment by vernesong** [comment]
要支持v4的才行啊

**Comment by lurne** [comment]
> 要支持v4的才行啊

收到！
