### ISSUE TITLE
遇到腾讯国际版wetv.vip不能解析

### ISSUE THREAD

**Issue by xhrzg2017** [vernesong/OpenClash#1885]
腾讯海外 wetv 服务器有国内ip、国外ip
配置文件 
#  WeTV
PROCESS-NAME,com.tencent.qqlivei18n
DOMAIN-SUFFIX,wetv.vip
DOMAIN-SUFFIX,wetvinfo.com
IP-CIDR,150.109.28.51/32,no-resolve

要求解析到海外ip,dns返回国内ip了
当返回国内ip就舍弃了国外ip，只有国外ip才有服务

如何正常写入 .ini保留海外ip，订阅转换方便

**Comment by xhrzg2017** [comment]
![image](https://user-images.githubusercontent.com/34803905/147634926-e10e941c-c5fa-41c0-a0f8-6988cd265d6c.png)

**Comment by xhrzg2017** [comment]
但同组的viu，爱奇艺都能打开海外版，问题在dns或clash判断的ip舍弃思路

**Comment by vernesong** [comment]
Fallback-Filter

**Comment by xhrzg2017** [comment]
关键是如何写入ini 文件内让openclash转换

**Comment by feng1992** [comment]
> Fallback-Filter
请教个fallback-Fliter的问题
1、在fallback-Filter中选择true时geoip判断国外域名使用fallback解析最快的，国内选择nameserver解析最快的是这个意思吗？

2、在fallback-Filter设置true并添加"+.google.com.hk"代表google.com.hk强制使用fallback吗？

3、如果在fallback-Filter中添加"+.*"是不是强制redir远程解析的意思？

**Comment by vernesong** [comment]
代理的情况下本身就是远程解析，你如果是redir模式请打开DNS设置里面的远程解析
或者fallback-filter，geoip false, 然后下面加域名
