### ISSUE TITLE
可以支持国旗emoji吗

### ISSUE THREAD

**Issue by jwstaceyOvO** [vernesong/OpenClash#1886]
同样的订阅在windows和android客户端可以显示国旗emoji，而openclash只能显示策略组的emoji却无法显示国旗emoji，只显示成两个字母。

**Comment by vernesong** [comment]
字体显示的原因跟插件无关

**Comment by jwstaceyOvO** [comment]
> 字体显示的原因跟插件无关

感谢解答，方便的话可以告诉我可能是哪方面的原因吗？因为策略组的emoji是可以正常显示的
![image](https://user-images.githubusercontent.com/38880537/147750636-585835ac-b208-4f3f-9e2f-28d3f468bfd7.png)

**Comment by vernesong** [comment]
https://chrome.google.com/webstore/detail/chromoji-emojis-for-googl/negakbijaemdgbhklopmghphgaeadmpo

**Comment by ariakeumi** [comment]
楼上的 Chromoji 遇到节点很多的时候渲染很慢，而且图标很糊，推荐下面这个 wemoji for Chrome 。

https://chrome.google.com/webstore/detail/twemoji-for-chrome/fopgafjdjlongoeblobbafbnapafcicg

**Comment by kingcard1131** [comment]
> 楼上的 Chromoji 遇到节点很多的时候渲染很慢，而且图标很糊，推荐下面这个 wemoji for Chrome 。
> 
> https://chrome.google.com/webstore/detail/twemoji-for-chrome/fopgafjdjlongoeblobbafbnapafcicg

赞！
