### ISSUE TITLE
自定义dns只要增加了ipv6 dns就无法启动

### ISSUE THREAD

**Issue by yugu91** [vernesong/OpenClash#1890]
<img width="772" alt="image" src="https://user-images.githubusercontent.com/10072650/147755870-732d6c3a-f123-496b-9150-5c034717724a.png">

很奇怪，ping6 也解析不到域名，只能ping 纯ipv6地址

**Comment by vernesong** [comment]
你怎么加的

**Comment by yugu91** [comment]
就是添加 nameserver 2400:3200:baba::1 协议选udp

**Comment by vernesong** [comment]
端口要加53
