### ISSUE TITLE
一键生成的配置文件报错

### ISSUE THREAD

**Issue by Dorbmon** [vernesong/OpenClash#1891]
`level=fatal msg="Parse config error: proxy group[0]: `use` or `proxies` missing"`

`
proxy-groups:
  - name: Auto - UrlTest
    type: url-test
    url: https://cp.cloudflare.com/generate_204
    interval: "600"
    tolerance: "150"
  - name: Proxy
    type: select
    proxies:
      - Auto - UrlTest
      - DIRECT
  - name: Domestic
    type: select
    proxies:
      - DIRECT
      - Proxy
  - name: Others
    type: select
    proxies:
      - Proxy
      - DIRECT
      - Domestic
  - name: Asian TV
    type: select
    proxies:
      - DIRECT
      - Proxy
  - name: Global TV
    type: select
    proxies:
      - Proxy
      - DIRECT
rules:
`

**Comment by vernesong** [comment]
节点加了没有
