### ISSUE TITLE
命令行开启或关闭openclash的指令（init.d关闭Openclash时可能出现的Bug）？或者clash能否支持本机上某一个程序指定为direct规则？

### ISSUE THREAD

**Issue by Calmact** [vernesong/OpenClash#1892]
如题
还有一个问题一直很感兴趣，在源码那一部分能够查询到Luci界面的按钮对应执行的脚本命令呢？

**Comment by Calmact** [comment]
https://docs.cfw.lbyczf.com/contents/ui/profiles/rules.html
PROCESS-NAME
规则总又一条叫做process-name，比如我希望python3调用的/ect/myProc/my.py 程序指定为direct规则，该如何实现呢？

**Comment by Calmact** [comment]
![image](https://user-images.githubusercontent.com/10005540/147813718-f2294fac-80b8-4c1e-81dc-b13e7814ec84.png)
本地运行的clash能捕捉到这两个命令的命令行么？

**Comment by Calmact** [comment]
![image](https://user-images.githubusercontent.com/10005540/147813929-a1ae4a04-954a-4010-a873-20349876c00b.png)
这条规则是不是只适用于windows的clash？在linux(openwrt)上连接信息里面好像没看到这方面描述

**Comment by Calmact** [comment]
![image](https://user-images.githubusercontent.com/10005540/147814737-20a2b188-11fa-4934-9e0a-3ab07855abfd.png)
通过/etc/init.d/openclash stop 或者start停止和开启openclash,开启start挺管用，但是停止stop似乎没能正常停止openclash，虽然命令行显示的已经Already Stop!，但是程序依然健在！！！
![image](https://user-images.githubusercontent.com/10005540/147814878-3cc2ad72-bf1b-497e-bb31-33f93b108cb3.png)

**Comment by Calmact** [comment]
enable=$(uci -q get openclash.config.enable)
这里可能有Bug？不太懂UCI和openwrt的luci编程，init.d停止程序里面先检测uci里面是否enable，再关闭openclash，也就是说只留了从uci关闭openclash的途径，但是其中守护程序和uci没啥关系，外部调用init.d stop，只关闭了守护程序。
是否这么运行更合理？
：
调用init.d/openclash stop以后，将enable修改为0，然后关闭openclash和守护进程？

**Comment by Calmact** [comment]
@vernesong

**Comment by Calmact** [comment]
也可能我的理解问题，命令行开启和关闭openclash的方法：
开启：
```Open
uci set openclash.config.enable='1'
uci commit
/etc/init.d/openclash start
```
关闭：
```stop
uci set openclash.config.enable='0'
uci commit
/etc/init.d/openclash stop
```

**Comment by Calmact** [comment]
开启停止命令的问题自产自销了[doge]，制定程序设置规则的问题希望大佬能指点下@vernesong

**Comment by vernesong** [comment]
process-name在openwrt上应该是没用的，需要内核适配

开启关闭就是你楼上的命令，先uci

**Comment by Calmact** [comment]
> process-name在openwrt上应该是没用的，需要内核适配
> 
> 开启关闭就是你楼上的命令，先uci

还有一个问题一直很感兴趣，在源码那一部分能够查询到Luci界面的按钮对应执行的脚本命令呢?
比如我想手动命令行触发让openwrt强制更新配置，相当于配置页面点应用配置按钮，该到源码哪里查找呢？想触类旁通

**Comment by LakeishaKowalczyk** [comment]
> 还有一个问题一直很感兴趣，在源码那一部分能够查询到Luci界面的按钮对应执行的脚本命令呢?
> 比如我想手动命令行触发让openwrt强制更新配置，相当于配置页面点应用配置按钮，该到源码哪里查找呢？想触类旁通

@Calmact 
你找到了吗，分享一下

@vernesong 
想通过命令行断开某个域名的连接，请问应该怎么做

**Comment by LakeishaKowalczyk** [comment]
研究了一下搞定了
以下是一个关闭 `example.com` 所有连接的示例，后来的朋友可参考

1. 编写脚本
    1. 安装 json 解析工具 `sudo apt-get install jq`
    2. 脚本
        ```
        #!/bin/bash
        
        # 获取所有与 host 为 "example.com" 相关的 id
        ids=$(curl -s -H 'Authorization: Bearer 123456' http://127.0.0.1:9090/connections | jq -r '.connections[] | select(.metadata.host == "example.com") | .id')
        
        # 遍历每个 id，并发送 DELETE 请求以关闭对应的连接
        for id in $ids; do
          echo "Closing connection with id: $id"
          curl -s -H 'Authorization: Bearer 123456' http://127.0.0.1:9090/connections/$id -X DELETE
        done
        
        echo "All related connections have been closed."
        ```
    3. 参考资料
        1. APIs - 虚空终端 Docs [链接](https://wiki.metacubex.one/api/)
        2. RESTful API [链接](https://clash.gitbook.io/doc/restful-api)
2. 创建并定时运行自定义脚本
    1. SSH 连接 `ssh root@192.168.1.11`
    2. 创建脚本文件
        1. `cd mkdir /usr/bin`
        2. `touch auto_delete_connections.sh`
    3. 编辑文件写入脚本 `vi auto_delete_connections.sh`
    4. 添加运行权限 `chmod +x auto_delete_connections.sh`
    5. 定时运行
        1. `crontab -e`
            1. 添加 `* * * * * /usr/bin/custom_cron_scripts/auto_delete_connections.sh`
        2. `logread | grep cron`
            1. 看到类似以下 log 输出说明运行正确（cron.err 不是错误）
                1. `cron.err crond[27147]: USER root pid 27988 cmd /usr/bin/custom_cron_scripts/auto_delete_connections.sh`
