### ISSUE TITLE
fallback-Fliter使用疑问请大佬指导下

### ISSUE THREAD

**Issue by feng1992** [vernesong/OpenClash#1896]
我redir-tun模式下，github代理不能访问，www.google.com可以访问，www.googl.com.hk不能访问，在fallback-Fliter添加了"+.github.com"和"+.google.com.hk"之后，访问google和github都正常了，所以对fallback-Fliter有了以下的疑问。

1、在fallback-Filter中选择true时geoip判断国外域名使用fallback解析最快的，国内选择nameserver解析最快的是这个意思吗？

2、在fallback-Filter设置true并添加"+.google.com.hk"代表google.com.hk强制使用fallback吗？

3、如果在fallback-Filter中添加"+.*"是不是强制远程解析？

**Comment by vernesong** [comment]
# If IP addresses resolved with servers in `nameservers` are in the specified
# subnets below, they are considered invalid and results from `fallback`
# servers are used instead.
#
# IP address resolved with servers in `nameserver` is used when
# `fallback-filter.geoip` is true and when GEOIP of the IP address is `CN`.
#
# If `fallback-filter.geoip` is false, results from `nameserver` nameservers
# are always used if not match `fallback-filter.ipcidr`.
#
# This is a countermeasure against DNS pollution attacks.

**Comment by fydeos-alpha** [comment]
The "fallback filter" description above confuses me, too. It was written in a somewhat obscured manner and IMHO lacked a pragmatic approach to cover all the scenarios. This issue has proven that I am not the only one. 

My understanding of what the fallback filter does (based on the description above):

 - With all DNS requests, DNS servers defined in `Nameservers` will be used first. However, if the response falls in `fallback-filter.ipcidr` then it's considered "polluted", we will then continue the DNS resolution with DNS servers defined in  `Fallback`.
 - If `fallback-filter.geoip` is set to `true`, then DNS servers defined in `Nameservers` will be used if the GEOIP of the resolved IP address is `CN` (and obviously does not fall into the `fallback-filter.ipcidr`)
 - If `fallback-filter.geoip` is set to `true`, then DNS servers defined in `Fallback` will be used if the GEOIP of the resolved IP address is not `CN` (and obviously does not fall into the `fallback-filter.ipcidr`)
 - If `fallback-filter.geoip` is set to `false`, then DNS servers defined in `Nameservers` will be used as long as the resolved IP is not "polluted".

Correct me if I am wrong for the above? 

Also there is no explanation about `fallback-filter.domain`, guess domains defined here will be forced with DNS servers defined in `Fallback`?
