### ISSUE TITLE
DNS疑问

### ISSUE THREAD

**Issue by kpictor** [vernesong/OpenClash#190]
已查阅wiki
在luci主页，建议采用UDP HTTP等多种方式查询DNS抗污染
在wikiDNS设置章节，写明自定义上游只支持一个DNS服务器

问：自定义上游确实只能有一个服务器吗
如果支持多个，填写多个可以获得和smartdns同样的效果吗
如果不支持，luci主页的建议是指yaml文件里面填写多类型服务器且luci停用自定义DNS上游吗

**Comment by vernesong** [comment]
只支持一个的是DNS高级设置里填的dns，自定义dns可以多个。
但nameserver组必须要有，如果你要用smartdns可以只在nameserver组添加一个127.0.0.1:6053。
推荐的dns设置wiki里也有

**Comment by kpictor** [comment]
感谢解答！
