### ISSUE TITLE
Dashboard 控制面板的连接里出现很多乱七八糟的ip

### ISSUE THREAD

**Issue by jerrykkkkk** [vernesong/OpenClash#1900]
如下图所示：
<img width="1914" alt="unknown-ip" src="https://user-images.githubusercontent.com/35962239/147877580-e657a144-57fb-489b-b15e-90d1e9523d18.PNG">
这些ip连的访问的地址会变，并不是固定的，但基本都是重复的
<img width="1096" alt="unknown-ip2" src="https://user-images.githubusercontent.com/35962239/147877625-05c7eaf2-67a2-4a95-882d-acbb5484f8f8.PNG">

**Comment by vernesong** [comment]
![image](https://user-images.githubusercontent.com/42875168/147893294-cbf56268-e774-46db-ae87-f8fd8bb36ba7.png)

**Comment by OUZYcn** [comment]
https://github.com/vernesong/OpenClash/issues/1910

**Comment by jerrykkkkk** [comment]
> ![image](https://user-images.githubusercontent.com/42875168/147893294-cbf56268-e774-46db-ae87-f8fd8bb36ba7.png)

谢谢，解决了 ，目前除了内网ip，多显示一个wan口ip
