### ISSUE TITLE
会造成openwrt假死

### ISSUE THREAD

**Issue by xufuren** [vernesong/OpenClash#1904]
用L大和li大的库，加入OC后，会造成openwrt系统运行极度缓慢，处理崩溃的边缘，刷好机后，web 仅能输入密码，进入后，点任何一个菜单都会崩溃。4125，I255网卡。不知道哪里冲突了。

**Comment by vernesong** [comment]
有任何日志或者进程占用证明这个情况吗

**Comment by XUANCUN** [comment]
同上，也出现了这个问题

**Comment by violarulan** [comment]
使用 esir 的固件同上，运行一段时间后出现，不定时出现，国内、国外、局域网都会出现偶发的 timeout，重启 openclash 会立即恢复
redir、redir(tun)、fakeip（tun）都会出现

目前自行编译了个只带 openclash 的运行三四天了，正常，楼上两位朋友可以试试 @XUANCUN @xufuren 
https://github.com/violarulan/openwrt/releases/tag/2022.01.02-0235

**Comment by violarulan** [comment]
> 使用 esir 的固件同上，运行一段时间后出现，不定时出现，国内、国外、局域网都会出现偶发的 timeout，重启 openclash 会立即恢复 redir、redir(tun)、fakeip（tun）都会出现
> 
> 目前自行编译了个只带 openclash 的运行三四天了，正常，楼上两位朋友可以试试 @XUANCUN @xufuren https://github.com/violarulan/openwrt/releases/tag/2022.01.02-0235

发现 fakeip 返回的地址有时候会与zerotier某网段路由重叠，把这个路由删掉目前一切正常了
