### ISSUE TITLE
跪求继续支持vmess，求回滚内核

### ISSUE THREAD

**Issue by wangjianpro999** [vernesong/OpenClash#1905]
求继续支持vmess。求回滚内核，机场用户节点全丢，求大佬回滚内核

**Comment by Karmylr** [comment]
支持vmess啊

**Comment by WYC-2020** [comment]
自己fork回滚就是了

**Comment by vernesong** [comment]
vmess什么配置，我这边正常

**Comment by st0ck5** [comment]
我这几个机场全都是vmess~ 昨天升级tun到2022.01.02版本 就直接废了~~~ 幸亏还有一台服务器内的文件没升级赶紧抓回来~2021.12.07的clash_tun

**Comment by st0ck5** [comment]
> vmess什么配置，我这边正常

你升级下 clash_tun 内核到0102 保证你哭~~~ 记得提前备份内核文件

**Comment by Karmylr** [comment]
> > vmess什么配置，我这边正常
> 
> 你升级下 clash_tun 内核到0102 保证你哭~~~ 记得提前备份内核文件

放心，升级到0102还是可以用v2ray的～～～只是你的机场用了不安全

**Comment by wangjianpro999** [comment]
千万别升级！你做得了自己的主，做不了机场的主。机场不更新你就别作死！

**Comment by st0ck5** [comment]
> 

是啊~~刚续了1年……我擦的~

**Comment by Passerby1011** [comment]
回滚内核就可以了用旧的把新的替换掉

**Comment by ly19811105** [comment]
> 千万别升级！你做得了自己的主，做不了机场的主。机场不更新你就别作死！

请问手里没有旧版怎么样回滚?我也是手贱点了升级,悲剧了几天了😂😂

**Comment by lurne** [comment]
> > 千万别升级！你做得了自己的主，做不了机场的主。机场不更新你就别作死！
> 
> 请问手里没有旧版怎么样回滚?我也是手贱点了升级,悲剧了几天了😂😂

自己去啊https://github.com/Dreamacro/clash/releases
