### ISSUE TITLE
怎么把国外域名和国外域名解析用的dns服务器分开?

### ISSUE THREAD

**Issue by Karmylr** [vernesong/OpenClash#1906]
如题

**Comment by vernesong** [comment]
fallback-filter

**Comment by OUZYcn** [comment]
> fallback-filter

顺便请教一下，这里应该的Geo-IP：CN 意思是CN之外、ipcidr 列表中，加上范例中如下的 域名 的走 “设置自定义上游DNS服务器（在上方设置中启用本功能后生效） ” 中 选择 服务器分组为 Fallback 的 DNS ？

```
domain:
    - "+.google.com"
    - "+.facebook.com"
    - "+.youtube.com"
    - "+.githubusercontent.com"
    - "+.googlevideo.com"
```

![image](https://user-images.githubusercontent.com/47710598/148035880-943828a0-10be-4117-a382-c223c06c36f4.png)
