### ISSUE TITLE
TUN 1.03 出了

### ISSUE THREAD

**Issue by OUZYcn** [vernesong/OpenClash#1909]
https://github.com/Dreamacro/clash/releases/tag/premium

感觉比1.02好用了。。。

**Comment by st0ck5** [comment]
不敢升了~ 谁给我讲讲有啥好的~

**Comment by OUZYcn** [comment]
> 不敢升了~ 谁给我讲讲有啥好的~

备份好了原文件再升级有啥可怕。。。

**Comment by wangjianpro999** [comment]
不敢升级了+1，除非兼容老版本的vmess机场
