### ISSUE TITLE
运行大约20分钟后报错重启openclash，但是重启时是可以启动成功的

### ISSUE THREAD

**Issue by wuyu12580** [vernesong/OpenClash#191]
运行日志：
panic: runtime error: slice bounds out of range [:16] with capacity 0

goroutine 10247 [running]:
github.com/sh4d0wfiend/go-shadowsocksr.(*SSTCPConn).doRead(0x13e0000, 0x1a44000, 0x5000, 0x5000, 0x1f4e058, 0x20661b0, 0x5ec020)
	/home/runner/go/pkg/mod/github.com/sh4d0wfiend/go-shadowsocksr@v0.0.0-20200218095529-0fd9f315b912/tcp.go:159 +0xb68
github.com/sh4d0wfiend/go-shadowsocksr.(*SSTCPConn).Read(0x13e0000, 0x1a44000, 0x5000, 0x5000, 0x0, 0x14f0740, 0x0)
	/home/runner/go/pkg/mod/github.com/sh4d0wfiend/go-shadowsocksr@v0.0.0-20200218095529-0fd9f315b912/tcp.go:87 +0x54
github.com/Dreamacro/clash/tunnel.(*tcpTracker).Read(0x14981f0, 0x1a44000, 0x5000, 0x5000, 0x0, 0x1902400, 0x1e39060)
	/home/runner/work/clashssr/clashssr/tunnel/tracker.go:37 +0x60
io.copyBuffer(0x6fd45df0, 0x1498170, 0x6fd45e08, 0x14981f0, 0x1a44000, 0x5000, 0x5000, 0x4cd8c0, 0x51dd60, 0x0, ...)
	/opt/hostedtoolcache/go/1.13.8/x64/src/io/io.go:402 +0x10c
io.CopyBuffer(0x6fd45df0, 0x1498170, 0x6fd45e08, 0x14981f0, 0x1a44000, 0x5000, 0x5000, 0x44fa08, 0x1024200, 0x14f07dc, ...)
	/opt/hostedtoolcache/go/1.13.8/x64/src/io/io.go:375 +0x7c
github.com/Dreamacro/clash/tunnel.relay.func1(0x5ee9a0, 0x1498170, 0x6fd45d60, 0x14981f0, 0x13d3400)
	/home/runner/work/clashssr/clashssr/tunnel/connection.go:122 +0x114
created by github.com/Dreamacro/clash/tunnel.relay
	/home/runner/work/clashssr/clashssr/tunnel/connection.go:120 +0x8c
2020-03-02 22:27:06 Watchdog: Clash Core Problem, Restart.

**Comment by vernesong** [comment]
内核的问题，你可以发日志向作者反馈

**Comment by wuyu12580** [comment]
好的
