### ISSUE TITLE
无法在公网访问局域网服务

### ISSUE THREAD

**Issue by brucmao** [vernesong/OpenClash#1912]
> 主路由梅林，旁路由OpenWRT,主路由已经开启了端口转发
> OpenWRT启用了AdGuardHome

出现的问题，外网无法通过域名或者ip 访问内网服务，tcping 域名 端口 可以ping 通

现在临时解决方法是：**openclash访问控制里面将 局域网ip加入黑名单，但是这样局域网就无法使用代理了**

# OpenWRT 设置如下

运行模式：Redir-Host(兼容)模式

代理模式：Rule【策略代理】

OpenWRT 防火墙禁用了53端口转发

~~~
#iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53
#iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53
~~~

OpenWRT DNS 设置如下

![image](https://user-images.githubusercontent.com/6119652/148155168-782691ca-acaf-4a8a-ab9a-993d1c702baa.png)

# AdGuardHome设置如下：

​     重定向53端口到AdGuardHome
​     上游 DNS 服务器：127.0.0.1:7874

**Comment by vernesong** [comment]
流量经过clash后进行NAT，你只能在主路由转发给旁路由，旁路由再转发一遍到设备

**Comment by brucmao** [comment]
在旁路由再转发一次确实可以了。
如果设置成主路由开启dhcp，旁路由关闭dhcp，应该就不需要再转发一次了。

**Comment by brucmao** [comment]
> 流量经过clash后进行NAT，你只能在主路由转发给旁路由，旁路由再转发一遍到设备

新问题，这样设置后，虽然在外网可以访问内网设备了，但是在内网又无法通过域名访问局域网设备，用ip可以。（已尝试在dns设置，指定（第二）DNS服务器，并加入自己的域名）

**Comment by brucmao** [comment]
最终完美解决方法 openclash -全局设置-模式设置 勾选下面的
**实验性：绕过中国大陆IP 启用后中国大陆流量将不再经过内核，提升系统性能**
这样也不用主路由再转发给旁路由了，内外网都可用通过域名访问

**Comment by LittleTurtle2333** [comment]
我也遇到了这个问题，听你的把绕过中国大陆ip开开就行，但是感觉这不是很好的办法

**Comment by LittleTurtle2333** [comment]
因为这样中国大陆的ip确实能通过公网访问内网服务了，但是如果是其他地区的ip还是访问不了

**Comment by LittleTurtle2333** [comment]
所以把这个绕过中国大陆iP开开也是治标不治本
