### ISSUE TITLE
关于添加直连域名规则一些疑问

### ISSUE THREAD

**Issue by aiwu12** [vernesong/OpenClash#1913]
nfmovies.com这个网站是只能中国ip直连访问,所以我在规则中添加并不使用代理，但是还是无法访问，passwall却没有问题，这是什么原因呢，我是这样配置的，- DOMAIN,nfmovies.com,🎯 全球直连

**Comment by aiwu12** [comment]
还有就是我使用访问控制中添加局域网中不代理的ip之后，也是打不开，正常ip不代理之后应该可以访问的

**Comment by vernesong** [comment]
调试日志里面有连接测试，看走哪个规则了

**Comment by aiwu12** [comment]
![image](https://user-images.githubusercontent.com/61082200/148339959-d2f24308-61f3-49f9-b14c-ca57ecc118bb.png)
控制面板显示是走直连

**Comment by aiwu12** [comment]
调试测试也不显示日志内容

**Comment by vernesong** [comment]
被污染成1.1.1.1了，换dns

**Comment by aiwu12** [comment]
感谢，学到了

**Comment by aiwu12** [comment]
![image](https://user-images.githubusercontent.com/61082200/148367921-b7add08b-e8fb-4e4f-bf22-5125446dbb0e.png)
刚才还行，现在又不行了
