### ISSUE TITLE
旁路路由形式部分客户端无法上网。

### ISSUE THREAD

**Issue by Silver-cybersec** [vernesong/OpenClash#1914]
我使用vmware桥接我得主机和刷了openclash得openwrt (fake-ip模式，IP为192.168.0.19)
<img width="703" alt="捕获4" src="https://user-images.githubusercontent.com/9884474/148163989-e349c232-530a-4287-a3ff-2bd5273c4800.PNG">
openwrt开启了本地dns劫持 并且没有限制lan得IP地址
<img width="678" alt="捕获5" src="https://user-images.githubusercontent.com/9884474/148164001-5f763dda-0d08-499b-9eae-33d2ac584306.PNG">
<img width="741" alt="捕获6" src="https://user-images.githubusercontent.com/9884474/148164017-4a9c3799-faff-47c9-8bde-fde8720eeff2.PNG">
虚拟机中一台linux主机（192.168.0.64）可以上网，另外一台终端无法进行上网。
<img width="511" alt="捕获" src="https://user-images.githubusercontent.com/9884474/148163935-197eec0a-dc41-4c54-b0e6-31e177e5b3b3.PNG">
从面板中看，捕捉到得流量也都是从192.168.0.74这台主机发出得。
<img width="766" alt="1101b9908da602d86088c9b7de6865c" src="https://user-images.githubusercontent.com/9884474/148163963-fdb94385-b2f3-424e-b64d-e690f244d45c.png">
内网中另一台机器IP为192.168.0.222，指向原网关（192.168.0.1）可以上网，指向（192.168.0.19）无法上网，两个主机配置方式均为修改网口协议为静态，手动配置IP，指定Gateway dns192.168.0.19.
<img width="502" alt="捕获3" src="https://user-images.githubusercontent.com/9884474/148164755-edcf45fd-e203-404b-a7ec-50a8eef85123.PNG">
不知道啥情况，求解答。

**Comment by lrgcx** [comment]
我的旁路由上openclash打开油管一直转圈，就是打不开。google可以打开。改用ssrp没问题。不知道怎么解决？

**Comment by Passerby1011** [comment]
openwrt有指向原网关吗？192.168.0.1

**Comment by lrgcx** [comment]
网关指向应该没问题，用ssrp都可以的。只是喜欢用openclash
