### ISSUE TITLE
v0.44.07中替换CDN的逻辑不正确会导致代理集下载失败

### ISSUE THREAD

**Issue by htfcuddles** [vernesong/OpenClash#1917]
代理集URL格式如下，使用了SSR转换API，参数部分引用了githubusercontent：
`https://api.xxx.com/sub?url=https://rss.xxx.com/link/xxx?config=https%3A%2F%2Fraw.githubusercontent.com%2Fxxx%2Fyyy%2Fmaster%2FCL4SSR_Online_NoAuto.ini`

在 1fb204f 提交中，以下代码将整个URL替换成 了jsdelivr开头导致Clash无法启动：
https://github.com/vernesong/OpenClash/blob/0b0e0a08b04b4ffc8301fe62a6010256a77dd3a1/luci-app-openclash/root/etc/init.d/openclash#L244-L247

**Comment by xaotag** [comment]
cdn 的修改导致 代理集无法成功更新
原地址：https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/YouTube.yaml
修改后：https://testingcf.jsdelivr.net/ACL4SSR/ACL4SSR@master/Clash/Providers/Ruleset/YouTube.yaml  
报错cdn报错 Failed to fetch version info for ACL4SSR.

**Comment by xaotag** [comment]
问题解决，使用这个。 cdn.jsdelivr.net/gh

**Comment by xaotag** [comment]
> > cdn 的修改导致 代理集无法成功更新 原地址：https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/YouTube.yaml 修改后：https://testingcf.jsdelivr.net/ACL4SSR/ACL4SSR@master/Clash/Providers/Ruleset/YouTube.yaml 报错cdn报错 Failed to fetch version info for ACL4SSR.
> 
> 怎么解决的呀？我在“Github 地址修改”使用内置的几个网址，规则集地址也是被替换成类似这样的网址 域名后缀缺少/gh，导致没法更新，如果使用自定义网址[https://testingcf.jsdelivr.net/gh/的话就会变成](https://testingcf.jsdelivr.net/gh/%E7%9A%84%E8%AF%9D%E5%B0%B1%E4%BC%9A%E5%8F%98%E6%88%90) 下面这样，也是无法更新。https://testingcf.jsdelivr.net/gh/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR@master/Clash/Providers/Ruleset/YouTube.yaml

我不是说了使用 `cdn.jsdelivr.net/gh`你咋就不听,离谱

**Comment by wuyuqq** [comment]
> > > cdn 的修改导致 代理集无法成功更新 原地址：https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/YouTube.yaml 修改后：https://testingcf.jsdelivr.net/ACL4SSR/ACL4SSR@master/Clash/Providers/Ruleset/YouTube.yaml 报错cdn报错 Failed to fetch version info for ACL4SSR.
> > 
> > 
> > 怎么解决的呀？我在“Github 地址修改”使用内置的几个网址，规则集地址也是被替换成类似这样的网址 域名后缀缺少/gh，导致没法更新，如果使用自定义网址[https://testingcf.jsdelivr.net/gh/的话就会变成](https://testingcf.jsdelivr.net/gh/%E7%9A%84%E8%AF%9D%E5%B0%B1%E4%BC%9A%E5%8F%98%E6%88%90) 下面这样，也是无法更新。https://testingcf.jsdelivr.net/gh/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR@master/Clash/Providers/Ruleset/YouTube.yaml
> 
> 我不是说了使用 `cdn.jsdelivr.net/gh`你咋就不听,离谱

可能是我固件或者插件问题吧，自定义更换网址后 是叠加，而不是替换。
![20230517212908](https://github.com/vernesong/OpenClash/assets/33753437/c1e46df1-3e07-498d-8442-7fa2bd3984d9)

![20230517212719](https://github.com/vernesong/OpenClash/assets/33753437/96267e86-f3d9-4c49-b8b9-7019a64dc794)

**Comment by xaotag** [comment]
> > > > cdn 的修改导致 代理集无法成功更新 原地址：https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/YouTube.yaml 修改后：https://testingcf.jsdelivr.net/ACL4SSR/ACL4SSR@master/Clash/Providers/Ruleset/YouTube.yaml 报错cdn报错 Failed to fetch version info for ACL4SSR.
> > > 
> > > 
> > > 怎么解决的呀？我在“Github 地址修改”使用内置的几个网址，规则集地址也是被替换成类似这样的网址 域名后缀缺少/gh，导致没法更新，如果使用自定义网址[https://testingcf.jsdelivr.net/gh/的话就会变成](https://testingcf.jsdelivr.net/gh/%E7%9A%84%E8%AF%9D%E5%B0%B1%E4%BC%9A%E5%8F%98%E6%88%90) 下面这样，也是无法更新。https://testingcf.jsdelivr.net/gh/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR@master/Clash/Providers/Ruleset/YouTube.yaml
> > 
> > 
> > 我不是说了使用 `cdn.jsdelivr.net/gh`你咋就不听,离谱
> 
> 可能是我固件或者插件问题吧，自定义更换网址后 是叠加，而不是替换。 ![20230517212908](https://user-images.githubusercontent.com/33753437/239288215-c1e46df1-3e07-498d-8442-7fa2bd3984d9.png)
> 
> ![20230517212719](https://user-images.githubusercontent.com/33753437/239288346-96267e86-f3d9-4c49-b8b9-7019a64dc794.png)

 我是手动替换的

**Comment by xaotag** [comment]
> > > > cdn 的修改导致 代理集无法成功更新 原地址：https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/YouTube.yaml 修改后：https://testingcf.jsdelivr.net/ACL4SSR/ACL4SSR@master/Clash/Providers/Ruleset/YouTube.yaml 报错cdn报错 Failed to fetch version info for ACL4SSR.
> > > 
> > > 
> > > 怎么解决的呀？我在“Github 地址修改”使用内置的几个网址，规则集地址也是被替换成类似这样的网址 域名后缀缺少/gh，导致没法更新，如果使用自定义网址[https://testingcf.jsdelivr.net/gh/的话就会变成](https://testingcf.jsdelivr.net/gh/%E7%9A%84%E8%AF%9D%E5%B0%B1%E4%BC%9A%E5%8F%98%E6%88%90) 下面这样，也是无法更新。https://testingcf.jsdelivr.net/gh/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR@master/Clash/Providers/Ruleset/YouTube.yaml
> > 
> > 
> > 我不是说了使用 `cdn.jsdelivr.net/gh`你咋就不听,离谱
> 
> 可能是我固件或者插件问题吧，自定义更换网址后 是叠加，而不是替换。 ![20230517212908](https://user-images.githubusercontent.com/33753437/239288215-c1e46df1-3e07-498d-8442-7fa2bd3984d9.png)
> 
> ![20230517212719](https://user-images.githubusercontent.com/33753437/239288346-96267e86-f3d9-4c49-b8b9-7019a64dc794.png)

 我是手动替换的

**Comment by wuyuqq** [comment]
> > > > > cdn 的修改导致 代理集无法成功更新 原地址：https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/YouTube.yaml 修改后：https://testingcf.jsdelivr.net/ACL4SSR/ACL4SSR@master/Clash/Providers/Ruleset/YouTube.yaml 报错cdn报错 Failed to fetch version info for ACL4SSR.
> > > > 
> > > > 
> > > > 怎么解决的呀？我在“Github 地址修改”使用内置的几个网址，规则集地址也是被替换成类似这样的网址 域名后缀缺少/gh，导致没法更新，如果使用自定义网址[https://testingcf.jsdelivr.net/gh/的话就会变成](https://testingcf.jsdelivr.net/gh/%E7%9A%84%E8%AF%9D%E5%B0%B1%E4%BC%9A%E5%8F%98%E6%88%90) 下面这样，也是无法更新。https://testingcf.jsdelivr.net/gh/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR@master/Clash/Providers/Ruleset/YouTube.yaml
> > > 
> > > 
> > > 我不是说了使用 `cdn.jsdelivr.net/gh`你咋就不听,离谱
> > 
> > 
> > 可能是我固件或者插件问题吧，自定义更换网址后 是叠加，而不是替换。 ![20230517212908](https://user-images.githubusercontent.com/33753437/239288215-c1e46df1-3e07-498d-8442-7fa2bd3984d9.png)
> > ![20230517212719](https://user-images.githubusercontent.com/33753437/239288346-96267e86-f3d9-4c49-b8b9-7019a64dc794.png)
> 
> 我是手动替换的

手动替换没问题，使用“GitHub地址修改”自动替换的话就会少/GH字节，目前停用地址替换功能 自定义规则集更新下载正常。
