### ISSUE TITLE
为什么我的 dns: enhanced-mode:  始终是 fake-ip ？

### ISSUE THREAD

**Issue by smallst** [vernesong/OpenClash#1918]
今天在配置页面切换 redir-host 后无法访问google， 查看了一下配置文件中 dns: enhance-mode: 是 fake-ip 
然后我试了将上传的配置文件中 dns: enhance-mode: 删掉/手动改成 redir-host ，然后应用配置后下载运行配置依然得到 enhanced-mode: fake-ip 。。。 好奇怪啊……

**Comment by vernesong** [comment]
redir模式的dns远程解析是通过fakeip实现的

**Comment by smallst** [comment]
ok，所以这不影响 redir模式的使用是吧
