### ISSUE TITLE
有可能 redir 和 fake-ip 模式共存吗？

### ISSUE THREAD

**Issue by Yixi** [vernesong/OpenClash#1919]
openclash 版本和所有内核版本均为最新版本。

网络拓扑为 openclash 在旁路由 （192.168.50.3)，开启DNS劫持，  adGuard 作为默认dns服务器在 192.168.50.9， adguardHome 上设置上游DNS 为旁路由 192.168.50.3

现在有下面的问题

使用 redir 模式时（打开了远程解析域名），感觉网页访问解析时明显变慢，有时候还会超时， UU加速器工作正常

使用Fake ip时，网页访问速度快，但玩游戏时偶尔掉线，且UU加速器工作偶尔不正常会掉线, 加速器路由模式和进程模式均一样

所以有没有可能其他机器使用 Fake ip 模式，需要玩游戏的台式机 ip 使用 redir 模式

**Comment by vernesong** [comment]
插件关闭劫持，分配50.9给下面设备

**Comment by Yixi** [comment]
试了一下，感觉更不正常了。。国外都打不开，或者报https错误。

插件关闭劫持的话，是不是需要设置 adguardHome 上游是 192.168,50.53:7874   是使用redir 和还是 fake ip呢

**Comment by vernesong** [comment]
adguardHome 上设置上游DNS 为旁路由 192.168.50.3, 所以需要ad去劫持DNS，转给clash的7874

**Comment by vernesong** [comment]
下游网关50.3，DNS 50.9

**Comment by Yixi** [comment]
感谢，我试试去掉openclash的劫持

**Comment by exlulu** [comment]
[dev] 当前内核版本 v1.9.0-7-gb1a639f，[TUN] 当前内核版本 2022.01.27，当前客户端版本 v0.44.16-beta，OPCLASH IP .1.3，ADGHOME IP .1.4，redir 模式或Fake ip 模式都是以下结果（非TUN和非混合）
OPCLASH开启劫持，ADGHOME上游为 .1.3时ADGH测试上游DNS提示服务器无法使用，但是网络能正常访问
OPCLASH关闭劫持，ADGHMOE上游为 .1.3时ADGH测试上游DNS正常，但是只能访问国内网站
OPCLASH关闭劫持，ADGHMOE上游为 .1.3:7874时ADGH测试上游DNS正常，但是什么网站都不能访问
