### ISSUE TITLE
OpenClash的lhie1 规则不兼容吗？

### ISSUE THREAD

**Issue by milkwwa** [vernesong/OpenClash#192]
使用lhie1 规则的时候，日志提示
time="2020-03-03T01:36:03+08:00" level=fatal msg="Parse config error: Rules[8504] [DOMAIN-SUFFIX,netflix.com,Netflix] error: proxy [Netflix] not found"

这个需要怎么处理？

**Comment by vernesong** [comment]
更新

**Comment by milkwwa** [comment]
> 更新

OpenClash已经是最新版本了
v0.36.7-beta

**Comment by vernesong** [comment]
奈飞的策略组指定一下

**Comment by cloudsben** [comment]
> 奈飞的策略组指定一下

没有理解,我也遇到同样问题
![image](https://user-images.githubusercontent.com/1283779/75841406-9faebe00-5e08-11ea-9e3d-4bc5c230e711.png)

**Comment by cloudsben** [comment]
我看了下, lhie1的配置文件和此项目的配置文件不一样
![image](https://user-images.githubusercontent.com/1283779/75841709-5dd24780-5e09-11ea-9414-d90a45421500.png)
![image](https://user-images.githubusercontent.com/1283779/75841734-6b87cd00-5e09-11ea-9974-3ed6e5fcd189.png)

**Comment by vernesong** [comment]
规则部分跟节点没关系，上传你自己的配置文件，在规则设置里面给各个规则制定策略组就行了
