### ISSUE TITLE
不能刷新订阅

### ISSUE THREAD

**Issue by aguero119** [vernesong/OpenClash#1922]
最新版本有没有遇到不能刷新订阅的?  
怎么点刷新按钮都不能生效.用的在线转换nodelist的url.

**Comment by vernesong** [comment]
cdn替换有点问题，可以编译dev解决

**Comment by aguero119** [comment]
> cdn替换有点问题，可以编译dev解决

有没有教程

**Comment by aguero119** [comment]
可以通过版本更新里的更新dev解决么?

**Comment by aguero119** [comment]
更新了最新的dev之后好像还是不行.

**Comment by aguero119** [comment]
但是我把配置文件删除后,重启openclash又可以下载订阅文件. 就是不能替换.

**Comment by aguero119** [comment]
> cdn替换有点问题，可以编译dev解决

感觉这个问题很奇怪,我放在gitee就可以更新,放在github就不能更新....难道更新这个还要过q?

**Comment by vernesong** [comment]
github一般是走代理

**Comment by aguero119** [comment]
以前更新规则都可以啊。。。

vernesong ***@***.***> 于 2022年1月10日周一 12:00写道：

**Comment by aguero119** [comment]
> github一般是走代理

我感觉是规则更新不了导致的,rule和proxy都更新不了,rule我尝试把一个放在国内网站就可以更新. 
所以应该不是替换的问题. 是网络的问题,但是我是开了openclash的情况下,怎么会更新不了呢?

**Comment by aguero119** [comment]
我看到github已经过代理了,但是还是不能更新.

**Comment by aguero119** [comment]
> cdn替换有点问题，可以编译dev解决

apt update

apt install build-essential ccache ecj fastjar file g++ gawk \
gettext git java-propose-classpath libelf-dev libncurses5-dev \
libncursesw5-dev libssl-dev python python2.7-dev python3 unzip wget \
python3-distutils python3-setuptools python3-dev rsync subversion \
swig time xsltproc zlib1g-dev curl

这样么?还是只是涉及-dev这几个?
