### ISSUE TITLE
关于流媒体增强自动解锁策略组获取问题？

### ISSUE THREAD

**Issue by feng1992** [vernesong/OpenClash#1923]
能不能不让自动获取解锁策略组？只允许关键词选择策略组解锁，这样的话大家的可操作性多一点。如果自动获取策略组有时候自己机场的节点匹配不到奈飞相关策略组中。
![Screenshot_20220107_195744](https://user-images.githubusercontent.com/26924963/148541014-04110669-a1c7-43bc-86b5-ca712944676d.jpg)

**Comment by vernesong** [comment]
自动获取就是根据规则实际分流的策略组去获取的，你按关键字匹配到其他策略组最后反而没有效果

**Comment by feng1992** [comment]
> 自动获取就是根据规则实际分流的策略组去获取的，你按关键字匹配到其他策略组最后反而没有效果

主要是，奈飞策略组里好多地区分组例如美国，香港。这样的话自动解锁会跳地区（有时候节点解锁不好），这样有啥好的方法吗？只能自己修改奈飞策略组吗？

**Comment by vernesong** [comment]
最好是自己修改，不行就自己改脚本吧，在其上再实现节点筛选，过程太漫长和复杂
