### ISSUE TITLE
无法劫持chromecast的udp://8.8.8.8(4.4)

### ISSUE THREAD

**Issue by sakuyamaij** [vernesong/OpenClash#1924]
### 环境
主路由：ROS
旁路由：OpenWrt + Openclash (FakeIP增强 + UDP转发关闭)

### 现象：
通过clash日志观察chromecast设备的解析记录
发现chromecast刚开机时域名通过clash解析，运行一段时间后就只有IP记录。此时youtube等大概率出现异常无法观看。
![openclash.jpg](https://s2.loli.net/2022/01/07/YsazFNjfxGp6qrE.jpg)

在主路由ROS中查看连接，发现有chromecast访问udp://8.8.8.8(4.4)的记录
![ros.jpg](https://s2.loli.net/2022/01/07/lbw7xI6oa1cHdqt.jpg)

此时openwrt的iptables状态如下图
![iptable.jpg](https://s2.loli.net/2022/01/07/9YAxXNMiFkLeab3.jpg)

### 无责任推测：
chromecast开机时有用tcp://8.8.8.8(4.4)来查询dns，所以被正常劫持，clash中也可以看到解析记录。
随后chromecast开始用udp来查询dns，此时由于clash没有劫持到dns，所以日志中只留下了ip记录，访问也出现了异常

**Comment by sakuyamaij** [comment]
> 用tun

谢谢，已解决。

**Comment by assist726** [comment]
> > 用tun
> 
> 谢谢，已解决。

@sakuyamaij @vernesong  我这边切换到TUN模式依旧Chromecast的Youtube无法连接, Netflix 正常,其他配置全部默认

请问是还需要设置什么DNS配置么?

**Comment by vernesong** [comment]
我这边混合模式也正常
