### ISSUE TITLE
openclash支持小米mini 路由吗？

### ISSUE THREAD

**Issue by jerrykkkkk** [vernesong/OpenClash#1925]
小米路由mini 即 R1C，是可以刷openwrt的

想问下，可以安装openclash吗？应该是哪个架构？（下图来自R2S截图，R1C还没有刷机）
<img width="130" alt="2022-01-07_213154" src="https://user-images.githubusercontent.com/35962239/148551642-6d5569ac-8ab4-4515-868e-f88720e339eb.png">

**Comment by zh2209645** [comment]
MT7620A处理器 选mipsle-softfloat

**Comment by jerrykkkkk** [comment]
> MT7620A处理器 选mipsle-softfloat

谢谢
