### ISSUE TITLE
启动失败

### ISSUE THREAD

**Issue by wangjianpro999** [vernesong/OpenClash#1928]
![Screenshot_2022-01-08-09-12-09-365_com microsoft emmx](https://user-images.githubusercontent.com/79621192/148625701-9219670d-264c-4e0d-a1d9-f7b9fe425711.jpg)

![Screenshot_2022-01-08-09-06-09-832_com microsoft emmx](https://user-images.githubusercontent.com/79621192/148625707-39a7ea43-0cc1-41bc-a43c-8686bd61d92c.jpg)

![Screenshot_2022-01-08-08-56-47-191_com microsoft emmx](https://user-images.githubusercontent.com/79621192/148625724-02ea5a97-79b2-4aa2-92cc-f60b05c36f52.jpg)

**Comment by vernesong** [comment]
节点名字不匹配，检查配置文件

**Comment by wangjianpro999** [comment]
> 节点名字不匹配，检查配置文件

ok，果然是，不好意思，感谢您
