### ISSUE TITLE
希望添加流量记录与可视化功能

### ISSUE THREAD

**Issue by sunjx97** [vernesong/OpenClash#1933]
希望添加流量记录与可视化功能，可以按时/天/月记录局域网内各个ip的直连/代理流量，并支持可视化观察流量变化趋势。

**Comment by vernesong** [comment]
https://lancellc.gitbook.io/clash/start-clash/using-clash-tracing

**Comment by rheatin** [comment]
> https://lancellc.gitbook.io/clash/start-clash/using-clash-tracing

他的traffic好像没有那么细化，从websocket看...（也有可能我没用好😳
