### ISSUE TITLE
lede系统路由器无法从源更新，是证书问题，求解决方法。

### ISSUE THREAD

**Issue by stingzou** [vernesong/OpenClash#1934]
`root@LEDE:/tmp# opkg update
Downloading https://openwrt.proxy.ustclug.org/snapshots/targets/mvebu/cortexa9/packages/Packages.gz
*** Failed to download the package list from https://openwrt.proxy.ustclug.org/snapshots/targets/mvebu/cortexa9/packages/Packages.gz

Downloading https://openwrt.proxy.ustclug.org/snapshots/packages/arm_cortex-a9_vfpv3/base/Packages.gz
*** Failed to download the package list from https://openwrt.proxy.ustclug.org/snapshots/packages/arm_cortex-a9_vfpv3/base/Packages.gz

Downloading https://openwrt.proxy.ustclug.org/snapshots/packages/arm_cortex-a9_vfpv3/luci/Packages.gz
*** Failed to download the package list from https://openwrt.proxy.ustclug.org/snapshots/packages/arm_cortex-a9_vfpv3/luci/Packages.gz

Downloading https://openwrt.proxy.ustclug.org/snapshots/packages/arm_cortex-a9_vfpv3/packages/Packages.gz
*** Failed to download the package list from https://openwrt.proxy.ustclug.org/snapshots/packages/arm_cortex-a9_vfpv3/packages/Packages.gz

root@LEDE:/tmp# opkg update
Downloading https://openwrt.proxy.ustclug.org/snapshots/targets/mvebu/cortexa9/packages/Packages.gz
*** Failed to download the package list from https://openwrt.proxy.ustclug.org/snapshots/targets/mvebu/cortexa9/packages/Packages.gz

Downloading https://openwrt.proxy.ustclug.org/snapshots/packages/arm_cortex-a9_vfpv3/base/Packages.gz
*** Failed to download the package list from https://openwrt.proxy.ustclug.org/snapshots/packages/arm_cortex-a9_vfpv3/base/Packages.gz

Downloading https://openwrt.proxy.ustclug.org/snapshots/packages/arm_cortex-a9_vfpv3/luci/Packages.gz
*** Failed to download the package list from https://openwrt.proxy.ustclug.org/snapshots/packages/arm_cortex-a9_vfpv3/luci/Packages.gz

Downloading https://openwrt.proxy.ustclug.org/snapshots/packages/arm_cortex-a9_vfpv3/packages/Packages.gz
*** Failed to download the package list from https://openwrt.proxy.ustclug.org/snapshots/packages/arm_cortex-a9_vfpv3/packages/Packages.gz

Downloading https://openwrt.proxy.ustclug.org/snapshots/packages/arm_cortex-a9_vfpv3/routing/Packages.gz
*** Failed to download the package list from https://openwrt.proxy.ustclug.org/snapshots/packages/arm_cortex-a9_vfpv3/routing/Packages.gz

Downloading https://openwrt.proxy.ustclug.org/snapshots/packages/arm_cortex-a9_vfpv3/telephony/Packages.gz
*** Failed to download the package list from https://openwrt.proxy.ustclug.org/snapshots/packages/arm_cortex-a9_vfpv3/telephony/Packages.gz

Collected errors:
 * opkg_download: Failed to download https://openwrt.proxy.ustclug.org/snapshots/targets/mvebu/cortexa9/packages/Packages.gz, wget returned 5.
 * opkg_download: Failed to download https://openwrt.proxy.ustclug.org/snapshots/packages/arm_cortex-a9_vfpv3/base/Packages.gz, wget returned 5.
 * opkg_download: Failed to download https://openwrt.proxy.ustclug.org/snapshots/packages/arm_cortex-a9_vfpv3/luci/Packages.gz, wget returned 5.
 * opkg_download: Failed to download https://openwrt.proxy.ustclug.org/snapshots/packages/arm_cortex-a9_vfpv3/packages/Packages.gz, wget returned 5.
 * opkg_download: Failed to download https://openwrt.proxy.ustclug.org/snapshots/packages/arm_cortex-a9_vfpv3/routing/Packages.gz, wget returned 5.
 * opkg_download: Failed to download https://openwrt.proxy.ustclug.org/snapshots/packages/arm_cortex-a9_vfpv3/telephony/Packages.gz, wget returned 5.`

然后wget文件时也是报错：

`root@LEDE:/tmp# wget https://openwrt.proxy.ustclug.org/snapshots/targets/mvebu/cortexa9/packages/Packages.gz
--2022-01-08 21:38:29--  https://openwrt.proxy.ustclug.org/snapshots/targets/mvebu/cortexa9/packages/Packages.gz
Resolving openwrt.proxy.ustclug.org... 2400:ddc0:1000::6417:bae0, 192.109.232.118
Connecting to openwrt.proxy.ustclug.org|2400:ddc0:1000::6417:bae0|:443... connected.
ERROR: cannot verify openwrt.proxy.ustclug.org's certificate, issued by 'CN=R3,O=Let\'s Encrypt,C=US':
  Issued certificate has expired.
To connect to openwrt.proxy.ustclug.org insecurely, use `--no-check-certificate'.`

求助，这问题咋解决，我现在无法安装任何软件。

**Comment by OUZYcn** [comment]
To connect to openwrt.proxy.ustclug.org insecurely, use --no-check-certificate'.`

**Comment by zhangguanzhang** [comment]
我curl 了下这个域名，发现证书没过期，如果不是CDN就是你的https被劫持了，你换个节点试试
