### ISSUE TITLE
求加上改代理配置的脚本可视化一键操作

### ISSUE THREAD

**Issue by wangjianpro999** [vernesong/OpenClash#1935]
求在新版本里加上改代理配置的脚本可视化一键操作！！跪求！否则多节点手动修改是噩梦，而且一旦订阅又得再一个个改

把openclash代理配置中的
```
ws-path: /xxx
ws-headers: xxx
```
更改为
```
ws-opts:
  path: "/xxx"
  headers: xxx
```

_Originally posted by @Suwmlee in https://github.com/vernesong/OpenClash/issues/1903#issuecomment-1004145282_

**Comment by Passerby1011** [comment]
回滚解决所有问题

**Comment by wangjianpro999** [comment]
> 回滚解决所有问题

当然知道，但是今后都不能更新也是个大问题

**Comment by Passerby1011** [comment]
可以选个订阅转换，好像有的转换是支持1.9的
