### ISSUE TITLE
启动后无法连接外网

### ISSUE THREAD

**Issue by rambo0827** [vernesong/OpenClash#194]
添加AAEX的Calsh托管服务报错后无法启动，我手工添加一个HK节点后可以成功启动，但总是无法连接外网，baidu都可以访问，但是Google测试就是无法连接，总感觉我哪里犯了一个简单错误，但不知道是哪里
![image](https://user-images.githubusercontent.com/61268299/75843804-1c449b00-5e0f-11ea-8dd5-37cfc4f44fff.png)
<img width="1049" alt="Clash" src="https://user-images.githubusercontent.com/61268299/75843830-31b9c500-5e0f-11ea-8f93-1a3a9364727d.PNG">

**Comment by rambo0827** [comment]
<img width="1049" alt="Clash" src="https://user-images.githubusercontent.com/61268299/75843873-5ada5580-5e0f-11ea-979b-119622eec677.PNG">

**Comment by vernesong** [comment]
对照wiki检查

**Comment by rambo0827** [comment]
谢谢帮助，但啥是wiki呀？去哪里看呀？

**Comment by vernesong** [comment]
https://github.com/vernesong/OpenClash/wiki/%E7%BD%91%E7%BB%9C%E8%BF%9E%E6%8E%A5%E5%BC%82%E5%B8%B8%E6%97%B6%E6%8E%92%E6%9F%A5%E5%8E%9F%E5%9B%A0
