### ISSUE TITLE
Relay策略组不可用

### ISSUE THREAD

**Issue by cmbs2019** [vernesong/OpenClash#1940]
更新之后relay策略组不可用
所有依赖均已安装，配置文件在clash for android和clash for windows下relay策略组均可用
在openclash下不可用，延迟一直超时
之前旧版本是可用的，请帮忙分析

relay节点配置如下：
- name: Relay
  type: relay
  proxies:
  - Before
  - After
- name: Before
  type: select
  proxies:
  - "\U0001F1ED\U0001F1F0 HK"
  - "\U0001F1ED\U0001F1F0 HH"
  - "\U0001F1F8\U0001F1EC SG"
  - "\U0001F1FA\U0001F1F8 US"
  - "\U0001F1FA\U0001F1F8 NF"
  - "\U0001F1EF\U0001F1F5 JP-AZURE"
  - "\U0001F1ED\U0001F1F0 HK-GCP"
  - "\U0001F1F8\U0001F1EC SG-GCP"
  - "\U0001F1ED\U0001F1F0 HK-AZURE"
  - "\U0001F1FA\U0001F1F8 just1"
  - "\U0001F1FA\U0001F1F8 just2"
  - "\U0001F1FA\U0001F1F8 just3"
  - "\U0001F1FA\U0001F1F8 just4"
  - "\U0001F1FA\U0001F1F8 just5"
- name: After
  type: select
  proxies:
  - "\U0001F1ED\U0001F1F0 HK"
  - "\U0001F1ED\U0001F1F0 HH"
  - "\U0001F1F8\U0001F1EC SG"
  - "\U0001F1FA\U0001F1F8 US"
  - "\U0001F1FA\U0001F1F8 NF"
  - "\U0001F1EF\U0001F1F5 JP-AZURE"
  - "\U0001F1ED\U0001F1F0 HK-GCP"
  - "\U0001F1F8\U0001F1EC SG-GCP"
  - "\U0001F1ED\U0001F1F0 HK-AZURE"
  - "\U0001F1FA\U0001F1F8 just1"
  - "\U0001F1FA\U0001F1F8 just2"
  - "\U0001F1FA\U0001F1F8 just3"
  - "\U0001F1FA\U0001F1F8 just4"
  - "\U0001F1FA\U0001F1F8 just5"

OpenClash 调试日志

生成时间: 2022-01-11 11:16:06
插件版本: v0.44.09-beta
隐私提示: 上传此日志前请注意检查、屏蔽公网IP、节点、密码等相关敏感信息

```

#===================== 系统信息 =====================#

主机型号: Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz : 4 Core 4 Thread
固件版本: OpenWrt SNAPSHOT r0-8efdb24e
LuCI版本: git-21.335.48743-5f363d9-1
内核版本: 5.4.162
处理器架构: x86_64

#此项有值时,如不使用IPv6,建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: 

#此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 127.0.0.1#7874

#===================== 依赖检查 =====================#

dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
iptables-mod-tproxy: 已安装
kmod-ipt-tproxy: 已安装
iptables-mod-extra: 已安装
kmod-ipt-extra: 已安装
libcap: 已安装
libcap-bin: 已安装
ruby: 已安装
ruby-yaml: 已安装
ruby-psych: 已安装
ruby-pstore: 已安装
ruby-dbm: 已安装
kmod-tun(TUN模式): 已安装
luci-compat(Luci-19.07): 已安装

#===================== 内核检查 =====================#

运行状态: 运行中
进程pid: 17939
运行权限: 17939: cap_dac_override,cap_net_bind_service,cap_net_admin,cap_net_raw,cap_sys_resource=eip
运行用户: nobody
已选择的架构: linux-amd64

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 2022.01.02
Tun内核文件: 存在
Tun内核运行权限: 正常

Dev内核版本: 
Dev内核文件: 不存在
Dev内核运行权限: 否

#===================== 插件设置 =====================#

当前配置文件: /etc/openclash/config/AZ8T.yaml
启动配置文件: /etc/openclash/AZ8T.yaml
运行模式: fake-ip-mix
默认代理模式: rule
UDP流量转发(tproxy): 停用
DNS劫持: 启用
自定义DNS: 停用
IPV6代理: 启用
IPV6-DNS解析: 停用
禁用Dnsmasq缓存: 停用
自定义规则: 停用
仅允许内网: 停用
仅代理命中规则流量: 启用
仅允许常用端口流量: 停用
绕过中国大陆IP: 停用
DNS远程解析: 启用

#启动异常时建议关闭此项后重试
混合节点: 停用
保留配置: 停用

#启动异常时建议关闭此项后重试
第三方规则: 停用

**Comment by cmbs2019** [comment]
emmmm，没有人遇到相同情况么，win下和Android下的客户端，同配置relay都是可用的，在OP下不行，emmmm

**Comment by aueu** [comment]
看下跟这个是否是同问题

#1916

**Comment by cmbs2019** [comment]
> 看下跟这个是否是同问题
> 
> #1916

是的，这是一个相同问题，请问我该如何去避免这个问题，如果把服务器都改成IP格式有些太麻烦，而且IP会经常变动

**Comment by aueu** [comment]
> > 看下跟这个是否是同问题
> > #1916
> 
> 是的，这是一个相同问题，请问我该如何去避免这个问题，如果把服务器都改成IP格式有些太麻烦，而且IP会经常变动

你可以试试这里提到的 Nightly premium-2022-01-11T16:40+00:00，我没有测试

https://github.com/Dreamacro/clash/issues/1901

**Comment by cmbs2019** [comment]
> 

这个应该如何在openclash下替换呢？

**Comment by cmbs2019** [comment]
> > > 看下跟这个是否是同问题
> > > #1916
> > 
> > 
> > 是的，这是一个相同问题，请问我该如何去避免这个问题，如果把服务器都改成IP格式有些太麻烦，而且IP会经常变动
> 
> 你可以试试这里提到的 Nightly premium-2022-01-11T16:40+00:00，我没有测试
> 
> [Dreamacro/clash#1901](https://github.com/Dreamacro/clash/issues/1901)

请问，知己替换为dev内核吗？/etc/openclash/core/clash
