### ISSUE TITLE
更新出问题

### ISSUE THREAD

**Issue by AlasJiahui** [vernesong/OpenClash#1941]
自编译lean版lede，linux内核5.10、5.15、5.4.162更新客户端版本后，openclash直接消失，但是之前编译的linux内核为5.4.143的lede，没有这个问题，出现该情况的不止我一个

**Comment by OUZYcn** [comment]
kiddin9 的这个版本没有任何问题，我自己编译的官方21.02 branch也没问题
OpenWrt 01.11.2022 by Kiddin' / LuCI openwrt-21.02 branch git-13df80d
--

**Comment by AlasJiahui** [comment]
问题已解决，编译时勾选openclash不会自动选择ca-certificates，需要在base system中手动勾选
