### ISSUE TITLE
开启OPENCLASH后，内网环境下用域名访问无法访问内网服务

### ISSUE THREAD

**Issue by oreoleeus** [vernesong/OpenClash#1944]
如题，也就是说NAT环回失效了，在外网用域名访问就正常，关闭OPENCALSH后也正常，只要打开OPENCLASH，NAT环回就失效

**Comment by vernesong** [comment]
可以尝试使用DNS高级设置

**Comment by oreoleeus** [comment]
> 
谢谢大神回复，已经解决了，是我的机场的配置文件有问题导致的应该是，我换了一个第三方的配置就好了，感谢
