### ISSUE TITLE
为什么以前支持udp现在不支持了？

### ISSUE THREAD

**Issue by wangjianpro999** [vernesong/OpenClash#1946]
![Screenshot_2022-01-12-13-05-31-925_com microsoft emmx](https://user-images.githubusercontent.com/79621192/149067234-6c3d9851-40ae-457e-b4d1-8b4b92667390.jpg)

以前各模式都支持udp转发，现在都不支持了？机场还是那个机场，没变化呀，配置还是那个配置也。没变化呀。求各位大神指导

**Comment by vernesong** [comment]
最近内核的UDP不太稳定

**Comment by Rakau** [comment]
我记得增强模式支持，TUN开了也不走
