### ISSUE TITLE
tun模式下B站直播会启动大量端口

### ISSUE THREAD

**Issue by WinnieJiangHW** [vernesong/OpenClash#1948]
tun模式下B站直播会启动大量端口
![image](https://user-images.githubusercontent.com/57868812/149156121-68f0bc8f-123c-4f0a-b17b-a43fb4a4b40b.png)
增强模式无此问题，但由于安装了docker，增强模式下游戏延迟异常
观看直播一段时间后，其他网页无法打开

**Comment by WinnieJiangHW** [comment]
#===================== 插件设置 =====================#

当前配置文件: /etc/openclash/config/zcssr.yaml
启动配置文件: /etc/openclash/zcssr.yaml
运行模式: fake-ip-mix
默认代理模式: rule
UDP流量转发(tproxy): 停用
DNS劫持: 启用
自定义DNS: 停用
IPV6代理: 停用
IPV6-DNS解析: 停用
禁用Dnsmasq缓存: 停用
自定义规则: 停用
仅允许内网: 停用
仅代理命中规则流量: 停用
仅允许常用端口流量: 停用
绕过中国大陆IP: 停用
DNS远程解析: 启用

#启动异常时建议关闭此项后重试
混合节点: 停用
保留配置: 停用

#启动异常时建议关闭此项后重试
第三方规则: 停用

**Comment by liofoil** [comment]
不是tun也会启用的，这个应该是b站网页版在看直播时候会发生的事，把用户当cdn。。。

**Comment by paladin4fan** [comment]
这个是B站开启P2P上传
我一开始看域名还以为是弹幕池
会出现这个域名大概是你是fake-ip模式
你需要让这个域名避免走插件
