### ISSUE TITLE
日志有大量的信息如下：

### ISSUE THREAD

**Issue by osxdiy** [vernesong/OpenClash#195]
level=warning msg="dial Domestic error: dial tcp4 X.X.X.X:9999: connect: connection refused"

**Comment by osxdiy** [comment]
查了一下：只走TCP UDP不走

**Comment by jediseed** [comment]
我也是遇到了这个问题，不知是否跟你一样，使用的是0.367+clashr+acl4ssr，油管网站可以登陆但是视频无法播放，报错代码和你的一样。

**Comment by osxdiy** [comment]
我估计是规则出了问题，我的是PPPOE取的电信的局端的公网地址connection refused，主要是不懂才问的，代理没有问题，有时无法代理，过一会儿好了，这有可能是机场节点的出了问题。

**Comment by jediseed** [comment]
我刚刚重置了ADguard,关闭安全搜索后正常了，原来我的日志是只要出现 dial tcp4 X.X.X.X:8001: connect: connection refused"就无法翻，而且IP地址都是一样的东莞地址。现在反而不确定跟你的是不是一个原因造成的。

**Comment by osxdiy** [comment]
在多拨的情况下：
wan_ip4=$(ubus call network.interface.wan status 2>/dev/null | grep \"address\" | grep -oE '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' 2>/dev/null)
多个接口的地址如何获取的

**Comment by vernesong** [comment]
> 在多拨的情况下：
> wan_ip4=$(ubus call network.interface.wan status 2>/dev/null | grep "address" | grep -oE '[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}' 2>/dev/null)
> 多个接口的地址如何获取的

我这边没有多拨环境，你可以反馈生效的代码

**Comment by osxdiy** [comment]
问题是多拨的造成的，我现在用最笨的办法在加了四个WAN口，因为不会写代码，批量获取地址的UCI代码不会写
wan_ip4=$(ubus call network.interface.wan status 2>/dev/null | grep \"address\" | grep -oE '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' 2>/dev/null)
    wan1_ip4=$(ubus call network.interface.vwan1 status 2>/dev/null | grep \"address\" | grep -oE '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' 2>/dev/null)
    wan2_ip4=$(ubus call network.interface.vwan2 status 2>/dev/null | grep \"address\" | grep -oE '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' 2>/dev/null)
    wan3_ip4=$(ubus call network.interface.vwan3 status 2>/dev/null | grep \"address\" | grep -oE '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' 2>/dev/null)

if [ ! -z "$wan_ip4" ]; then
                	iptables -t nat -A openclash -d "$wan_ip4" -j RETURN
                fi
                if [ ! -z "$wan1_ip4" ]; then
                	iptables -t nat -A openclash -d "$wan1_ip4" -j RETURN
                fi
                if [ ! -z "$wan2_ip4" ]; then
                	iptables -t nat -A openclash -d "$wan2_ip4" -j RETURN
                fi
                if [ ! -z "$wan3_ip4" ]; then
                	iptables -t nat -A openclash -d "$wan3_ip4" -j RETURN
                fi
                if [ ! -z "$wan4_ip4" ]; then
                	iptables -t nat -A openclash -d "$wan4_ip4" -j RETURN
                fi
就这样加的，问题解决。

**Comment by osxdiy** [comment]
ipv6也有可能存在这个问题

**Comment by jediseed** [comment]
刚刚异常记录又出现了，持续出现[warning] dial 🎯 全球直连 error: dial tcp4 127.0.0.1:8888: connect: connection refused，梯子正常。

**Comment by osxdiy** [comment]
time="2020-03-08T09:17:00Z" level=warning msg="dial Domestic error: dial tcp4 120.132.47.182:80: i/o timeout"
time="2020-03-08T09:17:02Z" level=warning msg="dial Domestic error: dial tcp4 52.83.174.65:443: i/o timeout"
time="2020-03-08T09:17:03Z" level=warning msg="dial Domestic error: dial tcp4 52.83.174.65:443: i/o timeout"
time="2020-03-08T09:17:34Z" level=warning msg="dial Domestic error: dial tcp4 127.0.0.1:62078: connect: connection refused"
time="2020-03-08T09:17:34Z" level=warning msg="dial Domestic error: dial tcp4 127.0.0.1:62079: connect: connection refused"
time="2020-03-08T09:17:34Z" level=warning msg="dial Domestic error: dial tcp4 127.0.0.1:62078: connect: connection refused"
time="2020-03-08T09:17:38Z" level=warning msg="dial Domestic error: dial tcp4 127.0.0.1:62079: connect: connection refused"
time="2020-03-08T09:17:53Z" level=warning msg="dial Domestic error: dial tcp4 39.105.246.48:8000: i/o timeout"
time="2020-03-08T09:18:08Z" level=warning msg="dial Domestic error: dial tcp4 104.18.10.39:8000: i/o timeout"
这些日志不知什么原因和

**Comment by osxdiy** [comment]
多WAN的问题完美修复
