### ISSUE TITLE
关于openclash的游戏策略组

### ISSUE THREAD

**Issue by Urban1023** [vernesong/OpenClash#1950]
根据第三方游戏规则中选择了游戏规则，并导入配置，并且在服务器策略中增加了专门的UDP游戏节点，可是游戏延迟一样卡的飞起。要怎么破。

**Comment by vernesong** [comment]
确认是否走了代理

**Comment by Urban1023** [comment]
> 是否确认走了代理

没有走代理。我的是旁路由。

**Comment by vernesong** [comment]
游戏流量走没走

**Comment by Urban1023** [comment]
> 游戏流量走没走

是的，所以就很奇怪，不知道要如何设置。
