### ISSUE TITLE
FakeIP模式下电视怎么ipv6解锁奈飞

### ISSUE THREAD

**Issue by evolsnow** [vernesong/OpenClash#1951]
- 设备是 sony tv，fakeip混合模式，机场通过v6解锁的Netflix，openclash调试了很多配置电视还是走到了Netflix的v4域名（只知道apple tv会有这个问题）。同网络下手机、电脑播放时看到倒是ipv6开头的域名。
- 配置：路由关闭了ipv6 dhcp + 未勾选允许ipv6域名解析 + 未开启ipv6代理 + 启用了流媒体域名定时解析。

1. 好奇fakeip混合模式下域名是怎么解析的，还会交给机场节点么？
2. 电视通过v6解锁netflix还有解么

**Comment by vernesong** [comment]
atv好像只能V4

**Comment by evolsnow** [comment]
我是索尼电视，openwrt里tcpdump了53端口的包，并没有什么可疑/规则外的域名。头大，不知道怎么检测出来的。

**Comment by evolsnow** [comment]
放弃了，后台看到有直接用ip发起的链接。。。
