### ISSUE TITLE
进程中有openclash_watchdog.sh进程，但webui中显示守护进程未运行

### ISSUE THREAD

**Issue by devome** [vernesong/OpenClash#1952]
日志信息挺正常的：
```
2022-01-14 20:11:16 OpenClash 启动成功，请等待服务器上线！
2022-01-14 20:11:16 第十步: 添加计划任务,启动进程守护程序...
2022-01-14 20:11:16 正在设置第二DNS服务器列表...
2022-01-14 20:11:16 第九步: 重启 Dnsmasq 程序...
2022-01-14 20:11:14 第八步: 设置防火墙规则...
2022-01-14 20:11:14 第七步: 设置控制面板...
2022-01-14 20:11:14 第六步: 等待主程序下载外部文件...
2022-01-14 20:11:11 第五步: 检查内核启动状态...
2022-01-14 20:11:11 提示: 未检测到特殊配置，调用 Dev 内核启动...
2022-01-14 20:11:11 第四步: 启动主程序...
2022-01-14 20:11:11 第二步: 组件运行前检查...
2022-01-14 20:11:11 第一步: 获取配置...
2022-01-14 20:11:11 OpenClash 开始启动...
2022-01-14 20:11:11 第六步：删除 OpenClash 残留文件...
2022-01-14 20:11:11 第五步: 重启 Dnsmasq 程序...
2022-01-14 20:11:11 第四步: 关闭 Clash 主程序...
2022-01-14 20:11:11 第三步: 关闭 OpenClash 守护程序...
2022-01-14 20:11:10 第二步: 删除 OpenClash 防火墙规则...
2022-01-14 20:11:10 第一步: 备份当前策略组状态...
2022-01-14 20:11:10 OpenClash 开始关闭...
```
在ps中也能看到守护进程：
```
 4053 root      1128 S    {openclash_watch} /bin/sh /usr/share/openclash/openclash_watchdog.sh
```
但在webui中显示守护程序未运行
![image](https://user-images.githubusercontent.com/93664269/149514130-78c05b83-8135-440d-8447-20e79958cbd0.png)

程序版本：

| [dev] 当前内核版本 | v1.9.0-1-g8c6d0c6 | [dev] 最新内核版本 | v1.9.0-1-g8c6d0c6 |
| [TUN] 当前内核版本 | 2022.01.03 | [TUN] 最新内核版本 | 2022.01.03 |
| 当前客户端版本 | v0.44.09-beta | 最新客户端版本 | v0.44.09-beta |

**Comment by devome** [comment]
> dev试试

是指选择更新分支切换到developer吗？已从developer分支更新了dev版本到v1.9.0-4-g8f3385b，问题依旧。

**Comment by vernesong** [comment]
要编译

**Comment by devome** [comment]
> 要编译

反馈前就是今天刚刚编译的，不过利用了旧的编译缓存，这个会有影响吗

**Comment by vernesong** [comment]
https://github.com/vernesong/OpenClash/blob/02e3b2fcdabd5bc9b0476a7dee38a656207e0a07/luci-app-openclash/luasrc/controller/openclash.lua#L108
看看那个命令在你这不正常吧

**Comment by devome** [comment]
> 

知道了。lede今天升级到busybox 1.35.0以后，`ps --version`这个命令已经无法执行了，我再看看怎么恢复。

**Comment by devome** [comment]
我尝试额外单独添加procps-ng这个包试试。

**Comment by devome** [comment]
> https://github.com/vernesong/OpenClash/blob/02e3b2fcdabd5bc9b0476a7dee38a656207e0a07/luci-app-openclash/luasrc/controller/openclash.lua#L108
> 
> 
> 看看那个命令在你这不正常吧

不对，刚才说错了，我看你逻辑是如果`ps --version 2>&1 |grep -c procps-ng |tr -d '\n'`输出是0，就用`ps |grep openclash_watchdog.sh |grep -v grep >/dev/null`的退出状态，这个退出状态确实是0的。那这样说来，没有问题啊。

**Comment by devome** [comment]
```
root@OpenWrt:/etc/openclash/core# ps |grep openclash_watchdog.sh |grep -v grep >/dev/null
root@OpenWrt:/etc/openclash/core# ps |grep openclash_watchdog.sh |grep -v grep
 7369 root      1128 S    {openclash_watch} /bin/sh /usr/share/openclash/openclash_watchdog.sh
root@OpenWrt:/etc/openclash/core# ps |grep openclash_watchdog.sh |grep -v grep >/dev/null
root@OpenWrt:/etc/openclash/core# echo $?
0
```

**Comment by vernesong** [comment]
ps加 -w 试试吧，可能用lua执行有点问题

**Comment by devome** [comment]
> ps加 -w 试试吧，可能用lua执行有点问题

```
root@OpenWrt:~# ps -w | grep openclash_watchdog
 7268 root      1076 R    grep openclash_watchdog
 7369 root      1128 S    {openclash_watch} /bin/sh /usr/share/openclash/openclash_watchdog.sh
```

**Comment by vernesong** [comment]
替换这个文件重启

**Comment by devome** [comment]
> 替换这个文件重启机器

第111行换成这样确实好了
```
return luci.sys.call("ps -w | grep openclash_watchdog.sh | grep -v grep >/dev/null") == 0
```

**Comment by devome** [comment]
神奇，执行加-w和不加执行结果看起来一样啊，没明白为啥这样加上就能正常。

**Comment by Actuallymax** [comment]
遇到同样的问题，我的是x86软路由

**Comment by devome** [comment]
> 遇到同样的问题，我的是x86软路由

按14楼处理后重启。

**Comment by NV3S** [comment]
> > 替换这个文件重启机器
> 
> `/usr/lib/lua/luci/controller/openclash.lua`第111行换成这样确实好了
> 
> ```
> return luci.sys.call("ps -w | grep openclash_watchdog.sh | grep -v grep >/dev/null") == 0
> ```

依此解决。

**Comment by honsunrise** [comment]
设置 `COLUMNS` 环境变量也是可以的 e.g. `COLUMNS=256`

```
return luci.sys.call("COLUMNS=256 ps | grep openclash_watchdog.sh | grep -v grep >/dev/null") == 0
```

**Comment by honsunrise** [comment]
> 神奇，执行加-w和不加执行结果看起来一样啊，没明白为啥这样加上就能正常。

不加 -w 最大单行输出长度就是busybox默认是80个列宽（命令失败也是因为截断），除非设置了`COLUMNS`环境变量
[https://github.com/mirror/busybox/blob/master/libbb/xfuncs.c#L265](https://github.com/mirror/busybox/blob/master/libbb/xfuncs.c#L265)

所以解决方案有两个
1. 设置 COLUMNS 环境变量
2. 设置 busybox 的 ps 的 -w[w]选项 （一个w，列宽：132； 大于一个w，列宽：2*1024）参考：[https://github.com/mirror/busybox/blob/master/procps/ps.c#L679](https://github.com/mirror/busybox/blob/master/procps/ps.c#L679)

综上感觉用 **`1`** 更合理一些

**Comment by devome** [comment]
> > 神奇，执行加-w和不加执行结果看起来一样啊，没明白为啥这样加上就能正常。
> 
> 不加 -w 最大单行输出长度就是busybox默认是80个列宽（命令失败也是因为截断），除非设置了`COLUMNS`环境变量
> [https://github.com/mirror/busybox/blob/master/libbb/xfuncs.c#L265](https://github.com/mirror/busybox/blob/master/libbb/xfuncs.c#L265)
> 
> 所以解决方案有两个
> 1. 设置 COLUMNS 环境变量
> 2. 设置 busybox 的 ps 的 -w[w]选项 （一个w，列宽：132； 大于一个w，列宽：2*1024）参考：[https://github.com/mirror/busybox/blob/master/procps/ps.c#L679](https://github.com/mirror/busybox/blob/master/procps/ps.c#L679)
> 
> 综上感觉用 **`1`** 更合理一些
> 

受教了

**Comment by JwietPuj-Drin** [comment]
> ps加 -w 试试吧，可能用lua执行有点问题

@vernesong 近来 OpenWRT 要替换用 Alpine 的 APK 管理器的事传来传去的，我也试了下。

发现 APK 的 busybox-1.36.1 的 ps 是没有 -w 这个 flag 的，会导致 openclash_ps.sh openclash.lua 等一系列调用 ps -w 检查状态的命令无效
![屏幕截图 2024-10-11 084858](https://github.com/user-attachments/assets/edcebf40-a3de-4249-b208-906b9fc43ae2)

**Comment by vernesong** [comment]
没看到官方删了这个选项
