### ISSUE TITLE
Rule Provider不会按配置的Interval自动更新

### ISSUE THREAD

**Issue by InsOnYou** [vernesong/OpenClash#1957]
`rule-providers:
  TikTok:
    type: http
    behavior: classical
    path: "/etc/openclash/rule_provider/TikTok.yaml"
    url: https://cdn.jsdelivr.net/gh/DivineEngine/Profiles@master/Clash/RuleSet/StreamingMedia/Video/TikTok.yaml
    interval: 86400

  Netflix(By lhie1):
    type: http
    behavior: classical
    path: "/etc/openclash/rule_provider/Netflix-lhie1.yaml"
    url: https://cdn.jsdelivr.net/gh/lhie1/Rules@master/Clash/Provider/Media/Netflix.yaml
    interval: 86400`

配置文件里设定了一天更新一次，但是不起作用。日志里也没有报错，请问是什么原因导致的呢？
<img width="374" alt="Screen Shot 2022-01-15 at 16 50 13" src="https://user-images.githubusercontent.com/29951150/149616011-fb7904f5-5d91-4ab8-9b29-99f032dc28c9.png">

**Comment by InsOnYou** [comment]
如果在yacd面板里手动更新了，下次OpenClash启动后，规则组又会变成更新前的样子。

**Comment by vernesong** [comment]
表示没有更新的意思

**Comment by coderbean** [comment]
> 表示没有更新的意思

遇到了同样的问题，“没有更新的意思”是什么意思？

**Comment by coderbean** [comment]
> > 表示没有更新的意思
> 
> 遇到了同样的问题，“没有更新的意思”是什么意思？ 我理解这个是内核自带的功能吧？ @vernesong

我自己做了测试，我也终于懂了“没有更新”的意思了😄。

先说结论：**如果远端的文件和本地文件没有任何变化的话，就不会进行覆盖**，所以本地文件的修改日期也不会变化，clash内核应该是在内存中维护了检查更新的时间，所以点击更新后会提示不久前更新，但是重启之后只能读取文件的修改时间，所以会变成文件的修改时间。
所以：内核没有问题，逻辑也没有问题。唯一可以优化的地方就是当没有变化的时候也可以变更一下文件的修改日期就没有歧义了。这个应该去让D大改一下。

**Comment by xiaocheng-929** [comment]
不不不，我终于发现原因了，因为规则集raw的链接是直连不了的，即使是cdn的链接也基本是抽风状态，但
Rule Provider是不走代理的，并且你没选择当前配置它也不会更新的。
解决办法有：使用cdn链接并且interval设置小点，比如5分钟更新一次！！！cdn链接总有不抽风的时候；tun模式此时也不好用，Rule Provider依旧会绕开clash的tun模式，开其他代理软件的tun模式有又卡不准规则集的更新时间。
那个规则集是放在个人用户\.config\clash\providers\rule文件夹里的，因为cdn链接不稳定，新电脑（当前电脑没存有规则集）新加入一个带规则集的配置时，基本上就一直报错切换不了当前配置，切换不了当前配置它有不会按interval的时间间隔去更新，这是就只能不断的把链接贴上去下载（不是点那个更新配置的圈圈），看脸哪时就能下载齐了；或者去其他电脑把规则集复制过来；或者使用其他代理软件开tun模式去下载配置文件。

**Comment by xiaocheng-929** [comment]
不不不，我终于发现原因了，因为规则集raw的链接是直连不了的，即使是cdn的链接也基本是抽风状态，但
Rule Provider是不走代理的，并且你没选择当前配置它也不会更新的。
解决办法有：使用cdn链接并且interval设置小点，比如5分钟更新一次！！！cdn链接总有不抽风的时候；tun模式此时也不好用，Rule Provider依旧会绕开clash的tun模式，开其他代理软件的tun模式有又卡不准规则集的更新时间。
那个规则集是放在个人用户\.config\clash\providers\rule文件夹里的，因为cdn链接不稳定，新电脑（当前电脑没存有规则集）新加入一个带规则集的配置时，基本上就一直报错切换不了当前配置，切换不了当前配置它有不会按interval的时间间隔去更新，这是就只能不断的把链接贴上去下载（不是点那个更新配置的圈圈），看脸哪时就能下载齐了；或者去其他电脑把规则集复制过来；或者使用其他代理软件开tun模式去下载配置文件。

**Comment by NewEpoch2020** [comment]
> 不不不，我终于发现原因了，因为规则集raw的链接是直连不了的，即使是cdn的链接也基本是抽风状态，但 Rule Provider是不走代理的，并且你没选择当前配置它也不会更新的。 解决办法有：使用cdn链接并且interval设置小点，比如5分钟更新一次！！！cdn链接总有不抽风的时候；tun模式此时也不好用，Rule Provider依旧会绕开clash的tun模式，开其他代理软件的tun模式有又卡不准规则集的更新时间。 那个规则集是放在个人用户.config\clash\providers\rule文件夹里的，因为cdn链接不稳定，新电脑（当前电脑没存有规则集）新加入一个带规则集的配置时，基本上就一直报错切换不了当前配置，切换不了当前配置它有不会按interval的时间间隔去更新，这是就只能不断的把链接贴上去下载（不是点那个更新配置的圈圈），看脸哪时就能下载齐了；或者去其他电脑把规则集复制过来；或者使用其他代理软件开tun模式去下载配置文件。

我是关了TUN模式就会马上自动更新了, 确实是TUN的锅.

**Comment by NewEpoch2020** [comment]
> 不不不，我终于发现原因了，因为规则集raw的链接是直连不了的，即使是cdn的链接也基本是抽风状态，但 Rule Provider是不走代理的，并且你没选择当前配置它也不会更新的。 解决办法有：使用cdn链接并且interval设置小点，比如5分钟更新一次！！！cdn链接总有不抽风的时候；tun模式此时也不好用，Rule Provider依旧会绕开clash的tun模式，开其他代理软件的tun模式有又卡不准规则集的更新时间。 那个规则集是放在个人用户.config\clash\providers\rule文件夹里的，因为cdn链接不稳定，新电脑（当前电脑没存有规则集）新加入一个带规则集的配置时，基本上就一直报错切换不了当前配置，切换不了当前配置它有不会按interval的时间间隔去更新，这是就只能不断的把链接贴上去下载（不是点那个更新配置的圈圈），看脸哪时就能下载齐了；或者去其他电脑把规则集复制过来；或者使用其他代理软件开tun模式去下载配置文件。

我是关了TUN模式就会马上自动更新了, 确实是TUN的锅.
