### ISSUE TITLE
局域网固定几个ip走规则，其余都走直连

### ISSUE THREAD

**Issue by lrgcx** [vernesong/OpenClash#1958]
我想局域网内的几个设备ip走规则而不是直走代理，其他都走直连。试过把所有ip段都走直连，然后在前面加入指定的ip时只能设为节点选择或是手动选择之类的。请教该如何设置！

**Comment by vernesong** [comment]
redir模式访问控制

**Comment by lrgcx** [comment]
谢谢回复！我还没用过redir模式，哈哈。

**Comment by lrgcx** [comment]
我用了redir混合模式，白名单。完美解决我的需求。感谢！
