### ISSUE TITLE
请问如何自定义直连网址

### ISSUE THREAD

**Issue by peace000** [vernesong/OpenClash#1959]
之前一直用cfw，直接选直连所有流量就都可以不经过代理了。但openclash即使我在控制台选了全局直连，依然会按规则代理。我想不走代理直连https://www.speedtest.net/这个网站，请问有什么好的方法吗？

**Comment by Nesxc** [comment]
为什么不用 speedtest.cn

**Comment by vernesong** [comment]
![image](https://user-images.githubusercontent.com/42875168/149804640-a24f3e85-c944-444a-aedc-dbee2c5a178c.png)
这里没用？

**Comment by peace000** [comment]
> ![image](https://user-images.githubusercontent.com/42875168/149804640-a24f3e85-c944-444a-aedc-dbee2c5a178c.png) 这里没用？

我选中了direct，但流量照样按规则分流出去了

**Comment by vernesong** [comment]
切换没有问题，只是没有打断之前的链接

**Comment by peace000** [comment]
> 切换没有问题，只是没有打断之前的链接
谢谢！切换代理模式不生效的问题已解决，控制台关闭所有连接即可
