### ISSUE TITLE
【求助】开启OpenClash之后，无法使用 git clone/push，kex ssh 密钥错误

### ISSUE THREAD

**Issue by LittleNewton** [vernesong/OpenClash#1960]
git clone/push 我的 Github 私人仓库，通过ssh，命令行报错：

```
Cloning into 'test'...
kex_exchange_identification: Connection closed by remote host
Connection closed by 20.205.243.166 port 22
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

关闭 OpenClash 之后一切正常。

OpenClash 版本：44.09beta
OpenWrt: 21.02
OS: Windows 10

**Comment by vernesong** [comment]
切换代理呢？可能IP被屏蔽

**Comment by LittleNewton** [comment]
@vernesong 

换了另一个代理提供商的配置文件之后，GitHub就访问正常了。

**Comment by allinu** [comment]
这种情况我也遇到了，不只是openclash，使用passwall也会遇到
在本机使用代理的时候有时候也会遇到，使用socket5连接可以规避，但是不知道软路由上怎么解决这个问题

目前猜测可能是以下情况和原因：

- 不使用 FakeIP 模式
  不使用 FakeIP 的时候，可能是秘钥在交换的时候，经过了代理服务器，连接目标服务器就变成了连接代理服务器
- 使用 FakeIP 模式
  使用 FakeIP 就很明确了，直接连接了缓存的虚假IP

不知道怎么解决，希望有大佬能帮忙解决一下，由于工作和学习原因，这个问题还是很急切需要解决的

**Comment by allinu** [comment]
@LittleNewton 把模式改为 Redir 模式

添加下面的规则
<img width="1179" alt="image" src="https://user-images.githubusercontent.com/32992109/150631775-47c0b001-e78f-4eff-b66b-80879eb69cad.png">

我这边的ssh连接和git测试都通过了，不知道能不能对你有帮助

**Comment by LittleNewton** [comment]
@allinu 

感谢分享。目前我换了一个 Proxy 提供商，这个问题没有了。以后有机会我再试试吧。

BTW，你这个自定义的规则好丰富啊，咱俩用的是同一个 OpenClash 嘛哈哈

**Comment by IvanLi-CN** [comment]
我有同样的问题，目前排查了一下午，好像只能断定是代理的问题……  请教下换了哪家，我怕是也要换了

**Comment by allinu** [comment]
@IvanLi-CN 这个要看你的电脑系统了，我只能给你提供Mac的，如果你是使用Mac的话，改用电脑端Clash X或者Clash X Pro，然后复制终端代理命令，把http和https的代理都改为socks5的代理，就好了，如果是软路由也可以根据这个思路改成路由器的socks的代理

**Comment by IvanLi-CN** [comment]
感谢回复🥰 @allinu ,我感觉我遇到的问题是节点屏蔽 22 端口的连接，我检查过我的服务器，没有收到 SSH 连接。

> @IvanLi-CN 这个要看你的电脑系统了，我只能给你提供Mac的，如果你是使用Mac的话，改用电脑端Clash X或者Clash X Pro，然后复制终端代理命令，把http和https的代理都改为socks5的代理，就好了，如果是软路由也可以根据这个思路改成路由器的socks的代理

我在软路由上使用的。
我使用 OpenClash 时，换了个机场，挨个选节点，选了十来个，终于选到一个能正常连的节点。
我使用 HelloWorld  时，使用自建节点和机场的节点，发现自建的节点正常，机场的不行。


> 这种情况我也遇到了，不只是openclash，使用passwall也会遇到 在本机使用代理的时候有时候也会遇到，使用socket5连接可以规避，但是不知道软路由上怎么解决这个问题
> 
> 目前猜测可能是以下情况和原因：
> 
> * 不使用 FakeIP 模式
>   不使用 FakeIP 的时候，可能是秘钥在交换的时候，经过了代理服务器，连接目标服务器就变成了连接代理服务器
> * 使用 FakeIP 模式
>   使用 FakeIP 就很明确了，直接连接了缓存的虚假IP
> 
> 不知道怎么解决，希望有大佬能帮忙解决一下，由于工作和学习原因，这个问题还是很急切需要解决的

我按这个切换了下 "`Redir-Host`" 模式和 "`Fake IP`" 模式，连接 SSH 方面没什么变化，只要走代理就过不去，除非我选了那个正常连的节点。

之后偶然测了下非 22 端口的 SSH，无论是什么节点都能成功连接。

所以我感觉，问题出在节点。我判断我确实使用了代理的依据是 Clash Dashboard 控制面板里的日志，有看到对应的`域名/IP:port` match Match() using 🐟 漏网之鱼[🇯🇵 日本 JP-Y02]，这方面应该不会错。

**Comment by supine-win** [comment]
> > @LittleNewton 把模式改为 Redir 模式
> > 添加下面的规则
> > `- DST-PORT,22,DIRECT`
> > <img alt="image" width="1179" src="https://user-images.githubusercontent.com/32992109/150631775-47c0b001-e78f-4eff-b66b-80879eb69cad.png">
> > 我这边的ssh连接和git测试都通过了，不知道能不能对你有帮助
> 
> 大佬，按你这说的，把22端口改成直连，git可以正常使用了。 不知道有什么副作用没？

副作用就是git clone贼慢,我也在找解决方案

**Comment by openips** [comment]
没遇到 一切正常 节点问题

**Comment by xinydev** [comment]
改成通过443端口git clone就没问题了 
ssh配置需要进行一下修改 https://docs.github.com/en/authentication/troubleshooting-ssh/using-ssh-over-the-https-port

```
Host github.com
Hostname ssh.github.com
Port 443
User git
IdentityFile .....
```

感觉确实是22端口的问题

**Comment by yoyo837** [comment]
> 改成通过443端口git clone就没问题了 ssh配置需要进行一下修改 https://docs.github.com/en/authentication/troubleshooting-ssh/using-ssh-over-the-https-port
> 
> ```
> Host github.com
> Hostname ssh.github.com
> Port 443
> User git
> IdentityFile .....
> ```
> 
> 感觉确实是22端口的问题

You save my time, You save my life!

**Comment by wangwei2-ola** [comment]
> 改成通过443端口git clone就没问题了 ssh配置需要进行一下修改 https://docs.github.com/en/authentication/troubleshooting-ssh/using-ssh-over-the-https-port
> 
> ```
> Host github.com
> Hostname ssh.github.com
> Port 443
> User git
> IdentityFile .....
> ```
> 
> 感觉确实是22端口的问题

你这个方法比22端口direct好！ 解决了实际问题，同时不影响速度，完美👍🏻

**Comment by a525850194** [comment]
> @LittleNewton 把模式改为 Redir 模式
> 
> 添加下面的规则
> 
> `- DST-PORT,22,DIRECT`
> 
> <img alt="image" width="1179" src="https://user-images.githubusercontent.com/32992109/150631775-47c0b001-e78f-4eff-b66b-80879eb69cad.png">
> 
> 我这边的ssh连接和git测试都通过了，不知道能不能对你有帮助

感谢大佬，找了好久，终于在你这里找到方法了

**Comment by Haojen** [comment]
有的机场因为某些原因，可能会封锁端口为22的连接，所以无论怎么在设备端上折腾都不行。 只能在代理规则里排除22端口，或者暂时关掉代理才可以

**Comment by unclezs** [comment]
我是软路由里面使用，因为以前配置了 ~/.ssh/config 文件，删除里面 github 的配置就行了

**Comment by otakutyrant** [comment]
> 有的机场因为某些原因，可能会封锁端口为22的连接，所以无论怎么在设备端上折腾都不行。 只能在代理规则里排除22端口，或者暂时关掉代理才可以

我问了我自家的，他说不封就会被扫爆，上游接着封他们服务器。

**Comment by mikeguo99** [comment]
<img width="949" alt="image" src="https://github.com/vernesong/OpenClash/assets/111490790/5eb462fd-8bc5-4223-aef3-177592e34ec0">
没有这个“规则设置”这个页签啊。。

**Comment by DukeAnn** [comment]
> Host github.com
> Hostname ssh.github.com
> Port 443
> User git
> IdentityFile .....

可以说救人于水火之中了

**Comment by lianggx6** [comment]
> 改成通过443端口git clone就没问题了 ssh配置需要进行一下修改 https://docs.github.com/en/authentication/troubleshooting-ssh/using-ssh-over-the-https-port
> 
> ```
> Host github.com
> Hostname ssh.github.com
> Port 443
> User git
> IdentityFile .....
> ```
> 
> 感觉确实是22端口的问题

NB啊

**Comment by evilArsh** [comment]
> 改成通过443端口git clone就没问题了 ssh配置需要进行一下修改 https://docs.github.com/en/authentication/troubleshooting-ssh/using-ssh-over-the-https-port
> 
> ```
> Host github.com
> Hostname ssh.github.com
> Port 443
> User git
> IdentityFile .....
> ```
> 
> 感觉确实是22端口的问题

love you ,hope you peaceful

**Comment by Ronchy2000** [comment]
> [@LittleNewton](https://github.com/LittleNewton) 把模式改为 Redir 模式
> 
> 添加下面的规则
> 
> `- DST-PORT,22,DIRECT`
> 
> <img alt="image" width="1179" src="https://user-images.githubusercontent.com/32992109/150631775-47c0b001-e78f-4eff-b66b-80879eb69cad.png">
> 
> 我这边的ssh连接和git测试都通过了，不知道能不能对你有帮助

多谢！！已解决！
