### ISSUE TITLE
使用第三方规则集，如何修改Match的分流？

### ISSUE THREAD

**Issue by MuseA-5** [vernesong/OpenClash#1962]
- 如下图所示，我在使用第三方规则集
![Xnip2022-01-16_16-40-19](https://user-images.githubusercontent.com/62163340/149653106-eb6fe22e-3cf4-4da8-8c30-af39d2445ad4.jpg)

- 当openclash启动后，规则变成了如下所示，但是没有match的分流（也没有geoip），并且会默认走直连，请问哪里可以修改match的分流吗？
![Xnip2022-01-16_16-39-37](https://user-images.githubusercontent.com/62163340/149653124-2d4250bc-6c55-43a0-ad65-8fda8708d481.jpg)

**Comment by vernesong** [comment]
这里加不了，你直接在配置文件里加

**Comment by MuseA-5** [comment]
> 这里加不了，你直接在配置文件里加

感谢解答
