### ISSUE TITLE
v0.44.09-beta几个小问题!

### ISSUE THREAD

**Issue by wakeup611** [vernesong/OpenClash#1964]
1.一直显示守护程序未运行
2.使用steam下载时速度慢. 只有几百kb  但是在日志中可以看到没有走代理
3.steam每次登陆都需要重新输密码  有没有办法解决呀

麻烦大佬啦!

**Comment by mengxinz** [comment]
> 1.一直显示守护程序未运行 2.使用steam下载时速度慢. 只有几百kb 但是在日志中可以看到没有走代理 3.steam每次登陆都需要重新输密码 有没有办法解决呀
> 
> 麻烦大佬啦!

替换这个文件重启机器

/usr/lib/lua/luci/controller/openclash.lua第111行换成这样确实好了

return luci.sys.call("ps -w | grep openclash_watchdog.sh | grep -v grep >/dev/null") == 0

**Comment by wakeup611** [comment]
我用了别的固件好了，剩下两个问题有办法解决吗。。> > 1.一直显示守护程序未运行 2.使用steam下载时速度慢. 只有几百kb 但是在日志中可以看到没有走代理 3.steam每次登陆都需要重新输密码 有没有办法解决呀
> 
> > 
> 
> > 麻烦大佬啦!
> 
> 
> 
> 替换这个文件重启机器
> 
> 
> 
> /usr/lib/lua/luci/controller/openclash.lua第111行换成这样确实好了
> 
> 
> 
> return luci.sys.call("ps -w | grep openclash_watchdog.sh | grep -v grep >/dev/null") == 0

**Comment by vernesong** [comment]
![image](https://user-images.githubusercontent.com/42875168/149806239-03a3ac81-11fa-4634-bba0-2ec443283d71.png)
steam是规则的问题，要下载最好还是暂时直连

**Comment by coderbean** [comment]
> > 1.一直显示守护程序未运行 2.使用steam下载时速度慢. 只有几百kb 但是在日志中可以看到没有走代理 3.steam每次登陆都需要重新输密码 有没有办法解决呀
> > 麻烦大佬啦!
> 
> 替换这个文件重启机器
> 
> /usr/lib/lua/luci/controller/openclash.lua第111行换成这样确实好了
> 
> return luci.sys.call("ps -w | grep openclash_watchdog.sh | grep -v grep >/dev/null") == 0

多谢，修改后正常显示了

**Comment by wakeup611** [comment]
所以说steam下载无论什么配置都会有这样的问题存在是吧，谢谢大佬> ![image](https://user-images.githubusercontent.com/42875168/149806239-03a3ac81-11fa-4634-bba0-2ec443283d71.png)
> 
> steam是规则的问题，要下载最好还是暂时直连

**Comment by coderbean** [comment]
> 所以说steam下载无论什么配置都会有这样的问题存在是吧，谢谢大佬> ![image](https://user-images.githubusercontent.com/42875168/149806239-03a3ac81-11fa-4634-bba0-2ec443283d71.png)
> > 
> > steam是规则的问题，要下载最好还是暂时直连
> 
> 

老哥，你先去看下clash教程吧，什么是分流规则搞清楚

**Comment by wakeup611** [comment]
我看了呀 就是不知道你想表达什么哇> > 所以说steam下载无论什么配置都会有这样的问题存在是吧，谢谢大佬> ![image](https://user-images.githubusercontent.com/42875168/149806239-03a3ac81-11fa-4634-bba0-2ec443283d71.png)
> > > 
> > > steam是规则的问题，要下载最好还是暂时直连
> > 
> > 
> 
> 老哥，你先去看下clash教程吧，什么是分流规则搞清楚
> 
>

**Comment by hnxxd** [comment]
奇芭，网站访问检查全部都通过，油管也能打开，就是不能看视频。
