### ISSUE TITLE
v0.44.09在随固件编译后，自启动默认为“禁用”

### ISSUE THREAD

**Issue by NV3S** [vernesong/OpenClash#1965]
在使用v0.44.09代码编译并安装固件、配置完成并启动后，发现重启openwrt后，openclash未启动。
检查发现，启动项中，openclash默认为禁用状态（如图），需手动启用后可随系统启动。

> OpenClash 调试日志

> 生成时间: 2022-01-17 13:25:29
> 插件版本: v0.44.09-beta
> 隐私提示: 上传此日志前请注意检查、屏蔽公网IP、节点、密码等相关敏感信息
> 
> ```
> 
> #===================== 系统信息 =====================#
> 
> 主机型号: VMware, Inc. VMware7,1
> 固件版本: OpenWrt SNAPSHOT r4099-ada52a0ef
> LuCI版本: git-21.335.48743-5f363d9-1
> 内核版本: 5.10.91
> 处理器架构: x86_64
> 
> #此项有值时,如不使用IPv6,建议到网络-接口-lan的设置中禁用IPV6的DHCP
> IPV6-DHCP: 
> 
> #此项结果应仅有配置文件的DNS监听地址
> Dnsmasq转发设置: 127.0.0.1#7874
> 
> #===================== 依赖检查 =====================#
> 
> dnsmasq-full: 已安装
> coreutils: 已安装
> coreutils-nohup: 已安装
> bash: 已安装
> curl: 已安装
> ca-certificates: 已安装
> ipset: 已安装
> ip-full: 已安装
> iptables-mod-tproxy: 已安装
> kmod-ipt-tproxy: 已安装
> iptables-mod-extra: 已安装
> kmod-ipt-extra: 已安装
> libcap: 已安装
> libcap-bin: 已安装
> ruby: 已安装
> ruby-yaml: 已安装
> ruby-psych: 已安装
> ruby-pstore: 已安装
> ruby-dbm: 已安装
> kmod-tun(TUN模式): 已安装
> luci-compat(Luci-19.07): 未安装
> 
> #===================== 内核检查 =====================#
> 
> 运行状态: 运行中
> 进程pid: 16359
> 运行权限: 16359: cap_dac_override,cap_net_bind_service,cap_net_admin,cap_net_raw,cap_sys_resource=eip
> 运行用户: nobody
> 已选择的架构: linux-amd64
> 
> #下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
> Tun内核版本: 2022.01.03
> Tun内核文件: 存在
> Tun内核运行权限: 正常
> 
> Dev内核版本: v1.9.0-1-g8c6d0c6
> Dev内核文件: 存在
> Dev内核运行权限: 正常

![image](https://user-images.githubusercontent.com/17755534/149712547-b5daf76e-870c-4658-95f8-aa73af5550f7.png)

**Comment by kkfuzi** [comment]
我也发现了这个问题。

**Comment by vernesong** [comment]
用dev

**Comment by WYC-2020** [comment]
@vernesong  现在dev 多久会合并到master分支呢

**Comment by vernesong** [comment]
可以直接选dev分支更新啊

**Comment by WYC-2020** [comment]
@vernesong 不是我只是想知道master还维护不，所以才问会不会每次间隔多久合并到master

**Comment by vernesong** [comment]
一般一个月
