### ISSUE TITLE
更新了好几个版本，fake-ip还是看不了iqiyi

### ISSUE THREAD

**Issue by 6060E6II** [vernesong/OpenClash#1968]
只要是用fake-ip，任何模式iqiyi点视频进去都是load不出来的，如果是手机app简直整个页面load不出来，求大神帮我解决，很想用fake-ip模式，但是这样不敢用

[openclash_debug.log](https://github.com/vernesong/OpenClash/files/7890047/openclash_debug.log)

**Comment by vernesong** [comment]
mwan3关了试试

**Comment by 6060E6II** [comment]
> mwan3关了试试

mwan一直都没开，我禁用了，后来把所有mwan设置都删了也不行
