### ISSUE TITLE
19.07.2版本的Openwrt代码下，GEOIP依然更新失败

### ISSUE THREAD

**Issue by lifetyper** [vernesong/OpenClash#197]
之前这个issue https://github.com/vernesong/OpenClash/issues/123 不知道为什么就被关闭了，我测试了各种设置，现象依然没有改变，GEOIP下载都是失败的。

如果确实修复了，能不能提供一下测试通过的openwrt代码版本和编译的.config文件，因为那个issue里有人回复说修复了，但我真的试得快吐血了也没成功。

我一度怀疑浏览器的问题，但是FF，Chrome，Edge都试过了，luci的ssl打开和关闭都试过了，也没发现任何变化啊。

症状依然是：点击更新GEOIP数据库后，下载GEOIP数据的提示一闪而过，然后就跳到后面步骤，最后提示更新失败。但直接运行更新脚本又是可以的。

**Comment by vernesong** [comment]
建议你单独检查脚本语句，看看是哪一行代码造成的

**Comment by baggio630** [comment]
检查下依赖都装了吗，没装的话全装完再试试。

**Comment by lifetyper** [comment]
> 
> 
> 建议你单独检查脚本语句，看看是哪一行代码造成的

单独运行脚本是成功的，但是从luci界面调用就失败。。。

**Comment by lidyu2019** [comment]
官方版本的确不能更新，不管是18.06还是19.07，lean的固件没有问题，用官方的就从这里下载https://static.clash.to/GeoIP2/GeoIP2-Country.mmdb，改名Country.mmdb，用WinSCP直接拖进去etc/openclash替换吧
