### ISSUE TITLE
老问题重提：开启openclash port forwarding 无法工作

### ISSUE THREAD

**Issue by Pandoxie** [vernesong/OpenClash#1970]
![Screenshot 2022-01-19 111457](https://user-images.githubusercontent.com/4418547/150057285-0757da31-3d46-4ed7-bb51-4c9c00ac0a03.jpg)
应该都是最新版本，但是测试了基本上所有的模式fake-ip, redir均无法使得openwrt firewall设置的port forward生效。开启openclash 外网访问内网的NAS和openwrt端口均立马切断。

**Comment by vernesong** [comment]
旁路由要再转发一次

**Comment by fish125658** [comment]
同样问题，开启openclash端口转发失效，关闭后，又无法上网

**Comment by Pandoxie** [comment]
> 旁路由要再转发一次

就这一个路由器，怎么操作能提示下么。并不太专业这块。非常感谢

**Comment by Botasky86** [comment]
固件问题吧，我的正常的
