### ISSUE TITLE
OpenClash v0.44.09-beta 启动配置中Rule Provider的链接地址无效

### ISSUE THREAD

**Issue by Bradley-Chen** [vernesong/OpenClash#1972]
用了ACL4SSR的规则，链接都不能正常转换，但是另一个规则却可以，如图：
![image](https://user-images.githubusercontent.com/88963146/150273318-104907f1-d65d-4ee7-b5df-74a68bcd6b5d.png)

导致ACL4SSR的规则都只能自己手动替换文件

**Comment by aguero119** [comment]
> 用了ACL4SSR的规则，链接都不能正常转换，但是另一个规则却可以，如图： ![image](https://user-images.githubusercontent.com/88963146/150273318-104907f1-d65d-4ee7-b5df-74a68bcd6b5d.png)
> 
> 导致ACL4SSR的规则都只能自己手动替换文件

github的确实不行,不管rule还是proxy,都不行. 请问楼主另外个能支持订阅转换么?

**Comment by aguero119** [comment]
错了,我用jsdelivr.net偶尔也会更新失败.但是放在不开代理的网站就没问题.
