### ISSUE TITLE
希望可以增加在使用url-test自动切换节点后断开旧连接的功能

### ISSUE THREAD

**Issue by Bradley-Chen** [vernesong/OpenClash#1978]
如图，自动切换节点后旧连接未断开，同时使用了两个节点，有时会导致网页和应用无法访问。
希望可以增加一个在使用url-test自动切换节点后断开旧连接的设置，并且不断开其他策略组的连接，比如走直连的连接不会同时断开。
感谢作者大大
![image](https://user-images.githubusercontent.com/88963146/150565253-db09de7a-f7b2-4034-b9d2-19ae1019da50.png)

**Comment by wangjianpro999** [comment]
本来就有啊，我勒个去，兄弟你搞笑了

**Comment by Bradley-Chen** [comment]
> 本来就有啊，我勒个去，兄弟你搞笑了

开启这个后只对selector组手动选择的生效，url-test自动切换还是不会断开旧连接呀。
<img width="197" alt="image" src="https://user-images.githubusercontent.com/88963146/150637811-9ece4101-9c97-4a34-bad9-6c81c011313c.png">

<img width="351" alt="image" src="https://user-images.githubusercontent.com/88963146/150637711-45f26967-6ddf-48e4-8cfd-c9826d602eab.png">

**Comment by wangjianpro999** [comment]
还有这事？好像我的会断开呀

**Comment by LakeishaKowalczyk** [comment]
+1

**Comment by laizou** [comment]
感谢作者以及提问的兄弟，我也没发现本来就有这个功能
