### ISSUE TITLE
mips 7621 cpu编译的clash不能记录选择的节点信息

### ISSUE THREAD

**Issue by codetiger666** [vernesong/OpenClash#1979]
mips 7621 cpu编译的clash不能记录选择的节点信息，每次重启后需要手动选择

**Comment by codetiger666** [comment]
日志提示
 level=warning msg="[CacheFile] can't open cache file: invalid argument"

**Comment by MaoSuSu** [comment]
同样的问题+1，希望作者大大早些修复

**Comment by vernesong** [comment]
更新到dev最新，打开小闪存模式

**Comment by codetiger666** [comment]
好的，希望尽快修复这个问题

**Comment by codetiger666** [comment]
> 逻辑还没处理好，等更新测试



> 逻辑还没处理好，等更新测试

好的，希望尽快修复此问题

**Comment by vernesong** [comment]
dev测试一下。打开小闪存模式

**Comment by codetiger666** [comment]
> 

好的

**Comment by codetiger666** [comment]
> dev测试一下。打开小闪存模式

好的

**Comment by codetiger666** [comment]
> dev测试一下。打开小闪存模式

还是不行，重启不记录，日志还是那个错误

**Comment by vernesong** [comment]
> > dev测试一下。打开小闪存模式
> 
> 更新dev内核可以了，可不可以不用小闪存模式，每次重启都要重新下载，网络环境差的时候经常下载失败

不是dev内核，你更新客户端再试，如果没问题我再改方案

**Comment by codetiger666** [comment]
> > > dev测试一下。打开小闪存模式
> > 
> > 
> > 更新dev内核可以了，可不可以不用小闪存模式，每次重启都要重新下载，网络环境差的时候经常下载失败
> 
> 不是dev内核，你更新客户端再试，如果没问题我再改方案

好的，我再试下

**Comment by codetiger666** [comment]
> > > dev测试一下。打开小闪存模式
> > 
> > 
> > 更新dev内核可以了，可不可以不用小闪存模式，每次重启都要重新下载，网络环境差的时候经常下载失败
> 
> 不是dev内核，你更新客户端再试，如果没问题我再改方案

可以用了，但是新刷的固件第一次启动clash依然提示无法打开缓存文件，第二次启动就好了，以后就都能记录了

**Comment by vernesong** [comment]
内核用的哪个架构

**Comment by codetiger666** [comment]
> 内核用的哪个架构

mipsel_24kc

**Comment by codetiger666** [comment]
> 内核用的哪个架构

现在可以关闭小闪存模式用了么，啥时候更新到主分支版本

**Comment by vernesong** [comment]
更新那里选dev分支更新就行了

**Comment by codetiger666** [comment]
> 更新那里选dev分支更新就行了

好的
