### ISSUE TITLE
fake IP模式下动态DDNS怎么设置呢？

### ISSUE THREAD

**Issue by asnon** [vernesong/OpenClash#1982]
fake ip模式下动态DDNS无法获取真是ip，外网无法连接，请问怎么排除呢？谢谢

**Comment by openips** [comment]
手工加一条规则 ddns服务上域名直接direct

**Comment by asnon** [comment]
> 手工加一条规则 ddns服务上域名直接direct

奇怪了。。我设置了没反应呢。。估计要清一下缓存。。我再试试

**Comment by clock88731** [comment]
你可以试试这样设置：
动态 DNS - 高级设置 - DNS-服务器 ，在这里填写一个靠谱的 DNS 服务器，比如 8.8.8.8
这样 DDNS 就不会从本地取你的IP地址，而是向外部 DNS 服务器查询你的域名地址。

**Comment by clock88731** [comment]
> > 手工加一条规则 ddns服务上域名直接direct
> 
> 奇怪了。。我设置了没反应呢。。估计要清一下缓存。。我再试试

我今天也遇到了类似的问题，解决了，给你这也回复下看看有没有帮助。。
我原本的问题是，设置了fake-ip，在局域网内部 ping ddns 的域名，就会指向一个不通的假IP，而且在路由 DDNS 页面看到的也是ping不通的假 IP，而我在局域网内部通过域名就无法访问端口映射出来的服务。
为了解决这个问题，我先是在动态 DNS的高级设置下，DNS-服务器 处，指定了靠谱的 DNS 服务，比如8.8.8.8。这么设置之后，DDNS 页面的IP能够获取正确。但此时局域网内的DNS解析还是不行。
然后，我在 DNS 设置页最后的 自定义挟持域名 处，将域名和路由内网IP进行绑定，并在防火墙-端口映射处映射路由器lan口的指定端口到我内网服务器的指定端口。
如此一来，我的内网和外网都能通过域名进行服务的访问了。

**Comment by nevertoday** [comment]
请问，具体的设置页面是在哪里？ 现在新版一更新，原本的设置，突然又失效了，很是~ 尴尬！

**Comment by llg38456** [comment]
> > > 手工加一条规则 ddns服务上域名直接direct
> > 
> > 
> > 奇怪了。。我设置了没反应呢。。估计要清一下缓存。。我再试试
> 
> 我今天也遇到了类似的问题，解决了，给你这也回复下看看有没有帮助。。 我原本的问题是，设置了fake-ip，在局域网内部 ping ddns 的域名，就会指向一个不通的假IP，而且在路由 DDNS 页面看到的也是ping不通的假 IP，而我在局域网内部通过域名就无法访问端口映射出来的服务。 为了解决这个问题，我先是在动态 DNS的高级设置下，DNS-服务器 处，指定了靠谱的 DNS 服务，比如8.8.8.8。这么设置之后，DDNS 页面的IP能够获取正确。但此时局域网内的DNS解析还是不行。 然后，我在 DNS 设置页最后的 自定义挟持域名 处，将域名和路由内网IP进行绑定，并在防火墙-端口映射处映射路由器lan口的指定端口到我内网服务器的指定端口。 如此一来，我的内网和外网都能通过域名进行服务的访问了。

感谢，这个解决了我的问题。
