### ISSUE TITLE
调试日志页面的连接测试

### ISSUE THREAD

**Issue by rgs66** [vernesong/OpenClash#1986]
我的情况是openwrt作为旁路由使用，之前反馈过问题，升级09版本后就无法更新订阅，也无法更新第三方规则，只有上传配置文件可用，调试日志页面，测试连接，提示如下

找不到任何连接日志！
1. 可能是插件未在运行
2. 可能是缓存导致浏览直接使用IP地址进行访问
3. 可能是DNS未劫持成功，导致Clash无法正确反推出域名连接
4. 可能是所填地址无法进行解析和连接

调试日志如下

[12.log](https://github.com/vernesong/OpenClash/files/7920714/12.log)

旁路由的防火墙设置

![image](https://user-images.githubusercontent.com/39143290/150685050-7f2f8ae1-f203-479a-a07a-592f2c8e966e.png)
![image](https://user-images.githubusercontent.com/39143290/150685056-11b81f0f-5797-4791-a8e1-4cf8008e7fcf.png)

请大佬帮分析解决问题，不胜感激！！

**Comment by alanhg** [comment]
所以这个问题是如何解决的？
