### ISSUE TITLE
运行一段时间后，apple服务与淘宝店铺页无法加载

### ISSUE THREAD

**Issue by Mintkarla** [vernesong/OpenClash#1988]
Fake ip增强模式。opclash运行一段时间后，apple music applestore之类的应用打开无法加载，开始的时候正常。当手机关闭WIFI在连接后，又能正常加载。多次稳定复现

**Comment by kendraase** [comment]
把IPV6代理关了，节点不支持的不要开。

**Comment by KKirara1227** [comment]
一直没有开IPV6。用SSR+就一直正常

**Comment by zb737472783** [comment]
同问
