### ISSUE TITLE
加入vmess后出现以下报错

### ISSUE THREAD

**Issue by aguero119** [vernesong/OpenClash#1989]
加入如下订阅后,启动openclash报错,请问是什么不兼容导致?
    xxx:
        type: http
        path: ./proxy_provider/xxx.list
        url: vmess://exxx 
     

2022-01-25 23:41:27 第四步: 启动主程序...
2022-01-25 23:41:21 Error: Edit Vmess compatible Error,【undefined method `each' for nil:NilClass】
2022-01-25 23:41:25 第三步: 修改配置文件...

**Comment by aguero119** [comment]
现在是加入后始终检测不到节点,但是通过"服务器节点配置"就可以添加并检测到.

**Comment by aguero119** [comment]
这种格式对吗?
proxies:
- name: "r"
  type: vmess
  server: v2ray.
  port: 443
  uuid: 07a21
  alterId: 0
  cipher: none
  tls: true
  skip-cert-verify: false
  udp: false
  network: ws
  ws-opts:
    path: "/ws"
    headers:
      Host: v2ray.s

**Comment by aguero119** [comment]
VMess WS TLS CDN

**Comment by aguero119** [comment]
无论用什么办法,转换订阅后的url放入到配置文件也不行.但是在clash for windows就可以.

**Comment by zoengzihaam** [comment]
> 这种格式对吗? proxies:
> 
> * name: "r"
>   type: vmess
>   server: v2ray.
>   port: 443
>   uuid: 07a21
>   alterId: 0
>   cipher: none
>   tls: true
>   skip-cert-verify: false
>   udp: false
>   network: ws
>   ws-opts:
>   path: "/ws"
>   headers:
>   Host: v2ray.s

在 Host: v2ray.s 这个地方自己修改成： Host: "你的域名"，自己在域名地方添加双引号

**Comment by wangxin6** [comment]
v0.44.16-beta 出现同样的错误信息

**Comment by fryderykhuang** [comment]
v0.44.16-beta 出现这个报错，且dns无法解析

**Comment by Kirolite** [comment]
v0.45.20还是报这个错，貌似不影响使用
