### ISSUE TITLE
经常出现收集数据中，只要出现就断联

### ISSUE THREAD

**Issue by wangjianpro999** [vernesong/OpenClash#1992]
经常出现收集数据中，只要出现就断联，求解决。
![Screenshot_2022-01-25-08-10-03-224_com microsoft emmx](https://user-images.githubusercontent.com/79621192/151102231-3fa9ada0-1a4b-4ad7-bf0b-946c7be0a01c.jpg)

**Comment by wangjianpro999** [comment]
而且每次出现时间都很长，浏览器进度条等很久

**Comment by vernesong** [comment]
什么设备，建议固件更新下

**Comment by wangjianpro999** [comment]
R2S，固件是404大佬的最新版，内核也是最新版

vernesong ***@***.***> 于 2022年1月28日周五 15:46写道：
