### ISSUE TITLE
【Feature request】允许选择备份时保留的文件

### ISSUE THREAD

**Issue by Potat0000** [vernesong/OpenClash#1999]
目前做 OpwnWrt 备份时，会将 `/etc/openclash` 目录的文件全部导出。能否增加一些选项，可以选择导出哪些内容？或者只做一个选项，可以选择不导出 `/etc/openclash`，由用户自行在备份列表中添加所需的内容。
感谢！

**Comment by vernesong** [comment]
这个文件的内容基本都是自定义的，备份下来没有多大影响吧

**Comment by Potat0000** [comment]
主要是里面包含 core，会显著增加备份文件大小

**Comment by helmiau** [comment]
@vernesong maybe you can add checkbox options like this

```
Backup Options:
[_] Config (Path: /etc/openclash/config)
[_] Core (Path: /etc/openclash/core)
[_] Proxy Providers (Path: /etc/openclash/proxy_provider)
[_] Rule Providers (Path: /etc/openclash/rule_provider)
[_] Game Rules (Path: /etc/openclash/game_rules)
[_] LuCI Config (Path: /etc/config/openclash)
```

**Comment by Potat0000** [comment]
> @vernesong maybe you can add checkbox options like this
> 
> ```
> Backup Options:
> [_] Config (Path: /etc/openclash/config)
> [_] Core (Path: /etc/openclash/core)
> [_] Proxy Providers (Path: /etc/openclash/proxy_provider)
> [_] Rule Providers (Path: /etc/openclash/rule_provider)
> [_] Game Rules (Path: /etc/openclash/game_rules)
> [_] LuCI Config (Path: /etc/config/openclash)
> ```

Yes! These are exactly what I (and probably other users) need!
