### ISSUE TITLE
在原版openwrt上 样式有问题

### ISSUE THREAD

**Issue by TangPere** [vernesong/OpenClash#2]
![image](https://user-images.githubusercontent.com/13415537/60277674-98a5e680-9930-11e9-825f-cf068eb53c37.png)

**Comment by vernesong** [comment]
Theme的问题，不太好兼容，以后找到方法再修吧。

你可以安装其他主题。

**Comment by cmheia** [comment]
IP地址这个表宽度不足的问题可以把[这里](https://github.com/vernesong/OpenClash/blob/4b2034c964ad51e592d4a1f0624c92c41c60eeaf/luci-app-openclash/files/usr/lib/lua/luci/view/openclash/myip.htm#L128)改成`<table width="100%">`解决。

另外`国内:`和后面的IP地址文字之间间距太大可以把[这里](https://github.com/vernesong/OpenClash/blob/4b2034c964ad51e592d4a1f0624c92c41c60eeaf/luci-app-openclash/files/usr/lib/lua/luci/view/openclash/myip.htm#L48)改成`margin:0;`弄窄。
不过这里还是间距很大，改成table应该好整。

**Comment by vernesong** [comment]
> <table width="100%">

好的
