### ISSUE TITLE
无法在斐讯K2上安装

### ISSUE THREAD

**Issue by TodayNow** [vernesong/OpenClash#200]
无法在斐讯K2上安装
固件是：OpenWrt 19.07.1 r10911-c155900f66 / LuCI openwrt-19.07 branch git-20.029.45734-adbbd5c
提示没有依赖，但是无法在OpenWrt中安装各个依赖包，提示Collected errors:
 * opkg_install_cmd: Cannot install package coreutils-nohup.
The opkg install command failed with code 255.

**Comment by TodayNow** [comment]
无法在斐讯K2上安装
固件是：OpenWrt 19.07.1 r10911-c155900f66 / LuCI openwrt-19.07 branch git-20.029.45734-adbbd5c

**Comment by vernesong** [comment]
opkg update 先，最好挂代理

**Comment by TodayNow** [comment]
> opkg update 先，最好挂代理

我是用的国内清华原是否对这个有影响呢

**Comment by lidashuang** [comment]
一样的问题, 可能是openwrt的问题

**Comment by vernesong** [comment]
就是依赖无法安装，你可以先手动装上
