### ISSUE TITLE
已选择编译内核版本显示错误，且无法更改

### ISSUE THREAD

**Issue by aweigz** [vernesong/OpenClash#2000]
昨天刚拉下来编译的，4.44.09版本，路由是WRT-1200AC，ARMv7处理器，现在的情况是，选择编译内核版本显示错误，且无法更改，选linux-armv7后按保存或应用都会跳成未设置。但是，处理器架构确是正常的，显示arm_cortex-a9_vfpv3-d16，openclash的使用也是正常的。

![微信图片_20220128233011](https://user-images.githubusercontent.com/18355236/151575731-7d08cd0c-e891-43ac-a0f6-470750cefa67.png)

**Comment by vernesong** [comment]
这里不是uci控制，你选择后点击任意更新按钮保存

**Comment by aweigz** [comment]
> 这里不是uci控制，你选择后点击更新按钮保存

OK，确实可以，谢谢！
