### ISSUE TITLE
建议丰富局域网控制功能

### ISSUE THREAD

**Issue by aweigz** [vernesong/OpenClash#2001]
缺少对单个主机采用何种方式上网的设置，如CLASH设置全局走规则，还能单独设置A主机，直通，B主机，全局代理。

**Comment by XinSSS** [comment]
这里尝试下

![Snipaste_2022-01-30_18-19-47](https://user-images.githubusercontent.com/30732527/151695723-3d7079c5-93c0-413e-9a72-61c746d42d57.png)

**Comment by aweigz** [comment]
> 这里尝试下
> 
> ![Snipaste_2022-01-30_18-19-47](https://user-images.githubusercontent.com/30732527/151695723-3d7079c5-93c0-413e-9a72-61c746d42d57.png)

谢谢！不过，感觉在访问控制那都已经做了黑白名单，逻辑上，如果把这个分别设置IP怎么走代理的方式，也做成菜单那样，那就方便很多了
