### ISSUE TITLE
似乎fakeip会与其它应用段(如zerotier)重叠导致断流

### ISSUE THREAD

**Issue by violarulan** [vernesong/OpenClash#2006]
标题表意可能不清，重新说明一下

最近换了几个固件都存在这个问题，fakeip 模式下的 openclash 运行一段时间（几分钟到数小时不等）后会偶尔出现断流情况，浏览器表现为 time out，局域网、国内、国外地址均会出现，后来发现 fakeip 返回的解析地址与我运行的 zerotier managed 路由重叠（我某个段使用了 192.168.5.0/24），删除掉这条 managed 路由后稳定运行，目前已稳定运行一周时间。

**Comment by vernesong** [comment]
解析出本地地址？
