### ISSUE TITLE
0.44.16无法正常启动

### ISSUE THREAD

**Issue by AXBNG** [vernesong/OpenClash#2007]
09版本除了首页运行状态显示不正常以外一切正常使用，
手贱更新，设置同前，redir兼容模式；
启动日志：“提示: 检测到配置了 TUN 内核专属功能，调用 TUN 内核启动”，“警告: 代理集文件检查超时，如启动失败请到日志页面查看详细信息！”，无法正常启动使用。

**Comment by AXBNG** [comment]
回退09版本正常启动

**Comment by jaove** [comment]
碰到同样问题

**Comment by AXBNG** [comment]
订阅转换的问题
