### ISSUE TITLE
URL-Test类型策略组，能否增加个参数，由用户定义2次测量最低延迟数值超过多少才做切换操作

### ISSUE THREAD

**Issue by yutaocn** [vernesong/OpenClash#201]
URL-Test类型策略组，能否增加个参数，由用户定义本次测量最低延迟和当前服务器延迟差距数值超过多少才做切换操作。
比如设置为100ms，就是当本次测试URL-Test结果最快的服务器B和当前服务器A差距超过100ms才做切换，可以一定程度避免每次测试稍有区别服务器就来回跳转造成的视频卡顿情况

**Comment by vernesong** [comment]
切换服务器不会中断已有链接，如你不愿意按照URL-Test的策略可以改为fallback

**Comment by yutaocn** [comment]
原来是这样，那么youtube卡顿应该是别的原因，谢谢解惑
