### ISSUE TITLE
为什么OpenClash要内置Dler Cloud？

### ISSUE THREAD

**Issue by OMGrz** [vernesong/OpenClash#2011]
最近更新了最新版的OpenClash，发现在“全局设置”里多了一个可以直接登陆机场Dler Cloud的标签页

好奇OpenClash和这家机场有什么关系吗？

**Comment by vernesong** [comment]
因为他家提供开发者套餐

**Comment by OMGrz** [comment]
soga，明白了，谢谢

**Comment by LimChoi** [comment]
dler登录失败，请问怎么解决？
