### ISSUE TITLE
如何使用备份文件，如何恢复openclash？

### ISSUE THREAD

**Issue by icucuio** [vernesong/OpenClash#2014]
使用《版本更新》界面里的《备份设置》，生成了备份文件，但是没有找到重新导入备份文件的地方，那应该怎么使用？

<img width="674" alt="image" src="https://user-images.githubusercontent.com/69136587/152329884-6ab40684-4a20-45ab-9cc0-7e9203eb8bed.png">

**Comment by michaelchen644** [comment]
你可以解压.gz文件，然后sftp上传替换文件还原设置，备份文件夹根目录下除了openclash放入/etc/config，其他都在/etc/openclash。

**Comment by icucuio** [comment]
> 你可以解压.gz文件，然后sftp上传替换文件还原设置，备份文件夹根目录下除了openclash放入/etc/config，其他都在/etc/openclash。

这样也太复杂了额，我想的是能够设计导入配置的地方，恢复之前的备份，方便大家升级后出现问题后，可以及时恢复之前的版本，而不是重新安装一遍openclash

**Comment by michaelchen644** [comment]
> > 你可以解压.gz文件，然后sftp上传替换文件还原设置，备份文件夹根目录下除了openclash放入/etc/config，其他都在/etc/openclash。
> 
> 这样也太复杂了额，我想的是能够设计导入配置的地方，恢复之前的备份，方便大家升级后出现问题后，可以及时恢复之前的版本，而不是重新安装一遍openclash

那直接在openwrt的 系统 -> 备份/升级里恢复应该就行了。

**Comment by icucuio** [comment]
> > > 你可以解压.gz文件，然后sftp上传替换文件还原设置，备份文件夹根目录下除了openclash放入/etc/config，其他都在/etc/openclash。
> > 
> > 
> > 这样也太复杂了额，我想的是能够设计导入配置的地方，恢复之前的备份，方便大家升级后出现问题后，可以及时恢复之前的版本，而不是重新安装一遍openclash
> 
> 那直接在openwrt的 系统 -> 备份/升级里恢复应该就行了。

是那样设计吗？那样不会覆盖整个openwrt系统的配置吗？毕竟这里备份的只是openclash的，openwrt别的配置文件没有被包括，从那里导入后，虽然可能能够恢复openclash，但是会不会导致openwrt的配置丢失？

**Comment by michaelchen644** [comment]
> > > > 你可以解压.gz文件，然后sftp上传替换文件还原设置，备份文件夹根目录下除了openclash放入/etc/config，其他都在/etc/openclash。
> > > 
> > > 
> > > 这样也太复杂了额，我想的是能够设计导入配置的地方，恢复之前的备份，方便大家升级后出现问题后，可以及时恢复之前的版本，而不是重新安装一遍openclash
> > 
> > 
> > 那直接在openwrt的 系统 -> 备份/升级里恢复应该就行了。
> 
> 是那样设计吗？那样不会覆盖整个openwrt系统的配置吗？毕竟这里备份的只是openclash的，openwrt别的配置文件没有被包括，从那里导入后，虽然可能能够恢复openclash，但是会不会导致openwrt的配置丢失？

兄弟千万别在备份/升级里恢复，备份文件目录和openwrt备份文件是不一样的。刚刚试了下不会覆盖其他设置，但目录不对备份文件全恢复到根目录去了...233。要是目录对了就方便了

**Comment by vernesong** [comment]
![image](https://user-images.githubusercontent.com/42875168/152397175-637dc13d-5912-4954-92b1-fbcb9447f6c8.png)

**Comment by michaelchen644** [comment]
还是没玩透啊！openclash这东西太好玩了，只要不停更，我可以玩到去逝

**Comment by icucuio** [comment]
> > > > > 你可以解压.gz文件，然后sftp上传替换文件还原设置，备份文件夹根目录下除了openclash放入/etc/config，其他都在/etc/openclash。
> > > > 
> > > > 
> > > > 这样也太复杂了额，我想的是能够设计导入配置的地方，恢复之前的备份，方便大家升级后出现问题后，可以及时恢复之前的版本，而不是重新安装一遍openclash
> > > 
> > > 
> > > 那直接在openwrt的 系统 -> 备份/升级里恢复应该就行了。
> > 
> > 
> > 是那样设计吗？那样不会覆盖整个openwrt系统的配置吗？毕竟这里备份的只是openclash的，openwrt别的配置文件没有被包括，从那里导入后，虽然可能能够恢复openclash，但是会不会导致openwrt的配置丢失？
> 
> 兄弟千万别在备份/升级里恢复，备份文件目录和openwrt备份文件是不一样的。刚刚试了下不会覆盖其他设置，但目录不对备份文件全恢复到根目录去了...233。要是目录对了就方便了

和我想象的一样，你当小白鼠了，不好意思，让你踩坑了。

**Comment by icucuio** [comment]
> ![image](https://user-images.githubusercontent.com/42875168/152397175-637dc13d-5912-4954-92b1-fbcb9447f6c8.png)

大佬，强烈建议能不能把备份和恢复按键放一起，我相信90%的人不知道备份恢复时在配置那里，而且还需要选择。可能很多人都遇到过升级后想回滚的情况。

**Comment by edmondfr** [comment]
不敢点一键更新，点了两次程序都自杀了，菜单上也找不到。。。

**Comment by icksky** [comment]
> 不敢点一键更新，点了两次程序都自杀了，菜单上也找不到。。。

我也是...更新后直接挂了, 然后想恢复, 把路由器搞挂了 只能重装...废了一晚上

**Comment by magic-monkey** [comment]
> > ![image](https://user-images.githubusercontent.com/42875168/152397175-637dc13d-5912-4954-92b1-fbcb9447f6c8.png)
> 
> 大佬，强烈建议能不能把备份和恢复按键放一起，我相信90%的人不知道备份恢复时在配置那里，而且还需要选择。可能很多人都遇到过升级后想回滚的情况。

这个好像是原版openwrt的备份恢复界面，还有得选择，如果自己编译的lede固件的话连这个选择都没有，强烈建议还是出一个直接在openclash里面恢复备份的选项

**Comment by vivikuyo** [comment]
> > > > > > 你可以解压.gz文件，然后sftp上传替换文件还原设置，备份文件夹根目录下除了openclash放入/etc/config，其他都在/etc/openclash。
> > > > > 
> > > > > 
> > > > > 这样也太复杂了额，我想的是能够设计导入配置的地方，恢复之前的备份，方便大家升级后出现问题后，可以及时恢复之前的版本，而不是重新安装一遍openclash
> > > > 
> > > > 
> > > > 那直接在openwrt的 系统 -> 备份/升级里恢复应该就行了。
> > > 
> > > 
> > > 是那样设计吗？那样不会覆盖整个openwrt系统的配置吗？毕竟这里备份的只是openclash的，openwrt别的配置文件没有被包括，从那里导入后，虽然可能能够恢复openclash，但是会不会导致openwrt的配置丢失？
> > 
> > 
> > 兄弟千万别在备份/升级里恢复，备份文件目录和openwrt备份文件是不一样的。刚刚试了下不会覆盖其他设置，但目录不对备份文件全恢复到根目录去了...233。要是目录对了就方便了
> 
> 和我想象的一样，你当小白鼠了，不好意思，让你踩坑了。

口胡...作者都表明了直接在刷机那恢复设置

**Comment by peoplechinapower** [comment]
> 你可以解压.gz文件，然后sftp上传替换文件还原设置，备份文件夹根目录下除了openclash放入/etc/config，其他都在/etc/openclash。

这是正解 感谢

**Comment by Wyatt323** [comment]
这个备份点了之后没有反应啊，怎么怎么下载的备份文件
