### ISSUE TITLE
三方规则集下载/更新的问题

### ISSUE THREAD

**Issue by michaelchen644** [vernesong/OpenClash#2015]
在规则集与策略组管理 -> 第三方规则集管理中下载/更新规则时，文件大小显示0.1kb，查看yaml文件内容为
Invalid URL. The URL structure is /gh/user/repo@version/file.js
![image](https://user-images.githubusercontent.com/66155014/152355342-19ebab70-4170-4252-b204-de40893c2c1c.png)

**Comment by vernesong** [comment]
更新插件

**Comment by michaelchen644** [comment]
> 更新插件

配置好config，然后启动一下openclash，规则集yaml就会自己拉取写入了
