### ISSUE TITLE
开启openclash之后，win10桌面右下角的网络标识显示断网

### ISSUE THREAD

**Issue by Karmylr** [vernesong/OpenClash#2019]
如题。但是有网络。

**Comment by veik** [comment]
我也会，但是我不用fake-IP模式的话，大部分时间都是好的。也好奇什么原因，不知道是不是IPv6的原因。

**Comment by hprandom** [comment]
我也是。之前一直好好的，前几天重新装了windows后就出现了。如果关了openclash，就显示正常。
问题是我重新安装windows10的前后，没有去动过openclash的设置……

有哪位高手能指点一下怎么设置吗？
