### ISSUE TITLE
[Feature] Request Custom Providers creator and editor

### ISSUE THREAD

**Issue by djoeni** [vernesong/OpenClash#2026]
For now in Provider file manage it only displayed list...it would be nice if it can create custom provider files too with simple code editor for editing.

Thanks

**Comment by Nurwahyu99** [comment]
like this? 
![image](https://user-images.githubusercontent.com/24325593/153103895-8164fa52-b028-426a-a77e-4d0abedfc50c.png)

**Comment by Nurwahyu99** [comment]
![image](https://user-images.githubusercontent.com/24325593/153103961-483dc507-2207-45c3-9a02-89f3c7348a8d.png)
 i added config editor on tab openclash with tiny file manager

**Comment by djoeni** [comment]
@Nurwahyu99 it would be best putting in their respective field like this

![Screenshot  - LuCI](https://user-images.githubusercontent.com/20867437/153273302-e61969f0-b6aa-45f4-9e19-3f3e04c8da3e.png)

and openclash already have great built-in code editor which support syntax check for error (the one in config manage)

**Comment by djoeni** [comment]
thanks for this feature...really helpful
