### ISSUE TITLE
OpenClash 全局模式无效

### ISSUE THREAD

**Issue by palemoky** [vernesong/OpenClash#2027]
我发现 OpenClash 有多个地方能够设置代理模式，但在一处设置了代理模式后，其它地方的状态都不一致
1. 运行状态的代理模式
![运行状态的代理模式](https://user-images.githubusercontent.com/21208635/152805409-ed58782b-6c8f-493d-a2e3-0ee0fda7683a.png)

2. 全局设置中的代理模式
![全局设置中的代理模式](https://user-images.githubusercontent.com/21208635/152805534-c67239fa-1942-4ff2-adab-017cdbd7ff5b.png)

3. 控制面板中的代理模式
![控制面板中的代理模式](https://user-images.githubusercontent.com/21208635/152805659-55012a87-3266-41ef-837e-f6fee198046c.png)

我全部调整为全局代理模式后，在规则代理模式下能打开的 Google 在全局模式下反而打不开了，ip138 显示的 IP 也不是代理 IP。配置文件软路由和电脑都用的同一份，电脑的全局是没有问题的，ShadowSocksR Plus+ 的全局模式也是正常的，请问 OpenClash 是我哪里配置有问题吗？

_Originally posted by @palemoky in https://github.com/vernesong/OpenClash/discussions/2025_

**Comment by vernesong** [comment]
全局设置里面的是启动时的默认施设置，另外两个地方是临时修改

**Comment by palemoky** [comment]
> 全局设置里面的是启动时的默认设置，另外两个地方是临时修改

我修改了两个临时开关中的一个，另一个的状态就不一致了，这个是正常的吗？还是我要打开两个临时开关才行呢？

**Comment by XRSec** [comment]
我也不行，求解

**Comment by HideNameUser** [comment]
同样求解

**Comment by xiyu01** [comment]
> 通过 debug 排查日志，问题已经解决了，感谢 v 大

请教最后您的问题出在哪里了？

**Comment by palemoky** [comment]
> > 通过 debug 排查日志，问题已经解决了，感谢 v 大
> 
> 请教最后您的问题出在哪里了？

我记得好像是clash配置文件的问题，你打开 debug 仔细看下日志，里边有线索
