### ISSUE TITLE
王者荣耀卡顿

### ISSUE THREAD

**Issue by peonleon** [vernesong/OpenClash#2028]
不知何原因最近开始只要开启openclash王者荣耀就会卡顿 无法游戏 目测策略组中没有设置过 udp也关闭了

**Comment by eyaeya** [comment]
同发生

**Comment by Keyboards-Liu** [comment]
同发生，没找到好办法

**Comment by lhc87227** [comment]
有人解决了么

**Comment by Keyboards-Liu** [comment]
> 有人解决了么

![image](https://user-images.githubusercontent.com/43167158/168508305-9a537f3e-4963-44c7-9426-8b733c9a51ee.png)
目前已解决，设置为FakeIP（UDP-TUN，TCP-转发），另外需要本地DNS劫持并自定义一些可用的DNS地址
