### ISSUE TITLE
[Suggestion] 依赖包添加ipset

### ISSUE THREAD

**Issue by L0snight** [vernesong/OpenClash#203]
在使用tun模式的时候发现外网连不通的情况，然后查了一下路由表，发现mangle表没有set mark的相关rule，进一步发现是ipset localnetwork 没有生效，最后发现是没有安装ipset这个包。由于我用的是官方的openwrt固件，相关依赖都是按照wiki来安的。不知道其他的固件是否默认自带ipset。所以建议相关依赖可以加上ipset这个package，这样的话就能防止有人因没有ipset而导致tun模式失效的情况

**Comment by vernesong** [comment]
因为目前没有强制使用tun，所以强依赖没有加上去，我会在说明里注明
