### ISSUE TITLE
openclash擅自更改我的rule-providers订阅地址

### ISSUE THREAD

**Issue by Slotheve** [vernesong/OpenClash#2030]
openclash擅自更改我的rule-providers订阅地址,我使用的是github raw,但是使用配置后他擅自改成了jsdelivr地址,但我并不想用jsdelivr

运行配置
rule-providers:
  Microsoft:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/Slotheve/Clash-Rule-Set@release/Microsoft.txt
    path: "./rule_provider/Microsoft.yaml"
    interval: 86400
  Apple:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/Slotheve/Clash-Rule-Set@release/Apple.txt
    path: "./rule_provider/Apple.yaml"
    interval: 86400
  Game:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/Slotheve/Clash-Rule-Set@release/Game.txt
    path: "./rule_provider/Game.yaml"
    interval: 86400
  Bilibili:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/Slotheve/Clash-Rule-Set@release/Bilibili.txt
    path: "./rule_provider/Bilibili.yaml"
    interval: 86400
  Direct:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/Slotheve/Clash-Rule-Set@release/Direct.txt
    path: "./rule_provider/Direct.yaml"
    interval: 86400
  CNIP:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/Slotheve/Clash-Rule-Set@release/CNIP.txt
    path: "./rule_provider/CNIP.yaml"
    interval: 86400
  Process:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/Slotheve/Clash-Rule-Set@release/Process.txt
    path: "./rule_provider/Process.yaml"
    interval: 86400
  Proxy:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/Slotheve/Clash-Rule-Set@release/Proxy.txt
    path: "./rule_provider/Proxy.yaml"
    interval: 86400
rules:
- IP-CIDR,198.18.0.1/16,REJECT,no-resolve
- RULE-SET,Microsoft,Microsoft
- RULE-SET,Apple,Apple
- RULE-SET,Game,Game
- RULE-SET,Bilibili,Bilibili
- RULE-SET,Proxy,PROXY
- RULE-SET,Process,DIRECT
- RULE-SET,CNIP,DIRECT
- RULE-SET,Direct,DIRECT
- GEOIP,CN,DIRECT
- MATCH,PROXY
dns:
  nameserver:
  - 127.0.0.1:5335
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  listen: 127.0.0.1:7874
  fake-ip-filter:
  - "*.lan"
  - "*.localdomain"
  - "*.example"
  - "*.invalid"
  - "*.localhost"
  - "*.test"
  - "*.local"
  - "*.home.arpa"
  - time.*.com
  - time.*.gov
  - time.*.edu.cn
  - time.*.apple.com
  - time1.*.com
  - time2.*.com
  - time3.*.com
  - time4.*.com
  - time5.*.com
  - time6.*.com
  - time7.*.com
  - ntp.*.com
  - ntp1.*.com
  - ntp2.*.com
  - ntp3.*.com
  - ntp4.*.com
  - ntp5.*.com
  - ntp6.*.com
  - ntp7.*.com
  - "*.time.edu.cn"
  - "*.ntp.org.cn"
  - "+.pool.ntp.org"
  - time1.cloud.tencent.com
  - music.163.com
  - "*.music.163.com"
  - "*.126.net"
  - musicapi.taihe.com
  - music.taihe.com
  - songsearch.kugou.com
  - trackercdn.kugou.com
  - "*.kuwo.cn"
  - api-jooxtt.sanook.com
  - api.joox.com
  - joox.com
  - y.qq.com
  - "*.y.qq.com"
  - streamoc.music.tc.qq.com
  - mobileoc.music.tc.qq.com
  - isure.stream.qqmusic.qq.com
  - dl.stream.qqmusic.qq.com
  - aqqmusic.tc.qq.com
  - amobile.music.tc.qq.com
  - "*.xiami.com"
  - "*.music.migu.cn"
  - music.migu.cn
  - "+.msftconnecttest.com"
  - "+.msftncsi.com"
  - msftconnecttest.com
  - msftncsi.com
  - localhost.ptlogin2.qq.com
  - localhost.sec.qq.com
  - "+.srv.nintendo.net"
  - "+.stun.playstation.net"
  - xbox.*.microsoft.com
  - xnotify.xboxlive.com
  - "+.battlenet.com.cn"
  - "+.wotgame.cn"
  - "+.wggames.cn"
  - "+.wowsgame.cn"
  - "+.wargaming.net"
  - proxy.golang.org
  - stun.*.*
  - stun.*.*.*
  - "+.stun.*.*"
  - "+.stun.*.*.*"
  - "+.stun.*.*.*.*"
  - heartbeat.belkin.com
  - "*.linksys.com"
  - "*.linksyssmartwifi.com"
  - "*.router.asus.com"
  - mesu.apple.com
  - swscan.apple.com
  - swquery.apple.com
  - swdownload.apple.com
  - swcdn.apple.com
  - swdist.apple.com
  - lens.l.google.com
  - stun.l.google.com
  - "+.nflxvideo.net"
  - "*.square-enix.com"
  - "*.finalfantasyxiv.com"
  - "*.ffxiv.com"
  - "*.mcdn.bilivideo.cn"
  - "+.media.dssott.com"
  default-nameserver:
  - 127.0.0.1:5335
redir-port: 7892
tproxy-port: 7895
mixed-port: 7893
secret: '123456'
bind-address: "*"
external-ui: "/usr/share/openclash/dashboard"
ipv6: false
tun:
  enable: true
  stack: system
  dns-hijack:
  - tcp://8.8.8.8:53
  - tcp://8.8.4.4:53
profile:
  store-selected: true
  store-fake-ip: true

上传配置
rule-providers:
  Microsoft:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/Slotheve/Clash-Rule-Set/release/Microsoft.txt"
    path: ./ruleset/Microsoft.yaml
    interval: 86400

  Apple:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/Slotheve/Clash-Rule-Set/release/Apple.txt"
    path: ./ruleset/Apple.yaml
    interval: 86400

  Game:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/Slotheve/Clash-Rule-Set/release/Game.txt"
    path: ./ruleset/Game.yaml
    interval: 86400
    
  Bilibili:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/Slotheve/Clash-Rule-Set/release/Bilibili.txt"
    path: ./ruleset/Bilibili.yaml
    interval: 86400

  Direct:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/Slotheve/Clash-Rule-Set/release/Direct.txt"
    path: ./ruleset/Direct.yaml
    interval: 86400

  CNIP:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/Slotheve/Clash-Rule-Set/release/CNIP.txt"
    path: ./ruleset/CNIP.yaml
    interval: 86400

  Process:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/Slotheve/Clash-Rule-Set/release/Process.txt"
    path: ./ruleset/Process.yaml
    interval: 86400

  Proxy:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/Slotheve/Clash-Rule-Set/release/Proxy.txt"
    path: ./ruleset/Proxy.yaml
    interval: 86400

rules:
  - RULE-SET,Microsoft,Microsoft
  - RULE-SET,Apple,Apple
  - RULE-SET,Game,Game
  - RULE-SET,Bilibili,Bilibili
  - RULE-SET,Proxy,PROXY
  - RULE-SET,Process,DIRECT
  - RULE-SET,CNIP,DIRECT
  - RULE-SET,Direct,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,PROXY

**Comment by Water-blue7** [comment]
## 老铁,我不能使用rule-providers:
你知道啥原因吗?链接我都检查了,全都可以打开.
![image](https://user-images.githubusercontent.com/60252035/154021717-64029d54-a843-422c-9d36-eefb712832bd.png)
