### ISSUE TITLE
选择更新分支是无法锁定的？

### ISSUE THREAD

**Issue by wangjianpro999** [vernesong/OpenClash#2035]
选择更新分支是无法锁定的？
![Screenshot_2022-02-10-11-41-27-755_com microsoft emmx](https://user-images.githubusercontent.com/79621192/153333047-d1d1fec4-d18f-42fe-b950-d8b2605c9eff.jpg)
保存配置也无法锁定

**Comment by AXBNG** [comment]
你更新过一次就锁定了

**Comment by wangjianpro999** [comment]
> 你更新过一次就锁定了

去更新过多次了，依然没锁定

**Comment by AXBNG** [comment]
> > 你更新过一次就锁定了
> 
> 更新过多次了，依然没锁定

反正我是这样，从0.44.09选dev分支更新到0.44.21，就会保持在dev分支，没的问题
