### ISSUE TITLE
希望Netflix流媒体增强模式支持纯v6解锁的情况

### ISSUE THREAD

**Issue by evolsnow** [vernesong/OpenClash#2036]
设备是android tv，观察到有直接通过ip访问的情况（23.246.56.138），开启netflix域名预解析后，这ip会被替换成ipv4-c014-hkg001-ix.1.oca.nflxvideo.net。
不过机场一般都是只支持ipv6解锁，所以试了下把netflix预解析域名列表文件里的ipv4都替换成了ipv6（因为ipv6-c014-hkg001-ix.1.oca.nflxvideo.net对应的A记录也是23.246.56.138），这样交给代理服务器时就能正常走到v6解锁了。
但这做法比较黑，希望有更优雅更稳定的方法。所以有两个问题：
1. 流媒体增强能否支持只预解析v6开头的域名，或者ip优先反查v6域名
2. 23.246.56.138这个v4 ip是哪来的，app自己通过8.8.8.8发起的查询么

**Comment by vernesong** [comment]
这个应该不影响解锁吧

**Comment by vernesong** [comment]
客户端会先查询的，机场既然只能v6解锁在连接前就会告诉设备用v6地址连接

**Comment by evolsnow** [comment]
除电视外其他设备都没问题，我猜测是因为电视netflix会主动向8.8.8.8发起域名查询(虽然被劫持到本地dns了)，所以即使机场返回的是v6域名，本地解析后拿到的也是个v4 ip（路由关闭了v6解析和代理）。

**Comment by vernesong** [comment]
电视的8.8.8.8不清楚是doh还是什么，简单的udp和tcp用TUN模式可以劫持，你可以在奈飞规则里面加一条8.8.8.8和44的规则试试

**Comment by nameless3721** [comment]
sed -i 's/ipv4/ipv6/g' /usr/share/openclash/res/Netflix_Domains.list
sed -i 's/ipv4/ipv6/g'  /etc/openclash/custom/openclash_custom_netflix_domains.list
可以尝试把预解析ipv4的都改成ipv6 因为v6nflxvideo域名的v4地址和v4nflxvideo域名一样导致先解析v4nflxvideo域名的话只有v4域名映射回来 v6域名也有v4ip理论不影响v4吧  反正v6解锁节点可以试试这个

**Comment by icefall-michael** [comment]
> sed -i 's/ipv4/ipv6/g' /usr/share/openclash/res/Netflix_Domains.list sed -i 's/ipv4/ipv6/g' /etc/openclash/custom/openclash_custom_netflix_domains.list 可以尝试把预解析ipv4的都改成ipv6 因为v6nflxvideo域名的v4地址和v4nflxvideo域名一样导致先解析v4nflxvideo域名的话只有v4域名映射回来 v6域名也有v4ip理论不影响v4吧 反正v6解锁节点可以试试这个 v4nflxvideo 域名没有v6的ip所以服务器肯定连不了v6

改了还是预解析为ipv4

**Comment by nameless3721** [comment]
> > sed -i 's/ipv4/ipv6/g' /usr/share/openclash/res/Netflix_Domains.list sed -i 's/ipv4/ipv6/g' /etc/openclash/custom/openclash_custom_netflix_domains.list 可以尝试把预解析ipv4的都改成ipv6 因为v6nflxvideo域名的v4地址和v4nflxvideo域名一样导致先解析v4nflxvideo域名的话只有v4域名映射回来 v6域名也有v4ip理论不影响v4吧 反正v6解锁节点可以试试这个 v4nflxvideo 域名没有v6的ip所以服务器肯定连不了v6
> 
> 改了还是预解析为ipv4

那还是只能说你有地方先解析出ipv4导致的 同ip的域名谁先解析就用谁了  可以尝试最新openclash的meta内核有域名探测不开预解析应该也可以

**Comment by icefall-michael** [comment]
> > > sed -i 's/ipv4/ipv6/g' /usr/share/openclash/res/Netflix_Domains.list sed -i 's/ipv4/ipv6/g' /etc/openclash/custom/openclash_custom_netflix_domains.list 可以尝试把预解析ipv4的都改成ipv6 因为v6nflxvideo域名的v4地址和v4nflxvideo域名一样导致先解析v4nflxvideo域名的话只有v4域名映射回来 v6域名也有v4ip理论不影响v4吧 反正v6解锁节点可以试试这个 v4nflxvideo 域名没有v6的ip所以服务器肯定连不了v6
> > 
> > 
> > 改了还是预解析为ipv4
> 
> 那还是只能说你有地方先解析出ipv4导致的 同ip的域名谁先解析就用谁了 可以尝试最新openclash的meta内核有域名探测不开预解析应该也可以

redir-host模式下，选了强制远程域名解析就可以了，不知道这个远程域名解析有什么其他影响的？

**Comment by shuoyue21** [comment]
同，我也有楼主这样的问题，楼上的方法都试了，观看日志还是v4开头的域名

**Comment by shuoyue21** [comment]
meta内核可以开启强制域名探测,加入Netflix的域名后缀,实测可以解决,v4域名变v6域名
