### ISSUE TITLE
cfw上能用的配置文件的订阅节点在openclash上全部失效

### ISSUE THREAD

**Issue by SaarChaffee** [vernesong/OpenClash#2037]
我现在用的cfw和cfa的配置文件的订阅链接在OpenClash中订阅后，启动openclash发现全部节点都是灰的，全都没连上。订阅链接是经过第三方订阅转换后的。我进log看的时候发现一大堆输出 `connect error: all DNS requests failed, first error: dial tcp4 8.8.8.8:853: i/o timeout`

**Comment by vernesong** [comment]
插件要单独指定模式，部分设置不会按照配置文件，你插件切换到fakeip就可以了

**Comment by SaarChaffee** [comment]
问题解决了，，我在上游DNS加了一堆fallback
