### ISSUE TITLE
建议增加配置文件预处理功能。

### ISSUE THREAD

**Issue by xdbcx** [vernesong/OpenClash#2038]
Clash for windows可以通过Parsers在更新订阅时在配置文件中插入自定义规则，openclash能不能也加入配置文件预处理功能啊。

**Comment by LiweiDong** [comment]
我也有类似需求。 在机场提供的订阅里增加一组策略和规则。pc上用CFW的Mixin实现了。 openwrt里太复杂 试了半天没有成功。

**Comment by LiweiDong** [comment]
> 不能，在自定义规则里面编辑

能否在自定义规则里 添加一个proxy-groups

**Comment by lswsx** [comment]
我现在也遇到这个问题了，现在解决了吗？

**Comment by PangBoUShrooo2002** [comment]
我也遇到这个问题了，真是不好搞。想手动添加一个relay节点，但是不想重新改订阅转换的配置文件

**Comment by goforu** [comment]
+1

**Comment by vernesong** [comment]
覆写设置，开发者选项

**Comment by xxp2277** [comment]
> 覆写设置，开发者选项

复制规则进去，不生效。
