### ISSUE TITLE
openclash 会导致 WAN 入网的防火墙失效

### ISSUE THREAD

**Issue by ccinls** [vernesong/OpenClash#204]
![image](https://user-images.githubusercontent.com/1269356/76152819-27dddd80-60ff-11ea-9119-c5bd6b173fb8.png)
内网的端口被开放，导致一直有恶意登录尝试

**Comment by vernesong** [comment]
wan口ip的访问已做return处理，等待更新

**Comment by kl9800** [comment]
大佬我之前装完以后，看到这个问题，吓尿了赶紧拆卸。。。
所以想问一下大概什么时候能有更新？软件本身还是很NB的很想用！！
