### ISSUE TITLE
openclash能否跟随openwrt一起启动，例如openwrt关机重启后，是否也会自动重启？

### ISSUE THREAD

**Issue by yingkun1** [vernesong/OpenClash#2041]
openclash能否跟随openwrt一起启动，例如openwrt关机重启后，是否也会自动重启？我看到配置页面有这个按钮，但是无法勾选
![微信截图_20220211192039](https://user-images.githubusercontent.com/44250060/153583119-a1914f47-6899-4775-a95a-10d2b499b47e.png)

**Comment by wangjianpro999** [comment]
一直都能啊

**Comment by yingkun1** [comment]
这个能勾选？你用的是哪个版本，我这边是0.42.10

**Comment by yingkun1** [comment]
![54edbd67891079d2a46bbda9ea6e489](https://user-images.githubusercontent.com/44250060/153603105-0295df70-a461-4733-a57d-60443b6d5c6e.jpg)

**Comment by AXBNG** [comment]
不用去选，默认开机自启

你但凡动手重启一下路由就能得到答案，何必又是发issue又是拍照的......

**Comment by yingkun1** [comment]
因为我开始测试过一次，重启后配置就失效了，需要手动点击启动openclash，系统重走那诗歌步骤才行

**Comment by vernesong** [comment]
版本太旧了，更新

**Comment by yingkun1** [comment]
最新的那个版本好像有问题，在第六步总是抛出异常，警告: 代理集文件检查超时，如启动失败请到日志页面查看详细信息！

**Comment by vernesong** [comment]
好的
