### ISSUE TITLE
[Bug] Deleted part of config when applying from Servers and Groups

### ISSUE THREAD

**Issue by djoeni** [vernesong/OpenClash#2044]
Just got updated on v0.44.22-beta to test new indentation configuration and found out that when applying from Servers and Groups part of default config starting from port and dns got deleted resulting in failure connection.

thanks

**Comment by vernesong** [comment]
ok, I found there is no way to change the yaml style, so I will revert the commit, sorry

**Comment by djoeni** [comment]
no problem it just a minor case
