### ISSUE TITLE
【求助】clash打开Google和Youtube极不稳定，但其他网站可秒开

### ISSUE THREAD

**Issue by Johnstfrank** [vernesong/OpenClash#2045]
自从1月份以来就不时出现无法打开 Google 和 Youtube 的情况（其实 GitHub 也不行，这条我是用手机发的），偶尔能打开，但很不稳定，其他网站则不受影响可以秒开。手机端我用的是 Shadowrocket，所有网站都没有问题

无论是 Global/Rule/Direct 都没有办法解决

参考了[https://github.com/vernesong/OpenClash/issues/1374](url) 里的清理 DNS 缓存的建议，没有太多改善。请问有朋友知道解决方法吗？感谢！

**Comment by machine-doll** [comment]
是不是ipv6的问题？
禁用IPv6试试

**Comment by fjjking** [comment]
可以试一试换一个DNS，我之前用114也是天天Google YouTube打不开换了阿里的没出现过了

**Comment by Johnstfrank** [comment]
> 可以试一试换一个DNS，我之前用114也是天天Google YouTube打不开换了阿里的没出现过了

等下试试，可以的话告诉大家，谢谢！

**Comment by Johnstfrank** [comment]
> 可以试一试换一个DNS，我之前用114也是天天Google YouTube打不开换了阿里的没出现过了

用了你建议的方法，没有改善。我有个朋友用的是 mac 上的客户端，没有出现这个问题...
