### ISSUE TITLE
请教关于openclash和adguard home的设置问题

### ISSUE THREAD

**Issue by Jacob-LYC** [vernesong/OpenClash#2048]
之前一直使用pve安装openwrt（以下简称op）虚拟机的方式搭梯上网，后来发现广告太多，网页开启速度也不是很理想，遂准备加入adguardhome（以下简称adg）进行dns解析，但却始终不成功。在网络上翻遍了教程，查阅了很多其他先行者的资料，也私下请教了几个人（包括淘宝店），始终不能成功设置，所以来这里请教一下大家，希望各位能够不吝赐教。

* 一、网络环境
（互联网ip）光猫拨号（局域网ip1段）---（局域网ip1段）PVE下的op（局域网ip2段）---AP
       1、局域网ip1段只用于链接光猫和op的wan口，网关为光猫局域网ip；
       2、op开启dhcp，op的lan口为局域网ip2段的网关（ip为A），openclash（以下简称oc）在op内，；
       3、adg由PVE下的容器单独创建（ip为B），未在op内，在PVE下共用op的lan口；
       4、op和oc都是直接拉取代码编译的。

* 二、目前的网络状态
       1、整个网络中如果不加入adg，仅使用  光猫+op+oc，则网络一切正常；
       2、如加入adg：adg网关为A（op的lan口地址），adg地址为B（解析端口默认53），则无法进行DNS解析。
       op关闭Turbo ACC，注销防火墙内53端口转发；lan、wan设置中均未填写dns。

* 三、小白的疑惑
       1、假如我在op内lan、wan处添加非adg的正确DNS，则可以正常访问网页，一旦取消正确DNS或只填入adg地址就不能访问。这样是否表示必须在此处填写正确的dns？但假如填写正确的DNS，又是否意味着adg并未起效？
       2、在“二”中，加入adg后无论怎么设置，adg的上游 DNS 服务器都是测试失败；

       不瞒大家，前前后后一共试了20多个小时，始终不明白设置错误在哪个地方，导致解析域名失败。还请各位知晓能够给予帮助。
       感谢！

**Comment by paladin4fan** [comment]
你是否尝试过
LAN口WAN口的DNS不动 单纯改Dnsmasq的设置，把adh设置成dnsmasq的唯一上游服务器
然后再到adh里，把上游DNS设置成Openclash的监听端口

**Comment by Jacob-LYC** [comment]
这个还没有试过。我去试一试然后再回复。

**Comment by zpengcom** [comment]
我的设置:
**路由（53）→ ADG(54) → Clash(7874)**

- ADG: 服务-AdGuard Home，点更新核心，点启用，重定向选择「无（也可作为dnsmasq的上游服务器）」，在点手动设置中将ADG的端口改成54（可不改，改的话和下面统一），改完保存&应用

ADG: 上游的 DNS 伺服器：127.0.0.1:7874 (指向clash)  DNS下游：127.0.0.1:54 等

- CLASH: 服务-OpenClash-全局设置-dns设置，去掉本地dns劫持（不然会修改下面的DHCP/DNS转发），自定义上游dns服务器可勾，不勾选追加上游DNS，Fake-IP 持久化可勾，应用配置

如果是Fack-IP模式    开启高级设置 指定（第二）DNS 服务器 添加本地域名 解决本地不能访问

- 网络-DHCP/DNS-高级设置，把DNS 转发改成127.0.0.1#54 （转发到ADG）
