### ISSUE TITLE
禁ping的服务器检测

### ISSUE THREAD

**Issue by kl9800** [vernesong/OpenClash#205]
大佬好，我为了安全，服务器开启了禁ping，此时会影响到“最低延迟”模式的选择结果，但那台服务器是我最喜欢的也是最快的，能不能采取其他检测方式？

**Comment by vernesong** [comment]
延迟策略非ping，采用的是http-get,服务器禁止ping不会有影响

**Comment by kl9800** [comment]
可是我v2节点全部是检测时无法连通 （但可以使用），我用的是  v2 + ws + tls ，

**Comment by wangxin6** [comment]
> 可是我v2节点全部是检测时无法连通 （但可以使用），我用的是 v2 + ws + tls ，

节点配置增加
`skip-cert-verify: true`

**Comment by kl9800** [comment]
> > 可是我v2节点全部是检测时无法连通 （但可以使用），我用的是 v2 + ws + tls ，
> 
> 节点配置增加
> `skip-cert-verify: true`

谢谢！
