### ISSUE TITLE
更新大陆白名单导致挂起

### ISSUE THREAD

**Issue by wangjianpro999** [vernesong/OpenClash#2051]
大陆白名单永远是10月24号的，手动自动更新都无效。
每次手动更新白名单时openclash都会挂起并导致断流。长时间停留在正在更新数据页面。。。
![Screenshot_2022-02-14-12-04-32-301_com microsoft emmx](https://user-images.githubusercontent.com/79621192/153798558-685bd918-53d3-4c86-b59d-be85e5e53806.jpg)

![Screenshot_2022-02-14-11-49-58-700_com microsoft emmx](https://user-images.githubusercontent.com/79621192/153798578-b8356b76-ffca-4cb5-a4b1-73ee7408199d.jpg)

![Screenshot_2022-02-14-12-04-24-233_com microsoft emmx](https://user-images.githubusercontent.com/79621192/153798595-83ac4810-ab53-4aac-a161-19a7c4ec1169.jpg)

**Comment by vernesong** [comment]
哪个版本的白名单

**Comment by wangjianpro999** [comment]
> 哪个版本的白名单

![Screenshot_2022-02-14-14-02-36-663_com microsoft emmx](https://user-images.githubusercontent.com/79621192/153808743-50e205e2-5848-489f-b6d3-a336f21ebb78.jpg)
