### ISSUE TITLE
为什么这个规则不能正常更新？

### ISSUE THREAD

**Issue by Pacio** [vernesong/OpenClash#2052]
![image](https://user-images.githubusercontent.com/6836705/153812178-df0e9c00-880e-4790-b021-de2dd0c55a26.png)
默认的lhie1可以正常更新，这个好像不行，但是这个更好用，麻烦看看咋回事

**Comment by vernesong** [comment]
作者删了，其实也没啥必要更新，里面的provider会自动更新
