### ISSUE TITLE
从国外查询（IP.SB）始终是 国内IP

### ISSUE THREAD

**Issue by assist726** [vernesong/OpenClash#2054]
Redir-host 模式 - 开启 Global - v1.9.0-7-gb1a639f 最新内核
访问一下网站或者在控制面板内查看 IP.SB国外始终都是国内的
https://ip.skk.moe/

不过同线路在使用Clash for Windows 的global 就是正常海外

这是Openclash的什么问题导致IP地址没有被替换?

这也导致我领英一直会被从新指向.cn网站然后就无法使用了

**Comment by aiwu12** [comment]
目前使用 Redir-host，rule，没有问题

**Comment by assist726** [comment]
@aiwu12 我是最开始用rule也不行才尝试的global, 看到有人说因为ip sb没有正确加到规则内会有错误

**Comment by lemonBill** [comment]
> Redir-host 模式 - 开启 Global - v1.9.0-7-gb1a639f 最新内核 访问一下网站或者在控制面板内查看 IP.SB国外始终都是国内的 https://ip.skk.moe/
> 
> 不过同线路在使用Clash for Windows 的global 就是正常海外
> 
> 这是Openclash的什么问题导致IP地址没有被替换?
> 
> 这也导致我领英一直会被从新指向.cn网站然后就无法使用了

我也遇到同样的情况，我是 Fake-IP （增强）模式运行，在全局设置 → 模式设置 → 绕过中国大陆 IPv6 去掉打钩，保存、应用配置，然后解决了
