### ISSUE TITLE
配置文件不可用?(clash for Windows Android可以用)

### ISSUE THREAD

**Issue by Water-blue7** [vernesong/OpenClash#2056]
# 在n1,op上装的openclash,配置文件是不是不能用这种远程规则啊
### 三软件里都有clash,我也不太清楚他们之间有啥关系.
![image](https://user-images.githubusercontent.com/60252035/154019804-94cfc3c0-79aa-4e22-99fb-4c793cb5f624.png)
![image](https://user-images.githubusercontent.com/60252035/154019784-7c2196b2-8fda-4a4f-824a-b4a99368df39.png)
### 错误提示
![image](https://user-images.githubusercontent.com/60252035/154021931-ffc88ee7-ec37-4450-b50a-29801adad96f.png)

**Comment by vernesong** [comment]
直连下载的，这个地址访问不了你只能更换

**Comment by Water-blue7** [comment]
> 直连下载的，这个地址访问不了你只能更换

这个链接我检查了,可以访问,我配置文件里所有的链接都能访问

**Comment by vernesong** [comment]
你在路由上面curl测试吧

**Comment by Water-blue7** [comment]
> 你在路由上面curl测试吧

我知道因为啥了,之前的dns有点问题,导致如果不开启openclash就断网,所以cdn的链接也不能正常下载.就出现了图片里那个链接下载失败.
