### ISSUE TITLE
王者荣耀不能玩?(不确定是不是openclash的问题)

### ISSUE THREAD

**Issue by Water-blue7** [vernesong/OpenClash#2057]
openclash升级到最新版后我玩王者荣耀的时候就不能进入选英雄的页面了,我不确是不是openclash的问题,因为我也改了dns,但是dns应该不会对游戏造成影响吧,用的阿里的dns

**Comment by Bradley-Chen** [comment]
看下规则是不是让王者走代理了，再试试把udp代理关掉。
如果你让游戏走了代理，且开始udp转发，但是你的节点不支持udp转发，就会导致无法进入游戏这类需要udp连接的软件

**Comment by avalanceonerd** [comment]
检查线路稳定性和dns是否连接正常
一个很反直觉的情况就是 clash连接外网如果不稳定也会影响到直连地址的稳定

**Comment by dahetaoa** [comment]
我也是，升级完以后进不去游戏
