### ISSUE TITLE
在线订阅转换  lhie1洞主规则完整版

### ISSUE THREAD

**Issue by QingHui653** [vernesong/OpenClash#2058]
iQiyi 规则无法打开

https://api.dler.io/getruleset?type=6&url=aHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL2RsZXItaW8vUnVsZXMvbWFzdGVyL1N1cmdlL1N1cmdlJTIwMy9Qcm92aWRlci9NZWRpYS9pUWl5aS5saXN0

导致配置文件无效

**Comment by QingHui653** [comment]
2022-02-15 17:21:24 level=fatal msg="Parse config error: initial rule provider iQiyi error: yaml: unmarshal errors:\n  line 1: cannot unmarshal !!str `Invalid...` into provider.RuleSchema"

**Comment by lbsnake** [comment]
电报上说被封转移到新库了
https://github.com/dler-io/Rules

**Comment by DawnAleax** [comment]
这个规则模板我也用不了了，还有什么类似分组多的模板吗

**Comment by imcaocao** [comment]
原规则网址被封，请更新规则网址

**Comment by vernesong** [comment]
晚点我自己更新一下吧

**Comment by Mrered** [comment]
> 

电报群还有吗？求群
