### ISSUE TITLE
自定义游戏规则怎么启用

### ISSUE THREAD

**Issue by paladin4fan** [vernesong/OpenClash#2059]
在配置文件管理->游戏规则文件列表里新建了一个游戏规则文件
再到规则集与策略组管理里想添加一条策略
但是 游戏规则与策略组管理->选择游戏规则里没有新建的规则
自定义规则集与策略组管理 新建一项条目 也只能从rule provider目录里选择规则 不能找到我新建的规则

**Comment by vernesong** [comment]
那就先用自定义规则集创建，最后使用区别没有区别

**Comment by paladin4fan** [comment]
> 那就先用自定义规则集创建，最后使用没有区别
OK
