### ISSUE TITLE
DNS不能正常配置#7874端口，自定义的上游DNS不能正常使用

### ISSUE THREAD

**Issue by zgs360** [vernesong/OpenClash#206]
启用DNS劫持本地，不能在Dnsmasq配置#7874端口转发，自定义的上游DNS不能使用，无法连接。
主程序没有运行，openwrt固件编译。

**Comment by vernesong** [comment]
请确认主程序没有运行的错误信息，dns劫持失败不会导致主程序无法运行

**Comment by zgs360** [comment]
@vernesong 重新编译，还是不行！
![1](https://user-images.githubusercontent.com/15887630/76276585-26f4a980-62c1-11ea-95a0-91dc35230172.png)
![2](https://user-images.githubusercontent.com/15887630/76276592-2bb95d80-62c1-11ea-9807-11c4efccbb22.png)

**Comment by zgs360** [comment]
@vernesong 大神，转发端口自动配置了，但没正常查询
![3](https://user-images.githubusercontent.com/15887630/76276658-69b68180-62c1-11ea-902f-c7f8c4ec1dd0.png)
![4](https://user-images.githubusercontent.com/15887630/76276663-6d4a0880-62c1-11ea-90a1-f559e37f5f4c.png)
![5](https://user-images.githubusercontent.com/15887630/76276710-9074b800-62c1-11ea-94d1-3825c8f1dda1.png)

**Comment by xufzh** [comment]
你上面日志不是说配置文件有问题吗？

**Comment by vernesong** [comment]
> @vernesong 大神，转发端口自动配置了，但没正常查询
> ![3](https://user-images.githubusercontent.com/15887630/76276658-69b68180-62c1-11ea-902f-c7f8c4ec1dd0.png)
> ![4](https://user-images.githubusercontent.com/15887630/76276663-6d4a0880-62c1-11ea-90a1-f559e37f5f4c.png)
> ![5](https://user-images.githubusercontent.com/15887630/76276710-9074b800-62c1-11ea-94d1-3825c8f1dda1.png)

关闭全局设置-规则设置-第三方规则

**Comment by xsnaruto** [comment]
我这边是配置和 AdGuard Home 一起用的，在把 OpenClash 的 DNS 端口填入 AdGuard Home 的上游后测试时失败，提示 DNS 不可用。
尝试换了一下其他的端口给 OpenClash 做 DNS，似乎也都不行。
现在暂时只能先用 AdGuard Home 做 OpenClash 的上游。
具体的不太懂，所以留个言观望一下这个 issue 好了。

**Comment by wtser** [comment]
@xufzh 你直接保存就完了，别去测试
