### ISSUE TITLE
请问能否根据设备ip设置规则？

### ISSUE THREAD

**Issue by pv0402** [vernesong/OpenClash#2063]
比如默认走规则，漏网之鱼直连，指定某一设备走规则，漏网之鱼走代理？或者默认设备走规则，指定设备走大陆白名单模式？谢谢！

**Comment by vernesong** [comment]
自定义规则不会写？

**Comment by pv0402** [comment]
> ```
> 
> script:
> 
>   shortcuts:
> 
>     direct: src_ip == '192.168.1.2' and (geoip(resolve_ip(host)) == 'CN' or geoip(dst_ip) == 'CN')
> 
>     proxy: src_ip == '192.168.1.2' and (geoip(resolve_ip(host)) != 'CN' or geoip(dst_ip) != 'CN')
> 
> rules:
> 
> - SCRIPT,direct,DIRECT
> 
> - SCRIPT,proxy,#proxy group name

感谢大神指导！
