### ISSUE TITLE
DNS服务器解锁的Netflix无法观看，必须原生IP

### ISSUE THREAD

**Issue by Faramitas** [vernesong/OpenClash#207]
我看到了作者你说的使用fakeip 游戏模式，但是我的机场是SSR机场，不支持clash，所以我只能使用CLASHR内核，希望作者能解决这个问题。。。。。应该不止我一个有这样的困扰。

**Comment by vernesong** [comment]
部分设备（电视盒子等）因为内置的tcp查询方式目前可以用游戏模式解决，其他设备DNS服务器解锁使用fake-ip（增强）模式是没有问题的

**Comment by z877303287** [comment]
> 部分设备（电视盒子等）因为内置的tcp查询方式目前可以用游戏模式解决，其他设备DNS服务器解锁使用fake-ip（增强）模式是没有问题的

但是游戏模式的内核只有clash，并没有clashR的，这咋办。。。

**Comment by z877303287** [comment]
> 部分设备（电视盒子等）因为内置的tcp查询方式目前可以用游戏模式解决，其他设备DNS服务器解锁使用fake-ip（增强）模式是没有问题的

最新版本测试，DNS服务器解锁的Netflix服务，连电脑端都不能正常转发了，我换成SSR plus+正常，之前版本至少电脑端是可以正常观看Netflix的。

**Comment by laoz77** [comment]
> 我看到了作者你说的使用fakeip 游戏模式，但是我的机场是SSR机场，不支持clash，所以我只能使用CLASHR内核，希望作者能解决这个问题。。。。。应该不止我一个有这样的困扰。

可以替换内核解决这个问题。

**Comment by z877303287** [comment]
> > 我看到了作者你说的使用fakeip 游戏模式，但是我的机场是SSR机场，不支持clash，所以我只能使用CLASHR内核，希望作者能解决这个问题。。。。。应该不止我一个有这样的困扰。
> 
> 
> 
> 可以替换内核解决这个问题。
更换哪个内核？  tun？

**Comment by laoz77** [comment]
> 
> 
> > > 我看到了作者你说的使用fakeip 游戏模式，但是我的机场是SSR机场，不支持clash，所以我只能使用CLASHR内核，希望作者能解决这个问题。。。。。应该不止我一个有这样的困扰。
> > 
> > 
> > 可以替换内核解决这个问题。
> > 更换哪个内核？  tun？

ClashR内核，你搜一下frainzy1477在github的项目吧
