### ISSUE TITLE
ssh 异常（git没法推送代码，也没法拉取代码）

### ISSUE THREAD

**Issue by hzmming** [vernesong/OpenClash#2074]
开了openClash代理后，会出现

```shell
kex_exchange_identification: Connection closed by remote host
Connection closed by 20.205.243.166 port 22
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

请问这是 openClash 的问题，还是我机场节点的问题呢？

**Comment by a76yyyy** [comment]
github个人中心里设置好ssh

**Comment by hzmming** [comment]
> github个人中心里设置好ssh

并不是这问题。
细说下我的网络情况：
两台路由器，一台直接联网，一台前置接入软路由r2s（openClash装在r2s上）
1. 使用直接联网的路由器wifi，能正常ssh使用git推拉代码
2. 使用接入了软路由r2s的路由器wifi，不启动openClash，也能正常ssh使用git推拉代码
3. 第2种情况，启动openClash后，就不行了，会遇到我说的ssh异常问题。

所以很明显问题就出在“openClash”这里（我是这样认为的）

还是说，要怎么配置下openClash才行吗？看面板上有挺多配置的

**Comment by hzmming** [comment]
https://github.com/vernesong/OpenClash/issues/1960#issuecomment-1019101426

提到了相同的问题

**Comment by AnzhiZhang** [comment]
将 Git Clone 改为使用 443 端口

https://github.com/vernesong/OpenClash/issues/1960#issuecomment-1115732292

**Comment by liangminghan0228** [comment]
Windows 用户编辑 ~/.ssh/config 文件，给文件加上以下内容，重启git bash.

Host github.com
    User git
    ProxyCommand connect -H 127.0.0.1:7890 %h %p

https://www.v2ex.com/t/841032

**Comment by HaiYangCode** [comment]
我使用了Clash代理导致包这个错，关闭clash就能正常提交了。

**Comment by QGB** [comment]
Connection closed by 20.205.243.160 port 22

**Comment by gyx1210** [comment]
官方文档里有解决办法
https://docs.github.com/zh/authentication/troubleshooting-ssh/using-ssh-over-the-https-port

**Comment by n-WN** [comment]
在 clash 配置文件里配置过滤22端口

**Comment by Aikoin** [comment]
> 官方文档里有解决办法
> https://docs.github.com/zh/authentication/troubleshooting-ssh/using-ssh-over-the-https-port

5555谢谢，真的这几天搜了好多方法没解决orz，现在成功了

**Comment by whu-lyh** [comment]
Many thanks!!!

> 官方文档里有解决办法 https://docs.github.com/zh/authentication/troubleshooting-ssh/using-ssh-over-the-https-port

**Comment by watchpoints** [comment]
Host github.com
    Hostname ssh.github.com
    Port 443
    User git

**Comment by h1ello** [comment]
> 我使用了Clash代理导致包这个错，关闭clash就能正常提交了。

同样的问题，已解决，谢谢
