### ISSUE TITLE
编入固件后即使不进行任何设置连接旁路由的设备也无法正常上网

### ISSUE THREAD

**Issue by Zaphkito** [vernesong/OpenClash#2078]
经过测试，在旁路由的情况下，如果我将openclash编入到固件内，在设置好lan口且关闭ipv6一些服务的情况下会出现设备在互联网内不能正常“下载”的情况，但是可以正常上传的奇怪bug，此时没有对openclash进行任何设置改动，路由器本身可以正常上网，此时如果将openclash设置好并打开，网络就会完全恢复正常，另外如果不编译openclash就不会出现这个问题

**Comment by vernesong** [comment]
未启动不会修改任何东西，请排查网络问题的具体原因
