### ISSUE TITLE
给steam加代理，每次登录都需要输入令牌。不加代理steam被屏蔽的啥也打不开。

### ISSUE THREAD

**Issue by DawnAleax** [vernesong/OpenClash#2079]
如题有啥好的办法？天天都得输验证码太烦了

**Comment by DawnAleax** [comment]
登录时间 | 注销时间 | OS 类型 | 国家/地区 | 城市 | 州或省
-- | -- | -- | -- | -- | --
2022 年 2 月 21 日 上午 11:39 CST |   | -400 | CN | ******** | Henan
2022 年 2 月 21 日 上午 11:39 CST |   | 16 | HK | Hong Kong | Hong Kong

**Comment by DawnAleax** [comment]
登录记录会同时出现两条

**Comment by vernesong** [comment]
手动选择，固定节点
