### ISSUE TITLE
请教一下，我的机场是SSR的，openclash支持订阅吗，如果说用在线转换方式来订阅，这种路线可以吗

### ISSUE THREAD

**Issue by dddd64693** [vernesong/OpenClash#2083]
![image](https://user-images.githubusercontent.com/14047878/155061141-cefc800a-18cf-4b3d-adb1-df3899697b1b.png)
当前是使用的SSR地址转换成clash的方式，结果如上

**Comment by wangjianpro999** [comment]
转换了当然支持

**Comment by AXBNG** [comment]
订阅转换就行了，你这版本太老了，更新下看看

**Comment by dddd64693** [comment]
> 订阅转换就行了，你这版本太老了，更新下看看

主要我的机器太老了，新的不一定支持，玩客云的刷snail

**Comment by abigchopstick** [comment]
看加密方式，好像有一种加密方式SSR是不支持的
