### ISSUE TITLE
切换节点必须用一个控制面板吗？

### ISSUE THREAD

**Issue by pscj** [vernesong/OpenClash#2085]
openclash的功能里面本身是不提供的吗？，找了一圈设置项也没找到

**Comment by AXBNG** [comment]
你这是啥问题，不然用意念控制么，控制面板又不用你手动输入网址

**Comment by pscj** [comment]
之前用ssr那些，都可以在openwrt设置页面里直接切换，不用再呼叫另一个面板，再用clash api切换

**Comment by AXBNG** [comment]
> 之前用ssr那些，都可以在openwrt设置页面里直接切换，不用再呼叫另一个面板，再用clash api切换

先入为主罢了，clash的高级策略分流用面板再直观不过了

**Comment by pscj** [comment]
> > 之前用ssr那些，都可以在openwrt设置页面里直接切换，不用再呼叫另一个面板，再用clash api切换
> 
> 先入为主罢了，clash的高级策略分流用面板再直观不过了

我去学习一下
