### ISSUE TITLE
请教 openwrt 下， openclash 和 adguard home 哪个应该做上游 DNS？

### ISSUE THREAD

**Issue by magic3584** [vernesong/OpenClash#2091]
试了好几次都没有配置成功。
跟 openclash 是Redir 还是 Fake-IP 有关系吗？
openclash 和 adguard home  哪个应该做上游 DNS？又该如何配置？

感谢

**Comment by mengxinz** [comment]
Redir模式 ADGUARDHOME做上游

**Comment by malikshi** [comment]
Operation mode `redir-host`
DNS setting unchecked redirect local DNS setting
Set DNS upstream on Ahh
![IMG_20220308_111823](https://user-images.githubusercontent.com/9080737/157165482-20f3de5e-3e0f-4256-9193-5a33741f5656.jpg)

![IMG_20220308_111637](https://user-images.githubusercontent.com/9080737/157165467-6efc43ee-3973-4edb-95c1-dea443fb3b7d.jpg)

**Comment by magic3584** [comment]
@malikshi 
Hi, what's the difference between Redir and Fake-IP?
After setting, it only shows localhost(127.0.0.1) in ADG. Is there any way to show the real IP address?

**Comment by malikshi** [comment]
> @malikshi Hi, what's the difference between Redir and Fake-IP? After setting, it only shows localhost(127.0.0.1) in ADG. Is there any way to show the real IP address?

Use redir-host if you want real IP address/ domain shown in yacd. Don't you know fake-ip meaning faking the real IP with fake ip? So it's won't work along with agh I assume

**Comment by magic3584** [comment]
> > @malikshi Hi, what's the difference between Redir and Fake-IP? After setting, it only shows localhost(127.0.0.1) in ADG. Is there any way to show the real IP address?
> 
> Use redir-host if you want real IP address/ domain shown in yacd. Don't you know fake-ip meaning faking the real IP with fake ip? So it's won't work along with agh I assume

It always show localhost(127.0.0.1) in ADG while using redir-host
