### ISSUE TITLE
Dev内核刚刚又回滚了？

### ISSUE THREAD

**Issue by wangjianpro999** [vernesong/OpenClash#2093]
Dev内核刚刚还是1.9.0-10，一刷新又回滚到-7了？一更新又回到-7，也刷不到-10了，怎么回事？

Dev] 当前内核版本 | v1.9.0-7-gb1a639f | [Dev] 最新内核版本 | v1.9.0-7-gb1a639f

![Screenshot_2022-02-24-10-16-38-487_com microsoft emmx](https://user-images.githubusercontent.com/79621192/155444687-6f1eb8a5-2c1c-4fba-8b3a-47206a326ee4.jpg)
当前客户端版本也是经常错乱

**Comment by lrgcx** [comment]
我的选择dev更新分支一键更新后整个openclash都消失了，不知是啥情况？

**Comment by wangjianpro999** [comment]
那倒没有

lrgcx ***@***.***> 于 2022年2月24日周四 10:32写道：
