### ISSUE TITLE
使用OpenClash遇到的一些问题，不清楚怎么解决

### ISSUE THREAD

**Issue by shange1993** [vernesong/OpenClash#2096]
就是外网访问内网无法访问，比如远程连接，访问群晖，访问http等等，只要指向了开启openclash的旁路由的网关就无法访问，不清楚怎么解决，以前用的passwall和ShadowSocksR Plus++都不会有类似问题，研究好久都不清楚怎么解决，无论是Redir-Host模式还是fake-ip模式都会这样

**Comment by vernesong** [comment]
绕过国内？

**Comment by shange1993** [comment]
@vernesong Redir-Host模式勾选了绕过国内还是一样无法在外网访问内网，0.44.25版本，以前貌似能访问的

**Comment by shange1993** [comment]
@vernesong  问题解决。勾选了[旁路网关（旁路由）兼容]导致的外网无法访问内网，把这个关闭就好了，无奈，手贱勾选造成的问题

**Comment by Alinlin918** [comment]
> @vernesong 问题解决。勾选了[旁路网关（旁路由）兼容]导致的外网无法访问内网，把这个关闭就好了，无奈，手贱勾选造成的问题

您好，我遇到了和您一样的问题，不过我不论是不是勾选旁路由，一样都是无法外网访问群晖，我用的是fake-ip模式，您知道要怎么解决吗

**Comment by JiuYueCHN** [comment]
> [@vernesong](https://github.com/vernesong) 问题解决。勾选了[旁路网关（旁路由）兼容]导致的外网无法访问内网，把这个关闭就好了，无奈，手贱勾选造成的问题

谢谢你！终于好了！！！
