### ISSUE TITLE
问下这几个连接在哪、

### ISSUE THREAD

**Issue by MXJNZ6** [vernesong/OpenClash#2099]
![image](https://user-images.githubusercontent.com/53927877/155842621-9cf099be-7010-4cfb-951b-d7b4befbef0c.png)
这4个连接在哪个途径我想给它改了，这样看着好难受.

**Comment by Wenjn** [comment]
![屏幕截图 2022-02-28 094011](https://user-images.githubusercontent.com/30819559/155910732-34d04947-ba50-4b6f-a04b-5e1268a3f1c6.png)
难兄难弟，我dev和master都有显示不出IP的，dev的还好点。

**Comment by MXJNZ6** [comment]
> 用dev的

![image](https://user-images.githubusercontent.com/53927877/155929716-c608cf45-61c5-4eb9-b2e2-adeec0f0cd1f.png)
第三个还是显示的国内的ip，没有那个一直查询中的了。但是master分支在线订阅转换选择api默认的，模版也是默认的能订阅和启动，其它的全是提示配置文件错误还是啥，或者了订阅成功后启动到下载外部文件失败，然后只有守护程序运行中其它的全未运行。dev版本的是所有在线订阅转换都无法启动，要么订阅失败，要么只有守护程序启动。

**Comment by MXJNZ6** [comment]
> > 用dev的
> 
> ![image](https://user-images.githubusercontent.com/53927877/155929716-c608cf45-61c5-4eb9-b2e2-adeec0f0cd1f.png) 第三个还是显示的国内的ip，没有那个一直查询中的了。但是master分支在线订阅转换选择api默认的，模版也是默认的能订阅和启动，其它的全是提示配置文件错误还是啥，或者了订阅成功后启动到下载外部文件失败，然后只有守护程序运行中其它的全未运行。dev版本的是所有在线订阅转换都无法启动，要么订阅失败，要么只有守护程序启动。
错误：【订阅】下载失败，请检查网络或稍后再试...
配置文件格式校验失败...
错误：配置文件解析失败，【(/tmp/config.yaml): invalid leading UTF-8 octet at line 1 column 1】
配置文件格式校验失败，尝试不使用代理下载配置文件...
错误：配置文件解析失败，【(/tmp/config.yaml): invalid leading UTF-8 octet at line 1 column 1】
 开始更新配置文件【订阅】...

**Comment by vernesong** [comment]
![image](https://user-images.githubusercontent.com/42875168/156010416-4d68a147-cad8-45a5-8a60-2dd1baa5d03d.png)

**Comment by MXJNZ6** [comment]
> ![image](https://user-images.githubusercontent.com/42875168/156010416-4d68a147-cad8-45a5-8a60-2dd1baa5d03d.png)

日志里这个报错啊， 错误：配置文件解析失败，【(/tmp/config.yaml): invalid leading UTF-8 octet at line 1 column 1】好像不是代理的事。

**Comment by MXJNZ6** [comment]
> ![image](https://user-images.githubusercontent.com/42875168/156010416-4d68a147-cad8-45a5-8a60-2dd1baa5d03d.png)

应该是我的订阅链接的原因，我的订阅链接是一个链接基本所有客户端都能用，我打开看看里边的很长的一溜英文字母，应该是一种加密方式，不是其它机场一个客户端一个链接，浏览器打开链接是一个文件，内容直接是节点信息。
