### ISSUE TITLE
请检查网络或稍后再试……

### ISSUE THREAD

**Issue by MrCatQy** [vernesong/OpenClash#2101]
版本更新老是查询失败 然后订阅地址配置了也是获取失败 怎么整😭弄了半天一点也没明白 求大佬打救😭
![9837F074-2E1C-4655-AD3A-DC299D0489CB](https://user-images.githubusercontent.com/9411162/155896896-9ed74749-e236-4b34-bc83-395ded38bb3e.png)
![91C80F2D-7C63-40AE-AFCA-B37999E61927](https://user-images.githubusercontent.com/9411162/155896902-c2e26b4c-bef1-43d2-b505-6665a8850495.png)

**Comment by vernesong** [comment]
全局设置里面启用代理

**Comment by MrCatQy** [comment]
> 全局设置里面启用代理

具体是哪里 能否截图哈
