### ISSUE TITLE
Upgrading luci-app-openclash on root from 0.44.25-beta to 0.44.28-beta 报错

### ISSUE THREAD

**Issue by yanyingjie007** [vernesong/OpenClash#2102]
openclash 0.44.25检查更新检测不到，所以下载新版手动安装，但是报错如下：

Collected errors:
 * pkg_run_script: package "luci-app-openclash" prerm script returned status 1.
 * prerm_upgrade_old_pkg: prerm script for package "luci-app-openclash" failed
 * opkg_install_cmd: Cannot install package luci-app-openclash.

请问如何解决？ etc里面的openclash目录权限是0777

补充：并且无法卸载0.44.25版本

**Comment by skr3328** [comment]
遇到一模一样的问题。也是0.44.25升级0.44.28，目录权限正确，之前的版本都是这么升级过来的没问题

**Comment by vernesong** [comment]
先卸载再升级

**Comment by skr3328** [comment]
卸载也报一样的错误呢
Collected errors:
 * pkg_run_script: package "luci-app-openclash" prerm script returned status 1.
 * opkg_remove_pkg: not removing package "luci-app-openclash", prerm script failed

**Comment by yanyingjie007** [comment]
> 

所以你有解决办法吗？

**Comment by vernesong** [comment]
opkg remove --force-remove "*openclash*"

**Comment by skr3328** [comment]
强制删除clash报错：
root@Openwrt:~# opkg remove --force-remove "luci-app-openclash"
Removing package luci-app-openclash from root...
Collected errors:
 * pkg_run_script: package "luci-app-openclash" prerm script returned status 1.


之后一看clash页面还在，但是/etc/openclash文件夹无了
接着
mkdir /etc/openclash
chmod 0777  /etc/openclash
再安装ipk，更新成功

**Comment by yanyingjie007** [comment]
> 

你什么平台？X86连卸载都无法卸载，no package removed

**Comment by skr3328** [comment]
> 你什么平台？X86连卸载都无法卸载，no package removed

X86平台，要输入：
opkg remove --force-remove "luci-app-openclash"

**Comment by yanyingjie007** [comment]
> > 你什么平台？X86连卸载都无法卸载，no package removed
> 
> X86平台，要输入： opkg remove --force-remove "luci-app-openclash"

一样的，no package removed, 准备恢复快照了
