### ISSUE TITLE
fakeip 增强模式逻辑上来说不应该dev内核就可以了吗？

### ISSUE THREAD

**Issue by Pacio** [vernesong/OpenClash#2103]
开启以后还是自动下载了tun内核？

**Comment by InsOnYou** [comment]
我也有这个疑问，路由器上流量走redir和tun有什么区别呢

**Comment by Pacio** [comment]
> 我也有这个疑问，路由器上流量走redir和tun有什么区别呢

fakeip难道不是只有需要udp代理的时候才需要tun内核吗？难道我理解的不对?

**Comment by vernesong** [comment]
日志不是写的很清楚吗，配置文件写了TUN内核才支持的功能
