### ISSUE TITLE
打开代理youtube无法连接，过几分钟才能连接

### ISSUE THREAD

**Issue by linger040831** [vernesong/OpenClash#2104]
在打开代理后的几分钟内，油管无法打开，其他网页都正常访问谷歌也能正常访问，fakeip和redir模式下都会有这个问题，fakeip缓存和dns缓存都清理过，问题还是存在，模式走的全局代理，所以不是分流问题，在fakeip模式下用nslookup  ping  www.youtube.com能解析到198.xxx.xx.xx的域名，用插件内的测试无法ping通，但是其他网页都可以ping通，过大概5分钟油管就能正常访问，想知道这到底是什么问题，我dns的问题吗？

设备:r4s
系统:[https://github.com/DHDAXCW/NanoPi-R4S/releases/download/2022.02.27-Lean2/openwrt-rockchip-armv8-friendlyarm_nanopi-r4s-squashfs-sysupgrade.img.gz](url)骷髅头的最新稳定版
插件:除了openclash都关了
开了本地劫持，没有开上游dns，网关的dns是运营商默认
fakeip持久化打开，dns缓存关闭
模式:fakeip增强模式

**Comment by WYC-2020** [comment]
感觉自从那个内核改了解析不发送到远程后，越来越不好用了，我这边和你一样ytb打开慢的像乌龟，很多时候直接打不开，google反而没任何问题

**Comment by vernesong** [comment]
控制面板里面看看能不能正常显示域名

**Comment by linger040831** [comment]
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/84896599/156015808-23a6875b-ffe8-426b-a7f5-ab71493a48dc.png">
没有油管的域名

**Comment by 5ycloud** [comment]
这个问题一般都存在，就是dns缓存导致的延迟， 需要将本地DNS和路由DNS缓存都刷新一下就好了

**Comment by skyper72** [comment]
远程域名解析打开,,,,

**Comment by XinSSS** [comment]
> 感觉自从那个内核改了解析不发送到远程后，越来越不好用了，我这边和你一样ytb打开慢的像乌龟，很多时候直接打不开，google反而没任何问题

咋会这样呢， 挺奇怪的， 我这边ytb速度都ok的。。

目前在用fakeip, 兼容性差点， 比如说shark007的解码器包ADVANCED_64bitCodecs无法通过AutoUpdate更新，换成redir就行，别的目前感知区别倒不大，fakeip快点，redir慢点

@linger040831 fakeip是这样的， 除非配置了fake-ip-filter，把域名加了进去， 不然ping 返回的ip都是198.18xxxxx

**Comment by WYC-2020** [comment]
@XinSSS 以前用起来非常好用，最近升级到最新就这样了，不管保留配置还是不保留配置，我一直用的就是兼容模式，现在先暂时切换到小肉鸡了，等这边稳定些再切回来

**Comment by WYC-2020** [comment]
也有可能给我编译了ipv6有关系，先暂时这样吧
@XinSSS
