### ISSUE TITLE
版本更新 查询失败

### ISSUE THREAD

**Issue by yanyingjie007** [vernesong/OpenClash#2105]
如图，
这个是怎么回事？最近2个版本都无法检测更新

![image](https://user-images.githubusercontent.com/3379511/155991477-5b85667e-72f4-47cf-8b3b-497059f52ed4.png)

**Comment by vernesong** [comment]
![image](https://user-images.githubusercontent.com/42875168/156010157-531c592c-e070-4238-a280-7396f6f4d45c.png)
