### ISSUE TITLE
版本：OpenClash-0.44.28-beta，内核无法正常识别和启动

### ISSUE THREAD

**Issue by zorroforever** [vernesong/OpenClash#2106]
如题 大佬求助首先我更新主程序前fakeip（tun混合模式）是正常的，更新后启动不正常，
内核更新页面显示未知，我点了页面上的删除内核，删除/etc/openclash/core/下所有内核文件。
重新手动下载（自动更新会提示更新失败，/tmp/下clash_tun下载4kb就断了，只能手动下载。。。）tun核心改名clash_tun，
放到/etc/openclash/core/下，chmod设置权限如下
-rwsr-xrwx    1 root     root       3868680 Feb 28 22:22 clash_tun*
从调试日志中可以发现
----------------------------

> Tun内核版本: 
> Tun内核文件: 存在
> Tun内核运行权限: 正常

-----------------------------

tun内核版本不显示有问题。

启动tun混合模式日志如下就报错，大佬求助。
-------------------------------------------------------------------------------

> 2022-02-28 22:24:12 Tip: Detected The Exclusive Function of The TUN Core, Use TUN Core to Start...
> 2022-02-28 22:24:12 Step 5: Check The Core Status...
> nohup: failed to run command '/etc/openclash/clash': Exec format error
> 2022-02-28 22:24:15 Step 6: Wait For The File Downloading...
> 2022-02-28 22:24:15 Error: OpenClash Can Not Start, Try Use Raw Config Restart Again...
> 2022-02-28 22:24:15 Tip: Detected The Exclusive Function of The TUN Core, Use TUN Core to Start...
> nohup: failed to run command '/etc/openclash/clash': Exec format error

-----------------------------------------------------------------------------------

具体调试日志如下
[OpenClash 调试日志.txt](https://github.com/vernesong/OpenClash/files/8154089/OpenClash.txt)

**Comment by vernesong** [comment]
检查架构是不是选错了

**Comment by vernesong** [comment]
![image](https://user-images.githubusercontent.com/42875168/156010113-149bc5a9-9e37-4e3a-ac8a-320f2810a425.png)

**Comment by zorroforever** [comment]
> 不要更新，最近有点翻车倾向

是的呢，以前点更新就好了，这次第一次翻车。。回不去了。

**Comment by zorroforever** [comment]
> 检查架构是不是选错了

架构是不是要选amdx64?我的是软路由，3865u。

**Comment by zorroforever** [comment]
> ![image](https://user-images.githubusercontent.com/42875168/156010113-149bc5a9-9e37-4e3a-ac8a-320f2810a425.png)

好哒我换个git代理看看

**Comment by zorroforever** [comment]
谢谢大大 解决啦，问题是刚更新时候架构不是自动选择，我自己选了第一个，选错了，
第二就是换上大大的github地址修改，下载了正确的内核就修复啦。
