### ISSUE TITLE
[Bug] Keep reverting to old config after update

### ISSUE THREAD

**Issue by djoeni** [vernesong/OpenClash#2107]
It happen again when update to v0.44.29-beta (before is when update to v0.44.28-beta).

After update it uses or reverting to "old" config not the latest config running before update... all proxy provider created gone and the one which already deleted back again.

Thanks

**Comment by vernesong** [comment]
delete the ```/tmp/openclash``` before update

**Comment by djoeni** [comment]
ic2...thanks
