### ISSUE TITLE
0.44.29问题多吗？能升级吗？

### ISSUE THREAD

**Issue by nielu527** [vernesong/OpenClash#2108]
之前我升级了0.44.25，随时崩溃，内存占用800M左右，后来降级使用了。现在降级用的0.44.06。今天看有0.44.29了，不知道新版本问题还多吗？我不敢升级了，有高手说说吗？？

**Comment by zephyrhex** [comment]
我也是类似状况，0.44.25后各种崩溃不稳定，升到0.44.29两小时内必断网，降级回0.43.05，观望ing

**Comment by zhaoxp520** [comment]
感觉DNS经常炸，网页解析好慢，这几个版本一直这样。

**Comment by ghaner** [comment]
今天上午日志连续弹内核崩溃记录,重启后路由器lweb页面加载很慢,采用清除数据的重启方式才好,目前还在观察中.

**Comment by WYC-2020** [comment]
> 感觉DNS经常炸，网页解析好慢，这几个版本一直这样。

你还慢，我的直接game over 直接打不开。间歇性抽风哈哈

**Comment by Suwmlee** [comment]
升级后，直接无法识别版本和内核了 😃

**Comment by WYC-2020** [comment]
来统计一下 哪个版本好用，给大伙提供一个回退的版本

**Comment by Pacio** [comment]
感觉最近几个版本都有点问题，尤其是fakeip完全感觉不出来速度的优势了，我都改用redir-host了

**Comment by 5ycloud** [comment]
> 来统计一下 哪个版本好用，给大伙提供一个回退的版本

回退到0.44.06，使用还可以！

**Comment by jayolim** [comment]
我是CPU占用很高，DNS经常炸会卡死openwrt后台然后developer升级了0.44.30

**Comment by 5ycloud** [comment]
@

> 我是CPU占用很高，DNS经常炸会卡死openwrt后台然后developer升级了0.44.30

44.30已经出来了？

**Comment by anjue39** [comment]
千万别更新，升级后，直接无法识别版本和内核了

**Comment by 5ycloud** [comment]
> 千万别更新，升级后，直接无法识别版本和内核了 

这种问题都好解决，主要关注稳定性表现

**Comment by anjue39** [comment]
收到，新版本可以更新了。使用2天，只是发现时间久了会有点卡网



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: GUAIYU ***@***.***&gt;
发送时间: 2022年3月20日 18:51
收件人: vernesong/OpenClash ***@***.***&gt;
抄送: anjue39 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [vernesong/OpenClash] 0.44.29问题多吗？能升级吗？ (Issue #2108)





  
千万别更新，升级后，直接无法识别版本和内核了
  
这种问题都好解决，主要关注稳定性表现
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 5ycloud** [comment]
测试44.34表现不错，比较稳定正常了

**Comment by anjue39** [comment]
是的，我正在用。默认只订阅节点，不做任何规则设置时是稳定的。比如开启第三方规则后，时间久了延迟大一点点。我现在尽量少碰dns这些，只要一判断，就会慢，本来是为了快，结果判断占了延迟。就像360本来是打扫软件占用资源的，结果它是占资源的。轻盈，用原始的服务商dns，简单一个规则就行了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: GUAIYU ***@***.***&gt;
发送时间: 2022年3月26日 20:51
收件人: vernesong/OpenClash ***@***.***&gt;
抄送: anjue39 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [vernesong/OpenClash] 0.44.29问题多吗？能升级吗？ (Issue #2108)





 
测试44.34表现不错，比较稳定正常了
