### ISSUE TITLE
openclash用rule模式，为什么国内网都走国外呢

### ISSUE THREAD

**Issue by tom6781459** [vernesong/OpenClash#2112]
这个是啥原因，怎么解决

**Comment by AXBNG** [comment]
1.检查你的规则里有没有把国内设为直连，没有就用订阅转换
2.把设置里的禁用、仅允许、绕过等等都设置好

**Comment by Sm1rkBoy** [comment]
可能国内的规则写在了一个大范围的后面,匹配到了大范围走了国外就不会向下检测了

**Comment by tom6781459** [comment]
怎么解决呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月3日(星期四) 下午4:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [vernesong/OpenClash] openclash用rule模式，为什么国内网都走国外呢 (Issue #2112)





 
可能国内的规则写在了一个大范围的后面,匹配到了大范围走了国外就不会向下检测了
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Sm1rkBoy** [comment]
留下几个油管链接你看一下,可能会对你的问题有所帮助
https://reurl.cc/9OLA1x  自定义分流策略上集
https://reurl.cc/AKLWdd 自定义分流策略下集
https://reurl.cc/GoLqAD Clash clash配置文件详解
