### ISSUE TITLE
openclash开启前后及不同运行模式 宽带测速速度明显有差异

### ISSUE THREAD

**Issue by ghaner** [vernesong/OpenClash#2117]
测速工具http://test.ustc.edu.cn/
openclash v0.44.29-beta
openclash不运行时测速为330Mbps
openclash运行时Fake-IP增强模式测速为190Mbps
openclash运行时Fake-IP tun模式测速为33Mbps
什么原因?

**Comment by m1987n** [comment]
我这有这个问题，有时候设置好之后速度才20，我的是500的宽带，路由重启下试试。

**Comment by ghaner** [comment]
> 我这有这个问题，有时候设置好之后速度才20，我的是500的宽带，路由重启下试试。

这就是恢复出厂设置后再用清除数据的方式重启路由器的测速结果.速度在开启openclash和更换模式前后有明显差异.

**Comment by wangjianpro999** [comment]
启动前后测速两端位置是不是不同？国内测速与对外测速是不同的

**Comment by openips** [comment]
路由器性能差的影响的吧

**Comment by HoHoibin** [comment]
怎么办，有解决方法吗
