### ISSUE TITLE
已经安装最新的libcap和libcap-bin，但仍提示没有安装

### ISSUE THREAD

**Issue by Tongzhao9417** [vernesong/OpenClash#2118]
已从官方源安装了这两个依赖，但是仍然无法启动，提示没有安装。如何解决？

**Comment by zb737472783** [comment]
我记得官方源得按照/base/路径下的 新路径下的改名字了 安装没用

**Comment by Tongzhao9417** [comment]
> 我记得官方源得按照/base/路径下的 新路径下的改名字了 安装没用

我知道问题的原因了：我是在docker里安装的op和openclash，会有比较多的坑。我已经转到虚拟机安装了，没出过任何问题
