### ISSUE TITLE
关于adg+oc的问题

### ISSUE THREAD

**Issue by DockerYumeko** [vernesong/OpenClash#2119]
有一点问题想请教一下，我的lede用的是清风的homelede，环境为adg+dnsmasq+chinadnsng+smartdns，使用openclash时，为了广告过滤，将adg的上游设置为openclash的7874，openclash是Fake-IP模式，不劫持dns，使用自定义dns服务器，指定上游到smartdns。
在这个设置下，即使我将adg的上游指定到dnsmasq，不指向clash，却仍旧可以正常访问国外网站是为什么

**Comment by AXBNG** [comment]
套娃套得不够多（手动滑稽

**Comment by DockerYumeko** [comment]
> 套娃套得不够多（手动滑稽

阿这

**Comment by itswl** [comment]
真有这么强烈的需求吗😂

**Comment by jayolim** [comment]
我就想问过了adg smartdns oc还能匹配域名分流的规则吗？之前我试过了返回oc的都是ip有可能奈飞无法解锁。不知道是不是节点问题。后来干脆直接在oc设置dns了，省事。
