### ISSUE TITLE
YouTube 监测连接超时问题

### ISSUE THREAD

**Issue by ccinoo** [vernesong/OpenClash#212]
您好：

我是OpenClash新手，按照wiki在我的软路由上安装了OpenClash并进行了全局等设置。且通过OpenClash中订阅功能自动添加了节点。但是一直显示如下“YouTube 监测连接超时”不知道如何解决？谢谢

![image](https://user-images.githubusercontent.com/30647119/76161245-678ede80-616c-11ea-9156-4be09290927d.png)

-----------其他信息-----------------
OpenWRT版本：Openwrt Koolshare mod V2.30
Openclahs版本：luci-app-openclash_0.36.7-beta_all.ipk
服务器节点显示有延时信息，入下图：
![image](https://user-images.githubusercontent.com/30647119/76161269-c05e7700-616c-11ea-8f1d-ccc962ddcaac.png)

**Comment by vernesong** [comment]
路由关闭ipv6和其他dns加速插件，openclash开启dns劫持，电脑的网关和dns设置为路由器地址。
启动后进入控制面板查看日志检查异常，或者按照wiki中网络异常检查的操作排查故障

**Comment by ccinoo** [comment]
非常感谢，关闭IPV6后网站访问检查正常了，我再试试其他功能。

1、路由关闭ipv6和其他dns加速插件
接口 - LAN - DHCP服务器中已经关闭IPV6，如下图：
![image](https://user-images.githubusercontent.com/30647119/76163206-22c07300-617f-11ea-8b3f-6439fb86b04d.png)
