### ISSUE TITLE
DoH长时间使用后疑似死锁

### ISSUE THREAD

**Issue by KernelErr** [vernesong/OpenClash#2120]
你好，我的配置文件中DNS只有一个DoH服务器，每次平均运行OpenClash一天后就会出现100% CPU占用，运行日志提示无法通过DoH解析域名，strace进程发现卡在futex。应该不是DoH被墙的问题？因为重启路由器/OpenClash后就可以恢复正常。想请问一下OpenClash是否存在Bug。

**Comment by vernesong** [comment]
待查

**Comment by KernelErr** [comment]
目前问题一段时间没有再出现，采用了以下步骤：

- 将DoT服务器在规则中设置为DIRECT（似乎不能解决问题）
- 修改DoT服务器子域名长度为超长
- 在发生问题时更换节点
- 重新添加了Nameserver，把DoT作为Fallback（尽管这样还是很大一部分查询会走DoH）

此issue将被关闭，感谢vernesong。
