### ISSUE TITLE
clash出现未知IP连接

### ISSUE THREAD

**Issue by Kev1nZheng** [vernesong/OpenClash#2122]
clash面板出现未知IP的连接，如图所示，内网IP在192.168.2.1/24网段。但clash连接中出现了公网的IP，而且source和target均不是在192.168.2.1/24网段。有时会大量出现此类IP，且并没有设备在访问显示的Host。设置中已经开启了“仅代理命中规则流量”和“仅允许常用端口流量”。
<img width="1895" alt="Screen Shot 2022-03-06 at 22 58 47" src="https://user-images.githubusercontent.com/24239053/156929367-edab2939-2c78-47a5-a609-cfb22e417566.png">

**Comment by vernesong** [comment]
全局-常规-仅允许内网

**Comment by Kev1nZheng** [comment]
> 全局-常规-仅允许内网

已经勾选了全局设置-基本设置-仅允许内网

**Comment by GaimenKwan** [comment]
我也是勾选了仅允许内网，还是会出现很多未知ip，流量一下就跑光了

**Comment by vernesong** [comment]
调试日志
