### ISSUE TITLE
redir-host模式下谷歌搜索提示不是私密连接

### ISSUE THREAD

**Issue by linger040831** [vernesong/OpenClash#2125]
谷歌搜索报错截图

<img width="528" alt="image" src="https://user-images.githubusercontent.com/84896599/157164682-3ba9b7fb-4f3c-430d-b74a-b3bfc4a2e75c.png">
<img width="494" alt="image" src="https://user-images.githubusercontent.com/84896599/157164700-b2383ae3-9cee-42a5-8a5f-be70de5450ef.png">

fakeip模式下正常

换过浏览器也是这样

电脑dns以清除

openclash设置

![image](https://user-images.githubusercontent.com/84896599/157164747-fcee3f6b-0aa2-44e5-b11f-a1b5732770cf.png)
![image](https://user-images.githubusercontent.com/84896599/157164764-274fa573-475b-40a6-a7bc-192ec9ef1256.png)

面板调试日志
<img width="1078" alt="image" src="https://user-images.githubusercontent.com/84896599/157165071-6a4b917f-2a10-42ff-a27e-53e9a25d9cb5.png">

<img width="1101" alt="image" src="https://user-images.githubusercontent.com/84896599/157165141-4cbf23f2-c0ea-4495-a6ee-f9722440378b.png">

**Comment by madman43** [comment]
这个问题远古版本到现在一直存在，fake-ip模式也有这个问题。

**Comment by nekomiya-hinata** [comment]
dns污染

**Comment by madman43** [comment]
> 

已经勾上不需要dns缓存了

**Comment by zgc** [comment]
这个不是openclash的问题吧，我用surge+4g也遇到过，dns换成doh就正常了

**Comment by madman43** [comment]
更换dohdns依旧

**Comment by madman43** [comment]
![image](https://user-images.githubusercontent.com/19260034/157862159-34ef080b-1d36-47b7-b9e6-7829f16e86a0.png)
youtube.com表现为这样，其他tw ins 表现为![image](https://user-images.githubusercontent.com/19260034/157862276-ba8b44bc-9d02-497e-b3f1-f56b6d7868bb.png)

**Comment by zgc** [comment]
> ![image](https://user-images.githubusercontent.com/19260034/157862159-34ef080b-1d36-47b7-b9e6-7829f16e86a0.png) youtube.com表现为这样，其他tw ins 表现为![image](https://user-images.githubusercontent.com/19260034/157862276-ba8b44bc-9d02-497e-b3f1-f56b6d7868bb.png)

我刚刚也遇到了，但是是因为我重启软路由的时候，Chrome的dns被污染了，全退了一下Chrome就好了，不知道你是不是和我一样的问题。我这边只要用udp的dns是必污染的。

**Comment by madman43** [comment]
> > ![image](https://user-images.githubusercontent.com/19260034/157862159-34ef080b-1d36-47b7-b9e6-7829f16e86a0.png) youtube.com表现为这样，其他tw ins 表现为![image](https://user-images.githubusercontent.com/19260034/157862276-ba8b44bc-9d02-497e-b3f1-f56b6d7868bb.png)
> 
> 我刚刚也遇到了，但是是因为我重启软路由的时候，Chrome的dns被污染了，全退了一下Chrome就好了，不知道你是不是和我一样的问题。我这边只要用udp的dns是必污染的。

不知道怎么说了我从用clash一直是这个问题就没正常使用过，换ssr，bypass，passwall都直接没问题，dns试过全doh，全常规dns都这样，不是证书问题就是响应超时

**Comment by kokutoukiritsugu** [comment]
我也遇到了

最后发现把里面一个国内的dns删了,重启服务,手机上浏览器重启, 关闭数据流量, 就好了...
试过不关数据流量, 还是污染的, 有时候不关又没事, 这个可能跟各种手机系统有关系

注意配置里dns的enable要true
fallback里全都是国外dns, 都是是doh的
nameserver都是国内dns, 尽量也是doh的
