### ISSUE TITLE
打开openclash后能上网，但windows电脑有线提示未连接网络

### ISSUE THREAD

**Issue by dinggood615** [vernesong/OpenClash#2126]
关闭openclash后网口又恢复正常了，有没有遇到我这同样情况的 我的版本是最新029版本

**Comment by dinggood615** [comment]
问题自己摸索解决了 在自定义规则里添加一行代码
- DOMAIN-SUFFIX,windows.com,DIRECT

**Comment by mmeiwenlong** [comment]
> 关闭openclash后网又恢复正常了，有口没有我遇到同样情况的我的版本是最新029版本

一样的。重启下openclash就好了。不知道为啥
