### ISSUE TITLE
+.youtube.com与*.youtube.com有什么区别吗

### ISSUE THREAD

**Issue by ForestL18** [vernesong/OpenClash#2127]
如题

**Comment by ForestL18** [comment]
@vernesong

**Comment by wangbo-ops** [comment]
@ForestL18 老哥为啥关闭issue了，我也想知道这个问题的答案。昨天去看源码我的理解是好像没有区别（看不懂go，所以只是一个猜测）
https://github.com/Dreamacro/clash/blob/master/component/trie/domain.go

**Comment by ForestL18** [comment]
额，其实这个是clash作者自定义的用法
[configuration · Dreamacro/clash Wiki](https://github.com/Dreamacro/clash/wiki/configuration#syntax "configuration · Dreamacro/clash Wiki")

**Comment by ForestL18** [comment]
> @ForestL18 老哥为啥关闭issue了，我也想知道这个问题的答案。昨天去看源码我的理解是好像没有区别（看不懂go，所以只是一个猜测） https://github.com/Dreamacro/clash/blob/master/component/trie/domain.go

额，其实这个是clash作者自定义的用法
[configuration · Dreamacro/clash Wiki](https://github.com/Dreamacro/clash/wiki/configuration#syntax "configuration · Dreamacro/clash Wiki")
