### ISSUE TITLE
lhie1规则更新404

### ISSUE THREAD

**Issue by ding0828** [vernesong/OpenClash#213]
lhie1规则更新404

**Comment by evileonline** [comment]
刘大的规则获取不到……希望多做几个备份规则……辛苦

**Comment by tete1030** [comment]
原因是地址从`https://raw.githubusercontent.com/lhie1/Rules/master/Clash/Rule.yml`变成了`https://raw.githubusercontent.com/lhie1/Rules/master/Clash/Rule.yaml`，多了个"a"
