### ISSUE TITLE
内核问题

### ISSUE THREAD

**Issue by zhurant** [vernesong/OpenClash#2132]
我的内核显示不存在，手动上传是未知  更新dev和tun都不行  ![image](https://user-images.githubusercontent.com/93750304/157886724-d096b857-4503-4109-af62-cd91c81073d9.png)

**Comment by vernesong** [comment]
手动上传需要给权限

**Comment by zhurant** [comment]
> 手动上传需要给权限

chmod 777 clash 后没有变化。

**Comment by zhurant** [comment]
![image](https://user-images.githubusercontent.com/93750304/158012570-ffd51fc6-c740-4b8d-8c15-8f4ca02d2093.png)
