### ISSUE TITLE
N1旁路由开启openclash网速指能达到passwall或者ssr+一半

### ISSUE THREAD

**Issue by SamZig** [vernesong/OpenClash#2133]
N1旁路由开启openclash网速指能达到passwall或者ssr+一半，
用passwall可以跑到200m多，
用openclash只能100m左右
请问如何解决？

**Comment by vernesong** [comment]
性能问题，尽量用兼容模式开绕过大陆

**Comment by SamZig** [comment]
> 性能问题，尽量用兼容模式开绕过大陆

兼容模式会泄露dns

**Comment by SamZig** [comment]
貌似 tun-混合模式解决了，我想问下 tun模式跟tun混合模式有什么区别？
