### ISSUE TITLE
更新订阅没有应用外部配置文件

### ISSUE THREAD

**Issue by Lucio-0408** [vernesong/OpenClash#2134]
使用openclash内的在线订阅转换功能更新订阅没有应用外部配置
版本号0.44.29-beta，x86平台，内核版本5.10.100
订阅转换后端使用的是本地搭建
自定义配置链接正常
浏览器直接访问转换后链接正常
后端日志显示config=后面没有具体参数

**Comment by vernesong** [comment]
配置怎么填的

**Comment by Lucio-0408** [comment]
在使用raw.githubusercontent.com的远程配置链接时正常，使用cdn.jsdelivr.net远程配置时会出现上述情况

**Comment by Lucio-0408** [comment]
> 配置怎么填的

初步试验结果只要用jsdelivr的链接就会出问题
