### ISSUE TITLE
openclash 是否有docker版本，使得它可以作为一个独立的组件，运行在所有linux上？

### ISSUE THREAD

**Issue by baozitao** [vernesong/OpenClash#2135]
openclash 是否有docker版本，使得它可以作为一个独立的组件，运行在所有linux上？

**Comment by zhaoxp520** [comment]
linux为什么不直接使用clash程序呢
毕竟linux下可用clash的方式很多呀

**Comment by vernesong** [comment]
不行的，插件是基于openwrt写的，你可以先装openwrt再装插件

**Comment by Neverends4** [comment]
openwrt有docker
曲线救国

**Comment by baozitao** [comment]
> 不行的，插件是基于openwrt写的，你可以先装openwrt再装插件
是因为openwrt里有很多东西，其他linux里没有么？

**Comment by madman43** [comment]
clash有docker版本，教程有很多

**Comment by TomYule** [comment]
小米7000 支持docker
