### ISSUE TITLE
希望大佬更新一下ssr的参数规则

### ISSUE THREAD

**Issue by kl9800** [vernesong/OpenClash#214]
希望大佬更新一下ssr的参数规则，
用了个机场的节点，发现好多加密方式没有，比如chacha20等等（看到个xchacha，但是选了以后无法使用这个节点），
传输协议好像也少了几个，
我不知道是我搞错了还是怎么的，反正v2的参数填进去可以，ssr的不行（因为参数选项没有）

**Comment by wuyu12580** [comment]
ssr你得换支持ssr的内核

**Comment by kl9800** [comment]
比如哪个内核支持？求教，我第一次用这个

**Comment by vernesong** [comment]
ssr你可以去使用下面这个项目的，openclash对ssr支持有限
https://github.com/frainzy1477/luci-app-clash

**Comment by kl9800** [comment]
以后是否打算支持ssr？

**Comment by vernesong** [comment]
> 以后是否打算支持ssr？

目前跟原版内核，你可以前往 https://github.com/Dreamacro/clash/pull/519 了解进度

**Comment by kl9800** [comment]
好的，谢谢！
