### ISSUE TITLE
WARNING: Makefile 'package/luci-app-openclash/luci-app-openclash/Makefile' has a dependency on 'kmod-inet-diag', which does not exist

### ISSUE THREAD

**Issue by fjjonline** [vernesong/OpenClash#2140]
这是什么问题？ WARNING: Makefile 'package/luci-app-openclash/luci-app-openclash/Makefile' has a dependency on 'kmod-inet-diag', which does not exist

**Comment by vernesong** [comment]
支持PROCESS-NAME的依赖，目前大多数源还没有包，可以自行在kernel_menuconfig里启用，这个警告不用理会

**Comment by predators46** [comment]
implemented in the master branch

https://github.com/openwrt/openwrt/pull/9431
