### ISSUE TITLE
实在不会处理了。按照呢些设置也没用

### ISSUE THREAD

**Issue by mmeiwenlong** [vernesong/OpenClash#2142]
重启下openclash或者更新下节点就好了。晕。别看是个地球但上网没问题。
![QQ截图20220313194029](https://user-images.githubusercontent.com/44661424/158057781-18741315-a9cb-4a9d-95a6-79baa4172b5e.png)
以前没这问题最近几个版本总是会这样

**Comment by vernesong** [comment]
![image](https://user-images.githubusercontent.com/42875168/158065309-1e2c69fb-7a3d-4a05-a2e7-1e9bd3a52936.png)
