### ISSUE TITLE
怎么设置某个内网ip漏网之鱼走国内

### ISSUE THREAD

**Issue by shange1993** [vernesong/OpenClash#2145]
怎么设置某个内网ip漏网之鱼走国内，就是单独的规则之外优先国内，Dashboard 控制面板只能设置整体，怎么设置单个的设备规则之外优先国内，其余的设备规则之外优先国外呢

**Comment by Sm1rkBoy** [comment]
没怎么看懂问题,但是应该要在配置文件规则里写IP-CIDR
