### ISSUE TITLE
How much milliseconds the proxy servers considered as inactive/dead?

### ISSUE THREAD

**Issue by malikshi** [vernesong/OpenClash#2149]
Hi, I want to know how much in ms the proxy considered as inactive/dead, I am using cloudflare CDN so sometimes I got 2000-5000ms(tested on v2rayNG) then when i'm checked in yacd the proxy went off.

**Comment by vernesong** [comment]
5s

**Comment by malikshi** [comment]
> 5s

Whenever proxies went off in yacd, I need to test on v2rayNG/other tools then after few secs in yacd the proxies ON again... is it something wrong with the test connection?

**Comment by vernesong** [comment]
Increase the interval if the group type is not a select

**Comment by malikshi** [comment]
Yes I'm using load-balance and fallback. Interval 180 is too low? Every proxy group has 4 proxy/server

**Comment by vernesong** [comment]
Low intervals are not friendly to high latency servers, if you approve of the reliability of the server, increasing the interval will help your problem

**Comment by malikshi** [comment]
Thanks you for the advice, I will test it later

**Comment by malikshi** [comment]
Thanks, I had no problem since increased the interval
