### ISSUE TITLE
正常使用中忽然断网，查看日志显示异常

### ISSUE THREAD

**Issue by andison07** [vernesong/OpenClash#215]
正常使用中忽然整个连接断开，查看日志发现以下异常：

2020-03-09 08:33:15 OpenClash Start Successful
2020/03/09 00:34:16 http: Accept error: accept tcp [::]:9090: accept4: too many open files; retrying in 5ms
2020/03/09 00:34:16 http: Accept error: accept tcp [::]:9090: accept4: too many open files; retrying in 10ms
2020/03/09 00:34:16 http: Accept error: accept tcp [::]:9090: accept4: too many open files; retrying in 20ms
2020/03/09 00:34:16 http: Accept error: accept tcp [::]:9090: accept4: too many open files; retrying in 40ms
2020/03/09 00:34:16 http: Accept error: accept tcp [::]:9090: accept4: too many open files; retrying in 80ms
2020/03/09 00:34:16 http: Accept error: accept tcp [::]:9090: accept4: too many open files; retrying in 160ms
2020/03/09 00:34:17 http: Accept error: accept tcp [::]:9090: accept4: too many open files; retrying in 320ms
2020/03/09 00:34:17 http: Accept error: accept tcp [::]:9090: accept4: too many open files; retrying in 640ms
2020/03/09 00:34:17 http: Accept error: accept tcp [::]:9090: accept4: too many open files; retrying in 1s
2020/03/09 00:34:19 http: Accept error: accept tcp [::]:9090: accept4: too many open files; retrying in 1s
2020/03/09 00:34:20 http: Accept error: accept tcp [::]:9090: accept4: too many open files; retrying in 1s
2020/03/09 00:34:21 http: Accept error: accept tcp [::]:9090: accept4: too many open files; retrying in 1s
2020/03/09 00:34:22 http: Accept error: accept tcp [::]:9090: accept4: too many open files; retrying in 1s
2020/03/09 00:34:23 http: Accept error: accept tcp [::]:9090: accept4: too many open files; retrying in 1s
2020/03/09 00:34:24 http: Accept error: accept tcp [::]:9090: accept4: too many open files; retrying in 1s
2020/03/09 00:34:25 http: Accept error: accept tcp [::]:9090: accept4: too many open files; retrying in 1s
2020/03/09 00:34:26 http: Accept error: accept tcp [::]:9090: accept4: too many open files; retrying in 1s
2020/03/09 00:34:27 http: Accept error: accept tcp [::]:9090: accept4: too many open files; retrying in 1s
2020/03/09 00:34:28 http: Accept error: accept tcp [::]:9090: accept4: too many open files; retrying in 1s
2020/03/09 00:34:29 http: Accept error: accept tcp [::]:9090: accept4: too many open files; retrying in 1s
2020/03/09 00:34:30 http: Accept error: accept tcp [::]:9090: accept4: too many open files; retrying in 1s
2020/03/09 00:34:31 http: Accept error: accept tcp [::]:9090: accept4: too many open files; retrying in 1s
2020/03/09 00:34:32 http: Accept error: accept tcp [::]:9090: accept4: too many open files; retrying in 1s
2020/03/09 00:34:33 http: Accept error: accept tcp [::]:9090: accept4: too many open files; retrying in 1s
2020/03/09 00:34:34 http: Accept error: accept tcp [::]:9090: accept4: too many open files; retrying in 1s
2020/03/09 00:34:35 http: Accept error: accept tcp [::]:9090: accept4: too many open files; retrying in 1s
2020/03/09 00:34:36 http: Accept error: accept tcp [::]:9090: accept4: too many open files; retrying in 1s
2020/03/09 00:34:37 http: Accept error: accept tcp [::]:9090: accept4: too many open files; retrying in 1s
2020/03/09 00:34:38 http: Accept error: accept tcp [::]:9090: accept4: too many open files; retrying in 1s
2020/03/09 00:34:39 http: Accept error: accept tcp [::]:9090: accept4: too many open files; retrying in 1s
2020/03/09 00:34:40 http: Accept error: accept tcp [::]:9090: accept4: too many open files; retrying in 1s
2020/03/09 00:34:41 http: Accept error: accept tcp [::]:9090: accept4: too many open files; retrying in 1s
2020/03/09 00:34:42 http: Accept error: accept tcp [::]:9090: accept4: too many open files; retrying in 1s
2020/03/09 00:34:43 http: Accept error: accept tcp [::]:9090: accept4: too many open files; retrying in 1s
2020/03/09 00:34:44 http: Accept error: accept tcp [::]:9090: accept4: too many open files; retrying in 1s
2020/03/09 00:34:45 http: Accept error: accept tcp [::]:9090: accept4: too many open files; retrying in 1s
2020/03/09 00:34:46 http: Accept error: accept tcp [::]:9090: accept4: too many open files; retrying in 1s

关闭openclash，用手机端小飞机app测试线路均没有问题。

**Comment by vernesong** [comment]
curl备份配置可能出现这种情况，目前内核还不太稳定
