### ISSUE TITLE
请教下，如何才能跟openwrt内置的ddns不冲突

### ISSUE THREAD

**Issue by lurne** [vernesong/OpenClash#2153]
好像近两个月开始，内置ddns解析地址就不是真实的IP，也不是翻墙后的IP地址。请问如何设置才能正确解析到拨号的IP呢，接口已选pppoe-wan

**Comment by zhaoxp520** [comment]
是不是Fake-IP模式
是的话把你用来DDNS的域名，加入到Fake-IP黑名单
在全局设置-DNS设置-高级设置勾选

**Comment by lurne** [comment]
> 是不是Fake-IP模式 是的话把你用来DDNS的域名，加入到Fake-IP黑名单 在全局设置-DNS设置-高级设置勾选

好的，我去试试，请问如果是redir模式也可按此操作么

**Comment by vernesong** [comment]
redir模式不需要，再加个让他直连的规则

**Comment by lurne** [comment]
> redir模式不需要，再加个让他直连的规则

谢谢讲解
