### ISSUE TITLE
这内核咋啦

### ISSUE THREAD

**Issue by mmeiwenlong** [vernesong/OpenClash#2158]
<img width="1750" alt="QQ20220318-211819@2x" src="https://user-images.githubusercontent.com/44661424/159009907-aadb3023-53e1-4a37-acd0-5c55d3bb8943.png">

**Comment by WYC-2020** [comment]
你说咋了。你的用户组什么1000都来了，你怕是手工传的吧，所有的都删除，在更新

**Comment by mmeiwenlong** [comment]
> 你说咋了。你的用户组什么1000都来了，你怕是手工传的吧，所有的都删除，在更新

删了点击更新没反应像没点一样

**Comment by mmeiwenlong** [comment]
<img width="1453" alt="QQ20220320-000341@2x" src="https://user-images.githubusercontent.com/44661424/159128727-82bfb36b-7b3f-4928-b300-96907d86ff96.png">
已修复
