### ISSUE TITLE
如何在编译openwrt固件时把openclash的配置也编译进去

### ISSUE THREAD

**Issue by wangweitung** [vernesong/OpenClash#2159]
如何在编译openwrt固件时把openclash的配置也编译进去

**Comment by shmily103** [comment]
修改luci-app-openclash/root/etc/config/openclash

**Comment by wangweitung** [comment]
> 修改luci-app-openclash/root/etc/config/openclash

是备份的目录全部都放进去吗？

**Comment by lifetyper** [comment]
git clone openclash到package目录下，make menuconfig里在luci-application里选择luci-app-openclash，就可以了。

**Comment by wangweitung** [comment]
> 把配置文件都放到build root的files目录下，和在openwrt里的目录保持一致。 https://openwrt.org/docs/guide-developer/toolchain/use-buildsystem#custom_files

谢谢~~~
