### ISSUE TITLE
关于配置文件订阅的问题

### ISSUE THREAD

**Issue by ikelvingo** [vernesong/OpenClash#216]
目前发现主要有以下几个问题：

- 如果订阅地址为当前使用配置文件，经常出现订阅失败，查看订阅文件为下载配置不完整
- 默认根据当前规则适配订阅地址，如订阅地址在代理范围内，则使用代理进行订阅，如机场发生服务器调整则订阅失败

建议：

- 加入订阅配置完整性校验，如果如关键的proxy信息不完整则放弃本次订阅更新
- 增加订阅地址是否使用代理进行订阅的开关，避免陷入订阅地址的死循环

**Comment by vernesong** [comment]
会首先尝试代理下载并检查关键字段，校验失败后直连下载
