### ISSUE TITLE
Padavan MIPS支持？

### ISSUE THREAD

**Issue by orange2008** [vernesong/OpenClash#2160]
错误代码：
[RT-N14U /opt/home/admin/luci]# opkg install ./luci-app-openclash_0.44.29-beta_all.ipk 
Unknown package 'luci-app-openclash'.
Collected errors:
 * pkg_hash_fetch_best_installation_candidate: Packages for luci-app-openclash found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package luci-app-openclash.

架构：
[RT-N14U /opt/home/admin/luci]# uname -a
Linux RT-N14U 3.4.113 #2 Mon Sep 23 20:46:26 CST 2019 mips GNU/Linux

**Comment by vernesong** [comment]
没有必要环境，支持不了
