### ISSUE TITLE
出现下面的错误，更新后

### ISSUE THREAD

**Issue by anjue39** [vernesong/OpenClash#2161]
No page is registered at '/admin/services/openclash/client'.
If this url belongs to an extension, make sure it is properly installed.
If the extension was recently installed, try removing the /tmp/luci-indexcache file.
---
出现这个错误后从此再也打不开，openclash毁掉了，彻底启动不了了，也从菜单消失了，再也找不到openclash，咋回事呢

**Comment by anjue39** [comment]
出现这个错误后从此再也打不开，openclash毁掉了，彻底启动不了了，咋回事呢

**Comment by vernesong** [comment]
重启

**Comment by pv0402** [comment]
我的也这样 更新必丢失,不知道是不是没有新要求的inet依赖的问题,还好有esxi快照暂时恢复了

> ## No page is registered at '/admin/services/openclash/client'.
> If this url belongs to an extension, make sure it is properly installed.
> If the extension was recently installed, try removing the /tmp/luci-indexcache file.
> 出现这个错误后从此再也打不开，openclash毁掉了，彻底启动不了了，也从菜单消失了，再也找不到openclash，咋回事呢


> ## No page is registered at '/admin/services/openclash/client'.
> If this url belongs to an extension, make sure it is properly installed.
> If the extension was recently installed, try removing the /tmp/luci-indexcache file.
> 出现这个错误后从此再也打不开，openclash毁掉了，彻底启动不了了，也从菜单消失了，再也找不到openclash，咋回事呢

我也是这样。不知道是不是没有新版依赖的问题

**Comment by anjue39** [comment]
> 重启

重启不解决问题！还是丢失了

**Comment by anjue39** [comment]
> 重启不解决问题！还是丢失了

**Comment by anjue39** [comment]
重启不解决问题。还是丢失了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: vernesong ***@***.***&gt;
发送时间: 2022年3月20日 00:07
收件人: vernesong/OpenClash ***@***.***&gt;
抄送: anjue39 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [vernesong/OpenClash] 出现下面的错误，更新后 (Issue #2161)





 
重启
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
