### ISSUE TITLE
在哪里设置让某个网站不是ip不走代理

### ISSUE THREAD

**Issue by tom6781459** [vernesong/OpenClash#2166]
现在我用的lastpass插件，是不是提醒异地登录，包括花生壳也是，怎么让这些网站强制不走代理？
比如花生壳，是国内网站，怎么就走代理了？
花生壳每次一走代理就需要重新实名认证。

**Comment by vernesong** [comment]
国内网站一般规则都不会代理，你先检查配置文件的问题

**Comment by Sm1rkBoy** [comment]
1.在配置文件rules栏自定义编写域名并设置成direct
2.使用第三方规则,国内网站设定成direct
![image](https://user-images.githubusercontent.com/79188982/159157049-d334db7e-9a9c-42f3-904e-c6f8492468bd.png)

**Comment by tom6781459** [comment]
> 1.在配置文件rules栏自定义编写域名并设置成direct 2.使用第三方规则,国内网站设定成direct ![image](https://user-images.githubusercontent.com/79188982/159157049-d334db7e-9a9c-42f3-904e-c6f8492468bd.png)

这里的第三方和自定义规则要打开吗，默认是关闭的。

**Comment by Sm1rkBoy** [comment]
> > 1.在配置文件rules栏自定义编写域名并设置成direct 2.使用第三方规则,国内网站设定成direct ![image](https://user-images.githubusercontent.com/79188982/159157049-d334db7e-9a9c-42f3-904e-c6f8492468bd.png)
> 
> 这里的第三方和自定义规则要打开吗，默认是关闭的。

1.比如我想让github直连不走代理,可以打开自定义规则
![image](https://user-images.githubusercontent.com/79188982/159195593-cb5c9089-6355-4b6a-9310-80d3bb847ae3.png)
然后在下面写
![image](https://user-images.githubusercontent.com/79188982/159195665-924bb434-84cb-4fa4-b30a-5357655df07d.png)
应用设置后会把这个规则写入你的配置文件
这个规则意思是匹配到google关键字就直连不走代理

**Comment by Sm1rkBoy** [comment]
> > 1.在配置文件rules栏自定义编写域名并设置成direct 2.使用第三方规则,国内网站设定成direct ![image](https://user-images.githubusercontent.com/79188982/159157049-d334db7e-9a9c-42f3-904e-c6f8492468bd.png)
> 
> 这里的第三方和自定义规则要打开吗，默认是关闭的。

2.启用第三方规则
![image](https://user-images.githubusercontent.com/79188982/159195891-59bf8ff7-01ea-4e71-81af-2e3db62d0140.png)
往下翻来到这里
![image](https://user-images.githubusercontent.com/79188982/159195920-d64574b6-a7af-4e5a-9c74-b058e4005abe.png)
点击添加然后选择你自己的配置文件
![image](https://user-images.githubusercontent.com/79188982/159196115-c680f707-85fb-41be-b3ed-6ab7ad6c0d8c.png)

**Comment by Sm1rkBoy** [comment]
留下几个油管链接,可能会对你的问题有所帮助
https://reurl.cc/GoLqAD Clash配置文件详解
https://reurl.cc/9OLA1x 自定义分流策略上集
https://reurl.cc/AKLWdd 自定义分流策略下集

**Comment by tom6781459** [comment]
第三方规则这个图片，没有的选项怎么设置哈。只能在上面添加了是吧。

**Comment by Sm1rkBoy** [comment]
> 第三方规则这个图片，没有的选项怎么设置哈。只能在上面添加了是吧。

嗯,没有配置都是没有的,需要自己添加再选择自己的配置文件

**Comment by tom6781459** [comment]
用了这么久都是默认不动，第三方和自定义都是关闭的，原来这么多学问。
谢谢你。

**Comment by Sm1rkBoy** [comment]
> 用了这么久都是默认不动，第三方和自定义都是关闭的，原来这么多学问。 谢谢你。

一般的机场给的订阅链接都会比较简陋,就会出现你访问花生壳走代理的情况,所以需要自定义或者使用第三方规则

**Comment by tom6781459** [comment]
还有个问题有时候困扰我，有时候用代理国内网站打开慢，需要重新刷新一次，我也知道是dns问题，但是哪里设置不会。
默认的。

**Comment by Sm1rkBoy** [comment]
> 还有个问题有时候困扰我，有时候用代理国内网站打开慢，需要重新刷新一次，我也知道是dns问题，但是哪里设置不会。 默认的。

![image](https://user-images.githubusercontent.com/79188982/159198043-a785a5f6-ee49-4dc4-be77-1b9251e53e3e.png)

然后下面的dns组设置
![image](https://user-images.githubusercontent.com/79188982/159198081-773c8ea2-865e-4bea-850a-7508f3ebefa7.png)
nameserver和fallback组的作用不用了解的很透彻,只要知道fallback组填国外dns服务器地址,nameserver组填国内dns服务器地址

**Comment by Sm1rkBoy** [comment]
> 还有个问题有时候困扰我，有时候用代理国内网站打开慢，需要重新刷新一次，我也知道是dns问题，但是哪里设置不会。 默认的。

我倾向于你打开网站走了一圈代理再回来导致的

**Comment by tom6781459** [comment]
### 我吧机场规则改成只有谷歌油管奈飞电报走代理，其他都改成直连是不是就可以了解决了。平时也就用这几个，其他几乎不用。
国内流量和未匹配到规则的流量都改成direct

**Comment by tom6781459** [comment]
10.2.8.10
221.6.4.66
这两个地址是什么

**Comment by Sm1rkBoy** [comment]
> ### 我吧机场规则改成只有谷歌油管奈飞电报走代理，其他都改成直连是不是就可以了解决了。平时也就用这几个，其他几乎不用。
> 国内流量和未匹配到规则的流量都改成direct

这个要改成DIRECT
![image](https://user-images.githubusercontent.com/79188982/159198874-3a81b17b-2a9e-4903-87fc-c4bf1bcb93bc.png)

**Comment by Sm1rkBoy** [comment]
> ### 我吧机场规则改成只有谷歌油管奈飞电报走代理，其他都改成直连是不是就可以了解决了。平时也就用这几个，其他几乎不用。
> 国内流量和未匹配到规则的流量都改成direct

可以的

**Comment by Sm1rkBoy** [comment]
> 10.2.8.10 221.6.4.66 这两个地址是什么

这是我的本地dns服务器地址,拨号的时候给的

**Comment by Sm1rkBoy** [comment]
之后可以打开油管再去查看控制面板就能知道是代理还是直连了
![image](https://user-images.githubusercontent.com/79188982/159199118-44c7a12a-22fa-41d6-bcd4-654e9ba42133.png)

**Comment by tom6781459** [comment]
2001:da8::666这个我填上错误，启动不了

**Comment by Sm1rkBoy** [comment]
> 2001:da8::666这个我填上错误，启动不了

ipv6的dns地址没啥用,不填也没事

**Comment by madman43** [comment]
> 之后可以打开油管再去查看控制面板就能知道是代理还是直连了 ![image](https://user-images.githubusercontent.com/79188982/159199118-44c7a12a-22fa-41d6-bcd4-654e9ba42133.png)

为何你的事域名我的是ip地址呢，怎么设置成ip地址呢

**Comment by Sm1rkBoy** [comment]
> > 之后可以打开油管再去查看控制面板就能知道是代理还是直连了 ![image](https://user-images.githubusercontent.com/79188982/159199118-44c7a12a-22fa-41d6-bcd4-654e9ba42133.png)
> 
> 为何你的事域名我的是ip地址呢，怎么设置成ip地址呢

可能你配合了smartdns或者adguard home插件使用,我之前配合使用就会出现只有ip地址的情况,后面关闭这些插件就没有这种问题了

**Comment by tom6781459** [comment]
> > 还有个问题有时候困扰我，有时候用代理国内网站打开慢，需要重新刷新一次，我也知道是dns问题，但是哪里设置不会。 默认的。
> 
> 我倾向于你打开网站走了一圈代理再回来导致的

今天下午，突然电脑登陆，有关能打开，但是黑色转圈圈，手机tg电报可以登录，这个是哪里出问题了。

**Comment by madman43** [comment]
> > > 之后可以打开油管再去查看控制面板就能知道是代理还是直连了 ![image](https://user-images.githubusercontent.com/79188982/159199118-44c7a12a-22fa-41d6-bcd4-654e9ba42133.png)
> > 
> > 
> > 为何你的事域名我的是ip地址呢，怎么设置成ip地址呢
> 
> 可能你配合了smartdns或者adguard home插件使用,我之前配合使用就会出现只有ip地址的情况,后面关闭这些插件就没有这种问题了

我并没有使用以上两款插件，奇怪，还有其他地方能影响这个吗

**Comment by Sm1rkBoy** [comment]
> > > > 之后可以打开油管再去查看控制面板就能知道是代理还是直连了 ![image](https://user-images.githubusercontent.com/79188982/159199118-44c7a12a-22fa-41d6-bcd4-654e9ba42133.png)
> > > 
> > > 
> > > 为何你的事域名我的是ip地址呢，怎么设置成ip地址呢
> > 
> > 
> > 可能你配合了smartdns或者adguard home插件使用,我之前配合使用就会出现只有ip地址的情况,后面关闭这些插件就没有这种问题了
> 
> 我并没有使用以上两款插件，奇怪，还有其他地方能影响这个吗

#2184

**Comment by madman43** [comment]
> > > > > 之后可以打开油管再去查看控制面板就能知道是代理还是直连了 ![image](https://user-images.githubusercontent.com/79188982/159199118-44c7a12a-22fa-41d6-bcd4-654e9ba42133.png)
> > > > 
> > > > 
> > > > 为何你的事域名我的是ip地址呢，怎么设置成ip地址呢
> > > 
> > > 
> > > 可能你配合了smartdns或者adguard home插件使用,我之前配合使用就会出现只有ip地址的情况,后面关闭这些插件就没有这种问题了
> > 
> > 
> > 我并没有使用以上两款插件，奇怪，还有其他地方能影响这个吗
> 
> #2184 #278

还是IP显示，我重新刷固件只装openclash后启动了还是ip加端口形式，咋回事呀，都是按照这里的教程设置的

**Comment by bluspea** [comment]
也发现了同样的问题， 同 issue #2184  域名提前解析成了IP地址。 
问题发生在 OpenClash 跑在旁路网关的时候，如果 把 Win10客户端的 网关+DNS 设置为旁路网关地址，则会提前解析成IP地址；
如果Win10客户端 把OpenClash 作为 http 代理的时候，则正常，不会提前解析成IP.

客户端版本	v0.45.02-beta
处理器架构	aarch64_cortex-a53
运行模式	Redir-Host 兼容
[Dev] 当前内核版本	v1.10.0-3-gdd9bdf4

**Comment by senup** [comment]
感谢大佬们，也解答了我的疑惑

**Comment by Myttl** [comment]
例如这样：
- DOMAIN-SUFFIX,bilibili.com,DIRECT
- DOMAIN-SUFFIX,bilibili.cn,DIRECT
- DOMAIN-SUFFIX,bilivideo.com,DIRECT
- DOMAIN-SUFFIX,bilivideo.cn,DIRECT
- DOMAIN-SUFFIX,biliapi.com,DIRECT
- DOMAIN-SUFFIX,biliapi.net,DIRECT
- DOMAIN-SUFFIX,apple.com,DIRECT

**Comment by Myttl** [comment]
前面带“-（空格）”
