### ISSUE TITLE
无法油管和浏览器打开google问题

### ISSUE THREAD

**Issue by noway2014** [vernesong/OpenClash#217]
运行在路由器上clash,订阅正常，运行正常。但是手机连接路由器后，只能打开电报，无法浏览google网页和油管程序。请问什么原因。都是使用默认设置

**Comment by L0snight** [comment]
请提供详细信息。比如用的什么模式，用的内核版本，并提供脱敏后的配置文件，以及运行时的log，这样我们才能判断问题。

**Comment by yanyingjie007** [comment]
遇到了同样的问题，FAKE-IP 模式，纯 IPV4 网络，nslookup 查询结果www.google.com 198.18.0.13,说明内部解析正确，但是所有需要翻墙的网站全部无法打开，上周六出现，焦头烂额，直接刷机重装未解决

**Comment by yanyingjie007** [comment]
> 遇到了同样的问题，FAKE-IP 模式，纯 IPV4 网络，nslookup 查询结果www.google.com 198.18.0.13,说明内部解析正确，但是所有需要翻墙的网站全部无法打开，上周六出现，焦头烂额，直接刷机重装未解决

我解决了，发现是第三方规则的问题lhie 规则坑惨了

**Comment by vernesong** [comment]
> > 遇到了同样的问题，FAKE-IP 模式，纯 IPV4 网络，nslookup 查询结果www.google.com 198.18.0.13,说明内部解析正确，但是所有需要翻墙的网站全部无法打开，上周六出现，焦头烂额，直接刷机重装未解决
> 
> 我解决了，发现是第三方规则的问题lhie 规则坑惨了

第三方规则最近变得频繁，忍耐一下

**Comment by kettly1260** [comment]
@yanyingjie007 我也遇到了一样的问题。没有开启第三方规则，但是使用相同的订阅，在PC和clashR for Android 上都是正常的，就路由器不行。看了看连接，好像把IP识别成直连

**Comment by idoall** [comment]
> 运行在路由器上clash,订阅正常，运行正常。但是手机连接路由器后，只能打开电报，无法浏览google网页和油管程序。请问什么原因。都是使用默认设置

我遇到和你一样的问题，电报可打开

**Comment by ziyourenchina** [comment]
我没有开第三方规则。但是YouTube还是不能用

**Comment by mashirozx** [comment]
能上Google.com.hk，但是Google.com就是一直显示ERR_QUIC_PROTOCOL_ERROR

**Comment by vernesong** [comment]
> 我没有开第三方规则。但是YouTube还是不能用

youtube不能用一般是dns劫持问题，规则一般都写好了

**Comment by vernesong** [comment]
> 能上Google.com.hk，但是Google.com就是一直显示ERR_QUIC_PROTOCOL_ERROR

你关闭浏览器的quic试试呗

**Comment by yjh8047** [comment]
需要把运行模式改TUN或混合模式
