### ISSUE TITLE
不能作为adguardhome的上游服务器

### ISSUE THREAD

**Issue by warrenhoo** [vernesong/OpenClash#2171]
openclash版本：2022年03月21日版本,tun，dev版本均已更新至最新
adguardhome使用53端口替换dnsmasq53端口，dnsmasq监听6363端口，dnsmasq未设置上游服务器，仅仅自动获取营运商dns，此时，adguardhome的上游服务器设置为：127.0.0.1:6363， adguardhome测试上游服务器正常，使用正常，能监察到各个子网客户端访问了哪些网址，也就是查询了哪些域名。 将“网络”——“Turbo ACC 网络加速设置” 的dns加速（使用dnsproxy）打开，dnsmasq的上游服务器自动变化为127.0.0.1#5333（同时营运商dns文件被自动频闭）， 此时adguardhome测试上游服务器正常，照样使用正常，能监察到各个子网客户端访问了哪些网址，也就是查询了哪些域名。 关闭“网络”——“Turbo ACC 网络加速设置” 的dns加速（使用dnsproxy），暂时恢复dnsmasq没有本地上游服务器，仅仅向营运商dns查询。
打开openclash，dns监听端口保持为默认7874，勾选“*本地DNS劫持”，打开，此时，dnsmasq的上游服务器自动变化为127.0.0.1#7874（同时营运商dns文件被自动频闭），adguardhome的上游服务器设置为127.0.0.1:6363（dnsmasq)， dnsmaq的上游服务器设置为127.0.0.1#7874，整个dns的查询理想顺序为 adguardhome收到客户端查询，发向dnsmasq，再发向openclash，但是问题出现了，子网客户端访问国内域名正常，国外域名很慢，adguardhome里测试上游服务器异常， adguardhome只能监察到localhost和127.0.0.1的自身路由器的dns查询，无法监测到其他子网客户端的dns查询， 把adguardhome的上游服务器设置为127.0.0.1:7874，测试上游服务器照样异常，说明问题时出现在openclash这里。
openclash 更换redir-hose  和fakeip模式，每种模式均设置兼容、tun、混合， 都不行。
关掉openclash， 打开ssrplus，ssrplus本身就是利用dnsmasq来分流， 此时，adguardhome的上游服务器设置为127.0.0.1:6363（dnsmasq)，测试正常，监察其他子网客户端的域名解析请求正常。
我为什么要首先使用adguardhome作为第一dns查询服务器：可以直观看到哪个客户端访问了哪个域名，针对性地封锁。还有广告问题，家里自动化设备太多 了，利用andbyby去广告或者openclash去广告，自动化很迟钝， 利用adguardhome监测，直观看到这些自动化设备不停地发送dns域名查询请求，此时只要打开anti（去广告规则），可以看到这些请求都被封锁了，所以说，国产家居智能设备，说的就是某米， 不停地在追踪分析你的行为，现在只能利用adguardhome 看看是请求了哪些域名，在不影响智能化联动地情况下针对性地封锁域名请求，这个只有adguardhome 能做到。

**Comment by warrenhoo** [comment]
补充一下，几个月前地版本，openclash是可以做为adguardhome的上游服务器的，也就是说把adguardhome的上游服务器设置为127.0.0.1:7874， 测试是正常的，使用是正常的，adguardhome能监察到各个子网客户端的域名请求

**Comment by vernesong** [comment]
https://github.com/vernesong/OpenClash/discussions/1420

**Comment by warrenhoo** [comment]
> #1420

大神，我的稍有不同，我的AD已设置：使用53端口替换dnsmasq，dnsmasq不再监听53改为6363了， 此时在AD里设置上游服务器127.0.0.1:7874，测试异常，127.0.0.1:6363测试正常(openclash还未劫持dnsmasq），如果再将dnsmasq的上游更改为127.0.0.1:7874，那么在AD里设置上游服务器为127.0.0.1:6363也是异常的，所以说根源应该处在openclash这里，就算我完全弃用dnsmasq，AD里设置上游服务器127.0.0.1:7874也是异常的，可能我OP里哪里设置不对吧。

**Comment by cs-star** [comment]
一直很正常

**Comment by learnsometech** [comment]
我也是这种方法，你现在搞定了吗
