### ISSUE TITLE
导入规则之后，就被固定了

### ISSUE THREAD

**Issue by wmjlxl** [vernesong/OpenClash#218]
大神你好，

openwrt下，导入规则之后，就被固定了。服务器信息一直不会变。

我尝试卸载重启后重装，明明导入了不同规则，但是ss服务器名称依然没变。

请问设置还残留在哪些位置？
谢谢

**Comment by vernesong** [comment]
清空服务器与策略组管理页面的配置

**Comment by wmjlxl** [comment]
> 清空服务器与策略组管理页面的配置

谢谢，问题解决，还有一个问题，就是 "控制面板登录端口" 是不是就不能更改？
发现怎么改都无效，必须还是 9090 的端口。

**Comment by vernesong** [comment]
> > 清空服务器与策略组管理页面的配置
> 
> 谢谢，问题解决，还有一个问题，就是 "控制面板登录端口" 是不是就不能更改？
> 发现怎么改都无效，必须还是 9090 的端口。

重启内核才会生效

**Comment by Yoo-4x** [comment]
> > 清空服务器与策略组管理页面的配置
> 
> 谢谢，问题解决，还有一个问题，就是 "控制面板登录端口" 是不是就不能更改？
> 发现怎么改都无效，必须还是 9090 的端口。

在 /etc/config/openclash 内修改，似乎只用了自定义规则。(我的路由器上界面有bug，无法更新config，只能在后台找，后发现在下载后直接对yaml修改无用，看代码找到了这个配置文件)
