### ISSUE TITLE
最新版openclash fakeip模式下上传掉速度

### ISSUE THREAD

**Issue by samanhk2** [vernesong/OpenClash#2181]
套餐上传100m，开启后只有10m，tun模式下只有5m

**Comment by HoHoibin** [comment]
我300M掉到10M

**Comment by MBRjun** [comment]
硬路由性能低用 TUN 网速慢正常，没有需求老老实实 Redir，有需求建议混合模式

**Comment by Zayia** [comment]
哇，我才发现是这个问题，我联通50m的上传被限制成10m，我以为是联通宽带给我限速的，我换了电信宽带，结果发现上传还是只有10m，就知道坏事了
我先停了clash试试，结果真是这个软件的问题

**Comment by MBRjun** [comment]
只掉上传还是上下都有问题

> 哇，我才发现是这个问题，我联通50m的上传被限制成10m，我以为是联通宽带给我限速的，我换了电信宽带，结果发现上传还是只有10m，就知道坏事了 我先停了clash试试，结果真是这个软件的问题

**Comment by Zayia** [comment]
> 只掉上传还是上下都有问题
> 
> > 哇，我才发现是这个问题，我联通50m的上传被限制成10m，我以为是联通宽带给我限速的，我换了电信宽带，结果发现上传还是只有10m，就知道坏事了 我先停了clash试试，结果真是这个软件的问题

只掉上传
下行没事
就是因为只有上传速度掉了，但是下载速度没事才以为是运营商的问题
之前没出现过这个问题，应该就是过了1月1号才发现的这个问题

**Comment by QingShuiHePan** [comment]
之前没有发现这个问题，远程群辉Nas在有openlash的环境下上传不超过2M，在正常网络下上传可到60M
