### ISSUE TITLE
一直显示正在收据数据是什么原因啊？

### ISSUE THREAD

**Issue by xx791117** [vernesong/OpenClash#2182]
更新了最新版之后，一直显示正在收据数据是什么原因啊？日至也没有内容

**Comment by liofoil** [comment]
我也有这个问题，luci版本较新是21.02，注意到过以下两个现象：
openclash上传好配置文件点击启动后会有几率导致路由器后台界面进不去，必须要重启路由器才行。
勾选完一些设置选项，点击应用设置跳回运行状态界面后，除了运行模式以外，其它地方均是正在收集数据，这时候有很大概率国内外的网就全断了，而且再次重启路由器也无法恢复。
