### ISSUE TITLE
不支持firewall4

### ISSUE THREAD

**Issue by abc9878** [vernesong/OpenClash#2192]
22.03默认使用firewall4，openclash以redir模式开启后不生效。用tun模式会导致国内网站无法上。

**Comment by vernesong** [comment]
不支持nftables,请安装iptables

**Comment by abc9878** [comment]
叹气。只能这样了。
-firewall4 -nftables -kmod-nft-offload \
firewall iptables-legacy kmod-inet-diag coreutils-nohup dnsmasq-full curl ca-certificates ipset ip-full iptables-mod-tproxy iptables-mod-extra libcap libcap-bin ruby ruby-yaml kmod-tun

**Comment by ctz556** [comment]
> 

22.03使用Actions应该如何通过修改.config来编译？

**Comment by sky96111** [comment]
> 不支持nftables,请安装iptables

考虑做nftables适配吗？OpenWrt官方22.03.0分支开始改用nftables了
