### ISSUE TITLE
无法更新订阅，无法下载订阅，Unable to renew subscription, unable to download subscription

### ISSUE THREAD

**Issue by li2518888** [vernesong/OpenClash#2194]
切换了两个网络，切换了两个机场，都是无法下载订阅，请检查网络
Switched two networks, switched two airports, both failed to download the subscription, please check the network.
![无法更新订阅](https://user-images.githubusercontent.com/100082103/160406349-cfa12144-a8c2-4d46-88c5-d967f2d72d56.png)
![2](https://user-images.githubusercontent.com/100082103/160406355-c8565e73-0976-49c1-ae5b-a5fc022b124d.jpg)

**Comment by xiaochong113** [comment]
> 

我更新

> subconverter?

我更新0.44.34也遇到这个问题，无法更新订阅。0.44.29版本是正常的，用的subconverter。

**Comment by vernesong** [comment]
dev呢

**Comment by Pollo3470** [comment]
> dev呢

我也是配置文件更新失败，默认的两个都不行，换成id9那个可以

**Comment by ForestL18** [comment]
我这边是45.16，用subconverter更新会一直循环更新rulesets，最后显示订阅失败，是网页延时，导致刷新造成的吗？

**Comment by vernesong** [comment]
现在会一直等内核下载，内核没报错退出就会一直等，建议先自己下载下来

**Comment by ForestL18** [comment]
> 现在会一直等内核下载，内核没报错退出就会一直等，建议先自己下载下来

是新版内核问题？
