### ISSUE TITLE
请问openclash有没有自动优选IP的方案

### ISSUE THREAD

**Issue by SamZig** [vernesong/OpenClash#2195]
请问openclash有没有自动优选IP的方案，
节点用的CF的小云朵

**Comment by vernesong** [comment]
什么意思

**Comment by eggydutch** [comment]
这和openclash有什么关系，目前有哪个科学软件有cloudflare cdn ip优选吗？

**Comment by Nvsdyi** [comment]
> 什么意思

就是cloudflare cdn某些ip大陆访问速度不错，搭配上ws可以实现代理走cdn 可以看看这个项目 https://github.com/XIU2/CloudflareSpeedTest

**Comment by SamZig** [comment]
> > 什么意思
> 
> 就是cloudflare cdn某些ip大陆访问速度不错，搭配上ws可以实现代理走cdn 可以看看这个项目 https://github.com/XIU2/CloudflareSpeedTest

是的 目前passwall可以

**Comment by liusex** [comment]
再搞个自动测速节点的功能，这个自动测速不同于现在的测试反应速度，而是测试下载速度，因为某些节点反应很快但是连接速度很慢，而很多可以看高清的节点其反应速度很慢。
或者弄个反应速度和连接速度的选项，让使用的人自己选择用哪个速度，还是说两者兼容，哪个优先等等。我觉得非常有必要。

**Comment by goophoo** [comment]
写了两个小脚本，可以完成你说的自动优选IP的方案；
https://github.com/goophoo/auto-update-cf-cdn-for-openclash

**Comment by senzige300** [comment]
> 写了两个小脚本，可以完成你说的自动优化IP的方案； https://github.com/goophoo/auto-update-cf-cdn-for-openclash

大佬我看了你的脚本了，但是不知道怎么使用，把一个脚本放到主路由上是什么个意思？

**Comment by goophoo** [comment]
> > 写了两个小脚本，可以完成你说的自动优化IP的方案； https://github.com/goophoo/auto-update-cf-cdn-for-openclash
> 
> 大佬我看了你的脚本了，但是不知道怎么使用，把一个脚本放到主路由上是什么个意思？

脚本已经完全更新了， 不再使用重启openclash的方式更新CDN了，而是使用调用Cloudflare API的方式来更新DNS记录；
因为测速是要在没有梯子的路由器上，一般宽带拨号的主路由，没有安装openclash, 所以测速相关的脚本都放在主路由上，其它调用CF API的脚本都在旁路由上运行。

**Comment by cnhap** [comment]
> > > 写了两个小脚本，可以完成你说的自动优化IP的方案； https://github.com/goophoo/auto-update-cf-cdn-for-openclash
> > 
> > 
> > 大佬我看了你的脚本了，但是不知道怎么使用，把一个脚本放到主路由上是什么个意思？
> 
> 脚本已经完全更新了， 不再使用重启openclash的方式更新CDN了，而是使用调用Cloudflare API的方式来更新DNS记录； 因为测速是要在没有梯子的路由器上，一般宽带拨号的主路由没有安装openclash, 所以测速相关的脚本都放在主路由上，其它调用CF API的脚本都在旁路由上运行。

您的这个我也看了,可用域名的方式,会遇到域名被阻断的问题,能直接改配置文件里的IP是最好的,passwall2就这样用的,现在想看看怎么在openclash实现直接改配置文件里IP的方式.

**Comment by goophoo** [comment]
> > > > 写了两个小脚本，可以完成你说的自动优化IP的方案； https://github.com/goophoo/auto-update-cf-cdn-for-openclash
> > > 
> > > 
> > > 大佬我看了你的脚本了，但是不知道怎么使用，把一个脚本放到主路由上是什么个意思？
> > 
> > 
> > 脚本已经完全更新了， 不再使用重启openclash的方式更新CDN了，而是使用调用Cloudflare API的方式来更新DNS记录； 因为测速是要在没有梯子的路由器上，一般宽带拨号的主路由没有安装openclash, 所以测速相关的脚本都放在主路由上，其它调用CF API的脚本都在旁路由上运行。
> 
> 您的这个我也看了,可用域名的方式,会遇到域名被阻断的问题,能直接改配置文件里的IP是最好的,passwall2就这样用的,现在想看看怎么在openclash实现直接改配置文件里IP的方式.

目前用了快两年了，没遇到域名被阻断的问题，可能是因为DOH的缘故吧。你试试别用任何赵国的DNS，全部替换为国外的DOH.

**Comment by Antecer** [comment]
> > > > > 写了两个小脚本，可以完成你说的自动优化IP的方案； https://github.com/goophoo/auto-update-cf-cdn-for-openclash
> > > > 
> > > > 
> > > > 大佬我看了你的脚本了，但是不知道怎么使用，把一个脚本放到主路由上是什么个意思？
> > > 
> > > 
> > > 脚本已经完全更新了， 不再使用重启openclash的方式更新CDN了，而是使用调用Cloudflare API的方式来更新DNS记录； 因为测速是要在没有梯子的路由器上，一般宽带拨号的主路由没有安装openclash, 所以测速相关的脚本都放在主路由上，其它调用CF API的脚本都在旁路由上运行。
> > 
> > 
> > 您的这个我也看了,可用域名的方式,会遇到域名被阻断的问题,能直接改配置文件里的IP是最好的,passwall2就这样用的,现在想看看怎么在openclash实现直接改配置文件里IP的方式.
> 
> 目前用了快两年了，没遇到域名被阻断的问题，可能是因为DOH的缘故吧。你试试别用任何赵国的DNS，全部替换为国外的DOH.

提个问题，如果OpenClash就是安装在主路由的，咋整？
