### ISSUE TITLE
etc/openclash 目录下无core目录

### ISSUE THREAD

**Issue by foxnake** [vernesong/OpenClash#2198]
**设备信息** 
Base on OpenWrt R22.3.13 by lean & lienol
 Kernel 5.16.18-kissyouhunter
 Packaged by kissyouhunter on 2022-03-29
 PLATFORM: amlogic  SOC: s905d  BOARD: n1

设备信息： Phicomm N1
CPU 型号:  AArch64 : Cortex-A53 x 4
系统负载:  1.27 0.74 0.35       运行时间:  7分钟 19秒           
环境温度:  48.0 °C              当前频率:  1000 Mhz
内存已用:  6% of 1935MB         IP  地址:  192.168.2.2
启动存储:  18% of 511.0M        系统存储:  36% of 720.0M        
数据存储:  1% of 5.1G     

故障描述：

Openclash总是提示内核不存在，手动上传的时候发现...etc/openclash路径下没有core目录

<img width="639" alt="image" src="https://user-images.githubusercontent.com/81220700/160743653-ee82df5c-b0bf-4778-9949-61c2394c19e4.png">

于是手动创建...etc/openclash/core文件夹，并且赋予所有权限，之后上传clash、clash_tun内核文件到..etc/openclash/core，在openclash页面启动Openclash，还是提示内核不存在。重启OpenWrt之后，进入...etc/openclash/目录，发现core文件夹消失了。

再次回到Openclash管理页面进行内核更新下载操作，发现内核文件直接下载到了...etc/openclash/目录下。

OpenWrt固件内置Openclash版本为  v0.44.34-beta

**Comment by Dawneng** [comment]
> 

![20220330162517](https://user-images.githubusercontent.com/44763845/160786719-f0fa6213-c73b-46b0-a2d6-4c3e4205fe6e.png)
etc/openclash/clash 是指向etc/openclash/core里的clash核心

**Comment by foxnake** [comment]
> > 
> 
> ![20220330162517](https://user-images.githubusercontent.com/44763845/160786719-f0fa6213-c73b-46b0-a2d6-4c3e4205fe6e.png) etc/openclash/clash 是指向 etc/openclash/core 里的 clash 核心

明白了，但我的问题是 etc/openclash/目录下没有core文件夹，即便是我自己手动创建，也会消失，我怀疑这是频繁监测不到内核文件的原因

**Comment by vernesong** [comment]
这个文件夹安装的时候会自己创建，没代码去故意删的，你更新dev试试下载问题解决没有

**Comment by foxnake** [comment]
> 这个文件夹安装的时候会自己创建，没代码去故意删的，你更新 dev 试试下载问题解决没有

目前好了，不过我除了更新内核和客户端之外没有别的操作，估计还是因为网络不畅通导致下载内核的问题？
