### ISSUE TITLE
请问 全局设置里的追加上游DNS是干什么的？需要勾选吗？

### ISSUE THREAD

**Issue by w504925264** [vernesong/OpenClash#2199]
![屏幕截图 2022-03-30 120736](https://user-images.githubusercontent.com/32632848/160749627-5a150f29-2cff-4365-b79e-7082934d3239.png)

**Comment by eggydutch** [comment]
把你运营商分配的dns追加到openclash的dns列表里，我自己的选择是不选，因为以前试过加了后会造成dns污染。

**Comment by w504925264** [comment]
@eggydutch   好的 謝謝
