### ISSUE TITLE
全局设置的每一个子页面都有相同的几个配置

### ISSUE THREAD

**Issue by wangxin6** [vernesong/OpenClash#22]
全局设置的每一个子页面都有相同的几个配置：

设置自定义上游DNS服务器，在上方DNS设置中启用本功能后生效
设置SOCKS5/HTTP(S)认证信息
设置自定义规则，在上方规则设置中启用本功能后生效
设置自定义Hosts，仅在Redir-Host模式下生效（不会覆盖配置文件设置）

都是同一配置，不懂为什么需要重复？

**Comment by vernesong** [comment]
不是重复，是openwrt限制那几个模块只能那样固定在页面上，跟上面的标签没关系。
