### ISSUE TITLE
游戏加速如何设置？

### ISSUE THREAD

**Issue by icucuio** [vernesong/OpenClash#2200]
![image](https://user-images.githubusercontent.com/69136587/160762818-616addcd-246b-4a41-8e5f-bbdd3e3c9fab.png)

请教下，如何设置游戏加速

**Comment by vernesong** [comment]
指定好规则对应的策略组，策略组里面放ss和trojan节点，需要节点支持UDP

**Comment by icucuio** [comment]
> 

大佬，在《选择策略组》那里只能选择“DIRECT” 和“REJECT”啊，我的配置文件里面都加了UDP启用
给给个例子吗？
