### ISSUE TITLE
Opkg install segmentation fault

### ISSUE THREAD

**Issue by zli070211** [vernesong/OpenClash#2206]
您好，尝试在x86-64 openwrt 20.02.2 上安装openclash时出现如下问题：
 - dependencies: unknown package 'kmod-inet-diag' （已知问题）
 - install ipk: Segmentation fault （具体信息请看截图）
![image](https://user-images.githubusercontent.com/102834699/161347548-71201d28-995a-44cf-8192-0cc19ca0221a.png)
请问是否为bug？谢谢！

**Comment by congxiaodan** [comment]
同缺少 kmod-inet-diag 这个依赖。

**Comment by vernesong** [comment]
包有问题，重新下载试试

**Comment by zli070211** [comment]
> 包有问题，重新下载试试

感谢回复！折腾了一晚之后：
 - 之前的下载用的是wget直接下载到openwrt，最新的两个ipk版本都会报segmentation fault
 - 使用LuCI界面 System -> Software -> Upload Packages上传并安装下载到电脑的ipk时，最新版仍旧报错（应该是kmod-inet-diag的问题），但0.44.34版ipk能够成功安装
 - 0.44.34版ipk安装之后无法正常进入LuCI界面，错误信息类似于’luci.cbi.??? not found'。最后通过重新安装luci，luci-base和luci-compat解决了问题

不知是否是wget的问题，希望这些信息对你有用，第一次用github issue，如果希望关闭这个issue请告知我。感谢你在openclash里倾注的心血！
