### ISSUE TITLE
升级失败，OpenClash 直接没了

### ISSUE THREAD

**Issue by LittleNewton** [vernesong/OpenClash#2207]
Bug还是故意删库？

**Comment by LittleNewton** [comment]
```
404 未找到
对不起，请求的目标未找到。

No page is registered at '/admin/services/openclash'. If this url belongs to an extension, make sure it is properly installed. If the extension was recently installed, try removing the /tmp/luci-indexcache file.

无法调度: /cgi-bin/luci/admin/services/openclash
```

**Comment by icetea0822** [comment]
我也是，直接下载安装包重新安装一下吧，安装完重新登录一下

**Comment by G0m3e** [comment]
应该是需要kmod-inet-diag依赖，我AX3600还没找到这个依赖所以安装失败了，升级完也没了

**Comment by LittleNewton** [comment]
我又 kmod-inet-diag，肯定是其他原因。git commits 里，作者删除了很多东西。

**Comment by ksong008** [comment]
> kmod-inet-diag
有这个依赖直接升级没问题的

**Comment by w12928293** [comment]
我这OP也是，怀疑是没有那个新的依赖，手动重装也失败，不过重新登录之后OpenClash又出现了，日志显示升级失败。

**Comment by LittleNewton** [comment]
@vernesong 升级策略可能需要重新权衡一下。

**Comment by chinesepyanyue** [comment]
遇到了同样的问题。
因为广为大家使用的lean的openwrt 默认配置好像就是没有选kmod-inet-diag 的，所以估计很多人都会遇到这个问题。
重新编译固件加上应该可以解决，但太麻烦了，一堆应用要重新安装，能通过其他方法安装上这个依赖码？

**Comment by Karmylr** [comment]
编译新固件就可以了。带上kmod-inet-diag

**Comment by silmee** [comment]
我也不想重新编译，kmod-inet-diag  有其他办法么

**Comment by we11adam** [comment]
个人认为引入这种 breaking change 不是特别妥当的做法，尤其是在官方 stable 版本里无法通过包管理安装这个依赖。不能假定每个用户都具备可以自行重新编译 OpenWrt 的技术储备或者可以承担相应的时间精力。

**Comment by aueu** [comment]
是检测闪存大小的代码出问题了，会提示闪存不足...

**Comment by LittleNewton** [comment]
![image](https://user-images.githubusercontent.com/17793356/161377670-2bc3967b-3180-4273-943b-c95fe9366c03.png)
目前认为和`kmod-inet-diag`没有直接关系，因为我的版本本身就有这个内核模块。

**Comment by XinSSS** [comment]
我是M独立编译openclash的, 今天发现安装失败了, 少了个kmod-inet-diag , 找到target里的ipk后就安装成功了
[luci-app-openclash_0.44.41-beta_all.zip](https://github.com/vernesong/OpenClash/files/8402342/luci-app-openclash_0.44.41-beta_all.zip)
[kmod-inet-diag_5.15.32-1_x86_64.zip](https://github.com/vernesong/OpenClash/files/8402343/kmod-inet-diag_5.15.32-1_x86_64.zip)

**Comment by silmee** [comment]
> 我是M独立编译openclash的, 今天发现安装失败了, 少了个kmod-inet-diag , 找到target里的ipk后就安装成功了 [luci-app-openclash_0.44.41-beta_all.zip](https://github.com/vernesong/OpenClash/files/8402342/luci-app-openclash_0.44.41-beta_all.zip) [kmod-inet-diag_5.15.32-1_x86_64.zip](https://github.com/vernesong/OpenClash/files/8402343/kmod-inet-diag_5.15.32-1_x86_64.zip)

这个kmod-inet-diag我这5.4内核不支持了

**Comment by i5ean** [comment]
也出现了同样的问题

**Comment by cby-chen** [comment]
内核  5.4.179 不支持   (艹皿艹 )

**Comment by micawberism-jwk** [comment]
直接就无了

**Comment by liusex** [comment]
我也是，没有那个依赖。

**Comment by mmeiwenlong** [comment]
> 我是M独立编译openclash的, 今天发现安装失败了, 少了个kmod-inet-diag , 找到target里的ipk后就安装成功了 [luci-app-openclash_0.44.41-beta_all.zip](https://github.com/vernesong/OpenClash/files/8402342/luci-app-openclash_0.44.41-beta_all.zip) [kmod-inet-diag_5.15.32-1_x86_64.zip](https://github.com/vernesong/OpenClash/files/8402343/kmod-inet-diag_5.15.32-1_x86_64.zip)
![QQ截图20220402222702](https://user-images.githubusercontent.com/44661424/161387864-6380dcc9-81c8-4893-bd7d-cd1a1035980e.png)


你能单独安装这个ipk成功？

**Comment by i5ean** [comment]
> 我是M独立编译openclash的, 今天发现安装失败了, 少了个kmod-inet-diag , 找到target里的ipk后就安装成功了 [luci-app-openclash_0.44.41-beta_all.zip](https://github.com/vernesong/OpenClash/files/8402342/luci-app-openclash_0.44.41-beta_all.zip) [kmod-inet-diag_5.15.32-1_x86_64.zip](https://github.com/vernesong/OpenClash/files/8402343/kmod-inet-diag_5.15.32-1_x86_64.zip)

我是esir的固件，无法安装你发的这个kmod-inet-diag

**Comment by XinSSS** [comment]
> > 我是M独立编译openclash的, 今天发现安装失败了, 少了个kmod-inet-diag , 找到target里的ipk后就安装成功了 [luci-app-openclash_0.44.41-beta_all.zip](https://github.com/vernesong/OpenClash/files/8402342/luci-app-openclash_0.44.41-beta_all.zip) [kmod-inet-diag_5.15.32-1_x86_64.zip](https://github.com/vernesong/OpenClash/files/8402343/kmod-inet-diag_5.15.32-1_x86_64.zip)
> 
> 我是esir的固件，无法安装你发的这个kmod-inet-diag

不能, 我是x86的

**Comment by XinSSS** [comment]
> > 我是M独立编译openclash的, 今天发现安装失败了, 少了个kmod-inet-diag , 找到target里的ipk后就安装成功了 [luci-app-openclash_0.44.41-beta_all.zip](https://github.com/vernesong/OpenClash/files/8402342/luci-app-openclash_0.44.41-beta_all.zip) [kmod-inet-diag_5.15.32-1_x86_64.zip](https://github.com/vernesong/OpenClash/files/8402343/kmod-inet-diag_5.15.32-1_x86_64.zip)
> > ![QQ截图20220402222702](https://user-images.githubusercontent.com/44661424/161387864-6380dcc9-81c8-4893-bd7d-cd1a1035980e.png)
> 
> 你能单独安装这个ipk成功？

看上去内核不同版本...我的是5.15的

**Comment by Mosney** [comment]
> 我是esir的固件，无法安装你发的这个kmod-inet-diag

kmod都是要匹配内核版本的，自编译版就别想了，几乎不可能匹配上，用OpenWrt官方分支才可以直接使用包管理安装这些包。问题是这次官方分支21.02.2包仓库没有这个`kmod-inet-diag`，并且官方稳定版目前的内核版本号是5.4.179，也跟上面给出的预编译包不匹配。

**Comment by XinSSS** [comment]
> > 我是esir的固件，无法安装你发的这个kmod-inet-diag
> 
> kmod都是要匹配内核版本的，自编译版就别想了，几乎不可能匹配上，用OpenWrt官方分支才可以直接使用包管理安装这些包。 问题是这次OpenClash需要的这个`kmod-inet-diag`包目前在官方的包仓库里并不存在，并且官方分支稳定版21.02.2目前的内核版本号是5.4.179，上面给出的预编译包也不匹配此内核版本故也无法直接使用。

学习了, 看来是要大家都得再来一遍编译了

**Comment by Karmylr** [comment]
> > 我是esir的固件，无法安装你发的这个kmod-inet-diag
> 
> kmod都是要匹配内核版本的，自编译版就别想了，几乎不可能匹配上，用OpenWrt官方分支才可以直接使用包管理安装这些包。 问题是这次OpenClash需要的这个`kmod-inet-diag`包目前在官方的包仓库里并不存在，并且官方分支稳定版21.02.2目前的内核版本号是5.4.179，上面给出的预编译包也不匹配此内核版本故也无法直接使用。

存在啊

**Comment by Mosney** [comment]
> > kmod都是要匹配内核版本的，自编译版就别想了，几乎不可能匹配上，用OpenWrt官方分支才可以直接使用包管理安装这些包。 问题是这次OpenClash需要的这个`kmod-inet-diag`包目前在官方的包仓库里并不存在，并且官方分支稳定版21.02.2目前的内核版本号是5.4.179，上面给出的预编译包也不匹配此内核版本故也无法直接使用。
> 
> 存在啊

说了是稳定分支21.02.2，当前的[包仓库](https://downloads.openwrt.org/releases/21.02.2/targets/x86/64/packages/)并没有`kmod-inet-diag`，只有[snapshot分支的包仓库](https://downloads.openwrt.org/snapshots/targets/x86/64/packages/)存在`kmod-inet-diag`，但由于这是kmod包依然需要匹配内核版本，故无论是稳定版还是坊间各路自编译版，只要内核版本对不上目前snapshot的`5.10.109`就无法直接使用.

**Comment by mmeiwenlong** [comment]
> > > 我是M独立编译openclash的, 今天发现安装失败了, 少了个kmod-inet-diag , 找到target里的ipk后就安装成功了 [luci-app-openclash_0.44.41-beta_all.zip](https://github.com/vernesong/OpenClash/files/8402342/luci-app-openclash_0.44.41-beta_all.zip) [kmod-inet-diag_5.15.32-1_x86_64.zip](https://github.com/vernesong/OpenClash/files/8402343/kmod-inet-diag_5.15.32-1_x86_64.zip)
> > > ![QQ截图20220402222702](https://user-images.githubusercontent.com/44661424/161387864-6380dcc9-81c8-4893-bd7d-cd1a1035980e.png)
> > 
> > 
> > 你能单独安装这个ipk成功？
> 
> 看上去内核不同版本...我的是5.15的
![QQ截图20220402233015](https://user-images.githubusercontent.com/44661424/161390162-603b399c-dbf8-453e-9119-dab1348e2052.png)

我也是5.15

**Comment by derekling** [comment]
尽快修复吧 多谢了 重装太麻烦

**Comment by Karmylr** [comment]
> 尽快修复吧 多谢了 重装太麻烦

不会修复的。只是缺依赖而已

**Comment by srduino** [comment]
提高技术门槛！有效防止小白用户入场！

**Comment by mmeiwenlong** [comment]
> 提高技术门槛！有效防止小白用户入场！

暂时可以用升级了，最新的去了这个依赖

**Comment by AllForLandlord** [comment]
> 

还好去掉了，我没看需要什么依赖就升级了，升级完看了下确实是缺了一个，好险

**Comment by cby-chen** [comment]
编译了一个 内核为 5.4.188 版本的，大家试试

[kmod-inet-diag_5.4.188-1_x86_64.zip](https://github.com/vernesong/OpenClash/files/8404153/kmod-inet-diag_5.4.188-1_x86_64.zip)
看

**Comment by AllForLandlord** [comment]
膜拜前辈们，我本来还以为直接用opkg install命令下载个依赖就行了，原来还要考虑openwrt内核的版本。看了下我内核是5.4.162，楼上说5.4.179都不能装这个依赖，那看来我是不能享受之后的版本了

**Comment by cby-chen** [comment]
正在尝试编译 5.4.179 版本

**Comment by chinesepyanyue** [comment]
我重新编译了一遍最新的lean的固件。这是我编译出来的5.15.32 内核的kmod-inet-diag 
[kmod-inet-diag_5.15.32-1_x86_64.ipk.zip](https://github.com/vernesong/OpenClash/files/8404202/kmod-inet-diag_5.15.32-1_x86_64.ipk.zip)

**Comment by mmeiwenlong** [comment]
> 正在尝试编译 5.4.179 版本
以编译5.15 
![QQ截图20220403174431](https://user-images.githubusercontent.com/44661424/161421738-8c44d07e-8dfb-40f4-968a-99a2d434b303.png)
![QQ截图20220403174742](https://user-images.githubusercontent.com/44661424/161421763-b751c548-067b-4f4b-b242-9ef647a26440.png)

**Comment by Kisoul** [comment]
![image](https://user-images.githubusercontent.com/32985553/161432143-222eaa95-5fbd-4941-bc60-2cacb80d3a66.png)
稀里糊涂升级了它自己装上去了，就是这个版本实在是难受，目前情况正常

**Comment by ishkong** [comment]
我使用 Boos4721 大佬的库增加相关内容编译了一个 有需要可以自取
https://github.com/ishkong/AX6-AX3600-openwrt-self-use/releases/download/2022.04.04-1505/kmod-inet-diag_5.10.109-1_aarch64_cortex-a53.ipk

**Comment by MBRjun** [comment]
求一个 5.10.91 的 kmod-inet-diag

**Comment by MBRjun** [comment]
> 提高技术门槛！有效防止小白用户入场！

这下子蚌埠住了😅

**Comment by AllForLandlord** [comment]
那我也求一个5.4.162的kmod-inet-diag

**Comment by tonyqus** [comment]
亲测！
直接在x-wrt里进入OpenClash->插件设置->版本更新，找到客户端更新，点击检查并更新，从0.45.70beta自动升级到了0.45.112beta最新版，运行正常。

![image](https://user-images.githubusercontent.com/772561/232618694-53a2cf12-2154-48f8-8c08-b3638d48edcd.png)

**Comment by bigsb-scw** [comment]
openclash直接没了

**Comment by Karmylr** [comment]
> openclash直接没了

看系统日志
