### ISSUE TITLE
点击一键检查更新，tun内核最新版本为旧的

### ISSUE THREAD

**Issue by zzcabc** [vernesong/OpenClash#2208]
![image](https://user-images.githubusercontent.com/46120743/161366114-cc4b0e43-55fd-44cd-a4b2-7e5ecec69631.png)
升级前最新为03.21 升级到0.44.41，最新的tun为03.19

**Comment by vernesong** [comment]
各个CDN有缓存，等待刷新

**Comment by fanck0605** [comment]
@vernesong 应该是 release 里的文件损坏导致的，需要重新上传一下

![image](https://user-images.githubusercontent.com/28819315/161374644-50f27cfe-5b16-4f22-8592-e1bb753d4ac8.png)

**Comment by vernesong** [comment]
版本号跟这个没关系，是个文本文件

**Comment by fanck0605** [comment]
不好意思，我以为这个内置的检查更新是从 https://github.com/vernesong/OpenClash/releases/tag/TUN-Premium 下载的。
这里面的二进制文件有问题，需要重新上传一下。

**Comment by vernesong** [comment]
好的

**Comment by zzcabc** [comment]
重启clash后显示正常
