### ISSUE TITLE
error: dial tcp4 123.120.104.7:6800: i/o timeout

### ISSUE THREAD

**Issue by JingenChen** [vernesong/OpenClash#221]
这个错误是啥意思？

time="2020-03-10T06:24:32Z" level=warning msg="dial 🎯 全球直连 error: dial tcp4 123.120.104.7:6800: i/o timeout"
time="2020-03-10T06:24:32Z" level=warning msg="dial 🎯 全球直连 error: dial tcp4 123.120.104.7:6800: i/o timeout"
time="2020-03-10T06:24:32Z" level=warning msg="dial 🎯 全球直连 error: dial tcp4 123.120.104.7:6800: i/o timeout"
time="2020-03-10T06:24:32Z" level=warning msg="dial 🎯 全球直连 error: dial tcp4 123.120.104.7:6800: i/o timeout"
time="2020-03-10T06:24:32Z" level=warning msg="dial 🎯 全球直连 error: dial tcp4 123.120.104.7:6800: i/o timeout"
time="2020-03-10T06:24:32Z" level=warning msg="dial 🎯 全球直连 error: dial tcp4 123.120.104.7:6800: i/o timeout"

**Comment by liangxyz** [comment]
链接超时，你这个是直连的，所以应该是那个端口关了

**Comment by JingenChen** [comment]
请问怎么查看发起这些连接的局域网主机是哪个？这个error前后没找到

**Comment by vernesong** [comment]
> 请问怎么查看发起这些连接的局域网主机是哪个？这个error前后没找到

控制面板

**Comment by JingenChen** [comment]
> > 请问怎么查看发起这些连接的局域网主机是哪个？这个error前后没找到
> 
> 控制面板

控制面板里看不到这个错误对应的局域网主机IP吧？
