### ISSUE TITLE
0.44.41流媒体解锁检测失败

### ISSUE THREAD

**Issue by kk-cao** [vernesong/OpenClash#2211]
手动测试 无论是 
解锁检测（选择）还是 测试所有节点 都失败

显示信息：
正在收集数据...
发生了一些错误，测试失败...

log提示
2022-04-02 22:29:31 提示：开始自动选择（检测）Netflix 解锁节点...
2022-04-02 21:59:28 提示：开始自动选择（检测）Netflix 解锁节点...

**Comment by vernesong** [comment]
https://github.com/vernesong/OpenClash/blob/92d1f3f9d1e29a0867f50d3011c46e8eb6a95a2c/luci-app-openclash/root/usr/share/openclash/openclash_streaming_unlock.lua#L23
前面加一句

```
print(tonumber(self_status))
```
看看输出内容

**Comment by kk-cao** [comment]
打开 全局设置下的 路由本机代理 后 恢复正常
