### ISSUE TITLE
如何设置订阅地址的超时时间

### ISSUE THREAD

**Issue by Sucre-2333** [vernesong/OpenClash#2212]
由于是自己写的模板分流规则比较大在openclash上订阅一直超时无法正常获取订阅连接（其他客户端正常）
---------------------------------------------------------------------------------------------------------------------
2022-04-03 01:53:26 错误：【WoW】下载失败，请检查网络或稍后再试...
2022-04-03 01:53:04 错误：配置文件【WoW】订阅失败，尝试不使用代理下载配置文件...
2022-04-03 01:52:46 开始更新配置文件【WoW】...

**Comment by vernesong** [comment]
目前是超过30秒，或者15秒没速度会终止下载https://github.com/vernesong/OpenClash/blob/92d1f3f9d1e29a0867f50d3011c46e8eb6a95a2c/luci-app-openclash/root/usr/share/openclash/openclash.sh#L57 
请你自行测试后提供合适的参数

**Comment by Sucre-2333** [comment]
> 

好的 谢谢
