### ISSUE TITLE
请问有没有办法在不更换openwrt的前提下安装上kmod-inet-diag

### ISSUE THREAD

**Issue by warcns** [vernesong/OpenClash#2215]
我在使用OpenWrt R20.7.20 GDQ v8.1版本，在系统 - 软件包 中安装kmod-inet-diag的时候提示以下错误，请问各位大佬有没有办法在不换openwrt的前提下安装上kmod-inet-diag？

如果不行的话难道升级openclash就必须得升级openwrt？这是不是有点夸张了，得完全重做软路由的系统。

> Installing kmod-inet-diag (5.10.109-1) to root...
Downloading https://downloads.openwrt.org/snapshots/targets/x86/64/packages/kmod-inet-diag_5.10.109-1_x86_64.ipk
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-inet-diag:
 * 	kernel (= 5.10.109-1-974809f18940ab659f16306b93f28d72)
 * opkg_install_cmd: Cannot install package kmod-inet-diag.

**Comment by ppyohhh** [comment]
难 我用的官方21.02.2 基本是要无解了

**Comment by ppyohhh** [comment]
先用今天的43版本 然后以后官方出稳定版再升级再弄吧

**Comment by liaryshee** [comment]
https://openwrt.org/docs/guide-user/additional-software/opkg#options

https://www.google.com/search?q=%E5%BC%BA%E5%88%B6%E5%AE%89%E8%A3%85ipk

自行承担后果

**Comment by cby-chen** [comment]
编译了一个5.4.188 内核版本的

[kmod-inet-diag_5.4.188-1_x86_64.zip](https://github.com/vernesong/OpenClash/files/8404159/kmod-inet-diag_5.4.188-1_x86_64.zip)

**Comment by mmeiwenlong** [comment]
![QQ截图20220403174431](https://user-images.githubusercontent.com/44661424/161421674-399a5887-eb06-455c-92bc-a4cb88fd7e9e.png)

**Comment by paladin4fan** [comment]
编译openwrt时 如果修改.config文件里与内核、kmod相关的包、选项
编译出来的kernel version就会变化
所以如果是自己手动编译的固件 就会产生一个你自己的version
软件源里的kmod包你就用不了了
所以编译openwrt固件的时候会把没有勾上的kmod包都编译出ipk 并且生成sdk
