### ISSUE TITLE
Feature Request: 能否有一个选项可以去掉防火墙中对于谷歌dns的劫持

### ISSUE THREAD

**Issue by liofoil** [vernesong/OpenClash#2217]
由于流媒体服务解锁的需要，我希望能够完全自己设置各类dns请求的去向：目前我关闭了openclash中的“本地dns劫持”，但是当我在本地dns服务器上设置tcp谷歌dns后会因为劫持导致回环，而udp谷歌dns的请求就绕过了这个限制；
经过排查发现是防火墙中默认设置了对tcp谷歌dns的劫持，所以希望可以有一个选项用于彻底去除这种劫持，也就是下面图中的劫持规则。
![image](https://user-images.githubusercontent.com/53076556/161418261-6af06d76-c8bf-4ae1-a49b-296e12642029.png)
![image](https://user-images.githubusercontent.com/53076556/161418242-9f6be556-4954-43ec-9189-78e473c8284e.png)

**Comment by vernesong** [comment]
这个属于特殊需求，建议自行改脚本代码

**Comment by liofoil** [comment]
自己修改的话，每次更新openclash都要重新改，这样比较麻烦呢

**Comment by OUZYcn** [comment]
> 自己修改的话，每次更新openclash都要重新改，这样比较麻烦呢

看着你都挺熟悉的啊，，写个脚本然后设置定时检查，自动修改不好？
