### ISSUE TITLE
0.44.42无法启用流媒体解锁功能

### ISSUE THREAD

**Issue by hirintou** [vernesong/OpenClash#2218]
更新固件后也同步更新了订阅，部分log显示如下：
2022-04-03 16:16:11 OpenClash 启动成功，请等待服务器上线！
2022-04-03 16:16:11 第十步: 添加计划任务,启动进程守护程序...
2022-04-03 16:16:11 第九步: 重启 Dnsmasq 程序...

旧版本显示完以上内容会进入流媒体解锁，但新版本没有任何显示，重新订阅过几次，重启等方法试过均无法解决。

求解，谢谢。

**Comment by vernesong** [comment]
![image](https://user-images.githubusercontent.com/42875168/161423002-83f8ccf6-3b94-4ef0-b08d-38dd627fc234.png)

**Comment by hirintou** [comment]
> ![image](https://user-images.githubusercontent.com/42875168/161423002-83f8ccf6-3b94-4ef0-b08d-38dd627fc234.png)
> 
> 

解决了，谢谢大大

**Comment by gengleo** [comment]
路由本机代理具体有啥用呀

> ![image](https://user-images.githubusercontent.com/42875168/161423002-83f8ccf6-3b94-4ef0-b08d-38dd627fc234.png)
