### ISSUE TITLE
是否可以强制替换成clashr内核？

### ISSUE THREAD

**Issue by kl9800** [vernesong/OpenClash#222]
我喜欢openclash，但是我也需要ssr，
所以如果我想把clash替换成clashr的话，

1. 应该怎么干？
2. 能不能这么干？
3. 有何问题或者隐患吗？

谢谢！

**Comment by L0snight** [comment]
自行下载对应的clashr core，chmod 0755后上传到/etc/openclash

**Comment by kl9800** [comment]
好的我去试试

**Comment by VanDeAnna** [comment]
> 自行下载对应的clashr core，chmod 0755后上传到/etc/openclash

请教一下哪里能下载到适用于 OpenClash 的 ClashR 内核，我搜了一圈没有找到，先谢谢了

**Comment by wangfeng35** [comment]
> > 自行下载对应的clashr core，chmod 0755后上传到/etc/openclash
> 
> 请教一下哪里能下载到适用于 OpenClash 的 ClashR 内核，我搜了一圈没有找到，先谢谢了
> 
> 看了篇博客，找到了，https://github.com/frainzy1477/clashrdev/releases

补充另一个clashr内核：
https://github.com/BROBIRD/clash/releases

**Comment by tomagag** [comment]
nice,thanks
