### ISSUE TITLE
请问怎样实现指定设置指定线路?

### ISSUE THREAD

**Issue by anson2416** [vernesong/OpenClash#2222]
我使用的是机场,自带了很多分组: 国外流量, YouTu, Netflix等.

我想指定内网下一个手机永远只用一个**节点** (只是是节点, 不是分组). 请问可以实现吗?

下面的例子是访问blogger的时候, 使用 **分组** - 国外流量.
`- "DOMAIN-SUFFIX,blogger.com,\U0001F530国外流量"`

现在的需求返过来了. 我不知道怎样写. 谢谢.

**Comment by Mosney** [comment]
不知道就去看clash文档

**Comment by happy86755** [comment]
找到解决办法了没@anson2416
