### ISSUE TITLE
ruleset域名匹配规则不对导致gmail无法正常访问

### ISSUE THREAD

**Issue by tony1016** [vernesong/OpenClash#2225]
我在使用ruleset时，发现域名匹配的顺序不对。

我使用[这个项目](https://github.com/Loyalsoldier/clash-rules)的ruleset，其中mail.google.com属于proxy，mail-ads.google.com属于reject。
因为imail-ads.google.com，其解析地址和mail.bankcomm.com是一致的，似乎会导致redir时，该IP的访问被标记成了mail-ads.google.com

```
dig mail.google.com +short
googlemail.l.google.com.
216.58.195.69

dig mail-ads.google.com +short
googlemail.l.google.com.
216.58.195.69
```

理论上，我把proxy放在前面，reject放在后面，mail-ads.google.com会被proxy中的+.google.com代理，但是却匹配了reject
```
[TCP] 192.168.31.7:52365 --> mail-ads.google.com:443 match RuleSet(reject) using REJECT

```

**Comment by vernesong** [comment]
你看在配置文件中的位置

**Comment by tony1016** [comment]
> 你看在配置文件中的位置

位置肯定没有错啊
```
  - RULE-SET,proxy,PROXY
  - RULE-SET,reject,REJECT
  - RULE-SET,private,DIRECT
  - RULE-SET,lancidr,DIRECT
  - GEOIP,CN,DIRECT
  - DST-PORT,22,VIA-RELAY
  - MATCH,PROXY
```

其中proxy中包含了域名规则+.google.com，我觉得无论如何也不应该被reject啊

**Comment by vernesong** [comment]
那应该是内核的问题，可以去那边提问

**Comment by bash99** [comment]
> > 你看在配置文件中的位置
> 
> 我甚至把位置调成这样，但依然会被拦截
> 
> ```
>   - RULE-SET,proxy,PROXY
>   - RULE-SET,reject,REJECT
>   - RULE-SET,private,DIRECT
>   - RULE-SET,lancidr,DIRECT
>   - GEOIP,CN,DIRECT
>   - DST-PORT,22,VIA-RELAY
>   - MATCH,PROXY
> ```
> 
> 其中proxy中包含了域名规则+.google.com，我觉得无论如何也不应该被reject啊

我有碰到这个问题，最后在REJECT那行之前加上
  - DOMAIN,mail.google.com,PROXY
就解决了
