### ISSUE TITLE
is it process-name works properly?

### ISSUE THREAD

**Issue by malikshi** [vernesong/OpenClash#2227]
i have rule_Streaming with code something like this
```yaml
  # > Pandora
  - PROCESS-NAME,com.pandora.android
  - DOMAIN-SUFFIX,pandora.com
```

and rule_Gaming
```yaml
# > Apex Legends Mobile
  - DOMAIN-SUFFIX,tdm.mgapex.com
  - DOMAIN-SUFFIX,download.2.707369824.dmp.mgapex.com
  - DOMAIN-SUFFIX,bugly-android.mgapex.com
  - DOMAIN-SUFFIX,itop.mgapex.com
  - DOMAIN-SUFFIX,tgpa.mgapex.com
  - DOMAIN-SUFFIX,cloudctrl.mgapex.com
  - DOMAIN-SUFFIX,file.mgapex.com
  - DOMAIN-SUFFIX,ire.csoversea.mgapex.com
  - DOMAIN-SUFFIX,voice-sg.mgapex.com
  - DOMAIN-SUFFIX,pay.mgapex.com
  - DOMAIN-SUFFIX,lobby.mgapex.com
  - DOMAIN-SUFFIX,apex.go.sonobi.com
  - DOMAIN-SUFFIX,mgapex.com
  - DOMAIN-SUFFIX,devmgapex.com
  - DOMAIN-KEYWORD,mgapex
  - DOMAIN-KEYWORD,devmgapex
```
with the order rules:
- RULE-SET,rule_Streaming,Streaming
- RULE-SET,rule_Gaming,Gaming

yacd test: somehow domain `bugly-android.mgapex.com:443` would filtered in rule_Streaming not in rule_Gaming.
openclash > global setting> debug logs:  the result test of `domain bugly-android.mgapex.com:443` filtered in rule_Gaming

is it related to process-name filter?

**Comment by vernesong** [comment]
work for router-self only

**Comment by malikshi** [comment]
Tyvm for the answers. Just done reconfigure the rules, no error till now
