### ISSUE TITLE
Can't start after update to v0.36.9

### ISSUE THREAD

**Issue by Cyanogen-Mod** [vernesong/OpenClash#223]
Model: Xiaomi Mi Router 3G
Architecture: MediaTek MT7621 ver:1 eco:3
Firmware Version: OpenWrt 19.07.0 r10860-a3ffeb413b / LuCI openwrt-19.07 branch git-20.006.26738-35aa527
Kernel Version: 4.14.162

Core: clash-linux-mipsle-softfloat.tar.gz v0.18.0-13-g14d5137
Logs:
SIGILL: illegal instruction
PC=0x87fb4 m=3 sigcode=128

goroutine 1 [running]:
runtime.asyncPreempt()
	/usr/lib/go-1.14/src/runtime/preempt_mipsx.s:40 +0x7c fp=0xc93a24 sp=0xc93930 pc=0x87fb4
gopkg.in/yaml%2ev2.yaml_parser_update_buffer(0xc66000, 0x2, 0x15)
	/home/vernesong/go/pkg/mod/gopkg.in/yaml.v2@v2.2.8/readerc.go:349 +0x48c fp=0xc93a40 sp=0xc93a28 pc=0x3791c8
gopkg.in/yaml%2ev2.yaml_parser_scan_plain_scalar(0xc66000, 0xc93b7c, 0xc93b01)
	/home/vernesong/go/pkg/mod/gopkg.in/yaml.v2@v2.2.8/scannerc.go:2641 +0x2f8 fp=0xc93b6c sp=0xc93a40 pc=0x38a588
gopkg.in/yaml%2ev2.yaml_parser_fetch_plain_scalar(0xc66000, 0x201)
	/home/vernesong/go/pkg/mod/gopkg.in/yaml.v2@v2.2.8/scannerc.go:1435 +0x80 fp=0xc93bc4 sp=0xc93b6c pc=0x3802b8
gopkg.in/yaml%2ev2.yaml_parser_fetch_next_token(0xc66000, 0xc62060)
	/home/vernesong/go/pkg/mod/gopkg.in/yaml.v2@v2.2.8/scannerc.go:813 +0x510 fp=0xc93bf0 sp=0xc93bc4 pc=0x37ca1c
gopkg.in/yaml%2ev2.yaml_parser_fetch_more_tokens(0xc66000, 0xc66101)
	/home/vernesong/go/pkg/mod/gopkg.in/yaml.v2@v2.2.8/scannerc.go:642 +0x50 fp=0xc93c08 sp=0xc93bf0 pc=0x37c2a0
gopkg.in/yaml%2ev2.peek_token(...)
	/home/vernesong/go/pkg/mod/gopkg.in/yaml.v2@v2.2.8/parserc.go:47
gopkg.in/yaml%2ev2.yaml_parser_parse_indentless_sequence_entry(0xc66000, 0xc66108, 0x36adb0)
	/home/vernesong/go/pkg/mod/gopkg.in/yaml.v2@v2.2.8/parserc.go:640 +0x344 fp=0xc93cec sp=0xc93c08 pc=0x374fdc
gopkg.in/yaml%2ev2.yaml_parser_state_machine(0xc66000, 0xc66108, 0x501)
	/home/vernesong/go/pkg/mod/gopkg.in/yaml.v2@v2.2.8/parserc.go:128 +0x2a0 fp=0xc93d00 sp=0xc93cec pc=0x371a50
gopkg.in/yaml%2ev2.yaml_parser_parse(0xc66000, 0xc66108, 0xc2b501)
	/home/vernesong/go/pkg/mod/gopkg.in/yaml.v2@v2.2.8/parserc.go:72 +0xb4 fp=0xc93d10 sp=0xc93d00 pc=0x371778
gopkg.in/yaml%2ev2.(*parser).peek(0xc66000, 0xf22d80)
	/home/vernesong/go/pkg/mod/gopkg.in/yaml.v2@v2.2.8/decode.go:105 +0x54 fp=0xc93d20 sp=0xc93d10 pc=0x36a184
gopkg.in/yaml%2ev2.(*parser).sequence(0xc66000, 0xec7c07)
	/home/vernesong/go/pkg/mod/gopkg.in/yaml.v2@v2.2.8/decode.go:205 +0x9c fp=0xc93d54 sp=0xc93d20 pc=0x36ad90
gopkg.in/yaml%2ev2.(*parser).parse(0xc66000, 0xec7cc0)
	/home/vernesong/go/pkg/mod/gopkg.in/yaml.v2@v2.2.8/decode.go:151 +0x20c fp=0xc93d7c sp=0xc93d54 pc=0x36a600
gopkg.in/yaml%2ev2.(*parser).mapping(0xc66000, 0x9)
	/home/vernesong/go/pkg/mod/gopkg.in/yaml.v2@v2.2.8/decode.go:217 +0xd4 fp=0xc93db4 sp=0xc93d7c pc=0x36b024
gopkg.in/yaml%2ev2.(*parser).parse(0xc66000, 0xc50203)
	/home/vernesong/go/pkg/mod/gopkg.in/yaml.v2@v2.2.8/decode.go:149 +0x1e4 fp=0xc93ddc sp=0xc93db4 pc=0x36a5d8
gopkg.in/yaml%2ev2.(*parser).document(0xc66000, 0x3)
	/home/vernesong/go/pkg/mod/gopkg.in/yaml.v2@v2.2.8/decode.go:175 +0xb4 fp=0xc93e0c sp=0xc93ddc pc=0x36a780
gopkg.in/yaml%2ev2.(*parser).parse(0xc66000, 0x0)
	/home/vernesong/go/pkg/mod/gopkg.in/yaml.v2@v2.2.8/decode.go:153 +0x180 fp=0xc93e34 sp=0xc93e0c pc=0x36a574
gopkg.in/yaml%2ev2.unmarshal(0xd80000, 0x662a6, 0x664a6, 0x4701c0, 0xc0c018, 0x431b00, 0x0, 0x0)
	/home/vernesong/go/pkg/mod/gopkg.in/yaml.v2@v2.2.8/yaml.go:142 +0x22c fp=0xc93e84 sp=0xc93e34 pc=0x38b7a4
gopkg.in/yaml%2ev2.Unmarshal(...)
	/home/vernesong/go/pkg/mod/gopkg.in/yaml.v2@v2.2.8/yaml.go:81
github.com/Dreamacro/clash/config.UnmarshalRawConfig(0xd80000, 0x662a6, 0x664a6, 0x0, 0xc9ad20, 0x4de230)
	/home/vernesong/home/clash/config/config.go:168 +0x278 fp=0xc93eb0 sp=0xc93e84 pc=0x423b94
github.com/Dreamacro/clash/config.Parse(0xd80000, 0x662a6, 0x664a6, 0x662a6, 0x664a6, 0x0)
	/home/vernesong/home/clash/config/config.go:126 +0x4c fp=0xc93ecc sp=0xc93eb0 pc=0x4238b8
github.com/Dreamacro/clash/hub/executor.ParseWithBytes(...)
	/home/vernesong/home/clash/hub/executor/executor.go:75
github.com/Dreamacro/clash/hub/executor.ParseWithPath(0x7f8eeafe, 0x25, 0xc, 0x9d44500, 0x1080a4)
	/home/vernesong/home/clash/hub/executor/executor.go:70 +0x90 fp=0xc93eec sp=0xc93ecc pc=0x431b70
github.com/Dreamacro/clash/hub/executor.Parse(...)
	/home/vernesong/home/clash/hub/executor/executor.go:60
github.com/Dreamacro/clash/hub.Parse(0x7f8eeaec, 0xe)
	/home/vernesong/home/clash/hub/hub.go:10 +0x50 fp=0xc93f0c sp=0xc93eec pc=0x44b3dc
main.main()
	/home/vernesong/home/clash/main.go:74 +0x2e4 fp=0xc93fc0 sp=0xc93f0c pc=0x44ba4c
runtime.main()
	/usr/lib/go-1.14/src/runtime/proc.go:203 +0x284 fp=0xc93fec sp=0xc93fc0 pc=0x4f9ec
runtime.goexit()
	/usr/lib/go-1.14/src/runtime/asm_mipsx.s:651 +0x4 fp=0xc93fec sp=0xc93fec pc=0x87834

goroutine 18 [chan receive]:
github.com/Dreamacro/clash/common/observable.(*Observable).process(0xc98aa0)
	/home/vernesong/home/clash/common/observable/observable.go:16 +0xe4
created by github.com/Dreamacro/clash/common/observable.NewObservable
	/home/vernesong/home/clash/common/observable/observable.go:63 +0xa4

goroutine 19 [select]:
gopkg.in/eapache/channels%2ev1.(*InfiniteChannel).infiniteBuffer(0xca21f0)
	/home/vernesong/go/pkg/mod/gopkg.in/eapache/channels.v1@v1.1.0/infinite_channel.go:49 +0x120
created by gopkg.in/eapache/channels%2ev1.NewInfiniteChannel
	/home/vernesong/go/pkg/mod/gopkg.in/eapache/channels.v1@v1.1.0/infinite_channel.go:19 +0x160

goroutine 20 [select]:
gopkg.in/eapache/channels%2ev1.(*InfiniteChannel).infiniteBuffer(0xca2200)
	/home/vernesong/go/pkg/mod/gopkg.in/eapache/channels.v1@v1.1.0/infinite_channel.go:49 +0x120
created by gopkg.in/eapache/channels%2ev1.NewInfiniteChannel
	/home/vernesong/go/pkg/mod/gopkg.in/eapache/channels.v1@v1.1.0/infinite_channel.go:19 +0x160

goroutine 21 [select]:
github.com/Dreamacro/clash/tunnel.(*Manager).handleCh(0xcca280, 0xc94280, 0xcca2a0, 0xcca2b0, 0xcca2c0)
	/home/vernesong/home/clash/tunnel/manager.go:81 +0xd4
created by github.com/Dreamacro/clash/tunnel.(*Manager).handle
	/home/vernesong/home/clash/tunnel/manager.go:74 +0x70

goroutine 22 [select]:
github.com/Dreamacro/clash/tunnel.(*Manager).handleCh(0xcca280, 0xc942c0, 0xcca2a8, 0xcca2b8, 0xcca2c8)
	/home/vernesong/home/clash/tunnel/manager.go:81 +0xd4
created by github.com/Dreamacro/clash/tunnel.(*Manager).handle
	/home/vernesong/home/clash/tunnel/manager.go:75 +0xb4

goroutine 23 [chan receive]:
github.com/Dreamacro/clash/tunnel.process()
	/home/vernesong/home/clash/tunnel/tunnel.go:126 +0x118
created by github.com/Dreamacro/clash/tunnel.init.1
	/home/vernesong/home/clash/tunnel/tunnel.go:42 +0x44

goroutine 24 [chan receive]:
github.com/Dreamacro/clash/tunnel.processUDP()
	/home/vernesong/home/clash/tunnel/tunnel.go:110 +0x70
created by github.com/Dreamacro/clash/tunnel.process
	/home/vernesong/home/clash/tunnel/tunnel.go:122 +0x70

goroutine 25 [chan receive]:
github.com/Dreamacro/clash/tunnel.processUDP()
	/home/vernesong/home/clash/tunnel/tunnel.go:110 +0x70
created by github.com/Dreamacro/clash/tunnel.process
	/home/vernesong/home/clash/tunnel/tunnel.go:122 +0x70

goroutine 26 [chan receive]:
github.com/Dreamacro/clash/tunnel.processUDP()
	/home/vernesong/home/clash/tunnel/tunnel.go:110 +0x70
created by github.com/Dreamacro/clash/tunnel.process
	/home/vernesong/home/clash/tunnel/tunnel.go:122 +0x70

goroutine 27 [chan receive]:
github.com/Dreamacro/clash/tunnel.processUDP()
	/home/vernesong/home/clash/tunnel/tunnel.go:110 +0x70
created by github.com/Dreamacro/clash/tunnel.process
	/home/vernesong/home/clash/tunnel/tunnel.go:122 +0x70

r0   0x0	r1   0x10
r2   0x200	r3   0x1
r4   0xc66000	r5   0x113
r6   0x2	r7   0xdfff
r8   0x2d	r9   0x10ffff
r10  0x20	r11  0xc6a112
r12  0x1	r13  0x2d0a6b63
r14  0x4d4f4420	r15  0x2d4e4941
r16  0x0	r17  0x0
r18  0x0	r19  0x0
r20  0x0	r21  0x0
r22  0x52cc10	r23  0xd800
r24  0x9cb	r25  0x2
r26  0x0	r27  0x0
r28  0xc161f8	r29  0xc93930
r30  0xc000e0	r31  0x3791c8
pc   0x87fb4	link 0x3791c8
lo   0x0	hi   0x0
2020-03-10 19:42:23 OpenClash Can Not Start, Please Check The Error Info And Try Again

**Comment by vernesong** [comment]
此问题建议向内核开发者提出 https://github.com/Dreamacro/clash/tree/dev

**Comment by Cyanogen-Mod** [comment]
好的 谢谢啦

**Comment by vernesong** [comment]
https://github.com/Dreamacro/clash/issues/576

**Comment by Neubulae** [comment]
https://github.com/golang/go/issues/37667
