### ISSUE TITLE
如何在fakeip模式下进行DNS重写

### ISSUE THREAD

**Issue by MURChen** [vernesong/OpenClash#2231]
这可能是一个比较肤浅的问题
我目前使用adguardhome（53端口，dns指向openclash）也就是#1420的配置
我查看了文档，似乎adguardhome里的DNS重写不能使用
在openclash 倒是有个自定义hosts，但好像只能在redir-host下使用
找了issue和文档都没有说明，不知道如何实现

例如：我想将 assets1.xboxlive.cn 这个域名指向 115.231.77.219 
这个是将微软商店的地址指向国内CDN的位置，我并不想仅仅使用设备上的hosts来修改，有点麻烦

使用openwrt上的hosts不知道能不能生效

**Comment by paladin4fan** [comment]
![image](https://user-images.githubusercontent.com/34474436/161889749-eb040393-e6e8-45cc-9542-99b4f79cf1f6.png)

**Comment by chinesepyanyue** [comment]
我的adguardhome 配置的是“作为dnsmasq的上游服务器”，这样我只要在dnsmasq里面自定义挟持域名就可以了。
fake-ip那个黑名单我搞过几次，有点不太搞得明白。对于我这样的小白用户，还是dnsmasq这种简单的适合我。
![image](https://user-images.githubusercontent.com/14289912/162145582-1d6e0024-28c4-4d3a-8460-3801af884159.png)
