### ISSUE TITLE
当前最新版本 0.44.42 内核报错 导致自定义规则不能加入到运行配置文件中

### ISSUE THREAD

**Issue by matthuo333** [vernesong/OpenClash#2233]
具体报错如下：

OpenClash 启动失败：
Parse config error:rules[0][SRC-IP-CIDR,/32,DIRECT] error:payload error

回滚到 v0.44.34 则没问题。

是不是新版本对于配置yaml 语法规则有变化？ 但是基本将所有规则拿掉，仍然提示报错。

**Comment by vernesong** [comment]
lan ip获取失败了，你什么固件

**Comment by matthuo333** [comment]
> lan ip获取失败了，你什么固件

OpenWrt R20.10.20

**Comment by vernesong** [comment]
```
ip address show $(uci -q -p /tmp/state get network.lan.ifname) | grep -w "inet" | awk '{print $2}'
```
试试

**Comment by matthuo333** [comment]
环境没了，明上午试哈

**Comment by LagunAPaTa** [comment]
同样的问题
ip address show $(uci -q -p /tmp/state get network.lan.ifname) | grep -w "inet" | awk '{print $2}'可以获取到IP地址

**Comment by LagunAPaTa** [comment]
当前固件
 ImmortalWrt 18.06-5.4-SNAPSHOT r11867-398ea52770 (2022-04-06)
