### ISSUE TITLE
openclash 连接不显示域名 导致有很多国内的下载用了代理

### ISSUE THREAD

**Issue by liyuxu0405** [vernesong/OpenClash#2236]
- ### 我是用的旁路由，但是clash显示不正常，域名被解析成IP显示出来，导致自己加入的域名规则不生效 
![image](https://user-images.githubusercontent.com/75111830/162131334-6e61c5e7-8a5a-4ae1-9569-63dcae9f67a4.png)

**Comment by vernesong** [comment]
![image](https://user-images.githubusercontent.com/42875168/162135815-ac1fedc6-3439-4ed5-8b48-4d66b949184f.png)

**Comment by liyuxu0405** [comment]
好的 已经解决了   是我的SMARTDNS 的原因，我把clash开启了本地DNS劫持后 已经恢复正常
![image](https://user-images.githubusercontent.com/75111830/162147110-8df98a19-0f9a-404e-aea4-4485ab1f2269.png)

**Comment by MBRjun** [comment]
提示: 可以关闭Issue了
