### ISSUE TITLE
在appletv上使用iplaytv看m3u格式直播电视很卡怎么回事？

### ISSUE THREAD

**Issue by cicai1631** [vernesong/OpenClash#2238]
使用redir-host（兼容）模式，ACL4SSR 规则 Online Full模板

规则
国外媒体：自动选择

主要是看国外的电视很卡，或者根本打不开。但是这个资源是可用的，别人播放流畅。
节点足够多。
有什么解决办法，或者建议？

**Comment by vernesong** [comment]
换节点啊

**Comment by cicai1631** [comment]
> 
手动还是自动换啊？
切换模式能完美解决问题吗？

**Comment by cicai1631** [comment]
> 节点手动切

好吧，先试试
