### ISSUE TITLE
莫名出现source和destination都是本机ip：7892端口的连接，连接数暴涨至15000+

### ISSUE THREAD

**Issue by YukawaMi** [vernesong/OpenClash#224]
问题原因不明，用了openclash也好久了，之前一直正常，今天突然感觉网速很慢，进web页面查看，管理界面都加载了半天，然后发现都是openclash机器的ip：7892自己访问自己，一眼看去连接都是这个，然后进openwrt的web界面看连接数突破15000,平时正常的连接数只有几百
关闭openclah也没用，直接就把openwrt重启了，重启后正常，暂未复现问题，不知道和最新版的openclash有没有关系，
模式是redir模式，未开udp转发

**Comment by vernesong** [comment]
redir模式下路由自身的流量回环应该不会产生，这个问题的原因还有待观察

**Comment by YukawaMi** [comment]
https://github.com/Dreamacro/clash/issues/425#issue-535499586

看描述应该是同一个问题，上游跟进了
