### ISSUE TITLE
控制面板支持 https

### ISSUE THREAD

**Issue by MBRjun** [vernesong/OpenClash#2246]
![Snipaste_2022-04-09_23-25-36](https://user-images.githubusercontent.com/55020690/162580559-d752d048-5493-4cf9-b4d6-d77f517f5e9c.png)
请求加入个 https 支持，不然 yacd 无法正常使用）

**Comment by 1nfsr** [comment]
自己反代一下就好了

**Comment by MBRjun** [comment]
> 自己反代一下就好了

很好的办法

**Comment by liangyi9812** [comment]
> > 自己反代一下就好了
> 
> 很好的办法

我最近也碰到了这个问题,能分享下反代的配置吗🥰
