### ISSUE TITLE
tun 模式不能改 mtu 开巨帧

### ISSUE THREAD

**Issue by gyhmz** [vernesong/OpenClash#2247]
如题，tun模式开了巨帧（mtu=9000）后不能联网

**Comment by vernesong** [comment]
具体操作和使用场景？

**Comment by gyhmz** [comment]
电脑打开巨帧，openwrt终端 ifconfig eth4 mtu9000 （电脑连eth4），tun模式下浏览器打开baidu.com google.com 都完全没反应，然后过会显示超时，ping倒是可以ping通

**Comment by BlueBenson** [comment]
我也遇到同样情况，Redir-Host Tun模式不行，Redir-Host 混合模式可以。Mac系统

**Comment by vernesong** [comment]
https://release.dreamacro.workers.dev/
latest

**Comment by geek981108** [comment]
同样遇到这个问题, 通过curl发现开启mtu9000后, curl https 卡在 
![image](https://github.com/vernesong/OpenClash/assets/28996049/f769d0f4-e9de-405c-b645-6051a05b3032)
