### ISSUE TITLE
出现503错误？

### ISSUE THREAD

**Issue by wolnlow** [vernesong/OpenClash#225]
在日志里出现以下503大量错误，导致连接不上，线路是正常，用其他代理使用完全没有问题，将域名换成ip地址则出现403错误，目前Fake-IP增强模式，DNS设置，本次dns劫持启用，自定义上游dns服务器启用，默认启用自带的前面2个dns地址，ipv6类型dns解析停用，禁止dnsmasq缓存启用，高级设置停用或启用都不行。
2020-03-11 15:26:32[warning] dial Others error: Dial wh4.123cdn.xyz error: 530
2020-03-11 15:26:34[warning] dial Proxy error: Dial wh4.123cdn.xyz error: 530

**Comment by vernesong** [comment]
Fake-IP下会把需要代理的流量发给服务器解析，这种问题很可能是服务端造成的。
你可以试试直连这个域名

**Comment by wolnlow** [comment]
> 
> 
> Fake-IP下会把需要代理的流量发给服务器解析，这种问题很可能是服务端造成的。
> 你可以试试直连这个域名

通过在线ping工具，获得该域名ip后，将代理节点中域名修改为ip地址，后提出403错误
[warning] dial Proxy error: Dial 122.190.3.42 error: 403 Forbidden
[warning] dial Proxy error: Dial 122.190.3.42 error: 403 Forbidden

**Comment by vernesong** [comment]
你现在还是走代理。添加自定义规则：
```
- DOMAIN-SUFFIX,123cdn.xyz,DIRECT
```

**Comment by wolnlow** [comment]
> 
> 
> 你现在还是走代理。添加自定义规则：
> 
> ```
> - DOMAIN-SUFFIX,123cdn.xyz,DIRECT
> ```

设定自定义规则里面将123cd.xyz设为直接连接，依然提醒503错误，看来服务端可能有问题！
