### ISSUE TITLE
Redir 在规则配置后仍重定向IANA 保留地址

### ISSUE THREAD

**Issue by mengzhuo** [vernesong/OpenClash#2251]
198.18.0.0/15

https://datatracker.ietf.org/doc/html/rfc6890

这些地址均是IANA保留地址，不应该重定向，但是就算我配置了第三方设置如下
```
rules:
- IP-CIDR,198.18.0.0/16,REJECT
- IP-CIDR6,2001:2::/48,REJECT
- MATCH,auto
```
仍然会被重定向至服务器，而不是直接拒绝

**Comment by vernesong** [comment]
对应的日志显示什么
