### ISSUE TITLE
可以添加icmp劫持功能吗？

### ISSUE THREAD

**Issue by fengyang0317** [vernesong/OpenClash#2252]
看passwall上面有，加上这个功能可以ping和mtr了。

**Comment by MBRjun** [comment]
你想要做成啥样 ICMP包都是路由器回复吗

**Comment by fengyang0317** [comment]
之前以为可以劫持成通过代理测延迟。
今天试了一下passwall里的icmp劫持，是路由器回复，这个没啥用。
