### ISSUE TITLE
0.44.42偶尔无限崩溃，需要重启设备解决

### ISSUE THREAD

**Issue by 296475202** [vernesong/OpenClash#2253]
![B6529A5D-97F4-44C9-84F1-A720D09F0885](https://user-images.githubusercontent.com/37367487/162865047-d5c60b9b-9084-4340-a59a-953964242005.jpeg)
![F7F96E1D-74D0-4A9E-8730-75CF36675A08](https://user-images.githubusercontent.com/37367487/162865057-0bbc7a5d-8a3e-47bc-b760-cfb8b8152152.jpeg)
![226C553C-37A2-4B69-93D9-870CFC11BEAE](https://user-images.githubusercontent.com/37367487/162865071-6a5e2bef-5b92-49e3-83d1-b24ec6205610.png)
![86C1F625-8DC9-49BB-AACE-A4325093031D](https://user-images.githubusercontent.com/37367487/162865076-73cd1718-4dc9-4305-8db1-74f5869a6ce4.png)

**Comment by vernesong** [comment]
不是连续的崩溃没办法检测停止重启
