### ISSUE TITLE
[TUN] 当前内核版本“未知”

### ISSUE THREAD

**Issue by bauw2008** [vernesong/OpenClash#2254]
![屏幕截图 2022-04-12 121546](https://user-images.githubusercontent.com/77882800/162879687-e4300d20-029d-497a-96fd-d3883f0eb5ed.jpg)
![未知截图](https://user-images.githubusercontent.com/77882800/162879692-cd024c10-c435-4264-bb4e-7feb1c7f23c3.jpg)

#===================== 依赖检查 =====================#

dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
iptables-mod-tproxy: 已安装
kmod-ipt-tproxy: 已安装
iptables-mod-extra: 已安装
kmod-ipt-extra: 已安装
libcap: 已安装
libcap-bin: 已安装
ruby: 已安装
ruby-yaml: 已安装
ruby-psych: 已安装
ruby-pstore: 已安装
ruby-dbm: 已安装
kmod-tun(TUN模式): 已安装
luci-compat(Luci-19.07): 已安装
kmod-inet-diag(PROCESS-NAME): 已安装

#===================== 内核检查 =====================#

运行状态: 运行中
进程pid: 17847
运行权限: 17847: cap_dac_override,cap_net_bind_service,cap_net_admin,cap_net_raw,cap_sys_ptrace,cap_sys_resource=eip
运行用户: nobody
已选择的架构: linux-amd64

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 
Tun内核文件: 存在
Tun内核运行权限: 正常

Dev内核版本: v1.10.0
Dev内核文件: 存在
Dev内核运行权限: 正常

 OpenWrt SNAPSHOT, r19422-aece8f5ae8
 -----------------------------------------------------
root@OpenWrt:~#  /etc/openclash/core/clash -v
Clash v1.10.0 linux amd64 with go1.18 2022年 03月 19日 星期六 08:31:21 UTC
root@OpenWrt:~#   /etc/openclash/core/clash_tun -v
Clash 2022.03.21 linux amd64 with go1.18 Mon Mar 21 11:52:40 UTC 2022
root@OpenWrt:~# 

换过版本编译，都是显示tun内核未知，能正常使用。

**Comment by vernesong** [comment]
重下

**Comment by bauw2008** [comment]
感谢大佬回复，手动上传改权限或者检查更新结果都是tun未知，换过其他内核版本结果一样。

**Comment by vernesong** [comment]
https://github.com/Dreamacro/clash/releases/tag/premium

**Comment by bauw2008** [comment]
编译不添加bypass或vssr解决这问题。
