### ISSUE TITLE
github网页上的图片打不开有没有人同样的问题

### ISSUE THREAD

**Issue by rockmetalcn** [vernesong/OpenClash#2255]
openwrt openclash 使用正常 只遇到一个小问题 强迫症实在受不了 github中的图片都显示一个小的图片碎片图标 查了一下是raw.githubusercontent.com这个域名解析不了 请教各位如何解决 谢谢！！
openwrt里面nslookup：

Server:		127.0.0.1
Address:	127.0.0.1#53

Name:      raw.githubusercontent.com
Address 1: 0.0.0.0
*** Can't find raw.githubusercontent.com: No answer

**Comment by rockmetalcn** [comment]
> hosts

查了一下 就是改成下面这个例子 还是手动查到ip添加进去 
hosts:                            
   '*.clash.dev': 127.0.0.1 
   'alpha.clash.dev': ::1

**Comment by vernesong** [comment]
你电脑上的

**Comment by rockmetalcn** [comment]
> 你电脑上的

我那个nslookup结果是在openwrt上查的 是应该在软路由里面修改吧 不太明白

**Comment by zhangguanzhang** [comment]
dns的最终请求外网全部走 dns over http试下，防止呗劫持

**Comment by rockmetalcn** [comment]
> dns的最终请求外网全部走 dns over http试下，防止呗劫持

感谢回答 具体怎么设置呢

**Comment by rockmetalcn** [comment]
![image](https://user-images.githubusercontent.com/74691164/163081743-e4b94472-c90a-409c-8580-f511273d8275.png)

按理说这是openclash里面有的设置啊

**Comment by loohalh** [comment]
图片不能打开，你试试google和YouTube.com播放视频正常吗

**Comment by rockmetalcn** [comment]
> 图片不能打开，你试试google和YouTube.com播放视频正常吗

其他都正常就这一个小问题 现在我按照大佬回复修改了电脑hosts文件 添加199.232.96.133 raw.githubusercontent.com记录已解决
![image](https://user-images.githubusercontent.com/74691164/163085567-019f5dd1-56cd-4079-a3c0-c90ba2a5d391.png)
但是在软路由上还是没有完全解决 只是电脑本地进行了这么一个本地查询 比如iPhone没有hosts记录还是打不开 或者说以后有类似的网站都需要添加电脑上的记录不算根本解决办法吧

**Comment by rockmetalcn** [comment]
> > 图片不能打开，你试试google和YouTube.com播放视频正常吗
> 
> 其他都正常就这一个小问题 现在我按照大佬回复修改了电脑hosts文件 添加199.232.96.133 raw.githubusercontent.com记录已解决 ![image](https://user-images.githubusercontent.com/74691164/163085567-019f5dd1-56cd-4079-a3c0-c90ba2a5d391.png) 但是在软路由上还是没有完全解决 只是电脑本地进行了这么一个本地查询 比如iPhone没有hosts记录还是打不开 或者说以后有类似的网站都需要添加电脑上的记录不算根本解决办法吧

电脑虽然能打开 nslookup如下图
![image](https://user-images.githubusercontent.com/74691164/163085950-0e78c159-479f-413f-be70-e438c6a960e9.png)

**Comment by loohalh** [comment]
我之前的问题是raw.githubusercontent.com打不开，google.com异常，YouTube.com网站能打开，视频不能播放，最后是ipv6解析的问题，已解决

**Comment by rockmetalcn** [comment]
> 我之前的问题是raw.githubusercontent.com打不开，google.com异常，YouTube.com网站能打开，视频不能播放，最后是ipv6解析的问题，已解决

我目前测试只有raw图片打不开这一个小问题 google是正常的 软路由ipv6全关了 你是怎么发现ipv6解析的 还是说这个网址优先走了ipv6解析？。

**Comment by rockmetalcn** [comment]
> > 我之前的问题是raw.githubusercontent.com打不开，google.com异常，YouTube.com网站能打开，视频不能播放，最后是ipv6解析的问题，已解决
> 
> 我目前测试只有raw图片打不开这一个小问题 google是正常的 软路由ipv6全关了 你是怎么发现ipv6解析的 还是说这个网址优先走了ipv6解析？。

**Comment by rockmetalcn** [comment]
> > > 我之前的问题是raw.githubusercontent.com打不开，google.com异常，YouTube.com网站能打开，视频不能播放，最后是ipv6解析的问题，已解决
> > 
> > 
> > 我目前测试只有raw图片打不开这一个小问题 google是正常的 软路由ipv6全关了 你是怎么发现ipv6解析的 还是说这个网址优先走了ipv6解析？。

最新进展：删除电脑hosts文件记录 在openclash添加：
![image](https://user-images.githubusercontent.com/74691164/163088460-31435746-4485-455c-a801-b94f5faa1232.png)
openwrt上nslookup 
![image](https://user-images.githubusercontent.com/74691164/163088553-1ed118ce-7c5d-4ec9-937f-070ae650d3e0.png)
电脑nslookup
![image](https://user-images.githubusercontent.com/74691164/163088593-f5c928da-dffd-4ff9-8ee2-3610926c98b7.png)
好像是上面那位兄弟说的ipv6解析问题 不过还是不知道怎么修改

**Comment by rockmetalcn** [comment]
> > > > 我之前的问题是raw.githubusercontent.com打不开，google.com异常，YouTube.com网站能打开，视频不能播放，最后是ipv6解析的问题，已解决
> > > 
> > > 
> > > 我目前测试只有raw图片打不开这一个小问题 google是正常的 软路由ipv6全关了 你是怎么发现ipv6解析的 还是说这个网址优先走了ipv6解析？。
> 
> 最新进展：删除电脑hosts文件记录 在openclash添加： ![image](https://user-images.githubusercontent.com/74691164/163088460-31435746-4485-455c-a801-b94f5faa1232.png) openwrt上nslookup ![image](https://user-images.githubusercontent.com/74691164/163088553-1ed118ce-7c5d-4ec9-937f-070ae650d3e0.png) 电脑nslookup ![image](https://user-images.githubusercontent.com/74691164/163088593-f5c928da-dffd-4ff9-8ee2-3610926c98b7.png) 好像是上面那位兄弟说的ipv6解析问题 不过还是不知道怎么修改

已解决：删除了openclash里的host记录
![image](https://user-images.githubusercontent.com/74691164/163089293-9a54b0b9-6099-4a1c-bd0d-5f3a35defe11.png)
把上面这个开关重新打上勾，之前也是选上的，感觉是bug没生效，刚才重新选一次 重启软路由 问题解决。

**Comment by loohalh** [comment]
> > > > 我之前的问题是raw.githubusercontent.com打不开，google.com异常，YouTube.com网站能打开，视频不能播放，最后是ipv6解析的问题，已解决
> > > 
> > > 
> > > 我目前测试只有raw图片打不开这一个小问题 google是正常的 软路由ipv6全关了 你是怎么发现ipv6解析的 还是说这个网址优先走了ipv6解析？。
> 
> 最新进展：删除电脑hosts文件记录 在openclash添加： ![image](https://user-images.githubusercontent.com/74691164/163088460-31435746-4485-455c-a801-b94f5faa1232.png) openwrt上nslookup ![image](https://user-images.githubusercontent.com/74691164/163088553-1ed118ce-7c5d-4ec9-937f-070ae650d3e0.png) 电脑nslookup ![image](https://user-images.githubusercontent.com/74691164/163088593-f5c928da-dffd-4ff9-8ee2-3610926c98b7.png) 好像是上面那位兄弟说的ipv6解析问题 不过还是不知道怎么修改

查看[#2232](https://github.com/vernesong/OpenClash/issues/2232)，这个是我最后的解决方案

**Comment by loohalh** [comment]
> > > > > 我之前的问题是raw.githubusercontent.com打不开，google.com异常，YouTube.com网站能打开，视频不能播放，最后是ipv6解析的问题，已解决
> > > > 
> > > > 
> > > > 我目前测试只有raw图片打不开这一个小问题 google是正常的 软路由ipv6全关了 你是怎么发现ipv6解析的 还是说这个网址优先走了ipv6解析？。
> > 
> > 
> > 最新进展：删除电脑hosts文件记录 在openclash添加： ![image](https://user-images.githubusercontent.com/74691164/163088460-31435746-4485-455c-a801-b94f5faa1232.png) openwrt上nslookup ![image](https://user-images.githubusercontent.com/74691164/163088553-1ed118ce-7c5d-4ec9-937f-070ae650d3e0.png) 电脑nslookup ![image](https://user-images.githubusercontent.com/74691164/163088593-f5c928da-dffd-4ff9-8ee2-3610926c98b7.png) 好像是上面那位兄弟说的ipv6解析问题 不过还是不知道怎么修改
> 
> 查看[#2232](https://github.com/vernesong/OpenClash/issues/2232)，这个是我最后的解决方案
要么完全关闭ipv6，要么要让ipv6的到正确的解析和转发

**Comment by geniussar** [comment]
同样的问题，试过多个方法，还搭建了两个AGH，一个国内一个国外，都不行。
偶然发现了是IPv6的DNS问题，最后在openwrt的IPv6的DNS，手动指定了google的2001:4860:4860::8888解决。
