### ISSUE TITLE
请教大大，怎么设置绕过来自某个端口的流量，比如5900这样的vnc远程接口

### ISSUE THREAD

**Issue by loohalh** [vernesong/OpenClash#2258]
请教大大，怎么设置绕过来自某个端口的流量，比如5900这样的vnc远程接口，开启openclash后远程桌面连接无法使用了

**Comment by WhoJave** [comment]
DST-PORT,5900,DIRECT
@loohalh 
建议看看文档再提issue
https://lancellc.gitbook.io/clash/clash-config-file/rules/miscellaneous-rule

**Comment by loohalh** [comment]
> DST-PORT,5900,DIRECT
> @loohalh
> 建议看看文档再提issue
> https://lancellc.gitbook.io/clash/clash-config-file/rules/miscellaneous-rule
请问大佬，这个往那儿填，这方面是小白

**Comment by a76yyyy** [comment]
<img width="657" alt="" src="https://user-images.githubusercontent.com/56478790/163129686-d05ddb76-e050-4bf3-ad37-3d702c636f0b.png">

**Comment by FrodoTTK** [comment]
我遇到的问题是开了OpenClash无法通过公网IP连接RDP到PC，iptables添加这两条规则就可以了：
root@OpenWrt:~# iptables -t nat -I openclash -s 192.168.1.123/32 -p tcp -m multiport --dports 3389 -j RETURN
root@OpenWrt:~# iptables -t nat -I openclash -s 192.168.1.123/32 -p tcp -m multiport --sports 3389 -j RETURN
