### ISSUE TITLE
 v0.45.02-beta 启动成功但是不能科学上网，求助大佬

### ISSUE THREAD

**Issue by fengfan0820** [vernesong/OpenClash#2260]
openwrt   内核版本  5.10.96    5.15.33  都是相同情况，求助大佬  感谢  感谢
![image](https://user-images.githubusercontent.com/52518332/163114870-48cd03b5-5cd3-42dc-81bb-412f0ed3b38f.png)

订阅使用了默认的转换模板  订阅信息显示无订阅信息
![image](https://user-images.githubusercontent.com/52518332/163115211-143a797a-9483-4f8d-af43-8492700acf43.png)

网站访问检查  YouTube 不通过
![image](https://user-images.githubusercontent.com/52518332/163115390-26193fdb-bfd3-4a7c-9cc4-566386b2e09e.png)

日志
![image](https://user-images.githubusercontent.com/52518332/163115496-947fc8a1-0f38-42d7-b65c-f503152a8c27.png)

**Comment by yhl452493373** [comment]
你是自己编译的吗？

openwrt22.03或者更新，使用了firewall4，由原来的iptables变成了nftables，openclash不兼容nftables。编译的时候配置下

https://github.com/vernesong/OpenClash/issues/2248

**Comment by fengfan0820** [comment]
> 你是自己编译的吗？
> 
> openwrt22.03或者更新，使用了firewall4，由原来的iptables变成了nftables，openclash不兼容nftables。编译的时候配置下
> 
> #2248

谢谢大佬
我是自己编译的，内核版本5.15.33，源码来自coolsnowwolf/lede，iptables有安装，我目前在openclash  DNS设置中选择本地DNS劫持可以正常使用，选择自定义上游DNS服务器 国内可以访问，国外不行，应该是DNS的问题
![image](https://user-images.githubusercontent.com/52518332/163152964-c373296d-4aee-4b16-b9f1-25d8472b41a4.png)

上游DNS如下
![image](https://user-images.githubusercontent.com/52518332/163153231-e74ff71f-836e-465c-8623-3590fa57267d.png)

![image](https://user-images.githubusercontent.com/52518332/163153385-cd55cd47-3a04-4d33-b290-c5186a6f7851.png)

![image](https://user-images.githubusercontent.com/52518332/163153487-4b8c23a3-7a9a-4c8c-b34f-5d6ee61300ed.png)

**Comment by fengfan0820** [comment]
好像我配置有问题，打扰了，抱歉抱歉，现在DNS设置中选择自定义上游DNS服务器配合adguardhome可以正常使用。感谢感谢

**Comment by AlasJiahui** [comment]
请问你是怎么解决的啊

**Comment by fengfan0820** [comment]
> 请问你是怎么解决的啊

我之前使用的内核版本是5.10.96
配置为：

> 启动adguardhome，adguardhome上游DNS 服务器 127.0.0.1:7874
> openclash DNS设置中**不勾选本地DNS劫持**，**勾选自定义上游DNS服务器**
> 
> openclash 升级后国内访问没问题，国外无法访问。

然后我重新编译了，内核版本是5.15.33
配置为：

- 配置1
> adguardhome**未运行**
> openclash DNS设置中**不勾选本地DNS劫持**，**勾选自定义上游DNS服务器**
国内访问没问题，国外无法访问

- 配置2
> adguardhome**未运行**
> openclash DNS设置中**勾选本地DNS劫持**，**不勾选自定义上游DNS服务器**
内外网络正常

- 配置3  是我现在使用的配置
> 启动adguardhome，adguardhome上游DNS 服务器 127.0.0.1:7874
> openclash DNS设置中**不勾选本地DNS劫持**，**勾选自定义上游DNS服务器**
内外网络正常

希望对你有帮助

**Comment by AlasJiahui** [comment]
> 

谢谢，我试了还是有点问题，我还是继续使用旧版本吧
