### ISSUE TITLE
各位谁知道为什么一开启就99+的连接数，造成网络拥堵。

### ISSUE THREAD

**Issue by tonyzzt001** [vernesong/OpenClash#2265]
![error](https://user-images.githubusercontent.com/58526448/163186740-66ee761d-d13c-48dd-bbee-fd05e4a74b58.png)

**Comment by vernesong** [comment]
这是你自己的连接吗

**Comment by littleneko** [comment]
这来源ip是你自己吗？查了下 ip 归属地是 荷兰北荷兰省阿姆斯特丹

**Comment by ppyohhh** [comment]
设置延迟启动20s  我也有过这个问题。 延迟启动就好了

**Comment by tonyzzt001** [comment]
> 

不是我自己的，我没有设备跑这个IP

**Comment by tonyzzt001** [comment]
> 

请问哪里设置延时启动？我是每次重启WAN口或光猫或软路由就好了。

**Comment by tonyzzt001** [comment]
> 

我现在设置后连接数不会以前那样迅速升到99+了，不过还是在慢慢升到99+，我要是在设置延时长一点30，40，50，之类的会有什么影响吗？

**Comment by ppyohhh** [comment]
> > 
> 
> 我现在设置后连接数不会以前那样迅速升到99+了，不过还是在慢慢升到99+，我要是在设置延时长一点30，40，50，之类的会有什么影响吗？

那可能咱俩的问题不一样。。。。

**Comment by tonyzzt001** [comment]
> > 我现在设置后连接数不会以前那样迅速升到99+了，不过还是在慢慢升到99+，我要是在设置延时长一点30，40，50，之类的会有什么影响吗？
> 
> 那可能咱俩的问题不一样。。。。

嗯，应该是！不过谢了兄弟。

**Comment by MBRjun** [comment]
设置里关了外网访问
