### ISSUE TITLE
连接列表全部显示IP，无法根据走自定义规则

### ISSUE THREAD

**Issue by jasondong1999** [vernesong/OpenClash#2267]
clash面板连接列表里查看连接，都是IP不是域名，只有一两条显示域名，自定义域名分流规则失效，都走的漏网之鱼设定的服务器。请问求教是哪里出了问题

**Comment by littleneko** [comment]
改了 DNS ？或者浏览器开了 DOH/DOT 导致 DNS 请求没走 openclash

**Comment by jasondong1999** [comment]
> 改了 DNS ？或者浏览器开了 DOH/DOT 导致 DNS 请求没走 openclash

没有改DNS，软路由的DNS设置的是上级设备，电脑的DNS分配的是软路由。这个怎么解决啊

**Comment by yeepZhang** [comment]
遇到同样的问题， 还没解决

**Comment by uclort** [comment]
请问最后怎么解决的？我也有这个问题。

**Comment by sunr1s6** [comment]
使用openclash自带的dns服务器
