### ISSUE TITLE
各位用openclash很卡的，流量异常的，注意小心端口外泄被人扫到当成肉鸡或跳板！

### ISSUE THREAD

**Issue by bywuxin** [vernesong/OpenClash#2268]
很多openwrt的系统集成了openclash或者自行安装的openclash，相信大家都是喜欢折腾的人，但千万注意修改默认的openclash配置端口，做好防火墙策略，注意查看异常连接的流量，非必要别把外网端口全开。
已经检测发现最近一些SB在扫描HTTP(S)或者SOCKS5 把用于CC/DDOS攻击，扫的就是7890/7891/7892/7893等，千万注意。。。

**Comment by InsOnYou** [comment]
基本设置里开启“仅允许内网”就可以了吧

**Comment by MBRjun** [comment]
开外网代理还不配置认证被盗用后果自负
还有，SOCKS代理端口还可以SOCKS**4**

**Comment by bauw2008** [comment]
最新版本确实比前面卡不少。

**Comment by DamienMM** [comment]
根本没开外网代理啊，为什么还是被黑，很多国外的上传流量很多都是俄罗斯的，有没有大神告诉我该怎么解决。

**Comment by MBRjun** [comment]
> 根本没开外网代理啊，为什么还是被黑，很多国外的上传流量很多都是俄罗斯的，有没有大神告诉我该怎么解决。

有公网IP吗
