### ISSUE TITLE
[Request] Dashboard Panel open in new tab

### ISSUE THREAD

**Issue by djoeni** [vernesong/OpenClash#2269]
Request openclash dashboard panel from button at main page open in new tab instead.

Thanks

**Comment by MetaCubeX** [comment]
> Request openclash dashboard panel from button at main page open in new tab instead.
> 
> Thanks

long time no see

**Comment by djoeni** [comment]
> > Request openclash dashboard panel from button at main page open in new tab instead.
> > Thanks
> 
> long time no see

hi
glad that openclash now support meta
