### ISSUE TITLE
远程解析的问题

### ISSUE THREAD

**Issue by wangchunin** [vernesong/OpenClash#2270]
您好作者，我做了个实验，加入iptalbes：
iptables -t mangle  -I POSTROUTING  -p udp --dport 53 -j DROP
后，即使开启远程解析也无法解析dns了，但是我觉得应该还是能解析才对啊，我查阅了很久的资料，确实没有相同其中的道理。
我用的是【redir-host(tun混合)】模式，DNS设置中开启了“DNS劫持”和“远程域名解析”和“自定义上游服务器”
请问您可以帮我想想原因吗，或者我给的信息还不够

**Comment by nameless3721** [comment]
clash原版因为没域名探测的远程解析获取域名的方法是通过劫持dns到clash自己的dns服务器解析  只有控制台日志信息里面 域名和走代理 2个条件达成 才会给服务器发送域名来达到远程解析的效果  其他请到 https://blog.skk.moe/post/what-happend-to-dns-in-proxy/   这里看如何实现全局流量经过代理来   了解路由如何让设备走代理吧

**Comment by wangchunin** [comment]
非常感谢您的回答，在这片博客中，我确认了自己很多的猜想，也学习到许多新知识。
我猜测我问题的原因：
1. 由于屏蔽了53端口，没有设置tls等dns地址，导致redir模式无法解析域名
2. tcp链接就无法被建立起来
3. 代理客户端收不到想要的（ip+数据包），自然就没法替换成（域名+数据）的包发送给远程
4. 自然也就没法远程解析（确实远端也抓不到dns请求对应A记录的包）
5. 当然是在透明代理下，socks5从一开始就不存在这个问题因为直接就有（域名+数据）的包，直接发给远程
——————————————————————————————————————————————————
如果有什么不对的地方，希望大佬能够补充一下
但是现在仍然不清楚openclash中【远程域名解析】设置选项的意义，我测试过这个选项，开启后，也不会解析到直连的域名（判断规则为域名判断）
现在我再去测试下
————————————————————————————————————————————————————
我的目的就是希望所有的tcp udp全走代理
根据这篇博客，fakeip似乎就能满足目的
再次感谢大佬👍

**Comment by htfcuddles** [comment]
redir和fakeip都能实现全走代理，redir会通过clash自己dns服务器解析到真实IP，内存中会缓存解析结果，这样clash接收到客户端连接后就可以通过缓存反向把IP映射到域名。【远程域名解析】会把这个域名交给远程服务器解析（解析结果不一定等于上一步IP），若不选择的话则是把IP交给远程。

**Comment by lisonge** [comment]
请问 在本机 hosts 已经声明 ip 的情况下，如果关闭 【远程域名解析】呢？
