### ISSUE TITLE
网站访问检查问题

### ISSUE THREAD

**Issue by anglesccs** [vernesong/OpenClash#2273]
百度搜索和网易云音乐总是显示无法访问
![image](https://user-images.githubusercontent.com/49857157/163564434-5c5edab7-3c93-488e-af52-74d25e23fc89.png)

**Comment by vernesong** [comment]
f12看看报错信息

**Comment by anglesccs** [comment]
![2](https://user-images.githubusercontent.com/49857157/163655502-ea7eb6f6-6e80-4d72-b2a8-5a7146a829b1.JPG)

**Comment by vernesong** [comment]
广告屏蔽了

**Comment by anglesccs** [comment]
![2](https://user-images.githubusercontent.com/49857157/163655944-3d6f7832-3a86-409e-b73c-8d99bfa61b3d.JPG)
Openwrt里就装了这点东西，openclash Direct模式也不行，可能是啥屏蔽的？

**Comment by anglesccs** [comment]
www.baidu.com/favicon.ico?1650071436335:1 
这个就是百度的测试网址吗?电脑通过这个OPENWRT局域网代理的方式，这个网址是可以打开的

**Comment by zb737472783** [comment]
我也是 就百度打不开  么有广告过滤之类的功能

**Comment by zb737472783** [comment]
> 我也是 就百度打不开 么有广告过滤之类的功能

![image](https://user-images.githubusercontent.com/2137950/163951869-d9760f49-7f28-42d7-8556-bd45a8f5bed6.png)
![image](https://user-images.githubusercontent.com/2137950/163951900-5346e5ca-9a8c-46cf-843c-5bbffdef78cc.png)

**Comment by vernesong** [comment]
浏览器屏蔽

**Comment by zb737472783** [comment]
> 浏览器屏蔽

![image](https://user-images.githubusercontent.com/2137950/163952545-cd279d63-5937-48ab-8652-19a8126ee299.png)
应该没有吧  关了openclash就行...

**Comment by zb737472783** [comment]
每次启动刚开始一会是好的,过一会就无法访问,然后我切直连模式 瞬间就正常了,切策略又不行了.

**Comment by vernesong** [comment]
但是你F12确实是显示被屏蔽了

**Comment by vernesong** [comment]
ipify也是

**Comment by zb737472783** [comment]
那个F12不是的报错...

**Comment by zb737472783** [comment]
怎么能够排查一下  是什么原因啊  好郁闷

**Comment by zb737472783** [comment]
> 那个F12不是的报错...

不是我的截图

**Comment by vernesong** [comment]
那你报什么错

**Comment by zb737472783** [comment]
![image](https://user-images.githubusercontent.com/2137950/164002734-d2010700-f27d-4049-bf28-064f8d167189.png)
![image](https://user-images.githubusercontent.com/2137950/164002754-dd1d4519-81e5-4538-98da-096706887655.png)
![image](https://user-images.githubusercontent.com/2137950/164002774-7afc90b8-03fd-452c-b4a9-3e67621ba16e.png)
刚重新启动的 现在百度首页的新闻图片已经刷不出来了,新闻连接点不开了

**Comment by zb737472783** [comment]
![image](https://user-images.githubusercontent.com/2137950/164003237-26817c0b-cb05-4460-b7ea-1f93db837a6e.png)
现在彻底没了
![image](https://user-images.githubusercontent.com/2137950/164003353-275fa6a5-97f3-458b-899c-45d7171464f4.png)

**Comment by vernesong** [comment]
访问这个地址然后去控制面板找日志
