### ISSUE TITLE
请教大大，DNS设置-高级设置和配置文件订阅的问题

### ISSUE THREAD

**Issue by loohalh** [vernesong/OpenClash#2274]
1、ikuai主路由，openWrt旁路由，ikuai和openWrt的DNS服务器都是openWrt，openClash，模式为redir-host(兼容)，使用自定义DNS服务器，搭配ad一起使用，ad上游服务器为127.0.0.1:7874。我想让jenen.cn 、jenen.cn+不同端口以及jenen.cn 的子域名都不经过openClash的DNS服务器，DNS设置-高级设置中，如下图，我用第一种方案或者第二种方案设置了jenen.cn域名使用223.5.5.5 来解析，是不是都可以达到我的目的?
<img width="1013" alt="image" src="https://user-images.githubusercontent.com/16890588/163593443-97172e05-4a73-4c53-aca8-4e4bec9cf958.png">

<img width="1107" alt="image" src="https://user-images.githubusercontent.com/16890588/163592707-6d8220a1-33e2-4359-9573-78c70cff829d.png">
2、订阅文件设置了每天4点更新，但是好像不会在设置的时间点自动更新，需要手动点击更新才可以，如下图
<img width="1141" alt="image" src="https://user-images.githubusercontent.com/16890588/163593763-b708ccda-d88a-416e-ae13-9658e100f61e.png">
<img width="1197" alt="image" src="https://user-images.githubusercontent.com/16890588/163593902-5e1bbab7-fee6-4831-ac77-82eec5695042.png">

**Comment by loohalh** [comment]
问题一，已得到验证，这样配置没问题。问题二不知道为啥 先关了

**Comment by 771695775** [comment]
定时订阅那个你在openclash运行日志那里能看到，节点信息都没有变会显示不更新，如果多节点或者少节点信息有变，他才会更新
