### ISSUE TITLE
使用meta core时只能使用xtls协议或grpc协议，请求增加h2等协议的支持

### ISSUE THREAD

**Issue by mervynsword** [vernesong/OpenClash#2278]
使用meta core时只能使用xtls协议或grpc协议，请求增加h2等协议的支持

**Comment by MetaCubeX** [comment]
到频道下载最新的订阅转换工具，线上的在path部分转义有问题

**Comment by mervynsword** [comment]
我是使用自建，并不是订阅，所以短时间内不会支持h2或tcp是吗？

**Comment by MetaCubeX** [comment]
> 我是使用自建，并不是订阅，所以短时间内不会支持h2或tcp是吗？

已经支持的 检查下配置参数吧，用v2rayn的分享格式也可以在线转

**Comment by mervynsword** [comment]
> 持的 检查下配置参数吧，用v2rayn的分享格式也可以在线转

麻烦请给出相关的参数吧，再meta的github页面上只找到grpc的参数设置示例，没看到有h2相关的内容

**Comment by MetaCubeX** [comment]
> > 持的 检查下配置参数吧，用v2rayn的分享格式也可以在线转
> 
> 麻烦请给出相关的参数吧，再meta的github页面上只找到grpc的参数设置示例，没看到有h2相关的内容

id9.cc 选实验后端，用v2rayn的分享链接就能转
