### ISSUE TITLE
使用openclash后无法取得动态dns端口

### ISSUE THREAD

**Issue by xiaoxiongwn** [vernesong/OpenClash#2279]
外网访问内网，使用动态dns插件。翻墙如何使用passwall插件，动态dns取得的ip地址没有问题。不翻墙的情况下不启动passwall和openclash时也可以取得正确ip地址。但不使用passwall插件，而使用openclash后，动态dns插件取得的ip地址变成了别的ip（可能是代理节点的ip地址），致使外网无法访问内网。大家有这种情况吗？是我的问题？还是openclash本身的bug？

**Comment by aweigz** [comment]
我用openclash+DDNS没这个问题

**Comment by loohalh** [comment]
> 外网访问内网，使用动态dns插件。翻墙如何使用passwall插件，动态dns取得的ip地址没有问题。不翻墙的情况下不启动passwall和openclash时也可以取得正确ip地址。但不使用passwall插件，而使用openclash后，动态dns插件取得的ip地址变成了别的ip（可能是代理节点的ip地址），致使外网无法访问内网。大家有这种情况吗？是我的问题？还是openclash本身的bug？

有过，解决方案是DNS设置-高级设置中，配置你域名的DNS服务器,参考:[#2274](https://github.com/vernesong/OpenClash/issues/2274)

**Comment by xiaoxiongwn** [comment]
> > 外网访问内网，使用动态dns插件。翻墙如何使用passwall插件，动态dns取得的ip地址没有问题。不翻墙的情况下不启动passwall和openclash时也可以取得正确ip地址。但不使用passwall插件，而使用openclash后，动态dns插件取得的ip地址变成了别的ip（可能是代理节点的ip地址），致使外网无法访问内网。大家有这种情况吗？是我的问题？还是openclash本身的bug？
> 
> 有过，解决方案是DNS设置-高级设置中，配置你域名的DNS服务器，参考：[#2274](https://github.com/vernesong/OpenClash/issues/2274)

麻烦您，请教一下该改哪里呢？是改动态DNS里面的DNS、还是openclash里面的DNS？我基础比较差，给您添麻烦了。不能使用动态DNS，挺麻烦的。

**Comment by xiaoxiongwn** [comment]
> > 外网访问内网，使用动态dns插件。翻墙如何使用passwall插件，动态dns取得的ip地址没有问题。不翻墙的情况下不启动passwall和openclash时也可以取得正确ip地址。但不使用passwall插件，而使用openclash后，动态dns插件取得的ip地址变成了别的ip（可能是代理节点的ip地址），致使外网无法访问内网。大家有这种情况吗？是我的问题？还是openclash本身的bug？
> 
> 有过，解决方案是DNS设置-高级设置中，配置你域名的DNS服务器，参考：[#2274](https://github.com/vernesong/OpenClash/issues/2274)

我的动态DNS高级设置里面第一项IP地址来源里面，选择接口的话，在下面选择wan口会提示“高级设置 - IP 地址来源 [IPv4]: 无法确定本地 IP。请更换 IP 来源”。不知道ip地址来源这里应该选择哪项？

**Comment by openips** [comment]
来源选择接口
