### ISSUE TITLE
旁路网关使用openclash后，主路由流控失效

### ISSUE THREAD

**Issue by 497131664** [vernesong/OpenClash#228]
![F479C060-47B7-4E88-8225-27C22DD02805](https://user-images.githubusercontent.com/32135624/76431550-af239d80-63ec-11ea-933d-3ab9b03cb5cc.png)
所有流量均通过旁路网关的ip，如果关闭openclash则恢复正常，每个设备的流量都会通过自己的ip产生。关闭openclash后恢复正常。同时测试了下ssrplus没有问题，在网上搜索均没有找到答案。麻烦开发者了。

**Comment by vernesong** [comment]
因为进行了nat，所以实际上流量都是由clash发出的，这是预期行为

**Comment by 497131664** [comment]
感谢回复
