### ISSUE TITLE
为什么会出现这种错误

### ISSUE THREAD

**Issue by carrot117** [vernesong/OpenClash#2281]
time="2022-04-18T02:46:43Z" level=fatal msg="Parse config error: proxy group[2]: `use` or `proxies` missing"
clash启动失败，虽说是padavan的，我也不知道去哪问了，问题就是在一次断网后重启就出现这个问题，不是配置文件的问题，同一份配置在pc，手机上都是正常运行的，也不知道还要提供什么信息，需要的麻烦说一下

**Comment by MetaCubeX** [comment]
你还是好好检查下配置部分吧，的确是配置报错

**Comment by carrot117** [comment]
> 你还是好好检查下配置部分吧，的确是配置报错

我知道这是配置的报错，但是同一个机场的同一时间的同一份的订阅在pc和手机都能正常使用，也试过换别的机场的配置文件，一样是报错，也不带这样的吧

**Comment by MetaCubeX** [comment]
> > 你还是好好检查下配置部分吧，的确是配置报错
> 
> 我知道这是配置的报错，但是同一个机场的同一时间的同一份的订阅在pc和手机都能正常使用，也试过换别的机场的配置文件，一样是报错，也不带这样的吧

换行缩进你好好检查下……

**Comment by carrot117** [comment]
> > > 你还是好好检查下配置部分吧，的确是配置报错
> > 
> > 
> > 我知道这是配置的报错，但是同一个机场的同一时间的同一份的订阅在pc和手机都能正常使用，也试过换别的机场的配置文件，一样是报错，也不带这样的吧
> 
> 换行缩进你好好检查下……

 我是直接订阅的，也试过网上的转换模板，而且同一个文件在之前没有问题的

**Comment by vernesong** [comment]
第三个策略组没节点

**Comment by MetaCubeX** [comment]
用meta，哪怕没节点也有缺省

**Comment by carrot117** [comment]
谢谢，我看看

Outlook<https://aka.ms/qtex0l> for iOS
________________________________
发件人: vernesong ***@***.***>
发送时间: Monday, April 18, 2022 11:18:41 PM
收件人: vernesong/OpenClash ***@***.***>
抄送: carrot117 ***@***.***>; Author ***@***.***>
主题: Re: [vernesong/OpenClash] 为什么会出现这种错误 (Issue #2281)


第三个策略组没节点

―

**Comment by carrot117** [comment]
> > > 你还是好好检查下配置部分吧，的确是配置报错
> > 
> > 
> > 我知道这是配置的报错，但是同一个机场的同一时间的同一份的订阅在pc和手机都能正常使用，也试过换别的机场的配置文件，一样是报错，也不带这样的吧
> 
> 换行缩进你好好检查下……

 搞定了，确实是配置文件的问题，换个机场就没事了，谢谢你的帮助

**Comment by carrot117** [comment]
Meta内核吗

Outlook<https://aka.ms/qtex0l> for iOS
________________________________
发件人: Meta ***@***.***>
发送时间: Tuesday, April 19, 2022 1:37:59 AM
收件人: vernesong/OpenClash ***@***.***>
抄送: carrot117 ***@***.***>; Author ***@***.***>
主题: Re: [vernesong/OpenClash] 为什么会出现这种错误 (Issue #2281)


用meta，哪怕没节点也有缺省

―
