### ISSUE TITLE
fake ip混合模式使用meta内核ps5的nat类型失败

### ISSUE THREAD

**Issue by spirytuslove** [vernesong/OpenClash#2286]
同样模式下使用tun内核nat类型2 meta内核nat类型就失败

**Comment by vernesong** [comment]
不是vmess吧

**Comment by spirytuslove** [comment]
vmess和ss都试过了 好像meta内核nat类型都是失败 同样模式tun内核没问题

**Comment by vernesong** [comment]
嗅探开了吗

**Comment by spirytuslove** [comment]
你是说自定义流量探测设置吗 那个没开

**Comment by shuoyue21** [comment]
xbox一样的情况,使用meta后nat变为严格,fakeip混合模式是开放,开没开域名嗅探都一样

**Comment by spirytuslove** [comment]
我现在是暂时把meta关了 看什么时候能修复吧

**Comment by coderLyonMa** [comment]
v0.46.003-beta
该版本TUN模式/混合模式已无该问题
