### ISSUE TITLE
开启 OpenClash 影响NAT类型

### ISSUE THREAD

**Issue by Alano-i** [vernesong/OpenClash#2288]
OpenWrt 已开启 **全锥形 NAT**
OpenClash 关闭时，网心云上显示网络类型为映射公网
但是当启动 OpenClash ，就变成端口映射型了，降级了。

请问是设置不当还是本身存在bug?

**Comment by vernesong** [comment]
直连的会有这个问题，建议绕过国内

**Comment by Alano-i** [comment]
> 直连的会有这个问题，建议绕过国内

使用的fake-ip增强模式，没有绕过国内。能不能取消掉UDP流量转发来实现啊，刚试了下不知道是时间太短没反应过来还是本身这种方法不行，网心那边还是端口限制型。
<img width="778" alt="image" src="https://user-images.githubusercontent.com/68833595/164377569-932a7ab5-74cc-467f-b513-6982f52f7f76.png">

**Comment by TGSAN** [comment]
一样，连接国外STUN服务器，关闭OpenClash立刻FullCone，开了OpenClash就变成PortRestrictedCone。即使在Clash规则里面让STUN直连也是一样，兼容模式和TUN模式都一样，试了下 Windows 上 Clash 没这个问题，OpenClash需要关闭UDP代理或者勾选“仅允许常用端口流量”，让STUN流量完全不走OpenClash才可以。

**Comment by AnzhiZhang** [comment]
在 OpenClash 的全局设置中开启 `仅允许常用端口流量` 即可。

**Comment by TGSAN** [comment]
看上去最新版本依然没解决这个问题的样子，如果需要STUN走代理的话就无解了（即使代理服务端已经是支持FullCone的情况）

**Comment by link-duan** [comment]
我的问题比较简单，就希望 UPnP 能正常使用，公网通过端口映射访问不走代理。但是现在访问不通，用的 miniupnp ，有人解决过这个问题吗？

**Comment by TGSAN** [comment]
最近试了在openclash里换上新版本的clash内核和meta内核，发现和之前一样，但是在单独使用这些版本内核的情况下nat可以fullcone

**Comment by paladin4fan** [comment]
奇怪 我两台路由器同样的系统 都是clash内核 一个国外服务器direct可以继续fullcone 另一个不行

**Comment by chelomei** [comment]
大陆ip绕过核心模式,tun混合模式,国内外流量都能实现fullcone
大陆流量不绕过核心,同样设置的tun混合模式,国外流量仍可以实现fullcone,国内流量降为PortRestrictedCone

**Comment by paladin4fan** [comment]
> 大陆ip绕过核心模式,tun混合模式,国内外流量都能实现fullcone 大陆流量不绕过核心,同样设置的tun混合模式,国外流量仍可以实现fullcone,国内流量降为PortRestrictedCone

你的国外流量应该是走代理节点了 代理节点替你Fullcone的
如果是进了TUN内核又判定direct的国外流量 就会和不绕过核心的大陆流量一样被改成PortRestrictedCone
现在好像Tun模式是无解

**Comment by superdejavu** [comment]
我的udp流量老是直连，开了全局也还是直连，请教是为什么呢

**Comment by TGSAN** [comment]
> > 大陆ip绕过核心模式,tun混合模式,国内外流量都能实现fullcone 大陆流量不绕过核心,同样设置的tun混合模式,国外流量仍可以实现fullcone,国内流量降为PortRestrictedCone
> 
> 你的国外流量应该是走代理节点了 代理节点替你Fullcone的 如果是进了TUN内核又判定direct的国外流量 就会和不绕过核心的大陆流量一样被改成PortRestrictedCone 现在好像Tun模式是无解

兼容模式也会影响NAT，可能和TUN模式无关，另外试了下在Windows上带GUI的Clash客户端使用原版内核是可以FullCone的（但是Meta内核不行）

**Comment by paladin4fan** [comment]
> > > 大陆ip绕过核心模式,tun混合模式,国内外流量都能实现fullcone 大陆流量不绕过核心,同样设置的tun混合模式,国外流量仍可以实现fullcone,国内流量降为PortRestrictedCone
> > 
> > 
> > 你的国外流量应该是走代理节点了 代理节点替你Fullcone的 如果是进了TUN内核又判定direct的国外流量 就会和不绕过核心的大陆流量一样被改成PortRestrictedCone 现在好像Tun模式是无解
> 
> 兼容模式也会影响NAT，可能和TUN模式无关，另外试了下在Windows上带GUI的Clash客户端使用原版内核是可以FullCone的（但是Meta内核不行）

我用了三台同个固件的软路由试了下 只有一台兼容模式下对国外direct规则也是fullcone的 剩下两台都是降级 NatTypeTester测试NAT3 PyStun3测试NAT2
不知道这个唯一一台成功的是为什么 是因为运营商还是因为我配了mwan3分流

**Comment by jacobsenxin** [comment]
同样遇到此问题，请问您最后是如何解决的，我是switch主机，关闭openclash是NAT A，打开走代理是NAT F,走直连是NAT B

**Comment by TGSAN** [comment]
> 同样遇到此问题，请问您最后是如何解决的，我是switch主机，关闭openclash是NAT A，打开走代理是NAT F,走直连是NAT B

无解，只能让流量不要过OpenClash才可以，不过NAT F应该是节点问题

**Comment by TGSAN** [comment]
> 可以增加一个代理绕过端口的功能吗，类似于passwall，把stun的流量给绕过。我用的的redir-host兼容模式meta核，使用natmap只有把指定的tcp stun服务器的ip添加到本地ip地址绕过才可以打洞成功（udp的不需要，可以直接打成功，并且观察到开启openclash，tcp只有80和443可以打成功），或者openclash延迟启动，等打完洞再启动。。。。

之前有开一个新的issue #3480 里面是希望可以单独指定TCP或者UDP的那些端口需要走内核

**Comment by stackia** [comment]
在 OpenClash 插件设置 - 开发者选项，加入这两条 nftables 规则，把所有 STUN 流量绕过即可（3478-3497 是苹果 FaceTime 的 STUN 端口范围）

```
nft insert rule inet fw4 openclash_mangle position 0 meta nfproto ipv4 udp dport 3478-3497 counter return
nft insert rule inet fw4 openclash_mangle_v6 position 0 meta nfproto ipv6 udp dport 3478-3497 counter return
```

**Comment by paladin4fan** [comment]
> 在 OpenClash 插件设置 - 开发者选项，加入这两条 nftables 规则，把所有 STUN 流量绕过即可（3478-3497 是苹果 FaceTime 的 STUN 端口范围）
> 
> ```
> nft insert rule inet fw4 openclash_mangle position 0 meta nfproto ipv4 udp dport 3478-3497 counter return
> nft insert rule inet fw4 openclash_mangle_v6 position 0 meta nfproto ipv6 udp dport 3478-3497 counter return
> ```

  问题是很多需求fullcone的人是用来打游戏的 而游戏是不是用的标准stun端口呢

**Comment by stackia** [comment]
除了标准的 STUN，大多数 p2p 协议从设计上都会使用 3478 附近端口来打洞，因为很多防火墙在 3478 上比较宽松。
我观察到的有：FaceTime、HomeKit Secure Video、微信视频聊天、Steam/PS/Xbox Networking（大多数游戏底层使用）、Zoom、Teams、Google Meet、GTA5 等。

**Comment by vernesong** [comment]
新版加了tun的接口，nat应该没问题

**Comment by paladin4fan** [comment]
新版用tun udp模式 判定direct的流量好像还是被降级nat
________________________________

**Comment by TGSAN** [comment]
> 新版加了tun的接口，nat应该没问题

试了下新版本tun接口可以让命中代理链的流量正常变为FullCone了，但是奇怪的是命中DIRECT的流量反而变成了PortResCone

**Comment by vernesong** [comment]
直连的没办法

**Comment by TGSAN** [comment]
即使打了FullCone NAT的补丁也没办法吗，不过代理可以FullCone应该可以本机开代理服务然后DIRECT规则连本机了。辛苦作者开发了，感谢！

**Comment by TGSAN** [comment]
> 可以试试开启 clash meta 的 endpoint-independent-nat https://wiki.metacubex.one/config/inbound/tun/#endpoint-independent-nat

一直开着，用的开发者模式的ruby_edit
![image](https://github.com/vernesong/OpenClash/assets/7440847/8075ebb9-27a9-44c2-830e-02a0e0b87c80)

**Comment by paladin4fan** [comment]
> > 可以试试开启 clash meta 的 endpoint-independent-nat https://wiki.metacubex.one/config/inbound/tun/#endpoint-independent-nat
> 
> 一直开着，用的开发者模式的ruby_edit ![image](https://private-user-images.githubusercontent.com/7440847/302546703-8075ebb9-27a9-44c2-830e-02a0e0b87c80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMzk1MTUsIm5iZiI6MTcwNzIzOTIxNSwicGF0aCI6Ii83NDQwODQ3LzMwMjU0NjcwMy04MDc1ZWJiOS0yN2E5LTQ0YzItODMwZS0wMmEwZTBiODdjODAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDZUMTcwNjU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjQzZGNlMWQ0ZTVhYzkzNjMzNGQ4OTlkNDg4YWNlYjFjMWQzMDc0OGRhYmM3YTIxNmYxMjY5NWE1MzE3NjNhYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7OETKT2CIVvFLxGqBbF6IvT4ygbvhd2yNdvr9D19BD4) ![image](https://private-user-images.githubusercontent.com/7440847/302547531-8e53fe41-29cb-4ba9-95fb-ee38ddf1466f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMzk1MTUsIm5iZiI6MTcwNzIzOTIxNSwicGF0aCI6Ii83NDQwODQ3LzMwMjU0NzUzMS04ZTUzZmU0MS0yOWNiLTRiYTktOTVmYi1lZTM4ZGRmMTQ2NmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDZUMTcwNjU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmFmMGM0Y2FlZjRlNjhlMDc4MDQwMTVlNWE5MTliYWFiNDNlY2FkMTQ0MmExOTQxNzY4Y2E5MWY4MDM3YmJiMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.aBbZbL3v-fqwaDH9V2EEu8Eifaj7HEGXZky2Df4vIdI)


所以当前OC的三个核心 唯一可以在开启UDP代理的时候实现direct链接fullcone的方式
就是用路由器自身的代理服务器重新代理一遍？

**Comment by TGSAN** [comment]
> 所以当前OC的三个核心 唯一可以在开启UDP代理的时候实现direct链接fullcone的方式 就是用路由器自身的代理服务器重新代理一遍？
做法有点脏，但是目前看上去可行。其他方案还在研究。

**Comment by paladin4fan** [comment]
> > 所以当前OC的三个核心 唯一可以在开启UDP代理的时候实现direct链接fullcone的方式 就是用路由器自身的代理服务器重新代理一遍？
> 
> 做法有点脏，但是目前看上去可行。其他方案还在研究。

这个方案实践过了吗 如果可以让国外direct流量变回fullcone那我也这么玩好了

**Comment by Pacio** [comment]
目前用的fakeip+混合模式~无解啊~fullcone都没了

**Comment by paladin4fan** [comment]
> 目前用的fakeip+混合模式~无解啊~fullcone都没了

fakeip确实难搞
我用redir 可以单独把ipv4 udp链接排除出去用passwall
也算是曲线救国

**Comment by iTofu** [comment]
同问，fake-ip 模式有啥解决方案吗？需要 fullcone

**Comment by Todd-Zhangt** [comment]
> > 新版加了tun的接口，nat应该没问题
> 
> 试了下新版本tun接口可以让命中代理链的流量正常变为FullCone了，但是奇怪的是命中DIRECT的流量反而变成了PortResCone

大佬麻烦问一下有什么新的解决办法么？我现在用的fakeip增强模式，natmap打洞会失败 NAT类型变成NAT3。改成redir-host就正常了

**Comment by TGSAN** [comment]
> > > 新版加了tun的接口，nat应该没问题
> > 
> > 
> > 试了下新版本tun接口可以让命中代理链的流量正常变为FullCone了，但是奇怪的是命中DIRECT的流量反而变成了PortResCone
> 
> 大佬麻烦问一下有什么新的解决办法么？我现在用的fakeip增强模式，natmap打洞会失败 NAT类型变成NAT3。改成redir-host就正常了

我不用fakeip，因为打洞和fakeip本身就很容易冲突（一个是转换地址，一个是解地址转换）

**Comment by JokerIvanZK** [comment]
fakeip模式下如果能够确定端口可以在 插件设置-黑白名单-绕过核心的来源端口 指定对应端口直接绕过代理

**Comment by Alunixa** [comment]
在openclash的 “仅允许特定端口流量” 这个设置里填上 1-3477,3479-5348,5350-65535  然后就好了。好了记得来咕一声

**Comment by q736178471** [comment]
最新版本没这个选项啊

<img width="2560" height="1343" alt="Image" src="https://github.com/user-attachments/assets/94445464-bb6c-401a-befe-cf4720b76c6f" />

> 在openclash的 “仅允许特定端口流量” 这个设置里填上 1-3477,3479-5348,5350-65535 然后就好了。好了记得来咕一声

**Comment by Alunixa** [comment]
[image: image.png]插件设置---流量控制。只有在RH模式下才会有这个选项。fake-ip在开发者选项里填入


  #!/bin/sh
. /usr/share/openclash/log.sh
. /lib/functions.sh






sleep 5

if nft list ruleset | grep -q "chain openclash_mangle"; then

    # 针对所有内网设备，强制 3478 端口不走代理
# IPv4 TCP 绕过（input/forward 方向 + output 方向）
nft insert rule inet fw4 openclash tcp dport { 3478, 5349, 38810, 38820,
38830, 38840 } counter return
nft insert rule inet fw4 openclash_output tcp dport { 3478, 5349, 38810,
38820, 38830, 38840 } counter return

# IPv4 UDP 绕过（主要是 mangle 表用于标记/路由策略）
nft insert rule inet fw4 openclash_mangle udp dport { 3478, 5349, 38810,
38820, 38830, 38840 } counter return
nft insert rule inet fw4 openclash_mangle_output udp dport { 3478, 5349,
38810, 38820, 38830, 38840 } counter return

# IPv6 部分（如果你的 OpenClash 开启了 IPv6 支持，就加这些，命令加了 2>/dev/null 防止没链时报错）
nft insert rule inet fw4 openclash_mangle_v6 udp dport { 3478, 5349, 38810,
38820, 38830, 38840 } counter return 2>/dev/null
nft insert rule inet fw4 openclash_mangle_output_v6 udp dport { 3478, 5349,
38810, 38820, 38830, 38840 } counter return 2>/dev/null

# IPv6 TCP 如果也需要（OpenClash IPv6 代理通常也走 mangle，但 TCP 部分看你配置，有的不一定有
openclash_v6 链，可以先试加）
nft insert rule inet fw4 openclash tcp dport { 3478, 5349, 38810, 38820,
38830, 38840 } counter return 2>/dev/null
nft insert rule inet fw4 openclash_output tcp dport { 3478, 5349, 38810,
38820, 38830, 38840 } counter return 2>/dev/null

LOG_OUT "3478、5349、38810、38820、38830、38840已成功绕过。"

fi

ruby_edit "$CONFIG_FILE" "['tun']['mtu']" "1440"


exit 0


如果解决了你的问题我会很高兴😉

q736178471 ***@***.***> 于2026年5月10日周日 22:30写道：
