### ISSUE TITLE
最近几个版本fq正常但google.com间歇性无法连接

### ISSUE THREAD

**Issue by kkfuzi** [vernesong/OpenClash#2290]
说一下环境和配置。openwrt 5.15，openclash + adguard home。 openclash redir，启用了远程域名解析。机场+ ACL4SSR规则
openclash dev 目前最新版本0.45.06

问题描述：
最近几个版本出现的问题，整体翻墙一切正常，youtube可正常访问观看，但Google.com间歇性无法连接。手动更新配置后恢复，过一段时间后又无法连接。手机用小火箭或电脑用clash客户端连接没问题。

不知道有没有人有类似问题。谢谢

**Comment by MBRjun** [comment]
你日志呢

**Comment by kkfuzi** [comment]
> 禁用quic估计就行了

之前就禁用了

**Comment by kkfuzi** [comment]
昨天更新了内核，目前测试正常，在观望几天

**Comment by kkfuzi** [comment]
测试了两天，更新内核后正常了。考虑把更新方式从dev转回master了，可能更稳定一些。

**Comment by marlonfan** [comment]
同情况, @kkfuzi 有遇到的话可以交流下看看到底为啥... google.com.hk 无任何问题. google.com间歇性能打开...

**Comment by kkfuzi** [comment]
> 到的话可以交流
我自己做了测试，首先应该能排除机场节点的问题，无法访问的时候通过手机端小火箭或者笔记本端的CFW都没问题。然后openclash的配置应该也没问题，都没动过，有人说是防火墙的顺序问题，我觉得不太可能。
我个人怀疑可能是openclash的远程域名解析的锅？想测试但是现在redir 模式下是强制远程了。。。

**Comment by kkfuzi** [comment]
我自己做了测试，首先应该能排除机场节点的问题，无法访问的时候通过手机端小火箭或者笔记本端的CFW都没问题。然后openclash的配置应该也没问题，都没动过，有人说是防火墙的顺序问题，我觉得不太可能。
我个人怀疑可能是openclash的远程域名解析的锅？想测试但是现在redir 模式下是强制远程了。。。

**Comment by marlonfan** [comment]
是指自定义上游dns服务器么?

**Comment by marlonfan** [comment]
我使用的是`fake-ip`模式, 之前没有开启自定义上游服务器 我怀疑我这边是不是dns拦截了. 现在开启在观察..

**Comment by wdubaiyu** [comment]
我也遇到了，我把小猫咪关闭了换ssrp一切正常，只要用小猫咪就会这样。我dns设置的smartDNS，ssrp用smartDNS也没问题，个人觉得这个可能是猫咪本身的问题了。等待大神，看了clash日志，确实走了节点，为什么不通就不知道了
