### ISSUE TITLE
使用meta内核无法正常上网

### ISSUE THREAD

**Issue by coderbean** [vernesong/OpenClash#2291]
自行更换了固件，由原来的404大佬固件更换为天灵大佬固件，使用meta内核无下面错误了。
同时解决了每次启动 设置防火墙规则 和 重置Dnsmasq 需要很久（大约共10分钟）的问题

----
更换内核，配置文件只修改了订阅节点过滤。

启动后没有报错异常，
但是无法打开百度、谷歌网页。

电视手机app打开Netflix都正常。

手机电脑访问Google网页，Chrome提示网站已经永久移动。

请求Google尝试查看日志，日志中无请求记录

补充一下调试日志

```
OpenClash 调试日志

生成时间: 2022-04-20 18:46:42
插件版本: v0.45.06-beta
隐私提示: 上传此日志前请注意检查、屏蔽公网IP、节点、密码等相关敏感信息

```

**Comment by hcym** [comment]
昨天试过正常，就是没什么区别，😂

**Comment by zzz6839** [comment]
使用META内核后，BT客户端的DHT显著减少，以及在wegame上英雄联盟提示多个网络出口，导致到各个节点的延迟都超过100+，以及玩游戏的时候会突然掉线并无法重连。

考虑到meta内核现在还不成熟，所以还是关闭并采用原版内核在使用。

**Comment by coderbean** [comment]
自行更换了固件，由原来的404大佬固件更换为天灵大佬固件，使用meta内核无下面错误了。
同时解决了每次启动 设置防火墙规则 和 重置Dnsmasq 需要很久（大约共10分钟）的问题

**Comment by chenzhiguo** [comment]
openclash只要切换到meta内核，就没法上网，切换回原版内核，就正常，求解，咋回事儿呢？
