### ISSUE TITLE
关于添加代理集的问题

### ISSUE THREAD

**Issue by doushixiaoshisa** [vernesong/OpenClash#2293]
我用github私密仓库制作一个clash格式的配置文件，我将私密链接添加到服务器与策略组管理中的代理集，然后一键生成配置文件，这样做并不能使用，但是这个链接可以在小火箭、浏览器里面打开并下载

**Comment by vernesong** [comment]
格式正确是能使用的，你手动刷新

**Comment by doushixiaoshisa** [comment]
> 格式是能使用的，你手动刷新

我同样的文件，放到github，获取到的链接就不能更新，手动也不行

**Comment by vernesong** [comment]
![image](https://user-images.githubusercontent.com/42875168/164652272-9145fe2e-bcd8-4fa6-8c95-4a1050d2dc7d.png)
