### ISSUE TITLE
原版OpenWrt 21.02.2为什么装不上v0.45.06beta？

### ISSUE THREAD

**Issue by supersensen** [vernesong/OpenClash#2295]
root@OpenWrt:~# opkg install coreutils-nohup bash iptables dnsmasq-full curl ca-certificates ipset ip-full iptables-mod-tp
roxy iptables-mod-extra libcap libcap-bin ruby ruby-yaml kmod-tun kmod-inet-diag
Package coreutils-nohup (8.32-6) installed in root is up to date.
Package bash (5.1-2) installed in root is up to date.
Package iptables (1.8.7-1) installed in root is up to date.
Installing dnsmasq-full (2.85-8) to root...
Downloading https://downloads.openwrt.org/releases/21.02.2/packages/mipsel_24kc/base/dnsmasq-full_2.85-8_mipsel_24kc.ipk
Package curl (7.82.0-2) installed in root is up to date.
Package ca-certificates (20210119-1) installed in root is up to date.
Package ipset (7.6-1) installed in root is up to date.
Package ip-full (5.11.0-3) installed in root is up to date.
Package iptables-mod-tproxy (1.8.7-1) installed in root is up to date.
Package iptables-mod-extra (1.8.7-1) installed in root is up to date.
Package libcap (2.43-1) installed in root is up to date.
Package libcap-bin (2.43-1) installed in root is up to date.
Package ruby (3.0.3-1) installed in root is up to date.
Package ruby-yaml (3.0.3-1) installed in root is up to date.
Package kmod-tun (5.4.179-1) installed in root is up to date.
Unknown package 'kmod-inet-diag'.
Collected errors:
 * check_data_file_clashes: Package dnsmasq-full wants to install file /etc/hotplug.d/ntp/25-dnsmasqsec
        But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /etc/init.d/dnsmasq
        But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /usr/lib/dnsmasq/dhcp-script.sh
        But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /usr/sbin/dnsmasq
        But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /usr/share/acl.d/dnsmasq_acl.json
        But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /usr/share/dnsmasq/dhcpbogushostname.conf
        But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /usr/share/dnsmasq/rfc6761.conf
        But that file is already provided by package  * dnsmasq
 * opkg_install_cmd: Cannot install package dnsmasq-full.
 * opkg_install_cmd: Cannot install package kmod-inet-diag.
root@OpenWrt:~#

web页面上upload ipk无反应，在ssh里安装依赖偶几个找不到，求大佬带路！

**Comment by jeasonliang** [comment]
opkg update
opkg remove dnsmasq && opkg install dnsmasq-full

**Comment by MBRjun** [comment]
按照楼上的方法安装 dnsmasq-full 或者自己编译时选上
