### ISSUE TITLE
openclash的dns协议不支持socks5

### ISSUE THREAD

**Issue by zhangjiaqing2000** [vernesong/OpenClash#2296]
openclash可以在dns上游服务器添加socks5协议么？就例如在火狐浏览器上的功能。
![image](https://user-images.githubusercontent.com/48935590/164335606-b85c6557-17c7-4d20-8306-e3b599014739.png)

**Comment by zhangjiaqing2000** [comment]
因为使用某些代理节点并不支持udp查询，并且我不想用doh类型（影响速度），国内udp也会被泛播劫持。

**Comment by vernesong** [comment]
不支持，浏览器这是在设置代理，可以设置clash的对应地址
