### ISSUE TITLE
自定义Hosts和Domain规则的问题

### ISSUE THREAD

**Issue by twtjy2008** [vernesong/OpenClash#23]
在redir-host模式下，自定义Hosts貌似并没有起作用，指定的域名没有走指定的ip。
另外，刚装上openclash的时候，DOMAIN规则是有效的，可以DIRECT，REJECT。但是，调了几次设置之后，不知道为何，DOMAIN规则不起作用了，在LOG里只有GEOIP, IP-CIDR, MATCH，没有DOMAIN相关的规则了，REJECT的DOMAIN并没有被BLOCK。看起来是连接被解析之后才进行规则判断，请问这是碰了什么设置吗？

**Comment by vernesong** [comment]
这说明路由器上DNS流量没有正常劫持到clash，而是被其他插件劫持并解析了，客户端拿解析后的IP地址连接，日志里就会只有IP地址的连接信息。
你需要检查路由器DNS设置，关闭其他插件的DNS劫持功能，确保DNS请求是通过clash去解析的。
自定义HOST同理，按照上面说明检查正常后，应该才会起作用

**Comment by vernesong** [comment]
跟性能有关，启动时基本都是靠的shell命令去修改配置文件，所以你规则很多的话不建议开太多功能，命令修改起来太慢

**Comment by twtjy2008** [comment]
原来是这样。那我就用一两千的规则吧，谢谢解答
