### ISSUE TITLE
Netflix怎么总是被检测到代理

### ISSUE THREAD

**Issue by guitarppp** [vernesong/OpenClash#230]
fake-ip增强与游戏模式都试了很多次，总是不行。难啊
全局模式倒是可以，不过openclash不能定义单个IP地址用全局。

**Comment by vernesong** [comment]
基本上是规则不完善导致的，电视端因为检测机制可能也会出现此问题。
单个全局可以自定规则
```
- SRC-IP-CIDR,192.168.1.201/32,DIRECT
```

**Comment by yangliu** [comment]
最后 Match 走代理基本可以解决，netflix部分客户端，特别是android tv平台的客户端，会直接通过ip访问，当前规则很难全员覆盖。所以我才提出了 #172 的建议和pr

**Comment by hehehehehaha** [comment]
港台地区貌似多了几条 IP 地址，自定义规则加上去就行了
```
210.0.153.0/24
203.75.84.0/24
203.198.13.0/24
203.198.80.0/24

**Comment by guitarppp** [comment]
> 基本上是规则不完善导致的，电视端因为检测机制可能也会出现此问题。
> 单个全局可以自定规则
> 
> ```
> - SRC-IP-CIDR,192.168.1.201/32,DIRECT
> ```

Direct是直连，proxy是自动代理，全局是哪个参数?

**Comment by vernesong** [comment]
规则最后的match 走代理也不行？

**Comment by guitarppp** [comment]
加了指定IP全局  加了港台新IP  还是不行

- IP-CIDR,210.0.153.0/24,PROXY
- IP-CIDR,203.75.84.0/24,PROXY
- IP-CIDR,203.198.13.0/24,PROXY
- IP-CIDR,203.198.80.0/24,PROXY

- SRC-IP-CIDR,192.168.1.38/32,PROXY
- SRC-IP-CIDR,192.168.1.39/32,PROXY

**Comment by yangliu** [comment]
结合当前release版本openclash 0.36.9 自定义规则的逻辑，设置的自定义规则会插入在所有规则的前面，也就是说 SRC-IP-CIDR 已经使对应客户端进入全局代理（都走PROXY 策略组），如果其它设置都无误的话，就是你的代理服务器被netflix拉黑了。如果可以确定代理服务器没问题的话，建议排查一下策略组的设定。

**Comment by MartialBE** [comment]
如果是买的机场的
是否和机场 使用的人数太多导致的？
目前 我使用 的机场 香港的 节点，NF 有时候正常 有时候会返回 使用代理(其他人貌似用香港的看没问题)。
但是， 如果我使用台湾的 就完全不会出现这种情况。   
规则我使用的是 openclash里面的 lhie1。除了必要的规则，其他和 match 使用的都是 直连。
PS:
我使用的是 火棒， 当出现 检查到您在使用 代理后， 直接切换其他节点，是不行的， 必须要 重启 火棒后，才会生效， 估计可能因为存在 【缓存】的原因。
最好的方法是， 直接在电脑上 开一个 无痕浏览， 打开 NF 网站去登录，如果不能登录， 则关闭浏览器， 切换节点，再开无痕 来一遍，  如果可以正常登录使用，说明该节点 是能正常使用的， 然后再 重启 电视 -。-

**Comment by soriano** [comment]
如果通过设定电视机的所有流量走代理可否？

**Comment by Masstone** [comment]
> 如果通过设定电视机的所有流量走代理可否？

不一定可以，原因如下：
如果你使用的代理服务器是DNS解锁的服务器（通俗解释：基于来源请求的域名判断，将访问Netflix的请求通过另一个原本就能观看Netflix的服务器进行代理）
那么就要求代理客户端发起的请求必须是域名的方式，
Clash以域名方式建立代理连接的前提是，Clash DNS解析过相应的域名，留下了ip与域名的映射关系。
但个别盒子比如firestick则直接向8.8.8.8以TCP方式53端口发起DNS查询，然后发起对ip的请求，，即便劫持8.8.8.8到Clash DNS，由于Clash不具备解析tcp  dns请求的能力（游戏内核除外），这种情况下Clash便无法得知ip与域名的对应关系，只能同样以ip的方式建立和代理服务器的链接，此时即便你使用全局代理也无法观看。

如果你的代理服务器是原本就可以观看Netflix的（所谓原生节点），那么无论代理客户端以ip还是域名发起请求都可以观看，所以全局代理也一定可以。

**Comment by soriano** [comment]
> > 如果通过设定电视机的所有流量走代理可否？
> 
> 不一定可以，原因如下：
> 如果你使用的代理服务器是DNS解锁的服务器（通俗解释：基于来源请求的域名判断，将访问Netflix的请求通过另一个原本就能观看Netflix的服务器进行代理）
> 那么就要求代理客户端（如 Clash）以域名的方式发起TCP请求，Clash默认是以域名发起请求，
> 但Clash得知请域名的前提是，Netflix APP端以域名的方式发起请求，并且Clash DNS解析过相应的域名，留下了ip与域名的映射关系。
> 但个别盒子比如firestick则直接向8.8.8.8以TCP方式53端口发起DNS查询，然后发起对ip的请求，即便劫持8.8.8.8到Clash DNS，由于Clash不具备解析tcp dns请求的能力（游戏内核除外），这种情况下Clash便无法得知ip与域名的对应关系，只能同样以ip的方式建立和代理服务器的链接，此时你的代理服务器便无法得知你访问的是Netflix域名，即便你使用全局代理也无法观看，除非这个代理服务器把所有相关ip列入Netflix规则中（此规则非Clash的分流规则）。
> 
> 如果你的代理服务器是原本就可以观看Netflix的（所谓原生节点），那么无论代理客户端以ip还是域名发起请求都可以观看，所以全局代理也一定可以。

是的，我之前netflix被检测代理，关注连接发现就是直接向8.8.8.8以TCP方式53端口发起DNS查询，后来机场主动调整后，就可以正常看了，在这种情况下，把电视机设定规则全走代理反而会被认定使用代理，正常走奈飞策略组就可以正常观看，谢谢讲解。

**Comment by Masstone** [comment]
> > > 如果通过设定电视机的所有流量走代理可否？
> > 
> > 
> > 不一定可以，原因如下：
> > 如果你使用的代理服务器是DNS解锁的服务器（通俗解释：基于来源请求的域名判断，将访问Netflix的请求通过另一个原本就能观看Netflix的服务器进行代理）
> > 那么就要求代理客户端（如 Clash）以域名的方式发起TCP请求，Clash默认是以域名发起请求，
> > 但Clash得知请域名的前提是，Netflix APP端以域名的方式发起请求，并且Clash DNS解析过相应的域名，留下了ip与域名的映射关系。
> > 但个别盒子比如firestick则直接向8.8.8.8以TCP方式53端口发起DNS查询，然后发起对ip的请求，即便劫持8.8.8.8到Clash DNS，由于Clash不具备解析tcp dns请求的能力（游戏内核除外），这种情况下Clash便无法得知ip与域名的对应关系，只能同样以ip的方式建立和代理服务器的链接，此时你的代理服务器便无法得知你访问的是Netflix域名，即便你使用全局代理也无法观看，除非这个代理服务器把所有相关ip列入Netflix规则中（此规则非Clash的分流规则）。
> > 如果你的代理服务器是原本就可以观看Netflix的（所谓原生节点），那么无论代理客户端以ip还是域名发起请求都可以观看，所以全局代理也一定可以。
> 
> 是的，我之前netflix被检测代理，关注连接发现就是直接向8.8.8.8以TCP方式53端口发起DNS查询，后来机场主动调整后，就可以正常看了，在这种情况下，把电视机设定规则全走代理反而会被认定使用代理，正常走奈飞策略组就可以正常观看，谢谢讲解。

你也是用火棒么？ [私聊]( https://t.me/Masstone)交流一下啊

**Comment by soriano** [comment]
> > > > 如果通过设定电视机的所有流量走代理可否？
> > > 
> > > 
> > > 不一定可以，原因如下：
> > > 如果你使用的代理服务器是DNS解锁的服务器（通俗解释：基于来源请求的域名判断，将访问Netflix的请求通过另一个原本就能观看Netflix的服务器进行代理）
> > > 那么就要求代理客户端（如 Clash）以域名的方式发起TCP请求，Clash默认是以域名发起请求，
> > > 但Clash得知请域名的前提是，Netflix APP端以域名的方式发起请求，并且Clash DNS解析过相应的域名，留下了ip与域名的映射关系。
> > > 但个别盒子比如firestick则直接向8.8.8.8以TCP方式53端口发起DNS查询，然后发起对ip的请求，即便劫持8.8.8.8到Clash DNS，由于Clash不具备解析tcp dns请求的能力（游戏内核除外），这种情况下Clash便无法得知ip与域名的对应关系，只能同样以ip的方式建立和代理服务器的链接，此时你的代理服务器便无法得知你访问的是Netflix域名，即便你使用全局代理也无法观看，除非这个代理服务器把所有相关ip列入Netflix规则中（此规则非Clash的分流规则）。
> > > 如果你的代理服务器是原本就可以观看Netflix的（所谓原生节点），那么无论代理客户端以ip还是域名发起请求都可以观看，所以全局代理也一定可以。
> > 
> > 
> > 是的，我之前netflix被检测代理，关注连接发现就是直接向8.8.8.8以TCP方式53端口发起DNS查询，后来机场主动调整后，就可以正常看了，在这种情况下，把电视机设定规则全走代理反而会被认定使用代理，正常走奈飞策略组就可以正常观看，谢谢讲解。
> 
> 你也是用火棒么？ [TG私聊](https://t.me/Masstone)交流一下啊

我是LG电视机的webos，我加你了

**Comment by Masstone** [comment]
> > > > > 如果通过设定电视机的所有流量走代理可否？
> > > > 
> > > > 
> > > > 不一定可以，原因如下：
> > > > 如果你使用的代理服务器是DNS解锁的服务器（通俗解释：基于来源请求的域名判断，将访问Netflix的请求通过另一个原本就能观看Netflix的服务器进行代理）
> > > > 那么就要求代理客户端（如 Clash）以域名的方式发起TCP请求，Clash默认是以域名发起请求，
> > > > 但Clash得知请域名的前提是，Netflix APP端以域名的方式发起请求，并且Clash DNS解析过相应的域名，留下了ip与域名的映射关系。
> > > > 但个别盒子比如firestick则直接向8.8.8.8以TCP方式53端口发起DNS查询，然后发起对ip的请求，即便劫持8.8.8.8到Clash DNS，由于Clash不具备解析tcp dns请求的能力（游戏内核除外），这种情况下Clash便无法得知ip与域名的对应关系，只能同样以ip的方式建立和代理服务器的链接，此时你的代理服务器便无法得知你访问的是Netflix域名，即便你使用全局代理也无法观看，除非这个代理服务器把所有相关ip列入Netflix规则中（此规则非Clash的分流规则）。
> > > > 如果你的代理服务器是原本就可以观看Netflix的（所谓原生节点），那么无论代理客户端以ip还是域名发起请求都可以观看，所以全局代理也一定可以。
> > > 
> > > 
> > > 是的，我之前netflix被检测代理，关注连接发现就是直接向8.8.8.8以TCP方式53端口发起DNS查询，后来机场主动调整后，就可以正常看了，在这种情况下，把电视机设定规则全走代理反而会被认定使用代理，正常走奈飞策略组就可以正常观看，谢谢讲解。
> > 
> > 
> > 你也是用火棒么？ [TG私聊](https://t.me/Masstone)交流一下啊
> 
> 我是LG电视机的webos，我加你了

好像没收到。。怎么回事

**Comment by soriano** [comment]
> > > > > > 如果通过设定电视机的所有流量走代理可否？
> > > > > 
> > > > > 
> > > > > 不一定可以，原因如下：
> > > > > 如果你使用的代理服务器是DNS解锁的服务器（通俗解释：基于来源请求的域名判断，将访问Netflix的请求通过另一个原本就能观看Netflix的服务器进行代理）
> > > > > 那么就要求代理客户端（如 Clash）以域名的方式发起TCP请求，Clash默认是以域名发起请求，
> > > > > 但Clash得知请域名的前提是，Netflix APP端以域名的方式发起请求，并且Clash DNS解析过相应的域名，留下了ip与域名的映射关系。
> > > > > 但个别盒子比如firestick则直接向8.8.8.8以TCP方式53端口发起DNS查询，然后发起对ip的请求，即便劫持8.8.8.8到Clash DNS，由于Clash不具备解析tcp dns请求的能力（游戏内核除外），这种情况下Clash便无法得知ip与域名的对应关系，只能同样以ip的方式建立和代理服务器的链接，此时你的代理服务器便无法得知你访问的是Netflix域名，即便你使用全局代理也无法观看，除非这个代理服务器把所有相关ip列入Netflix规则中（此规则非Clash的分流规则）。
> > > > > 如果你的代理服务器是原本就可以观看Netflix的（所谓原生节点），那么无论代理客户端以ip还是域名发起请求都可以观看，所以全局代理也一定可以。
> > > > 
> > > > 
> > > > 是的，我之前netflix被检测代理，关注连接发现就是直接向8.8.8.8以TCP方式53端口发起DNS查询，后来机场主动调整后，就可以正常看了，在这种情况下，把电视机设定规则全走代理反而会被认定使用代理，正常走奈飞策略组就可以正常观看，谢谢讲解。
> > > 
> > > 
> > > 你也是用火棒么？ [TG私聊](https://t.me/Masstone)交流一下啊
> > 
> > 
> > 我是LG电视机的webos，我加你了
> 
> 好像没收到。。怎么回事

username：ngvinhman再试试你加我 我不会你发的那个链接

**Comment by sun5025** [comment]
> > > > > 如果通过设定电视机的所有流量走代理可否？
> > > > 
> > > > 
> > > > 不一定可以，原因如下：
> > > > 如果你使用的代理服务器是DNS解锁的服务器（通俗解释：基于来源请求的域名判断，将访问Netflix的请求通过另一个原本就能观看Netflix的服务器进行代理）
> > > > 那么就要求代理客户端（如 Clash）以域名的方式发起TCP请求，Clash默认是以域名发起请求，
> > > > 但Clash得知请域名的前提是，Netflix APP端以域名的方式发起请求，并且Clash DNS解析过相应的域名，留下了ip与域名的映射关系。
> > > > 但个别盒子比如firestick则直接向8.8.8.8以TCP方式53端口发起DNS查询，然后发起对ip的请求，即便劫持8.8.8.8到Clash DNS，由于Clash不具备解析tcp dns请求的能力（游戏内核除外），这种情况下Clash便无法得知ip与域名的对应关系，只能同样以ip的方式建立和代理服务器的链接，此时你的代理服务器便无法得知你访问的是Netflix域名，即便你使用全局代理也无法观看，除非这个代理服务器把所有相关ip列入Netflix规则中（此规则非Clash的分流规则）。
> > > > 如果你的代理服务器是原本就可以观看Netflix的（所谓原生节点），那么无论代理客户端以ip还是域名发起请求都可以观看，所以全局代理也一定可以。
> > > 
> > > 
> > > 是的，我之前netflix被检测代理，关注连接发现就是直接向8.8.8.8以TCP方式53端口发起DNS查询，后来机场主动调整后，就可以正常看了，在这种情况下，把电视机设定规则全走代理反而会被认定使用代理，正常走奈飞策略组就可以正常观看，谢谢讲解。
> > 
> > 
> > 你也是用火棒么？ [TG私聊](https://t.me/Masstone)交流一下啊
> 
> 我是LG电视机的webos，我加你了

我的也是LG电视 也有这个问题 请问怎么解决的？

**Comment by vernesong** [comment]
可以装个smartdns劫持dns，openclash关闭劫持做smartdns的上游

**Comment by vernesong** [comment]
或者使用游戏模式

**Comment by ingnelson** [comment]
@vernesong Is it possible you create a server to bypass my ISP firewall , please ? I can pay you via Bitcoin .

My telegram : https://t.me/Trader_Nelson.
Or send me a way to contact you, please.

**Comment by cdjoep** [comment]
我的火棒碰到了同样的问题，在其他设备观看Netflix都是正常，只有火棒被检测代理，最后更换了第三方规则：ConnersHua，完美解决。

**Comment by Jewel591** [comment]
如果你已经拥有了一台 VPS，但却被 Netflix 检测到代理而无法观看。不用担心，我们提供专业的解锁服务：[Netflix 任意 VPS 解锁](https://item.taobao.com/item.htm?id=624020898466)
每台 VPS 20 RMB，不限时间，永久解锁。

**Comment by gz0007** [comment]
> 我的火棒碰到了同样的问题，在其他设备观看Netflix都是正常，只有火棒被检测代理，最后更换了第三方规则：ConnersHua，完美解决。

我开第三方规则：ConnersHua还是不行,客户端是 shield tv.

**Comment by gz0007** [comment]
> 我的火棒碰到了同样的问题，在其他设备观看Netflix都是正常，只有火棒被检测代理，最后更换了第三方规则：ConnersHua，完美解决。

我开第三方规则：ConnersHua还是不行,客户端是 shield tv.
