### ISSUE TITLE
clash.meta开启流量探测后, macos系统下无法访问google youtube

### ISSUE THREAD

**Issue by shetz163** [vernesong/OpenClash#2300]
在macos下访问google和youtube的时候，无法加载页面，在yacd里面 连接 可以看到已断开分类下有好多 proxy选择的节点的sni地址，但其他的windows和android都可以正常访问，连接这个分类下也可以看到正确的连接网址，android tv下的netflix使用的oca.nflxvideo.net地址也是正确的显示在这里的。

我需要怎么样去排查这个问题是出在哪里呢？

**Comment by vernesong** [comment]
日志会有提示

**Comment by QuentinHsu** [comment]
将 ` 'google.com'` 加入到【强制探测（嗅探）域名列表】里再试试？
