### ISSUE TITLE
openwrt的openclash，能代理局域网外的设备吗?

### ISSUE THREAD

**Issue by Curtain-c** [vernesong/OpenClash#2302]
openwrt的openclash，能代理局域网外的设备吗.
就是局域网外的设备，通过openwrt的openclash访问外网.
我的openwrt有ipv6和域名，可以外网访问.
我主要是想让国内云服务器，通过家里的openwrt访问外网，
最好是通过域名➕端口的方式代理
但是我直接填进去域名+7890或者7893不行.
我的openwrt是旁路由，没有wan口，lan口所有的防火墙都关了
求指点

**Comment by vernesong** [comment]
http和socks5
