### ISSUE TITLE
Meta里的强制嗅探怎么设置？

### ISSUE THREAD

**Issue by wangjianpro999** [vernesong/OpenClash#2309]
force-domain: 
#  - '+.Instagram.com'
这样对吗？
这个#是注释号吗？需要去掉吗？空格呢？
完整的例子是怎样的？求教了

**Comment by vernesong** [comment]
#是注释
格式跟rules一样

**Comment by wangjianpro999** [comment]
> #是注释 格式跟rules一样

请给我完整样例，非常感谢

**Comment by cicai1631** [comment]
我也不会设置，希望开发者照顾下菜鸟。
