### ISSUE TITLE
请问提示这些错误应该怎么解决？/libmbedcrypto.so.3 /libmbedtls.so.12 /libmbedx509.so.0

### ISSUE THREAD

**Issue by iJayscn** [vernesong/OpenClash#231]
root@CC:/tmp# opkg install luci-app-openclash_0.36.9-beta_all.ipk --force-depends
Installing luci-app-openclash (0.36.9-beta) to root...
Installing libmbedtls12 (2.16.5-1) to root...
Downloading http://downloads.openwrt.org/snapshots/packages/mipsel_24kc/base/libmbedtls12_2.16.5-1_mipsel_24kc.ipk
Collected errors:
 * check_data_file_clashes: Package libmbedtls12 wants to install file /usr/lib/libmbedcrypto.so.3
	But that file is already provided by package  * libmbedtls
 * check_data_file_clashes: Package libmbedtls12 wants to install file /usr/lib/libmbedtls.so.12
	But that file is already provided by package  * libmbedtls
 * check_data_file_clashes: Package libmbedtls12 wants to install file /usr/lib/libmbedx509.so.0
	But that file is already provided by package  * libmbedtls
 * opkg_install_cmd: Cannot install package luci-app-openclash.

**Comment by vernesong** [comment]
```
opkg install luci-app-openclash_0.36.9-beta_all.ipk
```
看下缺什么依赖
