### ISSUE TITLE
Yacd 控制面板,密码中有@时，@被编码，无法登录，测试了，换了其他的就可以，不知道是不是bug

### ISSUE THREAD

**Issue by loohalh** [vernesong/OpenClash#2311]
<img width="1301" alt="image" src="https://user-images.githubusercontent.com/16890588/164982478-137ee79a-14db-4db3-abd1-5b455da3a831.png">

**Comment by vernesong** [comment]
联系作者

**Comment by loohalh** [comment]
> 联系作者

好的
