### ISSUE TITLE
更新客户端时意外丢失，出现以下错误提示

### ISSUE THREAD

**Issue by anjue39** [vernesong/OpenClash#2320]
No page is registered at '/admin/services/openclash/settings'.
If this url belongs to an extension, make sure it is properly installed.
If the extension was recently installed, try removing the /tmp/luci-indexcache file.

**Comment by vernesong** [comment]
重启

**Comment by anjue39** [comment]
重启路由器还是重启openclash？重启路由器，openwrt后台菜单中再也不见openclash踪影



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: vernesong ***@***.***&gt;
发送时间: 2022年4月26日 02:54
收件人: vernesong/OpenClash ***@***.***&gt;
抄送: anjue39 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [vernesong/OpenClash] 更新客户端时意外丢失，出现以下错误提示 (Issue #2320)





 
重启

**Comment by anjue39** [comment]
还是以前的老问题，在线旧版本升级客户端，识别不了内核



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: vernesong ***@***.***&gt;
发送时间: 2022年4月26日 02:54
收件人: vernesong/OpenClash ***@***.***&gt;
抄送: anjue39 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [vernesong/OpenClash] 更新客户端时意外丢失，出现以下错误提示 (Issue #2320)





 
重启
