### ISSUE TITLE
ipv6的想法

### ISSUE THREAD

**Issue by jackadam1981** [vernesong/OpenClash#2321]
现在ipv6已经发展的差不多了，v6上面也有墙了。

但是clash如果做双栈支持，技术曲线和工作强度都会增加。

大家是怎么处理IPV6的呢？

我现在在考虑openclash做旁路有吧，否则很多IPV6的业务处理不了。

但是或许有个好的解决方案来进行双栈过渡：
给IPV6一个白名单。
白名单的可以使用IPV6解析，不在白名单的，就使用IPV4。
毕竟ipv6地址太多了，现在也不知道分配是什么原则，我们的服务端也还是v4,想直接V6太难了。
但是白名单似乎就比较容易实现了，就像允许IPv6类型DNS解析这个功能一样，变为允许一部分IPV6解析出来。
慢慢的再逐步维护一个ipv6域名策略集。应该是现在最优的解决方案了。

**Comment by InsOnYou** [comment]
一直都在用ipv6，没有出过问题

**Comment by jackadam1981** [comment]
![image](https://user-images.githubusercontent.com/28656671/165432460-e293951d-8c9f-4f19-b63b-3a28d10ac059.png)
1.1是没装openclash的。
1.9是装了openclash，默认设置的。
一旦我使用1.9，openclash全局透明翻，那就无法解析IPV6了。更别提什么访问了。
ddns还需要ipv6解析接口服务器呢。

**Comment by malikshi** [comment]
can someone share `uci show dhcp.lan`

**Comment by jackadam1981** [comment]
![image](https://user-images.githubusercontent.com/28656671/165465539-f08dfadc-a0df-4e5c-a139-e178a6a196c1.png)
![image](https://user-images.githubusercontent.com/28656671/165465628-81f30f29-ad3d-449c-9ab0-a2a076b4ec68.png)

**Comment by jackadam1981** [comment]
现在的用法是这样的
主路由openWRT，正确配置ipv，slaac，dhcpv6   192.168.1.1
旁路由openwrt+openclash，只有一个LAN口，IPV4，无IPV6配置，192.168.1.9

其他设备，都从1.1dhcp获取IP地址，ipv4 ipv6 ，正常上网，包括各个内部服务器。
日常操作的设备，使用powershell脚本进行切换：

**Comment by jayolim** [comment]
尝试过了，放弃了。ikuai主路由获取V6前缀，V6 DHCP，OP旁路由，用OP的IVP6本地回环地址作为DNS的话网通但无法解析V6，如果用运营商下发的DNS的话直接无法打开奈飞。

**Comment by jackadam1981** [comment]
> 尝试过了，放弃了。ikuai主路由获取V6前缀，V6 DHCP，OP旁路由，用OP的IVP6本地回环地址作为DNS的话网通但无法解析V6，如果用运营商下发的DNS的话直接无法打开奈飞。

所以我写脚本切换网关，切换DNS，开启禁用IPV6。
翻墙就v4，且只有V4.

**Comment by loohalh** [comment]
> > 尝试过了，放弃了。ikuai主路由获取V6前缀，V6 DHCP，OP旁路由，用OP的IVP6本地回环地址作为DNS的话网通但无法解析V6，如果用运营商下发的DNS的话直接无法打开奈飞。
> 
> 所以我写脚本切换网关，切换DNS，开启禁用IPV6。 翻墙就v4，且只有V4.

最好是能在openwrt中统一用脚本处理

**Comment by hcym** [comment]
用一直可以的，就是lan口必需关闭，不影响wan口

**Comment by jackadam1981** [comment]
影响传统IPV4内网服务器使用IPV6直接访问，所以我clash跑旁路由。

好在我的DHCP比较给力，分别分配不同的网关。
![image](https://user-images.githubusercontent.com/28656671/165670365-f8a5e158-2bce-4148-a20d-2fdee3fa6546.png)

**Comment by jackadam1981** [comment]
> > > 尝试过了，放弃了。ikuai主路由获取V6前缀，V6 DHCP，OP旁路由，用OP的IVP6本地回环地址作为DNS的话网通但无法解析V6，如果用运营商下发的DNS的话直接无法打开奈飞。
> > 
> > 
> > 所以我写脚本切换网关，切换DNS，开启禁用IPV6。 翻墙就v4，且只有V4.
> 
> 最好是能在openwrt中统一用脚本处理

所以我考虑的解决方案是设立IPV6白名单，这个就可以返回IPV6的DNS，不走clash，直接联通。
现阶段，46共存，过渡期会很漫长的。

**Comment by jackadam1981** [comment]
想了想，我网关指定clash，只切换dns就可以实现我的目标了。
下午试试看。

**Comment by cs-star** [comment]
> 这样的 主路由openwrt，配置ipv，slaac，dhWRT6 19268.1.现在IPV1是正确的， 由openwrt+openclash，一个LAN口，IPV4，无V6配置，192.168.1.9
> 
> 日常操作的设备，使用powershell都从1.1dhcp获取ipv4 ipv6 ipv6，正常上网，其他地址，IP进行内部切换。
> 
> 另存为PS1脚本，在管理员powershell脚本中执行
> 
> netsh interface ip set dns "WLAN" static 192.168.1.199 255.255.255.0 192.168.1.9 #静态设置地址，指定IPV4，只翻墙网关。 netsh interface ip set dns "WLAN" static 192.168.1.9 #netsh interface设置DNS，强制使用clash来进行解析，不会返回v6地址 disable -name "WLAN" -componentid ms_tcpip6 #禁止WLAN的IPv6 ipconfig /flushdn #刷新dns缓存，避免缓存干扰。
> 
> IP 网关，IPV4，IPV6+IP 网关。 enable-netadapbinding -Name "WLAN" -componentid ms_tcpip6 #启用WLAN的IPv6 netsh interface ip set address WLAN source=dhcp设置DHCP模式 netsh interface ipv4 set dns "WLAN " dhcp设置为获取即DNS请求#通过DNS配置#/刷新DHCPdns 缓存，避免缓存中断。

www.nivod.tv  比如这网站 开了ipv6打不开 ip4正常 不知道怎么处理
