### ISSUE TITLE
Google TV， Openwrt软路由做为主路由，hello world为科学上网插件，Google TV可以正常联网，但是使用Openclash后就不能正常联网了

### ISSUE THREAD

**Issue by dalydeng** [vernesong/OpenClash#2324]
软路由的设置如下：把time.android.com劫持到 203.107.6.88(阿里云的ntp服务器)，使用Hello world能解决原生安卓时间不对的问题。
具体步骤：openwrt---网络----dhcp/dns----host和解析文件拉到最下边----自定义挟持域名或者自定义dns解析
但是发现使用openclash后这个就不起作用了，Google TV就无法联网了。请大家帮我看下，为啥使用Openclash，在DHCP/DNS设置的劫持就不起作用了。

**Comment by kingsey** [comment]
在openclash里设置，dns解析正常来说是被劫持到openclash里处理的。

**Comment by dalydeng** [comment]
> 在openclash里设置，dns解析正常来说是被劫持到openclash里处理的。

您可以说下在openclash里哪个位置设置的吗？

**Comment by Hokia** [comment]
> 

打开Openclash的页面——全局设置——DNS设置，拉到最下边在“设置自定义 Hosts（不会覆盖配置文件设置）“中添加如下保存即可。
'time.android.com': 203.107.6.88

**Comment by Hokia** [comment]
> > 在openclash里设置，dns解析正常来说是被劫持到openclash里处理的。
> 
> 您可以说下在openclash里哪个位置设置的吗？

打开Openclash的页面——全局设置——DNS设置，拉到最下边在“设置自定义 Hosts（不会覆盖配置文件设置）“中添加如下保存即可。
'time.android.com': 203.107.6.88

**Comment by dalydeng** [comment]
好的，我试一下，谢谢哈

**Comment by realityeditors** [comment]
这个我是试过了

> > > 在openclash里设置，dns解析正常来说是被劫持到openclash里处理的。
> > 
> > 
> > 您可以说下在openclash里哪个位置设置的吗？
> 
> 打开Openclash的页面——全局设置——DNS设置，拉到最下边在“设置自定义 Hosts（不会覆盖配置文件设置）“中添加如下保存即可。 'time.android.com': 203.107.6.88

解决了～

**Comment by sion516516** [comment]
> > > 在openclash里设置，dns解析正常来说是被劫持到openclash里处理的。
> > 
> > 
> > 您可以说下在openclash里哪个位置设置的吗？
> 
> 打开Openclash的页面——全局设置——DNS设置，拉到最下边在“设置自定义 Hosts（不会覆盖配置文件设置）“中添加如下保存即可。 'time.android.com': 203.107.6.88

请问我现在更新后的clash怎么劫持？DNS设置里面没有自定义hosts这个选项了啊？

**Comment by kklkkLYX** [comment]
> > > > 在openclash里设置，dns解析正常来说是被劫持到openclash里处理的。
> > > 
> > > 
> > > 您可以说下在openclash里哪个位置设置的吗？
> > 
> > 
> > 打开Openclash的页面——全局设置——DNS设置，拉到最下边在“设置自定义 Hosts（不会覆盖配置文件设置）“中添加如下保存即可。 'time.android.com': 203.107.6.88
> 
> 请问我现在更新后的clash怎么劫持？DNS设置里面没有自定义hosts这个选项了啊？

<img width="584" height="451" alt="Image" src="https://github.com/user-attachments/assets/84765037-4884-4a27-9916-e1f4de221811" />

<img width="777" height="194" alt="Image" src="https://github.com/user-attachments/assets/71e637dc-776a-45bb-96c8-de9fb93e4da5" />

<img width="853" height="573" alt="Image" src="https://github.com/user-attachments/assets/2bc38c10-f36e-48d9-9668-173fc288cc53" />
希望可以帮到你
