### ISSUE TITLE
路由被植入挖矿程序 （注意：在线订阅转换存在隐私泄露风险）

### ISSUE THREAD

**Issue by jeasonliang** [vernesong/OpenClash#2325]
#大家查查自己的路由进程有没有到这个**fr.minexmr.com:4444**链接
前几天出差，昨晚回家发现网速很慢，登陆luci页面 提示密码错误，哎呀！没办法转到esxi后台 进入路由 直接passwd更改密码，然后reboot了。。。然后登陆路由发现cpu占用一直100%，好家伙，**给黑了？**top一查，如下：
/bin/dhpcd 占用那么高 绝对不是我自己安装的，
![Snipaste_2022-04-27_08-33-52](https://user-images.githubusercontent.com/27670071/165416703-e9c40b67-c4e4-4545-87c0-e2d3e7791746.png)
然后打开计划任务一查，如下：
![Snipaste_2022-04-27_08-31-35](https://user-images.githubusercontent.com/27670071/165416818-092c850d-a202-481f-9569-e291344462ed.png)
![Snipaste_2022-04-27_08-40-23](https://user-images.githubusercontent.com/27670071/165416904-d1a38c9b-d674-4334-a4a6-a64508b8f56e.png)

动手清理完，先观察观察，插件我就安装了以下几个
![Snipaste_2022-04-27_08-57-52](https://user-images.githubusercontent.com/27670071/165417187-988e1fc1-0798-4704-b5e2-684a90356683.png)
以上还是我自己利用sdk 自行编译的 ，固件是官方的！防火墙NAT也检查了 没问题！唯一问题就是刚玩clash，以前都是玩ssr-plus！（在此说明，不是说clash不好和有漏洞！）唯一的可能是订阅时候使用了第三方在线订阅转换，不知道有没有和我类似的朋友！还有各位出点主意帮我想下哪里还要检查，以防残余后门！谢谢！

**Comment by weilai-all** [comment]
我倒是觉得跟你说的没关系，很久以前也被扫过，只要你暴露在公网还是弱密码，被扫几率很大。如果不需要公网访问openclash，可以勾选仅允许内网，如果需要就得把密码设置复杂点，包括路由登录密码和ssh连接密码啥的。

**Comment by jackadam1981** [comment]
xmr,挖币了。

**Comment by bugparty** [comment]
这明显是针对openwrt弱密码进行的攻击
