### ISSUE TITLE
新版本openclash无法解析t.co短链接

### ISSUE THREAD

**Issue by wangjianpro999** [vernesong/OpenClash#2326]
如题，网无论是否使用meta内核，新版本的openclash均无法解析Twitter的t.co这类短链接。换成ssr+或者passwall就可以。注：同一个机场

**Comment by wangjianpro999** [comment]
反复确认，短域名无法解析！

**Comment by Karmylr** [comment]
可以

**Comment by PN62323424** [comment]
> 

你解决了吗，我也是打不开

**Comment by kingsey** [comment]
新版本openclash表示解析正常，所以是配置或者机场问题不是openclash的问题。

**Comment by PN62323424** [comment]
> 

同一个机场，cfw下是可以访问的。配置文件的话规则是一样的，具体设置的话因为openclash和cfw不完全一样所以我也不知道哪里的问题，我尝试强制远程域名解析，也是不行，能指点下不

**Comment by PN62323424** [comment]
> 同样存在这个问题，非常诡异，但经过我N次的重置固件，发现问题应该是跟 lan/wan 接口里面的 "使用内置IPV6管理" 这个勾选相关联，只要这个勾是打上的，其他ipv6相关的都禁用也没事。但只要取消勾选过一次，应用设置之后，就再也无法解析 t.co 了.
> 
> btw: 我用的是lean的lede编译的r2s，加了几个自定义源
> 
> ```
>  cat feeds.conf.default
> src-git packages https://github.com/coolsnowwolf/packages
> src-git luci https://github.com/coolsnowwolf/luci
> src-git routing https://github.com/coolsnowwolf/routing
> src-git telephony https://git.openwrt.org/feed/telephony.git
> #src-git video https://github.com/openwrt/video.git
> #src-git targets https://github.com/openwrt/targets.git
> #src-git oldpackages http://git.openwrt.org/packages.git
> #src-link custom /usr/src/openwrt/custom-feed
> src-git helloworld https://github.com/fw876/helloworld
> src-git lienol https://github.com/xiaorouji/openwrt-passwall;packages
> ```
> 
> git pull最新代码，之后使用以下命令强制覆盖feeds，不知道是否跟这个有关系（暂时也不想编译尝试了。。
> 
> ```
> ./scripts/feeds update -a && ./scripts/feeds install -f -a
> ```
> 
> 所以结论是：
> 
> `这个问题并不是由openclash带来的。。。虽然起初我也觉得是openclash，毕竟同样的代理提供商，在其他软件上是work的。。。`
> 
> 也许 @vernesong 大佬可以结案了。。
> 
> 其他使用lean固件的朋友可以试试我的操作步骤，如果存在同样的问题可以去lean的固件反馈。。。

我的情况比你更神奇，我不定期访问不了t.co，三两天可以三两天不可以，openclash期间没改过设置最多重启下

**Comment by CsHeng** [comment]
不定期的可能是节点问题，我这个是能稳定复现的步骤。。。
重置了N次，最终将选项缩小到”反勾选使用内置的IPV6管理“上，至于背后干了什么我就不清楚了。。而且蛋疼的是，出问题之后，即使重选勾选回来也并不能恢复。

**Comment by PN62323424** [comment]
> 

同样的节点，当场切换到quan x就可以访问的，应该是固件问题了

**Comment by wangjianpro999** [comment]
更新固件后貌似可以了

PN62323424 ***@***.***> 于 2022年5月15日周日 09:52写道：

**Comment by hdchieh** [comment]
我也出现了这个问题，排查一圈。发现我是被 AdguardHome 里的 Peter Lowe's Blocklist 拦截了。好蠢！

**Comment by xia080517** [comment]
我最近也出现了同样的问题，目前的clash是最近的，突然推特里的短链接就打不开了，我用的是旁路由模式，如果不用旁路由，在电脑上启动clash客户端打开短链接就正常。

**Comment by wlrsx** [comment]
当前也遇到这个问题。。使用fake-IP 或者将 t.co 指定 Nameserver-Policy 才正常访问。

**Comment by wlrsx** [comment]
不知道对不对：
当 [t.co](http://t.co/) 域名受到本地 DNS 污染：Ping 请求找不到主机 [t.co](http://t.co/)。请检查该名称，然后重试。返回 Address: 0.0.0.0 为空
openclash 使用 Fake-IP 模式，NameServer 里只有 10.10.10.1，因为 Fake-IP 会进行规则集匹配，当匹配到规则会发送到远程服务器进行DNS解析，但是如果匹配到最后的规则（白名单模式）- MATCH,Proxies，该规则导致 Fake-IP 会进行本地DNS解析，所以还是失败。
# 解决方法
# 使用 Fake-IP 并添加 t.co 规则
# Fake-IP 的 NameServer 不使用 10.10.10.1 本地 DNS 服务器
# Redir 模式不使用 10.10.10.1 本地 DNS 服务器
# Redir 模式单独指定 Nameserver-Policy：'t.co': '114.114.114.114'

**Comment by jaychoww** [comment]
> 同样存在这个问题，非常诡异，但经过我N次的重置固件，发现问题应该是跟 lan/wan 接口里面的 "使用内置IPV6管理" 这个勾选相关联，只要这个勾是打上的，其他ipv6相关的都禁用也没事。但只要取消勾选过一次，应用设置之后，就再也无法解析 t.co 了.
> 
> btw: 我用的是lean的lede编译的r2s，加了几个自定义源
> 
> ```
>  cat feeds.conf.default
> src-git packages https://github.com/coolsnowwolf/packages
> src-git luci https://github.com/coolsnowwolf/luci
> src-git routing https://github.com/coolsnowwolf/routing
> src-git telephony https://git.openwrt.org/feed/telephony.git
> #src-git video https://github.com/openwrt/video.git
> #src-git targets https://github.com/openwrt/targets.git
> #src-git oldpackages http://git.openwrt.org/packages.git
> #src-link custom /usr/src/openwrt/custom-feed
> src-git helloworld https://github.com/fw876/helloworld
> src-git lienol https://github.com/xiaorouji/openwrt-passwall;packages
> ```
> 
> git pull最新代码，之后使用以下命令强制覆盖feeds，不知道是否跟这个有关系（暂时也不想编译尝试了。。
> 
> ```
> ./scripts/feeds update -a && ./scripts/feeds install -f -a
> ```
> 
> 所以结论是：
> 
> `这个问题并不是由openclash带来的。。。虽然起初我也觉得是openclash，毕竟同样的代理提供商，在其他软件上是work的。。。`
> 
> 也许 @vernesong 大佬可以结案了。。
> 
> 其他使用lean固件的朋友可以试试我的操作步骤，如果存在同样的问题可以去lean的固件反馈。。。

运行模式从“兼容”模式切换到“混合”模式也能解决这个问题

**Comment by graysonjphoenix** [comment]
帮大家提供一个思路：/tmp/dnsmasq.d

**Comment by graysonjphoenix** [comment]
帮大家提供一个思路，也许有帮助：
1、nslookup t.co 127.0.0.1:7874 （openclash的dns解析端口）
2、nslookup t.co 127.0.0.1:5553 （adguardhome的dns解析端口，根据自己需要修改）
3、nslookup t.co 127.0.0.1:53 （dnsmasq的端口）
我的情况是前两个都能正常解析，唯独第三个不能解析。这个时候把/tmp/dnsmasq.d目录下产生的临时文件全部删掉即可。查了一下这个目录里的文件在重启之后依然会加载，可能是其他程序产生的临时配置文件

**Comment by Gnlop** [comment]
删除/tmp/dnsmasq.d下的文件重新启动即可 已解决
