### ISSUE TITLE
在多个订阅链接转换之后，配置文件就算没有变化，也会被判定有变化

### ISSUE THREAD

**Issue by Karmylr** [vernesong/OpenClash#2329]
如题。我在局域网里建了subconverter。单个订阅连接转换不会导致错误判定。两个就会了

**Comment by vernesong** [comment]
我这边没问题，看看是改了什么吧，对比使用的cmp

**Comment by Karmylr** [comment]
> 

用Notepad++对比了两次的配置文件，完全一致的

**Comment by Karmylr** [comment]
> 我这边没问题，看看是改了什么吧，对比使用的cmp

对了，要两个订阅链接同时转换才能复现的

**Comment by Karmylr** [comment]
@vernesong 发现自动更新不会出现这个bug，手动点击更新才会

**Comment by vernesong** [comment]
手动更新是强制更新，不会对比变动

**Comment by Karmylr** [comment]
原来如此
