### ISSUE TITLE
请问如何在开启绕过国内ip的情况下强制代理bilibili？

### ISSUE THREAD

**Issue by Blacklw** [vernesong/OpenClash#2332]
请问如何在开启绕过国内ip的情况下强制代理bilibili？相关的强制代理入口在哪个位置呢？

**Comment by Lixuhuilll** [comment]
编写clash代理规则 ，添加一条bilibili的代理就行

**Comment by Blacklw** [comment]
> 只要是工作在规则模式下，clash就会按照配置文件里面设置的规则，来对网站做匹配 。

先谢谢您的回答。其实clash的规则我一直都是有写bilibili的，但是主要问题好像不是出现在规则，是因为开了绕过国内ip，一碰到bilibili就跳出去不走clash了，merlin的时候也是这样，但是merlin有个强制代理白名单的设置入口，而在openclash里面我找了很久都没有相关的设置入口，所以就想说求助一下能怎么设置

**Comment by Blacklw** [comment]
> 编写clash代理规则 ，添加一条bilibili的代理就行
![1651494178(1)](https://user-images.githubusercontent.com/75933358/166237726-a01d5518-e0f2-4c61-b536-2a5edb244d5c.jpg)
![1651495200(1)](https://user-images.githubusercontent.com/75933358/166237737-568aed62-4789-43ee-ac88-005f2d6a2a8e.jpg)
![1651495819(1)](https://user-images.githubusercontent.com/75933358/166237753-7cfbe12f-cc3d-4c3b-9dc2-ff8fdb200bd8.jpg)
图二那里我不管添不添加都一样，只要开了绕过国内ip，bilibili相关的都不会走openclash

**Comment by mingxiaoyu** [comment]
同问

**Comment by Karmylr** [comment]
扭曲
