### ISSUE TITLE
游戏规则列表全部下载失败

### ISSUE THREAD

**Issue by cnfjice** [vernesong/OpenClash#2333]
![微信截图_20220429164634](https://user-images.githubusercontent.com/44722003/165912801-510efb29-ed87-4b60-9f97-f56af37f9d5e.jpg)

**Comment by hbin** [comment]
+1

**Comment by hbin** [comment]
找到方法：
1. 到 https://github.com/FQrabbit/SSTap-Rule 下载规则解压
2. 把解压的文件放到 /etc/openclash/game_rules 目录即可

**Comment by cnfjice** [comment]
> 找到方法：
> 
> 1. 到 https://github.com/FQrabbit/SSTap-Rule 下载规则解压
> 2. 把解压的文件放到 /etc/openclash/game_rules 目录即可

是的，我已经按这样做了，测试了几天发现这规则也不是很准。
