### ISSUE TITLE
GeoSite 数据库下载失败

### ISSUE THREAD

**Issue by pengcu** [vernesong/OpenClash#2335]
更新后 GeoSite  数据库下载失败，请问是否可以手动下载然后上传到系统中呢？
上传到什么路径下呢？

**Comment by pengcu** [comment]
我上传到 `/tmp/geosite.dat` 解决了

**Comment by touzi** [comment]
我也上传到了这个路径, 但还是需要下载并且下载失败

**Comment by touzi** [comment]
> 说一下我的解决方法：
> 
> `ps | grep clash `
> 
> 然后发现它运行了这个脚本下载数据库：
> 
> `cat /usr/share/openclash/openclash_geosite.sh`
> 
> 然后手动下载然后复制了过去，启动成功了：
> 
> `wget https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat`
> 
> `cp geosite.dat /etc/openclash/GeoSite.dat`

很好的方法, 我之前手动复制进去后忽略了文件名的大小写, 注意 GeoSite.dat 需要大小写才能被程序识别.

**Comment by ShanZJ-gvs** [comment]
> 

请问wget时有没有出现连接失败，百度了说加什么参数，加了还是不行.....
`wget https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat --no-check-certificate
--2022-05-27 13:28:39--  https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat
Resolving cdn.jsdelivr.net... 151.101.73.229, 2a04:4e42:1a::485
Connecting to cdn.jsdelivr.net|151.101.73.229|:443... connected.
Unable to establish SSL connection.
`

**Comment by ShanZJ-gvs** [comment]
> 

请问wget时有没有出现连接失败，百度了说加什么参数，加了还是不行.....
`wget https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat --no-check-certificate
--2022-05-27 13:28:39--  https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat
Resolving cdn.jsdelivr.net... 151.101.73.229, 2a04:4e42:1a::485
Connecting to cdn.jsdelivr.net|151.101.73.229|:443... connected.
Unable to establish SSL connection.
`

**Comment by touzi** [comment]
这个域名被污染了，你直接从GitHub下载吧

**Comment by ShanZJ-gvs** [comment]
> 这个域名被污染了，你直接从GitHub下载吧

谢谢，我本机架梯子然后下载了传过去啦

**Comment by teli5200** [comment]
现在还有这个问题，一直没有办法更新，所以经常服务起不来
