### ISSUE TITLE
如何进一步在代理集 Proxy Group 中过滤服务器节点？

### ISSUE THREAD

**Issue by dayunliang** [vernesong/OpenClash#2336]
<img width="2300" alt="image" src="https://user-images.githubusercontent.com/36461319/166091460-2707dc5e-8997-4762-97ae-474e310c0b96.png">

如图中所示想把红框中的游戏节点过滤掉，怎么做呢？谢谢！

**Comment by dayunliang** [comment]
有人可以帮忙回答下吗？

**Comment by kingsey** [comment]
Proxy Group是策略组不是代理集，过滤节点一般要经过订阅转换。
