### ISSUE TITLE
强制安装 kmod-inet-diag 失败   v0.45.12， openwrt 70o+

### ISSUE THREAD

**Issue by laozhang123456** [vernesong/OpenClash#2341]
* pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.112-1-f03ff259ae29fbdcbee719356718adbc) for kmod-inet-diag
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-inet-diag found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package kmod-inet-diag.

**Comment by hcym** [comment]
这玩意只能编译时就加上，后期安装kmod基本都是失败

**Comment by shu0802** [comment]
最新版订阅信息提示获取失败
![image](https://user-images.githubusercontent.com/43750373/166133953-6584633c-f08e-442c-b0e0-5391f1713aee.png)
