### ISSUE TITLE
redir模式下ipv6时有时无

### ISSUE THREAD

**Issue by topsite** [vernesong/OpenClash#2344]
fakeip下无任何问题，但是切换到redir模式下，ipv6一会有一会没有，一会电脑上有手机wifi没有，一会手机wifi有，电脑上没有，怎么调整都不行。

**Comment by vernesong** [comment]
ipv6要改设备网关DNS为路由地址

**Comment by topsite** [comment]
> ipv6要改设备网关DNS为路由地址

问题解决，感谢。

**Comment by Actuallymax** [comment]
> 

怎么改的可以截图看看吗？

**Comment by lengxii** [comment]
怎么改的可以截图看看吗？
