### ISSUE TITLE
0.45.13-beta这个版本，用meta会报错

### ISSUE THREAD

**Issue by Karmylr** [vernesong/OpenClash#2345]
![image](https://user-images.githubusercontent.com/69903376/166229630-3f86c84a-44ca-4c60-a89f-4153a85a0fea.png)

**Comment by MetaCubeX** [comment]
内核更了没

**Comment by Karmylr** [comment]
> 内核更了没

更新了

**Comment by topsite** [comment]
确实报错，需要关闭嗅探。

**Comment by topsite** [comment]
更新内核就好了，不更新的话就会提示关闭嗅探。
