### ISSUE TITLE
奈飞播放多集后出现断流

### ISSUE THREAD

**Issue by matthuo333** [vernesong/OpenClash#2347]
使用最新版openclash,以及使用dev 和 tun最新内核。经由fire tv 播放多集奈飞后，出现断流，通过面板看不到奈飞流量。
网络拓扑采用旁路由。

**Comment by vernesong** [comment]
开流媒体增强了吗

**Comment by matthuo333** [comment]
> 开流媒体增强了吗

开了。
另外，仅从火棒换到gtv ，测试一上午，没发现同样问题。

**Comment by vernesong** [comment]
看看断流前是不是自动切换节点了

**Comment by matthuo333** [comment]
> 看看断流前是不是自动切换节点了

应该没有自动切换。因为是手动select设置的代理.
另外，大神能推荐下空口抓包的工具，我从fire tv无线侧，进clash前抓下报文。
