### ISSUE TITLE
在wan口中继模式下redir模式丢失ipv6

### ISSUE THREAD

**Issue by topsite** [vernesong/OpenClash#2350]
上级路由器是一台插手机卡的CPE，然后接了一个r4s。如果用fakeip模式，ipv6完全没问题。切换到redir模式后，无论怎么更改lan口和wan口的模式都无法显示出ipv6，求解。
[https://s3.bmp.ovh/imgs/2022/05/03/87bf4a1d53ad4626.png](url)
[https://s3.bmp.ovh/imgs/2022/05/03/25b7e98bfecd39c6.png](url)

**Comment by topsite** [comment]
找到原因了，原来用r4s用redir tun就没有ipv6，换了x86就没问题了，请问如何解决r4s的问题呢。

**Comment by malikshi** [comment]
+1 Same issues.
