### ISSUE TITLE
Can't open luci with openwrt-22.03 with today build version Openclash

### ISSUE THREAD

**Issue by MatJeheyy** [vernesong/OpenClash#2351]
/usr/lib/lua/luci/controller/openclash.lua:93: module 'luci.model.ipkg' not found:
	no field package.preload['luci.model.ipkg']
	no file './luci/model/ipkg.lua'
	no file '/usr/share/lua/luci/model/ipkg.lua'
	no file '/usr/share/lua/luci/model/ipkg/init.lua'
	no file '/usr/lib/lua/luci/model/ipkg.lua'
	no file '/usr/lib/lua/luci/model/ipkg/init.lua'
	no file './luci/model/ipkg.so'
	no file '/usr/lib/lua/luci/model/ipkg.so'
	no file '/usr/lib/lua/loadall.so'
	no file './luci.so'
	no file '/usr/lib/lua/luci.so'
	no file '/usr/lib/lua/loadall.so'
stack traceback:
	[C]: in function 'require'
	/usr/lib/lua/luci/controller/openclash.lua:93: in main chunk
	[C]: in function 'require'
	/usr/lib/lua/luci/dispatcher.lua:1131: in function 'createindex'
	/usr/lib/lua/luci/dispatcher.lua:1232: in function 'createtree'
	/usr/lib/lua/luci/dispatcher.lua:635: in function 'menu_json'
	/usr/lib/lua/luci/dispatcher.lua:884: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:479: in function </usr/lib/lua/luci/dispatcher.lua:478>

**Comment by pikachullk** [comment]
luci-compat include？

**Comment by vernesong** [comment]
fix in 0.45.15

**Comment by jeasonliang** [comment]
#2294
