### ISSUE TITLE
请求答疑

### ISSUE THREAD

**Issue by Johnsnow-s** [vernesong/OpenClash#2352]
* pkg_hash_fetch_best_installation_candidate: Packages for kmod-nf-log found, but incompatible with the architectures configured
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-nf-log6 found, but incompatible with the architectures configured
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-nft-compat found, but incompatible with the architectures configured
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-nf-tproxy found, but incompatible with the architectures configured

安装完ipk之后出现如上提示，打开openclash拒绝访问

**Comment by topsite** [comment]
为什么要自己装呢，固件都集成啊，就算没有集成，用自带的软件库装就行了。

**Comment by Johnsnow-s** [comment]
我找来找去都没找到适合LEDE X64 openclash软件V2.37版本，基本都是用不了的

**Comment by Johnsnow-s** [comment]
> 为什么要自己装呢，固件都集成啊，就算没有集成，用自带的软件库装就行了。

我找来找去都没找到适合LEDE X64 openclash软件V2.37版本，基本都是用不了的

**Comment by vernesong** [comment]
不支持koolshare

**Comment by pikachullk** [comment]
> > 为什么要自己装呢，固件都集成啊，就算没有集成，用自带的软件库装就行了。
> 
> 我找来找去都没找到适合LEDE X64 openclash软件V2.37版本，基本都是用不了的

这怕得是个上古版本了吧。。。。哪还有LEDE啊现在
