### ISSUE TITLE
无法在play商店下载。可以浏览。使用clash可以正常下载。就是openclash不行

### ISSUE THREAD

**Issue by yunxuan910** [vernesong/OpenClash#2356]
无法在play商店下载。可以浏览。使用clash可以正常下载。就是openclash不行。

**Comment by cc9014** [comment]
可能是规则的问题，先开全局试试

**Comment by yunxuan910** [comment]
最后确定应该是模式问题。换到fakeip模式后再重新下载规则就能正常下载了。应该全部换了模式。

Chao Chen ***@***.***> 于2022年5月7日周六 22:31写道：
