### ISSUE TITLE
Fake-IP模式下如何设置排除特定内网IP设备不经过Openclash？

### ISSUE THREAD

**Issue by TimKKLYT** [vernesong/OpenClash#2358]
在Fake-IP模式下，想要让特定内网IP设备不是走openclash直连、而是该流量直接跳过openclash，请问该怎么设定？

已经参考过[#169](https://github.com/vernesong/OpenClash/issues/169)的做法
![image](https://user-images.githubusercontent.com/91398728/167241027-55bd1fe4-7818-4380-9d3c-b48262098ded.png)
在这个页面内新增以下指令
iptables -t nat -I openclash -s 172.16.0.240/32 -j RETURN
iptables -t mangle -A openclash -s 172.16.0.240/32 -j RETURN

但不论在Fake-IP(增强)、Fake-IP(TUN)、Fake-IP+Meta内核的这几个模式下，都还是可以在Openclash的Dashboard 控制面板界面看到IP 172.16.0.240还是经过了Openclash

请问我是要在Openclash内进行其他设定？还是在这二个地方进行什么什么设定呢？
![image](https://user-images.githubusercontent.com/91398728/167241235-67ea3dfc-d827-419b-aa51-4e1ccaa48fd3.png)
![image](https://user-images.githubusercontent.com/91398728/167241242-da1158fa-62e3-46fe-aa3c-94a28c4767af.png)

**Comment by vernesong** [comment]
用增强模式，另外再开一个DNS服务，将DNS转过去

**Comment by TimKKLYT** [comment]
> 用增强模式，另外再开一个DNS服务，将DNS转过去

谢谢回复。
我还在努力学习openwrt系统的很多东西，但还是很多地方不是很懂。

请问新开一个DNS服务，是指“设置自定义上游 DNS 服务器”这个选项吗？
![image](https://user-images.githubusercontent.com/91398728/167292966-04bc162b-4e7b-46bb-b450-1a1d2e9e3806.png)


也再请问一下，
新开的DNS是指向电信商的DNS吗？
如何只让指定的内网IP走新增的DNS？ 因为不想让电信商的DNS污染了其他设备的上网环境

问题有点多，先谢谢你的耐心观看

**Comment by jayling1111** [comment]
相同的问题，请求大神答疑，目前fakeip速度稳定又快。但是当pt下载的时候，流量会经过ooenclash，连接数过大，导致CPU占用拉满，在redict模式下满速才30，需求是在fakeip模式下指定下载机不走opc内核

**Comment by eightsheep67** [comment]
我用FakeIP增强模式，莫名奇妙米家部分设备（空调伴侣，屏幕挂灯）就会离线，关闭openclash就立马上线。
我把家里需要科学的设备都固定IP在192.168.1.1~100内，然后其他设备我让DHCP服务器从192.168.129开始分配。
尝试1：openclash规则设置里，设置128~255网段直连，命令：- SRC-IP-CIDR,192.168.1.128/25,DIRECT，在控制面板看规则应用了，但是还是会设备离线，无效
尝试2：redir模式启动后使用以下命令：iptables -t nat -I openclash -s 192.168.1.128/25 -j RETURN，在控制面板仍然看到被排除的网段连接，无效
尝试3：FakeIP增强模式下，我开了smartdns并运行，然后用一下命令：
iptables -t nat -I openclash -s 192.168.1.128/25 -j RETURN
iptables -t nat -I PREROUTING -s 192.168.1.128/25 -p udp --dport 53 -j REDIRECT --to-ports 6053
iptables -t nat -I PREROUTING -s 192.168.1.128/25 -p tcp --dport 53 -j REDIRECT --to-ports 6053
在控制面板仍然看到被排除的网段连接，无效

更改命令后重启过防火墙也重启了openwrt，均无效，求大佬指导一下。

**Comment by eightsheep67** [comment]
终于发现问题了，我关闭掉所有的规则后，仔细看了一下连接，发现我掉线的几个设备都连接到一个叫Mijia Cloud:443的地址，然后我设置- DOMAIN-KEYWORD,Mijia,DIRECT后设备就正常上线了……

**Comment by eightsheep67** [comment]
Mijia Cloud:443这个问题解决了，原来meta内核自定义嗅探设置里就有，打开就行了。
skip-domain:
  - 'Mijia Cloud'
  - 'dlg.io.mi.com'
  - '+.apple.com'
  - '+.jd.com'

**Comment by cicai1631** [comment]
> 



> Mijia Cloud:443这个问题解决了，原来meta内核自定义嗅探设置里就有，打开就行了。
> 
> ```
> skip-domain:
>   - 'Mijia Cloud'
>   - 'dlg.io.mi.com'
>   - '+.apple.com'
>   - '+.jd.com'
> ```
只能定群晖ip:端口？
只直连群晖ip
代理群晖ip：端口，这样可以？

**Comment by xibaluo** [comment]
我也碰到了同样的问题，楼主解决没？

**Comment by xibaluo** [comment]
我大概明白了，加iptable不生效的原因，是因为openwrt新固件改用nftable了吧。

**Comment by caolei3721** [comment]
被这个问题困扰很久了，你们解决没有啊

**Comment by Shanks20100922** [comment]
> 被这个问题困扰很久了，你们解决没有啊

我最近也是被这个问题困扰，一直到处查，也没有找到答案，你解决了？

**Comment by Shanks20100922** [comment]
> 在Fake-IP模式下，想要让特定内网IP设备不是走openclash直连、而是该流量直接跳过openclash，请问该怎么设定？
楼主，所以你解决了这个问题了吗？

**Comment by 67373net** [comment]
> > 在Fake-IP模式下，想要让特定内网IP设备不是走openclash直连、而是该流量直接跳过openclash，请问该怎么设定？
> > 楼主，所以你解决了这个问题了吗？

试验出来一个方案，不知道对你们是不是有效：

1. openclash设置：dns模式修改：openclash - plugin settings - dns settings，ndsmasq redirect 改为 firewall redirect，然后 apply settings；

2. 在openwrt命令行中编辑：`vi /etc/openclash/custom/openclash_custom_firewall_rules.sh`：
在exit 0之前添加以下内容：
```
nft insert rule inet fw4 dstnat ether saddr [目标MAC地址] accept 2>/dev/null
nft insert rule inet fw4 mangle_prerouting ether saddr [目标MAC地址] accept 2>/dev/null
```
编辑完后 `chmod +x /etc/openclash/custom/openclash_custom_firewall_rules.sh`
然后在 openclash 里面 apply settings

ps：如果没有命令行可以安装ttyd插件
