### ISSUE TITLE
卡在第六步了，卸载重装，降级版本，还是过不去，【已解决】。

### ISSUE THREAD

**Issue by lingyunzhiss** [vernesong/OpenClash#2359]
换了iStoreOS系统，启动openclash,死活过不去第六步。卸载重装，降级版本都试过了
![image](https://user-images.githubusercontent.com/19514184/167253015-d07332f2-4381-4d81-9035-ec03b77b69a7.png)

**Comment by yunxuan910** [comment]
应该是网本身不行下载不过来。可以先用别的翻墙下载后再使用。

**Comment by lingyunzhiss** [comment]
![image](https://user-images.githubusercontent.com/19514184/167253751-a2c1c321-458c-49ca-b20b-8d958c412ad8.png)
大量报错

**Comment by lingyunzhiss** [comment]
> 应该是网本身不行下载不过来。可以先用别的翻墙下载后再使用。

你是对的！！！
我强制启动，每次看一下调试日志，发现initial xxxxxxxxx error在减少，应该是下载不过来。rule provider proxy类似的条目下载和装载完成后顺利启动了。
谢谢！

**Comment by MBRjun** [comment]
close issue
