### ISSUE TITLE
更新后进不去控制面板啊

### ISSUE THREAD

**Issue by mmeiwenlong** [vernesong/OpenClash#236]
<img width="1321" alt="QQ20200313-204806@2x" src="https://user-images.githubusercontent.com/44661424/76622313-419e7b00-656c-11ea-99b8-da3d76d765a6.png">
怎处理

**Comment by yangliu** [comment]
safari屏蔽了弹窗，点击刷新左侧图标临时放行或设置例外

**Comment by mmeiwenlong** [comment]
> safari屏蔽了弹窗，单击刷新重新图标临时放行或设置例外

谷歌浏览器进去是空白的页面

**Comment by vernesong** [comment]
进去页面空白，需要清理一下浏览器缓存

**Comment by mmeiwenlong** [comment]
> 进去页面空白，需要清理一下浏览器缓存

谢谢，已按你的解决了
