### ISSUE TITLE
请问下自定义嗅探要怎么设置

### ISSUE THREAD

**Issue by spirytuslove** [vernesong/OpenClash#2360]
openclash用了meta内核ps5的nat检测一直失败 用的是混合模式 之前不用meta内核没有这个问题 请问下要怎么设置自定义嗅探让ps5nat能正常

**Comment by vernesong** [comment]
没有相关设备测试，你可以去内核那提

**Comment by MetaCubeX** [comment]
> openclash用了meta内核ps5的nat检测一直失败 用的是混合模式 之前不用meta内核没有这个问题 请问下要怎么设置自定义嗅探让ps5nat能正常

用的啥协议？

**Comment by vernesong** [comment]
试试45.17

**Comment by spirytuslove** [comment]
没看到出来45.17啊 只有45.16
