### ISSUE TITLE
控制面板登录 IP显示未设置

### ISSUE THREAD

**Issue by quanzhun** [vernesong/OpenClash#2362]
全局设置里的还原配置也没有LAN地址，这个似乎发生在我重新配置LAN接口之后。尝试过重新安装openclash依然无法解决，请问这由哪个配置文件决定？或者我该如何修复它？![屏幕截图 2022-05-08 155203](https://user-images.githubusercontent.com/60285749/167286977-48f32917-8bb2-45a6-895f-d73e67950647.png)
![屏幕截图 2022-05-08 155256](https://user-images.githubusercontent.com/60285749/167287030-6013e1e2-014e-4228-b7d1-d13cb10b730e.png)

**Comment by vernesong** [comment]
lan口ip三种方法都获取失败就没办法了，lan口不要改其他名字

**Comment by quanzhun** [comment]
> lan口ip三种方法都获取失败就没办法了，lan口不要改其他名字

确实是名字的问题，配置时习惯用了大写，而openwrt默认是小写。此问关闭。
