### ISSUE TITLE
在“组件运行前检查”时卡住

### ISSUE THREAD

**Issue by AuroraAndersson** [vernesong/OpenClash#2369]
在尝试启动OpenClash时，在“组件运行前检查”时卡住。
固件版本 OpenWrt Development Snapshot / LuCI Master (git-22.121.65028-2a5da72)
固件内核版本 5.15.38
![image](https://user-images.githubusercontent.com/31511420/168025345-ff3e3cac-be43-49be-8243-6b725485212b.png)
Log：

> 2022-05-12 16:15:31 第二步: 组件运行前检查...
> 2022-05-12 16:15:30 第一步: 获取配置...
> 2022-05-12 16:15:30 OpenClash 开始启动...
> 2022-05-12 16:15:30 第六步：删除 OpenClash 残留文件...
> 2022-05-12 16:15:29 第五步: 重启 Dnsmasq 程序...
> 2022-05-12 16:15:29 第四步: 关闭 Clash 主程序...
> 2022-05-12 16:15:28 第三步: 关闭 OpenClash 守护程序...
> 2022-05-12 16:15:26 第二步: 删除 OpenClash 防火墙规则...
> 2022-05-12 16:15:26 第一步: 备份当前策略组状态...
> 2022-05-12 16:15:26 OpenClash 开始关闭...

**Comment by LimeZky** [comment]
2天后问题依旧存在
