### ISSUE TITLE
如何为Clash写一个通用的自定义规则

### ISSUE THREAD

**Issue by huang5307** [vernesong/OpenClash#2370]
机场还有外面分享的Clash文件，都是有自己固定定义规则，我们自己如果有些网址需要自定义，要如何才能写一个通用的自定义规则呢？例如：tw.appledaily.com 这个网站是不能正常访问，所以于是我写了一条自定义规则，如下：
`- DOMAIN,tw.appledaily.com,🚀 节点选择`
但问题就出在后面那个Group“🚀 节点选择”上面，因为文件里面有标准的**Direct**也有标准的**Reject**，所以你写一条规则要他直连或是reject那么无论是哪家机场的配置文件都可以使用。但不是每一家机场的配置文件都有“🚀 节点选择”这个group，有时候只是前面的图形不一样也同样用不了，我试过写“Proxy”不行，“Select”也不行，请问一下有没有什么写法可以不管是启用什么配置文件都能使用的写法呢？

**Comment by 771695775** [comment]
https://acl4ssr-sub.github.io/
用订阅转换再转换一次，或者直接用openclash自带的在线订阅转换再转换一次，效果是一样的

**Comment by huang5307** [comment]
> https://acl4ssr-sub.github.io/ 用订阅转换再转换一次，或者直接用openclash自带的在线订阅转换再转换一次，效果是一样的
这个办法我想过，但遇到一个问题，机场的订阅经过转换，节点就不能用了。不转换直接订阅就可以用，理由我也不知道。

**Comment by 771695775** [comment]
> > https://acl4ssr-sub.github.io/ 用订阅转换再转换一次，或者直接用openclash自带的在线订阅转换再转换一次，效果是一样的
> 
> 这个办法我想过，但遇到一个问题，机场的订阅经过转换，节点就不能用了。不转换直接订阅就可以用，理由我也不知道。
> 
可以试试直接复制机场的ssr或者v2订阅链接转换

**Comment by huang5307** [comment]
> > > https://acl4ssr-sub.github.io/ 用订阅转换再转换一次，或者直接用openclash自带的在线订阅转换再转换一次，效果是一样的
> > 
> > 
> > 这个办法我想过，但遇到一个问题，机场的订阅经过转换，节点就不能用了。不转换直接订阅就可以用，理由我也不知道。
> 
> 可以试试直接复制机场的ssr或者v2订阅链接转换

哎！非常遗憾我用的这个机场只有提供Clash订阅。

**Comment by kingsey** [comment]
你想说的是固定proxy-groups（UI里名称是策略集）的名称，但这个名称是完全可自定义的，各个机场给的配置会完全不同，不存在可用的关键字。想多家机场混用或者通用只能是提取节点信息然后自己配置proxy-groups，然后相对应的，还得去配套规则。

**Comment by Mosney** [comment]
一劳永逸的办法：自己维护配置文件，机场的订阅链接用subconverter使用list=true参数将其转换为proxy-providers只取其节点而不用其规则

**Comment by JH2628** [comment]
利用 proxy-providers: 参数，实现每次拉取订阅，只取节点信息，其他全部采用自定义配置，强大好用，比预配置处理好用太多了
