### ISSUE TITLE
Meta设置里用哪个版本的GEOIP数据库好一点？

### ISSUE THREAD

**Issue by 771695775** [vernesong/OpenClash#2377]
今天用了Meta模式觉得非常好用，不用担心和AdguardHome的DNS设置冲突了，想问咨询两个问题：
1、打开启用 GeoIP Dat 版数据库打开会更好一点吗？
2、Geodata 数据加载方式用“小内存模式”还是“标准模式”好一点？
![QQ截图20220514020549](https://user-images.githubusercontent.com/63600136/168342463-dd0a68ea-8f04-4674-9d39-22596f450a7a.png)

**Comment by wangjianpro999** [comment]
标准内存更好，其他问题同问

**Comment by vernesong** [comment]
没区别，看你规则怎么写
