### ISSUE TITLE
提问：有关UDP转发

### ISSUE THREAD

**Issue by linger040831** [vernesong/OpenClash#2378]
在fakeip模式下 开启udp转发会造成qBittorrent的dht连接数为0，但是貌似并不会影响下载速度，在tun模式下依旧是0，但是不开启udp转发就是正常的，想请教一下有没有大佬知道这是什么原因造成的，谢谢。
<img width="113" alt="image" src="https://user-images.githubusercontent.com/84896599/168373643-20233b52-a0ee-4b3c-9a05-37de8834ad83.png">

**Comment by vernesong** [comment]
p2p是这样的,因为过clash会进行NAT

**Comment by linger040831** [comment]
请问，要如何解决dht一直为0，或者说dht为0并不会影响下载速度嘛？

**Comment by vernesong** [comment]
你可以尝试加fakeip黑名单

**Comment by linger040831** [comment]
好的，谢谢回答
