### ISSUE TITLE
openclash添加http节点启动报错

### ISSUE THREAD

**Issue by RLEDE** [vernesong/OpenClash#2379]
http节点在安卓clash里面能用，添加到openclash后启动会报以下错误:
![IMG_20220514_133817_327](https://user-images.githubusercontent.com/102712434/168412337-09064087-9a5a-4d55-82bf-e5f1a414bc1b.jpg)

**Comment by vernesong** [comment]
用单引号包一下username

**Comment by RLEDE** [comment]
我用的是http订阅链接，通过转换后还是username，在安卓端的clash可以使用，但是在openclash中订阅成功后启动第三步就会修改为openclash的启动配置，就会出现username解析失败的问题！

**Comment by vernesong** [comment]
username后面的参数用单引号包起来，没看懂？

**Comment by RLEDE** [comment]
看懂了，但是加单引号还是出现错误的，加双引才能启动，节点信息例如:
 - name: 🇮🇳 HTTPS｜印度
     server: in.gotochinatown.net
     port: 10884
     type: http
     username: "yaojiayu246@gmail.com"
     password: "73a4ff1c-85c8-11ea-82ef-f23c9164ca5d"
     tls: true

**Comment by RLEDE** [comment]
不知道能不能修复下这个问题，不然每次更新订阅之后还要手动更改节点信息

**Comment by vernesong** [comment]
插件不修改这些，特殊符号本来就是要加引号的，不然会判断为其他类型

**Comment by kingsey** [comment]
> 看懂了，但是加单引号还是出现错误的，加双引才能启动，更改后节点信息例如:
> 
> * name: 🇩🇪 HTTPS｜德国03
>   server: de.gotochinatown.net
>   port: 10887
>   type: http
>   username: "[2068459124@qq.com](mailto:2068459124@qq.com)"
>   password: "8cccbc36-4355-11ec-a8bf-f23c91cfbbc9"
>   tls: true

快删掉吧....节点信息完全暴露了
