### ISSUE TITLE
无法进入Dashboard 控制面板

### ISSUE THREAD

**Issue by ywycd** [vernesong/OpenClash#238]
Dashboard 控制面板一直弹出改端口。但改成9091、8080还是不行。但是另外的可以进。
Docker Openwrt 20.3.5，最新ipk。
![Screenshot_20200314-151406](https://user-images.githubusercontent.com/59784740/76677279-65fb6580-6607-11ea-8766-6ccaf8328c17.jpg)

**Comment by jackge0323** [comment]
host改成192.168.2.200就可以了。
