### ISSUE TITLE
请教，openwrt下安装的openclash, 为什么其它的应用都可以正常使用，唯独twitter打不开呢？

### ISSUE THREAD

**Issue by oldsue2021** [vernesong/OpenClash#2380]
油管，谷歌都正常使用，而且连接速度很快。但就是twitter打不开。不知道要怎么排查问题？目前使用的FakeIP 增强模式， 也试用redir-host 模式，也是twiiter访问有问题。

服务器节点肯定没有问题。

**Comment by vernesong** [comment]
换节点尝试，会屏蔽节点

**Comment by oldsue2021** [comment]
> 

感觉应该不是节点的问题，目前我手机也是用的这些节点，测速优选的是香港节点。 openclash里用的也是香港节点。但手机4G网络下，使用节点访问twiiter是正常的。 只是路由器上推异常, 我刚刚在规则里将国外媒体的访问节点，固定选择香港节点。好像访问还是异常。

**Comment by vernesong** [comment]
节点解析的DNS不能用或者被屏蔽就会这样，我这边正常

**Comment by oldsue2021** [comment]
请问如何解决这个DNS不能用的问题呢？从哪里排查，麻烦给个思路，谢谢！ 记得以前的版本openclash没这个问题，我已经升级到最新版本了。不知道要从哪里去设置…………

**Comment by bugparty** [comment]
dig twitter.com
