### ISSUE TITLE
https://t.co这个twitter的短链接服务打不开，换clash则可以正常打开

### ISSUE THREAD

**Issue by PN62323424** [vernesong/OpenClash#2381]
尝试加规则无效果

**Comment by vernesong** [comment]
换节点尝试

**Comment by PN62323424** [comment]
> 换节点尝试

同样的节点换quan X，或者CFW就可以，另外以下这个帖子里的人和我情况一样。你可以试一下，我估计也是打不开的。
https://github.com/vernesong/OpenClash/issues/2326

**Comment by vernesong** [comment]
节点解析的DNS不能用或者被屏蔽就会这样，我这边正常

**Comment by PN62323424** [comment]
> 节点解析的DNS不能用或者被屏蔽就会这样，我这边正常

感谢解答，我再排查下

**Comment by PN62323424** [comment]
> 节点解析的DNS不能用或者被屏蔽就会这样，我这边正常

同一个机场，同一个节点，cfw下是可以访问的。配置文件的话规则是一样的，具体设置的话因为openclash和cfw不完全一样所以我也不知道哪里的问题，我尝试强制远程域名解析，也是不行，能指点下排查方向不

**Comment by vernesong** [comment]
fallback-filter开了没有

**Comment by PN62323424** [comment]
> fallback-filter开了没有

感谢答复，fallback-filter我开了的。主要这个问题很久了一直没解决，找不到原因。附件是我的运行配置文件（删了部分节点信息），能否麻烦您帮看下。


[1.txt](https://github.com/vernesong/OpenClash/files/8715350/1.txt)

**Comment by vernesong** [comment]
tg找我，直接发我插件备份配置的压缩包

**Comment by Xx1th** [comment]
> > tg找我，直接发我插件备份配置的压缩包
> 
> 好的，已经发您了，麻烦了

请问有解决方案了吗
