### ISSUE TITLE
作为旁路由，主路由端口映射后，外网无法访问内网设备

### ISSUE THREAD

**Issue by MeowRay** [vernesong/OpenClash#2383]
ERR_CONNECTION_RESET

之前用的2021年之前的旧版本正常，但是新版就不行了

**Comment by vernesong** [comment]
开旁路由兼容呢

**Comment by MeowRay** [comment]
> 开旁路由兼容呢

试过了，不行

**Comment by happyeddie** [comment]
+1 openclash 那都好，我也是遇到了这个问题

---

不知道我家的网络拓扑是否和楼主一致，简单描述下：
1. 主路由是 Unifi USG3P
2. OpenClash 装在 NAS（GEN8）里的 OpenWrt（官方固件），桥接网络
3. USG 配置了 DHCP，把网关和 DNS 都指向了 #2 所指的机器 IP
4. USG 上配置了 NAS 中各个服务的端口映射，OpenWrt 没有配置任何端口映射

问题现象：
1. 从内网可以直接通过外网域名（DDNS）访问到家里的设备
2. 从外网无法访问，CURL 提示 `curl: (35) TCP connection reset by peer`
3. 安装 ByPass 科学上网无此问题（安装在 https://supes.top/ 定制的固件，官方固件不确定试了没有）
4. 关闭（不用卸载）OpenClash，#2 的问题不存在了，外网可以访问

**Comment by cs-star** [comment]
我怎么正常

**Comment by happyeddie** [comment]
> 我怎么正常

有没有可能是规则的问题？
我的规则是白名单模式，名单内的直连，名单外的所有请求都走代理

**Comment by MeowRay** [comment]
> > 我怎么正常
> 
> 有没有可能是规则的问题？ 我的规则是白名单模式，名单内的直连，名单外的所有请求都走代理

我先前版本也正常，这个问题反反复复莫名其妙的，如果直连了那旁路由就没用了，还不如网关直接写主路由

**Comment by happyeddie** [comment]
> > > 我怎么正常
> > 
> > 
> > 有没有可能是规则的问题？ 我的规则是白名单模式，名单内的直连，名单外的所有请求都走代理
> 
> 我先前版本也正常，这个问题反反复复莫名其妙的，如果直连了那旁路由就没用了，还不如网关直接写主路由

我是说，我也遇到了类似的问题，但是 @cs-star 说他正常，所以我想是不是我是用的机场的规则导致的这个问题？

还请 @vernesong 费心，需要提供什么信息对解决这个问题有帮助？

**Comment by vernesong** [comment]
绕过国内呢

**Comment by happyeddie** [comment]
> 绕过国内呢

也不行，只保留一个 MATCH,DIRECT，只要打开了 openclash，外网就没法访问内网端口映射的设备，很诡异，一关了就好

再补充一个场景：

如果在旁路由上配置端口映射到需要访问的设备，那这时候外网就可以访问了，但是内网通过 ddns 映射的域名就不能访问了……

**Comment by vernesong** [comment]
旁路由确实是这样，因为只要你过了clash就会nat，只能绕过去

**Comment by freereaper** [comment]
有同样的问题，nas需要科学，所以设置旁路由的网关，求方案。

**Comment by DZ65367709** [comment]
我也遇到同样的问题。
主路由DDNS 使用dynv6.net进行域名解析。
1、考虑到可能是因为此域名是境外域名所导致，但是我把此域名写进 自定义规则 优化配置 - DOMAIN-SUFFIX, dynv6.net,DIRECT 也不能解决。
2、听网友提供方案，选用redrect-host模式也是没有用处。
。。。
另外，如果按照1的思路，其实也是权宜之计，因为那会导致以后无法进入dynv6.net官网。同一个域名不可能有矛盾的两种操作。
希望大佬尽快有方案出来啊。

**Comment by vernesong** [comment]
第一种：
```
iptables -t nat -A openclash -m set --match-set localnetwork src -m conntrack --ctstate ESTABLISHED -j RETURN
```
第二种：
![image](https://user-images.githubusercontent.com/42875168/169639387-fce62bcc-40c6-4117-a84e-5ed0d1b5a597.png)

看看哪个管用吧

**Comment by freereaper** [comment]
还请 @vernesong 费心，需要提供什么信息对解决这个问题有帮助？我看恩山论坛上的帖子，有这个问题的人群不在少数，都是反映开了openclash就无法外网访问内部nas。

**Comment by DZ65367709** [comment]
我已经撤了我的问题。其实作者大佬已经考虑很周全了，是我们没有注意到或者设置有错误。为了方便大家，说出来我的思路请君可以一试。
我的解决办法，仍旧是在 规则设置—自定义规则里，添加“ DOMAIN-SUFFIX, 你的访问域名（不带端口号）, DIRECT” 点击保存并应用。
所以，这就是大佬不解释的原因吧。

**Comment by freereaper** [comment]
> Referenc
你先看清楚问题吧。

**Comment by DZ65367709** [comment]
…经过反复测试，
把nas 网关设置成旁路由，远程访问NAS 仍然是歇菜…
目前实验看来，
1.自定义规则添加远程访问的域名不能解决
2. iptables -t nat -A openclash -m set --match-set localnetwork src -m conntrack --ctstate ESTABLISHED -j RETURN 不能解决
唯一能解决的就是关闭openclash

**Comment by zh15933** [comment]
我也遇到过这个问题,主路由是爱快,旁路由是op,爱快转发op的端口不能用,
更换一下运行模式就行了
![image](https://user-images.githubusercontent.com/32957590/170677678-ab1544c8-0497-4a42-90cc-1222caa35006.png)
![image](https://user-images.githubusercontent.com/32957590/170677943-dbc0c5b6-2699-4e90-81c0-444f090b9330.png)

**Comment by xianren78** [comment]
![Screenshot_2022-05-28-22-19-07-32_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/26913311/170829448-ffa5f94b-a23d-42e8-a7ba-537302c4f0ad.jpg)
在防火墙 - 通讯规则里加上一条允许lan访问该端口的规则解决了一个类似的问题。

**Comment by xianren78** [comment]
![Screenshot_2022-05-28-22-19-07-32_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/26913311/170829892-f6ffd1ce-7c62-42f0-874c-9cdb54cf239e.jpg)
我用通讯规则解决过旁路由本身的问题，就是这个udp端口映射后外部访问不了，不知道有没有借鉴意义。

**Comment by MeowRay** [comment]
> 我也遇到过这个问题,主路由是爱快,旁路由是op,爱快转发op的端口不能用, 更换一下运行模式就行了 ![image](https://user-images.githubusercontent.com/32957590/170677678-ab1544c8-0497-4a42-90cc-1222caa35006.png) ![image](https://user-images.githubusercontent.com/32957590/170677943-dbc0c5b6-2699-4e90-81c0-444f090b9330.png)

测试无效，但我在旧版可以访问时也是这个配置，应该与这个有关联

**Comment by vernesong** [comment]
旁路由你再转发一次就行了，插件会自动去绕过端口的流量

**Comment by ChaojuWang** [comment]
在nat表的openclash_post上做匹配，让被转发端口的流量不走openclash的nat， 参考命令（端口映射是外网-》内网9443）
`iptables -t nat -I openclash_post -p tcp --sport 9443 -j RETURN`

**Comment by ChaojuWang** [comment]
> 在nat表的openclash_post上做匹配，让被转发端口的流量不走openclash的nat， 参考命令（端口映射是外网-》内网9443） `iptables -t nat -I openclash_post -p tcp --sport 9443 -j RETURN`

建议增加选项让我们能够在openclash启动后执行特定脚本用来修改iptables或者设置某些端口或者ip不走openclash的nat

**Comment by ChaojuWang** [comment]
可以暂时通过修改`/etc/init.d/openclash`中防火墙配置函数使得在每次openclash启动时应用额外的iptables规则， 但是每次更新openclash都要重新修改

**Comment by XGGY** [comment]
> ![image](https://user-images.githubusercontent.com/42875168/172864318-d8e1ccba-8e63-411a-9bf9-82f3866cef12.png)

我开了旁路由（旁网关）模式后，设置这个绕过核心来源端口都没用，外网还是无法访问进来，而且连ping公网ip都不通。但是不开这个旁路由模式呢，主路由的wifi就无法上网，但是mesh的子路由wifi却没事。真是头都大了

**Comment by XGGY** [comment]
> > ![image](https://user-images.githubusercontent.com/42875168/172864318-d8e1ccba-8e63-411a-9bf9-82f3866cef12.png)
> 
> 我开了旁路由（旁网关）模式后，设置这个绕过核心来源端口都没用，外网还是无法访问进来，而且连ping公网ip都不通。但是不开这个旁路由模式呢，主路由的wifi就无法上网，但是mesh的子路由wifi却没事。真是头都大了

有人知道吗

**Comment by runchunzhang** [comment]
我通过全局设置-访问控制-绕过核心的来源端口-加入了ikuai转发的端口目前已经稳定可以ddns了
![image](https://user-images.githubusercontent.com/18542704/184061597-ae9fbf07-0c3a-45f7-a356-126ef6ae53c4.png)
![image](https://user-images.githubusercontent.com/18542704/184061631-b5a0ff87-30e3-42f2-9310-680a0113a69a.png)

**Comment by hutao562** [comment]
> 我通过全局设置-访问控制-绕过核心的来源端口-加入了ikuai转发的端口目前已经稳定可以ddns了 ![image](https://user-images.githubusercontent.com/18542704/184061597-ae9fbf07-0c3a-45f7-a356-126ef6ae53c4.png) ![image](https://user-images.githubusercontent.com/18542704/184061631-b5a0ff87-30e3-42f2-9310-680a0113a69a.png)

感谢，fake-ip模式下也可以正常解析外网地址了

**Comment by bamboo2002cn** [comment]
我刚刚解决了 其他方案都不行,在dns设置-高级设置里,第一项,添加自己的域名就可以了

**Comment by hackmgrm** [comment]
> Reference in new i

不行啊

**Comment by hackmgrm** [comment]
> 我刚刚解决了 其他方案都不行,fak-ip模式在dns设置-高级设置里,第一项,添加自己的域名就可以了

不行啊，来个截图看看撒

**Comment by DZ65367709** [comment]
谢谢兄台分享。的确这个方法能够解决。这个问题可以关闭了。在 2022年9月14日，13:18，bamboo2002cn ***@***.***> 写道：﻿
我刚刚解决了 其他方案都不行,在dns设置-高级设置里,第一项,添加自己的域名就可以了

**Comment by hackmgrm** [comment]
> 谢谢兄台分享。的确这个方法能够解决。这个问题可以关闭了。在 2022年9月14日，13:18，bamboo2002cn ***@***.***> 写道：﻿ 我刚刚解决了 其他方案都不行,在dns设置-高级设置里,第一项,添加自己的域名就可以了 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

奇怪我昨天晚上试了一下还是不行。而通过“绕过核心”放行才可以

**Comment by liasece** [comment]
经过各种抓包分析后，找到了一个可能的原因，也解决了我的问题。希望对后来者有帮助。

当内网设备暴露端口并由主路由转发端口数据时，内网设备的入口流量是正常的，但是其出口流量会流经旁路由。旁路由会转发该出口流量，这时这个流量的 source ip 会变成旁路由的ip。知道这个原因后，我们只要在旁路由上设置如下 iptables 规则即可：

```
# 要跳过旁路由针对该服务端口的处理
firewall-cmd --permanent --direct --passthrough ipv4 -t nat -A PREROUTING -s 192.168.1.3/32 -p tcp --sport 22 -j RETURN

# SNAT 动作意为修改数据包的源地址。在这里，192.168.1.3 就是内网提供服务的IP。
firewall-cmd --permanent --direct --passthrough ipv4 -t nat -A POSTROUTING -s 192.168.1.3/32 -p tcp --sport 22 -j SNAT --to-source 192.168.1.3
```

**Comment by SilenceEagle** [comment]
> 我刚刚解决了 其他方案都不行,fak-ip模式在dns设置-高级设置里,第一项,添加自己的域名就可以了

666，真的有效，稳的很！！！

我的主路由是小米的`AX6`，旁路由是`R2S`，之前一直没有把主路由的`DNS`和网关指向旁路由（`fake-ip,tun模式`），因为存在以下矛盾点：
***
将主路由的`DNS`和网关指向旁路由后：
1. 如果**开启**旁路由防火墙中`lan`口的`ip伪装`（这东西应该就是`nat`的翻译），内网的上网设备是**可以正常科学上网**的，也**可以正常访问国内的网站**，但就是**从外网无法访问内网的服务**，比如通过域名访问`NAS`的管理界面；
2. 如果**关闭**旁路由防火墙中`lan`口的`ip伪装`，内网的上网设备**可以正常科学上网**，但**不能访问国内的网站**，却这时**外网设备**又**可以访问内网的服务**了，比如通过域名访问`NAS`的管理界面。
***
所以为了内网设备能正常访问国内网站，我就必须开启旁路由防火墙中`lan`口的`ip伪装`，但这样就会导致从外网无法访问内网的服务。

今天不死心就又来尝试各路大神的解决方法，发现老哥的解决办法有效：
* `旁路由`>>`网络`>>`防火墙`>>`基本设置`>>`区域`>>勾选`lan`口的`ip动态伪装`后`保存&应用`；
* `openclash` 模式选择为`Fake-IP(tun)模式`
* `旁路由`>>`服务`>>`openclash`>>`全局设置`>>`dns设置`>>勾选`高级设置`，将会显示一个文本输入框，这里面应该是用来配置`fake-ip-filter`的，其中已经预填好了一些域名，这里的意思是访问这些域名时，`openclash`将查询`dns`来得到真实`IP`而不是直接返回一个假的随机`IP`。在最后添加我们自己的域名后`应用配置`。

等待片刻，便可实现**内网设备可正常上网**+**外网可访问内网服务**。

**Comment by jouleken** [comment]
我在国内的时候，外网访问内网设备一切正常，
但是现在在曼谷旅游，访问不了国内的群晖，只有在”黑白名单“里的”绕过核心的来源端口“添加端口才能正常访问。

**Comment by 991547436** [comment]
可以试试op先转服务端口，主路由转发op端口，我是这样解决的

**Comment by chenzz** [comment]
我来终结一下这个问题，

参考如下博主的解决方案：
https://e11z.net/posts/OpenWRT-FORWARD

**Comment by zhizheyongfeng** [comment]
经测试，内核只有dev开启fakeip模式，在访问设置里面添加转发的端口就能解决问题，之前尝试添加域名在dns等操作都失败，这次总算成功

**Comment by xiaoess** [comment]
![1694268934749](https://github.com/vernesong/OpenClash/assets/70944478/f0c0bb76-1639-4af8-a6db-c96543e4229e)试试我的最简单的一个方法，这里转发点接受

**Comment by yuyuan1019** [comment]
> ![1694268934749](https://user-images.githubusercontent.com/70944478/266785753-f0c0bb76-1639-4af8-a6db-c96543e4229e.png)试试我的最简单的一个方法，这里转发点接受

太稳了 兄弟

**Comment by YaoMiss** [comment]
> 经过各种抓包分析后，找到了一个可能的原因，也解决了我的问题。希望对后来者有帮助。
> 
> 当内网设备暴露端口并由主路由转发端口数据时，内网设备的入口流量是正常的，但是其出口流量会流经旁路由。旁路由会转发该出口流量，这时这个流量的 source ip 会变成旁路由的ip。知道这个原因后，我们只要在旁路由上设置如下 iptables 规则即可：
> 
> ```
> # 要跳过旁路由针对该服务端口的处理
> firewall-cmd --permanent --direct --passthrough ipv4 -t nat -A PREROUTING -s 192.168.1.3/32 -p tcp --sport 22 -j RETURN
> 
> # SNAT 动作意为修改数据包的源地址。在这里，192.168.1.3 就是内网提供服务的IP。
> firewall-cmd --permanent --direct --passthrough ipv4 -t nat -A POSTROUTING -s 192.168.1.3/32 -p tcp --sport 22 -j SNAT --to-source 192.168.1.3
> ```

根據理論來說 ，映射到內部機器手，返回的時候因為網關是旁路由，導致多了一層旁路由，source ip 變了之後就找不到返回的路了 ，一般會顯示 termiante by server 的信息。除了加這個規則還有其他能直接在 openwrt 上修改的嗎？

**Comment by domonnss** [comment]
**成功实现外网访问**
ikuai 主路由 istoreos旁路由 open clash 挂在旁路由上 ipv4环境
ikuai做了端口映射
![image](https://github.com/vernesong/OpenClash/assets/60506557/5c85ee4b-06d7-4541-b05c-15383170c16d)
openclash开启fake ip模式,`服务`>>`openclash`>>`插件设置`>>`黑白名单` >>`绕过核心的来源端口`添加内网端口
![image](https://github.com/vernesong/OpenClash/assets/60506557/4ac8be6e-53e2-4236-938a-a80b99dd747c)

**Comment by Alinlin918** [comment]
支持

**Comment by RandomWrite** [comment]
> **成功实现外网访问** ikuai 主路由 istoreos旁路由 open clash 挂在旁路由上 ipv4环境 ikuai做了端口映射 ![image](https://private-user-images.githubusercontent.com/60506557/337206866-5c85ee4b-06d7-4541-b05c-15383170c16d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMzM5ODIsIm5iZiI6MTcyNDIzMzY4MiwicGF0aCI6Ii82MDUwNjU1Ny8zMzcyMDY4NjYtNWM4NWVlNGItMDZkNy00NTQxLWIwNWMtMTUzODMxNzBjMTZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDA5NDgwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3NTY3NDVhYjBiMGViMzg2NmI3OTRkZDExMTU1MDZiNzE0YjNhMzYyYTAxOTA0ZTVkNTYxZjRjZGMxMzVmZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Rj0imk3Tx9Tl86aYbYlaY6GD81glamhfz4Mc5KjJdHY) openclash开启fake ip模式,`服务`>>`openclash`>>`插件设置`>>`黑白名单` >>`绕过核心的来源端口`添加**内网端口** ![image](https://private-user-images.githubusercontent.com/60506557/337207738-4ac8be6e-53e2-4236-938a-a80b99dd747c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMzM5ODIsIm5iZiI6MTcyNDIzMzY4MiwicGF0aCI6Ii82MDUwNjU1Ny8zMzcyMDc3MzgtNGFjOGJlNmUtNTNlMi00MjM2LTkzOGEtYTgwYjk5ZGQ3NDdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDA5NDgwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxYTM1NDUyMDJhYTRjZjg3NzljNTIxMzFmZmI3ZTc4YTIyNmM5NDIyNDNmYzAzOTAwMDJmY2YzYTFiODQyMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UzDTvS1WxYR5xCzBhbL2FxR05OqPuUlrjIswRdizwe0)

这个可以

**Comment by caoyulotus** [comment]
> **成功实现外网访问** ikuai 主路由 istoreos旁路由 open clash 挂在旁路由上 ipv4环境 ikuai做了端口映射 ![image](https://private-user-images.githubusercontent.com/60506557/337206866-5c85ee4b-06d7-4541-b05c-15383170c16d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MDY3NTIsIm5iZiI6MTczNDQwNjQ1MiwicGF0aCI6Ii82MDUwNjU1Ny8zMzcyMDY4NjYtNWM4NWVlNGItMDZkNy00NTQxLWIwNWMtMTUzODMxNzBjMTZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDAzMzQxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1MzliY2M5OWYxOWNkMzM5MTQ0M2FiMjJlOTM4ODQzOTc3ZjkxNGU4ZTg2NGZiNjI4ZjMwOGZhM2YzY2Q3NWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.N1n36JzfRXsHjOMOLFTGZEhFA9Q9Xa-08RcKEmkskkw) openclash开启fake ip模式,`服务`>>`openclash`>>`插件设置`>>`黑白名单` >>`绕过核心的来源端口`添加**内网端口** ![image](https://private-user-images.githubusercontent.com/60506557/337207738-4ac8be6e-53e2-4236-938a-a80b99dd747c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MDY3NTIsIm5iZiI6MTczNDQwNjQ1MiwicGF0aCI6Ii82MDUwNjU1Ny8zMzcyMDc3MzgtNGFjOGJlNmUtNTNlMi00MjM2LTkzOGEtYTgwYjk5ZGQ3NDdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDAzMzQxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlN2I0YzlkNDExNTc4NmZjMjViNjRhNTcxNDI5YmQ2NWNjNDQwMmFmNTM0ZmFhOGMwNmIxNzFjZmI1YThjOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VqtQC77WmVr2IMN0QTCL1DfsUAIF0yGUYCHmV8_DzaM)

非常感谢，解决问题了

**Comment by Ethanwish** [comment]
我遇到的问题更奇怪，以前一直正常，我是ikuai 主路由 istoreos旁路由 open clash的环境，ikuai做ddns及端口转发，只有旁路网关指向主路由，然后nas的ip填固定ip，网关几DNS指向旁路由，问题是：我两台nas，两台nas上均有不同的服务，使用多个端口，但是只有威联通这一台nas自己的网页端口（5000）无法访问，另外的端口都可以访问，另一台nas也是这样设置的，所有端口正常访问。 istoreos旁路由重启或者重启防火墙后的几分钟之内是可以访问的，过一会又不能访问。

**Comment by Ghu784** [comment]
> > ![image](https://user-images.githubusercontent.com/42875168/172864318-d8e1ccba-8e63-411a-9bf9-82f3866cef12.png)
> 
> 我开了旁路由（旁网关）模式后，设置这个绕过核心来源端口都没用，外网还是无法访问进来，而且连ping公网ip都不通。但是不开这个旁路由模式呢，主路由的wifi就无法上网，但是mesh的子路由wifi却没事。真是头都大了

        我目前也是遇到这个问题，关闭旁路由模式后，插件设置>>黑白名单 >>绕过核心的来源端口设置nas的访问端口之后可以公网域名访问，但是出现一个问题，主路由的wifi，如果手机进行连接，手动将网关和DNS指向旁路由之后，wifi就会没网。
相反，开启旁路由模式之后，主路由wifi正常，但是没法公网域名访问nas了，这时候关掉openclash就正常，要兼顾上面wifi正常的情况下，如何修改才能让公网正常访问nas呢

**Comment by Ahui2** [comment]
> **成功实现外网访问** ikuai 主路由 istoreos旁路由 open clash 挂在旁路由上 ipv4环境 ikuai做了端口映射 ![image](https://github.com/vernesong/OpenClash/assets/60506557/5c85ee4b-06d7-4541-b05c-15383170c16d) openclash开启fake ip模式,`服务`>>`openclash`>>`插件设置`>>`黑白名单` >>`绕过核心的来源端口`添加**内网端口** ![image](https://github.com/vernesong/OpenClash/assets/60506557/4ac8be6e-53e2-4236-938a-a80b99dd747c)

厉害

**Comment by GeneKong** [comment]
> 2\. 如果**关闭**旁路由防火墙中`lan`口的`ip伪装`，内网的上网设备**可以正常科学上网**，但**不能访问国内的网站**，却这时**外网设备**又**可以访问内网的服务**了，比如通过域名访问`NAS`的管理界面。

关了ip伪装感觉是有效的，这边测试好像也能访问国内网站。

**Comment by hack2012** [comment]
> > **成功实现外网访问** ikuai 主路由 istoreos旁路由 open clash 挂在旁路由上 ipv4环境 ikuai做了端口映射 ![image](https://github.com/vernesong/OpenClash/assets/60506557/5c85ee4b-06d7-4541-b05c-15383170c16d) openclash开启fake ip模式,`服务`>>`openclash`>>`插件设置`>>`黑白名单` >>`绕过核心的来源端口`添加**内网端口** ![image](https://private-user-images.githubusercontent.com/60506557/337207738-4ac8be6e-53e2-4236-938a-a80b99dd747c.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjQ4Mjk2NTgsIm5iZiI6MTc2NDgyOTM1OCwicGF0aCI6Ii82MDUwNjU1Ny8zMzcyMDc3MzgtNGFjOGJlNmUtNTNlMi00MjM2LTkzOGEtYTgwYjk5ZGQ3NDdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMjA0VDA2MjIzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0M2UzODhmMzA4ZGM1YmY1NDBjZDU0ZDBkMTgzNjIwOWM3NWIxNjJiYThmYmU4MmVjMzljNGJhMDIxMGMxZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WFbH0QkvZOf3xBbX1cRTJQabwus383h6pWSHfbX4mRE)
> 
> 厉害

新版本的op在哪里配置？
