### ISSUE TITLE
管理面板源IP只显示路由器内网IP

### ISSUE THREAD

**Issue by isoulgh** [vernesong/OpenClash#2388]
![image](https://user-images.githubusercontent.com/47737022/168739723-25fc0b1b-ef07-4adb-9c18-e6c8ca8361da.png)

使用内网或外网的任意不同设备经过Socks5代理连接旁路由的OpenClash访问网页，

Clash管理面板内的连接模块里的源IP都只是路由器的内网IP加随机端口号（如图），

有什么办法方便查看，

或显示设备的真实IP呢？

**Comment by cnfjice** [comment]
试试关闭：*本地 DNS 劫持

**Comment by isoulgh** [comment]
感谢解答！
我刚去试了一下，关闭“*本地 DNS 劫持”后，会无法连接外网。我也尝试了OpenClash中DNS设置里的其他几个选项，都没有效果。
我也百度搜索，关闭了主路由的DNS劫持，也无效果。

还有别的办法嘛？
