### ISSUE TITLE
又遇到问题追问一下？？在Fake-IP模式下内网里动态DNS域名没法使用怎么破？又遇到问题追问一下

### ISSUE THREAD

**Issue by xx791117** [vernesong/OpenClash#239]
发现在Fake-IP模式下，内网里使用动态DNS域名访问nas或者路由无法访问，ping域名发现域名被解析到一个假ip上所以无法访问，不知道这个怎么设置才可以内网使用域名？主要nas上配置了证书，手机上的app不用域名无法使用！

**Comment by vernesong** [comment]
dns高级设置

**Comment by xx791117** [comment]
看到了感谢！！

**Comment by xx791117** [comment]
追问在这！！！！！修改DNS黑名单后，开始正常但是修改一些其他不相关配置后，重新应用，访问路由的域名就显示 拒绝连接了  访问NAS的正常，这又是什么情况？又是我改了什么不该改的配置吗？
