### ISSUE TITLE
openwrt on Docker，openclash启动后，openwrt的luci/ssh无法连接

### ISSUE THREAD

**Issue by NV3S** [vernesong/OpenClash#2390]
Docker里面跑了一个openwrt，用macvlan网卡，然后其中的openclash启动，openwrt的luci/ssh无法连接了。
如果进console，把firewall或者openclash停了，就可以访问了。
因为故障时，进不了luci，没办法抓出诊断日志，请问如何排查，需要哪些素材。

**Comment by vernesong** [comment]
进启动脚本，把防火墙参数一个个禁用，看是哪条引起的

**Comment by NV3S** [comment]
> 
我试试，/etc/init.d/openclash 这个吧

**Comment by NV3S** [comment]
> 

这条在运行时是有的，iptables -t nat -F openclash 就把它删了，删之前会导致docker openwrt的luci/ssh无法访问，应该的端口转走了...

**Comment by vernesong** [comment]
你防火墙发完整

**Comment by NV3S** [comment]
启动openclash前：
![网页捕获_24-5-2022_18520_192 168 100 220](https://user-images.githubusercontent.com/17755534/170007978-842f60eb-ef59-42e5-8906-2dbde98fc4fa.jpeg)

========================
启动openclash后（提示启动完成后截取，一会儿就无法访问luci和ssh了）
![网页捕获_24-5-2022_18825_192 168 100 220](https://user-images.githubusercontent.com/17755534/170008019-9705d143-2287-45a2-add6-a5bcc97f88cb.jpeg)


=======================================
在上一步骤后，运行 iptables -t nat -F openclash后（能够访问luci和ssh）
![网页捕获_24-5-2022_181221_192 168 100 220](https://user-images.githubusercontent.com/17755534/170008255-3da12c71-3939-4cc3-890e-400d39f53945.jpeg)

**Comment by NV3S** [comment]
0.45.29 解决了

**Comment by applehan2002** [comment]
我现在使用的OpenClash  v0.45..141-beta仍然有这个问题，一旦启动Openclash成功，就会无法连接到SSH和LUCI的登录界面，直接我通过在客户端处输入iptables -t nat -F openclash后，问题立马解决！但是这是个很麻烦的问题，因为每次更新订阅后都会重启Openclash，问题也就再次出现，难道就不能把这个防火墙命令写在Openclash的启动命令中吗？
![image](https://github.com/vernesong/OpenClash/assets/80624095/803b685d-2c3a-4648-bf8c-c2e6216e72b8)

**Comment by applehan2002** [comment]
自己解决：SSH接入Openwrt，编辑Openclash脚本 vim /etc/init.d/openclash ，移到文本最后，在restart()中加入 iptables -t nat -F openclash 
![image](https://github.com/vernesong/OpenClash/assets/80624095/6e0c3678-6cf4-4a63-a20f-c795d813ad62)
在reload()中加入 iptables -t nat -F openclash 
![image](https://github.com/vernesong/OpenClash/assets/80624095/f3d9945c-743d-4629-8a66-612d60d8d73d)
好了！
