### ISSUE TITLE
Speedtest result is much worse than expected when running in TUN mode

### ISSUE THREAD

**Issue by rltyty** [vernesong/OpenClash#2396]
无论用网页版speedtest.net (或者speedtest.cn), 还是路由器上的speedtest-cli, 无论运行在redir-host还是fake-ip模式，只要是TUN模式，测试结果就很慢。
比如我的带宽正常测试结果是410M/s左右 (不使用openclash，或者使用openclash并运行在默认的fake-ip和redir-host模式下），只要我切换到TUN模式，无论fake-ip还是redir-host, 测试结果就掉到200M/s以下，甚至100左右）。

我记得TUN模式是为了支持UDP代理，请问这种模式为何使带宽测试降速这么多？是不是等于说在TUN模式下，我访问任何资源的带宽上限都被软件给降低了？这是个bug吗？

谢谢。

**Comment by djoeni** [comment]
its happening on me too speed like cut in half when TUN mode, fortunately my firmware came with Turbo ACC Center software. When activating Flow Offloading in Turbo ACC speed like "normal" again.

**Comment by MBRjun** [comment]
用混合模式
