### ISSUE TITLE
到底哪个版本新？反复横跳？

### ISSUE THREAD

**Issue by wangjianpro999** [vernesong/OpenClash#2397]
如题
如图
![microsoft_edge_screenshot_2022年5月20日 GMT+08_00 上午8_22_25 png](https://user-images.githubusercontent.com/79621192/169424834-e04213e6-e6b8-41e8-813d-db15f99990c7.jpg)

**Comment by AllForLandlord** [comment]
这个疑似是网络问题造成的，网络不稳定的时候检测出来的结果不正确

**Comment by openips** [comment]
dev master开会选就这样选对
