### ISSUE TITLE
自动更新订阅无效？

### ISSUE THREAD

**Issue by cjlhll** [vernesong/OpenClash#2398]
你好，自动更新订阅不好使啊？一直都这样。试了很多固件。和openclash版本。需要什么特殊设置吗？
![image](https://user-images.githubusercontent.com/26736892/169434254-3c297b8d-9639-43bc-9d26-1534b3c78c4e.png)

**Comment by vernesong** [comment]
订阅旁边打钩没有

**Comment by cjlhll** [comment]
> 订阅旁边打钩没有

打勾了
![image](https://user-images.githubusercontent.com/26736892/169553324-7fd62470-d4b1-4bf4-9dc9-5a3b75e0dbdb.png)

**Comment by vernesong** [comment]
那是什么不好使

**Comment by cjlhll** [comment]
> 那是什么不好使

到每天设置的0点了。并不会更新订阅。

**Comment by vernesong** [comment]
重启一下才会生效

**Comment by vernesong** [comment]
你看一下计划任务里面有没有

**Comment by cjlhll** [comment]
> 你看一下计划任务里面有没有

计划任务里有。但是还是不会执行订阅更新
![67CE3E97-2F4B-42D8-8027-750B8F9BE3F2](https://user-images.githubusercontent.com/26736892/169567892-47747d58-a746-4ea3-9672-e6cf83c953ad.jpeg)

**Comment by cjlhll** [comment]
> 重启一下才会生效

N1也重启了。

**Comment by FFanta** [comment]
我也遇到了同样的问题

**Comment by cjyy46** [comment]
我也是同样问题 Linux arm64平台

**Comment by cjyy46** [comment]
> 你看一下计划任务里面有没有

我也是同样问题  计划任务内容如下
0 5 * * * /usr/share/openclash/openclash.sh
0 2 * * * /usr/share/openclash/openclash_rule.sh
0 3 * * * /usr/share/openclash/openclash_ipdb.sh
0 4 * * * /usr/share/openclash/openclash_chnroute.sh
