### ISSUE TITLE
[提问]mips_24kc的ath79反复出现崩溃是怎么回事

### ISSUE THREAD

**Issue by Neubulae** [vernesong/OpenClash#240]
https://pastebin.com/2we44qcx

**Comment by Neubulae** [comment]
ar71xx和ath79不能通用吗? 那我是不是要自己编译一个ath79的版本

**Comment by vernesong** [comment]
固件编译的时候开启FPU，内核用hardfloat，目前go1.4对软浮点的支持好像有问题。

**Comment by Neubulae** [comment]
> 固件编译的时候开启FPU，内核用hardfloat，目前go1.4对软浮点的支持好像有问题。

刚逛了一圈看到了，问题是怎么编译…哪里下载已经好了的包呢

**Comment by vernesong** [comment]
固件要重新编译支持fpu的版本并刷机，或者你可以装二月份发布的内核版本

**Comment by Neubulae** [comment]
> 固件要重新编译支持fpu的版本并刷机，或者你可以装二月份发布的内核版本

好的，后者还是简单些…前者是要怎么做

**Comment by Neubulae** [comment]
> 固件要重新编译支持fpu的版本并刷机，或者你可以装二月份发布的内核版本

https://github.com/golang/go/issues/37667
