### ISSUE TITLE
[Process] find process xxx: dial netlink: protocol not supported

### ISSUE THREAD

**Issue by MBRjun** [vernesong/OpenClash#2401]
![Snipaste_2022-05-21_11-46-08](https://user-images.githubusercontent.com/55020690/169634255-7eaa8994-726f-433f-b92c-1552ab6185e3.png)
能正常使用，但是日志里很多这个，这是什么提示

**Comment by vernesong** [comment]
找processname的日志

**Comment by MBRjun** [comment]
![Screenshot_20220522-011150_Chrome](https://user-images.githubusercontent.com/55020690/169662164-93c8b3aa-f00e-4bd3-b825-c3c36fb42e35.png)
好像没啥有关的日志 日志等级是Debug🤔
