### ISSUE TITLE
openclash 外部控制（dashboard）无法更新节点。

### ISSUE THREAD

**Issue by Hywfred** [vernesong/OpenClash#2403]
![image](https://user-images.githubusercontent.com/57909991/169638517-7a119d3b-6f63-414e-b539-630100ecf590.png)
你好，如上图所示，代理集中的代理无法更新。我使用的是proxy-provider。
还有规则集中的规则也无法更新。通过F12调试，后台显示503错误。
![image](https://user-images.githubusercontent.com/57909991/169638765-01a9f730-4e80-4d32-aa6c-3259da11f990.png)
请教一下，这种情况如何解决，谢谢！

**Comment by vernesong** [comment]
我这边没问题，考虑是连接问题，因为内核是直连更新

**Comment by Hywfred** [comment]
> 我这边没问题，考虑是连接问题，因为内核是直连更新

你说的连接问题具体是指什么连接，可不可以稍微具体点。这种情况可以尝试怎么解决？谢谢回复！

**Comment by LimonChoms** [comment]
我也是一样的问题

**Comment by vernesong** [comment]
就是直连下载失败啊，你自己单独直连试试

**Comment by vernesong** [comment]
meta是走代理

**Comment by LimonChoms** [comment]
> 就是直连下载失败啊，你自己单独直连试试

一样的，我本地搭的，不存在下载不了，启动的时候都可以正常下载，但是面板里点更新就是没反应

**Comment by Hywfred** [comment]
> 的，我本地搭的，不存在下载不了，启动的时候都可以正常下载

是的。启动的时候可以下载，但是dashboard里面手动更新有问题。好像是点击之后没有发起请求还是怎样。把地址输入浏览器也可以正常显示。

**Comment by vernesong** [comment]
地址是内网地址？

**Comment by Hywfred** [comment]
> 地址是内网地址？

是的。dashboard地址是http://10.10.10.3:9090/ui/#/proxies?host=10.10.10.3&port=9090&secret=123456。
奇怪的是刚才我又试了下，连着刷新五六次会有一次成功。有点玄学0 0

**Comment by LimonChoms** [comment]
> 地址是内网地址？

是的，本地nas定时pull下来，可以正常访问的，就是更新不了

**Comment by vernesong** [comment]
jsdelvr是被污染的啊

如果下载的文件是内网的地址就关闭绑定接口

**Comment by Hywfred** [comment]
> jsdelvr是被污染的啊
> 
> 如果下载的文件是内网的地址就关闭绑定接口

是的，规则用的是jsdelvr,更新不成功；代理用的是转换网站的地址，刷新五六次会有一次成功。用的都是外部的地址。那就把规则的地址换一下试试，不用jsdelvr了。谢谢回复~

**Comment by LimonChoms** [comment]
> jsdelvr是被污染的啊
> 
> 如果下载的文件是内网的地址就关闭绑定接口

OK了，在配置文件hosts加上内网地址可以更新了😄
