### ISSUE TITLE
UI问题：自定义规则页面显示在所有选项卡下

### ISSUE THREAD

**Issue by citratecycle** [vernesong/OpenClash#2406]
> 主机型号: Xiaomi Redmi Router AC2100
> 固件版本: OpenWrt 22.03.0-rc1 r19302-df622768da
> LuCI版本: git-20.074.84698-ead5e81
> 内核版本: 5.10.111
> 处理器架构: mipsel_24kc

![image](https://user-images.githubusercontent.com/48681002/169690354-ae1b0da4-d9db-411e-8b15-c4f4ad85b9d3.png)

**Comment by vernesong** [comment]
这个自定义DNS是这样的
