### ISSUE TITLE
不能替换配置文件里的dns

### ISSUE THREAD

**Issue by jwkinko** [vernesong/OpenClash#2407]
大佬！
1:在线订阅转换配置文件，设置自定义上游dns，配置文件并没有覆盖只是在后面追加。版本x86-64是最新的版本。
2:代理集配置的url 填机场订阅地址行吗？支不支持https

**Comment by vernesong** [comment]
1、命令就是覆盖的命令，不可能追加
2、可以

**Comment by jwkinko** [comment]
明白了大佬是不是default-nameserver 不算在内
![image](https://user-images.githubusercontent.com/95012013/169696464-2a717f5b-4a6a-4c38-bb11-814f0eae6f96.jpeg)

**Comment by vernesong** [comment]
嗯
