### ISSUE TITLE
cpu被占满

### ISSUE THREAD

**Issue by loohalh** [vernesong/OpenClash#2408]
升级45-18-beat后，cpu瞬间被占满，打开openclash后cpu是100%，关闭openclash后cpu不到10%。
<img width="1369" alt="image" src="https://user-images.githubusercontent.com/16890588/169703521-b24f51b0-0d42-4ac2-a26f-10129751ffc3.png">
<img width="1343" alt="image" src="https://user-images.githubusercontent.com/16890588/169703534-c32296cd-cd90-463e-a285-4154c49425a5.png">
查看链接数有2万多
<img width="1361" alt="image" src="https://user-images.githubusercontent.com/16890588/169703697-54d0d5bb-51e0-4445-9e7f-d33968fface3.png">
查看链接数时可能数据太多，引起内核崩溃
<img width="978" alt="image" src="https://user-images.githubusercontent.com/16890588/169703710-f69b666e-0876-45ea-9730-9f47854fbff6.png">
在ikuai中查看openwrt链接数有近3万
<img width="1211" alt="image" src="https://user-images.githubusercontent.com/16890588/169704046-f5db8a64-fdb2-47d4-a55f-e001e07201ae.png">

**Comment by BULikeS** [comment]
+1，我也遇到了，而且还是不定时/突然出现的，全是255的UDP（路由本机）
尝试过绑定网络接口/不绑定都会出现（主路由）
只好关闭openclash再重新启动

**Comment by Karmylr** [comment]
+1

**Comment by xianren78** [comment]
回环了，debug log到相应的内核去反馈一下

**Comment by openips** [comment]
节点域名配置规则 direct

**Comment by BULikeS** [comment]
> +1，我也遇到了，而且还是不定时/突然出现的，全是255的UDP（路由本机） 尝试过绑定网络接口/不绑定都会出现（主路由） 只好关闭openclash再重新启动

通过更换不同日期的内核（P核）测试，初步排除内核问题（04.17/05.17/05.18），均会出现255UDP大量出现
依旧没特征（运行成功后几分钟/几小时内随机出现）

**Comment by 949852071** [comment]
一样遇到但是我一开立马100%，不用等时间

**Comment by loohalh** [comment]
> 回环了，debug log到相应的内核去反馈一下



> 节点域名配置规则 direct

是在这儿配置吗
<img width="1151" alt="image" src="https://user-images.githubusercontent.com/16890588/169824207-7ab03795-f2c8-4862-9606-ff7247efaad9.png">

**Comment by loohalh** [comment]
> 节点域名配置规则 direct
是在这儿配置吗

![](https://user-images.githubusercontent.com/16890588/169824207-7ab03795-f2c8-4862-9606-ff7247efaad9.png)

**Comment by loohalh** [comment]
> > +1，我也遇到了，而且还是不定时/突然出现的，全是255的UDP（路由本机） 尝试过绑定网络接口/不绑定都会出现（主路由） 只好关闭openclash再重新启动
> 
> 通过更换不同日期的内核（P核）测试，初步排除内核问题（04.17/05.17/05.18），均会出现255UDP大量出现 依旧没特征（运行成功后几分钟/几小时内随机出现） 或许可以考虑把luci-openclash-v0.45.18降到16/17试试((((

openclash怎么降级

**Comment by openips** [comment]
> > 节点域名配置规则 direct
> 是在这儿配置吗
> 
> ![](https://user-images.githubusercontent.com/16890588/169824207-7ab03795-f2c8-4862-9606-ff7247efaad9.png)
> 

不是这里 自定义规则里面加 不过现在自定义规则有bug 需要手动运行配置

**Comment by loohalh** [comment]
> > > 节点域名配置规则 direct
> > > 是在这儿配置吗
> > 
> > 
> > ![](https://user-images.githubusercontent.com/16890588/169824207-7ab03795-f2c8-4862-9606-ff7247efaad9.png)
> 
> 不是这里 自定义规则里面加 不过现在自定义规则有bug 需要手动运行配

> > > +1，我也遇到了，而且还是不定时/突然出现的，全是255的UDP（路由本机） 尝试过绑定网络接口/不绑定都会出现（主路由） 只好关闭openclash再重新启动
> > 
> > 
> > 通过更换不同日期的内核（P核）测试，初步排除内核问题（04.17/05.17/05.18），均会出现255UDP大量出现 依旧没特征（运行成功后几分钟/几小时内随机出现） 或许可以考虑把luci-openclash-v0.45.18降到16/17试试((((
> 
> openclash怎么降级



> > +1，我也遇到了，而且还是不定时/突然出现的，全是255的UDP（路由本机） 尝试过绑定网络接口/不绑定都会出现（主路由） 只好关闭openclash再重新启动
> 
> 通过更换不同日期的内核（P核）测试，初步排除内核问题（04.17/05.17/05.18），均会出现255UDP大量出现 依旧没特征（运行成功后几分钟/几小时内随机出现） 或许可以考虑把luci-openclash-v0.45.18降到16/17试试((((

卸载安装master 45-16-bea版本后一切正常

**Comment by loohalh** [comment]
> 回环了，debug log到相应的内核去反馈一下

好像是版本的问题，卸载安装master 45-16-bea版本后一切正常

**Comment by vernesong** [comment]
ipset list localnetwork 命令看看结果

**Comment by loohalh** [comment]
> ipset list localnetwork 命令看看结果

啊 刚退回beat16了，16是正常的
<img width="667" alt="image" src="https://user-images.githubusercontent.com/16890588/169833531-41fd38d8-2537-4f66-9bc5-35a6ffab7579.png">

**Comment by loohalh** [comment]
> 看看新版什么结果吧

稍等 我升级上去

**Comment by loohalh** [comment]
> 看看新版什么结果吧

beat19了，也有问题
<img width="814" alt="image" src="https://user-images.githubusercontent.com/16890588/169834390-86e65dd9-2124-4259-a336-11e8616dc5cf.png">

**Comment by loohalh** [comment]
> ipset add localnetwork 100.64.0.0/10 ipset add localnetwork 240.0.0.0/4
> 
> 输一下命令，看还有问题没

好了，正常了

**Comment by loohalh** [comment]
> ipset add localnetwork 100.64.0.0/10 ipset add localnetwork 240.0.0.0/4
> 
> 输一下命令，看还有问题没

刚才还以为又被打了，清理了一遍，今晚会有新版本吗？
