### ISSUE TITLE
常规设置中的[Github 地址修改]，meta设置页面中的[GeoIP Dat 数据库更新URL]和[GeoSite 数据库更新URL]以及版本更新clash_version.sh中URL替代问题

### ISSUE THREAD

**Issue by xianren78** [vernesong/OpenClash#2410]
问题一: 启用meta后，meta设置中[GeoIP Dat 数据库更新URL]和[GeoSite 数据库更新URL]默认的 https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/*.dat 在部分地区连通性不好，openclash_geoip.sh和openclash_geosite.sh中的逻辑是如果存在默认的URL，则直接下载默认URL，跳过了常规设置页面中的[Github 地址修改]。
这也导致在部分地区，更新geoip和geosite失败。

问题二：常规设置中的[Github 地址修改]如果使用 https://cdn.jsdelivr.net/ 或者 https://fastly.jsdelivr.net/ 对应/usr/share/openclash/clash_version.sh版本更新中的URL $github_address_mod"https://raw.githubusercontent.com/vernesong/OpenClash/"$RELEASE_BRANCH"/core_version  这种方式下载并不能使用，直接用 https://cdn.jsdelivr.net/https://raw.githubusercontent.com/vernesong/OpenClash/master/core_version 会输出Failed to fetch version info for https:. 实际上这个方式可以用的就是备注中的https://ghproxy.com/。 这个[Github 地址修改]实际上也在openclash_geoip.sh和openclash_geosite.sh中，但是由于问题一，并不会出现这个问题。

受这个影响的我看还有好几个脚本文件 openclash_update.sh openclash_ipdb.sh 都是这种方式写的

PS：下载外部资源能不能有一个选项可以使用PROXY进行下载？

**Comment by vernesong** [comment]
原则是自定义优先，内置的只是选项，保存后就认为是自定义的，没找到保存的值才会走默认逻辑

**Comment by xianren78** [comment]
> 原则是自定义优先，内置的只是选项，保存后就认为是自定义的，没找到保存的值才会走默认逻辑

我在每个curl下面都加了echo，才发现这些问题的，实际上脚本中列的那5种地址实际上大概只有2种能用到，其他都是摆设。
