### ISSUE TITLE
OpenWrt v21.02.3 同时启用 mwan3和openclash大概率卡死

### ISSUE THREAD

**Issue by goofysun** [vernesong/OpenClash#2413]
主要现象，openclash启用卡在 重启dnsmasq
然后 mwan3 无法stop或者start，命令行操作 会 timeout

mwan3状态查看会一直loading，所有流量会都走 openclash 默认的wan口…… 

尝试了几次，只要卸载openclash 就没问题了

另外 使用lean的就没有冲突问题，但lean的不支持 js渲染，部分插件不能用，比如 luci-app-wrtbwmon 支持ipv6的版本

**Comment by openips** [comment]
openwrt官方master代码没发现问题 一直使用正常

**Comment by paladin4fan** [comment]
opwnwrt官方版没问题+1

**Comment by goofysun** [comment]
> 

也试了官方版，基本上开启mwan3 并且有多条线路就跪了，不开mwan3 一切正常。
目前 只有用 lean大的  mwan3 和 openclash 使用正常

**Comment by goofysun** [comment]
> opwnwrt官方版没问题+1

找到问题原因了，打开 ipv6代理，基本就跪了，开其他的只是开启和关闭很慢，但等等还是可以开启成功的。
总结规律就是 只要不触发 修改防火墙规则 就没问题，一旦触发修改防火墙规则，命令行操作 firewall 或者 mwan3 都会超时
