### ISSUE TITLE
(已解决)观看某emby公益服的时候出现的奇怪故障，有关打开关闭仅代理命中规则流量

### ISSUE THREAD

**Issue by PN62323424** [vernesong/OpenClash#2414]
前提：
此公益服据说直连不卡，电视观看的时候我在Dashboard观察了很久，除了公益服主域名外，只看到几个香港（香港IP不是一直出现）和深圳的IP地址。

故障表现：
打开仅代理命中规则流量，主域名走规则直连，香港没命中geoip，命中了match走直连。深圳命中直连，这样就完全不卡。
关闭仅代理命中规则流量，主域名走规则直连，香港IP和深圳IP自定义规则里IP段匹配设置为直连，按理来说应该也不会卡，但实际观看的时候就会不停的卡顿。

请问这是什么原因，是我漏了什么吗。

我添加的规则如下：
- IP-CIDR,xxx.xxx.xxx.216/24,DIRECT  
- IP-CIDR,xxx.xxx.xxx.253/24,DIRECT  
- IP-CIDR,xxx.xxx.xxx.184/24,DIRECT

**Comment by XinSSS** [comment]
添加了规则, 为什么会走final呢, 规则还是有遗漏?

有没有尝试过把所有的规则暂时性的都变成DIRECT试试看有没有不卡了呢?
可以尝试使用排除法

**Comment by PN62323424** [comment]
> 添加了规则, 为什么会走final呢, 规则还是有遗漏?
> 
> 有没有尝试过把所有的规则暂时性的都变成DIRECT试试看有没有不卡了呢? 可以尝试使用排除法

是漏了。。。官方给的域名之外还有个今天发现了加上就好了，奇怪昨天都不显示的
