### ISSUE TITLE
订阅信息获取失败 检查失败

### ISSUE THREAD

**Issue by hualiuqiang** [vernesong/OpenClash#2418]
<img width="1062" alt="微信截图_20220527213656" src="https://user-images.githubusercontent.com/53924610/170710410-bf7379cc-61cb-4c2e-80c2-14bfa81f2b29.png">

**Comment by hualiuqiang** [comment]
怎么搞定啊  谢谢

**Comment by vernesong** [comment]
这个一般是连接失败了或者机场禁止获取header信息

**Comment by vernesong** [comment]
0.1kb的文件本身也有问题

**Comment by hualiuqiang** [comment]
不是，我别的软路由可以，机场节点没问题

**Comment by vernesong** [comment]
哪个机场的配置文件只有0.1kb？你自己检查

**Comment by hualiuqiang** [comment]
更新了  469.5 KB | 检查失败 还是 检查失败

**Comment by hualiuqiang** [comment]
![SharedScreenshot](https://user-images.githubusercontent.com/53924610/170846868-39ca67be-553c-4448-aeaa-301fb9d29c1b.jpg)

**Comment by hualiuqiang** [comment]
![SharedScreenshot](https://user-images.githubusercontent.com/53924610/170846892-fef3331b-bed0-4193-bea4-43bc8d884701.jpg)

**Comment by hualiuqiang** [comment]
这回这样子了   我另一个软路由就正常的

**Comment by vernesong** [comment]
你到配置文件管理看下，编辑器会提示你错误的地方
