### ISSUE TITLE
[Feature] 添加「直接使用原始配置文件启动」选项

### ISSUE THREAD

**Issue by Mosney** [vernesong/OpenClash#2419]
openclash内使用的配置文件是我自行维护的完整配置，因此我不太需要openclash额外添加额外规则以规避回环等问题，请问是否可以添加一个选项「直接使用原始配置文件启动」？根据之前看到openclash的log，如果启动失败的话启动脚本是会回落到直接使用原始配置文件启动的。

```yaml
rules:
- DST-PORT,7895,REJECT
- DST-PORT,9090,REJECT
- SRC-IP-CIDR,10.0.0.1/32,DIRECT
- SRC-IP-CIDR,198.18.0.1/32,DIRECT
```

如果不行的话，那是否可以控制不在实际运行的配置文件中加入额外的规则条目？
为了避免环路和clash log spam #1666 我选择直接不让clash处理本机发起的流量，自行修改了启动脚本删掉了`openclash_output`这条链。本想通过设置`http_proxy`环境变量的方式让OpenWrt自身的的opkg、curl等通过http代理的方式加速资源访问。但我注意到最近新版本的openclash会在配置文件规则前添加上述四条规则，其中第三条规则`10.0.0.1`这条会让所有来自OpenWrt本身发起的流量直接首先匹配上此条规则直连失去加速效果。据我观察OpenWrt自身发起的流量不全是`127.0.0.1`，有的时候还会是lan口static IP `10.0.0.1`，请问有什么办法可以让openclash不添加这条规则呢？

**Comment by vernesong** [comment]
没这条，自己看看自定义是不是写了

**Comment by Mosney** [comment]
> 没这条，自己看看自定义是不是写了

并没有添加任何规则，自定义规则这个复选框也是非勾选状态，在配置文件管理中可以看到确实是前面多出了4条规则

---
![图片](https://user-images.githubusercontent.com/22477230/170770815-1f0f4abb-346d-4359-a19c-d6ba743199fe.png)

---
![图片](https://user-images.githubusercontent.com/22477230/170770925-1588a424-e958-4eef-a859-b5a1350bd953.png)
---
![图片](https://user-images.githubusercontent.com/22477230/170771097-6b955808-6f75-4e75-9a36-8b4cf96c06ea.png)

**Comment by Mosney** [comment]
看了一下yml处理脚本，应该是在这里加入的这4条额外的规则
https://github.com/vernesong/OpenClash/blob/56dda468b0ec78ed110b5712ff36fac66d38f360/luci-app-openclash/root/usr/share/openclash/yml_rules_change.sh#L629-L648

**Comment by Mosney** [comment]
用最简单粗暴的方法，直接把上述这两段删掉即可暂时达成上述“去掉额外添加的4条规则”的目的。

---
另外刚注意到openclash是强制补全配置文件里所有端口号的设置，而不管是否实际需要。懒得去找脚本里加端口的逻辑部分了，多占用几个端口号无伤大雅
![图片](https://user-images.githubusercontent.com/22477230/170840492-78834f95-0cca-4969-a191-652d192915a0.png)

**Comment by Mosney** [comment]
**尽管可以手动删减脚本达成我的需求，但还是希望openclash能在未来的版本添加一个「直接使用原始配置文件启动」，以方便更多样的用户群体按需选择自己所需要的功能。
对我来说oopenclash提供clash之外的附加功能过于庞杂且交互起来需要不小的学习成本，就不如索性自己维护一份完整的clash配置文件，仅使用openclash提供的启动脚本、守护进程来的更简单方便。**

@vernesong

**Comment by Mosney** [comment]
同样原因引发的问题： #2374
