### ISSUE TITLE
內核無法離線安裝

### ISSUE THREAD

**Issue by deepfish** [vernesong/OpenClash#242]
你好，我重裝了新版本的 openclash，一直無法在線更新內核。
於是想離線安裝內核 https://github.com/vernesong/OpenClash/releases/download/Clash/clash-linux-amd64.tar.gz 下載完成後，解壓縮得到 “clash”文件，並將其上傳至 /etc/openclash 目錄。其後對文件權限進行 0755 設置。
設置完成後，再次查看“版本更新”，裡面的“当前内核版本”一直為未知狀態。即使重啟路由器也無法識別。

**Comment by vernesong** [comment]
架构正确吗？尝试之前版本的内核呢？

**Comment by deepfish** [comment]
架構正確，操作無異常。
後來把路由器系統備份設置，重裝了。重裝後一切正常，只是下載內核時，需要先讓路由器進行科學上網。
