### ISSUE TITLE
openclash无法打开任何网站

### ISSUE THREAD

**Issue by iceye2072** [vernesong/OpenClash#2420]
用了订阅机场的节点，所有网站都显示无法打开，youtube偶尔可以打开界面，让后播放视频的时候就是黑屏转圈。
我自己的配置文件（手动输入的节点），无问题。
以前不是这样，因为自己买的vps有点问题，切换成订阅的机场发现都不能用（试了5个机场，一样的情况）
路由器是旁路有。
试了全局，关闭dns上游，都无效果。

求解。

**Comment by iceye2072** [comment]
这些机场的订阅，在苹果手机里的QuantumultX都正常，只有openclash无法用。

**Comment by chenyunwow** [comment]
我和你一样 播放视频就是黑屏转圈。后面

**Comment by alanzhu2019** [comment]
我的现象是油管可以打开，只能加载图片，视频播放不出来。

**Comment by chenyunwow** [comment]
我前天更新了软路由 好像重新设置下好了，但是具体怎么弄好也不知道如何弄好，以前是youtu 能打开 但是视频没，旁边的视频 加载加载图片 下面的文字都能很快加载出来，就是放视频转圈。我目前使用 V.45.22版本 这是链接https://github.com/vernesong/OpenClash&nbsp; 你看看 配置我这里选增强模式，现在我这里可以用了，我的软路由是1230V2 希望能帮到你


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vernesong/OpenClash"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月29日(星期天) 晚上11:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [vernesong/OpenClash] openclash无法打开任何网站 (Issue #2420)





 
我的现象是油管可以打开，只能加载图片，视频播放不出来。

**Comment by czxinshui** [comment]
> 我的现象是油管可以打开，只能加载图片，视频播放不出来。

PC还是手机？PC的话，浏览器设置为安全DNS 就可以了

**Comment by chenyunwow** [comment]
我现在 一切正常，图片 视频 都可以看 关键我不知道 怎么弄好的，我好想重新升级了下，然后全部重启了下，再设置了关闭 那个游戏加速功能。就好了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vernesong/OpenClash"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月30日(星期一) 下午5:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [vernesong/OpenClash] openclash无法打开任何网站 (Issue #2420)





  
我的现象是油管可以打开，只能加载图片，视频播放不出来。
  
PC还是手机？PC的话，浏览器设置为安全DNS 就可以了

**Comment by MartinDai** [comment]
> 

我最近也碰到了  然后今天折腾了一下  关闭了IPV6的DHCP相关服务  换成fake-ip模式  就好了

**Comment by chenyunwow** [comment]
Fake-IP&nbsp; &nbsp;增强&nbsp; IPV6 DHCP 必须关闭的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vernesong/OpenClash"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月11日(星期六) 晚上9:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [vernesong/OpenClash] openclash无法打开任何网站 (Issue #2420)





   
我最近也碰到了  然后今天折腾了一下  关闭了IPV6的DHCP相关服务  换成fake-ip模式  就好了
