### ISSUE TITLE
IP错误？？

### ISSUE THREAD

**Issue by huangfengye** [vernesong/OpenClash#243]
![image](https://user-images.githubusercontent.com/26798988/76697279-41b78b80-66d0-11ea-84af-a1c3bb6c6868.png)

**Comment by vernesong** [comment]
访问正常即可，因为检测的客户端而非路由，会受到规则判定的影响

**Comment by huangfengye** [comment]
> 访问正常即可，因为检测的客户端而非路由，会受到规则判定的影响

逼死强迫症。😄

**Comment by vernesong** [comment]
你可以把那两个国外域名加到自定义规则，让他走代理
