### ISSUE TITLE
配置文件订阅错误

### ISSUE THREAD

**Issue by vindia9** [vernesong/OpenClash#244]
你好
我的配置文件订阅一直提示错误，换过其他服务方的配置文件订阅地址，也没有成功过。
日志只有这么一条：

2020-03-15 15:21:00 Config 【config1】Update Error

开了debug也没有更多日志出现。
在openwrt上ping订阅的域名正常，wget正常。订阅地址为https服务，config内不包含emoji。

请问有什么方式可以进一步定位问题吗？

谢谢！

**Comment by vernesong** [comment]
什么版本？新版依赖换成curl了

**Comment by vindia9** [comment]
你好，问题已经解决，谢谢！
确认是curl的问题，我重新编译了curl，之前的版本不支持ssl。
OpenClash版本是最新版v0.36.11-beta
