### ISSUE TITLE
[Bug] Bash找不到po2lmo命令

### ISSUE THREAD

**Issue by LittleNewton** [vernesong/OpenClash#2441]

**Comment by BabXhwZUNBeTV** [comment]
百度一下 谷歌一下 必应一下 不会死吧？[https://www.bing.com/search?q=po2lmo%3A+command+not+found&PC=U316&FORM=CHROMN](url)
[https://blog.csdn.net/x13163303344/article/details/70062361](url)
[https://www.right.com.cn/forum/thread-1086753-1-1.html](url)
