### ISSUE TITLE
[Bug] Edge/Chrome浏览器下的Subscription Info显示错误

### ISSUE THREAD

**Issue by jiayuqian** [vernesong/OpenClash#2447]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.22-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Other, All

### To Reproduce

Openwrt - Services - OpenClash
Openwrt - Services - OpenClash - Config Manage

### Describe the Bug

Edge/Chrome浏览器下的“Subscription Info”布局异常，无法查看和执行配置文件相关信息和操作，如：Update Time, Size, Grammar Check	Switch Config, Edit, Copy Config, Rename, Download Config, Download Running, Config Remove

### OpenClash Log

OpenClash 调试日志

生成时间: 2022-06-05 15:11:55
插件版本: 
隐私提示: 上传此日志前请注意检查、屏蔽公网IP、节点、密码等相关敏感信息

```

#===================== 系统信息 =====================#

主机型号: Linksys WRT1900ACS
固件版本: OpenWrt 21.02.0 r16279-5cc0535800
LuCI版本: 
内核版本: 5.4.143
处理器架构: arm_cortex-a9_vfpv3-d16

#此项有值时,如不使用IPv6,建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: 

#此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 127.0.0.1#7874

#===================== 依赖检查 =====================#

dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
iptables-mod-tproxy: 已安装
kmod-ipt-tproxy: 已安装
iptables-mod-extra: 已安装
kmod-ipt-extra: 已安装
libcap: 已安装
libcap-bin: 已安装
ruby: 已安装
ruby-yaml: 已安装
ruby-psych: 已安装
ruby-pstore: 已安装
ruby-dbm: 已安装
kmod-tun(TUN模式): 已安装
luci-compat(Luci-19.07): 已安装
kmod-inet-diag(PROCESS-NAME): 未安装

#===================== 内核检查 =====================#

运行状态: 运行中
进程pid: 25108
运行权限: 25108: cap_dac_override,cap_net_bind_service,cap_net_admin,cap_net_raw,cap_sys_ptrace,cap_sys_resource=eip
2668: =ep
运行用户: nobody
已选择的架构: linux-armv6

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 2022.05.18
Tun内核文件: 存在
Tun内核运行权限: 正常

Dev内核版本: v1.10.6-9-g9d2fc97
Dev内核文件: 存在
Dev内核运行权限: 正常
Meta内核版本: alpha-gd0268bb
Meta内核文件: 存在
Meta内核运行权限: 正常

#===================== 插件设置 =====================#

当前配置文件: /etc/openclash/config/clash@qx.noreply.yaml
启动配置文件: /etc/openclash/clash@qx.noreply.yaml
运行模式: redir-host-mix
默认代理模式: rule
UDP流量转发(tproxy): 停用
DNS劫持: 启用
自定义DNS: 停用
IPV6代理: 停用
IPV6-DNS解析: 停用
禁用Dnsmasq缓存: 启用
自定义规则: 启用
仅允许内网: 停用
仅代理命中规则流量: 停用
仅允许常用端口流量: 停用
绕过中国大陆IP: 启用
DNS远程解析: 启用
路由本机代理: 停用

#启动异常时建议关闭此项后重试
混合节点: 停用
保留配置: 停用

#启动异常时建议关闭此项后重试
第三方规则: 停用

### OpenClash Config

```shell
11
```

### Expected Behavior

修复显示布局

### Screenshots

<img width="928" alt="1" src="https://user-images.githubusercontent.com/72557068/172040089-4d949f81-f1cb-4e9e-8121-84ef839d81fc.png">
<img width="928" alt="1" src="https://user-images.githubusercontent.com/72557068/172040127-754105a3-a755-445c-9782-9dbcba17ef16.png">

**Comment by vernesong** [comment]
无限流量吗

**Comment by jiayuqian** [comment]
无限量或者超过1TB+

**Comment by vernesong** [comment]
```
curl -sLI -H 'User-Agent: Clash' url

看一下header

**Comment by jiayuqian** [comment]
![image](https://user-images.githubusercontent.com/72557068/172040904-dff14b23-d273-426d-ab17-3a4a67540ac2.png)
没有输出结果~

**Comment by vernesong** [comment]
后面写你订阅地址

**Comment by jiayuqian** [comment]
![image](https://user-images.githubusercontent.com/72557068/172041023-1df32b63-9225-4bea-bd3a-a74bf86c71c2.png)

**Comment by jiayuqian** [comment]
感觉是total小数点后面的位数太多？

**Comment by vernesong** [comment]
不是，没考虑科学计数

**Comment by jiayuqian** [comment]
会在下个版本中修复不？
