### ISSUE TITLE
更新至最新内核及客户端问题

### ISSUE THREAD

**Issue by evileonline** [vernesong/OpenClash#245]
Web更新页面进行更新……内核与客户端正确识别并安装后，显示不识别x86系统，之前运行科学上网无任何问题……查看全局设置后发现没有问题，点击保存设置并应用后……再次查看全局设置页面显示如下图内容……

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by evileonline** [comment]
![IMG_4855](https://user-images.githubusercontent.com/36870868/76700286-e8138900-66f0-11ea-8ad5-eeb770236971.PNG)

**Comment by vernesong** [comment]
最新版的内核显示不出版本号吗？

**Comment by evileonline** [comment]
在Web页面更新后，没有立刻显示x86系统……但内核版本和客户端都有显示……我后来是直接重新刷机解决的问题……
