### ISSUE TITLE
[Bug] meta alpha-gd0268bb内核，内网ssh无法连接，之前版本可以，同时openclash的localnetwork ipset列表无192.168.0.0/16网段，导致内网ssh访问失败。

### ISSUE THREAD

**Issue by hiyuxiang** [vernesong/OpenClash#2451]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.22-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

启动openclash,访问内网ssh

### Describe the Bug

meta alpha-gd0268bb内核，内网ssh无法连接，之前版本可以，同时openclash的localnetwork ipset列表无192.168.0.0/16网段，导致内网ssh访问失败。

### OpenClash Log

应该不需要log

### Expected Behavior

把192.168.0.0/16加入localnetwork ipset

**Comment by vernesong** [comment]
ip route

看下输出

**Comment by hiyuxiang** [comment]
我是openvpn至软路由，要访问的是192.168.5网段192.168.5.254上的ssh,有这样的路由信息
     192.168.5.0    255.255.255.0        10.18.4.1        10.18.4.3     35
完整的路由信息如下：
tracert 192.168.5.254
通过最多 30 个跃点跟踪到 192.168.5.254 的路由

  1     5 ms     5 ms     6 ms  10.18.4.1    （这个是openvpn服务器，其ip为172.22.18.248,也是openclash服务所在）
  2     6 ms     5 ms     *     172.22.18.253  （这个是我主路由）
  3    16 ms    18 ms     7 ms  172.22.18.1   （这个是我交换机ip, 上头有个vlan是网段192.168.5)
  4     6 ms     9 ms     6 ms  192.168.5.254   
在更新meta内核前，ssh无问题，更新后出问题，但把openclash服务关闭，即恢复正常，应该是meta内核的新版本有问题所致，但因是内网地址有问题，所以如果在/etc/init.d/openclash脚本里加入ipset add localnetwork 192.168.0.0/16，同样也能解决问题，所以希望可以加入，避免后面每次版本升级都要手工添加，至于meta内核新版是什么问题，没有深究。

**Comment by vernesong** [comment]
clash规则直连了没有

**Comment by hiyuxiang** [comment]
规则设直连了，同一台机（openvpn客户端），浏览器通过直连或代理访问192.168.5.254上8006端口的web服务（pve的管理页面）都能访问，但ssh无法访问，提示如下：
Connecting to 192.168.5.254:22...
Connection established.
To escape to local shell, press 'Ctrl+Alt+]'.
Connection closing...Socket close.

Connection closed by foreign host.
在把192.168加入localnetwork使其不走clash内核后，正常。

**Comment by vernesong** [comment]
试试29
