### ISSUE TITLE
[Bug] default nameserver should be pure IP

### ISSUE THREAD

**Issue by BULikeS** [vernesong/OpenClash#2453]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.28-beta

### Bug on Environment

Other

### Bug on Platform

All

### To Reproduce

None

### Describe the Bug

我使用的配置文件仅有 `proxy-groups` `proxy-providers` `rule-providers` `rules` 这四部分（clash for windows运行正常）
DNS部分则使用openclash的自定义DNS（全部为IP形式的DOH）
当我启动openclash时，提示 `default nameserver should be pure IP`
`default-nameserver` 参数非必须参数（当加密DNS为IP形式时）
以往版本我没添加 `default-nameserver` 也可以正常启动

### OpenClash Log

None

### Expected Behavior

None

**Comment by BULikeS** [comment]
最新版本 v0.45.29-beta 已修复，此iss关闭
大佬辛苦了~

**Comment by djoeni** [comment]
confirmed fix with dev and tun core, but not with meta core there is still tcp, https dns written in default nameserver. Or is supposed that way with meta core?

**Comment by vernesong** [comment]
only meta

**Comment by zZPiglet** [comment]
@vernesong 您好，"Parse config error: default nameserver should be pure IP" 的问题在使用 Meta 内核时依然存在，我使用的是版本是：  
[Meta] 当前内核版本 | alpha-g01d2e88  
当前客户端版本 | v0.45.30-beta

**Comment by vernesong** [comment]
meta 新版支持
