### ISSUE TITLE
[Feature] 关于DNS挟持问题

### ISSUE THREAD

**Issue by luckyyyyy** [vernesong/OpenClash#2457]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

https://github.com/vernesong/OpenClash/blob/master/luci-app-openclash/root/etc/init.d/openclash#L1060

这里的挟持是为了什么？建议只作为dnsmasq上游服务器 会与内网部分功能冲突

<img width="1100" alt="image" src="https://user-images.githubusercontent.com/9210430/172516305-45e6a530-8655-4e4e-8f9f-509e58283ca0.png">

### Describe the Solution

建议不要默认挟持，可选挟持，仅作为上游，现在是两个放在一起了

**Comment by vernesong** [comment]
你没看明白代码，53的取值来自dnsmasq

**Comment by luckyyyyy** [comment]
> 你没看明白代码，53的取值来自dnsmasq

我的意思是，我偶尔需要在客户端上临时设置下别的DNS，验证下域名DNS是否生效，不希望完全走网关的dns，这条设置后，无论客户端怎么设DNS，都会被转发过去。

$ dig www.baidu.com @2.2.2.2 +short
www.a.shifen.com.
180.101.49.11
180.101.49.12
