### ISSUE TITLE
lhie1规则问题

### ISSUE THREAD

**Issue by evileonline** [vernesong/OpenClash#246]
使用刘大2020年3月1日前的规则可以正常科学上网，但更新规则后，无法访问YouTube……使用ConnersaHua规则，可以正常科学上网……版本0.36.7-beta，内核v0.18.0-15-g9471d80，处理架构x86_64

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by vernesong** [comment]
控制面板检查链接日志排查问题

**Comment by yanyingjie007** [comment]
我也这样，能打开youtube,不能播放，等再次更新吧

**Comment by evileonline** [comment]
> 控制面板检查链接日志排查问题

控制面板内容显示，全部直连……没有其他策略数据走……策略组正常显示……之后我会再仔细看看

**Comment by evileonline** [comment]
今日更新了刘大的策略，显示3月19日……策略恢复正常使用……
