### ISSUE TITLE
[Bug] 第三方规则集与策略组管理中的规则永远出现在自定定义规则之后

### ISSUE THREAD

**Issue by htfcuddles** [vernesong/OpenClash#2461]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.30-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-386

### To Reproduce

1. 第三方规则集与策略组管理中添加规则A，优先级：**优先-覆盖**
<img width="720" alt="image" src="https://user-images.githubusercontent.com/23210827/172678296-f71c22f9-6869-421b-947e-44cf35e330f7.png">

2. 自定义规则中设置自定义规则B，优先级：**候补匹配**

  `- GEOSITE,cn,DIRECT`

3. 无论如何调整规则A和规则B的优先级，修改后的配置文件中规则A总会出现在规则B之后

### Describe the Bug

第三方规则集与策略组管理的优先级与预期不符

### OpenClash Log

```
rules:
- DST-PORT,7895,REJECT
- DST-PORT,7892,REJECT
- IP-CIDR,198.18.0.1/16,REJECT,no-resolve
- IP-CIDR,8.8.8.8/32,FAST
- IP-CIDR,1.1.1.1/32,FAST
- GEOSITE,cn,DIRECT
- MATCH,FINAL
- RULE-SET,Netflix,NETFLIX
- RULE-SET,GoogleSearch,FAST
```

### Expected Behavior

 第三方规则集与策略组管理中添加**规则A**（优先级：优先-覆盖） 出现在 自定义规则中设置自定义**规则B**（优先级：候补匹配 ）之前
```
rules:
- DST-PORT,7895,REJECT
- DST-PORT,7892,REJECT
- IP-CIDR,198.18.0.1/16,REJECT,no-resolve
- IP-CIDR,8.8.8.8/32,FAST
- IP-CIDR,1.1.1.1/32,FAST
- RULE-SET,Netflix,NETFLIX
- RULE-SET,GoogleSearch,FAST
- GEOSITE,cn,DIRECT
- MATCH,FINAL
```

**Comment by vernesong** [comment]
![image](https://user-images.githubusercontent.com/42875168/172761543-703b944c-a542-477a-b1ca-597c98890810.png)
![image](https://user-images.githubusercontent.com/42875168/172762003-4a43eae2-ef88-41f1-8775-378e3dfaeba9.png)

![image](https://user-images.githubusercontent.com/42875168/172761977-0d5c3148-5c75-46e8-9ec5-95bb09e76680.png)
复现不了
