### ISSUE TITLE
[Bug] 更新到v0.45.30-beat后描述文件显示剩余0天，所有节点无法链接

### ISSUE THREAD

**Issue by loohalh** [vernesong/OpenClash#2464]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.30-beat

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

更新到v0.45.30-beat后所有节点都无法链接，同样的节点再手机和电脑clash客户端使用都正常

### Describe the Bug

描述文件状态显示剩余0天，但实际时间还很远
<img width="1149" alt="image" src="https://user-images.githubusercontent.com/16890588/172967387-8576aa1b-7a02-43cf-aca9-fe0c4af5d275.png">

### OpenClash Log

<img width="1174" alt="image" src="https://user-images.githubusercontent.com/16890588/172967590-6e04a6c8-afc8-46c4-a609-0f1edb304e0a.png">

### Expected Behavior

能正常链接节点使用

### Screenshots

<img width="1171" alt="image" src="https://user-images.githubusercontent.com/16890588/172967755-bf976f9e-96a2-43fb-955a-657c25647db0.png">

**Comment by vernesong** [comment]
你这版本不对吧，重启重装一下

**Comment by loohalh** [comment]
> 你这版本不对吧，重启重装一下

卸载重新安装了 好了
