### ISSUE TITLE
[Feature] 更新至v0.45.30-beat后流媒体增强功能消失，是否可以恢复该功能功

### ISSUE THREAD

**Issue by hjj0421** [vernesong/OpenClash#2468]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

没有该功能很不方便

### Describe the Solution

是否可以增加谢谢

**Comment by vernesong** [comment]
模式设置-路由本机代理
