### ISSUE TITLE
仅代理命中规则流量开关开启后，还需要设置BT设备SRC-IP-CIDR直连吗？

### ISSUE THREAD

**Issue by LarkinZero** [vernesong/OpenClash#247]
更新了v0.36.11-beta多了这个开关后，不知道具体需要如何使用
打开后是自动将MATCH,DIRECT加入了配置文件结尾吗？

**Comment by vernesong** [comment]
对，但建议设置SRC-IP规则完全屏蔽下载机，如果个人设备会偶尔下载的话请开启仅代理

**Comment by LarkinZero** [comment]
我观察到订阅的规则最后是MATCH,代理
如果OpenClash加上了MATCH,DIRECT
订阅规则的MATCH,代理，还会生效吗

**Comment by vernesong** [comment]
会帮你注释掉
