### ISSUE TITLE
更新到最新版后，发现OPENCLASH页面标签一直转圈。

### ISSUE THREAD

**Issue by kevinyang68** [vernesong/OpenClash#2470]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

OPENCLASH 正常代理可以上网，就是打开OPENCLASH的运行状态页面，网页标签一直显示转圈，发现状态是不是等待OPENWRT网关响应 就是等待网络检查的各种响应，我点击关闭自动刷新后，也没用，切回来后，自动刷新还是打开状态。

### Describe the Solution

请问如何解决该问题？

**Comment by vernesong** [comment]
dev已修复

**Comment by shu0802** [comment]
.33版master修复了吗？
