### ISSUE TITLE
[Feature] 游戏规则与策略组管理建议添加优先级选项

### ISSUE THREAD

**Issue by HoldOnBro** [vernesong/OpenClash#2476]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

默认为补充条款，这对于游戏规则来说不合理

### Describe the Solution

像第三方规则一样可选优先级为覆盖即可解决

**Comment by vernesong** [comment]
不建议置顶，你可以在自定义规则集与策略组管理里面设置为优先匹配
