### ISSUE TITLE
clash配置文件订阅中的特殊字符[Feature] 

### ISSUE THREAD

**Issue by xiaoxiongwn** [vernesong/OpenClash#2479]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

openclash中的配置文件订阅中，添加的订阅地址中的节点如果有特殊字符的话，比如“ss://YU5QCQq@140.225.128168:25554”这种节点中带有特殊字符“@”。则节点是无效的，导致更新配置不会更新节点。能不能请求改进一下，可以允许节点中带有特殊字符呢？谢谢你们！

### Describe the Solution

v2ray可以支持特殊字符“@”。能不能借鉴一下？

### Describe Alternatives

无

### Additional Context

再次感谢

**Comment by vernesong** [comment]
subconverter不支持

**Comment by xiaoxiongwn** [comment]
为什么clash of windows导入带有“@”字符的节点没有问题，但openclash对带有“@”的节点却无法导入呢？

**Comment by xiaoxiongwn** [comment]
还是没法更新带@的节点。网上找到的节点好多都带@字符，都不能用，大家有啥办法吗？
