### ISSUE TITLE
openclash_version 文件位置

### ISSUE THREAD

**Issue by sunxun47** [vernesong/OpenClash#248]
建议将/etc/openclash 下的openclash_version 文件挪到/usr/share/openclash 下。
如果openclash 随固件编译更新，并希望保留配置，设置为直接保留/etc/openclash 最简单，但是这种情况下openclash_version 文件不会被覆盖，升级完成后版本识别不对。

**Comment by vernesong** [comment]
更新是直接卸载再安装的形式，不会保留版本号的文件

**Comment by sunxun47** [comment]
可能我没说清楚，以ipk 安装的形式，直接在openclash 中点更新是会更新版本号的，像你说的一样，是卸载再安装的形式。这个没有问题。

我的应用场景是这样的，固件里面集成了openclash，没有单独安装ipk，每隔一段时间用升级固件的形式更新整个openwrt 包括openclash，因为希望保留openclash 的一系列设置，就将/etc/openclash 设置到了openwrt 的备份清单中。如果更新openwrt 固件的同时openclash 有版本号变化，升级固件后，openclash 确实升级了，但是版本文件因为在配置文件夹中，不会改变。

**Comment by vernesong** [comment]
保留配置更新固件的时候备份配置里面已经添加了需要保留的文件。接下来我会把核心也包括进去

**Comment by sunxun47** [comment]
好的，谢谢。
