### ISSUE TITLE
关于Openclash功能疑问

### ISSUE THREAD

**Issue by Nanyu123456** [vernesong/OpenClash#2486]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

因为一些特殊原因我只能通过ssh来连接我的软路由 

### Describe the Solution

openclash是否具有指令开关的功能？
如果没有是否可以开发？

**Comment by vernesong** [comment]
暂时没有，可以执行init.d文件里的启动关闭命令

**Comment by Nanyu123456** [comment]
> 暂时没有，可以执行init.d文件里的启动关闭命令

谢谢 请问具体开关的指令是什么呢
