### ISSUE TITLE
[Bug] Unknown alias: xxxxx

### ISSUE THREAD

**Issue by Rakau** [vernesong/OpenClash#2487]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.30-beta

### Bug on Environment

Lean

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

使用如下配置

proxy-providers:
    司令部: &ggggg
        type: http
        url: "地址"
        path: ./providers/司令部.yaml
        interval: 86400
        health-check:
          enable: true
          url: http://cp.cloudflare.com
          interval: 180
          tolerance: 200

    香港:
     <<: *ggggg
     filter: "港|香港|hk|HK|hongkong|HongKong"
    新加坡:
     <<: *ggggg
     filter: "新|新加坡|sgp|SGP|sg|SG"
    日本:
     <<: *ggggg
     filter: "日|日本|jp|JP|japan|Japan"
    韩国:
     <<: *ggggg
     filter: "韩|韩国|kr|KR|korea|KOREA"
    俄罗斯:
     <<: *ggggg
     filter: "俄|俄罗斯|ru|RU|Russia|russia"
    美国:
     <<: *ggggg
     filter: "美|美国|us|US|USA|usa"
    普通:
     <<: *ggggg
     filter: "普通"
    专线:
     <<: *ggggg
     filter: "专线"

### Describe the Bug

如上

### OpenClash Log

2022-06-16 19:25:49 错误：配置文件格式校验失败...
2022-06-16 19:25:44 错误：配置文件解析失败，【Unknown alias: ggggg】

### OpenClash Config

```shell
P核已有
```

### Expected Behavior

正常工作

**Comment by vernesong** [comment]
我这边没问题，考虑是ruby的版本问题

**Comment by Rakau** [comment]
> 我这边没问题，考虑是ruby的版本问题

版本是3.1.2-1

**Comment by ZealousLyon** [comment]
ruby版本3.1.2-2同样复现

```
2022-08-01 18:54:07 错误：配置文件解析失败，【Unknown alias: All】
2022-08-01 18:54:07 开始更新配置文件【Zealous】...
```

**Comment by vernesong** [comment]
下个版本修复
