### ISSUE TITLE
openclash_rule.sh脚本似乎有问题

### ISSUE THREAD

**Issue by maskedeken** [vernesong/OpenClash#249]
如果开启了clash，curl更新规则的时候会带上-U参数，这时如果没有开启proxy认证，curl会提示
Enter proxy password for user '':

然后报错退出

**Comment by vernesong** [comment]
报什么错？

**Comment by maskedeken** [comment]
就是下载不成功，直接运行/usr/share/openclash/openclash_rule.sh就会一直卡住，我在curl那一行后面重定向了错误信息，就看到Enter proxy password for user '':，应该是卡在提示输入密码这里

**Comment by maskedeken** [comment]
还有一个疑问，openclash_rule.sh最后一句用sed替换掉lhie1.yaml所有换行符的作用是什么？这一句是个很耗时的操作，最终执行结果也没有保存下来

**Comment by vernesong** [comment]
建议你去掉-sl参数看看，去换行符是因为那规则时常会有这种问题导致启动失败
