### ISSUE TITLE
启用ipv6代理后可否不进行nat转换

### ISSUE THREAD

**Issue by k2p2p** [vernesong/OpenClash#2491]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

目前启用代理ipv6流量以后，所有的v6访问都nat成了网关地址，能否不进行nat，直接转发

### Describe the Solution

ipv6不进行nat，直接转发

**Comment by vernesong** [comment]
经过内核的都会nat
