### ISSUE TITLE
[Feature] 希望能增加对纯ipv6节点的支持

### ISSUE THREAD

**Issue by a597232887** [vernesong/OpenClash#2494]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

目前openclash无法连接纯ipv6机器搭建的节点，或设置项名目和文档不明确。目前使用hax,woiden,dein,scaleway,webhorizon,gullo等纯ipv6公网搭建的节点全部无法连接。已通过v2rayN,添加中转等方法确定节点正常工作。

### Describe the Solution

希望能增加对纯ipv6节点的支持。如已支持，希望能有更明确的设置项名目和文档。

**Comment by hcym** [comment]
听不懂，纯ipv6一样的用，无非是机器上需要设置一个ipv4的隧道，clash这边实现双栈可能需要自己折腾吧

**Comment by a597232887** [comment]
> 

你这不是听懂了吗？你提出需要在机器上进行某个操作，不就是说明openclash不支持，所以需要机器上操作来支持openclash？

**Comment by hexin-lin-1024** [comment]
> > 
> 
> 你这不是听懂了吗？你提出需要在机器上进行某个操作，不就是说明openclash不支持，所以需要机器上操作来支持openclash？

你这个问题应该到内核提，而且Clash是支持纯IPv6节点的，OpenClash也早就添加了IPv6流量代理功能。

**Comment by github-office** [comment]
纯IPv6节点本来就能用啊，软路由有IPv6地址，在openClash设置里面勾选几个IPv6的DNS就行。我这里测试了很多翻墙插件，就openClash能用纯IPv6节点，ssr+、passwall都不能用
