### ISSUE TITLE
[Bug] OP内核5.15，机场订阅信息获取失败

### ISSUE THREAD

**Issue by winner890302** [vernesong/OpenClash#2495]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

0.45.30

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

机场订阅信息获取失败， 手里3个大机场都是如此

### Describe the Bug

不能显示机场订阅信息：流量 、到期时间

翻墙功能一切正常

### OpenClash Log

111111

### Expected Behavior

显示机场订阅信息：流量 、到期时间

### Screenshots

![无标题](https://user-images.githubusercontent.com/59077925/174435571-c71acaac-a48c-46c1-b5cb-364048297861.png)

**Comment by vernesong** [comment]
自行curl -I 测试连接情况
