### ISSUE TITLE
[Bug] 错误：【TUN】内核最新版本检测失败，请稍后再试...

### ISSUE THREAD

**Issue by yqchilde** [vernesong/OpenClash#2499]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.33-beta

### Bug on Environment

Other

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

点击更新TUN内核->在线更新 / 手动下载

### Describe the Bug

在线更新失败，尝试手动更新，发现并没有指向包，不确定是下载TUN需要其他条件还是什么，看了下代码，发现判断这边是有一句判断不到的。

<img width="950" alt="image" src="https://user-images.githubusercontent.com/36953759/174476740-07a9ece8-ee9b-407c-a386-4670c98b12e5.png">

### OpenClash Log

错误：【TUN】内核最新版本检测失败，请稍后再试...

### Expected Behavior

提示更新失败是基于什么没有安装或设置的前提下才会失败

### Screenshots

<img width="1078" alt="image" src="https://user-images.githubusercontent.com/36953759/174476859-a72f73ab-126e-44c9-98c4-d3443f52be84.png">

_No response_

**Comment by yqchilde** [comment]
补充：群友帮忙测试是正常的，所以我这里corelv用split分割不到，是因为我缺失了什么配置吗

**Comment by vernesong** [comment]
下载失败了，版本更新是后台下载https://github.com/vernesong/OpenClash/blob/master/core_version

**Comment by yqchilde** [comment]
奇怪了，我挂了梯子了，订阅也更新失败，在线更新客户端以及内核也全是失败，最后都是手动上传的

**Comment by wydinhk** [comment]
同遇到了……单独降级内核、客户端无效

**Comment by albuslee** [comment]
折腾了一个小时，直接wget tar也不行
最后发现是需要安装这个页面里的依赖 https://github.com/vernesong/OpenClash/releases
