### ISSUE TITLE
[Bug] 新版 Dev 内核无法转发 UDP

### ISSUE THREAD

**Issue by Mipa233** [vernesong/OpenClash#2500]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.33-beta

### Bug on Environment

Lean

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

使用 v1.10.6-15-ge0c5a85 之后的 DEV 内核，均无法转发 UDP 链接。

使用 v1.10.6-12-g09d49ba 之前的 DEV 内核都正常转发 UDP 链接。

### Describe the Bug

新版 Dev 内核无法正常转发UDP

### OpenClash Log

无

### Expected Behavior

修复UDP无法转发的问题。

**Comment by XinSSS** [comment]
确实, 更新之后我的游戏打开连不到服务器了

**Comment by vernesong** [comment]
那应该是内核的问题，可以去那边提

**Comment by XinSSS** [comment]
https://t.me/c/1241423769/243346
@Mipa233 有人说已经修了， 但是1.11内核我试了下好像不行， 你试了吗？

**Comment by NorthShad0w** [comment]
@XinSSS 我更新后一切正常了

**Comment by XinSSS** [comment]
嗯, 现在问题解决了
