### ISSUE TITLE
[Bug] 外部使用DDNS远程连接家中路由器，管理页面映射端口生效不完全

### ISSUE THREAD

**Issue by HoldOnBro** [vernesong/OpenClash#2502]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.33-beta

### Bug on Environment

Lean

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

![GpC3LsHLYo](https://user-images.githubusercontent.com/16101088/174510090-2284b8cf-ed2f-4cc6-9ce8-54cfd570d998.png)

点击首页的打开控制面板会跳转到如下地址，无法正常访问，必须手动修改前面9090为外部映射端口

![tf5FYY31y6](https://user-images.githubusercontent.com/16101088/174509964-626d0ebd-95da-4fe6-9f73-d80cd35cb599.png)

### Describe the Bug

映射端口只在后面port=xxxx部分生效了

### OpenClash Log

无须log

### Expected Behavior

前面URL里冒号后面的端口号应当也是填写的映射端口，和后面port=XXXX保持一致

**Comment by slevin57** [comment]
一样的问题
