### ISSUE TITLE
[Bug] 最新版meta内核无法正常启动vless代理的配置文件

### ISSUE THREAD

**Issue by dawei233** [vernesong/OpenClash#2509]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.33-beta

### Bug on Environment

Lean

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

使用mete内核启动 vless代理转换的配置文件

### Describe the Bug

vless代理的配置文件启动就内核崩溃。同配置文件在用windwos客户端启动就可以，排除配置文件问题

### OpenClash Log

[OpenClash-2022-6-25-15-40-4.log](https://github.com/vernesong/OpenClash/files/8984135/OpenClash-2022-6-25-15-40-4.log)

### Expected Behavior

能用就行

**Comment by lingyunzhiss** [comment]
我也认为是最新版的meta的内核问题alpha-g30a0834，占用高，cpu热，4项延迟间歇性过千。要能回退到上一版本就好了。

**Comment by dawei233** [comment]
> 我也认为是最新版的meta的内核问题alpha-g30a0834，占用高，cpu热，4项延迟间歇性过千。要能回退到上一版本就好了。

![image](https://user-images.githubusercontent.com/31338729/175765996-655c0696-8d26-4ffa-9e45-db64f3679d1b.png)
windows端最新版内核无异常， openclash的meta内核和原版的不一样好像

**Comment by liubos** [comment]
Meta的alpha内核已经更新到alpha-637f1b5，也可以自己下载稳定版v1.11.2内核替换
![image](https://user-images.githubusercontent.com/24912536/175777854-0227d759-a325-458f-a2e9-00d72db9f60c.png)

**Comment by dawei233** [comment]
> Meta的alpha内核已经更新到alpha-637f1b5，也可以自己下载稳定版v1.11.2内核替换 ![image](https://user-images.githubusercontent.com/24912536/175777854-0227d759-a325-458f-a2e9-00d72db9f60c.png)

手动替换v1.11.2-compatible 可以正常使用， 额但是我没检测到alpha-637f1b5这个版本的更新啊是分支不对吗

**Comment by lingyunzhiss** [comment]
> > Meta的alpha内核已经更新到alpha-637f1b5，也可以自己下载稳定版v1.11.2内核替换 ![image](https://user-images.githubusercontent.com/24912536/175777854-0227d759-a325-458f-a2e9-00d72db9f60c.png)
> 
> 手动替换v1.11.2-compatible 可以正常使用， 额但是我没检测到alpha-637f1b5这个版本的更新啊是分支不对吗

谢谢，如你所述，更换meta核心到v1.11.2 CPU占用从30多下降到8%。Iintel J1900.

**Comment by vernlau** [comment]
> > > Meta的alpha内核已经更新到alpha-637f1b5，也可以自己下载稳定版v1.11.2内核替换 ![image](https://user-images.githubusercontent.com/24912536/175777854-0227d759-a325-458f-a2e9-00d72db9f60c.png)
> > 
> > 
> > 手动替换v1.11.2-compatible 可以正常使用， 额但是我没检测到alpha-637f1b5这个版本的更新啊是分支不对吗
> 
> 谢谢，如你所述，更换meta核心到v1.11.2 CPU占用从30多下降到8%。Iintel J1900.

Alpha是预览版，几乎每天都会更新的，不想折腾，就换release核心，自己upx压缩一下

**Comment by abigchopstick** [comment]
我的设备是N1，固件是flippy，OPENCLASH的传统内核开不了FAKEIP+TUN模式，一直报错。

现在开了meta内核的fakeid+TUN，正常工作的时候真的太爽了，反应速度快了很多。

但是经过一个晚上就不行了，今天在clash.meta的github看到有人说docker可能是问题，卸载掉docker试一下，目前正常，出问题再回来报告 。

同时再问一个问题，N1是ARMv8的，我如果想手工替换meta的内核应该下载哪个版本？Armv7还是Arm64？

**Comment by abigchopstick** [comment]
很不幸的是生存不了几小时，看来我的问题跟docker没啥关系。

**Comment by binhe-cpu** [comment]
请问下，怎么更新meta内核，我下载Clash.Meta-linux-amd64-v1.13.1解压改名上传后，应用后又自动下载alpha版了

**Comment by dawei233** [comment]
要改名字 把名字改成自带的那个，现在最新版已经修复这个bug了不用自己整了其实




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月9日(星期五) 上午9:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [vernesong/OpenClash] [Bug] 最新版meta内核无法正常启动vless代理的配置文件 (Issue #2509)





 
请问下，怎么更新meta内核，我下载Clash.Meta-linux-amd64-v1.13.1解压改名上传后，应用后又自动下载alpha版了

**Comment by maike2019** [comment]
> 要改名字 把名字改成自带的那个，现在最新版已经修复这个bug了不用自己整了其实
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年9月9日(星期五) 上午9:02 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [vernesong/OpenClash] [Bug] 最新版meta内核无法正常启动vless代理的配置文件 (Issue #2509) 请问下，怎么更新meta内核，我下载Clash.Meta-linux-amd64-v1.13.1解压改名上传后，应用后又自动下载alpha版了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

请问如何下载新版本Alpha内核呢？我的是N1 openwrt 的openclash ，我点击版本更新，一直失败。但我又不知道怎么下载替换

**Comment by maike2019** [comment]
> 要改名字 把名字改成自带的那个，现在最新版已经修复这个bug了不用自己整了其实
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年9月9日(星期五) 上午9:02 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [vernesong/OpenClash] [Bug] 最新版meta内核无法正常启动vless代理的配置文件 (Issue #2509) 请问下，怎么更新meta内核，我下载Clash.Meta-linux-amd64-v1.13.1解压改名上传后，应用后又自动下载alpha版了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

我下载 clash.meta-linux-arm64-v1.14.5.gz 后解压缩，然后复制到 /etc/openclash/core/clash_meta 中，将原来的clash_meta 文件删除。把新复制进来的文件名改为 clash_meta 。然后重启N1，加载 meta 失败，没法正常工作，检测不到meta内核

**Comment by maike2019** [comment]
> 要改名字 把名字改成自带的那个，现在最新版已经修复这个bug了不用自己整了其实
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年9月9日(星期五) 上午9:02 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [vernesong/OpenClash] [Bug] 最新版meta内核无法正常启动vless代理的配置文件 (Issue #2509) 请问下，怎么更新meta内核，我下载Clash.Meta-linux-amd64-v1.13.1解压改名上传后，应用后又自动下载alpha版了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

我按照您的方法更新了，核心名称现实为 v1.14.5 with_gvisor  ，为何后面会现实 with_gvisor  ，什么意思？我看你的图片中没有

**Comment by yongyuandeconan** [comment]
> > 要改名字 把名字改成自带的那个，现在最新版已经修复这个bug了不用自己整了其实
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: _**@**_._**>; 发送时间: 2022年9月9日(星期五) 上午9:02 收件人: _**@**_.**_>; 抄送: _**@**_._**>; _**@**_.**_>; 主题: Re: [vernesong/OpenClash] [Bug] 最新版meta内核无法正常启动vless代理的配置文件 (Issue #2509) 请问下，怎么更新meta内核，我下载Clash.Meta-linux-amd64-v1.13.1解压改名上传后，应用后又自动下载alpha版了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: _**@**_.***>
> 
> 我下载 clash.meta-linux-arm64-v1.14.5.gz 后解压缩，然后复制到 /etc/openclash/core/clash_meta 中，将原来的clash_meta 文件删除。把新复制进来的文件名改为 clash_meta 。然后重启N1，加载 meta 失败，没法正常工作，检测不到meta内核

执行chmod 777 /etc/openclash/core/clash_meta 的命令
