### ISSUE TITLE
希望作者优化一下openclash控制面板的节点选用逻辑

### ISSUE THREAD

**Issue by jiangzhi1m** [vernesong/OpenClash#251]
原本无所谓，因为机场修改规则，不同节点有不同倍率，目前更新配置，原本指定的节点会变成自动选择节点；重启也有几率会变成自动选择；望作者修改

**Comment by YukawaMi** [comment]
我个人感觉 这种客制化的需求还是结合subconverter 自己做二次规则修改的好，自己去定义的话比较灵活   ,你可以用正则匹配关键字去定义符合自己的分组分流规则。鉴于基本重启就会恢复默认的情况，我都是把自己需要的规则放到第一个。。。。
https://bianyuan.xyz/ini
https://github.com/tindy2013/subconverter

**Comment by vernesong** [comment]
重启本身已经支持还原节点选择状态，除非节点变了，如果你不放心，还是建议按照楼上的方法。

**Comment by jiangzhi1m** [comment]
> 我个人感觉 这种客制化的需求还是结合subconverter 自己做二次规则修改的好，自己去定义的话比较灵活   ,你可以用正则匹配关键字去定义符合自己的分组分流规则。鉴于基本重启就会恢复默认的情况，我都是把自己需要的规则放到第一个。。。。
> 
> https://bianyuan.xyz/ini
> 
> https://github.com/tindy2013/subconverter
> 
> 
> 
> 

谢谢回复！可以加个tg吗？能请你大概教我操作下吗？我只需要把常用的节点放在首位就行；tg：https//t.me/Jz0223

**Comment by jiangzhi1m** [comment]
> 重启本身已经支持还原节点选择状态，除非节点变了，如果你不放心，还是建议按照楼上的方法。

谢谢作者回复，辛苦了

**Comment by jiangzhi1m** [comment]
> 我个人感觉 这种客制化的需求还是结合subconverter 自己做二次规则修改的好，自己去定义的话比较灵活   ,你可以用正则匹配关键字去定义符合自己的分组分流规则。鉴于基本重启就会恢复默认的情况，我都是把自己需要的规则放到第一个。。。。
> 
> https://bianyuan.xyz/ini
> 
> https://github.com/tindy2013/subconverter
> 
> 
> 
> 

https://t.me/Jz0223
