### ISSUE TITLE
[Feature] Fake-IP模式下依然提供根据IP/MAC排除客户端的选项

### ISSUE THREAD

**Issue by InspoOnU** [vernesong/OpenClash#2510]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

现在，Fake-IP模式下，访问控制里不提供通过IP/MAC来排除客户端的功能。这种情况下，如果要控制局域网内某个客户端直连，只能用SrcIP-CIDR规则，但这样会带来一些问题：
1. IPv6地址是随机的，而且每次拨号后都会更新，所以没法写进规则里。
2. 有些客户端直接使用IPv6地址连接（比如连接[2001:4860:4860::8888]:853来判断地区），导致功能异常。
3. 下游可以给客户端制定不同的DNS，没有必要在Fake-IP模式下禁用这个功能。

### Describe the Solution

Fake-IP下，和Redir-Host模式一样，提供IP/MAC排除客户端的选项。保险起见，可以把198.18.0.1/16排除掉，流量依旧经过核心。

**Comment by InspoOnU** [comment]
> ### Verify Steps
> * [x]  Tracker 我已经在 [Issue Tracker](%E2%80%A6%E2%80%A6/) 中找过我要提出的问题
> * [x]  Need 当前 OpenClash 并不包含该功能特性或者还不完善
> * [x]  Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
> * [x]  Meaningful 我提交的不是无意义的 催促更新或修复 请求
> 
> ### Describe the Feature
> 现在，Fake-IP模式下，访问控制里不提供通过IP/MAC来排除客户端的功能。这种情况下，如果要控制局域网内某个客户端直连，只能用SrcIP-CIDR规则，但这样会带来一些问题：
> 
> 1. IPv6地址是随机的，而且每次拨号后都会更新，所以没法写进规则里。
> 2. 有些客户端直接使用IPv6地址连接（比如连接2001:4860:4860::8888:853来判断地区），导致功能异常。
> 3. 下游可以给客户端制定不同的DNS，所以禁用这个功能没有必要
> 
> ### Describe the Solution
> Fake-IP下，和Redir-Host模式一样，提供IP/MAC排除客户端的选项。保险公司起见，如果连接的IP是198.18.0.1/16，流量依旧经过核心。
> 
> ### Describe Alternatives
> _No response_
> 
> ### Additional Context
> _No response_

**Comment by laye0619** [comment]
希望有提供排除mac地址客户端的选项

**Comment by jayling1111** [comment]
同样有此需求，希望可以提供。
pt下载流量经过内核会导致CPU占用极高

**Comment by XinSSS** [comment]
我也想要这个。。
