### ISSUE TITLE
[Feature] 请问openclash 怎么设置指定网址不走代理呢

### ISSUE THREAD

**Issue by coolhugh** [vernesong/OpenClash#2518]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

pt论坛会走代理，如何设置才能让pt论坛不走代理呢？

### Describe the Solution

没找到解决方案

**Comment by jayling1111** [comment]
自定义规则 看模板或者上youtube看看教程
