### ISSUE TITLE
[Bug] 自定义fake-IP黑名单按钮消失

### ISSUE THREAD

**Issue by ForestL18** [vernesong/OpenClash#2529]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.33-beta

### Bug on Environment

Lean

### Bug on Platform

Linux-armv8

### To Reproduce

![image](https://user-images.githubusercontent.com/45709305/177025634-b5e053c9-cc37-46e8-a56b-9841cd88308e.png)

### Describe the Bug

无

### OpenClash Log

无

### Expected Behavior

这是之前版本的截图，黑名单按钮是存在的

![image](https://user-images.githubusercontent.com/45709305/177025651-511c3399-a0dc-40b0-b3fa-f1b612a22386.png)

**Comment by ForestL18** [comment]
@vernesong

**Comment by ForestL18** [comment]
经测试，该按钮从[v0.45.22-beta] 版本开始消失

**Comment by ForestL18** [comment]
> 不需要了，改完保存应用

改完保存应用后，在 `配置文件管理-OpenClash修改后用于启动的配置文件` 查看，发现整个fake-ip filter都消失了，其他配置都还存在

**Comment by ForestL18** [comment]
我现在已经退回v0.45.16-beta版本使用

**Comment by XXTMTA** [comment]
原来是这个功能消失了..另外访问控制的 不走代理的 WAN IP功能也是无效的

**Comment by cubarco** [comment]
这个问题我也遇到了，版本：v0.45.35-beta
可以看到在/etc/openclash/custom/openclash_custom_fake_filter.list下确实保存了我在GUI界面上保存的fake-ip-filter黑名单，但是最终生成的yaml配置只有以下两项：- "+.nflxvideo.net"
  - "+.media.dssott.com"

**Comment by ForestL18** [comment]
https://github.com/vernesong/OpenClash/issues/2529#issuecomment-1186840931
@vernesong 希望作者把原来的按钮给加回来
