### ISSUE TITLE
[Bug] 在FriendlyWrt 系统下全局模式的自定义上游DNS服务器的界面不是很友好

### ISSUE THREAD

**Issue by marswow** [vernesong/OpenClash#2530]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.33beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-armv8

### To Reproduce

点开openclash>>全局设置>>滑动到“设置自定义上游 DNS 服务器（在上方设置中启用本功能后生效）”UI界面被挤压看的挺难受的。希望改进界面布局以适应宽屏模式

### Describe the Bug

-----------------系统信息--------------------
主机名 | FriendlyWrt
-- | --
型号 | FriendlyElec NanoPi R5S
架构 | ARMv8 Processor rev 0
目标平台 | rockchip/armv8
固件版本 | OpenWrt 21.02.3 r16554-1d4dea6d4f / LuCI openwrt-21.02 branch git-22.083.69138-0a0ce2a
内核版本 | 5.10.66
---------------------------------------------
点开openclash>>全局设置>>滑动到“设置自定义上游 DNS 服务器（在上方设置中启用本功能后生效）”UI界面被挤压看的挺难受的。希望改进界面布局

### OpenClash Log

-

### Expected Behavior

希望改进页面布局支持宽屏模式 避免某些页面布局困难

### Screenshots

![image](https://user-images.githubusercontent.com/13765982/177026414-005aac14-fb18-46ac-9d6a-a6e3db7046a0.png)

**Comment by LarkinZero** [comment]
试试装个Material主题，对宽屏有优化
