### ISSUE TITLE
[Bug] 代理集文件下载失败 Parse config error... x509: certificate signed by unknown authority"

### ISSUE THREAD

**Issue by pv0402** [vernesong/OpenClash#2531]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.33-beta

### Bug on Environment

Lean

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

启动openclash时

### Describe the Bug

手动上传的配置，启动openclash时下载代理集文件报错：Parse config error: initial proxy provider bityuntj_rate1 error: Get \"https://sub.id9.cc/sub?target=clash&url=此处省略\": x509: certificate signed by unknown authority
windows版无此问题，请问如何解决？

### OpenClash Log

2022-07-04 17:08:31 level=fatal msg="Parse config error: initial proxy provider bityuntj_rate1 error: Get \"https://sub.id9.cc/sub?target=clash&url=此处省略\": x509: certificate signed by unknown authority"
2022-07-04 17:08:31 level=info msg="Start initial provider bityuntj_rate1"

### Expected Behavior

可以正常下载代理集

**Comment by vernesong** [comment]
暂时不明，换个地址呢

**Comment by zhangjiabo0** [comment]
把服务端网站的证书相关文件：.cer .csr .key .crt 上传到客户端的/etc/ssl/certs文件夹下，重启openclash。我猜是服务端的证书颁发机构不被客户端信任导致的
