### ISSUE TITLE
[Bug] 使用过程中，后台提示内核崩溃

### ISSUE THREAD

**Issue by zelbloo** [vernesong/OpenClash#2539]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.35

### Bug on Environment

Other

### Bug on Platform

Linux-armv8

### To Reproduce

无，正常使用

### Describe the Bug

使用过程中，在后台查看到内核崩溃

### OpenClash Log

2022-07-09 13:50:29 守护程序：检测到 Clash 内核崩溃，重启中...
	github.com/Dreamacro/clash/listener/stack/system/system.go:59 +0x1dc
created by github.com/Dreamacro/clash/listener/stack/system.(*System).Start
	github.com/Dreamacro/clash/listener/stack/system/system.go:79 +0x11c
github.com/Dreamacro/clash/listener/stack/system.(*System).Start.func1()
	github.com/Dreamacro/clash/listener/stack/system/system.go:207 +0x600
github.com/Dreamacro/clash/listener/stack/system.(*System).handleTCPv4(0x400019e000?, {0x40001b6000?, 0x34?, 0x8000?})
	github.com/Dreamacro/clash/listener/stack/system/tcpip/ip.go:32
github.com/Dreamacro/clash/listener/stack/system/tcpip.IPv4Packet.Payload(...)
goroutine 233 [running]:
panic: runtime error: slice bounds out of range [:33305] with capacity 32768

### Expected Behavior

无

### Screenshots

![image](https://user-images.githubusercontent.com/7335235/178093666-7894b36e-c65b-4095-8770-d840cd574b50.png)

**Comment by Bingbing020205** [comment]
![image](https://user-images.githubusercontent.com/37571850/183547032-0d1c4562-fe96-4188-b7d1-2f04ccab9288.png)
![image](https://user-images.githubusercontent.com/37571850/183547090-f5452e78-94e6-459f-9509-ef86b9c0ce5e.png)
![image](https://user-images.githubusercontent.com/37571850/183547115-37cb39b4-7dcf-4685-876c-b4a17801a511.png)
我也是，反复有崩溃的情况，最新的beta47版本，系统是4.19.237
