### ISSUE TITLE
如何在开启Fake-ip时，域名仍旧可以通过114.114.114.114获取真实IP

### ISSUE THREAD

**Issue by LarkinZero** [vernesong/OpenClash#254]
目前我发现在路由器开启Clash的Fake-ip时，无论是直接用nslookup获取域名的ip，还是加上114dns，查询到ip都是198.18.X.X的ip地址。
如何设置才能使请求路由器DNS时返回Fake-ip，请求114dns时返回真实ip呢？

**Comment by vernesong** [comment]
dns高级设置

**Comment by LarkinZero** [comment]
我的意思是，在不配置DNS黑名单的情况下，使用路由器dns查询到198段的ip，用114dns查询到真实ip。
这样设备手动配置一个114dns，对所有域名都能查询到真实ip了
要用clash的fakeip，就配置默认的路由器dns

**Comment by vernesong** [comment]
有何意义

**Comment by LarkinZero** [comment]
内网一个设备如果也使用了fake ip为本机实现代理，就可以避免冲突了

**Comment by vernesong** [comment]
禁用dns劫持，启动后使用一下命令：
```
iptables -t nat -I PREROUTING -p udp -d 192.168.1.1 --dport 53 -j REDIRECT --to-ports 7874
```

**Comment by LarkinZero** [comment]
成功了，将`本地DNS劫持`改成停用后，然后执行iptables命令确实可以实现只劫持路由器DNS服务，不劫持公网DNS服务的需求。
如果能将此功能加入DNS设置作为一个选项就好了，这样就能更精细的控制内网的DNS劫持情况。

**Comment by LarkinZero** [comment]
现在发现本地DNS劫持关闭后，Fake-IP域名黑名单就失效了，有什么办法能让其生效吗

**Comment by LarkinZero** [comment]
现在发现可能Fake-ip模式并不适合我目前的需求，还是改成redir模式更适合我

**Comment by xufzh** [comment]
> 现在发现可能Fake-ip模式并不适合我目前的需求，还是改成redir模式更适合我

我是把不需要fake-ip的终端直接dns请求redirect到另一个dns服务进程的端口来弄的

**Comment by jackge0323** [comment]
> > 现在发现可能Fake-ip模式并不适合我目前的需求，还是改成redir模式更适合我
> 
> 我是把不需要fake-ip的终端直接dns请求redirect到另一个dns服务进程的端口来弄的

请教一下，这个怎么操作？

**Comment by xufzh** [comment]
> > > 现在发现可能Fake-ip模式并不适合我目前的需求，还是改成redir模式更适合我
> > 
> > 
> > 我是把不需要fake-ip的终端直接dns请求redirect到另一个dns服务进程的端口来弄的
> 
> 请教一下，这个怎么操作？

iptables prerouting里把需要请求真实ip的源地址的dns请求redirect 到另一个dns服务进程的端口，这里我用的是smartdns
