### ISSUE TITLE
[Bug] 指定（第二）DNS 服务器 无效

### ISSUE THREAD

**Issue by zgc** [vernesong/OpenClash#2547]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.35-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-armv8

### To Reproduce

openclash指定第二dns服务器到SmartDNS 127.0.0.1#6053，域名列表 xxx.com，
SmartDNS配置了address xxx.com/127.0.0.1，
dnspod配置了xxx.com -> 1.1.1.1，
nslookup -port=6053 xxx.com 192.168.2.1 返回 127.0.0.1，
nslookup -port=7874 xxx.com 192.168.2.1 返回 1.1.1.1

### Describe the Bug

nslookup -port=7874 xxx.com 192.168.2.1 返回 1.1.1.1 应该返回 127.0.0.1 才对吧？

### OpenClash Log

无

### Expected Behavior

nslookup -port=7874 xxx.com 192.168.2.1 应该返回SmartDNS里配置的 127.0.0.1

**Comment by zgc** [comment]
我想把xxx.com所有子域名都指向第二dns服务器，是应该配置 +.xxx.com 吗？

**Comment by vernesong** [comment]
第二服务器是通过dnsmasq实现的，直接查询7874就绕过dnsmasq了

**Comment by zgc** [comment]
> 第二服务器是通过dnsmasq实现的，直接查询7874就绕过dnsmasq了

明白，那配置 +.xxx.com 是代表 xxx.com 所有子域名都指向第二dns服务器吗？

**Comment by zgc** [comment]
<img width="359" alt="WX20220718-002700@2x" src="https://user-images.githubusercontent.com/4143433/179411490-b731c938-fa9a-4914-9fc2-1c56b4ff51c9.png">
![1658075275378](https://user-images.githubusercontent.com/4143433/179411493-e26755f7-21f5-4eb4-a3a9-0aa6f4aa89c7.jpg)
<img width="347" alt="WX20220718-002826@2x" src="https://user-images.githubusercontent.com/4143433/179411498-4566b2ed-e3c0-4722-b7ab-7b31b6413adb.png">
换了Meta 内核之后，用着用着突然间就出不了墙，我自己弄个[shell脚本](https://raw.githubusercontent.com/zgc/openwrt-nanopi-r2s/openwrt-lean/scripts/check_openclash_connect.sh)，五分钟检查一下，检查了日志，没发觉有什么问题
