### ISSUE TITLE
[Bug] OpenClash不支持shadowsocks-ws节点吗？

### ISSUE THREAD

**Issue by kitkw** [vernesong/OpenClash#2548]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.35-beta

### Bug on Environment

Lean

### Bug on Platform

Linux-armv8

### To Reproduce

能正常添加shadowsocks-ws节点但不通！！v2rayN下正常。

### Describe the Bug

-----

### OpenClash Log

-----

### Expected Behavior

-----

**Comment by hcym** [comment]
v2的ws没事，一直都在用，ss的没试

**Comment by vernesong** [comment]
dev的内核试试

**Comment by kitkw** [comment]
> 

不行
