### ISSUE TITLE
[Bug] 开启绕过大陆ip后LinkedIn无法打开， 无网络， 关闭绕过大陆ip才可以

### ISSUE THREAD

**Issue by kakomin** [vernesong/OpenClash#2549]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

0.45.16

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-armv7

### To Reproduce

开启绕过大陆ip后LinkedIn无法打开， 无网络， 关闭绕过大陆ip才可以

### Describe the Bug

开启绕过大陆ip后LinkedIn无法打开， 无网络， 关闭绕过大陆ip才可以

### OpenClash Log

开启绕过大陆ip后LinkedIn无法打开， 无网络， 关闭绕过大陆ip才可以

### Expected Behavior

开启绕过大陆ip后LinkedIn无法打开， 无网络， 关闭绕过大陆ip才可以

**Comment by kakomin** [comment]
如果关闭绕过大陆ip， 网速会从800M降到300左右

**Comment by kingsey** [comment]
你本地网络设置有问题吧，dns之类的。绕过大陆IP 网络都不经过openclash处理的。关闭绕过大陆之后降网速应该是设备性能太弱。

**Comment by kakomin** [comment]
> 找到问题了， 开启绕过大陆ip，open clash DNS自定义域名加入一下就可以正常访问linkedin了
'linkedin.com': '8.8.8.8'
'licdn.com': '8.8.8.8'
'bizographics.com': '8.8.8.8'
'linkedin.cn': '8.8.8.8'
'lnkd.in': '8.8.8.8'
'l-0005.dc-msedge.net': '8.8.8.8'
'l-0005.l-msedge.net': '8.8.8.8'

**Comment by vernesong** [comment]
写规则让他代理

**Comment by kakomin** [comment]
写规则也代理不上，之后是redir-host 切换到混合模式解决的
