### ISSUE TITLE
启用fake-ip模式下geoip及机场订阅更新始终失败

### ISSUE THREAD

**Issue by zzxjohn** [vernesong/OpenClash#255]
在官方系统OpenWrt 19.07.2 r10947-65030d81f3下，启用fake-ip模式下geoip及机场订阅更新始终失败，但是换回redir-host下就能正常更新(openclash版本：v0.36.11-beta)

**Comment by vernesong** [comment]
看下日志情况

**Comment by zzxjohn** [comment]
日志只显示Geoip更新失败，机场订阅失败在日志里看不到
<img width="624" alt="Screenshot 2020-03-20 at 7 33 09 PM" src="https://user-images.githubusercontent.com/9846060/77160555-8aad7c80-6ae2-11ea-96dd-1e0a69d68be5.png">
![image](https://user-images.githubusercontent.com/9846060/77160576-9731d500-6ae2-11ea-82de-2b471e8c0f15.png)
![image](https://user-images.githubusercontent.com/9846060/77160593-a022a680-6ae2-11ea-84d5-14d25f3097fa.png)

**Comment by zzxjohn** [comment]
刚准备在luci更新到v0.36.12-beta时发现除了geoip和机场订阅以外，clash内核跟openclash客户端都同样更新失败
<img width="966" alt="image" src="https://user-images.githubusercontent.com/9846060/77160948-728a2d00-6ae3-11ea-9000-ba308824c8da.png">

**Comment by zzxjohn** [comment]
<img width="964" alt="image" src="https://user-images.githubusercontent.com/9846060/77161276-373c2e00-6ae4-11ea-84cf-f2801de5d2f1.png">
刚准备在luci更新到v0.36.12-beta时发现除了geoip和机场订阅以外，clash内核跟openclash客户端都同样更新失败

**Comment by vernesong** [comment]
先检查下路由自身能不能连接外网，然后看curl有没有装

**Comment by zzxjohn** [comment]
<img width="981" alt="Screenshot 2020-03-20 at 10 40 35 PM" src="https://user-images.githubusercontent.com/9846060/77174407-f8b26d80-6afb-11ea-8612-26ace8bfba0a.png">
<img width="697" alt="Screenshot 2020-03-20 at 10 41 09 PM" src="https://user-images.githubusercontent.com/9846060/77174422-fd772180-6afb-11ea-9ab1-f60e9c864450.png">
路由器已安装curl，ssh进去路由器crul www.google.com有返回数据

**Comment by kmoc** [comment]
把猫重启下试试，让宽带运营商重新分配Ip后，再执行更新

**Comment by kmoc** [comment]
如果还是不行，把openclash关闭后，再执行geoip更新，测试通过

**Comment by zzxjohn** [comment]
把openclash关闭后，再执行geoip的确可以更新，但是如果这样操作的话就无法自动更新geoip跟订阅了。

**Comment by vernesong** [comment]
规则是怎么判定的？控制面板的日志里

**Comment by zzxjohn** [comment]
<img width="610" alt="Screenshot 2020-03-21 at 5 59 40 PM" src="https://user-images.githubusercontent.com/9846060/77224166-de30d080-6b9d-11ea-9266-7f9a44fa96a0.png">
<img width="982" alt="Screenshot 2020-03-21 at 6 01 21 PM" src="https://user-images.githubusercontent.com/9846060/77224216-513a4700-6b9e-11ea-80e4-1ce6f5dd131c.png">
![Screenshot 2020-03-21 at 6 07 01 PM](https://user-images.githubusercontent.com/9846060/77224256-cb6acb80-6b9e-11ea-94f4-f2e9b381d062.png)
我已经将geoip的更新域名手动添加到自定义规则中，路由器为单臂路由器，LAN口的DNS已经设成127.0.0.1了，opkg update时在控制面板中能看到正常走代理，但是更新geoip，订阅，客户端跟内核就看不到走openclash，日志也是空的

**Comment by vernesong** [comment]
启动后除了geoip,更新这些都是通过clash的http代理，是不是开了仅允许内网？新版修复了这个问题。

**Comment by zzxjohn** [comment]
<img width="972" alt="image" src="https://user-images.githubusercontent.com/9846060/77224652-abd5a200-6ba2-11ea-82f2-96f74fb6753a.png">
仅允许内网是关闭的

**Comment by vernesong** [comment]
你在浏览器上设置一个clash的http代理，一般是192.168.1.1:7890，看下访问情况吧，只能说根据你的描述fake-ip的情况下http代理不正常

**Comment by zzxjohn** [comment]
的确，http代理不正常，浏览器上无法用；扫路由器的端口连7890都扫不出来
![IMG_14739A8F67A0-1](https://user-images.githubusercontent.com/9846060/77226129-e34b4b00-6bb0-11ea-8359-d105ec394595.jpeg)

**Comment by zzxjohn** [comment]
貌似7890/7891/7892几个端口都listen在ipv6上
<img width="802" alt="image" src="https://user-images.githubusercontent.com/9846060/77226263-f9a5d680-6bb1-11ea-8496-d71a7683c260.png">

**Comment by zzxjohn** [comment]
我在/etc/sysctl.conf加了net.ipv6.conf.all.disable_ipv6 = 1重启后7890/7891/7892几个端口都还是listen在ipv6上

**Comment by vernesong** [comment]
不是，这代表监听所有地址，你挂http代理看访问情况

**Comment by zzxjohn** [comment]
浏览器挂代理测试也是无法使用

**Comment by flymess** [comment]
我个人也遇到了订阅、内核等无法更新，总提示更新失败。由于我对Linux和bash不大明白，但是我个人觉得可能出现的问题在使用curl进行下载上面，因为我同时安装了luci-app-clash。而luci的那个版本是可以进行更新订阅等，我查看了下二位写的下载，luci使用的是wget，而openclash使用curl，不知道是不是跟这个也有关系。我还没进行试验，准备今晚进一步排查问题

**Comment by flymess** [comment]
实测是由于没有ca-bundle导致curl无法下载https，安装依赖后解决，由于错误信息没能打印到日志，所以之前一直没能搞明白原因

**Comment by vernesong** [comment]
> 浏览器挂代理测试也是无法使用

curl -v 路由上测试下，反馈结果

**Comment by zzxjohn** [comment]
换了lean‘s openwrt后就能正常更新了

**Comment by vernesong** [comment]
跟楼上一样缺少ca-bundle？
