### ISSUE TITLE
[Feature] 关于防火墙的疑问

### ISSUE THREAD

**Issue by paladin4fan** [vernesong/OpenClash#2551]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

使用Openwrt官方22.03.0安装openclash 会由于防火墙换成了nftables而无法成功代理
装上kmod-ipt-nat之后openclash可以正常工作了
想问一下 在iptables里执行return操作的流量 NAT是由nftables实现的 还是旧的iptables实现的

### Describe the Solution

无

**Comment by vernesong** [comment]
没有更新，暂时没去了解机制

**Comment by paladin4fan** [comment]
> 没有更新，暂时没去了解机制

不知道是个例还是普遍的 目前这个防火墙混用的条件下 TUN内核又会有问题
启用tun混合模式 Discord语音频道连接不上 提示没有路径
fakeip增强模式开UDP转发就没什么问题
顺便问一下 不开启TUN混合模式 单用fakeip增强+勾选meta内核 可不可以使用规则集与策略组管理功能

**Comment by vernesong** [comment]
日志不是会提示吗，跟模式没关系

**Comment by paladin4fan** [comment]
> 日志不是会提示吗，跟模式没关系

看到了 后台匹配上了ruleset
现在就是不知道为什么tun模式会出问题 如果不开绕过大陆IP+手动分流国内域名到直连DNS 甚至国内的语音平台也连不上

**Comment by qin9125** [comment]
你现在用的 22.03 rc？rc6 openclash 已经失效了不能代理，更新 ip 数据库会一直出现内核崩溃

**Comment by paladin4fan** [comment]
> 你现在用的 22.03 rc几？rc6 openclash 已经失效了不能代理，更新 ip 数据库会一直出现内核崩溃

rc5 用官方源代码编译 编译过程就加入了openclash和nftables的fullcone补丁
