### ISSUE TITLE
请问怎么能做到访问国内和国外用不同的dns

### ISSUE THREAD

**Issue by lloyd18** [vernesong/OpenClash#256]
比如国内用114.114.114.114，国外用8.8.4.4

**Comment by hardy-one** [comment]
现在就是不一样的，clash发给服务器的都是域名，由服务器再解析。
本地这边dns查询如果是国内就使用nameserver的结果，国外用fallback的结果。

**Comment by lloyd18** [comment]
> 现在就是不一样的，clash发给服务器的都是域名，由服务器再解析。
> 本地这边dns查询nameserver的结果国内就直接使用，如果是国外就用fallback的结果。

现在是这样吗，不是很懂，fallback不是备用的意思？

**Comment by hardy-one** [comment]
> > 现在就是不一样的，clash发给服务器的都是域名，由服务器再解析。
> > 本地这边dns查询nameserver的结果国内就直接使用，如果是国外就用fallback的结果。
> 
> 现在是这样吗，不是很懂，fallback不是备用的意思？

https://github.com/Fndroid/clash_for_windows_pkg/wiki/DNS%E6%B1%A1%E6%9F%93%E5%AF%B9Clash%EF%BC%88for-Windows%EF%BC%89%E7%9A%84%E5%BD%B1%E5%93%8D#%E5%B7%A5%E4%BD%9C%E5%8E%9F%E7%90%86

**Comment by lloyd18** [comment]
> > > 现在就是不一样的，clash发给服务器的都是域名，由服务器再解析。
> > > 本地这边dns查询nameserver的结果国内就直接使用，如果是国外就用fallback的结果。
> > 
> > 
> > 现在是这样吗，不是很懂，fallback不是备用的意思？
> 
> https://github.com/Fndroid/clash_for_windows_pkg/wiki/DNS%E6%B1%A1%E6%9F%93%E5%AF%B9Clash%EF%BC%88for-Windows%EF%BC%89%E7%9A%84%E5%BD%B1%E5%93%8D#%E5%B7%A5%E4%BD%9C%E5%8E%9F%E7%90%86

谢谢
