### ISSUE TITLE
[Bug] 开启openclash  redir-host兼容模式（不代理UDP）的同时开启雷神加速器，雷神加速器会频繁报告本地网络异常

### ISSUE THREAD

**Issue by LuziJay** [vernesong/OpenClash#2562]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.16-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

问题1.开启openclash  redir-host兼容模式（不代理UDP）的同时开启雷神加速器，雷神加速器会频繁报告本地网络异常
问题2.开启openclash  redir-host兼容模式（代理UDP）/redir-host混合模式的同时开启UU加速器，UU加速器的测速节点基本无法链接，关掉openclash，或者开启绕过大陆ip后正常。

### Describe the Bug

我不确定这算不算BUG，按正常逻辑UU加速器的测速请求应该是国内IP，但是我查看日志后，发现UU加速器都是发送的国外IP+9999端口的UDP

### OpenClash Log

发送的国外IP+9999端口的UDP

### Expected Behavior

如果可以的话能不能添加一个功能，单独针对UDP绕过大陆IP，因为有时候需要代理港澳台的bilibili（TCP）但是同时不想影响到国内游戏的正常链接

经过多次测试，已基本判定是Meta内核的问题，关闭Meta内核绝大多数的问题都没有再复现
不过说实话，还是没搞定Meta内核是干嘛的，绝大多数人都说建议开，但是实际使用感觉没什么区别

**Comment by LuziJay** [comment]
> fake-ip 混合 主机 混合没开redirdir ![图片](https://user-images.githubusercontent.com/42875168/180364738-106f67bc-4ee1-45b7-841e-8e85f40be026.png) ![图片](https://user-images.githubusercontent.com/42875168/180364930-2c1d4478-94cf-4a0f-bee6-1e80d80897d7.png)

你加速一下国服的游戏试试，现在主要问题是现在连加速国内的游戏，比如国服LOL，都检测到的是国外的节点，这就特别尴尬，我想加速到网二的北方服务器，然后UU加速器把我弄到俄罗斯的节点去了，然后检测国内的节点全是不通的。。。。。。

**Comment by vernesong** [comment]
https://github.com/vernesong/OpenClash/issues/1751

**Comment by vernesong** [comment]
你开仅常用端口应该就行了

**Comment by LuziJay** [comment]
> 你开仅常用端口应该就行了

NAS需要用其他端口的

**Comment by LuziJay** [comment]
雷神加速器检测到本地网络不稳定的问题已经基本判定是meta核心的问题，meta核心关闭就很稳定

**Comment by LuziJay** [comment]
> 雷神加速器检测到本地网络不稳定的问题 已经基本验证是元内核的问题，元内核就稳定了
> 
> 所以我还是没搞懂元的用处

经过多次测试，已基本确定是meta的问题，希望openclash开发者能够将meta源更换为稳定版。

**Comment by vernesong** [comment]
meta怎么配置的？可以去内核那边提

**Comment by LuziJay** [comment]
> meta怎么配置的？可以去内核那边提

仅开启了“使用Meta内核”

**Comment by LuziJay** [comment]
已解决，是因为docker+meta造成的udp转发异常，开启tun也无法正常转发，最后将docker卸载后解决。

**Comment by Se7enMuting** [comment]
最近用网易UU也出现这个问题，Meta在Redir-Host的tun和混合下都出现异常，切回P内核好像暂时没问题了，至少不是显示100%丢包
