### ISSUE TITLE
[Bug] OpenClash无法开启TUN模式

### ISSUE THREAD

**Issue by abigchopstick** [vernesong/OpenClash#2569]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.35beta

### Bug on Environment

Lean

### Bug on Platform

Linux-armv8

### To Reproduce

在以下版本的Openwrt中尝试打开OpenClash Fake-ip 的TUN模式

型号 | Phicomm N1
架构 | AArch64 Processor : Cortex-A53 * 4
固件版本 | OpenWrt R22.7.7 (2022-07-16 13:48:19 by flippy) / LuCI Master (git-22.196.12585-0f5cc90)
内核版本 | 5.15.55-flippy-74+o

### Describe the Bug

2022-07-25 16:15:56 错误: 无法获取 General 部分的转发端口设置, OpenClash 使用原始配置文件启动失败
总是到这里失败

### OpenClash Log

2022-07-25 16:15:59 OpenClash 开始关闭...
2022-07-25 16:15:56 错误: 无法获取 General 部分的转发端口设置, OpenClash 使用原始配置文件启动失败
2022-07-25 16:15:54 错误: OpenClash 启动失败，尝试使用原始配置文件启动...
2022-07-25 16:15:53 第六步: 等待主程序下载外部文件...
	github.com/Dreamacro/clash/main.go:100 +0x7cc
main.main()
	github.com/Dreamacro/clash/hub/hub.go:31 +0x48
github.com/Dreamacro/clash/hub.Parse({0x0, 0x0, 0x85024b?})
	github.com/Dreamacro/clash/hub/executor/executor.go:50
github.com/Dreamacro/clash/hub/executor.Parse(...)
	github.com/Dreamacro/clash/hub/executor/executor.go:60 +0x44
github.com/Dreamacro/clash/hub/executor.ParseWithPath({0x7fcfc57af5?, 0x4000143e40?})
	github.com/Dreamacro/clash/hub/executor/executor.go:65
github.com/Dreamacro/clash/hub/executor.ParseWithBytes(...)
	github.com/Dreamacro/clash/config/config.go:220 +0x3c
github.com/Dreamacro/clash/config.Parse({0x4000200000?, 0x1d?, 0x7f9cd84a68?})
	github.com/Dreamacro/clash/config/config.go:313 +0x21c
github.com/Dreamacro/clash/config.ParseRawConfig(0x400014f8c0)
	github.com/Dreamacro/clash/config/config.go:766 +0x32c
github.com/Dreamacro/clash/config.parseDNS(0x400014f8c0, 0x400011a2d8)
	github.com/Dreamacro/clash/component/trieset/domain.go:91 +0x514
github.com/Dreamacro/clash/component/trieset.New({0x4000422000, 0x5f, 0x400026d5f4?})
goroutine 1 [running]:
panic: runtime error: slice bounds out of range [:-1]

### OpenClash Config

```shell
N1运行在旁路模式，IPV6已经全关掉了（但OPENCLASH启动时还是会提示），不用TUN模式可以工作，但有些网站无法访问（大概跟UPD有关？）
```

### Expected Behavior

正常开启TUN模式

**Comment by abigchopstick** [comment]
v0.45.16beta也有同样的问题

**Comment by insomnia417** [comment]
同上

**Comment by abigchopstick** [comment]
没人有同样问题吗

**Comment by abigchopstick** [comment]
解决了，应该是配置文件的问题，可能用OpenClash内置的转换模式会好一些。
