### ISSUE TITLE
配置文件手动更新功能的加入

### ISSUE THREAD

**Issue by ikelvingo** [vernesong/OpenClash#257]
希望可以引入配置文件手动更新功能，强制刷新。

**Comment by vernesong** [comment]
什么意思

**Comment by ikelvingo** [comment]
就是在”配置文件管理“或者”配置文件订阅“页面，加入一个对于订阅文件手动进行更新的功能（按钮）。

**Comment by vernesong** [comment]
订阅页面应用配置就是强制更新

**Comment by ikelvingo** [comment]
这个我知道，只是比如我启用一个本地上传的配置，然后删除订阅配置。再在页面中应用配置强制更新。
按照页面反馈的信息，会显示订阅不成功启用备用配置，并且此时点击配置文件管理是看不到该订阅的配置文件，需要有一定的时间刷新后，才能看到。

**Comment by ikelvingo** [comment]
另外补充一个情况，如果新增配置，应用配置后，返回运行状态页面，新增的配置文件是不会在成功下载后被刷新出来，需要切换下页面才会被刷新线上。

**Comment by vernesong** [comment]
订阅第一次下载失败会重试直连下载的

**Comment by ikelvingo** [comment]
默认的超时时间是多久？难道是因为订阅地址超时？

**Comment by vernesong** [comment]
10秒，失败重试两次，两次失败直连

**Comment by ikelvingo** [comment]
明白了，应该是网络状况不好的时候，可能下载超时，导致下载文件不完整（部分规则不可用）

**Comment by anjue39** [comment]
> 订阅页面应用配置就是强制更新

不是吧，点了更新订阅，会提示配置文件没更新。到现在问题依然存在，更新订阅，如果订阅地址不变，会提示配置文件没更新。需要重新读取配置才可以，难道不可以点更新订阅后自动刷新列表吗？还可以加入一个选择。可以保留上次节点。可以自动去重

**Comment by vernesong** [comment]
> > 订阅页面应用配置就是强制更新
> 
> 不是吧，点了更新订阅，会提示配置文件没更新。到现在问题依然存在，更新订阅，如果订阅地址不变，会提示配置文件没更新。需要重新读取配置才可以，难道不可以点更新订阅后自动刷新列表吗？还可以加入一个选择。可以保留上次节点。可以自动去重

建议你使用代理集，代理集的地址可以直接填订阅地址，用meta内核可以再筛选节点

**Comment by anjue39** [comment]
大佬，我给你描述一下过程你就知道问题了。我的订阅地址是固定直链某个文件。每次部分变动了。点更新订阅，先会提示配置文件没更新，我不知道它怎么对比的。明明更新了。然后删除节点保存，再读取配置，才能读取到新订阅的内容。甚至我每次都先删除config配置文件，删除节点，策略，代理集，然后点更新订阅才顺利



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: vernesong ***@***.***&gt;
发送时间: 2022年9月20日 22:15
收件人: vernesong/OpenClash ***@***.***&gt;
抄送: anjue39 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [vernesong/OpenClash] 配置文件手动更新功能的加入 (#257)





   
订阅页面应用配置就是强制更新
  
不是吧，点了更新订阅，会提示配置文件没更新。到现在问题依然存在，更新订阅，如果订阅地址不变，会提示配置文件没更新。需要重新读取配置才可以，难道不可以点更新订阅后自动刷新列表吗？还可以加入一个选择。可以保留上次节点。可以自动去重
  
建议你使用代理集，代理集的地址可以直接填订阅地址，用meta内核可以再筛选节点
