### ISSUE TITLE
如何设置端口直连？

### ISSUE THREAD

**Issue by Venompool888** [vernesong/OpenClash#2570]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

作者您好，我是openclash作的旁路由，群晖网关指向的openclash所在的软路由，因为做种原因需要群晖的端口16881走直连，我在规则设置优先匹配中添加了
“- DST-PORT,16881,DIRECT
- SRC-PORT,16881,DIRECT”
但是通过pt站可以发现走的依旧是代理，
端口是内网16881映射到外网16881，请问我应当如何设置才能使其走直连呢？

### Describe the Solution

端口是内网16881映射到外网16881，请问我应当如何设置才能使其走直连呢？

**Comment by vernesong** [comment]
截图

**Comment by vernesong** [comment]
截图

**Comment by taoletsgo** [comment]
单纯设置端口是无效的，因为其他人的端口不是这个。

解决办法：
把下载工具（以qb举例）如docker里的qb设置bridge-host桥接，这样qb就单独被路由器分配了一个内网ip，然后你把这个内网ip添加进openclash访问控制的黑名单里

如何设置bridge-host?请参考这类文章或者搜关键字（如果你需要手动指定内网ip的话）
https://iqqoz.com/post-3046.html#gsc.tab=0

最后，记得对新的内网ip添加端口转发（主路由添加即可，我是op作为主路由，所以op的防火墙我设置了端口转发到这个新的内网ip）

**Comment by cicai1631** [comment]
> 类

我的不是群晖qb容器，而是群晖官方dm下载器(主要是来pt)
请问如何设置？

**Comment by taoletsgo** [comment]
> > 类
> 
> 我的不是群晖qb容器，而是群晖官方dm下载器(主要是来pt) 请问如何设置？

方法1.换成docker容器的下载工具，然后分配软路由网段内网ip
方法2.软路由当旁路由，群晖连接硬路由，科学上网插件为群晖设置常规端口
方法3.学习写代码，给openclash项目提交可用pr，实现以下功能（二选一即可）：
1）不同设备使用不同自定义运行规则;
2）pc走tun代理全部端口，群晖走redir-host代理普通端口）
方法4.换其他代理软件

**Comment by cicai1631** [comment]
> 


软路由和nas docker是内网同网段
硬路由也是设置软路由为网关，且群晖docker容器，有的容器也需要sockks5代理，这种情况如何搞群晖的dm下载器，pt走之恋，有的群晖docker容器代理？
