### ISSUE TITLE
[Bug] 更新完最新的meta内核alpha-g503b1ef后，rule模式国内网络访问出现问题

### ISSUE THREAD

**Issue by ShawsonBian** [vernesong/OpenClash#2571]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.35-beta

### Bug on Environment

Other

### Bug on Platform

Linux-armv8

### To Reproduce

我用的是R4S，7.25白天点了下“一键检查更新”，openclash客户端更新成功，但内核更新提示闪存不足，更新失败，此时dev和meta内核文件没了。
之后我又尝试单独更新获取内核文件，dev成功，meta内核还是报闪存不足，我再点了两次，就又更新成了。
之后就出现网络异常，用rule模式国内网络连不上；也是到了晚上才尝试关闭meta内核，发现一切正常，所以目前判断是meta内核的问题。
但不清楚是我更新出的问题，还是这个版本有bug，还麻烦有同样问题或者知道原因的大佬解答，谢谢。

### Describe the Bug

使用最新的alpha-g503b1ef版本meta内核，在rule模式下，访问国内网络出现降速和无法访问的问题，比如抖音、小红书

### OpenClash Log

生成调试日志发生错误

### Expected Behavior

能正常解析国内域名ip，meta内核在rule模式正常访问国内域名

**Comment by vernesong** [comment]
试试dev
