### ISSUE TITLE
[Bug] 关于开启自动更新dev和tun问题

### ISSUE THREAD

**Issue by Jejz168** [vernesong/OpenClash#2576]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.35-beta

### Bug on Environment

Lean

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

现在重新装。全部显示未知。

### Describe the Bug

客户端可能无法更新,因为squashfs格式的固件更新后不会释放闪存空间 
 难道只有ext4才行吗？之前是squashfs也没有问题。现在重新装。全部显示未知。必须开启别的科学才能更新dev和tun

希望告知解决办法

**Comment by vernesong** [comment]
试试更新dev

**Comment by Jejz168** [comment]
> 试试更新dev

选了分支也是未知。很奇怪。之前都没这样。这次重装openwrt。必须开别的科学。才能正常

**Comment by Jejz168** [comment]
如果显示未知。更新是更不了的。是不是地址被墙了？用了超链吗？

**Comment by vernesong** [comment]
默认非官方地址挂了，
![image](https://user-images.githubusercontent.com/42875168/181132502-89f5e9c8-dd7c-436c-b00d-212ddf47c259.png)

**Comment by Jejz168** [comment]
> 默认TUNA地址挂了，
> ![image](https://user-images.githubusercontent.com/42875168/181132502-89f5e9c8-dd7c-436c-b00d-212ddf47c259.png)

这里用自建的。好像也不行阿。超链是不是默认在主文件地址中就加入了？

**Comment by Jejz168** [comment]
下次更新能否加入dev呢。这样也可以防止下载不下来。导致开启不了

**Comment by y9858** [comment]
我手动上传内核 还是不行

**Comment by Jejz168** [comment]
> 我手动上传内核 还是不行

手动要把上传的改权限0777

**Comment by Jejz168** [comment]
> 我手动上传内核 还是不行

最好先用别的科学再下载。手动的比较麻烦

**Comment by Jejz168** [comment]
> 默认TUNA地址挂了， ![image](https://user-images.githubusercontent.com/42875168/181132502-89f5e9c8-dd7c-436c-b00d-212ddf47c259.png)

感谢大佬，已经正常了。
