### ISSUE TITLE
这个内核问题怎么解决

### ISSUE THREAD

**Issue by kimcnc** [vernesong/OpenClash#258]
SIGILL: illegal instruction
PC=0x87fb4 m=0 sigcode=128

goroutine 1 [running]:
runtime.asyncPreempt()
	/usr/lib/go-1.14/src/runtime/preempt_mipsx.s:40 +0x7c fp=0x1035bc0 sp=0x1035acc pc=0x87fb4
gopkg.in/yaml%2ev2.yaml_parser_fetch_next_token(0x105e480, 0x104f3e0)
	/home/vernesong/go/pkg/mod/gopkg.in/yaml.v2@v2.2.8/scannerc.go:693 +0xa74 fp=0x1035bf0 sp=0x1035bc4 pc=0x381008
gopkg.in/yaml%2ev2.yaml_parser_fetch_more_tokens(0x105e480, 0x105e588)
	/home/vernesong/go/pkg/mod/gopkg.in/yaml.v2@v2.2.8/scannerc.go:642 +0x50 fp=0x1035c08 sp=0x1035bf0 pc=0x380328
gopkg.in/yaml%2ev2.peek_token(...)
	/home/vernesong/go/pkg/mod/gopkg.in/yaml.v2@v2.2.8/parserc.go:47
gopkg.in/yaml%2ev2.yaml_parser_parse_indentless_sequence_entry(0x105e480, 0x105e588, 0x36ee38)
	/home/vernesong/go/pkg/mod/gopkg.in/yaml.v2@v2.2.8/parserc.go:632 +0x4a4 fp=0x1035cec sp=0x1035c08 pc=0x3791c4
gopkg.in/yaml%2ev2.yaml_parser_state_machine(0x105e480, 0x105e588, 0x201)
	/home/vernesong/go/pkg/mod/gopkg.in/yaml.v2@v2.2.8/parserc.go:128 +0x2a0 fp=0x1035d00 sp=0x1035cec pc=0x375ad8
gopkg.in/yaml%2ev2.yaml_parser_parse(0x105e480, 0x105e588, 0x1057001)
	/home/vernesong/go/pkg/mod/gopkg.in/yaml.v2@v2.2.8/parserc.go:72 +0xb4 fp=0x1035d10 sp=0x1035d00 pc=0x375800
gopkg.in/yaml%2ev2.(*parser).peek(0x105e480, 0x10e5d80)
	/home/vernesong/go/pkg/mod/gopkg.in/yaml.v2@v2.2.8/decode.go:105 +0x54 fp=0x1035d20 sp=0x1035d10 pc=0x36e20c
gopkg.in/yaml%2ev2.(*parser).sequence(0x105e480, 0x10cbc07)
	/home/vernesong/go/pkg/mod/gopkg.in/yaml.v2@v2.2.8/decode.go:205 +0x9c fp=0x1035d54 sp=0x1035d20 pc=0x36ee18
gopkg.in/yaml%2ev2.(*parser).parse(0x105e480, 0x10cbc40)
	/home/vernesong/go/pkg/mod/gopkg.in/yaml.v2@v2.2.8/decode.go:151 +0x20c fp=0x1035d7c sp=0x1035d54 pc=0x36e688
gopkg.in/yaml%2ev2.(*parser).mapping(0x105e480, 0x9)
	/home/vernesong/go/pkg/mod/gopkg.in/yaml.v2@v2.2.8/decode.go:217 +0xd4 fp=0x1035db4 sp=0x1035d7c pc=0x36f0ac
gopkg.in/yaml%2ev2.(*parser).parse(0x105e480, 0x103d403)
	/home/vernesong/go/pkg/mod/gopkg.in/yaml.v2@v2.2.8/decode.go:149 +0x1e4 fp=0x1035ddc sp=0x1035db4 pc=0x36e660
gopkg.in/yaml%2ev2.(*parser).document(0x105e480, 0x3)
	/home/vernesong/go/pkg/mod/gopkg.in/yaml.v2@v2.2.8/decode.go:175 +0xb4 fp=0x1035e0c sp=0x1035ddc pc=0x36e808
gopkg.in/yaml%2ev2.(*parser).parse(0x105e480, 0x0)
	/home/vernesong/go/pkg/mod/gopkg.in/yaml.v2@v2.2.8/decode.go:153 +0x180 fp=0x1035e34 sp=0x1035e0c pc=0x36e5fc
gopkg.in/yaml%2ev2.unmarshal(0x10b6000, 0xc937, 0xcb37, 0x480280, 0x100c870, 0x435c00, 0x0, 0x0)
	/home/vernesong/go/pkg/mod/gopkg.in/yaml.v2@v2.2.8/yaml.go:142 +0x22c fp=0x1035e84 sp=0x1035e34 pc=0x38f82c
gopkg.in/yaml%2ev2.Unmarshal(...)
	/home/vernesong/go/pkg/mod/gopkg.in/yaml.v2@v2.2.8/yaml.go:81
github.com/Dreamacro/clash/config.UnmarshalRawConfig(0x10b6000, 0xc937, 0xcb37, 0x0, 0x1050d20, 0x4ee7d9)
	/home/vernesong/home/clash/config/config.go:168 +0x278 fp=0x1035eb0 sp=0x1035e84 pc=0x427d18
github.com/Dreamacro/clash/config.Parse(0x10b6000, 0xc937, 0xcb37, 0xc937, 0xcb37, 0x0)
	/home/vernesong/home/clash/config/config.go:126 +0x4c fp=0x1035ecc sp=0x1035eb0 pc=0x427a3c
github.com/Dreamacro/clash/hub/executor.ParseWithBytes(...)
	/home/vernesong/home/clash/hub/executor/executor.go:75
github.com/Dreamacro/clash/hub/executor.ParseWithPath(0x7f862f82, 0x21, 0xc, 0x3307c500, 0x1080a4)
	/home/vernesong/home/clash/hub/executor/executor.go:70 +0x90 fp=0x1035eec sp=0x1035ecc pc=0x435c6c
github.com/Dreamacro/clash/hub/executor.Parse(...)
	/home/vernesong/home/clash/hub/executor/executor.go:60
github.com/Dreamacro/clash/hub.Parse(0x7f862f70, 0xe)
	/home/vernesong/home/clash/hub/hub.go:10 +0x50 fp=0x1035f0c sp=0x1035eec pc=0x44f4d8
main.main()
	/home/vernesong/home/clash/main.go:74 +0x2e4 fp=0x1035fc0 sp=0x1035f0c pc=0x44fb48
runtime.main()
	/usr/lib/go-1.14/src/runtime/proc.go:203 +0x284 fp=0x1035fec sp=0x1035fc0 pc=0x4f9ec
runtime.goexit()
	/usr/lib/go-1.14/src/runtime/asm_mipsx.s:651 +0x4 fp=0x1035fec sp=0x1035fec pc=0x87834

goroutine 6 [chan receive]:
github.com/Dreamacro/clash/common/observable.(*Observable).process(0x104eaa0)
	/home/vernesong/home/clash/common/observable/observable.go:16 +0xe4
created by github.com/Dreamacro/clash/common/observable.NewObservable
	/home/vernesong/home/clash/common/observable/observable.go:63 +0xa4

goroutine 7 [select]:
gopkg.in/eapache/channels%2ev1.(*InfiniteChannel).infiniteBuffer(0x100a210)
	/home/vernesong/go/pkg/mod/gopkg.in/eapache/channels.v1@v1.1.0/infinite_channel.go:49 +0x120
created by gopkg.in/eapache/channels%2ev1.NewInfiniteChannel
	/home/vernesong/go/pkg/mod/gopkg.in/eapache/channels.v1@v1.1.0/infinite_channel.go:19 +0x160

goroutine 8 [select]:
gopkg.in/eapache/channels%2ev1.(*InfiniteChannel).infiniteBuffer(0x100a220)
	/home/vernesong/go/pkg/mod/gopkg.in/eapache/channels.v1@v1.1.0/infinite_channel.go:49 +0x120
created by gopkg.in/eapache/channels%2ev1.NewInfiniteChannel
	/home/vernesong/go/pkg/mod/gopkg.in/eapache/channels.v1@v1.1.0/infinite_channel.go:19 +0x160

goroutine 9 [select]:
github.com/Dreamacro/clash/tunnel.(*Manager).handleCh(0x106c230, 0x103a2c0, 0x106c250, 0x106c260, 0x106c270)
	/home/vernesong/home/clash/tunnel/manager.go:81 +0xd4
created by github.com/Dreamacro/clash/tunnel.(*Manager).handle
	/home/vernesong/home/clash/tunnel/manager.go:74 +0x70

goroutine 10 [select]:
github.com/Dreamacro/clash/tunnel.(*Manager).handleCh(0x106c230, 0x103a300, 0x106c258, 0x106c268, 0x106c278)
	/home/vernesong/home/clash/tunnel/manager.go:81 +0xd4
created by github.com/Dreamacro/clash/tunnel.(*Manager).handle
	/home/vernesong/home/clash/tunnel/manager.go:75 +0xb4

goroutine 11 [chan receive]:
github.com/Dreamacro/clash/tunnel.process()
	/home/vernesong/home/clash/tunnel/tunnel.go:126 +0x118
created by github.com/Dreamacro/clash/tunnel.init.1
	/home/vernesong/home/clash/tunnel/tunnel.go:42 +0x44

goroutine 12 [chan receive]:
github.com/Dreamacro/clash/tunnel.processUDP()
	/home/vernesong/home/clash/tunnel/tunnel.go:110 +0x70
created by github.com/Dreamacro/clash/tunnel.process
	/home/vernesong/home/clash/tunnel/tunnel.go:122 +0x70

goroutine 13 [chan receive]:
github.com/Dreamacro/clash/tunnel.processUDP()
	/home/vernesong/home/clash/tunnel/tunnel.go:110 +0x70
created by github.com/Dreamacro/clash/tunnel.process
	/home/vernesong/home/clash/tunnel/tunnel.go:122 +0x70

goroutine 14 [chan receive]:
github.com/Dreamacro/clash/tunnel.processUDP()
	/home/vernesong/home/clash/tunnel/tunnel.go:110 +0x70
created by github.com/Dreamacro/clash/tunnel.process
	/home/vernesong/home/clash/tunnel/tunnel.go:122 +0x70

goroutine 15 [chan receive]:
github.com/Dreamacro/clash/tunnel.processUDP()
	/home/vernesong/home/clash/tunnel/tunnel.go:110 +0x70
created by github.com/Dreamacro/clash/tunnel.process
	/home/vernesong/home/clash/tunnel/tunnel.go:122 +0x70

r0   0x0	r1   0x200
r2   0x201	r3   0x105e480
r4   0x600	r5   0x10c8000
r6   0x10c80bc	r7   0xd
r8   0x1	r9   0x8
r10  0x10dffe0	r11  0x10de000
r12  0xff	r13  0x1
r14  0x0	r15  0x100
r16  0x0	r17  0x0
r18  0xf1	r19  0x10
r20  0x1057408	r21  0x10e5d80
r22  0x0	r23  0x890000
r24  0x18b	r25  0x2
r26  0x0	r27  0x0
r28  0x10d0288	r29  0x1035acc
r30  0x10000e0	r31  0x381008
pc   0x87fb4	link 0x381008
lo   0x0	hi   0x0
2020-03-20 14:21:32 OpenClash Can Not Start, Try Use Backup Rules Start Again

**Comment by vernesong** [comment]
暂时用hardfloat版本，等上游更新

**Comment by kimcnc** [comment]
MT7620A不支持hardfloat吧

**Comment by kimcnc** [comment]
v0.19.0-1-g86dfb65内核还是老样子

**Comment by c71an** [comment]
@vernesong @kimcnc 用go1.14.1编译可以解决

**Comment by kimcnc** [comment]
就是不会编译啊

**Comment by kimcnc** [comment]
> @vernesong @kimcnc 用go1.14.1编译可以解决

就是不会编译啊

**Comment by vernesong** [comment]
#280
