### ISSUE TITLE
[Bug] Hysteria 如何填入

### ISSUE THREAD

**Issue by wclmgcd** [vernesong/OpenClash#2582]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.41-beta

### Bug on Environment

Lean

### Bug on Platform

Linux-armv7

### To Reproduce

Hysteria在passwall都可以使用，但openclash中有几个选项不知道是什么，如何填写
passwall的选项如下：
混淆密码
认证类型
登录密码
QUIC TLS ALPN
域名
允许不安全连接
是否允许不安全连接。当勾选时，将跳过证书验证。
最大上行(Mbps)
最大下行(Mbps)

openclash中这些是对应那些项：
up
down
up_mbps
down_mbps
跳过证书验证
sni
alpn
obfs
auth
auth_str
ca
ca_str
recv_window_conn
recv_window
disable_mtu_discovery
指定出口网卡
指定路由标记

### Describe the Bug

Hysteria在passwall都可以使用，但openclash中有几个选项不知道是什么，如何填写

### OpenClash Log

无

### Expected Behavior

正常使用Hysteria

**Comment by vernesong** [comment]
没有参数就不填，updown必须写

**Comment by wclmgcd** [comment]
感谢大佬，可以了

**Comment by hcym** [comment]
普通内核还是必须什么内核

**Comment by hcym** [comment]
嗯，和服务端一样就行，感谢分享

**Comment by teddy780102** [comment]
up down填写什么？

**Comment by wclmgcd** [comment]
上传和下载带宽，与服务器设置相同

**Comment by teddy780102** [comment]
up_mbps
down_mbps这两个还用填什么？搞了好久不成功，楼主能否打码发个你的节点截图？？？？

**Comment by vernesong** [comment]
https://docs.metacubex.one/function/proxy/hysteria

**Comment by wclmgcd** [comment]
> up_mbps down_mbps这两个还用填什么？搞了好久不成功，楼主能否打码发个你的节点截图？？？？
![捕获](https://user-images.githubusercontent.com/13980437/183647790-1fab0add-f03a-4301-ac05-1edd6ff62260.JPG)

最好是重新安装一次openclash，我原来是从低版本升级上来的，使用vless和hysteria节点始终有问题，时可用时不可用，于是重新编译固件全新安装后没有出现问题
