### ISSUE TITLE
[Help] clash一直访问31.31.xxx 俄罗斯的ip，十几条链接一直connection状态 

### ISSUE THREAD

**Issue by xckai** [vernesong/OpenClash#2588]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v 0.45.41

### Bug on Environment

Lean

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

换了好几个内核，clash一直有链接31.31.xxx的ip
还是俄罗斯的ip地址，十几个链接一直激活；
请问有人知道原因么？

软路由+openclash
查看的是软路由的网络情况
![image](https://user-images.githubusercontent.com/5928422/181591863-1c8c6fba-a1a2-4b2e-acfc-c7447cc18c04.png)

### Describe the Bug

如上述

### OpenClash Log

无

### Expected Behavior

有人遇到么？

**Comment by eightsheep67** [comment]
你这不看看其他插件情况吗？这个又不一定是clash的连接

**Comment by vernesong** [comment]
看日志不就知道是谁在访问了吗

**Comment by xckai** [comment]
这两天没再出现，等后续观察；
