### ISSUE TITLE
开启绕行中国ip后，谷歌商店下载软件网路问题[Bug] 

### ISSUE THREAD

**Issue by XGGY** [vernesong/OpenClash#2593]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.41-213

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

经过反复测试，开启后会影响到手机google play下载软件或者更新软件的网络问题，有些软件会一直卡在下载中，有些会下载到99%就不动了。关闭绕行功能就正常了。

### Describe the Bug

如上

### OpenClash Log

无

### Expected Behavior

无

### Screenshots

![S20731-12114838](https://user-images.githubusercontent.com/11489381/182010019-0c276806-ab15-4f5d-b292-57504fc66e40.png)

**Comment by peeweep** [comment]
指定 googleapis.cn 走代理试试
```
 - DOMAIN-SUFFIX,googleapis.cn,Proxy
```

**Comment by exlulu** [comment]
这个问题在[v0.45.69-beta](https://github.com/vernesong/OpenClash/releases/tag/v0.45.69-beta)【fake-ip支持绕过大陆】延续下来了

**Comment by bzkmsjy** [comment]
> 指定 services.googleapis.cn 走代理试试
> 
> ```
>  - DOMAIN-SUFFIX,googleapis.cn,Proxy
> ```但是绕过大陆IP的流量就直接不经过内核了，写规则不可能有用的啊

**Comment by leonevilred** [comment]
0.45.157谷歌商店，google play store 问题依旧，the issue still exists
其他类似clash verge meta等没有问题

**Comment by HugoPresents** [comment]
在开启 fake ip 并且绕过大陆 ip 的情况下使用 nameserver-policy 指定 google 使用远程 dns
```yaml
nameserver-policy:
     "geosite:google": ['tls://1.1.1.1#disable-ipv6=true', 'tls://8.8.8.8#disable-ipv6=true']
```
并在 rules 中保证 `- GEOSITE,google,PROXY` 在 `- GEOSITE,cn,DIRECT` 前面
