### ISSUE TITLE
[Bug] 开启Meta内核后，如果打开启用流量（域名）探测功能，米家部分产品会离线

### ISSUE THREAD

**Issue by ics8023** [vernesong/OpenClash#2594]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.41-beta

### Bug on Environment

Lean

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

打开启用流量（域名）探测后，如米家的风扇，床头灯等会离线，关闭这个功能后恢复正常。

### Describe the Bug

不清楚什么情况造成

### OpenClash Log

日志无记录这个问题

### Expected Behavior

希望修复米家产品离线问题

**Comment by eightsheep67** [comment]
你要把meta设置里自定义嗅探打开啊

**Comment by ics8023** [comment]
> 你要把meta设置里自定义嗅探打开啊

非常感谢，原来没注意要开这个，已经解决

**Comment by iKira** [comment]
根治了，看这里：
https://github.com/MetaCubeX/mihomo/discussions/1994#discussioncomment-12990182
