### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Wyatt323** [vernesong/OpenClash#2595]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.35

### Bug on Environment

Other

### Bug on Platform

Linux-armv8

### To Reproduce

![image](https://user-images.githubusercontent.com/71224625/182323413-19361fd2-bc92-49f5-9603-511b741ee5ed.png)

### Describe the Bug

近期无法自动更新，但是之前是可以的

### OpenClash Log

![image](https://user-images.githubusercontent.com/71224625/182323536-c22de8f8-841c-4cee-aa72-99f6df459aea.png)

### Expected Behavior

希望可以解决这个闪存空间的问题

**Comment by ShawsonBian** [comment]
貌似在最新版修复了这个问题 更新到.41版本试试吧
