### ISSUE TITLE
可以提供旧版本的clash下载吗？

### ISSUE THREAD

**Issue by twtjy2008** [vernesong/OpenClash#26]
更新到0.34.3版本之后无法链接网络，原因不明，不知道是否和fallback-filter有关。想退回0.34.2版，但是找不到clash v0.15.0-32-g0d51877，可以提供一下吗？谢谢！

**Comment by vernesong** [comment]
有没有错误日志

**Comment by twtjy2008** [comment]
更新到0.34.4之后可以联网了，不过出现了下面的warning:
[warning] dial DIRECT error: dial tcp6: address 198.18.0.65: no suitable address found
设置里的ipv6 dns是false，设备也没有ipv6地址

**Comment by vernesong** [comment]
客户端缓存清理一下或者重启，日志出现fakeip一般是此类情况

**Comment by zxlhhyccc** [comment]
> 客户端缓存清理一下或者重启，日志出现fakeip一般是此类情况

请问您如何不重启路由的情况下清理缓存？

**Comment by twtjy2008** [comment]
> 客户端缓存清理一下或者重启，日志出现fakeip一般是此类情况

有些设备不好清理缓存或者重启，现在也能用，先用着吧。感谢及时修复

**Comment by vernesong** [comment]
更新一下吧，内核更新应该解决了

**Comment by twtjy2008** [comment]
更新到了0.34.5和对应的clash新内核，好像warning少了些，但是依然存在。用的是Fake-ip模式
[warning] dial DIRECT error: dial tcp6: address 216.58.194.170: no suitable address found
[warning] dial DIRECT error: dial tcp6: address 198.18.0.224: no suitable address found

另外，有一个一直以来都出现的情况是：每次应用配置之后，百度搜索，网易云音乐，GitHub，Facebook 和 YouTube 都连接正常，但是运行一段时间（10小时以上，一个晚上）之后，出现百度搜索无法连接，或者GitHub无法连接，或者Facebook无法连接，或者YouTube无法连接。

**Comment by vernesong** [comment]
这个我需要观察下，这边复现才能解决
