### ISSUE TITLE
lean 上出现，500 内部服务器错误

### ISSUE THREAD

**Issue by miroda** [vernesong/OpenClash#260]
OpenClash
一个运行在OpenWrt上的Clash客户端，兼容Shadowsocks、Vmess、Snell等协议，根据灵活的规则配置实现策略代理
500 内部服务器错误
对不起，服务器遇到未知错误。

/usr/lib/lua/luci/dispatcher.lua:381: Failed to execute function dispatcher target for entry '/admin/services/openclash'.
The called action terminated with an exception:
/usr/lib/lua/luci/dispatcher.lua:381: Failed to execute cbi dispatcher target for entry '/admin/services/openclash/client'.
The called action terminated with an exception:
/usr/lib/lua/luci/template.lua:55: Failed to execute template 'cbi/map'.
A runtime error occured: /usr/lib/lua/luci/template.lua:39: Failed to load template 'openclash/status'.
Error while parsing template '/usr/lib/lua/luci/view/openclash/status.htm':
Syntax error in /usr/lib/lua/luci/view/openclash/status.htm:1: unfinished string near '"'
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:381: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:95: in function 

有人说是luci-combat问题，请问谁知道

**Comment by YukawaMi** [comment]
这个是openwrt本身固有的问题………之前瞎装ipk遇到过，我一般遇到这种问题都是重装………
