### ISSUE TITLE
[Feature] 能够去掉这个"增加新依赖：unzip"

### ISSUE THREAD

**Issue by zfdang** [vernesong/OpenClash#2601]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

旧版本的固件，因为不含这个package，就没法升级了。。。

### Describe the Solution

旧版本的固件，因为不含这个package，就没法升级了。。。

**Comment by vernesong** [comment]
这个不行

**Comment by a904055262** [comment]
opkg 直接装个unzip

**Comment by zfdang** [comment]
去哪里找呢？kernel不对，是不是也安装不上去啊？

**Comment by Nvsdyi** [comment]
你这个理由有点牵强了，你的固件没有自己去编译一个不就好了，难道开发者还得考虑每个人的设备么

**Comment by kingsey** [comment]
那就别更新用旧版插件呗……
