### ISSUE TITLE
[Bug] 通过域名 http://openwrt.lan/ 访问 OpenWrt 管理界面时，openclash 的 Panel 无法访问

### ISSUE THREAD

**Issue by zhangjint5** [vernesong/OpenClash#2606]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.47-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

使用 http://openwrt.lan/ 访问 OpenWrt 管理界面，访问 OpenClash ，点击 Open Panel 按钮

### Describe the Bug

通过域名 http://openwrt.lan/ 访问 OpenWrt 管理界面时，openclash 的 Panel 无法访问

### OpenClash Log

无需日志

### OpenClash Config

```shell
无相关配置
```

### Expected Behavior

无需此项目

### Screenshots

![屏幕截图 2022-08-06 140900](https://user-images.githubusercontent.com/57692302/183237256-45f8ebf7-fd69-4aea-b3d6-721917b593ef.png)

**Comment by vernesong** [comment]
host填openwrt.lan

**Comment by zhangjint5** [comment]
> host填openwrt.lan

这样可以！不过如果能像使用ip访问一样 自动识别好的话 会更方便一些！
