### ISSUE TITLE
[Bug] 通过UDP连接的IP地址无法匹配自定义配置

### ISSUE THREAD

**Issue by kas12323** [vernesong/OpenClash#2608]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.41-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-mips-softfloat

### To Reproduce

将IP添加到自定义列表后匹配不生效
添加的规则是：
- IP-CIDR,185.218.24.0/24,🔰 选择节点

### Describe the Bug

将IP添加到自定义列表后匹配不生效

### OpenClash Log

无法生成，提示“发生了一些错误”

### Expected Behavior

正常匹配自定义规则

### Screenshots

![issue1](https://user-images.githubusercontent.com/90122331/183241161-1853faaa-2fec-4d38-a983-024b4e89679b.png)
![issue2](https://user-images.githubusercontent.com/90122331/183241162-ec6d165e-ffcf-4e48-9698-e13631ebf8d2.png)

**Comment by vernesong** [comment]
控制面板实际是啥？配置文件正常写入了规则吗

**Comment by kas12323** [comment]
我刚才更新到了最新版本，这个自定义配置直接不出现在控制面板里了（上一个版本至少会出现在控制面板，如上图1），不论怎么保存应用或是重启都不出现。

**Comment by kas12323** [comment]
我又设置了一下，现在控制面板的规则里有这个IP段了，但是在连接里这个IP段依然走的是“DIRECT”
![Uploading F5816536-AB81-4156-9C8F-7C698C945533.png…]()

**Comment by kas12323** [comment]
![2EE4F07B-7286-49FA-A870-C8A82E145EA7](https://user-images.githubusercontent.com/90122331/183245482-e3ea29aa-9c21-41ea-af57-eb05cbf90afc.jpeg)

**Comment by kas12323** [comment]
我又设置了一下，现在控制面板的规则里有这个IP段了，但是在连接里这个IP段依然走的是“DIRECT”
![09791259-064C-4CAF-89E9-B03921A161CF](https://user-images.githubusercontent.com/90122331/183245544-4b09ee70-3984-409e-8cf9-26eea15db26a.jpeg)
![C683802F-1478-4524-988A-E31A9D6577F2](https://user-images.githubusercontent.com/90122331/183245548-02a4dbd2-d1a8-4c55-a4a4-f6ed851bbc80.png)

**Comment by vernesong** [comment]
看下这个策略组是不是禁用了udp

**Comment by kas12323** [comment]
我看了一下，这个配置文件里面没有关于UDP的设置，不过我发现我确实所有的udp连接全部走的是direct连接，这个是因为VMESS不支持udp吗

**Comment by vernesong** [comment]
vmess也要写udp支持才行啊

**Comment by kas12323** [comment]
好的好的感谢，我去问问机场那边怎么说

**Comment by vernesong** [comment]
我说的是配置文件里面节点要写 udp true

**Comment by kas12323** [comment]
感谢，我按照你的方法修改了配置文件，现在UDP连接也能被匹配了，感谢！

**Comment by kas12323** [comment]
你好，还出现了一个问题，就是配置文件中的SSR节点无法连接，在手机上用shadowrocket或电脑上的clash都能连接成功，但是openclash上无法连接，也测不到延迟

**Comment by vernesong** [comment]
看下启动的配置文件里面的节点配置写错没有

**Comment by kas12323** [comment]
对照了一下原始的配置文件，启动的配置文件是正常的，没有写错的地方

**Comment by kas12323** [comment]
![Uploading 735A9DF0-E6B2-4421-A0D8-BB03B9337744.png…]()

**Comment by kas12323** [comment]
![AF0DA9BF-19B2-4C0D-B1E5-7976BEA69194](https://user-images.githubusercontent.com/90122331/183293073-da408bd9-0e3f-4bec-a932-88c36c33bb6d.png)

**Comment by vernesong** [comment]
看看控制面板报错吧

**Comment by kas12323** [comment]
没报错，选择SSR节点后并尝试打开谷歌，只有正常匹配并选择节点的日志（所有的日志等级全都试了一遍），chrome提示意外终止了连接ERR_CONNECTION_CLOSED，firefox提示建立安全连接失败PR_END_OF_FILE_ERROR，测试延迟也没有报错

**Comment by kas12323** [comment]
然后我用clash for windows再测试了一下，确认那几个ssr节点是正常的
