### ISSUE TITLE
手机端看youtube和Facebook视频会出现断流情况

### ISSUE THREAD

**Issue by oringring** [vernesong/OpenClash#261]
电脑端看youtube和Facebook视频没问题，就是手机端看youtube和Facebook视频会出现断流情况，通常只能缓冲看几秒然后就卡住了，用的是line1的规则，是规则的问题还是什么问题呢？

**Comment by yanyingjie007** [comment]
llhie1的在openclash我也遇上不上问题，比如youtube客户端头像不显示,你有这种情况？

**Comment by vernesong** [comment]
我一般用的神机规则，你们什么模式？fake-ip模式下，dns那块只管国内直连的不会对代理有影响，连接取决于服务器，只要你能连上

**Comment by oringring** [comment]
> 我一般用的神机规则，你们什么模式？fake-ip模式下，dns那块只管国内直连的不会对代理有影响，连接取决于服务器，只要你能连上

神机规则是Conners Hua 这个规则吗？

**Comment by vernesong** [comment]
嗯
