### ISSUE TITLE
[Bug] 启用meta内核的情况下节点筛选仍无效

### ISSUE THREAD

**Issue by saphhireBlue** [vernesong/OpenClash#2618]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.47-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-armv8

### To Reproduce

原有配置：考虑原带机场给出的订阅链接策略组单一，在保留订阅文件的基础上，启用了服务器与策略组管理下边的一键配置文件，拿到策略组后，关闭了一键配置文件选项。其余代理集无配置、服务器无配置（经观察，会从订阅链接生成的配置文件中获取，但可能会有一个从服务器节点里写入配置文件的重复写入过程，这里建议加入检测：原本代理集和服务器无配置即无法启用的情况下，改为增加为检测原有配置文件是否含有Proxies部分， 如果有不再读取至服务器与策略组下的服务器，避免重复读写）

考虑使用meta内核：修改上边步骤中保留的策略组，在Netflix策略组下填入节点筛选Net,保存后进入全局设置勾选启用meta内核，并同时勾选tcp并发与域名探测，保存配置并应用配置。OpenClash正常启动。在YACD和dashboard控制面板下，仍  出现不包含Net字符的节点。

### Describe the Bug

meta内核下，策略组配置中的节点筛选无效。

### OpenClash Log

由于PC损坏暂时无法获得配置文件并隐藏敏感信息，待处理后马上补上。

### Expected Behavior

策略组节点筛选能够正常使用，服务器与策略组配置下的服务器不再从配置文件重复读写。

**Comment by vernesong** [comment]
你看下配置文件的策略组有没有写入这个筛选的选项
