### ISSUE TITLE
[Feature] 第三方游戏规则和第三方规则集

### ISSUE THREAD

**Issue by AlasJiahui** [vernesong/OpenClash#2622]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

现有的第三方规则集感觉不是很全，比如现有的任天堂nintendo的规则就只有2条，但是这个大佬https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Clash/Nintendo里的规则有121条

### Describe the Solution

希望可以添加自定义第三方游戏规则和第三方规则集的源。
比如这个大佬的规则集就很全面、强大
https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Clash

**Comment by Nvsdyi** [comment]
不是有自定义规则集吗，就在下面

**Comment by Nvsdyi** [comment]
![game-settings.png](https://user-images.githubusercontent.com/98214647/184483506-055d81ef-c661-4cdf-a0f7-b071dd41b3e3.png)

**Comment by o0owcnmd** [comment]
具体怎么设置？  第三方规则集地址多少？ 怎么添加进OpenClash ，是在自定义规则集添加，还是第三方规则集添加

**Comment by AlasJiahui** [comment]
1455160564
***@***.***



&nbsp;
https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Clash
在里面寻找需要的规则，在自定义规则集里添加


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vernesong/OpenClash"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月23日(星期四) 上午10:49
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [vernesong/OpenClash] [Feature] 第三方游戏规则和第三方规则集 (Issue #2622)





 
具体怎么设置？  第三方规则集地址多少？ 怎么添加进OpenClash ，是在自定义规则集添加，还是第三方规则集添加
