### ISSUE TITLE
[Bug] 开启clash后有大量未知上传流量，消耗了上百G机场流量

### ISSUE THREAD

**Issue by xjx0524** [vernesong/OpenClash#2629]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [x] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.47-beta

### Bug on Environment

Lean

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

开启openclash后，有大量上传链接，src和dst都非局域网内ip，消耗了大量机场资源

### Describe the Bug

开启openclash后，有大量上传链接，src和dst都非局域网内ip，消耗了大量机场资源
![微信图片_20220814112210](https://user-images.githubusercontent.com/2041320/184524237-4dc42177-2f84-438b-bc60-de9b948569a8.png)

### OpenClash Log

OpenClash 调试日志

生成时间: 2022-08-14 11:18:11
插件版本: v0.45.47-beta
隐私提示: 上传此日志前请注意检查、屏蔽公网IP、节点、密码等相关敏感信息

```

#===================== 系统信息 =====================#

主机型号: Intel(R) Celeron(R) J4125 CPU @ 2.00GHz : 4 Core 4 Thread
固件版本: OpenWrt GDQ v4-1[2021]
LuCI版本: git-21.088.17646-3fe6408-1
内核版本: 5.4.106
处理器架构: x86_64

#此项有值时,如不使用IPv6,建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: 

#此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 

#===================== 依赖检查 =====================#

dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
iptables-mod-tproxy: 已安装
kmod-ipt-tproxy: 已安装
iptables-mod-extra: 已安装
kmod-ipt-extra: 已安装
libcap: 已安装
libcap-bin: 已安装
ruby: 已安装
ruby-yaml: 已安装
ruby-psych: 已安装
ruby-pstore: 已安装
kmod-tun(TUN模式): 已安装
luci-compat(Luci-19.07): 已安装
kmod-inet-diag(PROCESS-NAME): 未安装
unzip: 已安装

#===================== 内核检查 =====================#

运行状态: 未运行
已选择的架构: linux-amd64

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 2022.07.07-7-g56f0a92
Tun内核文件: 存在
Tun内核运行权限: 正常

Dev内核版本: v1.11.4-6-gbec4df7
Dev内核文件: 存在
Dev内核运行权限: 正常

Meta内核版本: alpha-g2899a12
Meta内核文件: 存在
Meta内核运行权限: 正常

#===================== 插件设置 =====================#

当前配置文件: /etc/openclash/config/flowercloud.yaml
启动配置文件: /etc/openclash/flowercloud.yaml
运行模式: fake-ip-mix
默认代理模式: rule
UDP流量转发(tproxy): 停用
DNS劫持: 启用
自定义DNS: 启用
IPV6代理: 停用
IPV6-DNS解析: 停用
禁用Dnsmasq缓存: 启用
自定义规则: 启用
仅允许内网: 停用
仅代理命中规则流量: 启用
仅允许常用端口流量: 停用
绕过中国大陆IP: 停用
DNS远程解析: 停用
路由本机代理: 停用

#启动异常时建议关闭此项后重试
混合节点: 停用
保留配置: 停用

#启动异常时建议关闭此项后重试
第三方规则: 停用

```

### Expected Behavior

请教如何查清来源

**Comment by xjx0524** [comment]
重新拨号获取新公网ip后，就不会再出现这些连接了，但不知道会不会过段时间重新出来

**Comment by tigerorc** [comment]
我在使用clash的过程中出现了类似的问题，经查是由于公网ip暴露被爬虫抓取导致，请检查防火墙设置或者关闭DMZ内网穿透，疑似与俄罗斯黑客活动有关，若有兴趣希望您发送一份log给予我进一步研究。

**Comment by xjx0524** [comment]
> 我在使用clash的过程中出现了类似的问题，经查是由于公网ip暴露被爬虫抓取导致，请检查防火墙设置或者关闭DMZ内网穿透，疑似与俄罗斯黑客活动有关，若有兴趣希望您发送一份log给予我进一步研究。

我的问题就是 clash 的 scoks 代理没设密码，并且路由器的防火墙没有设置拒绝入站流量，ip被扫到了被人当成代理跳板了。
设置下防火墙就好了，并且clash后来的版本更新也给socks代理加了随机密码

**Comment by CN-HEX** [comment]
老哥，方便问下是怎么设置的吗？遇到这问题了...

**Comment by gxt-kt** [comment]
我也是公网ip开了7890端口就会有大量未知流量，换一个端口就好了，估计就是7890端口太出名了被别人利用了。
