### ISSUE TITLE
静默模式出问题，开了debug模式就可以解决。

### ISSUE THREAD

**Issue by jackge0323** [vernesong/OpenClash#263]
今天发现一个问题，就是我开着静默模式，上谷歌，会出现连接已重置的提示，而且一直上不去，来回测了3-4分钟，但是我进路由器，打开控制面板，把模式改成debug，马上就通了，不明白这是什么原理？有朋友能解释一下吗？

**Comment by jackge0323** [comment]
还有个问题，之前36.11我用fake-ip增强，我家的nintendo Switch nat类型是b，但是我更新到36.12之后，nat类型就变成f了，有什么办法能解决这个问题吗？

**Comment by vernesong** [comment]
连接重置的问题我还无法确认原因，nat类型新版本没有动相关设置

**Comment by yanyingjie007** [comment]
> 连接重置的问题我还无法确认原因，nat类型新版本没有动相关设置

我也遇到链接重置问题，主要是 gmail 网页版和 youtube网页版和客户端，一开始以为是 DNS 问题，后来发现不是，是偶然的重置，时而正常，时而重置。我肯定自己的 配置是正常的

**Comment by vernesong** [comment]
我之前遇到这种情况切换节点会立马正常
