### ISSUE TITLE
[Bug] 端口转发+openclash+接口Lan中开启桥接接口会使端口转发失效

### ISSUE THREAD

**Issue by LuziJay** [vernesong/OpenClash#2630]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.16-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

现象1：openclash将**需要转发的域名**添加至fallback-Filter/高级设置 +  端口转发  +   接口Lan中**开启**桥接接口 = 端口转发失效
现象2：openclash将**需要转发的域名**添加至fallback-Filter/高级设置 +  端口转发  +   接口Lan中**关闭**桥接接口 = 端口转发正常
现象3：**关闭**openclash +  端口转发  +   接口Lan中**开启**桥接接口 = 端口转发正常
现象4：**关闭**openclash +  端口转发  +   接口Lan中**关闭**桥接接口 = 端口转发正常

很奇怪的是现象1需要端口转发的网站打不开时，tcping却ping得通

### Describe the Bug

此BUG影响到需要使用Lan多接口+openwrt+端口转发的人群

### OpenClash Log

![image](https://user-images.githubusercontent.com/91416749/184533863-79a99e7c-4f9b-45cc-b1ce-85438c3f580f.png)
![image](https://user-images.githubusercontent.com/91416749/184533868-32eadaa1-97d7-493e-bc7b-4ff93820f994.png)
![image](https://user-images.githubusercontent.com/91416749/184533875-8df6ee78-adfc-43d7-a50a-b374f5b4c9fe.png)

### Expected Behavior

能够使这三个功能能够同时使用

### Screenshots

![image](https://user-images.githubusercontent.com/91416749/184533863-79a99e7c-4f9b-45cc-b1ce-85438c3f580f.png)
![image](https://user-images.githubusercontent.com/91416749/184533868-32eadaa1-97d7-493e-bc7b-4ff93820f994.png)
![image](https://user-images.githubusercontent.com/91416749/184533875-8df6ee78-adfc-43d7-a50a-b374f5b4c9fe.png)

**Comment by LuziJay** [comment]
最新测试结果：只要是LAN口的桥接接口开关打开+openwrt，除非把需要转发的内网ip拉进黑名单，或者设置绕过本地端口，否则防火墙的端口转发功能一定失效

这个bug从37版本-现在这个版本我都测试了一下 一直都存在

望修复

**Comment by vernesong** [comment]
这个问题目前没想到办法，因为出去的流量会经过内核nat而进来的流量因为是本地地址所以不会经过内核，你可以暂时在访问控制设置绕过

**Comment by vernesong** [comment]
你可以看看哪个版本是正常的，我看看是什么改动造成的

**Comment by LuziJay** [comment]
> 

好像更早的版本就算不开桥街街口也无法正常转发，目前的版本不开桥接接口是可以正常转发的

**Comment by VAMPIRE0924** [comment]
我的情况稍好一点，开了绕过中国大陆模式，大陆的IP访问端口映射的服务是没问题的，但是海外的IP没办法访问，其它的情况差不多，海外TCP可以ping通，但是没办法访问。
刚从passwall换过来，用了俩个月觉得挺完美的，结果还是有问题，好像就没有比较完美的插件了

**Comment by VAMPIRE0924** [comment]
啥时候能修下这个问题就好了，上百条端口映射记录，手动设置绕过太消耗时间了

**Comment by vernesong** [comment]
插件设置里有来源流量控制

**Comment by VAMPIRE0924** [comment]
> 插件设置里有来源流量控制

映射记录太多了，设置绕过来源流量太耗时间了，目前能想到的方法就是让这些做了端口映射的主机不走openwrt网关出去，然后再手动设置http代理，零散的端口设置绕过来源流量

**Comment by VAMPIRE0924** [comment]
还有方法就是设置dmz映射给openwrt，然后走openwrt的设备再设置映射一次，没有走openwrt的还是走主路由映射，这样也可以，但是我本地有多个公网IP，所以不方便操作

**Comment by vernesong** [comment]
直接写配置文件开ss协议监听端口，规则直连，外网连接设备挂代理，规则为连接公网域名时用这个代理

**Comment by VAMPIRE0924** [comment]
不是自己用，自己想访问怎样都行
