### ISSUE TITLE
http proxy认证如何关闭

### ISSUE THREAD

**Issue by vany75** [vernesong/OpenClash#2632]
是否可以关闭http proxy的认证 不输入账号密码直接使用http proxy

**Comment by Miaoerr** [comment]
看手册里有：
[使用手册-SOCKS5、HTTP(S)认证信息](https://github.com/vernesong/OpenClash/wiki/SOCKS5%E3%80%81HTTP(S)%E8%AE%A4%E8%AF%81%E4%BF%A1%E6%81%AF)

> 在全局设置的页面下方配置SOCKS5/HTTP(S)认证信息

**Comment by jikkyfu** [comment]
v0.45.157-beta 这个版本只要重启openwrt ，这个地方就会重新生成一个新的账号。不论之前什么情况。
（1什么都没有，2新增一个但是没有启用，3，已经有一个，也启用了。）
