### ISSUE TITLE
筛选 节点 跟排除节点功能不生效

### ISSUE THREAD

**Issue by ding0828** [vernesong/OpenClash#264]
筛选 节点 跟排除节点功能不生效

筛选：添加了条件  命中的没导入
排除：添加排除不生效

**Comment by vernesong** [comment]
截图设置

**Comment by ding0828** [comment]
要排除GCP
![image](https://user-images.githubusercontent.com/40944328/77232719-d1cc6800-6bdd-11ea-9e8c-c76fa2dc5e0c.png)
但是无效  都会被导入
![image](https://user-images.githubusercontent.com/40944328/77232811-3091e180-6bde-11ea-87dd-3e6588290f65.png)

**Comment by vernesong** [comment]
脱敏的配置文件发一下给我测试

**Comment by ding0828** [comment]
port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: true
mode: Rule
log-level: silent
external-controller: '0.0.0.0:9090'
secret: ''
Proxy:
  -
    name: '🇹🇼 台湾 GCP节点1 - 100M带宽'
    type: ss
    server: 
    port: 
    cipher: xchacha20-ietf-poly1305
    password: 
    udp: true
    plugin: obfs
    plugin-opts:
      mode: tls
      host: 9537140689.ds.download.windowsupdate.com
  -
    name: '🇹🇼 台湾 GCP节点2 - 100M带宽'
    type: ss
    server: 
    port: 
    cipher: xchacha20-ietf-poly1305
    password: 
    udp: true
    plugin: obfs
    plugin-opts:
      mode: tls
      host: 9537140689.ds.download.windowsupdate.com
  -
    name: '🇹🇼 台湾 GCP节点3 - 100M带宽'
    type: ss
    server: 
    port: 
    cipher: xchacha20-ietf-poly1305
    password: 
    udp: true
    plugin: obfs
    plugin-opts:
      mode: tls
      host: 9537140689.ds.download.windowsupdate.com
  -
    name: '🇹🇼 台湾 普通节点1 - 100M带宽'
    type: ss
    server: 
    port: 
    cipher: xchacha20-ietf-poly1305
    password: 
    udp: true
    plugin: obfs
    plugin-opts:
      mode: tls
      host: 9537140689.ds.download.windowsupdate.com
  -
    name: '🇯🇵 日本 GCP节点1 - 100M带宽'
    type: ss
    server: 
    port: 
    cipher: xchacha20-ietf-poly1305
    password: 
    udp: true
    plugin: obfs
    plugin-opts:
      mode: tls
      host: 9537140689.ds.download.windowsupdate.com
  -
    name: '🇭🇰 香港 GCP节点1 - 100M带宽'
    type: ss
    server: 
    port: 
    cipher: xchacha20-ietf-poly1305
    password: 
    udp: true
    plugin: obfs
    plugin-opts:
      mode: tls
      host: 9537140689.ds.download.windowsupdate.com
  -
    name: '🇭🇰 香港 阿里云中继 - 30M带宽'
    type: ss
    server: 
    port: 
    cipher: xchacha20-ietf-poly1305
    password: 
    udp: true
    plugin: obfs
    plugin-opts:
      mode: tls
      host: 9537140689.ds.download.windowsupdate.com
'Proxy Group':
  -
    name: ⚡️Auto
    type: url-test
    proxies:
      - '🇹🇼 台湾 GCP节点1 - 100M带宽'
      - '🇹🇼 台湾 GCP节点2 - 100M带宽'
      - '🇹🇼 台湾 GCP节点3 - 100M带宽'
      - '🇹🇼 台湾 普通节点1 - 100M带宽'
      - '🇯🇵 日本 GCP节点1 - 100M带宽'
      - '🇭🇰 香港 GCP节点1 - 100M带宽'
      - '🇭🇰 香港 阿里云中继 - 30M带宽'
    url: 'http://www.gstatic.com/generate_204'
    interval: '300'
  -
    name: 🔰国外流量
    type: select
    proxies:
      - ⚡️Auto
      - '🇹🇼 台湾 GCP节点1 - 100M带宽'
      - '🇹🇼 台湾 GCP节点2 - 100M带宽'
      - '🇹🇼 台湾 GCP节点3 - 100M带宽'
      - '🇹🇼 台湾 普通节点1 - 100M带宽'
      - '🇯🇵 日本 GCP节点1 - 100M带宽'
      - '🇭🇰 香港 GCP节点1 - 100M带宽'
      - '🇭🇰 香港 阿里云中继 - 30M带宽'
  -
    name: ⚓️其他流量
    type: select
    proxies:
      - 🔰国外流量
      - 🚀直接连接
  -
    name: ✈️Telegram
    type: select
    proxies:
      - 🔰国外流量
      - '🇹🇼 台湾 GCP节点1 - 100M带宽'
      - '🇹🇼 台湾 GCP节点2 - 100M带宽'
      - '🇹🇼 台湾 GCP节点3 - 100M带宽'
      - '🇹🇼 台湾 普通节点1 - 100M带宽'
      - '🇯🇵 日本 GCP节点1 - 100M带宽'
      - '🇭🇰 香港 GCP节点1 - 100M带宽'
      - '🇭🇰 香港 阿里云中继 - 30M带宽'
  -
    name: 🎬Youtube
    type: select
    proxies:
      - 🔰国外流量
      - '🇹🇼 台湾 GCP节点1 - 100M带宽'
      - '🇹🇼 台湾 GCP节点2 - 100M带宽'
      - '🇹🇼 台湾 GCP节点3 - 100M带宽'
      - '🇹🇼 台湾 普通节点1 - 100M带宽'
      - '🇯🇵 日本 GCP节点1 - 100M带宽'
      - '🇭🇰 香港 GCP节点1 - 100M带宽'
      - '🇭🇰 香港 阿里云中继 - 30M带宽'
  -
    name: 🎬Netflix
    type: select
    proxies:
      - 🔰国外流量
      - '🇹🇼 台湾 GCP节点1 - 100M带宽'
      - '🇹🇼 台湾 GCP节点2 - 100M带宽'
      - '🇹🇼 台湾 GCP节点3 - 100M带宽'
      - '🇹🇼 台湾 普通节点1 - 100M带宽'
      - '🇯🇵 日本 GCP节点1 - 100M带宽'
      - '🇭🇰 香港 GCP节点1 - 100M带宽'
      - '🇭🇰 香港 阿里云中继 - 30M带宽'
  -
    name: 🎬国外媒体
    type: select
    proxies:
      - 🔰国外流量
      - '🇹🇼 台湾 GCP节点1 - 100M带宽'
      - '🇹🇼 台湾 GCP节点2 - 100M带宽'
      - '🇹🇼 台湾 GCP节点3 - 100M带宽'
      - '🇹🇼 台湾 普通节点1 - 100M带宽'
      - '🇯🇵 日本 GCP节点1 - 100M带宽'
      - '🇭🇰 香港 GCP节点1 - 100M带宽'
      - '🇭🇰 香港 阿里云中继 - 30M带宽'
  -
    name: 🍎苹果服务
    type: select
    proxies:
      - 🚀直接连接
      - 🔰国外流量
  -
    name: 🚀直接连接
    type: select
    proxies:
      - DIRECT

**Comment by vernesong** [comment]
在新版本测试正常，如有问题请更新后反馈

**Comment by ding0828** [comment]
还是一样  是因为机场的订阅格式有问题吗

time="2020-03-23T01:47:24+08:00" level=fatal msg="Parse config error: ProxyGroup[0]: `use` or `proxies` missing"

**Comment by vernesong** [comment]
你把服务器与策略组管理页面的内容删除了再尝试

**Comment by ding0828** [comment]
是删掉的，为了避免冲突，更新后我都是全删掉的，包含配置文件
然后再生成的

**Comment by vernesong** [comment]
那就没问题啊，你先删了再订阅，策略组里没节点是删选完的结果

**Comment by ding0828** [comment]
删除节点 删除策略组 删除订阅 删除配置
再新建订阅 使用筛选导入配置 提示上方的报错

**Comment by vernesong** [comment]
保留配置关了没有，策略组是不是跟订阅的一样

**Comment by ding0828** [comment]
保留配置关了，重新订阅后策略组进来了，但是节点都没进来

订阅网址内的内容应该也是没问题的，因为我试过直接把配置内容直接手动贴到配置文件 Clash可以正常启动，就是订阅用上筛选后取不到节点

**Comment by vernesong** [comment]
> 保留配置关了，重新订阅后策略组进来了，但是节点都没进来
> 
> 订阅网址内的内容应该也是没问题的，因为我试过直接把订阅的配置内容直接手动贴到配置文件 Clash可以正常启动，就是订阅用上筛选后取不到节点

你的订阅telegram上发我
