### ISSUE TITLE
openclash分流策略定向不成功

### ISSUE THREAD

**Issue by jiangzhi1m** [vernesong/OpenClash#265]
主要是netflix定向问题,我proxy定向的是香港服务器.netflix定向的是新加坡,但是netflix经常定向到香港

**Comment by wtser** [comment]
分流不是clash 规则定义的么

**Comment by vernesong** [comment]
奈飞的规则你指定为奈飞策略组了吗

**Comment by jiangzhi1m** [comment]
> 奈飞的规则你指定为奈飞策略组了吗

-谢谢作者回复；

我在全局设置-规则设置里是如下设置的：

自定义规则-停用；

第三方规则-lhie1；

以下除了必须走代理的流量、未匹配到规则的流量走proxy，苹果服务流量、广告流量以及国内流量走相应的direct和reject外，其余全是选择对应的策略；

因为我发现所有流量都会走proxy，而且我要看新加坡区奈飞，所以只能选择proxy新加坡节点，然后我又发现YouTube Premium不在新加坡提供服务，所以我又试了试在Global视频里面选择香港节点，刚开始能行，过了一天global视频又恢复到走proxy，我已关闭节点自动更新（因为作者之前说过更新会导致分流策略恢复默认状态）我使用的是dlercloud机场

**Comment by jiangzhi1m** [comment]
> 奈飞的规则你指定为奈飞策略组了吗

我发现我托管是带有规则的，然后第三方规则也启用了，觉得会有冲突，把自定义规则关了后短暂的能分流了，然后不一会儿就不行了；
还有一天，我关闭了节点更新，重启路由器分流策略依然恢复默认

**Comment by laoz77** [comment]
建议对Netflix和Youtube使用不同的分组。我目前就是让Netflix流量走机场的特定节点（比如美区节点），Youtube走自建的节点，平时搜索的走机场最快的节点。这样感觉速度很快。在一个配置文件中可以有多个url-test分组，可以根据需要自己设定这些分组。
