### ISSUE TITLE
[Feature] 能否增加对Trojan-Go的支持

### ISSUE THREAD

**Issue by panda-ABCD** [vernesong/OpenClash#2650]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

软路由使用x86版本的openwrt。现有版本openclash在订阅某机场trojan协议连接时，出现Disney+安卓版客户端无法播放的问题（登录选剧正常，播放时无限转圈圈），此时IOS客户端与PC浏览器能够正常播放，通过passwall以xray方式订阅相同连接，问题现象一样，但以trojan-go方式订阅后，问题解决。希望openclash也能支持以trojan-go方式订阅trojan连接。

### Describe the Solution

希望新版本的openclash在订阅trojan协议连接时，可以使用trojan-go方式，以更加适配服务器端协议。

**Comment by li-dianzheng** [comment]
Disney+安卓客户端无法播放视频，有没有可能是迪士尼的问题。我使用cfa，安卓上的小猫咪，也是同样的情况。

**Comment by panda-ABCD** [comment]
存在这种可能，但我换trojango方式订阅或者换ssr协议，安卓客户端都是正常的。
