### ISSUE TITLE
[Bug] 遇到升级后出现的问题，之前正常使用

### ISSUE THREAD

**Issue by marswow** [vernesong/OpenClash#2651]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.51-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-armv8

### To Reproduce

通过在线升级出现的bug，手动更新未尝试

### Describe the Bug

-我家里的路由拓扑结构
                   光猫
                     ┃
                  主路由
  ╱                                      ╲       
win10电脑                    R5S软路由 
---------------------------------------------------
1、我设置win10电脑通过设置操作系统代理模式访问软路由，
2、网关是主路由的网关
3、一键更新版本后就无法联网了，这样我上网就会受到断网影响
4、但是设置ip为R5S网关的时候就没问题，但是BT上传受影响
5、重置设置后这问题解决了
============================
但是插件的另一个问题就是关闭插件后R5S下的设备或通过代理走R5S都无法上网

### OpenClash Log

-

### OpenClash Config

```shell
-
```

### Expected Behavior

哪位大佬解释下问题出在哪里？

**Comment by Nvsdyi** [comment]
请提供调试日志
