### ISSUE TITLE
透明代理与HSTS的问题

### ISSUE THREAD

**Issue by ikelvingo** [vernesong/OpenClash#266]
无论使用Redir-Host还是Fake-IP模式，劫持局域网流量后，移动端可以正常访问各墙外站点，PC浏览器则会显示HSTS问题，如google.com的ssl证书会显示为Facebook的，导致触发HSTS，被中断浏览。Socks代理正常。
而同样使用其它如Passwall等代理软件，则均可以正常使用，无需通过socks代理。

**Comment by ikelvingo** [comment]
经过测试发现，是由于所使用openwrt固件中，防火墙被加入了两条自定义规则，注释两条自定义规则，并重启防火墙无效，需要重启路由才可以获得正确效果。
打扰了。

**Comment by ivanberry** [comment]
同样需要这个规则，请问是那两条规则，谢谢

**Comment by VioletEvergar-den** [comment]
是什么规则？

**Comment by sss132919** [comment]
谜语人滚出哥谭！！！！

**Comment by ikelvingo** [comment]
> 谜语人滚出哥谭！！！！

闭上你的嘴，然后圆润的离开github，你的素质不配在这里。

**Comment by sss132919** [comment]
> > 谜语人滚出哥谭！！！！
> 
> 闭上你的嘴，然后圆润的离开github，你的素质不配在这里。

诶，我就不，我气死你。你自己想滚就滚吧，你爷爷我想在哪就在哪，谜语人都该灭九族！！！！哈哈哈，气不气？

**Comment by ikelvingo** [comment]
> > > 谜语人滚出哥谭！！！！
> > 
> > 
> > 闭上你的嘴，然后圆润的离开github，你的素质不配在这里。
> 
> 诶，我就不，我气死你。你自己想滚就滚吧，你爷爷我想在哪就在哪，谜语人都该灭九族！！！！哈哈哈，气不气？

你这种二皮脸是有多贱？你现实中是有多失败才会这么贱？现实中不敢报复社会就翻墙出来躺贱？一个closed问题的timeline上犯贱？你赢了，毕竟人至贱则无敌，对贱人最好的手段就是block！
