### ISSUE TITLE
[Feature] 更改OpenClash依赖以适配OpenWrt22.03

### ISSUE THREAD

**Issue by LtD0gE** [vernesong/OpenClash#2660]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

在OpenWrt 22.03中，由于firewall4弃用iptables转为nftables，OpenClash无法进行流量转发。

### Describe the Solution

在22.03版本中将iptables依赖改为iptables-nft，随后重装OpenClash。

### Describe Alternatives

1. 在openwrt编译时加入iptables支持。个人实践里难搞，最终放弃。

**Comment by LtD0gE** [comment]
我的OpenWrt版本是22.03-rc6，在上述方案下正常使用、分流。

**Comment by ilworkcn** [comment]
分支: 22.03.0-rc6
内核: 5.15.58
同样有此问题

**Comment by topsite** [comment]
> 分支: 22.03.0-rc6 内核: 5.15.58 平台: x86_64 同样有此问题

你用的是那个小鸡过河的固件吧

**Comment by ilworkcn** [comment]
> > 分支: 22.03.0-rc6 内核: 5.15.58 平台: x86_64 同样有此问题
> 
> 
> 
> 你用的是那个小鸡过河的固件吧

不是

**Comment by palxex** [comment]
该方法在小米r3p路由器22.03rc6上无效。但在snapshot上有效。

**Comment by InspoOnU** [comment]
不是改变依赖就能解决的问题。nft防火墙还必须要卸载，否则OpenClash运行还是会出问题。

**Comment by xibaluo** [comment]
原来不转发是因为这个原因导致的。

希望支持nft哈

**Comment by yzbleaf** [comment]
> 将iptables依赖改为

能分享下具体操作方法吗？我也遇到同样问题。

**Comment by gujiangjiang** [comment]
22.03正式版也无法使用，流量没法转发，等官方更新了

**Comment by jwkinko** [comment]
必须支持 firewall4才行？

**Comment by palxex** [comment]
不清楚问题是什么，但应该不是iptables-nft和firewall4的问题。在snapshot上转发完全正常(还是r3p, r20432-f39d9ea0c2)。`opkg list-installed`可见安装了iptables-nft和firewall4，没装iptables或者任何带legacy字样的东西。

**Comment by gujiangjiang** [comment]
@palxex 搞不清楚什么问题，我昨天看到这条建议去安装了iptables-nft，并且卸载了iptables-legacy，但是依然无效，无法转发流量，所有的数据都是0，但是可以肯定的是防火墙的问题，但是具体怎么解决还得进一步研究

**Comment by jwkinko** [comment]
ssrp 装iptables-nft就能用了，clash可能还要改些东西

**Comment by ilworkcn** [comment]
换成中文话意思就是 把firewall4和他的依赖都卸载干净 然后换成firewall> Temporary workaround:
> 
> opkg update && opkg remove firewall4 --force-depends && opkg install firewall
> 
>

**Comment by wplook** [comment]
编译了dev分支的ipk，在22.03正式版正常使用，如果自己编译，切换到dev分支clone就行了。https://drive.google.com/file/d/1FwVRjulLY8F-zhxjR9_7PL-DGwI_cwod/view?usp=sharing

**Comment by wplook** [comment]
大佬貌似昨天更新了DEV版的，自己clone dev代码编译能正常使用，这是我编译好的，https://drive.google.com/file/d/1FwVRjulLY8F-zhxjR9_7PL-DGwI_cwod/view?usp=sharing
