### ISSUE TITLE
[Bug] SSR链接无法订阅，显示语法错误

### ISSUE THREAD

**Issue by MaoSuSu** [vernesong/OpenClash#2661]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.51-beta

### Bug on Environment

Lean

### Bug on Platform

Linux-armv8

### To Reproduce

在订阅中填入SSR的订阅地址

### Describe the Bug

SSR链接无法订阅，显示语法错误，链接可正常访问，同一个订阅链接在早期几个版本都无此问题

### OpenClash Log

无

### Expected Behavior

希望作者大大可以早些修复，谢谢！

### Screenshots

<img width="1027" alt="uTools_1661609750723" src="https://user-images.githubusercontent.com/45323874/187034323-93e1bd5b-eadb-4298-8fe0-5e5de72062e1.png">

**Comment by vernesong** [comment]
请提供详细的报错位置实际信息

**Comment by MaoSuSu** [comment]
> 请提供详细的报错位置实际信息

报错位置：
“配置文件订阅”下填写订阅链接并更新订阅

![uTools_1661905423397](https://user-images.githubusercontent.com/45323874/187566776-0d52cf98-e9c4-4319-8e8e-08895a9b1f6a.png)
（红框标注的位置就是出错的第207列）

具体情况：
填写的链接是在第三方网站将SSR订阅转Clash，这个链接在过去的Openclash版本中是可以正常订阅的，估计是Openclash的yaml语法检测那块有些问题，我换用纯Clash订阅链接是可以正常下载并启动Openclash的

**Comment by MaoSuSu** [comment]
> 你加个引号

抱歉，现在才看到消息
我试过了，加上引号没有作用，openclash启动的时候会自动修改配置文件，修改后引号就被去除了，也许大大可以为修改后的配置文件参数都默认加上引号？

**Comment by vernesong** [comment]
```
!!str 15978:

**Comment by MaoSuSu** [comment]
> !!str

<img width="1086" alt="image" src="https://user-images.githubusercontent.com/45323874/188256904-b6b6eb57-099c-4580-b34f-62231a0d038d.png">
不起作用诶

**Comment by MaoSuSu** [comment]
今天我重新测试了一下，发现配置文件校验失败可能是软件本身的问题，问题都是出现在内核启动前，目前mipsle soft的openclash v0.45.51-beta没有这个问题，出现问题的是armv8的v0.45.51-beta，不知道是不是大大在编译多版本openclash的时候有所疏漏？

**Comment by prunes81485216** [comment]
同样的问题，现在依旧存在哦

**Comment by prunes81485216** [comment]
楼主是怎么解决问题的能提供一下思路吗？我是大雕的360V6固件，订阅一直有问题，同样的转换链接其他客户端都可以使用

**Comment by MaoSuSu** [comment]
> 楼主是怎么解决问题的能提供一下思路吗？我是大雕的360V6固件，订阅一直有问题，同样的转换链接其他客户端都可以使用

我是大雕的闭源ax6，问题还没有解决，只能等作者在下个版本修复了

**Comment by prunes81485216** [comment]
> > 楼主是怎么解决问题的能提供一下思路吗？我是大雕的360V6固件，订阅一直有问题，同样的转换链接其他客户端都可以使用
> 
> 我是大雕的闭源ax6，问题还没有解决，只能等作者在下个版本修复了

那就是一模一样的固件，4460闭源，我是10.1的固件

**Comment by MaoSuSu** [comment]
> > > 楼主是怎么解决问题的能提供一下思路吗？我是大雕的360V6固件，订阅一直有问题，同样的转换链接其他客户端都可以使用
> > 
> > 
> > 我是大雕的闭源ax6，问题还没有解决，只能等作者在下个版本修复了
> 
> 那就是一模一样的固件，4460闭源，我是10.1的固件

你是用的大雕的群里的固件吗？方便指个路加个群吗？

**Comment by prunes81485216** [comment]
> > > > 楼主是怎么解决问题的能提供一下思路吗？我是大雕的360V6固件，订阅一直有问题，同样的转换链接其他客户端都可以使用
> > > 
> > > 
> > > 我是大雕的闭源ax6，问题还没有解决，只能等作者在下个版本修复了
> > 
> > 那就是一模一样的固件，4460闭源，我是10.1的固件
> 
> 你是用的大雕的群里的固件吗？方便指个路加个群吗？

加我Q 81485216

**Comment by MashiroX1** [comment]
> 你加个引号

ssr节点的protocol-param的内容必须加单引号，才能通过openclash启动前的配置文件检查。
Clash for Windows、Clash for Android、ShellClash都没有这个要求，证明这不是Clash内核必须的要求。openclash的检查过于严苛了。
希望修复这个bug。
谢谢。

**Comment by MaoSuSu** [comment]
在这写一个临时的解决方案：
前往openwrt目录-->usr/share/openclash.sh

在文件的66行（）下可以加入这个语句：sed -i "s/你的protocol-param中的参数/'&'/g" $CFG_FILE
这样即可实现ssr的自动订阅下载而无需手动修改配置文件
<img width="876" alt="image" src="https://user-images.githubusercontent.com/45323874/199991550-b145415a-f240-4d51-9a05-af20c0018d63.png">


其实我还写了个自认为更加完善的sed语句：sed -r "s/protocol-param: ([^,]+),/protocol-param: '\1',/g" $CFG_FILE
该语句在测试环境下可完美为所有protocol-param参数加上引号，但实际在openwrt中不起作用，原因不明

此次是针对配置文件进行修改，以达到ssr订阅通过的目的，并未对ruby yaml语法检测强度进行变动，故为临时解决方案

**Comment by vernesong** [comment]
事实上我这边并不会报错，可以尝试升级ruby版本
![image](https://user-images.githubusercontent.com/42875168/200136563-02ac218d-3777-4e3a-9f8f-fb809519b54a.png)

**Comment by prunes81485216** [comment]
> 事实上我这边并不会报错，可以尝试升级ruby版本
> ![image](https://user-images.githubusercontent.com/42875168/200136563-02ac218d-3777-4e3a-9f8f-fb809519b54a.png)
> 

3.1.2－1这个版本去哪更新？我的目前是3.1.2

**Comment by MaoSuSu** [comment]
> 事实上我这边并不会报错，可以尝试升级ruby版本
> ![image](https://user-images.githubusercontent.com/42875168/200136563-02ac218d-3777-4e3a-9f8f-fb809519b54a.png)

这个问题目前只出现在内核4.4上，在5.4、5.10、5.15的openwrt上也都未出现问题，不知内核版本会不会影响ruby yaml的检查方式？

**Comment by vernesong** [comment]
行吧，你这闭源固件我估计也没办法自己去解决，我看看用sed处理下

**Comment by prunes81485216** [comment]
> 行吧，你这闭源固件我估计也没办法自己去解决，我看看用sed处理下

期待大佬的更新！现在手动加引号也算还行的解决方案了。

**Comment by prunes81485216** [comment]
感谢大佬！！！
