### ISSUE TITLE
[Bug] 更新订阅配置不改变运行配置

### ISSUE THREAD

**Issue by Franky18** [vernesong/OpenClash#2663]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.51-beta

### Bug on Environment

Lean

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

修改远端配置文件的规则内容，在Openclash客户端更新配置文件订阅，查看该订阅配置的**_运行配置文件_**即可复现此问题。

### Describe the Bug

Openclash更新订阅后，**_本地订阅配置文件本身会改变_**，**_但运行配置文件不会改变_**，因此实际运行时并没有使用新的配置文件。定时自动、web界面手动、ssh手动：/usr/share/openclash/openclash.sh 更新订阅，都存在此问题。

定时自动、ssh手动：/etc/init.d/openclash restart 2>/dev/null 重启Openclash，Openclash也不会更新运行配置。

只有web界面在openclash主页最下方，点击按钮手动关闭Openclash，再手动开启Openclash， 才会更新运行配置。个人目前使用OpenWrt自动重启功能解决该问题。

本人只使用“配置文件订阅“功能，并未使用”服务器与策略组管理“，“规则集与策略组管理”功能，且订阅配置文件内不包含任何第三方规则集。
刚接触Openclash，只在上一版本[v0.45.47-beta]测试过，也存在同样问题，其他过往版本未测试。
没有在Dev版本测试过，不知道链接在哪里。

### OpenClash Log

问题易复现，所有依赖均已安装，且与其他高级功能无关，暂时不上传调试日志，有需要即上传。

### Expected Behavior

希望更新订阅配置文件后能够**_立即更新运行配置_**，保证配置文件更新即时生效。

**Comment by vernesong** [comment]
看下/tmp/openclash.change里面记录的文件路径

**Comment by Franky18** [comment]
> 看下/tmp/openclash.change里面记录的文件路径

感谢大佬指点，配置文件订阅命名不能有空格，有空格命名(eg. Space Ship)更新后/tmp/openclash.change内显示的配置文件文件路径在空格处有个换行，如下：
/etc/openclash/config/Spece
Ship.yaml

无空格命名(eg. Rocket)更新后正常：
/etc/openclash/config/Rockets.yaml Tue Aug 30 09:19:48 CST 2022

命名取消空格后Openclash正常运行，更新订阅后更新运行文件重新启动内核。
