### ISSUE TITLE
[Feature] 访问控制优化

### ISSUE THREAD

**Issue by itbencn** [vernesong/OpenClash#2672]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

由passwall插件转openclash使用的
功能都挺棒的 唯独访问控制用着不是太方便

### Describe the Solution

可以参考passwall的UI
通过下拉选择的方式很方便的将多个设备进行分组，并设置不同的代理模式

### Additional Context

<img width="1472" alt="Snipaste_2022-09-02_15-38-19" src="https://user-images.githubusercontent.com/42700064/188085530-5742fe1a-09c7-4d32-92b0-3a67a00b4d2f.png">

**Comment by taoletsgo** [comment]
需要该功能优化+1

**Comment by eightsheep67** [comment]
你这代理模式不应该写到规则里吗？为什么要用访问控制……

**Comment by eightsheep67** [comment]
理解错了……
不过passwall 和 clash的逻辑不太一样，clash是精确分流，你有特殊需求还是需要写到规则里。

**Comment by taoletsgo** [comment]
> 理解错了…… 不过passwall 和 clash的逻辑不太一样，clash是精确分流，你有分流需求还是需要写到规则里。

规则实现不了楼主所说的：a设备tun模式，b设备redir-host，c设备fake ip模式；
规则只能所有设备共用一套自定义规则；
规则只能单一内网设备如192.168.0.6全部端口设定代理/不走代理/拒绝，而不是192.168.0.6:80端口走GFW列表

当然楼主的想法以前我在issue里也写过折中解决方案（针对有docker 功能类的产品如群晖nas等）
https://github.com/vernesong/OpenClash/issues/2570#issuecomment-1207137014

**Comment by eightsheep67** [comment]
> > 理解错了…… 不过passwall 和 clash的逻辑不太一样，clash是精确分流，你有分流需求还是需要写到规则里。
> 
> 规则实现不了楼主所说的：a设备tun模式，b设备redir-host，c设备fake ip模式； 规则只能所有设备共用一套自定义规则； 规则只能单一内网设备如192.168.0.6全部端口设定代理/不走代理/拒绝，而不是192.168.0.6:80端口走GFW列表
> 
> 当然楼主的想法以前我在issue里也写过折中解决方案（针对有docker 功能类的产品如群晖nas等） [#2570 (comment)](https://github.com/vernesong/OpenClash/issues/2570#issuecomment-1207137014)

我看楼主所说的是大陆白名单模式、GFW模式，这个东西其实在clash里已经不适用了，相当于就是自定义规则模式。
需要不同的设备直连、或者全局很简单啊，直接规则设定设备IP直连或者走某个规则，那个规则可以随时选择 直连或者代理。
需要不同设备走大陆白名单或者GFW，这个一般是有特殊需求比如测速或者DDNS被代理，不然一般默认选大陆白名单，这个也都有规则可以设置排除。
你所说的同时运行不同的模式，估计要大改吧而且很耗费资源很容易崩溃……（感觉）

**Comment by shmily103** [comment]
passwall以前也用过，代码写的很中国化，而且还不以官方源码仓适配写代码，用起来心真的很累。

**Comment by sunr1s6** [comment]
> > > 理解错了…… 不过passwall 和 clash的逻辑不太一样，clash是精确分流，你有分流需求还是需要写到规则里。
> > 
> > 
> > 规则实现不了楼主所说的：a设备tun模式，b设备redir-host，c设备fake ip模式； 规则只能所有设备共用一套自定义规则； 规则只能单一内网设备如192.168.0.6全部端口设定代理/不走代理/拒绝，而不是192.168.0.6:80端口走GFW列表
> > 当然楼主的想法以前我在issue里也写过折中解决方案（针对有docker 功能类的产品如群晖nas等） [#2570 (comment)](https://github.com/vernesong/OpenClash/issues/2570#issuecomment-1207137014)
> 
> 我看楼主所说的是大陆白名单模式、GFW模式，这个东西其实在clash里已经不适用了，相当于就是自定义规则模式。 需要不同的设备直连、或者全局很简单啊，直接规则设定设备IP直连或者走某个规则，那个规则可以随时选择 直连或者代理。 需要不同设备走大陆白名单或者GFW，这个一般是有特殊需求比如测速或者DDNS被代理，不然一般默认选大陆白名单，这个也都有规则可以设置排除。 你所说的同时运行不同的模式，估计要大改吧而且很耗费资源很容易崩溃……（感觉）

只能说你根本就不懂PT

**Comment by sunr1s6** [comment]
> ### Verify Steps
> * [x]  Tracker 我已经在 [Issue Tracker](%E2%80%A6%E2%80%A6/) 中找过我要提出的问题
> * [x]  Need 当前 OpenClash 并不包含该功能特性或者还不完善
> * [x]  Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
> * [x]  Meaningful 我提交的不是无意义的 催促更新或修复 请求
> 
> ### Describe the Feature 描述功能
> 由passwall插件转openclash使用的 功能都挺棒的 唯独访问控制用着不是太方便
> 
> ### Describe the Solution 描述解决方案
> 可以参考passwall的UI 通过下拉选择的方式很方便的将多个设备进行分组，并设置不同的代理模式
> 
> ### Describe Alternatives 描述替代方案
> _No response_
> 
> ### Additional Context 其他上下文
> <img alt="Snipaste_2022-09-02_15-38-19" width="1472" src="https://user-images.githubusercontent.com/42700064/188085530-5742fe1a-09c7-4d32-92b0-3a67a00b4d2f.png">

请问下你的设置里 智能家居不代理， 下面还有个 仅直连， 这2个有什么区别吗？

**Comment by itbencn** [comment]
> > ### Verify Steps
> > 
> > * [x]   Tracker 我已经在 [Issue Tracker](%E2%80%A6%E2%80%A6/) 中找过我要提出的问题
> > * [x]   Need 当前 OpenClash 并不包含该功能特性或者还不完善
> > * [x]   Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
> > * [x]   Meaningful 我提交的不是无意义的 催促更新或修复 请求
> > 
> > ### Describe the Feature 描述功能
> > 由passwall插件转openclash使用的 功能都挺棒的 唯独访问控制用着不是太方便
> > ### Describe the Solution 描述解决方案
> > 可以参考passwall的UI 通过下拉选择的方式很方便的将多个设备进行分组，并设置不同的代理模式
> > ### Describe Alternatives 描述替代方案
> > _No response_
> > ### Additional Context 其他上下文
> > <img alt="Snipaste_2022-09-02_15-38-19" width="1472" src="https://user-images.githubusercontent.com/42700064/188085530-5742fe1a-09c7-4d32-92b0-3a67a00b4d2f.png">
> 
> 请问下你的设置里 智能家居不代理， 下面还有个 仅直连， 这2个有什么区别吗？

智能家居不代理就是字面意思
仅直连/代理指的是在自定义规则列表里指定的直连ip/域名就不代理、代理ip/域名就走代理，不在直连/代理列表里的任何ip域名都不代理
