### ISSUE TITLE
请求作者可以支持vless节点

### ISSUE THREAD

**Issue by Wyatt323** [vernesong/OpenClash#2673]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

我的机场全是vless节点，openclash订阅只有3个节点，用v2几十个

### Describe the Solution

可否支持vless

**Comment by xcf13363175** [comment]
meta内核已经支持，村通网

**Comment by Wyatt323** [comment]
请问meta下应该用v2的订阅链接还是clash的，我用clash的订阅出来还是只有几个，但是V2直接订阅失败

**Comment by github-office** [comment]
> 请问meta下应该用v2的订阅链接还是clash的，我用clash的订阅出来还是只有几个，但是V2直接订阅失败

订阅转换呀
