### ISSUE TITLE
fakeip模式下英雄联盟（国服）无法进入内置语音

### ISSUE THREAD

**Issue by jiangzhi1m** [vernesong/OpenClash#268]
不是偶然，只要是fake ip下，绝对不可能连接上内置语音，切换成兼容模式，立马能进入

**Comment by ding0828** [comment]
我也有一样的问题

**Comment by ikelvingo** [comment]
fake-ip模式下，基本可以确认不支持vpn、语音等服务，所以在路由器上，还是兼容模式的适应性比较号。

**Comment by vernesong** [comment]
开udp了吗

**Comment by eyaeya** [comment]
同样问题，包括腾讯会议，腾讯系的语音通话全跪（除了微信）

**Comment by eyaeya** [comment]
> 开udp了吗

已尝试过组合切换：
FakeIP（增强）+UDP转发启用
FakeIP（TUN）
非规则命中流量不走代理

**Comment by vernesong** [comment]
fakeip的情况特殊，应该是涉及的某些udp协议clash还没支持吧

**Comment by vernesong** [comment]
如果一定要使用，可以再尝试将抓到的域名加到dns高级设置里

**Comment by eyaeya** [comment]
> 如果一定要使用，可以再尝试将抓到的域名加到dns高级设置里

感谢，测试后再答复。

**Comment by eyaeya** [comment]
> > 如果一定要使用，可以再尝试将抓到的域名加到dns高级设置里
> 
> 感谢，测试后再答复。

首次测试失败，等待明天完全情况DNS缓存后，再次测试。

[配置]
运行模式：Fake-IP（增强）
代理UDP流量：启用
代理模式：Rule
本地DNS劫持：启用
禁止Dnsmasp缓存DNS：启用
（DNS）高级设置：启用
更新Fake-IP域名黑名单：已加入抓包域名

**Comment by eyaeya** [comment]
> fakeip的情况特殊，应该是涉及的某些udp协议clash还没支持吧

有一个新线索：
Redir-Host模式+代理UDP流量开启，的设置下。腾讯会议和其SDK同样无法语音。

附上腾讯会议官网下载链接，只要可以正常进入会议房间即为成功第一步、可与房间中另一人语音即为第二步成功。我目前仅达成过第一步。
https://cloud.tencent.com/product/tm

**Comment by vernesong** [comment]
> > fakeip的情况特殊，应该是涉及的某些udp协议clash还没支持吧
> 
> 有一个新线索：
> Redir-Host模式+代理UDP流量开启，的设置下。腾讯会议和其SDK同样无法语音。
> 
> 附上腾讯会议官网下载链接，只要可以正常进入会议房间即为成功第一步、可与房间中另一人语音即为第二步成功。我目前仅达成过第一步。
> https://cloud.tencent.com/product/tm

我这边fake-ip是正常的，电脑端走clash，手机用4G测试

**Comment by mephisX** [comment]
> > fakeip的情况特殊，应该是涉及的某些udp协议clash还没支持吧
> 
> 有一个新线索：
> Redir-Host模式+代理UDP流量开启，的设置下。腾讯会议和其SDK同样无法语音。
> 
> 附上腾讯会议官网下载链接，只要可以正常进入会议房间即为成功第一步、可与房间中另一人语音即为第二步成功。我目前仅达成过第一步。
> [cloud.tencent.com/product/tm](https://cloud.tencent.com/product/tm)

Redir-Host TUN模式肯定可以，我最近打台服英雄联盟没问题。

**Comment by eyaeya** [comment]
> > > fakeip的情况特殊，应该是涉及的某些udp协议clash还没支持吧
> > 
> > 
> > 有一个新线索：
> > Redir-Host模式+代理UDP流量开启，的设置下。腾讯会议和其SDK同样无法语音。
> > 附上腾讯会议官网下载链接，只要可以正常进入会议房间即为成功第一步、可与房间中另一人语音即为第二步成功。我目前仅达成过第一步。
> > https://cloud.tencent.com/product/tm
> 
> 我这边fake-ip是正常的，电脑端走clash，手机用4G测试

:innocent: @vernesong 请教：
1. 是Fake-IP模式具体的哪一种配置；
2. 是否加入了DNS黑名单。

**Comment by vernesong** [comment]
普通模式，打开udp，规则用的神机，关闭ipv6，dns只有114和119

**Comment by eyaeya** [comment]
> 37.2版本，普通模式fakeip，打开udp，规则用的神机，路由关闭ipv6，dns只有114和119，自定义规则，黑名单都没动，节点trojan，支持udp

难道我的Dler不支持UDP转发？

**Comment by vernesong** [comment]
> > 37.2版本，普通模式fakeip，打开udp，规则用的神机，路由关闭ipv6，dns只有114和119，自定义规则，黑名单都没动，节点trojan，支持udp
> 
> 难道我的Dler不支持UDP转发？

本身它也没走代理，看链接是tcp形式，我用ss节点也正常

**Comment by mephisX** [comment]
> > 37.2版本，普通模式fakeip，打开udp，规则用的神机，路由关闭ipv6，dns只有114和119，自定义规则，黑名单都没动，节点trojan，支持udp
> 
> 难道我的Dler不支持UDP转发？

你看看节点有这个参数没
```udp: true```

**Comment by eyaeya** [comment]
> > > 37.2版本，普通模式fakeip，打开udp，规则用的神机，路由关闭ipv6，dns只有114和119，自定义规则，黑名单都没动，节点trojan，支持udp
> > 
> > 
> > 难道我的Dler不支持UDP转发？
> 
> 你看看节点有这个参数没
> `udp: true`

@mephisX 有，在Yaml配置文件中的节点有这个参数。

**Comment by javierzhang0504** [comment]
暴雪战网语音fake-ip无法正常开启

**Comment by eyaeya** [comment]
> > 开udp了吗
> 
> 已尝试过组合切换：
> FakeIP（增强）+UDP转发启用
> FakeIP（TUN）
> 非规则命中流量不走代理
> 
> 同时也试过规则中将 Other设为直连，和通过抓包找到的腾讯音视频通话域名加入规则Direct

更正：
@vernesong 经过测试，发现 FakeIP（TUN）模式 我未正确测试。仅测试了 FakeIP（增强）+UDP转发启用。
测试后答复，目前正在寻找TUN kmod的openclash安装方法。

**Comment by eyaeya** [comment]
> 同时也试过规则中将 Other设为直连，和通过抓包找到的腾讯音视频通话域名加

@vernesong 正确安装  FakeIP（TUN）模式的内核后，在此模式下腾讯语音全部恢复正常。
希望原生 FakeIP（增强）+UDP转发启用 也可以支持。

**Comment by Regulus88** [comment]
经测试，Fake IP（TUN）对语音UDP流量的支持更好，测试内容包括腾讯系语音、阿里系语音、Telegram等。而在Fake IP（增强）模式下，语音均未能接通

**Comment by BerlinChan** [comment]
版本
openclash v0.39.6-beta
clash         v1.0.0-23-gb1d9dfd
clash_tun  2020.07.28.ge8f69b1

我用FakeIP(TUN)，腾讯会议语音仍然无声
Redir-Host（兼容）模式 一切正常

**Comment by eyaeya** [comment]
> 版本
> openclash v0.39.6-beta
> clash v1.0.0-23-gb1d9dfd
> clash_tun 2020.07.28.ge8f69b1
> 
> 我用FakeIP(TUN)，腾讯会议语音仍然无声
> Redir-Host（兼容）模式 一切正常

试试最新0.39.7的FakeIP混合模式，一切正常

**Comment by BerlinChan** [comment]
> > 版本
> > openclash v0.39.6-beta
> > clash v1.0.0-23-gb1d9dfd
> > clash_tun 2020.07.28.ge8f69b1
> > 我用FakeIP(TUN)，腾讯会议语音仍然无声
> > Redir-Host（兼容）模式 一切正常
> 
> 试试最新0.39.7的FakeIP混合模式，一切正常

测试了两天，用 Fake-IP(TUN-混合模式)确实好了，谢谢！
> > 版本
> > openclash v0.39.7-beta 
> > clash v1.0.0-33-g8b7c731 
> > clash_tun 2020.08.13.g827ef84

**Comment by etsam** [comment]
请问 用openClash 玩PUBG 一直都无法小队语音，有兄弟有解决办法吗
SSR+也不行 但是PASSWALL的 GWF模式可以 但是游戏经常卡掉，刷新慢。
