### ISSUE TITLE
[Bug] 每次重启系统或者重启OC后，代理模式都恢复到Rule

### ISSUE THREAD

**Issue by matthuo333** [vernesong/OpenClash#2687]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.47-beta

### Bug on Environment

Other

### Bug on Platform

Linux-armv8

### To Reproduce

1. 设置代理模式 为 Global
2. 重启OP系统或者重启OC
3. 代理模式又变为Rule

### Describe the Bug

总是恢复为Rule

### OpenClash Log

这个和配置或业务没关系，应该是载入配置文件的问题吧？

### Expected Behavior

保持当前设置，不因重启而改变

**Comment by vernesong** [comment]
插件全局设置里面设置
