### ISSUE TITLE
[Bug] 勾选自定义 Fallback-Filter 并替换内容时提示一个值或多个值为空

### ISSUE THREAD

**Issue by SeaGull1919** [vernesong/OpenClash#2689]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.59-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

勾选自定义 Fallback-Filter 将内容替换为 https://raw.githubusercontent.com/wxfyes/cf/main/openclashfallback.txt 后保存提示一个值或多个值为空
![image](https://github.com/SeaGull1919/OcBinaryData/blob/master/20220911102403.jpg)

### Describe the Bug

无

### OpenClash Log

无

### Expected Behavior

无

**Comment by vernesong** [comment]
用meta就行了，不用写这么多
![image](https://user-images.githubusercontent.com/42875168/189525953-c59f4a2b-a4e1-4e36-ae8d-11f45e4d2014.png)

**Comment by WYSSYJY** [comment]
> 用meta就行了，不用写这么多 ![image](https://user-images.githubusercontent.com/42875168/189525953-c59f4a2b-a4e1-4e36-ae8d-11f45e4d2014.png)

找你写的，外网全部瘫痪
