### ISSUE TITLE
linux kernel 4.19 是不是无法安装 openclash？

### ISSUE THREAD

**Issue by jfdnet** [vernesong/OpenClash#269]
linux kernel 4.19 是不是无法安装 openclash？ 换成4.14 就可以。

Installing luci-app-openclash (0.36.12-beta) to root...
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-app-openclash:
 *      kernel (= 4.19.108-1-3eaead0264b0c72dd8c795ba8cea0c3b)
 * opkg_install_cmd: Cannot install package luci-app-openclash.

**Comment by vernesong** [comment]
自己编译一下即可

**Comment by jfdnet** [comment]
谢谢
