### ISSUE TITLE
[Bug] Yacd面板显示问题

### ISSUE THREAD

**Issue by ximiTech** [vernesong/OpenClash#2693]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.59-beta

### Bug on Environment

Lean

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

无需

### Describe the Bug

Yacd面板 “代理” 项显示有问题，变为纵向

### OpenClash Log

无需

### OpenClash Config

```shell
无需
```

### Expected Behavior

Yacd面板 “代理” 项显示与其他项一致

### Screenshots

![1](https://user-images.githubusercontent.com/63538901/189615056-e9afef94-5752-4e57-a950-c6deadae4d6f.JPG)
![2](https://user-images.githubusercontent.com/63538901/189615067-7522950b-dbd5-48ab-90ac-5e17ca4fcce4.JPG)

**Comment by maskedeken** [comment]
[https://github.com/haishanh/yacd/pull/715](https://github.com/haishanh/yacd/pull/715)
