### ISSUE TITLE
更新到0.34.3之后经常死机

### ISSUE THREAD

**Issue by laoz77** [vernesong/OpenClash#27]
更新到0.34.3之后经常死机，对应的clash版本号：v0.15.0-44-gb76737b。需要手动重新启动。
部分日志如下：
2019/09/18 09:11:57 http: Accept error: accept tcp 0.0.0.0:9090: accept4: too many open files; retrying in 1s
2019/09/18 09:11:58 http: Accept error: accept tcp 0.0.0.0:9090: accept4: too many open files; retrying in 1s
2019/09/18 09:11:59 http: Accept error: accept tcp 0.0.0.0:9090: accept4: too many open files; retrying in 1s
2019/09/18 09:12:00 http: Accept error: accept tcp 0.0.0.0:9090: accept4: too many open files; retrying in 1s
2019/09/18 09:12:01 http: Accept error: accept tcp 0.0.0.0:9090: accept4: too many open files; retrying in 1s
2019/09/18 09:12:02 http: Accept error: accept tcp 0.0.0.0:9090: accept4: too many open files; retrying in 1s
2019/09/18 09:12:03 http: Accept error: accept tcp 0.0.0.0:9090: accept4: too many open files; retrying in 1s
2019-09-18 17:12:04 OpenClash Start Successful

**Comment by vernesong** [comment]
更新再试一下

**Comment by laoz77** [comment]
谢谢！已经更新，正在观察。

**Comment by laoz77** [comment]
经过一天多都没有出现问题了。谢谢！
