### ISSUE TITLE
warning 日志分析求助

### ISSUE THREAD

**Issue by yanyingjie007** [vernesong/OpenClash#270]
最近出现gmail YouTube时而打不开，时而打得开，warning级别日志出现以下情况：

time="2020-03-22T12:29:14Z" level=warning msg="dial DIRECT error: dial tcp4 172.217.160.110:443: i/o timeout"
time="2020-03-22T12:29:16Z" level=warning msg="dial DIRECT error: dial tcp4 172.217.24.5:443: i/o timeout"
time="2020-03-22T12:29:26Z" level=warning msg="dial DIRECT error: dial tcp4 216.58.200.46:443: i/o timeout"
time="2020-03-22T12:29:26Z" level=warning msg="dial DIRECT error: dial tcp4 172.217.24.5:443: i/o timeout"

解析出了IP，IP查询也是Google的IP，但是为什么会出现timeout?节点问题应该排除了，请指教

PS:内网情况：openclash部署在网关，内网有个DNS服务器pi-hole，内网设备DNS地址是这个pi-hole，pi-hole的上游服务器只有一个，就是网关，应该不存在DNS污染的问题，其实手动把设备的DNS地址改为网关也会出现这样的问题，

**Comment by vernesong** [comment]
openclash的自定义上游dns设置为pi-hole，下面设备使用网关的地址做dns

**Comment by yanyingjie007** [comment]
> openclash的自定义上游dns设置为pi-hole，下面设备使用网关的地址做dns

感谢这么快速的回复，

这样设置使我很糊涂，

假设我把openclash的上游DNS设置为pihole，pihole的上游DNS设置为公共DNS吗？

这样无法保证pihole得到的解析信息是没被污染吧？解析过程容易被劫持和污染。

还有您说下面的设备使用网关的地址做DNS

那么假设openclash上游DNS设置为pihole，那么我局域网里面的设备的DNS设置为网关或者pihole似乎没什么区别吧，

烦请指教

**Comment by vernesong** [comment]
clash的nameserver只保留pihole，pihole的设置不用动。
redir模式下还需要在fallback加国外dns，fake模式不需要。

openclash正常工作的情况下因为劫持了dns所以只要网关指向正确，客户端的dns其实无所谓，但为了避免异常建议你设置成网关。

**Comment by yanyingjie007** [comment]
感谢回复，

我这个问题似乎不是由于pihole引起的，问题的根本原因肯定是DNS污染，我把内网设备的DNS手动指向网关，还是会出现这种情况。

现在怀疑是dlercloud自带的规则问题，但是我切换升级规则，后台ycad后台打开proxy selector里面还是和原来的一样。是没切换规则成功吗？

**Comment by vernesong** [comment]
规则都显示是直连了，你肯定访问不了啊
你的dns通过clash向上游查询，clash的规则判定才会生效
proxy selector里的是节点和策略组，你换规则跟他们没关系
