### ISSUE TITLE
[Bug] 日志输出只有DNS，开了debug。

### ISSUE THREAD

**Issue by skill7899** [vernesong/OpenClash#2706]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.59-beta

### Bug on Environment

Other

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

打开控制面板-日志选debug

### Describe the Bug

日志输出全是dns，我用redir，app访问不了disney+，切换成fake-ip可以，本来想看一下日志在那里出了问题，结果全是DNS，

### OpenClash Log

无

### Expected Behavior

应该会输出error以及match

**Comment by Suchbear** [comment]
v0.45.59-beta   我也有这个问题，日志输出只有DNS，而且看不见连接，不确定是不是一个问题
