### ISSUE TITLE
[Bug] Windows Youtube 不可访问，Mac Android均可以

### ISSUE THREAD

**Issue by assist726** [vernesong/OpenClash#2707]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v1.11.4-13-g6e058f8

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

Windows Youtube 不可访问，Mac Android均可以

### Describe the Bug

已经尝试换多个不同的浏览器 cmd  ipconfig /flushdns 浏览器内flush dns 重启openclash 设置全局模式 都没有解决问题

### OpenClash Log

使用youtube.com

正在收集数据...

找不到任何连接日志！

1. 可能是插件未在运行

2. 可能是缓存导致浏览直接使用 IP 地址进行访问

3. 可能是 DNS 未劫持成功，导致 Clash 无法正确反推出域名连接

4. 可能是所填地址无法进行解析和连接

使用instagram。com则正常

### Expected Behavior

正常打开youtube

**Comment by openips** [comment]
明天都用 没问题

**Comment by assist726** [comment]
> 明天都用 没问题

后来调试发现了问题是电脑开启加速器才会导致youtube无法访问

电脑上的Clash+加速器倒是没问题， openclash有什么配置改动可解决问题呢？

**Comment by vernesong** [comment]
如果加速器劫持了流量就没办法

**Comment by lloyd18** [comment]
我的是Redir-Host（兼容）模式下iOS　YouTube　无法后台播放，其它所有模式都没问题

**Comment by liby** [comment]
> 如果加速器劫持了流量就没办法

感觉我遇到的问题，和楼主比较像，但我没为 PS5 开启什么加速器

https://github.com/vernesong/OpenClash/discussions/2780
