### ISSUE TITLE
[Bug] Redir-Host模式下github无法访问的问题

### ISSUE THREAD

**Issue by ximiTech** [vernesong/OpenClash#2714]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.59-beta

### Bug on Environment

Lean

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

设置模式为Redir-Host，等待网站访问检查Github项为正常后，发现至少有三种方式复现：
1.在控制面板中切换Github的代理，10s内，网站访问检查Github项变为无法访问
2.关闭当前浏览器再重开，网站访问检查Github项变为无法访问
3.新开另一个浏览器，打开主界面，网站访问检查Github项变为无法访问

### Describe the Bug

Redir-Host模式访问Github失效的问题

### OpenClash Log

无log，设置应该没问题

### OpenClash Config

```shell
无
```

### Expected Behavior

设置模式为Redir-Host，等待网站访问检查Github项为正常后，
1.切换代理Github的服务器，github能正常访问
2.关闭重开浏览器，github能正常访问
3.新开另一个浏览器，在此浏览器中，github也能正常访问

### Screenshots

无

**Comment by LuXun20220905** [comment]
我也遇到同样的问题了，更换各种配置文件和规则都还是有这个问题，时好时坏。

**Comment by vernesong** [comment]
配置呢

**Comment by ximiTech** [comment]
配置就是配置为Redir-Host，保证Youtube能通就行，Youtube就一直能通，Github访问会变成有问题。

**Comment by charlie1227** [comment]
> 配置就是配置为Redir-Host，保证Youtube能通就行，Youtube就一直能通，Github访问会变成有问题。
我也遇到这样的情况，怀疑是DNS问题，刷新电脑端DNS后，问题解决。

**Comment by caliban511** [comment]
我也遇到类似的问题，改成混合模式就能用，另外两种都不正常。

**Comment by vernesong** [comment]
![image](https://user-images.githubusercontent.com/42875168/198331771-0753c28a-5287-45ef-90a0-ef86030328fb.png)

**Comment by caliban511** [comment]
> DNS开远端解析，开fallbackfilter

这样加了但是没用啊，，，github 还是连不上，，，
![屏幕截图 2022-10-28 024352](https://user-images.githubusercontent.com/13557387/198372875-7c8af99f-418a-44c9-a25c-d2ec8500fbe4.png)

**Comment by QuincySx** [comment]
最近我也很头疼这件事，排查了好久没有头绪，感觉是 Meta 内核的问题。Redir-Host 兼容模式很多网站就是不正常。其他模式和 Fake-IP 都没问题。

**Comment by ximiTech** [comment]
进一步使用后发现，这个问题在原版内核下存在，在meta内核下没有问题。
