### ISSUE TITLE
[Feature] 切换了fake-ip可不可以加上不走代理的局域网设备 IP

### ISSUE THREAD

**Issue by skill7899** [vernesong/OpenClash#2719]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

用face-ip会导致nat类型不正确

### Describe the Solution

切换到face-ip之后，也可以加上不走代理的局域网设备 IP

**Comment by skill7899** [comment]
[已经有一样的了](https://github.com/vernesong/OpenClash/issues/2506)

**Comment by htgg1** [comment]
> 已经有一样的了

什么有一样的 我需要这个功能
