### ISSUE TITLE
[Feature] 关于在请求头UA中显示版本号

### ISSUE THREAD

**Issue by moranno** [vernesong/OpenClash#2723]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

目前OpenClash发送UA的时候只有一个Clash，导致用户获取订阅时候无法分辨用户使用的版本。
（老版本的clash可能会导致特征泄露 https://github.com/Dreamacro/clash/issues/1468 ）
如果UA发送版本号的话，可以禁止用户使用老版本发起订阅，提示用户升级。

### Describe the Solution

申请在请求头UA中加入版本号。

**Comment by vernesong** [comment]
机场有这个需求吗

**Comment by moranno** [comment]
> 机场有这个需求吗

强烈需求。
