### ISSUE TITLE
[Feature] 给旁路由，手机使用中问题提供一个思路(不一定都适用)。

### ISSUE THREAD

**Issue by CrazyArson** [vernesong/OpenClash#2724]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

使用中发现，电脑，平板等其他设备都能被open劫持DNS，但是手机的连接就全是IP(被运营商DNS污染过可能)，这就导致像google.com访问不了，但是google.com.hk就可以，youtube加载不出预览图，但是视频又能播放，或者其他很多奇奇怪怪的问题，找了很多论坛，贴吧也没能解决。

### Describe the Solution

找到一个答案说，安卓手机会预先解析域名，openclash没办法劫持到，在测试静态地址里面填谷歌dns，依旧没用，后面发现有个私人DNS，把他改成dns.google.com之后，完美解决，虽然连接还是显示IP，但google解析的大概没加工过，youtube之类的也能正常使用了。
另外一点就是这个私人DNS建议填dns.google.com，不要使用阿里，腾讯之类的，我测试用dns.ipv6dns.com之后，某黄黑网站是打不开的，所以对国内的DNS供应商保持一定的戒备心比较好

**Comment by Astlm** [comment]
感谢 一堆玄学问题总算解决了
