### ISSUE TITLE
[Bug] openclash导致手机唤醒异常，造成耗电

### ISSUE THREAD

**Issue by LovelyToaster** [vernesong/OpenClash#2729]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.59-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

打开openclash，手机熄屏出现异常唤醒
关闭openclash，现象消失

### Describe the Bug

手机会出现大量异常唤醒导致耗电异常
尝试更换openclash 规则 内核 版本 均无法消失
手机和平板多次刷机清除data，更换系统内核，系统版本 均无法消失
原先使用树莓派4b时也有这个问题

### OpenClash Log

#===================== 系统信息 =====================#

主机型号: Huawei CT6100
固件版本: OpenWrt 22.03.0 r19685-512e76967f
LuCI版本: git-20.074.84698-ead5e81
内核版本: 5.10.138
处理器架构: x86_64

#此项有值时,如不使用IPv6,建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: 

#此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 

#===================== 依赖检查 =====================#

dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
libcap: 已安装
libcap-bin: 已安装
ruby: 已安装
ruby-yaml: 已安装
ruby-psych: 已安装
ruby-pstore: 已安装
kmod-tun(TUN模式): 已安装
luci-compat(Luci >= 19.07): 已安装
kmod-inet-diag(PROCESS-NAME): 已安装
unzip: 已安装
kmod-nft-tproxy: 已安装

#===================== 内核检查 =====================#

运行状态: 运行中
进程pid: 15336
运行权限: 15336: cap_dac_override,cap_net_bind_service,cap_net_admin,cap_net_raw,cap_sys_ptrace,cap_sys_resource=eip
运行用户: nobody
已选择的架构: linux-amd64

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 2022.08.26-3-ge16bdd2
Tun内核文件: 存在
Tun内核运行权限: 正常

Dev内核版本: v1.11.8-3-g4f291fa
Dev内核文件: 存在
Dev内核运行权限: 正常

Meta内核版本: alpha-g9b89ff9
Meta内核文件: 存在
Meta内核运行权限: 正常

#===================== 插件设置 =====================#

当前配置文件: /etc/openclash/config/config.yaml
启动配置文件: /etc/openclash/config.yaml
运行模式: redir-host-mix
默认代理模式: rule
UDP流量转发(tproxy): 停用
DNS劫持: 停用
自定义DNS: 启用
IPV6代理: 停用
IPV6-DNS解析: 启用
禁用Dnsmasq缓存: 启用
自定义规则: 停用
仅允许内网: 启用
仅代理命中规则流量: 停用
仅允许常用端口流量: 停用
绕过中国大陆IP: 停用
DNS远程解析: 停用
路由本机代理: 启用

#启动异常时建议关闭此项后重试
混合节点: 停用
保留配置: 停用

#启动异常时建议关闭此项后重试
第三方规则: 停用
#===================== IPTABLES 防火墙设置 =====================#

#IPv4 NAT chain

#IPv4 Mangle chain

# Generated by iptables-save v1.8.7 on Sat Oct  8 21:08:23 2022
*mangle
:PREROUTING ACCEPT [7727873:10688022312]
:INPUT ACCEPT [4241708:6344008839]
:FORWARD ACCEPT [3459825:4338772124]
:OUTPUT ACCEPT [3699428:6487883523]
:POSTROUTING ACCEPT [7158298:10825971030]
:mwan3_connected_ipv4 - [0:0]
:mwan3_custom_ipv4 - [0:0]
:mwan3_dynamic_ipv4 - [0:0]
:mwan3_hook - [0:0]
:mwan3_iface_in_wan - [0:0]
:mwan3_iface_in_wan1 - [0:0]
:mwan3_iface_in_wan2 - [0:0]
:mwan3_iface_in_wan3 - [0:0]
:mwan3_ifaces_in - [0:0]
:mwan3_policy_balanced - [0:0]
:mwan3_rule_https - [0:0]
:mwan3_rules - [0:0]
-A PREROUTING -j mwan3_hook
-A OUTPUT -j mwan3_hook
-A mwan3_connected_ipv4 -m set --match-set mwan3_connected_ipv4 dst -j MARK --set-xmark 0x3f00/0x3f00
-A mwan3_custom_ipv4 -m set --match-set mwan3_custom_ipv4 dst -j MARK --set-xmark 0x3f00/0x3f00
-A mwan3_dynamic_ipv4 -m set --match-set mwan3_dynamic_ipv4 dst -j MARK --set-xmark 0x3f00/0x3f00
-A mwan3_hook -m mark --mark 0x0/0x3f00 -j CONNMARK --restore-mark --nfmask 0x3f00 --ctmask 0x3f00
-A mwan3_hook -m mark --mark 0x0/0x3f00 -j mwan3_ifaces_in
-A mwan3_hook -m mark --mark 0x0/0x3f00 -j mwan3_custom_ipv4
-A mwan3_hook -m mark --mark 0x0/0x3f00 -j mwan3_connected_ipv4
-A mwan3_hook -m mark --mark 0x0/0x3f00 -j mwan3_dynamic_ipv4
-A mwan3_hook -m mark --mark 0x0/0x3f00 -j mwan3_rules
-A mwan3_hook -j CONNMARK --save-mark --nfmask 0x3f00 --ctmask 0x3f00
-A mwan3_hook -m mark ! --mark 0x3f00/0x3f00 -j mwan3_custom_ipv4
-A mwan3_hook -m mark ! --mark 0x3f00/0x3f00 -j mwan3_connected_ipv4
-A mwan3_hook -m mark ! --mark 0x3f00/0x3f00 -j mwan3_dynamic_ipv4
-A mwan3_iface_in_wan -i eth1 -m set --match-set mwan3_custom_ipv4 src -m mark --mark 0x0/0x3f00 -m comment --comment default -j MARK --set-xmark 0x3f00/0x3f00
-A mwan3_iface_in_wan -i eth1 -m set --match-set mwan3_connected_ipv4 src -m mark --mark 0x0/0x3f00 -m comment --comment default -j MARK --set-xmark 0x3f00/0x3f00
-A mwan3_iface_in_wan -i eth1 -m set --match-set mwan3_dynamic_ipv4 src -m mark --mark 0x0/0x3f00 -m comment --comment default -j MARK --set-xmark 0x3f00/0x3f00
-A mwan3_iface_in_wan -i eth1 -m mark --mark 0x0/0x3f00 -m comment --comment wan -j MARK --set-xmark 0x100/0x3f00
-A mwan3_iface_in_wan1 -i vth0 -m set --match-set mwan3_custom_ipv4 src -m mark --mark 0x0/0x3f00 -m comment --comment default -j MARK --set-xmark 0x3f00/0x3f00
-A mwan3_iface_in_wan1 -i vth0 -m set --match-set mwan3_connected_ipv4 src -m mark --mark 0x0/0x3f00 -m comment --comment default -j MARK --set-xmark 0x3f00/0x3f00
-A mwan3_iface_in_wan1 -i vth0 -m set --match-set mwan3_dynamic_ipv4 src -m mark --mark 0x0/0x3f00 -m comment --comment default -j MARK --set-xmark 0x3f00/0x3f00
-A mwan3_iface_in_wan1 -i vth0 -m mark --mark 0x0/0x3f00 -m comment --comment wan1 -j MARK --set-xmark 0x200/0x3f00
-A mwan3_iface_in_wan2 -i vth1 -m set --match-set mwan3_custom_ipv4 src -m mark --mark 0x0/0x3f00 -m comment --comment default -j MARK --set-xmark 0x3f00/0x3f00
-A mwan3_iface_in_wan2 -i vth1 -m set --match-set mwan3_connected_ipv4 src -m mark --mark 0x0/0x3f00 -m comment --comment default -j MARK --set-xmark 0x3f00/0x3f00
-A mwan3_iface_in_wan2 -i vth1 -m set --match-set mwan3_dynamic_ipv4 src -m mark --mark 0x0/0x3f00 -m comment --comment default -j MARK --set-xmark 0x3f00/0x3f00
-A mwan3_iface_in_wan2 -i vth1 -m mark --mark 0x0/0x3f00 -m comment --comment wan2 -j MARK --set-xmark 0x300/0x3f00
-A mwan3_iface_in_wan3 -i vth2 -m set --match-set mwan3_custom_ipv4 src -m mark --mark 0x0/0x3f00 -m comment --comment default -j MARK --set-xmark 0x3f00/0x3f00
-A mwan3_iface_in_wan3 -i vth2 -m set --match-set mwan3_connected_ipv4 src -m mark --mark 0x0/0x3f00 -m comment --comment default -j MARK --set-xmark 0x3f00/0x3f00
-A mwan3_iface_in_wan3 -i vth2 -m set --match-set mwan3_dynamic_ipv4 src -m mark --mark 0x0/0x3f00 -m comment --comment default -j MARK --set-xmark 0x3f00/0x3f00
-A mwan3_iface_in_wan3 -i vth2 -m mark --mark 0x0/0x3f00 -m comment --comment wan3 -j MARK --set-xmark 0x400/0x3f00
-A mwan3_ifaces_in -m mark --mark 0x0/0x3f00 -j mwan3_iface_in_wan
-A mwan3_ifaces_in -m mark --mark 0x0/0x3f00 -j mwan3_iface_in_wan3
-A mwan3_ifaces_in -m mark --mark 0x0/0x3f00 -j mwan3_iface_in_wan1
-A mwan3_ifaces_in -m mark --mark 0x0/0x3f00 -j mwan3_iface_in_wan2
-A mwan3_policy_balanced -m mark --mark 0x0/0x3f00 -m statistic --mode random --probability 0.25000000000 -m comment --comment "wan3 1 4" -j MARK --set-xmark 0x400/0x3f00
-A mwan3_policy_balanced -m mark --mark 0x0/0x3f00 -m statistic --mode random --probability 0.33300000010 -m comment --comment "wan2 1 3" -j MARK --set-xmark 0x300/0x3f00
-A mwan3_policy_balanced -m mark --mark 0x0/0x3f00 -m statistic --mode random --probability 0.50000000000 -m comment --comment "wan1 1 2" -j MARK --set-xmark 0x200/0x3f00
-A mwan3_policy_balanced -m mark --mark 0x0/0x3f00 -m comment --comment "wan 1 1" -j MARK --set-xmark 0x100/0x3f00
-A mwan3_rule_https -m mark --mark 0x0/0x3f00 -j mwan3_policy_balanced
-A mwan3_rule_https -m mark ! --mark 0xfc00/0xfc00 -j SET --del-set mwan3_rule_ipv4_https src,src
-A mwan3_rule_https -m mark ! --mark 0xfc00/0xfc00 -j SET --add-set mwan3_rule_ipv4_https src,src
-A mwan3_rules -p tcp -m multiport --dports 443 -m mark --mark 0x0/0x3f00 -j mwan3_rule_https
-A mwan3_rules -m mark --mark 0x0/0x3f00 -j mwan3_policy_balanced
COMMIT
# Completed on Sat Oct  8 21:08:23 2022

#IPv4 Filter chain

# Generated by iptables-save v1.8.7 on Sat Oct  8 21:08:23 2022
*filter
:INPUT ACCEPT [150759284:213485143127]
:FORWARD ACCEPT [9284169:7434801026]
:OUTPUT ACCEPT [136877810:210903492108]
COMMIT
# Completed on Sat Oct  8 21:08:23 2022

#IPv6 NAT chain

#IPv6 Mangle chain

# Generated by ip6tables-save v1.8.7 on Sat Oct  8 21:08:23 2022
*mangle
:PREROUTING ACCEPT [23476:5217379]
:INPUT ACCEPT [525:44215]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [319:33399]
:POSTROUTING ACCEPT [319:33399]
:mwan3_connected_ipv6 - [0:0]
:mwan3_custom_ipv6 - [0:0]
:mwan3_dynamic_ipv6 - [0:0]
:mwan3_hook - [0:0]
:mwan3_ifaces_in - [0:0]
:mwan3_policy_balanced - [0:0]
:mwan3_rule_https - [0:0]
:mwan3_rules - [0:0]
-A PREROUTING -j mwan3_hook
-A OUTPUT -j mwan3_hook
-A mwan3_connected_ipv6 -m set --match-set mwan3_connected_ipv6 dst -j MARK --set-xmark 0x3f00/0x3f00
-A mwan3_custom_ipv6 -m set --match-set mwan3_custom_ipv6 dst -j MARK --set-xmark 0x3f00/0x3f00
-A mwan3_dynamic_ipv6 -m set --match-set mwan3_dynamic_ipv6 dst -j MARK --set-xmark 0x3f00/0x3f00
-A mwan3_hook -p ipv6-icmp -m icmp6 --icmpv6-type 133 -j RETURN
-A mwan3_hook -p ipv6-icmp -m icmp6 --icmpv6-type 134 -j RETURN
-A mwan3_hook -p ipv6-icmp -m icmp6 --icmpv6-type 135 -j RETURN
-A mwan3_hook -p ipv6-icmp -m icmp6 --icmpv6-type 136 -j RETURN
-A mwan3_hook -p ipv6-icmp -m icmp6 --icmpv6-type 137 -j RETURN
-A mwan3_hook -m mark --mark 0x0/0x3f00 -j CONNMARK --restore-mark --nfmask 0x3f00 --ctmask 0x3f00
-A mwan3_hook -m mark --mark 0x0/0x3f00 -j mwan3_ifaces_in
-A mwan3_hook -m mark --mark 0x0/0x3f00 -j mwan3_custom_ipv6
-A mwan3_hook -m mark --mark 0x0/0x3f00 -j mwan3_connected_ipv6
-A mwan3_hook -m mark --mark 0x0/0x3f00 -j mwan3_dynamic_ipv6
-A mwan3_hook -m mark --mark 0x0/0x3f00 -j mwan3_rules
-A mwan3_hook -j CONNMARK --save-mark --nfmask 0x3f00 --ctmask 0x3f00
-A mwan3_hook -m mark ! --mark 0x3f00/0x3f00 -j mwan3_custom_ipv6
-A mwan3_hook -m mark ! --mark 0x3f00/0x3f00 -j mwan3_connected_ipv6
-A mwan3_hook -m mark ! --mark 0x3f00/0x3f00 -j mwan3_dynamic_ipv6
-A mwan3_policy_balanced -m mark --mark 0x0/0x3f00 -m comment --comment unreachable -j MARK --set-xmark 0x3e00/0x3f00
-A mwan3_rule_https -m mark --mark 0x0/0x3f00 -j mwan3_policy_balanced
-A mwan3_rule_https -m mark ! --mark 0xfc00/0xfc00 -j SET --del-set mwan3_rule_ipv6_https src,src
-A mwan3_rule_https -m mark ! --mark 0xfc00/0xfc00 -j SET --add-set mwan3_rule_ipv6_https src,src
-A mwan3_rules -p tcp -m multiport --dports 443 -m mark --mark 0x0/0x3f00 -j mwan3_rule_https
-A mwan3_rules -m mark --mark 0x0/0x3f00 -j mwan3_policy_balanced
COMMIT
# Completed on Sat Oct  8 21:08:23 2022

#IPv6 Filter chain

# Generated by ip6tables-save v1.8.7 on Sat Oct  8 21:08:23 2022
*filter
:INPUT ACCEPT [7253:514869]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [1667678:830643180]
COMMIT
# Completed on Sat Oct  8 21:08:23 2022

#===================== NFTABLES 防火墙设置 =====================#

table inet fw4 {
	chain dstnat {
		type nat hook prerouting priority dstnat; policy accept;
		meta nfproto ipv4 tcp dport 53 counter packets 0 bytes 0 accept comment "OpenClash TCP DNS Hijack"
		iifname "br-lan" jump dstnat_lan comment "!fw4: Handle lan IPv4/IPv6 dstnat traffic"
		iifname { "vth0", "eth1", "vth1", "vth2" } jump dstnat_wan comment "!fw4: Handle wan IPv4/IPv6 dstnat traffic"
		ip protocol tcp counter packets 44 bytes 2384 jump openclash
	}
}
table inet fw4 {
	chain dstnat {
		type nat hook prerouting priority dstnat; policy accept;
		meta nfproto ipv4 tcp dport 53 counter packets 0 bytes 0 accept comment "OpenClash TCP DNS Hijack"
		iifname "br-lan" jump dstnat_lan comment "!fw4: Handle lan IPv4/IPv6 dstnat traffic"
		iifname { "vth0", "eth1", "vth1", "vth2" } jump dstnat_wan comment "!fw4: Handle wan IPv4/IPv6 dstnat traffic"
		ip protocol tcp counter packets 44 bytes 2384 jump openclash
	}
}
table inet fw4 {
	chain dstnat {
		type nat hook prerouting priority dstnat; policy accept;
		meta nfproto ipv4 tcp dport 53 counter packets 0 bytes 0 accept comment "OpenClash TCP DNS Hijack"
		iifname "br-lan" jump dstnat_lan comment "!fw4: Handle lan IPv4/IPv6 dstnat traffic"
		iifname { "vth0", "eth1", "vth1", "vth2" } jump dstnat_wan comment "!fw4: Handle wan IPv4/IPv6 dstnat traffic"
		ip protocol tcp counter packets 44 bytes 2384 jump openclash
	}
}
table inet fw4 {
	chain dstnat {
		type nat hook prerouting priority dstnat; policy accept;
		meta nfproto ipv4 tcp dport 53 counter packets 0 bytes 0 accept comment "OpenClash TCP DNS Hijack"
		iifname "br-lan" jump dstnat_lan comment "!fw4: Handle lan IPv4/IPv6 dstnat traffic"
		iifname { "vth0", "eth1", "vth1", "vth2" } jump dstnat_wan comment "!fw4: Handle wan IPv4/IPv6 dstnat traffic"
		ip protocol tcp counter packets 44 bytes 2384 jump openclash
	}
}
table inet fw4 {
	chain dstnat {
		type nat hook prerouting priority dstnat; policy accept;
		meta nfproto ipv4 tcp dport 53 counter packets 0 bytes 0 accept comment "OpenClash TCP DNS Hijack"
		iifname "br-lan" jump dstnat_lan comment "!fw4: Handle lan IPv4/IPv6 dstnat traffic"
		iifname { "vth0", "eth1", "vth1", "vth2" } jump dstnat_wan comment "!fw4: Handle wan IPv4/IPv6 dstnat traffic"
		ip protocol tcp counter packets 44 bytes 2384 jump openclash
	}
}
table inet fw4 {
	chain dstnat {
		type nat hook prerouting priority dstnat; policy accept;
		meta nfproto ipv4 tcp dport 53 counter packets 0 bytes 0 accept comment "OpenClash TCP DNS Hijack"
		iifname "br-lan" jump dstnat_lan comment "!fw4: Handle lan IPv4/IPv6 dstnat traffic"
		iifname { "vth0", "eth1", "vth1", "vth2" } jump dstnat_wan comment "!fw4: Handle wan IPv4/IPv6 dstnat traffic"
		ip protocol tcp counter packets 44 bytes 2384 jump openclash
	}
}
table inet fw4 {
	chain dstnat {
		type nat hook prerouting priority dstnat; policy accept;
		meta nfproto ipv4 tcp dport 53 counter packets 0 bytes 0 accept comment "OpenClash TCP DNS Hijack"
		iifname "br-lan" jump dstnat_lan comment "!fw4: Handle lan IPv4/IPv6 dstnat traffic"
		iifname { "vth0", "eth1", "vth1", "vth2" } jump dstnat_wan comment "!fw4: Handle wan IPv4/IPv6 dstnat traffic"
		ip protocol tcp counter packets 44 bytes 2384 jump openclash
	}
}

#===================== IPSET状态 =====================#

Name: mwan3_dynamic_ipv6
Name: mwan3_connected_ipv4
Name: mwan3_connected_ipv6
Name: mwan3_custom_ipv4
Name: mwan3_custom_ipv6
Name: mwan3_rule_ipv4_https
Name: mwan3_rule_ipv6_https
Name: mwan3_dynamic_ipv4

#===================== 路由表状态 =====================#

#route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         172.21.0.1      0.0.0.0         UG    1      0        0 eth1
0.0.0.0         172.21.0.1      0.0.0.0         UG    2      0        0 vth0
0.0.0.0         172.21.0.1      0.0.0.0         UG    3      0        0 vth1
0.0.0.0         172.21.0.1      0.0.0.0         UG    4      0        0 vth2
172.21.0.0      0.0.0.0         255.255.0.0     U     1      0        0 eth1
172.21.0.0      0.0.0.0         255.255.0.0     U     2      0        0 vth0
172.21.0.0      0.0.0.0         255.255.0.0     U     3      0        0 vth1
172.21.0.0      0.0.0.0         255.255.0.0     U     4      0        0 vth2
192.168.31.0    0.0.0.0         255.255.255.0   U     0      0        0 br-lan
198.18.0.0      0.0.0.0         255.255.0.0     U     0      0        0 utun
#ip route list
default via 172.21.0.1 dev eth1 proto static src 172.21.38.244 metric 1 
default via 172.21.0.1 dev vth0 proto static src 172.21.38.252 metric 2 
default via 172.21.0.1 dev vth1 proto static src 172.21.38.253 metric 3 
default via 172.21.0.1 dev vth2 proto static src 172.21.38.254 metric 4 
172.21.0.0/16 dev eth1 proto static scope link metric 1 
172.21.0.0/16 dev vth0 proto static scope link metric 2 
172.21.0.0/16 dev vth1 proto static scope link metric 3 
172.21.0.0/16 dev vth2 proto static scope link metric 4 
192.168.31.0/24 dev br-lan proto kernel scope link src 192.168.31.1 
198.18.0.0/16 dev utun proto kernel scope link src 198.18.0.1 
#ip rule show
0:	from all lookup local
1000:	from all fwmark 0x162 lookup 354
1001:	from all iif eth1 lookup 1
1002:	from all iif vth0 lookup 2
1003:	from all iif vth1 lookup 3
1004:	from all iif vth2 lookup 4
2001:	from all fwmark 0x100/0x3f00 lookup 1
2002:	from all fwmark 0x200/0x3f00 lookup 2
2003:	from all fwmark 0x300/0x3f00 lookup 3
2004:	from all fwmark 0x400/0x3f00 lookup 4
2061:	from all fwmark 0x3d00/0x3f00 blackhole
2062:	from all fwmark 0x3e00/0x3f00 unreachable
3001:	from all fwmark 0x100/0x3f00 unreachable
3002:	from all fwmark 0x200/0x3f00 unreachable
3003:	from all fwmark 0x300/0x3f00 unreachable
3004:	from all fwmark 0x400/0x3f00 unreachable
32766:	from all lookup main
32767:	from all lookup default

#===================== Tun设备状态 =====================#

utun: tun

#===================== 端口占用状态 =====================#

tcp        0      0 0.0.0.0:45033           0.0.0.0:*               LISTEN      15336/clash
tcp        0      0 :::7890                 :::*                    LISTEN      15336/clash
tcp        0      0 :::7891                 :::*                    LISTEN      15336/clash
tcp        0      0 :::7892                 :::*                    LISTEN      15336/clash
tcp        0      0 :::7893                 :::*                    LISTEN      15336/clash
tcp        0      0 :::7895                 :::*                    LISTEN      15336/clash
tcp        0      0 :::9090                 :::*                    LISTEN      15336/clash
udp        0      0 :::48849                :::*                                15336/clash
udp        0      0 :::7891                 :::*                                15336/clash
udp        0      0 :::7892                 :::*                                15336/clash
udp        0      0 :::7893                 :::*                                15336/clash
udp        0      0 :::7895                 :::*                                15336/clash
udp        0      0 :::52300                :::*                                15336/clash
udp        0      0 :::56622                :::*                                15336/clash
udp        0      0 :::7874                 :::*                                15336/clash

### Expected Behavior

异常唤醒消失

### Screenshots

![QQ图片20221008211624](https://user-images.githubusercontent.com/92214385/194710614-c3b0a996-e554-4c98-a4ff-c10ae1f8b252.jpg)
红圈为关闭openclash，正常现象
绿圈为开启openclash，唤醒异常

**Comment by LovelyToaster** [comment]
全部改成直连也不行，只有关掉才行，这是什么玄学啊😭

**Comment by vernesong** [comment]
绕过大陆呢

**Comment by LovelyToaster** [comment]
> 绕过大陆呢

试过了，不行

**Comment by love768952693** [comment]
> 全部改成直连也不行，只有关掉才行，这是什么玄学啊😭

牵扯到底层逻辑了，只有大佬才能解决。。。。

**Comment by LovelyToaster** [comment]
> > 全部改成直连也不行，只有关掉才行，这是什么玄学啊😭
> 
> 牵扯到底层逻辑了，只有大佬才能解决。。。。

已经解决了，自己编译把keepalive时间改长点就行了😁

**Comment by xpn282** [comment]
不会编译，怎么解决这个问题？我的iPhone iPad也是这个现象

**Comment by LovelyToaster** [comment]
> 不会编译，怎么解决这个问题？我的iPhone iPad也是这个现象

最新Meta内核可以在配置文件里手动配置

**Comment by xpn282** [comment]
> > 不会编译，怎么解决这个问题？我的iPhone iPad也是这个现象
> 
> 最新Meta内核可以在配置文件里手动配置

直接在配置文件里添加这项就可以了吗
keep-alive-interval: 1800 

还有就是，修改了这项会有什么弊端吗

**Comment by LovelyToaster** [comment]
> > > 不会编译，怎么解决这个问题？我的iPhone iPad也是这个现象
> > 
> > 最新Meta内核可以在配置文件里手动配置
> 
> 直接在配置文件里添加这项就可以了吗
> keep-alive-interval: 1800 
> 
> 还有就是，修改了这项会有什么弊端吗
> 

是啊，弊端可能有部分连接一直在内核中很久才会被释放

**Comment by xpn282** [comment]
> > > > 不会编译，怎么解决这个问题？我的iPhone iPad也是这个现象
> > > 
> > > 
> > > 最新Meta内核可以在配置文件里手动配置
> > 
> > 
> > 直接在配置文件里添加这项就可以了吗
> > keep-alive-interval: 1800
> > 还有就是，修改了这项会有什么弊端吗
> 
> 是啊，弊端可能有部分连接一直在内核中很久才会被释放

连接很久不释放对iPhone使用上有什么影响吗

**Comment by LovelyToaster** [comment]
> > > > > 不会编译，怎么解决这个问题？我的iPhone iPad也是这个现象
> > > > 
> > > > 
> > > > 最新Meta内核可以在配置文件里手动配置
> > > 
> > > 
> > > 直接在配置文件里添加这项就可以了吗
> > > keep-alive-interval: 1800
> > > 还有就是，修改了这项会有什么弊端吗
> > 
> > 是啊，弊端可能有部分连接一直在内核中很久才会被释放
> 
> 连接很久不释放对iPhone使用上有什么影响吗
> 

应该没有
