### ISSUE TITLE
能支持ssr协议吗？

### ISSUE THREAD

**Issue by rtcheng** [vernesong/OpenClash#273]
我的ssr节点都用不上，未来有计划支持ssr吗？

**Comment by vernesong** [comment]
https://github.com/frainzy1477/luci-app-clash

**Comment by rtcheng** [comment]
额，意思是openclash支持了ssr协议，别人写的就。。。。。。

**Comment by vernesong** [comment]
支持是随时可以支持的，但是要内核支持。
由于clashr闭源，且并非官方开发，我不会去用

**Comment by rtcheng** [comment]
了解，谢谢。
