### ISSUE TITLE
[Feature] 希望fakeip模式可以直接解析大陆IP

### ISSUE THREAD

**Issue by machine-doll** [vernesong/OpenClash#2730]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

在clash中，如果是fakeip模式，clash会直接对任何DNS请求返回一个fakeip，不论是否命中规则  
而运行在路由器上时，由于所有基于域名的连接都会由于解析到了fakeip而经过clash内核，相较于可以绕过大陆IP的redir-host模式，开销大了很多  
希望openclash能够用某种方式，在DNS解析时检查规则，只在命中规则后返回fakeip，其余时候返回真实IP

### Describe the Solution

启动一个DNS服务器作为内网中设备的默认的DNS服务器。在进行DNS查询的时候，匹配clash配置文件中的规则，命中某个走代理的配置组后向clash发送DNS查询，得到fakeip。没有命中的情况下，通过自定义的多个DNS服务器同时发送DNS查询，返回真实IP

### Describe Alternatives

考虑过采用adguardhome等方案，也在网上搜索过别的方案，感觉都不是很好

**Comment by htgg1** [comment]
你现在的解决方案是什么？

**Comment by kingsey** [comment]
> 你现在的解决方案是什么？
新版本的fake-ip支持绕过大陆ip了

**Comment by htgg1** [comment]
> > 你现在的解决方案是什么？
> > 新版本的fake-ip支持绕过大陆ip了

我绕过大陆百度还是fakeip怎么整
