### ISSUE TITLE
[Feature] 能否支持路由器上的某些网卡发出的所有包不走代理

### ISSUE THREAD

**Issue by julee** [vernesong/OpenClash#2734]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

路由器上除了 OpenClash 还运行了一些其他网络服务，这些服务是不需要走代理的。 通过代理规则过滤很容易出现遗漏，造成问题。

例如，在 OpenClash 上搭建了下载服务，不想直接粗暴的根据目的端口（例如 BT 下载的非常规端口）这种模糊的规则来绕过代理，因为这会造成需要正常翻墙访问这些端口的服务出现问题，也不符合在路由器上实现透明代理的初衷。

我目前的方案是，通过 ip 命令给网卡添加了一个新的局域网 ip，例如 10.38.1.3：
`ip addr add 10.38.1.3 dev br-lan label br-lan:cn_service`

然后，将网络服务选择的网卡绑定在 br-lan:cn_service 上面，这样，这些服务的 src ip 就都是上面的这个固定的 10.38.1.3。 
我希望 OpenClash 能够支持配置这个 src ip 的包不走代理。

当前 OpenClash 的访问控制中，有一个 “不走代理的局域网设备 IP” 的选项，可以让局域网某个ip地址的设备的浏览不走代理，但是它对上面的路由器上的地址是无效的， 原因是实现不走代理的局域网设备IP功能的 lan_ac_black_ips 对应的 openclash chain 是在 PREROUTING chain 中的，而上面的 10.38.1.3 是路由器本机的地址，不会走这个规则。

我现在只能手动的用 iptables 添加一条规则临时让 10.38.1.3 被跳过代理：
`iptables -t mangle -I openclash_output --src 10.38.1.3 -j RETURN`

但这个不是 openclash 内建的功能，重启或者修改 openclash 配置可能会造成它失效，又需要手动执行该命令。

### Describe the Solution

希望能在 OpenClash 中提供上面的功能。 谢谢！

**Comment by vernesong** [comment]
自定义规则写一条直连不就行了？

**Comment by julee** [comment]
> 自定义规则写一条直连不就行了？

什么样的规则可以实现这个功能？

**Comment by openips** [comment]
ip direct

**Comment by julee** [comment]
> ip direct

感谢，添加规则 `- SRC-IP-CIDR,10.38.1.3/32,DIRECT` 之后，可以了。

请教为什么 openclash 的设置中， 访问控制中，“不走代理的局域网设备 IP”  为什么不直接追加这个规则来实现，而是通过 iptables 规则？ 

之前以为 clash 规则里面的 ip 匹配只针对目的 ip，没想到还有源 ip 规则。 用 openclash 的访问控制 “不走代理的局域网设备 IP” 不生效，就去研究为啥不生效去了，发现它用 iptables 实现的，也以为我要的功能也只能 iptables 来做

**Comment by fakeboboliu** [comment]
> 请教为什么 openclash 的设置中， 访问控制中，“不走代理的局域网设备 IP” 为什么不直接追加这个规则来实现，而是通过 iptables 规则？

因为用 clash 的规则来做就意味着流量还是要进一圈 clash

**Comment by gitcook** [comment]
https://github.com/vernesong/OpenClash/issues/2506

**Comment by ctacy** [comment]
覆写设置 --> 规则设置 里面新增一行
 - SRC-IP-CIDR,192.168.100.100/32,DIRECT
