### ISSUE TITLE
[Bug] 一个域名解析到多个IP时的DNS问题

### ISSUE THREAD

**Issue by zkdfbb** [vernesong/OpenClash#2737]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.59-beta

### Bug on Environment

Lean

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

有一个域名，如abc.com，解析到了多个A记录，如1.1.1.1，2.2.2.2，3.3.3.3
从Clash日志里可以看到，某一次会有一条[DNS] abc.com -> 1.1.1.1的记录
但是使用ssh登录服务器或者在其他使用IP地址的场景下
比如用ssh 2.2.2.2登录服务器，Clash日志里会有下面一条记录
[TCP] 192.168.1.3:38834 --> abc.com:22
似乎又把IP解析成了域名，导致登录时无法确定具体登录到了哪个服务器
可能是1.1.1.1，也可能是3.3.3.3
在其他使用IP地址时也是一样，比如用1.1.1.1:8080，实际上可能访问的是2.2.2.2:8080

### Describe the Bug

IP到域名解析出错

### OpenClash Log

[DNS] abc.com -> 1.1.1.1
[TCP] 192.168.1.3:38834 --> abc.com:22

### Expected Behavior

使用IP时不要转换为域名

**Comment by vernesong** [comment]
IP连接不会替换

**Comment by zkdfbb** [comment]
@vernesong 但是事实确实是这样的，如果我有一个域名A记录解析到了4个服务器，可能需要先访问一下这个域名，可能会解析到其中任意一个IP，到目前为止是正常的，但是分别使用SSH IP来依次登录这4个服务器，这个时候登录上去的感觉就是随机的，可能用不同的IP登录的确实同一个服务器，在Clash的日志里面也能看到 下面这种日志
[2022-10-15 10:56:06][INFO] [TCP] 192.168.1.3:39560 --> abc.com:22 match DstPort(22) using 🏡 国内直连[DIRECT]
[2022-10-15 10:56:06][INFO] [TCP] 192.168.1.3:56254 --> abc.com:22 match DstPort(22) using 🏡 国内直连[DIRECT]

使用Redir-Host模式时会有这个问题，使用Fake-IP时好像不会，但是Fake-IP会把一些域名解析到192开头的IP，就ping不通了

**Comment by vernesong** [comment]
日志里面有DNS解析记录吗
