### ISSUE TITLE
[Bug] 后台重启完没多久就有一堆外网IP一直上传·在全局设置里只有黑名单白名单，没仅内网？

### ISSUE THREAD

**Issue by Whi1366** [vernesong/OpenClash#2738]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.59_beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-armv7

### To Reproduce

重启动后没多久就出现

### Describe the Bug

外网IP上传流量

### OpenClash Log

调试日志？？是？

### Expected Behavior

不在跑流量就行

**Comment by vernesong** [comment]
全局设置第一个标签里面

**Comment by Passerby1011** [comment]
> 

我也遇到了同样的问题而且确认是openclash导致的

**Comment by Passerby1011** [comment]
[日志.txt](https://github.com/vernesong/OpenClash/files/9845869/default.txt)

**Comment by Passerby1011** [comment]
版本回退后问题就消失了回退至59

**Comment by taoletsgo** [comment]
拒绝openwrt的防火墙wan入站！出站和转发可以接受
