### ISSUE TITLE
[Bug] 无法下载订阅连接 只能手动安装yaml订阅文件

### ISSUE THREAD

**Issue by cjyy46** [vernesong/OpenClash#2739]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.59-beta

### Bug on Environment

Other

### Bug on Platform

Linux-armv8

### To Reproduce

1.设备Nanopi R5S，系统iStoreOS（固件版本OpenWrt 21.02.1 2022061021），机场dler cloud
2.新设备R5S刷机iStoreOS后，安装依赖及最新版Dev和Tun内核后安装OpenClash v0.45.59-beta，最开始是国内直连无法下载dler订阅，然后为了排除网络问题，我在R5S前端连接一台梅林科学上网路由器，并开启全局和大陆白名单模式测试，连接梅林路由器的其它设备上外网正常，OpenClash问题依旧无法下载dler订阅（已关闭所有IPV6功能），只能通过dler订阅地址下载yaml文件后手动上传使用。
3.同时存在的问题还有无法下载GEOIP 数据库和大陆 IP 白名单

### Describe the Bug

OpenClash v0.45.59-beta在iStoreO（固件版本OpenWrt 21.02.1 2022061021）的Nanopi R5S设备中无法下载订阅地址（绝非网络问题），只能手动安装yaml订阅文件。

### OpenClash Log

2022-10-13 16:47:12 GEOIP 数据库下载失败，请检查网络或稍后再试...
2022-10-13 16:47:12 开始下载 GEOIP 数据库...
2022-10-13 16:47:04 未启用第三方规则，更新程序终止！
2022-10-13 16:45:18 大陆 IPv6 白名单下载失败，请检查网络或稍后再试...
2022-10-13 16:45:18 开始下载大陆 IPv6 白名单...
2022-10-13 16:45:15 大陆 IP 白名单下载失败，请检查网络或稍后再试...
2022-10-13 16:45:15 开始下载大陆 IP 白名单...
2022-10-13 16:44:51 GEOIP 数据库下载失败，请检查网络或稍后再试...
2022-10-13 16:44:51 开始下载 GEOIP 数据库...
2022-10-13 16:44:37 未启用第三方规则，更新程序终止！
2022-10-13 16:12:38 错误：【dler】下载失败，请检查网络或稍后再试...
2022-10-13 16:12:29 错误：配置文件【dler】订阅失败，尝试不使用代理下载配置文件...
2022-10-13 16:12:29 开始更新配置文件【dler】...
2022-10-13 16:12:01 重置 OpenClash 防火墙规则...
2022-10-13 15:32:54 错误：【dler】下载失败，请检查网络或稍后再试...
2022-10-13 15:32:45 错误：配置文件【dler】订阅失败，尝试不使用代理下载配置文件...

### Expected Behavior

希望OpenClash的“配置文件订阅”功能可以正常使用，能够下载订阅连接。

### Screenshots

![photo_2022-10-13_15-31-04](https://user-images.githubusercontent.com/25416040/195533968-df8a7f2d-ae22-47bc-ad8a-c4bae1a5b797.jpg)

**Comment by Karmylr** [comment]
![Uploading IMG_20221013_221228_887.jpg…]()

**Comment by Karmylr** [comment]
![IMG_20221013_221228_887](https://user-images.githubusercontent.com/69903376/195620879-307d088b-5c08-45e9-9122-3b65bad2a80f.jpg)

**Comment by cjyy46** [comment]
> ![IMG_20221013_221228_887](https://user-images.githubusercontent.com/69903376/195620879-307d088b-5c08-45e9-9122-3b65bad2a80f.jpg)

请问对于小白用户，不需要太多复杂功能，完美兼容最新版本openclash，哪些第三方的openwrt好用？

**Comment by Karmylr** [comment]
> > ![IMG_20221013_221228_887](https://user-images.githubusercontent.com/69903376/195620879-307d088b-5c08-45e9-9122-3b65bad2a80f.jpg)
> 
> 请问对于小白用户，不需要太多复杂功能，完美兼容最新版本openclash，哪些第三方的openwrt好用？

lean openwrt

**Comment by vernesong** [comment]
检查下curl

**Comment by cjyy46** [comment]
> 检查下curl

不好意思 我是小白 能不能说下通俗易懂的具体操作方法 感谢！

**Comment by cjyy46** [comment]
> 检查下curl

一次订阅更新失败的日志，麻烦帮找下原因及解决方案
Fri Oct 14 21:16:26 2022 daemon.info dnsmasq[19809]: exiting on receipt of SIGTERM
Fri Oct 14 21:16:26 2022 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Fri Oct 14 21:16:26 2022 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: Connected to system UBus
Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: started, version 2.85 cachesize 150
Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: DNS service limited to local subnets
Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: compile time options: IPv6 GNU-getopt no-DBus UBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth cryptohash DNSSEC no-ID loop-detect inotify dumpfile
Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: UBus support enabled: connected to system bus
Fri Oct 14 21:16:29 2022 daemon.info dnsmasq-dhcp[20902]: DHCP, IP range 192.168.100.100 -- 192.168.100.249, lease time 12h
Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: using only locally-known addresses for domain test
Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: using only locally-known addresses for domain onion
Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: using only locally-known addresses for domain localhost
Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: using only locally-known addresses for domain local
Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: using only locally-known addresses for domain invalid
Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: using only locally-known addresses for domain bind
Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: using only locally-known addresses for domain lan
Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: reading /tmp/resolv.conf.d/resolv.conf.auto
Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: using only locally-known addresses for domain test
Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: using only locally-known addresses for domain onion
Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: using only locally-known addresses for domain localhost
Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: using only locally-known addresses for domain local
Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: using only locally-known addresses for domain invalid
Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: using only locally-known addresses for domain bind
Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: using only locally-known addresses for domain lan
Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: using nameserver 202.96.64.68#53
Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: using nameserver 202.96.69.38#53
Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: using nameserver 192.168.2.1#53
Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: read /etc/hosts - 4 addresses
Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: read /tmp/hosts/dhcp.cfg01411c - 3 addresses
Fri Oct 14 21:16:29 2022 daemon.info dnsmasq-dhcp[20902]: read /etc/ethers - 0 addresses
Fri Oct 14 21:16:32 2022 daemon.info dnsmasq[20902]: exiting on receipt of SIGTERM
Fri Oct 14 21:16:32 2022 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Fri Oct 14 21:16:32 2022 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Fri Oct 14 21:16:35 2022 daemon.info dnsmasq[21305]: Connected to system UBus
Fri Oct 14 21:16:35 2022 daemon.info dnsmasq[21305]: started, version 2.85 cachesize 150
Fri Oct 14 21:16:35 2022 daemon.info dnsmasq[21305]: DNS service limited to local subnets
Fri Oct 14 21:16:35 2022 daemon.info dnsmasq[21305]: compile time options: IPv6 GNU-getopt no-DBus UBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth cryptohash DNSSEC no-ID loop-detect inotify dumpfile
Fri Oct 14 21:16:35 2022 daemon.info dnsmasq[21305]: UBus support enabled: connected to system bus
Fri Oct 14 21:16:35 2022 daemon.info dnsmasq-dhcp[21305]: DHCP, IP range 192.168.100.100 -- 192.168.100.249, lease time 12h
Fri Oct 14 21:16:35 2022 daemon.info dnsmasq[21305]: using only locally-known addresses for domain test
Fri Oct 14 21:16:35 2022 daemon.info dnsmasq[21305]: using only locally-known addresses for domain onion
Fri Oct 14 21:16:35 2022 daemon.info dnsmasq[21305]: using only locally-known addresses for domain localhost
Fri Oct 14 21:16:35 2022 daemon.info dnsmasq[21305]: using only locally-known addresses for domain local
Fri Oct 14 21:16:35 2022 daemon.info dnsmasq[21305]: using only locally-known addresses for domain invalid
Fri Oct 14 21:16:35 2022 daemon.info dnsmasq[21305]: using only locally-known addresses for domain bind
Fri Oct 14 21:16:35 2022 daemon.info dnsmasq[21305]: using nameserver 127.0.0.1#7874
Fri Oct 14 21:16:35 2022 daemon.info dnsmasq[21305]: using only locally-known addresses for domain lan
Fri Oct 14 21:16:35 2022 daemon.info dnsmasq[21305]: read /etc/hosts - 4 addresses
Fri Oct 14 21:16:35 2022 daemon.info dnsmasq[21305]: read /tmp/hosts/dhcp.cfg01411c - 3 addresses
Fri Oct 14 21:16:35 2022 daemon.info dnsmasq-dhcp[21305]: read /etc/ethers - 0 addresses
Fri Oct 14 21:16:38 2022 cron.err crond[21537]: crond (busybox 1.33.1) started, log level 5

**Comment by vernesong** [comment]
你用curl随便下载试试，报错就重装下

**Comment by cjyy46** [comment]
> 你用curl随便下载试试，报错就重装下
每次订阅失败，都有这个报错，29147这个位置的数字会总变，请问是这个原因么，如何解决呢？
Thu Oct 27 20:26:54 2022 cron.err crond[29147]: crond (busybox 1.33.1) started, log level 5

**Comment by cjyy46** [comment]
> 你用curl随便下载试试，报错就重装下

每次订阅失败，都有这个报错，29147这个位置的数字会总变，请问是这个原因么，如何解决呢？
Thu Oct 27 20:26:54 2022 cron.err crond[29147]: crond (busybox 1.33.1) started, log level 5

**Comment by Karmylr** [comment]
就不能curl下吗

**Comment by cczhr** [comment]
> > 就不能curl下吗
> 
> curl命令具体是什么？我这水平不是小白，已经是大白了，麻烦说得详细一点，多谢！

执行 curl www.baidu.com
