### ISSUE TITLE
[Bug] 订阅、版本、内核、数据库检查更新均失败报错

### ISSUE THREAD

**Issue by DesmondDu** [vernesong/OpenClash#2742]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.59-β

### Bug on Environment

Lean

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

订阅不能自动更新，手动让订阅更新也报错不能下载
版本、内核、数据库检查更新均失败

### Describe the Bug

涉及到更新的都失败。
调试日志里显示依赖没安装，但实际上都安装的

### OpenClash Log

OpenClash 调试日志

生成时间: 2022-10-13 23:14:49
插件版本: 
隐私提示: 上传此日志前请注意检查、屏蔽公网IP、节点、密码等相关敏感信息

```

#===================== 系统信息 =====================#

主机型号: VMware - Genuine Intel(R) CPU 0000 @ 1.60GHz : 1 Core 8 Thread
固件版本: OpenWrt SNAPSHOT r4491-d5622e353
LuCI版本: 
内核版本: 5.15.36
处理器架构: 

#此项有值时,如不使用IPv6,建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: 

#此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 127.0.0.1#7874

#===================== 依赖检查 =====================#

dnsmasq-full: 未安装
coreutils: 未安装
coreutils-nohup: 未安装
bash: 未安装
curl: 未安装
ca-certificates: 未安装
ipset: 未安装
ip-full: 未安装
libcap: 未安装
libcap-bin: 未安装
ruby: 未安装
ruby-yaml: 未安装
ruby-psych: 未安装
ruby-pstore: 未安装
kmod-tun(TUN模式): 未安装
luci-compat(Luci >= 19.07): 未安装
kmod-inet-diag(PROCESS-NAME): 未安装
unzip: 未安装
iptables-mod-tproxy: 未安装
kmod-ipt-tproxy: 未安装
iptables-mod-extra: 未安装
kmod-ipt-extra: 未安装
kmod-ipt-nat: 未安装

#===================== 内核检查 =====================#

运行状态: 运行中
进程pid: 32614
运行权限: 32614: cap_dac_override,cap_net_bind_service,cap_net_admin,cap_net_raw,cap_sys_ptrace,cap_sys_resource=eip
运行用户: nobody
已选择的架构: linux-amd64

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 2022.07.07-7-g56f0a92
Tun内核文件: 存在
Tun内核运行权限: 正常

Dev内核版本: v1.11.8-3-g4f291fa
Dev内核文件: 存在
Dev内核运行权限: 正常

Meta内核版本: alpha-g9b89ff9
Meta内核文件: 存在
Meta内核运行权限: 正常

#===================== 插件设置 =====================#

当前配置文件: /etc/openclash/config/cdl.yaml
启动配置文件: /etc/openclash/cdl.yaml
运行模式: fake-ip-mix
默认代理模式: rule
UDP流量转发(tproxy): 停用
DNS劫持: 启用
自定义DNS: 停用
IPV6代理: 停用
IPV6-DNS解析: 启用
禁用Dnsmasq缓存: 停用
自定义规则: 停用
仅允许内网: 停用
仅代理命中规则流量: 启用
仅允许常用端口流量: 停用
绕过中国大陆IP: 停用
DNS远程解析: 停用
路由本机代理: 停用

#启动异常时建议关闭此项后重试
混合节点: 停用
保留配置: 停用

#启动异常时建议关闭此项后重试
第三方规则: 停用

### OpenClash Config

_No response_

### Expected Behavior

希望之后能正常更新

### Screenshots

_No response_

**Comment by vernesong** [comment]
检查下curl

**Comment by DesmondDu** [comment]
> 检查下curl

<html>
<body>


curl | 7.85.0-4.1


</body>
</html>

**Comment by cjyy46** [comment]
> > 检查下curl
> 
> curl | 7.85.0-4.1
> 
> 另外其他显示未安装的依赖包安装情况： dnsmasq-full: 2.86-15 coreutils: 9.0-2 coreutils-nohup: 9.1-1 bash: 5.1.16-1 curl: 7.85.0-4.1 ca-certificates: 20211016-1 ipset: 7.15-2 ip-full: 5.15.0-1 libcap: 2.66-1 libcap-bin: 2.66-1 ruby: 3.1.2-2 ruby-yaml: 3.1.2-2 ruby-psych: 3.1.2-1 ruby-pstore: 3.1.2-1 kmod-tun(TUN模式): 5.15.36-1 luci-compat(Luci = git-22.153.11261-95eb5da-1): git-20.356.64372-1259bb1-1 kmod-inet-diag(PROCESS-NAME): 5.15.36-1 unzip: 6.0-8 iptables-mod-tproxy: 1.8.8-1 kmod-ipt-tproxy: 5.15.36-1 iptables-mod-extra: 1.8.8-1 kmod-ipt-extra: 5.15.36-1 kmod-ipt-nat: 5.15.36-1
> 
> 我去系统日志里看到curl有报错，大佬的思路对了！

我也有同样的问题，请问解决了么？我是小白，能说下具体的解决步骤吗，我一步步操作。

**Comment by DesmondDu** [comment]
curl 有两个重要报错：
Error relocating /usr/bin/curl: curl_easy_nextheader: symbol not found 
Error loading shared library libnghttp2.so.14: No such file or directory (needed by /usr/bin/curl)
解决办法：
opkg update; opkg install libmbedtls libcurl4
已解决

**Comment by DesmondDu** [comment]
> > > 检查下curl
> > 
> > 
> > curl | 7.85.0-4.1
> > 另外其他显示未安装的依赖包安装情况： dnsmasq-full: 2.86-15 coreutils: 9.0-2 coreutils-nohup: 9.1-1 bash: 5.1.16-1 curl: 7.85.0-4.1 ca-certificates: 20211016-1 ipset: 7.15-2 ip-full: 5.15.0-1 libcap: 2.66-1 libcap-bin: 2.66-1 ruby: 3.1.2-2 ruby-yaml: 3.1.2-2 ruby-psych: 3.1.2-1 ruby-pstore: 3.1.2-1 kmod-tun(TUN模式): 5.15.36-1 luci-compat(Luci = git-22.153.11261-95eb5da-1): git-20.356.64372-1259bb1-1 kmod-inet-diag(PROCESS-NAME): 5.15.36-1 unzip: 6.0-8 iptables-mod-tproxy: 1.8.8-1 kmod-ipt-tproxy: 5.15.36-1 iptables-mod-extra: 1.8.8-1 kmod-ipt-extra: 5.15.36-1 kmod-ipt-nat: 5.15.36-1
> > 我去系统日志里看到curl有报错，大佬的思路对了！
> 
> 我也有同样的问题，请问解决了么？我是小白，能说下具体的解决步骤吗，我一步步操作。

看上一条评论

**Comment by cjyy46** [comment]
> > > > 检查下curl
> > > 
> > > 
> > > curl | 7.85.0-4.1
> > > 另外其他显示未安装的依赖包安装情况： dnsmasq-full: 2.86-15 coreutils: 9.0-2 coreutils-nohup: 9.1-1 bash: 5.1.16-1 curl: 7.85.0-4.1 ca-certificates: 20211016-1 ipset: 7.15-2 ip-full: 5.15.0-1 libcap: 2.66-1 libcap-bin: 2.66-1 ruby: 3.1.2-2 ruby-yaml: 3.1.2-2 ruby-psych: 3.1.2-1 ruby-pstore: 3.1.2-1 kmod-tun(TUN模式): 5.15.36-1 luci-compat(Luci = git-22.153.11261-95eb5da-1): git-20.356.64372-1259bb1-1 kmod-inet-diag(PROCESS-NAME): 5.15.36-1 unzip: 6.0-8 iptables-mod-tproxy: 1.8.8-1 kmod-ipt-tproxy: 5.15.36-1 iptables-mod-extra: 1.8.8-1 kmod-ipt-extra: 5.15.36-1 kmod-ipt-nat: 5.15.36-1
> > > 我去系统日志里看到curl有报错，大佬的思路对了！
> > 
> > 
> > 我也有同样的问题，请问解决了么？我是小白，能说下具体的解决步骤吗，我一步步操作。
> 
> 看上一条评论

不好意思 没明白 方便留tg号交流下吗

**Comment by DesmondDu** [comment]
> 

安装libmbedtls和libcurl4。openwrt安装软件包会的吧？后台opkg update; opkg install libmbedtls libcurl4

**Comment by DesmondDu** [comment]
> > > > > 检查下curl
> > > > 
> > > > 
> > > > curl | 7.85.0-4.1
> > > > 另外其他显示未安装的依赖包安装情况： dnsmasq-full: 2.86-15 coreutils: 9.0-2 coreutils-nohup: 9.1-1 bash: 5.1.16-1 curl: 7.85.0-4.1 ca-certificates: 20211016-1 ipset: 7.15-2 ip-full: 5.15.0-1 libcap: 2.66-1 libcap-bin: 2.66-1 ruby: 3.1.2-2 ruby-yaml: 3.1.2-2 ruby-psych: 3.1.2-1 ruby-pstore: 3.1.2-1 kmod-tun(TUN模式): 5.15.36-1 luci-compat(Luci = git-22.153.11261-95eb5da-1): git-20.356.64372-1259bb1-1 kmod-inet-diag(PROCESS-NAME): 5.15.36-1 unzip: 6.0-8 iptables-mod-tproxy: 1.8.8-1 kmod-ipt-tproxy: 5.15.36-1 iptables-mod-extra: 1.8.8-1 kmod-ipt-extra: 5.15.36-1 kmod-ipt-nat: 5.15.36-1
> > > > 我去系统日志里看到curl有报错，大佬的思路对了！
> > > 
> > > 
> > > 我也有同样的问题，请问解决了么？我是小白，能说下具体的解决步骤吗，我一步步操作。
> > 
> > 
> > 看上一条评论
> 
> 不好意思 没明白 方便留tg号交流下吗

安装libmbedtls和libcurl4。openwrt安装软件包会的吧？后台opkg update; opkg install libmbedtls libcurl4

**Comment by cjyy46** [comment]
> > > > > > 检查下curl
> > > > > 
> > > > > 
> > > > > curl | 7.85.0-4.1
> > > > > 另外其他显示未安装的依赖包安装情况： dnsmasq-full: 2.86-15 coreutils: 9.0-2 coreutils-nohup: 9.1-1 bash: 5.1.16-1 curl: 7.85.0-4.1 ca-certificates: 20211016-1 ipset: 7.15-2 ip-full: 5.15.0-1 libcap: 2.66-1 libcap-bin: 2.66-1 ruby: 3.1.2-2 ruby-yaml: 3.1.2-2 ruby-psych: 3.1.2-1 ruby-pstore: 3.1.2-1 kmod-tun(TUN模式): 5.15.36-1 luci-compat(Luci = git-22.153.11261-95eb5da-1): git-20.356.64372-1259bb1-1 kmod-inet-diag(PROCESS-NAME): 5.15.36-1 unzip: 6.0-8 iptables-mod-tproxy: 1.8.8-1 kmod-ipt-tproxy: 5.15.36-1 iptables-mod-extra: 1.8.8-1 kmod-ipt-extra: 5.15.36-1 kmod-ipt-nat: 5.15.36-1
> > > > > 我去系统日志里看到curl有报错，大佬的思路对了！
> > > > 
> > > > 
> > > > 我也有同样的问题，请问解决了么？我是小白，能说下具体的解决步骤吗，我一步步操作。
> > > 
> > > 
> > > 看上一条评论
> > 
> > 
> > 不好意思 没明白 方便留tg号交流下吗
> 
> 安装libmbedtls和libcurl4。openwrt安装软件包会的吧？后台opkg update; opkg install libmbedtls libcurl4

按你的方法试了，还是无法更新订阅，请问你说的curl两条报错是通过什么命令查询的？

**Comment by DesmondDu** [comment]
> > > > > > > 检查下curl
> > > > > > 
> > > > > > 
> > > > > > curl | 7.85.0-4.1
> > > > > > 另外其他显示未安装的依赖包安装情况： dnsmasq-full: 2.86-15 coreutils: 9.0-2 coreutils-nohup: 9.1-1 bash: 5.1.16-1 curl: 7.85.0-4.1 ca-certificates: 20211016-1 ipset: 7.15-2 ip-full: 5.15.0-1 libcap: 2.66-1 libcap-bin: 2.66-1 ruby: 3.1.2-2 ruby-yaml: 3.1.2-2 ruby-psych: 3.1.2-1 ruby-pstore: 3.1.2-1 kmod-tun(TUN模式): 5.15.36-1 luci-compat(Luci = git-22.153.11261-95eb5da-1): git-20.356.64372-1259bb1-1 kmod-inet-diag(PROCESS-NAME): 5.15.36-1 unzip: 6.0-8 iptables-mod-tproxy: 1.8.8-1 kmod-ipt-tproxy: 5.15.36-1 iptables-mod-extra: 1.8.8-1 kmod-ipt-extra: 5.15.36-1 kmod-ipt-nat: 5.15.36-1
> > > > > > 我去系统日志里看到curl有报错，大佬的思路对了！
> > > > > 
> > > > > 
> > > > > 我也有同样的问题，请问解决了么？我是小白，能说下具体的解决步骤吗，我一步步操作。
> > > > 
> > > > 
> > > > 看上一条评论
> > > 
> > > 
> > > 不好意思 没明白 方便留tg号交流下吗
> > 
> > 
> > 安装libmbedtls和libcurl4。openwrt安装软件包会的吧？后台opkg update; opkg install libmbedtls libcurl4
> 
> 按你的方法试了，还是无法更新订阅，请问你说的curl两条报错是通过什么命令查询的？

Openwrt的系统日志

**Comment by cjyy46** [comment]
> > > > > > > > 检查下curl
> > > > > > > 
> > > > > > > 
> > > > > > > curl | 7.85.0-4.1
> > > > > > > 另外其他显示未安装的依赖包安装情况： dnsmasq-full: 2.86-15 coreutils: 9.0-2 coreutils-nohup: 9.1-1 bash: 5.1.16-1 curl: 7.85.0-4.1 ca-certificates: 20211016-1 ipset: 7.15-2 ip-full: 5.15.0-1 libcap: 2.66-1 libcap-bin: 2.66-1 ruby: 3.1.2-2 ruby-yaml: 3.1.2-2 ruby-psych: 3.1.2-1 ruby-pstore: 3.1.2-1 kmod-tun(TUN模式): 5.15.36-1 luci-compat(Luci = git-22.153.11261-95eb5da-1): git-20.356.64372-1259bb1-1 kmod-inet-diag(PROCESS-NAME): 5.15.36-1 unzip: 6.0-8 iptables-mod-tproxy: 1.8.8-1 kmod-ipt-tproxy: 5.15.36-1 iptables-mod-extra: 1.8.8-1 kmod-ipt-extra: 5.15.36-1 kmod-ipt-nat: 5.15.36-1
> > > > > > > 我去系统日志里看到curl有报错，大佬的思路对了！
> > > > > > 
> > > > > > 
> > > > > > 我也有同样的问题，请问解决了么？我是小白，能说下具体的解决步骤吗，我一步步操作。
> > > > > 
> > > > > 
> > > > > 看上一条评论
> > > > 
> > > > 
> > > > 不好意思 没明白 方便留tg号交流下吗
> > > 
> > > 
> > > 安装libmbedtls和libcurl4。openwrt安装软件包会的吧？后台opkg update; opkg install libmbedtls libcurl4
> > 
> > 
> > 按你的方法试了，还是无法更新订阅，请问你说的curl两条报错是通过什么命令查询的？
> 
> Openwrt的系统日志

一次订阅更新失败的日志，麻烦帮找下原因及解决方案
Fri Oct 14 21:16:26 2022 daemon.info dnsmasq[19809]: exiting on receipt of SIGTERM
Fri Oct 14 21:16:26 2022 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Fri Oct 14 21:16:26 2022 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: Connected to system UBus
Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: started, version 2.85 cachesize 150
Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: DNS service limited to local subnets
Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: compile time options: IPv6 GNU-getopt no-DBus UBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth cryptohash DNSSEC no-ID loop-detect inotify dumpfile
Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: UBus support enabled: connected to system bus
Fri Oct 14 21:16:29 2022 daemon.info dnsmasq-dhcp[20902]: DHCP, IP range 192.168.100.100 -- 192.168.100.249, lease time 12h
Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: using only locally-known addresses for domain test
Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: using only locally-known addresses for domain onion
Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: using only locally-known addresses for domain localhost
Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: using only locally-known addresses for domain local
Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: using only locally-known addresses for domain invalid
Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: using only locally-known addresses for domain bind
Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: using only locally-known addresses for domain lan
Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: reading /tmp/resolv.conf.d/resolv.conf.auto
Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: using only locally-known addresses for domain test
Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: using only locally-known addresses for domain onion
Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: using only locally-known addresses for domain localhost
Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: using only locally-known addresses for domain local
Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: using only locally-known addresses for domain invalid
Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: using only locally-known addresses for domain bind
Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: using only locally-known addresses for domain lan
Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: using nameserver 202.96.64.68#53
Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: using nameserver 202.96.69.38#53
Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: using nameserver 192.168.2.1#53
Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: read /etc/hosts - 4 addresses
Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: read /tmp/hosts/dhcp.cfg01411c - 3 addresses
Fri Oct 14 21:16:29 2022 daemon.info dnsmasq-dhcp[20902]: read /etc/ethers - 0 addresses
Fri Oct 14 21:16:32 2022 daemon.info dnsmasq[20902]: exiting on receipt of SIGTERM
Fri Oct 14 21:16:32 2022 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Fri Oct 14 21:16:32 2022 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Fri Oct 14 21:16:35 2022 daemon.info dnsmasq[21305]: Connected to system UBus
Fri Oct 14 21:16:35 2022 daemon.info dnsmasq[21305]: started, version 2.85 cachesize 150
Fri Oct 14 21:16:35 2022 daemon.info dnsmasq[21305]: DNS service limited to local subnets
Fri Oct 14 21:16:35 2022 daemon.info dnsmasq[21305]: compile time options: IPv6 GNU-getopt no-DBus UBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth cryptohash DNSSEC no-ID loop-detect inotify dumpfile
Fri Oct 14 21:16:35 2022 daemon.info dnsmasq[21305]: UBus support enabled: connected to system bus
Fri Oct 14 21:16:35 2022 daemon.info dnsmasq-dhcp[21305]: DHCP, IP range 192.168.100.100 -- 192.168.100.249, lease time 12h
Fri Oct 14 21:16:35 2022 daemon.info dnsmasq[21305]: using only locally-known addresses for domain test
Fri Oct 14 21:16:35 2022 daemon.info dnsmasq[21305]: using only locally-known addresses for domain onion
Fri Oct 14 21:16:35 2022 daemon.info dnsmasq[21305]: using only locally-known addresses for domain localhost
Fri Oct 14 21:16:35 2022 daemon.info dnsmasq[21305]: using only locally-known addresses for domain local
Fri Oct 14 21:16:35 2022 daemon.info dnsmasq[21305]: using only locally-known addresses for domain invalid
Fri Oct 14 21:16:35 2022 daemon.info dnsmasq[21305]: using only locally-known addresses for domain bind
Fri Oct 14 21:16:35 2022 daemon.info dnsmasq[21305]: using nameserver 127.0.0.1#7874
Fri Oct 14 21:16:35 2022 daemon.info dnsmasq[21305]: using only locally-known addresses for domain lan
Fri Oct 14 21:16:35 2022 daemon.info dnsmasq[21305]: read /etc/hosts - 4 addresses
Fri Oct 14 21:16:35 2022 daemon.info dnsmasq[21305]: read /tmp/hosts/dhcp.cfg01411c - 3 addresses
Fri Oct 14 21:16:35 2022 daemon.info dnsmasq-dhcp[21305]: read /etc/ethers - 0 addresses
Fri Oct 14 21:16:38 2022 cron.err crond[21537]: crond (busybox 1.33.1) started, log level 5

**Comment by DesmondDu** [comment]
> > > > > > > > > 检查下curl
> > > > > > > > 
> > > > > > > > 
> > > > > > > > curl | 7.85.0-4.1
> > > > > > > > 另外其他显示未安装的依赖包安装情况： dnsmasq-full: 2.86-15 coreutils: 9.0-2 coreutils-nohup: 9.1-1 bash: 5.1.16-1 curl: 7.85.0-4.1 ca-certificates: 20211016-1 ipset: 7.15-2 ip-full: 5.15.0-1 libcap: 2.66-1 libcap-bin: 2.66-1 ruby: 3.1.2-2 ruby-yaml: 3.1.2-2 ruby-psych: 3.1.2-1 ruby-pstore: 3.1.2-1 kmod-tun(TUN模式): 5.15.36-1 luci-compat(Luci = git-22.153.11261-95eb5da-1): git-20.356.64372-1259bb1-1 kmod-inet-diag(PROCESS-NAME): 5.15.36-1 unzip: 6.0-8 iptables-mod-tproxy: 1.8.8-1 kmod-ipt-tproxy: 5.15.36-1 iptables-mod-extra: 1.8.8-1 kmod-ipt-extra: 5.15.36-1 kmod-ipt-nat: 5.15.36-1
> > > > > > > > 我去系统日志里看到curl有报错，大佬的思路对了！
> > > > > > > 
> > > > > > > 
> > > > > > > 我也有同样的问题，请问解决了么？我是小白，能说下具体的解决步骤吗，我一步步操作。
> > > > > > 
> > > > > > 
> > > > > > 看上一条评论
> > > > > 
> > > > > 
> > > > > 不好意思 没明白 方便留tg号交流下吗
> > > > 
> > > > 
> > > > 安装libmbedtls和libcurl4。openwrt安装软件包会的吧？后台opkg update; opkg install libmbedtls libcurl4
> > > 
> > > 
> > > 按你的方法试了，还是无法更新订阅，请问你说的curl两条报错是通过什么命令查询的？
> > 
> > 
> > Openwrt的系统日志
> 
> 一次订阅更新失败的日志，麻烦帮找下原因及解决方案 Fri Oct 14 21:16:26 2022 daemon.info dnsmasq[19809]: exiting on receipt of SIGTERM Fri Oct 14 21:16:26 2022 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses! Fri Oct 14 21:16:26 2022 user.notice dnsmasq: Allowing 127.0.0.0/8 responses Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: Connected to system UBus Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: started, version 2.85 cachesize 150 Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: DNS service limited to local subnets Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: compile time options: IPv6 GNU-getopt no-DBus UBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth cryptohash DNSSEC no-ID loop-detect inotify dumpfile Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: UBus support enabled: connected to system bus Fri Oct 14 21:16:29 2022 daemon.info dnsmasq-dhcp[20902]: DHCP, IP range 192.168.100.100 -- 192.168.100.249, lease time 12h Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: using only locally-known addresses for domain test Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: using only locally-known addresses for domain onion Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: using only locally-known addresses for domain localhost Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: using only locally-known addresses for domain local Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: using only locally-known addresses for domain invalid Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: using only locally-known addresses for domain bind Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: using only locally-known addresses for domain lan Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: reading /tmp/resolv.conf.d/resolv.conf.auto Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: using only locally-known addresses for domain test Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: using only locally-known addresses for domain onion Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: using only locally-known addresses for domain localhost Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: using only locally-known addresses for domain local Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: using only locally-known addresses for domain invalid Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: using only locally-known addresses for domain bind Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: using only locally-known addresses for domain lan Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: using nameserver 202.96.64.68#53 Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: using nameserver 202.96.69.38#53 Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: using nameserver 192.168.2.1#53 Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: read /etc/hosts - 4 addresses Fri Oct 14 21:16:29 2022 daemon.info dnsmasq[20902]: read /tmp/hosts/dhcp.cfg01411c - 3 addresses Fri Oct 14 21:16:29 2022 daemon.info dnsmasq-dhcp[20902]: read /etc/ethers - 0 addresses Fri Oct 14 21:16:32 2022 daemon.info dnsmasq[20902]: exiting on receipt of SIGTERM Fri Oct 14 21:16:32 2022 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses! Fri Oct 14 21:16:32 2022 user.notice dnsmasq: Allowing 127.0.0.0/8 responses Fri Oct 14 21:16:35 2022 daemon.info dnsmasq[21305]: Connected to system UBus Fri Oct 14 21:16:35 2022 daemon.info dnsmasq[21305]: started, version 2.85 cachesize 150 Fri Oct 14 21:16:35 2022 daemon.info dnsmasq[21305]: DNS service limited to local subnets Fri Oct 14 21:16:35 2022 daemon.info dnsmasq[21305]: compile time options: IPv6 GNU-getopt no-DBus UBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth cryptohash DNSSEC no-ID loop-detect inotify dumpfile Fri Oct 14 21:16:35 2022 daemon.info dnsmasq[21305]: UBus support enabled: connected to system bus Fri Oct 14 21:16:35 2022 daemon.info dnsmasq-dhcp[21305]: DHCP, IP range 192.168.100.100 -- 192.168.100.249, lease time 12h Fri Oct 14 21:16:35 2022 daemon.info dnsmasq[21305]: using only locally-known addresses for domain test Fri Oct 14 21:16:35 2022 daemon.info dnsmasq[21305]: using only locally-known addresses for domain onion Fri Oct 14 21:16:35 2022 daemon.info dnsmasq[21305]: using only locally-known addresses for domain localhost Fri Oct 14 21:16:35 2022 daemon.info dnsmasq[21305]: using only locally-known addresses for domain local Fri Oct 14 21:16:35 2022 daemon.info dnsmasq[21305]: using only locally-known addresses for domain invalid Fri Oct 14 21:16:35 2022 daemon.info dnsmasq[21305]: using only locally-known addresses for domain bind Fri Oct 14 21:16:35 2022 daemon.info dnsmasq[21305]: using nameserver 127.0.0.1#7874 Fri Oct 14 21:16:35 2022 daemon.info dnsmasq[21305]: using only locally-known addresses for domain lan Fri Oct 14 21:16:35 2022 daemon.info dnsmasq[21305]: read /etc/hosts - 4 addresses Fri Oct 14 21:16:35 2022 daemon.info dnsmasq[21305]: read /tmp/hosts/dhcp.cfg01411c - 3 addresses Fri Oct 14 21:16:35 2022 daemon.info dnsmasq-dhcp[21305]: read /etc/ethers - 0 addresses Fri Oct 14 21:16:38 2022 cron.err crond[21537]: crond (busybox 1.33.1) started, log level 5

兄弟你总得看的是相关的报错日志吧，这一坨无关日志哎。还有找到报错内容了自己google一下就能找到方案，让别人保姆级服务这要求太过了哈
