### ISSUE TITLE
[Feature] Clash可否支持下配置文件加密，在本地磁盘加密保存配置文件

### ISSUE THREAD

**Issue by lingfeng0303** [vernesong/OpenClash#2745]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

clash目前配置文件都是明文保存，配置文件里的vps的相关信息，很容易被暴露，比如socks的用户名和密码
存在比较大的安全隐患
1、其他程序读取这个配置文件，并上传到自身的服务器，导致配置文件暴露
2、在一些公有电脑上使用clash，也会导致配置文件暴露

### Describe the Solution

可否支持下RSA加解密，clash客户端由用户配置公钥，配置文件由用户自己用私钥加密
当然可以明文的和非明文的配置文件都支持，这样用户可以选择，安全需求强的用户可以自己选择加密的方式
存储配置文件

**Comment by zheshifandian** [comment]
表示没出现这个问题，通45.64版本

**Comment by cxzlw** [comment]
> * [x]  Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
> *

或许openclash这种透明代理一般不会在公有电脑使用？而且安装oc的设备或许都不会装一些不怀好意的程序？
或许这是Clash应包含的特性，你可以考虑去Clash那边提issue？
