### ISSUE TITLE
外部控制切换控制面板显示解压失败[Bug] 

### ISSUE THREAD

**Issue by fxljay** [vernesong/OpenClash#2748]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.64-beta

### Bug on Environment

Lean

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

重装了多次依然不行

### Describe the Bug

![image](https://user-images.githubusercontent.com/35395762/196013093-2dad5499-e01b-4378-ba01-25cc676fdd1a.png)

### OpenClash Log

调试日志一切正常

### Expected Behavior

请大佬指点哪里出现的问题

**Comment by zheshifandian** [comment]
表示没出现这个问题，同45.64版本

**Comment by fxljay** [comment]
大概知道怎么回事了，应该是其他的什么软件不兼容，重新编译只选择openclash后，问题解决

**Comment by fxljay** [comment]
再次复见，并发现了问题原因，最新的Dev版本，无法切换外部控制面板
