### ISSUE TITLE
貌似自定义规则集中无法覆盖屏蔽原配置文件中已经走代理的网站……

### ISSUE THREAD

**Issue by mqpbjnsdjvbwl** [vernesong/OpenClash#2749]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.59-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-armv7

### To Reproduce

大概是这样，比如说最近**身体有点虚**，想**屏蔽掉 pornhub.com 几天**，但是添加自定义规则集后**无法覆盖原设置**，电脑**仍然可以访问 pornhub.com** 

### Describe the Bug

**已测试：如果在自定义规则集中屏蔽墙内网址，则规则集生效，但是对于墙外网址无效**

### OpenClash Log

无特定日志，使用正常

### OpenClash Config

```shell
1
```

### Expected Behavior

让我屏蔽 pornhub.com 几天

### Screenshots

1

**Comment by vernesong** [comment]
填优先匹配的位置
