### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by shum-elli** [vernesong/OpenClash#2752]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.59-beta

### Bug on Environment

Lean

### Bug on Platform

Linux-armv7

### To Reproduce

设置自定义上游dns服务器无效，包括使用选项追加上游dns，追加默认dns等选项，已经将域名放入直连白名单，校园网环境，学校的oa系统位于内网服务器上，内网有一台负责解析的dns服务器，该dns服务器ip为10.1.x.xxx；

### Describe the Bug

设置放入上游dns服务器也无效 ，貌似在win下的cfw试过好像也不行，但是我觉得dnsmasq应该不会出现这样的问题，关闭clash可以解析到内网上的网页，内网上的许多网页都有域名，所以需要dns服务器来解析，dns服务器有问题

### OpenClash Log

debug log无法看到相关信息

### OpenClash Config

```shell
1
```

### Expected Behavior

内网dns设置生效 或者给一个可行的解决方案，也试过高级dns设置 

### Screenshots

1

**Comment by A-Cepheus** [comment]
尝试不设置任何其他dns服务器

**Comment by vernesong** [comment]
手动查DNS是什么结果

**Comment by shum-elli** [comment]
抱歉了 找到问题了 是openwrt自带的dnsmasq默认安全配置不能解析内网域名  踩坑了  研究了很久
