### ISSUE TITLE
[Bug] 无法生成调试日志

### ISSUE THREAD

**Issue by kyo66666** [vernesong/OpenClash#2754]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.65-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

官方原版OpenWrt 22.03.2，点击调试日志->生成日志，然后提示“发生了一些错误！”

### Describe the Bug

其他功能正常，不知道什么原因不能生成调试日志

### OpenClash Log

无

### Expected Behavior

无

**Comment by vernesong** [comment]
/usr/share/openclash/openclash_debug.sh

单独运行试试

**Comment by kyo66666** [comment]
> /usr/share/openclash/openclash_debug.sh
> 
> 单独运行试试

单独运行脚本以及界面点击生成日志，/tmp 目录下都能正常生成日志文件 openclash_debug.log，但界面始终显示“发生了一些错误！”
