### ISSUE TITLE
ss协议下无法打开Youtube/google

### ISSUE THREAD

**Issue by b141r** [vernesong/OpenClash#276]
Hi!

昨天更新了0.37.1-beta内核之后ss会出现一些问题

自己做了一个.yaml测试了一下： 
- 节点是来自A机场的vmes & ss, B的vmess, C的ss.
- 规则组和DNS用的是lhie1的rule.yaml+ Head_tap.yaml
测试结果是 所有vmess协议都可以正常上Google/youtube， ss的不可以

在访问youtube的时候Chrome的console 会显示
net::ERR_CERT_COMMON_NAME_INVALID 
net::ERR_TIMED_OUT
对应的域名是googlevideo.com 

同样的文件在ClashX上面测试没有问题。
所以我怀疑是不是新的内核对ss有影响？

Thanks

**Comment by vernesong** [comment]
什么模式

**Comment by b141r** [comment]
页面操作模式：Fake-IP模式
运行模式： Fake-IP(增强）模式
代理UDP流量：UDP启用
代理模式： Rule

**Comment by b141r** [comment]
> 什么模式

Fake-IP 模式
Fake-IP增强
UDP启用
Rule

**Comment by xpn282** [comment]
> 什么模式

很喜欢本软件，请问Openclash的官方电报群吗

**Comment by vernesong** [comment]
> > 什么模式
> 
> 
> 
> 很喜欢本软件，请问Openclash的官方电报群吗
> 
> 
> 
> 我还遇到一个问题，最新版0.37.1-beta的udp转发有问题，相同的设置相同的节点之前的版本，Switch游戏机的nat可以显示A级别，现在0.37.1版本只能C或D，和没开udp转发一样。。好像upd转发失效

udp的设置我没有变动过，你可以试试之前安装的内核

**Comment by vernesong** [comment]
> > 什么模式
> 
> 
> 
> Fake-IP 模式
> 
> Fake-IP增强
> 
> UDP启用
> 
> Rule

感觉是内核的锅，最近频繁在修dns有关的bug

**Comment by vernesong** [comment]
访问异常时使用以下命令分别测试域名，把整个结果发上来
'curl -v'

**Comment by sunxun47** [comment]
更改规则重新连接clash 启动的时候偶尔会这样，证书错误。
比如这个是刚刚更改了规则点启动的时候访问youtube ，证书不对。
![image](https://user-images.githubusercontent.com/8243923/77749111-6f9bb900-705c-11ea-83f8-e2d5581c0647.png)

openclash 连接全部显示正常的时候访问youtube 正常。

![image](https://user-images.githubusercontent.com/8243923/77749319-cdc89c00-705c-11ea-9e38-108c990c0f68.png)

下面只是猜测：
clash 重新启动，没完全连上，输入地址，连接了本地dns 缓存中的fake ip，但是访问这个fake ip 以后，clash 重新连接，通过fake ip 反查域名的时候clash 中fake ip 域名对应的关系变了，实际访问的是另一个域名，在浏览器中，地址栏的地址或实际获取的地址不一致，证书错误。
还有一种可能就是访问的时候clash 没启动，本地缓存中的fake ip 恰好对应某个域名，而这个域名和浏览器中输入的地址不一样，证书错误。

**Comment by b141r** [comment]
> 访问异常时使用以下命令分别测试域名，把整个结果发上来
> `curl -v`


### user-end

**type: ss
cipher: xchacha20-ietf-poly1305**

```
curl -v www.google.com
*   Trying 174.36.196.242...
* TCP_NODELAY set
* Connected to www.google.com (174.36.196.242) port 80 (#0)
> GET / HTTP/1.1
> Host: www.google.com
> User-Agent: curl/7.64.1
> Accept: */*
>
* Empty reply from server
* Connection #0 to host www.google.com left intact
curl: (52) Empty reply from server
* Closing connection 0
```

**type: ss
cipher: rc4-md5**

```
curl -v www.google.com
*   Trying 69.63.186.31...
* TCP_NODELAY set
* Connected to www.google.com (69.63.186.31) port 80 (#0)
> GET / HTTP/1.1
> Host: www.google.com
> User-Agent: curl/7.64.1
> Accept: */*
>
* Empty reply from server
* Connection #0 to host www.google.com left intact
curl: (52) Empty reply from server
* Closing connection 0
```

**type: vmess**

```
curl -v www.google.com
*   Trying 31.13.80.1...
* TCP_NODELAY set
* Connected to www.google.com (31.13.80.1) port 80 (#0)
> GET / HTTP/1.1
> Host: www.google.com
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Sun, 29 Mar 2020 14:50:06 GMT
< Expires: -1
......
......
......
* Closing connection 0
```



###host-end 

**type: ss
cipher:xchacha20-ietf-poly1305**

```
curl -v www.google.com
* Failed to connect to www.google.com port 80: Operation timed out
curl: (7) Failed to connect to www.google.com port 80: Operation timed out
```

**type: ss
cipher: rc4-md5**

```
curl -v www.google.com
* Failed to connect to www.google.com port 80: Operation timed out
curl: (7) Failed to connect to www.google.com port 80: Operation timed out
```

**type: vmess**

```
curl -v www.google.com
* Failed to connect to www.google.com port 80: Operation timed out
curl: (7) Failed to connect to www.google.com port 80: Operation timed out
```

**Comment by vernesong** [comment]
> > 访问异常时使用以下命令分别测试域名，把整个结果发上来
> > `curl -v`
> 
> ### user-end
> **type: ss cipher: xchacha20-ietf-poly1305**
> 
> ```
> curl -v www.google.com
> *   Trying 174.36.196.242...
> * TCP_NODELAY set
> * Connected to www.google.com (174.36.196.242) port 80 (#0)
> > GET / HTTP/1.1
> > Host: www.google.com
> > User-Agent: curl/7.64.1
> > Accept: */*
> >
> * Empty reply from server
> * Connection #0 to host www.google.com left intact
> curl: (52) Empty reply from server
> * Closing connection 0
> ```
> 
> **type: ss cipher: rc4-md5**
> 
> ```
> curl -v www.google.com
> *   Trying 69.63.186.31...
> * TCP_NODELAY set
> * Connected to www.google.com (69.63.186.31) port 80 (#0)
> > GET / HTTP/1.1
> > Host: www.google.com
> > User-Agent: curl/7.64.1
> > Accept: */*
> >
> * Empty reply from server
> * Connection #0 to host www.google.com left intact
> curl: (52) Empty reply from server
> * Closing connection 0
> ```
> 
> **type: vmess**
> 
> ```
> curl -v www.google.com
> *   Trying 31.13.80.1...
> * TCP_NODELAY set
> * Connected to www.google.com (31.13.80.1) port 80 (#0)
> > GET / HTTP/1.1
> > Host: www.google.com
> > User-Agent: curl/7.64.1
> > Accept: */*
> >
> < HTTP/1.1 200 OK
> < Date: Sun, 29 Mar 2020 14:50:06 GMT
> < Expires: -1
> ......
> ......
> ......
> * Closing connection 0
> ```
> 
> ### host-end
> **type: ss cipher:xchacha20-ietf-poly1305**
> 
> ```
> curl -v www.google.com
> * Failed to connect to www.google.com port 80: Operation timed out
> curl: (7) Failed to connect to www.google.com port 80: Operation timed out
> ```
> 
> **type: ss cipher: rc4-md5**
> 
> ```
> curl -v www.google.com
> * Failed to connect to www.google.com port 80: Operation timed out
> curl: (7) Failed to connect to www.google.com port 80: Operation timed out
> ```
> 
> **type: vmess**
> 
> ```
> curl -v www.google.com
> * Failed to connect to www.google.com port 80: Operation timed out
> curl: (7) Failed to connect to www.google.com port 80: Operation timed out
> ```

确定是fake-ip？建议你检查本地DNS设置，clash没有劫持到。
正常情况如下（注意观察返回的DNS）：
![image](https://user-images.githubusercontent.com/42875168/77867393-aa267100-7269-11ea-811e-8c3bdf1f889f.png)

**Comment by touchsky-real** [comment]
我也是这个问题，youtube和google打不开，又提示说facebook的证书错误啥的

**Comment by Somnusochi** [comment]
同样遇到了这个问题，希望有人能帮忙看看
