### ISSUE TITLE
vmess ws+tls 在openclash的使用问题咨询

### ISSUE THREAD

**Issue by zhyhub123** [vernesong/OpenClash#2769]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

最近一段时间，在openclash不能使用vmess+ws+tls的v2ray ，配置格式如下。这个格式在clash种可以正常使用，但在openclash，一直不能识别。请指教

  - {name: xx, server: IP, port: xxx, type: vmess, uuid: xxx, alterId: 0, cipher: auto, tls: true, network: ws, ws-opts: {path: /xxx, headers: {Host: xxx}}}

### Describe the Solution

另外，还试了下述几种格式，一样不能使用。询问正确的配置

- { name: xx, type: vmess, server: IP, port: xx, uuid:xxx, alterId: 0, cipher: auto, network: ws, ws-path: /xxx, ws-headers: { Host: xxx } }

  - { name: xx, type: vmess, server: IP, port: xxx, uuid: xxx, alterId: 0, cipher: auto, network: ws, ws-path: /xxx, tls: true }

**Comment by vernesong** [comment]
```
- name: "vmess"
    type: vmess
    server: server
    port: 443
    uuid: uuid
    alterId: 32
    cipher: auto
    # udp: true
    # tls: true
    # skip-cert-verify: true
    # servername: example.com # priority over wss host
    # network: ws
    # ws-opts:
    #   path: /path
    #   headers:
    #     Host: v2ray.com
    #   max-early-data: 2048
    #   early-data-header-name: Sec-WebSocket-Protocol

**Comment by vernesong** [comment]
```
你看下启动配置是不是改错了什么

**Comment by zhyhub123** [comment]
大佬，启动配置在哪看？另外，alterId: 32是必须的？安装好的v2ray是alterId:0。

**Comment by zhyhub123** [comment]
反复检测了好几天了，还是不知道问题在哪里。在clash里就可以，在openclash里就不行。配置的信息肯定正确，配置的顺序也是按照上面的，还是一样的问题。
利用订阅转换格式的方式也看了，配置的格式都是对的。
需要改成meta内核吗？

**Comment by vernesong** [comment]
![image](https://user-images.githubusercontent.com/42875168/198844807-31182022-a1ef-4560-928f-9d58970513b6.png)
看下这个配置里面写的对不对

**Comment by zhyhub123** [comment]
![配置文件](https://user-images.githubusercontent.com/92083354/198857026-3ee1edd0-e57d-415e-a728-d98cbeeb2dae.png)
我这里的openclash版本是V0.45.59-beta,没有大师说的下载运行配置。
是不是升级版本或转换成meta内核就行了。谢谢

**Comment by zhyhub123** [comment]
在规则集里添加了配置信息，显示有延时，能连通。之后，把这个配置信息由openclash写入到配置文件里，就又一样了。

**Comment by dinnermanac** [comment]
我和你遇到了一样的问题。我尝试了vless+xtls和trojan2种节点，都是在CFW或者ClashX下正常运行，完全相同的yaml配置文件防到Openclash上之后都无法识别（到Openclash首页-点击打开控制面板-代理页面滑到最下面查看节点，可以看到显示着Vless或者Trojan，但整个是灰色的，不显示ping值）

你的问题有得到解决吗？求教。

**Comment by zhyhub123** [comment]
问题解决了。
在大佬的指点下，发现openclash的版本需要升级到最新。在新的格式，需要新的app版本对应。
谢谢[vernesong]

**Comment by zhyhub123** [comment]
good
