### ISSUE TITLE
[Bug] 官方OpenWrt SNAPSHOT r21107开始luci错误，无法进入

### ISSUE THREAD

**Issue by k2p2p** [vernesong/OpenClash#2770]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

全部

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-armv5

### To Reproduce

官方OpenWrt SNAPSHOT r21107开始luci错误，无法进入

### Describe the Bug

官方OpenWrt SNAPSHOT r21107开始luci错误，无法进入

### OpenClash Log

官方OpenWrt SNAPSHOT r21107开始luci错误，无法进入

### Expected Behavior

官方OpenWrt SNAPSHOT r21107开始luci错误，无法进入

**Comment by vernlau** [comment]
昨天更新的Latest最新dev版本已经可以了。

插件版本: v0.45.67-beta
固件版本: OpenWrt SNAPSHOT r21112-eb456aedfe
LuCI版本: git-22.297.83017-0143ef2
内核版本: 5.15.74
处理器架构: x86_64

**Comment by k2p2p** [comment]
> 昨天更新的Latest最新dev版本已经可以了。
> 
> 插件版本: v0.45.67-beta
> 固件版本: OpenWrt SNAPSHOT r21112-eb456aedfe
> LuCI版本: git-22.297.83017-0143ef2
> 内核版本: 5.15.74
> 处理器架构: x86_6


还是不行
插件版本: v0.45.67-beta
固件版本: OpenWrt SNAPSHOT r21112-eb456aedfe
LuCI版本: git-22.297.83017-94dd7fd
内核版本: 5.10.149
处理器架构: arm

**Comment by vernlau** [comment]
最新commits是正常了的，不是前两天那个ipk。
![image](https://user-images.githubusercontent.com/24912536/198424446-32c5ff38-6459-41e3-8ff9-7a964018decd.png)
![image](https://user-images.githubusercontent.com/24912536/198424901-ad992298-3c54-413f-a532-ed96fd6d189a.png)

**Comment by k2p2p** [comment]
还是不行
插件版本: v0.45.67-beta

OpenWrt SNAPSHOT r21113-6a02205a4d / LuCI Master git-22.297.83017-94dd7fd
ARMv7 Processor rev 0 (v7l)
5.10.149

**Comment by vernlau** [comment]
> > 昨天更新的最新最新开发版本已经可以了。
> > 内核版本：v0.45.67-beta 
> > ：OpenWrt 固件APSHOT r21112-eb456aedfe 
> > Lu版本：git-22.297.83017-0143ef2
> > 内核版本：5.15.74
> > 处理器架构：x86_6
> 
> 还是不行 插件版本：v0.67- beta4版本：APSHOT r21112-eb456aedfe Lu版本：git-22.29783017-94dd7fd 内核版本：5.10.149 处理器架构：arm

最新commits是正常了的，不是前两天那个ipk。

**Comment by k2p2p** [comment]
![image](https://user-images.githubusercontent.com/31801071/198428216-8a586a5d-68f5-4386-b607-3d6b356a9630.png)

**Comment by vernlau** [comment]
> 还是不行 插件版本: v0.45.67-beta
> 
> OpenWrt SNAPSHOT r21113-6a02205a4d / LuCI Master git-22.297.83017-94dd7fd ARMv7 Processor rev 0 (v7l) 5.10.149
![image](https://user-images.githubusercontent.com/24912536/198429149-fe51df1b-2702-4f9c-ae4d-9292b95cc6f6.png)
![image](https://user-images.githubusercontent.com/24912536/198429243-1939ea97-2c13-4332-a9db-7719b3c1d279.png)

**Comment by vernlau** [comment]
> ![image](https://user-images.githubusercontent.com/31801071/198428216-8a586a5d-68f5-4386-b607-3d6b356a9630.png)

pull最新的提交，这个前天晚上就修好了。

**Comment by openips** [comment]
最新的没问题了 昨天我试了

**Comment by k2p2p** [comment]
昨天更新的Latest最新dev版本已经可以了。

插件版本: v0.45.67-beta
固件版本: OpenWrt SNAPSHOT r21112-eb456aedfe
LuCI版本: git-22.297.83017-94dd7fd
内核版本: 5.10.149
处理器架构: arm



    新的是没问题了，不过应该出发行版

**Comment by vernlau** [comment]
> 昨天更新的Latest最新dev版本已经可以了。
> 
> 插件版本: v0.45.67-beta 固件版本: OpenWrt SNAPSHOT r21112-eb456aedfe LuCI版本: git-22.297.83017-94dd7fd 内核版本: 5.10.149 处理器架构: arm
> 
> ```
> 新的是没问题了，不过应该出发行版
> ```

你用SNAPSHOT，应该了解这个含义。
出现这个问题是10.26早上，10.26晚上22点就更新修护了，已经很快了。

**Comment by hcym** [comment]
好像22.03主分支也不行，配置用的复制粘贴也凑活着用
