### ISSUE TITLE
开启IP v6的都有公网IP，所以IP v 6只需要转发，不需要nat

### ISSUE THREAD

**Issue by k2p2p** [vernesong/OpenClash#2771]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

目前对IP v6也做nat 处理

### Describe the Solution

把v6部分只做转发

### Describe Alternatives

或者加一个选择

**Comment by k2p2p** [comment]
![image](https://user-images.githubusercontent.com/31801071/198885301-a14b2c95-e3f8-4982-9db3-21adc0878a10.png)

**Comment by k2p2p** [comment]
![image](https://user-images.githubusercontent.com/31801071/198885407-ce8f5419-1ab1-41fa-b841-7dfb4c594857.png)

**Comment by k2p2p** [comment]
开启前后

**Comment by paladin4fan** [comment]
你用的FakeIP模式吧

**Comment by k2p2p** [comment]
> 你用的FakeIP模式吧 

不是的

**Comment by paladin4fan** [comment]
> > 你用的FakeIP模式吧
> 
> 不是的
redir如果开启了绕过大陆IP地址 大陆的测试站点就可以看到机子的IPv6地址了
其他测试地址流量进入内核了 碰到ipv6 就会用的tproxy 直连就显示是路由器地址 走节点流量的显示节点地址
这个代理类似nat 但是你的v6网络本质上还是不是NAT6, 你分配到的地址还是GUA地址 而且依然可以从外网通过ipv6直接访问你机子

**Comment by k2p2p** [comment]
> > > 你用的FakeIP模式吧
> > 
> > 不是的
> redir如果开启了绕过大陆IP地址 大陆的测试站点就可以看到机子的IPv6地址了
> 其他测试地址流量进入内核了 碰到ipv6 就会用的tproxy 直连就显示是路由器地址 走节点流量的显示节点地址
> 这个代理类似nat 但是你的v6网络本质上还是不是NAT6, 你分配到的地址还是GUA地址 而且依然可以从外网通过ipv6直接访问你机子
> 

我觉得即使是通过了内核也应该是直连，而不是tproxy直连，不需要ip伪装，直接转发就可以了

**Comment by machine-doll** [comment]
我的理解是大部分的机场就算给了IPv6，也不会给你一个/64及以上的网段，顶多给你一个IP  
流量经过clash内核了的话，要单独为这种场景做两套逻辑，很麻烦  
ipv6 大陆段的可以轻松绕过，根本不走clash内核。少数可以直连的ipv6地址，一个是基本上都被严重干扰，再一个就是多过了层NAT也没什么  
等到大部分的机场给大家人手一个/64甚至/56了，这个问题可能会被重视
