### ISSUE TITLE
所有域名在nameserver和fallback都会查一遍有泄露隐私风险

### ISSUE THREAD

**Issue by htgg1** [vernesong/OpenClash#2774]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [x] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

设置fallback分流规则后，查询国外网站域名还是会在nameserver组和fallback组都查询一遍 访问了什么中共直接看到了

### Describe the Solution

可以fallback规则里设置哪些域名不查询nameserver

**Comment by vernesong** [comment]
![image](https://user-images.githubusercontent.com/42875168/199661057-9b9a3ffa-a5ef-4b20-8548-c9a0a77a2973.png)
meta

**Comment by htgg1** [comment]
> ![image](https://user-images.githubusercontent.com/42875168/199661057-9b9a3ffa-a5ef-4b20-8548-c9a0a77a2973.png)
> meta

我尝试设置了 但是没成功 还是会用nameserver 查询google.com
也许我的意思表达的不太清楚？我是希望gfw屏蔽的域名就不用nameserver查询了 直接从fallback拿结果

**Comment by vernesong** [comment]
这样填就是，用meta内核

**Comment by htgg1** [comment]
![E089B28E-8E0F-4DED-AAE2-0848666CEE2D](https://user-images.githubusercontent.com/115396208/199690963-6d01e9c7-9fa9-4fd0-b06b-5f27d617f8e8.png)
![C8DBD72C-C202-49B4-B429-0F0A162AF3AB](https://user-images.githubusercontent.com/115396208/199690972-ae84399e-f51d-4370-9ca4-22b2f94e9819.png)
哪里不正确
nameserver组的adguardhome还是有查询google的日志
是meta内核

**Comment by vernesong** [comment]
忘记这里不是防泄漏的了，你用fakeip呢

**Comment by htgg1** [comment]
我不能用fake ip 家里有nas 开了fakeip直接变端口限制型
所以现在还无法实现这个功能？希望后续可以添加 谢谢

**Comment by vernesong** [comment]
IP规则不要写在域名规则前面，一般不会本地查询DNS

**Comment by momonoshiori** [comment]
会用nameserver查询所有域名主要是因为使用geoip判断国内或者国外域名，必须先全部解析域名才能判断。
如果需要nameserver里不解析国外域名好像现在只能用meta内核。
不用 geoip: true和geoip-code: CN这2行
 fallback-filter:
    geosite:
      - gfw
规则里如果使用了geoip也要修改
geosite,cn,DIRECT  #为了可以判断域名
geoip,CN,DIRECT,no-resolve
MATCH,Proxy

**Comment by htgg1** [comment]
> 会用nameserver查询所有域名主要是因为使用geoip判断国内或者国外域名，必须先全部解析域名才能判断。
> 如果需要nameserver里不解析国外域名好像现在只能用meta内核。
> 不用 geoip: true和geoip-code: CN这2行
> fallback-filter:
> geosite:
> - gfw
> 规则里如果使用了geoip也要修改
> geosite,cn,DIRECT #为了可以判断域名
> geoip,CN,DIRECT,no-resolve
> MATCH,Proxy

谢谢 我试试看

**Comment by htgg1** [comment]
> IP规则不要写在域名规则前面，一般不会本地查询DNS

没理解 是有办法fake ip和端口转发共存？
还是fallback规则写错了或者配置文件里的规则要怎么填

**Comment by momonoshiori** [comment]
半夜没看清忘记了只有fake ip才能解决这个问题redir-host好像无解。
而且听有些人说redir-host快被弃用了，不知道是不是真的。

**Comment by htgg1** [comment]
不可能吧 用了fake ip nat等级直接炸裂了 跟其他插件兼容也很差

**Comment by Karmylr** [comment]
> 不可能吧 用了fake ip nat等级直接炸裂了 跟其他插件兼容也很差

redir host确实被弃用了

**Comment by vernlau** [comment]
不用meta内核,
你nameserver和fallback前面可以套个mos分流转发到两个分内外的adguardhome，当然不用adguardhome也可以
  - tag: cn
    type: "query_matcher"
    args:
      domain:
        - "provider:geosite:cn,apple-cn,icloud,google-cn,tld-cn"

  - tag: gfw
    type: "query_matcher"
    args:
      domain:
        - "provider:geosite:gfw"

  - tag: notcn
    type: "query_matcher"
    args:
      domain:
        - "provider:geosite:geolocation-!cn"

  - tag: local_adh
    type: forward
    args:
      upstream:
        - addr: "h3://"
        - addr: "tls://"
        - addr: "quic://"

      bootstrap:
        - "tls://"
        - "https://"
      timeout: 5 
                               
  - tag: remote_adh
    type: forward
    args:
      upstream:
        - addr: "h3://"
        - addr: "tls://"
        - addr: "quic://"
        
      bootstrap:
        - "tls://"
        - "https://"
      timeout: 5

**Comment by htgg1** [comment]
> > 不可能吧 用了fake ip nat等级直接炸裂了 跟其他插件兼容也很差
> 
> redir host确实被弃用了

那现在fakeip导致nat类型变差有什么解决办法吗

**Comment by htgg1** [comment]
> 不用meta内核, 你nameserver和fallback前面可以套个mos分流转发到两个分内外的adguardhome，当然不用adguardhome也可以
> 
> * tag: cn
>   type: "query_matcher"
>   args:
>   domain:
>   - "provider:geosite:cn,apple-cn,icloud,google-cn,tld-cn"
> * tag: gfw
>   type: "query_matcher"
>   args:
>   domain:
>   - "provider:geosite:gfw"
> * tag: notcn
>   type: "query_matcher"
>   args:
>   domain:
>   - "provider:geosite:geolocation-!cn"
> * tag: local_adh
>   type: forward
>   args:
>   upstream:
>   - addr: "h3://"
>   - addr: "tls://"
>   - addr: "quic://"
>   bootstrap:
>   - "tls://"
>   - "https://"
>   timeout: 5
> * tag: remote_adh
>   type: forward
>   args:
>   upstream:
>   - addr: "h3://"
>   - addr: "tls://"
>   - addr: "quic://"
>   bootstrap:
>   - "tls://"
>   - "https://"
>   timeout: 5

学习一下

**Comment by htgg1** [comment]
fake ip刚才更新绕过大陆模式了 完美解决所有问题 感谢各位大佬 可以关闭这个issue了

**Comment by Karmylr** [comment]
> > > 不可能吧 用了fake ip nat等级直接炸裂了 跟其他插件兼容也很差
> > 
> > 
> > redir host确实被弃用了
> 
> 那现在fakeip导致nat类型变差有什么解决办法吗

nat类型变差?

**Comment by htgg1** [comment]
> > > > 不可能吧 用了fake ip nat等级直接炸裂了 跟其他插件兼容也很差
> > > 
> > > 
> > > redir host确实被弃用了
> > 
> > 
> > 那现在fakeip导致nat类型变差有什么解决办法吗
> 
> nat类型变差?

对呀 开了fake ip nas在外面就用不了了 网心云也显示端口限制型

**Comment by htgg1** [comment]
> fake ip刚才更新绕过大陆模式了 试试能不能让nas外部访问
还是放弃fake ip了 刚更新的大陆绕过模式也还是有好多奇怪的问题 nas外部访问只能用域名 直接用ip就连不上 而且电脑用了fake ip开网页贼慢不知道啥原因 还是得等之后再更新完善吧，，

**Comment by Neverends4** [comment]
暂时可以这样：整一个旁路由使用openclash，主路由最好是op，在dnsmasq里用tag指定需要科学设备的网关和DNS为旁路由

**Comment by htgg1** [comment]
Fake ip更新了绕过大陆模式 nas访问和保护隐私的问题暂时是解决了 fake ip发现一点奇怪的问题 这个issue可以先关闭了

**Comment by weicaixian86** [comment]
> 不用meta内核, 你nameserver和fallback前面可以套个mos分流转发到两个分内外的adguardhome，当然不用adguardhome也可以
> 
>     * tag: cn
>       type: "query_matcher"
>       args:
>       domain:
>       - "provider:geosite:cn,apple-cn,icloud,google-cn,tld-cn"
> 
>     * tag: gfw
>       type: "query_matcher"
>       args:
>       domain:
>       - "provider:geosite:gfw"
> 
>     * tag: notcn
>       type: "query_matcher"
>       args:
>       domain:
>       - "provider:geosite:geolocation-!cn"
> 
>     * tag: local_adh
>       type: forward
>       args:
>       upstream:
>       - addr: "h3://"
>       - addr: "tls://"
>       - addr: "quic://"
>       bootstrap:
>       - "tls://"
>       - "https://"
>       timeout: 5
> 
>     * tag: remote_adh
>       type: forward
>       args:
>       upstream:
>       - addr: "h3://"
>       - addr: "tls://"
>       - addr: "quic://"
>       bootstrap:
>       - "tls://"
>       - "https://"
>       timeout: 5

openclash 的DNS是并发查询，会造成DNS泄路这个是没有办法的，我的办法也是在前面加个mosdns进行分流。
