### ISSUE TITLE
[Feature] FAKE-IP 模式无法解析ipv6

### ISSUE THREAD

**Issue by cyh303** [vernesong/OpenClash#2775]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

FAKE-IP 模式无法解析ipv6地址  ipv6网站打不开  dns不返回V6地址    host模式下正常

### Describe the Solution

各位大佬有没有什么解决的好办法

**Comment by love4taylor** [comment]
fakeip 底下的设备是必然拿不到 AAAA 记录的，而是解析到 A 记录的 fakeip 然后通过 clash 再向外请求 AAAA 地址。

<img width="1210" alt="SCR-20221103-gvs" src="https://user-images.githubusercontent.com/6081912/199646006-b223ae9b-7174-4731-8269-3feeeae1338c.png">

**Comment by onlyLTY** [comment]
> fakeip 底下的设备是必然拿不到 AAAA 记录的，而是解析到 A 记录的 fakeip 然后通过 clash 再向外请求 AAAA 地址。
> 
> <img alt="SCR-20221103-gvs" width="1210" src="https://user-images.githubusercontent.com/6081912/199646006-b223ae9b-7174-4731-8269-3feeeae1338c.png">

请问这个是需要设置什么吗？yard界面我的有时候也会像你这样的出现ipv6地址。但更多的时候没有。

**Comment by love4taylor** [comment]
1. 用户请求域名 --> clash 返回 fake-ip --> 流量进入 clash --> 由 clash 判断该域名需要如何连接以及以什么地址访问，至于 v4v6 优先级你得问 clash
2. 用户请求裸 IPv6 地址 --> 若 openclash 开启 IPv6 转发则流量进入 clash 由其连接该地址 || 若 openclash 未开启 IPv6 转发就不进入 clash 直连该地址

其实说到底就是如果你访问的 IPv6 服务是域名方式，只要 clash 配置文件里 `ipv6: true` 就没啥问题。如果是裸 IP 的方式，只要 openclash 开了 IPv6 转发且依赖安装完整且 clash 配置文件 `ipv6: true` 那也没啥问题。

**Comment by machine-doll** [comment]
fake ip模式下，只要IP是clash返回的，一定是ipv4的fake ip。设备能不能访问到ipv6的网站，和这个过程并没有关系，因为真正与服务器建立连接的是clash  
参考Dreamacro的文档，clash能不能与ipv6的服务器建立连接，分两个情况：  
1. 直连  
在直连模式下，能不能访问ipv6的网站，一个是clash中对于这个策略所使用的DNS是否能够返回AAAA记录，再一个是clash的网络出口有没有ipv6的网络访问权限，还有就是是否打开了ipv6。在fake-ip模式下，clash会维护返回给客户端的fake-ip与实际的ipv6地址的关系，你发送给fake-ip的流量都会由clash自己转发到ipv6地址，反之亦然。所以服务器那边看到的是clash的ipv6 ip地址，你看到的是clash提供的fake-ip。但是这里似乎没有说端口映射和UDP转发是怎样进行的，不过应该和ipv4的情况是一样的
2. 代理  
由于我用过的几个机场都没有ipv6，我只能说一下我的猜测，不能保证准确。  
绝大多数机场是使用的ipv4来接受用户的传入连接，在这个过程中，用户这边是否有ipv6并不会有任何的影响  
clash在命中规则后，是交给节点来进行DNS解析的，本身的DNS查询只是匹配规则时使用的。如果你的clash允许了ipv6，哪怕你这边没有ipv6，只要你的机场支持v6，你就可以使用ipv6  
同样的，假设你的机场没有ipv6，那么由于走代理的情况下，你的连接直接发送给了机场的节点，由节点进行处理，是不会走你的ipv6的。你这边有没有ipv6，都没有影响  
---   
不排除有一些时候，节点本身是走ipv6的。这种情况下，fake-ip也没有影响，因为clash自己通过上游DNS拿到的是真实的ip。考虑到国内的ipv6国际出口的延时，这种情况应该是很少的
