### ISSUE TITLE
求问下如何解决网址被缓存成ip的问题

### ISSUE THREAD

**Issue by crotoc** [vernesong/OpenClash#278]
非常感谢这个软件，让分流变得非常方便！我使用的最新版本的openclash，今天碰到一个奇怪的问题，想问问怎么解决。

我在国外，想通过代理自动解锁国内视频，我将带有地址的规则放入了config文件：

DOMAIN-SUFFIX,video.qq.com,Proxy

发现只有第一次的时候，因为DNS解析的需要，网址是按照域名形式发送，这样可以被匹配上，而第二次开始由于路由或者电脑有缓存的ip了，这个网址不再出现，只是出现网址对应的ip，这样就很蛋疼了，由于相关ip太多，也不能说将所有的ip都转换出来，而且很多时候会出现换ip的情况。请问下这个问题openclash是怎么处理和解决。非常感谢！

**Comment by vernesong** [comment]
如果设置正确的话，那么日志显示ip不显示域名很可能是因为客户端不遵守ttl。
如果你在国外可以直接GEOIP,cn,proxy
或者尝试使用fakeip模式

**Comment by crotoc** [comment]
好的，谢谢~

**Comment by crotoc** [comment]
> 如果设置正确的话，那么日志显示ip不显示域名很可能是因为客户端不遵守ttl。
> 如果你在国外可以直接GEOIP,cn,proxy
> 或者尝试使用fakeip模式

还是没有办法成功，可能是其他设置的问题。
1.请问下这个openclash会建立ipset的list来存储需要代理的地址通过iptable进行转发么？
2. 如果是那我打开服务的时候，是不是ipset中找到对应的list，并且在iptable中看到转发规则。非常感谢！

**Comment by vernesong** [comment]
不会，那是ssr的国内白名单处理方式。你要确保dns通过clash查询，这样才会在clash内形成域名和dns的缓存关系。
你都用geoip了，国内ip肯定是代理的

**Comment by crotoc** [comment]
我今天查了下，是dns劫持出了问题。用netstat -nlp查询的时候发现clash只在:::监听,也就是说只在ipv6地址监听。这样是不是很不正常。我单独启动clash的时候也是只出现ipv6地址的监听。请问这个咋解决？

**Comment by crotoc** [comment]
我尝试了不同的解决办法，好像将bind_address从*换成127.0.0.1可以将服务带回到ipv4，然后将dns里面的0.0.0.0改成127.0.0.1可以把dns服务带回到ipv4，请问这样设置会有影响么？为什么在我的openwrt上面使用0.0.0.0的时候默认启动ipv6呢？有没有什么办法可以解决一下？谢谢

**Comment by crotoc** [comment]
我按照上述的更改之后，好像可以正确的代理，看起来原因就是这个了。当时我还是不懂原理，希望能有个系统的方法解决。

**Comment by vernesong** [comment]
端口占用情况我的跟你一样，dns确实没有指定监听地址，但是我路由禁用了ipv6

**Comment by crotoc** [comment]
之前我尝试禁用ipv6，结果把openwrt搞挂了，还是没找到能用的方法。改成127之后看起来都正常了。希望这个能安全维持下去。谢谢了，我有问题在来麻烦你。

**Comment by crotoc** [comment]
你觉得有必要pull request把我说的两个地方改成127.0.0.1么？谢谢！

**Comment by vernesong** [comment]
bind_address跟这些无关，dns监听地址我在下个版本改成127先观察一段时间

**Comment by crotoc** [comment]
我之前试了下，如果把bind_address改成127的话，相当于是吧redir, http, socks的listen换成ipv4，可能这个即使放在ipv6也不影响使用。dns劫持listen在127比较关键，因为域名匹配在clash中的实现就是用的clash自己的dns。这个信息放在这里，如果有人出了问题，应该能搜索出来，谢谢！：）

**Comment by 2054686334** [comment]
禁止 Dnsmasq 缓存 DNS 
 推荐启用，防止因缓存造成连接错误（部分固件可能不兼容）
我之前也是这样，开启这个选项之后正常，仅供参考
