### ISSUE TITLE
[Bug] 出现间歇性CPU占用过大的情况

### ISSUE THREAD

**Issue by ximiTech** [vernesong/OpenClash#2784]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.70-beta

### Bug on Environment

Lean

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

使能openclash，并观察cpu占用率

### Describe the Bug

openclash出现间歇性CPU占用过大的情况

### OpenClash Log

无

### OpenClash Config

```shell
无
```

### Expected Behavior

CPU占用不应出现陡然上升下降的情况

### Screenshots

![111](https://user-images.githubusercontent.com/63538901/200162458-e16f7f4c-29eb-4add-b9e2-ca8b5950e86b.JPG)

**Comment by Karmylr** [comment]
看连接数

**Comment by ximiTech** [comment]
相比之下，passwall的CPU占用率
![222](https://user-images.githubusercontent.com/63538901/200164532-df76cd46-9f77-4f61-bff5-99ffd4e82b17.JPG)

**Comment by Sanhom365** [comment]
我也有这种情况，根据观察，差不多每分钟会有个波峰，CPU使用率会一下子上升15%左右，几秒钟后恢复。

**Comment by Karmylr** [comment]
> 我也有这种情况，根据观察，差不多每分钟会有个波峰，CPU使用率会一下子上升15%左右，几秒钟后恢复。

正常的

**Comment by Sanhom365** [comment]
> > 我也有这种情况，根据观察，差不多每分钟会有个波峰，CPU使用率会一下子上升15%左右，几秒钟后恢复。
> 
> 正常的

后来我把“实验性：绕过中国大陆 IP”和“实验性：绕过中国大陆 IPv6”关了，这个波峰几乎没有了（还是会有一点点，但只有1%左右，之前会超过平时的15%左右），并且“自定义规则”中设置的直连和拒绝也都有效了。
