### ISSUE TITLE
[Feature] 在升级到 69版本时，自动转换 core_version

### ISSUE THREAD

**Issue by xlighting2017** [vernesong/OpenClash#2785]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

69版本 将原来的 core_version值，从 linux-armv8 改成了  linux-arm64 

如果一个人使用了 69版本之前的版本，然后升级至69版本，则他的 core_version值 仍然是 linux-armv8  （在 /etc/config/openclash中）

此时，他要升级 clash core核心，就会失败，且提示信息不明显 

![image](https://user-images.githubusercontent.com/25970065/200164041-ab302641-eece-4625-ad9a-5643bffd6f3a.png)

真实的失败原因是升级时，URL是根据 core_version 转换的，由于旧配置是 armv8，
生成的URL是clash-linux-**armv8**-xxxxx.gz, 
而repo中的URL已变成了clash-linux-**arm64**-xxxxx.gz

### Describe the Solution

实现一个 兼容层，将  linux-armv8 和   linux-arm64 视为一致，
或者 做一个转换，将 用户原配置中的   linux-armv8  自动转换为 linux-arm64

### Describe Alternatives

workaround：
需要用户自己在 版本更新 页面，手动选择 “已选择编译版本” 至  linux-arm64 并保存后，就可正常更新

**Comment by vernesong** [comment]
一般安装的时候会自己改过来，插件显示的内核什么型号的

**Comment by xlighting2017** [comment]
> 一般安装的时候会自己改过来，插件显示的内核什么型号的

我升级之后，已选择编译版本 在网页上显示是 空值， 自己手动修改 才正常

**Comment by vernesong** [comment]
有些型号可能识别不了
