### ISSUE TITLE
[Bug] 更新最新版后，使用hysteria协议，启动时显示'alpn' is not a slice

### ISSUE THREAD

**Issue by moranno** [vernesong/OpenClash#2788]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [x] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

 v0.45.70-beta

### Bug on Environment

Lean

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

刚更新完成最新版，之前一直能用的配置文件，在更新完成后启动过程中报错：'alpn' is not a slice

### Describe the Bug

上面说了

### OpenClash Log

2022-11-06 22:53:23 level=fatal msg="Parse config error: proxy 0: 'alpn' is not a slice"
2022-11-06 22:53:23 level=info msg="Start initial configuration in progress"

### OpenClash Config

```shell
- { name: hy, type: hysteria, server: xxx.xxx.com, port: 440, auth_str: fewahgire8343y7wp9hg, alpn: h3, protocol: udp, up: '50', down: '100' }
```

### Expected Behavior

能正常使用

**Comment by vernesong** [comment]
格式改了，重新生成一下配置

**Comment by moranno** [comment]
> 格式改了，重新生成一下配置

请问改成啥了？翻了hy和这边的wiki都没找到相关修改内容额。

**Comment by skill7899** [comment]
> > 格式改了，重新生成一下配置
> 
> 请问改成啥了？翻了hy和这边的wiki都没找到相关修改内容额。
> 
> edit: 使用数组： alpn: ['h3']

这个是meta的问题

**Comment by vernesong** [comment]
如果你是插件添加的节点不是自己写的配置，就重新去服务器策略组页面确认修改一下配置文件

**Comment by jencoxu** [comment]
我也碰到同样的问题，请问怎么改配置啊？

**Comment by skill7899** [comment]
> 我也碰到同样的问题，请问怎么改配置啊？

上面不是用吗？修改了数组了。alpn

**Comment by jencoxu** [comment]
> > 我也碰到同样的问题，请问怎么改配置啊？
> 
> 上面不是用吗？修改了数组了。alpn

哦，了解了，改成  alpn:  ['h3']

**Comment by Job28703** [comment]
测试网速，显示会有问题，无法显示

**Comment by UncleUncleWang** [comment]
重新配置了确实也还是不行，是不是得手动改了
