### ISSUE TITLE
iOS家庭 摄像头连接问题[Feature] 

### ISSUE THREAD

**Issue by YiliTang** [vernesong/OpenClash#2790]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

在OpenWrt中使用OpenClash，Fake-IP模式，局域网内访问国内国外均正常，iOS家庭中的摄像头画面可以正常查看。
防火墙开启了端口转发，转发了本地网络中的SMB和OpenClash的HTTP(S)&SOCKS5 混合代理端口

iOS设备使用第三方软件（Stash），从公网IP连接OpenClash的HTTP(S)&SOCKS5 混合代理端口
可以正常国内国外，但是iOS家庭中的摄像头无法查看，SMB也无法连接。
此摄像头是Aqara平台的摄像头，使用Aqara的App可以正常查看画面。

Stash中的Socks5代理配置文件如下，使用时设置为全局代理

dns:
    enable: true
    ipv6: false
    default-nameserver: [114.114.114.114, 223.5.5.5, 223.6.6.6, 119.29.29.29]
    enhanced-mode: redir-host
    fake-ip-range: 198.18.0.1/16
    fake-ip-filter: ['我的域名'] #OpenClash Fake-IP模式 DNS无法返回真实IP 需要过滤
    use-hosts: true
    nameserver: ['https://doh.pub/dns-query', 'https://dns.alidns.com/dns-query', 'https://dns27.hichina.com', 'https://dns28.hichina.com']
    fallback: ['https://doh.dns.sb/dns-query', 'https://dns.cloudflare.com/dns-query', 'https://dns.twnic.tw/dns-query', 'tls://8.8.4.4:853']

proxies:
  - { name: 'OpenClashProxy', type: socks5, server: 我的域名, port: xxx, udp: true}
  
proxy-groups:
  -
    name: AllProxy
    type: select
    proxies: ['OpenClashProxy']
    
rules:
  - MATCH,AllProxy

### Describe the Solution

不清楚这是为什么。。。求大神解答。

**Comment by vernesong** [comment]
外网访问这些设备的时候clash日志显示是什么行为

**Comment by YiliTang** [comment]
> 
摄像头的问题已经解决了。目前SMB还有问题，223.104.159.232为蜂窝数据的iOS设备IP，不使用代理时可以连接SMB，
[2022-11-07 14:32:02][WARNING] [TCP] dial DIRECT (match GeoIP/CN) 223.104.159.232:6450 --> 我的公网IP:我的SMB端口 error: dial tcp4 我的公网IP:我的SMB端口: connect: connection refused

**Comment by YiliTang** [comment]
还有一个情况是我局域网的PC，映射网络驱动器\\公网IP:公网的SMB端口，是无法连接的，映射网络驱动器\\局域网SMB的IP\，是可以正常连接的。

**Comment by YiliTang** [comment]
是不是在clash里添加内网DNS？

**Comment by vernesong** [comment]
你试试加host，公网域名内网ip

**Comment by YiliTang** [comment]
我的OpenWrt有设置不同端口转发到不同的设备，host设置成公网域名和内网OpenWrt的IP吗？

**Comment by vernesong** [comment]
![image](https://user-images.githubusercontent.com/42875168/200819896-bbba4a5e-c557-42e3-9a87-33cc68dfeaa0.png)
在clash里面解析成内网ip去访问
