### ISSUE TITLE
请问一下能否指定某个域名强制使用nameserver的dns服务器去解析dns呢？

### ISSUE THREAD

**Issue by Linyue-GitHub** [vernesong/OpenClash#2792]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

因为手动设置了smartdns国内外分流dns服务器，有一个域名一直被识别为国外fallback组去解析，因为我不想要国外域名解析v6dns，所以在smartdns上关闭了国外组dns的v6解析，这个域名恰好又需要v6才能访问，很苦恼。

### Describe the Solution

指定某个域名强制使用nameserver的dns服务器去解析dns

**Comment by htgg1** [comment]
在smartdns里设置

**Comment by Green-m** [comment]
clash 中有 nameserver-policy 这个设置可以指定对应域名让某个DNS服务器解析，不过我没有找到openclash中应该如何设置，见 [issue](https://github.com/vernesong/OpenClash/issues/2794)。
