### ISSUE TITLE
请问如何在openclash 中自定义 nameserver-policy 设置？

### ISSUE THREAD

**Issue by Green-m** [vernesong/OpenClash#2794]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

想自定义nameserver-policy规则，没有找到对应的方案，在dns设置中的自定义 Fallback-Filter中写了该部分配置，也不生效。

### Describe the Solution

希望添加该部分功能，如果有现成的方案的话还请指教一下，多谢。

**Comment by vernesong** [comment]
![image](https://user-images.githubusercontent.com/42875168/201515065-04bc5b8f-2e08-40b0-a270-e5b4bedd21fa.png)

**Comment by Green-m** [comment]
@vernesong 我找到了，在DNS设置中的高级设置中，多谢您的回复。
