### ISSUE TITLE
googlevideo.com被识别为国内IP，IOS版YT视频不播放[Bug] 

### ISSUE THREAD

**Issue by lingyunzhiss** [vernesong/OpenClash#2797]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.69

### Bug on Environment

Other

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

iStoreOS没做任何调整，IOS手机版YT客户端更新后出现的。fake-ip 混合模式。

### Describe the Bug

所有安卓系统不受影响
所有IOS手机版youtubo能打开浏览，但所有视频无法打开闪断
（无法贴图？？？）

### OpenClash Log

openclash启动运行无问题
2022-11-07 23:04:46 提示：Disney Plus 域名预解析完成!
2022-11-07 23:04:37 提示：开始预解析 Disney Plus 域名...
2022-11-07 23:04:37 提示：Netflix 域名预解析完成!
2022-11-07 23:01:46 提示：开始预解析 Netflix 域名...
2022-11-07 23:00:46 OpenClash 启动成功，请等待服务器上线！
2022-11-07 23:00:45 第九步: 添加计划任务,启动进程守护程序...
2022-11-07 23:00:45 第八步: 重启 Dnsmasq 程序...
2022-11-07 23:00:44 第七步: 设置防火墙规则...
2022-11-07 23:00:44 第六步: 等待主程序下载外部文件...
2022-11-07 23:00:41 第五步: 检查内核启动状态...
2022-11-07 23:00:40 提示: 检测到配置了 Meta 内核专属功能，调用 Meta 内核启动...
2022-11-07 23:00:40 第四步: 启动主程序...

### OpenClash Config

```shell
修改配置文件加入 fake-ip-filter: - "+.googlevideo.com"恢复了IOS端的视频播放。
```

### Expected Behavior

手动修改配置文件不方便。
另外，还有发线“米家”无法打开远程摄像头视频。

### Screenshots

这里无法贴图？？？

**Comment by lingyunzhiss** [comment]
升级到70版，配置文件复原，用Redir-Host混合模式，IOS版YouTube端googlevideo.com不再识别为国内IP，走的是Other规则，同时米家可以正常播放远程摄像头了。

**Comment by AXBNG** [comment]
是不是googlevideo解析出的ip包含在了大陆白名单里，然后openclash选择绕过大陆ip，就导致了不走代理   (º﹃º)

**Comment by vernesong** [comment]
把fallbackfilter加一下

**Comment by htgg1** [comment]
dns污染了吧

**Comment by charlie1227** [comment]
跟你一样，遇到了IOS端油管app视频不能播放的情况。折腾了一番后，转为fake-ip模式（兼容）之后，貌似正常了。

**Comment by zakk-ex** [comment]
与你一样的问题，区别是我这是所有设备（win11、IOS、android）都能预览youtube视频缩略图但不能播放视频。推特很多图片没法加载或者加载很久。升级到70版本后切换为fake-IP模式后就恢复正常了。注：redir-host模式下已经根据github的DNS设定设定了DNS。

**Comment by lingyunzhiss** [comment]
正解在这里，IOS端再也没出现过问题了。
<img width="1079" alt="image" src="https://user-images.githubusercontent.com/19514184/202850839-b1fcbccc-6c8a-4395-8750-c734ce77b548.png">
