### ISSUE TITLE
[Bug] 经常卡死，需要重启插件

### ISSUE THREAD

**Issue by djkcyl** [vernesong/OpenClash#2798]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.70-beta

### Bug on Environment

Official OpenWrt, Lean

### Bug on Platform

Linux-amd64(x86-64), Linux-arm64

### To Reproduce

开启插件后使用若干时间

### Describe the Bug

开启插件后经常网站加载时间超过几分钟，打开web管理后会出现类似如下的情况
![image](https://user-images.githubusercontent.com/59153990/200381993-2415bdd5-ad18-4e77-b7bc-689dd79dca41.png)
![_P G F30_R_ZWW16ZNTP MI](https://user-images.githubusercontent.com/59153990/200382020-4e047b64-4096-43d5-9c43-2cb27c271ee0.png)
需要等待很久才会恢复，在此期间无法重启插件

### OpenClash Log

![image](https://user-images.githubusercontent.com/59153990/200394248-7f10535e-a4ca-4c93-9be5-2182105ca7c1.png)

### Expected Behavior

修复卡顿

**Comment by TnZzZHlp** [comment]
这个应该是你设备的问题，而且openclash只是一个clash的启动器而已，这种问题到clash那边去反馈吧

**Comment by djkcyl** [comment]
> 这个应该是你设备的问题，而且openclash只是一个clash的启动器而已，这种问题到clash那边去反馈吧

我之前也以为是我自己设备问题，但我用的x86机器装的跟arm机器装的都是这样子卡着，挺奇怪的

**Comment by vernesong** [comment]
开控制面板看看连接数

**Comment by caopeng19911002** [comment]
卡死什么意思，我好像也遇到了，用的Meta内核就是突然谷歌YouTube都不能连接，但是节点是正常的，用别的客户端都可以

**Comment by littleneko** [comment]
我也经常这样，不过我这里应该是宽带的问题，垃圾宽带，经常过一段时间就断了，不知道是本来垃圾还是识别到我用代理了，然后宽带恢复后大概率要重启一下 clash 才能正常工作，不然有些网站打不开

**Comment by djkcyl** [comment]
> 卡死什么意思，我好像也遇到了，用的Meta内核就是突然谷歌YouTube都不能连接，但是节点是正常的，用别的客户端都可以

就是进管理页面跟我上面截图的一样，加载不出数据

**Comment by caopeng19911002** [comment]
[](url)[](url)
![截屏2022-11-30 19 40 46](https://user-images.githubusercontent.com/111079733/204787212-6b7ee985-c3fe-4e56-9faf-825caf5a8b5d.png)
我好像是因为节点是cdn加速的，下载ftp.jaist.ac.jp:443失败

**Comment by caopeng19911002** [comment]
goole了下好像是因为jaist.ac.jp被污染不知道有没有什么解决办法
