### ISSUE TITLE
节点在线转换失败，后台老师下载啥东西失败！

### ISSUE THREAD

**Issue by silmee** [vernesong/OpenClash#2799]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

2022-11-08 11:55:45【/tmp/openclash_last_version】下载失败：【curl: (28) Connection timed out after 10001 milliseconds】
2022-11-08 11:55:07【/tmp/openclash_last_version】下载失败：【curl: (28) Connection timed out after 10001 milliseconds】
2022-11-08 11:55:07【/tmp/openclash_last_version】下载失败：【curl: (28) Connection timed out after 10001 milliseconds】
2022-11-08 11:55:07【/tmp/openclash_last_version】下载失败：【curl: (28) Connection timed out after 10000 milliseconds】
2022-11-08 11:54:57【/tmp/openclash_last_version】下载失败：【curl: (28) Connection timed out after 10001 milliseconds】
2022-11-08 11:53:19 守护程序：检测到转发规则顺序错误，修改插件防火墙规则...
2022-11-08 11:52:04【/tmp/openclash_last_version】下载失败：【curl: (28) Connection timed out after 10002 milliseconds】
2022-11-08 11:51:52【/tmp/openclash_last_version】下载失败：【curl: (28) Connection timed out after 10001 milliseconds】
2022-11-08 11:52:04【/tmp/openclash_last_version】下载失败：【curl: (28) Connection timed out after 10001 milliseconds】
2022-11-08 11:52:19 错误：【A】下载失败，请检查网络或稍后再试...
2022-11-08 11:52:16 错误：更新的配置文件【A】节点部分校验失败...
2022-11-08 11:52:04【/tmp/openclash_last_version】下载失败：【curl: (28) Connection timed out after 10001 milliseconds】
2022-11-08 11:51:52【/tmp/openclash_last_version】下载失败：【curl: (28) Connection timed out after 10000 milliseconds】
2022-11-08 11:52:11 错误：配置文件【A】订阅失败，尝试不使用代理下载配置文件...
2022-11-08 11:51:53【/tmp/yaml_sub_tmp_config.yaml】下载失败：【curl: (28) Connection timeout after 5001 ms】
2022-11-08 11:51:53【/tmp/yaml_sub_tmp_config.yaml】下载失败：【curl: (28) Connection timeout after 5001 ms】
2022-11-08 11:51:54【/tmp/openclash_last_version】下载失败：【curl: (28) Connection timed out after 10001 milliseconds】
2022-11-08 11:51:52【/tmp/openclash_last_version】下载失败：【curl: (28) Connection timed out after 10000 milliseconds】
2022-11-08 11:51:53【/tmp/yaml_sub_tmp_config.yaml】下载失败：【curl: (28) Connection timeout after 5001 ms】
2022-11-08 11:51:53 开始更新配置文件【A】...
2022-11-08 11:51:42【/tmp/openclash_last_version】下载失败：【curl: (28) Connection timed out after 10000 milliseconds】

### Describe the Solution

~

**Comment by mouseroser** [comment]
我也出现相同的情况

**Comment by mouseroser** [comment]
有大大发现问题了，应该和 vernesong 无关
[https://github.com/vernesong/OpenClash/issues/2795#issuecomment-1307971027](url)

**Comment by silmee** [comment]
> curl

咋解决啊~

**Comment by yff0216** [comment]
我也有这个问题

**Comment by mouseroser** [comment]
等新版本更新了

**Comment by Eircodong** [comment]
内核版本: 5.15.74
处理器架构: aarch64_generic
同样出现该问题 
无法在线转换更新订阅

**Comment by vernesong** [comment]
换固件吧，curl的问题我没法修

**Comment by YASUKUMI** [comment]
curl 7.86.0-2 会导致 在线订阅转换 有问题。同时oc 0.45.70 又与curl兼容有问题。解决方案：curl版本7.85.0-1. oc版本 0.45.16，测试没有问题。内核版本不会影响上述问题。curl不能最新，oc不能最新。这两个有一个最新就没法正常用。

**Comment by mouseroser** [comment]
能否提供下这两个软件包啊

**Comment by mouseroser** [comment]
> curl 7.86.0-2 会导致 在线订阅转换 有问题。同时oc 0.45.70 又与curl兼容有问题。解决方案：curl版本7.85.0-1. oc版本 0.45.16，测试没有问题。内核版本不会影响上述问题。curl不能最新，oc不能最新。这两个有一个最新就没法正常用。

oc的软件全名有吗？package包里面我没有找到啊

**Comment by mouseroser** [comment]
> curl 7.86.0-2 会导致 在线订阅转换 有问题。同时oc 0.45.70 又与curl兼容有问题。解决方案：curl版本7.85.0-1. oc版本 0.45.16，测试没有问题。内核版本不会影响上述问题。curl不能最新，oc不能最新。这两个有一个最新就没法正常用。

不好意思，脑子秀逗了，oc--openclash，curl只要是7.85.0-1及以下版本就可以对吧

**Comment by libuke** [comment]
curl的问题可参考：https://github.com/curl/curl/issues/9889

https://github.com/vernesong/OpenClash/tree/master/luci-app-openclash/root/usr/share/openclash/openclash.sh
第39行
urlencode() {
   local data
   if [ "$#" -eq 1 ]; then
      data=$(curl -s -o /dev/null -w %{url_effective} --get --data-urlencode "key=$1" "")
      if [ ! -z "$data" ]; then
         echo -n "$(echo ${data##/?key=} |sed 's/\//%2f/g' |sed 's/:/%3a/g' |sed 's/?/%3f/g' |sed 's/(/%28/g' |sed 's/)/%29/g' |sed 's/\^/%5e/g' |sed 's/=/%3d/g' |sed 's/|/%7c/g' |sed 's/+/%20/g')"
      fi
   fi
}

**curl -s -o /dev/null -w %{url_effective} --get --data-urlencode "key=$1" ""**
这段代码在curl 7.86.0版本下无法正常工作 (curl 7.86.0版本未返回编码后的字符串)

后续生成URL：https://订阅转换链接?target=clash&new_name=true&url=订阅链接（空字符串）
导致下载出错

在不回滚curl 7.86.0之前版本解决方案如下：
vim /usr/share/openclash/openclash.sh 39行
将原先urlencode()方法替换成下面的

urlencode() {
  local string="${1}"
  local strlen=${#string}
  local encoded=""
  local pos c o

  for (( pos=0 ; pos<strlen ; pos++ )); do
     c=${string:$pos:1}
     case "$c" in
        [-_.~a-zA-Z0-9] ) o="${c}" ;;
        * )               printf -v o '%%%02x' "'$c"
     esac
     encoded+="${o}"
  done
  echo "${encoded}"    # You can either set a return variable (FASTER) 
  REPLY="${encoded}"   #+or echo the result (EASIER)... or both... :p
}

**Comment by YASUKUMI** [comment]
> > curl 7.86.0-2 会导致 在线订阅转换 有问题。同时oc 0.45.70 又与curl兼容有问题。解决方案：curl版本7.85.0-1. oc版本 0.45.16，测试没有问题。内核版本不会影响上述问题。curl不能最新，oc不能最新。这两个有一个最新就没法正常用。
> 
> 不好意思，脑子秀逗了，oc--openclash，curl只要是7.85.0-1及以下版本就可以对吧

目前我的组合是：curl 7.85.0-1，oc 0.45.16。oc应该能升级一下但是避免最近的一个月的版本应该问题不大。

**Comment by YASUKUMI** [comment]
oc 0.45.59 也可以用，.16的确有点老了。抱歉。

**Comment by mouseroser** [comment]
> curl的问题可参考：[curl/curl#9889](https://github.com/curl/curl/issues/9889)
> 
> https://github.com/vernesong/OpenClash/tree/master/luci-app-openclash/root/usr/share/openclash/openclash.sh 第39行 urlencode() { local data if [ "$#" -eq 1 ]; then data=$(curl -s -o /dev/null -w %{url_effective} --get --data-urlencode "key=$1" "") if [ ! -z "$data" ]; then echo -n "$(echo ${data##/?key=} |sed 's///%2f/g' |sed 's/:/%3a/g' |sed 's/?/%3f/g' |sed 's/(/%28/g' |sed 's/)/%29/g' |sed 's/^/%5e/g' |sed 's/=/%3d/g' |sed 's/|/%7c/g' |sed 's/+/%20/g')" fi fi }
> 
> **curl -s -o /dev/null -w %{url_effective} --get --data-urlencode "key=$1" ""** 这段代码在curl 7.86.0版本下无法正常工作 (curl 7.86.0版本未返回编码后的字符串)
> 
> 后续生成URL：[https://订阅转换链接?target=clash&new_name=true&url=订阅链接（空字符串）](https://%E8%AE%A2%E9%98%85%E8%BD%AC%E6%8D%A2%E9%93%BE%E6%8E%A5?target=clash&new_name=true&url=%E8%AE%A2%E9%98%85%E9%93%BE%E6%8E%A5%EF%BC%88%E7%A9%BA%E5%AD%97%E7%AC%A6%E4%B8%B2%EF%BC%89) 导致下载出错
> 
> 在不回滚curl 7.86.0之前版本解决方案如下： vim /usr/share/openclash/openclash.sh 39行 将原先urlencode()方法替换成下面的
> 
> urlencode() { local string="${1}" local strlen=${#string} local encoded="" local pos c o
> 
> for (( pos=0 ; pos<strlen ; pos++ )); do c=${string:$pos:1} case "$c" in [-_.~a-zA-Z0-9] ) o="${c}" ;; * ) printf -v o '%%%02x' "'$c" esac encoded+="${o}" done echo "${encoded}" # You can either set a return variable (FASTER) REPLY="${encoded}" #+or echo the result (EASIER)... or both... :p }

已验证，更新订阅恢复正常

urlencode() {
  local string="${1}"
  local strlen=${#string}
  local encoded=""
  local pos c o

  for (( pos=0 ; pos<strlen ; pos++ )); do
     c=${string:$pos:1}
     case "$c" in
        [-_=.:/\&\?~a-zA-Z0-9] ) o="${c}" ;;
        * )               printf -v o '%%%02x' "'$c"
     esac
     encoded+="${o}"
  done

  echo "${encoded}"    # You can either set a return variable (FASTER)
  REPLY="${encoded}"   #+or echo the result (EASIER)... or both... :p

}

**Comment by caliban511** [comment]
> curl的问题可参考：[curl/curl#9889](https://github.com/curl/curl/issues/9889)
> 
> https://github.com/vernesong/OpenClash/tree/master/luci-app-openclash/root/usr/share/openclash/openclash.sh 第39行 urlencode() { local data if [ "$#" -eq 1 ]; then data=$(curl -s -o /dev/null -w %{url_effective} --get --data-urlencode "key=$1" "") if [ ! -z "$data" ]; then echo -n "$(echo ${data##/?key=} |sed 's///%2f/g' |sed 's/:/%3a/g' |sed 's/?/%3f/g' |sed 's/(/%28/g' |sed 's/)/%29/g' |sed 's/^/%5e/g' |sed 's/=/%3d/g' |sed 's/|/%7c/g' |sed 's/+/%20/g')" fi fi }
> 
> **curl -s -o /dev/null -w %{url_effective} --get --data-urlencode "key=$1" ""** 这段代码在curl 7.86.0版本下无法正常工作 (curl 7.86.0版本未返回编码后的字符串)
> 
> 后续生成URL：[https://订阅转换链接?target=clash&new_name=true&url=订阅链接（空字符串）](https://%E8%AE%A2%E9%98%85%E8%BD%AC%E6%8D%A2%E9%93%BE%E6%8E%A5?target=clash&new_name=true&url=%E8%AE%A2%E9%98%85%E9%93%BE%E6%8E%A5%EF%BC%88%E7%A9%BA%E5%AD%97%E7%AC%A6%E4%B8%B2%EF%BC%89) 导致下载出错
> 
> 在不回滚curl 7.86.0之前版本解决方案如下： vim /usr/share/openclash/openclash.sh 39行 将原先urlencode()方法替换成下面的
> 
> urlencode() { local string="${1}" local strlen=${#string} local encoded="" local pos c o
> 
> for (( pos=0 ; pos<strlen ; pos++ )); do c=${string:$pos:1} case "$c" in [-_.~a-zA-Z0-9] ) o="${c}" ;; * ) printf -v o '%%%02x' "'$c" esac encoded+="${o}" done echo "${encoded}" # You can either set a return variable (FASTER) REPLY="${encoded}" #+or echo the result (EASIER)... or both... :p }

感谢大佬，订阅转换成功，，，但节点关键字过滤的功能好像失效，不知道你那里有没有相同问题？

**Comment by libuke** [comment]
> > curl的问题可参考：curl[/curl#9889](https://github.com/curl/curl/issues/9889)
> > https://github.com/vernesong/OpenClash/tree/master/luci-app-openclash/root/usr/share/openclash/openclash.sh 第39行 urlencode（） { local data if [ “$#” -eq 1 ]; then data=$（curl -s -o /dev/null -w %{url_effective} --get --data-urlencode “key=$1” “”） if [ ！-z “$data” ];then echo -n “$（echo ${data##/？key=} |sed 's///%2f/g' |sed 's/：/%3a/g' |sed 's/？/%3f/g' |sed 's/（/%28/g' |sed 's/）/%29/g' |sed 's/^/%5e/g' |sed 's/=/%3d/g' |sed 's/|/%7c/g' |sed 's/+/%20/g'）” fi fi }
> > **curl -s -o /dev/null -w %{url_effective} --get --data-urlencode “key=$1” “”这段**代码在curl 7.86.0版本下无法正常工作 （curl 7.86.0版本未返回编码后的字符串）
> > 后续生成URL：[https:// 订阅转换链接？target=clash&new_name=true&url=订阅链接（空字符串）](https://%E8%AE%A2%E9%98%85%E8%BD%AC%E6%8D%A2%E9%93%BE%E6%8E%A5?target=clash&new_name=true&url=%E8%AE%A2%E9%98%85%E9%93%BE%E6%8E%A5%EF%BC%88%E7%A9%BA%E5%AD%97%E7%AC%A6%E4%B8%B2%EF%BC%89)导致下载出错
> > 在不回滚curl 7.86.0之前版本解决方案如下： vim /usr/share/openclash/openclash.sh 39行 将原先urlencode（）方法替换成下面的
> > urlencode（） { local string=“${1}” local strlen=${#string} local encoded=“” local pos c o
> > for （ pos=0 ; pos<strlen ; pos++ ））;do c=${string：$pos：1} case “$c” in [-_.~a-zA-Z0-9] ） o=“${c}” ;;* ） printf -v o '%%%02x' “'$c” esac encoded+=“${o}” done echo “${encoded}” # 你可以设置一个返回变量（FASTER） REPLY=“${encoded}” #+或echo the result （EASY）...或两者兼而有之... :p }
> 
> 感谢大佬，订阅转换成功，，，但节点关键字过滤的功能好像失效，不知道你那里有没有相同问题？

我未使用过该功能，未注意到问题

[Vernesong](https://github.com/vernesong) 大佬已经修复curl 7.86.0无法正常下载订阅的功能
[curl's urlencode not work](https://github.com/vernesong/OpenClash/commit/c0c8a70cd70d93d96392b2719fc3476f4a6c63e7)
在作者没发布前 可以先手动修改这几个文件

**Comment by caliban511** [comment]
> 
> 我未使用过该功能，未注意到问题
> 
> [Vernesong](https://github.com/vernesong) 大佬已经修复curl 7.86.0无法正常下载订阅的功能 [curl's urlencode not work](https://github.com/vernesong/OpenClash/commit/c0c8a70cd70d93d96392b2719fc3476f4a6c63e7) 在作者没发布前 可以先手动修改这几个文件

好的，感谢回复。
