### ISSUE TITLE
Openclash 启动失败

### ISSUE THREAD

**Issue by zelbloo** [vernesong/OpenClash#280]
log信息
2020-03-25 16:20:56 Watchdog: Clash Core Problem, Restart.
time="2020-03-25T16:20:57Z" level=fatal msg="Parse config error: yaml: line 15: mapping values are not allowed in this context"
time="2020-03-25T16:22:59Z" level=fatal msg="Parse config error: yaml: line 30: mapping values are not allowed in this context"
2020-03-25 16:21:06 OpenClash Can Not Start, Please Check The Error Info And Try Again
time="2020-03-25T16:37:51Z" level=fatal msg="Parse config error: yaml: line 30: mapping values are not allowed in this context"
2020-03-25 16:36:39 OpenClash Can Not Start, Please Check The Error Info And Try Again

**Comment by vernesong** [comment]
配置文件15行的上下内容

**Comment by zelbloo** [comment]
> 配置文件15行的上下内容
第十行到第二十一行
ignore-resolve-fail: true
redir-port: 7892
secret: "123456"
external-ui: "/usr/share/openclash/dashboard"
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  listen: 0.0.0.0:7874
  nameserver:
  - 114.114.114.114

**Comment by vernesong** [comment]
把这些全删了，直接重启

**Comment by zelbloo** [comment]
goroutine 1 [running]:
runtime.asyncPreempt()
	/usr/lib/go-1.14/src/runtime/preempt_mipsx.s:40 +0x7c fp=0xc39bec sp=0xc39af8 pc=0x87fb4
gopkg.in/yaml%2ev2.yaml_parser_fetch_more_tokens(0xc62480, 0xc62501)
	/home/vernesong/go/pkg/mod/gopkg.in/yaml.v2@v2.2.8/scannerc.go:635 +0xc8 fp=0xc39c08 sp=0xc39bf0 pc=0x3811a0
gopkg.in/yaml%2ev2.peek_token(...)
	/home/vernesong/go/pkg/mod/gopkg.in/yaml.v2@v2.2.8/parserc.go:47
gopkg.in/yaml%2ev2.yaml_parser_parse_indentless_sequence_entry(0xc62480, 0xc62588, 0x36fc38)
	/home/vernesong/go/pkg/mod/gopkg.in/yaml.v2@v2.2.8/parserc.go:640 +0x344 fp=0xc39cec sp=0xc39c08 pc=0x379e64
gopkg.in/yaml%2ev2.yaml_parser_state_machine(0xc62480, 0xc62588, 0x401)
	/home/vernesong/go/pkg/mod/gopkg.in/yaml.v2@v2.2.8/parserc.go:128 +0x2a0 fp=0xc39d00 sp=0xc39cec pc=0x3768d8
gopkg.in/yaml%2ev2.yaml_parser_parse(0xc62480, 0xc62588, 0xec6001)
	/home/vernesong/go/pkg/mod/gopkg.in/yaml.v2@v2.2.8/parserc.go:72 +0xb4 fp=0xc39d10 sp=0xc39d00 pc=0x376600
gopkg.in/yaml%2ev2.(*parser).peek(0xc62480, 0xec1f00)
	/home/vernesong/go/pkg/mod/gopkg.in/yaml.v2@v2.2.8/decode.go:105 +0x54 fp=0xc39d20 sp=0xc39d10 pc=0x36f00c
gopkg.in/yaml%2ev2.(*parser).sequence(0xc62480, 0xe97c07)
	/home/vernesong/go/pkg/mod/gopkg.in/yaml.v2@v2.2.8/decode.go:205 +0x9c fp=0xc39d54 sp=0xc39d20 pc=0x36fc18
gopkg.in/yaml%2ev2.(*parser).parse(0xc62480, 0xe97cc0)
	/home/vernesong/go/pkg/mod/gopkg.in/yaml.v2@v2.2.8/decode.go:151 +0x20c fp=0xc39d7c sp=0xc39d54 pc=0x36f488
gopkg.in/yaml%2ev2.(*parser).mapping(0xc62480, 0x9)
	/home/vernesong/go/pkg/mod/gopkg.in/yaml.v2@v2.2.8/decode.go:217 +0xd4 fp=0xc39db4 sp=0xc39d7c pc=0x36feac
gopkg.in/yaml%2ev2.(*parser).parse(0xc62480, 0xc49003)
	/home/vernesong/go/pkg/mod/gopkg.in/yaml.v2@v2.2.8/decode.go:149 +0x1e4 fp=0xc39ddc sp=0xc39db4 pc=0x36f460
gopkg.in/yaml%2ev2.(*parser).document(0xc62480, 0x3)
	/home/vernesong/go/pkg/mod/gopkg.in/yaml.v2@v2.2.8/decode.go:175 +0xb4 fp=0xc39e0c sp=0xc39ddc pc=0x36f608
gopkg.in/yaml%2ev2.(*parser).parse(0xc62480, 0x0)
	/home/vernesong/go/pkg/mod/gopkg.in/yaml.v2@v2.2.8/decode.go:153 +0x180 fp=0xc39e34 sp=0xc39e0c pc=0x36f3fc
gopkg.in/yaml%2ev2.unmarshal(0xe00000, 0x6b365, 0x6b565, 0x4802a0, 0xc0c860, 0x438800, 0x0, 0x0)
	/home/vernesong/go/pkg/mod/gopkg.in/yaml.v2@v2.2.8/yaml.go:142 +0x22c fp=0xc39e84 sp=0xc39e34 pc=0x39062c
gopkg.in/yaml%2ev2.Unmarshal(...)
	/home/vernesong/go/pkg/mod/gopkg.in/yaml.v2@v2.2.8/yaml.go:81
github.com/Dreamacro/clash/config.UnmarshalRawConfig(0xe00000, 0x6b365, 0x6b565, 0x0, 0xc54b60, 0x4ee167)
	/home/vernesong/home/clash/config/config.go:168 +0x278 fp=0xc39eb0 sp=0xc39e84 pc=0x42a94c
github.com/Dreamacro/clash/config.Parse(0xe00000, 0x6b365, 0x6b565, 0x6b365, 0x6b565, 0x0)
	/home/vernesong/home/clash/config/config.go:126 +0x4c fp=0xc39ecc sp=0xc39eb0 pc=0x42a670
github.com/Dreamacro/clash/hub/executor.ParseWithBytes(...)
	/home/vernesong/home/clash/hub/executor/executor.go:75
github.com/Dreamacro/clash/hub/executor.ParseWithPath(0x7fd9cf87, 0x1c, 0xc, 0x7582700, 0x1080a4)
	/home/vernesong/home/clash/hub/executor/executor.go:70 +0x90 fp=0xc39eec sp=0xc39ecc pc=0x4388a0
github.com/Dreamacro/clash/hub/executor.Parse(...)
	/home/vernesong/home/clash/hub/executor/executor.go:60
github.com/Dreamacro/clash/hub.Parse(0x7fd9cf75, 0xe)
	/home/vernesong/home/clash/hub/hub.go:10 +0x50 fp=0xc39f0c sp=0xc39eec pc=0x452134
main.main()
	/home/vernesong/home/clash/main.go:74 +0x2e4 fp=0xc39fc0 sp=0xc39f0c pc=0x4527a4
runtime.main()
	/usr/lib/go-1.14/src/runtime/proc.go:203 +0x284 fp=0xc39fec sp=0xc39fc0 pc=0x4f9ec
runtime.goexit()
	/usr/lib/go-1.14/src/runtime/asm_mipsx.s:651 +0x4 fp=0xc39fec sp=0xc39fec pc=0x87834

goroutine 6 [chan receive]:
github.com/Dreamacro/clash/common/observable.(*Observable).process(0xc52aa0)
	/home/vernesong/home/clash/common/observable/observable.go:16 +0xe4
created by github.com/Dreamacro/clash/common/observable.NewObservable
	/home/vernesong/home/clash/common/observable/observable.go:63 +0xa4

goroutine 7 [select]:
gopkg.in/eapache/channels%2ev1.(*InfiniteChannel).infiniteBuffer(0xc0a220)
	/home/vernesong/go/pkg/mod/gopkg.in/eapache/channels.v1@v1.1.0/infinite_channel.go:49 +0x120
created by gopkg.in/eapache/channels%2ev1.NewInfiniteChannel
	/home/vernesong/go/pkg/mod/gopkg.in/eapache/channels.v1@v1.1.0/infinite_channel.go:19 +0x160

goroutine 8 [select]:
gopkg.in/eapache/channels%2ev1.(*InfiniteChannel).infiniteBuffer(0xc0a230)
	/home/vernesong/go/pkg/mod/gopkg.in/eapache/channels.v1@v1.1.0/infinite_channel.go:49 +0x120
created by gopkg.in/eapache/channels%2ev1.NewInfiniteChannel
	/home/vernesong/go/pkg/mod/gopkg.in/eapache/channels.v1@v1.1.0/infinite_channel.go:19 +0x160

goroutine 9 [select]:
github.com/Dreamacro/clash/tunnel.(*Manager).handleCh(0xc70280, 0xc462c0, 0xc702a0, 0xc702b0, 0xc702c0)
	/home/vernesong/home/clash/tunnel/manager.go:81 +0xd4
created by github.com/Dreamacro/clash/tunnel.(*Manager).handle
	/home/vernesong/home/clash/tunnel/manager.go:74 +0x70

goroutine 10 [select]:
github.com/Dreamacro/clash/tunnel.(*Manager).handleCh(0xc70280, 0xc46300, 0xc702a8, 0xc702b8, 0xc702c8)
	/home/vernesong/home/clash/tunnel/manager.go:81 +0xd4
created by github.com/Dreamacro/clash/tunnel.(*Manager).handle
	/home/vernesong/home/clash/tunnel/manager.go:75 +0xb4

goroutine 11 [chan receive]:
github.com/Dreamacro/clash/tunnel.process()
	/home/vernesong/home/clash/tunnel/tunnel.go:126 +0x118
created by github.com/Dreamacro/clash/tunnel.init.1
	/home/vernesong/home/clash/tunnel/tunnel.go:42 +0x44

goroutine 17 [chan receive]:
github.com/Dreamacro/clash/tunnel.processUDP()
	/home/vernesong/home/clash/tunnel/tunnel.go:110 +0x70
created by github.com/Dreamacro/clash/tunnel.process
	/home/vernesong/home/clash/tunnel/tunnel.go:122 +0x70

goroutine 18 [chan receive]:
github.com/Dreamacro/clash/tunnel.processUDP()
	/home/vernesong/home/clash/tunnel/tunnel.go:110 +0x70
created by github.com/Dreamacro/clash/tunnel.process
	/home/vernesong/home/clash/tunnel/tunnel.go:122 +0x70

goroutine 19 [chan receive]:
github.com/Dreamacro/clash/tunnel.processUDP()
	/home/vernesong/home/clash/tunnel/tunnel.go:110 +0x70
created by github.com/Dreamacro/clash/tunnel.process
	/home/vernesong/home/clash/tunnel/tunnel.go:122 +0x70

goroutine 20 [chan receive]:
github.com/Dreamacro/clash/tunnel.processUDP()
	/home/vernesong/home/clash/tunnel/tunnel.go:110 +0x70
created by github.com/Dreamacro/clash/tunnel.process
	/home/vernesong/home/clash/tunnel/tunnel.go:122 +0x70

r0   0x0	r1   0x400
r2   0x14	r3   0xc62480
r4   0xc1a3c0	r5   0x1
r6   0x4a6c80	r7   0x4c
r8   0x1	r9   0x0
r10  0x2	r11  0x0
r12  0x0	r13  0x0
r14  0x1	r15  0x1
r16  0x2d	r17  0xd
r18  0xcf	r19  0x0
r20  0x0	r21  0x0
r22  0x53de94	r23  0x890000
r24  0x93f	r25  0x2
r26  0x0	r27  0x0
r28  0xc723f0	r29  0xc39af8
r30  0xc000e0	r31  0x3811a0
pc   0x87fb4	link 0x3811a0
lo   0x0	hi   0x0
2020-03-26 16:50:45 OpenClash Can Not Start, Please Check The Error Info And Try Again

**Comment by vernesong** [comment]
还有30行附近的，你看下写的什么

**Comment by zelbloo** [comment]
![image](https://user-images.githubusercontent.com/7335235/77775116-1301c380-7087-11ea-8b90-699bf183595e.png)

**Comment by zelbloo** [comment]
做过几个尝试：
1、删除DNS配置
2、删除Emoji
3、使用Clash配置订阅
4、使用Surge配置订阅
都无法启动，最终的报错都指向 golang/go#37667

尝试退回到2月份的版本，可以成功启动

**Comment by vernesong** [comment]
这个错误我在mips上测试已经修复，你使用如果会编译的话可以尝试使用未压缩的版本
