### ISSUE TITLE
[Feature] 希望可以修改fakeip网段

### ISSUE THREAD

**Issue by yjps** [vernesong/OpenClash#2800]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

![image](https://user-images.githubusercontent.com/32375607/200494148-f677b22b-0963-40fe-8515-b97ee3692975.png)
我的dns服务是mosdns，因为公司流量很大，我需要用dns进行多个openwrt上openclash fakeip的分流。
当我想把openclash_1的fakeip设为10.1.0.1/16，openclash_2的fakeip设为10.2.0.1/16时，我发现yaml文件的配置无法生效。

### Describe the Solution

希望openclash可以修改fakeip的网段。

**Comment by machine-doll** [comment]
我感觉这可能是上游的问题，不知道有没有人试过clash meta是不是支持修改fake ip的网段
