### ISSUE TITLE
Hysteria [端口跳跃/多端口](Port Hopping)[Feature] 

### ISSUE THREAD

**Issue by Job28703** [vernesong/OpenClash#2804]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

长时间单端口 UDP 连接容易被运营商封锁/QoS 的问题

### Describe the Solution

封锁/QoS 的问题。
clash_meta 的客户端都没有很好的支持这一功能

### Describe Alternatives

Hysteria 修改 UDP
设置udp链接自动过期时间，
然后会话平滑转移到新链接，
然后就可以避免某个链接被qos

### Additional Context

clash_meta 的客户端
Hysteria 修改 UDP

**Comment by skill7899** [comment]
提错地方了吧，应该去clash_meta那边提

**Comment by Job28703** [comment]
clash_meta 在那？
有连网址吗？

**Comment by skill7899** [comment]
> clash_meta 在那？ 有连网址吗？

直接github搜就可以了
https://github.com/MetaCubeX/Clash.Meta

**Comment by Job28703** [comment]
感謝！！
