### ISSUE TITLE
[Bug] 重启 WAN 导致 Fallback 偶现无法解析

### ISSUE THREAD

**Issue by FanxJK** [vernesong/OpenClash#2807]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.70

### Bug on Environment

Lean

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

重启 WAN 口

### Describe the Bug

v0.45.70 重启 WAN 导致 Fallback 偶现无法解析，时间越久无法解析的问题越严重
相关: https://github.com/Dreamacro/clash/issues/2313

### OpenClash Log

******
*** all DNS requests failed ***
*****

### OpenClash Config

```shell
dns:
  enhanced-mode: fake-ip
  use-hosts: true
  nameserver:
  - 119.29.29.29
  - 223.5.5.5
  fallback:
  - tls://8.8.8.8:853
  - https://8.8.8.8/dns-query
  - tls://1.1.1.1:853
  - https://1.1.1.1/dns-query
  enable: true
  ipv6: false
  fake-ip-range: 198.18.0.1/16
  listen: 0.0.0.0:7874
  default-nameserver:
  - 119.29.29.29
  - 223.5.5.5
  fake-ip-filter:
  - "+.*"
```

### Expected Behavior

使用 #1689 中的修改 /etc/init.d/openclash
```
https://github.com/vernesong/OpenClash/issues/1689#issuecomment-938600532
/etc/init.d/openclash 翻到最底下reload函数改成
reload()
{
    restart
}
```
解决问题

希望修复 WAN 重启后的 reload

**Comment by vernesong** [comment]
DNS没法用还是什么

**Comment by FanxJK** [comment]
> DNS没法用还是什么

和 https://github.com/Dreamacro/clash/issues/2313 一样，dns正常使用，但是走fallback的无法解析，另外我今天经过一天的使用发现修改reload为restart能缓解，但依然会偶现此问题

**Comment by FanxJK** [comment]
> 这个问题不好解决，不知道原因，换换固件呢

更换固件为自编译lede，已无此问题
