### ISSUE TITLE
openclash不能随openwrt自动启动

### ISSUE THREAD

**Issue by lichuncat** [vernesong/OpenClash#281]
控制面板里选设置，“开机时启动”开关不能打开，重启openwrt，openwrt不能自动启动。

**Comment by vernesong** [comment]
控制面板那个开关不是给linux用的，如果你在重启之前openclash是启动状态，那么重启后无法启动的原因我还需要观察一下

**Comment by lichuncat** [comment]
可能是openwrt版本的问题，恩山“lusty”版本不行，换了"智能超神者"版本，就没问题
