### ISSUE TITLE
[Bug] urlencode函数返回空导致第三方规则更新了错误的内容

### ISSUE THREAD

**Issue by wxy1343** [vernesong/OpenClash#2811]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.70-beta

### Bug on Environment

Lean

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

`游戏规则列表`或`第三方规则集列表`点击更新规则

### Describe the Bug

https://github.com/vernesong/OpenClash/blob/e475a5d3bc05fdf60ab1c8d24432122684451701/luci-app-openclash/root/usr/share/openclash/openclash_download_rule_list.sh#L5-L13
`curl`执行完没有任何输出
https://github.com/vernesong/OpenClash/blob/e475a5d3bc05fdf60ab1c8d24432122684451701/luci-app-openclash/root/usr/share/openclash/openclash_download_rule_list.sh#L8
`DOWNLOAD_PATH`被赋予空值
https://github.com/vernesong/OpenClash/blob/e475a5d3bc05fdf60ab1c8d24432122684451701/luci-app-openclash/root/usr/share/openclash/openclash_download_rule_list.sh#L67

### OpenClash Log

***

### Expected Behavior

---

### Screenshots

![image](https://user-images.githubusercontent.com/49909001/201487249-d5197621-9c72-4527-a2d8-6639b3f2d7d3.png)

**Comment by vernesong** [comment]
你curl正常吗

**Comment by wxy1343** [comment]
> 你curl正常吗

其它功能都是正常的
```shell
root@OpenWrt:~# curl --version
curl 7.86.0 (x86_64-openwrt-linux-gnu) libcurl/7.86.0 mbedTLS/2.28.1 nghttp2/1.44.0
Release-Date: 2022-10-26
Protocols: file ftp ftps http https mqtt
Features: alt-svc HSTS HTTP2 IPv6 Largefile SSL threadsafe
```

**Comment by vernesong** [comment]
curl -sS -o /dev/null -w %{url_effective} --get --data-urlencode "key=TEST" ""

**Comment by wxy1343** [comment]
> curl -sS -o /dev/null -w %{url_effective} --get --data-urlencode "key=TEST" ""

![image](https://user-images.githubusercontent.com/49909001/201515826-9de6a38c-2b35-4ac8-b928-e0f3492f3fef.png)

**Comment by vernesong** [comment]
curl -sS -o /dev/null -w %{url_effective}  "www.baidu.com"

**Comment by wxy1343** [comment]
> curl -sS -o /dev/null -w %{url_effective} "www.baidu.com"

![image](https://user-images.githubusercontent.com/49909001/201516492-a1de6bbd-8248-40f2-93f0-50a8fb7b821f.png)

**Comment by wxy1343** [comment]
应该是更新curl后出现的问题，旧版本正常

**Comment by mouseroser** [comment]
[https://github.com/vernesong/OpenClash/issues/2799#issue-1439435989](url)，已给出解决方案且已通过验证

使用以下代码替换原有urlencode() 代码即可：

urlencode() { 
    local string="${1}"
    local strlen=${#string}
    local encoded=""
    local pos c o

    for (( pos=0 ; pos<strlen ; pos++ )); do
       c=${string:$pos:1}
       case "$c" in
       [-_.~a-zA-Z0-9] ) o="${c}" ;;
       * ) printf -v o '%%%02x' "'$c"
       esac
       encoded+="${o}"
   done

   echo "${encoded}" # You can either set a return variable (FASTER)
   REPLY="${encoded}" #+or echo the result (EASIER)... both... :p
}

**Comment by mouseroser** [comment]
> 应该是更新curl后出现的问题，旧版正常，已经测试`v7.86.0`出现该问题

已在楼上给出解决方案

**Comment by abc9878** [comment]
> [https://github.com/vernesong/OpenClash/issues/2799#issue-1439435989](url)，已给出解决方案且已通过验证，curl及openclash均使用最新版本
> 
> 在不回滚curl 7.86.0之前版本解决方案如下： vim /usr/share/openclash/openclash.sh 39行，使用以下代码替换原有urlencode()方法代码即可：
> 
> ```
> urlencode() { 
>     local string="${1}"
>     local strlen=${#string}
>     local encoded=""
>     local pos c o
> 
>     for (( pos=0 ; pos<strlen ; pos++ )); do
>        c=${string:$pos:1}
>        case "$c" in
>        [-_.~a-zA-Z0-9] ) o="${c}" ;;
>        * ) printf -v o '%%%02x' "'$c"
>        esac
>        encoded+="${o}"
>    done
> 
>    echo "${encoded}" # You can either set a return variable (FASTER)
>    REPLY="${encoded}" #+or echo the result (EASIER)... both... :p
> }
> ```

额，排除节点失效了

**Comment by vernesong** [comment]
dev
