### ISSUE TITLE
[Bug] No Armv8 Compiled Version?

### ISSUE THREAD

**Issue by SuperCoolDude** [vernesong/OpenClash#2819]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.71

### Bug on Environment

Official OpenWrt

### Bug on Platform

Other

### To Reproduce

https://raw.githubusercontent.com/vernesong/OpenClash/master/core-lateset/dev/clash-linux-armv8.tar.gz

This doesn't update any longer and the file doesn't exist.

### Describe the Bug

https://raw.githubusercontent.com/vernesong/OpenClash/master/core-lateset/dev/clash-linux-armv8.tar.gz

I can no longer get the update from here, is this no longer supported? This was the default version on R4S version of OpenClash on OpenWRT.

### OpenClash Log

4M7g5$FX*T$a5^jL

### Expected Behavior

Update

**Comment by TDL3** [comment]
armv8 has been renamed to arm64, you can manually select it under the drop-down list
