### ISSUE TITLE
抛砖引玉：关于 OpenClash 打游戏的部分见解

### ISSUE THREAD

**Issue by mephisX** [vernesong/OpenClash#282]
# 众所周知： 
    OpenClash TUN REAL-IP 模式，可以实现 NAT 1。
    Clash For Windows TUN REAL-IP 模式，亦可以实现 NAT 1。
### 测试游戏1：Call of Duty: Modern Warfare
只需要在规则中加上：
```
DOMAIN-SUFFIX,demonware.net
```
指向韩国或者新加坡服务器即可正常游戏。
### 测试游戏2：Counter-Strike: Global Offensive
在规则末尾加上以下规则
```
SelectSGP,[]GEOIP,SG
SelectJP,[]GEOIP,JP
SelectKR,[]GEOIP,KR
SelectTW,[]GEOIP,TW
SelectHK,[]GEOIP,HK
```
游戏中无缝切换港服日服亚服。

由于精力有限，只测试了这两个游戏。
```
游戏规则与策略组管理
```
这个功能我觉得可以更新一下。

**Comment by vernesong** [comment]
因为存在游戏节点倍率的情况，geoip规则不太适合游戏用

**Comment by mephisX** [comment]
> 因为存在游戏节点倍率的情况，geoip规则不太适合游戏用

切换规则也不是太麻烦吧？而且现在规则的完善度，用到 geoip 的情况一般都是只有游戏了。

**Comment by YukawaMi** [comment]
TUN内核就可以吗，我之前用的原版内核不行，回去试试TUN内核。。。

**Comment by Gxcel** [comment]
请问 cfw 怎么做到 NAT1 啊？我 fake-ip 是严格，redir-host 也只能到中等，怎么才能到公开类型？openclash 我老安装不上，想着用 cfw

**Comment by lddsb** [comment]
我Switch的NAT只能到F，你们NAT这么优秀的是设置了HTTP代理吗？我是直接设置网关和DNS为旁路由

**Comment by vernesong** [comment]
服务器没问题的话，使用redir模式开启udp转发或者tun和游戏模式，用`- SRC-IP-CIDR,192.168.1.201/32,策略组名字`让机子完全走代理

**Comment by lddsb** [comment]
> 服务器没问题的话，使用redir模式开启udp转发或者tun和游戏模式，用`- SRC-IP-CIDR,192.168.1.201/32,策略组名字`让机子完全走代理

点赞。换了个ss的节点然后加上这个让Switch全部走代理之后NAT变A了。

**Comment by muink** [comment]
需要在proxies开启udp: true吗 @mephisX
