### ISSUE TITLE
[Feature] 异步加载

### ISSUE THREAD

**Issue by huajideshutiao** [vernesong/OpenClash#2825]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

如题，现在打开状态页和启动clash时太慢了

### Describe the Solution

比如同时重启防火墙和dns

**Comment by aimai-who** [comment]
启动慢我觉得可以接受，但是期望加载状态能够快一点。

**Comment by huajideshutiao** [comment]
> 

确实
我现在换了软路由，经常core启动了概览还在获取信息
