### ISSUE TITLE
[Bug]随OpenWrt启动后在Fake-IP模式下“绕过大陆IP”不生效，nslookup仍然获取fake ip

### ISSUE THREAD

**Issue by Hiibu** [vernesong/OpenClash#2829]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.16-beta

### Bug on Environment

Official OpenWrt, Lean

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

OpenClash随Openwrt启动后，在FAKE-IP模式下绕过大陆IP不生效，用过nslookup测试，国内网址仍然是fakeip。手动取消“绕过大陆IP”-应用配置，再重新勾选“绕过大陆IP”-应用配置后，重新使用nslookup命令就可以获得真实IP了。而单纯的重新启动OpenClash不起作用。

### Describe the Bug

自启动后在Fake-IP模式下“绕过大陆IP”不生效。

### OpenClash Log

没有相关日志

### Expected Behavior

自启动后可正确绕过大陆IP。

**Comment by love4taylor** [comment]
具体代码没看，但逻辑上 fake-ip 的绕过大陆 IP 应该是指裸 IP 连接的情况，如果你希望 fake-ip 获得真实 IP 为什么不用redir-host 加开启远程域名解析（开了这个本质上就是 fake-ip + 在 fake-ip-filter 里通配所有域名而实现真实 IP）

**Comment by 7revor** [comment]
同样遇到这个问题，开机自启的clash绕过大陆ip不会生效，所有流量都会走clash，并且ping任何域名都返回保留地址。手动重启clash后恢复正常。

**Comment by machine-doll** [comment]
我最近也遇到了这个问题。这几天软路由的系统崩了，重装了一下系统，再用openclash就遇到了很多问题。  
我是无论怎么弄，也还是只会返回保留地址。ssh连接到软路由，/tmp/dnsmasq里有对应的文件，但是似乎dnsmasq没有加载这些文件

**Comment by onecombo** [comment]
mark，同样问题

**Comment by machine-doll** [comment]
发现似乎和依赖有关系。这个功能可能是依赖一些iptables的组件以及kmod，但是默认安装插件的时候，并不会安装这些依赖。而软件运行的时候也不会提示用户去安装这些依赖  
还有一个可能就是自己的访问控制规则里面有使用CIDR的网段的，这点不是很清楚，不知道dnsmasq到底是怎么处理的，有可能是处理CIDR的时候出现了问题
