### ISSUE TITLE
大大请教:电脑开启代理后,3389远程桌面无法通过外网连接,3389是通过端口映射到其他端口进行远程连接的.

### ISSUE THREAD

**Issue by Zikosyo** [vernesong/OpenClash#283]
请教:
开启代理后,电脑3389远程桌面无法通过外网连接,电脑代理上网正常.
3389是通过端口映射到其他端口进行远程连接的.关闭代理后,远程连接正常.
有什么方法在开启代理后,电脑能正常进行远程桌面连接?
谢谢!

**Comment by vernesong** [comment]
端口映射在哪台机器设置的

**Comment by Zikosyo** [comment]
端口映射是在主路由上做的端口转发，主路由IP：192.168.2.1
电脑是用的op旁路由的方式实现的代理，开启代理后，远程桌面在不断开情况下，能保持连接，断开之后就无法远程连接了，关闭代理后，恢复正常。
感谢回复指点！

**Comment by Zikosyo** [comment]
端口映射是在主路由上做的端口转发，主路由IP：192.168.2.1
电脑是用op旁路由的方式实现代理，开启代理后，远程桌面在断开的情况下，能保持连接，断开之后就无法远程连接了，关闭代理后，恢复正常。
感谢回复指点！

**Comment by vernesong** [comment]
两种方法
第一种是绕过来自于端口3389的流量，不让他进入nat，启动后执行以下命令
tcp
https://github.com/vernesong/OpenClash/blob/72fe5f97d272b0fe6ff2ec6628951a1eb73067ce/luci-app-openclash/files/etc/init.d/openclash#L812
`iptables -t nat -A openclash -p tcp --sport 3389 -j RETURN'tcp
udp
https://github.com/vernesong/OpenClash/blob/72fe5f97d272b0fe6ff2ec6628951a1eb73067ce/luci-app-openclash/files/etc/init.d/openclash#L837

'iptables -t mangle -A openclash -p tcp -- sport 3389 -j RETURN'

第二种
主路由端口转发到旁路由，旁路由再转发到3389

**Comment by Zikosyo** [comment]
用第二种方法解决问题。
感谢大大能抽空指点，谢谢！

**Comment by sheiy** [comment]
同一台机器我主路由映射到客户机ip的非3389比如qittorrent的8080端口外网能访问 3389端口就不行

**Comment by sheiy** [comment]
@vernesong

**Comment by rainbowshine521** [comment]
> 用第二种方法解决问题。
> 感谢大大能抽空指点，谢谢！

@Zikosyo @vernesong 请问具体是怎么配置呀？

**Comment by vernesong** [comment]
> > 用第二种方法解决问题。
> 
> > 感谢大大能抽空指点，谢谢！
> 
> 
> 
> @Zikosyo @vernesong 请问具体是怎么配置呀？

主路由转发到旁路由上的端口，旁路由再lan to lan转发到内网主机

**Comment by homerxie** [comment]
大大，能请教一下吗，我尝试在ikuai主路由中将的外网端口9999转发到openwrt旁路由（192.168.1.1）的100端口，然后再在openwrt里把自己的100端口转发给pc的3389端口，但还是不行，能帮我看看是哪里的问题吗？感激不尽。不知道openwrt的这个100端口是否需要手动打开呢？还是这样子就可以了？
![image](https://user-images.githubusercontent.com/39032393/93191127-c3b76880-f776-11ea-8d6a-c7eaa559dbe5.png)
![image](https://user-images.githubusercontent.com/39032393/93191495-2a3c8680-f777-11ea-879f-435bac93f449.png)

**Comment by livebelive** [comment]
> 

跟你一样的操作 按照V大的第二方法设置了 但是依然无法连接...百度有人提供了一个思路说 端口转发不生效 就用自定义规则 但提供的那条命令 貌似有地方要改 不知道怎么改。。。
iptables -t nat -I PREROUTING -i pppoe-wan -p tcp --dport 8000 -j DNAT --to-destination 192.168.2.1:80
就是这条 看样子是改8000和后面的IP:端口 但改完 还是连接不了 我看他前面使用的是pppoe-wan 应该不是lan->lan方式 求有人帮忙 不胜感激！

**Comment by livebelive** [comment]
另外 我做了 DDNS 做了 NGINX的反代 只要一开启clash 除了openwrt自身 使用外网IP+端口可以访问 其他服务 包括 3389的远程 各种端口映射的服务！全部都访问不了...使用外网IP、域名都不行...有没有办法设置某个局域网IP的某个端口服务 不走clash，和某个域名排除在外呢？

**Comment by livebelive** [comment]
而且 我将开启服务的主机 网关设置成主路由 开启openclash后 一样无法访问...

**Comment by JefferWong** [comment]
可以尝试修改远程桌面使用的端口，自定义端口号来解决
