### ISSUE TITLE
[Bug] 安装OpenClash后报错

### ISSUE THREAD

**Issue by AkarinLiu** [vernesong/OpenClash#2837]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.70-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-arm64

### To Reproduce

我上传了安装包到Openwrt设备，然后点击安装，安装完成后就报错了

### Describe the Bug

安装后页面报错

### OpenClash Log

![image](https://user-images.githubusercontent.com/58081491/203228744-f70a61bc-a0fd-4f17-839e-2310afc7467c.png)

### Expected Behavior

没有

**Comment by Jejz168** [comment]
直接安装不行吧。依赖不全

**Comment by Ayase-chan** [comment]
opkg安装luci-compact试试
