### ISSUE TITLE
[Bug] 惊天bug，如图所示

### ISSUE THREAD

**Issue by Sincejunly** [vernesong/OpenClash#2839]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.70-beta

### Bug on Environment

Lean

### Bug on Platform

Linux-armv7

### To Reproduce

自动出现,已无法复现

### Describe the Bug

DNS解析出问题，乐

### OpenClash Log

打开了所有第三方规则，日志遗失
[log.txt](https://github.com/vernesong/OpenClash/files/10072527/log.txt)

### Expected Behavior

了解，无所谓我可以换内核反正

### Screenshots

![123](https://user-images.githubusercontent.com/96775034/203460134-61e08fc6-fba0-4487-92fe-4720a6cd3c58.png)

**Comment by Sincejunly** [comment]
我记得开tun或者混合模式，也有可能不是meta记不清了

**Comment by Sincejunly** [comment]
只有b站 会这样，别的不会

**Comment by oyhngithub** [comment]
+1 遇到数十次了 :(
![1](https://user-images.githubusercontent.com/32537123/204077574-45381350-4c4a-43bd-8ef3-cb9ae8b1bf88.png)

**Comment by WangONC** [comment]
这个问题我也遇到过

**Comment by machine-doll** [comment]
这个问题不知道是不是clash甚至v2ray本身的问题，因为我有时候也会遇到。有时候是一个网站的IP被解析成另一个网站的IP了  
好像SSR时代，有时候就会这样。有时候重启梯子、清除DNS缓存会好。小概率事件  
另外，fake-ip模式，出现解析乱套的概率感觉大不少

**Comment by kingsey** [comment]
在很久很久以前出现过一次，然后就没见过了
