### ISSUE TITLE
服务器与策略组管理-读取配置-服务器节点配置为空

### ISSUE THREAD

**Issue by rookiealex** [vernesong/OpenClash#284]
更新v0.37.1-beta后，读取配置文件的节点，只有格式如下的才能读取到

- name: "vmess"
  type: vmess
  server: server
  port: 443
  uuid: uuid
  alterId: 32
  cipher: auto
  udp: true
  tls: true
  skip-cert-verify: true
  network: ws
  ws-path: /path
  ws-headers:
     Host: v2ray.com`

格式如下的以前能读取到，更新后读取不到
- {"name":"name","type":"vmess","server":"server","port":443,"uuid":"uuid","alterId":32,"cipher":"auto","udp":true,"network":"ws","ws-path":"/","ws-headers":{"Host":"v2ray.com"}}

![1](https://user-images.githubusercontent.com/62787175/77817280-b47b2a80-7104-11ea-8095-612ddd33414a.PNG)

**Comment by vernesong** [comment]
因为有双引号的缘故，json数据读取关键字有bug，会在下版本修复
