### ISSUE TITLE
[Feature] 开启绕过大陆模式后国内ip reject失效

### ISSUE THREAD

**Issue by MaoSuSu** [vernesong/OpenClash#2841]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

如题

### Describe the Solution

个人理解：绕过模式是将国内ip通通不经过内核处理，导致国内ip reject失效。
个人猜想：能否在设置绕过模式时先一步将配置文件中的reject规则的优先级提高呢？既保证了reject的规则，又不失绕过的特性？

**Comment by skill7899** [comment]
感觉不行，一旦进行了reject规则就是进到了clash，绕过的模式就是不经过clash直走。

**Comment by LovelyToaster** [comment]
应该不行，把reject的网站重定向到0.0.0.0吧

**Comment by MaoSuSu** [comment]
首先感谢各位的热心回复

**Comment by MaoSuSu** [comment]
很感谢各位的热心回复
那能否这样呢，在启用绕过大陆模式时，openclash将reject的相关规则写入host中，变通的实现
个人之前在测试时发现，当启用fakeip绕过时，广告屏蔽大师plus+的拦截效果就失效了

**Comment by paladin4fan** [comment]
> 能否这样呢，在启用绕过大陆模式时，o

那不如你自己把这部分写成dnsmasq的list
或者图方便用adguardhome接管你的DNS 先做过滤再喂给openclash

**Comment by MaoSuSu** [comment]
> > 能否这样呢，在启用绕过大陆模式时，o
> 
> 那不如你自己把这部分写成dnsmasq的list 或者图方便用adguardhome接管你的DNS 先做过滤再喂给openclash

手动配置dnsmasq可行，openclash如果能自动将reject规则写入dnsmasq中就好了
