### ISSUE TITLE
[Bug] openwrt后台大量ping进程

### ISSUE THREAD

**Issue by btbai007** [vernesong/OpenClash#2842]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.70-225

### Bug on Environment

Lean

### Bug on Platform

Linux-arm64

### To Reproduce

服务器&策略组管理中存在ping不通的服务器,随着进入次数后台ping进程会不断增加

### Describe the Bug

30485 root      1144 S    sh -c ping -c 1 -W 1 "hk02.iplcserver.com" 2>&1 | grep -o 'time=[0-9]*.[0-9]' | awk -F '=' '{print$2}'
30486 root      1140 S    ping -c 1 -W 1 hk02.iplcserver.com
30487 root      1144 S    grep -o time=[0-9]*.[0-9]
30488 root      1148 S    awk -F = {print$2}
30492 root      1144 S    sh -c ping -c 1 -W 1 "sg03.iplcserver.com" 2>&1 | grep -o 'time=[0-9]*.[0-9]' | awk -F '=' '{print$2}'
30493 root      1140 S    ping -c 1 -W 1 sg03.iplcserver.com
30494 root      1144 S    grep -o time=[0-9]*.[0-9]
30495 root      1148 S    awk -F = {print$2}
30528 root      1144 S    sh -c ping -c 1 -W 1 "kr02.iplcserver.com" 2>&1 | grep -o 'time=[0-9]*.[0-9]' | awk -F '=' '{print$2}'
30529 root      1140 S    ping -c 1 -W 1 kr02.iplcserver.com
30530 root      1144 S    grep -o time=[0-9]*.[0-9]
30531 root      1148 S    awk -F = {print$2}
30537 root      1144 S    sh -c ping -c 1 -W 1 "tw03.iplcserver.com" 2>&1 | grep -o 'time=[0-9]*.[0-9]' | awk -F '=' '{print$2}'
30538 root      1140 S    ping -c 1 -W 1 tw03.iplcserver.com
30539 root      1144 S    grep -o time=[0-9]*.[0-9]
30540 root      1148 S    awk -F = {print$2}
30544 root      1144 S    sh -c ping -c 1 -W 1 "jp01.iplcserver.com" 2>&1 | grep -o 'time=[0-9]*.[0-9]' | awk -F '=' '{print$2}'
30545 root      1140 S    ping -c 1 -W 1 jp01.iplcserver.com
30546 root      1144 S    grep -o time=[0-9]*.[0-9]
30547 root      1148 S    awk -F = {print$2}
30640 root      1144 S    sh -c ping -c 1 -W 1 "us02.iplcserver.com" 2>&1 | grep -o 'time=[0-9]*.[0-9]' | awk -F '=' '{print$2}'
30641 root      1140 S    ping -c 1 -W 1 us02.iplcserver.com
30642 root      1144 S    grep -o time=[0-9]*.[0-9]
30643 root      1148 S    awk -F = {print$2}
30648 root      1144 S    sh -c ping -c 1 -W 1 "tr01.iplcserver.com" 2>&1 | grep -o 'time=[0-9]*.[0-9]' | awk -F '=' '{print$2}'
30649 root      1140 S    ping -c 1 -W 1 tr01.iplcserver.com
30650 root      1144 S    grep -o time=[0-9]*.[0-9]
30651 root      1148 S    awk -F = {print$2}
30654 root      1144 S    sh -c ping -c 1 -W 1 "kr02.iplcserver.com" 2>&1 | grep -o 'time=[0-9]*.[0-9]' | awk -F '=' '{print$2}'
30655 root      1140 S    ping -c 1 -W 1 kr02.iplcserver.com
30656 root      1144 S    grep -o time=[0-9]*.[0-9]
30657 root      1148 S    awk -F = {print$2}
32615 root      1144 S    sh -c ping -c 1 -W 1 "ervitypi.gxcvbmj.xyz" 2>&1 | grep -o 'time=[0-9]*.[0-9]' | awk -F '=' '{print$2}'
32616 root      1140 S    ping -c 1 -W 1 ervitypi.gxcvbmj.xyz
32617 root      1144 S    grep -o time=[0-9]*.[0-9]
32618 root      1148 S    awk -F = {print$2}
32624 root      1144 S    sh -c ping -c 1 -W 1 "owevings.omjkgl.xyz" 2>&1 | grep -o 'time=[0-9]*.[0-9]' | awk -F '=' '{print$2}'
32625 root      1140 S    ping -c 1 -W 1 owevings.omjkgl.xyz

### OpenClash Log

与这无关

### OpenClash Config

```shell
与这无关
```

### Expected Behavior

超时退出机制

### Screenshots

与这无关

**Comment by zheshifandian** [comment]
先降50版本

**Comment by Ayase-chan** [comment]
找到luasrc/view下的myip.htm，清空里面的内容，然后输入<html></html>，保存，然后自己重新编译一个，这样就不会有大量ping进程了，代价是首页的IP信息功能缺失
