### ISSUE TITLE
[Bug] 第三方游戏规则无法更新和下载

### ISSUE THREAD

**Issue by btbai007** [vernesong/OpenClash#2849]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.70-225

### Bug on Environment

Lean

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

规则集与策略组管理-第三方游戏规则  列表中的规则下载全部失效。
我研究了一晚上，我说游戏怎么游戏规则就是不生效，重刷固件，重装软件 最后仔细一看文件内容payload:   - 400: Invalid request

### Describe the Bug

显示成功但是文件大小0.0 KB  /etc/openclash/game_rules文件具体内容如下:
payload:   - 400: Invalid request

### OpenClash Log

无

### OpenClash Config

```shell
无
```

### Expected Behavior

无

### Screenshots

无

**Comment by btbai007** [comment]
设置 Github 地址修改依然没有用 日志显示  规则文件【*******】下载成功
但是我把脚本 openclash_download_rule_list.sh curl提取出来执行又可以成功,得到的结果正常.奇怪了。这是哪出问题了。

`curl -SsL --connect-timeout 5 -m 30 --speed-time 15 --speed-limit 1 --retry 2 https://raw.githubusercontent.com/FQrabbit/SSTap-Rule/master/rules/300hero-cn.rules -o /root/300hero-cn.rule 2>&1`

**Comment by qiyuey** [comment]
> 设置 Github 地址修改依然没有用 日志显示 规则文件【*******】下载成功 但是我把脚本 openclash_download_rule_list.sh curl提取出来执行又可以成功,得到的结果正常.奇怪了。这是哪出问题了。
> 
> `curl -SsL --connect-timeout 5 -m 30 --speed-time 15 --speed-limit 1 --retry 2 https://raw.githubusercontent.com/FQrabbit/SSTap-Rule/master/rules/300hero-cn.rules -o /root/300hero-cn.rule 2>&1`

似乎是```urlencode()```将```$DOWNLOAD_PATH```清空了，我尝试手动删除了该方法的内容，临时正常了

**Comment by qiyuey** [comment]
400 应该是由于反向代理被屏蔽的问题？

但是我遇到了另外一个问题，下载 provider 的时候，获得的内容是 206.0KB 的 github 的首页。

经过排查似乎是```urlencode()```将```$DOWNLOAD_PATH```清空了，我尝试手动删除了该方法的内容，临时正常了。

**Comment by vernesong** [comment]
更新dev分支

**Comment by Jejz168** [comment]
> 更新dev分支
什么时候正式版

**Comment by btbai007** [comment]
> 更新dev分支

更新后问题解决。
