### ISSUE TITLE
最新lede版openwrt，安装Openclash 启动失败

### ISSUE THREAD

**Issue by gordonzzl** [vernesong/OpenClash#285]
日志
/etc/rc.common: line 760: nohup: not found
2020-03-28 17:55:00 OpenClash Can Not Start, Please Check The Error Info And Try Again
版本
固件版本 | OpenWrt R20.3.19 / LuCI Master (git-20.087.30210-56fe7ae)
内核版本 | 4.19.108

**Comment by xiaoqq88** [comment]
缺少依赖包，我昨天也是这样的

**Comment by gordonzzl** [comment]
> 普遍依赖包，我昨天也是这样的

缺了哪个依赖包

**Comment by hy4015** [comment]
> > 普遍依赖包，我昨天也是这样的
> 
> 根据旧版本对比发现缺了
> coreutils-nohup
> bash
> curl
> 这个几个依赖，安装好，顺利启动

请问下这个依赖包怎么安装呀，谢谢！
