### ISSUE TITLE
希望服务器与策略组管理的服务器节点管理，能识别ss或trojan的订阅链接

### ISSUE THREAD

**Issue by xpn282** [vernesong/OpenClash#286]
不能识别ss、trojan、v2的订阅链接就太麻烦了，要自己手动一个一个的输入节点。

不能识别订阅链接的话，起码要能识别协议的专属链接嘛，比如trojan://、ss://，希望能加强一下。

支持节点订阅链接的话，直接读取节点信息，不用在手动输入了，在使用“一键生成配置文件”，配置文件就可以直接搞定了，那就多简单啊！

**Comment by xpn282** [comment]
什么时候增加这个功能啊。。。。。。

**Comment by freefrank** [comment]
同求！
