### ISSUE TITLE
[Bug] OpenClash 启动失败, Parse config error: initial rule provider Discord error

### ISSUE THREAD

**Issue by Hugo821** [vernesong/OpenClash#2860]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.70-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

ARM64(找到了更新日志中V8换成64的内容）

### To Reproduce

纯小白，启动openclash后遇到如日志遇到问题

### Describe the Bug

因这个问题不能成功启动openclash(第一次用GitHub提问题尽力了...)

### OpenClash Log

00:58:46 level=fatal msg="Parse config error: initial rule provider Discord error: Get \"https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Discord.yaml\": lookup fastly.jsdelivr.net on [::1]:53: read udp [::1]:51310->[::1]:53: read: connection refused"

类似的还有

00:37:03 level=fatal msg="Parse config error: initial rule provider F1 TV error: Get \"https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/F1%20TV.yaml\": lookup fastly.jsdelivr.net on [::1]:53: read udp [::1]:59100->[::1]:53: read: connection refused"

### Expected Behavior

希望可以正常启动openclash就好，谢谢

**Comment by vernesong** [comment]
先用meta启动一次

**Comment by Hugo821** [comment]
> 先用meta启动一次

请问一下怎么用meta启动...我没找到
