### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by mmeiwenlong** [vernesong/OpenClash#2874]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

45.7.0

### Bug on Environment

Lean

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

![QQ截图20221202181744](https://user-images.githubusercontent.com/44661424/205270843-3e6cb477-aa2c-4991-b801-66aaa50bbb25.png)
这问题咋回事。国内ip

### Describe the Bug

edd

### OpenClash Log

e

### Expected Behavior

ewe

**Comment by vernesong** [comment]
看看控制面板，淘宝走代理了

**Comment by mmeiwenlong** [comment]
> 
![QQ截图20221202191832](https://user-images.githubusercontent.com/44661424/205281650-bf69d728-cad4-4ecb-9155-9661dadeac0e.png)
![QQ截图20221202191845](https://user-images.githubusercontent.com/44661424/205281659-b669c01e-d577-4f78-9628-f1ec6caa39aa.png)
