### ISSUE TITLE
[Feature] 更新机场订阅时需要不覆盖自己的代理集

### ISSUE THREAD

**Issue by Leefurmore** [vernesong/OpenClash#2875]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

我用自己的配置文件，里面定义了Proxy Provider，我所有策略组依赖这个，但每次更新订阅我自己的代理集会被清空，每次都需要重新配置。

### Describe the Solution

希望增加一项更新订阅保留自设的代理集（目前是可以保留策略组的）。

**Comment by vernesong** [comment]
![image](https://user-images.githubusercontent.com/42875168/205299651-27886c0d-48b5-42b3-a954-9ccc951feb3b.png)
先读取配置文件再添加自己的

**Comment by vernesong** [comment]
手动加一次，如果是从配置文件直接读取的可能会认为是订阅配置被删除

**Comment by Leefurmore** [comment]
emm，还是不行。算了，不折腾了，感谢回复
