### ISSUE TITLE
[Bug] 对于链接模式选择部分Wiki描述模糊不清或已经过期

### ISSUE THREAD

**Issue by ttxs25830** [vernesong/OpenClash#2876]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.70-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-amd64-v3(x86-64)

### To Reproduce

无

### Describe the Bug

如图，描述中提到了**游戏模式**，但实际使用中只有**TUN-混合模式**，请问游戏模式是否就指的是TUN-混合模式？如果是的话，可以更新一下wiki么，感谢。

### OpenClash Log

无关

### OpenClash Config

```shell
无关
```

### Expected Behavior

Wiki描述与实际面板一致

### Screenshots

Wiki：
![Wiki Screenshots](https://user-images.githubusercontent.com/57991009/205416580-5402e4d4-8f34-493d-9f57-6fdfb07e1467.PNG)
实际面板：
![Dashbord Screenshots](https://user-images.githubusercontent.com/57991009/205416836-a79b4586-7281-43dd-93c7-44e5be9d5904.PNG)

**Comment by machine-doll** [comment]
我记得这个软件在支持clash meta之前，好像是有个游戏内核的设定，不知道哪个版本给删掉了
