### ISSUE TITLE
自定义上游DNS

### ISSUE THREAD

**Issue by tian-jeff** [vernesong/OpenClash#288]
自定义上游DNS服务器情况下，可以有办法让上游DNS服务器知道哪个客户端发起的DNS查询吗？
现在发生的情况：
1. 在OpenClash的DNS配置页面，配置了上游DNS服务器为另外一个IP的adguard home地址
2. 但是adguard home查询日志页面，显示所有的请求都是OpenClash所在的IP

**Comment by vernesong** [comment]
你可以尝试用openclash做ad的上游

**Comment by tian-jeff** [comment]
谢谢回复，我已经设置好试了下，OpenClash和ADH都可以显示

**Comment by eyaeya** [comment]
> 谢谢回复，我已经设置好试了下，OpenClash和ADH都可以显示

请问如何设置openclash做adh的上游

**Comment by eyaeya** [comment]
> 你可以尝试用openclash做ad的上游

@vernesong 请教，OpenClash作为ADH的上游，该如何设置呢？

ADH的上游DNS该如何设置；
ADH该设置为什么重定向模式。

感恩。

**Comment by tian-jeff** [comment]
> > 谢谢回复，我已经设置好试了下，OpenClash和ADH都可以显示
> 
> 请问如何设置openclash做adh的上游

在ADH的上有DNS中设置为OpenClash所在的IP+端口就可以了
