### ISSUE TITLE
[Bug] redir-host兼容模式解析异常导致github无法打开

### ISSUE THREAD

**Issue by eightsheep67** [vernesong/OpenClash#2881]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.75-beta

### Bug on Environment

Lean

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

redir-host兼容模式下，软路由科学，导致全家设备无法打开github，关闭openclash反而可以打开（就是很慢）

### Describe the Bug

最近才发现家里上github有问题。家里用openclash，还建立了简单的socks供我手机上小飞机使用。

具体现象就是：

1.无法打开github，nslookup github.com 是182.43.124.6，指向了国家反诈；
nslookup [www.github.com](http://www.github.com/) 是192.30.255.112，美国地址，直接访问该ip显示不安全，继续的话无法访问

2.关掉openclash，刷新dns后可以访问github.com，指向20.205.243.166，新加坡地址，直接访问该ip显示不安全，继续的话进入github主页。

3.手机不连wifi通过联通数据，打开小飞机访问github.com正常

4.我想会不会是我openclash中设置的哪个dns出问题了,就用用nslookup域名后带dns地址方法来查询，但是无论用运营商自己的dns，还是其他所有的公共dns比如114dns，8.8.8.8，223.5.5.5，在开openclash的时候，nslookup查出来的都是和1一样的地址；关掉openclash查出来的都是和2一样的地址。貌似和dns也没有关系。

经过以上排查，非电脑手机等终端问题，也不是VPS的问题，也不是运营商DNS劫持的问题。
就是打开openclash后就会污染导致解析的ip出问题。
最后发现切换成FAKE IP就可以了，切换会redir-host兼容又不行。
所以是redir-host兼容模式有问题

### OpenClash Log

无

### Expected Behavior

redir-host恢复正常

**Comment by zepingwu** [comment]
草，我还以为是我的网络问题，找了一下午，然后暂时切到fake-ip了。

**Comment by phantombf** [comment]
取消勾选 追加上游dns 试试

**Comment by eightsheep67** [comment]
刚试了下你说的，转回redirhost 取消掉那个勾，试一下不行，于是有勾上转回fakeip，结果死活又连不上github，试着转回redirhost又好了，反而fakeip连不上了，莫名其妙的……

> 取消勾选 追加上游dns 试试

**Comment by eightsheep67** [comment]
现在redirhost又不行了，换回fakeip又可以了，莫名其妙的，这个模式切换比看起来的要久吗？

**Comment by kingsey** [comment]
github被大面积dns污染，在fallback的域名里加入吧

**Comment by vernesong** [comment]
![image](https://user-images.githubusercontent.com/42875168/206060421-58758da0-522c-4010-8566-9090c2a820a7.png)

**Comment by eightsheep67** [comment]
> github被大面积dns污染，在fallback的域名里加入吧

可行，fallback-filter的domain加了一列：
    - "+.github.com"
解决了问题
