### ISSUE TITLE
[Feature] openclash支持PROCESS-NAME吗

### ISSUE THREAD

**Issue by JamesLiu0802** [vernesong/OpenClash#2883]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

是否支持process-name

### Describe the Solution

匹配process-name配置

**Comment by machine-doll** [comment]
可以在外部规则里面指定，本身也是带了一些基于process name的规则的，会过滤掉常见的p2p下载软件的流量

**Comment by Reidhuang** [comment]
支持的，全局设置--规则设置里面

**Comment by JamesLiu0802** [comment]
> 支持的，全局设置--规则设置里面

能否匹配非openwrt本身，如安卓手机的进程呢

**Comment by machine-doll** [comment]
怎么可能？路由器怎么知道你手机发出的那个连接是哪个进程的？  而且安卓手机上，主要是要看是哪个软件包的流量，来进行分应用代理，而不是看哪个进程发出的  
不过你可以自己用anxray之类的软件配置分流，把要走代理的软件指向OpenClash的socks5代理服务器  
只能在安卓手机上对不同软件包的流量进行过滤。而且安卓的软件的TLS指纹应该就那几种，没什么特征  
HTTP流量，你可以劫持下来，用别的东西处理，基于UA来选择策略。HTTPS可以mitm，但是安卓7.0开始需要root才可以信任自己的证书。综上，建议你考虑直接在本机上进行处理

**Comment by JamesLiu0802** [comment]
> 怎么可能？路由器怎么知道你手机发出的那个连接是哪个进程的？ 而且安卓手机上，主要是要看是哪个软件包的流量，来进行分应用代理，而不是看哪个进程发出的 不过你可以自己用anxray之类的软件配置分流，把要走代理的软件指向OpenClash的socks5代理服务器 只能在安卓手机上对不同软件包的流量进行过滤。而且安卓的软件的TLS指纹应该就那几种，没什么特征 HTTP流量，你可以劫持下来，用别的东西处理，基于UA来选择策略。HTTPS可以mitm，但是安卓7.0开始需要root才可以信任自己的证书。综上，建议你考虑直接在本机上进行处理

好的，谢谢大佬的回答
