### ISSUE TITLE
[Feature] Shadowsocks 2022 UDP over TCP

### ISSUE THREAD

**Issue by Longtianmu** [vernesong/OpenClash#2886]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

如题，目前在OpenClash UI的服务器节点中似乎并没有看到UDP over TCP的支持选项。

### Describe the Solution

SS2022?

### Describe Alternatives

None

### Additional Context

None

**Comment by love4taylor** [comment]
上游 clash 并不支持。
