### ISSUE TITLE
[Bug] 编辑配置无法保存

### ISSUE THREAD

**Issue by rrfeng** [vernesong/OpenClash#2888]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.70-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

配置文件管理-编辑配置，配置中添加 emoji -点保存，报错如下

Reference error
Unhandled exception during request dispatching
access to undeclared variable err
In [anonymous function](), file /usr/share/ucode/luci/http.uc, line 97, byte 10:
  called from function parse ([C])
  called from function mimedecode_message_body (/usr/share/ucode/luci/http.uc:111:26)
  called from function parse_message_body (/usr/share/ucode/luci/http.uc:180:51)
  called from function [anonymous function] (/usr/share/ucode/luci/http.uc:450:3)
  called from function [anonymous function] (/usr/share/ucode/luci/http.uc:374:22)
  called from function require_post_security (/usr/share/ucode/luci/dispatcher.uc:680:47)
  called from function [anonymous function] (/usr/share/ucode/luci/dispatcher.uc:995:35)
  called from anonymous function (/www/cgi-bin/luci:39:12)

 `            err = buffer;`
  Near here --------^

### Describe the Bug

luci-app-openclash 看起来对 unicode 支持有问题，如果没有 emoji 测试是正常的。

### OpenClash Log

无

### OpenClash Config

```shell
无
```

### Expected Behavior

应该能够正常修改配置文件

**Comment by lloyd18** [comment]
在官方版本我也出现过，大雕版本没这问题
