### ISSUE TITLE
[Feature] 希望Fake-IP模式可以支持让指定的设备不走代理

### ISSUE THREAD

**Issue by machine-doll** [vernesong/OpenClash#2889]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

现在Redir-Host模式似乎无法避免DNS污染的问题，只能用Fake-IP模式  
但是Fake-IP模式，虽然最近加上了让国内域名直接返回真实IP的功能，可是对于局域网中的所有设备，都会返回Fake-IP  
我的局域网中有一个NAS挂下载，因为BT下载会建立大量的连接，在运行一段时间之后，会造成clash占用过多资源而卡死。此时占用的过多的资源是打开的套接字之类的资源，以及Fake-IP模式的IP，CPU和内存都有大量空余  
如果可以在br-lan上再绑定一个IP，在这个IP上启动一个DNS服务器，并且向不走代理的设备的分配这个DNS服务器，应该是可以解决的

### Describe the Solution

启动一个TUN设备，将一个DNS服务器绑定到这个TUN设备的IP，为这个TUN设备配置正确的路由，使得DNS查询可以交给这个设备  
通过`dnsmasq`的参数，让局域网中不走代理的设备拿到的是这个DNS服务器，从而实现直连，不占用clash的资源

### Describe Alternatives

考虑过在别的设备上配置一个DoH Client，来进行DNS解析，之后作为普通的UDP 53端口的DNS服务器，再对不走代理的设备进行配置，使得其使用这个DNS服务器

**Comment by vernesong** [comment]
dnsmasq不支持ip分流

**Comment by gitcook** [comment]
iptables可以实现吧 ，就是找不到教程
