### ISSUE TITLE
导致路由器随机重启

### ISSUE THREAD

**Issue by tete1030** [vernesong/OpenClash#289]
你好。

近几个月来我的路由器一直在不断随机重启，平均1-2次每天。最近忍无可忍，经过一个个排除发现只要openclash启动，随机重启问题就会出现。

我用的是x86_64软路由，openwrt是自己编译的 https://github.com/coolsnowwolf/lede 。openwrt和openclash中间一直有在更新，但是重启问题一直存在。

经过分析重启前的dmesg，我发现重启问题是kernel panic导致的。这个kernel panic涉及到了netfilter nat模块，我猜测可能是openclash添加的iptables rules带来的某种问题。虽然不一定是openclash自身的问题，我仍然想开个issue问问您是否有遇到过相关情况（我看到了#113，但是信息不多）

我已经在bugs.openwrt.org提交了issue，内有比较详细的分析和crash log：https://bugs.openwrt.org/index.php?do=details&task_id=2943&pagenum=1

但是现在仍然弄不清为什么会发生这种情况（dev_net()为NULL），以及为什么看起来只有我遇到这样的问题，不知您有没有什么见解？谢谢

**Comment by mephisX** [comment]
我倒没有遇到过路由器重启，openclash 核心崩溃自动重启倒是遇到不少，而且有些节点无法记忆。

**Comment by c71an** [comment]
同问   Xiaomi Mi Router 3G\MediaTek MT7621 ver:1 eco:3\ Linux version 4.14.171\ OpenWrt 19.07.2 r10947-65030d81f3
随机重启内核日志
Tue Mar 31 17:11:28 2020 kern.alert kernel: [23808.062036] CPU 3 Unable to handle kernel paging request at virtual address 07406000, epc == 8010e8bc, ra == 80349044
Tue Mar 31 17:11:28 2020 kern.warn kernel: [23808.072684] Oops[#1]:
Tue Mar 31 17:11:28 2020 kern.warn kernel: [23808.075000] CPU: 3 PID: 0 Comm: swapper/3 Not tainted 4.14.171 #0
Tue Mar 31 17:11:28 2020 kern.warn kernel: [23808.081069] task: 8fc3cc80 task.stack: 8fc68000

**Comment by tete1030** [comment]
@c71an 有更完整的日志吗，包括后面的call trace

**Comment by c71an** [comment]
@tete1030 目前只有system.log 中可以看到仅有的内核信息。

**Comment by ct66683** [comment]
我也有随机重启的情况，造成的影响是短暂性断网。不过看不到重启之前的日志

**Comment by c71an** [comment]
改用clash for openwrt之后也有重启现象，但是系统改用snapshot之后已稳定运行3天。

**Comment by tete1030** [comment]
已经能确认我自己的随机重启原因，问题不在openclash本身。

原因在nf_nat这个kernel module内的一个几年前的[patch](https://github.com/openwrt/openwrt/blob/master/target/linux/generic/pending-4.19/616-net_optimize_xfrm_calls.patch)，优化了nf_xfrm_me_harder函数，本意是加快速度，但是忽略了一处数值可能为NULL的情况（为NULL的原因不清楚，可能是正常的，也可能是其他原因导致的）

这个nullptr问题在执行iptables redirect规则时有一定概率触发，而这个规则正是openclash redir/fakeip非常依赖的。所以流量比较密集时容易kernel panic。

提交的[bug report](https://bugs.openwrt.org/index.php?do=details&task_id=2943)里别人建议删除这个patch重新编译内核，因为这个patch最初的提交动机也没有解释清楚。照做后重启不再发生。

解决方案就是编译openwrt时删除所有的target/linux/generic/pending-*/616-net_optimize_xfrm_calls.patch

> 我也有随机重启的情况，造成的影响是短暂性断网。不过看不到重启之前的日志

@ct66683 对，我一开始也看不到日志，即便让日志保存在硬盘上。主要是因为这种kernel panic会直接触发重启，导致userspace的日志管理工具不再有机会运行。也没机会sync到硬盘。最后试了很久才发现NetConsole这个好东西，能让kernel log在kernel space通过网络传到其他主机上😂，这才终于看到问题根源。当然如果你的路由器有uart或者rs232口可以直接记录，就不需要我这么麻烦

**Comment by tete1030** [comment]
> 同问 Xiaomi Mi Router 3G\MediaTek MT7621 ver:1 eco:3\ Linux version 4.14.171\ OpenWrt 19.07.2 r10947-65030d81f3
> 随机重启内核日志
> Tue Mar 31 17:11:28 2020 kern.alert kernel: [23808.062036] CPU 3 Unable to handle kernel paging request at virtual address 07406000, epc == 8010e8bc, ra == 80349044

@c71an 单从`0x07406000`这个address来看，你的问题和我的应该不一样。我那个问题导致的address必定会在0x113c附近（64位），如果是32位还要减半，你这个数值很大了

**Comment by ct66683** [comment]
> 已经能确认我自己的随机重启原因，问题不在openclash本身。
> 
> 原因在nf_nat这个kernel module内的一个几年前的[patch](https://github.com/openwrt/openwrt/blob/master/target/linux/generic/pending-4.19/616-net_optimize_xfrm_calls.patch)，优化了nf_xfrm_me_harder函数，本意是加快速度，但是忽略了一处数值可能为NULL的情况（为NULL的原因不清楚，可能是正常的，也可能是其他原因导致的）
> 
> 这个nullptr问题在执行iptables redirect规则时有一定概率触发，而这个规则正是openclash redir/fakeip非常依赖的。所以流量比较密集时容易kernel panic。
> 
> 提交的[bug report](https://bugs.openwrt.org/index.php?do=details&task_id=2943)里别人建议删除这个patch重新编译内核，因为这个patch最初的提交动机也没有解释清楚。照做后重启不再发生。
> 
> 解决方案就是编译openwrt时删除所有的target/linux/generic/pending-*/616-net_optimize_xfrm_calls.patch
> 
> > 我也有随机重启的情况，造成的影响是短暂性断网。不过看不到重启之前的日志
> 
> @ct66683 对，我一开始也看不到日志，即便让日志保存在硬盘上。主要是因为这种kernel panic会直接触发重启，导致userspace的日志管理工具不再有机会运行。也没机会sync到硬盘。最后试了很久才发现[NetConsole](https://wiki.archlinux.org/index.php/Netconsole)这个好东西，能让kernel log在kernel space通过网络传到其他主机上😂，这才终于看到问题根源。当然如果你的路由器有uart或者rs232口可以直接记录，就不需要我这么麻烦

那么就是要重装wrt系统咯？

在现有的环境删除没有效果是吧？

**Comment by tete1030** [comment]
修复起来需要自己编译openwrt，系统里不存在这个文件的
另外前提是你的问题根源和我的相同

**Comment by zhea55** [comment]
我也遇到了，n1装上了，刚启动ip还能ping

只有有机器访问盒子网关，机器ip马上就失联了。

**Comment by tete1030** [comment]
问题已解决

**Comment by Tesla9527** [comment]
我也遇到了这个问题，每天都要自动重启1到2次，现在把openclash关掉了，就没出现过问题了。

**Comment by joepeak** [comment]
> 问题已解决

怎么解决的啊
