### ISSUE TITLE
openclash如何设置双栈网站ipv4优先[Feature] 

### ISSUE THREAD

**Issue by kitkw** [vernesong/OpenClash#2893]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

双栈网站默认IPV6优先，但IPV6流量又不经代理  做成访问异常...
openclash能不能设置 某个网站IPV4优先 或者全局IPV4优先
（在不需要关闭IPV6情况下）
### Describe the Solution

![屏幕截图 2022-12-09 212521](https://user-images.githubusercontent.com/31963066/206747245-50554df0-c3a2-4343-872f-9d29e36ad514.png)

**Comment by lonesomexz** [comment]
很赞同 默认双栈网站默认IPV6优先比如disney netflix默认都是ipv6优先，现在只能借助第三方mosdns用作openclash唯一的上游服务器，利用里面的双栈网站默认IPV4才行

**Comment by lele712** [comment]
目前暂时使用smartdns过滤fallback的ipv6响应

**Comment by kitkw** [comment]
用Dnsmasq 搞定。

打开：
vi /jffs/configs/dnsmasq.conf.add #不同设备路径可能不一定
写入保存如下：
address=/nivod.tv/mudvod.tv/nbyy.tv/nbys.tv/nbys1.tv/newpppp.com/biggggg.com/::
重启服务：
service restart_dnsmasq

**Comment by 875355038** [comment]
> 目前暂时使用smartdns过滤fallback的ipv6响应

你好，可以看下你的配置么，目前我也遇到这个问题

**Comment by Lonely-Sit** [comment]
> 目前暂时使用smartdns过滤fallback的ipv6响应

smartdns是不是终端设备旁路由ipv4和ipv6都要手动设置dns才行
