### ISSUE TITLE
Cannot Start the Main Process

### ISSUE THREAD

**Issue by hsghost** [vernesong/OpenClash#29]
I can no longer start the service after upgraded to [v0.34.5-beta](https://github.com/vernesong/OpenClash/releases/tag/v0.34.5-beta). From the log:

> time="2019-09-22T19:52:27Z" level=fatal msg="Parse config error: yaml: line 76: did not find expected key"
2019-09-22 19:52:22 OpenClash Can Not Start, Please Check The Error Info And Try Again

when using Fake-IP mode, and 

> time="2019-09-22T20:29:01Z" level=fatal msg="Parse config error: yaml: line 84: did not find expected key"
2019-09-22 20:28:58 OpenClash Can Not Start, Please Check The Error Info And Try Again

when in Redir-Host mode.

Don't know whether or not it is due to a misconfiguration I made. Similar symptom showed once when I added custom rules on [v0.34.3-beta](https://github.com/vernesong/OpenClash/releases/tag/v0.34.3-beta), yet a clean reinstall resolved the problem by then. While this time, no custom rules were added and the problem showed up. Reverted the router to factory and reinstalled and configured with minimum setting changes, the problem persisted.

FYI I'm using a subscription provided by DuangCloud and on a GL.iNet GL-B1300 router. The line pointed by the log seems to be a line of comment (starting with a #):

![屏幕快照 2019-09-23 04 57 29](https://user-images.githubusercontent.com/15333619/65394312-b0212e00-ddbe-11e9-9864-63f9b13a5c55.png)

**Comment by hsghost** [comment]
After some more playing I discovered that enabling _Custom DNS_ in the OpenClash Luci UI resolves the problem. It seems the nameserver configurations provided by DuangCloud could not be parsed correctly by OpenClash. To help you figuring out the problem, I made a simple diff:

![屏幕快照 2019-09-23 06 09 38](https://user-images.githubusercontent.com/15333619/65395150-7dc8fe00-ddc9-11e9-839b-1c9a9511709b.png)

Also, I suggest that providing more information in the logs would be helpful to quickly locate various issues generated on different devices.

**Comment by vernesong** [comment]
what caused this error is the script adds `fallback-filter` parameters below`cfw-bypass` parameter, and I will try to fix it.

**Comment by vernesong** [comment]
what caused this error is the script adds `fallback-filter` parameters below`cfw-bypass` parameter, and I will try to fix it.
