### ISSUE TITLE
[Feature] 能否支持Bilibili预解析？

### ISSUE THREAD

**Issue by missing233** [vernesong/OpenClash#2904]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

根据这个issue了解到B站APP似乎直接用IP进行请求而导致解锁港澳台番剧的功能在APP端不可用https://github.com/ACL4SSR/ACL4SSR/issues/427
根据这个issue提到的内容编写自定义规则后仍无法解锁APP端（iOS）港澳台番剧

### Describe the Solution

流媒体增强中有预解析 Netflix、Disney Plus 域名的功能，希望该功能可以增加对Bilibili的支持

**Comment by vernesong** [comment]
现在有sniff，你规则写好就行了

**Comment by ATa0ist** [comment]
安卓系统的app得重启一下才行，ios不知道是不是这样，不行的话可以试试我用的这个规则
DOMAIN,p-bstarstatic.akamaized.net
DOMAIN,p.bstarstatic.com
DOMAIN,upos-bstar-mirrorakam.akamaized.net
DOMAIN,upos-bstar1-mirrorakam.akamaized.net
DOMAIN,upos-hz-mirrorakam.akamaized.net
DOMAIN-SUFFIX,acgvideo.com
DOMAIN-SUFFIX,bilibili.com
DOMAIN-SUFFIX,bilibili.tv
IP-CIDR,45.43.32.234/32,no-resolve
IP-CIDR,119.29.29.29/32,no-resolve
IP-CIDR,128.1.62.200/32,no-resolve
IP-CIDR,128.1.62.201/32,no-resolve
IP-CIDR,150.116.92.250/32,no-resolve
IP-CIDR,164.52.76.18/32,no-resolve
IP-CIDR,203.107.1.33/32,no-resolve
IP-CIDR,203.107.1.34/32,no-resolve
IP-CIDR,203.107.1.65/32,no-resolve
IP-CIDR,203.107.1.66/32,no-resolve
DOMAIN,apiintl.biliapi.net
DOMAIN,upos-hz-mirrorakam.akamaized.net
DOMAIN-SUFFIX,acg.tv
DOMAIN-SUFFIX,acgvideo.com
DOMAIN-SUFFIX,b23.tv
DOMAIN-SUFFIX,bigfun.cn
DOMAIN-SUFFIX,bigfunapp.cn
DOMAIN-SUFFIX,biliapi.com
DOMAIN-SUFFIX,biliapi.net
DOMAIN-SUFFIX,bilibili.com
DOMAIN-SUFFIX,bilibili.tv
DOMAIN-SUFFIX,biligame.com
DOMAIN-SUFFIX,biligame.net
DOMAIN-SUFFIX,bilivideo.cn
DOMAIN-SUFFIX,bilivideo.com
DOMAIN-SUFFIX,hdslb.com
DOMAIN-SUFFIX,im9.com
DOMAIN-SUFFIX,smtcdns.net

**Comment by phantombf** [comment]
我遇到了和你一样的问题，ios端无法解锁港澳台番剧，安卓tv端正常，规则是我参照acl4ssr规则修改的，研究了大半天也找不出问题，我换回机场自带的规则就正常了，不知道b站规则哪里写错了，头疼😩

**Comment by phantombf** [comment]
我把绕过中国大陆IP功能关闭就正常了，一直以为是规则问题，之前有把bilibili.com加入绕过大陆IP黑名单，安卓TV端能正常解锁，手机端解锁不了，可能还需要把特定的b站域名加入黑名单才能在开启该功能的同时解锁港澳台番剧
