### ISSUE TITLE
[Bug] 自定义规则不生效并报错

### ISSUE THREAD

**Issue by sanqianyanyi** [vernesong/OpenClash#2907]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.59-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

在自己的自定义规则中追加这个自定义规则,规则可能会被转义，我将给予截图
proxies:
  - name: 自建台湾
    type: trojan
    server: xx
    port: 442
    password: xx
    udp: true
    sni: xx
    skip-cert-verify: false
  
proxy-groups:
  - name: "\U0001F30D 动漫疯"
    type: select
    proxies:
      - 自建台湾
rules:
  - "IP-CIDR,219.87.171.0/22,\U0001F3AF 全球直连,no-resolve"
  - "IP-CIDR,43.154.169.48/22,\U0001F3AF 全球直连,no-resolve"
  - "IP-CIDR,101.32.45.0/22,\U0001F3AF 全球直连,no-resolve"
  - "IP-CIDR,106.55.20.0/22,\U0001F3AF 全球直连,no-resolve"
  - "IP-CIDR,123.50.37.103/22,\U0001F3AF 全球直连,no-resolve"
  - "DOMAIN-SUFFIX,licloud.io,\U0001F3AF 全球直连,no-resolve"
  - "DOMAIN-SUFFIX,logitech.com.cn,\U0001F3AF 全球直连"
  - "DOMAIN-SUFFIX,jkdate.hm-zy.cn,\U0001F3AF 全球直连"
  - "DOMAIN-SUFFIX,lscr.io,\U0001F30D 动漫疯"
  - "DOMAIN-SUFFIX,binance.com,\U0001F30D 动漫疯"
  - "DOMAIN-SUFFIX,openai.com,\U0001F30D 动漫疯"
  - "DOMAIN-SUFFIX,asmrbbs.com,\U0001F4F2 电报信息" #匹配域名后缀(交由Proxy代理服务器组)
  - "DOMAIN-SUFFIX,gamer.com.tw,\U0001F30D 动漫疯" #匹配域名后缀(交由Proxy代理服务器组)
  - "DOMAIN-SUFFIX,bahamut.com.tw,\U0001F30D 动漫疯" #匹配域名后缀(交由Proxy代理服务器组)
  - "DOMAIN-SUFFIX,hinet.net,\U0001F30D 动漫疯" #匹配域名后缀(交由Proxy代理服务器组)
  - "DOMAIN-SUFFIX,gamer-cds.cdn.hinet.net,\U0001F30D 动漫疯" #匹配域名后缀(交由Proxy代理服务器组)
  - "DOMAIN-SUFFIX,fbcdn.net,\U0001F30D 动漫疯" #匹配域名后缀(交由Proxy代理服务器组)
  - "DOMAIN-SUFFIX,gvt1.com,\U0001F30D 动漫疯" #匹配域名后缀(交由Proxy代理服务器组)
  - "DOMAIN-SUFFIX,digicert.com,\U0001F30D 动漫疯" #匹配域名后缀(交由Proxy代理服务器组)
  - "DOMAIN-SUFFIX,viblast.com,\U0001F30D 动漫疯" #匹配域名后缀(交由Proxy代理服务器组)
  - "DOMAIN-SUFFIX,d3u8eo6n4jxbvx.cloudfront.net,\U0001F30D 动漫疯" #匹配域名后缀(交由Proxy代理服务器组)
  - "DOMAIN-SUFFIX,www.asmrlt.net,\U0001F4F2 电报信息" 

### Describe the Bug

在自己的自定义规则中追加这个自定义规则，之后就报错，我是基于机场的配置文件进行修改，除了新增一个我自建的节点以及多写了一个策略组，没有增加新东西，但是写入之后，启动就报错，动漫疯策略组not found，在官方说明文档并未发现问题成因，希望能给予解答，是规则组只能写rule策略，还是我的写法有误。谢谢

### OpenClash Log

No log just ui after fresh install

### Expected Behavior

![image](https://user-images.githubusercontent.com/71774177/208113899-3d574ef7-1d43-487c-837a-8af70ce18081.png)
![image](https://user-images.githubusercontent.com/71774177/208114368-a2f2f4e3-3bf9-4313-a159-148e3557cf69.png)
![image](https://user-images.githubusercontent.com/71774177/208114470-fc0226d5-57b7-4683-8406-4089c9810d84.png)

**Comment by More500code** [comment]
我也遇到了同样的问题 你解决了吗？
