### ISSUE TITLE
[Bug] 绕过大陆模式 PlayStore商店无法下载app

### ISSUE THREAD

**Issue by MaoSuSu** [vernesong/OpenClash#2909]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.70-beta

### Bug on Environment

Lean

### Bug on Platform

Linux-arm64

### To Reproduce

无

### Describe the Bug

国行手机rom中使用services.googleapis.cn判断谷歌商店app走哪个下载节点，目前大陆白名单排除了该域名（估计是因为后缀的cn），导致域名无法进入clash被代理，直观的表现就是商店app无法下载更新，一直转圈圈，望作者修复

### OpenClash Log

无

### Expected Behavior

无

### Screenshots

<img width="414" alt="image" src="https://user-images.githubusercontent.com/45323874/208280902-aa63a7a4-6844-4f21-a6a3-16e71d517541.png">

**Comment by vernesong** [comment]
![image](https://user-images.githubusercontent.com/42875168/208296548-f7be85a4-4257-4628-bae0-63463af32aa9.png)

**Comment by MaoSuSu** [comment]
> ![image](https://user-images.githubusercontent.com/42875168/208296548-f7be85a4-4257-4628-bae0-63463af32aa9.png)

实测有效，感谢！
