### ISSUE TITLE
手机知乎APP无法刷新问题

### ISSUE THREAD

**Issue by oringring** [vernesong/OpenClash#291]
使用的是fake-ip模式，在使用机场自带规则，还有神机规则，还有lhie1规则，在手机使用知乎app时都会出现无法刷新的问题，有时候是回答无法打开，有时候是评论无法打开。
也尝试过使用smartdns，还是会出现知乎app无法刷新，已经把规则的广告屏蔽等选项都选择了直接连接模式了，不知道为什么会出现这种情况呢？在手机端使用安卓clash时是不会有这种情况的。
求大神解答。

**Comment by vernesong** [comment]
很明显是dns问题吧，fakeip只需要在配置文件里填国内的dns，还有就是路由关ipv6
![image](https://user-images.githubusercontent.com/42875168/77921710-b2ff5d00-72d2-11ea-9c98-2787c15c9e96.png)

**Comment by zzsimonss** [comment]
我这边关掉“仅代理命中规则流量”就可以了，不知道为啥

**Comment by peoplechinapower** [comment]
我是知乎加载不出图片。关掉了“*仅允许常用端口流量”貌似好了。
