### ISSUE TITLE
无法访问google相关服务

### ISSUE THREAD

**Issue by kettly1260** [vernesong/OpenClash#292]
版本：
当前内核版本 | v0.18.0.4 | 当前客户端版本 | v0.37.1-beta
模式：FAKE-IP
设备：斐讯N1 旁路由

问题：无法访问google相关的服务。包括YouTube。
相同的规则在电脑或者手机客户端上没有任何问题。
查看连接，未发现相关IP和域名

**Comment by vernesong** [comment]
wiki里有，检查dns的劫持情况

**Comment by kettly1260** [comment]
@vernesong 查看了一下，好像没有多大的区别。而且openclash的luci里面也显示YouTube无法访问
Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination
1    REDIRECT   tcp  --  0.0.0.0/0            8.8.4.4              redir ports 7892
2    REDIRECT   tcp  --  0.0.0.0/0            8.8.8.8              redir ports 7892
3    CLOUD_MUSIC  tcp  --  0.0.0.0/0            0.0.0.0/0            match-set music dst
4    CLOUD_MUSIC  tcp  --  0.0.0.0/0            0.0.0.0/0            match-set music dst
5    REDIRECT   udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:53 redir ports 53
6    REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:53 redir ports 53
7    DOCKER     all  --  0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL
8    prerouting_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom prerouting rule chain */
9    zone_lan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
10   zone_vpn_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
11   openclash  tcp  --  0.0.0.0/0            0.0.0.0/0

**Comment by vernesong** [comment]
电脑查询dns的结果呢？

**Comment by kettly1260** [comment]
问题已解决。还是DNS的问题。把DNS劫持到adguard之后问题莫名解决了。。。不清楚怎么回事

**Comment by ZXL-github** [comment]
如何解决的？
