### ISSUE TITLE
[Feature] 自定义配置文件获取订阅信息

### ISSUE THREAD

**Issue by DevilHandCC** [vernesong/OpenClash#2921]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

![CLASH](https://user-images.githubusercontent.com/24727765/210297490-ec0a7a82-920b-44f5-9348-ea9b2fe7a9be.png)
图中第一个配置文件是直接使用的机场订阅，第二个是用的机场代理集+自己编写的规则，能否让第二个配置像第一个一样获取订阅信息

### Describe the Solution

比如解析代理集时同时获取header信息？

**Comment by Doublefire-Chen** [comment]
你好，请问你解决了吗？我也有同样的需求

**Comment by 27747** [comment]
丢，这个问题一直存在，openclash不管的，我换passwall2了
