### ISSUE TITLE
[Bug] 在服务器与策略组管理中添加自定义节点会覆盖掉机场的所有节点

### ISSUE THREAD

**Issue by MaoSuSu** [vernesong/OpenClash#2927]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.78-beta

### Bug on Environment

Lean

### Bug on Platform

Linux-arm64

### To Reproduce

如题

### Describe the Bug

如题

### OpenClash Log

无

### Expected Behavior

问题如题，希望在添加自定义节点时可以同时保留机场的节点，仅将自定义的节点加在机场proxies最后一行，并且在所有proxy-groups中加入该节点的信息

### Screenshots

<img width="1222" alt="image" src="https://user-images.githubusercontent.com/45323874/211202731-cd493a23-c312-4e5c-ad02-02e2f231ec3d.png">

**Comment by vernesong** [comment]
先读取配置文件

**Comment by MaoSuSu** [comment]
> 先读取配置文件

但是这么做，在未来机场节点信息变动时是无法实时更新的吧？感觉这样就丧失了自动更新订阅节点的优势了

**Comment by vernesong** [comment]
机场节点你用provider就行了

**Comment by wizardmanxxx** [comment]
> 机场节点你用provider就行了

求问大佬，provider是一个选项嘛，我似乎没有在配置页面见到。。
