### ISSUE TITLE
[Bug] 近期openclash主页无法真实显示国外ip，都和国内的一样

### ISSUE THREAD

**Issue by anjue39** [vernesong/OpenClash#2935]
近期openclash主页无法真实显示国外ip，都和国内的一样
openclash主页 Powered by ip.skk.moe
显示的不准确，再也看不到国外的ip

**Comment by vernesong** [comment]
这个跟配置的规则相关，直连了就是国内IP

**Comment by expnn** [comment]
这个版本 [v0.45.78-beta](https://github.com/vernesong/OpenClash/releases/tag/v0.45.78-beta) 生成的配置文件有误：
我将运行模式设置为 redir-host, 但是生成的配置文件修改为了 fake-ip, 如下三图所示：
![image](https://user-images.githubusercontent.com/18525479/212349733-3f68a9ee-ad35-44ed-9295-e0d2c96d3d98.png)
![image](https://user-images.githubusercontent.com/18525479/212349898-eb8787db-0489-4d64-a1d3-979f576c6bf7.png)
![image](https://user-images.githubusercontent.com/18525479/212350079-e992e848-738c-42d5-a6b4-cb5581308bc5.png)

然后 ping google 或者 youtube 都会返回 127.0.0.1 这个地址，不过好像与这个问题无关，应该是其他地方还有问题。这导致透明代理不起作用。
