### ISSUE TITLE
[Bug] 0.45.79导致socat映射的外网访问端口无法访问

### ISSUE THREAD

**Issue by xianren78** [vernesong/OpenClash#2938]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

0.45.79

### Bug on Environment

Lean

### Bug on Platform

Linux-arm64

### To Reproduce

从0.45.78升级0.45.79后，从WAN访问路由器socat映射端口，比如DDNS:8443--->192.168.0.1:443，无法访问，返回0.45.78后正常，与meta内核也无关。

### Describe the Bug

从0.45.78升级0.45.79后，从WAN访问路由器映射端口，比如DDNS:8443--->192.168.0.1:443，无法访问，返回0.45.78后正常，与meta内核也无关。

### OpenClash Log

无

### Expected Behavior

正常如0.45.78

**Comment by vernesong** [comment]
可能走代理了，设置一下
![image](https://user-images.githubusercontent.com/42875168/212011625-128b5780-e1a9-45fb-9908-9a350544ecd0.png)

**Comment by xianren78** [comment]
> 可能走代理了，设置一下 ![image](https://user-images.githubusercontent.com/42875168/212011625-128b5780-e1a9-45fb-9908-9a350544ecd0.png)

8443加入来源端口没问题了，我当时把映射端口随意改其他比如7443 6443也不行。

**Comment by vernesong** [comment]
进来直连，出去经过内核会nat

**Comment by xianren78** [comment]
> 进来直连，出去经过内核会nat

所以后面就是会这种逻辑了，对吧，之前的版本似乎都是直连不走NAT的。

**Comment by xianren78** [comment]
> 进来直连，出去经过内核会nat

还是有不对劲的地方，我选中了实验性：绕过中国大陆 IPv6，我的DDNS是只解析ipv6的，理论上不应该走核心啊，直接绕过的。

**Comment by vernesong** [comment]
你看看内核日志和防火墙不就知道了
