### ISSUE TITLE
提高使用 OpenClash GUI 创建的 game rules 在最后生成config中的顺序的优先级

### ISSUE THREAD

**Issue by TyrionWang** [vernesong/OpenClash#2942]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

`rules:
- DST-PORT,7895,REJECT
- DST-PORT,7892,REJECT
- IP-CIDR,198.18.0.1/16,REJECT,no-resolve
- DOMAIN-KEYWORD,google,Proxy
- DOMAIN-SUFFIX,gstatic.com,Proxy
- RULE-SET,reject,REJECT
- RULE-SET,direct,DIRECT
- RULE-SET,cncidr,DIRECT
- RULE-SET,proxy,Auto
- RULE-SET,google,Auto
- RULE-SET,lancidr,DIRECT
- RULE-SET,applications,DIRECT
- DOMAIN,clash.razord.top,DIRECT
- DOMAIN,yacd.haishan.me,DIRECT
- RULE-SET,英雄联盟-台服,Taiwan
- GEOIP,LAN,DIRECT
- GEOIP,CN,DIRECT
- MATCH, Others`
如上图所示，使用 GUI 添加游戏规则后，生成的 running config 文件中，‘RULE-SET,英雄联盟-台服,Taiwan’ 的优先级很低，现在我的running config文件中规则优先级为 
global setting->rule setting中的设置
Rule provider and groups->Custom Rule Providers and Groups 中的设置
Rule provider and groups->Game Rules and Groups 中的设置
config management 中的设置

### Describe the Solution

我认为合理的顺序应该是

Rule provider and groups->Game Rules and Groups 中的设置
global setting->rule setting中的设置
Rule provider and groups->Custom Rule Providers and Groups 中的设置
config management 中的设置

以避免后面规则集中可能的冲突

**Comment by vernesong** [comment]
1 游戏规则都是ip规则且并不准确
2 放在最后防止匹配混乱
3 放在前面ip规则会触发dns，影响连接速度
4 手写自定义规则的优先级最高，因为必要时可以对其他第三方的规则进行覆盖

**Comment by vernesong** [comment]
如果需要，在页面下面的自定义规则集可以设置优先匹配，路径选本地的游戏规则

**Comment by TyrionWang** [comment]
>

**Comment by TyrionWang** [comment]
感谢解答
