### ISSUE TITLE
在国内玩国内对战平台“游聚”时遇到的问题

### ISSUE THREAD

**Issue by 70599** [vernesong/OpenClash#295]
官网：https://www.gotvg.com/

---

症状：不能联机对战（登录、观战均正常）

---

配置模式：国内IP白名单

---

平台可能比较小众，我也不清楚怎样收集详细日志，目前发现的情况如下：
- 日志级别为`warning`尝试联机对战，可见`level=warning msg="dial Domestic error: dial tcp4 106.75.147.95:5574: connect: connection refused"`的错误日志
- 依据上述IP使用`iptables -t nat -I PREROUTING -p tcp -d 106.75.147.95/32 -j RETURN`命令后，不再输出错误日志，但是依然不能联机对战
- 在`不走代理的局域网LAN IP`中加入启动对战平台的电脑IP，则可以联机对战

---

看起来即使是不走代理的流量，也会经过openclash。
`iptables -t nat -I PREROUTING ... -j RETURN`的流量，可能（？）也会经过openclash。
（就是不知道为什么相应的错误日志没有了）

请问有什么建议吗？

**Comment by 70599** [comment]
用`ipset`把`openclash`表中所有指向国内IP的流量，全都在重定向到7892端口前`RETURN`之后，目前对战平台正常工作。
openclash不能再控制国内流量了，不过目前没有直连以外的需求。

**Comment by lloyd18** [comment]
想不到在这还能看到有人玩游聚的 哈哈

**Comment by 70599** [comment]
问题暂时解决了，我就先close了。
