### ISSUE TITLE
[Bug] clash of windows能用 openclash不能用 两天找不到答案>.<

### ISSUE THREAD

**Issue by gekkjoe** [vernesong/OpenClash#2954]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.78

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-arm64, Other

### To Reproduce

使用x-ui面板生成vmess 导入clash of windows可以用 导入openclash不能用

### Describe the Bug

导入clash of windows后可以ping通 也可以正常刷视频
导入openclash ping不通 当然也用不了

### OpenClash Log

![image](https://user-images.githubusercontent.com/80162494/214367524-40faa87f-f0a7-448f-a574-f2d038ef4f71.png)
![image](https://user-images.githubusercontent.com/80162494/214367608-dfc66c1e-b96d-4ce8-b5e7-00ff930da0f7.png)

### Expected Behavior

请问如何解决

**Comment by vernesong** [comment]
跳过证书验证

**Comment by gekkjoe** [comment]
skip-cert-verify: false
已添加这个参数 还是不行 

> 跳过证书验证



> 跳过证书验证



> 跳过证书验证



> 跳过证书验证

**Comment by vernesong** [comment]
skip-cert-verify: true

**Comment by gekkjoe** [comment]
> skip-cert-verify: true

请教是我的证书没弄好还是openclash不支持还是x-ui问题还是什么原因？！

**Comment by vernesong** [comment]
证书问题，路由上忽略没事

**Comment by zhuxu222** [comment]
v神，我也遇到证书问题。后来经过一番尝试，发现通配符根域名证书不行，单域名证书可以。   问题出现在哪个环节？ 后续会优化吗？

> 证书问题，路由上忽略没事

**Comment by vernesong** [comment]
> * asdf12345

你看看安装ca-bundle和ca-certificates两个软件包没有

**Comment by vernesong** [comment]
> v神，我也遇到证书问题。后来经过一番尝试，发现通配符根域名证书不行，单域名证书可以。 问题出现在哪个环节？ 后续会优化吗？
> 
> > 证书问题，路由上忽略没事

你看看安装ca-bundle和ca-certificates两个软件包没有

**Comment by tony1016** [comment]
> > v神，我也遇到证书问题。后来经过一番尝试，发现通配符根域名证书不行，单域名证书可以。 问题出现在哪个环节？ 后续会优化吗？
> > > 证书问题，路由上忽略没事
> 
> 你看看安装ca-bundle和ca-certificates两个软件包没有

感觉vmess节点都失效了，不知道为什么。看过ca-bundle和ca-certifications都安装了，也看不到报错信息
