### ISSUE TITLE
[Bug] “服务器&策略组管理下”的“代理集节点筛选”不能够正确保存

### ISSUE THREAD

**Issue by machine-doll** [vernesong/OpenClash#2955]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.78-beta

### Bug on Environment

Other

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

在”服务器&策略组管理下”的任意一个策略组或者代理集的“代理集节点筛选“功能中，输入类似于”中继|免费|CDN|直连“之类的关键词，之后保存

### Describe the Bug

在大多数情况下，都不能够正确保存，应用配置后有时候一个关键词都保存不了，有时候只会保存第一个

### OpenClash Log

感觉没必要发

### Expected Behavior

过滤节点功能可以正常工作，而且wiki中也有说明

**Comment by vernesong** [comment]
你截图看看

**Comment by machine-doll** [comment]
<img width="792" alt="image" src="https://user-images.githubusercontent.com/87234334/215269831-713f2e99-96e3-4773-a2ff-f279b0ec5ba3.png">
<img width="715" alt="image" src="https://user-images.githubusercontent.com/87234334/215269874-9a398c40-c5c1-42b8-9777-5c232c75d1f3.png">
配置文件是“all”的那个可以保存筛选信息，但是没有起什么作用
配置文件是“config.yaml”的那个保存的时候会错乱，如果改成上面的那个，最多保存到前面的几个字符就会乱掉，而且筛选出来的节点也是怪的
<img width="657" alt="image" src="https://user-images.githubusercontent.com/87234334/215269995-8cdd57d6-aaff-41d3-9d7c-b4c8ab4b9674.png">
这个地方就完全没有作用，填了也会被覆盖

**Comment by yuntian123456** [comment]
这个问题解决了吗。我发现这个选项感觉填不填都没有区别，没有生效

**Comment by vernesong** [comment]
https://wiki.metacubex.one/config/proxy-groups/#filter
