### ISSUE TITLE
[Feature] 服务器&策略组管理中的策略组配置以及代理集配置添加排除节点功能

### ISSUE THREAD

**Issue by Demon-Lucifer** [vernesong/OpenClash#2960]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

![W~47$R3_6FH2C})PP~ZHIGH](https://user-images.githubusercontent.com/68825229/215150434-4672b7b4-4e6c-4c21-b0b1-fad8278340ce.png)
![9AETK9PR(}W@BNF C{GYMAU](https://user-images.githubusercontent.com/68825229/215150441-21841f05-5e3c-4367-ba6d-4753431f7b18.png)
![O` 4BGY)3C9KY(5S@P6JWW](https://user-images.githubusercontent.com/68825229/215150454-9777d2f1-8984-4530-8ab8-15f0be2accb3.png)
我尝试了!和正则好像都被当成关键字了

### Describe the Solution

支持正则或者添加一个排除节点选项

**Comment by vernesong** [comment]
meta内核是支持正则的，订阅那块要按照格式写，订阅那个不支持provider的过滤

**Comment by Demon-Lucifer** [comment]
明白了，meta内核加策略组过滤实现期望了
