### ISSUE TITLE
[Feature] IPv6 redirect

### ISSUE THREAD

**Issue by xianren78** [vernesong/OpenClash#2974]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

目前IPv6是使用Tproxy的，经由clash meta [commit 63922f](https://github.com/MetaCubeX/Clash.Meta/commit/63922f86a228b3240732bfe30a902b0b11b134bc)和原版clash [commit fbca37](https://github.com/Dreamacro/clash/commit/fbca37c42b444429c4841983306553ffa2109cc0) ，已经都支持IPv6 redirect，能否在ipv6 setting页面加入这个选项支持IPv6 redirect。

谢谢

### Describe the Solution

在ipv6 setting页面加入选项支持IPv6 redirect。

**Comment by vernesong** [comment]
v6 redirect 有什么好处

**Comment by xianren78** [comment]
> v6 redirect 有什么好处

之前看说redirect比tproxy稳定性要更好。

**Comment by InspoOnU** [comment]
> v6 redirect 有什么好处

redirect性能比tproxy强，实测tproxy的cpu占用多大概一倍

**Comment by xianren78** [comment]
继续请求加入这个功能

**Comment by xianren78** [comment]
[经由这个commit完成](https://github.com/vernesong/OpenClash/commit/695cd2a70dfbedb5127a6ec270e5e21c91346d79)
