### ISSUE TITLE
[Bug] 传入局域网设备的ipv6请求会因为clash无法正确返回

### ISSUE THREAD

**Issue by Makiras** [vernesong/OpenClash#2976]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.78-beta

### Bug on Environment

Lean

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

1. 路由器防火墙放行所有入LAN的ipv6请求   
2. 使用境内，境外v6请求对应接口。应当发现可以正常获得http结果。  // SRC 外网
3. 使用局域网设备请求境内，境外v6地址。应当均正常访问。// SRC 局域网
##
4. 打开openclash，并且使用不支持ipv6的节点。使用redir模式，绕过大陆v6地址
5. 重复2。应当发现境内v6客户端可以从局域网设备正常获得http结果，境外v6客户端无法连接局域网设备。// SRC 外网
6. 使用局域网设备请求境内，境外v6地址。应当发现境内v6可以正常获得http结果，境外v6无法连接。// SRC 局域网
##
7. 为clash添加 `- IP-CIDR,2000::/3,DIRECT,no-resolve` 规则，
8. 重复6。变为均正常访问。// SRC 局域网
9. 重复5，没有变化。// SRC 外网

### Describe the Bug

从 外网客户端 传入 局域网设备服务端 的ipv6 TCP请求无法正确返回外网客户端。（外网指境外）

### OpenClash Log

```
2023-02-02 01:08:10 INF [TCP] connected lAddr=[2408:xxxx:c16:71c1::a44]:51860 rAddr=[2603:xxxx:xxxx:xxxx:114:514:1919:810]:80 mode=rule rule=IPCIDR(2000::/3) proxy=DIRECT
2023-02-02 01:08:10 DBG [TCP] accept connection lAddr=[2408:xxxx:c16:71c1::a44]:51860 rAddr=[2603:c020:3:5eee:114:514:1919:810]:80 inbound=TProxy
```

此时是传出，传入流量从这里面看不到。
下图是iptables日志，为传入

![image](https://user-images.githubusercontent.com/22570332/216113598-0e4612a9-899d-44de-a5c1-3b5e6cce9653.png)

### Expected Behavior

从 外网客户端 传入 局域网设备服务端 的ipv6 TCP请求正确返回外网客户端，完成响应。

**Comment by Makiras** [comment]
我怀疑是iptables配置的路由表，让TCP连接的响应经过了clash，进而clash在转发时破坏了TCP的握手过程。  
如果是这样使用CONNMARK或许可以解决？我去尝试一下

**Comment by Makiras** [comment]
如下操作大抵有用。至少我这里有用。

```bash
ip6tables -t mangle -I PREROUTING -i eth0 -j CONNMARK --set-mark 114514 # 从外网接口的传入流量统统打上CONNMARK，内网的不管。 
ip6tables -t mangle -I PREROUTING 2  -m connmark --mark 114514 -j ACCEPT # 不管什么接口，凡是有过 CONNMARK 的流量直接送到下一步（内网响应完了也不用代理）
```

**Comment by jelly21fish** [comment]
虽然过了很久，但还是想问一下，现在的版本这个问题还存在吗？如果把ipv6的代理模式从tproxy改成redirect，还会出现这一问题以至于要手动修改路由表吗？如果使用fake-ip模式，或使用支持ipv6的节点会怎样呢？
