### ISSUE TITLE
[Feature] Trojan non TLS

### ISSUE THREAD

**Issue by belompunya** [vernesong/OpenClash#2978]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

please create Trojan non TLS 

### Describe the Solution

- name: Trojan non TLS
  server: myserver.com
  port: 8080
  type: trojan
  password: password123
  network: ws
  skip-cert-verify: true
  udp: true
  ws-opts:
    path: /path
    headers:
        Host: SERVER.COM

But cannot connect, without SNI , we need no SNI

**Comment by belompunya** [comment]
> sni dikasih aja `sni:` , tapi dikosongin nilainya

udah bang, tetep aja gabisa , jadi compatible nanti 

sni: 
sni: false
sni: -

udah di coba semua

buat popox terbaru , hehe

abang nya make popox gk di OC trojan tp,biar bisa vidcall  , di netmod hp / pc bisa soalnya

pgn popox trojan, biar  bisa vidcall , auto mantabs , tgl beli masa aktif aja setahun, haha

**Comment by starua** [comment]
I'm not sure what you mean. I've done an test my self, and i found openclash didn't add an `sni` option to clash config file if you didn't set it.
If you are talking about problem's about clash it self, then you should open an issue on clash, not openclash.
On the other hand, as i know, it's impossible for https protocol to not sending an “sni” head.
If for some reason you can't let others who spy on your network to see something like sni, maybe you can setup an proxy your self to provide an socks5 proxy on lookback, and then set that as an proxy on clash.
