### ISSUE TITLE
[Bug] OpenClash 使用自建的在线订阅转换服务，订阅转换模板不生效

### ISSUE THREAD

**Issue by Hscpro** [vernesong/OpenClash#2979]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.78-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

使用自建subconverter

### Describe the Bug

使用自建subconverter v0.7.2进行模板转换时订阅转换模板的配置选项不生效，应该是config参数少了`config/`或不正确。

直接使用链接测试是可以正常转换模板的。
既：`http://192.168.1.1:25500/sub?target=clash&url=XXX&config=config/ACL4SSR_Online_Full.ini`

### OpenClash Log

OpenClash：
2023-02-02 16:09:06 配置文件【config】更新成功！
2023-02-02 16:09:06 配置文件【config】下载成功，本地没有配置文件，开始创建...
2023-02-02 16:09:06 配置文件下载成功，检查是否有更新...
2023-02-02 16:09:02 开始更新配置文件【config】...
subconverter：
**[ERRO] Load external configuration failed. Reason: line 0: Empty document**

### OpenClash Config

```shell
不涉及
```

### Expected Behavior

正常转换模板

### Screenshots

![image](https://user-images.githubusercontent.com/13926044/216269910-4741ca06-8227-48ba-b3d3-da8925f988ef.png)

**Comment by vernesong** [comment]
这些预置的是远程地址，可能下载失败，你可以自定义到本地地址
