### ISSUE TITLE
[Bug] TUN内核启动失败问题

### ISSUE THREAD

**Issue by makeye** [vernesong/OpenClash#2980]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.16-Beta

### Bug on Environment

Official OpenWrt, Other

### Bug on Platform

Linux-armv7, Other

### To Reproduce

[OpenClash-2023-2-2-19-18-17.log](https://github.com/vernesong/OpenClash/files/10568348/OpenClash-2023-2-2-19-18-17.log)

### Describe the Bug

从-45版本更新后的插件，总是TUN内核启动失败，一只存在这个问题。机器是ARS2

### OpenClash Log

[OpenClash-2023-2-2-19-18-33.log](https://github.com/vernesong/OpenClash/files/10568350/OpenClash-2023-2-2-19-18-33.log)

### OpenClash Config

```shell
无
```

### Expected Behavior

希望能解决openclash TUN内核启动失败的问题

### Screenshots

![OpenClash插件](https://user-images.githubusercontent.com/28622643/216313235-ce8682a4-21f5-4010-a0d5-bb91bff8c94c.jpg)

**Comment by vernesong** [comment]
你更新一下，内核启动时间太长了

**Comment by makeye** [comment]
更新内核还是插件版本？

**Comment by makeye** [comment]
都更新了还是一样的老问题啊

**Comment by vernesong** [comment]
meta启动慢，不行就先别用了

**Comment by makeye** [comment]
好的，我又试过了，不用meta。单用tun模式也是无法启动，望作者你能够修复

**Comment by Blackrailgun** [comment]
同机器，同问题

**Comment by vernesong** [comment]
发调试日志，你日志里面写的权限不足

**Comment by LaplaceTor** [comment]
#https://github.com/Dreamacro/clash/issues/1116#issuecomment-770423575

**Comment by ParadiseEXPoi** [comment]
一模一样的机器，一模一样的问题，日志报错也一模一样，希望解决

**Comment by vernesong** [comment]
这种错误建议刷固件

**Comment by ParadiseEXPoi** [comment]
应该不是固件问题，今天回滚使用了旧版的客户端，内核使用最新的，启动顺利
类似的A53芯片硬件遇到类似问题可以尝试使用旧版客户端
![Snipaste_2023-03-28_23-09-50](https://user-images.githubusercontent.com/46411423/228283436-8e34af4d-897b-400c-a524-3f27bd81717a.png)

**Comment by Blackrailgun** [comment]
确实不是固件问题，我换了个op固件，问题依旧存在

**Comment by ilaipi** [comment]
一样的问题，希望能修复，先不要关闭bug，搞了一夜没搞好
