### ISSUE TITLE
[Bug] 有时改配置然后重启，内核文件突然不见了

### ISSUE THREAD

**Issue by yunyuyuan** [vernesong/OpenClash#2982]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.44.28-beta

### Bug on Environment

Other

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

无法稳定复现

### Describe the Bug

出现两次了，我改改基本配置（压根没有进入`版本更新`这个页面）然后重启openclash，就报错内核文件不存在（之前都是正常启动的，我用winscp上传的clash和clash_tun文件），`ls /etc/openclash/core`是空的，是被openclash误删了吗

### OpenClash Log

```
2023-02-03 08:53:27 第六步：删除 OpenClash 残留文件...
2023-02-03 08:53:23 第五步: 重启 Dnsmasq 程序...
2023-02-03 08:53:23 第四步: 关闭 Clash 主程序...
2023-02-03 08:53:23 第三步: 关闭 OpenClash 守护程序...
2023-02-03 08:53:22 第二步: 删除 OpenClash 防火墙规则...
2023-02-03 08:53:22 第一步: 备份当前策略组状态...
2023-02-03 08:53:22 OpenClash 开始关闭...
2023-02-03 08:53:19 【TUN】版本内核更新失败，请确认设备闪存空间足够后再试！
2023-02-03 08:53:19 【TUN】版本内核下载成功，开始更新...
2023-02-03 08:53:17 【TUN】版本内核正在下载，如下载失败请尝试手动下载并上传...
2023-02-03 08:53:14 提示: 检测到内核文件不存在，准备开始下载...
2023-02-03 08:53:13 第二步: 组件运行前检查...
2023-02-03 08:53:13 第一步: 获取配置...
2023-02-03 08:53:13 OpenClash 开始启动...
```

### Expected Behavior

-

**Comment by xianren78** [comment]
自己上传的要改一下权限 chmod 0755 /etc/openclash/core/clash_meta && chown nobody:nogroup /etc/openclash/core/clash_meta

**Comment by yunyuyuan** [comment]
> 自己上传的要改一下权限 chmod 0755 /etc/openclash/core/clash_meta && chown nobody:nogroup /etc/openclash/core/clash_meta 以clash_meta为例

我看了下，默认的权限就是你说的
```
root@ImmortalWrt:/etc/openclash/core# ls -lh
-rwxr-xr-x    1 nobody   nogroup     8.6M Feb  3 09:38 clash
-rwxr-xr-x    1 nobody   nogroup    13.3M Feb  3 09:39 clash_tun
```

**Comment by vernesong** [comment]
旧版本不好说

**Comment by zhychen1173** [comment]
> 旧版本不好说

我现在升级到最新版也有这个问题，而且我也不是手动上传文件的，是在版本更新页面上更新的 。路由器重启后，发现openclash没起来，看日志也是内核不存在，自动下载又失败了，所以启动不成功。

**Comment by WFANG12719** [comment]
这个更新失败我也碰到过，后来我发现是open clash自己总是去取 /etc/openclash/config目录里默认时间最新的一个。时间最新的配置文件不一定是可以用的机场，有些是免费的机场已经失效了，也排在第一个，这样就有问题了，一定会更新失败。我的解决办法是做个cron job，把我最常用的几个确认可以用的配置文件每几分钟touch一下，确保他们能排到最前面，这样就可以了。没有仔细去看shell script,不知道是不是这个问题。

**Comment by vernesong** [comment]
配置文件是根据文件名锁定的，不会随意切换

**Comment by yunyuyuan** [comment]
@WFANG12719 和配置文件没有关系啊，是内核文件不见了。不过自从我提了这个issue我就没遇到过这问题了🤣

**Comment by Kethers** [comment]
我这0.45.51-beta meta内核也出现过这个问题
