### ISSUE TITLE
[Bug] proxy-providers无法使用

### ISSUE THREAD

**Issue by Kry5ta1** [vernesong/OpenClash#2985]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.85-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

在配置文件中使用了 proxy-providers 导致openclash无法启动。
proxy-providers:
  Amy:
    type: http
    path: "./proxy_provider/Amy.yaml"
    url: *********
    interval: 3600
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300

### Describe the Bug

在配置文件中使用了 proxy-providers 导致openclash无法启动。

### OpenClash Log

2023-02-03 17:13:08 OpenClash 开始关闭...
2023-02-03 17:13:05 错误：无法获取 General 部分的转发端口设置, OpenClash 使用原始配置文件启动失败
2023-02-03 17:13:03 错误：无法获取 DNS 部分的运行模式设置, OpenClash 使用原始配置文件启动失败
2023-02-03 17:13:01 错误：无法获取 DNS 部分的监听端口设置, OpenClash 使用原始配置文件启动失败
2023-02-03 17:13:01 错误：OpenClash 启动失败，尝试使用原始配置文件启动...
github.com/Dreamacro/clash/hub/executor/executor.go:244 +0x90
created by github.com/Dreamacro/clash/hub/executor.loadRuleProvider
	github.com/Dreamacro/clash/hub/executor/executor.go:246 +0x88
github.com/Dreamacro/clash/hub/executor.loadRuleProvider.func1()
	github.com/Dreamacro/clash/hub/executor/executor.go:222 +0xe7
github.com/Dreamacro/clash/hub/executor.loadProvider({0x7f5bd0e283e0, 0xc00012e6e0})
	github.com/Dreamacro/clash/rules/provider/provider.go:64 +0x4e
github.com/Dreamacro/clash/rules/provider.(*ruleSetProvider).Initial(0xc0000009c0)
	github.com/Dreamacro/clash/rules/provider/provider.go:118 +0x4a
github.com/Dreamacro/clash/rules/provider.NewRuleSetProvider.func1({0xf43740?, 0xc00025a588?})
	github.com/Dreamacro/clash/rules/provider/ipcidr_strategy.go:35 +0x1a5
github.com/Dreamacro/clash/rules/provider.(*ipcidrStrategy).OnUpdate(0xc0000119f8, {0xc000818000, 0x27f7, 0x22?})
	github.com/Dreamacro/clash/component/trie/ipcidr_trie.go:46 +0x4b
github.com/Dreamacro/clash/component/trie.(*IpCidrTrie).AddIpCidrForString(0x3b1e8?, {0xc0006c1d70?, 0x13520a0?})
	github.com/Dreamacro/clash/component/trie/ipcidr_trie.go:34 +0xb4
github.com/Dreamacro/clash/component/trie.(*IpCidrTrie).AddIpCidr(0xc0006c1d70?, 0x17?)
	github.com/Dreamacro/clash/component/trie/ipcidr_trie.go:123 +0x2e
github.com/Dreamacro/clash/component/trie.addIpCidr(0x4?, 0x10?, {0xc00147c1ac?, 0x10?, 0x10?}, 0x13?)
	github.com/Dreamacro/clash/component/trie/ipcidr_trie.go:146 +0x505
github.com/Dreamacro/clash/component/trie.addIpv4Cidr(0x4?, {0xc00147c1ac, 0x4, 0x100000000000013?}, 0x10)
goroutine 98 [running]:
panic: runtime error: index out of range [4] with length 4
2023-02-03 17:12:55 提示：检测到配置了 Meta 内核专属功能，调用 Meta 内核启动...

### OpenClash Config

```shell
proxy-groups:
*****
rule-providers:
*****
proxy-providers:
  Amy:
    type: http
    path: "./proxy_provider/Amy.yaml"
    url: ******
    interval: 3600
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
```

### Expected Behavior

希望大佬帮忙看看

### Screenshots

春节之前一直使用如上的配置文件启动我的openclash，配置文件整体只设置了
1.proxy-groups: 
2.rule-providers:
3.proxy-providers:
这三个参数，其他参数由Openclash的设置自己接管，使用过程一直没有遇到问题。
春节回来后重启OPENCLASH就遇到了该问题，家里的设备和办公室的设备都出现了同样的日志报错。
家里的设备使用的是openwrt-snapshot源码自编译的。
办公室的设备是OpenWrt 21.02.5源码编译的。

**Comment by vernesong** [comment]
rule-providers 都删了重新下载
