### ISSUE TITLE
[Feature] ss2022

### ISSUE THREAD

**Issue by Re-Aqest** [vernesong/OpenClash#2986]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

能支持一下2022-blake3-aes-128-gcm吗 老协议容易被GFW和谐

### Describe the Solution

1

**Comment by vernesong** [comment]
内核不支持

**Comment by vernesong** [comment]
用meta
