### ISSUE TITLE
[Feature] 支持自动导入geosite:cn的域名到 fake-ip-filter 

### ISSUE THREAD

**Issue by ghost** [vernesong/OpenClash#2988]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

希望实现 对大陆的域名不使用fake-ip，直接返回真实ip。目前的做法是需要把GEOSITE 手工一行行抄写到fake-ip-filter 里，很麻烦。

试过 dnsmasq 劫持国内域名的做法，但这样会导致 “OC访问控制>不走代理的局域网设备ip（Mac） 实现局域网设备”功能失效。所以只好用防火墙劫持的做法。但这种情况下，openclash不会自动添加 geosite:cn 到 fake-ip-filter 了。

### Describe the Solution

使用防火墙劫持时，支持自动导入geosite:cn的域名到 fake-ip-filter，和 dnsmasq 劫持时保持一致。

### Describe Alternatives

https://github.com/MetaCubeX/Clash.Meta/issues/366

**Comment by vernesong** [comment]
这个内核暂时不支持，如果直接一行还写进配置文件就太长了

**Comment by vernesong** [comment]
几万行还是别这样加到filter了吧，倒不如去内核那问问能不能支持geosite
