### ISSUE TITLE
[Bug] 能不能提供一个选项关掉自动更新

### ISSUE THREAD

**Issue by justin-himself** [vernesong/OpenClash#2990]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.78.beta

### Bug on Environment

Lean

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

.

### Describe the Bug

Openclash 大概每 90 分钟检查一下最新的内核, 如果 fetch 不到就会关掉代理卡在那一直尝试, 造成了上网时常中断的问题.

### OpenClash Log

<img width="1327" alt="image" src="https://user-images.githubusercontent.com/73123028/216781339-15799f66-cee3-4f8b-87ea-67c3c3ed56b9.png">

### Expected Behavior

添加一个按钮允许用户关闭自动检查更新

### Screenshots

![graph (3)](https://user-images.githubusercontent.com/73123028/216781451-46230b03-a973-4600-bcc5-f60134159ab1.png)

我特地跑了一个脚本观察问题, 网络不畅时去看必定有上述日志.

**Comment by justin-himself** [comment]
我将 `/usr/share/openclash/openclash_version.sh` 的内容改为

```bash
#!/bin/bash
echo "v0.45.78-beta" > /tmp/clash_last_version
exit 0
```

后问题就消失了.

![image](https://user-images.githubusercontent.com/73123028/216799659-c33cc94e-91e7-4351-8b7d-5361b78fbbf1.png)

**Comment by vernesong** [comment]
这个只是curl的一次正常文件获取，卡顿的问题不大可能是插件代码的问题，你不停留在设置页面就不会运行了

**Comment by justin-himself** [comment]
明白了 我把因果关系搞反了
