### ISSUE TITLE
[Bug] 最新版本openclash和圈x搭配有点问题

### ISSUE THREAD

**Issue by spirytuslove** [vernesong/OpenClash#2997]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.87-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

之前版本圈x开直连 家里openclashfakeip混合模式 meta内核 规则模式下可以翻墙 这版本圈x开了直连模式用家里的opeenclash规则模式就不能代理了 其他不开圈x的软件都能正常翻墙

### Describe the Bug

如上

### OpenClash Log

如上不兼容了

### Expected Behavior

手机开着圈x直连可以用openclash翻墙

**Comment by vernesong** [comment]
你看看控制面板里面的日志有什么错误

**Comment by spirytuslove** [comment]
没有错误 但我发现圈x开了直连模式现在日志里面国外流量前面都有sniff tcp开头  不开的话直接是tcp开头 开了圈x直连模式openclash国外流量都是翻不了墙 上个版本没问题
![BAD8A322-2850-404B-8BBF-7B8A8DC0BF9C](https://user-images.githubusercontent.com/64483414/217871424-9baa1a10-d115-458b-81a5-aacab3fcb057.jpeg)

**Comment by vernesong** [comment]
开debug看下

**Comment by spirytuslove** [comment]
> 开debug看下

![Uploading 3D29288C-B734-4CF9-A261-BD29051241B6.jpeg…]()

**Comment by spirytuslove** [comment]
![Uploading FE2E41F1-C026-41C9-9D11-5FEBA1724B1F.jpeg…]()

**Comment by spirytuslove** [comment]
![Uploading 60F15F76-C837-411A-888D-6DC45EF99342.jpeg…]()

**Comment by vernesong** [comment]
没传上来

**Comment by spirytuslove** [comment]
![B417C0AD-4D08-4FB7-BAF3-FFF0CF72ACB1](https://user-images.githubusercontent.com/64483414/218074400-41fd350e-b0e9-4a14-8dc4-9cc8e7ccce09.jpeg)

**Comment by vernesong** [comment]
没报错吗，那可能是内核的问题，因为更新过sniff相关

**Comment by spirytuslove** [comment]
对  只有这种debug 其他没了

**Comment by vernesong** [comment]
你试试tun混合

**Comment by spirytuslove** [comment]
我现在就是tun混合。。。

**Comment by vernesong** [comment]
不要用meta

**Comment by spirytuslove** [comment]
刚试了下

> 不要用meta

刚试了下把meta换了就没问题了

**Comment by Skyxim** [comment]
> 刚试了下
> 
> > 不要用meta
> 
> 刚试了下把meta换了就没问题了

QX 使用了加密 DNS（DoH）会影响 OC 劫持 DNS，之前域名嗅探会默认替换域名，嗅探改了格式加了控制是否替换之后，没有设置默认值导致不会发送域名到远程。最新的版本已经改成默认替换了。
根本解决方法还是用 QX  的 ssid 在家里时关闭 DoH

**Comment by spirytuslove** [comment]
我好像没检测到最新版本 是还没出来吗 另外qx的ssid在家时关掉doh要怎么设置。。。

**Comment by vernesong** [comment]
![image](https://user-images.githubusercontent.com/42875168/218125858-f008a899-be2c-4a49-a35f-8d9877d7ec9c.png)

**Comment by spirytuslove** [comment]
可以了 感谢

**Comment by ShawsonBian** [comment]
昨晚遇到同样的问题 晚上回家我也按照上面的方法试试
