### ISSUE TITLE
[Feature] 能否考虑在更新包内直接打包所有内核，或者考虑增加web手动上传并赋权的页面？

### ISSUE THREAD

**Issue by elle007011** [vernesong/OpenClash#2999]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

目前每次更新后下载内核经常失败，无论用哪个CDN都是反复的提示错误，无法下载。手动下载上传，web页面的默认路径还不对，ssh进去不太会搞，尴尬了。。。所以是否能考虑直接把内核打包到更新包内？更新后就是直接可用的状态？或者提供web页面上传并搞好的功能，造福小白

### Describe the Solution

如上

**Comment by vernesong** [comment]
![image](https://user-images.githubusercontent.com/42875168/217235559-9a098882-7175-42d5-a783-9e77e2e25a74.png)

**Comment by elle007011** [comment]
> ![image](https://user-images.githubusercontent.com/42875168/217235559-9a098882-7175-42d5-a783-9e77e2e25a74.png)

您好，我确实使用过这个功能。但是我将下载下来的meta core文件上载后（无论是否改名叫meta_core）均无反应。重启openwrt再进入openclash相关页面后，在meta内核项下依然显示未知。

**Comment by elle007011** [comment]
> 直接传压缩包

感谢，下次我这么做

**Comment by VioletEvergar-den** [comment]
> > ![image](https://user-images.githubusercontent.com/42875168/217235559-9a098882-7175-42d5-a783-9e77e2e25a74.png)
> 
> 您好，我确实使用过这个功能。但是我将下载下来的meta core文件上载后（无论是否改名叫meta_core）均无反应。重启openwrt再进入openclash相关页面后，在meta内核项下依然显示未知。

这个界面在哪，我没找到...

**Comment by elle007011** [comment]
> > > ![image](https://user-images.githubusercontent.com/42875168/217235559-9a098882-7175-42d5-a783-9e77e2e25a74.png)
> > 
> > 
> > 您好，我确实使用过这个功能。但是我将下载下来的meta core文件上载后（无论是否改名叫meta_core）均无反应。重启openwrt再进入openclash相关页面后，在meta内核项下依然显示未知。
> 
> 这个界面在哪，我没找到...

这个页面在“配置文件管理”页面的最上部分

**Comment by ttxs25830** [comment]
直接打包内核绝对是坏注意。我是无所谓，但是OpenWRT的官网还专门提示了，应该使安装包尽量小，因为很多人的路由器其实没那么多硬盘空间，只能把内核写到var去。
