### ISSUE TITLE
首次安装, 直接更新规则，会出现死循环

### ISSUE THREAD

**Issue by xlighting2017** [vernesong/OpenClash#3]
如果没有config.yml, 直接更新规则，会出现死循环

日志如图：
![image](https://user-images.githubusercontent.com/25970065/60335469-998e5500-99d0-11e9-80cc-d3634a8a547e.png)

而且好像 如果不添加配置， 只要再进入 openclash的页面，就会一直死循环..除非从Web logout...

**Comment by vernesong** [comment]
> 如果没有config.yml, 直接更新规则，会出现死循环
> 
> 日志如图：
> ![image](https://user-images.githubusercontent.com/25970065/60335469-998e5500-99d0-11e9-80cc-d3634a8a547e.png)
> 
> 而且好像 如果不添加配置， 只要再进入 openclash的页面，就会一直死循环..除非从Web logout...

安装的什么固件？

**Comment by vernesong** [comment]
> > 如果没有config.yml, 直接更新规则，会出现死循环
> > 日志如图：
> > ![image](https://user-images.githubusercontent.com/25970065/60335469-998e5500-99d0-11e9-80cc-d3634a8a547e.png)
> > 而且好像 如果不添加配置， 只要再进入 openclash的页面，就会一直死循环..除非从Web logout...
> 
> 安装的什么固件？

日志可以消除，对使用没有影响，循环是因为page在定时获取数据。

**Comment by xlighting2017** [comment]
固件是 lean openwrt, 在 OrangePi Zero Plus 上，不过我觉得应该和 固件无关？

这个循环获取数据会导致至少 25% CPU占用...  不过这算是个边角问题，就是提醒一下 :)

**Comment by vernesong** [comment]
> 固件是 lean openwrt, 在 OrangePi Zero Plus 上，不过我觉得应该和 固件无关？
> 
> 这个循环获取数据会导致至少 25% CPU占用... 不过这算是个边角问题，就是提醒一下 :)

考虑到页面不会长时间停留，问题应该不大，以后如果有更好的方法我会修改

**Comment by vernesong** [comment]
> 固件是 lean openwrt, 在 OrangePi Zero Plus 上，不过我觉得应该和 固件无关？
> 
> 这个循环获取数据会导致至少 25% CPU占用... 不过这算是个边角问题，就是提醒一下 :)

v0.30.3 不再输出此错误日志
