### ISSUE TITLE
重启openclash时候有时会卡住

### ISSUE THREAD

**Issue by miku-nakano** [vernesong/OpenClash#30]
在开机之后自动启动的openclash 100%会启动成功，只是重启openclash的话有很大机率会卡住，我用的是koolshare那个lede，请问是这个系统魔改的原因么？

能力有限，只能提供一些信息了：stop的第一步: 删除 OpenClash 防火墙规则...和第五步：删除 OpenClash 残留文件...，start的第七步: 设置 OpenClash 防火墙规则...经常会卡住。

比如卡在删除 OpenClash 防火墙规则这步的时候，手动在ssh中输入/etc/init.d/firewall restart >/dev/null 2>&1也会卡住，所以推测可能是系统问题，请问这个有解决的办法么？

**Comment by wangxin6** [comment]
koolshare 不是应该用专用的koolclash？

**Comment by miku-nakano** [comment]
> koolshare 不是应该用专用的koolclash？

koolclash不太好用，强制fakeip模式，老版本0.16.2的dns又有问题，在我这总解析错区域，openclash除了卡住之外，其他真是很完美

**Comment by wangxin6** [comment]
> > koolshare 不是应该用专用的koolclash？
> 
> koolclash不太好用，强制fakeip模式，老版本0.16.2的dns又有问题，在我这总解析错区域，openclash除了卡住之外，其他真是很完美

换原版或者lean版

**Comment by vernesong** [comment]
有收到反馈是跟网易云解锁冲突，你关闭试一下

**Comment by miku-nakano** [comment]
> 有收到反馈是跟网易云解锁冲突，你关闭试一下

可以了，多谢大大！没想到是这个问题。。
