### ISSUE TITLE
路由器开启OpenClash国内访问变慢。

### ISSUE THREAD

**Issue by LunaticTian** [vernesong/OpenClash#300]
旁路由LEDE安装OpenClash，主路由(padavan)DHCP网关 DNS均指向旁路由，**均已关闭ipv6**

> 以下均为相同策略订阅节点

- A 相同策略订阅节点，使用Clash for Windows国内外访问速度分流均正常。

使用不同软件情况：

- B 开启OpenClash，模式**Fake-IP（增强）模式**，DNS上游开启：国内访问较A明显变慢，国外访问正常但未分流。

- C 开启Koolclash:情况与B相比更为严重，国内网站响应速度更慢。

- D LEDE开启V2RAY走gfwlist黑名单模式:国内外访问与A相同均正常。

- E 手机使用Clash for Android：与A相同速度分流均正常。

A情况下查看日志可知国内域名均走直连，B由于***WebUI日志中没有输出***无法查看，C在WebUI中可查看日志输出显示国内域名均走直连。

B通过 WebUI 中的 **连接面板** 可知国内网站均走直连，但分流错误。

**DNS 配置**

![](http://img.lunatic.wang/c3.png)

**规则分流情况，已设定YouTube等网站分流，但查看日志发现均没有走YouTube等分流策略，这与A,E不相同。**

![](http://img.lunatic.wang/c1.png)
![](http://img.lunatic.wang/c2.png)

**A情况下的分流(Clash for Windows)**

![](http://img.lunatic.wang/c4.png)

**Comment by vernesong** [comment]
dns请求没有到达clash，建议你关闭路由上可能造成影响的插件，将路由的ip地址作为dns地址下发给客户端

**Comment by LunaticTian** [comment]
> dns 请求没有到达 clash，建议你关闭路由上可能造成影响的插件，将路由的 ip 地址作为 dns 地址下发给客户端

感谢解答！

分流原因应是DNS指向问题(由于搭建内网SS未修改DNS导致)。但国内访问速度还是有所下降，明显的感受就是未开启OpenClash的国内访问基本处于秒开，开启会延迟1-2秒。
已给OpenClash添加了运营商以及阿里DNS等，但是均未达到未开启状态访问速度。

**Comment by xpn282** [comment]
我用Fake-IP（增强）模式，自定义dns为2个运营商的，其它nds一律不用。。没发现国内反应慢的问题。。  国外也正常

**Comment by LunaticTian** [comment]
> 我用Fake-IP（增强）模式，自定义添加了2个运营商的dns，其它dns一律不用。。没发现国内反应慢的问题。。 国外也正常。。
> 
> 另：我这里的宽带只要用公共dns的话（如114之类的），国内访问就不正常，很慢

请问自带的dns也要勾选上吗，还是只用了两个自带的？

**Comment by LunaticTian** [comment]
> 我用Fake-IP（增强）模式，自定义添加了2个运营商的dns，其它dns一律不用。。没发现国内反应慢的问题。。 国外也正常。。
> 
> 另：我这里的宽带只要用公共dns的话（如114之类的），国内访问就不正常，很慢

请问自带的dns也要勾选上吗，还是只用了两个运营商自带的？

**Comment by vernesong** [comment]
dns只要填两个你当地最快的国内地址就行了，或者你可以切换到redir模式测试打开和关闭的情况下dns查血结果是否相同来判断是否是clash处理速度的问题

**Comment by LunaticTian** [comment]
> dns 只要填两个你当地最快的国内地址就行了，或者你可以切换到 redir 模式测试打开和关闭的情况下 dns 查血结果是否相同来判断是否是 clash 处理速度的问题

**开启redir 模式状态**

>root@Lunatic_NAS:~# !68
nslookup baidu.com
Server:		192.168.123.165
Address:	192.168.123.165#53

>Name:	baidu.com
Address: 220.181.38.148
Name:	baidu.com
Address: 39.156.69.79

**关闭Clash状态**
>root@Lunatic_NAS:~# nslookup baidu.com
Server:		192.168.123.165
Address:	192.168.123.165#53

Non-authoritative answer:
Name:	baidu.com
Address: 39.156.69.79


在Fake-IP（增强）中使用了本地提供的DNS，速度的确快了许多，但是与未开启状态相比还是有明显差距(虽然速度相差不大但能明显感觉得到)。
真的很高兴可以到路由器版clash，但是由于设备是X86应该不存在硬件性能的问题.....现在只能怀疑是否是clash处理的问题又或者是DNS问题，但是尝试了几个常用的DNS都没有达到未开启OpenClash的速度。
头疼:scream:

**Comment by xpn282** [comment]
> > 我用Fake-IP（增强）模式，自定义添加了2个运营商的dns，其它dns一律不用。。没发现国内反应慢的问题。。 国外也正常。。
> > 另：我这里的宽带只要用公共dns的话（如114之类的），国内访问就不正常，很慢
> 
> 请问自带的dns也要勾选上吗，还是只用了两个运营商自带的？

我用fake-ip模式，不勾选Openclash自带的dns，只用了运营商的2个dns而已，感觉是正常的。没觉得和关闭Openclash时有什么差别哦。可能我的观感比较差吧，没什么感觉到区别，我也觉得满足了

**Comment by LunaticTian** [comment]
> > > 我用 Fake-IP（增强）模式，自定义添加了 2 个运营商的 dns，其它 dns 一律不用。。没发现国内反应慢的问题。。 国外也正常。。
> > > 另：我这里的宽带只要用公共 dns 的话（如 114 之类的），国内访问就不正常，很慢
> > 
> > 
> > 请问自带的 dns 也要勾选上吗，还是只用了两个运营商自带的？
> 
> 我用 fake-ip 模式，不勾选 Openclash 自带的 dns，只用了运营商的 2 个 dns 而已，感觉是正常的。没觉得和关闭 Openclash 时有什么差别哦。可能我的观感比较差吧，没什么感觉到区别，我也觉得满足了

感谢回复，我这么测试的时候的确是有慢一点不过满足了哈哈哈哈~

**Comment by dengke80622** [comment]
确实，开启DNS自定后默认设置会导致国内服务b变慢，微博尤其明显，只用运营商DNS明显改善

**Comment by uupks** [comment]
> 确实，开启DNS自定后默认设置会导致国内服务b变慢，微博尤其明显，只用运营商DNS明显改善

我这也有这个现象，用运营商DNS国内网站秒开，用Clash的DNS服务，开国内网站要犹豫几秒，国外网站都正常。
我是Clash DNS配置监听的1053端口，在iptable里把udp 53端口访问转发到Clash监听的1053端口。

**Comment by siren202101** [comment]
可以试着使用一个方法解决，就是DNS高级里--指定（第二）DNS服务器--最快的国内DNS服务器，列表里填入国内的域名列表，国内域名列表可以通过github上的出国插件项目找到，修改填入

**Comment by jerrykkkkk** [comment]
我也是这个问题，请问你解决了吗？

**Comment by LunaticTian** [comment]
> 我也是这个问题，请问你解决了吗？ 
 
没有解决，后来不用路由器的clash了

**Comment by jerrykkkkk** [comment]
> > 我也是这个问题，请问你解决了吗？
> 
> 没有解决，后来不用路由器的clash了

我找到原因了，把“网络”---“Turbo ACC 网络加速设置”-所有都关掉，就正常了（不知道具有哪个影响，就都关了）

**Comment by rheatin** [comment]
> > > 我也是这个问题，请问你解决了吗？
> > 
> > 
> > 没有解决，后来不用路由器的clash了
> 
> 我找到原因了，把“网络”---“Turbo ACC 网络加速设置”-所有都关掉，就正常了（不知道具有哪个影响，就都关了）
> 
> 之前 重启clash 刚开始正常，一会就不对了，关掉加速后目前运行了 1天 一切正常

这个插件我就没装，还有好兄弟有其他解决方案吗？- -

**Comment by supen8012** [comment]
> > > 我也是这个问题，请问你解决了吗？
> > 
> > 
> > 没有解决，后来不用路由器的clash了
> 
> 我找到原因了，把“网络”---“Turbo ACC 网络加速设置”-所有都关掉，就正常了（不知道具有哪个影响，就都关了）
> 
> 之前 重启clash 刚开始正常，一会就不对了，关掉加速后目前运行了 1天 一切正常

同样发现这个问题，取消turbo acc，正常了几个小时，后来又很慢，微信登录也变得非常慢，甚至提示无网络

**Comment by pkl173** [comment]
> > > > 我也是这个问题，请问你解决了吗？
> > > 
> > > 
> > > 没有解决，后来不用路由器的clash了
> > 
> > 
> > 我找到原因了，把“网络”---“Turbo ACC 网络加速设置”-所有都关掉，就正常了（不知道具有哪个影响，就都关了）
> > 之前 重启clash 刚开始正常，一会就不对了，关掉加速后目前运行了 1天 一切正常
> 
> 同样发现这个问题，取消turbo acc，正常了几个小时，后来又很慢，微信登录也变得非常慢，甚至提示无网络

现在取消了turbo accDNS也用的公共的，用着没问题

**Comment by supen8012** [comment]
> > > > > 我也是这个问题，请问你解决了吗？
> > > > 
> > > > 
> > > > 没有解决，后来不用路由器的clash了
> > > 
> > > 
> > > 我找到原因了，把“网络”---“Turbo ACC 网络加速设置”-所有都关掉，就正常了（不知道具有哪个影响，就都关了）
> > > 之前 重启clash 刚开始正常，一会就不对了，关掉加速后目前运行了 1天 一切正常
> > 
> > 
> > 同样发现这个问题，取消turbo acc，正常了几个小时，后来又很慢，微信登录也变得非常慢，甚至提示无网络
> 
> 现在取消了turbo accDNS也用的公共的，用着没问题

用的哪个版本，最新版吗

**Comment by pkl173** [comment]
> > > > > > 我也是这个问题，请问你解决了吗？
> > > > > 
> > > > > 
> > > > > 没有解决，后来不用路由器的clash了
> > > > 
> > > > 
> > > > 我找到原因了，把“网络”---“Turbo ACC 网络加速设置”-所有都关掉，就正常了（不知道具有哪个影响，就都关了）
> > > > 之前 重启clash 刚开始正常，一会就不对了，关掉加速后目前运行了 1天 一切正常
> > > 
> > > 
> > > 同样发现这个问题，取消turbo acc，正常了几个小时，后来又很慢，微信登录也变得非常慢，甚至提示无网络
> > 
> > 
> > 现在取消了turbo accDNS也用的公共的，用着没问题
> 
> 用的哪个版本，最新版吗

是最新的

**Comment by supen8012** [comment]
> > > > > > > 我也是这个问题，请问你解决了吗？
> > > > > > 
> > > > > > 
> > > > > > 没有解决，后来不用路由器的clash了
> > > > > 
> > > > > 
> > > > > 我找到原因了，把“网络”---“Turbo ACC 网络加速设置”-所有都关掉，就正常了（不知道具有哪个影响，就都关了）
> > > > > 之前 重启clash 刚开始正常，一会就不对了，关掉加速后目前运行了 1天 一切正常
> > > > 
> > > > 
> > > > 同样发现这个问题，取消turbo acc，正常了几个小时，后来又很慢，微信登录也变得非常慢，甚至提示无网络
> > > 
> > > 
> > > 现在取消了turbo accDNS也用的公共的，用着没问题
> > 
> > 
> > 用的哪个版本，最新版吗
> 
> 是最新的

好的，谢谢，回头我试试

**Comment by ssupssup** [comment]
我已经弃用了open clash，有时间有心的时候再折腾

**Comment by dafashi888** [comment]
解决没有？我的变快了
________________________________
发件人: jpydej ***@***.***>
发送时间: 2023年1月11日 10:16
收件人: vernesong/OpenClash ***@***.***>
抄送: dafashi888 ***@***.***>; Comment ***@***.***>
主题: Re: [vernesong/OpenClash] 路由器开启OpenClash国内访问变慢。 (#300)


难受啊

―

**Comment by xhardsun** [comment]
现在来看只有通过重启才能恢复最初的性能，哥们你是怎么解决的





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vernesong/OpenClash"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月15日(星期天) 中午1:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [vernesong/OpenClash] 路由器开启OpenClash国内访问变慢。 (#300)





 解决没有？我的变快了 
 ________________________________ 
 发件人: jpydej ***@***.***&gt; 
 发送时间: 2023年1月11日 10:16 
 收件人: vernesong/OpenClash ***@***.***&gt; 
 抄送: dafashi888 ***@***.***&gt;; Comment ***@***.***&gt; 
 主题: Re: [vernesong/OpenClash] 路由器开启OpenClash国内访问变慢。 (#300) 
 
 
 难受啊 
 
 ―

**Comment by ssupssup** [comment]
没解决，弃用op了，有时间再折腾吧

**Comment by Ag-Rock** [comment]
> 我的是把绕过中国大陆打勾，就可以了

确实是，但国内去广告策略失效了！

**Comment by cyczq11** [comment]
> 我已经弃用了open clash，有时间有心的时候再折腾

出门左转不送

**Comment by tiandiyijian** [comment]
> > > 我也是这个问题，请问你解决了吗？
> > 
> > 
> > 没有解决，后来不用路由器的clash了
> 
> 我找到原因了，把“网络”---“Turbo ACC 网络加速设置”-所有都关掉，就正常了（不知道具有哪个影响，就都关了）
> 
> 之前 重启clash 刚开始正常，一会就不对了，关掉加速后目前运行了 1天 一切正常

我把“网络”---“Turbo ACC 网络加速设置”里的软件流量分载关了就正常了

**Comment by teng59420** [comment]
我把这个关闭就好了
![微信图片_20240628050756](https://github.com/vernesong/OpenClash/assets/174063398/860c160c-c37d-45a0-958d-34a7f88c8039)

**Comment by NTPlay4** [comment]
说一下我的方法
1.关闭open clash的本地DNS劫持,让本地DNS解析走路由器.
2.安装AdGuard Home，53重定向选择"使用53替换dnsmasq"，使路由器解析走AdGuard Home.
3.AdGuard Home上游DNS配置DoH(国密)地址，比如"https://dns.alidns.com/dns-query"，防止DNS解析明文传输
这个方法配置后，dns解析超快，还能用AdGuard Home进行DNS过滤，一举两得

**Comment by NTPlay4** [comment]
说一下我的方法
1.关闭open clash的本地DNS劫持,让本地DNS解析走路由器.
2.安装AdGuard Home，53重定向选择"使用53替换dnsmasq"，使路由器解析走AdGuard Home.
3.AdGuard Home上游DNS配置DoH(国密)地址，比如"https://dns.alidns.com/dns-query"，防止DNS解析明文传输
这个方法配置后，dns解析超快，还能用AdGuard Home进行DNS过滤，一举两得

**Comment by kkusala123** [comment]
clash的分流策略不是基于dns分流的么，你把dns的dns劫持给关了，不就失去了分流的功能了吗？

**Comment by siren202101** [comment]
> 说一下我的方法 1.关闭open clash的本地DNS劫持,让本地DNS解析走路由器. 2.安装AdGuard Home，53重定向选择"使用53替换dnsmasq"，使路由器解析走AdGuard Home. 3.AdGuard Home上游DNS配置DoH(国密)地址，比如"[https://dns.alidns.com/dns-query"，防止DNS解析明文传输](https://dns.alidns.com/dns-query%22%EF%BC%8C%E9%98%B2%E6%AD%A2DNS%E8%A7%A3%E6%9E%90%E6%98%8E%E6%96%87%E4%BC%A0%E8%BE%93) 这个方法配置后，dns解析超快，还能用AdGuard Home进行DNS过滤，一举两得

大佬，好像您是openclash的作者之一，有个疑问，就是我无论用AdGuard Home还是smatrdns取代路由的DNS解析，虽然速度是加快，但国内网站时不时走国外的DNS进行解析
但使用openclash的劫持就不会出现这个问题

**Comment by hnsci-ai** [comment]
> > 说一下我的方法 1.关闭open clash的本地DNS劫持,让本地DNS解析走路由器. 2.安装AdGuard Home，53重定向选择"使用53替换dnsmasq"，使路由器解析走AdGuard Home. 3.AdGuard Home上游DNS配置DoH(国密)地址，比如"[https://dns.alidns.com/dns-query"，防止DNS解析明文传输](https://dns.alidns.com/dns-query%22%EF%BC%8C%E9%98%B2%E6%AD%A2DNS%E8%A7%A3%E6%9E%90%E6%98%8E%E6%96%87%E4%BC%A0%E8%BE%93) 这个方法配置后，dns解析超快，还能用AdGuard Home进行DNS过滤，一举两得
> 
> 大佬，好像您是openclash的作者之一，有个疑问，就是我无论用AdGuard Home还是smatrdns取代路由的DNS解析，虽然速度是加快，但国内网站时不时走国外的DNS进行解析 但使用openclash的劫持就不会出现这个问题

openclash 劫持dns后，把网卡的dns地址改成 openclash 的ip 地址就可以了，我是这么解决的，

**Comment by dafashi888** [comment]
采用mosDNS+ADGuardhome形式。mosdns监听53端口。国内DNS用运营商的dns或用adguardhome的。ADGuardhome 的DNS用DOT加密国内的，如你说的阿里的。
 openclash的国内的监听adguardhome,国外的空着。

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by FayTromp** [comment]
我也遇到过类似问题，抓包分析下来是浏览器的 HTTPS OCSP 验证导致白屏或首屏时间过长。可以在靠前的规则加上
```
- DOMAIN-KEYWORD,ocsp,DIRECT
```

原因是 https://github.com/MetaCubeX/meta-rules-dat 这个 geosite 规则里面 **geolocation-!cn** 包含了 **ocsp.digicert.cn** 导致 digicert 的大陆 OCSP 服务器被 DNS 解析到了国外 IP 。dae 的作者也在他的项目里提到了这个问题 https://github.com/daeuniverse/dae/blob/ba19046acbc1cd6f0a39c491b9add2dffbaf20e1/README.md?plain=1#L38

除此之外还有微软、苹果、globalsign 这些大厂的 pki 服务器也可能被涵盖在各种规则里，从而被无意中路由到了代理服务器，或者 DNS 分流到国外了。这些都可能导致访问国内 HTTPS 站点的白屏时间延长甚至无法访问。

至于 OP 的问题，由于 OP 没有解释清楚是哪里慢了，单纯的“国内网站访问变慢”是很笼统的，有可能是：
- DNS 解析
  - 尝试检查 mosdns 或者 smartdns 策略是否配置了等待全部上游dns响应再返回下游
- 路由器的 TCP 回包没有回到正确的主机
  - 可以分别在路由器和客户端主机抓包，看 443 端口的 TCP 是否有重传
- TLS 握手超时
  - 抓包的时候可以特别注意一下 TLS Client Hello 前后的包的时间，看看是否是 TLS 握手有问题
  - 尝试访问一些国内的纯 HTTP 站点，看看是否会有这个问题
  - 都开始抓包了，那就顺便再抓一下 dns 的包看看延迟
- 浏览器开启了安全 DNS
  - 新版本的 chromium based 浏览器都添加了 DoH 支持，尝试关闭后再看

最后也可以尝试在客户端主机上用 curl 访问这些速度慢的 URL ，添加 `-vv` 参数观察请求情况，或者使用 https://github.com/reorx/httpstat 测试各步骤的耗时。

**Comment by luckyuptop** [comment]
> 说一下我的方法 1.关闭open clash的本地DNS劫持,让本地DNS解析走路由器. 2.安装AdGuard Home，53重定向选择"使用53替换dnsmasq"，使路由器解析走AdGuard Home. 3.AdGuard Home上游DNS配置DoH(国密)地址，比如"[https://dns.alidns.com/dns-query"，防止DNS解析明文传输](https://dns.alidns.com/dns-query%22%EF%BC%8C%E9%98%B2%E6%AD%A2DNS%E8%A7%A3%E6%9E%90%E6%98%8E%E6%96%87%E4%BC%A0%E8%BE%93) 这个方法配置后，dns解析超快，还能用AdGuard Home进行DNS过滤，一举两得

正解
