### ISSUE TITLE
[Feature] 程式易用性太差

### ISSUE THREAD

**Issue by PoorerImmune** [vernesong/OpenClash#3005]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

你這外掛程式釋出這麼多版本，為什麼就不在介面設計上多下點功夫呢？OpenClash 的設計太過複雜，選項之間層層嵌套，把使用者都搞暈了！我明明在 clash.yaml 檔案中寫好了節點資訊和代理規則，但是你的程式的預設選項和參數會直接覆寫我的這份檔案，規則集都重複了，直接導致 Clash 匹配規則的時間被延長。另外，你的程式缺乏繁體中文語言套件，我把 OpenWrt 的系統語言設為繁體中文後，你的程式就只顯示英文了。

### Describe the Solution

1. UI 設計要大改。Clash 的設定分組，頂部用一列頁籤就夠了，這樣邏輯清晰明瞭，不要在每個頁籤下面再加一列頁籤。
2. 使用者匯入 yaml 檔案後，程式要先讀取檔案內已經寫好的設定項，並且要將程式的設定值與寫好的部分保持一致，以 yaml 檔案裡的參數優先。
3. 去掉花裡胡哨的功能，一些進階操作對一般人來說用不到。還要去掉重複的內容，例如 Yacd Control Panel 和 Dashboard Control Panel，留一個就夠了。
4. 加入流媒體檢測功能，檢測當前代理節點能否解鎖 Netflix、TikTok 和 Disney+ 等流媒體的地區限定內容。

**Comment by Karmylr** [comment]
6

**Comment by zheshifandian** [comment]
感觉操作麻烦，你可以不用！

**Comment by dwbii** [comment]
> 感觉操作麻痹，你可以不用！

难用是事实，为什么不能说？你看恩山的发帖问OpenClash的就能看出来

**Comment by Ayase-chan** [comment]
确实难用，到现在还没剥离luci-compat，大改UI估计要老命

**Comment by a904055262** [comment]
太臃肿了，逼得我自己写了个启动器。那个LUCI对性能稍微差点的设备都得要了老命

**Comment by DockerCS** [comment]
好多页面都有DNS的设置，不晓得为啥，生怕用户没设置DNS么😂

**Comment by DockerCS** [comment]
> 太臃肿了，逼得我自己写了个启动器。那个LUCI对性能稍微差点的设备都得要了老命

好多页面都有DNS的设置，不晓得为啥，生怕用户没设置DNS么😂

**Comment by briantang1117** [comment]
确实 参考macOS版本的Clash X Pro搞就好了 搞这么多配置和重写

**Comment by VioletEvergar-den** [comment]
雀食难用，新手看了一脸懵逼，有点网咯基础的倒是还好

**Comment by 0x5826** [comment]
我也觉的完全没必要把所有功能都做出UI，熟悉clash的应该都熟悉yaml配置了，即便没有可以预设一个规则模版即可，一堆按钮很多人完全不知道从何开头使用。

**Comment by Karmylr** [comment]
最恶心的还得是启动时强制修改配置文件

**Comment by vernesong** [comment]
在改啦，先把覆写的移到单独一页去

**Comment by ttxs25830** [comment]
我的意见是将dashbord和yacd作为独立软件包提供，不要捆绑到主包内。另外，建议把所有的代理端口改为可选的，不要空占端口。

**Comment by 665465** [comment]
软件功能很强大，感谢作者的付出，换种说法，如果界面的易用性更好一点就好了，Mac的Clash X确实是比较容易的用法。

**Comment by HoldOnBro** [comment]
个人觉得现在这样挺好的，清清楚楚，各个选项起到什么作用V大也都写明白了
