### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by drunkbear999** [vernesong/OpenClash#3007]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

“服务器节点配置”中的“服务器延时”

### Describe the Solution

可以在“服务器节点配置”中将“服务器延时”加回去么？0.45.78之前的版本都有的，很方便甄别是哪个节点出了问题的，谢谢

### Additional Context

![Untitled](https://user-images.githubusercontent.com/65745608/217743437-c11857b9-bd63-4482-8cd1-157287ae05fc.jpg)

**Comment by vernesong** [comment]
测这个意义不大的，额外开销，fakeip下也不通
新版本因为添加了防火墙的DNS劫持，这个只能在dnsnasq转发的情况下才能用，所以取消了这个东西

**Comment by drunkbear999** [comment]
好的，谢谢
