### ISSUE TITLE
[Feature] 提供Fake-IP Filter不覆写选项

### ISSUE THREAD

**Issue by rbbt065** [vernesong/OpenClash#3009]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

目前open clash以可以设置dns选用配置文件中的配置或者采用open clash面板中的设置，但Fake-IP Filter这一项却会强制使用open clash面板中的设置替换配置文件中的设置。因此希望可以提供单纯使用配置文件中Fake-IP Filter域名的功能

### Describe the Solution

如同DNS设置一样，提供一个可以选择是否使用open clash设置的选项（如下图红框）
<img width="1654" alt="Image_20230210100306" src="https://user-images.githubusercontent.com/84926161/217981718-9539bd44-34d1-4d58-ab77-9010d21a7ca4.png">

**Comment by vernesong** [comment]
高级设置里面

**Comment by rbbt065** [comment]
> 高级设置里面

我知道在高级设置里面可以把自己的fake-ip filter粘贴进去， 但这样感觉有点麻烦。所以想问能否提供一个可以设置是否覆写config file里fakeip filter的选项，这样我就可以通过更改config file直接实现fakeip filter内域名的改变

**Comment by vernesong** [comment]
直接清空高级设置里的就行啦

**Comment by rbbt065** [comment]
> 直接清空高级设置里的就行啦

谢谢，全部删除以后成功应用配置文件中的fakeip filter配置(但是openclash面板中的fakeip filter不能全部删除，不然无法成功保存，通过在第一行写入无意义注释解决问题)
