### ISSUE TITLE
Openclash开启后多线多拨下行速度无法叠加

### ISSUE THREAD

**Issue by edmund-zhao** [vernesong/OpenClash#301]
## 系统信息： 
**内核版本：v0.19.0-4-g19f809b**
**平台信息：x86_64**
**规则配置文件头部：**
```python
port: 7890
socks-port: 7891
allow-lan: true
bind-address: "*"
mode: Rule
log-level: silent
external-controller: 0.0.0.0:9090
cfw-bypass:
  - qq.com
  - music.163.com
  - "*.music.126.net"
  - localhost
  - 127.*
  - 10.*
  - 172.16.*
  - 172.17.*
  - 172.18.*
  - 172.19.*
  - 172.20.*
  - 172.21.*
  - 172.22.*
  - 172.23.*
  - 172.24.*
  - 172.25.*
  - 172.26.*
  - 172.27.*
  - 172.28.*
  - 172.29.*
  - 172.30.*
  - 172.31.*
  - 192.168.*
  - <local>
cfw-latency-timeout: 5000
redir-port: 7892
secret: "123456"
external-ui: "/usr/share/openclash/dashboard"
hosts:
##Custom HOSTS##
#  experimental hosts, support wildcard (e.g. *.clash.dev Even *.foo.*.example.com)
#  static domain has a higher priority than wildcard domain (foo.example.com > *.example.com)
#  NOTE: hosts don't work with `fake-ip`

#  '*.clash.dev': 127.0.0.1
#  'alpha.clash.dev': '::1'
##Custom HOSTS END##
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874
  nameserver:
  - 114.114.114.114
  fallback:
  - tls://8.8.8.8:853
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4
```
尾部：
----
```python
- DOMAIN-SUFFIX,smtp,DIRECT
- DOMAIN-KEYWORD,aria2,DIRECT
- GEOIP,CN,DIRECT
- MATCH,🐟 漏网之鱼
```
**规则注释**：使用bianyuan.xyz进行转换
## 测试：
测试分为四个部分
1. 关闭openclash 测速
2. 开启openclash Redir-Host模式进行测速
3. 使用openclash Fake IP 测速
4. 使用openclash Redir-Host模式进行访问控制，把测速住进加入Openclash黑名单
## 测试一：

![关闭Openclash负载，测速前](https://s1.ax1x.com/2020/04/01/G8mERA.png)
这是测速前，关闭openclash时的负载
![测速时，关闭openclash.png](https://i.loli.net/2020/04/01/gJXqHh8wD17Mxop.png)
测速时，关闭openclash
![关闭openclash测速结果.png](https://i.loli.net/2020/04/01/PdtYvuzejGTElh4.png)
测速结果

## 测试二：
![Redit-Host负载.png](https://i.loli.net/2020/04/01/mvSKuT9Vq1bxk37.png)
负载截图慢了几秒，由图标看出，CPU并没由达到最大负载，大概在3-45%之间
![Redir-Host.png](https://i.loli.net/2020/04/01/c23xQFgMLt6EXJR.png)
测速结果

## 测试三：
![Fake-IP.png](https://i.loli.net/2020/04/01/rkJYWzfcXpvVm3t.png)
负载截图与Redit-HOst模式差不多，但速度下降了30-40Mbps
![Fake-IP测速结果.png](https://i.loli.net/2020/04/01/fOcJjBPuLax2qM4.png)
测速结果

## 测试四：
![黑名单模式.png](https://i.loli.net/2020/04/01/xolhvmEF5UDLPrV.png)
负载与结果
## 结论：
当子网的机器网络不走Openclash的时候，上下行速度可以达到最大值；当Openclash为Redir-Host模式时，下行速度只能跑满原本带宽200M，上行宽带却可以叠加至60M；当Openclash为Fake-IP模式时，下行速度再一次减少至160M，上行带宽却保持至60M。
## 猜想：
1.造成这种原因是因为Openclash与多线多播的适配不太好，导致只能叠加上行宽带。
2.造成这种原因是因为Openclash太吃CPU的性能了，导致J1900的上限为200M

**Comment by vernesong** [comment]
```
experimental:
  interface-name: en0 # outbound interface name
```
https://github.com/Dreamacro/clash/blob/dev/README.md

**Comment by edmund-zhao** [comment]
> ```
> experimental:
>   interface-name: en0 # outbound interface name
> ```
> 
> https://github.com/Dreamacro/clash/blob/dev/README.md

也就是说需要在yaml配置文件头部添加以下语句是吗？
```python
interface-name: 
  - VWAN1
  - VWAN2
  - VWAN3
  - VWAN4 
```
如果一个接口掉线了，是否会有1/4的流量无法访问网页呢？
感谢您的回复。

**Comment by edmund-zhao** [comment]
> ```
> experimental:
>   interface-name: en0 # outbound interface name
> ```
> 
> https://github.com/Dreamacro/clash/blob/dev/README.md

我是这样设置的
interface-name: VWAN1, VWAN3
测速上，结果没有任何改变

**Comment by edmund-zhao** [comment]
experimental:
  interface-name: eh1
experimental:
  interface-name: VWAN1, VWAN3
这样设置均无法改变测速结果
```python
port: 7890
socks-port: 7891
allow-lan: true
bind-address: "*"
mode: Rule
log-level: silent
external-controller: 0.0.0.0:9090
experimental:
  interface-name: VWAN1, VWAN4
```

**Comment by edmund-zhao** [comment]
刚刚我测试了一下BT上传，发现上传流量不会显示在Openclash的控制面板之中。并且上传速度可以跑满6-70M。暂时不知道原因是什么

**Comment by vernesong** [comment]
只能指定一个，你看看你的多拨出口都是eth0还是啥

**Comment by edmund-zhao** [comment]
我将多线多拨打开了绑定物理端口eh1，然后在配置文件头部添加了，但问题依旧存在。上行速度可以跑慢6-70M，上行可以叠加，下行无法叠加。
在 2020年4月2日，下午8:55，vernesong <notifications@github.com> 写道：

﻿

只能指定一个，你看看你的多拨出口都是eth0还是啥

**Comment by vernesong** [comment]
那暂时没有办法，负载均衡好像是通过路由表劫持流量，在那之前已经被clash转发出去了

**Comment by edmund-zhao** [comment]
是的，所以我关闭了多线多播功能，老老实实用200M

**Comment by vernesong** [comment]
主路由多拨，旁路由翻墙也可以的

**Comment by yzethan** [comment]
有人解决该问题了吗？
