### ISSUE TITLE
[Bug] GUI 中 实验性：绕过中国大陆 IP 的选项消失，只剩下 实验性：绕过中国大陆 IPv6

### ISSUE THREAD

**Issue by nick008a** [vernesong/OpenClash#3017]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

Fake IP(Mix)模式下，``本地 DNS 劫持``使用``使用防火墙转发``的时候，UI中找不到`实验性：绕过中国大陆 IP` 的开关，只有`实验性：绕过中国大陆 IPv6`在ipv6选项卡里。

但是从配置文件中，依然可以`option china_ip_route '1'` 启用该功能，并正常工作。

### Describe the Solution

将`实验性：绕过中国大陆 IP` 开关始终显示。

**Comment by yuxuan0107** [comment]
发现同样问题

**Comment by gitcook** [comment]
对 fakeip 模式 这个在哪设置？

**Comment by TnZzZHlp** [comment]
因为此功能依赖dnsmasq,你都不启用dnsmasq转发dns了,自然没法启用
![图片](https://user-images.githubusercontent.com/98214647/218927114-8fa12f8e-6833-4c4a-84ae-284fdd969dd5.png)
这个issue可以关闭了

**Comment by TnZzZHlp** [comment]
> chnroute 里面有一部分是ip地址，这些中国ip是被加入到ipset里给防火墙绕过的（假如客户端直接根据IP地址发起了请求，如游戏），这部分不依赖dnsmasq吧？dnsmasq只影响域名。
> 
> 另外，从配置文件中，依然可以option china_ip_route '1' 启用该功能，并正常工作。另外一个同类功能，绕过中国大陆 IPv6 也是不依赖dnsmasq的。

那这个你得跟v大反馈了
