### ISSUE TITLE
v0.19.0-4-g19f809b内核版本编译存在严重问题

### ISSUE THREAD

**Issue by ikelvingo** [vernesong/OpenClash#302]
0.19.0-2内核版本替换v0.19.0-4-g19f809b后，看日志成功启动，但无法正常转发流量，使用0.19.0-2覆盖回滚后，一切正常。

**Comment by okaygh** [comment]
我看着没人反应最新内核有问题,还以为只有我遇到了,升了最新内核启动是成功的,但是根本上不了网,日志又不报错,只能下回旧的内核用,折腾了一大圈...

**Comment by javierzhang0504** [comment]
我也遇到了一样的问题，但是找不到老内核在哪下载。。。

**Comment by vernesong** [comment]
什么架构

**Comment by javierzhang0504** [comment]
x86-64

**Comment by okaygh** [comment]
[https://i.jpg.dog/img/6df7e9974400176e75e82556112fd0f8.jpg](url)
这个也有问题

**Comment by javierzhang0504** [comment]
在哪里可以下载老版本openclash内核啊

**Comment by vernesong** [comment]
> 在哪里可以下载老版本openclash内核啊

之前的release都有啊

**Comment by javierzhang0504** [comment]
> > 在哪里可以下载老版本openclash内核啊
> 
> 之前的release都有啊

嗯，是我脑抽了：（

**Comment by ikelvingo** [comment]
我是用的是x64架构

**Comment by soriano** [comment]
我两台armv8 n1旁路，一台升级了可以正常使用，另一台如楼主问题一样，一切启动日志正常，但是要开全局模式才能走代理，规则模式失效，两台设置是一模一样的，有问题的那台选择了回滚

**Comment by Misaka-0x447f** [comment]
更新了

**Comment by vernesong** [comment]
[clash-linux-amd64.tar.gz](https://github.com/vernesong/OpenClash/files/4428886/clash-linux-amd64.tar.gz)
[clash-linux-armv8.tar.gz](https://github.com/vernesong/OpenClash/files/4428891/clash-linux-armv8.tar.gz)

未压缩版本

**Comment by c71an** [comment]
用upx3.9.5压缩，不要用3.9.6

**Comment by ikelvingo** [comment]
v0.19.0-5-g5591e15内核版本解决此问题，close。
