### ISSUE TITLE
[Bug] 在ImmortalWrt master分支使用时保存配置和应用配置报错

### ISSUE THREAD

**Issue by ximiTech** [vernesong/OpenClash#3020]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.87-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

无

### Describe the Bug

在ImmortalWrt配合Meta Core使用时发现的一点问题
1.使用tuic模式时无法打开twitch网站主页，而使用vless时可以
2.无法访问raw.githubusercontent.com的文件，某些图片加载会失败，规则已添加的情况下
3.配置文件管理页面-配置文件编辑-保存配置和应用配置 在已上传配置文件后失效，提示无法访问cgi-bin/luci/admin/services/openclash/config

### OpenClash Log

无

### Expected Behavior

1.tuic模式能打开twitch
2.能访问githubusercontent
3.保存和应用配置正常

**Comment by vernesong** [comment]
tuic等内核更新同步官方吧

**Comment by ximiTech** [comment]
可能是我这边搞杂了，我再试试看。。。

**Comment by ximiTech** [comment]
经测试第1,2个问题不存在
第3个：配置文件管理页面-配置文件编辑-保存配置和应用配置 在已上传配置文件后失效，提示无法访问cgi-bin/luci/admin/services/openclash/config 还是存在
