### ISSUE TITLE
[Bug] 错误：下载失败，请检查网络或稍后再试

### ISSUE THREAD

**Issue by AkarinLiu** [vernesong/OpenClash#3021]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.87-beta

### Bug on Environment

Other

### Bug on Platform

Linux-arm64

### To Reproduce

点击“启动OpenClash”按钮后提示如下：
错误：【FastLink】下载失败，请检查网络或稍后再试...

### Describe the Bug

配置文件无法下载

### OpenClash Log

[OpenClash-2023-2-17-9-49-15.log](https://github.com/vernesong/OpenClash/files/10762472/OpenClash-2023-2-17-9-49-15.log)

### Expected Behavior

望能够正常下载配置文件

**Comment by wangshenghao1** [comment]
I have the same problem
