### ISSUE TITLE
tun内核无法下载 

### ISSUE THREAD

**Issue by hyy34** [vernesong/OpenClash#3022]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.87

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-armv7

### To Reproduce

dev meta内核都可以下载，但是tun无法下载，跳转的网站404。

### Describe the Bug

tun内核跳转的网站是

https://raw.githubusercontent.com/vernesong/OpenClash/master/core-lateset/premium/clash-linux-armv7-2023.01.29-3-gfce8649.gz

### OpenClash Log

OpenClash 调试日志

生成时间: 2023-02-17 17:33:05
插件版本: v0.45.87-230
隐私提示: 上传此日志前请注意检查、屏蔽公网IP、节点、密码等相关敏感信息

```

#===================== 系统信息 =====================#

主机型号: P&W R619AC 128M
固件版本: OpenWrt 22.03.3 01.19.2023
LuCI版本: git-24.018.72712-6d712c3
内核版本: 5.15.88
处理器架构: arm_cortex-a7_neon-vfpv4

#此项有值时,如不使用IPv6,建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: hybrid

#此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 

#===================== 依赖检查 =====================#

dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
ca-certificates: 未安装
ipset: 已安装
ip-full: 已安装
libcap: 已安装
libcap-bin: 已安装
ruby: 已安装
ruby-yaml: 已安装
ruby-psych: 已安装
ruby-pstore: 已安装
kmod-tun(TUN模式): 已安装
luci-compat(Luci >= 19.07): 已安装
kmod-inet-diag(PROCESS-NAME): 已安装
unzip: 已安装
iptables-mod-tproxy: 已安装
kmod-ipt-tproxy: 已安装
iptables-mod-extra: 已安装
kmod-ipt-extra: 未安装
kmod-ipt-nat: 未安装

#===================== 内核检查 =====================#

运行状态: 未运行
已选择的架构: linux-armv7

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 
Tun内核文件: 不存在
Tun内核运行权限: 否

Dev内核版本: v1.13.0-3-gfbf2f26
Dev内核文件: 存在
Dev内核运行权限: 正常

Meta内核版本: alpha-ge59c35a3
Meta内核文件: 存在
Meta内核运行权限: 正常

#===================== 插件设置 =====================#

当前配置文件: /etc/openclash/config/amy.yaml
启动配置文件: /etc/openclash/amy.yaml
运行模式: redir-host-tun
默认代理模式: rule
UDP流量转发(tproxy): 启用
DNS劫持: Dnsmasq 转发
自定义DNS: 停用
IPV6代理: 停用
IPV6-DNS解析: 停用
禁用Dnsmasq缓存: 启用
自定义规则: 停用
仅允许内网: 启用
仅代理命中规则流量: 停用
仅允许常用端口流量: 停用
绕过中国大陆IP: 停用
路由本机代理: 启用

#启动异常时建议关闭此项后重试
混合节点: 停用
保留配置: 停用

#启动异常时建议关闭此项后重试
第三方规则: 停用

### OpenClash Config

_No response_

### Expected Behavior

可以更新，手动或自动都可。

### Screenshots

_No response_

**Comment by tinygrox** [comment]
是不是没有在上面选择自己的编译版本？我是没有选择编译版本的时候才会出现这种情况

**Comment by hyy34** [comment]
> 是不是没有在上面选择自己的编译版本？我是没有选择编译版本的时候才会出现这种情况

编译版本是自动选择的，已经网页下载，自行复制到规定位置了，目测是跳转的链接有问题，截至目前测试可以正常下载到本地了。

**Comment by fabian4** [comment]
https://raw.githubusercontent.com/vernesong/OpenClash/master/core-lateset/premium/clash-linux-armv7-2023.01.29-3-gfce8649.gz

这个地址我也一直都是 404 下载不了
