### ISSUE TITLE
[Feature] fakeip 模式支持绕过某个mac地址

### ISSUE THREAD

**Issue by cjwddtc** [vernesong/OpenClash#3024]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

fakeip 模式支持绕过某个mac地址，目前fakeip模式下无法像redir-host模式一样绕过某个mac地址，

### Describe the Solution

在dns选项为使用防火墙转发时，可以通过iptables/nftables的规则来绕fakeip dns对该mac地址dns请求的劫持，其他部分保持和redir-host模式一样即可。

**Comment by cjwddtc** [comment]
#2506 
已经有一个issue不过似乎超时关闭了

**Comment by cjwddtc** [comment]
似乎已经解决了

**Comment by Genv1er** [comment]
> 似乎已经解决了

请问楼主怎么解决的
