### ISSUE TITLE
[Feature] 添加插件系统

### ISSUE THREAD

**Issue by ttxs25830** [vernesong/OpenClash#3026]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

考虑到本软件包需求较大，也有许多人提出问题，但是由于OpenWRT、Luci系统和其他基本插件的联动较为复杂，本项目的维护者并不多，好多问题长期无法得到解决，因此我建议加入插件机制：在OpenClash达到某些运行生命周期时，调用一个用户指定的脚本，允许用户对生成的clash配置文件进行进一步处理。

### Describe the Solution

以下实现细节皆为举例：

在`/usr/share/clash/plugin`下创建一个文件夹，允许用户编辑其中的文件。

- 在OpenClash生成完成配置文件，即将启动时，先清空`/usr/share/clash/plugin/tmp/`，然后将编辑完成的配置文件写入`/usr/share/clash/plugin/tmp/<配置文件名>.yaml`，授予写入权限，然后执行`/usr/share/clash/plugin/main.sh prestart --name <配置文件名>`，等待命令执行完成后再将该文件移动到真正位置执行。
- 在OpenClash停止后执行同上过程，但将`prestart`改为`poststop`，并执行完成后不移动文件

这样以来，举例来说，如果有人需要保存对配置文件的修改，则可以在plugin目录内保存一个其他版本，然后将其与新文件按照自定义的规则合并。

**Comment by vernesong** [comment]
dev已经加了，自定义覆写脚本

**Comment by ttxs25830** [comment]
真的抱歉，今天刚看到。。。
