### ISSUE TITLE
[Bug] 访问控制页签下部分内容无法正常显示

### ISSUE THREAD

**Issue by GOUKI9999** [vernesong/OpenClash#3027]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.87-beta

### Bug on Environment

Lean

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

重启，清理luci cache，重新安装ipk都还存在，除提及的一处外，其他显示

### Describe the Bug

全局设置-访问控制页签下

原本前三行应该出现的三个选项：

局域网访问控制模式
走代理的局域网设备 IP
走代理的局域网设备 Mac

消失，直接从第四个选项出现，而且查看网页代码时发现前三行的luci代码都存在，但不知道为何无法显示，而且填入的白名单局域网ip也在正常生效，只是因为luci显示不全无法操作了

### OpenClash Log

OpenClash 调试日志

生成时间: 2023-02-20 16:56:35
插件版本: v0.45.87-beta
隐私提示: 上传此日志前请注意检查、屏蔽公网IP、节点、密码等相关敏感信息

```

#===================== 系统信息 =====================#

主机型号: Intel(R) Celeron(R) CPU J3160 @ 1.60GHz : 4 Core 4 Thread
固件版本: OpenWrt GDQ Winter[2022]
LuCI版本: git-21.335.48743-5f363d9-1
内核版本: 5.10.88
处理器架构: x86_64

#此项有值时,如不使用IPv6,建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: 

#此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 127.0.0.1#7353 127.0.0.1#5333

#===================== 依赖检查 =====================#

dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
libcap: 已安装
libcap-bin: 已安装
ruby: 已安装
ruby-yaml: 已安装
ruby-psych: 已安装
ruby-pstore: 已安装
kmod-tun(TUN模式): 已安装
luci-compat(Luci >= 19.07): 已安装
kmod-inet-diag(PROCESS-NAME): 未安装
unzip: 已安装
iptables-mod-tproxy: 已安装
kmod-ipt-tproxy: 已安装
iptables-mod-extra: 已安装
kmod-ipt-extra: 已安装
kmod-ipt-nat: 已安装

#===================== 内核检查 =====================#

运行状态: 运行中
进程pid: 29723
运行权限: 29723: cap_dac_override,cap_net_bind_service,cap_net_admin,cap_net_raw,cap_sys_ptrace,cap_sys_resource=eip
运行用户: nobody
已选择的架构: linux-amd64

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 2023.02.16
Tun内核文件: 存在
Tun内核运行权限: 正常

Dev内核版本: v1.13.0-3-gfbf2f26
Dev内核文件: 存在
Dev内核运行权限: 正常

Meta内核版本: alpha-g4c25f5e7
Meta内核文件: 存在
Meta内核运行权限: 正常

#===================== 插件设置 =====================#

当前配置文件: /etc/openclash/config/111.yaml
启动配置文件: /etc/openclash/111.yaml
运行模式: redir-host-tun
默认代理模式: rule
UDP流量转发(tproxy): 停用
DNS劫持: 停用
自定义DNS: 启用
IPV6代理: 停用
IPV6-DNS解析: 停用
禁用Dnsmasq缓存: 停用
自定义规则: 停用
仅允许内网: 停用
仅代理命中规则流量: 启用
仅允许常用端口流量: 启用
绕过中国大陆IP: 停用
路由本机代理: 启用

#启动异常时建议关闭此项后重试
混合节点: 停用
保留配置: 停用

#启动异常时建议关闭此项后重试
第三方规则: 停用

### OpenClash Config

```shell
暂无
```

### Expected Behavior

恢复正常的显示情况

### Screenshots

![image](https://user-images.githubusercontent.com/11640942/220059135-3c4d02e6-29ab-4848-ade7-8f35c786d551.png)

**Comment by vernesong** [comment]
停用dns劫持的暂时会隐藏，等新版本

**Comment by GOUKI9999** [comment]
> 

哦哦原来如此，我因为是使用dnsmasq到adguard到opclash的套娃，所以没有开dns劫，但这是这一个版本新加入的设定吗，因为我记得上一个版本我也是这样设定的，似乎没有隐藏选项的结果

**Comment by GOUKI9999** [comment]
> 

抱歉还有个问题，我发现watchdog，在打开劫持dns后，会强制修改dnsmaq的转发端口到openclash的对应dns端口，这就造成实际上我无法手动修改这部分，现在您这边对于这类问题有什么建议。

如上我可能需要通过的是dnsmasq--adguardhome-openclash这样的两层转发，但现在同时我因为需要使用白名单，所以就很困扰，需要自己修改或者注释掉watchdog中的相关部分实现吗？

**Comment by vernesong** [comment]
更新dev，关闭劫持

**Comment by GOUKI9999** [comment]
> 
已更新，但关闭劫持之后就无法使用黑白名单的设备控制——这在我环境目前是必须的，所以现在只能还是通过手动指定dnsmasq并修改watchdog才能实现自定义上级转发

**Comment by GOUKI9999** [comment]
昨天更新到dev 59 beta，看到luci部分已经调整，问题解决
