### ISSUE TITLE
打开太多文件报错

### ISSUE THREAD

**Issue by ct66683** [vernesong/OpenClash#303]
![20200402100854](https://user-images.githubusercontent.com/43426911/78203672-29b27b00-74ca-11ea-82d0-7120a03967de.png)
如图，也更新了最新版本，日志总会弹出这样的报错，是我的配置问题吗？

9090端口是控制面板运行的端口。

尝试过提升file descriptors的上限，但不久之后还是会出现这个报错

**Comment by vernesong** [comment]
可能是调用api的时候出现问题，你可以尝试注释
https://github.com/vernesong/OpenClash/blob/52b8308dafc2e5d842277c7bf70c8b890694bfc3/luci-app-openclash/files/etc/init.d/openclash#L967
https://github.com/vernesong/OpenClash/blob/52b8308dafc2e5d842277c7bf70c8b890694bfc3/luci-app-openclash/files/etc/init.d/openclash#L942

**Comment by ct66683** [comment]
> 可能是调用api的时候出现问题，你可以尝试注释
> https://github.com/vernesong/OpenClash/blob/52b8308dafc2e5d842277c7bf70c8b890694bfc3/luci-app-openclash/files/etc/init.d/openclash#L967
> 
> 
> https://github.com/vernesong/OpenClash/blob/52b8308dafc2e5d842277c7bf70c8b890694bfc3/luci-app-openclash/files/etc/init.d/openclash#L942

这样修改的话，会导致Yacd 控制面板打不开吗？
![image](https://user-images.githubusercontent.com/43426911/78220371-fbe22c00-74f3-11ea-9638-269dc4f8f224.png)

**Comment by ct66683** [comment]
另外，我已注释上述两行，但仍有此情况产生

![image](https://user-images.githubusercontent.com/43426911/78238218-e8908a00-750e-11ea-921a-8c370a9cd728.png)

**Comment by vernesong** [comment]
```
https://github.com/vernesong/OpenClash/blob/52b8308dafc2e5d842277c7bf70c8b890694bfc3/luci-app-openclash/files/etc/init.d/openclash#L1029
```
这一行也注释掉呢

**Comment by ct66683** [comment]
这个也注释了，不过这个问题还是有的。

另外clash服务有频繁重启的情况，没出现什么其他报错？是因为wrt系统过载的原因吗？因为从控制面板看到CPU使用率都在60%以上。
![image](https://user-images.githubusercontent.com/43426911/78419222-3c69b300-7676-11ea-9d77-d8a9659fb22a.png)

![image](https://user-images.githubusercontent.com/43426911/78419228-455a8480-7676-11ea-8d2c-5d7599d8618a.png)

**Comment by vernesong** [comment]
一般的软路由性能就够了，以前出现这种情况大多是因为有回环的情况，如果你确定规则和设置没问题的话，建议你换一下固件。

**Comment by ct66683** [comment]
明白了，非常感谢！

**Comment by ZeaKyX** [comment]
完全一样的情况，突然占cpu，问题解决了吗？

**Comment by ct66683** [comment]
> 完全一样的情况，突然占cpu，问题解决了吗？

没有，注释了三行代码，依然有问题存在。
可能是我这边的使用人数较多的原因
