### ISSUE TITLE
国区Safari浏览器使用Google搜索引擎重定向问题[Feature] 

### ISSUE THREAD

**Issue by Turingrun** [vernesong/OpenClash#3032]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

中国地区的Apple设备的Safari浏览器，默认的Google搜索引擎只能指向弃用的google.cn域名。不知道openclash是否支持重定向/或者是URL重写等功能，或者是clash内核支持，但是openclash还未开发出相关配置。希望可以将google.cn自动重定向到google.com.hk域名。

### Describe the Solution

希望可以通过https解密等功能，将google.cn重定向到google.com.hk

**Comment by vernesong** [comment]
不支持的
