### ISSUE TITLE
[Bug] 用dev拉取的最新代码，编译后仍然是v0.45.89，需要在插件界面点更新，才能更新至v0.45.90，已经编译过几次了

### ISSUE THREAD

**Issue by RodmanWang** [vernesong/OpenClash#3035]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.89

### Bug on Environment

Lean

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

用dev拉取的最新代码，编译后仍然是显示v0.45.89，需要在插件界面点更新，才能更新至v0.45.90

### Describe the Bug

用dev拉取的最新代码，编译后仍然是显示v0.45.89，需要在插件界面点更新，才能更新至v0.45.90

### OpenClash Log

不需要

### Expected Behavior

需要修复

**Comment by vernesong** [comment]
忘改了，晚点修下action

**Comment by iKira** [comment]
0.46.050-beta也出现了这个问题，编译到OpenWrt里依然是0.46.033-beta，仍需手动升级至0.46.050-beta。
