### ISSUE TITLE
[Bug] DNS配置问题

### ISSUE THREAD

**Issue by momonoshiori** [vernesong/OpenClash#3037]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.90-beta

### Bug on Environment

Other

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

Meta内核的proxy-server-nameserver，nameserver-policy里只要填入DoH类型DNS就无法解析（比如tls://1.0.0.1:853 https://1.1.1.1/dns-query）运行正常但是没有服务器或者服务器无法解析 其他位置填入DoH类型DNS没有测试

### Describe the Bug

DoH类型DNS无法使用

### OpenClash Log

日志没有报错内容

### Expected Behavior

希望修复DoH类型DNS

**Comment by skr3328** [comment]
一模一样的现象，发现是dns根本不解析，多谢楼主定位出具体问题

**Comment by vernesong** [comment]
![image](https://user-images.githubusercontent.com/42875168/221387109-0136a22d-da5d-4817-864e-c323dafb5bbe.png)
![image](https://user-images.githubusercontent.com/42875168/221387115-8ae4a82f-602d-4cac-b51c-4bb38b918b1e.png)
没啥问题啊，我自己也在用

**Comment by momonoshiori** [comment]
完全清除配置后正常了，必须手动删掉所有配置才恢复正常，感谢测试
