### ISSUE TITLE
不能通过sockket5和http(s)代理端口上网

### ISSUE THREAD

**Issue by sheiy** [vernesong/OpenClash#304]
clash配置页
![image](https://user-images.githubusercontent.com/12210038/78225125-449de300-74fc-11ea-811a-971bc9b0dfe9.png)
端口映射页
![image](https://user-images.githubusercontent.com/12210038/78225190-64cda200-74fc-11ea-81d9-64fe2a087afd.png)
LAN口配置
![image](https://user-images.githubusercontent.com/12210038/78225250-7e6ee980-74fc-11ea-9571-41bf3f022cbe.png)
防火墙配置
![image](https://user-images.githubusercontent.com/12210038/78225298-9181b980-74fc-11ea-984c-8083c72689d4.png)
![image](https://user-images.githubusercontent.com/12210038/78225320-98103100-74fc-11ea-9094-2d6349a2715a.png)
![image](https://user-images.githubusercontent.com/12210038/78225338-9fcfd580-74fc-11ea-9d51-3e2d04cb6733.png)

**Comment by ct66683** [comment]
你可以试试clash的控制，看看是否有代理流量出入，再检查下服务端代理是否正常

**Comment by sheiy** [comment]
@ct66683 请教下
![image](https://user-images.githubusercontent.com/12210038/78336122-6dd47700-75c1-11ea-9306-d78cbb4bc23f.png)
访问youtube怎么命中了直连规则啊

规则文件如下
[config.zip](https://github.com/vernesong/OpenClash/files/4425677/config.zip)

**Comment by vernesong** [comment]
开其他dns插件了吧，dns请求没到clash

**Comment by sheiy** [comment]
@vernesong 没有啊  刚下载的op系统 然后就只装了clash

**Comment by vernesong** [comment]
> @vernesong 没有啊  刚下载的op系统 然后就只装了clash

正常情况日志里应该有域名，检查一下规则是否完整，路由关闭ipv6，下发路由地址给客户端dns

**Comment by sheiy** [comment]
嗯 谢谢
