### ISSUE TITLE
[Bug] 升级0.45.90 beta一键配置无法使用

### ISSUE THREAD

**Issue by youngxlover** [vernesong/OpenClash#3045]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.90.beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

升级后重置配置，启用一键配置，记录显示

警告：由于第三方规则设置中的策略组名称与配置文件中的不符或不存在，停止继续设置第三方规则！

无法访问外网。

### Describe the Bug

升级后重置配置，启用一键配置，记录显示

警告：由于第三方规则设置中的策略组名称与配置文件中的不符或不存在，停止继续设置第三方规则！

无法访问外网。

### OpenClash Log

于之前版本保持一致的配置

### Expected Behavior

希望可以正常运行一键配置

**Comment by adminidor** [comment]
https://github.com/vernesong/OpenClash/issues/3038

**Comment by ItsRyanWu** [comment]
所以这个是啥原因？我也遇到了

> 由于第三方规则设置中的策略组名称与配置文件中的不符或不存在，停止继续设置第三方规则！
