### ISSUE TITLE
[Feature] 是否支持Script Shortcut功能

### ISSUE THREAD

**Issue by meesii** [vernesong/OpenClash#3048]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

我设置了Script Shortcut，然后在rules中使用- SCRIPT,quic,REJECT，启动时提示“unsupported rule type SCRIPT”

### Describe the Solution

麻烦作者回复一下openclas是否支持SCRIPT规则，不支持的话我就不折腾了

**Comment by vernesong** [comment]
meta不支持，tun内核才有
