### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by xiuxiudada** [vernesong/OpenClash#3051]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.92-beta

### Bug on Environment

Lean

### Bug on Platform

Linux-arm64

### To Reproduce

自动更新订阅，使用的是自己搭建在腾讯云服务器上的sub Converter，没有使用在线订阅转换，其他平台一切正常。

### Describe the Bug

一直会更新失败，手动重启openclash之后再手动更新没有问题。

### OpenClash Log

2023-03-01 16:39:47 错误：【xxx】下载失败，请检查网络或稍后再试...
2023-03-01 16:39:13【/tmp/yaml_sub_tmp_config.yaml】下载失败：【curl: (28) Connection timeout after 10001 ms】
2023-03-01 16:39:13【/tmp/yaml_sub_tmp_config.yaml】下载失败：【curl: (28) Connection timeout after 10001 ms】
2023-03-01 16:39:13【/tmp/yaml_sub_tmp_config.yaml】下载失败：【curl: (28) Connection timeout after 10001 ms】

### Expected Behavior

1

### Screenshots

<img width="1026" alt="截屏2023-03-01 18 03 08" src="https://user-images.githubusercontent.com/38947822/222107493-48c84f23-1dc8-446c-8491-38f0239ddbde.png">

**Comment by vernesong** [comment]
没转换就是直接curl去下载，你看看本机网络是不是通的
开着插件更新就可能是其他问题，看日志说怎么回事

**Comment by xiuxiudada** [comment]
> 没转换就是直接curl去下载，你看看本机网络是不是通的 开着插件更新就可能是其他问题，看日志说怎么回事

![QQ截图20230301210553](https://user-images.githubusercontent.com/38947822/222147575-2a56e559-311e-42cd-94b4-217a132d98f8.png)
使用命令行curl 订阅链接就是返回的这些东西。

**Comment by xiuxiudada** [comment]
![QQ截图20230301210742](https://user-images.githubusercontent.com/38947822/222147942-7868ae81-cbc0-4c0d-9a52-308246243a95.png)
然后这是插件的日志..

> 没转换就是直接curl去下载，你看看本机网络是不是通的 开着插件更新就可能是其他问题，看日志说怎么回事

**Comment by vernesong** [comment]
curl -SL "url" -o /tmp/config.yaml

**Comment by xiuxiudada** [comment]
> curl -SL "url" -o /tmp/config.yaml

可以下载的
![QQ截图20230301213714](https://user-images.githubusercontent.com/38947822/222154435-7db670f6-a6d8-4622-8f21-88edffb6587a.png)

**Comment by vernesong** [comment]
那应该是下载太慢了，我改下超时
