### ISSUE TITLE
[Bug] 仅代理命中规则流量: 启用 选项找不到，  - DST-PORT,80 443 22自动加入配置

### ISSUE THREAD

**Issue by GOUKI9999** [vernesong/OpenClash#3059]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

之前通过这一功能选项开关，可以选择是否加入这几条，现在这个选项消失后似乎变成了默认打开
即似乎一定会自动加入这三条 dst-port，这样使得兜底规则的行为和原配置文件不符，起码使所有22绕行了代理是预期之外的

要通过定时手动删除或注释掉这三条显然不是理想的解决方案

### Describe the Solution

有对应开关或者明确的描述，使用户理解这一功能的效果和对原配置文件的修改造成的影响
就目前而言和“仅允许常用端口流量”的开关字面描述实际上有混淆——这三个就是最常用的端口

**Comment by Mipa233** [comment]
最新版这个[仅代理命中规则流量]选项在 覆写设置→规则设置 下

**Comment by GOUKI9999** [comment]
收到，是我没找到，这次改版比较多，我以为隐藏或者取消了，不好意思
