### ISSUE TITLE
[Bug] 同样的规则，在TUN模式下生效，在兼容就不生效，但是TUN模式下无法打游戏（Rust）

### ISSUE THREAD

**Issue by Wyatt323** [vernesong/OpenClash#3061]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.97-beta

### Bug on Environment

Lean

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

在添加ChatGPT分流规则后
分流规则如下：
- DOMAIN-SUFFIX,openai.com,🤖 ChatGPT
 - DOMAIN-SUFFIX,chat.openai.com,🤖 ChatGPT
 - DOMAIN-SUFFIX,auth0.openai.com,🤖 ChatGPT
 - DOMAIN-SUFFIX,challenges.cloudflare.com,🤖 ChatGPT
 - DOMAIN-SUFFIX,vimeocdn.com,🤖 ChatGPT
 - DOMAIN-SUFFIX,hcaptcha.com,🤖 ChatGPT
 - DOMAIN-SUFFIX,akamaized.net,🤖 ChatGPT
 - DOMAIN-SUFFIX,vimeo.com,🤖 ChatGPT
 - DOMAIN-SUFFIX,f7tk.com,🤖 ChatGPT
 - DOMAIN-SUFFIX,doubleclick.net,🤖 ChatGPT
开启TUN模式可以正常分流，但是Rust游戏中无法搜索到服务器。
使用兼容模式或者fake-ip时添加的这条分流无法使用，游戏正常

### Describe the Bug

如上

### OpenClash Log

不知道咋搞

### Expected Behavior

希望可以在兼容模式进行分流的实现，还有可以正常游戏

**Comment by Wyatt323** [comment]
不确定是不是bug，想请教一下各位大佬

**Comment by vernesong** [comment]
分流无法使用是什么意思，你去控制面板看看这个域名走什么规则了

**Comment by Wyatt323** [comment]
我创了一个策略组，也是叫🤖 ChatGPT，方便我自己选择支持Chatgpt的节点，如下图，但是这个只在使用tun模式的情况下生效，在兼容模式下，这些域名还是用的我手动选择这个策略组的节点
![image](https://user-images.githubusercontent.com/71224625/222907931-11e95b5e-5c17-4362-b776-b42ca53f0626.png)
![image](https://user-images.githubusercontent.com/71224625/222907944-77c1bfd2-9848-4a35-8328-09a5b6774553.png)

**Comment by vernesong** [comment]
去连接里面看

**Comment by Wyatt323** [comment]
连接里面都是ip啊，看不到域名，

**Comment by Wyatt323** [comment]
![image](https://user-images.githubusercontent.com/71224625/222917767-816d8fd6-ba7f-4ae2-8136-bb47f66854e6.png)
在这个域名列表里添加我的上面的那些域名吗

**Comment by Wyatt323** [comment]
解决了，谢谢大佬

**Comment by lu161513** [comment]
> 解决了，谢谢大佬

请问如何解决的，一样的问题

**Comment by Wyatt323** [comment]
详细见[#5](https://github.com/Wyatt323/openclash-rules/issues/5)
![image](https://user-images.githubusercontent.com/71224625/227169237-e778f96b-6c87-42fe-b3da-2113eb7e2b0a.png)

**Comment by tangli159** [comment]
按着楼上的说法操作还是不生效，尝试[这个](https://github.com/wgetnz/chatgpt-openclash#注意事项)，解决了。是http3的问题。给其他小伙伴提供思路
