### ISSUE TITLE
[Bug] 未找到覆写页面以及功能开启入口？

### ISSUE THREAD

**Issue by koomi** [vernesong/OpenClash#3062]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.97-beta

### Bug on Environment

Lean, Other

### Bug on Platform

Linux-arm64

### To Reproduce

未找到覆写页面以及功能开启入口？

### Describe the Bug

未找到覆写页面以及功能开启入口？

### OpenClash Log

未找到覆写页面以及功能开启入口？

### Expected Behavior

未找到覆写页面以及功能开启入口？

**Comment by vernesong** [comment]
重启
