### ISSUE TITLE
[Bug] redir-host 模式下设置的某mac地址不代理，即使删除该条规则或者切换到fake-ip模式下后此设备依旧无法走代理

### ISSUE THREAD

**Issue by HoldOnBro** [vernesong/OpenClash#3066]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.87 - v0.45.97 均存在

### Bug on Environment

Lean

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

RT

### Describe the Bug

访问控制内的规则即使删除后也依旧在生效

### OpenClash Log

没有log，只是简单操作

### Expected Behavior

我的设备是SteamDeck，目前绕过手段是使用macchanger工具更改设备mac地址，预期修复结果应当为使访问控制内的规则在删除后能正常失效。

**Comment by vernesong** [comment]
```
ipset list lan_ac_black_macs
```
检查配置删除前后是否有内容

**Comment by HoldOnBro** [comment]
> ```
> ipset list lan_ac_black_macs
> ```
> 
> 检查配置删除前后是否有内容

删除访问规则后后在fake-ip模式下执行这条命令返回以下内容：
```
ipset v7.17: The set with the given name does not exist
```

**Comment by vernesong** [comment]
```
ipset list lan_ac_black_ips
```
那你控制面板里面看不到流量？

**Comment by HoldOnBro** [comment]
> ```
> ipset list lan_ac_black_ips
> ```
> 
> 那你控制面板里面看不到流量？

看不到，最新情况是我在 DHCP/DNS 界面把 Deck 的指定 IP 更换之后发现可以正常走代理了。

我想起来在设置mac地址不走代理之前，我是设置的针对Deck IP（192.168.123.14）的不走代理。

后来把针对ip的规则删除了，添加了针对 mac 地址的代理。

目前 ip 为 192.168.123.15 可以正常使用，再次改为 192.168.123.14 并重连 deck wifi 刷新DHCP，又出现了无法走代理的情况。

这样看来应该是原本设置的针对 ip 的不走代理一直在生效。

且更新固件版本和 OpenClash 版本后依然存在这种情况。

**Comment by HoldOnBro** [comment]
> ```
> ipset list lan_ac_black_ips
> ```
> 
> 那你控制面板里面看不到流量？

另外这条命令的返回结果和上面mac的一样

```
ipset v7.17: The set with the given name does not exist
```

**Comment by vernesong** [comment]
发调试日志

**Comment by HoldOnBro** [comment]
> 发调试日志

[https://pastebin.ubuntu.com/p/TptTyNKjdM/](https://pastebin.ubuntu.com/p/TptTyNKjdM/)

**Comment by vernesong** [comment]
![image](https://user-images.githubusercontent.com/42875168/223109882-3e2ba87c-106c-469a-9dce-2f5e16027433.png)

**Comment by HoldOnBro** [comment]
> ![image](https://user-images.githubusercontent.com/42875168/223109882-3e2ba87c-106c-469a-9dce-2f5e16027433.png)

哈哈，原来是它，但是我应该没有手动添加过

感谢V大~
