### ISSUE TITLE
[Bug] 版本无法更新，显示404和未知

### ISSUE THREAD

**Issue by hirintou** [vernesong/OpenClash#3069]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.78-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

![1678029006777](https://user-images.githubusercontent.com/75249799/222968974-970e7966-7390-46b7-a807-ac773913228f.jpg)

如图所示，dev内核显示404，其他两个内核未知。

### Describe the Bug

dev内核显示404，其他两个内核未知，点击更新会失败，无法更新内核和版本。

### OpenClash Log

无

### Expected Behavior

恢复正常在线更新版本的功能

**Comment by SharerMax** [comment]
先更新客户端后再尝试更新其它

**Comment by DuaiDuai0815** [comment]
我也是这个问题 显示“未知” 无法更新

**Comment by hirintou** [comment]
![1678161153062](https://user-images.githubusercontent.com/75249799/223316488-c4db09ca-40d8-4f01-a59b-613dd6ea5a6a.jpg)
今天推送45.100版本后这样显示，可以直接升级吗？
