### ISSUE TITLE
cpu占用20-70，连接数极速上升

### ISSUE THREAD

**Issue by In233** [vernesong/OpenClash#307]
正常cpu占用是在0-10 连接数是1000内，开了后连接数到3w多，软路由 x64 j1900.不知道哪里出了问题，测试了其他软件是正常的，希望大佬看看，软件跟内核都是最新的

**Comment by vernesong** [comment]
进控制面板看下日志，这种情况一般是有回环

**Comment by In233** [comment]
大佬，我解决问题了。
参考了之前的，把lan段全部改成direct，就正常了，
之前的是（ IP-CIDR,127.0.0.0/8,Domestic,no-resolve）
  - IP-CIDR,0.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,10.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,127.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,169.254.0.0/16,DIRECT,no-resolve
  - IP-CIDR,172.16.0.0/12,DIRECT,no-resolve
  - IP-CIDR,192.0.2.0/24,DIRECT,no-resolve
  - IP-CIDR,192.168.0.0/16,DIRECT,no-resolve
  - IP-CIDR,198.18.0.0/15,DIRECT,no-resolve
  - IP-CIDR,198.51.100.0/24,DIRECT,no-resolve
  - IP-CIDR,203.0.113.0/24,DIRECT,no-resolve
  - IP-CIDR,224.0.0.0/4,DIRECT,no-resolve
  - IP-CIDR,240.0.0.0/4,DIRECT,no-resolve
