### ISSUE TITLE
Error when compiling the new version of OpenClash 

### ISSUE THREAD

**Issue by Burhan7610** [vernesong/OpenClash#3075]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.97

### Bug on Environment

Official OpenWrt

### Bug on Platform

Other

### To Reproduce

.

### Describe the Bug

i found error when compiling the new version of OpenClash on the github actions.

help me, please!

### OpenClash Log

.

### Expected Behavior

.

### Screenshots

![223029033-da5352ee-ecf2-4e3a-99ec-97ac872bca6f](https://user-images.githubusercontent.com/125169413/223064915-43b27c27-9dbd-432e-96de-bc2e7c0ae13c.jpeg)
![223029032-897c29a8-dec9-4a3a-91a8-f7cd8512c9ed](https://user-images.githubusercontent.com/125169413/223064966-e69eed2f-9380-4b85-bfdb-9fb0865f8d74.jpeg)

**Comment by vernesong** [comment]
Need dev and package branch

**Comment by Burhan7610** [comment]
so, how to fix it brother?

**Comment by Burhan7610** [comment]
> Need dev and package branch

so, how to fix it brother?

**Comment by vernesong** [comment]
re fork

**Comment by Burhan7610** [comment]
Done. worked. but, why i can't compile ipk? the github actions always skipping the compile.
