### ISSUE TITLE
[Bug] 更新后延迟测速用不了了

### ISSUE THREAD

**Issue by lxsmenghai** [vernesong/OpenClash#3077]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.97

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

![image](https://user-images.githubusercontent.com/76509825/223091998-663c086b-675c-44f8-8d3e-38bcf13d6bcb.png)

### Describe the Bug

更新后延迟测速不显示数值，是我设置的问题还是其他问题？

### OpenClash Log

![image](https://user-images.githubusercontent.com/76509825/223092244-dcf3fbfd-12dd-4077-914e-867c8fc44b92.png)

### Expected Behavior

更新后延迟测速不显示数值，是我设置的问题还是其他问题？

**Comment by vernesong** [comment]
网络通不通，通就看其他软件能不能用

**Comment by lxsmenghai** [comment]
> 网络通不通，通就看其他软件能不能用

网络也是通的，访问外网也没问题就是测不出延迟。passwall，helloworld都可以测出延迟，

**Comment by vernesong** [comment]
换测速地址

**Comment by Speechless22** [comment]
换内核可以暂时规避这个问题https://github.com/vernesong/OpenClash/issues/3065

**Comment by dqh668** [comment]
v1.13.0-6-g71f8f06 <可更新>更新后，确实出现无法显示ss的延迟测速

**Comment by lxsmenghai** [comment]
使用meta内核，就能解决这个问题，坐等下次更新吧
