### ISSUE TITLE
无论我怎么配置，都是可以访问youtue，不能访问google.com，试了好多次了[Bug] 

### ISSUE THREAD

**Issue by Guojunkay** [vernesong/OpenClash#3078]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

0.45.97-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-arm64

### To Reproduce

youtube的视频无阻，就是一点都不能访问谷歌搜索，一直显示访问被拒绝，但是youtue界面进入的谷歌账号设置是可以访问的
【https://myaccount.google.com/】这个可以访问，就是google.com一直访问不了，全局也不行，节点是没有问题的，测试过了。

bug报告写到一半，发现是我没打开第二个dns，我是有ipv6的，请问我是什么原因，为什么要打开那个第二个dns选项

### Describe the Bug

无法访问谷歌搜索，但能访问youtube

bug报告写到一半，发现是我没打开第二个dns，我是有ipv6的，请问我是什么原因，为什么要打开那个第二个dns选项

### OpenClash Log

bug报告写到一半，发现是我没打开第二个dns，我是有ipv6的，请问我是什么原因，为什么要打开那个第二个dns选项

### Expected Behavior

能访问google搜索就欢天喜地了！！！！

### Screenshots

![批注 2023-03-06 224833](https://user-images.githubusercontent.com/104040166/223144293-3177ccf9-b5bf-4c30-9855-9a629b415709.jpg)
![image](https://user-images.githubusercontent.com/104040166/223148536-916588dc-71a6-4689-96c9-b393c05b91d6.png)

**Comment by Guojunkay** [comment]
现在已经可以了，秘诀就是把那个启用第二 DNS 服务器打开，这应该也属于bug，毕竟我觉得这个和ipv6毫无关联

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年3月6日 23:39
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [vernesong/OpenClash] 无论我怎么配置，都是可以访问youtue，不能访问google.com，试了好多次了[Bug] (Issue #3078)


关ipv6

―

**Comment by slyang40** [comment]
第二dns服务器是指smartdns的？

**Comment by vernesong** [comment]
关一下qos

**Comment by james-curtis** [comment]
> 关一下qos

```shell
root@wrtVPN:~# /etc/init.d/qos status
inactive
root@wrtVPN:~# curl google.com -L
curl: (52) Empty reply from server
root@wrtVPN:~# curl -L youtu.be
<!DOCTYPE html><html style="font-size: 10px;fo
```

**Comment by vernesong** [comment]
切到fakeip，然后找一下DNS被谁提前解析了

**Comment by RagtagGeoduck** [comment]
我也遇到了这个问题, 能看YouTube, 但是Google一搜就报错dns有误;
这可能是我误打误撞解决的办法 : 
1. 我更改使用了passwall, 然后调整了xray分流设置, 保存并应用
2. 关闭passwall, 切换回openClash, 此时一切都能够正常访问了.

这个问题经常发生在频繁切换订阅后
