### ISSUE TITLE
[Bug] 无法去掉本地ipv4绕过地址

### ISSUE THREAD

**Issue by Rashhz** [vernesong/OpenClash#3079]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

V0.54.97-beta

### Bug on Environment

Other

### Bug on Platform

Linux-arm64

### To Reproduce

设置““本地 IPv4 绕过地址”

### Describe the Bug

在插件设置中，无法去掉“本地 IPv4 绕过地址”中已有的private ip。表现为去掉之后保存，框里又重新出现private ip

### OpenClash Log

1

### Expected Behavior

不知道是bug还是特性，我希望包括局域网的流量也能通过clash核心

**Comment by vernesong** [comment]
这个排除目的地流量，跟你内网流量进内核没关系

**Comment by Rashhz** [comment]
> 这个排除目的地流量，跟你内网流量进内核没关系

我在clashVerge和圈x上试过了都能进内网，但是openclash上不行。。我也不知道是不是这个设置的原因。。

**Comment by vernesong** [comment]
能连上路由器吗

**Comment by Rashhz** [comment]
> 能连上路由器吗

可以连上开启openclash的路由器，但是连不上学校的路由器。。
我加了一条规则
ip-cidr,192.168.100.0/24,school
也没法连上学校的路由器。。

**Comment by vernesong** [comment]
那应该是你路由自身访问不了内网

**Comment by fangfang333** [comment]
我也遇到一样的问题，我的目的就是利用openclash异地组网。
并且我已经在clash_for_windows 和 clash_for_Android，clash_for_magisk 以及clashN上面实现，不管是clash核心还是clash_meta核心都已经实现，所以我认为这是openclash的问题。

尝试方法①：/etc/openclash/custom/openclash_custom_fallback_filter.yaml 文件中将搜索到的 - 10.0.0.0/8 全部替换成- 10.0.0.0/32，无效。(半年前记得不是这个路径的文件，也试了好久，现在改的是这个文件)

尝试方法②：通过iptable添加规则，将内网流量导入clash，但是我不太懂iptable规则，都以失败告终，还不少次搞得全家断网，得重新给路由器装系统。

希望有一个简单的办法让内网某些IP的流量不绕过核心，从而走代理出去，像clash_for_magisk那样只要修改/data/clash/clash.config文件中的reserved_ip即可。

![QQ截图20230420004723](https://user-images.githubusercontent.com/78396305/233147182-d92d8b33-516c-45d9-8f20-c8da977c3ea4.png)
![QQ截图20230420005907](https://user-images.githubusercontent.com/78396305/233147287-19dbea3a-8248-468d-93ca-dd9425ba584e.png)

**Comment by fangfang333** [comment]
主要的问题是流量根本没有经过核心，而不是  经过核心但是走了直连，我的策略组配置是没有问题的，不然也无法在clash_meta_for_Android上组网。
有朋友可能会说异地组网为什么不用其他方式，可是我已经有了clash，为啥还要再多装一个软件？
并且其他组网方式都是再生成一个专有IP，我的笔记本电脑挂载了NAS的文件夹，换个地方，得重新挂载一遍？

**Comment by vernesong** [comment]
照理来说是不需要改的，因为流量进来是经过clash转发的，出去也应该是经过clash出去，除非你绕过了大陆IP或者绑定了接口

**Comment by vernesong** [comment]
或者是进来的流量没经过clash，出去的时候经过了，验证就是在插件黑白名单那里绕过一下80和443，这种情况可以在路由器防火墙流量规则那里添加一个规则，然后插件会自动处理

**Comment by fangfang333** [comment]
>

> 或者是进来的流量没经过clash，出去的时候经过了，验证就是在插件黑白名单那里绕过一下80和443，这种情况可以在路由器防火墙流量规则那里添加一个规则，然后插件会自动处理

进站出站都没经过clash，"绕过局域网"和"绕过大陆"这是两个类似的机制，并且我一直都是关掉绕过大陆的，在控制面板里根本看不到这条链接，我用了很多clash的其他平台客户端反复尝试，才确定流量是没有进clash核心的。
这个问题困扰我将近半年了，我寻找过很多办法，大家都说添加防火墙规则。
就是道理我都懂，但是实际操作起来，不管是在web界面添加，还是用命令行iptable命令添加，都没成功(全家断网无数次)，可是没人给我提供具体的命令，对于一个并不熟悉iptable的人来说，这个门槛和试错成本实在有些高了，不得已才来到这里寻求帮助

**Comment by fangfang333** [comment]
用的是esir的高大全2022固件，我尝试过以下两条命令及其修改过的很多个版本：
iptables -t nat -A PREROUTING -i eth1 -p udp  -j DNAT --to 10.10.10.4
iptables -t nat -A PREROUTING -i eth1 -p tcp  -j DNAT --to 10.10.10.4

我只是有些奇怪，在配置文件里有"本地绕过地址"部分写着以下内容
0.0.0.0/8
10.0.0.0/8
100.64.0.0/10
127.0.0.0/8
169.254.0.0/16
172.16.0.0/12
192.168.0.0/16
224.0.0.0/4
240.0.0.0/4

我明明已经将10.0.0.0/8这一行修改掉了，流量还是绕过了clash核心，所以很可能是路由器本身的路由表里的规则，并不是clash或者openclash添加的规则。
如果问的直接一点就是：如何插入一条"劫持流量进clash核心"的"iptable规则"并放在第一优先级？openclash可否帮我完成这件事并设置一个开关让用户可以非常简单的使用它。QAQ

**Comment by fangfang333** [comment]
![image](https://user-images.githubusercontent.com/78396305/234027811-640851bc-40ca-4606-9685-f8267ed5e14d.png)
![QQ图片20230424222933](https://user-images.githubusercontent.com/78396305/234028284-3ab721ec-7c20-4ab0-9c45-02a8020466cd.png)

**Comment by vernesong** [comment]
你是家里开的oc插件去连学校的是吧，发下调试日志

**Comment by fangfang333** [comment]
![3](https://user-images.githubusercontent.com/78396305/234277568-0b45fab5-801b-410a-bc5c-d0cdd8502739.png)
[3.txt](https://github.com/vernesong/OpenClash/files/11322488/3.txt)

**Comment by vernesong** [comment]
你访问10网段的规则也没放到最前面啊

**Comment by fangfang333** [comment]
> 你访问10网段的规则也没放到最前面啊

  你指的是配置文件里的吗？配置文件不是按照顺序执行的吗，那么只要在前面不包含10网段不就可以了吗，前面都是不相干的规则
你没明白我的意思：
1，而且这个配置文件在其他客户端都很正常，
2，流量都没进clash核心，理论上 根本不归配置文件管，配置文件是分流规则，现在的问题是看不到链接，并不是直连不直连的问题
3，全局模式也没组网成功，fake-ip也没成功。
4，所以我认为重点是：很可能是路由器本身的路由表里的规则，并不是clash或者openclash添加的规则。

**Comment by fangfang333** [comment]
> 

但是openclash显然没有考虑到"路由器"这个特定场景会遇到的特定问题，希望可以帮助解决

**Comment by Rashhz** [comment]
谢谢v佬，一直忘了还有这个issue了。。已经解决了！
