### ISSUE TITLE
[Bug] 自定义规则一段时间后失效

### ISSUE THREAD

**Issue by Cathgao** [vernesong/OpenClash#3080]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.100-beta

### Bug on Environment

Lean

### Bug on Platform

Linux-arm64

### To Reproduce

全局设置→规则设置→设置自定义规则（优先匹配）中设置部分域名DIRECT规则，然后使用一段时间（1~4小时或隔天）

### Describe the Bug

自定义规则中加入`- DOMAIN-KEYWORD,anydesk,DIRECT`，将anydesk加入到直连中，应用后一段时间内anydesk远程桌面都非常流畅。而一段时间之后（几小时或隔天）后，再次使用anydesk远程控制会变得非常卡，而进路由管理页面手动关闭openclash后anydesk会短暂断线，重新连接后变得非常流畅，可知anydesk在一段时间后流量被代理，自定义规则失效。

### OpenClash Log

[log.txt](https://github.com/vernesong/OpenClash/files/10905829/log.txt)

### Expected Behavior

自定义规则（优先匹配）中的规则条目永久有效，不被覆盖、改写、无效化

**Comment by vernesong** [comment]
你要看看不正常的时候规则在不在配置文件里面，在的话需要去控制面板看debug的日志，连接问题都会显示

**Comment by vernesong** [comment]
可能过段时间会直接使用IP访问，你可以尝试开嗅探

**Comment by Cathgao** [comment]
> 可能过段时间会直接使用IP访问，你可以尝试开嗅探

假设失效的时候是因为用了IP访问，而IP刚好在代理网段内，那是因为有DNS缓存还是什么原因？软件本身的请求就是IP？失效的时候我会关注一下链接表跟进一下

**Comment by Cathgao** [comment]
最新的观察显示，yacd面板里显示anydesk这个连接是在DIRECT链路中，但实际上使用就是如上面的情况描述，显示是直连事实是代理。在debug等级的内核日志中没搜索到“anydesk”关键字。
![image](https://user-images.githubusercontent.com/21031564/224188744-3a70b578-87b8-4f74-b0b9-0927bc42ba49.png)

在重启openclash后，anydesk变得流畅，yacd内的链接表没有anydesk条目。会不会是模拟的Redir-Host模式中有某种成都的bug？

控制端可以确定没有任何代理链路，就是办公室的普通电信商网

**Comment by vernesong** [comment]
可用信息不多，你可以试试match,direct，然后插件每天定时重启

**Comment by Accademia** [comment]
> 最新的观察显示，yacd面板里显示anydesk这个连接是在DIRECT链路中，但实际上使用就是如上面的情况描述，显示是直连事实是代理。在debug等级的内核日志中没搜索到“anydesk”关键字。 ![image](https://user-images.githubusercontent.com/21031564/224188744-3a70b578-87b8-4f74-b0b9-0927bc42ba49.png)
> 
> 在重启openclash后，anydesk变得流畅，yacd内的链接表没有anydesk条目。会不会是模拟的Redir-Host模式中有某种程度的bug？
> 
> 控制端可以确定没有任何代理链路，就是办公室的普通电信商网

你这个已经是经过国际中转了，relay开头的就是国际中转服务器的地址，你这个BUG应该报给AnyDesk官方，让他们与Clash兼容。我怀疑是UDP打洞失败导致之类的问题的。总之 没有直连。直连不会出现这个。

**Comment by Accademia** [comment]
你要解决这个问题，只需要配置AnyDesk即可。

在 “全局设置 -> 连接 -> HTTP代理 -> 选择：禁用代理”

记得开启允许直连。
