### ISSUE TITLE
[Bug] 在规则附加界面添加规则时，每次点击保存设置，规则就会自动duplicate一条，删除无效

### ISSUE THREAD

**Issue by HoldOnBro** [vernesong/OpenClash#3086]
### Verify Steps

- [x] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.100-beta

### Bug on Environment

Lean

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

在规则附加界面逐条添加游戏规则，每次点击保存，原已添加的规则就会自动重复出一条，删除再保存依旧重复添加。

### Describe the Bug

如上

### OpenClash Log

无需log

### Expected Behavior

不应当出现此种情况。

### Screenshots

![image](https://user-images.githubusercontent.com/16101088/223886374-0edb272f-64dc-4aee-998c-d9522ab2b03d.png)

**Comment by theLibra12** [comment]
我也遇到了同样的问题，而且在添加“自定义规则集”时，无法弹出添加窗口。
<img width="309" alt="image" src="https://user-images.githubusercontent.com/2962657/223906541-162dbcad-1297-4fcd-ba8f-d0acc666ee17.png">

**Comment by MafiaLee** [comment]
> 这个[commit](https://github.com/vernesong/OpenClash/commit/d7165d3de2ae02eb02a3d06296a461697fc28963)有些许bug，先使用0.45.94之前的版本，或者自行修改

请问怎么降级啊？必须卸掉重装吗
