### ISSUE TITLE
[Bug] 运行状态及配置管理页面错位

### ISSUE THREAD

**Issue by YaoGuanglinEryu** [vernesong/OpenClash#3087]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.100-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

点击进入运行状态页面或配置管理页面

### Describe the Bug

配置文件列表中的项目错位

### OpenClash Log

略

### Expected Behavior

页面无错位

### Screenshots
![屏幕截图 2023-03-10 102243](https://user-images.githubusercontent.com/125945056/224287592-c34f951a-9aa1-432d-9de5-23c7c55e022b.jpg)

**Comment by vernesong** [comment]
这是什么主题

**Comment by YaoGuanglinEryu** [comment]
上面截图用的是material，用bootstrap也有一样的问题
![屏幕截图 2023-03-10 180403](https://user-images.githubusercontent.com/125945056/224287314-b2b44be4-bf49-48c6-a30f-177559d8cbe2.jpg)

**Comment by YaoGuanglinEryu** [comment]
查了一下代码，猜测是sub_info_show.htm中第42行最后的<div>写错了，是否应该是</div>
