### ISSUE TITLE
[Bug] 在Redir-Host模式下开启IPv6 流量代理，内网设备通过ip.sb查询到的ipv6地址为路由器ip，而不是本机ip

### ISSUE THREAD

**Issue by wumode** [vernesong/OpenClash#3088]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [ ] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.100-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-arm64

### To Reproduce

在Redir-Host模式下，关闭IPv6流量代理，内网设备通过ip.sb可以正确查询本机ip

```
con@con-TN15S:~$ curl ipv6.ip.sb
240e:361:2382:f000:211:32ff:fe41:7f19
```

开启IPv6流量代理，内网设备会查询到路由器ip

```
con@con-TN15S:~$ curl ipv6.ip.sb
240e:361:2382:f000::1
```

尝试添加规则 `DOMAIN,ipv6.ip.sb,DIRECT`，内网设备仍会查询到路由器ip

```
con@con-TN15S:~$ curl ipv6.ip.sb
240e:361:2382:f000::1
```

### Describe the Bug

在DDNS或者PT下载时，可能导致服务器无法获取到设备的真实IPv6地址

### OpenClash Log

无

### Expected Behavior

开启IPv6 流量代理后，是否可以通过插件设置，使ip.sb获取到内网设备的IPv6地址

**Comment by davidu2003** [comment]
> 参考 [MetaCubeX/Clash.Meta#430](https://github.com/MetaCubeX/Clash.Meta/issues/430)
> 
> 和 OpenClash 无关，应该算不上 bug，代理软件应该只能这样子，解决办法参考 https://imciel.com/2023/03/06/qbittorent-direct/
> 
> 重点是在插件设置-开发者选项中加入下面内容，注意修改自己的 IP 后缀
> 
> ```
> #!/bin/sh
> . /usr/share/openclash/log.sh
> . /lib/functions.sh
> 
> # This script is called by /etc/init.d/openclash
> # Add your custom firewall rules here, they will be added after the end of the OpenClash iptables rules
> 
> LOG_OUT "Tip: Start Add Custom Firewall Rules..."
> 
> nft 'insert rule inet fw4 openclash_mangle_v6 position 0 ip6 saddr & ::ffff:ffff:ffff:ffff == ::20e1:fbff:fe6d:5fba counter return'
> nft 'insert rule inet fw4 openclash_mangle_v6 position 0 ip6 saddr & ::ffff:ffff:ffff:ffff == ::c2b counter return'
> exit 0
> ```

这样的话相当于这台机器的ipv6流量就不过代理了吧，那和关闭ipv6流量代理有什么区别呢？

**Comment by EkkoG** [comment]
区别就是不影响其他机

**Comment by EkkoG** [comment]
> > 这个issue 的主题是服务器拿到的IP不对，一般是PT下载时遇到的，列的方案可以解决，该方案并不是针对你的问题的解决方案，建议你的问题详细说明并单独讨论
> 
> 无意冒犯哈，只是一直在寻找两全其美的方案……

@davidu2003 没有感觉到冒犯，只是不知道你想要解决的是什么问题

就题主的问题来说，这个解决方案是不完美的，会影响同网卡出口的其他程序

我觉得主要是在网关看来，局域网中设备的流量没有什么特征，只有 IP 和端口能区别，所以常见的方案一个是只代理常用端口，一个是针对某 IP 设置直连

[dae](https://github.com/daeuniverse/dae) 这种基于 bpf 技术的代理软件也许能解决直连流量 IP 是网关 IP 的问题，如果可以，加上设置代理常用端口加上针对某些域名的直连，就能比较完美解决 PT 软件的下载直连和 tracker 上报的问题，但是没有用过，不知道能不能

如果这个方案可行，对于题主的问题，只需要针对 IP 测试域名设置一个直连应该可以，不影响其他程序

**Comment by davidu2003** [comment]
> > > 这个issue 的主题是服务器拿到的IP不对，一般是PT下载时遇到的，列的方案可以解决，该方案并不是针对你的问题的解决方案，建议你的问题详细说明并单独讨论
> > 
> > 
> > 无意冒犯哈，只是一直在寻找两全其美的方案……
> 
> @davidu2003 没有感觉到冒犯，只是不知道你想要解决的是什么问题
> 
> 就题主的问题来说，这个解决方案是不完美的，会影响同网卡出口的其他程序
> 
> 我觉得主要是在网关看来，局域网中设备的流量没有什么特征，只有 IP 和端口能区别，所以常见的方案一个是只代理常用端口，一个是针对某 IP 设置直连
> 
> [dae](https://github.com/daeuniverse/dae) 这种基于 bpf 技术的代理软件也许能解决直连流量 IP 是网关 IP 的问题，如果可以，加上设置代理常用端口加上针对某些域名的直连，就能比较完美解决 PT 软件的下载直连和 tracker 上报的问题，但是没有用过，不知道能不能
> 
> 如果这个方案可行，对于题主的问题，只需要针对 IP 测试域名设置一个直连应该可以，不影响其他程序

我想要解决的问题主要是两点：
一是上网的设备的ipv6可以直连外网，就像题主的问题一样；
二是不影响爬墙代理，让被代理的域名能继续走代理。
看上去一和二是冲突的。

折中的方案 能做到在代理列表的域名走ipv6代理，不在代理列表的域名走ipv6直连也行，目前还没搞出来该怎么配，所以特来学习哈。
