### ISSUE TITLE
服务器&策略组管理中加入**补充**服务器/代理集的功能

### ISSUE THREAD

**Issue by luvletter2333** [vernesong/OpenClash#309]
对于手动添加的服务器，现用的方案好像是强制覆盖掉订阅里面的设置。

能否增加一个选项，使用户可以手动**添加**节点到订阅文件中，且随着订阅更新而添加？

**Comment by vernesong** [comment]
读取配置文件后，启用保留配置。
这样每次更新只会更新节点，手动添加的节点有隐藏参数会自动识别，也会添加进去。

**Comment by luvletter2333** [comment]
个人不是很喜欢这个模式。如果服务提供商对节点有修改就意味着用户得手动替换配置文件。

**Comment by vernesong** [comment]
节点会更新啊，策略组不会
