### ISSUE TITLE
[Bug] process not found

### ISSUE THREAD

**Issue by hadifarnoud** [vernesong/OpenClash#3091]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.101-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-arm64

### To Reproduce

I have no idea how to reproduce this. but I did delete core files as well still have the issue

### Describe the Bug

I get a lot of `[Process] find process *****: process not found` errors. I cannot open Youtube on my TV for some reason. I thought this might be related to these errors

tried dev versions, it did not fix the issue

### OpenClash Log

23-03-11 00:16:49[ debug ][Process] find process connectivitycheck.gstatic.com: process not found
23-03-11 00:16:49[ debug ][Process] find process connectivitycheck.gstatic.com: process not found
23-03-11 00:16:49[ debug ][Process] find process connectivitycheck.gstatic.com: process not found
23-03-11 00:16:49[ debug ][Process] find process connectivitycheck.gstatic.com: process not found
23-03-11 00:16:49[ debug ][Process] find process connectivitycheck.gstatic.com: process not found
23-03-11 00:16:49[ debug ][Process] find process connectivitycheck.gstatic.com: process not found
23-03-11 00:16:49[ debug ][Process] find process connectivitycheck.gstatic.com: process not found
23-03-11 00:16:49[ debug ][Process] find process connectivitycheck.gstatic.com: process not found
23-03-11 00:16:49[ debug ][Process] find process connectivitycheck.gstatic.com: process not found
23-03-11 00:16:49[ debug ][Process] find process connectivitycheck.gstatic.com: process not found
23-03-11 00:16:49[ debug ][Process] find process connectivitycheck.gstatic.com: process not found

I get similar errors for other things other than connectivitycheck.gstatic.com too

### Expected Behavior

expect it to proxy my TV just fine. everything works on my laptop.

**Comment by vernesong** [comment]
Ignore this error, please provide debug logs for network problems

**Comment by hadifarnoud** [comment]
I managed to fix youtube issue on my TV.

here is what I changed:
change TUN to system
changed DNS redirect to Firewall redirect (using openclash)
changed Enable Process Rule to OFF

I have no idea what fixed the issue. I found nothing unusual in logs.

**Comment by danielcdai** [comment]
> I managed to fix youtube issue on my TV.
> 
> here is what I changed: change TUN to system changed DNS redirect to Firewall redirect (using openclash) changed Enable Process Rule to OFF
> 
> I have no idea what fixed the issue. I found nothing unusual in logs.

Your first rule really did the magic. Thanks alot on the comment.
