### ISSUE TITLE
[Bug] 兼容模式无法正常游戏，tun模式/混合模式无法启动（新提带全日志）

### ISSUE THREAD

**Issue by Blackrailgun** [vernesong/OpenClash#3098]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.100-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-arm64

### To Reproduce

软路由EasePi ARS2，旁路由模式，固件21.02.3 r16854、21.02.3 r16846、21.02.3 r16835均尝试

open clash运行模式选择Redir-Host（兼容）模式后，
>可以正常开启王者荣耀，可以领取任务奖励和邮件，可以正常进入房间点击启动，在匹配后的确认界面100%掉线无限重连。
>蛋仔派对直接无法进入服务器。
>其它游戏未尝试

运行模式选择Redir-Host（TUN）模式或者（TUN-混合）模式，则提示TUN接口启动失败

### Describe the Bug

Redir-Host（兼容）模式无法正常进行游戏
Redir-Host（TUN）模式或者（TUN-混合）模式，无法启动，提示TUN接口启动失败

### OpenClash Log

[调试日志](https://github.com/vernesong/OpenClash/files/10960173/default.txt)
[内核日志+插件日志](https://github.com/vernesong/OpenClash/files/10960176/OpenClash-2023-3-14-1-48-51.log)

### Expected Behavior

可以正常启动tun模式/兼容模式可以正常进行游戏

**Comment by vernesong** [comment]
/etc/openclash/history/ 清空

**Comment by Blackrailgun** [comment]
> /etc/openclash/history/ 清空

清空了，依旧失败。

**Comment by Blackrailgun** [comment]
> /etc/openclash/history/ 清空

**Comment by Blackrailgun** [comment]
> /etc/openclash/history/ 清空

清空过了 没解决 问题依旧

**Comment by Blackrailgun** [comment]
不小心点错了，点成关闭了，问题没解决。
然后更新了今天最新的客户端及内核版本后，主程序、代理模式、IP、控制面板等都是收集数据...。版本更新里，除了客户端版本，其他的内核都提示老版本为最新版。

**Comment by vernesong** [comment]
libcap有问题吧，我用master都没问题

**Comment by Blackrailgun** [comment]
首页显示和版本更新都正常了，求大佬帮忙看看tun模式如何解决～

**Comment by vernesong** [comment]
https://firmware-selector.immortalwrt.org/

**Comment by WhitCrow** [comment]
我也是同样的问题
