### ISSUE TITLE
[Bug] 最近几版meta内核都不正常....

### ISSUE THREAD

**Issue by kitkw** [vernesong/OpenClash#3099]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.100-beta

### Bug on Environment

Lean

### Bug on Platform

Linux-arm64

### To Reproduce

切换到meta内核

### Describe the Bug

官方内核一切正常。切换到meta内核外网就出问题（内网正常），但并无任何报错。最后在dashboard发现是规则完全不受控，就算代理模式切换成全局还是有很大部分没有跟从.........
正常的规则代理模式下，我常用的“ 油管视频”规则分组也是完全失效...

### OpenClash Log

日志无报错

### Expected Behavior

之前一直用meta最近几版开始出问题才没用，还以为很快就解决呢！！

**Comment by vernesong** [comment]
/etc/openclash/history/ 清空

**Comment by kitkw** [comment]
> /etc/openclash/history/ 清空

不行！！
清空后在默认的  规则模式  下好像恢复了能正常分流
但切换  全局模式  还是不行，而且再切换回  规则模式  又回到完全不受控状态............

**Comment by vernesong** [comment]
那你换固件吧，估计是libcap的问题

**Comment by moreoronce** [comment]
应该是固件问题。
我这里X86的几个版本meta都没有问题。
