### ISSUE TITLE
偶尔有部分网址不能正常连接，切换代理模式后又正常

### ISSUE THREAD

**Issue by ziiilok** [vernesong/OpenClash#31]
目前使用的是最新版本、内核、使用Fake-IP模式下，偶尔会出现某部分网站不能正常连接，比如可以正常连接YouTube、Google，但是Facebook却不能正常访问，然后把代理模式切回全局再改回规则模式下才恢复正常，初步排查规则节点dns设置正常（在cfw是可以正常连接上的，而之前cfw旧版也有类似情况出现过）

**Comment by ziiilok** [comment]
![SharedScreenshot](https://user-images.githubusercontent.com/31038809/65461107-e2e22980-de85-11e9-9609-ea65e3b0b50a.jpg)

**Comment by ziiilok** [comment]
重启openclash并没有解决问题，把代理模式改为全局再切换回规则后恢复正常。

**Comment by vernesong** [comment]
访问不了的时候进控制面板看下内核日志，看下内核是如何处理这些请求的。

**Comment by ziiilok** [comment]
time="2019-09-24T15:55:22Z" level=warning msg="dial 🚀 Domestic error: dial tcp6: address 42.62.94.2: no suitable address found"
time="2019-09-24T15:57:28Z" level=warning msg="dial 🚀 Domestic error: dial tcp6: address 118.26.253.26: no suitable address found"
time="2019-09-24T15:57:29Z" level=warning msg="dial 🚀 Domestic error: dial tcp6: address 42.62.94.2: no suitable address found"
目前有3条错误

**Comment by vernesong** [comment]
fake-ip？

**Comment by ziiilok** [comment]
> fake-ip？

是的

**Comment by tianhuxu** [comment]
我也有遇到这个问题，通常是运行时间超过2天就出现一些网站无法访问，重启之后恢复正常。

**Comment by zxlhhyccc** [comment]
> 目前使用的是最新版本、内核、使用Fake-IP模式下，偶尔会出现某部分网站不能正常连接，比如可以正常连接YouTube、Google，但是Facebook却不能正常访问，然后把代理模式切回全局再改回规则模式下才恢复正常，初步排查规则节点dns设置正常（在cfw是可以正常连接上的，而之前cfw旧版也有类似情况出现过）

我也是一样，我以为就我一个人是这个样子，请问你切换回规则模式是指什么规则？

**Comment by ziiilok** [comment]
> > 目前使用的是最新版本、内核、使用Fake-IP模式下，偶尔会出现某部分网站不能正常连接，比如可以正常连接YouTube、Google，但是Facebook却不能正常访问，然后把代理模式切回全局再改回规则模式下才恢复正常，初步排查规则节点dns设置正常（在cfw是可以正常连接上的，而之前cfw旧版也有类似情况出现过）
> 
> 我也是一样，我以为就我一个人是这个样子，请问你切换回规则模式是指什么规则？

mode: Rule Global Direct 之间切换

**Comment by twtjy2008** [comment]
Clash dev commit c384693好像修复了error: dial tcp6 的问题， @vernesong 可以更新一下吗？

**Comment by twtjy2008** [comment]
> Clash dev commit c384693好像修复了error: dial tcp6 的问题， @vernesong 可以更新一下吗？

感谢更新！虽然还是看到有
time="2019-09-28T21:12:16Z" level=warning msg="dial DIRECT error: dial tcp4 198.18.0.53:443: i/o timeout"
time="2019-09-28T21:12:41Z" level=warning msg="dial DIRECT error: dial tcp4 198.18.0.56:443: socket: too many open files"
这样的warning，但是好像不影响使用

**Comment by vernesong** [comment]
这种日志的出现是不正常的，你的某些应用会缓存过期的fakeip，很容易导致连接失败，建议你换成redir模式

**Comment by vernesong** [comment]
请确保没开起开其他dns加速插件

**Comment by twtjy2008** [comment]
> 这种日志的出现是不正常的，你的某些应用会缓存过期的fakeip，很容易导致连接失败，建议你换成redir模式

按照你的建议，换成了redir模式。不过依旧出现
time="2019-09-29T17:54:52Z" level=warning msg="dial DIRECT error: dial tcp4 198.18.1.42:443: i/o timeout"
time="2019-09-29T17:56:08Z" level=warning msg="dial DIRECT error: dial tcp4 198.18.1.42:443: socket: too many open files"
这样的warning，但同样没有看出来有什么使用上影响。没有使用其他dns加速插件

**Comment by vernesong** [comment]
ipv6呢？不建议开

**Comment by twtjy2008** [comment]
> ipv6和ipv6的dhcp呢？不建议开

没开clash的ipv6，路由器的ipv6 dhcp也关闭了，路由器wan6 接口也已经关闭了

**Comment by vernesong** [comment]
> > ipv6和ipv6的dhcp呢？不建议开
> 
> 没开clash的ipv6，路由器的ipv6 dhcp也关闭了，路由器wan6 接口也已经关闭了

再观察一下吧，日志一般不会出现198.18开头的请求

**Comment by twtjy2008** [comment]
我看不出来哪里设置有问题，可以帮忙看一看吗？下面是相关设置的截图
![01](https://user-images.githubusercontent.com/1089991/65896931-06fca980-e363-11e9-94d6-6af8c4c6bda9.png)
![02](https://user-images.githubusercontent.com/1089991/65896940-09f79a00-e363-11e9-9ef0-a74967b65fea.png)
![09](https://user-images.githubusercontent.com/1089991/65896950-0ebc4e00-e363-11e9-9497-230cef7ebc84.png)
![03](https://user-images.githubusercontent.com/1089991/65896960-14199880-e363-11e9-8375-89076b37de7e.png)
![04](https://user-images.githubusercontent.com/1089991/65896961-14199880-e363-11e9-8acd-737f22ed3026.png)
![07](https://user-images.githubusercontent.com/1089991/65896985-1b40a680-e363-11e9-8f67-3834f0284f80.png)
![05](https://user-images.githubusercontent.com/1089991/65896993-1f6cc400-e363-11e9-8d6c-348572f1b824.png)
![06](https://user-images.githubusercontent.com/1089991/65896994-1f6cc400-e363-11e9-9ac7-4f22fbdae139.png)
![08](https://user-images.githubusercontent.com/1089991/65896997-23004b00-e363-11e9-9be1-2b5736d3942a.png)
![10](https://user-images.githubusercontent.com/1089991/65897028-33b0c100-e363-11e9-8e6e-06201c0e12d7.png)

**Comment by vernesong** [comment]
> 我看不出来哪里设置有问题，@vernesong 可以帮忙看一看吗？下面是相关设置的截图
> ![01](https://user-images.githubusercontent.com/1089991/65896931-06fca980-e363-11e9-94d6-6af8c4c6bda9.png)
> ![02](https://user-images.githubusercontent.com/1089991/65896940-09f79a00-e363-11e9-9ef0-a74967b65fea.png)
> ![09](https://user-images.githubusercontent.com/1089991/65896950-0ebc4e00-e363-11e9-9497-230cef7ebc84.png)
> ![03](https://user-images.githubusercontent.com/1089991/65896960-14199880-e363-11e9-8375-89076b37de7e.png)
> ![04](https://user-images.githubusercontent.com/1089991/65896961-14199880-e363-11e9-8acd-737f22ed3026.png)
> ![07](https://user-images.githubusercontent.com/1089991/65896985-1b40a680-e363-11e9-8f67-3834f0284f80.png)
> ![05](https://user-images.githubusercontent.com/1089991/65896993-1f6cc400-e363-11e9-8d6c-348572f1b824.png)
> ![06](https://user-images.githubusercontent.com/1089991/65896994-1f6cc400-e363-11e9-9ac7-4f22fbdae139.png)
> ![08](https://user-images.githubusercontent.com/1089991/65896997-23004b00-e363-11e9-9be1-2b5736d3942a.png)
> ![10](https://user-images.githubusercontent.com/1089991/65897028-33b0c100-e363-11e9-8e6e-06201c0e12d7.png)

ipv4上游接口dns换成114试试，clash的dns也用ip地址的，koolshare我没法测试，这日志说的意思是连接数限制。

**Comment by twtjy2008** [comment]
> ipv4上游接口dns换成114试试，clash的dns也用ip地址的，koolshare我没法测试，这日志说的意思是连接数限制。

我不知道改得对不对，但是把DNS换成114.114.114.114之后，依然有[warning] dial DIRECT error: dial tcp4 198.18.0.57:443: socket: too many open files
不过现在感觉不出来使用上有什么影响，先这样用着吧。多谢啦

**Comment by ganlu510** [comment]
最近也在用openclash，也经常性出现google、youtube连不上的情况，但是过个10来分钟又可以自动连上的情况，这种情况很常见。
但是同样使用55R-plus插件时就很正常。

**Comment by vernesong** [comment]
> 最近也在用openclash，也经常性出现google、youtube连不上的情况，但是过个10来分钟又可以自动连上的情况，这种情况很常见。
> 但是同样使用55R-plus插件时就很正常。

节点不稳定自动切换的话可能也会对某些访问造成影响，你可以把策略改成故障转移fallback排查下。
我这边用最低延迟面对服务器不稳定的情况有时候也会访问不畅。

**Comment by ganlu510** [comment]
我怀疑是dns设置的情况导致的（用的fake-ip模式，出现过google能正常访问，但是youtube却不能访问的情况），但是我用的都是默认设置，对clash还不太熟悉，所以不敢瞎设置。

**Comment by vernesong** [comment]
> 我怀疑是dns设置的情况导致的（用的fake-ip模式，出现过google能正常访问，但是youtube却不能访问的情况），但是我用的都是默认设置，对clash还不太熟悉，所以不敢瞎设置。

先去看wiki排查问题

**Comment by JAYBOY137** [comment]
我跟你一样的问题 满世界找问题的原因 FAKE-IP 也换过策略也换过，都不行 最后改了  114.114.114.114就好了 在改回来也没问题了 搞不懂什么原因 我只是油管打不开。可能被劫持了 其他的日志能看的也都看过

**Comment by godotu** [comment]
同样的问题，将ipv4上游接口dns换成114之后确实解决了，感谢楼上

**Comment by cusuanan** [comment]
同样的问题，甚至windows下的网络标志也是无网络状态。后来在【覆写设置】下【DNS设置】，勾选【自定义上游DNS服务器】，下面的【NameServer】选择114.114.114.114 以及 223.5.5.5等，【default-nameserver】 全勾选。就解决了。希望帮到看到的。
