### ISSUE TITLE
youtube无法访问

### ISSUE THREAD

**Issue by Zayia** [vernesong/OpenClash#310]
旁路由openclash，每隔一段时间访问youtube连不上，等一会才能连上，这是啥情况

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by vernesong** [comment]
节点不稳定，建议手动选择一个

**Comment by Zayia** [comment]
并不是节点问题，用其他梯子没出现过这个问题

**Comment by vernesong** [comment]
提供连接日志
