### ISSUE TITLE
[Bug] 为什么clone下来的项目体积高达14GB？

### ISSUE THREAD

**Issue by threerog** [vernesong/OpenClash#3104]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45

### Bug on Environment

Official OpenWrt, Lean

### Bug on Platform

All

### To Reproduce

为什么clone下来的项目体积高达14GB？
人性的扭曲还是道德的沦丧

### Describe the Bug

为什么clone下来的项目体积高达14GB？
人性的扭曲还是道德的沦丧

### OpenClash Log

为什么clone下来的项目体积高达14GB？
人性的扭曲还是道德的沦丧

### Expected Behavior

为什么clone下来的项目体积高达14GB？
人性的扭曲还是道德的沦丧

**Comment by jjm2473** [comment]
因为二进制文件都放在这个仓库了 😆

**Comment by threerog** [comment]
所有成品文件和源代码应该单独分支存放呀

**Comment by love4taylor** [comment]
```
git clone --depth=1
```

**Comment by jjm2473** [comment]
> 所有成品文件和源代码应该单独分支存放呀

所以不知道作者怎么想的，放在其他仓库或者放release里面都更合适

**Comment by Bunnui** [comment]
git会将历史提交文件一起保存，这样能达到回退某个版本效果，正常git文件不会重复储存，重复文件只储存一份，但该仓库作者每次提交都把二进制文件放入仓库中，每次提交都在git仓库中，而二进制文件每次MD5或者其他文件标识都不一样，时间一久文件就越来越大。

**Comment by love4taylor** [comment]
二月已经开了单独分支，但估计顾及到老版本兼容性主分支一直没动。

**Comment by starua** [comment]
存放确实是个问题，但是建议不要乱用Bug标签......
建议关闭这个issure
@vernesong

**Comment by starua** [comment]
提一嘴，我认为正确的方法其实应该是使用git lfs扩展
