### ISSUE TITLE
[Bug] 【/tmp/clash.tar.gz】下载失败：【curl: (56) Error】

### ISSUE THREAD

**Issue by RhythmNz** [vernesong/OpenClash#3105]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.103-beta

### Bug on Environment

Other

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

点击更新按钮

### Describe the Bug

【/tmp/clash.tar.gz】下载失败：【curl: (56) Error】
更新内核和插件本体均有该提示
在路由器上执行ping和curl都是正常的

### OpenClash Log

2023-03-15 18:11:16 【Dev】版本内核更新成功！
2023-03-15 18:11:16 【Dev】版本内核下载成功，开始更新...
2023-03-15 18:11:11【/tmp/clash.tar.gz】下载失败：【curl: (56) Error】
2023-03-15 18:11:13 【Dev】版本内核更新失败，请检查网络或稍后再试！
2023-03-15 18:11:08【/tmp/clash.tar.gz】下载失败：【curl: (56) Error】
2023-03-15 18:11:11 【Dev】版本内核正在下载，如下载失败请尝试手动下载并上传...
2023-03-15 18:11:08 【Dev】版本内核正在下载，如下载失败请尝试手动下载并上传...
2023-03-15 18:09:56 OpenClash 启动成功，请等待服务器上线！

### Expected Behavior

正常更新

**Comment by ciegyet** [comment]
检查一下网络连接是否正常，使用 curl -I -m 10 -o /dev/null -s -w %{http_code} https://github.com/vernesong/OpenClash ，观察输出状态码是否为200  为200 即正常

**Comment by cncot** [comment]
> 检查一下网络连接是否正常，使用 curl -I -m 10 -o /dev/null -s -w %{http_code} https://github.com/vernesong/OpenClash ，观察输出状态码是否为200 为200 即正常

请问怎么手动下载内核？？？能透露请给一个地址！

**Comment by ciegyet** [comment]
https://github.com/vernesong/OpenClash/wiki/%E5%AE%89%E8%A3%85 Wiki里有 releases 地址 https://github.com/vernesong/OpenClash/releases/tag/Clash

**Comment by cncot** [comment]
> https://github.com/vernesong/OpenClash/wiki/%E5%AE%89%E8%A3%85 Wiki里有 releases 地址 https://github.com/vernesong/OpenClash/releases/tag/Clash

多谢大佬！

**Comment by ciegyet** [comment]
> > https://github.com/vernesong/OpenClash/wiki/%E5%AE%89%E8%A3%85Wiki里有 发布地址 https://github.com/vernesong/OpenClash/releases/tag/Clash
> 
> 多谢大佬！tun 的内核没有啊？

tun meta内核需要安装插件后，到插件设置---版本更新中---下载到本地，作者没发布在github，或者说我没找到。
这里提提供几个amd64 的直链
[dev](https://raw.githubusercontent.com/vernesong/OpenClash/core/master/dev/clash-linux-amd64.tar.gz)
[tun](https://raw.githubusercontent.com/vernesong/OpenClash/core/master/premium/clash-linux-amd64-2023.03.04-5-g4a8cefb.gz
)
[meta](https://raw.githubusercontent.com/vernesong/OpenClash/core/master/meta/clash-linux-amd64.tar.gz)

**Comment by cncot** [comment]
> > > [https://github.com/vernesong/OpenClash/wiki/%E5%AE%89%E8%A3%85Wiki里有](https://github.com/vernesong/OpenClash/wiki/%E5%AE%89%E8%A3%85Wiki%E9%87%8C%E6%9C%89) 发布地址 https://github.com/vernesong/OpenClash/releases/tag/Clash
> > 
> > 
> > 多谢大佬！tun 的内核没有啊？
> 
> tun meta内核需要安装插件后，到插件设置---版本更新中---下载到本地，作者没发布在github，或者说我没找到。 这里提提供几个amd64 的直链 [dev](https://raw.githubusercontent.com/vernesong/OpenClash/core/master/dev/clash-linux-amd64.tar.gz) [tun](https://raw.githubusercontent.com/vernesong/OpenClash/core/master/premium/clash-linux-amd64-2023.03.04-5-g4a8cefb.gz) [meta](https://raw.githubusercontent.com/vernesong/OpenClash/core/master/meta/clash-linux-amd64.tar.gz)

感谢！！！！1

**Comment by RhythmNz** [comment]
> 检查一下网络连接是否正常，使用 curl -I -m 10 -o /dev/null -s -w %{http_code} https://github.com/vernesong/OpenClash ，观察输出状态码是否为200 为200 即正常
是正常的

**Comment by fannwong001** [comment]
他界面应该说明下载地址和上传位置，github的下载域名是被封的，不翻墙能下下来才怪。

**Comment by fannwong001** [comment]
> > 检查一下网络连接是否正常，使用 curl -I -m 10 -o /dev/null -s -w %{http_code} https://github.com/vernesong/OpenClash ，观察输出状态码是否为200 为200 即正常
> > 是正常的

代码地址没有被墙，程序的release安装包地址域名都会跳转到githubusercontent.com，是被墙的。

**Comment by ciegyet** [comment]
> > > 检查一下网络连接是否正常，使用 curl -I -m 10 -o /dev/null -s -w %{http_code} https://github.com/vernesong/OpenClash ，观察输出状态码是否为200 为200 即正常
> > > 是正常的
> 
> 代码地址没有被墙，程序的release安装包地址域名都会跳转到githubusercontent.com，是被墙的。

灵活更改下url即可

**Comment by fannwong001** [comment]
> > > > 检查一下网络连接是否正常，使用 curl -I -m 10 -o /dev/null -s -w %{http_code} https://github.com/vernesong/OpenClash ，观察输出状态码是否为200 为200 即正常
> 
> > > > 是正常的
> 
> > 
> 
> > 代码地址没有被墙，程序的release安装包地址域名都会跳转到githubusercontent.com，是被墙的。
> 
> 
> 
> 灵活更改下url即可

费那劲干什么，也不知道改完url的安不安全，本来就有翻墙的节点 用它先在windows上翻墙再下载下来就行了，下载地址和安装位置在界面上 插件设置--版本更新 里，这一点他在前面确实没说明白，需要自己找。本来可以用第一次配置的订阅信息下载下来的，但是如果一开始配置的东西有问题的话也就不行了。
