### ISSUE TITLE
[Bug] 在“一键生成”中修改配置无法生效，配置文件没有变化。

### ISSUE THREAD

**Issue by clk01** [vernesong/OpenClash#3107]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.103-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

在“一键生成”中修改配置无法生效，配置文件没有变化。

### Describe the Bug

在“一键生成”中修改配置无法生效，配置文件没有变化。

### OpenClash Log

就是不生效啊。

### Expected Behavior

可以修改配置并生效

**Comment by clk01** [comment]
更新后无法对之前的旧配置更改，但是重装openclash新建配置就可以了。

**Comment by godashang** [comment]
我也遇到在配置界面不行，不过去配置文件里写就可以。
