### ISSUE TITLE
ipv6是否还不支持？

### ISSUE THREAD

**Issue by Sauhun** [vernesong/OpenClash#311]
感谢各开发者！非常强大的一款工具。请问目前是否对IPV6支持方面有些问题呢？也可能是个人配置原因？挂上代理后所有IPV6的站点都无法访问了，只能通过IPV4访问。停掉服务正常。

**Comment by vernesong** [comment]
dns设置开启ipv6

**Comment by vernesong** [comment]
fakeip和tun模式用不了
