### ISSUE TITLE
[Bug] 请求清理git仓库历史提交二进制文件

### ISSUE THREAD

**Issue by Bunnui** [vernesong/OpenClash#3112]
## 说明

请求作者清理git仓库历史提交二进制文件，git仓库文件过大。

## 请不要将编译过程生成的文件以及二进制文件提交到git仓库！！！

二进制文件请放在[Releases](https://github.com/vernesong/OpenClash/releases)中

![image](https://user-images.githubusercontent.com/37466008/225641146-05d1b1ea-b0c0-44ba-8c36-5dc5bddcec7c.png)

**Comment by 450717565** [comment]
git clone --depth=1 --single-branch --branch "dev" https://github.com/vernesong/OpenClash.git

即可

**Comment by Bunnui** [comment]
> git clone --depth=1 --single-branch --branch "dev" https://github.com/vernesong/OpenClash.git
> 
> 即可

我知道，只是提出建议，不要把二进制放到仓库了。

**Comment by Bunnui** [comment]
> git clone --depth=1 --single-branch --branch "dev" https://github.com/vernesong/OpenClash.git
> 
> 即可

在编译openwrt看偷跑了很多流量才知道是这个仓库的委托

**Comment by 450717565** [comment]
> > git clone --depth=1 --single-branch --branch "dev" https://github.com/vernesong/OpenClash.git
> > 即可
> 
> 在编译openwrt看偷跑了很多流量才知道是这个仓库的委托

我不是作者。
一开始我也不知道，我也是看了前面有人说克隆下来有14G我才发现的0.0

**Comment by starua** [comment]
正确的，编译的二进制文件不应该包括在仓库里，clash内核们应该放在其他仓库里，现在要改可以使用git lfs保持旧版本的兼容性
