### ISSUE TITLE
[Bug] openclash的本地nds劫持，无法劫持到chat.openai.com

### ISSUE THREAD

**Issue by yhsrzbg** [vernesong/OpenClash#3113]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.103-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-mips64

### To Reproduce

配置文件加入了以下规则 
- DOMAIN-SUFFIX,openai.com,🤖 OpenAi
- DOMAIN-SUFFIX,chat.openai.com,🤖 OpenAi

openai官网（openai.com）能够被劫持并解析，
但打开chat.openai.com这个域名，无法在控制台的connections里筛选到，页面返回的错误信息也显示，流量没有被代理。

### Describe the Bug

chat.openai.com感觉根本没有走内核，这个域名解析出来是104.18.3.161，也符合走clash的条件。很奇怪

### OpenClash Log

日志没有什么有价值的信息

### Expected Behavior

修复后期望chat.openai.com能正常走clash

**Comment by PicaroonX** [comment]
确实有问题，我也配置了
- DOMAIN-SUFFIX,openai.com, ...
同样的yaml配置文件在Windows上用Clash for Windows是正常的，在Openwrt上用OpenClash也不行
其他规则全部正常，目前也只发现了openai.com不行

**Comment by thj8** [comment]
请问解决了吗, 我也遇到同样的问题
