### ISSUE TITLE
[Feature] 黑白名单设置里的设备还会走订阅规则吗

### ISSUE THREAD

**Issue by threerog** [vernesong/OpenClash#3116]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

黑白名单设置里的设备还会走订阅规则吗
比如我设置了某个设备为白名单模式
那他是全局代理还是仍然走订阅规则

### Describe the Solution

黑白名单设置里的设备还会走订阅规则吗
比如我设置了某个设备为白名单模式
那他是全局代理还是仍然走订阅规则

**Comment by yzxj3180** [comment]
根据你设置的模式是rule、direct和global来决定，设置哪个模式白名单设备走哪个模式
