### ISSUE TITLE
openclash在19.07下配置文件管理页面保存和应用导致网页卡死（路由器所有网页无法打开）

### ISSUE THREAD

**Issue by pikachullk** [vernesong/OpenClash#312]
具体位置是:
input class="cbi-button cbi-input-apply" type="submit" name="cbid.table.1.Apply" id="cbid.table.1.Apply" value="应用配置" size="0"
和
input class="cbi-button cbi-input-apply" type="submit" name="cbid.table.1.Commit" id="cbid.table.1.Commit" value="保存配置" size="0"
只要一点击整个网页就会完全卡死～任何页面都进不去～（在导入规则后才会发生）
用了sora大佬的19.07源码和lateast源码测试后结果一样~
后反馈至sora大佬处~
大佬编译测试后结果一样~
sora大佬说:新 LuCI 行为改了...
希望大佬能帮帮忙解决一下

**Comment by pikachullk** [comment]
![photo_2020-04-06_22-41-53](https://user-images.githubusercontent.com/9532218/78584161-5cfa5e80-786a-11ea-89aa-a81496babdbd.jpg)
![photo_2020-04-06_22-42-16](https://user-images.githubusercontent.com/9532218/78584164-5d92f500-786a-11ea-82ad-29703295d646.jpg)

**Comment by vernesong** [comment]
写入这一块提供的api就是主要这样，对大文件和特殊符号支持有限，19.07不知道改了没有

**Comment by pikachullk** [comment]
> 写入这一块提供的api就是主要这样，对大文件和特殊符号支持有限，19.07不知道改了没有

可问题是这东西在18.06没问题啊...到19.07就不行了..怪事啊....
我后来试了试他19.07的latest问题依旧..

**Comment by freeman02** [comment]
我在OpenWrt 18.06.1 r7258-5eb055306f却有同样问题，在配置文件管理上传文件后，点击保存配置就会
出现这个情况。下面状态栏会显示上传（94%），有时是（96%）左右就卡住了。点任何页面都没反应，只能ssh去reboot

**Comment by SakuraWald** [comment]
這個問題在2023年仍然存在. 可以正常拉取默認的訂閱文件, 但是手動修改訂閱文件之後, 提交保存會導致頁面卡住.
無法再次訪問Openwrt的任何頁面, 但是卻可以正常使用Openclash的功能.
