### ISSUE TITLE
[Feature] 能不能给openclash单独增加一个DNS地址避免DNS劫持失败。

### ISSUE THREAD

**Issue by clk01** [vernesong/OpenClash#3122]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

使用旁路由于时将DNS配置成旁路由IP经常遇到openclash无法劫持到dns，在连接中查看直接变成ip无法fq的问题。

### Describe the Solution

单独给openclash设置一个IP不同于其他设备只用来做DNS解析

**Comment by vernesong** [comment]
那有啥用，流量跑到路由器还不是要被劫持

**Comment by clk01** [comment]
> 那有啥用，流量跑到路由器还不是要被劫持

确实，应该是在到路由器之前就被解析了，所以到openclash是IP，如果只是直接走路由器应该openclash也不显示。大佬点醒了我，大意了，我似乎找到问题了，再研究一下。谢谢大佬！
