### ISSUE TITLE
兼容tun模式下xbox和githubusercontent无法连接

### ISSUE THREAD

**Issue by trombonist852** [vernesong/OpenClash#3123]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.103-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

开启Redir-Host tun模式

### Describe the Bug

win10 xbox网络里面性能延迟-1毫秒，数据包丢失100%，xboxlive多人游戏nat 类型开放，服务器连接已阻止，关掉openclash就正常了
githubusercontent无法连接

### OpenClash Log

[logs.txt](https://github.com/vernesong/OpenClash/files/11010741/logs.txt)

### Expected Behavior

希望大佬能指点一二 

### Screenshots

![225194998-824c5ce2-cdc7-4ee8-85f1-7a82d5d1e475](https://user-images.githubusercontent.com/13253090/226170133-223b02df-436b-4907-ad1f-5c453ed067e1.png)
![225196292-d61c7131-8126-4307-a291-b01aa4c21035](https://user-images.githubusercontent.com/13253090/226170156-96dc9ad3-4842-4479-a2e4-a7cdcb8888ad.png)
![fc698ca09aeee33673a31e8e56d4fa3](https://user-images.githubusercontent.com/13253090/226170164-aa0da9ac-021c-46df-b412-5296c017b216.png)
![b94355bd82a55749272025e9aad1616](https://user-images.githubusercontent.com/13253090/226170167-c574b871-1b0f-4c2e-bfa4-c1c0c21cedd5.png)

**Comment by vernesong** [comment]
xbox好像一直是这样，你改成代理试试，dns加几个fallback

**Comment by trombonist852** [comment]
> xbox好像一直是这样，你改成代理试试，dns加几个fallback



> 控制面板看看有没有githubusercontent的连接

好的  感谢大佬回复 我试试看

**Comment by free1x** [comment]
我这样也是遇到这个情况，请问问题如何解决？

**Comment by kiligone** [comment]
两个解决办法：
1. x1ds.xboxlive.com这个域名的连接不能过内核，让这个域名对应的ip绕过内核就好了。
2. 不代理udp连接

**Comment by zhaoxp520** [comment]
我也是githubusercontent不通
返回IP不是127.0.0.1就是0.0.0.0
解析不出IP地址导致无法访问

**Comment by Yaochen2182** [comment]
我搞定了，主路由iKuai，旁路由开代理，fake ip 的 TUN模式 meta核心
fake-ip-filter:
- Xbox.*.*.microsoft.com
- *.*xboxlive.com
- xbox.*.microsoft.com
- xnotify.xboxlive.com
给Xbox服务返回真实地址
然后抓3544端口的IP，放在插件设置-〉流量控制-〉本地绕过地址，ikuai直接映射Xbox IP
内网填主机给的端口一般是3074，外网填3544，彻底解决问题。

**Comment by jelly21fish** [comment]
> 两个解决办法：
> 
> 1. x1ds.xboxlive.com这个域名的连接不能过内核，让这个域名对应的ip绕过内核就好了。
> 2. 不代理udp连接

我把解析到的x1ds的ip填到“不走代理的 WAN IP”，真的解决了！真的找了很久解决方案，感谢大佬~虽然xbox的测试通过也不代表联机不掉线，但至少舒心了很多~
