### ISSUE TITLE
能否支持kcptun配置

### ISSUE THREAD

**Issue by rilyuuj** [vernesong/OpenClash#313]
你好，
使用你的luci clash很好用，但是能否考虑支持下kcptun的配置？，其实只需在interface下面添加一个程序路径接口，ss-libev本身就支持kcp插件的，望能实现下优化
这只是本人一个请愿，非常谢谢

**Comment by vernesong** [comment]
内核还没支持此种配置

**Comment by rilyuuj** [comment]
> 内核还没支持此种配置

好吧，我去内核仓库逛了圈发觉大家都比较偏向v2的mkcp。。没人提kcptun。。

**Comment by rilyuuj** [comment]
目前曲线救国的办法就是单独安装[luci-app-kcptun](https://github.com/kuoruan/luci-app-kcptun)，然后服务器设置里指向本地127.0.0.1:kcptun监听端口,其余设置和普通酸酸乳设置一样。
给需要的人吧~
另外，本人实测下来v2的kcp没有酸酸+kcptun效果好。。当然也可能是主机垃圾的关系。。

**Comment by ZevAlain** [comment]
> 目前曲线救国的办法就是单独安装[luci-app-kcptun](https://github.com/kuoruan/luci-app-kcptun)，然后服务器设置里指向本地127.0.0.1:kcptun监听端口,其余设置和普通酸酸乳设置一样。
> 给需要的人吧~
> 另外，本人实测下来v2的kcp没有酸酸+kcptun效果好。。当然也可能是主机垃圾的关系。。

不好意思，可否稍微具体点，我也有这样的需求。

**Comment by hcym** [comment]
v2的mkcp也没有支持吧，网页确实不错，视频效果一般，还是trojan拉倒

**Comment by rilyuuj** [comment]
> > 目前曲线救国的办法就是单独安装[luci-app-kcptun](https://github.com/kuoruan/luci-app-kcptun)，然后服务器设置里指向本地127.0.0.1:kcptun监听端口,其余设置和普通酸酸乳设置一样。
> > 给需要的人吧~
> > 另外，本人实测下来v2的kcp没有酸酸+kcptun效果好。。当然也可能是主机垃圾的关系。。
> 
> 不好意思，可否稍微具体点，我也有这样的需求。

配置号kcptun监听本地端口，在用作者的openclash设置一个$$服务器，监听那个端口就可以了。

**Comment by rilyuuj** [comment]
> v2的mkcp也没有支持吧，网页确实不错，视频效果一般，还是trojan拉倒

trojan现在支持cdn伪装了吗？之前没法套cdn所以一直没关注。。

**Comment by hcym** [comment]
原版的trojan不行的，ipv6都不行，用cdn就用哪个衍生的go版本吧，我怕烦一直用原版

**Comment by rilyuuj** [comment]
> 原版的trojan不行的，ipv6都不行，用cdn就用哪个衍生的go版本吧，我怕烦一直用原版

好，谢谢。go版能给个作者名字吗? vernnesong整合的应该就是原版trojan

**Comment by wyfang** [comment]
你好，请问我一直用的koolshare的酷软中心里的koolss，我一直用的ss+kcptun，最近想要重装软路由，看了很多教程想要pve+openwrt，求问这个OpenClash里能否满足使用？
