### ISSUE TITLE
[Feature] 为什么还没有添加naiveproxy？界面做的不错

### ISSUE THREAD

**Issue by fannwong001** [vernesong/OpenClash#3132]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

1、界面做的不错，但是为什么还没有添加naiveproxy？为什么还保留着ssr这些早就被识别淘汰的协议？
2、比passwall反应慢一点。看了看iptables规则，虽然是加在了nft里面，这点比passwall先进了，但是把所有的国内ip段加在里面就效率低了，因为nft对这种情况也是逐条匹配的，不如放在用户空间做来的快。
3、尽快支持好ipv6吧，至少在路由测能够用ipv6访问外网没问题，因为某些cdn的ipv6地址延迟比较低，翻墙效果好

后记：
看到配置里有一项：
    实验性：绕过中国大陆 IP
    启用后中国大陆流量将不再经过内核，提升系统性能
但是我设置了之后，再查看nft规则，怎么还在规则里呢，而且这个描述，怎么会不经过内核呢？他应该是想表达不经过内核过滤吧？

### Describe the Solution

这边以前的表述有问题

**Comment by deuteros-gex** [comment]
你是不是把“内核”理解成操作系统的kernel了？对clash来说，内核指的是不带GUI的可执行文件，是openclash的上游。
openclash大致是给clash套一层UI，用脚本控制可执行文件的行为、如有需要再加一些iptables/nftables。

这个项目本来就不负责加这个协议删那个协议的，那属于clash内核的scope，有想法麻烦去上游提啊。

> 2、比passwall反应慢一点。看了看iptables规则，虽然是加在了nft里面，这点比passwall先进了，但是把所有的国内ip段加在里面就效率低了，因为nft对这种情况也是逐条匹配的，不如放在用户空间做来的快。
甚至没看懂你在说什么。。但既然懂iptables/nftables，有啥需求是你自己无法解决的吗。

> 3、尽快支持好ipv6吧，至少在路由测能够用ipv6访问外网没问题，因为某些cdn的ipv6地址延迟比较低，翻墙效果好
作者文档写得有点问题，事实上支持ipv6，你说的需求早就能满足了。

**Comment by LimonChoms** [comment]
大佬本来就用爱发电，你是怎么做到伸手伸得那么理直气壮的？

**Comment by deuteros-gex** [comment]
> 是的，我理解成linux内核了。顺便问一下，不经过clash内核的话，是经过其他哪个程序来处理的呢？

这问法就离谱，既然看得懂iptables，又何必张嘴问呢？

> 第2个我说的是同样的节点用passwall刷油管时网页加载的比较快，用openclash有时候会加载的慢一点。但是passwall的设置bug多。

你要不要再读一遍自己写了什么？日志不给，光说一个唯象的结果，顺带diss别的项目。即便真有问题也没人愿意帮你定位。

> ipv6这个功能我打开了，在插件设置-ipv6设置里，也添加了网卡lan6，获取到了真正的ipv6地址，用的旁路网关，但是抓包看了看，路由跟服务端节点的交互还是用的ipv4，按道理ipv6的延迟低一点，应该优选ipv6的（小火箭上有这个设置），在passwall上就是按ipv6交互的，openclash和passwall用的都是223.5.5.5做dns

这段话东一榔头西一棒，不知道怎么回。

**Comment by fannwong001** [comment]
> > 是的，我理解成linux内核了。顺便问一下，不经过clash内核的话，是经过其他哪个程序来处理的呢？
> 
> 
> 
> 这问法就离谱，既然看得懂iptables，又何必张嘴问呢？
> 
> 你不想回答可以不必打字找存在感！如果你是另一个人的小号的话就请上大号直接diss 不要拉黑别人
> 
> > 第2个我说的是同样的节点用passwall刷油管时网页加载的比较快，用openclash有时候会加载的慢一点。但是passwall的设置bug多。
> 
> 
> 
> 你要不要再读一遍自己写了什么？日志不给，光说一个唯象的结果，顺带diss别的项目。即便真有问题也没人愿意帮你定位。
> 
> 这个本来就是主观感受怎么有日志！请问你们有这方面的日志吗？我说那个项目的问题怎么叫diss别的项目？难道你们之间也搞粉圈吗！
> 
> > ipv6这个功能我打开了，在插件设置-ipv6设置里，也添加了网卡lan6，获取到了真正的ipv6地址，用的旁路网关，但是抓包看了看，路由跟服务端节点的交互还是用的ipv4，按道理ipv6的延迟低一点，应该优选ipv6的（小火箭上有这个设置），在passwall上就是按ipv6交互的，openclash和passwall用的都是223.5.5.5做dns
> 
> 
> 
> 这段话东一榔头西一棒，不知道怎么回。

不知道你就别逼逼，阅读能力差的跟今天有个人有一拼，没人逼你回答！

**Comment by fannwong001** [comment]
> 大佬本来就用爱发电，你是怎么做到伸手伸得那么理直气壮的？

你是为什么那么不理直气壮的？难道这里是需要讲人情世故先夸赞一番的地方吗？提交代码到这里来不就是为了互相指点进步的吗？如果你觉得别人说的不对可以不用理就是了，不知道很多国人为什么变得这样虚伪！

**Comment by LimonChoms** [comment]
> > 大佬本来就用爱发电，你是怎么做到伸手伸得那么理直气壮的？
> 
> 你是为什么那么不理直气壮的？难道这里是需要讲人情世故先夸赞一番的地方吗？提交代码到这里来不就是为了互相指点进步的吗？如果你觉得别人说的不对可以不用理就是了，不知道很多国人为什么变得这样虚伪！

敢问你提交了什么代码？有什么贡献？别人在这里分享东西不是让你在这理直气壮提要求的，你有需求有能力你可以自己提pr，没能力就客客气气麻烦一下说句谢谢，不知道你有什么脸要求别人做事？我没钱了是不是可以理直气壮找你要钱？一点素质没有，怪不得在别的项目被人closed了，也就是你这种人害得国内开源环境这么恶劣

**Comment by openips** [comment]
外挂naive客户端起socks5就可以了 不是只有1+1=2 0.5+1.5也是可以的 自己动手丰衣足食

**Comment by fannwong001** [comment]
> 外挂naive客户端起socks5就可以了 不是只有1+1=2 0.5+1.5也是可以的 自己动手丰衣足食

我会用脚本 也可以加过滤配置

**Comment by fannwong001** [comment]
> > > 大佬本来就用爱发电，你是怎么做到伸手伸得那么理直气壮的？
> 
> > 
> 
> > 你是为什么那么不理直气壮的？难道这里是需要讲人情世故先夸赞一番的地方吗？提交代码到这里来不就是为了互相指点进步的吗？如果你觉得别人说的不对可以不用理就是了，不知道很多国人为什么变得这样虚伪！
> 
> 
> 
> 敢问你提交了什么代码？有什么贡献？别人在这里分享东西不是让你在这理直气壮提要求的，你有需求有能力你可以自己提pr，没能力就客客气气麻烦一下说句谢谢，不知道你有什么脸要求别人做事？我没钱了是不是可以理直气壮找你要钱？一点素质没有，怪不得在别的项目被人closed了，也就是你这种人害得国内开源环境这么恶劣

先不说你丫有什么素质和能力，单就你这逻辑就知道你丫跟今天close我那人是一人，坚决不能跟你这类人多说话，真就是你最后这句话，其实是你这类货害得国内开源环境这么恶劣，你丫连要求都不敢提！

**Comment by fannwong001** [comment]
既然没人愿意听不好听的话那就关了吧，爱tnzdzd

**Comment by LGuangming** [comment]
> 既然没人愿意听不好听的话那就关了吧，爱tnzdzd

本来没习惯评论但看到你这个忍不了了哈哈，我一路人都觉得你是个煞笔了哈哈，国内开源环境这么恶劣，不就是因为你这种傻逼吗，怎么有自己骂自己的习惯。哈哈。

**Comment by LGuangming** [comment]
> 既然没人愿意听不好听的话那就关了吧，爱tnzdzd

本来没习惯评论但看到你这个忍不了了哈哈，我一路人都觉得你是个煞笔了哈哈，国内开源环境这么恶劣，不就是因为你这种傻逼吗，怎么有自己骂自己的习惯。哈哈。我寻思你那么有骨气不用呢，还屁颠屁颠跑去另一个opeclash提问题了，哈哈哈。下贱的人

**Comment by fannwong001** [comment]
> > 既然没人愿意听不好听的话那就关了吧，爱tnzdzd
> 
> 
> 
> 本来没习惯评论但看到你这个忍不了了哈哈，我一路人都觉得你是个煞笔了哈哈，国内开源环境这么恶劣，不就是因为你这种傻逼吗，怎么有自己骂自己的习惯。哈哈。我寻思你那么有骨气不用呢，还屁颠屁颠跑去另一个opeclash提问题了，哈哈哈。下贱的人

你们这种同一个群里的沙壁就别装了！像个男人一样坦白一点吧沙壁！装的像不认识一样的虚伪沙壁！你爷爷我从来也没有打算长期用、现在也没有在用、只是帮别人想用的测评一下，顺便说一下自己用后体验，你爷爷我自己写过翻墙协议自己会做命令行完全不需要这些界面！你这种沙壁从来不知道开源代码是为什么叫开源，从来不知道不同看法的意义，只愿意像个奴才一样匍匐于开发者面前，让开发者陶醉于别人的仰慕，让他们以为自己是在做慈善，你这种沙壁只会索取、只会捧臭脚、连抖内都舍不得、自己只要能用凑合就行、自己从来不提新功能旧bug要求、还瞧不起别人提，就是你这种low B搞的国内开源都烂的一批，功能bug一大堆还不愿意改、只要别人提的要求不中他意就直接diss，就这种臭毛病臭习惯都是你这种沙壁造成的！

**Comment by LimonChoms** [comment]
> > > 既然没人愿意听不好听的话那就关了吧，爱tnzdzd
> > 
> > 
> > 本来没习惯评论但看到你这个忍不了了哈哈，我一路人都觉得你是个煞笔了哈哈，国内开源环境这么恶劣，不就是因为你这种傻逼吗，怎么有自己骂自己的习惯。哈哈。我寻思你那么有骨气不用呢，还屁颠屁颠跑去另一个opeclash提问题了，哈哈哈。下贱的人
> 
> 你们这种同一个群里的沙壁就别装了！像个男人一样坦白一点吧沙壁！这边就是openclash，自己切换切糊涂了吧！装的像不认识一样的虚伪沙壁！你爷爷我从来也没有打算长期用、现在也没有在用、只是帮别人想用的测评一下，顺便说一下自己用后体验，你爷爷我自己写过翻墙协议自己会做命令行完全不需要这些界面！你这种沙壁从来不知道开源代码是为什么叫开源，从来不知道不同看法的意义，只愿意像个奴才一样匍匐于开发者面前，让开发者陶醉于别人的仰慕，让他们以为自己是在做慈善，你这种沙壁只会索取、只会捧臭脚、连抖内都舍不得、自己只要能用凑合就行、自己从来不提新功能旧bug要求、还瞧不起别人提，就是你这种low B搞的国内开源都烂的一批，功能bug一大堆还不愿意改、只要别人提的要求不中他意就直接diss，就这种臭毛病臭习惯都是你这种沙壁造成的！

所以说开发者应该像奴才一样接受意见是吧？那你开个项目吧，我让你体验一下当奴才的感觉

**Comment by fannwong001** [comment]
> > > > 既然没人愿意听不好听的话那就关了吧，爱tnzdzd
> 
> > > 
> 
> > > 
> 
> > > 本来没习惯评论但看到你这个忍不了了哈哈，我一路人都觉得你是个煞笔了哈哈，国内开源环境这么恶劣，不就是因为你这种傻逼吗，怎么有自己骂自己的习惯。哈哈。我寻思你那么有骨气不用呢，还屁颠屁颠跑去另一个opeclash提问题了，哈哈哈。下贱的人
> 
> > 
> 
> > 你们这种同一个群里的沙壁就别装了！像个男人一样坦白一点吧沙壁！这边就是openclash，自己切换切糊涂了吧！装的像不认识一样的虚伪沙壁！你爷爷我从来也没有打算长期用、现在也没有在用、只是帮别人想用的测评一下，顺便说一下自己用后体验，你爷爷我自己写过翻墙协议自己会做命令行完全不需要这些界面！你这种沙壁从来不知道开源代码是为什么叫开源，从来不知道不同看法的意义，只愿意像个奴才一样匍匐于开发者面前，让开发者陶醉于别人的仰慕，让他们以为自己是在做慈善，你这种沙壁只会索取、只会捧臭脚、连抖内都舍不得、自己只要能用凑合就行、自己从来不提新功能旧bug要求、还瞧不起别人提，就是你这种low B搞的国内开源都烂的一批，功能bug一大堆还不愿意改、只要别人提的要求不中他意就直接diss，就这种臭毛病臭习惯都是你这种沙壁造成的！
> 
> 
> 
> 所以说开发者应该像奴才一样接受意见是吧？那你开个项目吧，我让你体验一下当奴才的感觉

我前面说的是你们这种像奴才一样跪舔，所以我是痛恨国人这种态度的，现在你反过来曲解我认为我想让开发者像奴才一样，在你们的观念里是没有人格平等这一说的！动不动就大神大佬的叫着，实际生活中越是这种跪舔的人对不如自己的人的态度却是180度大转变！如果你觉得对于我提的诉求被冒犯或者难为情你最多就是不予理睬或者未计划关闭，我也不求你做圣人，但是那种“一副高高在上我做这种开发都是施舍给你们使用的人 然后我可以随便态度傲慢” 这种就是我讨厌的！时刻记住做开源不是做公益做施舍的！
