### ISSUE TITLE
[Feature] 能不能实现让某些mac或者ip的设备单独走global模式，而不影响主程序的代理模式

### ISSUE THREAD

**Issue by threerog** [vernesong/OpenClash#3134]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

能不能实现让某些mac或者ip的设备单独走global模式，而不影响主程序的代理模式

### Describe the Solution

能不能实现让某些mac或者ip的设备单独走global模式，而不影响主程序的代理模式

**Comment by deuteros-gex** [comment]
如果严格按你字面里的描述，那是做不到的。
但如果你只是想让特定设备的流量只走国外节点，那能做到，比如这台设备ip是192.168.0.3，需要走的国外节点/节点组名字叫tooyoung，添加一条自定义规则即可
SRC-IP-CIDR,192.168.0.3,tooyoung

**Comment by starua** [comment]
可以考虑添加一个专门侧策略组模仿GLOBAL配置，再在最上方添加自定义规则：
- SRC-IP-CIDR, <设备IP>, <策略组名字>
至于mac，可以在dnsmasq上配置静态地址，这样就能转化成上面这个了

**Comment by Cathgao** [comment]
> 可以考虑添加一个专门侧策略组模仿GLOBAL配置，再在最上方添加自定义规则：
> 
> ```
> - SRC-IP-CIDR, <设备IP>, <策略组名字>
> ```
> 
> 至于mac，可以在dnsmasq上配置静态地址，这样就能转化成上面这个了

请教一下，有方法可以做到下面这样的规则吗：

1. 指定某个内网IP或MAC设备的指定域名走代理，其他设备按照全局规则，如：192.168.1.100访问*.example.com代理
2. 反之亦然，就是某设备指定某域名走直连，其他设备走代理

**Comment by deuteros-gex** [comment]
> > 可以考虑添加一个专门侧策略组模仿GLOBAL配置，再在最上方添加自定义规则：
> > ```
> > - SRC-IP-CIDR, <设备IP>, <策略组名字>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 至于mac，可以在dnsmasq上配置静态地址，这样就能转化成上面这个了
> 
> 请教一下，有方法可以做到下面这样的规则吗：
> 
> 1. 指定某个内网IP或MAC设备的指定域名走代理，其他设备按照全局规则，如：192.168.1.100访问*.example.com代理
> 2. 反之亦然，就是某设备指定某域名走直连，其他设备走代理

假设你希望让局域网内ip为192.168.0.3访问域名中包含bilibili的网址时，走名叫tooyoung的节点/节点组。
那么在配置文件中添加以下内容：

> script:
>   shortcuts:
>    xsk1: "'bilibili' in host and src_ip == '192.168.0.103'"
> 
> rules:
> - SCRIPT,xsk1,tooyoung

仅仅是提示一下这个功能的存在，更多细节参考
https://lancellc.gitbook.io/clash/clash-config-file/script
语法走的是python3，看清楚我给的实例，不要遗漏任何单引号或双引号。
另外也需要注意yaml语法的缩进、大小写等规范（不要直接复制我的，我只是随手一写打个样。。）

**Comment by nevertoday** [comment]
> > > 可以考虑添加一个专门侧策略组模仿GLOBAL配置，再在最上方添加自定义规则：
> > > ```
> > > - SRC-IP-CIDR, <设备IP>, <策略组名字>
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 至于mac，可以在dnsmasq上配置静态地址，这样就能转化成上面这个了
> > 
> > 
> > 请教一下，有方法可以做到下面这样的规则吗：
> > 
> > 1. 指定某个内网IP或MAC设备的指定域名走代理，其他设备按照全局规则，如：192.168.1.100访问*.example.com代理
> > 2. 反之亦然，就是某设备指定某域名走直连，其他设备走代理
> 
> 假设你希望让局域网内ip为192.168.0.3访问域名中包含bilibili的网址时，走名叫tooyoung的节点/节点组。 那么在配置文档中添加以下内容：
> 
> ```
> script:
>    shortcuts:
>        xsk1: src_ip == '192.168.0.103'and 'bilibili' in host 
> rules:
>    - SCRIPT,xsk1,tooyoung
> ```
> 
> 仅仅是提示一下这个功能的存在，更多细节参考 https://lancellc.gitbook.io/clash/clash-config-file/script 语法走的是python3，另外也需要注意yaml语法的缩进、大小写等规范（不要直接复制我的，我只是随手一写打个样。。）

可以这么写？xsk1: src_ip == '192.168.0.103'and 'xiaohongshu' in host 
小红书单独指定？
