### ISSUE TITLE
OpenClash 无法启动

### ISSUE THREAD

**Issue by LunaticTian** [vernesong/OpenClash#314]
OpenClash今天之前使用正常，但是今早突然出现无法访问墙外的情况。重启clash有概率性启动但是无法使用，大部分时间都是无法启动状态。

LOG:

> Force Reset DNS Hijack。

或者

> OpenClash Can Not Start, Please Check The Error Info And Try Again

本地开启SmartDNS且未对SmartDNS或者其他DNS有过操作，尝试更换DNS也无法使用。
切换两种模式都出现如上问题。

![](http://img.lunatic.wang/%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE_20200408115154.png)

PS:koolclash也无法启动！

**Comment by okaygh** [comment]
难道不该是启动自定义上游吗...话说SmartDNS为啥有人tcp有人udp...有啥区别...

**Comment by pikachullk** [comment]
大佬在dns劫持不是有说明～openclash必须在所有dns的最上游～那smartdns还有必要吗…emmm～我也不懂

**Comment by LunaticTian** [comment]
> 大佬在dns劫持不是有说明～openclash必须在所有dns的最上游～那smartdns还有必要吗…emmm～我也不懂
> 然后你开启smartdns的话～剧情会不会是这样的：
> openclash：我劫持
> smartdns：滚，我劫持
> dnsmasq:mmp！！！！

哈哈哈，这不是问题的关键，问题的关键是就算把smartdns关掉使用推荐的自定义默认设置也导致失败。前几天相同的配置都是正常可用的。

**Comment by pikachullk** [comment]
> > 大佬在dns劫持不是有说明～openclash必须在所有dns的最上游～那smartdns还有必要吗…emmm～我也不懂
> > 然后你开启smartdns的话～剧情会不会是这样的：
> > openclash：我劫持
> > smartdns：滚，我劫持
> > dnsmasq:mmp！！！！
> 
> 哈哈哈，这不是问题的关键，问题的关键是就算把smartdns关掉使用推荐的自定义默认设置也导致失败。前几天相同的配置都是正常可用的。

主要你上面那个设置也没对啊…

**Comment by LunaticTian** [comment]
> > > 大佬在dns劫持不是有说明～openclash必须在所有dns的最上游～那smartdns还有必要吗…emmm～我也不懂
> > > 然后你开启smartdns的话～剧情会不会是这样的：
> > > openclash：我劫持
> > > smartdns：滚，我劫持
> > > dnsmasq:mmp！！！！
> > 
> > 
> > 哈哈哈，这不是问题的关键，问题的关键是就算把smartdns关掉使用推荐的自定义默认设置也导致失败。前几天相同的配置都是正常可用的。
> 
> 主要你上面那个设置也没对啊…

我的意思是我正确配置现在也无法使用

**Comment by pikachullk** [comment]
> > > > 大佬在dns劫持不是有说明～openclash必须在所有dns的最上游～那smartdns还有必要吗…emmm～我也不懂
> > > > 然后你开启smartdns的话～剧情会不会是这样的：
> > > > openclash：我劫持
> > > > smartdns：滚，我劫持
> > > > dnsmasq:mmp！！！！
> > > 
> > > 
> > > 哈哈哈，这不是问题的关键，问题的关键是就算把smartdns关掉使用推荐的自定义默认设置也导致失败。前几天相同的配置都是正常可用的。
> > 
> > 
> > 主要你上面那个设置也没对啊…
> 
> 我的意思是我正确配置现在也无法使用

要不还是:
firstboot
y
reboot -f
重启后
opkg remove smartdns
然后手动设置试试

**Comment by vernesong** [comment]
#112
