### ISSUE TITLE
[Bug] www.qq.com在打开了“实验性：绕过中国大陆 IP”后无法访问，其它网站暂时没影响

### ISSUE THREAD

**Issue by WFANG12719** [vernesong/OpenClash#3140]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.100

### Bug on Environment

Lean

### Bug on Platform

Linux-arm64

### To Reproduce

流量设置里勾选：实验性：绕过中国大陆 IP
然后应用设置。
再在浏览器打开www.qq.com，网站一直不显示，重新启动机器也不行。其它新闻类网站 www.sina.com.cn, www.sohu.com, www.163.com没有问题。

### Describe the Bug

实验性：绕过中国大陆 IP, 不知往防火墙添加了那条规则，在openclash里的日志一直检查不到日志关键子qq.com

### OpenClash Log

无日志输出

### OpenClash Config

```shell
在GUI界面勾选：实验性：绕过中国大陆 IP
```

### Expected Behavior

只要取消“绕过中国大陆 IP”，立马恢复正常。

### Screenshots

无

**Comment by WFANG12719** [comment]
勾选绕过中国大陆 IP后，大陆DNS解析填写的是119.29.29.29, 也尝试了119.28.28.28，都一样。

**Comment by VIKINGYFY** [comment]
请清除浏览器缓存，关掉安全DNS选项，清除电脑DNS缓存后尝试

![image](https://user-images.githubusercontent.com/7755795/227753235-27b93767-8ec3-4efe-b3d7-960b80bcb56e.png)

**Comment by WFANG12719** [comment]
还是不行。就没开secure DNS,然后再新装了个microsoft edge,也还不行，就是www.qq.com; news.qq.com上不了，奇怪了.我的是mac, 清DNS cache用的命令是 sudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder

**Comment by lovehuiping** [comment]
www.qq.com我倒正常

我开了 实验性：绕过中国大陆 IP” 这个功能后 交通买单吧APP 时不时会无法联网

如何快体体现  打开APP后>再关掉APP后台 >重新打开APP 随便去找个美食店铺 就会有30~50的概率打不开 白屏

**Comment by lovehuiping** [comment]
> [www.qq.com我倒正常](http://www.qq.com%E6%88%91%E5%80%92%E6%AD%A3%E5%B8%B8)
> 
> 我开了 实验性：绕过中国大陆 IP” 这个功能后 交通买单吧APP 时不时会无法联网
> 
> 如何快体体现 打开APP后>再关掉APP后台 >重新打开APP 随便去找个美食店铺 就会有30~50的概率打不开 白屏

----------------------------强迫症分割线------------------------
以前是用防火墙转发
OPC(无dnsmasq)>ADG

目前把交通买单吧的域名添加个不走核心名单(需要dnsmasq),让买单吧这个APP走核心(默认规则里已经有直连规则),暂时正常使用

从上面变成了 ADG>OPC(开启dnsmasq) 

弊端就是ADG不能显示客户端只显示一个本机的HOST客户端了 凑合了

**Comment by WFANG12719** [comment]
我客户端升级到了v0.45.112-beta，貌似大部分问题已经解决。我用的是一键更新，clash内核文件同步升级了。大家可以试一下。

**Comment by wakaka123wakaka** [comment]
我开了 实验性：绕过中国大陆 IP” 这个功能后 raw.githubusercontent.com 无法访问，ping获取到的ip是127.0.0.1，无解，关闭以后就自动好了
