### ISSUE TITLE
运行clash卡在{删除clash iptables}阶段

### ISSUE THREAD

**Issue by diyjack0326** [vernesong/OpenClash#3143]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

无法进行运行

### Describe the Solution

是我哪里设置有问题吗？

### Additional Context

![QQ截图20230326154412](https://user-images.githubusercontent.com/110292277/227762543-5fb92ee2-6783-4988-97eb-da2cde58f7c5.png)

**Comment by vernesong** [comment]
这个不是openclash

**Comment by diyjack0326** [comment]
openclash支持aarch64_cortex-a53固件吗？安装的时候依赖安装失败，安装包也安装不成功。
