### ISSUE TITLE
自定义规则（底部）的设置不恰当

### ISSUE THREAD

**Issue by gzw02140** [vernesong/OpenClash#315]
如果开启了自定义规则，程序会把最后的一条MATCH规则注释掉，添加完自定义底部规则后，加上- MATCH,DIRECT。这就使应该是白名单的规则变成了黑名单,没匹配的流量直连了。

例如
默认规则的最后两条是
\- GEOIP,CN,DIRECT
\- MATCH,Proxy

开启自定义规则后，会变成
\- GEOIP,CN,DIRECT
###- MATCH,Proxy
##Custom Rules 2##
……
##Custom Rules 2 End##
\- MATCH,DIRECT

如果开启白名单，就只有手动在自定义规则（底部）添加上一条- MATCH,Proxy。这样的话要切换不同的配置，得手动修改自定义规则（底部）。

建议可以自由选择是否启用自定义规则（底部），或者将自定义规则（底部）插入到最后一条MATCH规则的上面。

clash内核 v0.19.0-5-g5591e15
客户端版本 v0.37.2-beta

**Comment by vernesong** [comment]
这是你开启了仅代理命中规则流量的结果，另外脚本添加位置的逻辑有个小问题

**Comment by gzw02140** [comment]
> 这是你开启了仅代理命中规则流量的结果，另外脚本添加位置的逻辑有个小问题

解决了，谢谢

**Comment by touzi** [comment]
我也遇到了, 在规则模式下 match 能根据自己的配置文件生效, 但配置文件是含有 script 内容的时候 match 就变着默认到的 DIRECT 了. 目前只能不开启仅命中规则流量.
