### ISSUE TITLE
[Bug] fakeip模式下设置了绕过黑名单IP和MAC依旧过Clash处理

### ISSUE THREAD

**Issue by Rakau** [vernesong/OpenClash#3151]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.103-beta

### Bug on Environment

Lean

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

RT

### Describe the Bug

RT

### OpenClash Log

无对应Log

### Expected Behavior

正常绕过

**Comment by vernesong** [comment]
截图看看设置

**Comment by Rakau** [comment]
> 截图看看设置

已经好了，我切换到redir模式然后再切回来就正常了
