### ISSUE TITLE
[Bug] 页面崩溃了~

### ISSUE THREAD

**Issue by whfweb** [vernesong/OpenClash#3159]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.103-beta

### Bug on Environment

Other

### Bug on Platform

Linux-armv7

### To Reproduce

在openclash已正常工作的情况下，进入“配置管理”选项卡，点击页面最下方的“保存配置”或者“应用配置”。

### Describe the Bug

在openclash已正常工作的情况下，进入“配置管理”选项卡，点击页面最下方的“保存配置”或者“应用配置”，页面崩溃，显示：
Reference error
Unhandled exception during request dispatching
access to undeclared variable err
In [anonymous function](), file /usr/share/ucode/luci/http.uc, line 97, byte 10:
  called from function parse ([C])
  called from function mimedecode_message_body (/usr/share/ucode/luci/http.uc:111:26)
  called from function parse_message_body (/usr/share/ucode/luci/http.uc:180:51)
  called from function [anonymous function] (/usr/share/ucode/luci/http.uc:450:3)
  called from function [anonymous function] (/usr/share/ucode/luci/http.uc:374:22)
  called from function require_post_security (/usr/share/ucode/luci/dispatcher.uc:680:47)
  called from function [anonymous function] (/usr/share/ucode/luci/dispatcher.uc:995:35)
  called from anonymous function (/www/cgi-bin/luci:39:12)

 `            err = buffer;`
  Near here --------^

回退页面，openclash仍可正常工作。

### OpenClash Log

OpenClash 调试日志

生成时间: 2023-04-02 17:39:19
插件版本: v0.45.103-beta
隐私提示: 上传此日志前请注意检查、屏蔽公网IP、节点、密码等相关敏感信息

```

#===================== 系统信息 =====================#

主机型号: Linksys WRT1900AC v2
固件版本: OpenWrt SNAPSHOT r22670-e397f1eddb
LuCI版本: git-23.051.66410-a505bb1
内核版本: 5.15.105
处理器架构: arm_cortex-a9_vfpv3-d16

#此项有值时,如不使用IPv6,建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: 

DNS劫持: Dnsmasq 转发
#DNS劫持为Dnsmasq时，此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 127.0.0.1#7874

#===================== 依赖检查 =====================#

dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
libcap: 已安装
libcap-bin: 已安装
ruby: 已安装
ruby-yaml: 已安装
ruby-psych: 已安装
ruby-pstore: 已安装
kmod-tun(TUN模式): 已安装
luci-compat(Luci >= 19.07): 已安装
kmod-inet-diag(PROCESS-NAME): 已安装
unzip: 已安装
kmod-nft-tproxy: 已安装

#===================== 内核检查 =====================#

运行状态: 运行中
内核：Meta
进程pid: 5823
运行权限: 5823: cap_dac_override,cap_net_bind_service,cap_net_admin,cap_net_raw,cap_sys_ptrace,cap_sys_resource=eip
运行用户: nobody
已选择的架构: Meta

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 2023.03.04-5-g4a8cefb
Tun内核文件: 存在
Tun内核运行权限: 正常

Dev内核版本: v1.13.0-7-g4ffc999
Dev内核文件: 存在
Dev内核运行权限: 正常

Meta内核版本: alpha-g2f992e9
Meta内核文件: 存在
Meta内核运行权限: 正常

#===================== 插件设置 =====================#

当前配置文件: /etc/openclash/config/3.31.yaml
启动配置文件: /etc/openclash/3.31.yaml
运行模式: fake-ip
默认代理模式: rule
UDP流量转发(tproxy): 启用
自定义DNS: 停用
IPV6代理: 停用
IPV6-DNS解析: 停用
禁用Dnsmasq缓存: 启用
自定义规则: 停用
仅允许内网: 启用
仅代理命中规则流量: 停用
仅允许常用端口流量: 停用
绕过中国大陆IP: 停用
路由本机代理: 启用

#启动异常时建议关闭此项后重试
混合节点: 停用
保留配置: 停用

#启动异常时建议关闭此项后重试
第三方规则: 停用

#===================== 配置文件 =====================#

port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: info
external-controller: 0.0.0.0:9090
proxy-groups:
- name: "\U0001F680 节点选择"
  type: select
  proxies:
  - "♻️ 自动选择"
  - DIRECT





### OpenClash Config

_No response_

### Expected Behavior

希望重复如上操作，页面能正常保存/应用配置。

### Screenshots

![捕获](https://user-images.githubusercontent.com/40481696/229345079-d48359b0-09f6-47ba-a886-7832f60dd114.PNG)

**Comment by vernesong** [comment]
换个固件不要用SNAPSHOT

**Comment by whfweb** [comment]
好的
