### ISSUE TITLE
请问怎么设置某个ip或ip段直连呢

### ISSUE THREAD

**Issue by dalmie** [vernesong/OpenClash#316]
自定义规则里这样改对吗？
##排序在上的规则优先生效,如添加（去除规则前的#号）：

##限制单个IP地址直连
-SRC-IP-CIDR,192.168.11.59/60,DIRECT

对的话群晖ddns解析不出来呢。换ssp+后就可以。

**Comment by pikachullk** [comment]
-SRC-IP-CIDR,192.168.11.59/32,DIRECT

**Comment by dalmie** [comment]
> -SRC-IP-CIDR,192.168.11.59/32,DIRECT
感谢
小白问一下后面的32是什么意思呢？

**Comment by dalmie** [comment]
ip正常了，但是解析失败。

**Comment by pikachullk** [comment]
> ip正常了，但是解析失败。

ddns获取ip方式直接选接口～选wan口～完美

**Comment by dalmie** [comment]
群晖设置IP的时候没有接口选项呢，直接更改成路由ip也是解析不出来

**Comment by pikachullk** [comment]
> 群晖设置IP的时候没有接口选项呢，直接更改成路由ip也是解析不出来

其实群晖那个ddns速度贼慢...实在不行用个3322的免费域名都会比他快~路由器的DDNS功能别浪费了

**Comment by dalmie** [comment]
感谢
现在主要是ip识别后解析不出来，ssp+却没问题。群晖只支持自己的ddns

**Comment by vernesong** [comment]
插件怎么配置的

**Comment by pikachullk** [comment]
> 感谢
> 现在主要是ip识别后解析不出来，ssp+却没问题。群晖只支持自己的ddns

我又不是没用过群晖～把5000端口转发给这个ip就行了～群晖各大app都能自定义连接url…因为fake-ip才导致这个问题的其实～如果实在要用群晖的ddns～用redir-host就行了～但速度会慢点

**Comment by dalmie** [comment]
访问控制里面启用了自定义规则。其他还有需要设置的吗？模式是fake-ip模式

**Comment by dalmie** [comment]
> > 感谢
> > 现在主要是ip识别后解析不出来，ssp+却没问题。群晖只支持自己的ddns
> 
> 我又不是没用过群晖～把5000端口转发给这个ip就行了～群晖各大app都能自定义连接url…因为fake-ip才导致这个问题的其实～如果实在要用群晖的ddns～用redir-host就行了～但速度会慢点

现在是在旁路油上开启的openclash。昨天添加了一个ddns才发现有其他自定义ddns。试了一下redir-host模式可以了。再次感谢。端口转发暂时先不研究了。这样用着吧。

**Comment by pikachullk** [comment]
> > > 感谢
> > > 现在主要是ip识别后解析不出来，ssp+却没问题。群晖只支持自己的ddns
> > 
> > 
> > 我又不是没用过群晖～把5000端口转发给这个ip就行了～群晖各大app都能自定义连接url…因为fake-ip才导致这个问题的其实～如果实在要用群晖的ddns～用redir-host就行了～但速度会慢点
> 
> 现在是在旁路油上开启的openclash。昨天添加了一个ddns才发现有其他自定义ddns。试了一下redir-host模式可以了。再次感谢。端口转发暂时先不研究了。这样用着吧。

还是要感谢vernesong大佬才对~没他开发这个我们连讨论的机会都没有~哈哈~应该可以close了这个issue
