### ISSUE TITLE
[Feature] 流量控制 - IPv4 代理地址（IPv4 绕过地址 的反选）

### ISSUE THREAD

**Issue by ljcbaby** [vernesong/OpenClash#3163]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

TUN 模式下，即使域名已经不走 fake-ip(mosdns分流实现)仍然会被 utun 吃进来导致无法实现绕过内核

### Describe the Solution

提供一个选项+另一个列表，使utun默认只吃掉列表中IP的请求

### Additional Context

列表的默认值应该是 fake-ip+常用国外dns+telegramcidr

**Comment by vernesong** [comment]
开发者模式自己写防火墙不就行了

**Comment by ljcbaby** [comment]
现有这个还在不会有问题吗？我看除了当前列表，还会把网关ip之类的加上

**Comment by vernesong** [comment]
目的地址是内网能有啥影响，默认return啊
