### ISSUE TITLE
[Bug] 覆写设置-dns设置-开启Fallback-Filter

### ISSUE THREAD

**Issue by godashang** [vernesong/OpenClash#3165]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.103-beta

### Bug on Environment

Other

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

发现只能写到4130行。而且超过后点击保存时，原有的nameserver及fallbackserver的配置会消失掉。

### Describe the Bug

原本要写上5000多行，发现写了不了，再去试，发现只能写到4130行。只要在4130行以内，就可以保存。正常使用。

### OpenClash Log

失去

### Expected Behavior

不应该有限制

**Comment by godashang** [comment]
我尝试关闭openclash之后我进custom目录，把内容写进openclash_custom_fallback_filter.yaml，然后启动openclash，发现成功了。进界面fallbak-filter，可以看到全部，5000多条。

**Comment by vernesong** [comment]
dev已经修了

**Comment by godashang** [comment]
> dev已经修了

thanks

**Comment by QuincySx** [comment]
其实 Meta 内核的 Fallback-Filter 支持 Geosite https://docs.metacubex.one/function/dns/fallback
```
  geosite:
    - gfw
    - "!cn"
```
