### ISSUE TITLE
[Bug] DNS里面的自定义 Fallback-Filter只能添加几十条规则

### ISSUE THREAD

**Issue by Guan920** [vernesong/OpenClash#3169]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.103

### Bug on Environment

Other

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

无

### Describe the Bug

全局设置-DNS设置 里面的自定义 Fallback-Filter 只能添加几十条规则、复制几千条规则保存后最后就剩下几十条。最后一个正常的版本是v0.45.87

### OpenClash Log

无

### Expected Behavior

无

### Screenshots

<img width="1203" alt="屏幕截图 2023-04-07 210852" src="https://user-images.githubusercontent.com/97109825/230614307-579f5ff6-36c1-4ff9-b292-0d3206c01b72.png">

**Comment by vernesong** [comment]
![image](https://user-images.githubusercontent.com/42875168/230646303-b9eebd6d-8074-4ea7-beff-7b4b9a6d5c12.png)
什么固件，给个地址我

**Comment by Guan920** [comment]
骷髅头的:https://github.com/DHDAXCW
istoreos:https://fw.koolcenter.com/iStoreOS/x86_64/
好像不是固件问题，还试过几个别的论坛里的固件，都会出现这个问题！



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: vernesong ***@***.***&gt;
发送时间: 2023年4月8日 00:48
收件人: vernesong/OpenClash ***@***.***&gt;
抄送: Guan920 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [vernesong/OpenClash] [Bug] DNS里面的自定义 Fallback-Filter只能添加几十条规则 (Issue #3169)





 

 什么固件，给个地址我
