### ISSUE TITLE
[Bug] openclash规则失效，连接中只显示IP，不显示域名。

### ISSUE THREAD

**Issue by 124316030** [vernesong/OpenClash#3172]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.103-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

更新过后就如此，以前是好的。

### Describe the Bug

openclash旁路由，无论我如何设置，从上上次更新之后，！！！规则就失效了！！！，规则只有MATCH 和 GEOIP, 取而代之的如截图，clash面板连接中只显示IP, 不显示域名了，求大神帮助一下！谢谢~！

### OpenClash Log

OpenClash 调试日志

生成时间: 2023-04-07 23:25:58
插件版本: v0.45.103-beta
隐私提示: 上传此日志前请注意检查、屏蔽公网IP、节点、密码等相关敏感信息

```

#===================== 系统信息 =====================#

主机型号: QEMU Standard PC (i440FX + PIIX, 1996) - Intel(R) Celeron(R) J4125 CPU @ 2.00GHz : 2 Core 2 Thread
固件版本: OpenWrt SNAPSHOT r5793-1ac276866
LuCI版本: git-23.065.55910-800c6df-1
内核版本: 5.15.98
处理器架构: x86_64

#此项有值时,如不使用IPv6,建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: 

DNS劫持: Dnsmasq 转发
#DNS劫持为Dnsmasq时，此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 127.0.0.1#7874

#===================== 依赖检查 =====================#

dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
libcap: 已安装
libcap-bin: 未安装
ruby: 未安装
ruby-yaml: 未安装
ruby-psych: 未安装
ruby-pstore: 已安装
kmod-tun(TUN模式): 未安装
luci-compat(Luci >= 19.07): 未安装
kmod-inet-diag(PROCESS-NAME): 未安装
unzip: 已安装
iptables-mod-tproxy: 已安装
kmod-ipt-tproxy: 已安装
iptables-mod-extra: 已安装
kmod-ipt-extra: 已安装
kmod-ipt-nat: 已安装

#===================== 内核检查 =====================#

运行状态: 运行中
内核：Meta
进程pid: 21242
运行权限: 21242: cap_dac_override,cap_net_bind_service,cap_net_admin,cap_net_raw,cap_sys_ptrace,cap_sys_resource=eip
运行用户: nobody
已选择的架构: Meta

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 2023.03.04-5-g4a8cefb
Tun内核文件: 存在
Tun内核运行权限: 正常

Dev内核版本: v1.13.0-7-g4ffc999
Dev内核文件: 存在
Dev内核运行权限: 正常

Meta内核版本: alpha-g2f992e9
Meta内核文件: 存在
Meta内核运行权限: 正常

#===================== 插件设置 =====================#

当前配置文件: /etc/openclash/config/henry1.yaml
启动配置文件: /etc/openclash/henry1.yaml
运行模式: fake-ip
默认代理模式: rule
UDP流量转发(tproxy): 停用
自定义DNS: 启用
IPV6代理: 停用
IPV6-DNS解析: 停用
禁用Dnsmasq缓存: 启用
自定义规则: 停用
仅允许内网: 启用
仅代理命中规则流量: 停用
仅允许常用端口流量: 停用
绕过中国大陆IP: 启用
路由本机代理: 启用

#启动异常时建议关闭此项后重试
混合节点: 停用
保留配置: 停用

#启动异常时建议关闭此项后重试
第三方规则: 停用


### OpenClash Config

_No response_

### Expected Behavior

求恢复到规则可以用，域名可以显示，而不是IP。

### Screenshots

![FireShot Capture 003 - Clash - 192 168 2 11](https://user-images.githubusercontent.com/113280873/230636008-c04e4a51-c3d2-4256-a29d-2135afcd8070.jpg)

**Comment by 124316030** [comment]
![FireShot Capture 003 - Clash - 192 168 2 11](https://user-images.githubusercontent.com/113280873/230636406-efd77491-1de3-435f-b5f1-a49e185faf88.jpg)

**Comment by vernesong** [comment]
插件设置，DNS劫持改为防火墙

**Comment by 124316030** [comment]
> 插件设置，DNS劫持改为防火墙

感谢您的回复，试过这么设置了，依旧是规则不生效 且 只显示IP。  windows clash就可以显示域名。

**Comment by vernesong** [comment]
你检查DNS被谁先解析了，是不是开了安全DNS

**Comment by 124316030** [comment]
> 你检查DNS被谁先解析了，是不是开了安全DNS

麻烦您帮看看，我上网找了一下如何查询DNS解析顺序，这是关了MCFEE防火墙后查询的，另，chrome没有开安全DNS.
这个结果是不是有问题呢，如何恢复？

Resolved IP addresses of "baidu.com": ["110.242.68.66","39.156.66.10"].
Resolved IP addresses of "www.youtube.com": ["172.217.163.46","142.251.43.14","172.217.160.110","142.251.42.238"].
Resolved IP addresses of "github.com": ["140.82.113.3"].

**Comment by LimonChoms** [comment]
你都知道网关设置旁路由了，那dns肯定也是设置旁路由

**Comment by 124316030** [comment]
> 你都知道网关设置旁路由了，那dns肯定也是设置旁路由

是的，琢磨出来了，DNS设置了旁路由，之前看YOUTUBE学乱了，谢谢！

**Comment by cutbuzz** [comment]
我也是这个问题 fakeip就正常 用redir模式就是全ip

**Comment by kingcard1131** [comment]
我用meta内核就是IP，不启用meta内核就正常是域名。另外我加了adguardhome做dns服务器，重定向是使用53端口替换dnsmaq，不知道和这个有关系没

**Comment by xuanqb** [comment]
我用meta也是只显示IP

**Comment by kingcard1131** [comment]
> 我用meta也是只显示IP

有办法解决吗

**Comment by xuanqb** [comment]
> > 我用meta也是只显示IP
> 
> 有办法解决吗

没有找到解决方法，把meta关掉了

**Comment by 1187887012** [comment]
我用旁路由openclash也碰到这个问题了，自定义规则是用域名写的走代理的规则，但是访问不生效，查看openclash的内核日志发现访问的网站不是域名而是被解析成了ip，而解析成的ip又和geoip库里的不走代理ip匹配上了，所以访问这个网站不走代理（即使设置了自定义规则），把电脑的dns设置成114.114.114.114刚开始确实解决了，但过了一会又变成ip了，不知道该咋解决啊

**Comment by laughtLOOL** [comment]
> 我用meta内核就是IP，不启用meta内核就正常是域名。另外我加了adguardhome做dns服务器，重定向是使用53端口替换dnsmaq，不知道和这个有关系没

我的版本是0.45.162-beta 客户端
meta内核 alpha-g1d3e9f4

我也是有adg在clash的后面，由于很久没升级从2021升级了tun最新版本之后就出现了一半域名一半ip的情况，而meta更是离谱，直接全都是ip了，后来改动了很多地方，首先我是192*  2.3 clash，2.2 adg, 2.2 DNS填 2.3在接口哪里，在adh哪里填上游dns 2.3 下面bootstrap dns也填2.3, 2个都关闭dnsmasq在 网络 dhcp/dns 把基本设置和高级设置默认的勾全消，在openclash哪里设置是meta启动 fakeip tun 模式， 网络类型system 关闭旁路由兼容，第二个 流量控制 关闭路由本机代理只开quic dns设置 本地dns劫持 使用防火墙转发 
然后菜单覆盖设置里 dns设置 开了 追加上游dns 其他就没了，恢复之前的有域名显示能分流

**Comment by SandMioB** [comment]
https://github.com/vernesong/OpenClash/issues/3171#issuecomment-1506556071
按这兄弟给出的方法试一下，我这边是就这样解决了，感觉是bug。

**Comment by zhimadelvdou** [comment]
> [#3171 (comment)](https://github.com/vernesong/OpenClash/issues/3171#issuecomment-1506556071) 按这兄弟给出的方法试一下，我这边是就这样解决了，感觉是bug。

果然改了就好了

**Comment by hackhuman** [comment]
> > [#3171 (comment)](https://github.com/vernesong/OpenClash/issues/3171#issuecomment-1506556071) 按这兄弟给出的方法试一下，我这边是就这样解决了，感觉是bug。
> 
> 果然改了就好了

确实牛逼

**Comment by PeterChen1997** [comment]
确实要打开第三个，华佗再世》。。

**Comment by pavideo** [comment]
同样的问题，确实是要开第三个，成功解决麻烦。open clash坑实在太多了，本小白实在难以招架

**Comment by Duuck-D** [comment]
> [#3171 (comment)](https://github.com/vernesong/OpenClash/issues/3171#issuecomment-1506556071) 按这兄弟给出的方法试一下，我这边是就这样解决了，感觉是bug。

确实好了，牛逼，查了好几天了一直没解决，这个一下就好了

**Comment by potoo0** [comment]
我这边也出现了 PC 都是 ip，内核日志中大量 `i/o timeout`, 但我这里出现的原因其实是因为电脑流量已经走了代理, 到路由器时自然发现大量的代理服务器 ip 地址。

未预料电脑也经过代理的情况:
1. 电脑以前安装了 [clash-verge-rev/clash-verge-rev](https://github.com/clash-verge-rev/clash-verge-rev) 1.x 版本
2. 然后升级 2.x 之前没有卸载直接覆盖安装的
3. 导致即使没有启动 clash-verge-rev 的情况下连接实际还是经过了 tun 接口

路由器端内核日志:
```
411	[warning]	[TCP] dial DIRECT (match Match/) 192.168.8.226:65136 --> 20.205...:443 error: dial tcp 20.205...:443: i/o timeout
410	[warning]	[TCP] dial DIRECT (match Match/) 192.168.8.226:65167 --> 31.13...:443 error: dial tcp 31.13...:443: connect: connection refused
409	[warning]	[TCP] dial DIRECT (match Match/) 192.168.8.226:65165 --> 31.13...:443 error: dial tcp 31.13...:443: connect: connection refused
408	[warning]	[TCP] dial DIRECT (match Match/) 192.168.8.226:65161 --> 172.67...:443 error: dial tcp 172.67...:443: connect: connection refused
407	[warning]	[TCP] dial DIRECT (match Match/) 192.168.8.226:65159 --> 104.26...:443 error: dial tcp 104.26...:443: connect: connection refused
406	[warning]	[TCP] dial DIRECT (match Match/) 192.168.8.226:65167 --> 31.13...:443 error: dial tcp 31.13...:443: connect: connection refused
405	[warning]	[TCP] dial DIRECT (match Match/) 192.168.8.226:65167 --> 31.13...:443 error: dial tcp 31.13...:443: connect: connection refused
404	[warning]	[TCP] dial DIRECT (match Match/) 192.168.8.226:65161 --> 172.67...:443 error: dial tcp 172.67...:443: connect: connection refused
403	[info]	[TCP] 192.168.8.226:65160 --> 104.26...:443 match Match using DIRECT
402	[warning]	[TCP] dial DIRECT (match Match/) 192.168.8.226:65165 --> 31.13...:443 error: dial tcp 31.13...:443: connect: connection refused
401	[warning]	[TCP] dial DIRECT (match Match/) 192.168.8.226:65167 --> 31.13...:443 error: dial tcp 31.13...:443: connect: connection refused
400	[warning]	[TCP] dial DIRECT (match Match/) 192.168.8.226:65161 --> 172.67...:443 error: dial tcp 172.67...:443: connect: connection refused
399	[warning]	[TCP] dial DIRECT (match Match/) 192.168.8.226:65159 --> 104.26...:443 error: dial tcp 104.26...:443: connect: connection refused
398	[warning]	[TCP] dial DIRECT (match Match/) 192.168.8.226:65165 --> 31.13...:443 error: dial tcp 31.13...:443: connect: connection refused
397	[warning]	[TCP] dial DIRECT (match Match/) 192.168.8.226:65167 --> 31.13...:443 error: dial tcp 31.13...:443: connect: connection refused
```
