### ISSUE TITLE
[Feature] 希望能在官方luci源上看到这个插件

### ISSUE THREAD

**Issue by 8MiYile** [vernesong/OpenClash#3173]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

无

### Describe the Solution

https://github.com/openwrt/luci/tree/master/applications
希望能在这个项目开一个编译源 分支build master
然后同步到官方源 以方便在官方仓库下载
就意思就是更新分支master编译包的同步到这里

**Comment by vernesong** [comment]
官方pr需要js重构，暂时没计划

**Comment by 8MiYile** [comment]
@vernesong  
但奇怪的是我直接安装能用啊。。。
