### ISSUE TITLE
iptables问题

### ISSUE THREAD

**Issue by rilyuuj** [vernesong/OpenClash#318]
请问哪个设置造成运行iptables -t nat -nL --line-number会多出来两条记录：
> 1    REDIRECT   tcp  --  0.0.0.0/0            8.8.4.4              redir ports 7892
> 2    REDIRECT   tcp  --  0.0.0.0/0            8.8.8.8              redir ports 7892

少了一条cloud_music的规则（我是参考wikiDNS设置的）

另外我在防火墙里添加里下面的规则，请问会和openclash冲突嘛？
> iptables -t nat -I POSTROUTING -o eth0 -j MASQUERADE

因为我是做旁路由的，必须加这一条地址伪装，因为和openclash都是PREROUTING chain怕冲突所以特别问一下。。

再问下目前手机百度老是加载不了图片，在哪可以比较直观查看代理过程？需要进行下排查。。

**Comment by vernesong** [comment]
```
iptables -t nat -I POSTROUTING -o eth0 -j MASQUERADE
```
这条应该不需要了，插件开启后流量本身都是以旁路由的IP发出去的
控制面板里面可以看日志和连接情况
