### ISSUE TITLE
[Feature] ruby依赖相关---去除去配置文件的校验，或者添加强制使用配置文件的开关。

### ISSUE THREAD

**Issue by yyysuo** [vernesong/OpenClash#3180]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

网上很多人遇到因为固件导致的ruby依赖问题，很多时候配置是没问题的，能否去除对配置文件的强制检查，或者加个强制使用配置文件的开关？

### Describe the Solution

去除对配置文件的强制检查，或者加个强制使用配置文件的开关。

**Comment by vernesong** [comment]
ruby 主要作用是读写配置文件

**Comment by yyysuo** [comment]
> ruby 主要作用是读写配置文件

那估计确实不方便了，不过网上遇到ruby问题的，没有1000，也有800了，也确实是个门槛，我忍了4年，前几天刚换了固件，才解决掉这个问题。

**Comment by vernesong** [comment]
很早之前没有ruby，改配置文件老是出问题，既然是作为依赖，其正常工作是基本，而且openwrt上也没有其他好的办法

**Comment by zhjh0521** [comment]
> > ruby 主要作用是读写配置文件
> 
> 那估计确实不方便了，不过网上遇到ruby问题的，没有1000，也有800了，也确实是个门槛，我忍了4年，前几天刚换了固件，才解决掉这个问题。

怎么换固件？小白一枚，遇到ruby依赖问题，不知道怎么搞了。麻烦说的详细点

**Comment by yyysuo** [comment]
> > > ruby 主要作用是读写配置文件
> 
> > 
> 
> > 那估计确实不方便了，不过网上遇到ruby问题的，没有1000，也有800了，也确实是个门槛，我忍了4年，前几天刚换了固件，才解决掉这个问题。
> 
> 
> 
> 怎么换固件？小白一枚，遇到ruby依赖问题，不知道怎么搞了。麻烦说的详细点

重新刷个自带openclas的固件呀
