### ISSUE TITLE
内核报错。求一套稳定点的的程序版本与内核版本组合

### ISSUE THREAD

**Issue by sunyink** [vernesong/OpenClash#3181]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

0.45.100-bate & 0.45.103-bate

### Bug on Environment

Lean

### Bug on Platform

Linux-armv7

### To Reproduce

LEDE与Openclash同时开启，clash使用redir-host 兼容。 

### Describe the Bug

LEDE与Openclash同时开启，过一段时间就会因为clash的内核报错导致LEDE的内核也一并报错，通常导致一段时间断网，期间整个内回环也非常慢。

### OpenClash Log

[OpenClash-2023-3-10-2-26-26.log](https://github.com/vernesong/OpenClash/files/11197649/OpenClash-2023-3-10-2-26-26.log)

### OpenClash Config

`
config openclash 'config'
	option proxy_port '7892'
	option tproxy_port '7895'
	option mixed_port '7893'
	option socks_port '7891'
	option http_port '7890'
	option dns_port '7874'
	option update '0'
	option cn_port '9090'
	option dashboard_password '123456'
	option dashboard_forward_ssl '0'
	option rule_source '0'
	option ipv6_enable '0'
	option ipv6_dns '0'
	option other_rule_auto_update '0'
	option servers_if_update '0'
	option servers_update '0'
	option log_level '0'
	option proxy_mode 'rule'
	option intranet_allowed '1'
	option disable_udp_quic '1'
	option enable_rule_proxy '0'
	option filter_aaaa_dns '0'
	option small_flash_memory '0'
	option interface_name '0'
	option log_size '1024'
	option tolerance '0'
	option store_fakeip '0'
	option custom_fallback_filter '0'
	option custom_fakeip_filter '0'
	option custom_host '0'
	option custom_name_policy '0'
	option stream_domains_prefetch '0'
	option stream_auto_select '0'
	option bypass_gateway_compatible '0'
	option github_address_mod '0'
	option urltest_address_mod '0'
	option urltest_interval_mod '0'
	option delay_start '0'
	option router_self_proxy '1'
	option release_branch 'master'
	option dashboard_type 'Official'
	option yacd_type 'Official'
	option append_default_dns '0'
	option geo_custom_url 'https://testingcf.jsdelivr.net/gh/alecthw/mmdb_china_ip_list@release/lite/Country.mmdb'
	option chnr_custom_url 'https://ispip.clang.cn/all_cn.txt'
	option chnr6_custom_url 'https://ispip.clang.cn/all_cn_ipv6.txt'
	option cndomain_custom_url 'https://testingcf.jsdelivr.net/gh/felixonmars/dnsmasq-china-list@master/accelerated-domains.china.conf'
	option core_version 'linux-armv7'
	option default_resolvfile '/tmp/resolv.conf.d/resolv.conf.auto'
	option config_path '/etc/openclash/config/Tag3.yaml'
	option restricted_mode '0'
	option dnsmasq_noresolv '0'
	option dnsmasq_resolvfile '/tmp/resolv.conf.d/resolv.conf.auto'
	option cachesize_dns '0'
	option redirect_dns '0'
	option enable_custom_dns '1'
	option find_process_mode '0'
	option global_client_fingerprint '0'
	option enable_meta_sniffer '0'
	option geodata_loader '0'
	option enable_geoip_dat '0'
	option enable_custom_clash_rules '1'
	option geo_auto_update '0'
	option geo_update_week_time '1'
	option geo_update_day_time '0'
	option geoip_auto_update '0'
	option geosite_auto_update '0'
	option chnr_auto_update '0'
	option chnr_update_week_time '1'
	option chnr_update_day_time '0'
	option auto_restart '0'
	option auto_restart_week_time '1'
	option auto_restart_day_time '0'
	option auto_update '1'
	option config_auto_update_mode '0'
	option config_update_week_time '1'
	option auto_update_time '6'
	option operation_mode 'redir-host'
	option lan_ac_mode '0'
	option common_ports '0'
	option append_wan_dns '1'
	option enable_meta_core '0'
	option china_ip_route '1'
	option enable_redirect_dns '2'
	option en_mode 'redir-host'
	option enable_udp_proxy '0'
	list lan_ac_black_ips '192.168.2.1/32'
	list lan_ac_black_ips '192.168.2.2/31'
	list lan_ac_black_ips '192.168.2.4/30'
	list lan_ac_black_ips '192.168.2.8/29'
	list lan_ac_black_ips '192.168.2.16/28'
	list lan_ac_black_ips '192.168.2.32/27'
	list lan_ac_black_ips '192.168.2.64/26'
	list lan_ac_black_ips '192.168.2.128/25'
	list lan_ac_black_ips '192.168.3.0/24'
	list lan_ac_black_ips '192.168.4.0/22'
	list lan_ac_black_ips '192.168.8.0/21'
	list lan_ac_black_ips '192.168.16.0/20'
	list lan_ac_black_ips '192.168.32.0/19'
	list lan_ac_black_ips '192.168.64.0/18'
	list lan_ac_black_ips '192.168.128.0/17'
	option core_type 'TUN'
	list lan_ac_black_ports '10690'
	list lan_ac_black_ports '10695'
	list lan_ac_black_ports '5000'
	list lan_ac_black_ports '10183'
	option config_reload '1'
	option enable '0'

config dns_servers
	option group 'nameserver'
	option type 'udp'
	option ip '114.114.114.114'
	option enabled '0'

config dns_servers
	option group 'nameserver'
	option type 'udp'
	option ip '119.29.29.29'
	option enabled '0'

config dns_servers
	option group 'nameserver'
	option type 'udp'
	option ip '119.28.28.28'
	option enabled '0'

config dns_servers
	option group 'nameserver'
	option type 'udp'
	option ip '223.5.5.5'
	option enabled '0'

config dns_servers
	option type 'https'
	option ip 'doh.pub/dns-query'
	option group 'nameserver'
	option enabled '0'

config dns_servers
	option type 'https'
	option ip 'dns.alidns.com/dns-query'
	option group 'nameserver'
	option enabled '0'

config dns_servers
	option type 'https'
	option group 'fallback'
	option ip 'dns.cloudflare.com/dns-query'
	option enabled '0'

config dns_servers
	option group 'fallback'
	option ip 'dns.google'
	option port '853'
	option type 'tls'
	option enabled '0'

config dns_servers
	option group 'fallback'
	option type 'https'
	option ip '1.1.1.1/dns-query'
	option enabled '0'

config dns_servers
	option group 'fallback'
	option ip '1.1.1.1'
	option port '853'
	option type 'tls'
	option enabled '0'

config dns_servers
	option group 'fallback'
	option ip '8.8.8.8'
	option port '853'
	option type 'tls'
	option enabled '0'

config dns_servers
	option type 'udp'
	option group 'fallback'
	option ip '2001:4860:4860::8888'
	option port '53'
	option enabled '0'

config dns_servers
	option type 'udp'
	option group 'fallback'
	option ip '2001:4860:4860::8844'
	option port '53'
	option enabled '0'

config dns_servers
	option type 'udp'
	option group 'fallback'
	option ip '2001:da8::666'
	option port '53'
	option enabled '0'

config dns_servers
	option group 'fallback'
	option type 'https'
	option ip 'public.dns.iij.jp/dns-query'
	option enabled '0'

config dns_servers
	option group 'fallback'
	option type 'https'
	option ip 'jp.tiar.app/dns-query'
	option enabled '0'

config dns_servers
	option group 'fallback'
	option type 'https'
	option ip 'jp.tiarap.org/dns-query'
	option enabled '0'

config dns_servers
	option group 'fallback'
	option ip 'jp.tiar.app'
	option type 'tls'
	option enabled '0'

config dns_servers
	option group 'fallback'
	option ip 'dot.tiar.app'
	option type 'tls'
	option enabled '0'

config authentication
	option enabled '1'
	option username 'Clash'
	option password 'tT9JLkgs'
`

### Expected Behavior

不知道是不是独我一家，如果那样，若你的 LEDE+openclash很稳定，麻烦回一下程序版本与内核版本，我试着再重编一版。

**Comment by VIKINGYFY** [comment]
R4S，LEDE R23.4.1，5.15.104，OC版本v0.45.108-beta，fake-ip tun模式，meta内核，ipv6代理，绕过大陆白名单模式，原生机场+第三方订阅

稳得1B

**Comment by gj0518** [comment]
> R4S，LEDE R23.4.1，5.15.104，OC版本v0.45.108-beta，fake-ip tun模式，meta内核，ipv6代理，绕过大陆白名单模式，原生机场+第三方订阅
> 
> 稳得1B

给个下载地址好吗，谢谢

**Comment by VIKINGYFY** [comment]
> > R4S，LEDE R23.4.1，5.15.104，OC版本v0.45.108-beta，fake-ip tun模式，meta内核，ipv6代理，绕过大陆白名单模式，原生机场+第三方订阅
> > 稳得1B
> 
> 给个下载地址好吗，谢谢

https://github.com/VIKINGYFY/OWRT-CI

我的云编译项目，每天自动编译，lede源和imm源，有需要的请点星收藏。enjoy~

**Comment by gj0518** [comment]
> > > R4S，LEDE R23.4.1，5.15.104，OC版本v0.45.108-beta，fake-ip tun模式，meta内核，ipv6代理，绕过大陆白名单模式，原生机场+第三方订阅
> > > 稳得1B
> > 
> > 
> > 给个下载地址好吗，谢谢
> 
> https://github.com/VIKINGYFY/OWRT-CI
> 
> 我的云编译项目，每天自动编译，lede源和imm源，有需要的请点星收藏。enjoy~

用用看，感谢
