### ISSUE TITLE
[Feature] Auto select new proxy on failure

### ISSUE THREAD

**Issue by Mohsen7s** [vernesong/OpenClash#3182]
### Describe the Feature

When a single proxy fail or gets blocked, the user will lose their network connection until select another proxy node manually while it could be done automatically.

### Describe the Solution

We need a auto-switch proxy on failure.
This feature is for subscribing where more than one proxy node is available.
Once a proxy fail to connect or lose it's connectivity, automatically it could select next available proxy sorted by Ping/Speed.

**Comment by vernesong** [comment]
use fallback group

**Comment by vernesong** [comment]
clash can not select depend on uploading speed right now, how about urltest group? you can edit speedtest url here:
![image](https://user-images.githubusercontent.com/42875168/232760115-85ecd808-05d0-4d08-8ccc-9c191d3b26a5.png)

**Comment by vernesong** [comment]
use meta core & meta yacd panel you can select proxies in urltest group
