### ISSUE TITLE
[Bug] 110版本面板链接问题反馈

### ISSUE THREAD

**Issue by dycwuxing** [vernesong/OpenClash#3190]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.110-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

随时

### Describe the Bug

面板-链接-出现需要DNS作为客户端链接的显示,103及以前并未如此
<img width="1006" alt="image" src="https://user-images.githubusercontent.com/44988562/232203131-747c5044-b71e-4e03-b394-e66cdcb2a4fb.png">

### OpenClash Log

103及以前并未如此,配置并未变动

### OpenClash Config

```shell
无
```

### Expected Behavior

希望仅显示本地客户端

**Comment by vernesong** [comment]
什么内核什么模式，这个DNS链接是哪里发起的

**Comment by dycwuxing** [comment]
> 什么内核什么模式，这个DNS链接是哪里发起的
Redir-Host兼容模式,我已经回退103了....印象里目标IP是我本地的公网IP,忘记截图了,不好意思~

**Comment by lovehuiping** [comment]
我更新完110版本 然后面板连接 是直接大量显示连接192.168.1.104(99+) 然后网络还崩了......我是开了国内IP不走内核 192.168.0.0/16那些局域网地址不起作用

**Comment by vernesong** [comment]
应该不会回环了才对
你设置日志格式为debug，然后手动运行
/etc/init.d/openclash stop
再到/tmp/openclash.log看看日志

**Comment by lovehuiping** [comment]
> 应该不会回环了才对 你设置日志格式为debug，然后手动运行 /etc/init.d/openclash stop 再到/tmp/openclash.log看看日志

你好大佬,已经急于恢复网络 下次有遇到再贴debug log了 已经降回103版本跟DEV内核v1.13.0-6-g71f8f06(电脑存档).现在已经恢复正常了

就是103升上来啥都没有动配置文件
升完1.15内核跟110版本就出现一个104的客户端,我局域网里没有这台机器 连接99+ 网络卡死

**Comment by xxf19900504** [comment]
Yacd 控制面板和Dashboard 控制面板无法打开，求助。

**Comment by dycwuxing** [comment]
> /etc/init.d/openclash stop

我升级了111,先退回103了
stop以后的日志的最后几行大概是这样
<img width="1191" alt="image" src="https://user-images.githubusercontent.com/44988562/232291481-e7da903a-db41-4076-92b8-ca3dba167293.png">
之前的那个DNS发起的链接是下图,目标IP是我当前的公网IP
![telegram-cloud-photo-size-5-6188178448057479611-y](https://user-images.githubusercontent.com/44988562/232291522-c8cfc562-1f40-4833-be99-38cd528826be.jpg)
我主要的运行模式是OC(redir增强模式)+ADH(oc正常设置DNS,ADH的上游是127.0.0.1:7874)

**Comment by dycwuxing** [comment]
我的DNS部分:
dns:
  enable: true
  ipv6: true
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874
  nameserver:
  - https://doh.360.cn/dns-query
  - https://doh.pub/dns-query
  - https://dns.google/dns-query
  - https://1.1.1.1/dns-query
  - https://doh.opendns.com/dns-query
  - https://doh.dns.apple.com/dns-query
  - https://doh.dns.sb/dns-query
  fallback:
  - https://dns.google/dns-query
  - https://1.1.1.1/dns-query
  - https://doh.opendns.com/dns-query
  - https://doh.dns.apple.com/dns-query
  - https://doh.dns.sb/dns-query
  proxy-server-nameserver:
  - https://dns.google/dns-query
  - https://1.1.1.1/dns-query
  - https://doh.opendns.com/dns-query
  - https://doh.dns.apple.com/dns-query
  - https://doh.dns.sb/dns-query
  default-nameserver:
  - 8.8.8.8
  - 8.8.4.4
  - 1.1.1.1

**Comment by kiligone** [comment]
我也是这样。udp连接会出现这样的情况，目标地址本机wanip，来源地址是要连接的地址，感觉是把目标地址和来源地址给调换了
