### ISSUE TITLE
[Bug] R2S 【TUN】版本内核更新失败，请检查网络或稍后再试

### ISSUE THREAD

**Issue by qianzhangxa** [vernesong/OpenClash#3192]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.78-226

### Bug on Environment

Other

### Bug on Platform

Linux-arm64

### To Reproduce

在切换到一个我大概有一周没有用的订阅时出现了这个问题，但另外一个订阅就没有这个问题。

### Describe the Bug

切换订阅时出现如下错误：
【TUN】版本内核更新失败，请检查网络或稍后再试！

### OpenClash Log

```
2023-04-15 22:49:13 【TUN】版本内核更新失败，请检查网络或稍后再试！
2023-04-15 22:49:09 【TUN】版本内核正在下载，如下载失败请尝试手动下载并上传...
2023-04-15 22:49:07 提示：检测到内核文件不存在，准备开始下载...
2023-04-15 22:49:07 第二步: 组件运行前检查...
2023-04-15 22:49:07 第一步: 获取配置...
2023-04-15 22:49:07 OpenClash 开始启动...
```

### Expected Behavior

能够在切换订阅后成功启动。

### Screenshots

点了“检查并更新”后还是一样的错。

![image](https://user-images.githubusercontent.com/16984932/232233898-1b76c0df-09ca-4b26-8baf-cf063b37d8cf.png)

**Comment by lifetyper** [comment]
不是写了"文件迁移,请更新插件"吗？新版本检查地址都变了，你这个老版本当然更新不了。

**Comment by qianzhangxa** [comment]
谢谢 @lifetyper！

请问如何更新插件呢？是指更新客户端版本吗？另外，为什么我的另外一个订阅就没有这个问题？

**Comment by lifetyper** [comment]
更新客户端版本
你另一个订阅能更新成功这才是奇怪的事情

**Comment by qianzhangxa** [comment]
刚试了一下“检查并更新”客户端，但也出错了，请问如何手动更新呢？

【OpenClash - v0.45.103-beta】更新前测试失败，文件保存在 /tmp/openclash.ipk，请尝试手动更新！

**Comment by lifetyper** [comment]
更新前测试失败可能openwrt缺依赖吧，或者网络下载过程中出错了，自己下载后上传到路由器上opkg -i安装试试看好了。
https://github.com/vernesong/OpenClash/releases/download/v0.45.103-beta/luci-app-openclash_0.45.103-beta_all.ipk

**Comment by qianzhangxa** [comment]
> 更新前测试失败可能openwrt缺依赖吧，或者网络下载过程中出错了，自己下载后上传到路由器上opkg -i安装试试看好了。 https://github.com/vernesong/OpenClash/releases/download/v0.45.103-beta/luci-app-openclash_0.45.103-beta_all.ipk

已经搞定了，非常感谢 @lifetyper ！
