### ISSUE TITLE
[Improvement] Fake-IP模式+接管路由器自身流量情况下，OpenClash启动时给dnsmsq添加一个localuse=1的设置

### ISSUE THREAD

**Issue by lifetyper** [vernesong/OpenClash#3195]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

原因是来自这个(https://github.com/vernesong/OpenClash/issues/2791) ,在启用了fake-ip的情况下，openclash代理路由器自身流量时依然会遭遇dns污染的情况。

root cause是路由器的/etc/resolv.conf决定了自身dns，openclash启动后这个文件里没有使用dnsmasq作为system resolver，虽然路由器下挂的客户端走fake-ip了(dnsmasq依然正常给lan提供了服务)，但路由器本身没有使用dnsmasq的fake-ip。

### Describe the Solution

大概推理顺序是这样的:
1.要让路由器也完整的走fake-ip，就要让/etc/resolv.conf使用nameserver 127.0.0.1(dnsmasq--openclash 127.0.0.1:7874)，即dnsmsq作为system resolver。

2.要让dnsmasq把自己设置为system resolver，就需要设置dnsmasq的localuse=1,localuse这个默认值是0的。

3.正常没有openclash的情况下，dnsmasq如果检测到noresolve=0（默认值），就会把localuse设置为1，并把自己作为system resolver,所以没有openclash的时候dnsmasq确实是作为system resolver的。

4.但是openclash启动的时候会好像给dnsmasq添加一个noresolv选项，这个当然是没问题的，因为要避免dnsmasq使用其他被污染的dns源。
```
      uci -q delete dhcp.@dnsmasq[0].resolvfile
      uci -q set dhcp.@dnsmasq[0].noresolv=1
      uci -q set openclash.config.redirect_dns=1
```
按照/etc/init.d/dnsmasq中的代码，这也就导致了dnsmsq不会把localuse设置为1，继而导致不会把自己接管为system resolver。
```
if [ "$noresolv" != "1" ]; then
                config_get resolvfile "$cfg" resolvfile /tmp/resolv.conf.d/resolv.conf.auto
                [ -n "$resolvfile" ] && [ ! -e "$resolvfile" ] && touch "$resolvfile"
                xappend "--resolv-file=$resolvfile"
                [ "$resolvfile" = "/tmp/resolv.conf.d/resolv.conf.auto" ] && localuse=1
                resolvdir="$(dirname "$resolvfile")"
        fi
```
5.参考openwrt官方[设置文档](https://openwrt.org/docs/guide-user/base-system/dhcp_configuration#enforcing_dnsmasq_for_local_system),我们其实是可以在启用noresolv的情况下，手工设置localuse为1的。
```
uci set dhcp.@dnsmasq[0].localuse="1"
uci commit dhcp
/etc/init.d/dnsmasq restart
```
7.实测这样操作之后，/etc/resolv.conf里的nameserver就是127.0.0.1了，走fake-ip后路由器自身流量也就没有dns污染的问题了。

所以我建议，如果检测到用户开启了fake-ip模式和代理路由器自身流量(或者其他需要openclash接管路由器system resolver的设置)，那么openclash在启动时，除了设置一下dnsmasq的转发到7874和添加noresolv选项外，也添加一个localuse设置值，让dnsmasq作为路由器的system resolver，避免dns污染问题。

### Additional Context
其实有这个问题的用户也可以自己手工设置一下dnsmasq的localuse选项，不过我觉得默认启用的localuse其实是在openclash添加noreolv之后失效的，而且确实引发了问题，那么最好是让openclash同时设置noresolv和localuse。
_No response_

**Comment by vernesong** [comment]
好像2203才有这个毛病

**Comment by gemnioo** [comment]
@vernesong   请教 按照此处的 localuse=1 设置. 启动OpenClash 会使得 /etc/resolv.conf 文件下被覆写成 如下.  

```
root@device:~# cat /etc/resolv.conf
search lan
nameserver 127.0.0.1
nameserver ::1
```
请问如果我想做到和 Tailscale MagicDNS 兼容 但采用 "tailscale set --accept-dns=false" 方案,  除了设置OpenClash >- 插件设置 >- DNS设置 >- 勾选 启用第二 DNS 服务器 >- 并在指定服务器填入 “100.100.100.100” >- 下方列表中域名填入 “tailnetname.ts.net"  

即等效为：
```
# /etc/dnsmasq.conf
server=/tailnetname.ts.nett/100.100.100.100
```

除此之外还在在 OpenClash 成功启动后修改 /etc/resolv.conf 为
```
# /etc/resolv.conf
nameserver 127.0.0.1
nameserver ::1
search lan tailnetname.ts.net
```
此时 query an unqualified hostname 等同于 --accept-dns=true
```
DNS Query "myhost" → resolv.conf 
                     ↓
1. Try "myhost.lan" → 127.0.0.1 (dnsmasq)
                     ↓ (if not found)
2. Try "myhost.tailnetname.ts.net" → 127.0.0.1 (dnsmasq)
                     ↓
                     dnsmasq sees "*.tailnetname.ts.net"
                     ↓
                     forwards to 100.100.100.100 (Tailscale DNS)
```
请问可以在 OpenClash >- 插件设置 >- 开发者选项中填入以下脚本么？

**Comment by vernesong** [comment]
```
nameserver-policy:
    "+.tailnetname.ts.net": 100.100.100.100

**Comment by gemnioo** [comment]
> ```
> nameserver-policy:
>     "+.tailnetname.ts.net": 100.100.100.100
> ```

A/B TEST:
```
设置OpenClash >- 插件设置 >- DNS设置 >- 勾选 启用第二 DNS 服务器 >- 并在指定服务器填入 “100.100.100.100” >- 下方列表中域名填入 “tailnetname.ts.net"

以及 mihomo.config 中添加：
nameserver-policy:
    "+.tailnetname.ts.net": 100.100.100.100
```
都无法成功 query an unqualified hostname via nslookup. 查看 cat /etc/dnsmasq.conf 并没有被写入任何第二DNS服务器规则.

按照我的理解  此时的DNS 查询逻辑理应是: (是冗余的.. Tailscale --accpet-dns=true 就插入置顶 resolv.conf

```
DNS Query "myhost" → resolv.conf 
                     ↓
1. Try "myhost.lan" → 127.0.0.1 (dnsmasq)
                     ↓ (if not found)
2. Try "myhost.tailnetname.ts.net" → 127.0.0.1 (dnsmasq) \\port:53 → dnsmasq sees "*.tailnetname.ts.net" → forwards to 100.100.100.100 (Tailscale DNS)
                     ↓ (if not found)
                     OpenClash nameserver-policy "+.tailnetname.ts.net" \\port: 7974 upstream of Dnsmasq
                     ↓
                     forwards to 100.100.100.100 (Tailscale DNS)

**Comment by gemnioo** [comment]
op  [实验性：不使用Dnsmasq绕过中国大陆IP](https://www.dolingou.com/article/experimental-bypass-china-ip-without-dnsmasq-mihomo)  是通过:
```
China_ip_route_pass这个IP集是通过劫持Dnsmasq，使用设定的 DNS 对国内常见域名（也就是/etc/openclash/accelerated-domains.china.conf 文件内域名）进行解析并生成的IP集。这部分非常依赖于Dnsmasq
``` 
应该是这个原因导致 “ /etc/dnsmasq.conf 并没有被写入任何第二DNS服务器规则 吗？”

**Comment by vernesong** [comment]
没必要搞这么多事情，你开了劫持DNS就是clash去解析，写了policy给100.100.100.100就行了

**Comment by gemnioo** [comment]
> 没必要搞这么多事情，你开了劫持DNS就是clash去解析，写了policy给100.100.100.100就行了

没用启用 第二 DNS 服务器. 加了 mihomo.conf "nameserver-policy:     " 看起来没成功啊~

```
root@N1:~# cat /etc/resolv.conf
search lan
nameserver 127.0.0.1
nameserver ::1
root@N1:~# ping claw-hk
ping: bad address 'claw-hk'
root@N1:~# nslookup claw-hk
Server:		127.0.0.1
Address:	127.0.0.1:53

** server can't find claw-hk.lan: NXDOMAIN

** server can't find claw-hk.lan: NXDOMAIN
```
