### ISSUE TITLE
关于备份问题

### ISSUE THREAD

**Issue by Wyatt323** [vernesong/OpenClash#3196]
点击版本更新页面的 备份openclash 和 配置管理页面的 备份 都没生成下载文件

已经浏览过历史issue,没找到解决办法，不知道这个备份文件是生成在哪里了

**Comment by ghost** [comment]
需要修改openclash管理页面url才能触发下载  ：（
除了内核都备份：“admin/services/openclash/backup_ex_core” 
所有都备份：“admin/services/openclash/backup”
