### ISSUE TITLE
[Bug] 110和111 一些国外域名都无法解析回退103就全部正常了。

### ISSUE THREAD

**Issue by gzw13999** [vernesong/OpenClash#3199]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.111-bata

### Bug on Environment

Lean

### Bug on Platform

Linux-arm64

### To Reproduce

升级v0.45.110-bata和v0.45.111-bata版本

### Describe the Bug

使用以上两个版本 nslookup 国外域名都会超时 

### OpenClash Log

无需日志

### Expected Behavior

正常可访问

**Comment by cqjerry** [comment]
遇到同样问题，升级至112问题仍然存在。
