### ISSUE TITLE
能不能添加一个Newifi3（MediaTek MT7621 mipsel_24kc）可用的内核，谢谢！

### ISSUE THREAD

**Issue by doreencheng** [vernesong/OpenClash#32]
能不能添加一个Newifi3（MediaTek MT7621 mipsel_24kc）可用的内核，谢谢！

**Comment by Love4Taylor** [comment]
就 linux-mipsle-softfloat 啊. 如果编译的时候有开 FPU 模拟就 linux-mipsle-hardfloat.

**Comment by doreencheng** [comment]
> 就 linux-mipsle-softfloat 啊. 如果编译的时候有开 FPU 模拟就 linux-mipsle-hardfloat.

感谢！又试了一下，可以了，可能那天晚上网络问题，内核一直没下载成功！
