### ISSUE TITLE
openclash设置界面丢失

### ISSUE THREAD

**Issue by kmoc** [vernesong/OpenClash#320]
随固件编译
版本号OpenWrt SNAPSHOT r12903
发现设置界面全部丢失

<img width="1152" alt="无标题" src="https://user-images.githubusercontent.com/32633913/79044374-62272700-7c37-11ea-9aab-f815767c0708.png">
<img width="1152" alt="无标题2" src="https://user-images.githubusercontent.com/32633913/79044375-63f0ea80-7c37-11ea-97be-40915c9c333f.png">
<img width="725" alt="无标题3" src="https://user-images.githubusercontent.com/32633913/79044376-63f0ea80-7c37-11ea-939e-6d5e0ed133c2.png">

**Comment by 1715173329** [comment]
Due to commit https://github.com/openwrt/luci/commit/c099344013ad72d01a93b99184c72c5eeb792174, every LuCI app must register a ACL rule to control the config.
You may simply revert the commit to make everything works as usual.

**Comment by kmoc** [comment]
感谢，自己编了luci-app-openclash.json文件，上传后，一切正常
[luci-app-openclash.zip](https://github.com/vernesong/OpenClash/files/4471350/luci-app-openclash.zip)
下载 luci-app-openclash.zip 后解压到/usr/share/rpcd/acl.d文件夹并 chmod 0664给予权限
<img width="734" alt="批注 2020-04-14 031707" src="https://user-images.githubusercontent.com/32633913/79152256-7406f680-7dfe-11ea-94f8-fab3d903dbf2.png">
