### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by bulzed** [vernesong/OpenClash#3201]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.111-bata

### Bug on Environment

ImmortalWrt

### Bug on Platform

Linux-arm64

### To Reproduce

.

### Describe the Bug

unable to access hilink modem webui (192.168.8.1) when openclash running

### OpenClash Log

.

### Expected Behavior

same as v0.45.103-beta

**Comment by remedynotavailable** [comment]
Many problem after 103.
This is the different in nft
```diff
 	chain openclash_mangle {
@@ -197,10 +197,11 @@
 		meta nfproto ipv4 udp sport 68 counter packets 0 bytes 0 return
-		meta l4proto { tcp, udp } iifname "utun" counter packets 4854 bytes 3540612 return
-		ip daddr @localnetwork counter packets 10386 bytes 5358167 return
-		ip protocol udp counter packets 114 bytes 41258 jump openclash_upnp
-		meta l4proto { tcp, udp } th dport 0-65535 meta mark set 0x00000162
+		meta l4proto { tcp, udp } iifname "utun" counter packets 1653 bytes 1532469 return
+		iifname "lo" ip daddr @localnetwork counter packets 159 bytes 24026 return
+		iifname "br-lan" ip daddr @localnetwork counter packets 1196 bytes 104821 return
+		ip protocol udp counter packets 331 bytes 104062 jump openclash_upnp
+		meta l4proto { tcp, udp } th dport 0-65535 meta mark set 0x00000162 counter packets 3776 bytes 2183516
 	}
 
 	chain openclash_dns_hijack {

```
