### ISSUE TITLE
[Bug] meta内核下开启域名嗅探，米家设备离线

### ISSUE THREAD

**Issue by jeffreymor** [vernesong/OpenClash#3202]
### Verify Steps

- [x] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [x] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.112-beta

### Bug on Environment

Lean

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

使用meta内核，开启域名嗅探，并且打开自定义嗅探忽略设置，已经添加以下米家相关sni进行忽略
  - 'Mijia Cloud'
  - 'dlg.io.mi.com'

### Describe the Bug

米家设备无法联网，且之前很长一段时间开启同样设置（开启域名嗅探并且有忽略mijia cloud）是没有出现问题的，现在日志就一直报
Sniff TCP [*:55812]-->[Mijia Cloud:443] success, replace domain [Mijia Cloud]-->[Mijia Cloud]
Mijia Cloud:443 error: dns resolve failed: couldn't find ip

### OpenClash Log

无

### Expected Behavior

使用meta内核，正确配置自定义嗅探的情况下，米家设备不应出现离线

**Comment by ym2008** [comment]
遇到了同样的问题

**Comment by vernesong** [comment]
看一下配置文件有没有写进去

**Comment by Winhauls** [comment]
家里的小米智能门铃3也连不上了

**Comment by jeffreymor** [comment]
> 看一下配置文件有没有写进去

有的，确认过很多次，对着meta的wiki看过没问题，我昨天重置过后重新配置了一遍，开嗅探就出问题了

**Comment by jeffreymor** [comment]
> > > 看一下配置文件有没有写进去
> > 
> > 
> > 有的，确认过很多次，对着meta的wiki看过没问题，我昨天重置过后重新配置了一遍，开嗅探就出问题了
> 
> 请问怎么解决的呢，我也有这个问题，配置也是写了的（现在默认配置就有米家）。

当时是偶发的，出现后过几天就好了，然后也有复现过，再后来因为别的原因没用meta内核了

**Comment by bhujlnkj** [comment]
关闭edge浏览器的安全dns

**Comment by liyunlong5** [comment]
- 'mijia cloud'
- 'dlg.io.mi.com'
- 使用小写来匹配尝试一下

**Comment by iKira** [comment]
根治了，看这里：
https://github.com/MetaCubeX/mihomo/discussions/1994#discussioncomment-12990182
