### ISSUE TITLE
升级之后，有反向“升”级的申请显示

### ISSUE THREAD

**Issue by jacobin** [vernesong/OpenClash#3203]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.112

### Bug on Environment

Other

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

插件设置 --> 版本更新 --> 一键检查更新，失败，不得不进行手工升级：
    1. 覆写/etc/openclash/core;
    2. opkg  install  --force-depends  "luci-app-openclash_0.45.112-beta_all.ipk"
    3. 重新设置配置openclash
   到这一步，看起来都已经更新完毕，信息显示也是对的。但是偶尔就会出现如图中的狗屁倒灶的情形，奇怪

### Describe the Bug

要升级到的版本，比本地版本，还小

### OpenClash Log

没有攫取下来

### OpenClash Config

```shell
没有记录下来
```

### Expected Behavior

右边圆圈的版本号大于或者等于左边本地版本号

### Screenshots

![Untitled](https://user-images.githubusercontent.com/5020373/232711404-1ff6452e-246f-4e5f-9074-abf7f8ec46a0.png)

**Comment by AoThen** [comment]
我是这玩意...也是有点摸不着头脑.
![image](https://user-images.githubusercontent.com/32790381/232942238-24077200-c30a-457f-b942-65c3951e3e70.png)

**Comment by vernesong** [comment]
因为还有一个osdn的地址，跟github同步不一致的时候就会这样

**Comment by vernesong** [comment]
> > 我是这玩意...也是有点摸不着头脑. ![image](https://user-images.githubusercontent.com/32790381/232942238-24077200-c30a-457f-b942-65c3951e3e70.png)
> > 同样的情况

更新插件解决

**Comment by Wyatt323** [comment]
> > > 我是这玩意...也是有点摸不着头脑. ![image](https://user-images.githubusercontent.com/32790381/232942238-24077200-c30a-457f-b942-65c3951e3e70.png)
> > > 同样的情况
> 
> 更新插件解决

解决了

**Comment by jacobin** [comment]
没有解决，就在刚才，我把clash从v15.0升级到几分钟前发布出来的V15.1，然后又见这个现象
![Snap11](https://user-images.githubusercontent.com/5020373/233456599-2ed9f0f2-c10f-448c-b029-9b2593f57e20.jpg)

**Comment by jacobin** [comment]
没有解决。就在刚才，我把clash从v15.0升级到几分钟前发布出来的V15.1，然后又见这个现象
![Snap11](https://user-images.githubusercontent.com/5020373/233456883-c9593621-eff3-42f3-aa38-569f85f62913.jpg)

**Comment by caliban511** [comment]
一样遇到，而且在meta和dev之间切换使用时还会遇到来回“升级”的情况，，，

**Comment by jacobin** [comment]
![Snap9](https://github.com/vernesong/OpenClash/assets/5020373/ef6d25b4-a5bb-4c81-9807-aef2d048861d)
