### ISSUE TITLE
[Bug] Cortex-A53架构TUN不可用

### ISSUE THREAD

**Issue by LaplaceTor** [vernesong/OpenClash#3206]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.112-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-arm64

### To Reproduce

Cortex-A53架构使用tun模式

### Describe the Bug

原以为是内核有问题，更换为shell的clash后正常打开TUN并使用

### OpenClash Log

在系统日志中可以看到modprobe 提示tun not found ，然后clash调试日志中则是operation not permitted（kmod-tun已确认存在）

### Expected Behavior

正常使用TUN

### Screenshots

![屏幕截图 2023-04-18 233231](https://user-images.githubusercontent.com/28674126/232829189-b08897e8-d2c3-4efd-b294-d1c851da72a1.png)
正常打开tun
![屏幕截图 2023-04-18 235432](https://user-images.githubusercontent.com/28674126/232834093-373ff043-a324-42c5-a4f8-04e32dae70b5.png)
打开前
![屏幕截图 2023-04-18 235326](https://user-images.githubusercontent.com/28674126/232834183-2587d8fc-cf6e-483b-bf91-d4defad03fe7.png)
打开后

**Comment by vernesong** [comment]
应该是libcap的问题，建议换固件

**Comment by LaplaceTor** [comment]
> 应该是libcap的问题，建议换固件

A53架构的机器相关issue有好几个，你基本只回答固件有问题，能不能来点新的回答？

openclash连tun网卡都没有成功创建

**Comment by LaplaceTor** [comment]
> 感觉这个加入了ruby后，a53架构连ruby都装不了，难受

装不了你的问题，或者你的源有问题

**Comment by vernesong** [comment]
因为我的A53设备是正常的，虽然用的是1806

**Comment by ilaipi** [comment]
我这边也一样，都更新到最新版启动不了tun，期待下个版本能解决

![image](https://github.com/vernesong/OpenClash/assets/1689135/204001fb-aab8-424e-a9d8-4420721edadc)
