### ISSUE TITLE
[Enhancement] 默认的DNS服务器不要再用114.114.114.114了吧

### ISSUE THREAD

**Issue by WFANG12719** [vernesong/OpenClash#3208]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

建议：
目前openclash脚本里很多DNS服务器配置项默认如果用户不自己个性化配置，就用114.114.114.114代替。其实114.114.114.114南京信风提供的服务节点在全国范围内落地很有限，仅在南京和济南附近有节点，其它地方基本没有。建议可以改成阿里的或腾讯的公共DNS IP地址：119.28.28.28 ，223.5.5.5。这两个公共DNS比较稳定，另外在全国人口密集的地区都有落地，本地延时非常小，每次 DNS查询可以就近解决，不需要跑到南京或济南去。

### Describe the Solution

把openclash脚本和配置文件里的114.114.114.114 替换成223.5.5.5/119.28.28.28。

**Comment by rsgdn** [comment]
一般默认解析国内的Dns不是运营商下发的或者就是阿里腾讯云这两个
