### ISSUE TITLE
今天使用最新源码编译的版本，配置文件订阅一直提示下载失败

### ISSUE THREAD

**Issue by sypopo** [vernesong/OpenClash#321]
今天使用最新源码编译的版本，配置文件订阅一直提示下载失败。昨天之前编译的正常

**Comment by vernesong** [comment]
稍后修复

**Comment by mymld2020** [comment]
2020-04-14 20:59:38 OpenClash 【Dev】 Core Update Error
2020-04-14 20:59:49 OpenClash 【Tun】 Core Update Error
订阅也是总是更新不了，你家隔壁的那个1.68的可以更新订阅，可以更新检测检查，但是用不习惯，还是喜欢用你这个，但是就是无法更新订阅111····

**Comment by vernesong** [comment]
你这是更新内核，节点没问题的话启动后会自己挂代理下载
