### ISSUE TITLE
[Feature] clash fake ip 模式下，怎么通过特殊手获取真实ip

### ISSUE THREAD

**Issue by coppea** [vernesong/OpenClash#3211]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

无法通过特殊手段或者特殊命令获取域名的真实ip

### Describe the Solution

因为有需求获取域名的真实ip，是否有特殊命令能够获取域名的真实ip？

**Comment by lifetyper** [comment]
你猜fake-ip-filter是干什么用的

**Comment by coppea** [comment]
> 你猜fake-ip-filter是干什么用的

我知道这个配置功能，他适合自定义域名，我想查询非自定义域名，如查询xxx.com的ip，这个xxx不确定，我使用dig，nslookup，host返回都是198.x.x.x

**Comment by lifetyper** [comment]
自建一个dns，或者ssh到服务器上dig，或者用各种web版的nslookup工具

**Comment by coppea** [comment]
我使用的是popclip的getip插件，https://github.com/pilotmoon/PopClip-Extensions/blob/master/extensions/GetIP.popclipextz
因fake-ip模式就失效了

**Comment by coppea** [comment]
> 在局域网自建一个dns，或者ssh到服务器上dig，或者用各种web版的nslookup工具。

感谢

**Comment by luweijun1992** [comment]
自建mosdns：国内域名使用国内dns解析；国外域名使用clash解析。

**Comment by coppea** [comment]
> 自建mosdns：国内域名使用国内dns解析；国外域名使用clash解析。

fake-ip模式下可以用吗，我看网上教程适用于redir-host模式

**Comment by luweijun1992** [comment]
> > 自建mosdns：国内域名使用国内dns解析；国外域名使用clash解析。
> 
> fake-ip模式下可以用吗，我看网上教程适用于redir-host模式

直接看截图效果把，你应该跟我类似；国内域名还是需要解析到正确IP，但是国外的无所谓。
![image](https://github.com/vernesong/OpenClash/assets/58923704/68e855aa-4edb-40fc-99d2-875503f8b5da)

**Comment by kk88y** [comment]
> 

请问是怎样操作的呢

**Comment by kk88y** [comment]
> > > 自建mosdns：国内域名使用国内dns解析；国外域名使用clash解析。
> > 
> > 
> > fake-ip模式下可以用吗，我看网上教程适合使用于redir-host模式
> 
> 直接看截图效果把，你应该跟我似的；国内名称还是需要解析到正确的IP，但是国外的无所谓。 ![图像](https://user-images.githubusercontent.com/58923704/237849443-68e855aa-4edb-40fc-99d2-875503f8b5da.png)

请问是怎样操作的呢，谢谢

**Comment by luweijun1992** [comment]
> > > > 自建mosdns：国内域名使用国内dns解析；国外域名使用clash解析。
> > > 
> > > 
> > > fake-ip模式下可以用吗，我看网上教程适合使用于redir-host模式
> > 
> > 
> > 直接看截图效果把，你应该跟我似的；国内名称还是需要解析到正确的IP，但是国外的无所谓。 ![图像](https://user-images.githubusercontent.com/58923704/237849443-68e855aa-4edb-40fc-99d2-875503f8b5da.png)
> 
> 请问是怎样操作的呢，谢谢

终端使用mosdns作为dns服务器，mosdns收到dns请求后判断这个域名。
如果是国内域名就使用几个共用dns，比如阿里：223.5.5.5；腾讯：119.29.29.29；
如果是国外域名就是用OpenWrt上的OpenClash进行解析，拿到FakeIP（192.18.0.0/16）；
基于以上就可以进行dns的分流，国内域名还是拿到正确IP，国外假IP。

我在想如果国外域名我i直接使用国外的dns服务器进行解析，就能拿到正确IP地址，但是后续流量转发到OpenClash的时候不知道会不会被转发出去，有待研究。
