### ISSUE TITLE
openclash开启fake-ip后阻止win10网络检测，导致部分网络无访问权限，右下角网络图标黄色感叹号

### ISSUE THREAD

**Issue by hatbhtbh** [vernesong/OpenClash#3215]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

lede源码编译openwrt ，Linux-amd64(x86-64)，   openclash版本v0.45.112-beta   

openclash开启fake-ip增强模式后win10电脑有线连接软路由IPv4无网络访问权限，右下角网络图标黄色感叹号，但是还能上网；
openclash开启redir-host兼容模式一切正常；电脑IPv4正常连接网络，右下角黄色感叹号消失；
关闭openclash也一切正常，电脑IPv4正常连接网络，右下角黄色感叹号消失；
我上网查了一下原因是openclash在开启fake-ip增强模式后阻止了win10网络检测地址所致
下面附上部分调试日志，请各位大神看看什么原因？
![R5%@YOILUBQ8M4@J8VU)_OA](https://user-images.githubusercontent.com/93958708/233289741-e4bad4b4-f3bb-4cea-958e-1ecc7786ae70.png)
![J7YQ7R8V5V_H~0WLS% HF0D](https://user-images.githubusercontent.com/93958708/233289757-73f7bb08-a254-4d0c-b90f-5b6bff0c61cd.png)

开启redir-host兼容模式：

OpenClash 调试日志

生成时间: 2023-04-20 14:52:40
插件版本: v0.45.112-beta
隐私提示: 上传此日志前请注意检查、屏蔽公网IP、节点、密码等相关敏感信息

```

#===================== 系统信息 =====================#

主机型号: Default string Default string/Default string - Intel(R) Celeron(R) J4125 CPU @ 2.00GHz : 4C4T
固件版本: OpenWrt SNAPSHOT r5900-4bba40608
LuCI版本: git-23.104.57901-bf5e9ad-1
内核版本: 5.15.104
处理器架构: x86_64

#此项有值时,如不使用IPv6,建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: 

DNS劫持: Dnsmasq 转发
#DNS劫持为Dnsmasq时，此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 127.0.0.1#7874

#===================== 依赖检查 =====================#

dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
libcap: 已安装
libcap-bin: 未安装
ruby: 已安装
ruby-yaml: 已安装
ruby-psych: 已安装
ruby-pstore: 已安装
kmod-tun(TUN模式): 已安装
luci-compat(Luci >= 19.07): 已安装
kmod-inet-diag(PROCESS-NAME): 已安装
unzip: 已安装
iptables-mod-tproxy: 已安装
kmod-ipt-tproxy: 已安装
iptables-mod-extra: 已安装
kmod-ipt-extra: 已安装
kmod-ipt-nat: 已安装

#===================== 内核检查 =====================#

运行状态: 运行中
运行内核：Dev
进程pid: 19571
运行权限: 19571: cap_dac_override,cap_net_bind_service,cap_net_admin,cap_net_raw,cap_sys_ptrace,cap_sys_resource=eip
运行用户: nobody
已选择的架构: linux-amd64

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 2023.04.13-1-ge15ba70
Tun内核文件: 存在
Tun内核运行权限: 正常

Dev内核版本: v1.15.0
Dev内核文件: 存在
Dev内核运行权限: 正常

Meta内核版本: alpha-g8e5dbc7
Meta内核文件: 存在
Meta内核运行权限: 正常

开启fake-ip增强模式：
OpenClash 调试日志

生成时间: 2023-04-20 14:40:27
插件版本: v0.45.112-beta
隐私提示: 上传此日志前请注意检查、屏蔽公网IP、节点、密码等相关敏感信息

```

#===================== 系统信息 =====================#

主机型号: Default string Default string/Default string - Intel(R) Celeron(R) J4125 CPU @ 2.00GHz : 4C4T
固件版本: OpenWrt SNAPSHOT r5900-4bba40608
LuCI版本: git-23.104.57901-bf5e9ad-1
内核版本: 5.15.104
处理器架构: x86_64

#此项有值时,如不使用IPv6,建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: 

DNS劫持: Dnsmasq 转发
#DNS劫持为Dnsmasq时，此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 127.0.0.1#7874

#===================== 依赖检查 =====================#

dnsmasq-full: 未安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
libcap: 已安装
libcap-bin: 已安装
ruby: 已安装
ruby-yaml: 已安装
ruby-psych: 已安装
ruby-pstore: 已安装
kmod-tun(TUN模式): 已安装
luci-compat(Luci >= 19.07): 已安装
kmod-inet-diag(PROCESS-NAME): 已安装
unzip: 已安装
iptables-mod-tproxy: 已安装
kmod-ipt-tproxy: 已安装
iptables-mod-extra: 已安装
kmod-ipt-extra: 已安装
kmod-ipt-nat: 已安装

#===================== 内核检查 =====================#

运行状态: 运行中
运行内核：Dev
进程pid: 30114
运行权限: 30114: cap_dac_override,cap_net_bind_service,cap_net_admin,cap_net_raw,cap_sys_ptrace,cap_sys_resource=eip
运行用户: nobody
已选择的架构: linux-amd64

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 2023.04.13-1-ge15ba70
Tun内核文件: 存在
Tun内核运行权限: 正常

Dev内核版本: v1.15.0
Dev内核文件: 存在
Dev内核运行权限: 正常

Meta内核版本: alpha-g8e5dbc7
Meta内核文件: 存在
Meta内核运行权限: 正常

**Comment by vernesong** [comment]
试试
![image](https://user-images.githubusercontent.com/42875168/233297411-973b65ed-2116-432c-bb12-6e535095f2d6.png)

**Comment by hatbhtbh** [comment]
> 试试 ![图像](https://user-images.githubusercontent.com/42875168/233297411-973b65ed-2116-432c-bb12-6e535095f2d6.png)

我按照上面截图在fake-ip增强模式下添加了上图中的3,4,5条命令后测试了一下，
重启软路由，电脑重启后正常（win10系统有线连接J4125软路由），
电脑睡眠后启动后又恢复ipv4无网络访问权限，右下角网络图标黄色感叹号
睡眠后启动然后再重启有时候恢复正常，不确定，
无网络访问权限的时候虽然能上网，我发现微软自家的便笺 （无法同步）
请大神在修复一下，谢谢！
![TI6P61B6425HT Q3@1OC65R](https://user-images.githubusercontent.com/93958708/233347242-ea6ea0e3-5963-41c1-88f7-667cad087288.png)
![@8$S7_EE(%@MRTTR4ZM3Z6G](https://user-images.githubusercontent.com/93958708/233347260-2d7ef627-aacc-4272-bf4b-058f1f29810e.png)
![FJ%I5B9WT5HPGG1NXB 3Z1W](https://user-images.githubusercontent.com/93958708/233347272-201a4c37-503f-413b-86c9-4412ed765501.png)

**Comment by vernesong** [comment]
那你直接去百度修改系统的检测地址吧，这个插件没好办法解决

**Comment by hatbhtbh** [comment]
> 那你直接去百度修改系统的检测地址吧，这个插件没好办法解决

好的

**Comment by hatbhtbh** [comment]
> 那你直接去百度修改系统的检测地址吧，这个插件没办法解决

我昨晚百度搜索了一晚上资料再测试获得一些方法如下（做个记录）：
1：禁用win10注册表EnableActiveProbing 的值从1改为0,重启正常。
2：openclash使用默认的redir-host兼容模式
3：关闭openclash,使用其它插件替换
4：烦请开发者在openclash的fake-ip增强模式下放行win10系统探测网址的域名

下面是方法一整理的的详细信息和网站地址：
1.按 Win+R 热键以调出 Windows 的“运行”对话框。在“运行”对话框中，键入 regedit 并按 Enter 键。这将打开Windows注册表编辑器。

2.在 Windows 注册表编辑器窗口中，导航到
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\NlaSvc\Parameters\Internet

3.找到名为 EnableActiveProbing 的值，双击它并将其值从 1 更改为 0。

4.关闭 Windows 注册表编辑器。尝试重新连接到互联网（通过重新插入以太网电缆或重新启动路由器）。现在Windows将不再探测Microsoft NCSI服务器。


![disable-network-probing-windows-0](https://user-images.githubusercontent.com/93958708/233513178-e3ac2119-359a-46f6-b765-9468d8c46541.jpg)

下面两段话是我从网上拷贝下来的看一下原理：

1.win10右下角显示黄色感叹号，以太网IPv4显示无Internet访问权限，但实际可以上网，但win10系统自带的便笺等无法同步显示离线，随手ping了下www.msftconnecttest.com，发现已经ping不通了，看来是被openclash:fake-ip增强模式下屏蔽了（我的就是这个情况，已有其它原因自己测试）。win10系统有个NSCI机制，就是用来探测系统的网络环境，是否真的连上网。这个机制的缺点就是如果探测网址被单点屏蔽，那么这个机制就歇菜了。

2.当您通过 LAN 电缆或 WiFi 适配器将 Windows PC 连接到任何网络时，它会显示该网络是否具有有效的互联网连接。如果计算机能够通过其连接的现有网络访问 Internet，则 Windows 会在系统托盘中显示一个正常的网络图标。如果没有可用的活动互联网访问，则网络图标将显示黄色感叹号。它背后的魔力在于，Windows不断探测一些Microsoft服务器，以检查是否可以访问互联网。在此过程中，它会检查 dns.msftncsi.com 的IPv4和IPv6地址（Microsoft NCSI 的服务器 - 网络连接状态指示器），并将它们与硬编码值匹配。它还尝试从包含文本“Microsoft NCSI”的 msftncsi.com 服务器读取一个小文本文件“ncsi.txt”。这些操作成功后，它会声明一个活动的互联网连接，否则认为 Windows 无法访问互联网。所以我就把禁用了，不用系统检测，上不上的了网自己打开一个网页不就知道了。

**Comment by vernesong** [comment]
覆写设置，DNS设置，fake-ip-filter有预置

**Comment by hatbhtbh** [comment]
> 覆写设置，DNS设置，fake-ip-filter有预置

我试了一下再fake-ip增强模式下把Fallback-Filter打上√，还是不行；切换redir-host兼容模式一切正常。
还请大神你闲暇之余能在下一个版本能得到修复，再次表示感谢，谢谢！

**Comment by yyysuo** [comment]
> > 覆写设置，DNS设置，fake-ip-filter有预置
> 
> 我试了一下再fake-ip增强模式下把Fallback-Filter打上√，还是不行；切换redir-host兼容模式一切正常。 还请大神你闲暇之余能在下一个版本能得到修复，再次表示感谢，谢谢！

我直接用Adguard Home占用了53端口，dnsmasq的dns端口改成其它，在Adguard Home里面指定这2个域名的dns就好了。

**Comment by vernesong** [comment]
fake-ip-filter不是Fallback-Filter

**Comment by hatbhtbh** [comment]
> > > 覆写设置，DNS设置，fake-ip-filter有预置
> > 
> > 
> > 我试了一下再fake-ip增强模式下把Fallback-Filter打上√，还是不行；切换redir-host兼容模式一切正常。 还请大神你闲暇之余能在下一个版本能得到修复，再次表示感谢，谢谢！
> 
> 我直接用Adguard Home占用了53端口，dnsmasq的dns端口改成其它，在Adguard Home里面指定这2个域名的dns就好了。
最近比较忙，没有时间回复，谢谢你的方法，只是我小白一个，你能详细告诉我一下怎么设置吗，谢谢！

**Comment by hatbhtbh** [comment]
> fake-ip-filter不是Fallback-Filter

好的。我打上勾后还是不管用，我在咨询楼上的大神方法.....

**Comment by hatbhtbh** [comment]
最近一段时间我在百度和issues里面查询了好多类似于这个问题，我经过自己的测试最终在issues中找到了一个解决方法：
[https://github.com/vernesong/OpenClash/issues/2050](url)
[https://github.com/vernesong/OpenClash/commit/9c78e61fba49bdfd8bc2d57364d494cc8ab19ba0](url)
按照这个方法完美解决问题。

**Comment by hatbhtbh** [comment]
> > > 伪装设置，DNS设置，fake-ip-filter有预先设置
> > 
> > 
> > 我试了下再fake-ip增强模式下把Fallback-Filter打上√，还是不行；切换redir-host兼容模式一切换正常。还请大神你闲暇之余能在下一个版本能得到修复，再次表示感谢，谢谢！
> 
> 我直接接入Adguard Home占了53个端口，dnsmasq的dns端口改成它了，在Adguard Home里指定这2个域名的dns就好了。

大神能详细解释一下吗，我小白一个，不太懂，这个Adguard Home占了53个端口如下设置吗？
![)D@ $8KHXV@ 7J{P68@GXH](https://github.com/vernesong/OpenClash/assets/93958708/b7fd8d81-94ff-40ad-82f0-2715a7b23176)
dnsmasq的dns端口改成它了
![M5)%%~C$JWKHQSTJA2{OP3H](https://github.com/vernesong/OpenClash/assets/93958708/a425aaad-8305-4612-8d22-0c5e191166dd)
下面在Adguard Home里指定这2个域名的dns不会填了
![1~5GN3VBY T5 YM VX%Y%TL](https://github.com/vernesong/OpenClash/assets/93958708/cf847608-e4e0-4bd9-899b-bf5c72589e82)

**Comment by hatbhtbh** [comment]
> fake-ip-filter不是Fallback-Filter

大神这个问题目前就没有办法在openclash上解决了吗?用win10系统的电脑有线连接软路由应该都会遇到这个情况的吧！

**Comment by hztbhtbh1** [comment]
> > > > 伪装设置，DNS设置，fake-ip-filter有预先设置
> > > 
> > > 
> > > 我试了下再fake-ip增强模式下把Fallback-Filter打上√，还是不行；切换redir-host兼容模式一切换正常。还请大神你闲暇之余能在下一个版本能得到修复，再次表示感谢，谢谢！
> > 
> > 
> > 我直接用Adguard Home占用了53端口，dnsmasq的dns端口改成其它，在Adguard Home里面指定这2个域名的dns就好了。
> 
> 大神能指点一下吗？你这三个步骤我看不懂，拜托

**Comment by hztbhtbh1** [comment]
> > > 覆写设置，DNS设置，fake-ip-filter有预置
> > 
> > 
> > 我试了一下再fake-ip增强模式下把Fallback-Filter打上√，还是不行；切换redir-host兼容模式一切正常。 还请大神你闲暇之余能在下一个版本能得到修复，再次表示感谢，谢谢！
> 
> 我直接用Adguard Home占用了53端口，dnsmasq的dns端口改成其它，在Adguard Home里面指定这2个域名的dns就好了。

大佬，能不能请你详细讲一下设置步骤，截图也行，小白看不懂

**Comment by hztbhtbh1** [comment]
感谢大佬，我刚才试了一下更新到最新版本v0.45.121-beta打开Fake-IP-Filter
里面有这个地址，然后保存，重启电脑和睡眠模式唤醒后都正常使用，完美解决问题。谢谢~~~
`#win10本地连接检测
+.msftconnecttest.com
+.msftncsi.com`

**Comment by HimriZngz** [comment]
补充：如果在使用ipv6，则可以额外在[fake-ip-filter]中增加一行 `*.msftncsi.com`

**Comment by lightmon233** [comment]
如果开了fakeip-filter还是没用的话，可以尝试设置一下fallback的dns服务器，*.msftncsi.com在你没有专门写规则的时候应该会匹配到这里的dns服务器进行解析，很有可能你这里的dns服务器有问题导致网络连通性检测失败，比如我就因为校园网疑似把这里的dns服务器都屏蔽掉了所以检测失败，可以把上游分配的dns服务器地址填在这里并启用，然后在windows terminal里面用nslookup dns.msftncsi.com来验证dns解析是否正常。
