### ISSUE TITLE
[Bug] 升级到112后，使用TUN模式报内核崩溃 无法启动。使用非TUN模式正常启动

### ISSUE THREAD

**Issue by liuyongqing1** [vernesong/OpenClash#3216]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

0.45.112

### Bug on Environment

Other

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

没有其他环境复现

### Describe the Bug

启动的时候报错
2023-04-20 19:37:55 守护程序：检测到 Clash 内核崩溃，重启中...
	github.com/Dreamacro/clash/tunnel/tunnel.go:146 +0x71
created by github.com/Dreamacro/clash/tunnel.process
	github.com/Dreamacro/clash/tunnel/tunnel.go:478 +0x523
github.com/Dreamacro/clash/tunnel.handleTCPConn({0xfd2f18, 0xc00058f3b0})
	github.com/Dreamacro/clash/adapter/adapter.go:39 +0x38
github.com/Dreamacro/clash/adapter.(*Proxy).DialContext(0xc00031eb60, {0xfd2ce8?, 0xc00058f6e0?}, 0xc0000124f0?, {0x0?, 0x1?, 0x2?})
	github.com/Dreamacro/clash/adapter/outboundgroup/selector.go:25 +0x278
github.com/Dreamacro/clash/adapter/outboundgroup.(*Selector).DialContext(0xc000326b80, {0xfd2ce8, 0xc00058f6e0}, 0x15a06a0?, {0x0, 0x0, 0x0})
	github.com/Dreamacro/clash/adapter/adapter.go:39 +0x38
github.com/Dreamacro/clash/adapter.(*Proxy).DialContext(0xc00031e700, {0xfd2ce8?, 0xc00058f6e0?}, 0x508b73?, {0x0?, 0xc0002ca7a0?, 0x15a06a0?})
	github.com/Dreamacro/clash/adapter/outboundgroup/selector.go:25 +0x278
github.com/Dreamacro/clash/adapter/outboundgroup.(*Selector).DialContext(0xc000326580, {0xfd2ce8, 0xc00058f6e0}, 0xc0001d5cb0?, {0x0, 0x0, 0x0})
	github.com/Dreamacro/clash/adapter/adapter.go:39 +0x38
github.com/Dreamacro/clash/adapter.(*Proxy).DialContext(0xc000302300, {0xfd2ce8?, 0xc00058f6e0?}, 0x0?, {0x0?, 0x40df47?, 0x20?})
	github.com/Dreamacro/clash/adapter/outbound/shadowsocksr.go:73 +0x433
github.com/Dreamacro/clash/adapter/outbound.(*ShadowSocksR).DialContext(0xc00024e840, {0xfd2ce8, 0xc00058f6e0}, 0xc0001d5ba8?, {0x0?, 0xc000326580?, 0xb13b01?})
	github.com/Dreamacro/clash/adapter/outbound/shadowsocksr.go:57 +0x14c
github.com/Dreamacro/clash/adapter/outbound.(*ShadowSocksR).StreamConn(0xc00024e840, {0xfda7a8?, 0xc000012510?}, 0xc0002585a0?)
	github.com/Dreamacro/clash/transport/ssr/protocol/stream.go:39 +0x1f4
github.com/Dreamacro/clash/transport/ssr/protocol.(*Conn).Write(0xc000118770, {0xc0003743c0, 0x13, 0x18})
	github.com/Dreamacro/clash/common/pool/buffer.go:16
github.com/Dreamacro/clash/common/pool.GetBuffer(...)
goroutine 153 [running]:
panic: interface conversion: interface {} is *protobytes.BytesWriter, not *bytes.Buffer

### OpenClash Log

2023-04-20 19:37:55 守护程序：检测到 Clash 内核崩溃，重启中...
	github.com/Dreamacro/clash/tunnel/tunnel.go:146 +0x71
created by github.com/Dreamacro/clash/tunnel.process
	github.com/Dreamacro/clash/tunnel/tunnel.go:478 +0x523
github.com/Dreamacro/clash/tunnel.handleTCPConn({0xfd2f18, 0xc00058f3b0})
	github.com/Dreamacro/clash/adapter/adapter.go:39 +0x38
github.com/Dreamacro/clash/adapter.(*Proxy).DialContext(0xc00031eb60, {0xfd2ce8?, 0xc00058f6e0?}, 0xc0000124f0?, {0x0?, 0x1?, 0x2?})
	github.com/Dreamacro/clash/adapter/outboundgroup/selector.go:25 +0x278
github.com/Dreamacro/clash/adapter/outboundgroup.(*Selector).DialContext(0xc000326b80, {0xfd2ce8, 0xc00058f6e0}, 0x15a06a0?, {0x0, 0x0, 0x0})
	github.com/Dreamacro/clash/adapter/adapter.go:39 +0x38
github.com/Dreamacro/clash/adapter.(*Proxy).DialContext(0xc00031e700, {0xfd2ce8?, 0xc00058f6e0?}, 0x508b73?, {0x0?, 0xc0002ca7a0?, 0x15a06a0?})
	github.com/Dreamacro/clash/adapter/outboundgroup/selector.go:25 +0x278
github.com/Dreamacro/clash/adapter/outboundgroup.(*Selector).DialContext(0xc000326580, {0xfd2ce8, 0xc00058f6e0}, 0xc0001d5cb0?, {0x0, 0x0, 0x0})
	github.com/Dreamacro/clash/adapter/adapter.go:39 +0x38
github.com/Dreamacro/clash/adapter.(*Proxy).DialContext(0xc000302300, {0xfd2ce8?, 0xc00058f6e0?}, 0x0?, {0x0?, 0x40df47?, 0x20?})
	github.com/Dreamacro/clash/adapter/outbound/shadowsocksr.go:73 +0x433
github.com/Dreamacro/clash/adapter/outbound.(*ShadowSocksR).DialContext(0xc00024e840, {0xfd2ce8, 0xc00058f6e0}, 0xc0001d5ba8?, {0x0?, 0xc000326580?, 0xb13b01?})
	github.com/Dreamacro/clash/adapter/outbound/shadowsocksr.go:57 +0x14c
github.com/Dreamacro/clash/adapter/outbound.(*ShadowSocksR).StreamConn(0xc00024e840, {0xfda7a8?, 0xc000012510?}, 0xc0002585a0?)
	github.com/Dreamacro/clash/transport/ssr/protocol/stream.go:39 +0x1f4
github.com/Dreamacro/clash/transport/ssr/protocol.(*Conn).Write(0xc000118770, {0xc0003743c0, 0x13, 0x18})
	github.com/Dreamacro/clash/common/pool/buffer.go:16
github.com/Dreamacro/clash/common/pool.GetBuffer(...)
goroutine 153 [running]:
panic: interface conversion: interface {} is *protobytes.BytesWriter, not *bytes.Buffer

### Expected Behavior

应该能正常启动，目前是我无论使用redir-host还是使用fake ip都是一样 只要使用TUN就是不能启动

**Comment by vernesong** [comment]
等内核更新

**Comment by gj0518** [comment]
同样问题
