### ISSUE TITLE
[Feature] 能否增加openclash启动后，延迟n秒后自动对节点进行测速的功能？

### ISSUE THREAD

**Issue by Tatchaxzw** [vernesong/OpenClash#3217]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

我的设置是：
1、23点更新订阅
2、24点更新大陆白名单和ipv6白名单
3、更改测速间隔为300秒

出现的问题的是：
自动更新订阅和白名单后，openclash重启，但是重启完成300秒后，节点没有连上，看了下控制面板，节点全部显示灰色，似乎是未完成测速，不知道是未进行测速还是测速失败。（如今晚23点重启后，直到23:30仍未连上节点）但是每次手动测速都没有问题。导致经常性到点后无法访问外网，需要进入控制面板手动测速。

PS：
该问题是经常性出现，但不是总出现，也会有重启后300秒测速成功的情况。

### Describe the Solution

增加启动后，延迟n秒自动进行测速的功能，并保证测速完成。

**Comment by vernesong** [comment]
什么内核

**Comment by Tatchaxzw** [comment]
> 什么内核

Dev内核启动，Fake-ip增强模式

**Comment by vernesong** [comment]
你先换一下测速地址

**Comment by Tatchaxzw** [comment]
> 你先换一下测速地址

好的，我会更换测试地址并观察一段时间

**Comment by Tatchaxzw** [comment]
> 你先换一下测速地址

作者你好，更换测速地址后也是有时生效有时不生效的情况，已经更换过4种地址，请问这是网络连通性问题造成的吗

**Comment by vernesong** [comment]
测速是内核自己的行为，考虑到这个问题不常见，判断应该是节点的问题，可以在电脑上验证

**Comment by Tatchaxzw** [comment]
> 测速是内核自己的行为，考虑到这个问题不常见，判断应该是节点的问题，可以在电脑上验证

好的，谢谢

**Comment by a76yyyy** [comment]
> > 你先换一下测速地址
> 
> 作者你好，更换测速地址后也是有时生效有时不生效的情况，已经更换过4种地址，请问这是网络连通性问题造成的吗

是不是这里描述的问题 vernesong/OpenClash#3274
