### ISSUE TITLE
[Bug] 插件日志显示异常 ...

### ISSUE THREAD

**Issue by jacobin** [vernesong/OpenClash#3218]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.112

### Bug on Environment

Other

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

1、早前，在OpenClashV0.45.110的时候，我在“运行日志”\"插件日志" 里看到诸如“2023-04-21 02:01:51 守护程序：因日志大小限制，清理所有日志内容...”的日志信息；
2、因为不爽1，到“插件设置” --> “模式设置” --> 把“日志大小”从1024KB修改为10240KB；如图1
3、做完2，以为大吉利是，不曾想出现了，如图2之莫名其妙难以名状的"奇观"。

### Describe the Bug

见前面重现/Reproduce的步骤，我认为：
1、在Reproduce step 3里，不该是显示出个奇迹“...”，令人看到而呆若木鸡不知所措；
2、在Reproduce step 1里，我认为“日志大小”的限制应该不至于要清理所有的日志内容，采用FIFO的队列，迎新除旧不是更合理吗？

### OpenClash Log

没有攫取日志

### OpenClash Config

```shell
Reproduce步骤里有相关说明
```

### Expected Behavior

无论如何，都要能正确显示最近最新的日志，而不是当垃圾一样一扫而空尚嫌房子太小不够收拾。

### Screenshots

![Snap9](https://user-images.githubusercontent.com/5020373/233454528-58e820b4-a4b5-4bb1-a013-e34810cc91d5.jpg)
![Snap10](https://user-images.githubusercontent.com/5020373/233454542-aa755115-aac8-4e80-b5ec-a9651ab63e4c.jpg)

**Comment by jacobin** [comment]
太初，上帝创造了天地，有如下提示
![Snap12](https://user-images.githubusercontent.com/5020373/233455645-4ba1c0cf-13da-4b10-89d1-7d704aeb4f6d.jpg)

**Comment by vernesong** [comment]
这里刷新只会显示一千行的内容，一千行是插件日志和内核日志的总行数

**Comment by vernesong** [comment]
这里刷新只会显示一千行的内容，一千行是插件日志和内核日志的总行数

**Comment by jacobin** [comment]
> 这里刷新只会显示一千行的内容，一千行是插件日志和内核日志的总行数

噢。我以为：
1、插件日志和内核日志是分开分属的；
2、“一千行”应该是个日志窗口，且该窗口一直盖扣在日志的最前部，是个Viewer；
3、“日志大小”应该是存储空间的支配大小。

谢谢

**Comment by dqh668** [comment]
> 这里刷新只会显示一千行的内容，一千行是插件日志和内核日志的总行数

插件日志经常被自动清除 了，不知道可不可以看分开插件日志和内核日志，我感觉保留插件日志可以更清楚看到订阅连接是否定时更新内容

**Comment by sunrise021** [comment]
> 这里刷新只会显示一千行的内容，一千行是插件日志和内核日志的总行数

您好，请问是开发者吗？ 这里能修改一下么，让我们点击进去的时候能看见前面1000条，现在点击进去经常是没用日志的

**Comment by mosesyeung** [comment]
我也需要进去看到今天凌晨订阅连接的定时更新内容是否成功更新。 麻烦您把这个日志前面1000条加回去。 另外，我有6台NanoPi R4S, iStore与Open Clash的固件版本都是一样的，只有一台出现这个问题。这一台的不同的是SD卡是32G的， 在没有问题的机器里的SD卡是8G的。

**Comment by vernesong** [comment]
日志是根据文件大小去清除的，前端只会显示一千行，要看完整的去看文件/tmp/openclash.log

**Comment by 1q2w3e123-coder** [comment]
我也有这个问题，他好像不是所有设备安装openclash出现这个情况
