### ISSUE TITLE
[Bug] 无法打开pikpak下的文件  其他网站均正常

### ISSUE THREAD

**Issue by sunr1s6** [vernesong/OpenClash#3219]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

V0.45.112

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

除开fake ip 
无论什么模式下 全局 规则 TUN 都无法访问pikpak里的文件。
只能看到文件目录 
用的Meta模式 ，且重置过openclash所有设置，用默认配置也不行。

### Describe the Bug

无法打开pikpak下的文件  其他网站均正常

### OpenClash Log

无法打开pikpak下的文件  其他网站均正常

### OpenClash Config

```shell
无法打开pikpak下的文件  其他网站均正常
```

### Expected Behavior

无法打开pikpak下的文件  其他网站均正常

### Screenshots

无法打开pikpak下的文件  其他网站均正常

**Comment by vernesong** [comment]
控制面板debug模式看下链接日志的说明

**Comment by lzk821** [comment]
您好，解决了吗
