### ISSUE TITLE
[Bug] 更新了v0.45.112-beta版，raw.githubusercontent.com又访问不了了

### ISSUE THREAD

**Issue by free1x** [vernesong/OpenClash#3221]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.112-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

[v0.45.100-beta]出现这个问题，后面更新了103版，可以访问了。现在更新了v0.45.112-beta版，raw.githubusercontent.com又访问不了

### Describe the Bug

更新了v0.45.112-beta版，raw.githubusercontent.com又访问不了了

### OpenClash Log

更新了v0.45.112-beta版，raw.githubusercontent.com又访问不了了

### OpenClash Config

```shell
更新了v0.45.112-beta版，raw.githubusercontent.com又访问不了了
```

### Expected Behavior

更新了v0.45.112-beta版，raw.githubusercontent.com又访问不了了

**Comment by jacobin** [comment]
我也是出现过这个问题现象，浪费了我不少时间。寻寻觅觅凄凄惨惨之后，我的可能的解决方法是：须要用户自己重新洗一遍附加规则也就是第三方规则，具体做法就是明确地一个个地把那些第三方规则加进去，并调试以观效果

**Comment by await777** [comment]
确实访问不了，只能加在第三方规则走代理
