### ISSUE TITLE
[Bug] parse rule provider  error: cannot parse 'interval' as int: strconv.ParseInt: parsing "86400 86400": invalid syntax

### ISSUE THREAD

**Issue by zhqu1148980644** [vernesong/OpenClash#3222]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.100 beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

1. 添加多份订阅配置
2. 添加rule providers(use for all configs)
3. 应用设置

### Describe the Bug

为所有配置添加rule providers后保存时报错

### OpenClash Log

```
2023-04-21 15:43:38 FTL [Config] parse config failed error=parse rule provider 国内域名白名单 error: cannot parse 'interval' as int: strconv.ParseInt: parsing "86400 86400": invalid syntax

```

### Expected Behavior

不报错

### Screenshots
<img width="329" alt="image" src="https://user-images.githubusercontent.com/29366130/233579709-17e7121c-2cfc-4cbd-b925-0bf5293bcf96.png">
<img width="362" alt="image" src="https://user-images.githubusercontent.com/29366130/233579794-beb895f8-3a7f-4462-b522-f0faeac0cf95.png">

_No response_

**Comment by vernesong** [comment]
看一下配置文件对应生成的内容是什么
