### ISSUE TITLE
[Bug] ADG使用DNS重写内网IP被OpenClash拦截的问题

### ISSUE THREAD

**Issue by ZhelinCheng** [vernesong/OpenClash#3226]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.112-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

客户端 -> 网关(10.0.0.2) -> OpenWrt(10.0.0.2) -> OpenClash(dns劫持开启) -> OpenClash（自定义上游 DNS 服务器开启，配置ADG 10.0.1.2:53）

同时我开启了【启用第二 DNS 服务器】，并将本地ADG服务及域名填写

### Describe the Bug

当DNS重写设置成公网地址能正确解析：
![image](https://user-images.githubusercontent.com/16441850/233792691-e5dc0106-00b6-406a-a971-4b8461648aa4.png)

当DNS重写设置成内网地址不能解析：
![image](https://user-images.githubusercontent.com/16441850/233792755-533eb8e9-4e61-4444-88bb-b87cdcb68b3b.png)

### OpenClash Log

#===================== 系统信息 =====================#

主机型号: Default string Default string
固件版本: iStoreOS 21.02.3 2023042111
LuCI版本: git-22.258.47264-284140f
内核版本: 5.4.188
处理器架构: x86_64

#此项有值时,如不使用IPv6,建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: 

DNS劫持: Dnsmasq 转发
#DNS劫持为Dnsmasq时，此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 127.0.0.1#7874

#===================== 依赖检查 =====================#

dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
libcap: 已安装
libcap-bin: 已安装
ruby: 已安装
ruby-yaml: 已安装
ruby-psych: 已安装
ruby-pstore: 已安装
kmod-tun(TUN模式): 已安装
luci-compat(Luci >= 19.07): 已安装
kmod-inet-diag(PROCESS-NAME): 已安装
unzip: 已安装
iptables-mod-tproxy: 已安装
kmod-ipt-tproxy: 已安装
iptables-mod-extra: 已安装
kmod-ipt-extra: 已安装
kmod-ipt-nat: 已安装

#===================== 内核检查 =====================#

运行状态: 运行中
运行内核：Dev
进程pid: 31701
运行权限: 31701: cap_dac_override,cap_net_bind_service,cap_net_admin,cap_net_raw,cap_sys_ptrace,cap_sys_resource=eip
运行用户: nobody
已选择的架构: linux-amd64

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 
Tun内核文件: 不存在
Tun内核运行权限: 否

Dev内核版本: v1.11.0-7-g5497ada
Dev内核文件: 存在
Dev内核运行权限: 正常

Meta内核版本: 
Meta内核文件: 不存在
Meta内核运行权限: 否

#===================== 插件设置 =====================#

当前配置文件: /etc/openclash/config/速鹰.yaml
启动配置文件: /etc/openclash/速鹰.yaml
运行模式: redir-host
默认代理模式: rule
UDP流量转发(tproxy): 启用
自定义DNS: 启用
IPV6代理: 停用
IPV6-DNS解析: 停用
禁用Dnsmasq缓存: 启用
自定义规则: 停用
仅允许内网: 启用
仅代理命中规则流量: 启用
仅允许常用端口流量: 停用
绕过中国大陆IP: 启用
路由本机代理: 启用

#启动异常时建议关闭此项后重试
混合节点: 停用
保留配置: 停用

#启动异常时建议关闭此项后重试
第三方规则: 停用

#===================== 配置文件 =====================#

port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: info
external-controller: 0.0.0.0:9090
proxy-groups:

### Expected Behavior

希望能正确解析IP

**Comment by vernesong** [comment]
![image](https://user-images.githubusercontent.com/42875168/233794476-4f80098a-3f3f-412c-ba35-81f87e1780d2.png)

**Comment by ZhelinCheng** [comment]
> ![image](https://user-images.githubusercontent.com/42875168/233794476-4f80098a-3f3f-412c-ba35-81f87e1780d2.png)

谢谢
