### ISSUE TITLE
使用一段时间后会出现wall外无法访问

### ISSUE THREAD

**Issue by USDao** [vernesong/OpenClash#323]
固件版本：OpenWrt R20.4.8 / LuCI Master (git-20.088.29068-cebe120)
内核版本：v0.19.0-8-g2750c7e / 原版的amd64  19.0
客户端版本：v0.37.3
运行模式：redir-host
openwrt开机后可以正常使用，使用一段时候以后无法正常访问wall外的网站，国内网站访问正常，检查dns解析正常，防火墙条目正常。切换fake-ip也无法访问。

**dns正常解析**
root@Route:~# cat /etc/init.d/openclash |grep 7874
      dns_port=7874
root@Route:~# netstat -an |grep 7874
udp        0      0 127.0.0.1:7874          0.0.0.0:*                           
root@Route:~# dig www.google.com @127.0.0.1 -p 7874

; <<>> DiG 9.11.2-P1 <<>> www.google.com @127.0.0.1 -p 7874
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 45713
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 6, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;www.google.com.			IN	A

;; ANSWER SECTION:
www.google.com.		83	IN	A	74.125.20.99
www.google.com.		83	IN	A	74.125.20.105
www.google.com.		83	IN	A	74.125.20.104
www.google.com.		83	IN	A	74.125.20.106
www.google.com.		83	IN	A	74.125.20.147
www.google.com.		83	IN	A	74.125.20.103

;; Query time: 39 msec
;; SERVER: 127.0.0.1#7874(127.0.0.1)
;; WHEN: Mon Apr 13 09:46:40 CST 2020
;; MSG SIZE  rcvd: 223

**firewall**
Chain PREROUTING (policy ACCEPT 57138 packets, 20M bytes)
 pkts bytes target     prot opt in     out     source               destination         
    8   480 REDIRECT   tcp  --  *      *       0.0.0.0/0            8.8.4.4              redir ports 7892
    0     0 REDIRECT   tcp  --  *      *       0.0.0.0/0            8.8.8.8              redir ports 7892
14611  842K REDIRECT   udp  --  *      *       0.0.0.0/0            0.0.0.0/0            udp dpt:53 redir ports 53
    0     0 REDIRECT   tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:53 redir ports 53
97175   23M prerouting_rule  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom prerouting rule chain */
59971   11M zone_lan_prerouting  all  --  br-lan *       0.0.0.0/0            0.0.0.0/0            /* !fw3 */
37204   12M zone_wan_prerouting  all  --  pppoe-wan *       0.0.0.0/0            0.0.0.0/0            /* !fw3 */
40777 2155K openclash  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0      

重启firewall dnsmasq openclash 均无法正常使用 需要重启路由

openclash 日志调整到info也没发现异常 而且日志时间不是北京时间 哈

没有办法再排查下去了。。。。一切都只能重启路由后，就恢复正常

**Comment by vernesong** [comment]
你用电脑查询下dns

**Comment by USDao** [comment]
在电脑上查询dns 通过网关ip查询 解析也正常

openwrt在重启的时候会出现 
sh: out of range的提示

**Comment by vernesong** [comment]
异常的时候截图上来

**Comment by USDao** [comment]
问题解决不是程序问题。系统时间和服务器时间相差超过2秒，导致v2ray连接失败。

另外对服务器延迟应该只是使用了icmp而没有url检测，导致服务器连接不上，延时显示正常。

**Comment by sunxun47** [comment]
之前日志里面

> 固件版本：OpenWrt R20.4.8 / LuCI Master (git-20.088.29068-cebe120)
> 内核版本：v0.19.0-8-g2750c7e / 原版的amd64 19.0
> 客户端版本：v0.37.3
> 运行模式：redir-host
> openwrt开机后可以正常使用，使用一段时候以后无法正常访问wall外的网站，国内网站访问正常，检查dns解析正常，防火墙条目正常。切换fake-ip也无法访问。
> 
> **dns正常解析**
> root@Route:~# cat /etc/init.d/openclash |grep 7874 dns_port=7874 root@Route:~# netstat -an |grep 7874
> udp 0 0 127.0.0.1:7874 0.0.0.0:*
> root@Route:~# dig [www.google.com](http://www.google.com) @127.0.0.1 -p 7874
> 
> ; <<>> DiG 9.11.2-P1 <<>> [www.google.com](http://www.google.com) @127.0.0.1 -p 7874
> ;; global options: +cmd
> ;; Got answer:
> ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 45713
> ;; flags: qr aa rd ra; QUERY: 1, ANSWER: 6, AUTHORITY: 0, ADDITIONAL: 1
> 
> ;; OPT PSEUDOSECTION:
> ; EDNS: version: 0, flags:; udp: 4096
> ;; QUESTION SECTION:
> ;www.google.com. IN A
> 
> ;; ANSWER SECTION:
> [www.google.com](http://www.google.com). 83 IN A 74.125.20.99
> [www.google.com](http://www.google.com). 83 IN A 74.125.20.105
> [www.google.com](http://www.google.com). 83 IN A 74.125.20.104
> [www.google.com](http://www.google.com). 83 IN A 74.125.20.106
> [www.google.com](http://www.google.com). 83 IN A 74.125.20.147
> [www.google.com](http://www.google.com). 83 IN A 74.125.20.103
> 
> ;; Query time: 39 msec
> ;; SERVER: 127.0.0.1#7874(127.0.0.1)
> ;; WHEN: Mon Apr 13 09:46:40 CST 2020
> ;; MSG SIZE rcvd: 223
> 
> **firewall**
> Chain PREROUTING (policy ACCEPT 57138 packets, 20M bytes)
> pkts bytes target prot opt in out source destination
> 8 480 REDIRECT tcp -- * * 0.0.0.0/0 8.8.4.4 redir ports 7892
> 0 0 REDIRECT tcp -- * * 0.0.0.0/0 8.8.8.8 redir ports 7892
> 14611 842K REDIRECT udp -- * * 0.0.0.0/0 0.0.0.0/0 udp dpt:53 redir ports 53
> 0 0 REDIRECT tcp -- * * 0.0.0.0/0 0.0.0.0/0 tcp dpt:53 redir ports 53
> 97175 23M prerouting_rule all -- * * 0.0.0.0/0 0.0.0.0/0 /* !fw3: Custom prerouting rule chain _/ 59971 11M zone_lan_prerouting all -- br-lan * 0.0.0.0/0 0.0.0.0/0 /_ !fw3 _/ 37204 12M zone_wan_prerouting all -- pppoe-wan * 0.0.0.0/0 0.0.0.0/0 /_ !fw3 */
> 40777 2155K openclash tcp -- * * 0.0.0.0/0 0.0.0.0/0
> 
> 重启firewall dnsmasq openclash 均无法正常使用 需要重启路由
> 
> openclash 日志调整到info也没发现异常 而且日志时间不是北京时间 哈
> 
> 没有办法再排查下去了。。。。一切都只能重启路由后，就恢复正常

日志的时间问题：
用的game_tun 的内核。
dashboard 里面的时间不会有问题。openclash 脚本生成的log 里面的时间，一种来自date 命令，这个时间是正常的，另外一个是nohup clash ，这个时间是utc，试了hwclock -w 发现无关，固件里加了zoneinfo 以后正常，不过不少固件里面应该都是luci 设置时区，没有zoneinfo。
