### ISSUE TITLE
[Bug] DNS地址引号脱除导致META的代理解析功能无效

### ISSUE THREAD

**Issue by scegg** [vernesong/OpenClash#3230]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.112-239

### Bug on Environment

Official OpenWrt, Lean

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

添加一个配置文件，包含使用代理组的DNS。
使用此配置文件。
配置文件会被自动编辑，相关行的引号被去掉，导致代理组被认为注释。

### Describe the Bug

Meta现支持指定代理组访问DNS，语法为```'[协议://]DNS域名或IP[:端口]#ProxyGroup名'```，例如```'tls://8.8.4.4:853#DNSg'```，参考[官方文档](https://docs.metacubex.one/function/dns/fallback)。

Openclash自动整理配置文件格式时，将引号脱除，导致组名被认为注释，从而功能无效。

### OpenClash Log

N/A

### Expected Behavior

DNS记录中，引号内带有#时，引号不应脱除。

**Comment by vernesong** [comment]
这个我测试过不影响
