### ISSUE TITLE
[Bug] v0.45.112-beta版本关闭openclash后，dns服务无法启动使用

### ISSUE THREAD

**Issue by davidu2003** [vernesong/OpenClash#3247]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.112-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

启动状态下在运行状态页面点击关闭openclash按钮，待关闭后：
1. 使用电脑或者手机访问任意网站，如 https://www.baidu.com，查看访问结果.
2. ssh登录openwrt，执行 netstat -ntl|grep 53查看端口占用。

### Describe the Bug

关闭openclash后，所有网站无法访问，登录openwrt查看53端口，没有进程监听，dns服务无法启动。

### OpenClash Log

无

### Expected Behavior

关闭openclash后，dns服务能正常使用。

**Comment by vernesong** [comment]
尝试dev114

**Comment by davidu2003** [comment]
> 尝试dev114

114版本也有该问题，103版本是ok的

**Comment by dockylf** [comment]
问题完全一致，唯一不同的是关闭openclash后，整个局域网中只有我的手机可以上网。
