### ISSUE TITLE
[Bug] v0.45.112-beta 开启代理后 dns 无法使用

### ISSUE THREAD

**Issue by dyf991645** [vernesong/OpenClash#3248]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.112-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

更新openwrt版本后，所有安装的东西都丢了，下载了最新版本的openclash，恢复之前的配置文件，然后就用不了。

### Describe the Bug

开启代理后dns失效。详见日志。
看issue里有人提dns相关的问题，虽然和他情况不一样，尝试了103版本，仍然不行。
lsof -i:53 dnsmasq 运行正常

### OpenClash Log

2023-04-27 21:05:04 level=warning msg="[TCP] dial DIRECT (match Match/) to 1.0.0.1:853 error: dial tcp4 1.0.0.1:853: no such device"
2023-04-27 21:05:04 level=warning msg="[TCP] dial DIRECT (match Match/) to 1.1.1.1:853 error: dial tcp4 1.1.1.1:853: no such device"
2023-04-27 21:05:04 level=warning msg="[TCP] dial DIRECT (match Match/) to 1.0.0.1:853 error: dial tcp4 1.0.0.1:853: no such device"
2023-04-27 21:05:04 level=warning msg="[TCP] dial DIRECT (match Match/) to 1.1.1.1:853 error: dial tcp4 1.1.1.1:853: no such device"
2023-04-27 21:05:04 level=warning msg="[TCP] dial DIRECT (match Match/) to 1.0.0.1:853 error: dial tcp4 1.0.0.1:853: no such device"
2023-04-27 21:05:04 level=warning msg="[TCP] dial DIRECT (match Match/) to 1.1.1.1:853 error: dial tcp4 1.1.1.1:853: no such device"
2023-04-27 21:05:04 level=warning msg="[TCP] dial DIRECT (match RuleSet/direct) to t14.baidu.com:443 error: all DNS requests failed, first error: Post \"https://public.dns.iij.jp/dns-query\": all DNS requests failed, first error: dial udp4 119.29.29.29:53: no such device"
2023-04-27 21:05:04 level=warning msg="[TCP] dial DIRECT (match Match/) to 1.0.0.1:853 error: dial tcp4 1.0.0.1:853: no such device"
2023-04-27 21:05:03 level=warning msg="[TCP] dial DIRECT (match RuleSet/direct) to b.bdstatic.com:443 error: all DNS requests failed, first error: use default dns resolve failed: all DNS requests failed, first error: dial udp4 119.29.29.29:53: no such device"
2023-04-27 21:05:03 level=warning msg="[TCP] dial DIRECT (match RuleSet/direct) to hpd.baidu.com:443 error: all DNS requests failed, first error: use default dns resolve failed: all DNS requests failed, first error: dial udp4 119.29.29.29:53: no such device"
2023-04-27 21:05:03 level=warning msg="[TCP] dial DIRECT (match RuleSet/direct) to b.bdstatic.com:443 error: all DNS requests failed, first error: use default dns resolve failed: all DNS requests failed, first error: dial udp4 119.29.29.29:53: no such device"
2023-04-27 21:05:03 level=warning msg="[TCP] dial DIRECT (match RuleSet/direct) to hpd.baidu.com:443 error: all DNS requests failed, first error: use default dns resolve failed: all DNS requests failed, first error: dial udp4 119.29.29.29:53: no such device"
2023-04-27 21:05:03 level=warning msg="[TCP] dial DIRECT (match RuleSet/direct) to b.bdstatic.com:443 error: all DNS requests failed, first error: use default dns resolve failed: all DNS requests failed, first error: dial udp4 119.29.29.29:53: no such device"
2023-04-27 21:05:03 level=warning msg="[TCP] dial DIRECT (match RuleSet/direct) to b.bdstatic.com:443 error: all DNS requests failed, first error: use default dns resolve failed: all 

### OpenClash Config

```shell
##---------------------------------------------------#
## This file should be located in $HOME/.config/clash/*.yaml
## Official Document https://github.com/Dreamacro/clash/wiki
## Unofficial Wiki: https://lancellc.gitbook.io/clash/
##---------------------------------------------------#

# Port of HTTP(S) proxy server on the local end
port: 7890

# Port of SOCKS5 proxy server on the local end
socks-port: 7891

# Transparent proxy server port for Linux and macOS (Redirect TCP and TProxy UDP)
# redir-port: 7892

# Transparent proxy server port for Linux (TProxy TCP and TProxy UDP)
# tproxy-port: 7893

# HTTP(S) and SOCKS4(A)/SOCKS5 server on the same port
mixed-port: 7890

# authentication of local SOCKS5/HTTP(S) server
# authentication:
#  - "user1:pass1"
#  - "user2:pass2"

# Set to true to allow connections to the local-end server from
# other LAN IP addresses
allow-lan: true

# This is only applicable when `allow-lan` is `true`
# '*': bind all IP addresses
# 192.168.122.11: bind a single IPv4 address
# "[aaaa::a8aa:ff:fe09:57d8]": bind a single IPv6 address
bind-address: '*'

# Clash router working mode
# rule: rule-based packet routing
# global: all packets will be forwarded to a single endpoint
# direct: directly forward the packets to the Internet
mode: rule

# Clash by default prints logs to STDOUT
# info / warning / error / debug / silent
log-level: info

# When set to false, resolver won't translate hostnames to IPv6 addresses
ipv6: false

# RESTful web API listening address
external-controller: 127.0.0.1:9090

# A relative path to the configuration directory or an absolute path to a
# directory in which you put some static web resource. Clash core will then
# serve it at `http://{{external-controller}}/ui`.
# external-ui: folder

# Secret for the RESTful API (optional)
# Authenticate by spedifying HTTP header `Authorization: Bearer ${secret}`
# ALWAYS set a secret if RESTful API is listening on 0.0.0.0
# secret: ""

# Outbound interface name
interface-name: en0

# fwmark on Linux only
routing-mark: 6666

# Static hosts for DNS server and connection establishment (like /etc/hosts)
#
# Wildcard hostnames are supported (e.g. *.clash.dev, *.foo.*.example.com)
# Non-wildcard domain names have a higher priority than wildcard domain names
# e.g. foo.example.com > *.example.com > .example.com
# P.S. +.foo.com equals to .foo.com and foo.com
hosts:
  # '*.clash.dev': 127.0.0.1
  # '.dev': 127.0.0.1s
  # # 'alpha.clash.dev': '::1'

profile:
  # Store the `select` results in $HOME/.config/clash/.cache
  # set false If you don't want this behavior
  # when two different configurations have groups with the same name, the selected values are shared
  store-selected: false

  # persistence fakeip
  store-fake-ip: true

dns:
  enable: true
  listen: 0.0.0.0:53
  # ipv6: false # when the false, response to AAAA questions will be empty

  # These nameservers are used to resolve the DNS nameserver hostnames below.
  # Specify IP addresses only
  default-nameserver:
    - 114.114.114.114
    - 8.8.8.8
  enhanced-mode: fake-ip # or redir-host
  fake-ip-range: 198.18.0.1/16 # Fake IP addresses pool CIDR
  use-hosts: true # lookup hosts and return IP record
  
  # Hostnames in this list will not be resolved with fake IPs
  # i.e. questions to these domain names will always be answered with their
  # real IP addresses
  # fake-ip-filter:
  #   - '*.lan'
  #   - localhost.ptlogin2.qq.com
  
  # Supports UDP, TCP, DoT, DoH. You can specify the port to connect to.
  # All DNS questions are sent directly to the nameserver, without proxies
  # involved. Clash answers the DNS question with the first result gathered.
  nameserver:
    - 114.114.114.114
    - 223.5.5.5 # 阿里
    - 180.76.76.76 # 百度
    - 8.8.8.8 # Google
    - tls://dns.rubyfish.cn:853 # DNS over TLS
    - https://1.1.1.1/dns-query # DNS over HTTPS
    - dhcp://en0 # dns from dhcp


proxies:  null

proxy-groups:
  - name: PROXY
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    tolerance: 200
    lazy: true
    use:
      - tomatossr

proxy-providers:
  tomatossr:
    type: http
    url: xxxxxxxxxxxxxxxxxxxxx
    interval: 3600
    path: default.yaml
    health-check:
      enable: true
      interval: 600
      lazy: true
      url: http://www.gstatic.com/generate_204

rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400

  icloud:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 86400

  apple:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 86400

  google:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt"
    path: ./ruleset/google.yaml
    interval: 86400

  proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400

  direct:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400

  private:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
    path: ./ruleset/private.yaml
    interval: 86400

  gfw:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400

  greatfire:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/greatfire.tx\
      t"
    path: ./ruleset/greatfire.yaml
    interval: 86400

  tld-not-cn:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.t\
      xt"
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400

  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr\
      .txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400

  cncidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400

  lancidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400

  applications:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications\
      .txt"
    path: ./ruleset/applications.yaml
    interval: 86400

rules:
  - SRC-IP-CIDR,192.168.31.105/32,DIRECT
  - SRC-IP-CIDR,192.168.31.111/32,DIRECT
  - SRC-IP-CIDR,192.168.31.112/32,DIRECT
  - DOMAIN,data.sec.miui.com,DIRECT
  - DOMAIN-SUFFIX,steampowered.com,DIRECT
  - DOMAIN-SUFFIX,googleapis.cn,PROXY
  - DOMAIN,ghcr.io,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - RULE-SET,applications,DIRECT
  - RULE-SET,private,DIRECT
  - RULE-SET,reject,REJECT
  - RULE-SET,icloud,DIRECT
  - RULE-SET,apple,DIRECT
  - RULE-SET,google,PROXY
  - RULE-SET,proxy,PROXY
  - RULE-SET,direct,DIRECT
  - RULE-SET,lancidr,DIRECT
  - RULE-SET,cncidr,DIRECT
  - RULE-SET,telegramcidr,PROXY
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,PROXY
```

### Expected Behavior

正常使用

### Screenshots

无

**Comment by vernesong** [comment]
关闭插件，看看路由本机的网络是不是有问题

**Comment by dyf991645** [comment]
> 关闭插件，看看路由本机的网络是不是有问题

关闭插件后正常的，开启代理就不行，

**Comment by vernesong** [comment]
![image](https://user-images.githubusercontent.com/42875168/235063837-c1f72bbe-54c2-47e6-b739-77723fc0c65d.png)
这两个去掉

**Comment by dyf991645** [comment]
> ![image](https://user-images.githubusercontent.com/42875168/235063837-c1f72bbe-54c2-47e6-b739-77723fc0c65d.png) 这两个去掉

可以了，感谢

**Comment by a11thwn** [comment]
感谢这个issue，R2S 困扰很久的问题解决，因为固件绑定的网口问题升级87以后的版本就网络出错了，今天参考了这个帖子就恢复正常了。
如果没有手工绑定网口，不是dial tcp4 XXX:XXX  i/o timeout 就是 all DNS requests failed 的错误提示。

设置方法如下：
<img width="922" alt="Snipaste_2023-05-10_21-04-32" src="https://github.com/vernesong/OpenClash/assets/2621203/293aeb29-1f49-41db-8d3a-6a10ff08bdaa">
<img width="1150" alt="Snipaste_2023-05-10_21-06-04" src="https://github.com/vernesong/OpenClash/assets/2621203/cbb0d2e1-b9e6-4d0f-aa25-a4745c8347ab">
<img width="776" alt="Snipaste_2023-05-10_21-06-38" src="https://github.com/vernesong/OpenClash/assets/2621203/cbf575be-3aaa-4bef-ad3c-20cb70a7679d">

**Comment by ZerOri** [comment]
> 感谢这个issue，R2S 困扰很久的问题解决，因为固件绑定的网口问题升级87以后的版本就网络出错了，今天参考了这个帖子就恢复正常了。 如果没有手工绑定网口，不是dial tcp4 XXX:XXX i/o timeout 就是 all DNS requests failed 的错误提示。
> 
> 设置方法如下： <img alt="Snipaste_2023-05-10_21-04-32" width="922" src="https://private-user-images.githubusercontent.com/2621203/237401066-293aeb29-1f49-41db-8d3a-6a10ff08bdaa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MDE5NjEsIm5iZiI6MTcxMjcwMTY2MSwicGF0aCI6Ii8yNjIxMjAzLzIzNzQwMTA2Ni0yOTNhZWIyOS0xZjQ5LTQxZGItOGQzYS02YTEwZmYwOGJkYWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDlUMjIyNzQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjZiMDYzMDlhNjlkYWEzZDRkMDgyYjBmZTc1ODM0MmM5OTY1M2JlODdhODFmNjYyZTRmYmIwM2JhOWQ2YzJjMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.T-v2cETT88u0ESgsLRjDEtMMr2TPN5bpcAHSOYJGeT0"> <img alt="Snipaste_2023-05-10_21-06-04" width="1150" src="https://private-user-images.githubusercontent.com/2621203/237401108-cbb0d2e1-b9e6-4d0f-aa25-a4745c8347ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MDE5NjEsIm5iZiI6MTcxMjcwMTY2MSwicGF0aCI6Ii8yNjIxMjAzLzIzNzQwMTEwOC1jYmIwZDJlMS1iOWU2LTRkMGYtYWEyNS1hNDc0NWM4MzQ3YWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDlUMjIyNzQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTFmYzQ3YzY5MDhkMGU3NDBiZTI5ODE4ZWM0YjM2MTAzOTU1NDAwOWFkZTBlYjJiYmM5NjY0ZDhiMDJhZjk3MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.j-H4Fcd_JNDOqQIjRTEGzzDyJmLOWc_0tyS09kme-fA"> <img alt="Snipaste_2023-05-10_21-06-38" width="776" src="https://private-user-images.githubusercontent.com/2621203/237401145-cbf575be-3aaa-4bef-ad3c-20cb70a7679d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MDE5NjEsIm5iZiI6MTcxMjcwMTY2MSwicGF0aCI6Ii8yNjIxMjAzLzIzNzQwMTE0NS1jYmY1NzViZS0zYWFhLTRiZWYtYWQzYy0yMGNiNzBhNzY3OWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDlUMjIyNzQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDE4MDVlYzA4ZTA4MmU4MzA2OGFjZTc1ODkyODkzMjdlMjFlYWZkN2E0ZmYwN2E2NGVhZmZmMzdjMWY4ZjYzMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.e9BUS-PFuTwaoCwhg0QcPUGr31IsxPYodGE_gju-DLw">

我这样设置完问题依旧，绝望

**Comment by jvuixcqm** [comment]
> > ![image](https://user-images.githubusercontent.com/42875168/235063837-c1f72bbe-54c2-47e6-b739-77723fc0c65d.png) 这两个去掉
> 
> 可以了，感谢

这俩在哪去掉啊

**Comment by vernesong** [comment]
多网口才需要选网卡，默认不会加
