### ISSUE TITLE
[Bug] Openwrt 22.03.0 Dnsmasq因Clash修改配置无法启动

### ISSUE THREAD

**Issue by Dt8333** [vernesong/OpenClash#3249]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.112-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Other

### To Reproduce

1.本地DNS劫持选择Dnsmasq
2.启动服务
3.停止服务
4.解析文件位置被错误修改为/tmp/resolv.conf.auto 而不是/tmp/resolv.conf.d/resolv.conf.auto

### Describe the Bug

OpenWRT 22.0.3 新增了ujail，修改了Dnsmasq服务的用户，解析文件路径并限制了/tmp的读写权限，导致Dnsmasq服务无法写入/tmp/resolv.conf.auto，导致启动失败。

建议增加对OpenWRT 22.0.3+版本判断，在关闭时据此修改Dnsmasq解析文件路径。

### OpenClash Log

（无需日记）
（无法上传日记，路由器会在读取日记时崩溃重启，原因不明，似乎与该插件无关）

### OpenClash Config

```shell
无
```

### Expected Behavior

在OpenWRT 22.0.3+ 停止OpenClash时Dnsmasq解析文件路径为/tmp/resolv.conf.d/resolv.conf.auto

### Screenshots

无

**Comment by Dt8333** [comment]
和#3247 #3248 应该是同一个问题

**Comment by davidu2003** [comment]
> 和#3247 应该是同一个问题

应该是，我也是22.03

**Comment by sskkcc** [comment]
一样的问题，110 111 112，这三个版本，我都有同样的问题。openclash修改了dnsmasq，每次我都需要重装dnsmasq才行。

**Comment by caliban511** [comment]
> 一样的问题，110 111 112，这三个版本，我都有同样的问题。openclash修改了dnsmasq，每次我都需要重装dnsmasq才行。

大佬，重装哪个？dnsmasq-full 还是 dnsmasq ？

**Comment by caliban511** [comment]
我都更新到 v0.45.116-beta 了，还是这个问题。

**Comment by caliban511** [comment]
麻了，我手动替换 luci-app-openclash/root/etc/init.d/openclash 这个文件，重新编译固件重刷都没用，，，这个问题到底要怎么解决啊？

**Comment by caliban511** [comment]
直接替换路由器 root/etc/init.d/openclash 这个文件，重启路由器，问题依旧，，，无语，，，

**Comment by Dt8333** [comment]
> 直接替换路由器 root/etc/init.d/openclash 这个文件，重启路由器，问题依旧，，，无语，，，
建议先临时改解析文件路径，等作者大大发新版

**Comment by caliban511** [comment]
> 

感谢回复，请问要怎么改？

**Comment by caliban511** [comment]
> > 直接替换路由器 root/etc/init.d/openclash 这个文件，重启路由器，问题依旧，，，无语，，，
> > 建议先临时改解析文件路径，等作者大大发新版

感谢回复，请问要怎么改？

**Comment by Dt8333** [comment]
> 

网络
DHCP DNS
Hosts和解析文件
把解析文件那一行删了
应用配置

这样dmsmasq应该就恢复了

**Comment by caliban511** [comment]
> > 
> 
> 网络 DHCP DNS Hosts和解析文件 把解析文件那一行删了 应用配置
> 
> 这样dmsmasq应该就恢复了

感谢回复，不过咱们的界面好像不太一样？
你用的是大雕或者天灵的代码吗？
我这个是原版openwrt，界面不一样，，，
![屏幕截图 2023-05-01 175934](https://user-images.githubusercontent.com/13557387/235438177-20098f49-63c4-4124-82dd-a7694d10e5bc.png)

**Comment by Dt8333** [comment]
> > > 
> > 
> > 
> > 网络 DHCP DNS Hosts和解析文件 把解析文件那一行删了 应用配置
> > 这样dmsmasq应该就恢复了
>

**Comment by Dt8333** [comment]
> > > 
> > 
> > 
> > 网络 DHCP DNS Hosts和解析文件 把解析文件那一行删了 应用配置
> > 这样dmsmasq应该就恢复了
> 
> 感谢回复，不过咱们的界面好像不太一样？ 你用的是大雕或者天灵的代码吗？ 我这个是原版openwrt，界面不一样，，， ![屏幕截图 2023-05-01 175934](https://user-images.githubusercontent.com/13557387/235438177-20098f49-63c4-4124-82dd-a7694d10e5bc.png)

看起来你没关OpenClash（
先把OpenClash服务停止后再操作
（或者去掉忽略解析文件的勾）

**Comment by caliban511** [comment]
> 看起来你没关OpenClash（ 先把OpenClash服务停止后再操作 （或者去掉忽略解析文件的勾）

原来如此，是每次关掉openclash后手动修改这里啊，谢谢大佬，，就先这样吧，，，

**Comment by caliban511** [comment]
> 看起来你没关OpenClash（ 先把OpenClash服务停止后再操作 （或者去掉忽略解析文件的勾）

我想了想，反正我用的就是op22.03，不像大佬那样需要考虑别的机型和版本，就干脆打开 root/etc/init.d/openclash  ，把所有 /tmp/resolv.conf.auto 都替换成 /tmp/resolv.conf.d/resolv.conf.auto ，，，这样一来，貌似就暂时不影响了，，，

**Comment by davidu2003** [comment]
> > 网络 DHCP DNS Hosts和解析文件 把解析文件那一行删了 应用配置
> > 这样dmsmasq应该就恢复了
> 
> 感谢回复，不过咱们的界面好像不太一样？ 你用的是大雕或者天灵的代码吗？ 我这个是原版openwrt，界面不一样，，， ![屏幕截图 2023-05-01 175934](https://user-images.githubusercontent.com/13557387/235438177-20098f49-63c4-4124-82dd-a7694d10e5bc.png)

升级到115或者116，关闭openclash后，在你这个界面把忽略解析文件勾掉，然后下面解析文件填入  /tmp/resolv.conf.d/resolv.conf.auto，再启动openclash，再关闭就正确了～

**Comment by caliban511** [comment]
> 升级到115或者116，关闭openclash后，在你这个界面把忽略解析文件勾掉，然后下面解析文件填入 /tmp/resolv.conf.d/resolv.conf.auto，再启动openclash，再关闭就正确了～

直接在 root/etc/init.d/openclash 里替换就一次性解决了。
