### ISSUE TITLE
[Bug] 0.45.115 启动时活动连接数飙到数千，内存占用飚到1点几G

### ISSUE THREAD

**Issue by ximiTech** [vernesong/OpenClash#3251]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.115-beta

### Bug on Environment

Lean

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

0.45.115 启动时活动连接数飙到数千，内存占用飚到1点几G

### Describe the Bug

0.45.115 启动时活动连接数飙到数千，内存占用飚到1点几G

### OpenClash Log

0.45.115 启动时活动连接数飙到数千，内存占用飚到1点几G

### Expected Behavior

0.45.115 启动时活动连接数飙到数千，内存占用飚到1点几G
0.45.114 无此问题

**Comment by vernesong** [comment]
![image](https://user-images.githubusercontent.com/42875168/235296523-63063570-964b-4de0-822d-dfa6d020c1e6.png)
动这个了？

**Comment by youngxlover** [comment]
我也是一摸一样的问题，没有动过本地ipv4绕过，两台软路由都一样。启动飙满cpu，8000+连接数，内存上g，然后开始下降，最终是可以使用的。

**Comment by vernesong** [comment]
那你看下有没有没写进去的本地网段

**Comment by ximiTech** [comment]
> ![image](https://user-images.githubusercontent.com/42875168/235296523-63063570-964b-4de0-822d-dfa6d020c1e6.png) 动这个了？

没有动这里，本地有 ipv6 网络，会不会有影响？

**Comment by vernesong** [comment]
你开下clash内核的日志，看在刷什么内容

**Comment by youngxlover** [comment]
日志显示，不断的udp高位端口互相通信，比如udp：34566端口 访问 udp 37890，一直刷。我尝试开启绕过中国大陆ip后，恢复正常。之前的版本都没有这样，这次升级115第一次碰到。最新的metacore，redir-host模式

**Comment by vernesong** [comment]
截图看下

**Comment by youngxlover** [comment]
![Uploading IMG_9289.jpeg…]()

**Comment by youngxlover** [comment]
![IMG_9290](https://user-images.githubusercontent.com/30921140/235339078-0da1327b-619f-41d3-8e40-09bba6ffe0fc.jpeg)
![IMG_9289](https://user-images.githubusercontent.com/30921140/235339088-ba0762a0-f056-48f9-af23-7aef027d3a1f.jpeg)

**Comment by youngxlover** [comment]
![IMG_9289](https://user-images.githubusercontent.com/30921140/235339168-840566de-9a36-4885-afdb-522e79d24f00.jpeg)
![IMG_9290](https://user-images.githubusercontent.com/30921140/235339171-ebb6ae7f-d995-4cca-89d6-5aa45dc63213.jpeg)

**Comment by vernesong** [comment]
这个ip是你wan的吗

**Comment by youngxlover** [comment]
是的，这个ip是我的wan

**Comment by xianren78** [comment]
我的也有这个问题

**Comment by vernesong** [comment]
试下116

**Comment by youngxlover** [comment]
更新116，问题解决，感谢大佬高速响应

**Comment by redblackbst** [comment]
> 日志显示，不断的udp高位端口互相通信，比如udp：34566端口 访问 udp 37890，一直刷。我尝试开启绕过中国大陆ip后，恢复正常。之前的版本都没有这样，这次升级115第一次碰到。最新的metacore，redir-host模式

115-117没有解决，一样的问题，只是变成WAN的ipv6 IP不停刷连接。猜测可能上次的fix，ipv6忘了处理。

**Comment by vernesong** [comment]
> > 日志显示，不断的udp高位端口互相通信，比如udp：34566端口 访问 udp 37890，一直刷。我尝试开启绕过中国大陆ip后，恢复正常。之前的版本都没有这样，这次升级115第一次碰到。最新的metacore，redir-host模式
> 
> 115-117没有解决，一样的问题，只是变成WAN的ipv6 IP不停刷连接。猜测可能上次的fix，ipv6忘了处理。

你v6接口是什么协议

**Comment by redblackbst** [comment]
> 看看这个命令的结果 ip route show table local

这是114版本正常的结果：
```
root@ImmortalWrt:~# ip route show table local
broadcast 127.0.0.0 dev lo proto kernel scope link src 127.0.0.1
local 127.0.0.0/8 dev lo proto kernel scope host src 127.0.0.1
local 127.0.0.1 dev lo proto kernel scope host src 127.0.0.1
broadcast 127.255.255.255 dev lo proto kernel scope link src 127.0.0.1
broadcast 192.168.1.0 dev eth1 proto kernel scope link src 192.168.1.5
local 192.168.1.5 dev eth1 proto kernel scope host src 192.168.1.5
broadcast 192.168.1.255 dev eth1 proto kernel scope link src 192.168.1.5
broadcast 192.168.2.0 dev br-lan proto kernel scope link src 192.168.2.1
local 192.168.2.1 dev br-lan proto kernel scope host src 192.168.2.1
broadcast 192.168.2.255 dev br-lan proto kernel scope link src 192.168.2.1
```

> 你v6接口是什么协议

![protocol](https://user-images.githubusercontent.com/14046170/236079172-2002548b-9165-4cc3-b8ea-f30f7588e4e8.png)

**Comment by redblackbst** [comment]
119版本，问题解决了，谢谢开发者。

**Comment by yellowsavant** [comment]
> 119版本，问题解决了，谢谢开发者。

老铁你们都哪来的新版本呀？明明版上目前是112还beta

**Comment by redblackbst** [comment]
> > 119版本，问题解决了，谢谢开发者。
> 
> 老铁你们都哪来的新版本呀？明明版上目前是112还beta

更新分支切换到 Developer
![Screenshot 2023-05-12 102203](https://github.com/vernesong/OpenClash/assets/14046170/26583a3a-e7c5-404f-b3f8-d485a08f821a)

**Comment by yellowsavant** [comment]
> > > 119版本，问题解决了，谢谢开发者。
> > 
> > 
> > 老铁你们都哪来的新版本呀？明明版上目前是112还beta
> 
> 更新分支切换到 Developer ![Screenshot 2023-05-12 102203](https://user-images.githubusercontent.com/14046170/237853091-26583a3a-e7c5-404f-b3f8-d485a08f821a.png)

好的非常感谢！
