### ISSUE TITLE
[Feature] nas里下载器qb需要直连，且nas其他项目需要代理，有什么好办法么？

### ISSUE THREAD

**Issue by sunr1s6** [vernesong/OpenClash#3259]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

PVE环境 OP主路由，当然也可以主+OP旁， 然后群晖nas都是同网段， 
openclsh设置 
使用的是REDIR HOST TUN 模式， 没用META内核
绕过CN  ✔
本地DNS劫持 使用DNSMASQ转发 🈲缓存  
IPV6 未勾选
1.找了很多办法，都不理想，自定义端口 走直连好像也不管用？
另外 流量控制里的 仅允许常用端口流量，勾上的话 可以让QB下载器的流量都走直连么？
黑白名单里面有一个 绕过核心的来源端口  这个是否可以 让QB下载器单独走国内呢？ 

2.绕过中国大陆 IPv4 黑名单 这个功能， 我在里面添加 bing.com 之后 启动不了openclash了。 
这里不知道需要怎样才可以使用？ 因为访问bing就直接被带到CN 了，之前有个大佬说 把绕过CN 不勾选，确实可以解决这个问题，但是所有流量都走了内核导致网速下架 CPU负载过高 不得已又勾上了， 看到这里有单独设置的确没能用成功。

感谢各位大佬的回复

### Describe the Solution

1.发现很多软件都有 socks5 http 这种方式走代理， 那么可以加个选项让SOCKS5 以及类似这种代理方式走直连么？
直连代理端口  7895 这样？ 纯个人脑洞，如果是异想天开 就当个笑话看吧。

2.想要在开启绕过CN的情况下  让单独某个网站能 正确走代理  避免出现访问不了被404 或者被引流到CN的问题。

**Comment by deuteros-gex** [comment]
你这个问题想要解决，不能指望只靠clash或openclash。
考虑用docker+macvlan的方式跑qb，此时qb所在的容器可以单独占一个ip。这样在clash端分流就很容易设置了。

**Comment by sunr1s6** [comment]
> 你这个问题想要解决，不能指望只靠clash或openclash。 考虑用docker+macvlan的方式跑qb，此时qb所在的容器可以单独占一个ip。这样在clash端分流就很容易设置了。

感谢， 然后单独把那个IP 弄到直连么？ 还是用黑名单的方法把他的IP 不代理？

**Comment by embeddedlove** [comment]
https://www.linuxtopia.org/Linux_Firewall_iptables/x4172.html 区分服务类型

**Comment by deuteros-gex** [comment]
> > 你这个问题想要解决，不能指望只靠clash或openclash。 考虑用docker+macvlan的方式跑qb，此时qb所在的容器可以单独占一个ip。这样在clash端分流就很容易设置了。
> 
> 感谢， 然后单独把那个IP 弄到直连么？ 还是用黑名单的方法把他的IP 不代理？

两种方法都可以，我更建议用黑名单，这样可以让它直接绕过clash。

**Comment by CkovMk** [comment]
我的配置和你类似，根据我的观察“仅允许常用端口流量”能够将bt流量绕过Clash。

**Comment by sunr1s6** [comment]
> 我的配置和你类似，根据我的观察“仅允许常用端口流量”能够将bt流量绕过Clash。

感谢， 我打开试了下 好像确实在 监控里没看到下载数据了。

**Comment by 991547436** [comment]
仅允许常用端口流量选项pt流量还是有可能会跑代理的，我建议是再开一个虚拟机，网关直接指向主路由
如果op就是主路由就开ip黑名单把新的虚拟机加进去，
docker我没试过独占ip，不过一个道理，可以少一个虚拟机

**Comment by XinSSS** [comment]
我自己的NAS用的是Windows系统，openclash我是把nas所在IP直接排除掉了，然后NAS系统里自己另外安装设置了cfw, 并把系统里的相关线程设置为直连

**Comment by dianqizgb** [comment]
> 我自己的NAS用的是Windows系统，openclash我是把nas所在IP直接排除掉了，然后NAS系统里自己另外安装设置了cfw, 并把系统里的相关线程设置为直连

能问一下怎么把NAS的IP排除？必须在配置文件里面加代码吗？
