### ISSUE TITLE
[Bug] DNS does not work on non-Clash networks.

### ISSUE THREAD

**Issue by TJT-JTJ** [vernesong/OpenClash#3264]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.119-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-arm64

### To Reproduce

Two LANs on one device
One proxied, one not (via white/black lists)
OpenClash installed (doesn't matter if running or not)

### Describe the Bug

The proxied network works fine with OpenClash
The non-proxied network cannot use DNS, even with Clash disabled.

This issue was worse in v112, it was partially resolved and now dnsmasq runs, but DNS still doesn't work

### OpenClash Log

No log issues

### Expected Behavior

DNS works

**Comment by vernesong** [comment]
Check the dnsmasq option, and show me the contents of the file
![image](https://github.com/vernesong/OpenClash/assets/42875168/f56d3a78-7f52-4c8e-a9e4-d89b76b29e3c)

**Comment by yyysuo** [comment]
> Check the dnsmasq option, and show me the contents of the file ![image](https://user-images.githubusercontent.com/42875168/239263639-f56d3a78-7f52-4c8e-a9e4-d89b76b29e3c.png)

这个忽略解析文件应不应该勾选呢？

**Comment by TJT-JTJ** [comment]
> Check the dnsmasq option, and show me the contents of the file 

`# Interface proxy
nameserver 223.5.5.5
nameserver 4.2.2.4
nameserver 8.8.4.4
# Interface wan
nameserver 211.136.150.66
nameserver 211.136.112.50
# Interface wan_6
nameserver 2409:801e:2000::1
nameserver 2409:801e:2000::2`

There is another interface called 'lan' which isn't here.
