### ISSUE TITLE
[Feature] 在`编辑服务器配置`页面 为`WireGuard` 添加选项

### ISSUE THREAD

**Issue by 8MiYile** [vernesong/OpenClash#3265]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

Meta作者跟我说可以在添加WireGuard节点的时候选择中继节点
```yaml
dialer-proxy："节点或策略组名称"
```
资料参考 https://clash-meta.wiki/config/proxies/wg/
设置了中继节点以后 访问顺序就是 clash -> dialer-proxy -> WireGuard
补充：细问了一下发现所有节点都可以加入这个参数 但需要更新到今天的版本

### Describe the Solution

想要在
编辑服务器这页面
当选择节点类型为WireGuard
添加一个跟添加到策略组的那个框一样 （包含节点与策略组）（只能选择一个）
名称为 `中继 节点/策略组（仅 Meta 内核）`

**Comment by 8MiYile** [comment]
配置文件带订阅且自动更新 直接改配置文件就怕是一个更新直接冲没 只能用这种方式来改。。。。

**Comment by vernesong** [comment]
覆写设置开发者选项

**Comment by labulac** [comment]
> 覆写设置开发者选项

大佬有增加proxy的示例吗？尝试在开发者选项中使用ruby add file方式加入wg的信息，重启后，未报错但配置文件中找不到加入的信息

**Comment by labulac** [comment]
已解决
