### ISSUE TITLE
[Bug] Windows显示没有联网

### ISSUE THREAD

**Issue by kougar** [vernesong/OpenClash#3269]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.112-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

从 v0.45.103-beta 升级到 v0.45.112-beta

### Describe the Bug

从 v0.45.103-beta 升级到 v0.45.112-beta 后Windows网络图标显示无网络连接，但是实际上可以上网，如果是此网络环境安装Windows 11的话会导致安装卡住，由于网络问题没法完成。

估计是升级导致DNS解析出问题了：dns.msftncsi.com
具体可以参考：https://www.bilibili.com/read/cv5292887/

### OpenClash Log

N/A

### Expected Behavior

Windows网络状态能显示联网

**Comment by vernesong** [comment]
试试nameserver-policy

**Comment by Licheng-Xu** [comment]
具体说就是 覆写设置 > DNS 设置 > Nameserver-Policy 勾选上，编辑框里填入
```
'+.msftconnecttest.com': '114.114.114.114'
'+.msftncsi.com': '114.114.114.114'
```
具体dns服务器可以填一个你习惯用的。

**Comment by hztbhtbh1** [comment]
![233297411-973b65ed-2116-432c-bb12-6e535095f2d6](https://github.com/vernesong/OpenClash/assets/104251804/3f3bc11e-2237-488b-bb3f-4db42a74718d)

**Comment by kougar** [comment]
完美解决！

**Comment by hztbhtbh1** [comment]
> 完美解决！

不一定吧，你休眠以后唤醒试试看OK不

**Comment by hztbhtbh1** [comment]
> > 完美解决！
> 
> 不确定吧，你休眠以后唤醒试试看OK不

**Comment by axcsz** [comment]
> 

我加了这个还是一样，显示小地球

**Comment by hztbhtbh1** [comment]
大佬说目前这个插件没有好办法解决这个问题（在fake-ip模式下），其它模式正常
你要是配合Adguard Home使用，可以试试以下方法（大神提供不是我，我也不会设置）：
直接用Adguard Home占用了53端口，dnsmasq的dns端口改成其它，在Adguard Home里面指定这2个域名的dns就好了。
你们谁要是设置正常了，分享一下详细步骤～～～

**Comment by Licheng-Xu** [comment]
#win10本地连接检测
+.msftconnecttest.com
+.msftncsi.com

**Comment by Licheng-Xu** [comment]
Fake-IP-Filter 打开了么？里面有没有这两条规则：
```
#win10本地连接检测
+.msftconnecttest.com
+.msftncsi.com
```
再不行的话，你用国内dns解析得到ip，填在下面的的 Hosts 里试一试。

**Comment by hztbhtbh1** [comment]
> Fake-IP-Filter 打开了么？里面有没有这两条规则：
> 
> ```
> #win10本地连接检测
> +.msftconnecttest.com
> +.msftncsi.com
> ```
> 
> 再不行的话，你用国内dns解析得到ip，填在下面的的 Hosts 里试一试。

感谢大佬，我刚才试了一下更新到最新版本v0.45.121-beta打开Fake-IP-Filter 
里面有这个地址，然后保存，重启电脑和睡眠模式唤醒后都正常使用，完美解决问题。谢谢~~~

**Comment by caliban511** [comment]
> 具体dns服务器可以填一个你习惯用的。
感谢大佬，解决了这个困扰我很久的问题。

**Comment by erbao006** [comment]
感谢大佬 我也解决了

**Comment by zzf317** [comment]
谢谢解决了我的问题
