### ISSUE TITLE
吐了呀

### ISSUE THREAD

**Issue by lloyd18** [vernesong/OpenClash#327]
下载不成功，上传查询失败
![QQ拼音截图未命名](https://user-images.githubusercontent.com/10294460/79321886-99028300-7f3e-11ea-9e9c-92f7bbf918bb.png)

**Comment by lloyd18** [comment]
试了很多遍，终于在线更新了，原来是手动下载的内核版本不对，看大小就知道，太坑了
![QQ拼音截图未命名](https://user-images.githubusercontent.com/10294460/79336977-42ee0980-7f57-11ea-9e64-4f92f89d70f2.png)

**Comment by vernesong** [comment]
你的意思是显示查询失败有歧义？

**Comment by lloyd18** [comment]
> 你的意思是显示查询失败有歧义？

关键是用不了啊

**Comment by pikachullk** [comment]
> > 你的意思是显示查询失败有歧义？
> 
> 关键是用不了啊

有可能是代理开启的状态导致的查询失败咯~每次遇到这种情况我都会点一下关闭openclash再试~第二个也是有可能代理没开启~但本地网络对github不友好...这个情况就经常遇到了...想办法开一开ssrp或者别的穿墙软件再查询会好一点

**Comment by lloyd18** [comment]
> > > 你的意思是显示查询失败有歧义？
> > 
> > 
> > 关键是用不了啊
> 
> 有可能是代理开启的状态导致的查询失败咯~每次遇到这种情况我都会点一下关闭openclash再试~第二个也是有可能代理没开启~但本地网络对github不友好...这个情况就经常遇到了...想办法开一开ssrp或者别的穿墙软件再查询会好一点

应该是客户端那个下载到本地的连接不对，因为在线更新和手动下载的内核大小不一样
