### ISSUE TITLE
[Feature] 建议增加定时启动和关闭 openclash 功能

### ISSUE THREAD

**Issue by Roller44** [vernesong/OpenClash#3272]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

当前 openclash 必须手动控制开/关，希望能够增加一个定时开关的功能。

### Describe the Solution

希望能够提供较为细粒度的定时开关策略：可以为周末和非周末的设置不同的开关时间。

**Comment by lyxhwy** [comment]
现在可以了吗?

**Comment by yjx1804** [comment]
建议 断网自动重启OpenClash
定时开关OpenClash
