### ISSUE TITLE
[Bug] 配置文件订阅后下载失败，试了好几个，都这样

### ISSUE THREAD

**Issue by coolbiubiu** [vernesong/OpenClash#3282]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.44.28-beta	

### Bug on Environment

Other

### Bug on Platform

Other

### To Reproduce

配置文件订阅后，更新配置后，配置文件下载失败

### Describe the Bug

配置文件订阅后，更新配置后，配置文件下载失败

### OpenClash Log

2023-05-18 21:14:44 错误：【config01】下载失败，请检查网络或稍后再试...
2023-05-18 21:14:44 错误：配置文件【config01】订阅失败，尝试不使用代理下载配置文件...
2023-05-18 21:14:44 开始更新配置文件【config01】...
2023-05-17 23:23:06 获取版本信息失败，请稍后再试...
2023-05-17 23:17:51 获取版本信息失败，请稍后再试...

### Expected Behavior

能下载配置文件。

### Screenshots

![image](https://github.com/vernesong/OpenClash/assets/42194590/c1aa3327-a673-4d5f-abf0-fd5c9b19295c)

**Comment by anihao** [comment]
遇到了同样的问题，请问解决了吗

**Comment by kaichii** [comment]
同样的问题
