### ISSUE TITLE
[Bug] 发现一个有趣的问题，软路由开启 OpenClash，有线AP路由器就无法获取正确的时间

### ISSUE THREAD

**Issue by sky2016cn** [vernesong/OpenClash#3283]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.121

### Bug on Environment

Lean

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

软路由开启 OpenClash，有线AP路由器就无法获取正确的时间，关闭OpenClash，就没有这个问题

### Describe the Bug

软路由开启 OpenClash，有线AP路由器就无法获取正确的时间，关闭OpenClash，就没有这个问题

### OpenClash Log

软路由开启 OpenClash，有线AP路由器就无法获取正确的时间，关闭OpenClash，就没有这个问题

### Expected Behavior

软路由开启 OpenClash，有线AP路由器就无法获取正确的时间，关闭OpenClash，就没有这个问题

**Comment by Rashhz** [comment]
是开了fakeip吗？开了fakeip filter吗

**Comment by sky2016cn** [comment]
是的

**Comment by zengxw-chn** [comment]
> 
两个点，
1.切换redis-host的话，建议清理dns
2.如果使用fake-ip,建议在dns设置中开启fake-ip filter

**Comment by sky2016cn** [comment]
已解决
