### ISSUE TITLE
有关OpenClash的自动更新之策略选择问题

### ISSUE THREAD

**Issue by jacobin** [vernesong/OpenClash#3287]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

如下图，是我：
0、因为撞墙网络卡顿，切换另一个yaml；
1、主动点击“关闭OPENCLASH”；
2、等了几分钟后；
3、再来“启动OPENCLASH”，看到的日志。

这里有两个问题：
a、执行3之后，OpenClash走到“第六步”就放弃治疗了；
b、不停的喷射“.../tmp/openclash_clast_version ... 下载失败...”的日志。

我找过本频道，问题a已经有人提出，看似到现在也没得解决，问题b是我曾经提出过的问题，也是没得解决。这次，我的issue所在是：
A、问题b是不是由“连网检查新版本”而导致的？
B、版本检查应该支持手工定制/启动/关闭。

![Snap2](https://github.com/vernesong/OpenClash/assets/5020373/457ef2ed-99bb-497a-af4d-899273226e5a)

### Describe the Solution

B、版本检查应该支持手工定制/启动/关闭，而不是每次都是强制进行版本检查

### Describe Alternatives

B、版本检查应该支持手工定制/启动/关闭。

### Additional Context

B、版本检查应该支持手工定制/启动/关闭。

**Comment by Dt8333** [comment]
如果你是OpenWRT 22.03.0+用户的话
试试清空DHCP解析文件路径后重启Dnsmasq服务
然后启用插件

0.45.121插件已经修复了错误配置导致Dnsmasq启动失败导致的无法解析主机引起的一系列问题
你可以尝试更新一下

**Comment by jacobin** [comment]
> 如果你是OpenWRT 22.03.0+用户的话 试试清空DHCP解析文件路径后重启Dnsmasq服务 然后启用插件
> 
> 0.45.121插件已经修复了错误配置导致Dnsmasq启动失败导致的无法解析主机引起的一系列问题 你可以尝试更新一下

我没用dnsmasq，因为我发现使用Dnsmasq有DNS泄漏；我直接"使用防火墙转发"。

上个版本45.112刚出来的时候我就发现它各种死相，然后我开始第一次尝试用“第三方规则集附加”，玩甩子似的碰到解决。

但是 .............................. 上面说的都不是这次问题的重点！！！
重点是：我什么都不缺，不缺核心文件、数据、脚本，等等等等，为什么做个启动非要去下载什么的openclash_clast_version 不可？

这才是重点

**Comment by Karmylr** [comment]
> 

这个是判断有没有可用更新的
