### ISSUE TITLE
[Bug] 使用“一键生成”界面添加的节点无法添加到配置文件中

### ISSUE THREAD

**Issue by davidu2003** [vernesong/OpenClash#3288]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.121-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

1. 在“一键生成”页面添加任意一个vmess节点，保存。
2. 点击“应用配置”按钮。
3. 进入“配置管理”，查看配置文件。

### Describe the Bug

新添加的节点无法写入到配置文件中，应用配置后日志中会报错找不到刚添加的节点。

### OpenClash Log

内核日志：
2023-05-20 09:55:31 level=fatal msg="Parse config error: proxy group[0]: '新加节点' not found"
2023-05-20 09:55:31 level=info msg="Start initial configuration in progress"

### Expected Behavior

能正确添加新节点。

**Comment by laozhang123456** [comment]
自建节点添加，一键生成配置文件，应用配置，报错：2023-05-21 00:21:49 错误：配置文件格式校验失败...
2023-05-21 00:21:46 错误：配置文件解析失败，【(/etc/openclash/config/config.yaml): did not find expected '-' indicator while parsing a block collection at line 2 column 3】

**Comment by laozhang123456** [comment]
trojan节点

**Comment by davidu2003** [comment]
好像是这个问题导致的 https://github.com/vernesong/OpenClash/issues/3289

**Comment by laozhang123456** [comment]
> 好像是这个问题导致的 https://github.com/vernesong/OpenClash/issues/3289

查看/openclash/config.yaml,节点信息确实没写进去

**Comment by davidu2003** [comment]
修改了下 /usr/share/openclash/yml_proxys_set.sh中的 `if [ ! -z "$multiplex" ]; then` 为`if [ "$multiplex" = "true" ]; then`，然后把这行下multiplex的几个字段的tab缩进加上了，貌似ok了。
