### ISSUE TITLE
Dashboard策略组节点异常

### ISSUE THREAD

**Issue by Tigheliu** [vernesong/OpenClash#329]
我在配置中订阅了我机场给的配置文件，然后进到dashboard准备配置clash的时候，发觉dashboard里面显示的策略组里面的节点，完全不是我的机场的节点，也无法选择

这是我机场的节点⬇️
![image](https://user-images.githubusercontent.com/5736058/79379720-e6f4a680-7f91-11ea-9ea8-e90aef1cfe0f.png)

这是dashboard显示的⬇️
![image](https://user-images.githubusercontent.com/5736058/79379829-16a3ae80-7f92-11ea-9067-811e929a5dd1.png)

 客户端版本：v0.37.3-beta

内核：v0.19.0-8-g2750c7e

**Comment by vernesong** [comment]
切换一下配置文件

**Comment by Tigheliu** [comment]
切换过两三遍，还是如此

**Comment by vernesong** [comment]
清空还原服务器与策略组管理页面的设置再订阅吧

**Comment by Tigheliu** [comment]
不好意思请问一下 如何清空还原呢

**Comment by vernesong** [comment]
节点跟策略组都删了，上面的开关停用

**Comment by Tigheliu** [comment]
我还是请教一下 如何删策略组和节点 在配置文件管理嘛？另外clash如何转发udp流量啊

**Comment by Tigheliu** [comment]
![image](https://user-images.githubusercontent.com/5736058/79609773-e727aa00-8129-11ea-8fb8-ae4bd0cface6.png)
我清空了这里的设置，删除了配置文件，重新订阅之后，我无法打开Dashboard控制面板和Yacd 控制面板，点击按钮呈现短暂灰色后又恢复蓝色，页面无任何反应

**Comment by vernesong** [comment]
> ![image](https://user-images.githubusercontent.com/5736058/79609773-e727aa00-8129-11ea-8fb8-ae4bd0cface6.png)
> 我清空了这里的设置，删除了配置文件，重新订阅之后，我无法打开Dashboard控制面板和Yacd 控制面板，点击按钮呈现短暂灰色后又恢复蓝色，页面无任何反应

能启动吗，按钮是弹窗形式，看看是不是被插件屏蔽了

**Comment by Tigheliu** [comment]
clash能启动，但是弹窗弹不出来，另外我用的MacOS Safari，没屏蔽弹窗

**Comment by Tigheliu** [comment]
我补充一下，我如果直接访问IP：9090 是可以访问到clash的配置，并且正常使用的，但是点击按钮始终是无法弹窗，我试了3-4个浏览器，这是MacOS导致的问题，还是个bug？

**Comment by vernesong** [comment]
F12仅浏览器控制台看报错
