### ISSUE TITLE
[Bug] mwan和openclash共存时，会有部分流量没经过openclash

### ISSUE THREAD

**Issue by Rashhz** [vernesong/OpenClash#3290]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.121

### Bug on Environment

Lean

### Bug on Platform

Linux-arm64

### To Reproduce

v佬，我之前提过这个issue #3046 问题已经解决了（网络能通了），但是我发现mwan和openclash的共存还是存在问题，有一部分流量还是会直接走mwan，而没流过openclash。我发现的原因是我用openclash免流，然后开了mwan之后，就会跳点很大，而不开mwan就基本不跳，感觉是有流量没走openclash

### Describe the Bug

有部分流量没有经过openclash

### OpenClash Log

无

### Expected Behavior

希望openclash能劫持到所有流量

**Comment by deuteros-gex** [comment]
怎么讲呢，多拨和openclash都是利用防火墙做流量劫持，想要共存不是说不可能，但
#301 
这个算是陈年问题了，作者应该也没什么兴趣改进，但也谈不上bug，因为设计一个兼容性足够好的透明代理框架确实挺费脑细胞的。
要么试试passwall等其它方案，要么把多拨转到另一台路由上去。
或者你足够闲的话，参考下面的项目，自己手搓一个出来。
https://github.com/zfl9/ss-tproxy

**Comment by Rashhz** [comment]
> 怎么讲呢，多拨和openclash都是利用防火墙做流量劫持，想要共存不是说不可能，但
> #301
> 这个算是陈年问题了，作者应该也没什么兴趣改进，但也谈不上bug，因为设计一个兼容性足够好的透明代理框架确实挺费脑细胞的。
> 要么试试passwall等其它方案，要么把多拨转到另一台路由上去。
> 或者你足够闲的话，参考下面的项目，自己手搓一个出来。
> https://github.com/zfl9/ss-tproxy

好的佬，我去琢磨一下
