### ISSUE TITLE
vmess ws+tls+web自建节点在未跳过证书验证时openclash中无法使用[Bug] 

### ISSUE THREAD

**Issue by Pollo3470** [vernesong/OpenClash#3291]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.121-bata

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

vmess ws+tls自建节点在openclash中无法使用，但开启跳过证书后恢复正常，该节点已正常申请Let's Encrypt证书

### Describe the Bug

相同配置文件在相同内核的CFW中自建的vmess ws+tls+web节点可以正常使用，但在openclash中无法使用，测速超时，只有跳过证书验证才能使用

### OpenClash Log

2023-05-20 22:17:51 WRN [TCP] dial failed error=dial pollochen.tech:443 error: tls: failed to verify certificate: x509: certificate signed by unknown authority proxy=🚀 节点选择 lAddr=192.168.100.159:27909 rAddr=v16m-default.akamaized.net:443 rule=DomainSuffix rulePayload=akamaized.net

### Expected Behavior

希望能够在验证证书的情况下正常使用vmess+ws+tls+web节点

**Comment by Pollo3470** [comment]
我把服务端的普通证书换成fullchain证书后恢复正常

**Comment by Direct-A** [comment]
> 相同配置文件在相同内核的CFW中自建的vmess ws+tls+web节点可以正常使用，但在openclash中无法使用，测速超时，只有跳过证书验证才能使用

🙏感谢描述，救我于水火，快整疯了都没搞明白为啥日志里总有 `tls: failed to verify certificate: x509:`。

还是希望能够在验证证书的情况下正常使用节点，不过我的机场用的是`Trojan-Plus`

**Comment by Pollo3470** [comment]
> > 相同配置文件在相同内核的CFW中自建的vmess ws+tls+web节点可以正常使用，但在openclash中无法使用，测速超时，只有跳过证书验证才能使用
> 
> 🙏感谢描述，救我于水火，快整疯了都没搞明白为啥日志里总有 `tls: failed to verify certificate: x509:`。
> 
> 还是希望能够在验证证书的情况下正常使用节点，不过我的机场用的是`Trojan-Plus`

这个估计是你的机场证书有点问题，我的换成fullchain证书是可以正常验证证书的

**Comment by LeonChiew** [comment]
请问是在哪里开跳过验证啊

**Comment by Direct-A** [comment]
> 请问是在哪里开跳过验证啊

配置订阅 -> 
![image](https://github.com/vernesong/OpenClash/assets/46991254/04d3c9ab-6008-473f-b841-acb6a701ef03)
