### ISSUE TITLE
[Feature] 是否能配置所有端口的流量都经过openclash 代理？

### ISSUE THREAD

**Issue by WeichenXu123** [vernesong/OpenClash#3294]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

是否能配置所有端口的流量都经过openclash 代理？（要求所有端口，不仅仅是80， 443 等端口）

### Describe the Solution

为了安全性考虑，是否能配置所有端口的流量都经过openclash 代理？（要求所有端口，不仅仅是80， 443 等端口）

**Comment by 991547436** [comment]
你说的是否是全局代理？

**Comment by WeichenXu123** [comment]
是的
