### ISSUE TITLE
[Bug] v0.45.112-beta升级v0.45.121-beta直接程序都没了

### ISSUE THREAD

**Issue by werran2** [vernesong/OpenClash#3298]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.121-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

点了一键更新，直接程序都没了

### Describe the Bug

菜单里都看不见

### OpenClash Log

none

### OpenClash Config

```shell
none
```

### Expected Behavior

重装了一遍还是无法启动，提示“错误：Ruby 依赖异常，无法校验配置文件，请确认ruby依赖工作正常后重试！”
又把ruby重新更新了一遍，从3.1升级到3.2，终于能用了

**Comment by Num0** [comment]
我也遇见过，升级个版本整个程序直接没了，一头雾水
