### ISSUE TITLE
有机场的Clash配置订阅链接，怎么使用第三方配置策略规则？

### ISSUE THREAD

**Issue by xpn282** [vernesong/OpenClash#330]
机场的订阅配置里的策略规则太简单了，，我想用Openclash自带的ConnersHua规则，该怎么设置？

就是说只需要机场clash配置里的节点，不用机场的策略规则，把规则换为ConnersHua规则

**Comment by WinnieCrazyUniverse** [comment]
全局设置-规则设置（访问控制）-第三方规则-ConnersHua规则
然后在全局设置-第三方规则订阅内配置一下自动订阅就好了

**Comment by xpn282** [comment]
> 全局设置-规则设置（访问控制）-第三方规则-ConnersHua规则
> 然后在全局设置-第三方规则订阅内配置一下自动订阅就好了

早就试了，没用的，提示失败，然后自动使用之前机场订阅的默认规则。

我发现除了在“ 服务器&策略组管理”里自己手动添加节点服务器，然后一键生成ConnersHua规则配置文件，这样才能成功。。
而自己手动添加节点太麻烦了
