### ISSUE TITLE
[Bug] 不会自动测延迟

### ISSUE THREAD

**Issue by Karmylr** [vernesong/OpenClash#3304]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.121-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

无论是在配置文件的url-test里填写`interval`，还是在`测速（连通性）间隔修改(s)`里设置，都不会自动测延迟

### Describe the Bug

无论是在配置文件的url-test里填写`interval`，还是在`测速（连通性）间隔修改(s)`里设置，都不会自动测延迟

### OpenClash Log

No need.

### Expected Behavior

可以自动测延迟

**Comment by vernesong** [comment]
看看配置没带引号吧

**Comment by Karmylr** [comment]
> 看看配置没带引号吧

配置文件吗，是subconverter转换出来的，`interval`这一项不带引号

**Comment by vernesong** [comment]
meta的测试有日志，可以尝试换个地址

**Comment by Karmylr** [comment]
换了连通性测试地址还是不会自动测，需要点一下按钮

**Comment by wayne0926** [comment]
> 换了连通性测试地址还是不会自动测，需要点一下按钮

请问一下你是怎么解决的？

**Comment by Karmylr** [comment]
> > 换了连通性测试地址还是不会自动测，需要点一下按钮
> 
> 请问一下你是怎么解决的？

没解决。换软件了

**Comment by wayne0926** [comment]
> > > 换了连通性测试地址还是不会自动测，需要点一下按钮
> > 
> > 
> > 请问一下你是怎么解决的？
> 
> 没解决。换软件了

好的，谢谢😂
你换成了啥

**Comment by Karmylr** [comment]
> > > > 换了连通性测试地址还是不会自动测，需要点一下按钮
> > > 
> > > 
> > > 请问一下你是怎么解决的？
> > 
> > 
> > 没解决。换软件了
> 
> 好的，谢谢😂 你换成了啥

dae

**Comment by 506500125** [comment]
我也存在这个问题,新手小白一个,每个分组都要手动点一下测速按钮才行

**Comment by Karmylr** [comment]
@506500125 我运行裸核没问题
