### ISSUE TITLE
[Bug] 使用端口转发进行一段端口或者所有端口时转发不生效

### ISSUE THREAD

**Issue by aalberrty** [vernesong/OpenClash#3307]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.121-beta

### Bug on Environment

Lean

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

使用端口转发转发到一段端口或者所有端口
端口转发不生效 链接超时

### Describe the Bug

使用端口转发进行一段端口或者所有端口时openclash并不会识别和添加该端口转发规则

### OpenClash Log

OpenClash无日志输出
![image](https://github.com/vernesong/OpenClash/assets/59857887/6e06a432-6bf9-4cf0-b5cb-47e1ec71b06f)

### OpenClash Config

```shell
config redirect
        option target 'DNAT'
        option src 'wan'
        option dest 'lan'
        option proto 'tcp udp'
        option dest_ip '192.168.50.150'
        option name 'Forward'
```

### Expected Behavior

修复后应当与设置单端口端口转发一致

**Comment by vernesong** [comment]
不支持端口范围的自动绕过设置，因为容易导致代理异常，可以使用黑名单或者开发者模式自己写防火墙规则

**Comment by aalberrty** [comment]
请问黑名单应该怎么配置呢？现版本可以让一个lan ip不走代理吗

**Comment by Se7enMuting** [comment]
![image](https://github.com/vernesong/OpenClash/assets/889925/d2abd97c-a08d-4ada-a49a-9643ca38f3f7)
我好像也遇到同样问题，所有防火墙里设置了端口范围的规则，openclash里都会有warning提示，而且实际无法转发。
关于“黑名单或者开发者模式自己写防火墙规则”能否提供一个样例或者哪里有说明文档。。。
