### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by Ucopyrightable** [vernesong/OpenClash#3309]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

怎么设置才能远程访问FakeIP模式下的NAS？
X86软路由，安装openclash，版本0.45.121，NAS接软路由
redir模式，远程访问NAS正常
切换fakeip增强模式，无法远程连接NAS，在黑白名单里，把NAS的ip加入“不走代理的WAN IP”，一样无法连接
切换fakeipTUN模式，开始几个小时正常，然后又无法访问。

### Describe the Solution

能不能针对某个设备不分配fakeip？

**Comment by Karmylr** [comment]
openclash只是个界面，这是内核的功能请求
