### ISSUE TITLE
今天凌晨3时自动更新GEOIP后，导致openclash无法启动

### ISSUE THREAD

**Issue by WinnieCrazyUniverse** [vernesong/OpenClash#331]
运行日志报错如下：
time="2020-04-16T10:49:21+08:00" level=fatal msg="Can't load mmdb: error opening database: invalid MaxMind DB file"

之后尝试手动更新GEOIP若干次均未成功，不管是否挂全局，都无法完成更新订阅。

![IMG_4778(20200416-104546)](https://user-images.githubusercontent.com/62456649/79409673-18d92d80-7fd1-11ea-9d6c-cfc3cfd2a36e.PNG)

**Comment by vernesong** [comment]
```
curl -v https://geolite.clash.dev/Country.mmdb -o /etc/openclash/Country.mmdb
```

**Comment by WinnieCrazyUniverse** [comment]
根据您的方法尝试，但是无效，后经过重装后正常使用
报错图如下
![image](https://user-images.githubusercontent.com/62456649/80165442-0af95d00-860e-11ea-8169-fe801d300a51.png)
![image](https://user-images.githubusercontent.com/62456649/80165448-1056a780-860e-11ea-82a5-fece08aea24f.png)
