### ISSUE TITLE
[Feature] 一键生成策略组配置如何实现节点组效果？

### ISSUE THREAD

**Issue by JunTsao** [vernesong/OpenClash#3310]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

我在一键生成页面中，建立了一个策略组“IPLC”，新建了一个自定义节点“HK-01”并添加进“IPLC”策略组。使用ACL4SSR FULL自动生成模板。
当我在应用配置后，在ycad与Dashboard中可看到该策略组与节点，但无法将其应用在“微软服务”、“漏网之鱼”，因为这些组选项内并没有“IPLC”.IPLC这个组作为了一个独立的组存在。
我期望这个自定义组可以添加进”油管视频“、“奈飞视频”、“微软服务”等组里面，实现与“香港节点”、“台湾节点”一样效果，请问需要做什么设置？

### Describe the Solution

无

**Comment by deuteros-gex** [comment]
一张图简单提示一下足矣
<img width="646" alt="image" src="https://github.com/vernesong/OpenClash/assets/67225583/a848c2ee-e207-4af4-9840-d9d4d31e8e7d">
不要问我这个选项从哪儿调出来的。
