### ISSUE TITLE
[Bug] 覆写设置 - 开发者选项 ruby_arr_add_file 不可用

### ISSUE THREAD

**Issue by deuteros-gex** [vernesong/OpenClash#3312]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.121

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

我在/etc/openclash/custom目录下创建了一个名为wireguard.yaml的文件，文件内容是
![image](https://github.com/vernesong/OpenClash/assets/67225583/a47b8236-d433-482f-8d19-707f16a2cc15)
然后在覆写设置 - 开发者选项中加入一行：
<img width="763" alt="image" src="https://github.com/vernesong/OpenClash/assets/67225583/b948bfd8-feb8-4152-b6c7-56dad16500a4">

`ruby_arr_add_file "$CONFIG_FILE" "['dns']['nameserver']" "0" "/etc/openclash/custom/wireguard.yaml" "['dns']['nameserver']"`

保存设置，应用设置。观察到openclash整体重启，并且启动日志中有
<img width="737" alt="image" src="https://github.com/vernesong/OpenClash/assets/67225583/f791e559-086d-47b2-862c-8a8b77c71df5">

但生成的配置文件中，上述自定义覆写并没生效。

### Describe the Bug

ruby_arr_add_file这个函数并不可用，因为同等环境下，哪怕是作者自己提供的示例也无效
![image](https://github.com/vernesong/OpenClash/assets/67225583/63cc11aa-17cc-4719-a974-7a258276c47a)

`ruby_arr_add_file "$CONFIG_FILE" "['dns']['fallback-filter']['ipcidr']" "0" "/etc/openclash/custom/openclash_custom_fallback_filter.yaml" "['fallback-filter']['ipcidr']"`
 
但形如
`ruby_arr_insert "$CONFIG_FILE" "['dns']['nameserver']" "0" "114.114.114.114"`
这种函数倒是能够生效。

为了进一步这几个函数的可用性，直接ssh进openwrt：
`. /usr/share/openclash/ruby.sh && ruby_arr_insert "/etc/openclash/myconfig.yaml" "['dns']['nameserver']" "0" "114.114.114.114"`
会发现/etc/openclash/myconfig.yaml成功被修改

但终端中直接运行
`. /usr/share/openclash/ruby.sh && ruby_arr_add_file "/etc/openclash/myconfig.yaml" "['dns']['nameserver']" "0" "/etc/openclash/custom/wireguard.yaml" "['dns']['nameserver']"`
则发现/etc/openclash/myconfig.yaml无任何变化

**总之，以上测试应该能说明ruby_arr_add_file这个函数是不工作的。**

### OpenClash Log

调试日志对这个应该没用，略。

**Comment by deuteros-gex** [comment]
顺便一说，直接ssh进openwrt，在终端中直接运行：
`. /usr/share/openclash/ruby.sh && . /lib/functions.sh && ruby_arr_insert "/etc/openclash/myconfig.yaml" "['dns']['nameserver']" "0" "114.114.114.114"`
会发现/etc/openclash/myconfig.yaml成功被修改

但终端中直接运行
. /usr/share/openclash/ruby.sh && . /lib/functions.sh && ruby_arr_add_file "/etc/openclash/myconfig.yaml" "['dns']['nameserver']" "0" "/etc/openclash/custom/wireguard.yaml" "['dns']['nameserver']"
则发现/etc/openclash/myconfig.yaml无任何变化

应该能说明ruby_arr_add_file这个函数是不工作的。

**Comment by deuteros-gex** [comment]
@vernesong 
/usr/share/openclash/ruby.sh
我也看了，临时抱佛脚学了点ruby，也实在没看懂你用ruby写的这个函数是怎么工作的。

**Comment by vernesong** [comment]
指定数组key必须存在且有值才行
![image](https://github.com/vernesong/OpenClash/assets/42875168/31773349-cd46-4d3b-993d-2b511ea1768f)

**Comment by deuteros-gex** [comment]
Tested
Working properly after the fix, thanks!

**Comment by labulac** [comment]
@deuteros-gex 我也刚好遇到了这个问题，想问一下，使用开发者选项ruby_arr_add_file函数增加wg配置至配置文件，但生成的配置文件中，上述自定义覆写并没生效，能不能帮看一下写个示例？感谢
