### ISSUE TITLE
[Feature] 请求在*仅允许常用端口流量-默认端口中增加8008端口

### ISSUE THREAD

**Issue by Oscarbyu** [vernesong/OpenClash#3317]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

你好，我想在插件设置-流量控制-*仅允许常用端口-（默认常用端口），在默认常用端口中增加8008端口，请问该如何添加，因为自定义8008之后其他端口又无法使用，所以想在默认端口中添加8008.请问如何修改谢谢，电子邮箱sniperbai@126.com

### Describe the Solution

你好，我想在插件设置-流量控制-*仅允许常用端口-（默认常用端口），在默认常用端口中增加8008端口，请问该如何添加，因为自定义8008之后其他端口又无法使用，所以想在默认端口中添加8008.请问如何修改谢谢，电子邮箱sniperbai@126.com

### Describe Alternatives

你好，我想在插件设置-流量控制-*仅允许常用端口-（默认常用端口），在默认常用端口中增加8008端口，请问该如何添加，因为自定义8008之后其他端口又无法使用，所以想在默认端口中添加8008.请问如何修改谢谢，电子邮箱sniperbai@126.com

### Additional Context

你好，我想在插件设置-流量控制-*仅允许常用端口-（默认常用端口），在默认常用端口中增加8008端口，请问该如何添加，因为自定义8008之后其他端口又无法使用，所以想在默认端口中添加8008.请问如何修改谢谢，电子邮箱sniperbai@126.com

**Comment by vernesong** [comment]
先选默认的，在选自定义

**Comment by Oscarbyu** [comment]
你好，默认的怎么添加托个端口，用什么符号隔开？要是自定义只写8008端口好像别的端口都不可用

**Comment by caliban511** [comment]
我也想知道这里怎么先选常用端口再选自定义，，，😂😂😂

**Comment by vernesong** [comment]
选完默认的再选自定义不就可以编辑了吗

**Comment by Oscarbyu** [comment]
您的意思是先选择默认常用端口，保存应用后再选择自定义端口8008。这种操作就是默认常用端口+8008端口一起了是吧？

**Comment by Oscarbyu** [comment]
您的意思是先选择默认常用端口，保存应用后再选择自定义端口8008。这种操作就是默认常用端口+8008端口一起了是吧？













在 2023-06-12 00:07:23，"vernesong" ***@***.***> 写道：

选完默认的再选自定义不就可以编辑了吗

**Comment by vernesong** [comment]
```
21 22 23 53 80 123 143 194 443 465 587 853 993 995 998 2052 2053 2082 2083 2086 2095 2096 5222 5228 5229 5230 8080 8443 8880 8888 8889

**Comment by Oscarbyu** [comment]
按您的方法以空格分开填写到自定义里边是吧？

**Comment by Oscarbyu** [comment]
您好，请问想加区间端口怎么在自定义里添加？比如49000-50000
21 22 23 53 80 123 143 49000-50000
是否是上述格式？谢谢
