### ISSUE TITLE
[Bug] openvpn服务无法连接

### ISSUE THREAD

**Issue by sxtiger** [vernesong/OpenClash#3322]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.121-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-mips64

### To Reproduce

启动openclash,opevpn客户端无法连接，关闭openclash,openVPN客户端恢复连接

### Describe the Bug

在openwrt上安装openclash,同时openwrt上安装有openvpn服务，以便在外面连接家中内网，以前使用一切正常。
openclash升级后，无法使用openvpn服务，外网无法连接至内网，关闭openclash恢复正常。

### OpenClash Log

无

### OpenClash Config

```shell
无
```

### Expected Behavior

修复

### Screenshots

无

**Comment by vernesong** [comment]
openvpn我记得是单独接口吧，你可以试试绕过相关端口的流量

**Comment by sxtiger** [comment]
> 

如何绕开？openclash不代理VPN的流量吗？那代价太大，本来openVPN的流量就是想通过openclash集中代理

**Comment by vernesong** [comment]
![image](https://github.com/vernesong/OpenClash/assets/42875168/da6b3eb4-a1ea-4005-92b3-de4508c2c7ca)
这里加一下ip

**Comment by sxtiger** [comment]
也不行，暂时退回到v0.45.47-214，现在正常了

**Comment by jt8823** [comment]
> 也不行，暂时退回到v0.45.47-214，现在正常了

我也遇到了这个问题 45.129.  有办法解决吗
