### ISSUE TITLE
[Bug] 使用Dnsmasq转发无法连接luminati服务器

### ISSUE THREAD

**Issue by hsiangyeung** [vernesong/OpenClash#3327]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v045.121-beta

### Bug on Environment

Other

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

本地DNS劫持选项-使用Dnsmasq转发

### Describe the Bug

Dnsmasq转发状态下无法正常连接luminati服务器, 通过Yacd控制面板查看规则命中了流量,但是秒断开连接,无法正常使用,切换至防火墙转发,可以正常使用,之前旧版本我记得Dnsmasq转发也可以正常使用的

### OpenClash Log

无

### Expected Behavior

默认dnsmasq转发下也能正常使用

### Screenshots

![Dnsmasq](https://github.com/vernesong/OpenClash/assets/66523548/5e635c53-7ff9-4cb4-9724-b5ddc0cb3287)

**Comment by vernesong** [comment]
这种要代理的都是远程解析的，跟本地dns没啥大关系，你看看是不是节点问题

**Comment by hsiangyeung** [comment]
> 这种要代理的都是远程解析的，跟本地dns没啥大关系，你看看是不是节点问题

节点应该没问题,尝试了其它软件,如CFW SSRP可以正常连接  目前用的防火墙转发也能连接 
比较纠结的是 貌似之前的版本 默认Dnsmasq也可以使用的

**Comment by vernesong** [comment]
只管DNS的部分怎么影响链接？要不你再试试两种模式的DNS结果有啥不同

**Comment by hsiangyeung** [comment]
> 只管DNS的部分怎么影响链接？要不你再试试两种模式的DNS结果有啥不同

已经解决,Dnsmasq转发下,启用第二 DNS 服务器,将域名填入就可以了.
