### ISSUE TITLE
[Bug] opencalsh导致snmp失效

### ISSUE THREAD

**Issue by sanqianyanyi** [vernesong/OpenClash#3329]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.121-241

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

开启openclash

### Describe the Bug

openwrt作为旁路由，在爱快开启跨三层应用，如果开启OpenClash，终端监控流量全变成了openwrt了，请问该怎么解决

### OpenClash Log

暂无

### Expected Behavior

openwrt作为旁路由，在爱快开启跨三层应用，如果开启OpenClash，终端监控虽然正常上报了设备名，但实时流量无法探测，导致ikua QOS失效。在家里使用老版本并没有这样的问题，请问怎么解决

**Comment by vernesong** [comment]
正常就是这样，你可以选择绕过国内并限制设备的国外流量
