### ISSUE TITLE
希望支持 comzyh clash tun core 

### ISSUE THREAD

**Issue by mephisX** [vernesong/OpenClash#333]
comzyh clash tun core (ctun) - (https://github.com/comzyh/clash/releases)
理由：原有的tun內核已經不支持新版的 Clash 寫法。

Clash For Windows 也有寫到
Rule/Proxy/Proxy Group写法将在未来几个版本不再兼容

**Comment by vernesong** [comment]
人家也没更新啊，在我这边是叫游戏内核
