### ISSUE TITLE
[Bug] 自定义规则根本没用

### ISSUE THREAD

**Issue by Sincejunly** [vernesong/OpenClash#3331]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.121-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-arm64

### To Reproduce

![image](https://github.com/vernesong/OpenClash/assets/96775034/36e13d21-db50-41b4-a284-e7de2017f848)

### Describe the Bug

![image](https://github.com/vernesong/OpenClash/assets/96775034/08dacb93-26a0-4023-b4b2-c04f6e0d3cd0)
![image](https://github.com/vernesong/OpenClash/assets/96775034/1d09dc93-1149-4ad5-8082-3a7971293a76)

配置文件中的示例语法根本不对，会报错，拜其所赐，总会有不该被代理网址被代理，我还不能改，想要指定的代理又没有效果，我不知道是其它的什么优先级的问题，但我觉得自定义规则应当优先级最高才对，clash for windows没有此类问题

### OpenClash Log

```
023-06-11 13:10:45 提示：开始添加自定义防火墙规则...
2023-06-11 13:10:44 提示：正在根据防火墙端口转发和防火墙通信规则添加端口绕过规则...
2023-06-11 13:10:44 提示：正在等待 TUN 接口启动...
2023-06-11 13:10:44 提示：DNS 劫持模式为 Dnsmasq 转发...
2023-06-11 13:10:44 第七步: 设置防火墙规则...
2023-06-11 13:10:39 提示：检测到配置了 TUN 内核专属功能，调用 TUN 内核启动...
2023-06-11 13:10:38 错误：OpenClash 启动失败，尝试还原第三方规则并重新启动 Clash 主程序...
```
```
2023-06-11 14:50:57 FTL [Config] parse config failed error=rules[9643] [DOMAIN-SUFFIX,google.com,纽约1] error: proxy [纽约1] not found
2023-06-11 14:50:57 INF [Config] initial compatible provider name=⛽ 剩余流量:71G
```

### Expected Behavior

正常添加使用自定义规则

**Comment by zheshifandian** [comment]
-前面不留空格

**Comment by M1A6I3L** [comment]
DOMAIN-SCRIPT 是什么？

**Comment by deuteros-gex** [comment]
没什么恶意，但你能写出DOMAIN-SCRIPT这种语句，说明要么对clash的yaml语法有误解，要么对openclash的工作机制有误解。
哪怕是示例语法也没有DOMAIN-SCRIPT这种写法啊。
我建议你详细写一写自己的思路轨迹，这样大家才好纠正你，省得这个issue里来来回回地讲几十句也不见得解决问题。

**Comment by Sincejunly** [comment]
> -前面不留空格



> 没什么恶意，但你能写出DOMAIN-SCRIPT这种语句，说明要么对clash的yaml语法有误解，要么对openclash的工作机制有误解。 哪怕是示例语法也没有DOMAIN-SCRIPT这种写法啊。 我建议你详细讲清楚自己是怎么想的，这样大家才好纠正你，省得这个issue里来来回回地讲几十句也不见得根治问题。

有没有可能示例里有DOMAIN-SUFFIX这个注释？

**Comment by Sincejunly** [comment]
> > 1. clash 不存在 DOMAIN-SCRIPT 类型的规则，有的是 DOMAIN 或 SCRIPT 类型，参考 https://dreamacro.github.io/clash/configuration/rules.html
> > 2. yaml 语法中 # 表示注释，而 - 表示列表的一项，所以应该把样例的 # 删掉，保留 -
> > 3. openclash 的自定义规则分两部分，优先匹配和候补匹配，前者优先级最高，放在最终传给 clash 核心的规则集的最前面，后者优先级最低，在最后面。当然个人觉得这个界面布局不是太好，有一点误导性。
> > 
> > ![image](https://user-images.githubusercontent.com/51705682/245078139-f0cf186b-c4be-47b1-a391-0b9668c7a1c6.png)
> 
> ![image](https://user-images.githubusercontent.com/96775034/245222217-b79d51ff-67cc-4f48-8f4e-9c22787fa0f4.png) 我之前一直都是写KEYWORD，效果随缘，上面下面都试过，我自己设置一个网址直链没效果，这网站我走代理访问不了，不走才能访问，正好撞枪口上了，其它规则都是默认的，
webui上面的规则介绍网址就是-(空格)规则，我自己也一直试，不报错了也没效果，完全按照网址介绍和注释来就报错，和我规则关键字写没写错没关系，就算规则关键字是错的只要我吧空格删了就不会报错

**Comment by Sincejunly** [comment]
> 没什么恶意，但你能写出DOMAIN-SCRIPT这种语句，说明要么对clash的yaml语法有误解，要么对openclash的工作机制有误解。 哪怕是示例语法也没有DOMAIN-SCRIPT这种写法啊。 我建议你详细讲清楚自己是怎么想的，这样大家才好纠正你，省得这个issue里来来回回地讲几十句也不见得根治问题。

![image](https://github.com/vernesong/OpenClash/assets/96775034/b79d51ff-67cc-4f48-8f4e-9c22787fa0f4)
我之前一直都是写KEYWORD，效果随缘，上面下面都试过，我自己设置一个网址直链没效果，这网站我走代理访问不了，不走才能访问，正好撞枪口上了，其它规则都是默认的，webUI和注释的教程都是错的，会导致我发的哪个错误跟关键字根本没关系

**Comment by deuteros-gex** [comment]
半夜折腾上头，分析问题的能力都没了吧。
啥叫语法对了也还是没用？
是你觉得语法对了、但自定义规则就是插不进去？
还是说自定义规则添加成功、但分流行为仍和你预期的不一致？

语法问题，给一个能用的实例参考吧。
![image](https://github.com/vernesong/OpenClash/assets/67225583/ea226985-4521-4eaf-913c-0da614a649ce)

如果语法对了，那openclash启动后新生成的配置文件里就能看到你加进去的部分：
![image](https://github.com/vernesong/OpenClash/assets/67225583/a3552c02-a93d-4338-8a35-28f4cef9d4ec)

如果自定义规则添加成功，但分流行为仍和你预期的不一致，那就不是自定义规则的毛病，再分析过就是了。

**Comment by M1A6I3L** [comment]
以防万一，还是提一句，自定义规则不是热加载的，虽然你有截启动出错的图，当我多嘴吧。

其次，非自己手搓的规则，基本都带cn的ipcidr和geoip，搞bilibili只能用优先匹配

再者，你只放自定义规则里填写的内容大家根本无法有效判断实际情况，牵扯到config和log的事情却没放config和log，要不干脆放生辰八字，大家一起算一算那一步有问题？？你用 `- DOMAIN-KEYWORD,bilibili,REJECT` 成功启动后去 `配置管理`  `OpenClash 修改后用于启动的配置文件` 找有没有有没有这一条规则。如果没有才是该在这里提issue的。

**Comment by Sincejunly** [comment]
> 半夜折腾上头，分析问题的能力都没了吧。 啥叫语法对了也还是没用？ 是你觉得语法对了、但自定义规则就是插不进去？ 还是说自定义规则添加成功、但分流行为仍和你预期的不一致？
> 
> 语法问题，给一个能用的实例参考吧。 ![image](https://user-images.githubusercontent.com/67225583/245224641-ea226985-4521-4eaf-913c-0da614a649ce.png)
> 
> 如果语法对了，那openclash启动后新生成的配置文件里就能看到你加进去的部分： ![image](https://user-images.githubusercontent.com/67225583/245225702-a3552c02-a93d-4338-8a35-28f4cef9d4ec.png)
> 
> 如果自定义规则添加成功，但分流行为仍和你预期的不一致，那就不是自定义规则的毛病，再分析过就是了。

我也不知道是不是语法不对阿，帖子里的那个回答使用后没报错了，我只能这么说，注释里的语法根本用不了，啥叫我觉得，我截图的注释里都有示例语法吧，就这样吧唉
