### ISSUE TITLE
[求助]合并订阅失败 

### ISSUE THREAD

**Issue by psumhm** [vernesong/OpenClash#3336]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.121-beta

### Bug on Environment

Lean

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

两个不同机场的clash订阅链接单独订阅可以订阅成功，然后我按照合并订阅的说明将这两个订阅链接放在一个订阅里，两个地址中间用 | 分隔，并且启动了在线订阅转换，配置订阅失败。是还需要设置什么吗？

### Describe the Bug

无

### OpenClash Log

如图：
![微信图片_20230614085539](https://github.com/vernesong/OpenClash/assets/49806324/728bc2cf-1c4a-4d70-8b7c-24ce741a08e4)
![微信图片_20230614085544](https://github.com/vernesong/OpenClash/assets/49806324/6cacffb8-7ddb-4fd9-9f4b-66ff14eaaa03)

### Expected Behavior

无

**Comment by M1A6I3L** [comment]
下载失败，网不好吧。
多换几个订阅转换服务地址试一下呗

**Comment by vernesong** [comment]
用回车试试

**Comment by psumhm** [comment]
> 用回车试试

刚试了，回车让两个链接上下行，也是同样的错误提示。

**Comment by M1A6I3L** [comment]
那就用在线的看一下 https://sub.dler.io 看是什么情况
我用的机场禁用其他的订阅转换（其实就是把知名度比较高的拉黑名单了，自建的不影响），不知道你是不是这个情况。

**Comment by psumhm** [comment]
> 那就用在线的看一下 https://sub.dler.io https://acl4ssr-sub.github.io 看是什么情况 我用的机场禁用其他的订阅转换（其实就是把知名度比较高的拉黑名单了，自建的不影响），不知道你是不是这个情况。 ![a](https://user-images.githubusercontent.com/58336295/245975238-3631ed59-06f0-4d5d-b52b-25643ab9a4f0.jpg)
The following link doesn't contain any valid node info: https://api.……………… 也是这个提示。

**Comment by M1A6I3L** [comment]
你两个链接分别订阅试下，看是哪个机场禁止订阅转换
然后找对应的机场主问问有没有机场自建的订阅转换

**Comment by M1A6I3L** [comment]
对了，还有一种可能性，机场有提供订阅转换专用链接，不用这个链接也没法转换。
我还有个机场就是这种情况，看见你这个api开头的订阅我突然想起来的，V开头，没准同一家。

**Comment by psumhm** [comment]
> 对了，还有一种可能性，机场有提供订阅转换专用链接，不用这个链接也没法转换。 我还有个机场就是这种情况，看见你这个api开头的订阅我突然想起来的，V开头，没准同一家。

非常感谢，确实是其中一家机场不支持在线订阅转换。我已联系机场主看是否能提供支持在线订阅转换的链接。
