### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by iknowzxc** [vernesong/OpenClash#3339]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.121beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-arm64

### To Reproduce

不定时出现内核崩溃，没有观察到特别的触发条件

### Describe the Bug

2023-06-14 22:21:49 守护程序：检测到 Clash 内核崩溃，重启中...
	github.com/Dreamacro/clash/listener/stack/system/system.go:59 +0x1dc
created by github.com/Dreamacro/clash/listener/stack/system.(*System).Start
	github.com/Dreamacro/clash/listener/stack/system/system.go:79 +0x11c
github.com/Dreamacro/clash/listener/stack/system.(*System).Start.func1()
	github.com/Dreamacro/clash/listener/stack/system/system.go:207 +0x600
github.com/Dreamacro/clash/listener/stack/system.(*System).handleTCPv4(0x40004c2090?, {0x4000518000?, 0x10cc?, 0x8000?})
	github.com/Dreamacro/clash/listener/stack/system/tcpip/ip.go:32
github.com/Dreamacro/clash/listener/stack/system/tcpip.IPv4Packet.Payload(...)
goroutine 58 [running]:
panic: runtime error: slice bounds out of range [:32820] with capacity 32768

### OpenClash Log

OpenClash 调试日志

生成时间: 2023-06-14 22:26:01
插件版本: 
隐私提示: 上传此日志前请注意检查、屏蔽公网IP、节点、密码等相关敏感信息

```

#===================== 系统信息 =====================#

主机型号: FriendlyElec NanoPi R2S
固件版本: OpenWrt 22.03.2 10.19.2022
LuCI版本: 
内核版本: 5.15.74
处理器架构: 

#此项有值时,如不使用IPv6,建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: 

#此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 127.0.0.1#7874

#===================== 依赖检查 =====================#

dnsmasq-full: 未安装
coreutils: 未安装
coreutils-nohup: 未安装
bash: 未安装
curl: 未安装
ca-certificates: 未安装
ipset: 未安装
ip-full: 未安装
libcap: 未安装
libcap-bin: 未安装
ruby: 未安装
ruby-yaml: 未安装
ruby-psych: 未安装
ruby-pstore: 未安装
kmod-tun(TUN模式): 未安装
luci-compat(Luci >= 19.07): 未安装
kmod-inet-diag(PROCESS-NAME): 未安装
unzip: 未安装
iptables-mod-tproxy: 未安装
kmod-ipt-tproxy: 未安装
iptables-mod-extra: 未安装
kmod-ipt-extra: 未安装
kmod-ipt-nat: 已安装

#===================== 内核检查 =====================#

运行状态: 运行中
进程pid: 15938
运行权限: 15938: cap_dac_override,cap_net_bind_service,cap_net_admin,cap_net_raw,cap_sys_ptrace,cap_sys_resource=eip
运行用户: nobody
已选择的架构: linux-armv8

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 2022.06.19-13-ga45638d
Tun内核文件: 存在
Tun内核运行权限: 正常

Dev内核版本: v1.11.0-7-g5497ada
Dev内核文件: 存在
Dev内核运行权限: 正常

Meta内核版本: 
Meta内核文件: 不存在
Meta内核运行权限: 否

#===================== 插件设置 =====================#

当前配置文件: /etc/openclash/config/flower.yaml
启动配置文件: /etc/openclash/flower.yaml
运行模式: fake-ip-tun
默认代理模式: rule
UDP流量转发(tproxy): 停用
DNS劫持: 启用
自定义DNS: 停用
IPV6代理: 停用
IPV6-DNS解析: 停用
禁用Dnsmasq缓存: 停用
自定义规则: 启用
仅允许内网: 启用
仅代理命中规则流量: 停用
仅允许常用端口流量: 停用
绕过中国大陆IP: 停用
DNS远程解析: 启用
路由本机代理: 启用

#启动异常时建议关闭此项后重试
混合节点: 停用
保留配置: 停用

#启动异常时建议关闭此项后重试
第三方规则: 停用

#===================== 自定义规则 一 =====================#
script:
##  shortcuts:
##    Notice: The core timezone is UTC
##    CST 20:00-24:00 = time.now().hour > 12 and time.now().hour < 16
##    内核时区为UTC,故以下time.now()函数的取值需要根据本地时区进行转换
##    北京时间(CST) 20:00-24:00 = time.now().hour > 12 and time.now().hour < 16
##    quic: network == 'udp' and dst_port == 443 and (geoip(resolve_ip(host)) != 'CN' or geoip(dst_ip) != 'CN')
##    time-limit: in_cidr(src_ip,'192.168.1.2/32') and time.now().hour < 20 or time.now().hour > 21
##    time-limit: src_ip == '192.168.1.2' and time.now().hour < 20 or time.now().hour > 21

##  code: |
##    def main(ctx, metadata):
##        directkeywordlist = ["baidu"]
##        for directkeyword in directkeywordlist:
##          if directkeyword in metadata["host"]:
##            ctx.log('[Script] matched keyword %s use direct' % directkeyword)
##            return "DIRECT"

rules:

##- DOMAIN-SUFFIX, op.supes.top, DIRECT
##- SCRIPT,quic,REJECT #shortcuts rule
##- SCRIPT,time-limit,REJECT #shortcuts rule

##- PROCESS-NAME,curl,DIRECT #匹配路由自身进程(curl直连)
##- DOMAIN-SUFFIX,google.com,Proxy #匹配域名后缀(交由Proxy代理服务器组)
##- DOMAIN-KEYWORD,google,Proxy #匹配域名关键字(交由Proxy代理服务器组)
##- DOMAIN,google.com,Proxy #匹配域名(交由Proxy代理服务器组)
##- DOMAIN-SUFFIX,ad.com,REJECT #匹配域名后缀(拒绝)
##- IP-CIDR,127.0.0.0/8,DIRECT #匹配数据目标IP(直连)
##- SRC-IP-CIDR,192.168.1.201/32,DIRECT #匹配数据发起IP(直连)
##- DST-PORT,80,DIRECT #匹配数据目标端口(直连)
##- SRC-PORT,7777,DIRECT #匹配数据源端口(直连)

##排序在上的规则优先生效,如添加（去除规则前的#号）：
##IP段：192.168.1.2-192.168.1.200 直连
##- SRC-IP-CIDR,192.168.1.2/31,DIRECT
##- SRC-IP-CIDR,192.168.1.4/30,DIRECT
##- SRC-IP-CIDR,192.168.1.8/29,DIRECT
##- SRC-IP-CIDR,192.168.1.16/28,DIRECT
##- SRC-IP-CIDR,192.168.1.32/27,DIRECT
##- SRC-IP-CIDR,192.168.1.64/26,DIRECT
##- SRC-IP-CIDR,192.168.1.128/26,DIRECT
##- SRC-IP-CIDR,192.168.1.192/29,DIRECT
##- SRC-IP-CIDR,192.168.1.200/32,DIRECT

##IP段：192.168.1.202-192.168.1.255 直连
##- SRC-IP-CIDR,192.168.1.202/31,DIRECT
##- SRC-IP-CIDR,192.168.1.204/30,DIRECT
##- SRC-IP-CIDR,192.168.1.208/28,DIRECT
##- SRC-IP-CIDR,192.168.1.224/27,DIRECT

##此时IP为192.168.1.1和192.168.1.201的客户端流量走代理（策略），其余客户端不走代理
##因为Fake-IP模式下，IP地址为192.168.1.1的路由器自身流量可走代理（策略），所以需要排除

##仅设置路由器自身直连：
##- SRC-IP-CIDR,192.168.1.1/32,DIRECT
##- SRC-IP-CIDR,198.18.0.1/32,DIRECT

##DDNS
##- DOMAIN-SUFFIX,checkip.dyndns.org,DIRECT
##- DOMAIN-SUFFIX,checkipv6.dyndns.org,DIRECT
##- DOMAIN-SUFFIX,checkip.synology.com,DIRECT
##- DOMAIN-SUFFIX,ifconfig.co,DIRECT
##- DOMAIN-SUFFIX,api.myip.com,DIRECT
##- DOMAIN-SUFFIX,ip-api.com,DIRECT
##- DOMAIN-SUFFIX,ipapi.co,DIRECT
##- DOMAIN-SUFFIX,ip6.seeip.org,DIRECT
##- DOMAIN-SUFFIX,members.3322.org,DIRECT

##在线IP段转CIDR地址：http://ip2cidr.com
#===================== 自定义规则 二 =====================#
script:
##  shortcuts:
##    common_port: dst_port not in [21, 22, 23, 53, 80, 123, 143, 194, 443, 465, 587, 853, 993, 995, 998, 2052, 2053, 2082, 2083, 2086, 2095, 2096, 5222, 5228, 5229, 5230, 8080, 8443, 8880, 8888, 8889]

##  code: |
##    def main(ctx, metadata):
##        directkeywordlist = ["baidu"]
##        for directkeyword in directkeywordlist:
##          if directkeyword in metadata["host"]:
##            ctx.log('[Script] matched keyword %s use direct' % directkeyword)
##            return "DIRECT"

rules:
##- SCRIPT,common_port,DIRECT #shortcuts rule

##- DOMAIN-SUFFIX,google.com,Proxy #匹配域名后缀(交由Proxy代理服务器组)
##- DOMAIN-KEYWORD,google,Proxy #匹配域名关键字(交由Proxy代理服务器组)
##- DOMAIN,google.com,Proxy #匹配域名(交由Proxy代理服务器组)
##- DOMAIN-SUFFIX,ad.com,REJECT #匹配域名后缀(拒绝)
##- IP-CIDR,127.0.0.0/8,DIRECT #匹配数据目标IP(直连)
##- SRC-IP-CIDR,192.168.1.201/32,DIRECT #匹配数据发起IP(直连)
##- DST-PORT,80,DIRECT #匹配数据目标端口(直连)
##- SRC-PORT,7777,DIRECT #匹配数据源端口(直连)

#===================== 配置文件 =====================#

......

### OpenClash Config

_No response_

### Expected Behavior

希望能帮忙定位或规避掉bug

### Screenshots

_No response_

**Comment by iknowzxc** [comment]
2023-06-15 01:25:11 守护程序：检测到 Clash 内核崩溃，重启中...
	github.com/Dreamacro/clash/listener/stack/system/system.go:59 +0x1dc
created by github.com/Dreamacro/clash/listener/stack/system.(*System).Start
	github.com/Dreamacro/clash/listener/stack/system/system.go:79 +0x11c
github.com/Dreamacro/clash/listener/stack/system.(*System).Start.func1()
	github.com/Dreamacro/clash/listener/stack/system/system.go:207 +0x600
github.com/Dreamacro/clash/listener/stack/system.(*System).handleTCPv4(0x40001c6090?, {0x4000556000?, 0x28?, 0x8000?})
	github.com/Dreamacro/clash/listener/stack/system/tcpip/ip.go:32
github.com/Dreamacro/clash/listener/stack/system/tcpip.IPv4Packet.Payload(...)
goroutine 48 [running]:
panic: runtime error: slice bounds out of range [:32820] with capacity 32768
2023-06-15 01:24:08 守护程序：检测到 Clash 内核崩溃，重启中...
	github.com/Dreamacro/clash/listener/stack/system/system.go:59 +0x1dc
created by github.com/Dreamacro/clash/listener/stack/system.(*System).Start
	github.com/Dreamacro/clash/listener/stack/system/system.go:79 +0x11c
github.com/Dreamacro/clash/listener/stack/system.(*System).Start.func1()
	github.com/Dreamacro/clash/listener/stack/system/system.go:207 +0x600
github.com/Dreamacro/clash/listener/stack/system.(*System).handleTCPv4(0x4000179830?, {0x4000554000?, 0x28?, 0x8000?})
	github.com/Dreamacro/clash/listener/stack/system/tcpip/ip.go:32
github.com/Dreamacro/clash/listener/stack/system/tcpip.IPv4Packet.Payload(...)
goroutine 28 [running]:
panic: runtime error: slice bounds out of range [:32820] with capacity 32768
2023-06-15 01:09:00 守护程序：检测到 Clash 内核崩溃，重启中...
	github.com/Dreamacro/clash/listener/stack/system/system.go:59 +0x1dc
created by github.com/Dreamacro/clash/listener/stack/system.(*System).Start
	github.com/Dreamacro/clash/listener/stack/system/system.go:79 +0x11c
github.com/Dreamacro/clash/listener/stack/system.(*System).Start.func1()
	github.com/Dreamacro/clash/listener/stack/system/system.go:207 +0x600
github.com/Dreamacro/clash/listener/stack/system.(*System).handleTCPv4(0x40004be360?, {0x4000526000?, 0x10cc?, 0x8000?})
	github.com/Dreamacro/clash/listener/stack/system/tcpip/ip.go:32
github.com/Dreamacro/clash/listener/stack/system/tcpip.IPv4Packet.Payload(...)
goroutine 54 [running]:
panic: runtime error: slice bounds out of range [:32820] with capacity 32768
2023-06-15 00:53:53 守护程序：检测到 Clash 内核崩溃，重启中...
	github.com/Dreamacro/clash/listener/stack/system/system.go:59 +0x1dc
created by github.com/Dreamacro/clash/listener/stack/system.(*System).Start
	github.com/Dreamacro/clash/listener/stack/system/system.go:79 +0x11c
github.com/Dreamacro/clash/listener/stack/system.(*System).Start.func1()
	github.com/Dreamacro/clash/listener/stack/system/system.go:207 +0x600
github.com/Dreamacro/clash/listener/stack/system.(*System).handleTCPv4(0x40001c01b0?, {0x40001d6000?, 0xcbf?, 0x8000?})
	github.com/Dreamacro/clash/listener/stack/system/tcpip/ip.go:32
github.com/Dreamacro/clash/listener/stack/system/tcpip.IPv4Packet.Payload(...)
goroutine 21 [running]:
panic: runtime error: slice bounds out of range [:32820] with capacity 32768
2023-06-15 00:23:41 守护程序：检测到 Clash 内核崩溃，重启中...
	github.com/Dreamacro/clash/listener/stack/system/system.go:59 +0x1dc
created by github.com/Dreamacro/clash/listener/stack/system.(*System).Start
	github.com/Dreamacro/clash/listener/stack/system/system.go:79 +0x11c
github.com/Dreamacro/clash/listener/stack/system.(*System).Start.func1()
	github.com/Dreamacro/clash/listener/stack/system/system.go:207 +0x600
github.com/Dreamacro/clash/listener/stack/system.(*System).handleTCPv4(0x400022e2d0?, {0x4000244000?, 0x17ce?, 0x8000?})
	github.com/Dreamacro/clash/listener/stack/system/tcpip/ip.go:32
github.com/Dreamacro/clash/listener/stack/system/tcpip.IPv4Packet.Payload(...)
goroutine 65 [running]:
panic: runtime error: slice bounds out of range [:32820] with capacity 32768
2023-06-15 00:22:38 守护程序：检测到 Clash 内核崩溃，重启中...
	github.com/Dreamacro/clash/listener/stack/system/system.go:59 +0x1dc
created by github.com/Dreamacro/clash/listener/stack/system.(*System).Start
	github.com/Dreamacro/clash/listener/stack/system/system.go:79 +0x11c
github.com/Dreamacro/clash/listener/stack/system.(*System).Start.func1()
	github.com/Dreamacro/clash/listener/stack/system/system.go:207 +0x600
github.com/Dreamacro/clash/listener/stack/system.(*System).handleTCPv4(0x400019e240?, {0x40001be000?, 0x28?, 0x8000?})
	github.com/Dreamacro/clash/listener/stack/system/tcpip/ip.go:32
github.com/Dreamacro/clash/listener/stack/system/tcpip.IPv4Packet.Payload(...)
goroutine 9 [running]:
panic: runtime error: slice bounds out of range [:32820] with capacity 32768
2023-06-14 23:38:21 守护程序：检测到 Clash 内核崩溃，重启中...
	github.com/Dreamacro/clash/listener/stack/system/system.go:59 +0x1dc
created by github.com/Dreamacro/clash/listener/stack/system.(*System).Start
	github.com/Dreamacro/clash/listener/stack/system/system.go:79 +0x11c
github.com/Dreamacro/clash/listener/stack/system.(*System).Start.func1()
	github.com/Dreamacro/clash/listener/stack/system/system.go:207 +0x600
github.com/Dreamacro/clash/listener/stack/system.(*System).handleTCPv4(0x400019a000?, {0x40001a2000?, 0x1e1?, 0x8000?})
	github.com/Dreamacro/clash/listener/stack/system/tcpip/ip.go:32
github.com/Dreamacro/clash/listener/stack/system/tcpip.IPv4Packet.Payload(...)
goroutine 5 [running]:
panic: runtime error: slice bounds out of range [:32820] with capacity 32768
2023-06-14 23:37:18 守护程序：检测到 Clash 内核崩溃，重启中...
	github.com/Dreamacro/clash/listener/stack/system/system.go:59 +0x1dc
created by github.com/Dreamacro/clash/listener/stack/system.(*System).Start
	github.com/Dreamacro/clash/listener/stack/system/system.go:79 +0x11c
github.com/Dreamacro/clash/listener/stack/system.(*System).Start.func1()
	github.com/Dreamacro/clash/listener/stack/system/system.go:207 +0x600
github.com/Dreamacro/clash/listener/stack/system.(*System).handleTCPv4(0x40004bc000?, {0x40004ca000?, 0x34?, 0x8000?})
	github.com/Dreamacro/clash/listener/stack/system/tcpip/ip.go:32
github.com/Dreamacro/clash/listener/stack/system/tcpip.IPv4Packet.Payload(...)
goroutine 49 [running]:
panic: runtime error: slice bounds out of range [:32820] with capacity 32768
2023-06-14 23:22:11 守护程序：检测到 Clash 内核崩溃，重启中...
	github.com/Dreamacro/clash/listener/stack/system/system.go:59 +0x1dc
created by github.com/Dreamacro/clash/listener/stack/system.(*System).Start
	github.com/Dreamacro/clash/listener/stack/system/system.go:79 +0x11c
github.com/Dreamacro/clash/listener/stack/system.(*System).Start.func1()
	github.com/Dreamacro/clash/listener/stack/system/system.go:207 +0x600
github.com/Dreamacro/clash/listener/stack/system.(*System).handleTCPv4(0x400023a000?, {0x4000246000?, 0x34?, 0x8000?})
	github.com/Dreamacro/clash/listener/stack/system/tcpip/ip.go:32
github.com/Dreamacro/clash/listener/stack/system/tcpip.IPv4Packet.Payload(...)
goroutine 49 [running]:
panic: runtime error: slice bounds out of range [:32820] with capacity 32768
...



昨晚睡觉时的log

**Comment by jingfengLu** [comment]
同样是升级后内核崩溃，据我观察好像是内存申请的问题，原来旧版本内存一般就几十M，升级后一启动内存就不断申请变大，CPU负载很高，然后就崩溃了。

**Comment by deuteros-gex** [comment]
duplicate of #3188 

> Tun内核版本: 2022.06.19-13-ga45638d
> Dev内核版本: v1.11.0-7-g5497ada

先尝试更新内核版本吧，现在的太旧了。

**Comment by iknowzxc** [comment]
> duplicate of #3188
> 
> > Tun内核版本: 2022.06.19-13-ga45638d
> > Dev内核版本: v1.11.0-7-g5497ada
> 
> 先尝试更新内核版本吧，现在的太旧了。

请问最新的内核在哪里下载，这个页面上TUN内核最新只到2022.06.19
https://github.com/vernesong/OpenClash/releases/tag/TUN-Premium

**Comment by deuteros-gex** [comment]
https://github.com/Dreamacro/clash/releases
https://github.com/Dreamacro/clash/releases/tag/premium

**Comment by iknowzxc** [comment]
> https://github.com/Dreamacro/clash/releases https://github.com/Dreamacro/clash/releases/tag/premium

感谢~

**Comment by iknowzxc** [comment]
> https://github.com/Dreamacro/clash/releases https://github.com/Dreamacro/clash/releases/tag/premium

再请问一下，这里的内核是不是只需要下载premium就可以，premium包含了tun的功能？

**Comment by deuteros-gex** [comment]
> > https://github.com/Dreamacro/clash/releases https://github.com/Dreamacro/clash/releases/tag/premium
> 
> 再请问一下，这里的内核是不是只需要下载premium就可以，premium包含了tun的功能？

tun是早期叫法，现在上游改叫premium了，但openclash一直沿用了tun的叫法。

**Comment by iknowzxc** [comment]
> 沿

3Q

**Comment by iknowzxc** [comment]
> 同样是升级45.121后内核崩溃，据我观察好像是内存申请的问题，原来旧版本内存一般就几十M，升级后一启动内存就不断申请变大，CPU负载很高，然后就崩溃了。现在回退到45.112后一晚上没出现这个问题。

请问用的是哪个内核版本，我也出现了同样的情况，回退opeclash后依旧

**Comment by deuteros-gex** [comment]
> > 同样是升级45.121后内核崩溃，据我观察好像是内存申请的问题，原来旧版本内存一般就几十M，升级后一启动内存就不断申请变大，CPU负载很高，然后就崩溃了。现在回退到45.112后一晚上没出现这个问题。
> 
> 请问用的是哪个内核（/etc/openclash/core/clash, /etc/openclash/core/clash_tun）版本，我也出现了同样的情况，回退opeclash后依旧

 #3188 的问题我自己最后只是靠`换官方openwrt固件、只装需要的包`这种和稀泥的方式绕开了，也不算正面解决。

现在既然内核更新也不管用的话，讲真这就不算openclash的问题了。
可以考虑把错误日志贴到上游项目里去问问看，模仿Dreamacro/clash#2524

**Comment by iknowzxc** [comment]
> > > 同样是升级45.121后内核崩溃，据我观察好像是内存申请的问题，原来旧版本内存一般就几十M，升级后一启动内存就不断申请变大，CPU负载很高，然后就崩溃了。现在回退到45.112后一晚上没出现这个问题。
> > 
> > 
> > 请问用的是哪个内核（/etc/openclash/core/clash, /etc/openclash/core/clash_tun）版本，我也出现了同样的情况，回退opeclash后依旧
> 
> #3188 的问题我自己最后只是靠`换官方openwrt固件、只装需要的包`这种和稀泥的方式绕开了，也不算正面解决。
> 
> 讲真，个人感觉这就不算openclash的问题了，毕竟是内核在报错。 可以带着你的配置文件和错误日志，到上游项目里去问问看，模仿[Dreamacro/clash#2524](https://github.com/Dreamacro/clash/issues/2524)

好滴

**Comment by iknowzxc** [comment]
> > > 同样是升级45.121后内核崩溃，据我观察好像是内存申请的问题，原来旧版本内存一般就几十M，升级后一启动内存就不断申请变大，CPU负载很高，然后就崩溃了。现在回退到45.112后一晚上没出现这个问题。
> > 
> > 
> > 请问用的是哪个内核（/etc/openclash/core/clash, /etc/openclash/core/clash_tun）版本，我也出现了同样的情况，回退opeclash后依旧
> 
> #3188 的问题我自己最后只是靠`换官方openwrt固件、只装需要的包`这种和稀泥的方式绕开了，也不算正面解决。
> 
> 讲真，个人感觉这就不算openclash的问题了，毕竟是内核在报错。 可以带着你的配置文件和错误日志，到上游项目里去问问看，模仿[Dreamacro/clash#2524](https://github.com/Dreamacro/clash/issues/2524)

顺便问下截图中这个4000M的虚拟内存占用应该是不正常的吧？
