### ISSUE TITLE
[bug] openwrt开启openclash，通过修改自定义规则，解决插件aliddns不能获取真实ip。

### ISSUE THREAD

**Issue by W-Haooooo** [vernesong/OpenClash#3343]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.121-beta

### Bug on Environment

Lean

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

开启openclash，无论是Redir-Host ，还是Fake-IP 模式，openwrt插件aliddns有时会获取到代理后的国外ip地址，导致ddns地址更新错误。
通过查看aliddns的程序，发现是shell脚本，获取ip由以下方式实现：
```
ntelnetip() {
	tmp_ip=`curl -sL --connect-timeout 3 members.3322.org/dyndns/getip`
	if [ "Z$tmp_ip" == "Z" ]; then
		tmp_ip=`curl -sL --connect-timeout 3   api-ipv4.ip.sb/ip`
	fi
	if [ "Z$tmp_ip" == "Z" ]; then
		tmp_ip=`curl -sL --connect-timeout 3 v4.myip.la`
	fi
	if [ "Z$tmp_ip" == "Z" ]; then
		tmp_ip=`curl -sL --connect-timeout 3 whatismyip.akamai.com`
	fi
	echo -n $tmp_ip
}
```
因为其中几个网址会自动走代理，所以会获取到代理的ip。
我把以上网址添加到自定义规则，使其direct。且查看通过OpenClash 修改后用于启动的配置文件，验证规则已经加入配置文件。但是不管使用DOMAIN，还是DOMAIN-KEYWORD，网址还是走代理。
然后，我尝试把以上规则删除，新加一条规则：**PROCESS-NAME,curl,DIRECT**，测试后问题解决。

### Describe the Bug

ddns不能获取真实ip，部分自定义规则不生效。

### OpenClash Log

暂无

### Expected Behavior

自定义规则优先匹配，DOMAIN,DOMAIN-KEYWORD等方式可以生效。

**Comment by anjue39** [comment]
我也遇到同样花生壳ddns无法获取真实ip被fake ip模式劫持的问题
