### ISSUE TITLE
[Feature] 一键生成(配置)兼容Meta内核的TUICv5配置

### ISSUE THREAD

**Issue by kunger97** [vernesong/OpenClash#3347]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

Meta内核已经支持TUICv5，新增配置选项:
uuid: 
password: 
目前openclash不支持这两个配置选项，会导致启动服务时覆盖手动添加的TUICv5的节点

### Describe the Solution

一键生成种新增这两个配置项，生成配置文件，读取配置文件支持这两个配置项

### Additional Context

https://wiki.metacubex.one/config/proxies/tuic/

**Comment by zw83173060** [comment]
vless://e7ac956c-2b1e-411c-bbe7-232a84a2e03f@23.105.209.38:443?encryption=none&security=reality&flow=xtls-rprx-vision&type=tcp&sni=www.paypal.com&pbk=uswAZ6cunlGepvrp_ymgaRKGJQfwuq83wQv9Xse681o&fp=ios#233boy-reality-23.105.209.38

vless://4461f8f2-c89c-41ae-ab71-6aa8fae8372b@38.47.125.167:443?encryption=none&security=reality&flow=xtls-rprx-vision&type=tcp&sni=aws.amazon.com&pbk=-C6EkVi7KO4O82eLnegeWMutqWO8bbjpG8rjVoQy2VQ&fp=ios#233boy-reality-38.47.125.167
