### ISSUE TITLE
[Bug] enable_redirect_dns 忘记考虑 lan_ac_black_ip6s

### ISSUE THREAD

**Issue by ghost** [vernesong/OpenClash#3348]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

 v0.45.124-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-arm64

### To Reproduce

打开 enable_redirect_dns 并设置 lan_ac_black_ips 和 lan_ac_black_ip6s

### Describe the Bug

https://github.com/vernesong/OpenClash/blob/9ee0f02ed7615a62f960c9ee2f951dd1b47e2411/luci-app-openclash/root/etc/init.d/openclash#L1518

enable_redirect_dns  忘记考虑 lan_ac_black_ip6s，导致black list模式下内网用ipv6发出的dns请求未被正确处理。

### OpenClash Log

无关。

### Expected Behavior

对ipv6和ipv4分别处理。

**Comment by deuteros-gex** [comment]
ipv6是允许独立开闭的，不可能跟ipv4部分写到一起啊。
https://github.com/vernesong/OpenClash/blob/9ee0f02ed7615a62f960c9ee2f951dd1b47e2411/luci-app-openclash/root/etc/init.d/openclash#L1808
这不就是你要的东西吗。

**Comment by deuteros-gex** [comment]
> 似乎这行完全没执行
是因为检测到v4已经设置了一次所以自动跳过了？

别**似乎**啊，shell读不明白的话，那直接看结果不就好了。
nft list table inet fw4把整个防火墙的状态输出到一个文件，然后把文件传到github来
