### ISSUE TITLE
[Bug] 最新版本meta内核时不时在低负载下吃满cpu

### ISSUE THREAD

**Issue by RhythmNz** [vernesong/OpenClash#3353]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.121-beta

### Bug on Environment

Other

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

运行clash后随机出现

### Describe the Bug

最新版本meta内核时不时在低负载下吃满cpu
随机的

### OpenClash Log

最新版本meta内核时不时在低负载下吃满cpu

### OpenClash Config

```shell
J4125 I211
Speedtest xray千兆跑满负载30%
```

### Expected Behavior

正常使用 无高cpu负载

**Comment by Synchronized1** [comment]
我也遇到这个问题...80%-90% CPU占用😄

**Comment by RhythmNz** [comment]
> 我也遇到这个问题...80%-90% CPU占用😄

我的cpu比较菜 已经跑满了 j4125

**Comment by Ckandzy** [comment]
我也遇到了这个问题
https://github.com/vernesong/OpenClash/issues/3360

**Comment by jhjpzheng** [comment]
如果是在路由环境的话，可以尝试关闭进程规则

**Comment by RhythmNz** [comment]
> 如果是在路由环境的话，可以尝试关闭进程规则

已经关闭了

**Comment by wayne0926** [comment]
我跑speedtest有几率直接内核崩溃，然后重启内核，内存被占700多mb😭

**Comment by flyingthecat** [comment]
刚刚更新了 149还是cpu跑满。。。
