### ISSUE TITLE
[Bug] 使用几天后就无法进行代理，频繁掉线，直到最后开启后无法上网

### ISSUE THREAD

**Issue by yjiawqgj** [vernesong/OpenClash#3356]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.121-beta

### Bug on Environment

Lean

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

正常使用就出现BUG

### Describe the Bug

之前使用带有本插件的固件，使用几天后，就频繁的掉线，然后一天左右就无法正常代理，运行open clash无论是国外还是国内都无法联网，只能停掉固件。我以为是openclash有BUG，但电脑版的clash却可以正常使用同一机场。然后6月16号以重新安装了一个新固件，并正常使用到今天（6月20号）下午，又开始频繁的连接不上，我只能无奈停止。但是电脑版的clash还是使用同一机场流畅运行。我询问机场客服，客服说一切正常，但只有我一个人反馈节点有故障，其他人都没有说节点有问题。但是我切换到另一家备用机场却很流畅，但是流量很少，一下没控制信用超了。然后我再切换回来这个机场依然是无法正常使用。

### OpenClash Log

[debug.txt](https://github.com/vernesong/OpenClash/files/11800836/debug.txt)

### Expected Behavior

不知道啥意思

**Comment by vernesong** [comment]
发异常情况下的日志

**Comment by yjiawqgj** [comment]
> 发异常情况下的日志

我又重新安装了固件，等几天再出现情况时给你回馈日志，等几天。

**Comment by yjiawqgj** [comment]
[OpenClash-2023-6-23-16-49-55.log](https://github.com/vernesong/OpenClash/files/11846588/OpenClash-2023-6-23-16-49-55.log)
这是运行日志。
21号安装的今天下午23号就开始频繁掉线。youtube等网站一会能打开，一会不能打开，还有PT站，某PT网站我已经设置了代理，他的tracker服务器设置为直连，但主页是一会能打开一会打不开，网站做种数量实际为4千左右，网站显示数量从四千一会降到三千多一会降到两千多直到0，然后又慢慢涨回来，稳定到一千五百多左右。网站显示我的IP是代理，客户端是实际国内IP这倒没有错。

**Comment by vernesong** [comment]
![image](https://github.com/vernesong/OpenClash/assets/42875168/0c28dacd-13fa-4696-bfc8-c95730ba5e3c)

**Comment by yjiawqgj** [comment]
> ![image](https://user-images.githubusercontent.com/42875168/248275731-0c28dacd-13fa-4696-bfc8-c95730ba5e3c.png)

[这个昨天我昨天（22号）取消了，做种正常，因为这个规则把馒头的域名设置为直连了，而馒头这两天不能直连了，我直接取消后又自己手动添加的自定义规则：
- DOMAIN,m-team.cc,慈善机场
- DOMAIN,tracker.m-team.cc,DIRECT
- DOMAIN,t.audiences.me,DIRECT
- DOMAIN,tracker.hdsky.me,DIRECT
今天下午（23号）又频繁掉线了，网站又出现不能正确显示做种数，到目前为止做种量由下行的1500左右到了3000左右，还差1000多种没有显示出来。重点是又出现了那种代理频繁掉线和很打开速度慢的的情况。这个如何解决？我以为是我安装在群晖因为天热不太好散热导致的虚拟机性能不够，但我看了一下open clash运行状态页面的占用率：
  上传:  15.2 KB/S   下载:  12.1 KB/S   上传总量:  73.7 MB   下载总量:  1.6 GB   活动连接:  62   内存占用:  34.3 MB   CPU占用:  5 %
国内网络倒是很流畅。

**Comment by Aleix-Chen** [comment]
我和你一样，用着用着就上不去外网了，但是关掉open clash之后，用电脑端的calshx就没问题。

**Comment by Aleix-Chen** [comment]
> 
软路由的openwrt上，老机子R2S

**Comment by yjiawqgj** [comment]
我是安装在群晖920+虚拟机上的，夏天热，又挂着PT刷流，CPU倒不是经常高，8G内存占用到7、80，有时候打开群晖和里面部署的docker都很慢，但是打开虚拟机上的路由却没受多大影响，有时候刚一打开时，openwrt的背景壁纸不快速显示，国内网络延迟比较高不能打游戏。我怀疑是多功能在一起，加上一直读写硬盘，天又热，性能不够。开发人员也没有有回信，准备入手一个软路由试试能不能解决。

**Comment by zxlhhyccc** [comment]
> 我是安装在群晖920+虚拟机上的，夏天热，又挂着PT刷流，CPU倒不是经常高，8G内存占用到7、80，有时候打开群晖和里面部署的docker都很慢，但是打开虚拟机上的路由却没受多大影响，有时候刚一打开时，openwrt的背景壁纸不快速显示，国内网络延迟比较高不能打游戏。我怀疑是多功能在一起，加上一直读写硬盘，天又热，性能不够。开发人员也没有有回信，准备入手一个软路由试试能不能解决。

上游服务器设置一下本机地址（127.0.0.1），如果是二级路由或者旁路由，设置上级路由的地址，比如上级路由地址是：192.168.2.1，那么上游服务器设置一个，即：192.168.2.1，保证没事。。。。

**Comment by anjue39** [comment]
确实新版本一堆莫名其妙的问题。也不知道是不是openclash的问题。比如地平线5无法多人联机进入在线模式，fake ip下花生壳ddns以前相安无事正常解析，现在ddns无法用，比如花生壳。还有一些莫名其妙的网速变慢变卡。我觉得是那个本地dns劫持的bug

**Comment by lencil** [comment]
我也发现此问题了，我软路由是openwrt，跑OpenClash，每次运行十来天后，就突然连不上了，所有能试的方法都试过了，然后重新安装后就好了。过十来天又不行了，相当奇怪，下次发疯时，我粘个日志上来看看。

**Comment by Aleix-Chen** [comment]
openwrt里面那个

github-actions[bot] ***@***.***> 于2023年10月8日周日 16:33写道：

**Comment by filliang** [comment]
我也遇到了这个情况，时不时的断网，摸索了很久，后来我换了固件，刷的ImmortalWrt的固件，从昨天到今天，目前未发现断网的情况，之前用的是istore的固件。

**Comment by TohsakaOrz** [comment]
> 我也遇到了这个情况，时不时的断网，摸索了很久，后来我换了固件，刷的ImmortalWrt的固件，从昨天到今天，目前未发现断网的情况，之前用的是istore的固件。

你好，我用的也是istore固件，发现打网游（国服瓦）时偶现网络波动，我感觉就是在安装open clash之后出现的，想问一下，您更换固件之后还遇到过问题吗？
