### ISSUE TITLE
[Bug] 更新第三方规则 lhie1失败

### ISSUE THREAD

**Issue by psumhm** [vernesong/OpenClash#3357]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.121-beta

### Bug on Environment

Lean

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

用的 lhie1规则一键生成配置文件，在插件设置-第三方规则订阅点击检查并更新，出现错误，如图：

![1](https://github.com/vernesong/OpenClash/assets/49806324/31db372c-8c83-4a98-aea2-791909df5f01)
![2](https://github.com/vernesong/OpenClash/assets/49806324/4be7eb7c-c329-4fcb-98a7-617ee676af38)
![3](https://github.com/vernesong/OpenClash/assets/49806324/dcd2569f-814d-4c09-a030-cb19f525f75f)

### Describe the Bug

无

### OpenClash Log

无

### Expected Behavior

无

**Comment by 404user** [comment]
解决了吗？我这里也是这样，规则突然全没了，更新不了。
