### ISSUE TITLE
[Bug] Openclash内核不定期崩溃

### ISSUE THREAD

**Issue by Ckandzy** [vernesong/OpenClash#3360]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.121-241

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-arm64

### To Reproduce

1.openwrt所在设备为旁路由，关闭dhcp，电脑手动设置旁路由网关上网
2.运行openclash，使用一段时间后cpu占有率飙升，旁路由无法ssh连接，直至openclash内核崩溃，cpu占有率下降，可重新通过ssh连接旁路由

### Describe the Bug

运行openclash后，国内国外访问一切正常，但使用一段时间后cpu占有率飙升，直至openclash内核崩溃

### OpenClash Log

[内核日志.txt](https://github.com/vernesong/OpenClash/files/11818276/default.txt)

### Expected Behavior

希望能够长时间稳定运行

**Comment by tkfanswind** [comment]
启动这个版本的openclash会导致R2S不停重启
