### ISSUE TITLE
[Bug] 升级失败惨案

### ISSUE THREAD

**Issue by jacobin** [vernesong/OpenClash#3379]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.121-beta

### Bug on Environment

Other

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

欲升级至v0.45.128-beta

### Describe the Bug

升级过程中，失败，然后拉不起来，用winscp挂上去一看，乖乖，所有的文件都变成了0长度。
不是第一次发现这个问题。
很恶心
太烂了

### OpenClash Log

没必要

### OpenClash Config

```shell
没必要
```

### Expected Behavior

还用说吗？

### Screenshots

![Snap2](https://github.com/vernesong/OpenClash/assets/5020373/14419b0b-f6e7-4643-bdf3-05ecbaa027d3)
![Snap3](https://github.com/vernesong/OpenClash/assets/5020373/93f0298c-3c67-483d-a0d5-843f4439c7ae)
![Snap1](https://github.com/vernesong/OpenClash/assets/5020373/8a88f46a-0312-4f50-a2c2-3e2d9965efed)

**Comment by BiuZero** [comment]
我也升级失败了，倒是没变成0，但是不知道为啥怎么也成功不了。。。哎

**Comment by momonoshiori** [comment]
升级失败基本是网络问题，自己找原因吧，别在这阴阳怪气

**Comment by jacobin** [comment]
> 升级失败基本是网络问题，自己找原因吧，别在这阴阳怪气

web上点“升级”按钮试过一次，直接下载好ipk再试一次，都是这个结果，你知道毛啊你，胡咧咧

**Comment by caliban511** [comment]
同样经常升级失败，，，和网络没有关系，，，反复尝试，最终还是可以升级成功的，，，相比这个，我更头疼的是核心的升级，，除了一样要反复尝试之外，，他还会转着圈提示升级，，，升级完了又要你再“升”回去，升无止境，有时候手动下载扔进去也一样，，，😂😂😂

**Comment by jacobin** [comment]
> 同样经常升级失败，，，和网络没有关系，，，反复尝试，最终还是可以升级成功的，，，相比这个，我更头疼的是核心的升级，，除了一样要反复尝试之外，，他还会转着圈提示升级，，，升级完了又要你再“升”回去，升无止境，有时候手动下载扔进去也一样，，，😂😂😂

是的，“最终还是可以升级成功的” ，但是你可曾有过『知道最后的成功是怎么成就的』吗？没有过吧？大家都是稀里糊涂连滚带爬踉踉跄跄的混过去的😂😂😂

安装IPK而把我的/etc/openclash清零（/亦即/etc/openclash里的所有的文件、子目录的文件，它们的文件长度都变成了0）之后，我得诚惶诚恐的1、解包最后一次的OpenClash的备份包，覆盖过去到 /etc/openclash；2、从网络上下载linuxAmdx86-64的clash.tar.gz；3、解压clash.tar.gz得文件clash直接覆盖/etc/openclash/clash；4、到terminal/bash上执行chmod 755 /etc/openclash/clash；5、在“鸡蛋和鸡孰先有”的问题上，通过另外的翻墙渠道下载一个确信可用的yaml譬如abc.yaml扔到/etc/openclash/config里；6、在openwrt\openclash里切换到“使用abc.yaml”，点击“启动openclash” ... ... 哎，浮上来透口气吧，又死了一回

**Comment by caliban511** [comment]
> 
我这边是自己编译openwrt固件，翻墙是机场订阅，没那么麻烦，，，每次刷完把备份好的设置解压扔进去覆盖一下就好，，，升级遇到问题的时候只要反复点检查更新，总会成功的，，偶尔手动安装ipk也没遇到清零的情况，，，有循环提示更新的核心不管它就是了，，，🤣🤣🤣

**Comment by caliban511** [comment]
> 
> 安装IPK而把我的/etc/openclash清零（/亦即/etc/openclash里的所有的文件、子目录的文件，它们的文件长度都变成了0）之后，我得诚惶诚恐的1、解包最后一次的OpenClash的备份包，覆盖过去到 /etc/openclash；2、从网络上下载linuxAmdx86-64的clash.tar.gz；3、解压clash.tar.gz得文件clash直接覆盖/etc/openclash/clash；4、到terminal/bash上执行chmod 755 /etc/openclash/clash；5、在“鸡蛋和鸡孰先有”的问题上，通过另外的翻墙渠道下载一个确信可用的yaml譬如abc.yaml扔到/etc/openclash/config里；6、在openwrt\openclash里切换到“使用abc.yaml”，点击“启动openclash” ... ... 哎，浮上来透口气吧，又死了一回

我这边是自己编译openwrt固件，翻墙是机场订阅，没那么麻烦，，，每次刷完把备份好的设置解压扔进去覆盖一下就好，，，升级遇到问题的时候只要反复点检查更新，总会成功的，，偶尔手动安装ipk也没遇到清零的情况，，，有循环提示更新的核心不管它就是了，，，🤣🤣🤣

**Comment by jacobin** [comment]
> > 安装IPK而把我的/etc/openclash清零（/亦即/etc/openclash里的所有的文件、子目录的文件，它们的文件长度都变成了0）之后，我得诚惶诚恐的1、解包最后一次的OpenClash的备份包，覆盖过去到 /etc/openclash；2、从网络上下载linuxAmdx86-64的clash.tar.gz；3、解压clash.tar.gz得文件clash直接覆盖/etc/openclash/clash；4、到terminal/bash上执行chmod 755 /etc/openclash/clash；5、在“鸡蛋和鸡孰先有”的问题上，通过另外的翻墙渠道下载一个确信可用的yaml譬如abc.yaml扔到/etc/openclash/config里；6、在openwrt\openclash里切换到“使用abc.yaml”，点击“启动openclash” ... ... 哎，浮上来透口气吧，又死了一回
> 
> 我这边是自己编译openwrt固件，翻墙是机场订阅，没那么麻烦，，，每次刷完把备份好的设置解压扔进去覆盖一下就好，，，升级遇到问题的时候只要反复点检查更新，总会成功的，，偶尔手动安装ipk也没遇到清零的情况，，，有循环提示更新的核心不管它就是了，，，🤣🤣🤣

你是自锻装甲上马的玩家，是没有困难制造困难也要上的蛮主，还那么有耐心，非我闲散认死理之棒槌所愿意学习的榜样🤣🤣🤣

**Comment by jacobin** [comment]
> 我这边是自己编译openwrt固件，翻墙是机场订阅，没那么麻烦，，，每次刷完把备份好的设置解压扔进去覆盖一下就好，，，升级遇到问题的时候只要反复点检查更新，总会成功的，，偶尔手动安装ipk也没遇到清零的情况，，，有循环提示更新的核心不管它就是了，，，🤣🤣🤣

你是自锻装甲上马的玩家，是没有困难制造困难也要上的蛮主，还那么有耐心，非我等闲散认死理之棒槌所愿意学习的榜样🤣🤣🤣

**Comment by o0rz** [comment]
不知道这个issue提的意义在哪？纯粹情绪发泄有意义么？亏你简介还写着"c/c++ programmer",
贴一下复现的步骤，贴一下升级的日志，帮助开发者定位问题不是能更快的解决问题吗？

**Comment by jacobin** [comment]
> 不知道这个issue提的意义在哪？纯粹情绪发泄有意义么？亏你简介还写着"c/c++ programmer", 贴一下复现的步骤，贴一下升级的日志，帮助开发者定位问题不是能更快的解决问题吗？

别淫看我太夸张，我笑别淫没受伤

**Comment by WYC-2020** [comment]
用个锤子用，作者删库跑路吧 吃力不讨好做个 锤子做

**Comment by WYC-2020** [comment]
让他们所有用的 爱用谁用谁的 ，直接把仓库关闭了

**Comment by jacobin** [comment]
> 让他们所有用的 爱用谁用谁的 ，直接把仓库关闭了

我对我说的话负责，你说这些话能负责吗？你代表作者吗？一句话都说不利索有语病一箩筐的人，装腔作势的。
在gihub上删库的人从来没有戴着意义的预告，也不会说理由。你不能用品格高尚或者道德低劣来评价他，他只需要一句“我累了”就够了。

我从来不以为我的建议能对别人有什么影响，因为首先人都有成见，其次是不以你美。你以为很重要很漂亮的建议，在他心里，什么都不是，对你有回复也许只是出于礼貌和装作谦虚。丰富的表达须要同样丰富的时间来组织和润色，母语都说不利索的人，换我是作者，我才不要这样的帮腔。

**Comment by mphin** [comment]
感觉升级的过程逻辑需要优化，我也是经常升级失败，导致openclash彻底无法启动，只能手动下载拷贝到目录，完了之后，它又重新再次下载！又升级失败！又需要重新拷贝到目录。。总得来说梯子烂谨慎升级。

**Comment by jacobin** [comment]
> 感觉升级的过程逻辑需要优化，我也是经常升级失败，导致openclash彻底无法启动，只能手动下载拷贝到目录，完了之后，它又重新再次下载！又升级失败！又需要重新拷贝到目录。。总得来说梯子烂谨慎升级。

你要有兴趣，请去解压它的IPK，可以检查它的安装脚本。脚本真的是按照最想当然、最理想的情形进行程序编写，对可能的异常，考虑不足或者根本就没有考虑。一个下载好了的IPK，安装的时候为什么还要去爬梯/上网？太驴倔拧巴了
