### ISSUE TITLE
内网ip段走代理怎么设置

### ISSUE THREAD

**Issue by wangkun-king** [vernesong/OpenClash#338]
<img width="757" alt="image" src="https://user-images.githubusercontent.com/20026922/79616848-9cf9f500-8138-11ea-9613-211e9646aca6.png">
<img width="533" alt="image" src="https://user-images.githubusercontent.com/20026922/79616933-d92d5580-8138-11ea-8e4c-46ee1fae894b.png">

内网ip段这里直接return 无法代理公司网络

**Comment by vernesong** [comment]
代理的用途？

**Comment by wangkun-king** [comment]
在家办公 代理公司内网

**Comment by wangkun-king** [comment]
已经解决
修改 /etc/init.d/openclash 添加的路由就行了

**Comment by bleachzhou** [comment]
> 请问下具体要怎么修改下

**Comment by bleachzhou** [comment]
> 

您好，想请问在具体是怎么修改的呀？ipset add localnetwork 192.168.0.0/16，是把这个注释掉吗？
