### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by JJ-Coffee** [vernesong/OpenClash#3383]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.129

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-arm64

### To Reproduce

Can't using system tun on openwrt 23.05

### Describe the Bug

No internet access with system tun on openwrt 23.05

### OpenClash Log

No

### Expected Behavior

No

**Comment by JJ-Coffee** [comment]
No internet access with using tun system on openwrt 23.05

**Comment by JJ-Coffee** [comment]
Thanks dude it's working

**Comment by RebelliousWhiz** [comment]
> Maybe this can help,
> go to Network -> Firewall at _**General Setting**_ Change _**Input**_ from **_reject_** to _**accept**_

I use OpenWrt 23.05.0-rc3, clash tun core, fake-ip (tun mode).

I observed if I use "System" as Stack Type, all the connections will be denied.

![Screenshot 2023-09-04 at 2 24 22 PM](https://github.com/vernesong/OpenClash/assets/15100865/42e4c934-92ba-424d-9ff1-4d3cd4d033a1)

But using Givosr works fine.

![image](https://github.com/vernesong/OpenClash/assets/15100865/70b5c77a-6e6b-444f-8f55-aa219510f119)

Surprisingly, System Stack will work again if I change _**Input**_ from **_reject_** to _**accept**_ in Firewall settings.

![image](https://github.com/vernesong/OpenClash/assets/15100865/d6aef13a-8da4-4953-85f4-d1d4c0e69be3)

![image](https://github.com/vernesong/OpenClash/assets/15100865/7161918a-bca6-476d-b73c-aa0cd09120ca)
