### ISSUE TITLE
[Feature] 实现根据不同的设备IP定制策略

### ISSUE THREAD

**Issue by AgaigetS** [vernesong/OpenClash#3384]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

组网：主路由是软路由，搭载openwrt系统，旁路由是硬路由（AP模式），家用上网设备通过硬路由接入

利用openclash下载了游戏规则，在rule模式下，xbox游戏机仍然无法正常游戏，切换成global模式后可以一切正常，但又会使网络中的其他设备访问内网变慢。于是就想能否对某一特定IP指定为global模式，而其他设备保留rule模式上网呢？可能现在已经有，但是我不是很清楚应该怎么设置。

### Describe the Solution

如上

**Comment by deuteros-gex** [comment]
#3134
