### ISSUE TITLE
Question: OpenClash现阶段是否支持新的Clash配置格式？

### ISSUE THREAD

**Issue by maddie** [vernesong/OpenClash#339]
在Clash的[这个commit](https://github.com/Dreamacro/clash/commit/88d8f937938d7aba774b1af638df6910b1a1a14d)里面，把`Proxy`改成了`proxies`, `Proxy Group:`改成了`proxy-groups`

虽然作者说在1.0的时候才会deprecate这两个旧的名称，我想问问现阶段OpenClash是否能支持使用`proxies`和`proxy-groups`的配置文件（订阅）？

**Comment by vernesong** [comment]
会替换回旧的

**Comment by maddie** [comment]
也就是说如果订阅下来的是新格式，OpenClash也是可以正确处理的对吧？那就ok!!
