### ISSUE TITLE
想问一下为啥open clash默认开启experimental:   sniff-tls-sni: true

### ISSUE THREAD

**Issue by ForestL18** [vernesong/OpenClash#3390]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.129

### Bug on Environment

Lean

### Bug on Platform

Linux-arm64

### To Reproduce

如题所示，这个功能在clash项目中不是默认关闭的吗？因为是实验性功能。为什么在OpenClash 修改后用于启动的配置文件中是默认开启的呢？作者可以解释一下原因吗？

### Describe the Bug

无

### OpenClash Log

无

### Expected Behavior

无

**Comment by ace115** [comment]
同问，以前是没这个选项的

**Comment by wuyuqq** [comment]
同 即使改了sniff-tls-sni: false 也会被默认覆盖成sniff-tls-sni: true
