### ISSUE TITLE
[Bug] 为什么启用openclash之后，威联通的ddns功能就失效了呢 

### ISSUE THREAD

**Issue by freshzhy** [vernesong/OpenClash#3391]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.129-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

启用openclash之后，威联通的ddns功能就失效

### Describe the Bug

![image](https://github.com/vernesong/OpenClash/assets/125800886/3bc66c68-16c9-47bc-98a1-72919061fedc)

### OpenClash Log

![image](https://github.com/vernesong/OpenClash/assets/125800886/96775d8d-ec32-49bc-b11c-4a9643999d6b)
![image](https://github.com/vernesong/OpenClash/assets/125800886/1349f95b-665e-424e-ab3d-7323a1d8373d)
![image](https://github.com/vernesong/OpenClash/assets/125800886/01b1d665-b207-452f-97bf-841ad4ecfa27)

### Expected Behavior

不清楚是否是配置错误

**Comment by vernesong** [comment]
ping 域名看是否正常，如果是旁路由，建议黑白名单绕过核心的来源端口

**Comment by freshzhy** [comment]
openclash启用后，威联通的ddns就失效了，ping域名不通，检查了一下，发现ddns解析到的是节点的IP，如果将威联通的IP不允许使用代理，ddns就是正常获取到真实的公网IP。但由于威联通里面的一些服务又需要代理上网，目前的解决方案是在openclash的Dashboard 控制面板中，让“漏网之鱼”组别全部直连。请问大神是否可以通过设置相应的策略使得威联通的ddns服务直连，“漏网之鱼”代理上网呢？如果可以，应该如何设置？

**Comment by freshzhy** [comment]
> ping 域名看是否正常，如果是旁路由，建议黑白名单绕过核心的来源端口

软路由是主路由，openclash启用后，威联通的ddns就失效了，检查了一下，发现ddns解析到的是节点的IP，如果将威联通的IP不允许使用代理，ddns就是正常获取到真实的公网IP。但由于威联通里面的一些服务又需要代理上网，目前的解决方案是在openclash的Dashboard 控制面板中，让“漏网之鱼”组别全部直连。请问大神是否可以通过设置相应的策略使得威联通的ddns服务直连，“漏网之鱼”代理上网呢？如果可以，应该如何设置？

**Comment by vernesong** [comment]
ddns有专门获取IP的域名，加规则让他直连

**Comment by m20104600** [comment]
> ddns有专门获取IP的域名，加规则让他直连

我群晖也一样，但是我是在ikuai上做的ddns并把群晖端口映射出去的，内网可以域名：端口 访问群晖下的所有服务，外网无法访问群晖。域名可以ping通，并且可以访问除群晖外映射出去的所有其他服务。也尝试将群辉相关的域名加入了自定义规则，但还是没解决问题。
![image](https://github.com/vernesong/OpenClash/assets/33032343/acf26855-69cb-4e45-b7e0-6eef13ba0917)

**Comment by vernesong** [comment]
插件设置-黑白名单-绕过来源端口，写群辉的映射端口
