### ISSUE TITLE
[Bug] 你他妈搁这做游戏呢？你先别急着他妈把issue关了，赶紧把你的二进制给我移出去，别几把跟我说depth，自己搁这犯贱别逼用户骂你

### ISSUE THREAD

**Issue by Zaphkito** [vernesong/OpenClash#3393]
https://blog.csdn.net/sinat_42483341/article/details/110181767
https://learn.microsoft.com/zh-cn/azure/devops/repos/git/remove-binaries
https://blog.csdn.net/imyyx125/article/details/77966103
https://geek-docs.com/git/git-questions/282_git_after_deleting_a_binary_file_from_git_history_why_is_my_repository_still_large.html

不会用git可以百度谷歌，没必要把自己变成傻逼
不会用git可以百度谷歌，没必要把自己变成傻逼
不会用git可以百度谷歌，没必要把自己变成傻逼
不会用git可以百度谷歌，没必要把自己变成傻逼
不会用git可以百度谷歌，没必要把自己变成傻逼
不会用git可以百度谷歌，没必要把自己变成傻逼

### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.129

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

你他妈搁这做游戏呢？你先别急着他妈把issue关了，赶紧把你的二进制给我移出去，别几把跟我说depth，自己搁这犯贱别逼用户骂你

### Describe the Bug

你他妈搁这做游戏呢？你先别急着他妈把issue关了，赶紧把你的二进制给我移出去，别几把跟我说depth，自己搁这犯贱别逼用户骂你

### OpenClash Log

你他妈搁这做游戏呢？你先别急着他妈把issue关了，赶紧把你的二进制给我移出去，别几把跟我说depth，自己搁这犯贱别逼用户骂你

### OpenClash Config

```shell
你他妈搁这做游戏呢？你先别急着他妈把issue关了，赶紧把你的二进制给我移出去，别几把跟我说depth，自己搁这犯贱别逼用户骂你
```

### Expected Behavior

你他妈搁这做游戏呢？你先别急着他妈把issue关了，赶紧把你的二进制给我移出去，别几把跟我说depth，自己搁这犯贱别逼用户骂你

### Screenshots

![image](https://github.com/vernesong/OpenClash/assets/64299266/c0aded2e-df42-43fa-8594-b4f1f2df81b5)
![image](https://github.com/vernesong/OpenClash/assets/64299266/1d13b576-8599-4148-8cb2-a9cbaec4dd2e)
![2b0d612f54b41455851e46c1f013213b](https://github.com/vernesong/OpenClash/assets/64299266/85abd236-3a91-45fb-87ac-19c43975a921)
![image](https://github.com/vernesong/OpenClash/assets/64299266/72388669-37ea-4acd-a410-d5a0fd7db5ca)

**Comment by wayne0926** [comment]
这么暴躁干什么

**Comment by wayne0926** [comment]
By the way, 我看了下你的issues，不是被机器人自动关了的嘛

**Comment by Zaphkito** [comment]
> By the way, 我看了下你的issues，不是被机器人自动关了的嘛

我之前的issue没问题，你把我发的图再看一下

**Comment by Zaphkito** [comment]
现在auto release一周三个，还觉得depth 1省事，回头一clone比3A大作大小还鸡巴逆天

**Comment by lztxi** [comment]
觉得不好用，有能力就自己修改，没能力就换一个，有必要在这里泼妇骂街么

**Comment by Zaphkito** [comment]
![image](https://github.com/vernesong/OpenClash/assets/64299266/c9dc7706-58cb-4d19-8f94-5f33e5f198aa)
又是理都不理，我的评价是如果你确实在改可以出来说一声你正在改，你自己什么都不说真别怪用户到处骂

**Comment by Zaphkito** [comment]
> 觉得不好用，有能力就自己修改，没能力就换一个，有必要在这里泼妇骂街么

觉得我烦的，要不无视我，要不自己去死，有必要在这里指指点点吗

**Comment by Zaphkito** [comment]
> 觉得不好用，有能力就自己修改，没能力就换一个，有必要在这里泼妇骂街么

不开玩笑的说，你自己翻翻过去的issue和我的截图就知道了，别光看我在这里骂

**Comment by wayne0926** [comment]
可是他是开源作者，这不是他的义务。他也可以说：“`觉得我烦的，要不无视我，要不自己去死，有必要在这里指指点点吗`"

**Comment by Zaphkito** [comment]
> 可是他是开源作者，这不是他的义务。他也可以说：“`觉得我烦的，要不无视我，要不自己去死，有必要在这里指指点点吗`"

有没有一种可能，维护开源项目是作者的义务之一

**Comment by Zaphkito** [comment]
@vernesong

**Comment by wayne0926** [comment]
> 

1. 作为开源项目的作者，他没有义务满足每个用户的要求或承担责任来维护项目。开源项目的作者是自愿分享代码和成果，而不是被迫接受用户的指令或批评。作者消极对待实属不妥，但这确实不是他的义务。
2. 作者有权选择是否接受他人的意见或建议。他可以自由决定是否采纳建议或将项目移交给其他人。开源项目的核心在于自由和合作，而不是被迫接受他人的意见。你可以公开指责企业亦或政府原因在于他们从你这里获得了利益，但是显然作者并没有从你这里获取利益，_**没有“应不应该”，只有“愿不愿意”**_（即使你 Sponsor 了这个项目）。
3. 无论是作者还是用户，都应该以尊重和友善的态度进行交流。侮辱和攻击的言论不仅不会促进问题的解决，反而会破坏合作氛围。

作者不需要有“觉悟”，使用者也不是“天王老子”，这里是社区，不是服务站。

**Comment by Zaphkito** [comment]
> > 
> 
> 1. 作为开源项目的作者，他没有义务满足每个用户的要求或承担责任来维护项目。开源项目的作者是自愿分享代码和成果，而不是被迫接受用户的指令或批评。作者消极对待实属不妥，但这确实不是他的义务。
> 2. 作者有权选择是否接受他人的意见或建议。他可以自由决定是否采纳建议或将项目移交给其他人。开源项目的核心在于自由和合作，而不是被迫接受他人的意见。你可以公开指责企业亦或政府原因在于他们从你这里获得了利益，但是显然作者并没有从你这里获取利益，也就没有义务对你负责。_**没有“应不应该”，只有“愿不愿意”**_（即使你 Sponsor 了这个项目）。
> 3. 无论是作者还是用户，都应该以尊重和友善的态度进行交流。侮辱和攻击的言论不仅不会促进问题的解决，反而会破坏合作氛围。
> 
> 作者不需要有“觉悟”，使用者也不是“天王老子”，这里是社区，不是服务站。

开源项目核心在自由和合作对吧，你全版本dist全扔仓库里，容量这么大，我可不可以算你阻碍了“正常”使用版本管理工具的人自由拉取仓库呢，“正常”使用版本管理工具，也包括但不限于使用了某种图形界面，一键拉取，或者是用 GitHub Desktop 的，这玩意我印象里可不能带参拉取，这也不是它本体的问题了，完全是项目管理上出了原则性错误，怎么改？而且我极其反对第三点，因为已经有大量用户通过issue向用户询问或提起清理二进制文件的需求，但作者无一例外的回复depth 1或者直接无视掉，现在已经不是代码本身的问题了，就是对“仓库”如何使用，一个原则上的问题，作者不会正确使用仓库，也不从根本上解决问题，要是协作项目可以把人整死的，针对他人的诉求置之不理，先礼后兵，其他的用户已经礼完了，没办法了，我当然只能这样通过侮辱和攻击的言论引起作者的注意

**Comment by wayne0926** [comment]
我个人认为这个诉求是完全合理的，但是你的方式显然过激了。引起注意有道理，但是这样的表达方式显然招致了一部分的反感，这不是表达诉求最有效的方式。
我仍然认为这是一个`社区`，友好合作的社区，过激的行为方式是不应该被提倡的，也没有必要把这个问题上升到“原则性错误”、“先礼后兵”等不属于社区合作范畴的高度。不过也希望作者可以给出一个答复来避免这种不必要的争端。
@vernesong

**Comment by WYC-2020** [comment]
这个问题，我很早以前就说过，作者他不弄也没办法，毕竟这是别人的仓库，别人想怎么玩就怎么玩，最多提意见，他接受不接受那是作者的意愿，不接受你也不应该这么怼，你这明显过激了

**Comment by LOVE2CMOL** [comment]
人家没有义务这么干 最多你提意见 不接受也不应该开骂

**Comment by LOVE2CMOL** [comment]
[Maintaining a strong community](https://docs.github.com/en/site-policy/github-terms/github-community-guidelines#maintaining-a-strong-community)
[Building Welcoming Communities](https://opensource.guide/building-community/)

**Comment by xiqiuqiu** [comment]
我草，涨见识了~好奇这哥们在生活中是个怎么样的人

> > > 
> > 
> > 
> > 
> > 1. 作为开源项目的作者，他没有义务满足每个用户的要求或承担责任来维护项目。开源项目的作者是自愿分享代码和成果，而不是被迫接受用户的指令或批评。作者消极对待实属不妥，但这确实不是他的义务。
> > 2. 作者有权选择是否接受他人的意见或建议。他可以自由决定是否采纳建议或将项目移交给其他人。开源项目的核心在于自由和合作，而不是被迫接受他人的意见。你可以公开指责企业亦或政府原因在于他们从你这里获得了利益，但是显然作者并没有从你这里获取利益，也就没有义务对你负责。_**没有“应不应该”，只有“愿不愿意”**_（即使你 Sponsor 了这个项目）。
> > 3. 无论是作者还是用户，都应该以尊重和友善的态度进行交流。侮辱和攻击的言论不仅不会促进问题的解决，反而会破坏合作氛围。
> > 
> > 作者不需要有“觉悟”，使用者也不是“天王老子”，这里是社区，不是服务站。
> 
> 开源项目核心在自由和合作对吧，你全版本dist全扔仓库里，容量这么大，我可不可以算你阻碍了“正常”使用版本管理工具的人自由拉取仓库呢，“正常”使用版本管理工具，也包括但不限于使用了某种图形界面，一键拉取，或者是用 GitHub Desktop 的，这玩意我印象里可不能带参拉取，这也不是它本体的问题了，完全是项目管理上出了原则性错误，怎么改？而且我极其反对第三点，因为已经有大量用户通过issue向作者询问或提起清理二进制文件的需求，但作者无一例外的回复depth 1或者直接无视掉，现在已经不是代码本身的问题了，就是对“仓库”如何使用，一个原则上的问题，作者不会正确使用仓库，也不从根本上解决问题，要是协作项目可以把人整死的，针对他人的诉求置之不理，先礼后兵，其他的用户已经礼完了，没办法了，我当然只能这样通过侮辱和攻击的言论引起作者的注意，你自己都已经这样了，就别怪用户不尊重你

**Comment by wuiiled** [comment]
> 我草，涨见识了~好奇这哥们在生活中是个怎么样的人
> 
> > > > 
> > > 
> > > 
> > > 
> > > 1. 作为开源项目的作者，他没有义务满足每个用户的要求或承担责任来维护项目。开源项目的作者是自愿分享代码和成果，而不是被迫接受用户的指令或批评。作者消极对待实属不妥，但这确实不是他的义务。
> > > 2. 作者有权选择是否接受他人的意见或建议。他可以自由决定是否采纳建议或将项目移交给其他人。开源项目的核心在于自由和合作，而不是被迫接受他人的意见。你可以公开指责企业亦或政府原因在于他们从你这里获得了利益，但是显然作者并没有从你这里获取利益，也就没有义务对你负责。_**没有“应不应该”，只有“愿不愿意”**_（即使你 Sponsor 了这个项目）。
> > > 3. 无论是作者还是用户，都应该以尊重和友善的态度进行交流。侮辱和攻击的言论不仅不会促进问题的解决，反而会破坏合作氛围。
> > > 
> > > 作者不需要有“觉悟”，使用者也不是“天王老子”，这里是社区，不是服务站。
> > 
> > 
> > 开源项目核心在自由和合作对吧，你全版本dist全扔仓库里，容量这么大，我可不可以算你阻碍了“正常”使用版本管理工具的人自由拉取仓库呢，“正常”使用版本管理工具，也包括但不限于使用了某种图形界面，一键拉取，或者是用 GitHub Desktop 的，这玩意我印象里可不能带参拉取，这也不是它本体的问题了，完全是项目管理上出了原则性错误，怎么改？而且我极其反对第三点，因为已经有大量用户通过issue向作者询问或提起清理二进制文件的需求，但作者无一例外的回复depth 1或者直接无视掉，现在已经不是代码本身的问题了，就是对“仓库”如何使用，一个原则上的问题，作者不会正确使用仓库，也不从根本上解决问题，要是协作项目可以把人整死的，针对他人的诉求置之不理，先礼后兵，其他的用户已经礼完了，没办法了，我当然只能这样通过侮辱和攻击的言论引起作者的注意，你自己都已经这样了，就别怪用户不尊重你

要饭的觉得要来的饭不好吃，把厨子跟饭店都喷满粪。

**Comment by caliban511** [comment]
这个说话方式让我感觉是来反串的。😂😂😂

**Comment by lztxi** [comment]
> > 觉得不好用，有能力就自己修改，没能力就换一个，有必要在这里泼妇骂街么
> 
> 不开玩笑的说，你自己翻翻过去的issue和我的截图就知道了，别光看我在这里骂 https://docs.github.com/zh/repositories/working-with-files/managing-large-files/about-large-files-on-github

就怎么说呢？？呃呃呃，还是祝你生活愉快吧！

**Comment by caliban511** [comment]
好家伙，这都能转移到键政上去，专业啊。🤣🤣🤣

**Comment by PolymorphismException** [comment]
> 好家伙，这都能转移到键政上去，专业啊。🤣🤣🤣
你用openclash就已经犯法和辱华了，这都盲人摸象，当懦夫和瞎子你才是专业的

**Comment by caliban511** [comment]
> > 你用openclash就已经犯法和辱华了，这都盲人摸象，当懦夫和瞎子你才是专业的

厉害，你也专业。他键政你键战，双键合一，网络无敌。😂😂😂

**Comment by Zaphkito** [comment]
@PolymorphismException @caliban511 这个issue不讨论建政问题，自己滚一边去

**Comment by palermoe** [comment]
编译 brave-browser 也是一样,  要下载20多GB的文件 :(

**Comment by zanzhz1101** [comment]
？为啥不fork之后自己改呢，改完再合并过来嘛

**Comment by zanzhz1101** [comment]
![65VJ5SJV%)O@M3KQFKA$8C5](https://github.com/vernesong/OpenClash/assets/11192517/91240f40-d6a0-49ca-98bf-2889d38236aa)

**Comment by caliban511** [comment]
> 编译 brave-browser 也是一样, 要下载20多GB的文件 :(

好家伙，20G ，，，话说 V大现在这已经是整理过一次了，，，以前拉openclash编译一次要下10个G，直接治好了我喜欢全删重拉的臭毛病，，，😂😂😂

**Comment by PolymorphismException** [comment]
1. 表达公民权利：在大多数民主国家，公民有权利表达自己的政治观点和意见。这是民主社会的一部分，而且是一个健康的民主国家所应该鼓励和保护的。键政不是一种贬义词，而是公民履行自己责任的一种方式。

2. 推动变革和改进：通过在网上发表自己的政治观点，可以促进社会的变革和政策的改进。公众的声音和意见对于政策制定是非常重要的，因为政府需要了解人民的需求和期望，才能更好地代表他们的利益。

3. 信息透明度和公开讨论：键政有助于增加政策制定的透明度，使政府更加负责和透明。公众的讨论和批评可以促使政府回应问题并解决民众的关切。

4. 社会参与的重要性：社会参与是民主社会的基石。通过键政，公民可以在政治决策中发挥积极作用，而不仅仅是被动接受政策。

5. 提高政治意识和知识：键政可以帮助人们更深入地了解政治议题和政策，从而成为更负责任的选民和公民。

蜘蛛有没有正常人？一天到晚就是扣帽子和讲废话？害怕谈论政治？不关心政治？你他妈不关心这是政治来关心你你他妈买个菜车停哪里都是政治啊，你买个菜几块钱都是政治啊，一天到晚键政，用起别人的免费东西觉得自己牛逼的很，指点江山这里不满意哪里不满意挑这挑那，你他妈共产党没搞防火墙你用的着在这废话？妈连公民都不是还他妈的天天见证见证你的脑子已经被阉割啦谈到政治就害怕，妈的共产党在在你头上拉屎拉尿，上个github他妈的域名被污染，你在这里装看不见这就是你他妈的正义，他妈的好好的讨论区你在这里狗叫一样的放屁，还他妈键政键政，你怎么不叫共产党把防火墙撤了？你共爹都不让你上外网啦他妈的还出来狗叫维护你共爹

**Comment by wayne0926** [comment]
> @PolymorphismException @caliban511 这个issue不讨论建政问题，相关话题自己滚一边去，这里只讨论巨大的二进制文件问题

你以为你是谁？

**Comment by Zaphkito** [comment]
> 1. 表达公民权利：在大多数民主国家，公民有权利表达自己的政治观点和意见。这是民主社会的一部分，而且是一个健康的民主国家所应该鼓励和保护的。键政不是一种贬义词，而是公民履行自己责任的一种方式。
> 2. 推动变革和改进：通过在网上发表自己的政治观点，可以促进社会的变革和政策的改进。公众的声音和意见对于政策制定是非常重要的，因为政府需要了解人民的需求和期望，才能更好地代表他们的利益。
> 3. 信息透明度和公开讨论：键政有助于增加政策制定的透明度，使政府更加负责和透明。公众的讨论和批评可以促使政府回应问题并解决民众的关切。
> 4. 社会参与的重要性：社会参与是民主社会的基石。通过键政，公民可以在政治决策中发挥积极作用，而不仅仅是被动接受政策。
> 5. 提高政治意识和知识：键政可以帮助人们更深入地了解政治议题和政策，从而成为更负责任的选民和公民。
> 
> 蜘蛛有没有正常人？一天到晚就是扣帽子和讲废话？害怕谈论政治？不关心政治？你他妈不关心这是政治来关心你你他妈买个菜车停哪里都是政治啊，你买个菜几块钱都是政治啊，一天到晚键政，用起别人的免费东西觉得自己牛逼的很，指点江山这里不满意哪里不满意挑这挑那，你他妈共产党没搞防火墙你用的着在这废话？妈连公民都不是还他妈的天天见证见证你的脑子已经被阉割啦谈到政治就害怕，妈的共产党在在你头上拉屎拉尿，上个github他妈的域名被污染，你在这里装看不见这就是你他妈的正义，他妈的好好的讨论区你在这里狗叫一样的放屁，还他妈键政键政，你怎么不叫共产党把防火墙撤了？你共爹都不让你上外网啦他妈的还出来狗叫维护你共爹

这里就不是让你发表这些东西的地方，这个issue也不针对相关的问题进行讨论，你去你该去的地方说去

**Comment by wayne0926** [comment]
> 

你也去你该去的地方发脾气去

**Comment by wayne0926** [comment]
> > 1. 表达公民权利：在大多数民主国家，公民有权利表达自己的政治观点和意见。这是民主社会的一部分，而且是一个健康的民主国家所应该鼓励和保护的。键政不是一种贬义词，而是公民履行自己责任的一种方式。
> > 2. 推动变革和改进：通过在网上发表自己的政治观点，可以促进社会的变革和政策的改进。公众的声音和意见对于政策制定是非常重要的，因为政府需要了解人民的需求和期望，才能更好地代表他们的利益。
> > 3. 信息透明度和公开讨论：键政有助于增加政策制定的透明度，使政府更加负责和透明。公众的讨论和批评可以促使政府回应问题并解决民众的关切。
> > 4. 社会参与的重要性：社会参与是民主社会的基石。通过键政，公民可以在政治决策中发挥积极作用，而不仅仅是被动接受政策。
> > 5. 提高政治意识和知识：键政可以帮助人们更深入地了解政治议题和政策，从而成为更负责任的选民和公民。
> > 
> > 蜘蛛有没有正常人？一天到晚就是扣帽子和讲废话？害怕谈论政治？不关心政治？你他妈不关心这是政治来关心你你他妈买个菜车停哪里都是政治啊，你买个菜几块钱都是政治啊，一天到晚键政，用起别人的免费东西觉得自己牛逼的很，指点江山这里不满意哪里不满意挑这挑那，你他妈共产党没搞防火墙你用的着在这废话？妈连公民都不是还他妈的天天见证见证你的脑子已经被阉割啦谈到政治就害怕，妈的共产党在在你头上拉屎拉尿，上个github他妈的域名被污染，你在这里装看不见这就是你他妈的正义，他妈的好好的讨论区你在这里狗叫一样的放屁，还他妈键政键政，你怎么不叫共产党把防火墙撤了？你共爹都不让你上外网啦他妈的还出来狗叫维护你共爹
> 
> 这里就不是让你发表这些东西的地方，这个issue也不针对相关的问题进行讨论，你去你该去的地方说去

你也去你该去的地方发脾气去

**Comment by lhn1989** [comment]
> > 可是他是开源作者，这不是他的义务。他也可以说：“`觉得我烦的，要不无视我，要不自己去死，有必要在这里指指点点吗`"
> 
> 一个负责的作者当然不能说这话，说难听的，开源就是你甘愿被白嫖 而且有没有一种可能，维护开源项目是作者的义务之一，如果你不打算听取他人意见也不打算维护那你干脆别开源了，这个情况的issue又不是就那么一两个，不少人全被depth 1怼回去或者直接无视了，他当这个作者干啥，他就应该把这个项目交给别人，你没这个能力，你也不是 contributor，遇到问题了我有提出的权利，应该是向谁提出？当然是 contributor，什么是开源精神，开源精神就是你有这个用爱发电的觉悟，没有觉悟也要拿出点诚意，如果没这个诚意我建议直接移交，或者直接停止维护等其他人，对任何一个项目来说用户就是天王老子，如果真有问题那就该解决，不然就是和各种大厂一样的大傻逼，如果他不想做了我就劝他趁早把仓库 private 了，自己慢慢玩去

一个但凡有点良知的人当然不能说这话，说难听的，使用开源就是白嫖别人的劳动成果
而且有没有一种可能，使用开源项目是你自己的选择之一，如果你不打算尊重别人的成功也不打算贡献任何力量那你干脆别用了，这个情况的issue不是就那么一两个，自己fork改完merge回来不行么，他当这个作者干的多了去了，你除了把作者和回复的人骂个遍你还会干啥，你就应该换个项目用，你没这个同理心，也不懂得怎么做人，遇到问题了去给人扣帽子去道理攻击别人，两个互不相识的陌生人别人为什么要惯着你？别人又没有生你养你。什么是开源精神，开源精神就是有共同兴趣有共同语言的人一起讨论一起贡献靠大家的力量把东西做好，如果这点觉悟都没有，总是以自我为中心，讲些幼稚的言论去碰瓷别人，讲脏话攻击别人，那真是没有存在的必要。对任何一个项目来说，作者和用户是平等的，如果真有问题那就自己动动手出份力，不然就是像现在一样大声哭喊自己无能。如果不能理解也不能接受，我建议去医院好好检查身体，身心健康比什么都重要。

**Comment by Cathgao** [comment]
![QQ图片20230725145741](https://github.com/vernesong/OpenClash/assets/21031564/52a36612-b9c8-4e77-94bc-3ece6d2c06bc)

**Comment by cczhr** [comment]
哈哈 急急急

**Comment by wayne0926** [comment]
![image](https://github.com/vernesong/OpenClash/assets/63389859/26b3e144-cecc-4d5e-86b8-601394fab6e7)

**Comment by wayne0926** [comment]
> https://twitter.com/chacha20_rbq/status/1684576477277491200?s=46&t=Z4L7kiO3IIFHBdt5l1q_sA
> ![image](https://user-images.githubusercontent.com/64299266/256637093-ba735c31-3a79-4199-8d0b-2513e03efb99.png)

![image](https://github.com/vernesong/OpenClash/assets/63389859/b2c3885c-f8e1-4e3e-b759-1f4a9b6373d8)

**Comment by caliban511** [comment]
> https://twitter.com/chacha20_rbq/status/1684576477277491200?s=46&t=Z4L7kiO3IIFHBdt5l1q_sA ![image](https://user-images.githubusercontent.com/64299266/256637093-ba735c31-3a79-4199-8d0b-2513e03efb99.png)

好家伙，这一下子就升华了主题。
享受被人追捧和拥护有什么错？圈子里人有亲疏远近有什么问题？这特么不都是人之常情吗？
要说深明大义什么的，这位发言人才是真的高屋建瓴，道德巅峰了属于是，，，😂😂😂
这以后搞个开源项目，还得先当圣人？
回头记得把圣经改一下，把玛利亚删了，把这位裱上去，，，😂😂😂

**Comment by Cathgao** [comment]
笑死，开源不收钱还得为人民服务，蜘蛛是不敢找收税的为人民服务吗，绷不住了

**Comment by jfjdskwiss221** [comment]
有一说一，几十G的仓库确实挺恶心人的，之前规则有问题，想帮忙动一下，但能力极度有限加上有点强迫症，只愿 fork 后通过 GitHub Desktop 修改再 pull 过来，然后 GitHub Desktop 里下了几分钟，进度不到百分之十，查了下文件大小，瞬间就不想干了。
之前有人说这边 commit 只有 V 大一个人辛苦，在我看来和这堆二进制有关系的。

**Comment by Zxz8964** [comment]
![IMG_20230716_151905_850.jpg](https://github.com/vernesong/OpenClash/assets/104437672/6d3c5e8c-2085-4fae-aa6e-f61c0b22d6a8)

**Comment by Zxz8964** [comment]
疑似自我意识过剩

**Comment by Karmylr** [comment]
> 这个问题，我很早以前就说过，作者他不弄也没办法，毕竟这是别人的仓库，别人想怎么玩就怎么玩，最多提意见，他接受不接受那是作者的意愿，不接受你也不应该这么怼，你这明显过激了

真的很疑惑为什么vernesong不弄= =

**Comment by 1715173329** [comment]
> 不会用git可以百度谷歌，没必要把自己变成傻逼

这话说得其实挺搞笑的，但毕竟以楼主的智商不足以知道 git 其实支持 partial clone。
如果你想贡献代码，克隆这个仓库只需要不到 40 MB 空间左右，包括完整历史提交记录。

**Comment by Unaude** [comment]
支不住了

**Comment by cczhr** [comment]
免费开源给你用，然后还要被你恶言相骂，真是巨婴逻辑。

**Comment by zgc** [comment]
你也没做什么贡献，不喜欢就别用，白嫖还这么理直气壮，很多开源作者不继续维护了就是你这里神奇人物导致的

**Comment by IlluminateDarkheat** [comment]
直接入典
![image](https://github.com/vernesong/OpenClash/assets/28666767/dec9ea5b-9ee3-4f8c-aa6a-65286475d9dd)

**Comment by Weoworks** [comment]
> > 这个问题，我很早以前就说过，作者他不弄也没办法，毕竟这是别人的仓库，别人想怎么玩就怎么玩，最多提意见，他接受不接受那是作者的意愿，不接受你也不应该这么怼，你这明显过激了
> 
> 真的很疑惑为什么vernesong不弄= =

丢了可惜（？

**Comment by zhqu1148980644** [comment]
该骂，并不是说强迫作者区改动，起码态度得端正吧，这一直关issue是怎么回事？起码给出些意见或者规划，这样子其他人可以参与改进。关闭issue真有点那种禁言/拉黑的感觉了，禁言、拉黑、闭嘴这些东西大家没受够吗？

**Comment by Karmylr** [comment]
> 该骂，并不是说强迫作者区改动，起码态度得端正吧，这一直关issue是怎么回事？起码给出些意见或者规划，这样子其他人可以参与改进。关闭issue真有点那种禁言/拉黑的感觉了，禁言、拉黑、闭嘴这些东西大家没受够吗？

issue是机器人关的。开发者只是一直不回应

**Comment by zgc** [comment]
> 该骂，并不是说强迫作者区改动，起码态度得端正吧，这一直关issue是怎么回事？起码给出些意见或者规划，这样子其他人可以参与改进。关闭issue真有点那种禁言/拉黑的感觉了，禁言、拉黑、闭嘴这些东西大家没受够吗？

在你说出这种话之前，建议你把每一层回复都认真读一遍。

**Comment by zgc** [comment]
> > 该骂，并不是说强迫作者区改动，起码态度得端正吧，这一直关issue是怎么回事？起码给出些意见或者规划，这样子其他人可以参与改进。关闭issue真有点那种禁言/拉黑的感觉了，禁言、拉黑、闭嘴这些东西大家没受够吗？
> 
> 在你说出这种话之前，建议你把每一层回复都认真读一遍。

看完回复之后，再把作者的commit list读一遍，看看是谁在秀智商。

**Comment by Weoworks** [comment]
看戏

**Comment by yellowsavant** [comment]
然而你骂了作者以后，事情解决了还是变更糟了？我很好奇

**Comment by czm180** [comment]
纯纯乐子人，你受不了可以去自己开个啊，又没人逼着你用，笑死，开源本意是为了大家一起共同进步一起维护，你又没为项目做任何贡献作者为啥要理你啊？还“为人民服务”，乐死了，你是觉着人家开源付出是义务了呗，不会说话完全可以闭嘴没必要在这找存在感骂开源作者，还为这点破事儿开个issue骂，哥们现实多不如意啊你这是。整天搁那嚷嚷为人民服务咋也没看到你做啥大东西让咱这些小人民用上啊，整天搁那屁贡献不做屁大项目不开嘴巴还叭叭个不停人家又不是你爹为啥要依着你啊乐子人，人家二进制确实麻烦但是你能说他违反规定了么？找不到合适的规定来限制人家就闭上你那狗嘴，早点回去吃点脑白金给你那发育不全的低能大脑补一补吧老铁

**Comment by SharerMax** [comment]
> > 不会用git可以百度谷歌，没必要把自己变成傻逼
> 
> 这话说得其实挺搞笑的，但毕竟以楼主的智商不足以知道 git 其实支持 partial clone。 如果你想贡献代码，克隆这个仓库只需要不到 40 MB 空间左右，包括完整历史提交记录。

https://git-scm.com/docs/partial-clone
https://git-scm.com/docs/git-clone#Documentation/git-clone.txt---filterltfilter-specgt
https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/
https://help.aliyun.com/document_detail/309002.html

**Comment by smallprogram** [comment]
git clone --filter=blob:none --branch=master https://github.com/vernesong/OpenClash.git
 
 不要生气啦

**Comment by jwkinko** [comment]
不是自己的东西，就不要多说了，更别人身攻击侵犯他人私有财产你已经违法了。如果你的邻居看你老婆涂得红色口红不好看，非要你涂成黑色，你怎么看。

**Comment by ddclaus** [comment]
虽然我不懂git，但是我作为一个看热闹的闲人，是不是可以这样理解楼主的意思：
老子TM为了你好，苦口婆心地劝你把我看不惯的“毛病”改了，你非但不改，还连搭理都不搭理我，让我夜以继日熬白了头写的好几本教育你的笔记全排不上用场，所以老子必须消灭你？

**Comment by vpei** [comment]
最好是能压缩一下，呵呵。

**Comment by zgc** [comment]
> 最好是能压缩一下，呵呵。

和楼主一样，智力智商都被压缩过，怎么的智力智商才会说出这样的话。

**Comment by vpei** [comment]
> > 最好是能压缩一下，呵呵。
> 
> 和楼主一样，智力智商都被压缩过，怎么的智力智商才会说出这样的话。

我是建议，作者不搞就不搞就是了。你是哪根葱，这么愤青做啥，没事想屁吃吗？

**Comment by zgc** [comment]
> > > 最好是能压缩一下，呵呵。
> 
> > 
> 
> > 和楼主一样，智力智商都被压缩过，怎么的智力智商才会说出这样的话。
> 
> 
> 
> 我是建议，作者不搞就不搞就是了。你是哪根葱，这么愤青做啥，没事想屁吃吗？主人还没讲话呢，一只狗乱叫啥。

前面的楼层看完了吗？所有分支的commit message看完了吗？你是在自嘲吗？

**Comment by vpei** [comment]
要低调。
