### ISSUE TITLE
希望程序提交到openwrt官方

### ISSUE THREAD

**Issue by liumingan** [vernesong/OpenClash#3396]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

感谢你的付出

### Describe the Solution

感谢你的付出

**Comment by Zaphkito** [comment]
https://github.com/vernesong/OpenClash/issues/3173
