### ISSUE TITLE
[Bug] 无论redir-host还是fake-ip模式，开启后本地网络手机的多个翻墙软件节点不通，请教...

### ISSUE THREAD

**Issue by ogr1432** [vernesong/OpenClash#3398]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.129-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

无论redir-host还是fake-ip模式，开启openclash后本地网络手机v2rayNG、Clash meat、Clash全部节点不通，关闭路由openclash节点正常使用。日志太长上传了几个设置界面截图供参考。

### Describe the Bug

单设备主路由，AD接管dnsmasq，上游dns留唯一地址指向openclash7874端口，生效后无论使用edir-host还是fake-ip模式，局域网手机v2rayNG测试真连接延迟全部节点均显示-1ms不通，手机更换clash meta和原版clash，节点均不通；关闭opclash，adg上游dns填任意服务器地址，开机手机软件各节点正常；尝试排除法换路由使用passwall，手机节点正常。隐约感觉是dns的问题，但不知修改哪个选项来解决，烦请热心人帮助，谢谢！提交issue较少，如有不规范请谅解。

### OpenClash Log

![2023-07-17_210849](https://github.com/vernesong/OpenClash/assets/6716791/9774144e-2c06-4070-9463-87aea5e3c553)
![2023-07-17_210814](https://github.com/vernesong/OpenClash/assets/6716791/df654451-d0fd-47af-b100-0792b0e76de2)
![2023-07-17_210829](https://github.com/vernesong/OpenClash/assets/6716791/572e0ecd-9220-4a8e-b5b7-0e53eb280eba)
![2023-07-17_210904](https://github.com/vernesong/OpenClash/assets/6716791/2041c927-ef22-448c-8b9e-5230e9fe0202)
![2023-07-17_210912](https://github.com/vernesong/OpenClash/assets/6716791/2b4bc996-3aec-416c-97fb-50da4ae34781)

### Expected Behavior

无。

**Comment by vernesong** [comment]
不通是测试节点连通性不通，可能走了两次代理，你可以设置绕过手机ip或者让手机连接路由器时停用自身代理软件

**Comment by ogr1432** [comment]
> 不通是测试节点连通性不通，可能走了两次代理，你可以设置绕过手机ip或者让手机连接路由器时停用自身代理软件

由于使用习惯的问题,通常在家庭局域网中也习惯不关手机代理软件,是因为opclash的短间隔更新订阅功能,想要换过来用一下; 所以关闭手机代理的情况下应当是可以的因为节点在路由的opwrt代理组件内正常... 只是不明白为什么别passwall运行时手机代理也正常使用且设备优先而opclash运行时手机上的节点就不通了，所以求助看是哪里设置问题

**Comment by vernesong** [comment]
跟规则有关系的，那些代理地址设置成直连应该就可以了
