### ISSUE TITLE
订阅更新失败

### ISSUE THREAD

**Issue by MRDHR** [vernesong/OpenClash#34]
如题，在使用的时候出现订阅更新失败的情况，用windows版的可以更新成功。
![20190928001823](https://user-images.githubusercontent.com/5576916/65784870-aa906300-e185-11e9-962e-8a59b2f1251e.png)
![QQ截图20190928002005](https://user-images.githubusercontent.com/5576916/65784889-bc720600-e185-11e9-9a4d-406f574c1879.png)

**Comment by vernesong** [comment]
可能是检查配置文件的时候发现有错误导致的，会在下个版本改进

**Comment by MRDHR** [comment]
好的，如果需要我这边做些什么，请回复我。现在更新不了订阅，使用会比较麻烦。

**Comment by vernesong** [comment]
https://github.com/vernesong/OpenClash/blob/357774a187f54f0ac48226fe302b39a4b2599e9b/luci-app-openclash/files/usr/share/openclash/openclash.sh#L21

把最后一个条件删了

**Comment by MRDHR** [comment]
需要我重新编译个ipk出来么，还是直接等你发布新版本？

**Comment by MRDHR** [comment]
已看到更新，晚上回去更新一下试试

**Comment by MRDHR** [comment]
更新clash后可以正常更新订阅了
