### ISSUE TITLE
覆写设置的DNS设置中，default-nameserver未覆盖订阅中的配置，仅做了添加

### ISSUE THREAD

**Issue by yyysuo** [vernesong/OpenClash#3405]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.132-beta

### Bug on Environment

Lean

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

覆写设置的DNS设置中，default-nameserver未覆盖订阅中的配置，仅做了添加。
比如订阅文件中的default-nameserver设置为：
  default-nameserver:
  - 223.5.5.5
  - 1.1.1.1
 
在luci中添加一条127.0.0.1:5454

配置文件变成了
  default-nameserver:
  - 223.5.5.5
  - 1.1.1.1
  - 127.0.0.1:5454

### Describe the Bug

见重现

### OpenClash Log

无

### Expected Behavior

覆写设置的DNS设置中，default-nameserver未覆盖订阅中的配置，仅做了添加。
比如订阅文件中的default-nameserver设置为：
  default-nameserver:
  - 223.5.5.5
  - 1.1.1.1
 
在luci中添加一条127.0.0.1:5454

配置文件应该为：
  default-nameserver:
  - 127.0.0.1:5454

**Comment by vernesong** [comment]
暂时是这样，因为一般机场配置也不会写这个

**Comment by qrekkwijjtx54** [comment]
遇到了相同的问题。请问有解决办法吗？每次都要手动更改比较麻烦
