### ISSUE TITLE
[Feature] 错误：更新的第三方规则文件【lhie1】含有未支持的新策略组，更新停止，请等待 OpenClash 版本更新适配...

### ISSUE THREAD

**Issue by 404user** [vernesong/OpenClash#3407]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

错误：更新的第三方规则文件【lhie1】含有未支持的新策略组，更新停止，请等待 OpenClash 版本更新适配...
我想请问一下这个要怎么解决。。。。。。。。。

### Describe the Solution

错误：更新的第三方规则文件【lhie1】含有未支持的新策略组，更新停止，请等待 OpenClash 版本更新适配...
我想请问一下这个要怎么解决。。。。。。。。。

**Comment by lingyunzhiss** [comment]
我猜你碰到的跟我一样的问题，lhie1写了一个OpenAi的策略条目，但没定义好，昨天已经修复了。不是openclash的问题。

**Comment by yuanzhuohao** [comment]
#3415 这里有解决问题方法。

**Comment by 404user** [comment]
> 我猜你碰到的跟我一样的问题，lhie1写了一个OpenAi的策略条目，但没定义好，昨天已经修复了。不是openclash的问题。

我的还是不行。哎

**Comment by 404user** [comment]
> #3415 这里有解决问题方法。

暂时可以用，不过openai的那个规则改了。好像不是很稳定，先换回pallwall用，等稳定了在说把。

**Comment by vernesong** [comment]
dev修了

**Comment by 404user** [comment]
> dev修了

需要重新安装一下吗？试了一下，好像还是不行。都是最新版本的了。

**Comment by vernesong** [comment]
规则有更新了，晚点再适配

**Comment by yuanzhuohao** [comment]
> 规则有更新了，晚点再适配

终于等到更新了。哈哈

**Comment by 404user** [comment]
> 规则有更新了，晚点再适配

感谢🙏

**Comment by 404user** [comment]
> 规则有更新了，晚点再适配

大佬，有计划什么时候更新一下吗？

**Comment by Faramitas** [comment]
> 

已经更新到最新了，还是提示 请等待 OpenClash 版本更新适配...

**Comment by young1119** [comment]
更新了还是一样，如何解决
错误：更新的第三方规则文件【lhie1】含有未支持的新策略组，更新停止，请等待 OpenClash 版本更新适配...

**Comment by xrh0905** [comment]
Not stale
