### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by zmx9712** [vernesong/OpenClash#3408]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

今天突然不能上外网的视频网站了，telegram和Instagram可以上

### Describe the Solution

目前通过clashx可以科学上网，openclash还是不行

**Comment by vernesong** [comment]
切到fakeip，fallback的DNS不通请更换
