### ISSUE TITLE
[Bug] dns突然出了问题

### ISSUE THREAD

**Issue by Louis-ui** [vernesong/OpenClash#3413]
### Verify Steps

- [x] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [x] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.129

### Bug on Environment

Lean

### Bug on Platform

Linux-arm64

### To Reproduce

无任何修改，正常使用openclash一段时间后发现连接出现问题，重新启动openclash后依旧复现无法连接的问题。

### Describe the Bug

重新启动openclash后，在短暂时间内dns解析正常，但是切换节点（中断全部链接）或者一段时间后，dns解析出问题（无法解析），yacd面板内不见请求的连接，折腾了一下发现将dns劫持的模式从dnsmasq换成防火墙转发后正常，或者将不改变dns劫持设置，将redir-host模式切换为fakeip模式，dns解析正常。

### OpenClash Log

太长了放不下，放个pastebin....
https://paste.opensuse.org/pastes/d078433a1806

### OpenClash Config

```shell
环境变量：
root@QWRT:~# env
USER=root
SSH_CLIENT=192.168.2.2 7646 22
SHLVL=1
HOME=/root
SSH_TTY=/dev/pts/0
PS1=\[\e]0;\u@\h: \w\a\]\u@\h:\w\$
LOGNAME=root
TERM=xterm-256color
PATH=/usr/sbin:/usr/bin:/sbin:/bin
SHELL=/bin/ash
PWD=/root
SSH_CONNECTION=192.168.2.2 7646 192.168.2.1 22
root@QWRT:~#
防火墙自定义规则：
iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53
iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53
[ -n "$(command -v ip6tables)" ] && ip6tables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53
[ -n "$(command -v ip6tables)" ] && ip6tables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53
系统配置：
好像没什么特别的内容，如需要后续再补充
```

### Expected Behavior

希望openclash使用dnsmasq劫持dns时，dns解析正常。

### Screenshots

暂无，如需后续再补充

**Comment by laobanbiefangcu** [comment]
同样的问题

**Comment by autumn187** [comment]
一样的问题 才发现换了fakeip模式能用。。。

**Comment by gzw13999** [comment]
这两天使用openclash 客户端DNS都陆续出现问题了

**Comment by Louis-ui** [comment]
正如V佬在群里说的，fallback的几个DNS挂了，修改相关设置后恢复正常，感谢V佬。

**Comment by chasecheese** [comment]
请问怎设置是如何修改的？

> 正如V佬在群里说的，fallback的几个DNS挂了，修改相关设置后恢复正常，感谢V佬。

**Comment by gzw13999** [comment]
> 正如V佬在群里说的，fallback的几个DNS挂了，修改相关设置后恢复正常，感谢V佬。

是的说详细点，我昨天研究到凌晨5点都没搞定。

**Comment by chasecheese** [comment]
Hi，我参考 https://github.com/vernesong/OpenClash/issues/3412#issuecomment-1646628451 修改了Overwrite Settings->DNS Settings->Name Server，其中UDP类型的DNS Server仅保留114.114.114.114，TUN模式正常了

**Comment by Turning-A** [comment]
https://t.me/iQDNSGroup
