### ISSUE TITLE
[Bug] dler.cloud域名的规则集出现404

### ISSUE THREAD

**Issue by yuanzhuohao** [vernesong/OpenClash#3415]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.129-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-armv7

### To Reproduce

No

### Describe the Bug

dler.cloud域名的规则集全部出现404，比如，其中一个https://dler.cloud/Rules/Clash/Provider/Reject.yaml。

### OpenClash Log

No

### OpenClash Config

```shell
No
```

### Expected Behavior

No

### Screenshots

No

**Comment by vernesong** [comment]
用github的地址

**Comment by CyEilo** [comment]
> 用github的地址

可否指路一下如何修改第三方规则集的源? /etc/openclash/ 下没有找到相关的文件

**Comment by yuanzhuohao** [comment]
> 用github的地址

同问，如何修改的？

**Comment by yuanzhuohao** [comment]
> 用github的地址

你好，什么意思？是重新安装openclash吗？

**Comment by CyEilo** [comment]
> > 用github的地址
> 
> 可否指路一下如何修改第三方规则集的源? /etc/openclash/ 下没有找到相关的文件

我找到了
openclash根目录
/usr/share/openclash/res/lhie1.yaml

这个文件里面的
https://dler.cloud/Rules/
替换成
https://github.com/dler-io/Rules/raw/main/

@yuanzhuohao

**Comment by yuanzhuohao** [comment]
> > > 用github的地址
> > 
> > 
> > 可否指路一下如何修改第三方规则集的源? /etc/openclash/ 下没有找到相关的文件
> 
> 我找到了 openclash根目录 /usr/share/openclash/res/lhie1.yaml
> 
> 这个文件里面的 https://dler.cloud/Rules/ 替换成 https://github.com/dler-io/Rules/raw/main/
> 
> @yuanzhuohao

可以了，谢谢
