### ISSUE TITLE
[Bug] 一键生成页面的策略组设置中, 如有使用meta内置的PASS策略, 该PASS策略在写入文件时会被忽略

### ISSUE THREAD

**Issue by CyEilo** [vernesong/OpenClash#3416]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.129-beta

### Bug on Environment

Lean

### Bug on Platform

Linux-arm64

### To Reproduce

0.45.121升级至129时发现此问题

### Describe the Bug

策略组中设置PASS后,如

```
config groups 
	option name 'Manual' 
	option type 'select' 
	list other_group 'PASS' 
	list other_group 'Proxy' 
	list other_group 'DIRECT
```

生成的123.yaml中只有 proxy和direct 如

```
config groups
	option name 'Manual'
	option type 'select'
	list other_group 'Proxy'
	list other_group 'DIRECT'
```

在"配置管理"页面左侧可以手动添加后保存,可正常使用

### OpenClash Log

日志无表现无报错

### Expected Behavior

在"配置管理"页面左侧可以手动添加后保存,可正常使用
但每次修改"一键生成"页面的设置后 需要重新手动修改

**Comment by vernesong** [comment]
添加的时候会检测，目前没有考虑pass这个内置组
