### ISSUE TITLE
[Feature] 希望出个功能，让所有ipv6直连，而不是代理或者禁用它

### ISSUE THREAD

**Issue by ighlES** [vernesong/OpenClash#3417]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

目前绝大部分机场都是不支持ipv6的，Clash代理ipv6只会导致大部分原本能访问ipv6网站无法访问，这问题应该大部分人都知道吧？很奇怪为什么一直没有解决

### Describe the Solution

让所有ipv6连接 DIRECT

**Comment by Karmylr** [comment]
让IPv6绕过clash内核就行了
