### ISSUE TITLE
[Feature]实验性：绕过中国大陆 IP   启用后中国大陆流量将不再经过内核，提升系统性能，此功能依赖于 Dnsmasq

### ISSUE THREAD

**Issue by jt8823** [vernesong/OpenClash#3427]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

这条设置的规则在哪里啊。
能不能自行配置？
指定某些域名或ip  不经过内核

### Describe the Solution

或者有没有指定局域网内某个ip不走clash内核的功能？

**Comment by LemonPAKA** [comment]
redir-host模式下，可以选择内网的某个ip或者mac地址不走clash代理

**Comment by LemonPAKA** [comment]
> redir-host模式下，可以选择内网的某个ip或者mac地址不走clash代理

另外，绕过大陆ip功能同希望增加类似已存在的黑名单功能（该功能为让域名强制走内核），让手动添加的域名也绕过clash内核

**Comment by LemonPAKA** [comment]
> > redir-host模式下，可以选择内网的某个ip或者mac地址不走clash代理
> 
> 另外，绕过大陆ip功能同希望增加类似已存在的黑名单功能（该功能为让域名强制走内核），让手动添加的域名也绕过clash内核

![image](https://github.com/vernesong/OpenClash/assets/17202894/8682026e-3f47-4ec4-a618-47e186de22f5)
找到了，但是暂不清楚支不支持正则。。。想把stun全弄进去得了（

**Comment by jt8823** [comment]
> > > redir-host模式下，可以选择内网的某个ip或者mac地址不走clash代理
> > 
> > 
> > 另外，绕过大陆ip功能同希望增加类似已存在的黑名单功能（该功能为让域名强制走内核），让手动添加的域名也绕过clash内核
> 
> ![image](https://user-images.githubusercontent.com/17202894/258869567-8682026e-3f47-4ec4-a618-47e186de22f5.png) 找到了，但是暂不清楚支不支持正则。。。想把stun全弄进去得了（

这个我试了,;没效果...

**Comment by jt8823** [comment]
> > redir-host模式下，可以选择内网的某个ip或者mac地址不走clash代理
> 
> 另外，绕过大陆ip功能同希望增加类似已存在的黑名单功能（该功能为让域名强制走内核），让手动添加的域名也绕过clash内核

我现在在用passwall2,  简单易用,  不泄露

**Comment by 631122919** [comment]
> > > > redir-host模式下，可以选择内网的某个ip或者mac地址不走clash代理
> > > 
> > > 
> > > 另外，绕过大陆ip功能同希望增加类似已存在的黑名单功能（该功能为让域名强制走内核），让手动添加的域名也绕过clash内核
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/17202894/258869567-8682026e-3f47-4ec4-a618-47e186de22f5.png) 找到了，但是暂不清楚支不支持正则。。。想把stun全弄进去得了（
> 
> 这个我试了,;没效果...

有效果啊 我试过了 不添加BING 用不了NEWBING 添加了就可以用

**Comment by 631122919** [comment]
> > > redir-host模式下，可以选择内网的某个ip或者mac地址不走clash代理
> > 
> > 
> > 另外，绕过大陆ip功能同希望增加类似已存在的黑名单功能（该功能为让域名强制走内核），让手动添加的域名也绕过clash内核
> 
> 我现在在用passwall2, 简单易用, 不泄露

PASSWALL2默认设置下遇到了tiktok刷不出来的问题 passwall就没问题不知道什么原因
