### ISSUE TITLE
由Redir-host无法使用引起的各种问题反馈

### ISSUE THREAD

**Issue by javierzhang0504** [vernesong/OpenClash#343]
处理器架构：linux-mipsle-softfloat
上版本【0.19.0-8】内核，一直使用Redir-host兼容模式，昨晚忽然失效，随即升级内核到最新版本，问题无解决。

多种尝试描述如下：
1，Redir-host（兼容模式）【内核：v0.19.0-12-gb1cf2ec】可成功启动openclash，但ip.sb和ipify显示ip段依然为国内，偶尔跳一下为国外，持续几秒又跳回国内ip段。且访问检查youtube：连接超时，外网无法访问。
尝试过开启自定义上游dns服务器，选中了默认的两个nameserver和3个fallback，依然无法访问。
2，fake-ip（增强模式）【内核：v0.19.0-12-gb1cf2ec】正常，但该模式下暴雪战网语音无法使用。
3，fake-ip（游戏模式）【内核：20200223-66-gd7cdb7e】一切正常，但是打开外网，youtube视频时加载速度慢。
4，fake-ip（tun）【内核v0.18.0-8-g68b82c9】无法正常启动opencalsh，看起来是内核问题。

**Comment by vernesong** [comment]
是不是内核的问题我无法判断。
另外redir模式有几率dns污染，建议fallback选上

**Comment by javierzhang0504** [comment]
> 是不是内核的问题我无法判断。
> 
> 另外redir模式有几率dns污染，建议fallback选上

你的内核没问题，是Tun版本内核无法启动。
dns污染了之后有什么办法清空缓存吗？

**Comment by vernesong** [comment]
客户端清理下缓存就行了，插件重启
tun模式你看控制面板有没有连接再判断是否成功
