### ISSUE TITLE
[Feature] 「一键生成配置文件」模板数量增加与自定义模板

### ISSUE THREAD

**Issue by LakeishaKowalczyk** [vernesong/OpenClash#3448]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

如果没有理解错的话，「一键生成配置文件」应该是「在线订阅转换」的本地版，可以避免服务不稳定或节点泄露

但是「一键生成配置文件」只有有限的三个模板，并且没有自行添加模板的入口，希望可以提供更多模板和手动添加的入口

![图片](https://github.com/vernesong/OpenClash/assets/14090545/b1e05951-d5e5-4bdc-9c36-33c63a5305fa)

![图片](https://github.com/vernesong/OpenClash/assets/14090545/dfeb1bc3-3b79-4fa8-9375-14fb76896368)

### Describe the Solution

自带更多模板，提供手动添加模板的方法

**Comment by 404user** [comment]
我也希望可以多一些，但是好像使用一键的用户好像不是很多。

**Comment by LakeishaKowalczyk** [comment]
> 我也希望可以多一些，但是好像使用一键的用户好像不是很多

可能是因为没有太多的介绍，还没领悟到它的好处

**Comment by 404user** [comment]
> > 我也希望可以多一些，但是好像使用一键的用户好像不是很多
> 
> 可能是因为没有太多的介绍，还没领悟到它的好处

是啊，这软件功能太多了，太散了，我也是摸索了很久才发现这个功能真的太好用了。太方便了。

**Comment by LakeishaKowalczyk** [comment]
@deuteros-gex 

所以「一键生成配置文件」也是在线转换，并不是本地？

**Comment by LakeishaKowalczyk** [comment]
@deuteros-gex 

上面一共有两张图
第二张「在线模板转换」是送到外部服务器我知道．

第一张「一键生成配置文件」一共只有 3 个模板，也是送到外部服务器吗？
![图片](https://github.com/vernesong/OpenClash/assets/14090545/3c6c1c1c-92bc-4370-ae3a-2e0bdf4ee108)

**Comment by deuteros-gex** [comment]
> @deuteros-gex
> 
> 上面一共有两张图 第二张「在线模板转换」是送到外部服务器我知道．
> 
> 第一张「一键生成配置文件」一共只有 3 个模板，也是送到外部服务器吗？ ![图片](https://user-images.githubusercontent.com/14090545/258835262-982cb0a2-3ff8-4897-841f-57d16e2d4cd5.png)

my bad。
你说的这个确实是本地拼接。
模板在/usr/share/openclash/res目录下，看得懂的话大可以自定义模板（修改现有的lhie1.yaml、ConnersHua_return.yaml、ConnersHua.yaml，也就相当于自己定制模板了）。
我唯一没想到的是这个功能还真有人用。。

**Comment by deuteros-gex** [comment]
这个功能最主要的问题可能在于除了作者本人，没人知道该怎么用。
#3312

**Comment by 404user** [comment]
https://github.com/vernesong/OpenClash/issues/3407
你们可以看看，好像这个BUG 还没解决。。。

**Comment by CyEilo** [comment]
这个非常好用 但是第一次用的时候肯定一脸懵逼 如果需要自定义的话还需要有第三方规则组支持
不过我一般不会一直开启这个选项 而是一键生成后根据自己的需要修改调整

**Comment by LakeishaKowalczyk** [comment]
经过长年累月的潜心研究，终于研制出使用「一键生成」代替在线订阅转换的方法，也不再需要第三方的模板

原理就是「一键生成 - 代理集」可以直接订阅并正则筛选节点，再喂给自定义的策略组（策略组里可以再筛选一次），这样就可以完全控制配置文件中的 proxy-groups 部分
配合「覆写设置 - 自定义规则」与「规则覆加」功能对  rules 的自定义与第三方订阅，基本可以实现对  proxy-groups 和 rules 的随意改写，而配置文件的其它部分一般也没有修改的需求

附友情且贴心提供的用于排除节点的正则表达式 `^((?!不需要的节点名A|不需要的节点B).)*$`

**Comment by 404user** [comment]
> 

要是能直接用这个就好了。https://acl4ssr-sub.github.io/

**Comment by 404user** [comment]
> 经过长年累月的潜心研究，终于研制出使用「一键生成」代替在线订阅转换的方法，也不再需要第三方的模板
> 
> 原理就是「一键生成 - 代理集」可以直接订阅并正则筛选节点，再喂给自定义的策略组（策略组里可以再筛选一次），这样就可以完全控制配置文件中的 proxy-groups 部分 配合「覆写设置 - 自定义规则」与「规则覆加」功能对 rules 的自定义与第三方订阅，基本可以实现对 proxy-groups 和 rules 的随意改写，而配置文件的其它部分一般也没有修改的需求
> 
> 附友情且贴心提供的用于排除节点的正则表达式 `^((?!不需要的节点名A|不需要的节点B).)*$`

可以写个具体的教程吗？

**Comment by LakeishaKowalczyk** [comment]
> 可以写个具体的教程吗？

哪种教程，下一步下一步的那种保姆级教程嘛？这个得图文混排写很长或者做个视频才行的，我很懒的
不过可以把笔记复制粘贴在这里，需要的同学可以参考参考

话说经过数十年的苦心钻研，我又进化了．现在可以随意改写配置文件而不再有有任何限制．需要灵活运用「配置订阅」「上传 yaml 配置文件」「一键生成策略组／代理集／服务器节点配置」「覆写设置 - 自定义规则」「规则附加」这些功能


```
#### OpenClash 代理配置文件完全自定义（本地）

##### 配置订阅

1. 用途 —— 自动生成 yaml 配置文件
    1. 订阅服务器节点，供策略组选用
    2. 使用其自动生成的「port」「dns」「fallback」等「一键生成」、「覆写设置 - 自定义规则」「规则附加」不能修改的部分
2. 设置
    1. 无须设置在线转换和过滤，由后面的「一键生成」功能接管．甚至可以将节点全部过滤不用，完全通过代理集引入节点


##### 上传 yaml 代理配置文件

1. 用途 —— 手动上传 yaml 配置文件，代替配置订阅．可完全自定义「一键生成」、「覆写设置 - 自定义规则」「规则附加」不能修改的部分
2. 设置
    1. 不再配置订阅，仅通过代理集获取节点
    2. 手动编写 yaml 配置文件，并上传使用
    3. 可通过改写其它 yaml 模板简化编写（比如通过订阅下载或第三方模板转换得来的配置文件）


##### 「一键生成」功能

1. 用途 —— 自定义配置文件中的 proxy-groups 区域
2. 配置流程
    1. 读取配置
    2. 配置「自定义策略组」
        1. 新建 Url-test 型「自动选择」，用于自动切换节点，放入默认生效的 Select 策略组（一般是最上面那组）
        2. 新建 Select 型「排除港日」作为「覆写设置 - 自定义规则」的前置设置，用作部分网站使用
        3. 新建 Url-test 型「排除港日_自动」，放入「排除港日」用于自动切换
        4. 新建 Select 型「谷歌专用」作为「覆写设置 - 自定义规则」的前置设置，用作谷歌专用
        5. 新建 Url-test 型「谷歌专用_自动」，放入「谷歌专用」用于自动切换
    3. 通过代理集订阅服务器节点
        1. 优点是可将多个节点批量喂给策略组，而使用订阅的服务器节点只能手动到每一个服务器节点中修改添加
        2. 正则表达式过滤
            1. 排除不需要的节点 `^((?!不需要的节点名A|不需要的节点名B).)*$`
    4. 启用「保留配置」
        1. 「新节点默认策略组」是指通过订阅新增的节点自动进入哪些策略组
            1. 如果采用手动上传 yaml 配置文件，则无需配置
            2. 如果使用订阅引用服务器节点则按需选择．如果留空，通过订阅新增的节点将不会自动进组生效


##### 覆写设置 - 自定义规则

1. 用途 —— 追加自定义的分流 rules
2. 设置 —— 按需使用


##### 规则附加

1. 用途 —— 追加第三方订阅的 rules
```

**Comment by 404user** [comment]
> > 可以写个具体的教程吗？
> 
> 哪种教程，下一步下一步的那种保姆级教程嘛？这个得图文混排写很长或者做个视频才行的，我很懒的 不过可以把笔记复制粘贴在这里，需要的同学可以参考参考
> 
> 话说经过数十年的苦心钻研，我又进化了．现在可以随意改写配置文件而不再有有任何限制．需要灵活运用「配置订阅」「上传 yaml 配置文件」「一键生成策略组／代理集／服务器节点配置」「覆写设置 - 自定义规则」「规则附加」这些功能
> 
> ```
> #### OpenClash 代理配置文件完全自定义（本地）
> 
> ##### 配置订阅
> 
> 1. 用途 —— 自动生成 yaml 配置文件
>     1. 订阅服务器节点，供策略组选用
>     2. 使用其自动生成的「port」「dns」「fallback」等「一键生成」、「覆写设置 - 自定义规则」「规则附加」不能修改的部分
> 2. 设置
>     1. 无须设置在线转换和过滤，由后面的「一键生成」功能接管．甚至可以将节点全部过滤不用，完全通过代理集引入节点
> 
> 
> ##### 上传 yaml 代理配置文件
> 
> 1. 用途 —— 手动上传 yaml 配置文件，代替配置订阅．可完全自定义「一键生成」、「覆写设置 - 自定义规则」「规则附加」不能修改的部分
> 2. 设置
>     1. 不再配置订阅，仅通过代理集获取节点
>     2. 手动编写 yaml 配置文件，并上传使用
>     3. 可通过改写其它 yaml 模板简化编写（比如通过订阅下载或第三方模板转换得来的配置文件）
> 
> 
> ##### 「一键生成」功能
> 
> 1. 用途 —— 自定义配置文件中的 proxy-groups 区域
> 2. 配置流程
>     1. 读取配置
>     2. 配置「自定义策略组」
>         1. 新建 Url-test 型「自动选择」，用于自动切换节点，放入默认生效的 Select 策略组（一般是最上面那组）
>         2. 新建 Select 型「排除港日」作为「覆写设置 - 自定义规则」的前置设置，用作部分网站使用
>         3. 新建 Url-test 型「排除港日_自动」，放入「排除港日」用于自动切换
>         4. 新建 Select 型「谷歌专用」作为「覆写设置 - 自定义规则」的前置设置，用作谷歌专用
>         5. 新建 Url-test 型「谷歌专用_自动」，放入「谷歌专用」用于自动切换
>     3. 通过代理集订阅服务器节点
>         1. 优点是可将多个节点批量喂给策略组，而使用订阅的服务器节点只能手动到每一个服务器节点中修改添加
>         2. 正则表达式过滤
>             1. 排除不需要的节点 `^((?!不需要的节点名A|不需要的节点名B).)*$`
>     4. 启用「保留配置」
>         1. 「新节点默认策略组」是指通过订阅新增的节点自动进入哪些策略组
>             1. 如果采用手动上传 yaml 配置文件，则无需配置
>             2. 如果使用订阅引用服务器节点则按需选择．如果留空，通过订阅新增的节点将不会自动进组生效
> 
> 
> ##### 覆写设置 - 自定义规则
> 
> 1. 用途 —— 追加自定义的分流 rules
> 2. 设置 —— 按需使用
> 
> 
> ##### 规则附加
> 
> 1. 用途 —— 追加第三方订阅的 rules
> ```

太感谢了！谢谢你！

**Comment by vernesong** [comment]
自己装个subc就行了啊

**Comment by LennoC** [comment]
这其实是个好功能，可以考虑直接把subconverter集成进去再给人自定义模板。
之前这里一点修改那里一点改动的，一个自定义模板其实就能解决了。
没人用的原因可能是年久失修+模板太少，于是更没人用了……

不用在线版的原因：隐私和安全问题。
