### ISSUE TITLE
群晖DDNS获取IP异常

### ISSUE THREAD

**Issue by socekin** [vernesong/OpenClash#345]
开启OpenClash后，群晖DDNS服务获取到的IP地址不是宽带的公网IP，变成了海外IP。请问如何解决？谢谢

**Comment by TwoBall** [comment]
把synology.com直连就行了

**Comment by socekin** [comment]
如何设置呢？

**Comment by socekin** [comment]
把synology.com加入直连无效。现在DDNS是一直读取的“IP.SB    海外:”的IP。没有读取到“IP.PC    国内:”的IP

**Comment by TwoBall** [comment]
> 把synology.com加入直连无效。现在DDNS是一直读取的“IP.SB 海外:”的IP。没有读取到“IP.PC 国内:”的IP

你的ddns服务商域名加入直连。加在头部规则里

**Comment by socekin** [comment]
ddns服务商域名加入规则直连，还是无法解决这个问题。只要开启翻墙，NAS外网访问就断开

**Comment by z98401** [comment]
我也遇到这个问题了，只有设定走GFWlist才能正确获得地址！

**Comment by ttyycool** [comment]
把whatismyip.akamai.com设为直连就行了

**Comment by ChiaSang** [comment]
> 把whatismyip.akamai.com设为直连就行了

还是没有解决这个问题，我的也是这个

**Comment by ChiaSang** [comment]
> 开启OpenClash后，群晖DDNS服务获取到的IP地址不是宽带的公网IP，变成了海外IP。请问如何解决？谢谢

我通过抓包找到了一种解决方法，可以试试。
抓包发现在使用代理后会向一个域名为on-us-checkip5.synology.com的地址解析你的ip，实际有多个解析服务器，通过ipip.net 查询为digitalocean.com的服务，可以尝试使用把此ip直连的方式

AS14061 | 已标注 | 68.183.160.0/20 | DIGITALOCEAN-ASN - DigitalOcean, LLC, US

注意直连ip为这一段子网掩码为20的地址全部直连

**Comment by lim0513** [comment]
> > 开启OpenClash后，群晖DDNS服务获取到的IP地址不是宽带的公网IP，变成了海外IP。请问如何解决？谢谢
> 
> 我通过抓包找到了一种解决方法，可以试试。
> 抓包发现在使用代理后会向一个域名为on-us-checkip5.synology.com的地址解析你的ip，实际有多个解析服务器，通过ipip.net 查询为digitalocean.com的服务，可以尝试使用把此ip直连的方式
> 
> AS14061 | 已标注 | 68.183.160.0/20 | DIGITALOCEAN-ASN - DigitalOcean, LLC, US
> 
> 注意直连ip为这一段子网掩码为20的地址全部直连

感谢分享，目前看好像可以解决问题。

**Comment by zx0922** [comment]
> > 开启OpenClash后，群晖DDNS服务获取到的IP地址不是宽带的公网IP，变成了海外IP。请问如何解决？谢谢
> 
> 我通过抓包找到了一种解决方法，可以试试。
> 抓包发现在使用代理后会向一个域名为on-us-checkip5.synology.com的地址解析你的ip，实际有多个解析服务器，通过ipip.net 查询为digitalocean.com的服务，可以尝试使用把此ip直连的方式
> 
> AS14061 | 已标注 | 68.183.160.0/20 | DIGITALOCEAN-ASN - DigitalOcean, LLC, US
> 
> 注意直连ip为这一段子网掩码为20的地址全部直连



> 把whatismyip.akamai.com设为直连就行了

感谢2位分享

**Comment by lim0513** [comment]
好像没有根治问题，现在ddns在国外和国内来回横跳。。。。

**Comment by zx0922** [comment]
> 好像没有根治问题，现在ddns在国外和国内来回横跳。。。。

好像是有点问题，我直接换成gwflist模式可以了

**Comment by Onpicex** [comment]
访问控制，添加一条不就可以了么。

**Comment by zx0922** [comment]
> 访问控制，添加一条不就可以了么。

关键是加哪条，楼上几个说的加了不行

**Comment by lim0513** [comment]
> > 访问控制，添加一条不就可以了么。
> 
> 关键是加哪条，楼上几个说的加了不行

我给nas加到不翻墙列表了...

**Comment by Onpicex** [comment]
> > > 访问控制，添加一条不就可以了么。
> > 
> > 
> > 关键是加哪条，楼上几个说的加了不行
> 
> 我给nas加到不翻墙列表了...

正解

**Comment by zx0922** [comment]
> > > 访问控制，添加一条不就可以了么。
> > 
> > 
> > 关键是加哪条，楼上几个说的加了不行
> 
> 我给nas加到不翻墙列表了...



> > > > 访问控制，添加一条不就可以了么。
> > > 
> > > 
> > > 关键是加哪条，楼上几个说的加了不行
> > 
> > 
> > 我给nas加到不翻墙列表了...
> 
> 正解

额 你们没搞清需求吧。需求是，nas需要翻墙，但是不要获取到翻墙服务器的ip

**Comment by dengpeng** [comment]
可以试试把下面这些域名加入直连列表：

* checkip.synology.com
* checkipv6.synology.com
* checkport.synology.com
* ddns.synology.com
* account.synology.com

参考：[What websites does Synology NAS connect to when running services or updating software?](https://www.synology.com/en-global/knowledgebase/DSM/tutorial/Service_Application/What_websites_does_Synology_NAS_connect_to_when_running_services_or_updating_software)

**Comment by evanjiang404** [comment]
> 可以试试把下面这些域名加入直连列表：
> 
> * checkip.synology.com
> * checkipv6.synology.com
> * checkport.synology.com
> * ddns.synology.com
> * account.synology.com
> 
> 参考：[What websites does Synology NAS connect to when running services or updating software?](https://www.synology.com/en-global/knowledgebase/DSM/tutorial/Service_Application/What_websites_does_Synology_NAS_connect_to_when_running_services_or_updating_software)

实测有效，代理模式绕过大陆IP

**Comment by lrgcx** [comment]
把nas的内网ip设为直连。

**Comment by kidd31** [comment]
把这两个ip地址添加到不走代理的广域网ip列表里
142.93.81.166
138.68.9.145

**Comment by layouswitch** [comment]
所有楼上的ip和域名都填到直连名单了，还是不行 
ddns还是会在海外和国内ip之间来回横跳
之前直接synology.com加入直连就可以的获得真实ip的，现5次有四次获取的是是海外的ip
猜想群晖应该是修改了策略，会同时向多个ip service请求获取所在地的ip 。
改成gfwlist模式可以获得真实的ip，但我实际场景需要用到“中国列表以外”会更方便

**Comment by lim0513** [comment]
已经放弃了，现在用docker连阿里云的ddns

**Comment by layouswitch** [comment]
问题解决了，过来回复下，原来是NAS DNS服务器设置的问题
我之前在网络-网络界面-局域网那里面设置的网关DNS是192.168.2.2（旁路由，出国）
但是不知道什么时候手贱在网络-常规-手动配置DNS服务器那里设置了192.168.2.1（主路由，仅仅拨号）
所以获取的IP会来回跳
我把手动配置DNS那里的删掉就能识别到正确的国内IP了
当然前提是白名单里把楼上的域名和IP 都加到直连名单了

**Comment by zpengcom** [comment]
我发现NAS在ddns.synology.com 前会先请求这个地址： checkip.dyndns.org
而且这个地址直连打不开（获取不到IP)，但是用代理打开得到的就是代理的IP.

我用的是clash 在策略组里把其它流量设置成海外流量时就会遇到这个问题。。

**Comment by RideWindOne** [comment]
> 我发现NAS在ddns.synology.com 前会先请求这个地址： checkip.dyndns.org
> 而且这个地址直连打不开（获取不到IP)，但是用代理打开得到的就是代理的IP.
> 
> 我用的是clash .. 最后还是直接设备绕行解决

也是用的Clash用上面所有方法试过都不行，又不想用设备绕行。把checkip.dyndns.org加到直连。直接显示dns错误。搞不懂。

**Comment by zpengcom** [comment]
> > 我发现NAS在ddns.synology.com 前会先请求这个地址： checkip.dyndns.org
> > 而且这个地址直连打不开（获取不到IP)，但是用代理打开得到的就是代理的IP.
> > 我用的是clash .. 最后还是直接设备绕行解决
> 
> 也是用的Clash用上面所有方法试过都不行，又不想用设备绕行。把checkip.dyndns.org加到直连。直接显示dns错误。搞不懂。

绕行也不行，我现在没用clash, 难受

**Comment by RideWindOne** [comment]
> > > 我发现NAS在ddns.synology.com 前会先请求这个地址： checkip.dyndns.org
> > > 而且这个地址直连打不开（获取不到IP)，但是用代理打开得到的就是代理的IP.
> > > 我用的是clash .. 最后还是直接设备绕行解决
> > 
> > 
> > 也是用的Clash用上面所有方法试过都不行，又不想用设备绕行。把checkip.dyndns.org加到直连。直接显示dns错误。搞不懂。
> 
> 绕行也不行，我现在没用clash, 难受

群晖手动设置了一个国内DNS，然后把checkip.dyndns.org 给reject了，然后正常了。

**Comment by ljtao020** [comment]
> 可以试试把下面这些域名加入直连列表：
> 
> * checkip.synology.com
> * checkipv6.synology.com
> * checkport.synology.com
> * ddns.synology.com
> * account.synology.com
> 
> 参考：[Synology NAS在运行服务或更新软件时会连接哪些网站？](https://www.synology.com/en-global/knowledgebase/DSM/tutorial/Service_Application/What_websites_does_Synology_NAS_connect_to_when_running_services_or_updating_software)

虽然是挖坟，不过终于可以解决我这个问题了，谢谢，我用的是pw，之前只能绕开设备来搞

**Comment by shuxuejia** [comment]
> > 可以试试把下面这些域名加入直连列表：
> > 
> > * checkip.synology.com
> > * checkipv6.synology.com
> > * checkport.synology.com
> > * ddns.synology.com
> > * account.synology.com
> > 
> > 参考：[Synology NAS在运行服务或更新软件时会连接哪些网站？](https://www.synology.com/en-global/knowledgebase/DSM/tutorial/Service_Application/What_websites_does_Synology_NAS_connect_to_when_running_services_or_updating_software)
> 
> 虽然是挖坟，不过终于可以解决我这个问题了，谢谢，我用的是pw，之前只能绕开设备来搞

perfect! 也解决了我的问题，过几天再看看反复不反复了

**Comment by gkl1368** [comment]
这个问题好像目前还不能解决

**Comment by tyejuan** [comment]
我给大家一种方法， 百分百能解决问题，把synology这个关键词加入直连就可以了，随便你使用什么方法编辑config.yaml,加上一条  “- DOMAIN-KEYWORD,-synology,DIRECT”，不含引号，保存，重启clash服务即可。

**Comment by hprandom** [comment]
之前把以上的所有方法都设置过了都无效。
今天把代理模式从 Script 改成 Rule （Fake-IP的增强模式），NAS目前IP获取正常，过几天再看看情况。

**Comment by fengyunkkx** [comment]
> > 可以试试把下面这些域名加入直连列表：
> > 
> > * checkip.synology.com
> > * checkipv6.synology.com
> > * checkport.synology.com
> > * ddns.synology.com
> > * account.synology.com
> > 
> > 参考：[What websites does Synology NAS connect to when running services or updating software?](https://www.synology.com/en-global/knowledgebase/DSM/tutorial/Service_Application/What_websites_does_Synology_NAS_connect_to_when_running_services_or_updating_software)
> 
> 实测有效，代理模式绕过大陆IP

目前把这几个地址加到 config.yaml 后，亲测有效——

```
 - DOMAIN-SUFFIX,checkip.synology.com,DIRECT
 - DOMAIN-SUFFIX,checkipv6.synology.com,DIRECT
 - DOMAIN-SUFFIX,checkport.synology.com,DIRECT
 - DOMAIN-SUFFIX,ddns.synology.com,DIRECT
 - DOMAIN-SUFFIX,account.synology.com,DIRECT
```

配完记得重启下 Clash 服务，不然不会自动读取配置文件。

最后那位加关键词的方法应该也是可行的
```
- DOMAIN-KEYWORD,-synology,DIRECT
```

**Comment by lim0513** [comment]
再共享两个地址：
checkipv6.quickconnect.to
global.quickconnect.to

**Comment by gkl1368** [comment]
共享一些ip
##Synology                                                                                                            
##account.synology.com                                                                                                
- IP-CIDR,54.192.18.23/32,DIRECT                                                                                      
- IP-CIDR,54.192.18.27/32,DIRECT                                                                                      
- IP-CIDR,54.192.18.29/32,DIRECT                                                                                      
- IP-CIDR,54.192.18.107/32,DIRECT                                                                                     
##checkip.synology.com                                                                                                
- IP-CIDR,104.248.79.120/32,DIRECT                                                                                    
- IP-CIDR,138.68.28.244/32,DIRECT                                                                                     
- IP-CIDR,142.93.81.166/32,DIRECT                                                                                     
- IP-CIDR,159.65.77.153/32,DIRECT                                                                                     
- IP-CIDR,159.89.129.146/32,DIRECT                                                                                    
- IP-CIDR,159.89.142.52/32,DIRECT                                                                                     
- IP-CIDR,165.227.63.200/32,DIRECT                                                                                    
- IP-CIDR,206.189.214.49/32,DIRECT                                                                                    
##dddns-global.quickconnect.to                                                                                        
- IP-CIDR,44.236.224.47/32,DIRECT                                                                                     
- IP-CIDR,44.239.15.20/32,DIRECT                                                                                      
- IP-CIDR,44.239.77.234/32,DIRECT                                                                                     
- IP-CIDR,44.240.201.191/32,DIRECT                                                                                    
- IP-CIDR,44.241.103.184/32,DIRECT                                                                                    
- IP-CIDR,52.10.31.158/32,DIRECT                                                                                      
##global.quickconnect.to                                                                                              
- IP-CIDR,52.80.147.155/32,DIRECT                                                                                     
- IP-CIDR,54.222.157.210/32,DIRECT                                                                                    
- IP-CIDR,54.222.235.145/32,DIRECT                                                                                    
- IP-CIDR,54.223.206.219/32,DIRECT
加入自定义列表，可以完美获取ip

**Comment by Tao311** [comment]
把在群晖上设置的ddns删除，在路由器上开启ddns。路由器上的可以设置几种获取ip的方式，选择pppoe地址，这个问题就完美的解决了

**Comment by hprandom** [comment]
> 把在群晖上设置的ddns删除，在路由器上开启ddns。路由器上的可以设置几种获取ip的方式，选择pppoe地址，这个问题就完美的解决了

这样能用SSL吗？强迫症看不得“不安全”😂

**Comment by Tao311** [comment]
> > 把在群晖上设置的ddns删除，在路由器上开启ddns。路由器上的可以设置几种获取ip的方式，选择pppoe地址，这个问题就完美的解决了
> 
> 这样能用SSL吗？强迫症看不得“不安全”😂

可以的，有选项是不是打开https

**Comment by warn1n9** [comment]
不要用 fake IP 模式就好了

**Comment by wey-gu** [comment]
> 可以试试把下面这些域名加入直连列表：
> 
> * checkip.synology.com
> * checkipv6.synology.com
> * checkport.synology.com
> * ddns.synology.com
> * account.synology.com
> 
> 参考：[What websites does Synology NAS connect to when running services or updating software?](https://www.synology.com/en-global/knowledgebase/DSM/tutorial/Service_Application/What_websites_does_Synology_NAS_connect_to_when_running_services_or_updating_software)

亲测这个有效。

**Comment by zouyong94** [comment]
同样的问题测试完楼上所有域名都不行，打开openclash后阿里云的DDNS就访问不了群晖的5000端口，关闭就好了。    现在群晖想走梯子，有没有好的办法既可以开openclash，ddns正常，nas还可以走梯子

**Comment by lim0513** [comment]
> 

阿里云DDNS用docker装 ddns-go，用国内域名获取IP。

**Comment by sfdzkj** [comment]
如果是passwall ，在规则列表里加上
# nas
synology.cn
synology.com
synology.com
quickconnect.to
quickconnect.cn
akamai.com
dyndns.com
dyndns.org
dnsapi.cn
然后passwall 基本设置里DNS  清空 IPSET。如果不清空设置不会立马生效

**Comment by wanhmr** [comment]
> > > 可以试试把下面这些域名加入直连列表：
> > > 
> > > * checkip.synology.com
> > > * checkipv6.synology.com
> > > * checkport.synology.com
> > > * ddns.synology.com
> > > * account.synology.com
> > > 
> > > 参考：[What websites does Synology NAS connect to when running services or updating software?](https://www.synology.com/en-global/knowledgebase/DSM/tutorial/Service_Application/What_websites_does_Synology_NAS_connect_to_when_running_services_or_updating_software)
> > 
> > 
> > 实测有效，代理模式绕过大陆IP
> 
> 目前把这几个地址加到 config.yaml 后，亲测有效——
> 
> ```
>  - DOMAIN-SUFFIX,checkip.synology.com,DIRECT
>  - DOMAIN-SUFFIX,checkipv6.synology.com,DIRECT
>  - DOMAIN-SUFFIX,checkport.synology.com,DIRECT
>  - DOMAIN-SUFFIX,ddns.synology.com,DIRECT
>  - DOMAIN-SUFFIX,account.synology.com,DIRECT
> ```
> 
> 配完记得重启下 Clash 服务，不然不会自动读取配置文件。
> 
> 最后那位加关键词的方法应该也是可行的
> 
> ```
> - DOMAIN-KEYWORD,-synology,DIRECT
> ```

亲测有效

**Comment by wjy000** [comment]
> quickconnect.to
> quickconnect.cn
> akamai.com
> dyndns.com
> dyndns.org
> dnsapi.cn

没有效果, 还是来回横跳

**Comment by hejiajin720** [comment]
试试把这个加入Clash的直连名单：

# - DOMAIN-SUFFIX,synology.cn,DIRECT
# - DOMAIN-SUFFIX,synology.com,DIRECT
# - DOMAIN-SUFFIX,quickconnect.to,DIRECT
# - DOMAIN-SUFFIX,quickconnect.cn,DIRECT
# - DOMAIN-SUFFIX,akamai.com,DIRECT
# - DOMAIN-SUFFIX,dyndns.com,DIRECT
# - DOMAIN-SUFFIX,dyndns.org,DIRECT

至少对我有用（fake-ip模式下）

**Comment by 404user** [comment]
感谢各位，已经解决了。

**Comment by GOUKI9999** [comment]
之前偷懒，结果还是在这里找到系统答案，多谢以上诸位

**Comment by GOUKI9999** [comment]
最后补充一个目前我在用的，如上面某位所说，我通过刷新群晖的ddns，并在clash端查看规则，可见它的确是在向含有群晖域名的和其他几个公用的api查询域名，所以只能保证这些api的域名都进DIRECT，同时还有几个看起来新加的域名，再加上我个人用的几个ddns域名（通常也是请求域名和查询ip域名），同一问题也出现在威联通系统上，所以还有几个qnap域名

DOMAIN-SUFFIX,tpddns.cn
DOMAIN-SUFFIX,duckdns.org
DOMAIN-SUFFIX,dns-dns.com
DOMAIN-SUFFIX,3322.org
DOMAIN-SUFFIX,3322.net
DOMAIN-SUFFIX,nat123.com
DOMAIN-SUFFIX,dynu.com
DOMAIN-SUFFIX,changeip.com
DOMAIN-SUFFIX,myddns.rocks
DOMAIN-SUFFIX,ddnsfree.com
DOMAIN-SUFFIX,dyndns.org
DOMAIN-SUFFIX,dnsapi.cn #似乎是会查询的公用ip返回api
DOMAIN-SUFFIX,api.ipify.org #似乎是会查询的公用ip返回api
DOMAIN-SUFFIX,api.nn.ci #似乎是会查询的公用ip返回api
DOMAIN-SUFFIX,checkip.synology.com
DOMAIN-SUFFIX,checkipv6.synology.com
DOMAIN-SUFFIX,checkport.synology.com
DOMAIN-SUFFIX,ddns.synology.com
DOMAIN-SUFFIX,account.synology.com
DOMAIN-SUFFIX,quickconnect.to
DOMAIN-SUFFIX,QuICKcoNnECt.tO #和上一个类似但是新的 
DOMAIN-SUFFIX,quickconnect.cn
DOMAIN-SUFFIX,synology.cn
DOMAIN-SUFFIX,synocommunity.com
DOMAIN-SUFFIX,update.qnap.com
DOMAIN-SUFFIX,myqnapcloud.com

**Comment by songchi9** [comment]
> 可以试试把下面这些域名加入直连列表：
> 
> * checkip.synology.com
> * checkipv6.synology.com
> * checkport.synology.com
> * ddns.synology.com
> * account.synology.com
> 
> 参考：[What websites does Synology NAS connect to when running services or updating software?](https://www.synology.com/en-global/knowledgebase/DSM/tutorial/Service_Application/What_websites_does_Synology_NAS_connect_to_when_running_services_or_updating_software)

感谢大佬，解决了。

**Comment by qjwq** [comment]
> 我给大家一种方法，百分百能解决问题，把synology这个关键字加进去直连就可以了，随方便你用什么方法编辑config.yaml,加上一条DOMAINIR-ECT-s”- ，不包含引号，保存，重新启动冲突服务即可。



> 

想请教一下为什么关键字是-synology而不是synology，多个符号有什么特别意义还是无心之举呢？谢谢

**Comment by HU914** [comment]
- DOMAIN-SUFFIX,checkip.synology.com,DIRECT
- DOMAIN-SUFFIX,checkipv6.synology.com,DIRECT 
- DOMAIN-SUFFIX,checkport.synology.com,DIRECT 
- DOMAIN-SUFFIX,ddns.synology.com,DIRECT 
- DOMAIN-SUFFIX,account.synology.com,DIRECT 
- DOMAIN-SUFFIX,checkip.dyndns.org,REJECT 

- SRC-IP-CIDR,142.93.81.166/32,REJECT #匹配数据发起IP(直连)

有效配置

**Comment by McJ1on** [comment]
改用pw了 oc一点不好用

**Comment by HU914** [comment]
上面的失效了，目前解决办法：
使用ddns-go，但是这个好像要配合ddnsto

**Comment by 933127** [comment]
> DOMAIN-KEYWORD,-synology,DIRECT

你说的不全对，你用host模式会造成DNS泄露

**Comment by 632460935** [comment]
经过测试，我是这样成功的走直连，
fake-ip模式
添加两条，
例如域名是*.ddnsddns.com 在fake-ip-filter下添加一条
nameserver-policy下添加一条本地的218.4.4.4 DNS解析

fake-ip-filter:
  - "+.ddnsddns.com"
	
	
nameserver-policy:
  "+.ddnsddns.com":
    - 218.4.4.4

**Comment by fastxteam** [comment]
> > > 可以试试把下面这些域名加入直连列表：
> > > 
> > > * checkip.synology.com
> > > * checkipv6.synology.com
> > > * checkport.synology.com
> > > * ddns.synology.com
> > > * account.synology.com
> > > 
> > > 参考：[What websites does Synology NAS connect to when running services or updating software?](https://www.synology.com/en-global/knowledgebase/DSM/tutorial/Service_Application/What_websites_does_Synology_NAS_connect_to_when_running_services_or_updating_software)
> > 
> > 
> > 实测有效，代理模式绕过大陆IP
> 
> 目前把这几个地址加到 config.yaml 后，亲测有效——
> 
> ```
>  - DOMAIN-SUFFIX,checkip.synology.com,DIRECT
>  - DOMAIN-SUFFIX,checkipv6.synology.com,DIRECT
>  - DOMAIN-SUFFIX,checkport.synology.com,DIRECT
>  - DOMAIN-SUFFIX,ddns.synology.com,DIRECT
>  - DOMAIN-SUFFIX,account.synology.com,DIRECT
> ```
> 
> 配完记得重启下 Clash 服务，不然不会自动读取配置文件。
> 
> 最后那位加关键词的方法应该也是可行的
> 
> ```
> - DOMAIN-KEYWORD,-synology,DIRECT
> ```

https://kb.synology.com/en-global/DSM/tutorial/What_websites_does_Synology_NAS_connect_to_when_running_services_or_updating_software

我用这个好像是可以了

**Comment by songchi9** [comment]
感谢指导。

wanqiang.liu ***@***.***>于2025年9月23日 周二20:25写道：
