### ISSUE TITLE
[Bug] 一键生成自定义策略组，正则表达式包含转义 \ 则无效

### ISSUE THREAD

**Issue by LakeishaKowalczyk** [vernesong/OpenClash#3453]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.129-beta

### Bug on Environment

Lean, Other

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

1. 进入「一键生成」- 「策略组配置」- 「代理集节点筛选」
2. 设置为 `5` 并应用，筛选成功（部分节点被筛走）
3. 设置为空并应用，恢复默认成功
4. 设置为 `\.5`并应用，筛选无效（所有节点都保留）

### Describe the Bug

正则中包含转义 `\` 将使该次设置失效

### OpenClash Log

（日志中未见任何错误或警告）

### Expected Behavior

通过正则式 `\[倍率\:2\.5\]` 可以筛出所有包含字符串 `[倍率:2.5]` 的节点

### Screenshots

![图片](https://github.com/vernesong/OpenClash/assets/14090545/7c0a6912-53fd-475c-be7a-3088814ac2f0)

![图片](https://github.com/vernesong/OpenClash/assets/14090545/3631dd85-231a-44b9-9c13-7d496ce0e00b)

**Comment by LakeishaKowalczyk** [comment]
@vernesong 

大佬快来，真的有 BUG
现在想要排除 `深港专线转香港BGP[M][倍率:2.5]` 而保留 `深港专线转香港BGP9[M][倍率:2.5]` 却没有办法做到．因为后面的 `[M][倍率:2.5]` 必须要转义才能用，但是只要加入 `\` 设置就会失效

**Comment by vernesong** [comment]
这个应该是内核的问题

**Comment by LakeishaKowalczyk** [comment]
@vernesong 
应该怎么解决呢？只能去 Dreamacro/Clash 发 issue 吗？
