### ISSUE TITLE
Meta Dashboard 控制面板节点被隐藏

### ISSUE THREAD

**Issue by qin9125** [vernesong/OpenClash#3458]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.139-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

MacOS Chrome浏览器打开 Meta Dashboard 控制面板节点剩余 10 个

### Describe the Bug

当只有 10 个节点时打开 Meta Dashboard 控制面板展开按钮会消失，导致第10 个节点被隐藏，以前十几个节点没有注意到，但是当你点击其他菜单栏如日志或者规则后再次点击代理展开按钮出现，测试手机端 Chrome 正常 Mac Safari端正常

### OpenClash Log

无

### Expected Behavior

能正常显示节点信息不被隐藏

### Screenshots

<img width="1743" alt="image" src="https://github.com/vernesong/OpenClash/assets/32502941/3081d1d3-1915-497a-9659-ceb6470a68ea">
<img width="1659" alt="image" src="https://github.com/vernesong/OpenClash/assets/32502941/13bf55ca-779c-40f8-bd01-c5a3c7f29170">

**Comment by ReredDffed** [comment]
你自己都写了 Meta Dashboard ...
https://github.com/MetaCubeX/Razord-meta

**Comment by qin9125** [comment]
Win11 edge 测试依旧第一次打开控制面板展开按钮会消失
