### ISSUE TITLE
升级0.37.3后，发现一些bug

### ISSUE THREAD

**Issue by MatrixxZENG** [vernesong/OpenClash#346]
最近看到插件更新，第一时间下载了最新版本来。然后发现了一些问题。
http://192.168.2.1:9090/ui这个页面打开是空白了，用yacd的控制面板经常导致分流出现问题。
经常出现google打不开，然后许久之后才能够完全识别需要代理的流量。
我一直以为是我用的节点不稳定的问题，但是后来发现我用桌面端的clash并没有出现卡顿。
我今天降级到0.37.2版本后，DashBoard控制面板打开正常，分流正常。

**Comment by vernesong** [comment]
控制面板只是提供一个操作界面，跟这些情况没关系，页面空白可以尝试刷新一下浏览器缓存，或者F12到浏览器控制台看一下报错

**Comment by MatrixxZENG** [comment]
那请教一下作者，分流比较慢，一段时间后再上Google需要等大概半分钟才能正确访问是不是由于规则中的那个检测延迟的链接连接不稳定导致的？IPV6的DHCP已关闭。

0.37.3还出现过有几率重启插件无法出去的情况，然后需要再次重启插件才能正常。这个我可以确认节点一定是正常的。

**Comment by vernesong** [comment]
用curl -v测试

**Comment by MatrixxZENG** [comment]
那我晚上回家再测试一下，多谢作者解答

**Comment by MatrixxZENG** [comment]
还有一个问题想请教一下作者。
添加ss节点的时候，混淆选择tls，host为空的情况下，应用配置后混淆会自动变为none，是插件不支持host为空吗？

**Comment by vernesong** [comment]
支持

**Comment by MatrixxZENG** [comment]
OK，那我再研究研究，多谢作者。

**Comment by vernesong** [comment]
> OK，那我再研究研究，多谢作者。

别试了，刚刚看了一下，脚本有问题，我稍后改改
