### ISSUE TITLE
[Feature] 求指导，如何给http/socks5代理增加ssl加密？

### ISSUE THREAD

**Issue by immoke** [vernesong/OpenClash#3464]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

我已经将7890和7891端口映射到公网了，为比如说阿里云服务器临时提供加速使用，但是我看默认都是http代理，这样有些敏感信息还是会在公网暴露，我尝试改过将7890前面增加nginx+ssl反向代理，但是反向代理后根本无法通过认证（我还给代理服务器增加了账号认证），在网上搜了很久，都没有相关的教程，所以请教各位大佬，如何给http/sock5代理增加ssl加密？

### Describe the Solution

如何给http/sock5代理增加ssl加密？

### Describe Alternatives

如何给http/sock5代理增加ssl加密？

### Additional Context

如何给http/sock5代理增加ssl加密？

**Comment by EndOfNewFall** [comment]
没有相关的教程是因为没有必要，给http/sock5代理增加ssl加密就是画蛇添足。代理服务器只负责转发，即使增加了ssl加密，你到代理服务器是安全的，但是代理服务器到目标网站是没有加密的。别忘了，现在的网站都是https而不是http，除非你的证书出问题，没有量子计算机，你传输的数据受到“绝对”保证。

**Comment by immoke** [comment]
有ssl很有必要。这种需求的场景在于云服务器，调用本地的代理服务器。必须经过互联网，且希望在中间传输中加密。
而且，世界上没有绝对，我只希望相对安全一些，不被某些部门抓到证据而已。

**Comment by EndOfNewFall** [comment]
那你应该用“真VPN”例如WireGuard,或者直接用Tor

**Comment by rubbit233** [comment]
解决了吗
