### ISSUE TITLE
全新openwrt安装openclash后出现异常

### ISSUE THREAD

**Issue by okphilo** [vernesong/OpenClash#347]
之前使用都是正常的，openclash和clash的版本都未变，把我的树莓派4b重装了openwrt，然后安装openclash后就出现了以下情况

![image](https://user-images.githubusercontent.com/56027888/79697372-f38c3e00-82b4-11ea-9713-8536d9771cf0.png)

![image](https://user-images.githubusercontent.com/56027888/79697352-e2433180-82b4-11ea-94dc-72f37981b075.png)

**Comment by vernesong** [comment]
自己拉源码编译一下，安装包还没上传

**Comment by okphilo** [comment]
https://github.com/vernesong/OpenClash/releases/download/v0.37.3-beta/clash-linux-armv8.tar.gz

请问这个安装包不适用树莓派4b吗？

**Comment by vernesong** [comment]
> https://github.com/vernesong/OpenClash/releases/download/v0.37.3-beta/clash-linux-armv8.tar.gz
> https://github.com/vernesong/OpenClash/releases/download/v0.37.3-beta/luci-app-openclash_0.37.3-beta_all.ipk
> 
> 请问这个安装包不适用树莓派4b吗？

仓库源码修复了还没编译

**Comment by itnewgay** [comment]
大佬 。树莓派4B，在全局里的基本设置里，CPU架构怎么选啊？
![Uploading image.png…]()

**Comment by hcym** [comment]
4b树莓派选armv8的
