### ISSUE TITLE
如何配置VLESS-TCP-XTLS-Vision，支持吗？

### ISSUE THREAD

**Issue by crazynet999** [vernesong/OpenClash#3473]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

有疑问，请问支持吗？如何配置？VLESS-TCP-XTLS-Vision，支持吗？

### Describe the Solution

一直寻找，没看到答案

**Comment by Jacky-Bruse** [comment]
支持的，用meta内核
