### ISSUE TITLE
升级到v0.45.141-beta，OpenClash 崩溃，重启后丢失

### ISSUE THREAD

**Issue by laosuye** [vernesong/OpenClash#3476]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.141-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

升级到v0.45.141-beta，OpenClash 崩溃，重启后丢失

### Describe the Bug

升级到v0.45.141-beta，OpenClash 崩溃，重启后丢失

### OpenClash Log

升级到v0.45.141-beta，OpenClash 崩溃，重启后丢失

### Expected Behavior

升级到v0.45.141-beta，OpenClash 崩溃，重启后丢失

**Comment by YSblack** [comment]
我也遇到了，经常性

**Comment by guocongjie** [comment]
你只要把github版本下载页面里提醒的依赖安装一遍就可以正常升级！

**Comment by Sakuramasiro** [comment]
> 你只要把github版本下载页面里提醒的依赖安装一遍就可以正常升级！
无法更新，会报错的

**Comment by bangbang93** [comment]
从`v0.45.103-beta`升级到任意版本都会出现这个问题，升级后OpenWRT会在10s内重启，重启后插件列表里就没有OpenWRT了。并且ext4文件系统会损坏，会ro挂载，感觉像是kernel panic导致的重启。

所有依赖均已更新
```
root@h:~# opkg install coreutils-nohup bash dnsmasq-full curl ca-certificates ipset ip-full libcap libcap-bin ruby ruby-yaml kmod-tun kmod-inet-diag unzip kmod-nft-tproxy luci-compat luci luci-base
Package coreutils-nohup (9.0-2) installed in root is up to date.
Package bash (5.2.15-1) installed in root is up to date.
Package dnsmasq-full (2.86-16) installed in root is up to date.
Package curl (8.2.1-1) installed in root is up to date.
Package ca-certificates (20230311-1) installed in root is up to date.
Package ipset (7.15-2) installed in root is up to date.
Package ip-full (5.15.0-4) installed in root is up to date.
Package libcap (2.63-1) installed in root is up to date.
Package libcap-bin (2.63-1) installed in root is up to date.
Package ruby (3.0.6-1) installed in root is up to date.
Package ruby-yaml (3.0.6-1) installed in root is up to date.
Package kmod-tun (5.10.161-1) installed in root is up to date.
Package kmod-inet-diag (5.10.161-1) installed in root is up to date.
Package unzip (6.0-8) installed in root is up to date.
Package kmod-nft-tproxy (5.10.161-1) installed in root is up to date.
Package luci-compat (git-23.093.42303-ef4cd04) installed in root is up to date.
Package luci (git-23.093.42303-d58cd69) installed in root is up to date.
Package luci-base (git-23.119.80898-65ef406) installed in root is up to date.
```

x86/64 OpenWrt 22.03.3 r20028-43d71ad93e

**Comment by paladin4fan** [comment]
> 从`v0.45.103-beta`升级到任意版本都会出现这个问题，升级后启动OpenClash，在clash启动成功（主程序显示两个运行中）后，OpenWRT会在10s内重启，重启后插件列表里就没有OpenClash了。并且ext4文件系统会损坏，会ro挂载，感觉像是kernel panic导致的重启。
> 
> 所有依赖均已更新
> 
> ```
> root@h:~# opkg install coreutils-nohup bash dnsmasq-full curl ca-certificates ipset ip-full libcap libcap-bin ruby ruby-yaml kmod-tun kmod-inet-diag unzip kmod-nft-tproxy luci-compat luci luci-base
> Package coreutils-nohup (9.0-2) installed in root is up to date.
> Package bash (5.2.15-1) installed in root is up to date.
> Package dnsmasq-full (2.86-16) installed in root is up to date.
> Package curl (8.2.1-1) installed in root is up to date.
> Package ca-certificates (20230311-1) installed in root is up to date.
> Package ipset (7.15-2) installed in root is up to date.
> Package ip-full (5.15.0-4) installed in root is up to date.
> Package libcap (2.63-1) installed in root is up to date.
> Package libcap-bin (2.63-1) installed in root is up to date.
> Package ruby (3.0.6-1) installed in root is up to date.
> Package ruby-yaml (3.0.6-1) installed in root is up to date.
> Package kmod-tun (5.10.161-1) installed in root is up to date.
> Package kmod-inet-diag (5.10.161-1) installed in root is up to date.
> Package unzip (6.0-8) installed in root is up to date.
> Package kmod-nft-tproxy (5.10.161-1) installed in root is up to date.
> Package luci-compat (git-23.093.42303-ef4cd04) installed in root is up to date.
> Package luci (git-23.093.42303-d58cd69) installed in root is up to date.
> Package luci-base (git-23.119.80898-65ef406) installed in root is up to date.
> ```
> 
> x86/64 OpenWrt 22.03.3 r20028-43d71ad93e

+1 但是我是更早开始出现这个问题的 而我能升级到0.45.103 是做了两个操作 不知道是哪个比较对症
1、卸载旧版本ipk 重启路由器后再安装新版ipk
2、IPv6代理模式切换到redirect

**Comment by bangbang93** [comment]
1. 卸载103后重启openwrt
2. 安装141
3. 启动openclash依旧会导致系统重启

此时我将ipv6代理模式切换为tun（原先是tproxy），目前已经稳定运行12hr

**Comment by bangbang93** [comment]
> > 1. 卸载103后重启openwrt
> > 2. 安装141
> > 3. 启动openclash依旧会导致系统重启
> > 
> > 此时我将ipv6代理模式切换为tun（原先是tproxy），目前已经稳定运行12hr
> 
> 确认这样能解决吗？最后有解决吗？我更新到最新版本后遇到类似问题，谢谢。

目前按照这个方法使用至今没有再出现过问题
