### ISSUE TITLE
菜单变英文了,

### ISSUE THREAD

**Issue by lxwq** [vernesong/OpenClash#348]
![openclash](https://user-images.githubusercontent.com/51162826/79703422-5ba34a00-82de-11ea-9d8e-db138217fc3e.PNG)
编译时只要加入openclash,services主菜单就变成英文,去掉就正常,不知道是什么原因

**Comment by caesarjing** [comment]
另外有没有办法强制软件全部都以中文显示？openwrt固件是英文的，想在openclash里面使用种中文界面

**Comment by zxlhhyccc** [comment]
> 另外有没有办法强制软件全部都以中文显示？openwrt固件是英文的，想在openclash里面使用种中文界面

你用的是哪个op源码编译的？估计是官方的源码吧？如果是官方源码，你仔细看看官方luci。。。。
