### ISSUE TITLE
[Bug] 无法保存规则配置

### ISSUE THREAD

**Issue by LzwCracker** [vernesong/OpenClash#3482]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.141-brta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-386, Linux-amd64(x86-64), Linux-amd64-v3(x86-64)

### To Reproduce

上传配置后点击应用会弹出错误对话框

### Describe the Bug

1

### OpenClash Log

1

### OpenClash Config

```shell
1
```

### Expected Behavior

1

### Screenshots

![image](https://github.com/vernesong/OpenClash/assets/18252512/b93f9f6d-1bdf-4b20-a856-4a7689d46771)
![image](https://github.com/vernesong/OpenClash/assets/18252512/4dbfa9ea-2a45-4725-b538-6ec1f0a837fc)

**Comment by asnon** [comment]
一样呢，请问解决了么？
