### ISSUE TITLE
[question] 为什么一开openclash就导致公网ip频繁变更

### ISSUE THREAD

**Issue by haryswu** [vernesong/OpenClash#3485]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.141-bate

### Bug on Environment

Official OpenWrt

### Bug on Platform

All

### To Reproduce

本意是通过阿里云dns动态解析来解决域名绑定访问群晖

![0zm0m12000c0p8cqy9449](https://github.com/vernesong/OpenClash/assets/107027980/cc01b1b4-3f1c-4630-9991-5a280a61f19a)

### Describe the Bug

但这个月开始只要开openclash，就出发公网ip频繁变动，一天几十次

关闭openclash，公网ip变动就没那么频繁了，几天才一次

### OpenClash Log

<img width="1170" alt="image" src="https://github.com/vernesong/OpenClash/assets/107027980/8cf6ee4b-94a0-4ac4-929f-d97f50863034">

### Expected Behavior

暂时还没有修复

**Comment by ZeroBaiCyber** [comment]
我使用没有你个频繁变更,而且你这个变更很有规律可循,你找下哪边你配置了 整10分钟相关,()然后公网频繁变更,只有一中情况,就是你重新拨号了 找下日志看下为啥重启

**Comment by madman43** [comment]
使用openclash后win11的手机连接也是频繁申请配对，应该也是ip变更了导致，还有就是zerotier延迟500ms，并大部分时间连不上
