### ISSUE TITLE
[Bug] 切换到Meta模式后奈飞分流失效

### ISSUE THREAD

**Issue by kay-zhu** [vernesong/OpenClash#3486]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.141-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

Meta模式后奈飞分流失效

### Describe the Bug

Meta模式后奈飞分流失效

### OpenClash Log

无

### Expected Behavior

希望尽快修复，谢谢！

**Comment by zakizou** [comment]
我是meta模式，广告reject rules providers 规则无效

**Comment by chenmin600383** [comment]
切换到meta内核后，看了下日志，连接奈飞有一些直接是ip，客户端无法识别成奈飞。  所以我在规则设置里把这些ip都指定为奈飞策略，问题就解决了。
