### ISSUE TITLE
[Feature] 能否自动关闭或定时清理超时的活动连接

### ISSUE THREAD

**Issue by kenwestern** [vernesong/OpenClash#3488]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

活动连接经常蹦哒到800多个，导致弱鸡软路由CPU负载很，新打开的访问延迟很大，最可怕的是开视频会议总是中断，一查其实没几个人在访问，都是一些已经关掉的或杀掉的连接。这时在yacd手动点击close all connections清掉活动连接就正常了。

### Describe the Solution

这个close all connections功能有命令行可以实现吗？
如果有能否针对特定ip、连接时长过滤？
最希望实现每2小时自动清理一次超过10分钟的活动连接

**Comment by haohaoget** [comment]
我也遇见了同样的问题
https://github.com/vernesong/OpenClash/issues/1396#issuecomment-2041004937
