### ISSUE TITLE
Watchdog: Clash Core Problem, Restart.

### ISSUE THREAD

**Issue by ChanterelleFan** [vernesong/OpenClash#349]
vernesong先生，您好。
更新v0.37.3-beta，路由器定时重启后，openclash会出现故障。
每天早上五点，软路由定时重启，重启后openclash提示以下内容：

time="2020-04-19T21:01:36Z" level=info msg="Start initial compatible provider Microsoft"
time="2020-04-19T21:01:36Z" level=info msg="Start initial compatible provider Apple"
time="2020-04-19T21:01:36Z" level=info msg="Start initial compatible provider Spotify"
time="2020-04-19T21:01:36Z" level=info msg="Start initial compatible provider Proxy"
time="2020-04-19T21:01:36Z" level=info msg="Start initial compatible provider PayPal"
time="2020-04-19T21:01:36Z" level=info msg="Start initial compatible provider AsianTV"
time="2020-04-19T21:01:36Z" level=info msg="Start initial compatible provider AdBlock"
time="2020-04-19T21:01:36Z" level=info msg="Start initial compatible provider Steam"
time="2020-04-19T21:01:36Z" level=info msg="Start initial compatible provider Speedtest"
time="2020-04-19T21:01:36Z" level=info msg="Start initial compatible provider Domestic"
time="2020-04-19T21:01:36Z" level=info msg="Start initial compatible provider Netflix"
time="2020-04-19T21:01:36Z" level=info msg="Start initial compatible provider GlobalTV"
time="2020-04-19T21:01:36Z" level=info msg="Start initial compatible provider Others"
time="2020-04-19T21:01:36Z" level=info msg="Start initial compatible provider Telegram"
time="2020-04-19T21:01:36Z" level=info msg="Start initial compatible provider Netease Music"
time="2020-04-19T21:01:36Z" level=info msg="Start initial compatible provider Auto - UrlTest"
2020-04-20 05:01:30 OpenClash Start Successful
2020-04-20 05:01:45 Watchdog: Clash Core Problem, Restart.
time="2020-04-19T21:01:46Z" level=info msg="Start initial compatible provider Microsoft"
time="2020-04-19T21:01:46Z" level=info msg="Start initial compatible provider AdBlock"
time="2020-04-19T21:01:46Z" level=info msg="Start initial compatible provider Netease Music"
time="2020-04-19T21:01:46Z" level=info msg="Start initial compatible provider Domestic"
time="2020-04-19T21:01:46Z" level=info msg="Start initial compatible provider Spotify"
time="2020-04-19T21:01:46Z" level=info msg="Start initial compatible provider Apple"
time="2020-04-19T21:01:46Z" level=info msg="Start initial compatible provider Netflix"
time="2020-04-19T21:01:46Z" level=info msg="Start initial compatible provider GlobalTV"
time="2020-04-19T21:01:46Z" level=info msg="Start initial compatible provider Speedtest"
time="2020-04-19T21:01:46Z" level=info msg="Start initial compatible provider Others"
time="2020-04-19T21:01:46Z" level=info msg="Start initial compatible provider AsianTV"
time="2020-04-19T21:01:46Z" level=info msg="Start initial compatible provider Auto - UrlTest"
time="2020-04-19T21:01:46Z" level=info msg="Start initial compatible provider Steam"
time="2020-04-19T21:01:46Z" level=info msg="Start initial compatible provider Telegram"
time="2020-04-19T21:01:46Z" level=info msg="Start initial compatible provider PayPal"
time="2020-04-19T21:01:46Z" level=info msg="Start initial compatible provider Proxy"
time="2020-04-19T21:01:51Z" level=fatal msg="Parse config error: Configuration file /etc/openclash/config/Dler.yaml is empty"
2020-04-20 05:01:46 OpenClash Can Not Start, Please Check The Error Info And Try Again

查看对应的yaml文件，的确为0KB，手动更新托管配置后，openclash又可正常运行。重现问题的过程中，将内核、yaml文件均设为777。手动重启路由也故障，唯有早上自动重启后会出现此问题。

路由器及openclash相关配置如下：
![image](https://user-images.githubusercontent.com/24196916/79705828-9c549080-82e9-11ea-909f-806cbb4cd036.png)
![image](https://user-images.githubusercontent.com/24196916/79705846-aaa2ac80-82e9-11ea-92d3-df0a2d5c3c8b.png)
![image](https://user-images.githubusercontent.com/24196916/79705870-baba8c00-82e9-11ea-91fc-4a78666a7d2f.png)

您开发辛苦了！

**Comment by vernesong** [comment]
不可能变成空文件啊，自动更新配置文件了？

**Comment by ChanterelleFan** [comment]
我也觉得特别奇怪，突然出现的问题。
5:00 路由器自动重启
6:00 配置文件自动更新
按理在5:00的时候，配置文件是正常的。我观察了好几天，每次都是启动15S之后，日志提示core错误。
2020-04-20 05:01:30 OpenClash Start Successful
2020-04-20 05:01:45 Watchdog: Clash Core Problem, Restart.

**Comment by vernesong** [comment]
知道了，最近订阅的问题有点多
