### ISSUE TITLE
[Bug] 开启绕过大陆IP后微信语音，腾讯会议接通后说话对方听不到

### ISSUE THREAD

**Issue by spritewdx** [vernesong/OpenClash#3491]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.141-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-arm64

### To Reproduce

开启绕过大陆IP，可以正常访问内外网，但微信语音，腾讯会议发言对方都无法收到，关闭绕过大陆IP既正常

### Describe the Bug

开启绕过大陆IP，可以正常访问内外网，但微信语音，腾讯会议发言对方都无法收到，关闭绕过大陆IP既正常

### OpenClash Log

日志没有怪异的地方，除了微信语音，游戏偶尔掉帧，其他正常

### Expected Behavior

希望大神解答

**Comment by ZeroBaiCyber** [comment]
你这个问题 你先要定位到你的bug点, 其实这块你可以这么调试,
先查看下你自己机器ip(),然后发一段长语音,你发过去,然后看面板日志 这段时间比较大的长文件的ip发向了那个策略

**Comment by spritewdx** [comment]
大佬，开了绕过大陆IP就没有日志了，不开是正常的
