### ISSUE TITLE
请问如何在Fake-IP 模式上面使用设备白名单

### ISSUE THREAD

**Issue by Sucre-2333** [vernesong/OpenClash#3492]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

请问如何在Fake-IP 模式上面使用设备白名单

### Describe the Solution

请问如何在Fake-IP 模式上面使用设备白名单

**Comment by vernesong** [comment]
dns改成防火墙转发

**Comment by Leo4242** [comment]
> dns改成防火墙转发

DNS改成防火墙后白名单功能还是不能正常工作，请问是怎么回事？
