### ISSUE TITLE
一键生成中读取配置存在bug

### ISSUE THREAD

**Issue by himho** [vernesong/OpenClash#3505]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.141-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

重新更新配置后再次读取配置就会出现！

### Describe the Bug

一键配置里面读取配置后 节点信息不能读取完整。

### OpenClash Log

OpenClash 调试日志

生成时间: 2023-09-11 21:10:59
插件版本: v0.45.141-beta
隐私提示: 上传此日志前请注意检查、屏蔽公网IP、节点、密码等相关敏感信息

```

#===================== 系统信息 =====================#

主机型号: QEMU Standard PC (i440FX + PIIX - Common KVM processor : 4C8T
固件版本: OpenWrt SNAPSHOT r5952-d126f73d9
LuCI版本: git-23.126.47457-0290ff2-1
内核版本: 5.15.110
处理器架构: x86_64

#此项有值时,如不使用IPv6,建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: 

DNS劫持: Dnsmasq 转发
#DNS劫持为Dnsmasq时，此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 127.0.0.1#7874

#===================== 依赖检查 =====================#

dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
libcap: 已安装
libcap-bin: 已安装
ruby: 已安装
ruby-yaml: 已安装
ruby-psych: 已安装
ruby-pstore: 已安装
kmod-tun(TUN模式): 已安装
luci-compat(Luci >= 19.07): 未安装
kmod-inet-diag(PROCESS-NAME): 已安装
unzip: 已安装
iptables-mod-tproxy: 已安装
kmod-ipt-tproxy: 已安装
iptables-mod-extra: 已安装
kmod-ipt-extra: 已安装
kmod-ipt-nat: 已安装

#===================== 内核检查 =====================#

运行状态: 运行中
运行内核：Meta
进程pid: 24646
运行权限: 24646: cap_dac_override,cap_net_bind_service,cap_net_admin,cap_net_raw,cap_sys_ptrace,cap_sys_resource=eip
运行用户: nobody
已选择的架构: linux-amd64

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 2023.08.17-3-g32a983f
Tun内核文件: 存在
Tun内核运行权限: 正常

Dev内核版本: v1.18.0-6-ge4cd3e5
Dev内核文件: 存在
Dev内核运行权限: 正常

Meta内核版本: alpha-g630a17c
Meta内核文件: 存在
Meta内核运行权限: 正常

#===================== 插件设置 =====================#

当前配置文件: /etc/openclash/config/config.yaml
启动配置文件: /etc/openclash/config.yaml
运行模式: fake-ip
默认代理模式: rule
UDP流量转发(tproxy): 停用
自定义DNS: 停用
IPV6代理: 停用
IPV6-DNS解析: 停用
禁用Dnsmasq缓存: 启用
自定义规则: 停用
仅允许内网: 启用
仅代理命中规则流量: 停用
仅允许常用端口流量: 停用
绕过中国大陆IP: 启用
路由本机代理: 启用

#启动异常时建议关闭此项后重试
混合节点: 停用
保留配置: 启用

#启动异常时建议关闭此项后重试
第三方规则: 停用

#===================== 配置文件 =====================#

### OpenClash Config

_No response_

### Expected Behavior

修复bug 订阅更新后能保持策略组正常工作

### Screenshots

![Snipaste_2023-09-11_21-12-09](https://github.com/vernesong/OpenClash/assets/43086765/e37dd503-f3f0-49f6-8263-df1b4ffcf045)
订阅文件中的混淆参数
### 
![image](https://github.com/vernesong/OpenClash/assets/43086765/64fe30e6-a67a-4923-bc8f-0be7261f8b8d)

一键配置 读取配置后节点信息中混淆参数
中间$L6Y丢失  导致生成的配置文件无法工作！

**Comment by himho** [comment]
![Snipaste_2023-09-11_21-12-09](https://github.com/vernesong/OpenClash/assets/43086765/e37dd503-f3f0-49f6-8263-df1b4ffcf045)
订阅文件中的混淆参数
### 
![image](https://github.com/vernesong/OpenClash/assets/43086765/64fe30e6-a67a-4923-bc8f-0be7261f8b8d)

一键配置 读取配置后节点信息中混淆参数
中间$L6Y丢失  导致生成的配置文件无法工作！ #
/

**Comment by jaychoww** [comment]
遇到同样问题,内核日志显示:
`2023-09-14 16:43:45 08:43:45 ERR [Config] configuration file test failed error=proxy group[0]: Proxy: 'Auto - UrlTest' not found path=/etc/openclash/xxx.yaml`
系统:
openwrt 23.05 rc3
openclash 0.45.141


处理器架构 | arm_cortex-a9_vfpv3-d16 | 上次检查更新时间 | 2023-09-14 16:46:44

[Dev] 当前内核版本 | v1.15.1-17-g6ecd96e | [Dev] 最新内核版本 | v1.15.1-17-g6ecd96e

[TUN] 当前内核版本 | 2023.04.16-20-g212da6a | [TUN] 最新内核版本 | 2023.04.16-20-g212da6a
