### ISSUE TITLE
[Feature] 根据目前设置的clash内核来使用不同的User Agent请求订阅链接

### ISSUE THREAD

**Issue by kogekiplay** [vernesong/OpenClash#3508]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

如题，部分机场普通订阅会根据UA请求下发不同的订阅，例如V2board，若UA为"clash"则下发clash订阅，若UA包含"meta"则下发除了ss以外的更多协议(etc:vless,tuic)，希望在设置默认内核为"meta"核心时，不是使用默认ua，"clash"而是使用包含"clashmeta"的ua请求订阅。
虽然机场主也会提供meta的订阅链接(订阅链接+&flag=meta)，但是希望可以根据meta的ua通过普通订阅也能获取到更多的节点。

### Describe the Solution

目前看到无论什么情况，ua都是"clash"，希望可以根据内核来区分不同的ua，谢谢作者有空可以采纳并跟进下我的issue，谢谢！

### Additional Context

![image](https://github.com/vernesong/OpenClash/assets/46434871/31ff0e84-8879-41c2-816c-bf2d35689913)

图片：V2board不同客户端适配的php文件，根据ua智能判断客户端

**Comment by vernesong** [comment]
这个只能做选项，直接替换不适合所有人
