### ISSUE TITLE
Fake-IP （TUN） 模式不能打开京东  Fake-IP （增强） 模式 进不去和平精英  Redir-Host模式电视奈飞看不了

### ISSUE THREAD

**Issue by sun5025** [vernesong/OpenClash#351]
我这问题有点多啊 切换各种模式 都不行 
Fake-IP （TUN） 模式不能打开京东购物车  还有微信表情 等
Fake-IP （增强） 模式 进不去和平精英  卡在进游戏时候 
Redir-Host 模式 电视的奈飞看不了
这几个问题切别的模式就没问题 但是就是没有一个模式 能解决这3个问题的

**Comment by vernesong** [comment]
建议redir游戏模式，dns加上fallback，关闭路由的ipv6
