### ISSUE TITLE
最新版本在官方master下出现读取UCI权限不足的问题！！！

### ISSUE THREAD

**Issue by zxlhhyccc** [vernesong/OpenClash#352]
![image](https://user-images.githubusercontent.com/45259624/79749747-524bc900-8342-11ea-8ef9-25a2b0309277.png)

**Comment by zxlhhyccc** [comment]
第二个问题：
海外全部显示的是国内IP，无论是何模式。。。。

**Comment by vernesong** [comment]
> 第二个问题：
> 海外全部显示的是国内IP，无论是何模式。。。。
> ![DFIM0@YA(AMASU%RI$VB H4](https://user-images.githubusercontent.com/45259624/79831558-37c52e80-83da-11ea-9cb2-cc3ef6942c8d.png)
> ![T1N{M{WMS 18ZF%P`A3N4@L](https://user-images.githubusercontent.com/45259624/79831615-50cddf80-83da-11ea-939f-156e55994a3b.png)

这个跟规则有关，你可以自己加一下

**Comment by zxlhhyccc** [comment]
> > 第二个问题：
> > 海外全部显示的是国内IP，无论是何模式。。。。
> > ![DFIM0@YA(AMASU%RI$VB H4](https://user-images.githubusercontent.com/45259624/79831558-37c52e80-83da-11ea-9cb2-cc3ef6942c8d.png)
> > ![T1N{M{WMS 18ZF%P`A3N4@L](https://user-images.githubusercontent.com/45259624/79831615-50cddf80-83da-11ea-939f-156e55994a3b.png)
> 
> 这个跟规则有关，你可以自己加一下

那请问在官方最新的luci下运行状态为何出现读取UCI权限不足，你的源码已经有acl了啊。。。。

**Comment by sillycat3** [comment]
> 
> 
> > 第二个问题：
> > 海外全部显示的是国内IP，无论是何模式。。。。
> > ![DFIM0@YA(AMASU%RI$VB H4](https://user-images.githubusercontent.com/45259624/79831558-37c52e80-83da-11ea-9cb2-cc3ef6942c8d.png)
> > ![T1N{M{WMS 18ZF%P`A3N4@L](https://user-images.githubusercontent.com/45259624/79831615-50cddf80-83da-11ea-939f-156e55994a3b.png)
> 
> 这个跟规则有关，你可以自己加一下

请问怎么操作？ 设置第三方规则也没法生效，现在规则外的海外全部都成了国内Ip链接 
谢谢啦
