### ISSUE TITLE
请支持下hy2，meta官方内核已经支持了

### ISSUE THREAD

**Issue by chenbo443756309** [vernesong/OpenClash#3520]
### Verify Steps

- [ ] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [x] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [ ] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [x] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

请支持下hy2，meta官方内核已经支持了

### Describe the Solution

请支持下hy2，meta官方内核已经支持了

### Additional Context

0

**Comment by Kanon1982** [comment]
请支持下hy2.0，谢谢大佬们

**Comment by chenbo443756309** [comment]
dev已经支持，可以关了

**Comment by Kanon1982** [comment]
> dev已经支持，可以关了

大佬，什么是dev？？？

**Comment by planktonzp** [comment]
> dev已经支持，可以关了

并未支持 在dev分支中未见到hysteria2类型 clash.Meta中将hysteria和hysteria2区分为两种结构体对应不同的代理配置并分别进行解析
代码位置如下：
https://github.com/MetaCubeX/Clash.Meta/blob/bf619d858615ebce70e58f931a12bde29ec8ea5e/adapter/parser.go#L95

**Comment by chenbo443756309** [comment]
你切dev更新就有了，我都已经用上了

**Comment by hpqqph** [comment]
> 你切dev更新就有了，我都已经用上了

单个hysteria2节点的yaml支持，同时添加多个节点的yaml就不支持了。不知道怎么回事。

**Comment by chenzhiguo** [comment]
是需要切换到meta内核吗？

**Comment by someway22** [comment]
> 你切dev更新就有了，我都已经用上了

我切换更新分支到 dev 总是不成功，咋整的这个界面。。选择 developer 后保存配置、然后更新？没用啊

**Comment by hpqqph** [comment]
> > 你切dev更新就有了，我都已经用上了
> 
> 我切换更新分支到 dev 总是不成功，咋整的这个界面。。选择 developer 后保存配置、然后更新？没用啊

用passwall啥的挂个代理，貌似用openclash本身的代理有时候更新不下来。

**Comment by dtknight** [comment]
proxy 0: unsupport proxy type: hysteria2 报错还是不支持呀

**Comment by hpqqph** [comment]
> proxy 0: unsupport proxy type: hysteria2 报错还是不支持呀

先用passwall挂个能用的代理，openclash插件设置-版本更新-已选择更新分支选择developer。然后点meta内核的检查并更新应该就可以。当然我是把整个客户端和所有内核都更新到developer的版本。目前客户端版本是v0.45.149-beta。meta内核版本是
alpha-g261b6e8。

**Comment by palemoky** [comment]
@hpqqph 我现在遇到了同样的问题，相同的配置文件在小火箭和电脑客户端都能正常运行，但在OpenClash中提示不支持h2类型，内核都已经是最新的了，我换成单个节点也是不行。你知道是什么原因吗？

**Comment by Sxxuxc** [comment]
openclash hysteria2节点是否不支持ipv6服务器地址？v0.45.155-beta 好像不能使用

**Comment by alexallen1** [comment]
建议检测到有hysteria节点，自动切换dev内核
因为不然坑很大。不上github搜都不知道存在这问题。按道理切换meta以为都ok了
