### ISSUE TITLE
[Bug] 启动的时候每次都会去自动下载一个文件 /tmp/geoip.metadb

### ISSUE THREAD

**Issue by LOVE2CMOL** [vernesong/OpenClash#3521]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [x] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [x] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.141-beta

### Bug on Environment

Lean

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

openwrt重启后 每次自动启动都会去自动下载一个文件 /tmp/geoip.metadb

或者在更新订阅的时候 都会触发下载/tmp/geoip.metadb

### Describe the Bug

会导致类似这位老哥提出的问题 -更新订阅连接后测试不通过 #3507 
也可能会导致clash启动过慢 或者 无法启动的问题

### OpenClash Log

插件日志：
2023-09-23 00:47:57 错误：【xxxxx】下载失败，请检查网络或稍后再试...
2023-09-23 00:47:57 错误：配置文件测试失败，请查看《内核日志》排查失败原因！
2023-09-23 00:47:57 配置文件【/etc/openclash/config/xxxxx.yaml】测试失败...
2023-09-23 00:47:26 配置文件下载成功，使用内核测试是否有错误...

内核日志：
2023-09-23 00:47:57 level=error msg="rules[2902] [GEOIP,CN,DIRECT,no-resolve] error: can't download MMDB: Get "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.metadb\": context deadline exceeded"
2023-09-23 00:47:57 level=error msg="can't initial GeoIP: can't download MMDB: Get "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.metadb\": context deadline exceeded"
2023-09-23 00:47:27 level=info msg="Can't find MMDB, start download"
2023-09-23 00:47:27 level=info msg="Geodata Loader mode: memconservative"
2023-09-23 00:47:27 level=info msg="Start initial configuration in progress"

### OpenClash Config

```shell
OpenClash 调试日志

生成时间: 2023-09-23 01:05:43
插件版本: v0.45.141-beta
隐私提示: 上传此日志前请注意检查、屏蔽公网IP、节点、密码等相关敏感信息



#===================== 系统信息 =====================#

主机型号: QEMU Standard PC (Q35 + ICH9 - Intel(R) Celeron(R) N5105 @ 2.00GHz : 4C4T
固件版本: OpenWrt SNAPSHOT r6106-d3e80e6e6
LuCI版本: git-23.194.57997-26d16e6-1
内核版本: 5.15.120
处理器架构: x86_64

#此项有值时,如不使用IPv6,建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: 

DNS劫持: Dnsmasq 转发
#DNS劫持为Dnsmasq时，此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 127.0.0.1#7874

#===================== 依赖检查 =====================#

dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
libcap: 已安装
libcap-bin: 已安装
ruby: 已安装
ruby-yaml: 已安装
ruby-psych: 已安装
ruby-pstore: 已安装
kmod-tun(TUN模式): 已安装
luci-compat(Luci >= 19.07): 已安装
kmod-inet-diag(PROCESS-NAME): 已安装
unzip: 已安装
iptables-mod-tproxy: 已安装
kmod-ipt-tproxy: 已安装
iptables-mod-extra: 已安装
kmod-ipt-extra: 已安装
kmod-ipt-nat: 已安装

#===================== 内核检查 =====================#

运行状态: 运行中
运行内核：Meta
进程pid: 18503
运行权限: 18503: cap_dac_override,cap_net_bind_service,cap_net_admin,cap_net_raw,cap_sys_ptrace,cap_sys_resource=eip
运行用户: nobody
已选择的架构: linux-amd64

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 2023.08.17
Tun内核文件: 存在
Tun内核运行权限: 正常

Dev内核版本: v1.17.0-20-ga19a9fe
Dev内核文件: 存在
Dev内核运行权限: 正常

Meta内核版本: alpha-g3a9fc39
Meta内核文件: 存在
Meta内核运行权限: 正常

#===================== 插件设置 =====================#

当前配置文件: /etc/openclash/config/config.yaml
启动配置文件: /etc/openclash/config.yaml
运行模式: redir-host-mix
默认代理模式: rule
UDP流量转发(tproxy): 停用
自定义DNS: 启用
IPV6代理: 启用
IPV6-DNS解析: 启用
禁用Dnsmasq缓存: 启用
自定义规则: 启用
仅允许内网: 停用
仅代理命中规则流量: 启用
仅允许常用端口流量: 停用
绕过中国大陆IP: 启用
路由本机代理: 启用

#启动异常时建议关闭此项后重试
混合节点: 停用
保留配置: 停用

#启动异常时建议关闭此项后重试
第三方规则: 启用
```

### Expected Behavior

我建议是把/tmp/geoip.metadb 下载好后自动挪到 /etc/openclash/geoip.metadb 进行持久化处理 下载成功就用新的metadb  失败则使用旧的metadb 

jsdelivr下载个5m的文件在很多网络下都有可能会中途断开

**Comment by blngxj** [comment]
你挑个反代网站添加在"Github 地址修改"栏能有效解决

**Comment by LOVE2CMOL** [comment]
> 你挑个反代网站添加在"Github 地址修改"栏能有效解决，没有的话只能在启动前开启前置代理了

主要是这文件也不小 而且每次重启系统更新配置都要去刷新一次 超时时间也太短 每次失败都是差一点下载完成就超时

**Comment by LOVE2CMOL** [comment]
> 你挑个反代网站添加在"Github 地址修改"栏能有效解决，没有的话只能在启动前开启前置代理了

经检测 geoip.metadb修改这玩意是没有效果的 还是会用旧地址 本身metadb就是用了jsdelivr 就算是jsdelivr这些 这个文件毕竟高达5m多 中途失败率还是挺高的
