### ISSUE TITLE
[Bug] 关闭openclash 重启路由器后 DNS不工作

### ISSUE THREAD

**Issue by AmazingGame** [vernesong/OpenClash#3522]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

不知道在哪看

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-arm64

### To Reproduce

启动openclash
关闭openclash
重启路由器

### Describe the Bug

关闭openclash后 重启路由器后dns不工作

发现openclash启动时,会设置dnsmasq忽略解析文件.dns工作正常

关闭openclash时,会取消忽略解析文件并且设置解析文件为/tmp/resolv.conf.auto 

然而我使用的固件是 IStoreOS 其中默认的解析文件是/tmp/resolv.conf.d/resolv.conf.auto 文件内容设置了拨号获取到的DNS

如果openclash 修改了这个设置为/tmp/resolv.conf.auto    在路由重启后,这个文件里面的内容是空,导致无法解析DNS
需要重新开启openclash 在关闭openclash才能正常解析

### OpenClash Log

无

### Expected Behavior

?

**Comment by Aincvy** [comment]
![image](https://github.com/vernesong/OpenClash/assets/8110347/39d7356b-9c20-4bd4-a116-eae8d07bff01)

在你重启路由器之后， 这个位置的选项有无变化？  

*这是dnsmasq 的设置部分，  如果你使用了别的dns解析服务， 那当我什么也没说*

客户端版本应该是在这里  

![image](https://github.com/vernesong/OpenClash/assets/8110347/ea3f78c3-8d78-4829-9904-6b938ab12f28)


*PS： 我只是一个路过的好心人*
