### ISSUE TITLE
[Bug] 局域网ip通过防火墙+黑白名单绕过openclash成功，但是无法联网！

### ISSUE THREAD

**Issue by iceye2072** [vernesong/OpenClash#3524]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.141-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

[这是个以前似乎解决的问题但是发现没用](https://github.com/vernesong/OpenClash/issues/2506)
就跟上面写的方法一样，通过改成用防火墙转发+fakeip+黑白名单

### Describe the Bug

可以成功绕开openclash, 在连接里已经没有这台设备了。但是，该设备也无法联网。

### OpenClash Log

已经没有该设备ip的信息了，不在openclash里显示，但是该设备无法上网。

### Expected Behavior

希望该设备绕开openclash后可以上网。

**Comment by iceye2072** [comment]
忘记说了，一关了openclash就正常，另外如果不在黑名单里添加也正常。

**Comment by eedaniel12** [comment]
我是用的adguard(重定向53)+openclash(fake-ip)，首先在防火墙里面自定义规则让指定设备不走adguard：
```
iptables -t nat -A PREROUTING -p udp --dport 53 -s 192.168.11.157/32 -j REDIRECT --to-ports 53
iptables -t nat -A PREROUTING -p tcp --dport 53 -s 192.168.11.157/32 -j REDIRECT --to-ports 53
```
这里192.168.11.157是我不走代理的设备，系统的53端口我是没有动的，用的系统默认DNS服务器。然后在openclash里面开发者选项里添加：
```
#跳过特定局域网IP：192.168.11.157
#Fake-IP（TUN）模式
iptables -t mangle -I openclash -s 192.168.11.157/32 -j RETURN
#Fake-IP（增强）模式
iptables -t nat -I openclash -s 192.168.11.157/32 -j RETURN
```
你看看这样对你有没有用
