### ISSUE TITLE
[Bug] 影响imassige的照片发送与接收！

### ISSUE THREAD

**Issue by 111413** [vernesong/OpenClash#3529]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.141-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-armv7

### To Reproduce

目前是tun模式（其他模式我无法正常使用）
尝试了加入部分关键字的只连
也尝试全局直连
都不管用

只有关闭openclash才正常

具体情况就是收、发imassige照片失败！
文字和facetime没有问题！

### Describe the Bug

1

### OpenClash Log

1

### OpenClash Config

```shell
1
```

### Expected Behavior

1

### Screenshots

1

**Comment by vernesong** [comment]
全局代理呢

**Comment by 111413** [comment]
> 全局代理呢

也不行，换shellclash了
