### ISSUE TITLE
[Feature] 添加metacubexd面板支持

### ISSUE THREAD

**Issue by ByteArray0** [vernesong/OpenClash#3534]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

metacubexd是clash meta官方团队制作的面板，对meta特性支持比第三方改版好。项目地址：https://github.com/MetaCubeX/metacubexd

### Describe the Solution

实现起来不难，只需要在/usr/share/openclash/ui下添加新面板的assets即可。

### Describe Alternatives

唯一问题可能是主页显示三个面板不太好排版？可以考虑在meta启用时使用metacubexd代替dashboard。

### Additional Context

![Snipaste_2023-09-28_21-00-12](https://github.com/vernesong/OpenClash/assets/134892304/e2c98f72-ac98-4fee-bd02-18ed64eea3ec)

**Comment by ObcbO** [comment]
很好用！强烈希望加入这个功能

在没加入之前可以先用这个命令一键安装
```
wget -cqO- https://gi
thub.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.tar
.gz | tar -xz -C /usr/share/openclash/ui | mv /usr/share/open
clash/ui/metacubexd-gh-pages /usr/share/openclash/ui/metacube
xd
```
然后metacubexd面板地址就是`http://192.168.8.1:9090/ui/metacubexd/`

**Comment by liangyi9812** [comment]
顶一下 metacubexd确实更强大

**Comment by Lovest20018** [comment]
支持-真的挺好用的，自带的2个是可以考虑换个了。

**Comment by sdttttt** [comment]
我还是习惯使用yacd.

**Comment by boyeye** [comment]
安装后手动替换即可。

**Comment by KarlLee830** [comment]
同，请求支持

**Comment by ObcbO** [comment]
> 同，请求支持

dev分支已加入
