### ISSUE TITLE
[Feature]  hysteria2 配置类型解析和支持

### ISSUE THREAD

**Issue by planktonzp** [vernesong/OpenClash#3536]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

申请更新openclash中配置类型解析逻辑增加hysteria2

### Describe the Solution

当前版本openclash中仅有hysteria v1配置文件类型 后端meta内核新增hysteria2类型对应v2版本的代理配置解析
https://github.com/MetaCubeX/Clash.Meta/blob/bf619d858615ebce70e58f931a12bde29ec8ea5e/adapter/parser.go#L95

**Comment by chenbo443756309** [comment]
dev支持了的，你更新分支切dev，或者直接在这个代码分支切到core，然后自己下包

**Comment by planktonzp** [comment]
后端内核meta.clash里面的config.type分为hysteria和hysteria2 openclash的server-config.lua解析配置代码里面搜hysteria2结果是0个 你告诉我 怎么用上的？？？？？ 靠爱吗
https://github.com/vernesong/OpenClash/blob/dev/luci-app-openclash/luasrc/model/cbi/openclash/servers-config.lua

**Comment by planktonzp** [comment]
> dev支持了的，你更新分支切dev，或者直接在这个代码分支切到core，然后自己下包

认认真真看看代码 求求了

后端内核meta.clash里面的config.type分为hysteria和hysteria2
https://github.com/MetaCubeX/Clash.Meta/blob/bf619d858615ebce70e58f931a12bde29ec8ea5e/adapter/parser.go#L95

openclash的server-config.lua解析配置
在里面搜hysteria2结果是0个 你告诉我 怎么用上的？？？？？ 靠爱吗
https://github.com/vernesong/OpenClash/blob/dev/luci-app-openclash/luasrc/model/cbi/openclash/servers-config.lua

**Comment by chenbo443756309** [comment]
> > dev支持了的，你更新分支切dev，或者直接在这个代码分支切到core，然后自己下包
> 
> 认认真真看看代码 求求了
> 
> 后端内核meta.clash里面的config.type分为hysteria和hysteria2 https://github.com/MetaCubeX/Clash.Meta/blob/bf619d858615ebce70e58f931a12bde29ec8ea5e/adapter/parser.go#L95
> 
> openclash的server-config.lua解析配置 在里面搜hysteria2结果是0个 你告诉我 怎么用上的？？？？？ 靠爱吗 https://github.com/vernesong/OpenClash/blob/dev/luci-app-openclash/luasrc/model/cbi/openclash/servers-config.lua

随你吧，装什么看代码？我好心给你说怎么弄，你在那激动啥也不知道，反正我用起了，你不会用就算了，别回了

**Comment by chenbo443756309** [comment]
> > > dev支持了的，你更新分支切dev，或者直接在这个代码分支切到core，然后自己下包
> > 
> > 
> > 认认真真看看代码 求求了
> > 后端内核meta.clash里面的config.type分为hysteria和hysteria2 https://github.com/MetaCubeX/Clash.Meta/blob/bf619d858615ebce70e58f931a12bde29ec8ea5e/adapter/parser.go#L95
> > openclash的server-config.lua解析配置 在里面搜hysteria2结果是0个 你告诉我 怎么用上的？？？？？ 靠爱吗 https://github.com/vernesong/OpenClash/blob/dev/luci-app-openclash/luasrc/model/cbi/openclash/servers-config.lua
> 
> 随你吧，装什么看代码？我好心给你说怎么弄，你在那激动啥也不知道，反正我用起了，你不会用就算了，别回了

https://github.com/vernesong/OpenClash/tree/core/dev  你自己去看看meta编译的核心版本吧，在这看什么主程序的代码？不知道支持hy的都是核心支持吗？和主程序有什么关系？还给我说搜不到相关代码

**Comment by planktonzp** [comment]
> > > > dev支持了的，你更新分支切dev，或者直接在这个代码分支切到core，然后自己下包
> > > 
> > > 
> > > 认认真真看看代码 求求了
> > > 后端内核meta.clash里面的config.type分为hysteria和hysteria2 https://github.com/MetaCubeX/Clash.Meta/blob/bf619d858615ebce70e58f931a12bde29ec8ea5e/adapter/parser.go#L95
> > > openclash的server-config.lua解析配置 在里面搜hysteria2结果是0个 你告诉我 怎么用上的？？？？？ 靠爱吗 https://github.com/vernesong/OpenClash/blob/dev/luci-app-openclash/luasrc/model/cbi/openclash/servers-config.lua
> > 
> > 
> > 随你吧，装什么看代码？我好心给你说怎么弄，你在那激动啥也不知道，反正我用起了，你不会用就算了，别回了
> 
> https://github.com/vernesong/OpenClash/tree/core/dev 你自己去看看meta编译的核心版本吧，在这看什么主程序的代码？不知道支持hy的都是核心支持吗？和主程序有什么关系？还给我说搜不到相关代码

只能说为你的文盲感到悲哀
你贴的link里面是编译后的core二进制文件 运行时需要从openclash读取配置文件，作为config参数提供给meta.Clash, Openclash现在不管是dev还是master版本都没法提供type：hysteria2的配置 就算你hysteria服务端是2.0以上版本也只能运行在v1的模式下

**Comment by chenbo443756309** [comment]
> > > > > dev支持了的，你更新分支切dev，或者直接在这个代码分支切到core，然后自己下包
> > > > 
> > > > 
> > > > 认认真真看看代码 求求了
> > > > 后端内核meta.clash里面的config.type分为hysteria和hysteria2 https://github.com/MetaCubeX/Clash.Meta/blob/bf619d858615ebce70e58f931a12bde29ec8ea5e/adapter/parser.go#L95
> > > > openclash的server-config.lua解析配置 在里面搜hysteria2结果是0个 你告诉我 怎么用上的？？？？？ 靠爱吗 https://github.com/vernesong/OpenClash/blob/dev/luci-app-openclash/luasrc/model/cbi/openclash/servers-config.lua
> > > 
> > > 
> > > 随你吧，装什么看代码？我好心给你说怎么弄，你在那激动啥也不知道，反正我用起了，你不会用就算了，别回了
> > 
> > 
> > https://github.com/vernesong/OpenClash/tree/core/dev 你自己去看看meta编译的核心版本吧，在这看什么主程序的代码？不知道支持hy的都是核心支持吗？和主程序有什么关系？还给我说搜不到相关代码
> 
> 只能说为你的文盲感到悲哀 你贴的link里面是编译后的core二进制文件 运行时需要从openclash读取配置文件，作为config参数提供给meta.Clash, Openclash现在不管是dev还是master版本都没法提供type：hysteria2的配置 就算你hysteria服务端是2.0以上版本也只能运行在v1的模式下

你是开发者？你试过没有就在那说什么没有参数给meta？你到底清楚流程吗？你看过启动时候的日志吗？检测到mate专用配置或者参数会启用mate核心去解析配置，配置直接就被mate解析了，自己也不试，嘴是真硬，我一个用着和你一个没用上，还不会用的人说那么多，真的吃饱了，你慢慢等吧，管我屁事

**Comment by planktonzp** [comment]
> > > > > > dev支持了的，你更新分支切dev，或者直接在这个代码分支切到core，然后自己下包
> > > > > 
> > > > > 
> > > > > 认认真真看看代码 求求了
> > > > > 后端内核meta.clash里面的config.type分为hysteria和hysteria2 https://github.com/MetaCubeX/Clash.Meta/blob/bf619d858615ebce70e58f931a12bde29ec8ea5e/adapter/parser.go#L95
> > > > > openclash的server-config.lua解析配置 在里面搜hysteria2结果是0个 你告诉我 怎么用上的？？？？？ 靠爱吗 https://github.com/vernesong/OpenClash/blob/dev/luci-app-openclash/luasrc/model/cbi/openclash/servers-config.lua
> > > > 
> > > > 
> > > > 随你吧，装什么看代码？我好心给你说怎么弄，你在那激动啥也不知道，反正我用起了，你不会用就算了，别回了
> > > 
> > > 
> > > https://github.com/vernesong/OpenClash/tree/core/dev 你自己去看看meta编译的核心版本吧，在这看什么主程序的代码？不知道支持hy的都是核心支持吗？和主程序有什么关系？还给我说搜不到相关代码
> > 
> > 
> > 只能说为你的文盲感到悲哀 你贴的link里面是编译后的core二进制文件 运行时需要从openclash读取配置文件，作为config参数提供给meta.Clash, Openclash现在不管是dev还是master版本都没法提供type：hysteria2的配置 就算你hysteria服务端是2.0以上版本也只能运行在v1的模式下
> 
> 你是开发者？你试过没有就在那说什么没有参数给meta？你到底清楚流程吗？你看过启动时候的日志吗？检测到meta专用配置或者参数会启用meta核心去解析配置，配置直接就被meta解析了，自己也不试，嘴是真硬，我一个用着和你一个没用上，还不会用的人说那么多，真的吃饱了，你慢慢等吧，管我屁事

巧了 哥们本地调试完才发的issue 另外哥们大发善心给你科普一下 你看到的那一行检测到meta专用配置只是这个文本翻译的一行字
https://github.com/vernesong/OpenClash/blob/master/luci-app-openclash/po/zh-cn/openclash.zh-cn.po#L1966

另外 为了避免你这种又蠢又自大又嘴硬的人继续浪费我时间 上面那个中英翻译是用在下边这个初始化脚本里面的提示， 至于会出现这一行提示的原因是因为内核类型是meta， 这并不代表你传入的参数直接被meta接收了， 而是openclash做了一次转换输出成yaml才作为配置文件提交给meta.Clash的
https://github.com/vernesong/OpenClash/blob/979338e771e58947945e1a94beb6cf38552a7d20/luci-app-openclash/root/etc/init.d/openclash#L555

还有 借用你一句内容 我提feature 关你p事

**Comment by chenbo443756309** [comment]
> > > > > > > dev支持了的，你更新分支切dev，或者直接在这个代码分支切到core，然后自己下包
> > > > > > 
> > > > > > 
> > > > > > 认认真真看看代码 求求了
> > > > > > 后端内核meta.clash里面的config.type分为hysteria和hysteria2 https://github.com/MetaCubeX/Clash.Meta/blob/bf619d858615ebce70e58f931a12bde29ec8ea5e/adapter/parser.go#L95
> > > > > > openclash的server-config.lua解析配置 在里面搜hysteria2结果是0个 你告诉我 怎么用上的？？？？？ 靠爱吗 https://github.com/vernesong/OpenClash/blob/dev/luci-app-openclash/luasrc/model/cbi/openclash/servers-config.lua
> > > > > 
> > > > > 
> > > > > 随你吧，装什么看代码？我好心给你说怎么弄，你在那激动啥也不知道，反正我用起了，你不会用就算了，别回了
> > > > 
> > > > 
> > > > https://github.com/vernesong/OpenClash/tree/core/dev 你自己去看看meta编译的核心版本吧，在这看什么主程序的代码？不知道支持hy的都是核心支持吗？和主程序有什么关系？还给我说搜不到相关代码
> > > 
> > > 
> > > 只能说为你的文盲感到悲哀 你贴的link里面是编译后的core二进制文件 运行时需要从openclash读取配置文件，作为config参数提供给meta.Clash, Openclash现在不管是dev还是master版本都没法提供type：hysteria2的配置 就算你hysteria服务端是2.0以上版本也只能运行在v1的模式下
> > 
> > 
> > 你是开发者？你试过没有就在那说什么没有参数给meta？你到底清楚流程吗？你看过启动时候的日志吗？检测到meta专用配置或者参数会启用meta核心去解析配置，配置直接就被meta解析了，自己也不试，嘴是真硬，我一个用着和你一个没用上，还不会用的人说那么多，真的吃饱了，你慢慢等吧，管我屁事
> 
> 巧了 哥们本地调试完才发的issue 另外哥们大发善心给你科普一下 你看到的那一行检测到meta专用配置只是这个文本翻译的一行字
> 
> https://github.com/vernesong/OpenClash/blob/master/luci-app-openclash/po/zh-cn/openclash.zh-cn.po#L1966
> 
> 另外 为了避免你这种又蠢又自大又嘴硬的人继续浪费我时间 上面那个中英翻译是用在下边这个初始化脚本里面的提示， 至于会出现这一行提示的原因是因为内核类型是meta， 这并不代表你传入的参数直接被meta接收了， 而是openclash做了一次转换输出成yaml才作为配置文件提交给meta.Clash的
> 
> https://github.com/vernesong/OpenClash/blob/979338e771e58947945e1a94beb6cf38552a7d20/luci-app-openclash/root/etc/init.d/openclash#L555
> 
> 还有 借用你一句内容 我提feature 关你p事

你不在我关闭了的issues说话，我也不会来管你的闲事

**Comment by chenbo443756309** [comment]
戾气比谁都大，我说我用上了，没问题，我关我的issues你要来说一嘴，自己开个issues，好心给你说怎么做，你不信就算了，需要在哪阴阳怪气说我靠爱用起的？我是靠自己研究用起的，没问任何人，你那么牛皮怎么不自己去开发一个？自己拉代码下来自己改了自己编译嘛，大神！

**Comment by planktonzp** [comment]
> 戾气比谁都大，我说我用上了，没问题，我关我的issues你要来说一嘴，自己开个issues，好心给你说怎么做，你不信就算了，需要在哪阴阳怪气说我靠爱用起的？我是靠自己研究用起的，没问任何人，你那么牛皮怎么不自己去开发一个？自己拉代码下来自己改了自己编译嘛，大神！

哇 那只能说后面哥们提pr侥幸更新了openclash的话  您千万要脸别更新

**Comment by vernesong** [comment]
![image](https://github.com/vernesong/OpenClash/assets/42875168/da37f7bf-35a6-45e4-b2e5-95955307fc88)
直接写里面

**Comment by planktonzp** [comment]
> ![image](https://user-images.githubusercontent.com/42875168/271982898-da37f7bf-35a6-45e4-b2e5-95955307fc88.png) 直接写里面

后续有调整成单独type的计划么 或者我提个pr吧 假期后没什么课了 写写lua锻炼身体

**Comment by klmmlk** [comment]
我硬是没有找到上面“其他附加配置在哪里”。。。翻烂了都。

**Comment by sfdzkj** [comment]
~.~大佬们讨论的好激烈。
看网上都说hysteria2速度快，我不知道我甲骨文有没有必要换成hysteria2。目前速度感觉还可以。 还是速度慢的才有必要用hysteria2
