### ISSUE TITLE
机顶盒无法播放视频

### ISSUE THREAD

**Issue by hcwang** [vernesong/OpenClash#354]
使用Fake IP增强模式，家中的机顶盒（DNet 上.265播放盒，可以观看HBO等全球3510余个频道）无法播放，其使用的UDP协议，而IP地址均在海外，怀疑是因为Fake IP导致无法建立连接。

该盒子可以在家中宽带情况下直连，无须代理。

有任何合适的方案吗？谢谢。

**Comment by vernesong** [comment]
udp流量代理打开或者使用tun和游戏模式

**Comment by hcwang** [comment]
UDP流量转发打开的情况下，UDP流量不会走代理吧？

**Comment by vernesong** [comment]
也按规则

**Comment by hcwang** [comment]
不过此种情况下，我无法确认IP地址范围以及端口，好象都是随机的。有没有一种规则，让UDP流量直接走Direct？谢谢。

**Comment by vernesong** [comment]
你盒子不需要代理就自定义用src规则
