### ISSUE TITLE
[Bug] meta overwrite "invalid find process mode" on fresh install/select disable

### ISSUE THREAD

**Issue by lux5am** [vernesong/OpenClash#3540]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.143-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-arm64

### To Reproduce

fresh install or select disable for meta overwrite > find process mode.

### Describe the Bug

In meta overwrite, after "disable" selected on "find process mode" clash core refused to start with msg "invalid find process mode". apparently it is also the default value after fresh install. so it failed on first start.

Upon inspection, it write `find-process-mode: false` to the yaml file. which is indeed invalid value.
disable should left the value untouched like the other settings.

### OpenClash Log

```
2023-09-30 08:50:17 level=error msg="invalid find process mode"
```

### Expected Behavior

find-process-mode value should left untouched

### Screenshots

![Screenshot_20230930-090218_Firefox Nightly](https://github.com/vernesong/OpenClash/assets/110870661/35a72b1a-b00a-43d0-acc5-786225c6fdef)

**Comment by vernesong** [comment]
it is your own config value, openclash do not set the default value to false

**Comment by lux5am** [comment]
my value was "off". but after openclash overwrite "disable" it's written as "false".
