### ISSUE TITLE
无法运行提示格式错误

### ISSUE THREAD

**Issue by HeyDx** [vernesong/OpenClash#355]
nohup: failed to run command ‘/etc/openclash/clash’: Exec format error
打开时提示错误如下 不知道如何解决 麻烦大佬帮忙看一下什么问题

**Comment by HeyDx** [comment]
nohup: failed to run command ‘/etc/openclash/clash’: Exec format error

**Comment by HeyDx** [comment]
打开时提示错误如下 不知道如何解决 麻烦大佬帮忙看一下什么问题

**Comment by zxlhhyccc** [comment]
> nohup: failed to run command ‘/etc/openclash/clash’: Exec format error
> 打开时提示错误如下 不知道如何解决 麻烦大佬帮忙看一下什么问题

clash所在的路径改了。。。。

**Comment by HeyDx** [comment]
> > nohup: failed to run command ‘/etc/openclash/clash’: Exec format error
> > 打开时提示错误如下 不知道如何解决 麻烦大佬帮忙看一下什么问题
> 
> clash所在的路径改了。。。。

啥意思啊老板

**Comment by osxdiy** [comment]
内核版本不对

**Comment by HeyDx** [comment]
> 内核版本不对

处理器架构: mipsel_24kc , 请根据处理器架构选择以便下载、更新对应内核，错误的版本将不能正常运行   我选的是liniux-mips64  是不是弄错了。。

**Comment by zxlhhyccc** [comment]
> > 内核版本不对
> 
> 处理器架构: mipsel_24kc , 请根据处理器架构选择以便下载、更新对应内核，错误的版本将不能正常运行 我选的是liniux-mips64 是不是弄错了。。

也可能是版本错了吧

**Comment by zxlhhyccc** [comment]
> > > nohup: failed to run command ‘/etc/openclash/clash’: Exec format error
> > > 打开时提示错误如下 不知道如何解决 麻烦大佬帮忙看一下什么问题
> > 
> > 
> > clash所在的路径改了。。。。
> 
> 啥意思啊老板

二进制执行文件的路径已经改为：/etc/openclash/core/clash

**Comment by HeyDx** [comment]
> > > > nohup: failed to run command ‘/etc/openclash/clash’: Exec format error
> > > > 打开时提示错误如下 不知道如何解决 麻烦大佬帮忙看一下什么问题
> > > 
> > > 
> > > clash所在的路径改了。。。。
> > 
> > 
> > 啥意思啊老板
> 
> 二进制执行文件的路径已经改为：/etc/openclash/core/clash

这个clash是文件还是文件夹啊  我也在/core下放过内核  也没用

**Comment by HeyDx** [comment]
> > > > nohup: failed to run command ‘/etc/openclash/clash’: Exec format error
> > > > 打开时提示错误如下 不知道如何解决 麻烦大佬帮忙看一下什么问题
> > > 
> > > 
> > > clash所在的路径改了。。。。
> > 
> > 
> > 啥意思啊老板
> 
> 二进制执行文件的路径已经改为：/etc/openclash/core/clash

我的路由器是Newifi D2

**Comment by vernesong** [comment]
试试mipsle-softfloat

**Comment by HeyDx** [comment]
好的  我尝试一下

vernesong <notifications@github.com> 于 2020年4月21日周二 下午10:19写道：

**Comment by HeyDx** [comment]
> 试试mipsle-softfloat

好了  感谢好兄弟
