### ISSUE TITLE
[Feature] 请求更新支持一下reality 协议。谢谢！

### ISSUE THREAD

**Issue by 404user** [vernesong/OpenClash#3552]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

请求更新支持一下reality 协议。谢谢！

### Describe the Solution

请求更新支持一下XRAY1.8版本以上的reality 协议

**Comment by zakizou** [comment]
meta.clash勾选了就支持reality

**Comment by 404user** [comment]
> meta.clash勾选了就支持reality

勾选了啊，但是添加了后通不过啊。

**Comment by xiandu999-yu** [comment]
> > meta.clash勾选了就支持reality
> 
> 勾选了啊，但是添加了后通不过啊。

看了一下，好像clash.meta好像支持不全...

**Comment by zakizou** [comment]
> > meta.clash勾选了就支持reality
> 
> 勾选了啊，但是添加了后通不过啊。

应该是你的节点信息没写对，我的正常使用
