### ISSUE TITLE
[Bug] tun模式下使用system网络栈导致网关下设备无法联网

### ISSUE THREAD

**Issue by rsgdn** [vernesong/OpenClash#3557]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v045.141-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

无

### Describe the Bug

fake-ip/redir-host的tun模式下使用system网络栈导致网关下设备无法联网，nslookup域名返回ip地址正常，但是浏览器打开网页提示无法获取ip地址，并且网关本身是可以正常联网的，另外gvisor网络栈是正常的

### OpenClash Log

无

### Expected Behavior

软件本身和内核本身好几个版本都是这个

**Comment by Dawdler-G** [comment]
相同问题

**Comment by dainslef** [comment]
相同問題。

似乎跟指定設備相關，我有三台設備GL.iNET MT1300、Redmi AX6S、Linksys E8450，相同的OpenWRT版本（23.05.0）+ 相同的OpenClash版本（v045.141-beta）+ 相同軟件包配置，GL.iNET MT1300/Redmi AX6S可以使用tun + system，但Linksys E8450使用tun + system會出現無法聯網，改成tun + gvisor正常。

**Comment by yzbleaf** [comment]
相同问题

**Comment by faidev** [comment]
我的wrt3200ACM也是这样

**Comment by YuKongA** [comment]
同问题，360T7, ImmortalWrt 23.05.0, OpenClash v045.141-beta
