### ISSUE TITLE
[Bug]  fake-ip模式下，rules providers reject没有生效

### ISSUE THREAD

**Issue by zakizou** [vernesong/OpenClash#3561]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

0.45.16 bata

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-arm64

### To Reproduce

![image](https://github.com/vernesong/OpenClash/assets/30678311/fb689aba-4dbd-4fa3-8317-6cff3eacfe52)

### Describe the Bug

fake-ip模式下， 日志看不到reject的信息，广告依旧存在。是因为直接解析了IP，这些域名的广告规则不生效了？但是其他规则还是有效的。

### OpenClash Log

日志没有reject 信息

### Expected Behavior

希望有大佬能解答疑惑

**Comment by vernesong** [comment]
全局代理不要绕过国内，然后看看有没有域名
