### ISSUE TITLE
[Bug] metacubexd面板的节点切换有问题

### ISSUE THREAD

**Issue by ximiTech** [vernesong/OpenClash#3563]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.149

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

进入metacubexd面板后手动切换节点，发现能改变选项，但是节点并没有切换

### Describe the Bug

进入metacubexd面板后手动切换节点，发现能改变选项，但是节点并没有切换

### OpenClash Log

无需

### Expected Behavior

进入metacubexd面板后手动切换节点，能生效

**Comment by LemonPAKA** [comment]
请在节点切换右上角的齿轮中打开自动断开连接

**Comment by ximiTech** [comment]
谢谢提示
