### ISSUE TITLE
[Feature] 增强tidal的流媒体增强

### ISSUE THREAD

**Issue by hjchjchjc4352** [vernesong/OpenClash#3564]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

tidal只有美国ip才能播放，手动选择了美国节点有些可以有些还是无法播放tidal

### Describe the Solution

希望增加tidal的流媒体解锁功能

**Comment by OUZYcn** [comment]
我这里国内 IP可以直连，甚至规则中还特意加入了 直连
