### ISSUE TITLE
[Bug] 配置订阅里的 User-Agent 好像不生效

### ISSUE THREAD

**Issue by VIKINGYFY** [vernesong/OpenClash#3567]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

0.45.149

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-arm64

### To Reproduce

原生订阅链接，UA不管选clash还是clash.meta，都无法订阅，提示
"yaml: unmarshal errors:\n line 1: cannot unmarshal !!str dHJvamF... into config.RawConfig"

而在原生订阅链接后添加&flag=clash后，不管UA选什么都能正确订阅

**Comment by vernesong** [comment]
```
curl -SsL --connect-timeout 30 -m 60 --speed-time 30 --speed-limit 1 --retry 2 -H 'User-Agent: Clash' URL -o /tmp/yaml_sub_tmp_config.yaml

你可以自己测试一下
