### ISSUE TITLE
[Feature] fake-ip模式同时使用绕过大陆和黑白名单

### ISSUE THREAD

**Issue by Smolder3955** [vernesong/OpenClash#3570]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

redir-host模式经常dns污染加载失败，fake-ip页面中的绕过大陆依赖DNSMASQ，黑白名单需要防火墙转发，两者不能兼得

### Describe the Solution

DNSMASQ转发在配置文件增加 option lan_acl_mode 并不生效，反过来防火墙转发增加绕过大陆的配置也同样不生效（只能绕过大陆域名，不能绕过IP？）

### Describe Alternatives

mosdns+shellclash，可以关闭覆写之后按被隐藏都选项开启绕过大陆，但mosdns配置复杂而且小毛病很多

**Comment by vernesong** [comment]
做不了

**Comment by Smolder3955** [comment]
> 做不了

是不是因为OpenClash和ShellClash的绕过大陆流程不同，必须依赖DNSMASQ？

**Comment by deuteros-gex** [comment]
这么说吧，clash的fake ip机制决定了，如果希望fake ip+黑白名单+绕过大陆三开，那一定需要除了dnsmasq外的另一个dns服务。
具体细节自己分析吧。

**Comment by Smolder3955** [comment]
> 这么说吧，clash的fake ip机制决定了，如果希望fake ip+黑白名单+绕过大陆三开，那一定需要除了dnsmasq外的另一个dns服务。 具体细节自己分析吧。

但是OpenClash停用DNS劫持就不能用绕过大陆了，有没有更好的解决方法？
