### ISSUE TITLE
[Bug] 自定义规则不生效

### ISSUE THREAD

**Issue by zsasad** [vernesong/OpenClash#3571]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.141-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-arm64

### To Reproduce

填写完自定义规则后应用配置

### Describe the Bug

填写完自定义规则后应用配置，发现本该直连的网站依然通过代理访问

### OpenClash Log

2023-10-22 22:32:23 INF [TCP] connected lAddr=192.168.5.246:7557 rAddr=canyouseeme.org:443 mode=rule rule=DstPort(443) proxy=Ku[🇭🇰 Hong Kong 01]
![image](https://github.com/vernesong/OpenClash/assets/9253791/a264c885-1430-418f-bef6-e84a53209912)

### Expected Behavior

希望可以把自定义规则修复

**Comment by marswow** [comment]
左侧的两个##号去掉后把DOMAIN-KEYWORD改成DOMAIN-SUFFIX试试？

**Comment by lxiaya** [comment]
好久都没更新版本了！还有自定义你前面#都是注释掉了，还能生效才怪！
