### ISSUE TITLE
[Bug] 如何启动premium内核？

### ISSUE THREAD

**Issue by iknowzxc** [vernesong/OpenClash#3583]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

NA

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-arm64

### To Reproduce

已经下载了premium内核重命名为clash_tun，放在/etc/openclash/core目录下，openclash中已经启用了tun模式，top后看到还是用的/etc/openclash/core/clash而非etc/openclash/core/clash_tun，怎么判断现在openclash调用的是premium内核呢？
[![pCKxfZ4.png](https://z1.ax1x.com/2023/06/15/pCKxfZ4.png)](https://imgse.com/i/pCKxfZ4)

### Describe the Bug

NA

### OpenClash Log

NA

### Expected Behavior

NA

**Comment by vernesong** [comment]
/etc/openclash/clash是个链接地址
