### ISSUE TITLE
[Bug] op启动后, 本来走直连的代理服务器, 瞬间变成走代理, 导致无法正确连接代理服务器

### ISSUE THREAD

**Issue by Nssiny** [vernesong/OpenClash#3584]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.141-beta

### Bug on Environment

Lean

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

运行模式: Redir-Host(TUN)
代理配置: proxies的server配置使用域名

之前用着好好的, 突然某一天开始无法连接代理服务器(确认服务器可以直连)

看着就像是, 代理服务器域名解析出来的ip是国外的, 不走直连了

于是我把其中一个代理服务器配成ip, 就都能正常代理

### Describe the Bug

如上

### OpenClash Log

-

### Expected Behavior

代理服务器能够正常使用域名

**Comment by vernesong** [comment]
配置default-nameserver

**Comment by Nssiny** [comment]
跟default-nameserver没关系, 是fallback的dns全挂了导致的, 随便加一个就解决了
