### ISSUE TITLE
[Bug] openclash_upnp规则链中的UPNP规则不会自动删除

### ISSUE THREAD

**Issue by skill7899** [vernesong/OpenClash#3587]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.149-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

开启miniupnpd

### Describe the Bug

过了一段时间，miniupnpd有些端口失效后查看防火墙，发现openclash_upnp规则链中比upnp_forward多得多，一些已经关闭了还是存在于openclash_upnp规则连中
``

### OpenClash Log

无

### Expected Behavior

应该和upnp_forward规则链一致

### Screenshots

<img width="2201" alt="image" src="https://github.com/vernesong/OpenClash/assets/13962272/9ec24972-11b6-4071-8e7f-b91f7ab9ce5b">

**Comment by vernesong** [comment]
你试试151，不行就提供一下
```
uci -q get upnpd.config.upnp_lease_file
```
显示的文件内容

**Comment by skill7899** [comment]
> 你试试151，不行就提供一下
> 
> ```
> uci -q get upnpd.config.upnp_lease_file
> ```
> 
> 显示的文件内容

我发现，这个151我重新安装，会导致我的网络接口全部重新下线，再上线。
<img width="2049" alt="image" src="https://github.com/vernesong/OpenClash/assets/13962272/50bb4160-9206-4ce9-96ef-11830f10d42c">
应该是utun删除了，再添加导致的？我这里utun我重启一下openclash，所以时间对不上。

**Comment by vernesong** [comment]
卸载会还原一下接口

**Comment by skill7899** [comment]
> 你试试151，不行就提供一下
> 
> ```
> uci -q get upnpd.config.upnp_lease_file
> ```
> 
> 显示的文件内容

TCP:36626:192.168.60.20:43615:1700306456:PTL-00113294A6DA004V
UDP:36626:192.168.60.20:36626:1700306456:PTL-00113294A6DA004V
TCP:46543:192.168.60.20:46543:1700306456:PTL-00113294A6DA004V
TCP:50401:192.168.60.201:50401:1700306501:8e846ef1
UDP:50401:192.168.60.201:50401:1700306501:8e846ef1
TCP:64835:192.168.60.201:64835:1700306503:8e846ef1
UDP:64835:192.168.60.201:64835:1700306503:8e846ef1
TCP:15123:192.168.60.201:15123:1700306506:8e846ef1
UDP:15123:192.168.60.201:15123:1700306506:8e846ef1
UDP:53454:192.168.60.123:53454:1700314489:GUDP@3395551702
TCP:44457:192.168.60.123:44457:1700314489:GWSS@3395551702
TCP:23930:192.168.60.123:23930:1700314489:GTCP@3395551702
UDP:23868:192.168.60.123:23868:1700314489:GNATUDP@3395551702
TCP:56860:192.168.60.123:39661:1700314693:PTL-OC553C0F6510C9WB
UDP:56860:192.168.60.123:56860:1700314693:PTL-OC553C0F6510C9WB
TCP:42949:192.168.60.123:42949:1700314693:PTL-OC553C0F6510C9WB
UDP:38091:192.168.60.123:38091:1700316405:GUDP@3595102017
TCP:23071:192.168.60.123:23071:1700316405:GWSS@3595102017
TCP:44023:192.168.60.123:44023:1700316405:GTCP@3595102017
UDP:29620:192.168.60.123:29620:1700316405:GNATUDP@3595102017
UDP:37774:192.168.60.123:37774:1700316406:GUDP@1055362758
TCP:29373:192.168.60.123:29373:1700316406:GWSS@1055362758
TCP:46800:192.168.60.123:46800:1700316406:GTCP@1055362758
UDP:25606:192.168.60.123:25606:1700316406:GNATUDP@1055362758
UDP:31683:192.168.60.123:31683:1700332600:31683-bilibili
UDP:32326:192.168.60.123:32326:1700359751:32326-bilibili
UDP:41789:192.168.60.193:41789:1699867439:wechat voip
UDP:39841:192.168.60.151:39841:1699869868:wechat voip
UDP:37949:192.168.60.193:37949:1699871688:wechat voip
TCP:6881:192.168.60.20:6881:1699859169:PCP MAP 2100c9f060df6141f500e3bf
UDP:6881:192.168.60.20:6881:1699859169:PCP MAP b83e14f9f04e53e4ad85a9c7
TCP:6883:192.168.60.123:6882:1699860703:NAT-PMP 6883 tcp
UDP:6883:192.168.60.123:6882:1699860703:NAT-PMP 6883 udp
UDP:35541:192.168.60.176:35541:1699879103:wechat voip
TCP:6882:192.168.60.123:6881:1699861415:NAT-PMP 6882 tcp
UDP:6882:192.168.60.123:6881:1699861416:NAT-PMP 6882 udp

上面是文upnp的文件内容，明显没有3936端口的
下面是防火墙的openclash_upnp一部份
<img width="1895" alt="image" src="https://github.com/vernesong/OpenClash/assets/13962272/0351d2c6-9937-4d6b-9a1e-daf3a873d923">

**Comment by skill7899** [comment]
我问题依然有
