### ISSUE TITLE
[Bug] 错误：配置文件测试失败，请查看《内核日志》排查失败原因！

### ISSUE THREAD

**Issue by minisind** [vernesong/OpenClash#3588]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.141-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-mips-softfloat

### To Reproduce

修改配置文件，增加自定义规则［修改原因：机场的订阅规则有问题，把GOOGLE子域和相关的几个域名分流到国内，引起GOOGLE翻译的网页翻译无法使用，还有GOOGLE PLAY的APP无法更新］。 修改完成后保存配置，应用配置，openclash自动启动后报错。

使用中发现的暂时解决办法： 把内核全部删除，所有配置文件全部删除。再重装内核，配置文件在外部先编辑好再重新上传，不在OPENCLASH中编辑。 -- 带来新问题，机场订阅无法更新，节点如果有更新，采用订阅链接更新后需要再次修改配置。OPENCLASH 可能再次停工。

### Describe the Bug

在OPENCLASH 中编辑配置引起BUG。 
基于MT7621的OPENWRT环境，搭配MOSDNS . 

### OpenClash Log

2023-11-02 18:43:17 10:43:17 ERR [Config] configuration file test failed error=initial rule provider Rule-provider - cfg1fac5a error: Get "https://statcounter.com/": lookup statcounter.com on 127.0.0.1:53: no such host path=/etc/openclash/ONE-YUAN.yaml

### OpenClash Config

```shell
主机名	OpenWrt
主机型号	HiWiFi HC5962 (CpuMark : 6692.740468 Scores)
架构	MediaTek MT7621 ver:1 eco:3 x 4
固件版本	OpenWrt R23.4.1 / LuCI Master (git-23.109.50273-11b9572)
内核版本	5.4.241
```

### Expected Behavior

修复BUG后，在自定义配置编辑保存和应用中应用重启，不再运行错误。 该错误揭示的文件实际并未删除，好好的存在路由器中的呢。

**Comment by jackiossy** [comment]
我也遇到了相同的问题。

**Comment by zhurant** [comment]
ERR [Config] configuration file test failed error=yaml: line 9: mapping values are not allowed in this context path=/tmp/yaml_sub_tmp_config.yaml

**Comment by Mocha-s** [comment]
![Snipaste_2023-11-22_10-12-47](https://github.com/vernesong/OpenClash/assets/20685520/75f4f2b8-ffd7-43a6-9952-753f3fbece10)
![Snipaste_2023-11-22_10-15-03](https://github.com/vernesong/OpenClash/assets/20685520/5b32b57a-5076-4a8f-8a95-a8d555381344)
昨天更新到最新版本后，也是同样问题。

**Comment by moyanstar** [comment]
我也遇到了相同的问题。

**Comment by minisind** [comment]
升级新版，更换内核已经正常运行。

**Comment by SalomonHsiun** [comment]
我的OpenClash前两周突然用不了了，检查下订阅链接发现到期时间什么的都是错的，但是更新订阅失败，包括在关闭OpenClash的情况下尝试也一样；并且OpenClash组件也检测不到更新，下游路由器也都无法访问谷歌等

**Comment by ssrv2** [comment]
遇到相同问题，只有2个机场能正常下载并通过内核测试
OpenClash Version
v0.45.152-beta

[Dev] 当前内核版本 | v1.18.0-13-gd034a40
[Meta] 当前内核版本alpha-g8c3557e 
当前客户端版本v0.45.152-245
未下载[TUN] 内核测试

**Comment by minisind** [comment]
手动更新一次订阅，生成本地配置文件，再手动把配置文件上传。  把OPENCLASH中的自动更新订阅取消掉。

**Comment by SalomonHsiun** [comment]
更新订阅失败，配置文件更新时间是几年前，

**Comment by ssrv2** [comment]
有人更新最新版客户端 v0.45.157-beta
这个版本了吗？解决这个订阅更新UA识别问题没？

**Comment by ssrv2** [comment]
> > 有人更新最新版客户端 v0.45.157-beta 这个版本了吗？解决这个订阅更新UA识别问题没？
> 
> 临时办法：订阅链接后面加&flag=clash就可以了

得机场支持吧，不是所有机场都支持这个指令来下载正确的配置

**Comment by peoplechinapower** [comment]
> > > 有人更新最新版客户端 v0.45.157-beta 这个版本了吗？解决这个订阅更新UA识别问题没？
> > 
> > 
> > 临时办法：订阅链接后面加&flag=clash就可以了
> 
> 非常感谢大佬的分享，我的加上可以正常更新订阅了，顺便一提，我更新了客户端 v0.45.157-beta，并不能解决更新订阅问题T.T

我也是这个版本 我加完就能更新订阅了，你说的是什么更新订阅问题

**Comment by peoplechinapower** [comment]
> > > 有人更新最新版客户端 v0.45.157-beta 这个版本了吗？解决这个订阅更新UA识别问题没？
> > 
> > 
> > 临时办法：订阅链接后面加&flag=clash就可以了
> 
> 非常感谢大佬的分享，我的加上可以正常更新订阅了，顺便一提，我更新了客户端 v0.45.157-beta，并不能解决更新订阅问题T.T

更新到157就又不能更新了？

**Comment by ssrv2** [comment]
> > > > 有人更新最新版客户端 v0.45.157-beta 这个版本了吗？解决这个订阅更新UA识别问题没？
> > > 
> > > 
> > > 临时办法：订阅链接后面加&flag=clash就可以了
> > 
> > 
> > 非常感谢大佬的分享，我的加上可以正常更新订阅了，顺便一提，我更新了客户端 v0.45.157-beta，并不能解决更新订阅问题T.T
> 
> 更新到157就又不能更新了？

不是，是更新到157还是得在订阅链接后面加&flag=clash，才能正常更新订阅

**Comment by zuixinxuting** [comment]
错误：配置文件测试失败，请查看《内核日志》排查失败原因！

**Comment by z2282023838** [comment]
还有什么解决办法没有？

**Comment by peoplechinapower** [comment]
> 还有什么解决办法没有？

&flag=clash
加这个不可以吗

**Comment by zuixinxuting** [comment]
没用

peoplechinapower ***@***.***> 于2024年12月30日周一 21:18写道：
