### ISSUE TITLE
[Feature] 建议支持v2ray内核

### ISSUE THREAD

**Issue by ghost** [vernesong/OpenClash#3590]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

clash所有上游均已停止维护。

### Describe the Solution

建议支持v2ray/sing-box内核

**Comment by Karmylr** [comment]
那样openclash目前的脚本都要重写了

**Comment by onecombo** [comment]
我也觉得添加协议工作量应该前所未有的大。

转网上哥们发了份统计。
1. Clash.Meta「已archived」
2. Clash Core「已删库」
3. Clash for Windows「已删库」
4. Tuic协议「已archived」
5. Helloworld路由器插件「已删库」
6. Gui.For.Clash「已删库」
7. ClashForAndroid 「已删库」
8. homeproxy 「已archived」
9. ClashMetaForAndroid 「已archived」
10. Fclash 「已archived」
11. Clash verge 「已archived」

meta还能打一阵，但独木难支或许只是时间问题，期待singbox早日推出适宜gui。
感谢项目组成员大佬们长久以来的维护，小弟拜谢。
穷鬼一个，谈不起赞助，一行文字，略表谢意。

**Comment by lux5am** [comment]
there's passwall/passwall2 that support xray and sing-box. but I can't get it to work with my router. something about loopback idk. without turning on the main switch the nodes seems to be ok. the ping appears. but when the main switch turned on, the ping timeout. and the issues on that project also closed at the same time with the closing of clash/meta 😭

**Comment by InspoOnU** [comment]
可以出一个纯防火墙模式，二进制文件自己制定。反正redirect和tproxy大部分软件都支持。

**Comment by lux5am** [comment]
> You can create a pure firewall mode and customize the binary file yourself. Anyway, most software supports redirect and tproxy.

give me an example for fw4 with sing-box
I played around with box for root for Android. I think it has potential. but I don't know how to implement forwarding for openwrt. does it even support tun. in android it does support tun.
