### ISSUE TITLE
[Bug] 更新到45.150后/usr/lib/lua/luci/http.lua被改坏导致无法进入管理界面

### ISSUE THREAD

**Issue by Howard20181** [vernesong/OpenClash#3592]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.150-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-mipsle-softfloat

### To Reproduce

用luci的软件包界面上传并更新

### Describe the Bug

这条commit引入的bug
c8ef45d2f0f0b5b2eb079715e0bf22c8642dde38

文件
luci-app-openclash/root/etc/uci-defaults/luci-openclash
```
sed -i '/.*HTTP_MAX_CONTENT*/c\HTTP_MAX_CONTENT = 1024*10240' /usr/lib/lua/luci/http.lua >/dev/null 2>&1
```

会匹配多次，随机插入很多行导致脚本格式错误
源文件 https://github.com/openwrt/luci/blob/openwrt-22.03/libs/luci-lib-base/luasrc/http.lua

### OpenClash Log

OpenClash 没跑起来，手动排查 luci 的问题
```
# /www/cgi-bin/luci
/usr/bin/lua: /usr/lib/lua/luci/ccache.lua:70: error loading module 'luci.http' from file '/usr/lib/lua/luci/http.lua':
        /usr/lib/lua/luci/http.lua:419: 'end' expected (to close 'function' at line 349) near 'HTTP_MAX_CONTENT'
stack traceback:
        [C]: in function 'loader'
        /usr/lib/lua/luci/ccache.lua:70: in function </usr/lib/lua/luci/ccache.lua:61>
        [C]: in function 'require'
        /usr/lib/lua/luci/sgi/cgi.lua:8: in main chunk
        [C]: in function 'require'
        /www/cgi-bin/luci:3: in main chunk
        [C]: ?
```

附上被改坏的 `luci.http` 
[http.lua.txt](https://github.com/vernesong/OpenClash/files/13255887/http.lua.txt)

### Expected Behavior

安装 luci 插件不应该去修改系统里其他软件包的脚本

**Comment by koomi** [comment]
me too

**Comment by qin9125** [comment]
怪不得今天早上，我试了 150 几次，一安装就歇菜 520 路由后台进不去了，我给作者说了也没理我，哈哈，我还以为是我的问题

**Comment by ArnoChenFx** [comment]
我的解决方法：
ssh进入后台， 运行/www/cgi-bin/luci，查看报错内容。在报错的地方对照以下代码
https://github.com/killbus/luci/blob/82abf9add923e5edd1d6abb07314f16f9167978f/modules/luci-base/luasrc/http.lua
，把改错的地方改回来就行了。

**Comment by koomi** [comment]
> 我的解决方法： ssh进入后台， 运行/www/cgi-bin/luci，查看报错内容。在报错的地方对照以下代码 https://github.com/killbus/luci/blob/82abf9add923e5edd1d6abb07314f16f9167978f/modules/luci-base/luasrc/http.lua ，把改错的地方改回来就行了。

搞定了，查找 HTTP_MAX_CONTENT = 1024*10240 内容，还原就好。

**Comment by zxlhhyccc** [comment]
怎么我的没问题呢

**Comment by xuelide** [comment]
昨天因为这事只能DD，2次都是升级150就进不去··最后放弃升级

**Comment by Yaochen2182** [comment]
> 就好

419行改過來了，還是不行，哪裡還有問題😫

**Comment by Yaochen2182** [comment]
具體怎麼修復，vim命令找不到這個文件

**Comment by Yaochen2182** [comment]
我丟這代碼怎麼變成這個樣子了，下面還有3個錯誤，離譜了

**Comment by Howard20181** [comment]
> 怎么我的没问题呢
> 

23.05 或者 OpenWrt master 不受影响

**Comment by ykhuazai** [comment]
最新的151还是会改这个文件

**Comment by XCJYO** [comment]
> 10240



> 我的解决方法： ssh进入后台， 运行/www/cgi-bin/luci，查看报错内容。在报错的地方对照以下代码 https://github.com/killbus/luci/blob/82abf9add923e5edd1d6abb07314f16f9167978f/modules/luci-base/luasrc/http.lua ，把改错的地方改回来就行了。

我直接将这个http.lua替换原来报错的http.lua,正常进入了...就这样吧

**Comment by lifetyper** [comment]
> 最新的151还是会改这个文件

我的也是，lean的lede没问题，用的master版本的openwrt挂了

**Comment by lifetyper** [comment]
> 151也有问题？回头我再看看

151没有问题，是151之后的那个[commit](https://github.com/vernesong/OpenClash/commit/ef7188c2d7d7a0136969d808ce48066adbf3cced)造成的，已经有人提了[PR](https://github.com/vernesong/OpenClash/pull/3598)来修了

**Comment by ykhuazai** [comment]
> > 最新的151还是会改这个文件
> 
> 
> 
> http.lua的14行被替换成了
> ```
> export let HTTP_MAX_CONTENT = 1024*10240;               // 100 kB maximum content size
> ```
> 改成
> ```
> HTTP_MAX_CONTENT = 1024*10240
> ```
> 

我直接替换整个文件就好了

**Comment by caliban511** [comment]
我也遇到过，干脆就不升了，，，又不是不能用.jpg ，，，😂😂😂
