### ISSUE TITLE
订阅多个地址

### ISSUE THREAD

**Issue by RealKiro** [vernesong/OpenClash#36]
![image](https://user-images.githubusercontent.com/33367701/65817150-67da9380-e236-11e9-93ea-04c67cd7ed17.png)

- 这里可以添加多个订阅地址吗？就像下面这个Lean的ssrplus+类似
![image](https://user-images.githubusercontent.com/33367701/65817166-8b054300-e236-11e9-94eb-1434b936ea03.png)

- 同时自动识别订阅协议那就更好了，这样就能订阅不同协议的飞机场
- 订阅地址的服务器在哪里可见？

**Comment by vernesong** [comment]
目的？多个配置文件切换吗
你在控制面板可以选择和切换服务器

**Comment by RealKiro** [comment]
> 目的？多个配置文件切换吗
> 你在控制面板可以选择和切换服务器

1. 目的：在不需要指定协议的情况下同时订阅多个地址（可以是多种协议）
![image](https://user-images.githubusercontent.com/33367701/65824067-83748700-e294-11e9-84fa-c6cd444a2305.png)


2. 有反馈说4个不通视频无法播放，经我使用确实有不通的问题（尤其是第三个），且部分网页会提示收不到数据或响应时间太长（如google.com）
![image](https://user-images.githubusercontent.com/33367701/65824054-40b2af00-e294-11e9-9230-aee68cca5590.png)

![image](https://user-images.githubusercontent.com/33367701/65824032-a05c8a80-e293-11e9-94c7-196e26b242ba.png)

**Comment by vernesong** [comment]
你的意思是合并多个订阅的节点吧，clash支持ss和vmess的部分协议
但现在clash的运行不只需要节点信息，还需要对应配置策略组和对应规则的分流，这样的话订阅需要配置的信息会很多很杂，不利于使用，也许你有更好的建议？

**Comment by vernesong** [comment]
连接不了的问题，受网络环境和配置的影响，一般是DNS问题，你也可以telegram联系我提供具体信息方便测试

**Comment by RealKiro** [comment]
> 连接不了的问题，受网络环境和配置的影响，一般是DNS问题，你也可以telegram联系我提供具体信息方便测试

https://t.me/ctcgfw_openwrt_discuss
