### ISSUE TITLE
运行状态和运行日志显示UCI权限不足

### ISSUE THREAD

**Issue by hx801217** [vernesong/OpenClash#360]

**Comment by hx801217** [comment]
![QQ截图20200422110223](https://user-images.githubusercontent.com/34504398/79936291-a0b7af80-8489-11ea-84db-e3427b46eae4.png)
![QQ截图20200422110242](https://user-images.githubusercontent.com/34504398/79936295-a44b3680-8489-11ea-95c9-352e36a8a1af.png)

**Comment by zxlhhyccc** [comment]
你是官方master最新的luci编译的吧？目前解决办法是，将luci-compat里的map.htm降级。。。。

**Comment by hx801217** [comment]
> 你是官方master最新的luci编译的吧？目前解决办法是，将luci-compat里的map.htm降级。。。。

我这不是啊，是koolshare2.34

**Comment by hx801217** [comment]
> > 你是官方master最新的luci编译的吧？目前解决办法是，将luci-compat里的map.htm降级。。。。
> 
> 我这不是啊，是koolshare2.34

怎么个降级法，大神

**Comment by hx801217** [comment]
> 你是官方master最新的luci编译的吧？目前解决办法是，将luci-compat里的map.htm降级。。。。

已经替换解决。。。cbi里面的map.htm替换成老的，现在正常了，谢谢大佬

**Comment by poemsiu** [comment]
> > 你是官方master最新的luci编译的吧？目前解决办法是，将luci-compat里的map.htm降级。。。。
> 
> 
> 
> 已经替换解决。。。cbi里面的map.htm替换成老的，现在正常了，谢谢大佬

话说 怎么替换啊

**Comment by lycor1s** [comment]
> > > 你是官方master最新的luci编译的吧？目前解决办法是，将luci-compat里的map.htm降级。。。。
> > 
> > 
> > 已经替换解决。。。cbi里面的map.htm替换成老的，现在正常了，谢谢大佬
> 
> 话说 怎么替换啊

把/usr/lib/lua/luci/view/cbi下面的map.htm替换为旧版本的
`https://github.com/openwrt/luci/blob/d5dff8f9a5ca85d197cbb6037f95053bc55941e5/modules/luci-compat/luasrc/view/cbi/map.htm`

**Comment by voler90** [comment]
> > > > 你是官方master最新的luci编译的吧？目前解决办法是，将luci-compat里的map.htm降级。。。。
> > > 
> > > 
> > > 已经替换解决。。。cbi里面的map.htm替换成老的，现在正常了，谢谢大佬
> > 
> > 
> > 话说 怎么替换啊
> 
> 把/usr/lib/lua/luci/view/cbi下面的map.htm替换为旧版本的 https://github.com/openwrt/luci/blob/d5dff8f9a5ca85d197cbb6037f95053bc55941e5/modules/luci-compat/luasrc/view/cbi/map.htm

感谢大佬找了半天方法，终于在这里找到正确答案
