### ISSUE TITLE
[Feature] 能给在线订阅转换增加一个生成订阅转换链接的功能么？

### ISSUE THREAD

**Issue by Fddh2012** [vernesong/OpenClash#3602]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

机场不让用公共后端，自己搭了个自用。用OpenClash的在线订阅转换功能，但是需要直接输出成订阅链接然后使用在配置文件中。

### Describe the Solution

给在线订阅转换增加一个生成订阅转换链接的功能。

**Comment by caliban511** [comment]
https://acl4ssr.netlify.app/

**Comment by Fddh2012** [comment]
> https://acl4ssr.netlify.app/

我知道怎么转换，我也有自己的后端&前端，我甚至已经在手搓配置文件了。只是不想那么麻烦。如果OpenClash能直接替代前端的工作，我就不需要再维护一个前端了。唉，主要是懒。

**Comment by akaet** [comment]
> > https://acl4ssr.netlify.app/
> 
> 我知道怎么转换，我也有自己的后端&前端，我甚至已经在手搓配置文件了。只是不想那么麻烦。如果OpenClash能直接替代前端的工作，我就不需要再维护一个前端了。唉，主要是懒。

添加配置的时候不是有在线订阅转换的开关吗？

**Comment by hongCchao** [comment]
使用订阅转换，自己github写一个转换规则模版不就行了，然后套品云的转换 用自己的规则模版

**Comment by Fddh2012** [comment]
> > > https://acl4ssr.netlify.app/
> > 
> > 
> > 我知道怎么转换，我也有自己的后端&前端，我甚至已经在手搓配置文件了。只是不想那么麻烦。如果OpenClash能直接替代前端的工作，我就不需要再维护一个前端了。唉，主要是懒。
> 
> 添加配置的时候不是有在线订阅转换的开关吗？

我只需要“在线订阅转换”有一个导出链接的功能。

**Comment by Fddh2012** [comment]
> 勾选订阅转换，使用自定义模版，自己github写一个转换规则模版文件，复制粘贴url不就行了，然后套品云的转换 用自己的规则模版

你说的这些都不是我的核心诉求，我只是需要“在线订阅转换”有一个导出链接的功能。

**Comment by lztxi** [comment]
> > https://acl4ssr.netlify.app/
> 
> 我知道怎么转换，我也有自己的后端&前端，我甚至已经在手搓配置文件了。只是不想那么麻烦。如果OpenClash能直接替代前端的工作，我就不需要再维护一个前端了。唉，主要是懒。

配置订阅里面，可以自定义后端地址，不知道是不是你要的功能
![image](https://github.com/vernesong/OpenClash/assets/72137239/1fe0a575-7f45-4a34-9b75-952a82906c95)

**Comment by riches2020cn** [comment]
> > > https://acl4ssr.netlify.app/
> > 
> > 
> > 我知道怎么转换，我也有自己的后端&前端，我甚至已经在手搓配置文件了。只是不想那么麻烦。如果OpenClash能直接替代前端的工作，我就不需要再维护一个前端了。唉，主要是懒。
> 
> 配置订阅里面，可以自定义后端地址，不知道是不是你要的功能 ![image](https://user-images.githubusercontent.com/72137239/283647618-1fe0a575-7f45-4a34-9b75-952a82906c95.png)

我也正为此苦恼，自己搭了前端后端用来生成配置文件，问题是机场节点一更新，又要重新手动去生成新的配置文件来代替旧的配置文件，能否像passwall2一样，只需点击更新订阅就一键搞定了？是否可以允许使用者创建自用模版，只需填入机场的订阅链接，就能自动套入自用模版中去？以后只需点击配置文件的更新按钮来更新机场的节点

**Comment by Fddh2012** [comment]
> 不是你要的功能

可以用proxy-providers来提取订阅节点列表；然后在proxy-groups引用；
https://a76yyyy.github.io/clash/zh_CN/configuration/outbound.html#proxy-providers-%E4%BB%A3%E7%90%86%E9%9B%86
然后还可以用rule-provider来在线订阅规则集，在订阅转换时使用expand=false就能生存这种类型的；
https://a76yyyy.github.io/clash/zh_CN/premium/rule-providers.html
配置文件只需要三个核心内容：
proxy-groups，proxy-providers，rules，rule-providers；然后其它都是在插件里设置往直接追加的。

**Comment by Fddh2012** [comment]
看我最新的回复。
________________________________
发件人: riches2020cn ***@***.***>
发送时间: 2023年11月19日 21:22
收件人: vernesong/OpenClash ***@***.***>
抄送: One percent ***@***.***>; Author ***@***.***>
主题: Re: [vernesong/OpenClash] [Feature] 能给在线订阅转换增加一个生成订阅转换链接的功能么？ (Issue #3602)


https://acl4ssr.netlify.app/

我知道怎么转换，我也有自己的后端&前端，我甚至已经在手搓配置文件了。只是不想那么麻烦。如果OpenClash能直接替代前端的工作，我就不需要再维护一个前端了。唉，主要是懒。

配置订阅里面，可以自定义后端地址，不知道是不是你要的功能 [image] <https://user-images.githubusercontent.com/72137239/283647618-1fe0a575-7f45-4a34-9b75-952a82906c95.png>

我也正为此苦恼，自己搭了前端后端用来生成配置文件，问题是机场节点一更新，又要重新手动去生成新的配置文件来代替旧的配置文件，能否像passwall2一样，只需点击更新订阅就一键搞定了？是否可以允许使用者创建自用模版，只需填入机场的订阅链接，就能自动套入自用模版中去？以后只需点击配置文件的更新按钮来更新机场的节点

―
