### ISSUE TITLE
[Bug] 订阅配置后，发现在配置管理的 diff 比对中，openclash 的修改版自动加了一堆规则

### ISSUE THREAD

**Issue by timmyz** [vernesong/OpenClash#3603]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.141-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

直接看图吧
![image](https://github.com/vernesong/OpenClash/assets/795528/84e929dc-5459-49ac-b93a-1d0ffaf9d2f4)

### Describe the Bug

订阅配置后，发现在配置管理的 diff 比对中，openclash 的修改版自动加了一堆规则

### OpenClash Log

暂略

### Expected Behavior

不希望自己加规则

**Comment by timmyz** [comment]
从别的 issue 里看到似乎是勾选了 bt 流量走直连才添加的，我再研究下

**Comment by timmyz** [comment]
看了一圈，在 插件设置-流量控制 中把 『仅允许常用端口的流量经过 Clash，防止 BT、P2P 下载流量经过代理』关掉似乎没用，还是 reopen 一下看看有没有大佬帮忙指导下

**Comment by waynesg** [comment]
"覆写设置--规则设置--仅代理命中规则流量"
这里关掉。
