### ISSUE TITLE
请问 nftables 下局域网特定 IP 如何绕过clash

### ISSUE THREAD

**Issue by xukecheng** [vernesong/OpenClash#3604]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

https://github.com/vernesong/OpenClash/issues/169
之前用 iptables -t nat -I openclash -s LAN_IP -j RETURN 是可以的，但是升级之后就没办法处理了

### Describe the Solution

请问 nftables 下局域网特定 IP 如何绕过clash

**Comment by Fddh2012** [comment]
源地址：插件设置-黑白名单-不走代理的局域网设备IP；
目的地址IPv4：插件设置-流量控制-本地IPv4绕过地址；
目的地址IPv6：插件设置-IPv6设置-本地IPv6绕过地址；

**Comment by LemonPAKA** [comment]
> > 源地址：插件设置-黑白名单-不走代理的局域网设备IP； 目的地址IPv4：插件设置-流量控制-本地IPv4绕过地址； 目的地址IPv6：插件设置-IPv6设置-本地IPv6绕过地址；
> 
> FakeIP TUN 模式下只有 不走代理的 WAN IP ![CleanShot 2023-11-16 at 21 07 31@2x](https://user-images.githubusercontent.com/29099863/283459211-46b1015d-b281-4f33-b8d5-635cf0ddd7b8.png)

貌似可以把DNS劫持模式改成防火墙模式的情况下，就能够在fake-ip模式下调整绕过IP

**Comment by xukecheng** [comment]
> > > 源地址：插件设置-黑白名单-不走代理的局域网设备IP； 目的地址IPv4：插件设置-流量控制-本地IPv4绕过地址； 目的地址IPv6：插件设置-IPv6设置-本地IPv6绕过地址；
> > 
> > 
> > FakeIP TUN 模式下只有 不走代理的 WAN IP ![CleanShot 2023-11-16 at 21 07 31@2x](https://user-images.githubusercontent.com/29099863/283459211-46b1015d-b281-4f33-b8d5-635cf0ddd7b8.png)
> 
> 貌似可以把DNS劫持模式改成防火墙模式的情况下，就能够在fake-ip模式下调整绕过IP

好像确实可以，感谢
