### ISSUE TITLE
N1-openclash报错

### ISSUE THREAD

**Issue by 1033154478** [vernesong/OpenClash#361]
上午折腾n1旁路由上的openclash可能是因为上传文件的内容搞错或者怎么样,运行日志大概是说做这个文件目录下的程序格式错误，原运行日志如下
nohup: failed to run command ‘/etc/openclash/clash’: Exec format error
2020-04-22 11:52:14 OpenClash Can Not Start, Please Check The Error Info And Try Again
我在google的时候也发现有人问了一样的问题，但是可能是问问题的板块不一样没有人回答，截图辅以佐证我的问题。希望能有大佬帮忙回答一下，或者也可以指导一下如何直接把openwrt里的openclash如何全部还原卸载重装试一下

![~P)3`422N)I4`UJF9~I266J](https://user-images.githubusercontent.com/62164808/79939383-8da8dd80-8491-11ea-8b45-1dbfddf492a1.png)

**Comment by zxlhhyccc** [comment]
> 上午折腾n1旁路由上的openclash可能是因为上传文件的内容搞错或者怎么样,运行日志大概是说做这个文件目录下的程序格式错误，原运行日志如下
> nohup: failed to run command ‘/etc/openclash/clash’: Exec format error
> 2020-04-22 11:52:14 OpenClash Can Not Start, Please Check The Error Info And Try Again
> 我在google的时候也发现有人问了一样的问题，但是可能是问问题的板块不一样没有人回答，截图辅以佐证我的问题。希望能有大佬帮忙回答一下，或者也可以指导一下如何直接把openwrt里的openclash如何全部还原卸载重装试一下
> 
> ![P)3422N)I4UJF9I266J](https://user-images.githubusercontent.com/62164808/79939383-8da8dd80-8491-11ea-8b45-1dbfddf492a1.png)

根据路由的cpu架构下载适配的clash。。。。

**Comment by 1033154478** [comment]
clash没有下载错，他现在就是连接不上内核

**Comment by NV3S** [comment]
`Exec format error`
这个应该是clash文件下载错了，和[上面](https://github.com/vernesong/OpenClash/issues/361#issuecomment-617571891)说的一样

**Comment by vernesong** [comment]
什么架构？

**Comment by vernesong** [comment]
版本更新标签里有还原设置，不需要重装

**Comment by 1033154478** [comment]
clash架构装错了，不好意思，我已经解决了
