### ISSUE TITLE
[Bug] 填写包含/排除节点后，更新订阅失败

### ISSUE THREAD

**Issue by VMatrices** [vernesong/OpenClash#3610]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.152-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-armv7

### To Reproduce

1. 新增订阅，输入订阅地址等参数
2. 选择一个订阅转换服务地址
3. 添加一个包含或排除的节点
4. 保存，点击更新订阅

### Describe the Bug

订阅信息填写包含/排除节点后，更新订阅必定失败

### OpenClash Log

2023-11-20 23:54:28 错误：【config】下载失败，请检查网络或稍后再试...
2023-11-20 23:54:16 错误：配置文件【config】订阅失败，尝试不使用代理下载配置文件...
2023-11-20 23:54:14 开始更新配置文件【config】...

### Expected Behavior

正确更新订阅

### Screenshots

对比在线订阅生成的地址，发现失败是正则的“?”号未转义导致：

![image](https://github.com/vernesong/OpenClash/assets/24680533/4bb12354-8744-4bea-b2d4-7340686c90b8)

**Comment by bitxeno** [comment]
这问题找了2周了，终于找到原因了👍
