### ISSUE TITLE
[Feature] 使用TProxy代理所有流量

### ISSUE THREAD

**Issue by ByteArray0** [vernesong/OpenClash#3614]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

目前OpenClash的兼容模式是Redirect IPv4 TCP + TProxy IPv4 UDP的混合，IPv6那边可选TUN和TProxy。

### Describe the Solution

使用TProxy代理IPv4/6、TCP/UDP所有流量。这样奇奇怪怪的问题会少一些，感觉Redirect经常会有莫名其妙的异常。

### Describe Alternatives
为什么不用TUN？在用，很稳定。但是TUN确实太吃性能了。R2s CPU占用100%，TUN只能跑100Mbps，而Redirect可以跑300Mbps以上。

**Comment by lux5am** [comment]
I tried with command line with tproxy it's indeed more stable I think. redirect sometimes slow/hang after long time. after restart it back to normal. so I only use tun most of the time. 
maybe make a separate tcp and udp option combo box.
tcp: redirect, tproxy, tun.
udp: tproxy, tun.

**Comment by ByteArray0** [comment]
> I tried with command line with tproxy it's indeed more stable I think. redirect sometimes slow/hang after long time. after restart it back to normal. so I only use tun most of the time. maybe make a separate tcp and udp option combo box. tcp: redirect, tproxy, tun. udp: tproxy, tun.

The decoupling idea is great, it makes OpenClash more flexible. Redirect is indeed unstable. There are sevaral times the apps or websites are loading endlessly, looks like it cannot connect to the domestic destinations. But the log shows that the domestic traffic is correctly routed to DIRECT outbound.

**Comment by lux5am** [comment]
> @lux5am The decoupling idea is great, it makes OpenClash more flexible. Redirect is indeed unstable. There are sevaral times the apps or websites are loading endlessly, looks like it cannot connect to the domestic destinations. But the log shows that the domestic traffic is correctly routed to DIRECT outbound.

that's exactly what I experienced. I looked at the connections log in yacd it's connected but no dl/ul. restarting openclash fixed it. there's no problem with tun but it just resource hungry. especially when uploading cpu hit 100% and  the internet on other devices get very slow.

**Comment by sdttttt** [comment]
我之前用的是fake-ip增强模式，然后我给改成TCP强制用TProxy了，就加了一个新的iptables链和修改了一下`插件设置 - 开发者选项`的脚本。

```
iptables -t mangle -N clash_tproxy

iptables -t mangle -A clash_tproxy -p udp -m udp --sport 500 -j RETURN
iptables -t mangle -A clash_tproxy -i lo -j RETURN
iptables -t mangle -A clash_tproxy -m set --match-set localnetwork dst -j RETURN

iptables -t mangle -A clash_tproxy -p udp -m udp --dport 53 -j RETURN

iptables -t mangle -A clash_tproxy -d 198.18.0.0/16 -p udp -j TPROXY --on-port 7895 --on-ip 0.0.0.0 --tproxy-mark 0x162
iptables -t mangle -A clash_tproxy -d 198.18.0.0/16 -p tcp -j TPROXY --on-port 7895 --on-ip 0.0.0.0 --tproxy-mark 0x162

iptables -t mangle -A clash_tproxy -p udp -j TPROXY --on-port 7895 --on-ip 0.0.0.0 --tproxy-mark 0x162
iptables -t mangle -A clash_tproxy -p tcp -j TPROXY --on-port 7895 --on-ip 0.0.0.0 --tproxy-mark 0x162


iptables -t mangle -N clash_tproxy_output

iptables -t mangle -A clash_tproxy_output -p udp -m udp --sport 500 -j RETURN
iptables -t mangle -A clash_tproxy_output -d 198.18.0.0/16 -p udp -m owner ! --uid-owner 65534 -j MARK --set-xmark 0x162
iptables -t mangle -A clash_tproxy_output -d 198.18.0.0/16 -p tcp -m owner ! --uid-owner 65534 -j MARK --set-xmark 0x162


iptables -t mangle -A PREROUTING -j clash_tproxy
iptables -t mangle -A OUTPUT -j clash_tproxy_output
```

开发者选项脚本：

```sh
#!/bin/sh
. /usr/share/openclash/log.sh
. /lib/functions.sh

# This script is called by /etc/init.d/openclash
# Add your custom firewall rules here, they will be added after the end of the OpenClash iptables rules

LOG_OUT "Tip: Start Add Custom Firewall Rules..."

// 删除tcp redirect的端口转发
iptables -t nat -D PREROUTING 10
iptables -t nat -D OUTPUT 1

// 删除TPROXY UDP
iptables -t mangle -D PREROUTING 2
iptables -t mangle -D OUTPUT 2

exit 0
```

不过现在我不用clash了，不知道新版本这个脚本还能不能用。

**Comment by ByteArray0** [comment]
@sdttttt 好东西，有条件的可以试试。不过新版OpenWRT使用nftables作为主防火墙。

**Comment by lux5am** [comment]
I can run clash full tproxy from command line with nftables example from xray page. but I can't integrate it with openclash without messed the firewall. previously I was looked out off the router  because the firewall was caught in a loop lol. I reluctant to try it again. adding a new temporary table in nftables seems to be no effect. maybe I will try it again later 😁

**Comment by lux5am** [comment]
here's my setup for nftables fw4. it run on top of tun mode.
just save it to something e.g. `/etc/openclash/openclash_tproxy.sh`
then run it `bash /etc/openclash/openclash_tproxy.sh start`. it should start catching all traffic to tproxy.
to stop it just run  `bash /etc/openclash/openclash_tproxy.sh stop`
it should be integrated to default table inet fw4, but just to be safe (I locked out before).
just edit it if you want to only forward tcp or ipv4. or if you want to put direct ipset.
run it first then observe. if something bad happens just reboot the router.
after everything okay you can put it to `/etc/unit.d/openclash` in start stop function.
for me I just manually execute it after starting openclash. just to be safe so it's not applied upon reboot.

I tested with speedtest and iperf3 numerous times. with pure tun cpu was about 70%+. with tproxy it was about 30%+.
I tried playing games which use udp and no problem so far. ipv6 also fine.

<details>
<summary>openclash_tproxy.sh</summary>

```bash
#!/bin/bash
TPROXY_PORT="7895"
PROXY_FWMARK="0x165"
PROXY_ROUTE_TABLE="0x165"

start() {
	ip rule add fwmark ${PROXY_FWMARK} table ${PROXY_ROUTE_TABLE}
	ip route add local 0.0.0.0/0 dev lo table ${PROXY_ROUTE_TABLE}
	ip -6 rule add fwmark ${PROXY_FWMARK} table ${PROXY_ROUTE_TABLE}
	ip -6 route add local ::/0 dev lo table ${PROXY_ROUTE_TABLE}

	nft -f - <<EOF
		table inet clash_tproxy
		delete table inet clash_tproxy
		table inet clash_tproxy {
		
			set localnetwork {
				type ipv4_addr
				flags interval
				auto-merge
				elements = { 0.0.0.0/8, 10.0.0.0/8,
					100.64.0.0/10, 127.0.0.0/8,
					169.254.0.0/16, 172.16.0.0/12,
					192.168.0.0/16, 224.0.0.0/3 }
			}
			set localnetwork6 {
				type ipv6_addr
				flags interval
				auto-merge
				elements = { ::/127,
					::ffff:0.0.0.0/96,
					::ffff:0:0:0/96,
					64:ff9b::/96,
					100::/64,
					2001::/32,
					2001:20::/28,
					2001:db8::/32,
					2002::/16,
					fc00::/7,
					fe80::/10,
					ff00::/8 }
			}
			chain direct {
				meta l4proto != { tcp, udp } accept
				ip daddr @localnetwork accept comment "localnetwork IP"
				ip6 daddr @localnetwork6 accept comment "localnetwork IP"
			}
			chain divert {
				type filter hook prerouting priority mangle; policy accept;
				meta l4proto { tcp, udp } socket transparent 1 meta mark set ${PROXY_FWMARK} counter accept comment "mark rerouted local"
			}
			chain prerouting  {
				type filter hook prerouting priority filter; policy accept;
				jump direct
				meta l4proto { tcp, udp } meta mark set ${PROXY_FWMARK} tproxy to :${TPROXY_PORT} counter accept comment "mark to tproxy"
			}
			chain output {
				type route hook output priority filter; policy accept;
				jump direct
				meta l4proto { tcp, udp } meta skuid != nobody meta mark set ${PROXY_FWMARK} counter accept comment "reroute local to prerouting"
			}
		}
EOF
}

stop() {
	nft delete table inet clash_tproxy >/dev/null 2>&1

	ip rule del fwmark ${PROXY_FWMARK} table ${PROXY_ROUTE_TABLE} >/dev/null 2>&1
	ip route del local 0.0.0.0/0 dev lo table ${PROXY_ROUTE_TABLE} >/dev/null 2>&1
	ip -6 rule del fwmark ${PROXY_FWMARK} table ${PROXY_ROUTE_TABLE} >/dev/null 2>&1
	ip -6 route del local ::/0 dev lo table ${PROXY_ROUTE_TABLE} >/dev/null 2>&1
}

case "${1}" in
	"start")
		start
		;;
	"stop")
		stop
		;;
	"restart")
		stop
		start
		;;
	*)
	echo "nothing to do."
		exit 0
		;;
esac

```

</details>

**Comment by kiligone** [comment]
用tproxy怎么代理路由器本机流量啊

**Comment by ByteArray0** [comment]
@kiligone 不知道，感觉可以参考一下ipv6的设置？

**Comment by lux5am** [comment]
> How to use tproxy to proxy router local traffic?

you can see in my script.
basically local traffic directly go to output chain while tproxy only effective in prerouting chain. so we reroute output from local traffic to prerouting by marking it then catch it with  ip route.
if only need to tproxy lan traffic, prerouting chain alone is enough.

**Comment by kiligone** [comment]
if [ "$enable_udp_proxy" -eq 1 ]; then
            modprobe nft_tproxy >/dev/null 2>&1
            ip rule add fwmark "$PROXY_FWMARK" table "$PROXY_ROUTE_TABLE"
            ip route add local 0.0.0.0/0 dev lo table "$PROXY_ROUTE_TABLE"
            nft 'add chain inet fw4 openclash_mangle'
            nft 'flush chain inet fw4 openclash_mangle'
            nft 'add chain inet fw4 openclash_upnp'
            nft 'flush chain inet fw4 openclash_upnp'
            upnp_exclude
            nft 'add rule inet fw4 openclash_mangle meta l4proto { udp } iifname lo counter return'
            nft add rule inet fw4 openclash_mangle ip daddr @localnetwork counter return
            nft 'add rule inet fw4 openclash_mangle udp dport 53 counter return'
            if [ "$en_mode" = "fake-ip" ]; then
               nft add rule inet fw4 openclash_mangle meta l4proto { udp } ip daddr { "$fakeip_range" } mark set "$PROXY_FWMARK" tproxy ip to 127.0.0.1:"$tproxy_port" counter accept
            fi
            nft 'add rule inet fw4 openclash_mangle ip saddr @localnetwork udp sport @lan_ac_black_ports counter return'
            nft 'add rule inet fw4 openclash_mangle ip daddr @wan_ac_black_ips counter return'
            nft 'add rule inet fw4 openclash_mangle ip saddr @lan_ac_black_ips counter return'
            nft 'add rule inet fw4 openclash_mangle ether saddr @lan_ac_black_macs counter return'
            if [ "$lan_ac_mode" = "1" ] && [ -n "$(uci -q get openclash.config.lan_ac_white_ips)" ] && [ -n "$(uci -q get openclash.config.lan_ac_white_macs)" ]; then
               nft 'add rule inet fw4 openclash_mangle ether saddr != @lan_ac_white_macs ip saddr != @lan_ac_white_ips counter return'
            else
               nft 'add rule inet fw4 openclash_mangle ether saddr != @lan_ac_white_macs counter return'
               nft 'add rule inet fw4 openclash_mangle ip saddr != @lan_ac_white_ips counter return'
            fi

            if [ "$en_mode" = "redir-host" ]; then
               nft 'add rule inet fw4 openclash_mangle udp dport != @common_ports counter return'
            fi
            if [ "$china_ip_route" = "1" ]; then
               if [ "$enable_redirect_dns" != "2" ]; then
                  nft 'add rule inet fw4 openclash_mangle ip daddr @china_ip_route ip daddr != @china_ip_route_pass counter return'
               else
                  nft 'add rule inet fw4 openclash_mangle ip daddr @china_ip_route counter return'
               fi
            fi

            nft 'add rule inet fw4 openclash_mangle ip protocol udp counter jump openclash_upnp'

            nft add rule inet fw4 openclash_mangle meta l4proto { udp } mark set "$PROXY_FWMARK" tproxy ip to 127.0.0.1:"$tproxy_port" counter accept
            nft 'add rule inet fw4 mangle_prerouting meta nfproto {ipv4} ip protocol udp counter jump openclash_mangle'
            if [ "$router_self_proxy" = "1" ]; then
               nft 'add chain inet fw4 openclash_mangle_output'
               nft 'flush chain inet fw4 openclash_mangle_output'
               nft add rule inet fw4 openclash_mangle_output meta l4proto { udp } meta skuid != 65534 meta mark set "$PROXY_FWMARK" counter accept comment "reroute local to prerouting"
               nft 'add rule inet fw4 mangle_output meta nfproto {ipv4} ip protocol udp counter jump openclash_mangle_output'
            fi

我改了一下启动文件，最后一个if里的内容是我加的，不知道为什么不行
