### ISSUE TITLE
[Bug] v0.45.152-beta无法更新订阅多了个utun口不知道跟它有没有关系，用v0.45.141-beta 版秒更新

### ISSUE THREAD

**Issue by jwkinko** [vernesong/OpenClash#3617]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.152-beta

### Bug on Environment

Lean

### Bug on Platform

Linux-arm64

### To Reproduce

更新配置

### Describe the Bug

v0.45.152-beta无法更新配置，用v0.45.141-beta 版秒更新

### OpenClash Log

2023-11-22 14:31:50 错误：【yy】下载失败，请检查网络或稍后再试...
2023-11-22 14:31:50 错误：配置文件【yy】订阅失败，尝试不使用代理下载配置文件...
2023-11-22 14:31:50 开始更新配置文件【yy】...
2023-11-22 14:31:43 错误：【yy】下载失败，请检查网络或稍后再试...
2023-11-22 14:31:43 错误：配置文件【yy】订阅失败，尝试不使用代理下载配置文件...
2023-11-22 14:31:42 开始更新配置文件【yy】...
2023-11-22 14:31:31 错误：【yy】下载失败，请检查网络或稍后再试...
2023-11-22 14:31:31 错误：配置文件【yy】订阅失败，尝试不使用代理下载配置文件...

### Expected Behavior

v0.45.152-beta多了个utun 接口 不知道干什么是否跟它有关

### Screenshots

<img width="569" alt="{53BDC5DA-8644-4a4b-93A7-2727602F003D}" src="https://github.com/vernesong/OpenClash/assets/95012013/bc6c03a3-9647-47bc-a632-25da2bc32ca7">

**Comment by dqh668** [comment]
最近几天出现了部分订阅无法更新。提示：错误：配置文件测试失败，请查看《内核日志》排查失败原因！

**Comment by etsam** [comment]
对，新编辑的多出一个UTUN接口 我还奇怪怎么多了这么个接口 看Makefile里面有 uci -q delete network.utun这句

**Comment by slyang40** [comment]
同样的问题, 无法更新订阅.

**Comment by Mocha-s** [comment]
服了，直接这两天没法用

**Comment by limitrinno** [comment]
根据Nginx返回的日志来看，这个版本的UA调用出现了问题
```
{0.0.0.0 - - [23/Nov/2023:06:34:25 +0000] "GET /api/v1/client/subscribe?token=*** HTTP/2.0" 200 1973 "-" "${sub_ua}"}
```

**Comment by dqh668** [comment]
目前不敢轻易从v0.45.141-beta升级到v0.45.157-beta，不知道v0.45.157-beta 是否存在和v0.45.152-beta一样无法更新订阅的情况？一旦更新后回退不容易了。
