### ISSUE TITLE
[Feature] 跪求大佬们，如何ping 特定域名返回真实ip(fake ip)

### ISSUE THREAD

**Issue by xiaolongzhou123** [vernesong/OpenClash#3626]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

ddns 绑定域名的时候。会通过nslookup  特定域名  去更新域名对应的ip
由于设置了fakeip ，返回198.18.0.0/24的ip,会导致更新错误

### Describe the Solution

不能在openwrt写死某个域名对应的ip，因为 是pppoe拨号，这个外网ip会变动

### Describe Alternatives

1

### Additional Context

1

**Comment by yuntian123456** [comment]
![image](https://github.com/vernesong/OpenClash/assets/19453085/ea0f54b7-739e-4536-a61a-df4847b427ff)
![image](https://github.com/vernesong/OpenClash/assets/19453085/b308ee0d-67e8-413f-856b-f177fe9d1238)

**Comment by yellowsavant** [comment]
楼上正解，把需要返回真实IP的域名加到fakeip filter即可

**Comment by gemnioo** [comment]
请教 “Fake-IP 模式下将返回真实IP地址" 是否需要对应 ” Fake-IP TUN&混合模式” ?

" Fake-IP 增强模式" 用的是 TProxy (Transparent Proxy)   是否添加到 Fake-IP Filter 并没有用？

TUN 模式才在OpenWRT 虚拟UTUN接口 ( v0.45.152-beta  为tun模式添加接口，改善NAT通信

**Comment by yellowsavant** [comment]
> 请教 “Fake-IP 模式下将返回真实IP地址" 是否需要对应 ” Fake-IP TUN&混合模式” ?
> 
> " Fake-IP 增强模式" 用的是 TProxy (Transparent Proxy) 是否添加到 Fake-IP Filter 并没有用？
> 
> TUN 模式才在OpenWRT 虚拟UTUN接口 ( v0.45.152-beta 为tun模式添加接口，改善NAT通信

fake-ip本来就是用来返回假的dns响应给客户端的，放在fake-ip filter列表的域名是告诉clash 返回真实dns 响应给客户端
tunnel模式（TUN）是在第三层网络层拦截所有出口流量，因为有的客户端软件不走代理，而是走路由，这就导致流量没有被代理，直接走直连出去。
utun虚拟网络接口则是用来实现tun模式的，真正意义上在clash core实现全局流量劫持的功能

**Comment by gemnioo** [comment]
@yellowsavant  两周前 覆写设置 DNS设置 勾选 Fake-IP-Filter 后 (Fake-IP 地址范围 (IPv4 Cidr)
 停用是停用 , 遇到了iOS macOS 系统间 使用SMB协议共享文档无法登录的问题  类似如下报错  以为是 bugiOS的锅, 结果取消勾选后就能正常连接了 

When connecting the SMB server, the following error message shows: “The operation van’t be completed because an unexpected error occurred   https://discussions.apple.com/thread/255360633?sortBy=best

原本配置文档里面就写了 雷同的 Fake-IP-Filter 所以还是不理解这里的勾选 意义是什么，openclash 的 fake-ip增强模式（Tproxy   的调用逻辑

**Comment by yellowsavant** [comment]
> @yellowsavant 两周前 覆写设置 DNS设置 勾选 Fake-IP-Filter 后 (Fake-IP 地址范围 (IPv4 Cidr) 停用是停用 , 遇到了iOS macOS 系统间 使用SMB协议共享文档无法登录的问题 类似如下报错 以为是 bugiOS的锅, 结果取消勾选后就能正常连接了
> 
> When connecting the SMB server, the following error message shows: “The operation van’t be completed because an unexpected error occurred https://discussions.apple.com/thread/255360633?sortBy=best
> 
> 原本配置文档里面就写了 雷同的 Fake-IP-Filter 所以还是不理解这里的勾选 意义是什么，openclash 的 fake-ip增强模式（Tproxy 的调用逻辑

SMB和fake-ip不搭界的呀，甚至用的端口号都不一样，fake-ip只是dns反馈方案而已，主要起到构建dns回应包的工作（假的dns IP reply）我估计和utun有关系，如果真有问题，就选增强模式吧
其实utun只是一个设备虚拟网卡，它会从layer 3 接管所有设备的流量，这几个版本的utun我感觉还没完全弄好，也常出问题
fake-ip-filter列表里的domain，表示需要真ip反馈，一般是国内的域名放在这里

**Comment by Rangtian** [comment]
> ![image](https://private-user-images.githubusercontent.com/19453085/285592846-ea0f54b7-739e-4536-a61a-df4847b427ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzNTQ5MTAsIm5iZiI6MTcwOTM1NDYxMCwicGF0aCI6Ii8xOTQ1MzA4NS8yODU1OTI4NDYtZWEwZjU0YjctNzM5ZS00NTM2LWE2MWEtZGY0ODQ3YjQyN2ZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAyVDA0NDMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzZDFiMjg0YTAzYzcxN2JkMmNkZTE5Y2M3OGM1MzUyOWE4ZmVhMWViNWMyOTQ2NzVmMTcxYjVkMjU2Y2RhMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BmD_UJaRnd4DCtlwKE8Wqh3tHh1-6CJ9cfOfwz5OiHM) ![image](https://private-user-images.githubusercontent.com/19453085/285592892-b308ee0d-67e8-413f-856b-f177fe9d1238.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzNTQ5MTAsIm5iZiI6MTcwOTM1NDYxMCwicGF0aCI6Ii8xOTQ1MzA4NS8yODU1OTI4OTItYjMwOGVlMGQtNjdlOC00MTNmLTg1NmItZjE3N2ZlOWQxMjM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAyVDA0NDMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwYzgzZTk2NGRmNDMwZWM4OTVkNmFlNmU1MTY2MDM4YTcxZDkwMzk3YjAzYjRjZmMxZWEwOTI1OWZjOGU4MmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9ElPYSVUF5E3A0fqoJMciLJo2oIX5KrHVDQ1wqJYH38)

您好，Fake-IP-Filter里已经自带坦克世界相关域名了，可我勾选后，依旧无法连接游戏服务器，请问还有其他什么地方需要设置么？谢谢您~

+.wotgame.cn
+.wggames.cn
+.wowsgame.cn
+.wargaming.net
+.wot.360.cn

**Comment by Rangtian** [comment]
> 楼上正解，把需要返回真实IP的域名加到fakeip filter即可


您好，Fake-IP-Filter里已经自带坦克世界相关域名了，可我勾选后，依旧无法连接游戏服务器，请问还有其他什么地方需要设置么？谢谢您~

+.wotgame.cn
+.wggames.cn
+.wowsgame.cn
+.wargaming.net
+.wot.360.cn

**Comment by yellowsavant** [comment]
> > 楼上正解，把需要返回真实IP的域名加到fakeip filter即可
> 
> 您好，Fake-IP-Filter里已经自带坦克世界相关域名了，可我勾选后，依旧无法连接游戏服务器，请问还有其他什么地方需要设置么？谢谢您~
> 
> +.wotgame.cn +.wggames.cn +.wowsgame.cn +.wargaming.net +.wot.360.cn

首先你先确认一下机场/自建代理服务器有无支持UDP转发，一般来说都有
其次clash必须使用TUN模式，很多游戏不支持走代理，所以需要在路由那边开启tun模式才能接管全局流量

**Comment by Rangtian** [comment]
> > > 楼上正解，把需要返回真实IP的域名加到fakeip filter即可
> > 
> > 
> > 您好，Fake-IP-Filter里已经自带坦克世界相关域名了，可我勾选后，依旧无法连接游戏服务器，请问还有其他什么地方需要设置么？谢谢您~
> > +.wotgame.cn +.wggames.cn +.wowsgame.cn +.wargaming.net +.wot.360.cn
> 
> 首先你先确认一下机场/自建代理服务器有无支持UDP转发，一般来说都有 其次clash必须使用TUN模式，很多游戏不支持走代理，所以需要在路由那边开启tun模式才能接管全局流量

切换为Fake-IP TUN模式后，游戏能正常登录了。谢谢您的帮助！

**Comment by yellowsavant** [comment]
> > > > 楼上正解，把需要返回真实IP的域名加到fakeip filter即可
> > > 
> > > 
> > > 您好，Fake-IP-Filter里已经自带坦克世界相关域名了，可我勾选后，依旧无法连接游戏服务器，请问还有其他什么地方需要设置么？谢谢您~
> > > +.wotgame.cn +.wggames.cn +.wowsgame.cn +.wargaming.net +.wot.360.cn
> > 
> > 
> > 首先你先确认一下机场/自建代理服务器有无支持UDP转发，一般来说都有 其次clash必须使用TUN模式，很多游戏不支持走代理，所以需要在路由那边开启tun模式才能接管全局流量
> 
> 切换为Fake-IP TUN模式后，游戏能正常登录了。谢谢您的帮助！

不客气，祝你玩得愉快！
