### ISSUE TITLE
[Bug] 订阅链接里包含“?”时会下载失败

### ISSUE THREAD

**Issue by SilenceEagle** [vernesong/OpenClash#3628]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.152-beta

### Bug on Environment

Lean

### Bug on Platform

Linux-arm64

### To Reproduce

`配置订阅`>>`添加`>>添加一条带有`?`的订阅，然后点击`更新配置`，查看`运行日志`里的`插件日志`，会提示:
>错误：【xxxxx】下载失败，请检查网络或稍后再试...
>开始更新配置文件【xxxxx】...

我同时测试了另外一个机场，它的订阅链接里没有"?"，就能成功下载。

然后网上搜了搜，我直接在`openwrt`的终端里`curl`了带`?`号带订阅地址：
```bash
FusionWrt# curl https://sub2.tanke66.cc/api/v1/client/subscribe?token=xxxxxxxxxxxxx
zsh: no matches found: https://sub2.tanke66.cc/api/v1/client/subscribe?token=xxxxxxxxxxxxx
```

然后搜索了一下，找到了这个帖子：
[You need to escape the question mark, otherwise zsh thinks it is a globbing or wildcard character and tries to find files that match it (that's why it says no matches found). Using double or single quotes is enough: curl "wttr.in/Changsha?lang=zh".](https://github.com/ohmyzsh/ohmyzsh/issues/7058#issuecomment-412364730)

我试着给订阅链接用‘’括起来了，但又报了curl(3) 的错误，应该是程序内部还给curl 命令加上了其他参数。

是否有办法可以支持带`?`的订阅链接。

### Describe the Bug

订阅链接中带有问号`?`时会无法下载配置文件。

### OpenClash Log

2023-11-26 14:05:11 配置文件【glados】更新成功！
2023-11-26 14:05:11 配置文件【glados】下载成功，本地没有配置文件，开始创建...
2023-11-26 14:05:11 配置文件测试成功，检查是否有更新...
2023-11-26 14:05:10 配置文件【/etc/openclash/config/glados.yaml】测试成功...
2023-11-26 14:05:09 配置文件下载成功，使用内核测试是否有错误...
2023-11-26 14:05:09 开始更新配置文件【glados】...
2023-11-26 14:05:09 错误：【dageyun】下载失败，请检查网络或稍后再试...
2023-11-26 14:05:09 错误：配置文件测试失败，请查看《内核日志》排查失败原因！
2023-11-26 14:05:08 配置文件下载成功，使用内核测试是否有错误...
2023-11-26 14:05:06 开始更新配置文件【dageyun】...

### Expected Behavior

即使订阅链接带有"?"，也可以正常下载配置文件。

**Comment by vernesong** [comment]
脚本是用bash

**Comment by SilenceEagle** [comment]
> 脚本是用bash

我试了一下，在TTY终端里切换到bash后运行curl命令确实可以正常返回带？的链接内容，但openclash里仍旧会下载失败

**Comment by SilenceEagle** [comment]
又测试了一下，应该不是？的原因，还是UA的原因，和这个issue一样 https://github.com/vernesong/OpenClash/issues/3621
