### ISSUE TITLE
[Feature] 支持 虚空终端 二进制的自动下载

### ISSUE THREAD

**Issue by foxii-cn** [vernesong/OpenClash#3630]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

看起来 Clash.Meta 还在更新，但改了名字并且不再公开源代码

### Describe the Solution

这是发布的二进制：https://github.com/MerlinKodo/akasha-terminal-bin/releases/tag/latest
这是仓库中仅有的信息（文档地址）：https://wiki.metacubex.one/
这里有更多的讨论信息：https://github.com/keiko233/clash-nyanpasu/issues/20

**Comment by foxii-cn** [comment]
不过这个二进制似乎不是作者本人直接发布的，或许可以再观望下

**Comment by voncamel** [comment]
我已经自己替换了mihomo的1.17版，改名为clash meta即可，正常运行，面板中能正常显示版本号。二进制见附件。
[clash_meta.zip](https://github.com/vernesong/OpenClash/files/13587115/clash_meta.zip)

**Comment by ObcbO** [comment]
新地址（不过其实就是原本meta仓库改名而来）
[MetaCubeX/mihomo](https://github.com/MetaCubeX/mihomo)
