### ISSUE TITLE
[BUG] nameserver-policy 表情符号 转译识别问题

### ISSUE THREAD

**Issue by lonecale** [vernesong/OpenClash#3632]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.152-beta

### Bug on Environment

Official OpenWrt, Lean

### Bug on Platform

Linux-amd64(x86-64), All

### To Reproduce

nameserver-policy 内容配置如下
'rule-set:🎯 全球直连': 223.5.5.5

### Describe the Bug

根据clash.meta 文档 [nameserver-policy](https://wiki.metacubex.one/config/dns/#nameserver-policy)
支持rule直接指定DNS，测试发现如果不带表情符号可以，带上标签符号就无法正常的转译提示找不到这个rule

**Comment by FTeAffs** [comment]
请去了解一下 `openclash` `clash/clash.meta` 两者的关系

> - [x] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题

**Comment by lonesomexz** [comment]
看了下 好像只支持
rule-providers 这样配置的规则集引用，一般都是使用直接转换到规则 没使用规则集好像不行
