### ISSUE TITLE
[Bug]0.45.152升级后，订阅链接无法更新 

### ISSUE THREAD

**Issue by BlueBenson** [vernesong/OpenClash#3633]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

0.45.152

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

更新0.45.152后，之前的订阅连接无法更新（两个不同机场都如此），发现订阅界面多了个User-Agent，不论选Clash还是Clash.meta，日志都报错，感觉无法转换RawConfig为YAML，回退到0.45.142后一切正常。

### Describe the Bug

更新0.45.152后之前的订阅无法更新，订阅界面多了个User-Agent，不论选Clash还是Clash.meta，日志都报错，感觉无法转换RawConfig为YAML，回退到0.45.142后一切正常。

### OpenClash Log

2023-11-29 23:54:19 15:54:19 ERR [Config] configuration file test failed error=yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `c3M6Ly9...` into config.RawConfig path=/tmp/yaml_sub_tmp_config.yaml
2023-11-29 23:54:07 15:54:07 ERR [Config] configuration file test failed error=yaml: unmarshal errors:

### Expected Behavior

希望解决问题

**Comment by sun5000** [comment]
相同问题 armv7

**Comment by FTeAffs** [comment]
152订阅确实有问题， 0ce45df072e1ecba64e1a9aaca5f63abf1a5b66d 修复了，还没合并到主分支，所以用155以后的才正常。
https://github.com/vernesong/OpenClash/raw/package/dev/luci-app-openclash_0.45.155-beta_all.ipk

最近变动比较大，呼吁V大尽快合一下吧。



hysteria的话，应该是订阅转换不支持吧，那就和V大没关系


> - [x] Tracker 我已经在 [Issue Tracker](https://github.com/vernesong/OpenClash/issues/%E2%80%A6%E2%80%A6/) 中找过我要提出的问题
> - [x] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在

**Comment by dqh668** [comment]
目前不敢轻易从v0.45.141-beta升级到v0.45.157-beta，不知道v0.45.157-beta 是否存在和v0.45.152-beta一样无法更新订阅的情况？一旦更新后回退不容易了。

**Comment by SilenceEagle** [comment]
实测157版本已可正常更新订阅

**Comment by Femoon** [comment]
157版本同样问题，本地文件正常使用，用 ghproxy 做了个 rule-providers 的 yaml 链接更新就报同样的错误
