### ISSUE TITLE
关于 v0.37.4-beta 对配置文件进行自动处理的问题

### ISSUE THREAD

**Issue by hly0928** [vernesong/OpenClash#364]
在升级到 v0.37.4-beta 后观察到以下现象：

1. 新版本似乎是以 `proxy-providers` 位置来判断 `OpenClash-General-Settings` 的，如果 `proxy-providers` 在配置文件中位于 `proxies` 或者 `proxy-groups` 之后会出现问题

2. 我的配置文件的 `proxies` 部分只有一行，是 `proxies: [json 数组]` 这种形式，新版本在将 `proxies` 改为 `Proxy` 的过程中会导致后面的 json 数组丢失

建议能全面兼容 Clash 新配置文件标准，另外感谢作者。

**Comment by Apocalypsor** [comment]
遇到了同样的问题，使用Srugio来产生的配置文件中的代理部分 ```proxies:``` 后跟的是json数组形式，导致代理全部丢失

**Comment by hly0928** [comment]
> 遇到了同样的问题，使用Srugio来产生的配置文件中的代理部分 `proxies:` 后跟的是json数组形式，导致代理全部丢失

握手，我也是 Surgio 用户，目前临时的解决方法只能修改模版文件：

1. 把 `proxy-providers` 放在 `proxies` 和 `proxy-groups` 之前
2. 把 `proxies` 改成 `Proxy`

**Comment by vernesong** [comment]
字段等待tun内核更新再跟进
你的配置文件模板可以发上来，我看看能不能先解决启动问题

**Comment by Apocalypsor** [comment]
proxies段是这样的：
```https://pastebin.com/raw/cYcuzjZn```

**Comment by hly0928** [comment]
另外我三部分的顺序是 `proxies`, `proxy-groups`, `proxy-providers`，这符合 Clash-core 给出的示例文件的顺序，而且在之前的版本中也能正确识别

**Comment by hly0928** [comment]
经测试 v0.37.5-beta 已经解决本问题，再次感谢作者。
