### ISSUE TITLE
[Bug] 157版本在运行状态页面打开yacd面板需要重新登录

### ISSUE THREAD

**Issue by Mipa233** [vernesong/OpenClash#3646]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.157-beta

### Bug on Environment

Lean

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

在运行状态页点击yacd控制面板。

### Describe the Bug

在运行状态页点击yacd控制面板需要重新登录才能显示。

只需要把网址中的 /# 删掉就能正常显示无需重新登录。

### OpenClash Log

无

### Expected Behavior

无需登录即可打开。

**Comment by openips** [comment]
同样的问题

**Comment by frui85** [comment]
可能问题不是很严重，打开yacd面包，把浏览器 url "/#" 干掉就可以打开，估计是路由跳转字符串没处理好

**Comment by fengtion11** [comment]
这个解决了？我用最新版v0.46.003-beta也是这样
