### ISSUE TITLE
[Bug] 关于UTUN接口问题！

### ISSUE THREAD

**Issue by zxlhhyccc** [vernesong/OpenClash#3649]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45-157-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-arm64

### To Reproduce

luci版本更新时，因UTUN接口在版本更新过程中不会自动删除，然后更新版本后又重新新建一次UTUN接口，会导致网络全断，此时必须重启路由网络才能正常。

### Describe the Bug

luci版本更新时，因UTUN接口在版本更新过程中不会自动删除，然后更新版本后又重新新建一次UTUN接口，会导致网络全断，此时必须重启路由网络才能正常。

### OpenClash Log

无

### Expected Behavior

建议在版本更新时先自动删除UTUN接口，待版本更新时再自动重新新建UTUN接口。

**Comment by etsam** [comment]
UTUN接口到底是什么，以前的版本为什么没有，新编译的固件也有这个，这是个新增的功能吗

**Comment by chinesepy** [comment]
同样出现了全局断网的问题！ redir-host  混合 模式。半夜自动更新订阅订阅后有概率会断网，重启openclash后恢复。但手动更新规则或者手动重启openclash不会断网。暂时切换为fake-ip 模式观察后续情况。

**Comment by wlnxing** [comment]
现在任然有这个问题, 点击重新连接utun会恢复网络, 客户端版本 `v0.46.001-beta` 内核meta: alpha-g0c384b1

**Comment by AllForLandlord** [comment]
> 现在任然有这个问题, 点击重新连接utun会恢复网络, 客户端版本 `v0.46.001-beta` 内核`meta: alpha-g0c384b1`

我这里虽然也有UTUN，但是不影响上网
