### ISSUE TITLE
[Bug] 只要更新clashmeta内核就无法联网

### ISSUE THREAD

**Issue by Leefurmore** [vernesong/OpenClash#3651]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.157

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

在插件设置-版本更新里选择更新meta内核，正常更新完成，自动重新启动openclash后，所有节点无法联网。用旧版本clashmeta内核替换后重启openclash又会恢复正常。

### Describe the Bug

只要更新meta内核就出现这个问题，更新dev内核和tun内核无此问题。内核日志的前方都有两个红色小圆点，正常情况下是没有的。

### OpenClash Log

[36mINFO[0m[2023-12-04T09:21:59.908212279Z] [TUN] Tun adapter listening at: utun([198.18.0.1/30],[]), mtu: 9000, auto route: false, ip stack: System 
[36mINFO[0m[2023-12-04T09:21:59.907082879Z] Mixed(http+socks) proxy listening at: [::]:7893 
[36mINFO[0m[2023-12-04T09:21:59.907055866Z] TProxy server listening at: [::]:7895        
[36mINFO[0m[2023-12-04T09:21:59.907004133Z] Redirect proxy listening at: [::]:7892       
[36mINFO[0m[2023-12-04T09:21:59.90697105Z] SOCKS proxy listening at: [::]:7891          
[36mINFO[0m[2023-12-04T09:21:59.906936422Z] HTTP proxy listening at: [::]:7890           
[36mINFO[0m[2023-12-04T09:21:59.906896188Z] DNS server listening at: [::]:7874           
[36mINFO[0m[2023-12-04T09:21:59.906807275Z] Use tcp concurrent                           
[36mINFO[0m[2023-12-04T09:21:59.906801286Z] Sniffer is loaded and working                
[36mINFO[0m[2023-12-04T09:21:59.906776129Z] Authentication of local server updated       
[36mINFO[0m[2023-12-04T09:21:59.894711579Z] RESTful API listening at: [::]:19090         
[36mINFO[0m[2023-12-04T09:21:59.894104281Z] Initial configuration complete, total time: 878ms 
[33mWARN[0m[2023-12-04T09:21:59.894074137Z] Deprecated: Use Sniff instead                
[36mINFO[0m[2023-12-04T09:21:59.894027822Z] Start initial GeoSite dns fallback filter `gfw`, records: 6069 
[33mWARN[0m[2023-12-04T09:21:59.820014809Z] replace fallback-filter.geosite with nameserver-policy, it will be removed in the future 
[36mINFO[0m[2023-12-04T09:21:59.819672672Z] Start initial GeoIP rule CN => DIRECT, records: 10519 
[36mINFO[0m[2023-12-04T09:21:59.456963039Z] Start initial GeoSite rule CN => DIRECT, records: 64614 
[36mINFO[0m[2023-12-04T09:21:59.01736055Z] Geodata Loader mode: standard                
[36mINFO[0m[2023-12-04T09:21:59.015376773Z] Start initial configuration in progress      
[36mINFO[0m[2023-12-04T09:21:57.290341145Z] Initial configuration complete, total time: 1846ms 
[33mWARN[0m[2023-12-04T09:21:57.290318856Z] Deprecated: Use Sniff instead                
[36mINFO[0m[2023-12-04T09:21:57.290293466Z] Start initial GeoSite dns fallback filter `gfw`, records: 6069 
[33mWARN[0m[2023-12-04T09:21:57.220688603Z] replace fallback-filter.geosite with nameserver-policy, it will be removed in the future 
[33mWARN[0m[2023-12-04T09:21:57.220426118Z] [CacheFile] can't open cache file: timeout   
[36mINFO[0m[2023-12-04T09:21:56.262234416Z] Start initial GeoIP rule CN => DIRECT, records: 10519 
[36mINFO[0m[2023-12-04T09:21:55.882633681Z] Start initial GeoSite rule CN => DIRECT, records: 64614 
[36mINFO[0m[2023-12-04T09:21:55.445799383Z] Geodata Loader mode: standard                
[36mINFO[0m[2023-12-04T09:21:55.443538302Z] Start initial configuration in progress     

### Expected Behavior

希望能修复

### Screenshots

<img width="1439" alt="iShot_2023-12-04_17 43 14" src="https://github.com/vernesong/OpenClash/assets/112952363/4e1b618c-ab3b-438b-8fc0-ae382720a7f5">

**Comment by trantuan-20048607** [comment]
> 内核日志的前方都有两个红色小圆点，正常情况下是没有的。

单独提了一个 issue：#3652

> 正常更新完成，自动重新启动openclash后，所有节点无法联网

看上去开了 TUN，Meta 和 TUN 一起用很玄学（
重启下 OpenClash 或者 OpenWrt 试试

**Comment by Leefurmore** [comment]
> > 内核日志的前方都有两个红色小圆点，正常情况下是没有的。
> 
> 单独提了一个 issue：#3652
> 
> > 正常更新完成，自动重新启动openclash后，所有节点无法联网
> 
> 看上去开了 TUN，Meta 和 TUN 一起用很玄学（ 重启下 OpenClash 或者 OpenWrt 试试

我用的是fakeip混合模式，用了一年多，从来没出过问题，一直都是Meta内核，都是第一时间更新的最新版本。自从10月份的版本开始就这样，一更新就用不了。重启也无用，只能回滚到9月份的meta版本内核才正常，不知道如何解决。

**Comment by trantuan-20048607** [comment]
> > > 内核日志的前方都有两个红色小圆点，正常情况下是没有的。
> > 
> > 
> > 单独提了一个 issue：#3652
> > > 正常更新完成，自动重新启动openclash后，所有节点无法联网
> > 
> > 
> > 看上去开了 TUN，Meta 和 TUN 一起用很玄学（ 重启下 OpenClash 或者 OpenWrt 试试
> 
> 我用的是fakeip混合模式，用了一年多，从来没出过问题，一直都是Meta内核，都是第一时间更新的最新版本。自从10月份的版本开始就这样，一更新就用不了。重启也无用，只能回滚到9月份的meta版本内核才正常，不知道如何解决。

看起来是 Meta 内核+1s之后集中出现的问题

你的日志里看不出什么有价值的信息：可以测试一下 DNS、开 Debug 模式截取日志、从几个 Clash 面板（Dashboard、Yacd、MetaCubeXd）里构造一些错误出来截图

鉴于你开了 TUN（混合模式包含该模式），可以检查一下虚拟网卡是否存在、试一下把 System 网络堆栈改成 Gvisor 等常见玄学操作，也试试直接关掉 TUN（选择兼容模式）再尝试上述日志截取操作

**Comment by Leefurmore** [comment]
用旧的内核虚拟网卡运行正常，切换成新内核就有错误了。
<img width="730" alt="iShot_2023-12-05_14 34 34" src="https://github.com/vernesong/OpenClash/assets/112952363/e8244352-fe64-40e8-a395-e39b9ee1dba8">
<img width="942" alt="iShot_2023-12-05_14 45 17" src="https://github.com/vernesong/OpenClash/assets/112952363/b44d9f2c-8e5f-46a3-90ce-831fc2b0cfe8">

试着不用tun模式，更改网络堆栈等操作，发现都一样无效，以下是截取了一部分的debug模式下的日志，有大量400bad request。
<img width="1202" alt="iShot_2023-12-05_14 51 12" src="https://github.com/vernesong/OpenClash/assets/112952363/e5399d6e-3b7f-4293-9e89-15810a713623">

**Comment by trantuan-20048607** [comment]
这仍然是 Meta 内核的问题，等作者修复吧（

**Comment by Leefurmore** [comment]
> 这仍然是 Meta 内核的问题，等作者修复吧（

意思是等待下一个meta内核的版本更新是吗？

**Comment by trantuan-20048607** [comment]
> > 这仍然是 Meta 内核的问题，等作者修复吧（
> 
> 意思是等待下一个meta内核的版本更新是吗？

可以等等看、换 developer 通道的内核，不行就退版本（
老版本也不是不能用

**Comment by Leefurmore** [comment]
> > > 这仍然是 Meta 内核的问题，等作者修复吧（
> > 
> > 
> > 意思是等待下一个meta内核的版本更新是吗？
> 
> 可以等等看、换 developer 通道的内核，不行就退版本（ 老版本也不是不能用

看来只能这样了，先用老版本，等新版本出来再看看吧，感谢您的协助～

**Comment by crazynet999** [comment]
修正了吗？更新了内核，发现只有tuic能够连上，vmess不行了，同样的配置……

**Comment by Leefurmore** [comment]
> 修正了吗？更新了内核，发现只有tuic能够连上，vmess不行了，同样的配置……

我这只要更新就一直连不上网，还在用旧版本内核，不知啥时候可以正常更新

**Comment by Leefurmore** [comment]
> > 我这只要更新就一直连不上网，还在用旧版本内核，不知啥时候可以正常更新
> 
> 如果确定只和内核有关建议去内核那边反馈。
> 
> vless报400，内核那边已经有人反馈了，但状况描述不详细，但没人回。

meta内核版本最近出了新版，目前还是一样的状况，更新后vmess，vless，trojan都无法联网

**Comment by gdanmac** [comment]
meta内核版本 在arm上好像是有问题

**Comment by phoenix13023** [comment]
> > > 我这只要更新就一直连不上网，还在用旧版本内核，不知啥时候可以正常更新
> > 
> > 
> > 如果确定只和内核有关建议去内核那边反馈。
> > vless报400，内核那边已经有人反馈了，但状况描述不详细，但没人回。
> 
> meta内核版本最近出了新版，目前还是一样的状况，更新后vmess，vless，trojan都无法联网

楼主，这是内核问题么！？ 我这折腾了一个星期，几家机场，不管是fake还是基础默认的，meta 连接，一直服务器一下黑一片，然后又偶尔好一小段时间，就完全不可用。

有两个小问题，不知道能帮忙回答下么：
1，老版本内核哪下载啊？有github地址么？
2，我目前看openwrt接口 utun就没这设备。

**Comment by Leefurmore** [comment]
> > > > 我这只要更新就一直连不上网，还在用旧版本内核，不知啥时候可以正常更新
> > > 
> > > 
> > > 如果确定只和内核有关建议去内核那边反馈。
> > > vless报400，内核那边已经有人反馈了，但状况描述不详细，但没人回。
> > 
> > 
> > meta内核版本最近出了新版，目前还是一样的状况，更新后vmess，vless，trojan都无法联网
> 
> 楼主，这是内核问题么！？ 我这折腾了一个星期，几家机场，不管是fake还是基础默认的，meta 连接，一直服务器一下黑一片，然后又偶尔好一小段时间，就完全不可用。
> 
> 有两个小问题，不知道能帮忙回答下么： 1，老版本内核哪下载啊？有github地址么？ 2，我目前看openwrt接口 utun就没这设备。

老版本在release那一直往下拉就可以下载，但我那么下载的内核无法使用，也不知道为啥，我是用的以前的系统备份里拉出来的。utun的问题我不清楚。

**Comment by maike2019** [comment]
我说呢，我把我的N1 79+O固件，clash meta 内核版本是1.15.0，以前一直使用正常。最近刷机为最新的87+O，之后有刷为88+O，发现所有节点在open clash上都无法使用，导致我反复几天刷机那么多次，还以为是固件问题或者open clash的插件问题，我把插件从最新版往回每个版本都试了一次都不行，我又回退到插件到0.45.78版本可以正常用了，但是一会儿关闭open clash或重启又不行。原来问题出在meta最新版本的核心上啊。我现在又用上了 N1 88+O固件，openclash插件版本为v0.46.003-beta，内核手动下载替换为v1.16.0，现在使用正常，我在继续观察下，看看使用是否还有问题，继续观察中。不知道是不是楼主所说的meta核心问题，以前更新为最新meta核心版本alpha-gfeedc9e 后，的确所有节点都无法使用，是能本地连接国内上网，外网节点都没法用，不通，日志BUG显示  警告TCP******************400bad

**Comment by Leefurmore** [comment]
> 我说呢，我把我的N1 79+O固件，clash meta 内核版本是1.15.0，以前一直使用正常。最近刷机为最新的87+O，之后有刷为88+O，发现所有节点在open clash上都无法使用，导致我反复几天刷机那么多次，还以为是固件问题或者open clash的插件问题，我把插件从最新版往回每个版本都试了一次都不行，我又回退到插件到0.45.78版本可以正常用了，但是一会儿关闭open clash或重启又不行。原来问题出在meta最新版本的核心上啊。我现在又用上了 N1 88+O固件，openclash插件版本为v0.46.003-beta，内核手动下载替换为v1.16.0，现在使用正常，我在继续观察下，看看使用是否还有问题，继续观察中。不知道是不是楼主所说的meta核心问题，以前更新为最新meta核心版本alpha-gfeedc9e 后，的确所有节点都无法使用，是能本地连接国内上网，外网节点都没法用，不通，日志BUG显示 警告TCP******************400bad

meta内核开始出现问题就是去年9月份以后的事情了，我从备份里拿出来的是8月份的，所以一直用到现在。我看了一下，你说的v16.0是9月的版本，不知道后续更高的版本你手动替换的话，是否也能正常使用？希望你能试一下，可以的话，回复一下我，谢谢。

**Comment by maike2019** [comment]
> > 我说呢，我把我的N1 79+O固件，clash meta 内核版本是1.15.0，以前一直使用正常。最近刷机为最新的87+O，之后有刷为88+O，发现所有节点在open clash上都无法使用，导致我反复几天刷机那么多次，还以为是固件问题或者open clash的插件问题，我把插件从最新版往回每个版本都试了一次都不行，我又回退到插件到0.45.78版本可以正常用了，但是一会儿关闭open clash或重启又不行。原来问题出在meta最新版本的核心上啊。我现在又用上了 N1 88+O固件，openclash插件版本为v0.46.003-beta，内核手动下载替换为v1.16.0，现在使用正常，我在继续观察下，看看使用是否还有问题，继续观察中。不知道是不是楼主所说的meta核心问题，以前更新为最新meta核心版本alpha-gfeedc9e 后，的确所有节点都无法使用，是能本地连接国内上网，外网节点都没法用，不通，日志BUG显示 警告TCP******************400bad
> 
> meta内核开始出现问题就是去年9月份以后的事情了，我从备份里拿出来的是8月份的，所以一直用到现在。我看了一下，你说的v16.0是9月的版本，不知道后续更高的版本你手动替换的话，是否也能正常使用？希望你能试一下，可以的话，回复一下我，谢谢。

我的旁路由设备是N1盒子（ARM 架构A53 CPU），固件为暴躁老哥https://github.com/breakings/OpenWrt/releases/tag/ARMv8 打包的88+O，我刚刚把内核手动替换为最新的正式版v1.18.1后，重启软路由，可以正常运行，国外国内访问正常，我使用的是Fake ip模式+meta内核。由于我的设备是ARM架构CPU设备，我下载的文件包名字是 mihomo-linux-arm64-v1.18.1 ，下载解压缩后，将核心文件名改为 clash_meta ，之后将其用复制进软路由文件夹/etc/openclash/core 替换原来的内核，之后断开充电插头，再插上。重启后，进入软路由管理后台openclash正常运行，open clash版本是v0.46.003-beta，是当今最新的，而openclash设置中的版本更新里面，检测到的最新版可更新的meta最新版本是 alpha-gfeedc9e。 我也不清楚是不是这个alpha-gfeedc9e最新版内核的问题，我以后再继续观察。但我发现我以前79+O版本固件，后续我也曾几次更新内核，那时候更新到1.15.0之后就一直没刷过新固件，也没更新过内核了，当时79+O的meta内核版本为1.15.0，大小是26.6MB，而alpha-gfeedc9e这个最新的内核更新下来，alpha-gfeedc9e  大小是5.94MB。而我手动下载替换的1.16.0版本内核大小是27.3MB，1.18.1 版本meta内核（mihomo-linux-arm64-v1.18.1解压缩后），1.18.1版本meta内核文件大小是28.8MB。所以问题到底出在哪里我也不能确定，我也是个菜鸟，不是程序员，也不是大神。不过提示可更新的最新版meta内核更新下载下来，其大小只有5.94MB，好像和其他版本的大小相差也太大了吧。我在使用观察中，看看日后能否一切正常。

**Comment by Leefurmore** [comment]
> > > 我说呢，我把我的N1 79+O固件，clash meta 内核版本是1.15.0，以前一直使用正常。最近刷机为最新的87+O，之后有刷为88+O，发现所有节点在open clash上都无法使用，导致我反复几天刷机那么多次，还以为是固件问题或者open clash的插件问题，我把插件从最新版往回每个版本都试了一次都不行，我又回退到插件到0.45.78版本可以正常用了，但是一会儿关闭open clash或重启又不行。原来问题出在meta最新版本的核心上啊。我现在又用上了 N1 88+O固件，openclash插件版本为v0.46.003-beta，内核手动下载替换为v1.16.0，现在使用正常，我在继续观察下，看看使用是否还有问题，继续观察中。不知道是不是楼主所说的meta核心问题，以前更新为最新meta核心版本alpha-gfeedc9e 后，的确所有节点都无法使用，是能本地连接国内上网，外网节点都没法用，不通，日志BUG显示 警告TCP******************400bad
> > 
> > 
> > meta内核开始出现问题就是去年9月份以后的事情了，我从备份里拿出来的是8月份的，所以一直用到现在。我看了一下，你说的v16.0是9月的版本，不知道后续更高的版本你手动替换的话，是否也能正常使用？希望你能试一下，可以的话，回复一下我，谢谢。
> 
> 我的旁路由设备是N1盒子（ARM 架构A53 CPU），固件为暴躁老哥https://github.com/breakings/OpenWrt/releases/tag/ARMv8 打包的88+O，我刚刚把内核手动替换为最新的正式版v1.18.1后，重启软路由，可以正常运行，国外国内访问正常，我使用的是Fake ip模式+meta内核。由于我的设备是ARM架构CPU设备，我下载的文件包名字是 mihomo-linux-arm64-v1.18.1 ，下载解压缩后，将核心文件名改为 clash_meta ，之后将其用复制进软路由文件夹/etc/openclash/core 替换原来的内核，之后断开充电插头，再插上。重启后，进入软路由管理后台openclash正常运行，open clash版本是v0.46.003-beta，是当今最新的，而openclash设置中的版本更新里面，检测到的最新版可更新的meta最新版本是 alpha-gfeedc9e。 我也不清楚是不是这个alpha-gfeedc9e最新版内核的问题，我以后再继续观察。但我发现我以前79+O版本固件，后续我也曾几次更新内核，那时候更新到1.15.0之后就一直没刷过新固件，也没更新过内核了，当时79+O的meta内核版本为1.15.0，大小是26.6MB，而alpha-gfeedc9e这个最新的内核更新下来，alpha-gfeedc9e 大小是5.94MB。而我手动下载替换的1.16.0版本内核大小是27.3MB，1.18.1 版本meta内核（mihomo-linux-arm64-v1.18.1解压缩后），1.18.1版本meta内核文件大小是28.8MB。所以问题到底出在哪里我也不能确定，我也是个菜鸟，不是程序员，也不是大神。不过提示可更新的最新版meta内核更新下载下来，其大小只有5.94MB，好像和其他版本的大小相差也太大了吧。我在使用观察中，看看日后能否一切正常。

好的，感谢回复，我是x86的设备，其他所有情况和你一样，不过我手动下载后替换的话，还是不能正常使用的，我也不知道问题在哪里。
