### ISSUE TITLE
[Bug] 订阅中添加排除节点就无法下载订阅文件

### ISSUE THREAD

**Issue by AaronHzy** [vernesong/OpenClash#3657]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.157

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

订阅中添加排除节点就会导致无法下载订阅配置文件

### Describe the Bug

订阅中添加排除节点就会导致无法下载订阅配置文件

### OpenClash Log

2023-12-06 11:51:01 错误：【xx云】下载失败，请检查网络或稍后再试...
2023-12-06 11:50:49 错误：配置文件【xx云】订阅失败，尝试不使用代理下载配置文件...
2023-12-06 11:50:49 开始更新配置文件【xx云】...

### Expected Behavior

如何配置排除节点

### Screenshots

![screenshot20231206](https://github.com/vernesong/OpenClash/assets/34953899/16c0bed9-7602-4938-9dc2-6227a7ddbebd)

**Comment by vernlau** [comment]
这个是subconverter后端的问题，退回[v0.8.1]的后端是正常的，那边有人提了，没处理

**Comment by sachikomakino** [comment]
同样的问题，预设的几个地址都是订阅失败，前几天还没问题～
