### ISSUE TITLE
希望能增加openai移动端的解锁

### ISSUE THREAD

**Issue by hjchjchjc4352** [vernesong/OpenClash#3659]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

使用现在openclash自带的openai解锁，节点可以正常打开网页端，但是有些节点移动端的chatgpt无法连接，移动端是通过android.chat.openai.com，ios.chat.openai.com来进行判定
![1702008531671](https://github.com/vernesong/OpenClash/assets/38029452/c6e56c7c-cbfa-4880-bffa-164769e20731)
![1702008531679](https://github.com/vernesong/OpenClash/assets/38029452/4d0fb07a-d0c8-480e-8218-16e8b4132c01)

### Describe the Solution

https://blog.gujiakai.top/2023/10/chatgpt-android-error-disallowed-isp-solution
https://github.com/1-stream/RegionRestrictionCheck
帖子搬运：“脚本的检测原理就是获取curl ios.chat.openai.com命令的执行结果，接着根据返回结果，将OpenAI移动端解锁与否的含义直观地在终端上呈现”

**Comment by Galaxian-Explosion** [comment]
如果你好好看过你引用的文章，你就没发现，人家最后解决靠的是vps后再挂二级代理吗？
openclash所谓的解锁只能保证没有漏网之鱼，把该代理的流量送到节点。如果流量送到节点后还显示不支持移动端，那不就是你的节点只能解锁网页、不能移动端吗？
除非你能提供clash内核日志，证明android.chat.openai.com，ios.chat.openai.com这两个域名没发到节点去，那才有继续讨论的价值。

**Comment by hjchjchjc4352** [comment]
> 如果你好好看过你引用的文章，你就没发现，人家最后解决靠的是vps后再挂二级代理吗？
> openclash所谓的解锁只能保证没有漏网之鱼，把该代理的流量送到节点。如果流量送到节点后还显示不支持移动端，那不就是你的节点只能解锁网页、不能移动端吗？
> 除非你能提供clash内核日志，证明android.chat.openai.com，ios.chat.openai.com这两个域名没发到节点去，那才有继续讨论的价值。

我当然看了原文，原文vps的ip就已经是被openai封禁的所以要挂代理，我看了openclash_streaming_unlock是通过对https://chat.openai.com/cdn-cgi/trace进行判定解锁，根本不涉及移动端，如果分流规则我都确定不好我都不好意思提这个需求，当然也只是需求并不是bug汇报，我现在是临时找了个节点支持解锁移动端这两个域名做好分流解决的，那提个需求总没问题吧

**Comment by Galaxian-Explosion** [comment]
Not even wrong.
正常openai相关的规则都是domain-suffix,openai.com，早就把这android.chat.openai.com，ios.chat.openai.com两个域名包进去了，只要你网页端chat.openai.com能走代理，那这两个域名基本走的是也是同一个代理。

既然都是同一个代理，那移动端被拒，除了说明你节点不行之外，跟openclash有什么关系呢？你是觉得openclash所谓的解锁有什么黑魔法吗？

**Comment by hjchjchjc4352** [comment]
> Not even wrong.
> 正常openai相关的规则都是domain-suffix,openai.com，早就把这android.chat.openai.com，ios.chat.openai.com两个域名包进去了，只要你网页端chat.openai.com能走代理，那这两个域名基本走的是也是同一个代理。
> 
> 既然都是同一个代理，那移动端被拒，除了说明你节点不行之外，跟openclash有什么关系呢？你是觉得openclash所谓的解锁有什么黑魔法吗？

别扯什么英文，跟二五八万似的，节点不行我这个需求就是想筛个行的节点，这都看不懂还说什么呢，人作者大佬都没说话，人家不认可自然会关了这个需求

**Comment by Galaxian-Explosion** [comment]
>人作者大佬都没说话，人家不认可自然会关了这个需求

巧了，作者连指着他鼻子骂的issue都懒得关 #3393 

>节点不行我这个需求就是想筛个行的节点，这都看不懂还说什么呢

你连openclash的解锁是在解锁什么都没搞清楚，你在这儿说什么呢？啥时候一个透明代理插件就能帮你选节点了？

**Comment by hjchjchjc4352** [comment]
> >人作者大佬都没说话，人家不认可自然会关了这个需求
> 
> 巧了，作者连指着他鼻子骂的issue都懒得关 #3393 
> 
> >节点不行我这个需求就是想筛个行的节点，这都看不懂还说什么呢
> 
> 你连openclash的解锁是在解锁什么都没搞清楚，你在这儿说什么呢？啥时候一个透明代理插件就能帮你选节点了？
> 

球球你了，不会用openclash看不懂人话就别说了，好好一个issue，别沦为对骂脏地了，你别回了好吗，关你吊事呢

**Comment by hjchjchjc4352** [comment]
> >好好一个issue，别沦为对骂脏地了，你别回了好吗，关你吊事呢
> 
> 我倒要看看是谁用了脏字
> 
> >不会用openclash看不懂人话就别说了
> 
> 继续精神胜利法。做不到的事情就是做不到，你若觉得透明代理插件能自动帮你选节点，那最好给出方案来，让大家都开开眼。
> 

哈哈对不起对不起，关你p事呢，这应该可以了吧
你不会呢是你自己不会，没人会嘲笑，但没必要拿出来炫耀，不值得

**Comment by Galaxian-Explosion** [comment]
乐了，没法做和不会做都分不清。
你说能做你就pr嘛，不知道的还以为你id上带着contributor标签呢，好大的口气。

**Comment by hjchjchjc4352** [comment]
> 乐了，没法做和不会做都分不清。
> 你说能做你就pr嘛，不知道的还以为你id上带着contributor标签呢，好大的口气。

没事你想乐就继续乐，最好自己再开个issue乐，你这英文我属实看不懂，哪国人？口气也是学你来的，github真能学不少东西呢，你也记得多学学哈，不会就少哔多学，没错的

**Comment by lifetyper** [comment]
明确两个问题：
1.解锁不解锁取决于节点，跟openclash没有关系，现在的分流规则也都已经包含了两者。
2.我觉得你的**准确诉求**是：增加openai移动端解锁的检测，类似流媒体增强里“*自动选择解锁节点”的功能，并不是让openclash把不能解锁的节点变成能解锁的节点。

那么问题在哪里？

也许你应该写：
希望能增加openai移动端的解锁**检测**？？？

**Comment by hjchjchjc4352** [comment]
> 明确两个问题：
> 1.解锁不解锁取决于节点，跟openclash没有关系，现在的分流规则也都已经包含了两者。
> 2.我觉得你的**准确诉求**是：增加openai移动端解锁的检测，类似流媒体增强里“*自动选择解锁节点”的功能，并不是让openclash把不能解锁的节点变成能解锁的节点。
> 
> 那么问题在哪里？
> 
> 也许你的issue标题应该写：
> 希望能增加openai移动端的解锁**检测**？？？
> 
> 毕竟除了标题之外我没看到内容里有任何关于具体诉求的体现，当然你在后面的对话中提到了，不过这标题已经引发误会了。
> 
> 事实上筛选节点这种事，你也可以自己测试完然后手动写入配置文件里指定解锁节点的，自动选节点这功能除非是节点整天变化，否则我感觉很少用得上。

是这个意思，也许是我表述不当，但openclash解锁相关的就只在流媒体解锁模块里面存在，正常是看一下应该能理解我的需求。
我现在也确实是测了个支持的节点来解决的，当然如果可以我是希望能够增加一个移动端的解锁功能，毕竟原来网页端是没问题的。
另外有错误我可以认识，可以改，但像那位那样颐指气使的口气不知道谁给他的勇气
