### ISSUE TITLE
[Feature] 可不可以增加一个开关，可以让用户自己控制是否需要自动检查或者自动更新Openclash，而不是每次都强制自动检查更新，尤其在目前这种clash作者和内核作者停更状态下，未来是否能够更新还不明朗，这个功能对很多人来说尤为重要，谢谢

### ISSUE THREAD

**Issue by lpflhh** [vernesong/OpenClash#3669]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

可不可以增加一个开关，可以让用户自己控制是否需要自动检查或者自动更新Openclash，而不是每次都强制自动检查更新，尤其在目前这种clash作者和内核作者停更状态下，未来是否能够更新还不明朗，这个功能对很多人来说尤为重要，谢谢

### Describe the Solution

<img width="1088" alt="屏幕截图 2023-12-12 005514" src="https://github.com/vernesong/OpenClash/assets/11377367/2db7c06a-0e2f-4ee7-816b-8e3bfd097982">

### Describe Alternatives

可不可以增加一个开关，可以让用户自己控制是否需要自动检查或者自动更新Openclash，而不是每次都强制自动检查更新，尤其在目前这种clash作者和内核作者停更状态下，未来是否能够更新还不明朗，这个功能对很多人来说尤为重要，谢谢

### Additional Context

可不可以增加一个开关，可以让用户自己控制是否需要自动检查或者自动更新Openclash，而不是每次都强制自动检查更新，尤其在目前这种clash作者和内核作者停更状态下，未来是否能够更新还不明朗，这个功能对很多人来说尤为重要，谢谢
<img width="1088" alt="屏幕截图 2023-12-12 005514" src="https://github.com/vernesong/OpenClash/assets/11377367/472c9a5f-d1b9-4318-80a2-973383b8609e">

**Comment by zxlhhyccc** [comment]
你指的是自动检查数据库、配置更新还是内核与插件的更新？数据库、配置自动更新可以自己luci设置，内核和配置不会自动更新，需手动更新！

**Comment by fengquan1984** [comment]
这个问题我也遇到了，提示clash_latest_verison下载失败，然后断网。PS：本人没有点击版本更新，甚至连内核更新标签都没有点击过。希望作者能够考虑这个功能。

**Comment by fengquan1984** [comment]
是这样，是DNS污染，我用了各种方法，都不管用。建议直接加一个开关，屏蔽这种行为。

**Comment by lpflhh** [comment]
> 你指的是自动检查数据库、配置更新还是内核与插件的更新？数据库、配置自动更新可以自己luci设置，内核和配置不会自动更新，需手动更新！

请看图片，谢谢

**Comment by MZRidaz** [comment]
等于脱裤子放屁，更新都是手动，你不确定好不好不更新不就行了。

**Comment by lpflhh** [comment]
> 等于脱裤子放屁，更新都是手动，你不确定好不好不更新不就行了。

如果眼神不好是要尽快配镜的！那么大的截图看不到吗？那里面几十上百条的报错信息，每一条都在提示插件每隔6秒就要自动检查更新尝试下载最新版本或者获取最新版信息，我指的是能不能加一个开关，控制它不要这么频繁的自动更新。而且今天发现，在内存低于512M的设备上，这个报错持续2小时左右会导致路由器直接不能访问，必须重新断电，测试均使用插件默认配置。

**Comment by sangyishuje1123** [comment]
为什么总有人喜欢把结果当原因 XD

**Comment by deuteros-gex** [comment]
哦，又是这个问题是吧。#3287 #3379 #2791

会报这个错的脚本有好几个，仅凭你给的信息定位不了问题，你得提供稳定复现的方法。
多观察观察这些日志什么情况下会出现，找出点规律再说，否则就只能等作者哪天灵光乍现了。

因为openclash现有的代码套娃套太多次了，一般没人愿意去做正向检查。
你可能觉得给个开关就行，但设计上这些功能从来都是只能手动触发的，并不是自动的。
