### ISSUE TITLE
求问配置订阅功能如何支持hy2节点

### ISSUE THREAD

**Issue by jayling1111** [vernesong/OpenClash#3675]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

配置订阅功能，添加hy2节点信息会失败，有没有哪个后端是支持这个转换的？

### Describe the Solution

配置订阅功能，添加hy2节点信息会失败，有没有哪个后端是支持这个转换的？

**Comment by nick1987xt** [comment]
请使用Meta内核来配置hy2节点，按照clash.meta的书写规格来书写自己的节点信息或直接从服务端获取clash- Meta.yaml

**Comment by jayling1111** [comment]
> 请使用Meta内核来配置hy2节点，按照clash.meta的书写规格来书写自己的节点信息或直接从服务端获取clash- Meta.yaml

节点手动添加是成功的，我想问的是哪个订阅后端支持配置订阅转换，内置的几个后端都不支持hy2协议

**Comment by zane-ng** [comment]
> > 请使用 Meta 内核来配置 hy2 节点，按照 clash.meta 的书写规格来书写自己的节点信息或直接从服务端获取 clash- Meta.yaml
> 
> 节点手动添加是成功的，我想问的是哪个订阅后端支持配置订阅转换，内置的几个后端都不支持 hy2 协议

@jayling1111 157 版本中 v.id9.cc 应该是支持的（个人目前使用）。如果还是不支持，在设置-版本更新中，分支选择 Developer ，似乎可以解决（参考 #3520 ）。

**Comment by werran2** [comment]
> > 请使用Meta内核来配置hy2节点，按照clash.meta的书写规格来书写自己的节点信息或直接从服务端获取clash- Meta.yaml
> 
> 节点手动添加是成功的，我想问的是哪个订阅后端支持配置订阅转换，内置的几个后端都不支持hy2协议

我用品云那个成功了
