### ISSUE TITLE
[Bug] 仓库中「clash-linux-amd64-v3-2023.08.17-13-gdcc8d87.gz」文件是个大小为0的空文件

### ISSUE THREAD

**Issue by nukewarrior** [vernesong/OpenClash#3676]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.157-beta

### Bug on Environment

Lean

### Bug on Platform

Linux-amd64-v3(x86-64)

### To Reproduce

选择linux-amd64-v3平台，无法下载内核

### Describe the Bug

[clash-linux-amd64-v3-2023.08.17-13-gdcc8d87.gz](https://github.com/vernesong/OpenClash/blob/core/master/premium/clash-linux-amd64-v3-2023.08.17-13-gdcc8d87.gz)
文件为空无法下载

### OpenClash Log

1

### Expected Behavior

1

**Comment by sangyishuje1123** [comment]
三个月都没人发现啊，先自己传上版凑合用吧。
https://github.com/vernesong/OpenClash/tree/2d53dcac0a3c28151eac5537d8b97c918d916c28/dev/premium

**Comment by nukewarrior** [comment]
> 三个月都没人发现啊，先自己传上版凑合用吧。 https://github.com/vernesong/OpenClash/tree/2d53dcac0a3c28151eac5537d8b97c918d916c28/dev/premium

可能大家用amd64比较多，而不是amd64-v3吧。话说，我检索到的资料是建议使用更好amd64-v3而不是amd64，请问是这样么？

**Comment by sangyishuje1123** [comment]
https://go.dev/wiki/MinimumRequirements#amd64

提升是肯定有的，但路由器上挂的代理有需求且能跑满千兆的又有几个人，反正可以选的情况下选了没坏处。
