### ISSUE TITLE
[BUG] wiki 的版本太老旧了，和新版的 UI 完全对不上

### ISSUE THREAD

**Issue by LeeYunhang** [vernesong/OpenClash#3687]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

如题，几乎完全没有参考价值了

### Describe the Solution

可能是我的版本问题嘛

**Comment by rsgdn** [comment]
这个看内核文档一样效果的
