### ISSUE TITLE
[Bug] 0.45.157版本yacd面板打不开

### ISSUE THREAD

**Issue by bzkmsjy** [vernesong/OpenClash#3689]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

0.45.157

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-arm64

### To Reproduce

更新了一下OpenClash，yacd面板就打不开了，yacd面板地址和密码都是默认的，以前无论怎么更新Openwrt和OpenClash，只要路由器地址不变就可以打开，现在同样的地址打开是这个样子的，无论是下面默认的地址和自己添加的地址都打不开yacd面板
<img width="646" alt="屏幕截图 2023-12-19 092629" src="https://github.com/vernesong/OpenClash/assets/112675091/a0bbf24f-4a7c-428a-a290-e26e392bc3d7">

### Describe the Bug

yacd面板打不开y

### OpenClash Log

应该不需要吧，运行日志看不到面板相关

### Expected Behavior

打开yacd面板

### Screenshots

<img width="646" alt="屏幕截图 2023-12-19 092629" src="https://github.com/vernesong/OpenClash/assets/112675091/66c5bf8e-9586-4a2f-9699-ec7664413db0">

**Comment by sangyishuje1123** [comment]
emmmm

分两部分

---

156以后的oc密码不默认了，每次安装或更新都会随机生成，所以要固定密码只能自己手动设置了

---




你这个 yacd 的问题158就修了 https://github.com/vernesong/OpenClash/commit/d8072dcbd2f894e19e93faf13dfce1d846176832 

https://github.com/vernesong/OpenClash/blob/07707bb6524c9640c0f252af505e9ed1583fb23d/dev/luci-app-openclash_0.45.158-beta_all.ipk

> - [x] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在

建议看一下内容再打勾。

**Comment by Airshuai** [comment]
我也遇到完全相同的问题

**Comment by linxingwu** [comment]
v0.45.157-beta
不仅仅是yacd，metacubexd也不行了，能打开，但是没有数据。
![image](https://github.com/vernesong/OpenClash/assets/11658121/d58489c8-d5c9-42a3-9f0c-4fdf04e5f34c)
![image](https://github.com/vernesong/OpenClash/assets/11658121/9a4c5e64-0b0f-4a3b-8646-2c9c333905b2)
感觉是401，没有连到openclash

**Comment by sangyishuje1123** [comment]
> v0.45.157-beta 不仅仅是yacd，metacubexd也不行了，能打开，但是没有数据。 ![image](https://private-user-images.githubusercontent.com/11658121/292855030-d58489c8-d5c9-42a3-9f0c-4fdf04e5f34c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4OTk3ODAsIm5iZiI6MTcwMzg5OTQ4MCwicGF0aCI6Ii8xMTY1ODEyMS8yOTI4NTUwMzAtZDU4NDg5YzgtZDVjOS00MmEzLTlmMGMtNGZkZjA0ZTVmMzRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMwVDAxMjQ0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4MjRiZDI2MzVlODdlZWI0MzZiMTRkNjAyZTQ5ZDRhMzgzZGUzZWRlYmY1ZGYyOWQ3NDQ2MGM5NzAxMWM4NDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0esW35VGaSpctHapcQb5UehOrxQhmCvG9vpN-QaqsJk) ![image](https://private-user-images.githubusercontent.com/11658121/292855087-9a4c5e64-0b0f-4a3b-8646-2c9c333905b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4OTk3ODAsIm5iZiI6MTcwMzg5OTQ4MCwicGF0aCI6Ii8xMTY1ODEyMS8yOTI4NTUwODctOWE0YzVlNjQtMGIwZi00YTNiLTg2NDYtMmM5YzMzMzkwNWIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMwVDAxMjQ0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2MzYxMmM0NjIwMWQ5NGY5ZDdjN2ZkMzEzZDBjNDk4Y2VhNTM4MWYzNTdjMzU5ZWEwNzYzMjQ1YjViZmU2M2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bcmNQCslXVJ3lP8Sx5k1sNx2AouIKSxggXRD7ecJKtg) 感觉是401，没有连到openclash

metacubexd 是受改随机密码影响了，隐私模式或清浏览器缓存缓存和cookie试试

用yacd的升级158后再清浏览器缓存和cookie

**反正156以前的版本升156以后的版本都是要清缓存和cookie**

**Comment by Cnmajun** [comment]
我也是一样的问题，无法打开yacd面板。
**但是metax和dashboard面板使用正常**。
使用无痕模式打开的话，yacd面板会`正常的闪现一下，然后又回到界面入口。已经测试了无数次。
ps: openclash已经是最新版本

**Comment by Cnmajun** [comment]
> 我也是一样的问题，无法打开yacd面板。 **但是metax和dashboard面板使用正常**。 使用无痕模式打开的话，yacd面板会`正常的闪现一下，然后又回到界面入口。已经测试了无数次。 ps: openclash已经是最新版本

在openclash的   插件设置  -》外部控制 里面把密码改成123456，重启以后问题解决了。注意这个yacd不要用meta版本。

**Comment by Rangtian** [comment]
> > 我也是一样的问题，无法打开yacd面板。
> > 但是metax和dashboard面板使用正常。
> > 使用无痕模式打开的话，yacd面板会`正常的闪现一下，然后又回到界面入口。已经测试了无数次。
> > ps: openclash已经是最新版本
> > 在openclash的 插件设置 -》外部控制 里面把密码改成123456，重启以后问题解决了。注意这个yacd不要用meta版本。
> 
> 你这其实还是缓存和cookie问题。。。 123456能打开是因为你之前密码是123456

清除浏览器cookies后：

Yacd 能短暂登上去几秒钟，然后就「Oops, something went wrong!」；
Metacubexd 依旧是能登录，但无数据；
Dashboard 依旧是卡在登录界面，点击「OK」无反应。
