### ISSUE TITLE
更新内核无法使用VMESS链接，只能tuic，同一节点[Bug] 

### ISSUE THREAD

**Issue by crazynet999** [vernesong/OpenClash#3692]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.157-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

更新内核无法使用VMESS链接，只能tuic，同一节点连接

### Describe the Bug

更新内核无法使用VMESS链接，只能tuic，同一节点连接

### OpenClash Log

困扰很久，为啥出现这个问题

### Expected Behavior

     期待修复     

### Screenshots

   期待修复

**Comment by sangyishuje1123** [comment]
更新内核后出现的问题是否表示这是内核的bug？

 

> - [x] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
