### ISSUE TITLE
[Feature] 如何跳过adobe认证

### ISSUE THREAD

**Issue by beebeam** [vernesong/OpenClash#3694]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

开启openclash后局域网内的电脑adobe软件开启就验证检测失败无法使用

### Describe the Solution

如何可以屏蔽掉adobe验证服务器

**Comment by blngxj** [comment]
屏蔽如下
activate.adobe.com
practivate.adobe.com
ereg.adobe.com
activate.wip3.adobe.com
wip3.adobe.com
3dns-3.adobe.com
3dns-2.adobe.com
adobe-dns.adobe.com
adobe-dns-2.adobe.com
adobe-dns-3.adobe.com
ereg.wip3.adobe.com
activate-sea.adobe.com
wwis-dubc1-vip60.adobe.com
activate-sjc0.adobe.com
