### ISSUE TITLE
订阅V2ray Bug

### ISSUE THREAD

**Issue by RealKiro** [vernesong/OpenClash#37]
- 在订阅V2ray协议的地址，检查并更新订阅后Openclash自动停止运行（未运行），实测使用Clash协议的地址正常
![image](https://user-images.githubusercontent.com/33367701/65824282-e7994a00-e298-11e9-8743-c6b41818cc32.png)

![image](https://user-images.githubusercontent.com/33367701/65824275-ccc6d580-e298-11e9-849a-800e5624b709.png)

- 订阅的地址和手动填写的✈️地址在`控制面板`没有同时显示，我该在哪里设置才能同时显示呢？
![image](https://user-images.githubusercontent.com/33367701/65824310-4bbc0e00-e299-11e9-9005-437e4c282c37.png)

具体：开启 订阅的地址 或 手动填写的✈️地址 逻辑是：点击更新订阅就是订阅地址自动开启，点击服务器&策略组管理下的应用配置就是手动填写的开启；所以如何同时开启然后再能在控制面板都显示？

---

- 控制面板里面日志为空，而luci-app-clash日志是正常的

**Comment by vernesong** [comment]
订阅跟手动添加的节点暂时不支持同时进行，因为容易受订阅影响导致启动失败。
你如果想合并，可以先读取配置文件，把订阅的节点读取出来，再自己添加节点，然后一键创建配置文件。
V2订阅后停止运行，你看下日志是不是有错误，因为订阅下载失败不会重启，只有配置文件读取失败才可能导致启动失败。

**Comment by RealKiro** [comment]
> 订阅跟手动添加的节点暂时不支持同时进行，因为容易受订阅影响导致启动失败。
> 你如果想合并，可以先读取配置文件，把订阅的节点读取出来，再自己添加节点，然后一键创建配置文件。
> V2订阅后停止运行，你看下日志是不是有错误，因为订阅下载失败不会重启，只有配置文件读取失败才可能导致启动失败。
> 控制面板的日志是内核日志，配置文件需要将日志等级改为非silent才会输出

1. 对照模板将`silent` 改为 `info`可以输出日志了，但是一键生成配置后又自动还原成silent了，总感觉按钮有点分散啊
2. 点击`启动OPENCLASH`总会有点问题，我想既然 自定义✈️有一键应用配置+订阅也有应用配置 的情况下这个按钮是否有点多余？

![image](https://user-images.githubusercontent.com/33367701/65831491-bc404a80-e2ec-11e9-912e-22d50757cb96.png)
![image](https://user-images.githubusercontent.com/33367701/65831545-53a59d80-e2ed-11e9-91a3-0b7dcdc431c4.png)
![image](https://user-images.githubusercontent.com/33367701/65831549-63bd7d00-e2ed-11e9-8ffc-92949b314ec1.png)

**Comment by vernesong** [comment]
应用配置对应的都是保存当前页面的设置并重启，涉及的脚本不一祥，这个一键页面现在基本是是给没有订阅的用户设置的

**Comment by vernesong** [comment]
日志等级你可以去yacd控制面板随意更改
