### ISSUE TITLE
[Bug] 疑似Bug，fake-ip模式下绕过中国大陆 IP功能中，黑名单设置无效。

### ISSUE THREAD

**Issue by gama791** [vernesong/OpenClash#3700]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.157-beta

### Bug on Environment

Lean

### Bug on Platform

Linux-armv7

### To Reproduce

Fake-IP模式下，使用“实验性：绕过中国大陆 IP”功能，其中的“绕过中国大陆 IPv4 黑名单”设置无效，比如默认黑名单输入框中的services.googleapis.cn，clash内核直接拿到了解析出来的国内IP，致使谷歌商店无法下载。

### Describe the Bug

在Fake-IP模式下，“实验性：绕过中国大陆 IP”功能，绕过中国大陆 IPv4 黑名单功能无效。Redir-Host模式正常。研究/etc/init.d/openclash文件，个人能力有限，发现貌似Redir-Host模式使用谷歌DNS重新做了域名解析，而Fake-IP模式下，直接把“绕过中国大陆 IP”功能指定DNS解析出来的国内IP，交给了clash内核。

### OpenClash Log

[Uploading OpenClash-2023-12-23-20-31-59.log…]()

### Expected Behavior

可以正常使用绕过中国大陆 IP的黑名单功能。

**Comment by lim-kim930** [comment]
同样的问题，一直解析到120.253.253.226，一个上海IP，导致谷歌商店下载转圈圈，加入了黑名单还是无效
![image](https://github.com/vernesong/OpenClash/assets/72185892/d110a2a2-694f-4389-9758-15605e8c1a7e)

**Comment by Mei-Sakura** [comment]
+1，fake ip模式的绕过中国大陆模式会导致谷歌商店下载转圈，黑名单设置无效

**Comment by sysalong** [comment]
fake ip模式  都没办法让局域网内部某个IP不走代理。。。哎。。愁。

**Comment by LemonPAKA** [comment]
> fake ip模式 都没办法让局域网内部某个IP不走代理。。。哎。。愁。

DNS模式设置为防火墙模式而不是dnsmasq转发就行

**Comment by heart8858** [comment]
一模一样的问题，redir可以，fake-ip模式即使加入黑名单，大陆dns指向AdguardHome的时候，services.googleapis.cn这个域名直接解析成本地地址了，根本没有经过clash内核

**Comment by heart8858** [comment]
> 一模一样的问题，redir可以，fake-ip模式即使加入黑名单，大陆dns指向AdguardHome的时候，services.googleapis.cn这个域名直接解析成本地地址了，根本没有经过clash内核

按我的使用环境，暂时的解决方法是AdguardHome里面DNS重写功能将services.googleapis.cn 重写为services.googleapis.com即正常

**Comment by lim-kim930** [comment]
> > 一模一样的问题，redir可以，fake-ip模式即使加入黑名单，大陆dns指向AdguardHome的时候，services.googleapis.cn这个域名直接解析成本地地址了，根本没有经过clash内核
> 
> 按我的使用环境，暂时的解决方法是AdguardHome里面DNS重写功能将services.googleapis.cn 重写为services.googleapis.com即正常

这个域名的DNS解析似乎到不了ADGuard，不知道是不是ADGuard的模式问题，我现在ADGuard设置的是作为dnsmasq的上游服务器

**Comment by heart8858** [comment]
> > > 一模一样的问题，redir可以，fake-ip模式即使加入黑名单，大陆dns指向AdguardHome的时候，services.googleapis.cn这个域名直接解析成本地地址了，根本没有经过clash内核
> > 
> > 
> > 按我的使用环境，暂时的解决方法是AdguardHome里面DNS重写功能将services.googleapis.cn 重写为services.googleapis.com即正常
> 
> 这个域名的DNS解析似乎到不了ADGuard，不知道是不是ADGuard的模式问题，我现在ADGuard设置的是作为dnsmasq的上游服务器

那你的使用环境跟我不一样，我dnsmasq的上游依旧是openclash，大陆dns指向ADGuard，只是绕过大陆在fakeip黑名单下无效，查看ADGuard发现services.googleapis.cn有记录，遂重写.com还真的奏效了

**Comment by sysalong** [comment]
fake ip模式 都没办法让局域网内部某个IP不走代理。。。哎。。愁。

**Comment by sysalong** [comment]
> > fake ip模式 都没办法让局域网内部某个IP不走代理。。。哎。。愁。
> 
> DNS模式设置为防火墙模式而不是dnsmasq转发就行

如果这样，我就没办法过滤广告，同时没办法做到DNS防泄漏

**Comment by LemonPAKA** [comment]
> > > fake ip模式 都没办法让局域网内部某个IP不走代理。。。哎。。愁。
> > 
> > 
> > DNS模式设置为防火墙模式而不是dnsmasq转发就行
> 
> 如果这样，我就没办法过滤广告，同时没办法做到DNS防泄漏

印象中防泄漏不应该是openclash的上游DNS决定的吗
https://ipleak.net/

**Comment by derekling** [comment]
请问新版有没有修复

**Comment by mmmjie** [comment]
我redirect也不行...填了绕过的域名,但实际还是走代理

**Comment by forvicky** [comment]
同样的问题，希望尽快修复一下

**Comment by keai336** [comment]
可以尝试 指定大陆域名DNS服务器为一个可以进行分流操作的本地服务器，在这个本地服务器配置一个上游服务器为clash的DNS服务，然后分流黑名单内的域名给这个上游服务器。

**Comment by keai336** [comment]
一个自用的暂时解决方案：
可以尝试 指定大陆域名DNS服务器为一个可以进行分流操作的本地服务器，在这个本地服务器配置一个上游服务器为clash的DNS服务，然后分流黑名单内的域名给这个上游服务器。

**Comment by Mrhs121** [comment]
依旧有这个bug 黑名单不生效，希望尽早修掉

**Comment by DreamFerry** [comment]
困扰已久的问题，请修复，谢谢
