### ISSUE TITLE
[Bug] clash节点订阅后通过一键生成添加新的策略组，排版出现问题导致报错

### ISSUE THREAD

**Issue by Xiaohantx** [vernesong/OpenClash#3702]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

0.45.157-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

All

### To Reproduce

在订阅 clash链接后再通过一键生成添加新的策略组写入的时候就会出现问题
`- name: "⚡️IPLC/IEPL"
  type: select
  proxies:
  - IEPL｜OpenAI专线-1 [2.0][ChatGPT]
  - "\U0001F1FC\U0001F1F8 IEPL｜京台 [2.0][原生]"
  - "\U0001F1F8\U0001F1EC IEPL｜京新 [2.0][UDP][ChatGPT]"
  - "\U0001F1EF\U0001F1F5 IEPL｜京日 [2.0][原生]"
  - "\U0001F1ED\U0001F1F0 IEPL｜京港 [2.0][原生]"
  - "\U0001F1FA\U0001F1F2 IEPL｜京美 [2.0][NF][原生]"
  - "\U0001F1EC\U0001F1E7 IEPL｜京英 [2.0]"
  - "\U0001F1FC\U0001F1F8 IEPL｜台湾媒体专线-1 [2.0][NF][Disney+]"
  - "\U0001F1F8\U0001F1EC IEPL｜新加坡媒体专线-1 [2.0][NF]"
  - "\U0001F1EF\U0001F1F5 IEPL｜日本媒体专线-1 [2.0][NF]"
  - "\U0001F1FC\U0001F1F8 IEPL｜沪台 [2.0][原生]"
  - "\U0001F1F8\U0001F1EC IEPL｜沪新 [2.0][UDP][ChatGPT]"
  - "\U0001F1EF\U0001F1F5 IEPL｜沪日 [2.0][原生]"
  - "\U0001F1ED\U0001F1F0 IEPL｜沪港 [2.0][原生]"
  - "\U0001F1FA\U0001F1F2 IEPL｜沪美 [2.0][NF][原生]"
  - "\U0001F1EC\U0001F1E7 IEPL｜沪英 [2.0]"
  - "\U0001F1FC\U0001F1F8 IEPL｜深台 [2.0][原生]"
  - "\U0001F1F8\U0001F1EC IEPL｜深新 [2.0][UDP][ChatGPT]"
  - "\U0001F1EF\U0001F1F5 IEPL｜深日 [2.0][原生]"
  - "\U0001F1ED\U0001F1F0 IEPL｜深港 [2.0][原生]"
  - "\U0001F1FA\U0001F1F2 IEPL｜深美 [2.0][NF][原生]"
  - "\U0001F1EC\U0001F1E7 IEPL｜深英 [2.0]"
  - IPLC｜OpenAI专线-1 [2.0][ChatGPT]
  - "\U0001F1FC\U0001F1F8 IPLC｜冀台 [2.0][原生]"
  - "\U0001F1F8\U0001F1EC IPLC｜冀新 [2.0][UDP][ChatGPT]"
  - "\U0001F1EF\U0001F1F5 IPLC｜冀日 [2.0][原生]"
  - "\U0001F1ED\U0001F1F0 IPLC｜冀港 [2.0][原生]"
  - "\U0001F1FA\U0001F1F2 IPLC｜冀美 [2.0][NF][原生]"
  - "\U0001F1FC\U0001F1F8 IPLC｜台湾媒体专线-1 [2.0][NF][Disney+]"
  - "\U0001F1F8\U0001F1EC IPLC｜新加坡媒体专线-1 [2.0][NF]"
  - "\U0001F1EF\U0001F1F5 IPLC｜日本媒体专线-1 [2.0][NF]"
  - "\U0001F1FC\U0001F1F8 IPLC｜沪台 [2.0][原生]"
  - "\U0001F1F8\U0001F1EC IPLC｜沪新 [2.0][UDP][ChatGPT]"
  - "\U0001F1EF\U0001F1F5 IPLC｜沪日 [2.0][原生]"
  - "\U0001F1ED\U0001F1F0 IPLC｜沪港 [2.0][原生]"
  - "\U0001F1FA\U0001F1F2 IPLC｜沪美 [2.0][NF][原生]"
  - "\U0001F1FC\U0001F1F8 IPLC｜浙台 [2.0][原生]"
  - "\U0001F1F8\U0001F1EC IPLC｜浙新 [2.0][UDP][ChatGPT]"
  - "\U0001F1EF\U0001F1F5 IPLC｜浙日 [2.0][原生]"
  - "\U0001F1ED\U0001F1F0 IPLC｜浙港 [2.0][原生]"
  - "\U0001F1FA\U0001F1F2 IPLC｜浙美 [2.0][NF][原生]"
  - "\U0001F1FC\U0001F1F8 IPLC｜深台 [2.0][原生]"
  - "\U0001F1F8\U0001F1EC IPLC｜深新 [2.0][UDP][ChatGPT]"
  - "\U0001F1EF\U0001F1F5 IPLC｜深日 [2.0][原生]"
  - "\U0001F1ED\U0001F1F0 IPLC｜深港 [2.0][原生]"
  - "\U0001F1FA\U0001F1F2 IPLC｜深美 [2.0][NF][原生]"
  - "\U0001F1FC\U0001F1F8 IPLC｜湘台 [2.0][原生]"
  - "\U0001F1F8\U0001F1EC IPLC｜湘新 [2.0][UDP][ChatGPT]"
  - "\U0001F1EF\U0001F1F5 IPLC｜湘日 [2.0][原生]"
  - "\U0001F1ED\U0001F1F0 IPLC｜湘港 [2.0][原生]"
  - "\U0001F1FA\U0001F1F2 IPLC｜湘美 [2.0][NF]"
  - "\U0001F1FC\U0001F1F8 IPLC｜珠台 [2.0][原生]"
  - "\U0001F1F8\U0001F1EC IPLC｜珠新 [2.0][UDP][ChatGPT]"
  - "\U0001F1EF\U0001F1F5 IPLC｜珠日 [2.0][原生]"
  - "\U0001F1ED\U0001F1F0 IPLC｜珠港 [2.0][原生]"
  - "\U0001F1FA\U0001F1F2 IPLC｜珠美 [2.0][NF][原生]"
  - "\U0001F1FC\U0001F1F8 IPLC｜苏台 [2.0][原生]"
  - "\U0001F1F8\U0001F1EC IPLC｜苏新 [2.0][UDP][ChatGPT]"
  - "\U0001F1EF\U0001F1F5 IPLC｜苏日 [2.0][原生]"
  - "\U0001F1ED\U0001F1F0 IPLC｜苏港 [2.0][原生]"
  - "\U0001F1FA\U0001F1F2 IPLC｜苏美 [2.0][NF][原生]"
  - "\U0001F1FC\U0001F1F8 IPLC｜闽台 [2.0][原生]"
  - "\U0001F1F8\U0001F1EC IPLC｜闽新 [2.0][UDP][ChatGPT]"
  - "\U0001F1EF\U0001F1F5 IPLC｜闽日 [2.0][原生]"
  - "\U0001F1ED\U0001F1F0 IPLC｜闽港 [2.0][原生]"
  - "\U0001F1FA\U0001F1F2 IPLC｜闽美 [2.0][原生][NF]"
  - DIRECT`
加入新的之后这里会转成
` name: "⚡️IPLC/IEPL"
  type: select
  proxies: "⚡️IPLC/IEPL - DIRECT - \"IEPL｜OpenAI专线-1 [2.0][ChatGPT]\" - \"\U0001F1FC\U0001F1F8
    IEPL｜京台 [2.0][原生]\" - \"\U0001F1F8\U0001F1EC IEPL｜京新 [2.0][UDP][ChatGPT]\" - \"\U0001F1EF\U0001F1F5
    IEPL｜京日 [2.0][原生]\" - \"\U0001F1ED\U0001F1F0 IEPL｜京港 [2.0][原生]\" - \"\U0001F1FA\U0001F1F2
    IEPL｜京美 [2.0][NF][原生]\" - \"\U0001F1EC\U0001F1E7 IEPL｜京英 [2.0]\" - \"\U0001F1FC\U0001F1F8
    IEPL｜台湾媒体专线-1 [2.0][NF][Disney+]\" - \"\U0001F1F8\U0001F1EC IEPL｜新加坡媒体专线-1 [2.0][NF]\"
    - \"\U0001F1EF\U0001F1F5 IEPL｜日本媒体专线-1 [2.0][NF]\" - \"\U0001F1FC\U0001F1F8 IEPL｜沪台
    [2.0][原生]\" - \"\U0001F1F8\U0001F1EC IEPL｜沪新 [2.0][UDP][ChatGPT]\" - \"\U0001F1EF\U0001F1F5
    IEPL｜沪日 [2.0][原生]\" - \"\U0001F1ED\U0001F1F0 IEPL｜沪港 [2.0][原生]\" - \"\U0001F1FA\U0001F1F2
    IEPL｜沪美 [2.0][NF][原生]\" - \"\U0001F1EC\U0001F1E7 IEPL｜沪英 [2.0]\" - \"\U0001F1FC\U0001F1F8
    IEPL｜深台 [2.0][原生]\" - \"\U0001F1F8\U0001F1EC IEPL｜深新 [2.0][UDP][ChatGPT]\" - \"\U0001F1EF\U0001F1F5
    IEPL｜深日 [2.0][原生]\" - \"\U0001F1ED\U0001F1F0 IEPL｜深港 [2.0][原生]\" - \"\U0001F1FA\U0001F1F2
    IEPL｜深美 [2.0][NF][原生]\" - \"\U0001F1EC\U0001F1E7 IEPL｜深英 [2.0]\" - \"IPLC｜OpenAI专线-1
    [2.0][ChatGPT]\" - \"\U0001F1FC\U0001F1F8 IPLC｜冀台 [2.0][原生]\" - \"\U0001F1F8\U0001F1EC
    IPLC｜冀新 [2.0][UDP][ChatGPT]\" - \"\U0001F1EF\U0001F1F5 IPLC｜冀日 [2.0][原生]\" - \"\U0001F1ED\U0001F1F0
    IPLC｜冀港 [2.0][原生]\" - \"\U0001F1FA\U0001F1F2 IPLC｜冀美 [2.0][NF][原生]\" - \"\U0001F1FC\U0001F1F8
    IPLC｜台湾媒体专线-1 [2.0][NF][Disney+]\" - \"\U0001F1F8\U0001F1EC IPLC｜新加坡媒体专线-1 [2.0][NF]\"
    - \"\U0001F1EF\U0001F1F5 IPLC｜日本媒体专线-1 [2.0][NF]\" - \"\U0001F1FC\U0001F1F8 IPLC｜沪台
    [2.0][原生]\" - \"\U0001F1F8\U0001F1EC IPLC｜沪新 [2.0][UDP][ChatGPT]\" - \"\U0001F1EF\U0001F1F5
    IPLC｜沪日 [2.0][原生]\" - \"\U0001F1ED\U0001F1F0 IPLC｜沪港 [2.0][原生]\" - \"\U0001F1FA\U0001F1F2
    IPLC｜沪美 [2.0][NF][原生]\" - \"\U0001F1FC\U0001F1F8 IPLC｜浙台 [2.0][原生]\" - \"\U0001F1F8\U0001F1EC
    IPLC｜浙新 [2.0][UDP][ChatGPT]\" - \"\U0001F1EF\U0001F1F5 IPLC｜浙日 [2.0][原生]\" - \"\U0001F1ED\U0001F1F0
    IPLC｜浙港 [2.0][原生]\" - \"\U0001F1FA\U0001F1F2 IPLC｜浙美 [2.0][NF][原生]\" - \"\U0001F1FC\U0001F1F8
    IPLC｜深台 [2.0][原生]\" - \"\U0001F1F8\U0001F1EC IPLC｜深新 [2.0][UDP][ChatGPT]\" - \"\U0001F1EF\U0001F1F5
    IPLC｜深日 [2.0][原生]\" - \"\U0001F1ED\U0001F1F0 IPLC｜深港 [2.0][原生]\" - \"\U0001F1FA\U0001F1F2
    IPLC｜深美 [2.0][NF][原生]\" - \"\U0001F1FC\U0001F1F8 IPLC｜湘台 [2.0][原生]\" - \"\U0001F1F8\U0001F1EC
    IPLC｜湘新 [2.0][UDP][ChatGPT]\" - \"\U0001F1EF\U0001F1F5 IPLC｜湘日 [2.0][原生]\" - \"\U0001F1ED\U0001F1F0
    IPLC｜湘港 [2.0][原生]\" - \"\U0001F1FA\U0001F1F2 IPLC｜湘美 [2.0][NF]\" - \"\U0001F1FC\U0001F1F8
    IPLC｜珠台 [2.0][原生]\" - \"\U0001F1F8\U0001F1EC IPLC｜珠新 [2.0][UDP][ChatGPT]\" - \"\U0001F1EF\U0001F1F5
    IPLC｜珠日 [2.0][原生]\" - \"\U0001F1ED\U0001F1F0 IPLC｜珠港 [2.0][原生]\" - \"\U0001F1FA\U0001F1F2
    IPLC｜珠美 [2.0][NF][原生]\" - \"\U0001F1FC\U0001F1F8 IPLC｜苏台 [2.0][原生]\" - \"\U0001F1F8\U0001F1EC
    IPLC｜苏新 [2.0][UDP][ChatGPT]\" - \"\U0001F1EF\U0001F1F5 IPLC｜苏日 [2.0][原生]\" - \"\U0001F1ED\U0001F1F0
    IPLC｜苏港 [2.0][原生]\" - \"\U0001F1FA\U0001F1F2 IPLC｜苏美 [2.0][NF][原生]\" - \"\U0001F1FC\U0001F1F8
    IPLC｜闽台 [2.0][原生]\" - \"\U0001F1F8\U0001F1EC IPLC｜闽新 [2.0][UDP][ChatGPT]\" - \"\U0001F1EF\U0001F1F5
    IPLC｜闽日 [2.0][原生]\" - \"\U0001F1ED\U0001F1F0 IPLC｜闽港 [2.0][原生]\" - \"\U0001F1FA\U0001F1F2
    IPLC｜闽美 [2.0][原生][NF]\""
  use: "⚡️IPLC/IEPL"`

目前别的分组没有出现这个问题

<img width="577" alt="image" src="https://github.com/vernesong/OpenClash/assets/30380582/2e377161-b3ba-45e5-9ded-e538b3945489">

### Describe the Bug

会造成2023-12-24 21:54:41 13:54:41 ERR [Config] configuration file test failed error=ProxyGroup ⚡️IPLC/IEPL: 'proxies' is not a slice path=/etc/openclash/caomei.yaml

### OpenClash Log

2023-12-24 21:54:41 13:54:41 ERR [Config] configuration file test failed error=ProxyGroup ⚡️IPLC/IEPL: 'proxies' is not a slice path=/etc/openclash/caomei.yaml

### Expected Behavior

应该是和其他的一样正常的出现

**Comment by vernesong** [comment]
没法复现，请贴详细步骤

**Comment by Xiaohantx** [comment]
> 无法恢复，请贴详细步骤

有可提供发送的邮箱嘛，我把配置文件格式发过去，主要就是在手动添加组的时候，脚本会重新生成一遍，所以在重新生成的时候这个转换过程出错，因为包含节点等重要信息无法在这里发出整个配置文件，

**Comment by vernesong** [comment]
tg同名找我

**Comment by MsZhu-trans** [comment]
我页遇到了 是怎么解决的呀
