### ISSUE TITLE
[Feature] 是否可以在 DNS 高级设置中支持所有域名都返回真实 IP

### ISSUE THREAD

**Issue by alaneuler** [vernesong/OpenClash#3705]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

目前 OpenClash 仅支持一行一个域名，这些域名使用指定 DNS server 查询的时候会返回真实 IP。想要在指定 DNS server 的情况下，所有域名都返回真实 IP

### Describe the Solution

1. 是不是可以使用正则？或者通配符？
2. 添加一个开关，这个开关打开的时候，直接返回真实 IP；这个开关默认关闭

### Additional Context

这是目前的配置截图：
![](https://github.com/vernesong/OpenClash/raw/master/img/set2.png)

**Comment by LemonPAKA** [comment]
列表里写+.*试一下咯

**Comment by alaneuler** [comment]
> 列表里写+.*试一下咯

我试了 `*` 是不行的，正则回去再试下。。。

**Comment by LemonPAKA** [comment]
> > 列表里写+.*试一下咯
> 
> 我试了 `*` 是不行的，正则回去再试下。。。

我的意思是写    `+.*`

**Comment by yellowsavant** [comment]
dns方案用redir-host就行了，fake-ip本来就是回复假ip

**Comment by SqiChiu** [comment]
有没有可能，你说的这个功能叫redir-host模式

**Comment by alaneuler** [comment]
> `+.*`

@LemonPAKA  试了下这个也是不行的

**Comment by LemonPAKA** [comment]
> > `+.*`
> 
> @LemonPAKA 试了下这个也是不行的

那你直接开redir-host得了，反正非meta内核的redir-host就是fake-ip模拟的，通过返回全部真实IP

**Comment by alaneuler** [comment]
> > > `+.*`
> > 
> > 
> > @LemonPAKA 试了下这个也是不行的
> 
> 那你直接开redir-host得了，反正非meta内核的redir-host就是fake-ip模拟的，通过返回全部真实IP

<img width="446" alt="image" src="https://github.com/vernesong/OpenClash/assets/8054939/e805c18d-fce7-4971-80c9-14f573c633fc">
我的 clash 版本是 v0.45.157-beta，貌似都没有 redir-host 的选项了？

**Comment by LemonPAKA** [comment]
> > > > `+.*`
> > > 
> > > 
> > > @LemonPAKA 试了下这个也是不行的
> > 
> > 
> > 那你直接开redir-host得了，反正非meta内核的redir-host就是fake-ip模拟的，通过返回全部真实IP
> 
> <img alt="image" width="446" src="https://private-user-images.githubusercontent.com/8054939/293463650-e805c18d-fce7-4971-80c9-14f573c633fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5NDQ2NzAsIm5iZiI6MTcwMzk0NDM3MCwicGF0aCI6Ii84MDU0OTM5LzI5MzQ2MzY1MC1lODA1YzE4ZC1mY2U3LTQ5NzEtODBjOS0xNGY1NzNjNjMzZmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDIzMTIzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMzBUMTM1MjUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTY1ZWVhMzc5ZGU5ZjQzMjZhODQ0MmFiYjk1MTc2OWIwMDU3MzNiYWVhNGYxMTE5YjM5M2I0ZGQyMDBlZGNkZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.9VCon8pfU9sYR5mwjmxR8IoVUg1LPufWQChuffFPW5E"> 我的 clash 版本是 v0.45.157-beta，貌似都没有 redir-host 的选项了？

界面正底下有个切换redir-host模式的大按钮

**Comment by alaneuler** [comment]
> > > > > `+.*`
> > > > 
> > > > 
> > > > @LemonPAKA 试了下这个也是不行的
> > > 
> > > 
> > > 那你直接开redir-host得了，反正非meta内核的redir-host就是fake-ip模拟的，通过返回全部真实IP
> > 
> > 
> > <img alt="image" width="446" src="https://private-user-images.githubusercontent.com/8054939/293463650-e805c18d-fce7-4971-80c9-14f573c633fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5NDQ2NzAsIm5iZiI6MTcwMzk0NDM3MCwicGF0aCI6Ii84MDU0OTM5LzI5MzQ2MzY1MC1lODA1YzE4ZC1mY2U3LTQ5NzEtODBjOS0xNGY1NzNjNjMzZmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDIzMTIzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMzBUMTM1MjUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTY1ZWVhMzc5ZGU5ZjQzMjZhODQ0MmFiYjk1MTc2OWIwMDU3MzNiYWVhNGYxMTE5YjM5M2I0ZGQyMDBlZGNkZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.9VCon8pfU9sYR5mwjmxR8IoVUg1LPufWQChuffFPW5E"> 我的 clash 版本是 v0.45.157-beta，貌似都没有 redir-host 的选项了？
> 
> 界面正底下有个切换redir-host模式的大按钮

不好意思添乱了，看到了。。

**Comment by alaneuler** [comment]
@SqiChiu @yellowsavant 不是 redir-host 哈，我是想要用 fake-ip 模式，但是有时候排查网络问题，需要看一下 DNS 是否能被正确解析。

在家里我把 OpenClash 当旁路由使用，公司里面用的 Surge。Surge 在指定 nslookup 的 DNS server 的情况下是会返回真实的 IP 的。

**Comment by LemonPAKA** [comment]
> @SqiChiu @yellowsavant 不是 redir-host 哈，我是想要用 fake-ip 模式，但是有时候排查网络问题，需要看一下 DNS 是否能被正确解析。
> 
> 在家里我把 OpenClash 当旁路由使用，公司里面用的 Surge。Surge 在指定 nslookup 的 DNS server 的情况下是会返回真实的 IP 的（Surge 是 fake-ip 模式）。

![image](https://github.com/vernesong/OpenClash/assets/17202894/3f4e57a9-644a-40e6-920c-44d1e072694b)
metacubexd面板的这个功能你可以试一下，不过我个人喜欢用redir-host的，不知道fake-ip下能不能用

**Comment by yellowsavant** [comment]
> @SqiChiu @yellowsavant 不是 redir-host 哈，我是想要用 fake-ip 模式，但是有时候排查网络问题，需要看一下 DNS 是否能被正确解析。
> 
> 在家里我把 OpenClash 当旁路由使用，公司里面用的 Surge。Surge 在指定 nslookup 的 DNS server 的情况下是会返回真实的 IP 的（Surge 是 fake-ip 模式）。

fake-ip模式下解析真实dns ip没有意义吧，因为真正的dns解析是交给远程网点去做的，再说了，国内dns解析国外网站或多或少都有dns污染的问题，而国外的dns提供商又基本让GFW给阻断，在fake-ip模式下看国外网站dns解析没多大意义
如果你真想在fake-ip下让解析返回真实ip，那就直接用fake-ip-fliter就好啦

**Comment by alaneuler** [comment]
> > @SqiChiu @yellowsavant 不是 redir-host 哈，我是想要用 fake-ip 模式，但是有时候排查网络问题，需要看一下 DNS 是否能被正确解析。
> 
> > 
> 
> > 在家里我把 OpenClash 当旁路由使用，公司里面用的 Surge。Surge 在指定 nslookup 的 DNS server 的情况下是会返回真实的 IP 的（Surge 是 fake-ip 模式）。
> 
> 
> 
> fake-ip模式下解析真实dns ip没有意义吧，因为真正的dns解析是交给远程网点去做的，再说了，国内dns解析国外网站或多或少都有dns污染的问题，而国外的dns提供商又基本让GFW给阻断，在fake-ip模式下看国外网站dns解析没多大意义
> 
> 如果你真想在fake-ip下让解析返回真实ip，那就直接用fake-ip-fliter就好啦

我的理解不知道是不是和你的有偏差，如果是正常国内网站的话，应该是不用交给远程网点去做解析的吧？（因为CDN的存在，还是得用国内的解析获得最佳访问速度）。

我其实不看国外网站的dns解析，我只是想看看国内正常网站的解析是否正常，但又不想仅限于配置固定的那几个。。。

我想用fake-ip，只是在排查网络问题的时候想看真实ip。clash劫持了所有dns请求，全都返回假的ip，头疼这一点

**Comment by alaneuler** [comment]
> > @SqiChiu @yellowsavant 不是 redir-host 哈，我是想要用 fake-ip 模式，但是有时候排查网络问题，需要看一下 DNS 是否能被正确解析。
> 
> > 
> 
> > 在家里我把 OpenClash 当旁路由使用，公司里面用的 Surge。Surge 在指定 nslookup 的 DNS server 的情况下是会返回真实的 IP 的（Surge 是 fake-ip 模式）。
> 
> 
> 
> ![image](https://github.com/vernesong/OpenClash/assets/17202894/3f4e57a9-644a-40e6-920c-44d1e072694b)
> 
> metacubexd面板的这个功能你可以试一下，不过我个人喜欢用redir-host的，不知道fake-ip下能不能用

这个在fake-ip下也能用的，感谢大佬。

另外问一下，我看网上都是说redir速度差一些，你在用的过程中碰到的问题多吗？

**Comment by yellowsavant** [comment]
> > > @SqiChiu @yellowsavant 不是 redir-host 哈，我是想要用 fake-ip 模式，但是有时候排查网络问题，需要看一下 DNS 是否能被正确解析。
> > 
> > 
> > > 
> > 
> > 
> > > 在家里我把 OpenClash 当旁路由使用，公司里面用的 Surge。Surge 在指定 nslookup 的 DNS server 的情况下是会返回真实的 IP 的（Surge 是 fake-ip 模式）。
> > 
> > 
> > fake-ip模式下解析真实dns ip没有意义吧，因为真正的dns解析是交给远程网点去做的，再说了，国内dns解析国外网站或多或少都有dns污染的问题，而国外的dns提供商又基本让GFW给阻断，在fake-ip模式下看国外网站dns解析没多大意义
> > 如果你真想在fake-ip下让解析返回真实ip，那就直接用fake-ip-fliter就好啦
> 
> 我的理解不知道是不是和你的有偏差，如果是正常国内网站的话，应该是不用交给远程网点去做解析的吧？（因为CDN的存在，还是得用国内的解析获得最佳访问速度）。
> 
> 我其实不看国外网站的dns解析，我只是想看看国内正常网站的解析是否正常，但又不想仅限于配置固定的那几个。。。
> 
> 我想用fake-ip，只是在排查网络问题的时候想看真实ip（看了下fake-ip-filter应该不符合我的需求）。clash劫持了所有dns请求，全都返回假的ip，头疼这一点

1. clash在任何dns方案下（fake,redir）都是按照分流规则来决定流量是走远程或是走国内
2. fake-ip-filter列表其实是一种exception，让clash返回真实的dns ip
3. 基本上有geoip的存在，理论上应该都会返回真ip，但是一些机场的国内规则有时候写的不好，或是兜底的那条分流规则直接 
    定义送到远程服务器，都会返回fake-ip
4. 为什么要使用fake-ip，是因为有dns泄露问题，fake比redir快一点主要是因为client的dns查询理论上会少一次，而且clash返回 
   的dns回应是在局域网发生的，所以比redir模式下的dns反应时间快多了
5. 如果你真的需要常常解析国内域名ip，那还是建议用redir模式吧，但是dns最好使用doh或dot而非udp，尽量不要使用isp提供
    的，虽然这样算是掩耳盗铃，我个人认为公用的dns会比isp直接给的还要安全点，你不知道isp部署了哪些反人权设备
6. 我现在大部分时间都在用fake模式，redir这个模式clash貌似在1年前就弃用了，因为他的问题主要集中在dns泄露
    其实随便用用也没太大问题，速度其实也还行
7. fake模式有个问题，如果半道你的clash崩溃了，或是路由重启，由于有dns缓存的存在，会导致没有及时清理缓存的设备在一 
    段时间无法上网，如果家里设备较多，而你又常常搞路由重启，那将会收到很多投诉的.....
8.  如果你只是想得到国内dns域名解析的结果，那就使用一些whois网站查询就行了，例如站长之家这类的
9. 我不是大佬也不是大神，大家只是讨论讨论罢了

**Comment by alaneuler** [comment]
看了下 clash core 和 openclash 的源码，我发现 **Fake-IP 域名黑名单**和 **fake-ip-filter **的作用是一样的，在 fake-ip 模式下，返回真实 ip：
- fake-ip-filter 语法是在 clash core 的 trie 树中定义的，通配符写法形如 `+.com`：所有 `.com` 域名都返回真实 ip
- Fake-IP 黑名单用的是 dnsmasq 的配置语法（因为依赖了 dnsmasq），和 fake-ip-filter 相同功能的话需要配置成 `.com`（我试过是 work 的）

但我的原始想法是，**在指定 dns server 的情况下，不要返回 fake ip**，例如：
```
nslookup baidu.com 114.114.114.114
```
但是由于 openclash 作为网关劫持了所有的 DNS 请求，上述的请求也会返回 fake-ip。
所以我理解不要让 openclash 劫持所有 DNS 请求就可以了？

**Comment by deuteros-gex** [comment]
最简单的做法，客户端放弃nslookup，用dog发doh或者dot请求，这样就不会被劫持了

愿意研究netfilter总能实现某些更精细的劫持诉求，比如可以让指向114的dns不被劫持（但这样会造成另外的误杀），写进openclash的自定义脚本中即可。
但我觉得这属于应该让用户自己造的轮子，做进openclash徒增理解难度了。

**Comment by yellowsavant** [comment]
> 看了下 clash core 和 openclash 的源码，我发现 **Fake-IP 域名黑名单**和 **fake-ip-filter** 的作用是一样的，在 fake-ip 模式下，返回真实 ip：
> 
> * fake-ip-filter 语法是在 clash core 的 trie 树中定义的，通配符写法形如 `+.com`：所有 `.com` 域名都返回真实 ip
> * Fake-IP 黑名单用的是 dnsmasq 的配置语法（因为依赖了 dnsmasq），和 fake-ip-filter 相同功能的话需要配置成 `.com`（我试过是 work 的）
> 
> 我的原始需求是，**在指定 dns server 的情况下，不要返回 fake ip**，但不指定 DNS server（也就是 openclash 的 dnsmasq 作为 dns server）还是返回 fake ip，所以上面两个配置不符合我的需求），例子：
> 
> ```shell
> # 以下请求返回真实 IP
> nslookup baidu.com 114.114.114.114
> 
> # 以下请求返回 fake ip
> nslookup baidu.com
> ```
> 
> 但是由于 openclash 作为网关劫持了所有的 DNS 请求，上述第一个请求也会返回 fake-ip。 所以我理解不要让 openclash 劫持所有 DNS 请求就可以了？

openclash在iptables（fw3）或nft（fw4）层面，会把所有udp port 53都劫持到clash core的dns监听端口（默认是8853）
如果你会操作iptables 或者nft，你的问题就能解决了
你可以在 /etc/init.d/openclash 这个里面添加相关的命令行，前提是你懂这个玩意儿

**Comment by alaneuler** [comment]
@yellowsavant 嗯嗯，我用的最新版的 clash 用的是 nft 做的流量劫持，不过 udp port 53 应该都是被劫持到 dnsmasq 53，然后 dnsmasq 上游设置的是 clas core 的 dns，所以 openclash 的 Fake-IP 黑名单才能起作用。
