### ISSUE TITLE
[Feature] 适当精简

### ISSUE THREAD

**Issue by bfcs** [vernesong/OpenClash#3708]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

Hi, @vernesong 
感谢作者的辛勤付出，使用这个很长时间了，一直都是更新，但是发现越来越臃肿了，一直在collecting data，启动和关闭也慢了很多，我两个路由器都是这样，请问能否作一些适当的精简呢，比如控制台就已经有三个了

### Describe the Solution

适当删减，比如删除多余的两个控制台

**Comment by xiaozhuai** [comment]
> 比如删除多余的两个控制台

控制台是直接由clash内核对外提供静态http服务的，启动时只会从配置中读一个路径。所以这并不能加快启动速度。

**Comment by caliban511** [comment]
可以试试精简一下自己的规则，，，一千行的配置肯定比一万行的配置加载时和跑起来要快，，，

**Comment by Manweill** [comment]
我也觉得当前路openclash 上的配置内容和选项过多，并且有些混乱。对比起 cfw，clash verge 等都复杂庞大很多。

**Comment by ObcbO** [comment]
> 我也觉得当前路openclash 上的配置内容和选项过多，并且有些混乱。对比起 cfw，clash verge 等都复杂庞大很多。

是openclash的覆写功能实在是太全面了 一般用不到这么多功能 所以我提出了 #3769
