### ISSUE TITLE
使用openclash代理后curl报错35

### ISSUE THREAD

**Issue by jerryliang122** [vernesong/OpenClash#371]
使用REDIR-HOST模式（非TUN）无论是否代理都会弹出curl 35 报错
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to kd.jerryliang.top:443 
包括WGET 但是chrome浏览器使用正常。wget报错Unable to establish SSL connection.

**Comment by vernesong** [comment]
检查一下环境，客户端是不是设置了其他代理

**Comment by limimiking** [comment]
我在redir-host模式也遇到了类似问题，curl(35)而且网页打不开
比如 curl https://www.quora.com 就会有 curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to www.quora.com:443
但是如果我用openclash的socks端口7891或者http端口7890作为代理就可以打开网页，但是这样就必须用socks客户端或者改系统代理设置，没法实现透明代理了
我肯定没有设置其他代理，只有部分网站是这种情况，比如quora和偶尔的wikipedia
不知道跟dns有没有关系，我在openclash里已经设了custom dns，而且ipv6也都关掉了
另外我在linux bashrc里设置http_proxy后curl仍然35，也是只有部分网站这样

**Comment by abumn** [comment]
我也是这样

**Comment by Declarcall** [comment]
我也遇到类似问题，换个代理节点就好了。应该是代理节点出了问题。如果openclash可以自动排除ssl报错的节点就好了
