### ISSUE TITLE
[Bug] 无法访问自建节点

### ISSUE THREAD

**Issue by yqdhm** [vernesong/OpenClash#3710]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.162-beta

### Bug on Environment

Official OpenWrt, Lean

### Bug on Platform

Linux-arm64

### To Reproduce

使用带有自建节点A的文件时，无法访问自建节点A上的网站及ssh连接，chrome提示ERR_CONNECTION_REFUSED，FinalShell提示java.net.ConnectException: Connection refused: connect，在yacd里也看不到连接

### Describe the Bug

使用带有自建节点A的文件时，无法访问自建节点A上的网站及ssh连接，chrome提示ERR_CONNECTION_REFUSED，FinalShell提示java.net.ConnectException: Connection refused: connect，在yacd里也看不到连接，使用不带自建节点A的配置时访问正常，yacd里能看到正常连接
cfw使用带有自建节点A的文件时访问正常

### OpenClash Log

[log.txt](https://github.com/vernesong/OpenClash/files/13818103/default.txt)

### Expected Behavior

能正常访问自建节点A

### Screenshots

![image](https://github.com/vernesong/OpenClash/assets/94184883/d8c61082-8d84-406b-bde7-717f0b06f102)
![image](https://github.com/vernesong/OpenClash/assets/94184883/a888107c-469d-4f59-a1df-6b30f00ff406)

**Comment by vernesong** [comment]
新版本会排除配置文件里的节点ip，让他们不经过内核直连

**Comment by yqdhm** [comment]
> 新版本会排除配置文件里的节点ip，让他们不经过内核直连

现在是无法直连，且电脑上再开cfw就无法上外网了
这个功能能否提供一个开关？

**Comment by vernesong** [comment]
不能直连还怎么当节点

**Comment by yqdhm** [comment]
> 不能直连还怎么当节点

误解了，我的意思是开了openclash就不能连接节点，关了之后能正常用

**Comment by vernesong** [comment]
节点是IP还是域名

**Comment by yqdhm** [comment]
ipv4和域名都不行

**Comment by yqdhm** [comment]
v0.45.164-beta
把dns指向openclash后可以通过域名访问网站，基于ip的ssh和网站仍然无法访问
