### ISSUE TITLE
[Feature] 希望同步更新第三方游戏规则

### ISSUE THREAD

**Issue by izumiChan16** [vernesong/OpenClash#3711]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经**使用最新 Dev 版本**查看过，并不包含该功能特性或者还不完善
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 应包含的特性
- [X] Contributors 我有能力协助 OpenClash 开发或完善此功能特性
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### Describe the Feature

目前正在使用规则附加中的游戏规则附加功能，运行非常稳定，使用体验很好。

但仍然存在自带游戏规则库与上游源不同步的功能，希望可以添加一个同步上游规则，修改本地`/usr/share/openclash/res/game_rules.list`文件的功能。

原因：
在`openclash/game-rules-file-manage`路径下管理的文件，可以新增文件，但是无法在`openclash/rule-providers-settings 游戏规则附加`中进行选择引用，也许是**BUG**。另外，也无法手动修改配置文件来达到新增本地文件链接引用的效果，因为在配置修改页面种，运行后生成的配置是无法修改的。
所以，本地创建的规则暂时无法使用。只能通过修改下载的rules文件达到要求，本质上并没有解决问题。

**Comment by Zenhang** [comment]
请问下你加速用的是哪个规则，是SSTAP那些rules吗，我看那里面有些规则好几年都没更新了，还可以正常使用吗
