### ISSUE TITLE
[Feature] 增加配置文件中节点经过内核，通过代理链接的选项

### ISSUE THREAD

**Issue by Plus-xu** [vernesong/OpenClash#3714]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经**使用最新 Dev 版本**查看过，并不包含该功能特性或者还不完善
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 应包含的特性
- [ ] Contributors 我有能力协助 OpenClash 开发或完善此功能特性
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### Describe the Feature

旧版本配置文件里面的节点可以通过当前使用中的代理链接，而新版本会排除配置文件里的节点ip，让他们不经过内核直连，这样会导致与大陆线路延迟高或丢包的服务器无法稳定链接ssh和进行网站维护（比如连接宝塔或服务器上的数据库），希望可以增加允许配置文件中的节点经过内核代理链接的选项

**Comment by sangyishuje1123** [comment]
？？？？？

通俗说就是是你想让一个不走代理的ip走代理？

**Comment by sangyishuje1123** [comment]
不好意思，没看最近commit记录。

**Comment by Plus-xu** [comment]
> ？？？？？
> 
> 通俗说就是是你想让一个不走代理的ip走代理？
是配置节点中当前未使用的节点可以选择走代理链接，比如我配置中有10个服务器代理节点，晚高峰或者因为服务器临时线路调整导致其中某个节点延迟和丢包异常，无法稳定直连这些节点ssh或进行服务器维护（比如宝塔，数据库，上传下载数据）。希望可以像旧版本一样，可以选择通过代理服务器连接这些暂时异常的节点。

**Comment by sangyishuje1123** [comment]
https://github.com/vernesong/OpenClash/issues/3710#issuecomment-1875299437

**Comment by HdeGff** [comment]
我建议你改一下吧

如你所说，`新版本会排除配置文件里的节点ip`，这个才是关键点

要求改成`可选择性排除配置文件里的节点ip`，才是你的目的

**Comment by gq20110204** [comment]
+1 我有个别服务器在国内直连ssh访问非常糟糕 平时基本需要通过代理才能顺畅访问
想补充一点
可配置让节点ip的22 3389这种端口继续走代理 其他的直连 或者10000以上的高位端口直连  或许更加合理
这样可以让直连好的ssh直连 直连不好的ssh手动配置走代理 决定权交给用户

**Comment by gq20110204** [comment]
> > +1 我有个别国内服务器在直连ssh访问非常糟糕 平时基本需要通过代理才能访问以上想补充点可配置让节点ip的22 3389这种端口继续走代理其他的直连或者10000以上的高位端口直连更可能合理的结果可以让直连好的ssh直连不好的ssh手动配置走代理决定权用户解锁
> 
> 你可能误会了一点，这个直连是针对yaml配置文件中proxy字段中的纯ip。rule 部分不出行。

嗯嗯 前面没说清楚 我想说的是我跟楼主的情况和需求类似 一台服务器又搭建了节点又需要ssh的情况 ssh会被强制直连
而且这种直连似乎是内核级别的 我尝试在SRC-IP-CIDR中添加了该ip的强制代理 并不奏效
