### ISSUE TITLE
[Bug] Vless 更新订阅 proxy 中 servername 字段缺失或不正确

### ISSUE THREAD

**Issue by yongman** [vernesong/OpenClash#3715]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [ ] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

v0.45.164-beta

### Bug on Environment

Lean

### OpenWrt Version

OpenWrt R22.10.10

### Bug on Platform

Linux-amd64(x86-64)

### Describe the Bug

VLESS 节点通过订阅地址更新获取到的 proxy 配置中 servername 缺失或者和原来订阅信息中的 servername 不一致。

正常的 proxy 配置：

```
  - {name: xxx1, server: 108.181.xx.xx, port: 443, client-fingerprint: chrome, type: vless, uuid: f6c89xxx-63xx-426b-9faa-5fba7344x7xx, tls: true, tfo: false, servername: 34-21-xx-xx.nhost.00cdn.com, flow: xtls-rprx-vision, skip-cert-verify: true, udp: true}
  - {name: xxx2, server: jp1.xxx.com, port: 443, client-fingerprint: chrome, type: vless, uuid: f6c89xxx-63xx-426b-9faa-5fba7344x7xx, tls: true, tfo: false, servername: 34-21-xx-xx.nhost.00cdn.com, flow: xtls-rprx-vision, skip-cert-verify: true, udp: true}
```

通过 OpenClash 获取到的 proxy 错误配置：

```
  - {name: xxx1, server: 108.181.xx.xx, port: 443, client-fingerprint: chrome, type: vless, uuid: f6c89xxx-63xx-426b-9faa-5fba7344x7xx, tls: true, tfo: false, flow: xtls-rprx-vision, skip-cert-verify: true, udp: true}
  - {name: xxx2, server: jp1.xxx.com, port: 443, client-fingerprint: chrome, type: vless, uuid:f6c89xxx-63xx-426b-9faa-5fba7344x7xx, tls: true, tfo: false, servername:  jp1.xxx.com, flow: xtls-rprx-vision, skip-cert-verify: true, udp: true}
```

其中，
第一条，proxy 中的 server 是 IP，缺少 servername 字段。
第二条，proxy 中的 server 是域名，生成的 servername 和 server 是同一个域名，源配置中 servername 为 `34-21-xx-xx.nhost.00cdn.com`

### To Reproduce

更新订阅，/etc/openclash/config/xxx.yml 配置不正确。

### OpenClash Log

```log
无
```

### Expected Behavior

获取到的订阅和源订阅内容一致。

**Comment by sangyishuje1123** [comment]
这应该不是启动配置吧？
所以会不会是UA问题？

**Comment by yongman** [comment]
这个配置`/etc/openclash/config/xx.yaml`应该是从上游更新下来还未经过转换的配置文件，经过转换的配置文件放在`/etc/openclash/xx.yaml`。订阅的上游是自建的 subconverter，UA 指定的 clash.meta。

**Comment by yongman** [comment]
`/etc/openclash/config/xx.yaml` 文件 servername 字段不对，转换出来的启动配置也是不对的。

**Comment by sangyishuje1123** [comment]
对，所以现在有点迷，只下载订阅的话oc应该还没接手修改啊。
等V大吧 XD

**Comment by yongman** [comment]
辛苦，还没有继续深究，暂时用脚本手动更新订阅然后重启 oc，能正常 work。
