### ISSUE TITLE
[Feature] 在「一键生成（服务器&策略组管理）」中允许追加策略组和服务器结点

### ISSUE THREAD

**Issue by zzc-tongji** [vernesong/OpenClash#3722]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经**使用最新 Dev 版本**查看过，并不包含该功能特性或者还不完善
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 应包含的特性
- [ ] Contributors 我有能力协助 OpenClash 开发或完善此功能特性
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### Describe the Feature

在「一键生成（服务器&策略组管理）」中编辑策略组和服务器节点，并选定配置文件。配置文件中的 proxy-groups / proxies 会被直接**强制覆盖**。

希望能提供一个**追加**的选项，即**把填入策略组和服务器节点追加在配置文件对应部分的后面**。

### Describe Alternatives

**OpenClash 只能同时运行一个 Clash 配置文件**，我一般会用机场提供的（在「配置订阅」中配置 URL 下载并启用自动更新）。

我的需求**在下载后的配置文件中自动追加自建节点和规则**，原因是：

- 某些网站（比如 ChatGPT 和 TikTok）对出口IP的限制非常严格，机场 IP 无法满足要求。
- 机场 IP 同时被大量用户使用，极易引发网站风控（比如 PayPal）。

我尝试用「一键生成（服务器&策略组管理）」来加入自建结点，结果就是机场配置文件中的 proxy-groups / proxies 被覆盖掉了，rules 找不到对应的 proxies，配置文件损坏，插件无法启动。

所以我提出了这个 issue 。（也许是我的使用方式不对？欢迎大家给出建议。）

**Comment by vernesong** [comment]
先读取配置再添加节点，机场需要更新就勾选保留配置
