### ISSUE TITLE
[Bug]  alpha-g51803f1 版本内核崩溃

### ISSUE THREAD

**Issue by lifetyper** [vernesong/OpenClash#3724]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [ ] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

v0.45.164-beta

### Bug on Environment

Lean

### OpenWrt Version

OpenWrt R23.11.11 

### Bug on Platform

Linux-amd64(x86-64)

### Describe the Bug

多个硬件平台下(x86,rk3358,rk3326)更新到这个版本后都出现了内核崩溃反复重启的情况

### To Reproduce

更新到alpha-g51803f1版本即可复现

### OpenClash Log

```log
内核log错误过大,贴到这里了:
https://pastebin.com/kGfFBEL8
```

### Expected Behavior

更新一下内核避免崩溃

**Comment by lbsnake** [comment]
同版本同内核崩溃，已替换回alpha-g425bc69版本使用。

**Comment by superminian** [comment]
升级到最新alpha-g51803f1 meta没有崩溃
x86、固件R23.11.11、6.1.66linux内核、0.45.164openclash

**Comment by gdanmac** [comment]
alpha-g0c384b1	

alpha-g8c3557e	

alpha-23e3f12	

alpha-g3a9fc39
