### ISSUE TITLE
[Bug] 官方版系统安装后找不到入口（固件版本23.05.1）

### ISSUE THREAD

**Issue by luiguangguan** [vernesong/OpenClash#3726]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [ ] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

0.45.157-beta

### Bug on Environment

Official OpenWrt

### OpenWrt Version

23.05.1

### Bug on Platform

Linux-amd64(x86-64)

### Describe the Bug

![image](https://github.com/vernesong/OpenClash/assets/20753694/3ac9bfea-ef8d-40dd-81e1-745198b89600)
我直接安装ipk文件后，没有提示任何失败，但是web界面中找不到任何关于的openclash的菜单选项

### To Reproduce

直接安装ipk，没有提示任何失败

### OpenClash Log

```log
无法运行
```

### OpenClash Config

```shell
无
```

### Expected Behavior

可以在界面找到openclash的功能入口（选项）
并且能正常配置和使用各个功能

**Comment by sangyishuje1123** [comment]
看一下luci compat装了没

**Comment by luiguangguan** [comment]
好的 我装了，看到了，但是我还有个问题
![image](https://github.com/vernesong/OpenClash/assets/20753694/8d9ed88d-5aca-4820-bb0f-81a204e39626)
好像有些功能配置没有了，
不是很了解什么原因

**Comment by luiguangguan** [comment]
我之前用iStore出现过一段时间就不能代理，国内链接没有问题。切换一下tun模式或者重启clash又可以用一阵

**Comment by sangyishuje1123** [comment]
？？？你装错了吧，你安装的这个应该这是luci clash，你现在发帖的这个地方是luci openclash，前者几年前就不维护了

你第二个问题，这边也有人发过类似的issue，但没人找到关键点，所以目前没解决。
