### ISSUE TITLE
[Bug] git clone拉取OpenClash非常非常慢

### ISSUE THREAD

**Issue by fxxccp** [vernesong/OpenClash#3736]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [ ] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

0.45.157

### Bug on Environment

Lean

### OpenWrt Version

5.15.147

### Bug on Platform

Linux-amd64(x86-64)

### Describe the Bug

GitHub于 2024 年1月8日停止支持版本控制系统 Subversion，无法再用svn co单独拉取luci-app-openclash文件夹，不得以用git clone拉取整个OpenClash仓库，但非常慢，无论是本地编译拉取还是Github Actions编译拉取都是如此。整个OpenClash仓库不足8M，不清楚为什么拉取得这么慢，希望vernesong大佬能排查并优化一下。谢谢！

### To Reproduce

本地编译拉取或Github Actions编译拉取整个OpenClash仓库都异常慢

### OpenClash Log

```log
no log
```

### OpenClash Config

```shell
无
```

### Expected Behavior

排查并优化问题所在

### Additional Context

无

**Comment by fxxccp** [comment]
> 你确定是慢？而不是大？ ![1](https://private-user-images.githubusercontent.com/152784766/298921216-6bf80ec7-df3f-4781-a5b0-a41ebed83d90.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwOTQ3ODcsIm5iZiI6MTcwNjA5NDQ4NywicGF0aCI6Ii8xNTI3ODQ3NjYvMjk4OTIxMjE2LTZiZjgwZWM3LWRmM2YtNDc4MS1hNWIwLWE0MWViZWQ4M2Q5MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNFQxMTA4MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NjgxMjFiM2FiZjg2Yzc4MDZjN2JjZTdhMTM2M2U2Yzg2OWMzNzNiNWMwZGVjYjZmNTJiOTlhM2QxOGVhODhlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pxOmVS4OGZrg75EO7L5hO2DMtveMhHymf3VZOSYjwBw) `git clone --filter=blob:none https://github.com/vernesong/OpenClash`

感谢指点迷津

**Comment by fxxccp** [comment]
> 指点迷津不敢当，“受害者”交流罢了，第一次clone时打了个电话，回过神发现还没下完，赶紧打断，一查发现下了近8G XD 现在基本clone都会加depth或者filter了

再请教下大佬，如果我只需要luci-app-openclash这一个文件夹，其它的不需要，git命令应该怎么写？

**Comment by v8040** [comment]
> > 指点迷津不敢当，“受害者”交流罢了，第一次clone时打了个电话，回过神发现还没下完，赶紧打断，一查发现下了近8G XD 现在基本clone都会加depth或者filter了
> 
> 再请教下大佬，如果我只需要luci-app-openclash这一个文件夹，其它的不需要，git命令应该怎么写？

我是这样用git clone --sparse 供参考:
git clone -b master --depth=1 --filter=blob:none --sparse https://github.com/vernesong/OpenClash.git package/luci-app-openclash
git -C package/luci-app-openclash sparse-checkout set luci-app-openclash

**Comment by zheshifandian** [comment]
作者写的readme你是一点也不看

**Comment by v8040** [comment]
> > 只需要luci-app-openclash这一个文件夹，其它的不需要
> 
> 真不是大佬。。。 目前来讲，是无法只用几行git命令就达到只有luci-app-openclash这一个文件夹的。
> 
> > 我是这样用git clone --sparse 供参考:
> > ```
> > git clone -b master --depth=1 --filter=blob:none --sparse https://github.com/vernesong/OpenClash.git package/luci-app-openclash
> > git -C package/luci-app-openclash sparse-checkout set luci-app-openclash
> > ```
> 
> 不好意思，说一下 该命令的目录会变成 package/luci-app-openclash/luci-app-openclash 严格来讲这还是两层文件夹，作者的readme也一样
> 
> 因为没这方面需求，所以没研究过
> 
> 如果本地看，直接鼠标点就行。 对我来说极偶尔的一行`cd luci-app-openclash`或者`右击luci-app-openclash` `在终端中打开`也没有繁琐
> 
> 如果编译openwrt 直接写进feed里`echo 'src-git OpenClash https://github.com/vernesong/OpenClash >> feeds.conf.default`也能够正常编译
> 
> 了解的少，所以是真的没有研究过这方面

是我没写清楚,就算是2层目录也不影响编译,可能强迫症吧,想要用git命令就达到只有`luci-app-openclash`这一个文件夹的可以这样(应该和之前用的`svn export`效果差不多了):
```
git_sparse_clone() {
    branch="$1" repourl="$2" repodir="$3"
    git clone -b $branch --depth=1 --filter=blob:none --sparse $repourl package/cache
    git -C package/cache sparse-checkout set $repodir
    mv -f package/cache/$repodir package
    rm -rf package/cache
}
git_sparse_clone master https://github.com/vernesong/OpenClash.git luci-app-openclash
```
