### ISSUE TITLE
OpenClash正常运行，但活动连接始终为0

### ISSUE THREAD

**Issue by okletgo64** [vernesong/OpenClash#3747]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [ ] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [X] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

v0.45.141-beta

### Bug on Environment

Immortalwrt

### OpenWrt Version

ImmortalWrt 21.02-SNAPSHOT r20386-4a1f0eb31b / LuCI openwrt-21.02 branch git-23.098.38725-847bd6b

### Bug on Platform

Linux-arm64

### Describe the Bug

Clash for Windows是正常的，OpenClash配置也正常，但活动连接:  0 ，并且警告：设置仅允许内网功能失败，无法获取 IPv4 的 WAN 接口名称，请确保防火墙设置中 IPv4 WAN 区域的名称为 wan，如设备无 WAN 口请忽略此提示...

### To Reproduce

按照网上能找到的配置方法，没有复现步骤。

### OpenClash Log

```log
超出字符限制，以附件形式上传。
```

### OpenClash Config

```shell
一切都是默认设置，没有手动更改。
```

### Expected Behavior

找出无法访问外网的原因，给大家提供参考；
找出警告：设置仅允许内网功能失败，无法获取 IPv4 的 WAN 接口名称，请确保防火墙设置中 IPv4 WAN 区域的名称为 wan，如设备无 WAN 口请忽略此提示...的原因；

### Additional Context

[OpenClash 调试日志.txt](https://github.com/vernesong/OpenClash/files/14111630/OpenClash.txt)
![屏幕截图 2024-01-31 201155](https://github.com/vernesong/OpenClash/assets/158281149/a9b9c2b6-b73c-4ec6-a5ad-eb020f0af742)
![w233](https://github.com/vernesong/OpenClash/assets/158281149/11d741bf-4d9a-4481-97fa-30dadc81eb45)
![e233](https://github.com/vernesong/OpenClash/assets/158281149/2b8d2a30-53be-4ea9-9014-b504fa21ab67)

**Comment by okletgo64** [comment]
@sangyishuje1123 
感谢Contributor回复！
1、请教一下nf_table是什么意思？在路由器管理页面哪个地方能看到？我用的是https://github.com/funigna/wrt_release/releases的固件。
![路由器](https://github.com/vernesong/OpenClash/assets/158281149/1ee9bf93-f8a2-4af0-aeb9-c9b84b0d2b6e)
—————————————————————————————————————————————————————————
2、防火墙如下图所示，我的接口名确实是wan，不知道是哪里错了。
![捕获](https://github.com/vernesong/OpenClash/assets/158281149/120183ae-5bf5-4664-93bb-d8454b9ddb8a)
—————————————————————————————————————————————————————————
3、已经改正，并且我在OpenClash“检查并更新”时，貌似无法连接，一直没有进度，只好手动上传内核，误把内核版本当作Dev。我想请教一下，客户端版本如何手动更新？

**Comment by yellowsavant** [comment]
IP v6关掉吧，clash和v6的兼容性并不是很好，很多问题都是v6来的

**Comment by okletgo64** [comment]
@yellowsavant 
感谢提醒，已经尝试过了，我关闭lan接口的DHCPv6功能，并没有作用，只是在nslookup www.baidu.com的时候，成功解析到了IPv4地址

**Comment by okletgo64** [comment]
@sangyishuje1123 
ok，放假就开干，我close掉问题吧
