### ISSUE TITLE
感谢作者首先

### ISSUE THREAD

**Issue by jackway2016** [vernesong/OpenClash#3748]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经**使用最新 Dev 版本**查看过，并不包含该功能特性或者还不完善
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 应包含的特性
- [ ] Contributors 我有能力协助 OpenClash 开发或完善此功能特性
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### Describe the Feature

但是这个东西做的真的很不友好, 尤其是对小白. 其他的配置基本都没问题就这个Openclash配置的时候总是无故就消失要不就是能启动也不能连接. 再不就是读取配置 ,保存配置, 还应用配置搞得超级复杂. 能请作者做的人性化点或者容错率或者错误提示更友好明确一些吗? 感谢

### Describe Alternatives

服了这东西了

**Comment by AllForLandlord** [comment]
标题说感谢作者，但是后面又说服了这东西了，这是什么心态？

**Comment by WFANG12719** [comment]
这东西目标用户本来就是给有Linux 、shell脚本基础、有网络基础知识的人用的，找个这样的朋友帮看看（学计算机的），要么就用别的工具吧。
