### ISSUE TITLE
有个疑问，关于OpenClash的Fake-IP的问题

### ISSUE THREAD

**Issue by shenyanshu** [vernesong/OpenClash#3750]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [ ] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

v0.45.164-beta

### Bug on Environment

Official OpenWrt

### OpenWrt Version

OpenWrt 0.0.0

### Bug on Platform

Linux-386

### Describe the Bug

我目前使用爱快+OpenClash进行分流，国内的域名通过DNS分流获取正常的IP地址，国外的域名通过OpenClash的Fake-IP模式返回IP，然后通过爱快来进行IP分流。
但我发现OpenClash奈飞nflxvideo.net的域名返回的是真实IP，而并非FakeIP。这个是BUG还是实际就是这么设计的？

### To Reproduce

无

### OpenClash Log

```log
我目前使用爱快+OpenClash进行分流，国内的域名通过DNS分流获取正常的IP地址，国外的域名通过OpenClash的Fake-IP模式返回IP，然后通过爱快来进行IP分流。
但我发现OpenClash奈飞nflxvideo.net的域名返回的是真实IP，而并非FakeIP。这个是BUG还是实际就是这么设计的？
```

### OpenClash Config

```shell
无
```

### Expected Behavior

无

**Comment by yellowsavant** [comment]
你可以检查yaml设置档里关于fake-ip-filter区域是否存在奈飞的域名，有的机场给的yaml设置不是那么smooth

**Comment by shenyanshu** [comment]
> 你可以检查yaml设置档里关于fake-ip-filter区域是否存在奈飞的域名，有的机场给的yaml设置不是那么smooth

感谢解惑，我看到默认的fake-ip-filter里面确实是有  - "+.nflxvideo.net" 条目
