### ISSUE TITLE
[Feature] 增加绕过非中国大陆IP功能

### ISSUE THREAD

**Issue by missing233** [vernesong/OpenClash#3752]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经**使用最新 Dev 版本**查看过，并不包含该功能特性或者还不完善
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 应包含的特性
- [ ] Contributors 我有能力协助 OpenClash 开发或完善此功能特性
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### Describe the Feature

希望增加适用于回国代理的绕过非中国大陆IP的功能，仅中国大陆IP以及特定IP（例如B站港澳台）走代理，其他IP不再经过内核

**Comment by missing233** [comment]
> 其实你只要找个非中国大陆IP的地址填到大陆白名单url里，更新一下 然后绕过中国大陆 IPv4 黑名单填特定IP（例如B站港澳台） 再启动oc就行

似乎没有IPv6的oversea名单

**Comment by carrollis** [comment]
> 其实你只要找个非中国大陆IP的地址填到大陆白名单url里，更新一下 然后绕过中国大陆 IPv4 黑名单填特定IP（例如B站港澳台） 再启动oc就行

没理解哈哈，求解释
