### ISSUE TITLE
[Bug] 无法进行版本更新

### ISSUE THREAD

**Issue by ShoukakuChuuCC** [vernesong/OpenClash#3757]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [ ] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

v0.45.157-beta

### Bug on Environment

Immortalwrt

### OpenWrt Version

ImmortalWrt SNAPSHOT r28864-c5048f245b / LuCI Master git-24.034.28311-d9b93a6

### Bug on Platform

Linux-amd64-v3(x86-64)

### Describe the Bug

在immortalwrt中，已经将iptables换成nftables，升级时依然提示需要安装ipset

### To Reproduce

进行版本更新

### OpenClash Log

```log
Package luci-app-openclash (0.45.157-beta) installed in root is up to date.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency ipset for luci-app-openclash
```

### Expected Behavior

在检测到使用nftables的情况下不再依赖ipset进行更新

**Comment by yellowsavant** [comment]
你还是装一下ipset吧，这个在依赖说明上是必装的东西

**Comment by yellowsavant** [comment]
> 你好，如果按你说的，nft不应使用ipset，那么它应该使用什么？

因为dnsmasq本身不完全支持nftset只能用ipset，作者已经在页面上提示必装ipset，装上就是

**Comment by yellowsavant** [comment]
> > 因为dnsmasq本身不完全支持nftset只能用ipset，作者已经在页面上提示必装ipset，装上就是
> 
> ...不是让你回啊🤣🤣🤣

哈哈，看错啦

**Comment by GeekXtop** [comment]
为什么我点检查更新，把自己删除了但没有安装新版本。。。

**Comment by anjue39** [comment]
我是编译版本保存不了，如斐讯k3，本应该是arm7，但是选择它，保存不了，现在只能是未配置
