### ISSUE TITLE
这个只能设置Proxy代理服务器组吗？![image](https://user-images.githubusercontent.com/42875168/80095279-3cd0dc00-859a-11ea-9ec1-4fadccd93cdd.png)

### ISSUE THREAD

**Issue by sun5025** [vernesong/OpenClash#376]
![image](https://user-images.githubusercontent.com/42875168/80095279-3cd0dc00-859a-11ea-9ec1-4fadccd93cdd.png)

_Originally posted by @vernesong in https://github.com/vernesong/OpenClash/issues/370#issuecomment-618352533_

**Comment by vernesong** [comment]
Proxy是指策略组名字，根据你的配置文件来写
