### ISSUE TITLE
[Bug] 网内设备无法用IP访问配置中的代理服务器地址

### ISSUE THREAD

**Issue by 4b441** [vernesong/OpenClash#3763]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [ ] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

v0.46.001-beta

### Bug on Environment

Official OpenWrt

### OpenWrt Version

OpenWrt 22.03.3 r20028-43d71ad93e

### Bug on Platform

Linux-amd64(x86-64)

### Describe the Bug

fake-ip模式，某服务器以IP地址形式写在配置文件中（如下config）

网内设备无法用IP地址访问该服务器（ssh, web服务等），即使切换到直连模式
网内设备可以用域名访问服务器
路由器自身可以用IP访问服务器
[v0.45.157-beta]版本无此问题

### To Reproduce

1. 在配置文件中以IP形式写服务器地址
2. 网内的其他设备用IP访问该服务器
3. 请求被拒绝

### OpenClash Log

```log
尝试访问该服务器时，内核日志（debug）中没有任何相关内容
```

### OpenClash Config

```shell
port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: silent
external-controller: 0.0.0.0:9090
experimental:
  ignore-resolve-fail: true
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  nameserver:
  - https://doh.pub/dns-query
  default-nameserver:
  - 114.114.114.114
  - 119.29.29.29
  fake-ip-range: 198.18.0.1/16
  listen: 0.0.0.0:7874

proxies:
- name: aa
  type: trojan
  server: 123.123.123.123
  port: 443
  password: bb
  network: grpc
  sni: my.domain
  udp: true
  grpc-opts:
    grpc-service-name: cc
```

### Expected Behavior

可用IP访问配置中的代理服务器地址

**Comment by 4b441** [comment]
> 你好是这个情况吗？看你的描述好像不太一样？
> 
> ```ini
> https://github.com/vernesong/OpenClash/issues/3714
> https://github.com/vernesong/OpenClash/issues/3710
> ```

```ini
v0.45.164-beta
把dns指向openclash后可以通过域名访问网站，基于ip的ssh和网站仍然无法访问

_Originally posted by @yqdhm in https://github.com/vernesong/OpenClash/issues/3710#issuecomment-1879675641_
```
看起来我遇到和 #3710 类似的问题，不走内核之后直接连不上。

**Comment by vernesong** [comment]
旁路由？
