### ISSUE TITLE
[Feature] 添加关闭覆写功能

### ISSUE THREAD

**Issue by ObcbO** [vernesong/OpenClash#3769]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经**使用最新 Dev 版本**查看过，并不包含该功能特性或者还不完善
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 应包含的特性
- [ ] Contributors 我有能力协助 OpenClash 开发或完善此功能特性
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### Describe the Feature

对于部分人来说(比如我) 自用的clash配置是一份多端使用的
什么运行模式之类的在配置文件都写好了
在用openclash的时候 没必要都要重新调一遍

**Comment by xuelide** [comment]
按这种逻辑···覆写设置 一键生成 规则附加 配置订阅 这全都可以去掉了。
因为我也是手撸配置，这几个标签页没用过。
但我觉得没啥意义，本来你手撸不去用那些设置就是了，也不影响，没必要大费周章的做修改
