### ISSUE TITLE
频繁占用cpu，降级v0.45.157-beta后正常

### ISSUE THREAD

**Issue by hondaya06** [vernesong/OpenClash#3770]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [ ] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

v0.46.001-beta

### Bug on Environment

Lean

### OpenWrt Version

OpenWrt R24.1.13

### Bug on Platform

Linux-amd64(x86-64)

### Describe the Bug

频繁占用cpu，降级v0.45.157-beta后正常
<img width="505" alt="iShot_2024-02-20_17 13 42" src="https://github.com/vernesong/OpenClash/assets/80587577/eb7b8bea-cc49-41ef-bc02-12ca2345055a">
<img width="1837" alt="iShot_2024-02-21_14 55 41" src="https://github.com/vernesong/OpenClash/assets/80587577/23a2706e-9c39-4e91-be2d-6aa711d7510f">

### To Reproduce

...

### OpenClash Log

```log
...
```

### Expected Behavior

...

**Comment by sachikomakino** [comment]
![image](https://github.com/vernesong/OpenClash/assets/75249799/4cadb1cd-289c-47fb-8abb-5d0d22c6d991)

46.001的cpu确实周期性占用突然升高，跟日志提示还原防火墙规则周期一致

**Comment by anjue39** [comment]
现在版本开启绕过大陆后，跑不满带宽了。以前可以

**Comment by arm946ejs** [comment]
同样问题，周期性CPU占用高

**Comment by IraXu** [comment]
同样，间断性CPU100%占用

**Comment by ihategfw** [comment]
定位到代码在 [这里](https://github.com/vernesong/OpenClash/blob/c38cb9ce81b7a341ffc0fa0914a1849116fe8b82/luci-app-openclash/root/usr/share/openclash/openclash_watchdog.sh#L312)

**Comment by maike2019** [comment]
> ![image](https://private-user-images.githubusercontent.com/75249799/307069640-4cadb1cd-289c-47fb-8abb-5d0d22c6d991.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMTk1NjcsIm5iZiI6MTcxMTExOTI2NywicGF0aCI6Ii83NTI0OTc5OS8zMDcwNjk2NDAtNGNhZGIxY2QtMjg5Yy00N2ZiLThhYmItNWQwZDIyYzZkOTkxLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMlQxNDU0MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YjlmZWM5MzljNmU2MjA2MjM1NDM0ZTM3ZTViN2ZiNjc4OWQ2MmZlYTQwNjFjZmUzNjk1ZmI4MDQzMzBiYTRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GKP0hi1J1VYqrJihucROp4kHnCPuvxWD9KQOJkHbahA)
> 
> 46.001的cpu确实周期性占用突然升高，跟日志提示还原防火墙规则周期一致

你的实时监控软件怎么是中文的？怎么汉化的？

**Comment by Sanhom365** [comment]
> 定位到代码在 [这里](https://github.com/vernesong/OpenClash/blob/c38cb9ce81b7a341ffc0fa0914a1849116fe8b82/luci-app-openclash/root/usr/share/openclash/openclash_watchdog.sh#L312)

这个问题困扰了我很久，把watchdog的间隔调大后就没有每分钟的波峰了。太感谢了！！！

**Comment by t0saki** [comment]
同样，修改sleep到600之后恢复正常。

**Comment by Asunfly** [comment]
> > 定位到代码在 [这里](https://github.com/vernesong/OpenClash/blob/c38cb9ce81b7a341ffc0fa0914a1849116fe8b82/luci-app-openclash/root/usr/share/openclash/openclash_watchdog.sh#L312)
> 
> 这个问题困扰了我很久，把watchdog的间隔调大后就没有每分钟的波峰了。太感谢了！！！

请问大佬是修改哪个选项啊，没有找到。

**Comment by Asunfly** [comment]
> 同样，修改sleep到600之后恢复正常。

请问大佬是修改哪个选项啊，没有找到。
