### ISSUE TITLE
[小小遗憾] 开启clash后，电视中TVbox无法加载数据

### ISSUE THREAD

**Issue by xibeilang0616** [vernesong/OpenClash#3774]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经**使用最新 Dev 版本**查看过，并不包含该功能特性或者还不完善
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 应包含的特性
- [X] Contributors 我有能力协助 OpenClash 开发或完善此功能特性
- [x] Meaningless 我提交的**是无意义的**催促更新或修复请求

### Describe the Feature

设备：中国移动 CMCC RAX3000M路由器，改刷openwrt。

![Screenshot_2024-02-28-14-20-52-633_com android browser](https://github.com/vernesong/OpenClash/assets/56585354/7b30d95c-2d2c-422a-9d64-9f7dc9f4b84b)

开启后clash后，代理大部分正常，就是电视中TVbox就无法加载数据节目源。界面空白！

![Screenshot_2024-02-28-14-04-03-752_com github tvbox osc tk](https://github.com/vernesong/OpenClash/assets/56585354/6e4e31ca-2ad0-4d12-8a3e-1bf1a843383a)

这是APP里面节目源

![Screenshot_2024-02-28-14-07-51-760_com github tvbox osc tk](https://github.com/vernesong/OpenClash/assets/56585354/ed0d0bcd-52eb-460f-bc11-599d85fcc5c0)

![Screenshot_2024-02-28-14-05-10-627_com github tvbox osc tk](https://github.com/vernesong/OpenClash/assets/56585354/5b41dac8-6911-4bba-a7b0-774b829973f6)

一关闭就好了，问问有没有其他办法在不关闭clash的情况下，也能使用TVbox。

这是关闭后的APP正常加载图

![Screenshot_2024-02-28-14-07-40-728_com github tvbox osc tk](https://github.com/vernesong/OpenClash/assets/56585354/00f47de8-d08c-4ba6-88ea-4b2461594847)

**Comment by xashow** [comment]
软件安全DNS选阿里试试

**Comment by xibeilang0616** [comment]
> 软件安全DNS选阿里试试

没有效果

**Comment by xiaolongzhou123** [comment]
我这没有问题。是你的op问题

**Comment by Rafeal-Ma** [comment]
1.可以验证是否fakeip原因 切换成redirhost试试。
2.之前有好友遇到同样的问题。大致原因可能是你的影视盒子里有太多不同的域名或者IP，一部分被你direct的规则匹配走了，一部分被你proxy的规则匹配走了。导致加载不出来。。

**Comment by xibeilang0616** [comment]
> 1.可以验证是否fakeip原因 切换成redirhost试试。 2.之前有好友遇到同样的问题。大致原因可能是你的影视盒子里有太多不同的域名或者IP，一部分被你direct的规则匹配走了，一部分被你proxy的规则匹配走了。导致加载不出来。。

排查出来了，好像不是clash的问题。
是 DNS广告过滤器 的问题

**Comment by anjue39** [comment]
就是clash的问题，tvbox的源国内ip被proxy识别匹配走了，得自定义规则里把源改为直连

**Comment by anjue39** [comment]
> > 1.可以验证是否fakeip原因 切换成redirhost试试。 2.之前有好友遇到同样的问题。大致原因可能是你的影视盒子里有太多不同的域名或者IP，一部分被你direct的规则匹配走了，一部分被你proxy的规则匹配走了。导致加载不出来。。
> 
> 排查出来了，好像不是clash的问题。 是 DNS广告过滤器 的问题

Openclash里有dns广告过滤器？你怎么改的

**Comment by xibeilang0616** [comment]
> > > 1.可以验证是否fakeip原因 切换成redirhost试试。 2.之前有好友遇到同样的问题。大致原因可能是你的影视盒子里有太多不同的域名或者IP，一部分被你direct的规则匹配走了，一部分被你proxy的规则匹配走了。导致加载不出来。。
> > 
> > 
> > 排查出来了，好像不是clash的问题。 是 DNS广告过滤器 的问题
> 
> Openclash里有dns广告过滤器？你怎么改的

就是这样子，效果还不错，就是视频拦截不敢√
IPV6直播源不受影响，IPV4直播源直播无法直播。
![Screenshot_2024-03-02-11-29-49-914_com android browser](https://github.com/vernesong/OpenClash/assets/56585354/38e3eda0-b1df-4143-941b-a0cd0eb8fcf7)

**Comment by anjue39** [comment]
我就没装dns过滤器，也同样有问题，得手动添加规则改直连



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 午夜狂奔 ***@***.***&gt;
发送时间: 2024年3月2日 11:32
收件人: vernesong/OpenClash ***@***.***&gt;
抄送: anjue39 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [vernesong/OpenClash] [小小遗憾] 开启clash后，电视中TVbox无法加载数据 (Issue #3774)





    
1.可以验证是否fakeip原因 切换成redirhost试试。 2.之前有好友遇到同样的问题。大致原因可能是你的影视盒子里有太多不同的域名或者IP，一部分被你direct的规则匹配走了，一部分被你proxy的规则匹配走了。导致加载不出来。。
  
排查出来了，好像不是clash的问题。 是 DNS广告过滤器 的问题
  
Openclash里有dns广告过滤器？你怎么改的
  
就是这样子，效果还不错，就是视频拦截不敢√
 IPV6直播源不受影响，IPV4直播源直播无法直播。
 Screenshot_2024-03-02-11-29-49-914_com.android.browser.jpg (view on web)

**Comment by xibeilang0616** [comment]
> 就是clash的问题，tvbox的源国内ip被proxy识别匹配走了，得自定义规则里把源改为直连

具体怎么操作？

**Comment by Amazon90** [comment]
我停用dnsmasq就解决了

**Comment by cjlhll** [comment]
我也遇到问题了，如何解决啊，把tvbox源添加到直连也不好使。我的是能加载数据，但是无法播放，播放源可太多了，根本不可能加到直连规则里。
