### ISSUE TITLE
DDNS获取的公网IP地址异常

### ISSUE THREAD

**Issue by yaleyip** [vernesong/OpenClash#378]
没有科学上网时，默认显示IP地址125.88.19.122，youtube状态项显示连接超时
一旦科学上网，才能显示正确公网IP地址，所有状态项显示正常

第一次科学上网，往往有卡滞现象，是不是与这个有关？
![image](https://user-images.githubusercontent.com/60421789/80173950-f0ca7980-8623-11ea-99d1-ca3106b0515c.png)

![image](https://user-images.githubusercontent.com/60421789/80166975-d8516380-8611-11ea-9769-afe10a3c8fdd.png)

-----------
0.37.4
FakeIP TUN模式

**Comment by vernesong** [comment]
把你的域名解析服务器加到DNS高级设置里

**Comment by yaleyip** [comment]
已经添加域名解析服务器。

进一步分析发现，报告的问题仅仅出现在远程登录，本地公网IP地址显示正常。
