### ISSUE TITLE
[Feature] 支持dns: proxy-server-nameserver 字段

### ISSUE THREAD

**Issue by Plutonium141** [vernesong/OpenClash#3781]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经**使用最新 Dev 版本**查看过，并不包含该功能特性或者还不完善
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 应包含的特性
- [ ] Contributors 我有能力协助 OpenClash 开发或完善此功能特性
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### Describe the Feature

目前openclash还没有proxy-server-nameserver对应的设置，用起来有点不方便

### Describe Alternatives

可以参考 [clash.meta wiki: proxy-server-nameserver](https://wiki.metacubex.one/config/dns/#proxy-server-nameserver)

**Comment by Fddh2012** [comment]
有吧？？？？？
点开具体的DNS服务器详细设置里就有了。

**Comment by Plutonium141** [comment]
> 有吧？？？？？ 点开具体的DNS服务器详细设置里就有了。

没找到啊 到是有个Fallback-Filter似乎可以曲线救国一下

**Comment by LemonPAKA** [comment]
> > 有吧？？？？？ 点开具体的DNS服务器详细设置里就有了。
> 
> 没找到啊 到是有个Fallback-Filter似乎可以曲线救国一下

![image](https://github.com/vernesong/OpenClash/assets/17202894/0658641e-1dda-4c72-b3e3-e914e826a6c8)
这个就是

**Comment by Plutonium141** [comment]
> > > 有吧？？？？？ 点开具体的DNS服务器详细设置里就有了。
> > 
> > 没找到啊 到是有个Fallback-Filter似乎可以曲线救国一下
> 
> ![image](https://github.com/vernesong/OpenClash/assets/17202894/0658641e-1dda-4c72-b3e3-e914e826a6c8)
> 这个就是

感谢，找到了，没想到放的这么深，可以用但也不是太理想，如果想单独添加proxy-server-nameserver就会影响nameserver / fallback / default-nameserver的设置

目前只能选择default-nameserver组服务器作为节点域名解析才能最小化影响

**Comment by Fddh2012** [comment]
> > > > 有吧？？？？？ 点开具体的DNS服务器详细设置里就有了。
> > > 
> > > 
> > > 没找到啊 到是有个Fallback-Filter似乎可以曲线救国一下
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/17202894/309871111-0658641e-1dda-4c72-b3e3-e914e826a6c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MTUyNDAsIm5iZiI6MTcwOTYxNDk0MCwicGF0aCI6Ii8xNzIwMjg5NC8zMDk4NzExMTEtMDY1ODY0MWUtMWRkYS00YzcyLWIzZTMtZTkxNGU4MjZhNmM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDA1MDIyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5ZWY5NWQ2NDBhZDBmMzRjOGQ1NDQ2NjczZGU4MTYyNzNhZjBhMGYyM2E2NzhmMTllMmM1MTgyY2RjNTIzYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ay9SsX0DGFmGG7Jyz-9VZZ3y677ms32ts4ewDInFleI)
> > 这个就是
> 
> 感谢，找到了，没想到放的这么深，可以用但也不是太理想，如果想单独添加proxy-server-nameserver就会影响nameserver / fallback / default-nameserver的设置
> 
> 目前只能选择default-nameserver组服务器作为节点域名解析才能最小化影响

怎么会影响啊？这些本质上都是要写入运行配置的，meta内核怎么处理，找到对应的条目写入不就好了。

**Comment by Fddh2012** [comment]
> 借楼问一下这两个DNS的功能在哪里能找到？ https://wiki.metacubex.one/config/dns/#prefer-h3 https://wiki.metacubex.one/config/proxies/dns/

prefer-h3 也在这个页面里，服务器类型切换到https后就会有。
dns出站这个好像要自己写进配置里。

**Comment by Plutonium141** [comment]
> > > > > 有吧？？？？？ 点开具体的DNS服务器详细设置里就有了。
> > > > 
> > > > 
> > > > 没找到啊 到是有个Fallback-Filter似乎可以曲线救国一下
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/17202894/309871111-0658641e-1dda-4c72-b3e3-e914e826a6c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MTUyNDAsIm5iZiI6MTcwOTYxNDk0MCwicGF0aCI6Ii8xNzIwMjg5NC8zMDk4NzExMTEtMDY1ODY0MWUtMWRkYS00YzcyLWIzZTMtZTkxNGU4MjZhNmM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDA1MDIyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5ZWY5NWQ2NDBhZDBmMzRjOGQ1NDQ2NjczZGU4MTYyNzNhZjBhMGYyM2E2NzhmMTllMmM1MTgyY2RjNTIzYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ay9SsX0DGFmGG7Jyz-9VZZ3y677ms32ts4ewDInFleI)
> > > 这个就是
> > 
> > 
> > 感谢，找到了，没想到放的这么深，可以用但也不是太理想，如果想单独添加proxy-server-nameserver就会影响nameserver / fallback / default-nameserver的设置
> > 目前只能选择default-nameserver组服务器作为节点域名解析才能最小化影响
> 
> 怎么会影响啊？这些本质上都是要写入运行配置的，meta内核怎么处理，找到对应的条目写入不就好了。

把114.114.114.114添加到proxy-server-nameserver然后在default-nameserver组里勾选作为节点域名解析，如果不启用这条dns设置那么114也不会被添加到proxy-server-nameserver，如果勾选启用那么114会既在proxy-server-nameserver里又在default-nameserver里

**Comment by Fddh2012** [comment]
> > > > > > 有吧？？？？？ 点开具体的DNS服务器详细设置里就有了。
> > > > > 
> > > > > 
> > > > > 没找到啊 到是有个Fallback-Filter似乎可以曲线救国一下
> > > > 
> > > > 
> > > > ![image](https://private-user-images.githubusercontent.com/17202894/309871111-0658641e-1dda-4c72-b3e3-e914e826a6c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MTUyNDAsIm5iZiI6MTcwOTYxNDk0MCwicGF0aCI6Ii8xNzIwMjg5NC8zMDk4NzExMTEtMDY1ODY0MWUtMWRkYS00YzcyLWIzZTMtZTkxNGU4MjZhNmM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDA1MDIyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5ZWY5NWQ2NDBhZDBmMzRjOGQ1NDQ2NjczZGU4MTYyNzNhZjBhMGYyM2E2NzhmMTllMmM1MTgyY2RjNTIzYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ay9SsX0DGFmGG7Jyz-9VZZ3y677ms32ts4ewDInFleI)
> > > > 这个就是
> > > 
> > > 
> > > 感谢，找到了，没想到放的这么深，可以用但也不是太理想，如果想单独添加proxy-server-nameserver就会影响nameserver / fallback / default-nameserver的设置
> > > 目前只能选择default-nameserver组服务器作为节点域名解析才能最小化影响
> > 
> > 
> > 怎么会影响啊？这些本质上都是要写入运行配置的，meta内核怎么处理，找到对应的条目写入不就好了。
> 
> 如果想把114.114.114.114添加到proxy-server-nameserver就需要先将114添加到一个dns组里比如default-nameserver，再勾选作为节点域名解析，如果不启用这条dns设置那么114也不会被添加到proxy-server-nameserver，如果勾选启用那么114会既在proxy-server-nameserver里又在default-nameserver里

如果是这样的话，需要把proxy-server-nameserver单独拉出来做为一个分组了。

**Comment by Plutonium141** [comment]
> > > > > 有吧？？？？？ 点开具体的DNS服务器详细设置里就有了。
> > > > 
> > > > 
> > > > 没找到啊 到是有个Fallback-Filter似乎可以曲线救国一下
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/17202894/309871111-0658641e-1dda-4c72-b3e3-e914e826a6c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MjIyNzIsIm5iZiI6MTcwOTYyMTk3MiwicGF0aCI6Ii8xNzIwMjg5NC8zMDk4NzExMTEtMDY1ODY0MWUtMWRkYS00YzcyLWIzZTMtZTkxNGU4MjZhNmM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDA2NTkzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyY2M1MDJlODBlZjMyMjU4OWRlNDA3OTVlY2FjZjVkZTViZjU2N2IwOTdmOWY2MTdkMWUzZjMyNzkwODM0OGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pVJUrCrbVeR6y8ZyZCyXq4V59YlqiRSxKmqAHRQ-KBA)
> > > 这个就是
> > 
> > 
> > 感谢，找到了，没想到放的这么深，可以用但也不是太理想，如果想单独添加proxy-server-nameserver就会影响nameserver / fallback / default-nameserver的设置
> > 目前只能选择default-nameserver组服务器作为节点域名解析才能最小化影响
> 
> 感觉应对特殊时期用proxy-server-nameserver设置意义不大，如果设置为国外的地址，连接不稳定。如果设置成国内的，污染的就是国内的，更没用。不如直接根据服务器域名查出对应的ip写进host里 https://wiki.metacubex.one/config/dns/#use-hosts https://wiki.metacubex.one/config/dns/hosts/ ，反正一年也就这么几周。

有些机场的节点会根据dns提供不同的入口，使用海外dns会得到海外的入口，使用国内dns就会得到国内的入口

**Comment by Plutonium141** [comment]
> > > > > > > 有吧？？？？？ 点开具体的DNS服务器详细设置里就有了。
> > > > > > 
> > > > > > 
> > > > > > 没找到啊 到是有个Fallback-Filter似乎可以曲线救国一下
> > > > > 
> > > > > 
> > > > > ![image](https://private-user-images.githubusercontent.com/17202894/309871111-0658641e-1dda-4c72-b3e3-e914e826a6c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MjIyNzIsIm5iZiI6MTcwOTYyMTk3MiwicGF0aCI6Ii8xNzIwMjg5NC8zMDk4NzExMTEtMDY1ODY0MWUtMWRkYS00YzcyLWIzZTMtZTkxNGU4MjZhNmM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDA2NTkzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyY2M1MDJlODBlZjMyMjU4OWRlNDA3OTVlY2FjZjVkZTViZjU2N2IwOTdmOWY2MTdkMWUzZjMyNzkwODM0OGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pVJUrCrbVeR6y8ZyZCyXq4V59YlqiRSxKmqAHRQ-KBA)
> > > > > 这个就是
> > > > 
> > > > 
> > > > 感谢，找到了，没想到放的这么深，可以用但也不是太理想，如果想单独添加proxy-server-nameserver就会影响nameserver / fallback / default-nameserver的设置
> > > > 目前只能选择default-nameserver组服务器作为节点域名解析才能最小化影响
> > > 
> > > 
> > > 感觉应对特殊时期用proxy-server-nameserver设置意义不大，如果设置为国外的地址，连接不稳定。如果设置成国内的，污染的就是国内的，更没用。不如直接根据服务器域名查出对应的ip写进host里 https://wiki.metacubex.one/config/dns/#use-hosts https://wiki.metacubex.one/config/dns/hosts/ ，反正一年也就这么几周。
> > 
> > 
> > 有些机场的节点会根据dns提供不同的入口，使用海外dns会得到海外的入口，使用国内dns就会得到国内的入口
> 
> 不好意思，不太理解你的意思 我的意思是把入口地址写进host，这样dns污染时就不会受到波及。
> 
> 你回复的意思是，你既要用国内入口，也要用海外入口？

我的意思是用proxy-server-nameserver设置一个国内dns就可以使用节点的高速国内入口，不需要为节点域名写hosts，也不是为了应对特殊时期

**Comment by Fddh2012** [comment]
> > > > > > > > > 有吧？？？？？ 点开具体的DNS服务器详细设置里就有了。
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 没找到啊 到是有个Fallback-Filter似乎可以曲线救国一下
> > > > > > > 
> > > > > > > 
> > > > > > > ![image](https://private-user-images.githubusercontent.com/17202894/309871111-0658641e-1dda-4c72-b3e3-e914e826a6c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MjIyNzIsIm5iZiI6MTcwOTYyMTk3MiwicGF0aCI6Ii8xNzIwMjg5NC8zMDk4NzExMTEtMDY1ODY0MWUtMWRkYS00YzcyLWIzZTMtZTkxNGU4MjZhNmM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDA2NTkzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyY2M1MDJlODBlZjMyMjU4OWRlNDA3OTVlY2FjZjVkZTViZjU2N2IwOTdmOWY2MTdkMWUzZjMyNzkwODM0OGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pVJUrCrbVeR6y8ZyZCyXq4V59YlqiRSxKmqAHRQ-KBA)
> > > > > > > 这个就是
> > > > > > 
> > > > > > 
> > > > > > 感谢，找到了，没想到放的这么深，可以用但也不是太理想，如果想单独添加proxy-server-nameserver就会影响nameserver / fallback / default-nameserver的设置
> > > > > > 目前只能选择default-nameserver组服务器作为节点域名解析才能最小化影响
> > > > > 
> > > > > 
> > > > > 感觉应对特殊时期用proxy-server-nameserver设置意义不大，如果设置为国外的地址，连接不稳定。如果设置成国内的，污染的就是国内的，更没用。不如直接根据服务器域名查出对应的ip写进host里 https://wiki.metacubex.one/config/dns/#use-hosts https://wiki.metacubex.one/config/dns/hosts/ ，反正一年也就这么几周。
> > > > 
> > > > 
> > > > 有些机场的节点会根据dns提供不同的入口，使用海外dns会得到海外的入口，使用国内dns就会得到国内的入口
> > > 
> > > 
> > > 不好意思，不太理解你的意思 我的意思是把入口地址写进host，这样dns污染时就不会受到波及。
> > > 你回复的意思是，你既要用国内入口，也要用海外入口？
> > 
> > 
> > 我的意思是用proxy-server-nameserver设置一个国内dns就可以使用节点的高速国内入口，不需要为节点域名写hosts，也不是为了应对特殊时期
> 
> 好的，我们情况不一样，我的机场老板默认给了个proxy-server-nameserver，结果今早的污染还是没撑住 ![1](https://private-user-images.githubusercontent.com/162243326/310028894-a1c633a8-28ba-4431-893c-557f18471ee9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2Mzc3NTUsIm5iZiI6MTcwOTYzNzQ1NSwicGF0aCI6Ii8xNjIyNDMzMjYvMzEwMDI4ODk0LWExYzYzM2E4LTI4YmEtNDQzMS04OTNjLTU1N2YxODQ3MWVlOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNVQxMTE3MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kM2NjYTNhOWEyNDQ3NGE1ZDRhZTg3ZDk0MDViM2IxNmJjYjlhMGQ0NWI3ZjJjOWRmZjhjNDRlZWIzOThlZjc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Gj3L3BBKcrqbIRQw3aSqxP3czBhDI6aVWg5PV1uAUBk)

你的污染源会不会在别的地方呢？

**Comment by Fddh2012** [comment]
> > > > > > > > > > > 有吧？？？？？ 点开具体的DNS服务器详细设置里就有了。
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 没找到啊 到是有个Fallback-Filter似乎可以曲线救国一下
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > ![image](https://private-user-images.githubusercontent.com/17202894/309871111-0658641e-1dda-4c72-b3e3-e914e826a6c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MjIyNzIsIm5iZiI6MTcwOTYyMTk3MiwicGF0aCI6Ii8xNzIwMjg5NC8zMDk4NzExMTEtMDY1ODY0MWUtMWRkYS00YzcyLWIzZTMtZTkxNGU4MjZhNmM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDA2NTkzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyY2M1MDJlODBlZjMyMjU4OWRlNDA3OTVlY2FjZjVkZTViZjU2N2IwOTdmOWY2MTdkMWUzZjMyNzkwODM0OGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pVJUrCrbVeR6y8ZyZCyXq4V59YlqiRSxKmqAHRQ-KBA)
> > > > > > > > > 这个就是
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 感谢，找到了，没想到放的这么深，可以用但也不是太理想，如果想单独添加proxy-server-nameserver就会影响nameserver / fallback / default-nameserver的设置
> > > > > > > > 目前只能选择default-nameserver组服务器作为节点域名解析才能最小化影响
> > > > > > > 
> > > > > > > 
> > > > > > > 感觉应对特殊时期用proxy-server-nameserver设置意义不大，如果设置为国外的地址，连接不稳定。如果设置成国内的，污染的就是国内的，更没用。不如直接根据服务器域名查出对应的ip写进host里 https://wiki.metacubex.one/config/dns/#use-hosts https://wiki.metacubex.one/config/dns/hosts/ ，反正一年也就这么几周。
> > > > > > 
> > > > > > 
> > > > > > 有些机场的节点会根据dns提供不同的入口，使用海外dns会得到海外的入口，使用国内dns就会得到国内的入口
> > > > > 
> > > > > 
> > > > > 不好意思，不太理解你的意思 我的意思是把入口地址写进host，这样dns污染时就不会受到波及。
> > > > > 你回复的意思是，你既要用国内入口，也要用海外入口？
> > > > 
> > > > 
> > > > 我的意思是用proxy-server-nameserver设置一个国内dns就可以使用节点的高速国内入口，不需要为节点域名写hosts，也不是为了应对特殊时期
> > > 
> > > 
> > > 好的，我们情况不一样，我的机场老板默认给了个proxy-server-nameserver，结果今早的污染还是没撑住 ![1](https://private-user-images.githubusercontent.com/162243326/310028894-a1c633a8-28ba-4431-893c-557f18471ee9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2Mzc3NTUsIm5iZiI6MTcwOTYzNzQ1NSwicGF0aCI6Ii8xNjIyNDMzMjYvMzEwMDI4ODk0LWExYzYzM2E4LTI4YmEtNDQzMS04OTNjLTU1N2YxODQ3MWVlOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNVQxMTE3MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kM2NjYTNhOWEyNDQ3NGE1ZDRhZTg3ZDk0MDViM2IxNmJjYjlhMGQ0NWI3ZjJjOWRmZjhjNDRlZWIzOThlZjc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Gj3L3BBKcrqbIRQw3aSqxP3czBhDI6aVWg5PV1uAUBk)
> > 
> > 
> > 你的污染源会不会在别的地方呢？ 你的psn是doh，严格来说是不会被污染的，只能说你的污染源不在这条路径上。 另外防污染应该是Fallback和Fallback-Filter来负责的，配置好这两应该就没问题了。
> 
> 机场群全说炸，我是自己写的配置，反而没出问题。同时我也没开fakeip持久化。之后机场老板临时把部分节点域名改ip让大家先用，最后全部换了新的域名。所以应该是dns被污染了。 再问一下，现在有必要配Fallback吗？我之前查资料看网上全都在骂。用nameserver-policy代替。 ![1](https://private-user-images.githubusercontent.com/162243326/310121529-78bf0125-2325-4e6f-be04-7241ade67347.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2NTkwMDcsIm5iZiI6MTcwOTY1ODcwNywicGF0aCI6Ii8xNjIyNDMzMjYvMzEwMTIxNTI5LTc4YmYwMTI1LTIzMjUtNGU2Zi1iZTA0LTcyNDFhZGU2NzM0Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNVQxNzExNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYzFlMjgxMDE5Njc5ZDZmNDIyMjY2OTI3ZTkwNTI2ZWI2YTgzMjNkNWEyZDEwZmJkNzYyNWRkZjU4ZmQ4ODI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aAFORgtrdZ_bGhQj07wYD_rsCchmLAACte46ZBajDdw)

搞明白Fallback的作用了就知道应该怎么用了。不能别人说什么就什么。

**Comment by Fddh2012** [comment]
> > 搞明白Fallback的作用了就知道应该怎么用了。不能别人说什么就什么。
> 
> 问题就在这，所以请教一下，希望别嫌烦 fallback的作用是在得到的结果和nameserver冲突时，非设置地区的结果以fallback为准，默认是非CN以fallback为准。 既然fallback是产生冲突后才生效，为何不直接对海外网址用海外dns国内网址用国内dns 所以我是真没搞明白Fallback的作用，也不知道应该怎么用

https://wiki.metacubex.one/config/dns/diagram/
看一下这里的解析流程哈。

**Comment by Plutonium141** [comment]
> > 搞明白Fallback的作用了就知道应该怎么用了。不能别人说什么就什么。
> 
> 问题就在这，所以请教一下，希望别嫌烦 fallback的作用是在得到的结果和nameserver冲突时，非设置地区的结果以fallback为准，默认是非CN以fallback为准。 既然fallback是产生冲突后才生效，为何不直接对海外网址用海外dns国内网址用国内dns 所以我是真没搞明白Fallback的作用，也不知道应该怎么用

想要海外域名使用海外dns，国内域名使用国内dns的前提是知道哪些域名是国外哪些域名是国内的，虽然有geosite但是还是有漏网之鱼，在不清楚域名是国内还是国外时就需要使用fallback

fallback与nameserver并发解析域名，再根据fallback-filter的配置决定采用哪一个组的结果，这样的好处是可以尽可能的找到最佳解析结果，而不是因为直接使用海外dns错过国内进入点导致速度卡慢

**Comment by xpn282** [comment]
我就是用 Nameserver-Policy设为geosite:cn，设国内dns。Nameserver设为国外dns（代理解析），舍弃了Fallback-Filter。
虽然会出现上面说的，并非所有cn域名都能收录在geosite里，导致用到国外dns来解析，其实这些极小众域名根本就不用在乎它是用谁来解析，即使使用了国外dns来解析，也不影响访问的。舍弃Fallback-Filter，对实际使用中的影响微乎其微，我是这样觉得，因为我就是这样用的，仅供参考。。哈哈

还有proxy-server-nameserver其实我主要是为了给Nameserver的国外dns代理解析用的，就像Meta文档说的，防止鸡生蛋的问题，不然我就不设proxy-server- Nameserver了
