### ISSUE TITLE
[Bug] 检测到 Dnsmasq 工作异常 提示反复出现

### ISSUE THREAD

**Issue by winnie-neil** [vernesong/OpenClash#3782]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [ ] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

v0.46.002-beta

### Bug on Environment

Other

### OpenWrt Version

OpenWrt 23.198.59743-991daf5

### Bug on Platform

Linux-amd64(x86-64)

### Describe the Bug

日志中反复出现：警告：检测到 Dnsmasq 工作异常，设置防火墙 DNS 劫持规则...
见截图，功能目前未见明显影响，有时会断网，几秒钟后自动恢复（不确定是否是由本issue引起的）。

<img width="984" alt="截屏2024-03-05 17 39 44" src="https://github.com/vernesong/OpenClash/assets/80040267/24af16b5-b104-4f7c-a3b6-dec52dd2e501">

### To Reproduce

随时出现，一直存在

### OpenClash Log

```log
见附件
```

### Expected Behavior

请求排除故障，告知原因（如dnsmasq问题）

### Additional Context

[OpenClash 调试日志.txt](https://github.com/vernesong/OpenClash/files/14493498/OpenClash.txt)

**Comment by vernesong** [comment]
尝试以下命令
```
uci set dhcp.@dnsmasq[0].localuse="1"
uci commit dhcp
/etc/init.d/dnsmasq restart

**Comment by winnie-neil** [comment]
尝试上述命令并尝试https://github.com/vernesong/OpenClash/issues/3765#issuecomment-1977793826 给出的iptable命令均无效。请见截图。谢谢！
![Uploading 截屏2024-03-06 00.34.58.png…]()

**Comment by winnie-neil** [comment]
尝试上述命令并尝试https://github.com/vernesong/OpenClash/issues/3765#issuecomment-1977793826 给出的iptable命令均无效。请见截图。谢谢！
<img width="917" alt="截屏2024-03-06 00 34 58" src="https://github.com/vernesong/OpenClash/assets/80040267/d96102f1-3317-41d6-adcb-706fd43d9db9">

**Comment by qin9125** [comment]
> 尝试以下命令
> 
> ```
> uci set dhcp.@dnsmasq[0].localuse="1"
> uci commit dhcp
> /etc/init.d/dnsmasq restart
> ```

<img width="691" alt="image" src="https://github.com/vernesong/OpenClash/assets/32502941/5bd45050-9318-4f87-af3a-055fc3aaa3c1">
大佬能更新一下自动编译吗？现在不能用了，谢谢

**Comment by winnie-neil** [comment]
经过反复测试，刚刚重启openwrt后是可以的（图1），但过了日志中的这一步：提示：检测到 Dnsmasq 正常工作，还原防火墙 DNS 劫持规则...  之后，就不行了，如图2。请作者参考，谢谢！
<img width="523" alt="截屏2024-03-06 11 44 37" src="https://github.com/vernesong/OpenClash/assets/80040267/4e86ca9d-03f3-4500-9610-453d735512c8">
图1

<img width="939" alt="截屏2024-03-06 11 44 49" src="https://github.com/vernesong/OpenClash/assets/80040267/d57db241-40a2-4fa5-b3c1-e0357d7c400d">
图2

**Comment by vernesong** [comment]
你的日志里面 nslookup www.baidu.com 是正常的，nslookup www.baidu.com 127.0.0.1:53不正常，我还在找原因

**Comment by wujun4code** [comment]
我也遇到了这个问题，老版本的内核

![image](https://github.com/user-attachments/assets/56311c62-e0bc-4698-bb59-85122f920bcf)
