### ISSUE TITLE
[Bug] mata内核与metacubexd面板无法正常使用

### ISSUE THREAD

**Issue by GuangYu-yu** [vernesong/OpenClash#3791]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [X] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [X] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

v0.46.003-248

### Bug on Environment

Official OpenWrt, Immortalwrt, Other

### OpenWrt Version

openwrt-23.05

### Bug on Platform

Linux-amd64(x86-64)

### Describe the Bug

mata内核使用后，提示无法获取 General 部分的转发端口设置以及dns端口等问题。metacubexd面板完全空白，一直是这样。

### To Reproduce

不使用mata内核，就能够正常启动使用了。

### OpenClash Log

```log
日志丢失
```

### Expected Behavior

正常使用mata内核以及面板

**Comment by Unwillingx** [comment]
之前遇到过类似情况，貌似是meta内核没下载好的问题，用其它科学插件扶梯后重新下载后恢复正常使用，希望能帮到你

**Comment by vl3550** [comment]
嘗試 
設置-切換後端-填入後台地址端口 密鑰

**Comment by pandamelive** [comment]
我也遇到相同的问题

**Comment by Rangtian** [comment]
应该是 Metacubexd 的问题。

我发现主力机 Metacubexd 空白后，翻出备用机，备用机的旧版 Metacubexd 一切正常。
更新备用机的 Metacubexd 后，也变成空白了。

**Comment by GuangYu-yu** [comment]
> 应该是 Metacubexd 的问题。
> 
> 我发现主力机 Metacubexd 空白后，翻出备用机，备用机的旧版 Metacubexd 一切正常。
> 更新备用机的 Metacubexd 后，也变成空白了。 

检查并更新下载来的Meta有问题，我手动上传后面板能正常使用了

**Comment by GuangYu-yu** [comment]
> 应该是 Metacubexd 的问题。
> 
> 我发现主力机 Metacubexd 空白后，翻出备用机，备用机的旧版 Metacubexd 一切正常。
> 更新备用机的 Metacubexd 后，也变成空白了。 

也许更新的mata版本可能不是最新的，也可能是不兼容最新的Meta内核

**Comment by garryshield** [comment]
自动更新的 版本是 `MetaCubeX/metacubexd` V1.138.1 
面板自动获取后台地址和密码是在 `setup` 路由里

[/src/main.tsx#L28](https://github.com/MetaCubeX/metacubexd/blob/9e68bb6ad5e880dec0e641cf24bb0a65c5c28f58/src/main.tsx#L28)
```js
   ...
        <Route path={ROUTES.Setup} component={Setup} />
        <Route path="*" component={Overview} /> // 默认路由
   ...
```
[/src/pages/Setup.tsx#L110](https://github.com/MetaCubeX/metacubexd/blob/9e68bb6ad5e880dec0e641cf24bb0a65c5c28f58/src/pages/Setup.tsx#L110)
```js

  onMount(() => {
    const query = new URLSearchParams(location.search)

    if (query.has('hostname')) {
      void onSubmit({
        url: `${window.location.protocol}//${query.get('hostname')}${
          query.get('port') ? `:${query.get('port')}` : ''
        }`,
        secret: query.get('secret') ?? '',
      })
    } else if (endpointList().length === 0) {
      /**
        we only try auto login when there is nothing in endpoint list
        or user who is using default config won't be able to switch to another endpoint ever
      */
      void onSubmit({
        url: 'http://127.0.0.1:9090',
        secret: '',
      })
    }
  })
```

后台生成面板地址用的是 `'/ui/metacubexd/#/?hostname='` 主路由 `*`
[/luci-app-openclash/luasrc/view/openclash/status.htm#L851](https://github.com/vernesong/OpenClash/blob/8ebe09eec3d8e6dc115328ef54a2ca7c4d6d40ad/luci-app-openclash/luasrc/view/openclash/status.htm#L851)
```js
	function meta_dashboard(btn)
    {
        XHR.get('<%=luci.dispatcher.build_url("admin", "services", "openclash", "status")%>', null, function(x, status) {
        btn.disabled = true;
        btn.value    = '<%:Metacubexd Control Panel%>';
        if (status.daip && window.location.hostname == status.daip) {
            url9='<%="http://'+window.location.hostname+':'+status.cn_port+'/ui/metacubexd/#/?hostname='+ window.location.hostname + '&port=' + status.cn_port + '&secret=' + status.dase +'"%>';
        }
        else if (status.daip && window.location.hostname != status.daip && status.db_foward_domain && status.db_foward_port) {
            var ui_proto = status.db_forward_ssl == 0 ? 'http://' : 'https://';
            url9='<%="'+ui_proto+status.db_foward_domain+':'+status.db_foward_port+'/ui/metacubexd/#/?hostname='+ status.db_foward_domain + '&port=' + status.db_foward_port + '&secret=' + status.dase +'"%>';
        }
        else {
            url9='<%="http://'+window.location.hostname+':'+status.cn_port+'/ui/metacubexd/"%>';
        }
        winOpen(url9);
        return false;
        });
    };
```

`'/ui/metacubexd/#/setup?hostname='` 这里应该更新下
完整的自动填充后台地址的密码的链接应该是
'http://10.10.1.1:9090/ui/metacubexd/#/setup?hostname=10.10.1.1&port=9090&secret=XXX'

**Comment by XinSSS** [comment]
我也遇到了相同的问题，我尝试着直接clone [metacubexd](https://github.com/MetaCubeX/metacubexd) build运行是没有问题的

@garryshield 有用，在openclash原先打开的链接中加入了setup后能正常使用了

**Comment by Chever-John** [comment]
@GuangYu-yu hi，我理解你这里所说的 meta 指的是 metacubexd 是吧？
因为我也遇到了 openclash 默认安装 的 metacubexd 访问直接白屏，我尝试了很多方法，升级这个 metacubexd 到最新的版本，通过页面的插件中的 “外部访问” 里提供的升级按钮。我也尝试过 setup 添加到 url 中。

请问还有其他可以尝试的方法吗？

**Comment by 46319943** [comment]
> 自动更新的 版本是 `MetaCubeX/metacubexd` V1.138.1 面板自动获取后台地址和密码是在 `setup` 路由里
> 
> [/src/main.tsx#L28](https://github.com/MetaCubeX/metacubexd/blob/9e68bb6ad5e880dec0e641cf24bb0a65c5c28f58/src/main.tsx#L28)
> 
> ```js
>    ...
>         <Route path={ROUTES.Setup} component={Setup} />
>         <Route path="*" component={Overview} /> // 默认路由
>    ...
> ```
> 
> [/src/pages/Setup.tsx#L110](https://github.com/MetaCubeX/metacubexd/blob/9e68bb6ad5e880dec0e641cf24bb0a65c5c28f58/src/pages/Setup.tsx#L110)
> 
> ```js
>   onMount(() => {
>     const query = new URLSearchParams(location.search)
> 
>     if (query.has('hostname')) {
>       void onSubmit({
>         url: `${window.location.protocol}//${query.get('hostname')}${
>           query.get('port') ? `:${query.get('port')}` : ''
>         }`,
>         secret: query.get('secret') ?? '',
>       })
>     } else if (endpointList().length === 0) {
>       /**
>         we only try auto login when there is nothing in endpoint list
>         or user who is using default config won't be able to switch to another endpoint ever
>       */
>       void onSubmit({
>         url: 'http://127.0.0.1:9090',
>         secret: '',
>       })
>     }
>   })
> ```
> 
> 后台生成面板地址用的是 `'/ui/metacubexd/#/?hostname='` 主路由 `*` [/luci-app-openclash/luasrc/view/openclash/status.htm#L851](https://github.com/vernesong/OpenClash/blob/8ebe09eec3d8e6dc115328ef54a2ca7c4d6d40ad/luci-app-openclash/luasrc/view/openclash/status.htm#L851)
> 
> ```js
> 	function meta_dashboard(btn)
>     {
>         XHR.get('<%=luci.dispatcher.build_url("admin", "services", "openclash", "status")%>', null, function(x, status) {
>         btn.disabled = true;
>         btn.value    = '<%:Metacubexd Control Panel%>';
>         if (status.daip && window.location.hostname == status.daip) {
>             url9='<%="http://'+window.location.hostname+':'+status.cn_port+'/ui/metacubexd/#/?hostname='+ window.location.hostname + '&port=' + status.cn_port + '&secret=' + status.dase +'"%>';
>         }
>         else if (status.daip && window.location.hostname != status.daip && status.db_foward_domain && status.db_foward_port) {
>             var ui_proto = status.db_forward_ssl == 0 ? 'http://' : 'https://';
>             url9='<%="'+ui_proto+status.db_foward_domain+':'+status.db_foward_port+'/ui/metacubexd/#/?hostname='+ status.db_foward_domain + '&port=' + status.db_foward_port + '&secret=' + status.dase +'"%>';
>         }
>         else {
>             url9='<%="http://'+window.location.hostname+':'+status.cn_port+'/ui/metacubexd/"%>';
>         }
>         winOpen(url9);
>         return false;
>         });
>     };
> ```
> 
> `'/ui/metacubexd/#/setup?hostname='` 这里应该更新下 完整的自动填充后台地址的密码的链接应该是 'http://10.10.1.1:9090/ui/metacubexd/#/setup?hostname=10.10.1.1&port=9090&secret=XXX'

方法有用。我全新安装的0.46.016-beta，使用meta内核下metacubexd面板就进不去。
把上面这个链接中，两处的10.10.1.1换成自己的软路由IP地址，然后在“插件设置-外部控制-管理页面登录密钥”中查看密钥，把secret=XXX中的XXX替换成密钥，浏览器访问这个修改后的链接就可以正常使用了。
