### ISSUE TITLE
[Bug] 下载失败：【curl: (60) SSL certificate problem: self signed certificate More details here: https://curl.haxx.se/docs/sslcerts.html

### ISSUE THREAD

**Issue by lrs-960** [vernesong/OpenClash#3793]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [X] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [X] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

v0.46.003-beta

### Bug on Environment

Official OpenWrt

### OpenWrt Version

V2.36

### Bug on Platform

Linux-amd64(x86-64)

### Describe the Bug

1.通过提示自动下载内核失败，通过手动下载内核后，发现openClash并不会启动clash，日志提示下载失败
2.解析config.yaml失败，但是能查看订阅信息

### To Reproduce

安装后直接出现该问题

### OpenClash Log

```log
tmp/openclash_last_version】下载失败：【curl: (60) SSL certificate problem: self signed certificate More details here: https://curl.haxx.se/docs/sslcerts.html  curl failed to verify the legitimacy of the server and therefore could not establish a secure connection to it. To learn more about this situation and how to fix it, please visit the web page mentioned above
```

### Expected Behavior

正常使用

### Additional Context

![Uploading 屏幕截图 2024-03-10<img width="1631" alt="屏幕截图 2024-03-10 155507" src="https://github.com/vernesong/OpenClash/assets/65840470/bcf7f47c-ff0f-492a-aca9-9d2056e681af">

**Comment by lrs-960** [comment]
![Uploading 屏幕截图 2024-03-10 155424.png…]()

**Comment by lrs-960** [comment]
<img width="1604" alt="屏幕截图 2024-03-10 155424" src="https://github.com/vernesong/OpenClash/assets/65840470/2a151d31-db60-436c-b8cc-e6e1d322c342">

**Comment by wujun4code** [comment]
@lrs-960  你解决了吗？

**Comment by Nodewebzsz** [comment]
请问这个ssl的问题怎么解决的啊

**Comment by baijun9206** [comment]
我也遇到了，你有解决？

**Comment by nihaohellohola** [comment]
同样的问题，每天都来一次

**Comment by easyinplay** [comment]
解决了吗
