### ISSUE TITLE
[Bug] 订阅信息获取失败

### ISSUE THREAD

**Issue by cjlhll** [vernesong/OpenClash#3798]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [x] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [X] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [X] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

v0.46.003

### Bug on Environment

Lean

### OpenWrt Version

24.057.40909

### Bug on Platform

Linux-arm64

### Describe the Bug

订阅信息获取失败，最近一直这样，windows版本的clash客户端都正常的。

### To Reproduce

正常更新订阅，首页无法显示订阅信息。

### OpenClash Log

```log
见附件。
```

### Expected Behavior

首页能正常显示订阅信息。

**Comment by cjlhll** [comment]
无法上传文件呢。

**Comment by cjlhll** [comment]
[log.txt](https://github.com/vernesong/OpenClash/files/14565973/log.txt)
![QQ截图20240312090302](https://github.com/vernesong/OpenClash/assets/26736892/7fce9660-4680-4349-9d93-c3c8ec8afbb3)

**Comment by cjlhll** [comment]
订阅链接里是有response header里的流量信息的。但是就是不显示。

**Comment by FreedomC** [comment]
怎么解决呀？

**Comment by eeooeeooee** [comment]
同问

**Comment by FreedomC** [comment]
> 同问

我这边发现是订阅转换服务地址不可达的问题. 修改下/etc/hosts 文件，把ip解析加进去就好了。

# cat /etc/hosts

45.142.157.222 v.id9.cc
3.64.163.50 api.dier.io
104.218.235.103 sub.id9.cc

**Comment by eeooeeooee** [comment]
受到楼上的启发，知道了如何解决了。可能openclash是用curl命令而不是curl -L来获取header，倘若机场订阅链接出现了重定向，用curl命令测试订阅链接会报错301。可以看看机场配置文件是否有提供真正的订阅链接，用那个链接则可正确提示流量。

**Comment by Vtary** [comment]
> > 同问
> 
> 我这边发现是订阅转换服务地址不可达的问题. 修改下/etc/hosts 文件，把ip解析加进去就好了。
> 
> # cat /etc/hosts
> 45.142.157.222 v.id9.cc 3.64.163.50 api.dier.io 104.218.235.103 sub.id9.cc

Still not working for me anyway. Failed all the time.

**Comment by Vtary** [comment]
nameserver 223.5.5.5
nameserver 223.6.6.6
修改了DNS就解决了
可以正常获取订阅信息
![1715671796340](https://github.com/vernesong/OpenClash/assets/44052676/e6a1bc42-2acb-4192-8796-ca871b2912c4)

**Comment by SealinGp** [comment]
> 受到楼上的启发，我也解决了。可能openclash是用curl命令而不是curl -L来获取header，倘若机场订阅链接出现了重定向，用curl命令测试订阅链接会报错301。可以看看机场配置文件是否有提供真正的订阅链接，用那个链接订阅或指定从该链接获取订阅信息则可正确显示流量。

1.首先通过
```sh
curl -L 你的订阅链接 > 1.txt
``` 
2.查看1.txt中实际重定向的真实订阅链接 (在文件的开头）
<img width="633" alt="image" src="https://github.com/user-attachments/assets/82c8cea9-8c06-456a-ba65-efca1463b83f">
3.复制该链接，然后重新粘贴到你的订阅链接即可更新
