### ISSUE TITLE
[Feature] 在“流媒体增强”中增加“Bing非送中港”

### ISSUE THREAD

**Issue by WFANG12719** [vernesong/OpenClash#3799]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经**使用最新 Dev 版本**查看过，并不包含该功能特性或者还不完善
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 应包含的特性
- [ ] Contributors 我有能力协助 OpenClash 开发或完善此功能特性
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### Describe the Feature

Bing搜索目前强制跳转cn.bing.com，要将之转向海外（非港）只能全局。盼望能向Google那样非送中

### Describe Alternatives

修改UA，HTTP header均不管用，貌似只能全局到非港节点。

**Comment by WFANG12719** [comment]
> 你直接在规则里把bing.com以及或者微软服务全代理了不就好了

试过还真不行，不是打不开网站就是跳转到cn。微软网站用的这个清单：https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Microsoft.yaml

**Comment by LemonPAKA** [comment]
> > 你直接在规则里把bing.com以及或者微软服务全代理了不就好了
> 
> 试过还真不行，不是打不开网站就是跳转到cn。微软网站用的这个清单：https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Microsoft.yaml

![image](https://github.com/vernesong/OpenClash/assets/17202894/69892227-eb4d-4d5c-b273-4b52119d731e)
![image](https://github.com/vernesong/OpenClash/assets/17202894/644efee9-306a-47e1-b06f-3b76dfafa342)
我觉得是你的问题。。。

**Comment by WFANG12719** [comment]
@LemonPAKA ,兄台可否分享一下你的"微软服务"规则，我再试试改规则。

**Comment by Yuko1997** [comment]
`DOMAIN-SUFFIX,bing.com,Proxies
DOMAIN-SUFFIX,bing.net,Proxies
DOMAIN-SUFFIX,bingapis.com,Proxies`
我就这三条
