### ISSUE TITLE
[notBug] not use proxy for LAN

### ISSUE THREAD

**Issue by userosos** [vernesong/OpenClash#3800]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [X] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [X] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

0.46.003-beta

### Bug on Environment

Official OpenWrt

### OpenWrt Version

OpenWrt 23.05.2 r23630-842932a63d / LuCI openwrt-23.05 branch git-24.067.02086-146a8f1

### Bug on Platform

Other

### Describe the Bug

Hi! What i need do for OpenClsah not uses proxy for LAN?

### To Reproduce

Hi! What i need do for OpenClsah not uses proxy for LAN?

### OpenClash Log

```log
Hi! What i need do for OpenClsah not uses proxy for LAN?
```

### OpenClash Config

```shell
Hi! What i need do for OpenClsah not uses proxy for LAN?
```

### Expected Behavior

Hi! What i need do for OpenClsah not uses proxy for LAN?

### Additional Context

Hi! What i need do for OpenClsah not uses proxy for LAN?

**Comment by xrh0905** [comment]
Have you tried to change the `LAN Access Control Mode` to Whitelist?
