### ISSUE TITLE
Collected errors:  * pkg_hash_check_unresolved: cannot find dependency kernel (= 6.1.81-1-649ec23e52d6aedbeabb0e12b7ba402f) for kmod-nft-tproxy  * pkg_hash_fetch_best_installation_candidate: Packages for kmod-nft-tproxy found, but incompatible with the architectures configured  * opkg_install_cmd: Cannot install package kmod-nft-tproxy.

### ISSUE THREAD

**Issue by 1273294133** [vernesong/OpenClash#3805]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [ ] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

v0.46.003-beta

### Bug on Environment

Official OpenWrt, Docker

### OpenWrt Version

固件版本	OpenWrt SNAPSHOT r0-f7a6845 / LuCI Master git-24.069.76687-78d0c7e 内核版本	5.15.86-flippy-80+o

### Bug on Platform

Linux-armv7, Linux-arm64

### Describe the Bug

安装kmod-nft-tproxy报错内核版本不对
Collected errors:  * pkg_hash_check_unresolved: cannot find dependency kernel (= 6.1.81-1-649ec23e52d6aedbeabb0e12b7ba402f) for kmod-nft-tproxy  * pkg_hash_fetch_best_installation_candidate: Packages for kmod-nft-tproxy found, but incompatible with the architectures configured  * opkg_install_cmd: Cannot install package kmod-nft-tproxy.
强制安装kernel_6.1.81-1-649ec23e52d6aedbeabb0e12b7ba402f_aarch64_generic.ipk
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 6.1.81-1-86131da921e0ddda2f74d10cb3f4679b) for kmod-nfnetlink
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-nfnetlink found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 6.1.81-1-86131da921e0ddda2f74d10cb3f4679b) for kmod-nf-reject
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-nf-reject found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 6.1.81-1-86131da921e0ddda2f74d10cb3f4679b) for kmod-nf-reject6
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-nf-reject6 found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 6.1.81-1-86131da921e0ddda2f74d10cb3f4679b) for kmod-nf-conntrack
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-nf-conntrack found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 6.1.81-1-86131da921e0ddda2f74d10cb3f4679b) for kmod-nf-conntrack6
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-nf-conntrack6 found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 6.1.81-1-86131da921e0ddda2f74d10cb3f4679b) for kmod-nf-nat
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-nf-nat found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 6.1.81-1-86131da921e0ddda2f74d10cb3f4679b) for kmod-nf-log
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-nf-log found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 6.1.81-1-86131da921e0ddda2f74d10cb3f4679b) for kmod-nf-log6
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-nf-log6 found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 6.1.81-1-86131da921e0ddda2f74d10cb3f4679b) for kmod-crypto-hash
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-crypto-hash found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 6.1.81-1-86131da921e0ddda2f74d10cb3f4679b) for kmod-crypto-crc32c
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-crypto-crc32c found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 6.1.81-1-86131da921e0ddda2f74d10cb3f4679b) for kmod-lib-crc32c
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-lib-crc32c found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 6.1.81-1-86131da921e0ddda2f74d10cb3f4679b) for kmod-nft-core
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-nft-core found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 6.1.81-1-86131da921e0ddda2f74d10cb3f4679b) for kmod-nf-tproxy
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-nf-tproxy found, but incompatible with the architectures configured

### To Reproduce

opkg install kmod-nft-tproxy

### OpenClash Log

```log
还没到使用openclash这一步。。卡在了安装依赖。
```

### Expected Behavior

。。

**Comment by bcseputetto** [comment]
kmod 内核模块 需要和内核版本，内核vermagic一致才能被安装上，这不是openclash可以解决的事情。
要么固件编译时就带上这些模块，要么固件编译者自己提供kmod，而不是去使用openwrt官方的opkg软件源。
还有一种做法就是编译固件者使内核版本和内核vermagic和openwrt官方软件源提供的内核一致。
总之，不管是什么办法，这都不属于openclash该负责的范畴

**Comment by blacktail1937** [comment]
用的快照版本吗，好激进啊

**Comment by Karmylr** [comment]
@bcseputetto 我编译了一个固件，但是忘记加入一个kmod了。能不能在当时的编译目录下单独编译出ipk格式的kmod并安装？

**Comment by techkieflower** [comment]
我也遇到这个问题 ImmortalWrt SNAPSHOT r0-0f2088d / LuCI Master 25.026.34803~41c64f9
root@ImmortalWrt:~#  apk info kmod-nf-tproxy
kmod-nf-tproxy-6.6.74-r1 description:
Netfilter tproxy support
kmod-nf-tproxy-6.6.74-r1 webpage:
kmod-nf-tproxy-6.6.74-r1 installed size:
24 KiB

少了1个t，依赖检查不过，ipk装不上
