### ISSUE TITLE
[Bug] 获取的订阅节点不完整。

### ISSUE THREAD

**Issue by yjiawqgj** [vernesong/OpenClash#3806]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [X] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [X] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

v0.46.003-beta

### Bug on Environment

Lean, Other

### OpenWrt Version

23.346.45702-3e8eb4a

### Bug on Platform

Linux-amd64(x86-64)

### Describe the Bug

经常性断网，但是使用桌面clash verge却没有问题，检查后发现下载的配置文件不一样，订阅地址是同一个，clash verge的配置里有hy2协议的节点，而openclash里的配置却没有hy2节点，通过dev分支更新mata内核最新版本：alpha-gb3db113，删除订阅重新订阅依然缺少hy2节点。

### To Reproduce

没

### OpenClash Log

```log
已作为附件上传
```

### Expected Behavior

没

### Additional Context

[log.txt](https://github.com/vernesong/OpenClash/files/14613697/log.txt)

**Comment by zxlhhyccc** [comment]
> 经常性断网，但是使用桌面clash verge却没有问题，检查后发现下载的配置文件不一样，订阅地址是同一个，clash verge的配置里有hy2协议的节点，而openclash里的配置却没有hy2节点，通过dev分支更新mata内核最新版本：alpha-gb3db113，删除订阅重新订阅依然缺少hy2节点。

这个不是openclash的问题，是openclash里的订阅转换中没有这个功能导致，建议把节点手搓进配置文件。。。。或者建议V大添加可转换hy2配置的代码。。。。

**Comment by yjiawqgj** [comment]
> > 经常性断网，但是使用桌面clash verge却没有问题，检查后发现下载的配置文件不一样，订阅地址是同一个，clash verge的配置里有hy2协议的节点，而openclash里的配置却没有hy2节点，通过dev分支更新mata内核最新版本：alpha-gb3db113，删除订阅重新订阅依然缺少hy2节点。
> 
> 这个不是openclash的问题，是openclash里的订阅转换中没有这个功能导致，建议把节点手搓进配置文件。。。。或者建议V大添加可转换hy2配置的代码。。。。

但我没有使用订阅转换功能！我没有他的V号！

**Comment by help-eeeee** [comment]
![image](https://github.com/vernesong/OpenClash/assets/25654699/ff9f1448-cab3-4930-9ad9-31fe5a98edbb)

订阅设定里这一项可以尝试修改为 clash-verge/v1.5.8 让服务器觉得是Clash verge拉取的

**Comment by yjiawqgj** [comment]
> ![image](https://private-user-images.githubusercontent.com/25654699/313926952-ff9f1448-cab3-4930-9ad9-31fe5a98edbb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MjUxMTcsIm5iZiI6MTcxMDgyNDgxNywicGF0aCI6Ii8yNTY1NDY5OS8zMTM5MjY5NTItZmY5ZjE0NDgtY2FiMy00OTMwLTlhZDktMzFmZTVhOThlZGJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDA1MDY1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhYTdhNDIwZWFmMmQ3OTk3YTE2N2U1ZDM4MTdjZmIzNTg0ZDhkNWNjNDdmOWM0ZjBiODc2NDQ1OGE3ZGFlZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fpLfDqn4uckF-G1Vm7ZyDfnJM1-lYC1VPa2fHsIX1Zg)
> 
> 订阅设定里这一项可以尝试修改为 clash-verge/v1.5.8 让服务器觉得是Clash verge拉取的

在订阅链接后增加后缀解决问题了。

**Comment by FreedomC** [comment]
> > ![image](https://private-user-images.githubusercontent.com/25654699/313926952-ff9f1448-cab3-4930-9ad9-31fe5a98edbb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MjUxMTcsIm5iZiI6MTcxMDgyNDgxNywicGF0aCI6Ii8yNTY1NDY5OS8zMTM5MjY5NTItZmY5ZjE0NDgtY2FiMy00OTMwLTlhZDktMzFmZTVhOThlZGJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDA1MDY1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhYTdhNDIwZWFmMmQ3OTk3YTE2N2U1ZDM4MTdjZmIzNTg0ZDhkNWNjNDdmOWM0ZjBiODc2NDQ1OGE3ZGFlZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fpLfDqn4uckF-G1Vm7ZyDfnJM1-lYC1VPa2fHsIX1Zg)
> > 订阅设定里这一项可以尝试修改为 clash-verge/v1.5.8 让服务器觉得是Clash verge拉取的
> 
> 在订阅链接后增加后缀解决问题了。

请问怎么样增加后缀呀？

**Comment by RavenCage** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/25654699/313926952-ff9f1448-cab3-4930-9ad9-31fe5a98edbb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MjUxMTcsIm5iZiI6MTcxMDgyNDgxNywicGF0aCI6Ii8yNTY1NDY5OS8zMTM5MjY5NTItZmY5ZjE0NDgtY2FiMy00OTMwLTlhZDktMzFmZTVhOThlZGJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDA1MDY1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhYTdhNDIwZWFmMmQ3OTk3YTE2N2U1ZDM4MTdjZmIzNTg0ZDhkNWNjNDdmOWM0ZjBiODc2NDQ1OGE3ZGFlZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fpLfDqn4uckF-G1Vm7ZyDfnJM1-lYC1VPa2fHsIX1Zg)
> > > 订阅设定里这一项可以尝试修改为 clash-verge/v1.5.8 让服务器觉得是Clash verge拉取的
> > 
> > 
> > 在订阅链接后增加后缀解决问题了。
> 
> 请问怎么样增加后缀呀？

在token末尾加上&types=hysteria2就可以拉取到hy2节点了。

**Comment by FreddieLu** [comment]
> ![image](https://private-user-images.githubusercontent.com/25654699/313926952-ff9f1448-cab3-4930-9ad9-31fe5a98edbb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0Mzk5MjcsIm5iZiI6MTczMDQzOTYyNywicGF0aCI6Ii8yNTY1NDY5OS8zMTM5MjY5NTItZmY5ZjE0NDgtY2FiMy00OTMwLTlhZDktMzFmZTVhOThlZGJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDA1NDAyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiZjhlZjQ0YWU1NTgyZWE0OTg1YTQ4MTU0MmZiOTVjMTVhYjllOGUzMDE3NGY3NmNjNzIxMjc2MTgzZmE5YmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.892c0RxxqU4qXJl2GikStdHkSdCJwDpoErsOT5sY4oc)
> 
> 订阅设定里这一项可以尝试修改为 clash-verge/v1.5.8 让服务器觉得是Clash verge拉取的

我的openclash这里只有Clash和clash.meta两项，应该在自定义里加入吗？
