### ISSUE TITLE
[Bug] redir-host DNS机制

### ISSUE THREAD

**Issue by AllForLandlord** [vernesong/OpenClash#3809]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [X] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

	v0.46.003-beta

### Bug on Environment

Immortalwrt

### OpenWrt Version

ImmortalWrt 23.05.1 r27304-31bc47589e

### Bug on Platform

Linux-arm64

### Describe the Bug

想请教下，redir-host现版本对于DNS的请求的流程。
之前的openclash版本里我记得可以选择是否远程解析DNS服务器，后来某次更新取消了这个选项。

我的疑问是，在**Meta内核**下：
1. redir-host下无论是否**命中域名规则走了代理**，都会进行DNS解析吗？好像fake-ip模式命中代理的域名规则就不会本地进行DNS解析了？
2. redir-host下DNS解析出IP后如果需要代理，会复用本地DNS解析的结果吗？
3. redir-host下比如DNS解析出是0.0.0.0，而我没启用fallback服务器，但是该网站能匹配到域名规则走代理，此时会怎么运作？

### To Reproduce

无

### OpenClash Log

```log
无
```

### Expected Behavior

麻烦大佬们解惑，非常感谢！

**Comment by vernesong** [comment]
1、是
2、会
3、污染，可以启用fallback和fallback-filter规避

**Comment by AllForLandlord** [comment]
> 1、是 2、会 3、污染，可以启用fallback和fallback-filter规避

谢谢解答疑惑，关于第二个问题，我用腾讯阿里的DNS，解析出的被墙的域名的IP肯定是被污染的，如果复用结果那我应该不能正常代理，然而我还是能正常代理，请问这是为什么？

**Comment by vernesong** [comment]
meta内核没有完全遵循这个逻辑，考虑到容易污染，后来改成域名匹配到了就走远程解析
