### ISSUE TITLE
[Feature] 希望能添加自定义控制面板登录密钥的功能，或者能告诉我在覆写设置的开发者选项中应该使用什么命令？

### ISSUE THREAD

**Issue by wy19xx** [vernesong/OpenClash#3815]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经**使用最新 Dev 版本**查看过，并不包含该功能特性或者还不完善
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 应包含的特性
- [X] Contributors 我有能力协助 OpenClash 开发或完善此功能特性
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### Describe the Feature

如题，我有在覆写设置的开发者选项中尝试过命令：
ruby_edit "$CONFIG_FILE" "['secret']" "xxxxxx"
和命令：
uci -q set openclash.config.dashboard_password="xxxxxx"
但重启openwrt后发现登录密钥并未生效，还是自动在生成

**Comment by vernesong** [comment]
你换个固件，你的固件每次重启都在执行default脚本，这是不正常行为

**Comment by wy19xx** [comment]
换了固件，运行正常。
