### ISSUE TITLE
[Bug] Fake-IP 模式下 防火墙转发 进行客户端访问控制不起作用

### ISSUE THREAD

**Issue by guidocn** [vernesong/OpenClash#3817]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [X] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [X] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

v0.46.003-beta

### Bug on Environment

Istoreos

### OpenWrt Version

最新

### Bug on Platform

Linux-arm64

### Describe the Bug

Fake-IP 模式下 防火墙转发 进行客户端访问控制不起作用

### To Reproduce

Fake-IP 模式下 防火墙转发 进行客户端访问控制不起作用

### OpenClash Log

```log
Fake-IP 模式下 防火墙转发 进行客户端访问控制不起作用
```

### Expected Behavior

Fake-IP 模式下 防火墙转发 进行客户端访问控制不起作用

**Comment by no1sjc** [comment]
istoreos 此版本遇见相同问题，
iStoreOS 22.03.6 2024031514 / LuCI istoreos-22.03 branch git-24.057.30647-6659faa


<br class="Apple-interchange-newline">

**Comment by vernesong** [comment]
iStoreOS 22.03.6 2024031514 / LuCI istoreos-22.03 branch git-24.057.30647-6659faa
![image](https://github.com/vernesong/OpenClash/assets/42875168/20eb491d-661c-4922-8760-e4d73f8cb3fa)

我这边测试没问题

**Comment by guidocn** [comment]
我这边现在用覆写规则的规则设置可以解决到指定的内网不走代理
![guido2024-03-26_20-07-54](https://github.com/vernesong/OpenClash/assets/75555539/472ef3fe-fe68-4bb1-9d7f-6cd0af08599a)

**Comment by guidocn** [comment]
不过现在又出现了另外一个问题 就是每次我打完穿越火线之后 openclash可以ping通google 但是就是无法访问 另外国内我尝试抖音看直播也加载不出来
