### ISSUE TITLE
[Bug] 安装OpenClash首次启动后无法正常添加接口Link-Local IPv6地址

### ISSUE THREAD

**Issue by Muska-Ami** [vernesong/OpenClash#3819]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [ ] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

v0.46.003-beta

### Bug on Environment

Istoreos

### OpenWrt Version

iStoreOS 22.03.6 2024030112

### Bug on Platform

Linux-arm64

### Describe the Bug

在首次启动了OpenClash后，我发现我的bird BGP Session全部断开，反复排查发现无法正常添加Link-Local IPv6地址，尝试关闭了OpenClash，发现依然无法正常添加

### To Reproduce

1. 安装并启动OpenClash
2. 使用 `ip addr add` 向接口添加Link-Local IPv6地址：
   ```sh
   root@MAR2S:~# ip addr add fe80::101/64 dev dn42_ASxxxxxx
   RTNETLINK answers: Permission denied
   ```

### OpenClash Log

```log
https://paste.fastmirror.net/?9df565ab0da524d8#A3ykami2KsJphTz5B9Cs1MzfXcPPCRwnwRcLcvoAVB9G
```

### Expected Behavior

希望能正常添加Link-Local IPv6地址。。。这个问题导致我的DN42 Peer全部断开连接

**Comment by vernesong** [comment]
```
ip -6 link set dn42_ASxxxxxx down
ip -6 addr add fe80::101/64 dev dn42_ASxxxxxx

**Comment by vernesong** [comment]
那你先把utun删了呢，或者还原重装，等接口状态up了在添加地址，还没有碰到过干扰其他接口启动的情况

**Comment by Muska-Ami** [comment]
utun删过了，貌似不行还原重装的话我配置的东西有点多。。。不太好整From: ***@***.*** ***@***.***> on behalf of vernesong ***@***.***>Sent: Thursday, March 21, 2024 12:16:07 PMTo: OpenClash ***@***.***>Cc: 2549619802 ***@***.***>; author ***@***.***>Subject: Re: [vernesong/OpenClash] [Bug] 安装OpenClash首次启动后无法正常添加接口Link-Local IPv6地址 (Issue #3819)
那你先把utun删了呢，或者还原重装，等接口状态up了在添加地址，还没有碰到过干扰其他接口启动的情况

**Comment by vernesong** [comment]
你要看一下接口是否能够正常启动，因为同样是创建接口，uu加速器插件就没问题

**Comment by Muska-Ami** [comment]
LuCI上面显示是正常启动了

FROM 夏沫花火zzz🌙(Muska_Ami)
This letter was send by a human, not auto send.
________________________________

**Comment by vernesong** [comment]
暂无解决思路

**Comment by Muska-Ami** [comment]
目前把OpenClash和bird放在不同路由上暂时解决，对于无法操作添加链路地址这个还没有头绪
