### ISSUE TITLE
[Bug] DNS策略转发不正常

### ISSUE THREAD

**Issue by willxucn** [vernesong/OpenClash#3821]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [ ] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

v0.46.003-beta

### Bug on Environment

Official OpenWrt

### OpenWrt Version

OpenWrt 23.05.2 r23630-842932a63d

### Bug on Platform

Linux-amd64(x86-64)

### Describe the Bug

目前客户端电脑直连openwrt，FQ功能全部正常，但是内网有专门的dns服务器10.101.11.21，用于解析内网设备的域名（假设内网domain为 aaa.com），内网解析地址应为 10.X.X.X。
目前在dns覆写设置-dns设置-Nameserver-Policy 上增加策略
‘aaa.com’: '10.101.11.21'

测试如下：
1、客户端电脑，nslookup指定server为10.101.11.21，可以得到正确解析结果 10.X.X.X
2、ssh到openwrt的命令行，执行 dig aaa.com @10.101.11.21 解析也正确，得到 10.X.X.X
3、但是在客户端电脑，nslookup指定server为openwrt，aaa.com 找不到记录

如果aaa.com在公网dns上，具备公网ip解析记录，那么删除DNS策略转发的策略后，同样测试，结果如下：
1、客户端电脑，nslookup指定server为10.101.11.21，可以得到内网解析结果 10.X.X.X
2、ssh到openwrt的命令行，执行 dig aaa.com @10.101.11.21 得到内网解析结果 10.X.X.X
3、在客户端电脑，nslookup指定server为openwrt，aaa.com 得到公网ip

后来试了一下：去掉Nameserver-Policy后，直接在openwrt的dnsmasq设置上面增加，然后重启openclash，似乎dnsmasq被接管了，也没有正常转发。

目前系统的 dnsmasq-full版本为2.90-1

### To Reproduce

虚拟机上直接安装 OpenWrt 23.05.2 r23630-842932a63d
做完基础LAN WAN网络配置以后，直接安装v0.46.003-beta，导入机场的配置，就出现这个问题

### OpenClash Log

```log
运行日志上没有任何错误。
```

### Expected Behavior

正常按设置转发

**Comment by willxucn** [comment]
除了导入机场数据，其他工作模式redir这些全部默认。

**Comment by willxucn** [comment]
刚刚偶然在/var/dnsmasq.d下面发现openclash添加的自定义解析文件，内容是
server=/aaa.com/114.114.114.114
server=/+.aaa.com/114.114.114.114

但是我从来就没有指定过114服务器啊！！我之前写入的时候，最后是10.101.11.21，不知道为啥这里出现114的情况

**Comment by willxucn** [comment]
刚刚尝试通过openclash的第二dns进行设置，完成后，发现
/var/dnsmasq.d 目录下生成了 dnsmasq_openclash_custom_domain.conf
内容是
server=/aaa.com/10.101.11.21

但是故障依旧啊

**Comment by 42thcoder** [comment]
我似乎碰到了一样的问题

**Comment by vernesong** [comment]
![image](https://github.com/vernesong/OpenClash/assets/42875168/dcb1c774-5b00-4e17-bdec-092f4b7bc010)

**Comment by abc582915847** [comment]
把openclash 默认的dns 换成mosdns 性能杠杠滴，CPU负载过高问题也解决了
