### ISSUE TITLE
[Bug] 最新的Meta内核导致Hy2节点无响应

### ISSUE THREAD

**Issue by josenzhong** [vernesong/OpenClash#3826]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [X] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [X] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

v0.45.157-beta

### Bug on Environment

Other

### OpenWrt Version

OpenWrt Li [2023]GDQ v7.5 Compiled by Li / LuCI Master (git-23.346.45702-3e8eb4a)

### Bug on Platform

Linux-arm64

### Describe the Bug

刚刚更新了最新Arm64 版本的Meta内核(alpha-gfeedc9e)导致注册机场的Hy2节点无响应。想换回旧版本的Meta内核，但是找不到。
<img width="771" alt="image" src="https://github.com/vernesong/OpenClash/assets/11269628/5e069c6c-4e16-4248-81f2-6ee50db4e81b">

### To Reproduce

主机名 | Photonicat
-- | --
型号 | Rockchip RK3568 photonicat Linux Board
架构 | ARMv8 Processor x 1
固件版本 | photonicatWrt R23.10.1 / LuCI Master (git-23.289.13355-67c2cb7)
内核版本 | 6.1.56

### OpenClash Log

```log
2024-03-24 04:05:47 警告：OpenClash 启动成功，检测到您启用了IPv6的DHCP服务，可能会造成连接异常！
2024-03-24 04:05:47 第九步: 添加计划任务,启动进程守护程序...
2024-03-24 04:05:43 第八步: 重启 Dnsmasq 程序...
2024-03-24 04:05:43 提示：开始添加自定义防火墙规则...
2024-03-24 04:05:43 提示：正在根据防火墙端口转发和防火墙通信规则添加端口绕过规则...
2024-03-24 04:05:42 提示：DNS 劫持模式为 Dnsmasq 转发...
2024-03-24 04:05:42 第七步: 设置防火墙规则...
2024-03-24 04:05:42 第六步: 等待主程序下载外部文件...
2024-03-24 04:05:38 第五步: 检查内核启动状态...
2024-03-24 04:05:37 配置文件【/etc/openclash/xxx.yaml】测试成功...
2024-03-24 04:05:35 启动前调用内核测试配置文件...
2024-03-24 04:05:35 提示：检测到配置了 Meta 内核专属功能，调用 Meta 内核启动...
2024-03-24 04:05:35 第四步: 启动主程序...
2024-03-24 04:05:35 提示：开始运行自定义覆写脚本...
2024-03-24 04:05:30 第三步: 修改配置文件...
2024-03-24 04:05:29 第二步: 组件运行前检查...
2024-03-24 04:05:28 第一步: 获取配置...
2024-03-24 04:05:28 OpenClash 开始启动...
```

### Expected Behavior

无法正常连接Hy2节点

**Comment by Rangtian** [comment]
同。

**Comment by zjgtree** [comment]
同样手贱升级后hy2机场全红了

**Comment by xpn282** [comment]
不知道为什么那么重大的bug那么多天还没修复。。。。。

**Comment by josenzhong** [comment]
怎么还不更新Meta内核版本？

**Comment by ashton2914** [comment]
我用meta内核v1.18.3 hysteria2是没问题的。建议去手动下载mihomo最新的正式版内核手动替换一下

**Comment by lfinexr** [comment]
什么时候能发布正常连接Hy2节点的版本啊？

**Comment by CJSen** [comment]
> 我用meta内核v1.18.3 hysteria2是没问题的。建议去手动下载mihomo最新的正式版内核手动替换一下

我手动替换了1.18.3的meta内核，也还是不行。看日志显示的都是配置文件问题，订阅拉取不下来。但是clash_verge是可以正常使用该订阅的。所以不清楚是订阅问题，还是meta内核，还是openclash问题。

**Comment by lfinexr** [comment]
----- 原始邮件 -----
发件人：CJSen ***@***.***>
收件人：vernesong/OpenClash ***@***.***>
抄送人：lfinexr ***@***.***>,  Comment ***@***.***>
主题：Re:_[vernesong/OpenClash]_[Bug]_最新的Meta内核导致Hy2节点无响应_(Issue_#3826)
日期：2024年05月07日 12点59分



我用meta内核v1.18.3 hysteria2是没问题的。建议去手动下载mihomo最新的正式版内核手动替换一下

我手动替换了1.18.3的meta内核，也还是不行。看日志显示的都是配置文件问题，订阅拉取不下来。但是clash_verge是可以正常使用该订阅的。所以不清楚是订阅问题，还是meta内核，还是openclash问题。

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.
多谢回复！我用windows版的clash_verge连接Hy2也是没问题的，但OpenWrt下的OpenClash就不行。本人小白一个，不懂得如何手动替换meta内核，也不知道去哪里找可用的meta内核文件，只能指望最新版本的内核更新了。再次多谢！Message ID: ***@***.***>

**Comment by Atlas52306** [comment]
更新v1.18.4 内核 配置管理里编辑配置文件订阅信息 自行转换

**Comment by ashakii** [comment]
> 更新v1.18.4 内核 配置管理里编辑配置文件订阅信息 自行转换，就何以使用H2啦

请问一下"自行转换"是怎么操作的啊?求教

**Comment by Atlas52306** [comment]
> > 更新v1.18.4 内核配置管理里编辑配置文件订阅信息自行转换，就怎么用H2啦
> 
> 请问一下“手机转换”是怎么操作的啊？求教
![image](https://github.com/vernesong/OpenClash/assets/169112183/4992e02b-fbef-4ae1-85b1-e75aedf27995)
[下载内核](https://github.com/MetaCubeX/mihomo/releases/tag/v1.18.4) 并上传
配置订阅-新增-新增配置文件订阅信息
1.填写订阅地址
2.User-Agent 指定clash meta
3.剩余....懒得写看图把
![image](https://github.com/vernesong/OpenClash/assets/169112183/2a9fab11-7ca8-42d3-80da-c90dbcfcd42d)
emm，转换随便写，但是转换完成需要看下 支不支持hy2
直接保存
4.更新配置
ps：更新配置之后再看是不是支持hy2

**Comment by zhangweibo413** [comment]
我也遇到类似问题，去mihomo手工下载 alpha-fe88f0e，替换后立刻正常

**Comment by lfinexr** [comment]
我在下载alpha-fe88f0e时浏览器提示“无法下载-检测到病毒”？

**Comment by Atlas52306** [comment]
这就是常识性问题了，建议你多看看浏览器的说明





我在下载alpha-fe88f0e时浏览器提示“无法下载-检测到病毒”？

**Comment by lfinexr** [comment]
> 这就是常识性问题了，建议你多看看浏览器的说明 我在下载alpha-fe88f0e时浏览器提示“无法下载-检测到病毒”？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

在windows保护历史记录中可以查到检测到“Trojan:Win32/Mirai!ml”，

**Comment by Atlas52306** [comment]
> > 这就是常识性问题了，建议你多看看浏览器的说明 我在下载alpha-fe88f0e时浏览器提示“无法下载-检测到病毒”？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> 
> 在windows保护历史记录中可以查到检测到“Trojan:Win32/Mirai!ml”，

首先呢是这是个开源项目，如果觉得有问题你可以自行编译，又或者查看作者源代码，如果你发现啥你也可以公布出来啊。实在不行你还是觉得有问题你可以不使用....我们也不是作者...只是遇到问题解决了帮大家答疑了一下

**Comment by lfinexr** [comment]
> > > 这就是常识性问题了，建议你多看看浏览器的说明 我在下载alpha-fe88f0e时浏览器提示“无法下载-检测到病毒”？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> > 
> > 
> > 在windows保护历史记录中可以查到检测到“Trojan:Win32/Mirai!ml”，
> 
> 首先呢是这是个开源项目，如果觉得有问题你可以自行编译，又或者查看作者源代码，如果你发现啥你也可以公布出来啊。实在不行你还是觉得有问题你可以不使用....我们也不是作者...只是遇到问题解决了帮大家答疑了一下

我也是觉得挺奇怪的，所以想问问其他人是否遇到同样问题，并没有其他意思。在另一台电脑上下载就没再遇到这个问题了。大概是前一台电脑防病毒数软件据库出问题了吧？

**Comment by 286615275** [comment]
> > > > 这就是常识性问题了，建议你多看看浏览器的说明 我在下载alpha-fe88f0e时浏览器提示“无法下载-检测到病毒”？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> > > 
> > > 
> > > 在windows保护历史记录中可以查到检测到“Trojan:Win32/Mirai!ml”，
> > 
> > 
> > 首先呢是这是个开源项目，如果觉得有问题你可以自行编译，又或者查看作者源代码，如果你发现啥你也可以公布出来啊。实在不行你还是觉得有问题你可以不使用....我们也不是作者...只是遇到问题解决了帮大家答疑了一下
> 
> 我也是觉得挺奇怪的，所以想问问其他人是否遇到同样问题，并没有其他意思。在另一台电脑上下载就没再遇到这个问题了。大概是前一台电脑防病毒数软件据库出问题了吧？

跳过证书验证，ip+sni 必须skip-cert-verify: true才能连接

**Comment by wgwi007** [comment]
> 我也遇到类似问题，去mihomo手工下载 alpha-fe88f0e，替换后立刻正常

在哪下啊，没找到fe88f0e
