### ISSUE TITLE
[Bug] 开启clash后，华为体脂秤无法配对联网，其他设备都正常。

### ISSUE THREAD

**Issue by Hdmxmf0530** [vernesong/OpenClash#3827]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [ ] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [x] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

v0.46.003

### Bug on Environment

Immortalwrt

### OpenWrt Version

 ImmortalWrt 21.02-SNAPSHOT r0-e1b4487

### Bug on Platform

Linux-armv7, Other

### Describe the Bug

开启clash后，华为体脂秤无法配对联网，其他设备都正常。抓包发现开启clash后，体脂秤一直在请求dns
![错误](https://github.com/vernesong/OpenClash/assets/165108720/5152ba42-eb35-46c8-bf37-17001f33d7d7)
![正常](https://github.com/vernesong/OpenClash/assets/165108720/c950390e-c160-41bd-a1a9-e92f41608bd9)

### To Reproduce

开启clash后华为体脂秤配对联网失败，关闭clash后可以正常使用

### OpenClash Log

```log
请见附件
```

### Expected Behavior

请问如何解决这个问题

### Additional Context

[log.txt](https://github.com/vernesong/OpenClash/files/14766398/log.txt)

**Comment by vernesong** [comment]
黑名单排除掉

**Comment by Hdmxmf0530** [comment]
> 黑名单排除掉

尝试过通过黑名单排除终端IP，但是没有生效，故障依旧。
<img width="841" alt="黑名单" src="https://github.com/vernesong/OpenClash/assets/165108720/00008aea-30c6-4765-8e4c-8dffcd53295c">

**Comment by vernesong** [comment]
那就是dns有问题，你可以试试写host

**Comment by teli5200** [comment]
我也有这个问题，加入排除名单后没有任何效果。。。。

**Comment by teli5200** [comment]
请问最后是怎么处理的，谢谢

**Comment by vernesong** [comment]
可以试试防火墙转发DNS，再把设备加入黑名单

**Comment by teli5200** [comment]
fake 模式下貌似没办法设置黑名单，我一会切换模式试试

**Comment by teli5200** [comment]
> 可以试试防火墙转发DNS，再把设备加入黑名单

这样试了真的可以，哈哈，不错，多谢
