### ISSUE TITLE
[Bug] 我现在用的最新的clash，现在有一个问题。我用群晖QB下载PT，流量一直走的是我机场的。

### ISSUE THREAD

**Issue by 1314Kissy** [vernesong/OpenClash#3828]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [X] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [X] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

111111

### Bug on Environment

Official OpenWrt

### OpenWrt Version

OpenWrt_x64_全功能版 by GXNAS build 2024.01.12 @ OpenWrt R23.11.11 / Lede - 18.06

### Bug on Platform

Linux-mips64

### Describe the Bug

我现在用的最新的clash，现在有一个问题。我用群晖QB下载PT，流量一直走的是我机场的，流量走的很快。这个如何设置的。PT下载走我代理流量呢。我群晖也设置到不走代理流量里面了。

### To Reproduce

1

### OpenClash Log

```log
1
```

### OpenClash Config

```shell
111111
```

### Expected Behavior

111111

### Additional Context

11111

**Comment by S0MEW0LF** [comment]
OpenClash—》插件设置—》流量控制
仅允许常用端口流量：默认常用端口

**Comment by blacktail1937** [comment]
我是开了仅允许常用端口流量，然后把qb那个机器的dst_port>5000的全部直连，基本杜绝了大部分链接偷跑机场流量，还有小部分访问tracker的时候会走机场，不过产生的流量也微乎其微了。

**Comment by mjyhj** [comment]
> 我是开了仅允许常用端口流量，然后把qb那个机器的dst_port>5000的全部直连，基本杜绝了大部分链接偷跑机场流量，还有小部分访问tracker的时候会走机场，不过产生的流量也微乎其微了。

建议qb或者tr使用docker部署，网络用macvlan，独立一个IP，openclash里设置IP直连

**Comment by hong0980** [comment]
> > 我是开了仅允许常用端口流量，然后把qb那个机器的dst_port>5000的全部直连，基本杜绝了大部分链接偷跑机场流量，还有小部分访问tracker的时候会走机场，不过产生的流量也微乎其微了。
> 
> 建议qb或者tr使用docker部署，网络用macvlan，独立一个IP，openclash里设置IP直连

如果pt是nas，应该怎么能？

**Comment by Nothend** [comment]
> > 我是开了仅允许常用端口流量，然后把qb那个机器的dst_port>5000的全部直连，基本杜绝了大部分链接偷跑机场流量，还有小部分访问tracker的时候会走机场，不过产生的流量也微乎其微了。
> 
> 建议qb或者tr使用docker部署，网络用macvlan，独立一个IP，openclash里设置IP直连

谢谢这位兄弟提供了不错的思路，我把qb按照macvlan进行了重建。pt确实不走流量了。但是有一个问题，就是openclash中使用“- SRC-IP-CIDR,10.0.0.211/32,DIRECT #不走代理” 这个语句，确实是直连了。但是日志有大量的警告信息、连接中也有这个ip的信息。就是能不能直接不走clash呢？
