### ISSUE TITLE
[Bug] 源码编译拉取仓库太大，远超30G，建议缩小一下仓库或者修改一下首页的拉取代码示例

### ISSUE THREAD

**Issue by luoei** [vernesong/OpenClash#3833]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [ ] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

master

### Bug on Environment

Official OpenWrt

### OpenWrt Version

master

### Bug on Platform

All

### Describe the Bug

build@build:~/openwrt/loongarch/openwrt/package/luci-app-openclash$ git remote add -f origin https://github.com/vernesong/OpenClash.git
Updating origin
remote: Enumerating objects: 33119, done.
remote: Counting objects: 100% (72/72), done.
remote: Compressing objects: 100% (72/72), done.
Receiving objects:  29% (9842/33119), 10.06 GiB | 16.38 MiB/s

### To Reproduce

已源码方式编译

### OpenClash Log

```log
无
```

### OpenClash Config

```shell
无
```

### Expected Behavior

减小拉起仓库包的大小

### Additional Context

无

**Comment by Unwillingx** [comment]
git clone --depth=1 https://github.com/vernesong/OpenClash.git，仅拉取最新提交

**Comment by luoei** [comment]
> git clone --depth=1 [https://github.com/vernesong/OpenClash.git，仅拉取最新提交](https://github.com/vernesong/OpenClash.git%EF%BC%8C%E4%BB%85%E6%8B%89%E5%8F%96%E6%9C%80%E6%96%B0%E6%8F%90%E4%BA%A4)

这个可以。希望作者把这个命令更新到readme中。
