### ISSUE TITLE
[Bug] 日志中只有ip，没有域名

### ISSUE THREAD

**Issue by hccz95** [vernesong/OpenClash#3848]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [ ] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

0.46.003-beta

### Bug on Environment

Official OpenWrt

### OpenWrt Version

OpenWrt 23.05.2 r23630-842932a63d

### Bug on Platform

Linux-mipsle-hardfloat

### Describe the Bug

无法按照规则正常转发，查看日志发现，所有访问都只有ip地址，没有域名，但是规则是按域名分流的，所以无法进行匹配

### To Reproduce

正常启动openclash，然后在电脑上访问特定网站

### OpenClash Log

```log
2024-04-14 22:47:02 level=info msg="[TCP] 192.168.1.249:58859 --> 104.18.32.115:443 match Match using MATCH[DIRECT]"
2024-04-14 22:47:00 level=info msg="[TCP] 192.168.1.249:58858 --> 123.56.37.133:80 match GeoIP(cn) using DIRECT"
2024-04-14 22:46:58 level=warning msg="[TCP] dial MATCH (match Match/) 192.168.1.249:58847 --> 159.106.121.75:443 error: connect failed: dial tcp 159.106.121.75:443: i/o timeout"
2024-04-14 22:46:58 level=warning msg="[TCP] dial MATCH (match Match/) 192.168.1.249:58846 --> 159.106.121.75:443 error: connect failed: dial tcp 159.106.121.75:443: i/o timeout"
2024-04-14 22:46:57 level=info msg="[TCP] 192.168.1.249:58853 --> 39.97.141.111:80 match GeoIP(cn) using DIRECT"
2024-04-14 22:46:57 level=info msg="[TCP] 192.168.1.249:58852 --> 31.13.85.2:443 match IPCIDR(31.13.64.0/18) using Proxy[深港专线转香港BGP9[M][倍率:2.5]]"
2024-04-14 22:46:56 level=info msg="[TCP] 192.168.1.249:58850 --> 120.133.65.233:443 match GeoIP(cn) using DIRECT"
2024-04-14 22:46:55 level=info msg="[TCP] 192.168.1.249:58849 --> 123.56.37.133:80 match GeoIP(cn) using DIRECT"
2024-04-14 22:46:52 level=info msg="[TCP] 192.168.1.249:58843 --> 23.47.50.182:80 match Match using MATCH[DIRECT]"
2024-04-14 22:46:52 level=info msg="[TCP] 192.168.1.249:58842 --> 23.47.50.182:80 match Match using MATCH[DIRECT]"
2024-04-14 22:46:51 level=info msg="[TCP] 192.168.1.249:58845 --> 39.97.141.111:80 match GeoIP(cn) using DIRECT"
2024-04-14 22:46:48 level=info msg="[TCP] 192.168.1.249:58840 --> 123.56.37.132:80 match GeoIP(cn) using DIRECT"
2024-04-14 22:46:47 level=info msg="[TCP] 192.168.1.249:58839 --> 20.219.237.180:80 match Match using MATCH[DIRECT]"
```

### Expected Behavior

openclash能正确按照域名进行分流

**Comment by xiandu999-yu** [comment]
是不是像这样？
![322116522-82d263dc-26e3-4a3d-a290-529b9887adcf](https://github.com/vernesong/OpenClash/assets/58256481/03967995-de6f-4dfe-850d-99bd2ee65030)

**Comment by madman43** [comment]
> 是不是像这样？ ![322116522-82d263dc-26e3-4a3d-a290-529b9887adcf](https://private-user-images.githubusercontent.com/58256481/322850062-03967995-de6f-4dfe-850d-99bd2ee65030.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MTIwNDgsIm5iZiI6MTcxMzUxMTc0OCwicGF0aCI6Ii81ODI1NjQ4MS8zMjI4NTAwNjItMDM5Njc5OTUtZGU2Zi00ZGZlLTg1MGQtOTliZDJlZTY1MDMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDA3MjkwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiNjJkMzQ5MWU5ZWEzOGU0ZjI0ZTdiODAwNDU2NzhmMDJjYzFmNGJiNjljNzExMzM1NDhlZjA4M2U3ZmJmZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gl4RQ8dgStbAyYCTmznuZQnMmZN64E0MwggMbIYnfHc)

我也是这样了，前两天刚出现的情况，不知道咋回事

**Comment by hccz95** [comment]
> 是不是像这样？ ![322116522-82d263dc-26e3-4a3d-a290-529b9887adcf](https://private-user-images.githubusercontent.com/58256481/322850062-03967995-de6f-4dfe-850d-99bd2ee65030.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MTkyNjUsIm5iZiI6MTcxMzUxODk2NSwicGF0aCI6Ii81ODI1NjQ4MS8zMjI4NTAwNjItMDM5Njc5OTUtZGU2Zi00ZGZlLTg1MGQtOTliZDJlZTY1MDMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDA5MjkyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0M2EzZGIzMzk2ODNlYWZjZjkyODVlMGMyMGJmM2RjNTM1ZjI4ZjljNjc3Yzk2YmYzNmVmYTYxOGRiNWJiOTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BzgpAoDrdorXNy5GoI32G8agJ7eLE_rba5xbn9seWRc)

是这样！

**Comment by xiandu999-yu** [comment]
> > 是不是像这样？ ![322116522-82d263dc-26e3-4a3d-a290-529b9887adcf](https://private-user-images.githubusercontent.com/58256481/322850062-03967995-de6f-4dfe-850d-99bd2ee65030.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MTkyNjUsIm5iZiI6MTcxMzUxODk2NSwicGF0aCI6Ii81ODI1NjQ4MS8zMjI4NTAwNjItMDM5Njc5OTUtZGU2Zi00ZGZlLTg1MGQtOTliZDJlZTY1MDMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDA5MjkyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0M2EzZGIzMzk2ODNlYWZjZjkyODVlMGMyMGJmM2RjNTM1ZjI4ZjljNjc3Yzk2YmYzNmVmYTYxOGRiNWJiOTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BzgpAoDrdorXNy5GoI32G8agJ7eLE_rba5xbn9seWRc)
> 
> 是这样！

开DNS劫持试试...

**Comment by xiandu999-yu** [comment]
> > 是不是像这样？ ![322116522-82d263dc-26e3-4a3d-a290-529b9887adcf](https://private-user-images.githubusercontent.com/58256481/322850062-03967995-de6f-4dfe-850d-99bd2ee65030.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MTIwNDgsIm5iZiI6MTcxMzUxMTc0OCwicGF0aCI6Ii81ODI1NjQ4MS8zMjI4NTAwNjItMDM5Njc5OTUtZGU2Zi00ZGZlLTg1MGQtOTliZDJlZTY1MDMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDA3MjkwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiNjJkMzQ5MWU5ZWEzOGU0ZjI0ZTdiODAwNDU2NzhmMDJjYzFmNGJiNjljNzExMzM1NDhlZjA4M2U3ZmJmZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gl4RQ8dgStbAyYCTmznuZQnMmZN64E0MwggMbIYnfHc)
> 
> 我也是这样了，前两天刚出现的情况，不知道咋回事

鬼知道，DNS劫持开了反倒能用了....

**Comment by virus2010** [comment]
如果你开启了其他DNS插件的话，建议关闭或者关闭其中的DNS转发再试试。
