### ISSUE TITLE
问一下，覆写设置>>DNS设置>>NameServer 和 FallBack中的设置保存在那个配置文件中，有知道的吗？

### ISSUE THREAD

**Issue by lpflhh** [vernesong/OpenClash#3852]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [X] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [X] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

最新版

### Bug on Environment

Official OpenWrt

### OpenWrt Version

21.21

### Bug on Platform

Linux-amd64(x86-64)

### Describe the Bug

问一下，覆写设置>>DNS设置>>NameServer 和 FallBack中的设置保存在那个配置文件中，有知道的吗？

### To Reproduce

问一下，覆写设置>>DNS设置>>NameServer 和 FallBack中的设置保存在那个配置文件中，有知道的吗？

### OpenClash Log

```log
问一下，覆写设置>>DNS设置>>NameServer 和 FallBack中的设置保存在那个配置文件中，有知道的吗？
```

### OpenClash Config

```shell
问一下，覆写设置>>DNS设置>>NameServer 和 FallBack中的设置保存在那个配置文件中，有知道的吗？
```

### Expected Behavior

问一下，覆写设置>>DNS设置>>NameServer 和 FallBack中的设置保存在那个配置文件中，有知道的吗？

### Additional Context

问一下，覆写设置>>DNS设置>>NameServer 和 FallBack中的设置保存在那个配置文件中，有知道的吗？

**Comment by PKC278** [comment]
/etc/config/openclash

**Comment by lpflhh** [comment]
> /etc/config/openclash
谢谢，问题解决！

**Comment by vernesong** [comment]
/etc/openclash/custom
