### ISSUE TITLE
[Bug] 首页的IP 地址的 IP.TB 地址一直显示为查询中...

### ISSUE THREAD

**Issue by cngzsunny** [vernesong/OpenClash#3854]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [X] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [X] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

v0.46.003-beta

### Bug on Environment

Official OpenWrt

### OpenWrt Version

23.05.3

### Bug on Platform

Linux-arm64

### Describe the Bug

打开首页，在IP地址栏目里面，IP.TB 这项一直显示 查询中……

### To Reproduce

打开首页，在IP地址栏目里面，IP.TB 这项一直显示 查询中……

### OpenClash Log

```log
-
```

### Expected Behavior

打开首页，在IP地址栏目里面，IP.TB 应该能够显示国内IP，或者换做其他显示国内IP的提供商。

用Chrome检查页面操作，这里是访问https://www.taobao.com/help/getip.php?callback=ipCallback来获取国内IP地址，但返回是403代码，应该是淘宝那边ban了这个访问了

**Comment by vernesong** [comment]
dev换了

**Comment by cngzsunny** [comment]
用dev分支的myip.htm替换现在运行时的文件搞定了

**Comment by animo66** [comment]
遇到了同样的问题，请问最终的解决办法是用哪个文件替换哪个文件？

**Comment by takeseem** [comment]
```
if [ -d "/usr/lib/lua/luci/view/openclash" ]; then
  cd /usr/lib/lua/luci/view/openclash
  cp -rp myip.htm myip.htm.$(date +%Y-%m-%d_%H-%M-%S)
  curl -L https://github.com/vernesong/OpenClash/raw/dev/luci-app-openclash/luasrc/view/openclash/myip.htm -O myip.htm
  ls -lsa /usr/lib/lua/luci/view/openclash|grep myip
fi
```
@animo66 直接执行代码即可
