### ISSUE TITLE
[Bug] 以http方式下载大文件规则集做分流配置时，下载规则集报错

### ISSUE THREAD

**Issue by BlueBenson** [vernesong/OpenClash#3857]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [X] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

v0.46.003-beta

### Bug on Environment

Immortalwrt

### OpenWrt Version

ImmortalWrt 21.02

### Bug on Platform

Linux-amd64(x86-64)

### Describe the Bug

使用“自定义规则集附加”功能时，如果通过http方式新增规则集，当下载的规则集文件较大（2.7mb），openclash内核报错。换用yaml配置文件rule-providers方式，openclash同样报错。
报错内容如下：ERR [Config] configuration file test failed error=initial rule provider Http-大陆域名 error: Get "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMax/ChinaMax_Classical.yaml": context deadline exceeded path=/etc/openclash/Benson-Rlues.yaml

如果将上述同一个规则集文件（https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMax/ChinaMax_Classical.yaml）下载后，手动上传至openclash，使用“自定义规则集附加”file方式，该规则集文件顺利通过配置检查。

### To Reproduce

使用“自定义规则集附加”功能时，如果通过http方式新增规则集：https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMax/ChinaMax_Classical.yaml

### OpenClash Log

```log
ERR [Config] configuration file test failed error=initial rule provider Http-大陆域名 error: Get "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMax/ChinaMax_Classical.yaml": context deadline exceeded path=/etc/openclash/Benson-Rlues.yaml
```

### Expected Behavior

请帮助解决该问题，方便通过http方式自动更新规则集

**Comment by vernesong** [comment]
用meta

**Comment by BlueBenson** [comment]
> 用meta

换用Meta内核后确实可以正常下载了，非常感谢，但是出了个新问题，换用Meta内核后，发现分流时，全是IP地址，用域名的规则都无法命中。

**Comment by xiaoyangdkj** [comment]
> > 用meta
> 
> 换用Meta内核后确实可以正常下载了，非常感谢，但是出了个新问题，换用Meta内核后，发现分流时，全是IP地址，用域名的规则都无法命中。我的网络环境是内网搭建了pi-hole，pi-hole通过tls dns方式解析域名，不知道和这个有关系否，但是之前用普通内核，分流规则是出域名的，没有问题。

打开域名嗅探，应该是meta+fakeip出现的问题。如果域名嗅探无用，就打开openclash的dns劫持

**Comment by BlueBenson** [comment]
> > > 用meta
> > 
> > 
> > 换用Meta内核后确实可以正常下载了，非常感谢，但是出了个新问题，换用Meta内核后，发现分流时，全是IP地址，用域名的规则都无法命中。我的网络环境是内网搭建了pi-hole，pi-hole通过tls dns方式解析域名，不知道和这个有关系否，但是之前用普通内核，分流规则是出域名的，没有问题。
> 
> 打开域名嗅探，应该是meta+fakeip出现的问题。如果域名嗅探无用，就打开openclash的dns劫持

我一直使用Redir-Host TUN模式（fakeip模式uu加速器总是失败），按照您给的建议调整为meta+fakeip，打开域名嗅探，打开dns劫持，依然分流时全是ip地址，域名规则无效。所以不论是Redir-host还是fakeip，使用meta后，分流规则均是ip地址。
我把我的配置提供如下：


<img width="980" alt="Screenshot 2024-04-25 at 12 32 05" src="https://github.com/vernesong/OpenClash/assets/102408041/cc179452-9de2-49a3-a87c-46b48f5196b3">

<img width="960" alt="Screenshot 2024-04-25 at 12 27 38" src="https://github.com/vernesong/OpenClash/assets/102408041/f4972495-49e4-4121-b173-4056484db21f">

<img width="761" alt="Screenshot 2024-04-25 at 12 27 55" src="https://github.com/vernesong/OpenClash/assets/102408041/35ecc00e-5628-4902-912d-70b3eaa05ae6">


<img width="1030" alt="Screenshot 2024-04-25 at 12 27 43" src="https://github.com/vernesong/OpenClash/assets/102408041/090a5363-b092-496d-8f15-2ec3abb42e0e">


<img width="1206" alt="Screenshot 2024-04-25 at 12 27 20" src="https://github.com/vernesong/OpenClash/assets/102408041/d66eb2f2-40e2-4556-9b41-a5cf1e2f2f6e">

**Comment by xiaoyangdkj** [comment]
> > > > 用meta
> > > 
> > > 
> > > 换用Meta内核后确实可以正常下载了，非常感谢，但是出了个新问题，换用Meta内核后，发现分流时，全是IP地址，用域名的规则都无法命中。 我的网络环境是内网搭建了pi-hole，pi-hole通过tls dns方式解析域名，不知道和这个有关系否，但是之前用普通内核，分流规则是出域名的，没有问题。
> > 
> > 
> > 打开域名嗅探，应该是meta+fakeip出现的问题。 如果域名嗅探无用，就打开openclash的dns劫持
> 
> 我一直使用Redir-Host TUN模式（fakeip模式uu加速器总是失败），按照您给的建议调整为meta+fakeip，打开域名嗅探，打开dns劫持，依然分流时全是ip地址，域名规则无效。 所以不论是Redir-host还是fakeip，使用meta后，分流规则均是ip地址。 我把我的配置提供如下：
> 
> redir-host配置 <img alt="Screenshot 2024-04-25 at 12 32 05" width="980" src="https://private-user-images.githubusercontent.com/102408041/325473030-cc179452-9de2-49a3-a87c-46b48f5196b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMjE2NzMsIm5iZiI6MTcxNDAyMTM3MywicGF0aCI6Ii8xMDI0MDgwNDEvMzI1NDczMDMwLWNjMTc5NDUyLTlkZTItNDlhMy1hODdjLTQ2YjQ4ZjUxOTZiMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNVQwNTAyNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMjBjMDZmMmU2ZGUwYzkyNTNhYWJlNjg4Y2JhZGJlYmMzNWYxOTFhN2FmNDdmNzlmZGM1ZjMyZDZlMzE1ZmUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WGV0tt8PxPCeTNqucb9RTMaKmhQFb4QEpb_ZudQGYQA">
> 
> fakeip 放置 <img alt="Screenshot 2024-04-25 at 12 27 38" width="960" src="https://private-user-images.githubusercontent.com/102408041/325473108-f4972495-49e4-4121-b173-4056484db21f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMjE2NzMsIm5iZiI6MTcxNDAyMTM3MywicGF0aCI6Ii8xMDI0MDgwNDEvMzI1NDczMTA4LWY0OTcyNDk1LTQ5ZTQtNDEyMS1iMTczLTQwNTY0ODRkYjIxZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNVQwNTAyNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03N2E1NjY2MGJhZjM0MDQyMGNjZTMxMzFjZGRhYjM2ZjhmYmNhNGMyZDNkNDJlNGRhYTU2ODhhMzQ3ZTgzNWI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.phSw8AUpX1hc2XEugYrh6tfAg1p5Wa1L5V_RSAHPUF0">
> 
> Meta设置 <img alt="Screenshot 2024-04-25 at 12 27 55" width="761" src="https://private-user-images.githubusercontent.com/102408041/325473161-35ecc00e-5628-4902-912d-70b3eaa05ae6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMjE2NzMsIm5iZiI6MTcxNDAyMTM3MywicGF0aCI6Ii8xMDI0MDgwNDEvMzI1NDczMTYxLTM1ZWNjMDBlLTU2MjgtNDkwMi05MTJkLTcwYjNlYWEwNWFlNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNVQwNTAyNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMTFkNDNmMzJmNTY2NTk3MWQxYTc0ZWQzOTVlZTY0M2M1ZmE1ODA0NmMwY2JkMzJmMWZjNmIzZmZmMjdiZWQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IiZcbCfhdxe1THdkk0W9jW1nwpvcyfXfZwoIyueyxzc">
> 
> DNS设置 <img alt="Screenshot 2024-04-25 at 12 27 43" width="1030" src="https://private-user-images.githubusercontent.com/102408041/325473193-090a5363-b092-496d-8f15-2ec3abb42e0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMjE2NzMsIm5iZiI6MTcxNDAyMTM3MywicGF0aCI6Ii8xMDI0MDgwNDEvMzI1NDczMTkzLTA5MGE1MzYzLWIwOTItNDk2ZC04ZjE1LTJlYzNhYmI0MmUwZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNVQwNTAyNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMTNjZDAwNDAxZTBlZTMzODc5ZmM4NWVkN2YyY2U2MmM4MzdiMjEyZjg5MzczOTYyOGZiZGEyYTZjMWFhNjZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yjJjrPpeGPKcPTqnF2WZYibl-3DZoFSKFWOjzEa1X4E">
> 
> 分流显示 <img alt="Screenshot 2024-04-25 at 12 27 20" width="1206" src="https://private-user-images.githubusercontent.com/102408041/325473228-d66eb2f2-40e2-4556-9b41-a5cf1e2f2f6e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMjE2NzMsIm5iZiI6MTcxNDAyMTM3MywicGF0aCI6Ii8xMDI0MDgwNDEvMzI1NDczMjI4LWQ2NmViMmYyLTQwZTItNDU1Ni05YjQxLWE1Y2YxZTJmMmY2ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNVQwNTAyNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZjNkY2UxMmU2NTRmMDUzMzk1NzIyZDM5MmQ1YTJlYzY0MWE4NDkxZTA5YzQwYzNiN2YxNmNkM2I3ZjVhNGI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ErfVPpXie6tuM1qZ31MADPATM0v_mCJ-R9KxPJfkQN0">

meta的域名嗅探似乎需要启用"自定义流量探测（嗅探）设置"才能使用

我的 流量（域名）探测设置
![屏幕截图_20240425_130432](https://github.com/vernesong/OpenClash/assets/82305021/2ce59753-14d6-4c9a-a4e0-c981545c6fc5)

另外，如无需要，可停用udp转发（避免uu加速器加速失败）

**Comment by BlueBenson** [comment]
> > > > > 用meta
> > > > 
> > > > 
> > > > 换用Meta内核后确实可以正常下载了，非常感谢，但是出了个新问题，换用Meta内核后，发现分流时，全是IP地址，用域名的规则都无法命中。 我的网络环境是内网搭建了pi-hole，pi-hole通过tls dns方式解析域名，不知道和这个有关系否，但是之前用普通内核，分流规则是出域名的，没有问题。
> > > 
> > > 
> > > 打开域名嗅探，应该是meta+fakeip出现的问题。 如果域名嗅探无用，就打开openclash的dns劫持
> > 
> > 
> > 我一直使用Redir-Host TUN模式（fakeip模式uu加速器总是失败），按照您给的建议调整为meta+fakeip，打开域名嗅探，打开dns劫持，依然分流时全是ip地址，域名规则无效。 所以不论是Redir-host还是fakeip，使用meta后，分流规则均是ip地址。 我把我的配置提供如下：
> > redir-host配置 <img alt="Screenshot 2024-04-25 at 12 32 05" width="980" src="https://private-user-images.githubusercontent.com/102408041/325473030-cc179452-9de2-49a3-a87c-46b48f5196b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMjE2NzMsIm5iZiI6MTcxNDAyMTM3MywicGF0aCI6Ii8xMDI0MDgwNDEvMzI1NDczMDMwLWNjMTc5NDUyLTlkZTItNDlhMy1hODdjLTQ2YjQ4ZjUxOTZiMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNVQwNTAyNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMjBjMDZmMmU2ZGUwYzkyNTNhYWJlNjg4Y2JhZGJlYmMzNWYxOTFhN2FmNDdmNzlmZGM1ZjMyZDZlMzE1ZmUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WGV0tt8PxPCeTNqucb9RTMaKmhQFb4QEpb_ZudQGYQA">
> > fakeip 放置 <img alt="Screenshot 2024-04-25 at 12 27 38" width="960" src="https://private-user-images.githubusercontent.com/102408041/325473108-f4972495-49e4-4121-b173-4056484db21f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMjE2NzMsIm5iZiI6MTcxNDAyMTM3MywicGF0aCI6Ii8xMDI0MDgwNDEvMzI1NDczMTA4LWY0OTcyNDk1LTQ5ZTQtNDEyMS1iMTczLTQwNTY0ODRkYjIxZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNVQwNTAyNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03N2E1NjY2MGJhZjM0MDQyMGNjZTMxMzFjZGRhYjM2ZjhmYmNhNGMyZDNkNDJlNGRhYTU2ODhhMzQ3ZTgzNWI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.phSw8AUpX1hc2XEugYrh6tfAg1p5Wa1L5V_RSAHPUF0">
> > Meta设置 <img alt="Screenshot 2024-04-25 at 12 27 55" width="761" src="https://private-user-images.githubusercontent.com/102408041/325473161-35ecc00e-5628-4902-912d-70b3eaa05ae6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMjE2NzMsIm5iZiI6MTcxNDAyMTM3MywicGF0aCI6Ii8xMDI0MDgwNDEvMzI1NDczMTYxLTM1ZWNjMDBlLTU2MjgtNDkwMi05MTJkLTcwYjNlYWEwNWFlNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNVQwNTAyNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMTFkNDNmMzJmNTY2NTk3MWQxYTc0ZWQzOTVlZTY0M2M1ZmE1ODA0NmMwY2JkMzJmMWZjNmIzZmZmMjdiZWQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IiZcbCfhdxe1THdkk0W9jW1nwpvcyfXfZwoIyueyxzc">
> > DNS设置 <img alt="Screenshot 2024-04-25 at 12 27 43" width="1030" src="https://private-user-images.githubusercontent.com/102408041/325473193-090a5363-b092-496d-8f15-2ec3abb42e0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMjE2NzMsIm5iZiI6MTcxNDAyMTM3MywicGF0aCI6Ii8xMDI0MDgwNDEvMzI1NDczMTkzLTA5MGE1MzYzLWIwOTItNDk2ZC04ZjE1LTJlYzNhYmI0MmUwZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNVQwNTAyNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMTNjZDAwNDAxZTBlZTMzODc5ZmM4NWVkN2YyY2U2MmM4MzdiMjEyZjg5MzczOTYyOGZiZGEyYTZjMWFhNjZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yjJjrPpeGPKcPTqnF2WZYibl-3DZoFSKFWOjzEa1X4E">
> > 分流显示 <img alt="Screenshot 2024-04-25 at 12 27 20" width="1206" src="https://private-user-images.githubusercontent.com/102408041/325473228-d66eb2f2-40e2-4556-9b41-a5cf1e2f2f6e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMjE2NzMsIm5iZiI6MTcxNDAyMTM3MywicGF0aCI6Ii8xMDI0MDgwNDEvMzI1NDczMjI4LWQ2NmViMmYyLTQwZTItNDU1Ni05YjQxLWE1Y2YxZTJmMmY2ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNVQwNTAyNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZjNkY2UxMmU2NTRmMDUzMzk1NzIyZDM5MmQ1YTJlYzY0MWE4NDkxZTA5YzQwYzNiN2YxNmNkM2I3ZjVhNGI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ErfVPpXie6tuM1qZ31MADPATM0v_mCJ-R9KxPJfkQN0">
> 
> meta的域名嗅探似乎需要启用"自定义流量探测（嗅探）设置"才能使用
> 
> 我的 流量（域名）探测设置 ![屏幕截图_20240425_130432](https://private-user-images.githubusercontent.com/82305021/325479929-2ce59753-14d6-4c9a-a4e0-c981545c6fc5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMjc3MzQsIm5iZiI6MTcxNDAyNzQzNCwicGF0aCI6Ii84MjMwNTAyMS8zMjU0Nzk5MjktMmNlNTk3NTMtMTRkNi00YzlhLWE0ZTAtYzk4MTU0NWM2ZmM1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDA2NDM1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4OTY5MTE4NzdjOGI4YzI5ZWY5NjlmZDQ3ZTVjZjZiMjU5NzZmN2U2YWI2YWE0ZDUxZjE2ZDhmZTg1ZmY0MzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C63xcff47x5oHZOWNa-QYSxysuGghNZK-aH-eUxXvic)
> 
> 另外，如无需要，可停用udp转发（避免uu加速器加速失败） ![屏幕截图_20240425_130915](https://private-user-images.githubusercontent.com/82305021/325480603-e6f64d81-c402-4fc3-8356-f7202e389076.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMjc3MzQsIm5iZiI6MTcxNDAyNzQzNCwicGF0aCI6Ii84MjMwNTAyMS8zMjU0ODA2MDMtZTZmNjRkODEtYzQwMi00ZmMzLTgzNTYtZjcyMDJlMzg5MDc2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDA2NDM1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkZmZlOTJjZTZlZDlmMTk1OTZjMmMzN2FiMmVlMTkxNGJlY2Q2NjVjNjI0MTc5NjQwZjVmNTZiYjJiNzNmN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hRDzRxW6zxYFx173l57uiSFSHFzT_ATrBFGG4AWaTog)

勾选启用"自定义流量探测（嗅探）设置"后，问题解决了，感谢！貌似meta确实还需继续优化。

**Comment by BlueBenson** [comment]
> > > > > 用meta
> > > > 
> > > > 
> > > > 换用Meta内核后确实可以正常下载了，非常感谢，但是出了个新问题，换用Meta内核后，发现分流时，全是IP地址，用域名的规则都无法命中。 我的网络环境是内网搭建了pi-hole，pi-hole通过tls dns方式解析域名，不知道和这个有关系否，但是之前用普通内核，分流规则是出域名的，没有问题。
> > > 
> > > 
> > > 打开域名嗅探，应该是meta+fakeip出现的问题。 如果域名嗅探无用，就打开openclash的dns劫持
> > 
> > 
> > 我一直使用Redir-Host TUN模式（fakeip模式uu加速器总是失败），按照您给的建议调整为meta+fakeip，打开域名嗅探，打开dns劫持，依然分流时全是ip地址，域名规则无效。 所以不论是Redir-host还是fakeip，使用meta后，分流规则均是ip地址。 我把我的配置提供如下：
> > 
> >
> > 
> >
> 
> meta的域名嗅探似乎需要启用"自定义流量探测（嗅探）设置"才能使用
> 
> 我的 流量（域名）探测设置 ![屏幕截图_20240425_130432](https://private-user-images.githubusercontent.com/82305021/325479929-2ce59753-14d6-4c9a-a4e0-c981545c6fc5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMjc3MzQsIm5iZiI6MTcxNDAyNzQzNCwicGF0aCI6Ii84MjMwNTAyMS8zMjU0Nzk5MjktMmNlNTk3NTMtMTRkNi00YzlhLWE0ZTAtYzk4MTU0NWM2ZmM1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDA2NDM1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4OTY5MTE4NzdjOGI4YzI5ZWY5NjlmZDQ3ZTVjZjZiMjU5NzZmN2U2YWI2YWE0ZDUxZjE2ZDhmZTg1ZmY0MzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C63xcff47x5oHZOWNa-QYSxysuGghNZK-aH-eUxXvic)
> 
> 另外，如无需要，可停用udp转发（避免uu加速器加速失败） ![屏幕截图_20240425_130915](https://private-user-images.githubusercontent.com/82305021/325480603-e6f64d81-c402-4fc3-8356-f7202e389076.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMjc3MzQsIm5iZiI6MTcxNDAyNzQzNCwicGF0aCI6Ii84MjMwNTAyMS8zMjU0ODA2MDMtZTZmNjRkODEtYzQwMi00ZmMzLTgzNTYtZjcyMDJlMzg5MDc2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDA2NDM1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkZmZlOTJjZTZlZDlmMTk1OTZjMmMzN2FiMmVlMTkxNGJlY2Q2NjVjNjI0MTc5NjQwZjVmNTZiYjJiNzNmN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hRDzRxW6zxYFx173l57uiSFSHFzT_ATrBFGG4AWaTog)
