### ISSUE TITLE
fake-ip不能n1代理自身流量

### ISSUE THREAD

**Issue by 2287405159** [vernesong/OpenClash#386]
n1盒子使用fake-ip无论是增强，tun，game模式，n1盒子自身始终无法访问网络，在ssr或passwall中测试均无法连接，docker容器也无法pull。
当开启udp或tun模式时，解锁网易云音乐可以自动分流，解锁手机端网易云音乐灰色歌曲。
不论访问控制里规则是否包含路由器自身ip均无法解决

**Comment by vernesong** [comment]
关闭插件能上网吗

**Comment by 2287405159** [comment]
关闭可以上网，我今天玩游戏还发现王者荣耀与和平精英都无法进入游戏，但可以进入加载页面邀请好友等都可以

**Comment by 2287405159** [comment]
> 关闭插件能上网吗

关闭可以上网，我今天玩游戏还发现王者荣耀与和平精英都无法进入游戏，但可以进入加载页面邀请好友等都可以
