### ISSUE TITLE
[Bug] 禁用 QUIC 对 IPv6 TUN 模式 无效

### ISSUE THREAD

**Issue by snachx** [vernesong/OpenClash#3863]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [X] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

v0.46.007-beta

### Bug on Environment

Lean

### OpenWrt Version

Openwrt 23.05.3

### Bug on Platform

Linux-arm64

### Describe the Bug

Meta 内核
运行模式 Redir-Host(TUN)
禁用 QUIC
IPv6 代理模式 TUN 模式

以上设置的前提下，验证发现 IPv6 下会添加 quic reject 规则到 input 链，不会添加到 forward 链
https://github.com/vernesong/OpenClash/blob/e9575929f8bbec1c511dc237aefe5d5a33733e6f/luci-app-openclash/root/etc/init.d/openclash#L2895
作为对比， IPv4 下启用 TUN，quic reject 规则只会添加 forward 链，不启用 TUN, 只会添加到 input 链
https://github.com/vernesong/OpenClash/blob/e9575929f8bbec1c511dc237aefe5d5a33733e6f/luci-app-openclash/root/etc/init.d/openclash#L2481
https://github.com/vernesong/OpenClash/blob/e9575929f8bbec1c511dc237aefe5d5a33733e6f/luci-app-openclash/root/etc/init.d/openclash#L2625

fw3 和 fw4 都有同样的问题

### To Reproduce

Meta 内核
运行模式 Redir-Host(TUN)
禁用 QUIC
IPv6 代理模式 TUN 模式
检查防火墙设置

### OpenClash Log

```log
日志无关
```

### Expected Behavior

IPv6 下使用 tun 模式也应该在 forward 链添加 quic reject 规则

**Comment by snachx** [comment]
@vernesong 测了一下有个 bug,  match-set 应该是 china_ip6_route
https://github.com/vernesong/OpenClash/blob/7256d89a39e9db4c971076c841347d203360878f/luci-app-openclash/root/etc/init.d/openclash#L2922

**Comment by snachx** [comment]
v0.46.010 已经修好了，你这个提示跟这个没关系，应该是代理本身的问题

**Comment by patsnap-guyong** [comment]
> 这个问题是不是还没修好，我看Youtube会有类似情况 ![image](https://private-user-images.githubusercontent.com/57741549/330765192-a82a9a64-3bb3-4685-b180-e54c5e6ff921.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNjkzMDYsIm5iZiI6MTcxNjI2OTAwNiwicGF0aCI6Ii81Nzc0MTU0OS8zMzA3NjUxOTItYTgyYTlhNjQtM2JiMy00Njg1LWIxODAtZTU0YzVlNmZmOTIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDA1MjMyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwNzJkMzJmNTgyYTYxZjEyMTk3ZjliYmRhMThkMTczNjgwN2U1YWRiYTA4NzcwZjVhMWQzYzk2MGYxMjc4MWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cbHeA1WGaclazKBipYk4esRFnhTfRFsfTn6kyp-7_7g)

0.46.011版本依然存在问题，表现还是卡：
Tip: Firewall4 was Detected, Use NFTABLE Rules...

**Comment by patsnap-guyong** [comment]
> 0.46.011版本依然存在问题，表现还是卡：
> Tip: Firewall4 was Detected, Use NFTABLE Rules...
