### ISSUE TITLE
[Bug] 访问其他国内网站都正常，但是京东报错

### ISSUE THREAD

**Issue by iamjimmycheng** [vernesong/OpenClash#3867]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [ ] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

v0.46.003-beta

### Bug on Environment

Official OpenWrt

### OpenWrt Version

OpenWrt R23.3.3

### Bug on Platform

Linux-amd64(x86-64)

### Describe the Bug

访问大部分都国内、国外网站都正常，唯独访问京东不行，但是换成passwall的话，访问京东就正常了，是DNS的问题吗？

### To Reproduce

以下是我的yaml配置：
mixed-port: 7890
unified-delay: false
geodata-mode: true
tcp-concurrent: false
find-process-mode: strict
global-client-fingerprint: chrome

allow-lan: true
mode: rule
log-level: info

external-controller: 127.0.0.1:9090

geox-url:
  geoip: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb"

profile:
  store-selected: true
  store-fake-ip: true

sniffer:
  enable: false
  sniff:
    TLS:
      ports: [443]
    HTTP:
      ports: [80]
      override-destination: true

tun:
  enable: true
  stack: system
  dns-hijack:
    - 'any:53'
  auto-route: true
  auto-detect-interface: true

dns:
  enable: true
  listen: 0.0.0.0:1053
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter:
    - '*'
    - '+.lan'
  default-nameserver:
    - 223.5.5.5
  nameserver:
    - 'tls://8.8.4.4#DNS_Proxy'
    - 'tls://1.0.0.1#DNS_Proxy'
  proxy-server-nameserver:
    - https://dns.alidns.com/dns-query#h3=true
  nameserver-policy:
    "geosite:cn,private":
      - 223.5.5.5
      - 114.114.114.114
      - https://dns.alidns.com/dns-query#h3=true

### OpenClash Log

```log
2024-04-30 17:33:27 level=warning msg="[TCP] dial DIRECT (match RuleSet/ChinaMaxDomain) 192.168.3.176:57468 --> misc.360buyimg.com:443 error: dial tcp 117.72.226.3:443: i/o timeout"
2024-04-30 17:33:27 level=info msg="[TCP] 192.168.3.176:57472 --> static.360buyimg.com:443 match RuleSet(ChinaMaxDomain) using DIRECT"
2024-04-30 17:33:27 level=warning msg="[TCP] dial DIRECT (match RuleSet/ChinaMaxDomain) 192.168.3.176:57467 --> misc.360buyimg.com:443 error: dial tcp 117.72.226.3:443: i/o timeout"
```

### Expected Behavior

无

**Comment by vernesong** [comment]
nameserver不要填国外的
