### ISSUE TITLE
希望增加对hysteria2协议的支持

### ISSUE THREAD

**Issue by lyglay1991** [vernesong/OpenClash#3869]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经**使用最新 Dev 版本**查看过，并不包含该功能特性或者还不完善
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 应包含的特性
- [X] Contributors 我有能力协助 OpenClash 开发或完善此功能特性
- [X] Meaningless 我提交的**是无意义的**催促更新或修复请求

### Describe the Feature

希望增加对hysteria2协议的支持

### Describe Alternatives

希望增加对hysteria2协议的支持

**Comment by Pacio** [comment]
你没用meta内核？

**Comment by RayWangQvQ** [comment]
关了吧，meta内核本身就支持

**Comment by zxlhhyccc** [comment]
> 希望增加对hysteria2协议的支持

本来meta就支持，何来增加支持？

**Comment by yellowsavant** [comment]
Openclash = 汽车操控系统（外壳/操作介面）
内核（Core） = 引擎（可更换，有数种引擎可选，例如Meta）
Meta = Core的其中一种型号
每种Core型号支持的功能不一，Meta是目前还有人维护的Core
So：把这些概念搞搞清楚，你就能知道楼上这些人说的什么东西了

**Comment by zhangweibo413** [comment]
新版meta内核有问题，部分订阅不支持，很奇怪，具体原因不详，我自己去mihomo下载alpha-fe88f0e版本替换掉后台推荐升级的版本，立马正常

**Comment by yellowsavant** [comment]
> 我用旁路由 meta内核 用hysteria2节点 直连网关不能代理 改用HTTP连openclash就行 不知道是什么原因 切换成vless等节点又可以旁网关代理

你用旁路最好在旁路上开启nat，因为你的client端指向旁路再由主路返回会有路由追踪的问题

**Comment by Qicloud-W** [comment]
我是mate ssh连接不上海外服务器...找不出问题在哪

**Comment by ymBoss** [comment]
大神们 我也遇到一样的问题啊，订阅节点在verge里面显示是正常的，但是openclash刷新不出来啊，怎么办

**Comment by lfinexr** [comment]
检查一下Meta内核版本。不少人反应gfeedc9e本版bug，连不上hy2。更新一下就好了。参见
https://github.com/vernesong/OpenClash/issues/3826

**Comment by ppllpig** [comment]
> 我用旁路由 meta内核 用hysteria2节点 直连网关不能代理 改用HTTP连openclash就行 不知道是什么原因 切换成vless等节点又可以旁网关代理

解决了吗，同样。s5可以，改网关为旁路不行

**Comment by Rich-xuguo** [comment]
> 我用旁路由 meta内核 用hysteria2节点 直连网关不能代理 改用HTTP连openclash就行 不知道是什么原因 切换成vless等节点又可以旁网关代理

我也是一样，新买了个机场节点hysteria2协议，旁路由模式下客户机网关指向clash无法翻墙，改用设置clash为代理服务器就正常。旧机场vmess协议两种方式都可以上。
