### ISSUE TITLE
请问一下 YACD面板中“代理”页面所指定的openclash分流规则保存在哪个配置文件中，我想调整好之后备份一下【已解决】

### ISSUE THREAD

**Issue by lpflhh** [vernesong/OpenClash#3873]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [X] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [X] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

last

### Bug on Environment

Lean

### OpenWrt Version

last

### Bug on Platform

Linux-amd64(x86-64)

### Describe the Bug

请问一下 YACD面板中“代理”页面所指定的openclash分流规则保存在哪个配置文件中，我想调整好之后备份一下

### To Reproduce

请问一下 YACD面板中“代理”页面所指定的openclash分流规则保存在哪个配置文件中，我想调整好之后备份一下

### OpenClash Log

```log
请问一下 YACD面板中“代理”页面所指定的openclash分流规则保存在哪个配置文件中，我想调整好之后备份一下
```

### Expected Behavior

请问一下 YACD面板中“代理”页面所指定的openclash分流规则保存在哪个配置文件中，我想调整好之后备份一下

**Comment by PKC278** [comment]
/etc/openclash/配置文件名.yml
