### ISSUE TITLE
[Bug] 安装插件直接导致设备失联，因为是远程异地操作，现在不知道怎么处理

### ISSUE THREAD

**Issue by 858622025** [vernesong/OpenClash#3876]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [ ] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

v0.46.003-beta

### Bug on Environment

Istoreos

### OpenWrt Version

当前无法获取，只知道是最新版的

### Bug on Platform

Linux-amd64(x86-64)

### Describe the Bug

[Bug] 安装插件直接导致设备失联，因为是远程异地操作，现在不知道怎么处理

### To Reproduce

[Bug] 安装插件直接导致设备失联，因为是远程异地操作，现在不知道怎么处理

### OpenClash Log

```log
[Bug] 安装插件直接导致设备失联，因为是远程异地操作，现在不知道怎么处理
```

### Expected Behavior

[Bug] 安装插件直接导致设备失联，因为是远程异地操作，现在不知道怎么处理

**Comment by vernesong** [comment]
取消本机代理

**Comment by 858622025** [comment]
> 取消本机代理

应该不是。周末回家的时候，发现单纯安装过程中死机了

**Comment by 858622025** [comment]
> > 取消本机代理
> 
> 应该不是。周末回家的时候，发现单纯安装过程中死机了

代理的话，我没有开启相关的东西

**Comment by 725216** [comment]
下次设置个定时重启，第二天就好了
