### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by 2443552033** [vernesong/OpenClash#3881]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [x] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [X] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [X] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

v0.64.003

### Bug on Environment

Istoreos

### OpenWrt Version

	iStoreOS 22.03.6 2024043010 / LuCI istoreos-22.03 branch git-24.057.30647-6659faa

### Bug on Platform

Linux-amd64(x86-64)

### Describe the Bug

在软路由docker部署的迅雷下载文件时局域网内其他设备无法正常上网内核日志显示iotimeout

### To Reproduce

在istoreos商店中下载并安装迅雷插件并随意下载文件

### OpenClash Log

```log
1
```

### OpenClash Config

```shell
# This file is interpreted as shell script.
# Put your custom iptables rules here, they will
# be executed with each firewall (re-)start.

# Internal uci firewall chains are flushed and recreated on reload, so
# put custom rules into the root chains e.g. INPUT or FORWARD or into the
# special user chains, e.g. input_wan_rule or postrouting_lan_rule.
```

### Expected Behavior

在软路由上迅雷下载同时其他设备正常上网

### Additional Context

![屏幕截图 2024-05-11 204923](https://github.com/vernesong/OpenClash/assets/108340942/742ebd3c-ea4c-41ca-a509-bd22389b443b)
![屏幕截图 2024-05-11 204932](https://github.com/vernesong/OpenClash/assets/108340942/ab1f85f7-b213-4274-908b-b2200c580395)
[调试日志.txt](https://github.com/vernesong/OpenClash/files/15282868/default.txt)

**Comment by xiaoyangdkj** [comment]
docker迅雷把流量抢完了吧,或许应该去docker那里限制上传下载

**Comment by 2443552033** [comment]
限制了也没用
