### ISSUE TITLE
[Bug] 使用fakeip模式后无法使用ping

### ISSUE THREAD

**Issue by GuangYu-yu** [vernesong/OpenClash#3882]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [ ] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

v0.46.003-249

### Bug on Environment

Other

### OpenWrt Version

openwrt-23.05

### Bug on Platform

Linux-amd64(x86-64)

### Describe the Bug

fakeip模式无法使用ping命令，进而导致mwan3插件出现问题

### To Reproduce

使用fakeip模式

### OpenClash Log

```log
.
```

### Expected Behavior

.

**Comment by xiaoyangdkj** [comment]
你可以看看 #1854 和 #2413
