### ISSUE TITLE
[Bug] fake-ip 模式下无法收到手机的部分请求，redir-host下就没问题

### ISSUE THREAD

**Issue by sean-root** [vernesong/OpenClash#3884]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [X] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [X] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

v0.46.003-beta

### Bug on Environment

Istoreos

### OpenWrt Version

22.03.6

### Bug on Platform

Linux-amd64(x86-64)

### Describe the Bug

fake-ip tun 下，完全看不到手机发出的 ss.epdg.epc.mnc260.mcc310.pub.3gppnetwork.org 请求（使用的是500/4500端口，已放行），从而无法使用 WiFi Calling，切换到 redir-host 模式下就能看到发出的这个网络请求，并能看到它走了那条规则。

希望在 fake-ip 模式下也能看到这个网络请求，进而可以使用 WiFi Calling。

### To Reproduce

0、关闭手机WiFi；
1、启动 openclash；
2、打开手机WiFi，手机即开始尝试链接运营商链接；
3、如问题描述，看不到网络请求；

### OpenClash Log

```log
只贴DNS部分吧，无其他特殊设置

dns:
  enable: true
  prefer-h3: true
  use-hosts: true
  use-system-hosts: true
  listen: 0.0.0.0:53
  ipv6: true

  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16

  nameserver:
      - https://223.5.5.5/dns-query
      - https://223.6.6.6/dns-query
      - https://1.12.12.12/dns-query
```

### OpenClash Config

```shell
只贴DNS部分吧，无其他特殊设置

dns:
  enable: true
  prefer-h3: true
  use-hosts: true
  use-system-hosts: true
  listen: 0.0.0.0:53
  ipv6: true

  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16

  nameserver:
      - https://223.5.5.5/dns-query
      - https://223.6.6.6/dns-query
      - https://1.12.12.12/dns-query
```

### Expected Behavior

希望在 fake-ip 模式下也能看到这个网络请求，进而可以使用 WiFi Calling。

**Comment by GuangYu-yu** [comment]
我使用fakeip模式后，手机连接上WiFi也是用不了，好像子网掩码和路由等信息都没有正常分配

**Comment by sean-root** [comment]
> 我使用fakeip模式后，手机连接上WiFi也是用不了，好像子网掩码和路由等信息都没有正常分配

我的倒是都有，除了 WiFi Calling 不能用以外，其他都是正常的

@vernesong redir-host 也能正常连接（也能看到走的 自定义的 规则），但是 fake-ip 模式下就是连请求都看不到。我也尝试使用防火墙转发dns，把手机 mac or ip 地址加入黑名单，这样也不行。

**Comment by vernesong** [comment]
加到fakeipfilter里面去，然后运行状态下查询下域名的dns，看内核日志有没有记录

**Comment by sean-root** [comment]
> 加到fakeipfilter里面去，然后运行状态下查询下域名的dns，看内核日志有没有记录

太赞了！通过把域名加入到 fake ip filter 内，终于解决了！请问 wifi calling 不能使用 fake ip 的原因是什么？

**Comment by yellowsavant** [comment]
> > 加到fakeipfilter里面去，然后运行状态下查询下域名的dns，看内核日志有没有记录
> 
> 太赞了！通过把域名加入到 fake ip filter 内，终于解决了！请问 wifi calling 不能使用 fake ip 的原因是什么？

fake ip filter名单相当于redir-host模式，而fake-ip模式下返回的ip是假ip段

**Comment by sean-root** [comment]
> > > 加到fakeipfilter里面去，然后运行状态下查询下域名的dns，看内核日志有没有记录
> > 
> > 
> > 太赞了！通过把域名加入到 fake ip filter 内，终于解决了！请问 wifi calling 不能使用 fake ip 的原因是什么？
> 
> fake ip filter名单相当于redir-host模式，而fake-ip模式下返回的ip是假ip段

是的，But why: wifi calling 不允许使用 fake ip 的原因是啥？难不成是校验 ip 啥的？（这个话题和 openclash 其实没关系了 😄）

**Comment by yellowsavant** [comment]
> > > > 加到fakeipfilter里面去，然后运行状态下查询下域名的dns，看内核日志有没有记录
> > > 
> > > 
> > > 太赞了！通过把域名加入到 fake ip filter 内，终于解决了！请问 wifi calling 不能使用 fake ip 的原因是什么？
> > 
> > 
> > fake ip filter名单相当于redir-host模式，而fake-ip模式下返回的ip是假ip段
> 
> 是的，But why: wifi calling 不允许使用 fake ip 的原因是啥？难不成是校验 ip 啥的？（这个话题和 openclash 其实没关系了 😄）

假IP事实上有很多问题，例如你在clash for windows使用fake ip，有时候会发现wifi断网（DNS rebind protection）....
或是clash因故重启，而client端的dns缓存还keep住之前的假ip，这也会出问题....

**Comment by createkk** [comment]
> > 加到fakeipfilter里面去，然后运行状态下查询下域名的dns，看内核日志有没有记录
> 
> 太赞了！通过把域名加入到 fake ip filter 内，终于解决了！请问 wifi calling 不能使用 fake ip 的原因是什么？

请问是哪个域名呢？

**Comment by sean-root** [comment]
> > > 加到fakeipfilter里面去，然后运行状态下查询下域名的dns，看内核日志有没有记录
> > 
> > 
> > 太赞了！通过把域名加入到 fake ip filter 内，终于解决了！请问 wifi calling 不能使用 fake ip 的原因是什么？
> 
> 请问是哪个域名呢？

Issue Description 里也说了，我是这么写的：

  fake-ip-filter:
    - '+.pub.3gppnetwork.org'

**Comment by createkk** [comment]
> > > > 加到fakeipfilter里面去，然后运行状态下查询下域名的dns，看内核日志有没有记录
> > > 
> > > 
> > > 太赞了！通过把域名加入到 fake ip filter 内，终于解决了！请问 wifi calling 不能使用 fake ip 的原因是什么？
> > 
> > 请问是哪个域名呢？
> 
> Issue Description 里也说了，我是这么写的：
> 
>   fake-ip-filter:
>     - '+.pub.3gppnetwork.org'

谢谢！

**Comment by clocktowerc** [comment]
> > > > 加到fakeipfilter里面去，然后运行状态下查询下域名的dns，看内核日志有没有记录
> 
> > > 
> 
> > > 
> 
> > > 太赞了！通过把域名加入到 fake ip filter 内，终于解决了！请问 wifi calling 不能使用 fake ip 的原因是什么？
> 
> > 
> 
> > 请问是哪个域名呢？
> 
> 
> 
> Issue Description 里也说了，我是这么写的：
> 
> 
> 
>   fake-ip-filter:
> 
>     - '+.pub.3gppnetwork.org'

请问还有除了这个以外的WiFi calling 的相关域名吗？

**Comment by sean-root** [comment]
> > > > > 加到fakeipfilter里面去，然后运行状态下查询下域名的dns，看内核日志有没有记录
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 太赞了！通过把域名加入到 fake ip filter 内，终于解决了！请问 wifi calling 不能使用 fake ip 的原因是什么？
> > 
> > 
> > > 
> > 
> > 
> > > 请问是哪个域名呢？
> > 
> > 
> > Issue Description 里也说了，我是这么写的：
> > fake-ip-filter:
> > ```
> > - '+.pub.3gppnetwork.org'
> > ```
> 
> 请问还有除了这个以外的WiFi calling 的相关域名吗？

没有了，这一个就OK了～

**Comment by solaris256** [comment]
> 我发现在自己的设备上必须要打开ipv6才可以使用wifi-calling，请问大家也是这样吗？

ipv6 没开，可以使用wifi-calling

**Comment by TrioTea** [comment]
> > 我发现在自己的设备上必须要打开ipv6才可以使用wifi-calling，请问大家也是这样吗？
> 
> ipv6 没开，可以使用wifi-calling

请问是mihomo还是singbox啊
