### ISSUE TITLE
无法完全兼容LEDE v2.34

### ISSUE THREAD

**Issue by HuiLi-Intel** [vernesong/OpenClash#389]
大量页面元素会出现Insufficient permissions to read UCI configuration.的错误

**Comment by pikachullk** [comment]
据说是FW867大佬用了19.07+linux 5.4内核太过激进导致的~~
赶紧转回来openwrt18.06吧~5.4连官方都没稳定就用起....别的问题还一大堆呢~苦海无涯~回头是岸

**Comment by zxlhhyccc** [comment]
> 大量页面元素会出现Insufficient permissions to read UCI configuration.的错误

仅运行状态出现吧？官方master的luci引入了acl机制，同时对acl进行了严格限制，所有插件均必须注册，目前我的master使用正常。。。。

**Comment by pikachullk** [comment]
就像我说的…配置yaml页面的保存和应用也点不了～不知道为嘛

zxlhhyccc <notifications@github.com> 于 2020年4月26日周日 19:31写道：
