### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by MSSX-Ifvo** [vernesong/OpenClash#3890]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [X] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

0.46.003-beta

### Bug on Environment

Immortalwrt

### OpenWrt Version

v23.05 branch (git-0eb8f6c)

### Bug on Platform

Linux-arm64

### Describe the Bug

安装软件包时提示缺少 iptables-mod-extra 依赖,但在软件库和官方仓库中均未找到此依赖，请问是否时采用了过时的依赖？ 

### To Reproduce

安装软件包时报错此问题
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency iptables-mod-extra for luci-app-openclash

### OpenClash Log

```log
插件无法启动输出日志
```

### Expected Behavior

希望能给出解决缺少依赖的方法

**Comment by xiaoyangdkj** [comment]
这个依赖是跟着编译固件一起出来的，或许需要检查一下固件

**Comment by yellowsavant** [comment]
这不是bug，而是固件缺少必要的依赖

**Comment by vernesong** [comment]
如果固件是nftables就不用管
