### ISSUE TITLE
[Bug] Fake-IP模式下，DDNS映射的地址无法访问

### ISSUE THREAD

**Issue by LucifielHack** [vernesong/OpenClash#3891]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [ ] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

v0.46.011-beta

### Bug on Environment

Official OpenWrt

### OpenWrt Version

6.1.28

### Bug on Platform

Linux-amd64(x86-64)

### Describe the Bug

使用ddns将内网nas和openwrt以及ipsec映射到域名上（有公网ipv4）
然后使用openwrt的openclash插件，使用fake-ip 混合模式进行代理
接着在外网使用域名+端口访问nas，无法访问，连接ipsec也失败，samba连接nas的硬盘也失败
但是在内网中用域名却又可以访问

### To Reproduce

无

### OpenClash Log

```log
无
```

### Expected Behavior

希望可以在该模式下（测试了我所需要的环境，只有这个模式最好用）正常在外网连接到nas

**Comment by LucifielHack** [comment]
有没有佬知道咋解决啊

**Comment by qq3398139007** [comment]
覆写DNS设置打开Fake-IP-Filter放行ip

**Comment by LuminaIgnis** [comment]
Fallback-Filter

**Comment by LucifielHack** [comment]
> Fallback-Filter

佬，又具体的语句吗

**Comment by LucifielHack** [comment]
佬们，是同一域名下，映射的81端口的ikuai可以在外网访问，82端口的openwrt也可以在外网访问，就是5000端口的nas和ipsec访问不了

**Comment by lqbby** [comment]
方法一:切换到Redir-Host模式
方法二:插件设置-DNS设置-启用第二DNS里面把你的域名都填上

**Comment by blacktail1937** [comment]
某些端口可以访问，某些不能访问应该去看一下端口映射是不是成功了。

**Comment by lhlxx2010** [comment]
请问解决了吗？我也碰到这个问题，暂时无法解决。按楼上 @lqbby 大佬的第二条方法，也不生效。

**Comment by LucifielHack** [comment]
> 请问解决了吗？我也碰到这个问题，暂时无法解决。按楼上 @lqbby 大佬的第二条方法，也不生效。

我找到个办法解决了一部分，在 插件设置 -> 黑白名单 -> 绕过核心的来源端口 中，把你要访问的内网和外网端口都加进去，就可以访问了，并且不影响代理

**Comment by banxiaya** [comment]
> > 请问一下我解决了这个疑问吗？我也想问这个问题，暂时无法解决。@lqbby大佬第二个条方法，也不生效。
> 
> 我找到了解决的一个办法，在插件设置 -> 黑白名单 -> 绕过核心的来源端口中，把你要访问的端口和外网端口都加进去，就可以访问了，并且不影响代理

这个方法可行👍
