### ISSUE TITLE
[Bug] v0.46.011-beta Pre-release  版本中， meta 内核一直更新失败，确认网络是正常的。 

### ISSUE THREAD

**Issue by keivenliao** [vernesong/OpenClash#3896]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [ ] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

v0.46.011-beta Pre-release

### Bug on Environment

Lean

### OpenWrt Version

OpenWrt R24.4.4 / LuCI Master (git-24.102.51807-8c6da73) 

### Bug on Platform

Linux-amd64(x86-64)

### Describe the Bug

meta 内核一直更新失败，确认网络是正常的。 

### To Reproduce

meta 内核一直更新失败，确认网络是正常的。 

### OpenClash Log

```log
meta 内核一直更新失败，确认网络是正常的。
```

### Expected Behavior

修复它

**Comment by keivenliao** [comment]
我只能通过手动下载更新

**Comment by dragon888888888888** [comment]
一样的问题，必须选择加速服务器才能下载，选择后又是各种卡，没有加速服务器的版本一次性下载成功

**Comment by caliban511** [comment]
我我刚好相反，前几个版本总是没法正常更新Meta内核，需要手动，，现在更新到 0.46.011 后，用这个新加的 cdn一键更新 解决了。

**Comment by honeyjuice** [comment]
同样 我的openwrt跑在虚拟机里 也同样无法更新meta内核 每次都是手动ssh上去替换文件
