### ISSUE TITLE
[Feature] 切换节点后断开相关Chains连接

### ISSUE THREAD

**Issue by Indekkusu545** [vernesong/OpenClash#3899]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经**使用最新 Dev 版本**查看过，并不包含该功能特性或者还不完善
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 应包含的特性
- [X] Contributors 我有能力协助 OpenClash 开发或完善此功能特性
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### Describe the Feature

能否在切换节点后断开相关Chains连接？目前切换节点后需要手动关闭所有连接让代理走切换后的节点。

**Comment by VMatrices** [comment]
![image](https://github.com/vernesong/OpenClash/assets/24680533/263a940c-f523-4a49-a340-ee1daafe96f1)
