### ISSUE TITLE
托管里面的dns配置不会清除然后 dns加到 #  nameserver: 

### ISSUE THREAD

**Issue by nameless3721** [vernesong/OpenClash#39]
![image](https://user-images.githubusercontent.com/50364156/66248735-95a76700-e765-11e9-9145-91ce277b9179.png)
![image](https://user-images.githubusercontent.com/50364156/66248741-ac4dbe00-e765-11e9-8a20-9cb0e3797018.png) 加错位置的报错的样子
 
![image](https://user-images.githubusercontent.com/50364156/66248807-372eb880-e766-11e9-92c4-2dde2b5d0c6d.png)
托管里面默认是这样的

v0.34.7-beta版本

**Comment by vernesong** [comment]
没有注释的nameserver正常添加了吗

**Comment by nameless3721** [comment]
> 没有注释的nameserver正常添加了吗

添加了  添加了2遍  上面注释了的添加 下面一个没注释的也添加

**Comment by vernesong** [comment]
fix
