### ISSUE TITLE
重新刷固件问题

### ISSUE THREAD

**Issue by CrazyMouse** [vernesong/OpenClash#390]
请教个问题，如果整合openclash到L大的固件中，重新编译固件了，OpenClash的配置要全部重新来一次么？包括内核下载和远程配置url之类的

**Comment by vernesong** [comment]
直接在luci页面升级会保留配置
内核你在编译的时候就可以放到对应路径以前编译

如果全新刷机需要备份配置可以到下图操作
![image](https://user-images.githubusercontent.com/42875168/80308128-ba495600-87ff-11ea-9464-356e7bdd2a58.png)

**Comment by CrazyMouse** [comment]
OK 也就是说编译的时候没有内置内核的话 更新固件以后需要重新下载一下内核 其他配置都不用重复配置的 对吧 非常感谢
