### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Lllinya** [vernesong/OpenClash#3902]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [ ] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

v0.46.011-beta

### Bug on Environment

Official OpenWrt

### OpenWrt Version

23.05.3

### Bug on Platform

Linux-amd64(x86-64)

### Describe the Bug

我的openwrt目前配置为单臂旁路由，安装了openclash，主路由一切默认并且设置了端口转发。局域网里连接的设备手动填写openwrt为网关实现代理。但是我发现只要我开了openclash，公网就无法再访问内网的网站或者服务了（只要关掉openclash外网就又可以访问了）。请问怎么解决？

### To Reproduce

在局域网设备上部署网站，网关填旁路由openwrt，在主路由设置端口转发，在旁路由上开启openclash，此时公网无法访问网站，并且只要关闭openclash就没问题

### OpenClash Log

```log
日志在附件
```

### Expected Behavior

开启openclash时，使用它为网关的设备上的服务/网站可以被公网访问

### Additional Context

[新建 文本文档.txt](https://github.com/vernesong/OpenClash/files/15492721/default.txt)

**Comment by vernesong** [comment]
访问控制，排除内网向外通讯的端口

**Comment by Lllinya** [comment]
> 访问控制，排除内网向外通讯的端口

<img width="835" alt="image" src="https://github.com/vernesong/OpenClash/assets/92159997/79473d7e-d1e5-487a-a646-a01ae7e6f0e9">
你好，这个选项我之前就填过了。我的内网是192.168.0.x

**Comment by vernesong** [comment]
黑白名单

**Comment by Lllinya** [comment]
> 黑白名单

黑白名单就直接全都走直连了，我只是想实现外部访问
