### ISSUE TITLE
[Bug] Openclash Fake-ip 混合模式下，LOL延迟高的问题

### ISSUE THREAD

**Issue by LucifielHack** [vernesong/OpenClash#3904]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [ ] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

v0.46.011-beta

### Bug on Environment

Official OpenWrt

### OpenWrt Version

OpenWrt R23.5.1 

### Bug on Platform

Linux-amd64(x86-64)

### Describe the Bug

在Fake-ip 混合模式下，LOL延迟高的问题，使用的是自建节点，希望LOL可以不通过节点，应该如何设置

### To Reproduce

无

### OpenClash Log

```log
无
```

### Expected Behavior

无

**Comment by vernesong** [comment]
第三方规则附加，国内ip直连，扩展匹配

**Comment by LucifielHack** [comment]
第三方附加规则的哪一个，我搜索lol 没有搜到国服的


------------------ 原始邮件 ------------------
发件人: vernesong ***@***.***&gt;
发送时间: 2024年6月1日 15:02
收件人: vernesong/OpenClash ***@***.***&gt;
抄送: Lucifiel ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [vernesong/OpenClash] [Bug] Openclash Fake-ip 混合模式下，LOL延迟高的问题 (Issue #3904)

**Comment by LucifielHack** [comment]
> 第三方规则附加，国内ip直连，扩展匹配

佬，请问第三方附加规则中，是哪一个，我搜索没有搜到国服LOL

**Comment by vernesong** [comment]
国内ip库不全，你换geoip或者补充国内ip规则

**Comment by LucifielHack** [comment]
> 国内ip库不全，你换geoip或者补充国内ip规则

佬有教程吗，我没弄过这个
