### ISSUE TITLE
参考安装依赖时出现该问题：Error loading shared library libwolfssl.so.5.5.3.99a5b54a: No such file or directory (needed by /usr/bin/curl)

### ISSUE THREAD

**Issue by db-root** [vernesong/OpenClash#3905]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [ ] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

v0.46.011-beta

### Bug on Environment

Istoreos

### OpenWrt Version

最新版本v0.46.011-beta

### Bug on Platform

Linux-amd64(x86-64)

### Describe the Bug

为什么我在按照安装页面执行了安装依赖的命令之后出现了这样的问题，这个怎么处理呢
#iptables
opkg update
opkg install coreutils-nohup bash iptables dnsmasq-full curl ca-certificates ipset ip-full iptables-mod-tproxy iptables-mod-extra libcap libcap-bin ruby ruby-yaml kmod-tun kmod-inet-diag unzip luci-compat luci luci-base

现在已经尝试过很多issues中说的opkg update 或者install libcurl4_7.83.1-4.1_x86_64.ipk
还是无法解决

### To Reproduce

#iptables
opkg update
opkg install coreutils-nohup bash iptables dnsmasq-full curl ca-certificates ipset ip-full iptables-mod-tproxy iptables-mod-extra libcap libcap-bin ruby ruby-yaml kmod-tun kmod-inet-diag unzip luci-compat luci luci-base

#nftables
opkg update
opkg install coreutils-nohup bash dnsmasq-full curl ca-certificates ipset ip-full libcap libcap-bin ruby ruby-yaml kmod-tun kmod-inet-diag unzip kmod-nft-tproxy luci-compat luci luci-base

root@iStoreOS:~# opkg install ./libcurl4_7.83.1-4.1_x86_64.ipk
Package libcurl4 (7.83.1-2.1) installed in root is up to date.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency libwolfssl5.5.3.99a5b54a for libcurl4
root@iStoreOS:~#
root@iStoreOS:~# curl
Error loading shared library libwolfssl.so.5.5.3.99a5b54a: No such file or directory (needed by /usr/bin/curl)
root@iStoreOS:~#

这个怎么处理呢

### OpenClash Log

```log
还没有安装
```

### Expected Behavior

希望能够帮助恢复curl以及opkg update 和 opkg install

**Comment by 3song** [comment]
这个和插件没关系，是你的系统问题，libwolfssl5.5.3.99a5b54a  吧这个传到openwrt上用命令搞试试
