### ISSUE TITLE
[Feature] 存在多个订阅时，增加前缀用于区分不同机场

### ISSUE THREAD

**Issue by VMatrices** [vernesong/OpenClash#3920]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经**使用最新 Dev 版本**查看过，并不包含该功能特性或者还不完善
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 应包含的特性
- [X] Contributors 我有能力协助 OpenClash 开发或完善此功能特性
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### Describe the Feature

存在多个订阅时，部分机场的节点命名相似不易区分

### Describe Alternatives

参考[此处](https://github.com/tindy2013/subconverter/issues/595#issuecomment-1546706632)，可以通过subconverter的rename参数实现

**Comment by vernlau** [comment]
meta内核支持覆写节点内容，使用override
写法：
proxy-providers:
  P1:
    <<: *P
    override:
      additional-prefix: "P1."
    path: "./proxy_provider/P1.yaml"
    url: http://10.0.0.2:2000/p1

  P2:
    <<: *P
    override:
      additional-prefix: "P2."
    path: "./proxy_provider/P2.yaml"
    url: http://10.0.0.2:2000/p2
实现效果：
![image](https://github.com/vernesong/OpenClash/assets/24912536/c710e7ce-728c-4445-865b-e048cd165a93)
