### ISSUE TITLE
[Feature] 如何让wechat不走代理呢？

### ISSUE THREAD

**Issue by cjlhll** [vernesong/OpenClash#3926]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经**使用最新 Dev 版本**查看过，并不包含该功能特性或者还不完善
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 应包含的特性
- [ ] Contributors 我有能力协助 OpenClash 开发或完善此功能特性
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### Describe the Feature

wechat部分域名只针对手机有效，可以用规则匹配直连，但是pc端wechat全是ip，ip还总变。有没有什么办法让openclash 能全局让wechat走直连呢？不然都默认走漏网之鱼了，导致发消息，发图片各种都很慢，转圈。

**Comment by cjlhll** [comment]
> https://developers.weixin.qq.com/doc/offiaccount/Basic_Information/Get_the_WeChat_server_IP_address.html `由于出口IP及入口IP可能存在变动，建议用户每天请求接口1次，以便于及时更新IP列表。` 别人微信直接走cnip了.你不走cn就得自己想想办法了

微信是走cn。但是切换到wechat后就不是了。

**Comment by 2eronia** [comment]
应该不是全IP吧。你可以考虑用 nameserver-policy

```
    nameserver-policy:
        "geosite:tencent":
            - "填自己ISP运营商的本地DNS"
```

我之前用其他梯子软件比如Passwall2，配合两个AdGuardHome分组，其中一个经验就是微信的图片加载，用阿里DNS或者DNSpod都不太行，换成ISP的本地DNS才流畅。

**Comment by vialib** [comment]
https://github.com/vialib/ASN-China/blob/main/IP.ASN.China.yaml

**Comment by cjlhll** [comment]
> https://github.com/vialib/ASN-China/blob/main/IP.ASN.China.yaml

这规则也太多了。影响性能吧。
