### ISSUE TITLE
[Bug] IP地址SpeedTest不显示归属地。

### ISSUE THREAD

**Issue by zxlhhyccc** [vernesong/OpenClash#3928]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [X] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [X] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

v0.46.016-beta

### Bug on Environment

Official OpenWrt

### OpenWrt Version

r26740-66edb2f9ad

### Bug on Platform

Linux-arm64

### Describe the Bug

![image](https://github.com/vernesong/OpenClash/assets/45259624/d71e22d1-9dc8-44b3-b4b5-acc1a4cc15d8)

### To Reproduce

![image](https://github.com/vernesong/OpenClash/assets/45259624/6744d6b5-5f3e-4fba-86d7-0386b7085517)

### OpenClash Log

```log
无。
```

### Expected Behavior

修复显示归属地。

**Comment by hztbhtbh** [comment]
我发现在下面网址中speedtest.cn的IP地址也是：获取失败
但是游览器输入域名speedtest.cn还是能打开的
https://ip.skk.moe/
![B)Z%)AN69WS6511Q2VTKM1P](https://github.com/vernesong/OpenClash/assets/104251804/fdddf632-98b4-4654-bfac-90c861798da6)

**Comment by zxlhhyccc** [comment]
@hztbhtbh 是滴，可能是这个域名获取不到IP问题。

**Comment by hztbhtbh** [comment]
#3854

**Comment by i0668** [comment]
> #3854 这个帖子可以解决，替换myip.htm内容即可

请问可否提供一下你修改后的myip.htm文件呢

**Comment by hztbhtbh** [comment]
> > #3854 这个帖子可以解决，替换myip.htm内容即可
> 
> 请问可否提供一下你修改后的myip.htm文件呢

下载解压替换：https://wwl.lanzouq.com/iEqad248u9yd

**Comment by i0668** [comment]
> > > #3854 这个帖子可以解决，替换myip.htm内容即可
> > 
> > 
> > 请问可否提供一下你修改后的myip.htm文件呢
> 
> 下载解压替换：https://wwl.lanzouq.com/iEqad248u9yd 也可以去下面网址打开全部复制-粘贴-替换： https://github.com/vernesong/OpenClash/raw/dev/luci-app-openclash/luasrc/view/openclash/myip.htm

听我说谢谢你，因为有你，温暖了四季

**Comment by Seaspirit** [comment]
> myip.htm

myip.htm在哪个目录啊？

**Comment by huoshan12345** [comment]
现在用dev的myip.htm替换后显示的是`你访问的网站盗用了 https://ip.skk.moe 的源码和接口`
![QQ截图20240917134656](https://github.com/user-attachments/assets/677323af-916b-418d-831a-b91bf0638333)
