### ISSUE TITLE
[Bug] 防火墙规则中，IP地址填写IPv6后缀时，暴露的端口不通

### ISSUE THREAD

**Issue by kfstorm** [vernesong/OpenClash#3929]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [ ] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

v0.45.157-beta

### Bug on Environment

Official OpenWrt

### OpenWrt Version

OpenWrt 22.03.5 r20134-5f15225c1e / LuCI openwrt-22.03 branch git-23.119.80898-65ef406

### Bug on Platform

Linux-arm64

### Describe the Bug

我的网络环境开启了IPv6，我想把内网一台设备的某个端口暴露到外网。因为IPv6前缀会经常变，所以我在OpenWrt的防火墙中配置了一个IPv6后缀，参考的是[OpenWrt的文档](::b241:6fff:fe0f:4346/-64
)。具体规则如下：

（为了避免暴露我的IPv6地址，以下我虚构一个内网设备的IPv6地址：`1234:1234:1234:1234:1234:1234:1234:1234`。）

```
firewall.cfg1192bd=rule
firewall.cfg1192bd.target='ACCEPT'
firewall.cfg1192bd.name='Allow-XXX'
firewall.cfg1192bd.dest='lan'
firewall.cfg1192bd.family='ipv6'
firewall.cfg1192bd.src='wan'
firewall.cfg1192bd.proto='tcp'
firewall.cfg1192bd.dest_port='10000'
firewall.cfg1192bd.dest_ip='::1234:1234:1234:1234/-64'
```

这样配置后，我从公网访问这个设备的10000端口时，发现访问不通。但是把防火墙规则里的IP地址换成完整的IPv6地址就能通，规则如下：

```
firewall.cfg1192bd=rule
firewall.cfg1192bd.target='ACCEPT'
firewall.cfg1192bd.name='Allow-XXX'
firewall.cfg1192bd.dest='lan'
firewall.cfg1192bd.family='ipv6'
firewall.cfg1192bd.src='wan'
firewall.cfg1192bd.proto='tcp'
firewall.cfg1192bd.dest_port='10000'
firewall.cfg1192bd.dest_ip='1234:1234:1234:1234:1234:1234:1234:1234'
```

使用`nft monitor trace`后发现填写后缀时，防火墙可以正常放过入站流量，但是出站流量有问题。和填写完整IPv6地址时的trace对比后发现，填写完整IPv6地址时出站流量有这样的日志：

```
trace id 111a0705 inet fw4 openclash_mangle_v6 verdict return
trace id 111a0705 inet fw4 mangle_prerouting verdict continue
trace id 111a0705 inet fw4 mangle_prerouting policy accept
```

但是在同样的位置，填写IPv6后缀时出站流量是这样的日志：

```
trace id 755fd3d6 inet fw4 openclash_mangle_v6 rule meta nfproto ipv6 tcp dport 0-65535 meta mark set 0x00000162 tproxy ip6 to :7895 counter packets 19 bytes 1520 accept comment "OpenClash TCP Tproxy" (verdict accept)
```

最后发现是`openclash_mangle_v6`有问题。当填写IPv6后缀时，`openclash_mangle_v6`链中没有对应的规则。当填写完整IPv6规则时，`openclash_mangle_v6`链中有对应的规则。所以在`openclash_mangle_v6`链中加入了对应的规则。

填写IPv6后缀时的`openclash_mangle_v6`链：

```
chain openclash_mangle_v6 {
		meta nfproto ipv6 udp sport 24853 counter packets 0 bytes 0 return
		meta nfproto ipv6 udp sport 500 counter packets 0 bytes 0 return
		ip6 saddr fc00::/6 udp sport 546 counter packets 0 bytes 0 return
		ip6 daddr @localnetwork6 counter packets 5091 bytes 4266390 return
		meta nfproto ipv6 udp dport 53 counter packets 0 bytes 0 return
		ip6 daddr @china_ip6_route ip6 daddr != @china_ip6_route_pass counter packets 544 bytes 105979 return
		meta nfproto ipv6 tcp dport 0-65535 meta mark set 0x00000162 tproxy ip6 to :7895 counter packets 0 bytes 0 accept comment "OpenClash TCP Tproxy"
		meta nfproto ipv6 udp dport 0-65535 meta mark set 0x00000162 tproxy ip6 to :7895 counter packets 0 bytes 0 accept comment "OpenClash UDP Tproxy"
	}
```

填写完整IPv6地址时的`openclash_mangle_v6`链：

```
chain openclash_mangle_v6 {
		ip6 saddr 1234:1234:1234:1234:1234:1234:1234:1234 tcp sport 10000 counter packets 0 bytes 0 return
		meta nfproto ipv6 udp sport 24853 counter packets 0 bytes 0 return
		meta nfproto ipv6 udp sport 500 counter packets 0 bytes 0 return
		ip6 saddr fc00::/6 udp sport 546 counter packets 0 bytes 0 return
		ip6 daddr @localnetwork6 counter packets 681 bytes 316235 return
		meta nfproto ipv6 udp dport 53 counter packets 0 bytes 0 return
		ip6 daddr @china_ip6_route ip6 daddr != @china_ip6_route_pass counter packets 39 bytes 14661 return
		meta nfproto ipv6 tcp dport 0-65535 meta mark set 0x00000162 tproxy ip6 to :7895 counter packets 0 bytes 0 accept comment "OpenClash TCP Tproxy"
		meta nfproto ipv6 udp dport 0-65535 meta mark set 0x00000162 tproxy ip6 to :7895 counter packets 0 bytes 0 accept comment "OpenClash UDP Tproxy"
	}
```

填写完整IPv6地址时，`openclash_mangle_v6`链中多了一条`ip6 saddr 1234:1234:1234:1234:1234:1234:1234:1234 tcp sport 10000 counter packets 0 bytes 0 return`规则。

我试着关闭OpenClash，结果两种填法网络都是通的。一旦打开OpenClash后，填写IPv6后缀的规则就不通了。

### To Reproduce

见上面

### OpenClash Log

```log
见上面
```

### Expected Behavior

希望能支持防火墙规则中填写IPv6后缀。

**Comment by jelly21fish** [comment]
感觉改代码比较困难，因为实际上有一个转换的过程，可以试试用这个办法来解决：https://github.com/vernesong/OpenClash/issues/3088#issuecomment-1463930866

**Comment by kfstorm** [comment]
@jelly21fish 明白了，就是自己去添加nft规则。我试试。感谢。
