### ISSUE TITLE
[Feature] 内核应在编译时就打包进去，而不是后面下载

### ISSUE THREAD

**Issue by dragon888888888888** [vernesong/OpenClash#3937]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经**使用最新 Dev 版本**查看过，并不包含该功能特性或者还不完善
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 应包含的特性
- [ ] Contributors 我有能力协助 OpenClash 开发或完善此功能特性
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### Describe the Feature

1：编译时的环境不需要其它操作就可以完成
2：内核并不经常更新，现在的都是23年的
所以为什么不在编译时就打包，而是后面再下载

**Comment by SQ528** [comment]
并不是所有人都是软路由，我们硬路由就那么大，怎么可能

**Comment by dragon888888888888** [comment]
> 并不是所有人都是软路由，我们硬路由就那么大，怎么可能

像SSR那样可以选择就可以了 3个内核 编译时可以全选 也可以一个不选

**Comment by BugOrBug** [comment]
@dragon888888888888 
自己编译

`# 集成内核
cd ~/lede/package/luci-app-openclash/root/etc/openclash

# 更新 GeoIP 数据库
curl -sfL -o ./Country.mmdb https://github.com/alecthw/mmdb_china_ip_list/raw/release/lite/Country.mmdb
curl -sfL -o ./GeoSite.dat https://github.com/Loyalsoldier/v2ray-rules-dat/raw/release/geosite.dat
curl -sfL -o ./GeoIP.dat https://github.com/Loyalsoldier/v2ray-rules-dat/raw/release/geoip.dat

mkdir ./core && cd ./core

# 下载 TUN 内核
curl -fL -o ./tun.gz "https://raw.githubusercontent.com/vernesong/OpenClash/core/dev/premium/clash-linux-amd64"-"$(curl -sfL https://raw.githubusercontent.com/vernesong/OpenClash/core/dev/core_version | sed -n "2{s/\r$//;p;q}")".gz
gzip -d ./tun.gz && mv ./tun ./clash_tun

# 下载 Meta 内核
curl -fL -o ./meta.tar.gz "https://raw.githubusercontent.com/vernesong/OpenClash/core/dev/meta/clash-linux-amd64.tar.gz"
tar -zxf ./meta.tar.gz && mv ./clash ./clash_meta

# 下载 Dev 内核
curl -sfL -o ./dev.tar.gz "https://raw.githubusercontent.com/vernesong/OpenClash/core/dev/dev/clash-linux-amd64.tar.gz"
tar -zxf ./dev.tar.gz

chmod +x ./clash* ; rm -rf ./*.gz`

**Comment by BugOrBug** [comment]
@dragon888888888888 编译时候自己打包吧

```
# 集成内核
cd ~/lede/package/luci-app-openclash/root/etc/openclash

# 更新 GeoIP 数据库
curl -sfL -o ./Country.mmdb https://github.com/alecthw/mmdb_china_ip_list/raw/release/lite/Country.mmdb
curl -sfL -o ./GeoSite.dat https://github.com/Loyalsoldier/v2ray-rules-dat/raw/release/geosite.dat
curl -sfL -o ./GeoIP.dat https://github.com/Loyalsoldier/v2ray-rules-dat/raw/release/geoip.dat

mkdir ./core && cd ./core

# 下载 TUN 内核
curl -fL -o ./tun.gz "https://raw.githubusercontent.com/vernesong/OpenClash/core/dev/premium/clash-linux-amd64"-"$(curl -sfL https://raw.githubusercontent.com/vernesong/OpenClash/core/dev/core_version | sed -n "2{s/\r$//;p;q}")".gz
gzip -d ./tun.gz && mv ./tun ./clash_tun

# 下载 Meta 内核
curl -fL -o ./meta.tar.gz "https://raw.githubusercontent.com/vernesong/OpenClash/core/dev/meta/clash-linux-amd64.tar.gz"
tar -zxf ./meta.tar.gz && mv ./clash ./clash_meta

# 下载 Dev 内核
curl -sfL -o ./dev.tar.gz "https://raw.githubusercontent.com/vernesong/OpenClash/core/dev/dev/clash-linux-amd64.tar.gz"
tar -zxf ./dev.tar.gz

chmod +x ./clash* ; rm -rf ./*.gz
```
