### ISSUE TITLE
[Bug] 开启“仅代理命中规则流量”会匹配到部分带有“announce”的域名直连

### ISSUE THREAD

**Issue by GeekXtop** [vernesong/OpenClash#3942]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [ ] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

最新版

### Bug on Environment

Immortalwrt

### OpenWrt Version

ImmortalWrt 23.05.1 r27304-31bc47589e / LuCI openwrt-23.05 branch git-23.313.50115-e3df634

### Bug on Platform

Linux-arm64

### Describe the Bug

开启“仅代理命中规则流量”会匹配到部分带有“announce”的域名直连

选项描述：
附加规则到配置文件，仅允许匹配规则的流量代理，防止 BT、P2P 下载流量经过代理

通过搜索代码发现，开启该选项实际上是增加了几条关键字规则，
但是会导致一些带有该关键字的子域名匹配到该规则导致代理失效

### To Reproduce

比如 
```
- DOMAIN-KEYWORD,announce
```
命中
```
https://announcements.bybit.com/zh-tw
```
本来该域名是走代理的,但是子域名却优先匹配到该规则导致代理失效
```
- DOMAIN-KEYWORD,torrent
```
命中
```
torrentgalaxy.to
```
直接把大部分种子站都给屏蔽了~~

### OpenClash Log

```log
24-06-30 02:11:40[ warn ][TCP] dial DIRECT (match DomainKeyword/announce) 10.0.0.181:4681 --> announcements.bybit.com:443 error: dial tcp 103.39.76.66:443: i/o timeout dial tcp 128.242.245.212:443: i/o timeout dial tcp 128.242.240.155:443: i/o timeout dial tcp 162.125.32.6:443: i/o timeout dial tcp 185.45.7.165:443: i/o timeout dial tcp 69.171.228.74:443: i/o timeout dial tcp 157.240.15.8:443: i/o timeout dial tcp 128.121.243.228:443: i/o timeout
```

### Expected Behavior

感觉该选项可能并不能达到想要的效果
而且描述也有点不太清楚
可能我不该在没有准确理解该选项意思的情况下就勾选

所以来反馈一下

**Comment by vernesong** [comment]
规则写的比较暴力，下载需求建议还是直接绕过
