### ISSUE TITLE
[Bug] 覆写设置-规则设置-自定义规则，使用Proxy，启动报错，error: proxy [Proxy] not found

### ISSUE THREAD

**Issue by loohalh** [vernesong/OpenClash#3946]
### OpenClash Version

v0.46.014-beat

### Bug on Environment

Official OpenWrt

### OpenWrt Version

bleach plus build 20220412 @ OpenWrt R22.4.1 / LuCI Master (git-22.095.24346-72703c8)

### Bug on Platform

Linux-386, Linux-amd64(x86-64)

### Describe the Bug

覆写设置-规则设置-自定义规则，使用Proxy，启动报错，error: proxy [Proxy] not found

### To Reproduce

覆写设置-规则设置-自定义规则，打开使用优先匹配中的## - DOMAIN,google.com,Proxy #匹配域名(交由Proxy代理服务器组)规则即可复现，启动日志报错为 ：2024-07-04 23:38:18 level=error msg="rules[3] [DOMAIN,google.com,Proxy] error: proxy [Proxy] not found"

<img width="893" alt="image" src="https://github.com/vernesong/OpenClash/assets/16890588/d90709b7-b3df-43aa-a20c-a0e0c3ab8939">

<img width="1034" alt="image" src="https://github.com/vernesong/OpenClash/assets/16890588/c0461bc0-df0f-4d58-a9ce-d35e504c1863">

### OpenClash Log

```log
2024-07-04 23:38:18 level=error msg="rules[3] [DOMAIN,google.com,Proxy] error: proxy [Proxy] not found"
2024-07-04 23:38:18 level=info msg="Geosite Matcher implementation: succinct"
2024-07-04 23:38:18 level=info msg="Geodata Loader mode: memconservative"
2024-07-04 23:38:18 level=info msg="Start initial configuration in progress"
```

**Comment by VMatrices** [comment]
Proxy只是实例，需要替换成你实际规则里的代理组名


```yaml
rules:
  - DOMAIN-KEYWORD,test-ipv6,DIRECT
  - DOMAIN-KEYWORD,torrent,🚀 节点选择
  - DOMAIN-KEYWORD,speedtest,🎯 全球直连
  - DOMAIN,surrit,🎯 全球直连
  - DOMAIN,access.pikpak.me,🚀 节点选择
  - DOMAIN,access.mypikpak.net,🚀 节点选择
  - DOMAIN-REGEX,^dl-.+mypikpak.com$,🎯 全球直连
  . . . . . .
 ```

**Comment by loohalh** [comment]
> Proxy只是示例名称，需要替换成你实际规则里的代理组名
> 
> ```yaml
> rules:
>   - DOMAIN-KEYWORD,test-ipv6,DIRECT
>   - DOMAIN-KEYWORD,torrent,🚀 节点选择
>   - DOMAIN-KEYWORD,speedtest,🎯 全球直连
>   - DOMAIN,surrit,🎯 全球直连
>   - DOMAIN,access.pikpak.me,🚀 节点选择
>   - DOMAIN,access.mypikpak.net,🚀 节点选择
>   - DOMAIN-REGEX,^dl-.+mypikpak.com$,🎯 全球直连
>   ...
> ```

原来是这样啊 ，谢谢

**Comment by loohalh** [comment]
> > Proxy只是示例名称，需要替换成你实际规则里的代理组名
> > ```yaml
> > rules:
> >   - DOMAIN-KEYWORD,test-ipv6,DIRECT
> >   - DOMAIN-KEYWORD,torrent,🚀 节点选择
> >   - DOMAIN-KEYWORD,speedtest,🎯 全球直连
> >   - DOMAIN,surrit,🎯 全球直连
> >   - DOMAIN,access.pikpak.me,🚀 节点选择
> >   - DOMAIN,access.mypikpak.net,🚀 节点选择
> >   - DOMAIN-REGEX,^dl-.+mypikpak.com$,🎯 全球直连
> >   ...
> > ```
> 
> 原来是这样啊 ，谢谢

已解决

**Comment by wzgy** [comment]
那有没有变量的形式，方便在切换规则文件时自动适配？
