### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Speechless22** [vernesong/OpenClash#3948]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [ ] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

v0.46.014-beta

### Bug on Environment

Official OpenWrt

### OpenWrt Version

OpenWrt 23.05.3 r23809-234f1a2efa

### Bug on Platform

Linux-amd64(x86-64)

### Describe the Bug

配置中的规则集如果太大（条目10000+），会出现无法正常下载/加载的情况
例如[ACL4SSR_Online_Full_AdblockPlus.ini](https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/config/ACL4SSR_Online_Full_AdblockPlus.ini)配置中的[AdBlock](https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyList.list)和[隐私防护](https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyPrivacy.list)

### To Reproduce

使用在线订阅转换功能并配置如下
![image](https://github.com/vernesong/OpenClash/assets/61347609/005dd6d7-cd7d-4f3c-87ad-33a6208d36dd)

### OpenClash Log

```log
OpenClash 调试日志

生成时间: 2024-07-06 18:59:24
插件版本: v0.46.014-beta
隐私提示: 上传此日志前请注意检查、屏蔽公网IP、节点、密码等相关敏感信息



#===================== 系统信息 =====================#

主机型号: Beijin Cloud Times S13XS
固件版本: OpenWrt 23.05.3 r23809-234f1a2efa
LuCI版本: git-23.051.66410-a505bb1
内核版本: 5.15.150
处理器架构: x86_64

#此项有值时,如不使用IPv6,建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: server

DNS劫持: Dnsmasq 转发
#DNS劫持为Dnsmasq时，此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 127.0.0.1#7874

#===================== 依赖检查 =====================#

dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
libcap: 已安装
libcap-bin: 已安装
ruby: 已安装
ruby-yaml: 已安装
ruby-psych: 已安装
ruby-pstore: 已安装
kmod-tun(TUN模式): 已安装
luci-compat(Luci >= 19.07): 已安装
kmod-inet-diag(PROCESS-NAME): 已安装
unzip: 已安装
kmod-nft-tproxy: 已安装

#===================== 内核检查 =====================#

运行状态: 运行中
运行内核：Meta
进程pid: 15637 8436
运行权限: 15637: =ep
8436: cap_dac_override,cap_net_bind_service,cap_net_admin,cap_net_raw,cap_sys_ptrace,cap_sys_resource=eip
运行用户: nobody
已选择的架构: linux-amd64

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 2023.08.17-13-gdcc8d87
Tun内核文件: 存在
Tun内核运行权限: 正常

Dev内核版本: v1.18.0-13-gd034a40
Dev内核文件: 存在
Dev内核运行权限: 正常

Meta内核版本: alpha-g0d4e57c
Meta内核文件: 存在
Meta内核运行权限: 正常

#===================== 插件设置 =====================#

当前配置文件: /etc/openclash/config/CNIX.yaml
启动配置文件: /etc/openclash/CNIX.yaml
运行模式: redir-host
默认代理模式: rule
UDP流量转发(tproxy): 启用
自定义DNS: 停用
IPV6代理: 启用
IPV6-DNS解析: 启用
禁用Dnsmasq缓存: 启用
自定义规则: 停用
仅允许内网: 启用
仅代理命中规则流量: 启用
仅允许常用端口流量: 停用
绕过中国大陆IP: 启用
路由本机代理: 启用

#启动异常时建议关闭此项后重试
混合节点: 停用
保留配置: 停用

#启动异常时建议关闭此项后重试
第三方规则: 停用

#===================== 配置文件 =====================#

port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: info
external-controller: 0.0.0.0:9090

```
```


### OpenClash Config

_No response_

### Expected Behavior

较大数据量的规则集应当也能下载/加载成功

### Additional Context

_No response_

**Comment by minisind** [comment]
让专业的人做专业的事，
个人折腾大半年有余，心得就是直接使用ADGH做广告过滤吧，虽然滤不干净，但是加载，修改，自定义超级方便，CLASH就攻CLASH的专业吧。  
本来CLASH 就已经够大了，占用存储也很多。
