### ISSUE TITLE
[Feature] 大佬有没有考虑做一个docker版本的openwrt

### ISSUE THREAD

**Issue by Watercolor-tone** [vernesong/OpenClash#3952]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经**使用最新 Dev 版本**查看过，并不包含该功能特性或者还不完善
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 应包含的特性
- [ ] Contributors 我有能力协助 OpenClash 开发或完善此功能特性
- [X] Meaningless 我提交的**是无意义的**催促更新或修复请求

### Describe the Feature

装了很多docker版本的clash，发现都没有你这个好用，宁愿多装一个虚拟机再安装openclash。希望大佬能做一个docker版的。

**Comment by VMatrices** [comment]
openclash是为openwrt开发的，无法独立运行，并不适合做成容器

**Comment by tonyzhou777** [comment]
https://hub.docker.com/r/wanuse/openwrt-x86-64
这个Docker镜像好使，记得用以下issue里的方式，添加启动参数
https://github.com/vernesong/OpenClash/issues/1915
