### ISSUE TITLE
关闭OpenClash科学上网后DNS转发不能恢复成smartdns的转发，造成无法上网。

### ISSUE THREAD

**Issue by feiche** [vernesong/OpenClash#396]
使用OpenClash发现一个问题，我是OpenClash+smartdns组合使用，smartdns设置为Dnsmasq的上游服务器，在科学上网的时候OpenClash会自动把DHCP/DNS里的DNS转发到127.0.0.1#7874，但是关闭后不会恢复成smartdns的转发地址即127.0.0.1#6053，这样就造成关闭OpenClash后无法上网，需要手动在去设置下，希望能改进下，在启动的时候不会删除smartdns已经设置的DNS转发地址，而是直接在添加一条OpenClash的DNS转发地址，关闭的时候只删除OpenClash的DNS转发，这样就不会影响关闭后的正常上网了。
![1](https://user-images.githubusercontent.com/6387321/80385244-6bbbba80-88d8-11ea-8c7f-331151fc10ca.png)
![2](https://user-images.githubusercontent.com/6387321/80385262-70806e80-88d8-11ea-8f05-d9ff4baf49de.png)
![3](https://user-images.githubusercontent.com/6387321/80385272-737b5f00-88d8-11ea-93fb-b34e7837a832.png)
![4](https://user-images.githubusercontent.com/6387321/80385296-7a09d680-88d8-11ea-982a-43b8de44b5d2.png)

**Comment by zxlhhyccc** [comment]
> 使用OpenClash发现一个问题，我是OpenClash+smartdns组合使用，smartdns设置为Dnsmasq的上游服务器，在科学上网的时候OpenClash会自动把DHCP/DNS里的DNS转发到127.0.0.1#7874，但是关闭后不会恢复成smartdns的转发地址即127.0.0.1#6053，这样就造成关闭OpenClash后无法上网，需要手动在去设置下，希望能改进下，在启动的时候不会删除smartdns已经设置的DNS转发地址，而是直接在添加一条OpenClash的DNS转发地址，关闭的时候只删除OpenClash的DNS转发，这样就不会影响关闭后的正常上网了。
> ![1](https://user-images.githubusercontent.com/6387321/80385244-6bbbba80-88d8-11ea-8c7f-331151fc10ca.png)
> ![2](https://user-images.githubusercontent.com/6387321/80385262-70806e80-88d8-11ea-8f05-d9ff4baf49de.png)
> ![3](https://user-images.githubusercontent.com/6387321/80385272-737b5f00-88d8-11ea-93fb-b34e7837a832.png)
> ![4](https://user-images.githubusercontent.com/6387321/80385296-7a09d680-88d8-11ea-982a-43b8de44b5d2.png)

openclash的上游服务器知道什么意思么。。。。？

**Comment by pikachullk** [comment]
openclash的DNS设置那不是有个自定义上游DNS服务器吗?

**Comment by feiche** [comment]
已经弄好了，搞混了，现在理解了，谢谢！

**Comment by iam3ddy** [comment]
> 已经弄好了，搞混了，现在理解了，谢谢！

请问您怎么解决？

本地DNS劫持：停用
自定义上游DNS服务器（加了127.0.0.1:6053)
配置文件编辑: DNS-> listen:0.0.0.0:53
