### ISSUE TITLE
[Feature] 希望增加非TUN模式，只监听 7890 mix-port 端口

### ISSUE THREAD

**Issue by cesaryuan** [vernesong/OpenClash#3961]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经**使用最新 Dev 版本**查看过，并不包含该功能特性或者还不完善
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 应包含的特性
- [ ] Contributors 我有能力协助 OpenClash 开发或完善此功能特性
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### Describe the Feature

出于一些原因，我默认情况下不需要TUN模式来代理所有流量，只需在使用的时候显式指定 `软路由IP:7890` 为http_proxy即可，因此在这种情况下，希望允许关闭TUN模式（全局代理模式），但是保持clash.meta在后台运行并监听 7890 mix-port 端口

**Comment by vernesong** [comment]
你可以直接屏蔽掉启动脚本的防火墙命令

**Comment by Private0xCC** [comment]
@cesaryuan 兄弟你解决这个问题了吗？我有和你一样的需求

**Comment by Private0xCC** [comment]
> 你可以直接屏蔽掉启动脚本的防火墙命令

请问一下，防火墙命令在哪个脚本文件中

**Comment by vernesong** [comment]
/etc/init.d/openclash 里启动得第六步和第七步

**Comment by Private0xCC** [comment]
根据作者的提示，我把/etc/init.d/openclash中的函数set_firewall屏蔽了(改为空实现)，能达到预期。
 希望作者大大 @vernesong 可以界面上添加该功能的选项，感激不尽

**Comment by vernesong** [comment]
加这个干啥，你直接启动内核不就行了
