### ISSUE TITLE
[Bug] OpenClash 启动失败，尝试使用原始配置文件启动...

### ISSUE THREAD

**Issue by wujun4code** [vernesong/OpenClash#3964]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [X] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

v0.46.014-beta

### Bug on Environment

Immortalwrt

### OpenWrt Version

ImmortalWrt 23.05.3 r27917-81a1f98d5b / LuCI openwrt-23.05 branch git-24.092.44091-d24c2e3

### Bug on Platform

Linux-arm64

## 路由器信息如下

主机名称 | ImmortalWrt
-- | --
型号 | Nokia EA0326GMP
架构 | ARMv8 Processor rev 4 (v8l) x 2
目标平台 | mediatek/filogic
固件版本 | ImmortalWrt 23.05.3 r27917-81a1f98d5b / LuCI openwrt-23.05 branch git-24.092.44091-d24c2e3
内核版本 | 5.15.162

## 错入日志如下

```
2024-07-21 21:39:44 第六步：删除 OpenClash 残留文件...
2024-07-21 21:39:39 第五步: 重启 Dnsmasq 程序...
2024-07-21 21:39:39 第四步: 关闭 Clash 主程序...
2024-07-21 21:39:39 第三步: 关闭 OpenClash 守护程序...
2024-07-21 21:39:39 第二步: 删除 OpenClash 防火墙规则...
2024-07-21 21:39:39 第一步: 备份当前策略组状态...
2024-07-21 21:39:39 OpenClash 开始关闭...
2024-07-21 21:39:38 错误：无法获取 General 部分的转发端口设置, OpenClash 使用原始配置文件启动失败
2024-07-21 21:39:38 错误：无法获取 DNS 部分的运行模式设置, OpenClash 使用原始配置文件启动失败
2024-07-21 21:39:37 错误：OpenClash 启动失败，尝试使用原始配置文件启动...
2024-07-21 21:39:25 第六步: 等待主程序下载外部文件...
2024-07-21 21:39:22 第五步: 检查内核启动状态...
2024-07-21 21:39:21 配置文件【/etc/openclash/clash.sub.yaml】测试成功...
2024-07-21 21:39:12 启动前调用内核测试配置文件...
2024-07-21 21:39:12 提示：检测到配置了 TUN 内核专属功能，调用 TUN 内核启动...
2024-07-21 21:39:12 第四步: 启动主程序...
2024-07-21 21:39:12 提示：开始运行自定义覆写脚本...
2024-07-21 21:39:11 提示：您为 SOCKS5/HTTP(S) 代理设置的账户密码为【Clash:xB377hDa】
2024-07-21 21:39:10 第三步: 修改配置文件...
2024-07-21 21:39:10 第二步: 组件运行前检查...
2024-07-21 21:39:09 第一步: 获取配置...
2024-07-21 21:39:09 OpenClash 开始启动...
2024-07-21 21:39:09 第六步：删除 OpenClash 残留文件...
2024-07-21 21:39:04 第五步: 重启 Dnsmasq 程序...
2024-07-21 21:39:04 第四步: 关闭 Clash 主程序...
2024-07-21 21:39:04 第三步: 关闭 OpenClash 守护程序...
2024-07-21 21:39:04 第二步: 删除 OpenClash 防火墙规则...
2024-07-21 21:39:03 第一步: 备份当前策略组状态...
2024-07-21 21:39:03 OpenClash 开始关闭...
2024-07-21 21:39:03 OpenClash 重新启动中...
```

我尝试过修改配置，并且切换了 master 和 developer 两个分支，都是一样的错误。

### OpenClash Log

```log
2024-07-21 21:39:44 第六步：删除 OpenClash 残留文件...
2024-07-21 21:39:39 第五步: 重启 Dnsmasq 程序...
2024-07-21 21:39:39 第四步: 关闭 Clash 主程序...
2024-07-21 21:39:39 第三步: 关闭 OpenClash 守护程序...
2024-07-21 21:39:39 第二步: 删除 OpenClash 防火墙规则...
2024-07-21 21:39:39 第一步: 备份当前策略组状态...
2024-07-21 21:39:39 OpenClash 开始关闭...
2024-07-21 21:39:38 错误：无法获取 General 部分的转发端口设置, OpenClash 使用原始配置文件启动失败
2024-07-21 21:39:38 错误：无法获取 DNS 部分的运行模式设置, OpenClash 使用原始配置文件启动失败
2024-07-21 21:39:37 错误：OpenClash 启动失败，尝试使用原始配置文件启动...
2024-07-21 21:39:25 第六步: 等待主程序下载外部文件...
2024-07-21 21:39:22 第五步: 检查内核启动状态...
2024-07-21 21:39:21 配置文件【/etc/openclash/clash.sub.yaml】测试成功...
2024-07-21 21:39:12 启动前调用内核测试配置文件...
2024-07-21 21:39:12 提示：检测到配置了 TUN 内核专属功能，调用 TUN 内核启动...
2024-07-21 21:39:12 第四步: 启动主程序...
2024-07-21 21:39:12 提示：开始运行自定义覆写脚本...
2024-07-21 21:39:11 提示：您为 SOCKS5/HTTP(S) 代理设置的账户密码为【Clash:xB377hDa】
2024-07-21 21:39:10 第三步: 修改配置文件...
2024-07-21 21:39:10 第二步: 组件运行前检查...
2024-07-21 21:39:09 第一步: 获取配置...
2024-07-21 21:39:09 OpenClash 开始启动...
2024-07-21 21:39:09 第六步：删除 OpenClash 残留文件...
2024-07-21 21:39:04 第五步: 重启 Dnsmasq 程序...
2024-07-21 21:39:04 第四步: 关闭 Clash 主程序...
2024-07-21 21:39:04 第三步: 关闭 OpenClash 守护程序...
2024-07-21 21:39:04 第二步: 删除 OpenClash 防火墙规则...
2024-07-21 21:39:03 第一步: 备份当前策略组状态...
2024-07-21 21:39:03 OpenClash 开始关闭...
2024-07-21 21:39:03 OpenClash 重新启动中...
```

### OpenClash Config

```shell
没有任何特殊设置
```

### Expected Behavior

我有 3 台 openwrt 设备

- istoreos 的 r5s 最新版固件+ 最新版 openclash，正常运行
- linux arm 架构下的 docker 跑 immoralwrt 最新版虚拟机固件+ openclash 最新版，也是正常运行
- NOKIA EA0326GMP 使用 https://github.com/easy-programming-guide/NOKIA-EA0326GMP/tree/main 这个固件是可以完美运行 openclash 最新版的

现在我用的是 immortalwrt 官方最新固件 https://firmware-selector.immortalwrt.org/?version=23.05.3&target=mediatek%2Ffilogic&id=nokia_ea0326gmp

就出现了这个问题。

**Comment by wujun4code** [comment]
基本可以确定是 opewrt 23 版本上的一些修改引发了跟 openclash 的不兼容，我四台完全不同架构，不同固件，不同版本的 openclash 综合测试
- openwrt 21 版本上的都没问题
- openwrt 23  包括 immortalwrt 23 都有问题

**Comment by calidion** [comment]
openwrt x86_64 最新版本也是一样的情况，无法使用。

**Comment by wujun4code** [comment]
@calidion 你用 [openwrt.ai ](https://openwrt.ai/?target=x86%2F64&id=generic) 生成 x86 的固件，然后编译的时候 按照我这个选择

![image](https://github.com/user-attachments/assets/b10e1452-14c2-4801-9b00-65f1a5708045)

就可以完美运行 openclash，后装 openclash 大多数都无法正常运行，一定要在编译期把内核组件一起编译。

**Comment by calidion** [comment]
我使用的是openwrt原始版本。通过命令行与网页都不能安装成功。

**Comment by wujun4code** [comment]
@calidion 我尝试过你的步骤，原始的 openwrt 版本我从未安装 openclash 成功过，哪怕安装了，也跑不起来，跑起来了，也会出问题，跑一会儿就重启，然后就死了，所以我强烈推荐自己编译，编译的时候一定要引入 kmod 几个内核服务一起编译，我保证你的 openwrt 版本对应的 kmod-ipt-nat 和 kmod-tun 都找不到，我试过从零 openwrt 开始，找对应版本的 kmod-tun，根本找不到，因此唯一的解决方案就是自定义编译。

**Comment by calidion** [comment]
为什么这个插件不能兼容官方的插件系统？

**Comment by wujun4code** [comment]
@calidion 不是不兼容，是你用的 官方的固件 并没有把 kmod 所有组件都编译进去，这个不可能把内核一起给你编译，你看它的安装教程的第一步就是让你安装基于你目前系统的官方组件

```
#nftables
opkg update
opkg install coreutils-nohup bash dnsmasq-full curl ca-certificates ipset ip-full libcap libcap-bin ruby ruby-yaml kmod-tun kmod-inet-diag unzip kmod-nft-tproxy luci-compat luci luci-base
```
你看到的  `kmod` 开头的全都是内核组件，而你用的官方的固件并没有把这几个固件都编译进去，所以导致 openclash 不能用。
结论就是：openclash 不可能针对每一个版本的内核都编译对应的内核组件，因为那是你系统本来就应该有的，你看一下你的内核版本是多少，如果是 openwrt 官方的固件一般都很精简，根本用不了，缺一大堆内核组件，这锅是 openwrt 官方自己的。

**Comment by calidion** [comment]
我装了这些固件一样安装运行不了。
openclash还要自己下载软件什么的。好像。
看起来像是spyware.

**Comment by wujun4code** [comment]
@calidion 是的，你经历过的这些我都经历过，最终的解决方案是：放弃官方 openwrt 纯净版，在 openwrt.ai 或者在 https://firmware-selector.immortalwrt.org/ 这里选择固件，更进一步是在 github 上找能让你自定义编译固件的开源 github action，然后你自己研究一下编译脚本，把 

```
 coreutils-nohup bash dnsmasq-full curl ca-certificates ipset ip-full libcap libcap-bin ruby ruby-yaml kmod-tun kmod-inet-diag unzip kmod-nft-tproxy luci-compat luci luci-base
```
这些组件都编译进去，因为这些组件都跟你所使用的 内核版本，不是 openwrt 版本，openwrt 版本目前是 21或者23 是主流，而内核版本有的是 5.4 有的是 5.5 还有一些是 5.6，`kmod-tun kmod-inet-diag unzip kmod-nft-tproxy` 这几个组件跟内核版本息息相关，必须统一到小数点个位数的版本号，你装了的那些可能是兼容版本，那些只是兼容你目前的 openwrt 版本，不代表一定能运行起来。

我甚至自己下载过`kmod-tun kmod-inet-diag unzip kmod-nft-tproxy` 这几个版本对应我的 openwrt 内核，但是就因为小数点版本号不兼容，我死也装不上 openclash，最后我放弃了，决定自定义编译，再次劝退 官方 openwrt 的 snapshot 版本，那个是给路由器厂商的参考标准，不是民用级别的固件，*纯净版是绝对无法正常使用的。*

**Comment by calidion** [comment]
> 这些组件都编译进去，因为这些组件都跟你所使用的 内核版本，不是 openwrt 版本，openwrt 版本目前是 21或者23 是主流，而内核版本有的是 5.4 有的是 5.5 还有一些是 5.6，`kmod-tun kmod-inet-diag unzip kmod-nft-tproxy` 这几个组件跟内核版本息息相关，必须统一到小数点个位数的版本号，你装了的那些可能是兼容版本，那些只是兼容你目前的 openwrt 版本，不代表一定能运行起来。

我是x86_64的。安装完成了。但是不能使用。

**Comment by calidion** [comment]
![2024-08-08 13-23-59屏幕截图](https://github.com/user-attachments/assets/7f41498b-a0c8-4613-814e-49760ac136b2)

**Comment by calidion** [comment]
```
Executing package manager
Unknown package 'luci-app-openclash'.
Errors
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency dnsmasq-full for luci-app-openclash
 * pkg_hash_check_unresolved: cannot find dependency coreutils-nohup for luci-app-openclash
 * pkg_hash_check_unresolved: cannot find dependency bash for luci-app-openclash
 * pkg_hash_check_unresolved: cannot find dependency ipset for luci-app-openclash
 * pkg_hash_fetch_best_installation_candidate: Packages for luci-app-openclash found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package luci-app-openclash.
The opkg install command failed with code 255.

```

**Comment by calidion** [comment]
```
root@OpenWrt:~# opkg install dnsmasq-full coreutils-nohup bash ipset 
Unknown package 'dnsmasq-full'.
Unknown package 'coreutils-nohup'.
Unknown package 'bash'.
Unknown package 'ipset'.
Collected errors:
 * opkg_install_cmd: Cannot install package dnsmasq-full.
 * opkg_install_cmd: Cannot install package coreutils-nohup.
 * opkg_install_cmd: Cannot install package bash.
 * opkg_install_cmd: Cannot install package ipset.
root@OpenWrt:~# opkg update
Downloading https://downloads.openwrt.org/snapshots/targets/x86/64/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_core
Downloading https://downloads.openwrt.org/snapshots/targets/x86/64/packages/Packages.sig
Signature check failed.
Remove wrong Signature file.
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/base/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_base
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/base/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/snapshots/targets/x86/64/kmods/6.6.43-1-7d4380a42289459dbd4f03be492ca992/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_kmods
Downloading https://downloads.openwrt.org/snapshots/targets/x86/64/kmods/6.6.43-1-7d4380a42289459dbd4f03be492ca992/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/luci/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_luci
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/luci/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_packages
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/packages/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/routing/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_routing
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/routing/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/telephony/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_telephony
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/telephony/Packages.sig
Signature check passed.
root@OpenWrt:~# opkg install dnsmasq-full coreutils-nohup bash ipset 
Installing dnsmasq-full (2.90-r2) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/base/dnsmasq-full_2.90-r2_x86_64.ipk
Installing libnettle8 (3.9.1-r1) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/base/libnettle8_3.9.1-r1_x86_64.ipk
Installing libnfnetlink0 (1.0.2-r1) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/base/libnfnetlink0_1.0.2-r1_x86_64.ipk
Installing kmod-nf-conntrack-netlink (6.6.43-r1) to root...
Downloading https://downloads.openwrt.org/snapshots/targets/x86/64/kmods/6.6.43-1-7d4380a42289459dbd4f03be492ca992/kmod-nf-conntrack-netlink_6.6.43-r1_x86_64.ipk
Installing libnetfilter-conntrack3 (1.0.9-r2) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/base/libnetfilter-conntrack3_1.0.9-r2_x86_64.ipk
Installing coreutils-nohup (9.3-r1) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/packages/coreutils-nohup_9.3-r1_x86_64.ipk
Installing bash (5.2.21-r1) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/packages/bash_5.2.21-r1_x86_64.ipk
Installing terminfo (6.4-r2) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/base/terminfo_6.4-r2_x86_64.ipk
Installing libncurses6 (6.4-r2) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/base/libncurses6_6.4-r2_x86_64.ipk
Installing libreadline8 (8.2-r2) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/base/libreadline8_8.2-r2_x86_64.ipk
Installing ipset (7.21-r1) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/base/ipset_7.21-r1_x86_64.ipk
Installing kmod-ipt-ipset (6.6.43-r1) to root...
Downloading https://downloads.openwrt.org/snapshots/targets/x86/64/kmods/6.6.43-1-7d4380a42289459dbd4f03be492ca992/kmod-ipt-ipset_6.6.43-r1_x86_64.ipk
Installing libipset13 (7.21-r1) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/base/libipset13_7.21-r1_x86_64.ipk
Configuring terminfo.
Configuring libncurses6.
Configuring libreadline8.
Configuring bash.
Configuring libnfnetlink0.
Configuring kmod-nf-conntrack-netlink.
Configuring libnetfilter-conntrack3.
Configuring kmod-ipt-ipset.
Configuring libipset13.
Configuring ipset.
Configuring libnettle8.
Configuring coreutils-nohup.
Configuring dnsmasq-full.
Collected errors:
 * resolve_conffiles: Existing conffile /etc/config/dhcp is different from the conffile in the new package. The new conffile will be placed at /etc/config/dhcp-opkg.
root@OpenWrt:~# 


```

**Comment by calidion** [comment]
Executing package manager
Package luci-app-openclash (0.46.014-beta) installed in root is up to date.
Errors
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 6.6.44~2e398c67f090c3654e410bca7e776644-r1) for kmod-nf-reject
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 6.6.44~2e398c67f090c3654e410bca7e776644-r1) for kmod-nf-reject6
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 6.6.44~2e398c67f090c3654e410bca7e776644-r1) for kmod-nf-log
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 6.6.44~2e398c67f090c3654e410bca7e776644-r1) for kmod-nf-log6
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 6.6.44~2e398c67f090c3654e410bca7e776644-r1) for kmod-crypto-crc32c
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 6.6.44~2e398c67f090c3654e410bca7e776644-r1) for kmod-nft-core
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 6.6.44~2e398c67f090c3654e410bca7e776644-r1) for kmod-nf-ipt
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 6.6.44~2e398c67f090c3654e410bca7e776644-r1) for kmod-ipt-core
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 6.6.44~2e398c67f090c3654e410bca7e776644-r1) for kmod-tun

**Comment by calidion** [comment]
各种错误，不断出现。似乎不能通过 安装 pkg解决

**Comment by wujun4code** [comment]
```
pkg_hash_check_unresolved: cannot find dependency kernel (= 6.6.44~2e398c67f090c3654e410bca7e776644-r1) for kmod-crypto-crc32c
```
这就是我说的，内核没有编译进去，所以你根本用不了，放弃吧。。。

**Comment by calidion** [comment]
这些内核模块好像是可以指定的。我有时间再看看。

**Comment by calidion** [comment]
> 这个问题其实很好解决 panckge底下有一个kernel开头的ipk文件，opkg update以后，先手动装完这个文件然后装别的kmod文件就行

有没有代码级教程？

**Comment by calidion** [comment]
> opkg update opkg list 找到个kernel开头的ipk opkg install kernel-xxxxx.ipk
> 
> 然后再安装别的kmod 重新opkg update后记得检查kernel文件 同时内核不能跨版本 6.1的不能装6.6的

还是不行。

**Comment by wujun4code** [comment]
哈哈哈，最终还是走向了自定义编译。。。来吧 https://openwer.ai 选择 x86 一样的。哈哈哈

**Comment by markixy** [comment]
@wujun4code 大佬，能帮忙解答下嘛？情况描述：#4020
目前点启动OpenClash按钮，页面提示“第二步: 配置文件检查...”（截图如下），然后没反应了，运行日志没有任何输出。~.~
![启动openclash，卡在第二步：检查配置  ](https://github.com/user-attachments/assets/ae1c9535-e648-4aa6-a0d5-c3831d3db9f5)
![image](https://github.com/user-attachments/assets/e8c101a4-691a-4616-8626-c9d802790795)

**Comment by markixy** [comment]
使用 OpenWrt 23.05.4 (r24012-d8dd03c46f) + OpenClash v0.46.014-beta 可以正常运行以及代理。
![image](https://github.com/user-attachments/assets/7dd02eb5-efe6-4d9f-882d-cefac6bf1fb4)

**Comment by tanbamboo** [comment]
openwork.ai能支持Netgear X6 R8000吗？

**Comment by wujun4code** [comment]
@tanbamboo 你路由器可能不支持刷机。。。

**Comment by tanbamboo** [comment]
> @tanbamboo 你路由器可能不支持刷机。。。

谢谢，已经工作正常

**Comment by tanbamboo** [comment]
@wujun4code 了解，谢谢

**Comment by yiqiquhuxi** [comment]
@calidion 田大佬， 解决了吗？

**Comment by calidion** [comment]
> [@calidion](https://github.com/calidion) 田大佬， 解决了吗？

没有。后来感觉还是客户端trojan比较实用。

**Comment by Ass-Sniper** [comment]
这问题今天让我遇到了。。。自己摸索解决了。结论先行：在【插件设置】【版本更新】中，点击【一键检查更新】后自己就恢复了，chatgpt说【一键检查更新】重新生成覆写配置，生成临时 YAML = 原始订阅 + OpenClash 覆写
2025-12-12 19:52:20 错误:无法获取 general 部分的转发端口设置, openclash 使用原始配置文件启动失败 
2025-12-12 19:52:20 错误:无法获取 dns 部分的运行模式设置, openclash 使用原始配置文件启动失败 
2025-12-12 19:52:20 错误:无法获取 dns 部分的监听端口设置, openclash 使用原始配置文件启动失败 
2025-12-12 19:52:19 错误:openclash 启动失败,尝试使用原始配置文件启动...
