### ISSUE TITLE
luci界面提示权限不足

### ISSUE THREAD

**Issue by Orokapei** [vernesong/OpenClash#397]
Insufficient permissions to read UCI configuration.
仅运行状态页面及运行日志页面提示，其他界面正常
![image](https://user-images.githubusercontent.com/23261300/80482299-8fd5d500-8986-11ea-9f20-3551b37af005.png)
![image](https://user-images.githubusercontent.com/23261300/80482325-9f551e00-8986-11ea-9f26-cd4c79d120e8.png)
现在是通过其他界面启动按钮启动了，暂时不怎么影响使用（查看issues然后看到/usr/share/rpcd/acl.d/luci-app-openclash.json 是有的）

**Comment by Orokapei** [comment]
啊，不对，是假启动（dns转发啥的都没设置成功）= =

**Comment by zxlhhyccc** [comment]
> 啊，不对，是假启动（dns转发啥的都没设置成功）= =

回退官方luci-compat里的map.htm即可。。。。

**Comment by poemsiu** [comment]
> > 啊，不对，是假启动（dns转发啥的都没设置成功）= =
> 
> 
> 
> 回退官方luci-compat里的map.htm即可。。。。

具体怎么操作啊？
