### ISSUE TITLE
[Bug] 勾选 禁用 QUIC，网页访问 chatgpt.com 无效，某些请求会直连，无法登录和聊天

### ISSUE THREAD

**Issue by fgpzen** [vernesong/OpenClash#3972]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [ ] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

v0.46.016-beta

### Bug on Environment

Official OpenWrt

### OpenWrt Version

OpenWrt 23.05.0 r23497-6637af95aa

### Bug on Platform

Linux-mipsle-softfloat

### Describe the Bug

插件设置已勾选 **禁用 QUIC**、**UDP 流量转发**，PC端和Android端的Chrome 浏览器 QUIC 都是默认设置（开启）

chatgpt.com 官网使用了 QUIC协议

测试手机端 Chrome 浏览器访问 chatgpt.com 会提示 Unable to load site，无法访问，并且会显示我的真实IP。
- 关闭 手机端 Chrome 浏览器QUIC可以解决问题，但是仅限于支持关闭QUIC的浏览器。
- 或者开启手机端的clash meta / 设置wifi代理 都可以解决QUIC问题正常访问chatgpt网页。

PC端 测试 Chromium 一样也不能访问。（我测试的时候发现 Chrome 浏览器访问 chatgpt.com 是可以正常访问，经过排查应该是SwitchyOmega插件接管了代理影响了。）

**禁用 QUIC** 选项没有对chatgpt网页生效。

### To Reproduce

PC端和Android端的Chrome 浏览器 QUIC 都是默认设置（开启）

在openwrt环境下，手机端 浏览器访问 chatgpt.com，然后点击登录或聊天，就会提示 Unable to load site，并且显示ip地址

### OpenClash Log

```log
（已删除）
```

### OpenClash Config

- [x] 使用 Meta 内核
- [x] 禁用 QUIC
- [x] UDP 流量转发
- 仅允许常用端口流量 **禁用**
- 机场节点支持 UDP

### Expected Behavior

插件设置 勾选 **禁用 QUIC** 可以对 Android/Ipad 手机端网页访问 chatgpt.com 生成，能在手机端网页正常登录使用 chatgpt.com

### Additional Context

![IMG_20240729_101135](https://github.com/user-attachments/assets/d32ec1a5-5cd4-461f-9390-03f72ce92465)

**Comment by vernesong** [comment]
```
iptables -I INPUT -p udp --dport 443 -m comment --comment "OpenClash QUIC REJECT" -j REJECT

试试这个防火墙命令

**Comment by vernesong** [comment]
可能是收到了大陆ip库的影响，因为不会屏蔽国内ip的quic

**Comment by fgpzen** [comment]
> 可能是收到了大陆ip库的影响，因为不会屏蔽国内ip的quic

感谢作者回复。没有测试防火墙命令😂，但现在突然又可以正常用chatgpt.com了😂，我也不知道为啥。
