### ISSUE TITLE
[Bug] 大量“socket: protocol not supporte”相关报错

### ISSUE THREAD

**Issue by Ellean** [vernesong/OpenClash#3976]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [ ] Definite 这确实是 OpenClash 出现的问题
- [X] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

v0.45.121-beta

### Bug on Environment

Other

### OpenWrt Version

OpenWrt 21.02.1 r16325-88151b8303

### Bug on Platform

All

### Describe the Bug

1. 类似 `https://raw.githubusercontent.com/vernesong/OpenClash/dev/img/logo.png` 这样的地址无法访问，集中在 `raw.githubusercontent.com` ，不仅仅在浏览器发生
2. 大量 `socket: protocol not supported` 相关报错
例如我在使用如下命令时得到报错：
```
ssh -T git@github.com
kex_exchange_identification: Connection closed by remote host
Connection closed by 198.18.0.28 port 22
```
此时日志会报错如下：
```
2024-08-01 02:47:41 level=info msg="[TCP] 192.168.1.132:61355 --> github.com:22 match DomainKeyword(github) using Proxy[🇭🇰 香港 | V2 | 01]"
2024-08-01 02:47:40 level=debug msg="[Process] find process github.com: socket: protocol not supported"
2024-08-01 02:47:40 level=debug msg="[Rule] use default rules"
```

### To Reproduce

无明确步骤

### OpenClash Log

```log
附件
```

### Expected Behavior

正常访问

### Additional Context

[OpenClash 调试日志.txt](https://github.com/user-attachments/files/16446097/OpenClash.txt)

**Comment by Ellean** [comment]
补充一点，问题一用 Chrome 访问正常，Safari不正常

**Comment by vernesong** [comment]
![image](https://github.com/user-attachments/assets/c7c69587-50f3-4575-a21d-c20e9308f3cc)
