### ISSUE TITLE
[Bug] 自定义规则指向节点时，规则失效（如果指向分组规则是生效的）

### ISSUE THREAD

**Issue by madlbx** [vernesong/OpenClash#3977]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [ ] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

v0.46.014-beta

### Bug on Environment

Istoreos

### OpenWrt Version

istoreos-22.03 branch (git-24.207.28853-3b34de8) / ArgonTheme v2.2.10.10 / iStoreOS 22.03.7 2024080210

### Bug on Platform

Linux-amd64(x86-64)

### Describe the Bug

在自定义规则中设置某个DOMAIN-SUFFIX规则，规则指向某个特定代理服务器，代理是不起作用的，而指向分组，规则是生效的。
eg.

#失效规则，"日本-03"是一个特定的服务器，即一个节点
`- DOMAIN-SUFFIX,claude.ai,日本-03`
#有效规则，“代理”是一个分组
`- DOMAIN-SUFFIX,claude.ai,代理`

此Bug在v0.46.014-beta存在，回退到v0.46.011-beta Bug消失。

### To Reproduce

1. 覆写设置->规则设置->自定义规则
2. 增加规则  `- DOMAIN-SUFFIX,claude.ai,节点`
3. 建议使用日本节点。
4. 使用浏览器登录claude.ai网站

Bug现象：在中国境内网络，浏览器显示页面是不提供服务相关字样。

### OpenClash Log

```log
已退回v0.46.011，没有抓到Log，但我有两个设备在46.014都出现同样问题，回退到46.011版本问题消失。
```

### Expected Behavior

期待现象：DOMAIN-SUFFIX 后指向单独节点的时候，节点能生效，在上边复现步骤里，期望能进入claude的登录页面。

**Comment by vernesong** [comment]
我记得本身就是只能写策略组

**Comment by madlbx** [comment]
> 我记得本身就是只能写策略组

好尴尬呀~v0.46.011和之前的一个版本我都是写单独节点名的 -_-！，要不我改一下Bug描述，描述成之前可以写单独节点是Bug现象？？O(∩_∩)O玩笑玩笑。

之所以尝试写单独节点也是因为我的机场默认分组没有AI分组，我手动增加分组，一更新订阅新增分组就没了，所以就尝试在规则写指定节点，忘了哪个版本，尝试写节点是好用的，然后就对特定网站如openai和claude.ai分别定义美国节点和日本节点，这样配置完都好用，直至46.014……

**Comment by madlbx** [comment]
> 换内核了吗？ 没log确实没法定位问题 而且这种不可能没log 你确定你是查的是开了debug的内核日志

没换内核~等哪天有空，我用公司的设备升到46.014抓抓log~
