### ISSUE TITLE
能否增加(翻墙模式下)中国国内网站直接直连功能？

### ISSUE THREAD

**Issue by sagan** [vernesong/OpenClash#398]
为了提高性能，对于中国国内网站，能否不通过 clash 透明代理，直接直连？毕竟国内网站需要用到规则的情况很少。

具体步骤：(以 fake-ip 模式为例)

1. 把 GEOIP 的中国IP存到 ipset 里
2. 在 iptables 里对于中国 IP 直接返回，不通过 clash 转发。
iptables -t nat -I openclash -m set --match-set china dst -j RETURN
如果开启 udp 转发，在 -t mangle openclash 里同样这样做
3. 整合 [dnsmasq-china-list](https://github.com/felixonmars/dnsmasq-china-list), 对常用的国内网站的DNS查询, 直接用 dnsmasq  走 114.114.114.114，不通过 clash。

以上自己用脚本也能做，但是能否直接集成到 openclash 里然后加个开关选项。这样会方便得多。

**Comment by maskedeken** [comment]
fake-ip模式下，客户端拿到的都是fake ip，没办法跟ipset里的中国ip比较

**Comment by GitHubd3b7c** [comment]
Fake IP模式就不能存 IP 了吧,拿到的都是假 IP ,域名还是有戏的
