### ISSUE TITLE
[Feature] 希望添加关闭劫持局域网53端口的开关

### ISSUE THREAD

**Issue by YuxuanZuo** [vernesong/OpenClash#3980]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经**使用最新 Dev 版本**查看过，并不包含该功能特性或者还不完善
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 应包含的特性
- [X] Contributors 我有能力协助 OpenClash 开发或完善此功能特性
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### Describe the Feature

在Fake-IP模式且开启绕过中国大陆的情况下，DNS劫持设置为dnsmsaq上游或停用时仍然会劫持局域网53端口，这会导致路由器部署wireguard时无法绕过代理。
经过定位，这一问题的原因可能由此处的代码导致：
https://github.com/vernesong/OpenClash/blob/dd5e07d891f12ab46830db4064f7a0e19a08f38d/luci-app-openclash/root/usr/share/openclash/openclash_watchdog.sh#L95-L102

### Describe Alternatives

请问是否可以添加一个默认开启的开关来控制这个行为？

**Comment by sqliuchang** [comment]
巧了，前一阵子玩校园网免流也遇到了这个问题，会导致无法将53端口的流量转发到wg的监听端口，个人是修改
https://github.com/vernesong/OpenClash/blob/a2ec35894484426ecc80ef1fec940ca28b43c0bc/luci-app-openclash/root/etc/init.d/openclash#L1614
这附近为
```
nft insert rule inet fw4 dstnat position 0 udp dport 53 ${ACBLACKDNSFILTER} ip saddr ${lan_ip}/24 counter redirect to "$DNSPORT" comment \"OpenClash DNS Hijack\"
