### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by GuangYu-yu** [vernesong/OpenClash#3988]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经**使用最新 Dev 版本**查看过，并不包含该功能特性或者还不完善
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 应包含的特性
- [ ] Contributors 我有能力协助 OpenClash 开发或完善此功能特性
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### Describe the Feature

在使用mwan3和fakeip的情况下，应该自动将mwan3的ping地址添加到绕过fakeip，这样就避免和mwan3冲突。增加两种模式，每一个节点向每一条宽带都发出ping，节点自动走ping最低的一条宽带，或者多条能ping通的宽带负载均衡，或者这两种模式中自动选择，不断根据网络情况选择最佳方式。

**Comment by vernesong** [comment]
手动加一下就行了
