### ISSUE TITLE
[Feature] `Mihomo`内核`fake-ip-filter`已经支持`rule-set`和`geosite`

### ISSUE THREAD

**Issue by ydoKFVJQDymJcb** [vernesong/OpenClash#3989]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经**使用最新 Dev 版本**查看过，并不包含该功能特性或者还不完善
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 应包含的特性
- [ ] Contributors 我有能力协助 OpenClash 开发或完善此功能特性
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### Describe the Feature

https://github.com/MetaCubeX/mihomo/commit/696b75ee375660bb8478ca94fe2f16b8ad2ff3c3
`Mihomo`内核`fake-ip-filter`已经支持`rule-set`和`geosite`

**Comment by moreoronce** [comment]
手动替换内核后可以在fake-ip-filter修改

**Comment by blngxj** [comment]
之前不是说过不考虑做这个的吗 XD， 不过既然支持了待mater更新后就可以用fake-ip了，现在路由端还在用redir-host，之前用fake-ip直连某域名会有connect 198.xx failed/time out  错误，路由端flush fake-ip和客户端 flush dns 都清理了还是这样，用redir-host直接无误了，支持这个feature能改善fake-ip下直连的问题。v佬更新之后打算再试试fake-ip

**Comment by qq6510** [comment]
支持    - rule-set:fakeip-filter,DIRECT   吗？
