### ISSUE TITLE
关于编译openwrt时候集成openclash同时加入clash内核的问题？

### ISSUE THREAD

**Issue by CrazyMouse** [vernesong/OpenClash#399]
想请教一下，如果要在编译L大的固件的时候集成openclash，且保证之后更新固件的时候，直接能开机使用，有几个问题想请教一下：

1. 如果要集成clash内核，我想用github action自动去处理，clash内核最新的下载地址是啥？

2.如果正常下载了clash内核，是否需要执行chmod脚本进行授权？

3.编译的时候集成了clash内核的话，是否影响后续页面的手动更新clash内核？

**Comment by vernesong** [comment]
```bash
curl -sL -m 30 --retry 2 https://github.com/vernesong/OpenClash/releases/download/Clash/clash-"$CPU_MODEL".tar.gz -o /tmp/clash.tar.gz
tar zxvf /tmp/clash.tar.gz -C /tmp >/dev/null 2>&1
chmod +x /tmp/clash >/dev/null 2>&1
mkdir -p /etc/openclash/core
mv /tmp/clash /etc/openclash/core/clash >/dev/null 2>&1
rm -rf /tmp/clash.tar.gz >/dev/null 2>&1
```

**Comment by CrazyMouse** [comment]
> ```shell
> curl -sL -m 30 --retry 2 https://github.com/vernesong/OpenClash/releases/download/Clash/clash-"$CPU_MODEL".tar.gz -o /tmp/clash.tar.gz
> tar zxvf /tmp/clash.tar.gz -C /tmp >/dev/null 2>&1
> chmod +x /tmp/clash >/dev/null 2>&1
> mkdir -p .../package/luci-app-openclash/files/etc/openclash/core
> mv /tmp/clash .../package/luci-app-openclash/files/etc/openclash/core/clash >/dev/null 2>&1
> rm -rf /tmp/clash.tar.gz >/dev/null 2>&1
> ```

收到，非常感谢！

**Comment by CrazyMouse** [comment]
`# Clone 项目
mkdir package/luci-app-openclash
cd package/luci-app-openclash
git init
git remote add -f origin https://github.com/vernesong/OpenClash.git
git config core.sparsecheckout true
echo "luci-app-openclash" >> .git/info/sparse-checkout
git pull origin master
git branch --set-upstream-to=origin/master master`

这个clone下来的目录会变成/package/luci-app-openclash/luci-app-openclash，有个嵌套，因此上面的代码可能需要多加一层luci-app-openclash   
@vernesong

**Comment by LIKE2000-ART** [comment]
> `# Clone 项目 mkdir package/luci-app-openclash cd package/luci-app-openclash git init git remote add -f origin https://github.com/vernesong/OpenClash.git git config core.sparsecheckout true echo "luci-app-openclash" >> .git/info/sparse-checkout git pull origin master git branch --set-upstream-to=origin/master master`
> 
> 这个clone下来的目录会变成/package/luci-app-openclash/luci-app-openclash，有个嵌套，因此上面的代码可能需要多加一层luci-app-openclash
> @vernesong

Linux小白，大佬能写一下您完整的命令么谢谢了555

**Comment by LIKE2000-ART** [comment]
> > ```shell
> > curl -sL -m 30 --retry 2 https://github.com/vernesong/OpenClash/releases/download/Clash/clash-"$CPU_MODEL".tar.gz -o /tmp/clash.tar.gz
> > tar zxvf /tmp/clash.tar.gz -C /tmp >/dev/null 2>&1
> > chmod +x /tmp/clash >/dev/null 2>&1
> > mkdir -p .../package/luci-app-openclash/files/etc/openclash/core
> > mv /tmp/clash .../package/luci-app-openclash/files/etc/openclash/core/clash >/dev/null 2>&1
> > rm -rf /tmp/clash.tar.gz >/dev/null 2>&1
> > ```
> 
> 收到，非常感谢！

这样集成的内核是只有DEV分支么。。。。如果是的话如何整合其他内核。。。Linux小白已经不懂了555

**Comment by windybird** [comment]
> > ```shell
> > curl -sL -m 30 --retry 2 https://github.com/vernesong/OpenClash/releases/download/Clash/clash-"$CPU_MODEL".tar.gz -o /tmp/clash.tar.gz
> > tar zxvf /tmp/clash.tar.gz -C /tmp >/dev/null 2>&1
> > chmod +x /tmp/clash >/dev/null 2>&1
> > mkdir -p .../package/luci-app-openclash/files/etc/openclash/core
> > mv /tmp/clash .../package/luci-app-openclash/files/etc/openclash/core/clash >/dev/null 2>&1
> > rm -rf /tmp/clash.tar.gz >/dev/null 2>&1
> > ```
> 
> 收到，非常感谢！

你可以了？我怎么试了不行啊
