### ISSUE TITLE
[Bug] v0.46.018-beta不管是否勾选绕过大陆，都会过一遍核心导致访问国内网站延迟很高

### ISSUE THREAD

**Issue by eightsheep67** [vernesong/OpenClash#3990]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [X] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [X] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

v0.46.018-beta

### Bug on Environment

Lean

### OpenWrt Version

2024.08.12 @ OpenWrt R24.8.1 / Lede - 18.06

### Bug on Platform

Linux-amd64(x86-64)

### Describe the Bug

不管是否勾选绕过大陆，都会过一遍核心导致访问国内网站延迟很高，降回v0.46.016-beta问题解决

### To Reproduce

不管是否勾选绕过大陆，都会过一遍核心导致访问国内网站延迟很高

### OpenClash Log

```log
无
```

### Expected Behavior

修复绕过大陆的配置

**Comment by kojiqi** [comment]
不会呀，很正常

**Comment by eightsheep67** [comment]
> 不会呀，很正常

同样设置，18就国内百度搜索200多延迟，就是走了代理，降回16就25

**Comment by xuanranran** [comment]
> 不会呀，很正常

18版是有这个BUG，默认匹配443到代理，不仅仅baidu，sogou，weixin，qq这些域名都会默认匹配443端口到代理，但是过那么一分钟就好了，但是重启成功还是会这样的

**Comment by vernesong** [comment]
走内核控制面板会有记录

**Comment by eightsheep67** [comment]
> 走内核控制面板会有记录

有记录，在yacd的连接里都能看到小红书等国内网站的访问链接，走的全球直连。正常绕过大陆的情况下是不会出现在这里的。
我试过在18beta把那个绕过大陆设置，停用后再应用，以防它设置不生效，但是结果是一样的。openclash首页的网站访问检查中百度搜索一直延迟在200ms以上。用回16beta就恢复正常25ms

**Comment by redblackbst** [comment]
有同样的问题。

**Comment by kojiqi** [comment]
> > 走内核控制面板会有记录
> 
> 有，在yacd的连接里都能看到小红书等国内网站的访问链接，走的全球直连。正常绕过大陆的情况下是不会出现在这里的。 我在18beta测试过把那个绕过大陆设置，失效重新应用，设置不生效，但是结果是一样的。openclash首页的网站访问检查中百度搜索一直延迟在200ms以上。用回16beta就恢复正常25ms

我升级完确实没有问题，访问百度，sina等国内网站，在控制面板里都没有这些网站的记录。只有apple，google这两个国内服务的一些连接数据，走的是规则直连。

**Comment by Fddh2012** [comment]
v0.46.018-beta
这个版本国内的确会延迟特别高。

**Comment by Fddh2012** [comment]
> v0.46.018-beta 这个版本国内的确会延迟特别高。

临时解决办法：启用第二 DNS 服务器，把国内域名放进去。

**Comment by vernesong** [comment]
fakeip会先走内核等dnsmasq正常

**Comment by eightsheep67** [comment]
> fakeip会先走内核等dnsmasq正常

我这边使用的是redir兼容

**Comment by d407565739** [comment]
哪来的v0.46.018-beta啊

**Comment by Aethersailor** [comment]
fake-ip模式没有遇到这个问题

**Comment by redblackbst** [comment]
发现不是v0.46.018的问题，内核回退到[Meta core: alpha-g7fd0467](https://github.com/vernesong/OpenClash/commit/1ac92ff42081f658b946973cbca641b9db2fab1d)就正常了。

**Comment by missing233** [comment]
> 发现不是v0.46.018的问题，内核回退到[Meta core: alpha-g7fd0467](https://github.com/vernesong/OpenClash/commit/1ac92ff42081f658b946973cbca641b9db2fab1d)就正常了。

可以去meta内核repo提一下issue看看？
