### ISSUE TITLE
[Feature] 修改插件设置文本

### ISSUE THREAD

**Issue by mai1202** [vernesong/OpenClash#3994]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经**使用最新 Dev 版本**查看过，并不包含该功能特性或者还不完善
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 应包含的特性
- [ ] Contributors 我有能力协助 OpenClash 开发或完善此功能特性
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### Describe the Feature

建议在 插件设置 - 外部控制 - 管理登录页面密钥 一项下方加上说明，不要填写符号作为密钥。
我一开始使用密码生成器生成了类似`GVCuik|fn"2v"]<=`的密码，结果用不了控制面板。后来发现密钥是通过URL传入的，故修改为数字+字母后可用。

**Comment by xuelide** [comment]
搭车顺便建议，既然都去掉了clash [dev&tun core support] 了，把meta的文案也改成mihomo吧。

**Comment by missing233** [comment]
v0.46.014-beta测试了一下`GVCuik|fn"2v"]<=`，控制面板正常，没有问题
