### ISSUE TITLE
[Bug] 无法通过luci界面下载内核

### ISSUE THREAD

**Issue by codetiger666** [vernesong/OpenClash#3995]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [X] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [X] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

v0.46.020-beta

### Bug on Environment

Other

### OpenWrt Version

X-WRT 24.04_b202408182159 Noble

### Bug on Platform

Linux-arm64

### Describe the Bug

无法通过luci界面下载内核，设备空间足够
![image](https://github.com/user-attachments/assets/dcdf4b36-18d7-4244-bd9e-607e848760df)
![Uploading image.png…]()

### To Reproduce

下载内核失败

### OpenClash Log

```log
2024-08-21 18:17:39 【Meta】版本内核更新失败，请确认设备闪存空间足够或内核平台正确后再试！
2024-08-21 18:17:37 【Meta】版本内核下载成功，开始更新...
2024-08-21 18:17:35 【Meta】版本内核正在下载，如下载失败请尝试手动下载并上传...
2024-08-21 18:15:52 警告：OpenClash 目前处于未启用状态，请从插件页面启动本插件，脚本退出...
```

### Expected Behavior

可以正常下载内核

**Comment by caserangle** [comment]
我也是碰到这个情况了，换回master分支下以前的内核才好的

**Comment by codetiger666** [comment]
> 我也是碰到这个情况了，换回master分支下以前的内核才好的

可能是内核名称不对，压缩包里的名叫clash,应该是clash_meta才对
