### ISSUE TITLE
[Bug]  find-process-mode 设置为off配置文件检查不通过

### ISSUE THREAD

**Issue by liumingan** [vernesong/OpenClash#3996]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [X] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [X] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

.020

### Bug on Environment

Official OpenWrt

### OpenWrt Version

OpenWrt SNAPSHOT r27194-a2662309aa / LuCI Master 24.212.79282~65b8002

### Bug on Platform

Linux-armv5

### Describe the Bug

#  find-process-mode has 3 values:always, strict, off
#  - always, 开启，强制匹配所有进程
#  - strict, 默认，由 mihomo 判断是否开启
#  - off, 不匹配进程，推荐在路由器上使用此模式
 find-process-mode 设置为off配置文件检查不通过

### To Reproduce

 find-process-mode 设置为off

### OpenClash Log

```log
level=error msg="invalid find process mode"
```

### Expected Behavior

修复

**Comment by vernesong** [comment]
看下配置文件和内核版本

**Comment by jhdh487** [comment]
+1
