### ISSUE TITLE
[Bug] 绕过中国大陆IP功能对一些网站无效

### ISSUE THREAD

**Issue by missing233** [vernesong/OpenClash#3999]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [ ] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

v0.46.020-beta 

### Bug on Environment

Official OpenWrt

### OpenWrt Version

OpenWrt 23.05.2

### Bug on Platform

Linux-amd64(x86-64)

### Describe the Bug

如同此issue https://github.com/vernesong/OpenClash/issues/3990
设置绕过中国大陆后百度、小红书、qq.com等一系列常见国内网站流量都会走clash核心。
一些不常用的网站反而没有此问题，例如whois.pconline.com.cn反而正常直连了，即使订阅的配置文件中有此网站规则也不会进入核心
海外回国模式正常，观察控制面板中的连接没有出现过非大陆IP的连接

### To Reproduce

启用绕过中国大陆IP功能。
v0.46.014-beta到v0.46.020-beta，也更换过Meta内核版本，此问题仍然复现。

### OpenClash Log

[https://bin.disroot.org/?31e17415982f889e#FsDvVkSCv7YYhEyo8YRYUCA5RDQ7qZHycw4DqB4jS6tP](https://bin.disroot.org/?31e17415982f889e#FsDvVkSCv7YYhEyo8YRYUCA5RDQ7qZHycw4DqB4jS6tP)

### OpenClash Config

```shell
china_ip_route=1
china_ip6_route=1
```

### Expected Behavior

修复此问题

### Additional Context

测试环境宽带为日本au one net，无论是更新过海外回国模式的dev版本还是没更新的master分支版本都存在此问题，绕过中国大陆模式对部分网站无效，海外回国模式一切正常
怀疑与DNS有关，我的网络环境中DNS为谷歌和cloudflare以及ISP的DNS，没有指定国内的DNS服务器
由于暂时不在国内，无法测试此问题是否会出现在国内宽带环境中。

**Comment by hereVg0** [comment]
确实是这样，我发现似乎是META内核的问题，更新到alpha-gc4660e1，ip138显示在走代理，百度等国内网站延时非常高，甚至断网。更换了之前我备份的alpha-g09be5cb，更换后一切又正常了

**Comment by missing233** [comment]
> 确实是这样，我发现似乎是META内核的问题，更新到alpha-gc4660e1，ip138显示在走代理，百度等国内网站延时非常高，甚至断网。更换了之前我备份的alpha-g09be5cb，更换后一切又正常了
> 
> PS：刚刚更新到v0.46.020-beta，发现在版本更新选项只有META内核了，Dev和tun没有了吗？

我这边换成alpha-g09be5cb也无效，控制面板里一直都能看到百度小红书ip138。
DEV和tun内核是clash premium的吧？都删库outdated了

**Comment by ykhuazai** [comment]
我wegame加载巨慢，LOL玩不了一直提示断开连接。关掉clash立马恢复正常

**Comment by hereVg0** [comment]
> > 确实是这样，我发现似乎是META内核的问题，更新到alpha-gc4660e1，ip138显示在走代理，百度等国内网站延时非常高，甚至断网。更换了之前我备份的alpha-g09be5cb，更换后一切又正常了
> > PS：刚刚更新到v0.46.020-beta，发现在版本更新选项只有META内核了，Dev和tun没有了吗？
> 
> 我这边换成alpha-g09be5cb也无效，控制面板里一直都能看到百度小红书ip138。 DEV和tun内核是clash premium的吧？都删库outdated了

重启一次看看

**Comment by OldCoding** [comment]
还以为就我这有问题，英雄联盟一直站在泉水提示正在连接，但我把clash关了还是这样，总感觉是被修改了防火墙规则，导致游戏数据不知道被转发到哪去了

**Comment by OldCoding** [comment]
> 还以为就我这有问题，英雄联盟一直站在泉水提示正在连接，但我把clash关了还是这样，总感觉是被修改了防火墙规则，导致游戏数据不知道被转发到哪去了

我这个问题经过一天的排查找到原因了，跟openclash无关，原因出在linux内核上，最近两版6.6的内核有异常，6.6.47和6.6.46，导致游戏一致掉线重连

**Comment by ykhuazai** [comment]
我是iStoreOS 内核5.10.221，关掉插件一切正常，开起来就不行

**Comment by vernesong** [comment]
库更新一下

**Comment by vernesong** [comment]
![image](https://github.com/user-attachments/assets/403c5616-69c7-42ac-93cb-58ee69e59eea)
ipset的情况看不到，看是不是依赖问题

**Comment by missing233** [comment]
> ![image](https://private-user-images.githubusercontent.com/42875168/361386188-403c5616-69c7-42ac-93cb-58ee69e59eea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NzQ4NzYsIm5iZiI6MTcyNDY3NDU3NiwicGF0aCI6Ii80Mjg3NTE2OC8zNjEzODYxODgtNDAzYzU2MTYtNjljNy00MmFjLTkzY2ItNThlZTY5ZTU5ZWVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDEyMTYxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkOTcxMjkyNTg1NGRkMjQxNDBkNDA3ZWJhNjRkZWI1ZDIyMDZkZWM0Zjg5NGUzYTRhNTNkNWE3ZjJhYTRhNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ViJ-aYJ2KZQUWtvv7lg-M8b0uY1Ym_NDAg_Yn5u1KcI)
> ipset的情况看不到，看是不是依赖问题

请问具体是指哪些依赖呢

**Comment by missing233** [comment]
> ![image](https://private-user-images.githubusercontent.com/42875168/361386188-403c5616-69c7-42ac-93cb-58ee69e59eea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NzU5NDYsIm5iZiI6MTcyNDY3NTY0NiwicGF0aCI6Ii80Mjg3NTE2OC8zNjEzODYxODgtNDAzYzU2MTYtNjljNy00MmFjLTkzY2ItNThlZTY5ZTU5ZWVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDEyMzQwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2NjhkMjUxNTU0NDMxNmEwNDc4OTQxYzViYjRkZDEwMzY1ZjE1OGRlZDA4ODNiNTNlZjcwYTdlNDQ5YTcxYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.irKxZeb_8w8HhHwgJg_0ooLaTKadrpG5G3tOPPo5Ycs) ipset的情况看不到，看是不是依赖问题

安装了ipset-lists包后可以看到了：
https://bin.disroot.org/?430635285dfc2222#3CDveju7Yhg6p3Wrza8cqwZUWPdMLbbDJYME6WfGMZuT
这是新的日志

**Comment by vernesong** [comment]
你先把v6关了

**Comment by missing233** [comment]
> 你先把v6关了

我这边v4是走4in6隧道的，关V6就断网了。。

**Comment by vernesong** [comment]
/etc/openclash/china_ip6_route.ipset

看看这个文件

分别执行下面两个命令看看
```
nft 'flush set inet fw4 china_ip6_route'
nft -f '/etc/openclash/china_ip6_route.ipset'

**Comment by missing233** [comment]
> /etc/openclash/china_ip6_route.ipset
> 
> 看看这个文件
> 
> 分别执行下面两个命令看看
> 
> ```
> nft 'flush set inet fw4 china_ip6_route'
> nft -f '/etc/openclash/china_ip6_route.ipset'
> ```

https://bin.disroot.org/?d29ec4d07d1059c2#852SAs1mrH5tncGdzThSvQ3Qo9Ptz8JAh1Tpxy2fLkjL
内容上看起来没什么问题，下面两条命令也执行了

**Comment by vernesong** [comment]
那应该不是插件问题

**Comment by missing233** [comment]
> 那应该不是插件问题

好吧。回去看看大陆宽带的情况，不清楚这个诡异问题的原因。。反向回国是没有问题的

**Comment by missing233** [comment]
v0.46.022-beta依然存在此问题

**Comment by vernesong** [comment]
应该是内核的问题，dns处理逻辑有误，用新内核再试试吧

**Comment by OldCoding** [comment]
> 应该是内核的问题，dns处理逻辑有误，用新内核再试试吧

![image](https://github.com/user-attachments/assets/a45ecfdf-e0a2-4d4b-86db-b846109f09c4)
会不会跟openwrt补丁有关系，我更新了修复后的linux内核后没有这个问题了

**Comment by missing233** [comment]
> 应该是内核的问题，dns处理逻辑有误，用新内核再试试吧
> 

我的系统内核还是5.15.x

**Comment by vernesong** [comment]
clash内核，固件一般没人天天换

**Comment by missing233** [comment]
> clash内核，固件一般没人天天换

检查更新里没有新版本，应该是最新内核了。这个问题一直存在

**Comment by michaelchen644** [comment]
可能是ipv6绕过大陆ip没生效，我的dashboard里查看链接大部分都是走tproxy的ipv6直连链接。原来版本东北大学测速网显示的ipv6地址是测速设备的，现在变成路由器的地址了

**Comment by missing233** [comment]
> 可能是ipv6绕过大陆ip没生效，我的dashboard里查看链接大部分都是走tproxy的ipv6直连链接。原来版本东北大学测速网显示的ipv6地址是测速设备的，现在变成路由器的地址了

我这里V4V6绕过大陆均有存在失效情况，主要集中在百度小红书qq.com之类的网站。反而类似whois.pconline这种非热门网站能正常绕过

**Comment by michaelchen644** [comment]
已验证，退回v0.46.020后恢复正常

**Comment by xyz701** [comment]
> > 确实是这样，我发现好像是META内核的问题，更新到alpha-gc4660e1，ip138显示在走代理，百度等国内网站延迟非常高，甚至断网。在我备份的alpha-g09be5cb之前更换了，更换后又一切正常了
> > PS：刚刚更新到v0.46.020-beta，发现版本更新选项只有META内核了，Dev和tun没有吗？
> 
> 是我的也更新到v0.46.020-beta，Dev和tun没有了，有啥影响

我也一样，我是更新到v0.46.033-beta，Dev和Tun没有了，找的原因了吗？

**Comment by xyz701** [comment]
原来如此，感谢解答


fouvromenth ***@***.***> 于2024年9月27日周五 10:35写道：

**Comment by gungnirayu** [comment]
我两台路由，linux内核一样，都是6.6.69，open clash版本、内核、设置都一样，结果一台有这个问题，一台没有……
