### ISSUE TITLE
会支持ShadowSocksR吗？

### ISSUE THREAD

**Issue by Hscpro** [vernesong/OpenClash#40]
RT.

**Comment by MartialBE** [comment]
这个应该去[clash](https://github.com/Dreamacro/clash)项目中去 询问， 不过clash 作者明确表明不会支持ssr https://github.com/Dreamacro/clash/issues/37#issuecomment-437647621

**Comment by wangxin6** [comment]
是说的clashr吧？

**Comment by vernesong** [comment]
https://github.com/frainzy1477/luci-app-clash

暂时不会考虑，需要SSR你可以使用上面的版本
