### ISSUE TITLE
关于第三方规则的一些问题以及报错，想知道问题出自哪里

### ISSUE THREAD

**Issue by WinnieCrazyUniverse** [vernesong/OpenClash#400]
v神您好，在使用您的openclash时遇到了一些问题
首先在更新第三方lhie1规则系统提示信息如下
![QQ图片20200429225548](https://user-images.githubusercontent.com/62456649/80610999-9dfe2100-8a6c-11ea-9ca3-bd3e55599d28.png)
![QQ图片20200429225555](https://user-images.githubusercontent.com/62456649/80611047-af472d80-8a6c-11ea-853c-d5c6059d1dbc.png)
![QQ图片20200429225601](https://user-images.githubusercontent.com/62456649/80611058-b2421e00-8a6c-11ea-9757-9e6283be1f45.png)

相关运行日志如下：
time="2020-04-29T22:51:36+08:00" level=fatal msg="Parse config error: yaml: line 145: could not find expected ':'"
2020-04-29 22:51:27 OpenClash Can Not Start, Try Use Backup Rules Start Again
time="2020-04-29T22:51:39+08:00" level=info msg="Start initial compatible provider Proxy"
time="2020-04-29T22:51:39+08:00" level=info msg="Start initial compatible provider Domestic"
time="2020-04-29T22:51:39+08:00" level=info msg="Start initial compatible provider GlobalTV"
time="2020-04-29T22:51:39+08:00" level=info msg="Start initial compatible provider Others"
time="2020-04-29T22:51:39+08:00" level=info msg="Start initial compatible provider AsianTV"
2020-04-29 22:51:27 OpenClash Start Successful With Backup Rules Config, Please Check Or Update Other Rules And Retry
2020-04-29 22:51:24 Other Rules 【lhie1】 Update Successful

目前我找不到原因出自哪里，看了下配置文件管理里面的配置文件内容，貌似是我直接订阅的配置文件规则，第三方规则貌似没有被加入，目前很想使用lhie1的第三方规则，想请教应该怎么办？

**Comment by vernesong** [comment]
现在145行前后内容是什么

**Comment by WinnieCrazyUniverse** [comment]
> 现在145行前后内容是什么

订阅规则的143-147行内容如下：
- DOMAIN-SUFFIX,foxplay.com,GlobalTV
- DOMAIN-SUFFIX,ipinfo.io,GlobalTV
- DOMAIN-SUFFIX,mstage.io,GlobalTV
- DOMAIN-SUFFIX,now.com,GlobalTV
- DOMAIN-SUFFIX,theplatform.com,GlobalTV

**Comment by WinnieCrazyUniverse** [comment]
如果是第三方规则的145行的话，我具体不知道在哪里可以下载lhie1的rules

**Comment by WinnieCrazyUniverse** [comment]
![image](https://user-images.githubusercontent.com/62456649/80663218-f3b2e780-8ac5-11ea-88c1-e1a25fecda18.png)
这是目前最新的lhie1 rules的145行前后

**Comment by vernesong** [comment]
脱敏的配置文件发上来，敏感信息替换一下就行，发完整的

**Comment by WinnieCrazyUniverse** [comment]
[config.zip](https://github.com/vernesong/OpenClash/files/4556133/config.zip)
您好，这就是脱敏后的配置文件

**Comment by vernesong** [comment]
你发的配置文件没问题，你去全局设置-规则设置里面重新设定一下各个策略组的设置

**Comment by WinnieCrazyUniverse** [comment]
> 你发的配置文件没问题，你去全局设置-规则设置里面重新设定一下各个策略组的设置

好的，我试一下，谢谢v大

**Comment by WinnieCrazyUniverse** [comment]
> 你发的配置文件没问题，你去全局设置-规则设置里面重新设定一下各个策略组的设置

V大您好，问题解决了，我又仔细看了一下，问题是自定义规则出错了，改正后已正常，谢谢您的耐心帮助
