### ISSUE TITLE
[Bug] 安装依赖提示kmod-nft-core的依赖找不到

### ISSUE THREAD

**Issue by themikan** [vernesong/OpenClash#4000]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [X] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [X] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

v0.46.014-beta

### Bug on Environment

Istoreos

### OpenWrt Version

 iStoreOS 22.03.6 2024043010

### Bug on Platform

Linux-arm64

### Describe the Bug

根据v0.46.014-beta 的安装说明，在安装 ipk 文件前，需要安装相关依赖：
#iptables
opkg update
opkg install coreutils-nohup bash iptables dnsmasq-full curl ca-certificates ipset ip-full iptables-mod-tproxy iptables-mod-extra libcap libcap-bin ruby ruby-yaml kmod-tun kmod-inet-diag unzip luci-compat luci luci-base

获得报错：
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency kmod-nft-core for nftables-json
 * pkg_hash_fetch_best_installation_candidate: Packages for nftables-json found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kmod-nft-core for firewall4
 * pkg_hash_check_unresolved: cannot find dependency kmod-nft-fib for firewall4
 * pkg_hash_check_unresolved: cannot find dependency kmod-nft-offload for firewall4
 * pkg_hash_check_unresolved: cannot find dependency kmod-nft-nat for firewall4

### To Reproduce

执行
opkg install coreutils-nohup bash iptables dnsmasq-full curl ca-certificates ipset ip-full iptables-mod-tproxy iptables-mod-extra libcap libcap-bin ruby ruby-yaml kmod-tun kmod-inet-diag unzip luci-compat luci luci-base
命令后，系统提示：
Package coreutils-nohup (9.0-2) installed in root is up to date.
Package bash (5.2.15-1) installed in root is up to date.
Package iptables-zz-legacy (1.8.7-8) installed in root is up to date.
Package dnsmasq-full (2.89-4) installed in root is up to date.
Package curl (8.6.0-1) installed in root is up to date.
Package ca-certificates (20230311-1) installed in root is up to date.
Package ipset (7.15-2) installed in root is up to date.
Package ip-full (5.15.0-4) installed in root is up to date.
Package iptables-mod-tproxy (1.8.7-8) installed in root is up to date.
Package iptables-mod-extra (1.8.7-8) installed in root is up to date.
Package libcap (2.63-1) installed in root is up to date.
Package libcap-bin (2.63-1) installed in root is up to date.
Package ruby (3.0.6-1) installed in root is up to date.
Package ruby-yaml (3.0.6-1) installed in root is up to date.
Package kmod-tun (5.10.201-1) installed in root is up to date.
Package kmod-inet-diag (5.10.201-1) installed in root is up to date.
Package unzip (6.0-8) installed in root is up to date.
Package luci-compat (git-24.057.30647-6659faa) installed in root is up to date.
Package luci (git-23.093.42303-d58cd69) installed in root is up to date.
Package luci-base (git-24.208.65546-18f3914) installed in root is up to date.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency kmod-nft-core for nftables-json
 * pkg_hash_fetch_best_installation_candidate: Packages for nftables-json found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kmod-nft-core for firewall4
 * pkg_hash_check_unresolved: cannot find dependency kmod-nft-fib for firewall4
 * pkg_hash_check_unresolved: cannot find dependency kmod-nft-offload for firewall4
 * pkg_hash_check_unresolved: cannot find dependency kmod-nft-nat for firewall4

### OpenClash Log

```log
root...
Downloading https://mirrors.cernet.edu.cn/openwrt/releases/22.03.6/packages/aarch64_cortex-a53/packages/ruby-psych_3.0.6-1_aarch64_cortex-a53.ipk
Package kmod-tun (5.10.201-1) installed in root is up to date.
Package kmod-inet-diag (5.10.201-1) installed in root is up to date.
Package unzip (6.0-8) installed in root is up to date.
Package luci-compat (git-24.057.30647-6659faa) installed in root is up to date.
Package luci (git-23.093.42303-d58cd69) installed in root is up to date.
Upgrading luci-base on root from git-24.057.30647-6659faa to git-24.208.65546-18f3914...
Downloading https://mirrors.cernet.edu.cn/openwrt/releases/22.03.6/packages/aarch64_cortex-a53/luci/luci-base_git-24.208.65546-18f3914_aarch64_cortex-a53.ipk
Configuring ip-full.
Configuring curl.
Configuring luci-base.
Configuring libruby3.0.
Configuring ruby.
Configuring libdb47.
Configuring ruby-dbm.
Configuring libcap-bin.
Configuring ruby-digest.
Configuring ruby-enc.
Configuring ruby-pstore.
Configuring ruby-forwardable.
Configuring ruby-stringio.
Configuring ruby-bigdecimal.
Configuring ruby-date.
Configuring ruby-strscan.
Configuring libyaml.
Configuring ruby-psych.
Configuring ruby-yaml.
Configuring coreutils-nohup.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency kmod-nft-core for nftables-json
 * pkg_hash_fetch_best_installation_candidate: Packages for nftables-json found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kmod-nft-core for firewall4
 * pkg_hash_check_unresolved: cannot find dependency kmod-nft-fib for firewall4
 * pkg_hash_check_unresolved: cannot find dependency kmod-nft-offload for firewall4
 * pkg_hash_check_unresolved: cannot find dependency kmod-nft-nat for firewall4
 * resolve_conffiles: Existing conffile /etc/config/luci is different from the conffile in the new package. The new conffile will be placed at /etc/config/luci-opkg.
 * resolve_conffiles: Existing conffile /etc/config/ucitrack is different from the conffile in the new package. The new conffile will be placed at /etc/config/ucitrack-opkg.
```

### Expected Behavior

能正常下载依赖，或能正常运行 openClash

**Comment by WilliamLuuu** [comment]
kmod缺东西需要编译内核...

**Comment by themikan** [comment]
大佬，所以你的意思是，我安装的 istoreOS 版本有问题，缺少了东西咯？

**Comment by WayneLyn** [comment]
> 大佬，所以你的意思是，我安装的 istoreOS 版本有问题，缺少了东西咯？

最后怎么解决的？我也是istoreOS官方固件，R5S
