### ISSUE TITLE
最新内核活动连接过高

### ISSUE THREAD

**Issue by OleStore** [vernesong/OpenClash#401]
如图，这是更换之前的内核，活动连接数正常，从来没超1000，基本维持在150-600
![pic](https://user-images.githubusercontent.com/1283711/80662840-e9441e00-8ac4-11ea-91f0-60dd10eedb96.jpg)
更新之后，活动连接数2000以上，而且还慢慢往上飙，cpu温度从35升至45（忘了截图），日志正常，启动正常，ipk版本0.375，GitHub下载的，之前都是自己拉包编译，这次偷懒。。
系统：x86_64 Lean
运行时间：15天

补充：fake ip模式

当前内核v0.19.0-15-g065456f
之前v0.19.0-19-g5036f62也正常，电脑没备份

**Comment by vernesong** [comment]
连接情况控制面板里都有，现在有keep-alive，还有就是策略组测速间隔写大一点
