### ISSUE TITLE
[Bug] 使用meta内核，会让"本地 IPv4 绕过地址"失效

### ISSUE THREAD

**Issue by pure-white-ice-cream** [vernesong/OpenClash#4017]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [ ] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

v0.46.014-beta

### Bug on Environment

Immortalwrt

### OpenWrt Version

openwrt-21.02

### Bug on Platform

Linux-arm64

### Describe the Bug

使用meta内核，会让"本地 IPv4 绕过地址"失效

### To Reproduce

勾选 使用meta内核
填写 本地 IPv4 绕过地址 ip.sb
访问 ip.sb 发现地址在节点位置

关闭 使用meta内核
访问 ip.sb 地址恢复为自己宽带位置

### OpenClash Log

```log
我已知晓缺失日志可能会导致开发者无法了解我的情况并降低本issue的处理优先级
```

### Expected Behavior

使用meta内核，"本地 IPv4 绕过地址"依然生效

**Comment by youzhi1233** [comment]
解决了吗 我的也是match代理模式下局域网ip访问都访问不了 应该是绕过无效了
