### ISSUE TITLE
[Bug] dev分支 meta插件hysteria2，tuic协议不能用。

### ISSUE THREAD

**Issue by dfbucy090** [vernesong/OpenClash#4024]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [ ] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

0.46.029

### Bug on Environment

Lean

### OpenWrt Version

6.6.51

### Bug on Platform

Linux-arm64

### Describe the Bug

我过去编译的openwrt6.6.36版本，openclash的hy2很好用，从openwrt6.6.46开始，到现在的6.6.51版本，dev插件都是0.46.029了吧，Hy2就一直不能用了，订阅导入可以，但是打不开网站，tuic也不行了，是否是UDP的协议都不能用了？请大佬验证解决下。

### To Reproduce

和过去的版本对比

### OpenClash Log

```log
日志暂无
```

### Expected Behavior

起码能通吧

### Additional Context

无

**Comment by liuhuanyu093** [comment]
是的我也遇到这个问题了，换了几个openwrt与openclash版本都不行。内核报错:"proxy 0: unsupport proxy type: hysteria2"

**Comment by vernesong** [comment]
没有节点测试，可以tg私发我配置文件

**Comment by liuyie** [comment]
我用meta内核，正常了

**Comment by dfbucy090** [comment]
> 没有节点测试，可以tg私发我配置文件

今天又新编译了openwrt，还是这种结果，用早期编译的hy2很丝滑,是效果最好的协议，可是新编译的UDP两个协议就不能用，怎样把配置文件传给您呢？

**Comment by dfbucy090** [comment]
> 没有节点测试，可以tg私发我配置文件

节点配置文件怎样发给您呢？

**Comment by dfbucy090** [comment]
> 我用meta内核，正常了

是用最近编译lean的openwrt吗？如果是老版本就没啥可说了，本来就能用hy2

**Comment by liuyie** [comment]
我用的immortalwrt23.05.3



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: dfbucy090 ***@***.***&gt;
发送时间: 2024年9月21日 09:43
收件人: vernesong/OpenClash ***@***.***&gt;
抄送: liuyie ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [vernesong/OpenClash] [Bug] dev分支 meta插件hysteria2，tuic协议不能用。 (Issue #4024)





  
我用meta内核，正常了
  
是用最近编译lean的openwrt吗？如果是老版本就没啥可说了，本来就能用hy2

**Comment by dfbucy090** [comment]
> 我用的immortalwrt23.05.3 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: dfbucy090 ***@***.***&gt; 发送时间: 2024年9月21日 09:43 收件人: vernesong/OpenClash ***@***.***&gt; 抄送: liuyie ***@***.***&gt;, Comment ***@***.***&gt; 主题: Re: [vernesong/OpenClash] [Bug] dev分支 meta插件hysteria2，tuic协议不能用。 (Issue #4024) 我用meta内核，正常了 是用最近编译lean的openwrt吗？如果是老版本就没啥可说了，本来就能用hy2 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

应该是新版的openclash需要Firewall4，我编译lean勾上Firewall4时候就出错。过去也不需要勾上，openclash也能使用hy2，希望作者能改过来。

**Comment by dfbucy090** [comment]
> 没有节点测试，可以tg私发我配置文件

又编译了一个源码23.05的openwrt，确实都正常了，看来是需要fw4，但还是希望作者能兼顾到lean版本，毕竟原来那个hy2也可以用，而且lean用的比较习惯了。先谢谢大佬。

**Comment by vernesong** [comment]
telegram上搜我的名字

**Comment by vernesong** [comment]
![image](https://github.com/user-attachments/assets/b6441d71-76a1-4013-9cbd-7cdf1fe3eac8)
我这里fw3正常

**Comment by dfbucy090** [comment]
我用的是N1，使用的是github自动编译，代码都没变，过段时间编译一次，每次X86和N1都有编译，但一般都使用N1。昨天刷了一次X86，结果正常了，hy2可以正常使用，但是换了N1的6.6.53版还是不行，又刷了下6.1.112版，很奇怪正常了，看来是ARM的6.6版有问题。

**Comment by vernesong** [comment]
我用的imm

**Comment by helperhui** [comment]
别的帖子看到，实测可以解决，插件设置里勾上【禁用 quic-go GSO 支持】或者配置里添加
`experimental:
  quic-go-disable-gso: true`
