### ISSUE TITLE
 升级到v0.46.031-beta的绕过国内IP功能失效了

### ISSUE THREAD

**Issue by SanLiGu** [vernesong/OpenClash#4031]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [x] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [x] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [X] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [X] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

v0.46.031-beta

### Bug on Environment

Lean

### OpenWrt Version

OpenWrt R23.7.7 GDQ V2

### Bug on Platform

Linux-amd64(x86-64)

### Describe the Bug

升级到v0.46.031-beta的绕过国内IP功能失效了都返回是fake ip，回退到[v0.46.014-beta则正常
![image](https://github.com/user-attachments/assets/b3b7c72b-0010-4d2a-91b3-64b134da1ee9)
![image](https://github.com/user-attachments/assets/ff8ac3f4-3ddb-4e5e-a25a-950f43967657)
![image](https://github.com/user-attachments/assets/50b24177-a64f-4435-a978-a0160614a2f9)
![image](https://github.com/user-attachments/assets/1b5c746a-dffa-4dbb-88cf-d4bf04aea77d)

### To Reproduce

升级到v0.46.031-beta，nslookup 国内网站

### OpenClash Log

```log
请见附件。
```

### Expected Behavior

 v0.46.031-beta的绕过国内IP功能可以正常

### Additional Context

[log.txt](https://github.com/user-attachments/files/17069233/log.txt)

**Comment by vernesong** [comment]
路由本机的测试没有问题啊

**Comment by SanLiGu** [comment]
大佬好，电脑端我nslookup了很多次，也清了dns cache和reboot软路由和电脑了，在v0.46.031-beta这个版本确实是将所有国内流量都fake ip了，回退到v0.46.014-beta，则一切正常了。烦请大佬帮忙再看看是啥问题。谢谢！

**Comment by vernesong** [comment]
更新你的geosite

**Comment by SanLiGu** [comment]
大佬，我已update了geosite，geo数据库订阅的三个和大陆白名单订阅也都update了。也重启软路由和电脑了，结果nslookup国内网站返回的还是fake ip，如下，请帮忙看看。谢谢！
[log_2.txt](https://github.com/user-attachments/files/17069935/log_2.txt)

![image](https://github.com/user-attachments/assets/7e754080-05b1-42c7-bfcb-809eba29a2a2)

**Comment by vernesong** [comment]
那就是v6的问题了，你先关了

**Comment by charlie1227** [comment]
更新到031版本，关V6，绕国内ip，正常

**Comment by SanLiGu** [comment]
现在很多设备都用ipv6了，不用不现实啊，期待vernesong大佬在下个版本解决。谢谢！

**Comment by SanLiGu** [comment]
把「Dnsmasq 转发」改为「使用防火墙转发」,问题依旧。另外，请教下大佬们，Dnsmasq 转发和使用防火墙转发，两者哪个性能比较好？谢谢！
![image](https://github.com/user-attachments/assets/d63408d6-da93-4636-8c66-cc376c911593)
![image](https://github.com/user-attachments/assets/64cd860f-88dd-496e-a448-5efce649c91b)

**Comment by Aethersailor** [comment]
更新到031版本，开启V6，绕国内ip，正常

**Comment by SanLiGu** [comment]
我的是meta内核，fake-ip 增强模式，请问你的是什么模式？谢谢

**Comment by xuanranran** [comment]
正常的啊，不过需要在Fake-IP-Filter添加`geoip:cn`
![Uploading Screenshot_2024-09-20-22-40-48-236_com.server.auditor.ssh.client-edit.jpg…]()

**Comment by ltshddx** [comment]
我跟你一样的现象，只不过我是v4
root@debian:~# nslookup baidu.com
Server:         192.168.100.2
Address:        192.168.100.2#53

Name:   baidu.com
Address: 198.18.0.48

**Comment by SanLiGu** [comment]
> Fake-IP-Filter是自带的，我只是勾选了，能否发下你的截图看看，谢谢！同样的配置，我回退到014版本，nslookup 国内ip都是正常的。谢谢！

你好，我的
![image](https://github.com/user-attachments/assets/60b094d2-8ba3-4573-92e5-c839dbd1f365)

**Comment by akaet** [comment]
覆盖升级应该不会遇到此问题。
但如果是新刷的系统的话在`流量控制`中将 `实验性：绕过指定区域 IP`选择为`绕过中国大陆`。

**Comment by SanLiGu** [comment]
1.流量控制中将 实验性：绕过指定区域 IP选择为绕过中国大陆
2.实验性：绕过中国大陆 IPv6 
3.本地 DNS 劫持的「Dnsmasq 转发」改为「使用防火墙转发」
--以上3点均试了，访问国内网站返回的还是fake-ip。应该是031版本问题，现在回退并使用014版本一切正常。

**Comment by vernesong** [comment]
DNSMASQ转发，启动后试试这个
```
ip6tables -t nat -D PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 7874 -m comment --comment "OpenClash DNS Hijack"

**Comment by SanLiGu** [comment]
> DNSMASQ转发，启动后试试这个
> 
> ```
> ip6tables -t nat -D PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 7874 -m comment --comment "OpenClash DNS Hijack"
> ```

大佬好，按照您说的试了，问题依旧，如下：
![image](https://github.com/user-attachments/assets/ee1f05d0-f6a8-4d36-b8a9-7c8167226999)
![image](https://github.com/user-attachments/assets/698a8637-e51b-492a-9ec9-3fe5004298bd)
![image](https://github.com/user-attachments/assets/b3267746-7eef-4079-9866-27a8f7276e13)

**Comment by SanLiGu** [comment]
> > DNSMASQ转发，启动后试试这个
> > ```
> > ip6tables -t nat -D PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 7874 -m comment --comment "OpenClash DNS Hijack"
> > ```
> 
> 大佬好，按照您说的试了，问题依旧，如下： ![image](https://private-user-images.githubusercontent.com/66503405/369590563-ee1f05d0-f6a8-4d36-b8a9-7c8167226999.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4ODc0MjQsIm5iZiI6MTcyNjg4NzEyNCwicGF0aCI6Ii82NjUwMzQwNS8zNjk1OTA1NjMtZWUxZjA1ZDAtZjZhOC00ZDM2LWI4YTktN2M4MTY3MjI2OTk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIxVDAyNTIwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhZmU0YzllYWU2NzZjZjVjMDY2ZGI3Zjg2YjJjYjFiZjNhNmIyYzI4YmZhYjQxNWFiMzdiNjhlYTA3MmZmMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LuQUjn1wUijaQCllRlEV_bz6q9kdH7E5gMVuwNbM3bQ) ![image](https://private-user-images.githubusercontent.com/66503405/369590573-698a8637-e51b-492a-9ec9-3fe5004298bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4ODc0MjQsIm5iZiI6MTcyNjg4NzEyNCwicGF0aCI6Ii82NjUwMzQwNS8zNjk1OTA1NzMtNjk4YTg2MzctZTUxYi00OTJhLTllYzktM2ZlNTAwNDI5OGJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIxVDAyNTIwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjOGNlNGI5ZGYyM2IyMmUzODlmYTE0ODQ5Y2QyZTg1YTY2OWIxZjUyNDE5Njg1MTUwZDhjNmZkMTAxYjFlMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6-PGJ47xsM6dnDtchX52Z6Bqna7UDcfKxz-FuuZfM30) ![image](https://private-user-images.githubusercontent.com/66503405/369590583-b3267746-7eef-4079-9866-27a8f7276e13.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4ODc0MjQsIm5iZiI6MTcyNjg4NzEyNCwicGF0aCI6Ii82NjUwMzQwNS8zNjk1OTA1ODMtYjMyNjc3NDYtN2VlZi00MDc5LTk4NjYtMjdhOGY3Mjc2ZTEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIxVDAyNTIwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjNzU1NjYyNjJlYjc3MzhkZDU4YmQ2OTQ0NWU0YzJiMjU3Y2FiOGZkMjE1YTk3NTMxNmVjOWQzMjNiM2U1MTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.m2ErzINVDxzMizN8QoUhalYq05rWOvIXaG_sZCxgOg0)

还发现031版本nslook出来的name自动加了.lan，014版本则没有，如下：
031版本：
<img width="571" alt="image" src="https://github.com/user-attachments/assets/b148615b-04d9-410c-a4ca-c5b2fc0cf13c">

014版本：
<img width="430" alt="image" src="https://github.com/user-attachments/assets/b26c5112-aec6-479a-bcd5-0489ef4eb764">

**Comment by sun1a2b3c** [comment]
> 正常的啊，不過需要在Fake-IP-Filter添加`geoip:cn`
> 
> # 根 @ LovinYarn 在 ~ [22：52：53]
> $ nslookup [www.baidu.com](http://www.baidu.com) 伺服器：127.0.0.1 位址：127.0.0.1：53
> 
> [www.baidu.com](http://www.baidu.com) 規範名稱 = [www.a.shifen.com](http://www.a.shifen.com) 名稱：[www.a.shifen.com](http://www.a.shifen.com) 位址：240e：e9：6002：15a：0：ff：b05c：1278 名稱：[www.a.shifen.com](http://www.a.shifen.com) 位址：240e：e9：6002：15c：0：ff：b015：146f
> 
> [www.baidu.com](http://www.baidu.com) 規範名稱 = [www.a.shifen.com](http://www.a.shifen.com) 名稱：[www.a.shifen.com](http://www.a.shifen.com) 位址：180.101.50.242 名稱：[www.a.shifen.com](http://www.a.shifen.com) 位址：180.101.50.188

请问现在已经支持这项功能了吗？格式有什么要求吗？

**Comment by vernesong** [comment]
https://support.azure.cn/docs/azure-operations-guide/virtual-network/aog-virtual-network-qa-nslookup-parse-dns-abnormal.html

**Comment by xuanranran** [comment]
因为0.46.014到031修改了很多东西，如果是014直接升级到031，`/etc/openclash`文件夹和`/etc/config/openclash`OpenWrt配置参数里内容不会变更修改后的，依然是以前的参数，如果比较介意的话，还是推荐直接删除`/etc/config/openclash`和`/etc/openclash`文件内容，并重新安装OpenClash，但是也可以自己去修改添加014到031参数，我提供一下我目前的参数，你们可以自行尝试一下
![Fake-IP-Filter](https://github.com/user-attachments/assets/63be36e8-51c5-40cc-bf49-1b8ec06a9741)
![Nameserver-Policy](https://github.com/user-attachments/assets/52782458-7a5e-478a-b952-27c5db0a9e77)

**Comment by vernesong** [comment]
试试032呢

**Comment by SanLiGu** [comment]
> 试试032呢

请问大佬 在哪download 032？谢谢！

**Comment by vernesong** [comment]
更新选dev分支

**Comment by vernesong** [comment]
> > 尝试卸载 OpenClash、不还原配置文件， 然后重新安装 v0.46.031-beta，只安装内核、配置一键生成并启动 OpenClash 后，境内网站无法访问，只能访问境外网站； 最后只改插件设置 - DNS 设置 - 本地 DNS 劫持，由「Dnsmasq 转发」改为「使用防火墙转发」后才能正常访问境内网站
> 
> 更新至 v0.46.032-beta， 再把本地 DNS 劫持，由「使用防火墙转发」改回默认的「Dnsmasq 转发」，问题仍旧

你发日志

**Comment by xuanranran** [comment]
> > > 尝试卸载 OpenClash、不还原配置文件， 然后重新安装 v0.46.031-beta，只安装内核、配置一键生成并启动 OpenClash 后，境内网站无法访问，只能访问境外网站； 最后只改插件设置 - DNS 设置 - 本地 DNS 劫持，由「Dnsmasq 转发」改为「使用防火墙转发」后才能正常访问境内网站
> > 
> > 
> > 更新至 v0.46.032-beta， 再把本地 DNS 劫持，由「使用防火墙转发」改回默认的「Dnsmasq 转发」，问题仍旧
> 
> OpenClash 版本号: v0.46.032-beta Openwrt 固件版本: OpenWrt For N1 v0622 R24.6.6 / LuCI Master (git-24.172.27007-2c766c3)
> 
> 问题表现： 无法访问境内网站（如 baidu.com 等），但访问境外网站正常（如 google.com 等）
> 
> 日志，将「本地 DNS 劫持」设置为「Dnsmasq 转发」后，访问 baidu.com 测试：
> 
> 插件设置-调试日志： 连接测试（当前浏览器），填写 baidu.com 测试：
> 
> ```
> 找不到任何连接日志！
> 1. 可能是插件未在运行
> 2. 可能是缓存导致浏览直接使用 IP 地址进行访问
> 3. 可能是 DNS 未劫持成功，导致 Clash 无法正确反推出域名连接
> 4. 可能是所填地址无法进行解析和连接
> ```
> 
> DNS 测试（Clash 查询结果），填写 baidu.com 测试： `结果获取失败！` 生成日志，见 log.tx 文件（其中无关设备、敏感信息已替换文本） [log.txt](https://github.com/user-attachments/files/17084060/log.txt)
> 
> 内核日志（搜索 baidu.com 摘出 2 行）：
> 
> ```
> 2024-09-21 19:57:42 level=warning msg="[TCP] dial Domestic (match RuleSet/Domestic) 192.168.31.215:62091 --> www.baidu.com:443 error: dns resolve failed: all DNS requests failed, first error: requesting https://dns.google:443/dns-query: Get \"https://dns.google:443/dns-query?dns=AAABAAABAAAAAAAAA3d3dwViYWlkdQNjb20AAAEAAQ\": context deadline exceeded"
> 2024-09-21 19:57:42 level=warning msg="[TCP] dial Domestic (match RuleSet/Domestic) 192.168.31.215:62092 --> www.baidu.com:443 error: dns resolve failed: all DNS requests failed, first error: requesting https://dns.google:443/dns-query: Get \"https://dns.google:443/dns-query?dns=AAABAAABAAAAAAAAA3d3dwViYWlkdQNjb20AAAEAAQ\": context deadline exceeded"
> ```

要不你添加我上传的图那个参数，在上面倒数四五层

**Comment by SanLiGu** [comment]
> 更新选dev分支

大佬好，我按照上面哥们说的将014卸载，然后重启软路由，再安装031版本，显示031版本里面什么配置都没有，连内核都要下载。下载好内核配置好后，依然选择绕过国内ip。现在问题已解决。我怀疑之前出的问题都是014的参数还残留，因为之前我都是从014直接升级到031，参数还保留者。所以导致这个问题。谢谢大家！如下：
![image](https://github.com/user-attachments/assets/ca97bd04-7d34-4d3c-9714-781f94a7dcb1)
![image](https://github.com/user-attachments/assets/02e0da00-854a-4d88-81fe-775f7ac810d3)

**Comment by xuanranran** [comment]
唉，那个本来就是给你们自定义加入的啊，不然干嘛提供可自定义输入进行应用扩展，现在OpenClash可自定义性很高的，Mihomo(Meta)内核可玩性很多的，OpenClash也仅仅提供了文本格式...

**Comment by SanLiGu** [comment]
看看是否后续升级时都建议先卸载openclash，重启软路由后再安装新版本，然后看到openclash配置啥都没有时，按照提示下载内核配置好后再启动openclash，这样可避免从旧版本升级至新版本时存在旧版本参数残留导致出问题。

**Comment by vernesong** [comment]
> > > 尝试卸载 OpenClash、不还原配置文件， 然后重新安装 v0.46.031-beta，只安装内核、配置一键生成并启动 OpenClash 后，境内网站无法访问，只能访问境外网站； 最后只改插件设置 - DNS 设置 - 本地 DNS 劫持，由「Dnsmasq 转发」改为「使用防火墙转发」后才能正常访问境内网站
> > 
> > 
> > 更新至 v0.46.032-beta， 再把本地 DNS 劫持，由「使用防火墙转发」改回默认的「Dnsmasq 转发」，问题仍旧
> 
> OpenClash 版本号: v0.46.032-beta Openwrt 固件版本: OpenWrt For N1 v0622 R24.6.6 / LuCI Master (git-24.172.27007-2c766c3)
> 
> 问题表现： 无法访问境内网站（如 baidu.com 等），但访问境外网站正常（如 google.com 等）
> 
> 日志，将「本地 DNS 劫持」设置为「Dnsmasq 转发」后，访问 baidu.com 测试：
> 
> 插件设置-调试日志： 连接测试（当前浏览器），填写 baidu.com 测试：
> 
> ```
> 找不到任何连接日志！
> 1. 可能是插件未在运行
> 2. 可能是缓存导致浏览直接使用 IP 地址进行访问
> 3. 可能是 DNS 未劫持成功，导致 Clash 无法正确反推出域名连接
> 4. 可能是所填地址无法进行解析和连接
> ```
> 
> DNS 测试（Clash 查询结果），填写 baidu.com 测试： `结果获取失败！` 生成日志，见 log.tx 文件（其中无关设备、敏感信息已替换文本） [log.txt](https://github.com/user-attachments/files/17084060/log.txt)
> 
> 内核日志（搜索 baidu.com 摘出 2 行）：
> 
> ```
> 2024-09-21 19:57:42 level=warning msg="[TCP] dial Domestic (match RuleSet/Domestic) 192.168.31.215:62091 --> www.baidu.com:443 error: dns resolve failed: all DNS requests failed, first error: requesting https://dns.google:443/dns-query: Get \"https://dns.google:443/dns-query?dns=AAABAAABAAAAAAAAA3d3dwViYWlkdQNjb20AAAEAAQ\": context deadline exceeded"
> 2024-09-21 19:57:42 level=warning msg="[TCP] dial Domestic (match RuleSet/Domestic) 192.168.31.215:62092 --> www.baidu.com:443 error: dns resolve failed: all DNS requests failed, first error: requesting https://dns.google:443/dns-query: Get \"https://dns.google:443/dns-query?dns=AAABAAABAAAAAAAAA3d3dwViYWlkdQNjb20AAAEAAQ\": context deadline exceeded"
> ```

你自定义填两个nameserver

**Comment by Biggulu** [comment]
> > 尝试卸载 OpenClash、不还原配置文件， 然后重新安装 v0.46.031-beta，只安装内核、配置一键生成并启动 OpenClash 后，境内网站无法访问，只能访问境外网站； 最后只改插件设置 - DNS 设置 - 本地 DNS 劫持，由「Dnsmasq 转发」改为「使用防火墙转发」后才能正常访问境内网站
> 
> 更新至 v0.46.032-beta， 再把本地 DNS 劫持，由「使用防火墙转发」改回默认的「Dnsmasq 转发」，问题仍旧

我使用ACL4SSR_Online_Full.ini转换模板同你情况一样，但是相同的配置使用默认的分流规则就没有问题
