### ISSUE TITLE
[Bug] 运行状态页面中 IP.SB 和 IPIFY 无法显示 IP 地址归属地

### ISSUE THREAD

**Issue by Aethersailor** [vernesong/OpenClash#4035]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [X] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

v0.46.031-beta

### Bug on Environment

Immortalwrt

### OpenWrt Version

SNAPSHOT

### Bug on Platform

Linux-amd64(x86-64)

### Describe the Bug

[Bug] 运行状态页面中 IP.SB 和 IPIFY 无法显示 IP 地址归属地
归属地位置显示“你访问的网站盗用了 https://ip.skk.moe 的源码和接口”

### To Reproduce

观察首页

### OpenClash Log

```log
无
```

### Expected Behavior

![屏幕截图 2024-09-21 060331](https://github.com/user-attachments/assets/4e8bffaa-69c5-4a15-ba48-1e6e19b6c1e6)

希望能正常显示 IP 归属地

**Comment by vernesong** [comment]
浏览器什么环境

**Comment by Aethersailor** [comment]
> 浏览器什么环境

Firefox Nightly

**Comment by mmeiwenlong** [comment]
![QQ_1726973171707](https://github.com/user-attachments/assets/da0b138c-3eae-45ad-84cf-4529fd31b38a)
![QQ_1726973219025](https://github.com/user-attachments/assets/d14fa514-62b6-4850-94d4-cabd61bb273d)

**Comment by Aethersailor** [comment]
尝试了 Chrome 和 Edge 浏览器，显示正常
目前只发现 Firefox 和 Safari 有这个问题

**Comment by sunfing** [comment]
之前我的 Edge 和 Chrome 都正常显示属地，最近 Chrome 和 Edge 都重新安装过，Chrome 开始显示不正常了，Safari 浏览器一直有这个问题，期待解决办法。

**Comment by Aethersailor** [comment]
> 之前我的 Edge 和 Chrome 都正常显示属地，最近 Chrome 和 Edge 都重新安装过，Chrome 开始显示不正常了，Safari 浏览器一直有这个问题，期待解决办法。

我这边更新最新的dev版本以后已经可以正常显示了

**Comment by Yeeeeeer** [comment]
currentversion 0.46.066，IP.SB 一直显示 查询中 ，直接打开 https://api.ip.sb/ip ,能显示机场IP，就是在Openclash状态页面中，只有这一个显示的是查询中三个字
