### ISSUE TITLE
[Bug] 14版本覆盖升级到31版本，IPv6异常

### ISSUE THREAD

**Issue by akaet** [vernesong/OpenClash#4037]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [ ] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

v0.46.031-beta

### Bug on Environment

Lean

### OpenWrt Version

git-24.260.12982-5cd327a

### Bug on Platform

Linux-arm64

### Describe the Bug

希望可以和14版本一样，在选择绕过中国大陆后，**国内的IPv6**也可以正常使用。

v0.46.014-beta 勾选绕过中国大陆，插件设置中的IPv6设置都不勾选，https://testipv6.cn 测试一切正常，https://6.ipw.cn/ 也是可以显示IPv6地址。

v0.46.014-beta 版本覆盖升级到 v0.46.031-beta，其他配置没有变化，https://testipv6.cn 测试不通过，https://6.ipw.cn/ 也打不开。

### To Reproduce

v0.46.014-beta 版本覆盖升级到 v0.46.031-beta

### OpenClash Log

```log
14版本和31版本 多次尝试生成日志都显示：发生了一些错误！
```

### Expected Behavior

希望可以和14版本一样，在选择绕过中国大陆后，**国内的IPv6**也可以正常使用。

**Comment by vernesong** [comment]
浏览器什么环境

**Comment by vernesong** [comment]
32版本试一下

**Comment by 7461151** [comment]
这几天更新的很勤。 现在31版本勾选追加默认dns， 内核会报错 default nameserver should be pure IP"

**Comment by akaet** [comment]
> 32版本试一下

感谢大佬，升级到32版本正常。

**Comment by hcym** [comment]
感谢大佬更新

**Comment by vernesong** [comment]
> 这几天更新的很勤。 现在31版本勾选追加默认dns， 内核会报错 default nameserver should be pure IP"

看看配置文件default nameserver加了什么内容进去

**Comment by akaet** [comment]
http://6.ipw.cn/ 隔一段时间后打开会非常慢。`curl 6.ipw.cn -v` 表现一样慢。

IPv6 有时候测试时正常。
<img width="839" alt="Screen Shot 2024-09-21 at 18 23 15" src="https://github.com/user-attachments/assets/08f6e422-3376-420b-9096-ef6bf9de9e69">

多测试几次可能会出现：
<img width="1127" alt="Screen Shot 2024-09-21 at 18 25 11" src="https://github.com/user-attachments/assets/355cd43f-d23e-42fe-a45a-de50a607de25">

**Comment by akaet** [comment]
> 32版本试一下

不好意思大佬，我之前的反馈有误。我查看了配置发现

> > 32版本试一下
> 
> 感谢大佬，升级到32版本正常。

不好意思大佬，我之前的反馈有误。之前说的没有问题是 `IPv6设置` 勾选了 `允许 IPv6 类型 DNS 解析`。取消勾选后还是和31版本一样。

另外发现 我勾选了 `允许 IPv6 类型 DNS 解析`后，打开 6.ipw.cn 会比较慢，testipv6.cn 测试有时候可以通过，有时候不可以。

给大佬添麻烦了。🙏

**Comment by 7461151** [comment]
有没有人知道，fakeip的话是不是自定义的fallback dns就没用了？ 使用fakeip 小众网站会走代理，使用redirhost就会正常

**Comment by akaet** [comment]
> 有没有人知道，fakeip的话是不是自定义的fallback dns就没用了？ 使用fakeip 小众网站会走代理，使用redirhost就会正常

https://wiki.metacubex.one/config/dns/diagram/ 看看这个是否对你有帮助

**Comment by vernesong** [comment]
现在就是这个逻辑，绕过大陆也需要开v6解析，不然不会返回v6结果

**Comment by myroid** [comment]
> 现在就是这个逻辑，绕过大陆也需要开v6解析，不然不会返回v6结果

谢谢大佬解惑。就是感觉31和32版本，访问 6.ipw.cn 挺慢的，访问 testipv6.cn 也很慢，有时候还会检测ipv6失败。

**Comment by LOVE2CMOL** [comment]
> > 这几天更新的很勤。 现在31版本勾选追加默认dns， 内核会报错 default nameserver should be pure IP"
> 
> 看看配置文件default nameserver加了什么内容进去
33版本  勾选追加上游也会出现default nameserver should be pure IP提示 检查发现default nameserver这里好像少个空格
![4feec1a6-6d1c-44aa-9a72-cffb29fcea8f](https://github.com/user-attachments/assets/630bc08d-7255-4c1d-95a6-030dfc45d62b)
  @vernesong

**Comment by vernesong** [comment]
dev已经修复了
