### ISSUE TITLE
Dashboard策略组节点，控制面板进去后不管怎么选，都是用的“节点选择”指定的节点。

### ISSUE THREAD

**Issue by buzhidaoshaqingkuang** [vernesong/OpenClash#404]
最近联系3个晚上都在研究小猫咪。。

**Comment by buzhidaoshaqingkuang** [comment]
最近连续3个晚上都在研究小猫咪。。 
在苹果系统上用的小猫咪，规则非常好用。youtube指定节点、netflix也另外指定节点。其他的都可以按需设置。 但是在openwrt下面的openclash把我折腾坏了。要么不能上网，要么配置文件报错，各种问题。但是昨天晚上折腾到能上网了，国内国外都可以；配置文件也不报错了，可以自己添加修改proxy proxy group， rule。
但是最终还是有个问题困扰了。就是我设置的proxy group里面，只有“节点选择”是有作用的。其他的比如设置的“youtube”“netflix”都是不起作用。切换都是靠“节点选择”。。
想请教大佬，我到底哪里搞错了，谢谢。

**Comment by vernesong** [comment]
规则是和策略组对应的，只改策略组是没有效果的
