### ISSUE TITLE
[Bug] 升级到031或032，发现访问国内网站比014版本相比慢很多

### ISSUE THREAD

**Issue by SanLiGu** [vernesong/OpenClash#4043]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [ ] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [X] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

v0.46.031-beta和v0.46.032-beta

### Bug on Environment

Lean

### OpenWrt Version

OpenWrt R23.7.7 GDQ V2[2023] Compiled by eSir / LuCI Master

### Bug on Platform

Linux-amd64(x86-64)

### Describe the Bug

升级到031或032，发现访问国内网站比014版本相比慢很多，访问国外网站则正常。三个版本都有开启绕过国内IP。032版本，虽然解析国内网站正常，但速度也很慢。但发现014版本开启实验性：绕过中国大陆 IP后，下面有个大陆域名 DNS 服务器选项可以填，而031或032这两个版本却没有，不知是否和这有关。

### To Reproduce

升级到031或032，发现访问国内网站比014版本相比慢很多。

### OpenClash Log

```log
暂不需log，升级到031或032，就可以发现访问国内网站比014版本相比慢很多。
```

### OpenClash Config

```shell
无
```

### Expected Behavior

升级新版本后，访问国内网站可以和之前速度一样。

### Additional Context

无

**Comment by SanLiGu** [comment]
所以我现在用的依然是014版本，031和032两个版本访问国内网站真的很慢，我已经是卸载014，重启软路由，再安装031和032，重新下载内核配置的，都有开启绕过国内ip。不存在残留014版本参数的问题了，希望大佬能帮忙看看。谢谢！

**Comment by SanLiGu** [comment]
附上014和031的debug log。在同样都有开启绕过国内IP的情况下，可以看到访问国内网站csdn、51cto、ifeng.com等在031版本都是走了代理，貌似绕过国内IP依然是有问题的，032版本问题一样；014版本则没有走代理。谢谢！
[OpenClash-014版本-debug.log](https://github.com/user-attachments/files/17088801/OpenClash-014.-debug.log)
[OpenClash-031版本-debug.log](https://github.com/user-attachments/files/17088802/OpenClash-031.-debug.log)

**Comment by CybertronCracker** [comment]
这题我会，实际大家需要去覆写设置-DNS设置-Fake-IP-Filter，勾选开启。这个问题迎刃而解，我应该是在022版本的时候遇到过。

**Comment by SanLiGu** [comment]
> 国内哪里走代理了，你日志里面只有DNS查询记录

同样开启绕过国内IP和勾选Fake-IP-Filter，对于那几个测试的国内网站，014版本没有dns查询记录，是不是就是没经过openclash内核了呢，031和032里有很多dns查询记录，是不是说明经过penclash内核了，走了代理？014版本确实比031 032版本打开国内网站快很多，还请大佬赐教。谢谢！

**Comment by vernesong** [comment]
新版就是这样，你觉的慢可以开tcp并发，并把国内的dns服务器优化一下

**Comment by gemnioo** [comment]
都绕过国内 Geosite 直接用运营商的DNS吧. 查看 /etc/config/openclash 启动配置文件. 插件设置--流量控制--实验性：绕过指定区域 IP, 勾选的话 日志会出现： 另外别折腾 014版本了. 

```
2024-09-23 08:44:57 提示：为保证绕过 IP 正常工作，已在 Fake-IP-Filter 中添加规则【 geosite:cn 】
```

https://github.com/Aethersailor/Custom_OpenClash_Rules/wiki/OpenClash-%E8%AE%BE%E7%BD%AE%E6%95%99%E7%A8%8B

**Comment by ioldaiEdfe** [comment]
> 都绕过国内 Geosite 直接用运营商的DNS吧. 插件设置--流量控制--实验性：绕过指定区域 IP, 勾选的话 日志会出现： 另外别折腾 014版本了.
> 
> ```
> 2024-09-23 08:44:57 提示：为保证绕过 IP 正常工作，已在 Fake-IP-Filter 中添加规则【 geosite:cn 】
> ```
> 
> https://github.com/Aethersailor/Custom_OpenClash_Rules/wiki/OpenClash-%E8%AE%BE%E7%BD%AE%E6%95%99%E7%A8%8B

感谢分享 升级031后遇到很多dns问题  通过这篇教程完美解决了

**Comment by hcym** [comment]
晚上试试，还没用

**Comment by SanLiGu** [comment]
> 都绕过国内 Geosite 直接用运营商的DNS吧. 插件设置--流量控制--实验性：绕过指定区域 IP, 勾选的话 日志会出现： 另外别折腾 014版本了.
> 
> ```
> 2024-09-23 08:44:57 提示：为保证绕过 IP 正常工作，已在 Fake-IP-Filter 中添加规则【 geosite:cn 】
> ```
> 
> https://github.com/Aethersailor/Custom_OpenClash_Rules/wiki/OpenClash-%E8%AE%BE%E7%BD%AE%E6%95%99%E7%A8%8B

非常感谢大佬的指导，按照您的guide，完美用上了dev版本，最重要的是解决了dns泄露问题！！！感谢大佬！！！好人一生平安！！！

**Comment by hcym** [comment]
要等一等，再等一下
就好了，一切正常，还是原来的设置

**Comment by WoodyDDD** [comment]
同样的问题，也是014升级到033后，相同的设置下出现浏览国内网页慢，我是把op完全重装后再新装openclash的，不存在残留问题，具体问题应该是出在IPV6代理哪里，只要不开IPV6代理的话就没问题，打开IPV6代理，打开IPV6 NDS解析，打开绕过大陆后，在debug日志还是很多国内的IPV6流量经过核心，但在014的话就没发现有流量经过。相同设置换回014就什么问题都没了。看大哥能不能排查一下是不是代理IPV6那边的问题，总感觉是Fake-IP-Filter那的这条规则的问题 “为保证绕过 IP 正常工作，已在 Fake-IP-Filter 中添加规则【 geosite:cn 】”，这个规则能手动删除吗？

**Comment by WoodyDDD** [comment]
> 同样的问题，也是014升级到033后，相同的设置下出现浏览国内网页慢，我是把op完全重装后再新装openclash的，不存在残留问题，具体问题应该是出在IPV6代理哪里，只要不开IPV6代理的话就没问题，打开IPV6代理，打开IPV6 NDS解析，打开绕过大陆后，在debug日志还是很多国内的IPV6流量经过核心，但在014的话就没发现有流量经过。相同设置换回014就什么问题都没了。看大哥能不能排查一下是不是代理IPV6那边的问题，总感觉是Fake-IP-Filter那的这条规则的问题 “为保证绕过 IP 正常工作，已在 Fake-IP-Filter 中添加规则【 geosite:cn 】”，这个规则能手动删除吗？

补充一下，是有很多国内网站的DNS查询出现在核心里面，在014的话是没有的。

**Comment by WoodyDDD** [comment]
> > 同样的问题，也是014升级到033后，相同的设置下出现浏览国内网页慢，我是把op完全重装后再新装openclash的，不存在残留问题，具体问题应该是出在IPV6代理哪里，只要不开IPV6代理的话就没问题，打开IPV6代理，打开IPV6 NDS解析，打开绕过大陆后，在debug日志还是很多国内的IPV6流量经过核心，但在014的话就没发现有流量经过。相同设置换回014就什么问题都没了。看大哥能不能排查一下是不是代理IPV6那边的问题，总感觉是Fake-IP-Filter那的这条规则的问题 “为保证绕过 IP 正常工作，已在 Fake-IP-Filter 中添加规则【 geosite:cn 】”，这个规则能手动删除吗？
> 
> 补充一下，是有很多国内网站的DNS查询出现在核心里面，在014的话是没有的。

这个是014的日志，033的没下载下来，区别就是033的日志里面会有很多我浏览国内网站的时候的DNS查询，但014里面是没有的
[OpenClash-2024-9-24-22-1-38.log](https://github.com/user-attachments/files/17115768/OpenClash-2024-9-24-22-1-38.log)

**Comment by SanLiGu** [comment]
> 都绕过国内 Geosite 直接用运营商的DNS吧. 插件设置--流量控制--实验性：绕过指定区域 IP, 勾选的话 日志会出现： 另外别折腾 014版本了.
> 
> ```
> 2024-09-23 08:44:57 提示：为保证绕过 IP 正常工作，已在 Fake-IP-Filter 中添加规则【 geosite:cn 】
> ```
> 
> https://github.com/Aethersailor/Custom_OpenClash_Rules/wiki/OpenClash-%E8%AE%BE%E7%BD%AE%E6%95%99%E7%A8%8B

你好的，我们的问题差不多，我是卸载014，重启软路由后，安装最新的dev版本，然后按照楼上gemnioo大佬的的教程完美解决了，重要的是解决了dns泄露问题。你也可以参考下。
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
都绕过国内 Geosite 直接用运营商的DNS吧. 插件设置--流量控制--实验性：绕过指定区域 IP, 勾选的话 日志会出现： 另外别折腾 014版本了.

https://github.com/Aethersailor/Custom_OpenClash_Rules/wiki/OpenClash-%E8%AE%BE%E7%BD%AE%E6%95%99%E7%A8%8B

**Comment by WoodyDDD** [comment]
> > 都绕过国内 Geosite 直接用运营商的DNS吧. 插件设置--流量控制--实验性：绕过指定区域 IP, 勾选的话 日志会出现： 另外别折腾 014版本了.
> > ```
> > 2024-09-23 08:44:57 提示：为保证绕过 IP 正常工作，已在 Fake-IP-Filter 中添加规则【 geosite:cn 】
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > https://github.com/Aethersailor/Custom_OpenClash_Rules/wiki/OpenClash-%E8%AE%BE%E7%BD%AE%E6%95%99%E7%A8%8B
> 
> 你好的，我们的问题差不多，我是卸载014，重启软路由后，安装最新的dev版本，然后按照楼上gemnioo大佬的的教程完美解决了，重要的是解决了dns泄露问题。你也可以参考下。 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ 都绕过国内 Geosite 直接用运营商的DNS吧. 插件设置--流量控制--实验性：绕过指定区域 IP, 勾选的话 日志会出现： 另外别折腾 014版本了.
> 
> https://github.com/Aethersailor/Custom_OpenClash_Rules/wiki/OpenClash-%E8%AE%BE%E7%BD%AE%E6%95%99%E7%A8%8B

我也试过了，问题依旧，也不知道是咋回事

**Comment by SanLiGu** [comment]
> > > 都绕过国内 Geosite 直接用运营商的DNS吧. 插件设置--流量控制--实验性：绕过指定区域 IP, 勾选的话 日志会出现： 另外别折腾 014版本了.
> > > ```
> > > 2024-09-23 08:44:57 提示：为保证绕过 IP 正常工作，已在 Fake-IP-Filter 中添加规则【 geosite:cn 】
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > https://github.com/Aethersailor/Custom_OpenClash_Rules/wiki/OpenClash-%E8%AE%BE%E7%BD%AE%E6%95%99%E7%A8%8B
> > 
> > 
> > 你好的，我们的问题差不多，我是卸载014，重启软路由后，安装最新的dev版本，然后按照楼上gemnioo大佬的的教程完美解决了，重要的是解决了dns泄露问题。你也可以参考下。 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ 都绕过国内 Geosite 直接用运营商的DNS吧. 插件设置--流量控制--实验性：绕过指定区域 IP, 勾选的话 日志会出现： 另外别折腾 014版本了.
> > https://github.com/Aethersailor/Custom_OpenClash_Rules/wiki/OpenClash-%E8%AE%BE%E7%BD%AE%E6%95%99%E7%A8%8B
> 
> 我也试过了，问题依旧，也不知道是咋回事

我是完全按照大佬给的链接设置的。你确定也是这样吗？我和楼上的同学都是这样解决了问题的。怎么你这就有问题了呢，现在最新版本是033，我也安装了，完全没有问题。

**Comment by WoodyDDD** [comment]
> > > > 都绕过国内 Geosite 直接用运营商的DNS吧. 插件设置--流量控制--实验性：绕过指定区域 IP, 勾选的话 日志会出现： 另外别折腾 014版本了.
> > > > ```
> > > > 2024-09-23 08:44:57 提示：为保证绕过 IP 正常工作，已在 Fake-IP-Filter 中添加规则【 geosite:cn 】
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > https://github.com/Aethersailor/Custom_OpenClash_Rules/wiki/OpenClash-%E8%AE%BE%E7%BD%AE%E6%95%99%E7%A8%8B
> > > 
> > > 
> > > 你好的，我们的问题差不多，我是卸载014，重启软路由后，安装最新的dev版本，然后按照楼上gemnioo大佬的的教程完美解决了，重要的是解决了dns泄露问题。你也可以参考下。 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ 都绕过国内 Geosite 直接用运营商的DNS吧. 插件设置--流量控制--实验性：绕过指定区域 IP, 勾选的话 日志会出现： 另外别折腾 014版本了.
> > > https://github.com/Aethersailor/Custom_OpenClash_Rules/wiki/OpenClash-%E8%AE%BE%E7%BD%AE%E6%95%99%E7%A8%8B
> > 
> > 
> > 我也试过了，问题依旧，也不知道是咋回事
> 
> 我是完全按照大佬给的链接设置的。你确定也是这样吗？我和楼上的同学都是这样解决了问题的。怎么你这就有问题了呢，现在最新版本是033，我也安装了，完全没有问题。

是按照他那个设置的，只是我没有设置启用第二DNS服务器那里，不知道和这个有没有关系

**Comment by WoodyDDD** [comment]
> > > > > 都绕过国内 Geosite 直接用运营商的DNS吧. 插件设置--流量控制--实验性：绕过指定区域 IP, 勾选的话 日志会出现： 另外别折腾 014版本了.
> > > > > ```
> > > > > 2024-09-23 08:44:57 提示：为保证绕过 IP 正常工作，已在 Fake-IP-Filter 中添加规则【 geosite:cn 】
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > https://github.com/Aethersailor/Custom_OpenClash_Rules/wiki/OpenClash-%E8%AE%BE%E7%BD%AE%E6%95%99%E7%A8%8B
> > > > 
> > > > 
> > > > 你好的，我们的问题差不多，我是卸载014，重启软路由后，安装最新的dev版本，然后按照楼上gemnioo大佬的的教程完美解决了，重要的是解决了dns泄露问题。你也可以参考下。 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ 都绕过国内 Geosite 直接用运营商的DNS吧. 插件设置--流量控制--实验性：绕过指定区域 IP, 勾选的话 日志会出现： 另外别折腾 014版本了.
> > > > https://github.com/Aethersailor/Custom_OpenClash_Rules/wiki/OpenClash-%E8%AE%BE%E7%BD%AE%E6%95%99%E7%A8%8B
> > > 
> > > 
> > > 我也试过了，问题依旧，也不知道是咋回事
> > 
> > 
> > 我是完全按照大佬给的链接设置的。你确定也是这样吗？我和楼上的同学都是这样解决了问题的。怎么你这就有问题了呢，现在最新版本是033，我也安装了，完全没有问题。
> 
> 是按照他那个设置的，只是我没有设置启用第二DNS服务器那里，不知道和这个有没有关系

我看了一下你上传的日志，我和你的情况一样，014的话日志都是正常的，033的访问国内网站的话会有很多DNS查询进核心

**Comment by WoodyDDD** [comment]
> > > > 都绕过国内 Geosite 直接用运营商的DNS吧. 插件设置--流量控制--实验性：绕过指定区域 IP, 勾选的话 日志会出现： 另外别折腾 014版本了.
> > > > ```
> > > > 2024-09-23 08:44:57 提示：为保证绕过 IP 正常工作，已在 Fake-IP-Filter 中添加规则【 geosite:cn 】
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > https://github.com/Aethersailor/Custom_OpenClash_Rules/wiki/OpenClash-%E8%AE%BE%E7%BD%AE%E6%95%99%E7%A8%8B
> > > 
> > > 
> > > 你好的，我们的问题差不多，我是卸载014，重启软路由后，安装最新的dev版本，然后按照楼上gemnioo大佬的的教程完美解决了，重要的是解决了dns泄露问题。你也可以参考下。 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ 都绕过国内 Geosite 直接用运营商的DNS吧. 插件设置--流量控制--实验性：绕过指定区域 IP, 勾选的话 日志会出现： 另外别折腾 014版本了.
> > > https://github.com/Aethersailor/Custom_OpenClash_Rules/wiki/OpenClash-%E8%AE%BE%E7%BD%AE%E6%95%99%E7%A8%8B
> > 
> > 
> > 我也试过了，问题依旧，也不知道是咋回事
> 
> 我是完全按照大佬给的链接设置的。你确定也是这样吗？我和楼上的同学都是这样解决了问题的。怎么你这就有问题了呢，现在最新版本是033，我也安装了，完全没有问题。

我看了一下你上传的日志，我和你的情况一样，014的话日志都是正常的，033的访问国内网站的话会有很多DNS查询进核心

**Comment by WoodyDDD** [comment]
> > > > > 都绕过国内 Geosite 直接用运营商的DNS吧. 插件设置--流量控制--实验性：绕过指定区域 IP, 勾选的话 日志会出现： 另外别折腾 014版本了.
> > > > > ```
> > > > > 2024-09-23 08:44:57 提示：为保证绕过 IP 正常工作，已在 Fake-IP-Filter 中添加规则【 geosite:cn 】
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > https://github.com/Aethersailor/Custom_OpenClash_Rules/wiki/OpenClash-%E8%AE%BE%E7%BD%AE%E6%95%99%E7%A8%8B
> > > > 
> > > > 
> > > > 你好的，我们的问题差不多，我是卸载014，重启软路由后，安装最新的dev版本，然后按照楼上gemnioo大佬的的教程完美解决了，重要的是解决了dns泄露问题。你也可以参考下。 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ 都绕过国内 Geosite 直接用运营商的DNS吧. 插件设置--流量控制--实验性：绕过指定区域 IP, 勾选的话 日志会出现： 另外别折腾 014版本了.
> > > > https://github.com/Aethersailor/Custom_OpenClash_Rules/wiki/OpenClash-%E8%AE%BE%E7%BD%AE%E6%95%99%E7%A8%8B
> > > 
> > > 
> > > 我也试过了，问题依旧，也不知道是咋回事
> > 
> > 
> > 我是完全按照大佬给的链接设置的。你确定也是这样吗？我和楼上的同学都是这样解决了问题的。怎么你这就有问题了呢，现在最新版本是033，我也安装了，完全没有问题。
> 
> 是按照他那个设置的，只是我没有设置启用第二DNS服务器那里，不知道和这个有没有关系

重新安装了一下033，日志下载下来了。还是一样
[OpenClash-2024-9-25-5-6-50.log](https://github.com/user-attachments/files/17121149/OpenClash-2024-9-25-5-6-50.log)

**Comment by hcym** [comment]
今天的应该可以了，谢谢大佬啦
