### ISSUE TITLE
[Bug] 032版在哪里？

### ISSUE THREAD

**Issue by lingyunzhiss** [vernesong/OpenClash#4044]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [ ] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

0.46.031-beta

### Bug on Environment

Istoreos

### OpenWrt Version

Powered by LuCI openwrt-22.03 branch (git-24.067.02332-4c1ddfb)

### Bug on Platform

Linux-amd64(x86-64)

### Describe the Bug

openclash 更新到 0.46.031 提示配置文件没通过，卸载后重装了014版。我知道要去修改规则附加，看到这里提到更新到0.46.032-beta。可是没看到这个版本的下载，能看到的是从14版直接到31版，中间没有其他版本，其后也没看到32版。什么情况？

### To Reproduce

没看到032版

### OpenClash Log

```log
与日志无关
```

### Expected Behavior

希望能顺利升级到031版，谢谢

**Comment by SuperArilo** [comment]
https://github.com/vernesong/OpenClash/tree/package/dev
