### ISSUE TITLE
[Bug] 流媒体增强中迪士尼+解锁不生效

### ISSUE THREAD

**Issue by wuiiled** [vernesong/OpenClash#4048]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [ ] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

v0.46.033-beta

### Bug on Environment

Immortalwrt

### OpenWrt Version

ImmortalWrt 23.05.2

### Bug on Platform

Linux-amd64(x86-64)

### Describe the Bug

![微信截图_20240924004402](https://github.com/user-attachments/assets/973f81e1-bbcc-4edf-8299-4d1778762ab8)
![微信截图_20240924004430](https://github.com/user-attachments/assets/b00ea158-3e61-44ba-be50-7a10b953ea0e)

### To Reproduce

启用之后即可复现，奈菲可以正常筛选

### OpenClash Log

```log
OpenClash 调试日志

生成时间: 2024-09-24 00:56:08
插件版本: 
隐私提示: 上传此日志前请注意检查、屏蔽公网IP、节点、密码等相关敏感信息



#===================== 系统信息 =====================#

主机型号: Acute angle AA-B4
固件版本: ImmortalWrt 23.05.2 r27625-416c8c5c91
LuCI版本: 
内核版本: 5.15.150
处理器架构: x86_64

#此项有值时,如不使用IPv6,建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: server

DNS劫持: Dnsmasq 转发
#DNS劫持为Dnsmasq时，此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 127.0.0.1#7874

#===================== 依赖检查 =====================#

dnsmasq-full: 未安装
coreutils: 未安装
coreutils-nohup: 未安装
bash: 未安装
curl: 未安装
ca-certificates: 未安装
ipset: 未安装
ip-full: 未安装
libcap: 未安装
libcap-bin: 未安装
ruby: 未安装
ruby-yaml: 未安装
ruby-psych: 未安装
ruby-pstore: 未安装
kmod-tun(TUN模式): 未安装
luci-compat(Luci >= 19.07): 未安装
kmod-inet-diag(PROCESS-NAME): 未安装
unzip: 未安装
kmod-nft-tproxy: 未安装

#===================== 内核检查 =====================#

运行状态: 运行中
运行内核：Meta
进程pid: 17751
运行权限: 17751: cap_dac_override,cap_net_bind_service,cap_net_admin,cap_net_raw,cap_sys_ptrace,cap_sys_admin,cap_sys_resource=eip
运行用户: nobody
已选择的架构: linux-amd64

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限

Meta内核版本: alpha-g59a2b24
Meta内核文件: 存在
Meta内核运行权限: 正常

#===================== 插件设置 =====================#

当前配置文件: /etc/openclash/config/NCloud.yaml
启动配置文件: /etc/openclash/NCloud.yaml
运行模式: fake-ip-mix
默认代理模式: rule
UDP流量转发(tproxy): 停用
自定义DNS: 启用
IPV6代理: 停用
IPV6-DNS解析: 启用
禁用Dnsmasq缓存: 启用
自定义规则: 停用
仅允许内网: 启用
仅代理命中规则流量: 停用
仅允许常用端口流量: 停用
绕过中国大陆IP: 启用
路由本机代理: 启用

#启动异常时建议关闭此项后重试
混合节点: 停用
保留配置: 停用

#启动异常时建议关闭此项后重试
第三方规则: 停用
```

### Expected Behavior

可以正常使用

**Comment by vernesong** [comment]
```
/usr/share/openclash/openclash_streaming_unlock.lua "Disney Plus"

**Comment by wuiiled** [comment]
> ```
> /usr/share/openclash/openclash_streaming_unlock.lua "Disney Plus"
> ```
[openclash_streaming_unlock.lua.txt](https://github.com/user-attachments/files/17116616/openclash_streaming_unlock.lua.txt)

**Comment by vernesong** [comment]
让你命令行运行，不是发脚本

**Comment by wuiiled** [comment]
> 让你命令行运行，不是发脚本

运行之后再luci里还是这样显示，这是luci的显示问题吗？我实际观察有时候会自动切换节点，功能应该是正常的。

**Comment by vernesong** [comment]
运行之后看命令行的报错信息

**Comment by wuiiled** [comment]
> > 让你命令行运行，不是发脚本
> 
> 运行之后再luci里还是这样显示，这是luci的显示问题吗？我实际观察有时候会自动切换节点，功能应该是正常的。

命令行没有报错

**Comment by vernesong** [comment]
有问题时候再试

**Comment by wuiiled** [comment]
> ```
> /usr/share/openclash/openclash_streaming_unlock.lua "Disney Plus"
> ```

命令运行没有报错，但是也无法测试节点和自动切换
