### ISSUE TITLE
[Feature] 添加设置dns的“prefer-h3”选项

### ISSUE THREAD

**Issue by Vegas7** [vernesong/OpenClash#4051]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经**使用最新 Dev 版本**查看过，并不包含该功能特性或者还不完善
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 应包含的特性
- [ ] Contributors 我有能力协助 OpenClash 开发或完善此功能特性
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### Describe the Feature

目前只能够在节点中开强制H3

**Comment by Fddh2012** [comment]
+1

**Comment by vernesong** [comment]
开发者选项不是随便加吗，啥功能都加个选项小白天天吐槽看不懂

**Comment by Vegas7** [comment]
> 开发者选项不是随便加吗，啥功能都加个选项小白天天吐槽看不懂

不好意思，不是很懂开发语言。
我尝试按照示例中的格式写，但似乎加到了dns内的最后一行，不知道是否可以正常生效？
ruby_edit "$CONFIG_FILE" "['dns']['prefer-h3']" "true"
