### ISSUE TITLE
[Feature] 图标显示优化

### ISSUE THREAD

**Issue by EricZhou05** [vernesong/OpenClash#4052]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经**使用最新 Dev 版本**查看过，并不包含该功能特性或者还不完善
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 应包含的特性
- [X] Contributors 我有能力协助 OpenClash 开发或完善此功能特性
- [X] Meaningless 我提交的**是无意义的**催促更新或修复请求

### Describe the Feature

主界面打开“常用操作快捷按钮”的gif图标可能引起误解，较不直观。初次使用时一直以为是界面元素加载失败，一直在加载。
![image](https://github.com/user-attachments/assets/93351475-9270-4808-bb96-4f4527570b81)

### Describe Alternatives

建议改成上下箭头引导用户收起和展开隐藏的按钮。

**Comment by jeffreymor** [comment]
这个地方的按钮是什么时候有的，我用了快三年都没发现

**Comment by vernesong** [comment]
![image](https://github.com/user-attachments/assets/877db010-83c9-4712-9e00-a8173bdf2152)

**Comment by Fddh2012** [comment]
> ![image](https://private-user-images.githubusercontent.com/42875168/370648540-877db010-83c9-4712-9e00-a8173bdf2152.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNTc3NjksIm5iZiI6MTcyNzI1NzQ2OSwicGF0aCI6Ii80Mjg3NTE2OC8zNzA2NDg1NDAtODc3ZGIwMTAtODNjOS00NzEyLTllMDAtYTgxNzNiZGYyMTUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI1VDA5NDQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0ZDdlYmRmNjBhZjU0M2Q3NzMwZmE4ZmFlNzExMTMxMTFhMWRlMzgyNjhjYTY0ZjkwMmVhZTZlNjQ4NGEwYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TkjICJPkxxLr04pO0uHtDfI9yONYKGYv9vkJEGCXLzk)

我不看这个问题，我现在都不知道有这个东西。。。哈哈。。。。。。我这里也是显示的三个点。。。

**Comment by mimi147258** [comment]
我也用了这么长时间没发现....

**Comment by Aethersailor** [comment]
我从第一天用这个插件就发现这个地方有这仨点，跳来跳去，我一直以为是什么东西加载不出来……

**Comment by king1393** [comment]
我一直以为我的clash没配置对所有3个点一直在加载中。。。

**Comment by king1393** [comment]
我一直以为我的clash没配置对所以3个点一直在加载中。。。

**Comment by EricZhou05** [comment]
请更新openclash软件包至[v0.46.035-beta]，该问题已优化
![image](https://github.com/user-attachments/assets/e095b9b7-e83b-420f-a248-e50a8897ed2a)
