### ISSUE TITLE
[Feature] 升级到v0.46.033-beta 后，没有切换meta的开关

### ISSUE THREAD

**Issue by Mrhs121** [vernesong/OpenClash#4053]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经**使用最新 Dev 版本**查看过，并不包含该功能特性或者还不完善
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 应包含的特性
- [ ] Contributors 我有能力协助 OpenClash 开发或完善此功能特性
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### Describe the Feature

<img width="1273" alt="截屏2024-09-25 12 05 50" src="https://github.com/user-attachments/assets/507e3a93-0256-432d-a2a2-f94f3211fc2c">
以前的版本在这里有个meta的选项，现在没有了

### Describe Alternatives

如题

**Comment by Mrhs121** [comment]
看到了，移除了dev和tun的支持持,https://github.com/vernesong/OpenClash/commit/1db849489527787e92bde741947564aa87a80dc4

**Comment by dalant2019** [comment]
现在meta模式下面有设置教程吗，升级以后设置没有变但油管好像无法正常播放，但“网站访问检查”那里全是绿色的

**Comment by jonthan840923** [comment]
我也发现了一样的问题，导致链接非常不稳定，重启后才能正常启动，几个小时后就断开机场链接了，无论如何都无法再次链接成功，只能重启后才可以链接，问题反复，最后退回到v0.46.014beta版了，一切恢复正常立刻
