### ISSUE TITLE
[Feature] 添加设置“proxy-server-nameserver”

### ISSUE THREAD

**Issue by Vegas7** [vernesong/OpenClash#4058]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经**使用最新 Dev 版本**查看过，并不包含该功能特性或者还不完善
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 应包含的特性
- [ ] Contributors 我有能力协助 OpenClash 开发或完善此功能特性
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### Describe the Feature

通过日志可以看到openclash默认设置了4个国内DNS用于proxy-server-nameserver。
希望可以添加设置入口便于用户自行设置。

### Describe Alternatives

目前只能在每个DNS中勾选设置，但当使用特定分流设置下，如仅使用nameserver+nameserver-policy做国内外分流，且nameserver均为国外DNS，此时国外DNS不适合用于节点域名解析，因为域名通常指向国内中转服务器。

**Comment by hcym** [comment]
手动写上试试看吧
我是在mihomo遇过这个东西，必须设置，不然不能用分流

**Comment by Vegas7** [comment]
> 手动写上试试看吧 我是在mihomo遇过这个东西，必须设置，不然不能用分流

使用托管而非本地文件的情况下，如何手动写入？
本人不是很懂开发语言。
使用开发者选项中的一些sample也无法正确修改，是否可以麻烦提供正确语法？
谢谢

**Comment by Fddh2012** [comment]
这东西本身是在配置文件里的，特别是鸡场提供的配置里的，当然插件的确是有接管这块的，但是你不设置，肯定就不替换了。
最新的开发版本已经是支持这些的了。

**Comment by lhq46688** [comment]
使用meta内核，在覆写设置-nameserver中的dns选择编辑，里面有节点域名解析
 用于解析节点域名的 IP 地址（仅 Meta 内核），按需勾选

**Comment by vernesong** [comment]
ruby_edit "$CONFIG_FILE" "['dns']['proxy-server-nameserver']" "['114.114.114.114','119.29.29.29']"

ruby_arr_insert "$CONFIG_FILE" "['dns']['proxy-server-nameserver']" "0" "114.114.114.114"

**Comment by Vegas7** [comment]
> ruby_edit "$CONFIG_FILE" "['dns']['proxy-server-nameserver']" "['114.114.114.114','119.29.29.29']"
> 
> ruby_arr_insert "$CONFIG_FILE" "['dns']['proxy-server-nameserver']" "0" "114.114.114.114"

感谢

**Comment by YaowenCode** [comment]
> > ruby_edit "$CONFIG_FILE" "['dns']['proxy-server-nameserver']" "['114.114.114.114','119.29.29.29']"
> > ruby_arr_insert "$CONFIG_FILE" "['dns']['proxy-server-nameserver']" "0" "114.114.114.114"
> 
> 感谢

这是在覆写设置-开发者选项里填写么？

填写这里是否会在“OpenClash 修改后用于启动的配置文件”里显示？
