### ISSUE TITLE
[Feature] 适配provider文件路径

### ISSUE THREAD

**Issue by fouvromenth** [vernesong/OpenClash#4060]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经**使用最新 Dev 版本**查看过，并不包含该功能特性或者还不完善
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 应包含的特性
- [ ] Contributors 我有能力协助 OpenClash 开发或完善此功能特性
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### Describe the Feature

mihomo内核在使用provider时，配置文件会自动下载进内核下的proxies和rules文件夹中，而openclash的文件目录是proxy_provider和rule_provider
想要查看规则文件只能再找文件管理器，而无法通过openclash的管理器查看
可以适配内核，修改openclash的文件目录，方便luci管理规则文件

**Comment by Fddh2012** [comment]
这东西不是直接在配置里固定下来么?

**Comment by Fddh2012** [comment]
> > 这东西不是直接在配置里固定下来么?
> 
> 是的
> 内核会固定下载到proxies和rules这两个文件夹，但openclash使用的是proxy_provider和rule_provider

这个可以在配置里自定义的。
