### ISSUE TITLE
[Bug] 内网地址无法解析

### ISSUE THREAD

**Issue by Magic989** [vernesong/OpenClash#4069]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [ ] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

v0.46.033-beta

### Bug on Environment

Official OpenWrt

### OpenWrt Version

23.05

### Bug on Platform

Linux-amd64(x86-64)

### Describe the Bug

调用内核功能将内网地址交给上级路由解析，但解析超时

### To Reproduce

配置文件中加上
```
 nameserver-policy:
    "geosite:private": ['system']
```
webui 解析 tplogin.cn 或者网页访问 tplogin.cn

### OpenClash Log

```log
384	[debug]	[DNS Server] Exchange ;tplogin.cn. IN A failed: all DNS requests failed, first error: all DNS requests failed, first error: read udp 127.0.0.1:39169->127.0.0.1:53: i/o timeout
377	[debug]	[DNS] resolve tplogin.cn A from udp://127.0.0.1:53
376	[debug]	[DNS] resolve tplogin.cn A from udp://[::1]:53
375	[debug]	[DNS] resolve tplogin.cn A from system(udp://127.0.0.1:53,udp://[::1]:53)
```

### Expected Behavior

不知道能不能修，不好修就算了，反正是小问题🙂，因为我各个设备用的都是同一套配置文件，所以最好是能将内网地址发给上级路由解析，再不济用公网的也行（不至于转圈圈），感觉和 dnsmasq 有关系

**Comment by Gnlop** [comment]
the same question

**Comment by vernesong** [comment]
交个上级解析是dhcp，这个写法还是在本机解析，等于是查询回环了

**Comment by Magic989** [comment]
也就是说这其实是内核的问题吗

vernesong ***@***.***> 于 2024年9月29日周日 16:57写道：

**Comment by Magic989** [comment]
> 交个上级解析是dhcp，这个写法还是在本机解析，等于是查询回环了

哦，我明白了，在 Linux 上得指定接口，像下面这么写就对了

```yaml
  nameserver-policy:
    "geosite:private": ['dhcp://eth0','dhcp://system']      # eth0 为 WAN 口
```
