### ISSUE TITLE
nohup: failed to run command ‘/etc/openclash/clash’: Exec format error 

### ISSUE THREAD

**Issue by HKHKHKHKHK** [vernesong/OpenClash#407]
日志显示:
nohup: failed to run command ‘/etc/openclash/clash’: Exec format error
处理器架构:i386_pentium4, 用的是linux-386版本,
请大佬指点,万分感谢

**Comment by vernesong** [comment]
把nohup依赖装一下先，内核没问题

**Comment by HKHKHKHKHK** [comment]
您好，特别希望能用上你的作品。请教一下，怎么装nohup依赖。 这个openclash是我安装软路由openwrt里面本来自带的。谢谢。盼复。

**Comment by lloyd18** [comment]
> 您好，特别希望能用上你的作品。请教一下，怎么装nohup依赖。 这个openclash是我安装软路由openwrt里面本来自带的。谢谢。盼复。

试试
opkg update
opkg install nohup

**Comment by OleStore** [comment]
coreutils-nohup

**Comment by HKHKHKHKHK** [comment]
> coreutils-nohup

我安装了，好像没什么反应呢。？需要重启吗？

**Comment by vernesong** [comment]
> > coreutils-nohup
> 
> 我安装了，好像没什么反应呢。？需要重启吗？
不行就试试amd64的内核

**Comment by gxhao** [comment]
你好  我也遇到了上诉问题 nohup已安装，x86内核，
