### ISSUE TITLE
[Feature] 使用旁路由后ps5的游戏都没办法联机了

### ISSUE THREAD

**Issue by Yykai8899** [vernesong/OpenClash#4072]
### Verify Steps

- [ ] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [ ] Latest 我已经**使用最新 Dev 版本**查看过，并不包含该功能特性或者还不完善
- [ ] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [ ] Definite 这确实是 OpenClash 应包含的特性
- [ ] Contributors 我有能力协助 OpenClash 开发或完善此功能特性
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### Describe the Feature

主路由流量全部走向旁路由并进行了科学上网，此后ps5联机游戏就无法连接服务器了，ps5是能正常访问youtube，正常能下载游戏和上网的，就是联机游戏无法进行联机，求解决

**Comment by kojiqi** [comment]
你看一下ps5上的网络测试，看看是nat几？，玩ps5的时候，把ps5连接的服务器就是sony的分流都通过代理，不要走直联，走直联可能是nat3 走代理可以是nat2 联机应该没问题，然后主路由后台把ps5的ip绑定dmz 并打开upnp openwrt里把upnp也打开。反正我是这么设置的，可以通过联机玩外网的游戏。ps5上的网络测试是nat2

**Comment by Yykai8899** [comment]
> 你看一下ps5上的网络测试，看看是nat几？，玩ps5的时候，把ps5连接的服务器就是sony的分流都通过代理，不要走直联，走直联可能是nat3 走代理可以是nat2 联机应该没问题，然后主路由后台把ps5的ip绑定dmz 并打开upnp openwrt里把upnp也打开。反正我是这么设置的，可以通过联机玩外网的游戏。ps5上的网络测试是nat2

我ps5测试网络显示是nat2，可是就是没办法联机，dmz绑定了，upnp都打开了也还是不行

**Comment by vernesong** [comment]
联机尽量不要走代理了，除非你对自己的服务器有信心
https://github.com/vernesong/OpenClash/discussions/3684
