### ISSUE TITLE
[Bug] 更新最新dev版本后访问走代理的网站内核崩溃

### ISSUE THREAD

**Issue by missing233** [vernesong/OpenClash#4077]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [ ] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

v0.46.035-beta

### Bug on Environment

Official OpenWrt

### OpenWrt Version

OpenWrt 23.05.2

### Bug on Platform

Linux-amd64(x86-64)

### Describe the Bug

访问走代理的网站时日志出现：
```
fatal error: newosproc
runtime: may need to increase max user processes (ulimit -u)
runtime: failed to create new OS thread (have 7949 already; errno=11)
```
然后内核崩溃，无法正常解析DNS，甚至访问路由器自身都有巨大延迟

### To Reproduce

更新v0.46.035-beta，内核
alpha-ga330fa1，启动openclash

### OpenClash Log

```log
https://bin.disroot.org/?595f3affc40c32aa#CbSZ6s2TMSDdaMYueKcSJMQPiqeiXpxPHx4C6qacbAGU
```

### Expected Behavior

降级034后恢复正常

**Comment by Aethersailor** [comment]
一样的情况

**Comment by vernesong** [comment]
pid=$(pidof clash) && cat /proc/$pid/limits

**Comment by unwty8991** [comment]
same
现在到了v0.46.038-beta仍然不可以，降级到033恢复正常。

**Comment by Finntaro** [comment]
一样的问题

**Comment by Takamatsu-Tomori** [comment]
+1 路由器一直崩
