### ISSUE TITLE
[Bug] default-nameserver 不是纯ip

### ISSUE THREAD

**Issue by lovitus** [vernesong/OpenClash#4078]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [ ] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

v0.46.033-beta

### Bug on Environment

Immortalwrt

### OpenWrt Version

 ImmortalWrt 18.06-5.4-SNAPSHOT r11928-ae6ff3410 / LuCI openwrt-18.06-k5.4 branch (git-23.178.42687-494cc11) 

### Bug on Platform

Linux-arm64

### Describe the Bug

<img width="1373" alt="image" src="https://github.com/user-attachments/assets/f20617e9-9b05-4729-a6b3-1278a05cc0ed">

```
2024-10-02 14:39:10 level=error msg="default nameserver should be pure IP"
2024-10-02 14:39:10 level=info msg="Geosite Matcher implementation: succinct"
2024-10-02 14:39:10 level=info msg="Geodata Loader mode: memconservative"
```

### To Reproduce

当dns里面有DOH或者其他非ip配置的时候，
openclash会把这些拼到 default-nameserver导致clash无法启动， 最新的v1.18.9 with_gvisor  也启动不了。
luci的openclash设置里没有看到对应的开关或者覆写配置。

### OpenClash Log

```log
上面的bug描述有写。
```

### Expected Behavior

可以覆写，或者有开关去关闭这个配置优化

### Additional Context

有搜到类似的issue，但是在目前的openclash版本中没有看到处理的方法 。

**Comment by lovitus** [comment]
> 因为这是内核要求的，openclash无法管 ![image](https://private-user-images.githubusercontent.com/183583497/372761269-feef7c9e-c5ff-4ee0-bf5b-e95057116197.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4NjQwMjMsIm5iZiI6MTcyNzg2MzcyMywicGF0aCI6Ii8xODM1ODM0OTcvMzcyNzYxMjY5LWZlZWY3YzllLWM1ZmYtNGVlMC1iZjViLWU5NTA1NzExNjE5Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMlQxMDA4NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xN2Q2NWM0NzkxZjliYmZmMGMxOTA0NjllNDM2NTQ1Mzc4MjZlMjVkOWM2YTQzOTI3ZDIxM2UwMzFkM2Q5NTg0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.HzM_p3Aoh_HTMz1Kgydqrx4GCJ2XRTclAwicN0CMxzg)

左边是原始yml，订阅更新的。 右边是openclash处理后的， 多了default-nameserver， 因为openclash的拼凑逻辑导致核心不能启动。。回退用v0.46.014-beta正常了

**Comment by iam993** [comment]
> > 因为这是内核要求的，openclash无法管 ![image](https://private-user-images.githubusercontent.com/183583497/372761269-feef7c9e-c5ff-4ee0-bf5b-e95057116197.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4NjQwMjMsIm5iZiI6MTcyNzg2MzcyMywicGF0aCI6Ii8xODM1ODM0OTcvMzcyNzYxMjY5LWZlZWY3YzllLWM1ZmYtNGVlMC1iZjViLWU5NTA1NzExNjE5Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMlQxMDA4NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xN2Q2NWM0NzkxZjliYmZmMGMxOTA0NjllNDM2NTQ1Mzc4MjZlMjVkOWM2YTQzOTI3ZDIxM2UwMzFkM2Q5NTg0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.HzM_p3Aoh_HTMz1Kgydqrx4GCJ2XRTclAwicN0CMxzg)
> 
> 左边是原始yml，订阅更新的。 右边是openclash处理后的， 多了default-nameserver， 因为openclash的拼凑逻辑导致核心不能启动。。回退用v0.46.014-beta正常了

去掉追加上游DNS就行，应该是版本差异。
