### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Landidi666** [vernesong/OpenClash#4082]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [ ] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

v0.46.033-beta & v0.46.036-beta

### Bug on Environment

Immortalwrt

### OpenWrt Version

ImmortalWrt 23.05.2

### Bug on Platform

Linux-arm64

### Describe the Bug

启动时由于不知名原因OpenClash会中途关闭，仅剩守护程序运行。所用配置文件已经在安卓的“Clash Meta”和Windows的“Clash Verge”测试过，可以正常使用

### To Reproduce

本人使用这个配置文件100%复现，将OpenClash恢复默认配置后也能复现

### OpenClash Log

```log
在附件
```

### Expected Behavior

OpenClash正常工作，使用该配置文件不会再出问题

### Additional Context

[Debug.txt](https://github.com/user-attachments/files/17239411/Debug.txt)

**Comment by vernesong** [comment]
看看固件系统日志有没有错误

**Comment by digiw** [comment]
我也遇到很奇怪的状况，今天升级到v0.46.036-beta，突然发现日志内进行到最后一步提示："守护程序：正在检查 TUN 接口状态”，然后tun就崩了。这个时候如果卸载0.36beta是没用的，一定要刷一次固件，此时返回到0.33版本就正常了。

**Comment by lito12345** [comment]
升级的038增强好了，tun模式还是没有流量

**Comment by digiw** [comment]
升级到038后能正常使用，但查看日志发现，openwrt防火墙又被反复重置的记录，
![image](https://github.com/user-attachments/assets/49a02fe6-d5a9-4a57-966e-6e635d77d000)

**Comment by Landidi666** [comment]
固件日志没发现和OpenClash有关的错误，不过升级到038后确实又没问题了
