### ISSUE TITLE
[Feature] 0.46.038开fakeip并开绕过大陆，但还是有部分的国内地址进内核

### ISSUE THREAD

**Issue by lovexiaofan123** [vernesong/OpenClash#4086]
![51](https://github.com/user-attachments/assets/bb78f388-b4eb-4e05-90f0-70ad65ebd092)
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经**使用最新 Dev 版本**查看过，并不包含该功能特性或者还不完善
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 应包含的特性
- [X] Contributors 我有能力协助 OpenClash 开发或完善此功能特性
- [X] Meaningless 我提交的**是无意义的**催促更新或修复请求

### Describe the Feature

还是有部分的国内地址进内核，但Redir-Host开绕过大陆就很干净没有任何漏掉进内核的。

### Describe Alternatives

目前我个人但解决的办法直接丢Fake-IP-Filter，只不过这样挨个挨个的弄不是个办法吧。
我也找了些china list直接丢Fake-IP-Filter，感觉这样也太臃肿了，而且启动时候有点慢了
手动尝试在Fake-IP-Filter加geosite:cn，但没生效。

**Comment by youzhi1233** [comment]
不知道是不是版本的问题，更新了033:设置流量控制（实验性：绕过指定区域 IP、本地 IPv4 绕过地址）访问国内域名和本地网段全都匹配了clash规则。

**Comment by NextAbyss** [comment]
> 不知道是不是版本的问题，更新了033:设置流量控制（实验性：绕过指定区域 IP、本地 IPv4 绕过地址）访问国内域名和本地网段全都匹配了clash规则。

是的我还以为我记性出了问题，全进去了然后走DIRECT。但昨晚下载WIN11 ISO的时候我特意在控制面板看速率发现又没走核心，很怪

**Comment by MCQSJ** [comment]
很简单，设置一下，fake-ip设置为白名单模式，然后只匹配gfw就行

**Comment by jeddy2020** [comment]
> 很简单，设置一下，fake-ip设置为白名单模式，然后只匹配gfw就行

这个怎么设置，能介绍一下吗，我看流量控制的设置界面里面只有黑名单设置。
