### ISSUE TITLE
[Bug] 【undefined method `merge!' for ["Clash:xxxxxx"]:Array】

### ISSUE THREAD

**Issue by WFANG12719** [vernesong/OpenClash#4090]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [ ] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

v0.46.033

### Bug on Environment

Lean

### OpenWrt Version

OPENWRT_RELEASE="OpenWrt SNAPSHOT r5800-5bfe3bd9f"

### Bug on Platform

Linux-arm64

### Describe the Bug

启动日志中有以下错误日志：Error: Set authentication Failed,【undefined method `merge!' for ["Clash:8FVsjK0W"]:Array】
目前暂时不影响使用。

### To Reproduce

在UI界面重启openclash,日志中会出现。

### OpenClash Log

```log
root@openwrt-2:~#rg -i "array" /tmp/openclash.log
172551:2024-10-05 21:28:28 Error: Set authentication Failed,【undefined method `merge!' for ["Clash:8FVsjK0W"]:Array】
```

### Expected Behavior

配置界面里没有找到相关的字符串8FVsjK0W，不知从哪里来的。

**Comment by WFANG12719** [comment]
多谢！

**Comment by vernesong** [comment]
配置文件里面找下
