### ISSUE TITLE
[Feature] 建议添加一个手工切换机场节点的功能

### ISSUE THREAD

**Issue by HenryLuoCN** [vernesong/OpenClash#4091]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经**使用最新 Dev 版本**查看过，并不包含该功能特性或者还不完善
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 应包含的特性
- [ ] Contributors 我有能力协助 OpenClash 开发或完善此功能特性
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### Describe the Feature

我在openwrt上装的openclash，和电脑上使用的客户端不一样，客户端的版本是clash Verge，在测速后，发现有不好的节点或者节点虽然ping值正常，但是连接状态不好，可以手工干预，之前clash Verge也没这个功能，后来大家要求，添加了。
![image](https://github.com/user-attachments/assets/80889a11-a54e-4587-8499-28306666e644)

但是在openwrt上的openclash却没这个功能，特别是使用电信的网络，对机场封锁更严，导致能访问内网，但是很久都翻不出去，通过客户端yacd或者dashboard界面测速后只能看，没法手工切换。之前使用移动的宽带比电信要顺畅很多，希望能添加这个功能，方便使用时遇到问题能手工快速干预。是不是这个需要第三方插件来实现？
![image](https://github.com/user-attachments/assets/afbac675-6a9d-4b0c-8a88-618968ebde0f)
![image](https://github.com/user-attachments/assets/7a9718f3-b9ba-40ae-8313-013b4ee7c6bd)

**Comment by digiw** [comment]
![Screenshot_2024-10-06-03-37-02-811_com vivaldi browser-edit](https://github.com/user-attachments/assets/20ed2ebd-17d3-42b4-a7fa-95c5e2b2fff6)
以yacd面板为例，在图例中开启这个选项，然后你手动点击就可以切换想要的节点了，基本上几个常用面板都有这个功能。

**Comment by vernesong** [comment]
用meta面板就可以了，可以手动选择

**Comment by HenryLuoCN** [comment]
> ![Screenshot_2024-10-06-03-37-02-811_com vivaldi browser-edit](https://private-user-images.githubusercontent.com/5784996/373901129-20ed2ebd-17d3-42b4-a7fa-95c5e2b2fff6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyMjYzNjMsIm5iZiI6MTcyODIyNjA2MywicGF0aCI6Ii81Nzg0OTk2LzM3MzkwMTEyOS0yMGVkMmViZC0xN2QzLTQyYjQtYTdmYS05NWM1ZTJiMmZmZjYuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDZUMTQ0NzQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OThhODEzYWZkNDVlMDBmYTlhYWVlYzg3YjY0ZmMyNmFiYTQ4MDdlYTA1OGQ0Yzk2M2ZmOTU0ZDlhMjk5OWQ4ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.LMBRogFFnluAde_RkmAZB06hN618JekdXW1hqVUNtRA) 以yacd面板为例，在图例中开启这个选项，然后你手动点击就可以切换想要的节点了，基本上几个常用面板都有这个功能。

谢谢，get了一个新技能

**Comment by HenryLuoCN** [comment]
> 用meta面板就可以了，可以手动选择

感谢排在第二位的大佬答疑，解决了
