### ISSUE TITLE
[Bug] (防火墙模式+IPV6)会使KMS(vlmcsd)失效

### ISSUE THREAD

**Issue by arkswalumes** [vernesong/OpenClash#4093]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [ ] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

46.39

### Bug on Environment

Immortalwrt

### OpenWrt Version

23.05

### Bug on Platform

Linux-amd64(x86-64)

### Describe the Bug

 (防火墙模式+IPV6)会使KMS(vlmcsd)失效
这两者只要不一起使用就没问题

升级win11 24h2后发现无法激活了
花了5个小时一个选项一个选项试出来的
重做了不下20次系统
希望修复

### To Reproduce

刷入含openclash kms的operwrt固件

开启openclash

使用防火墙模式

开启IPV6

运行openclash

### OpenClash Log

```log
无关
```

### Expected Behavior

 (防火墙模式+IPV6)不会使KMS(vlmcsd)失效

**Comment by vernesong** [comment]
![image](https://github.com/user-attachments/assets/422e339a-c0e7-41d9-b860-da208a474d37)
