### ISSUE TITLE
[Bug] 自定义规则集附加（仅 TUN & Meta 内核）：别名不可以有中横线

### ISSUE THREAD

**Issue by WFANG12719** [vernesong/OpenClash#4095]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [ ] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

v0.46.033

### Bug on Environment

Lean

### OpenWrt Version

OPENWRT_RELEASE="OpenWrt SNAPSHOT r6809-6df7d6894"

### Bug on Platform

Linux-arm64

### Describe the Bug

规则附加--> 自定义规则集附加（仅 TUN & Meta 内核）
如果：
规则集类型：HTTP
规则类型：domain
规则格式：yaml
则：
别名：如果含有 英文中横线，openclash启动过程不会报错，但所订阅的规则不生效，文件不会被下载到 /etc/openclash/rule_provider，检索日志不会有任何匹配。

### To Reproduce

规则附加--> 自定义规则集附加（仅 TUN & Meta 内核）
如果：
规则集类型：HTTP
规则类型：domain
规则格式：yaml
设置别名为含有中横线，例如 anti-ad-chinese, Clash启动不会报错，UI页面显示RuleSet加载了，但日志里检索不到任何匹配。实际并不起作用。

### OpenClash Log

```log
无
```

### Expected Behavior

建议：自定义规则集附加的别名不要含有中横线，用下划线代替，估计脚本里把中横线当做运算符了。

**Comment by vernesong** [comment]
下载问题你要看内核下载有没有报错，地址有没有问题，这不是bug

**Comment by youzhi1233** [comment]
代理集地址需要添加代理地址下载

**Comment by cqjerry** [comment]
问题复现，
比如我自定义ruleset，规则类型：domain，写法如下：
clash-classic:https://raw.githubusercontent.com/dreamoeu/V2rayDomains2Clash/generated/category-porn.yaml
启动不报错，UI页面显示RuleSet加载了，但日志里检索不到任何匹配。实际并不起作用。
之前版本正常。

**Comment by vernesong** [comment]
![image](https://github.com/user-attachments/assets/1588272d-67f4-41e2-b4b9-3ffec7cc686f)
![image](https://github.com/user-attachments/assets/bd4a1d8e-d6e8-4922-a556-a560ba75e6f3)
![image](https://github.com/user-attachments/assets/0d3d7e18-b3ea-40a1-ae09-eb57e88c1400)
![image](https://github.com/user-attachments/assets/eecd0eea-78e6-45b9-ad0b-b1a3af407a21)

**Comment by cqjerry** [comment]
找到原因了，修改后用于启动的配置文件里，behavior非domain，
![PixPin_2024-10-07_21-40-39](https://github.com/user-attachments/assets/6ade0d89-e0ae-4442-b603-ae9bb1943505)

那应该如何正确的写这条ruleset呢？
![PixPin_2024-10-07_21-42-30](https://github.com/user-attachments/assets/d176c1a3-e77c-442e-a8bc-c33c7a10a5fe)
写成
clash-domain:https://raw.githubusercontent.com/dreamoeu/V2rayDomains2Clash/generated/category-porn.yaml 是否可以呢？

**Comment by vernesong** [comment]
![image](https://github.com/user-attachments/assets/94dfdda3-da6f-44f4-9a35-ea6c816141ff)

**Comment by cqjerry** [comment]
多谢V大，问题解决了。
