### ISSUE TITLE
更新后，更新节点并筛选订阅，无法启动

### ISSUE THREAD

**Issue by MRDHR** [vernesong/OpenClash#41]
更新后，更新节点并筛选订阅，无法启动
日志如下。查看过配置文件，Proxy字段为空，什么数据都没有。但是在服务器列表中确实是出现了相应筛选的服务器节点。
time="2019-10-13T06:33:36Z" level=fatal msg="Parse config error: ProxyGroup Proxy: key 'proxies' missing"
2019-10-13 14:33:36 OpenClash Can Not Start, Please Check The Error Info And Try Again
time="2019-10-13T06:35:21Z" level=fatal msg="Parse config error: ProxyGroup Proxy: key 'proxies' missing"
2019-10-13 14:35:21 OpenClash Can Not Start, Please Check The Error Info And Try Again

**Comment by MRDHR** [comment]
只有不填写筛选才可启动成功。

**Comment by vernesong** [comment]
1、节点列表页面先清空再订阅一下
2、订阅完成后看下节点列表页面，每个节点详情里面有没有读到各个策略组的名字
3、如果没有读到策略组名字，把你原始订阅的文件的策略组部分放上来，可能是格式问题导致读取错误

**Comment by MRDHR** [comment]
1：节点列表清空后重新订阅，启动失败
2：查看过节点的策略组名字，是存在的。
config.yaml原始配置信息大体如下，字段值有改动

Proxy:
  - {"name":"台湾*","type":"ss","server":"xxxx.com","port":123456,"cipher":"xchacha20-ietf-poly1305","password":"xxxxxx","udp":true,"plugin":"obfs","plugin-opts":{"mode":"tls","host":"xxxxxxx.com"}}

Proxy Group:
-
  name: Proxy
  type: select
  proxies:
    - '台湾*'

**Comment by MRDHR** [comment]
![QQ截图20191013150605](https://user-images.githubusercontent.com/5576916/66712149-03d5d480-edcb-11e9-836a-43b6c81bc4aa.png)

**Comment by MRDHR** [comment]
添加筛选值并更新订阅后
在配置文件中，这两个字段均为空

**Comment by vernesong** [comment]
好的，等会修复再发个release

**Comment by MRDHR** [comment]
麻烦你了。如果复现不出来，我可以提供订阅地址，方便你查问题。

**Comment by MRDHR** [comment]
更新后可以了。谢谢大佬！终于不用看到那么多无用节点了。
