### ISSUE TITLE
最新版本显示内核版本未知，上一版本显示正常！！！

### ISSUE THREAD

**Issue by zxlhhyccc** [vernesong/OpenClash#410]
![image](https://user-images.githubusercontent.com/45259624/80849991-343c6d80-8c4c-11ea-8fa0-ca50aede7da6.png)

**Comment by OleStore** [comment]
![2020-05-02_084832](https://user-images.githubusercontent.com/1283711/80851036-b9765100-8c51-11ea-8db1-281fc79b5877.jpg)
一切正常

**Comment by zxlhhyccc** [comment]
> ![2020-05-02_084832](https://user-images.githubusercontent.com/1283711/80851036-b9765100-8c51-11ea-8db1-281fc79b5877.jpg)
> 一切正常

科学状态下确实正常。。。。
