### ISSUE TITLE
[Bug] 修改策略组无效

### ISSUE THREAD

**Issue by ighlES** [vernesong/OpenClash#4108]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [ ] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

	v0.46.033-beta

### Bug on Environment

Istoreos

### OpenWrt Version

iStoreOS 22.03.6 2024052410 / LuCI istoreos-22.03 branch git-24.057.30647-6659faa

### Bug on Platform

Linux-amd64(x86-64)

### Describe the Bug

![1292d070af088ec6c03eaa28977f2920](https://github.com/user-attachments/assets/fc74bead-2ed6-434a-b005-6b0e63e2d322)
![eea53dbf98749494fa4f700a3f154c8a](https://github.com/user-attachments/assets/ba6954a3-74ca-45ea-ba2e-268d4fc12330)
以上选项不管怎么修改都没有效果，似乎始终都是默认选项
![8f1f6f4f6ee7444d029748a09bf9ae76](https://github.com/user-attachments/assets/31e04d06-e441-41f6-8442-703156289754)
而使用windows版同样的配置则是有效的
![44110ebbce7d5ff48c46984bf33b6398](https://github.com/user-attachments/assets/dd0e3b0f-3d2c-41d2-b974-9ae5d76e47fe)
![63b41f94a759ebf485c407d6f2a9c2ed](https://github.com/user-attachments/assets/9ba8ce8d-6e62-4ce1-a0a8-bd3e28015bb9)
应该不是没有被保存，因为刷新页面后被修改的策略组依然存在，在yacd和metacube中也都能看到

### To Reproduce

/

### OpenClash Log

```log
无报错日志
```

### Expected Behavior

/

**Comment by vernesong** [comment]
什么意思，你看日志匹配的什么

**Comment by ighlES** [comment]
> 什么意思，你看日志匹配的什么
不好意外啊，原因找到了
![27577129ce475bba00305f1eed3cea84](https://github.com/user-attachments/assets/eee1f2a9-d37c-4936-9b93-b99475f51c48)
是这个功能导致的，开启之后，不管怎么配置，我查到的国内网站出口ip都是我自家的，因为国内网站默认是直连，误以为配置策略组无效
