### ISSUE TITLE
[Feature] 自己搭了几个节点，每次通过更新订阅获取最新节点信息，但是每次节点的分流规则全部丢失，每次都需要重新手动指定，想问一下YACD面板中“代理”页面所指定的openclash分流规则能不能做成可以和订阅一起同步过来

### ISSUE THREAD

**Issue by lpflhh** [vernesong/OpenClash#4113]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经**使用最新 Dev 版本**查看过，并不包含该功能特性或者还不完善
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 应包含的特性
- [ ] Contributors 我有能力协助 OpenClash 开发或完善此功能特性
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### Describe the Feature

自己搭了几个节点，每次通过更新订阅获取最新节点信息，但是每次更新后节点的分流规则全部丢失，每次都需要重新手动指定，想问一下YACD面板中“代理”页面所指定的openclash分流规则能不能做成可以和订阅一起同步过来的呢，这样能省很大的事，我找到了保存分流配制的文件，就在/etc/openclash/history/目录下

### Describe Alternatives

自己搭了几个节点，每次通过更新订阅获取最新节点信息，但是每次更新后节点的分流规则全部丢失，每次都需要重新手动指定，想问一下YACD面板中“代理”页面所指定的openclash分流规则能不能做成可以和订阅一起同步过来的呢，这样能省很大的事，我找到了保存分流配制的文件，就在/etc/openclash/history/目录下

**Comment by vernesong** [comment]
你现在启动完成/etc/openclash/history/config.db这个软连接没指向对应的文件？ 如果这个文件有问题，那内核的启动日志显示什么信息

**Comment by lpflhh** [comment]
> 你现在启动完成/etc/openclash/history/config.db这个软连接没指向对应的文件？ 如果这个文件有问题，那内核的启动日志显示什么信息

您好，openclash功能都是正常的，我有几台软路由，在一台软路由上配置好了订阅，更新完成之后，我必须配置好分流规则，就是生成/etc/openclash/history/config.db这个文件，然后我配置其他软路由的openclash订阅的时候，有没有办法同步这个/etc/openclash/history/config.db 分流规则文件呢？这样就省去了多台路由器都要逐一配置或者手动拷贝/etc/openclash/history/config.db文件了，是这个意思

**Comment by vernesong** [comment]
做不到
