### ISSUE TITLE
[Bug] 测试确定升级至0.46.044在FW4是没问题的，但在FW3环境下问题很大，会导致多数代理多数网站无法打开的状况

### ISSUE THREAD

**Issue by xuanranran** [vernesong/OpenClash#4121]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [X] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

v0.46.044-beta

### Bug on Environment

Lean

### OpenWrt Version

OpenWrt R24.9.18 (2024-10-10) / LuCI Master (git-24.283.20555-a1e6216)

### Bug on Platform

Linux-amd64(x86-64)

### Describe the Bug

测试确定升级至0.46.044在FW4是没问题的，但在FW3环境下问题很大，会导致多数代理多数网站无法打开的状况，无论全局和TUN都是同样的结果

### To Reproduce

lean编译的固件，默认使用FW3并非FW4，使用0.46.044版本即可复现

### OpenClash Log

[0.46.044使用 Dnsmasq 转发.log](https://github.com/user-attachments/files/17391012/0.46.044.Dnsmasq.log)
[0.46.044使用防火墙转发.log](https://github.com/user-attachments/files/17391013/0.46.044.log)

### Expected Behavior

修复FW3环境下正常使用OpenClash

**Comment by vernesong** [comment]
你的日志没显示有问题，连接日志也看不到

**Comment by xuanranran** [comment]
> 你的日志没显示有问题，连接日志也看不到

刚刚测试一下，`*本地 DNS 劫持` 使用 `使用防火墙转发`是没问题的，但是在lean编译的固件使用默认fw3环境下，`使用 Dnsmasq 转发`会导致多数代理境外地址无法加载的情况，DNS解析是对的，但是就是无法访问，现在只好使用 `使用防火墙转发` 了，具体日志我看也没啥问题
如果可以的话，麻烦修复一下 `使用 Dnsmasq 转发`

**Comment by kingfingerpro** [comment]
新版本好像没有生成dnsmasq的配置文件，即使在nftable环境下也有问题，我有一些需要用国内dns直接解析的域名没有被加载，导致我的域名都被解析成了fakeip
![image](https://github.com/user-attachments/assets/2875de1e-e467-4253-b3ed-686f0ff8e16d)

**Comment by xuanranran** [comment]
### 0.46.046依然有问题
- [0.46.046使用 Dnsmasq 转发.log](https://github.com/user-attachments/files/17415856/0.46.046.Dnsmasq.log)
![屏幕截图 2024-10-18 001417](https://github.com/user-attachments/assets/d4c7042a-f668-4631-a478-91bf7be55e61)

**Comment by kingfingerpro** [comment]
已更新，感谢修复🙏

**Comment by vernesong** [comment]
![image](https://github.com/user-attachments/assets/50c2c258-4087-45a7-9f13-34d6795f2298)

DNS跟分流都是正常的，你是不是节点不支持v6
> ### 0.46.046依然有问题
> * [0.46.046使用 Dnsmasq 转发.log](https://github.com/user-attachments/files/17415856/0.46.046.Dnsmasq.log)

**Comment by xuanranran** [comment]
> ![image](https://private-user-images.githubusercontent.com/42875168/377661644-50c2c258-4087-45a7-9f13-34d6795f2298.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMTkxNzgsIm5iZiI6MTcyOTIxODg3OCwicGF0aCI6Ii80Mjg3NTE2OC8zNzc2NjE2NDQtNTBjMmMyNTgtNDA4Ny00NWE3LTlmMTMtMzRkNjc5NWYyMjk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDAyMzQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjZjEwZDljZGU4MWU4MGJlNzhkMTIwMDViMDUxY2Y3MjMwNWQzNTY5OTkyNTVhMjljNjU1ZTEzMGFmOTZkMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.j69V69oXCMIG5KdIRAyBYwOZFlQ38LELlPWejpgpn6k)
> 
> DNS跟分流都是正常的，你是不是节点不支持v6
> 
> > ### 0.46.046依然有问题
> > 
> > * [0.46.046使用 Dnsmasq 转发.log](https://github.com/user-attachments/files/17415856/0.46.046.Dnsmasq.log)

支持的啊，退回042是正常的，进行最简单的配置使用也不行，解析我也看是正常的，但就是无法加载，感觉是成功解析无法返回结果的样子

**Comment by vernesong** [comment]
能返回fakeip就没问题，你的本机查询也没问题

**Comment by xuanranran** [comment]
> 能返回fakeip就没问题，你的本机查询也没问题

访问其他网站，log是有解析的，但是切换节点的面板是没有访问连接规则的

**Comment by vernesong** [comment]
你看看关闭绕过大陆和黑白名单这些功能

**Comment by xuanranran** [comment]
`fake-ip-filter-mode` 为 `白名单模式` 还是有问题，可以打开一些黑名单无法打开的，但不是全部

**Comment by langziyang** [comment]
你们哪里来的新版本

**Comment by vernesong** [comment]
> * `fake-ip-filter-mode` 为 `白名单模式` 还是有问题，可以打开一些黑名单无法打开加载的，但不是全部
> * 再把 `实验性：绕过指定区域 IP` 改成 `停用` 基本都能正常加载打开了，再观望观望~

所以你到底是什么配置导致的，你的日志永远看不到配置文件

**Comment by xuanranran** [comment]
> > * `fake-ip-filter-mode` 为 `白名单模式` 还是有问题，可以打开一些黑名单无法打开加载的，但不是全部
> > * 再把 `实验性：绕过指定区域 IP` 改成 `停用` 基本都能正常加载打开了，再观望观望~
> 
> 所以你到底是什么配置导致的，你的日志永远看不到配置文件

### `proxies`和`proxy-groups`已经去掉，同样的配置在0.46.042是没问题的
 - [OpenClash# chore: refine
](https://github.com/vernesong/OpenClash/commit/064915dddbae6f2dbd4047024706fc3a4de77f2b)，此提交导致lean的默认fw3无法使用，需要更改`fake-ip-filter-mode`为白名单模式才可以
 - [v0.46.046-beta使用 Dnsmasq 转发.log](https://github.com/user-attachments/files/17449941/v0.46.046-beta.Dnsmasq.log)

**Comment by xuanranran** [comment]
> > * `fake-ip-filter-mode` 为 `白名单模式` 还是有问题，可以打开一些黑名单无法打开加载的，但不是全部
> > * 再把 `实验性：绕过指定区域 IP` 改成 `停用` 基本都能正常加载打开了，再观望观望~
> 
> 所以你到底是什么配置导致的，你的日志永远看不到配置文件

### 此提交是没问题的
- [OpenClash#chore: add ipv6 mix mode
](https://github.com/vernesong/OpenClash/commit/4ba8002cfcc2bab9b94de5f5ce971adbca3182cd)

**Comment by vernesong** [comment]
无法复现，日志里面的分流也是正常，不知道你说的无法访问是什么情况

**Comment by xuanranran** [comment]
> 无法复现，日志里面的分流也是正常，不知道你说的无法访问是什么情况

日志分流是正常的没错，就是访问成功的结果无法到达访问终端，只进不出这个样子，等有空看看当时有关于iptables的提交复原打包看看
