### ISSUE TITLE
[Feature] 克隆同步源码的文件太大了，能不能给压缩一下，小水管伤不起呀。

### ISSUE THREAD

**Issue by vpei** [vernesong/OpenClash#4126]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经**使用最新 Dev 版本**查看过，并不包含该功能特性或者还不完善
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 应包含的特性
- [ ] Contributors 我有能力协助 OpenClash 开发或完善此功能特性
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### Describe the Feature

克隆同步源码的文件太大了，能不能给压缩一下，小水管伤不起呀。

### Describe Alternatives

克隆同步源码的文件太大了，能不能给压缩一下，小水管伤不起呀。

**Comment by vpei** [comment]
![Snipaste_2024-10-18_10-15-21](https://github.com/user-attachments/assets/13ed555b-29fa-4269-8d25-2dc61d6507c3)

**Comment by NextAbyss** [comment]
你是觉得直接clone仓库体积太大了？
git clone https://github.com/vernesong/OpenClash.git --depth=1

**Comment by zheshifandian** [comment]
我觉得可以把核心单独拉一个仓库
