### ISSUE TITLE
[Bug] Dota2 游戏丢包

### ISSUE THREAD

**Issue by gyq180** [vernesong/OpenClash#4127]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [ ] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

v0.46.046-beta

### Bug on Environment

Immortalwrt, Istoreos

### OpenWrt Version

22.03

### Bug on Platform

Linux-amd64(x86-64)

### Describe the Bug

v0.46.031-beta 到最新的版本, DOTA 2游戏中都会有丢包的情况, v0.46.014-beta 正常, 或者兼容模式正常

### To Reproduce

DOTA2 打开显示网络信息, 可以看到丢包情况, 游戏中有很明显的卡顿

### OpenClash Log

```log
.
```

### Expected Behavior

Tun(udp) 感觉有问题, 希望解决丢包问题

### Additional Context

![image](https://github.com/user-attachments/assets/db425f15-7439-479d-af3e-50be18c8a809)

**Comment by ysn2233** [comment]
我也遇到这个问题了，但是关掉openclash重启以后就好了，请问你解决了吗

**Comment by gyq180** [comment]
> 我也遇到这个问题了，但是关掉openclash重启以后就好了，请问你解决了吗

目前使用最新版没有这个问题了, 你可以更新了试下

**Comment by yeezythefantasy** [comment]
![捕获222](https://github.com/user-attachments/assets/a6dbf510-0e4f-4392-acda-a803799448f8)
跟你一个问题。OpenClash版本是v0.46.064，Meta内核版本是最新的。请问怎么解决呢？

**Comment by gyq180** [comment]
> ![捕获222](https://private-user-images.githubusercontent.com/79381075/399729992-a6dbf510-0e4f-4392-acda-a803799448f8.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU4MzAyMjYsIm5iZiI6MTczNTgyOTkyNiwicGF0aCI6Ii83OTM4MTA3NS8zOTk3Mjk5OTItYTZkYmY1MTAtMGU0Zi00MzkyLWFjZGEtYTgwMzc5OTQ0OGY4LlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTAyVDE0NTg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5ZWRlN2Y3ZmE0MzJkNWE4MzZmMDNiMDYxOWFlMTdmOGRlNzg1ODI2MDYxMGE5MDQ4OTFkZjgxM2Q2MzFhMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Q0a8uwaWvPvTloee2pFg-dWqz2vLvU5Bt7cmni9Ee4M) 跟你一个问题。OpenClash版本是v0.46.064，Meta内核版本是最新的。请问怎么解决呢？

特意更新到最新版的试了下, 我这里没有这个问题了, 猜测大概率是网络运营商的提供的网络是NAT4导致的, 或者运行模式改成兼容试一下

**Comment by jack3014** [comment]
我也是，dota2 会掉线，  然后游戏重连后，能正常一段时间，然后又掉线，，关闭openclash就好了。原来的版本没这个问题。

**Comment by ysn2233** [comment]
我是fakeip改了redir-host模式后暂时好了，但是之前都没这个问题
