### ISSUE TITLE
[Feature] 代理集使用筛选会区分大小写不方便

### ISSUE THREAD

**Issue by xgitl** [vernesong/OpenClash#4131]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经**使用最新 Dev 版本**查看过，并不包含该功能特性或者还不完善
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 应包含的特性
- [X] Contributors 我有能力协助 OpenClash 开发或完善此功能特性
- [X] Meaningless 我提交的**是无意义的**催促更新或修复请求

### Describe the Feature

代理集筛选会区分大小写不方便
比如使用排除关键字碰到字母会区分大小写，^((?!期|WANG|订|官).)*$，wang这样的小写不会被排除

**Comment by vernesong** [comment]
应该暂时做不到忽略大小写，可以去内核那边提
