### ISSUE TITLE
[Feature] 请求支持vless协议

### ISSUE THREAD

**Issue by mdjbn** [vernesong/OpenClash#4132]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经**使用最新 Dev 版本**查看过，并不包含该功能特性或者还不完善
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 应包含的特性
- [ ] Contributors 我有能力协助 OpenClash 开发或完善此功能特性
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### Describe the Feature

请求vless协议支持，我尝试替换meta内核为最新的mihomo-linux-armv7-alpha-95af5f7然后直接更新订阅，发现订阅文件中没有vless协议的节点。之后我将准备好的含有vless协议的配置文件上传到openclash中，发现可以正常使用，确定为openclash不支持vless协议，请求大佬更新。

**Comment by xiaoyangdkj** [comment]
openclash会在启动时和下载后检查配置文件，下载的订阅里没有东西的话应该先去询问订阅转换......(对于不正确的配置文件，openclash是直接丢弃的)

**Comment by daoyelihuowang** [comment]
1

**Comment by howard55** [comment]
用品云那个在线转换

**Comment by bdhwrsh** [comment]
是订阅转换不支持，不是meta不支持，而openclash自带的订阅转换服务是旧版，没跟上meta内核的更新进度，希望可以解答的你的困惑：）
