### ISSUE TITLE
FakeIP下，DNS解析问题

### ISSUE THREAD

**Issue by lycor1s** [vernesong/OpenClash#415]
OpenClash是安装在旁路由上的，旁路由ip为10.10.10.2，主路由是10.10.10.1。
在FakeIP下，客户端的默认网关设置成主路由则DNS无法联通，不知道是什么问题。
![image](https://user-images.githubusercontent.com/23312700/81067352-266b3e80-8f11-11ea-8169-fa67b45a5500.png)
此为默认网关为主路由的状态。
![image](https://user-images.githubusercontent.com/23312700/81067422-371bb480-8f11-11ea-95b2-7266a500fd32.png)
上图为默认网关设为旁路由的情况。
换成Redir-Host则正常。

**Comment by vernesong** [comment]
fake-ip的原理就是这样，不必纠结ping的问题，你curl这个198的地址就知道是可以访问的

**Comment by 2287405159** [comment]
腾讯会议和腾讯游戏是不是也是因为这个原因不能访问网络？

**Comment by vernesong** [comment]
> 腾讯会议和腾讯游戏是不是也是因为这个原因不能访问网络？

udp的原因，如果udp转发开启没用的话你可以暂时先用游戏模式

**Comment by lycor1s** [comment]
> fake-ip的原理就是这样，不必纠结ping的问题，你curl这个198的地址就知道是可以访问的

主要是我想用旁路由上设置的DNS。我按照你说的试了一下，设备的默认网关设置成主路由时curl不到这个地址，而且此设备无法使用Clash的DNS也上不了网。切换为Redir-Host或用Adguard的DNS劫持53端口则可以正常解析DNS。
![image](https://user-images.githubusercontent.com/23312700/81161117-a4851f00-8fbd-11ea-8a3e-844ef15e5168.png)
上图为默认网关为旁路由时，可以连通。
![image](https://user-images.githubusercontent.com/23312700/81161420-22492a80-8fbe-11ea-8cf7-e1fe90bc61fd.png)
上图为默认网关设置成主路由时，使用FakeIP，旁路由上Clash的DNS就访问超时。
请问这可能是什么原因呢

**Comment by lycor1s** [comment]
补上设置：
![image](https://user-images.githubusercontent.com/23312700/81161705-8ff55680-8fbe-11ea-9b15-69ed9700771a.png)
![image](https://user-images.githubusercontent.com/23312700/81161721-971c6480-8fbe-11ea-8321-1b921b19c7f6.png)
![image](https://user-images.githubusercontent.com/23312700/81161733-9daadc00-8fbe-11ea-9f64-39c8de2bb7f0.png)
5553是本地的Adguard

**Comment by vernesong** [comment]
你这样设置没错啊，设备用旁路由地址做DNS就行了，clash查询dns是向5553请求的

**Comment by 2287405159** [comment]
> > 腾讯会议和腾讯游戏是不是也是因为这个原因不能访问网络？
> 
> udp的原因，如果udp转发开启没用的话你可以暂时先用游戏模式

但是游戏模式的很久没更新了好像不支持trojan，我主要还是用trojan就很难受

**Comment by vernesong** [comment]
> > > 腾讯会议和腾讯游戏是不是也是因为这个原因不能访问网络？
> > 
> > 
> > udp的原因，如果udp转发开启没用的话你可以暂时先用游戏模式
> 
> 但是游戏模式的很久没更新了好像不支持trojan，我主要还是用trojan就很难受

内核最近才更新啊

**Comment by 2287405159** [comment]
我今天看游戏模式2月份更新的啊？

**Comment by vernesong** [comment]
> 我今天看游戏模式2月份更新的啊？

那个是创建日期

**Comment by 2287405159** [comment]
> > 我今天看游戏模式2月份更新的啊？
> 
> 那个是创建日期

哦哦，好的谢谢我去更新试试

**Comment by 2287405159** [comment]
> > > 我今天看游戏模式2月份更新的啊？
> > 
> > 
> > 那个是创建日期
> 
> 哦哦，好的谢谢我去更新试试

嗯嗯，可以用trojan也可以王者了完美

**Comment by zfkira** [comment]
Fake 模式，DNS 设置，高级设置必须要启用吗？ 我初次接触openclash。

**Comment by lycor1s** [comment]
> 你这样设置没错啊，设备用旁路由地址做DNS就行了，clash查询dns是向5553请求的

![image](https://user-images.githubusercontent.com/23312700/81699383-d7d21d00-9499-11ea-86aa-f43ccce7398a.png)
我看配置中多了一行这个，Redir-host模式没有。自己删了还会自动添加，原因应该是这个？
