### ISSUE TITLE
[Feature] 建议端口劫持功能中可以自定义劫持到的端口，以便可以将去广告dns插到dnsmasq之前

### ISSUE THREAD

**Issue by bleeeeeeeeeee** [vernesong/OpenClash#4153]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经**使用最新 Dev 版本**查看过，并不包含该功能特性或者还不完善
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 应包含的特性
- [X] Contributors 我有能力协助 OpenClash 开发或完善此功能特性
- [X] Meaningless 我提交的**是无意义的**催促更新或修复请求

### Describe the Feature

想实现如下dns链路，并且启用dns劫持，当前的劫持会自动劫持到dnsmasq的端口，希望能自定义端口
192.168.1.1:53->adguardhome->127.0.0.1:5053->dnsmasq->127.0.0.1:7874->clashdns系统

**Comment by bleeeeeeeeeee** [comment]
adguardhome没有劫持选项

> 捋了一遍，这个意思是吧
> 
> ```mermaid
> graph TD;
>     lan-->adg;
>     adg--内网-->dnsmasq;
>     adg--外网-->clash
>     clash-->wan;
> ```
> OpenClash关劫持，adg开劫持不是更好吗？

**Comment by minisind** [comment]
ADGH 中设置DNS“劫持” 
![image](https://github.com/user-attachments/assets/db5fa860-17b1-461b-b435-1d1cc2522ec0)
或者在Dnsmasq中设置转发，效果相同。
![image](https://github.com/user-attachments/assets/5afc7348-ab53-44ed-b85e-3567b972c09e)

**Comment by bleeeeeeeeeee** [comment]
> ADGH 中设置DNS“劫持” ![image](https://private-user-images.githubusercontent.com/133642682/383529251-db5fa860-17b1-461b-b435-1d1cc2522ec0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5NjczMTYsIm5iZiI6MTczMDk2NzAxNiwicGF0aCI6Ii8xMzM2NDI2ODIvMzgzNTI5MjUxLWRiNWZhODYwLTE3YjEtNDYxYi1iNDM1LTFkMWNjMjUyMmVjMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwN1QwODEwMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OGE4ODRlZTdiOTk2ODIzODM2NmJiYmVkMWI0NTIwZTgxZDhiZTRiYjQ2ZDkxODRkZTUwOTgyZGY2N2NjY2JhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.zqXWRyLqvV26I5_-82QNtPWtf1g7WErRTv8__sOWIsc) 或者在Dnsmasq中设置转发，效果相同。 ![image](https://private-user-images.githubusercontent.com/133642682/383530115-5afc7348-ab53-44ed-b85e-3567b972c09e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5NjczMTYsIm5iZiI6MTczMDk2NzAxNiwicGF0aCI6Ii8xMzM2NDI2ODIvMzgzNTMwMTE1LTVhZmM3MzQ4LWFiNTMtNDRlZC1iODVlLTM1NjdiOTcyYzA5ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwN1QwODEwMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMmNjYjFlMTdlYjg1NzY3OTgxNmUyZGY4N2JkNjE3M2YxOGY0MmQ2MjFjODBmODQwZmMwY2JmM2M4NDcyMDY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.KRvoUEPHLiKIKbD1sE9zvH9W48SL0Q42Yf79CibIz-Q)

请问有luci包地址么

**Comment by minisind** [comment]
直接 openwrt.ai 定制所需要的固件包， 在这个网站也能找到IPK包。

**Comment by bleeeeeeeeeee** [comment]
> 直接 openwrt.ai 定制所需要的固件包， 在这个网站也能找到IPK包。

感谢，官网也找到了端口转发的设置https://openwrt.org/docs/guide-user/firewall/fw3_configurations/intercept_dns

**Comment by bleeeeeeeeeee** [comment]
> 没什么用，现在应用的广告都内置httpdns，路由器部署adghome连httpdns都没法拦截，更别说用dotdoh的大厂了
> 
> 想要过滤广告还是得靠流量代理软件

doh的ip用banip拦截了
