### ISSUE TITLE
[Feature] 想了解一下本仓库的mihomo内核。和mihomo仓库的内核有什么区别？

### ISSUE THREAD

**Issue by 7461151** [vernesong/OpenClash#4166]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经**使用最新 Dev 版本**查看过，并不包含该功能特性或者还不完善
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 应包含的特性
- [ ] Contributors 我有能力协助 OpenClash 开发或完善此功能特性
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### Describe the Feature

api面板更新和插件更新，版本号有一个字母区别。查看下载的内核，一个7m一个28m.两者有什么区别？

**Comment by JIZHENQIANG** [comment]
一样的，7m的是28m压缩过后的，可以减少存储占用执行没区别，自己·想用哪个用哪个

**Comment by vernesong** [comment]
没有太多区别，action编译的，可能存在go版本的差异

**Comment by refined-fish** [comment]
> ### Verify Steps
> * [x]  Tracker 我已经在 [Issue Tracker](%E2%80%A6%E2%80%A6/) 中找过我要提出的问题
> * [x]  Latest 我已经**使用最新 Dev 版本**查看过，并不包含该功能特性或者还不完善
> * [x]  Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
> * [x]  Definite 这确实是 OpenClash 应包含的特性
> * [ ]  Contributors 我有能力协助 OpenClash 开发或完善此功能特性
> * [ ]  Meaningless 我提交的**是无意义的**催促更新或修复请求
> 
> ### Describe the Feature
> api面板更新和插件更新，版本号有一个字母区别。查看下载的内核，一个7m一个28m.两者有什么区别？
> 
> ### Describe Alternatives
> _No response_

楼上已回答，请关闭此issue
