### ISSUE TITLE
随OpenWRT官方源码编译好固件后，在使用时发生错误

### ISSUE THREAD

**Issue by Yofo-me** [vernesong/OpenClash#417]
> 随OpenWRT官方源码编译好固件后，在使用时发生错误 ,在 `Web` 后台看到以下错误信息：
` Insufficient permissions to read UCI configuration. `

**Comment by zxlhhyccc** [comment]
> > 随OpenWRT官方源码编译好固件后，在使用时发生错误 ,在 `Web` 后台看到以下错误信息：
> > `Insufficient permissions to read UCI configuration.`

仔细看前面得issue，我已经告诉了解决方法。。。。
