### ISSUE TITLE
[Bug] 0.46.050 版本的第二DNS服务器只能全字匹配，无法匹配子域名，导致想直连的域名走内核分流

### ISSUE THREAD

**Issue by kingfingerpro** [vernesong/OpenClash#4174]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [ ] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

v0.46.050-beta

### Bug on Environment

Other

### OpenWrt Version

Kwrt-24.10-SNAPSHOT-6.6.58-11.11

### Bug on Platform

Linux-amd64(x86-64)

### Describe the Bug

![image](https://github.com/user-attachments/assets/0ac6951a-04ec-41a4-8a4b-6319c33a9565)
![image](https://github.com/user-attachments/assets/294a8eae-5dd4-454a-a545-5bea56efb7f7)
![image](https://github.com/user-attachments/assets/39bb412f-16a9-4a75-aec5-f27895cc8f44)

### To Reproduce

启用第二DNS服务器，在下方填入不在分流规则里的[domain.com]，应用配置后可以看到[domain.com]能够解析为真实IP，但[www.domain.com][api.domain.com]之类的会进入内核同时被归为漏网之鱼

### OpenClash Log

```log
---
```

### Expected Behavior

回归正常的判断逻辑

**Comment by vernesong** [comment]
无法复现

**Comment by kingfingerpro** [comment]
好像发现问题所在了，今天看到 Pull requests 里有一条提交提到了新版dnsmasq的读取路径发生了变化，我手动移动了openclash生成的配置文件到新的路径里，问题就解决了。

**Comment by vernesong** [comment]
这个还不确定会不会再改

**Comment by kingfingerpro** [comment]
我是这两天看到050作为正式版合并进主线的时候，顺便重新编译了一版固件升级系统才出现这个问题的，未来肯定会有越来越多的用户使用新版opwrt和dnsmasq，到时候肯定还是得适配这个新逻辑的
