### ISSUE TITLE
[Feature] 请求加入和shadowsocks和vmess 入站支持

### ISSUE THREAD

**Issue by gtxy22** [vernesong/OpenClash#4177]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经**使用最新 Dev 版本**查看过，并不包含该功能特性或者还不完善
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 应包含的特性
- [ ] Contributors 我有能力协助 OpenClash 开发或完善此功能特性
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### Describe the Feature

现在mihomo内核已经支持ss和vmess入站了，请求大佬对openclash 加入支持
现在的ipv6设备越来越多，这可以让有ipv6的机器通过外网直接连接家中的内网设备，没有中间服务商的带宽限制

**Comment by vernesong** [comment]
自己写一下配置其实更方便

**Comment by gtxy22** [comment]
直接修改不会被更想订阅覆盖吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月15日(周五) 上午8:34
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [vernesong/OpenClash] [Feature] 请求加入和shadowsocks和vmess 入站支持 (Issue #4177)




 
自己写一下配置其实更方便

**Comment by vernesong** [comment]
开发者的覆写可以加
