### ISSUE TITLE
旁路由部署下，外网域名+端口不能连接内部应用

### ISSUE THREAD

**Issue by codegitnoob** [vernesong/OpenClash#419]
网络情况如下：
主路由负责拨号，DDNS，交换机+无线。
旁路由N1，负责DNS，DHCP，openclash和其他服务。
旁路由adguard负责53端口，上级DNS为openclash和114。

如果内网客户端网关设置为主路由
外网通过域名+端口(（例如群晖的5001）能够访问内部应用：OK

当内网客户端网关设置为旁路由IP后
关闭openclash的情况下，外网通过域名+端口访问内部应用：OK
开启openclash后，无法访问，采用fakeip或者redir-hoc都不行。

尝试过主路由端口转发到内网客户端，不能访问。
再尝试主路由端口转发到旁路由，旁路由再转发到内网客户端，同样不能访问。

还请指导下是不是哪里配置有问题？谢谢。

**Comment by vernesong** [comment]
主路由端口转发到旁路由，旁路由再转发到内网客户端
旁路由的端口转发设置选择 lan to lan

**Comment by codegitnoob** [comment]
多谢V大，之前旁路由的端口转发设置没有选择 lan to lan。换成lan to lan后OK。
但是在这个配置下，外网访问速度非常慢，是不是哪个地方还能优化下？

**Comment by vernesong** [comment]
你加端口规则试试直连吧，可能是走代理了

**Comment by codegitnoob** [comment]
> 
> 
> 你加端口规则试试直连吧，可能是走代理了

是加在头部规则里面吗？
加了规则是否还是保持 主路由端口转发到旁路由，旁路由再转发到内网客户端

**Comment by codegitnoob** [comment]
多谢V大的提醒，又试了下，不用加端口规则。
端口转发使用lan to lan的时候，关掉nat还回，就解决速度慢的问题了。

**Comment by hackenfu** [comment]
> 主路由端口转发到旁路由，旁路由再转发到内网客户端
> 旁路由的端口转发设置选择 lan to lan

一直没解决这个问题，直到发现这里的新大陆，太好了
但是问题又来了，我这样设置之后，只有外网能通过ddns:端口访问内部设备，而内网却不能通过ddns:端口访问内部设备了，必须内网IP:端口，这是正常的吗？

**Comment by livebelive** [comment]
把旁路有模式 关了 然后访问控制里面 添加上绕行端口 就好了 那个旁路有模式 不要开
