### ISSUE TITLE
建议增加不受更新影响的自定义托管规则插入功能

### ISSUE THREAD

**Issue by Seitazzo** [vernesong/OpenClash#420]
比如有时候我只想加一个域名走代理，却发现似乎只能自己写规则文件，如果客户端能集成这个功能就可以更轻松地加进自己的需求了。

**Comment by vernesong** [comment]
https://github.com/vernesong/OpenClash/wiki/%E8%A7%84%E5%88%99%E8%AE%BE%E7%BD%AE%EF%BC%88%E8%AE%BF%E9%97%AE%E6%8E%A7%E5%88%B6%EF%BC%89
