### ISSUE TITLE
[Bug] All three dashboards have no data on the logs and connection tabs when accessing through nginx reverse proxy.

### ISSUE THREAD

**Issue by LedPeach** [vernesong/OpenClash#4207]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [X] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

v0.46.050-beta

### Bug on Environment

Immortalwrt

### OpenWrt Version

ImmortalWrt 23.05.1 r27304

### Bug on Platform

Linux-amd64(x86-64)

### Describe the Bug

All three dashboards have no data on the logs and connection tabs when accessing through nginx reverse proxy.
I have configured the `Dashboard Control` and all the other tabs of all three dashboards work just fine, only the log and connection tabs have no data. 
But accessing through ip address has no issues.
Is there any header parameter I need to set for my nginx reverse proxy?
My nginx conf: 
```server {
  set $forward_scheme http;
  set $server         "openclash.ip";
  set $port           9090;

  listen 80;
listen [::]:80;

listen 443 ssl http2;
listen [::]:443 ssl http2;


  server_name clash.dashboard;
...
```

### To Reproduce

Access openclash dashboard through nginx reverse proxy.

### OpenClash Log

```log
No relevant logs
```

### Expected Behavior

Have data on connections and logs when accessing all dashboard through nginx reverse proxy.

**Comment by vernesong** [comment]
https://github.com/MetaCubeX/mihomo/blob/9de9f1ef518206e43e9f8300cfc724d8e128d049/docs/config.yaml#L58

**Comment by LedPeach** [comment]
> https://github.com/MetaCubeX/mihomo/blob/9de9f1ef518206e43e9f8300cfc724d8e128d049/docs/config.yaml#L58

I did that. But the connection tab is still not working. I got `Browser can’t establish a connection to the server at wss://my.domain.tld/connections?token=mytoken.` in the browser console log. Do I have to add something to the nginx conf for upgrading HTTP to WebSocket?

**Comment by vernesong** [comment]
https://github.com/vernesong/OpenClash/pull/2386#issuecomment-1491389058
