### ISSUE TITLE
Openclash 配置未生效

### ISSUE THREAD

**Issue by hedm68** [vernesong/OpenClash#421]
请教一个问题，同样的规则配置文件，在clash for windows上运行可以按照规则走不同的节点，但是将同样配置用在openclash上，分流功能失效。比如使用Netflix时，设置Netflix策略组使用美国节点，其他策略组走日本节点，配置在clash for Windows上使用，能按照规则分流。在openclash上只能使用proxy策略组选定的节点，Netflix或其他策略组选定节点未生效。

**Comment by hedm68** [comment]
OpenClash 调试日志

生成时间: 2020-05-07 08:03:58
插件版本: v0.37.6-beta

#===================== 系统信息 =====================#
主机型号: Intel(R) Celeron(R) CPU 3865U @ 1.80GHz : 1 Core 2 Thread
固件版本: OpenWrt GDQ IPv4 v4.1[2020]
LuCI版本: git-20.088.29068-cebe120-1
内核版本: 4.19.108
处理器架构: x86_64

#此项在使用Tun模式时应为ACCEPT
防火墙转发: ACCEPT

#此项有值时建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: 

#此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 127.0.0.1#7874

#===================== 依赖检查 =====================#
dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
jsonfilter: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
iptables-mod-tproxy: 已安装
kmod-tun(TUN模式): 已安装
luci-compat(Luci-19.07): 未安装

#===================== 内核检查 =====================#
运行状态: 运行中
已选择的架构: linux-amd64

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 
Tun内核文件: 不存在
Tun内核运行权限: 否

Game内核版本: v0.17.0-100-g4d2ec55
Game内核文件: 存在
Game内核运行权限: 正常

Dev内核版本: v0.19.0-26-g94e0e4b
Dev内核文件: 存在
Dev内核运行权限: 正常

#===================== 插件设置 =====================#
当前配置文件: /etc/openclash/config/Dler.yaml
运行模式: fake-ip
默认代理模式: Rule
UDP流量转发: 停用
DNS劫持: 启用
自定义DNS: 停用
IPV6-DNS解析: 停用
Real-IP-DNS地址: 
禁用Dnsmasq缓存: 停用
自定义规则: 停用
仅允许内网: 停用
仅代理命中规则流量: 停用

#启动异常时建议关闭此项后重试
保留配置: 停用
第三方规则: 停用

#===================== 配置文件 =====================#
---
port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: true
bind-address: "*"
mode: Rule
log-level: silent
external-controller: 0.0.0.0:9090
experimental:
ignore-resolve-fail: true
secret: "Maige168!"
external-ui: "/usr/share/openclash/dashboard"
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  listen: 127.0.0.1:7874
  nameserver:
  - 114.114.114.114
  fallback:
  - tls://8.8.8.8:853
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4

#===================== 防火墙设置 =====================#

#NAT chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:53 redir ports 53
2    prerouting_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom prerouting rule chain */
3    zone_lan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
4    openclash  tcp  --  0.0.0.0/0            0.0.0.0/0           
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         
1    REDIRECT   tcp  --  0.0.0.0/0            198.18.0.0/16        redir ports 7892

#Mangle chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         
1    RRDIPT_OUTPUT  all  --  0.0.0.0/0            0.0.0.0/0           

#===================== 路由表状态 =====================#
#route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.10.10.3      0.0.0.0         UG    0      0        0 br-lan
10.10.10.0      0.0.0.0         255.255.255.0   U     0      0        0 br-lan
#ip route list
default via 10.10.10.3 dev br-lan proto static 
10.10.10.0/24 dev br-lan proto kernel scope link src 10.10.10.1 
#ip rule show
0:	from all lookup local 
32766:	from all lookup main 
32767:	from all lookup default 

#===================== 端口占用状态 =====================#
tcp        0      0 :::7890                 :::*                    LISTEN      31105/clash
tcp        0      0 :::7891                 :::*                    LISTEN      31105/clash
tcp        0      0 :::7892                 :::*                    LISTEN      31105/clash
tcp        0      0 :::9090                 :::*                    LISTEN      31105/clash
udp        0      0 127.0.0.1:7874          0.0.0.0:*                           31105/clash
udp        0      0 :::7891                 :::*                                31105/clash
udp        0      0 :::7892                 :::*                                31105/clash

#===================== 测试本机DNS查询 =====================#
Server:		127.0.0.1
Address:	127.0.0.1#53

Name:      www.baidu.com
Address 1: 198.18.0.6
*** Can't find www.baidu.com: No answer

#===================== resolv.conf.auto =====================#
# Interface lan
nameserver 114.114.114.114
nameserver 223.5.5.5

#===================== 测试本机网络连接 =====================#
HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: private, no-cache, no-store, proxy-revalidate, no-transform
Connection: keep-alive
Content-Length: 277
Content-Type: text/html
Date: Thu, 07 May 2020 00:03:59 GMT
Etag: "575e1f72-115"
Last-Modified: Mon, 13 Jun 2016 02:50:26 GMT
Pragma: no-cache
Server: bfe/1.0.8.18


#===================== 测试本机网络下载 =====================#
HTTP/1.1 200 Connection established

HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 78
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: text/plain; charset=utf-8
ETag: W/"056641c351c1b7748e0261368abda3c8f3559f64db330cb5f70ffe19108ce0ef"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
Via: 1.1 varnish (Varnish/6.0)
X-GitHub-Request-Id: 9C78:24EB:1A95C3:1F910C:5EB34704
Accept-Ranges: bytes
Date: Thu, 07 May 2020 00:04:00 GMT
Via: 1.1 varnish
X-Served-By: cache-hkg17934-HKG
X-Cache: HIT, HIT
X-Cache-Hits: 1, 1
X-Timer: S1588809841.663081,VS0,VE0
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
X-Fastly-Request-ID: 99dd0c21254bcae0ff871cbda206d5ac46480a29
Expires: Thu, 07 May 2020 00:09:00 GMT
Source-Age: 240


#===================== 最近运行日志 =====================#
time="2020-05-07T08:03:44+08:00" level=info msg="Start initial compatible provider AdBlock"
time="2020-05-07T08:03:44+08:00" level=info msg="Start initial compatible provider Apple"
time="2020-05-07T08:03:44+08:00" level=info msg="Start initial compatible provider Netease Music"
time="2020-05-07T08:03:44+08:00" level=info msg="Start initial compatible provider PayPal"
time="2020-05-07T08:03:44+08:00" level=info msg="Start initial compatible provider AsianTV"
time="2020-05-07T08:03:44+08:00" level=info msg="Start initial compatible provider Spotify"
time="2020-05-07T08:03:44+08:00" level=info msg="Start initial compatible provider Auto - UrlTest"
time="2020-05-07T08:03:44+08:00" level=info msg="Start initial compatible provider Proxy"
time="2020-05-07T08:03:44+08:00" level=info msg="Start initial compatible provider Domestic"
time="2020-05-07T08:03:44+08:00" level=info msg="Start initial compatible provider GlobalTV"
time="2020-05-07T08:03:44+08:00" level=info msg="Start initial compatible provider Steam"
time="2020-05-07T08:03:44+08:00" level=info msg="Start initial compatible provider Microsoft"
time="2020-05-07T08:03:44+08:00" level=info msg="Start initial compatible provider Telegram"
time="2020-05-07T08:03:44+08:00" level=info msg="Start initial compatible provider Netflix"
time="2020-05-07T08:03:44+08:00" level=info msg="Start initial compatible provider Speedtest"
time="2020-05-07T08:03:44+08:00" level=info msg="Start initial compatible provider Others"
2020-05-07 08:03:43 OpenClash Start Successful

**Comment by vernesong** [comment]
开日志看看
