### ISSUE TITLE
[Feature] apk 安装包

### ISSUE THREAD

**Issue by unijiang** [vernesong/OpenClash#4211]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经**使用最新 Dev 版本**查看过，并不包含该功能特性或者还不完善
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 应包含的特性
- [ ] Contributors 我有能力协助 OpenClash 开发或完善此功能特性
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### Describe the Feature

我现在用的 openwrt 是新的 apk 包管理器，请问 openclash 会 release apk 的安装包吗？

**Comment by lewis617** [comment]
> 目前没放release罢了
> 
> https://github.com/vernesong/OpenClash/raw/668e156f65e829931d00817c6c6df41875e83196/dev/luci-app-openclash-0.46.057.apk

安装后报错：UNTRUSTED signature

**Comment by unijiang** [comment]
> > 目前没放release罢了
> > https://github.com/vernesong/OpenClash/raw/668e156f65e829931d00817c6c6df41875e83196/dev/luci-app-openclash-0.46.057.apk
> 
> 安装后报错：UNTRUSTED signature

apk add --allow-untrusted ***.apk
https://openwrt.org/docs/guide-user/additional-software/opkg-to-apk-cheatsheet

**Comment by unijiang** [comment]
> ```
> root@ImmortalWrt:~# apk add --allow-untrusted luci-app-openclash_0.46.063_all.ip
> k
> ERROR: unable to select packages:
>   luci-app-openclash_0.46.063_all.ipk (no such package):
>     required by: world[luci-app-openclash_0.46.063_all.ipk]
> ```
> 
> @fejeIaqbhbv @unijiang 请问怎么解决
你用apk装的ipk包，下载上面提供的apk包来装。
