### ISSUE TITLE
x86路由器openclash，使用clsshr替换clash，SRC-IP-CIDR不起作用？

### ISSUE THREAD

**Issue by yasum2006** [vernesong/OpenClash#422]
x86路由器openclash，使用clsshr替换clash，上传配置文件后启用，SRC-IP-CIDR不起作用？
- SRC-IP-CIDR,192.168.6.55/32,DIRECT
 局域网内某台设备如何不走clash，用的是ssr机场，配置文件上传后应用，尝试改为：
- SOURCE-IP-CIDR,192.168.6.55/32,DIRECT
也不起作用？其他老师是否遇到过？

**Comment by vernesong** [comment]
用redir模式，全局设置单独有访问控制标签
