### ISSUE TITLE
[Bug] 多Wi-Fi隔离通过openwrt 设置VLAN 对接多路由 启动openclash 国内国际打不开网站 但是可以ping通 curl也通 微信海可以发聊天

### ISSUE THREAD

**Issue by showmyse1f** [vernesong/OpenClash#4226]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [ ] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

v0.46.050-beta

### Bug on Environment

Immortalwrt

### OpenWrt Version

ImmortalWRT 23.05.4

### Bug on Platform

Linux-armv5, All

### Describe the Bug

软路由（主路由）负责 DHCP NAT 联网等，wifi路由器只负责多wifi信号及转发，主路由和wifi路由通过1个lan口网线连接，并且设置了4个VLAN，分别对应主路由的4个VLAN接口和wifi路由的4个VLAN接口并且和4个WIFI信号绑定，所有VLAN已开标签并设置了主VLAN。搭建好后，不开启 openclash 可以正常访问国内网络，打开openclash 并配上节点，通过pc网卡网线连接wifi路由器lan口，国内国际都可以访问，所有设备连接Wi-Fi任意信号国内国际网页都打不开，通过命令行 ping网站是通的，curl 网站可以返回正确内容，微信也能发送聊天，就是打不开网站，国内国际都打不开。

尝试了各种办法 关闭dns劫持 设置配置文件 都无法解决。

### To Reproduce

无

### OpenClash Log

```log
无
```

### Expected Behavior

可正常访问网页

**Comment by vernesong** [comment]
发设备连接wifi后的测试截图，以及clash的日志

**Comment by showmyse1f** [comment]
> 发设备连接wifi后的测试截图，以及clash的日志

分别使用 PC 连接Wi-Fi、连接LAN，手机连接Wi-Fi进行了测试，结果附件图片和日志所示，请查看。
期待能把问题解决，感谢！
如有其他需要提供的资料，随时沟通。


![sj4](https://github.com/user-attachments/assets/e0b1722d-55dd-4b8d-9563-15676d8e0f7b)
![sj3](https://github.com/user-attachments/assets/da40988a-f20e-434b-aa79-8bc1c98bdb61)
![sj2](https://github.com/user-attachments/assets/95e4c43c-62cc-46d8-be09-600c03d5fc78)
![sj1](https://github.com/user-attachments/assets/b104dd97-60e6-4973-8024-e125e968d9af)
[sj-debug-OpenClash-2024-12-13-23-27-44.log](https://github.com/user-attachments/files/18128349/sj-debug-OpenClash-2024-12-13-23-27-44.log)
![pc3](https://github.com/user-attachments/assets/558afb93-3728-4053-9468-c7b64154ec8c)
![pc2](https://github.com/user-attachments/assets/56c302cb-9e59-4a43-9690-7c3923ad5539)
![pc1](https://github.com/user-attachments/assets/9bf9e213-edfd-47bd-ac76-f266dc805c9b)
[pc-info-OpenClash-2024-12-13-23-4-40.log](https://github.com/user-attachments/files/18128350/pc-info-OpenClash-2024-12-13-23-4-40.log)
[pc-info-OpenClash-2024-12-13-22-49-35.log](https://github.com/user-attachments/files/18128351/pc-info-OpenClash-2024-12-13-22-49-35.log)

**Comment by showmyse1f** [comment]
> 发设备连接wifi后的测试截图，以及clash的日志

PC 连接LAN 和 WI-FI 后 虽然网络通，但是感觉速度很慢。

**Comment by showmyse1f** [comment]
> 发设备连接wifi后的测试截图，以及clash的日志

分别使用 PC 连接Wi-Fi、连接LAN，手机连接Wi-Fi进行了测试，结果附件图片和日志所示，请查看。
PC 连接LAN 和 WI-FI 后 虽然网络通，但是感觉速度很慢。
期待问题可以解决，感谢！
如有其他需要提供的资料，随时沟通。

[pc-info-OpenClash-2024-12-13-22-49-35.log](https://github.com/user-attachments/files/18128507/pc-info-OpenClash-2024-12-13-22-49-35.log)
![sj4](https://github.com/user-attachments/assets/2002f9ca-1714-40d4-8ef2-22a0cf216fff)
![sj3](https://github.com/user-attachments/assets/276c8a57-547f-4c53-aaaa-f4dc90a2dfeb)
![sj2](https://github.com/user-attachments/assets/665be865-0977-4491-acf9-1c0df11cc678)
![sj1](https://github.com/user-attachments/assets/5e4cf697-1b7e-484e-b612-1633e55a9e3d)
[sj-debug-OpenClash-2024-12-13-23-27-44.log](https://github.com/user-attachments/files/18128511/sj-debug-OpenClash-2024-12-13-23-27-44.log)
![pc3-1](https://github.com/user-attachments/assets/a69a1320-824e-4f8d-93ae-dca2c8f2db98)
![pc2-1](https://github.com/user-attachments/assets/87d5731b-c1b9-4e7d-a199-bd94bba4ba2a)
![pc1](https://github.com/user-attachments/assets/8e956886-4bc8-43d3-9bbc-927c039042fe)
[pc-info-OpenClash-2024-12-13-23-4-40.log](https://github.com/user-attachments/files/18128512/pc-info-OpenClash-2024-12-13-23-4-40.log)

**Comment by showmyse1f** [comment]
> 发设备连接wifi后的测试截图，以及clash的日志

分别使用 PC 连接Wi-Fi、连接LAN，手机连接Wi-Fi进行了测试，结果附件图片和日志所示，请查看。
PC 连接LAN 和 WI-FI 后 虽然网络通，但是感觉速度很慢。
期待问题可以解决，感谢！
如有其他需要提供的资料，随时沟通。
![pc1](https://github.com/user-attachments/assets/f34e9eec-27a7-46e0-81a9-3f68f83390cc)
![pc3-1](https://github.com/user-attachments/assets/7d2b5afd-d62c-4045-8bf9-20d40947b9cd)
![pc2-1](https://github.com/user-attachments/assets/4b590897-1daf-4710-9846-7a3c0c005641)
[pc-info-OpenClash-2024-12-13-22-49-35.log](https://github.com/user-attachments/files/18128531/pc-info-OpenClash-2024-12-13-22-49-35.log)
[pc-info-OpenClash-2024-12-13-23-4-40.log](https://github.com/user-attachments/files/18128532/pc-info-OpenClash-2024-12-13-23-4-40.log)



![sj4](https://github.com/user-attachments/assets/07ac719c-efc5-413c-a2db-421e59bebcd7)
![sj3](https://github.com/user-attachments/assets/e9cb2479-7a2a-402d-90eb-a5429d6aab80)
[sj-debug-OpenClash-2024-12-13-23-27-44.log](https://github.com/user-attachments/files/18128542/sj-debug-OpenClash-2024-12-13-23-27-44.log)

**Comment by vernesong** [comment]
访问异常的网站的时候去控制面板看下debug的内核日志

**Comment by showmyse1f** [comment]
> 访问异常的网站的时候去控制面板看下debug的内核日志
sj-debug-OpenClash-2024-12-13-23-27-44.log 这个文件就是通过手机连接Wi-Fi访问网站异常时，debug内核日志。你看可以吗？还是我在去多记录一些debug的内核日志发给你？
[Uploading sj-debug-OpenClash-2024-12-13-23-27-44.log…]()

**Comment by vernesong** [comment]
![image](https://github.com/user-attachments/assets/732b1ca5-31f1-4006-9bd6-77d0e2395712)

**Comment by showmyse1f** [comment]
> ![image](https://private-user-images.githubusercontent.com/42875168/396747046-732b1ca5-31f1-4006-9bd6-77d0e2395712.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0OTM3NjMsIm5iZiI6MTczNDQ5MzQ2MywicGF0aCI6Ii80Mjg3NTE2OC8zOTY3NDcwNDYtNzMyYjFjYTUtMzFmMS00MDA2LTliZDYtNzdkMGUyMzk1NzEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDAzNDQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0Mzk1MjcyYTA3OGZlYWQ4NzI2ZjYwMmNhMzUyOWI4MjVmNTRiODU2MDQwMjU3ZjRmNDQxZjc0NmZhZjJiNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8kFSKicuLwz4I8cst7eQd9vicOWqV_vn4VCD-zCfoLU)



防火墙IP动态伪装 开启了，但还是不行。
Wi-Fi路由设置：
![1-1](https://github.com/user-attachments/assets/cc9f39d2-69a3-4c61-8049-812add690b97)
主路由设置：
![2-1](https://github.com/user-attachments/assets/555f5109-ed36-4dc4-80ce-f5e1eb0cafa4)

debug日志：
[sj-debug-OpenClash-2024-12-18-12-45-51.log](https://github.com/user-attachments/files/18175295/sj-debug-OpenClash-2024-12-18-12-45-51.log)
[pc-debug-OpenClash-2024-12-18-12-43-27.log](https://github.com/user-attachments/files/18175296/pc-debug-OpenClash-2024-12-18-12-43-27.log)



网络结构：
主路由是软路由 使用ImmortalWrt
Wi-Fi路由，只负责Wi-Fi信号3个（实际会更多），使用openwrt
主路由和Wi-Fi路由使用1根网线对接LAN口。为了使多Wi-Fi信号之间互相隔离，在主路由和Wi-Fi路由开启了【接口】的【网桥VALN过滤】功能，每个VLANID从Wi-Fi路由传输到主路由都会打标签标识，配置图如下：
Wi-Fi路由：
![1](https://github.com/user-attachments/assets/94479cc5-49b5-4f90-85dc-8c064a3edcef)
主路由：
![2](https://github.com/user-attachments/assets/5a314a7a-7c04-48ee-96d1-7c187b9e95e5)

**Comment by vernesong** [comment]
你这个问题不明，建议抓包吧，可能回包有问题，日志显示有流量出去

**Comment by showmyse1f** [comment]
> 你这个问题不明，建议抓包吧，可能回包有问题，日志显示有流量出去

首先咨询下在使用 网桥VALN过滤 的模式下，openclash 是可以正常使用的？
你那边复现时配置也使用了VLAN，不会出现这个问题？
我现在也很纳闷，在使用VLAN模式下，关闭了openclash 就可以正常访问，打开就不行......
