### ISSUE TITLE
配置文件订阅-更新模式为“循环”时，“更新间隔(分钟)”无法按预期应用到crontab

### ISSUE THREAD

**Issue by NV3S** [vernesong/OpenClash#423]
更新间隔(分钟)里面的值，会多加一个“/”到crontab里（翻代码没找到在哪儿...
如循环设置为1440分钟，检查crontab为
`*/1440 * * * * /usr/share/openclash/openclash.sh`

这样会造成无法设置成预期周期，错误解析成每小时循环一次。

**Comment by vernesong** [comment]
对，忘记这里只能填小于60的数了

**Comment by NV3S** [comment]
小于60也不行啊
目前配置：更新模式：”预约“
输出：
`0 0 * * 1 /usr/share/openclash/openclash.sh`

更改：更新模式选择”循环“，值从60手动改为10，点应用配置
输出：
`*/10 * * * * /usr/share/openclash/openclash.sh`
