### ISSUE TITLE
dev分支v0.46.060    来源流量访问控制无效

### ISSUE THREAD

**Issue by ppoolluuttii** [vernesong/OpenClash#4237]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [X] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [X] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

v0.46.060

### Bug on Environment

Istoreos

### OpenWrt Version

iStoreOS 22.03.6 2024071911 / LuCI istoreos-22.03 branch git-24.057.30647-6659faa

### Bug on Platform

Linux-amd64(x86-64)

### Describe the Bug

最新dev  0.46.060  Redir-Host模式
填写绕过核心端口无效（同样的模式旧版本填写端口可以绕过）
![Quicker_20241217_175648](https://github.com/user-attachments/assets/c4150880-b947-4c1d-8c93-4c03fe58e7a5)
这是旧版绕过核心端口  实测不会走代理

### To Reproduce

Redir-Host模式正常只要填写绕过端口就行了，实测绕过的端口在v0.46.060版本依然走代理

### OpenClash Log

```log
！
```

### Expected Behavior

新版增加了tcp/udp和v4/6的选择  希望同样Redir-Host模式设置填写端口就能起到作用！！！

**Comment by vernesong** [comment]
必须要写ip和端口

**Comment by ppoolluuttii** [comment]
对于内网穿透（打洞）需要穿透本地端口绕过核心代理，我该怎么写？

假如内网穿透服务和clash在同一个软路由
192.168.1.1，内网穿透服务服务打洞，穿透服务的本地端口12345，需要穿透的本地服务为192.168.1.1:1234

那么我在新版v0.46.060需要填写ip加端口才能绕过核心代理，我该怎么写才起作用呢？（旧版Redir-Host模式，我直接填写12345就能绕过核心，穿透到公网）

**Comment by vernesong** [comment]
防火墙看一下

**Comment by vernesong** [comment]
看看61

**Comment by ppoolluuttii** [comment]
最新0.46.061设置127.0.01+端口还是无法绕过核心。开起openclash，就无法穿透(转发)到真正的公网（显示的公网是代理节点IP），关闭openclash就可以

我看您从v0.46.059到060最大的变化就是这个端口绕过核心代理的优化，作用就是防止端口走代理无法转发吧？
![Quicker_20241220_163612](https://github.com/user-attachments/assets/364141a0-31b2-41ae-8bdb-569598ebada6)
旧版本Redir-Host下我填写端口12345绕过核心，在内网穿透服务中本地端口填写12345，能顺利穿透转发到公网，填写除12345以外的端口会转发不成功或者显示节点IP。关闭代理openclash的情况下穿透转发服务不受12345限制。

新版本涉及tcp/udp  v4/v6可供选择，端口那么多没必要这么细分吧！  v6的话不就是公共网吗？
或许我还没有get到这些细分功能的用途，还有就是看了下防火墙   固件本目前还没支持FW4，或许这是个原因？？？
![Quicker_20241220_165639](https://github.com/user-attachments/assets/d9fe9568-a53a-449b-a2eb-6d27b0d291f7)

您可以尝试下最新版在开启代理的情况下，弄一个v4内网穿透（转发）端口试试，能不能把本地服务穿透转发到公网。（我之所以旧版可以可能涉及到固件版本问题）

**Comment by vernesong** [comment]
本机不是127.0.0.1，填lan的ip

**Comment by ppoolluuttii** [comment]
穿透服务里面自带“防火墙自动放行”开关，穿透通道本地端口12345设置成绕过核心就能避免代理穿透失败或者是显示穿透到节点IP
![IMG_8417](https://github.com/user-attachments/assets/be7eae55-76d0-4ffa-bbaf-cece08b87aee)

现在用新版openclash，解决办法就是手动去防火墙开放12345端口，穿透服务里面的防火墙自动放行关闭，这样一来正常了😂，小猫咪也不需要设置12345绕过核心。到头来还是手动稳😁

感谢大佬解答，关闭吧

**Comment by ppoolluuttii** [comment]
> 为什么要关闭这个问题，我也遇到了同样的问题，只能回滚到上一个版本

不折腾了，原本用于内网穿透（走直连），我现在直接手动防火墙放行某个固定端口，不受代理软件控制
