### ISSUE TITLE
[Bug] "来源流量访问控制"上移下移按钮显示错误

### ISSUE THREAD

**Issue by NextAbyss** [vernesong/OpenClash#4242]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [ ] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

v0.46.060

### Bug on Environment

Immortalwrt

### OpenWrt Version

ImmortalWrt 23.05-SNAPSHOT (r0-951f50c) 

### Bug on Platform

Linux-amd64(x86-64)

### Describe the Bug

![屏幕截图 2024-12-19 093159](https://github.com/user-attachments/assets/bad338bf-2b75-4d67-8d59-97b67814da20)
应该是上移下移而不是在线下线.

### To Reproduce

插件设置->来源流量访问控制

### OpenClash Log

```log
无需日志
```

### Expected Behavior

按钮显示应该是上移下移而不是在线下线.

**Comment by NextAbyss** [comment]
顺便问一下，那个target中的return和accept有什么区别呢

**Comment by vernesong** [comment]
其他插件乱翻译

**Comment by gemnioo** [comment]
当前客户端版本 	v0.46.061  "来源流量访问控制"  会出现在 插件设置下任意类目底部： 如下图

![image](https://github.com/user-attachments/assets/22943de2-bc98-4c9a-8612-f9073eed5b05)

![image](https://github.com/user-attachments/assets/47f29f99-fdb7-46b6-a31a-9d300c145017)

![image](https://github.com/user-attachments/assets/2ba3de45-ae97-41d8-baf7-3b874de89d92)

**Comment by NextAbyss** [comment]
> 其他插件乱翻译

没开翻译插件，ImmortalWrt有问题，换回LEDE没问题了，我昨天试了这个功能真好用终于可以成功让游戏NAT1了。不过我试了一下ACCEPT和RETURN好像都可以。

**Comment by NextAbyss** [comment]
> 当前客户端版本 v0.46.061 "来源流量访问控制" 会出现在 插件设置下任意类目底部： 如下图
> 
> ![image](https://private-user-images.githubusercontent.com/20894536/397929168-22943de2-bc98-4c9a-8612-f9073eed5b05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3ODcwMzgsIm5iZiI6MTczNDc4NjczOCwicGF0aCI6Ii8yMDg5NDUzNi8zOTc5MjkxNjgtMjI5NDNkZTItYmM5OC00YzlhLTg2MTItZjkwNzNlZWQ1YjA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDEzMTIxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExYzEwNTVkZjlkZjY5MDI0N2NkOTgzMzhjN2FkYzUyMjZmNDg5ZjA1MzgyNTc3YzY3MjM1ZjlmN2ZhMTE0OTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.l8ET43A_bTffEzzwXc0oMuFiBXoK9QFiRFdJULefqkk)
> 
> ![image](https://private-user-images.githubusercontent.com/20894536/397929190-47f29f99-fdb7-46b6-a31a-9d300c145017.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3ODcwMzgsIm5iZiI6MTczNDc4NjczOCwicGF0aCI6Ii8yMDg5NDUzNi8zOTc5MjkxOTAtNDdmMjlmOTktZmRiNy00NmI2LWEzMWEtOWQzMDBjMTQ1MDE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDEzMTIxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlNjQ2YWFmYjgwMzM3Y2ExMWEzZWI3MGE3MGZiZTRlYjQyNWJlZWNiNjEwM2IxOTM3ZThlZjM2YjNjZThkNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ID6EsRECpuFVhcW1l8yDZsXRfDz-JhP9AsJA60FQPWg)
> 
> ![image](https://private-user-images.githubusercontent.com/20894536/397929224-2ba3de45-ae97-41d8-baf7-3b874de89d92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3ODcwMzgsIm5iZiI6MTczNDc4NjczOCwicGF0aCI6Ii8yMDg5NDUzNi8zOTc5MjkyMjQtMmJhM2RlNDUtYWU5Ny00MWQ4LWJhZjctM2I4NzRkZTg5ZDkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDEzMTIxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1NjY0OGZiY2EzMzZiMGZkYmJjODJlNDI1YzhhNzVjZGZhMWQwYTYwMTZhNjY3M2VmMzBhNWFhN2RhYjE4OWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MsbiCrPX35RlMYAEumBkCKA4nkFRuYLVrNc8_uASGYQ)

我倒是没你这个症状
