### ISSUE TITLE
chrome访问网页会间歇性地显示连接已重置

### ISSUE THREAD

**Issue by yuerongz97** [vernesong/OpenClash#425]
N1盒子openwrt系统下开启openclash 模式为fake-ip增强 dns为119.29.29.29与114.114.114.114
PC使用chrome访问网页时一瞬间会显示连接已重置页面，然后自动刷新成正常的页面

**Comment by yuerongz97** [comment]
![微信图片_20200509123736](https://user-images.githubusercontent.com/18389778/81464196-e1d1f280-91f1-11ea-921f-d703c5ffd7c0.png)

**Comment by hcym** [comment]
嗯，偶尔也会，一般来说路由还是用大雕方便也稳定，手机用clash，就算是费电也认了，广告出国组合的非常不错

**Comment by yuerongz97** [comment]
试了一下ssrplus和passwal，发现都会有类似的问题，最后还是换回clash了哈哈

**Comment by hcym** [comment]
大雕的没有遇过，pass可能有，也是劫持dnsmasq的

**Comment by Alunixa** [comment]
我也是

**Comment by Alunixa** [comment]
经过一些测试我发现多出现在。设备----路由器-----软路由---猫   这样子或者    设备-----路由器------猫
                                                                                                                                          |
                                                                                                                                     软路由


中间如果没有间隔设备或者间隔设备是桥接的则不会或者少出现此情况。推测可能是网络中dns服务器不唯一或者dns劫持出错导致链接中断。
