### ISSUE TITLE
状态页IP 获取与状态查询并非路由器真实状态

### ISSUE THREAD

**Issue by msxy47** [vernesong/OpenClash#426]
假设路由器为A ，通过B 机器访问A 的luci 页面，状态页IP 与访问检测的状态是B 机器的，不能反映openclash 所在路由器的真实状况。

今天在外远程发现家里宽带的运营商居然变了才注意到这个问题。
不知道是不是因为考虑非fakeip 不能代理路由本身做的这样的设计。

下图两图显示的是路由openclash关闭但访问luci 机器有代理情况下打开的状态页。
![image](https://user-images.githubusercontent.com/8243923/81467839-ffad5080-920d-11ea-893b-180346916301.png)
![image](https://user-images.githubusercontent.com/8243923/81467845-076cf500-920e-11ea-8eef-305035adb9e7.png)

**Comment by okaygh** [comment]
![QQ截图20200509212536](https://user-images.githubusercontent.com/25192149/81474979-a9570680-923b-11ea-9148-04a3e569f1cd.png)
为何我的从来都是无法访问
