### ISSUE TITLE
版本更新【TUN模式】内核版本

### ISSUE THREAD

**Issue by zfkira** [vernesong/OpenClash#428]
![Issue](https://user-images.githubusercontent.com/22000271/81478865-86841c80-9252-11ea-83c6-e2d43391cd60.JPG)

不好意思，想问tun 模式始终更新不了呢？点击下载到本地也不行

**Comment by vernesong** [comment]
官方移除了下载地址，你可以自己暂时去 https://github.com/Dreamacro/clash/releases/tag/premium 下载最新版本后手动上传

**Comment by zfkira** [comment]
谢谢大师~
