### ISSUE TITLE
关于内网IP如何在Openclash中设置被排除的问题

### ISSUE THREAD

**Issue by zfkira** [vernesong/OpenClash#429]
您好，作者，想问下，如何在open clash 中，设置局域网的某特定几台PC，设备，不走科学上网（不走代理），类似passwall 和ssrplus的 访问控制（基于IP+mac这种的），open clash中有类似的设置吗？（其实我是想以mac-address去排除，因为IP会受租赁时间的变化而变化，而我不想麻烦的去上层设备去手动一一绑定，请问在open clash中有基于ip+mac这种去排除我局域网内不想让其走代理的设置吗？谢谢！

**Comment by 2013108827** [comment]
据我所知，没看到过有能限制mac地址的规则，一般的都是手动绑定内网IP，然后再按照规则限制单个IP或者限制IP段走直连或者代理

**Comment by himonster1** [comment]
楼主解决了么

**Comment by deadlyedge** [comment]
可以在 `全局设置-规则设置（访问控制）-自定义规则（访问控制）` 下方的文本框中编辑规则，类似如下条目：
`##- SRC-IP-CIDR,192.168.1.201/32,DIRECT #匹配数据发起IP(直连)`
单个ip后缀是 `/32` ，多个ip可以使用转换工具自行转换。
[https://www.ipaddressguide.com/cidr](url) 或者 [https://ip2cidr.com/](url)

**Comment by himonster1** [comment]
> 可以在 `全局设置-规则设置（访问控制）-自定义规则（访问控制）` 下方的文本框中编辑规则，类似如下条目： `##- SRC-IP-CIDR,192.168.1.201/32,DIRECT #匹配数据发起IP(直连)` 单个ip后缀是 `/32` ，多个ip可以使用转换工具自行转换。 [https://www.ipaddressguide.com/cidr](url) 或者 [https://ip2cidr.com/](url)

好的 谢谢了  想要让这行代码生效 需要把前面的两个#都删除才可以吧

**Comment by wordscode** [comment]
- SRC-IP-CIDR,192.168.1.1/32,DIRECT
- SRC-IP-CIDR,192.168.1.2/31,DIRECT
- SRC-IP-CIDR,192.168.1.4/30,DIRECT
- SRC-IP-CIDR,192.168.1.8/29,DIRECT
- SRC-IP-CIDR,192.168.1.16/28,DIRECT
- SRC-IP-CIDR,192.168.1.32/27,DIRECT
- SRC-IP-CIDR,192.168.1.64/26,DIRECT
- SRC-IP-CIDR,192.168.1.128/25,DIRECT
我路由器是192.168.1.1，这样写配置对吗？
我还是ping不了。。
