### ISSUE TITLE
手动添加Fake-IP域名黑名单无法生效

### ISSUE THREAD

**Issue by zfh135072** [vernesong/OpenClash#431]
1. 【游戏模式】内核版本  v0.17.0-111-g73913b1
2. 当前客户端版本 v0.38.1-beta
3. Fake-IP(游戏)模式
DNS设置中手动添加Fake-IP域名后，点击“检查并更新”，一直提示“正在设置Fake-IP黑名单... ”，而且设置的域名未生效为真实IP
Fake-IP增强模式同样的情况

**Comment by vernesong** [comment]
你可以直接运行`/usr/share/openclash/openclash_fake_filter.sh`找报错原因

**Comment by zfh135072** [comment]
> 
> 
> 你可以直接运行`/usr/share/openclash/openclash_fake_filter.sh`找报错原因

可以了，DNS设置中最后一行要留空行，否则最后一行的域名不会添加到Fake-IP黑名单中，另外不知道什么原因，如果用户配置文件fake-ip-filter中有同样的域名的话，好像不生效？

**Comment by zfh135072** [comment]
还有个问题，添加Fake-IP黑名单，软路由中nslookup响应为

Server:		127.0.0.1
Address:	127.0.0.1#53

*** Can't find y.qq.com: Parse error
*** Can't find y.qq.com: No answer
