### ISSUE TITLE
在 tun 内核模式下的，自动 reload 问题

### ISSUE THREAD

**Issue by mephisX** [vernesong/OpenClash#432]
具体状况就是用 real-ip TUN 模式下，原版TUN内核。
会莫名其妙上不了网，只有 socks5 能上网。
一看运行日志
```
2020-05-10 21:45:55 未处理Clash Reload After Firewall Restart
```
每天都会出现好几次，需要手动关闭openclash 然后重新运行 openclash 才可以正常上网。
不过有时候等个几分钟也能上网（就是通过tun模式连接互联网，socks5则是一直都可以上网）

**Comment by vernesong** [comment]
你应该找找是什么原因导致防火墙频繁重启

**Comment by mephisX** [comment]
> 你应该找找是什么原因导致防火墙频繁重启

我先重新刷固件试试。
