### ISSUE TITLE
IP地址显示异常

### ISSUE THREAD

**Issue by Noche51** [vernesong/OpenClash#434]
版本0.38-1
![image](https://user-images.githubusercontent.com/52929974/81503913-d3322b00-9318-11ea-9b54-d54d9e21b825.png)
启用后，IP地址显示异常，全部都是国内IP地址

**Comment by vernesong** [comment]
受规则影响，能用就行

**Comment by lrgcx** [comment]
如何让它国外那里显示实际的外网IP？

**Comment by Noche51** [comment]
因为这个原因，有些网站直接给我墙了，只能在规则上把网站加上

**Comment by lrgcx** [comment]
能具体一点吗？我也是这样的

**Comment by Noche51** [comment]
把你要上的网站，加在clash规则里，就是自己动手修改后缀名为yml的配置文件
这个是clash的指导网站https://docs.cfw.lbyczf.com/contents/ui/profiles/rules.html

**Comment by lrgcx** [comment]
谢谢回复，我试试。

**Comment by lrgcx** [comment]
openclash的修改老是报错。

**Comment by Noche51** [comment]
clash的订阅连接？

**Comment by lrgcx** [comment]
规则。我现在一个noip的域名在openclash下显示为198.18.0.X，在用sppr就不会。

**Comment by lrgcx** [comment]
ssrp

**Comment by lrgcx** [comment]
而且是升级到0.38.1才出现的

**Comment by Noche51** [comment]
可能是你修改规则修改错了吧

**Comment by lrgcx** [comment]
没修改就这样。在dns高级里添加了dns服务器也没改变，再等等看。

**Comment by Noche51** [comment]
我用luci-app-clash 不用修改规则，ip地址测试直接就是国外的，用openclash的时候，需要把规则修改一下，才会上去被qiang网站，

**Comment by Noche51** [comment]
![image](https://user-images.githubusercontent.com/52929974/81664899-9417ed00-9472-11ea-921e-9a9246c19114.png)
我把两个测ip网站添加到规则里，就可以正常了

**Comment by lrgcx** [comment]
哪两个网站？添加到哪里？我就是想知道这个。谢谢！

**Comment by Noche51** [comment]
我用的是这个规则：https://github.com/tindy2013/subconverter
 - DOMAIN-SUFFIX,ip.sb,🔰 节点选择
 - DOMAIN-SUFFIX,ipify.org,🔰 节点选择
这样就可以了

**Comment by lrgcx** [comment]
感谢感谢，先试试，看看我能不能搞掂。

**Comment by lrgcx** [comment]
搞掂，谢谢啦！

**Comment by 3323** [comment]
> 搞掂，謝謝啦！
怎么搞定的？
