### ISSUE TITLE
刷固件配置保留问题

### ISSUE THREAD

**Issue by CrazyMouse** [vernesong/OpenClash#435]
openclash集成到lean的openwrt中，发现两个配置问题
1.刷完后无法直接启动openclash，需要更新一下订阅源
2.页面自定义规则在刷固件后会丢失，需要重新配置

**Comment by vernesong** [comment]
这个跟固件的逻辑有关，插件已经把需要备份的东西都告诉了。
![image](https://user-images.githubusercontent.com/42875168/81524444-cd256400-9383-11ea-8f05-9700735c8d1f.png)

**Comment by hcym** [comment]
刷固件刷手机千万不要保留配置，省得莫明其妙的麻烦

**Comment by CrazyMouse** [comment]
/etc/config/adbyby
/etc/config/aria2
/etc/config/arpbind
/etc/config/attendedsysupgrade
/etc/config/autoreboot
/etc/config/black.list
/etc/config/ddns
/etc/config/dhcp
/etc/config/docker
/etc/config/dropbear
/etc/config/firewall
/etc/config/flowoffload
/etc/config/frp
/etc/config/frps
/etc/config/fstab
/etc/config/gfw.list
/etc/config/google_fu_mode
/etc/config/hd-idle
/etc/config/luci
/etc/config/mia
/etc/config/minidlna
/etc/config/netflix.list
/etc/config/netflixip.list
/etc/config/network
/etc/config/nlbwmon
/etc/config/ntpclient
/etc/config/openclash
/etc/config/rpcd
/etc/config/samba
/etc/config/sfe
/etc/config/shadowsocksr
/etc/config/sqm
/etc/config/system
/etc/config/ucitrack
/etc/config/uhttpd
/etc/config/unblockmusic
/etc/config/upnpd
/etc/config/v2ray_server
/etc/config/vlmcsd
/etc/config/vnstat
/etc/config/vsftpd
/etc/config/white.list
/etc/config/wifi_schedule
/etc/config/wrtbwmon
/etc/crontabs/root
/etc/dnsmasq.conf
/etc/dropbear/authorized_keys
/etc/dropbear/dropbear_rsa_host_key
/etc/firewall.user
/etc/group
/etc/hosts
/etc/inittab
/etc/luci-uploads/.placeholder
/etc/opkg/keys/1035ac73cc4e59e3
/etc/opkg/keys/20bc240e06d09ab1
/etc/opkg/keys/5151f69420c3f508
/etc/opkg/keys/72a57f2191b211e0
/etc/opkg/keys/792d9d9b39f180dc
/etc/opkg/keys/9ef4694208102c43
/etc/opkg/keys/b26f36ae0f4106d
/etc/opkg/keys/b5043e70f9a75cde
/etc/opkg/keys/c10b9afab19ee428
/etc/opkg/keys/dace9d4df16896bf
/etc/opkg/keys/dd6de0d06bbd3d85
/etc/opkg/keys/ebc480b2740a1db4
/etc/passwd
/etc/profile
/etc/rc.local
/etc/shadow
/etc/shells
/etc/sysctl.conf


这个是lean的固件的配置，想问一下，除了刷机后手工去定制这个列表，有办法在编译固件的时候定制么？ @vernesong

**Comment by CrazyMouse** [comment]
![image](https://user-images.githubusercontent.com/1176862/81562938-34fd9e00-93c8-11ea-836c-9411df7fcdce.png)
貌似我找到定制点了

**Comment by CrazyMouse** [comment]
> 刷固件刷手机千万不要保留配置，省得莫明其妙的麻烦

和手机有啥关系

**Comment by CrazyMouse** [comment]
> 刷固件刷手机千万不要保留配置，省得莫明其妙的麻烦

存在即合理，知道原理了出问题能搞定就行 ，总比每次都重新配置省事多了

**Comment by vernesong** [comment]
/lib/upgrade/keep.d/

**Comment by CrazyMouse** [comment]
通过实验，在上面截图的文件中编译时加上 /etc/openclash/  可以完美解决，另外分享一下我的仓库，https://github.com/CrazyMouse/openwrt
