### ISSUE TITLE
运行内存占用很高

### ISSUE THREAD

**Issue by lswymxk** [vernesong/OpenClash#436]
我是用在nanopi的开发版上，全智h5的CPU，软件运行一段时间后，占用内存非常高，达到1.5G左右，请问这个正常吗，用的最新版，clash内核，第三方规则

**Comment by vernesong** [comment]
cpu占用高带宽的时候会高一点，内存不会太多

**Comment by lifei6671** [comment]
N1上2G内存被占用了70%。

**Comment by lswymxk** [comment]
我也是，不知道是个案还是有bug

**Comment by hcym** [comment]
没注意内存，路由偶尔用一下，还是用大雕的好。老版本有域名白名单失效的问题，有点抓狂，新版本似乎好了，手机用clash绝对优势，费电也认了

**Comment by NV3S** [comment]
> 我是用在nanopi的开发版上，全智h5的CPU，软件运行一段时间后，占用内存非常高，达到1.5G左右，请问这个正常吗，用的最新版，clash内核，第三方规则

诸位用什么的看的？如果是openwrt里面用top看，vst的值是虚拟内存，没多大参考意义
[vst](https://forum.archive.openwrt.org/viewtopic.php?id=38234)
你看一下free
另：如果用当红的servercat连上去看，会有两个指征，一个是free值，应该看到内存占用很少，空闲很大，第二个如果单看进程，调用的应该是top，显示的是vst值

**Comment by hcym** [comment]
今天注意了一下，非常低，七八十兆上下，2G内存armv8的

**Comment by bingfoon** [comment]
luci界面里系统进程那里显示的内存占用率不准，直接ssh进路由，输入 free 查看内存使用情况

**Comment by hcym** [comment]
内存一直不高，CPU用tun模式是高一点，但是体验好多了，最近一直用clash，分流太方便了😂

**Comment by zhihuiyuze** [comment]
`root@OpenWrt:~# free -m
              total        used        free      shared  buff/cache   available
Mem:        4042296     3491764      515004        2592       35528     3388168
Swap:             0           0           0`

**Comment by hcym** [comment]
可能是硬件兼容问题，我的几个x86和s912，s905还有s922都没有内存问题
