### ISSUE TITLE
使用内核自带的fake-ip-filter替代dnsmasq实现fake-ip模式下的real-ip功能不支持fake-ip-filter指定dns

### ISSUE THREAD

**Issue by cygmris** [vernesong/OpenClash#437]
clash: v0.20.0
openclash: v0.38.1-beta

## 问题1:
新版本更新了一个feature：使用内核自带的fake-ip-filter替代dnsmasq实现fake-ip模式下的real-ip功能

和旧版使用dnsmasq从业务上相比，不支持fake-ip-filter指定dns，在此之前可以指定fake-ip-filter内的域名走私人dns，而无需clash配置文件内指定dns服务器。

新版想要实现私人dns既内部域名，只能通过clash配置文件自定义dns的方式。

## 问题2:
> fake-ip-filter内的地址通配符不支持全域统配

添加一条`*.*.cluster.local`的fake-ip-filter规则.
发现 `a.b.cluster.local `可以生效，但是`a.b.c.cluster.local`或`a.b.c.d.cluster.local` 并不生效。

必须添加`*.*.*.*.cluster.local`的规则才可以使`a.b.c.d.cluster.local` 生效，其它情况同理。

**Comment by vernesong** [comment]
问题一如果你有特殊用途可以自己在
`/var/dnsmasq.d`下创建一个文件写入`server=/www.baidu.com/114.114.114.114`
问题二目前只能这样使用，等待支持

**Comment by cygmris** [comment]
@vernesong 问题2之前已经解决了，直接采用`.baidu.com`的写法。所有级别子域都可以匹配。然后问题一也是可行的，目前满足需求且使用正常。
