### ISSUE TITLE
启用openclash后国内网站下载速度极慢

### ISSUE THREAD

**Issue by JosephCN** [vernesong/OpenClash#438]
检查链接，确实国内下载（如天翼云 百度云等）走的是直连
关闭openclash后速度恢复至10mb/s，启用openash，速度只有500kb左右。

**Comment by OleStore** [comment]
![2020-05-13_091109](https://user-images.githubusercontent.com/1283711/81760423-b99c0980-94f9-11ea-9e1a-a4aca6468fd5.jpg)
速度正常，未开通会员

**Comment by JosephCN** [comment]
> ![2020-05-13_091109](https://user-images.githubusercontent.com/1283711/81760423-b99c0980-94f9-11ea-9e1a-a4aca6468fd5.jpg)
> 速度正常，未开通会员

可是国内站点未代理呀，反而代理的境外站点速度很快

**Comment by vernesong** [comment]
全局直连试试，如果正常就是规则的问题导致走代理了

**Comment by haossu** [comment]
看一下选择的内核，我这边的话采用Dev 内核速度会快，Tun 模式，Game模式下速度有很大影响

**Comment by JosephCN** [comment]
> 全局直连试试，如果正常就是规则的问题导致走代理了

全局直连一样速度很慢

**Comment by JosephCN** [comment]
请教大神解答一下哈～～
目前经过尝试，一旦开启OpenClash，百度云和天翼云的下载速度会从18MB/s 下降到3MB/s。关闭OpenClash后立即恢复下载速度。目前Redir和Fake-ip都尝试了，均有此问题。

**Comment by kongkongzzz** [comment]
我这边也遇到了过clash内核网速减半的问题，不只是openclash还是clash core还是固件的问题

**Comment by OleStore** [comment]
> 请教大神解答一下哈～～
> 目前经过尝试，一旦开启OpenClash，百度云和天翼云的下载速度会从18MB/s 下降到3MB/s。关闭OpenClash后立即恢复下载速度。目前Redir和Fake-ip都尝试了，均有此问题。

丢个天翼云 分享链接，我测试看看下载速度

**Comment by frank2002** [comment]
你好，我这边遇到了同样的问题，“刚开openclash没问题，过一段时间（大约几小时）出现问题”。刚开始测速500Mbps，过几个小时速度只能达到70Mbps。我使用的是redir-host（兼容）模式，没有转发UDP流量。当开启了绕过大陆IP模式，国内访问速度正常。如果关闭，国内访问速度只能达到70Mbps（家宽500Mbps）。通过代理走的流量全都是只能达到70Mbps（很稳定）（已知节点能跑满500Mbps）。
路由器cpu为i3-7100u，已知没有跑满，只有30%左右。内存也剩余70%左右。
还望解答，谢谢！

**Comment by kongkongzzz** [comment]
我这边用的是fake ip的各模式，开启了udp或者tun模式下的system。fake ip 增强出现问题的几率最小，同上出问题时国内速度和国外速度相同且非常慢（同很稳定的慢）。CPU，内存没占用满。若为redir-host，同开启了绕过大陆IP速度正常，关闭异常。clash连接界面显示没有走代理，测速网站显示的ip显示的是本地ip，非代理，应该可以确定很慢的时候并没有走代理。

**Comment by vernesong** [comment]
插件正常运行的话，我这边还不清楚原因，可以去内核那边反馈

**Comment by frank2002** [comment]
个人不是很懂，不好意思。如果是内核问题的话，是不是意味着Clash for Windows或者Clash for Android也会出现这个问题？但是我使用windows或者安卓版的时候都是可以跑满网速的，没有出现以上问题。

**Comment by frank2002** [comment]
我已经解决了，我之前使用了OpenWrt的SQM流控插件，关闭之后速度回到正常水平。

**Comment by fannysilence** [comment]
看别的ISSUES上说好像是和SQM 还有 BBR有冲突，我没有用SQM开了BBR会变慢。然后我刚刚关掉之后速度恢复了，还要再观察一阵看看

**Comment by LittleTurtle2333** [comment]
我也有这个问题，并且clash还设置的是全球直连

**Comment by smallst** [comment]
@fannysilence 能请问一下是哪里看到的吗？想了解一下和bbr 的冲突，毕竟bbr应该也是加速用的。谢谢

**Comment by fannysilence** [comment]
> @fannysilence 能请问一下是哪里看到的吗？想了解一下和bbr 的冲突，毕竟bbr应该也是加速用的。谢谢

记不清了。。。好像是 clash那边的issues看到的。时间有点久了
我现在直接不开BBR  梯子和BBR那一点速度，我选择梯子

**Comment by smallst** [comment]
> > @fannysilence 能请问一下是哪里看到的吗？想了解一下和bbr 的冲突，毕竟bbr应该也是加速用的。谢谢
> 
> 记不清了。。。好像是 clash那边的issues看到的。时间有点久了
> 我现在直接不开BBR 梯子和BBR那一点速度，我选择梯子

好的，还是谢谢了，下次再遇到这个问题我也把bbr关了好了

**Comment by Senorsen** [comment]
也遇到此问题了，有幸搜到本 issue 才发现。如果确定 bbr 跟插件有兼容性问题，建议能加个检测和警告功能（就像现在的 IPv6 DHCP 相关警告那样），这样之后用户网速就不会慢慢地莫名其妙变慢了
