### ISSUE TITLE
网速&YouTube 播放相关

### ISSUE THREAD

**Issue by haossu** [vernesong/OpenClash#439]
个人设置 ，供参考。 设备 n1 单臂主路由

- fake-ip/Redir-Host 模式下，保证speedtest 测速为直连，UDP 转发开启， 其中关闭OpenClash 下载速度为 385M 

|  内核  |  Fake-IP  |  Redir-Host |
| ------------- | ------------- | ------|
| Dev  |  392M  | 395M |
| Tun  | 102M  | 127M |
| 游戏  | 64M  | 63M |

- Fake-IP Dev 内核开启UDP转发情况下，YouTube chrome 视频播放 稳定3w分，Chrome 设置 chrome://flags/#enable-quic 为Disabled 后 可后显著提升至13w，节点分数供参考。

使用整体完美，感谢大佬开发

**Comment by MOOnLyer** [comment]
想问下你是怎么设置的 我dev内核 都只能到80M 左右 直连 关掉clash能到380左右

**Comment by haossu** [comment]
> 想问下你是怎么设置的 我dev内核 都只能到80M 左右 直连 关掉clash能到380左右

设备是啥呢？没啥动的，就是默认设置，你看下speedtest是不是走代理了1

**Comment by MOOnLyer** [comment]
93P 然后看了下cpu也没跑满 后台看进程是走direct的 没走代理

**Comment by MOOnLyer** [comment]
你用的也是最新版的吗？
