### ISSUE TITLE
Fake-IP黑名单域名，nslookup找不到IP

### ISSUE THREAD

**Issue by zfh135072** [vernesong/OpenClash#440]
添加Fake-IP黑名单，设置DNS上游为127.0.0.1#5553(AdguardHome)
软路由中nslookup响应为

Server: 127.0.0.1
Address: 127.0.0.1#53

*** Can't find y.qq.com: Parse error
*** Can't find y.qq.com: No answer

**Comment by vernesong** [comment]
那是你上游的原因
