### ISSUE TITLE
科学上网就是无法访问www.google.com

### ISSUE THREAD

**Issue by otherbanana** [vernesong/OpenClash#441]
用的是redir-host模式，一开始以为是dns的问题，然后自定义上游DNS还是不行。

下面是调试日志
OpenClash 调试日志

生成时间: 2020-05-14 11:48:46
插件版本: v0.38.1-beta

#===================== 系统信息 =====================#
主机型号: Phicomm N1
固件版本: OpenWrt SNAPSHOT r2419-5e9e8d85
LuCI版本: git-20.088.29068-cebe120-1
内核版本: 5.4.30-flippy-33+
处理器架构: aarch64_generic

#此项在使用Tun模式时应为ACCEPT
防火墙转发: ACCEPT

#此项有值时建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: 

#此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 127.0.0.1#7874

#===================== 依赖检查 =====================#
dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
jsonfilter: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
iptables-mod-tproxy: 已安装
kmod-tun(TUN模式): 已安装
luci-compat(Luci-19.07): 未安装

#===================== 内核检查 =====================#
运行状态: 运行中
已选择的架构: linux-armv8

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: v0.20.0
Tun内核文件: 存在
Tun内核运行权限: 正常

Game内核版本: 
Game内核文件: 不存在
Game内核运行权限: 否

Dev内核版本: v0.20.0
Dev内核文件: 存在
Dev内核运行权限: 正常

#===================== 插件设置 =====================#
当前配置文件: /etc/openclash/config/config.yaml
运行模式: redir-host
默认代理模式: Rule
UDP流量转发: 启用
DNS劫持: 启用
自定义DNS: 启用
IPV6-DNS解析: 停用
禁用Dnsmasq缓存: 停用
自定义规则: 停用
仅允许内网: 停用
仅代理命中规则流量: 停用

#启动异常时建议关闭此项后重试
保留配置: 启用

#启动异常时建议关闭此项后重试
第三方规则: ConnersHua
第三方规则策略组设置:
GlobalTV: 🚀 节点选择
AsianTV: 🚀 节点选择
Proxy: 🚀 节点选择
Apple: DIRECT
Netflix: 
Spotify: 
Steam: 
AdBlock: REJECT
Netease Music: 
Speedtest: 
Telegram: 
Microsoft: 
PayPal: 
Domestic: DIRECT
Others: 🚀 节点选择

读取的配置文件策略组:
🚀 节点选择
♻️ 自动选择
🎯 全球直连
🛑 全球拦截
🐟 漏网之鱼
DIRECT
REJECT

#===================== 配置文件 =====================#
port: 7890
socks-port: 7891
allow-lan: true
bind-address: "*"
mode: Rule
log-level: silent
external-controller: 0.0.0.0:9090
redir-port: 7892
secret: ""
external-ui: "/usr/share/openclash/dashboard"
hosts:
##Custom HOSTS##
#  experimental hosts, support wildcard (e.g. *.clash.dev Even *.foo.*.example.com)
#  static domain has a higher priority than wildcard domain (foo.example.com > *.example.com)
#  NOTE: hosts don't work with `fake-ip`

#  '*.clash.dev': 127.0.0.1
#  'alpha.clash.dev': '::1'
##Custom HOSTS END##
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 127.0.0.1:7874
  fake-ip-filter:
##Custom DNS##
  nameserver:
  - 114.114.114.114
  - 119.29.29.29
  - 8.8.8.8

#===================== 防火墙设置 =====================#

#NAT chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    REDIRECT   tcp  --  0.0.0.0/0            8.8.4.4              redir ports 7892
2    REDIRECT   tcp  --  0.0.0.0/0            8.8.8.8              redir ports 7892
3    CLOUD_MUSIC  tcp  --  0.0.0.0/0            0.0.0.0/0            match-set music dst
4    REDIRECT   udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:53 redir ports 53
5    REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:53 redir ports 53
6    prerouting_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom prerouting rule chain */
7    zone_lan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
8    zone_vpn_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
9    openclash  tcp  --  0.0.0.0/0            0.0.0.0/0           
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         

#Mangle chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    openclash  udp  --  0.0.0.0/0            0.0.0.0/0           
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         

#===================== 路由表状态 =====================#
#route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.0.1     0.0.0.0         UG    0      0        0 eth0
172.31.0.0      0.0.0.0         255.255.255.0   U     0      0        0 docker0
192.168.0.0     0.0.0.0         255.255.255.0   U     0      0        0 eth0
#ip route list
default via 192.168.0.1 dev eth0 proto static 
172.31.0.0/24 dev docker0 proto kernel scope link src 172.31.0.1 linkdown 
192.168.0.0/24 dev eth0 proto kernel scope link src 192.168.0.27 
#ip rule show
0:	from all lookup local 
32765:	from all fwmark 0x162 lookup 354 
32766:	from all lookup main 
32767:	from all lookup default 

#===================== 端口占用状态 =====================#
tcp        0      0 :::7890                 :::*                    LISTEN      29183/clash
tcp        0      0 :::7891                 :::*                    LISTEN      29183/clash
tcp        0      0 :::7892                 :::*                    LISTEN      29183/clash
tcp        0      0 :::9090                 :::*                    LISTEN      29183/clash
udp        0      0 127.0.0.1:7874          0.0.0.0:*                           29183/clash
udp        0      0 :::7891                 :::*                                29183/clash
udp        0      0 :::7892                 :::*                                29183/clash
udp        0      0 :::59269                :::*                                29183/clash
udp        0      0 :::49095                :::*                                29183/clash
udp        0      0 :::47191                :::*                                29183/clash
udp        0      0 :::45231                :::*                                29183/clash
udp        0      0 :::52420                :::*                                29183/clash
udp        0      0 :::52738                :::*                                29183/clash

#===================== 测试本机DNS查询 =====================#
Server:		127.0.0.1
Address:	127.0.0.1#53

Name:      www.baidu.com
www.baidu.com	canonical name = www.a.shifen.com
Name:      www.a.shifen.com
Address 1: 183.232.231.174
Address 2: 183.232.231.172
*** Can't find www.baidu.com: No answer

#===================== resolv.conf.auto =====================#
# Interface lan
nameserver 192.168.0.1

#===================== 测试本机网络连接 =====================#
HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: private, no-cache, no-store, proxy-revalidate, no-transform
Connection: keep-alive
Content-Length: 277
Content-Type: text/html
Date: Thu, 14 May 2020 03:48:47 GMT
Etag: "575e1f6f-115"
Last-Modified: Mon, 13 Jun 2016 02:50:23 GMT
Pragma: no-cache
Server: bfe/1.0.8.18

#===================== 测试本机网络下载 =====================#
HTTP/1.1 200 Connection established

HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 78
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: text/plain; charset=utf-8
ETag: W/"0dc2362bc173904737cc6f76ed1f0ffb5b6dba4165b8c48abb46ba2582e63d01"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
Via: 1.1 varnish (Varnish/6.0)
X-GitHub-Request-Id: 9512:48A6:C053:F587:5EBCB2CA
Accept-Ranges: bytes
Date: Thu, 14 May 2020 03:48:48 GMT
Via: 1.1 varnish
X-Served-By: cache-hkg17934-HKG
X-Cache: HIT, HIT
X-Cache-Hits: 1, 1
X-Timer: S1589428128.304558,VS0,VE286
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
X-Fastly-Request-ID: 23f7ca319a31f247195ed25594d4e2489904fbf3
Expires: Thu, 14 May 2020 03:53:48 GMT
Source-Age: 0

#===================== 最近运行日志 =====================#
time="2020-05-14T11:40:19+08:00" level=info msg="Start initial compatible provider 🎯 全球直连"
time="2020-05-14T11:40:19+08:00" level=info msg="Start initial compatible provider ♻️ 自动选择"
time="2020-05-14T11:40:19+08:00" level=info msg="Start initial compatible provider 🚀 节点选择"
time="2020-05-14T11:40:19+08:00" level=info msg="Start initial compatible provider 🐟 漏网之鱼"
time="2020-05-14T11:40:19+08:00" level=info msg="Start initial compatible provider 🛑 全球拦截"
2020-05-14 11:40:15 OpenClash Start Successful
time="2020-05-14T11:40:38+08:00" level=info msg="Start initial compatible provider 🎯 全球直连"
time="2020-05-14T11:40:38+08:00" level=info msg="Start initial compatible provider ♻️ 自动选择"
time="2020-05-14T11:40:38+08:00" level=info msg="Start initial compatible provider 🚀 节点选择"
time="2020-05-14T11:40:38+08:00" level=info msg="Start initial compatible provider 🐟 漏网之鱼"
time="2020-05-14T11:40:38+08:00" level=info msg="Start initial compatible provider 🛑 全球拦截"
2020-05-14 11:40:35 OpenClash Start Successful
time="2020-05-14T11:40:48+08:00" level=info msg="Start initial compatible provider 🎯 全球直连"
time="2020-05-14T11:40:48+08:00" level=info msg="Start initial compatible provider ♻️ 自动选择"
time="2020-05-14T11:40:48+08:00" level=info msg="Start initial compatible provider 🚀 节点选择"
time="2020-05-14T11:40:48+08:00" level=info msg="Start initial compatible provider 🛑 全球拦截"
time="2020-05-14T11:40:48+08:00" level=info msg="Start initial compatible provider 🐟 漏网之鱼"
2020-05-14 11:40:45 OpenClash Start Successful
time="2020-05-14T11:47:18+08:00" level=info msg="Start initial compatible provider 🎯 全球直连"
time="2020-05-14T11:47:18+08:00" level=info msg="Start initial compatible provider ♻️ 自动选择"
time="2020-05-14T11:47:18+08:00" level=info msg="Start initial compatible provider 🚀 节点选择"
time="2020-05-14T11:47:18+08:00" level=info msg="Start initial compatible provider 🛑 全球拦截"
time="2020-05-14T11:47:18+08:00" level=info msg="Start initial compatible provider 🐟 漏网之鱼"
2020-05-14 11:47:15 OpenClash Start Successful
time="2020-05-14T11:47:48+08:00" level=info msg="Start initial compatible provider 🎯 全球直连"
time="2020-05-14T11:47:48+08:00" level=info msg="Start initial compatible provider ♻️ 自动选择"
time="2020-05-14T11:47:48+08:00" level=info msg="Start initial compatible provider 🚀 节点选择"
time="2020-05-14T11:47:48+08:00" level=info msg="Start initial compatible provider 🐟 漏网之鱼"
time="2020-05-14T11:47:48+08:00" level=info msg="Start initial compatible provider 🛑 全球拦截"
2020-05-14 11:47:44 OpenClash Start Successful

**Comment by vernesong** [comment]
![image](https://user-images.githubusercontent.com/42875168/81891279-9dbc6480-95da-11ea-8a65-9f7b4b40749b.png)
清理一下dns缓存

**Comment by otherbanana** [comment]
大佬，我现在的自定义DNS服务器和您图上是一样的，使用ipconfig /flushdns清理了DNS缓存，但是仍然打不开，不知道您方不方便，我这里可以用teamviewer您远程帮我看看

**Comment by otherbanana** [comment]
C:\Users\Administrator>curl -v www.google.com
* Rebuilt URL to: www.google.com/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* connect to 127.0.0.1 port 80 failed: Connection refused
* Failed to connect to www.google.com port 80: Connection refused
* Closing connection 0
curl: (7) Failed to connect to www.google.com port 80: Connection refused

C:\Users\Administrator>curl -v www.youtube.com
* Rebuilt URL to: www.youtube.com/
*   Trying 172.217.160.110...
* TCP_NODELAY set
* Connected to www.youtube.com (172.217.160.110) port 80 (#0)
> GET / HTTP/1.1
> Host: www.youtube.com
> User-Agent: curl/7.55.1
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Content-Type: text/html; charset=utf-8
< Location: https://www.youtube.com/
< Cache-Control: no-cache
< Expires: Tue, 27 Apr 1971 19:44:06 GMT
< X-Content-Type-Options: nosniff
< Content-Length: 0
< P3P: CP="This is not a P3P policy! See http://support.google.com/accounts/answer/151657?hl=en for more info."
< Date: Thu, 14 May 2020 04:39:58 GMT
< Server: YouTube Frontend Proxy
< X-XSS-Protection: 0
< Set-Cookie: VISITOR_INFO1_LIVE=j24YGlzoZLQ; path=/; domain=.youtube.com; expires=Tue, 10-Nov-2020 04:39:58 GMT; httponly; samesite=None
< Set-Cookie: YSC=fqIUbnj_lzg; path=/; domain=.youtube.com; httponly; samesite=None
<
* Connection #0 to host www.youtube.com left intact

**Comment by otherbanana** [comment]
> ![image](https://user-images.githubusercontent.com/42875168/81891279-9dbc6480-95da-11ea-8a65-9f7b4b40749b.png)
> 清理一下dns缓存

大佬你好，我已经清理过DNS缓存了，我使用nslookup命令结果是这样子的：
root@OpenWrt:~# nslookup www.google.com 8.8.8.8
Server:		8.8.8.8
Address:	8.8.8.8#53

Name:      www.google.com
Address 1: 127.0.0.1
*** Can't find www.google.com: No answer
root@OpenWrt:~# nslookup www.google.com
Server:		127.0.0.1
Address:	127.0.0.1#53

Name:      www.google.com
Address 1: 127.0.0.1
*** Can't find www.google.com: No answer

www.google.com就是无法访问，但是类似www.google.com.hk这样的就没有问题
root@OpenWrt:~# nslookup www.google.com.hk
Server:		127.0.0.1
Address:	127.0.0.1#53

Name:      www.google.com.hk
www.google.com.hk	canonical name = www-wide.l.google.com
Name:      www-wide.l.google.com
Address 1: 108.177.125.199
*** Can't find www.google.com.hk: No answer

**Comment by vernesong** [comment]
你路由是不是设置hsots了，如果没有建议用fake-ip,目前的情况时google被污染成127.0.0.1了

**Comment by otherbanana** [comment]
我路由器没有设置hosts。确实，换用了fake-ip模式就可以访问了。那么请问，如果还是要用原来的模式，还有办法解决这个被污染的情况吗？谢谢

**Comment by vernesong** [comment]
nameserver用国内https的
```
223.5.5.5/dns-query
```

**Comment by otherbanana** [comment]
我切换成redir-host模式，并且在namesever那里添加了 https  223.5.5.5/dns-query 
但是测试下来并没有成功
当我切换回fake-ip模式的时候，又出现了意外。www.google.com又上不去了，已经清理过了dns缓存。
显示：
C:\Users\Administrator>nslookup www.google.com.sg
服务器:  OpenWrt.lan
Address:  192.168.0.27

名称:    www.google.com.sg
Address:  198.18.0.20


C:\Users\Administrator>nslookup www.google.com
服务器:  OpenWrt.lan
Address:  192.168.0.27

非权威应答:
名称:    www.google.com
Address:  127.0.0.1

真的是奇了怪了……
下面附上调试日志

OpenClash 调试日志

生成时间: 2020-05-17 01:41:26
插件版本: v0.38.1-beta

#===================== 系统信息 =====================#
主机型号: Phicomm N1
固件版本: OpenWrt SNAPSHOT r2518-b65f1ebf
LuCI版本: git-20.117.60969-420c61a-1
内核版本: 5.6.11-flippy-36+
处理器架构: aarch64_generic

#此项在使用Tun模式时应为ACCEPT
防火墙转发: ACCEPT

#此项有值时建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: 

#此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 127.0.0.1#7874

#===================== 依赖检查 =====================#
dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
jsonfilter: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
iptables-mod-tproxy: 已安装
kmod-tun(TUN模式): 已安装
luci-compat(Luci-19.07): 未安装

#===================== 内核检查 =====================#
运行状态: 运行中
已选择的架构: linux-armv8

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 
Tun内核文件: 不存在
Tun内核运行权限: 否

Game内核版本: 
Game内核文件: 不存在
Game内核运行权限: 否

Dev内核版本: v0.20.0
Dev内核文件: 存在
Dev内核运行权限: 正常

#===================== 插件设置 =====================#
当前配置文件: /etc/openclash/config/1config.yaml
运行模式: fake-ip
默认代理模式: Rule
UDP流量转发: 启用
DNS劫持: 启用
自定义DNS: 启用
IPV6-DNS解析: 停用
禁用Dnsmasq缓存: 启用
自定义规则: 停用
仅允许内网: 停用
仅代理命中规则流量: 停用

#启动异常时建议关闭此项后重试
保留配置: 停用
第三方规则: 停用

#===================== 配置文件 =====================#
port: 7890
socks-port: 7891
allow-lan: true
bind-address: "*"
mode: Rule
log-level: silent
external-controller: 0.0.0.0:9090
redir-port: 7892
secret: "123456"
external-ui: "/usr/share/openclash/dashboard"

dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  listen: 127.0.0.1:7874
  fake-ip-filter:
##Custom fake-ip-filter##
  - '*.lan'
  - 'time.windows.com'
  - 'time.nist.gov'
  - 'time.apple.com'
  - 'time.asia.apple.com'
  - '*.ntp.org.cn'
  - '*.openwrt.pool.ntp.org'
  - 'time1.cloud.tencent.com'
  - 'time.ustc.edu.cn'
  - 'pool.ntp.org'
  - 'ntp.ubuntu.com'
  - 'ntp.aliyun.com'
  - 'ntp1.aliyun.com'
  - 'ntp2.aliyun.com'
  - 'ntp3.aliyun.com'
  - 'ntp4.aliyun.com'
  - 'ntp5.aliyun.com'
  - 'ntp6.aliyun.com'
  - 'ntp7.aliyun.com'
  - 'time1.aliyun.com'
  - 'time2.aliyun.com'
  - 'time3.aliyun.com'
  - 'time4.aliyun.com'
  - 'time5.aliyun.com'
  - 'time6.aliyun.com'
  - 'time7.aliyun.com'
  - '*.time.edu.cn'
  - 'time1.apple.com'
  - 'time2.apple.com'
  - 'time3.apple.com'
  - 'time4.apple.com'
  - 'time5.apple.com'
  - 'time6.apple.com'
  - 'time7.apple.com'
  - 'time1.google.com'
  - 'time2.google.com'
  - 'time3.google.com'
  - 'time4.google.com'
  - 'music.163.com'
  - '*.music.163.com'
  - '*.126.net'
  - 'musicapi.taihe.com'
  - 'music.taihe.com'
  - 'songsearch.kugou.com'
  - 'trackercdn.kugou.com'
  - '*.kuwo.cn'
  - 'api-jooxtt.sanook.com'
  - 'api.joox.com'
  - 'joox.com'
  - 'y.qq.com'
  - '*.y.qq.com'
  - 'streamoc.music.tc.qq.com'
  - 'mobileoc.music.tc.qq.com'
  - 'isure.stream.qqmusic.qq.com'
  - 'dl.stream.qqmusic.qq.com'
  - 'aqqmusic.tc.qq.com'
  - 'amobile.music.tc.qq.com'
  - '*.xiami.com'
  - '*.music.migu.cn'
  - 'music.migu.cn'
  - '*.msftconnecttest.com'
  - '*.msftncsi.com'
  - 'localhost.ptlogin2.qq.com'
  - '*.*.*.srv.nintendo.net'
  - '*.*.stun.playstation.net'
  - 'xbox.*.*.microsoft.com'
##Custom fake-ip-filter END##
##Custom DNS##
  nameserver:
  - 114.114.114.114
  - 119.29.29.29

#===================== 防火墙设置 =====================#

#NAT chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    REDIRECT   tcp  --  0.0.0.0/0            8.8.4.4              redir ports 7892
2    REDIRECT   tcp  --  0.0.0.0/0            8.8.8.8              redir ports 7892
3    CLOUD_MUSIC  tcp  --  0.0.0.0/0            0.0.0.0/0            match-set music dst
4    REDIRECT   udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:53 redir ports 53
5    REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:53 redir ports 53
6    prerouting_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom prerouting rule chain */
7    zone_lan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
8    zone_vpn_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
9    openclash  tcp  --  0.0.0.0/0            0.0.0.0/0           
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         
1    openclash_output  tcp  --  0.0.0.0/0            0.0.0.0/0           

#Mangle chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    openclash  udp  --  0.0.0.0/0            0.0.0.0/0           
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         

#===================== 路由表状态 =====================#
#route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.0.1     0.0.0.0         UG    0      0        0 eth0
192.168.0.0     0.0.0.0         255.255.255.0   U     0      0        0 eth0
#ip route list
default via 192.168.0.1 dev eth0 proto static 
192.168.0.0/24 dev eth0 proto kernel scope link src 192.168.0.27 
#ip rule show
0:	from all lookup local 
32765:	from all fwmark 0x162 lookup 354 
32766:	from all lookup main 
32767:	from all lookup default 

#===================== 端口占用状态 =====================#
tcp        0      0 :::9090                 :::*                    LISTEN      6709/clash
tcp        0      0 :::7890                 :::*                    LISTEN      6709/clash
tcp        0      0 :::7891                 :::*                    LISTEN      6709/clash
tcp        0      0 :::7892                 :::*                    LISTEN      6709/clash
udp        0      0 127.0.0.1:7874          0.0.0.0:*                           6709/clash
udp        0      0 :::7891                 :::*                                6709/clash
udp        0      0 :::7892                 :::*                                6709/clash

#===================== 测试本机DNS查询 =====================#
Server:		127.0.0.1
Address:	127.0.0.1#53

Name:      www.baidu.com
Address 1: 198.18.0.18
*** Can't find www.baidu.com: No answer

#===================== resolv.conf.auto =====================#
# Interface lan
nameserver 192.168.0.1

#===================== 测试本机网络连接 =====================#
HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: private, no-cache, no-store, proxy-revalidate, no-transform
Connection: keep-alive
Content-Length: 277
Content-Type: text/html
Date: Sat, 16 May 2020 17:41:28 GMT
Etag: "575e1f6f-115"
Last-Modified: Mon, 13 Jun 2016 02:50:23 GMT
Pragma: no-cache
Server: bfe/1.0.8.18


#===================== 测试本机网络下载 =====================#
HTTP/1.1 200 Connection established

HTTP/1.1 200 Connection established

HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 78
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: text/plain; charset=utf-8
ETag: W/"0dc2362bc173904737cc6f76ed1f0ffb5b6dba4165b8c48abb46ba2582e63d01"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
Via: 1.1 varnish (Varnish/6.0)
X-GitHub-Request-Id: B270:49D4:315D9:3B467:5EC02068
Accept-Ranges: bytes
Date: Sat, 16 May 2020 17:41:34 GMT
Via: 1.1 varnish
X-Served-By: cache-hkg17923-HKG
X-Cache: HIT, HIT
X-Cache-Hits: 2, 1
X-Timer: S1589650894.018553,VS0,VE0
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
X-Fastly-Request-ID: ee2c0fd459f005c83152630822323e8ae90c3ded
Expires: Sat, 16 May 2020 17:46:34 GMT
Source-Age: 70


#===================== 最近运行日志 =====================#
time="2020-05-17T01:32:46+08:00" level=info msg="Start initial compatible provider 🐟 漏网之鱼"
time="2020-05-17T01:32:46+08:00" level=info msg="Start initial compatible provider 🎯 全球直连"
time="2020-05-17T01:32:46+08:00" level=info msg="Start initial compatible provider ♻️ 自动选择"
time="2020-05-17T01:32:46+08:00" level=info msg="Start initial compatible provider 🚀 节点选择"
time="2020-05-17T01:32:46+08:00" level=info msg="Start initial compatible provider 🛑 全球拦截"
2020-05-17 01:32:42 OpenClash Start Successful
time="2020-05-17T01:39:09+08:00" level=info msg="Start initial compatible provider 🐟 漏网之鱼"
time="2020-05-17T01:39:09+08:00" level=info msg="Start initial compatible provider 🛑 全球拦截"
time="2020-05-17T01:39:09+08:00" level=info msg="Start initial compatible provider 🎯 全球直连"
time="2020-05-17T01:39:09+08:00" level=info msg="Start initial compatible provider ♻️ 自动选择"
time="2020-05-17T01:39:09+08:00" level=info msg="Start initial compatible provider 🚀 节点选择"
2020-05-17 01:39:05 OpenClash Start Successful
time="2020-05-17T01:41:03+08:00" level=info msg="Start initial compatible provider 🐟 漏网之鱼"
time="2020-05-17T01:41:03+08:00" level=info msg="Start initial compatible provider 🛑 全球拦截"
time="2020-05-17T01:41:03+08:00" level=info msg="Start initial compatible provider 🎯 全球直连"
time="2020-05-17T01:41:03+08:00" level=info msg="Start initial compatible provider ♻️ 自动选择"
time="2020-05-17T01:41:03+08:00" level=info msg="Start initial compatible provider 🚀 节点选择"
2020-05-17 01:40:59 OpenClash Start Successful

**Comment by vernesong** [comment]
fake-ip是交给代理解析的，你确保规则内google是走代理的就行

**Comment by otherbanana** [comment]
就是使用fake-ip模式的时候，代理规则上明确www.google.com走代理，但是nslookup下来，不返回198.18开头的ip。重新安装后又正常了，可能是某个地方出了问题。谢谢大佬的解答
