### ISSUE TITLE
微信视频和语音通话无法连接

### ISSUE THREAD

**Issue by oversxxx** [vernesong/OpenClash#442]
只要启动clash的节点，就无法发起微信视频和语音通话，提示“网络异常，聊天结束”。关闭节点，就可以发起。接受别人发来的视频和语音请求没有问题。

**Comment by chenyubogit** [comment]
我也遇到差不多一致的问题、打开软路由的openclash、微信和QQ的语音就拨不出去，一直显示在外呼中。别人发来的视频和音频通话，点击接听、一直显示在连接中···尝试了fakeip+fakeip（增强）/fakeip-tun 都不行
