### ISSUE TITLE
规则外的域名走代理怎样设置才能生效呢

### ISSUE THREAD

**Issue by sillycat3** [vernesong/OpenClash#443]
用订阅自带的规则不行，用第三方规则，只把国内流量设直连也不成功,即便设置全局都走代理也没效
除了下面图片显示，实测也是规则外的域名无法走代理
![微信截图_20200515002218](https://user-images.githubusercontent.com/63470657/81959757-89ac4d80-9642-11ea-9ee2-352f6c19dd58.png)

**Comment by vernesong** [comment]
配置文件规则最后两条就是处理这种情况的
```
- GEOIP,CN,Domestic
- MATCH,Others
```
