### ISSUE TITLE
关闭openclash后对应的防火墙规则是不是应该删掉？

### ISSUE THREAD

**Issue by xuhuanxxx** [vernesong/OpenClash#444]
OpenWrt 版本：OpenWrt SNAPSHOT r13225-bc0288b768，x86-64
OpenClash 版本：0.38, 2524d67dd6a986be26d3557f04e03573a6f1a32b

偶然发现关闭了openclash后网络全部联不通，发现是openclash添加的防火墙规则再其关闭后没有被删除，不知道是不是版本下的特例。

**Comment by xuhuanxxx** [comment]
我看了下，关闭openclash后确实有revert_firewall，但是防火墙状态里的chain openclash、chain openclash_output以及几条redir ports 7892依然还在。

**Comment by vernesong** [comment]
你可以单独尝试命令，提供无法删除的错误信息

**Comment by Hyseen** [comment]
删除`openclash` 和`openclash_output` 链时，提示 `iptables: Too many links.`
此时 `mangle` 表中的 `PREROUTING` 和 `nat` 表中的 `PREROUTING ` `OUTPUT ` 这几条链中还有 `openclash` 和 `openclash_output` 的引用规则，应该要先删除这些规则才能删除这两个自定义链

**Comment by xuhuanxxx** [comment]
除了上面手动执行删除命令的方法，我发现在 系统-启动项 中，点击 openclash 的停止按钮也可以达到删除防火墙规则的目的。这个 issue 也提到了 https://github.com/vernesong/OpenClash/issues/462

**Comment by vernesong** [comment]
> 删除`openclash` 和`openclash_output` 链时，提示 `iptables: Too many links.`
> 此时 `mangle` 表中的 `PREROUTING` 和 `nat` 表中的 `PREROUTING ` `OUTPUT ` 这几条链中还有 `openclash` 和 `openclash_output` 的引用规则，应该要先删除这些规则才能删除这两个自定义链

好

**Comment by xuhuanxxx** [comment]
0.38.4b版本测试了一下，关闭openclash后防火墙规则依然存在，还是需要手动执行一次

> iptables -t mangle -F openclash >/dev/null 2>&1

> iptables -t mangle -X openclash >/dev/null 2>&1

> iptables -t nat -F openclash >/dev/null 2>&1

> iptables -t nat -X openclash >/dev/null 2>&1
执行时没有报错

**Comment by vernesong** [comment]
这几个表没删也不影响使用吧，目前在我的固件上没出现删不掉的情况

**Comment by xuhuanxxx** [comment]
好像确实不是这几个表的问题。

下面是关掉后的防火墙调试信息

#===================== 防火墙设置 =====================#

#NAT chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    REDIRECT   tcp  --  0.0.0.0/0            8.8.4.4              redir ports 7892
2    REDIRECT   tcp  --  0.0.0.0/0            8.8.8.8              redir ports 7892
3    prerouting_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom prerouting rule chain */
4    zone_lan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
5    openclash  tcp  --  0.0.0.0/0            0.0.0.0/0           
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         
1    openclash_output  tcp  --  0.0.0.0/0            0.0.0.0/0           

#Mangle chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    openclash  udp  --  0.0.0.0/0            0.0.0.0/0           
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination

**Comment by vernesong** [comment]
看起来像是for循环的写法问题
