### ISSUE TITLE
OpenClash使用转换的订阅链接 漏网之鱼默认直连

### ISSUE THREAD

**Issue by AlexanderShang** [vernesong/OpenClash#447]
<img width="188" alt="截屏2020-05-16 下午5 01 01" src="https://user-images.githubusercontent.com/35128091/82115692-081a0400-9797-11ea-8fa9-95e7c0d05470.png">
将订阅链接转换后，使用的是ACL4SSR_Online_AdblockPlus，转换出来的将漏网之鱼默认设置成Direct，需要手动调整将其恢复正常，请问是我配置的问题吗

**Comment by vernesong** [comment]
全局设置关闭仅代理命中规则流量

**Comment by AlexanderShang** [comment]
> 全局设置关闭仅代理命中规则流量

谢谢大佬！！
