### ISSUE TITLE
Compatibility of TUN-Core

### ISSUE THREAD

**Issue by 1715173329** [vernesong/OpenClash#448]
Commit 7431e6e now change to new format of config, but the TUN Core still uses the old one, have you tested the compatibility among the different cores?

**Comment by vernesong** [comment]
update from https://github.com/vernesong/OpenClash/releases/tag/TUN-Premium

**Comment by 1715173329** [comment]
Maybe we need update the download url in LuCI and the version in repo :)

**Comment by NV3S** [comment]
> Maybe we need update the download url in LuCI and the version in repo :)

https://github.com/vernesong/OpenClash/commit/b86fbb506e353b235e88bf9c91ea63a7d4560234

**Comment by 1715173329** [comment]
> [b86fbb5](https://github.com/vernesong/OpenClash/commit/b86fbb506e353b235e88bf9c91ea63a7d4560234)

Sorry I've missed this.
