### ISSUE TITLE
启动后外网无法访问黑裙

### ISSUE THREAD

**Issue by breezelol** [vernesong/OpenClash#449]
主机是装的黑裙，然后通过vmm虚拟openwrt做旁路由，开启openwrt后外网无法访问nas（ip、域名都不行），关闭openwrt后就可以访问了，不知道该如何解决？
使用的fake-ip模式，自行替换了frainzy1477的clashrdev内核。

**Comment by vernesong** [comment]
将群辉解析域名的服务器添加到dns高级设置的名单里去

**Comment by vernesong** [comment]
成功后反馈一下添加的域名，我顺便加到默认列表里去

**Comment by breezelol** [comment]
> 将群辉解析域名的服务器添加到dns高级设置的名单里去

我把我的域名（花生壳的免费壳域名）放到高级列表里试了一下，还是无法在打开openclash的情况下进行外网访问。
应该不是域名解析的问题，因为在打开openclash的情况下，可以外网访问ac68u和openwrt，只是群晖无法访问，而且不只是域名+端口无法访问，IP+端口也无法访问。对了，内网可以正常访问，IP、域名都可以。

**Comment by vernesong** [comment]
一个是路由器开upnp，要不然就切换redir模式，用访问控制标签排除群辉流量

**Comment by breezelol** [comment]
redir模式，访问控制黑名单模式添加了群晖IP后，可以正常外网访问了，但是有个新问题就是油管打不开（fake-ip模式下没问题）...
是否可以在fake-ip模式下，在rules里添加一条“- SRC-IP-CIDR,10.0.0.99/32,DIRECT”来实现（99是群晖的内网IP）

**Comment by breezelol** [comment]
redir模式下，不论是否将群晖IP添加到访问控制黑名单，都可以可以正常外网访问，但是有个新问题就是油管非常之慢甚至打不开（fake-ip模式下没问题），改为全局模式，openclash就会自动关闭

**Comment by breezelol** [comment]
redir模式下，将群晖IP添加到访问控制黑名单，可以正常外网访问，但是有个新问题就是油管非常之慢甚至打不开（fake-ip模式下没问题），改为全局模式，openclash就会自动关闭
