### ISSUE TITLE
建议:希望可以修改bind-address和external-controller

### ISSUE THREAD

**Issue by ioxuy** [vernesong/OpenClash#45]
因为路由器上有外网地址,然后又设置了DDNS,不想监听wan,只想监听内部地址给局域网内用,目前是托管的,监听了所有接口

**Comment by vernesong** [comment]
之前绑定路由器地址会有点问题，下个版本将改为只监听路由器的内网IP

**Comment by ZHENGFANNN** [comment]
目前希望可以修改bind-address

场景：
软路由拨号
希望对指定lan口进行转发，而不是全局内网ip

**Comment by ZHENGFANNN** [comment]
> 之前绑定路由器地址会有点问题，下个版本将改为只监听路由器的内网IP

目前希望可以修改bind-address

场景：
软路由拨号
希望对指定lan口进行转发，而不是全局内网ip
