### ISSUE TITLE
自己制作了geoip mmdb数据库，在官方的基础上整合china_ip_list和纯真CN，匹配大陆IP更精确

### ISSUE THREAD

**Issue by alecthw** [vernesong/OpenClash#453]
需要的可以取用哈
项目地址：https://github.com/alecthw/mmdb_china_ip_list
使用action，每周自动拉取新的MaxMind、china_ip_list和纯真CN数据库，并发布一个新的Release版本

**Comment by gozap99** [comment]
上传到在/etc/openclash/以后再更新geoip是不是就会替换掉mmdb数据库

**Comment by gozap99** [comment]
> 上传到在/etc/openclash/以后再更新geoip是不是就会替换掉mmdb数据库



> 需要的可以取用哈
> 项目地址：https://github.com/alecthw/mmdb_china_ip_list
> 使用action，每周自动拉取新的MaxMind、china_ip_list和纯真CN数据库，并发布一个新的Release版本

上传到在/etc/openclash/以后再更新geoip是不是就会替换掉mmdb数据库

**Comment by hcym** [comment]
试试看看，谢谢分享

**Comment by alecthw** [comment]
> > 上传到在/etc/openclash/以后再更新geoip是不是就会替换掉mmdb数据库
> 
> > 需要的可以取用哈
> > 项目地址：https://github.com/alecthw/mmdb_china_ip_list
> > 使用action，每周自动拉取新的MaxMind、china_ip_list和纯真CN数据库，并发布一个新的Release版本
> 
> 上传到在/etc/openclash/以后再更新geoip是不是就会替换掉mmdb数据库

先禁用自动更新吧，回头我在action里传到云上做个固定下载链接，然后把自动更新脚本里的url替换掉就可以保持自动更新了

**Comment by alecthw** [comment]
添加了release分支作为固定下载地址，action每次构建自动push到release分支
version文件：https://raw.githubusercontent.com/alecthw/mmdb_china_ip_list/release/version
mmdb文件： https://raw.githubusercontent.com/alecthw/mmdb_china_ip_list/release/Country.mmdb
可以之间替换/usr/share/openclash/openclash_ipdb.sh中的下载链接达到自动更新的目的

**Comment by kongkongzzz** [comment]
其实我一直有个疑问，绕过大陆IP（就是那个实验性功能）用的大陆IP的列表是哪个呢？和GEOIP中的中国部分是同一个吗，他会自动更新吗

**Comment by Contribuv** [comment]
Geoip 的 城市数据库，错误率90%，完全没有用

**Comment by alecthw** [comment]
mindmax 官方最近的Country.mmdb文件大小扩张到了7M+，对嵌入式设备的使用不友好了。
看clash的源码里只用到了 record.Country.IsoCode，所以额外做了个只包含iso_code和geoname_id的lite版本，大小1.9M，有需要的可以使用lite版本。
https://github.com/alecthw/mmdb_china_ip_list/issues/10
