### ISSUE TITLE
基础带宽100M，多拨5次成功，但是科学上网速度只有100M的

### ISSUE THREAD

**Issue by neuq2004** [vernesong/OpenClash#455]
j1900软路由，多拨成500M，关闭openclash用电脑clash测试科学上网可以跑300M左右，但是用openclash就只能固定在100M，请问又遇到这种问题的吗

**Comment by alecthw** [comment]
所有的连接都是从clash发出的，改一下分流策略，按目的地址+目的端口分流，应该就能好

**Comment by neuq2004** [comment]
> 所有的连接都是从clash发出的，改一下分流策略，按目的地址+目的端口分流，应该就能好

你好，能够说得详细一点吗？是在yaml那个配置文件里面改分流策略吗

**Comment by alecthw** [comment]
> > 所有的连接都是从clash发出的，改一下分流策略，按目的地址+目的端口分流，应该就能好
> 
> 你好，能够说得详细一点吗？是在yaml那个配置文件里面改分流策略吗

多播的负载均衡策略，我上级是ikuai，openwrt的多播不太记得了

**Comment by neuq2004** [comment]
> > > 所有的连接都是从clash发出的，改一下分流策略，按目的地址+目的端口分流，应该就能好
> > 
> > 
> > 你好，能够说得详细一点吗？是在yaml那个配置文件里面改分流策略吗
> 
> 多播的负载均衡策略，我上级是ikuai，openwrt的多播不太记得了
好的，我等下找找看，你的是虚拟机装爱快和lede是吧，不行的话我也打算这么装

**Comment by alecthw** [comment]
> > > > 所有的连接都是从clash发出的，改一下分流策略，按目的地址+目的端口分流，应该就能好
> > > 
> > > 
> > > 你好，能够说得详细一点吗？是在yaml那个配置文件里面改分流策略吗
> > 
> > 
> > 多播的负载均衡策略，我上级是ikuai，openwrt的多播不太记得了
> > 好的，我等下找找看，你的是虚拟机装爱快和lede是吧，不行的话我也打算这么装

我是软路由装ikuai，ikuai里装虚拟机openwrt做旁路，感觉这样挺好的

**Comment by MartialBE** [comment]
Duplicate of #301
