### ISSUE TITLE
openclash 和 zerotier 的冲突

### ISSUE THREAD

**Issue by imxz** [vernesong/OpenClash#457]
openclash 和 zerotier 一起使用的时候会发生冲突。不管是 fake-ip 还是 redir-host 模式，启用 openclash 后，ping zerotier 网络中的另一台机器，相应时间可达近 1000ms，关闭 openclash，响应时间通常都是 10ms 以下。

不知道是 bug，还是配置的问题。

**Comment by WoChen5770** [comment]
建议用用zerotier-cli info 查看一下状态

**Comment by lifetyper** [comment]
检查你自己的配置，我一直都是两个同时用的。

**Comment by imxz** [comment]
> 检查你自己的配置，我一直都是两个同时用的。

感谢你的回复。请问一下你是如何配置的？我测试了几种方式均不可行。。。

**Comment by imxz** [comment]
> zerotier-cli info

root@OpenWrt:~# zerotier-cli info
200 info XXXXX 1.4.6 ONLINE

仅仅有这个提示

**Comment by imxz** [comment]
经过一系列测试修改，又可以成功使用了。没有办法复现是如何实现的，操作过到步骤主要是根据恩山论坛到一个帖子，将lan口的绑定ip进行了更改，然后重启了路由器和电脑，之后突然将可以了。

可是组提这个issue之前已经连续测试过很多次，也并没有成功。

所以只能归纳为莫名其妙好了。

**Comment by zgc** [comment]
我的是单臂旁路由，出现了同样的问题，但是我把lan口的“桥接接口”关掉之后就正常了
![image](https://user-images.githubusercontent.com/4143433/82990054-281ab480-a02e-11ea-856b-50daa31deff6.png)

**Comment by zgc** [comment]
> 我的是单臂旁路由，出现了同样的问题，但是我把lan口的“桥接接口”关掉之后就正常了
> ![image](https://user-images.githubusercontent.com/4143433/82990054-281ab480-a02e-11ea-856b-50daa31deff6.png)

正常了一会，又出问题了

**Comment by kwingart** [comment]
我也有相似问题，
用的是小米AC2100路由器，刷了padavan固件，固件版本:3.4.3.9-099_23-04-1
集成的clash版本是：2023.04.16
zerotier版本是 1.10.6
单开任何一个都没问题，只要两个都开了，就造成CPU占用彪高，86%，持续在这个数字，或之上。
然后平均负载 是在 5-6，或者更高。导致路由器20个小时后，就假死。无法远程管理设备（包括web管理，telnet，ssh），客户端没法上网，但是能ping通。比如能ping baidu.com。

没到假死状态前，用netstat -ant 查看网络连接，非常夸张的数量大概几百条，90%是属于zerotier的这个地址（10.147.20.170）的连接。看起来是自己不断的连自己，如何解决？请高手帮忙。谢谢！

如下：
tcp        0      0 10.147.20.170:27638     10.147.20.170:7892      TIME_WAIT
tcp        0      0 10.147.20.170:19300     10.147.20.170:7892      TIME_WAIT
tcp        0      0 10.147.20.170:27321     10.147.20.170:7892      TIME_WAIT
tcp        0      0 10.147.20.170:19445     10.147.20.170:7892      TIME_WAIT
tcp        0      0 10.147.20.170:27852     10.147.20.170:7892      TIME_WAIT
tcp        0      0 10.147.20.170:27154     10.147.20.170:7892      TIME_WAIT
tcp        0      0 10.147.20.170:19274     10.147.20.170:7892      TIME_WAIT
tcp        0      0 10.147.20.170:19136     10.147.20.170:7892      TIME_WAIT
tcp        0      0 10.147.20.170:27629     10.147.20.170:7892      TIME_WAIT
tcp        0      0 10.147.20.170:27413     10.147.20.170:7892      TIME_WAIT
tcp        0      0 10.147.20.170:27332     10.147.20.170:7892      TIME_WAIT
tcp        0      0 10.147.20.170:27777     10.147.20.170:7892      TIME_WAIT
tcp        0      0 10.147.20.170:19781     10.147.20.170:7892      TIME_WAIT
tcp        0      0 10.147.20.170:19671     10.147.20.170:7892      TIME_WAIT
tcp        0      0 10.147.20.170:20110     10.147.20.170:7892      TIME_WAIT
tcp        0      0 10.147.20.170:27140     10.147.20.170:7892      TIME_WAIT
tcp        0      0 10.147.20.170:27176     10.147.20.170:7892      TIME_WAIT
tcp        0      0 10.147.20.170:19221     10.147.20.170:7892      TIME_WAIT
tcp        0      0 10.147.20.170:27227     10.147.20.170:7892      TIME_WAIT
tcp        0      0 10.147.20.170:19623     10.147.20.170:7892      TIME_WAIT
tcp        0      0 10.147.20.170:19202     10.147.20.170:7892      TIME_WAIT
tcp        0      0 10.147.20.170:28018     10.147.20.170:7892      TIME_WAIT
tcp        0      0 10.147.20.170:27241     10.147.20.170:7892      TIME_WAIT
tcp        0      0 10.147.20.170:19842     10.147.20.170:7892      TIME_WAIT
tcp        0      0 10.147.20.170:27988     10.147.20.170:7892      TIME_WAIT
tcp        0      0 10.147.20.170:27264     10.147.20.170:7892      TIME_WAIT
tcp        0      0 10.147.20.170:19942     10.147.20.170:7892      TIME_WAIT

**Comment by NicholasYZ** [comment]
> 我也有相似问题， 用的是小米AC2100路由器，刷了padavan固件，固件版本:3.4.3.9-099_23-04-1 集成的clash版本是：2023.04.16 zerotier版本是 1.10.6 单开任何一个都没问题，只要两个都开了，就造成CPU占用彪高，86%，持续在这个数字，或之上。 然后平均负载 是在 5-6，或者更高。导致路由器20个小时后，就假死。无法远程管理设备（包括web管理，telnet，ssh），客户端没法上网，但是能ping通。比如能ping baidu.com。
> 
> 没到假死状态前，用netstat -ant 查看网络连接，非常夸张的数量大概几百条，90%是属于zerotier的这个地址（10.147.20.170）的连接。看起来是自己不断的连自己，如何解决？请高手帮忙。谢谢！
> 
> 如下： tcp 0 0 10.147.20.170:27638 10.147.20.170:7892 TIME_WAIT tcp 0 0 10.147.20.170:19300 10.147.20.170:7892 TIME_WAIT tcp 0 0 10.147.20.170:27321 10.147.20.170:7892 TIME_WAIT tcp 0 0 10.147.20.170:19445 10.147.20.170:7892 TIME_WAIT tcp 0 0 10.147.20.170:27852 10.147.20.170:7892 TIME_WAIT tcp 0 0 10.147.20.170:27154 10.147.20.170:7892 TIME_WAIT tcp 0 0 10.147.20.170:19274 10.147.20.170:7892 TIME_WAIT tcp 0 0 10.147.20.170:19136 10.147.20.170:7892 TIME_WAIT tcp 0 0 10.147.20.170:27629 10.147.20.170:7892 TIME_WAIT tcp 0 0 10.147.20.170:27413 10.147.20.170:7892 TIME_WAIT tcp 0 0 10.147.20.170:27332 10.147.20.170:7892 TIME_WAIT tcp 0 0 10.147.20.170:27777 10.147.20.170:7892 TIME_WAIT tcp 0 0 10.147.20.170:19781 10.147.20.170:7892 TIME_WAIT tcp 0 0 10.147.20.170:19671 10.147.20.170:7892 TIME_WAIT tcp 0 0 10.147.20.170:20110 10.147.20.170:7892 TIME_WAIT tcp 0 0 10.147.20.170:27140 10.147.20.170:7892 TIME_WAIT tcp 0 0 10.147.20.170:27176 10.147.20.170:7892 TIME_WAIT tcp 0 0 10.147.20.170:19221 10.147.20.170:7892 TIME_WAIT tcp 0 0 10.147.20.170:27227 10.147.20.170:7892 TIME_WAIT tcp 0 0 10.147.20.170:19623 10.147.20.170:7892 TIME_WAIT tcp 0 0 10.147.20.170:19202 10.147.20.170:7892 TIME_WAIT tcp 0 0 10.147.20.170:28018 10.147.20.170:7892 TIME_WAIT tcp 0 0 10.147.20.170:27241 10.147.20.170:7892 TIME_WAIT tcp 0 0 10.147.20.170:19842 10.147.20.170:7892 TIME_WAIT tcp 0 0 10.147.20.170:27988 10.147.20.170:7892 TIME_WAIT tcp 0 0 10.147.20.170:27264 10.147.20.170:7892 TIME_WAIT tcp 0 0 10.147.20.170:19942 10.147.20.170:7892 TIME_WAIT

可以了解一下广播风暴，可能是你的设置在什么地方做出了网络环路
