### ISSUE TITLE
开启OpenClash之后，Youtube视频无法播放

### ISSUE THREAD

**Issue by frankkly** [vernesong/OpenClash#458]
Youtube是可以正常访问的，但是就是视频打不开，一直转圈圈，但是评论区和右侧的推荐列表又是可以正常加载的

**Comment by vernesong** [comment]
发调试日志

**Comment by sususu98** [comment]
可能是dns解析的问题，如果是旁路由开启openclash，可以尝试更改掉本机的dns服务器（包括ipv6的dns服务器）

**Comment by hcym** [comment]
单口旁路的话要搞好vlan，和普通路由器一模一样，没有任何问题。

**Comment by janus2xss** [comment]
> Youtube是可以正常访问的，但是就是视频打不开，一直转圈圈，但是评论区和右侧的推荐列表又是可以正常加载的

你好，你的这个问题解决了吗？我也遇到同样的问题了

**Comment by iam7cn** [comment]
我的也是，网页版可以打开youtube，手机APP无法打开。

Fake-IP（增强）模式
--
代理模式 rule

**Comment by wjjzzdlzd** [comment]
ss节点的话把 *UDP流量转发 关闭了应该就可以了

**Comment by xilailai37** [comment]
1、关闭openclash dns里面的自定义上游DNS服务器2、在LAN口自定义dns

**Comment by a2368007** [comment]
我也是这个问题

**Comment by hongqixaidedan** [comment]
我也是今天早上突然就这样了，有大佬帮忙知道一下吗

**Comment by loohaCode** [comment]
> 1、关闭openclash dns里面的自定义上游DNS服务器2、在LAN口自定义dns

自定义DNS是关掉的，主路由DNS是223.5.5.5和223.6.6.6，openwrt LAN口定义的设置的DNS也是223.5.5.5和223.6.6.6，用了一天好着没哈问题，第二天就成这样了，大佬又办法吗

**Comment by StrongKang** [comment]
我是把openclash自定义dns地址的谷歌dns 8.8.8.8 端口853删除，tls改成了http，问题是解决了，但是ins的视频无法播放

**Comment by StrongKang** [comment]
把openclash 谷歌的dns fallback改成namesever，tls改成udp，问题解决了

**Comment by luckyqiao** [comment]
@StrongKang 请教一下在哪个地方修改呢

**Comment by StrongKang** [comment]
@luckyqiao 在openclash里面的全局设置，有个dns设置，底下有自定义dns服务器

**Comment by kdyzm** [comment]
我也遇到这个问题了，你们都是咋解决的

**Comment by luckyqiao** [comment]
> 我也遇到这个问题了，你们都是咋解决的

dns解析的问题，我开启了远程dns解析就行了

**Comment by xeasonwang** [comment]
> 

请问远程解析选项在哪里？我的插件里没找到

**Comment by luckyqiao** [comment]
> > 
> 
> 请问远程解析选项在哪里？我的插件里没找到

这里
![image](https://user-images.githubusercontent.com/5688532/176206344-8816ecea-63c7-4e31-a546-07f6bc5e70c1.png)

**Comment by xeasonwang** [comment]
> > > 
> > 
> > 
> > 请问远程解析选项在哪里？我的插件里没找到
> 
> 这里 ![image](https://user-images.githubusercontent.com/5688532/176206344-8816ecea-63c7-4e31-a546-07f6bc5e70c1.png)

谢谢，原来我开了fake-ip就没有这个选项了

**Comment by 2567480258** [comment]
> 把openclash 谷歌的dns fallback改成namesever，tls改成udp，问题解决了

感谢，总算解决了。

**Comment by imkawa** [comment]
你们都解决了吗？目前我是用N1作旁路由
1.只有fake ip模式会出现这种情况。
2.用主路由的WIFI会这样，用旁路由的WIFI马上就好。

**Comment by 2567480258** [comment]
fakeip是因为兼容性问题，换了就ok了

imkawa ***@***.***> 于2023年10月21日周六 20:53写道：

**Comment by piziwh** [comment]
主路由或是网卡 dns 加 8.8.8.8
