### ISSUE TITLE
出现未知错误

### ISSUE THREAD

**Issue by haohaoget** [vernesong/OpenClash#459]
日志如下：
time="2020-05-22T19:05:09+08:00" level=info msg="Start initial compatible provider Auto - UrlTest"
time="2020-05-22T19:05:09+08:00" level=info msg="Start initial compatible provider GlobalTV"
time="2020-05-22T19:05:09+08:00" level=info msg="Start initial compatible provider Others"
time="2020-05-22T19:05:09+08:00" level=info msg="Start initial compatible provider Proxy"
time="2020-05-22T19:05:09+08:00" level=info msg="Start initial compatible provider Apple"
time="2020-05-22T19:05:09+08:00" level=info msg="Start initial compatible provider Netflix"
time="2020-05-22T19:05:09+08:00" level=info msg="Start initial compatible provider AdBlock"
time="2020-05-22T19:05:09+08:00" level=info msg="Start initial compatible provider AsianTV"
time="2020-05-22T19:05:09+08:00" level=info msg="Start initial compatible provider 2Auto - UrlTest"
time="2020-05-22T19:05:09+08:00" level=info msg="Start initial compatible provider Spotify"
time="2020-05-22T19:05:09+08:00" level=info msg="Start initial compatible provider Netease Music"
time="2020-05-22T19:05:09+08:00" level=info msg="Start initial compatible provider Steam"
time="2020-05-22T19:05:09+08:00" level=info msg="Start initial compatible provider Speedtest"
time="2020-05-22T19:05:09+08:00" level=info msg="Start initial compatible provider Domestic"
time="2020-05-22T19:05:09+08:00" level=info msg="Start initial compatible provider PayPal"
time="2020-05-22T19:05:09+08:00" level=info msg="Start initial compatible provider Microsoft"
time="2020-05-22T19:05:09+08:00" level=info msg="Start initial compatible provider Telegram"
time="2020-05-22T19:05:09+08:00" level=info msg="DNS server listening at: 127.0.0.1:7874"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x40e894]

goroutine 548 [running]:
github.com/Dreamacro/clash/tunnel.handleTCPConn(0x81bee0, 0x4000183180)
	/home/vernesong/home/clash-tun/clash/tunnel/tunnel.go:274 +0x1a4
created by github.com/Dreamacro/clash/tunnel.process
	/home/vernesong/home/clash-tun/clash/tunnel/tunnel.go:128 +0xd4
2020-05-22 19:04:57 OpenClash Start Successful, Please Note That Network May Abnormal With IPV6's DHCP Server
2020-05-22 19:05:13 Watchdog: Clash Core Problem, Restart.
time="2020-05-22T19:05:14+08:00" level=info msg="Start initial compatible provider Others"
time="2020-05-22T19:05:14+08:00" level=info msg="Start initial compatible provider Microsoft"
time="2020-05-22T19:05:14+08:00" level=info msg="Start initial compatible provider Netease Music"
time="2020-05-22T19:05:14+08:00" level=info msg="Start initial compatible provider AdBlock"
time="2020-05-22T19:05:14+08:00" level=info msg="Start initial compatible provider Auto - UrlTest"
time="2020-05-22T19:05:14+08:00" level=info msg="Start initial compatible provider GlobalTV"
time="2020-05-22T19:05:14+08:00" level=info msg="Start initial compatible provider 2Auto - UrlTest"
time="2020-05-22T19:05:14+08:00" level=info msg="Start initial compatible provider AsianTV"
time="2020-05-22T19:05:14+08:00" level=info msg="Start initial compatible provider Spotify"
time="2020-05-22T19:05:14+08:00" level=info msg="Start initial compatible provider PayPal"
time="2020-05-22T19:05:14+08:00" level=info msg="Start initial compatible provider Domestic"
time="2020-05-22T19:05:14+08:00" level=info msg="Start initial compatible provider Steam"
time="2020-05-22T19:05:14+08:00" level=info msg="Start initial compatible provider Apple"
time="2020-05-22T19:05:14+08:00" level=info msg="Start initial compatible provider Proxy"
time="2020-05-22T19:05:14+08:00" level=info msg="Start initial compatible provider Netflix"
time="2020-05-22T19:05:14+08:00" level=info msg="Start initial compatible provider Speedtest"
time="2020-05-22T19:05:14+08:00" level=info msg="Start initial compatible provider Telegram"
time="2020-05-22T19:05:14+08:00" level=info msg="DNS server listening at: 127.0.0.1:7874"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x40e894]

goroutine 333 [running]:
github.com/Dreamacro/clash/tunnel.handleTCPConn(0x81bee0, 0x400000cb80)
	/home/vernesong/home/clash-tun/clash/tunnel/tunnel.go:274 +0x1a4
created by github.com/Dreamacro/clash/tunnel.process
	/home/vernesong/home/clash-tun/clash/tunnel/tunnel.go:128 +0xd4

**Comment by 2287405159** [comment]
最新版内核以及版本，n1是36+o，只要已开启就会CPU占用90以上内存几乎也全部占用，
