### ISSUE TITLE
回国规则问题

### ISSUE THREAD

**Issue by kvtong93** [vernesong/OpenClash#46]
回国规则有几个问题，不需要走代理的中国区ip一样走了回国代理，并且，把geoip cn 那条去除以后运行久了，国内很多地址都会走proxy

**Comment by vernesong** [comment]
你看一下配置文件规则，有没有不需要走代理的分到proxy组了，geoip不能去掉，异常的时候把内核日志贴上来

**Comment by tongt15** [comment]
redir-port: 7892
port: 7890
socks-port: 7891
mode: Rule
log-level: silent
external-controller: 0.0.0.0:9090
secret: "123456"
allow-lan: true
bind-address: "*"
external-ui: "/usr/share/openclash/dashboard"
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  listen: 0.0.0.0:7874
  nameserver:
  - 114.114.114.114
  - tls://8.8.8.8:853
#===================== OpenClash-General-Settings =====================#
Proxy:
############隐藏#############
Proxy Group:
- name: Auto - UrlTest
  type: url-test
  proxies:
  - "V2公用亚洲回国专线-国外专用"
  - "V2公用大洋洲回国专线-国外专用"
  - "V2公用北美洲回国专线-国外专用"
  - "V2公用欧洲回国专线-国外专用"
  url: http://www.gstatic.com/generate_204
  interval: "600"
- name: Proxy
  type: select
  proxies:
  - Auto - UrlTest
  - DIRECT
  - "V2公用亚洲回国专线-国外专用"
  - "V2公用大洋洲回国专线-国外专用"
  - "V2公用北美洲回国专线-国外专用"
  - "V2公用欧洲回国专线-国外专用"
- name: Others
  type: select
  proxies:
  - Proxy
  - DIRECT
Rule:
##Custom Rules##
##- DOMAIN-SUFFIX,google.com,Proxy 匹配域名后缀(交由Proxy代理服务器组)
##- DOMAIN-KEYWORD,google,Proxy 匹配域名关键字(交由Proxy代理服务器组)
##- DOMAIN,google.com,Proxy 匹配域名(交由Proxy代理服务器组)
##- DOMAIN-SUFFIX,ad.com,REJECT 匹配域名后缀(拒绝)
##- IP-CIDR,127.0.0.0/8,DIRECT 匹配数据目标IP(直连)
##- SRC-IP-CIDR,192.168.1.201/32,DIRECT 匹配数据发起IP(直连)
##- DST-PORT,80,DIRECT 匹配数据目标端口(直连)
##- SRC-PORT,7777,DIRECT 匹配数据源端口(直连)

##排序在上的规则优先生效,如添加（去除规则前的#号）：
##IP段：192.168.1.2-192.168.1.200 直连
##- SRC-IP-CIDR,192.168.1.2/31,DIRECT
##- SRC-IP-CIDR,192.168.1.4/30,DIRECT
##- SRC-IP-CIDR,192.168.1.8/29,DIRECT
##- SRC-IP-CIDR,192.168.1.16/28,DIRECT
##- SRC-IP-CIDR,192.168.1.32/27,DIRECT
##- SRC-IP-CIDR,192.168.1.64/26,DIRECT
##- SRC-IP-CIDR,192.168.1.128/26,DIRECT
##- SRC-IP-CIDR,192.168.1.192/29,DIRECT
##- SRC-IP-CIDR,192.168.1.200/32,DIRECT

##IP段：192.168.1.202-192.168.1.255 直连
##- SRC-IP-CIDR,192.168.1.202/31,DIRECT
##- SRC-IP-CIDR,192.168.1.204/30,DIRECT
##- SRC-IP-CIDR,192.168.1.208/28,DIRECT
##- SRC-IP-CIDR,192.168.1.224/27,DIRECT

##此时IP为192.168.1.1和192.168.1.201的客户端流量走代理（策略），其余客户端不走代理
##因为Fake-IP模式下，IP地址为192.168.1.1的路由器自身流量可走代理（策略），所以需要排除
##在线IP段转CIDR地址：http://ip2cidr.com
##Custom Rules End##
##Proxy:Proxy
##Others:DIRECT
##source:ConnersHua_return
# (Video)
# AcFun
# USER-AGENT,AcFun*,Proxy
- DOMAIN-SUFFIX,acfun.cn,Proxy
- DOMAIN-SUFFIX,acfun.com,Proxy
- DOMAIN-SUFFIX,aixifan.com,Proxy
# > bilibili
# USER-AGENT,bili-universal,Proxy
# USER-AGENT,Bilibili*,Proxy
- DOMAIN-SUFFIX,acgvideo.com,Proxy
- DOMAIN-SUFFIX,bilibili.com,Proxy
- DOMAIN-SUFFIX,hdslb.com,Proxy
# > HunanTV
# USER-AGENT,MGTV*,Proxy
- DOMAIN-SUFFIX,hitv.com,Proxy
- DOMAIN-SUFFIX,hunantv.com,Proxy
- DOMAIN-SUFFIX,mgtv.com,Proxy
# > Migu
# USER-AGENT,MiguVideo*,Proxy
# USER-AGENT,%E5%92%AA%E5%92%95%E8%A7%86%E9%A2%91,Proxy
- DOMAIN-SUFFIX,cmvideo.cn,Proxy
- DOMAIN-SUFFIX,migu.cn,Proxy
- DOMAIN-SUFFIX,miguvideo.com,Proxy
# > iQiyi
# USER-AGENT,iQiYiPhoneVideo,Proxy
# USER-AGENT,PPStream,Proxy
# USER-AGENT,QIYIVideo,Proxy
# USER-AGENT,QYPlayer,Proxy
- DOMAIN-SUFFIX,iqiyi.com,Proxy
- DOMAIN-SUFFIX,iqiyipic.com,Proxy
- DOMAIN-SUFFIX,qy.net,Proxy
# > Sohu
- DOMAIN-SUFFIX,sohu.com,Proxy
- DOMAIN-SUFFIX,sohu.com.cn,Proxy
- DOMAIN-SUFFIX,itc.cn,Proxy
- DOMAIN-SUFFIX,v-56.com,Proxy
# > Tencent
# USER-AGENT,live4iphone*,Proxy
# USER-AGENT,qqlive4iphone*,Proxy
# USER-AGENT,TencentMidasConnect*,Proxy
- DOMAIN-SUFFIX,video.qq.com,Proxy
# > Youku
# USER-AGENT,Youku*,Proxy
# USER-AGENT,%E4%BC%98%E9%85%B7*,Proxy
#- DOMAIN-SUFFIX,soku.com,Proxy
#- DOMAIN-SUFFIX,youku.com,Proxy
#- DOMAIN-SUFFIX,ykimg.com,Proxy

# (Music)
# > Alibaba
# USER-AGENT,walkman*,Proxy
# USER-AGENT,xiami*,Proxy
- DOMAIN-SUFFIX,xiami.com,Proxy
- DOMAIN-SUFFIX,xiami.net,Proxy
# > Netease
# USER-AGENT,NeteaseMusic*,Proxy
# USER-AGENT,%E7%BD%91%E6%98%93%E4%BA%91%E9%9F%B3%E4%B9%90*,Proxy
- DOMAIN-SUFFIX,music.126.net,Proxy
- DOMAIN-SUFFIX,music.163.com,Proxy
# > Tencent
# USER-AGENT,MOO%E9%9F%B3%E4%B9%90*,Proxy
# USER-AGENT,QQ%E9%9F%B3%E4%B9%90,Proxy
- DOMAIN-SUFFIX,qqmusic.qq.com,Proxy
- DOMAIN-SUFFIX,y.qq.com,Proxy
- DOMAIN,aqqmusic.tc.qq.com,Proxy
# Kugou and Kuwo
- DOMAIN-SUFFIX,kugou.com,Proxy
# USER-AGENT,%E9%85%B7%E6%88%91%E9%9F%B3%E4%B9%90*,Proxy
- DOMAIN-SUFFIX,kuwo.cn,Proxy
- DOMAIN-SUFFIX,koowo.com,Proxy
# > Baidu
# USER-AGENT,baiduyinyue,Proxy
- DOMAIN-SUFFIX,qianqian.com,Proxy

- GEOIP,CN,Proxy

- MATCH,DIRECT

**Comment by tongt15** [comment]
> 你看一下配置文件规则，有没有不需要走代理的分到proxy组了，geoip不能去掉，异常的时候把内核日志贴上来

最后应该是geoip cn proxy

**Comment by tongt15** [comment]
match direct是吗

**Comment by vernesong** [comment]
> match direct是吗

对

**Comment by tongt15** [comment]
> > match direct是吗
> 
> 对

这样有个问题，我玩lol都会走代理，还没直连快，如果我只需要几个网站走流量是不是geoip得删了

**Comment by vernesong** [comment]
嗯
