### ISSUE TITLE
关于yacd面板

### ISSUE THREAD

**Issue by lloyd18** [vernesong/OpenClash#461]
![Snipaste_2020-05-23_10-42-54](https://user-images.githubusercontent.com/10294460/82720013-3725fd80-9ce2-11ea-893c-d085efb295e6.png)

可以优化一下yacd面板的conns页面显示吗，每次查看目标IP都要拖动滚动条到右边。可以看到中间还有较多空白，应该是可以完全一屏显示的。

使用环境，windows10，分辨率 1080p，100%缩放

> 敲错门了兄弟。。。
> 
> 👇正主搁这儿的👇
> [haishanh/yacd](https://github.com/haishanh/yacd)

好的 我这就转到那边去。

**Comment by 1-1-2** [comment]
敲错门了兄弟。。。

👇正主搁这儿的👇
[haishanh/yacd](https://github.com/haishanh/yacd)
