### ISSUE TITLE
0.38.4-beta 版本，仍是没法玩王者荣耀。

### ISSUE THREAD

**Issue by beaxqq** [vernesong/OpenClash#469]
其他网页均正常。需要什么设置吗？ 切换成其他模式redir host模式也不行

**Comment by gozap99** [comment]
试试tun模式

**Comment by yanliang721** [comment]
我也有出现这个问题，王者一直在500ms，无法游戏。尝试切换tun和game内核反而直接影响到正常上网，而且也没解决问题。在常规设置里开启了udp也不管用。需要提供什么信息吗
