### ISSUE TITLE
0.38.4 0.38.3 都出现这个 

### ISSUE THREAD

**Issue by ghost** [vernesong/OpenClash#470]
/usr/lib/lua/luci/dispatcher.lua:381: Failed to execute cbi dispatcher target for entry '/admin/services/openclash/settings'.
The called action terminated with an exception:
/usr/lib/lua/luci/model/cbi/openclash/settings.lua:270: attempt to index global 'file' (a nil value)
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:381: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:95: in function </usr/lib/lua/luci/dispatcher.lua:94>

                                                          ---OpenWrt R20.5.9 / LuCI Master (git-20.117.60969-420c61a)

**Comment by vernesong** [comment]
看看有没有/tmp/proxy_group文件，有内容的话估计是固件某些库的问题

**Comment by WGuifei** [comment]
我瞅瞅

**Comment by WGuifei** [comment]
> 看看有没有/tmp/proxy_group文件，有内容的话估计是固件某些库的问题

我瞅瞅

**Comment by WGuifei** [comment]
> 看看有没有/tmp/proxy_group文件，有内容的话估计是固件某些库的问题

没看到 依赖库也装齐了,OpenWRT放在ESXI里跑的

系统版本:Powered by LuCI openwrt-18.06 branch / OpenWrt R20.5.9

**Comment by vernesong** [comment]
运行
`/usr/share/openclash/yml_groups_name_get.sh`
看下报错

**Comment by FlyingSmoke** [comment]
遇到了同样问题，进行了上面的操作如下：
1、没有/tmp/proxy_group
2、执行/usr/share/openclash/yml_groups_name_get.sh，报错如下：
Error loading shared library libreadline.so.7: No such file or directory (needed by ./yml_groups_name_get.sh)
Error loading shared library libhistory.so.7: No such file or directory (needed by ./yml_groups_name_get.sh)
Error relocating ./yml_groups_name_get.sh: unstifle_history: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_make_bare_keymap: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_bind_key_if_unbound_in_map: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_macro_dumper: symbol not found
Error relocating ./yml_groups_name_get.sh: previous_history: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_vi_end_word: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_parse_and_bind: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_redisplay: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_push_macro_input: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_bind_key_in_map: symbol not found
Error relocating ./yml_groups_name_get.sh: clear_history: symbol not found
Error relocating ./yml_groups_name_get.sh: add_history: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_redraw_prompt_last_line: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_filename_completion_function: symbol not found
Error relocating ./yml_groups_name_get.sh: history_get: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_get_keymap: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_kill_text: symbol not found
Error relocating ./yml_groups_name_get.sh: remove_history: symbol not found
Error relocating ./yml_groups_name_get.sh: history_truncate_file: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_generic_bind: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_read_key: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_tilde_expand: symbol not found
Error relocating ./yml_groups_name_get.sh: read_history: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_add_defun: symbol not found
Error relocating ./yml_groups_name_get.sh: history_expand: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_newline: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_vi_editing_mode: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_get_previous_history: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_forced_update_display: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_read_init_file: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_username_completion_function: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_insert: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_invoking_keyseqs: symbol not found
Error relocating ./yml_groups_name_get.sh: append_history: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_tab_insert: symbol not found
Error relocating ./yml_groups_name_get.sh: free_history_entry: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_unbind_key_in_map: symbol not found
Error relocating ./yml_groups_name_get.sh: readline: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_variable_value: symbol not found
Error relocating ./yml_groups_name_get.sh: history_set_pos: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_unbind_function_in_map: symbol not found
Error relocating ./yml_groups_name_get.sh: read_history_range: symbol not found
Error relocating ./yml_groups_name_get.sh: history_is_stifled: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_menu_complete: symbol not found
Error relocating ./yml_groups_name_get.sh: stifle_history: symbol not found
Error relocating ./yml_groups_name_get.sh: replace_history_entry: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_insert_text: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_get_keymap_by_name: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_set_screen_size: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_vi_bWord: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_get_termcap: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_ding: symbol not found
Error relocating ./yml_groups_name_get.sh: where_history: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_delete_text: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_function_of_keyseq: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_bind_keyseq: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_reset_terminal: symbol not found
Error relocating ./yml_groups_name_get.sh: history_tokenize: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_forward_word: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_yank_last_arg: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_function_dumper: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_variable_bind: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_named_function: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_initialize: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_vi_start_inserting: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_complete: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_complete_internal: symbol not found
Error relocating ./yml_groups_name_get.sh: history_list: symbol not found
Error relocating ./yml_groups_name_get.sh: tilde_expand: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_funmap_names: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_set_keymap: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_variable_dumper: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_bind_keyseq_in_map: symbol not found
Error relocating ./yml_groups_name_get.sh: write_history: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_on_new_line: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_clear_visible_line: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_completion_matches: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_completion_mode: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_add_undo: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_cleanup_after_signal: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_list_funmap_names: symbol not found
Error relocating ./yml_groups_name_get.sh: using_history: symbol not found
Error relocating ./yml_groups_name_get.sh: history_get_time: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_crlf: symbol not found
Error relocating ./yml_groups_name_get.sh: history_length: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_completion_found_quote: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_completion_type: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_point: symbol not found
Error relocating ./yml_groups_name_get.sh: history_lines_written_to_file: symbol not found
Error relocating ./yml_groups_name_get.sh: history_max_entries: symbol not found
Error relocating ./yml_groups_name_get.sh: history_write_timestamps: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_completion_suppress_quote: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_basic_word_break_characters: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_mark: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_directory_rewrite_hook: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_end: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_directory_completion_hook: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_completer_word_break_characters: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_dispatching: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_filename_quoting_desired: symbol not found
Error relocating ./yml_groups_name_get.sh: history_search_delimiter_chars: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_executing_keyseq: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_filename_dequoting_function: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_filename_rewrite_hook: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_filename_stat_hook: symbol not found
Error relocating ./yml_groups_name_get.sh: vi_insertion_keymap: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_prep_term_function: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_menu_completion_entry_function: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_attempted_completion_function: symbol not found
Error relocating ./yml_groups_name_get.sh: history_comment_char: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_filename_completion_desired: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_done: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_completion_append_character: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_sort_completion_matches: symbol not found
Error relocating ./yml_groups_name_get.sh: history_lines_read_from_file: symbol not found
Error relocating ./yml_groups_name_get.sh: emacs_ctlx_keymap: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_deprep_term_function: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_editing_mode: symbol not found
Error relocating ./yml_groups_name_get.sh: tilde_additional_prefixes: symbol not found
Error relocating ./yml_groups_name_get.sh: history_subst_char: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_readline_state: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_attempted_completion_over: symbol not found
Error relocating ./yml_groups_name_get.sh: vi_movement_keymap: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_filename_quote_characters: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_filename_quoting_function: symbol not found
Error relocating ./yml_groups_name_get.sh: history_quotes_inhibit_expansion: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_readline_name: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_line_buffer: symbol not found
Error relocating ./yml_groups_name_get.sh: emacs_meta_keymap: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_char_is_quoted_p: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_completion_entry_function: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_last_func: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_ignore_some_completions_function: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_completion_invoking_key: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_instream: symbol not found
Error relocating ./yml_groups_name_get.sh: tilde_expansion_preexpansion_hook: symbol not found
Error relocating ./yml_groups_name_get.sh: tilde_additional_suffixes: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_completion_suppress_append: symbol not found
Error relocating ./yml_groups_name_get.sh: history_inhibit_expansion_function: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_completer_quote_characters: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_completion_quote_character: symbol not found
Error relocating ./yml_groups_name_get.sh: history_base: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_terminal_name: symbol not found
Error relocating ./yml_groups_name_get.sh: history_expansion_char: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_outstream: symbol not found
Error relocating ./yml_groups_name_get.sh: emacs_standard_keymap: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_startup_hook: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_signal_event_hook: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_special_prefixes: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_explicit_arg: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_num_chars_to_read: symbol not found
Error relocating ./yml_groups_name_get.sh: rl_completion_mark_symlink_dirs: symbol not found

看了一下是缺少libreadline.so.7和libhistory.so.7库文件，在/usr/lib/目录找了一下，找到了libreadline.so.8和libhistory.so.8，初步怀疑是升级到openwrt 19.07导致的库文件升级进而导致库版本不兼容
