### ISSUE TITLE
OpenWRT v19.07.3编译Error 2，但去除OpenClash后却能顺利编译

### ISSUE THREAD

**Issue by phantastar** [vernesong/OpenClash#472]
### 编译环境
VMWare 15 + Ubuntu 20.04服务器版
### 编译目标
OpenWRT v19.07.3 + OpenClash最新版(5月27下午7点github pull下来)+ smartdns release 31
### 其他可能的影响因素
kernel_menuconfig启用了64位内核
### 操作步骤

1. menuconfig选中luci-app-openclash；
2. make V=s
3. Error 2 （图1）
![图1](https://user-images.githubusercontent.com/25948362/83103739-e3ecea00-a0e9-11ea-9800-e7ba14a32cff.png)
---------------------------------------------------------

4. menuconfig取消选中luci-app-openclash；
5. make V=s
6. pass （图2）
![图2](https://user-images.githubusercontent.com/25948362/83103927-47771780-a0ea-11ea-9aca-7a5fe3e0f817.png)
--------------------------------------------------------

7. （不服气）再次选中luci-app-openclash；
8. make -j1 V=s
9. Error 2 （图3）
![图3](https://user-images.githubusercontent.com/25948362/83104103-9cb32900-a0ea-11ea-92be-015a6b13aec7.png)
### 期望实现的结果
menuconfig里选中luci-app-openclash也能编译19.07.3成功.

**Comment by skywalkker** [comment]
我也碰到过。后来发现openclash依赖dnsmasq-full，但openwrt默认会编译dnsmasq，二者有冲突，只能编译一个。在menuconfig里选择编译dnsmasq-full，取消dnsmasq，就OK了。

**Comment by phantastar** [comment]
> 我也碰到过。后来发现openclash依赖dnsmasq-full，但openwrt默认会编译dnsmasq，二者有冲突，只能编译一个。在menuconfig里选择编译dnsmasq-full，取消dnsmasq，就OK了。

我等下到那台编译电脑上试一下, 谢谢您了👍
