### ISSUE TITLE
关闭插件后无法上网

### ISSUE THREAD

**Issue by javierzhang0504** [vernesong/OpenClash#474]
每次关闭openclash之后都无法上网，需要重启路由器才可以恢复。
不知道是不是dns的事儿，该怎么设置才可以正常关闭插件，不影响网络呢？

**Comment by vernesong** [comment]
发调试日志上来

**Comment by javierzhang0504** [comment]
以下是开一次插件，再关闭插件，无法上网状态的调试日志：
OpenClash 调试日志

生成时间: 2020-05-31 16:22:17
插件版本: v0.38.4-beta

#===================== 系统信息 =====================#
主机型号: Xiaomi Mi Router 3 Pro
固件版本: OpenWrt 19.07.3 r11063-85e04e9f46
LuCI版本: git-20.146.54255-39d5f2e-1
内核版本: 4.14.180
处理器架构: mipsel_24kc

#此项在使用Tun模式时应为ACCEPT
防火墙转发: ACCEPT

#此项有值时建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: server

#此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 

#===================== 依赖检查 =====================#
dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
jsonfilter: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
iptables-mod-tproxy: 已安装
kmod-tun(TUN模式): 已安装
luci-compat(Luci-19.07): 已安装

#===================== 内核检查 =====================#
运行状态: 未运行
已选择的架构: linux-mipsle-softfloat

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 2020.05.08
Tun内核文件: 存在
Tun内核运行权限: 正常

Game内核版本: 20200510
Game内核文件: 存在
Game内核运行权限: 正常

Dev内核版本: premium-3-g5073c3c
Dev内核文件: 存在
Dev内核运行权限: 正常

#===================== 插件设置 =====================#
当前配置文件: /etc/openclash/config/喵帕斯.yaml
运行模式: redir-host
默认代理模式: Rule
UDP流量转发: 停用
DNS劫持: 启用
自定义DNS: 停用
IPV6-DNS解析: 停用
禁用Dnsmasq缓存: 启用
自定义规则: 停用
仅允许内网: 停用
仅代理命中规则流量: 停用

#启动异常时建议关闭此项后重试
保留配置: 停用
第三方规则: 停用

#===================== 配置文件 =====================#
#---------------------------------------------------#
## 最后更新时间：2020-05-21 10:10:04
#---------------------------------------------------#

# HTTP 代理端口
port: 7890

# SOCKS5 代理端口
socks-port: 7891

# Linux 和 macOS 的 redir 代理端口
redir-port: 7892

# 允许局域网的连接
allow-lan: true
bind-address: "*"

# 规则模式：Rule（规则） / Global（全局代理）/ Direct（全局直连）
mode: Rule

# 设置日志输出级别 (默认级别：silent，即不输出任何内容，以避免因日志内容过大而导致程序内存溢出）。
# 5 个级别：silent / info / warning / error / debug。级别越高日志输出量越大，越倾向于调试，若需要请自行开启。
log-level: silent

# Clash 的 RESTful API
external-controller: 0.0.0.0:9090

# RESTful API 的口令
secret: "123456"

# 您可以将静态网页资源（如 clash-dashboard）放置在一个目录中，clash 将会服务于 `RESTful API/ui`
# 参数应填写配置目录的相对路径或绝对路径。
# external-ui: folder

external-ui: "/usr/share/openclash/dashboard"
hosts:
##Custom HOSTS##
#  experimental hosts, support wildcard (e.g. *.clash.dev Even *.foo.*.example.com)
#  static domain has a higher priority than wildcard domain (foo.example.com > *.example.com)
#  NOTE: hosts don't work with `fake-ip`

#  '*.clash.dev': 127.0.0.1
#  'alpha.clash.dev': '::1'
##Custom HOSTS END##
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 127.0.0.1:7874
  fake-ip-filter:
  nameserver:
  - 114.114.114.114
  fallback:
  - tls://8.8.8.8:853
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4

#===================== 防火墙设置 =====================#

#NAT chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    REDIRECT   tcp  --  0.0.0.0/0            8.8.4.4              redir ports 7892
2    REDIRECT   tcp  --  0.0.0.0/0            8.8.8.8              redir ports 7892
3    prerouting_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom prerouting rule chain */
4    zone_lan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
5    zone_wan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
6    openclash  tcp  --  0.0.0.0/0            0.0.0.0/0           
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         

#Mangle chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         

#===================== 路由表状态 =====================#
#route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.1.1     0.0.0.0         UG    0      0        0 eth0.2
192.168.1.0     0.0.0.0         255.255.255.0   U     0      0        0 eth0.2
192.168.2.0     0.0.0.0         255.255.255.0   U     0      0        0 br-lan
#ip route list
default via 192.168.1.1 dev eth0.2 proto static src 192.168.1.31 
192.168.1.0/24 dev eth0.2 proto kernel scope link src 192.168.1.31 
192.168.2.0/24 dev br-lan proto kernel scope link src 192.168.2.1 
#ip rule show
0:	from all lookup local 
32766:	from all lookup main 
32767:	from all lookup default 

#===================== 端口占用状态 =====================#

#===================== 测试本机DNS查询 =====================#
Server:		127.0.0.1
Address:	127.0.0.1#53

Name:      www.baidu.com
www.baidu.com	canonical name = www.a.shifen.com
Name:      www.a.shifen.com
Address 1: 61.135.169.125
Address 2: 61.135.169.121
www.baidu.com	canonical name = www.a.shifen.com
Address 3: 2408:80f0:410c:1d:0:ff:b07a:39af
Address 4: 2408:80f0:410c:1c:0:ff:b00e:347f

#===================== resolv.conf.auto =====================#
# Interface wan
nameserver 192.168.1.1
# Interface wan6
nameserver fe80::1%eth0.2

#===================== 测试本机网络连接 =====================#
HTTP/1.1 200 OK
Bdpagetype: 1
Bdqid: 0x90b16a0e000038dc
Cache-Control: private
Connection: keep-alive
Content-Type: text/html;charset=utf-8
Date: Sun, 31 May 2020 08:22:21 GMT
Expires: Sun, 31 May 2020 08:21:54 GMT
Server: BWS/1.1
Set-Cookie: BIDUPSID=cb0af4dcd342f5ea6a86c6c2032dadbf; expires=Thu, 31-Dec-37 23:55:55 GMT; max-age=2147483647; path=/; domain=.baidu.com
Set-Cookie: PSTM=1590913341; expires=Thu, 31-Dec-37 23:55:55 GMT; max-age=2147483647; path=/; domain=.baidu.com
Set-Cookie: BDSVRTM=0; path=/
Set-Cookie: BD_HOME=1; path=/
Set-Cookie: H_PS_PSSID=31624_1425_31670_21082_31111_31253_31593_30825_31464_31715_30823; path=/; domain=.baidu.com
Set-Cookie: BAIDUID=cb0af4dcd342f5ea6a86c6c2032dadbf:FG=1; Path=/; Domain=baidu.com; Max-Age=31536000
Traceid: 1590913341189478273010426231220701509852
Vary: Accept-Encoding
Vary: Accept-Encoding
X-Ua-Compatible: IE=Edge,chrome=1


#===================== 测试本机网络下载 =====================#

#===================== 最近运行日志 =====================#

**Comment by javierzhang0504** [comment]
这个是正常打开插件的调试日志：
OpenClash 调试日志

生成时间: 2020-05-31 16:27:04
插件版本: v0.38.4-beta

#===================== 系统信息 =====================#
主机型号: Xiaomi Mi Router 3 Pro
固件版本: OpenWrt 19.07.3 r11063-85e04e9f46
LuCI版本: git-20.146.54255-39d5f2e-1
内核版本: 4.14.180
处理器架构: mipsel_24kc

#此项在使用Tun模式时应为ACCEPT
防火墙转发: ACCEPT

#此项有值时建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: server

#此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 127.0.0.1#7874

#===================== 依赖检查 =====================#
dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
jsonfilter: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
iptables-mod-tproxy: 已安装
kmod-tun(TUN模式): 已安装
luci-compat(Luci-19.07): 已安装

#===================== 内核检查 =====================#
运行状态: 运行中
已选择的架构: linux-mipsle-softfloat

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 2020.05.08
Tun内核文件: 存在
Tun内核运行权限: 正常

Game内核版本: 20200510
Game内核文件: 存在
Game内核运行权限: 正常

Dev内核版本: premium-3-g5073c3c
Dev内核文件: 存在
Dev内核运行权限: 正常

#===================== 插件设置 =====================#
当前配置文件: /etc/openclash/config/喵帕斯.yaml
运行模式: redir-host
默认代理模式: Rule
UDP流量转发: 停用
DNS劫持: 启用
自定义DNS: 停用
IPV6-DNS解析: 停用
禁用Dnsmasq缓存: 启用
自定义规则: 停用
仅允许内网: 停用
仅代理命中规则流量: 停用

#启动异常时建议关闭此项后重试
保留配置: 停用
第三方规则: 停用

#===================== 配置文件 =====================#
#---------------------------------------------------#
## 最后更新时间：2020-05-21 10:10:04
#---------------------------------------------------#

# HTTP 代理端口
port: 7890

# SOCKS5 代理端口
socks-port: 7891

# Linux 和 macOS 的 redir 代理端口
redir-port: 7892

# 允许局域网的连接
allow-lan: true
bind-address: "*"

# 规则模式：Rule（规则） / Global（全局代理）/ Direct（全局直连）
mode: Rule

# 设置日志输出级别 (默认级别：silent，即不输出任何内容，以避免因日志内容过大而导致程序内存溢出）。
# 5 个级别：silent / info / warning / error / debug。级别越高日志输出量越大，越倾向于调试，若需要请自行开启。
log-level: silent

# Clash 的 RESTful API
external-controller: 0.0.0.0:9090

# RESTful API 的口令
secret: "123456"

# 您可以将静态网页资源（如 clash-dashboard）放置在一个目录中，clash 将会服务于 `RESTful API/ui`
# 参数应填写配置目录的相对路径或绝对路径。
# external-ui: folder

external-ui: "/usr/share/openclash/dashboard"
hosts:
##Custom HOSTS##
#  experimental hosts, support wildcard (e.g. *.clash.dev Even *.foo.*.example.com)
#  static domain has a higher priority than wildcard domain (foo.example.com > *.example.com)
#  NOTE: hosts don't work with `fake-ip`

#  '*.clash.dev': 127.0.0.1
#  'alpha.clash.dev': '::1'
##Custom HOSTS END##
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 127.0.0.1:7874
  fake-ip-filter:
  nameserver:
  - 114.114.114.114
  fallback:
  - tls://8.8.8.8:853
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4

#===================== 防火墙设置 =====================#

#NAT chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    REDIRECT   tcp  --  0.0.0.0/0            8.8.4.4              redir ports 7892
2    REDIRECT   tcp  --  0.0.0.0/0            8.8.8.8              redir ports 7892
3    REDIRECT   tcp  --  0.0.0.0/0            8.8.4.4              redir ports 7892
4    REDIRECT   tcp  --  0.0.0.0/0            8.8.8.8              redir ports 7892
5    prerouting_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom prerouting rule chain */
6    zone_lan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
7    zone_wan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
8    openclash  tcp  --  0.0.0.0/0            0.0.0.0/0           
9    openclash  tcp  --  0.0.0.0/0            0.0.0.0/0           
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         

#Mangle chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         

#===================== 路由表状态 =====================#
#route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.1.1     0.0.0.0         UG    0      0        0 eth0.2
192.168.1.0     0.0.0.0         255.255.255.0   U     0      0        0 eth0.2
192.168.2.0     0.0.0.0         255.255.255.0   U     0      0        0 br-lan
#ip route list
default via 192.168.1.1 dev eth0.2 proto static src 192.168.1.31 
192.168.1.0/24 dev eth0.2 proto kernel scope link src 192.168.1.31 
192.168.2.0/24 dev br-lan proto kernel scope link src 192.168.2.1 
#ip rule show
0:	from all lookup local 
32766:	from all lookup main 
32767:	from all lookup default 

#===================== 端口占用状态 =====================#
tcp        0      0 :::7891                 :::*                    LISTEN      18267/clash
tcp        0      0 :::7892                 :::*                    LISTEN      18267/clash
tcp        0      0 :::9090                 :::*                    LISTEN      18267/clash
tcp        0      0 :::7890                 :::*                    LISTEN      18267/clash
udp        0      0 127.0.0.1:7874          0.0.0.0:*                           18267/clash
udp        0      0 :::7891                 :::*                                18267/clash
udp        0      0 :::7892                 :::*                                18267/clash

#===================== 测试本机DNS查询 =====================#
Server:		127.0.0.1
Address:	127.0.0.1#53

Name:      www.baidu.com
www.baidu.com	canonical name = www.a.shifen.com
Name:      www.a.shifen.com
Address 1: 61.135.169.125
Address 2: 61.135.169.121
www.baidu.com	canonical name = www.a.shifen.com
Address 3: 2408:80f0:410c:1c:0:ff:b00e:347f
Address 4: 2408:80f0:410c:1d:0:ff:b07a:39af

#===================== resolv.conf.auto =====================#
# Interface wan
nameserver 192.168.1.1
# Interface wan6
nameserver fe80::1%eth0.2

#===================== 测试本机网络连接 =====================#
HTTP/1.1 200 OK
Bdpagetype: 1
Bdqid: 0xbdbe3c8f00020332
Cache-Control: private
Connection: keep-alive
Content-Type: text/html;charset=utf-8
Date: Sun, 31 May 2020 08:27:09 GMT
Expires: Sun, 31 May 2020 08:27:09 GMT
Server: BWS/1.1
Set-Cookie: BIDUPSID=00064a10a02c368c71aacd1af2a137ab; expires=Thu, 31-Dec-37 23:55:55 GMT; max-age=2147483647; path=/; domain=.baidu.com
Set-Cookie: PSTM=1590913629; expires=Thu, 31-Dec-37 23:55:55 GMT; max-age=2147483647; path=/; domain=.baidu.com
Set-Cookie: BDSVRTM=9; path=/
Set-Cookie: BD_HOME=1; path=/
Set-Cookie: H_PS_PSSID=31357_1467_31670_21113_31110_31606_31673_31463_31321_30823; path=/; domain=.baidu.com
Set-Cookie: BAIDUID=00064a10a02c368c71aacd1af2a137ab:FG=1; Path=/; Domain=baidu.com; Max-Age=31536000
Traceid: 1590913629041445633013672432103621526322
Vary: Accept-Encoding
Vary: Accept-Encoding
X-Ua-Compatible: IE=Edge,chrome=1


#===================== 测试本机网络下载 =====================#
HTTP/1.1 200 Connection established

HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 78
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: text/plain; charset=utf-8
ETag: W/"d9dab6125ff65b18063159457bf671d83244d0cbf0b16951f3c02f8d3ee8c61b"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
Via: 1.1 varnish (Varnish/6.0)
X-GitHub-Request-Id: 81EC:05DB:40012:536EB:5ED34FA3
Accept-Ranges: bytes
Date: Sun, 31 May 2020 08:27:09 GMT
Via: 1.1 varnish
X-Served-By: cache-hkg17926-HKG
X-Cache: HFM, HIT
X-Cache-Hits: 0, 1
X-Timer: S1590913630.891107,VS0,VE1
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
X-Fastly-Request-ID: 791b1a28999d8c3c92c52c89aa7057c4de4594a8
Expires: Sun, 31 May 2020 08:32:09 GMT
Source-Age: 73


#===================== 最近运行日志 =====================#
2020-05-31 16:26:37 OpenClash Reload After Firewall Restart
time="2020-05-31T08:26:48Z" level=info msg="Start initial compatible provider China_media"
time="2020-05-31T08:26:48Z" level=info msg="Start initial compatible provider Global_media"
time="2020-05-31T08:26:48Z" level=info msg="Start initial compatible provider Proxy"
time="2020-05-31T08:26:48Z" level=info msg="Start initial compatible provider Domestic"
time="2020-05-31T08:26:48Z" level=info msg="Start initial compatible provider Others"
2020-05-31 16:26:36 OpenClash Start Successful, Please Note That Network May Abnormal With IPV6's DHCP Server
2020-05-31 16:26:52 Watchdog: Reset Firewall For Enabling Redirect.

**Comment by xuhuanxxx** [comment]
b80734b1254119525b968bd440bdd6b34a33582f , 实测已修复

**Comment by jindx0713** [comment]
目前是0.38.4，还是会出现关闭之后无法上网的问题。

**Comment by javierzhang0504** [comment]
内核和插件都升级到了最新，还是这样啊。

**Comment by javierzhang0504** [comment]
> b80734b1254119525b968bd440bdd6b34a33582f , 实测已修复

该怎么操作呢？小白一只，需要手动修改哪个文件吗？

**Comment by vernesong** [comment]
> > b80734b1254119525b968bd440bdd6b34a33582f , 实测已修复
> 
> 该怎么操作呢？小白一只，需要手动修改哪个文件吗？

发下无法上网时的调试日志

**Comment by javierzhang0504** [comment]
> > > [b80734b](https://github.com/vernesong/OpenClash/commit/b80734b1254119525b968bd440bdd6b34a33582f) , 实测已修复
> > 
> > 
> > 该怎么操作呢？小白一只，需要手动修改哪个文件吗？
> 
> 发下无法上网时的调试日志

我在楼上发过2日志，第一个就是无法上网时的调试日志。

**Comment by vernesong** [comment]
> > > > [b80734b](https://github.com/vernesong/OpenClash/commit/b80734b1254119525b968bd440bdd6b34a33582f) , 实测已修复
> 
> > > 
> 
> > > 
> 
> > > 该怎么操作呢？小白一只，需要手动修改哪个文件吗？
> 
> > 
> 
> > 发下无法上网时的调试日志
> 
> 
> 
> 我在楼上发过2日志，第一个就是无法上网时的调试日志。

更新了还这样？不应该啊

**Comment by javierzhang0504** [comment]
> > > > > [b80734b](https://github.com/vernesong/OpenClash/commit/b80734b1254119525b968bd440bdd6b34a33582f) , 实测已修复
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 该怎么操作呢？小白一只，需要手动修改哪个文件吗？
> > 
> > 
> > > 
> > 
> > 
> > > 发下无法上网时的调试日志
> > 
> > 
> > 我在楼上发过2日志，第一个就是无法上网时的调试日志。
> 
> 更新了还这样？不应该啊

附上最新版本的调试日志：

OpenClash 调试日志

生成时间: 2020-06-03 20:46:05
插件版本: v0.38.6-beta

#===================== 系统信息 =====================#
主机型号: Xiaomi Mi Router 3 Pro
固件版本: OpenWrt 19.07.3 r11063-85e04e9f46
LuCI版本: git-20.150.62258-217d331-1
内核版本: 4.14.180
处理器架构: mipsel_24kc

#此项在使用Tun模式时应为ACCEPT
防火墙转发: ACCEPT

#此项有值时建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: server

#此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 

#===================== 依赖检查 =====================#
dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
jsonfilter: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
iptables-mod-tproxy: 已安装
kmod-tun(TUN模式): 已安装
luci-compat(Luci-19.07): 已安装

#===================== 内核检查 =====================#
运行状态: 未运行
已选择的架构: linux-mipsle-softfloat

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 2020.05.08
Tun内核文件: 存在
Tun内核运行权限: 正常

Game内核版本: v0.17.0-117-gafdab3a
Game内核文件: 存在
Game内核运行权限: 正常

Dev内核版本: premium-10-gfb0289b
Dev内核文件: 存在
Dev内核运行权限: 正常

#===================== 插件设置 =====================#
当前配置文件: /etc/openclash/config/喵帕斯.yaml
运行模式: redir-host
默认代理模式: Rule
UDP流量转发: 停用
DNS劫持: 启用
自定义DNS: 停用
IPV6-DNS解析: 停用
禁用Dnsmasq缓存: 启用
自定义规则: 停用
仅允许内网: 停用
仅代理命中规则流量: 停用

#启动异常时建议关闭此项后重试
保留配置: 停用
第三方规则: 停用

#===================== 配置文件 =====================#
#---------------------------------------------------#
## 最后更新时间：2020-05-21 10:10:04
#---------------------------------------------------#

# HTTP 代理端口
port: 7890

# SOCKS5 代理端口
socks-port: 7891

# Linux 和 macOS 的 redir 代理端口
redir-port: 7892

# 允许局域网的连接
allow-lan: true
bind-address: "*"

# 规则模式：Rule（规则） / Global（全局代理）/ Direct（全局直连）
mode: Rule

# 设置日志输出级别 (默认级别：silent，即不输出任何内容，以避免因日志内容过大而导致程序内存溢出）。
# 5 个级别：silent / info / warning / error / debug。级别越高日志输出量越大，越倾向于调试，若需要请自行开启。
log-level: silent

# Clash 的 RESTful API
external-controller: 0.0.0.0:9090

# RESTful API 的口令
secret: "123456"

# 您可以将静态网页资源（如 clash-dashboard）放置在一个目录中，clash 将会服务于 `RESTful API/ui`
# 参数应填写配置目录的相对路径或绝对路径。
# external-ui: folder

external-ui: "/usr/share/openclash/dashboard"
hosts:
##Custom HOSTS##
#  experimental hosts, support wildcard (e.g. *.clash.dev Even *.foo.*.example.com)
#  static domain has a higher priority than wildcard domain (foo.example.com > *.example.com)
#  NOTE: hosts don't work with `fake-ip`

#  '*.clash.dev': 127.0.0.1
#  'alpha.clash.dev': '::1'
##Custom HOSTS END##
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 127.0.0.1:7874
  fake-ip-filter:
  nameserver:
  - 114.114.114.114
  fallback:
  - tls://8.8.8.8:853
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4

#===================== 防火墙设置 =====================#

#NAT chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    REDIRECT   tcp  --  0.0.0.0/0            8.8.4.4              redir ports 7892
2    REDIRECT   tcp  --  0.0.0.0/0            8.8.8.8              redir ports 7892
3    prerouting_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom prerouting rule chain */
4    zone_lan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
5    zone_wan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
6    openclash  tcp  --  0.0.0.0/0            0.0.0.0/0           
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         

#Mangle chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         

#===================== 路由表状态 =====================#
#route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.1.1     0.0.0.0         UG    0      0        0 eth0.2
192.168.1.0     0.0.0.0         255.255.255.0   U     0      0        0 eth0.2
192.168.2.0     0.0.0.0         255.255.255.0   U     0      0        0 br-lan
#ip route list
default via 192.168.1.1 dev eth0.2 proto static src 192.168.1.31 
192.168.1.0/24 dev eth0.2 proto kernel scope link src 192.168.1.31 
192.168.2.0/24 dev br-lan proto kernel scope link src 192.168.2.1 
#ip rule show
0:	from all lookup local 
32766:	from all lookup main 
32767:	from all lookup default 

#===================== 端口占用状态 =====================#

#===================== 测试本机DNS查询 =====================#
Server:		127.0.0.1
Address:	127.0.0.1#53

Name:      www.baidu.com
www.baidu.com	canonical name = www.a.shifen.com
Name:      www.a.shifen.com
Address 1: 61.135.169.125
Address 2: 61.135.169.121
www.baidu.com	canonical name = www.a.shifen.com
Address 3: 2408:80f0:410c:1d:0:ff:b07a:39af
Address 4: 2408:80f0:410c:1c:0:ff:b00e:347f

#===================== resolv.conf.auto =====================#
# Interface wan
nameserver 192.168.1.1
# Interface wan6
nameserver fe80::1%eth0.2

#===================== 测试本机网络连接 =====================#
HTTP/1.1 200 OK
Bdpagetype: 1
Bdqid: 0x85e644a4000170a7
Cache-Control: private
Connection: keep-alive
Content-Type: text/html;charset=utf-8
Date: Wed, 03 Jun 2020 12:46:09 GMT
Expires: Wed, 03 Jun 2020 12:45:13 GMT
Server: BWS/1.1
Set-Cookie: BIDUPSID=c198ce09cdc43579268949ae7ca6b96c; expires=Thu, 31-Dec-37 23:55:55 GMT; max-age=2147483647; path=/; domain=.baidu.com
Set-Cookie: PSTM=1591188369; expires=Thu, 31-Dec-37 23:55:55 GMT; max-age=2147483647; path=/; domain=.baidu.com
Set-Cookie: BDSVRTM=0; path=/
Set-Cookie: BD_HOME=1; path=/
Set-Cookie: H_PS_PSSID=1425_31325_21107_31069_31764_31715_30824_31844_26350_22157; path=/; domain=.baidu.com
Set-Cookie: BAIDUID=c198ce09cdc43579268949ae7ca6b96c:FG=1; Path=/; Domain=baidu.com; Max-Age=31536000
Traceid: 159118836907066150509648474722853286055
Vary: Accept-Encoding
Vary: Accept-Encoding
X-Ua-Compatible: IE=Edge,chrome=1


#===================== 测试本机网络下载 =====================#

#===================== 最近运行日志 =====================#

**Comment by javierzhang0504** [comment]
卸载插件，重启路由器，重装插件后，依然如此。

**Comment by Chris821C** [comment]
问题解决了吗？？我现在不知道怎么也成这样了，而且重启都没用，现在都不能关插件

**Comment by flaming** [comment]
> 问题解决了吗？？我现在不知道怎么也成这样了，而且重启都没用，现在都不能关插件

同样的情况，最新版，关闭openclash以后，就无法上网了

**Comment by kb5706** [comment]
我也出现了这个状况

**Comment by rzrcazk** [comment]
我也是这个情况

**Comment by Ailee1988** [comment]
一样的状况 关闭了以后在网络选项里的Turbo ACC 网络加速设置 再保存&应用一下就可以上网了

**Comment by UchihaYuki** [comment]
我也是，这个问题有新进展了吗？

**Comment by justethan** [comment]
防火墙添加这一条可以解决
iptables -t nat -I POSTROUTING -o eth3 -j MASQUERADE

eth3是我的wan口,你们自己更改成自己的wan口
