### ISSUE TITLE
日志中出现大量从openwrt路由器发出的数据包，使用随机端口，导致too many open files，然后网络卡顿或者失败

### ISSUE THREAD

**Issue by crotoc** [vernesong/OpenClash#475]
非常感谢你的软件。我家里的配置是这样的：两台路由器，att的路由和openwrt路由。att的路由接光纤获得外部地址，局域网地址是192.168.1.254，然后通过局域网端口分配给我的openwrt路由器192.168.1.153，然后我的openwrt路由器局域网使用192.168.251.1，dhcp给我家里的所有设备。我在openwrt路由器上安装openclash，fake-ip模式，用一会就会出现非常密集快速的请求，导致网络失败或者卡顿：
![image](https://user-images.githubusercontent.com/12446554/83221748-3eaf3180-a13c-11ea-856b-6622d4d737f8.png)
图中请求的地址是192.168.1.153，应该是路由器本身，指向的地址由于是fake-ip，所以不是很清楚。我想可能是哪里出现了回环，希望能帮忙debug一下，非常感谢！

**Comment by vernesong** [comment]
这是旧版本的故障，你插件更新了没有？

**Comment by crotoc** [comment]
谢谢提醒，我赶紧升级了新的版本，目前看日志里面没有了，可能好了，先跑一段时间看一下。请问下这个是什么问题是怎么在新版本里面解决的？想学习一下，谢谢！

**Comment by vernesong** [comment]
这是回环，fake模式会自动在规则最后加一句reject

**Comment by crotoc** [comment]
刚刚又出现了，怎么能debug出来那个回环出了问题？谢谢！

**Comment by crotoc** [comment]
![image](https://user-images.githubusercontent.com/12446554/83280591-85347880-a19c-11ea-9d06-d9ffec913419.png)

**Comment by crotoc** [comment]
用fakeip模式也不知道我的openwrt路由器尝试连接那个地址，所以也不知道那个链出了问题。

**Comment by crotoc** [comment]
从刚刚出现大规模这样的数据包之后，openclash自己就重启了好几回。

**Comment by crotoc** [comment]
我清掉所有的配置，重新安装，然后设置，现在又暂时好了。再运行一阵看看，谢谢了！

**Comment by crotoc** [comment]
你好。这两天使用fakeip模式的时候，刚开始的时候还好，但是突然就回出现大量的从路由器wan端口的包，导致openclash崩溃重启。感觉还是那个地方的iptables出了问题，但是不知道如何去debug。这是log里面的内容：

**Comment by crotoc** [comment]
这是没有启动openclash的时候，iptables -t nat -S的结果：
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT
-N postrouting_lan_rule
-N postrouting_rule
-N postrouting_wan_rule
-N prerouting_lan_rule
-N prerouting_rule
-N prerouting_wan_rule
-N zone_lan_postrouting
-N zone_lan_prerouting
-N zone_wan_postrouting
-N zone_wan_prerouting
-A PREROUTING -m comment --comment "!fw3: Custom prerouting rule chain" -j prerouting_rule
-A PREROUTING -i br-lan -m comment --comment "!fw3" -j zone_lan_prerouting
-A PREROUTING -i eth0.2 -m comment --comment "!fw3" -j zone_wan_prerouting
-A POSTROUTING -m comment --comment "!fw3: Custom postrouting rule chain" -j postrouting_rule
-A POSTROUTING -o br-lan -m comment --comment "!fw3" -j zone_lan_postrouting
-A POSTROUTING -o eth0.2 -m comment --comment "!fw3" -j zone_wan_postrouting
-A zone_lan_postrouting -m comment --comment "!fw3: Custom lan postrouting rule chain" -j postrouting_lan_rule
-A zone_lan_postrouting -s 192.168.215.0/24 -d 192.168.215.1/32 -p tcp -m tcp --dport 8022 -m comment --comment "!fw3: 8022 (reflection)" -j SNAT --to-source 192.168.215.1
-A zone_lan_postrouting -s 192.168.215.0/24 -d 192.168.215.1/32 -p udp -m udp --dport 8022 -m comment --comment "!fw3: 8022 (reflection)" -j SNAT --to-source 192.168.215.1
-A zone_lan_postrouting -s 192.168.215.0/24 -d 192.168.215.1/32 -p tcp -m tcp --dport 80 -m comment --comment "!fw3: 80 (reflection)" -j SNAT --to-source 192.168.215.1
-A zone_lan_postrouting -s 192.168.215.0/24 -d 192.168.215.1/32 -p udp -m udp --dport 80 -m comment --comment "!fw3: 80 (reflection)" -j SNAT --to-source 192.168.215.1
-A zone_lan_prerouting -m comment --comment "!fw3: Custom lan prerouting rule chain" -j prerouting_lan_rule
-A zone_lan_prerouting -s 192.168.215.0/24 -d 192.168.1.153/32 -p tcp -m tcp --dport 8022 -m comment --comment "!fw3: 8022 (reflection)" -j DNAT --to-destination 192.168.215.1:8022
-A zone_lan_prerouting -s 192.168.215.0/24 -d 192.168.1.153/32 -p udp -m udp --dport 8022 -m comment --comment "!fw3: 8022 (reflection)" -j DNAT --to-destination 192.168.215.1:8022
-A zone_lan_prerouting -s 192.168.215.0/24 -d 192.168.1.153/32 -p tcp -m tcp --dport 33333 -m comment --comment "!fw3: 80 (reflection)" -j DNAT --to-destination 192.168.215.1:80
-A zone_lan_prerouting -s 192.168.215.0/24 -d 192.168.1.153/32 -p udp -m udp --dport 33333 -m comment --comment "!fw3: 80 (reflection)" -j DNAT --to-destination 192.168.215.1:80
-A zone_wan_postrouting -m comment --comment "!fw3: Custom wan postrouting rule chain" -j postrouting_wan_rule
-A zone_wan_postrouting -m comment --comment "!fw3" -j MASQUERADE
-A zone_wan_prerouting -m comment --comment "!fw3: Custom wan prerouting rule chain" -j prerouting_wan_rule
-A zone_wan_prerouting -p tcp -m tcp --dport 8022 -m comment --comment "!fw3: 8022" -j DNAT --to-destination 192.168.215.1:8022
-A zone_wan_prerouting -p udp -m udp --dport 8022 -m comment --comment "!fw3: 8022" -j DNAT --to-destination 192.168.215.1:8022
-A zone_wan_prerouting -p tcp -m tcp --dport 33333 -m comment --comment "!fw3: 80" -j DNAT --to-destination 192.168.215.1:80
-A zone_wan_prerouting -p udp -m udp --dport 33333 -m comment --comment "!fw3: 80" -j DNAT --to-destination 192.168.215.1:80

**Comment by crotoc** [comment]
由于上面的都是fakeip，所以我也不知道到底哪些数据包的dst是哪里，所以没办法知道到底我干了啥导致了上面的状况。

**Comment by crotoc** [comment]
我仔细的读了一下相关的issue，猜测这个问题是和#144的相似，我也是使用回国规则，然后也是出现从路由器到两个fakeip的大量链接，怀疑就是到#144中提到的github的链接。所以我将output中这一条注释掉了：

**Comment by vernesong** [comment]
新版本会自己在规则后面加一句`- IP-CIDR,198.18.0.1/16,REJECT,no-resolve`
如果没有，你可以自己加

**Comment by crotoc** [comment]
好的，的确没有，我在跑跑试试。现在刚启动，暂时没问题！
在我上面注释“-A openclash_output -d 198.18.0.0/16 -p tcp -j REDIRECT --to-ports 7892”以后，也没有影响解锁视频的链接，请问这条有啥用呢？

**Comment by vernesong** [comment]
> 好的，的确没有，我在跑跑试试。现在刚启动，暂时没问题！
> 
> 在我上面注释“-A openclash_output -d 198.18.0.0/16 -p tcp -j REDIRECT --to-ports 7892”以后，也没有影响解锁视频的链接，请问这条有啥用呢？

代理路由自身用的

**Comment by crotoc** [comment]
谢谢！

平稳运行一天，应该没有问题了，先关掉issue了！
