### ISSUE TITLE
最新版无法启动，日志doesn't match any rule using DIRECT

### ISSUE THREAD

**Issue by haohaohub** [vernesong/OpenClash#476]
time="2020-05-29T20:14:47+08:00" level=info msg="DNS server listening at: 127.0.0.1:7874"
time="2020-05-29T20:14:47+08:00" level=info msg="RESTful API listening at: 0.0.0.0:9090"
time="2020-05-29T20:14:47+08:00" level=info msg="HTTP proxy listening at: :7890"
time="2020-05-29T20:14:47+08:00" level=info msg="SOCKS proxy listening at: :7891"
time="2020-05-29T20:14:47+08:00" level=info msg="Redir proxy listening at: :7892"
2020-05-29 20:14:37 OpenClash Start Successful
time="2020-05-29T20:14:48+08:00" level=info msg="[TCP] 192.168.2.149:63475 --> 61.139.29.83 doesn't match any rule using DIRECT"
time="2020-05-29T20:14:48+08:00" level=info msg="[TCP] 192.168.2.149:63476 --> 61.139.29.83 doesn't match any rule using DIRECT"
time="2020-05-29T20:15:03+08:00" level=info msg="[TCP] 192.168.2.149:63477 --> 117.23.61.188 doesn't match any rule using DIRECT"
time="2020-05-29T20:15:10+08:00" level=info msg="[TCP] 192.168.2.197:45452 --> 175.6.13.177 doesn't match any rule using DIRECT"
time="2020-05-29T20:15:10+08:00" level=info msg="[TCP] 192.168.2.149:63485 --> 183.3.233.227 doesn't match any rule using DIRECT"
time="2020-05-29T20:15:11+08:00" level=info msg="[TCP] 192.168.2.149:63486 --> 182.150.10.51 doesn't match any rule using DIRECT"
time="2020-05-29T20:15:26+08:00" level=info msg="[TCP] 192.168.2.197:39590 --> cn.app.chat.xiaomi.net doesn't match any rule using DIRECT"
time="2020-05-29T20:15:26+08:00" level=info msg="[TCP] 192.168.2.197:39592 --> cn.app.chat.xiaomi.net doesn't match any rule using DIRECT"
time="2020-05-29T20:15:26+08:00" level=info msg="[TCP] 192.168.2.197:49378 --> resolver.msg.xiaomi.net doesn't match any rule using DIRECT"
time="2020-05-29T20:15:29+08:00" level=info msg="[TCP] 192.168.2.149:63489 --> 175.6.13.166 doesn't match any rule using DIRECT"
time="2020-05-29T20:16:17+08:00" level=info msg="[TCP] 192.168.2.197:45460 --> 175.6.13.177 doesn't match any rule using DIRECT"
time="2020-05-29T20:16:18+08:00" level=info msg="[TCP] 192.168.2.149:63530 --> 175.6.13.177 doesn't match any rule using DIRECT"
time="2020-05-29T20:16:38+08:00" level=info msg="[TCP] 192.168.2.149:63533 --> 61.139.29.83 doesn't match any rule using DIRECT"
time="2020-05-29T20:16:39+08:00" level=info msg="[TCP] 192.168.2.149:63534 --> 61.139.29.83 doesn't match any rule using DIRECT"
以上是日志

我昨天重启了下然后就这么都不能用了，不能匹配直连规则是什么鬼？

**Comment by vernesong** [comment]
关闭插件后重启一下，内核映射丢失

**Comment by yakupjan01** [comment]
解决了吗？

**Comment by LevineWoo** [comment]
> 解决了吗？

我也有这样的问题，不过我这个是win版的clash meta。
