### ISSUE TITLE
都是最新内核和客户端软路由重启后守护进程未启动

### ISSUE THREAD

**Issue by jiatianxa** [vernesong/OpenClash#477]
试了很多次都是一样守护进程未启动，以前不会这样。需要手动启动一次才可以正常，使用久点也会掉守护进程。
![微信截图_20200530131331](https://user-images.githubusercontent.com/12829666/83320224-fbf27400-a277-11ea-9264-ed6553dd283f.png)

固件版本: OpenWrt SNAPSHOT r0-fdff277
LuCI版本: git-20.141.34051-f750b5f-1
内核版本: 4.19.122
处理器架构: x86_64

#此项在使用Tun模式时应为ACCEPT
防火墙转发: ACCEPT

#此项有值时建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: 

#===================== 依赖检查 =====================#
dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
jsonfilter: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
iptables-mod-tproxy: 已安装
kmod-tun(TUN模式): 已安装
luci-compat(Luci-19.07): 已安装

#===================== 内核检查 =====================#
运行状态: 运行中
已选择的架构: linux-amd64

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 
Tun内核文件: 不存在
Tun内核运行权限: 否

Game内核版本: 
Game内核文件: 不存在
Game内核运行权限: 否

Dev内核版本: premium-3-g5073c3c
Dev内核文件: 存在
Dev内核运行权限: 正常

#===================== 插件设置 =====================#
当前配置文件: /etc/openclash/config/Trojan1.yaml
运行模式: redir-host
默认代理模式: Rule
UDP流量转发: 启用
DNS劫持: 停用
自定义DNS: 启用
IPV6-DNS解析: 停用
禁用Dnsmasq缓存: 停用
自定义规则: 停用
仅允许内网: 停用
仅代理命中规则流量: 停用

#启动异常时建议关闭此项后重试
保留配置: 停用
第三方规则: 停用

#===================== 最近运行日志 =====================#
time="2020-05-30T05:11:34Z" level=info msg="Start initial compatible provider GlobalMedia"
time="2020-05-30T05:11:34Z" level=info msg="Start initial compatible provider HKMTMedia"
time="2020-05-30T05:11:34Z" level=info msg="Start initial compatible provider Apple"
time="2020-05-30T05:11:34Z" level=info msg="Start initial compatible provider Final"
time="2020-05-30T05:11:34Z" level=info msg="Start initial compatible provider Hijacking"
time="2020-05-30T05:11:34Z" level=info msg="Start initial compatible provider 自动节点选择"
time="2020-05-30T05:11:34Z" level=info msg="Start initial compatible provider PROXY"
2020-05-30 13:11:31 Faild to Download Proxy-Provider File, Please Check The Error Info And Try Again
2020-05-30 13:12:48 OpenClash Start Successful

**Comment by vernesong** [comment]
替换一下仓库最新的/etc/init.d/openclash

**Comment by jiatianxa** [comment]
感谢指导！已经好了！
