### ISSUE TITLE
youtube,netflix等网站可以连接，但Google确无法连接！

### ISSUE THREAD

**Issue by ganlu510** [vernesong/OpenClash#48]
使用fake-ip运行模式、代理模式是rule，使用同一个节点的情况下，出现youtube、netflix、telegram等应用都可以连接使用，但是同时Google确无法连接，网页显示如下：
![image](https://user-images.githubusercontent.com/31435113/67296704-6b9ec480-f51b-11e9-8459-d0ff5a12b5fb.png)

**Comment by ganlu510** [comment]
补充下配置
port: 7890
socks-port: 7891
allow-lan: true
bind-address: "*"
mode: Rule
log-level: warning
external-controller: 0.0.0.0:9090
experimental:
ignore-resolve-fail: true
cfw-bypass:
- qq.com
- music.163.com
- '*.music.126.net'
- localhost
- 127.*
- 10.*
- 172.16.*
- 172.17.*
- 172.18.*
- 172.19.*
- 172.20.*
- 172.21.*
- 172.22.*
- 172.23.*
- 172.24.*
- 172.25.*
- 172.26.*
- 172.27.*
- 172.28.*
- 172.29.*
- 172.30.*
- 172.31.*
- 192.168.*
- <local>
cfw-latency-timeout: 5000
redir-port: 7892
secret: "123456"
external-ui: "/usr/share/openclash/dashboard"
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  listen: 0.0.0.0:7874
  nameserver:
  - 114.114.114.114
  - 119.29.29.29

**Comment by ganlu510** [comment]
今天继续测试，发现虽然www.google.com首页无法连接，却意外发现www.google.com.hk 和www.google.com.tw和www.google.com.sg却都能上去。

**Comment by ganlu510** [comment]
google的日本站点也无法连接。

**Comment by vernesong** [comment]
cfw没问题？检查下规则和切换服务器，你也可以尝试清理下DNS缓存。
提供内核连接日志。

**Comment by ganlu510** [comment]
time="2019-10-24T12:27:35+08:00" level=warning msg="dial Apple error: dial tcp4 72.166.126.10:80: connect: connection refused"
time="2019-10-24T12:27:35+08:00" level=warning msg="dial Apple error: dial tcp4 72.166.126.10:80: connect: connection refused"
time="2019-10-24T12:27:50+08:00" level=warning msg="dial Apple error: dial tcp4 72.166.126.10:80: connect: connection refused"
time="2019-10-24T12:27:50+08:00" level=warning msg="dial Apple error: dial tcp4 72.166.126.10:80: connect: connection refused"
time="2019-10-24T12:27:57+08:00" level=warning msg="dial Apple error: dial tcp4 72.166.126.10:80: connect: connection refused"
time="2019-10-24T12:27:57+08:00" level=warning msg="dial Apple error: dial tcp4 72.166.126.10:80: connect: connection refused"
time="2019-10-24T12:35:20+08:00" level=warning msg="Parse metadata failed: [DNS] resolve email.docker.com error: All DNS requests failed"
time="2019-10-24T12:37:52+08:00" level=warning msg="dial Apple error: dial tcp4 31.13.77.55:443: connect: connection refused"
time="2019-10-24T12:37:57+08:00" level=warning msg="dial Apple error: dial tcp4 69.171.237.26:443: i/o timeout"
time="2019-10-24T12:38:09+08:00" level=warning msg="dial DIRECT error: dial tcp4 13.86.124.191:443: i/o timeout"
time="2019-10-24T12:44:56+08:00" level=warning msg="dial DIRECT error: dial tcp4 140.205.156.228:80: i/o timeout"
time="2019-10-24T12:51:45+08:00" level=warning msg="dial DIRECT error: dial tcp4 64.233.189.188:5228: i/o timeout"
time="2019-10-24T12:52:14+08:00" level=warning msg="dial DIRECT error: dial tcp4 64.233.189.188:443: i/o timeout"
time="2019-10-24T12:52:14+08:00" level=warning msg="dial DIRECT error: dial tcp4 64.233.189.188:443: i/o timeout"
time="2019-10-24T12:53:08+08:00" level=warning msg="dial DIRECT error: dial tcp4 64.233.189.188:5228: i/o timeout"
time="2019-10-24T12:54:33+08:00" level=warning msg="dial DIRECT error: dial tcp4 64.233.189.188:443: i/o timeout"
time="2019-10-24T12:57:33+08:00" level=warning msg="dial DIRECT error: dial tcp4 64.233.189.188:5228: i/o timeout"
time="2019-10-24T13:03:00+08:00" level=warning msg="dial DIRECT error: dial tcp4 64.233.189.188:443: i/o timeout"
time="2019-10-24T13:13:05+08:00" level=warning msg="dial DIRECT error: dial tcp4 64.233.189.188:5228: i/o timeout"
time="2019-10-24T13:23:10+08:00" level=warning msg="dial DIRECT error: dial tcp4 64.233.189.188:443: i/o timeout"
time="2019-10-24T13:33:15+08:00" level=warning msg="dial DIRECT error: dial tcp4 64.233.189.188:5228: i/o timeout"
time="2019-10-24T13:43:20+08:00" level=warning msg="dial DIRECT error: dial tcp4 64.233.189.188:443: i/o timeout"
time="2019-10-24T13:45:02+08:00" level=warning msg="dial DIRECT error: dial tcp4 140.205.156.228:80: i/o timeout"
time="2019-10-24T13:53:25+08:00" level=warning msg="dial DIRECT error: dial tcp4 64.233.189.188:5228: i/o timeout"

**Comment by vernesong** [comment]
给连接google时候的日志

**Comment by ntgeralt** [comment]
"dnsmasq.conf"添加
all-servers
dhcp-option=252,”\n”
server=127.0.0.1#5353 #AdGuardHome
no-resolv #AdGuardHome
dns-forward-max=1000 #AdGuardHome

然后clash dns listen127.0.0.1#5353
