### ISSUE TITLE
请问yacd面板可以通过端口转发实现远程控制吗？

### ISSUE THREAD

**Issue by soriano** [vernesong/OpenClash#480]
有时想远程监控一下连接情况，dashboard提供信息不如yacd丰富，但是不知道yacd是不是支持远程进入，请指教，谢谢！

**Comment by vernesong** [comment]
外部地址后加/luci-static/openclash访问，登录信息是外部访问时的地址和端口

**Comment by soriano** [comment]
> 外部地址后加/luci-static/openclash访问，登录信息是外部访问时的地址和端口

试过http://0.0.0.0:9090/luci-static/openclash显示404 page not found

http://0.0.0.0:9090/ui/#/proxies就可以访问到dashboard里

**Comment by vernesong** [comment]
地址不需要加9090

**Comment by 1-1-2** [comment]
yacd是工作在与后台相同的端口的，没特地改过后台端口可以不写直接访问。

**Comment by soriano** [comment]
弄明白了，ddns出来的地址后面把host信息密码改进去就好，谢谢各位指导

**Comment by abigchopstick** [comment]
> 弄明白了，ddns出来的地址后面把host信息密码改进去就好，谢谢各位指导

你好，请问这个host信息密码怎么改？我也在被这个问题困扰

**Comment by vernesong** [comment]
![image](https://user-images.githubusercontent.com/42875168/135795897-fac672b9-ad3e-4b5b-bffd-f9252f716819.png)
映射9090端口，填外部地址进去

**Comment by cjlhll** [comment]
楼主解决了吗？我设置了域名和端口88 。如何配置openclash远程访问呢？

**Comment by SimonLiXi** [comment]
> 楼主解决了吗？我设置了域名和端口88 。如何配置openclash远程访问呢？

我也不能访问

**Comment by xaotag** [comment]
![image](https://user-images.githubusercontent.com/40427877/211235586-836934c7-7580-4269-b032-0e9fc9183b03.png)
不太完美的实现二级域名访问

**Comment by ahxsong** [comment]
@xaotag 请问可以分享下湖南出口的代理服务么

**Comment by drw2005** [comment]
搞定了，步骤：

1、端口映射

2、openclash-插件设置-外部控制，下面两个地方填入你的域名和端口

**Comment by xmlys15** [comment]
管理页面公网SSL访问  设置公网协议是否开启了SSL，便于从公网访问时自动登录.
这个选项要去掉.
