### ISSUE TITLE
订阅地址中的排除节点无效

### ISSUE THREAD

**Issue by sususu98** [vernesong/OpenClash#481]
![image](https://user-images.githubusercontent.com/33882693/83374612-bc09c900-a3fe-11ea-8bf3-72071c45102e.png)
![image](https://user-images.githubusercontent.com/33882693/83374644-cdeb6c00-a3fe-11ea-86d9-05b0f806dca2.png)
机场有提供IPLC线路，但是超级难用，由于IPLC线路延迟低所以url-test会经常选择到该节点，所以想排除这个节点。但是添加排除节点无效

**Comment by vernesong** [comment]
节点名字部分复制发出来一下

**Comment by sususu98** [comment]
type: trojan, name: '3. 年费·T·体验 · 深港IPLC · 62 · 1年专享·100M·空闲'
