### ISSUE TITLE
Fake-IP tun模式网络被限速

### ISSUE THREAD

**Issue by STIVW** [vernesong/OpenClash#482]
正常在增强模式下可以满速260Mbps，切换到tun模式只有150Mbps。
speedtest测速

**Comment by haohaoget** [comment]
应该是你软路由性能太弱，你测速看一下你的CPU占用是不是80以上

**Comment by STIVW** [comment]
> 应该是你软路由性能太弱，你测速看一下你的CPU占用是不是80以上
好吧。我是树莓派4b用docker搭建的旁路由。
刚测了一下，clash占用110%了。总cpu确实超过80了。

**Comment by vernesong** [comment]
普通模式下速度影响会小一些，开启UDP转发后跟tun模式差别不大

**Comment by STIVW** [comment]
> 普通模式下速度影响会小一些，开启UDP转发后跟tun模式差别不大
对了，我上次无意间在fake增强模式下开了udp转发，然后腾讯会议无法加入，好多游戏匹配后进度条卡住无法进入。这是为什么？所有版本都是最新的。

**Comment by vernesong** [comment]
> > 普通模式下速度影响会小一些，开启UDP转发后跟tun模式差别不大
> > 对了，我上次无意间在fake增强模式下开了udp转发，然后腾讯会议无法加入，好多游戏匹配后进度条卡住无法进入。这是为什么？所有版本都是最新的。

tproxy未正常工作，非插件的问题，你可以尝试ssrp的udp全局，两个的转发方式是一样的
