### ISSUE TITLE
【讨论&建议】修改配置过程 临时文件放到/tmp中处理

### ISSUE THREAD

**Issue by 1-1-2** [vernesong/OpenClash#484]
目前看来配置文件修改过程的文件IO是在闪存上进行的。
可否考虑在`/tmp`目录下新建一个临时文件夹，比如`/tmp/config_mod`，先`cp`一份原配置到临时目录，将`sed`过程的临时文件也放到内存中，修改好后再拷贝覆盖原文件。感觉这样有以下好处：
+ 减少对闪存的读写
+ 整个过程在内存上进行，IO更快（P.S.我是在路由上运行的，闪存的顺序写速在300kb/s左右）
+ 修改过程中，临时文件不会被显示在luci界面上（如果在修改过程刷新luci页是会显示临时文件的）
+ 对于存储空间特别吃紧的设备，如`lhie1`的规则足有500kb，在极端情况下可能因空间不足而失败，也可以减少这种情况的发生。
当然最后一种是特别极端的情况，目前主要想到的就是1-3点感觉优化比较大。

**Comment by hcym** [comment]
墙裂沉降支持

**Comment by vernesong** [comment]
目前大部分操作本身就是在tmp目录下进行的

**Comment by 1-1-2** [comment]
在启动/重启过程中，在`/etc/openclash/config`文件夹会多次出现不同的`{原配置文件名}{随机后缀}`的临时文件。应该是在Openclash启动的`第三步`以后开始出现的。

为此我放入了一个有`proxies`+`proxy-groups`+空`rules`的配置文件（5KB），随后观察到临时文件的产生。最终在目录下的配置文件会被同名的500KB大小的配置文件替代。

这个产生配置的过程还是很实用的，只是觉得过程的临时文件路径可以稍微优化一下，推测应该跟`启用第三方规则`一功能有关。

**Comment by 1-1-2** [comment]
> 目前大部分操作本身就是在tmp目录下进行的

参照[sed命令临时文件空间占用的问题](https://zohead.com/archives/sed-space-usage/)

>sed 的 “-i” 参数做的操作就是将原先修改的 stdout 输出先保存成一个临时文件，并且临时文件与原始的文件在同一目录下（通过 mktemp 之类的方法生成，也就是上面看到的 sedXXXXXX 这种形式的临时文件，假设为：/var/sedBu2rt9），完成之后再将临时文件重命名覆盖为原始的文件（相当于：mv /var/sedBu2rt9 /var/myfile 操作），这样临时文件就消失了，也可以看出 “-i” 参数并不是直接修改 /var/myfile 文件本身。

我认为这个现象的发生是`sed -i PATTERN "$CONFIG_FILE"`过程的临时文件导致的。在启动的`"第二步: 配置文件检查..."`以及`"第三步: 修改配置文件..."`中涉及到这个操作，据我观察这两个步骤在路由上执行的总时间会超过一分钟。

考虑的可能解决方案：

```shell
# 于 init.d/openclash 变量
CONFIG_FILE_TEMP="/tmp/openclash/config_file_temp"

# 于 init.d/openclash : start() 开头
mkdir -p "/tmp/openclash"
cp -f "$CONFIG_FILE" "$CONFIG_FILE_TEMP"
```

于过程，使用`"$CONFIG_FILE_TEMP"`替代所有"$CONFIG_FILE"，所有过程在内存中运行

```shell
# 于 init.d/openclash : start() 结尾
cp -f "$CONFIG_FILE_TEMP" "$CONFIG_FILE"
```

由此，"$CONFIG_FILE"将只在开头读一次，结尾覆写一次，几乎以静态文件的形式存在。甚至clash内核的启动也将依托内存中的临时文件，至少能对第二、三、五步的启动速度有明显改善。
