### ISSUE TITLE
- 代理服务器 - 策略组 - 规则 - 部分异常

### ISSUE THREAD

**Issue by onepig22** [vernesong/OpenClash#486]
每天都会提醒这个- 代理服务器 - 策略组 - 规则 - 部分异常
每天都需要重新上传下配置文件才能使用
这个问题的原因是什么呢？怎样解决呢？升级到38.4才出现的这个问题

**Comment by vernesong** [comment]
意思就是在配置文件里面没找到这几部分的内容，建议你用自动生成或者用工具转换一下配置文件格式

**Comment by xuhuanxxx** [comment]
你看下异常是不是发生在每天的订阅更新之后

**Comment by onepig22** [comment]
> 你看下异常是不是发生在每天的订阅更新之后
是的每天更新后就用不了

**Comment by xuhuanxxx** [comment]
> > 你看下异常是不是发生在每天的订阅更新之后
> > 是的每天更新后就用不了

我也观察到这个情况，肉眼看上去是订阅规则没有更新完整。不知道是哪里的原因。

**Comment by onepig22** [comment]
> 哪里

**Comment by vernesong** [comment]
规则和订阅的时间错开
