### ISSUE TITLE
请教下，我没办法使用SSR的节点

### ISSUE THREAD

**Issue by NelsonFeng** [vernesong/OpenClash#487]
因为我这边买的服务是SSR的服务，但是我创建节点后，显示类型是SS，ping速度也是有的，唯独不能上外网

**Comment by vernesong** [comment]
暂不支持ssr，你可以取消混淆设置把ssr节点当ss用

**Comment by bobo2334** [comment]
可以手动下载 clashr 的内核，替换掉 clash 内核，记得 chmod 0755 给执行权限。

OpenClash 新旧版本 clash 内核的存放路径有点不同，注意区分。

v0.37.3-beta 之前在 `/etc/openclash/clash`，该版本以及之后版本在 `/etc/openclash/core/clash`。

- [Releases · frainzy1477/clashrdev](https://github.com/frainzy1477/clashrdev/releases)
- #222 
- #273

**Comment by NelsonFeng** [comment]
> 暂不支持ssr，你可以取消混淆设置把ssr节点当ss用

感谢，因为我这边购买的那个不可以用ss，所以期待楼主继续加上ssr支持，
