### ISSUE TITLE
QBittorrent port and SRC-PORT Issue

### ISSUE THREAD

**Issue by HueLiu** [vernesong/OpenClash#49]
Hi,

My qBittorrent listening port is `8999`, and you can see the screenshot as below.
![](https://i.loli.net/2019/10/26/7P6vy4Zb5HRGohm.png)

And also, I added `- SRC-PORT, 8999, DIRECT` to the top position of clash.yaml
![](https://i.loli.net/2019/10/26/tmQV3PDXhIzjg2J.png)

However, according to the traffic record of the ✈service provider's background interface, it shows that my traffic is being consumed in the BT download.

I checked the log information of Clash, and the domain name of the related `tracker` is using proxy. Is this caused by this reason?

![log](https://i.loli.net/2019/10/26/EXAPqZjupQwaR5D.png)

Is there a way to avoid using a proxy for bittorrent downloads?

Thank you:)

**Comment by vernesong** [comment]
The port `8999` is used for incoming connections.
Maybe, it's more suitable for you by using the rule such as `- DOMAIN-KEYWORD,tracker,DIRECT`, if there is no way to confirm the outgoing connection's port.
