### ISSUE TITLE
n1盒子使用分享，解决udp不能连接问题

### ISSUE THREAD

**Issue by haohaoget** [vernesong/OpenClash#491]
如果你使用的软路由是n1盒子遇到如下情况可借鉴：
在fake-ip模式下，使用增强模式不能连接udp流量（不能玩王者吃鸡，腾讯会议等）
切换到tun模式或者game模式又会出现由于n1盒子性能限制导致速率只有150mbps

解决方法：你只需要在网络-接口-物理设置中将**桥接接口**的勾去掉即可

你以为就完了吗？并没有，你还需要将openclash的**版本降到0.38.1**，使用**fake-ip增强模式**即内核选择dev分支内核（内核版本无所谓）
为什么要**降到0.38.1**，因为更高版本的会导致内核无法完成映射（具体原因我也不清楚）。

**Comment by abc000123** [comment]
感谢分享

**Comment by hcym** [comment]
只用过hanwckf的标定vlan方法，其它什么都不用考虑，和普通路由一样的用，

**Comment by iroywang** [comment]
提醒一下各位: 旁路由模式不可以关闭桥接接口, 否则旁路由无法连通lan

**Comment by iroywang** [comment]
> 提醒一下各位: 旁路由模式不可以关闭桥接接口, 否则旁路由无法连通lan

我刚测试了一下, 对于旁路由模式使用n1的用户可以尝试将 openclash-模式设置-UDP流量转发改成停用

**Comment by haohaoget** [comment]
> > 提醒一下各位: 旁路由模式不可以关闭桥接接口, 否则旁路由无法连通lan
> 
> 我刚测试了一下, 对于旁路由模式使用n1的用户可以尝试将 openclash-模式设置-UDP流量转发改成停用

关闭桥接可以使用，你有个地方没设置对，我以前也是旁路由关闭桥接就无法连接n1，记不清后来怎么改的了。而且我这个目的就是为了开启udp转发不然没法玩腾讯游戏和腾讯会议

**Comment by yang05130** [comment]
刚实测，不用游戏内核，切换普通内核，模式设置里的udp 转发给停用，王者荣耀的延迟恢复正常，测速也能跑满带宽
