### ISSUE TITLE
奇怪！升级0.38.6后可以上油管但其他比如谷歌、脸书、ins等等都没法上

### ISSUE THREAD

**Issue by Suidge** [vernesong/OpenClash#492]
OpenClash 调试日志

生成时间: 2020-06-03 20:42:57
插件版本: v0.38.6-beta

#===================== 系统信息 =====================#
主机型号: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz : 1 Core 4 Thread
固件版本: OpenWrt SNAPSHOT r2419-5e9e8d85
LuCI版本: git-20.088.29068-cebe120-1
内核版本: 4.19.108
处理器架构: x86_64

#此项在使用Tun模式时应为ACCEPT
防火墙转发: ACCEPT

#此项有值时建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: 

#此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 127.0.0.1#7874

#===================== 依赖检查 =====================#
dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
jsonfilter: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
iptables-mod-tproxy: 已安装
kmod-tun(TUN模式): 已安装
luci-compat(Luci-19.07): 未安装

#===================== 内核检查 =====================#
运行状态: 运行中
已选择的架构: linux-amd64

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 
Tun内核文件: 不存在
Tun内核运行权限: 否

Game内核版本: 
Game内核文件: 不存在
Game内核运行权限: 否

Dev内核版本: v0.19.0.2
Dev内核文件: 存在
Dev内核运行权限: 正常

#===================== 插件设置 =====================#
当前配置文件: /etc/openclash/config/ACL.yaml
运行模式: fake-ip
默认代理模式: Rule
UDP流量转发: 停用
DNS劫持: 启用
自定义DNS: 停用
IPV6-DNS解析: 停用
禁用Dnsmasq缓存: 启用
自定义规则: 启用
仅允许内网: 停用
仅代理命中规则流量: 停用

#启动异常时建议关闭此项后重试
保留配置: 停用
第三方规则: 停用

#===================== 自定义规则 一 =====================#
##- DOMAIN-SUFFIX,google.com,Proxy 匹配域名后缀(交由Proxy代理服务器组)
##- DOMAIN-KEYWORD,google,Proxy 匹配域名关键字(交由Proxy代理服务器组)
##- DOMAIN,google.com,Proxy 匹配域名(交由Proxy代理服务器组)
##- DOMAIN-SUFFIX,ad.com,REJECT 匹配域名后缀(拒绝)
##- IP-CIDR,127.0.0.0/8,DIRECT 匹配数据目标IP(直连)
##- SRC-IP-CIDR,192.168.1.201/32,DIRECT 匹配数据发起IP(直连)
##- DST-PORT,80,DIRECT 匹配数据目标端口(直连)
##- SRC-PORT,7777,DIRECT 匹配数据源端口(直连)

##排序在上的规则优先生效,如添加（去除规则前的#号）：
##IP段：192.168.1.2-192.168.1.200 直连
##- SRC-IP-CIDR,192.168.1.2/31,DIRECT
##- SRC-IP-CIDR,192.168.1.4/30,DIRECT
##- SRC-IP-CIDR,192.168.1.8/29,DIRECT
##- SRC-IP-CIDR,192.168.1.16/28,DIRECT
##- SRC-IP-CIDR,192.168.1.32/27,DIRECT
##- SRC-IP-CIDR,192.168.1.64/26,DIRECT
##- SRC-IP-CIDR,192.168.1.128/26,DIRECT
##- SRC-IP-CIDR,192.168.1.192/29,DIRECT
##- SRC-IP-CIDR,192.168.1.200/32,DIRECT

##IP段：192.168.1.202-192.168.1.255 直连
##- SRC-IP-CIDR,192.168.1.202/31,DIRECT
##- SRC-IP-CIDR,192.168.1.204/30,DIRECT
##- SRC-IP-CIDR,192.168.1.208/28,DIRECT
##- SRC-IP-CIDR,192.168.1.224/27,DIRECT

##此时IP为192.168.1.1和192.168.1.201的客户端流量走代理（策略），其余客户端不走代理
##因为Fake-IP模式下，IP地址为192.168.1.1的路由器自身流量可走代理（策略），所以需要排除
##在线IP段转CIDR地址：http://ip2cidr.com

##Ping-iPad
- SRC-IP-CIDR,10.10.10.196/32,DIRECT
##Ping-iPhone
- SRC-IP-CIDR,10.10.10.203/32,DIRECT
##Ayi-iPhone
- SRC-IP-CIDR,10.10.10.184/32,DIRECT
##FireTV
- SRC-IP-CIDR,10.10.10.194/32,🚀 手动切换
##AppleTV
##- SRC-IP-CIDR,10.10.10.216/32,🚀 手动切换
##NintendoSwitch
- SRC-IP-CIDR,10.10.10.195/32,🇯🇵 日本节点
##GoogleHomeMini
- SRC-IP-CIDR,10.10.10.210/32,♻️ 自动选择
##SONY-75X9500D
- SRC-IP-CIDR,10.10.10.189/32,DIRECT
##SONY-65S8500D
- SRC-IP-CIDR,10.10.10.192/32,DIRECT

##Netflix
##- DOMAIN-SUFFIX,fast.com, 🎥 奈飞节点
##- DOMAIN-SUFFIX,netflix.com, 🎥 奈飞节点
##- DOMAIN-SUFFIX,netflix.net, 🎥 奈飞节点
##- DOMAIN-SUFFIX,nflxext.com, 🎥 奈飞节点
##- DOMAIN-SUFFIX,nflximg.net,🎥 奈飞节点
##- DOMAIN-SUFFIX,nflxso.net,🎥 奈飞节点
##- DOMAIN-SUFFIX,nflxvideo.net,🎥 奈飞节点
##Disney Plus
- DOMAIN-SUFFIX,bamgrid.com, 🚀 手动切换
- DOMAIN-SUFFIX,disney-plus.net,🚀 手动切换
- DOMAIN-SUFFIX,disneyplus.com,🚀 手动切换
- DOMAIN-SUFFIX,dssott.com,🚀 手动切换
- DOMAIN-SUFFIX,cdn.registerdisney.go.com,🚀 手动切换
##Amazon Prime
- DOMAIN-SUFFIX,amazon.com,🚀 手动切换
- DOMAIN-SUFFIX,amazon.co.jp,🚀 手动切换
- DOMAIN-SUFFIX,amazon.co.uk,🚀 手动切换
- DOMAIN-SUFFIX,amazon.de,🚀 手动切换
- DOMAIN-SUFFIX,amazonvideo.com,🚀 手动切换
- DOMAIN-SUFFIX,primevideo.com,🚀 手动切换
##Twitch
- DOMAIN-SUFFIX,twitch.tv,🚀 手动切换
- DOMAIN-SUFFIX,ttvnw.net,🚀 手动切换
##Turnin
- DOMAIN-SUFFIX,turnin.com,🚀 手动切换
- DOMAIN-SUFFIX,amazon-adsystem.com,🚀 手动切换
- DOMAIN-SUFFIX,pubmatic.com,🚀 手动切换
- DOMAIN-SUFFIX,acast.com,🚀 手动切换
- DOMAIN-SUFFIX,adswizz.com,🚀 手动切换
- DOMAIN-SUFFIX,openx.net,🚀 手动切换
- DOMAIN-SUFFIX,crwdcntrl.net,🚀 手动切换
- DOMAIN-SUFFIX,agkn.com,🚀 手动切换
- DOMAIN-SUFFIX,radiotime.com,🚀 手动切换
##Line
- DOMAIN-SUFFIX,line.me,♻️ 自动选择
- DOMAIN-SUFFIX,naver.jp,♻️ 自动选择
##GAMING
- DOMAIN-SUFFIX,playstation.net,♻️ 自动选择
- DOMAIN-SUFFIX,xboxlive.com,♻️ 自动选择
##LOCATION CHECK
- DOMAIN-SUFFIX,maxmind.com,🚀 手动切换
- DOMAIN-SUFFIX,ifconfig.co,🚀 手动切换
- DOMAIN-SUFFIX,ip2location.com,🚀 手动切换
- DOMAIN-SUFFIX,uplynk.com,🚀 手动切换
##HBO NOW
- DOMAIN-SUFFIX,conviva.com,🚀 手动切换
- DOMAIN-SUFFIX,go.com,🚀 手动切换
- DOMAIN-SUFFIX,hbo.com,🚀 手动切换
- DOMAIN-SUFFIX,hbogo.com,🚀 手动切换
- DOMAIN-SUFFIX,hbonow.com,🚀 手动切换
##Hulu
- DOMAIN-SUFFIX,hulu.com,🚀 手动切换
- DOMAIN-SUFFIX,huluad.com,🚀 手动切换
- DOMAIN-SUFFIX,huluim.com,🚀 手动切换
- DOMAIN-SUFFIX,hulustream.com,🚀 手动切换
##Showtime
- DOMAIN-SUFFIX,sho.com,🚀 手动切换
- DOMAIN-SUFFIX,showtime.com,🚀 手动切换
##DirecTV NOW
- DOMAIN-SUFFIX,att.com,🚀 手动切换
- DOMAIN-SUFFIX,codec-cluster.org,🚀 手动切换
- DOMAIN-SUFFIX,directv.com,🚀 手动切换
- DOMAIN-SUFFIX,directvnow.com,🚀 手动切换
- DOMAIN-SUFFIX,dtvce.com,🚀 手动切换
- DOMAIN-SUFFIX,footprint.net,🚀 手动切换
- DOMAIN-SUFFIX,imrworldwide.com,🚀 手动切换
- DOMAIN-SUFFIX,inq.com,🚀 手动切换
- DOMAIN-SUFFIX,omtrdc.net,🚀 手动切换
##Sling TV
- DOMAIN-SUFFIX,adrta.com,🚀 手动切换
- DOMAIN-SUFFIX,adsrvr.org,🚀 手动切换
- DOMAIN-SUFFIX,cloudfront.net,🚀 手动切换
- DOMAIN-SUFFIX,crashlytics.com,🚀 手动切换
- DOMAIN-SUFFIX,doubleverify.com,🚀 手动切换
- DOMAIN-SUFFIX,fwmrm.net,🚀 手动切换
- DOMAIN-SUFFIX,innovid.com,🚀 手动切换
- DOMAIN-SUFFIX,movetv.com,🚀 手动切换
- DOMAIN-SUFFIX,scorecardresearch.com,🚀 手动切换
- DOMAIN-SUFFIX,doubleverify.com,🚀 手动切换
- DOMAIN-SUFFIX,fwmrm.net,🚀 手动切换
- DOMAIN-SUFFIX,innovid.com,🚀 手动切换
- DOMAIN-SUFFIX,movetv.com,🚀 手动切换
- DOMAIN-SUFFIX,serving-sys.com,🚀 手动切换
- DOMAIN-SUFFIX,sling.com,🚀 手动切换
- DOMAIN-SUFFIX,spotxchange.com,🚀 手动切换
- DOMAIN-SUFFIX,tremorhub.com,🚀 手动切换
- DOMAIN-SUFFIX,videoamp.com,🚀 手动切换
- DOMAIN-SUFFIX,doubleverify.com,🚀 手动切换
- DOMAIN-SUFFIX,fwmrm.net,🚀 手动切换
- DOMAIN-SUFFIX,innovid.com,🚀 手动切换
- DOMAIN-SUFFIX,movetv.com,🚀 手动切换
- DOMAIN-SUFFIX,serving-sys.com,🚀 手动切换
- DOMAIN-SUFFIX,sling.com,🚀 手动切换
- DOMAIN-SUFFIX,spotxchange.com,🚀 手动切换

##DIRECT
- DOMAIN-SUFFIX,sh.122.gov.cn,DIRECT
- DOMAIN-SUFFIX,videx.diplo.de,DIRECT
- DOMAIN-SUFFIX,live.com,DIRECT
##OTHERS
- DOMAIN-SUFFIX,ycis-sh.com,♻️ 自动选择
- DOMAIN-SUFFIX,wetransfer.com,♻️ 自动选择
- DOMAIN-SUFFIX,wpmucdn.com,♻️ 自动选择
- DOMAIN-SUFFIX,rarbg.is,♻️ 自动选择
- DOMAIN-SUFFIX,github.com,♻️ 自动选择
- DOMAIN-SUFFIX,mathletics.com,♻️ 自动选择
- DOMAIN-SUFFIX,raz-kids.com,♻️ 自动选择
- DOMAIN-SUFFIX,kidsa-z.com,♻️ 自动选择
- DOMAIN-SUFFIX,seesaw.me,♻️ 自动选择
- DOMAIN-SUFFIX,express-vpn-links.com,♻️ 自动选择
- DOMAIN-SUFFIX,expressvpn.com,♻️ 自动选择
- DOMAIN-SUFFIX,transfer.sh,♻️ 自动选择
- DOMAIN-SUFFIX,f95zone.com,♻️ 自动选择
- DOMAIN-SUFFIX,mega.nz,♻️ 自动选择
- DOMAIN-SUFFIX,ebay.com,♻️ 自动选择
- DOMAIN-SUFFIX,rakuten.co.jp,♻️ 自动选择
- DOMAIN-SUFFIX,britishairways.com,♻️ 自动选择
- DOMAIN-SUFFIX,qantas.com,♻️ 自动选择
- DOMAIN-SUFFIX,fortress.com.hk,♻️ 自动选择
- DOMAIN-SUFFIX,pornhub.com,♻️ 自动选择
- DOMAIN-SUFFIX,hsbc.com.hk,♻️ 自动选择
- DOMAIN-SUFFIX,hansgrohe.com,♻️ 自动选择
- DOMAIN-SUFFIX,americanexpressfhr.com,♻️ 自动选择
- DOMAIN-SUFFIX,tripadvisor.com,♻️ 自动选择
- DOMAIN-SUFFIX,sketchup.com,♻️ 自动选择
- DOMAIN-SUFFIX,europcar.com,♻️ 自动选择
- DOMAIN-SUFFIX,box.com,♻️ 自动选择
- DOMAIN-SUFFIX,boxcloud.com,♻️ 自动选择
- DOMAIN-SUFFIX,expedia.com,♻️ 自动选择
- DOMAIN-SUFFIX,expedia.cn,♻️ 自动选择
- DOMAIN-SUFFIX,expedia.com.hk,♻️ 自动选择
- DOMAIN-SUFFIX,etihad.com,♻️ 自动选择
- DOMAIN-SUFFIX,virtuallythere.com, ♻️ 自动选择
- DOMAIN-SUFFIX,interior-deluxe.com,♻️ 自动选择
- DOMAIN-SUFFIX,marriott.com,♻️ 自动选择
- DOMAIN-SUFFIX,bowerswilkins.com,♻️ 自动选择
- DOMAIN-SUFFIX,epsonconnect.com,♻️ 自动选择
- DOMAIN-SUFFIX,audible.com,♻️ 自动选择
- DOMAIN-SUFFIX,cospaces.io,♻️ 自动选择
- DOMAIN-SUFFIX,Wordpress.com,♻️ 自动选择
- DOMAIN-SUFFIX,fivethirtyeight.com,♻️ 自动选择
- DOMAIN-SUFFIX,maying.co,♻️ 自动选择
- DOMAIN-SUFFIX,cnbc.com,♻️ 自动选择
- DOMAIN-SUFFIX,herokuapp.com,♻️ 自动选择
- DOMAIN-SUFFIX,facebook.com,♻️ 自动选择
- DOMAIN-SUFFIX,phprcdn.com,♻️ 自动选择
- DOMAIN-SUFFIX,etahub.com,♻️ 自动选择
- DOMAIN-SUFFIX,netlify.app,♻️ 自动选择
- DOMAIN-SUFFIX,pornhub.com,🚀 手动切换
- DOMAIN-SUFFIX,pornhubpremium.com,🚀 手动切换
- DOMAIN-SUFFIX,theatlantic.com,🚀 手动切换
- DOMAIN-SUFFIX,ft.com,🚀 手动切换
- DOMAIN-SUFFIX,cnn.com,🚀 手动切换
- DOMAIN-SUFFIX,osboxes.org,♻️ 自动选择

#===================== 自定义规则 二 =====================#
##- DOMAIN-SUFFIX,google.com,Proxy 匹配域名后缀(交由Proxy代理服务器组)
##- DOMAIN-KEYWORD,google,Proxy 匹配域名关键字(交由Proxy代理服务器组)
##- DOMAIN,google.com,Proxy 匹配域名(交由Proxy代理服务器组)
##- DOMAIN-SUFFIX,ad.com,REJECT 匹配域名后缀(拒绝)
##- IP-CIDR,127.0.0.0/8,DIRECT 匹配数据目标IP(直连)
##- SRC-IP-CIDR,192.168.1.201/32,DIRECT 匹配数据发起IP(直连)
##- DST-PORT,80,DIRECT 匹配数据目标端口(直连)
##- SRC-PORT,7777,DIRECT 匹配数据源端口(直连)
#===================== 配置文件 =====================#
port: 7890
socks-port: 7891
allow-lan: true
bind-address: "*"
mode: Rule
log-level: silent
external-controller: 0.0.0.0:9090
experimental:
ignore-resolve-fail: true
redir-port: 7892
secret: "123456"
external-ui: "/usr/share/openclash/dashboard"
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  listen: 127.0.0.1:7874
  fake-ip-filter:
##Custom fake-ip-filter##
  - '*.lan'
  - 'time.windows.com'
  - 'time.nist.gov'
  - 'time.apple.com'
  - 'time.asia.apple.com'
  - '*.ntp.org.cn'
  - '*.openwrt.pool.ntp.org'
  - 'time1.cloud.tencent.com'
  - 'time.ustc.edu.cn'
  - 'pool.ntp.org'
  - 'ntp.ubuntu.com'
  - 'ntp.aliyun.com'
  - 'ntp1.aliyun.com'
  - 'ntp2.aliyun.com'
  - 'ntp3.aliyun.com'
  - 'ntp4.aliyun.com'
  - 'ntp5.aliyun.com'
  - 'ntp6.aliyun.com'
  - 'ntp7.aliyun.com'
  - 'time1.aliyun.com'
  - 'time2.aliyun.com'
  - 'time3.aliyun.com'
  - 'time4.aliyun.com'
  - 'time5.aliyun.com'
  - 'time6.aliyun.com'
  - 'time7.aliyun.com'
  - '*.time.edu.cn'
  - 'time1.apple.com'
  - 'time2.apple.com'
  - 'time3.apple.com'
  - 'time4.apple.com'
  - 'time5.apple.com'
  - 'time6.apple.com'
  - 'time7.apple.com'
  - 'time1.google.com'
  - 'time2.google.com'
  - 'time3.google.com'
  - 'time4.google.com'
  - 'music.163.com'
  - '*.music.163.com'
  - '*.126.net'
  - 'musicapi.taihe.com'
  - 'music.taihe.com'
  - 'songsearch.kugou.com'
  - 'trackercdn.kugou.com'
  - '*.kuwo.cn'
  - 'api-jooxtt.sanook.com'
  - 'api.joox.com'
  - 'joox.com'
  - 'y.qq.com'
  - '*.y.qq.com'
  - 'streamoc.music.tc.qq.com'
  - 'mobileoc.music.tc.qq.com'
  - 'isure.stream.qqmusic.qq.com'
  - 'dl.stream.qqmusic.qq.com'
  - 'aqqmusic.tc.qq.com'
  - 'amobile.music.tc.qq.com'
  - '*.xiami.com'
  - '*.music.migu.cn'
  - 'music.migu.cn'
  - '*.msftconnecttest.com'
  - '*.msftncsi.com'
  - 'localhost.ptlogin2.qq.com'
  - '*.*.*.srv.nintendo.net'
  - '*.*.stun.playstation.net'
  - 'xbox.*.*.microsoft.com'
  - '*.*.xboxlive.com'
##Custom fake-ip-filter END##
  nameserver:
  - 114.114.114.114
  fallback:
  - tls://8.8.8.8:853
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4

#===================== 防火墙设置 =====================#

#NAT chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    REDIRECT   tcp  --  0.0.0.0/0            8.8.4.4              redir ports 7892
2    REDIRECT   tcp  --  0.0.0.0/0            8.8.8.8              redir ports 7892
3    REDIRECT   udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:53 redir ports 53
4    REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:53 redir ports 53
5    prerouting_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom prerouting rule chain */
6    zone_lan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
7    zone_vpn_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
8    openclash  tcp  --  0.0.0.0/0            0.0.0.0/0           
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         
1    openclash_output  tcp  --  0.0.0.0/0            0.0.0.0/0           

#Mangle chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         
1    RRDIPT_OUTPUT  all  --  0.0.0.0/0            0.0.0.0/0           

#===================== 路由表状态 =====================#
#route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.10.10.253    0.0.0.0         UG    0      0        0 br-lan
10.10.10.0      0.0.0.0         255.255.255.0   U     0      0        0 br-lan
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
#ip route list
default via 10.10.10.253 dev br-lan proto static 
10.10.10.0/24 dev br-lan proto kernel scope link src 10.10.10.252 
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown 
#ip rule show
0:	from all lookup local 
32766:	from all lookup main 
32767:	from all lookup default 

#===================== 端口占用状态 =====================#
tcp        0      0 :::9090                 :::*                    LISTEN      31281/clash
tcp        0      0 :::7890                 :::*                    LISTEN      31281/clash
tcp        0      0 :::7891                 :::*                    LISTEN      31281/clash
tcp        0      0 :::7892                 :::*                    LISTEN      31281/clash
udp        0      0 127.0.0.1:7874          0.0.0.0:*                           31281/clash
udp        0      0 :::7891                 :::*                                31281/clash
udp        0      0 :::7892                 :::*                                31281/clash

#===================== 测试本机DNS查询 =====================#
Server:		127.0.0.1
Address:	127.0.0.1#53

Name:      www.baidu.com
Address 1: 198.18.0.108
*** Can't find www.baidu.com: No answer

#===================== resolv.conf.auto =====================#
# Interface lan
nameserver 10.10.10.253
nameserver 114.114.114.114
nameserver 223.5.5.5

#===================== 测试本机网络连接 =====================#
HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: private, no-cache, no-store, proxy-revalidate, no-transform
Connection: keep-alive
Content-Length: 277
Content-Type: text/html
Date: Wed, 03 Jun 2020 12:42:57 GMT
Etag: "575e1f60-115"
Last-Modified: Mon, 13 Jun 2016 02:50:08 GMT
Pragma: no-cache
Server: bfe/1.0.8.18

#===================== 测试本机网络下载 =====================#
HTTP/1.1 200 Connection established

HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 78
Content-Type: text/plain; charset=utf-8
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
ETag: W/"7e0d6ee41efaed471668d95783eb3427ecb306c06e5abd46be1bb57136b4c965"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
Via: 1.1 varnish (Varnish/6.0)
X-GitHub-Request-Id: 6738:3F32:11B5A0:14133B:5ED76F26
Accept-Ranges: bytes
Date: Wed, 03 Jun 2020 12:42:58 GMT
Via: 1.1 varnish
X-Served-By: cache-tyo19943-TYO
X-Cache: HFM, HIT
X-Cache-Hits: 0, 2
X-Timer: S1591188178.148388,VS0,VE0
Vary: Authorization,Accept-Encoding, Accept-Encoding
Access-Control-Allow-Origin: *
X-Fastly-Request-ID: aff5dd8dd20912eaa05e1839a3f7c75aff860e2a
Expires: Wed, 03 Jun 2020 12:47:58 GMT
Source-Age: 300

#===================== 最近运行日志 =====================#
time="2020-06-03T20:42:16+08:00" level=info msg="Start initial compatible provider 🎥 奈飞视频"
time="2020-06-03T20:42:16+08:00" level=info msg="Start initial compatible provider 🍃 应用净化"
time="2020-06-03T20:42:16+08:00" level=info msg="Start initial compatible provider Ⓜ️ 微软云盘"
time="2020-06-03T20:42:16+08:00" level=info msg="Start initial compatible provider 📢 谷歌FCM"
time="2020-06-03T20:42:16+08:00" level=info msg="Start initial compatible provider 🇨🇳 台湾节点"
time="2020-06-03T20:42:16+08:00" level=info msg="Start initial compatible provider 🚀 节点选择"
time="2020-06-03T20:42:16+08:00" level=info msg="Start initial compatible provider 🍎 苹果服务"
time="2020-06-03T20:42:16+08:00" level=info msg="Start initial compatible provider 🚀 手动切换"
time="2020-06-03T20:42:16+08:00" level=info msg="Start initial compatible provider 📹 油管视频"
time="2020-06-03T20:42:16+08:00" level=info msg="Start initial compatible provider 📲 电报消息"
time="2020-06-03T20:42:16+08:00" level=info msg="Start initial compatible provider 🇭🇰 香港节点"
time="2020-06-03T20:42:16+08:00" level=info msg="Start initial compatible provider 🇯🇵 日本节点"
time="2020-06-03T20:42:16+08:00" level=info msg="Start initial compatible provider 🇸🇬 狮城节点"
time="2020-06-03T20:42:16+08:00" level=info msg="Start initial compatible provider ♻️ 自动选择"
time="2020-06-03T20:42:16+08:00" level=info msg="Start initial compatible provider 🎥 奈飞节点"
time="2020-06-03T20:42:16+08:00" level=info msg="Start initial compatible provider 📺 巴哈姆特"
time="2020-06-03T20:42:16+08:00" level=info msg="Start initial compatible provider 🛑 广告拦截"
time="2020-06-03T20:42:16+08:00" level=info msg="Start initial compatible provider 🌏 国内媒体"
time="2020-06-03T20:42:16+08:00" level=info msg="Start initial compatible provider 🇺🇲 美国节点"
time="2020-06-03T20:42:16+08:00" level=info msg="Start initial compatible provider 🎮 游戏平台"
time="2020-06-03T20:42:16+08:00" level=info msg="Start initial compatible provider 🌍 国外媒体"
time="2020-06-03T20:42:16+08:00" level=info msg="Start initial compatible provider 🐟 漏网之鱼"
time="2020-06-03T20:42:16+08:00" level=info msg="Start initial compatible provider 🎯 全球直连"
2020-06-03 20:42:13 OpenClash Start Successful

**Comment by Suidge** [comment]
问题没解决……突然可以上了，然后又不行了。
打开谷歌显示：
www.google.com 通常会使用加密技术来保护您的信息。Google Chrome 此次尝试连接到 www.google.com 时，此网站发回了异常的错误凭据。这可能是因为有攻击者在试图冒充 www.google.com，或 Wi-Fi 登录屏幕中断了此次连接。请放心，您的信息仍然是安全的，因为 Google Chrome 尚未进行任何数据交换便停止了连接。

您目前无法访问 www.google.com，因为此网站使用了 HSTS。网络错误和攻击通常是暂时的，因此，此网页稍后可能会恢复正常。

再打开一次又变成了：
无法访问此网站www.google.com 意外终止了连接。
请试试以下办法：

检查网络连接
检查代理服务器和防火墙
运行 Windows 网络诊断

**Comment by Suidge** [comment]
关掉openclash 换成ssr+ 完全可用

**Comment by piaoyun** [comment]
我的也是这个问题呢。。测试几天，最后无法了。放弃折腾了。

**Comment by ivanberry** [comment]
我也有这个问题
