### ISSUE TITLE
dns解析的一个问题

### ISSUE THREAD

**Issue by xfdywy** [vernesong/OpenClash#494]
为了测试，在腾讯云dnspod上设置了几个域名解析，其中有两个解析到内网ip（比如路由所在ip）192.168.101.190， 有两个解析到外网ip，比如我自己的云服务器ip和8.8.8.8。

现象： 不论是在fakeip 还是redir-host 模式下，解析到内网ip的域名都没法正确解析。解析到外网ip的域名都可以正常解析。 fackip模式下四个域名都放到dns高级设置黑名单中，黑名单dns服务器设置成114.114.114.114  

![图片](https://user-images.githubusercontent.com/6959554/83652789-9abaff80-a5ed-11ea-9092-b2b28f09dff8.png)

我确定dns解析是正确的。因为我连接家里其他的路由器可以正常ping通。理论上你们应该都能ping通我的这三个域名

![图片](https://user-images.githubusercontent.com/6959554/83653222-12892a00-a5ee-11ea-8916-84f3954aa9fc.png)
![图片](https://user-images.githubusercontent.com/6959554/83653243-1c129200-a5ee-11ea-8da5-4a21692a3bb2.png)

不知道是什么原因。而且前两个域名我用nslookup ly.wyue.site 114.114.114.114也ping不通。。。。。剩下两个域名（就是指向外网的域名）都可以正常ping通。
![图片](https://user-images.githubusercontent.com/6959554/83653347-3ea4ab00-a5ee-11ea-8ff1-c7a2f6605b9d.png)

![图片](https://user-images.githubusercontent.com/6959554/83653643-9d6a2480-a5ee-11ea-981d-eb025568d0ee.png)

但是如果不是在这个环境下，连接家里另外一个路由器（非openwrt系统，没有openclash），是可以ping 通的（同理，你们可以自己试试，应该是可以ping 通的）不知道是什么原因。

![图片](https://user-images.githubusercontent.com/6959554/83653702-ae1a9a80-a5ee-11ea-921e-02300bc13934.png)

这个路由器上网完全没问题，国内国外都很流畅（除了腾讯会议等，貌似是已知问题）

**Comment by xfdywy** [comment]
再次测试。似乎与openclash无关。关闭openclash后现象依然存在。不过依然原因未明。

**Comment by Mosney** [comment]
/cgi-bin/luci/admin/network/dhcp

> 

> - [ ] 重绑定保护
> 
> 丢弃 RFC1918 上行响应数据
>
