### ISSUE TITLE
最新版在tun模式下启用网栈线路gvisor无法运行！！！

### ISSUE THREAD

**Issue by zxlhhyccc** [vernesong/OpenClash#496]
time="2020-06-04T05:11:36Z" level=info msg="Start initial compatible provider GlobalTV"
time="2020-06-04T05:11:36Z" level=info msg="Start initial compatible provider AsianTV"
time="2020-06-04T05:11:36Z" level=info msg="Start initial compatible provider Apple"
time="2020-06-04T05:11:36Z" level=info msg="Start initial compatible provider Others"
time="2020-06-04T05:11:36Z" level=info msg="Start initial compatible provider Auto - UrlTest"
time="2020-06-04T05:11:36Z" level=info msg="Start initial compatible provider Proxy"
time="2020-06-04T05:11:36Z" level=info msg="Start initial compatible provider Domestic"
time="2020-06-04T05:11:36Z" level=info msg="Start initial compatible provider AdBlock"
time="2020-06-04T05:11:36Z" level=info msg="RESTful API listening at: 0.0.0.0:9090"
time="2020-06-04T05:11:36Z" level=info msg="DNS server listening at: 127.0.0.1:7874"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11c94]

goroutine 25 [running]:
runtime/internal/atomic.goXadd64(0x28b8ad4, 0x1, 0x0, 0x4, 0xc145)
	/usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/internal/atomic/atomic_arm.go:103 +0x1c
gvisor.dev/gvisor/pkg/tcpip.(*StatCounter).IncrementBy(...)
	/Users/hfy/go/pkg/mod/github.com/comzyh/gvisor@v0.0.0-20200420094407-0d4ba3bd3efa/pkg/tcpip/tcpip.go:793
gvisor.dev/gvisor/pkg/tcpip.(*StatCounter).Increment(...)
	/Users/hfy/go/pkg/mod/github.com/comzyh/gvisor@v0.0.0-20200420094407-0d4ba3bd3efa/pkg/tcpip/tcpip.go:778
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*endpoint).sendTCP(0x28b8800, 0x28b88d4, 0x1bb, 0x2b7ae14, 0x4, 0xc145, 0x2b7ae10, 0x4, 0x120000, 0xd42f524c, ...)
	/Users/hfy/go/pkg/mod/github.com/comzyh/gvisor@v0.0.0-20200420094407-0d4ba3bd3efa/pkg/tcpip/transport/tcp/connect.go:739 +0xd8
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*endpoint).sendSynTCP(0x28b8800, 0x28b88d4, 0x1bb, 0x2b7ae14, 0x4, 0xc145, 0x2b7ae10, 0x4, 0x120000, 0xd42f524c, ...)
	/Users/hfy/go/pkg/mod/github.com/comzyh/gvisor@v0.0.0-20200420094407-0d4ba3bd3efa/pkg/tcpip/transport/tcp/connect.go:726 +0x78
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*handshake).execute(0x29d9f14, 0x0)
	/Users/hfy/go/pkg/mod/github.com/comzyh/gvisor@v0.0.0-20200420094407-0d4ba3bd3efa/pkg/tcpip/transport/tcp/connect.go:557 +0x3a8
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*listenContext).createEndpointAndPerformHandshake(0x28b43c0, 0x2926140, 0x287cf84, 0x2a28f60, 0x0, 0x0, 0xb6ee23ec, 0x0)
	/Users/hfy/go/pkg/mod/github.com/comzyh/gvisor@v0.0.0-20200420094407-0d4ba3bd3efa/pkg/tcpip/transport/tcp/accept.go:297 +0x11c
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*ForwarderRequest).CreateEndpoint(0x2922cc0, 0x2a28f60, 0x0, 0x0, 0x0)
	/Users/hfy/go/pkg/mod/github.com/comzyh/gvisor@v0.0.0-20200420094407-0d4ba3bd3efa/pkg/tcpip/transport/tcp/forwarder.go:153 +0xe8
github.com/Dreamacro/clash/proxy/stack/gvisor.(*Gvisor).Start.func1(0x2922cc0)
	/Users/hfy/Dev/project/clash/proxy/stack/gvisor/gvisor.go:132 +0x38
created by gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*Forwarder).HandlePacket
	/Users/hfy/go/pkg/mod/github.com/comzyh/gvisor@v0.0.0-20200420094407-0d4ba3bd3efa/pkg/tcpip/transport/tcp/forwarder.go:91 +0x208
2020-06-04 13:11:28 OpenClash Can Not Start, Try Use Backup Rules Start Again
time="2020-06-04T05:11:42Z" level=info msg="Start initial compatible provider AsianTV"
time="2020-06-04T05:11:42Z" level=info msg="Start initial compatible provider Others"
time="2020-06-04T05:11:42Z" level=info msg="Start initial compatible provider Auto - UrlTest"
time="2020-06-04T05:11:42Z" level=info msg="Start initial compatible provider Proxy"
time="2020-06-04T05:11:42Z" level=info msg="Start initial compatible provider Domestic"
time="2020-06-04T05:11:42Z" level=info msg="Start initial compatible provider Apple"
time="2020-06-04T05:11:42Z" level=info msg="Start initial compatible provider AdBlock"
time="2020-06-04T05:11:42Z" level=info msg="Start initial compatible provider GlobalTV"
time="2020-06-04T05:11:42Z" level=info msg="DNS server listening at: 127.0.0.1:7874"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11c94]

goroutine 51 [running]:
runtime/internal/atomic.goXadd64(0x15586d4, 0x1, 0x0, 0x4, 0xc15f)
	/usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/internal/atomic/atomic_arm.go:103 +0x1c
gvisor.dev/gvisor/pkg/tcpip.(*StatCounter).IncrementBy(...)
	/Users/hfy/go/pkg/mod/github.com/comzyh/gvisor@v0.0.0-20200420094407-0d4ba3bd3efa/pkg/tcpip/tcpip.go:793
gvisor.dev/gvisor/pkg/tcpip.(*StatCounter).Increment(...)
	/Users/hfy/go/pkg/mod/github.com/comzyh/gvisor@v0.0.0-20200420094407-0d4ba3bd3efa/pkg/tcpip/tcpip.go:778
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*endpoint).sendTCP(0x1558400, 0x15584d4, 0x1bb, 0x150be74, 0x4, 0xc15f, 0x150be70, 0x4, 0x120000, 0x7e5f13b8, ...)
	/Users/hfy/go/pkg/mod/github.com/comzyh/gvisor@v0.0.0-20200420094407-0d4ba3bd3efa/pkg/tcpip/transport/tcp/connect.go:739 +0xd8
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*endpoint).sendSynTCP(0x1558400, 0x15584d4, 0x1bb, 0x150be74, 0x4, 0xc15f, 0x150be70, 0x4, 0x120000, 0x7e5f13b8, ...)
	/Users/hfy/go/pkg/mod/github.com/comzyh/gvisor@v0.0.0-20200420094407-0d4ba3bd3efa/pkg/tcpip/transport/tcp/connect.go:726 +0x78
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*handshake).execute(0x16bbf14, 0x0)
	/Users/hfy/go/pkg/mod/github.com/comzyh/gvisor@v0.0.0-20200420094407-0d4ba3bd3efa/pkg/tcpip/transport/tcp/connect.go:557 +0x3a8
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*listenContext).createEndpointAndPerformHandshake(0x1630180, 0x1526140, 0x147cf84, 0x168c4a0, 0x0, 0x0, 0xb6f2a3ec, 0x0)
	/Users/hfy/go/pkg/mod/github.com/comzyh/gvisor@v0.0.0-20200420094407-0d4ba3bd3efa/pkg/tcpip/transport/tcp/accept.go:297 +0x11c
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*ForwarderRequest).CreateEndpoint(0x15232f0, 0x168c4a0, 0x0, 0x0, 0x0)
	/Users/hfy/go/pkg/mod/github.com/comzyh/gvisor@v0.0.0-20200420094407-0d4ba3bd3efa/pkg/tcpip/transport/tcp/forwarder.go:153 +0xe8
github.com/Dreamacro/clash/proxy/stack/gvisor.(*Gvisor).Start.func1(0x15232f0)
	/Users/hfy/Dev/project/clash/proxy/stack/gvisor/gvisor.go:132 +0x38
created by gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*Forwarder).HandlePacket
	/Users/hfy/go/pkg/mod/github.com/comzyh/gvisor@v0.0.0-20200420094407-0d4ba3bd3efa/pkg/tcpip/transport/tcp/forwarder.go:91 +0x208
2020-06-04 13:11:28 OpenClash Can Not Start, Please Check The Error Info And Try Again

**Comment by vernesong** [comment]
32位？

**Comment by zxlhhyccc** [comment]
> 32位？

我是k3，软路由上还没测试，周末测试一下。。。。
