### ISSUE TITLE
大神，您能不能一次性的更新好呀？

### ISSUE THREAD

**Issue by taoersvip** [vernesong/OpenClash#497]
大神，您能不能一次性的更新好呀？ 我都快崩溃了，上个版本更新了就用不了，现在又更新了

**Comment by vernesong** [comment]
什么用不了

**Comment by taoersvip** [comment]
> 什么用不了
直接启动不了，报错一大串，然后没办法退回38.4，在我目前能正常使用的版本

**Comment by cnsunyour** [comment]
这么抱怨不好吧，有问题就反馈问题进行解决。我这里两台设备刚更新了用的好好的。

**Comment by taoersvip** [comment]
> 这么抱怨不好吧，有问题就反馈问题进行解决。我这里两台设备刚更新了用的好好的。

我再试试吧， 不知道到底是什么问题
