### ISSUE TITLE
微信朋友圈图片视频缓冲问题

### ISSUE THREAD

**Issue by leozhu1120** [vernesong/OpenClash#499]
<img width="1351" alt="Screen Shot 2020-06-04 at 4 23 04 PM" src="https://user-images.githubusercontent.com/59215468/83733363-02ba2600-a680-11ea-8890-149da12713e0.png">
<img width="1348" alt="Screen Shot 2020-06-04 at 4 22 13 PM" src="https://user-images.githubusercontent.com/59215468/83733404-0fd71500-a680-11ea-962a-e5d5c0a2e2b5.png">
<img width="1313" alt="Screen Shot 2020-06-04 at 4 22 02 PM" src="https://user-images.githubusercontent.com/59215468/83733447-1f565e00-a680-11ea-9cd9-f073f964dd22.png">
<img width="1363" alt="Screen Shot 2020-06-04 at 4 31 44 PM" src="https://user-images.githubusercontent.com/59215468/83733973-eb2f6d00-a680-11ea-8a59-be51ec097624.png">

使用openclash的时候微信朋友圈内容刷新异常缓慢 打开图片或者视频转圈要好几秒 出国访问分流均正常 使用ssrp+的时候无此问题 网上搜了说可能是dns设置的问题 求大神指点 本人使用的Dler Cloud添加的配置

**Comment by vernesong** [comment]
自定义dns启用，下面预设的全部选上，进控制面板看看链接情况
