### ISSUE TITLE
Can't find www.google.com: No answer

### ISSUE THREAD

**Issue by wtser** [vernesong/OpenClash#50]
兼容模式

```
➜  ~ nslookup www.google.com
Server:		10.2.4.1
Address:	10.2.4.1#53

Non-authoritative answer:
*** Can't find www.google.com: No answer

➜  ~ nslookup www.google.com.hk
Server:		10.2.4.1
Address:	10.2.4.1#53

Non-authoritative answer:
Name:	www.google.com.hk
Address: 69.171.234.18
```

日志没有任何报错

**Comment by wtser** [comment]
![image](https://user-images.githubusercontent.com/2093743/67619114-19ff7e00-f82a-11e9-96f4-452ea9e5d177.png)

**Comment by vernesong** [comment]
显示的结果说明ipv4查询失败，兼容模式需要同时配置国内外的dns服务器，尝试更换clash的上游dns服务器，这部分你可以去wiki看下推荐配置。
还有就是建议关闭IPV6的DHCP服务，目前openclash还无法处理客户端上IPV6抢答的问题。

**Comment by wtser** [comment]
IPV6 DHCP 关了也这样啊

**Comment by vernesong** [comment]
用fake呢，如果规则有Google走代理，dns直接是交给代理服务器查询的

**Comment by wtser** [comment]
@vernesong fake 正常

**Comment by vernesong** [comment]
多尝试一下其他的国外服务器
