### ISSUE TITLE
控制面板

### ISSUE THREAD

**Issue by 88188ml** [vernesong/OpenClash#500]
更新后。控制面板进入后 无法选择 全局 规则 直连。或者选择全局后，出现的选择全局代理的页面和规则页面一样

**Comment by CodeEagle** [comment]
我也是遇到这个问题

**Comment by frankestain** [comment]
我也一样遇到这个问题了，样式错位了，不知道你两是不是这种情况。frankestain@vip.qq.com   如果解决了，麻烦发我一下办法
![2020-06-09_161629](https://user-images.githubusercontent.com/5234437/84123821-f281bc80-aa6c-11ea-80c4-d25ccc7eaa8c.jpg)
