### ISSUE TITLE
王者延迟问题排查

### ISSUE THREAD

**Issue by yanliang721** [vernesong/OpenClash#503]
王者在 fake ip 模式下一直4,500的延迟。。无法游戏，关闭就正常了。
我按照[这里](https://github.com/vernesong/OpenClash/wiki/%E7%BD%91%E7%BB%9C%E8%BF%9E%E6%8E%A5%E5%BC%82%E5%B8%B8%E6%97%B6%E6%8E%92%E6%9F%A5%E5%8E%9F%E5%9B%A0#%E4%BA%8Cdns%E6%AD%A3%E5%B8%B8%E6%97%B6%E4%BB%8D%E6%97%A0%E6%B3%95%E8%BF%9B%E8%A1%8C%E4%BB%A3%E7%90%86%E9%9D%9E%E6%B8%B8%E6%88%8F%E6%A8%A1%E5%BC%8F)检查了下。
我的是这样子的
![image](https://user-images.githubusercontent.com/66150016/83937867-fa3e2880-a802-11ea-8128-4d828d45b12a.png)
其中 1,2 两条的 `destination` 指向了 8.8.8.8 和 8.4.4.4。

我在手机上 利用 nslookup www.baidu.com 返回的 Server 直接是8.8.8.8。 小白不知道有没有影响。
![image](https://user-images.githubusercontent.com/66150016/83937916-44bfa500-a803-11ea-9ca3-b7b7bd8a8396.png)

而我在电脑上返回的 Server 是我路由器的地址。
![image](https://user-images.githubusercontent.com/66150016/83937945-7a648e00-a803-11ea-8265-371aa62bf124.png)

我尝试将 1,2 两条删除，影响访问 google。在 openclash 中先切到 Redir-Host 模式，再切回到 fake ip 模式，1,2 两条又回来了。还是 8.8.8.8 和 8.4.4.4。
不知道有没有帮助，想把这两条的 8.8.8.8 和 8.4.4.4 换成其他的尝试王者还会不会一直 4,500 ms的延迟。怎么操作。

**Comment by vernesong** [comment]
手机为啥是谷歌的DNS？那两条防火墙只劫持tcp，fakeip你要开udp流量转发

**Comment by yanliang721** [comment]
> 手机为啥是谷歌的DNS？那两条防火墙只劫持tcp，fakeip你要开udp流量转发

我也不知道为什么是8.8.8.8。
我开过udp流量转发，开了之后更惨，王者荣耀的测速，没开udp只是互联网延迟500，开了以后互联网延迟和社区宽带延迟都500了。。参考下面这图，没去开udp再截了。。
![image](https://user-images.githubusercontent.com/66150016/83958235-1ba22180-a8a2-11ea-9757-310f485f7dfd.png)

**Comment by vernesong** [comment]
路由运行 lsmod | grep proxy -i
看下结果

**Comment by yanliang721** [comment]
> 路由运行 lsmod | grep proxy -i
> 看下结果

![image](https://user-images.githubusercontent.com/66150016/83969020-ceed3380-a8ff-11ea-92d6-73a21a12e68a.png)

这样的

**Comment by vernesong** [comment]
参考下https://github.com/vernesong/OpenClash/issues/374

**Comment by yanliang721** [comment]
我的固件是有自带 docker 的。
参考 #374 最后将kmod-br-netfilter卸了重启，似乎还是没有解决，估计 #491 退回以前的版本可以解决，我也貌似就是5月份0.38.1左右的版本开始出现这样的情况的，晚上回家再试试。

**Comment by Mosney** [comment]
我没记错的话，这个测出来的延迟并不是实际延迟。开启网关代理之后这些延迟测试机制就会失效，之前我在clash透明代理下用Netch测节点延迟也是全都测不出正确的延迟，另外还发现同样是在clash透明代理后使用mtr追踪路由也是异常，只有一跳直接到终点。具体原理不清楚，以上只是根据我的观察而来

**Comment by vernesong** [comment]
cfa那边初步判断是内核BUG，还有待观察
https://networktest.twilio.com/
这个网站测试没通过

**Comment by vernesong** [comment]
更新内核看下

**Comment by revival83** [comment]
> 我的固件自带docker。>参考#374，kmod-br-netfilter后来重新卸下，似乎没有解决。估计#491退回以前的版本可以解决。我似乎开始出现这样的情况，版本约为0.38.1，回家试试。请问您最后怎么解决的？我也是和您一样的问题，请问退回哪个版本能解决呢？
