### ISSUE TITLE
luci-app-openclash.postinst-pkg: line 68: /lib/upgrade/keep.d/luci-app-openclash: No such file or directory

### ISSUE THREAD

**Issue by zxlhhyccc** [vernesong/OpenClash#507]
![image](https://user-images.githubusercontent.com/45259624/83973812-60b66a00-a91b-11ea-9f83-7ff99ca3fbed.png)

**Comment by vernesong** [comment]
固件编译中这个问题可以忽略，本身是为单独安装插件写的
