### ISSUE TITLE
[bug report]即使不启用DNS劫持功能，openclash的启动脚本关闭时依然会重置dnsmasq配置

### ISSUE THREAD

**Issue by Mosney** [vernesong/OpenClash#51]
看了一下openclash的[启动脚本](https://github.com/vernesong/OpenClash/blob/master/luci-app-openclash/files/etc/init.d/openclash)，应该是588行附近少了一个检查是否开启了DNS劫持功能的判断
```
echo "第四步: 重启 Dnsmasq 程序..." >$START_LOG
    revert_dns
    /etc/init.d/dnsmasq restart >/dev/null 2>&1
```
如果不加判断，service openclash stop时就会无脑执行如下脚本：删除手动添加的自定义上游DNS、重新启用解析文件、恢复默认DNS缓存大小
```
revert_dns() {
   dns_port=$(uci get openclash.config.dns_port 2>/dev/null)
   uci del_list dhcp.@dnsmasq[0].server=127.0.0.1#"$dns_port" >/dev/null 2>&1
   uci set dhcp.@dnsmasq[0].resolvfile=/tmp/resolv.conf.auto
   uci set dhcp.@dnsmasq[0].noresolv=0
   uci delete dhcp.@dnsmasq[0].cachesize
   uci commit dhcp
   rm -rf /tmp/dnsmasq.d/dnsmasq_openclash.conf >/dev/null 2>&1
}
```
建议如同469行一样添加判断参数，以防止这种情况出现

`          change_dns "$enable_redirect_dns" "$disable_masq_cache"
`

**Comment by vernesong** [comment]
目前来看影响不是很大，但为了避免不可预知的问题，我会在下个版本加入判断命令

**Comment by Mosney** [comment]
> 目前来看影响不是很大，但为了避免不可预知的问题，我会在下个版本加入判断命令

目前0.35.5仍会重置dnsmasq的上游DNS，忽略解析文件、缓存数量不会重置。
