### ISSUE TITLE
n1 openclash ui界面mode模式错位，不能选择

### ISSUE THREAD

**Issue by frankestain** [vernesong/OpenClash#511]
如图
![2020-06-09_161629](https://user-images.githubusercontent.com/5234437/84123561-928b1600-aa6c-11ea-850f-0a3d5f442c07.jpg)

错位了，以前好好的，而且不能点击选择rule global这些选项

**Comment by hcym** [comment]
别用那些规则，不然无穷无尽的状况，用自己参照模板改一个上传就ok

**Comment by frankestain** [comment]
> 别用那些规则，不然无穷无尽的状况，用自己参照模板改一个上传就ok

是规则的问题么？我用了好几个机场的规则，自己也改了好几个但是还是这样，我见其他主题里面也有写说是不能选

**Comment by hcym** [comment]
应该是自动生成的毛病，很早以前就用过，就是生成规则错误，放弃了有一年多，后来是瞎猫碰上死耗子，用别人模板改过上传，一切正常，现在都是用自己改好的，乱七八糟十几个节点也没有问题，就是机场的麻烦些，要一个个改好

**Comment by vernesong** [comment]
新版应该修复了

**Comment by frankestain** [comment]
修复什么了？

**Comment by 1033154478** [comment]
> 修复什么了？

请问你的问题解决了吗，俺的n1也是这样，不知道是不是和二楼的说的用了转换的锅，但是我记得几个版本前是没有问题的，如果你解决麻烦告诉俺一下怎么操作的谢谢

**Comment by 1033154478** [comment]
俺现在发现高版本不知道是不是n1的锅opclash有点，，脱节，特别是控制面板，反应非常慢，我现在暂时切回ssr+和cfw了

**Comment by frankestain** [comment]
> > 修复什么了？
> 
> 请问你的问题解决了吗，俺的n1也是这样，不知道是不是和二楼的说的用了转换的锅，但是我记得几个版本前是没有问题的，如果你解决麻烦告诉俺一下怎么操作的谢谢

我解决了，最新的内核和客户端不兼容，简单的办法就是替换以前的内核，不要更新更新内核；第二种就是直接下载最新ipk替换了客户端，那就如ver这个人说的，就没有问题了

**Comment by frankestain** [comment]
> 俺现在发现高版本不知道是不是n1的锅opclash有点，，脱节，特别是控制面板，反应非常慢，我现在暂时切回ssr+和cfw了

我n1 用的f大的open也用的旧的客户端，没有更新，你说的那个反应慢的问题，我没有遇到，现在用的挺好，切换快，故障

**Comment by hcym** [comment]
n1用的很好，没有什么问题，就是最近两个版本可能改变选择策略，总是最快的节点，不是最好的，路由器还是大雕的方便快捷，这个用在手机比较好

**Comment by 1033154478** [comment]
> > > 修复什么了？
> > 
> > 
> > 请问你的问题解决了吗，俺的n1也是这样，不知道是不是和二楼的说的用了转换的锅，但是我记得几个版本前是没有问题的，如果你解决麻烦告诉俺一下怎么操作的谢谢
> 
> 我解决了，最新的内核和客户端不兼容，简单的办法就是替换以前的内核，不要更新更新内核；第二种就是直接下载最新ipk替换了客户端，那就如ver这个人说的，就没有问题了

好的谢谢呀，我试一下，另外，versong是这个项目的开发者之一，不是这个人哈哈哈

**Comment by frankestain** [comment]
> > > > 修复什么了？
> > > 
> > > 
> > > 请问你的问题解决了吗，俺的n1也是这样，不知道是不是和二楼的说的用了转换的锅，但是我记得几个版本前是没有问题的，如果你解决麻烦告诉俺一下怎么操作的谢谢
> > 
> > 
> > 我解决了，最新的内核和客户端不兼容，简单的办法就是替换以前的内核，不要更新更新内核；第二种就是直接下载最新ipk替换了客户端，那就如ver这个人说的，就没有问题了
> 
> 好的谢谢呀，我试一下，另外，versong是这个项目的开发者之一，不是这个人哈哈哈

恩，是大佬，感谢大佬开发这么好软件，特别喜欢用，大佬还回复了

**Comment by 1033154478** [comment]
> > > > > 修复什么了？
> > > > 
> > > > 
> > > > 请问你的问题解决了吗，俺的n1也是这样，不知道是不是和二楼的说的用了转换的锅，但是我记得几个版本前是没有问题的，如果你解决麻烦告诉俺一下怎么操作的谢谢
> > > 
> > > 
> > > 我解决了，最新的内核和客户端不兼容，简单的办法就是替换以前的内核，不要更新更新内核；第二种就是直接下载最新ipk替换了客户端，那就如ver这个人说的，就没有问题了
> > 
> > 
> > 好的谢谢呀，我试一下，另外，versong是这个项目的开发者之一，不是这个人哈哈哈
> 
> 恩，是大佬，感谢大佬开发这么好软件，特别喜欢用，大佬还回复了

我从新装了ipk，可以选择模式，但是现在好像全局和规则没什么区别
![image](https://user-images.githubusercontent.com/62164808/84844730-97a82080-b07d-11ea-9ceb-8be32783b12f.png)
