### ISSUE TITLE
v0.38.7版本provider异常

### ISSUE THREAD

**Issue by RunStar99** [vernesong/OpenClash#512]
<img width="1176" alt="截屏2020-06-09 16 42 22" src="https://user-images.githubusercontent.com/46420475/84127882-64a8d000-aa72-11ea-8be1-62ceb8842f5f.png">
观察/etc/openclash/proxy_provider中已经正确下载完毕,  但一直显示下载外部文件.
退回v0.38.6后正常

**Comment by RunStar99** [comment]
<img width="1027" alt="截屏2020-06-12 15 12 45" src="https://user-images.githubusercontent.com/46420475/84475703-94004c80-acbf-11ea-800f-79f46051a240.png">
![F3C2CD3D-AB95-4E26-87A2-76F1C15F7FF2](https://user-images.githubusercontent.com/46420475/84475709-95ca1000-acbf-11ea-859c-9a32b69933fd.png)
38.8版仍然异常,回退38.6正常

**Comment by vernesong** [comment]
发下配置文件

**Comment by RunStar99** [comment]
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:7874
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    # QQ快捷登录
    - '.ptlogin2.qq.com'
    # xbox ps  switch
    - '*.*.*.*.srv.nintendo.net'
    - '*.*.*.stun.playstation.net'
    - 'xbox.*.microsoft.com'
    - '*.*.*.xboxlive.com'
    # NTP服务
    - time.windows.com
    - time.nist.gov
    - time.apple.com
    - time.asia.apple.com
    - cn.ntp.org.cn
    - edu.ntp.org.cn
    - hk.ntp.org.cn
    - tw.ntp.org.cn
    - us.ntp.org.cn
    - sgp.ntp.org.cn
    - kr.ntp.org.cn
    - jp.ntp.org.cn
    - de.ntp.org.cn
    - ina.ntp.org.cn
    - 0.openwrt.pool.ntp.org
    - 1.openwrt.pool.ntp.org
    - 2.openwrt.pool.ntp.org
    - 3.openwrt.pool.ntp.org
    - ntp.aliyun.com             
    - ntp1.aliyun.com
    - ntp2.aliyun.com
    - ntp3.aliyun.com
    - ntp4.aliyun.com
    - ntp5.aliyun.com
    - ntp6.aliyun.com
    - ntp7.aliyun.com
    - time1.aliyun.com
    - time2.aliyun.com
    - time3.aliyun.com
    - time4.aliyun.com
    - time5.aliyun.com
    - time6.aliyun.com
    - time7.aliyun.com
    - s1c.time.edu.cn
    - s2m.time.edu.cn
    - s1b.time.edu.cn
    - s1e.time.edu.cn
    - s2a.time.edu.cn
    - s2b.time.edu.cn
    - time1.apple.com
    - time2.apple.com
    - time3.apple.com
    - time4.apple.com
    - time5.apple.com
    - time6.apple.com
    - time7.apple.com
    - time1.google.com
    - time2.google.com
    - time3.google.com
    - time4.google.com
  nameserver:
    - 223.5.5.5
    - tcp://114.114.114.114

**Comment by RunStar99** [comment]
iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 8053
iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 8053

**Comment by vernesong** [comment]
发这些没用，你发provider那部分，我看看格式怎么写的

**Comment by RunStar99** [comment]
proxy-providers:
  游戏:
    type: http
    path: ./proxy_provider/Game.yaml
    url: 
    interval: 10800
    health-check:
        enable: true
        url: http://cp.cloudflare.com/generate_204
        interval: 85888
  救护车:
    type: http
    path: ./proxy_provider/Ambulance_3.yaml
    url: 
    interval: 10800
    health-check:
        enable: true
        url: http://cp.cloudflare.com/generate_204
        interval: 18000
  # 购物车:
  #   type: http
  #   path: ./proxy_provider/购物车_1.yaml
  #   url: 
  #   interval: 86400
  #   health-check:
  #       enable: true
  #       url: http://cp.cloudflare.com/generate_204
  #       interval: 900
  # 自行车:
  #   type: http
  #   path: ./proxy_provider/自行车.yaml
  #   url: 
  #   interval: 86400
  #   health-check:
  #       enable: true
  #       url: http://cp.cloudflare.com/generate_204
  #       interval: 900
  # 电瓶车:
  #   type: http
  #   path: ./proxy_provider/电瓶车.yaml
  #   url: 
  #   interval: 86400
  #   health-check:
  #       enable: true
  #       url: http://cp.cloudflare.com/generate_204
  #       interval: 900
  摩托:
    type: http
    path: ./proxy_provider/Motorcycle.yaml
    url: 
    interval: 86400
    health-check:
        enable: true
        url: http://cp.cloudflare.com/generate_204
        interval: 900
  # 汽车:
  #   type: http
  #   path: ./proxy_provider/Car.yaml
  #   url: 
  #   interval: 10800
  #   health-check:
  #       enable: true
  #       url: http://cp.cloudflare.com/generate_204
  #       interval: 600
  飞机:
    type: http
    path: ./proxy_provider/Airplane.yaml
    url: 
    interval: 10800
    health-check:
        enable: true
        url: http://cp.cloudflare.com/generate_204
        interval: 600
  火箭:
    type: http
    path: ./proxy_provider/Rocket.yaml
    url: 
    interval: 10800
    health-check:
        enable: true
        url: http://cp.cloudflare.com/generate_204
        interval: 299
  飞碟:
    type: http
    path: ./proxy_provider/UFO_1.yaml
    url: 
    interval: 10800
    health-check:
        enable: true
        url: http://cp.cloudflare.com/generate_204
        interval: 86400

  US:
    type: http
    path: ./proxy_provider/US.yaml
    url: 
    interval: 10800
    health-check:
        enable: true
        url: http://cp.cloudflare.com/generate_204
        interval: 43200
  JP:
    type: http
    path: ./proxy_provider/JP.yaml
    url: 
    interval: 10800
    health-check:
        enable: true
        url: http://cp.cloudflare.com/generate_204
        interval: 82222
  # TW:
  #   type: http
  #   path: ./proxy_provider/TW.yaml
  #   url: 
  #   interval: 10800
  #   health-check:
  #       enable: true
  #       url: http://cp.cloudflare.com/generate_204
  #       interval: 905
  SG:
    type: http
    path: ./proxy_provider/SG.yaml
    url: 
    interval: 10800
    health-check:
        enable: true
        url: http://cp.cloudflare.com/generate_204
        interval: 79988
  # KR:
  #   type: http
  #   path: ./proxy_provider/KR.yaml
  #   url: 
  #   interval: 10805
  #   health-check:
  #       enable: true
  #       url: http://cp.cloudflare.com/generate_204
  #       interval: 988

  # 忍者US
  1-US:
    type: http
    path: ./proxy_provider/1-US.yaml
    url: 
    interval: 86400
    health-check:
        enable: true
        url: http://cp.cloudflare.com/generate_204
        interval: 1500
  # 🍟real-US
  # 0-US:
  #   type: http
  #   path: ./proxy_provider/0-US.yaml
  #   interval: 86400
  #   health-check:
  #       enable: true
  #       url: http://cp.cloudflare.com/generate_204
  #       interval: 1500
  # 🍟V5
  水晶球:
    type: http
    path: ./proxy_provider/Crystal_1.yaml
    url: 
    interval: 86400
    health-check:
        enable: true
        url: http://cp.cloudflare.com/generate_204
        interval: 8888

**Comment by RunStar99** [comment]
38.9版问题已解决
