### ISSUE TITLE
外网客户端连接内网ssr服务器问题，求大佬解答！

### ISSUE THREAD

**Issue by xzhqhfe** [vernesong/OpenClash#513]
外网客户端访问内网ssr服务器可以连接到内网，可以打开Dashboard控制面板，但不能通过openclash连接谷歌和油管，用ShadowSocksR Plus+可以访问谷歌和油管。有什么可以解决的方法吗？

**Comment by vernesong** [comment]
ssr服务器怎么填的

**Comment by xzhqhfe** [comment]
> ssr服务器怎么填的

![批注 2020-06-09 215232](https://user-images.githubusercontent.com/65793074/84156117-b285fe00-aa9b-11ea-863e-a7045773581c.jpg)

**Comment by xzhqhfe** [comment]
这会有时可以访问，有时不行，系统日志如下：
Tue Jun  9 22:59:00 2020 cron.info crond[23774]: USER root pid 21113 cmd /usr/share/clash/kill_watchdog.sh
Tue Jun  9 22:59:10 2020 kern.err /usr/bin/ssr-server[5075]: remote recv: Connection reset by peer
Tue Jun  9 22:59:10 2020 kern.err /usr/bin/ssr-server[5075]: remote recv: Connection reset by peer
Tue Jun  9 22:59:11 2020 kern.err /usr/bin/ssr-server[5075]: remote recv: Connection reset by peer
Tue Jun  9 23:00:00 2020 cron.info crond[23774]: USER root pid 23218 cmd /usr/share/clash/kill_watchdog.sh
Tue Jun  9 23:01:00 2020 cron.info crond[23774]: USER root pid 25368 cmd /usr/share/clash/kill_watchdog.sh
Tue Jun  9 23:02:00 2020 cron.info crond[23774]: USER root pid 27482 cmd /usr/share/clash/kill_watchdog.sh
Tue Jun  9 23:03:00 2020 cron.info crond[23774]: USER root pid 29610 cmd /usr/share/clash/kill_watchdog.sh
Tue Jun  9 23:04:00 2020 cron.info crond[23774]: USER root pid 31648 cmd /usr/share/clash/kill_watchdog.sh
Tue Jun  9 23:05:00 2020 cron.info crond[23774]: USER root pid 892 cmd /usr/share/clash/kill_watchdog.sh
Tue Jun  9 23:06:00 2020 cron.info crond[23774]: USER root pid 2049 cmd /usr/share/clash/kill_watchdog.sh
Tue Jun  9 23:06:56 2020 kern.err /usr/bin/ssr-server[5075]: remote recv: Connection reset by peer
Tue Jun  9 23:06:56 2020 kern.err /usr/bin/ssr-server[5075]: remote recv: Connection reset by peer
Tue Jun  9 23:07:00 2020 cron.info crond[23774]: USER root pid 3194 cmd /usr/share/clash/kill_watchdog.sh
Tue Jun  9 23:08:00 2020 cron.info crond[23774]: USER root pid 4326 cmd /usr/share/clash/kill_watchdog.sh

**Comment by vernesong** [comment]
clash插件关一下，有个脚本在运行

**Comment by vernesong** [comment]
开服务端可能无法使用telegram这种使用IP连接的应用，目前还无法解决

**Comment by xzhqhfe** [comment]
刚才重启了一下路由，直接就可以访问，断开外网客户端再连接就又不能访问了，不知道什么原因？
谢谢大佬的回复
