### ISSUE TITLE
v0.38.7 yacd面板节点排序问题

### ISSUE THREAD

**Issue by btcforver** [vernesong/OpenClash#514]
大佬好：
      更新到最新的版本后，发现节点按延迟排序出现如下情况，不可用的节点跑最前面来了，之前的版本都正常的(延迟最低的绿色节点在最前面)，求指导：
![image](https://user-images.githubusercontent.com/60208053/84132827-ebf94200-aa78-11ea-8ab2-deb773e1ae8b.png)
![image](https://user-images.githubusercontent.com/60208053/84132879-fc112180-aa78-11ea-8f6c-b0087bd7c0cc.png)

**Comment by vernesong** [comment]
按配置文件的节点顺序显示的吧，你如果不习惯可以去yacd作者那边问问
