### ISSUE TITLE
状态页的国内IP地址查询一直都是查询中

### ISSUE THREAD

**Issue by xuhuanxxx** [vernesong/OpenClash#515]
这几个月的版本跟下来，国内IP从来没有查询成功过
![image](https://user-images.githubusercontent.com/4946617/84137999-261a1200-aa80-11ea-9b1c-938ba9477908.png)

今天无聊看了下页面，发现IPIP查询好像是跨域出了问题？
![image](https://user-images.githubusercontent.com/4946617/84138132-61b4dc00-aa80-11ea-93f5-2ef27fe74ab0.png)

IP.PC是直接被拒绝了
![image](https://user-images.githubusercontent.com/4946617/84138264-9163e400-aa80-11ea-8704-308db11f346d.png)

浏览器直接访问两个查询接口都能获得正确结果

**Comment by vernesong** [comment]
关闭下广告屏蔽？

**Comment by xuhuanxxx** [comment]
> 关闭下广告屏蔽？

一开始我也怀疑的广告屏蔽插件或者去广告规则的问题，测试了一下关闭openclash+移除浏览器广告屏蔽插件，下面那俩海外接口结果倒是正确

![image](https://user-images.githubusercontent.com/4946617/84149462-19eb8000-aa93-11ea-970e-509f99c249d9.png)

另外pconline那个接口是可以正常通信的，只是403了

![image](https://user-images.githubusercontent.com/4946617/84149286-cb3de600-aa92-11ea-8b63-6deb8e687aab.png)

**Comment by xuhuanxxx** [comment]
pconline这个接口，我模拟了一下http请求，请求头里去掉 Referer: https://10.10.10.254/cgi-bin/luci/admin/services/openclash ，就可以拿到正确的结果，不然就是403。

**Comment by xuhuanxxx** [comment]
IPIP接口应该是协议的问题，我的luci页面是https，IPIP的接口是http。

**Comment by vernesong** [comment]
IPIP的问题应该是HTTPS的原因，PCONLINE的可能跟你的证书有关，有试过关闭HTTPS访问吗

**Comment by xuhuanxxx** [comment]
> IPIP的问题应该是HTTPS的原因，PCONLINE的可能跟你的证书有关，有试过关闭HTTPS访问吗
http的luci状态页，pconline也是查询中。这个和我用什么证书应该没关系，浏览器直接发起的查询请求是能拿到正确结果的，状态页代发就会被403了。很明显是服务端的策略。你可以构造一个和状态页一样的请求试试看。

**Comment by vernesong** [comment]
似乎屏蔽了除192.168以外的内网地址的引用请求

**Comment by vernesong** [comment]
抽空换个api好了

**Comment by xuhuanxxx** [comment]
155dd538f5ff2526085fa96eeb2ae0bebaeac524 亲测有效
