### ISSUE TITLE
ipad在开启后的短暂时间内能连上，之后除了电报都连不上，重启又能连上然后过一段时间又只有电报连上，安卓没问题

### ISSUE THREAD

**Issue by RUI98** [vernesong/OpenClash#517]
这是为什么呢

**Comment by RUI98** [comment]
蓝鸟也连得上，股沟，油管和脸书无法连接

**Comment by RUI98** [comment]
![8187C44E-3358-4924-9ABE-166C544DC80C](https://user-images.githubusercontent.com/41661580/84158888-fa5a5480-aa9e-11ea-8b3a-c5b538a35343.png)

**Comment by vernesong** [comment]
有域名出现吗？
DNS污染，换FAKEIP
确保客户端DNS是路由地址

**Comment by RUI98** [comment]
太尴尬了，原来ipad设置了手动的没改回来
