### ISSUE TITLE
DNS解析无法区分国内跟国际

### ISSUE THREAD

**Issue by gzshasha** [vernesong/OpenClash#518]
当前客户端版本 | v0.38.8-beta ，当前【Dev分支】内核版本 premium-22-g58c077b

openwrt版本 OpenWrt R20.5.20 (Compiled by Lusty on Jun.2, 2020) / LuCI Master (git-20.141.34051-f750b5f) 。

openwrt运行在VM虚拟机中，同时也在运行了 DEBIAN Linux 。

物理主机能够桥接到 openwrt中的科学网络，Debian系统也能正常桥接上网，局域网中的其他设备也正常科学上网。

我在Debian中安装了 v2ray，用TCP-HTTP混淆进行手机流量免流，简单理解为手机网络vpn回家流量免费。

由于工作关系需要用钉钉签到拍照，在局域网中或者WiFi下钉钉的签到DNS解析到国内使用的是高德地图数据库有实际当地签到的商户名字。如果在4G流量中用钉钉签到就会钉钉DNS解析到国外，使用的是Google地图，没有签到的商家名字无法签到。尝试了多次抓包，将钉钉签到的IP跟网址填写到不走代理中依然还是一样DNS解析到国外。

手机4G连接了家中v2ray，打开ipip.net也会显示的是代理IP，但是打开ip111.cn会显示家里的宽带公网IP。

**Comment by vernesong** [comment]
需要用哪个DNS来解析才行？

**Comment by gzshasha** [comment]
> 需要用哪个DNS来解析才行？

换过全部的DNS都不行，只能用passwall的GFW模式才能解析到钉钉的国内DNS，但是passwall的GFW模式又不能连接Google，只能签到的时候改到GFW模式，签到完改回中国白名单模式。
这个我搞了很久都不懂问题出在哪里。

**Comment by vernesong** [comment]
gfw就是使用本地接口设置的dns解析的国内地址，你关闭openclash能不能签到
