### ISSUE TITLE
错误: 配置文件DNS选项下的Nameserver必须设置服务器,已自动还原配置

### ISSUE THREAD

**Issue by shugo-chara** [vernesong/OpenClash#52]
为了在海外能自动指定锅内网站使用指定dns，从smart转到openclash。

安装好后一直提示错误: 配置文件DNS选项下的Nameserver必须设置服务器,已自动还原配置
config里的文件是初始状态，没有修改过。尝试重置覆盖默认配置还是不行。
内核版本那里也一直显示未知，正确内核已经存在配置文件夹里。
mac上有用clashx，openwrt上绕了几圈也没没跑起来。。

**Comment by vernesong** [comment]
![image](https://user-images.githubusercontent.com/42875168/67688629-1ceaa200-f9d5-11e9-92e4-591cff6880f9.png)

这里启用后必须在页面下方选择启用dns服务器，否则会提示错误

![image](https://user-images.githubusercontent.com/42875168/67688805-60dda700-f9d5-11e9-85f8-70f5c89966fa.png)


内核放在`/etc/openclash`,给权限

**Comment by shugo-chara** [comment]
@vernesong 已经勾选了dns。内核在客户端里自己更新后也是提示启动失败，检查日志。
日志只是在重复 
OpenClash Can Not Start, Try Use Backup Rules Start Again
OpenClash Can Not Start, Please Check The Error Info And Try Again
OpenClash Core Update Successful。

**Comment by vernesong** [comment]
CPU什么架构，内核要根据CPU架构选择编译版本，选错了启动不了的

**Comment by shugo-chara** [comment]
@vernesong - -没有错。r8000的armv7架构。识别的也是这个。
而且今早发现安装openclash后路由频繁出错，无法连接，需要重启。可能跟8000不太兼容吧

**Comment by shugo-chara** [comment]
@vernesong openwrt
![image](https://user-images.githubusercontent.com/20610965/67834586-1c641f80-fb2b-11e9-828b-cae8bdfa04ae.png)
![image](https://user-images.githubusercontent.com/20610965/67834606-2d149580-fb2b-11e9-8dbb-4328f5018bed.png)

内核没问题，权限没问题，系统没问题。就是跑不起来。

**Comment by shugo-chara** [comment]
@vernesong 谢谢帮助，换成v5内核显示正常了，但是还是启动失败。
![image](https://user-images.githubusercontent.com/20610965/67926641-d6c25800-fbf9-11e9-8519-576889e6e4f9.png)

先是日志里一直显示uuid错误，参考别的issues吧默认配置里的节点都删掉后也不行，最后直接清空默认配置也不行。
`time="2019-10-31T07:06:10Z" level=fatal msg="Parse config error: Proxy [3]: uuid: incorrect UUID length: uuid"
2019-10-31 07:06:09 OpenClash Can Not Start, Please Check The Error Info And Try Again
time="2019-10-31T07:08:15Z" level=fatal msg="Parse config error: Proxy [2]: uuid: incorrect UUID length: uuid"
2019-10-31 07:08:14 OpenClash Can Not Start, Please Check The Error Info And Try Again
time="2019-10-31T07:08:53Z" level=fatal msg="Parse config error: Proxy [0]: uuid: incorrect UUID length: uuid"
2019-10-31 07:08:52 OpenClash Can Not Start, Please Check The Error Info And Try Again`

我只想给指定域名分流指定dns，并不用梯子之类的，请问要怎么设置。

**Comment by shugo-chara** [comment]
@vernesong 摸索了下把所有功能都关掉了。
我不需要用节点信息。只是单纯想把指定域名交给指定dns来解析而已，其他功能都不用。
现在在兼容模式下，host里添加'xxxx':ip这种规则来实现。
开启dns 劫持后在上游dns列表里无论选择哪一个都会出现b站直播无法加载的情况，只能全部关闭。

**Comment by vernesong** [comment]
那你切到fakeip，需要指定dns的域名添加到DNS设置-高级设置里的黑名单里去
规则只留下最后的`- MATCH,Direct`

你也可以不使用openclash，直接使用dnsmasq进行域名DNS指定
`server=/qq.com/114.114.114.114`
这个你自行百度

**Comment by shugo-chara** [comment]
@vernesong 谢谢知道。想问一下保留规则- MATCH,DIRECT后，
高级模式的黑名单里的域名是不走任何dns吗？如果我想指定域名走指定dns的话，只要把域名添加进黑名单后在下方服务器里勾选要用的dns后就行了吗。像下图这样？
![image](https://user-images.githubusercontent.com/20610965/68009427-48b3a380-fcc5-11e9-9af0-24a67e709012.png)
如果是的话，那黑名单以外的其他域名是不是就默认全部直连不走任何代理吗。
还是说我理解反了。

dnsmasq之前是用的这个，只是有时候需要随时换不同的dns，每次都要连上编辑dnsmasq多少有些麻烦。

**Comment by vernesong** [comment]
![image](https://user-images.githubusercontent.com/42875168/68010713-54e93200-fcc0-11e9-90de-6e8b0a8690d4.png)
黑名单走上图设置的DNS，不在黑名单里的全部直连，走你截图的自定义DNS

**Comment by shugo-chara** [comment]
@vernesong 明白了，谢谢你。
