### ISSUE TITLE
望尽快支持rule providers，幸苦了！！

### ISSUE THREAD

**Issue by Apocalypsor** [vernesong/OpenClash#520]
文档如下：
```
https://lancellc.gitbook.io/clash/clash-config-file/rule-provider
```
经测试，d大的docker镜像内的clash premium已可使用classical的provider
```
https://hub.docker.com/r/dreamacro/clash-premium
```
这里给一个我掏出来的[amd64](https://www.dropbox.com/t/QejlxhEyhPyj4UDP)的方便大佬测试（

**Comment by vernesong** [comment]
代码已做支持，你自己写好配置文件和替换tun内核

**Comment by Apocalypsor** [comment]
我替换好最新的tun内核后，在代理模式里面选了Script模式，但是我的配置还是显示规则部分异常
![规则部分异常](https://user-images.githubusercontent.com/37431235/84351301-add15f00-abed-11ea-92fe-5839049185d0.png)
并且启动后也显示异常
![Snipaste_2020-06-11_14-09-51](https://user-images.githubusercontent.com/37431235/84351333-c04b9880-abed-11ea-9a08-7bf08e86d066.png)
但是相同的配置直接用clash二进制跑是没问题的
![Snipaste_2020-06-11_14-14-58](https://user-images.githubusercontent.com/37431235/84351464-043e9d80-abee-11ea-9ce5-d42fe54c7a5b.png)
请问我这边是有啥操作不对吗，这里是我脱敏后的[配置文件](https://pastebin.com/Gtj2NCg9)

另外发现了个bug：
* 在rule-providers里面如果有个叫Proxy的provider，则会被以为是Proxy块（

**Comment by vernesong** [comment]
暂时把rules:段可以启动

**Comment by Apocalypsor** [comment]
大佬什么意思，只能暂时用rules而不能用script吗🤣

**Comment by vernesong** [comment]
把rules:字段加上就行了，内容留空

**Comment by Apocalypsor** [comment]
经过我的测试，加了rules:字段后，我给我的名字叫Proxy的rule provider改了个名字就可以正常启动了

**Comment by haossu** [comment]
请教一下 rule-provider 的GitHub推荐吗？没找到个合适的rule-provider地址

**Comment by Apocalypsor** [comment]
> 请教一下 rule-provider 的GitHub推荐吗？没找到个合适的rule-provider地址

神机规则啊
```
https://github.com/DivineEngine/Profiles/tree/master/Clash/RuleSet
```

**Comment by haossu** [comment]
多谢告知，clash x成功优化完成
