### ISSUE TITLE
请问为什么tun模式下强制启用dns-hijack？

### ISSUE THREAD

**Issue by Mosney** [vernesong/OpenClash#521]
我注意到使用tun模式启动脚本会强制加入
```yaml
  dns-hijack:
  - tcp://8.8.8.8:53
  - tcp://8.8.4.4:53
```
搞不清楚这个模块起什么作用，但是从名字来看是DNS劫持，如下所示我已经确保DNS查询必然会经过clash，iptables也没看到劫持UDP53，请问这个DNS劫持是起到什么作用？能不能交由用户选择开启与否？

```yaml
dns:
  enable: true
  ipv6: false
  listen: 127.0.0.1:5053
  enhanced-mode: redir-host
  nameserver:
  - 127.0.0.1:6053
  fallback:
  - 127.0.0.1:7053
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4
      - 127.0.0.0/8

**Comment by vernesong** [comment]
tcp的dns查询普通内核默认是不支持的，但是一些设备会调用谷歌的tcp，这是tun内核的一个功能，默认启用是方便使用

**Comment by Mosney** [comment]
@vernesong 还是没懂强制启用的的必要性，我理解的你说的意思是“因为tun可以用tcp查询DNS了所以就一定要用上它”

**Comment by vernesong** [comment]
> @vernesong 还是没懂强制启用的的必要性，我理解的你说的意思是“因为tun可以用tcp查询DNS了所以就一定要用上它”

不用的话你的tcp查询不通，谷歌服务很常见，所以为什么不用呢？

**Comment by Mosney** [comment]
我本来就已经做好了DNS分流的啊，如果强制用Google DNS的话走直连的国内域名解析出的IP会CDN不友好的吧

**Comment by vernesong** [comment]
你理解有误，这里的意思是你向8.8.8.8发起tcp查询才会劫持到clash
否则只会当成目标是8.8.8.8的tcp流量走IP规则判断，这样域名规则会失效
![image](https://user-images.githubusercontent.com/42875168/84391841-1808f480-ac2c-11ea-9c8a-673aa97b1b15.png)

![image](https://user-images.githubusercontent.com/42875168/84391863-1fc89900-ac2c-11ea-8c60-f21eec829035.png)

**Comment by Mosney** [comment]
意思是此处劫持的意思是只劫持使用TCP协议发往8.8.8.8且53端口的数据包，原本的DNS分流并不会受到影响，这个功能是为了类似chromecast之类强制使用8.8.8.8查询DNS的设备而准备的对吗？的确是没理解这个DNS劫持的含义，clash那边也没给出文档解释，感谢耐心解答

**Comment by Mosney** [comment]
找到一份文档
https://lancellc.gitbook.io/clash/start-clash/clash-tun-mode/clash-tun-mode-1

> dns-hijack
> When in fake-ip mode, clash will always return a fake-ip for standard DNS queries. Some devices or software always use a hardcoded DNS server. (For example, Google Speakers always use 8.8.8.8). You may use this option to hijack the query to get a fake address. And in redir-host mode, clash will return a result resolved by inside DNS server.
>

**Comment by Mosney** [comment]
这个文档还真不好找🌚

**Comment by yanliang721** [comment]
我#503 的问题，同样的网，我手机就指向了8.8.8.8 和 8.8.4.4，和这个有关系吗? @Mosney

**Comment by Mosney** [comment]
> 我#503 的问题，同样的网，我手机就指向了8.8.8.8 和 8.8.4.4，和这个有关系吗? @Mosney

没看懂你的表述

**Comment by yanliang721** [comment]
> > 我#503 的问题，同样的网，我手机就指向了8.8.8.8 和 8.8.4.4，和这个有关系吗? @Mosney
> 
> 没看懂你的表述

我手机上王者延迟一直很高是不是会是因为这个原因导致？用 Google DNS 的走直连的国内域名解析

**Comment by 5ian** [comment]
> 

我玩手游延迟也经常高的离谱，也怀疑因为这个设置产生的，想问一下这个问题解决了吗
