### ISSUE TITLE
任天堂Switch NAT检测B

### ISSUE THREAD

**Issue by Rakau** [vernesong/OpenClash#522]
不知道怎么回事，关闭openclash后正常。还有就是联机时是UDP，但是规则里已经写好，但是还是走的直连，看对应的规则居然是空白的。用Passwall是A....不知道怎么解决这个问题.....把所有模式(兼容模式/游戏模式/Tun/等)都试了

**Comment by vernesong** [comment]
- SRC-IP-CIDR,192.168.1.201/32,DIRECT 匹配数据发起IP(直连)
用tun的redir模式

**Comment by Rakau** [comment]
> * SRC-IP-CIDR,192.168.1.201/32,DIRECT 匹配数据发起IP(直连)
>   用tun的redir模式

谢谢你，一会儿我试试

**Comment by Rakau** [comment]
> * SRC-IP-CIDR,192.168.1.201/32,DIRECT 匹配数据发起IP(直连)
>   用tun的redir模式

![批注 2020-06-11 183558](https://user-images.githubusercontent.com/33389179/84375801-aa9c9a00-ac12-11ea-8c16-ab2183db88fe.png)
![批注 2020-06-11 183324](https://user-images.githubusercontent.com/33389179/84375813-ac665d80-ac12-11ea-844d-eaa2bc28e154.png)

如图，一张图是加了匹配数据的规则，依旧是B。
第二张图是指定nintendo关键字的规则，但是并未匹配规则，是空白的

**Comment by vernesong** [comment]
src规则选个代理策略组让switch走代理，不是直连

**Comment by Rakau** [comment]
> src规则选个代理策略组让switch走代理，不是直连

谢谢大佬了，还是和图一一样，不匹配规则，走直连。我还是先解决B的问题吧，大佬有方法吗？

**Comment by vernesong** [comment]
src规则不是第二张图吗

**Comment by Rakau** [comment]
> src规则不是第二张图吗

是的，好奇怪的现象，如果是IP就不走规则

**Comment by Rakau** [comment]
弄了半天终于把不匹配规则解决了，原因是节点配置里没写上udp: true，另外还是有个问题，那就是直连的话NAT还是B，不知道该怎么解决

**Comment by Rakau** [comment]
![2020061222424400-57B4628D2267231D57E0FC1078C0596D_waifu2x_2x_1n_jpg](https://user-images.githubusercontent.com/33389179/84515325-e7de5600-acfe-11ea-81ee-a5c80701d733.png)
成功开启UDP，NAT为A FullCone

**Comment by xfzha0** [comment]
> ![2020061222424400-57B4628D2267231D57E0FC1078C0596D_waifu2x_2x_1n_jpg](https://user-images.githubusercontent.com/33389179/84515325-e7de5600-acfe-11ea-81ee-a5c80701d733.png)
> 节点成功开启UDP，NAT为A FullCone

我开启udp转发后switc的nat type成了F了。。。。

**Comment by Rakau** [comment]
> > ![2020061222424400-57B4628D2267231D57E0FC1078C0596D_waifu2x_2x_1n_jpg](https://user-images.githubusercontent.com/33389179/84515325-e7de5600-acfe-11ea-81ee-a5c80701d733.png)
> > 节点成功开启UDP，NAT为A FullCone
> 
> 我开启udp转发后switc的nat type成了F了。。。。

你先确定你的节点UDP开了吗?

**Comment by Sciroccogti** [comment]
> 我开启udp转发后switch的nat type成了F了。。。。
我也是。。我的节点确认开了 UDP。

**Comment by Rakau** [comment]
> > 我开启udp转发后switch的nat type成了F了。。。。
> 我也是。。我的节点确认开了 UDP。
> 

我的已经解决，节点问题…你的话可能是固件问题，是不是有鲸鱼？

**Comment by Sciroccogti** [comment]
> 我的已经解决，节点问题…你的话可能是固件问题，是不是有鲸鱼？

（实际上我是 Linux 设备上的 docker 的 clash，但是应该差不多？）

我发现刚才我是 tun 的配置文件没写对（虽然现在也没搞明白应该怎么写

**Comment by Rakau** [comment]
带docker好像UDP转发都有问题

无风引漩 ***@***.***> 于 2021年5月25日周二 23:13写道：

**Comment by Sciroccogti** [comment]
> 带docker好像UDP转发都有问题

感谢，我现在换回原生的 clash 了，然后发现网卡写错了 👋🏻

然而修正以后 NAT 还是只有 C。。。请问是需要配置 iptable 然后 用redir的端口`7892`吗？

**Comment by Rakau** [comment]
你可以用桌面客户端先试试看是不是节点问题

无风引漩 ***@***.***> 于 2021年5月26日周三 01:34写道：

**Comment by CXYdgd** [comment]
> > > ![2020061222424400-57B4628D2267231D57E0FC1078C0596D_waifu2x_2x_1n_jpg](https://user-images.githubusercontent.com/33389179/84515325-e7de5600-acfe-11ea-81ee-a5c80701d733.png)
> > > 节点成功开启UDP，NAT为A FullCone
> > 
> > 
> > 我开启了udp类型的开关后的nat变成了。。。。
> 
> 你先确定你的节点UDP开了吗？

兄弟，我这边住的公寓给不了公网ip，但是我有vps可以搭建一个加速给swit加速natA吗？没有像相关教程链接呀，谢谢

**Comment by CXYdgd** [comment]
> > > ![2020061222424400-57B4628D2267231D57E0FC1078C0596D_waifu2x_2x_1n_jpg](https://user-images.githubusercontent.com/33389179/84515325-e7de5600-acfe-11ea-81ee-a5c80701d733.png)
> > > 节点成功开启UDP，NAT为A FullCone
> > 
> > 
> > 我开启了udp类型的开关后的nat变成了。。。。
> 
> 你先确定你的偏差UDP开了吗？

兄弟，我住的公寓，给不了公网ip，但是我有vps，我可以搭建一个给switch加速到natA的环境吗，给以给个教程链接吗？谢谢

**Comment by CXYdgd** [comment]
> > > > ![2020061222424400-57B4628D2267231D57E0FC1078C0596D_waifu2x_2x_1n_jpg](https://user-images.githubusercontent.com/33389179/84515325-e7de5600-acfe-11ea-81ee-a5c80701d733.png)
> > > > 节点成功开启UDP，NAT为A FullCone
> > > 
> > > 
> > > 我开启了udp类型的开关后的nat变成了。。。。
> > 
> > 
> > 你先确定你的偏差UDP开了吗？
> 
> 兄弟，我住的公寓，给不了公网ip，但是我有vps，我可以搭建一个给switch加速到natA的环境吗，给以给个教程链接吗？谢谢

我搭建了v2ray然后挂路由器里给switc，能有NATB了，但是还是很多联机游戏玩不了，比如马车和大乱斗，但是马里奥制造可以

**Comment by Rakau** [comment]
> > > > ![2020061222424400-57B4628D2267231D57E0FC1078C0596D_waifu2x_2x_1n_jpg](https://user-images.githubusercontent.com/33389179/84515325-e7de5600-acfe-11ea-81ee-a5c80701d733.png)
> > > > 节点成功开启UDP，NAT为A FullCone
> > > 
> > > 
> > > 我开启了udp类型的开关后的nat变成了。。。。
> > 
> > 你先确定你的偏差UDP开了吗？
> 
> 兄弟，我住的公寓，给不了公网ip，但是我有vps，我可以搭建一个给switch加速到natA的环境吗，给以给个教程链接吗？谢谢

可以使用trojan

**Comment by vernesong** [comment]
打游戏用ss或者trojan,vmess不行的

**Comment by Menmenla** [comment]
技术小白想打喷喷3搜到这里...

**Comment by Menmenla** [comment]
技术小白为了打喷喷3搜到这里 - - 绝望求助
收藏了这里找到的一些nintendo规则不知道但该怎么设置
家里网是朋友帮忙弄的公网ip 桥接模式 目前用openclash+支持udp的节点 
wifi链接设置了一个端口转发NAT是A 但是每次匹配进去就秒掉线.... 然后换了有线结果NAT变成B和F了... 结果都一样能匹配但一直掉线

**Comment by Rakau** [comment]
> 

不需要特意设置端口转发，防火墙打开转发，Fullcone打开节点正常就是A了，进去秒掉线可以试试换P核

**Comment by Menmenla** [comment]
> > 
> 
> 
> 
> 不需要特意设置端口转发，防火墙打开转发，Fullcone打开节点正常就是A了，进去秒掉线可以试试换P核

谢谢回复!!!
有点超纲可以再多问问防火墙和fullcone打开转发如何操作吗
之前只在hello world插件里面看到过，没在openclash找到fullcone设置🥹

**Comment by Rakau** [comment]
> > > 
> > 
> > 
> > 不需要特意设置端口转发，防火墙打开转发，Fullcone打开节点正常就是A了，进去秒掉线可以试试换P核
> 
> 谢谢回复!!! 有点超纲可以再多问问防火墙和fullcone打开转发如何操作吗 之前只在hello world插件里面看到过，没在openclash找到fullcone设置🥹

在Openwrt主页的网络-防火墙

**Comment by Menmenla** [comment]
> > > > 
> 
> > > 
> 
> > > 
> 
> > > 不需要特意设置端口转发，防火墙打开转发，Fullcone打开节点正常就是A了，进去秒掉线可以试试换P核
> 
> > 
> 
> > 谢谢回复!!! 有点超纲可以再多问问防火墙和fullcone打开转发如何操作吗 之前只在hello world插件里面看到过，没在openclash找到fullcone设置🥹
> 
> 
> 
> 在Openwrt主页的网络-防火墙

或许可以有偿求助嘛...🥹不太知道该设置什么具体内容

**Comment by Rakau** [comment]
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 不需要特意设置端口转发，防火墙打开转发，Fullcone打开节点正常就是A了，进去秒掉线可以试试换P核
> > 
> > 
> > > 
> > 
> > 
> > > 谢谢回复!!! 有点超纲可以再多问问防火墙和fullcone打开转发如何操作吗 之前只在hello world插件里面看到过，没在openclash找到fullcone设置🥹
> > 
> > 
> > 在Openwrt主页的网络-防火墙
> 
> 或许可以有偿求助嘛...🥹不太知道该设置什么具体内容

转发打开，Fullcone打开

**Comment by Menmenla** [comment]
> > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > 不需要特意设置端口转发，防火墙打开转发，Fullcone打开节点正常就是A了，进去秒掉线可以试试换P核
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 谢谢回复!!! 有点超纲可以再多问问防火墙和fullcone打开转发如何操作吗 之前只在hello world插件里面看到过，没在openclash找到fullcone设置🥹
> 
> > > 
> 
> > > 
> 
> > > 在Openwrt主页的网络-防火墙
> 
> > 
> 
> > 或许可以有偿求助嘛...🥹不太知道该设置什么具体内容
> 
> 
> 
> 转发打开，Fullcone打开

防火墙fullcone这里是兼容模式，端口转发有两个（转发到80和9090端口）都一直是开启的。
我昨天试着插了根网线结果NAT一会B一会F了。。。P核的话是什么 要怎么换呢🥹🥹

**Comment by Rakau** [comment]
> > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > 不需要特意设置端口转发，防火墙打开转发，Fullcone打开节点正常就是A了，进去秒掉线可以试试换P核
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > 谢谢回复!!! 有点超纲可以再多问问防火墙和fullcone打开转发如何操作吗 之前只在hello world插件里面看到过，没在openclash找到fullcone设置🥹
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 在Openwrt主页的网络-防火墙
> > 
> > 
> > > 
> > 
> > 
> > > 或许可以有偿求助嘛...🥹不太知道该设置什么具体内容
> > 
> > 
> > 转发打开，Fullcone打开
> 
> 防火墙fullcone这里是兼容模式，端口转发有两个（转发到80和9090端口）都一直是开启的。 我昨天试着插了根网线结果NAT一会B一会F了。。。P核的话是什么 要怎么换呢🥹🥹

ACC那也要设置，用高性能
