### ISSUE TITLE
关于openclash的cpu占用情况的一个问题

### ISSUE THREAD

**Issue by nekomiya-hinata** [vernesong/OpenClash#523]
使用openclash时，当一个请求经过openclash走直连时，softirq与system对cpu的占用明显比一个请求经过openclash走代理时高，具体可以看图中的情况，请问这是bug还是我使用的固件问题呢？
（使用设备：斐讯n1，固件：N1_Openwrt_R20.5.9_k5.4.39-flippy-36+o，openclash版本：v0.38.8-beta）
![请求直连](https://user-images.githubusercontent.com/46987091/84425889-e7898080-ac54-11ea-83b1-2f2def57e564.png)
![请求代理](https://user-images.githubusercontent.com/46987091/84425896-ece6cb00-ac54-11ea-84a8-e0bc5276a600.png)

**Comment by vernesong** [comment]
性能问题确实存在，非tun&游戏模式几乎没有影响。
