### ISSUE TITLE
开启OpenClash之后防火墙的端口转发失效

### ISSUE THREAD

**Issue by Mosney** [vernesong/OpenClash#525]
OpenWrt 19.07.3 
v0.38.8-beta

具体现象与此issue类似 https://github.com/vernesong/OpenClash/issues/63 ，不过按照他的叙述是防火墙**开启端口**的规则失效，我这边给OpenWrt自身开启的端口都正常工作，问题出在**端口转发**的规则都失效，关闭OpenClash之后即恢复正常。

网络拓扑是简单的All in One，即网关路由DHCP等都是唯一且为OpenWrt负责，不存在旁路网关设备，WAN口即是公网IP，使用OpenWrt luci界面 网络->防火墙，端口转发至LAN口设备规则全员失效，通信规则中开启本机端口规则正常运作。

由于我不是非常了解iptables转发的顺序、链、表什么的，只能用最小化OpenWrt默认配置给出测试结果，下面贴一下开启OpenClash、仅添加了一个公网:61234->10.1.1.123:9090的端口转发的NAT表，其中用 `$WAN-IP$`表示WAN口IP。

```
root@0P19:~# iptables -t nat -S
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT
-N postrouting_lan_rule
-N postrouting_rule
-N postrouting_wan_rule
-N prerouting_lan_rule
-N prerouting_rule
-N prerouting_wan_rule
-N zone_lan_postrouting
-N zone_lan_prerouting
-N zone_wan_postrouting
-N zone_wan_prerouting
-A PREROUTING -m comment --comment "!fw3: Custom prerouting rule chain" -j prerouting_rule
-A PREROUTING -i br-lan -m comment --comment "!fw3" -j zone_lan_prerouting
-A PREROUTING -i pppoe-wan -m comment --comment "!fw3" -j zone_wan_prerouting
-A POSTROUTING -m comment --comment "!fw3: Custom postrouting rule chain" -j postrouting_rule
-A POSTROUTING -o br-lan -m comment --comment "!fw3" -j zone_lan_postrouting
-A POSTROUTING -o pppoe-wan -m comment --comment "!fw3" -j zone_wan_postrouting
-A zone_lan_postrouting -m comment --comment "!fw3: Custom lan postrouting rule chain" -j postrouting_lan_rule
-A zone_lan_postrouting -s 10.1.1.0/24 -d 10.1.1.123/32 -p tcp -m tcp --dport 9090 -m comment --comment "!fw3: test-port-fw (reflection)" -j SNAT --to-source 10.1.1.1
-A zone_lan_postrouting -s 10.1.1.0/24 -d 10.1.1.123/32 -p udp -m udp --dport 9090 -m comment --comment "!fw3: test-port-fw (reflection)" -j SNAT --to-source 10.1.1.1
-A zone_lan_prerouting -m comment --comment "!fw3: Custom lan prerouting rule chain" -j prerouting_lan_rule
-A zone_lan_prerouting -s 10.1.1.0/24 -d $WAN-IP$/32 -p tcp -m tcp --dport 61234 -m comment --comment "!fw3: test-port-fw (reflection)" -j DNAT --to-destination 10.1.1.123:9090
-A zone_lan_prerouting -s 10.1.1.0/24 -d $WAN-IP$/32 -p udp -m udp --dport 61234 -m comment --comment "!fw3: test-port-fw (reflection)" -j DNAT --to-destination 10.1.1.123:9090
-A zone_wan_postrouting -m comment --comment "!fw3: Custom wan postrouting rule chain" -j postrouting_wan_rule
-A zone_wan_postrouting -m comment --comment "!fw3" -j MASQUERADE
-A zone_wan_prerouting -m comment --comment "!fw3: Custom wan prerouting rule chain" -j prerouting_wan_rule
-A zone_wan_prerouting -p tcp -m tcp --dport 61234 -m comment --comment "!fw3: test-port-fw" -j DNAT --to-destination 10.1.1.123:9090
-A zone_wan_prerouting -p udp -m udp --dport 61234 -m comment --comment "!fw3: test-port-fw" -j DNAT --to-destination 10.1.1.123:9090

```

**Comment by vernesong** [comment]
ipset list localnetwork 有你的公网IP吗， TUN模式默认不会标记发往本地和WAN地址的流量
还有你看看日志的连接记录

**Comment by Mosney** [comment]
> ipset list localnetwork 有你的公网IP吗

有的

**Comment by Mosney** [comment]
> 还有你看看日志的连接记录

是指clash的连接记录么？这种外部的入站流量按理说不会被clash处理的吧

**Comment by vernesong** [comment]
对，如果根本就没进入clash那应该不会影响转发的

**Comment by Mosney** [comment]
> 对，如果根本就没进入clash那应该不会影响转发的

但是实际上开启之后端口转发就失效，只能开着issue蹲同样问题的了

**Comment by xfzha0** [comment]
同样的问题，开tun模式后端口转发失效，但是路由器本身的端口转发没问题

**Comment by bangbang93** [comment]
我也是同样的问题，redir模式正常，tun模式端口转发失效，但是openwrt上的服务都能正常访问到

**Comment by RealKiro** [comment]
- 目前在Fack-ip模式，会影响DDNS域名解析，通过域名+端口（端口转发到NAS）访问失败，通过公网ip+端口（端口转发到NAS）访问正常，关闭OpenClash后转发和域名访问都正常了
![image](https://user-images.githubusercontent.com/33367701/85951595-a30d1d00-b996-11ea-90c6-1607aec40257.png)
![image](https://user-images.githubusercontent.com/33367701/85951603-bcae6480-b996-11ea-8857-014e6c180ea1.png)
![image](https://user-images.githubusercontent.com/33367701/85951613-c768f980-b996-11ea-86c5-25a031e78ed9.png)

![image](https://user-images.githubusercontent.com/33367701/85951661-3a727000-b997-11ea-97cf-91e1f438fedc.png)

- 查阅wiki配置有个奇怪的地方，如果是我配置错了该怎么配置？

**Comment by RealKiro** [comment]
![image](https://user-images.githubusercontent.com/33367701/86306647-69af0880-bc47-11ea-8733-2727aa64ffd1.png)

@vernesong 现在应网友建议：把DDNS解析域名加入了DNS黑名单 后目前正常了

**Comment by vernesong** [comment]
启动后尝试排除一下目标是公网端口的流量
iptables -t mangle -I PREROUTING -p tcp --dport 61234 -j RETURN >/dev/null 2>&1
iptables -t mangle -I PREROUTING -p udp --dport 61234 -j RETURN >/dev/null 2>&1

**Comment by xfzha0** [comment]
新的0.39.3 tun模式端口转发还是不行，网络栈用system的话直接无法访问网络，用gvisor的话可以访问网络但是端口转发不生效

**Comment by bangbang93** [comment]
亲测v0.39.6-beta正常，tun模式，system网络栈，端口转发工作正常，应该可以关闭这个issue了

**Comment by xfzha0** [comment]
确实，0.39.6端口转发正常了

**Comment by passer77** [comment]
v0.45.70-beta又有问题了，家庭网络的nginx proxy manager无法使用，关闭openclash可以瞬间打开nginx proxy manager下的网页。

**Comment by icesk** [comment]
试了下，使用TUN混合模式可以解决该问题。

**Comment by 1836509203** [comment]
已接近，需要的可以问我

**Comment by jimtse93** [comment]
0.46.003-beta 试了下，使用TUN混合模式防火墙转发端口不会失效，IP+端口可以访问，但是用DDNS域名访问失效。关闭就正常

**Comment by zlm324** [comment]
> 已解决，有需要可以问我

你好，我的openclash也遇到了同样的问题，使用TUN模式，会影响端口转发，会导致外网无法访问内网服务器（好像bt下载也受影响）。目前是通过把内网服务器的ip加入黑名单暂时解决的，但加入黑名单后，这台服务器就没办法使用翻墙服务了。还有更好的解决方案吗？

**Comment by zlm324** [comment]
> 0.46.003-beta 试了下，使用TUN混合模式防火墙转发端口不会失效，IP+端口可以访问，但是用DDNS域名访问失效,关闭就正常,覆写设置的DNS设置 里面Fake-IP-Filter列表加入域名，解决

请问TUN混合模式与TUN模式有什么区别？

**Comment by zhouyu732** [comment]
> 已解决，有需要可以问我

大哥，怎么弄，小白一个。currentversion 0.45.7
Fake ip增强模式
