### ISSUE TITLE
OpenClash 回国

### ISSUE THREAD

**Issue by terenceng81** [vernesong/OpenClash#527]
我在新加坡，安装设置完成了软路由以及OpenWRT with OpenClash。

我还在入门阶段，正在寻找可以讨论问题的telegram组群。

我已经付费订阅了机场，也已经审核成功，回得了国。我目前的问题如下：
1. “全局设置”里的“设置自定义规则” （http://192.168.X.X/cgi-bin/luci/admin/services/openclash/client）
和
“Dashboard 控制面板”里的“策略组”（http://192.168.X.X:9090/ui/#/proxies）
这两者有什么不同？是谁覆盖谁呢？

2. 机场提供了一个 yaml 配置文件，我是用这个成功启动OpenClash的，我也开启了“全局设置”>"规则设置"里的“第三方规则“，我选取了”CoenersHua 回国规则“，但我无法更新“第三方规则”，错误为“第三方规则下载失败，请检查网络或稍后再试！”这会造成什么问题呢？

3. 我目前是让其他电脑通过socks5 proxy回国追剧，芒果tv和爱奇艺。虽然成功了，但是必须是在一个ssid里实现，我的理想场景是通过双软路由，ros+openwrt+ubiquiti的 ap，创建两个不同vlan1的ssid，一个ssid用来连接本地网络，另一个ssid为使用openclash里的分流制度，请问能不能请教一些思路，我该怎么实现。

谢谢。
感激不尽！

**Comment by vernesong** [comment]
1.你观察下配置文件的结构就很直观了：
策略组是若干个代理服务器的集合，只负责指定给这个策略组的流量该走哪个节点；

规则就是负责规定哪些流量走哪个策略组，它的结构：
`- DOMAIN,google.com,Proxy 匹配域名(交由Proxy代理服务器组)`

表示匹配这个规则的流量交个名字叫Proxy的策略组，如果配置文件没有一个叫Proxy的策略组，那么就会启动失败。

2.第三方规则下载地址因为作者变更，等待插件版本更新，或者你可以自己编译仓库最新源码

3.不清楚你的设备功能设置高级程度，只说明下原则：
openwrt自身能够上网，下面需要分流的客户端必须是openwrt的设备地址作为网关和DNS

**Comment by terenceng81** [comment]
谢谢您的恢复，我大致上了解，正在消化和学习中。

我想问问，我能不能如下设置，我想从简单开始，只使用自己修改好的yaml配置文件？
1. 全局设置>规则设置>自定义规则>禁用
如果这功能开启，我能直接把规则写在软件的UI里，这里的设置会覆盖自上传文件里的配置，对吗？这里我会设置成“禁用“，因为我想用自修改好的文件上传并使用

2. 全局设置>规则设置>第三方规则>不使用第三方规则 
如果我只想使用自己修改好的yaml配置文件，这第三方规则其实是没必要开启的，对吗？这里我会设置成“不使用第三方规则”

3. 全局设置>第三方规则订阅>禁用
因为我不打算使用其他作者的规则模版，所以这里没必要开启？对吗？这里我会设置成“禁用“。

4. GEOIP数据库订阅，我选择“启用”自动更新，想了解这是什么呢？有必要订阅吗？

5. 服务器于策略组管理>一键生成配置文件>禁用
这里我使用了“禁用”，这是一个通过复制模板然后生成自己的配置文件的功能，对吗？如果我已经写好了自己的配置文件，没必要使用这个，对吗？

6. 配置文件订阅 里如果我开启了订阅机场的配置文件，加上我自己修改的配置文件就有两个了
假设机场的配置文件为 dler.yaml，我修改上传的文件为 nhkclouds.yaml，那么开启了订阅机场的配置文件后，下次自动更新后启动，软件还是会记住并选择我最后切换的配置文件来使用，对吗？

感谢您的解答，见谅我的多问。
Terence

**Comment by vernesong** [comment]
除了订阅，其他几点都关闭就不会影响你的配置文件。
项目wiki里面有解释功能用途，你自己看一遍就明白了

**Comment by terenceng81** [comment]
感谢。
