### ISSUE TITLE
什么都设置好了，提示也没报错就是无法运行

### ISSUE THREAD

**Issue by miaoermua** [vernesong/OpenClash#528]
规则什么的都没有问题，它的提示上面运行了一会又自动关掉了，大概是什么问题求解答

**Comment by 2013108827** [comment]
没有运行记录，我也猜不准为什么无法运行

**Comment by vernesong** [comment]
自动关掉说明你配置文件没写对启动失败，显示是有延迟的

**Comment by miaoermua** [comment]
> 自动关掉说明你配置文件没写对启动失败，显示是有延迟的

 我换了一个路由器试了试安装就出现Package libreadline8 is not available from any configured src
libreadline8不可用，大佬再解答一次麻烦了

**Comment by vernesong** [comment]
编译问题，先执行make clean
