### ISSUE TITLE
疑似bug 看门狗进程不会自动退出 

### ISSUE THREAD

**Issue by Mosney** [vernesong/OpenClash#53]
重启/重载几次openclash就有几个看门狗进程，懒得捉虫了，应该是重启或者重载的时候没有加kill watchdog导致
![image](https://user-images.githubusercontent.com/22477230/67696490-f2531600-f9e1-11e9-883d-671d122efaac.png)

**Comment by vernesong** [comment]
可能你需要测试一下`kill -9`是否正常。
```
watchdog_pids=$(ps |grep openclash_watchdog.sh |grep -v grep |awk '{print $1}' 2>/dev/null)
    for watchdog_pid in $watchdog_pids; do
        kill -9 "$watchdog_pid" >/dev/null 2>&1
    done
```

**Comment by Mosney** [comment]
之后看了看脚本没发现啥问题，也不知道咋搞出来的。等我啥时候再复现再来提交详细过程吧，目前是直接把看门狗启动的部分都注释掉了
