### ISSUE TITLE
升级0.38.9后报错无法启动

### ISSUE THREAD

**Issue by eyaeya** [vernesong/OpenClash#531]
time="2020-06-15T00:27:46+08:00" level=fatal msg="Parse config error: invalid mode"
2020-06-15 00:27:39 OpenClash Can Not Start, Please Check The Error Info And Try Again

**Comment by vernesong** [comment]
重新上传了

**Comment by cnsunyour** [comment]
重新安装后，tun 和 game 模式仍然报相同错误，退回到 0.38.8 ，核心仍然使用最新版本，正常

**Comment by vernesong** [comment]
什么时候更新的

**Comment by cnsunyour** [comment]
昨晚更新报错，刚刚上来看到 issue 后又重新手工上传安装了一遍

**Comment by cnsunyour** [comment]
噢，对了，昨天晚上更新的时候就是只有 tun 和 game 模式出错，普通模式可以运行。

**Comment by vernesong** [comment]
你把配置文件里面fakeip那行删掉就行了

**Comment by cnsunyour** [comment]
没懂，我配置文件是自己写的，每天会定时去远程服务器读取更新配置文件，我的配置里并没有 fake-ip 的行。似乎每次运行时都会进行重新组合配置文件，在组合后的配置文件里貌似有一行 `fake-ip-filter:` ，你是说删掉这一行吗？可下次更新配置的时候不就又有了吗？

**Comment by cnsunyour** [comment]
啊，报告。刚又更新了一次， 这次OK 了

**Comment by cnsunyour** [comment]
啊，又出现了以前出过的情况，重启 OpenWRT 后不能自动运行。报错代理集下载失败：
`2020-06-15 09:54:26 Faild to Download Proxy-Provider File, Please Check The Error Info And Try Again`

**Comment by eyaeya** [comment]
升级0.39.1故障恢复
