### ISSUE TITLE
字体颜色有问题

### ISSUE THREAD

**Issue by OleStore** [vernesong/OpenClash#533]
cgi-bin/luci/admin/services/openclash/config
配置文件
配置文件列表
代理集文件列表
规则集文件列表
一片雪白。。。
![2020-06-15_115116](https://user-images.githubusercontent.com/1283711/84616433-8be22000-aefe-11ea-8f74-c5039c3c6113.jpg)

**Comment by vernesong** [comment]
这里我没有加颜色，你主体的问题

**Comment by OleStore** [comment]
稍后换个主题看看
