### ISSUE TITLE
更新0.38.9后，ConnersHua规则把部分apple服务走proxy里了，“apple“策略组也不见了

### ISSUE THREAD

**Issue by xpn282** [vernesong/OpenClash#534]
<img width="1000" alt="截屏2020-06-15 下午2 25 27" src="https://user-images.githubusercontent.com/53807602/84628391-205a7b80-af1b-11ea-9001-67e982615079.png">

以前策略组有一项“apple”策略组，现在没有了。
现在部分apple服务被强制走proxy了，我不需要苹果服务走代理，要怎么弄呢？能不能把“apple”策略组恢复啊？

**Comment by vernesong** [comment]
人家是这么维护的我管不了，你可以尝试用ruleprovider

**Comment by Apocalypsor** [comment]
你自己弄个apple的策略组不就完事了
