### ISSUE TITLE
路由器重启后openclash没法自动启动

### ISSUE THREAD

**Issue by yang05130** [vernesong/OpenClash#535]
显示

错误: 代理集文件下载失败，请到日志页面查看详细错误信息！
--

重新点下启动按钮就可以正常启动，是什么问题导致的呢

**Comment by vernesong** [comment]
更新了没

**Comment by yang05130** [comment]
更新到0.38.9的了，在477那看到要替换新的openclash，也是没用

**Comment by vernesong** [comment]
发一下你的provider配置，看看怎么写的

**Comment by yang05130** [comment]
我的配置文件里没有写provider

**Comment by yang05130** [comment]
替换新的openclash进去后，重启路由器能正常启动了
