### ISSUE TITLE
openclash 测速跑不满

### ISSUE THREAD

**Issue by MOOnLyer** [vernesong/OpenClash#537]
openclash 开启直连 测速跑不满 只能到80左右
CPU占用没满
试过fake-ip和 redir 都不行

**Comment by TravelC** [comment]
我这边测试 tun 跑不满，也是 80 左右，普通模式正常，100M 宽带。

**Comment by hcym** [comment]
一直用的普通核普通模式，不错，今天的版本正常跑满

**Comment by MOOnLyer** [comment]
我升级了39.2 这依旧不行啊 300M 宽带 求一份设置图看看

**Comment by hcym** [comment]
大条啦，不能关，今天关闭后完全没有网络，呵呵😄

**Comment by yang05130** [comment]
我用的游戏内核也是，只能跑一半
