### ISSUE TITLE
General-Settings fake-ip部分冗余配置

### ISSUE THREAD

**Issue by xuhuanxxx** [vernesong/OpenClash#544]
调试信息：
![image](https://user-images.githubusercontent.com/4946617/85082702-4aa18700-b202-11ea-8a03-d5049b9067d7.png)

订阅文件配置：
![image](https://user-images.githubusercontent.com/4946617/85082445-7bcd8780-b201-11ea-8878-1533bbc3cb80.png)

调试文件配置：
![image](https://user-images.githubusercontent.com/4946617/85082580-f0a0c180-b201-11ea-9020-3caecaaa9dc8.png)

原本被注释掉的   fake-ip-range 被多处理了一次，Custom fake-ip-filter也被多设置了一次。

**Comment by xuhuanxxx** [comment]
感谢，已验证有效。

**Comment by OleStore** [comment]
这个bug修复后，贼稳定

**Comment by xuhuanxxx** [comment]
> 这个bug修复后，贼稳定

虽然有这两处多余的配置，但是有时候竟然也能启动😂
