### ISSUE TITLE
分流排序的问题

### ISSUE THREAD

**Issue by QuteSaltyFish** [vernesong/OpenClash#548]
开发者你好，我觉得发现了问题就是，在选择流媒体节点的时候，可能直接使用url-test进行排序不能反映出其真实水平，比如很多节点延迟低，但是其带宽小，不知道有没可能开发根据连接带宽的排序方式，普通浏览网页就使用url-test，选择流媒体就使用带宽的方式。

**Comment by vernesong** [comment]
什么服务器有什么宽带没有办法获取。
现在是可以记住你的策略组选择，日常浏览的网页你用自动就好，流媒体的策略组一般是select，你手动选择好后一般不会变化。
如果没有流媒体策略组，你可以在服务器与策略组管理页面先读取你的配置文件，然后用模板一键生成，这样以后订阅会自动保留模板的策略组和规则，只会更新节点信息，如果更新后名字变了或者节点失效了你才需要重新指定。
