### ISSUE TITLE
配置后一直无法启动。。

### ISSUE THREAD

**Issue by asnon** [vernesong/OpenClash#55]
OPENWRT 3215U
错误日志为time="2019-10-30T23:57:03+08:00" level=fatal msg="Parse config error: ProxyGroup Auto - UrlTest: key 'proxies' missing"
求大神指点~

**Comment by asnon** [comment]
> 如果没有机场托管，请使用配置文件一键生成

我就是用一键生成的配置文件呢

**Comment by vernesong** [comment]
![image](https://user-images.githubusercontent.com/42875168/67943693-9375e280-fc15-11e9-89fa-7dcfaa5b6a91.png)
版本v0.35.4-beta，测试正常
