### ISSUE TITLE
DNS与ipv6

### ISSUE THREAD

**Issue by bleeee** [vernesong/OpenClash#552]
请教一下dns和ipv6的问题，配置如下

> `dns:

  enable: true
  ipv6: true
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874
##Custom DNS##
  nameserver:
  - 202.99.104.68
  - 202.99.96.68
  fallback:
  - 192.168.1.25
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4 `

Fallback用的内网搭建的dnscrypt，屏蔽ipv6
这种情况下，www.google.com返回了正确的v4地址和错误的v6地址，错误的v6地址是不是因为现在程序尚未对2001:0:ffff类的地址做识别，导致匹配上了geoip？

**Comment by vernesong** [comment]
v6私有地址目前我没有往iptables里面加，其他的则需要配置文件里面的规则去判断，没有V6规则的话自然就到geoip了

**Comment by bleeee** [comment]
> v6私有地址目前我没有往iptables里面加，其他的则需要配置文件里面的规则去判断，没有V6规则的话自然就到geoip了

raw.githubusercontent.com 在多数地区被污染到了::

**Comment by vernesong** [comment]
如果一定要redir，那么dns用doh

**Comment by bleeee** [comment]
> 如果一定要redir，那么dns用doh

谢谢，tcp类型的其他方式不可以么？
Fake ip主要担心不能返回国内的正常ipv6地址

**Comment by vernesong** [comment]
tcp也可以，效果需要你自己去测试
