### ISSUE TITLE
FakeIP模式下的广告拦截问题

### ISSUE THREAD

**Issue by AnthonyZhai** [vernesong/OpenClash#553]
**目前的拓扑是：**
**openclash-》adguard home-》smartdns**
openclash：FakeIP模式
adguard home：添加了HalfLife规则：ads.youtube.com重定向到127.0.0.1
smartdns：两个DNS服务器都开启，国内外DNS分组后分别绑定到6053和7053端口，两个端口同时作为adguard的上游服务器。

**问题**
这样的结构下无法拦截HalfLife里的ads.youtube.com请求（不是放行或者怎么样），而是在查询日志里根本就没有关于youtube的任何记录，但是仍然可以拦截腾讯视频的一些广告。
**暂时解决方式**
目前，将openclash改为Host-Redir模式就可以解决，但是速度就会慢很多。或者将拓扑改为adguard home-》openclash-》smartdns也可以解决。

请问，这样的问题是什么原因？

**Comment by hehehehehaha** [comment]
因为在 Fake IP 模式下匹配到需要走代理的规则后，会将 DNS 请求直接交给远端代理服务器处理，不经过 Clash 中的上游 DNS 服务器。

**Comment by CORE2021** [comment]
fake ip不可以用自己的dns啊

**Comment by AnthonyZhai** [comment]
那么这种情况下，该如何处理呢？
1）adguardHome作为最下游DNS吗？
2）不想切换Redir模式，一说慢就不想用了

**Comment by CORE2021** [comment]
> 那么这种情况下，该如何处理呢？
> 1）adguardHome作为最下游DNS吗？
> 2）不想切换Redir模式，一说慢就不想用了

最下游，没错。
我用没有fake ip的ssrplus没觉得慢，你是有游戏需求吗

**Comment by CORE2021** [comment]
fake ip好像都是返回假IP啊，那直接配置文件去广告好了吧

**Comment by zzcabc** [comment]
> > 那么这种情况下，该如何处理呢？
> > 1）adguardHome作为最下游DNS吗？
> > 2）不想切换Redir模式，一说慢就不想用了
> 
> 最下游，没错。
> 我用没有fake ip的ssrplus没觉得慢，你是有游戏需求吗

你好,我想请问一下adg如何在fake-ip模式下设置最下游
