### ISSUE TITLE
开启后智能猫眼就无法连接服务器

### ISSUE THREAD

**Issue by Suidge** [vernesong/OpenClash#557]
用的是鹿客的智能猫眼。打开openclash就无法连接服务器，fake-ip/redir-host切换也没用。已经设了猫眼IP直连，也无效。不知道什么问题。

**Comment by vernesong** [comment]
观察日志看域名走什么规则，实在不行切换redir模式用全局设置里的访问控制排除设备流量

**Comment by Suidge** [comment]
奇怪的是 已经设了排除设备流量，全部direct了。但是无效。

**Comment by vernesong** [comment]
![image](https://user-images.githubusercontent.com/42875168/85922406-8a790600-b8b5-11ea-87dc-36d6a23952df.png)

**Comment by Suidge** [comment]
感谢大大回复。但是为啥我的界面跟你的不一样。没有这个选项啊。我用的openclash最新版。
![D8552773-1955-4033-943F-67221A30F97F](https://user-images.githubusercontent.com/34770064/85922526-a5984580-b8b6-11ea-8428-297ee3ed9963.png)
![5FAB2614-4FC3-4DD4-B4F6-8A69D787958E](https://user-images.githubusercontent.com/34770064/85922529-a7620900-b8b6-11ea-97e2-973fb93c9844.png)

**Comment by vernesong** [comment]
模式设置redirhost，页面操作设置切换到redirhost

**Comment by Suidge** [comment]
相当奇怪 还是不行

**Comment by Suidge** [comment]
原因查到了 猫眼的app连了一个growingio.com 大数据跟踪网站 被clash预算配置拦截

**Comment by Suidge** [comment]
谢谢大大回复 打搅了
