### ISSUE TITLE
fallback组的dns请求会遵循分流规则吗？

### ISSUE THREAD

**Issue by yuerongz97** [vernesong/OpenClash#558]
![image](https://user-images.githubusercontent.com/18389778/85875124-54307d80-b806-11ea-9ac4-ddfb7cccad74.png)
1. 如题，请问在redirhost兼容模式下，对境外dns的请求是直连还是依据分流规则呢？如果是依据分流规则的话，正常情况下是应该设置为直连还是走代理呢？
2. 请问redirhost兼容模式下，如果需要通过代理进行访问的域名或者IP，openclash是将域名发送给代理服务器还是发送ip地址呢？

**Comment by vernesong** [comment]
redirhost跟ssp+这些一样，都是本地直连请求国内外dns，直接发ip给代理服务器

**Comment by yuerongz97** [comment]
本地直连请求国外dns，然后再发送ip给代理服务器，那dns返回的ip对于代理服务器来说不是最优值把？

**Comment by CORE2021** [comment]
这样就不满足大雕说的就近性原则了

**Comment by vernesong** [comment]
一般流媒体dns解锁要用fakeip，其他的看你自己的使用体验

**Comment by yuerongz97** [comment]
![image](https://user-images.githubusercontent.com/18389778/85983262-c4631d00-ba19-11ea-9763-ca3cf36ee6d4.png)
大佬 我在Fndroid的wiki页面中好像看到，redir-host模式下是发送域名给代理服务器的。

来源：https://github.com/Fndroid/clash_for_windows_pkg/wiki/DNS%E6%B1%A1%E6%9F%93%E5%AF%B9Clash%EF%BC%88for-Windows%EF%BC%89%E7%9A%84%E5%BD%B1%E5%93%8D

**Comment by vernesong** [comment]
这里是指ip，dns解析过后的
