### ISSUE TITLE
在每次编译更新后会掉自定义规则

### ISSUE THREAD

**Issue by jerryliang122** [vernesong/OpenClash#559]
自从0.36开始，每次编译更新openclsh就会掉自定义规则

**Comment by vernesong** [comment]
什么情况下会掉，说清楚

**Comment by jerryliang122** [comment]
就是，我是用github的actions编译的openwrt，在每次刷写新的固件后，自定义规则就会重置

**Comment by vernesong** [comment]
https://github.com/vernesong/OpenClash/issues/435
