### ISSUE TITLE
部署后，发现局域网内的设备通过动态域名加端口转发访问局域网的其他设备会ERR_CONNECTION_RESET

### ISSUE THREAD

**Issue by yanyingjie007** [vernesong/OpenClash#56]
部署后，一切都好

就是发现局域网内的电脑，访问以动态域名加端口的地址，该地址映射到同一局域网段的其他设备，会出现ERR_CONNECTION_RESET，从外网访问该地址可以访问，这个如何解决？

**Comment by vernesong** [comment]
域名解析出来的ip是否正常

**Comment by yanyingjie007** [comment]
> 域名解析出来的ip是否正常

解析的域名完全正常，外网访问一切OK，内网访问不行，搞不明白，才来求问

平台koolshare LEDE V2.33, OPENCLASH版本：v0.35.4-beta
托管是dler

如果需要更多信息，请回复。我将提供

**Comment by vernesong** [comment]
fakeip？

**Comment by yanyingjie007** [comment]
> fakeip模式的话，你需要把域名加到DNS设置里-高级设置里的名单里
> redir模式应该不会有问题

感谢解答，问题已经解决
