### ISSUE TITLE
本地DNS劫持 停用后能否不修改 Dnsmasq 的 DNS转发 设置？

### ISSUE THREAD

**Issue by ATErBion** [vernesong/OpenClash#560]
硬件 Phicomm N1 5.7.2-flippy-37+

OpenClash 【Dev分支】内核版本 premium-29-g99b34e8 客户端 v0.39.2-beta

问题描述：
因为需要 Dnsmasq 来转发特定内部域名的请求到内网的域名服务器，通过设置 OP 的 DNS 转发 来实现
例如：
```
/xxx.local/192.168.168.0.55
/yyy.local/192.168.168.0.56
127.0.0.1#7874
#此时内网DNS和科学上网均正常
```

如果开启 OpenClash 的 本地DNS劫持，会触发自动删除所有 Dnsmasq 的自定义 DNS 转发，只保留“127.0.0.1#7874”一项，
DNS 转发被修改如下：
```
127.0.0.1#7874
#此时科学上网正常，内网DNS不正常
```

但是如果关闭 OpenClash 的 本地DNS劫持，每次启动或关闭 OpenClash 时，均会触发自动删除“127.0.0.1#7874”此项，其他自定义转发正常保留，DNS 转发被修改如下：
```
/xxx.local/192.168.168.0.55
/yyy.local/192.168.168.0.56
#此时内网DNS正常，科学上网不正常
```

我理解默认行为是为了方便新手使用，但是选择了停用本地 OpenClash 的 本地DNS劫持 ，OpenClash 还是会修改 Dnsmasq 的 DNS转发 设置，这个行为很困扰，能否通过修改配置文件或者提供一个选项彻底关闭这个行为？

**Comment by vernesong** [comment]
意思是停用后不删除127.0.0.1#7874？

**Comment by ATErBion** [comment]
> 意思是停用后不删除127.0.0.1#7874？

是的

**Comment by ATErBion** [comment]
启动时会触发的改写：

本地DNS劫持：启用
 Dnsmasq 的 DNS转发 清空，添加一项127.0.0.1#7874

本地DNS劫持：禁用
 Dnsmasq 的 DNS转发 不改变现状，删除127.0.0.1#7874

如果去掉自动删除会造成小白困扰的话，能否提供一个选项（或通过修改配置文件），允许不改写Dnsmasq 的 DNS转发 设置 ^_^

**Comment by RUI98** [comment]
另一个clash可以满足
