### ISSUE TITLE
为系统代理是添加这个配置吗？

### ISSUE THREAD

**Issue by gitelia** [vernesong/OpenClash#566]
system-proxy: true
下面这个打不开
![image](https://user-images.githubusercontent.com/44855037/86372661-12e01800-bcb5-11ea-99cd-2ca562aa4e38.png)

**Comment by icolourful** [comment]
你自己在系统代理设置里添加ip和端口号
![}QT1~HP%QSY H~KD`Y9 F O](https://user-images.githubusercontent.com/67251621/86432930-def40980-bd2b-11ea-9839-0c11b0ec505c.png)

**Comment by gitelia** [comment]
> 你自己在系统代理设置里添加ip和端口号
> ![} QT1HP％QSY HKD`Y9 FO](https://user-images.githubusercontent.com/67251621/86432930-def40980-bd2b-11ea-9839-0c11b0ec505c.png)
这个我是知道的，我是想让openclash接管路由本身所有流量。
