### ISSUE TITLE
openclash 做为旁路由 设置成网关无法翻墙 设置成系统代理却可以使用

### ISSUE THREAD

**Issue by baijincaomei** [vernesong/OpenClash#568]
主路由是10.0.0.1    
软路由1 openclash                   做为旁路由1     设置成10.0.0.21  
软路由2 ShadowsocksR Plus+  做为旁路由2     设置成10.0.0.31 
两个软路由网关均为10.0.0.1
两个软路由代理都开着
客户端用10.0.0.21 作为网关 DNS设置成10.0.0.31  nslookup解析google 油管能返回IP  无法翻墙  设置成系统代理却能正常浏览油管
使用10.0.0.31在任何客户端上作为网关与DNS时 均能正常使用
百思不得其解 那位大能急救下

**Comment by baijincaomei** [comment]
openclash调试日志
OpenClash 调试日志

生成时间: 2020-07-03 21:56:22
插件版本: v0.39.2-beta

#===================== 系统信息 =====================#
主机型号: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz : 2 Core 4 Thread
固件版本: OpenWrt 19.07-SNAPSHOT r11265-ae01f3dc98
LuCI版本: git-627283a-1
内核版本: 4.14.180
处理器架构: x86_64

#此项在使用Tun模式时应为ACCEPT
防火墙转发: ACCEPT

#此项有值时建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: 

#此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 127.0.0.1#7874

#===================== 依赖检查 =====================#
dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
jsonfilter: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
iptables-mod-tproxy: 已安装
kmod-tun(TUN模式): 已安装
luci-compat(Luci-19.07): 已安装

#===================== 内核检查 =====================#
运行状态: 运行中
已选择的架构: linux-amd64

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 2020.06.15.gbf68156
Tun内核文件: 存在
Tun内核运行权限: 正常

Game内核版本: v0.17.0-132-g3a53a25
Game内核文件: 存在
Game内核运行权限: 正常

Dev内核版本: v0.20.02
Dev内核文件: 存在
Dev内核运行权限: 正常

#===================== 插件设置 =====================#
当前配置文件: /etc/openclash/config/BigHead.yaml
运行模式: redir-host
默认代理模式: Rule
UDP流量转发: 停用
DNS劫持: 启用
自定义DNS: 停用
IPV6-DNS解析: 停用
禁用Dnsmasq缓存: 停用
自定义规则: 停用
仅允许内网: 停用
仅代理命中规则流量: 停用

#启动异常时建议关闭此项后重试
保留配置: 停用
第三方规则: 停用

#===================== 配置文件 =====================#
port: 7890
socks-port: 7891
allow-lan: true
bind-address: "*"
ipv6: false
mode: Rule
log-level: silent
external-controller: 0.0.0.0:9090
redir-port: 7892
secret: "123456"
external-ui: "/usr/share/openclash/dashboard"
hosts:
##Custom HOSTS##
#  experimental hosts, support wildcard (e.g. *.clash.dev Even *.foo.*.example.com)
#  static domain has a higher priority than wildcard domain (foo.example.com > *.example.com)
#  NOTE: hosts don't work with `fake-ip`

#  '*.clash.dev': 127.0.0.1
#  'alpha.clash.dev': '::1'
##Custom HOSTS END##
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 127.0.0.1:7874
  fake-ip-filter:
  nameserver:
  - 114.114.114.114
  fallback:
  - tls://8.8.8.8:853
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4

#===================== 防火墙设置 =====================#

#NAT chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    REDIRECT   tcp  --  0.0.0.0/0            8.8.4.4              redir ports 7892
2    REDIRECT   tcp  --  0.0.0.0/0            8.8.8.8              redir ports 7892
3    prerouting_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom prerouting rule chain */
4    zone_lan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
5    openclash  tcp  --  0.0.0.0/0            0.0.0.0/0           
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         

#Mangle chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         

#===================== 路由表状态 =====================#
#route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.0.0.1        0.0.0.0         UG    0      0        0 br-lan
10.0.0.0        0.0.0.0         255.255.255.0   U     0      0        0 br-lan
#ip route list
default via 10.0.0.1 dev br-lan proto static 
10.0.0.0/24 dev br-lan proto kernel scope link src 10.0.0.21 
#ip rule show
0:	from all lookup local 
32766:	from all lookup main 
32767:	from all lookup default 

#===================== 端口占用状态 =====================#
tcp        0      0 :::9090                 :::*                    LISTEN      21856/clash
tcp        0      0 :::7890                 :::*                    LISTEN      21856/clash
tcp        0      0 :::7891                 :::*                    LISTEN      21856/clash
tcp        0      0 :::7892                 :::*                    LISTEN      21856/clash
udp        0      0 127.0.0.1:7874          0.0.0.0:*                           21856/clash
udp        0      0 :::7891                 :::*                                21856/clash
udp        0      0 :::7892                 :::*                                21856/clash

#===================== 测试本机DNS查询 =====================#
Server:		127.0.0.1
Address:	127.0.0.1#53

Name:      www.baidu.com
www.baidu.com	canonical name = www.a.shifen.com
Name:      www.a.shifen.com
Address 1: 180.101.49.12
Address 2: 180.101.49.11
*** Can't find www.baidu.com: No answer

#===================== 测试本机网络连接 =====================#
HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: private, no-cache, no-store, proxy-revalidate, no-transform
Connection: keep-alive
Content-Length: 277
Content-Type: text/html
Date: Fri, 03 Jul 2020 13:56:22 GMT
Etag: "575e1f60-115"
Last-Modified: Mon, 13 Jun 2016 02:50:08 GMT
Pragma: no-cache
Server: bfe/1.0.8.18


#===================== 测试本机网络下载 =====================#
HTTP/1.1 200 Connection established

HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 78
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: text/plain; charset=utf-8
ETag: "2634120e33207f655153900e2398f5f93cf299cb681c51c8437b6c5c3863e805"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
Via: 1.1 varnish (Varnish/6.0)
X-GitHub-Request-Id: B1F6:032D:24181:2A353:5EFF34C3
Accept-Ranges: bytes
Date: Fri, 03 Jul 2020 13:56:23 GMT
Via: 1.1 varnish
X-Served-By: cache-hkg17929-HKG
X-Cache: MISS, HIT
X-Cache-Hits: 0, 3
X-Timer: S1593784583.468780,VS0,VE0
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
X-Fastly-Request-ID: 54854de6ee5de7e27a0f7a7904b716050100cd07
Expires: Fri, 03 Jul 2020 14:01:23 GMT
Source-Age: 273


#===================== 最近运行日志 =====================#
time="2020-07-03T21:09:10+08:00" level=info msg="Start initial compatible provider 📲 电报信息"
time="2020-07-03T21:09:10+08:00" level=info msg="Start initial compatible provider 🌍 国外媒体"
time="2020-07-03T21:09:10+08:00" level=info msg="Start initial compatible provider 🌏 国内媒体"
time="2020-07-03T21:09:10+08:00" level=info msg="Start initial compatible provider 🎯 全球直连"
time="2020-07-03T21:09:10+08:00" level=info msg="Start initial compatible provider Ⓜ️ 微软服务"
time="2020-07-03T21:09:10+08:00" level=info msg="Start initial compatible provider 🛑 全球拦截"
time="2020-07-03T21:09:10+08:00" level=info msg="Start initial compatible provider 🍎 苹果服务"
time="2020-07-03T21:09:10+08:00" level=info msg="Start initial compatible provider 🔰 节点选择"
time="2020-07-03T21:09:10+08:00" level=info msg="Start initial compatible provider 🐟 漏网之鱼"
2020-07-03 21:09:08 OpenClash Start Successful

**Comment by eggydutch** [comment]
不明白你为何设置Openclash为网关时为何要用SSR+旁路由IP做DNS？如果说是为了防止DNS污染的话Openclash也可以做到。
设系统代理为Openclash旁路时应该是用的HTTP代理吧？那么系统的DNS请求应该就会直接走Openclash旁路由故此时就正常。
综上，你的DNS请求没有正确走Openclash网关所以不能正常留学。

**Comment by eggydutch** [comment]
> 主路由是10.0.0.1
> 软路由1 openclash 做为旁路由1 设置成10.0.0.21
> 软路由2 ShadowsocksR Plus+ 做为旁路由2 设置成10.0.0.31
> 两个软路由网关均为10.0.0.1
> 两个软路由代理都开着
> 客户端用10.0.0.21 作为网关 DNS设置成10.0.0.31 nslookup解析google 油管能返回IP 无法翻墙 设置成系统代理却能正常浏览油管
> 使用10.0.0.31在任何客户端上作为网关与DNS时 均能正常使用
> 百思不得其解 那位大能急救下

不明白你为何设置Openclash为网关时为何要用SSR+旁路由IP做DNS？如果说是为了防止DNS污染的话Openclash也可以做到。
设系统代理为Openclash旁路时应该是用的HTTP代理吧？那么系统的DNS请求应该就会直接走Openclash旁路由故此时就正常。
综上，你的DNS请求没有正确走Openclash网关所以不能正常留学。

**Comment by baijincaomei** [comment]
使用openclash或者任何公网地址做DNS也不能留学 应该不是DNS的问题

eggydutch <notifications@github.com> 于2020年7月6日周一 上午4:51写道：

**Comment by deepfish** [comment]
我反而遇到跟你相反的問題。

我設置了雙路由，主路由為 10.0.0.1（ikuai），旁置網關10.0.0.251（openwrt），但是我發現無論電腦是否設置網關為 10.0.0.251 ，流量都會走到 openclash 那裡去。「我在 openclash 中設定 - SRC-IP-CIDR, 10.0.0.101/32,DIRECT ，其實流量還是走到了 openclash 那」

現在想某些 IP 的流量完全不經過 openclash，但是不知道怎麼弄，是不是要改路由表？

**Comment by threebowrice** [comment]
> 主路由是10.0.0.1
> 软路由1 openclash 做为旁路由1 设置成10.0.0.21
> 软路由2 ShadowsocksR Plus+ 做为旁路由2 设置成10.0.0.31
> 两个软路由网关均为10.0.0.1
> 两个软路由代理都开着
> 客户端用10.0.0.21 作为网关 DNS设置成10.0.0.31 nslookup解析google 油管能返回IP 无法翻墙 设置成系统代理却能正常浏览油管
> 使用10.0.0.31在任何客户端上作为网关与DNS时 均能正常使用
> 百思不得其解 那位大能急救下

请问楼主后来解决这个问题了吗？

**Comment by Dabrit** [comment]
我也遇到了这个问题 ，请问楼主解决了吗

**Comment by songyaojie** [comment]
我有同样的问题，同问楼主是否解决了？

**Comment by Dabrit** [comment]
> 我有同样的问题，同问楼主是否解决了？

https://github.com/vernesong/OpenClash/issues/1993

我遇到同样问题，这是我的解决方法
基本上是ipv6优先级的问题，需要手动指定ipv6网关和dns。

**Comment by songyaojie** [comment]
> > 我有同样的问题，同问楼主是否解决了？
> 
> #1993
> 
> 我遇到同样问题，这是我的解决方法 基本上是ipv6优先级的问题，需要手动指定ipv6网关和dns。


多谢答复，我路由器设置里面已经关闭了ipv6的所有设置，还需要在openclash里面设置ipv6的网关和dns吗？能否指点详细一点？

**Comment by Dabrit** [comment]
> > > 我有同样的问题，同问楼主是否解决了？
> > 
> > 
> > #1993
> > 我遇到同样问题，这是我的解决方法 基本上是ipv6优先级的问题，需要手动指定ipv6网关和dns。
> 
> 多谢答复，我路由器设置里面已经关闭了ipv6的所有设置，还需要在openclash里面设置ipv6的网关和dns吗？能否指点详细一点？

如果是旁路由配置的，关闭旁路由ipv6我不知道能不能解决问题。你可以选择手动在windows中配置ipv6网关和dns,或直接在拨号的主路由中关闭ipv6,之后openclash的ipv6关不关都可以

**Comment by lvxiangying** [comment]
> 我反而遇到跟你相反的問題。
> 
> 我設置了雙路由，主路由為 10.0.0.1（ikuai），旁置網關10.0.0.251（openwrt），但是我發現無論電腦是否設置網關為 10.0.0.251 ，流量都會走到 openclash 那裡去。「我在 openclash 中設定 - SRC-IP-CIDR， 10.0.0.101/32，DIRECT ，其實流量還是走到了 openclash 那」
> 
> 現在想某些 IP 的流量完全不經過 openclash，但是不知道怎麼弄，是不是要改路由表？

请问你解决了吗?
