### ISSUE TITLE
fakeIP模式下的两个问题，访问控制&openvpn

### ISSUE THREAD

**Issue by SinTod** [vernesong/OpenClash#57]
问题一：
在fakeip模式下由于所有域名解析都由clash返回fakeip，所以导致配置的openvpn域名也返回了198网段的ip导致连接失败。（临时修改配置文件为IP解决），问下这种情况有没有办法使用配置解决？

问题二：
访问控制问题，之前koolss的访问控制功能 比如某个主机不走代理，现在openclash可以通过SRC-IP-CIDR配置实现，但是之前的只代理端口这个功能可否用配置实现呢？想实现80,443端口根据规则判断，其他端口直连，看了文档找到了下面两个配置。
##- DST-PORT,80,DIRECT 匹配数据目标端口(直连)
##- SRC-PORT,7777,DIRECT 匹配数据源端口(直连)
这两个配置可以实现对端口的配置，不过我想设置非80,443的话是要把所有端口都生成一条规则么。这样的话配置可能要上万条。。。
btw，数据目标端口和数据源端口不太清楚什么意思，请问可以帮忙解释下吗 谢谢啦~

**Comment by vernesong** [comment]
第一个需求你可以去DNS设置-高级设置里面添加域名
第二个需求目前还无法直接实现，但你可以在使用第三方规则的基础上，将国内流量和未匹配到规则的流量设置为直连DIRECT，因为规则中基本都是域名规则，不太可能导致非必须流量代理。
![image](https://user-images.githubusercontent.com/42875168/68080641-7e2dcd80-fe3a-11e9-9797-a2255385b18e.png)

**Comment by SinTod** [comment]
谢谢~

**Comment by sarkrui** [comment]
请问fakeip模式下，是否支持端口段自定义规则(访问控制)呢？
比如我想要指定了端口`50001 直连`
那我可以使用
```
- SRC-PORT,50001,DIRECT
```
假如我想要 `50000 - 51000`端口全部直连，请问可以怎么设置呢？
谢谢！！

**Comment by vernesong** [comment]
这个需要script模式，写规则脚本，或者redir模式，用ipset把端口加到commonport列表里去
