### ISSUE TITLE
订阅时如何只更新服务器节点

### ISSUE THREAD

**Issue by wclmgcd** [vernesong/OpenClash#570]
买的机场，订阅时更新服务器节点还更新了配置文件
rules:
- DOMAIN-SUFFIX,asiacomics.com,Proxy这些内容，导致不能启动，
我是用的自己修改的，如何才能使用订阅时如何只更新服务器节点

**Comment by icolourful** [comment]
我添加了规则也不走代理。。。
你试试自定义规则(访问控制)这里添加吧

**Comment by ATErBion** [comment]
我的方法是把机场节点放到Proxy Provider里面去更新

**Comment by wclmgcd** [comment]
> 我的方法是把机场节点放到Proxy Provider里面去更新

那个设置？
