### ISSUE TITLE
记录选中节点

### ISSUE THREAD

**Issue by Synchronized1** [vernesong/OpenClash#574]
请问能否实现一个功能:
   在每次重启openclash后,依然选中重启前的节点?
   也就是记录重启前所有策略已选中的节点

**Comment by vernesong** [comment]
这个功能已经有了啊，请更新

**Comment by Synchronized1** [comment]
在koolshare Lede系统下
使用0.39.2-beta版,当我修改完配置文件->重新上传->重启openclash->打开yacd面板
此时每个策略组依然选择默认第一个节点..没有实现记录功能,难道跟系统有关?

**Comment by Synchronized1** [comment]
场景复现:
   1.选择节点
         
![image](https://user-images.githubusercontent.com/58451554/87222540-d4c6b080-c3a6-11ea-9357-21cf086661ac.png)
    2.此时history下对应的文件记录也会发生变化
         
    ![image](https://user-images.githubusercontent.com/58451554/87222545-e90aad80-c3a6-11ea-8670-e277792b6aeb.png)
  
   ![image](https://user-images.githubusercontent.com/58451554/87222556-0c355d00-c3a7-11ea-887d-72a33eb1760e.png)

   3.但是再重启openclash之后并没有读取之前记录的选中节点,而是又恢复原装
      
     ![image](https://user-images.githubusercontent.com/58451554/87222564-2cfdb280-c3a7-11ea-8dd9-4c4b492a1d8d.png)
     
    ![image](https://user-images.githubusercontent.com/58451554/87222578-4a328100-c3a7-11ea-89dc-10333e846f44.png)
    
   ![image](https://user-images.githubusercontent.com/58451554/87222581-54ed1600-c3a7-11ea-8f5b-a740442bae43.png)

   有可能作者您不是根据history这个文件夹来实现的节点记录,如果有错误的地方辛苦指正!

**Comment by vernesong** [comment]
单独运行/usr/share/openclash/openclash_history_set.sh找找问题

**Comment by Quzard** [comment]
实测，在openclash启动 history 会变回 direct（第一个节点）
