### ISSUE TITLE
Clash核心版本问题

### ISSUE THREAD

**Issue by eggydutch** [vernesong/OpenClash#575]
现在OpenClash最新核心版本显示为premium-29-g99b34e8，原生Clash和隔壁luici-for-clash的核心版本已经更新到v1.0.0（重大版本更新）。

想问问现在OpenClash的核心相当于原生Clash的哪个版本？有更新到最新v1.0.0的日程安排吗？感谢作者！

**Comment by adamw92** [comment]
你可以直接去下载clash最新的内核然后按照openclash的内核命名方式放到指定位置

**Comment by OleStore** [comment]
消失14天。。。

**Comment by eggydutch** [comment]
> 你可以直接去下载clash最新的内核然后按照openclash的内核命名方式放到指定位置

原生clash的内核也适用在OpenClash上吗？

**Comment by eggydutch** [comment]
> 消失14天。。。

什么意思？

**Comment by RunStar99** [comment]
版本号最后7位对应上游clash核心的commitID, openclash跟的dev分支核心自编译内核, 早就有了V1.0版所有特性. 
日常维护的版本也是跟随commit,  实际比clash仓库的release编译版本超前

**Comment by eggydutch** [comment]
> 版本号最后7位对应上游clash核心的commitID, openclash跟的dev分支核心自编译内核, 早就有了V1.0版所有特性.
> 日常维护的版本也是跟随commit, 实际比clash仓库的release编译版本超前

那意思是现在openclash的核心版本比原生v1.0.0正式版还超前？

**Comment by RunStar99** [comment]
> > 版本号最后7位对应上游clash核心的commitID, openclash跟的dev分支核心自编译内核, 早就有了V1.0版所有特性.
> > 日常维护的版本也是跟随commit, 实际比clash仓库的release编译版本超前
> 
> 那意思是现在openclash的核心版本比原生v1.0.0正式版还超前？

是啊, 比如clash官方仓库在6月27号发布的v1.0.0版中新增的“tolerance for url-test”, 这个参数早在5月29号中的commits 5628f97就发布了.  
<img width="1575" alt="截屏2020-07-09 22 18 00" src="https://user-images.githubusercontent.com/46420475/87051395-184bde00-c232-11ea-859b-0b16d21d144b.png">

**Comment by eggydutch** [comment]
> > > 版本号最后7位对应上游clash核心的commitID, openclash跟的dev分支核心自编译内核, 早就有了V1.0版所有特性.
> > > 日常维护的版本也是跟随commit, 实际比clash仓库的release编译版本超前
> > 
> > 
> > 那意思是现在openclash的核心版本比原生v1.0.0正式版还超前？
> 
> 是啊, 比如clash官方仓库在6月27号发布的v1.0.0版中新增的“tolerance for url-test”, 这个参数早在5月29号中的commits 5628f97就发布了.
> <img alt="截屏2020-07-09 22 18 00" width="1575" src="https://user-images.githubusercontent.com/46420475/87051395-184bde00-c232-11ea-859b-0b16d21d144b.png">

好的，感谢哥，这个还真不懂。这样看来Open clash应该是短期内不会再有新的核心版本更新了吧？

**Comment by vernesong** [comment]
新内核不兼容老配置，等段时间大家过渡好了再说

**Comment by eggydutch** [comment]
> 新内核不兼容老配置，等段时间大家过渡好了再说

好的，谢谢哥
