### ISSUE TITLE
在luci-nginx中启动时会卡死

### ISSUE THREAD

**Issue by maskedeken** [vernesong/OpenClash#576]
在用nginx取代uhttpd的luci环境中，在openclash设置页面点击“启动openclash”，会卡死，显示正在设置Fake ip黑名单就不动了，但直接手工调用/etc/init.d/openclash restart则不会有这个问题

**Comment by fantasylidong** [comment]
碰到同样问题

**Comment by a13547** [comment]
会不会是luci版本的问题？我用官方的snapshot，不管是luci还是luci-nginx，在部分页面保存设置的时候都会卡很久甚至卡死，尤其是修改配置文件，根本不行，卡死了只能重启。

**Comment by vernesong** [comment]
> 会不会是luci版本的问题？我用官方的snapshot，不管是luci还是luci-nginx，在部分页面保存设置的时候都会卡很久甚至卡死，尤其是修改配置文件，根本不行，卡死了只能重启。

一些固件碰到大文本写入会卡死

**Comment by vernesong** [comment]
> 在用nginx取代uhttpd的luci环境中，在openclash设置页面点击“启动openclash”，会卡死，显示正在设置Fake ip黑名单就不动了，但直接手工调用/etc/init.d/openclash restart则不会有这个问题

单独左右fakeip filter的脚本呢？

**Comment by maskedeken** [comment]
> 
> 
> > 在用nginx取代uhttpd的luci环境中，在openclash设置页面点击“启动openclash”，会卡死，显示正在设置Fake ip黑名单就不动了，但直接手工调用/etc/init.d/openclash restart则不会有这个问题
> 
> 单独运行fakeip filter的脚本呢？

跟了一下，是执行完sh /usr/share/openclash/yml_rules_change.sh之后的那句wait卡死，但yml_rules_change.sh已经执行完

**Comment by maskedeken** [comment]
> 
> 
> 会不会是luci版本的问题？我用官方的snapshot，不管是luci还是luci-nginx，在部分页面保存设置的时候都会卡很久甚至卡死，尤其是修改配置文件，根本不行，卡死了只能重启。

snapshot版本的luci有权限限制，应该是没权限读写某些文件卡住了

**Comment by vernesong** [comment]
> > > 在用nginx取代uhttpd的luci环境中，在openclash设置页面点击“启动openclash”，会卡死，显示正在设置Fake ip黑名单就不动了，但直接手工调用/etc/init.d/openclash restart则不会有这个问题
> > 
> > 
> > 单独运行fakeip filter的脚本呢？
> 
> 跟了一下，是执行完sh /usr/share/openclash/yml_rules_change.sh之后的那句wait卡死，但yml_rules_change.sh已经执行完

改成bash /usr/share/openclash/yml_rules_change.sh或者删除sh试试

**Comment by Forev3rNAlway5** [comment]
给个思路，把uhttpd的端口放到81，再到nginx的conf里把luci相关的location反代到81端口。

**Comment by garypang13** [comment]
这个问题作者不打算解决下么,

**Comment by vernesong** [comment]
![image](https://user-images.githubusercontent.com/42875168/96749943-087d9180-13fe-11eb-9c57-245cebd2c363.png)
我这没有问题，是不是因为不能忽略脚本部分语句错误的原因导致失败的
