### ISSUE TITLE
发现一个relay的功能缺失

### ISSUE THREAD

**Issue by USDao** [vernesong/OpenClash#577]
![image](https://user-images.githubusercontent.com/46472876/86900188-9aa6a600-c13d-11ea-8d55-f62d393f445b.png)
relay策略组下 没有调整节点顺序。
clash的relay 依赖顺序作为转发路径。希望可以补充。
感谢。

**Comment by vernesong** [comment]
策略组这里暂不支持添加节点。你得在节点那块设置要加入的策略组，添加节点的顺序则是按照页面显示从上到下
