### ISSUE TITLE
内核、客户端、配置文件 协同问题

### ISSUE THREAD

**Issue by OUZYcn** [vernesong/OpenClash#578]
依据另外一个讨论（https://github.com/vernesong/OpenClash/issues/575），请教几个问题：

1. 当前最新的【Dev分支】内核版本：premium-29-g99b34e8 （即基于 Dreamacro/clash v.1.0 或 更新的commitID），这与客户端版v0.39.2-beta 是否确认协同工作？因为rls log没有写。 

PS，之前的v0.38.7-beta 版本变化有注明：“同步dev内核：premium-22-g58c077b”

2. 依据“Dreamacro/clash rls note： 1.0 has many breaking changes”，我看了对于配置文件有不少变化。
a. 现在机场有些直接给了Clash配置文件订阅，或者通过tindy2013/subconverter进行Shadowrocket.conf  2 Clash 转换，他们若是没有依据changelog改动，是不是就会OpenClash启动失败？
_b. 额，，，不记得要问什么了。。。_

例如 rls note提及：
> - Proxy, Proxy Group and Rule is no longer used. They are now respectively proxies, proxy-groups and rules.
> - rule-provider is no longer a valid keyword. Use rule-providers instead.

**Comment by OUZYcn** [comment]
噢，对了。 还有就是“客户端版 v0.39.2-beta” 等同于OpenWRT上的web界面（luci-app-openclash）是吧？

**Comment by vernesong** [comment]
1.0的内核移除了老字段的兼容，openclash配合1.0的修改已经push但还未发release，如果你的配置文件还是老标准就不要自行替换1.0的内核

**Comment by eggydutch** [comment]
> 1.0的内核移除了老字段的兼容，openclash配合1.0的修改已经push但还未发release，如果你的配置文件还是老标准就不要自行替换1.0的内核

我现在用你的openclash配合隔壁luci-app-clash的最新1.0内核使用几天了好像没什么问题，配置文件也还是旧的，并没有按照1.0的格式要求去更改。
另外试了下luci-app-clash最新版+1.0内核，发现它好像会自动把旧的配置文件格式修改为最新格式标准。

**Comment by OUZYcn** [comment]
> > 1.0的内核移除了老字段的兼容，openclash配合1.0的修改已经push但还未发release，如果你的配置文件还是老标准就不要自行替换1.0的内核
> 
> 我现在用你的openclash配合隔壁luci-app-clash的最新1.0内核使用几天了好像没什么问题，配置文件也还是旧的，并没有按照1.0内核新的格式标准去更改。
> 另外试了下luci-app-clash最新版+1.0内核，发现它好像会自动把旧的配置文件格式修改为最新格式标准。

你说的luci-app-clash最新版是“https://github.com/frainzy1477/luci-app-clash” 的v1.7.5.4嘛？ 可以和vernesong/OpenClash协同工作嘛？

**Comment by OUZYcn** [comment]
> 1.0的内核移除了老字段的兼容，openclash配合1.0的修改已经push但还未发release，如果你的配置文件还是老标准就不要自行替换1.0的内核

1. 预计Release时间？
2. “客户端版 v0.39.2-beta” 等同于OpenWRT上的web界面（luci-app-openclash）是吧？

**Comment by eggydutch** [comment]
> > > 1.0的内核移除了老字段的兼容，openclash配合1.0的修改已经push但还未发release，如果你的配置文件还是老标准就不要自行替换1.0的内核
> > 
> > 
> > 我现在用你的openclash配合隔壁luci-app-clash的最新1.0内核使用几天了好像没什么问题，配置文件也还是旧的，并没有按照1.0内核新的格式标准去更改。
> > 另外试了下luci-app-clash最新版+1.0内核，发现它好像会自动把旧的配置文件格式修改为最新格式标准。
> 
> 你说的luci-app-clash最新版是“[https://github.com/frainzy1477/luci-app-clash”](https://github.com/frainzy1477/luci-app-clash%E2%80%9D) 的v1.7.5.4嘛？ 可以和vernesong/OpenClash协同工作嘛？

对，实测可以和vernesong/OpenClash协同工作

**Comment by OUZYcn** [comment]
> > > > 1.0的内核移除了老字段的兼容，openclash配合1.0的修改已经push但还未发release，如果你的配置文件还是老标准就不要自行替换1.0的内核
> > > 
> > > 
> > > 我现在用你的openclash配合隔壁luci-app-clash的最新1.0内核使用几天了好像没什么问题，配置文件也还是旧的，并没有按照1.0内核新的格式标准去更改。
> > > 另外试了下luci-app-clash最新版+1.0内核，发现它好像会自动把旧的配置文件格式修改为最新格式标准。
> > 
> > 
> > 你说的luci-app-clash最新版是“[https://github.com/frainzy1477/luci-app-clash”](https://github.com/frainzy1477/luci-app-clash%E2%80%9D) 的v1.7.5.4嘛？ 可以和vernesong/OpenClash协同工作嘛？
> 
> 对，实测可以和vernesong/OpenClash协同工作

premium-22-g58c077b + v0.38.7-beta （luci-app-openclash）稳定工作中，不太敢用OpenClash premium-29-g99b34e8 + luci-app-clash 的组合。。。不知道有啥潜在问题。。。

**Comment by eggydutch** [comment]
> > > > > 1.0的内核移除了老字段的兼容，openclash配合1.0的修改已经push但还未发release，如果你的配置文件还是老标准就不要自行替换1.0的内核
> > > > 
> > > > 
> > > > 我现在用你的openclash配合隔壁luci-app-clash的最新1.0内核使用几天了好像没什么问题，配置文件也还是旧的，并没有按照1.0内核新的格式标准去更改。
> > > > 另外试了下luci-app-clash最新版+1.0内核，发现它好像会自动把旧的配置文件格式修改为最新格式标准。
> > > 
> > > 
> > > 你说的luci-app-clash最新版是“[https://github.com/frainzy1477/luci-app-clash”](https://github.com/frainzy1477/luci-app-clash%E2%80%9D) 的v1.7.5.4嘛？ 可以和vernesong/OpenClash协同工作嘛？
> > 
> > 
> > 对，实测可以和vernesong/OpenClash协同工作
> 
> premium-22-g58c077b + v0.38.7-beta （luci-app-openclash）稳定工作中，不太敢用OpenClash premium-29-g99b34e8 + luci-app-clash 的组合。。。不知道有啥潜在问题。。。若不然只能另外启用一个虚拟机来测试。。。
> 
> 对了，装了luci-app-clash在服务菜单上出现一个新的Clash客户端web界面嘛（例如Clash什么的）？
> @eggydutch
> 
我是用的Openclash v39.2配合luci-app-clash那边的核心v1.0.0，装完luci-app-clash后服务菜单是会有Clash的WebUI
