### ISSUE TITLE
问一下，啥时候支持Mux 多路复用啊

### ISSUE THREAD

**Issue by lloyd18** [vernesong/OpenClash#579]
这个功能对于延迟高的人很有用，150ms延迟左右都能做到YouTube秒开，没开之前会黑屏1到2秒加载。

clash内核是支持mux的，至少v2ray是支持的，但是openclash没看到有开启的选项，，trojan-go也是支持的开启的，但不知道内核支不支持。

辛苦了！

**Comment by vernesong** [comment]
ss的v2ray-plugin支持
