### ISSUE TITLE
使用urtest会导致网络连接中断

### ISSUE THREAD

**Issue by junwu0608** [vernesong/OpenClash#58]
有可能是在自动切换节点的时候会导致网络不通，不论是否国外网站都会进不去。

**Comment by junwu0608** [comment]
还有个问题，开启openclash会导致活动连接暴涨，瞬间会涨到3万。

**Comment by vernesong** [comment]
切换节点不会导致直连受影响，目前还无法定位原因

**Comment by junwu0608** [comment]
> 切换节点不会导致直连受影响，目前还无法定位原因

当手动选择proxy后这个问题就没有再出现过了。
