### ISSUE TITLE
Fake-IP模式 手机外网不能访问小米摄像头

### ISSUE THREAD

**Issue by beilsn** [vernesong/OpenClash#580]
Fake-IP模式下，外网不能通过米家APP连接家里小米摄像头。

看过相关的Issues，需要重启防火墙后能连接正常，但是如果换了节点后又连不上了，还得重新再次重启防火墙才能连接，
请教各位该如何处理，谢谢！

**Comment by vernesong** [comment]
观察日志里的连接情况

**Comment by beilsn** [comment]
> 观察日志里的连接情况

大佬下面是调试日志，请帮忙看看，多谢！
#===================== 防火墙设置 =====================#

#NAT chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    REDIRECT   tcp  --  0.0.0.0/0            8.8.4.4              redir ports 7892
2    REDIRECT   tcp  --  0.0.0.0/0            8.8.8.8              redir ports 7892
3    prerouting_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom prerouting rule chain */
4    zone_lan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
5    zone_wan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
6    REDIRECT   udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:53 redir ports 53
7    REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:53 redir ports 53
8    openclash  tcp  --  0.0.0.0/0            0.0.0.0/0           
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         
1    openclash_output  tcp  --  0.0.0.0/0            0.0.0.0/0           

#Mangle chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    openclash  udp  --  0.0.0.0/0            0.0.0.0/0           
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         
1    RRDIPT_OUTPUT  all  --  0.0.0.0/0            0.0.0.0/0           

#===================== 路由表状态 =====================#
#route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         180.162.250.1   0.0.0.0         UG    0      0        0 pppoe-wan
180.162.250.1   0.0.0.0         255.255.255.255 UH    0      0        0 pppoe-wan
192.168.2.0     0.0.0.0         255.255.255.0   U     0      0        0 br-lan
#ip route list
default via 180.162.250.1 dev pppoe-wan proto static 
180.162.250.1 dev pppoe-wan proto kernel scope link src 180.162.250.74 
192.168.2.0/24 dev br-lan proto kernel scope link src 192.168.2.1 
#ip rule show
0:	from all lookup local 
219:	from all fwmark 0x162 lookup 354 
220:	from all lookup 220 
32766:	from all lookup main 
32767:	from all lookup default 

#===================== 端口占用状态 =====================#
tcp        0      0 192.168.2.1:7891        0.0.0.0:*               LISTEN      20601/clash
tcp        0      0 192.168.2.1:9091        0.0.0.0:*               LISTEN      20601/clash
tcp        0      0 192.168.2.1:7890        0.0.0.0:*               LISTEN      20601/clash
tcp        0      0 :::7892                 :::*                    LISTEN      20601/clash
udp        0      0 127.0.0.1:7874          0.0.0.0:*                           20601/clash
udp        0      0 192.168.2.1:7891        0.0.0.0:*                           20601/clash
udp        0      0 :::35891                :::*                                20601/clash
udp        0      0 :::36316                :::*                                20601/clash
udp        0      0 :::36819                :::*                                20601/clash
udp        0      0 :::37223                :::*                                20601/clash
udp        0      0 :::46536                :::*                                20601/clash
udp        0      0 :::48013                :::*                                20601/clash
udp        0      0 :::40287                :::*                                20601/clash
udp        0      0 :::7892                 :::*                                20601/clash
udp        0      0 :::34342                :::*                                20601/clash

#===================== 测试本机DNS查询 =====================#
Server:		127.0.0.1
Address:	127.0.0.1#53

Name:      www.baidu.com
Address 1: 198.18.0.28
*** Can't find www.baidu.com: No answer

**Comment by beilsn** [comment]
刚刚用SURGE抓流量，发现有大量如下日志，这个是小米摄像头连接不上家里41139端口后一直有这日志：
家里公网IP:41139（Port Map)

而再次生成的调试日志发现41139是被clash给占用，这是不是造成无法连接上小米摄像头的原因？
#===================== 端口占用状态 =====================#
tcp        0      0 192.168.2.1:7891        0.0.0.0:*               LISTEN      20601/clash
tcp        0      0 192.168.2.1:9091        0.0.0.0:*               LISTEN      20601/clash
tcp        0      0 192.168.2.1:7890        0.0.0.0:*               LISTEN      20601/clash
tcp        0      0 :::7892                 :::*                    LISTEN      20601/clash
udp        0      0 127.0.0.1:7874          0.0.0.0:*                           20601/clash
udp        0      0 192.168.2.1:7891        0.0.0.0:*                           20601/clash
udp        0      0 :::60850                :::*                                20601/clash
udp        0      0 :::36819                :::*                                20601/clash
udp        0      0 :::47228                :::*                                20601/clash
udp        0      0 :::47649                :::*                                20601/clash
udp        0      0 :::48058                :::*                                20601/clash
udp        0      0 :::48793                :::*                                20601/clash
udp        0      0 :::40639                :::*                                20601/clash
udp        0      0 :::7892                 :::*                                20601/clash
udp        0      0 :::41139                :::*                                20601/clash
udp        0      0 :::33262                :::*                                20601/clash
udp        0      0 :::51133                :::*                                20601/clash

**Comment by vernesong** [comment]
不是占用，在监听，你观察连接日志
如果redir模式没问题的话，根据连接日志尝试在DNS高级设置里面加一下米家的几个域名

**Comment by beilsn** [comment]
> 不是占用，在监听，你观察连接日志
> 如果redir模式没问题的话，根据连接日志尝试在DNS高级设置里面加一下米家的几个域名
把米家的*.mi.com  *.xiaomi.com加到DNS高级里面，Fake-IP下还是不行。。。。。

**Comment by beilsn** [comment]
FAKE-IP TUN模式下倒是能正常连接小米摄像头。。。。。

**Comment by beilsn** [comment]
今天才发现千兆带宽用FAKE-IP TUN模式  SPEEDTEST直连 发现测速只能到750M左右 更改为Fake-IP（增强）模式后 SPEEDTEST测速正常 能到940M左右 但是这样又不能外网访问家里小米摄像头。。。。。

**Comment by 5high** [comment]
加一条自定义策略:  - SRC-IP-CIDR,110.43.68.200/32,DIRECT

**Comment by beilsn** [comment]
> - SRC-IP-CIDR,110.43.68.200/32,DIRECT

多谢这位大佬 我先试试看！

**Comment by beilsn** [comment]
加一条自定义策略: - SRC-IP-CIDR,110.43.68.200/32,DIRECT

不好意思 多谢那位留言的大佬了  我删错回复了。

**Comment by brick713** [comment]
> 加一条自定义策略: - SRC-IP-CIDR,110.43.68.200/32,DIRECT
> 
> 不好意思 多谢那位留言的大佬了 我删错回复了。

请问你最后使用的是什么模式，怎么做的呢？我也碰上了这个问题

**Comment by new1943** [comment]
同问，我也发现这个问题，开启openclash后，小米摄像头无法访问，switch不能联机，upnp失效。

**Comment by iKira** [comment]
根治了，看这里：
https://github.com/MetaCubeX/mihomo/discussions/1994#discussioncomment-12990182
