### ISSUE TITLE
请问能添加一个设置让我们自定义GeoIP数据库订阅的下载链接吗

### ISSUE THREAD

**Issue by Apocalypsor** [vernesong/OpenClash#582]
由于众所周知的原因，托管在Github的GeoIP文件在国内下载速度缓慢

所以希望可以自定义GeoIP数据库订阅的下载链接

十分感谢开发者！

**Comment by OUZYcn** [comment]
变通方式：自己手动更新GeoIP，或者GeoIP+IPIP的合成库
https://github.com/Dreamacro/clash/issues/82

**Comment by Apocalypsor** [comment]
> 变通方式：自己手动更新GeoIP，或者GeoIP+IPIP的合成库
> https://github.com/Dreamacro/clash/issues/82#issuecomment-630290134

首先不开tun的话（fake-ip）在openclash本机就根本无法更新，而开tun的情况下万一更新失败（经常发生）就会导致clash自动下载，而又下载不下来，就会导致openclash启动不了

自动更新的话只需要cron wget就完事了，关键是容易遇到这些小问题

**Comment by OUZYcn** [comment]
> > 变通方式：自己手动更新GeoIP，或者GeoIP+IPIP的合成库
> > [Dreamacro/clash#82 (comment)](https://github.com/Dreamacro/clash/issues/82#issuecomment-630290134)
> 
> 首先不开tun的话（fake-ip）在openclash本机就根本无法更新，而开tun的情况下万一更新失败（经常发生）就会导致clash自动下载，而又下载不下来，就会导致openclash启动不了
> 
> 自动更新的话只需要cron wget就完事了，关键是容易遇到这些小问题

1. 如你提议OpenClash这里更动。
2. 你改动 /usr/share/openclash/openclash_ipdb.sh 中的Country.mmdb的下载地址。 例如：Alecthw提供的aliyun链接
```
   if pidof clash >/dev/null; then
      curl -sL --connect-timeout 10 --retry 2 -x http://$PROXY_ADDR:$HTTP_PORT -U "$PROXY_AUTH" https://geolite.clash.dev/Country.mmdb -o /tmp/Country.mmdb >/dev/null 2>&1
   else
      curl -sL --connect-timeout 10 --retry 2 https://geolite.clash.dev/Country.mmdb -o /tmp/Country.mmdb >/dev/null 2>&1
   fi

```

**Comment by Apocalypsor** [comment]
> > > 变通方式：自己手动更新GeoIP，或者GeoIP+IPIP的合成库
> > > [Dreamacro/clash#82 (comment)](https://github.com/Dreamacro/clash/issues/82#issuecomment-630290134)
> > 
> > 
> > 首先不开tun的话（fake-ip）在openclash本机就根本无法更新，而开tun的情况下万一更新失败（经常发生）就会导致clash自动下载，而又下载不下来，就会导致openclash启动不了
> > 自动更新的话只需要cron wget就完事了，关键是容易遇到这些小问题
> 
> 1. 如你提议OpenClash这里更动。
> 2. 你改动 /usr/share/openclash/openclash_ipdb.sh 中的Country.mmdb的下载地址。 例如：Alecthw提供的aliyun链接
> 
> ```
>    if pidof clash >/dev/null; then
>       curl -sL --connect-timeout 10 --retry 2 -x http://$PROXY_ADDR:$HTTP_PORT -U "$PROXY_AUTH" https://geolite.clash.dev/Country.mmdb -o /tmp/Country.mmdb >/dev/null 2>&1
>    else
>       curl -sL --connect-timeout 10 --retry 2 https://geolite.clash.dev/Country.mmdb -o /tmp/Country.mmdb >/dev/null 2>&1
>    fi
> ```

我现在就是这么做的，当每次更新都要改，毕竟会麻烦一点

Fake-IP模式的优势建议多读几遍[Sukka大佬的文章](https://blog.skk.moe/post/what-happend-to-dns-in-proxy/)，我开tun主要是为了路由器本机流量也能进clash（我也不太懂，只是解决了我这个问题）

**Comment by vernesong** [comment]
安装就自带了，你也没必要在不启动的情况下更新啊，订阅开启后会默认调用clash的http代理进行更新

**Comment by Apocalypsor** [comment]
> 安装就自带了，你也没必要在不启动的情况下更新啊，订阅开启后会默认调用clash的http代理进行更新

其实是因为我不想用GeoIP lite。。。因为有些ip总是莫名其妙识别为国内的，导致访问十分缓慢

**Comment by eggydutch** [comment]
> > > 变通方式：自己手动更新GeoIP，或者GeoIP+IPIP的合成库
> > > [Dreamacro/clash#82 (comment)](https://github.com/Dreamacro/clash/issues/82#issuecomment-630290134)
> > 
> > 
> > 首先不开tun的话（fake-ip）在openclash本机就根本无法更新，而开tun的情况下万一更新失败（经常发生）就会导致clash自动下载，而又下载不下来，就会导致openclash启动不了
> > 自动更新的话只需要cron wget就完事了，关键是容易遇到这些小问题
> 
> 1. 如你提议OpenClash这里更动。
> 2. 你改动 /usr/share/openclash/openclash_ipdb.sh 中的Country.mmdb的下载地址。 例如：Alecthw提供的aliyun链接
> 
> ```
>    if pidof clash >/dev/null; then
>       curl -sL --connect-timeout 10 --retry 2 -x http://$PROXY_ADDR:$HTTP_PORT -U "$PROXY_AUTH" https://geolite.clash.dev/Country.mmdb -o /tmp/Country.mmdb >/dev/null 2>&1
>    else
>       curl -sL --connect-timeout 10 --retry 2 https://geolite.clash.dev/Country.mmdb -o /tmp/Country.mmdb >/dev/null 2>&1
>    fi
> ```
> 
> 噢，忘了说，我用的是Redir-Host（兼容）模式，TUN模式不懂。。。可否顺带告知一下区别与优势呢？

感谢大胸弟提供的GeoIP解决方案，解决了我腾讯TV识别错误的问题

**Comment by OUZYcn** [comment]
> 安装就自带了，你也没必要在不启动的情况下更新啊，订阅开启后会默认调用clash的http代理进行更新

关键问题其实MaxMind GeoIP2 库对于识别国内IP不准确/完善，导致GeoIP规则有出错情况。 
因此才出现了“https://github.com/alecthw/mmdb_china_ip_list” 这种合成了GeoIP2 + ipip的合成库。
如果可以加入自定义地址 而非 当前写死了固定链接指向的MaxMind库就满足个性化需求。

**Comment by vernesong** [comment]
用ruleset呗，可以补充rixcloud的chinaip

**Comment by OUZYcn** [comment]
> 用ruleset呗，可以补充rixcloud的chinaip

可否给个地址看看rixcloud的ruleset？

**Comment by Apocalypsor** [comment]
> > 用ruleset呗，可以补充rixcloud的chinaip
> 
> 可否给个地址看看rixcloud的ruleset？ @vernesong

其实就是ipip转的，就用[神机规则](https://github.com/DivineEngine/Profiles/blob/master/Clash/RuleSet/Extra/ChinaIP.yaml)就行
或者用[我这个](https://github.com/Apocalypsor/Rules/blob/master/Clash/china_ip.yml)

**Comment by OUZYcn** [comment]
> > > 用ruleset呗，可以补充rixcloud的chinaip
> > 
> > 
> > 可否给个地址看看rixcloud的ruleset？ @vernesong
> 
> 其实就是ipip转的，就用[神机规则](https://github.com/DivineEngine/Profiles/blob/master/Clash/RuleSet/Extra/ChinaIP.yaml)就行
> 或者用[我这个](https://github.com/Apocalypsor/Rules/blob/master/Clash/china_ip.yml)

噢，感谢答复。 
是直接在“代理集URL”  填上 [你的ChinaIP.yml](https://github.com/Apocalypsor/Rules/blob/master/Clash/china_ip.yml) 是吗？

![openclash](https://user-images.githubusercontent.com/47710598/87390400-5d2d9700-c5db-11ea-8684-c261b342c592.png)

**Comment by Apocalypsor** [comment]
> 
> 
> > > > 用ruleset呗，可以补充rixcloud的chinaip
> > > 
> > > 
> > > 可否给个地址看看rixcloud的ruleset？ @vernesong
> > 
> > 
> > 其实就是ipip转的，就用[神机规则](https://github.com/DivineEngine/Profiles/blob/master/Clash/RuleSet/Extra/ChinaIP.yaml)就行
> > 或者用[我这个](https://github.com/Apocalypsor/Rules/blob/master/Clash/china_ip.yml)
> 
> 噢，感谢答复。
> 是直接在“代理集URL” 填上 [你的ChinaIP.yml](https://github.com/Apocalypsor/Rules/blob/master/Clash/china_ip.yml) 是吗？
> 
> ![openclash](https://user-images.githubusercontent.com/47710598/87390400-5d2d9700-c5db-11ea-8684-c261b342c592.png)
> 
> 试了下，貌似yml不是Clash可识别格式文件？？？有没有什么工具可以转换？

这个功能我没用使用过。。
不过我的这个代理集是rule-provider的形式，clash肯定能直接使用的

**Comment by OUZYcn** [comment]
> > > > > 用ruleset呗，可以补充rixcloud的chinaip
> > > > 
> > > > 
> > > > 可否给个地址看看rixcloud的ruleset？ @vernesong
> > > 
> > > 
> > > 其实就是ipip转的，就用[神机规则](https://github.com/DivineEngine/Profiles/blob/master/Clash/RuleSet/Extra/ChinaIP.yaml)就行
> > > 或者用[我这个](https://github.com/Apocalypsor/Rules/blob/master/Clash/china_ip.yml)
> > 
> > 
> > 噢，感谢答复。
> > 是直接在“代理集URL” 填上 [你的ChinaIP.yml](https://github.com/Apocalypsor/Rules/blob/master/Clash/china_ip.yml) 是吗？
> > ![openclash](https://user-images.githubusercontent.com/47710598/87390400-5d2d9700-c5db-11ea-8684-c261b342c592.png)
> > 试了下，貌似yml不是Clash可识别格式文件？？？有没有什么工具可以转换？
> 
> 这个功能我没用使用过。。
> 不过我的这个代理集是rule-provider的形式，clash肯定能直接使用的

oh , "是rule-provider的形式" , 我还没有更新到Clash 1.0对等的openclash新版。。。所以晚点升级了再试
