### ISSUE TITLE
关闭openclash后网站都打不开了

### ISSUE THREAD

**Issue by tengyuankoo** [vernesong/OpenClash#583]
现在最新编译的版本开启openclash后所有网站都能打开，但在关闭后所有的网站都打不开，提示找不到服务器IP地址，应该是关闭后DNS没改回来，每次关闭openclash都需要手动在DHCP里添加DNS，
关闭openclash后，使用其他的比如ssr plus科学上网同样打不开网站，只能启动openclash，百度搜索可以，但是不显示照片

**Comment by tengyuankoo** [comment]
OpenClash 调试日志

生成时间: 2020-07-11 21:44:14
插件版本: v0.39.2-beta

#===================== 系统信息 =====================#
主机型号: Intel(R) Celeron(R) CPU 3865U @ 1.80GHz : 2 Core 2 Thread
固件版本: OpenWrt SNAPSHOT r0-fefe096
LuCI版本: git-20.191.36863-eee6bae-1
内核版本: 4.19.123
处理器架构: x86_64

#此项在使用Tun模式时应为ACCEPT
防火墙转发: ACCEPT

#此项有值时建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: server

#此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 127.0.0.1#7874

#===================== 依赖检查 =====================#
dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
jsonfilter: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
iptables-mod-tproxy: 已安装
kmod-tun(TUN模式): 已安装
luci-compat(Luci-19.07): 已安装

#===================== 内核检查 =====================#
运行状态: 运行中
已选择的架构: linux-amd64

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 2020.06.15.gbf68156
Tun内核文件: 存在
Tun内核运行权限: 正常

Game内核版本: v0.17.0-132-g3a53a25
Game内核文件: 存在
Game内核运行权限: 正常

Dev内核版本: premium-29-g99b34e8
Dev内核文件: 存在
Dev内核运行权限: 正常

#===================== 插件设置 =====================#
当前配置文件: /etc/openclash/config/zyp.yaml
运行模式: fake-ip-vpn
默认代理模式: rule
UDP流量转发: 停用
DNS劫持: 启用
自定义DNS: 停用
IPV6-DNS解析: 停用
禁用Dnsmasq缓存: 启用
自定义规则: 停用
仅允许内网: 停用
仅代理命中规则流量: 停用

#启动异常时建议关闭此项后重试
保留配置: 停用
第三方规则: 停用

#===================== 配置文件 =====================#
port: 7890
socks-port: 7891
allow-lan: true
bind-address: "*"
ipv6: false
mode: rule
log-level: silent
external-controller: 0.0.0.0:9090
redir-port: 7892
secret: ""
external-ui: "/usr/share/openclash/dashboard"
tun:
  enable: true
  device-url: dev://clash0
  dns-listen: 0.0.0.0:53
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  listen: 127.0.0.1:7874
  fake-ip-filter:
##Custom fake-ip-filter##
  - '*.lan'
  - 'time.windows.com'
  - 'time.nist.gov'
  - 'time.apple.com'
  - 'time.asia.apple.com'
  - '*.ntp.org.cn'
  - '*.openwrt.pool.ntp.org'
  - 'time1.cloud.tencent.com'
  - 'time.ustc.edu.cn'
  - 'pool.ntp.org'
  - 'ntp.ubuntu.com'
  - 'ntp.aliyun.com'
  - 'ntp1.aliyun.com'
  - 'ntp2.aliyun.com'
  - 'ntp3.aliyun.com'
  - 'ntp4.aliyun.com'
  - 'ntp5.aliyun.com'
  - 'ntp6.aliyun.com'
  - 'ntp7.aliyun.com'
  - 'time1.aliyun.com'
  - 'time2.aliyun.com'
  - 'time3.aliyun.com'
  - 'time4.aliyun.com'
  - 'time5.aliyun.com'
  - 'time6.aliyun.com'
  - 'time7.aliyun.com'
  - '*.time.edu.cn'
  - 'time1.apple.com'
  - 'time2.apple.com'
  - 'time3.apple.com'
  - 'time4.apple.com'
  - 'time5.apple.com'
  - 'time6.apple.com'
  - 'time7.apple.com'
  - 'time1.google.com'
  - 'time2.google.com'
  - 'time3.google.com'
  - 'time4.google.com'
  - 'music.163.com'
  - '*.music.163.com'
  - '*.126.net'
  - 'musicapi.taihe.com'
  - 'music.taihe.com'
  - 'songsearch.kugou.com'
  - 'trackercdn.kugou.com'
  - '*.kuwo.cn'
  - 'api-jooxtt.sanook.com'
  - 'api.joox.com'
  - 'joox.com'
  - 'y.qq.com'
  - '*.y.qq.com'
  - 'streamoc.music.tc.qq.com'
  - 'mobileoc.music.tc.qq.com'
  - 'isure.stream.qqmusic.qq.com'
  - 'dl.stream.qqmusic.qq.com'
  - 'aqqmusic.tc.qq.com'
  - 'amobile.music.tc.qq.com'
  - '*.xiami.com'
  - '*.music.migu.cn'
  - 'music.migu.cn'
  - '*.msftconnecttest.com'
  - '*.msftncsi.com'
  - 'localhost.ptlogin2.qq.com'
  - '*.*.*.srv.nintendo.net'
  - '*.*.stun.playstation.net'
  - 'xbox.*.*.microsoft.com'
  - '*.*.xboxlive.com'
##Custom fake-ip-filter END##
  nameserver:
  - 114.114.114.114
  fallback:
  - tls://8.8.8.8:853
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4

#===================== 防火墙设置 =====================#

#NAT chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:53
2    CLOUD_MUSIC  tcp  --  0.0.0.0/0            0.0.0.0/0            match-set music dst
3    REDIRECT   udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:53 redir ports 53
4    REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:53 redir ports 53
5    prerouting_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom prerouting rule chain */
6    zone_lan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
7    zone_wan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
8    zone_wan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         

#Mangle chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    MARK       all  --  0.0.0.0/0            0.0.0.0/0            ! match-set localnetwork dst MARK set 0x162
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         
1    openclash  all  --  0.0.0.0/0            0.0.0.0/0           
2    RRDIPT_OUTPUT  all  --  0.0.0.0/0            0.0.0.0/0           

#===================== 路由表状态 =====================#
#route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.94.64.1      0.0.0.0         UG    0      0        0 pppoe-wan
10.94.64.1      0.0.0.0         255.255.255.255 UH    0      0        0 pppoe-wan
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
192.168.1.0     0.0.0.0         255.255.255.0   U     0      0        0 br-lan
192.168.192.0   0.0.0.0         255.255.255.0   U     0      0        0 ztzlggw24j
#ip route list
default via 10.94.64.1 dev pppoe-wan proto static 
10.94.64.1 dev pppoe-wan proto kernel scope link src 10.94.92.224 
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown 
192.168.1.0/24 dev br-lan proto kernel scope link src 192.168.1.1 
192.168.192.0/24 dev ztzlggw24j proto kernel scope link src 192.168.192.193 
#ip rule show
0:	from all lookup local 
32765:	from all fwmark 0x162 lookup 354 
32766:	from all lookup main 
32767:	from all lookup default 

#===================== Tun设备状态 =====================#
ztzlggw24j: tap
clash0: tun persist user 0

#===================== 端口占用状态 =====================#
tcp        0      0 :::7890                 :::*                    LISTEN      19380/clash
tcp        0      0 :::7891                 :::*                    LISTEN      19380/clash
tcp        0      0 :::7892                 :::*                    LISTEN      19380/clash
tcp        0      0 :::9090                 :::*                    LISTEN      19380/clash
tcp        0      0 :::6060                 :::*                    LISTEN      19380/clash
udp        0      0 127.0.0.1:7874          0.0.0.0:*                           19380/clash
udp        0      0 :::54815                :::*                                19380/clash
udp        0      0 :::7891                 :::*                                19380/clash
udp        0      0 :::7892                 :::*                                19380/clash
udp        0      0 :::44895                :::*                                19380/clash
udp        0      0 :::47593                :::*                                19380/clash
udp        0      0 :::40237                :::*                                19380/clash

#===================== 测试本机DNS查询 =====================#
Server:		211.140.13.188
Address:	211.140.13.188#53

Name:      www.baidu.com
www.baidu.com	canonical name = www.a.shifen.com
Name:      www.a.shifen.com
Address 1: 36.152.44.96
Address 2: 36.152.44.95
www.baidu.com	canonical name = www.a.shifen.com

#===================== resolv.conf.auto =====================#
# Interface wan
nameserver 211.140.13.188
nameserver 211.140.188.188
# Interface wan_6
nameserver 2409:8028:2000::1111
nameserver 2409:8028:2000::2222

#===================== 测试本机网络连接 =====================#
HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: private, no-cache, no-store, proxy-revalidate, no-transform
Connection: keep-alive
Content-Length: 277
Content-Type: text/html
Date: Sat, 11 Jul 2020 13:44:15 GMT
Etag: "575e1f7d-115"
Last-Modified: Mon, 13 Jun 2016 02:50:37 GMT
Pragma: no-cache
Server: bfe/1.0.8.18


#===================== 测试本机网络下载 =====================#
HTTP/1.1 200 Connection established

HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 78
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: text/plain; charset=utf-8
ETag: "2634120e33207f655153900e2398f5f93cf299cb681c51c8437b6c5c3863e805"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
Via: 1.1 varnish (Varnish/6.0)
X-GitHub-Request-Id: 8110:1B41:121319:159958:5F09BCD7
Accept-Ranges: bytes
Date: Sat, 11 Jul 2020 13:44:16 GMT
Via: 1.1 varnish
X-Served-By: cache-hkg17928-HKG
X-Cache: HIT, HIT
X-Cache-Hits: 1, 1
X-Timer: S1594475056.391044,VS0,VE1
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
X-Fastly-Request-ID: c3ec7713db3e83fa801e57f4fdcd760e9aad47a1
Expires: Sat, 11 Jul 2020 13:49:16 GMT
Source-Age: 145


#===================== 最近运行日志 =====================#
time="2020-07-11T13:19:31Z" level=info msg="Start initial compatible provider ♻️ 自动选择"
time="2020-07-11T13:19:31Z" level=info msg="Start initial compatible provider 🎯 全球直连"
time="2020-07-11T13:19:31Z" level=info msg="Start initial compatible provider 🐟 漏网之鱼"
time="2020-07-11T13:19:31Z" level=info msg="Start initial compatible provider 🛑 全球拦截"
time="2020-07-11T13:19:31Z" level=info msg="Start initial compatible provider 📢 谷歌FCM"
time="2020-07-11T13:19:31Z" level=info msg="Start initial compatible provider 🌍 国外媒体"
time="2020-07-11T13:19:31Z" level=info msg="Start initial compatible provider 🍃 应用净化"
time="2020-07-11T13:19:31Z" level=info msg="Start initial compatible provider 🚀 节点选择"
time="2020-07-11T13:19:31Z" level=info msg="Start initial compatible provider 📲 电报信息"
time="2020-07-11T13:19:31Z" level=info msg="Start initial compatible provider 🍎 苹果服务"
time="2020-07-11T13:19:31Z" level=info msg="Start initial compatible provider Ⓜ️ 微软服务"
time="2020-07-11T13:19:31Z" level=info msg="DNS server listening at: 127.0.0.1:7874"
2020-07-11 21:19:26 OpenClash Start Successful, Please Note That Network May Abnormal With IPV6's DHCP Server
2020-07-11 21:31:00 OpenClash Start Successful, Please Note That Network May Abnormal With IPV6's DHCP Server
2020-07-11 21:30:50 GEOIP Database Update Successful

**Comment by tengyuankoo** [comment]
以下是关闭后的调试日志
-------------------------------------------------

OpenClash 调试日志

生成时间: 2020-07-11 21:54:57
插件版本: v0.39.2-beta

#===================== 系统信息 =====================#
主机型号: Intel(R) Celeron(R) CPU 3865U @ 1.80GHz : 2 Core 2 Thread
固件版本: OpenWrt SNAPSHOT r0-fefe096
LuCI版本: git-20.191.36863-eee6bae-1
内核版本: 4.19.123
处理器架构: x86_64

#此项在使用Tun模式时应为ACCEPT
防火墙转发: ACCEPT

#此项有值时建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: server

#此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 

#===================== 依赖检查 =====================#
dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
jsonfilter: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
iptables-mod-tproxy: 已安装
kmod-tun(TUN模式): 已安装
luci-compat(Luci-19.07): 已安装

#===================== 内核检查 =====================#
运行状态: 未运行
已选择的架构: linux-amd64

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 2020.06.15.gbf68156
Tun内核文件: 存在
Tun内核运行权限: 正常

Game内核版本: v0.17.0-132-g3a53a25
Game内核文件: 存在
Game内核运行权限: 正常

Dev内核版本: premium-29-g99b34e8
Dev内核文件: 存在
Dev内核运行权限: 正常

#===================== 插件设置 =====================#
当前配置文件: /etc/openclash/config/zyp.yaml
运行模式: fake-ip-vpn
默认代理模式: rule
UDP流量转发: 停用
DNS劫持: 启用
自定义DNS: 停用
IPV6-DNS解析: 停用
禁用Dnsmasq缓存: 启用
自定义规则: 停用
仅允许内网: 停用
仅代理命中规则流量: 停用

#启动异常时建议关闭此项后重试
保留配置: 停用
第三方规则: 停用

#===================== 配置文件 =====================#
port: 7890
socks-port: 7891
allow-lan: true
bind-address: "*"
ipv6: false
mode: rule
log-level: silent
external-controller: 0.0.0.0:9090
redir-port: 7892
secret: ""
external-ui: "/usr/share/openclash/dashboard"
tun:
  enable: true
  device-url: dev://clash0
  dns-listen: 0.0.0.0:53
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  listen: 127.0.0.1:7874
  fake-ip-filter:
##Custom fake-ip-filter##
  - '*.lan'
  - 'time.windows.com'
  - 'time.nist.gov'
  - 'time.apple.com'
  - 'time.asia.apple.com'
  - '*.ntp.org.cn'
  - '*.openwrt.pool.ntp.org'
  - 'time1.cloud.tencent.com'
  - 'time.ustc.edu.cn'
  - 'pool.ntp.org'
  - 'ntp.ubuntu.com'
  - 'ntp.aliyun.com'
  - 'ntp1.aliyun.com'
  - 'ntp2.aliyun.com'
  - 'ntp3.aliyun.com'
  - 'ntp4.aliyun.com'
  - 'ntp5.aliyun.com'
  - 'ntp6.aliyun.com'
  - 'ntp7.aliyun.com'
  - 'time1.aliyun.com'
  - 'time2.aliyun.com'
  - 'time3.aliyun.com'
  - 'time4.aliyun.com'
  - 'time5.aliyun.com'
  - 'time6.aliyun.com'
  - 'time7.aliyun.com'
  - '*.time.edu.cn'
  - 'time1.apple.com'
  - 'time2.apple.com'
  - 'time3.apple.com'
  - 'time4.apple.com'
  - 'time5.apple.com'
  - 'time6.apple.com'
  - 'time7.apple.com'
  - 'time1.google.com'
  - 'time2.google.com'
  - 'time3.google.com'
  - 'time4.google.com'
  - 'music.163.com'
  - '*.music.163.com'
  - '*.126.net'
  - 'musicapi.taihe.com'
  - 'music.taihe.com'
  - 'songsearch.kugou.com'
  - 'trackercdn.kugou.com'
  - '*.kuwo.cn'
  - 'api-jooxtt.sanook.com'
  - 'api.joox.com'
  - 'joox.com'
  - 'y.qq.com'
  - '*.y.qq.com'
  - 'streamoc.music.tc.qq.com'
  - 'mobileoc.music.tc.qq.com'
  - 'isure.stream.qqmusic.qq.com'
  - 'dl.stream.qqmusic.qq.com'
  - 'aqqmusic.tc.qq.com'
  - 'amobile.music.tc.qq.com'
  - '*.xiami.com'
  - '*.music.migu.cn'
  - 'music.migu.cn'
  - '*.msftconnecttest.com'
  - '*.msftncsi.com'
  - 'localhost.ptlogin2.qq.com'
  - '*.*.*.srv.nintendo.net'
  - '*.*.stun.playstation.net'
  - 'xbox.*.*.microsoft.com'
  - '*.*.xboxlive.com'
##Custom fake-ip-filter END##
  nameserver:
  - 114.114.114.114
  fallback:
  - tls://8.8.8.8:853
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4

#===================== 防火墙设置 =====================#

#NAT chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    CLOUD_MUSIC  tcp  --  0.0.0.0/0            0.0.0.0/0            match-set music dst
2    REDIRECT   udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:53 redir ports 53
3    REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:53 redir ports 53
4    prerouting_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom prerouting rule chain */
5    zone_lan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
6    zone_wan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
7    zone_wan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         

#Mangle chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         
1    RRDIPT_OUTPUT  all  --  0.0.0.0/0            0.0.0.0/0           

#===================== 路由表状态 =====================#
#route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.94.64.1      0.0.0.0         UG    0      0        0 pppoe-wan
10.94.64.1      0.0.0.0         255.255.255.255 UH    0      0        0 pppoe-wan
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
192.168.1.0     0.0.0.0         255.255.255.0   U     0      0        0 br-lan
#ip route list
default via 10.94.64.1 dev pppoe-wan proto static 
10.94.64.1 dev pppoe-wan proto kernel scope link src 10.94.92.224 
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown 
192.168.1.0/24 dev br-lan proto kernel scope link src 192.168.1.1 
#ip rule show
0:	from all lookup local 
32766:	from all lookup main 
32767:	from all lookup default 

#===================== Tun设备状态 =====================#
clash0: tun persist user 0

#===================== 端口占用状态 =====================#

#===================== 测试本机DNS查询 =====================#
Server:		211.140.13.188
Address:	211.140.13.188#53

Name:      www.baidu.com
www.baidu.com	canonical name = www.a.shifen.com
Name:      www.a.shifen.com
Address 1: 36.152.44.96
Address 2: 36.152.44.95
www.baidu.com	canonical name = www.a.shifen.com

#===================== resolv.conf.auto =====================#
# Interface wan
nameserver 211.140.13.188
nameserver 211.140.188.188
# Interface wan_6
nameserver 2409:8028:2000::1111
nameserver 2409:8028:2000::2222

#===================== 测试本机网络连接 =====================#
HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: private, no-cache, no-store, proxy-revalidate, no-transform
Connection: keep-alive
Content-Length: 277
Content-Type: text/html
Date: Sat, 11 Jul 2020 13:54:58 GMT
Etag: "575e1f7c-115"
Last-Modified: Mon, 13 Jun 2016 02:50:36 GMT
Pragma: no-cache
Server: bfe/1.0.8.18


#===================== 测试本机网络下载 =====================#

#===================== 最近运行日志 =====================#

**Comment by vernesong** [comment]
该改的都改回去了啊，你关闭状态下路由自身DNS查询也没问题，你可以关闭IPV6后再尝试一下

**Comment by qin9125** [comment]
我也出现过，无规律，关闭openclash，整个就没网了，但是路由器拨号是正常的，开了openclash就有网，没法子就刷机，就好了，

**Comment by tengyuankoo** [comment]
> 该改的都改回去了啊，你关闭状态下路由自身DNS查询也没问题，你可以关闭IPV6后再尝试一下

关闭IPV6、重启试过很多次都是打不开，在DHCP/DNS里手动指定DNS 转发才能正常上网

**Comment by lichuncat** [comment]
遇见同样的问题，openclash版本好像最近没变化，不知道是不是openwrt 版本的问题，我的固件版本OpenWrt R20.7.7，内核版本5.4.50。

**Comment by lloyd18** [comment]
遇到同样问题

**Comment by tengyuankoo** [comment]
最近一次改动编译后开始这样的

**Comment by tengyuankoo** [comment]
v0.39.4-beta
