### ISSUE TITLE
OpenClash 无日志和 GEOIP 流量问题

### ISSUE THREAD

**Issue by terenceng81** [vernesong/OpenClash#586]
您好，

我使用的是最新版本的 v0.39.2-beta，已选择编译版本为 linux-amd64，处理器架构为 x86_64。

我访问这里查看“日志”，但这里是空白的，貌似日志功能失效。
http://x.x.x.x:9090/ui/#/logs
<a href="https://ibb.co/2gFwFz9"><img src="https://i.ibb.co/2gFwFz9/Screenshot-2020-07-12-at-4-49-02-PM.png" alt="Screenshot-2020-07-12-at-4-49-02-PM" border="0"></a>

另外，在“连接”里头，我看到有 GEOIP 的上载和下载流量，我很肯定的是没有任何用户在使用，为什么还是会产生流量呢？能否把所有 GEOIP 的流量通过“规则”让其使用 Others? 这样就是使用本地流量，不会使用该付费流量了。

附图，供您参考，谢谢。
<a href="https://ibb.co/fk3RJ5S"><img src="https://i.ibb.co/fk3RJ5S/Screenshot-2020-07-10-at-2-21-56-AM.png" alt="Screenshot-2020-07-10-at-2-21-56-AM" border="0"></a>

**Comment by OUZYcn** [comment]
1. 日志为空，你选择日志模式（log level）是什么有关系。 
2. 你用的是Redir-host还是Fake-ip模式？
3. Conns这里有Source列可以看到访问源，没有用户不可能有记录。。。
4. “能否把所有 GEOIP 的流量通过“规则”让其使用 Others?” ，需要你自己改动规则，例如“- GeoIP,DIRECT”

**Comment by terenceng81** [comment]
> 1. 日志为空，你选择日志模式（log level）是什么有关系。
> 2. 你用的是Redir-host还是Fake-ip模式？
> 3. Conns这里有Source列可以看到访问源，没有用户不可能有记录。。。
> 4. “能否把所有 GEOIP 的流量通过“规则”让其使用 Others?” ，需要你自己改动规则，例如“- GeoIP,DIRECT”

谢谢您的回复。

1. 我查看了 config file，机场提供的为 log-level: silent，我修改为 log-level: info，重启 openclash 后，其配置还是重设为 log-level: silent。
2. 我用的是 Fake-IP（增强）模式
3.我也觉得没有用户不可能有记录，但是我没法看到谁是访问源，我猜想可能是我家小米的设备。要如何才能显示访问源呢，你看看上面的图，我看得到域名，网络，类型，节点链等，就是没有访问源 source。。
4. 我已经把 “- GEOIP,CN,Proxy” 改为 “- GEOIP,CN,DIRECT” 了，Commit Configurations & Apply Configurations 执行后，设置还是自变更为 "- GEOIP,CN,Proxy”。于是我重新上载修改后的 yaml 文件，设置却生效了，不知哪里出了错。另外，这个修改为 Direct 后，我便无法访问国内网站了，例子 MGtv 里的电影。我在新加坡，我是通过openclash回国访问的，以我的情况为例，我不应该使用 direct？

**Comment by OUZYcn** [comment]
> > 1. 日志为空，你选择日志模式（log level）是什么有关系。
> > 2. 你用的是Redir-host还是Fake-ip模式？
> > 3. Conns这里有Source列可以看到访问源，没有用户不可能有记录。。。
> > 4. “能否把所有 GEOIP 的流量通过“规则”让其使用 Others?” ，需要你自己改动规则，例如“- GeoIP,DIRECT”
> 
> 谢谢您的回复。
> 
> 1. 我查看了 config file，机场提供的为 log-level: silent，我修改为 log-level: info，重启 openclash 后，其配置还是重设为 log-level: silent。

> >  改配置文件

> 2. 我用的是 Fake-IP（增强）模式
>    3.我也觉得没有用户不可能有记录，但是我没法看到谁是访问源，我猜想可能是我家小米的设备。要如何才能显示访问源呢，你看看上面的图，我看得到域名，网络，类型，节点链等，就是没有访问源 source。。

> > 换yacd，openclash带了这个控制面板的，里边可以看到sources

> 3. 我已经把 “- GEOIP,CN,Proxy” 改为 “- GEOIP,CN,DIRECT” 了，Commit Configurations & Apply Configurations 执行后，设置还是自变更为 "- GEOIP,CN,Proxy”。于是我重新上载修改后的 yaml 文件，设置却生效了，不知哪里出了错。另外，这个修改为 Direct 后，我便无法访问国内网站了，例子 MGtv 里的电影。我在新加坡，我是通过openclash回国访问的，以我的情况为例，我不应该使用 direct？

> > 回国啊。。。哪肯定不是 “- GEOIP,CN,DIRECT” 了，，，必须是 “- GEOIP,CN,Proxy” 才对啊 。。。要不然你的IP是海外的，国内媒体服务肯定拒绝的。。。

**Comment by terenceng81** [comment]
谢谢您的回答。
1, 我试了很多次，它还是会重设为 info，我也不知道为什么。
2. 我无法访问 YACD 的控制面板，没有报错，就只是空白一面。 https://192.168.8.18/luci-static/openclash/?hostname=192.168.8.18&port=9090&secret=123456

刚刚 github 有问题的时候我进行了错误排查，发现 YACD 必须使用 http 访问，于是我修改了vi /etc/config/uhttpd文件，我把这行改为  option redirect_https 0，不强制 http 自动转向https，重启之后就能访问 YACD了，发现都是GEOIP 请求，访问源都是小米设备，洗碗机，小爱音箱等。。。

**Comment by terenceng81** [comment]
在 UI 里设置就解决了配置文件一直重设的问题。 全局设置>常规设置>日志等级>Info [信息] 谢谢。
