### ISSUE TITLE
受限模式？

### ISSUE THREAD

**Issue by qin9125** [vernesong/OpenClash#587]
Google 不到答案只能来求助大佬，启动openclash 刚开始看YouTube并没有受限，过一会看YouTube就会变受限模式，这是哪里的问题，是规则还是其他，配置文件里YouTube的广告屏蔽我也删了，一会受限一会不，用其他插件确定不是节点的问题，
![image](https://user-images.githubusercontent.com/32502941/87243050-1b7ae000-c465-11ea-9438-75d3c21fd017.png)

**Comment by OUZYcn** [comment]
感觉不是clash的问题，而是YouTube本身的“限制模式”功能打开了。 
https://zh.wikihow.com/%E5%85%B3%E9%97%ADYouTube%E9%99%90%E5%88%B6%E6%A8%A1%E5%BC%8F

**Comment by qin9125** [comment]
> 感觉不是clash的问题，而是YouTube本身的“限制模式”功能打开了。
> https://zh.wikihow.com/%E5%85%B3%E9%97%ADYouTube%E9%99%90%E5%88%B6%E6%A8%A1%E5%BC%8F

这并不是YouTube的受限模式，我早检查过了，没有打开YouTube的受限模式，这个受限有时候有有时候没有，受限的时候视频评论看不到，你搜索一些视频比如4k，它也会提示你网络管理员开启了受限部分结果被移除，可能还是配置文件的问题但是我找不到跟这个有关系的规则，您有时间帮我看一下规则吗？

**Comment by OUZYcn** [comment]
> > 感觉不是clash的问题，而是YouTube本身的“限制模式”功能打开了。
> > https://zh.wikihow.com/%E5%85%B3%E9%97%ADYouTube%E9%99%90%E5%88%B6%E6%A8%A1%E5%BC%8F
> 
> 这并不是YouTube的受限模式，我早检查过了，没有打开YouTube的受限模式，这个受限有时候有有时候没有，受限的时候视频评论看不到，你搜索一些视频比如4k，它也会提示你网络管理员开启了受限部分结果被移除，可能还是配置文件的问题但是我找不到跟这个有关系的规则，您有时间帮我看一下规则吗？


我的就是这几条了。。。

# 内容：YouTube
# 数量：11条
USER-AGENT,*youtube*
USER-AGENT,YouTube*
USER-AGENT,com.google.ios.youtube*
DOMAIN-KEYWORD,youtube
DOMAIN,youtubei.googleapis.com
DOMAIN,yt3.ggpht.com
DOMAIN-SUFFIX,googlevideo.com
DOMAIN-SUFFIX,gvt2.com
DOMAIN-SUFFIX,youtu.be
DOMAIN-SUFFIX,youtube.com
DOMAIN-SUFFIX,ytimg.com

**Comment by vernesong** [comment]
什么模式

**Comment by qin9125** [comment]
> 什么模式

不管是fake-ip模式还是redir-host 都会在一段时间后变成受限模式
![image](https://user-images.githubusercontent.com/32502941/87294431-6153a900-c536-11ea-9449-5125fabf1509.png)
我有点懵不知道是哪个地方的锅

**Comment by qin9125** [comment]
> > > 感觉不是clash的问题，而是YouTube本身的“限制模式”功能打开了。
> > > https://zh.wikihow.com/%E5%85%B3%E9%97%ADYouTube%E9%99%90%E5%88%B6%E6%A8%A1%E5%BC%8F
> > 
> > 
> > 这并不是YouTube的受限模式，我早检查过了，没有打开YouTube的受限模式，这个受限有时候有有时候没有，受限的时候视频评论看不到，你搜索一些视频比如4k，它也会提示你网络管理员开启了受限部分结果被移除，可能还是配置文件的问题但是我找不到跟这个有关系的规则，您有时间帮我看一下规则吗？
> 
> 我的就是这几条了。。。
> 
> ```
> # 内容：YouTube
> # 数量：11条
> USER-AGENT,*youtube*
> USER-AGENT,YouTube*
> USER-AGENT,com.google.ios.youtube*
> DOMAIN-KEYWORD,youtube
> DOMAIN,youtubei.googleapis.com
> DOMAIN,yt3.ggpht.com
> DOMAIN-SUFFIX,googlevideo.com
> DOMAIN-SUFFIX,gvt2.com
> DOMAIN-SUFFIX,youtu.be
> DOMAIN-SUFFIX,youtube.com
> DOMAIN-SUFFIX,ytimg.com
> ```

能把您的配置文件去除节点信息给我试试吗？不知道哪里的问题，开启openclash 过一阵就会变受限，不是一开就受限
![image](https://user-images.githubusercontent.com/32502941/87294628-995aec00-c536-11ea-9d86-271880e09d91.png)

**Comment by OUZYcn** [comment]
> > > > 感觉不是clash的问题，而是YouTube本身的“限制模式”功能打开了。
> > > > https://zh.wikihow.com/%E5%85%B3%E9%97%ADYouTube%E9%99%90%E5%88%B6%E6%A8%A1%E5%BC%8F
> > > 
> > > 
> > > 这并不是YouTube的受限模式，我早检查过了，没有打开YouTube的受限模式，这个受限有时候有有时候没有，受限的时候视频评论看不到，你搜索一些视频比如4k，它也会提示你网络管理员开启了受限部分结果被移除，可能还是配置文件的问题但是我找不到跟这个有关系的规则，您有时间帮我看一下规则吗？
> > 
> > 
> > 我的就是这几条了。。。
> > ```
> > # 内容：YouTube
> > # 数量：11条
> > USER-AGENT,*youtube*
> > USER-AGENT,YouTube*
> > USER-AGENT,com.google.ios.youtube*
> > DOMAIN-KEYWORD,youtube
> > DOMAIN,youtubei.googleapis.com
> > DOMAIN,yt3.ggpht.com
> > DOMAIN-SUFFIX,googlevideo.com
> > DOMAIN-SUFFIX,gvt2.com
> > DOMAIN-SUFFIX,youtu.be
> > DOMAIN-SUFFIX,youtube.com
> > DOMAIN-SUFFIX,ytimg.com
> > ```
> 
> 能把您的配置文件去除节点信息给我试试吗？不知道哪里的问题，开启openclash 过一阵就会变受限，不是一开就受限
> ![image](https://user-images.githubusercontent.com/32502941/87294628-995aec00-c536-11ea-9d86-271880e09d91.png)

具体你可用https://github.com/tindy2013/subconverter 在默认设置下转成Clash格式，就带了规则库。你试下？

**Comment by qin9125** [comment]
> > > > > 感觉不是clash的问题，而是YouTube本身的“限制模式”功能打开了。
> > > > > https://zh.wikihow.com/%E5%85%B3%E9%97%ADYouTube%E9%99%90%E5%88%B6%E6%A8%A1%E5%BC%8F
> > > > 
> > > > 
> > > > 这并不是YouTube的受限模式，我早检查过了，没有打开YouTube的受限模式，这个受限有时候有有时候没有，受限的时候视频评论看不到，你搜索一些视频比如4k，它也会提示你网络管理员开启了受限部分结果被移除，可能还是配置文件的问题但是我找不到跟这个有关系的规则，您有时间帮我看一下规则吗？
> > > 
> > > 
> > > 我的就是这几条了。。。
> > > ```
> > > # 内容：YouTube
> > > # 数量：11条
> > > USER-AGENT,*youtube*
> > > USER-AGENT,YouTube*
> > > USER-AGENT,com.google.ios.youtube*
> > > DOMAIN-KEYWORD,youtube
> > > DOMAIN,youtubei.googleapis.com
> > > DOMAIN,yt3.ggpht.com
> > > DOMAIN-SUFFIX,googlevideo.com
> > > DOMAIN-SUFFIX,gvt2.com
> > > DOMAIN-SUFFIX,youtu.be
> > > DOMAIN-SUFFIX,youtube.com
> > > DOMAIN-SUFFIX,ytimg.com
> > > ```
> > 
> > 
> > 能把您的配置文件去除节点信息给我试试吗？不知道哪里的问题，开启openclash 过一阵就会变受限，不是一开就受限
> 
> 具体你可用https://github.com/tindy2013/subconverter 在默认设置下转成Clash格式，就带了规则库。你试下？

谢谢，openwrt的openclash是不有bug？今天下午家里来人连接设备有点多也就20台，内存直接被干到2g过，活动连接直接百分之97，网非常卡，youtube也很卡，重启路由才恢复如下图的正常水平，网速也正常了
![image](https://user-images.githubusercontent.com/32502941/87437631-2b3f2380-c621-11ea-81b6-b340f684b953.png)

**Comment by wuchen4588** [comment]
请求删除该规则！！！我的YouTube评论也被受限了[
![`4S9L3 SF1D 2XA70VK@LM3](https://user-images.githubusercontent.com/60568101/89118245-8d7b9d80-d4d6-11ea-8d6a-911c9aa06b62.png)

**Comment by Lonenso** [comment]
你可以尝试把 TLS 的 dns server 移除。
