### ISSUE TITLE
openclash_watchdog.sh 脚本重复运行

### ISSUE THREAD

**Issue by vindia9** [vernesong/OpenClash#588]
你好

OpenWRT版本：`19.07.3`
OpenClash版本：`v0.39.2-beta`

详情：
在 OpenClash 运行状态页面，点击【关闭 OpenClash】，之后再点击【启动 OpenClash】。
SSH 连接 OpenWRT，执行` ps -ef | grep openclash  `命令，可以看到运行了多个`/bin/sh /usr/share/openclash/openclash_watchdog.sh` 的进程。

多个进程可能会导致 dnsmasq 频繁重启（`logread -f`可以看到日志），从而使dns、dhcp失效。(似乎是因为某个`openclash_watchdog.sh` 脚本频繁触发 dnsmasq 重启，导致网络不可用，我才开始寻找这个问题的。)

目前发现的情况是，运行状态页重启 OpenClash、更换配置引起的 OpenClash 重启，都有 `openclash_watchdog.sh` 脚本重复运行的问题。

我的临时土鳖解决方案是，当发现多个 watchdog 时，上去 kill 掉，或者 reboot OpenWRT ....

谢谢！

**Comment by smallst** [comment]
同样有这个问题，为什么关闭了呢 @vindia9 ，是解决了吗？

**Comment by vindia9** [comment]
@smallst 后面我发现我安装的 ps wget curl 这些命令，都是完整版的。完整版和 OpenWRT 精简版的命令有所区别，例如：
完整版ps命令的PID是 $1，但精简版ps的PID是$2。

**Comment by smallst** [comment]
哦哦好，不过我的 openwrt 的ps 是精简版但同样有问题 😂

**Comment by vindia9** [comment]
@smallst 可以手动执行一下脚本检查问题，ps只是其中一个命令。
