### ISSUE TITLE
无法启用ConnersHua(规则集) 规则

### ISSUE THREAD

**Issue by MOOnLyer** [vernesong/OpenClash#589]
选择了一键生成配置文件里的ConnersHua(规则集) 规则
但是无法启动
查看日志 显示 error: unsupported rule type RULE-SET

Openclash 版本为0.39.2

**Comment by OUZYcn** [comment]
提问的智慧
1. Openclash版本、客户端版本
2. 什么神机规则，我还玉皇大帝规则呢。。。

从error信息来说，感觉是规则库更新到clash 1.0的conf字段，你还在用老的openclash
1.0 has many breaking changes: https://github.com/Dreamacro/clash/wiki/Breaking-Changes-in-1.0.0

**Comment by MOOnLyer** [comment]
> 提问的智慧
> 
> 1. Openclash版本、客户端版本
> 2. 什么神机规则，我还玉皇大帝规则呢。。。
> 
> 从error信息来说，感觉是规则库更新到clash 1.0的conf字段，你还在用老的openclash
> 1.0 has many breaking changes: https://github.com/Dreamacro/clash/wiki/Breaking-Changes-in-1.0.0

已根据建议更改issue， 不知道客户端版本是什么意思。 我是安装在OpenWrt R20.4.8上的
openclash应该已经是最新的了

**Comment by OUZYcn** [comment]
> > 提问的智慧
> > 
> > 1. Openclash版本、客户端版本
> > 2. 什么神机规则，我还玉皇大帝规则呢。。。
> > 
> > 从error信息来说，感觉是规则库更新到clash 1.0的conf字段，你还在用老的openclash
> > 1.0 has many breaking changes: https://github.com/Dreamacro/clash/wiki/Breaking-Changes-in-1.0.0
> 
> 已根据建议更改issue， 不知道客户端版本是什么意思。 我是安装在OpenWrt R20.4.8上的
> openclash应该已经是最新的了


“Openclash 版本为0.39.2 ” 这个应该是所谓的 “客户端版本” 
在 “全局设置” - “版本更新” 里边看看，你 “当前【Dev分支】内核版本” 是啥？？更新到premium-29-g99b34e8（我这里显示最新的版本是这个） 理论上就OK了。

**Comment by vernesong** [comment]
装tun内核，ruleset是闭源内核的功能

**Comment by xpn282** [comment]
> 装tun内核，ruleset是闭源内核的功能

0·39·3版是不是只需要下载tun内核，不需要在"全局设置"里运行模式里选tun模式，就可以使用神机规则集了？

我是更新完0·39·3后，无法启动，好像提示需要tun内核，我下载tun内核后，就可以启动了，但全局里并没有选择使用tun模式。

**Comment by vernesong** [comment]
> > 装tun内核，ruleset是闭源内核的功能
> 
> 0·39·3版是不是只需要下载tun内核，不需要在"全局设置"里运行模式里选tun模式，就可以使用神机规则集了？
> 
> 我是更新完0·39·3后，无法启动，好像提示需要tun内核，我下载tun内核后，就可以启动了，但全局里并没有选择使用tun模式。

待会更新一下39.4，我把问题修复一下

**Comment by MOOnLyer** [comment]
> > 装tun内核，ruleset是闭源内核的功能
> 
> 0·39·3版是不是只需要下载tun内核，不需要在"全局设置"里运行模式里选tun模式，就可以使用神机规则集了？
> 
> 我是更新完0·39·3后，无法启动，好像提示需要tun内核，我下载tun内核后，就可以启动了，但全局里并没有选择使用tun模式。

不应该呀 我装了tun内核 但是游戏模式和普通都不能用rule set

**Comment by vernesong** [comment]
游戏模式用不了，另外两个可以
