### ISSUE TITLE
编译无问题,运行报错!

### ISSUE THREAD

**Issue by kmoc** [vernesong/OpenClash#59]
版本OpenWrt SNAPSHOT r11400-d26738bc76 / LuCI Master git-19.308.21829-2ff7d24

Failed to execute cbi dispatcher target for entry '/admin/services/openclash/client'.
The called action terminated with an exception:
/usr/lib/lua/luci/dispatcher.lua:1070: module 'luci.cbi' not found:
	no field package.preload['luci.cbi']
	no file './luci/cbi.lua'
	no file '/usr/share/lua/luci/cbi.lua'
	no file '/usr/share/lua/luci/cbi/init.lua'
	no file '/usr/lib/lua/luci/cbi.lua'
	no file '/usr/lib/lua/luci/cbi/init.lua'
	no file './luci/cbi.so'
	no file '/usr/lib/lua/luci/cbi.so'
	no file '/usr/lib/lua/loadall.so'
	no file './luci.so'
	no file '/usr/lib/lua/luci.so'
	no file '/usr/lib/lua/loadall.so'
stack traceback:
	[C]: in function 'require'
	/usr/lib/lua/luci/dispatcher.lua:1070: in function </usr/lib/lua/luci/dispatcher.lua:1069>

**Comment by vernesong** [comment]
安装luci luci-base

**Comment by kmoc** [comment]
> 安装luci luci-base

我装了没用，新版的luci有改动，见截图
![9106B38F-C10D-4305-80A5-67452F6E7672](https://user-images.githubusercontent.com/32633913/68184238-76f0f600-ffd9-11e9-8406-9adbc4cedf95.png)

**Comment by kmoc** [comment]
编译时候加上luci-compat可以解决问题,正常启动
