### ISSUE TITLE
关于访问控制问题

### ISSUE THREAD

**Issue by lichuncat** [vernesong/OpenClash#590]
我在用openclash有和访问控制有关的问题。由于我的rixcloud机场不让使用BT，如果侦测到有BT流量，就会自动停止服务12小时。因此我在openclash的自定义规则里设置了“- SRC-IP-CIDR,192.168.1.24/32,DIRECT“，以限制我的NAS(BT下载) ip对梯子的访问。我也启用了lhie1第三方规则。但是，没有规律的，rixcloud会因为侦测到我有BT流量而断流。我改用ShadowSocksR Plus+，Hello world， passwall，设置了访问控制后都没有问题。我也测试了openclash，加了访问控制确实网页什么的都打不开google什么的。所以真的不知道问题可能出在哪里。看能否给些建议，非常感谢！

**Comment by icolourful** [comment]
openclash是部署在旁路由的话，bt机可以设置主路由的dns
或者设置仅代理命中规则流量

**Comment by lichuncat** [comment]
openclash不是旁路由，是主路由

**Comment by vernesong** [comment]
src规则放在顶部优先匹配，如果不行暂时是切换到redir模式，然后全局设置里面会多一个访问控制标签，跟ssr一样设置一下即可

**Comment by freeman02** [comment]
我在顶部规则设置如下
- SRC-IP-CIDR,192.168.1.135/32,Proxy
- SRC-IP-CIDR,192.168.1.136/32,Proxy
- SRC-IP-CIDR,192.168.1.137/32,Proxy
- SRC-IP-CIDR,192.168.1.138/32,Proxy
- SRC-IP-CIDR,192.168.1.0/24,DIRECT
本意是后面带proxy走代理，其它的直连，结果失败。必须要redir模式吗

**Comment by lichuncat** [comment]
已把openclash改成旁路由了，但不知道为什么，配置了openclash后，如果openclash关闭了，就浏览不了网页了，必须要把openclash打开。换SSR+就没事。感觉像DNS的问题，但都是按照网上双软路由做的，而且SSR+也没事，不知道问题出在哪里？

**Comment by hcym** [comment]
启动项里面再关闭一次就可以了，以前的版本没这个问题，还是手机用这个比较好，路由器是有点麻烦事

**Comment by lichuncat** [comment]
启动项里面再关闭一次我试了不行。和是不是旁路由没关系。目前的固件版本OpenWrt R20.7.7，内核版本5.4.50。openclash版本最近没变化，不知道是不是openwrt版本带来的问题，或者兼容性等。

**Comment by Yohoa** [comment]
> 
> 
> 我在用openclash有和访问控制有关的问题。由于我的rixcloud机场不让使用BT，如果侦测到有BT流量，就会自动停止服务12小时。因此我在openclash的自定义规则里设置了“- SRC-IP-CIDR,192.168.1.24/32,DIRECT“，以限制我的NAS(BT下载) ip对梯子的访问。我也启用了lhie1第三方规则。但是，没有规律的，rixcloud会因为侦测到我有BT流量而断流。我改用ShadowSocksR Plus+，Hello world， passwall，设置了访问控制后都没有问题。我也测试了openclash，加了访问控制确实网页什么的都打不开google什么的。所以真的不知道问题可能出在哪里。看能否给些建议，非常感谢！

嗨，你解决了吗？

我也是用SRC-IP-CIDR, 来解决访问控制，我不确定是否每一次都管用，但是我在yacd 中观察到connection 是会服从规则的可以的。

**Comment by touzi** [comment]
我也遇到此问题, 我是主路由和旁路由模式都是开启openclash 后无法bt下载, 人人影视也无法下载.

**Comment by vernesong** [comment]
用redir模式下全局设置的访问控制标签来绕过流量，这样设置后流量不会经过clash的

**Comment by milescui** [comment]
为何我使用访问控制设置了黑名单，bt流量还是经过clash

**Comment by vernesong** [comment]
> 为何我使用访问控制设置了黑名单，bt流量还是经过clash

检查ipset和ip-full依赖

**Comment by roninriddle** [comment]
> > 为何我使用访问控制设置了黑名单，bt流量还是经过clash
> 
> 检查ipset和ip-full依赖

可以详细描述一下么，谢谢。
