### ISSUE TITLE
已配置 DOMAIN-SUFFIX,mgtv.com,Proxy，但是 MGTV 不走 Proxy, 却走 GEOIPs

### ISSUE THREAD

**Issue by terenceng81** [vernesong/OpenClash#596]
如题，我是回国的，只有特定网站才需要走 proxy，但是不知道为什么无法正常操作，比如 MGTV，它还是走 GEOIPs (我创建的代理)

我把 - GEOIP,CN,GeoIPs 删除还是不行，我只想特定网站才走我回国的机场，proxy>Auto - UrlTestURL，请问是我的配置文件有错吗？

附上所有配置，只屏蔽了付费的回国机场信息，希望您帮我看看，感激不尽。

**Comment by vernesong** [comment]
加在规则最前面，观察下日志，可能规则不全

**Comment by terenceng81** [comment]
检查并启动都没有问题。

我把- GEOIP,CN,GeoIPs 和 - MATCH,Others 放在规则最前面了，还是不行。- DOMAIN-SUFFIX,mgtv.com,Proxy 并没有走proxy，而是走 GeoIPs
