### ISSUE TITLE
使用负载均衡模式，油管播放会出现谷歌流量异常提示。

### ISSUE THREAD

**Issue by Mazeorz** [vernesong/OpenClash#598]
环境说明：
N1主路由，开启openclash，自制surgio转换成的yaml。
家庭使用，手机1，电脑1，直连wifi使用Openclash代理。

情况说明：
使用配置中的负载均衡策略，手机用了油管APP播放视频后，再用电脑打开油管视频时会弹出谷歌异常提示。
------------
我們的系統檢測到來自您的計算機網絡的異常流量。
請稍後重試您的請求。
------------

配置排查：（关闭openclash，手机和电脑直连wifi，并且各用带负载均衡的代理工具）
手机：Loon 使用同一分流并开启负载均衡策略，情况无异常。
电脑：Clash for win ，与openclash同一配置，情况无异常。

请问这个异常提示该怎么处理，这个异常流量提示太烦人了点。手机用了油管，电脑就看不了太难受了。

**Comment by Mazeorz** [comment]
补充：
用Openclash出现的谷歌流量异常情况 ，是没那个人工解除异常的按钮。难受
![image](https://user-images.githubusercontent.com/67795943/87862158-a4bb7680-c97f-11ea-91c5-fd3dc1c98a8e.png)

**Comment by wuchen4588** [comment]
> 补充：
> 用Openclash出现的谷歌流量异常情况，是没那个人工解除异常的按钮。难受
> ![图片](https://user-images.githubusercontent.com/67795943/87862158-a4bb7680-c97f-11ea-91c5-fd3dc1c98a8e.png)

你尝试清除下浏览器cookie有效果不
