### ISSUE TITLE
启动 OpenClash 后的影响

### ISSUE THREAD

**Issue by terenceng81** [vernesong/OpenClash#599]
您好，我使用双路由回国，USG + OpenWRT，有下面几个问题。

1. 启动 OpenClash 后 OpenWRT 里外网测速变慢

启动 OpenClash 在 OpenWRT 里做外网测速结果
root@OpenWRT:~ speedtest
Retrieving speedtest.net configuration...
Testing from Singtel Fibre Broadband (我的本地外网IP)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by Singtel (Singapore) [6.13 km]: 11.559 ms
Testing download speed................................................................................
Download: 213.29 Mbit/s (下载速度少了近四倍左右)
Testing upload speed......................................................................................................
Upload: 51.32 Mbit/s (上载速度少了近十倍以上)

未启动 OpenClash 在 OpenWRT 里做外网测速结果
root@OpenWRT:~ speedtest
Retrieving speedtest.net configuration...
Testing from Singtel Fibre Broadband (我的本地外网IP)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by Singtel (Singapore) [6.13 km]: 9.385 ms
Testing download speed................................................................................
Download: 839.48 Mbit/s
Testing upload speed......................................................................................................
Upload: 688.33 Mbit/s

2. 可能不是个问题，开启 OpenClash 后，主路由 USG 的防火墙不再工作
Ubiquiti Unifi USG 实体路由 （做DHCP Server）+ OpenWRT 软路由 (做客户第一面向的网关) + ADGuard Home (做内网 DNS)
启动 OpenClash 后，USG 里头的防火墙规则就失效了，未启动 OpenClash没有这个问题。
在 OpenWRT 里的防火墙配置没有问题，我本来的配置是防火墙设在主路由 USG，OpenWRT里的防火墙是直通的，开启 OpenClash后，我必须防火墙规则写在 OpenWRT上，为了阻止家里的小米设备对外网访问。

3. 我想请教下面的配置是什么意思？
- GEOIP,CN,Proxy （这个是指在 GEOIP数据库内的CN中国里有的IP或域名，直接走 Proxy 的意思吗？如果是这样的话，为什么我还要定义类似- DOMAIN-SUFFIX,mgtv.com,Proxy 的规则？）因为我设置了规则，访问mgtv时，如果把这个（GEOIP,CN,Proxy）删掉，流量并没有走proxy，反而是走Others.
- GEOIP,SG,ABC（这个是指在 GEOIP数据库内的SG新加坡里有的IP或域名，直接走 ABC 的意思吗？）
- MATCH,Others，我知道 match 是匹配的意思，但是是匹配什么呢？

**Comment by xfzha0** [comment]
geoip,cn 一般国内用的话是direct。
match是指上面规则没有匹配到的部分由match来匹配走哪，所以放最后

**Comment by terenceng81** [comment]
> geoip,cn 一般国内用的话是direct。
> match是指上面规则没有匹配到的部分由match来匹配走哪，所以放最后

谢谢。
我是回国，所以这个我是用 GEOIP,CN,Proxy。而我的问题是我只是想特定的流量走回国的路线，我使用GEOIP,CN,Proxy后，家里很多小米设备也都自动的访问国内，造成流量浪费。

我如果删掉 GEOIP,CN,Proxy，却造成所有流量走 MATCH,Others，就算我已经有 DOMAIN-SUFFIX,mgtv.com,Proxy 这规则，但是它还是走 Others.
