### ISSUE TITLE
我的openclash成功启动，但是不能分流，上奈飞还是原来的节点，内核是X86

### ISSUE THREAD

**Issue by wdza1234** [vernesong/OpenClash#603]
用香港的节点上网，新加坡的节点看奈飞，但是开启后还是香港，请问各位大神有什么办法解决，部分配置未见如下，其中账号密码特殊处理过！
`redir-port: 7892
port: 7890
socks-port: 7891
ipv6: false
mode: rule
log-level: silent
external-controller: 0.0.0.0:9090
secret: "123456"
allow-lan: true
bind-address: "*"
external-ui: "/usr/share/openclash/dashboard"
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  listen: 127.0.0.1:7874
  fake-ip-filter:
##Custom fake-ip-filter##
  - '*.lan'
  - 'time.windows.com'
  - 'time.nist.gov'
  - 'time.apple.com'
  - 'time.asia.apple.com'
  - '*.ntp.org.cn'
  - '*.openwrt.pool.ntp.org'
  - 'time1.cloud.tencent.com'
  - 'time.ustc.edu.cn'
  - 'pool.ntp.org'
  - 'ntp.ubuntu.com'
  - 'ntp.aliyun.com'
  - 'ntp1.aliyun.com'
  - 'ntp2.aliyun.com'
  - 'ntp3.aliyun.com'
  - 'ntp4.aliyun.com'
  - 'ntp5.aliyun.com'
  - 'ntp6.aliyun.com'
  - 'ntp7.aliyun.com'
  - 'time1.aliyun.com'
  - 'time2.aliyun.com'
  - 'time3.aliyun.com'
  - 'time4.aliyun.com'
  - 'time5.aliyun.com'
  - 'time6.aliyun.com'
  - 'time7.aliyun.com'
  - '*.time.edu.cn'
  - 'time1.apple.com'
  - 'time2.apple.com'
  - 'time3.apple.com'
  - 'time4.apple.com'
  - 'time5.apple.com'
  - 'time6.apple.com'
  - 'time7.apple.com'
  - 'time1.google.com'
  - 'time2.google.com'
  - 'time3.google.com'
  - 'time4.google.com'
  - 'music.163.com'
  - '*.music.163.com'
  - '*.126.net'
  - 'musicapi.taihe.com'
  - 'music.taihe.com'
  - 'songsearch.kugou.com'
  - 'trackercdn.kugou.com'
  - '*.kuwo.cn'
  - 'api-jooxtt.sanook.com'
  - 'api.joox.com'
  - 'joox.com'
  - 'y.qq.com'
  - '*.y.qq.com'
  - 'streamoc.music.tc.qq.com'
  - 'mobileoc.music.tc.qq.com'
  - 'isure.stream.qqmusic.qq.com'
  - 'dl.stream.qqmusic.qq.com'
  - 'aqqmusic.tc.qq.com'
  - 'amobile.music.tc.qq.com'
  - '*.xiami.com'
  - '*.music.migu.cn'
  - 'music.migu.cn'
  - '*.msftconnecttest.com'
  - '*.msftncsi.com'
  - 'localhost.ptlogin2.qq.com'
  - '*.*.*.srv.nintendo.net'
  - '*.*.stun.playstation.net'
  - 'xbox.*.*.microsoft.com'
  - '*.*.xboxlive.com'
##Custom fake-ip-filter END##
  nameserver:
  - 114.114.114.114
  fallback:
  - tls://8.8.8.8:853
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4
#===================== OpenClash-General-Settings =====================#
proxies:
- name: "新加坡节点"
  type: trojan
  server: xxxxxxx
  port: 443
  password: "xxxxxx"
  udp: false
  skip-cert-verify: false
proxy-groups:
- name: Auto - UrlTest
  type: url-test
  proxies:
  - "新加坡节点"
  url: http://www.gstatic.com/generate_204
  interval: "600"
- name: Proxy
  type: select
  proxies:
  - Auto - UrlTest
  - DIRECT
  - "新加坡节点"
- name: Domestic
  type: select
  proxies:
  - DIRECT
  - Proxy
- name: Others
  type: select
  proxies:
  - Proxy
  - DIRECT
  - Domestic
- name: Apple
  type: select
  proxies:
  - DIRECT
  - Proxy
- name: Microsoft
  type: select
  proxies:
  - DIRECT
  - Proxy
- name: Netflix
  type: select
  proxies:
  - GlobalTV
  - DIRECT
  - "新加坡节点"
- name: Spotify
  type: select
  proxies:
  - GlobalTV
  - DIRECT
  - "新加坡节点"
- name: Steam
  type: select
  proxies:
  - DIRECT
  - Proxy
  - "新加坡节点"
- name: AdBlock
  type: select
  proxies:
  - REJECT
  - DIRECT
  - Proxy
- name: AsianTV
  type: select
  proxies:
  - DIRECT
  - Proxy
  - "新加坡节点"
- name: GlobalTV
  type: select
  proxies:
  - Proxy
  - DIRECT
  - "新加坡节点"
- name: Speedtest
  type: select
  proxies:
  - Proxy
  - DIRECT
  - "新加坡节点"
- name: Telegram
  type: select
  proxies:
  - Proxy
  - DIRECT
  - "新加坡节点"
- name: PayPal
type: select
  proxies:
  - DIRECT
  - Proxy
  - "新加坡节点"
- name: Netease Music
  type: select
  proxies:
  - DIRECT
  - Proxy
  - "新加坡节点"`

<img width="606" alt="WX20200720-220953@2x" src="https://user-images.githubusercontent.com/41967480/87949100-2cb49400-cad8-11ea-930e-cb3ae62d99e8.png">
<img width="1336" alt="WX20200720-220921@2x" src="https://user-images.githubusercontent.com/41967480/87949172-435aeb00-cad8-11ea-9c63-601605482094.png">

**Comment by vernesong** [comment]
进控制面板看一下连接情况

**Comment by Edger** [comment]
> 一样的问题，Fake-IP 增强模式，默认代理走香港节点，奈飞走美国节点。但是分流失败，奈飞还是走的香港节点，看日志是使用了美国的节点，但是奈飞首页刷新出来的是香港排行，cmd + shit + r 刷新还是一样。ClashX 启用了 Fake-IP 增强模式就不会有这个问题，使用的是同一个配置订阅。

我的 MacBook Pro 的问题，之前装了 ClashX Pro，现在把 ClashX Pro 关掉，走斐讯 N1 上的 OpenClash 上奈飞始终分流失败，不知道是什么原因。其他电脑和手机都是正常的。
