### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by Yofo-me** [vernesong/OpenClash#606]
在openwrt上无法启动，报错
```
2020/07/22 00:39:55 mmap: cannot allocate memory
2020-07-22 00:39:50 OpenClash Can Not Start, Try Use Backup Rules Start Again
2020/07/22 00:39:57 mmap: cannot allocate memory
2020-07-22 00:39:50 OpenClash Can Not Start, Please Check The Error Info And Try Again
```

**Comment by Yofo-me** [comment]
openwrt内存4g，运行时只占用了400M，排除openwrt本身的内存不够因素。其次，openwrt硬盘大小20G（根分区2G,数据盘18G)。排除硬盘空间不够的原因。

**Comment by OUZYcn** [comment]
openclash 无法启动的**真实原因**是底层 `mmap: cannot allocate memory`
我觉得你可以看看：https://bobcares.com/blog/mmap-failed-cannot-allocate-memory/

**Comment by Yofo-me** [comment]
- > openwrt的实际内存占用

![image](https://user-images.githubusercontent.com/55388087/88133748-63dc8f80-cc15-11ea-8cfa-9e724a49d3cf.png)
![image](https://user-images.githubusercontent.com/55388087/88133977-0137c380-cc16-11ea-8162-54a2d45cd82f.png)

---
- > 硬盘空间

![image](https://user-images.githubusercontent.com/55388087/88133802-866ea880-cc15-11ea-9850-bc7e4a39fc1b.png)
很明显，内存跟硬盘都用大量的空间未使用，且内存可使用的数量在70%及以上

**Comment by RockJohnson503** [comment]
这个问题解决了吗？
