### ISSUE TITLE
错误: OpenClash 启动失败

### ISSUE THREAD

**Issue by prodigychan** [vernesong/OpenClash#607]
2020-07-22 01:00:00 Config 【maying】 Update Successful
time="2020-07-22T01:00:22+08:00" level=fatal msg="Parse config error: invalid mode"
2020-07-22 01:00:16 OpenClash Can Not Start, Try Use Backup Rules Start Again
time="2020-07-22T01:00:26+08:00" level=fatal msg="Parse config error: invalid mode"
2020-07-22 01:00:16 OpenClash Can Not Start, Please Check The Error Info And Try Again

没做过什么修改，一直设定每天1点更新机场配置文件，昨晚自动更新后就直接G了，一直启动失败，试过重装openclash，换旧版本，还原设置，都不行，应该是配置文件出了问题，但是看日志又不知道是哪里出问题，求大神解答，万分感谢。

**Comment by OUZYcn** [comment]
你自己觉得配置文件出了问题，但又不贴出来，你说咋搞？
`time="2020-07-22T01:00:26+08:00" level=fatal msg="Parse config error: invalid mode"`

**Comment by vernesong** [comment]
内核更新一下，配置文件按最新标准

**Comment by prodigychan** [comment]
> 内核更新一下，配置文件按最新标准

重装后更新内核到最新版本，问题解决，thx
