### ISSUE TITLE
Google.com无法访问

### ISSUE THREAD

**Issue by Dragon-son** [vernesong/OpenClash#608]
MATCH选择DIRECT不能访问Google，其他油管什么的都可以访问，只有MATCh选择国外节点时，才能访问Google，规则都包括google.com

**Comment by Dragon-son** [comment]
> MATCH选择DIRECT不能访问Google，其他的油管什么的都可以，MATCH只有选择国外节点，才能访问Google，规则都包括了google.com

**Comment by vernesong** [comment]
那就是规则不全呗，你试试第三方规则
