### ISSUE TITLE
关于Country.mmdb体积问题

### ISSUE THREAD

**Issue by ntgeralt** [vernesong/OpenClash#61]
请问有没有一个方式，让它不依赖3MB的Country.mmdb，我觉得使用150k的chnroute可以满足需求了~

**Comment by vernesong** [comment]
取消依赖的话你可以去内核那提建议，但格式不同的chnroute需要人来维护，否则可能无法使用

**Comment by ntgeralt** [comment]
嗯。另外请问下，我在新路由3执行你的预编译文件使用v2ray tcp节点正常，但使用ws tls节点会提示
certificate signed by unknown authority 

请教一下怎么解决

**Comment by ntgeralt** [comment]
解决了，弄个空壳Country.mmdb
还是老方式比较稳，iptable绕过chnroute
