### ISSUE TITLE
从哪找历史版本下载啊，1.0版本配置文件和原来的不一样了

### ISSUE THREAD

**Issue by OrangeCh** [vernesong/OpenClash#613]

**Comment by STIVW** [comment]
https://github.com/vernesong/OpenClash/releases
![image](https://user-images.githubusercontent.com/48052580/88373365-4e5c9680-cdca-11ea-8e21-49398430e9b3.png)

**Comment by OrangeCh** [comment]
这些都是1.0.0版本啊

**Comment by STIVW** [comment]
这是一个版本。不同CPU架构不同，所以一个版本有好几个cpu版本。

1.0.0这个你得自己找，反正所有版本都在这个网址 ：   https://github.com/vernesong/OpenClash/releases
