### ISSUE TITLE
openclash启动失败

### ISSUE THREAD

**Issue by wuli-taotao-zhen** [vernesong/OpenClash#614]
OpenClash 调试日志

生成时间: 2020-07-24 18:12:44
插件版本: v0.38.1-beta

#===================== 系统信息 =====================#
主机型号: Phicomm K3
固件版本: OpenWrt SNAPSHOT r2532-8f9bc86
LuCI版本: git-20.117.60969-420c61a-1
内核版本: 4.14.180
处理器架构: arm_cortex-a9

#此项在使用Tun模式时应为ACCEPT
防火墙转发: ACCEPT

#此项有值时建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: 

#此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 

#===================== 依赖检查 =====================#
dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
jsonfilter: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
iptables-mod-tproxy: 已安装
kmod-tun(TUN模式): 已安装
luci-compat(Luci-19.07): 未安装

#===================== 内核检查 =====================#
运行状态: 未运行
已选择的架构: linux-armv7

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 
Tun内核文件: 不存在
Tun内核运行权限: 否

Game内核版本: 
Game内核文件: 不存在
Game内核运行权限: 否

Dev内核版本: 
Dev内核文件: 存在
Dev内核运行权限: 正常

#===================== 插件设置 =====================#
当前配置文件: /etc/openclash/config/速鹰.yaml
运行模式: redir-host
默认代理模式: Rule
UDP流量转发: 停用
DNS劫持: 启用
自定义DNS: 停用
IPV6-DNS解析: 停用
禁用Dnsmasq缓存: 停用
自定义规则: 停用
仅允许内网: 停用
仅代理命中规则流量: 启用

#启动异常时建议关闭此项后重试
保留配置: 停用
第三方规则: 停用

#===================== 配置文件 =====================#
#---------------------------------------------------#
## 感谢：https://github.com/Hackl0us/SS-Rule-Snippet
#---------------------------------------------------#

# HTTP 代理端口
port: 7890

# SOCKS5 代理端口
socks-port: 7891

# Linux 和 macOS 的 redir 代理端口
redir-port: 7892

# 允许局域网的连接
allow-lan: true
bind-address: "*"

# 规则模式：Rule（规则） / Global（全局代理）/ Direct（全局直连）
mode: Rule

# 设置日志输出级别 (默认级别：silent，即不输出任何内容，以避免因日志内容过大而导致程序内存溢出）。
# 5 个级别：silent / info / warning / error / debug。级别越高日志输出量越大，越倾向于调试，若需要请自行开启。
log-level: silent
# Clash 的 RESTful API
external-controller: 0.0.0.0:9090

# RESTful API 的口令
secret: "123456"

# 您可以将静态网页资源（如 clash-dashboard）放置在一个目录中，clash 将会服务于 `RESTful API/ui`
# 参数应填写配置目录的相对路径或绝对路径。
# external-ui: folder

external-ui: "/usr/share/openclash/dashboard"
hosts:
##Custom HOSTS##
#  experimental hosts, support wildcard (e.g. *.clash.dev Even *.foo.*.example.com)
#  static domain has a higher priority than wildcard domain (foo.example.com > *.example.com)
#  NOTE: hosts don't work with `fake-ip`

#  '*.clash.dev': 127.0.0.1
#  'alpha.clash.dev': '::1'
##Custom HOSTS END##
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 127.0.0.1:7874
  nameserver:
  - 114.114.114.114
  fallback:
  - tls://8.8.8.8:853
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4

#===================== 防火墙设置 =====================#

#NAT chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    SS_SPEC_WAN_AC  tcp  --  0.0.0.0/0            0.0.0.0/0            /* _SS_SPEC_RULE_ */
2    REDIRECT   udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:53 redir ports 53
3    REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:53 redir ports 53
4    prerouting_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom prerouting rule chain */
5    zone_lan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
6    zone_wan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
7    zone_vpn_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         
1    SS_SPEC_WAN_AC  tcp  --  0.0.0.0/0            0.0.0.0/0            /* _SS_SPEC_RULE_ */

#Mangle chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    mwan3_hook  all  --  0.0.0.0/0            0.0.0.0/0           
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         
1    mwan3_hook  all  --  0.0.0.0/0            0.0.0.0/0           

#===================== 路由表状态 =====================#
#route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.123.1   0.0.0.0         UG    0      0        0 eth0.2
192.168.2.0     0.0.0.0         255.255.255.0   U     0      0        0 br-lan
192.168.123.0   0.0.0.0         255.255.255.0   U     0      0        0 eth0.2
#ip route list
default via 192.168.123.1 dev eth0.2 proto static src 192.168.123.19 
192.168.2.0/24 dev br-lan proto kernel scope link src 192.168.2.1 
192.168.123.0/24 dev eth0.2 proto kernel scope link src 192.168.123.19 
#ip rule show
0:	from all lookup local 
1001:	from all iif eth0.2 lookup main 
2001:	from all fwmark 0x100/0x3f00 lookup 1 
2061:	from all fwmark 0x3d00/0x3f00 blackhole
2062:	from all fwmark 0x3e00/0x3f00 unreachable
32766:	from all lookup main 
32767:	from all lookup default 

#===================== 端口占用状态 =====================#

#===================== 测试本机DNS查询 =====================#
Server:		127.0.0.1
Address:	127.0.0.1#53

Name:      www.baidu.com
www.baidu.com	canonical name = www.a.shifen.com
Name:      www.a.shifen.com
Address 1: 39.156.66.14
Address 2: 39.156.66.18
*** Can't find www.baidu.com: No answer

#===================== resolv.conf.auto =====================#
# Interface wan
nameserver 211.137.191.26
nameserver 218.201.96.130
search k2.to

#===================== 测试本机网络连接 =====================#
HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: private, no-cache, no-store, proxy-revalidate, no-transform
Connection: keep-alive
Content-Length: 277
Content-Type: text/html
Date: Fri, 24 Jul 2020 10:12:46 GMT
Etag: "575e1f60-115"
Last-Modified: Mon, 13 Jun 2016 02:50:08 GMT
Pragma: no-cache
Server: bfe/1.0.8.18

#===================== 测试本机网络下载 =====================#
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 78
Content-Type: text/plain; charset=utf-8
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
ETag: "112d4129394202c4d61a89e5ee8d4a7a1dafcdac0f5963066360769268005bd4"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
Via: 1.1 varnish (Varnish/6.0)
X-GitHub-Request-Id: 1D6A:4625:559AC5:5BB582:5F1AB15F
Accept-Ranges: bytes
Date: Fri, 24 Jul 2020 10:12:47 GMT
Via: 1.1 varnish
X-Served-By: cache-sin18036-SIN
X-Cache: HFM, HIT
X-Cache-Hits: 0, 1
X-Timer: S1595585567.208961,VS0,VE1
Vary: Authorization,Accept-Encoding, Accept-Encoding
Access-Control-Allow-Origin: *
X-Fastly-Request-ID: 0f763754511f885e1c5f8141f483a0618e54c5eb
Expires: Fri, 24 Jul 2020 10:17:47 GMT
Source-Age: 131

#===================== 最近运行日志 =====================#
2020-07-24 17:30:51 Config 【速鹰】 Update Successful
2020-07-24 17:32:20 OpenClash 【Dev】 Core Update Successful
2020-07-24 17:33:59 OpenClash Can Not Start, Please Check The Error Info And Try Again
2020-07-24 17:33:52 GEOIP Database Update Successful
2020-07-24 17:34:37 OpenClash 【Dev】 Core Update Successful
2020-07-24 17:35:24 OpenClash Can Not Start, Please Check The Error Info And Try Again
2020-07-24 17:36:12 OpenClash Can Not Start, Please Check The Error Info And Try Again
2020-07-24 17:36:52 OpenClash 【Dev】 Core Update Error
2020-07-24 17:44:15 OpenClash Can Not Start, Please Check The Error Info And Try Again
2020-07-24 17:47:47 OpenClash 【Tun】 Core Update Error
2020-07-24 17:48:52 OpenClash 【Tun】 Core Update Successful
2020-07-24 17:49:08 OpenClash 【Game】 Core Update Successful
2020-07-24 17:49:56 OpenClash Can Not Start, Please Check The Error Info And Try Again
2020-07-24 18:04:47 OpenClash 【Dev】 Core Update Successful
time="2020-07-24T10:05:07Z" level=fatal msg="Parse config error: ProxyGroup[0]: 'V3-中转1007|广东-新加坡|解锁|x2.0|V2ray' not found"
2020-07-24 18:05:01 OpenClash Can Not Start, Please Check The Error Info And Try Again
time="2020-07-24T10:06:34Z" level=fatal msg="Parse config error: ProxyGroup[0]: 'V3-中转1007|广东-新加坡|解锁|x2.0|V2ray' not found"
2020-07-24 18:06:28 OpenClash Can Not Start, Please Check The Error Info And Try Again
2020-07-24 18:07:06 OpenClash 【Dev】 Core Update Successful
2020-07-24 18:07:27 OpenClash Can Not Start, Please Check The Error Info And Try Again
2020-07-24 18:08:07 OpenClash 【Dev】 Core Update Successful
nohup: failed to run command ‘/etc/openclash/clash’: Exec format error
2020-07-24 18:08:20 OpenClash Can Not Start, Please Check The Error Info And Try Again
2020-07-24 18:08:51 OpenClash 【Dev】 Core Update Error
2020-07-24 18:09:08 OpenClash 【Dev】 Core Update Successful
nohup: failed to run command ‘/etc/openclash/clash’: Exec format error
2020-07-24 18:09:28 OpenClash Can Not Start, Please Check The Error Info And Try Again
2020-07-24 18:10:28 OpenClash 【Dev】 Core Update Successful
2020-07-24 18:10:49 OpenClash Can Not Start, Please Check The Error Info And Try Again
2020-07-24 18:12:20 OpenClash Can Not Start, Please Check The Error Info And Try Again

**Comment by wuli-taotao-zhen** [comment]
![image](https://user-images.githubusercontent.com/34727286/88382042-3856d200-cdda-11ea-9cfb-355d3e5c43d1.png)
启用了dns加速，我看日志文件里面说百度dns找不到

**Comment by wuli-taotao-zhen** [comment]
关闭dns加速之后，新的日志文件
OpenClash 调试日志

生成时间: 2020-07-24 18:21:23
插件版本: v0.38.1-beta

#===================== 系统信息 =====================#
主机型号: Phicomm K3
固件版本: OpenWrt SNAPSHOT r2532-8f9bc86
LuCI版本: git-20.117.60969-420c61a-1
内核版本: 4.14.180
处理器架构: arm_cortex-a9

#此项在使用Tun模式时应为ACCEPT
防火墙转发: ACCEPT

#此项有值时建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: 

#此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 127.0.0.1#7874

#===================== 依赖检查 =====================#
dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
jsonfilter: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
iptables-mod-tproxy: 已安装
kmod-tun(TUN模式): 已安装
luci-compat(Luci-19.07): 未安装

#===================== 内核检查 =====================#
运行状态: 未运行
已选择的架构: linux-armv7

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 
Tun内核文件: 不存在
Tun内核运行权限: 否

Game内核版本: 
Game内核文件: 不存在
Game内核运行权限: 否

Dev内核版本: 
Dev内核文件: 存在
Dev内核运行权限: 正常

#===================== 插件设置 =====================#
当前配置文件: /etc/openclash/config/速鹰.yaml
运行模式: redir-host
默认代理模式: Rule
UDP流量转发: 停用
DNS劫持: 启用
自定义DNS: 停用
IPV6-DNS解析: 停用
禁用Dnsmasq缓存: 停用
自定义规则: 停用
仅允许内网: 停用
仅代理命中规则流量: 启用

#启动异常时建议关闭此项后重试
保留配置: 停用
第三方规则: 停用

#===================== 配置文件 =====================#
#---------------------------------------------------#
## 更新：2020-07-24 05:30:52
## 感谢：https://github.com/Hackl0us/SS-Rule-Snippet
#---------------------------------------------------#

# HTTP 代理端口
port: 7890

# SOCKS5 代理端口
socks-port: 7891

# Linux 和 macOS 的 redir 代理端口
redir-port: 7892

# 允许局域网的连接
allow-lan: true
bind-address: "*"

# 规则模式：Rule（规则） / Global（全局代理）/ Direct（全局直连）
mode: Rule

# 设置日志输出级别 (默认级别：silent，即不输出任何内容，以避免因日志内容过大而导致程序内存溢出）。
# 5 个级别：silent / info / warning / error / debug。级别越高日志输出量越大，越倾向于调试，若需要请自行开启。
log-level: silent
# Clash 的 RESTful API
external-controller: 0.0.0.0:9090

# RESTful API 的口令
secret: "123456"

# 您可以将静态网页资源（如 clash-dashboard）放置在一个目录中，clash 将会服务于 `RESTful API/ui`
# 参数应填写配置目录的相对路径或绝对路径。
# external-ui: folder


external-ui: "/usr/share/openclash/dashboard"
hosts:
##Custom HOSTS##
#  experimental hosts, support wildcard (e.g. *.clash.dev Even *.foo.*.example.com)
#  static domain has a higher priority than wildcard domain (foo.example.com > *.example.com)
#  NOTE: hosts don't work with `fake-ip`

#  '*.clash.dev': 127.0.0.1
#  'alpha.clash.dev': '::1'
##Custom HOSTS END##
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 127.0.0.1:7874
  nameserver:
  - 114.114.114.114
  fallback:
  - tls://8.8.8.8:853
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4

#===================== 防火墙设置 =====================#

#NAT chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    REDIRECT   tcp  --  0.0.0.0/0            8.8.4.4              redir ports 7892
2    REDIRECT   tcp  --  0.0.0.0/0            8.8.8.8              redir ports 7892
3    SS_SPEC_WAN_AC  tcp  --  0.0.0.0/0            0.0.0.0/0            /* _SS_SPEC_RULE_ */
4    prerouting_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom prerouting rule chain */
5    zone_lan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
6    zone_wan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
7    zone_vpn_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
8    REDIRECT   udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:53 redir ports 53
9    REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:53 redir ports 53
10   openclash  tcp  --  0.0.0.0/0            0.0.0.0/0           
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         
1    SS_SPEC_WAN_AC  tcp  --  0.0.0.0/0            0.0.0.0/0            /* _SS_SPEC_RULE_ */

#Mangle chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         

#===================== 路由表状态 =====================#
#route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.123.1   0.0.0.0         UG    0      0        0 eth0.2
192.168.2.0     0.0.0.0         255.255.255.0   U     0      0        0 br-lan
192.168.123.0   0.0.0.0         255.255.255.0   U     0      0        0 eth0.2
#ip route list
default via 192.168.123.1 dev eth0.2 proto static src 192.168.123.19 
192.168.2.0/24 dev br-lan proto kernel scope link src 192.168.2.1 
192.168.123.0/24 dev eth0.2 proto kernel scope link src 192.168.123.19 
#ip rule show
0:	from all lookup local 
1001:	from all iif eth0.2 lookup main 
2001:	from all fwmark 0x100/0x3f00 lookup 1 
2061:	from all fwmark 0x3d00/0x3f00 blackhole
2062:	from all fwmark 0x3e00/0x3f00 unreachable
32766:	from all lookup main 
32767:	from all lookup default 

#===================== 端口占用状态 =====================#

#===================== 测试本机DNS查询 =====================#
Server:		127.0.0.1
Address:	127.0.0.1#53

*** Can't find www.baidu.com: No answer
*** Can't find www.baidu.com: No answer

#===================== resolv.conf.auto =====================#
# Interface wan
nameserver 211.137.191.26
nameserver 218.201.96.130
search k2.to

#===================== 测试本机网络连接 =====================#
HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: private, no-cache, no-store, proxy-revalidate, no-transform
Connection: keep-alive
Content-Length: 277
Content-Type: text/html
Date: Fri, 24 Jul 2020 10:21:30 GMT
Etag: "575e1f60-115"
Last-Modified: Mon, 13 Jun 2016 02:50:08 GMT
Pragma: no-cache
Server: bfe/1.0.8.18


#===================== 测试本机网络下载 =====================#
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 78
Content-Type: text/plain; charset=utf-8
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
ETag: "112d4129394202c4d61a89e5ee8d4a7a1dafcdac0f5963066360769268005bd4"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
Via: 1.1 varnish (Varnish/6.0)
X-GitHub-Request-Id: 1D6A:4625:559AC5:5BB582:5F1AB15F
Accept-Ranges: bytes
Date: Fri, 24 Jul 2020 10:21:31 GMT
Via: 1.1 varnish
X-Served-By: cache-sin18032-SIN
X-Cache: HFM, HIT
X-Cache-Hits: 0, 1
X-Timer: S1595586092.685499,VS0,VE1
Vary: Authorization,Accept-Encoding, Accept-Encoding
Access-Control-Allow-Origin: *
X-Fastly-Request-ID: 8ad9a5e85dad911dc45082e18adf6a40c4b88dd3
Expires: Fri, 24 Jul 2020 10:26:31 GMT
Source-Age: 50


#===================== 最近运行日志 =====================#
2020-07-24 17:32:20 OpenClash 【Dev】 Core Update Successful
2020-07-24 17:33:59 OpenClash Can Not Start, Please Check The Error Info And Try Again
2020-07-24 17:33:52 GEOIP Database Update Successful
2020-07-24 17:34:37 OpenClash 【Dev】 Core Update Successful
2020-07-24 17:35:24 OpenClash Can Not Start, Please Check The Error Info And Try Again
2020-07-24 17:36:12 OpenClash Can Not Start, Please Check The Error Info And Try Again
2020-07-24 17:36:52 OpenClash 【Dev】 Core Update Error
2020-07-24 17:44:15 OpenClash Can Not Start, Please Check The Error Info And Try Again
2020-07-24 17:47:47 OpenClash 【Tun】 Core Update Error
2020-07-24 17:48:52 OpenClash 【Tun】 Core Update Successful
2020-07-24 17:49:08 OpenClash 【Game】 Core Update Successful
2020-07-24 17:49:56 OpenClash Can Not Start, Please Check The Error Info And Try Again
2020-07-24 18:04:47 OpenClash 【Dev】 Core Update Successful
time="2020-07-24T10:05:07Z" level=fatal msg="Parse config error: ProxyGroup[0]: 'V3-中转1007|广东-新加坡|解锁|x2.0|V2ray' not found"
2020-07-24 18:05:01 OpenClash Can Not Start, Please Check The Error Info And Try Again
time="2020-07-24T10:06:34Z" level=fatal msg="Parse config error: ProxyGroup[0]: 'V3-中转1007|广东-新加坡|解锁|x2.0|V2ray' not found"
2020-07-24 18:06:28 OpenClash Can Not Start, Please Check The Error Info And Try Again
2020-07-24 18:07:06 OpenClash 【Dev】 Core Update Successful
2020-07-24 18:07:27 OpenClash Can Not Start, Please Check The Error Info And Try Again
2020-07-24 18:08:07 OpenClash 【Dev】 Core Update Successful
nohup: failed to run command ‘/etc/openclash/clash’: Exec format error
2020-07-24 18:08:20 OpenClash Can Not Start, Please Check The Error Info And Try Again
2020-07-24 18:08:51 OpenClash 【Dev】 Core Update Error
2020-07-24 18:09:08 OpenClash 【Dev】 Core Update Successful
nohup: failed to run command ‘/etc/openclash/clash’: Exec format error
2020-07-24 18:09:28 OpenClash Can Not Start, Please Check The Error Info And Try Again
2020-07-24 18:10:28 OpenClash 【Dev】 Core Update Successful
2020-07-24 18:10:49 OpenClash Can Not Start, Please Check The Error Info And Try Again
2020-07-24 18:12:20 OpenClash Can Not Start, Please Check The Error Info And Try Again
2020-07-24 18:21:05 OpenClash Can Not Start, Please Check The Error Info And Try Again

**Comment by wuli-taotao-zhen** [comment]
# 更新openclash版本之后
OpenClash 调试日志

生成时间: 2020-07-24 18:31:55
插件版本: v0.39.4-beta

#===================== 系统信息 =====================#
主机型号: Phicomm K3
固件版本: OpenWrt SNAPSHOT r2532-8f9bc86
LuCI版本: git-20.117.60969-420c61a-1
内核版本: 4.14.180
处理器架构: arm_cortex-a9

#此项在使用Tun模式时应为ACCEPT
防火墙转发: ACCEPT

#此项有值时建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: 

#此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 127.0.0.1#5333

#===================== 依赖检查 =====================#
dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
jsonfilter: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
iptables-mod-tproxy: 已安装
kmod-tun(TUN模式): 已安装
luci-compat(Luci-19.07): 未安装

#===================== 内核检查 =====================#
运行状态: 未运行
已选择的架构: linux-armv7

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 
Tun内核文件: 不存在
Tun内核运行权限: 否

Game内核版本: 
Game内核文件: 不存在
Game内核运行权限: 否

Dev内核版本: 
Dev内核文件: 存在
Dev内核运行权限: 正常

#===================== 插件设置 =====================#
当前配置文件: /etc/openclash/config/速鹰.yaml
运行模式: fake-ip
默认代理模式: Rule
UDP流量转发: 停用
DNS劫持: 停用
自定义DNS: 停用
IPV6-DNS解析: 停用
禁用Dnsmasq缓存: 停用
自定义规则: 停用
仅允许内网: 停用
仅代理命中规则流量: 启用

#启动异常时建议关闭此项后重试
保留配置: 停用
第三方规则: 停用

#===================== 配置文件 =====================#
#---------------------------------------------------#
## 更新：2020-07-24 05:30:52
## 感谢：https://github.com/Hackl0us/SS-Rule-Snippet
#---------------------------------------------------#

# HTTP 代理端口
port: 7890

# SOCKS5 代理端口
socks-port: 7891

# Linux 和 macOS 的 redir 代理端口
redir-port: 7892

# 允许局域网的连接
allow-lan: true
bind-address: "*"

# 规则模式：Rule（规则） / Global（全局代理）/ Direct（全局直连）
ipv6: false
mode: Rule

# 设置日志输出级别 (默认级别：silent，即不输出任何内容，以避免因日志内容过大而导致程序内存溢出）。
# 5 个级别：silent / info / warning / error / debug。级别越高日志输出量越大，越倾向于调试，若需要请自行开启。
log-level: debug
# Clash 的 RESTful API
external-controller: 0.0.0.0:9090

# RESTful API 的口令
secret: "123456"

# 您可以将静态网页资源（如 clash-dashboard）放置在一个目录中，clash 将会服务于 `RESTful API/ui`
# 参数应填写配置目录的相对路径或绝对路径。
# external-ui: folder


external-ui: "/usr/share/openclash/dashboard"
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  listen: 127.0.0.1:7874
  fake-ip-filter:
##Custom fake-ip-filter##
  - '*.lan'
  - 'time.windows.com'
  - 'time.nist.gov'
  - 'time.apple.com'
  - 'time.asia.apple.com'
  - '*.ntp.org.cn'
  - '*.openwrt.pool.ntp.org'
  - 'time1.cloud.tencent.com'
  - 'time.ustc.edu.cn'
  - 'pool.ntp.org'
  - 'ntp.ubuntu.com'
  - 'ntp.aliyun.com'
  - 'ntp1.aliyun.com'
  - 'ntp2.aliyun.com'
  - 'ntp3.aliyun.com'
  - 'ntp4.aliyun.com'
  - 'ntp5.aliyun.com'
  - 'ntp6.aliyun.com'
  - 'ntp7.aliyun.com'
  - 'time1.aliyun.com'
  - 'time2.aliyun.com'
  - 'time3.aliyun.com'
  - 'time4.aliyun.com'
  - 'time5.aliyun.com'
  - 'time6.aliyun.com'
  - 'time7.aliyun.com'
  - '*.time.edu.cn'
  - 'time1.apple.com'
  - 'time2.apple.com'
  - 'time3.apple.com'
  - 'time4.apple.com'
  - 'time5.apple.com'
  - 'time6.apple.com'
  - 'time7.apple.com'
  - 'time1.google.com'
  - 'time2.google.com'
  - 'time3.google.com'
  - 'time4.google.com'
  - 'music.163.com'
  - '*.music.163.com'
  - '*.126.net'
  - 'musicapi.taihe.com'
  - 'music.taihe.com'
  - 'songsearch.kugou.com'
  - 'trackercdn.kugou.com'
  - '*.kuwo.cn'
  - 'api-jooxtt.sanook.com'
  - 'api.joox.com'
  - 'joox.com'
  - 'y.qq.com'
  - '*.y.qq.com'
  - 'streamoc.music.tc.qq.com'
  - 'mobileoc.music.tc.qq.com'
  - 'isure.stream.qqmusic.qq.com'
  - 'dl.stream.qqmusic.qq.com'
  - 'aqqmusic.tc.qq.com'
  - 'amobile.music.tc.qq.com'
  - '*.xiami.com'
  - '*.music.migu.cn'
  - 'music.migu.cn'
  - '*.msftconnecttest.com'
  - '*.msftncsi.com'
  - 'localhost.ptlogin2.qq.com'
  - '*.*.*.srv.nintendo.net'
  - '*.*.stun.playstation.net'
  - 'xbox.*.*.microsoft.com'
  - '*.*.xboxlive.com'
##Custom fake-ip-filter END##
  nameserver:
  - 114.114.114.114
  fallback:
  - tls://8.8.8.8:853
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4

#===================== 防火墙设置 =====================#

#NAT chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    SS_SPEC_WAN_AC  tcp  --  0.0.0.0/0            0.0.0.0/0            /* _SS_SPEC_RULE_ */
2    prerouting_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom prerouting rule chain */
3    zone_lan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
4    zone_wan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
5    zone_vpn_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
6    REDIRECT   udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:53 redir ports 53
7    REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:53 redir ports 53
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         
1    SS_SPEC_WAN_AC  tcp  --  0.0.0.0/0            0.0.0.0/0            /* _SS_SPEC_RULE_ */

#Mangle chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         

#===================== 路由表状态 =====================#
#route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.123.1   0.0.0.0         UG    0      0        0 eth0.2
192.168.2.0     0.0.0.0         255.255.255.0   U     0      0        0 br-lan
192.168.123.0   0.0.0.0         255.255.255.0   U     0      0        0 eth0.2
#ip route list
default via 192.168.123.1 dev eth0.2 proto static src 192.168.123.19 
192.168.2.0/24 dev br-lan proto kernel scope link src 192.168.2.1 
192.168.123.0/24 dev eth0.2 proto kernel scope link src 192.168.123.19 
#ip rule show
0:	from all lookup local 
1001:	from all iif eth0.2 lookup main 
2001:	from all fwmark 0x100/0x3f00 lookup 1 
2061:	from all fwmark 0x3d00/0x3f00 blackhole
2062:	from all fwmark 0x3e00/0x3f00 unreachable
32766:	from all lookup main 
32767:	from all lookup default 

#===================== 端口占用状态 =====================#

#===================== 测试本机DNS查询 =====================#
Server:		127.0.0.1
Address:	127.0.0.1#53

Name:      www.baidu.com
www.baidu.com	canonical name = www.a.shifen.com
Name:      www.a.shifen.com
Address 1: 39.156.66.18
Address 2: 39.156.66.14
*** Can't find www.baidu.com: No answer

#===================== resolv.conf.auto =====================#
# Interface wan
nameserver 211.137.191.26
nameserver 218.201.96.130
search k2.to

#===================== 测试本机网络连接 =====================#
HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: private, no-cache, no-store, proxy-revalidate, no-transform
Connection: keep-alive
Content-Length: 277
Content-Type: text/html
Date: Fri, 24 Jul 2020 10:31:57 GMT
Etag: "575e1f60-115"
Last-Modified: Mon, 13 Jun 2016 02:50:08 GMT
Pragma: no-cache
Server: bfe/1.0.8.18


#===================== 测试本机网络下载 =====================#

#===================== 最近运行日志 =====================#
2020-07-24 18:30:46 OpenClash Update Successful
2020-07-24 18:31:29 OpenClash Can Not Start, Please Check The Error Info And Try Again

**Comment by vernesong** [comment]
k3是用v5还是v6的内核好像

**Comment by wuli-taotao-zhen** [comment]
> k3是用v5还是v6的内核好像

![image](https://user-images.githubusercontent.com/34727286/88459076-09695a80-cec5-11ea-8593-215453fa8848.png)

**Comment by wuli-taotao-zhen** [comment]
> k3是用v5还是v6的内核好像
使用v5就好了
谢谢大哥，可以了。


![image](https://user-images.githubusercontent.com/34727286/88459591-2738be80-cec9-11ea-9d01-21691d64fc70.png)
