### ISSUE TITLE
如何在更新订阅的时候保留自己添加的节点和策略组配置？

### ISSUE THREAD

**Issue by pwrliang** [vernesong/OpenClash#616]
由于我的机场有墙中墙，我添加了一些自定义规则，走自己搭建的节点。

我在“服务器与策略组管理-服务器节点配置”添加了自己的节点和策略组配置，然后保存。

但是当我更新订阅的时候，我添加的节点和策略组配置会丢失。”服务器与策略组管理“里面有一个保留配置的功能，
但是看到上面的文字说明我有些看不懂。点击启用后，会多出一个“新节点默认策略组”选项，我应该在这个选项里选择什么才能保留自己添加的节点和策略组配置呢？

谢谢

**Comment by vernesong** [comment]
新节点就是指订阅前不在”服务器与策略组管理“页面里的节点，你这种保留配置即可，订阅出来的新节点会加到指定的策略组
