### ISSUE TITLE
fake-ip模式木有了

### ISSUE THREAD

**Issue by lloyd18** [vernesong/OpenClash#617]
最新源码编译，2楼发日志

![Snipaste_2020-07-25_19-25-44](https://user-images.githubusercontent.com/10294460/88455990-b5eb1280-ceac-11ea-8f8d-e60177978993.png)

**Comment by lloyd18** [comment]
OpenClash 调试日志

生成时间: 2020-07-25 19:24:42
插件版本: v0.39.4-beta

#===================== 系统信息 =====================#
主机型号: baytrail baytrail
固件版本: OpenWrt SNAPSHOT r13927-b2f7355eec
LuCI版本: git-20.206.49801-9dc29c0
内核版本: 5.4.52
处理器架构: x86_64

#此项在使用Tun模式时应为ACCEPT
防火墙转发: ACCEPT

#此项有值时建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: 

#此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 127.0.0.1#7874

#===================== 依赖检查 =====================#
dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
jsonfilter: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
iptables-mod-tproxy: 已安装
kmod-tun(TUN模式): 已安装
luci-compat(Luci-19.07): 已安装

#===================== 内核检查 =====================#
运行状态: 运行中
已选择的架构: linux-amd64

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 
Tun内核文件: 不存在
Tun内核运行权限: 否

Game内核版本: 
Game内核文件: 不存在
Game内核运行权限: 否

Dev内核版本: v1.0.0-18-g33a6579
Dev内核文件: 存在
Dev内核运行权限: 正常

#===================== 插件设置 =====================#
当前配置文件: /etc/openclash/config/config.yaml
运行模式: redir-host
默认代理模式: rule
UDP流量转发: 启用
DNS劫持: 启用
自定义DNS: 停用
IPV6-DNS解析: 停用
禁用Dnsmasq缓存: 停用
自定义规则: 停用
仅允许内网: 停用
仅代理命中规则流量: 停用

#启动异常时建议关闭此项后重试
保留配置: 停用
第三方规则: 停用

#===================== 配置文件 =====================#
port: 7890
socks-port: 7891
allow-lan: true
bind-address: "*"
ipv6: false
mode: rule
log-level: silent
external-controller: 0.0.0.0:9090
redir-port: 7892
secret: "123456"
external-ui: "/usr/share/openclash/dashboard"
hosts:
##Custom HOSTS##
#  experimental hosts, support wildcard (e.g. *.clash.dev Even *.foo.*.example.com)
#  static domain has a higher priority than wildcard domain (foo.example.com > *.example.com)
#  NOTE: hosts don't work with `fake-ip`

#  '*.clash.dev': 127.0.0.1
#  'alpha.clash.dev': '::1'
##Custom HOSTS END##
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 127.0.0.1:7874
  nameserver:
  - 114.114.114.114
  - 223.5.5.5
  fallback:
  - https://doh.rixcloud.dev/dns-query
  - tls://8.8.8.8:853
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4

#===================== 防火墙设置 =====================#

#NAT chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    REDIRECT   tcp  --  0.0.0.0/0            8.8.4.4              redir ports 7892
2    REDIRECT   tcp  --  0.0.0.0/0            8.8.8.8              redir ports 7892
3    DOCKER     all  --  0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL
4    prerouting_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom prerouting rule chain */
5    zone_lan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
6    zone_wan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
7    openclash  tcp  --  0.0.0.0/0            0.0.0.0/0           
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         
1    DOCKER     all  --  0.0.0.0/0           !127.0.0.0/8          ADDRTYPE match dst-type LOCAL

#Mangle chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    openclash  udp  --  0.0.0.0/0            0.0.0.0/0           
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         

#===================== 路由表状态 =====================#
#route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.199.1   0.0.0.0         UG    0      0        0 eth1
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
192.168.10.0    0.0.0.0         255.255.255.0   U     0      0        0 br-lan
192.168.199.0   0.0.0.0         255.255.255.0   U     0      0        0 eth1
#ip route list
default via 192.168.199.1 dev eth1 proto static src 192.168.199.222 
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown 
192.168.10.0/24 dev br-lan proto kernel scope link src 192.168.10.1 
192.168.199.0/24 dev eth1 proto kernel scope link src 192.168.199.222 
#ip rule show
0:	from all lookup local
32765:	from all fwmark 0x162 lookup 354
32766:	from all lookup main
32767:	from all lookup default

#===================== 端口占用状态 =====================#
tcp        0      0 :::9090                 :::*                    LISTEN      7641/clash
tcp        0      0 :::7890                 :::*                    LISTEN      7641/clash
tcp        0      0 :::7891                 :::*                    LISTEN      7641/clash
tcp        0      0 :::7892                 :::*                    LISTEN      7641/clash
udp        0      0 127.0.0.1:7874          0.0.0.0:*                           7641/clash
udp        0      0 :::7891                 :::*                                7641/clash
udp        0      0 :::7892                 :::*                                7641/clash

#===================== 测试本机DNS查询 =====================#
Server:		127.0.0.1
Address:	127.0.0.1#53

Name:      www.baidu.com
www.baidu.com	canonical name = www.a.shifen.com
Name:      www.a.shifen.com
Address 1: 14.215.177.38
Address 2: 14.215.177.39
*** Can't find www.baidu.com: No answer

#===================== resolv.conf.d =====================#
# Interface wan
nameserver 192.168.199.1
search lan

#===================== 测试本机网络连接 =====================#
HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: private, no-cache, no-store, proxy-revalidate, no-transform
Connection: keep-alive
Content-Length: 277
Content-Type: text/html
Date: Sat, 25 Jul 2020 11:24:43 GMT
Etag: "575e1f72-115"
Last-Modified: Mon, 13 Jun 2016 02:50:26 GMT
Pragma: no-cache
Server: bfe/1.0.8.18


#===================== 测试本机网络下载 =====================#
HTTP/1.1 200 Connection established

HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 78
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: text/plain; charset=utf-8
ETag: "112d4129394202c4d61a89e5ee8d4a7a1dafcdac0f5963066360769268005bd4"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
Via: 1.1 varnish (Varnish/6.0)
X-GitHub-Request-Id: DDC2:7088:6BD7E:856A3:5F1C11F7
Accept-Ranges: bytes
Date: Sat, 25 Jul 2020 11:24:44 GMT
Via: 1.1 varnish
X-Served-By: cache-hkg17922-HKG
X-Cache: HIT, HIT
X-Cache-Hits: 1, 28
X-Timer: S1595676284.058482,VS0,VE0
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
X-Fastly-Request-ID: f4589cb9432363509d201ef8ae557bab81922e88
Expires: Sat, 25 Jul 2020 11:29:44 GMT
Source-Age: 203


#===================== 最近运行日志 =====================#
2020-07-25 19:19:34 Config Not Found
2020-07-25 19:21:34 Config 【config】 Update Successful
time="2020-07-25T11:21:49Z" level=info msg="Start initial compatible provider 🎯 全球直连"
time="2020-07-25T11:21:49Z" level=info msg="Start initial compatible provider Ⓜ️ 微软服务"
time="2020-07-25T11:21:49Z" level=info msg="Start initial compatible provider 📲 电报信息"
time="2020-07-25T11:21:49Z" level=info msg="Start initial compatible provider 🌍 国外媒体"
time="2020-07-25T11:21:49Z" level=info msg="Start initial compatible provider ♻️ 自动选择"
time="2020-07-25T11:21:49Z" level=info msg="Start initial compatible provider 🔰 节点选择"
time="2020-07-25T11:21:49Z" level=info msg="Start initial compatible provider 🍎 苹果服务"
time="2020-07-25T11:21:49Z" level=info msg="Start initial compatible provider 🛑 全球拦截"
time="2020-07-25T11:21:49Z" level=info msg="Start initial compatible provider 🐟 漏网之鱼"
time="2020-07-25T11:21:49Z" level=info msg="Start initial compatible provider 🌏 国内媒体"
2020-07-25 19:21:40 OpenClash Start Successful

**Comment by vernesong** [comment]
![image](https://user-images.githubusercontent.com/42875168/88458434-a1187a00-cec0-11ea-81c8-3a6b8fe5a7ac.png)

**Comment by lloyd18** [comment]
你好，点了没反应

**Comment by lloyd18** [comment]
> ![image](https://user-images.githubusercontent.com/42875168/88458434-a1187a00-cec0-11ea-81c8-3a6b8fe5a7ac.png)
> 
> 


你好，点了没反应！

**Comment by lloyd18** [comment]
已经没问题了，先就关了
