### ISSUE TITLE
 使用最新版Proxy-Provider 里无法包含新版ssr配置

### ISSUE THREAD

**Issue by a936919** [vernesong/OpenClash#618]
![S00726-01094578](https://user-images.githubusercontent.com/41937411/88462379-86083300-cedd-11ea-9b4d-425c1b5ef615.png)

如图所示
内核也是最新版
相同配置文件在cfw可用

**Comment by xfzha0** [comment]
用tun内核

**Comment by Doraemon2020** [comment]
同问题

**Comment by Doraemon2020** [comment]
![Screenshot](https://user-images.githubusercontent.com/59880367/88508246-e6e45800-d010-11ea-83a4-f348bd3fb8a4.png)

**Comment by vernesong** [comment]
什么内核

**Comment by Doraemon2020** [comment]
更新到v1.0.0-19-g8f00980内核，可以了
