### ISSUE TITLE
使用新版内核后，添加ssr节点启动失败

### ISSUE THREAD

**Issue by STIVW** [vernesong/OpenClash#619]
![image](https://user-images.githubusercontent.com/48052580/88470783-8a5f3b00-cf33-11ea-959a-2d4d5fc9e817.png)

通过clashR连接订阅的。这是节点配置不适配吗？

**Comment by xfzha0** [comment]
不要用clashr，subconverter新版用正常的clash订阅即可，用clashr的话有个参数名称不对应

**Comment by STIVW** [comment]
好多👌🏻
