### ISSUE TITLE
核心程序、GeoIP等总是会下载失败

### ISSUE THREAD

**Issue by riverscn** [vernesong/OpenClash#62]
不知道是墙的干扰还是什么，有没有可以在UI中稳定下载的办法（或者提供一个上传的选项）

**Comment by vernesong** [comment]
fake模式路由器自身会使用代理下载

**Comment by riverscn** [comment]
fake ip模式我也失败了，不知道为什么
而且，我并不希望用fake ip模式
所以为了解决这个问题，我只能手动传文件更新了

**Comment by vernesong** [comment]
订阅是否正常？

**Comment by Mosney** [comment]
![image](https://user-images.githubusercontent.com/22477230/68975690-e57e5100-082e-11ea-963c-8ddbb76b6ce1.png)

同样的问题，直连状态下无法通过[版本更新]自动下载clash core，且不能获取最新版本。 

如果检查更新以及下载功能使用了raw.githubusercontent.com的话，可能是因为DNS污染导致的，大概在[10月底](https://zh.greatfire.org/search/all/raw.githubusercontent.com)的时候raw域名就被污染了，不过看起来最近有所恢复。

**Comment by Mosney** [comment]
刚才注意到系统日志刷的内容 

> Sat Nov 16 22:44:07 2019 daemon.err uhttpd[2722]: /usr/share/openclash/openclash_version.sh: line 6: wget-ssl: not found
> Sat Nov 16 22:44:13 2019 daemon.err uhttpd[2722]: /usr/share/openclash/clash_version.sh: line 6: wget-ssl: not found   

OpenWrt官方源中并没有`wget-ssl`,只有`wget-nossl`

**Comment by Mosney** [comment]
盲猜一个没装wget

**Comment by riverscn** [comment]
果然，把
https://github.com/vernesong/OpenClash/search?q=wget-ssl&unscoped_q=wget-ssl
这些文件里的wget-ssl都改成
`wget --no-check-certificate --quiet --timeout=10 "$version_url" -O $LAST_OPVER`
就没问题了。
p.s. 我用的官方openwrt，安装了系统自带的ssl支持

**Comment by riverscn** [comment]
openwrt 可以安装支持 ssl 的 wget，原版的 wget 不支持 --tries 参数。
要不是 tries 的话解决起来也简单，现在添加 alias 没用，需要手动改一堆 .sh 文件……

**Comment by vernesong** [comment]
原版的最近我没去测试，一般安装wget是可以正常使用的

**Comment by riverscn** [comment]
> 原版的最近我没去测试，一般安装wget是可以正常使用的

1. 原版的 wget 没有 wget-ssl 这个命令
2. 原版的 wget 本身是支持 ssl 的 （依赖 libustream-openssl ca-certificates）
3. 原版的 wget 不支持 --tries 参数

所以这里产生了兼容性问题

**Comment by Mosney** [comment]
```
root@OP19:~# wget-ssl
wget-ssl: missing URL
Usage: wget-ssl [OPTION]... [URL]...

Try `wget-ssl --help' for more options.

```

**Comment by Mosney** [comment]
> > 原版的最近我没去测试，一般安装wget是可以正常使用的
> 
> 1. 原版的 wget 没有 wget-ssl 这个命令
> 2. 原版的 wget 本身是支持 ssl 的 （依赖 libustream-openssl ca-certificates）
> 3. 原版的 wget 不支持 --tries 参数
> 
> 所以这里产生了兼容性问题

你可以尝试更新一下版本

**Comment by riverscn** [comment]
> > > 原版的最近我没去测试，一般安装wget是可以正常使用的
> > 
> > 
> > 
> > 1. 原版的 wget 没有 wget-ssl 这个命令
> > 2. 原版的 wget 本身是支持 ssl 的 （依赖 libustream-openssl ca-certificates）
> > 3. 原版的 wget 不支持 --tries 参数
> > 
> > 所以这里产生了兼容性问题
> 
> 你可以尝试更新一下版本，我这op是19.07rc1，wget是1.20.3

嗯，新版本可以了

**Comment by dalton-chiou** [comment]
抱歉重开这个issue。我的情况是核心程序能下载，Geoip不能。
openwrt自带的wget是busybox版，包名好像叫wget-nossl。其实也能支持https下载，只是需要安装libustream-openssl，再加上 --no-check-certificate 参数。
我是安装了支持SSL的（GNU）wget，但仍然不能通过脚本下载GEOIP。可能是别的原因。（openwrt18.06.5）
我的建议是，既然是为openwrt环境开发的，OpenClash似乎应该优先考虑原版openwrt的兼容问题。比如适当地调整参数和依赖文件。

**Comment by vernesong** [comment]
> 抱歉重开这个issue。我的情况是核心程序能下载，Geoip不能。
> openwrt自带的wget是busybox版，包名好像叫wget-nossl。其实也能支持https下载，只是需要安装libustream-openssl，再加上 --no-check-certificate 参数。
> 我是安装了支持SSL的（GNU）wget，但仍然不能通过脚本下载GEOIP。可能是别的原因。（openwrt18.06.5）
> 我的建议是，既然是为openwrt环境开发的，OpenClash似乎应该优先考虑原版openwrt的兼容问题。比如适当地调整参数和依赖文件。

同样是wget-ssl和--tries的问题？

**Comment by dalton-chiou** [comment]
是。

**Comment by dalton-chiou** [comment]
> 同样是wget-ssl和--tries的问题？
是。
我前面说的不准确。刚才ls -l $(which wget），才注意到从18.06开始，openwrt默认的wget其实是uclient-fetch。

**Comment by xdaniel9** [comment]
一样出现这个问题，opkg install wget还会报错
Collected errors:
 * check_data_file_clashes: Package wget wants to install file /usr/bin/wget
	But that file is already provided by package  * wget-nossl
 * opkg_install_cmd: Cannot install package wget.

**Comment by xdaniel9** [comment]
解决方法：
opkg remove wget-nossl --force-depends && opkg install wget
