### ISSUE TITLE
Redir-Host模式下开启绕过中国大陆IP后电视上Netflix加载不出来

### ISSUE THREAD

**Issue by blycoris** [vernesong/OpenClash#621]
用的终端是xbox，Netflix加载不出来，同时商店应用也加载不出来

**Comment by OUZYcn** [comment]
> 用的终端是xbox，Netflix加载不出来，同时商店应用也加载不出来

yacd里边来源自xbox IP的rule执行情况如何？

**Comment by blycoris** [comment]
很多识别成了直连流量，但是xbox上的youtube是能识别的

**Comment by vernesong** [comment]
规则不全，换个第三方规则

**Comment by blycoris** [comment]
> 规则不全，换个第三方规则

用的花花的规则，应该是识别的不精准

**Comment by tces1** [comment]
电视上的奈飞有的是直接用ip连的 所以规则比较多，不同区的规则还不完全一样，我索性把电视的ip全局代理了
