### ISSUE TITLE
疑似 TUN 模式影响王者荣耀网络链接

### ISSUE THREAD

**Issue by OUZYcn** [vernesong/OpenClash#622]
已选择编译版本 | linux-amd64
处理器架构（OPKG） | x86_64
处理器架构（OS） | x86_64
当前【Dev分支】内核版本 | v1.0.0-19-g8f00980
当前【TUN模式】内核版本 | 2020.07.24.g42c533f
当前客户端版本 | v0.39.5-beta

相同：1. Rule-set一样、*UDP流量转发 启用；2. 在王者中“网络诊断” 各项延迟都很理想。 
差异：使用Redir-Host（兼容）**或者** Redir-Host（TUN）模式。

现象：
1. 在Redir-Host（兼容）模式下，王者中 wi-fi信号延迟情况 正常（65ms）
2. 在Redir-Host（TUN）模式下，wi-fi信号延迟情况**不**正常（>300ms）

BTW: 貌似Redir-Host（兼容）也支持rule-set了？

顺手也测试了**Fake-ip （游戏）** 运行模式，以及**Redir-Host（游戏）**
都采用 **rule策略代理模式** ， 结果：都不支持Rule-set
`time="2020-07-27T10:29:41Z" level=fatal msg="Parse config error: Rules[6] [RULE-SET,反劫持规则,REJECT] error: unsupported rule type RULE-SET"`

**Comment by OUZYcn** [comment]
先说结论：貌似问题出现在【TUN模式】内核版本 | 2020.07.24.g42c533f版本。
验证方法：
1. 将*.qq.com放入fake-ip-filter清单中，使用fake-ip (TUN)模式也是不行，表现是延迟>300ms
2. 然后用[Premium 2020.06.27](https://github.com/Dreamacro/clash/releases/tag/premium)替代，并同样设置fake-ip-filter
```
  fake-ip-filter:
##Custom fake-ip-filter##
  - '*.qq.com'
##Custom fake-ip-filter END##
```
延迟+-65ms 正常了。

**Comment by OUZYcn** [comment]
Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination
1    ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:53
2    REDIRECT   udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:53 redir ports 53
3    REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:53 redir ports 53
4    prerouting_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom prerouting rule chain */
5    zone_lan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */

Chain INPUT (policy ACCEPT)
num  target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination

Chain POSTROUTING (policy ACCEPT)
num  target     prot opt source               destination
1    postrouting_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom postrouting rule chain */
2    zone_lan_postrouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */

Chain MINIUPNPD (1 references)
num  target     prot opt source               destination

Chain MINIUPNPD-POSTROUTING (1 references)
num  target     prot opt source               destination

Chain postrouting_lan_rule (1 references)
num  target     prot opt source               destination

Chain postrouting_rule (1 references)
num  target     prot opt source               destination

Chain postrouting_vpn_rule (1 references)
num  target     prot opt source               destination

Chain prerouting_lan_rule (1 references)
num  target     prot opt source               destination

Chain prerouting_rule (1 references)
num  target     prot opt source               destination

Chain prerouting_vpn_rule (1 references)
num  target     prot opt source               destination

Chain zone_lan_postrouting (1 references)
num  target     prot opt source               destination
1    MINIUPNPD-POSTROUTING  all  --  0.0.0.0/0            0.0.0.0/0
2    postrouting_lan_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom lan postrouting rule chain */

Chain zone_lan_prerouting (1 references)
num  target     prot opt source               destination
1    MINIUPNPD  all  --  0.0.0.0/0            0.0.0.0/0
2    prerouting_lan_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom lan prerouting rule chain */

Chain zone_vpn_postrouting (0 references)
num  target     prot opt source               destination
1    postrouting_vpn_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom vpn postrouting rule chain */
2    FULLCONENAT  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */

Chain zone_vpn_prerouting (0 references)
num  target     prot opt source               destination
1    prerouting_vpn_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom vpn prerouting rule chain */
2    FULLCONENAT  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */

**Comment by OUZYcn** [comment]
哎。。。最后的终极大招是 重置所有设置， 然后用“第三方规则 - ConnersHua(规则集) 规则 ” 自动生成配置。 
结果：Fake-IP（TUN）模式，游戏正常。。。。

**Comment by MOOnLyer** [comment]
这题我会
主要是geoip 的问题 你试下换mmdb就可以了

**Comment by OUZYcn** [comment]
> 这题我会
> 主要是geoip 的问题 你试下换mmdb就可以了

最新版的openclash客户端变更了geoip是Maxmind+ipip的混合geoip mmdb，所以应该更准确的。但我没有启用GeoIP，Direct 
而是我的rule-set里边用了所谓“神机规则”的ChinaDomain.yaml及ChinaIP.yaml

或者你可否贴一下你的config.yaml ？

**Comment by MOOnLyer** [comment]
这个我没试过 我一直都是更新客户端后 直接替换mmdb 一切正常
我用的是自己上传的原版connershua规则集
