### ISSUE TITLE
怎么启动IPv6啊？DNS设置里面没有相应的设置

### ISSUE THREAD

**Issue by li-xunhuan** [vernesong/OpenClash#625]
如图所示
![QQ截图20200728083457](https://user-images.githubusercontent.com/10476982/88605704-4f811280-d0ad-11ea-9a0d-71bb643e86f4.png)

**Comment by vernesong** [comment]
redir普通模式支持

**Comment by li-xunhuan** [comment]
redir普通模式我扶不住梯子。。
不知道为啥，只支持Fake-IP

**Comment by vernesong** [comment]
DNS多选几个
