### ISSUE TITLE
点了第三方配置更新后无法启动

### ISSUE THREAD

**Issue by ding0828** [vernesong/OpenClash#626]
点了第三方配置更新后无法启动

配置文件管理

500 内部服务器错误
对不起，服务器遇到未知错误。

> /usr/lib/lua/luci/dispatcher.lua:381: Failed to execute cbi dispatcher target for entry '/admin/services/openclash/config'.
The called action terminated with an exception:
/usr/lib/lua/luci/template.lua:55: Failed to execute template 'cbi/simpleform'.
A runtime error occured: /usr/lib/lua/luci/template.lua:55: Failed to execute template 'cbi/nullsection'.
A runtime error occured: /usr/lib/lua/luci/template.lua:39: Failed to load template 'openclash/upload'.
Error while parsing template '/usr/lib/lua/luci/view/openclash/upload.htm':
No space left on device
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:381: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:95: in function

**Comment by OUZYcn** [comment]
**No space left on device**
