### ISSUE TITLE
路由登录错误

### ISSUE THREAD

**Issue by ChanterelleFan** [vernesong/OpenClash#628]
V大您好，
更新最新的0.39.6后，输入路由器IP,openwrt管理界面无法打开。OpenClash本身功能正常运行
错误提示为：
/usr/lib/lua/luci/ccache.lua:52: error loading module 'luci.controller.openclash' from file '/usr/lib/lua/luci/controller/openclash.lua':
	/usr/lib/lua/luci/controller/openclash.lua:1: unexpected symbol
stack traceback:
	[C]: in function 'l'
	/usr/lib/lua/luci/ccache.lua:52: in function </usr/lib/lua/luci/ccache.lua:46>
	[C]: in function 'require'
	/usr/lib/lua/luci/dispatcher.lua:430: in function 'createindex'
	/usr/lib/lua/luci/dispatcher.lua:452: in function 'createtree'
	/usr/lib/lua/luci/dispatcher.lua:188: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:95: in function </usr/lib/lua/luci/dispatcher.lua:94>

**Comment by vernesong** [comment]
这块没有变动，重装旧版确认下是不是其他原因

**Comment by sky96111** [comment]
opkg install luci luci-base luci-compat
