### ISSUE TITLE
wan入站流量被prerouting的openclash chain劫持

### ISSUE THREAD

**Issue by tete1030** [vernesong/OpenClash#63]
模式：redir
clash的redir端口绑定在内网ip

问题：我希望在路由器的wan开放一个端口，从公网访问路由器。但是发现仅仅在luci中防火墙的”流量规则“（不是openclash的）添加wan入站规则是不够的，它只会在INPUT chain添加规则。如果此时我尝试连接这个公网端口，数据包在prerouting阶段被openclash的redir规则转向了clash的端口。由于clash仅仅绑定了内网ip端口，导致连接失败。

虽然我可以手动添加iptables规则绕过这个问题，但是这样自带的防火墙失去了设置效力。

建议：在prerouting中的openclash chain绕过所有interface的本机ip

Patch for /etc/init.d/openclash：
```
          iptables -t nat -N openclash
          iptables -t nat -A openclash -d 0.0.0.0/8 -j RETURN
          iptables -t nat -A openclash -d 10.0.0.0/8 -j RETURN
          iptables -t nat -A openclash -d 127.0.0.0/8 -j RETURN
          iptables -t nat -A openclash -d 169.254.0.0/16 -j RETURN
          iptables -t nat -A openclash -d 172.16.0.0/12 -j RETURN
          iptables -t nat -A openclash -d 192.168.0.0/16 -j RETURN
          iptables -t nat -A openclash -d 224.0.0.0/4 -j RETURN
          iptables -t nat -A openclash -d 240.0.0.0/4 -j RETURN
+       iptables -t nat -A openclash -d ${foreach_interface_ip}/32 -j RETURN
          iptables -t nat -A openclash -p tcp -j REDIRECT --to-ports "$proxy_port"
          iptables -t nat -A PREROUTING -p tcp -j openclash
          iptables -t nat -A OUTPUT -p tcp -d 198.18.0.0/16 -j REDIRECT --to-ports "$proxy_port"
```

**Comment by tete1030** [comment]
前几天写的仓促，有什么不明白的我可以进一步说明

**Comment by vernesong** [comment]
设置端口转发后prerouting表应该会添加对应的zone_wan_prerouting规则，这个规则在看门狗的监控下会保证处在openclash前面，所以涉及端口转发的流量一般不会被劫持。
不知道是固件差异还是插件脚本不同，wan端口转发的防火墙规则一般只根据端口，很少根据wan口ip去判断。
你需要发一下相关配置，我复现后可以尽快搞清楚原因

**Comment by tete1030** [comment]
我把思路写一下

我做的是仅仅从wan访问路由器本身的应用端口，不是将wan的端口映射到内网某台电脑端口上，在没有openclash的情况下无需配置zone_wan_prerouting。我只需要在防火墙”流量规则“界面中添加一条入站规则（其实它就是在“INPUT链”添加规则），类似于openwrt自带的许多Allow-XXX规则（比如Allow-ICMP），在特定端口ACCEPT即可。

之所以无需配置zone_wan_prerouting，
1. openwrt系统自带的其他开放端口规则也没有配置该链。你说的“设置端口转发后prerouting表应该会添加对应的zone_wan_prerouting规则”可能指的是端口映射，我不清楚这个会不会自动配置，但是我做的不是端口映射，仅仅是简单的开放端口。
2. 没有openclash时，在PREROUTING阶段，wan入站流量匹配不到相应规则会fallback到PREROUTING链自身的默认policy，也就是ACCEPT。而打开openclash后，该流量无法fallback到默认policy，在中间就被“openclash链”拦截了。

仔细想来，我觉得根源在于，clash不应该处理**目标为内网**和**目标为路由器**的流量。绕过**目标为内网**已经通过绕过“-d 局域网ip”包含在内；而绕过**目标为路由器**现在仅仅在lan端实现，因为wan口不在局域网ip范围内。

为了省去判断哪端是wan，我写成“绕过所有interface的ip”。

近几天在外，暂没法提供具体配置信息，过几天会补上

**Comment by tete1030** [comment]
## 设置

在以下界面
![image](https://user-images.githubusercontent.com/4312115/69493467-ffccc480-0ee9-11ea-99b3-ff723a98379c.png)
设置
![image](https://user-images.githubusercontent.com/4312115/69493488-25f26480-0eea-11ea-86d9-418daad84242.png)

## 防火墙状态

### Filter->INPUT->zone_wan_input （仅在这里产生一条规则）
![image](https://user-images.githubusercontent.com/4312115/69493514-7b2e7600-0eea-11ea-828c-0d38f55faba4.png)

### Nat->PREROUTING
![image](https://user-images.githubusercontent.com/4312115/69493568-2dfed400-0eeb-11ea-8b4c-5ee7a22c9252.png)

### Nat->zone_wan_prerouting （未在这里产生规则）
![image](https://user-images.githubusercontent.com/4312115/69493543-c6488900-0eea-11ea-93da-bb782785ad8c.png)

**Comment by vernesong** [comment]
```
iptables -t nat -A PREROUTING -p tcp -j openclash
```
试试将启动脚本`/etc/init.d/openclash`的上面这条规则改成如下形式，只劫持从br-lan进入的流量
```
iptables -t nat -A PREROUTING -i br-lan -p tcp -j openclash
```

**Comment by tete1030** [comment]
谢谢。这样的workaround确实也没问题，只是仍然假设了lan端的interface叫做br-lan，并且假设了仅有一个lan zone，不够通用。我仍然觉得绕过所有interface ip是更general、consistent并且简单的方法

**Comment by vernesong** [comment]
br-lan 是系统对lan和wifi的统一划分啊，不是随便取的名字

**Comment by tete1030** [comment]
br-lan的取名规则是br-${NETWORK_NAME}，lan是/etc/config/network里可以自定义的网络名
此外如果没有bridge多个端口和wifi（例如可能存在无wifi且仅有两个端口的路由器，一个用于wan一个用于lan），lan的interface名可能是eth0

当然这些是极少数情况，不一定要考虑，就按你那个方法够用了

**Comment by vernesong** [comment]
> br-lan的取名规则是br-${NETWORK_NAME}，lan是/etc/config/network里可以自定义的网络名
> 此外如果没有bridge多个端口和wifi（例如可能存在无wifi且仅有两个端口的路由器，一个用于wan一个用于lan），lan的interface名可能是eth0
> 
> 当然这些是极少数情况，不一定要考虑，就按你那个方法够用了

现在用单臂路由的情况还是比较多的，总之我这样处理的话可能问题会很多，不知道单独return目标是lo口的数据是否可行。
```
iptables -t nat -A openclash -o lo -j RETURN
```
总之还是处理wan口ip比较麻烦的问题，暂时没想到怎么去处理

**Comment by tete1030** [comment]
PREROUTING阶段还未经过routing decision，无从得知-o，这个选项应该是不能用的。即便能用-o，device也应该是目标ip对应的device而不是lo（除非目标ip是127.0.0.1）。比如目标ip是wan的话，-o就是eth1（假设这个是wan的device），这个device应该是根据`ip route show table local`决定的。

突然发现有个很简单的办法，把openclash链添加到zone_lan_prerouting或者prerouting_lan_rule链内，而不是直接在PREROUTING里，其实这就相当于-i br-lan，只不过它能避免自己去获取lan的设备名，这样不管单臂还是多端口桥接应该都没问题

**Comment by fgprodigal** [comment]
Lede是旁路由怎么解？

**Comment by superstaraug** [comment]
遇到了同样的问题，是旁路由模式，只有lan没有wan。内网的网站都无法从外网进行访问。

**Comment by vernesong** [comment]
目前已将绕过了wan口的地址

**Comment by superstaraug** [comment]
> 
> 
> 目前已将绕过了wan口的地址

旁路由模式没有Wan的情况该如何处理，是否可以指点一下进行手动修改。

**Comment by vernesong** [comment]
> > 目前已将绕过了wan口的地址
> 
> 旁路由模式没有Wan的情况该如何处理，是否可以指点一下进行手动修改。

目标是内网的地址也绕过了，redir模式下也不正常？

**Comment by jerrell851** [comment]
> > > 目前已将绕过了wan口的地址
> > 
> > 
> > 旁路由模式没有Wan的情况该如何处理，是否可以指点一下进行手动修改。
> 
> 目标是内网的地址也绕过了，redir模式下也不正常？

请问这个问题解决了吗？我现在使用的是v0.37.5-beta这个版本，依然是转发无效。从外网无法访问防火墙里设置的转发。

**Comment by tete1030** [comment]
问题已经解决了。不介意的话可以贴一下你的防火墙状态
```bash
iptables -t nat -S
```

**Comment by jerrell851** [comment]
iptables -t nat -S
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT
-N MINIUPNPD
-N MINIUPNPD-POSTROUTING
-N openclash
-N postrouting_lan_rule
-N postrouting_rule
-N postrouting_wan_rule
-N prerouting_lan_rule
-N prerouting_rule
-N prerouting_wan_rule
-N zone_lan_postrouting
-N zone_lan_prerouting
-N zone_wan_postrouting
-N zone_wan_prerouting
-A PREROUTING -d 8.8.4.4/32 -p tcp -j REDIRECT --to-ports 7892
-A PREROUTING -d 8.8.8.8/32 -p tcp -j REDIRECT --to-ports 7892
-A PREROUTING -p udp -m udp --dport 53 -j REDIRECT --to-ports 53
-A PREROUTING -p tcp -m tcp --dport 53 -j REDIRECT --to-ports 53
-A PREROUTING -m comment --comment "!fw3: Custom prerouting rule chain" -j prerouting_rule
-A PREROUTING -i br-lan -m comment --comment "!fw3" -j zone_lan_prerouting
-A PREROUTING -i pppoe-wan -m comment --comment "!fw3" -j zone_wan_prerouting
-A PREROUTING -p tcp -j openclash
-A OUTPUT -d 198.18.0.0/16 -p tcp -j REDIRECT --to-ports 7892
-A POSTROUTING -m comment --comment "!fw3: Custom postrouting rule chain" -j postrouting_rule
-A POSTROUTING -o br-lan -m comment --comment "!fw3" -j zone_lan_postrouting
-A POSTROUTING -o pppoe-wan -m comment --comment "!fw3" -j zone_wan_postrouting
-A openclash -d 0.0.0.0/8 -j RETURN
-A openclash -d 10.0.0.0/8 -j RETURN
-A openclash -d 127.0.0.0/8 -j RETURN
-A openclash -d 169.254.0.0/16 -j RETURN
-A openclash -d 172.16.0.0/12 -j RETURN
-A openclash -d 192.168.0.0/16 -j RETURN
-A openclash -d 224.0.0.0/4 -j RETURN
-A openclash -d 240.0.0.0/4 -j RETURN
-A openclash -d 192.168.1.1/32 -j RETURN
-A openclash -d 127.0.0.1/32 -j RETURN
-A openclash -d 220.172.4.228/32 -j RETURN
-A openclash -p tcp -j REDIRECT --to-ports 7892
-A zone_lan_postrouting -m comment --comment "!fw3: Custom lan postrouting rule chain" -j postrouting_lan_rule
-A zone_lan_postrouting -s 192.168.1.0/24 -d 192.168.1.99/32 -p tcp -m tcp --dport 5900 -m comment --comment "!fw3: M7H-VNC (reflection)" -j SNAT --to-source 192.168.1.1
-A zone_lan_postrouting -s 192.168.1.0/24 -d 192.168.1.1/32 -p tcp -m tcp --dport 9090 -m comment --comment "!fw3: Openclash (reflection)" -j SNAT --to-source 192.168.1.1
-A zone_lan_prerouting -m comment --comment "!fw3: Custom lan prerouting rule chain" -j prerouting_lan_rule
-A zone_lan_prerouting -s 192.168.1.0/24 -d 220.172.4.228/32 -p tcp -m tcp --dport 63243 -m comment --comment "!fw3: M7H-VNC (reflection)" -j DNAT --to-destination 192.168.1.99:5900
-A zone_lan_prerouting -s 192.168.1.0/24 -d 220.172.4.228/32 -p tcp -m tcp --dport 8881 -m comment --comment "!fw3: Openclash (reflection)" -j DNAT --to-destination 192.168.1.1:9090
-A zone_wan_postrouting -m comment --comment "!fw3: Custom wan postrouting rule chain" -j postrouting_wan_rule
-A zone_wan_postrouting -j MINIUPNPD-POSTROUTING
-A zone_wan_postrouting -m comment --comment "!fw3" -j MASQUERADE
-A zone_wan_prerouting -m comment --comment "!fw3: Custom wan prerouting rule chain" -j prerouting_wan_rule
-A zone_wan_prerouting -p tcp -m tcp --dport 63243 -m comment --comment "!fw3: M7H-VNC" -j DNAT --to-destination 192.168.1.99:5900
-A zone_wan_prerouting -p tcp -m tcp --dport 8881 -m comment --comment "!fw3: Openclash" -j DNAT --to-destination 192.168.1.1:9090
-A zone_wan_prerouting -j MINIUPNPD

**Comment by vernesong** [comment]
> > > > 目前已将绕过了wan口的地址
> > > 
> > > 
> > > 旁路由模式没有Wan的情况该如何处理，是否可以指点一下进行手动修改。
> > 
> > 
> > 目标是内网的地址也绕过了，redir模式下也不正常？
> 
> 请问这个问题解决了吗？我现在使用的是v0.37.5-beta这个版本，依然是转发无效。从外网无法访问防火墙里设置的转发。

网络情况说清楚，旁路由开openclash，端口转发在主路由设置的话就需要旁路由再转发一次

**Comment by jerrell851** [comment]
> > > > > 目前已将绕过了wan口的地址
> > > > 
> > > > 
> > > > 旁路由模式没有Wan的情况该如何处理，是否可以指点一下进行手动修改。
> > > 
> > > 
> > > 目标是内网的地址也绕过了，redir模式下也不正常？
> > 
> > 
> > 请问这个问题解决了吗？我现在使用的是v0.37.5-beta这个版本，依然是转发无效。从外网无法访问防火墙里设置的转发。
> 
> 网络情况说清楚，旁路由开openclash，端口转发在主路由设置的话就需要旁路由再转发一次

我没用旁路由，我就在主路由上装的OPENCLASH。我昨天翻了一些ISSUE，找到你回复的一个问题，就是把域名加入到高级设置的DNS的域名黑名单里，现在好像解决了，观察几天。

PS:在没有加入黑名单以前，本地解析这个域名返回的是一个局域网地址，现在能返回外部正确的IP啦。

**Comment by matthuo333** [comment]
如果远程访问路由器，为什么不使用zerotier？

**Comment by fgprodigal** [comment]
> 如果远程访问路由器，为什么不使用zerotier？

有公网ip为什么要用别的方式？

**Comment by zzswang** [comment]
> > > > > 目前已将绕过了wan口的地址
> > > > 
> > > > 
> > > > 旁路由模式没有Wan的情况该如何处理，是否可以指点一下进行手动修改。
> > > 
> > > 
> > > 目标是内网的地址也绕过了，redir模式下也不正常？
> > 
> > 
> > 请问这个问题解决了吗？我现在使用的是v0.37.5-beta这个版本，依然是转发无效。从外网无法访问防火墙里设置的转发。
> 
> 网络情况说清楚，旁路由开openclash，端口转发在主路由设置的话就需要旁路由再转发一次

@vernesong 

我发现，旁路由模式下，只要把 openclash 关掉，就可以从主路由直接转发到内网的机器上。开了 openclash 之后，需要从旁路由再转发一次。

**Comment by vernesong** [comment]
因为流量要从clash出去，nat了，旁路设置转发后脚本会绕过那个端口的流量。你可以发现访问旁路由本身是没问题的

**Comment by matthuo333** [comment]
> > > > > > 目前已将绕过了wan口的地址
> 
> > > > > 
> 
> > > > > 
> 
> > > > > 旁路由模式没有Wan的情况该如何处理，是否可以指点一下进行手动修改。
> 
> > > > 
> 
> > > > 
> 
> > > > 目标是内网的地址也绕过了，redir模式下也不正常？
> 
> > > 
> 
> > > 
> 
> > > 请问这个问题解决了吗？我现在使用的是v0.37.5-beta这个版本，依然是转发无效。从外网无法访问防火墙里设置的转发。
> 
> > 
> 
> > 网络情况说清楚，旁路由开openclash，端口转发在主路由设置的话就需要旁路由再转发一次
> 
> 
> 
> @vernesong 
> 
> 
> 
> 我发现，旁路由模式下，只要把 openclash 关掉，就可以从主路由直接转发到内网的机器上。开了 openclash 之后，需要从旁路由再转发一次。不知道这个现象和 @tete1030 说的是不是同一个原因。即便能够通过旁路由转发，网络应该还是有问题，上行会非常慢。

正常旁路由模式，并未出现你的问题。具体拓扑看看？

**Comment by zzswang** [comment]
## 网络拓扑结构

客户的机房，n台物理机搭建的 PVE 集群

- 192.168.0.x 的机器是物理机
- 192.168.100.x 网段的设备都在 PVE 的虚拟机上，包括 旁路由 也是做在虚拟机里

![image](https://user-images.githubusercontent.com/1524745/111567007-36160d80-87d9-11eb-8b41-5baa68e7fb26.png)

## 旁路由桥接开启

![image](https://user-images.githubusercontent.com/1524745/111567146-71184100-87d9-11eb-894b-abb0f857efc5.png)

## 旁路由的配置，基本都是默认值，安装过程参考的这个链接

https://www.10bests.com/install-openwrt-lede-on-pve

旁路由上配置了 zerotier，测试过关掉或者开启，看起来不影响上述结果

## 目前的 workaround

目前暂时没有使用 openclash，改用 shadowsocksplus 插件，外网可以通过主路由的端口映射直接访问内网机器。

**Comment by zzswang** [comment]
## iptables

![image](https://user-images.githubusercontent.com/1524745/111568744-424f9a00-87dc-11eb-84c8-5a7fcd870ba6.png)

**Comment by matthuo333** [comment]
100. 和 0. 机器都受到oc影响？

**Comment by zzswang** [comment]
只有 192.168.100.x 的机器受到 openclash 的影响

192.168.0.x 的机器由于网关是主路由，所以不受影响。开启 openclash 后，依然是可以通过 主路由转发端口到内网的。
