### ISSUE TITLE
我的软路由开启Openclash时YouTube评论受到限制，请求纠正规则

### ISSUE THREAD

**Issue by wuchen4588** [vernesong/OpenClash#630]
求纠正规则，特别影响体验
![`4S9L3 SF1D 2XA70VK@LM3](https://user-images.githubusercontent.com/60568101/89118255-c3b91d00-d4d6-11ea-8608-714f179036f5.png)

**Comment by wuchen4588** [comment]
没有人吗？？？？？

**Comment by STIVW** [comment]
openclash不提供规则。这个问题应该和openclash没关系吧

**Comment by wuchen4588** [comment]
> openclash不提供规则。这个问题应该和openclash没关系吧

不是，我也不知道怎么回事。反正我LEDE在koolss没这个情况，反而在openclash就出现这情况

**Comment by wuchen4588** [comment]
> openclash不提供规则。这个问题应该和openclash没关系吧

你这个参考这个issues，openclash规则的确有问题
https://github.com/vernesong/OpenClash/issues/587

**Comment by STIVW** [comment]
兄弟，openclash不提供规则。规则都是第三方的，可以自己随便修改。

**Comment by STIVW** [comment]
你要是使用的机场订阅链接。那就是机场给你配的规则，一般比较简陋。

你可以使用“lhie1”的规则，很好用
