### ISSUE TITLE
0.39.6 Redir-Host/Fake-IP 模式切换无效

### ISSUE THREAD

**Issue by harleywong** [vernesong/OpenClash#631]
0.39.6 Redir-Host/Fake-IP 切换没有效果，弹窗提示切换成功，但是实际页面没有切换。0.39.3老版本切换方式可以正常切换。

**Comment by vernesong** [comment]
浏览器F12进控制台看下报错信息

**Comment by harleywong** [comment]
![Snipaste_2020-08-05_13-38-28](https://user-images.githubusercontent.com/34861262/89375899-46351d00-d721-11ea-90d4-6bcd4bc81013.png)
好像没有看到什么错误信息，弹窗显示成功，实际上没变化。

**Comment by vernesong** [comment]
console标签

**Comment by harleywong** [comment]
![Snipaste_2020-08-06_08-40-02](https://user-images.githubusercontent.com/34861262/89477663-75e73200-d7c0-11ea-9d4e-65b45aaa021b.png)
![Snipaste_2020-08-06_08-41-26](https://user-images.githubusercontent.com/34861262/89477752-a7f89400-d7c0-11ea-8da1-6cdb1812f7e4.png)

好像也没有什么信息

**Comment by vernesong** [comment]
那就没有问题才对，刷新页面没用的话，你试试
`uci set openclash.config.operation_mode=redir-host >/dev/null 2>&1 && uci commit openclash`

**Comment by harleywong** [comment]
uci set openclash.config.operation_mode=redir-host >/dev/null 2>&1 && uci commit openclash
uci set openclash.config.operation_mode=fake-ip >/dev/null 2>&1 && uci commit openclash
用SSH输入代码可以切换2个模式

**Comment by vernesong** [comment]
那应该是固件的问题，待查

**Comment by harleywong** [comment]
刚刚试了一下，直接和固件一起编译OpenClash，可以切换。
之前固件不编译OpenClash，后安装的就不能切换，不知道是不是有什么依赖。
