### ISSUE TITLE
openclash无法更新内核，手动上传内核无法识别

### ISSUE THREAD

**Issue by wuchen4588** [vernesong/OpenClash#632]
openclash无法更新内核，手动上传内核无法识别
![ND@PT2P9K1ATDHB{(BNLZSJ](https://user-images.githubusercontent.com/60568101/89171060-2bdd3100-d5b3-11ea-91db-1f7f68131327.png)
![NG2T9~M5IXD8JUX {XYMBA2](https://user-images.githubusercontent.com/60568101/89171064-2d0e5e00-d5b3-11ea-86d1-81f1b9dc7e67.png)

**Comment by xfzha0** [comment]
core目录下直接放内核文件，你的多了一层文件夹

**Comment by wuchen4588** [comment]
> core目录下直接放内核文件，你的多了一层文件夹

需要特别改名吗？

**Comment by xfzha0** [comment]
> > core目录下直接放内核文件，你的多了一层文件夹
> 
> 需要特别改名吗？

dev内核就是clash，premium内核是clash_tun

**Comment by STIVW** [comment]
还需要给clash执行权限好像。可以做直接给全部权限

命令：chmod 777 clash

**Comment by wuchen4588** [comment]
> 还需要给clash文件 执行权限好像。可以做直接给全部权限
> 
> 命令：chmod 777 clash

![`$W(7RA15{}1`X9NJT2$OYS](https://user-images.githubusercontent.com/60568101/89311196-447b4300-d6a8-11ea-8229-90d7956cd0bf.png)
他说找不到该文件或指令

**Comment by STIVW** [comment]
兄弟，clash文件在core目录下！

你在root目录下它能找到，才奇怪了😂

你需要先cd到core目录。

**Comment by vernesong** [comment]
路径不对，权限启动脚本会自动给

**Comment by wuchen4588** [comment]
> 兄弟，clash文件在core目录下！
> 
> 你在root目录下它能找到，才奇怪了😂
> 
> 你需要先cd到core目录。

Dev内核是安装成功了，但是其他内核没有安装成功，不知道是什么问题
![T5BEPR84}RKDR$5E{Q{}{DM](https://user-images.githubusercontent.com/60568101/89377766-15ef7d80-d725-11ea-8153-798468ac6221.png)
![YNUG{XIJJ`3DUU$@2UV)VLD](https://user-images.githubusercontent.com/60568101/89377768-16881400-d725-11ea-9eaa-1dcdc9826fad.png)
![}$_~J$MR5U}ASIE ENUXQAH](https://user-images.githubusercontent.com/60568101/89377772-1720aa80-d725-11ea-80c6-305358cd043c.png)

**Comment by STIVW** [comment]
其他内核可以不用安装，Dev内核就够用的。

还有你是文件名字不对，所以没安装成功。tun内核文件名好像是clash_tun

仔细阅读作者的介绍：https://github.com/vernesong/OpenClash/releases/tag/v0.39.6-beta

**Comment by wuchen4588** [comment]
问题已解决，结束该话题，谢谢大佬耐心解答

**Comment by supermansaga** [comment]
2025年，大家还用clash_tun这个核心吗？感觉还停留在2022年7月6日没更新了？Clash Meta核心v1.19.1就是alpha-g368b1e1吗？谢谢。

**Comment by supermansaga** [comment]
> > 感觉还停留在2022年7月6日没更新了？还是说clash_tun 2023.08.17-13-gdcc8d87是最新的？
> 
> 好家伙，22年7月6日哪来的23.08.17
> 
> clash_tun作者删库了，所以这就删库前的最后一版。想了解可以自行搜索`clash 删库`
> 
> > Clash Meta核心v1.19.1就是alpha-g368b1e1吗？谢谢。
> 
> 不是，但无伤大雅， alpha 前缀的每隔几天就会更新
> 
> 现有内核使用未遇到问题可以不用更新

谢谢，如何密切关注这些alpha的更新节奏呢？

**Comment by supermansaga** [comment]
> 

> > 谢谢，如何密切关注这些alpha的更新节奏呢？
> 
> 没必要吧，这玩意随缘更新就好。 真要关注的话，那就 https://github.com/MetaCubeX/mihomo/tree/Alpha

谢谢。看懂了alpha-c7661d7是pre-release alpha，但没看懂alpha-g368b1e1是什么。Non-Clash Meta?
