### ISSUE TITLE
求助，LEDE系统安装openclash依赖环境导致酷软运行状态无法正常显示

### ISSUE THREAD

**Issue by wuchen4588** [vernesong/OpenClash#634]
![G)(KF1(1KFQ(_XKF MHW7UB](https://user-images.githubusercontent.com/60568101/89226085-e8fc7700-d60d-11ea-81db-f79c0a12aa02.png)
真的特别烦，搞的我重置了好多次

**Comment by xfzha0** [comment]
烦就不要用openclash了，连日志什么都不反馈，鬼知道是什么原因导致的？

**Comment by wuchen4588** [comment]
> 烦就不要用openclash了，连日志什么都不反馈，鬼知道是什么原因导致的？

我酷软怎么给你整日志啊？？？？？

**Comment by wuchen4588** [comment]
已经好了，改刷2.33的固件版本了

**Comment by dragonleehomsun** [comment]
有没有不刷回2.33又能解决的办法
