### ISSUE TITLE
不知道哪里设置错误,国内外网站DNS均无法解析

### ISSUE THREAD

**Issue by tsaitung-n** [vernesong/OpenClash#635]
设备:KoolShare LEDE v2.31 x86_64
用途:主路由 (PPPoE拨号)

OpenClash版本:0.39.6-beta
内核:TUN-Premium rev.20200728
模式:Redir-Host (TUN)
网络栈类型:System
代理模式:Script
实验性-绕过中国大陆IP:停用
仅代理命中规则流量:停用
日志等级:Debug
本地DNS劫持:启用
自定义上游DNS服务器:停用

自定义规则:停用
配置文件订阅:使用r**Cloud提供的Premium内核托管模式

日志无输出 ; Dashboard可以看见使用IP连接的流量,但是DNS无法解析,nslookup提示超时。

**Comment by vernesong** [comment]
发调试日志

**Comment by tsaitung-n** [comment]
time="2020-08-05T11:42:39+08:00" level=info msg="Start initial compatible provider AD Block"
time="2020-08-05T11:42:39+08:00" level=info msg="Start initial compatible provider Stream Services"
time="2020-08-05T11:42:39+08:00" level=info msg="Start initial compatible provider Apple Services"
time="2020-08-05T11:42:39+08:00" level=info msg="Start initial compatible provider rixCloud"
time="2020-08-05T11:42:39+08:00" level=info msg="Start initial compatible provider Domestic"
time="2020-08-05T11:42:39+08:00" level=info msg="Start initial compatible provider Netease Music"
time="2020-08-05T11:42:39+08:00" level=info msg="Start initial rule provider Reject Domains"
time="2020-08-05T11:42:39+08:00" level=info msg="Start initial rule provider Netease Music Domains"
time="2020-08-05T11:42:39+08:00" level=info msg="Start initial rule provider Domestic Services IPs"
time="2020-08-05T11:42:39+08:00" level=info msg="Start initial rule provider Reject IPs"
time="2020-08-05T11:42:39+08:00" level=info msg="Start initial rule provider Apple Services Domains"
time="2020-08-05T11:42:39+08:00" level=info msg="Start initial rule provider Stream Services IPs"
time="2020-08-05T11:42:39+08:00" level=info msg="Start initial rule provider Internal"
time="2020-08-05T11:42:39+08:00" level=info msg="Start initial rule provider Global Services IPs"
time="2020-08-05T11:42:39+08:00" level=info msg="Start initial rule provider Domestic Services Domains"
time="2020-08-05T11:42:39+08:00" level=info msg="Start initial rule provider Global Services Domains"
time="2020-08-05T11:42:39+08:00" level=info msg="Start initial rule provider Stream Services Domains"
time="2020-08-05T11:42:39+08:00" level=error msg="Start DNS server error: listen udp 127.0.0.1:5353: bind: address already in use"
time="2020-08-05T11:42:39+08:00" level=info msg="RESTful API listening at: 192.168.1.1:9090"
time="2020-08-05T11:42:39+08:00" level=info msg="HTTP proxy listening at: 192.168.1.1:7890"
time="2020-08-05T11:42:39+08:00" level=info msg="SOCKS proxy listening at: 192.168.1.1:7891"
time="2020-08-05T11:42:39+08:00" level=info msg="Redir proxy listening at: 192.168.1.1:7892"
time="2020-08-05T11:42:39+08:00" level=info msg="Mixed(http+socks5) proxy listening at: 192.168.1.1:8888"
time="2020-08-05T11:42:39+08:00" level=info msg="Tun Proxy listening at: utun(198.18.0.1)"
2020-08-05 11:42:34 OpenClash Start Successful
time="2020-08-05T11:42:45+08:00" level=info msg="[UDP] 58.219.147.51:54321 --> 118.26.252.214 using DIRECT by Script"
time="2020-08-05T11:42:46+08:00" level=info msg="[TCP] 192.168.1.131:37692 --> 58.83.177.192 using DIRECT by Script"
time="2020-08-05T11:42:49+08:00" level=info msg="[TCP] 192.168.1.140:55502 --> 54.222.216.141 using DIRECT by Script"
time="2020-08-05T11:42:50+08:00" level=info msg="[TCP] 192.168.1.140:43566 --> 101.226.49.144 using Domestic by Script"
time="2020-08-05T11:42:51+08:00" level=info msg="[TCP] 192.168.1.140:49274 --> 101.226.49.140 using Domestic by Script"
time="2020-08-05T11:42:52+08:00" level=info msg="[TCP] 192.168.1.140:43570 --> 101.226.49.144 using Domestic by Script"

下略。好像是5353端口被占用了。

**Comment by tsaitung-n** [comment]
我尝试将5353端口改为其他未占用的端口,却出现了新的错误 "fake dns record 198.18.0.3 missing"

> time="2020-08-05T11:42:39+08:00" level=info msg="Start initial compatible provider AD Block"
> time="2020-08-05T11:42:39+08:00" level=info msg="Start initial compatible provider Stream Services"
> time="2020-08-05T11:42:39+08:00" level=info msg="Start initial compatible provider Apple Services"
> time="2020-08-05T11:42:39+08:00" level=info msg="Start initial compatible provider rixCloud"
> time="2020-08-05T11:42:39+08:00" level=info msg="Start initial compatible provider Domestic"
> time="2020-08-05T11:42:39+08:00" level=info msg="Start initial compatible provider Netease Music"
> time="2020-08-05T11:42:39+08:00" level=info msg="Start initial rule provider Reject Domains"
> time="2020-08-05T11:42:39+08:00" level=info msg="Start initial rule provider Netease Music Domains"
> time="2020-08-05T11:42:39+08:00" level=info msg="Start initial rule provider Domestic Services IPs"
> time="2020-08-05T11:42:39+08:00" level=info msg="Start initial rule provider Reject IPs"
> time="2020-08-05T11:42:39+08:00" level=info msg="Start initial rule provider Apple Services Domains"
> time="2020-08-05T11:42:39+08:00" level=info msg="Start initial rule provider Stream Services IPs"
> time="2020-08-05T11:42:39+08:00" level=info msg="Start initial rule provider Internal"
> time="2020-08-05T11:42:39+08:00" level=info msg="Start initial rule provider Global Services IPs"
> time="2020-08-05T11:42:39+08:00" level=info msg="Start initial rule provider Domestic Services Domains"
> time="2020-08-05T11:42:39+08:00" level=info msg="Start initial rule provider Global Services Domains"
> time="2020-08-05T11:42:39+08:00" level=info msg="Start initial rule provider Stream Services Domains"
> time="2020-08-05T11:42:39+08:00" level=error msg="Start DNS server error: listen udp 127.0.0.1:5353: bind: address already in use"
> time="2020-08-05T11:42:39+08:00" level=info msg="RESTful API listening at: 192.168.1.1:9090"
> time="2020-08-05T11:42:39+08:00" level=info msg="HTTP proxy listening at: 192.168.1.1:7890"
> time="2020-08-05T11:42:39+08:00" level=info msg="SOCKS proxy listening at: 192.168.1.1:7891"
> time="2020-08-05T11:42:39+08:00" level=info msg="Redir proxy listening at: 192.168.1.1:7892"
> time="2020-08-05T11:42:39+08:00" level=info msg="Mixed(http+socks5) proxy listening at: 192.168.1.1:8888"
> time="2020-08-05T11:42:39+08:00" level=info msg="Tun Proxy listening at: utun(198.18.0.1)"
> 2020-08-05 11:42:34 OpenClash Start Successful
> time="2020-08-05T11:42:45+08:00" level=info msg="[UDP] 58.219.147.51:54321 --> 118.26.252.214 using DIRECT by Script"
> time="2020-08-05T11:42:46+08:00" level=info msg="[TCP] 192.168.1.131:37692 --> 58.83.177.192 using DIRECT by Script"
> time="2020-08-05T11:42:49+08:00" level=info msg="[TCP] 192.168.1.140:55502 --> 54.222.216.141 using DIRECT by Script"
> time="2020-08-05T11:42:50+08:00" level=info msg="[TCP] 192.168.1.140:43566 --> 101.226.49.144 using Domestic by Script"
> time="2020-08-05T11:42:51+08:00" level=info msg="[TCP] 192.168.1.140:49274 --> 101.226.49.140 using Domestic by Script"
> time="2020-08-05T11:42:52+08:00" level=info msg="[TCP] 192.168.1.140:43570 --> 101.226.49.144 using Domestic by Script"
> 
> 下略。好像是5353端口被占用了。

**Comment by OUZYcn** [comment]
config中的DNS部分也发出来看看

**Comment by dfly0603** [comment]
> config中的DNS部分也发出来看看

dns:
  enable: true
  ipv6: false
  listen: 127.0.0.1:5354
  enhanced-mode: redir-host
  default-nameserver:
  - 119.29.29.29
  - 119.28.28.28
  fake-ip-filter:
  - '*.lan'
  - localhost.ptlogin2.qq.com
  nameserver:
    - 'https://doh.rixcloud.dev/dns-query'
    - 'https://47.108.56.233/dns-query'
    - 'https://118.31.13.131/dns-query'
    - 'https://120.25.25.166/dns-query'
    - 'https://139.224.112.177/dns-query'
    - 'https://59.110.53.209/dns-query'

另外,重启路由器后,Warning消息似乎消失了。国外网站解析正常了。但是国内网站的解析速度很慢。

**Comment by tsaitung-n** [comment]
> config中的DNS部分也发出来看看

dns:
  enable: true
  ipv6: false
  listen: 127.0.0.1:5354
  enhanced-mode: redir-host
  default-nameserver:
  - 119.29.29.29
  - 119.28.28.28
  fake-ip-filter:
  - '*.lan'
  - localhost.ptlogin2.qq.com
  nameserver:
    - 'https://doh.rixcloud.dev/dns-query'
    - 'https://47.108.56.233/dns-query'
    - 'https://118.31.13.131/dns-query'
    - 'https://120.25.25.166/dns-query'
    - 'https://139.224.112.177/dns-query'
    - 'https://59.110.53.209/dns-query'

重启路由器后,国外网站解析正常了,Warning信息也消失了。不过国内网站解析的速度很慢。
