### ISSUE TITLE
本人openclash想与Adguard home配合使用，但是不知道如何配合SmartDNS配合使用，导致YouTube视频无法播放，google网站无法解析，求大佬帮助

### ISSUE THREAD

**Issue by wuchen4588** [vernesong/OpenClash#636]
![S9I EAE5_$~VMI4GOW1MRB1](https://user-images.githubusercontent.com/60568101/89468104-5abcf800-d7a9-11ea-9ee2-f2e5c45eca4d.png)
![}__TS5CF24I(9RWK_P~~}BR](https://user-images.githubusercontent.com/60568101/89468105-5b558e80-d7a9-11ea-8102-939de91b1eea.png)
![UKC3CD RMW(WCNA3R~7S5AM](https://user-images.githubusercontent.com/60568101/89468107-5bee2500-d7a9-11ea-9bca-31fac98ddebf.png)

**Comment by OUZYcn** [comment]
SmartDNS 就没有多少实际意义，我是不会用它的。
Adguard 的功能一个是DNS（自己及上游）、一个是ad blocking
OpenClash可以指定上游DNS，例如是Adguard ，以及通过规则屏蔽广告。
在屏蔽广告的功能上，Adguard、Clash的原理是一样的，都是通过黑白名单处理流量中的链接关键字。 

因此而言，对于DNS功能而言，仅用OpenClash其实也可以了，顶多加个Adguard 作为上游。
但是两者都启用广告过滤规则就会有机会引起不必要的性能消耗，因为名单有可能是overlap的

**Comment by wuchen4588** [comment]
> SmartDNS 就没有多少实际意义，我是不会用它的。
> Adguard 的功能一个是DNS（自己及上游）、一个是ad blocking
> OpenClash可以指定上游DNS，例如是Adguard ，以及通过规则屏蔽广告。
> 在屏蔽广告的功能上，Adguard、Clash的原理是一样的，都是通过黑白名单处理流量中的链接关键字。
> 
> 因此而言，对于DNS功能而言，仅用OpenClash其实也可以了，顶多加个Adguard 作为上游。
> 但是两者都启用广告过滤规则就会有机会引起不必要的性能消耗，因为名单有可能是overlap的

可是我还是希望能配合Adguard，反正我家100兆小水管耗不了多少CPU，日常闲余资源。而且我主要是针对特别烦人的百度广告配合使用的

**Comment by wuchen4588** [comment]
> SmartDNS 就没有多少实际意义，我是不会用它的。
> Adguard 的功能一个是DNS（自己及上游）、一个是ad blocking
> OpenClash可以指定上游DNS，例如是Adguard ，以及通过规则屏蔽广告。
> 在屏蔽广告的功能上，Adguard、Clash的原理是一样的，都是通过黑白名单处理流量中的链接关键字。
> 
> 因此而言，对于DNS功能而言，仅用OpenClash其实也可以了，顶多加个Adguard 作为上游。
> 但是两者都启用广告过滤规则就会有机会引起不必要的性能消耗，因为名单有可能是overlap的

但是我依然希望能配合使用，这样对于未过滤的规则我可以方便的自定义添加

**Comment by wuchen4588** [comment]
没有人帮我吗？？？？

**Comment by wuchen4588** [comment]
![RA$CG8`_S8IRI 0UO$U%JL5](https://user-images.githubusercontent.com/60568101/89530262-caba9500-d820-11ea-854c-fff96e6447a0.png)
Adguard解析情况，不知道什么原因。一直很迷，明明解析成功了，却一直无法播放

**Comment by wuchen4588** [comment]
已自己解决完毕，停止该话题

**Comment by wuchen4588** [comment]
谢谢各位

**Comment by XiaYi1002** [comment]
> 谢谢各位

老哥怎么解决的可以指导下吗。 这个问题 我也是困扰啊

**Comment by Rxiansheng** [comment]
老哥怎么解决的可以指导下吗。这个问题 我也是困扰啊

**Comment by xihazhiwang** [comment]
> 已自己解决完毕，停止该话题

请问是怎么解决的

**Comment by TheKing1991** [comment]
怎么解决的阿？

**Comment by xihazhiwang** [comment]
> 怎么解决的阿？

用openclash作为第一层dns解析，adguardhome作为openclash的下级dns，也就是adguardhome的dns设置为 openclash的解析地址。
不过现在不用openclash了，直接用ssrplus方便，

**Comment by wuchen4588** [comment]
> 怎么解决的阿？

已经弃用SmartDNS了，因为Adguard home有加了乐缓功能，延迟解析比SmartDNS低了不少，甚至做到0.01ms。推荐直接弃用SmartDNS

**Comment by sean908** [comment]
> > 怎么解决的阿？
> 
> 已经弃用SmartDNS了，因为Adguard home有加了乐缓功能，延迟解析比SmartDNS低了不少，甚至做到0.01ms。推荐直接弃用SmartDNS

现在是 openclash + adguard home?
体验如何啊? 顺便求下配置明细
