### ISSUE TITLE
跑跑卡丁车手游匹配后无法进行游戏

### ISSUE THREAD

**Issue by carson512** [vernesong/OpenClash#639]
跑跑卡丁车无法进行游戏
可以匹配，但是就提示服务器错误
关了Openclash就可以使用。。。
难道必须关闭ipv6么。。。

`OpenClash 调试日志

生成时间: 2020-08-07 09:39:56
插件版本: v0.39.6-beta

#===================== 系统信息 =====================#
主机型号: VMware, Inc. VMware Virtual Platform
固件版本: OpenWrt SNAPSHOT r13243-2f7118712e
LuCI版本: git-20.135.61997-a7d1e25
内核版本: 5.4.41
处理器架构: x86_64

`

**Comment by vernesong** [comment]
用tun\开启udp转发或者redir绕过国内

**Comment by carson512** [comment]
用tun模式解决。。

**Comment by carson512** [comment]
> 用tun\开启udp转发或者redir绕过国内

TUN模式外网映射无法访问。。需要做什么操作嘛？

**Comment by vernesong** [comment]
旁路由？

**Comment by carson512** [comment]
> 旁路由？

正常主路由啊。。
