### ISSUE TITLE
OpenClash v0.39.6-beta 和 Clash 1.0.0 版本 IPv6 配置适配问题

### ISSUE THREAD

**Issue by jakeslee** [vernesong/OpenClash#640]
新版本增加了一个配置项 `ipv6`，和之前的 dns.ipv6 有差别。新配置结构如下：

```
ipv6: false

dns:
  ipv6: false
```

目前 OpenClash 好像会把两个等同一个，没有分开做开关。全局设置里关掉 IPv6 DNS，ipv6 和 dns.ipv6 都会设置为 false。

**Comment by vernesong** [comment]
分开来不好理解，统一管理

**Comment by jakeslee** [comment]
按照我的文档的理解，这两个配置应该是控制不同行为的：

ipv6 是控制 clash dial 的时候是不是同时发起 ipv4 和 ipv6 的请求。在 Fake IP 模式下应该可以支持直连访问 ipv6 资源和 ipv6 的节点。

dns.ipv6 是控制 clash redir-host 模式下是否返回 AAAA 的解析结果。

我的目标是使用 Fake IP 模式访问只有 IPv6 单栈的资源，不知道能否实现。目前如果打开 ipv6，同时使用 redir-host 模式（DHCPv6 开启，内网所有设备均有公网 IPv6 地址），访问内外网络都会有点慢，Chrome 还会偶有访问失败再刷新正常和 Github issue 页头像部分不显示的问题。

如理解有误，敬请指教，谢谢。

**Comment by smallst** [comment]
@jakeslee 同样想要 1 的效果，如果有方法了麻烦告诉我，非常感谢！

**Comment by qq775818258-01-jakeslee-is-fool** [comment]
看不懂，更新OC时路过，过来拜访一下大佬
