### ISSUE TITLE
关于开启Openclash后安卓端的微信，美团等软件的图片加载问题

### ISSUE THREAD

**Issue by billyunver** [vernesong/OpenClash#641]
我在n1盒子上配置了openwrt（gd772 大神的38稳定版），给家里的路由器做软路由（主路由为dir882 刷padavan20200802版本），lan to lan连接。开启openclash，并且按照官方的使用说明调配了选项，软件核心等的安装均为最新版。现在出现的情况就是刚配置成功的时候，前10几分钟或者20几分钟很好用一切正常，但是在过一段时间后（不到一个小时）微信公众号提供的文章里面的图片，朋友圈里面的图片，美团里面的图片都加载不出来，等好几分钟后有时也能加载出来（我也怀疑手机也许是自动调用4g加载出来的，ins 推特都是完全正常的，电脑windows也是正常的。）
![微
![微信截图_20200807112756](https://user-images.githubusercontent.com/69335382/89608008-7823bc00-d8a6-11ea-8803-09a3e99b6556.png)
![微信截图_20200807112811](https://user-images.githubusercontent.com/69335382/89608009-78bc5280-d8a6-11ea-8d54-b185b2b2bfc9.png)
![微信截图_20200807112839](https://user-images.githubusercontent.com/69335382/89608011-7954e900-d8a6-11ea-8163-efbcb38845be.png)

信截图_20200807112850](https://user-images.githubusercontent.com/69335382/89608001-7528cb80-d8a6-11ea-9261-61d87f00f68d.png)
![微信截图_20200807112706](https://user-images.githubusercontent.com/69335382/89608006-778b2580-d8a6-11ea-8a8d-c7ce1a25fe2a.png)

模式为fakeip增强
最开始怀疑是dns问题。其中我最开始使用的是推荐的自定义dns：使用腾讯和阿里的两个dns。这样设置问题会出现。后来把feedback的都点上了，还是会出现同样问题。

请大家给我指点一个方向。感谢！

**Comment by vernesong** [comment]
直连走本地，看看lan口的dns设置。连接异常的去控制面板看连接日志

**Comment by billyunver** [comment]
情况更新：我发现我的安卓手机通过关掉wifi并且重新打开wifi可以短暂解决问题。关了再开就好了，过一会就又不好用了，还得关了再重开，就又好了
![Screenshot_20200808-101538](https://user-images.githubusercontent.com/69335382/89700359-20e22200-d960-11ea-981f-56bc34cdcb32.jpg)

**Comment by xpn282** [comment]
> 情况更新：我发现我的安卓手机通过关掉wifi并且重新打开wifi可以短暂解决问题。关了再开就好了，过一会就又不好用了，还得关了再重开，就又好了
> ![Screenshot_20200808-101538](https://user-images.githubusercontent.com/69335382/89700359-20e22200-d960-11ea-981f-56bc34cdcb32.jpg)
> 请问有了解这个的同志麼！求！


我也有这个现象，不知道是什么原因，有时候需要断开Wi-Fi在重新打开Wi-Fi，才能加载，以前更加严重，现在还好，偶尔会有这样的现象。
不知道是固件的原因，还是Openclash的原因，或者又是规则的原因。。。

**Comment by billyunver** [comment]
情况更新20200808 13:40  :
         我现在也在不断尝试着寻找问题的所在，不断的尝试各种选项的勾选或不勾选所带来的影响。目前锁定的范围是 DNS 连接 规则，订阅文件。因为想到用这个插件的人这么多，但是并没有看到很多人来反映这个问题，所以在自身找毛病。目前做了调整，从上午11时到现在目前一切正常。具体还在观望中。
        目前做的变动：Lan中dns不填主路由，而使用自定义的腾讯与阿里的dns（现在怀疑此次问题的发生是否与主路由老毛子系统或其系统中相关设置有关。）其他选项我贴图片吧。
![0](https://user-images.githubusercontent.com/69335382/89703460-98727a00-d97d-11ea-9933-108242611557.png)
![1](https://user-images.githubusercontent.com/69335382/89703461-9ad4d400-d97d-11ea-80b0-4c3f59d0f6d7.png)
![2](https://user-images.githubusercontent.com/69335382/89703462-9b6d6a80-d97d-11ea-94cf-ed6102e5e082.png)
![3](https://user-images.githubusercontent.com/69335382/89703464-9c9e9780-d97d-11ea-9581-b69b03865b8d.png)
![4](https://user-images.githubusercontent.com/69335382/89703465-9d372e00-d97d-11ea-8b8d-50db060d83ce.png)
![5](https://user-images.githubusercontent.com/69335382/89703466-9e685b00-d97d-11ea-935a-b237d1529f02.png)
![6](https://user-images.githubusercontent.com/69335382/89703467-9f00f180-d97d-11ea-82fc-25406af98642.png)

**Comment by billyunver** [comment]
> > 情况更新：我发现我的安卓手机通过关掉wifi并且重新打开wifi可以短暂解决问题。关了再开就好了，过一会就又不好用了，还得关了再重开，就又好了
> > ![Screenshot_20200808-101538](https://user-images.githubusercontent.com/69335382/89700359-20e22200-d960-11ea-981f-56bc34cdcb32.jpg)
> > 请问有了解这个的同志麼！求！
> 
> 我也有这个现象，不知道是什么原因，有时候需要断开Wi-Fi在重新打开Wi-Fi，才能加载，以前更加严重，现在还好，偶尔会有这样的现象。
> 不知道是固件的原因，还是Openclash的原因，或者又是规则的原因。。。

我想我已经找到问题的所在了

**Comment by billyunver** [comment]
2020-08-09早上九点四十：基本上已经能确定问题所在了。我内核dev没有用这个官方作者提供的，而使用的是Dreamacro提供的内核。从昨天下午三点开始，到现在一切正常。我把我的选择和设置给大家贴出来，供大家参考。
![Screenshot_20200809-094519](https://user-images.githubusercontent.com/69335382/89723161-3cfbc700-da25-11ea-9380-3f4d51d7e298.jpg)
![Screenshot_20200809-094541](https://user-images.githubusercontent.com/69335382/89723164-42f1a800-da25-11ea-8841-e021e5c3be50.jpg)
![Screenshot_20200809-093731](https://user-images.githubusercontent.com/69335382/89723166-4d13a680-da25-11ea-8904-5debbfbd0f1b.jpg)
![Screenshot_20200809-093714](https://user-images.githubusercontent.com/69335382/89723168-500e9700-da25-11ea-855f-7bce3d0ddec4.jpg)
![Screenshot_20200809-093752](https://user-images.githubusercontent.com/69335382/89723169-513fc400-da25-11ea-966f-292c0a9149ef.jpg)
![Screenshot_20200809-093737](https://user-images.githubusercontent.com/69335382/89723170-5270f100-da25-11ea-9bed-3a017db7674a.jpg)

**Comment by YukawaMi** [comment]
感谢分享，我这两天也发现很多APP的图片加载不出来的问题

**Comment by billyunver** [comment]
> 感谢分享，我这两天也发现很多APP的图片加载不出来的问题

总而言之我就是内核用dreamacro得了，并且我并没有使用fake ip，现在一切正常。其他的设置都遵循咱们这个v大的使用说明就可以

**Comment by iKe7vin** [comment]
我没有换内核 我发现的是把【仅代理命中规则流量】和【udp流量转发关了就好了】具体是哪个我也没试 应该是其中之一的问题 前者的可能性大

**Comment by Soct910** [comment]
> 

我试了,什么都没动的情况下,关闭UDP转发,就正常了,没再出现图片加载延迟
