### ISSUE TITLE
lean大的新版openwrt，ipk安装后无法打开全局设置 ，咋整啊大佬们

### ISSUE THREAD

**Issue by xx791117** [vernesong/OpenClash#642]
lean大的新版openwrt，ipk安装后无法打开全局设置 ，咋整啊大佬们
看其他帖子让安装libreadline_7.0-1_x86_64.ipk这个，但是我试了安装这个不能解决~太喜欢openclash了……
![image](https://user-images.githubusercontent.com/17248041/89710954-d7262580-d9b9-11ea-8579-e53d67ab2b2b.png)

**Comment by vernesong** [comment]
装bash没有，检查依赖

**Comment by dl250** [comment]
必须编译进入，直接安装ipk不行，我已经试过了，必要直接编译进入才行

**Comment by xx791117** [comment]
@vernesong 咋检查啊，大佬，不太会啊

**Comment by xx791117** [comment]
@dl250 编译完是不是不好升级啊，我记得大佬的文档里不建议编译进系统

**Comment by wuchen4588** [comment]
> @ dl250编译完是不是不好升级啊，我记得大佬的文档里不建议编译进系统

我之前遇到过，那个是环境依赖包的问题，别装luci环境依赖就解决了，koolshare的LEDE装luci环境依赖包就出这问题

**Comment by wuchen4588** [comment]
> @ dl250编译完是不是不好升级啊，我记得大佬的文档里不建议编译进系统

建议直接重刷，下次别整luci环境

**Comment by xx791117** [comment]
@wuchen4588 luci环境依赖包是哪个呀？

**Comment by wuchen4588** [comment]
> @ wuchen4588 luci环境依赖包是其中呀？

cd /tmp
opkg update
opkg install coreutils-nohup
opkg install bash
opkg install iptables
opkg install dnsmasq-full
opkg install curl
opkg install jsonfilter
opkg install ca-certificates
opkg install ipset
opkg install ip-full
opkg install iptables-mod-tproxy

**Comment by wuchen4588** [comment]
LEDE环境依赖正常安装方法

**Comment by xx791117** [comment]
@wuchen4588  lean的openwrt 是编译出来的啊

**Comment by wuchen4588** [comment]
> @ wuchen4588 lean的openwrt是编译出来的啊

那我不知道了，反正我LEDE装了luci依赖包就出这问题了

**Comment by keke1975** [comment]
我也遇到这个问题，现在还不知道怎么办呢~~~
