### ISSUE TITLE
openclash无法正常识别到内核

### ISSUE THREAD

**Issue by wuchen4588** [vernesong/OpenClash#643]
![~OPUU90R7 K__6G{5FM VHC](https://user-images.githubusercontent.com/60568101/89713130-460a7b00-d9c8-11ea-99e2-a3bd1be9cfe8.png)
![HCQMOJ5OR2S{1BFBP`T78NT](https://user-images.githubusercontent.com/60568101/89713131-460a7b00-d9c8-11ea-88bf-16b78e570e09.png)
![K)8JB%R` 3}7DD5)~(PTZEU](https://user-images.githubusercontent.com/60568101/89713132-473ba800-d9c8-11ea-9462-0d665e31561d.png)
求各位大佬帮忙下，因为之前玩openclash玩蹦了才重装的

**Comment by vernesong** [comment]
直接运行/etc/openclash/core/clash -V 看报错

**Comment by wuchen4588** [comment]
> /etc/openclash/core/clash -V
root@Openwrt:/etc/openclash/core# /etc/openclash/core/clash -V
/etc/openclash/core/clash: line 1: syntax error: unexpected "("
root@Openwrt:/etc/openclash/core#

**Comment by wuchen4588** [comment]
> 直接运行/ etc / openclash / core / clash -V看报错

请问是怎么回事

**Comment by vernesong** [comment]
固件问题，冲刷一下

**Comment by wuchen4588** [comment]
> 固件问题，冲刷一下

这个就是今天重刷的固件了

**Comment by wuchen4588** [comment]
> 固件问题，冲刷一下

我今天中午刷的，固件为koolshare LEDE 2.33

**Comment by wuchen4588** [comment]
重刷安装了，依然是老毛病
![)%RG4 SZDM~2$2ZGJA DH](https://user-images.githubusercontent.com/60568101/89730207-5164b180-da6f-11ea-940f-eb4e36fc70df.png)

**Comment by wuchen4588** [comment]
> 固件问题，冲刷一下

请问这是怎么回事的

**Comment by vernesong** [comment]
去官方那下载内核替换呢

**Comment by wuchen4588** [comment]
> 去官方那下载内核替换呢

已经解决了，感谢V大的帮助。但是我有一个问题，就是关于openclash的DNS的问题，我不知道为什么这个玩意时不时会抽风，导致视频播放无法解析，我之前希望通过SmartDNS和Adguard配合使用免去广告和加速解析，结果带来的是视频无法播放要么就是无法访问，要么提示私密链接有问题。到现在都不在问题的根源。请问这是本身openclash的DNS设置方面有毛病还是DNS根本问题，不管是默认DNS还是三方DNS似乎都有这个毛病

**Comment by wuchen4588** [comment]
> 去官方那下载内核替换呢

整个视频解析效果都比koolss慢很多，这让我的体验变得很差

**Comment by wuchen4588** [comment]
补充下，在redir模式情况下

**Comment by sqzxcv** [comment]
> > 去官方那下载内核替换呢
> 
> 已经解决了，感谢V大的帮助。但是我有一个问题，就是关于openclash的DNS的问题，我不知道为什么这个玩意时不时会抽风，导致视频播放无法解析，我之前希望通过SmartDNS和Adguard配合使用免去广告和加速解析，结果带来的是视频无法播放要么就是无法访问，要么提示私密链接有问题。到现在都不在问题的根源。请问这是本身openclash的DNS设置方面有毛病还是DNS根本问题，不管是默认DNS还是三方DNS似乎都有这个毛病

请问怎么解决的呀
