### ISSUE TITLE
开启OpenClash后 无法在内网使用公网域名访问内网设备

### ISSUE THREAD

**Issue by BigDog66** [vernesong/OpenClash#644]
我安装了阿里云ddns将公网IP解析到自己注册的域名 平时在内网访问自己的内网的设备都是通过 域名:端口访问，一切正常。
安装了Openclash之后 在内网就无法使用域名访问内网设备了。在内网ping自己的域名发现被定向到198.18.0.X 
停用OpenClash之后访问又恢复正常
未开IPV6
请问该如何解决此问题？
![image](https://user-images.githubusercontent.com/69404815/89721327-d370be00-da0e-11ea-8b86-55682d55b37d.png)

![image](https://user-images.githubusercontent.com/69404815/89721131-76740880-da0c-11ea-891c-cb07398e3a91.png)
![image](https://user-images.githubusercontent.com/69404815/89721135-7f64da00-da0c-11ea-8be2-5dd9f1542419.png)
![image](https://user-images.githubusercontent.com/69404815/89721137-91467d00-da0c-11ea-89a1-89a56b280a77.png)
![image](https://user-images.githubusercontent.com/69404815/89721139-986d8b00-da0c-11ea-8204-3fbc5c019027.png)
![image](https://user-images.githubusercontent.com/69404815/89721146-a3282000-da0c-11ea-88a2-ed979440de49.png)
![image](https://user-images.githubusercontent.com/69404815/89721154-ad4a1e80-da0c-11ea-9f23-00f405b84cb8.png)

**Comment by xx791117** [comment]
同问，fake-ip模式，设置了域名黑名单也不行

**Comment by wuchen4588** [comment]
> 我安装了阿里云ddns将公网IP解析到自己注册的域名平时内部网访问自己的内网的设备都是通过域名：端口访问，一切正常。
> 安装了Openclash之后内部网络就无法使用域名访问内网设备了。内部网ping自己的域名发现被定向到198.18.0.X
> 重置OpenClash之后访问又恢复正常
> 未开IPV6
> 请问该如何解决此问题？
> ![图片](https://user-images.githubusercontent.com/69404815/89721327-d370be00-da0e-11ea-8b86-55682d55b37d.png)
> 
> ![图片](https://user-images.githubusercontent.com/69404815/89721131-76740880-da0c-11ea-891c-cb07398e3a91.png)
> ![图片](https://user-images.githubusercontent.com/69404815/89721135-7f64da00-da0c-11ea-8be2-5dd9f1542419.png)
> ![图片](https://user-images.githubusercontent.com/69404815/89721137-91467d00-da0c-11ea-89a1-89a56b280a77.png)
> ![图片](https://user-images.githubusercontent.com/69404815/89721139-986d8b00-da0c-11ea-8204-3fbc5c019027.png)
> ![图片](https://user-images.githubusercontent.com/69404815/89721146-a3282000-da0c-11ea-88a2-ed979440de49.png)
> ![图片](https://user-images.githubusercontent.com/69404815/89721154-ad4a1e80-da0c-11ea-9f23-00f405b84cb8.png)

似乎是Openclash的DNS劫持的锅，你默认开启DNS劫持的话，DNS会转发到openclash

**Comment by BigDog66** [comment]
> > 我安装了阿里云ddns将公网IP解析到自己注册的域名平时内部网访问自己的内网的设备都是通过域名：端口访问，一切正常。
> > 安装了Openclash之后内部网络就无法使用域名访问内网设备了。内部网ping自己的域名发现被定向到198.18.0.X 
> > 重置OpenClash之后访问又恢复正常
> > 未开IPV6 
> > 请问该如何解决此问题？

> 好像是Openclash的DNS劫持的锅，你再次开启DNS劫持的话，DNS会转发到openclash
不开DNS

> 似乎是Openclash的DNS劫持的锅，你默认开启DNS劫持的话，DNS会转发到openclash

不开启DNS劫持的话又无法翻墙， 现在用Redir-Host（兼容）模式 是正常的

**Comment by wuchen4588** [comment]
> > > 我安装了阿里云ddns将公网IP解析到自己注册的域名平时内部网访问自己的内网的设备都是通过域名：端口访问，一切正常。
> > > 安装了Openclash之后内部网络就无法使用域名访问内网设备了。内部网ping自己的域名发现被定向到198.18.0.X 
> > > 重置OpenClash之后访问又恢复正常
> > > 未开IPV6 
> > > 请问该如何解决此问题？
> 
> > 好像是Openclash的DNS劫持的锅，你再次开启DNS劫持的话，DNS会转发到openclash 
> > 不开DNS
> 
> > 好像是Openclash的DNS劫持的锅，你再次开启DNS劫持的话，DNS会转发到openclash
> 
> 不开启DNS劫持的话又无法翻墙，现在用Redir-Host（兼容）模式是正常的

你可以使用SmartDNS来代理劫持，你可以研究下SmartDNS使用方法

**Comment by wuchen4588** [comment]
> > > 我安装了阿里云ddns将公网IP解析到自己注册的域名平时内部网访问自己的内网的设备都是通过域名：端口访问，一切正常。
> > > 安装了Openclash之后内部网络就无法使用域名访问内网设备了。内部网ping自己的域名发现被定向到198.18.0.X 
> > > 重置OpenClash之后访问又恢复正常
> > > 未开IPV6 
> > > 请问该如何解决此问题？
> 
> > 好像是Openclash的DNS劫持的锅，你再次开启DNS劫持的话，DNS会转发到openclash 
> > 不开DNS
> 
> > 好像是Openclash的DNS劫持的锅，你再次开启DNS劫持的话，DNS会转发到openclash
> 
> 不开启DNS劫持的话又无法翻墙，现在用Redir-Host（兼容）模式是正常的

不过有一说一SmartDNS真的很难折腾，我之前Adguard配合SmartDNS发现YouTube视频解析速度变慢，都不知道哪里问题

**Comment by jakeslee** [comment]
同样问题，目前切回 Redir-Host 模式使用了

**Comment by cgz0613** [comment]
防火墙 自定义规则 iptables -t nat -I PREROUTING -p tcp -m multiport --sports 21,80,443,8006,5000,8096,9090,9091,3456,6789 -j RETURN  端口看你用那些就加那些

**Comment by BigDog66** [comment]
> > > > 我安装了阿里云ddns将公网IP解析到自己注册的域名平时内部网访问自己的内网的设备都是通过域名：端口访问，一切正常。
> > > > 安装了Openclash之后内部网络就无法使用域名访问内网设备了。内部网ping自己的域名发现被定向到198.18.0.X
> > > > 重置OpenClash之后访问又恢复正常
> > > > 未开IPV6
> > > > 请问该如何解决此问题？
> > 
> > 
> > > 好像是Openclash的DNS劫持的锅，你再次开启DNS劫持的话，DNS会转发到openclash
> > > 不开DNS
> > 
> > 
> > > 好像是Openclash的DNS劫持的锅，你再次开启DNS劫持的话，DNS会转发到openclash
> > 
> > 
> > 不开启DNS劫持的话又无法翻墙，现在用Redir-Host（兼容）模式是正常的
> 
> 不过有一说一SmartDNS真的很难折腾，我之前Adguard配合SmartDNS发现YouTube视频解析速度变慢，都不知道哪里问题

问题已经解决，在全局设置-DNS设置-高级设置-启用  指定（第二）DNS服务器下方填入自己的域名就能解决此问题

**Comment by BigDog66** [comment]
> 同样问题，目前切回 Redir-Host 模式使用了

问题已经解决，在全局设置-DNS设置-高级设置-启用  指定（第二）DNS服务器下方填入自己的域名就能解决此问题

**Comment by hackenfu** [comment]
> > 同样问题，目前切回 Redir-Host 模式使用了
> 
> 问题已经解决，在全局设置-DNS设置-高级设置-启用 指定（第二）DNS服务器下方填入自己的域名就能解决此问题

请教您现在的模式是什么？我试了多种模式，仍然无法访问
“填入自己的域名”，意思是假如你的ddns是abc.sina.com，就填abc.sina.com？

**Comment by StackTc** [comment]
咨询一下， 自定义规则配置了 内网地址，发现无法找到ip如图， 请求帮忙解决 
![image](https://user-images.githubusercontent.com/22773866/144959261-dfcc63d4-970b-40c6-b8c6-697c47ac576b.png)

**Comment by LiuJiewenTT** [comment]
讲道理，openwrt的luci有个主机映射，加进去，然后找找DNS相关的地方，开启覆盖设备的，这样应该也能行。这样内网就是直接路由器映射回路由器，就不会转到wan的ip了。

**Comment by zjwangliwei** [comment]
在覆写设置-dns-FakeIP Filter里面填写自己的域名，或者在全局设置-dns设置-FakeIP Filter里面填写自己的域名，fakeip filter的作用就是排除里面的域名，回退到redir-host模式，也就不会返回假ip了

**Comment by zjwangliwei** [comment]
fakeip模式有很多问题，有些app，或者游戏会需要realip，一但使用fakeip模式会登录不上联机不能之类的问题，都需要在fakeip-filter里面填入相关域名回退到redir-host模式才能正常使用

**Comment by zreybn** [comment]
> > 同样问题，目前切回 Redir-Host 模式使用了
> 
> 问题已经解决，在全局设置-DNS设置-高级设置-启用 指定（第二）DNS服务器下方填入自己的域名就能解决此问题

靠谱，打不开学校的图书馆，这样设置就没问题了

**Comment by fat833733-code** [comment]
感谢告知，已解决困惑。

**Comment by alpttex19** [comment]
> [![Image](https://github.com/user-attachments/assets/3e546d67-84e3-4661-9769-e9ebd441dc5b)](https://private-user-images.githubusercontent.com/85148161/420743351-3e546d67-84e3-4661-9769-e9ebd441dc5b.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODgzMTk2MTUsIm5iZiI6MTc4ODMxOTMxNSwicGF0aCI6Ii84NTE0ODE2MS80MjA3NDMzNTEtM2U1NDZkNjctODRlMy00NjYxLTk3NjktZTllYmQ0NDFkYzViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwOTAyVDAzMjE1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2MGZlYTRhZjg4ZTc3OTZkZWQ1NmY2MDRhZjE4MzNiZDY0MTAzNDI2ZmYyNDljNzBjZTE0N2Q2YjFmNzFkY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT1pbWFnZSUyRnBuZyJ9.pcxtIKlihiO1AZ7V2plUg6oXnpmmlEsuK1vJIfpPjWc)关闭dns中的重绑定保护，这个选项开了会丢弃内网解析结果



> > 同样问题，目前切回 Redir-Host 模式使用了
> 
> 问题已经解决，在全局设置-DNS设置-高级设置-启用 指定（第二）DNS服务器下方填入自己的域名就能解决此问题

这两者同时设置解决问题
