### ISSUE TITLE
在openwrt上开启openclash后，Plex远程连接不上了

### ISSUE THREAD

**Issue by francis5959** [vernesong/OpenClash#645]
作者好
在openwrt上开启openclash后，Plex远程连接不上了，看网络设置中内网外网ip均为x

**Comment by vernesong** [comment]
发调试日志

**Comment by yanyingjie007** [comment]
有同样的问题，我还以为是运营商的问题

**Comment by poemsiu** [comment]
别用fake ip模式 试试re模式

**Comment by iKe7vin** [comment]
一样的问题
fake模式plex就断连 
 re模式可以设置不走代理LAN 就没有这个问题
但是还是fake模式速度快啊

**Comment by francis5959** [comment]
将
app.plex.tv
plex.tv
jellyfin.org
添加到直连列表中试试，添加jellyfin可用jellyfin app了。

**Comment by nevertoday** [comment]
楼上正解，谢谢

**Comment by dahuangshushu** [comment]
> 将 app.plex.tv plex.tv jellyfin.org 添加到直连列表中试试，添加jellyfin可用jellyfin app了。

将plex域名添加到直连列表亲测有效，感谢
