### ISSUE TITLE
Fake-IP的TUN内核下能否有任何方法达到和dev内核同等的速度而不是限速在150Mbps呢？

### ISSUE THREAD

**Issue by FanyangMengDev** [vernesong/OpenClash#647]
如题，主要是为了腾讯系的语音，比如腾讯会议，TUN能正常使用所有功能，但是dev内核开启UDP也不能用语音，估计是服务器不支持。

目前TUN模式下最高下载速度明显比Fake-IP-dev增强模式慢了不少，基本限速在150Mbps左右

感觉TUN比默认的增强模式适用更广泛，重度腾讯会议使用者表示能不能让TUN模式和普通dev速度一样，或者是dev也能支持腾讯系的语音功能。

目前了解到TUN好像比较依赖硬件，已购买比较新的4205，但是要是OpenClash本身能做到这点最好了。

再次感谢V大开源OpenClash。

**Comment by FanyangMengDev** [comment]
测试了几下发现，TUN模式兼容性最好，所有应用都能运行，但是最高下载速度明显比Fake-IP增强模式满了不少。
想用网速最快的Fake-IP又无法保证峰值下载速度，太难受了

**Comment by wuchen4588** [comment]
本来Fake不是很稳定啊，老实用Redir吧

**Comment by FanyangMengDev** [comment]
> 本来Fake不是很稳定啊，老实用Redir吧

你用Redir也一样好吗。

**Comment by wuchen4588** [comment]
> > 本来Fake不是很稳定啊，老实用Redir吧
> 
> 你用Redir也一样好吗。

还可以吧，我现在对openclash的主要问题是如何SmartDNS+Adguard配合使用，我就希望能配合这个玩意免广告，但是我发现这个玩意导致我YouTube视频解析速度变慢，挺恼火，还把openclash玩蹦了

**Comment by wuchen4588** [comment]
现在重装openclash又无法识别内核，某种意义上openclash真的不稳定

**Comment by FanyangMengDev** [comment]
> > > 本来Fake不是很稳定啊，老实用Redir吧
> > 
> > 
> > 你用Redir也一样好吗。
> 
> 还可以吧，我现在对openclash的主要问题是如何SmartDNS+Adguard配合使用，我就希望能配合这个玩意免广告，但是我发现这个玩意导致我YouTube视频解析速度变慢，挺恼火，还把openclash玩蹦了



> 现在重装openclash又无法识别内核，某种意义上openclash真的不稳定

这根openclash无关，就是你自己不会配置，建议不要来我的issue下面刷你自己的问题，谢谢

**Comment by wuchen4588** [comment]
> > > > 本来Fake不是很稳定啊，老实用Redir吧
> > > 
> > > 
> > > 你用Redir也一样好吗。
> > 
> > 
> > 还可以吧，我现在对openclash的主要问题是如何SmartDNS + Adguard配合使用，我就希望能配合这个玩意免广告，但是我发现这个玩意导致我YouTube视频解析速度变慢，挺恼火，还把openclash玩蹦了
> 
> > 现在重装openclash又无法识别内核，某种意义上openclash真的歪
> 
> 这跟openclash无关，就是你自己不会配置，建议不要来我的问题下面刷你自己的问题，并且表示无关紧要的回答，谢谢

我只是吐槽下openclash真的贼不稳定罢了

**Comment by FanyangMengDev** [comment]
> > > > > 本来Fake不是很稳定啊，老实用Redir吧
> > > > 
> > > > 
> > > > 你用Redir也一样好吗。
> > > 
> > > 
> > > 还可以吧，我现在对openclash的主要问题是如何SmartDNS + Adguard配合使用，我就希望能配合这个玩意免广告，但是我发现这个玩意导致我YouTube视频解析速度变慢，挺恼火，还把openclash玩蹦了
> > 
> > 
> > > 现在重装openclash又无法识别内核，某种意义上openclash真的歪
> > 
> > 
> > 这跟openclash无关，就是你自己不会配置，建议不要来我的问题下面刷你自己的问题，并且表示无关紧要的回答，谢谢
> 
> 我只是吐槽下openclash真的贼不稳定罢了

每个人的issue不同，你遇到的问题对于我都不是问题，吐槽的话可以直接开新issue吐槽（当然这样也不建议），但是请不要在每个人的Issue下面都刷你自己的问题，我看了最近的几个issue都有你说的这些，你这样不仅得不到V大重视甚至会让人反感，如果方便请删除您在我issue下的回复，谢谢。

**Comment by vernesong** [comment]
近期考虑udp用tun，tcp还是走redir端口的方式改善路由上的udp问题

**Comment by wuchen4588** [comment]
> 近期考虑udp用tun，tcp还是走redir端口的方式改善路由上的udp问题

请问一下V大关于DNS的问题.....

**Comment by FanyangMengDev** [comment]
redir端口不是redir模式吧？我比较喜欢fake-ip模式

确实要是只有udp走tun，其他的正常走dev是最舒服的了

**Comment by wuchen4588** [comment]
> redir端口不是redir模式吧？我比较喜欢fake-ip模式
> 
> 确实要是只有udp走tun，其他的正常走dev是最舒服的了

Fake是舒服，但是的确在其他方面有问题

**Comment by wuchen4588** [comment]
> redir端口不是redir模式吧？我比较喜欢fake-ip模式
> 
> 确实要是只有udp走tun，其他的正常走dev是最舒服的了

似乎有人说Fake在下载情况有过问题

**Comment by FanyangMengDev** [comment]
@wuchen4588 请问你为什么总爱在别人的issue下面刷存在感？

**Comment by FanyangMengDev** [comment]
@wuchen4588 请不要再在我的issue下面回复任何内容，这是我的issue，你自己的问题自己去开issue等回答，谢谢！

**Comment by FanyangMengDev** [comment]
@wuchen4588 奉劝你一句话，有问题，嫌不好，放弃别用，别总在别人issue下面刷存在感

**Comment by NV3S** [comment]
> 如题，主要是为了腾讯系的语音，比如腾讯会议，TUN能正常使用所有功能，但是dev内核开启UDP也不能用语音，估计是服务器不支持。
> 
> 目前TUN模式下最高下载速度明显比Fake-IP-dev增强模式慢了不少，基本限速在150Mbps左右
> 
> 感觉TUN比默认的增强模式适用更广泛，重度腾讯会议使用者表示能不能让TUN模式和普通dev速度一样，或者是dev也能支持腾讯系的语音功能。
> 
> **目前了解到TUN好像比较依赖硬件，已购买比较新的4205**，但是要是OpenClash本身能做到这点最好了。
> 
> 再次感谢V大开源OpenClash。

d7o大佬在mbp上iperf试出过tun到3.5G，而在openwrt上我发现TUN确实是很奇怪，它跑起来似乎不是依赖cpu频率，流量上去了以后，cpu不会占满就遇到了瓶颈。我用i5-5005U套esxi+openwrt（1vc），速度极限在350Mmps左右，不是硬限制于150Mbps。所以它可能是设备代码效率的问题。

**Comment by FanyangMengDev** [comment]
@NV3S 对的没错~我后续查了一下发现TUN很依赖设备本身，我一直在用N1盒子当旁路由，本身性能不是很好所以被限制在了150Mbps了，现在只期待openclash能有mix mode，还有就是我的新4105能快点到换上了，其实4105这性能完全足够跑满300兆了，mix mode要是不出我就一直TUN模式了。。。

**Comment by NV3S** [comment]
J4105到了的话请反馈一下，i5-5005的频率是2.0，2核，J4105我看在2.5，4核，多核心这一块我觉得并不会有很大提升，提升的频率可能会有些许帮助，也许不会有很大改善。因为在我的cpu上，一条线路我用无线ap测，转发模式能够跑到ap速率的上限，近乎tun的一倍，差距很大不像是cpu频率能够解决的问题...

**Comment by FanyangMengDev** [comment]
@NV3S 好的没问题，我其实目前刚入门第三天，所以真正部署好可能得花点时间，有任何新的进度我会在本issue反馈~

**Comment by hcym** [comment]
n1单臂300非常轻松，五百以上的宽带跑满出国才可能和5020u有区别，而且clash不用v2的话根本不费力

**Comment by FanyangMengDev** [comment]
@hcym 对我知道啊，使用起来只要不用TUN是完全足够用的，能跑满，主要是想进一步玩一玩换个高端的~嘿嘿

**Comment by NV3S** [comment]
你上了tun所有流量都也走tun了，你去本地测速的流量也是走它，会打折

**Comment by FanyangMengDev** [comment]
可是没办法。。。腾讯会议用的太多了。。不用tun就打不开腾讯会议。。。

**Comment by FanyangMengDev** [comment]
V大已加入混合模式并更新内核，性能很棒，issue关闭
