### ISSUE TITLE
[bug report] DNS高级设置不启用时仍会执行fake_block

### ISSUE THREAD

**Issue by Mosney** [vernesong/OpenClash#65]
看了一下脚本，DNS高级设置启用时会添加`option direct_dns ‘dns-server’` 不启用时什么也不添加。
最终结果是即使在luci配置中关闭这个功能也会使用默认的114来处理列表中的域名，似乎这是为了兼容解锁网易云的feature？如果是的话可以考虑将这个direct_dns增加一个**彻底关闭**的模式，即：**默认模式**下兼容网易云列表内解析真实IP，**彻底关闭**模式不对任何域名做单独解析，**自定义模式**下可以自定义列表和DNS

**Comment by vernesong** [comment]
在内核未解决某些场景需要特定dns解析流程才能正常工作的情况下，只要启用fake就会默认执行这个操作，这是刻意设置的步骤。
一是降低使用难度。
二是除了网易云音乐的部分域名，其他都是必要的，否则会出现一些常用服务异常的情况。

**Comment by Mosney** [comment]
> 二是除了网易云音乐的部分域名，其他都是必要的，否则会出现一些常用服务异常的情况。  

可以说说具体有什么服务异常情况吗？我自行注释掉这部分代码之后用起来没啥问题，大概是因为我不怎么用列表内的服务？

**Comment by vernesong** [comment]
ICMP、NTP等，win10的网络连通性检测，QQ的快捷登录接口
