### ISSUE TITLE
更新到0.39.6版本Clash运行正常但所有网站无法打开

### ISSUE THREAD

**Issue by natsumehowe** [vernesong/OpenClash#650]
路由器更新到该版本后，OpenClash工作状态显示正常，但是无法访问任何网页，包括国内的网页。关闭OpenClash则正常访问国内网站。之前0.36.4版本无此问题。配置文件、节点等问题均可以排除

**Comment by OleStore** [comment]
我是拉的最新源码，早上刷的机，发现外网都无法访问

**Comment by vernesong** [comment]
发调试日志
