### ISSUE TITLE
奇怪的问题

### ISSUE THREAD

**Issue by OleStore** [vernesong/OpenClash#652]
家中设备都是WiFi 连接，包括台式机，今早拉的最新源码编译至固件，最开始所有国内外网站都打不开，一顿操作猛如虎，台式机正常了，但是YouTube图片加载不出来，但能正常播放，又一顿操作，正常了，iPad上 YouTube无法连接，咋操作都不行，关键是台式机正常，连的同一WiFi ，另外一个问题，Apple tv4播放YouTube 居然会卡，这个问题一直存在，只是平时看电视少，一直没搭理，家里来了小朋友，看个动画片老说怎么又卡了，换回ssr plus一切正常。
Openclash 模式fake ip ，拉的最新源码。主要是openclash 启动正常，就不发调试日志了，规则:神机

**Comment by harleywong** [comment]
我今天也拉的最新的源码编译，Clash能启动，但是设备不能正常上网，又换回之前的版本了。

**Comment by OleStore** [comment]
更新后，正常了
