### ISSUE TITLE
使用openclash在抽取golang所遇问题

### ISSUE THREAD

**Issue by ksong008** [vernesong/OpenClash#653]
<img width="725" alt="批注 2020-08-11 230442" src="https://user-images.githubusercontent.com/54489832/89915881-80268780-dc29-11ea-9fb4-e4254849f329.png">
编译在抽取所需goalang时候会遭遇unexpected eof问题，用ssr或者passwall没有问题。请问，这是什么问题

**Comment by vernesong** [comment]
插件编译不需要go的

**Comment by ksong008** [comment]
> 插件编译不需要go的

我描述的不准确，是在编译固件时候，碰到需要golang的插件，比如filebrowser,就会有问题
