### ISSUE TITLE
Dashboard 控制面板必须要设置一下密码才可以正常刷新

### ISSUE THREAD

**Issue by Edger** [vernesong/OpenClash#654]
RT。

斐讯 N1 刷完 openwrt，配置 OpenClash。

最新的版本 Dashboard 控制面板必须要修改并应用一下外部控制管理密钥才可以正常使用，要不日志不会打印，策略组切换节点这些设置也不会生效。Yacd 控制面板则是正常的。

**Comment by vernesong** [comment]
ctrl+f5

**Comment by Edger** [comment]
> ctrl+f5

没有用啊，我用的是 mac Chrome，control + shit + r 也没有用，在 Ubuntu 上试了也是一样。

就是改了密码之后就可以正常使用了，折腾了半天。

我觉得把这个问题说明或者置顶一下比较好。

**Comment by 00LT00** [comment]
@Edger 你是在dashboard的设置里面改的吗，还是在openclash的外部控制改的，我两个都改了还是没有更新，但是yacd是正常的

**Comment by Edger** [comment]
> @Edger 你是在dashboard的设置里面改的吗，还是在openclash的外部控制改的，我两个都改了还是没有更新，但是yacd是正常的

现在外部控制里把默认的密码改成别的，再刷新 dashboard 页面，应该会弹出让你设置密码的窗口。修改之后应该就正常了

**Comment by 00LT00** [comment]
改了以后弹窗了，但是弹窗改了直接进不去了，跟没改一样，但是设置里面也好，自己跳的也好，密码都是改过的，我现在改回默认密码也不行了 @Edger

**Comment by Edger** [comment]
> 改了以后弹窗了，但是弹窗改了直接进不去了，跟没改一样，但是设置里面也好，自己跳的也好，密码都是改过的，我现在改回默认密码也不行了 @Edger

那我不知道了，你强制刷新了吗？

解决不了只能问作者了

**Comment by 00LT00** [comment]
如果刷新是指网页f5的话，那应该是没啥办法。。。

**Comment by Edger** [comment]
> 如果刷新是指网页f5的话，那应该是没啥办法。。。

。。。。。。。。。强制刷新， Ctrl +  F5

**Comment by GengchaoYang** [comment]
> 改了以后弹窗了，但是弹窗改了直接进不去了，跟没改一样，但是设置里面也好，自己跳的也好，密码都是改过的，我现在改回默认密码也不行了 @Edger

我是把Host地址从默认的127.0.0.1改成OpenWrt的访问地址就好了
