### ISSUE TITLE
请问如何设置本地ping来测试节点延迟呢？

### ISSUE THREAD

**Issue by zazitufu** [vernesong/OpenClash#656]
config里面的这个测试延迟的地址，跟我本地ping到的延迟差异很大。所有的节点都是如此。
http://www.gstatic.com/generate_204

![image](https://user-images.githubusercontent.com/57139031/89985450-b0b00500-dcad-11ea-9a9f-45fb0c250914.png)

**Comment by adamw92** [comment]
建议去搜一下各个代理软件测ping值的原理与区别…

**Comment by OUZYcn** [comment]
Clash里边的延迟测试并非ping （icmp）
