### ISSUE TITLE
cloudflare与维基百科等部分网站无法连接

### ISSUE THREAD

**Issue by JunTsao** [vernesong/OpenClash#657]
拓扑：
OpenClash - Adguard Home - Smartdns - Internet
规则：ACL4SSR

目前发现wiki、CloudFlare CDN等匹配到了IPCIDR规则，需要在自定义规则中加入方可正常打开
但是我使用Clash For Windows时，成功匹配到了“漏网之鱼”规则

测试前提下保证两者订阅连接一致、同步更新订阅。
请问为何会出现此情况？是否被smartdns错误解析？
还请作者能指点一二

附上调试日志：

OpenClash 调试日志

生成时间: 2020-08-12 17:05:13
插件版本: v0.39.6-beta

#===================== 系统信息 =====================#
主机型号: Intel(R) Celeron(R) CPU 3865U @ 1.80GHz : 1 Core 1 Thread
固件版本: OpenWrt SNAPSHOT 2020.07.15
LuCI版本: git-20.194.56991-0870bc9-1
内核版本: 4.19.132
处理器架构: x86_64

#此项在使用Tun模式时应为ACCEPT
防火墙转发: ACCEPT

#此项有值时建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: 

#此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 127.0.0.1#7874

#===================== 依赖检查 =====================#
dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
jsonfilter: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
iptables-mod-tproxy: 已安装
kmod-tun(TUN模式): 已安装
luci-compat(Luci-19.07): 已安装

#===================== 内核检查 =====================#
运行状态: 运行中
已选择的架构: linux-amd64

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 2020.07.24.g42c533f
Tun内核文件: 存在
Tun内核运行权限: 正常

Game内核版本: v0.17.0-171-ga365283
Game内核文件: 存在
Game内核运行权限: 正常

Dev内核版本: v1.0.0-19-g8f00980
Dev内核文件: 存在
Dev内核运行权限: 正常

#===================== 插件设置 =====================#
当前配置文件: /etc/openclash/config/hitun2.yaml
运行模式: fake-ip
默认代理模式: rule
UDP流量转发: 启用
DNS劫持: 启用
自定义DNS: 启用
IPV6-DNS解析: 停用
禁用Dnsmasq缓存: 启用
自定义规则: 启用
仅允许内网: 停用
仅代理命中规则流量: 停用

#启动异常时建议关闭此项后重试
保留配置: 停用
第三方规则: 停用

#===================== 自定义规则 一 =====================#
##- DOMAIN-SUFFIX,google.com,Proxy 匹配域名后缀(交由Proxy代理服务器组)
##- DOMAIN-KEYWORD,google,Proxy 匹配域名关键字(交由Proxy代理服务器组)
##- DOMAIN,google.com,Proxy 匹配域名(交由Proxy代理服务器组)
##- DOMAIN-SUFFIX,ad.com,REJECT 匹配域名后缀(拒绝)
##- IP-CIDR,127.0.0.0/8,DIRECT 匹配数据目标IP(直连)
##- SRC-IP-CIDR,192.168.1.201/32,DIRECT 匹配数据发起IP(直连)
##- DST-PORT,80,DIRECT 匹配数据目标端口(直连)
##- SRC-PORT,7777,DIRECT 匹配数据源端口(直连)
##- DOMAIN-SUFFIX,wikipedia.org,🐟 漏网之鱼

- IP-CIDR,1.2.4.8/32,DIRECT
- IP-CIDR,114.114.114.114/32,DIRECT
- IP-CIDR,119.29.29.29/32,DIRECT
- IP-CIDR,182.254.116.116/32,DIRECT
- IP-CIDR,202.175.82.46/32,DIRECT
- IP-CIDR,101.6.6.6/32,DIRECT
- IP-CIDR,101.101.101.101/3,DIRECT
- IP-CIDR,203.198.7.66/32,DIRECT

##排序在上的规则优先生效,如添加（去除规则前的#号）：
##IP段：192.168.1.2-192.168.1.200 直连
##- SRC-IP-CIDR,192.168.1.2/31,DIRECT
##- SRC-IP-CIDR,192.168.1.4/30,DIRECT
##- SRC-IP-CIDR,192.168.1.8/29,DIRECT
##- SRC-IP-CIDR,192.168.1.16/28,DIRECT
##- SRC-IP-CIDR,192.168.1.32/27,DIRECT
##- SRC-IP-CIDR,192.168.1.64/26,DIRECT
##- SRC-IP-CIDR,192.168.1.128/26,DIRECT
##- SRC-IP-CIDR,192.168.1.192/29,DIRECT
##- SRC-IP-CIDR,192.168.1.200/32,DIRECT

##IP段：192.168.1.202-192.168.1.255 直连
##- SRC-IP-CIDR,192.168.1.202/31,DIRECT
##- SRC-IP-CIDR,192.168.1.204/30,DIRECT
##- SRC-IP-CIDR,192.168.1.208/28,DIRECT
##- SRC-IP-CIDR,192.168.1.224/27,DIRECT

##此时IP为192.168.1.1和192.168.1.201的客户端流量走代理（策略），其余客户端不走代理
##因为Fake-IP模式下，IP地址为192.168.1.1的路由器自身流量可走代理（策略），所以需要排除
##在线IP段转CIDR地址：http://ip2cidr.com
#===================== 自定义规则 二 =====================#
##- DOMAIN-SUFFIX,google.com,Proxy 匹配域名后缀(交由Proxy代理服务器组)
##- DOMAIN-KEYWORD,google,Proxy 匹配域名关键字(交由Proxy代理服务器组)
##- DOMAIN,google.com,Proxy 匹配域名(交由Proxy代理服务器组)
##- DOMAIN-SUFFIX,ad.com,REJECT 匹配域名后缀(拒绝)
##- IP-CIDR,127.0.0.0/8,DIRECT 匹配数据目标IP(直连)
##- SRC-IP-CIDR,192.168.1.201/32,DIRECT 匹配数据发起IP(直连)
##- DST-PORT,80,DIRECT 匹配数据目标端口(直连)
##- SRC-PORT,7777,DIRECT 匹配数据源端口(直连)
#===================== 配置文件 =====================#
port: 7890
socks-port: 7891
allow-lan: true
bind-address: "*"
ipv6: false
mode: rule
log-level: silent
external-controller: 0.0.0.0:9090
redir-port: 7892
secret: "123456"
external-ui: "/usr/share/openclash/dashboard"
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  listen: 127.0.0.1:7874
  fake-ip-filter:
##Custom fake-ip-filter##
  - '*.lan'
  - 'time.windows.com'
  - 'time.nist.gov'
  - 'time.apple.com'
  - 'time.asia.apple.com'
  - '*.ntp.org.cn'
  - '*.openwrt.pool.ntp.org'
  - 'time1.cloud.tencent.com'
  - 'time.ustc.edu.cn'
  - 'pool.ntp.org'
  - 'ntp.ubuntu.com'
  - 'ntp.aliyun.com'
  - 'ntp1.aliyun.com'
  - 'ntp2.aliyun.com'
  - 'ntp3.aliyun.com'
  - 'ntp4.aliyun.com'
  - 'ntp5.aliyun.com'
  - 'ntp6.aliyun.com'
  - 'ntp7.aliyun.com'
  - 'time1.aliyun.com'
  - 'time2.aliyun.com'
  - 'time3.aliyun.com'
  - 'time4.aliyun.com'
  - 'time5.aliyun.com'
  - 'time6.aliyun.com'
  - 'time7.aliyun.com'
  - '*.time.edu.cn'
  - 'time1.apple.com'
  - 'time2.apple.com'
  - 'time3.apple.com'
  - 'time4.apple.com'
  - 'time5.apple.com'
  - 'time6.apple.com'
  - 'time7.apple.com'
  - 'time1.google.com'
  - 'time2.google.com'
  - 'time3.google.com'
  - 'time4.google.com'
  - 'music.163.com'
  - '*.music.163.com'
  - '*.126.net'
  - 'musicapi.taihe.com'
  - 'music.taihe.com'
  - 'songsearch.kugou.com'
  - 'trackercdn.kugou.com'
  - '*.kuwo.cn'
  - 'api-jooxtt.sanook.com'
  - 'api.joox.com'
  - 'joox.com'
  - 'y.qq.com'
  - '*.y.qq.com'
  - 'streamoc.music.tc.qq.com'
  - 'mobileoc.music.tc.qq.com'
  - 'isure.stream.qqmusic.qq.com'
  - 'dl.stream.qqmusic.qq.com'
  - 'aqqmusic.tc.qq.com'
  - 'amobile.music.tc.qq.com'
  - '*.xiami.com'
  - '*.music.migu.cn'
  - 'music.migu.cn'
  - '*.msftconnecttest.com'
  - '*.msftncsi.com'
  - 'localhost.ptlogin2.qq.com'
  - '*.*.*.srv.nintendo.net'
  - '*.*.stun.playstation.net'
  - 'xbox.*.*.microsoft.com'
  - '*.*.xboxlive.com'
##Custom fake-ip-filter END##
##Custom DNS##
  nameserver:
  - tcp://127.0.0.1:5333

#===================== 防火墙设置 =====================#

#NAT chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    REDIRECT   tcp  --  0.0.0.0/0            8.8.4.4              redir ports 7892
2    REDIRECT   tcp  --  0.0.0.0/0            8.8.8.8              redir ports 7892
3    prerouting_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom prerouting rule chain */
4    zone_lan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
5    openclash  tcp  --  0.0.0.0/0            0.0.0.0/0           
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         
1    openclash_output  tcp  --  0.0.0.0/0            0.0.0.0/0           

#Mangle chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    openclash  udp  --  0.0.0.0/0            0.0.0.0/0           
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         
1    RRDIPT_OUTPUT  all  --  0.0.0.0/0            0.0.0.0/0           

#===================== 路由表状态 =====================#
#route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.88.253  0.0.0.0         UG    0      0        0 br-lan
192.168.88.0    0.0.0.0         255.255.255.0   U     0      0        0 br-lan
#ip route list
default via 192.168.88.253 dev br-lan proto static 
192.168.88.0/24 dev br-lan proto kernel scope link src 192.168.88.251 
#ip rule show
0:	from all lookup local
32765:	from all fwmark 0x162 lookup 354
32766:	from all lookup main
32767:	from all lookup default

#===================== 端口占用状态 =====================#
tcp        0      0 :::9090                 :::*                    LISTEN      1815/clash
tcp        0      0 :::7890                 :::*                    LISTEN      1815/clash
tcp        0      0 :::7891                 :::*                    LISTEN      1815/clash
tcp        0      0 :::7892                 :::*                    LISTEN      1815/clash
udp        0      0 127.0.0.1:7874          0.0.0.0:*                           1815/clash
udp        0      0 :::52289                :::*                                1815/clash
udp        0      0 :::59341                :::*                                1815/clash
udp        0      0 :::7891                 :::*                                1815/clash
udp        0      0 :::7892                 :::*                                1815/clash

#===================== 测试本机DNS查询 =====================#
Server:		127.0.0.1
Address:	127.0.0.1#53

Name:      www.baidu.com
Address 1: 198.18.0.69
*** Can't find www.baidu.com: No answer

#===================== resolv.conf.auto =====================#
# Interface lan
nameserver 192.168.88.251

#===================== 测试本机网络连接 =====================#
HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: private, no-cache, no-store, proxy-revalidate, no-transform
Connection: keep-alive
Content-Length: 277
Content-Type: text/html
Date: Wed, 12 Aug 2020 09:05:14 GMT
Etag: "575e1f6d-115"
Last-Modified: Mon, 13 Jun 2016 02:50:21 GMT
Pragma: no-cache
Server: bfe/1.0.8.18

#===================== 测试本机网络下载 =====================#
HTTP/1.1 200 Connection established

HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 78
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: text/plain; charset=utf-8
ETag: "2f3a02f4e4fb5831f64d24282cbac5aee98c06edf5f10619508297c30fa0572d"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
Via: 1.1 varnish (Varnish/6.0)
X-GitHub-Request-Id: 0D58:01D5:316AB:3F185:5F33A892
Accept-Ranges: bytes
Date: Wed, 12 Aug 2020 09:05:15 GMT
Via: 1.1 varnish
X-Served-By: cache-hkg17931-HKG
X-Cache: HIT, HIT
X-Cache-Hits: 1, 1
X-Timer: S1597223115.087194,VS0,VE1
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
X-Fastly-Request-ID: 2d71e0fc3d6ff06784b40df0b8ec63276c3fe3d9
Expires: Wed, 12 Aug 2020 09:10:15 GMT
Source-Age: 39

#===================== 最近运行日志 =====================#
2020-08-05 09:42:45 OpenClash Start Successful
2020-08-05 14:31:18 Config 【hitun2】 Update Successful
2020-08-05 14:32:09 OpenClash Start Successful
2020-08-05 14:52:19 Config 【hitun2】 Update Successful
2020-08-06 00:00:00 Config 【hitun2】 Update Successful
2020-08-06 00:00:00 GEOIP Database Update Error
2020-08-07 00:00:00 Config 【hitun2】 Update Successful
2020-08-07 00:00:00 GEOIP Database Update Error
2020-08-08 00:00:00 Updated Config【hitun2】 No Change, Do Nothing
2020-08-08 00:00:00 GEOIP Database Update Error
2020-08-09 00:00:00 Config 【hitun2】Update Error
2020-08-09 00:00:00 GEOIP Database Update Error
2020-08-10 00:00:00 Updated Config【hitun2】 No Change, Do Nothing
2020-08-10 00:00:00 GEOIP Database Update Error
2020-08-11 00:00:00 Updated Config【hitun2】 No Change, Do Nothing
2020-08-11 00:00:00 GEOIP Database Update Error
2020-08-12 00:00:00 Updated Config【hitun2】 No Change, Do Nothing
2020-08-12 00:00:00 GEOIP Database Update Error
2020-08-12 16:48:46 Config 【hitun2】 Update Successful
time="2020-08-12T08:49:19Z" level=info msg="Start initial compatible provider 🍎 苹果服务"
time="2020-08-12T08:49:19Z" level=info msg="Start initial compatible provider 📲 电报信息"
time="2020-08-12T08:49:19Z" level=info msg="Start initial compatible provider 🐟 漏网之鱼"
time="2020-08-12T08:49:19Z" level=info msg="Start initial compatible provider Ⓜ️ 微软服务"
time="2020-08-12T08:49:19Z" level=info msg="Start initial compatible provider 🚀 节点选择"
time="2020-08-12T08:49:19Z" level=info msg="Start initial compatible provider 🎯 全球直连"
time="2020-08-12T08:49:19Z" level=info msg="Start initial compatible provider 🌍 国外媒体"
time="2020-08-12T08:49:19Z" level=info msg="Start initial compatible provider ♻️ 自动选择"
time="2020-08-12T08:49:19Z" level=info msg="Start initial compatible provider 📢 谷歌FCM"
2020-08-12 16:49:12 OpenClash Start Successful
2020-08-12 16:50:16 OpenClash Start Successful

**Comment by RAYSphere** [comment]
首先这个dns就离谱，不知道怎么设置的。fake-ip模式下，需要代理的网站是直接在代理服务器解析的。

**Comment by vernesong** [comment]
你设置的smartdns，结果就是他给的，你去找找原因
