### ISSUE TITLE
OpenClash上传速率问题

### ISSUE THREAD

**Issue by nekomiya-hinata** [vernesong/OpenClash#660]
在使用openclash时经过openclash的流量上传速率会变得非常慢，关闭openclash以及设置黑名单绕过后恢复正常，并且上传的流量是Direct
openclash版本为 v0.39.7
clash内核版本为 v1.0.0-33-g8b7c731，今天才更新的
![测速图](https://user-images.githubusercontent.com/46987091/90156230-cb25d380-ddbe-11ea-8b81-29d6aa45ce39.jpg)
![模式](https://user-images.githubusercontent.com/46987091/90156283-d5e06880-ddbe-11ea-9b98-32415a7338d0.png)

**Comment by verehu** [comment]
怎么解决的

**Comment by wkingnet** [comment]
实验了半天，应该是ipv6搞的鬼。

路由器关闭ipv6就可以了。

如果想用ipv6，先保证不安装openclash插件时，路由器ipv6网络是通的（我关闭了路由器的ipv6 DNS查询功能，具体看[这里](https://aethersailor.github.io/Custom_OpenClash_Rules/2.OpenWrt-IPv6-%E8%AE%BE%E7%BD%AE%E6%96%B9%E6%A1%88/#3-dhcp)）。然后安装openclash插件，ipv6标签我是这么设置的：
IPv6 流量代理：打钩
IPv6 代理模式：TProxy 模式
 UDP 流量转发：不打钩
允许 IPv6 类型 DNS 解析：打钩

设置完毕重启openclash，测速基本正常。
