### ISSUE TITLE
启动失败日志提示！

### ISSUE THREAD

**Issue by silmee** [vernesong/OpenClash#661]
time="2020-08-14T08:58:24Z" level=fatal msg="Parse config error: yaml: unmarshal errors:\n  line 1632: cannot unmarshal !!str `DOMAIN-...` into map[string]interface {}\n  line 1633: cannot unmarshal !!str `DOMAIN-...` into map[string]interface {}\n  line 1634: cannot unmarshal !!str `DOMAIN-...` into map[string]interface {}\n  line 1635: cannot unmarshal !!str `MATCH,D...` into map[string]interface {}\n  line 1636: cannot unmarshal !!str `DOMAIN-...` into map[string]interface {}\n  line 1637: cannot unmarshal !!str `DOMAIN-...` into map[string]interface {}\n  line 1638: cannot unmarshal !!str `DOMAIN-...` into map[string]interface {}\n  line 1639: cannot unmarshal !!str `MATCH,D...` into map[string]interface {}\n  line 1640: cannot unmarshal !!str `DOMAIN-...` into map[string]interface {}\n  line 1641: cannot unmarshal !!str `DOMAIN-...` into map[string]interface {}\n  line 1642: cannot unmarshal !!str `DOMAIN-...` into map[string]interface {}\n  line 1643: cannot unmarshal !!str `MATCH,D...` into map[string]interface {}\n  line 1644: cannot unmarshal !!str `DOMAIN-...` into map[string]interface {}\n  line 1645: cannot unmarshal !!str `DOMAIN-...` into map[string]interface {}\n  line 1646: cannot unmarshal !!str `DOMAIN-...` into map[string]interface {}\n  line 1647: cannot unmarshal !!str `MATCH,D...` into map[string]interface {}"
2020-08-14 16:58:18 OpenClash Can Not Start, Try Use Backup Rules Start Again
time="2020-08-14T08:58:27Z" level=fatal msg="Parse config error: yaml: unmarshal errors:\n  line 1632: cannot unmarshal !!str `DOMAIN-...` into map[string]interface {}\n  line 1633: cannot unmarshal !!str `DOMAIN-...` into map[string]interface {}\n  line 1634: cannot unmarshal !!str `DOMAIN-...` into map[string]interface {}\n  line 1635: cannot unmarshal !!str `MATCH,D...` into map[string]interface {}\n  line 1636: cannot unmarshal !!str `DOMAIN-...` into map[string]interface {}\n  line 1637: cannot unmarshal !!str `DOMAIN-...` into map[string]interface {}\n  line 1638: cannot unmarshal !!str `DOMAIN-...` into map[string]interface {}\n  line 1639: cannot unmarshal !!str `MATCH,D...` into map[string]interface {}\n  line 1640: cannot unmarshal !!str `DOMAIN-...` into map[string]interface {}\n  line 1641: cannot unmarshal !!str `DOMAIN-...` into map[string]interface {}\n  line 1642: cannot unmarshal !!str `DOMAIN-...` into map[string]interface {}\n  line 1643: cannot unmarshal !!str `MATCH,D...` into map[string]interface {}\n  line 1644: cannot unmarshal !!str `DOMAIN-...` into map[string]interface {}\n  line 1645: cannot unmarshal !!str `DOMAIN-...` into map[string]interface {}\n  line 1646: cannot unmarshal !!str `DOMAIN-...` into map[string]interface {}\n  line 1647: cannot unmarshal !!str `MATCH,D...` into map[string]interface {}"
2020-08-14 16:58:18 OpenClash Can Not Start, Please Check The Error Info And Try Again

**Comment by wwgxhh** [comment]
配置文件应该有问题

**Comment by vernesong** [comment]
你用一键生成，现在你的配置文件里面有换行符，不符合要求
