### ISSUE TITLE
部分app时而断流

### ISSUE THREAD

**Issue by kevinwinsper** [vernesong/OpenClash#664]
最新版本0.39.7-beta的客户端，遇上部分app，如Facebook和instagram，会突然断流无法刷新，udp转发是关闭状态，Facebook和fbcdn.net全都走代理。确定不是节点问题。望各位大神指教。

**Comment by STIVW** [comment]
我也是app会断流。

我发现Auto-UrlTest URL-Test策略组无法及时更换已经失效的节点。

**Comment by kevinwinsper** [comment]
> 我也是app会断流。
> 
> 我发现Auto-UrlTest URL-Test策略组无法及时更换已经失效的节点。

我并没有用url test

**Comment by kevinwinsper** [comment]
现在udp转发打开后 日志报如下错误：
time="2020-08-19T00:49:07+08:00" level=info msg="[UDP] 192.168.3.231:59341 --> external-hkg4-1.xx.fbcdn.net match DomainKeyword(fbcdn) using 🚀 节点选择[🇭🇰 Hong Kong 17]"
time="2020-08-19T00:49:10+08:00" level=warning msg="[UDP] dial REJECT error: match reject rule"
time="2020-08-19T00:49:10+08:00" level=warning msg="[UDP] dial REJECT error: match reject rule"
time="2020-08-19T00:49:10+08:00" level=warning msg="[UDP] dial REJECT error: match reject rule"
