### ISSUE TITLE
v0.39.7-beta 无法手动添加服务器节点。

### ISSUE THREAD

**Issue by zdz2019** [vernesong/OpenClash#666]
之前使用的旧版没有问题，更新v0.39.7-beta后，手动添加服务器节点一直失败，导致配置文件始终缺少服务器信息。
具体症状表现为，手动添加了服务器节点信息，再点击“应用配置”按钮后，脚本执行完成后，提示配置文件完整性检查不通过，
再查看服务器节点选项，已经添加的服务器信息就不存在了。
![Snipaste_2020-08-16_20-16-03](https://user-images.githubusercontent.com/50648881/90334072-8471ec80-dffd-11ea-81ec-8fefeca47b7b.png)
![Snipaste_2020-08-16_20-16-24](https://user-images.githubusercontent.com/50648881/90334073-876cdd00-dffd-11ea-9def-926de5952b1d.png)

**Comment by vcarus** [comment]
同样遇到此问题。

**Comment by zdz2019** [comment]
测试了您最新的修改，问题已经解决了。
