### ISSUE TITLE
停在第六步: 等待主程序下载外部文件...

### ISSUE THREAD

**Issue by hackenfu** [vernesong/OpenClash#668]
0.39.7，用的Fake-IP（TUN-混合）模式，每次只要更新配置文件，就会停在第六步: 等待主程序下载外部文件...
这时候主程序显示运行中，守护程序显示未运行，实际未翻墙
只能再手动点一次启动openclash，可以顺利启动

**Comment by hackenfu** [comment]
2020-08-18 21:36:41 OpenClash Reload After Firewall Restart
2020-08-18 21:36:40 Config 【Clash】 Update Successful
time="2020-08-18T13:36:50Z" level=info msg="Start initial provider Global"
time="2020-08-18T13:36:50Z" level=info msg="Start initial provider Silver"
time="2020-08-18T13:36:50Z" level=info msg="Start initial provider Bronze"
time="2020-08-18T13:36:50Z" level=info msg="Start initial compatible provider PROXY"
time="2020-08-18T13:36:50Z" level=info msg="Start initial compatible provider Streaming"
time="2020-08-18T13:36:50Z" level=info msg="Start initial compatible provider MATCH"
time="2020-08-18T13:36:50Z" level=info msg="Start initial compatible provider StreamingSE"
time="2020-08-18T13:36:50Z" level=info msg="Start initial rule provider Streaming"
time="2020-08-18T13:36:50Z" level=info msg="Start initial rule provider StreamingSE"
time="2020-08-18T13:36:50Z" level=info msg="Start initial rule provider Global"
time="2020-08-18T13:36:50Z" level=info msg="Start initial rule provider China"
time="2020-08-18T13:36:50Z" level=info msg="Start initial rule provider ChinaIP"
time="2020-08-18T13:36:50Z" level=info msg="Start initial rule provider Unbreak"
time="2020-08-18T13:36:50Z" level=info msg="DNS server listening at: 127.0.0.1:7874"
2020-08-18 21:36:48 OpenClash Start Successful
2020-08-18 21:38:57 OpenClash Reload After Firewall Restart

**Comment by Orokapei** [comment]
你的启动后能用吗= =

**Comment by hackenfu** [comment]
那没问题的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: おバカな槿槿殿 <notifications@github.com&gt;
发送时间: 2020年8月19日 21:08
收件人: vernesong/OpenClash <OpenClash@noreply.github.com&gt;
抄送: hackenfu <hacken@vip.qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[vernesong/OpenClash] 停在第六步: 等待主程序下载外部文件... (#668)

**Comment by Orokapei** [comment]
> 那没问题的 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: おバカな槿槿殿 <notifications@github.com&gt; 发送时间: 2020年8月19日 21:08 收件人: vernesong/OpenClash <OpenClash@noreply.github.com&gt; 抄送: hackenfu <hacken@vip.qq.com&gt;, Author <author@noreply.github.com&gt; 主题: 回复：[vernesong/OpenClash] 停在第六步: 等待主程序下载外部文件... (#668)

啊，悲，按你说的再点一下启动后我的用不了。。。= =我再看看叭

**Comment by vernesong** [comment]
provider的path参数是什么？截图看一下

**Comment by hackenfu** [comment]
> provider的path参数是什么？截图看一下

  Silver: # 墙洞机场订阅链接
    type: http
    url: "https://dler.cloud/subscribe/xxx"
    interval: 3600
    path: ./Proxy/Silver.yaml # 不同机场不同命名
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

  Bronze: # 墙洞机场订阅链接
    type: http
    url: "https://dler.cloud/subscribe/xxx"
    interval: 3600
    path: ./Proxy/Bronze.yaml # 不同机场不同命名
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

  Global: # 墙洞机场订阅链接
    type: http
    url: "https://dler.cloud/subscribe/xxx"
    interval: 3600
    path: ./Proxy/Global.yaml # 不同机场不同命名
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

  Unbreak:
    type: http
    behavior: classical
    path: ./rule_provider/Unbreak.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Unbreak.yaml
    interval: 3600

  Streaming:
    type: http
    behavior: classical
    path: ./rule_provider/Streaming.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/Streaming.yaml
    interval: 3600

  StreamingSE:
    type: http
    behavior: classical
    path: ./rule_provider/StreamingSE.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/StreamingSE.yaml
    interval: 3600

  Global:
    type: http
    behavior: classical
    path: ./rule_provider/Global.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Global.yaml
    interval: 3600

  China:
    type: http
    behavior: classical
    path: ./rule_provider/China.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/China.yaml
    interval: 3600

  ChinaIP:
    type: http
    behavior: ipcidr
    path: ./rule_provider/ChinaIP.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Extra/ChinaIP.yaml
    interval: 3600

**Comment by vernesong** [comment]
./Proxy/Global.yaml不会自动改成./proxy_provider/Global.yaml吗

**Comment by hackenfu** [comment]
> ./Proxy/Global.yaml不会自动改成./proxy_provider/Global.yaml吗

不会，rule_provider倒是自动从./RuleSet之类的改过来了，三个proxy全都在proxy文件夹内

**Comment by vernesong** [comment]
上传个完整配置给我测试

**Comment by hackenfu** [comment]
> 上传个完整配置给我测试

[Clash-订阅地址隐去token.txt](https://github.com/vernesong/OpenClash/files/5099868/Clash-.token.txt)
这里好像不能传yaml，我改了后缀
订阅地址已隐去token
