### ISSUE TITLE
打开全局配置后显示一堆错误代码，请问这要怎么弄？？？

### ISSUE THREAD

**Issue by caliban511** [vernesong/OpenClash#669]
如题，如图。
请问是否要重装？我重装openclash的ipk试了没用，是否还有哪些文件要一起重装？
还是说需要删除哪些文件？还是要手动创建哪些文件？？？
![snipaste_20200819_011946](https://user-images.githubusercontent.com/13557387/90544965-82a15800-e1ba-11ea-9646-0f101ac55902.jpg)

**Comment by vernesong** [comment]
装bash

**Comment by caliban511** [comment]
> 装bash
这个装了，你的意思是重装一遍吗？好的我试试。

**Comment by caliban511** [comment]
> 装bash

重装并重启了路由器，还是图里的样子。

**Comment by OUZYcn** [comment]
固件自己编译的嘛？我自己在用[eSir SPP精简小包版](https://drive.google.com/drive/folders/1eyIxVfyzO4nyzaT1sSr6xWf50_5YJN7g?usp=sharing)，里边有openclash，我一直用着挺好。

**Comment by caliban511** [comment]
> 固件自己编译的嘛？我自己在用[eSir SPP精简小包版](https://drive.google.com/drive/folders/1eyIxVfyzO4nyzaT1sSr6xWf50_5YJN7g?usp=sharing)，里边有openclash，我一直用着挺好。

不是，我用的是原生固件，自己安装的openclash，不知道是哪里的问题。

**Comment by OUZYcn** [comment]
> > 固件自己编译的嘛？我自己在用[eSir SPP精简小包版](https://drive.google.com/drive/folders/1eyIxVfyzO4nyzaT1sSr6xWf50_5YJN7g?usp=sharing)，里边有openclash，我一直用着挺好。
> 
> 不是，我用的是原生固件，自己安装的openclash，不知道是哪里的问题。

哪肯定是依赖库不全的问题了。。。

**Comment by caliban511** [comment]
> > > 固件自己编译的嘛？我自己在用[eSir SPP精简小包版](https://drive.google.com/drive/folders/1eyIxVfyzO4nyzaT1sSr6xWf50_5YJN7g?usp=sharing)，里边有openclash，我一直用着挺好。
> > 
> > 
> > 不是，我用的是原生固件，自己安装的openclash，不知道是哪里的问题。
> 
> 哪肯定是依赖库不全的问题了。。。

可是安装的时候很顺利啊，如果有啥不对，不是应该有提示吗？

**Comment by vernesong** [comment]
更新的脚本替换一下看看

**Comment by caliban511** [comment]
> 
> 
> 更新的脚本替换一下看看

谢谢回复。我已经重置openwrt然后重装，现在没有这个问题了。
