### ISSUE TITLE
REDIR-HOST模式SSR/SS节点无法看youtube和instagram

### ISSUE THREAD

**Issue by ronlzw** [vernesong/OpenClash#671]
所有固件、内核都已经是最新版。反复尝试，REDIR-HOST模式下SS/SSR节点电脑、手机均无法看youtube（能刷出页面，但点进去不播放），电视端可以。
V2RAY节点则没问题。但我的V2RAY节点经常挂所以我还是想用回SS/SSR节点。

FAKE-IP下面没有问题，但因为FAKE-IP会经常碰到上国内网不稳定的情况所以还是想用回REDIR-HOST，望解答！

**Comment by vernesong** [comment]
DNS换几个国外doh类型的

**Comment by ronlzw** [comment]
> DNS换几个国外doh类型的

好了。之前一直没问题的。。怎么现在会这样呢
