### ISSUE TITLE
选择代理后不定时跳转回urltest

### ISSUE THREAD

**Issue by jindx0713** [vernesong/OpenClash#672]
在Dashboard面板中，选择一股节点后，再点击测下速，回到上一次选择的节点。刷新页面不会。
不定时的跳转到urltest
内核：dev分支：v1.0.0-33-g8b7c731
客户端：v0.39.7-beta

调试日志：

OpenClash 调试日志

生成时间: 2020-08-19 23:38:05
插件版本: v0.39.7-beta

#===================== 系统信息 =====================#
主机型号: QEMU Standard PC (i440FX + PIIX, 1996)
固件版本: Openwrt Koolshare mod V2.36 r14941-67f6fa0a30
LuCI版本: git-20.213.35577-5e79fc4
内核版本: 5.4.52
处理器架构: x86_64

#此项在使用Tun模式时应为ACCEPT
防火墙转发: ACCEPT

#此项有值时建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: 

#此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 127.0.0.1#7874

#===================== 依赖检查 =====================#
dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
jsonfilter: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
iptables-mod-tproxy: 已安装
kmod-tun(TUN模式): 已安装
luci-compat(Luci-19.07): 已安装

#===================== 内核检查 =====================#
运行状态: 运行中
已选择的架构: linux-amd64

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 
Tun内核文件: 不存在
Tun内核运行权限: 否

Game内核版本: 
Game内核文件: 不存在
Game内核运行权限: 否

Dev内核版本: v1.0.0-33-g8b7c731
Dev内核文件: 存在
Dev内核运行权限: 正常

#===================== 插件设置 =====================#
当前配置文件: /etc/openclash/config/clash_config_0212 (1).yaml
运行模式: fake-ip
默认代理模式: rule
UDP流量转发: 启用
DNS劫持: 启用
自定义DNS: 停用
IPV6-DNS解析: 停用
禁用Dnsmasq缓存: 启用
自定义规则: 停用
仅允许内网: 停用
仅代理命中规则流量: 停用

#启动异常时建议关闭此项后重试
保留配置: 停用
第三方规则: 停用

#===================== 配置文件 =====================#
# 2019-07-01 12:00:00
# HTTP 代理端口
port: 7890

# SOCKS5 代理端口
socks-port: 7891

# Linux 和 macOS 的 redir 代理端口 (如需使用此功能，请取消注释)
# redir-port: 7892

# 允许局域网的连接（可用来共享代理）
allow-lan: true
bind-address: "*"

# 规则模式：Rule（规则） / Global（全局代理）/ Direct（全局直连）
ipv6: false
mode: rule

# 设置日志输出级别 (默认级别：silent，即不输出任何内容，以避免因日志内容过大而导致程序内存溢出）。
# 5 个级别：silent / info / warning / error / debug。级别越高日志输出量越大，越倾向于调试，若需要请自行开启。
log-level: info

# clash 的 RESTful API
external-controller: 0.0.0.0:9090

# 您可以将静态网页资源（如 clash-dashboard）放置在一个目录中，clash 将会服务于 `${API}/ui`
# 参数应填写配置目录的相对路径或绝对路径。
# external-ui: folder

# RESTful API 的口令 (可选)
#secret: "123456"
#external-ui: "/usr/share/openclash/dashboard"

redir-port: 7892
hosts:
secret: "123456"
external-ui: "/usr/share/openclash/dashboard"
dns:  # 如订阅配置无包括此项的所有DNS设置，OpenClash将自动添加
  enable: true
  ipv6: false
  listen: 127.0.0.1:7874
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  #fake-ip-range: 198.18.0.1/16 # if you don't know what it is, don't change it # 此项将被接管
#  fake-ip-filter: # fake ip white domain list
#  - '*.lan'
#  - localhost.ptlogin2.qq.com
  fake-ip-filter:
##Custom fake-ip-filter##
  - '*.lan'
  - 'time.windows.com'
  - 'time.nist.gov'
  - 'time.apple.com'
  - 'time.asia.apple.com'
  - '*.ntp.org.cn'
  - '*.openwrt.pool.ntp.org'
  - 'time1.cloud.tencent.com'
  - 'time.ustc.edu.cn'
  - 'pool.ntp.org'
  - 'ntp.ubuntu.com'
  - 'ntp.aliyun.com'
  - 'ntp1.aliyun.com'
  - 'ntp2.aliyun.com'
  - 'ntp3.aliyun.com'
  - 'ntp4.aliyun.com'
  - 'ntp5.aliyun.com'
  - 'ntp6.aliyun.com'
  - 'ntp7.aliyun.com'
  - 'time1.aliyun.com'
  - 'time2.aliyun.com'
  - 'time3.aliyun.com'
  - 'time4.aliyun.com'
  - 'time5.aliyun.com'
  - 'time6.aliyun.com'
  - 'time7.aliyun.com'
  - '*.time.edu.cn'
  - 'time1.apple.com'
  - 'time2.apple.com'
  - 'time3.apple.com'
  - 'time4.apple.com'
  - 'time5.apple.com'
  - 'time6.apple.com'
  - 'time7.apple.com'
  - 'time1.google.com'
  - 'time2.google.com'
  - 'time3.google.com'
  - 'time4.google.com'
  - 'music.163.com'
  - '*.music.163.com'
  - '*.126.net'
  - 'musicapi.taihe.com'
  - 'music.taihe.com'
  - 'songsearch.kugou.com'
  - 'trackercdn.kugou.com'
  - '*.kuwo.cn'
  - 'api-jooxtt.sanook.com'
  - 'api.joox.com'
  - 'joox.com'
  - 'y.qq.com'
  - '*.y.qq.com'
  - 'streamoc.music.tc.qq.com'
  - 'mobileoc.music.tc.qq.com'
  - 'isure.stream.qqmusic.qq.com'
  - 'dl.stream.qqmusic.qq.com'
  - 'aqqmusic.tc.qq.com'
  - 'amobile.music.tc.qq.com'
  - '*.xiami.com'
  - '*.music.migu.cn'
  - 'music.migu.cn'
  - '*.msftconnecttest.com'
  - '*.msftncsi.com'
  - 'localhost.ptlogin2.qq.com'
  - '*.*.*.srv.nintendo.net'
  - '*.*.stun.playstation.net'
  - 'xbox.*.*.microsoft.com'
  - '*.*.xboxlive.com'
##Custom fake-ip-filter END##
  nameserver:
  - 223.5.5.5
  - 119.29.29.29
  - 114.114.114.114

#===================== 防火墙设置 =====================#

#NAT chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    REDIRECT   tcp  --  0.0.0.0/0            8.8.4.4              redir ports 7892
2    REDIRECT   tcp  --  0.0.0.0/0            8.8.8.8              redir ports 7892
3    prerouting_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom prerouting rule chain */
4    zone_lan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
5    zone_wan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
6    openclash  tcp  --  0.0.0.0/0            0.0.0.0/0           
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         
1    openclash_output  tcp  --  0.0.0.0/0            0.0.0.0/0           

#Mangle chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    mwan3_hook  all  --  0.0.0.0/0            0.0.0.0/0           
2    openclash  udp  --  0.0.0.0/0            0.0.0.0/0           
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         
1    mwan3_hook  all  --  0.0.0.0/0            0.0.0.0/0           

#===================== 路由表状态 =====================#
#route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         113.88.96.1     0.0.0.0         UG    0      0        0 pppoe-wan
113.88.96.1     0.0.0.0         255.255.255.255 UH    0      0        0 pppoe-wan
192.168.2.0     0.0.0.0         255.255.255.0   U     0      0        0 br-lan
#ip route list
default via 113.88.96.1 dev pppoe-wan proto static 
113.88.96.1 dev pppoe-wan proto kernel scope link src 113.88.98.231 
192.168.2.0/24 dev br-lan proto kernel scope link src 192.168.2.1 
#ip rule show
0:	from all lookup local
1000:	from all fwmark 0x162 lookup 354
1001:	from all iif pppoe-wan lookup 1
2001:	from all fwmark 0x100/0x3f00 lookup 1
2061:	from all fwmark 0x3d00/0x3f00 blackhole
2062:	from all fwmark 0x3e00/0x3f00 unreachable
32766:	from all lookup main
32767:	from all lookup default

#===================== 端口占用状态 =====================#
tcp        0      0 :::7890                 :::*                    LISTEN      6358/clash
tcp        0      0 :::7891                 :::*                    LISTEN      6358/clash
tcp        0      0 :::7892                 :::*                    LISTEN      6358/clash
tcp        0      0 :::9090                 :::*                    LISTEN      6358/clash
udp        0      0 127.0.0.1:7874          0.0.0.0:*                           6358/clash
udp        0      0 :::64003                :::*                                6358/clash
udp        0      0 :::18948                :::*                                6358/clash
udp        0      0 :::56858                :::*                                6358/clash
udp        0      0 :::15905                :::*                                6358/clash
udp        0      0 :::25135                :::*                                6358/clash
udp        0      0 :::26185                :::*                                6358/clash
udp        0      0 :::34403                :::*                                6358/clash
udp        0      0 :::37486                :::*                                6358/clash
udp        0      0 :::58033                :::*                                6358/clash
udp        0      0 :::29379                :::*                                6358/clash
udp        0      0 :::7891                 :::*                                6358/clash
udp        0      0 :::7892                 :::*                                6358/clash
udp        0      0 :::62183                :::*                                6358/clash
udp        0      0 :::12040                :::*                                6358/clash
udp        0      0 :::50976                :::*                                6358/clash
udp        0      0 :::33575                :::*                                6358/clash
udp        0      0 :::11080                :::*                                6358/clash
udp        0      0 :::57166                :::*                                6358/clash
udp        0      0 :::43900                :::*                                6358/clash
udp        0      0 :::24455                :::*                                6358/clash
udp        0      0 :::10235                :::*                                6358/clash
udp        0      0 :::35839                :::*                                6358/clash
udp        0      0 :::29696                :::*                                6358/clash
udp        0      0 :::17411                :::*                                6358/clash
udp        0      0 :::51239                :::*                                6358/clash
udp        0      0 :::16427                :::*                                6358/clash
udp        0      0 :::37958                :::*                                6358/clash
udp        0      0 :::15464                :::*                                6358/clash
udp        0      0 :::25808                :::*                                6358/clash
udp        0      0 :::34009                :::*                                6358/clash
udp        0      0 :::34012                :::*                                6358/clash
udp        0      0 :::31965                :::*                                6358/clash
udp        0      0 :::58604                :::*                                6358/clash
udp        0      0 :::39168                :::*                                6358/clash
udp        0      0 :::29960                :::*                                6358/clash
udp        0      0 :::48405                :::*                                6358/clash
udp        0      0 :::37179                :::*                                6358/clash
udp        0      0 :::60778                :::*                                6358/clash
udp        0      0 :::54687                :::*                                6358/clash
udp        0      0 :::56735                :::*                                6358/clash
udp        0      0 :::18851                :::*                                6358/clash
udp        0      0 :::25074                :::*                                6358/clash

#===================== 测试本机DNS查询 =====================#

Name:      www.baidu.com
Address 1: 198.18.0.231

#===================== resolv.conf.d =====================#
# Interface wan
nameserver 202.96.134.133
nameserver 202.96.128.166

#===================== 测试本机网络连接 =====================#
HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: private, no-cache, no-store, proxy-revalidate, no-transform
Connection: keep-alive
Content-Length: 277
Content-Type: text/html
Date: Wed, 19 Aug 2020 15:38:06 GMT
Etag: "575e1f72-115"
Last-Modified: Mon, 13 Jun 2016 02:50:26 GMT
Pragma: no-cache
Server: bfe/1.0.8.18

#===================== 测试本机网络下载 =====================#
HTTP/1.1 200 Connection established

HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 78
Content-Type: text/plain; charset=utf-8
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
ETag: "2f3a02f4e4fb5831f64d24282cbac5aee98c06edf5f10619508297c30fa0572d"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
Via: 1.1 varnish (Varnish/6.0)
X-GitHub-Request-Id: 6958:6073:4B9F4:72F41:5F3D1C70
Accept-Ranges: bytes
Date: Wed, 19 Aug 2020 15:38:06 GMT
Via: 1.1 varnish
X-Served-By: cache-sin18044-SIN
X-Cache: HFM, HIT
X-Cache-Hits: 0, 1
X-Timer: S1597851487.674110,VS0,VE262
Vary: Authorization,Accept-Encoding, Accept-Encoding
Access-Control-Allow-Origin: *
X-Fastly-Request-ID: 30800088e9fb5ad6c47a73060d245c50ce6831d0
Expires: Wed, 19 Aug 2020 15:43:06 GMT
Source-Age: 70

#===================== 最近运行日志 =====================#
time="2020-08-19T23:38:04+08:00" level=info msg="[TCP] 192.168.2.122:62023 --> ipv4.icanhazip.com match Match() using Final[jdx-v2-211]"
time="2020-08-19T23:38:04+08:00" level=info msg="[TCP] 192.168.2.122:62020 --> captive-cidr.origin-apple.com.akadns.net match DomainSuffix(akadns.net) using DIRECT"
time="2020-08-19T23:38:04+08:00" level=info msg="[TCP] 192.168.2.122:62022 --> captive-cidr.origin-apple.com.akadns.net match DomainSuffix(akadns.net) using DIRECT"
time="2020-08-19T23:38:04+08:00" level=info msg="[TCP] 192.168.2.122:62025 --> ipv4.icanhazip.com match Match() using Final[jdx-v2-211]"
time="2020-08-19T23:38:04+08:00" level=info msg="[TCP] 192.168.2.122:62024 --> captive-cidr.origin-apple.com.akadns.net match DomainSuffix(akadns.net) using DIRECT"
time="2020-08-19T23:38:04+08:00" level=info msg="[TCP] 192.168.2.122:62026 --> www.qiqiboy.com match Match() using Final[jdx-v2-211]"
time="2020-08-19T23:38:04+08:00" level=info msg="[TCP] 192.168.2.122:62028 --> ipv4.icanhazip.com match Match() using Final[jdx-v2-211]"
time="2020-08-19T23:38:04+08:00" level=info msg="[TCP] 192.168.2.122:62027 --> captive-cidr.origin-apple.com.akadns.net match DomainSuffix(akadns.net) using DIRECT"
time="2020-08-19T23:38:04+08:00" level=info msg="[TCP] 192.168.2.122:62030 --> ipv4.icanhazip.com match Match() using Final[jdx-v2-211]"
time="2020-08-19T23:38:05+08:00" level=info msg="[TCP] 192.168.2.122:62029 --> captive-cidr.origin-apple.com.akadns.net match DomainSuffix(akadns.net) using DIRECT"
time="2020-08-19T23:38:05+08:00" level=info msg="[TCP] 192.168.2.122:62032 --> ipv4.icanhazip.com match Match() using Final[jdx-v2-211]"
time="2020-08-19T23:38:05+08:00" level=info msg="[TCP] 192.168.2.122:62034 --> ipv4.icanhazip.com match Match() using Final[jdx-v2-211]"
time="2020-08-19T23:38:05+08:00" level=info msg="[TCP] 192.168.2.122:62033 --> captive-cidr.origin-apple.com.akadns.net match DomainSuffix(akadns.net) using DIRECT"
time="2020-08-19T23:38:05+08:00" level=info msg="[TCP] 192.168.2.122:62031 --> captive-cidr.origin-apple.com.akadns.net match DomainSuffix(akadns.net) using DIRECT"
time="2020-08-19T23:38:05+08:00" level=info msg="[TCP] 192.168.2.122:62036 --> ipv4.icanhazip.com match Match() using Final[jdx-v2-211]"
time="2020-08-19T23:38:05+08:00" level=info msg="[TCP] 192.168.2.122:62035 --> captive-cidr.origin-apple.com.akadns.net match DomainSuffix(akadns.net) using DIRECT"
time="2020-08-19T23:38:05+08:00" level=info msg="[UDP] 192.168.2.122:50571 --> stun.douyucdn.cn match DomainSuffix(cn) using DIRECT"
time="2020-08-19T23:38:05+08:00" level=info msg="[TCP] 192.168.2.122:62038 --> ipv4.icanhazip.com match Match() using Final[jdx-v2-211]"
time="2020-08-19T23:38:05+08:00" level=info msg="[TCP] 192.168.2.122:62037 --> captive-cidr.origin-apple.com.akadns.net match DomainSuffix(akadns.net) using DIRECT"
time="2020-08-19T23:38:06+08:00" level=info msg="[TCP] 192.168.2.122:62040 --> ipv4.icanhazip.com match Match() using Final[jdx-v2-211]"
time="2020-08-19T23:38:06+08:00" level=info msg="[TCP] 192.168.2.122:62042 --> ipv4.icanhazip.com match Match() using Final[jdx-v2-211]"
time="2020-08-19T23:38:06+08:00" level=info msg="[TCP] 113.88.98.231:17324 --> www.baidu.com match DomainSuffix(baidu.com) using DIRECT"
time="2020-08-19T23:38:06+08:00" level=info msg="[TCP] 192.168.2.122:62041 --> captive-cidr.origin-apple.com.akadns.net match DomainSuffix(akadns.net) using DIRECT"
time="2020-08-19T23:38:06+08:00" level=info msg="[TCP] 192.168.2.122:62044 --> ipv4.icanhazip.com match Match() using Final[jdx-v2-211]"
time="2020-08-19T23:38:06+08:00" level=info msg="[TCP] 192.168.2.1:19326 --> raw.githubusercontent.com match DomainKeyword(github) using PROXY[jdx-v2-211]"
time="2020-08-19T23:38:06+08:00" level=info msg="[TCP] 192.168.2.122:62043 --> captive-cidr.origin-apple.com.akadns.net match DomainSuffix(akadns.net) using DIRECT"
time="2020-08-19T23:38:06+08:00" level=info msg="[TCP] 192.168.2.122:62046 --> ipv4.icanhazip.com match Match() using Final[jdx-v2-211]"
time="2020-08-19T23:38:06+08:00" level=info msg="[TCP] 192.168.2.122:62045 --> captive-cidr.origin-apple.com.akadns.net match DomainSuffix(akadns.net) using DIRECT"
time="2020-08-19T23:38:06+08:00" level=info msg="[TCP] 192.168.2.122:62048 --> ipv4.icanhazip.com match Match() using Final[jdx-v2-211]"
time="2020-08-19T23:38:06+08:00" level=info msg="[TCP] 192.168.2.122:62047 --> captive-cidr.origin-apple.com.akadns.net match DomainSuffix(akadns.net) using DIRECT"

**Comment by vernesong** [comment]
浏览器f12控制台network标签，看下切换节点有没有错误

**Comment by jindx0713** [comment]
![image](https://user-images.githubusercontent.com/30382973/90752547-1d5c7c80-e30a-11ea-83c6-eef9a2ce3d2d.png)
