### ISSUE TITLE
V大，今天更新版本之后内核显示位置，无法更新，GEOIP无法更新，配置文件无法订阅。。

### ISSUE THREAD

**Issue by laobibibibibibi** [vernesong/OpenClash#674]
V大，小白一个，今天更新了版本，0.39.7，更新完毕之后，内核最新版本全部显示未知，GEOIP更新失败，配置文件也无法订阅。望指导一下。。
![微信图片_20200820002704](https://user-images.githubusercontent.com/69908933/90663561-6960e000-e27c-11ea-9d31-a67fb2c545f9.png)
![微信截图_20200820002722](https://user-images.githubusercontent.com/69908933/90663575-6d8cfd80-e27c-11ea-9b0c-f1f4f9e899e7.png)
![微信截图_20200820002738](https://user-images.githubusercontent.com/69908933/90663599-7251b180-e27c-11ea-970e-35e382f9a813.png)

**Comment by laobibibibibibi** [comment]
这是调式日志。
OpenClash 调试日志

生成时间: 2020-08-20 00:31:39
插件版本: v0.39.7-beta

#===================== 系统信息 =====================#
主机型号: Phicomm N1
固件版本: 
LuCI版本: git-20.231.74128-b2fa790
内核版本: 5.4.13-amlogic-flippy-22+
处理器架构: aarch64_generic

#此项在使用Tun模式时应为ACCEPT
防火墙转发: ACCEPT

#此项有值时建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: 

#此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 127.0.0.1#7874

#===================== 依赖检查 =====================#
dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
jsonfilter: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
iptables-mod-tproxy: 已安装
kmod-tun(TUN模式): 已安装
luci-compat(Luci-19.07): 未安装

#===================== 内核检查 =====================#
运行状态: 运行中
已选择的架构: linux-armv8

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 2020.08.13.g827ef84
Tun内核文件: 存在
Tun内核运行权限: 正常

Game内核版本: v0.17.0-175-g7f77c72
Game内核文件: 存在
Game内核运行权限: 正常

Dev内核版本: v0.20.02
Dev内核文件: 存在
Dev内核运行权限: 正常

#===================== 插件设置 =====================#
当前配置文件: /etc/openclash/config/qiyicesu.yaml
运行模式: fake-ip
默认代理模式: rule
UDP流量转发: 停用
DNS劫持: 启用
自定义DNS: 启用
IPV6-DNS解析: 停用
禁用Dnsmasq缓存: 启用
自定义规则: 停用
仅允许内网: 停用
仅代理命中规则流量: 停用

#启动异常时建议关闭此项后重试
保留配置: 停用
第三方规则: 停用

#===================== 配置文件 =====================#
﻿port: 7890
socks-port: 7891
allow-lan: true
bind-address: "*"
ipv6: false
mode: rule
log-level: silent
external-controller: 0.0.0.0:9090
redir-port: 7892
port: 7890
secret: "admin"
external-ui: "/usr/share/openclash/dashboard"
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  listen: 127.0.0.1:7874
  fake-ip-filter:
##Custom fake-ip-filter##
  - '*.lan'
  - 'time.windows.com'
  - 'time.nist.gov'
  - 'time.apple.com'
  - 'time.asia.apple.com'
  - '*.ntp.org.cn'
  - '*.openwrt.pool.ntp.org'
  - 'time1.cloud.tencent.com'
  - 'time.ustc.edu.cn'
  - 'pool.ntp.org'
  - 'ntp.ubuntu.com'
  - 'ntp.aliyun.com'
  - 'ntp1.aliyun.com'
  - 'ntp2.aliyun.com'
  - 'ntp3.aliyun.com'
  - 'ntp4.aliyun.com'
  - 'ntp5.aliyun.com'
  - 'ntp6.aliyun.com'
  - 'ntp7.aliyun.com'
  - 'time1.aliyun.com'
  - 'time2.aliyun.com'
  - 'time3.aliyun.com'
  - 'time4.aliyun.com'
  - 'time5.aliyun.com'
  - 'time6.aliyun.com'
  - 'time7.aliyun.com'
  - '*.time.edu.cn'
  - 'time1.apple.com'
  - 'time2.apple.com'
  - 'time3.apple.com'
  - 'time4.apple.com'
  - 'time5.apple.com'
  - 'time6.apple.com'
  - 'time7.apple.com'
  - 'time1.google.com'
  - 'time2.google.com'
  - 'time3.google.com'
  - 'time4.google.com'
  - 'music.163.com'
  - '*.music.163.com'
  - '*.126.net'
  - 'musicapi.taihe.com'
  - 'music.taihe.com'
  - 'songsearch.kugou.com'
  - 'trackercdn.kugou.com'
  - '*.kuwo.cn'
  - 'api-jooxtt.sanook.com'
  - 'api.joox.com'
  - 'joox.com'
  - 'y.qq.com'
  - '*.y.qq.com'
  - 'streamoc.music.tc.qq.com'
  - 'mobileoc.music.tc.qq.com'
  - 'isure.stream.qqmusic.qq.com'
  - 'dl.stream.qqmusic.qq.com'
  - 'aqqmusic.tc.qq.com'
  - 'amobile.music.tc.qq.com'
  - '*.xiami.com'
  - '*.music.migu.cn'
  - 'music.migu.cn'
  - '*.msftconnecttest.com'
  - '*.msftncsi.com'
  - 'localhost.ptlogin2.qq.com'
  - '*.*.*.srv.nintendo.net'
  - '*.*.stun.playstation.net'
  - 'xbox.*.*.microsoft.com'
  - '*.*.xboxlive.com'
##Custom fake-ip-filter END##
##Custom DNS##
  nameserver:
  - 127.0.0.1:7053
  - tcp://127.0.0.1:7888
  - tls://127.0.0.1:7888
  - https://127.0.0.1:7888

#===================== 防火墙设置 =====================#

#NAT chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    REDIRECT   tcp  --  0.0.0.0/0            8.8.4.4              redir ports 7892
2    REDIRECT   tcp  --  0.0.0.0/0            8.8.8.8              redir ports 7892
3    REDIRECT   udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:53 redir ports 53
4    REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:53 redir ports 53
5    prerouting_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom prerouting rule chain */
6    zone_lan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
7    zone_vpn_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
8    openclash  tcp  --  0.0.0.0/0            0.0.0.0/0           
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         
1    openclash_output  tcp  --  0.0.0.0/0            0.0.0.0/0           

#Mangle chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         
1    RRDIPT_OUTPUT  all  --  0.0.0.0/0            0.0.0.0/0           

#===================== 路由表状态 =====================#
#route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.2.1     0.0.0.0         UG    0      0        0 br-lan
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
192.168.2.0     0.0.0.0         255.255.255.0   U     0      0        0 br-lan
#ip route list
default via 192.168.2.1 dev br-lan proto static 
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 
192.168.2.0/24 dev br-lan proto kernel scope link src 192.168.2.3 
#ip rule show
0:	from all lookup local 
220:	from all lookup 220 
32766:	from all lookup main 
32767:	from all lookup default 

#===================== 端口占用状态 =====================#
tcp        0      0 :::7890                 :::*                    LISTEN      9606/clash
tcp        0      0 :::7891                 :::*                    LISTEN      9606/clash
tcp        0      0 :::7892                 :::*                    LISTEN      9606/clash
tcp        0      0 :::9090                 :::*                    LISTEN      9606/clash
udp        0      0 127.0.0.1:7874          0.0.0.0:*                           9606/clash
udp        0      0 :::7891                 :::*                                9606/clash
udp        0      0 :::7892                 :::*                                9606/clash

#===================== 测试本机DNS查询 =====================#
Server:		127.0.0.1
Address:	127.0.0.1#53

Name:      www.baidu.com
Address 1: 198.18.0.29
*** Can't find www.baidu.com: No answer

#===================== resolv.conf.auto =====================#
# Interface lan
nameserver 192.168.2.3

#===================== 测试本机网络连接 =====================#

#===================== 测试本机网络下载 =====================#

#===================== 最近运行日志 =====================#
2020-08-20 00:14:19 GEOIP Database Update Error
2020-08-20 00:14:26 Config 【qiyi1】Update Error
time="2020-08-20T00:15:03+08:00" level=info msg="Start initial compatible provider 🔯 故障转移"
time="2020-08-20T00:15:03+08:00" level=info msg="Start initial compatible provider ♻️ 自动选择"
time="2020-08-20T00:15:03+08:00" level=info msg="Start initial compatible provider 🚀 节点选择"
time="2020-08-20T00:15:03+08:00" level=info msg="Start initial compatible provider 🎯 全球直连"
time="2020-08-20T00:15:03+08:00" level=info msg="Start initial compatible provider 🐟 漏网之鱼"
time="2020-08-20T00:15:03+08:00" level=info msg="Start initial compatible provider 🛑 全球拦截"
time="2020-08-20T00:15:03+08:00" level=info msg="Start initial compatible provider 🔮 负载均衡"
2020-08-20 00:14:57 OpenClash Start Successful
2020-08-20 00:15:14 OpenClash Start Successful
2020-08-20 00:27:10 GEOIP Database Update Error
2020-08-20 00:27:30 Config 【qiyi1】Update Error

**Comment by vernesong** [comment]
下载是用curl，你可以直接ssh下curl 地址测试

**Comment by laobibibibibibi** [comment]
> 下载是用curl，你可以直接ssh下curl 地址测试

V大昨天看着luci-compat(Luci-19.07)没安装，装了一个。直接把系统玩炸了，图形界面全丢了，哈哈哈，半夜起来重装的系统，现在好了。
我有个别的问题想问问，我用fake-ip模式，一开启UDP转发系统无法自动对时，而且两个电视盒子也一样，无法自动获取时间，都是出厂时间，把UDP转发关了就好，这是什么原因呢？

**Comment by vernesong** [comment]
DNS高级设置黑名单把对时的地址加进去

**Comment by laobibibibibibi** [comment]
好的v大，我回去试试，安卓电视跟盒子的对时地址有办法获取么？

**Comment by vernesong** [comment]
进控制面板看连接情况不就知道了

**Comment by vernesong** [comment]
搞完回复下地址我加到默认里面去

**Comment by laobibibibibibi** [comment]
> 搞完回复下地址我加到默认里面去

好的，V大，我晚上回去研究研究
