### ISSUE TITLE
升级V0.39.2-BETA后无法打开全局设置，请大佬帮助！！

### ISSUE THREAD

**Issue by keke1975** [vernesong/OpenClash#675]
/usr/lib/lua/luci/dispatcher.lua:469: Failed to execute cbi dispatcher target for entry '/admin/services/openclash/settings'.
The called action terminated with an exception:
/usr/lib/lua/luci/model/cbi/openclash/settings.lua:272: attempt to index global 'file' (a nil value)
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:469: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:121: in function </usr/lib/lua/luci/dispatcher.lua:120>

我的软路由里装了这个libreadline8.0-1，还是不行。7.0也装了。

**Comment by vernesong** [comment]
替换我晚上更新的脚本文件

**Comment by caliban511** [comment]
我也遇到过，后来重置路由器，又重装openclash才好。。。

**Comment by keke1975** [comment]
晚上更新的脚本文件在哪里可以下载？？

**Comment by keke1975** [comment]
> 替换我晚上更新的脚本文件

晚上更新的脚本文件在哪里可以下载？？我英文不好，不好意思，能给个链接吗？谢谢。
