### ISSUE TITLE
启用openclash后能连接youtube，但打不开google，请教一下大佬这是怎么回事？

### ISSUE THREAD

**Issue by caliban511** [vernesong/OpenClash#677]
最新版openwrt19.07.3，最新版openclash v0.39.7-beta
没有用第三方规则，自己又手动添加了google的规则，但还是无法打开google.com
请问是我哪里没有设置好吗？
我不需要流量分流功能，不需要第三方规则，只想正常使用联网翻墙功能。

下面是调试日志：

OpenClash 调试日志

生成时间: 2020-08-20 21:30:40
插件版本: v0.39.7-beta

#===================== 系统信息 =====================#
主机型号: VMware, Inc. VMware Virtual Platform
固件版本: OpenWrt 19.07.3 r11063-85e04e9f46
LuCI版本: git-20.136.49537-fb2f363-1
内核版本: 4.14.180
处理器架构: x86_64

#此项在使用Tun模式时应为ACCEPT
防火墙转发: ACCEPT

#此项有值时建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: 

#此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 127.0.0.1#7874

#===================== 依赖检查 =====================#
dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
jsonfilter: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
iptables-mod-tproxy: 已安装
kmod-tun(TUN模式): 未安装
luci-compat(Luci-19.07): 已安装

#===================== 内核检查 =====================#
运行状态: 运行中
已选择的架构: linux-amd64

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 2020.08.13.g827ef84
Tun内核文件: 存在
Tun内核运行权限: 正常

Game内核版本: v0.17.0-175-g7f77c72
Game内核文件: 存在
Game内核运行权限: 正常

Dev内核版本: v1.0.0-33-g8b7c731
Dev内核文件: 存在
Dev内核运行权限: 正常

#===================== 插件设置 =====================#
当前配置文件: /etc/openclash/config/cccat.yaml
运行模式: redir-host
默认代理模式: rule
UDP流量转发: 启用
DNS劫持: 启用
自定义DNS: 启用
IPV6-DNS解析: 停用
禁用Dnsmasq缓存: 启用
自定义规则: 启用
仅允许内网: 启用
仅代理命中规则流量: 启用

#启动异常时建议关闭此项后重试
保留配置: 停用
第三方规则: 停用

#===================== 自定义规则 一 =====================#
##- DOMAIN-SUFFIX,google.com,Proxy 匹配域名后缀(交由Proxy代理服务器组)
##- DOMAIN-KEYWORD,google,Proxy 匹配域名关键字(交由Proxy代理服务器组)
##- DOMAIN,google.com,Proxy 匹配域名(交由Proxy代理服务器组)
##- DOMAIN-SUFFIX,ad.com,REJECT 匹配域名后缀(拒绝)
##- IP-CIDR,127.0.0.0/8,DIRECT 匹配数据目标IP(直连)
##- SRC-IP-CIDR,192.168.1.201/32,DIRECT 匹配数据发起IP(直连)
##- DST-PORT,80,DIRECT 匹配数据目标端口(直连)
##- SRC-PORT,7777,DIRECT 匹配数据源端口(直连)

- DOMAIN,google.com,PROXY
- DOMAIN-SUFFIX,google.com,PROXY
- DOMAIN-SUFFIX,youtube.com,PROXY

##排序在上的规则优先生效,如添加（去除规则前的#号）：
##IP段：192.168.1.2-192.168.1.200 直连
##- SRC-IP-CIDR,192.168.1.2/31,DIRECT
##- SRC-IP-CIDR,192.168.1.4/30,DIRECT
##- SRC-IP-CIDR,192.168.1.8/29,DIRECT
##- SRC-IP-CIDR,192.168.1.16/28,DIRECT
##- SRC-IP-CIDR,192.168.1.32/27,DIRECT
##- SRC-IP-CIDR,192.168.1.64/26,DIRECT
##- SRC-IP-CIDR,192.168.1.128/26,DIRECT
##- SRC-IP-CIDR,192.168.1.192/29,DIRECT
##- SRC-IP-CIDR,192.168.1.200/32,DIRECT

##IP段：192.168.1.202-192.168.1.255 直连
##- SRC-IP-CIDR,192.168.1.202/31,DIRECT
##- SRC-IP-CIDR,192.168.1.204/30,DIRECT
##- SRC-IP-CIDR,192.168.1.208/28,DIRECT
##- SRC-IP-CIDR,192.168.1.224/27,DIRECT

##此时IP为192.168.1.1和192.168.1.201的客户端流量走代理（策略），其余客户端不走代理
##因为Fake-IP模式下，IP地址为192.168.1.1的路由器自身流量可走代理（策略），所以需要排除
##在线IP段转CIDR地址：http://ip2cidr.com
#===================== 自定义规则 二 =====================#
##- DOMAIN-SUFFIX,google.com,Proxy 匹配域名后缀(交由Proxy代理服务器组)
##- DOMAIN-KEYWORD,google,Proxy 匹配域名关键字(交由Proxy代理服务器组)
##- DOMAIN,google.com,Proxy 匹配域名(交由Proxy代理服务器组)
##- DOMAIN-SUFFIX,ad.com,REJECT 匹配域名后缀(拒绝)
##- IP-CIDR,127.0.0.0/8,DIRECT 匹配数据目标IP(直连)
##- SRC-IP-CIDR,192.168.1.201/32,DIRECT 匹配数据发起IP(直连)
##- DST-PORT,80,DIRECT 匹配数据目标端口(直连)
##- SRC-PORT,7777,DIRECT 匹配数据源端口(直连)

#===================== 配置文件 =====================#
port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: true
bind-address: "10.10.10.1"
ipv6: false
mode: rule
log-level: warning
external-controller: 10.10.10.1:9090
secret: "123456"
external-ui: "/usr/share/openclash/dashboard"
hosts:
##Custom HOSTS##
#  experimental hosts, support wildcard (e.g. *.clash.dev Even *.foo.*.example.com)
#  static domain has a higher priority than wildcard domain (foo.example.com > *.example.com)
#  NOTE: hosts don't work with `fake-ip`

#  '*.clash.dev': 127.0.0.1
#  'alpha.clash.dev': '::1'
##Custom HOSTS END##
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 127.0.0.1:7874
##Custom DNS##
  nameserver:
  - 114.114.114.114
  - 119.29.29.29
  - 208.67.222.222
  fallback:
  - tls://8.8.8.8:853
  - https://1.1.1.1/dns-query
  - tls://1.1.1.1:853
  - https://doh.rixcloud.dev/dns-query
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4

#===================== 防火墙设置 =====================#

#NAT chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    REDIRECT   tcp  --  0.0.0.0/0            8.8.4.4              redir ports 7892
2    REDIRECT   tcp  --  0.0.0.0/0            8.8.8.8              redir ports 7892
3    REDIRECT   tcp  --  0.0.0.0/0            8.8.4.4              redir ports 7892
4    REDIRECT   tcp  --  0.0.0.0/0            8.8.8.8              redir ports 7892
5    prerouting_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom prerouting rule chain */
6    zone_lan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
7    zone_wan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
8    zone_wan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
9    openclash  tcp  --  0.0.0.0/0            0.0.0.0/0           
10   openclash  tcp  --  0.0.0.0/0            0.0.0.0/0           
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         

#Mangle chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    openclash  udp  --  0.0.0.0/0            0.0.0.0/0           
2    openclash  udp  --  0.0.0.0/0            0.0.0.0/0           
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         

#===================== 路由表状态 =====================#
#route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         124.115.92.1    0.0.0.0         UG    0      0        0 pppoe-wan
10.10.10.0      0.0.0.0         255.255.255.0   U     0      0        0 br-lan
124.115.92.1    0.0.0.0         255.255.255.255 UH    0      0        0 pppoe-wan
#ip route list
default via 124.115.92.1 dev pppoe-wan proto static 
10.10.10.0/24 dev br-lan proto kernel scope link src 10.10.10.1 
124.115.92.1 dev pppoe-wan proto kernel scope link src 124.115.93.192 
#ip rule show
0:	from all lookup local 
32764:	from all fwmark 0x162 lookup 354 
32765:	from all fwmark 0x162 lookup 354 
32766:	from all lookup main 
32767:	from all lookup default 

#===================== 端口占用状态 =====================#
tcp        0      0 10.10.10.1:9090         0.0.0.0:*               LISTEN      23829/clash
tcp        0      0 10.10.10.1:7890         0.0.0.0:*               LISTEN      23829/clash
tcp        0      0 10.10.10.1:7891         0.0.0.0:*               LISTEN      23829/clash
tcp        0      0 :::7892                 :::*                    LISTEN      23829/clash
udp        0      0 127.0.0.1:7874          0.0.0.0:*                           23829/clash
udp        0      0 10.10.10.1:7891         0.0.0.0:*                           23829/clash
udp        0      0 :::40960                :::*                                23829/clash
udp        0      0 :::35848                :::*                                23829/clash
udp        0      0 :::52569                :::*                                23829/clash
udp        0      0 :::49762                :::*                                23829/clash
udp        0      0 :::7892                 :::*                                23829/clash

#===================== 测试本机DNS查询 =====================#
Server:		127.0.0.1
Address:	127.0.0.1#53

Name:      www.baidu.com
www.baidu.com	canonical name = www.a.shifen.com
Name:      www.a.shifen.com
Address 1: 14.215.177.39
Address 2: 14.215.177.38
*** Can't find www.baidu.com: No answer

#===================== resolv.conf.auto =====================#
# Interface wan
nameserver 61.134.1.5
nameserver 218.30.19.50

#===================== 测试本机网络连接 =====================#
HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: private, no-cache, no-store, proxy-revalidate, no-transform
Connection: keep-alive
Content-Length: 277
Content-Type: text/html
Date: Thu, 20 Aug 2020 13:30:41 GMT
Etag: "575e1f72-115"
Last-Modified: Mon, 13 Jun 2016 02:50:26 GMT
Pragma: no-cache
Server: bfe/1.0.8.18

#===================== 测试本机网络下载 =====================#
HTTP/1.1 200 Connection established

HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 78
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: text/plain; charset=utf-8
ETag: "2f3a02f4e4fb5831f64d24282cbac5aee98c06edf5f10619508297c30fa0572d"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
Via: 1.1 varnish (Varnish/6.0)
X-GitHub-Request-Id: 8F34:31C0:1D95B2:22DE83:5F3E7A2A
Accept-Ranges: bytes
Date: Thu, 20 Aug 2020 13:30:42 GMT
Via: 1.1 varnish
X-Served-By: cache-lax8642-LAX
X-Cache: HIT, HIT
X-Cache-Hits: 3, 1
X-Timer: S1597930243.923062,VS0,VE1
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
X-Fastly-Request-ID: adb049639878348b839d33451e671a652419a80d
Expires: Thu, 20 Aug 2020 13:35:42 GMT
Source-Age: 216

**Comment by caliban511** [comment]
好吧，现在youtube也打不开了。。。
试了下，开全局也打不开。。。
但使用windows客户端可以正常访问外网，可以说明节点是好的。。。

**Comment by zxsn** [comment]
目前也遇到同样的问题😂

**Comment by cikichen** [comment]
+1，打开谷歌安全dns选一个自定义的就可以打开，但是国内网站慢

**Comment by yemao221** [comment]
2024年最稳定梯子VPN，科学上网2年亲测稳定，56元畅享一年！   
地址：https://www.xxxlsop.com/#/register?code=sf9UTRC0    


🔥全年2300GB高速流量  
针对亚洲优化的IEPL中转方案  
palm world 团队的热门产品  

🌍 奈飞、迪士尼等流媒体解锁 畅享国际热门流媒体  
💡 ChatGPT解锁 - 无障碍访问ChatGPT  
🌐 全球10个国家接入 - 全球多点接入  
🛡️ 99.99% SLA 保证 - 高可靠性服务等级协议  
⚡ 1000Mbps 带宽保证 - 超高速带宽。  
💻 20台客户端同时登录 - 轻量用户的选择。    
![QQ20240824-134644](https://github.com/user-attachments/assets/6edfdb33-c6bc-492a-8f17-c8d4348a27a2)(https://www.xxxlsop.com/#/register?code=sf9UTRC0)
