### ISSUE TITLE
奇怪了，N1 docker 旁路由 无connection

### ISSUE THREAD

**Issue by abc000123** [vernesong/OpenClash#680]
OpenClash 调试日志

生成时间: 2020-08-22 13:22:00
插件版本: v0.39.7-beta

#===================== 系统信息 =====================#
主机型号: Amlogic
固件版本: OpenWrt SNAPSHOT r2848-f9e821f97
LuCI版本: git-20.191.36863-eee6bae-1
内核版本: 3.14.29
处理器架构: aarch64_generic

#此项在使用Tun模式时应为ACCEPT
防火墙转发: ACCEPT

#此项有值时建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: 

#此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 127.0.0.1#7874

#===================== 依赖检查 =====================#
dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
jsonfilter: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
iptables-mod-tproxy: 已安装
kmod-tun(TUN模式): 已安装
luci-compat(Luci-19.07): 已安装

#===================== 内核检查 =====================#
运行状态: 运行中
已选择的架构: linux-armv8

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 2020.08.13.g827ef84
Tun内核文件: 存在
Tun内核运行权限: 正常

Game内核版本: v0.17.0-175-g7f77c72
Game内核文件: 存在
Game内核运行权限: 正常

Dev内核版本: v1.0.0-33-g8b7c731
Dev内核文件: 存在
Dev内核运行权限: 正常

#===================== 插件设置 =====================#
当前配置文件: /etc/openclash/config/config.yaml
运行模式: fake-ip
默认代理模式: rule
UDP流量转发: 停用
DNS劫持: 启用
自定义DNS: 启用
IPV6-DNS解析: 停用
禁用Dnsmasq缓存: 停用
自定义规则: 启用
仅允许内网: 停用
仅代理命中规则流量: 停用

#启动异常时建议关闭此项后重试
保留配置: 停用
第三方规则: 停用

#===================== 自定义规则 一 =====================#
##- DOMAIN-SUFFIX,google.com,Proxy 匹配域名后缀(交由Proxy代理服务器组)
##- DOMAIN-KEYWORD,google,Proxy 匹配域名关键字(交由Proxy代理服务器组)
##- DOMAIN,google.com,Proxy 匹配域名(交由Proxy代理服务器组)
##- DOMAIN-SUFFIX,ad.com,REJECT 匹配域名后缀(拒绝)
##- IP-CIDR,127.0.0.0/8,DIRECT 匹配数据目标IP(直连)
##- SRC-IP-CIDR,192.168.1.201/32,DIRECT 匹配数据发起IP(直连)
##- DST-PORT,80,DIRECT 匹配数据目标端口(直连)
##- SRC-PORT,7777,DIRECT 匹配数据源端口(直连)

##排序在上的规则优先生效,如添加（去除规则前的#号）：
##IP段：192.168.1.2-192.168.1.200 直连
##- SRC-IP-CIDR,192.168.1.2/31,DIRECT
##- SRC-IP-CIDR,192.168.1.4/30,DIRECT
##- SRC-IP-CIDR,192.168.1.8/29,DIRECT
##- SRC-IP-CIDR,192.168.1.16/28,DIRECT
##- SRC-IP-CIDR,192.168.1.32/27,DIRECT
##- SRC-IP-CIDR,192.168.1.64/26,DIRECT
##- SRC-IP-CIDR,192.168.1.128/26,DIRECT
##- SRC-IP-CIDR,192.168.1.192/29,DIRECT
##- SRC-IP-CIDR,192.168.1.200/32,DIRECT

##IP段：192.168.1.202-192.168.1.255 直连
##- SRC-IP-CIDR,192.168.1.202/31,DIRECT
##- SRC-IP-CIDR,192.168.1.204/30,DIRECT
##- SRC-IP-CIDR,192.168.1.208/28,DIRECT
##- SRC-IP-CIDR,192.168.1.224/27,DIRECT

##此时IP为192.168.1.1和192.168.1.201的客户端流量走代理（策略），其余客户端不走代理
##因为Fake-IP模式下，IP地址为192.168.1.1的路由器自身流量可走代理（策略），所以需要排除
##在线IP段转CIDR地址：http://ip2cidr.com
#===================== 自定义规则 二 =====================#
##- DOMAIN-SUFFIX,google.com,Proxy 匹配域名后缀(交由Proxy代理服务器组)
##- DOMAIN-KEYWORD,google,Proxy 匹配域名关键字(交由Proxy代理服务器组)
##- DOMAIN,google.com,Proxy 匹配域名(交由Proxy代理服务器组)
##- DOMAIN-SUFFIX,ad.com,REJECT 匹配域名后缀(拒绝)
##- IP-CIDR,127.0.0.0/8,DIRECT 匹配数据目标IP(直连)
##- SRC-IP-CIDR,192.168.1.201/32,DIRECT 匹配数据发起IP(直连)
##- DST-PORT,80,DIRECT 匹配数据目标端口(直连)
##- SRC-PORT,7777,DIRECT 匹配数据源端口(直连)

- DOMAIN,osagadir02.ddns.net,📲 电报信息
- DOMAIN,humayun.ddns.net,📲 电报信息
- IP-CIDR,85.50.216.9/32,📲 电报信息
- IP-CIDR,62.140.252.114/32,📲 电报信息
- IP-CIDR,80.111.250.109/32,📲 电报信息
- IP-CIDR,46.39.253.12/32,📲 电报信息
- IP-CIDR,217.112.134.105/32,📲 电报信息
- IP-CIDR,178.48.238.135/32,📲 电报信息
- IP-CIDR,130.180.93.142/32,📲 电报信息
- IP-CIDR,86.45.213.35/32,📲 电报信息
- IP-CIDR,81.196.41.10/32,📲 电报信息
- IP-CIDR,88.118.152.106/32,📲 电报信息
- IP-CIDR,31.178.28.130/32,📲 电报信息
- IP-CIDR,151.237.25.124/32,📲 电报信息
- IP-CIDR,78.98.116.136/32,📲 电报信息
- IP-CIDR,79.245.168.2/32,📲 电报信息
- IP-CIDR,5.66.189.181/32,📲 电报信息
- IP-CIDR,90.163.33.4/32,📲 电报信息
- IP-CIDR,84.238.212.210/32,📲 电报信息
- IP-CIDR,109.97.108.52/32,📲 电报信息
- IP-CIDR,213.179.109.56/32,📲 电报信息
- IP-CIDR,176.114.248.227/32,📲 电报信息
- IP-CIDR,84.85.106.110/32,📲 电报信息
- IP-CIDR,143.176.18.30/32,📲 电报信息
- IP-CIDR,91.237.84.136/32,📲 电报信息
#===================== 配置文件 =====================#
port: 7890
socks-port: 7891
allow-lan: true
bind-address: "*"
ipv6: false
mode: rule
log-level: silent
external-controller: 0.0.0.0:9090
redir-port: 7892
secret: "123456"
external-ui: "/usr/share/openclash/dashboard"
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  listen: 127.0.0.1:7874
  fake-ip-filter:
##Custom fake-ip-filter##
  - '*.lan'
  - 'time.windows.com'
  - 'time.nist.gov'
  - 'time.apple.com'
  - 'time.asia.apple.com'
  - '*.ntp.org.cn'
  - '*.openwrt.pool.ntp.org'
  - 'time1.cloud.tencent.com'
  - 'time.ustc.edu.cn'
  - 'pool.ntp.org'
  - 'ntp.ubuntu.com'
  - 'ntp.aliyun.com'
  - 'ntp1.aliyun.com'
  - 'ntp2.aliyun.com'
  - 'ntp3.aliyun.com'
  - 'ntp4.aliyun.com'
  - 'ntp5.aliyun.com'
  - 'ntp6.aliyun.com'
  - 'ntp7.aliyun.com'
  - 'time1.aliyun.com'
  - 'time2.aliyun.com'
  - 'time3.aliyun.com'
  - 'time4.aliyun.com'
  - 'time5.aliyun.com'
  - 'time6.aliyun.com'
  - 'time7.aliyun.com'
  - '*.time.edu.cn'
  - 'time1.apple.com'
  - 'time2.apple.com'
  - 'time3.apple.com'
  - 'time4.apple.com'
  - 'time5.apple.com'
  - 'time6.apple.com'
  - 'time7.apple.com'
  - 'time1.google.com'
  - 'time2.google.com'
  - 'time3.google.com'
  - 'time4.google.com'
  - 'music.163.com'
  - '*.music.163.com'
  - '*.126.net'
  - 'musicapi.taihe.com'
  - 'music.taihe.com'
  - 'songsearch.kugou.com'
  - 'trackercdn.kugou.com'
  - '*.kuwo.cn'
  - 'api-jooxtt.sanook.com'
  - 'api.joox.com'
  - 'joox.com'
  - 'y.qq.com'
  - '*.y.qq.com'
  - 'streamoc.music.tc.qq.com'
  - 'mobileoc.music.tc.qq.com'
  - 'isure.stream.qqmusic.qq.com'
  - 'dl.stream.qqmusic.qq.com'
  - 'aqqmusic.tc.qq.com'
  - 'amobile.music.tc.qq.com'
  - '*.xiami.com'
  - '*.music.migu.cn'
  - 'music.migu.cn'
  - '*.msftconnecttest.com'
  - '*.msftncsi.com'
  - 'localhost.ptlogin2.qq.com'
  - '*.*.*.srv.nintendo.net'
  - '*.*.stun.playstation.net'
  - 'xbox.*.*.microsoft.com'
  - '*.*.xboxlive.com'
##Custom fake-ip-filter END##
##Custom DNS##
  nameserver:
  - 219.146.1.66
  - 219.147.1.66
  fallback:
  - tls://8.8.8.8:853
  - https://1.1.1.1/dns-query
  - tls://1.1.1.1:853
  - https://doh.rixcloud.dev/dns-query
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4

#===================== 防火墙设置 =====================#

#NAT chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    openclash  tcp  --  0.0.0.0/0            0.0.0.0/0           
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         
1    DOCKER_OUTPUT  all  --  0.0.0.0/0            127.0.0.11          
2    openclash_output  tcp  --  0.0.0.0/0            0.0.0.0/0           

#Mangle chain

#===================== 路由表状态 =====================#
#route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.1.1.1        0.0.0.0         UG    0      0        0 br-lan
10.1.1.0        0.0.0.0         255.255.255.0   U     0      0        0 br-lan
#ip route list
default via 10.1.1.1 dev br-lan proto static 
10.1.1.0/24 dev br-lan proto kernel scope link src 10.1.1.122 
#ip rule show
0:	from all lookup local
32766:	from all lookup main
32767:	from all lookup default

#===================== 端口占用状态 =====================#
tcp        0      0 :::7890                 :::*                    LISTEN      15053/clash
tcp        0      0 :::7891                 :::*                    LISTEN      15053/clash
tcp        0      0 :::7892                 :::*                    LISTEN      15053/clash
tcp        0      0 :::9090                 :::*                    LISTEN      15053/clash
udp        0      0 127.0.0.1:7874          0.0.0.0:*                           15053/clash
udp        0      0 :::7891                 :::*                                15053/clash
udp        0      0 :::7892                 :::*                                15053/clash

#===================== 测试本机DNS查询 =====================#
Server:		127.0.0.1
Address:	127.0.0.1#53

Name:      www.baidu.com
Address 1: 198.18.0.138
*** Can't find www.baidu.com: No answer

#===================== resolv.conf.d =====================#
# Interface lan
nameserver 10.1.1.1

#===================== 测试本机网络连接 =====================#

#===================== 测试本机网络下载 =====================#
HTTP/1.1 200 Connection established

HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 78
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: text/plain; charset=utf-8
ETag: "2f3a02f4e4fb5831f64d24282cbac5aee98c06edf5f10619508297c30fa0572d"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
Via: 1.1 varnish (Varnish/6.0)
X-GitHub-Request-Id: 2784:0724:99A91:B90D6:5F4092A4
Accept-Ranges: bytes
Date: Sat, 22 Aug 2020 05:22:07 GMT
Via: 1.1 varnish
X-Served-By: cache-hkg17933-HKG
X-Cache: HIT, HIT
X-Cache-Hits: 1, 1
X-Timer: S1598073727.130095,VS0,VE1
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
X-Fastly-Request-ID: d7d6db2c9966fb690a21abbadbf679d65140f6b2
Expires: Sat, 22 Aug 2020 05:27:07 GMT
Source-Age: 281

#===================== 最近运行日志 =====================#
time="2020-08-22T13:21:42+08:00" level=info msg="Start initial compatible provider 🐟 漏网之鱼"
time="2020-08-22T13:21:42+08:00" level=info msg="Start initial compatible provider 🛑 全球拦截"
time="2020-08-22T13:21:42+08:00" level=info msg="Start initial compatible provider Ⓜ️ 微软服务"
time="2020-08-22T13:21:42+08:00" level=info msg="Start initial compatible provider 🍃 应用净化"
time="2020-08-22T13:21:42+08:00" level=info msg="Start initial compatible provider 🍎 苹果服务"
time="2020-08-22T13:21:42+08:00" level=info msg="Start initial compatible provider ♻️ 自动选择"
time="2020-08-22T13:21:42+08:00" level=info msg="Start initial compatible provider 🚀 节点选择"
time="2020-08-22T13:21:42+08:00" level=info msg="Start initial compatible provider 📢 谷歌FCM"
time="2020-08-22T13:21:42+08:00" level=info msg="Start initial compatible provider 🆎 AdBlock"
time="2020-08-22T13:21:42+08:00" level=info msg="Start initial compatible provider 🌍 国外媒体"
time="2020-08-22T13:21:42+08:00" level=info msg="Start initial compatible provider 🎯 全球直连"
time="2020-08-22T13:21:42+08:00" level=info msg="Start initial compatible provider 📲 电报信息"
2020-08-22 13:21:29 OpenClash Start Successful

**Comment by matthuo333** [comment]
> 我的n1正常，混合模式和增强模式，第一次用增强模式感觉不错

用N1 docker 下起的op ,然后运行clash? 我的总是域名解析以及海外不行

**Comment by matthuo333** [comment]
> fake ip 增强模式不能使用。混合模式tun，不能代理ip地址的访问，域名可以

拔电重启后，还可以么？
