### ISSUE TITLE
上传了规则，但为啥还会报error: unsupported rule type RULE-SET"

### ISSUE THREAD

**Issue by dover** [vernesong/OpenClash#681]
level=fatal msg="Parse config error: Rules[0] [RULE-SET,Unbreak,DIRECT] error: unsupported rule type RULE-SET"

**Comment by OUZYcn** [comment]
你不贴出这段相关的config，光问有啥用

**Comment by dover** [comment]
# Unbreak
  - RULE-SET,Unbreak,DIRECT

  # Global Area Network

  # (Streaming Media)
  - RULE-SET,Streaming,Streaming

  # (StreamingSE)
  - RULE-SET,StreamingSE,StreamingSE

  # (DNS Cache Pollution) / (IP Blackhole) / (Region-Restricted Access Denied) / (Network Jitter)
  - RULE-SET,Global,PROXY

  # China Area Network
  - RULE-SET,China,DIRECT

**Comment by vernesong** [comment]
rule-providers写了没

**Comment by dover** [comment]
已经搞定，谢谢回复的人

**Comment by sunliang711** [comment]
> 已经搞定，谢谢回复的人

大哥怎么搞定的，我也遇到这个问题了

**Comment by z-dn** [comment]
请问是如何解决的？

**Comment by Num0** [comment]
同问是如何解决的？

**Comment by vernesong** [comment]
只装一个tun内核就行了

**Comment by terryzhouke** [comment]
同问，怎么解决的？

**Comment by Xuzan9396** [comment]
提示什么注释什么！
![image](https://user-images.githubusercontent.com/24741439/130037344-4407e838-af34-409a-b0f4-f0e471392dab.png)

**Comment by Xuzan9396** [comment]
不行，变成全局代理了

**Comment by Kritosy** [comment]
> 提示什么注释什么！ ![image](https://user-images.githubusercontent.com/24741439/130037344-4407e838-af34-409a-b0f4-f0e471392dab.png)

大佬，每次更新订阅完都手动注释的吗，我也是这个问题，有点烦

**Comment by dalengs** [comment]
有半官方文档的解释， `您正在使用 Clash 开源版. 规则 Providers 目前仅在 [Premium 内核](https://downloads.clash.wiki/ClashPremium) 中可用.`
https://clash.wiki/introduction/faq.html#%E9%94%99%E8%AF%AF-%E4%B8%8D%E6%94%AF%E6%8C%81%E7%9A%84-rule-set-%E8%A7%84%E5%88%99%E7%B1%BB%E5%9E%8B
