### ISSUE TITLE
建议添加真~DNS劫持功能

### ISSUE THREAD

**Issue by bleeee** [vernesong/OpenClash#682]
iptables -t nat -I PREROUTING -i br-lan -p udp --dport 53 -j DNAT --to 192.168.1.1
iptables -t nat -I PREROUTING -i br-lan -p tcp --dport 53 -j DNAT --to 192.168.1.1

不然有些谷歌的产品顽固的用8.8.8.8

**Comment by terenceng81** [comment]
我的 nvidia shield 原生 google TV 有类似问题。

必须开全局，而且ip那要开proxy指向openclash.

**Comment by hcym** [comment]
原生盒子还行，原生的手机用谷歌app也正常，谷歌home没用过，应该可以吧，走隧道的dns都是8888

**Comment by vernesong** [comment]
用混合模式或者tun模式，已劫持谷歌dns

**Comment by secretandanon** [comment]
实现不行你可以在openwrt防火墙下设置转发53端口
