### ISSUE TITLE
由于以下错误，配置文件无法被加载：

### ISSUE THREAD

**Issue by phields** [vernesong/OpenClash#685]
由于以下错误，配置文件无法被加载：
uci: Parse error (option/list command found before the first section) at line 1, byte 1

	option name 'blink'

config config_subscribe
	option enabled '1'
	option type 'clash'
	option name 'poi'
	option address 'https://api.poicloud.download/sub?target=clash&url=https%3A%2F%2Fapi.poicloud.org%2Flink%fsfsdfZ%3Fmu%3D6&insert=false&config=https%3A%2F%2Fsubconverter.oss-ap-southeast-1.aliyuncs.com%2FRules%2FRemoteConfig%2Funiversal%2Fno-urltest.ini&emoji=true&list=false&udp=false&tfo=false&scv=false&fdn=false&sort=false&new_name=true'

**Comment by vernesong** [comment]
版本更新页面还原默认配置
