### ISSUE TITLE
v0.39.8就算是装好了内核也无法正常使用

### ISSUE THREAD

**Issue by hnxxd** [vernesong/OpenClash#686]
在首页显示运行正常，youtubu无法连接
到更新里无法显示版本号。

**Comment by terenceng81** [comment]
内核编译版本要选适合的。。

你的配置文件是机场给你的吗？

**Comment by hnxxd** [comment]
机场配置文件，我另一台路由器是可以使用的，就是新路由3D2这台，以前38.04版本正常，升级最新版本后，上不了网了。而且到更新里长时间没有显示版本号

**Comment by Orokapei** [comment]
> 机场配置文件，我另一台路由器是可以使用的，就是新路由3D2这台，以前38.04版本正常，升级最新版本后，上不了网了。而且到更新里长时间没有显示版本号

是不是这样的，以前的内核没问题。（我自个编译的也有这问题）
https://github.com/vernesong/OpenClash/issues/678#issue-682768309

**Comment by vernesong** [comment]
UPX的问题吧，你可以试试自己编译一个最新内核，不压缩

**Comment by Orokapei** [comment]
果然是upx的问题🙄但是不压缩的话rom空间不够，暂时扔tmp，ln后运行了🙉🙉🙉
