### ISSUE TITLE
19.07无法访问yacd,打开后死循环问host/port那个灰色页面。控制面板直接就是打不开

### ISSUE THREAD

**Issue by nostalgicc** [vernesong/OpenClash#687]
测试了多种固件

**Comment by terenceng81** [comment]
你是使用 https 还是 http?

yacd 目前不支持 https

**Comment by nostalgicc** [comment]
> 你是使用 https 还是 http?
> 
> yacd 目前不支持 https

是http

**Comment by c17pl** [comment]
好像是新内核有问题?我是新路由3，用mipsle内核，版本号认不出，yacd面板也是循环让我登录，之前0.39.7+1.0.31内核没有问题，然而老内核已经被我删掉了，没办法做对照了

**Comment by nostalgicc** [comment]
> 好像是新内核有问题?我是新路由3，用mipsle内核，版本号认不出，yacd面板也是循环让我登录，之前0.39.7+1.0.31内核没有问题，然而老内核已经被我删掉了，没办法做对照了


同款路由同款问题。。。mipsle softfloat

**Comment by hcym** [comment]
mtk还是AP合适，我的x64和armv8都正常使用

**Comment by nostalgicc** [comment]
> mtk还是AP合适，我的x64和armv8都正常使用

问题是之前一直都能用就忍不了，老版内核怎么找。。

**Comment by c17pl** [comment]
> 
> 
> > mtk还是AP合适，我的x64和armv8都正常使用
> 
> 问题是之前一直都能用就忍不了，老版内核怎么找。。

我弱智了，刚刚看了一下，0.39.7附着的就是老内核

**Comment by vernesong** [comment]
应该是upx压缩问题，下个版本我换回老版本压缩试试

**Comment by c17pl** [comment]
> 
> 
> 应该是upx压缩问题，下个版本我换回老版本压缩试试

1.1.0-5内核配合0.39.7问题依旧

**Comment by vernesong** [comment]
[clash-linux-mipsle-softfloat.tar.gz](https://github.com/vernesong/OpenClash/files/5143060/clash-linux-mipsle-softfloat.tar.gz)

**Comment by c17pl** [comment]
> 
> 
> [clash-linux-mipsle-softfloat.tar.gz](https://github.com/vernesong/OpenClash/files/5143060/clash-linux-mipsle-softfloat.tar.gz)

还是不行，0.39.7和0.39.8都跑不起来，虽然主程序看起来跑起来了，但是面板还是循环的，实际代理也无法使用

**Comment by nostalgicc** [comment]
> > [clash-linux-mipsle-softfloat.tar.gz](https://github.com/vernesong/OpenClash/files/5143060/clash-linux-mipsle-softfloat.tar.gz)
> 
> 还是不行，0.39.7和0.39.8都跑不起来，虽然主程序看起来跑起来了，但是面板还是循环的，实际代理也无法使用

我还没测试，但是八成问题和你们一样

**Comment by pfangzhi** [comment]
不用测试了，7621平台的新版带upx的都不能启动，是程序启动了但是没有工作。
