### ISSUE TITLE
连接IPSec VPN 服务器无法翻墙？

### ISSUE THREAD

**Issue by silmee** [vernesong/OpenClash#689]
IPSec VPN 服务器用安卓自带的连接方式连接到家里的路由器后没办法翻墙，WiFi下可以正常翻。
咋解决啊~？？

**Comment by vernesong** [comment]
尝试fake-ip模式，目前主机自身纯IP流量的代理没有很好的解决办法

**Comment by jerryliang122** [comment]
如果你不想用fake-ip的话可以把你的IPSec 下放到路由器下层硬件上（树莓派）这类硬件上

**Comment by vernesong** [comment]
将下发网段设置为和路由器相同的内网网段，下发DNS设置为路由器的lan口IP

**Comment by auroracamus** [comment]
你看一下wireguard的客户端的配置文件中，DNS那一项是不是没填？填114.114.114.114试试看（或是网关地址），我就是这么解决的。
