### ISSUE TITLE
ipv6 nat 流量被拦截

### ISSUE THREAD

**Issue by de-conf** [vernesong/OpenClash#690]
当前版本
v1.0.0-33-g8b7c731
模式: Redir-Host
当配置好ipv6 nat之后 ipv6 流量无法从下面的主机 到达目标主机，主要问题在openwrt的ipv6防火墙表

路由器ipv6 可通
![image](https://user-images.githubusercontent.com/26062629/91316687-b0eeeb00-e7eb-11ea-8688-77d1d6cee65c.png)
下面的主机到目标地址不可达
![image](https://user-images.githubusercontent.com/26062629/91318178-87cf5a00-e7ed-11ea-94d8-eb1d94bbd964.png)
主机到路由ipv6可达
![image](https://user-images.githubusercontent.com/26062629/91318238-97e73980-e7ed-11ea-9a54-593c8b0fef37.png)

**Comment by de-conf** [comment]
其中IP6tables表中
` -A openclash -p tcp -j REDIRECT --to-ports 7892`
 是把所有 tcp 连接都重定向到本地的 7892 端口，由监听在后者上的程序来处理
导致本地nat6根本无法正常通讯

**Comment by de-conf** [comment]
icmp6不通的原因是openwt它使用了源地址路由，导致电脑出去的流量实际上没有匹配上主路由表里的任何一条路由
解决办法
ip -6 r add ::/0 via <本地ipv6地址> dev eth1.2
但是由于openclash劫持ipv6流量，导致正常ipv6连接无法建立与正常通讯
望修复！

**Comment by vernesong** [comment]
ip6tables-mod-nat装了吗

**Comment by de-conf** [comment]
> ip6tables-mod-nat装了吗
按照这个教程来的
https://github.com/tuna/ipv6.tsinghua.edu.cn/blob/master/openwrt.md

**Comment by vernesong** [comment]
装上试试

**Comment by de-conf** [comment]
> 装上试试

装过了

**Comment by de-conf** [comment]
> 装上试试
已装软件包：ip6tables kmod-ipt-nat6 kmod-ip6tables kmod-ip6tables-extra luci-proto-ipv6 iputils-traceroute6
在之前设置中如果没有openclash，ipv6流量表现正常,

**Comment by de-conf** [comment]
这是路由器ip6tables表，可以看到确实openclash拦截了ipv6流量
[ip6tables-save.txt](https://github.com/vernesong/OpenClash/files/5150313/ip6tables-save.txt)

**Comment by de-conf** [comment]
目前，手动办法只有把ip6tables表中openclash的自定义链删除掉
放下命令以供相同问题解决方案参考
```
ip6tables -t nat -D PREROUTING -p tcp  -j openclash
ip6tables -t nat -F openclash
ip6tables -t nat -X openclash
```

**Comment by zhihuiyuze** [comment]
> 
> 
> 目前，手动办法只有把ip6tables nat表中openclash的自定义链删除掉
> 放下命令以供相同问题解决方案参考
> 
> ```
> ip6tables -t nat -D PREROUTING -p tcp  -j openclash
> ip6tables -t nat -F openclash
> ip6tables -t nat -X openclash
> ```

您好，现在openclash这个表好像不存在了。现在有啥解决办法？我想关闭代理ipv6.

**Comment by openips** [comment]
方案不错

**Comment by yubanmeiqin9048** [comment]
> ip6tables-mod-nat

新版本改了IPV6流量不进openclash之后还需要装ip6tables-mod-nat吗？
