### ISSUE TITLE
IPv6 一定要 Nat 吗

### ISSUE THREAD

**Issue by smallst** [vernesong/OpenClash#691]
目前很多运营商已经有 ipv6 pd 了，我的路由器本来也是设置了pd，没有安装 ip6tables-mod-nat，可以正常使用 v6
之前路由器搭配 v2ray pro 使用的时候 v6 pd 也不影响，改用 Openclash 后 ipv6 就失效了。感觉应该是 dns 解析的问题，dns 支持 v6 后还是不行，看了下已有 issue 都说要装nat。目前打算试一试。

不过能不能支持 pd 呢？或者可以不劫持 v6 的 dns 保留路由器原有的配置吗

**Comment by smallst** [comment]
使用 smartDNS 作为上游 和 fake-Ip 居然解决了……

**Comment by yubanmeiqin9048** [comment]
> 使用 smartDNS 作为上游 和 fake-Ip 居然解决了……

新版clash直接不让IPV6流量进来了，不装也可以
