### ISSUE TITLE
请求增加v2ray的vless协议

### ISSUE THREAD

**Issue by Rakau** [vernesong/OpenClash#692]
RT

**Comment by lifetyper** [comment]
你应该去clash那里提，而不是这里。

**Comment by Rakau** [comment]
这个不是clash吗

**Comment by topjohncian** [comment]
> 这个不是clash吗

https://github.com/Dreamacro/clash

**Comment by Rakau** [comment]
> > 这个不是clash吗
> 
> https://github.com/Dreamacro/clash

感谢
