### ISSUE TITLE
更新最新内核后无法正常使用

### ISSUE THREAD

**Issue by iadao** [vernesong/OpenClash#694]
1.更新最新dev内核后，无法获取版本更新的相关信息，可以正常启动，但无法上网和无法生成调试日志，必须删除这个内核才可以正常获取相关信息和生成调试日志。

以下为删除dev内核后的调试信息
OpenClash 调试日志

生成时间: 2020-08-28 16:29:43
插件版本: v0.39.8-beta

#===================== 系统信息 =====================#
主机型号: XiaoYu XY-C5
固件版本: OpenWrt SNAPSHOT r0-299da0a
LuCI版本: git-20.141.34051-f750b5f-1
内核版本: 4.14.180
处理器架构: mipsel_24kc

#此项在使用Tun模式时应为ACCEPT
防火墙转发: ACCEPT

#此项有值时建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: 

#此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 

#===================== 依赖检查 =====================#
dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
jsonfilter: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
iptables-mod-tproxy: 已安装
kmod-tun(TUN模式): 已安装
luci-compat(Luci-19.07): 已安装

#===================== 内核检查 =====================#
运行状态: 未运行
已选择的架构: linux-mipsle-softfloat

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 
Tun内核文件: 不存在
Tun内核运行权限: 否

Game内核版本: v0.17.0-175-g7f77c72
Game内核文件: 存在
Game内核运行权限: 正常

Dev内核版本: 
Dev内核文件: 不存在
Dev内核运行权限: 否

#===================== 插件设置 =====================#
当前配置文件: /etc/openclash/config/123.yaml
运行模式: fake-ip-vpn
默认代理模式: rule
UDP流量转发: 停用
DNS劫持: 启用
自定义DNS: 启用
IPV6-DNS解析: 停用
禁用Dnsmasq缓存: 启用
自定义规则: 停用
仅允许内网: 停用
仅代理命中规则流量: 停用

#启动异常时建议关闭此项后重试
保留配置: 停用
第三方规则: 停用

#===================== 配置文件 =====================#
port: 7890
socks-port: 7891
allow-lan: true
bind-address: "*"
ipv6: false
mode: rule
log-level: silent
external-controller: 0.0.0.0:9090
redir-port: 7892
secret: "123456789"
external-ui: "/usr/share/openclash/dashboard"
tun:
  enable: true
  device-url: dev://clash0
  dns-listen: 0.0.0.0:53
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  listen: 127.0.0.1:7874
  fake-ip-filter:
##Custom fake-ip-filter##
  - '*.lan'
  - 'time.windows.com'
  - 'time.nist.gov'
  - 'time.apple.com'
  - 'time.asia.apple.com'
  - '*.ntp.org.cn'
  - '*.openwrt.pool.ntp.org'
  - 'time1.cloud.tencent.com'
  - 'time.ustc.edu.cn'
  - 'pool.ntp.org'
  - 'ntp.ubuntu.com'
  - 'ntp.aliyun.com'
  - 'ntp1.aliyun.com'
  - 'ntp2.aliyun.com'
  - 'ntp3.aliyun.com'
  - 'ntp4.aliyun.com'
  - 'ntp5.aliyun.com'
  - 'ntp6.aliyun.com'
  - 'ntp7.aliyun.com'
  - 'time1.aliyun.com'
  - 'time2.aliyun.com'
  - 'time3.aliyun.com'
  - 'time4.aliyun.com'
  - 'time5.aliyun.com'
  - 'time6.aliyun.com'
  - 'time7.aliyun.com'
  - '*.time.edu.cn'
  - 'time1.apple.com'
  - 'time2.apple.com'
  - 'time3.apple.com'
  - 'time4.apple.com'
  - 'time5.apple.com'
  - 'time6.apple.com'
  - 'time7.apple.com'
  - 'time1.google.com'
  - 'time2.google.com'
  - 'time3.google.com'
  - 'time4.google.com'
  - 'music.163.com'
  - '*.music.163.com'
  - '*.126.net'
  - 'musicapi.taihe.com'
  - 'music.taihe.com'
  - 'songsearch.kugou.com'
  - 'trackercdn.kugou.com'
  - '*.kuwo.cn'
  - 'api-jooxtt.sanook.com'
  - 'api.joox.com'
  - 'joox.com'
  - 'y.qq.com'
  - '*.y.qq.com'
  - 'streamoc.music.tc.qq.com'
  - 'mobileoc.music.tc.qq.com'
  - 'isure.stream.qqmusic.qq.com'
  - 'dl.stream.qqmusic.qq.com'
  - 'aqqmusic.tc.qq.com'
  - 'amobile.music.tc.qq.com'
  - '*.xiami.com'
  - '*.music.migu.cn'
  - 'music.migu.cn'
  - '*.msftconnecttest.com'
  - '*.msftncsi.com'
  - 'localhost.ptlogin2.qq.com'
  - '*.*.*.srv.nintendo.net'
  - '*.*.stun.playstation.net'
  - 'xbox.*.*.microsoft.com'
  - '*.*.xboxlive.com'
##Custom fake-ip-filter END##
##Custom DNS##
  nameserver:
  - 114.114.114.114
  - 119.29.29.29
  fallback:
  - tls://8.8.8.8:853
  fallback-filter:
    geoip: true
    ipcidr:
      - 0.0.0.0/8
      - 10.0.0.0/8
      - 100.64.0.0/10
      - 127.0.0.0/8
      - 169.254.0.0/16
      - 172.16.0.0/12
      - 192.0.0.0/24
      - 192.0.2.0/24
      - 192.88.99.0/24
      - 192.168.0.0/16
      - 198.18.0.0/15
      - 198.51.100.0/24
      - 203.0.113.0/24
      - 224.0.0.0/4
      - 240.0.0.0/4
      - 255.255.255.255/32

#===================== 防火墙设置 =====================#

#NAT chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    SS_SPEC_WAN_AC  tcp  --  0.0.0.0/0            0.0.0.0/0            match-set ss_spec_lan_ac src /* _SS_SPEC_RULE_ */
2    REDIRECT   udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:53 redir ports 53
3    REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:53 redir ports 53
4    prerouting_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom prerouting rule chain */
5    zone_lan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
6    zone_wan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
7    zone_wan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         
1    SS_SPEC_WAN_AC  tcp  --  0.0.0.0/0            0.0.0.0/0            /* _SS_SPEC_RULE_ */

#Mangle chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         

#===================== 路由表状态 =====================#
#route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         1.94.160.1      0.0.0.0         UG    0      0        0 pppoe-wan
1.94.160.1      0.0.0.0         255.255.255.255 UH    0      0        0 pppoe-wan
192.168.10.0    0.0.0.0         255.255.255.0   U     0      0        0 br-lan
#ip route list
default via 1.94.160.1 dev pppoe-wan proto static 
1.94.160.1 dev pppoe-wan proto kernel scope link src 1.94.173.229 
192.168.10.0/24 dev br-lan proto kernel scope link src 192.168.10.222 
#ip rule show
0:	from all lookup local
32766:	from all lookup main
32767:	from all lookup default

#===================== Tun设备状态 =====================#

#===================== 端口占用状态 =====================#

#===================== 测试本机DNS查询 =====================#
Server:		219.239.26.42
Address:	219.239.26.42#53

Name:      www.baidu.com
www.baidu.com	canonical name = www.a.shifen.com
Name:      www.a.shifen.com
Address 1: 182.61.200.7
Address 2: 182.61.200.6
www.baidu.com	canonical name = www.a.shifen.com

#===================== resolv.conf.auto =====================#
# Interface wan
nameserver 219.239.26.42
nameserver 124.207.160.106

#===================== 测试本机网络连接 =====================#
HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: private, no-cache, no-store, proxy-revalidate, no-transform
Connection: keep-alive
Content-Length: 277
Content-Type: text/html
Date: Fri, 28 Aug 2020 08:29:48 GMT
Etag: "575e1f60-115"
Last-Modified: Mon, 13 Jun 2016 02:50:08 GMT
Pragma: no-cache
Server: bfe/1.0.8.18

#===================== 测试本机网络下载 =====================#

#===================== 最近运行日志 =====================#

**Comment by vernesong** [comment]
[clash-linux-mipsle-softfloat.tar.gz](https://github.com/vernesong/OpenClash/files/5142972/clash-linux-mipsle-softfloat.tar.gz)
试试这个

**Comment by pfangzhi** [comment]
最近几个加了upx的版本我7621也不能用了，表现就是程序打开无反应，连出错都不报，armv8版本正常。

**Comment by iadao** [comment]
> [clash-linux-mipsle-softfloat.tar.gz](https://github.com/vernesong/OpenClash/files/5142972/clash-linux-mipsle-softfloat.tar.gz)
> 试试这个

我换了v0.39.7的版本内核是正常的，不过发的这个我也试了一下，问题和新版本的基本一致。

**Comment by iadao** [comment]
> 最近几个加了upx的版本我7621也不能用了，表现就是程序打开无反应，连出错都不报，armv8版本正常。

试试v0.39.7里面的内核版本，我是可以正常使用的

**Comment by Gol2dragon** [comment]
> > 最近几个加了upx的版本我7621也不能用了，表现就是程序打开无反应，连出错都不报，armv8版本正常。
> 
> 试试v0.39.7里面的内核版本，我是可以正常使用的

我的情况和你的一样，最新Dev内核不显示版本号，而且导致openclash启动失败
