### ISSUE TITLE
苹果设备经常性打不开国内资源

### ISSUE THREAD

**Issue by smallst** [vernesong/OpenClash#695]
使用了 openclash 的 fake-ip 模式
win10电脑以及安卓设备正常使用， ipone手机和ipad平板间歇性出现各种app连不上的情况，包括（但应该不限于）微信、抖音、微博等国内资源。重启设备能好一段时间，过一会儿又会出现，非常影响使用。

无法定位问题所在，求指导应该怎么定位。目前规则中和苹果相关的域名全部使用了 DIRECT 连接。
log 里除了一些不清楚哪来的ip地址加奇怪的端口（7680）会 timeout 外其余的看起来挺正常

**Comment by vernesong** [comment]
路由器网络接口的dns换一下，禁用dnsmasq的dns缓存

**Comment by smallst** [comment]
@vernesong  你好，感谢回复！请问一下是讲路由器接口wan里的dns 改成127.0.0.1 吗？ 禁用dnsmasq缓存是openclash 里操作吗？情况好像有好转，但目前微信图片还是加载很慢

（另外为什么dns缓存只影响苹果呢 :joy:)

**Comment by vernesong** [comment]
直连本身就跟插件没太大关系，主要看你本地网络

**Comment by smallst** [comment]
@vernesong 嗯……我也是这样想的，但实际上把openclash关掉就没有问题 😂  在想是不是哪里设置出了问题

**Comment by vernesong** [comment]
插件的dns换几个试试

**Comment by smallst** [comment]
```
2020/8/29 下午5:25:51
warning
dial DIRECT error: dial tcp4 219.230.69.43:36846: i/o timeout
2020/8/29 下午5:25:51
warning
dial DIRECT error: dial tcp4 222.168.71.83:7680: i/o timeout
2020/8/29 下午5:26:10
warning
dial DIRECT error: dial tcp4 223.72.45.100:7680: i/o timeout
2020/8/29 下午5:26:10
warning
dial DIRECT error: dial tcp4 59.46.96.47:7680: i/o timeout
2020/8/29 下午5:26:08
warning
dial DIRECT error: dial tcp4 111.32.180.225:7680: i/o timeout
```
这些 dial timeout 也是dns的原因吗

**Comment by vernesong** [comment]
连接超时，大概率是DNS返回的cdn不对

**Comment by smallst** [comment]
@vernesong  非常感谢。目前情况已有好转，具体问题我再自己探究探究。

不过目前有另外一个问题，路由器接口的dns设置了127.0.0.1 之后 ipv6 网站就不能上了 😂  但使用端局通告的话还是可以的（主要是 ipv6 pt 站只接受 ipv6 的情况），看了看log和 clash 源代码感觉是 ipv6resolver 在代码中默认 disable 了https://github.com/Dreamacro/clash/blob/50d778da3c155af36181b53aa736b21fb3753f24/component/resolver/resolver.go#L17
所以无法取得域名的 AAAA 记录（即使配置了 ipv6 true) ，不知道我的理解对不对，反正我 clone 了源码将这行改成 false 也没法正常解析 v6 域名……这个有办法吗 😂

**Comment by vernesong** [comment]
> @vernesong 非常感谢。目前情况已有好转，具体问题我再自己探究探究。
> 
> 不过目前有另外一个问题，路由器接口的dns设置了127.0.0.1 之后 ipv6 网站就不能上了 😂 但使用端局通告的话还是可以的（主要是 ipv6 pt 站只接受 ipv6 的情况），看了看log和 clash 源代码感觉是 ipv6resolver 在代码中默认 disable 了https://github.com/Dreamacro/clash/blob/50d778da3c155af36181b53aa736b21fb3753f24/component/resolver/resolver.go#L17
> 所以无法取得域名的 AAAA 记录（即使配置了 ipv6 true) ，不知道我的理解对不对，反正我 clone 了源码将这行改成 false 也没法正常解析 v6 域名……这个有办法吗 😂 不要求 v6 能走代理，只要给普通的v6 直连就行了。另外我的路由器是 v6 pd， 不是 nat

下个版本加选项，可以正常返回ipv6的结果

**Comment by smallst** [comment]
好的，感谢

**Comment by smallst** [comment]
最近又出现这个问题，仔细比对了一下 log 发现，ios设备的请求似乎没有到达 openclash (只有ios在请求网络时 openclash 的log 里没有任何记录，debug模式），即使我在ios端将wifi 的dns 手动设置成路由器地址也不行，这可能是什么问题呢？

**Comment by vernesong** [comment]
网关和dns都需要设置

**Comment by smallst** [comment]
@vernesong 咦……dhcp获取 ipv4 地址的话网关似乎不可以改啊 😂
