### ISSUE TITLE
我想自定义一些IP的特定端口走代理 要如何设置呢？

### ISSUE THREAD

**Issue by ghost** [vernesong/OpenClash#696]
公司有很多国外的服务器  用远程桌面访问 比方我有一台国外的服务器 IP是 1.1.1.1 需要访问的端口是4444     那么我如何设置访问1.1.1.1:4444这个端口走代理呢？

**Comment by vernesong** [comment]
最简单的是加一条规则
- IP-CIDR,127.0.0.0/8,DIRECT
复杂的是用script模式写py规则

**Comment by BigDog66** [comment]
> 最简单的是加一条规则
> 
> * IP-CIDR,127.0.0.0/8,DIRECT
>   复杂的是用script模式写py规则


我ping baidu.com 得到的IP是 220.181.38.148 就在自定义规则了添加了 IP-CIDR,220.181.38.148/32,DIRECT 这条规则来测试  但访问baidu.com走的还是国内IP 
![image](https://user-images.githubusercontent.com/69404815/91624396-af334c00-e9d2-11ea-95a3-6d33149336c9.png)

![image](https://user-images.githubusercontent.com/69404815/91624418-c40fdf80-e9d2-11ea-9696-59abd98b3425.png)

**Comment by adamw92** [comment]
> > 最简单的是加一条规则
> > 
> > * IP-CIDR,127.0.0.0/8,DIRECT
> >   复杂的是用script模式写py规则
> 
> 我ping baidu.com 得到的IP是 220.181.38.148 就在自定义规则了添加了 IP-CIDR,220.181.38.148/32,DIRECT 这条规则来测试 但访问baidu.com走的还是国内IP
> ![image](https://user-images.githubusercontent.com/69404815/91624396-af334c00-e9d2-11ea-95a3-6d33149336c9.png)
> 
> ![image](https://user-images.githubusercontent.com/69404815/91624418-c40fdf80-e9d2-11ea-9696-59abd98b3425.png)

不是每次访问baidu.com都会获得220.181.38.148这个IP，就算当次访问获得的是这个IP，openclash也按照你的要求进行直连了（DIRECT)，要调整*.baidu.com的访问方式，你应该使用的是
- DOMAIN-SUFFIX,baidu.com,你要用的proxy-group 名字
