### ISSUE TITLE
mt7621版本，自从0.9.5以后启用upx后程序就打不开了，

### ISSUE THREAD

**Issue by pfangzhi** [vernesong/OpenClash#698]
mt7621版本，自从0.9.5以后启用upx后程序就打不开了，我是纯用程序然后命令行启动，表现就是程序运行后无任何反应，没有自动退出，没有错误提示，进程一直在，没有数据流量，yacd都连不上，用旧的版本就可以正常使用。

**Comment by vernesong** [comment]
[clash-linux-mipsle-softfloat.tar.gz](https://github.com/vernesong/OpenClash/files/5145214/clash-linux-mipsle-softfloat.tar.gz)

**Comment by 1715173329** [comment]
> [clash-linux-mipsle-softfloat.tar.gz](https://github.com/vernesong/OpenClash/files/5145214/clash-linux-mipsle-softfloat.tar.gz)

该版本已测试可正常使用。

**Comment by pfangzhi** [comment]
> [clash-linux-mipsle-softfloat.tar.gz](https://github.com/vernesong/OpenClash/files/5145214/clash-linux-mipsle-softfloat.tar.gz)

这个版本正常启动。
