### ISSUE TITLE
无法访问google.com,fake ip无效

### ISSUE THREAD

**Issue by hermityang1230** [vernesong/OpenClash#699]
0.38.9版本，clash更新成最新版本
fakeip模式
无法访问www.google.com，换成www.google.com.hk可以正常访问
youtube可以正常打开，但是无法播放视频，发现是访问googlevideo.com失败
用dig查看域名解析，www.google.com和googlevideo.com返回都不是fakeip（172.xxx或者31.xxx），其他域名都可以正常返回fakeip
在fakeip黑名单里也没有配置www.google.com和googlevideo.com
切换到兼容模式也是一样的现象
请问大佬是什么问题。。。。。抓狂ing。。。。。

**Comment by vernesong** [comment]
插件没问题的话建议清理一下缓存或者重启

**Comment by hermityang1230** [comment]
> 插件没问题的话建议清理一下缓存或者重启

多谢大神，我重新刷了固件，重新安装就ok了。。。。
