### ISSUE TITLE
0.33.1-beta1 更新报错

### ISSUE THREAD

**Issue by HoonHwang** [vernesong/OpenClash#7]
报错信息如下：
Upgrading luci-app-openclash on root from 0.33.0-beta to 0.33.1-beta...
OpenClash Already Stop
Collected errors:
 * pkg_run_script: package "luci-app-openclash" preinst script returned status 1.
 * preinst_configure: Aborting installation of luci-app-openclash.
 * opkg_install_cmd: Cannot install package luci-app-openclash.

**Comment by vernesong** [comment]
卸载再装，不支持opkg upgrade
