### ISSUE TITLE
主界面显示已运行，无法连接网络，控制面板打不开

### ISSUE THREAD

**Issue by db992062117** [vernesong/OpenClash#701]
用的订阅连接，显示已运行，不过无法上网，控制面板无法打开，点进去登录就一直刷新登录界面，无法进入管理界面，我openwrt更新之前好用的，求大佬

**Comment by vernesong** [comment]
重新更新内核

**Comment by db992062117** [comment]
> 重新更新内核
就一直显示
![捕获](https://user-images.githubusercontent.com/70459120/91792898-3ab61280-ec49-11ea-8321-c3a70c5b4f38.PNG)
这样

**Comment by vernesong** [comment]
重新下载一下，内核已经更新了

**Comment by db992062117** [comment]
> 重新下载一下，内核已经更新了

谢谢大佬，已解决
