### ISSUE TITLE
定义hosts后 clash直连IP而不走域名

### ISSUE THREAD

**Issue by swj846454593** [vernesong/OpenClash#703]
![未定义hosts2](https://user-images.githubusercontent.com/57243967/91651702-7672a000-eac2-11ea-85cc-31f94dbdc1e8.PNG)
![未定义hosts](https://user-images.githubusercontent.com/57243967/91651703-77a3cd00-eac2-11ea-8adf-66c65b0e2650.PNG)
定义hosts后 Connections里显示连接的是IP而不是域名
![定义hosts2](https://user-images.githubusercontent.com/57243967/91651705-78d4fa00-eac2-11ea-99c4-aee830059e63.PNG)
![定义hosts](https://user-images.githubusercontent.com/57243967/91651706-7a9ebd80-eac2-11ea-8ad9-356fa4d68822.PNG)

**Comment by swj846454593** [comment]
Clash内核版本:v1.1.0-5-gc9735ef
客户端版本:v0.39.8-beta
处理器架构:x86_64
这是正常的还是bug啊 我也不懂

**Comment by vernesong** [comment]
建议去内核那边咨询
