### ISSUE TITLE
能否自定義DNS劫持地址「127.0.0.1」

### ISSUE THREAD

**Issue by natsumehowe** [vernesong/OpenClash#704]
當前DNS劫持在「127.0.0.1」請否能否自定義？
之所以這樣說是因為早期版本的CFW的TAP模式網卡設置上DNS地址也是設置為這一字段，導致部分網站訪問異常，CFW的issue下是有這樣的問題的，所以作者在後期的更新中網卡的DNS地址改在了「10.0.0.1」。
我沒有詳細了解過其中的技術問題，也許兩者對DNS劫持的原因和目的有所不同。但希望能夠提供自定義選項

**Comment by vernesong** [comment]
因为是在路由上，这个地址代表本机。
