### ISSUE TITLE
配置文件列表里的配置文件会莫名其妙消失全部的规则节点全部在

### ISSUE THREAD

**Issue by miaoermua** [vernesong/OpenClash#705]
如标题会消失所有网站的规则，本来400kb+的配置，开启openclash后立刻变成40+kb，重新拷贝备份好的配置应用也一样
版本：0.39.8 Fake-IP

**Comment by vernesong** [comment]
看一下配置文件规则部分是怎么写的，可能脚本识别有问题

**Comment by miaoermua** [comment]
配置前如下
redir-port: 7892
port: 7890
socks-port: 7891
ipv6: false
mode: rule
log-level: silent
external-controller: 0.0.0.0:9090
secret: "123456"
allow-lan: true
bind-address: "*"
external-ui: "/usr/share/openclash/dashboard"
hosts:
##Custom HOSTS##
#  experimental hosts, support wildcard (e.g. *.clash.dev Even *.foo.*.example.com)
#  static domain has a higher priority than wildcard domain (foo.example.com > *.example.com)
#  NOTE: hosts don't work with `fake-ip`

#  '*.clash.dev': 127.0.0.1
#  'alpha.clash.dev': '::1'
##Custom HOSTS END##
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 127.0.0.1:7874
  fake-ip-filter:
##Custom DNS##
  nameserver:
  - 114.114.114.114
#===================== OpenClash-General-Settings =====================#
proxies:

配置没问题，一样是0.39.8版本，我后面虚拟机出问题了重新安装了openclash同样的配置没问题了，应该是openclash客户端哪里出问题了帮不了作者检查问题了

**Comment by warcns** [comment]
我也发现同样的问题，用下面这段规则生成的配置文件，除了节点外，所有的rule都会被openclash删掉。
[ACL全分组.txt](https://github.com/vernesong/OpenClash/files/5161798/ACL.txt)

规则部分会被替换成这样：
# 规则
##Other-rule-providers-end##
rules:
##Others:🚀 节点选择
##Domestic:🚀 节点选择
##Proxy:🚀 节点选择
##AsianTV:🚀 节点选择
##GlobalTV:🚀 节点选择
##source:ConnersHua
  # Unbreak
- RULE-SET,Unbreak,DIRECT

  # Global Area Network

  # (Streaming Media)
- RULE-SET,Streaming,🚀 节点选择

  # (StreamingSE)
- RULE-SET,StreamingSE,🚀 节点选择

  # (DNS Cache Pollution) / (IP Blackhole) / (Region-Restricted Access Denied) / (Network Jitter)
- RULE-SET,Global,🚀 节点选择

  # China Area Network
- RULE-SET,China,🚀 节点选择

  # Local Area Network
- IP-CIDR,192.168.0.0/16,DIRECT
- IP-CIDR,10.0.0.0/8,DIRECT
- IP-CIDR,172.16.0.0/12,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- IP-CIDR,100.64.0.0/10,DIRECT
- IP-CIDR,224.0.0.0/4,DIRECT

  # （可选）使用来自 ipipdotnet 的 ChinaIP 以解决数据不准确的问题，使用 ChinaIP.yaml 时可禁用下列直至（包括）「GEOIP,CN」规则
- RULE-SET,ChinaIP,🚀 节点选择
  # Tencent
- IP-CIDR,119.28.28.28/32,DIRECT
- IP-CIDR,182.254.116.0/24,DIRECT
  # GeoIP China
  #- GEOIP,CN,🚀 节点选择

- IP-CIDR,198.18.0.1/16,REJECT,no-resolve
- MATCH,🚀 节点选择

**Comment by vernesong** [comment]
你开了第三方规则啊老哥

**Comment by warcns** [comment]
> 你开了第三方规则啊老哥

我之前一直订阅的这个规则，一直很正常，昨晚开始出问题的。后来才发现配置的rule被改写了

**Comment by warcns** [comment]
我去试试关掉第三方规则，但我现在用另外一个配置文件，就没有被改写啊

**Comment by warcns** [comment]
……关掉第三方规则就好了，是我智障了，不过我以前应该一直都开着第三方规则的

**Comment by miaoermua** [comment]
> ……关掉第三方规则就好了，是我智障了，不过我以前应该一直都开着第三方规则的

关掉他的自动更新？还是不使用第三方规则。。。这样的话只能自己写了

**Comment by warcns** [comment]
> > ……关掉第三方规则就好了，是我智障了，不过我以前应该一直都开着第三方规则的
> 
> 
> 
> 关掉他的自动更新？还是不使用第三方规则。。。这样的话只能自己写了

![image](https://user-images.githubusercontent.com/56870885/92011622-eceef680-ed7d-11ea-8eff-1854da509456.jpeg)这样就行了
