### ISSUE TITLE
节点丢失

### ISSUE THREAD

**Issue by tengyuankoo** [vernesong/OpenClash#706]
前2次的commits后更新订阅会丢失7个节点，订阅链接是从ACL4SSR转换的，链接配置内容没有问题，CFW能正常更新订阅，不丢失节点

日志：
time="2020-08-31T07:05:30Z" level=fatal msg="Parse config error: ProxyGroup[0]: '🇭🇰 香港' not found"
2020-08-31 15:05:24 OpenClash Can Not Start, Please Check The Error Info And Try Again

**Comment by tengyuankoo** [comment]
有没有和我一样的

**Comment by aguero119** [comment]
我是重启openclash后,节点配置会被重置,不知道为什么.之前的版本就不会.会倒回配置.

**Comment by tengyuankoo** [comment]
> 测试一下新版本

修复了。
