### ISSUE TITLE
Openclash 守护程序未运行

### ISSUE THREAD

**Issue by smallst** [vernesong/OpenClash#707]
![image](https://user-images.githubusercontent.com/11417632/91814205-5c71c280-ec66-11ea-8ff1-3d83440420fa.png)
这个问题在https://github.com/vernesong/OpenClash/issues/588 和 https://github.com/vernesong/OpenClash/issues/21 上均有提到，但两个 issue 似乎都没有提出解决方案。故打开一个新 issue

首先我使用的内核与 https://github.com/vernesong/OpenClash/issues/21 一样是 armv7, 但我并不是特别确定我是不是应该用 armv7，因此贴上处理器型号求确认。如果是因为内核版本选择错误那可能这个问题本不该存在。
![image](https://user-images.githubusercontent.com/11417632/91814380-9fcc3100-ec66-11ea-99f8-43af5850c2ea.png)

而目前出现的问题除了网页端无法检测到 watchdog 进程，同时路由器上也存在多个 watchdog。已确认停止 Openclash 不会停止 watchdog 进程，因此但凡 “关闭 openclash， 启动openclash” 或者 “应用配置” 即会产生一个新的 watchdog。 不保证仅有上述操作会增加 watchdog 进程。

同时，在路由器重启后只有一个 watchdog 进程时，网页ui上守护程序依然会显示为 “未运行”

-----------------------------以上为 bug 正文，以下为不确定猜想
根据 https://github.com/vernesong/OpenClash/issues/588 中提到多个 watchdog 进程可能导致 dhcp/dns 异常，合理怀疑该问题与我之前遇到的 ios 设备国内资源打不开https://github.com/vernesong/OpenClash/issues/695 有一定关联，目前正在确认中。（目前通过在 watchdog.sh 脚本开头添加
```bash
WATCHDOG_NUM=$(ps|grep -c {openclash_watch})
echo "$WATCHDOG_NUM"
if [ "$WATCHDOG_NUM" -ge 4 ]; then
    exit 0
fi
```
来阻止 watchdog 多开，但不确定这么做是否会产生其他不确定的问题（比如 openclash 重启后 watchdog 是否需要同步重启？旧的watchdog是否能对新的 openclash 进程正确守护）

**Comment by smallst** [comment]
@vernesong 直接运行 `ps |grep openclash_watchdog.sh |grep -v grep` 有输出，重定向到 `/dev/null` 我的理解是不影响脚本里的逻辑结果的，但页面是未运行。

直接运行 
```bash
watchdog_pids=$(ps |grep openclash_watchdog.sh |grep -v grep |awk '{print $1}' 2>/dev/null)
   for watchdog_pid in $watchdog_pids; do
      kill -9 "$watchdog_pid" >/dev/null 2>&1
   done
``` 可以正常退出 watchdog

**Comment by vernesong** [comment]
固件的问题

**Comment by smallst** [comment]
这样啊……看来我还是这个路由器买的不好 😢 下次还是要换 openwrt 官方支持的硬件

**Comment by planktonzp** [comment]
> 固件的问题

如果是固件的问题的话 应当贴出您变异的版本吧 好像很多的issue在最新版本中也遇到了问题 
反馈一下: 
x86_64 OpenWrt SNAPSHOT r13831-52cdd6185e / LuCI Master git-20.172.67167-b397549
不知道您说的这个问题在哪个固件上没有 我去编译试验一下

**Comment by vernesong** [comment]
参考717，看看最新版什么情况

**Comment by smallst** [comment]
@planktonzp 我在 https://github.com/vernesong/OpenClash/issues/717 上提了建议，现在应该修复了

**Comment by hcym** [comment]
显示未运行，上网正常，看看明天再说，我觉得无所谓了😂

**Comment by smallst** [comment]
@hcym 如果会上ssh试试 `ps |grep openclash_watchdog.sh |grep -v grep ` 和 `ps -ef |grep openclash_watchdog.sh |grep -v grep ` 这两条命令都有什么结果
