### ISSUE TITLE
自定义hosts未生效

### ISSUE THREAD

**Issue by xiao0yy** [vernesong/OpenClash#709]
配置了几个自定义hosts，使用路由器dns无法解析出ip，使用openclash的7874是可以解析到的，这种情况感觉像是劫持失败。

但配置的所有规则经过测试，都生效了。这种情况应该从哪里排查呢。

**Comment by vernesong** [comment]
![image](https://user-images.githubusercontent.com/42875168/91934138-23485980-ed1d-11ea-92eb-356959583b14.png)

**Comment by xiao0yy** [comment]
@vernesong 是指use-hosts选项么，我已经在dns配置中添加了，但好像没有效果。

**Comment by vernesong** [comment]
那就是你host没写对，注意通配符

**Comment by xiao0yy** [comment]
配置文件是这样的：

```yaml
...
hosts:
  'somedomain': 192.168.11.11
dns:
  listen: 127.0.0.1:7874
...
```

然后测试：

```
# nslookup somedomain
Server:         127.0.0.1
Address:        127.0.0.1#53

*** Can't find somedomain: No answer
*** Can't find somedomain: No answer

# nslookup somedomain 127.0.0.1#7874
Server:         127.0.0.1
Address:        127.0.0.1#7874

Name:      somedomain
Address 1: 192.168.11.11
Address 2: ::ffff:192.168.11.11
```

**Comment by RainThinks** [comment]
我和你遇到一样的问题，请问最后解决了吗？

**Comment by RainThinks** [comment]
我又测试了下，hosts 中的 IP 是外网的都没问题，如果是指向内网，例如192.168.10.1，53端口就不解析。

**Comment by UchihaYuki** [comment]
你们可以参考我提的这个问题，关了重绑定保护就好了
https://github.com/vernesong/OpenClash/issues/2179
