### ISSUE TITLE
在openclash运行时，防火墙转发的新设置无效，主机映射也无效

### ISSUE THREAD

**Issue by riverscn** [vernesong/OpenClash#71]
openwrt 19.07-rc1
复现方法：
1. 保持openclash运行
2. 添加防火墙新转发
3. 添加主机映射
测试转发地址和映射ip，均没有正常生效

**Comment by vernesong** [comment]
https://github.com/vernesong/OpenClash/issues/63

**Comment by tete1030** [comment]
我的openwrt版本是 coolsnowwolf/lede@2365f15 ，没有此问题（未测试主机映射）
在luci防火墙“端口转发”界面设置后会自动在zone_wan_prerouting添加规则，不会出现我在 #63 中描述的开放端口存在的问题，@riverscn 看一下你的防火墙设置和状态？

## Luci设置
![image](https://user-images.githubusercontent.com/4312115/69493335-b9c33100-0ee8-11ea-9804-5cb42991fa2b.png)

## 防火墙状态
![image](https://user-images.githubusercontent.com/4312115/69493347-d2cbe200-0ee8-11ea-94bd-7135d46f06c9.png)

![image](https://user-images.githubusercontent.com/4312115/69493352-e4ad8500-0ee8-11ea-8985-c04da7c9a138.png)
