### ISSUE TITLE
Auto - UrlTest模式容易断连——此站点的连接不安全 www.google.com 发送了无效的响应。

### ISSUE THREAD

**Issue by xhrzg2017** [vernesong/OpenClash#710]
此站点的连接不安全
www.google.com 发送了无效的响应。
openclash怎么减少自动切换两个节点更换时间
clash容易发生断连，passwall负载均衡都不会。
clash测速时连接选择节点，得到测速结果连接自动节点断开选择节点进入自动模式，下次测速以此类推

**Comment by onepig22** [comment]
我也经常遇到这个问题 不知道怎么解决

**Comment by adamw92** [comment]
看你urltest组设置的测试间隔

**Comment by xhrzg2017** [comment]
> 看你urltest组设置的测试间隔吧

怎样设置openclash的这个选项
