### ISSUE TITLE
电脑访问网站cdn分配IP分流问题

### ISSUE THREAD

**Issue by xsy2004** [vernesong/OpenClash#711]
电脑使用网线连接斐讯k3硬路由，硬路由再由软路由分配ip访问，软路由连接光猫桥接模式上网，软路由拨号。
手机使用wifi连接斐讯k3，其他同上。
但是我看电脑访问网站，在openclash的连接统计中全部是ip，但是手机通过wifi访问却是域名。
这样会导致一种情况，电脑端访问到路由器为ip无法分流，因为这个ip是经过了各大网站cdn分配出来的国外地址，直接被判断为国外ip而被代理。
![wiEJbD.png](https://s1.ax1x.com/2020/09/03/wiEJbD.png)
而手机访问网站在openclash连接统计中为域名，通过路由器去对域名请求判断，从而达到分流效果。
目前我的解决方案是让路由器走socks5连接openclash，这样在连接统计处为域名，则可以进行分流。
![wiEsr8.png](https://s1.ax1x.com/2020/09/03/wiEsr8.png)

想问下有什么特别好的解决方法吗，浏览器为chrome。

**Comment by Rakau** [comment]
这个问题我也遇到了，感觉是DNS的问题，但是又找不到动手的路子

**Comment by xsy2004** [comment]
> 这个问题我也遇到了，感觉是DNS的问题，但是又找不到动手的路子

就只能拿浏览器代理了

**Comment by vernesong** [comment]
因为已经拿到IP地址了，所以可以排查下电脑的DNS设置是不是设置成了路由地址，或者路由上还有其他DNS插件在运行，因为你手机端正常，所以重点看看电脑端的设置。

**Comment by xsy2004** [comment]
> 因为已经拿到IP地址了，所以可以排查下电脑的DNS设置是不是设置成了路由地址，或者路由上还有其他DNS插件在运行，因为你手机端正常，所以重点看看电脑端的设置。

好的，谢谢

**Comment by Rakau** [comment]
楼上开发大大说的对

**Comment by vernesong** [comment]
返回fakeip了怎么控制面板还都是ip的连接，不正常也应该全是fakeip的连接。
你的电脑软件不用查询DNS的吗？nslookup响应的服务器地址是不是插件的路由地址？
最好多测试几次，顺便清理一下DNS缓存

**Comment by Rakau** [comment]
你软路由和K3分别是什么方式上网的?最好说一下
