### ISSUE TITLE
自动更新订阅无效

### ISSUE THREAD

**Issue by evangelion015** [vernesong/OpenClash#712]
设置循环，预约，到时间了都不会自动更新，只能在订阅页面点应用配置进行手动更新
L大openwrt源码，树莓派4B，内核4.19.123，日志里也没有订阅有关的信息

**Comment by vernesong** [comment]
一个是看你固件的cron是否正常，在一个你单独运行/usr/share/openclash/openclash.sh看看预约功能是否正常

**Comment by evangelion015** [comment]
单独运行脚本，日志里只有一行
2020-09-06 00:19:13 Updated Config【Trojan】 No Change, Do Nothing

**Comment by vernesong** [comment]
这不是没问题吗。配置文件没有更新，所有不继续其他步骤

**Comment by qq253044370** [comment]
问题解决了吗？我这一样的问题。只能手动更新。
