### ISSUE TITLE
请问openclash会支持trojan go吗？

### ISSUE THREAD

**Issue by michaelchen644** [vernesong/OpenClash#715]
下次一定请你喝茶

**Comment by pfangzhi** [comment]
当然支持，配件文件写上就行了。

**Comment by sxml** [comment]
> 当然支持，配件文件写上就行了。

配置文件 请教怎么写 Trojan-go

**Comment by pfangzhi** [comment]
# Trojan
  - name: "SG"
    type: trojan
    server: server
    port: 443
    password: yourpsk
    # udp: true
    # sni: example.com # aka server name
    # alpn:
    #   - h2
    #   - http/1.1
    # skip-cert-verify: true

**Comment by pfangzhi** [comment]
https://github.com/ConnersHua/Profiles/blob/master/Clash/Global.yaml

**Comment by hcym** [comment]
几乎全世界的协议都支持，就是没有mkcp，呵呵😄
