### ISSUE TITLE
外部控制面板，一直弹出怎么解决

### ISSUE THREAD

**Issue by hkq3323** [vernesong/OpenClash#716]
外部控制面板，点进去就一直弹出来，关都关不掉
![QQ截图20200908013004](https://user-images.githubusercontent.com/48866478/92409391-07a4df00-f173-11ea-81bf-6405fb8e9c60.jpg)

**Comment by xhrzg2017** [comment]
> 外部控制面板，点进去就一直弹出来，关都关不掉
> ![QQ截图20200908013004](https://user-images.githubusercontent.com/48866478/92409391-07a4df00-f173-11ea-81bf-6405fb8e9c60.jpg)

那就填192.168.x.x，软路由ip
