### ISSUE TITLE
support full version of ps

### ISSUE THREAD

**Issue by smallst** [vernesong/OpenClash#717]
actually i want to create a pr for this, but i'm not familiar with luci-app develop. so i will post my opinion to support the procps-ng ps.

the key problem now for watchdog not running and cannot be killed is some openwrt has procps-ng version of ps command. mentioned in https://github.com/vernesong/OpenClash/issues/588. so they need use `ps -ef` and the pid of output is `$2`.  i think following code will help  that:
```bash
function unify_ps() {
  if [ $(ps --version|grep -c procps-ng) -eq 1 ];
  then
    ps -ef|cut -d ' ' -f 2-
  else
    ps
  fi
}
```

then if we replace the `ps` command with `unify_ps`, i think both version of ps can work normally to check watchdog and kill watchdog.

the key problem i met is how to define this function to all of scripts(.lua, .sh) in luci-app. the force way to do that is define the function in each scripts. i think is not a good idea. maybe you know how to achive that.

**Comment by vernesong** [comment]
Can I just use  ```ps -ef``` only?

**Comment by smallst** [comment]
@vernesong  `$1` of `ps -ef` returns the `UID` instead of `PID`, so just using `ps -ef` would break the `kill_watchdog` logic which needs the `PID` to kill process. so i use a  `cut` to cut the first column of `ps -ef` output.

**Comment by vernesong** [comment]
verify the latest commit

**Comment by smallst** [comment]
@vernesong oh, i think maybe i didn't express myself clearly. but the ps from busybox cannot accept the `-ef` option:
![image](https://user-images.githubusercontent.com/11417632/92572294-d03f4b00-f2b6-11ea-8ca7-1664695678ca.png)
that's why i use a `unify_ps` function to handle different `ps`

**Comment by vernesong** [comment]
maybe use the ps without -ef is simply.
So, I should try to verify the ps version first

**Comment by smallst** [comment]
@vernesong  yeah , with busybox-ps only `ps` is fine. but for procps-ng need the `ps -ef` . don't know why procps-ng's ps don't show all process... 

and busybox-ps is default for openwrt, while many distribution replace it with procps-ng, which is default for linux. what a pity
