### ISSUE TITLE
为什么用了openclash后打开twitter和youtube时经常会出现封面刷不出来的情况？

### ISSUE THREAD

**Issue by ininolee** [vernesong/OpenClash#719]
为什么用了openclash后打开twitter和youtube时经常会出现封面或者图片刷不出来的情况？

**Comment by hkq3323** [comment]
同求，我也是，油管的视频经常在转圈就是没图像

**Comment by vernesong** [comment]
频繁urltest切换节点的缘故吧，可以把策略组的检查时间适当延长

**Comment by ininolee** [comment]
> 频繁urltest切换节点的缘故吧，可以把策略组的检查时间适当延长

我是用的一个节点

**Comment by hkq3323** [comment]
> > 频繁urltest切换节点的缘故吧，可以把策略组的检查时间适当延长Due to the frequent urltest node switching, the policy group checking time can be extended appropriately
> 
> 我是用的一个节点
> 
> I’m using a node

我也没找到策略组的时间修改在哪里，刚才又重新用起了列表的第一个clash，没别的需求目前没其他问题，建议楼主也试下

**Comment by vernesong** [comment]
用fakeip呢

**Comment by ininolee** [comment]
> 用fakeip呢

几个模式都试过了，一个情况，但是用passwall就没这个问题

**Comment by ininolee** [comment]
> 又重新用起了列表的第一个clash

请问“又重新用起了列表的第一个clash”是啥意思

**Comment by hkq3323** [comment]
> > 又重新用起了列表的第一个clashOnce again, the first clash of the list is used
> 
> 请问“又重新用起了列表的第一个clash”是啥意思
> 
> What do you mean, “reactivated the first clash on the list”

你刷的是esir的openwrt吗，服务里面有2个clash，不过都不好用，360浏览器打不开youtube，谷歌的浏览器可以，还是换回了ssr+

**Comment by vernesong** [comment]
关ipv6了没

**Comment by ininolee** [comment]
> 关ipv6了没

openclash里面找不到ipv6的设置

**Comment by ininolee** [comment]
> 同求，我也是，油管的视频经常在转圈就是没图像

请问你找到原因了吗？

**Comment by ininolee** [comment]
> 关ipv6了没

已全部禁用，依旧不行

**Comment by blip** [comment]
我用ssr连接方式会出现这个问题，用trojan就不会。应该是clash ssr实现的断流问题:
https://github.com/Dreamacro/clash/issues/995

**Comment by xiyouxu** [comment]
我出现同样的情况，我即使关掉了op上的clash，在电脑端开v2ray的客户端也不行，后来我重启了我的整个路由器，就马上可以上推特了。我估计是DNS的问题，也没有深究。
