### ISSUE TITLE
使用大概10分钟左右断流

### ISSUE THREAD

**Issue by jindx0713** [vernesong/OpenClash#72]
不知道是不是clash内核的问题。
我和另外一个兄弟，都是lede安装openclash和koolclash
youtube10分钟左右，网络就断了。
两个不同型号软路由。防火墙规则也不同。

**Comment by vernesong** [comment]
先排除服务器的原因，策略组改成手动选择服务器测试，不要用urltest

**Comment by jindx0713** [comment]
已解决

**Comment by shuo4sell** [comment]
> 已解决

你好，请问怎么解决的？我情况一模一样，看着时间，每十分钟必断流。
如果我固定本机dns到运营商，OpenClash功能无效，不能上google。
如果我选自动获取，功能有效，但10分钟会断流一次。
