### ISSUE TITLE
youtube测试速度，但是clash的面板不显示实时速度

### ISSUE THREAD

**Issue by hkq3323** [vernesong/OpenClash#720]
如题
![photo_2020-09-08_21-06-51](https://user-images.githubusercontent.com/48866478/92480445-7d628680-f217-11ea-9e88-2017582c43bb.jpg)
![photo_2020-09-08_21-06-55](https://user-images.githubusercontent.com/48866478/92480450-7e93b380-f217-11ea-8ac7-6dbaf879b0f0.jpg)

**Comment by vernesong** [comment]
？？ 你network activity是0的时候要它显示什么速度
