### ISSUE TITLE
如何实现负载均衡

### ISSUE THREAD

**Issue by xzhqhfe** [vernesong/OpenClash#721]
如何实现负载均衡

**Comment by xhrzg2017** [comment]
Proxy选Auto - UrlTest

**Comment by xhrzg2017** [comment]
> 如何实现负载均衡

Proxy选Auto - UrlTest

**Comment by hcym** [comment]
不是这个东西，应该是类似haproxy的，选项是balance，没敢用

**Comment by adamw92** [comment]
load-balance，关于它的更多技术细节你可以看clash的文档
