### ISSUE TITLE
openclash无法下载google商店软件

### ISSUE THREAD

**Issue by wuchen4588** [vernesong/OpenClash#722]
120.52.14.3:80
877 B
645 B
0 B/s
0 B/s
🎯 全球直连 / DIRECT
GeoIP
8 minutes
192.168.50.247:42346
120.52.14.3
Redir(tcp)
183.3.234.102:443
14 KB
3.96 KB
0 B/s
0 B/s
🎯 全球直连 / DIRECT
GeoIP
15 minutes
192.168.50.247:57112
183.3.234.102
Redir(tcp)
42.121.13.244:4008
720 B
760 B
0 B/s
0 B/s
🎯 全球直连 / DIRECT
GeoIP
15 minutes
192.168.50.247:14009
42.121.13.244
TUN(udp)
157.240.199.17:443
1.29 KB
1.45 KB
0 B/s
0 B/s
🐟 漏网之鱼 / 🇺🇲 美国节点 / [SS] 🇺🇸 中继 美国 B1 [1x | GD-Linode]
Match
1 minute
192.168.50.247:51280
157.240.199.17
Redir(tcp)
alive.github.com:443
4.27 KB
1.63 KB
0 B/s
0 B/s
🚀 节点选择 / 🇭🇰 香港节点 / [SSR] 🇭🇰 中继 香港 B3 [1x | GD-AZ]
DomainKeyword
1 minute
192.168.50.134:22448
140.82.114.26
Redir(tcp)
connectivitycheck.gstatic.com:443
10.1 KB
8.14 KB
0 B/s
0 B/s
🚀 节点选择 / 🇭🇰 香港节点 / [SSR] 🇭🇰 中继 香港 B3 [1x | GD-AZ]
DomainSuffix
6 minutes
192.168.50.247:52222
203.208.50.66
Redir(tcp)
183.3.224.146:8080
573 B
1.07 KB
0 B/s
0 B/s
🎯 全球直连 / DIRECT
GeoIP
7 minutes
192.168.50.247:54082
183.3.224.146
Redir(tcp)
183.57.48.48:7512
18 B
81 B
0 B/s
0 B/s
🎯 全球直连 / DIRECT
GeoIP
3 minutes
192.168.50.247:42841
183.57.48.48
Redir(tcp)
edge-mqtt.facebook.com:443
3.38 KB
1.07 KB
0 B/s
0 B/s
🚀 节点选择 / 🇭🇰 香港节点 / [SSR] 🇭🇰 中继 香港 B3 [1x | GD-AZ]
DomainKeyword
1 minute
192.168.50.247:51722
69.171.250.20
Redir(tcp)
58.49.224.167:80
0 B
684 B
0 B/s
684 B/s
🎯 全球直连 / DIRECT
GeoIP
1 minute
192.168.50.247:52426
58.49.224.167
Redir(tcp)
58.49.224.167:80
0 B
682 B
0 B/s
682 B/s
🎯 全球直连 / DIRECT
GeoIP
1 minute
192.168.50.247:52424
58.49.224.167
Redir(tcp)
ws.infinitynewtab.com:443
4.05 KB
1.38 KB
0 B/s
0 B/s
🎯 全球直连 / DIRECT
GeoIP
less than a minute
192.168.50.134:22415
118.178.135.232
Redir(tcp)
www.googleapis.com:443
2.34 KB
1.04 KB
0 B/s
0 B/s
🚀 节点选择 / 🇭🇰 香港节点 / [SSR] 🇭🇰 中继 香港 B3 [1x | GD-AZ]
DomainKeyword
less than a minute
192.168.50.247:54690
172.217.160.106
Redir(tcp)
101.91.5.194:443
183 B
364 B
0 B/s
0 B/s
🎯 全球直连 / DIRECT
GeoIP
less than a minute
192.168.50.247:40684
101.91.5.194
Redir(tcp)
113.96.208.217:443
7.12 KB
15.8 KB
0 B/s
0 B/s
🎯 全球直连 / DIRECT
GeoIP
14 minutes
192.168.50.247:41820
113.96.208.217
Redir(tcp)
114.221.148.192:8080
169 KB
56.6 KB
0 B/s
0 B/s
🎯 全球直连 / DIRECT
GeoIP
12 minutes
192.168.50.247:39972
114.221.148.192
Redir(tcp)
211.144.31.47:443
3.41 KB
673 B
0 B/s
0 B/s
🎯 全球直连 / DIRECT
GeoIP
15 minutes
192.168.50.247:45518
211.144.31.47
Redir(tcp)
212.129.220.124:443
516 B
1.15 KB
0 B/s
0 B/s
🎯 全球直连 / DIRECT
IPCIDR
4 minutes
192.168.50.247:46280
212.129.220.124
Redir(tcp)
android.clients.google.com:443
355 KB
16.1 KB
0 B/s
0 B/s
🚀 节点选择 / 🇭🇰 香港节点 / [SSR] 🇭🇰 中继 香港 B3 [1x | GD-AZ]
DomainKeyword
6 minutes
192.168.50.247:46648
172.217.31.174
Redir(tcp)
58.51.135.221:80
41.8 MB
17.5 KB
0 B/s
0 B/s
🎯 全球直连 / DIRECT
GeoIP
1 minute
192.168.50.247:57652
58.51.135.221
Redir(tcp)
114.221.144.33:8080
95.5 KB
36.2 KB
0 B/s
1.18 KB/s
🎯 全球直连 / DIRECT
GeoIP
10 minutes
192.168.50.247:42690
114.221.144.33
Redir(tcp)
1.192.193.45:80
376 B
634 B
0 B/s
0 B/s
🎯 全球直连 / DIRECT
GeoIP
11 minutes
192.168.50.134:3541
1.192.193.45
Redir(tcp)
www.googleapis.com:443
2.34 KB
1.04 KB
0 B/s
0 B/s
🚀 节点选择 / 🇭🇰 香港节点 / [SSR] 🇭🇰 中继 香港 B3 [1x | GD-AZ]
DomainKeyword
less than a minute
192.168.50.247:54686
172.217.160.106
Redir(tcp)
118.178.135.232:443
1.74 KB
2.56 KB
0 B/s
0 B/s
🎯 全球直连 / DIRECT
GeoIP
15 minutes
192.168.50.134:3323
118.178.135.232
Redir(tcp)
client.wns.windows.com:443
4.93 KB
2.53 KB
0 B/s
0 B/s
🐟 漏网之鱼 / 🇺🇲 美国节点 / [SS] 🇺🇸 中继 美国 B1 [1x | GD-Linode]
Match
1 minute
192.168.50.134:22446
52.139.250.253
Redir(tcp)
113.96.208.217:443
7.26 KB
14.9 KB
0 B/s
0 B/s
🎯 全球直连 / DIRECT
GeoIP
14 minutes
192.168.50.247:38849
113.96.208.217
Redir(tcp)
www.google.com:443
3.81 KB
468 B
0 B/s
0 B/s
🚀 节点选择 / 🇭🇰 香港节点 / [SSR] 🇭🇰 中继 香港 B3 [1x | GD-AZ]
DomainKeyword
less than a minute
192.168.50.247:41094
108.160.166.137
Redir(tcp)
108.177.97.188:5228
850 B
977 B
0 B/s
0 B/s
🐟 漏网之鱼 / 🇺🇲 美国节点 / [SS] 🇺🇸 中继 美国 B1 [1x | GD-Linode]
Match
less than a minute
192.168.50.247:46700
108.177.97.188
Redir(tcp)
123.56.81.41:9990
99 B
448 B
0 B/s
0 B/s
🎯 全球直连 / DIRECT
GeoIP
14 minutes
192.168.50.247:58971
123.56.81.41
Redir(tcp)
101.89.15.106:443
2.42 KB
1.14 KB
0 B/s
0 B/s
🎯 全球直连 / DIRECT
GeoIP
15 minutes
192.168.50.247:44400
101.89.15.106

**Comment by wuchen4588** [comment]
各位大佬看看什么情况，这个是节点分流所有状态

**Comment by vernesong** [comment]
geoip不准吧，下个版本我换一个带ipip的

**Comment by ForestL18** [comment]
0.40.2最新版，fake-ip模式，谷歌商店无法下载，一直显示等待下载，更换节点也是如此。GEOIP已更新。

**Comment by Nepmonts** [comment]
> 0.40.2最新版，fake-ip模式，谷歌商店无法下载，一直显示等待下载，更换节点也是如此。GEOIP已更新。

应该是你本地设备或其他原因，我这别同版本插件测试正常。

**Comment by ForestL18** [comment]
好像是规则的原因，换了个规则又可以了

**Comment by JunTsao** [comment]
> 好像是规则的原因，换了个规则又可以了

你好，请问你在用哪个规则？我的play也是有点问题。。。

**Comment by ForestL18** [comment]
我用的机场规则转换器

**Comment by JunTsao** [comment]
> 我用的机场规则转换器

感谢！ACL4SSR总觉得有点问题

**Comment by ForestL18** [comment]
多次试验和多天使用后确定，fake-IP模式非常容易出现无法下载google play商店的应用，有时换规则有用，有时不行。而redirect-hos模式不易出现这种问题。
这是系统日志，大家可以排查一下
Tue Sep 22 06:52:28 2020 daemon.info watchcat[3570]: no internet connectivity for 5400 seconds. Reseting when reaching 21600
Tue Sep 22 06:52:28 2020 authpriv.notice beardropper[3585]: loadState() loaded 0 entries
Tue Sep 22 06:59:52 2020 cron.err crond[32735]: crond (busybox 1.31.1) started, log level 8
Tue Sep 22 07:00:02 2020 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Tue Sep 22 07:00:02 2020 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Tue Sep 22 07:00:02 2020 daemon.info dnsmasq[741]: Connected to system UBus
Tue Sep 22 07:00:02 2020 cron.err crond[782]: crond (busybox 1.31.1) started, log level 8
Tue Sep 22 07:00:21 2020 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Tue Sep 22 07:00:21 2020 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Tue Sep 22 07:00:21 2020 daemon.info dnsmasq[1619]: Connected to system UBus
Tue Sep 22 07:06:57 2020 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Tue Sep 22 07:06:57 2020 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Tue Sep 22 07:06:57 2020 daemon.info dnsmasq[6541]: Connected to system UBus
Tue Sep 22 07:06:58 2020 cron.err crond[6583]: crond (busybox 1.31.1) started, log level 8
Tue Sep 22 07:07:14 2020 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Tue Sep 22 07:07:14 2020 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Tue Sep 22 07:07:14 2020 daemon.info dnsmasq[7350]: Connected to system UBus
Tue Sep 22 07:07:45 2020 cron.err crond[8269]: crond (busybox 1.31.1) started, log level 8
Tue Sep 22 07:07:53 2020 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Tue Sep 22 07:07:53 2020 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Tue Sep 22 07:07:53 2020 daemon.info dnsmasq[8720]: Connected to system UBus
Tue Sep 22 07:07:53 2020 cron.err crond[8762]: crond (busybox 1.31.1) started, log level 8
Tue Sep 22 07:08:04 2020 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Tue Sep 22 07:08:04 2020 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Tue Sep 22 07:08:04 2020 daemon.info dnsmasq[9455]: Connected to system UBus
Tue Sep 22 07:10:28 2020 daemon.info watchcat[3570]: no internet connectivity for 6480 seconds. Reseting when reaching 21600
Tue Sep 22 07:10:43 2020 daemon.err nlbwmon[16336]: Netlink receive failure: Out of memory
Tue Sep 22 07:10:43 2020 daemon.err nlbwmon[16336]: Unable to dump conntrack: No buffer space available

**Comment by suyar** [comment]
我通过以下办法解决了：
机型：小米系列
设置->应用管理->搜索下载管理程序->如果没有找到，则点击开启显示所有应用->下载管理程序->清除全部数据

**Comment by iostreamx** [comment]
@vernesong OpenClash 版本[v0.45.51-beta] 内核版本 v1.11.4-13-g6e058f8 使用 Redir-Host 兼容模式依旧无法在 Play 商店下载软件.
测试下载 PUBG Mobile
我使用 Surfboard 正常：
![1661925913613](https://user-images.githubusercontent.com/63491179/187605710-6fc03eb5-26ee-418a-a75a-4203aa289cfc.jpg)
OpenClash 连接：
![openclash](https://user-images.githubusercontent.com/63491179/187606323-8b8f9411-4478-4fd1-9cea-b6d2faa3fd94.png)
谢谢。

**Comment by jy125131** [comment]
> 多次试验和多天使用后确定，fake-IP模式非常容易出现无法下载google play商店的应用，有时换规则有用，有时不行。而redirect-hos模式不易出现这种问题。 这是系统日志，大家可以排查一下 Tue Sep 22 06:52:28 2020 daemon.info watchcat[3570]: no internet connectivity for 5400 seconds. Reseting when reaching 21600 Tue Sep 22 06:52:28 2020 authpriv.notice beardropper[3585]: loadState() loaded 0 entries Tue Sep 22 06:59:52 2020 cron.err crond[32735]: crond (busybox 1.31.1) started, log level 8 Tue Sep 22 07:00:02 2020 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses! Tue Sep 22 07:00:02 2020 user.notice dnsmasq: Allowing 127.0.0.0/8 responses Tue Sep 22 07:00:02 2020 daemon.info dnsmasq[741]: Connected to system UBus Tue Sep 22 07:00:02 2020 cron.err crond[782]: crond (busybox 1.31.1) started, log level 8 Tue Sep 22 07:00:21 2020 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses! Tue Sep 22 07:00:21 2020 user.notice dnsmasq: Allowing 127.0.0.0/8 responses Tue Sep 22 07:00:21 2020 daemon.info dnsmasq[1619]: Connected to system UBus Tue Sep 22 07:06:57 2020 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses! Tue Sep 22 07:06:57 2020 user.notice dnsmasq: Allowing 127.0.0.0/8 responses Tue Sep 22 07:06:57 2020 daemon.info dnsmasq[6541]: Connected to system UBus Tue Sep 22 07:06:58 2020 cron.err crond[6583]: crond (busybox 1.31.1) started, log level 8 Tue Sep 22 07:07:14 2020 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses! Tue Sep 22 07:07:14 2020 user.notice dnsmasq: Allowing 127.0.0.0/8 responses Tue Sep 22 07:07:14 2020 daemon.info dnsmasq[7350]: Connected to system UBus Tue Sep 22 07:07:45 2020 cron.err crond[8269]: crond (busybox 1.31.1) started, log level 8 Tue Sep 22 07:07:53 2020 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses! Tue Sep 22 07:07:53 2020 user.notice dnsmasq: Allowing 127.0.0.0/8 responses Tue Sep 22 07:07:53 2020 daemon.info dnsmasq[8720]: Connected to system UBus Tue Sep 22 07:07:53 2020 cron.err crond[8762]: crond (busybox 1.31.1) started, log level 8 Tue Sep 22 07:08:04 2020 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses! Tue Sep 22 07:08:04 2020 user.notice dnsmasq: Allowing 127.0.0.0/8 responses Tue Sep 22 07:08:04 2020 daemon.info dnsmasq[9455]: Connected to system UBus Tue Sep 22 07:10:28 2020 daemon.info watchcat[3570]: no internet connectivity for 6480 seconds. Reseting when reaching 21600 Tue Sep 22 07:10:43 2020 daemon.err nlbwmon[16336]: Netlink receive failure: Out of memory Tue Sep 22 07:10:43 2020 daemon.err nlbwmon[16336]: Unable to dump conntrack: No buffer space available

果然如此，时隔3年 问题依旧，不知道有没有新的解决办法了
