### ISSUE TITLE
OpenClash 守护程序显示“未运行”

### ISSUE THREAD

**Issue by openips** [vernesong/OpenClash#726]
用的代码为Commits on Sep 9, 2020版本
之前的版本一切正常
![image](https://user-images.githubusercontent.com/47168453/92610443-46a97080-f2ea-11ea-874a-9d7844254ca5.png)

OpenClash 调试日志

生成时间: 2020-09-09 22:15:26
插件版本: v0.39.8-beta

#===================== 系统信息 =====================#
主机型号: QEMU Standard PC (i440FX + PIIX, 1996)
固件版本: OpenWrt SNAPSHOT r14430-2dda301d40
LuCI版本: git-20.191.33648-4ddcb36
内核版本: 5.4.63
处理器架构: x86_64

#此项在使用Tun模式时应为ACCEPT
防火墙转发: ACCEPT

#此项有值时建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: 

#此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 127.0.0.1#7874

#===================== 依赖检查 =====================#
dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
jsonfilter: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
iptables-mod-tproxy: 已安装
kmod-tun(TUN模式): 已安装
luci-compat(Luci-19.07): 已安装

#===================== 内核检查 =====================#
运行状态: 运行中
已选择的架构: linux-amd64

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 2020.09.05.gaf1a58d
Tun内核文件: 存在
Tun内核运行权限: 正常

Game内核版本: v0.17.0-194-gbe86985
Game内核文件: 存在
Game内核运行权限: 正常

Dev内核版本: v1.1.0-13-g314ce1c
Dev内核文件: 存在
Dev内核运行权限: 正常

#===================== 插件设置 =====================#
当前配置文件: /etc/openclash/config/config-0909.yaml
运行模式: redir-host
默认代理模式: Rule
UDP流量转发: 停用
DNS劫持: 启用
自定义DNS: 启用
IPV6-DNS解析: 停用
禁用Dnsmasq缓存: 启用
自定义规则: 停用
仅允许内网: 停用
仅代理命中规则流量: 停用

#启动异常时建议关闭此项后重试
保留配置: 停用

#启动异常时建议关闭此项后重试
第三方规则: ConnersHua
第三方规则策略组设置:
GlobalTV: GlobalTV
AsianTV: AsianTV
Proxy: Proxy
Apple: Apple
Netflix: Netflix
Spotify: Spotify
Steam: Steam
AdBlock: AdBlock
Netease Music: Netease Music
Speedtest: Speedtest
Telegram: Telegram
Microsoft: Microsoft
PayPal: PayPal
Domestic: Domestic
Others: Others

读取的配置文件策略组:
Auto - UrlTest
Proxy
Domestic
Others
Apple
Microsoft
Netflix
Youtube
Spotify
Steam
AdBlock
AsianTV
GlobalTV
Speedtest
Telegram
PayPal
Netease Music
DIRECT
REJECT

#===================== 配置文件 =====================#
redir-port: 7892
port: 7890
socks-port: 7891
ipv6: false
mode: Rule
log-level: silent
external-controller: 0.0.0.0:9090
secret: "123456"
allow-lan: true
bind-address: "*"
external-ui: "/usr/share/openclash/dashboard"
hosts:
##Custom HOSTS##
#  experimental hosts, support wildcard (e.g. *.clash.dev Even *.foo.*.example.com)
#  static domain has a higher priority than wildcard domain (foo.example.com > *.example.com)
#  NOTE: hosts don't work with `fake-ip`

#  '*.clash.dev': 127.0.0.1
#  'alpha.clash.dev': '::1'
##Custom HOSTS END##
dns:
  use-hosts: true
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 127.0.0.1:7874
##Custom DNS##
  nameserver:
  - 127.0.0.1:7055
  fallback:
  - 127.0.0.1:7054
  fallback-filter:
    geoip: true
    ipcidr:
      - 0.0.0.0/8
      - 10.0.0.0/8
      - 100.64.0.0/10
      - 127.0.0.0/8
      - 169.254.0.0/16
      - 172.16.0.0/12
      - 192.0.0.0/24
      - 192.0.2.0/24
      - 192.88.99.0/24
      - 192.168.0.0/16
      - 198.18.0.0/15
      - 198.51.100.0/24
      - 203.0.113.0/24
      - 224.0.0.0/4
      - 240.0.0.0/4
      - 255.255.255.255/32

#===================== 防火墙设置 =====================#

#NAT chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    REDIRECT   tcp  --  0.0.0.0/0            8.8.4.4              redir ports 7892
2    REDIRECT   tcp  --  0.0.0.0/0            8.8.8.8              redir ports 7892
3    REDIRECT   udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:53 redir ports 53
4    REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:53 redir ports 53
5    prerouting_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom prerouting rule chain */
6    zone_lan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
7    zone_wan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
8    zone_wan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
9    openclash  tcp  --  0.0.0.0/0            0.0.0.0/0           
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         

#Mangle chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         

#===================== 路由表状态 =====================#
#route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         125.44.28.1     0.0.0.0         UG    0      0        0 pppoe-wan
125.44.28.1     0.0.0.0         255.255.255.255 UH    0      0        0 pppoe-wan
192.168.1.0     0.0.0.0         255.255.255.0   U     0      0        0 br-lan
192.168.100.0   0.0.0.0         255.255.255.0   U     0      0        0 eth1
#ip route list
default via 125.44.28.1 dev pppoe-wan proto static 
125.44.28.1 dev pppoe-wan proto kernel scope link src 125.44.31.23 
192.168.1.0/24 dev br-lan proto kernel scope link src 192.168.1.1 
192.168.100.0/24 dev eth1 proto kernel scope link src 192.168.100.5 
#ip rule show
0:	from all lookup local
32766:	from all lookup main
32767:	from all lookup default

#===================== 端口占用状态 =====================#
tcp        0      0 0.0.0.0:7890            0.0.0.0:*               LISTEN      22558/clash
tcp        0      0 0.0.0.0:7891            0.0.0.0:*               LISTEN      22558/clash
tcp        0      0 0.0.0.0:7892            0.0.0.0:*               LISTEN      22558/clash
tcp        0      0 0.0.0.0:9090            0.0.0.0:*               LISTEN      22558/clash
udp        0      0 127.0.0.1:7874          0.0.0.0:*                           22558/clash
udp        0      0 0.0.0.0:7891            0.0.0.0:*                           22558/clash

#===================== 测试本机DNS查询 =====================#
Server:		127.0.0.1
Address:	127.0.0.1#53

Name:      www.baidu.com
www.baidu.com	canonical name = www.a.shifen.com
Name:      www.a.shifen.com
Address 1: 61.135.169.121

#===================== resolv.conf.d =====================#
# Interface wan

#===================== 测试本机网络连接 =====================#
HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: private, no-cache, no-store, proxy-revalidate, no-transform
Connection: keep-alive
Content-Length: 277
Content-Type: text/html
Date: Wed, 09 Sep 2020 14:15:26 GMT
Etag: "575e1f5c-115"
Last-Modified: Mon, 13 Jun 2016 02:50:04 GMT
Pragma: no-cache
Server: bfe/1.0.8.18

#===================== 测试本机网络下载 =====================#
HTTP/1.1 200 Connection established

HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 78
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: text/plain; charset=utf-8
ETag: "ef50130dcb4f80be197dede1c4d92defd39808f18c42543560fcb4df97dfb683"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
Via: 1.1 varnish (Varnish/6.0)
X-GitHub-Request-Id: AB1C:8485:379522:480F54:5F58CC0C
Accept-Ranges: bytes
Date: Wed, 09 Sep 2020 14:15:27 GMT
Via: 1.1 varnish
X-Served-By: cache-lax8621-LAX
X-Cache: HIT, HIT
X-Cache-Hits: 2, 1
X-Timer: S1599660928.516125,VS0,VE1
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
X-Fastly-Request-ID: 8850c2a438b3045b2e5d61bad6cfde91aead6145
Expires: Wed, 09 Sep 2020 14:20:27 GMT
Source-Age: 268

#===================== 最近运行日志 =====================#
time="2020-09-09T14:13:00Z" level=info msg="Start initial rule provider ChinaIP"
time="2020-09-09T14:13:00Z" level=info msg="Start initial rule provider Unbreak"
time="2020-09-09T14:13:00Z" level=info msg="DNS server listening at: 127.0.0.1:7874"
2020-09-09 22:12:58 OpenClash Start Successful
2020-09-09 22:13:00 Watchdog: Reset Firewall For Enabling Redirect.
time="2020-09-09T14:13:34Z" level=info msg="Start initial compatible provider Speedtest"
time="2020-09-09T14:13:34Z" level=info msg="Start initial compatible provider AdBlock"
time="2020-09-09T14:13:34Z" level=info msg="Start initial compatible provider Netflix"
time="2020-09-09T14:13:34Z" level=info msg="Start initial compatible provider Microsoft"
time="2020-09-09T14:13:34Z" level=info msg="Start initial compatible provider GlobalTV"
time="2020-09-09T14:13:34Z" level=info msg="Start initial compatible provider Apple"
time="2020-09-09T14:13:34Z" level=info msg="Start initial compatible provider Netease Music"
time="2020-09-09T14:13:34Z" level=info msg="Start initial compatible provider Spotify"
time="2020-09-09T14:13:34Z" level=info msg="Start initial compatible provider Telegram"
time="2020-09-09T14:13:34Z" level=info msg="Start initial compatible provider AsianTV"
time="2020-09-09T14:13:34Z" level=info msg="Start initial compatible provider Auto - UrlTest"
time="2020-09-09T14:13:34Z" level=info msg="Start initial compatible provider Proxy"
time="2020-09-09T14:13:34Z" level=info msg="Start initial compatible provider Others"
time="2020-09-09T14:13:34Z" level=info msg="Start initial compatible provider Domestic"
time="2020-09-09T14:13:34Z" level=info msg="Start initial compatible provider Youtube"
time="2020-09-09T14:13:34Z" level=info msg="Start initial compatible provider Steam"
time="2020-09-09T14:13:34Z" level=info msg="Start initial compatible provider PayPal"
time="2020-09-09T14:13:34Z" level=info msg="Start initial rule provider Global"
time="2020-09-09T14:13:34Z" level=info msg="Start initial rule provider China"
time="2020-09-09T14:13:34Z" level=info msg="Start initial rule provider ChinaIP"
time="2020-09-09T14:13:34Z" level=info msg="Start initial rule provider Unbreak"
time="2020-09-09T14:13:34Z" level=info msg="Start initial rule provider Streaming"
time="2020-09-09T14:13:34Z" level=info msg="Start initial rule provider StreamingSE"
time="2020-09-09T14:13:34Z" level=info msg="DNS server listening at: 127.0.0.1:7874"
2020-09-09 22:13:33 OpenClash Start Successful

**Comment by lifetyper** [comment]
有同样的问题，fake ip模式

**Comment by caliban511** [comment]
我这里也是，更新到39.9后，显示守护程序未运行。看来这是这个版本的BUG了。

**Comment by terenceng81** [comment]
也是有一样的问题。。。

**Comment by yanyingjie007** [comment]
hi, same here

**Comment by terenceng81** [comment]
我降级至 0.39.8 了，等问题解决了再更新吧

**Comment by lifetyper** [comment]
刚才的新版本已经修复这个问题了。

**Comment by elonj** [comment]
40.4中也遇到了这个问题。watchdog不运行了
![image](https://user-images.githubusercontent.com/56976129/93717618-ca096400-fb2b-11ea-84b7-e4976f785488.png)
