### ISSUE TITLE
启动错误日志如下

### ISSUE THREAD

**Issue by cescqb** [vernesong/OpenClash#727]
time="2020-09-10T00:10:18+08:00" level=fatal msg="Parse config error: yaml: unmarshal errors:\n  line 125: cannot unmarshal !!map into []map[string]interface {}\n  line 1413: cannot unmarshal !!map into []map[string]interface {}"
2020-09-10 00:10:13 OpenClash Can Not Start, Please Check The Error Info And Try Again

**Comment by cescqb** [comment]
我发现应该是一个bug，启动后会将配置文件的name前-删除，造成配置文件错误
      - 255.255.255.255/32
#===================== OpenClash-General-Settings =====================#
proxies:

    name: 'V301U&-1X-深圳香港CN2-NF*'
    type: ssr

**Comment by aprilies** [comment]
time="2020-09-10T14:43:41+08:00" level=fatal msg="Parse config error: yaml: unmarshal errors:\n  line 64: cannot unmarshal !!map into []map[string]interface {}\n  line 749: cannot unmarshal !!map into []map[string]interface {}"
2020-09-10 14:43:35 OpenClash Can Not Start, Please Check The Error Info And Try Again

今天更新最新的v0.40.1客户端版本和内核版本之后遇到了和你一样的报错

**Comment by aprilies** [comment]
> 我发现应该是一个bug，启动后会将配置文件的name前-删除，造成配置文件错误
> - 255.255.255.255/32
> #===================== OpenClash-General-Settings =====================#
> proxies:
> 
> ```
> name: 'V301U&-1X-深圳香港CN2-NF*'
> type: ssr
> ```

手动修改配置文件,补上name前的-后上传，能正常启动了，谢谢。

**Comment by zhu8808** [comment]
我也一样 添加-后也无法解决报错
