### ISSUE TITLE
v0.39.9-beta启动失败

### ISSUE THREAD

**Issue by lichuncat** [vernesong/OpenClash#728]
v0.39.8-beta是和lhie1的新规则文件不匹配。升级到v0.39.9-beta，重新配置，订阅rixcloud，启动失败，报错：
time="2020-09-10T05:10:55+08:00" level=fatal msg="Parse config error: yaml: unmarshal errors:\n  line 105: cannot unmarshal !!map into []map[string]interface {}\n  line 1053: cannot unmarshal !!map into []map[string]interface {}"
2020-09-10 05:10:51 OpenClash Can Not Start, Please Check The Error Info And Try Again

**Comment by cescqb** [comment]
我和你一样的错误提示

**Comment by iam3ddy** [comment]
更新0.39-9后， 守护程序“未运行”
![Screenshot 2020-09-10 at 8 37 49 AM☀️](https://user-images.githubusercontent.com/21017389/92668337-23f67680-f341-11ea-8976-0e7f8ef0b821.png)
![Screenshot 2020-09-10 at 8 41 24 AM☀️](https://user-images.githubusercontent.com/21017389/92668457-6ddf5c80-f341-11ea-81df-c9d17d453f94.png)

**Comment by iam3ddy** [comment]
> 更新0.39-9后， 守护程序“未运行”
> ![Screenshot 2020-09-10 at 8 37 49 AM☀️](https://user-images.githubusercontent.com/21017389/92668337-23f67680-f341-11ea-8976-0e7f8ef0b821.png)
> ![Screenshot 2020-09-10 at 8 41 24 AM☀️](https://user-images.githubusercontent.com/21017389/92668457-6ddf5c80-f341-11ea-81df-c9d17d453f94.png)

40-1beta解决了守护程序“未运行” 问题
