### ISSUE TITLE
配置文件一键生成  错误

### ISSUE THREAD

**Issue by OleStore** [vernesong/OpenClash#729]
自行添加的节点信息，使用一键配置
错误提示
time="2020-09-10T00:22:35Z" level=info msg="Start initial compatible provider PayPal"
time="2020-09-10T00:22:35Z" level=info msg="Start initial compatible provider Microsoft"
time="2020-09-10T00:22:35Z" level=info msg="Start initial compatible provider Apple"
time="2020-09-10T00:22:35Z" level=info msg="Start initial compatible provider Speedtest"
time="2020-09-10T00:22:35Z" level=info msg="Start initial compatible provider Spotify"
time="2020-09-10T00:22:35Z" level=info msg="Start initial compatible provider AdBlock"
time="2020-09-10T00:22:35Z" level=info msg="Start initial compatible provider Proxy"
time="2020-09-10T00:22:35Z" level=info msg="Start initial compatible provider Domestic"
time="2020-09-10T00:22:35Z" level=info msg="Start initial compatible provider Netflix"
time="2020-09-10T00:22:35Z" level=info msg="Start initial compatible provider Youtube"
time="2020-09-10T00:22:35Z" level=info msg="Start initial compatible provider Others"
time="2020-09-10T00:22:35Z" level=info msg="Start initial compatible provider Telegram"
time="2020-09-10T00:22:35Z" level=info msg="Start initial compatible provider AsianTV"
time="2020-09-10T00:22:35Z" level=info msg="Start initial compatible provider Auto - UrlTest"
time="2020-09-10T00:22:35Z" level=info msg="Start initial compatible provider GlobalTV"
time="2020-09-10T00:22:35Z" level=info msg="Start initial compatible provider Steam"
time="2020-09-10T00:22:35Z" level=info msg="Start initial rule provider Special"
time="2020-09-10T00:22:35Z" level=info msg="Start initial rule provider Amazon"
time="2020-09-10T00:22:35Z" level=info msg="Start initial rule provider myTV SUPER"
time="2020-09-10T00:22:35Z" level=info msg="Start initial rule provider Netflix"
time="2020-09-10T00:22:35Z" level=info msg="Start initial rule provider Letv"
time="2020-09-10T00:22:35Z" level=info msg="Start initial rule provider BBC iPlayer"
time="2020-09-10T00:22:35Z" level=info msg="Start initial rule provider iQiyi"
time="2020-09-10T00:22:35Z" level=info msg="Start initial rule provider Apple"
time="2020-09-10T00:22:35Z" level=info msg="Start initial rule provider Hulu Japan"
time="2020-09-10T00:22:35Z" level=info msg="Start initial rule provider Domestic IPs"
time="2020-09-10T00:22:35Z" level=info msg="Start initial rule provider JOOX"
time="2020-09-10T00:22:35Z" level=info msg="Start initial rule provider encoreTVB"
time="2020-09-10T00:22:35Z" level=info msg="Start initial rule provider Fox Now"
time="2020-09-10T00:22:35Z" level=info msg="Start initial rule provider Reject"
time="2020-09-10T00:22:35Z" level=info msg="Start initial rule provider HBO"
time="2020-09-10T00:22:35Z" level=info msg="Start initial rule provider PBS"
time="2020-09-10T00:22:35Z" level=info msg="Start initial rule provider Disney Plus"
time="2020-09-10T00:22:35Z" level=info msg="Start initial rule provider Fox+"
time="2020-09-10T00:22:35Z" level=info msg="Start initial rule provider YouTube"
time="2020-09-10T00:22:35Z" level=info msg="Start initial rule provider Abema TV"
time="2020-09-10T00:22:35Z" level=info msg="Start initial rule provider Japonx"
time="2020-09-10T00:22:35Z" level=info msg="Start initial rule provider Soundcloud"
time="2020-09-10T00:22:35Z" level=info msg="Start initial rule provider Microsoft"
time="2020-09-10T00:22:35Z" level=info msg="Start initial rule provider Apple TV"
time="2020-09-10T00:22:35Z" level=info msg="Start initial rule provider Steam"
time="2020-09-10T00:22:35Z" level=info msg="Start initial rule provider KKBOX"
time="2020-09-10T00:22:35Z" level=info msg="Start initial rule provider Bahamut"
time="2020-09-10T00:22:35Z" level=info msg="Start initial rule provider Line TV"
time="2020-09-10T00:22:35Z" level=info msg="Start initial rule provider Telegram"
time="2020-09-10T00:22:35Z" level=info msg="Start initial rule provider Domestic"
time="2020-09-10T00:22:35Z" level=info msg="Start initial rule provider Hulu"
time="2020-09-10T00:22:35Z" level=info msg="Start initial rule provider Pornhub"
time="2020-09-10T00:22:35Z" level=info msg="Start initial rule provider DAZN"
time="2020-09-10T00:22:35Z" level=info msg="Start initial rule provider Netease Music"
time="2020-09-10T00:22:35Z" level=info msg="Start initial rule provider ABC"
time="2020-09-10T00:22:35Z" level=info msg="Start initial rule provider Pandora"
time="2020-09-10T00:22:35Z" level=info msg="Start initial rule provider Spotify"
time="2020-09-10T00:22:35Z" level=info msg="Start initial rule provider Speedtest"
time="2020-09-10T00:22:35Z" level=info msg="Start initial rule provider ViuTV"
time="2020-09-10T00:22:35Z" level=info msg="Start initial rule provider PayPal"
time="2020-09-10T00:22:35Z" level=info msg="Start initial rule provider Apple News"
time="2020-09-10T00:22:35Z" level=info msg="Start initial rule provider PROXY"
time="2020-09-10T00:22:35Z" level=info msg="Start initial rule provider Bilibili"
time="2020-09-10T00:22:35Z" level=info msg="Start initial rule provider Tencent Video"
time="2020-09-10T00:22:35Z" level=info msg="Start initial rule provider Youku"
time="2020-09-10T00:22:35Z" level=info msg="Start initial rule provider KKTV"
time="2020-09-10T00:22:35Z" level=fatal msg="Parse config error: rules[4] [RULE-SET,YouTube,YouTube] error: proxy [YouTube] not found"
2020-09-10 08:22:28 Faild to Download Rule-Provider File, Please Check The Error Info And Try Again

**Comment by OleStore** [comment]
time="2020-09-09T23:38:04Z" level=info msg="Start initial compatible provider PayPal"
time="2020-09-09T23:38:04Z" level=info msg="Start initial compatible provider Youtube"
time="2020-09-09T23:38:04Z" level=info msg="Start initial compatible provider Telegram"
time="2020-09-09T23:38:04Z" level=info msg="Start initial compatible provider Speedtest"
time="2020-09-09T23:38:04Z" level=info msg="Start initial compatible provider Proxy"
time="2020-09-09T23:38:04Z" level=info msg="Start initial compatible provider GlobalTV"
time="2020-09-09T23:38:04Z" level=info msg="Start initial compatible provider AdBlock"
time="2020-09-09T23:38:04Z" level=info msg="Start initial compatible provider Spotify"
time="2020-09-09T23:38:04Z" level=info msg="Start initial compatible provider Auto - UrlTest"
time="2020-09-09T23:38:04Z" level=info msg="Start initial compatible provider Microsoft"
time="2020-09-09T23:38:04Z" level=info msg="Start initial compatible provider Apple"
time="2020-09-09T23:38:04Z" level=info msg="Start initial compatible provider Others"
time="2020-09-09T23:38:04Z" level=info msg="Start initial compatible provider Domestic"
time="2020-09-09T23:38:04Z" level=info msg="Start initial compatible provider Netflix"
time="2020-09-09T23:38:04Z" level=info msg="Start initial compatible provider AsianTV"
time="2020-09-09T23:38:04Z" level=info msg="Start initial compatible provider Steam"
time="2020-09-09T23:38:04Z" level=info msg="Start initial rule provider Telegram"
time="2020-09-09T23:38:04Z" level=info msg="Start initial rule provider Tencent Video"
time="2020-09-09T23:38:04Z" level=info msg="Start initial rule provider Bilibili"
time="2020-09-09T23:38:04Z" level=info msg="Start initial rule provider Disney Plus"
time="2020-09-09T23:38:04Z" level=info msg="Start initial rule provider Fox+"
time="2020-09-09T23:38:04Z" level=info msg="Start initial rule provider iQiyi"
time="2020-09-09T23:38:05Z" level=info msg="Start initial rule provider Youku"
time="2020-09-09T23:38:05Z" level=info msg="Start initial rule provider Line TV"
time="2020-09-09T23:38:05Z" level=info msg="Start initial rule provider Amazon"
time="2020-09-09T23:38:05Z" level=info msg="Start initial rule provider Hulu Japan"
time="2020-09-09T23:38:05Z" level=info msg="Start initial rule provider myTV SUPER"
time="2020-09-09T23:38:05Z" level=info msg="Start initial rule provider Letv"
time="2020-09-09T23:38:06Z" level=info msg="Start initial rule provider encoreTVB"
time="2020-09-09T23:38:06Z" level=info msg="Start initial rule provider Apple TV"
time="2020-09-09T23:38:06Z" level=info msg="Start initial rule provider PBS"
time="2020-09-09T23:38:06Z" level=info msg="Start initial rule provider PayPal"
time="2020-09-09T23:38:06Z" level=info msg="Start initial rule provider Domestic"
time="2020-09-09T23:38:06Z" level=info msg="Start initial rule provider Abema TV"
time="2020-09-09T23:38:06Z" level=info msg="Start initial rule provider Steam"
time="2020-09-09T23:38:07Z" level=info msg="Start initial rule provider Microsoft"
time="2020-09-09T23:38:07Z" level=info msg="Start initial rule provider HBO"
time="2020-09-09T23:38:07Z" level=info msg="Start initial rule provider Pandora"
time="2020-09-09T23:38:07Z" level=info msg="Start initial rule provider ViuTV"
time="2020-09-09T23:38:07Z" level=info msg="Start initial rule provider ABC"
time="2020-09-09T23:38:07Z" level=info msg="Start initial rule provider JOOX"
time="2020-09-09T23:38:08Z" level=info msg="Start initial rule provider Special"
time="2020-09-09T23:38:08Z" level=info msg="Start initial rule provider Speedtest"
time="2020-09-09T23:38:08Z" level=info msg="Start initial rule provider PROXY"
time="2020-09-09T23:38:08Z" level=info msg="Start initial rule provider Netease Music"
time="2020-09-09T23:38:08Z" level=info msg="Start initial rule provider BBC iPlayer"
time="2020-09-09T23:38:08Z" level=info msg="Start initial rule provider Japonx"
time="2020-09-09T23:38:08Z" level=info msg="Start initial rule provider Reject"
time="2020-09-09T23:38:09Z" level=info msg="Start initial rule provider Netflix"
time="2020-09-09T23:38:09Z" level=info msg="Start initial rule provider Soundcloud"
time="2020-09-09T23:38:09Z" level=info msg="Start initial rule provider KKTV"
time="2020-09-09T23:38:09Z" level=info msg="Start initial rule provider Apple"
time="2020-09-09T23:38:09Z" level=info msg="Start initial rule provider DAZN"
time="2020-09-09T23:38:09Z" level=info msg="Start initial rule provider Apple News"
time="2020-09-09T23:38:10Z" level=info msg="Start initial rule provider Spotify"
time="2020-09-09T23:38:10Z" level=info msg="Start initial rule provider Bahamut"
time="2020-09-09T23:38:10Z" level=info msg="Start initial rule provider Fox Now"
time="2020-09-09T23:38:10Z" level=info msg="Start initial rule provider Hulu"
time="2020-09-09T23:38:10Z" level=info msg="Start initial rule provider YouTube"
time="2020-09-09T23:38:10Z" level=info msg="Start initial rule provider KKBOX"
time="2020-09-09T23:38:11Z" level=info msg="Start initial rule provider Domestic IPs"
time="2020-09-09T23:38:11Z" level=info msg="Start initial rule provider Pornhub"
time="2020-09-09T23:38:11Z" level=fatal msg="Parse config error: rules[4] [RULE-SET,YouTube,YouTube] error: proxy [YouTube] not found"
2020-09-10 07:37:57 Faild to Download Rule-Provider File, Please Check The Error Info And Try Again

**Comment by OleStore** [comment]
错误: 规则集文件下载失败，请到日志页面查看详细错误信息！

time="2020-09-10T02:53:56Z" level=fatal msg="Parse config error: rules[4] [RULE-SET,YouTube,YouTube] error: proxy [YouTube] not found"
2020-09-10 10:53:49 Faild to Download Rule-Provider File, Please Check The Error Info And Try Again

**Comment by OleStore** [comment]
问题解决。

**Comment by jierchou** [comment]
请问是如何解决的呢？

**Comment by OleStore** [comment]
> 请问是如何解决的呢？

更新到最新版

**Comment by jierchou** [comment]
噢噢，才发现有新版。感谢

**Comment by Leo-Mu** [comment]
> > 请问是如何解决的呢？
> 
> 更新到最新版

更新到最新版还是没解决啊😭
