### ISSUE TITLE
AP模式下Google Home无法正常正常使用Assistant, 以及暂时凑合的解决办法以作参考. 

### ISSUE THREAD

**Issue by phantastar** [vernesong/OpenClash#73]
### 系统: 
Openwrt X86_64原版18.06.5
### OpenClash内核版本: 
v0.16.0-17-g3b0cc85
### OpenClash客户端版本: 
v0.35.5-beta
### DNS模式: 
Fake-IP
### 问题描述: 
运行Openwrt的是软路由, LAN口接出去的的无线路由器转换为AP模式后(普通模式没有该问题), 该WIFI下的Google Home的对话能力丧失(只会回答"There's Something Wrong"等等). 
### 暂时的解决办法: 
根据大佬们已有的解决方案(https://gist.github.com/willwhui/28e8896b6e4560f1cf0d32a5acf501f3)
在Openwrt的防火墙的自定义规则里填了如下内容. 
![屏幕截图(7)](https://user-images.githubusercontent.com/25948362/69408641-63b48900-0d42-11ea-98a5-036528d7c570.png)

> iptables -t nat -A PREROUTING -s 192.168.150.1/24 -p udp --dport 53 -j DNAT --to 192.168.150.1 
iptables -t nat -A PREROUTING -s 192.168.150.1/24 -p tcp --dport 53 -j DNAT --to 192.168.150.1 
iptables -I PREROUTING -t nat -p udp -d 8.8.4.4 --dport 53 -j REDIRECT --to-ports 53 
iptables -I PREROUTING -t nat -p udp -d 8.8.8.8 --dport 53 -j REDIRECT --to-ports 53
iptables -I PREROUTING -t nat -p tcp -d 8.8.4.4 --dport 53 -j REDIRECT --to-ports 53 
iptables -I PREROUTING -t nat -p tcp -d 8.8.8.8 --dport 53 -j REDIRECT --to-ports 53 

Google Home就恢复满血了. 
_**### 但同时发生一个问题**_ 
OpenClash提示53端口被别的程序劫持, **_发现53端口被劫持，如连接异常请将OpenClash设置为劫持53端口程序的上游DNS服务器！_**

**服务器日志:** 
**_2019-11-22 14:50:43 Warring: OpenClash May Can Not Take Over DNS, Please Use OpenClash for Upstream DNS Resolve Server 
2019-11-22 14:50:43 OpenClash Start Successful_**

不过目前至少能用了, 但是DNS劫持有问题, 所以这应该算一个"Clash未对Google Home做劫持"或"iptables转发与Clash DNS劫持有冲突"的问题? 总之我认为我需要提交issue.

**Comment by vernesong** [comment]
防火墙53端口的劫持dnsmasq已经做了，你看下只添加前两条命令是否有用

**Comment by phantastar** [comment]
> 防火墙53端口的劫持dnsmasq已经做了，你看下只添加前两条命令是否有用
谢谢您！只保留前两条后Google Home运行正常，并解决了Clash的DNS劫持冲突; )

**Comment by phantastar** [comment]
> 防火墙53端口的劫持dnsmasq已经做了，你看下只添加前两条命令是否有用

谢谢您！只保留前两条后Google Home运行正常，并解决了OpenClash的DNS劫持冲突; )

**Comment by vernesong** [comment]
你需要确认路由dhcp下发的设置是否有问题，因为dns查询通过openwrt时都会被劫持到openclash，实际上你添加的规则是否起到作用还未知。

**Comment by phantastar** [comment]
> 你需要确认路由dhcp下发的设置是否有问题，因为dns查询通过openwrt时都会被劫持到openclash，实际上你添加的规则是否起到作用还未知。

> 网上的说法
`Google Home不关心DHCP分配什么DNS, 直接走8.8.8.8\8.8.4.4, 在VPN下会改为TCP方式查询DNS. `

我不太清楚是劫持的问题还是路由器的BUG, 在路由器普通模式下(自己独自一个192.168.XXX.XXX网段), Google Home一切功能正常, 切换AP模式后(上级就是装有OpenClash的软路由)Hoogle Home的Assistant功能失效, Chromecast投射仍旧可用. 
### Koolshare+KoolClash\Koolss也是相同的问题
有一个变量在于, 路由器换做华硕AC88U并切换AP模式后, Google Home的Assistant满血工作. 
**那两条规则应该是起到了作用**
现今做了iptables转发后, Google Home的99%功能已恢复, 1%在于, 对它说晚安以后不会像路由器普通模式时那样, 自动播放催眠曲. 

> Moreover

我没有在Github找到私信功能, 但如果您愿意深入, 我自愿捐献家里第二个Google Home(不是Mini也不是Max).
