### ISSUE TITLE
关于	v0.40.1-beta和	v1.1.0-13-g314ce1c的一些问题

### ISSUE THREAD

**Issue by Nepmonts** [vernesong/OpenClash#732]
1.在v0.40.1-beta版本中 Yacd 控制面板中点击Config选项会直接报错，无法正常进行配置，Dashboard 控制面板正常。

2.在更新【Dev分支】内核版本v1.1.0-13-g314ce1c后，在控制面板中查看连接会发现其中出现一些IP和域名直接被DIRECT并没有遵循任何规则或Match走漏网之鱼
例如:
r7---sn-ipoxu-un5d.googlevideo.com
lh3.googleusercontent.com
redirector.googlevideo.com
www.youtube.com
还有一些其他的未知的IP地址，
出现这些情况多数是手机APP使用时出现，但此时访问并未出现异常。

以上为暂时发现的一些问题，希望能够修复，感谢开发者。

**Comment by vernesong** [comment]
Yacd 控制面板更新后浏览器需要强制刷新一下缓存
为何走direct你要看日志才清楚

**Comment by Nepmonts** [comment]
ok

**Comment by Nepmonts** [comment]
#此项在使用Tun模式时应为ACCEPT
防火墙转发: ACCEPT

#此项有值时建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: 

#此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 127.0.0.1#7874

#===================== 依赖检查 =====================#
dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
jsonfilter: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
iptables-mod-tproxy: 已安装
kmod-tun(TUN模式): 已安装
luci-compat(Luci-19.07): 已安装

#===================== 内核检查 =====================#
运行状态: 运行中
已选择的架构: linux-armv8

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 2020.09.05.gaf1a58d
Tun内核文件: 存在
Tun内核运行权限: 正常

Game内核版本: 
Game内核文件: 不存在
Game内核运行权限: 否

Dev内核版本: v1.1.0-13-g314ce1c
Dev内核文件: 存在
Dev内核运行权限: 正常

#===================== 插件设置 =====================#
当前配置文件: /etc/openclash/config/Fuck.yaml
运行模式: fake-ip
默认代理模式: rule
UDP流量转发: 启用
DNS劫持: 启用
自定义DNS: 停用
IPV6-DNS解析: 停用
禁用Dnsmasq缓存: 启用
自定义规则: 停用
仅允许内网: 启用
仅代理命中规则流量: 停用

#启动异常时建议关闭此项后重试
保留配置: 停用
第三方规则: 停用

#===================== 配置文件 =====================#
port: 7890
socks-port: 7891
allow-lan: true
bind-address: "192.168.31.2"
ipv6: false
mode: rule
log-level: silent
external-controller: 192.168.31.2:9090
redir-port: 7892
secret: "123456"
external-ui: "/usr/share/openclash/dashboard"
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  listen: 127.0.0.1:7874
  fake-ip-filter:
##Custom fake-ip-filter##
  - '*.lan'
  - 'time.windows.com'
  - 'time.nist.gov'
  - 'time.apple.com'
  - 'time.asia.apple.com'
  - '*.ntp.org.cn'
  - '*.openwrt.pool.ntp.org'
  - 'time1.cloud.tencent.com'
  - 'time.ustc.edu.cn'
  - 'pool.ntp.org'
  - 'ntp.ubuntu.com'
  - 'ntp.aliyun.com'
  - 'ntp1.aliyun.com'
  - 'ntp2.aliyun.com'
  - 'ntp3.aliyun.com'
  - 'ntp4.aliyun.com'
  - 'ntp5.aliyun.com'
  - 'ntp6.aliyun.com'
  - 'ntp7.aliyun.com'
  - 'time1.aliyun.com'
  - 'time2.aliyun.com'
  - 'time3.aliyun.com'
  - 'time4.aliyun.com'
  - 'time5.aliyun.com'
  - 'time6.aliyun.com'
  - 'time7.aliyun.com'
  - '*.time.edu.cn'
  - 'time1.apple.com'
  - 'time2.apple.com'
  - 'time3.apple.com'
  - 'time4.apple.com'
  - 'time5.apple.com'
  - 'time6.apple.com'
  - 'time7.apple.com'
  - 'time1.google.com'
  - 'time2.google.com'
  - 'time3.google.com'
  - 'time4.google.com'
  - 'music.163.com'
  - '*.music.163.com'
  - '*.126.net'
  - 'musicapi.taihe.com'
  - 'music.taihe.com'
  - 'songsearch.kugou.com'
  - 'trackercdn.kugou.com'
  - '*.kuwo.cn'
  - 'api-jooxtt.sanook.com'
  - 'api.joox.com'
  - 'joox.com'
  - 'y.qq.com'
  - '*.y.qq.com'
  - 'streamoc.music.tc.qq.com'
  - 'mobileoc.music.tc.qq.com'
  - 'isure.stream.qqmusic.qq.com'
  - 'dl.stream.qqmusic.qq.com'
  - 'aqqmusic.tc.qq.com'
  - 'amobile.music.tc.qq.com'
  - '*.xiami.com'
  - '*.music.migu.cn'
  - 'music.migu.cn'
  - '*.msftconnecttest.com'
  - '*.msftncsi.com'
  - 'localhost.ptlogin2.qq.com'
  - '*.*.*.srv.nintendo.net'
  - '*.*.stun.playstation.net'
  - 'xbox.*.*.microsoft.com'
  - '*.*.xboxlive.com'
##Custom fake-ip-filter END##
  nameserver:
  - 114.114.114.114
  - 119.29.29.29
  - https://doh.rixcloud.dev/dns-query
  fallback:
  - https://cloudflare-dns.com/dns-query
  - https://dns.google/dns-query
  - https://1.1.1.1/dns-query
  - tls://8.8.8.8:853
  fallback-filter:
    geoip: true
    ipcidr:
      - 0.0.0.0/8
      - 10.0.0.0/8
      - 100.64.0.0/10
      - 127.0.0.0/8
      - 169.254.0.0/16
      - 172.16.0.0/12
      - 192.0.0.0/24
      - 192.0.2.0/24
      - 192.88.99.0/24
      - 192.168.0.0/16
      - 198.18.0.0/15
      - 198.51.100.0/24
      - 203.0.113.0/24
      - 224.0.0.0/4
      - 240.0.0.0/4
      - 255.255.255.255/32

#===================== 防火墙设置 =====================#

#NAT chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    REDIRECT   tcp  --  0.0.0.0/0            8.8.4.4              redir ports 7892
2    REDIRECT   tcp  --  0.0.0.0/0            8.8.8.8              redir ports 7892
3    REDIRECT   udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:53 redir ports 53
4    REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:53 redir ports 53
5    prerouting_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom prerouting rule chain */
6    zone_lan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
7    openclash  tcp  --  0.0.0.0/0            0.0.0.0/0           
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         
1    openclash_output  tcp  --  0.0.0.0/0            0.0.0.0/0           

#Mangle chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    openclash  udp  --  0.0.0.0/0            0.0.0.0/0           
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         

#===================== 路由表状态 =====================#
#route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.31.1    0.0.0.0         UG    0      0        0 eth0
192.168.31.0    0.0.0.0         255.255.255.0   U     0      0        0 eth0
#ip route list
default via 192.168.31.1 dev eth0 proto static 
192.168.31.0/24 dev eth0 proto kernel scope link src 192.168.31.2 
#ip rule show
0:	from all lookup local
32765:	from all fwmark 0x162 lookup 354
32766:	from all lookup main
32767:	from all lookup default

#===================== 端口占用状态 =====================#
tcp        0      0 192.168.31.2:7890       0.0.0.0:*               LISTEN      13000/clash
tcp        0      0 192.168.31.2:7891       0.0.0.0:*               LISTEN      13000/clash
tcp        0      0 192.168.31.2:9090       0.0.0.0:*               LISTEN      13000/clash
tcp        0      0 :::7892                 :::*                    LISTEN      13000/clash
udp        0      0 127.0.0.1:7874          0.0.0.0:*                           13000/clash
udp        0      0 192.168.31.2:7891       0.0.0.0:*                           13000/clash
udp        0      0 :::7892                 :::*                                13000/clash
udp        0      0 :::55144                :::*                                13000/clash
udp        0      0 :::39277                :::*                                13000/clash

#===================== 测试本机DNS查询 =====================#
Server:		127.0.0.1
Address:	127.0.0.1#53

Name:      www.baidu.com
Address 1: 198.18.0.29
*** Can't find www.baidu.com: No answer

#===================== resolv.conf.d =====================#
# Interface lan
nameserver 192.168.31.1

#===================== 测试本机网络连接 =====================#
HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: private, no-cache, no-store, proxy-revalidate, no-transform
Connection: keep-alive
Content-Length: 277
Content-Type: text/html
Date: Fri, 11 Sep 2020 04:05:13 GMT
Etag: "575e1f60-115"
Last-Modified: Mon, 13 Jun 2016 02:50:08 GMT
Pragma: no-cache
Server: bfe/1.0.8.18


#===================== 测试本机网络下载 =====================#
HTTP/1.1 200 Connection established

HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 78
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: text/plain; charset=utf-8
ETag: "89ed4ad04014b5fa827fb050fe46a1d7fb8c25a0f3f2a883b68615420a18f22b"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
Via: 1.1 varnish (Varnish/6.0)
X-GitHub-Request-Id: FCFE:0542:D7D3C:F6F60:5F5AE497
Accept-Ranges: bytes
Date: Fri, 11 Sep 2020 04:05:14 GMT
Via: 1.1 varnish
X-Served-By: cache-hkg17929-HKG
X-Cache: HIT, HIT
X-Cache-Hits: 1, 1
X-Timer: S1599797114.903996,VS0,VE214
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
X-Fastly-Request-ID: 52b263e04d291454453f2197aee7f4c29f021c0f
Expires: Fri, 11 Sep 2020 04:10:14 GMT
Source-Age: 305


#===================== 最近运行日志 =====================#
time="2020-09-11T12:03:44+08:00" level=info msg="Start initial compatible provider 🚀 节点选择"
time="2020-09-11T12:03:44+08:00" level=info msg="Start initial compatible provider 🎯 全球直连"
time="2020-09-11T12:03:44+08:00" level=info msg="Start initial compatible provider 🐟 漏网之鱼"
2020-09-11 12:03:40 OpenClash Start Successful
![image](https://user-images.githubusercontent.com/63834771/92858122-43b49a00-f428-11ea-92e0-a55cecba3295.png)

**Comment by vernesong** [comment]
没啥问题啊，规则全吗？

**Comment by Nepmonts** [comment]
规则里面有googlevideo.com
![image](https://user-images.githubusercontent.com/63834771/92862137-eff87f80-f42c-11ea-8f2f-3d9bad602f41.png)

**Comment by vernesong** [comment]
那就等更新吧，使用没问题就好

**Comment by Nepmonts** [comment]
> 那就等更新吧，使用没问题就好

今天发现直接被DIRECT都是UDP流量，全局模式下不会DIRECT, 我使用的是Fake-IP（增强）模式或Fake-IP（TUN混合）模式会被直接DIRECT，反馈一下，希望对你修复有用。
