### ISSUE TITLE
关于 ipv6 的讨论

### ISSUE THREAD

**Issue by smallst** [vernesong/OpenClash#735]
目前的openclash似乎与 ipv6 的兼容性比较差？（看到各个地方都建议路由器不要开v6）想了解一下问题是出在哪里，看看能不能帮个手。

因为我在关闭路由器openclash 的情况下使用 clash for windows 的时候，同样的配置下直连访问 ipv6 是正常的，包括 ipv6 站点和 ip.sb 这类ipv6测试的网站都能准确显示ipv6地址和信息。但开启路由器的 openclash 后不管是使用 fake-ip 还是 redir-host 都会出现 ip.sb 上显示我的 ipv6 不可用。由于我目前对 ipv6 的需求也不是特别强烈，因此我自己的解决方案是用 fake-ip 并且把我需要访问的ipv6站点都添加到 dns 例外上。

我很好奇目前是否是因为 openclash 需要接管路由器的 dns 解析，从而导致 ipv6 的解析出了冲突。因为我自己目前没有代理 ipv6 或者使用 ipv6 服务器做代理的需求，所以仅仅是希望 ipv6 可以被正常解析（或者说完全不需要经过 openclash ），目前好像也没有找到合理的配置方法。从而引起了这个讨论。

如果你忙可以不用管我。如果有时间解释一下的话非常感谢。本人有一定的计算机网络基础，应该能听懂专业解释，谢谢！

**Comment by vernesong** [comment]
暂时将IPV6做直连处理

**Comment by smallst** [comment]
@vernesong 这个在配置中可以做到吗？

**Comment by vernesong** [comment]
新版改了，直接放弃ipv6进入clash，dns在劫持下需要去开启ipv6的解析

**Comment by smallst** [comment]
@vernesong 咦，那请问一下，新版（0.40.1 ?) 在fake-ip 模式下dns劫持后没有 开启ipv6解析的选项啊:joy:

**Comment by smallst** [comment]
@vernesong 你这更新效率也太给力了 👍

**Comment by yubanmeiqin9048** [comment]
> 新版改了，直接放弃ipv6进入clash，dns在劫持下需要去开启ipv6的解析

在固件里不够选禁止解析 IPv6 DNS 记录，然后进clash里勾选允许解析IPV6就好了嘛？我下BT的时候需要到IPV6

**Comment by smallst** [comment]
@yubanmeiqin9048 在不开启openclash的情况下保证有ipv6， 然后在openclash中选择解析ipv6就可以。当然以防万一可以在配置文件中两个ipv6的位置都设true
