### ISSUE TITLE
openwrt 内核未选择 tun 模式，总是使用 tun 内核

### ISSUE THREAD

**Issue by rrfeng** [vernesong/OpenClash#737]
手动下载 dev 内核放置到 core/clash，然后启动之后，程序自动创建了内核软链接 `/etc/openclash/clash  -> /etc/openclash/core/clash_tun`，导致找不到内核。

然后程序尝试自动下载 tun 内核，提示下载失败。

**Comment by vernesong** [comment]
某些功能只有tun内核才能使用，你的配置文件内如果有ruleset、script这些就会强制使用tun内核。
建议你只上传clash_tun内核，兼容除游戏模式外的所有模式

**Comment by rrfeng** [comment]
明白了。可能是订阅规则变了，不过这个功能最好给点提示…

**Comment by rrfeng** [comment]
TUN模式需要固件在编译时选择kmod-tun，通过opkg安装时可能无法正常工作。
@vernesong  这个是指 openwrt 内核吗？

**Comment by rrfeng** [comment]
OpenClash 调试日志

生成时间: 2020-09-12 07:35:37
插件版本: v0.39.8-beta

#===================== 系统信息 =====================#
主机型号: INTEL J1900
固件版本: OpenWrt 19.07.3 r11063-85e04e9f46
LuCI版本: git-20.136.49537-fb2f363-1
内核版本: 4.14.180
处理器架构: x86_64

#此项在使用Tun模式时应为ACCEPT
防火墙转发: ACCEPT

#此项有值时建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: 

#此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 127.0.0.1#7874

#===================== 依赖检查 =====================#
dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
jsonfilter: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
iptables-mod-tproxy: 已安装
kmod-tun(TUN模式): 已安装
luci-compat(Luci-19.07): 已安装

#===================== 内核检查 =====================#
运行状态: 运行中
已选择的架构: linux-amd64

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 2020.09.05.gaf1a58d
Tun内核文件: 存在
Tun内核运行权限: 正常

Game内核版本: v0.17.0-194-gbe86985
Game内核文件: 存在
Game内核运行权限: 正常

Dev内核版本: v1.1.0-13-g314ce1c
Dev内核文件: 存在
Dev内核运行权限: 正常

#===================== 插件设置 =====================#
当前配置文件: /etc/openclash/config/test.yaml
运行模式: redir-host
默认代理模式: rule
UDP流量转发: 启用
DNS劫持: 启用
自定义DNS: 启用
IPV6-DNS解析: 停用
禁用Dnsmasq缓存: 启用
自定义规则: 停用
仅允许内网: 启用
仅代理命中规则流量: 启用

#启动异常时建议关闭此项后重试
保留配置: 停用
第三方规则: 停用

#===================== 配置文件 =====================#
---
port: 7890
socks-port: 7891
mixed-port: 8899
allow-lan: true
bind-address: "192.168.2.1"
ipv6: false
mode: rule
log-level: info
external-controller: 192.168.2.1:9090
experimental:
ignore-resolve-fail: true
clash-for-android:
ui-subtitle-pattern: '[一-龥]{2,4}'
redir-port: 7892
secret: "123456"
external-ui: "/usr/share/openclash/dashboard"
hosts:
##Custom HOSTS##
#  experimental hosts, support wildcard (e.g. *.clash.dev Even *.foo.*.example.com)
#  static domain has a higher priority than wildcard domain (foo.example.com > *.example.com)
#  NOTE: hosts don't work with `fake-ip`

#  '*.clash.dev': 127.0.0.1
#  'alpha.clash.dev': '::1'
##Custom HOSTS END##
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 127.0.0.1:7874
  fake-ip-filter:
##Custom DNS##
  nameserver:
  - https://doh.rixcloud.dev/dns-query
  fallback:
  - https://cloudflare-dns.com/dns-query
  - https://dns.google/dns-query
  - tls://dns.google:853
  - https://1.1.1.1/dns-query
  - tls://1.1.1.1:853
  - tls://8.8.8.8:853
  fallback-filter:
    geoip: true
    ipcidr:
      - 0.0.0.0/8
      - 10.0.0.0/8
      - 100.64.0.0/10
      - 127.0.0.0/8
      - 169.254.0.0/16
      - 172.16.0.0/12
      - 192.0.0.0/24
      - 192.0.2.0/24
      - 192.88.99.0/24
      - 192.168.0.0/16
      - 198.18.0.0/15
      - 198.51.100.0/24
      - 203.0.113.0/24
      - 224.0.0.0/4
      - 240.0.0.0/4
      - 255.255.255.255/32

#===================== 防火墙设置 =====================#

#NAT chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    REDIRECT   tcp  --  0.0.0.0/0            8.8.4.4              redir ports 7892
2    REDIRECT   tcp  --  0.0.0.0/0            8.8.8.8              redir ports 7892
3    REDIRECT   tcp  --  0.0.0.0/0            8.8.4.4              redir ports 7892
4    REDIRECT   tcp  --  0.0.0.0/0            8.8.8.8              redir ports 7892
5    prerouting_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom prerouting rule chain */
6    zone_lan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
7    zone_wan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
8    openclash  tcp  --  0.0.0.0/0            0.0.0.0/0           
9    openclash  tcp  --  0.0.0.0/0            0.0.0.0/0           
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         

#Mangle chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    openclash  udp  --  0.0.0.0/0            0.0.0.0/0           
2    openclash  udp  --  0.0.0.0/0            0.0.0.0/0           
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         

#===================== 路由表状态 =====================#
#route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.1.1     0.0.0.0         UG    0      0        0 eth3
192.168.1.0     0.0.0.0         255.255.255.0   U     0      0        0 eth3
192.168.2.0     0.0.0.0         255.255.255.0   U     0      0        0 br-lan
#ip route list
default via 192.168.1.1 dev eth3 proto static src 192.168.1.7 
192.168.1.0/24 dev eth3 proto kernel scope link src 192.168.1.7 
192.168.2.0/24 dev br-lan proto kernel scope link src 192.168.2.1 
#ip rule show
0:	from all lookup local 
32764:	from all fwmark 0x162 lookup 354 
32765:	from all fwmark 0x162 lookup 354 
32766:	from all lookup main 
32767:	from all lookup default 

#===================== 端口占用状态 =====================#
tcp        0      0 192.168.2.1:9090        0.0.0.0:*               LISTEN      18738/clash
tcp        0      0 192.168.2.1:8899        0.0.0.0:*               LISTEN      18738/clash
tcp        0      0 192.168.2.1:7890        0.0.0.0:*               LISTEN      18738/clash
tcp        0      0 192.168.2.1:7891        0.0.0.0:*               LISTEN      18738/clash
tcp        0      0 192.168.2.1:7892        0.0.0.0:*               LISTEN      18738/clash
udp        0      0 192.168.2.1:8899        0.0.0.0:*                           18738/clash
udp        0      0 127.0.0.1:7874          0.0.0.0:*                           18738/clash
udp        0      0 192.168.2.1:7891        0.0.0.0:*                           18738/clash
udp        0      0 192.168.2.1:7892        0.0.0.0:*                           18738/clash
udp        0      0 :::49860                :::*                                18738/clash
udp        0      0 :::48624                :::*                                18738/clash

#===================== 测试本机DNS查询 =====================#
Server:		127.0.0.1
Address:	127.0.0.1#53

Name:      www.baidu.com
www.baidu.com	canonical name = www.a.shifen.com
Name:      www.a.shifen.com
www.a.shifen.com	canonical name = www.wshifen.com
Name:      www.wshifen.com
Address 1: 104.193.88.123
Address 2: 104.193.88.77
*** Can't find www.baidu.com: No answer

#===================== resolv.conf.auto =====================#
# Interface wan
nameserver 192.168.1.1
# Interface wan6
nameserver fe80::1%eth3

#===================== 测试本机网络连接 =====================#
HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: private, no-cache, no-store, proxy-revalidate, no-transform
Connection: keep-alive
Content-Length: 277
Content-Type: text/html
Date: Sat, 12 Sep 2020 07:35:39 GMT
Etag: "575e1f6f-115"
Last-Modified: Mon, 13 Jun 2016 02:50:23 GMT
Pragma: no-cache
Server: bfe/1.0.8.18


#===================== 测试本机网络下载 =====================#
HTTP/1.1 200 Connection established

HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 78
Content-Type: text/plain; charset=utf-8
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
ETag: "640f85e49b4d138d32852f7196455da5aca9eb836586e731ca7060cdbc361ff2"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
Via: 1.1 varnish (Varnish/6.0)
X-GitHub-Request-Id: C34A:3A0C:1688E1:18A4B9:5F5C787C
Accept-Ranges: bytes
Date: Sat, 12 Sep 2020 07:35:41 GMT
Via: 1.1 varnish
X-Served-By: cache-hnd18738-HND
X-Cache: HIT, HIT
X-Cache-Hits: 1, 1
X-Timer: S1599896142.946670,VS0,VE0
Vary: Authorization,Accept-Encoding, Accept-Encoding
Access-Control-Allow-Origin: *
X-Fastly-Request-ID: 53732089c15e93a42c4764234af5ae43b68fbfd3
Expires: Sat, 12 Sep 2020 07:40:41 GMT
Source-Age: 35


#===================== 最近运行日志 =====================#
time="2020-09-12T07:35:36Z" level=warning msg="dial DIRECT error: dial tcp4 149.154.175.55:443: connect: connection refused"
time="2020-09-12T07:35:36Z" level=warning msg="dial DIRECT error: dial tcp4 149.154.175.50:5222: connect: connection refused"
time="2020-09-12T07:35:37Z" level=warning msg="dial DIRECT error: dial tcp4 149.154.175.55:80: connect: connection refused"
time="2020-09-12T07:35:37Z" level=warning msg="dial DIRECT error: dial tcp4 149.154.175.50:443: connect: connection refused"
time="2020-09-12T07:35:37Z" level=warning msg="dial DIRECT error: dial tcp4 149.154.175.55:5222: connect: connection refused"
time="2020-09-12T07:35:37Z" level=warning msg="dial DIRECT error: dial tcp4 149.154.175.50:80: connect: connection refused"
time="2020-09-12T07:35:37Z" level=warning msg="dial DIRECT error: dial tcp4 149.154.175.50:5222: connect: connection refused"
time="2020-09-12T07:35:37Z" level=warning msg="dial DIRECT error: dial tcp4 149.154.175.55:443: connect: connection refused"
time="2020-09-12T07:35:38Z" level=warning msg="dial DIRECT error: dial tcp4 196.55.217.137:443: i/o timeout"
time="2020-09-12T07:35:38Z" level=warning msg="dial DIRECT error: dial tcp4 149.154.175.55:443: connect: connection refused"
time="2020-09-12T07:35:38Z" level=warning msg="dial DIRECT error: dial tcp4 149.154.175.50:5222: connect: connection refused"
time="2020-09-12T07:35:38Z" level=warning msg="dial DIRECT error: dial tcp4 149.154.175.55:5222: connect: connection refused"
time="2020-09-12T07:35:38Z" level=warning msg="dial DIRECT error: dial tcp4 149.154.175.50:443: connect: connection refused"
time="2020-09-12T07:35:38Z" level=warning msg="dial DIRECT error: dial tcp4 149.154.175.50:80: connect: connection refused"
time="2020-09-12T07:35:38Z" level=warning msg="dial DIRECT error: dial tcp4 149.154.175.55:80: connect: connection refused"
time="2020-09-12T07:35:39Z" level=warning msg="dial DIRECT error: dial tcp4 149.154.175.50:80: connect: connection refused"
time="2020-09-12T07:35:39Z" level=warning msg="dial DIRECT error: dial tcp4 149.154.175.55:5222: connect: connection refused"
time="2020-09-12T07:35:39Z" level=warning msg="dial DIRECT error: dial tcp4 149.154.175.55:80: connect: connection refused"
time="2020-09-12T07:35:39Z" level=warning msg="dial DIRECT error: dial tcp4 149.154.175.55:443: connect: connection refused"
time="2020-09-12T07:35:39Z" level=warning msg="dial DIRECT error: dial tcp4 149.154.175.50:443: connect: connection refused"
time="2020-09-12T07:35:39Z" level=warning msg="dial DIRECT error: dial tcp4 149.154.175.50:5222: connect: connection refused"
time="2020-09-12T07:35:40Z" level=info msg="[TCP] 192.168.2.1:35884 --> raw.githubusercontent.com doesn't match any rule using DIRECT"
time="2020-09-12T07:35:41Z" level=warning msg="dial DIRECT error: dial tcp4 149.154.175.55:443: connect: connection refused"
time="2020-09-12T07:35:41Z" level=warning msg="dial DIRECT error: dial tcp4 149.154.175.50:443: connect: connection refused"
time="2020-09-12T07:35:41Z" level=warning msg="dial DIRECT error: dial tcp4 149.154.175.50:80: connect: connection refused"
time="2020-09-12T07:35:41Z" level=warning msg="dial DIRECT error: dial tcp4 149.154.175.50:5222: connect: connection refused"
time="2020-09-12T07:35:41Z" level=warning msg="dial DIRECT error: dial tcp4 149.154.175.55:5222: connect: connection refused"
time="2020-09-12T07:35:41Z" level=warning msg="dial DIRECT error: dial tcp4 149.154.175.55:80: connect: connection refused"
time="2020-09-12T07:35:41Z" level=warning msg="dial DIRECT error: dial tcp4 149.154.175.55:443: connect: connection refused"
time="2020-09-12T07:35:41Z" level=warning msg="dial DIRECT error: dial tcp4 149.154.175.50:443: connect: connection refused"

**Comment by rrfeng** [comment]
原因是规则升级了，然后内核不支持 kmod-tun（非编译的，opkg 安装果然不行）

这是为什么呢……

**Comment by vernesong** [comment]
模块加载问题，换固件吧

**Comment by rrfeng** [comment]
> 模块加载问题，换固件吧

有什么固件推荐的吗？找了一圈也没有明确说编译了 kmod-tun 的。自己编译现在也没下载完代码，真是太难了...

**Comment by vernesong** [comment]
https://drive.google.com/drive/folders/1uRXg_krKHPrQneI3F2GNcSVRoCgkqESr

**Comment by rrfeng** [comment]
> https://drive.google.com/drive/folders/1uRXg_krKHPrQneI3F2GNcSVRoCgkqESr
感谢！

最后一问 kmod-tun 通过 opkg install 不工作是因为跟内核版本不匹配是吗？只要找到匹配的安装包（例如这里：https://downloads.openwrt.org/snapshots/targets/x86/64/kmods/ ）就能正常工作对吗？

**Comment by vernesong** [comment]
一般不行，重新加载模块也不行

**Comment by rrfeng** [comment]
> 一般不行，重新加载模块也不行
这是为什么？内核 bug？
