### ISSUE TITLE
Youtube能打开,但是视频播放不了.

### ISSUE THREAD

**Issue by feijihong** [vernesong/OpenClash#738]
OpenClash 调试日志

生成时间: 2020-09-11 22:28:32
插件版本: v0.40.2-beta

#===================== 系统信息 =====================#
主机型号: FriendlyElec NanoPi R2S
固件版本: OpenWrt SNAPSHOT r2993+618-b9a408c2b4
LuCI版本: git-20.223.26773-d18ef13-1
内核版本: 5.4.61
处理器架构: aarch64_cortex-a53

#此项在使用Tun模式时应为ACCEPT
防火墙转发: ACCEPT

#此项有值时建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: 

#此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 127.0.0.1#7874

#===================== 依赖检查 =====================#
dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
jsonfilter: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
iptables-mod-tproxy: 已安装
kmod-tun(TUN模式): 已安装
luci-compat(Luci-19.07): 未安装

#===================== 内核检查 =====================#
运行状态: 运行中
已选择的架构: linux-armv8

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 2020.09.05.gaf1a58d
Tun内核文件: 存在
Tun内核运行权限: 正常

Game内核版本: v0.17.0-194-gbe86985
Game内核文件: 存在
Game内核运行权限: 正常

Dev内核版本: v1.1.0-13-g314ce1c
Dev内核文件: 存在
Dev内核运行权限: 正常

#===================== 插件设置 =====================#
当前配置文件: /etc/openclash/config/IPLC.yaml
运行模式: redir-host
默认代理模式: rule
UDP流量转发: 停用
DNS劫持: 启用
自定义DNS: 停用
IPV6-DNS解析: 停用
禁用Dnsmasq缓存: 启用
自定义规则: 停用
仅允许内网: 停用
仅代理命中规则流量: 停用

#启动异常时建议关闭此项后重试
保留配置: 停用
第三方规则: 停用

#===================== 配置文件 =====================#
port: 7890
socks-port: 7891
allow-lan: true
bind-address: "*"
ipv6: false
mode: rule
log-level: silent
external-controller: 0.0.0.0:9090
redir-port: 7892
secret: "123456"
external-ui: "/usr/share/openclash/dashboard"
hosts:
##Custom HOSTS##
#  experimental hosts, support wildcard (e.g. *.clash.dev Even *.foo.*.example.com)
#  static domain has a higher priority than wildcard domain (foo.example.com > *.example.com)
#  NOTE: hosts don't work with `fake-ip`

#  '*.clash.dev': 127.0.0.1
#  'alpha.clash.dev': '::1'
##Custom HOSTS END##
dns:
  use-hosts: true
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 127.0.0.1:7874
  fake-ip-filter:
  nameserver:
  - 114.114.114.114
  - 119.29.29.29
  - https://doh.rixcloud.dev/dns-query
  fallback:
  - https://cloudflare-dns.com/dns-query
  - https://dns.google/dns-query
  - https://1.1.1.1/dns-query
  - tls://8.8.8.8:853
  fallback-filter:
    geoip: true
    ipcidr:
      - 0.0.0.0/8
      - 10.0.0.0/8
      - 100.64.0.0/10
      - 127.0.0.0/8
      - 169.254.0.0/16
      - 172.16.0.0/12
      - 192.0.0.0/24
      - 192.0.2.0/24
      - 192.88.99.0/24
      - 192.168.0.0/16
      - 198.18.0.0/15
      - 198.51.100.0/24
      - 203.0.113.0/24
      - 224.0.0.0/4
      - 240.0.0.0/4
      - 255.255.255.255/32

#===================== 防火墙设置 =====================#

#NAT chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    REDIRECT   tcp  --  0.0.0.0/0            8.8.4.4              redir ports 7892
2    REDIRECT   tcp  --  0.0.0.0/0            8.8.8.8              redir ports 7892
3    CLOUD_MUSIC  tcp  --  0.0.0.0/0            0.0.0.0/0            match-set music dst
4    REDIRECT   udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:53 redir ports 53
5    REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:53 redir ports 53
6    prerouting_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom prerouting rule chain */
7    zone_lan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
8    zone_wan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
9    openclash  tcp  --  0.0.0.0/0            0.0.0.0/0           
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         

#Mangle chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         

#===================== 路由表状态 =====================#
#route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.50.1    0.0.0.0         UG    0      0        0 eth1
192.168.0.0     0.0.0.0         255.255.0.0     U     0      0        0 eth1
#ip route list
default via 192.168.50.1 dev eth1 proto static 
192.168.0.0/16 dev eth1 proto kernel scope link src 192.168.50.18 
#ip rule show
0:	from all lookup local 
32766:	from all lookup main 
32767:	from all lookup default 

#===================== 端口占用状态 =====================#
tcp        0      0 :::7890                 :::*                    LISTEN      26474/clash
tcp        0      0 :::7891                 :::*                    LISTEN      26474/clash
tcp        0      0 :::7892                 :::*                    LISTEN      26474/clash
tcp        0      0 :::9090                 :::*                    LISTEN      26474/clash
udp        0      0 127.0.0.1:7874          0.0.0.0:*                           26474/clash
udp        0      0 :::7891                 :::*                                26474/clash
udp        0      0 :::7892                 :::*                                26474/clash

#===================== 测试本机DNS查询 =====================#
Server:		127.0.0.1
Address:	127.0.0.1#53

Name:      www.baidu.com
www.baidu.com	canonical name = www.a.shifen.com
Name:      www.a.shifen.com
Address 1: 14.215.177.39
Address 2: 14.215.177.38
*** Can't find www.baidu.com: No answer

#===================== resolv.conf.auto =====================#
# Interface lan
nameserver 223.5.5.5
nameserver 114.114.114.114

#===================== 测试本机网络连接 =====================#
HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: private, no-cache, no-store, proxy-revalidate, no-transform
Connection: keep-alive
Content-Length: 277
Content-Type: text/html
Date: Fri, 11 Sep 2020 14:28:34 GMT
Etag: "575e1f71-115"
Last-Modified: Mon, 13 Jun 2016 02:50:25 GMT
Pragma: no-cache
Server: bfe/1.0.8.18

#===================== 测试本机网络下载 =====================#
HTTP/1.1 200 Connection established

HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 78
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: text/plain; charset=utf-8
ETag: "640f85e49b4d138d32852f7196455da5aca9eb836586e731ca7060cdbc361ff2"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
Via: 1.1 varnish (Varnish/6.0)
X-GitHub-Request-Id: 9914:4BD4:17B53C:1B609E:5F5B79CF
Accept-Ranges: bytes
Date: Fri, 11 Sep 2020 14:28:34 GMT
Via: 1.1 varnish
X-Served-By: cache-hkg17921-HKG
X-Cache: HIT, HIT
X-Cache-Hits: 1, 1
X-Timer: S1599834514.472467,VS0,VE1
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
X-Fastly-Request-ID: 6bce2b0b07bdbbafec4e81a94ae0fe000b5f208d
Expires: Fri, 11 Sep 2020 14:33:34 GMT
Source-Age: 13

#===================== 最近运行日志 =====================#
time="2020-09-11T14:26:41Z" level=info msg="Start initial compatible provider 🔮 负载均衡"
time="2020-09-11T14:26:41Z" level=info msg="Start initial compatible provider 🔯 故障转移"
time="2020-09-11T14:26:41Z" level=info msg="Start initial compatible provider ♻️ 自动选择"
time="2020-09-11T14:26:41Z" level=info msg="Start initial compatible provider 🚀 节点选择"
time="2020-09-11T14:26:41Z" level=info msg="Start initial compatible provider 🎯 全球直连"
time="2020-09-11T14:26:41Z" level=info msg="Start initial compatible provider 🛑 全球拦截"
time="2020-09-11T14:26:41Z" level=info msg="Start initial compatible provider 🐟 漏网之鱼"
2020-09-11 22:26:35 OpenClash Start Successful

上面是运行日志,这个问题能解决吗?

**Comment by vernesong** [comment]
![image](https://user-images.githubusercontent.com/42875168/92947879-2c5ac880-f48b-11ea-8f7e-729713ce28ba.png)
配置文件里的这个DNS端口你看看是不是被占用了，自己换一个试试

**Comment by feijihong** [comment]
> 配置没发现问题，你直接切换到fakeip模式测试，redir模式可能会受污染影响

已切换未fakeip模式,但是我在Dashboard 控制面板里看到连接详情,类型还是Redir.这样会有问题吗?

**Comment by feijihong** [comment]
> > 配置没发现问题，你直接切换到fakeip模式测试，redir模式可能会受污染影响
> 
> 已切换为fakeip模式,但是我在Dashboard 控制面板里看到连接详情,类型还是Redir.这是否切换成功?

![aaa](https://user-images.githubusercontent.com/27736975/92951886-adb55980-f491-11ea-9d80-7b2d6f6a19a3.png)

**Comment by vernesong** [comment]
嗯

**Comment by feijihong** [comment]
> 嗯

[https://github.com/vernesong/OpenClash/issues/631](url)
还有其他办法解决吗?
编译固件没成功过...希望有其他办法解决.

**Comment by GeorgeMiao219** [comment]
我也是同样的问题，具体情况是手机和ATV设置网关和DNS到路由器上，可以打开youtube但是无法播放视频，在运行日志里有显示确实走了节点。

OpenClash 调试日志

生成时间: 2020-09-12 09:56:56
插件版本: v0.40.2-beta

#===================== 系统信息 =====================#
主机型号: Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz : 2 Core 4 Thread
固件版本: OpenWrt SNAPSHOT r2495-f2f84a68
LuCI版本: git-20.117.60969-420c61a-1
内核版本: 4.19.115
处理器架构: x86_64

#此项在使用Tun模式时应为ACCEPT
防火墙转发: ACCEPT

#此项有值时建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: 

#此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 

#===================== 依赖检查 =====================#
dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
jsonfilter: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
iptables-mod-tproxy: 已安装
kmod-tun(TUN模式): 已安装
luci-compat(Luci-19.07): 未安装

#===================== 内核检查 =====================#
运行状态: 运行中
已选择的架构: linux-amd64

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 
Tun内核文件: 不存在
Tun内核运行权限: 否

Game内核版本: 
Game内核文件: 不存在
Game内核运行权限: 否

Dev内核版本: v1.1.0-13-g314ce1c
Dev内核文件: 存在
Dev内核运行权限: 正常

#===================== 插件设置 =====================#
当前配置文件: /etc/openclash/config/miao.dev.yaml
运行模式: fake-ip
默认代理模式: rule
UDP流量转发: 停用
DNS劫持: 启用
自定义DNS: 停用
IPV6-DNS解析: 停用
禁用Dnsmasq缓存: 停用
自定义规则: 停用
仅允许内网: 停用
仅代理命中规则流量: 停用

#启动异常时建议关闭此项后重试
保留配置: 停用
第三方规则: 停用

#===================== 配置文件 =====================#
allow-lan: true
bind-address: "*"
redir-port: 7892
port: 7890
socks-port: 7891
ipv6: false
mode: rule
log-level: debug
external-controller: 0.0.0.0:9090
external-ui: "/usr/share/openclash/dashboard"
secret: "0219"
dns:
  use-hosts: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  listen: 127.0.0.1:7874
  enable: true
  ipv6: false
  fallback:
  - tls://13800000000.rubyfish.cn:853
  - tls://1.0.0.1:853
  - tls://dns.google:853
  fake-ip-filter:
##Custom fake-ip-filter##
  - '*.lan'
  - 'time.windows.com'
  - 'time.nist.gov'
  - 'time.apple.com'
  - 'time.asia.apple.com'
  - '*.ntp.org.cn'
  - '*.openwrt.pool.ntp.org'
  - 'time1.cloud.tencent.com'
  - 'time.ustc.edu.cn'
  - 'pool.ntp.org'
  - 'ntp.ubuntu.com'
  - 'ntp.aliyun.com'
  - 'ntp1.aliyun.com'
  - 'ntp2.aliyun.com'
  - 'ntp3.aliyun.com'
  - 'ntp4.aliyun.com'
  - 'ntp5.aliyun.com'
  - 'ntp6.aliyun.com'
  - 'ntp7.aliyun.com'
  - 'time1.aliyun.com'
  - 'time2.aliyun.com'
  - 'time3.aliyun.com'
  - 'time4.aliyun.com'
  - 'time5.aliyun.com'
  - 'time6.aliyun.com'
  - 'time7.aliyun.com'
  - '*.time.edu.cn'
  - 'time1.apple.com'
  - 'time2.apple.com'
  - 'time3.apple.com'
  - 'time4.apple.com'
  - 'time5.apple.com'
  - 'time6.apple.com'
  - 'time7.apple.com'
  - 'time1.google.com'
  - 'time2.google.com'
  - 'time3.google.com'
  - 'time4.google.com'
  - 'music.163.com'
  - '*.music.163.com'
  - '*.126.net'
  - 'musicapi.taihe.com'
  - 'music.taihe.com'
  - 'songsearch.kugou.com'
  - 'trackercdn.kugou.com'
  - '*.kuwo.cn'
  - 'api-jooxtt.sanook.com'
  - 'api.joox.com'
  - 'joox.com'
  - 'y.qq.com'
  - '*.y.qq.com'
  - 'streamoc.music.tc.qq.com'
  - 'mobileoc.music.tc.qq.com'
  - 'isure.stream.qqmusic.qq.com'
  - 'dl.stream.qqmusic.qq.com'
  - 'aqqmusic.tc.qq.com'
  - 'amobile.music.tc.qq.com'
  - '*.xiami.com'
  - '*.music.migu.cn'
  - 'music.migu.cn'
  - '*.msftconnecttest.com'
  - '*.msftncsi.com'
  - 'localhost.ptlogin2.qq.com'
  - '*.*.*.srv.nintendo.net'
  - '*.*.stun.playstation.net'
  - 'xbox.*.*.microsoft.com'
  - '*.*.xboxlive.com'
  - 'proxy.golang.org'
##Custom fake-ip-filter END##
  - '*.lan'
  - 'time.windows.com'
  - 'time.nist.gov'
  - 'time.apple.com'
  - 'time.asia.apple.com'
  - '*.ntp.org.cn'
  - '*.openwrt.pool.ntp.org'
  - 'time1.cloud.tencent.com'
  - 'time.ustc.edu.cn'
  - 'pool.ntp.org'
  - 'ntp.ubuntu.com'
  - 'ntp.aliyun.com'
  - 'ntp1.aliyun.com'
  - 'ntp2.aliyun.com'
  - 'ntp3.aliyun.com'
  - 'ntp4.aliyun.com'
  - 'ntp5.aliyun.com'
  - 'ntp6.aliyun.com'
  - 'ntp7.aliyun.com'
  - 'time1.aliyun.com'
  - 'time2.aliyun.com'
  - 'time3.aliyun.com'
  - 'time4.aliyun.com'
  - 'time5.aliyun.com'
  - 'time6.aliyun.com'
  - 'time7.aliyun.com'
  - '*.time.edu.cn'
  - 'time1.apple.com'
  - 'time2.apple.com'
  - 'time3.apple.com'
  - 'time4.apple.com'
  - 'time5.apple.com'
  - 'time6.apple.com'
  - 'time7.apple.com'
  - 'time1.google.com'
  - 'time2.google.com'
  - 'time3.google.com'
  - 'time4.google.com'
  - 'music.163.com'
  - '*.music.163.com'
  - '*.126.net'
  - 'musicapi.taihe.com'
  - 'music.taihe.com'
  - 'songsearch.kugou.com'
  - 'trackercdn.kugou.com'
  - '*.kuwo.cn'
  - 'api-jooxtt.sanook.com'
  - 'api.joox.com'
  - 'joox.com'
  - 'y.qq.com'
  - '*.y.qq.com'
  - 'streamoc.music.tc.qq.com'
  - 'mobileoc.music.tc.qq.com'
  - 'isure.stream.qqmusic.qq.com'
  - 'dl.stream.qqmusic.qq.com'
  - 'aqqmusic.tc.qq.com'
  - 'amobile.music.tc.qq.com'
  - '*.xiami.com'
  - '*.music.migu.cn'
  - 'music.migu.cn'
  - '*.msftconnecttest.com'
  - '*.msftncsi.com'
  - 'localhost.ptlogin2.qq.com'
  - '*.*.*.srv.nintendo.net'
  - '*.*.stun.playstation.net'
  - 'xbox.*.*.microsoft.com'
  - '*.*.xboxlive.com'
  - 'proxy.golang.org'
##Custom fake-ip-filter END##
  nameserver:
  - 1.2.4.8
  - 114.114.114.114
  - 223.5.5.5
  - tls://13800000000.rubyfish.cn:853
experimental:
  ignore-resolve-fail: true
log-level: info
mode: Rule
port: 7890

#===================== 防火墙设置 =====================#

#NAT chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    REDIRECT   udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:53 redir ports 53
2    REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:53 redir ports 53
3    DOCKER     all  --  0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL
4    prerouting_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom prerouting rule chain */
5    zone_lan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
6    zone_wan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
7    zone_vpn_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         
1    DOCKER     all  --  0.0.0.0/0           !127.0.0.0/8          ADDRTYPE match dst-type LOCAL

#Mangle chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         
1    RRDIPT_OUTPUT  all  --  0.0.0.0/0            0.0.0.0/0           

#===================== 路由表状态 =====================#
#route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.1.1     0.0.0.0         UG    0      0        0 eth0
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
192.168.1.0     0.0.0.0         255.255.255.0   U     0      0        0 eth0
#ip route list
default via 192.168.1.1 dev eth0 proto static src 192.168.1.116 
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown 
192.168.1.0/24 dev eth0 proto kernel scope link src 192.168.1.2 
#ip rule show
0:	from all lookup local 
32766:	from all lookup main 
32767:	from all lookup default 

#===================== 端口占用状态 =====================#
tcp        0      0 :::7890                 :::*                    LISTEN      6705/clash
tcp        0      0 :::7891                 :::*                    LISTEN      6705/clash
tcp        0      0 :::7892                 :::*                    LISTEN      6705/clash
tcp        0      0 :::9090                 :::*                    LISTEN      6705/clash
udp        0      0 127.0.0.1:7874          0.0.0.0:*                           6705/clash
udp        0      0 :::7891                 :::*                                6705/clash
udp        0      0 :::7892                 :::*                                6705/clash

#===================== 测试本机DNS查询 =====================#
Server:		127.0.0.1
Address:	127.0.0.1#53

Name:      www.baidu.com
www.baidu.com	canonical name = www.a.shifen.com
Name:      www.a.shifen.com
Address 1: 180.101.49.11
Address 2: 180.101.49.12
*** Can't find www.baidu.com: No answer

#===================== resolv.conf.auto =====================#
# Interface WAN0
nameserver 192.168.1.1

#===================== 测试本机网络连接 =====================#
HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: private, no-cache, no-store, proxy-revalidate, no-transform
Connection: keep-alive
Content-Length: 277
Content-Type: text/html
Date: Sat, 12 Sep 2020 01:56:56 GMT
Etag: "575e1f60-115"
Last-Modified: Mon, 13 Jun 2016 02:50:08 GMT
Pragma: no-cache
Server: bfe/1.0.8.18


#===================== 测试本机网络下载 =====================#
HTTP/1.1 200 Connection established

HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 78
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: text/plain; charset=utf-8
ETag: "640f85e49b4d138d32852f7196455da5aca9eb836586e731ca7060cdbc361ff2"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
Via: 1.1 varnish (Varnish/6.0)
X-GitHub-Request-Id: 266A:418B:2493:35DB:5F5C1FB8
Accept-Ranges: bytes
Date: Sat, 12 Sep 2020 01:56:56 GMT
Via: 1.1 varnish
X-Served-By: cache-hkg17928-HKG
X-Cache: MISS, HIT
X-Cache-Hits: 0, 2
X-Timer: S1599875817.810673,VS0,VE0
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
X-Fastly-Request-ID: dd3a4b674b4eab5adae538a254743136dc078d4f
Expires: Sat, 12 Sep 2020 02:01:56 GMT
Source-Age: 263


#===================== 最近运行日志 =====================#
time="2020-09-12T09:54:16+08:00" level=info msg="[TCP] 192.168.1.37:50561 --> content-autofill.googleapis.com match DomainKeyword(google) using YoYu-Pro[专线 上海-香港 03 [0.5]]"
time="2020-09-12T09:54:54+08:00" level=info msg="[TCP] 192.168.1.37:50562 --> mtalk.google.com match DomainKeyword(google) using YoYu-Pro[专线 上海-香港 03 [0.5]]"
time="2020-09-12T09:55:19+08:00" level=info msg="[TCP] 192.168.1.37:50568 --> github.com match DomainKeyword(github) using YoYu-Pro[专线 上海-香港 03 [0.5]]"
time="2020-09-12T09:55:20+08:00" level=info msg="[TCP] 192.168.1.37:50569 --> avatars1.githubusercontent.com match DomainKeyword(github) using YoYu-Pro[专线 上海-香港 03 [0.5]]"
time="2020-09-12T09:55:36+08:00" level=info msg="[TCP] 192.168.1.37:50570 --> d27xxe7juh1us6.cloudfront.net match DomainSuffix(cloudfront.net) using YoYu-Pro[日用 香港 01 [0.2]]"
2020-09-12 09:55:58 OpenClash Reload After Firewall Restart
time="2020-09-12T09:56:06+08:00" level=info msg="[TCP] 192.168.1.37:50574 --> whois.pconline.com.cn match DomainSuffix(cn) using DIRECT"
time="2020-09-12T09:56:06+08:00" level=info msg="[TCP] 192.168.1.37:50576 --> myip.ipip.net match DomainSuffix(ipip.net) using DIRECT"
time="2020-09-12T09:56:06+08:00" level=info msg="[TCP] 192.168.1.37:50575 --> api-ipv4.ip.sb match Match() using YoYu-Pro[日用 香港 01 [0.2]]"
time="2020-09-12T09:56:06+08:00" level=info msg="[TCP] 192.168.1.37:50577 --> api.ipify.org match Match() using YoYu-Pro[日用 香港 01 [0.2]]"
time="2020-09-12T09:56:06+08:00" level=info msg="[TCP] 192.168.1.37:50578 --> d.skk.moe match Match() using YoYu-Pro[日用 香港 01 [0.2]]"
time="2020-09-12T09:56:06+08:00" level=info msg="[TCP] 192.168.1.37:50580 --> api.ttt.sh match Match() using YoYu-Pro[日用 香港 01 [0.2]]"
time="2020-09-12T09:56:06+08:00" level=info msg="[TCP] 192.168.1.37:50579 --> api.skk.moe match Match() using YoYu-Pro[日用 香港 01 [0.2]]"
time="2020-09-12T09:56:06+08:00" level=info msg="[TCP] 192.168.1.37:50584 --> myip.ipip.net match DomainSuffix(ipip.net) using DIRECT"
time="2020-09-12T09:56:06+08:00" level=info msg="[TCP] 192.168.1.37:50582 --> myip.ipip.net match DomainSuffix(ipip.net) using DIRECT"
time="2020-09-12T09:56:06+08:00" level=info msg="[TCP] 192.168.1.37:50583 --> api.ipify.org match Match() using YoYu-Pro[日用 香港 01 [0.2]]"
time="2020-09-12T09:56:06+08:00" level=info msg="[TCP] 192.168.1.37:50585 --> api.ipify.org match Match() using YoYu-Pro[日用 香港 01 [0.2]]"
time="2020-09-12T09:56:07+08:00" level=info msg="[TCP] 192.168.1.37:50586 --> www.baidu.com match DomainKeyword(baidu) using DIRECT"
time="2020-09-12T09:56:07+08:00" level=info msg="[TCP] 192.168.1.37:50589 --> www.baidu.com match DomainKeyword(baidu) using DIRECT"
time="2020-09-12T09:56:07+08:00" level=info msg="[TCP] 192.168.1.37:50587 --> s1.music.126.net match DomainSuffix(126.net) using DIRECT"
time="2020-09-12T09:56:07+08:00" level=info msg="[TCP] 192.168.1.37:50588 --> www.youtube.com match DomainKeyword(youtube) using YoYu-Pro[日用 香港 01 [0.2]]"
time="2020-09-12T09:56:07+08:00" level=info msg="[TCP] 192.168.1.37:50590 --> github.com match DomainKeyword(github) using YoYu-Pro[日用 香港 01 [0.2]]"
time="2020-09-12T09:56:07+08:00" level=info msg="[TCP] 192.168.1.37:50591 --> qqwry.api.skk.moe match Match() using YoYu-Pro[日用 香港 01 [0.2]]"
time="2020-09-12T09:56:35+08:00" level=info msg="[TCP] 192.168.1.37:50592 --> play.google.com match DomainKeyword(google) using YoYu-Pro[日用 香港 01 [0.2]]"
time="2020-09-12T09:56:48+08:00" level=info msg="[TCP] 192.168.1.37:50593 --> myip.ipip.net match DomainSuffix(ipip.net) using DIRECT"
time="2020-09-12T09:56:48+08:00" level=info msg="[TCP] 192.168.1.37:50596 --> myip.ipip.net match DomainSuffix(ipip.net) using DIRECT"
time="2020-09-12T09:56:48+08:00" level=info msg="[TCP] 192.168.1.37:50597 --> myip.ipip.net match DomainSuffix(ipip.net) using DIRECT"
time="2020-09-12T09:56:48+08:00" level=info msg="[TCP] 192.168.1.37:50598 --> github.com match DomainKeyword(github) using YoYu-Pro[日用 香港 01 [0.2]]"
time="2020-09-12T09:56:55+08:00" level=info msg="[TCP] 192.168.1.37:50599 --> mtalk.google.com match DomainKeyword(google) using YoYu-Pro[日用 香港 01 [0.2]]"
time="2020-09-12T09:56:56+08:00" level=info msg="[TCP] 192.168.1.2:50250 --> raw.githubusercontent.com match DomainKeyword(github) using YoYu-Pro[日用 香港 01 [0.2]]"

**Comment by vernesong** [comment]
dnsmasq转发设置失败，自行查找原因

**Comment by PSC-F** [comment]
问题:  我遇到了在chrome中 youtube 加载不出来的情况，用火狐浏览器却可以正常播放。
解决:  停用 *仅代理命中规则流量

**Comment by obeho** [comment]
你好，我不懂中文，对不起。我想找这个域名的信息，只有这个页面有参考。请您解释一下该域名的用途？`d27xxe7juh1us6.cloudfront.net` @GeorgeMiao219

**Comment by Alafun** [comment]
@obeho maybe you want to @George-Miao
