### ISSUE TITLE
订阅节点失败

### ISSUE THREAD

**Issue by moekyo** [vernesong/OpenClash#739]
节点订阅失败，试了很多次，也试过重装了，可是节点死活下载不了，一个是V2Ray，一个是ssr的。最后试了一个的机场Trojan，这个就订阅成功了。请问这是为什么？

附上 调试日志
OpenClash 调试日志

生成时间: 2020-09-11 22:37:20
插件版本: v0.40.2-beta

#===================== 系统信息 =====================#
主机型号: FriendlyElec NanoPi R2S
固件版本: OpenWrt SNAPSHOT r2993+618-b9a408c2b4
LuCI版本: git-20.223.26773-d18ef13-1
内核版本: 5.4.61
处理器架构: aarch64_cortex-a53

#此项在使用Tun模式时应为ACCEPT
防火墙转发: ACCEPT

#此项有值时建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: server

#此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 127.0.0.1#7874

#===================== 依赖检查 =====================#
dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
jsonfilter: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
iptables-mod-tproxy: 已安装
kmod-tun(TUN模式): 已安装
luci-compat(Luci-19.07): 已安装

#===================== 内核检查 =====================#
运行状态: 运行中
已选择的架构: linux-armv8

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 2020.09.05.gaf1a58d
Tun内核文件: 存在
Tun内核运行权限: 正常

Game内核版本: 
Game内核文件: 不存在
Game内核运行权限: 否

Dev内核版本: v1.1.0-13-g314ce1c
Dev内核文件: 存在
Dev内核运行权限: 正常

#===================== 插件设置 =====================#
当前配置文件: /etc/openclash/config/shadowsock.yaml
运行模式: fake-ip
默认代理模式: rule
UDP流量转发: 启用
DNS劫持: 启用
自定义DNS: 停用
IPV6-DNS解析: 停用
禁用Dnsmasq缓存: 停用
自定义规则: 停用
仅允许内网: 停用
仅代理命中规则流量: 停用

#启动异常时建议关闭此项后重试
保留配置: 停用
第三方规则: 停用

#===================== 配置文件 =====================#
port: 7890
socks-port: 7891
allow-lan: true
bind-address: "*"
ipv6: false
mode: rule
log-level: silent
external-controller: 0.0.0.0:9090
secret: "123456"
redir-port: 7892
external-ui: "/usr/share/openclash/dashboard"
dns:
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  listen: 127.0.0.1:7874
  enable: true
  ipv6: false
  fake-ip-filter:
##Custom fake-ip-filter##
  - '*.lan'
  - 'time.windows.com'
  - 'time.nist.gov'
  - 'time.apple.com'
  - 'time.asia.apple.com'
  - '*.ntp.org.cn'
  - '*.openwrt.pool.ntp.org'
  - 'time1.cloud.tencent.com'
  - 'time.ustc.edu.cn'
  - 'pool.ntp.org'
  - 'ntp.ubuntu.com'
  - 'ntp.aliyun.com'
  - 'ntp1.aliyun.com'
  - 'ntp2.aliyun.com'
  - 'ntp3.aliyun.com'
  - 'ntp4.aliyun.com'
  - 'ntp5.aliyun.com'
  - 'ntp6.aliyun.com'
  - 'ntp7.aliyun.com'
  - 'time1.aliyun.com'
  - 'time2.aliyun.com'
  - 'time3.aliyun.com'
  - 'time4.aliyun.com'
  - 'time5.aliyun.com'
  - 'time6.aliyun.com'
  - 'time7.aliyun.com'
  - '*.time.edu.cn'
  - 'time1.apple.com'
  - 'time2.apple.com'
  - 'time3.apple.com'
  - 'time4.apple.com'
  - 'time5.apple.com'
  - 'time6.apple.com'
  - 'time7.apple.com'
  - 'time1.google.com'
  - 'time2.google.com'
  - 'time3.google.com'
  - 'time4.google.com'
  - 'music.163.com'
  - '*.music.163.com'
  - '*.126.net'
  - 'musicapi.taihe.com'
  - 'music.taihe.com'
  - 'songsearch.kugou.com'
  - 'trackercdn.kugou.com'
  - '*.kuwo.cn'
  - 'api-jooxtt.sanook.com'
  - 'api.joox.com'
  - 'joox.com'
  - 'y.qq.com'
  - '*.y.qq.com'
  - 'streamoc.music.tc.qq.com'
  - 'mobileoc.music.tc.qq.com'
  - 'isure.stream.qqmusic.qq.com'
  - 'dl.stream.qqmusic.qq.com'
  - 'aqqmusic.tc.qq.com'
  - 'amobile.music.tc.qq.com'
  - '*.xiami.com'
  - '*.music.migu.cn'
  - 'music.migu.cn'
  - '*.msftconnecttest.com'
  - '*.msftncsi.com'
  - 'localhost.ptlogin2.qq.com'
  - '*.*.*.srv.nintendo.net'
  - '*.*.stun.playstation.net'
  - 'xbox.*.*.microsoft.com'
  - '*.*.xboxlive.com'
  - 'proxy.golang.org'
##Custom fake-ip-filter END##
  nameserver:
  - 114.114.114.114
  - 223.5.5.5
  fallback:
  - tls://dns.google
  fallback-filter:
    geoip: true
    ipcidr:
      - 0.0.0.0/8
      - 10.0.0.0/8
      - 100.64.0.0/10
      - 127.0.0.0/8
      - 169.254.0.0/16
      - 172.16.0.0/12
      - 192.0.0.0/24
      - 192.0.2.0/24
      - 192.88.99.0/24
      - 192.168.0.0/16
      - 198.18.0.0/15
      - 198.51.100.0/24
      - 203.0.113.0/24
      - 224.0.0.0/4
      - 240.0.0.0/4
      - 255.255.255.255/32

#===================== 防火墙设置 =====================#

#NAT chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    REDIRECT   tcp  --  0.0.0.0/0            8.8.4.4              redir ports 7892
2    REDIRECT   tcp  --  0.0.0.0/0            8.8.8.8              redir ports 7892
3    SS_SPEC_WAN_AC  tcp  --  0.0.0.0/0            0.0.0.0/0            /* _SS_SPEC_RULE_ */
4    REDIRECT   udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:53 redir ports 53
5    REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:53 redir ports 53
6    prerouting_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom prerouting rule chain */
7    zone_lan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
8    zone_wan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
9    zone_wan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
10   openclash  tcp  --  0.0.0.0/0            0.0.0.0/0           
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         
1    SS_SPEC_WAN_AC  tcp  --  0.0.0.0/0            0.0.0.0/0            /* _SS_SPEC_RULE_ */
2    openclash_output  tcp  --  0.0.0.0/0            0.0.0.0/0           

#Mangle chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    openclash  udp  --  0.0.0.0/0            0.0.0.0/0           
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         

#===================== 路由表状态 =====================#
#route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         61.144.144.1    0.0.0.0         UG    0      0        0 pppoe-wan
61.144.144.1    0.0.0.0         255.255.255.255 UH    0      0        0 pppoe-wan
192.168.2.0     0.0.0.0         255.255.255.0   U     0      0        0 br-lan
#ip route list
default via 61.144.144.1 dev pppoe-wan proto static 
61.144.144.1 dev pppoe-wan proto kernel scope link src 61.144.145.17 
192.168.2.0/24 dev br-lan proto kernel scope link src 192.168.2.1 
#ip rule show
0:	from all lookup local 
32765:	from all fwmark 0x162 lookup 354 
32766:	from all lookup main 
32767:	from all lookup default 

#===================== 端口占用状态 =====================#
tcp        0      0 :::9090                 :::*                    LISTEN      29164/clash
tcp        0      0 :::7890                 :::*                    LISTEN      29164/clash
tcp        0      0 :::7891                 :::*                    LISTEN      29164/clash
tcp        0      0 :::7892                 :::*                    LISTEN      29164/clash
udp        0      0 127.0.0.1:7874          0.0.0.0:*                           29164/clash
udp        0      0 :::56399                :::*                                29164/clash
udp        0      0 :::7891                 :::*                                29164/clash
udp        0      0 :::7892                 :::*                                29164/clash
udp        0      0 :::49928                :::*                                29164/clash
udp        0      0 :::39310                :::*                                29164/clash
udp        0      0 :::56808                :::*                                29164/clash

#===================== 测试本机DNS查询 =====================#
Server:		127.0.0.1
Address:	127.0.0.1#53

Name:      www.baidu.com
Address 1: 198.18.0.11
*** Can't find www.baidu.com: No answer

#===================== resolv.conf.auto =====================#
# Interface wan
nameserver 202.96.128.166
nameserver 202.96.134.133
# Interface wan_6
nameserver 240e:1f:1::1

#===================== 测试本机网络连接 =====================#
HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: private, no-cache, no-store, proxy-revalidate, no-transform
Connection: keep-alive
Content-Length: 277
Content-Type: text/html
Date: Fri, 11 Sep 2020 14:37:22 GMT
Etag: "575e1f6f-115"
Last-Modified: Mon, 13 Jun 2016 02:50:23 GMT
Pragma: no-cache
Server: bfe/1.0.8.18

#===================== 测试本机网络下载 =====================#
HTTP/1.1 200 Connection established

HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 78
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: text/plain; charset=utf-8
ETag: "640f85e49b4d138d32852f7196455da5aca9eb836586e731ca7060cdbc361ff2"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
Via: 1.1 varnish (Varnish/6.0)
X-GitHub-Request-Id: 9914:4BD4:17B53C:1B609E:5F5B79CF
Accept-Ranges: bytes
Date: Fri, 11 Sep 2020 14:37:23 GMT
Via: 1.1 varnish
X-Served-By: cache-hkg17920-HKG
X-Cache: HIT, HIT
X-Cache-Hits: 1, 3
X-Timer: S1599835043.070559,VS0,VE0
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
X-Fastly-Request-ID: c4ffa7f197394163e838dfb95fd838196fa2b863
Expires: Fri, 11 Sep 2020 14:42:23 GMT
Source-Age: 237

#===================== 最近运行日志 =====================#
2020-09-11 22:31:24 OpenClash Can Not Start, Please Check The Error Info And Try Again
2020-09-11 22:32:36 Config 【IPLC.VIP】 Update Successful
2020-09-11 22:32:36 Config 【DuangCloud】Update Error
time="2020-09-11T14:32:59Z" level=fatal msg="Parse config error: proxy group[0]: `use` or `proxies` missing"
2020-09-11 22:32:49 OpenClash Can Not Start, Please Check The Error Info And Try Again
2020-09-11 22:33:58 Config 【DuangCloud】Update Error
time="2020-09-11T14:34:52Z" level=fatal msg="Parse config error: proxy group[0]: `use` or `proxies` missing"
2020-09-11 22:34:43 OpenClash Can Not Start, Please Check The Error Info And Try Again
time="2020-09-11T14:35:26Z" level=info msg="Start initial compatible provider Auto"
time="2020-09-11T14:35:26Z" level=info msg="Start initial compatible provider Proxy"
2020-09-11 22:35:16 OpenClash Start Successful, Please Note That Network May Abnormal With IPV6's DHCP Server
2020-09-11 22:35:52 Config 【DuangCloud】Update Error

**Comment by vernesong** [comment]
直接上传能不能用？因为是本机下载而且你开启了IPV6但IPV6-DNS解析没开，所以有可能下载失败

**Comment by moekyo** [comment]
> 直接上传能不能用？因为是本机下载而且你开启了IPV6但IPV6-DNS解析没开，所以有可能下载失败

直接上传yaml文件可以使用，就是直接用节点订阅的话就会失败，【允许IPV6类型DNS解析】是设为停用的，奇怪的不是所有的地址都失败，有个Trojan的可以，失败的是ssr和V2Ray的

**Comment by vernesong** [comment]
第一次下载失败都会重试直连下载的，跟插件关系不大

**Comment by moekyo** [comment]
> 第一次下载失败都会重试直连下载的，跟插件关系不大
那可能是我的网络问题吧，还是手动上传配置文件好了
