### ISSUE TITLE
openclash开启后ddns获取的ip是openclash生成的ip

### ISSUE THREAD

**Issue by madman43** [vernesong/OpenClash#740]
openclash fake-ip混合，增强模式都试过，全是openclash生成的ip
以及访问国外网站不加载图片

105918       : last update: 2020-09-12 10:57
 105918       : Detect registered/public IP
 105918       : #> /usr/bin/nslookup zer00.ml  >/var/run/ddns/myddns_ipv4.dat 2>/var/run/ddns/myddns_ipv4.err
 105918       : Registered IP '198.18.0.2' detected
 105919  info : Starting main loop at 2020-09-12 10:59
 105919       : Detect local IP on 'interface'
 105919       : #> ip -o addr show dev eth0 scope global >/var/run/ddns/myddns_ipv4.dat 2>/var/run/ddns/myddns_ipv4.err
 105919       : Local IP '192.168.2.2' detected on interface 'eth0'
 105920       : Update needed - L: '192.168.2.2' <> R: '198.18.0.2'
 105920 ERROR : No or private or invalid IP '192.168.2.2' given! Please check your configuration
 105920 ERROR : No update send to DDNS Provider
 105920       : Waiting 600 seconds (Check Interval)
 110024       : Detect registered/public IP
 110024       : #> /usr/bin/nslookup zer00.ml  >/var/run/ddns/myddns_ipv4.dat 2>/var/run/ddns/myddns_ipv4.err
 110024       : Registered IP '198.18.0.2' detected
 110025  WARN : Updating IP at DDNS provider failed - starting retry 1/0
 110025       : Detect local IP on 'network'
 110025       : Local IP '192.168.2.2' detected on network 'lan'
 110025       : Update needed - L: '192.168.2.2' <> R: '198.18.0.2'
 110025 ERROR : No or private or invalid IP '192.168.2.2' given! Please check your configuration
 110026 ERROR : No update send to DDNS Provider
 110026       : Waiting 600 seconds (Check Interval)
 110428       : Detect registered/public IP
 110428       : #> /usr/bin/nslookup zer00.ml  >/var/run/ddns/myddns_ipv4.dat 2>/var/run/ddns/myddns_ipv4.err
 110429       : Registered IP '198.18.0.2' detected
 110429  WARN : Updating IP at DDNS provider failed - starting retry 1/0
 110429       : Detect local IP on 'network'
 110429       : Local IP '192.168.2.2' detected on network 'lan'
 110429       : Update needed - L: '192.168.2.2' <> R: '198.18.0.2'
 110430 ERROR : No or private or invalid IP '192.168.2.2' given! Please check your configuration
 110430 ERROR : No update send to DDNS Provider
 110430       : Waiting 600 seconds (Check Interval)
![image](https://user-images.githubusercontent.com/19260034/92985825-d7e63600-f4e8-11ea-8bfa-c8eb65c5b7ea.png)
![image](https://user-images.githubusercontent.com/19260034/92985834-e9c7d900-f4e8-11ea-975b-76df9d2f3676.png)
![image](https://user-images.githubusercontent.com/19260034/92985850-09f79800-f4e9-11ea-9962-66f41de99774.png)
![image](https://user-images.githubusercontent.com/19260034/92985854-12e86980-f4e9-11ea-9952-5b2b628db091.png)

OpenClash 调试日志

生成时间: 2020-09-12 11:14:24
插件版本: v0.40.2-beta

#===================== 系统信息 =====================#
主机型号: 
固件版本: OpenWrt SNAPSHOT r2852-075090c4d
LuCI版本: git-20.223.26773-d18ef13-1
内核版本: 5.7.15-flippy-41+
处理器架构: aarch64_generic

#此项在使用Tun模式时应为ACCEPT
防火墙转发: ACCEPT

#此项有值时建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: hybrid

#此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 127.0.0.1#7874

#===================== 依赖检查 =====================#
dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
jsonfilter: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
iptables-mod-tproxy: 已安装
kmod-tun(TUN模式): 已安装
luci-compat(Luci-19.07): 已安装

#===================== 内核检查 =====================#
运行状态: 运行中
已选择的架构: linux-armv8

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 2020.09.05.gaf1a58d
Tun内核文件: 存在
Tun内核运行权限: 正常

Game内核版本: v0.17.0-194-gbe86985
Game内核文件: 存在
Game内核运行权限: 正常

Dev内核版本: v1.1.0-13-g314ce1c
Dev内核文件: 存在
Dev内核运行权限: 正常

#===================== 插件设置 =====================#
当前配置文件: /etc/openclash/config/freemy.yaml
运行模式: fake-ip-mix
默认代理模式: rule
UDP流量转发: 停用
DNS劫持: 启用
自定义DNS: 启用
IPV6-DNS解析: 启用
禁用Dnsmasq缓存: 启用
自定义规则: 停用
仅允许内网: 停用
仅代理命中规则流量: 启用

#启动异常时建议关闭此项后重试
保留配置: 停用

#启动异常时建议关闭此项后重试
第三方规则: lhie1
第三方规则策略组设置:
GlobalTV: ♻️ 自动选择
AsianTV: ♻️ 自动选择
Proxy: ♻️ 自动选择
Apple: 🎯 全球直连
Netflix: 🚀 节点选择
Spotify: 🚀 节点选择
Steam: 🎯 全球直连
AdBlock: REJECT
Netease Music: 🚀 节点选择
Speedtest: 🚀 节点选择
Telegram: 📲 电报信息
Microsoft: 🎯 全球直连
PayPal: 🚀 节点选择
Domestic: DIRECT
Others: 🎯 全球直连

读取的配置文件策略组:
🚀 节点选择
♻️ 自动选择
🌍 国外媒体
📲 电报信息
Ⓜ️ 微软服务
🍎 苹果服务
📢 谷歌FCM
🎯 全球直连
🛑 全球拦截
🍃 应用净化
🐟 漏网之鱼
DIRECT
REJECT

#===================== 配置文件 =====================#
port: 7890
socks-port: 7891
allow-lan: true
bind-address: "*"
ipv6: true
mode: rule
log-level: silent
external-controller: 0.0.0.0:9090
redir-port: 7892
secret: "123456"
external-ui: "/usr/share/openclash/dashboard"
tun:
  enable: true
  stack: gvisor
  dns-hijack:
  - tcp://8.8.8.8:53
  - tcp://8.8.4.4:53
dns:
  enable: true
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  listen: 0.0.0.0:7874
  fake-ip-filter:
##Custom fake-ip-filter##
  - '*.lan'
  - 'time.windows.com'
  - 'time.nist.gov'
  - 'time.apple.com'
  - 'time.asia.apple.com'
  - '*.ntp.org.cn'
  - '*.openwrt.pool.ntp.org'
  - 'time1.cloud.tencent.com'
  - 'time.ustc.edu.cn'
  - 'pool.ntp.org'
  - 'ntp.ubuntu.com'
  - 'ntp.aliyun.com'
  - 'ntp1.aliyun.com'
  - 'ntp2.aliyun.com'
  - 'ntp3.aliyun.com'
  - 'ntp4.aliyun.com'
  - 'ntp5.aliyun.com'
  - 'ntp6.aliyun.com'
  - 'ntp7.aliyun.com'
  - 'time1.aliyun.com'
  - 'time2.aliyun.com'
  - 'time3.aliyun.com'
  - 'time4.aliyun.com'
  - 'time5.aliyun.com'
  - 'time6.aliyun.com'
  - 'time7.aliyun.com'
  - '*.time.edu.cn'
  - 'time1.apple.com'
  - 'time2.apple.com'
  - 'time3.apple.com'
  - 'time4.apple.com'
  - 'time5.apple.com'
  - 'time6.apple.com'
  - 'time7.apple.com'
  - 'time1.google.com'
  - 'time2.google.com'
  - 'time3.google.com'
  - 'time4.google.com'
  - 'music.163.com'
  - '*.music.163.com'
  - '*.126.net'
  - 'musicapi.taihe.com'
  - 'music.taihe.com'
  - 'songsearch.kugou.com'
  - 'trackercdn.kugou.com'
  - '*.kuwo.cn'
  - 'api-jooxtt.sanook.com'
  - 'api.joox.com'
  - 'joox.com'
  - 'y.qq.com'
  - '*.y.qq.com'
  - 'streamoc.music.tc.qq.com'
  - 'mobileoc.music.tc.qq.com'
  - 'isure.stream.qqmusic.qq.com'
  - 'dl.stream.qqmusic.qq.com'
  - 'aqqmusic.tc.qq.com'
  - 'amobile.music.tc.qq.com'
  - '*.xiami.com'
  - '*.music.migu.cn'
  - 'music.migu.cn'
  - '*.msftconnecttest.com'
  - '*.msftncsi.com'
  - 'localhost.ptlogin2.qq.com'
  - '*.*.*.srv.nintendo.net'
  - '*.*.stun.playstation.net'
  - 'xbox.*.*.microsoft.com'
  - '*.*.xboxlive.com'
##Custom fake-ip-filter END##
##Custom DNS##
  nameserver:
  - 127.0.0.1:1053
  - tcp://127.0.0.1:1053
  - tls://127.0.0.1:1053
  - https://127.0.0.1:1053

#===================== 防火墙设置 =====================#

#NAT chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    ACCEPT     tcp  --  0.0.0.0/0            8.8.4.4             
2    ACCEPT     tcp  --  0.0.0.0/0            8.8.8.8             
3    CLOUD_MUSIC  tcp  --  0.0.0.0/0            0.0.0.0/0            match-set music dst
4    REDIRECT   udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:53 redir ports 1053
5    REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:53 redir ports 1053
6    prerouting_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom prerouting rule chain */
7    zone_lan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
8    openclash  tcp  --  0.0.0.0/0            0.0.0.0/0           
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         
1    openclash_output  tcp  --  0.0.0.0/0            0.0.0.0/0           

#Mangle chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    openclash  udp  --  0.0.0.0/0            0.0.0.0/0           
2    openclash_dns_hijack  tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:53
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         

#===================== 路由表状态 =====================#
#route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.2.1     0.0.0.0         UG    0      0        0 eth0
172.30.32.0     0.0.0.0         255.255.254.0   U     0      0        0 hassio
172.31.0.0      0.0.0.0         255.255.255.0   U     0      0        0 docker0
192.168.2.0     0.0.0.0         255.255.255.0   U     0      0        0 eth0
198.18.0.0      0.0.0.0         255.255.0.0     U     0      0        0 utun
#ip route list
default via 192.168.2.1 dev eth0 proto static 
172.30.32.0/23 dev hassio proto kernel scope link src 172.30.32.1 
172.31.0.0/24 dev docker0 proto kernel scope link src 172.31.0.1 
192.168.2.0/24 dev eth0 proto kernel scope link src 192.168.2.2 
198.18.0.0/16 dev utun proto kernel scope link src 198.18.0.1 
#ip rule show
0:	from all lookup local
32765:	from all fwmark 0x162 lookup 354
32766:	from all lookup main
32767:	from all lookup default

#===================== Tun设备状态 =====================#
utun: tun pi filter

#===================== 端口占用状态 =====================#
tcp        0      0 :::7890                 :::*                    LISTEN      11527/clash
tcp        0      0 :::7891                 :::*                    LISTEN      11527/clash
tcp        0      0 :::7892                 :::*                    LISTEN      11527/clash
tcp        0      0 :::9090                 :::*                    LISTEN      11527/clash
udp        0      0 :::56340                :::*                                11527/clash
udp        0      0 :::45090                :::*                                11527/clash
udp        0      0 :::51517                :::*                                11527/clash
udp        0      0 :::56638                :::*                                11527/clash
udp        0      0 :::60889                :::*                                11527/clash
udp        0      0 :::56991                :::*                                11527/clash
udp        0      0 :::7874                 :::*                                11527/clash
udp        0      0 :::7891                 :::*                                11527/clash
udp        0      0 :::7892                 :::*                                11527/clash

#===================== 测试本机DNS查询 =====================#
Server:		127.0.0.1
Address:	127.0.0.1#53

Name:      www.baidu.com
Address 1: 198.18.0.3
*** Can't find www.baidu.com: No answer

#===================== resolv.conf.d =====================#
# Interface lan
nameserver 192.168.2.1
# Interface lan6
nameserver 240e:399:262:
nameserver fe80::3646:ecff:fe99:8e26%eth0

#===================== 测试本机网络连接 =====================#
HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: private, no-cache, no-store, proxy-revalidate, no-transform
Connection: keep-alive
Content-Length: 277
Content-Type: text/html
Date: Sat, 12 Sep 2020 03:14:26 GMT
Etag: "575e1f72-115"
Last-Modified: Mon, 13 Jun 2016 02:50:26 GMT
Pragma: no-cache
Server: bfe/1.0.8.18

#===================== 测试本机网络下载 =====================#
HTTP/1.1 200 Connection established

HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 78
Content-Type: text/plain; charset=utf-8
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
ETag: "640f85e49b4d138d32852f7196455da5aca9eb836586e731ca7060cdbc361ff2"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
Via: 1.1 varnish (Varnish/6.0)
X-GitHub-Request-Id: A38E:3A0C:13B9F2:159CBB:5F5C376A
Accept-Ranges: bytes
Date: Sat, 12 Sep 2020 03:14:28 GMT
Via: 1.1 varnish
X-Served-By: cache-tyo19922-TYO
X-Cache: MISS, HIT
X-Cache-Hits: 0, 1
X-Timer: S1599880468.387474,VS0,VE258
Vary: Authorization,Accept-Encoding, Accept-Encoding
Access-Control-Allow-Origin: *
X-Fastly-Request-ID: be5d01db87b5dc476c802fa18f3aac546e036fcd
Expires: Sat, 12 Sep 2020 03:19:28 GMT
Source-Age: 0

#===================== 最近运行日志 =====================#
time="2020-09-12T11:11:51+08:00" level=info msg="Start initial compatible provider 🎯 全球直连"
time="2020-09-12T11:11:51+08:00" level=info msg="Start initial compatible provider 🍎 苹果服务"
time="2020-09-12T11:11:51+08:00" level=info msg="Start initial compatible provider 📢 谷歌FCM"
time="2020-09-12T11:11:51+08:00" level=info msg="Start initial compatible provider Ⓜ️ 微软服务"
time="2020-09-12T11:11:51+08:00" level=info msg="Start initial compatible provider 📲 电报信息"
time="2020-09-12T11:11:51+08:00" level=info msg="Start initial compatible provider ♻️ 自动选择"
time="2020-09-12T11:11:51+08:00" level=info msg="Start initial compatible provider 🚀 节点选择"
time="2020-09-12T11:11:51+08:00" level=info msg="Start initial compatible provider 🌍 国外媒体"
time="2020-09-12T11:11:51+08:00" level=info msg="Start initial compatible provider 🛑 全球拦截"
time="2020-09-12T11:11:51+08:00" level=info msg="Start initial compatible provider 🍃 应用净化"
time="2020-09-12T11:11:51+08:00" level=info msg="Start initial compatible provider 🐟 漏网之鱼"
time="2020-09-12T11:11:51+08:00" level=info msg="DNS server listening at: 127.0.0.1:7874"
2020-09-12 11:11:39 OpenClash Start Successful, Please Note That Network May Abnormal With IPV6's DHCP Server
time="2020-09-12T11:13:30+08:00" level=info msg="Start initial compatible provider ♻️ 自动选择"
time="2020-09-12T11:13:30+08:00" level=info msg="Start initial compatible provider 🚀 节点选择"
time="2020-09-12T11:13:30+08:00" level=info msg="Start initial compatible provider 🎯 全球直连"
time="2020-09-12T11:13:30+08:00" level=info msg="Start initial compatible provider 🍃 应用净化"
time="2020-09-12T11:13:30+08:00" level=info msg="Start initial compatible provider Ⓜ️ 微软服务"
time="2020-09-12T11:13:30+08:00" level=info msg="Start initial compatible provider 🐟 漏网之鱼"
time="2020-09-12T11:13:30+08:00" level=info msg="Start initial compatible provider 📢 谷歌FCM"
time="2020-09-12T11:13:30+08:00" level=info msg="Start initial compatible provider 🍎 苹果服务"
time="2020-09-12T11:13:30+08:00" level=info msg="Start initial compatible provider 🛑 全球拦截"
time="2020-09-12T11:13:30+08:00" level=info msg="Start initial compatible provider 🌍 国外媒体"
time="2020-09-12T11:13:30+08:00" level=info msg="Start initial compatible provider 📲 电报信息"
time="2020-09-12T11:13:30+08:00" level=info msg="DNS server listening at: 0.0.0.0:7874"
2020-09-12 11:13:18 OpenClash Start Successful, Please Note That Network May Abnormal With IPV6's DHCP Server

**Comment by vernesong** [comment]
DNS高级设置，不加载图片你要看走没走代理，一般是规则不全

**Comment by madman43** [comment]
> DNS高级设置，不加载图片你要看走没走代理，一般是规则不全

dns高级设置是停用的，规则我重新换了一个
![image](https://user-images.githubusercontent.com/19260034/92988811-71214680-f501-11ea-9e20-2f6e23e3c2b7.png)

**Comment by madman43** [comment]
openclash里面自定义dns指向了agh，目前agh里面查询日志都是正常的，
![image](https://user-images.githubusercontent.com/19260034/92988970-1be63480-f503-11ea-89df-5e24a8010e15.png)

**Comment by madman43** [comment]
![image](https://user-images.githubusercontent.com/19260034/92989115-35d44700-f504-11ea-9c06-ccab9b984456.png)
好像是大量的超时以及直连规则……，但YouTube确实打开了，能看视频，就是其他加载不出来，也没预览图

**Comment by vernesong** [comment]
adg劫持dns了没有，目前客户端的查询请求没到clash那去才会这样

**Comment by madman43** [comment]
> adg劫持dns了没有，目前客户端的查询请求没到clash那去才会这样

防火墙里是这个规则指向到agh上
iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 1053
iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 1053

**Comment by madman43** [comment]
我好像已经发现问题了。停用openclash所有关于dns的功能就解决了……

**Comment by vernesong** [comment]
你搞清楚DNS应该是clash返回给客户端再去折腾

**Comment by nevertoday** [comment]
这几天突然都不欧克了， 很是没辙~

**Comment by skinnyshy** [comment]
openclash →  覆写设置 → DNS设置 → Fake-IP-Filter  ，配置要放行的域名即可
