### ISSUE TITLE
关于Fake-IP模式下使用GEOIP匹配的问题

### ISSUE THREAD

**Issue by Sanly** [vernesong/OpenClash#741]
我在规则集中设置了一条规则：”- GEOIP,CN“，规则集的规则为“DIRECT”。但在Fake-IP模式下，我发现域名并不会被解析，只会去适用域名规则，由于域名规则并不全面，导致像“360.cn”这样的域名也会走代理。不知道有没有办法对于域名进行解析后匹配GEOIP然后适用相应规则？

**Comment by vernesong** [comment]
规则里面有的域名不解析，没有的域名才会解析DNS

**Comment by Sanly** [comment]
这个我明白，我现在用的以下脚本：

script:
  code: |
    def main(ctx, metadata):
        port_list = [21, 22, 23, 53, 123, 194, 587, 465, 995, 993, 143, 80, 443, 2052, 2053, 2082, 2083, 2086, 2095, 2096, 5228, 5229, 5230, 8080, 8443, 8880]
        ruleset_action = {"Reject Domains": "AD Block",
            "Reject IPs": "AD Block",
            "Netease Music Domains": "Netease Music",
            "Stream Services Domains": "Stream Services",
            "Stream Services IPs": "Stream Services",
            "Global Services Domains": "Proxy",
            "Global Services IPs": "Proxy",
            "Apple Services Domains": "Apple Services",
            "Domestic Services Domains": "Domestic",
            "Domestic Services IPs": "Domestic",
            "Internal": "DIRECT",
            "Local": "DIRECT"
            }
        port = int(metadata["dst_port"])

        if port not in port_list:
            return "DIRECT"

        for rule_name in ctx.rule_providers.keys():
            if ctx.rule_providers[rule_name].match(metadata):
                return ruleset_action[rule_name]

        return "Proxy"

“Local”是我自己添加的规则集，里面有规则”- GEOIP,CN“，希望达到的效果就是如果"Domestic Services Domains"中的域名不含该的域名，进行解析后匹配GEOIP，然后走"DIRECT"。但结果发现类似“360.cn”这样的域名，在"Domestic Services Domains"中没有，但也不会在“Local”规则集下进行解析去匹配GEOIP。

**Comment by vernesong** [comment]
```
script:
code: |
def main(ctx, metadata):
port_list = [21, 22, 23, 53, 123, 194, 587, 465, 995, 993, 143, 80, 443, 2052, 2053, 2082, 2083, 2086, 2095, 2096, 5228, 5229, 5230, 8080, 8443, 8880]
ruleset_action = {"Reject Domains": "AD Block",
"Reject IPs": "AD Block",
"Netease Music Domains": "Netease Music",
"Stream Services Domains": "Stream Services",
"Stream Services IPs": "Stream Services",
"Global Services Domains": "Proxy",
"Global Services IPs": "Proxy",
"Apple Services Domains": "Apple Services",
"Domestic Services Domains": "Domestic",
"Domestic Services IPs": "Domestic",
"Internal": "DIRECT",
"Local": "DIRECT"
}
port = int(metadata["dst_port"])
if port not in port_list:
  return "DIRECT"

for rule_name in ctx.rule_providers.keys():
  if ctx.rule_providers[rule_name].match(metadata):
    return ruleset_action[rule_name]

ip = metadata["dst_ip"] or ctx.resolve_ip(metadata["host"])

if ip == "":
   return "DIRECT"

code = ctx.geoip(ip)
if code == "LAN":
  return "DIRECT"

if code == "CN":
  return "DIRECT"

return "Proxy"
```

**Comment by Sanly** [comment]
搞定，多谢V大。

代码中有：

        if ip == "":
            return "DIRECT"

会导致“饿了吗”首页连不上网，删了就OK了。
