### ISSUE TITLE
怎么现在第三方规则都需要tun内核

### ISSUE THREAD

**Issue by kimcnc** [vernesong/OpenClash#748]
能不能添加需要tun内核的第三方规则

**Comment by vernesong** [comment]
只装一个tun内核就行

**Comment by kimcnc** [comment]
主要是两个原因，我固件没自带kmod-tun，而且路由器容量太小，装不下tun内核。

**Comment by vernesong** [comment]
tun内核我已经压缩过了，你用普通模式也不需要装kmod-tun，仅仅是因为只有tun内核支持rule-set

**Comment by kimcnc** [comment]
我现在用增强模式，怎么才能用第三方规则而不用tun内核

**Comment by vernesong** [comment]
2楼不是说了吗
