### ISSUE TITLE
OpenClash 无法启动，提示 unsupported rule type PROCESS-NAME

### ISSUE THREAD

**Issue by suzanneeound** [vernesong/OpenClash#749]
客户端版本是v0.40.3, Clash 内核已升级至 v1.1.0-13-g314ce1c 
启动OpenClash 后，主页面提示，错误：规则集文件下载失败，请到日志页面查看详细错误信息。
运行日志中提示：Parse config error: initial rule provider Apple error: unsupported rule type PROCESS-NAME

请问，如何正确配置？

**Comment by vernesong** [comment]
提示是用的dev内核吗

**Comment by suzanneeound** [comment]
更新clash_tun内核后，问题解决了。谢谢。
