### ISSUE TITLE
一个摸不着头脑的问题(启动失败)

### ISSUE THREAD

**Issue by phantastar** [vernesong/OpenClash#75]
### 系统版本
Openwrt X86_64原版18.06.5
### 内核版本
v0.16.0-17-g3b0cc85
### 客户端版本
v0.35.5-beta
### 问题描述
尝试启动OpenClash永远会被提示"_**错误: OpenClash 启动失败，请到日志页面查看详细错误信息！**_"
**服务器日志如下**

> 2019-11-23 20:17:59 Config Update Successful
time="2019-11-23T12:19:09Z" level=fatal msg="Parse config error: ProxyGroup Auto - UrlTest: key 'proxies' missing"
2019-11-23 20:19:08 OpenClash Can Not Start, Please Check The Error Info And Try Again

经过数次重新订阅配置和第三方规则后也无法解决, 
配置文件内是这么写的: 

> Proxy Group:
- name: Auto - UrlTest
  type: load-balance
  proxies:
  url: http://www.gstatic.com/generate_204
  interval: "600"
- name: Proxy
  type: select
  proxies:
  - Auto - UrlTest
  - DIRECT
- name: Domestic
  type: select
  proxies:
  - DIRECT
  - Proxy
- name: Others
  type: select
  proxies:
  - Proxy
  - DIRECT
  - Domestic
- name: AdBlock
  type: select
  proxies:
  - REJECT
  - DIRECT
  - Proxy
- name: AsianTV
  type: select
  proxies:
  - DIRECT
  - Proxy
- name: GlobalTV
  type: select
  proxies:
  - Proxy
  - DIRECT

### 其他(可能)相关信息

1. 第三方规则未启用. 

2." 服务器&策略组管理"未作改动. 

3. 配置文件未作改动. 

4. 启动参数检查（配置文件） | 检查通过

5. 配置文件更新日期 | 2019-11-23 20:18:36

6. 四个IP状态全部显示本省市地址.

**Comment by vernesong** [comment]
```
name: Auto - UrlTest
type: load-balance
proxies:
url: http://www.gstatic.com/generate_204
interval: "600"
```
这个策略组`proxies:`没有指定服务器或其他策略组，启动失败

**Comment by phantastar** [comment]
> ```
> name: Auto - UrlTest
> type: load-balance
> proxies:
> url: http://www.gstatic.com/generate_204
> interval: "600"
> ```
> 
> 这个策略组`proxies:`没有指定服务器或其他策略组，启动失败

那么请问我是该去“服务器&策略组管理”挨个编辑服务器吗？

**Comment by vernesong** [comment]
订阅的配置文件原本就没有就需要本地修改，有就需要你关闭并删除“服务器&策略组管理”页面的所有配置并重新订阅

**Comment by phantastar** [comment]
> 订阅的配置文件原本就没有就需要本地修改，有就需要你关闭并删除“服务器&策略组管理”页面的所有配置并重新订阅

经过几小时前重置路由器并重新安装OpenClash后也验证了您的说法, 谢谢您的回复^
