### ISSUE TITLE
自动更新geoip会导致无法连接proxy

### ISSUE THREAD

**Issue by ABXYvvv** [vernesong/OpenClash#750]
打开自动更新geoip，每次在搜索更新geoip后守护程序会关闭，然后无法连接proxy。

在全局设置-GEOIP数据库订阅：
自动更新：启用
更新时间（每周）：每天
更新时间（每天）：0：00

搜索更新后显示更新成功，然后openclash会重启，然后openclash守护程序：未运行。
openclash版本v0.40.4  所有内核全更新最新。

**Comment by cdzyp520** [comment]
跟你的故障一样，守护程序关闭还同时会出现无法停用第三方规则，删除服务器节点的问题怎么设置都不能删除，也无法启动前天就遇到这个问题，我还以为是我哪里设置不对，现在都不敢更新geoip

**Comment by vernesong** [comment]
守护程序就算没启动也应该能够正常使用，只可能是启动脚本没走完就出错退出，如果日志没有报错建议你把配置文件发出来

**Comment by ABXYvvv** [comment]
OpenClash 调试日志

生成时间: 2020-09-15 00:13:21
插件版本: v0.40.4-beta

#===================== 系统信息 =====================#
主机型号: Intel(R) Celeron(R) CPU 3965U @ 2.20GHz : 2 Core 2 Thread
固件版本: OpenWrt SNAPSHOT r0-4bc7b28
LuCI版本: git-20.223.26773-d18ef13-1
内核版本: 4.19.123
处理器架构: x86_64

#此项在使用Tun模式时应为ACCEPT
防火墙转发: ACCEPT

#此项有值时建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: 

#此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 127.0.0.1#7874

#===================== 依赖检查 =====================#
dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
jsonfilter: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
iptables-mod-tproxy: 已安装
kmod-tun(TUN模式): 未安装
luci-compat(Luci-19.07): 已安装

#===================== 内核检查 =====================#
运行状态: 运行中
已选择的架构: linux-amd64

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 2020.09.13.g3dc8802
Tun内核文件: 存在
Tun内核运行权限: 正常

Game内核版本: v0.17.0-194-gbe86985
Game内核文件: 存在
Game内核运行权限: 正常

Dev内核版本: v1.1.0-13-g314ce1c
Dev内核文件: 存在
Dev内核运行权限: 正常

#===================== 插件设置 =====================#
当前配置文件: /etc/openclash/config/openclash.yaml
运行模式: redir-host-mix
默认代理模式: rule
UDP流量转发: 停用
DNS劫持: 启用
自定义DNS: 停用
IPV6-DNS解析: 停用
禁用Dnsmasq缓存: 启用
自定义规则: 停用
仅允许内网: 停用
仅代理命中规则流量: 停用
绕过中国大陆IP: 启用

#启动异常时建议关闭此项后重试
保留配置: 停用
第三方规则: 停用

#===================== 配置文件 =====================#
redir-port: 7892
port: 7890
socks-port: 7891
ipv6: false
mode: rule
log-level: silent
external-controller: 0.0.0.0:9090
secret: "123456"
allow-lan: true
bind-address: "*"
external-ui: "/usr/share/openclash/dashboard"
tun:
  enable: true
  stack: system
  dns-hijack:
  - tcp://8.8.8.8:53
  - tcp://8.8.4.4:53
hosts:
##Custom HOSTS##
#  experimental hosts, support wildcard (e.g. *.clash.dev Even *.foo.*.example.com)
#  static domain has a higher priority than wildcard domain (foo.example.com > *.example.com)
#  NOTE: hosts don't work with `fake-ip`

#  '*.clash.dev': 127.0.0.1
#  'alpha.clash.dev': '::1'
##Custom HOSTS END##
dns:
  use-hosts: true
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 127.0.0.1:7874
  nameserver:
  - 114.114.114.114
  - 119.29.29.29
  - https://doh.rixcloud.dev/dns-query
  fallback:
  - https://cloudflare-dns.com/dns-query
  - https://dns.google/dns-query
  - https://1.1.1.1/dns-query
  - tls://8.8.8.8:853
  fallback-filter:
    geoip: true
    ipcidr:
      - 0.0.0.0/8
      - 10.0.0.0/8
      - 100.64.0.0/10
      - 127.0.0.0/8
      - 169.254.0.0/16
      - 172.16.0.0/12
      - 192.0.0.0/24
      - 192.0.2.0/24
      - 192.88.99.0/24
      - 192.168.0.0/16
      - 198.18.0.0/15
      - 198.51.100.0/24
      - 203.0.113.0/24
      - 224.0.0.0/4
      - 240.0.0.0/4
      - 255.255.255.255/32

#===================== 防火墙设置 =====================#

#NAT chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    ACCEPT     tcp  --  0.0.0.0/0            8.8.4.4             
2    ACCEPT     tcp  --  0.0.0.0/0            8.8.8.8             
3    REDIRECT   udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:53 redir ports 53
4    REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:53 redir ports 53
5    prerouting_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom prerouting rule chain */
6    zone_lan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
7    zone_wan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
8    zone_wan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
9    openclash  tcp  --  0.0.0.0/0            0.0.0.0/0           
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         

#Mangle chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    openclash  udp  --  0.0.0.0/0            0.0.0.0/0           
2    openclash_dns_hijack  tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:53
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         
1    RRDIPT_OUTPUT  all  --  0.0.0.0/0            0.0.0.0/0           

#===================== 路由表状态 =====================#
#route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         100.64.0.1      0.0.0.0         UG    0      0        0 pppoe-wan
100.64.0.1      0.0.0.0         255.255.255.255 UH    0      0        0 pppoe-wan
192.168.1.0     0.0.0.0         255.255.255.0   U     0      0        0 br-lan
#ip route list
default via 100.64.0.1 dev pppoe-wan proto static 
100.64.0.1 dev pppoe-wan proto kernel scope link src 100.64.0.3 
192.168.1.0/24 dev br-lan proto kernel scope link src 192.168.1.1 
#ip rule show
0:	from all lookup local 
32765:	from all fwmark 0x162 lookup 354 
32766:	from all lookup main 
32767:	from all lookup default 

#===================== Tun设备状态 =====================#

#===================== 端口占用状态 =====================#
tcp        0      0 :::9090                 :::*                    LISTEN      21815/clash
tcp        0      0 :::7890                 :::*                    LISTEN      21815/clash
tcp        0      0 :::7891                 :::*                    LISTEN      21815/clash
tcp        0      0 :::7892                 :::*                    LISTEN      21815/clash
udp        0      0 127.0.0.1:7874          0.0.0.0:*                           21815/clash
udp        0      0 :::7891                 :::*                                21815/clash
udp        0      0 :::7892                 :::*                                21815/clash

#===================== 测试本机DNS查询 =====================#
Server:		127.0.0.1
Address:	127.0.0.1#53

Name:      www.baidu.com
www.baidu.com	canonical name = www.a.shifen.com
Name:      www.a.shifen.com
Address 1: 14.215.177.39
Address 2: 14.215.177.38
*** Can't find www.baidu.com: No answer

#===================== resolv.conf.auto =====================#
# Interface wan
nameserver 202.96.128.86
nameserver 202.96.134.33

#===================== 测试本机网络连接 =====================#
HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: private, no-cache, no-store, proxy-revalidate, no-transform
Connection: keep-alive
Content-Length: 277
Content-Type: text/html
Date: Mon, 14 Sep 2020 16:13:21 GMT
Etag: "575e1f72-115"
Last-Modified: Mon, 13 Jun 2016 02:50:26 GMT
Pragma: no-cache
Server: bfe/1.0.8.18


#===================== 测试本机网络下载 =====================#
HTTP/1.1 200 Connection established

HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 78
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: text/plain; charset=utf-8
ETag: "f33f76b7c2036f06901d0623c3f96a4fab0edf76f9d8de884dadbec1f5d4750f"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
Via: 1.1 varnish (Varnish/6.0)
X-GitHub-Request-Id: 63A0:31C9:450044:503664:5F5F8959
Accept-Ranges: bytes
Date: Mon, 14 Sep 2020 16:13:21 GMT
Via: 1.1 varnish
X-Served-By: cache-hkg17921-HKG
X-Cache: HFM, HIT
X-Cache-Hits: 0, 2
X-Timer: S1600100002.823543,VS0,VE0
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
X-Fastly-Request-ID: 6e0e0b6501d9daec51a6d41238a6bf138b84db28
Expires: Mon, 14 Sep 2020 16:18:21 GMT
Source-Age: 157


#===================== 最近运行日志 =====================#
time="2020-09-13T17:27:49Z" level=info msg="Start initial compatible provider Netflix"
time="2020-09-13T17:27:49Z" level=info msg="Start initial compatible provider AdBlock"
time="2020-09-13T17:27:49Z" level=info msg="Start initial compatible provider Proxy2"
time="2020-09-13T17:27:49Z" level=info msg="Start initial compatible provider Proxy1"
time="2020-09-13T17:27:49Z" level=info msg="Start initial compatible provider Global"
time="2020-09-13T17:27:49Z" level=info msg="Start initial compatible provider Domestic"
time="2020-09-13T17:27:49Z" level=info msg="Start initial compatible provider Apple_API"
time="2020-09-13T17:27:49Z" level=info msg="Start initial compatible provider Apple_CDN"
time="2020-09-13T17:27:49Z" level=info msg="Start initial compatible provider Proxy4"
time="2020-09-13T17:27:49Z" level=info msg="Start initial compatible provider Proxy3"
time="2020-09-13T17:27:49Z" level=info msg="Start initial compatible provider AsianMedia"
time="2020-09-13T17:27:49Z" level=info msg="Start initial compatible provider PayPal"
time="2020-09-13T17:27:49Z" level=info msg="Start initial compatible provider GlobalMedia"
time="2020-09-13T17:27:49Z" level=info msg="DNS server listening at: 127.0.0.1:7874"
2020-09-14 01:27:42 OpenClash Start Successful
time="2020-09-13T17:28:37Z" level=info msg="Start initial compatible provider AdBlock"
time="2020-09-13T17:28:37Z" level=info msg="Start initial compatible provider Proxy4"
time="2020-09-13T17:28:37Z" level=info msg="Start initial compatible provider Proxy3"
time="2020-09-13T17:28:37Z" level=info msg="Start initial compatible provider Proxy1"
time="2020-09-13T17:28:37Z" level=info msg="Start initial compatible provider PayPal"
time="2020-09-13T17:28:37Z" level=info msg="Start initial compatible provider Netflix"
time="2020-09-13T17:28:37Z" level=info msg="Start initial compatible provider AsianMedia"
time="2020-09-13T17:28:37Z" level=info msg="Start initial compatible provider Apple_CDN"
time="2020-09-13T17:28:37Z" level=info msg="Start initial compatible provider Proxy2"
time="2020-09-13T17:28:37Z" level=info msg="Start initial compatible provider Global"
time="2020-09-13T17:28:37Z" level=info msg="Start initial compatible provider Domestic"
time="2020-09-13T17:28:37Z" level=info msg="Start initial compatible provider Apple_API"
time="2020-09-13T17:28:37Z" level=info msg="Start initial compatible provider GlobalMedia"
time="2020-09-13T17:28:37Z" level=info msg="DNS server listening at: 127.0.0.1:7874"
2020-09-14 01:28:31 OpenClash Start Successful

**Comment by ABXYvvv** [comment]
OpenClash 调试日志

生成时间: 2020-09-15 01:26:54
插件版本: v0.40.4-beta

#===================== 系统信息 =====================#
主机型号: Intel(R) Celeron(R) CPU 3965U @ 2.20GHz : 2 Core 2 Thread
固件版本: OpenWrt SNAPSHOT r0-eaf0770
LuCI版本: git-20.256.12360-1a54222-1
内核版本: 4.19.123
处理器架构: x86_64

#此项在使用Tun模式时应为ACCEPT
防火墙转发: ACCEPT

#此项有值时建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: 

#此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 127.0.0.1#7874

#===================== 依赖检查 =====================#
dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
jsonfilter: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
iptables-mod-tproxy: 已安装
kmod-tun(TUN模式): 已安装
luci-compat(Luci-19.07): 已安装

#===================== 内核检查 =====================#
运行状态: 运行中
已选择的架构: linux-amd64

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 2020.09.13.g3dc8802
Tun内核文件: 存在
Tun内核运行权限: 正常

Game内核版本: v0.17.0-194-gbe86985
Game内核文件: 存在
Game内核运行权限: 正常

Dev内核版本: v1.1.0-13-g314ce1c
Dev内核文件: 存在
Dev内核运行权限: 正常

#===================== 插件设置 =====================#
当前配置文件: /etc/openclash/config/openclash.yaml
运行模式: redir-host-mix
默认代理模式: rule
UDP流量转发: 停用
DNS劫持: 启用
自定义DNS: 停用
IPV6-DNS解析: 停用
禁用Dnsmasq缓存: 启用
自定义规则: 停用
仅允许内网: 停用
仅代理命中规则流量: 停用
绕过中国大陆IP: 启用

#启动异常时建议关闭此项后重试
保留配置: 停用
第三方规则: 停用

#===================== 配置文件 =====================#
redir-port: 7892
port: 7890
socks-port: 7891
ipv6: false
mode: rule
log-level: silent
external-controller: 0.0.0.0:9090
secret: "123456"
allow-lan: true
bind-address: "*"
external-ui: "/usr/share/openclash/dashboard"
tun:
  enable: true
  stack: system
  dns-hijack:
  - tcp://8.8.8.8:53
  - tcp://8.8.4.4:53
hosts:
##Custom HOSTS##
#  experimental hosts, support wildcard (e.g. *.clash.dev Even *.foo.*.example.com)
#  static domain has a higher priority than wildcard domain (foo.example.com > *.example.com)
#  NOTE: hosts don't work with `fake-ip`

#  '*.clash.dev': 127.0.0.1
#  'alpha.clash.dev': '::1'
##Custom HOSTS END##
dns:
  use-hosts: true
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 127.0.0.1:7874
  nameserver:
  - 114.114.114.114
  - 119.29.29.29
  - https://doh.rixcloud.dev/dns-query
  fallback:
  - https://cloudflare-dns.com/dns-query
  - https://dns.google/dns-query
  - https://1.1.1.1/dns-query
  - tls://8.8.8.8:853
  fallback-filter:
    geoip: true
    ipcidr:
      - 0.0.0.0/8
      - 10.0.0.0/8
      - 100.64.0.0/10
      - 127.0.0.0/8
      - 169.254.0.0/16
      - 172.16.0.0/12
      - 192.0.0.0/24
      - 192.0.2.0/24
      - 192.88.99.0/24
      - 192.168.0.0/16
      - 198.18.0.0/15
      - 198.51.100.0/24
      - 203.0.113.0/24
      - 224.0.0.0/4
      - 240.0.0.0/4
      - 255.255.255.255/32

#===================== 防火墙设置 =====================#

#NAT chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    ACCEPT     tcp  --  0.0.0.0/0            8.8.4.4             
2    ACCEPT     tcp  --  0.0.0.0/0            8.8.8.8             
3    REDIRECT   udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:53 redir ports 53
4    REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:53 redir ports 53
5    prerouting_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom prerouting rule chain */
6    zone_lan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
7    zone_wan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
8    zone_wan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
9    openclash  tcp  --  0.0.0.0/0            0.0.0.0/0           
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         

#Mangle chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    openclash  udp  --  0.0.0.0/0            0.0.0.0/0           
2    openclash_dns_hijack  tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:53
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         
1    RRDIPT_OUTPUT  all  --  0.0.0.0/0            0.0.0.0/0           

#===================== 路由表状态 =====================#
#route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         100.64.0.1      0.0.0.0         UG    0      0        0 pppoe-wan
100.64.0.1      0.0.0.0         255.255.255.255 UH    0      0        0 pppoe-wan
192.168.1.0     0.0.0.0         255.255.255.0   U     0      0        0 br-lan
198.18.0.0      0.0.0.0         255.255.0.0     U     0      0        0 utun
#ip route list
default via 100.64.0.1 dev pppoe-wan proto static 
100.64.0.1 dev pppoe-wan proto kernel scope link src 100.64.32.233 
192.168.1.0/24 dev br-lan proto kernel scope link src 192.168.1.1 
198.18.0.0/16 dev utun proto kernel scope link src 198.18.0.1 
#ip rule show
0:	from all lookup local 
32765:	from all fwmark 0x162 lookup 354 
32766:	from all lookup main 
32767:	from all lookup default 

#===================== Tun设备状态 =====================#
utun: tun pi filter

#===================== 端口占用状态 =====================#
tcp        0      0 198.18.0.1:7777         0.0.0.0:*               LISTEN      26836/clash
tcp        0      0 :::7890                 :::*                    LISTEN      26836/clash
tcp        0      0 :::7891                 :::*                    LISTEN      26836/clash
tcp        0      0 :::7892                 :::*                    LISTEN      26836/clash
tcp        0      0 :::9090                 :::*                    LISTEN      26836/clash
udp        0      0 198.18.0.1:7777         0.0.0.0:*                           26836/clash
udp        0      0 127.0.0.1:7874          0.0.0.0:*                           26836/clash
udp        0      0 :::7891                 :::*                                26836/clash
udp        0      0 :::7892                 :::*                                26836/clash

#===================== 测试本机DNS查询 =====================#
Server:		127.0.0.1
Address:	127.0.0.1#53

Name:      www.baidu.com
www.baidu.com	canonical name = www.a.shifen.com
Name:      www.a.shifen.com
Address 1: 14.215.177.39
Address 2: 14.215.177.38
*** Can't find www.baidu.com: No answer

#===================== resolv.conf.auto =====================#
# Interface wan
nameserver 202.96.128.86
nameserver 202.96.134.33

#===================== 测试本机网络连接 =====================#
HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: private, no-cache, no-store, proxy-revalidate, no-transform
Connection: keep-alive
Content-Length: 277
Content-Type: text/html
Date: Mon, 14 Sep 2020 17:26:54 GMT
Etag: "575e1f72-115"
Last-Modified: Mon, 13 Jun 2016 02:50:26 GMT
Pragma: no-cache
Server: bfe/1.0.8.18


#===================== 测试本机网络下载 =====================#
HTTP/1.1 200 Connection established

HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 78
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: text/plain; charset=utf-8
ETag: "f33f76b7c2036f06901d0623c3f96a4fab0edf76f9d8de884dadbec1f5d4750f"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
Via: 1.1 varnish (Varnish/6.0)
X-GitHub-Request-Id: 74E6:09B1:49C6D:667E8:5F5FA3CC
Accept-Ranges: bytes
Date: Mon, 14 Sep 2020 17:26:54 GMT
Via: 1.1 varnish
X-Served-By: cache-hkg17924-HKG
X-Cache: HIT, HIT
X-Cache-Hits: 1, 1
X-Timer: S1600104415.905462,VS0,VE0
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
X-Fastly-Request-ID: d12d721da8d9f332546c1d507e5a94b753ab8c9e
Expires: Mon, 14 Sep 2020 17:31:54 GMT
Source-Age: 282


#===================== 最近运行日志 =====================#
time="2020-09-14T17:19:24Z" level=info msg="Start initial compatible provider GlobalMedia"
time="2020-09-14T17:19:24Z" level=info msg="Start initial compatible provider AdBlock"
time="2020-09-14T17:19:24Z" level=info msg="Start initial compatible provider PayPal"
time="2020-09-14T17:19:24Z" level=info msg="Start initial compatible provider Proxy3"
time="2020-09-14T17:19:24Z" level=info msg="Start initial compatible provider Proxy2"
time="2020-09-14T17:19:24Z" level=info msg="Start initial compatible provider Proxy1"
time="2020-09-14T17:19:24Z" level=info msg="Start initial compatible provider Apple_API"
time="2020-09-14T17:19:24Z" level=info msg="Start initial compatible provider Netflix"
time="2020-09-14T17:19:24Z" level=info msg="Start initial compatible provider AsianMedia"
time="2020-09-14T17:19:24Z" level=info msg="Start initial compatible provider Apple_CDN"
time="2020-09-14T17:19:24Z" level=info msg="Start initial compatible provider Proxy4"
time="2020-09-14T17:19:24Z" level=info msg="Start initial compatible provider Global"
time="2020-09-14T17:19:24Z" level=info msg="Start initial compatible provider Domestic"
time="2020-09-14T17:19:24Z" level=info msg="DNS server listening at: 127.0.0.1:7874"
2020-09-15 01:19:18 OpenClash Start Successful
time="2020-09-14T17:22:39Z" level=info msg="Start initial compatible provider Proxy3"
time="2020-09-14T17:22:39Z" level=info msg="Start initial compatible provider Global"
time="2020-09-14T17:22:39Z" level=info msg="Start initial compatible provider PayPal"
time="2020-09-14T17:22:39Z" level=info msg="Start initial compatible provider AsianMedia"
time="2020-09-14T17:22:39Z" level=info msg="Start initial compatible provider Proxy4"
time="2020-09-14T17:22:39Z" level=info msg="Start initial compatible provider Proxy1"
time="2020-09-14T17:22:39Z" level=info msg="Start initial compatible provider Domestic"
time="2020-09-14T17:22:39Z" level=info msg="Start initial compatible provider Apple_API"
time="2020-09-14T17:22:39Z" level=info msg="Start initial compatible provider Netflix"
time="2020-09-14T17:22:39Z" level=info msg="Start initial compatible provider AdBlock"
time="2020-09-14T17:22:39Z" level=info msg="Start initial compatible provider GlobalMedia"
time="2020-09-14T17:22:39Z" level=info msg="Start initial compatible provider Apple_CDN"
time="2020-09-14T17:22:39Z" level=info msg="Start initial compatible provider Proxy2"
time="2020-09-14T17:22:39Z" level=info msg="DNS server listening at: 127.0.0.1:7874"
2020-09-15 01:22:33 OpenClash Start Successful

**Comment by ABXYvvv** [comment]
确实如你所说，更新完走到第五步就停下了，然后手动点一次启动openclash，就能走到第十步然后正常连接。现在只能设置关闭自动更新geoip

**Comment by lifetyper** [comment]
同样的问题，今天早上五点更新了一下geoip数据，刚才看了下clash还在运行（守护进程没运行），但代理规则都失效了，需要手动重启openclash。

**Comment by vernesong** [comment]
给错误的日志或者复现的方法，不然没法修

**Comment by ABXYvvv** [comment]
没有错误日志呀，上面已经整个调式日志发出来了

**Comment by goukey** [comment]
同样发现这个问题，不止是geoip，就连更新订阅也会出现更新结束openclash就打不开的情况。
于是我把自动更新全关了。

**Comment by vernesong** [comment]
更新完有没有启动的步骤显示？

**Comment by goukey** [comment]
没有，就像整个流程中间突然断了

**Comment by ShowMarkK** [comment]
最近我刚遇到这个问题，我的解决办法是，你的geoip更新后你需要重新去clash控制面板把节点测速下就可以了。
