### ISSUE TITLE
Wireguard 回连无法正常代理

### ISSUE THREAD

**Issue by suzanneeound** [vernesong/OpenClash#753]
一直使用 lhie1 的规则配合dev内核的 Redir-Host 模式使用，Wireguard 连回去能够正常代理。

最近lhie1规则更新后导致使用clash_tun内核，Wireguard 能够连接成功，DIRECT的网站能上，但是不能够正常代理。

请问，还需要提供什么其他信息吗？

**Comment by hcym** [comment]
wireguard也支持吗，还是单独使用做隧道？😋

**Comment by suzanneeound** [comment]
@hcym 只是移动设备用 wiregurad 连入内网，没有做其他用途。

**Comment by hcym** [comment]
哦，感谢回复，那就不用部署了🥰

**Comment by vernesong** [comment]
你用普通模式跟内核就没有关系，设置都是一样的，你去看下日志显示的什么错误，或者是流量有没到clash

**Comment by suzanneeound** [comment]
查了下 log，流量没有经过 clash。

然后看到这个 #689，现在把 wireguard server 放到内网的一台机子上，工作正常了。

**Comment by yanyingjie007** [comment]
我想在路由器上设置wireguard,让我两个home变成内网,这个和openclash不冲突吧?

**Comment by suzanneeound** [comment]
@yanyingjie007 

目前我是关闭了openclash udp代理，并且把wireguard server部署在内网其他机器，wireguard才能正常工作。

不知道v0.40.8以后是什么样子，我还没试。

**Comment by whwlsfb** [comment]
遇到相同问题，期待修复

**Comment by auroracamus** [comment]
你看一下wireguard的客户端的配置文件中，DNS那一项是不是没填？填114.114.114.114试试看（或是网关地址），我就是这么解决的。
