### ISSUE TITLE
ip地址检测

### ISSUE THREAD

**Issue by qin9125** [vernesong/OpenClash#754]
![image](https://user-images.githubusercontent.com/32502941/93044291-ef5b2580-f686-11ea-9261-7f5878d5ddc6.png)
好奇怪，更新了新版，这个地址全变 一样的了，无论重启路由，开关openclash，还是清理浏览器缓存，海外地址都无法变节点位置

**Comment by Nepmonts** [comment]
换个设备试试

**Comment by OleStore** [comment]
规则问题

**Comment by qin9125** [comment]
> 规则问题

应该不是规则吧，之前好像没有这样我也没有变规则，你指的规则具体是哪？
