### ISSUE TITLE
一键生成配置文件失败

### ISSUE THREAD

**Issue by STIVW** [vernesong/OpenClash#755]
无法添加规则。
规则栏空白
![ew](https://user-images.githubusercontent.com/48052580/93074536-16c9e680-f6b7-11ea-8f5b-e90af354dcdf.png)

**Comment by vernesong** [comment]
什么版本？怎么复现？

**Comment by STIVW** [comment]
今天全部更新了最新版本。  更新完客户端和内核后配置文件就失效了。

我重新订阅后，然后在---服务器&策略组管理--中保存应用，自动配置完策略组后提示，下图

![屏幕截图 2020-09-14 191443](https://user-images.githubusercontent.com/48052580/93079421-acb53f80-f6be-11ea-90e8-9141b7b92912.png)


而且--服务器&策略组管理--页面，点击应用总是转到首页后没有反应。

不知道是不是我使用方法有问题，不过以前一直这么用的

**Comment by STIVW** [comment]
lhie1 规则 一直配置失败

ConnersHua 规则 成功了两次，现在不敢再换了勉强用ConnersHua 规则

**Comment by vernesong** [comment]
发下错误日志

**Comment by STIVW** [comment]
一键恢复默认配置后，重新弄了又好了
