### ISSUE TITLE
请问 Openclash中tun内核的源码是从哪里来的呢

### ISSUE THREAD

**Issue by ffegya** [vernesong/OpenClash#756]
我想要自行编译clash tun 不是到v大的源码是从哪里来的

**Comment by Teaffanie** [comment]
闭源的

**Comment by ffegya** [comment]
但是我看vernesong的TUN内核是他自己编译的呀，那既然是闭源的他是从哪来的源码呀

**Comment by Teaffanie** [comment]
> 但是我看vernesong的TUN内核是他自己编译的呀，那既然是闭源的他是从哪来的源码呀

不是d大编好的吗

**Comment by ffegya** [comment]
不是的，vernesong更新的比较快，他最新的是9月13号的

**Comment by Teaffanie** [comment]
> 不是的，vernesong更新的比较快，他最新的是9月13号的

https://tmpclashpremiumbindary.cf/

**Comment by ffegya** [comment]
谢谢 我想问下 这个TUN内核是d大编译的吗，这个网站是在哪里介绍的呢，为什么我没在d大的github上找到呢

**Comment by Teaffanie** [comment]
> 谢谢 我想问下 这个TUN内核是d大编译的吗，这个网站是在哪里介绍的呢，为什么我没在d大的github上找到呢

我曾在这里看到就记下来了

**Comment by ffegya** [comment]
明白了，十分感谢

**Comment by Teaffanie** [comment]
https://github.com/comzyh/clash/tree/add-water 游戏内核可以编一下
