### ISSUE TITLE
自定义规则启动但是未生效

### ISSUE THREAD

**Issue by yanyingjie007** [vernesong/OpenClash#757]
请看部分调试日志：

OpenClash 调试日志

生成时间: 2020-09-15 09:53:25
插件版本: v0.40.4-beta

#===================== 系统信息 =====================#
主机型号: VMware, Inc. VMware Virtual Platform
固件版本: OpenWrt 19.07.3 r11063-85e04e9f46
LuCI版本: git-20.136.49537-fb2f363-1
内核版本: 4.14.180
处理器架构: x86_64

#此项在使用Tun模式时应为ACCEPT
防火墙转发: ACCEPT

#此项有值时建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: 

#此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 127.0.0.1#5450

#===================== 依赖检查 =====================#
dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
jsonfilter: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
iptables-mod-tproxy: 已安装
kmod-tun(TUN模式): 已安装
luci-compat(Luci-19.07): 已安装

#===================== 内核检查 =====================#
运行状态: 运行中
已选择的架构: linux-amd64

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 2020.09.13.g3dc8802
Tun内核文件: 存在
Tun内核运行权限: 正常

Game内核版本: v0.17.0-194-gbe86985
Game内核文件: 存在
Game内核运行权限: 正常

Dev内核版本: v1.1.0-13-g314ce1c
Dev内核文件: 存在
Dev内核运行权限: 正常

#===================== 插件设置 =====================#
当前配置文件: /etc/openclash/config/DlerCloud.yaml
运行模式: fake-ip-mix
默认代理模式: script
UDP流量转发: 停用
DNS劫持: 启用
自定义DNS: 停用
IPV6-DNS解析: 停用
禁用Dnsmasq缓存: 启用
自定义规则: 启用
仅允许内网: 停用
仅代理命中规则流量: 启用
绕过中国大陆IP: 停用

#启动异常时建议关闭此项后重试
保留配置: 停用
第三方规则: 停用

#===================== 自定义规则 一 =====================#
- DOMAIN-KEYWORD,lastpass,DIRECT
- DOMAIN-KEYWORD,rarbgprx,Proxy
- DOMAIN-KEYWORD,dlercloud,Proxy
- DOMAIN,plex.tv,DIRECT
- SRC-IP-CIDR,192.168.2.4/32,DIRECT
#===================== 自定义规则 二 =====================#
##- DOMAIN-SUFFIX,google.com,Proxy 匹配域名后缀(交由Proxy代理服务器组)
##- DOMAIN-KEYWORD,google,Proxy 匹配域名关键字(交由Proxy代理服务器组)
##- DOMAIN,google.com,Proxy 匹配域名(交由Proxy代理服务器组)
##- DOMAIN-SUFFIX,ad.com,REJECT 匹配域名后缀(拒绝)
##- IP-CIDR,127.0.0.0/8,DIRECT 匹配数据目标IP(直连)
##- SRC-IP-CIDR,192.168.1.201/32,DIRECT 匹配数据发起IP(直连)
##- DST-PORT,80,DIRECT 匹配数据目标端口(直连)
##- SRC-PORT,7777,DIRECT 匹配数据源端口(直连)

自定义规则显示启动，但是并未生效，比如plex.tv这个域名设置为直连，但实际是通过代理，是否哪里错了？
![image](https://user-images.githubusercontent.com/3379511/93156391-9ea50480-f73a-11ea-8536-020129e0fb8a.png)
![image](https://user-images.githubusercontent.com/3379511/93156424-b2506b00-f73a-11ea-96f6-00ccce3777f3.png)

**Comment by vernesong** [comment]
模式是script，自定规则没生效，切换到rule
