### ISSUE TITLE
无法开启tun模式


### ISSUE THREAD

**Issue by whufanwei** [vernesong/OpenClash#759]
![Screenshot_20200916-083439.jpg](https://user-images.githubusercontent.com/1192749/93278630-d1610280-f7f7-11ea-979d-7aab45872cd0.jpg)

![Screenshot_20200916-083350__01.jpg](https://user-images.githubusercontent.com/1192749/93278637-d756e380-f7f7-11ea-981c-428f1d875a21.jpg)

![Screenshot_20200916-083422__01.jpg](https://user-images.githubusercontent.com/1192749/93278645-dcb42e00-f7f7-11ea-908e-a536e422ef00.jpg)

**Comment by whufanwei** [comment]
现在只能使用fake-ip的增强模式，无法开启 tun及游戏模式。  这些内核均下载到本地，但是不能显示版本号。见上图，版本号显示是轮询机制，一会显示，一会不显示。切换到tun模式，clash无法启动。

**Comment by Teaffanie** [comment]
kmod-tun没装

**Comment by whufanwei** [comment]
kmod装了

**Comment by whufanwei** [comment]
#===================== 内核检查 =====================#
运行状态: 运行中
已选择的架构: linux-armv8

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 
Tun内核文件: 存在
Tun内核运行权限: 正常

Game内核版本: 
Game内核文件: 存在
Game内核运行权限: 正常

Dev内核版本: v1.1.0-13-g314ce1c
Dev内核文件: 存在
Dev内核运行权限: 正常

#===================== 插件设置 =====================#

**Comment by zlwww** [comment]
kmod-tun 把这个装了
