### ISSUE TITLE
订阅 dler 的配置，貌似代理规则不生效

### ISSUE THREAD

**Issue by rrfeng** [vernesong/OpenClash#760]
全部按照基本设置，订阅之后启动成功，但是日志中全部都是显示 xxx.gogole.com 没匹配到任何规则，DIRECT dial timeout 之类的，奇怪规则为什么没生效呢？

**Comment by chesterwang** [comment]
同问 上不了google非常影响工作啊啊啊啊啊啊

**Comment by Nepmonts** [comment]
> 全部按照基本设置，订阅之后启动成功，但是日志中全部都是显示 xxx.gogole.com 没匹配到任何规则，DIRECT dial timeout 之类的，奇怪规则为什么没生效呢？

是TCP流量没被代理还是UDP没被代理被DITECT?
