### ISSUE TITLE
大家有没有遇到上传外网速度变少的问题？

### ISSUE THREAD

**Issue by yang05130** [vernesong/OpenClash#762]
同个节点，同样是上传谷歌，开SSR能跑满上行，开了openclash后，只能跑5分之一
V2ray的节点，用的是tun模式

**Comment by 101818** [comment]
机器性能不行吧


发自 iPad 版 Yahoo 邮箱




同个节点，同样是上传谷歌，开SSR能跑满上行，开了openclash后，只能跑5分之一

**Comment by yang05130** [comment]
> 机器性能不行吧 发自 iPad 版 Yahoo 邮箱 同个节点，同样是上传谷歌，开SSR能跑满上行，开了openclash后，只能跑5分之一 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我看CPU占用，都不到20%

**Comment by kongkongzzz** [comment]
Me too.

**Comment by kongkongzzz** [comment]
刚才突然找到原因了，似乎和turbo acc的bbr冲突，关闭bbr加速以后上传恢复正常。你可以试试。至于为什么冲突和如何解决这个问题，咱也不清楚了。

**Comment by yang05130** [comment]
> 刚才突然找到原因了，似乎和turbo acc的bbr冲突，关闭bbr加速以后上传恢复正常。你可以试试。至于为什么冲突和如何解决这个问题，咱也不清楚了。
> 我这边是fake ip增强模式

Turbo ACC 网络加速设置只关掉BBR吗

**Comment by kongkongzzz** [comment]
你可以自己试。我这边反正关掉bbr即可，其他选项不知道有没有影响、

**Comment by frank2002** [comment]
我关掉了SQM就正常了
