### ISSUE TITLE
旁路由，开启0penc1ash后，无法上任何网站

### ISSUE THREAD

**Issue by violente21** [vernesong/OpenClash#763]
开启0penc1ash，服务器与策略管理，节点订阅ping检查：检测失败。              此时不能更新0penc1ash内核。
关闭0penc1ash，服务器与策略管理，节点订阅ping检查：有具体延迟时间。此时能更新0penc1ash内核。
无论是否开启0penc1ash，网站访问检查里y0utube项：连接超时。

插件只用0penc1ash，打开UDP流量转发，设置本地DNS劫持，启用上游DNS，0penc1ash能启动，但启动后pc连接无法上任何网站。

**Comment by violente21** [comment]
接口只有lan，dns服务器：旁路由的地址

**Comment by vernesong** [comment]
发调试日志

**Comment by violente21** [comment]
> 发调试日志

OpenClash 调试日志

生成时间: 2020-09-19 14:24:13
插件版本: v0.40.4-beta

#===================== 系统信息 =====================#
主机型号: Raspberry Pi 4 Model B Rev 1.2
固件版本: OpenWrt SNAPSHOT r11895-fba8083540
LuCI版本: git-20.004.64129-d60a1a1-1
内核版本: 4.19.93
处理器架构: arm_cortex-a7_neon-vfpv4

#此项在使用Tun模式时应为ACCEPT
防火墙转发: ACCEPT

#此项有值时建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: 

#此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 127.0.0.1#7874

#===================== 依赖检查 =====================#
dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
jsonfilter: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
iptables-mod-tproxy: 已安装
kmod-tun(TUN模式): 已安装
luci-compat(Luci-19.07): 已安装

#===================== 内核检查 =====================#
运行状态: 运行中
已选择的架构: linux-armv8

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 2020.09.13.g3dc8802
Tun内核文件: 存在
Tun内核运行权限: 正常

Game内核版本: v0.17.0-194-gbe86985
Game内核文件: 存在
Game内核运行权限: 正常

Dev内核版本: v1.1.0-13-g314ce1c
Dev内核文件: 存在
Dev内核运行权限: 正常

#===================== 插件设置 =====================#
当前配置文件: /etc/openclash/config/config.yaml
运行模式: redir-host
默认代理模式: rule
UDP流量转发: 启用
DNS劫持: 启用
自定义DNS: 启用
IPV6-DNS解析: 停用
禁用Dnsmasq缓存: 启用
自定义规则: 停用
仅允许内网: 停用
仅代理命中规则流量: 停用
绕过中国大陆IP: 停用

#启动异常时建议关闭此项后重试
保留配置: 启用

#启动异常时建议关闭此项后重试
第三方规则: lhie1
第三方规则策略组设置:
GlobalTV: GlobalTV
AsianTV: AsianTV
Proxy: Proxy
Apple: Apple
Netflix: Netflix
Spotify: Spotify
Steam: Steam
AdBlock: AdBlock
Netease Music: DIRECT
Speedtest: Speedtest
Telegram: Telegram
Microsoft: Microsoft
PayPal: PayPal
Domestic: Domestic
Others: Others

读取的配置文件策略组:
Auto - UrlTest
Proxy
Domestic
Others
Apple
Microsoft
Netflix
Youtube
Spotify
Steam
AdBlock
AsianTV
GlobalTV
Speedtest
Telegram
PayPal
DIRECT
REJECT

#===================== 配置文件 =====================#
redir-port: 7892
port: 7890
socks-port: 7891
ipv6: false
mode: rule
log-level: silent
external-controller: 0.0.0.0:9090
secret: "123456"
allow-lan: true
bind-address: "*"
external-ui: "/usr/share/openclash/dashboard"
hosts:
##Custom HOSTS##
#  experimental hosts, support wildcard (e.g. *.clash.dev Even *.foo.*.example.com)
#  static domain has a higher priority than wildcard domain (foo.example.com > *.example.com)
#  NOTE: hosts don't work with `fake-ip`

#  '*.clash.dev': 127.0.0.1
#  'alpha.clash.dev': '::1'
##Custom HOSTS END##
dns:
  use-hosts: true
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 127.0.0.1:7874
##Custom DNS##
  nameserver:
  - 114.114.114.114:53
  - 119.29.29.29:53
  fallback:
  - tcp://8.8.8.8
  - tls://8.8.8.8
  - https://8.8.8.8:443
  - tcp://8.8.4.4
  - tls://8.8.4.4
  - https://8.8.4.4:443
  fallback-filter:
    geoip: true
    ipcidr:
      - 0.0.0.0/8
      - 10.0.0.0/8
      - 100.64.0.0/10
      - 127.0.0.0/8
      - 169.254.0.0/16
      - 172.16.0.0/12
      - 192.0.0.0/24
      - 192.0.2.0/24
      - 192.88.99.0/24
      - 192.168.0.0/16
      - 198.18.0.0/15
      - 198.51.100.0/24
      - 203.0.113.0/24
      - 224.0.0.0/4
      - 240.0.0.0/4
      - 255.255.255.255/32

#===================== 防火墙设置 =====================#

#NAT chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    REDIRECT   tcp  --  0.0.0.0/0            8.8.4.4              redir ports 7892
2    REDIRECT   tcp  --  0.0.0.0/0            8.8.8.8              redir ports 7892
3    REDIRECT   udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:53 redir ports 53
4    REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:53 redir ports 53
5    prerouting_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom prerouting rule chain */
6    zone_lan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
7    openclash  tcp  --  0.0.0.0/0            0.0.0.0/0           
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         

#Mangle chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    openclash  udp  --  0.0.0.0/0            0.0.0.0/0           
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         

#===================== 路由表状态 =====================#
#route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.21.1    0.0.0.0         UG    0      0        0 eth0
192.168.21.0    0.0.0.0         255.255.255.0   U     0      0        0 eth0
#ip route list
default via 192.168.21.1 dev eth0 proto static 
192.168.21.0/24 dev eth0 proto kernel scope link src 192.168.21.23 
#ip rule show
0:	from all lookup local
32765:	from all fwmark 0x162 lookup 354
32766:	from all lookup main
32767:	from all lookup default

#===================== 端口占用状态 =====================#
tcp        0      0 :::7892                 :::*                    LISTEN      4825/clash
tcp        0      0 :::9090                 :::*                    LISTEN      4825/clash
tcp        0      0 :::7890                 :::*                    LISTEN      4825/clash
tcp        0      0 :::7891                 :::*                    LISTEN      4825/clash
udp        0      0 127.0.0.1:7874          0.0.0.0:*                           4825/clash
udp        0      0 :::7891                 :::*                                4825/clash
udp        0      0 :::7892                 :::*                                4825/clash

#===================== 测试本机DNS查询 =====================#

#===================== resolv.conf.auto =====================#
# Interface lan
nameserver 192.168.21.23

#===================== 测试本机网络连接 =====================#

#===================== 测试本机网络下载 =====================#
HTTP/1.1 200 Connection established

HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 78
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: text/plain; charset=utf-8
ETag: "f33f76b7c2036f06901d0623c3f96a4fab0edf76f9d8de884dadbec1f5d4750f"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
Via: 1.1 varnish (Varnish/6.0)
X-GitHub-Request-Id: 5592:0C48:8597A:B0689:5F6588E3
Accept-Ranges: bytes
Date: Sat, 19 Sep 2020 06:24:50 GMT
Via: 1.1 varnish
X-Served-By: cache-hkg17924-HKG
X-Cache: HFM, HIT
X-Cache-Hits: 0, 1
X-Timer: S1600496690.430400,VS0,VE1
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
X-Fastly-Request-ID: e32e5cd522fbc535eacca783aa0b77e9c9dd3ca1
Expires: Sat, 19 Sep 2020 06:29:50 GMT
Source-Age: 52


#===================== 最近运行日志 =====================#
time="2020-09-19T14:22:19+08:00" level=info msg="Start initial rule provider Letv"
time="2020-09-19T14:22:19+08:00" level=info msg="Start initial rule provider Steam"
time="2020-09-19T14:22:19+08:00" level=info msg="Start initial rule provider Apple"
time="2020-09-19T14:22:19+08:00" level=info msg="Start initial rule provider Disney Plus"
time="2020-09-19T14:22:19+08:00" level=info msg="Start initial rule provider Hulu"
time="2020-09-19T14:22:19+08:00" level=info msg="Start initial rule provider Fox Now"
time="2020-09-19T14:22:19+08:00" level=info msg="Start initial rule provider Reject"
time="2020-09-19T14:22:19+08:00" level=info msg="Start initial rule provider Bahamut"
time="2020-09-19T14:22:19+08:00" level=info msg="Start initial rule provider Amazon"
time="2020-09-19T14:22:19+08:00" level=info msg="Start initial rule provider JOOX"
time="2020-09-19T14:22:19+08:00" level=info msg="Start initial rule provider Abema TV"
time="2020-09-19T14:22:19+08:00" level=info msg="Start initial rule provider Pandora"
time="2020-09-19T14:22:19+08:00" level=info msg="Start initial rule provider Netease Music"
time="2020-09-19T14:22:19+08:00" level=info msg="Start initial rule provider encoreTVB"
time="2020-09-19T14:22:19+08:00" level=info msg="Start initial rule provider Microsoft"
time="2020-09-19T14:22:19+08:00" level=info msg="Start initial rule provider Telegram"
time="2020-09-19T14:22:19+08:00" level=info msg="Start initial rule provider YouTube"
time="2020-09-19T14:22:19+08:00" level=info msg="Start initial rule provider iQiyi"
time="2020-09-19T14:22:19+08:00" level=info msg="Start initial rule provider Pornhub"
time="2020-09-19T14:22:19+08:00" level=info msg="Start initial rule provider KKTV"
time="2020-09-19T14:22:19+08:00" level=info msg="Start initial rule provider ABC"
time="2020-09-19T14:22:19+08:00" level=info msg="Start initial rule provider Youku"
time="2020-09-19T14:22:19+08:00" level=info msg="Start initial rule provider Bilibili"
time="2020-09-19T14:22:19+08:00" level=info msg="Start initial rule provider Line TV"
time="2020-09-19T14:22:19+08:00" level=info msg="Start initial rule provider DAZN"
time="2020-09-19T14:22:19+08:00" level=info msg="DNS server listening at: 127.0.0.1:7874"
2020-09-19 14:22:14 OpenClash Start Successful
2020-09-19 14:22:22 OpenClash Reload After Firewall Restart
2020-09-19 14:22:26 OpenClash Reload After Firewall Restart
2020-09-19 14:22:27 OpenClash Reload After Firewall Restart

**Comment by vernesong** [comment]
你路由自身的网络连接有问题，无法直连访问外部，看下路由自身的lan口IP地址在不在主路由DHCP范围内

**Comment by violente21** [comment]
> 你路由自身的网络连接有问题，无法直连访问外部，看下路由自身的lan口IP地址在不在主路由DHCP范围内

旁路由的ip在主路由的dhcp地址内。
我之前用passwall很正常。openclash有一段时间也正常，忽然有一天出问题了。

**Comment by violente21** [comment]
> 你路由自身的网络连接有问题，无法直连访问外部，看下路由自身的lan口IP地址在不在主路由DHCP范围内
我关闭openclash后路由器可以连外网，订阅也有延迟的具体毫秒时间。
打开openclash后订阅的延时就就检测失败了。

**Comment by vernesong** [comment]
打开后是通过dnsmasq转发了dns查询，你可以暂时关闭DNS劫持选项，看看国内能否访问

**Comment by violente21** [comment]
> 打开后是通过dnsmasq转发了dns查询，你可以暂时关闭DNS劫持选项，看看国内能否访问

按你的方法，开启openclash后ping延迟检测失败。

**Comment by violente21** [comment]
> 打开后是通过dnsmasq转发了dns查询，你可以暂时关闭DNS劫持选项，看看国内能否访问

按你的方法，运行openclash后第三方规则和geoip更新成功，
订阅用代理更新下载失败，无代理的情况下下载更新成功。
服务器节点配置：ping延迟检测失败。
网站访问检查：youtube连接超时。

**Comment by shixiaoxia** [comment]
这个bug太多还是用ssrp 或passworld
