### ISSUE TITLE
求助：怎么让它停止每次更新订阅读取配置

### ISSUE THREAD

**Issue by InoryLwc** [vernesong/OpenClash#764]
如下图：
![image](https://user-images.githubusercontent.com/44205960/93462630-2fd1d200-f919-11ea-8e58-89a4fafb3d66.png)

不知道怎么关闭“服务器&策略组管理”这个功能，每次更新订阅就自动读取，花上十分钟，太浪费时间了。

**Comment by vernesong** [comment]
取消订阅筛选节点

**Comment by InoryLwc** [comment]
> 取消订阅筛选节点

好了，太感谢了
