### ISSUE TITLE
网络访问缓慢

### ISSUE THREAD

**Issue by R3pl4c3r** [vernesong/OpenClash#766]
2906f7c78833cd0b7c27b647cc3888365db62b36
这个commit之后手机端访问国内app资源加载速度很慢，甚至无法访问
除非是redir host模式且开启绕过大陆

**Comment by vernesong** [comment]
看下日志里的链接情况

**Comment by R3pl4c3r** [comment]
> 看下日志里的链接情况

能看到国内的域名和IP走了直连

**Comment by R3pl4c3r** [comment]
问题与 #767 一致

**Comment by R3pl4c3r** [comment]
@vernesong 去除rixCloud的DoH正常了
