### ISSUE TITLE
检测到配置了【Tun】内核专属功能，调用【Tun】内核启动

### ISSUE THREAD

**Issue by wanglongbiao** [vernesong/OpenClash#768]
但是我没有使用 tun 的功能啊
tun 内核还下载不下来
我手动下载下来放进去 clash_tun
结果还检查不到版本。。。
日志是 

2020-09-19 13:47:15 【Tun】Core Version Check Error, Please Try Again After A few seconds

**Comment by poemsiu** [comment]
same issue

**Comment by vernesong** [comment]
配置文件如果使用了ruleset和script，就只有tun内核支持启动，如果空间不够，只装tun内核就行，普通模式配合tun内核不需要kmod-tun

**Comment by vernesong** [comment]
版本检查失败时因为墙的原因，你确保路径正确直接启动即可
