### ISSUE TITLE
【建议】希望「一键生成配置文件」功能能够保留自定义策略组

### ISSUE THREAD

**Issue by chingxuds** [vernesong/OpenClash#769]
RT，目前在使用「一键生成配置文件」功能时，会根据选择的第三方规则自动刷新策略组，同时会把自定义的策略组也给刷新掉。对于某些只能使用特定节点的规则（如动画疯、Netflix），无法配置不同的策略组，只能使用第三方规则定义好的策略组，不够灵活。

**Comment by vernesong** [comment]
一键创建完关闭一键创建再自定义即可，对应规则去全局设置-规则设置调整

或者你添加完策略组和节点关闭一键创建确认修改一次，脚本会把规则外的部分生成，你再去全局设置-规则设置调整

**Comment by chingxuds** [comment]
现在关闭了一键创建，然后使用了第三方规则和手工添加的第三方规则集，但是每次更新都会报错，然后恢复到原始订阅配置，报错信息如下：
> level=fatal msg="Parse config error: proxy group[0]: 'XXXX' not found"
然而报错的代理服务器是订阅生成的，在策略组中设置的也是自动添加到策略组，从来没有显性引用，不知道为何一直报错。
![image](https://user-images.githubusercontent.com/3142486/94338319-d6a62480-0023-11eb-8222-def01461d7fa.png)

**Comment by vernesong** [comment]
策略组不存在就是这样啊，你规则集添加到的策略组名字要保证跟第三方规则里的一样才行

**Comment by chingxuds** [comment]
你看截图，我的策略组就是图里那些，报不存在的是订阅里面的代理服务器，不是策略组，所以很奇怪。我也没有在任何地方直接引用代理服务器

**Comment by vernesong** [comment]
操作分步骤列一下，我看能不能复现

**Comment by chingxuds** [comment]
> 操作分步骤列一下，我看能不能复现

操作有点多，顺序也记不太清了，大概是下面这样。最早是一直启用第三方规则的，后来也是配置文件生成失败才该用下面方法的。
1、添加机场订阅文件，无转换 - 正常
2、开启一键生成配置，带第三方规则 - 正常
3、关闭了一键生成，但是保留策略组，同时添加了自定义的策略组 - 失败，第三方规则报错，回滚到订阅配置
4、关闭了第三方规则，使用自定义策略组 - 成功
5、在规则集与策略组中添加第三方规则 - 配置成功，但是策略貌似没生效，即依然不能科学上网
6、重新开启第三方规则 - 首次成功（此处手动下载了成功的配置），后来更新订阅的时候就失败，然后配置就回滚了
7、重新粘贴之前下载的配置，可以正常启动，但是订阅一更新就报错，然后回滚到订阅配置，有时候启动都中止了。

**Comment by chingxuds** [comment]
总而言之，现在的配置状态是
1、关闭了一键配置，但是开启了保留策略组
2、全局设置中启用了第三方规则
3、规则集与策略组中又自定义添加了第三方规则

**Comment by hcym** [comment]
这次的版本相当不错，一直稳定，规则就是老的，没用过一键

**Comment by vernesong** [comment]
你看一下是不是有策略组没有添加节点或者其他策略组

**Comment by chingxuds** [comment]
> 你看一下是不是有策略组没有添加节点或者其他策略组

都检查过，里面至少都有配置Direct策略

另外现在又出现新错误了

> 2020-09-27 22:39:56 Warning: Because of The Different Porxy-Group's Name, Stop Setting The Other Rules!
time="2020-09-27T14:40:03Z" level=fatal msg="Parse config error: ProxyGroup Proxy: 'proxies[7]' expected type 'string', got unconvertible type 'map[interface {}]interface {}'"
