### ISSUE TITLE
【建议】希望策略组提供按照关键字或正则方式筛选节点的功能。

### ISSUE THREAD

**Issue by chingxuds** [vernesong/OpenClash#770]
RT，对于应用于特殊规则（如只能使用某些地区节点的规则）能够独立分配定制的策略组。策略根据关键字或正则筛选订阅到的节点，使得URL-Test或Fallback或Select方式只在筛选后的节点列表中生效。
此处的筛选与订阅文件中的筛选不一样，是更精细的筛选，例如有两个策略组A、B，A只能使用US节点，B只能使用HK节点，但是由希望是通过URL-Test或Fallback的方式在指定列表中选择。

**Comment by vernesong** [comment]
这个功能在本地实现太慢太麻烦，建议你学习下subconverter的ini配置，下个版本支持自定义模板并远程转换
