### ISSUE TITLE
Fake ip下资源占用高而且经常吃内存

### ISSUE THREAD

**Issue by zhiluop** [vernesong/OpenClash#774]
在Fake ip的情况下经常吃满cpu。进入监控查看system和user经常各占40%+ 。同时网络中的活动连接和可用内存一直减少。
但是在redir模式下，占用最高不超过40。这是正常现象吗？

用的是n1刷43 o+固件 插件只开了opclash和adg

**Comment by Nepmonts** [comment]
固件问题

**Comment by zhiluop** [comment]
不行  刷了44+o 后还是一样的情况。  另外，在监控显示高资源占用时进入系统进程查看时，没有发现有进程过多占用cpu和内存资源，最多的一项不超过5%且项目不多，达不到cpu满载。

**Comment by RodmanWang** [comment]
还是设置有问题，我之前有次设置出问题了，连接数直接爆炸了，看着内存一直往下垮，再检查检查，现在设置对了就没问题了

**Comment by zhiluop** [comment]
> 还是设置有问题，我之前有次设置出问题了，连接数直接爆炸了，看着内存一直往下崩溃，再检查检查，现在设置对了就没问题了

具体我还是没找到是哪里设置出了问题，你之前是哪里设置错误了？能提供一下参考吗？

**Comment by RodmanWang** [comment]
比如你设置过多分组且使用不同节点同时代理，我自己碰到一个问题就是如果把dns地址ip设置规则，后缀不能加,no-resolve，不然解析出问题。比如要设置成 IP-CIDR,101.6.6.6/32，

**Comment by kingo132** [comment]
我的也是，只要在“访问控制”里面添加一个不走代理的IP，马上cpu占用就从1%升到100%，内存占用也直接从150MB升到2GB，只是加了一个IP而已噢，郁闷
