### ISSUE TITLE
Frp内网穿透无法正常使用Yacd 控制面板和Dashboard 控制面板

### ISSUE THREAD

**Issue by Gangnamsstyle** [vernesong/OpenClash#775]
![image](https://user-images.githubusercontent.com/69400033/93705331-e965b880-fb4e-11ea-8275-c940038e6177.png)
![image](https://user-images.githubusercontent.com/69400033/93705345-04d0c380-fb4f-11ea-883b-a140e7a4b260.png)
其他界面内网穿透都没问题，就这两个面板无法正常使用。

**Comment by vernesong** [comment]
看浏览器地址栏，你用哪个域名访问就用哪个域名登录，端口80

**Comment by jitashenshi** [comment]
![image](https://user-images.githubusercontent.com/69400033/94036611-10461800-fdf7-11ea-97c4-236d47a43fdf.png)
这里吗？

**Comment by jitashenshi** [comment]
能麻烦在仔细讲一下吗?

**Comment by vernesong** [comment]
> 能麻烦在仔细讲一下吗?

登录用你cid002的地址，端口看你的应该就是80，密码不变

**Comment by vernesong** [comment]
![image](https://user-images.githubusercontent.com/42875168/94348893-94f09a80-0072-11eb-821a-dbefb7cd4f0b.png)
像这种，登录就填那个ddnsto的域名，端口5000

**Comment by jitashenshi** [comment]
![image](https://user-images.githubusercontent.com/69400033/95667256-06156f00-0b96-11eb-9718-a55a4b774b0a.png)
大佬请帮我再看一下，域名填写了我的域名端口填了80，密码是:123456，显示failed to connect.连接失败。

**Comment by super27035** [comment]
请问问题解决了吗？

**Comment by super27035** [comment]
你要在设置一个新的frp来代理9090端口，把这个新的代理9090端口的网址填上去就可以了

**Comment by super27035** [comment]
但现在最新版本的open clash又有新状况了，老方法用不了了，
![Uploading Screen Shot 2020-11-12 at 10.29.07 PM.png…]()

**Comment by super27035** [comment]
但现在最新版本的open clash又有新状况了
<img width="740" alt="Screen Shot 2020-11-12 at 10 43 40 PM" src="https://user-images.githubusercontent.com/43180500/98954684-027c5b80-2539-11eb-950d-47d11c106937.png">

**Comment by vernesong** [comment]
![image](https://user-images.githubusercontent.com/42875168/135795809-3edeb0f5-7c6a-4d89-98a8-eff8f62a9636.png)
这两个填公网访问的地址和IP
