### ISSUE TITLE
最新版本编译问题

### ISSUE THREAD

**Issue by XinSSS** [vernesong/OpenClash#777]
collected errors:
 * pkg_run_script: package "luci-app-openclash" preinst script returned status 1.
 * preinst_configure: Aborting installation of luci-app-openclash.
 * opkg_install_cmd: Cannot install package luci-app-openclash.
make[2]: *** [package/Makefile:68: package/install] Error 255
make[2]: Leaving directory '/home/shao/lede'
make[1]: *** [package/Makefile:108: /home/shao/lede/staging_dir/target-x86_64_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/home/shao/lede'
make: *** [/home/shao/lede/include/toplevel.mk:224: world] Error 2

昨天还好好的...

**Comment by OleStore** [comment]
看样子得晚点拉取编译

**Comment by ChrisLiu0343** [comment]
同样错误。。。

**Comment by RodmanWang** [comment]
同上

**Comment by OleStore** [comment]
确实报错。。
Collected errors:
 * pkg_run_script: package "luci-app-openclash" preinst script returned status 1.
 * preinst_configure: Aborting installation of luci-app-openclash.
 * opkg_install_cmd: Cannot install package luci-app-openclash.
make[2]: *** [package/Makefile:68: package/install] Error 255
make[2]: Leaving directory '/home/bbq/lede'
make[1]: *** [package/Makefile:108: /home/bbq/lede/staging_dir/target-x86_64_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/home/bbq/lede'
make: *** [/home/bbq/lede/include/toplevel.mk:224: world] Error 2
bbq@balabala:~/lede$

**Comment by RodmanWang** [comment]
刚才源码又更新了，还是错的

**Comment by Michaol** [comment]
同样错误，更新前更新后都是同样错误

**Comment by minfengyk** [comment]
同上

**Comment by RodmanWang** [comment]
大佬已修复，可以更新了。。

**Comment by RodmanWang** [comment]
大佬加的订阅转换很好用哦，表达式是通用的
