### ISSUE TITLE
如何添加域名白名单？

### ISSUE THREAD

**Issue by yaleyip** [vernesong/OpenClash#779]
在自定义规则中，可以实现域名白名单。如：
DOMAIN,youku.com,DIRECT
DOMAIN-SUFFIX,youku.com,DIRECT

这样，很容易出现莫名其妙的代理问题。如：

1. 不能油管，但可以谷歌及国内网站；
2. 不能油管和谷歌，但可以国内网站；
3. 不能所有国内外网站；

0.40.4，fake-ip（TUN-混合）模式

**Comment by vernesong** [comment]
不能访问你首先得把连接日志发出来才能分析

**Comment by secretandanon** [comment]
你用的fake-ip，要注意dns缓存问题，必要时重新启动浏览器，输入ipconfig /flushdns来清除系统dns缓存
