### ISSUE TITLE
在哪里手动选择服色器节点呢？

### ISSUE THREAD

**Issue by dalton-chiou** [vernesong/OpenClash#78]
首先谢谢作者。
比如，我在config.yaml里设置了四个节点。组策略是这样的：
- name: "PROXY"
  type: select
  proxies:
    - "UrlTest"
    - "s1"
    - "s2"
    - "v3"
    - "v4"
type是select，那么，在哪里手动选择呢？

**Comment by vernesong** [comment]
![image](https://user-images.githubusercontent.com/42875168/69595495-a88a3980-103a-11ea-972e-94c178a5db92.png)

**Comment by dalton-chiou** [comment]
@vernesong 我的控制面版打开有问题，不停弹出如图：
![屏幕快照 2019-11-26 23 18 58](https://user-images.githubusercontent.com/34107144/69647154-f12a0d00-10a3-11ea-919c-bbce96513456.png)
怎么确定也过不去。yacd面板也类似，confirm没反应。

与此相关的配置内容是接管生成的：

external-controller: 192.168.1.1:9090
redir-port: 7892
secret: "123456"
external-ui: "/usr/share/openclash/dashboard"

请问问题出在哪里？

**Comment by dalton-chiou** [comment]
已解决。关闭。

**Comment by wclmgcd** [comment]
> 
> 
> @vernesong 我的控制面版打开有问题，不停弹出如图：
> ![屏幕快照 2019-11-26 23 18 58](https://user-images.githubusercontent.com/34107144/69647154-f12a0d00-10a3-11ea-919c-bbce96513456.png)
> 怎么确定也过不去。yacd面板也类似，confirm没反应。
> 
> 与此相关的配置内容是接管生成的：
> 
> external-controller: 192.168.1.1:9090
> redir-port: 7892
> secret: "123456"
> external-ui: "/usr/share/openclash/dashboard"
> 
> 请问问题出在哪里？
我的也是这个问题，请问咋解决的

**Comment by dalton-chiou** [comment]
> > 我的也是这个问题，请问咋解决的

用路由IP，不要用127。

**Comment by wclmgcd** [comment]
> > > 我的也是这个问题，请问咋解决的
> 
> 用路由IP，不要用127。
感谢，没有注意这个细节
