### ISSUE TITLE
Tun模式下script脚本中流过fake-ip的流量

### ISSUE THREAD

**Issue by KillingJacky** [vernesong/OpenClash#783]
Tun模式下使用script脚本，发现198.18.0.1发起大量的连接，而目标地址却是fake-ip段的

time="2020-09-22T09:43:57Z" level=info msg="Start initial provider blinkload"
time="2020-09-22T09:43:57Z" level=info msg="Start initial provider muncloud"
time="2020-09-22T09:43:57Z" level=info msg="Start initial provider myvps"
time="2020-09-22T09:43:57Z" level=info msg="Start initial compatible provider ⛔️拒绝"
time="2020-09-22T09:43:57Z" level=info msg="Start initial compatible provider ✅直通"
time="2020-09-22T09:43:57Z" level=info msg="Start initial rule provider LanPass"
time="2020-09-22T09:43:57Z" level=info msg="DNS server listening at: 127.0.0.1:7874"
time="2020-09-22T09:43:57Z" level=info msg="RESTful API listening at: 192.168.32.1:9090"
time="2020-09-22T09:43:57Z" level=info msg="HTTP proxy listening at: 192.168.32.1:7890"
time="2020-09-22T09:43:57Z" level=info msg="SOCKS proxy listening at: 192.168.32.1:7891"
time="2020-09-22T09:43:57Z" level=info msg="Redir proxy listening at: 192.168.32.1:7892"
time="2020-09-22T09:43:57Z" level=info msg="Tun Proxy listening at: utun(198.18.0.1)"
time="2020-09-22T09:43:57Z" level=info msg="[Script] [TUN,tcp] 192.168.32.10:58696 -> (198.18.0.57):443, low ip request GEOIP LAN, use DIRECT"
time="2020-09-22T09:43:57Z" level=info msg="[Script] [TUN,tcp] 192.168.32.10:58695 -> (198.18.0.59):443, low ip request GEOIP LAN, use DIRECT"
time="2020-09-22T09:43:57Z" level=info msg="[TCP] 192.168.32.10:58695 --> 198.18.0.59 using DIRECT by Script"
time="2020-09-22T09:43:57Z" level=info msg="[Script] [TUN,tcp] 198.18.0.1:41458 -> (198.18.0.59):443, low ip request GEOIP LAN, use DIRECT"
time="2020-09-22T09:43:57Z" level=info msg="[Script] [TUN,tcp] 198.18.0.1:36922 -> (198.18.0.57):443, low ip request GEOIP LAN, use DIRECT"
time="2020-09-22T09:43:57Z" level=info msg="[TCP] 192.168.32.10:58696 --> 198.18.0.57 using DIRECT by Script"
time="2020-09-22T09:43:57Z" level=info msg="[Script] [TUN,tcp] 198.18.0.1:36928 -> (198.18.0.57):443, low ip request GEOIP LAN, use DIRECT"
time="2020-09-22T09:43:57Z" level=info msg="[Script] [TUN,tcp] 198.18.0.1:41460 -> (198.18.0.59):443, low ip request GEOIP LAN, use DIRECT"
time="2020-09-22T09:43:57Z" level=info msg="[TCP] 198.18.0.1:36922 --> 198.18.0.57 using DIRECT by Script"
time="2020-09-22T09:43:57Z" level=info msg="[TCP] 198.18.0.1:41458 --> 198.18.0.59 using DIRECT by Script"
time="2020-09-22T09:43:57Z" level=info msg="[TCP] 198.18.0.1:41460 --> 198.18.0.59 using DIRECT by Script"
time="2020-09-22T09:43:57Z" level=info msg="[Script] [TUN,tcp] 198.18.0.1:41466 -> (198.18.0.59):443, low ip request GEOIP LAN, use DIRECT"
time="2020-09-22T09:43:57Z" level=info msg="[Script] [TUN,tcp] 198.18.0.1:36930 -> (198.18.0.57):443, low ip request GEOIP LAN, use DIRECT"
time="2020-09-22T09:43:57Z" level=info msg="[TCP] 198.18.0.1:36928 --> 198.18.0.57 using DIRECT by Script"
time="2020-09-22T09:43:57Z" level=info msg="[TCP] 198.18.0.1:36930 --> 198.18.0.57 using DIRECT by Script"
time="2020-09-22T09:43:57Z" level=info msg="[Script] [TUN,tcp] 198.18.0.1:36936 -> (198.18.0.57):443, low ip request GEOIP LAN, use DIRECT"
time="2020-09-22T09:43:57Z" level=info msg="[Script] [TUN,tcp] 198.18.0.1:41468 -> (198.18.0.59):443, low ip request GEOIP LAN, use DIRECT"
time="2020-09-22T09:43:57Z" level=info msg="[TCP] 198.18.0.1:41466 --> 198.18.0.59 using DIRECT by Script"
time="2020-09-22T09:43:57Z" level=info msg="[Script] [TUN,tcp] 198.18.0.1:41474 -> (198.18.0.59):443, low ip request GEOIP LAN, use DIRECT"

后省略若干

**Comment by vernesong** [comment]
198.18.0.1指的是本机流量

**Comment by KillingJacky** [comment]
可是目标地址还是198.18段的，如果是本机发往外网的流量，目标地址不应该是外网域名/IP么？这感觉是clash自己的流量又被tun拦截了一遍

**Comment by KillingJacky** [comment]
为什么来自198.18.0.1的流量，目标地址还原不回域名/外网IP？那是不是这些流量最终无法成功连接远端？

**Comment by KillingJacky** [comment]
改用Tun+Redir混合模式了，应该是纯Tun模式iptable拦截多了

**Comment by vernesong** [comment]
tun模式本机是这样，刚启动映射丢失，实际访问不了，等待客户端重新发起dns查询请求才能恢复。
目前script还不好用脚本去修改reject目标是fakeip的地址，这个等代理本机的方案出来才能解决，
