### ISSUE TITLE
0.40.5配置文件编辑出错

### ISSUE THREAD

**Issue by wrxx2019** [vernesong/OpenClash#784]
升级0.40.5后，在配置文件管理-配置文件编辑里手动增加或者减少节点会出现两个问题：
1. 控制面板里还是修改前的旧节点信息配置
2.配置文件编辑里proxies节点信息部分完全消失，配置文件列表-启动参数检查会报节点配置错误
退回0.40.4上述问题消失

**Comment by vernesong** [comment]
无法复现，提供配置文件

**Comment by wrxx2019** [comment]
附上配置文件样板，仅隐去真实节点信息。核心使用Dreamacro的1.1.0。0.40.4下在openclash中上传导入修改这个配置文件没有问题，0.40.5下在proxies中删除任一节点并且proxy-groups也做相应节点删除，应用配置后，进入控制面板中被删除节点依然存在，并且启动参数检查显示红色警告“配置节点部分错误”

[test.zip](https://github.com/vernesong/OpenClash/files/5266044/test.zip)
