### ISSUE TITLE
配置文件【config】下载失败，请检查网络或稍后再试！ 

### ISSUE THREAD

**Issue by lloyd18** [vernesong/OpenClash#785]
同样的配置，上版本没问题，配置文件是自己用subconverter 做的，网页能正常打开

**Comment by Faramitas** [comment]
现在貌似必须用最新版本的自带的SUB转换，就是直接把SSR订阅链接复制上去，然后选择转换
转换都是把那些网站的集成了，你用就行了，挺不错的

**Comment by kongkongzzz** [comment]
但是，有些规则是某些在线订阅转换独有的。并不想用内置的订阅转换。

**Comment by kongkongzzz** [comment]
该问题的原因是重复urlencode，将【/usr/share/openclash/openclash.sh】中274行的【subscribe_url=$(urlencode "$address")】改成【subscribe_url="$address"】即可。希望作者能在下个版本中能够解决这一问题。谢谢！

**Comment by zheguzai** [comment]
这个问题现在还有，怎么能解决啊
