### ISSUE TITLE
更新40.5之后，电视机Prime Video在Redir-Host模式（绕过中国大陆IP）就会显示网络异常

### ISSUE THREAD

**Issue by Faramitas** [vernesong/OpenClash#788]
如题，切换为FAKE-IP后正常，但是我并不像非代理流量也走一遍核心。。。

**Comment by kongkongzzz** [comment]
这个问题似乎已经存在很久了，且不止存在于openclash中，也存在于其他作者的clash相关路由器插件中。redir-host所有模式均会发生这个问题，fake ip所有模式均正常。
表现为：概率性分流错误。我们可以观察到，当发生错误时在clash core提供的webui中连接列表中显示的连接地址并非我们访问的地址。举个例子（反正我这边这个例子是成立的，其他环境未知）：当我访问hostbuf.com（该网址已被加入代理的规则）时，在连接列表中显示的却是一个叫【acg51.com】（记不清了，大概是这个网址|该网址未被加入代理的规则）的网址，所以自然而然匹配不到任何规则或匹配到了【漏网之鱼】的规则，因为core以为我访问的是【acg51.com】。另一方面，这两个域名解析的结果是相同的ip，但clash很大一部分的规则却是按照域名匹配，所以。。。。。
clash在客户端中并没有发生这个问题。
以上仅供参考，不一定完全正确。

**Comment by secretandanon** [comment]
是否存在着一种可能，即在某些情况下hostbuf.com与acg51.com这2个domain被polluted成了一个ip，所以clash在用ip反查domain时出现问题，从而导致错误

**Comment by kongkongzzz** [comment]
更正一下，非【acg51.com】，应该是【www.fcg51.com】，以供测试。
