### ISSUE TITLE
检测不到版本更新

### ISSUE THREAD

**Issue by OleStore** [vernesong/OpenClash#790]
![2020-09-24_083959](https://user-images.githubusercontent.com/1283711/94087971-abfc7600-fe41-11ea-98c1-ff3155a6b890.jpg)
内核更新会提示，版本更新刷不出来
fakeip-tun 混合模式
规则：洞主，一键配置

**Comment by jaove** [comment]
同样问题

**Comment by elonj** [comment]
同样问题

**Comment by qin9125** [comment]
同上，最后下载了ipk包，手动更新，

**Comment by OleStore** [comment]
> 同上，最后下载了ipk包，手动更新，

手动更新直接报错。。

**Comment by vernesong** [comment]
cdn的问题等同步吧

**Comment by OleStore** [comment]
![11048E28-282F-4D14-B2EB-1D05B1A9ECC7](https://user-images.githubusercontent.com/1283711/94112549-32cc4580-fe78-11ea-9ef8-4531554f88bf.png)

不像cdn同步问题啊

**Comment by OleStore** [comment]
@qin9125 @jaove  你们正常了？

**Comment by OleStore** [comment]
问题解决，感谢@vernesong
