### ISSUE TITLE
脚本流程总是进行到一半就结束

### ISSUE THREAD

**Issue by goukey** [vernesong/OpenClash#791]
从上个版本就开始出现，不论是更新订阅（不论自动手动），更新geoip（不论自动手动）还是点击开启openclash，都有90%的几率发生，流程走到“重启dnsmasq”之后就直接结束，不会顺利继续读取配置文件，导致进程失败无法连接。只有偶尔会顺利走完流程，导致我把所有自动更新都关闭了。
更新到昨天的最新版一样没有解决。
我是随固件编译，哪怕全新安装也会出现，请看一下是怎么回事。

**Comment by goukey** [comment]
顺便说一下，我是把openclash作为adgh的上游存在。也就是adgh做dnsmasq上游，openclash关闭dns劫持，adgh上游dns只填openclash一个。记得在0.39.8时一切正常。

**Comment by vernesong** [comment]
日志有没有显示错误

**Comment by goukey** [comment]
没有显示

**Comment by lifetyper** [comment]
> 
> 
> 日志有没有显示错误

运行日志有时候会显示multi start script running,exit之类的。

**Comment by goukey** [comment]
> 日志有没有显示错误

我找到了日志显示的内容

![image](https://user-images.githubusercontent.com/44106685/94925657-2be5a880-04f2-11eb-969e-fc2604f1504e.png)

**Comment by vernesong** [comment]
新版测试了没

**Comment by goukey** [comment]
这截图就是最新版
