### ISSUE TITLE
无法访问epicgames客户端

### ISSUE THREAD

**Issue by CurssedCoffin** [vernesong/OpenClash#793]
epic网页可以正常打开，但是epicgames客户端总是提示登陆失败，网络错误
可以在connections中看到epic走了代理，但是无效

**Comment by vernesong** [comment]
建议用混合模式或者tun模式

**Comment by CurssedCoffin** [comment]
打开tun模式在后台看不到网络连接，请问这是怎么回事。。

**Comment by vernesong** [comment]
依赖装好

**Comment by CurssedCoffin** [comment]
kmod-tun is up to date...
求解

**Comment by CurssedCoffin** [comment]
重新编译了固件，kmod-tun依赖已安装，tun模式可以正常运行
但是epic客户端依旧无法进行登录操作

**Comment by vernesong** [comment]
![image](https://user-images.githubusercontent.com/42875168/94326175-f530ff00-ffd4-11ea-8bcd-e2fb6a7d71a0.png)

**Comment by CurssedCoffin** [comment]
好吧，可能我遇到了灵异事件

**Comment by CurssedCoffin** [comment]
OpenClash 调试日志

生成时间: 2020-09-26 14:07:42
插件版本: v0.40.6-beta

#===================== 系统信息 =====================#
主机型号: Newifi-D2
固件版本: OpenWrt SNAPSHOT r2899-9a482a15a
LuCI版本: git-20.256.12360-1a54222-1
内核版本: 5.4.61
处理器架构: mipsel_24kc

#此项在使用Tun模式时应为ACCEPT
防火墙转发: ACCEPT

#此项有值时建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: 

#此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 127.0.0.1#7874

#===================== 依赖检查 =====================#
dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
jsonfilter: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
iptables-mod-tproxy: 已安装
kmod-tun(TUN模式): 已安装
luci-compat(Luci-19.07): 已安装

#===================== 内核检查 =====================#
运行状态: 运行中
已选择的架构: linux-mipsle-hardfloat

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 2020.09.22.g2d3377d
Tun内核文件: 存在
Tun内核运行权限: 正常

Game内核版本: v0.17.0-194-gbe86985
Game内核文件: 存在
Game内核运行权限: 正常

Dev内核版本: v1.1.0-19-g8766287
Dev内核文件: 存在
Dev内核运行权限: 正常

#===================== 插件设置 =====================#
当前配置文件: /etc/openclash/config/Yoyu.yaml
运行模式: redir-host-mix
默认代理模式: rule
UDP流量转发: 停用
DNS劫持: 启用
自定义DNS: 启用
IPV6-DNS解析: 停用
禁用Dnsmasq缓存: 启用
自定义规则: 停用
仅允许内网: 停用
仅代理命中规则流量: 停用
绕过中国大陆IP: 停用

#启动异常时建议关闭此项后重试
保留配置: 停用
第三方规则: 停用

#===================== 配置文件 =====================#
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
allow-lan: true
bind-address: "*"
ipv6: false
mode: rule
log-level: info
external-controller: 0.0.0.0:9090
clash-for-android:
  append-system-dns: false
hosts:
##Custom HOSTS##
#  experimental hosts, support wildcard (e.g. *.clash.dev Even *.foo.*.example.com)
#  static domain has a higher priority than wildcard domain (foo.example.com > *.example.com)
#  NOTE: hosts don't work with `fake-ip`

#  '*.clash.dev': 127.0.0.1
#  'alpha.clash.dev': '::1'
##Custom HOSTS END##
  mtalk.google.com: 108.177.125.188
secret: "123456"
external-ui: "/usr/share/openclash/dashboard"
tun:
  enable: true
  stack: system
  dns-hijack:
  - tcp://8.8.8.8:53
  - tcp://8.8.4.4:53
dns:
  use-hosts: true
  enable: true
  ipv6: false
  listen: 127.0.0.1:7874
  default-nameserver:
  - 156.154.70.1
  - 1.0.0.1
  enhanced-mode: redir-host
  fake-ip-filter:
  - "*.lan"
  - stun.*.*.*
  - stun.*.*
  - time.windows.com
  - time.nist.gov
  - time.apple.com
  - time.asia.apple.com
  - "*.ntp.org.cn"
  - "*.openwrt.pool.ntp.org"
  - time1.cloud.tencent.com
  - time.ustc.edu.cn
  - pool.ntp.org
  - ntp.ubuntu.com
  - ntp.aliyun.com
  - ntp1.aliyun.com
  - ntp2.aliyun.com
  - ntp3.aliyun.com
  - ntp4.aliyun.com
  - ntp5.aliyun.com
  - ntp6.aliyun.com
  - ntp7.aliyun.com
  - time1.aliyun.com
  - time2.aliyun.com
  - time3.aliyun.com
  - time4.aliyun.com
  - time5.aliyun.com
  - time6.aliyun.com
  - time7.aliyun.com
  - "*.time.edu.cn"
  - time1.apple.com
  - time2.apple.com
  - time3.apple.com
  - time4.apple.com
  - time5.apple.com
  - time6.apple.com
  - time7.apple.com
  - time1.google.com
  - time2.google.com
  - time3.google.com
  - time4.google.com
  - music.163.com
  - "*.music.163.com"
  - "*.126.net"
  - musicapi.taihe.com
  - music.taihe.com
  - songsearch.kugou.com
  - trackercdn.kugou.com
  - "*.kuwo.cn"
  - api-jooxtt.sanook.com
  - api.joox.com
  - joox.com
  - y.qq.com
  - "*.y.qq.com"
  - streamoc.music.tc.qq.com
  - mobileoc.music.tc.qq.com
  - isure.stream.qqmusic.qq.com
  - dl.stream.qqmusic.qq.com
  - aqqmusic.tc.qq.com
  - amobile.music.tc.qq.com
  - "*.xiami.com"
  - "*.music.migu.cn"
  - music.migu.cn
  - "*.msftconnecttest.com"
  - "*.msftncsi.com"
  - localhost.ptlogin2.qq.com
  - "*.*.*.srv.nintendo.net"
  - "*.*.stun.playstation.net"
  - xbox.*.*.microsoft.com
  - "*.ipv6.microsoft.com"
  - "*.*.xboxlive.com"
  nameserver:
##Custom DNS##
  - 114.114.114.114
  - 119.29.29.29
  - 119.28.28.28
  - 223.5.5.5
  - https://doh.rixcloud.dev/dns-query
  fallback:
  - https://cloudflare-dns.com/dns-query
  - https://dns.google/dns-query
  - tls://dns.google:853
  - https://1.1.1.1/dns-query
  - tls://1.1.1.1:853
  - tls://8.8.8.8:853
  fallback-filter:
    geoip: true
    ipcidr:
      - 0.0.0.0/8
      - 10.0.0.0/8
      - 100.64.0.0/10
      - 127.0.0.0/8
      - 169.254.0.0/16
      - 172.16.0.0/12
      - 192.0.0.0/24
      - 192.0.2.0/24
      - 192.88.99.0/24
      - 192.168.0.0/16
      - 198.18.0.0/15
      - 198.51.100.0/24
      - 203.0.113.0/24
      - 224.0.0.0/4
      - 240.0.0.0/4
      - 255.255.255.255/32

#===================== 防火墙设置 =====================#

#NAT chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    CLOUD_MUSIC  tcp  --  0.0.0.0/0            0.0.0.0/0            match-set music dst
2    ACCEPT     tcp  --  0.0.0.0/0            8.8.4.4             
3    ACCEPT     tcp  --  0.0.0.0/0            8.8.8.8             
4    REDIRECT   udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:53 redir ports 53
5    REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:53 redir ports 53
6    prerouting_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom prerouting rule chain */
7    zone_lan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
8    zone_wan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
9    openclash  tcp  --  0.0.0.0/0            0.0.0.0/0           
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         

#Mangle chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    openclash  udp  --  0.0.0.0/0            0.0.0.0/0           
2    openclash_dns_hijack  tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:53
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         

#===================== 路由表状态 =====================#
#route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         120.35.64.1     0.0.0.0         UG    0      0        0 pppoe-wan
120.35.64.1     0.0.0.0         255.255.255.255 UH    0      0        0 pppoe-wan
192.168.1.0     0.0.0.0         255.255.255.0   U     0      0        0 br-lan
198.18.0.0      0.0.0.0         255.255.0.0     U     0      0        0 utun
#ip route list
default via 120.35.64.1 dev pppoe-wan proto static 
120.35.64.1 dev pppoe-wan proto kernel scope link src 120.35.66.200 
192.168.1.0/24 dev br-lan proto kernel scope link src 192.168.1.1 
198.18.0.0/16 dev utun proto kernel scope link src 198.18.0.1 
#ip rule show
0:	from all lookup local
32765:	from all fwmark 0x162 lookup 354
32766:	from all lookup main
32767:	from all lookup default

#===================== Tun设备状态 =====================#
utun: tun pi filter

#===================== 端口占用状态 =====================#
tcp        0      0 198.18.0.1:7777         0.0.0.0:*               LISTEN      2063/clash
tcp        0      0 :::7890                 :::*                    LISTEN      2063/clash
tcp        0      0 :::7891                 :::*                    LISTEN      2063/clash
tcp        0      0 :::7892                 :::*                    LISTEN      2063/clash
tcp        0      0 :::7893                 :::*                    LISTEN      2063/clash
tcp        0      0 :::9090                 :::*                    LISTEN      2063/clash
udp        0      0 127.0.0.1:7874          0.0.0.0:*                           2063/clash
udp        0      0 198.18.0.1:7777         0.0.0.0:*                           2063/clash
udp        0      0 :::35484                :::*                                2063/clash
udp        0      0 :::7891                 :::*                                2063/clash
udp        0      0 :::7892                 :::*                                2063/clash
udp        0      0 :::7893                 :::*                                2063/clash

#===================== 测试本机DNS查询 =====================#
Server:		127.0.0.1
Address:	127.0.0.1#53

Name:      www.baidu.com
www.baidu.com	canonical name = www.a.shifen.com
Name:      www.a.shifen.com
Address 1: 14.215.177.38
Address 2: 14.215.177.39
*** Can't find www.baidu.com: No answer

#===================== resolv.conf.d =====================#
# Interface wan
nameserver 218.85.152.99
nameserver 218.85.157.99

#===================== 测试本机网络连接 =====================#
HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: private, no-cache, no-store, proxy-revalidate, no-transform
Connection: keep-alive
Content-Length: 277
Content-Type: text/html
Date: Sat, 26 Sep 2020 06:07:46 GMT
Etag: "575e1f72-115"
Last-Modified: Mon, 13 Jun 2016 02:50:26 GMT
Pragma: no-cache
Server: bfe/1.0.8.18


#===================== 测试本机网络下载 =====================#
HTTP/1.1 200 Connection established

HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 78
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: text/plain; charset=utf-8
ETag: "97afa4c0bbc75244ccc8a610b442a7a9b44a59804544f5c8f9c969cd2a952777"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
Via: 1.1 varnish (Varnish/6.0)
X-GitHub-Request-Id: 4F0A:698D:ABC85:C8551:5F6ED6D5
Accept-Ranges: bytes
Date: Sat, 26 Sep 2020 06:07:46 GMT
Via: 1.1 varnish
X-Served-By: cache-hkg17927-HKG
X-Cache: HFM, HIT
X-Cache-Hits: 0, 1
X-Timer: S1601100467.917121,VS0,VE4
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
X-Fastly-Request-ID: cebfdc0532b1335978cee915445dc1e84d992df7
Expires: Sat, 26 Sep 2020 06:12:46 GMT
Source-Age: 193


#===================== 最近运行日志 =====================#
time="2020-09-26T06:07:08Z" level=info msg="[TCP] 192.168.1.6:2347 --> myip.ipip.net match IPCIDR(117.22.0.0/15) using 🎯 全球直连[DIRECT]"
time="2020-09-26T06:07:08Z" level=info msg="[TCP] 192.168.1.6:2360 --> api.ipify.org match Match() using 🐟 漏网之鱼[🇭🇰 PBGP 沪港 01 [0.4]]"
time="2020-09-26T06:07:08Z" level=info msg="[TCP] 192.168.1.6:2345 --> api-ipv4.ip.sb match Match() using 🐟 漏网之鱼[🇭🇰 PBGP 沪港 01 [0.4]]"
time="2020-09-26T06:07:08Z" level=info msg="[TCP] 192.168.1.6:2358 --> api.ttt.sh match Match() using 🐟 漏网之鱼[🇭🇰 PBGP 沪港 01 [0.4]]"
time="2020-09-26T06:07:08Z" level=info msg="[TCP] 192.168.1.6:2354 --> api.ipify.org match Match() using 🐟 漏网之鱼[🇭🇰 PBGP 沪港 01 [0.4]]"
time="2020-09-26T06:07:08Z" level=info msg="[TCP] 192.168.1.6:2364 --> camo.githubusercontent.com match DomainKeyword(github) using 🚀 节点选择[🇭🇰 PBGP 沪港 01 [0.4]]"
time="2020-09-26T06:07:08Z" level=info msg="[TCP] 192.168.1.6:2362 --> camo.githubusercontent.com match DomainKeyword(github) using 🚀 节点选择[🇭🇰 PBGP 沪港 01 [0.4]]"
time="2020-09-26T06:07:08Z" level=info msg="[TCP] 192.168.1.6:2363 --> camo.githubusercontent.com match DomainKeyword(github) using 🚀 节点选择[🇭🇰 PBGP 沪港 01 [0.4]]"
time="2020-09-26T06:07:08Z" level=info msg="[TCP] 192.168.1.6:2367 --> camo.githubusercontent.com match DomainKeyword(github) using 🚀 节点选择[🇭🇰 PBGP 沪港 01 [0.4]]"
time="2020-09-26T06:07:08Z" level=info msg="[TCP] 192.168.1.1:38576 --> raw.githubusercontent.com match DomainKeyword(github) using 🚀 节点选择[🇭🇰 PBGP 沪港 01 [0.4]]"
time="2020-09-26T06:07:08Z" level=info msg="[TCP] 192.168.1.6:2366 --> camo.githubusercontent.com match DomainKeyword(github) using 🚀 节点选择[🇭🇰 PBGP 沪港 01 [0.4]]"
time="2020-09-26T06:07:09Z" level=info msg="[TCP] 192.168.1.6:2368 --> 101.227.162.105 match IPCIDR(101.224.0.0/13) using 🌏 国内媒体[DIRECT]"
time="2020-09-26T06:07:10Z" level=info msg="[TCP] 192.168.1.6:2369 --> s1.url.cn match IPCIDR(110.80.0.0/13) using 🎯 全球直连[DIRECT]"
time="2020-09-26T06:07:10Z" level=info msg="[TCP] 192.168.1.6:2370 --> s1.url.cn match IPCIDR(110.80.0.0/13) using 🎯 全球直连[DIRECT]"
time="2020-09-26T06:07:10Z" level=info msg="[TCP] 192.168.1.6:2371 --> s1.url.cn match IPCIDR(110.80.0.0/13) using 🎯 全球直连[DIRECT]"
time="2020-09-26T06:07:10Z" level=info msg="[TCP] 192.168.1.6:2372 --> s1.url.cn match IPCIDR(110.80.0.0/13) using 🎯 全球直连[DIRECT]"
time="2020-09-26T06:07:10Z" level=info msg="[TCP] 192.168.1.6:2373 --> web.qun.qq.com match IPCIDR(101.80.0.0/12) using 🎯 全球直连[DIRECT]"
time="2020-09-26T06:07:17Z" level=info msg="[TCP] 192.168.1.7:54434 --> 61.151.165.101 match IPCIDR(61.128.0.0/10) using 🎯 全球直连[DIRECT]"
time="2020-09-26T06:07:24Z" level=info msg="[TCP] 192.168.1.6:2380 --> officeclient.microsoft.com match Match() using 🐟 漏网之鱼[🇭🇰 PBGP 沪港 01 [0.4]]"
time="2020-09-26T06:07:24Z" level=info msg="[TCP] 192.168.1.6:2381 --> officeclient.microsoft.com match Match() using 🐟 漏网之鱼[🇭🇰 PBGP 沪港 01 [0.4]]"
time="2020-09-26T06:07:25Z" level=info msg="[TCP] 192.168.1.6:2382 --> ecs.office.com match Match() using 🐟 漏网之鱼[🇭🇰 PBGP 沪港 01 [0.4]]"
time="2020-09-26T06:07:25Z" level=info msg="[TCP] 192.168.1.6:2383 --> ecs.office.com match Match() using 🐟 漏网之鱼[🇭🇰 PBGP 沪港 01 [0.4]]"
time="2020-09-26T06:07:25Z" level=info msg="[TCP] 192.168.1.6:2387 --> ecs.office.com match Match() using 🐟 漏网之鱼[🇭🇰 PBGP 沪港 01 [0.4]]"
time="2020-09-26T06:07:25Z" level=info msg="[TCP] 192.168.1.6:2384 --> ecs.office.com match Match() using 🐟 漏网之鱼[🇭🇰 PBGP 沪港 01 [0.4]]"
time="2020-09-26T06:07:25Z" level=info msg="[TCP] 192.168.1.6:2386 --> ecs.office.com match Match() using 🐟 漏网之鱼[🇭🇰 PBGP 沪港 01 [0.4]]"
time="2020-09-26T06:07:25Z" level=info msg="[TCP] 192.168.1.6:2385 --> ecs.office.com match Match() using 🐟 漏网之鱼[🇭🇰 PBGP 沪港 01 [0.4]]"
time="2020-09-26T06:07:26Z" level=info msg="[TCP] 192.168.1.6:2388 --> mrodevicemgr.officeapps.live.com match DomainSuffix(live.com) using 🚀 节点选择[🇭🇰 PBGP 沪港 01 [0.4]]"
time="2020-09-26T06:07:40Z" level=info msg="[TCP] 192.168.1.1:38678 --> cdn.jsdelivr.net match IPCIDR(120.32.0.0/13) using 🎯 全球直连[DIRECT]"
time="2020-09-26T06:07:46Z" level=info msg="[TCP] 192.168.1.7:41293 --> 91.108.56.145 match IPCIDR(91.108.0.0/16) using 📲 电报消息[🇭🇰 PBGP 沪港 01 [0.4]]"
time="2020-09-26T06:07:46Z" level=info msg="[TCP] 192.168.1.1:38694 --> raw.githubusercontent.com match DomainKeyword(github) using 🚀 节点选择[🇭🇰 PBGP 沪港 01 [0.4]]"

**Comment by lzkgbld** [comment]
我不知道为什么我也是这样，挂了代理是epic客户端的好友列表是离线状态的，而且不能下载游戏库或者虚幻引擎的任何东西...

**Comment by CurssedCoffin** [comment]
是的，我也是离线，但可以下载游戏

**Comment by hcym** [comment]
这玩意严重依赖性能，armv8都时不时的出个小毛病，只有x86没有任何问题
