### ISSUE TITLE
Openwrt. Luci 18.06.04 无法正常运行openclash 程序

### ISSUE THREAD

**Issue by pinotao** [vernesong/OpenClash#794]
1、已完成配置设置（订阅）
2、已更新内核；架构是mips-24kc选择的linux-mips-hardfloat
3、启动程序过程中，在最后一步提示启动失败。运行日志只有这一行信息。运行日志：
2020-09-24 10:51:54 OpenClash Can Not Start, Please Check The Error Info And Try Again
4、重新更新了下Dev内核。提示运行成功了。然后过了一会儿，一瞬间显示成功，然后又挂了。运行日志：
2020-09-24 10:51:54 OpenClash Can Not Start, Please Check The Error Info And Try Again
2020-09-24 10:57:24 OpenClash 【Dev】 Core Update Successful
2020-09-24 10:57:36 OpenClash Start Successful
2020-09-24 10:59:16 Watchdog: Clash Core Problem, Restart.

调试日志：
OpenClash 调试日志

生成时间: 2020-09-24 11:05:55
插件版本: v0.40.6-beta

#===================== 系统信息 =====================#
主机型号: GainStrong Oolite V5.2-Dev
固件版本: 
LuCI版本: git-20.213.35591-16dfb55-1
内核版本: 4.9.214
处理器架构: 

#此项在使用Tun模式时应为ACCEPT
防火墙转发: ACCEPT

#此项有值时建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: 

#此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 

#===================== 依赖检查 =====================#
dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
jsonfilter: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
iptables-mod-tproxy: 已安装
kmod-tun(TUN模式): 未安装
luci-compat(Luci-19.07): 已安装

#===================== 内核检查 =====================#
运行状态: 未运行
已选择的架构: linux-mips-hardfloat

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 
Tun内核文件: 不存在
Tun内核运行权限: 否

Game内核版本: 
Game内核文件: 不存在
Game内核运行权限: 否

Dev内核版本: 
Dev内核文件: 存在
Dev内核运行权限: 正常

#===================== 插件设置 =====================#
当前配置文件: /etc/openclash/config/ss.yaml
运行模式: redir-host
默认代理模式: rule
UDP流量转发: 启用
DNS劫持: 启用
自定义DNS: 停用
IPV6-DNS解析: 停用
禁用Dnsmasq缓存: 停用
自定义规则: 停用
仅允许内网: 停用
仅代理命中规则流量: 停用
绕过中国大陆IP: 停用

#启动异常时建议关闭此项后重试
保留配置: 停用
第三方规则: 停用

#===================== 配置文件 =====================#
port: 7890
socks-port: 7891
allow-lan: true
bind-address: "*"
ipv6: false
mode: rule
log-level: silent
external-controller: 0.0.0.0:9090
secret: "123456"
redir-port: 7892
external-ui: "/usr/share/openclash/dashboard"
hosts:
##Custom HOSTS##
#  experimental hosts, support wildcard (e.g. *.clash.dev Even *.foo.*.example.com)
#  static domain has a higher priority than wildcard domain (foo.example.com > *.example.com)
#  NOTE: hosts don't work with `fake-ip`

#  '*.clash.dev': 127.0.0.1
#  'alpha.clash.dev': '::1'
##Custom HOSTS END##
dns:
  use-hosts: true
  enhanced-mode: redir-host
  listen: 127.0.0.1:7874
  enable: true
  ipv6: false
  nameserver:
    - 114.114.114.114
    - 223.5.5.5
  fallback:
    - tls://dns.google
  fallback-filter:
    geoip: true
    ipcidr:
      - 0.0.0.0/8
      - 10.0.0.0/8
      - 100.64.0.0/10
      - 127.0.0.0/8
      - 169.254.0.0/16
      - 172.16.0.0/12
      - 192.0.0.0/24
      - 192.0.2.0/24
      - 192.88.99.0/24
      - 192.168.0.0/16
      - 198.18.0.0/15
      - 198.51.100.0/24
      - 203.0.113.0/24
      - 224.0.0.0/4
      - 240.0.0.0/4
      - 255.255.255.255/32

#===================== 防火墙设置 =====================#

#NAT chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    prerouting_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom prerouting rule chain */
2    zone_lan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
3    zone_wan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
4    zone_wan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         

#Mangle chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         

#===================== 路由表状态 =====================#
#route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.0.1     0.0.0.0         UG    0      0        0 eth2
100.64.32.0     0.0.0.0         255.255.255.0   U     0      0        0 br-lan
192.168.0.0     0.0.0.0         255.255.255.0   U     0      0        0 eth2
#ip route list
default via 192.168.0.1 dev eth2 proto static src 192.168.0.100 
100.64.32.0/24 dev br-lan proto kernel scope link src 100.64.32.1 
192.168.0.0/24 dev eth2 proto kernel scope link src 192.168.0.100 
#ip rule show
0:	from all lookup local 
32766:	from all lookup main 
32767:	from all lookup default 

#===================== 端口占用状态 =====================#

#===================== 测试本机DNS查询 =====================#
Server:		127.0.0.1
Address:	127.0.0.1#53

Name:      www.baidu.com
www.baidu.com	canonical name = www.a.shifen.com
Name:      www.a.shifen.com
Address 1: 112.80.248.76
Address 2: 112.80.248.75
www.baidu.com	canonical name = www.a.shifen.com

#===================== resolv.conf.auto =====================#
# Interface wwan
nameserver 192.168.0.1

#===================== 测试本机网络连接 =====================#
HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: private, no-cache, no-store, proxy-revalidate, no-transform
Connection: keep-alive
Content-Length: 277
Content-Type: text/html
Date: Thu, 24 Sep 2020 11:06:02 GMT
Etag: "575e1f7c-115"
Last-Modified: Mon, 13 Jun 2016 02:50:36 GMT
Pragma: no-cache
Server: bfe/1.0.8.18

#===================== 测试本机网络下载 =====================#

#===================== 最近运行日志 =====================#

2020-09-24 10:51:54 OpenClash Can Not Start, Please Check The Error Info And Try Again
2020-09-24 10:57:24 OpenClash 【Dev】 Core Update Successful
2020-09-24 10:57:36 OpenClash Start Successful
2020-09-24 10:59:16 Watchdog: Clash Core Problem, Restart.
2020-09-24 11:00:21 Watchdog: Clash Core Problem, Restart.
2020-09-24 11:01:25 Watchdog: Clash Core Problem, Restart.
2020-09-24 11:02:29 Watchdog: Already Restart 3 Times With Clash Core Problem, Auto-Exit.
2020-09-24 11:02:38 OpenClash 【Dev】 Core Update Successful
2020-09-24 11:02:49 OpenClash Can Not Start, Please Check The Error Info And Try Again

**Comment by vernesong** [comment]
读不出内核版本号，建议试试软浮点版本

**Comment by vernesong** [comment]
不行的话说一个选择了fpu模拟的固件

**Comment by pinotao** [comment]
> 读不出内核版本号，建议试试软浮点版本

换了软浮点，版本号可以诶读取到了。但还是启动失败。日志如下：
OpenClash 调试日志

生成时间: 2020-09-24 12:53:56
插件版本: v0.40.6-beta

#===================== 系统信息 =====================#
主机型号: GainStrong Oolite V5.2-Dev
固件版本: 
LuCI版本: git-20.213.35591-16dfb55-1
内核版本: 4.9.214
处理器架构: mips_24kc

#此项在使用Tun模式时应为ACCEPT
防火墙转发: ACCEPT

#此项有值时建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: 

#此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 

#===================== 依赖检查 =====================#
dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
jsonfilter: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
iptables-mod-tproxy: 已安装
kmod-tun(TUN模式): 未安装
luci-compat(Luci-19.07): 已安装

#===================== 内核检查 =====================#
运行状态: 未运行
已选择的架构: linux-mips-softfloat

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 
Tun内核文件: 存在
Tun内核运行权限: 正常

Game内核版本: 
Game内核文件: 不存在
Game内核运行权限: 否

Dev内核版本: v1.1.0-19-g8766287
Dev内核文件: 存在
Dev内核运行权限: 正常

#===================== 插件设置 =====================#
当前配置文件: /etc/openclash/config/ss.yaml
运行模式: fake-ip
默认代理模式: rule
UDP流量转发: 启用
DNS劫持: 启用
自定义DNS: 停用
IPV6-DNS解析: 停用
禁用Dnsmasq缓存: 停用
自定义规则: 停用
仅允许内网: 停用
仅代理命中规则流量: 停用
绕过中国大陆IP: 停用

#启动异常时建议关闭此项后重试
保留配置: 停用

#启动异常时建议关闭此项后重试
第三方规则: lhie1
第三方规则策略组设置:
GlobalTV: Auto
AsianTV: Auto
Proxy: Proxy
Apple: Auto
Netflix: Auto
Spotify: Auto
Steam: Auto
AdBlock: Auto
Netease Music: 
Speedtest: Auto
Telegram: Auto
Microsoft: Auto
PayPal: Auto
Domestic: Auto
Others: Auto

读取的配置文件策略组:
Auto
Proxy
DIRECT
REJECT

#===================== 配置文件 =====================#
port: 7890
socks-port: 7891
allow-lan: true
bind-address: "*"
ipv6: false
mode: rule
log-level: silent
external-controller: 0.0.0.0:9090
secret: "123456"
redir-port: 7892
external-ui: "/usr/share/openclash/dashboard"
dns:
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  listen: 127.0.0.1:7874
  enable: true
  ipv6: false
  fake-ip-filter:
##Custom fake-ip-filter##
  - '*.lan'
  - 'time.windows.com'
  - 'time.nist.gov'
  - 'time.apple.com'
  - 'time.asia.apple.com'
  - '*.ntp.org.cn'
  - '*.openwrt.pool.ntp.org'
  - 'time1.cloud.tencent.com'
  - 'time.ustc.edu.cn'
  - 'pool.ntp.org'
  - 'ntp.ubuntu.com'
  - 'ntp.aliyun.com'
  - 'ntp1.aliyun.com'
  - 'ntp2.aliyun.com'
  - 'ntp3.aliyun.com'
  - 'ntp4.aliyun.com'
  - 'ntp5.aliyun.com'
  - 'ntp6.aliyun.com'
  - 'ntp7.aliyun.com'
  - 'time1.aliyun.com'
  - 'time2.aliyun.com'
  - 'time3.aliyun.com'
  - 'time4.aliyun.com'
  - 'time5.aliyun.com'
  - 'time6.aliyun.com'
  - 'time7.aliyun.com'
  - '*.time.edu.cn'
  - 'time1.apple.com'
  - 'time2.apple.com'
  - 'time3.apple.com'
  - 'time4.apple.com'
  - 'time5.apple.com'
  - 'time6.apple.com'
  - 'time7.apple.com'
  - 'time1.google.com'
  - 'time2.google.com'
  - 'time3.google.com'
  - 'time4.google.com'
  - 'music.163.com'
  - '*.music.163.com'
  - '*.126.net'
  - 'musicapi.taihe.com'
  - 'music.taihe.com'
  - 'songsearch.kugou.com'
  - 'trackercdn.kugou.com'
  - '*.kuwo.cn'
  - 'api-jooxtt.sanook.com'
  - 'api.joox.com'
  - 'joox.com'
  - 'y.qq.com'
  - '*.y.qq.com'
  - 'streamoc.music.tc.qq.com'
  - 'mobileoc.music.tc.qq.com'
  - 'isure.stream.qqmusic.qq.com'
  - 'dl.stream.qqmusic.qq.com'
  - 'aqqmusic.tc.qq.com'
  - 'amobile.music.tc.qq.com'
  - '*.xiami.com'
  - '*.music.migu.cn'
  - 'music.migu.cn'
  - '*.msftconnecttest.com'
  - '*.msftncsi.com'
  - 'localhost.ptlogin2.qq.com'
  - '*.*.*.srv.nintendo.net'
  - '*.*.stun.playstation.net'
  - 'xbox.*.*.microsoft.com'
  - '*.*.xboxlive.com'
  - 'proxy.golang.org'
##Custom fake-ip-filter END##
  nameserver:
    - 114.114.114.114
    - 223.5.5.5
  fallback:
    - tls://dns.google
  fallback-filter:
    geoip: true
    ipcidr:
      - 0.0.0.0/8
      - 10.0.0.0/8
      - 100.64.0.0/10
      - 127.0.0.0/8
      - 169.254.0.0/16
      - 172.16.0.0/12
      - 192.0.0.0/24
      - 192.0.2.0/24
      - 192.88.99.0/24
      - 192.168.0.0/16
      - 198.18.0.0/15
      - 198.51.100.0/24
      - 203.0.113.0/24
      - 224.0.0.0/4
      - 240.0.0.0/4
      - 255.255.255.255/32

#===================== 防火墙设置 =====================#

#NAT chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    prerouting_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom prerouting rule chain */
2    zone_lan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
3    zone_wan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
4    zone_wan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         

#Mangle chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         

#===================== 路由表状态 =====================#
#route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.0.1     0.0.0.0         UG    0      0        0 eth2
100.64.32.0     0.0.0.0         255.255.255.0   U     0      0        0 br-lan
192.168.0.0     0.0.0.0         255.255.255.0   U     0      0        0 eth2
#ip route list
default via 192.168.0.1 dev eth2 proto static src 192.168.0.100 
100.64.32.0/24 dev br-lan proto kernel scope link src 100.64.32.1 
192.168.0.0/24 dev eth2 proto kernel scope link src 192.168.0.100 
#ip rule show
0:	from all lookup local 
32766:	from all lookup main 
32767:	from all lookup default 

#===================== 端口占用状态 =====================#

#===================== 测试本机DNS查询 =====================#
Server:		127.0.0.1
Address:	127.0.0.1#53

Name:      www.baidu.com
www.baidu.com	canonical name = www.a.shifen.com
Name:      www.a.shifen.com
Address 1: 112.80.248.75
Address 2: 112.80.248.76
www.baidu.com	canonical name = www.a.shifen.com

#===================== resolv.conf.auto =====================#
# Interface wwan
nameserver 192.168.0.1

#===================== 测试本机网络连接 =====================#
HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: private, no-cache, no-store, proxy-revalidate, no-transform
Connection: keep-alive
Content-Length: 277
Content-Type: text/html
Date: Thu, 24 Sep 2020 12:54:05 GMT
Etag: "575e1f7c-115"
Last-Modified: Mon, 13 Jun 2016 02:50:36 GMT
Pragma: no-cache
Server: bfe/1.0.8.18


#===================== 测试本机网络下载 =====================#

#===================== 最近运行日志 =====================#
2020-09-24 10:51:54 OpenClash Can Not Start, Please Check The Error Info And Try Again
2020-09-24 10:57:24 OpenClash 【Dev】 Core Update Successful
2020-09-24 10:57:36 OpenClash Start Successful
2020-09-24 10:59:16 Watchdog: Clash Core Problem, Restart.
2020-09-24 11:00:21 Watchdog: Clash Core Problem, Restart.
2020-09-24 11:01:25 Watchdog: Clash Core Problem, Restart.
2020-09-24 11:02:29 Watchdog: Already Restart 3 Times With Clash Core Problem, Auto-Exit.
2020-09-24 11:02:38 OpenClash 【Dev】 Core Update Successful
2020-09-24 11:02:49 OpenClash Can Not Start, Please Check The Error Info And Try Again
nohup: failed to run command ‘/etc/openclash/clash’: No such file or directory
2020-09-24 11:13:54 OpenClash Can Not Start, Try Use Backup Rules Start Again
nohup: failed to run command ‘/etc/openclash/clash’: No such file or directory
2020-09-24 11:13:54 OpenClash Can Not Start, Please Check The Error Info And Try Again
2020-09-24 11:15:17 OpenClash 【Tun】 Core Update Successful
2020-09-24 11:19:09 OpenClash Can Not Start, Try Use Backup Rules Start Again
2020-09-24 11:19:09 OpenClash Can Not Start, Please Check The Error Info And Try Again
2020-09-24 11:27:28 OpenClash Can Not Start, Try Use Backup Rules Start Again
2020-09-24 11:27:28 OpenClash Can Not Start, Please Check The Error Info And Try Again
2020-09-24 11:29:14 Faild to Download Rule-Provider File, Please Check The Error Info And Try Again
2020-09-24 11:44:36 OpenClash 【Dev】 Core Update Successful
2020-09-24 11:44:48 Faild to Download Rule-Provider File, Please Check The Error Info And Try Again
2020-09-24 12:36:31 Faild to Download Rule-Provider File, Please Check The Error Info And Try Again
2020-09-24 12:39:31 Config 【ss】 Update Successful
2020-09-24 12:40:14 Warning: Because of The Different Porxy-Group's Name, Stop Setting The Other Rules!
2020-09-24 12:40:14 OpenClash Can Not Start, Try Use Backup Rules Start Again
2020-09-24 12:40:14 OpenClash Can Not Start, Please Check The Error Info And Try Again
2020-09-24 12:42:57 Warning: Because of The Different Porxy-Group's Name, Stop Setting The Other Rules!
2020-09-24 12:42:57 OpenClash Can Not Start, Try Use Backup Rules Start Again
2020-09-24 12:42:57 OpenClash Can Not Start, Please Check The Error Info And Try Again
2020-09-24 12:44:59 Faild to Download Rule-Provider File, Please Check The Error Info And Try Again

**Comment by pinotao** [comment]
提示开启了TUN模式的功能相关的，跟切换Fake-IP模式有关?

**Comment by pinotao** [comment]
把订阅文件改成上传解决了。但是好像扛不住。一会儿就内部崩溃了。

**Comment by pinotao** [comment]
> 读不出内核版本号，建议试试软浮点版本

改为软浮点可以了，但是mips-24kc这个扛不住。用了一会儿就内部泄露扛不住了。有的解吗？

**Comment by pinotao** [comment]
还有一个问题，clash的控制面板没有内容。yacd是正常的。 @vernesong

**Comment by vernesong** [comment]
> 还有一个问题，clash的控制面板没有内容。yacd是正常的。 @vernesong

注销重新登录

**Comment by pinotao** [comment]
另外发现一个问题，不知道是不是Luci 18/06.04的适配原因，配置文件订阅，检查通过后。在初始化过程会解析异常。然后通过将配置文件下载到本地，改为手动上传，就能成功。 @vernesong

**Comment by zhihuiyuze** [comment]
`生成时间: 2020-11-05 11:01:19
插件版本: v0.40.15-beta
隐私提示: 上传此日志前请注意检查、屏蔽公网IP、节点、密码等相关敏感信息

```

#===================== 系统信息 =====================#
主机型号: QEMU Standard PC (i440FX + PIIX, 1996)
固件版本: OpenWrt 19.07.4 r11208-ce6496d796
LuCI版本: git-20.306.44214-6ad517e-1
内核版本: 4.14.195
处理器架构: x86_64

#此项在使用Tun模式时应为ACCEPT
防火墙转发: REJECT

#此项有值时建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: server

#此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 127.0.0.1#5353

#===================== 依赖检查 =====================#
dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
jsonfilter: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
iptables-mod-tproxy: 已安装
iptables-mod-extra: 已安装
libcap: 已安装
libcap-bin: 已安装
kmod-tun(TUN模式): 已安装
luci-compat(Luci-19.07): 已安装

#===================== 内核检查 =====================#
运行状态: 未运行
已选择的架构: linux-amd64

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 
Tun内核文件: 存在
Tun内核运行权限: 正常

Game内核版本: 
Game内核文件: 存在
Game内核运行权限: 正常

Dev内核版本: 
Dev内核文件: 存在
Dev内核运行权限: 正常`
奇怪，为什么我打x86_64的也检测不出内核

**Comment by zhihuiyuze** [comment]
很奇怪，重启openwrt后就能启动成功。关掉再打开就不行啦
