### ISSUE TITLE
官方源码编译使用 更新都直接说网络不行

### ISSUE THREAD

**Issue by nameless3721** [vernesong/OpenClash#8]
![image](https://user-images.githubusercontent.com/50364156/61955594-4e2e8d00-aff6-11e9-9634-0f6f507917e0.png)
![image](https://user-images.githubusercontent.com/50364156/61955612-57b7f500-aff6-11e9-835c-28b85370b707.png)
![image](https://user-images.githubusercontent.com/50364156/61955638-66061100-aff6-11e9-8f9c-29598d3a3570.png)
大概都会这样 实际自己上传配置和核心能使用  用lean的源码编译就没问题

**Comment by vernesong** [comment]
wget没装吧

**Comment by nameless3721** [comment]
> wget没装吧
不好意思 还真是。。重新编译选上wget就ok了
