### ISSUE TITLE
默认启动失败，而Backup文件夹里相同配置启动成功。

### ISSUE THREAD

**Issue by a315344690** [vernesong/OpenClash#800]
点击启动服务后，提示如下：
错误: OpenClash 启动失败，尝试还原第三方规则并重新启动 Clash 主程序...

然后使用backup config启动成功了，  默认配置和Backup配置一致。
日志如下：
time="2020-09-27T09:43:28Z" level=fatal msg="Parse config error: proxy group[0]: '美国 Magic IEPL 中继 1' not found"
2020-09-27 17:43:21 OpenClash Can Not Start, Try Use Backup Rules Start Again

[config.zip](https://github.com/vernesong/OpenClash/files/5288078/config.zip)

OpenClash 调试日志

生成时间: 2020-09-27 17:45:05
插件版本: v0.40.6-beta

#===================== 系统信息 =====================#
主机型号: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz : 4 Core 4 Thread
固件版本: OpenWrt SNAPSHOT r2869-88d85bb57
LuCI版本: git-20.223.26773-d18ef13-1
内核版本: 5.4.61
处理器架构: x86_64

#此项在使用Tun模式时应为ACCEPT
防火墙转发: ACCEPT

#此项有值时建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: 

#此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 127.0.0.1#5353

#===================== 依赖检查 =====================#
dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
jsonfilter: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
iptables-mod-tproxy: 已安装
kmod-tun(TUN模式): 已安装
luci-compat(Luci-19.07): 已安装

#===================== 内核检查 =====================#
运行状态: 运行中
已选择的架构: linux-amd64

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 2020.09.27.gc2ae5ea
Tun内核文件: 存在
Tun内核运行权限: 正常

Game内核版本: 
Game内核文件: 不存在
Game内核运行权限: 否

Dev内核版本: 
Dev内核文件: 不存在
Dev内核运行权限: 否

#===================== 插件设置 =====================#
当前配置文件: /etc/openclash/config/config.yaml
运行模式: redir-host-mix
默认代理模式: rule
UDP流量转发: 停用
DNS劫持: 启用
自定义DNS: 启用
IPV6-DNS解析: 停用
禁用Dnsmasq缓存: 启用
自定义规则: 启用
仅允许内网: 停用
仅代理命中规则流量: 停用
绕过中国大陆IP: 停用

#启动异常时建议关闭此项后重试
保留配置: 停用
第三方规则: 停用

#===================== 自定义规则 一 =====================#
##- DOMAIN-SUFFIX,google.com,Proxy 匹配域名后缀(交由Proxy代理服务器组)
##- DOMAIN-KEYWORD,google,Proxy 匹配域名关键字(交由Proxy代理服务器组)
##- DOMAIN,google.com,Proxy 匹配域名(交由Proxy代理服务器组)
##- DOMAIN-SUFFIX,ad.com,REJECT 匹配域名后缀(拒绝)
##- IP-CIDR,127.0.0.0/8,DIRECT 匹配数据目标IP(直连)
##- SRC-IP-CIDR,192.168.1.201/32,DIRECT 匹配数据发起IP(直连)
##- DST-PORT,80,DIRECT 匹配数据目标端口(直连)
##- SRC-PORT,7777,DIRECT 匹配数据源端口(直连)

##DNS
- DST-PORT,853,DIRECT

- IP-CIDR,1.1.1.100/32,Proxy

- DOMAIN-KEYWORD,zerotier,DIRECT
- DOMAIN-SUFFIX,ifreenet.com,DIRECT

# Local Area Network
- IP-CIDR,192.168.0.0/16,DIRECT
- IP-CIDR,10.0.0.0/8,DIRECT
- IP-CIDR,172.16.0.0/12,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- IP-CIDR,100.64.0.0/10,DIRECT
- IP-CIDR,224.0.0.0/4,DIRECT
- SRC-IP-CIDR,10.0.0.105/32,Proxy

# > DMM
#- DOMAIN-SUFFIX,dmm.co.jp,日本
#- DOMAIN-SUFFIX,dmm.com,日本
#- DOMAIN-SUFFIX,dmm-extension.com,日本

# > Backup
- DOMAIN-SUFFIX,rfi.fr,Backup
- DOMAIN-SUFFIX,rfa.org,Backup
- DOMAIN-KEYWORD,dafahao,Backup
- DOMAIN-KEYWORD,minghui,Backup
- DOMAIN-KEYWORD,dongtaiwang,Backup
- DOMAIN-KEYWORD,epochtimes,Backup
- DOMAIN-KEYWORD,ntdtv,Backup
- DOMAIN-KEYWORD,falundafa,Backup
- DOMAIN-KEYWORD,wujieliulan,Backup

#===================== 自定义规则 二 =====================#
##- DOMAIN-SUFFIX,google.com,Proxy 匹配域名后缀(交由Proxy代理服务器组)
##- DOMAIN-KEYWORD,google,Proxy 匹配域名关键字(交由Proxy代理服务器组)
##- DOMAIN,google.com,Proxy 匹配域名(交由Proxy代理服务器组)
##- DOMAIN-SUFFIX,ad.com,REJECT 匹配域名后缀(拒绝)
##- IP-CIDR,127.0.0.0/8,DIRECT 匹配数据目标IP(直连)
##- SRC-IP-CIDR,192.168.1.201/32,DIRECT 匹配数据发起IP(直连)
##- DST-PORT,80,DIRECT 匹配数据目标端口(直连)
##- SRC-PORT,7777,DIRECT 匹配数据源端口(直连)

- GEOIP,HK,香港Anycast
- GEOIP,AU,新加坡
- GEOIP,SG,新加坡
- GEOIP,US,美国Anycast
- GEOIP,CA,美国Anycast
- GEOIP,KR,韩国
- GEOIP,RU,日本
- GEOIP,JP,日本
- GEOIP,TW,台湾
- GEOIP,IE,欧洲
- GEOIP,NL,欧洲
- GEOIP,DE,欧洲
- GEOIP,UK,欧洲
- GEOIP,FR,欧洲
- GEOIP,IT,欧洲
- GEOIP,BE,欧洲
- GEOIP,DK,欧洲

#===================== 配置文件 =====================#
port: 7890

# Port of SOCKS5 proxy server on the local end
# 此项将被接管
socks-port: 7891

# Transparent proxy server port for Linux and macOS
# 此项将被接管
redir-port: 7892
 
# HTTP(S) and SOCKS5 server on the same port
mixed-port: 8888

# Set to true to allow connections to the local-end server from
# other LAN IP addresses
# 此项将被接管为true
allow-lan: true
bind-address: "*"

# This is only applicable when `allow-lan` is `true`
# '*': bind all IP addresses
# 192.168.122.11: bind a single IPv4 address
# "[aaaa::a8aa:ff:fe09:57d8]": bind a single IPv6 address
# HTTP(S)\SOCKS5 监听地址，此项将被接管为all

# Clash router working mode
# rule: rule-based packet routing
# global: all packets will be forwarded to a single endpoint
# direct: directly forward the packets to the Internet
# 此项将被接管
ipv6: false
mode: rule

# Clash by default prints logs to STDOUT
# info / warning / error / debug / silent
# 此项将被接管
log-level: info

# When set to false, resolver won't translate hostnames to IPv6 addresses
# 此项将被接管

# RESTful web API listening address
# 此项将被接管
external-controller: 0.0.0.0:9090

# A relative path to the configuration directory or an absolute path to a
# directory in which you put some static web resource. Clash core will then
# serve it at `http://{{external-controller}}/ui`.
# 此项将被接管
external-ui: "/usr/share/openclash/dashboard"

# Secret for the RESTful API (optional)
# Authenticate by spedifying HTTP header `Authorization: Bearer ${secret}`
# ALWAYS set a secret if RESTful API is listening on 0.0.0.0
# 此项将被接管
secret: "123456"

# authentication of local SOCKS5/HTTP(S) server
# 此项将被接管
tun:
  enable: true
  stack: system
  dns-hijack:
  - tcp://8.8.8.8:53
  - tcp://8.8.4.4:53
hosts:
##Custom HOSTS##
#  experimental hosts, support wildcard (e.g. *.clash.dev Even *.foo.*.example.com)
#  static domain has a higher priority than wildcard domain (foo.example.com > *.example.com)
#  NOTE: hosts don't work with `fake-ip`

#  '*.clash.dev': 127.0.0.1
#  'alpha.clash.dev': '::1'

  'ct.ifreenet.ltd': '10.0.0.1'
  'cm.ifreenet.ltd': '10.0.0.1'
  'home.ifreenet.ltd': '10.0.0.1'
##Custom HOSTS END##
dns:
  enable: true
  ipv6: false
  listen: 127.0.0.1:5353
  # These nameservers are used to resolve the DNS nameserver hostnames below.
  # Specify IP addresses only
  default-nameserver:
  - 114.114.114.114
  - 8.8.8.8
  enhanced-mode: redir-host # or fake-ip # 此项将被接管
  use-hosts: true
  # Hostnames in this list will not be resolved with fake IPs
  # i.e. questions to these domain names will always be answered with their
  # real IP addresses
  # fake-ip-filter:
  #   - '*.lan'
  #   - localhost.ptlogin2.qq.com
  
  # Supports UDP, TCP, DoT, DoH. You can specify the port to connect to.
  # All DNS questions are sent directly to the nameserver, without proxies
  # involved. Clash answers the DNS question with the first result gathered.
  nameserver:
##Custom DNS##
  - 10.0.0.1:6053
  fallback:
  - tls://1.0.0.1:853
  - tls://8.8.4.4:853
  - tls://8.8.8.8:853
  fallback-filter:
    geoip: true # default
    ipcidr: # ips in these subnets will be considered polluted
      - 240.0.0.0/4
  
# 以上设置您可直接覆盖到配置文件,无需更改
# Openclash 不会对下方服务器设置进行任何更改，请确保设置正确

      

#===================== 防火墙设置 =====================#

#NAT chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    ACCEPT     tcp  --  0.0.0.0/0            8.8.4.4             
2    ACCEPT     tcp  --  0.0.0.0/0            8.8.8.8             
3    REDIRECT   udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:53 redir ports 53
4    REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:53 redir ports 53
5    prerouting_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom prerouting rule chain */
6    zone_lan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
7    zone_wan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
8    openclash  tcp  --  0.0.0.0/0            0.0.0.0/0           
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         

#Mangle chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    openclash  udp  --  0.0.0.0/0            0.0.0.0/0           
2    openclash_dns_hijack  tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:53
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         

#===================== 路由表状态 =====================#
#route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.10.1    0.0.0.0         UG    0      0        0 eth1
10.0.0.0        0.0.0.0         255.255.255.0   U     0      0        0 br-lan
10.10.0.0       0.0.0.0         255.255.255.0   U     0      0        0 ztppit3jlv
172.31.12.0     10.10.0.2       255.255.255.0   UG    0      0        0 ztppit3jlv
192.168.10.0    0.0.0.0         255.255.255.0   U     0      0        0 eth1
198.18.0.0      0.0.0.0         255.255.0.0     U     0      0        0 utun
#ip route list
default via 192.168.10.1 dev eth1 proto static 
10.0.0.0/24 dev br-lan proto kernel scope link src 10.0.0.1 
10.10.0.0/24 dev ztppit3jlv proto kernel scope link src 10.10.0.1 
172.31.12.0/24 via 10.10.0.2 dev ztppit3jlv 
192.168.10.0/24 dev eth1 proto kernel scope link src 192.168.10.2 
198.18.0.0/16 dev utun proto kernel scope link src 198.18.0.1 
#ip rule show
0:	from all lookup local
32765:	from all fwmark 0x162 lookup 354
32766:	from all lookup main
32767:	from all lookup default

#===================== Tun设备状态 =====================#
ztppit3jlv: tap
utun: tun pi filter

#===================== 端口占用状态 =====================#
tcp        0      0 198.18.0.1:7777         0.0.0.0:*               LISTEN      834/clash
tcp        0      0 :::9090                 :::*                    LISTEN      834/clash
tcp        0      0 :::7890                 :::*                    LISTEN      834/clash
tcp        0      0 :::7891                 :::*                    LISTEN      834/clash
tcp        0      0 :::7892                 :::*                    LISTEN      834/clash
tcp        0      0 :::8888                 :::*                    LISTEN      834/clash
udp        0      0 127.0.0.1:5353          0.0.0.0:*                           834/clash
udp        0      0 198.18.0.1:7777         0.0.0.0:*                           834/clash
udp        0      0 :::8888                 :::*                                834/clash
udp        0      0 :::7891                 :::*                                834/clash
udp        0      0 :::7892                 :::*                                834/clash

#===================== 测试本机DNS查询 =====================#
Server:		127.0.0.1
Address:	127.0.0.1#53

Name:      www.baidu.com
www.baidu.com	canonical name = www.a.shifen.com
Name:      www.a.shifen.com
Address 1: 39.156.66.14
Address 2: 39.156.66.18
*** Can't find www.baidu.com: No answer

#===================== 测试本机网络连接 =====================#
HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: private, no-cache, no-store, proxy-revalidate, no-transform
Connection: keep-alive
Content-Length: 277
Content-Type: text/html
Date: Sun, 27 Sep 2020 09:45:06 GMT
Etag: "575e1f60-115"
Last-Modified: Mon, 13 Jun 2016 02:50:08 GMT
Pragma: no-cache
Server: bfe/1.0.8.18

#===================== 测试本机网络下载 =====================#
HTTP/1.1 200 Connection established

HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 78
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: text/plain; charset=utf-8
ETag: "97afa4c0bbc75244ccc8a610b442a7a9b44a59804544f5c8f9c969cd2a952777"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
Via: 1.1 varnish (Varnish/6.0)
X-GitHub-Request-Id: E6C0:01DB:8F98D:AD47A:5F704EDB
Accept-Ranges: bytes
Date: Sun, 27 Sep 2020 09:45:07 GMT
Via: 1.1 varnish
X-Served-By: cache-sea4438-SEA
X-Cache: HIT, MISS
X-Cache-Hits: 1, 0
X-Timer: S1601199907.949186,VS0,VE92
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
X-Fastly-Request-ID: be345570c0becb5d4145d1433b6c8dcc291b6bd5
Expires: Sun, 27 Sep 2020 09:50:07 GMT
Source-Age: 0

#===================== 最近运行日志 =====================#
time="2020-09-27T09:43:40Z" level=info msg="[TCP] 10.0.0.6:35294 --> 106.11.40.51 match RuleSet(国内IP白名单) using DIRECT"
time="2020-09-27T09:43:42Z" level=info msg="[TCP] 10.0.0.6:35388 --> 106.11.43.215 match RuleSet(国内IP白名单) using DIRECT"
time="2020-09-27T09:43:42Z" level=info msg="[TCP] 10.0.0.6:38960 --> accscdn.cp12.ott.cibntv.net match RuleSet(国内IP白名单) using DIRECT"
time="2020-09-27T09:43:42Z" level=info msg="[TCP] 10.0.0.1:50325 --> play.google.com match GeoIP(US) using 美国Anycast[美国 Magic IEPL 中继 1]"
time="2020-09-27T09:43:43Z" level=info msg="[TCP] 10.0.0.1:50123 --> clients4.google.com match GeoIP(US) using 美国Anycast[美国 Magic IEPL 中继 1]"
time="2020-09-27T09:43:45Z" level=info msg="[TCP] 10.0.0.6:36092 --> 39.98.22.144 match RuleSet(国内IP白名单) using DIRECT"
time="2020-09-27T09:43:49Z" level=info msg="[TCP] 10.0.0.6:45388 --> tv.aiseet.atianqi.com match RuleSet(国内IP白名单) using DIRECT"
time="2020-09-27T09:43:49Z" level=info msg="[TCP] 10.0.0.6:45390 --> tv.aiseet.atianqi.com match RuleSet(国内IP白名单) using DIRECT"
time="2020-09-27T09:43:57Z" level=info msg="[TCP] 10.0.0.1:46427 --> mtalk.google.com match GeoIP(US) using 美国Anycast[美国 Magic IEPL 中继 1]"
time="2020-09-27T09:43:58Z" level=info msg="[TCP] 10.0.0.6:35396 --> 203.208.41.66 match RuleSet(国内IP白名单) using DIRECT"
time="2020-09-27T09:43:58Z" level=info msg="[TCP] 10.0.0.6:57574 --> tv.aiseet.atianqi.com match RuleSet(国内IP白名单) using DIRECT"
time="2020-09-27T09:43:58Z" level=info msg="[TCP] 10.0.0.6:49354 --> 119.29.29.29 match RuleSet(国内IP白名单) using DIRECT"
time="2020-09-27T09:44:00Z" level=info msg="[TCP] 10.0.0.1:33391 --> www.v2ex.com match GeoIP(US) using 美国Anycast[美国 Magic IEPL 中继 1]"
time="2020-09-27T09:44:00Z" level=info msg="[TCP] 10.0.0.1:59925 --> www.v2ex.com match GeoIP(US) using 美国Anycast[美国 Magic IEPL 中继 1]"
time="2020-09-27T09:44:06Z" level=info msg="[TCP] 10.0.0.1:41981 --> 10.0.0.1 match IPCIDR(10.0.0.0/8) using DIRECT"
time="2020-09-27T09:44:06Z" level=info msg="[TCP] 10.0.0.1:48697 --> 10.0.0.1 match IPCIDR(10.0.0.0/8) using DIRECT"
time="2020-09-27T09:44:08Z" level=info msg="[TCP] 10.0.0.6:42524 --> tv.aiseet.atianqi.com match RuleSet(国内IP白名单) using DIRECT"
time="2020-09-27T09:44:08Z" level=info msg="[TCP] 10.0.0.6:42526 --> tv.aiseet.atianqi.com match RuleSet(国内IP白名单) using DIRECT"
time="2020-09-27T09:44:08Z" level=info msg="[TCP] 10.0.0.6:49360 --> 119.29.29.29 match RuleSet(国内IP白名单) using DIRECT"
time="2020-09-27T09:44:10Z" level=info msg="[TCP] 10.0.0.1:50297 --> github.com match GeoIP(SG) using 新加坡[新加坡 Magic IEPL 中继 1]"
time="2020-09-27T09:44:10Z" level=info msg="[TCP] 10.0.0.6:56148 --> connectivitycheck.gstatic.com match RuleSet(国内IP白名单) using DIRECT"
time="2020-09-27T09:44:10Z" level=info msg="[TCP] 10.0.0.1:57063 --> az213233.vo.msecnd.net match GeoIP(AU) using 新加坡[新加坡 Magic IEPL 中继 1]"
time="2020-09-27T09:44:31Z" level=info msg="[TCP] 10.0.0.6:53894 --> 47.92.21.227 match RuleSet(国内IP白名单) using DIRECT"
time="2020-09-27T09:44:31Z" level=info msg="[TCP] 10.0.0.6:53896 --> 47.92.21.227 match RuleSet(国内IP白名单) using DIRECT"
time="2020-09-27T09:44:41Z" level=info msg="[TCP] 10.0.0.6:43396 --> 116.198.14.154 match RuleSet(国内IP白名单) using DIRECT"
time="2020-09-27T09:45:00Z" level=info msg="[TCP] 10.0.0.6:55260 --> proxy-mob-cld.alicdn.com match RuleSet(国内IP白名单) using DIRECT"
time="2020-09-27T09:45:00Z" level=info msg="[TCP] 10.0.0.1:47553 --> 10.0.0.1 match IPCIDR(10.0.0.0/8) using DIRECT"
time="2020-09-27T09:45:02Z" level=info msg="[TCP] 10.0.0.1:51063 --> 10.0.0.1 match IPCIDR(10.0.0.0/8) using DIRECT"
time="2020-09-27T09:45:02Z" level=info msg="[TCP] 10.0.0.1:50995 --> 10.0.0.1 match IPCIDR(10.0.0.0/8) using DIRECT"
time="2020-09-27T09:45:06Z" level=info msg="[TCP] 10.0.0.1:38656 --> raw.githubusercontent.com match GeoIP(US) using 美国Anycast[美国 Magic IEPL 中继 1]"

**Comment by a315344690** [comment]
@vernesong

**Comment by vernesong** [comment]
time="2020-09-27T09:43:28Z" level=fatal msg="Parse config error: proxy group[0]: '美国 Magic IEPL 中继 1' not found"
2020-09-27 17:43:21 OpenClash Can Not Start, Try Use Backup Rules Start Again
找不到这个节点的意思

**Comment by a315344690** [comment]
> time="2020-09-27T09:43:28Z" level=fatal msg="Parse config error: proxy group[0]: '美国 Magic IEPL 中继 1' not found"
> 2020-09-27 17:43:21 OpenClash Can Not Start, Try Use Backup Rules Start Again
> 找不到这个节点的意思

但是配置文件已经有这个节点了，而且不明白相同的配置文件，默认启动报错，但是backup启动成功。

**Comment by a315344690** [comment]
@vernesong 
而且这个配置文件我用了很久都没什么问题  但是好像前几天更新之后就不行了  麻烦能帮忙看一下是不是bug吗 谢谢

**Comment by a315344690** [comment]
我又测试了一下  不启用第三方规则集就可以正常启动  一旦启用第三方规则集  就会启动失败

**Comment by lifetyper** [comment]
> 
> 
> 我又测试了一下 不启用第三方规则集就可以正常启动 一旦启用第三方规则集 就会启动失败

果然是一样的问题，你看一下启动失败的时候，最后“配置文件管理‘--”配置文件编辑“下面的哪个最终config文件，原始配置文件的"proxies"是不是被改成了”Proxy"

**Comment by a315344690** [comment]
> > 我又测试了一下 不启用第三方规则集就可以正常启动 一旦启用第三方规则集 就会启动失败
> 
> 果然是一样的问题，你看一下启动失败的时候，最后“配置文件管理‘--”配置文件编辑“下面的哪个最终config文件，原始配置文件里的"proxies"是不是被改成了”Proxy"，这个写法就会导致proxy节点无法被认到。
> 
> 看来这个第三方规则集的问题很普遍啊。

我已经先回退到0.40.4了  暂时就没这个问题了
