### ISSUE TITLE
openclash国内外dns设置的问题

### ISSUE THREAD

**Issue by Karmylr** [vernesong/OpenClash#804]
如题，我是一个openclash的使用者 享受着它精致的策略分流功能 但是我想把他和smartdns搭配着用（我知道smartdns心理作用大过实际作用，但是总想着能优化一点是一点哈哈哈） 但发现fake-ip下openclash并不能直接指定国内外的dns，而是在所有nameserver组里分出国外再用fallback组的  而不像passwall直接指定国内外dns
想知道如果把smartdns两组都开起来，第二组选国外的dns，openclash要怎么设置才能配合好smartdns呢

**Comment by hcym** [comment]
简单就是美

**Comment by adamw92** [comment]
fakeIP模式下，国外以及符合代理规则的dns查询，最终采用的都是来自代理服务器解析出来的结果。
所以，这个模式下nameserver和fallback组所有的dns服务器只需要快速的返回结果供clash进行判断就可以了，这个环节里对dns返回的结果进行测速排名并优选感觉没啥意义
以及，fakeip模式下，不需要配置国外的做fallback，反正采用的是第一个返回来的结果…
真的要搭配的话，整个adg home然后并行模式填几个你那反应最快的dns就行了，功能比smartdns也丰富的多。

**Comment by CORE202009** [comment]
实际上一点用都没有，本地解析的IP地址只用于判断，clash最终只能在代理服务器上解析。fake-ip是建立域名和假IP的映射，redir-host是建立域名和真IP的映射（这个IP是本地不通过代理查询的）。不管是fake-ip还是redir-host，客户端发起的TCP连接都会被clash拦截，IP被转换成域名，然后clash和代理连接，最终还是用不上的。

**Comment by secretandanon** [comment]
我个人认为无需搭载smartdns来分流，clash本身就已经有了很好的分流政策，如果你比较在意速度，可以搭建coredns作为clash的上游来进行dns缓存
