### ISSUE TITLE
使用配置文件订阅Trojan线路在控制面板里ping不通

### ISSUE THREAD

**Issue by warcns** [vernesong/OpenClash#807]
OpenClash v0.40.6 使用配置文件订阅的Trojan线路在控制面板里ping不通，但是有时线路是可以使用的。请问是需要再设置什么吗

**Comment by iam3ddy** [comment]
我这用trojan没这问题。应该是你自己配置错了

**Comment by warcns** [comment]
> 我这用trojan没这问题。应该是你自己配置错了

是的，谢谢提醒，Trojan配置要加 skip-cert-verify: true
