### ISSUE TITLE
树莓派3B+ 内核编译版本使用那个？

### ISSUE THREAD

**Issue by hyy34** [vernesong/OpenClash#808]
同标题，谢谢。

**Comment by hyy34** [comment]
选择了armv8，运行日志里 nohup: failed to run command '/etc/openclash/clash': No such file or directory

**Comment by zzcabc** [comment]
选择armv7试试

**Comment by vernesong** [comment]
v7吧，放/etc/openclash/core文件夹里去

**Comment by lordmos** [comment]
v7不行，然后显示的是未知内核，如图
<img width="814" alt="截屏2020-10-08 下午4 47 04" src="https://user-images.githubusercontent.com/4252491/95436012-e6a7f780-0985-11eb-8a20-82053d78f71a.png">

**Comment by vernesong** [comment]
给权限，不是v7就是v8，自己试一试

**Comment by zzcabc** [comment]
如果可以的话,使用ssrplus更新内核,而且在你下载好内核之后,网络问题可能导致为为之内核,但不影响使用
