### ISSUE TITLE
fake ip启用，docker portainer无法进入

### ISSUE THREAD

**Issue by junwu0608** [vernesong/OpenClash#81]
其他容器web界面也没法进入。

**Comment by vernesong** [comment]
web不是内网地址？

**Comment by junwu0608** [comment]
像192.168.1.1:9999【portainer】  192.168.1.1:3000【adguard home】这种都进不去，在dns转发这里添加5333端口(turb dns加速)可以打开。然后再打开fake ip模式，删除5333转发，在路由重启前的这段时间里，portainer和adguard home可以正常打开。重启后失效。

**Comment by vernesong** [comment]
这种内网地址clash并不会干预，如果跟DNS有关你可以切换到redir，原因暂不清楚
