### ISSUE TITLE
16M闪存的玩家需求

### ISSUE THREAD

**Issue by aueu** [vernesong/OpenClash#811]
读了 https://github.com/vernesong/OpenClash/issues/110  https://github.com/vernesong/OpenClash/issues/484

发现已经有类似的人提出此类需求

现在，`openclash_core.sh` `openclash_ipdb.sh` 这两个文件已经变化，需要另外做修改

建议下载之前，`curl -I `获取 Content-Length，如果大于剩余空间，就不要 mv 回 /etc 了，ln -sf 回去

最好的办法还是能自定义内核存放路径 **/etc/openclash/core** 与 geoip 数据路径 **/etc/openclash/Country.mmdb**

当然，弊端就是每次重启路由后，启动openclash前，需要重新下载，不过这个对于小于等于16M 闪存的玩家来说，应该是一个刚需。实际上，觉我所知，padavan 作者针对小闪存路由，就是这么处理的。

昨晚我用一个吃灰的miwifi-mini，测试了官方固件，安装openclash没有问题，下载内核就空间不足。自己编译固件，将openclash 打进固件，可以顺利启动，但是没什么空间再安装其他app了。另外，自己编译的固件那么大，导致重启路由花费的时间也过长，毕竟闪存读的速度有限。

所以，小闪存玩家，自定义下载大文件路径，配合 zram-swap 跑 golang。应该是一个最佳解决方案。

**Comment by 1715173329** [comment]
在 mips 设备上跑 clash 是觉得设备性能太高，还是觉得 golang 占用太低？

**Comment by aueu** [comment]
响应神速，小闪存成功，非常棒！

<img width="906" alt="screenshot 2020-10-01 at 10 41 03" src="https://user-images.githubusercontent.com/1732266/94759530-c77ff780-03d2-11eb-945a-bd8d44b96ed1.png">
<img width="951" alt="screenshot 2020-10-01 at 10 41 12" src="https://user-images.githubusercontent.com/1732266/94759549-cd75d880-03d2-11eb-9f36-a7160d780f3d.png">
<img width="971" alt="screenshot 2020-10-01 at 10 41 42" src="https://user-images.githubusercontent.com/1732266/94759564-d4045000-03d2-11eb-8d88-a42cc964d469.png">


用官方固件的同学，如果用zram-swap，优先级是-2，需要修改下 /etc/init.d/zram

https://github.com/openwrt/openwrt/commit/5f07b6f367ff10ecc029e0b9e41b9fc5eac6968e

**Comment by aueu** [comment]
安装了kmod-tun
运行与redir-host（tun混合）模式
<img width="918" alt="screenshot 2020-10-01 at 10 51 05" src="https://user-images.githubusercontent.com/1732266/94760058-1712f300-03d4-11eb-842a-a5c71c7f6d1e.png">

**Comment by aueu** [comment]
测试了3小时，一切正常，我将vm.swappiness设置成1了
刚启动openclash的时候负载偏高，当然这是我吃灰路由的闪存IO的问题，几分钟后就降下来

下图是看油管1080p的cpu与负载，加密是chacha20-ietf，结果还是挺满意的

<img width="1723" alt="screenshot 2020-10-01 at 13 19 18" src="https://user-images.githubusercontent.com/1732266/94771107-0caf2400-03e9-11eb-8991-0156ad852486.png">

**Comment by hcym** [comment]
累😩，mtk还是AP安稳

**Comment by aueu** [comment]
@vernesong 又来打扰了，小闪存模式非常棒！在k2p上家用环境跑openclash完全无问题。
只是geoip文件，现在已经没必要打包进ipk中了吧。因为依赖关系，装下openclash实际上需要的空间不少。

**Comment by energygreek** [comment]
@aueu  请问能否提供下miwifi-mini的编译好的simple-obfs？ 我不知道怎么编译

**Comment by qq963598371** [comment]
> @vernesong 又来打扰了，小闪存模式非常棒！在k2p上家用环境跑openclash完全无问题。 只是geoip文件，现在已经没必要打包进ipk中了吧。因为依赖关系，装下openclash实际上需要的空间不少。
有变异好的文件和方法么~企图让家里16M的k2p吃上clash。请留下博客地址~
