### ISSUE TITLE
对配置的一个疑问？或 BUG ?

### ISSUE THREAD

**Issue by Frankcjn** [vernesong/OpenClash#814]
- IP-CIDR,198.18.0.0/16,DIRECT
在向配置的 rules 加入以上规则会导致大量的 listen udp :0: bind: address already in use
伴随着高 cpu 占用，但访问似乎没有影响。经测试 clash for windows 不会出现相同的问题。
这是不是和 OpenClash 独有的行为有关？

OpenClash 运行模式 | Redir-Host（兼容）模式 
已选择编译版本 | linux-amd64
当前【TUN模式】内核版本 | 2020.09.27
当前客户端版本 | v0.40.7-beta

**Comment by vernesong** [comment]
设置成reject即可，不然fakeip模式下会造成回环死机

**Comment by Frankcjn** [comment]
> 设置成reject即可，不然fakeip模式下会造成回环死机

这里我用的是 Redir-Host 模式。不过我的确看到日志中有大量的 198.18.0.0/24 指向实际 ip，有 Fake-IP 类似的行为？

**Comment by vernesong** [comment]
不清楚，但机制不一样，等clash能代理路由自身流量之后这个就不用管了，本身是DNS缓存造成的

**Comment by secretandanon** [comment]
应该是你之前用的fake-ip，然后你系统中还有dns缓存，这个缓存指向这个fake-ip，设置时加上no-resolve，弄成reject就可以了
