### ISSUE TITLE
openclash游戏加速失败，各位大佬是什么情况

### ISSUE THREAD

**Issue by wuchen4588** [vernesong/OpenClash#815]
今天玩codm一直加速失败，几个战局只有一个进了，进了后还跳ping掉线了真的裂开。本人是iplc节点加速
![Screenshot_2020-10-01-18-48-04-78](https://user-images.githubusercontent.com/60568101/94813702-ee6a1800-042a-11eb-8c0d-d88c8a4bfb9c.jpg)

**Comment by wuchen4588** [comment]
本人使用fake-ip混合内核加速

**Comment by secretandanon** [comment]
这是什么游戏

**Comment by secretandanon** [comment]
发游戏让别人测试一下

**Comment by secretandanon** [comment]
更换节点后呢，有好转不

**Comment by wuchen4588** [comment]
没有，自己用手机ssr试了下。怀疑是ktun内核问题加速失败

**Comment by vernesong** [comment]
连接问题截图控制面板连接日志

**Comment by wuchen4588** [comment]
我寻思给连接日志也没用啊，因为我走的全球代理。

**Comment by wuchen4588** [comment]
好了，我找到原因了，在单开ktun内核可以正常加速，对于混合下ktun内核似乎出问题了。这个是连接日志
![Uploading Screenshot_2020-10-02-03-01-07-87.jpg…]()

**Comment by wuchen4588** [comment]
![Uploading Screenshot_2020-10-02-03-01-07-87.jpg…]()

**Comment by wuchen4588** [comment]
> 连接问题截图控制面板连接日志

我裂开了，刚看日志说没开UDP转发，这个ktun内核是怎么回事啊，到了混合模式下无法正常转发
![Uploading 屏幕截图 2020-10-02 133151.png…]()

**Comment by wuchen4588** [comment]
#===================== 插件设置 =====================#
当前配置文件: /etc/openclash/config/次元链接.yaml
运行模式: fake-ip-mix
默认代理模式: rule
UDP流量转发: 停用
DNS劫持: 启用
自定义DNS: 启用
IPV6-DNS解析: 启用
禁用Dnsmasq缓存: 启用
自定义规则: 停用
仅允许内网: 停用
仅代理命中规则流量: 停用
绕过中国大陆IP: 停用

#启动异常时建议关闭此项后重试
保留配置: 停用
第三方规则: 停用

**Comment by vernesong** [comment]
配置文件节点下面要写udp true才能代理，不写默认直连

**Comment by wuchen4588** [comment]
> 配置文件节点下面要写udp true才能代理，不写默认直连

配置文件已经打开udp了，很显然是bug

**Comment by vernesong** [comment]
你的日志图片看不到啊

**Comment by wuchen4588** [comment]
> 你的日志图片看不到啊

不知道什么问题，一直上传不了。有tg可以私聊吗？

**Comment by wuchen4588** [comment]
我也重试刷新固件了，确实是内核启动问题导致造成的

**Comment by wuchen4588** [comment]
然后我想倒回内核版本发现你没提供历史下载...........................

**Comment by wuchen4588** [comment]
当前配置文件: /etc/openclash/config/次元链接.yaml
运行模式: fake-ip-vpn
默认代理模式: rule
UDP流量转发: 停用
DNS劫持: 启用
自定义DNS: 启用
IPV6-DNS解析: 停用
禁用Dnsmasq缓存: 停用
自定义规则: 停用
仅允许内网: 停用
仅代理命中规则流量: 停用
绕过中国大陆IP: 停用

#启动异常时建议关闭此项后重试
保留配置: 停用
第三方规则: 停用

**Comment by wuchen4588** [comment]
当前配置文件: /etc/openclash/config/次元链接.yaml
运行模式: fake-ip-vpn
默认代理模式: rule
UDP流量转发: 停用
DNS劫持: 启用
自定义DNS: 启用
IPV6-DNS解析: 停用
禁用Dnsmasq缓存: 停用
自定义规则: 停用
仅允许内网: 停用
仅代理命中规则流量: 停用
绕过中国大陆IP: 停用

#启动异常时建议关闭此项后重试
保留配置: 停用
第三方规则: 停用

**Comment by wuchen4588** [comment]
目前单开ktun内核加速，等混合bug修复

**Comment by ufoozhenghao** [comment]
+1 codm也遇到了这个问题
