### ISSUE TITLE
[bug] 当luci使用非80端口时，切换页面到Fake-IP模式(切换页面到Redir-host模式)时，会跳转到80端口的页面

### ISSUE THREAD

**Issue by secretandanon** [vernesong/OpenClash#816]
问题出现在这里
`window.location.href='<%="http://'+window.location.hostname+'/cgi-bin/luci/admin/services/openclash/settings"%>';`
位于
/luci-app-openclash/luasrc/view/openclash/switch_mode.htm
@vernesong 望尽快修复

**Comment by vernesong** [comment]
影响？

**Comment by secretandanon** [comment]
@vernesong 是的，我的luci采用的是8080端口，每次它都自己跳转到80端口，导致网页打不开
