### ISSUE TITLE
旁路由关于dns的一些疑问

### ISSUE THREAD

**Issue by yonheng** [vernesong/OpenClash#818]
旁路由的自定义dns设置为主路由ip后才可以更新openclash然后使用，使用过程中所使用的dns是自定义的dns还是openclash的设置的dns？使用openclash后自定义dns里的dns有没有必要清空，因为如果清空后，openclash更新配置就会找不到dns，如果不清空又怕日常使用的不是openclash的dns？求解

**Comment by vernesong** [comment]
不必纠结那么多，哪个能用、最快就用哪个，redir模式再设置几个fallback即可

**Comment by hcym** [comment]
单臂用的vlan，和硬路由一样不用其他设置
