### ISSUE TITLE
关闭openclash不会刷新防火墙？

### ISSUE THREAD

**Issue by smallst** [vernesong/OpenClash#819]
最近的版本似乎关闭openclash会导致无法上网，在路由器上试了下 `firewall restart` 后会恢复。启动openclash没有任何问题。
不确定是不是我个人的问题（比如路由器的其他影响防火墙的设置？）

**Comment by hcym** [comment]
好几个版本这样了，无所谓，一般很少开关，分流配置好基本不用管

**Comment by smallst** [comment]
@hcym 好的，虽然我也不怎么开关（主要也就是研究ipv6的时候），不过有bug还是要提的hhh

**Comment by hcym** [comment]
ipv6节点能用吗？我试过没用，唯一的遗憾了

**Comment by smallst** [comment]
@hcym 呃我不是试ipv6节点，是试普通ipv6站点 :joy:

**Comment by vernesong** [comment]
ssh 下 /etc/init.d/openclash stop 看看报错

**Comment by smallst** [comment]
@vernesong 有个鬼故事…… 运行 `/etc/init.d/openclash stop`  会显示 `OpenClash Already Stop` 但 `ps -ef |grep openclash` 会发现 openclash 还在运行，网页端也显示还在运行， 但 `openclash_watchdog` 会停止。 并且， `/tmp/openclash_start.log` 这个文件不存在= =

**Comment by smallst** [comment]
@vernesong 有个疑问，https://github.com/vernesong/OpenClash/blob/04bbcf6f56c794d8ee1013123ed2d0dd2a89cb55/luci-app-openclash/root/etc/init.d/openclash#L1632-L1635 这里为什么是判 `enable!=1` ? 难道不是enable == 1 才需要kill openclash 吗

**Comment by vernesong** [comment]
你不是问防火墙吗，stop清除了没有

**Comment by smallst** [comment]
stop 没有停止 clash， 但防火墙清除了

**Comment by vernesong** [comment]
那我就不清楚了，建议换固件
