### ISSUE TITLE
和启动以及fake ip 相关的两个问题

### ISSUE THREAD

**Issue by dalton-chiou** [vernesong/OpenClash#82]
问题一：每次路由器（openwrt18.06.5)重启后，发现能够上网，不能翻墙。这时的部分日志：
time="2019-11-27T17:30:24Z" level=info msg="DNS server listening at: 0.0.0.0:7874"
time="2019-11-27T17:30:24Z" level=info msg="Redir proxy listening at: :7892"
time="2019-11-27T17:30:24Z" level=info msg="RESTful API listening at: 192.168.1.1:9090"
time="2019-11-27T17:30:24Z" level=info msg="HTTP proxy listening at: 192.168.1.1:7890"
time="2019-11-27T17:30:24Z" level=info msg="SOCKS proxy listening at: 192.168.1.1:7891"
2019-11-28 01:30:23 OpenClash Can Not Start, Try Use Backup Rules Start Again
time="2019-11-27T17:30:30Z" level=info msg="DNS server listening at: 0.0.0.0:7874"
time="2019-11-27T17:30:30Z" level=info msg="Redir proxy listening at: :7892"
time="2019-11-27T17:30:30Z" level=info msg="HTTP proxy listening at: 192.168.1.1:7890"
time="2019-11-27T17:30:30Z" level=info msg="RESTful API listening at: 192.168.1.1:9090"
time="2019-11-27T17:30:30Z" level=info msg="SOCKS proxy listening at: 192.168.1.1:7891"
time="2019-11-27T17:30:57Z" level=info msg="RESTful API listening at: 192.168.1.1:9090"
time="2019-11-27T17:30:57Z" level=error msg="External controller error: listen tcp 192.168.1.1:9090: bind: address already in use"
time="2019-11-27T17:30:57Z" level=error msg="Start HTTP server error: listen tcp 192.168.1.1:7890: bind: address already in use"
time="2019-11-27T17:30:57Z" level=error msg="Start SOCKS5 server error: listen tcp 192.168.1.1:7891: bind: address already in use"
time="2019-11-27T17:30:57Z" level=error msg="Start Redir server error: listen tcp :7892: bind: address already in use"
time="2019-11-27T17:30:57Z" level=error msg="Start DNS server error: listen udp 0.0.0.0:7874: bind: address already in use"
2019-11-28 01:30:23 OpenClash Start Successful With Backup Rules Config, Please Check Or Update Other Rules And Retry
2019-11-28 01:30:56 OpenClash Start Successful

结果不能翻墙。相关的一些日志：(dial 的地址并不是VPS真实地址，因为套着CDN）
time="2019-11-27T17:31:21Z" level=warning msg="dial DIRECT error: dial tcp4 172.217.xx.xx:443: i/o timeout"
time="2019-11-27T17:31:21Z" level=warning msg="dial DIRECT error: dial tcp4 67.228.xx.xx:443: i/o timeout"
time="2019-11-27T17:31:22Z" level=debug msg="[DNS] response msg error: &dns.Msg{MsgHdr:dns.MsgHdr{Id:0xd845, Response:true, Opcode:0, Authoritative:false, Truncated:false, RecursionDesired:true, RecursionAvailable:true, Zero:false, AuthenticatedData:false, CheckingDisabled:false, Rcode:0}, Compress:false, Question:[]dns.Question{dns.Question{Name:\"www.google.com.\", Qtype:0x1c, Qclass:0x1}}, Answer:[]dns.RR(nil), Ns:[]dns.RR(nil), Extra:[]dns.RR(nil)}"

然而，从“运行状态”页面重新启动openclash，却又一切正常，简单地“OpenClash Start Successful”。

**Comment by dalton-chiou** [comment]
问题二：
在没怎么使用网络的情况下，日志里有大量的：
time="2019-11-27T17:47:58Z" level=info msg="10.27.100.197 --> 198.18.0.31 match Match using Final[DIRECT]"
如果把日志调到debug级，则短短几秒内，类似下面的记录不计其数，洪水一样：
time="2019-11-27T17:52:52Z" level=warning msg="dial Final error: dial tcp4 198.18.0.12:443: socket: too many open files"
time="2019-11-27T17:52:52Z" level=warning msg="dial Final error: dial tcp4 198.18.0.15:443: socket: too many open files"
time="2019-11-27T17:52:52Z" level=warning msg="dial Final error: dial tcp4 198.18.0.14:443: socket: too many open files"
time="2019-11-27T17:52:52Z" level=warning msg="dial Final error: dial tcp4 198.18.0.21:443: socket: too many open files"


再看系统日志，也有许多条：
Thu Nov 28 01:53:08 2019 kern.warn kernel: [ 1353.569900] nf_conntrack: nf_conntrack: table full, dropping packet

我想这与fake ip 有关，又不懂是怎么回事。请教。
附上DNS设置：
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  listen: 0.0.0.0:7874
  nameserver:
  - 119.29.29.29
  - 114.114.114.114

**Comment by dalton-chiou** [comment]
问题二，和fake ip有关。
日志里有很多这样的条目：
time="2019-11-27T17:47:58Z" level=info msg="10.27.100.197 --> 198.18.0.31 match Match using Final[DIRECT]"
以及：
time="2019-11-27T17:52:52Z" level=warning msg="dial Final error: dial tcp4 198.18.0.12:443: socket: too many open files"
time="2019-11-27T17:52:52Z" level=warning msg="dial Final error: dial tcp4 198.18.0.15:443: socket: too many open files"
time="2019-11-27T17:52:52Z" level=warning msg="dial Final error: dial tcp4 198.18.0.14:443: socket: too many open files"
上面这样的特别多，几秒内可以达到成百上千。清理DNS缓存后好一些，但还是不少。

系统内核日志也大量出现如下的条目：
Thu Nov 28 01:53:08 2019 kern.warn kernel: [ 1353.569900] nf_conntrack: nf_conntrack: table full, dropping packet

看来和fake ip有关，但我又不懂，特此请教。

**Comment by vernesong** [comment]
不明原因，clash内核崩溃，DNS映射丢失，偶尔不能正常启动。

**Comment by dalton-chiou** [comment]
> 不明原因，clash内核崩溃，DNS映射丢失，偶尔不能正常启动。

看来某些问题是clash本身的。
关闭issue之前报告一下，问题一，在在启动脚本中加入sleep 10，目前看来能解决。问题二，我禁用urltest组后好转，当然这只是权宜之计。
