### ISSUE TITLE
开启tun/game模式后问带宽大幅降低

### ISSUE THREAD

**Issue by Yoo-4x** [vernesong/OpenClash#820]
普通模式下国内测速 200+，tun模式下50不到
YouTube  普通 2W+， tun模式下 1W左右

tun模式下 top 里 cup 大约有 30 的空闲，普通模式下 cpu 空闲能到 40-50

硬件是“极路由4增强版”。

是否是硬件问题。需要哪些信息？

**Comment by vernesong** [comment]
吃硬件性能，最大化速度的是redir混合同时绕过大陆IP
