### ISSUE TITLE
希望能支持自己添加游戏规则的功能

### ISSUE THREAD

**Issue by Kryo123456** [vernesong/OpenClash#822]
我玩的游戏有些在第三方规则里没有，目前只能将自己的规则贴在其他游戏的规则下面，不方便管理。图上的这个自定义功能好像没什么用。
![image](https://user-images.githubusercontent.com/46080229/95113011-53e43e80-0774-11eb-9538-908851ec6d8c.png)

**Comment by vernesong** [comment]
你用自定义规则集

**Comment by Kryo123456** [comment]
> 你用自定义规则集

好的我等下试下

**Comment by Kryo123456** [comment]
> 你用自定义规则集

请问大佬我这样子格式对么
payload:
  # > Team Fortress 2
  - IP-CIDR,1.64.193.0/24
  - IP-CIDR,1.214.121.0/24
  - IP-CIDR,23.76.210.158/32
  - IP-CIDR,31.186.251.0/24

**Comment by vernesong** [comment]
嗯
