### ISSUE TITLE
建议添加ipv6区分国内国外功能

### ISSUE THREAD

**Issue by bleeee** [vernesong/OpenClash#824]
目前墙对ipv6的策略是国内ipv6正常，国外ipv6可以连接，但是动态切断
所以建议dns增加识别返回的ipv6地址如果为国外，那么返回该地址的ipv4地址

**Comment by vernesong** [comment]
这个需求插件无能为力，建议还是关闭插件的IPV6解析，有IPV6需求的再直接去访问

**Comment by bleeee** [comment]
> 这个需求插件无能为力，建议还是关闭插件的IPV6解析，有IPV6需求的再直接去访问

是不是应该去内核的git提？

**Comment by vernesong** [comment]
这种需求优先级太低

**Comment by cielpy** [comment]
> 所以建议dns增加识别返回的ipv6地址如果为国外，那么返回该地址的ipv4地址

这个其实没有太大必要，如果可以接管 IPv6 流量，那么 IPv6 地址起作用的只是在终端到路由器这段，Clash 接管后，比如要访问 Google，不管拿到它的 4 或者 6 的地址，都是不会用的，都是只会告诉代理服务器要访问的是 Google 这个域名，所以我认为，添加 IPv6 支持可以解决访问国外带有 IPv6 DNS 记录的网站时慢或者断的问题

**Comment by cielpy** [comment]
https://github.com/vernesong/OpenClash/pull/1318 这个 PR 添加了 IPv6 支持，访问国外 IPv6 网站和 IPv4 的应该效果相当了
