### ISSUE TITLE
访问控制只有黑名单，请问是否有类似白名单，指定某个IP全局翻墙？

### ISSUE THREAD

**Issue by michealhansun** [vernesong/OpenClash#825]
访问控制只有黑名单，请问是否有类似白名单，指定某个IP全局翻墙？

**Comment by vernesong** [comment]
访问控制本质是让不让流量进入clash，即使是白名单，走不走代理还是看配置文件的规则，你按照自定义规则的模板自己写一下即可

**Comment by Yohoa** [comment]
> 
> 
> 访问控制只有黑名单，请问是否有类似白名单，指定某个IP全局翻墙？

用```IP-SRC```之类的配置可以实现你想要的功能

**Comment by michealhansun** [comment]
谢谢，我研究下
