### ISSUE TITLE
有没有可能加个选项让 OpenClash 完全不管 dnsmasq

### ISSUE THREAD

**Issue by LitingLin** [vernesong/OpenClash#826]
我现在的方案是自己做套dns解析，chinadns+smartdns还是功能更强一些。
而现在有个问题是OpenClash重启时总是会把 dnsmasq 里 Ignore resolve file 这一项改回来😂

**Comment by vernesong** [comment]
自己去启动脚本注释一下命令就行了啊

**Comment by LitingLin** [comment]
> 自己去启动脚本注释一下命令就行了啊

我现在就是这么做的。
只是提个建议。
fake-ip tun模式出来后大部分流量其实可以使用real ip了。
我现在的方案：
chinadns -- smartdns cn group -- carrier dns
                \  smartdns global group -- dns-https-proxy -- clash socks5 port -- 8.8.8.8 1.1.1.1
smartdns 设规则，像zoom.us这种返回 anycast ip 的查 clash 内置 dns 走 fake-ip
clash 只激活geoip规则，和少数域名规则。如此可兼具兼容性和分流的准确性。
唯一的问题是clash tun模式性能还是差了点。
