### ISSUE TITLE
希望能增加一个选项关闭dns解析。

### ISSUE THREAD

**Issue by wangliangliang2** [vernesong/OpenClash#827]
当前v0.40.7版本 我试了很多方式去关闭dns解析，也直接在config.yaml文件中dns中设置为关闭。但是程序还是会自动修改成开启dns。
当前的需求是：希望能让用户自己管理dns解析。
按照clash 的英文文档说明：dns 设置成false 也就是关闭状态，就会是的dns解析走系统的，那么就能自己管理dns解析了。

**Comment by vernesong** [comment]
关闭DNS不走clash无法形成域名映射，规则中只有IP类规则才会生效

**Comment by LitingLin** [comment]
https://github.com/vernesong/OpenClash/issues/826#issuecomment-705122849
有些时候就是想要仅ip规则，还望考虑。
感谢！
