### ISSUE TITLE
请问如何在yacd 中切换某一个Proxies 的时候，自动打断对应的连接呢？

### ISSUE THREAD

**Issue by Yohoa** [vernesong/OpenClash#828]
类似Clash for Windows 所提到的这个功能："Break When Proxy Change" @ https://docs.cfw.lbyczf.com/contents/breakconn.html

感谢！

**Comment by vernesong** [comment]
![image](https://user-images.githubusercontent.com/42875168/95365527-dac82100-0904-11eb-9653-013d15b73ed0.png)

**Comment by Yohoa** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/42875168/95365527-dac82100-0904-11eb-9653-013d15b73ed0.png)

不好意思，之前没有发现。大變感謝！🤓
