### ISSUE TITLE
有个严重的带宽问题

### ISSUE THREAD

**Issue by tinnlux** [vernesong/OpenClash#83]
我在openwrt主线添加的openclash，但是开启后千兆带宽瞬间只能跑不到200m。国内，不是走的国外线路。

**Comment by peterwjp2017** [comment]
我使用的是WNDR4300，家里200M宽带 跑clash的话 国内测速最多100出个头 
换成SSR，基本上170-180. 暂时找不到原因
我测试使用x86软路由，clash反而比ssr更稳定 速度差不多，可能是我那个路由器硬件太差了
