### ISSUE TITLE
openclash开启后GitHub和youtube连接不上

### ISSUE THREAD

**Issue by jiangxiaoqiang** [vernesong/OpenClash#831]
在OpennWrt上开启OpenClash之后，提示GitHub和Youtube连接不上，诡异的是在本地PC上开启Clash之后提示能连接上了。我的路由是：

ISP线路---》软路由 ----》 路由器 ---》PC

PC上开启Clash竟然软路由的网页检测可以连接GitHub和YouTube，真是见了鬼了。  软路由不是直接连接的互联网？还经过PC？

**Comment by hcym** [comment]
没搞好了，这些都是正常的

**Comment by vernesong** [comment]
网页上检测的是本机的状态，不是路由的状态

**Comment by jiangxiaoqiang** [comment]
现在命令启动可以连接，但是很慢，看来需要好好学习了
