### ISSUE TITLE
一个小建议😄

### ISSUE THREAD

**Issue by Nepmonts** [vernesong/OpenClash#833]
在v0.40.7-beta版本之前我记得有几个版本能够在Openwrt断电或者重新启动，OpenClash重新启动之后能够记住之前的选择的代理节点，现在的v0.40.7-beta版本不能够，每次重新启动之后就会默认选择节点选择里面的第一个。希望可以考虑把这个功能加回来。

**Comment by hcym** [comment]
没有吧，都是ping值低的，问题是ping低，质量未必好，我都是把油管和GitHub固定在几个ping高的节点，网页什么的由clash选择，完美解决

**Comment by Nepmonts** [comment]
> 没有吧，都是ping值低的，问题是ping低，质量未必好，我都是把油管和GitHub固定在几个ping高的节点，网页什么的由clash选择，完美解决

我们使用的配置文件的策略组不一样，感觉你说的问题和我提的不是一个问题。我遇到的问题是在控制面板节点选择里面选择一个节点之后，Openwrt断电或者重新启动，OpenClash重新启动之后，控制面板中的节点选择里面的选择就会默认回到第一个而不是我之前选择的那个节点。

**Comment by hcym** [comment]
第一个配置文件吧，这个没遇过，我最多三个配置，有时选择第二个，好像没什么异常

**Comment by Nepmonts** [comment]
> 第一个配置文件吧，这个没遇过，我最多三个配置，有时选择第二个，好像没什么异常

你在说的和我提的真的不是一个问题。

**Comment by Nepmonts** [comment]
> 第一个配置文件吧，这个没遇过，我最多三个配置，有时选择第二个，好像没什么异常

我不明白你所说的。我遇到的问题就是在控制面板代理列表里面选择了一个节点，OpenClash重新启动之后代理列表所选择的节点就会默认变成列表第一个。

**Comment by sekaiacg** [comment]
有一个类似的问题
https://github.com/xiaoqingfengATGH/HomeLede/issues/54
我遇到过启动顺序考前会导致节点状态记录丢失
开机也会有几率高连接数，内存泄漏的问题。

**Comment by Nepmonts** [comment]
> 有一个类似的问题
> [xiaoqingfengATGH/HomeLede#54](https://github.com/xiaoqingfengATGH/HomeLede/issues/54)
> 我遇到过启动顺序考前会导致节点状态记录丢失
> 开机也会有几率高连接数，内存泄漏的问题。

对，就是节点状态记录丢失。
