### ISSUE TITLE
luci界面中没有插件界面选项

### ISSUE THREAD

**Issue by Nozdormu-Timer** [vernesong/OpenClash#834]
![](https://github.com/Nozdormu-Timer/pic/blob/master/openwrt.png?raw=true)

**Comment by Nozdormu-Timer** [comment]
装完0.40.7-beta后，插件界面消失了，刷新了很多次、重装都没有用处。

**Comment by Nozdormu-Timer** [comment]
求大佬帮忙啊

**Comment by vernesong** [comment]
没报错你重启试试

**Comment by aprilies** [comment]
从面板更新后：
“404 未找到
对不起，请求的目标未找到。

无法调度: /cgi-bin/luci/admin/services/openclash”

**Comment by ronlzw** [comment]
No page is registered at '/admin/services/openclash'.
If this url belongs to an extension, make sure it is properly installed.
If the extension was recently installed, try removing the /tmp/luci-indexcache file.
