### ISSUE TITLE
希望能支持订阅多个配置文件

### ISSUE THREAD

**Issue by Apocalypsor** [vernesong/OpenClash#84]
现在的远程订阅只能订阅是个配置文件，如果流量用光了想换另一个机场只能改订阅链接。希望能提供类似cfw的多个配置文件的切换和订阅，辛苦开发者了！

**Comment by HinataKato** [comment]
https://github.com/tindy2013/subconverter/
在增加订阅之前可以用这个揉一起

**Comment by Apocalypsor** [comment]
> https://github.com/tindy2013/subconverter/
> 在增加订阅之前可以用这个揉一起

我目前是用Surgio来做的订阅连接，为的就是把不同✈分开
