### ISSUE TITLE
0.40.8 ipk安装后无法启动

### ISSUE THREAD

**Issue by qin9125** [vernesong/OpenClash#843]
2020-10-12 19:25:39 Error: OpenClash Can Not Start, Try Use Raw Config Restart Again
2020-10-12 19:25:39 Error: OpenClash Can Not Start, Please Check The Error Info And Try Again

**Comment by gnusir** [comment]
缺少依赖libcap, libcap-bin

**Comment by hcym** [comment]
armv8基本正常，赶紧x86，不然耽误看油管🤩

**Comment by qin9125** [comment]
> 缺少依赖libcap, libcap-bin

2020-10-12 21:22:21 Warning: OpenClash Now Disabled, Need Start From Luci Page, Exit...
2020-10-12 21:24:05 Error: Nameserver Option Must Be Setted, Auto Completing
2020-10-12 21:24:05 Error: OpenClash Can Not Start, Try Use Raw Config Restart Again
2020-10-12 21:24:05 Error: Get DNS 'listen' Option Error, OpenClash Can Not Start With Raw Config File
2020-10-12 21:24:05 Error: Get DNS 'enhanced-mode' Option Error, OpenClash Can Not Start With Raw Config File
2020-10-12 21:24:05 Error: Get General 'redir-port' Option Error, OpenClash Can Not Start With Raw Config File
依赖有我重置了路由器继续这样。。。

**Comment by testowenyoung** [comment]
同问题

**Comment by testowenyoung** [comment]
Nameserver Option Must Be Setted

**Comment by qin9125** [comment]
> 必须设置名称服务器选项

在哪设置？

**Comment by qin9125** [comment]
> Nameserver Option Must Be Setted

有点方，我的配置文件一路升级ipk都正常，唯独今天的各种报错

**Comment by testowenyoung** [comment]
> > 必须设置名称服务器选项
> 
> 在哪设置？

我的意思是我也是同样的问题，提示这个日志。

我换0.40.7了，已解决，等更新

我也是，之前自动升级都没问题，0.40.8直接删除了全部文件，重新配置了一遍

**Comment by hcym** [comment]
升级的可能麻烦事儿，我是全新安装没什么问题

**Comment by qin9125** [comment]
> 升级的可能麻烦事儿，我是全新安装没什么问题

我全新安装了一次不行路由被我重置

**Comment by vernesong** [comment]
发配置文件上来，我看看是不是格式问题

**Comment by warcns** [comment]
一样的问题，安装0.40.8后可以启动，但是实际并没有生效，无法打开Yacd 控制面板。
删除0.40.8，回退到0.40.7后问题解决

**Comment by qin9125** [comment]
> 发配置文件上来，我看看是不是格式问题

![image](https://user-images.githubusercontent.com/32502941/95766922-9367d900-0ce6-11eb-8506-fe2fa43903f3.png)
我这样截的图不知道能行不？

**Comment by vernesong** [comment]
依赖没装好吧，你https://mirrors.cloud.tencent.com/lede/snapshots/packages/里面找libcap和libcap-bin重装下

**Comment by qin9125** [comment]
> 依赖没装好吧，你[https://mirrors.cloud.tencent.com/lede/snapshots/packages/里面找libcap和libcap-bin重装下](https://mirrors.cloud.tencent.com/lede/snapshots/packages/%E9%87%8C%E9%9D%A2%E6%89%BElibcap%E5%92%8Clibcap-bin%E9%87%8D%E8%A3%85%E4%B8%8B)

![image](https://user-images.githubusercontent.com/32502941/95769522-9b297c80-0cea-11eb-951a-9256b6b0f80e.png)
我卸载重新安装看看，安装的时候自动装的，手动安装升级了libcap_2.43-1_x86_64.ipk

**Comment by qin9125** [comment]
> 依赖没装好吧，你[https://mirrors.cloud.tencent.com/lede/snapshots/packages/里面找libcap和libcap-bin重装下](https://mirrors.cloud.tencent.com/lede/snapshots/packages/%E9%87%8C%E9%9D%A2%E6%89%BElibcap%E5%92%8Clibcap-bin%E9%87%8D%E8%A3%85%E4%B8%8B)

我现在方了，卸载后安装不上了，这。。。。
![image](https://user-images.githubusercontent.com/32502941/95771447-a5994580-0ced-11eb-8e8a-42bcc3024416.png)

**Comment by vernesong** [comment]
update先

**Comment by qin9125** [comment]
> update先

不行，我update了好多遍，重启也试了，依旧不能安装，好烦，

![image](https://user-images.githubusercontent.com/32502941/95772457-594f0500-0cef-11eb-927d-c2cd09dbd6e1.png)

**Comment by vernesong** [comment]
不行就别折腾了，回退先

**Comment by qin9125** [comment]
> 不行就别折腾了，回退先

先感谢你的回复，我眼疾手快的截图这个设置是哪？
![image](https://user-images.githubusercontent.com/32502941/95802589-7c4dd900-0d30-11eb-950a-3272ab0a4e16.png)

**Comment by vernesong** [comment]
配置文件没问题的，两个新依赖没正常工作大概
ssh输入 capsh --supprots测试下依赖是否正常，不正常重装2.43版本的libcap和libcap-bin

**Comment by qin9125** [comment]
> capsh --supprots

![image](https://user-images.githubusercontent.com/32502941/95803143-f0d54780-0d31-11eb-90a9-5fa1de431b51.png)
麻烦你看看正常不两个依赖是我提前腾讯源安装过的

**Comment by danchao-gu** [comment]
> > 依赖没装好吧，你[https://mirrors.cloud.tencent.com/lede/snapshots/packages/里面找libcap和libcap-bin重装下](https://mirrors.cloud.tencent.com/lede/snapshots/packages/%E9%87%8C%E9%9D%A2%E6%89%BElibcap%E5%92%8Clibcap-bin%E9%87%8D%E8%A3%85%E4%B8%8B)
> 
> 我现在方了，卸载后安装不上了，这。。。。
> ![image](https://user-images.githubusercontent.com/32502941/95771447-a5994580-0ced-11eb-8e8a-42bcc3024416.png)

libcap和libcap-bin的ipk文件直接下到电脑上，ftp到你的机器分别执行安装这两个文件opkg install libcap-XXXX.ipk。我这亲测有效
