### ISSUE TITLE
开启openclash后所有流量都走路由网关

### ISSUE THREAD

**Issue by sekaiacg** [vernesong/OpenClash#850]
在爱快+lede下，lede作为旁路由
开启后内外流量都走lede网关，这样的结果是爱快限速功能失效。
这里的国内流量指经过了openclash并不真正的代理
国内流量有没有办法不走openclash？
用passwall测试没有这个问题

**Comment by vernesong** [comment]
不是有个绕过大陆ip吗

**Comment by sekaiacg** [comment]
> 不是有个绕过大陆ip吗

使用了第三方规则：
添加到所有配置-国内域名白名单/国内ip白名单-DIRECT策略

**Comment by sekaiacg** [comment]
我使用是fake-ip模式，没有绕过ip选项
切换到Redir-Host模式后有了，fake-ip模式能不能加上这个功能

**Comment by Travisss** [comment]
我也一直被这个问题困扰。clash for windows就没这个问题。

**Comment by hongbin75513** [comment]
流量控制里面打开 实验性：绕过中国大陆 IP
