### ISSUE TITLE
0.40.9版本安装问题

### ISSUE THREAD

**Issue by gui-li** [vernesong/OpenClash#853]
尝试opkg install安装ipk，但报如下错误：
```
Upgrading luci-app-openclash on root from 0.40.8-beta to 0.40.9-beta...
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-app-openclash:
 *      kernel (= 4.14.195-1-68143adfcb7fc62a239c4be112fe40de)
 * opkg_install_cmd: Cannot install package luci-app-openclash.
```

**Comment by OleStore** [comment]
Installing luci-app-openclash (0.40.9-beta) to root...
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-app-openclash:
 *      kernel (= 5.4.70-1-873c32b25c3269121c39b38cae2aa9da)
 * opkg_install_cmd: Cannot install package luci-app-openclash.
确实，同样的问题

**Comment by zlwww** [comment]
You Could Download And Re-Install The libcap & libcap-bin

**Comment by OleStore** [comment]
> You Could Download And Re-Install The libcap & libcap-bin

![2020-10-13_183314](https://user-images.githubusercontent.com/1283711/95849910-97493900-0d82-11eb-85a4-315c5565ae1b.jpg)

**Comment by gui-li** [comment]
> > You Could Download And Re-Install The libcap & libcap-bin
> 
> ![2020-10-13_183314](https://user-images.githubusercontent.com/1283711/95849910-97493900-0d82-11eb-85a4-315c5565ae1b.jpg)

这个是snapshot吗？我从v19.07.4构建的并没有libcap-bin

**Comment by OleStore** [comment]
> > > You Could Download And Re-Install The libcap & libcap-bin
> > 
> > 
> > ![2020-10-13_183314](https://user-images.githubusercontent.com/1283711/95849910-97493900-0d82-11eb-85a4-315c5565ae1b.jpg)
> 
> 这个是snapshot吗？我从v19.07.4构建的并没有libcap-bin

@lean 的

**Comment by openips** [comment]
刷固件吧
