### ISSUE TITLE
大家帮我看一下这个路由器该下载哪个ipk？

### ISSUE THREAD

**Issue by conphi** [vernesong/OpenClash#854]
https://openwrt.org/toh/hwdata/gl.inet/gl.inet_gl-ar150

> 主要规格
> Target: ar71xx-ath79
> Subtarget: generic
> Package architecture: mips_24kc
> CPU: Atheros AR9331
>

**Comment by lifetyper** [comment]
单核400m的mips，建议不要考虑clash方案。
