### ISSUE TITLE
0.40.9 启动会错,不要升级，linux-X86_64 软路由

### ISSUE THREAD

**Issue by icucuio** [vernesong/OpenClash#855]
错误：Capsh异常，请尝试重新安装依赖【libcap】和相应的Capsh库，终止启动...

**Comment by Frankcjn** [comment]
把 libcap 和 libcap-bin，装一装就好了。（有点坑，增加了依赖没警告。自动更新没成功，直接 luci 菜单都没了）
opkg update && opkg install libcap libcap-bin -y

**Comment by yezhu64** [comment]
> 把 libcap 和 libcap-bin，裝一裝就好了。（有點坑，增加了依賴沒警告。自動更新沒成功，直接 luci 菜單都沒了）
> opkg update && opkg install libcap libcap-bin -y

怎麼裝？能具體一些嗎？

**Comment by beilsn** [comment]
> 把 libcap 和 libcap-bin，装一装就好了。（有点坑，增加了依赖没警告。自动更新没成功，直接 luci 菜单都没了）
> opkg update && opkg install libcap libcap-bin -y

嗯，昨晚看了下其他帖子把这2个装上就好了

**Comment by yezhu64** [comment]
> > 把 libcap 和 libcap-bin，装一装就好了。（有点坑，增加了依赖没警告。自动更新没成功，直接 luci 菜单都没了）
> > opkg update && opkg install libcap libcap-bin -y
> 
> 嗯，昨晚看了下其他帖子把这2个装上就好了
問題沒有解決，還是出錯

**Comment by yezhu64** [comment]
重新回到0.40.7的就正常了

**Comment by snugduahn** [comment]
> 重新回到0.40.7的就正常了

问题是怎么回到0.40.7呢？

**Comment by icucuio** [comment]
ssh 进路由，然后opkg remove

**Comment by icucuio** [comment]
我又回去用0.40.7了，0.40.10确实问题感觉不少
