### ISSUE TITLE
0.40.10暂时完美！

### ISSUE THREAD

**Issue by hackenfu** [vernesong/OpenClash#858]
当了小白鼠，暂时完美！辛苦作者了

**Comment by ForestL18** [comment]
你的检查更新正常吗，我的还是检查不出来，显示是错误的

**Comment by hackenfu** [comment]
fake，我没问题，软路由



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: forestL <notifications@github.com&gt;
发送时间: 2020年10月13日 22:25
收件人: vernesong/OpenClash <OpenClash@noreply.github.com&gt;
抄送: hackenfu <hacken@vip.qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[vernesong/OpenClash] 0.40.10暂时完美！ (#858)





 
你用的redir还是fake-IP？我感觉fake-IP好像代理不了路由器流量了

**Comment by ForestL18** [comment]
终于成功！！！我换了fake，tun模式OK了

![image](https://user-images.githubusercontent.com/45709305/95874751-d045d580-0da3-11eb-8cac-acb45539c99a.png)

**Comment by laomao333** [comment]
我不管啥模式都显示不出来跟新

**Comment by hackenfu** [comment]
> > 你的检查更新正常吗，我的还是检查不出来，显示是错误的
> > ![image](https://user-images.githubusercontent.com/45709305/95873055-1dc14300-0da2-11eb-995b-36df40e78427.png)
> 
> 同样情况

今早看了下，没问题了

**Comment by yanyingjie007** [comment]
> 你用的redir还是fake-IP？我感觉fake-IP好像代理不了路由器流量了

我也这样，fake ip代理不了路由器本身的流量

**Comment by BerlinChan** [comment]
我运行如下后，更新 0.40.10 已正常
```sh
opkg update
opkg install libcap libcap-bin --force-depends --force-overwrite
```

**Comment by hcym** [comment]
还行，运行两天没什么问题

**Comment by iam3ddy** [comment]
eSIR 10-1 完美支持吗？
