### ISSUE TITLE
40.7升级到40.9启动不了UI消失不见

### ISSUE THREAD

**Issue by madman43** [vernesong/OpenClash#863]
用http://192.168.2.2/cgi-bin/luci/admin/services/openclash地址进去提示
No page is registered at '/admin/services/openclash'.
If this url belongs to an extension, make sure it is properly installed.
If the extension was recently installed, try removing the /tmp/luci-indexcache file.
删除了这个文件还是不行，一直生成

**Comment by tengyuankoo** [comment]
缺少依赖，整个op固件重新编译下

**Comment by davidwu111** [comment]
多加了几个依赖组件，看看release note 谢谢

**Comment by madman43** [comment]
已更新固件安装了依赖组件，目前良好
