### ISSUE TITLE
openclash升级后无法启动

### ISSUE THREAD

**Issue by btcforver** [vernesong/OpenClash#866]
大佬好：
openclash从v0.40.7升级到v0.40.10后无法正常启动，提示如下：
2020-10-15 08:41:43 Error: Could Not Load The Capsh Library, Please Verify The Capsh Shell Library Work Well
2020-10-15 08:41:43 Tip: You Could Download And Re-Install The libcap & libcap-bin Library From The Address Below:
翻看了其他帖子，貌似是要安装libcap & libcap-bin依赖，但是自己试了下，还是报错，小白求详细安装此依赖的教程或步骤，万分感谢！！

**Comment by Doraemon2020** [comment]
一毛一样 哈哈

**Comment by Doraemon2020** [comment]
> 一毛一样 哈哈

不知从何下手

**Comment by vernesong** [comment]
装完还报错就不建议升级了，有空更新固件了再去升级吧

**Comment by Doraemon2020** [comment]
> 装完还报错就不建议升级了，有空更新固件了再去升级吧

已经升级了，应该如何补救？感激不尽

**Comment by Doraemon2020** [comment]
![QQ截图20201015210535](https://user-images.githubusercontent.com/59880367/96131680-14fc7880-0f2c-11eb-989b-0f647720e05a.png)
安装libcap-bin出错  不知咋办好了

**Comment by vernesong** [comment]
装2.43版本的，2.27的都卸载了

**Comment by i5ean** [comment]
同样问题，使用esir的精品小包固件

**Comment by danchao-gu** [comment]
> ![QQ截图20201015210535](https://user-images.githubusercontent.com/59880367/96131680-14fc7880-0f2c-11eb-989b-0f647720e05a.png)
> 安装libcap-bin出错 不知咋办好了

libcap和libcap-bin的ipk文件直接下到电脑上，ftp到你的机器分别执行安装这两个文件opkg install libcap-XXXX.ipk。请测有效

**Comment by i5ean** [comment]
opkg update
opkg install libcap
opkg install libcap-bin

**Comment by i5ean** [comment]
> > ![QQ截图20201015210535](https://user-images.githubusercontent.com/59880367/96131680-14fc7880-0f2c-11eb-989b-0f647720e05a.png)
> > 安装libcap-bin出错 不知咋办好了
> 
> libcap和libcap-bin的ipk文件直接下到电脑上，ftp到你的机器分别执行安装这两个文件opkg install libcap-XXXX.ipk。请测有效

我的openwrt上传安装有问题
opkg update
opkg install libcap
opkg install libcap-bin
直接装就成功了

**Comment by btcforver** [comment]
> > > ![QQ截图20201015210535](https://user-images.githubusercontent.com/59880367/96131680-14fc7880-0f2c-11eb-989b-0f647720e05a.png)
> > > 安装libcap-bin出错 不知咋办好了
> > 
> > 
> > libcap和libcap-bin的ipk文件直接下到电脑上，ftp到你的机器分别执行安装这两个文件opkg install libcap-XXXX.ipk。请测有效
> 
> 我的openwrt上传安装有问题
> opkg update
> opkg install libcap
> opkg install libcap-bin
> 直接装就成功了

感谢大佬，这是最简单的方法，我一次性操作成功！！
