### ISSUE TITLE
yacd 面板 log

### ISSUE THREAD

**Issue by qin9125** [vernesong/OpenClash#867]
![image](https://user-images.githubusercontent.com/32502941/96088044-6a6a6280-0ef7-11eb-9aeb-8bc3b5ef1a9f.png)
![image](https://user-images.githubusercontent.com/32502941/96088070-75bd8e00-0ef7-11eb-9ac8-1a17c7a83010.png)
![image](https://user-images.githubusercontent.com/32502941/96088272-c339fb00-0ef7-11eb-904d-be205430b8f1.png)

不明觉厉这是bug还是最近改变了代码，我记得以前静默模式没有log输出，现在试了几个版本，虽然设置静默模式但是日志疯狂输出？

**Comment by hcym** [comment]
怕烦也看不懂，从来没看过什么日志，回头看看有没有

**Comment by qin9125** [comment]
> 怕烦也看不懂，从来没看过什么日志，回头看看有没有

那肯定有呀，怎么会没有呢，最近的版本都是这样的

**Comment by hcym** [comment]
真的看了一眼，空白，还有一个调试日志也是空白，就是运行日志有几个字，加载什么规则，成功。没了，以前从来没有看过yamca面板🤒

**Comment by qin9125** [comment]
> 真的看了一眼，空白，还有一个调试日志也是空白，就是运行日志有几个字，加载什么规则，成功。没了，以前从来没有看过yamca面板🤒

是让你打开这个地方的yacd面板log项看，你看调试日志干嘛，
![image](https://user-images.githubusercontent.com/32502941/96123189-0eb6ce00-0f25-11eb-9903-9562a5a030fc.png)

**Comment by hcym** [comment]
对啊，就是那个y面板，旁边是控制面板，我都从来没看过，今天才看到，里面黑屏空白，啥都没有

**Comment by hcym** [comment]
长的和你的一样，log就是空白

**Comment by chenhao2424** [comment]
而且还感觉这个面板很卡……整个代理的速度也下降了……

回退软路由版本，跟着降级openclash的版本了……因为实在是不会折腾o(╥﹏╥)o
