### ISSUE TITLE
openclash无法安装，提示package "luci-app-openclash" preinst script returned status 1    

### ISSUE THREAD

**Issue by WoodC2011** [vernesong/OpenClash#869]
root@N1:/tmp# opkg install luci-app-openclash_0.40.10-beta_all.ipk
Multiple packages (luci-app-openclash and luci-app-openclash) providing same nam                                                                                                             e marked HOLD or PREFER. Using latest.
Installing luci-app-openclash (0.40.10-beta) to root...
Collected errors:
 * pkg_run_script: package "luci-app-openclash" preinst script returned status 1                                                                                                             .
 * preinst_configure: Aborting installation of luci-app-openclash.
 * opkg_install_cmd: Cannot install package luci-app-openclash.

**Comment by zcq100** [comment]
你怎么解决的？

**Comment by WoodC2011** [comment]
> 你怎么解决的？

先强制卸载旧版，然后在版本更新里更新所有内核，然后上传ipk文件，安装好以后，重启路由就可以了

**Comment by zcq100** [comment]
看来是旧文件残留，逐个清理干净了，重启路由器，就安装成功了。感谢

**Comment by WoodC2011** [comment]
> 看来是旧文件残留，逐个清理干净了，重启路由器，就安装成功了。感谢

你0.40.10没什么问题吗，我踩了一堆坑，安装成功后还在排查
