### ISSUE TITLE
新版openclash可以正常运行，但是代理未生效。

### ISSUE THREAD

**Issue by adamw92** [vernesong/OpenClash#87]
单口旁路设备，接口只有eth0和lo

**Comment by vernesong** [comment]
客户端网关和DNS设置为旁路的lan口IP

**Comment by adamw92** [comment]
客户端的网关和DNS已经设置为旁路的IP了，其实就是旁路设备没有桥接，没有br-lan接口，只有eth0和lo
我把lan口桥接了一下无线，出现br-lan之后一下子就正常了……

**Comment by vernesong** [comment]
> 客户端的网关和DNS已经设置为旁路的IP了，其实就是旁路设备没有桥接，没有br-lan接口，只有eth0和lo
> 我把lan口桥接了一下无线，出现br-lan之后一下子就正常了……
嗯，新版本改了，只会劫持brlan的流量

**Comment by CyberKoo** [comment]
> 客户端的网关和DNS已经设置为旁路的IP了，其实就是旁路设备没有桥接，没有br-lan接口，只有eth0和lo
> 我把lan口桥接了一下无线，出现br-lan之后一下子就正常了……
> 嗯，新版本改了，只会劫持brlan的流量

我一样，爱快虚拟机中跑的OpenWRT只有eth0没有brlan，在更新到新版之后发现流量没有重定向到clash中。
请考虑增加需要被劫持的网络接口的选项。

**Comment by nameless3721** [comment]
init.d里面的openclash加一条 iptables -t nat -A PREROUTING -i eth0 -p tcp -j openclash 就好了 看门狗那边也许得加

**Comment by TillLindemann** [comment]
我遇到同样的问题了，笔记本改的单口旁路由，必须要桥接lan口，出现br-lan才能把流量导进openclash，但是目前的问题是，youtube可以打开，而且打开很快，但是点开任意一个视频都没法观看，感觉流量没有正确被导流，不知道是设置问题，还是这种单臂路由的问题。

**Comment by vernesong** [comment]
下个版本会把brlan的指向取消，把劫持放到zone-lan-prerouting
