### ISSUE TITLE
openwrt_x86升级v0.40.10-beta后，openwrt系统崩掉，再进入openwrt无openclash菜单

### ISSUE THREAD

**Issue by hnxxd** [vernesong/OpenClash#872]
我的竞斗云2.0升级也是上述问题。

**Comment by jakeslee** [comment]
试一下置顶 issue 的方法： https://github.com/vernesong/OpenClash/issues/839

**Comment by STIVW** [comment]
docker里的openwrt也是这样已更新4.10后，openwrt直接崩掉，openclash消失。重新运行了两个容器了

**Comment by 00LT00** [comment]
看起来就应该是依赖的问题，我也是直接崩掉，openclash直接不见

**Comment by 00LT00** [comment]
但我更新了依赖，现在还是崩了。。
