### ISSUE TITLE
启动openclash报错，Parse config error: proxy group[0]: `use` or `proxies` missing

### ISSUE THREAD

**Issue by WoodC2011** [vernesong/OpenClash#874]
time="2020-10-17T01:36:01+08:00" level=fatal msg="Parse config error: proxy group[0]: `use` or `proxies` missing"
2020-10-17 01:35:38 Error: OpenClash Can Not Start, Try Use Raw Config Restart Again
2020-10-17 01:35:38 Error: Get DNS 'listen' Option Error, OpenClash Can Not Start With Raw Config File
2020-10-17 01:35:38 Error: Get DNS 'enhanced-mode' Option Error, OpenClash Can Not Start With Raw Config File
2020-10-17 01:35:38 Error: Get General 'redir-port' Option Error, OpenClash Can Not Start With Raw Config File

在两个不同的网站订阅转换过，启动时一直报错，版本0.40.7，0.40.9都试过

**Comment by vernesong** [comment]
直接装40.10，配置文件重新转换一下

**Comment by WoodC2011** [comment]
> 直接装40.10，配置文件重新转换一下

请问重新转换的意思是找个订阅转换网站重新转换？

**Comment by vernesong** [comment]
不用换网站

**Comment by WoodC2011** [comment]
> 不用换网站

我重新下载了0.40.10，仍然报错

time="2020-10-17T01:53:54+08:00" level=fatal msg="Parse config error: proxy group[0]: `use` or `proxies` missing"
2020-10-17 01:53:44 Error: OpenClash Can Not Start, Try Use Raw Config Restart Again
2020-10-17 01:53:44 Error: Get DNS 'listen' Option Error, OpenClash Can Not Start With Raw Config File
2020-10-17 01:53:44 Error: Get DNS 'enhanced-mode' Option Error, OpenClash Can Not Start With Raw Config File
2020-10-17 01:53:44 Error: Get General 'redir-port' Option Error, OpenClash Can Not Start With Raw Config File

**Comment by WoodC2011** [comment]
> 不用换网站

这是我的OpenClash 调试日志麻烦您看下

生成时间: 2020-10-17 01:56:16
插件版本: v0.40.10-beta

```

#===================== 系统信息 =====================#
主机型号: Phicomm N1
固件版本: OpenWrt SNAPSHOT r3550-9404480aca
LuCI版本: git-20.191.36863-eee6bae-1
内核版本: 5.7.7-flippy-38+
处理器架构: aarch64_generic

#此项在使用Tun模式时应为ACCEPT
防火墙转发: ACCEPT

#此项有值时建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: 

#此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 

#===================== 依赖检查 =====================#
dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
jsonfilter: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
iptables-mod-tproxy: 已安装
iptables-mod-extra: 已安装
libcap: 已安装
libcap-bin: 已安装
kmod-tun(TUN模式): 已安装
luci-compat(Luci-19.07): 已安装

#===================== 内核检查 =====================#
运行状态: 未运行
已选择的架构: linux-armv8

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 2020.10.13.gd3de533
Tun内核文件: 存在
Tun内核运行权限: 正常

Game内核版本: v0.17.0-206-gf8a1f1d
Game内核文件: 存在
Game内核运行权限: 正常

Dev内核版本: v1.2.0-1-gbc52f8e
Dev内核文件: 存在
Dev内核运行权限: 正常

#===================== 插件设置 =====================#
当前配置文件: /etc/openclash/config/MY.yaml
运行模式: fake-ip
默认代理模式: rule
UDP流量转发: 启用
DNS劫持: 启用
自定义DNS: 启用
IPV6-DNS解析: 停用
禁用Dnsmasq缓存: 启用
自定义规则: 停用
仅允许内网: 停用
仅代理命中规则流量: 启用
绕过中国大陆IP: 停用

#启动异常时建议关闭此项后重试
保留配置: 启用
第三方规则: 停用

#===================== 配置文件 =====================#
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090

#===================== 防火墙设置 =====================#

#NAT chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    SS_SPEC_WAN_AC  tcp  --  0.0.0.0/0            0.0.0.0/0            match-set ss_spec_lan_ac src /* _SS_SPEC_RULE_ */
2    REDIRECT   udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:53 redir ports 53
3    REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:53 redir ports 53
4    DOCKER     all  --  0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL
5    prerouting_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom prerouting rule chain */
6    zone_lan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         
1    SS_SPEC_WAN_AC  tcp  --  0.0.0.0/0            0.0.0.0/0            /* _SS_SPEC_RULE_ */
2    DOCKER     all  --  0.0.0.0/0           !127.0.0.0/8          ADDRTYPE match dst-type LOCAL

#Mangle chain

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         

#===================== 路由表状态 =====================#
#route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.0.0.1        0.0.0.0         UG    0      0        0 eth0
10.0.0.0        0.0.0.0         255.255.255.0   U     0      0        0 eth0
172.31.0.0      0.0.0.0         255.255.255.0   U     0      0        0 docker0
#ip route list
default via 10.0.0.1 dev eth0 proto static 
10.0.0.0/24 dev eth0 proto kernel scope link src 10.0.0.55 
172.31.0.0/24 dev docker0 proto kernel scope link src 172.31.0.1 
#ip rule show
0:	from all lookup local 
32766:	from all lookup main 
32767:	from all lookup default 

#===================== 端口占用状态 =====================#

#===================== 测试本机DNS查询 =====================#
Server:		127.0.0.1
Address:	127.0.0.1#53

Name:      www.baidu.com
www.baidu.com	canonical name = www.a.shifen.com
Name:      www.a.shifen.com
Address 1: 180.101.49.12
Address 2: 180.101.49.11
*** Can't find www.baidu.com: No answer

#===================== resolv.conf.auto =====================#
# Interface lan
nameserver 10.0.0.1

#===================== 测试本机网络连接 =====================#
HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: private, no-cache, no-store, proxy-revalidate, no-transform
Connection: keep-alive
Content-Length: 277
Content-Type: text/html
Date: Fri, 16 Oct 2020 17:56:18 GMT
Etag: "575e1f60-115"
Last-Modified: Mon, 13 Jun 2016 02:50:08 GMT
Pragma: no-cache
Server: bfe/1.0.8.18


#===================== 测试本机网络下载 =====================#
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 80
Content-Type: text/plain; charset=utf-8
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
ETag: "c99ab8112c4b03a91444540c620183128306cd059f8f42d6c9e3399a4d311342"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
Via: 1.1 varnish (Varnish/6.0)
X-GitHub-Request-Id: A118:33D6:88A677:924253:5F899A64
Accept-Ranges: bytes
Date: Fri, 16 Oct 2020 17:56:19 GMT
Via: 1.1 varnish
X-Served-By: cache-hnd18740-HND
X-Cache: HIT, HIT
X-Cache-Hits: 5, 1
X-Timer: S1602870980.525255,VS0,VE260
Vary: Authorization,Accept-Encoding, Accept-Encoding
Access-Control-Allow-Origin: *
X-Fastly-Request-ID: 1af115b8153b8277614fc66173dfcb613a88e21f
Expires: Fri, 16 Oct 2020 18:01:19 GMT
Source-Age: 0


#===================== 最近运行日志 =====================#
2020-10-17 01:48:12 Warning: OpenClash Now Disabled, Need Start From Luci Page, Exit...
2020-10-17 01:48:08 Config 【Full】 Update Successful
2020-10-17 01:48:31 Config 【Full】 Update Successful
2020-10-17 01:49:16 Nameserver Option Must Be Setted, Auto Completed
time="2020-10-17T01:49:36+08:00" level=fatal msg="Parse config error: proxy group[0]: `use` or `proxies` missing"
2020-10-17 01:49:16 Error: OpenClash Can Not Start, Try Use Raw Config Restart Again
2020-10-17 01:49:16 Error: Get DNS 'listen' Option Error, OpenClash Can Not Start With Raw Config File
2020-10-17 01:49:16 Error: Get DNS 'enhanced-mode' Option Error, OpenClash Can Not Start With Raw Config File
2020-10-17 01:49:16 Error: Get General 'redir-port' Option Error, OpenClash Can Not Start With Raw Config File
time="2020-10-17T01:50:51+08:00" level=fatal msg="Parse config error: rules[0] [DOMAIN-SUFFIX,google.com,auto] error: proxy [auto] not found"
2020-10-17 01:50:44 Error: OpenClash Can Not Start, Try Use Raw Config Restart Again
time="2020-10-17T01:50:57+08:00" level=fatal msg="Parse config error: yaml: line 15: found a tab character that violates indentation"
2020-10-17 01:50:44 Error: OpenClash Can Not Start, Please Check The Error Info And Try Again
2020-10-17 01:52:07 Config 【MY】 Update Successful
2020-10-17 01:53:44 Nameserver Option Must Be Setted, Auto Completed
time="2020-10-17T01:53:54+08:00" level=fatal msg="Parse config error: proxy group[0]: `use` or `proxies` missing"
2020-10-17 01:53:44 Error: OpenClash Can Not Start, Try Use Raw Config Restart Again
2020-10-17 01:53:44 Error: Get DNS 'listen' Option Error, OpenClash Can Not Start With Raw Config File
2020-10-17 01:53:44 Error: Get DNS 'enhanced-mode' Option Error, OpenClash Can Not Start With Raw Config File
2020-10-17 01:53:44 Error: Get General 'redir-port' Option Error, OpenClash Can Not Start With Raw Config File

```

**Comment by vernesong** [comment]
策略组的部分发一下

**Comment by WoodC2011** [comment]
> 策略组的部分发一下

这部分？另外服务器延迟那里全部提示检测失败

port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
proxy-groups:
  - name: Proxies
    type: select
    proxies:
      - HK
      - SG
      - JP
      - US
      - TW
  - name: Apple
    type: select
    proxies:
      - DIRECT
      - Proxies
  - name: MicroSoft
    type: select
    proxies:
      - DIRECT
      - Proxies
  - name: Telegram
    type: select
    proxies:
      - Proxies
      - HK
      - SG
  - name: Netflix
    type: select
    proxies:
      - Proxies
      - HK
      - SG
      - JP
      - US
      - TW
  - name: Netease
    type: select
    proxies:
      - DIRECT
      - Proxies
  - name: HKMTMedia
    type: select
    proxies:
      - DIRECT
      - Proxies
      - TW
  - name: HK
    type: select
  - name: SG
    type: select
  - name: TW
    type: select
  - name: JP
    type: select
  - name: US
    type: select
rules:
省略此部分

**Comment by WoodC2011** [comment]
> 策略组的部分发一下

> 
![FireShot Capture 041 - N1 - 服务器与策略组管理 - LuCI - 10 0 0 55](https://user-images.githubusercontent.com/57359623/96296448-dfd25200-1021-11eb-8ede-1fbea22d7690.jpg)
![下载 (2)](https://user-images.githubusercontent.com/57359623/96296470-e5c83300-1021-11eb-890d-650bed08e83f.png)

**Comment by vernesong** [comment]
没节点的策略组删了

**Comment by WoodC2011** [comment]
> 没节点的策略组删了

删成这样并应用了，还是之前的报错提示

proxy-groups:
  - name: Proxies
    type: select
    proxies:
      - HK
      - SG
      - JP
      - US
      - TW
  - name: Apple
    type: select
    proxies:
      - DIRECT
      - Proxies
  - name: MicroSoft
    type: select
    proxies:
      - DIRECT
      - Proxies
  - name: Telegram
    type: select
    proxies:
      - Proxies
      - HK
      - SG
  - name: Netflix
    type: select
    proxies:
      - Proxies
      - HK
      - SG
      - JP
      - US
      - TW
  - name: Netease
    type: select
    proxies:
      - DIRECT
      - Proxies
  - name: HKMTMedia
    type: select
    proxies:
      - DIRECT
      - Proxies
      - TW

**Comment by WoodC2011** [comment]
> 没节点的策略组删了

解决了，谢谢

**Comment by zcq100** [comment]
> 
> 
> 没节点的策略组删了

我发现 那种引用了其他代理组名称的 代理组，就会出现proxies配置为空的问题。
```
name: ProxyA
  - proxies:
     -....

name: ProxyB
  - proxies:
     -....

name: ProxyCombine
  - proxies:
     - ProxyA
     - ProxyB
```
比如这种，然后ProxyCombine生成的proxies就是空的。

**Comment by vernesong** [comment]
> > 
> 
> > 
> 
> > 没节点的策略组删了
> 
> 
> 
> 我发现 那种引用了其他代理组名称的 代理组，就会出现proxies配置为空的问题。
> 
> ```
> 
> name: ProxyA
> 
> proxies:
> 
>      -....
> 
> 
> 
> name: ProxyB
> 
> proxies:
> 
>      -....
> 
> 
> 
> name: ProxyCombine
> 
> proxies:
> 
>      - ProxyA
> 
>      - ProxyB
> 
> ```
> 
> 比如这种，然后ProxyCombine生成的proxies就是空的。

没有内置yaml解释器，插件脚本暂时不支持读取修改这种格式

**Comment by zcq100** [comment]
@vernesong  那么，不能解析的话，能不能直接把这种 引用策略组 剔除呢？或者直接把这个proxies为空 当异常处理了，全部指向一个默认的策略组(比如DIRECT,REJECT)。
很多机场下发的配置文件已经这么配置了，每次手动去改也不现实。

**Comment by vernesong** [comment]
> @vernesong 那么，不能解析的话，能不能直接把这种 引用策略组 剔除呢？
> 或者直接把这个proxies为空 当异常处理了，全部指向一个默认的策略组 ，或者补一个默认策略(比如DIRECT,REJECT)。这样至少能让服务跑起来，不至于启动失败。
> 很多机场下发的配置文件已经这么写了，每次手动去改也不现实。

直接启动没问题啊，不去服务器与策略组页面操作不会涉及太多脚本操作

**Comment by jacobin** [comment]
> > > 
> > 
> > 
> > > 
> > 
> > 
> > > 没节点的策略组删了
> > 
> > 
> > 我发现 那种引用了其他代理组名称的 代理组，就会出现proxies配置为空的问题。
> > ```
> > 
> > name: ProxyA
> > 
> > proxies:
> > 
> >      -....
> > 
> > 
> > 
> > name: ProxyB
> > 
> > proxies:
> > 
> >      -....
> > 
> > 
> > 
> > name: ProxyCombine
> > 
> > proxies:
> > 
> >      - ProxyA
> > 
> >      - ProxyB
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 比如这种，然后ProxyCombine生成的proxies就是空的。
> 
> 没有内置yaml解释器，插件脚本暂时不支持读取修改这种格式

什么时候能内置yaml解释器呢？我也碰到这个问题了，所以找到了这里。我看到https://github.com/shadowsocksrr/shadowsocksr-csharp/issues/111 有同样的情况，而且有人提出建议：
『这个问题，实际上 是 group 这个字段的功能逻辑混乱问题带来的bug。
单个 ssr url 里都是可以携带 group=xxxx 的，而订阅里的 group 不仅作为分类，还作为所有同名 group 节点在更新订阅时被 “删除” 时要求判断的唯一字段，这就是问题。

即便是订阅中某个节点写错了 group=yyyy（由于最初 breakwa11 娃没有考虑两个变量的逻辑双重属性问题，并没有给订阅来的节点们设置一个独立字段），也会在订阅更新后，把 yyyy 名字的 group 组的所有节点删除！

建议，将订阅获得节点的 group 设置为特殊 group-subscribe，非订阅 节点 group 不变。更新订阅时，只删除 group-subscribe 相同的节点，这个bug就可以解决了。』

谢谢
