### ISSUE TITLE
40.10 fix859 开发大佬看一下

### ISSUE THREAD

**Issue by qin9125** [vernesong/OpenClash#875]
看到您分支修复了859openclash不能启动的问题卸载插件重启路由全新安装，两处都修改为keep=1 --caps="all+eip" -- -c "capsh --user=nobody --addamb='${capabilties}' -- -c 'nohup $CLASH -d $CLASH_CONFIG -f \"$CONFIG_FILE\" >> $LOG_FILE 2>&1 &'"然后重启路由设置完成后启动，结果还是启动失败，这次关闭再打开无法启动。。。我没法子了
2020-10-17 10:12:46 Nameserver Option Must Be Setted, Auto Completed
2020-10-17 10:12:46 Error: OpenClash Can Not Start, Try Use Raw Config Restart Again
2020-10-17 10:12:46 Error: Get DNS 'listen' Option Error, OpenClash Can Not Start With Raw Config File

**Comment by vernesong** [comment]
https://github.com/vernesong/OpenClash/commit/55ad056bec4f6d15f10dcac7a98ab123fafc42d4

**Comment by qin9125** [comment]
> [55ad056](https://github.com/vernesong/OpenClash/commit/55ad056bec4f6d15f10dcac7a98ab123fafc42d4)

感谢您辛苦码代码，我先换回40.7了，强迫症心累看到那个提示更新界面，这几天不是在重启路由，就是在重启的路上，O(∩_∩)O哈哈~

**Comment by qin9125** [comment]
> [55ad056](https://github.com/vernesong/OpenClash/commit/55ad056bec4f6d15f10dcac7a98ab123fafc42d4)

什么时候能编译个dev分支呢？大佬
