### ISSUE TITLE
运行openclash后，会造成DDNS 动态域名解析出问题？ 我之前用的很好的VPN，用了DDNS来解析公网IP，现在无法识别了

### ISSUE THREAD

**Issue by icucuio** [vernesong/OpenClash#877]
运行openclash后，会造成DDNS 动态域名解析出问题？ 我之前用的很好的VPN，用了DDNS来解析公网IP，现在发下无法识别了,关闭openclash后就可以了。

**Comment by goukey** [comment]
别用fake ip

**Comment by shuaigebo** [comment]
用的redir-host兼容模式也不行

**Comment by yankq79** [comment]
使用fake-ip模式的话，要在DNS设置页面下面开启高级设置，然后在下面输入你ddns服务提供商的域名让calsh获取动态ip时返回真实公网ip，啥都不设置的话群晖和其它ddns都会出错访问不到，要么返回的是机场线路的ip，要么返回fake-ip模式虚拟的内网ip地址，并且最近几个opencalsh版本更新之后，就算进行了前面的设置，也依然时好时坏，我已经放弃使用fake-ip模式，目前来看redir-host兼容模式没有这些问题，群晖myds.me，f3322.org，xicp.net这些ddns本人均正常使用中。

**Comment by icucuio** [comment]
能具体说下怎么做的吗？谢谢你。

**Comment by icucuio** [comment]
redir-host 模式好像要比 fake-ip 速度要慢，延时要高

**Comment by yankq79** [comment]
fake-ip模式不说了，我自己也搞不定是好是坏，别误导你了。
redir-host模式不需要什么设置，开启就能用呀，（注：我是在开启此模式后，在openclash-全局设置-访问控制-在黑名单模式下，把NAS的局域网IP添加到不走代理的局域网IP列表中，此步可以解决群晖DSM下DDNS获取到的本地ip变成你翻墙线路ip的问题）。
其它似乎并没有什么特殊设置，请大侠指正。

**Comment by eklim530** [comment]
> 
> 
> fake-ip模式不说了，我自己也搞不定时好时坏，别误导你了。
> redir-host模式不需要什么设置，开启就能用呀，（注：我是在开启此模式后，在openclash-全局设置-访问控制-在黑名单模式下，把NAS的局域网IP添加到不走代理的局域网IP列表中，此步可以解决群晖DSM下DDNS获取到的本地ip变成你翻墙线路ip的问题）。
> 其它似乎并没有什么特殊设置，请大侠指正。

如果想让NAS走代理，这样操作是否就不可以了？因为想用NAS同步Google Drive。。
谢谢！

**Comment by chinadaye** [comment]
> fake-ip模式不说了，我自己也搞不定时好时坏，别误导你了。 redir-host模式不需要什么设置，开启就能用呀，（注：我是在开启此模式后，在openclash-全局设置-访问控制-在黑名单模式下，把NAS的局域网IP添加到不走代理的局域网IP列表中，此步可以解决群晖DSM下DDNS获取到的本地ip变成你翻墙线路ip的问题）。 其它似乎并没有什么特殊设置，请大侠指正。

高手！按的指教设置，解决了。

**Comment by nevertoday** [comment]
最近更新的版本， fake ip 突然又失效了， 奇怪！ sad！

**Comment by xelier** [comment]
在覆写设置->dns设置 里面勾选FAKE-IP-FILTER，勾选黑名单模式 ,把你的域名加进去，比如你的顶级域名是kindom.com，这里填“+.kindom.com”<img width="2097" height="1290" alt="Image" src="https://github.com/user-attachments/assets/f2591188-d5ee-40f1-bd6e-eedbe196bea8" />
如果解析不到ddns服务器的地址，勾选Nameserver-Policy
给自己的域名和ddns服务器请求的地址制定一个DNS地址，格式如下图
<img width="1958" height="1351" alt="Image" src="https://github.com/user-attachments/assets/9f4d590b-edb0-437f-bf3f-490f615ff744" />
