### ISSUE TITLE
/etc/config 中不应储存非luci配置文件

### ISSUE THREAD

**Issue by Mosney** [vernesong/OpenClash#88]
/etc/config 中不应储存非luci配置文件，opkg每次操作都会检查一遍这里面的配置文件，如果存在问题就会回显错误提示`uci: Entry not found`，如下图所示。

> openclash_custom_fake_black.conf
> openclash_custom_hosts.list
> openclash_custom_rules.list

![image](https://user-images.githubusercontent.com/22477230/70617821-67a23f80-1c4c-11ea-9326-2cdd20506181.png)

**Comment by vernesong** [comment]
之前已经注意到了，这个影响不大，考虑到有需要保留配置升级固件的用户所以才放在这里

**Comment by Mosney** [comment]
保留配置的话应该是在`/etc/sysupgrade.conf`或者`/lib/upgrade/keep.d/`里添加

**Comment by vernesong** [comment]
好的
