### ISSUE TITLE
关于内核版本问题

### ISSUE THREAD

**Issue by freett** [vernesong/OpenClash#881]
首先感谢开发组的无私和积极工作，你们的奉献得以让我们能用到好的fq工具。
我有个问题：对于选择clash内核问题，我的路由器是linksys wrt1200ac 处理器架构: arm_cortex-a9_vfpv3-d16，我不知道自己该选哪一个内核版本，而且官方也没有一个正式的对照表格，如果我换了路由器不知道如何辨别内核版本，请问有对应的方法吗 谢谢！

**Comment by vernesong** [comment]
![image](https://user-images.githubusercontent.com/42875168/96357381-b868ab80-112d-11eb-9f20-200c87069d5b.png)

**Comment by freett** [comment]
感谢，但是依然无法启动，log信息如下：
/bin/sh: nohup: not found
2020-10-20 12:18:57 Error: OpenClash Can Not Start, Try Use Raw Config Restart Again
/bin/sh: nohup: not found
2020-10-20 12:18:57 Error: OpenClash Can Not Start, Please Check The Error Info And Try Again

不知道哪里不对

**Comment by vernesong** [comment]
nohup依赖桩号

**Comment by de-conf** [comment]
这个处理器 选择 armv7就行了

**Comment by leanovv** [comment]
太棒了，真遇到这个问题

**Comment by shaokn** [comment]
> 感谢，但是依然无法启动，log信息如下： /bin/sh: nohup: not found 2020-10-20 12:18:57 Error: OpenClash Can Not Start, Try Use Raw Config Restart Again /bin/sh: nohup: not found 2020-10-20 12:18:57 Error: OpenClash Can Not Start, Please Check The Error Info And Try Again
> 
> 不知道哪里不对

我也遇到这个问题了。重新安装一下nohup就好了。

`opkg install coreutils-nohup --force-reinstall`
