### ISSUE TITLE
v0.40.11-beta fe4942c socks5不可用

### ISSUE THREAD

**Issue by openips** [vernesong/OpenClash#882]
之前都是用naive的客户端提供的sock5接口配置到openclash中使用 从4.10版本开始 socks5接口老是检测不到 后台日志和netstate查看没有问题 应该是个bug 麻烦调查一下

**Comment by vernesong** [comment]
本机代理的影响吧，试试新版

**Comment by openips** [comment]
试过了 确实是本机代理问题 新版可以用 但是老报ssl错误 不过不是openclash问题
