### ISSUE TITLE
卸载完10后，安装11报错。

### ISSUE THREAD

**Issue by Eintler** [vernesong/OpenClash#883]
root@Openwrt:/tmp# opkg install luci-app-openclash_0.40.11-beta_all.ipk
Multiple packages (luci-app-openclash and luci-app-openclash) providing same name marked HOLD or PREFER. Using latest.
Installing luci-app-openclash (0.40.11-beta) to root...
Collected errors:
 * pkg_run_script: package "luci-app-openclash" preinst script returned status 1.
 * preinst_configure: Aborting installation of luci-app-openclash.
 * opkg_install_cmd: Cannot install package luci-app-openclash.

求解

**Comment by aguero119** [comment]
请问如何解决的?
