### ISSUE TITLE
错误：Capsh异常，请尝试重新安装依赖【libcap】和相应的Capsh库，终止启动...

### ISSUE THREAD

**Issue by Skytostop** [vernesong/OpenClash#885]
请问报错，怎么解决呢？

**Comment by Skytostop** [comment]
看到其他帖子，貌似输入下面即可
`opkg update
opkg install libcap libcap-bin --force-depends --force-overwrite`

**Comment by hcym** [comment]
重新编译master，一点毛病都没有😂

**Comment by janus2xss** [comment]
> 看到其他帖子，貌似输入下面即可
> `opkg update opkg install libcap libcap-bin --force-depends --force-overwrite`

你的解决了吗？我输入了这个还是提示没有解决呢

**Comment by janus2xss** [comment]
> 重新编译master，一点毛病都没有😂

怎么解决呀？

**Comment by Skytostop** [comment]
opkg update
opkg install libcap libcap-bin --force-depends --force-overwrite
试试






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "janus2xss"<notifications@github.com&gt;; 
发送时间: 2020年10月18日(星期天) 晚上11:16
收件人: "vernesong/OpenClash"<OpenClash@noreply.github.com&gt;; 
抄送: "Frank zhou"<779211327@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [vernesong/OpenClash] 错误：Capsh异常，请尝试重新安装依赖【libcap】和相应的Capsh库，终止启动... (#885)





  
看到其他帖子，貌似输入下面即可
 opkg update opkg install libcap libcap-bin --force-depends --force-overwrite
  
你的解决了吗？我输入了这个还是提示没有解决呢

**Comment by janus2xss** [comment]
> opkg update opkg install libcap libcap-bin --force-depends --force-overwrite 试试
> […](#)

root@OpenWrt:~# opkg install libcap libcap-bin --force-depends --force-overwrite
Package libcap (2.43-1) installed in root is up to date.
Installing libcap-bin (2.43-1) to root...
Downloading https://openwrt.proxy.ustclug.org/snapshots/packages/x86_64/packages/libcap-bin_2.43-1_x86_64.ipk
Collected errors:
 * opkg_install_pkg: Package size mismatch: libcap-bin is 12908 bytes, expecting 12897 bytes
 * opkg_install_cmd: Cannot install package libcap-bin.
出现报错

**Comment by nekomiya-hinata** [comment]
> > opkg update opkg install libcap libcap-bin --force-depends --force-overwrite 试试
> > […](#)
> 
> root@OpenWrt:~# opkg install libcap libcap-bin --force-depends --force-overwrite
> Package libcap (2.43-1) installed in root is up to date.
> Installing libcap-bin (2.43-1) to root...
> Downloading https://openwrt.proxy.ustclug.org/snapshots/packages/x86_64/packages/libcap-bin_2.43-1_x86_64.ipk
> Collected errors:
> 
> * opkg_install_pkg: Package size mismatch: libcap-bin is 12908 bytes, expecting 12897 bytes
> * opkg_install_cmd: Cannot install package libcap-bin.
>   出现报错

这个报错应该是opkg源问题，我换成openwrt官方源后就好了

**Comment by qq1316237299** [comment]
> 毛病都没
最新的也有问题

**Comment by qq1316237299** [comment]
你好作者 最新版的也有这个问题

**Comment by qq1316237299** [comment]
2020-10-19 01:40:07 Warning: Multiple Start Scripts Running, Exit...
2020-10-19 01:41:09 Warning: Multiple Start Scripts Running, Exit...
2020-10-19 01:41:20 Error: Could Not Load The Capsh Library, Please Verify The Capsh Shell Library Work Well
2020-10-19 01:41:20 Tip: You Could Download And Re-Install The libcap & libcap-bin Library From The Address Below:

---------- https://mirrors.cloud.tencent.com/lede/snapshots/packages/ ----------

2020-10-19 01:43:07 Error: Could Not Load The Capsh Library, Please Verify The Capsh Shell Library Work Well
2020-10-19 01:43:07 Tip: You Could Download And Re-Install The libcap & libcap-bin Library From The Address Below:

---------- https://mirrors.cloud.tencent.com/lede/snapshots/packages/ ----------

2020-10-19 01:43:34 Warning: Multiple Start Scripts Running, Exit...
2020-10-19 01:43:55 Warning: Multiple Start Scripts Running, Exit...
我是出现这个错误

**Comment by qq1316237299** [comment]
![image](https://user-images.githubusercontent.com/42686656/96375659-d18f4d80-1169-11eb-9acd-668995b40aeb.png)
![image](https://user-images.githubusercontent.com/42686656/96375667-dbb14c00-1169-11eb-9a18-232ac509b615.png)

**Comment by lozdve** [comment]
> opkg update opkg install libcap libcap-bin --force-depends --force-overwrite 试试
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "janus2xss"<notifications@github.com&gt;; 发送时间: 2020年10月18日(星期天) 晚上11:16 收件人: "vernesong/OpenClash"<OpenClash@noreply.github.com&gt;; 抄送: "Frank zhou"<779211327@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [vernesong/OpenClash] 错误：Capsh异常，请尝试重新安装依赖【libcap】和相应的Capsh库，终止启动... (#885) 看到其他帖子，貌似输入下面即可 opkg update opkg install libcap libcap-bin --force-depends --force-overwrite 你的解决了吗？我输入了这个还是提示没有解决呢 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我用这个成功了，升级到2.43

**Comment by inforest27** [comment]
查看日志，你会找到解决办法

**Comment by solodarker** [comment]
> opkg update opkg install libcap libcap-bin --force-depends --force-overwrite 试试
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "janus2xss"<notifications@github.com&gt;; 发送时间: 2020年10月18日(星期天) 晚上11:16 收件人: "vernesong/OpenClash"<OpenClash@noreply.github.com&gt;; 抄送: "Frank zhou"<779211327@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [vernesong/OpenClash] 错误：Capsh异常，请尝试重新安装依赖【libcap】和相应的Capsh库，终止启动... (#885) 看到其他帖子，貌似输入下面即可 opkg update opkg install libcap libcap-bin --force-depends --force-overwrite 你的解决了吗？我输入了这个还是提示没有解决呢 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
亲测有效！

**Comment by GavinXcXc** [comment]
建议从openwrt官方库中下载最新的libcap，安装后重试。直接自动更新不会更新到最新版本

**Comment by inforest27** [comment]
重新刷固件包了已经解决了，还是谢谢你！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月21日(周三) 晚上11:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [vernesong/OpenClash] 错误：Capsh异常，请尝试重新安装依赖【libcap】和相应的Capsh库，终止启动... (#885)




 
建议从openwrt官方库中下载最新的libcap，安装后重试。直接自动更新不会更新到最新版本

**Comment by forest-river** [comment]
同样的问题无法解决
