### ISSUE TITLE
v0.40.11版本下“服务器&策略组管理”下无法显示服务器节点

### ISSUE THREAD

**Issue by RodmanWang** [vernesong/OpenClash#886]
使用的自定义配置文件订阅，实际所有功能已正常使用。
但是在“服务器&策略组管理”下点击读取配置，无法显示节点，文字一直卡在“开始更新【ok.yaml】的服务器节点配置”，
而在“配置文件管理“可以看到实际配置已正确读取了节点。
之前版本都没有问题，v0.40.11是完全重新安装的固件也不行，麻烦大佬看看，辛苦了

**Comment by wty446** [comment]
我也遇到同样的问题

**Comment by maskedeken** [comment]
问题在这里[https://github.com/vernesong/OpenClash/commit/f261870cb728e7efd747fa37d0946300e7385165#r43358922](https://github.com/vernesong/OpenClash/commit/f261870cb728e7efd747fa37d0946300e7385165#r43358922)

**Comment by RodmanWang** [comment]
按照2楼大佬的指引修改后好了，谢谢
