### ISSUE TITLE
[请问发生什么了?]自40.10开始无法连接所有站点

### ISSUE THREAD

**Issue by phantastar** [vernesong/OpenClash#887]
### 系统平台
OpenWRT v19.07.3 X86_64原版 (已安装最新版libcap和libcap-bin)
### 问题描述
40.8升级40.10/40.11后无法连接任何需要代理的网站
### 复现步骤

1. 重置路由器. 
2. 更新所有软件包+手动下载libcap/libcap-bin并强制重装+安装openclash 40.11并手动存入clash三种内核(然后chmod +x 0644). 
3. 更新clash订阅. 
4. 自定义DNS为114.114.114.114和119.29.29.29 (禁用dnsmasq缓存)
5. 成功开启openclash
6. 事实上无法访问任何网站. 

### 期望结果
希望像40.8一样运转正常
### 调试日志
[openclash-log.txt](https://github.com/vernesong/OpenClash/files/5398583/openclash-log.txt)
_麻烦您了_

**Comment by hcym** [comment]
固件重新编译省心，注意相关依赖包一起加上，我的没什么问题，就是arm的cpu高一点，x86没影响，和40.7比较也没什么提升🥰

**Comment by phantastar** [comment]
> 固件重新编译省心，注意相关依赖包一起加上，我的没什么问题，就是arm的cpu高一点，x86没影响，和40.7比较也没什么提升🥰

好的, 那我暂时回到40.8, 我还留有安装包, 谢谢你
