### ISSUE TITLE
调试日志中报：luci-compat(Luci-19.07): 未安装，怎么安装？

### ISSUE THREAD

**Issue by laosuye** [vernesong/OpenClash#889]
调试日志中报：luci-compat(Luci-19.07): 未安装，怎么安装？

**Comment by YukawaMi** [comment]
这个东西不装你也能用就不要管他了。我之前强行装过，LUCI界面各种报错

**Comment by laosuye** [comment]
是的，我安装了几个版本都会出错！不装也能用！

**Comment by YukawaMi** [comment]
装完最新版本clash发现这玩意儿变成已安装了
