### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by txl263** [vernesong/OpenClash#89]
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/Dreamacro/clash/adapters/outboundgroup.NewURLTest(0xc1cc40, 0xe, 0x88efd8, 0x0, 0x0, 0x0)
	/home/vernesong/clash/adapters/outboundgroup/urltest.go:86 +0x1c4
github.com/Dreamacro/clash/adapters/outboundgroup.ParseProxyGroup(0xc15840, 0xc15980, 0xc159a0, 0x0, 0x0, 0xc7e500, 0x8)
	/home/vernesong/clash/adapters/outboundgroup/parser.go:99 +0x69c
github.com/Dreamacro/clash/config.parseProxies(0xcb4300, 0xc15980, 0xc159a0, 0x0, 0x0)
	/home/vernesong/clash/config/config.go:288 +0xe04
github.com/Dreamacro/clash/config.Parse(0xcca000, 0xbd99, 0xbf99, 0xbd99, 0xbf99, 0x0)
	/home/vernesong/clash/config/config.go:152 +0x2f0
github.com/Dreamacro/clash/hub/executor.ParseWithPath(0xc1a560, 0x1a, 0xc, 0x1a, 0x1)
	/home/vernesong/clash/hub/executor/executor.go:68 +0x90
github.com/Dreamacro/clash/hub/executor.Parse(...)
	/home/vernesong/clash/hub/executor/executor.go:58
github.com/Dreamacro/clash/hub.Parse(0x7fb8db31, 0xe)
	/home/vernesong/clash/hub/hub.go:10 +0x54
main.main()
	/home/vernesong/clash/main.go:61 +0x154
2019-12-11 12:07:43 OpenClash Can Not Start, Try Use Backup Rules Start Again
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/Dreamacro/clash/adapters/outboundgroup.NewURLTest(0x101cc40, 0xe, 0x88efd8, 0x0, 0x0, 0x0)
	/home/vernesong/clash/adapters/outboundgroup/urltest.go:86 +0x1c4
github.com/Dreamacro/clash/adapters/outboundgroup.ParseProxyGroup(0x10157e0, 0x1015920, 0x1015940, 0x0, 0x0, 0x107e480, 0x8)
	/home/vernesong/clash/adapters/outboundgroup/parser.go:99 +0x69c
github.com/Dreamacro/clash/config.parseProxies(0x10b4300, 0x1015920, 0x1015940, 0x0, 0x0)
	/home/vernesong/clash/config/config.go:288 +0xe04
github.com/Dreamacro/clash/config.Parse(0x10ca000, 0x41e, 0x61e, 0x41e, 0x61e, 0x0)
	/home/vernesong/clash/config/config.go:152 +0x2f0
github.com/Dreamacro/clash/hub/executor.ParseWithPath(0x101a560, 0x1a, 0xc, 0x1a, 0x1)
	/home/vernesong/clash/hub/executor/executor.go:68 +0x90
github.com/Dreamacro/clash/hub/executor.Parse(...)
	/home/vernesong/clash/hub/executor/executor.go:58
github.com/Dreamacro/clash/hub.Parse(0x7fa27b31, 0xe)
	/home/vernesong/clash/hub/hub.go:10 +0x54
main.main()
	/home/vernesong/clash/main.go:61 +0x154
2019-12-11 12:07:43 OpenClash Can Not Start, Please Check The Error Info And Try Again

**Comment by vernesong** [comment]
检查下配置文件，看使用一键生成的配置文件是否同样报错

**Comment by txl263** [comment]
就是用的一键生成的配置文件，这log表示内核文件是下载对了吧？就是配置文件的事儿？

**Comment by txl263** [comment]
咦，我把策略组配置清了重新生成就好了

**Comment by txl263** [comment]
> 检查下配置文件，看使用一键生成的配置文件是否同样报错

大佬，默认设置不能登录控制面板，是哪里的问题

**Comment by vernesong** [comment]
> > 检查下配置文件，看使用一键生成的配置文件是否同样报错
> 
> 大佬，默认设置不能登录控制面板，是哪里的问题
登录ip和密码都在控制面板的按钮上面几行显示了

**Comment by txl263** [comment]
> > > 检查下配置文件，看使用一键生成的配置文件是否同样报错
> > 
> > 
> > 大佬，默认设置不能登录控制面板，是哪里的问题
> > 登录ip和密码都在控制面板的按钮上面几行显示了
这个看到了IP端口密钥都有。点击『打开控制面板』跳转的界面不是自动带过去了吗。
但是我理解有误？控制登录面板那里的『编辑外部控制设置』不是登录是设置吗？可是点击确认它还会再弹出。点击取消里面都是空的。

**Comment by txl263** [comment]
另外，代理也没有生效，访问google twitter不成功也没有记录是什么原因呢？
time="2019-12-12T09:37:11Z" level=info msg="192.168.1.101 --> 31.13.76.8 match IPCIDR using Proxy[DigitalOcean]"
time="2019-12-12T09:37:13Z" level=info msg="192.168.1.101 --> 31.13.79.17 match IPCIDR using Proxy[DigitalOcean]"
time="2019-12-12T09:37:16Z" level=info msg="192.168.1.101 --> 31.13.76.8 match IPCIDR using Proxy[DigitalOcean]"
time="2019-12-12T09:37:18Z" level=info msg="192.168.1.101 --> 69.171.244.12 match IPCIDR using Proxy[DigitalOcean]"
time="2019-12-12T09:37:18Z" level=info msg="192.168.1.101 --> 111.206.70.132 match GeoIP using Domestic[DIRECT]"
time="2019-12-12T09:37:18Z" level=info msg="192.168.1.101 --> 111.206.70.132 match GeoIP using Domestic[DIRECT]"
time="2019-12-12T09:37:23Z" level=info msg="192.168.1.101 --> 151.101.0.133 match Match using Others[DigitalOcean]"
time="2019-12-12T09:37:37Z" level=info msg="192.168.1.101 --> 123.126.97.78 match GeoIP using Domestic[DIRECT]"
time="2019-12-12T09:37:37Z" level=info msg="192.168.1.101 --> 123.126.97.78 match GeoIP using Domestic[DIRECT]"
time="2019-12-12T09:37:40Z" level=info msg="192.168.1.101 --> 93.158.134.82 match Match using Others[DigitalOcean]"
time="2019-12-12T09:37:42Z" level=info msg="192.168.1.101 --> 69.171.244.12 match IPCIDR using Proxy[DigitalOcean]"
time="2019-12-12T09:37:47Z" level=info msg="192.168.1.161 --> applog.uc.cn match DomainSuffix using Domestic[DIRECT]"
time="2019-12-12T09:37:49Z" level=info msg="192.168.1.101 --> 31.13.76.8 match IPCIDR using Proxy[DigitalOcean]"
time="2019-12-12T09:37:52Z" level=info msg="192.168.1.101 --> 54.169.195.247 match Match using Others[DigitalOcean]"
time="2019-12-12T09:37:53Z" level=info msg="192.168.1.101 --> 13.250.168.23 match Match using Others[DigitalOcean]"
time="2019-12-12T09:37:53Z" level=info msg="192.168.1.101 --> 13.250.168.23 match Match using Others[DigitalOcean]"
time="2019-12-12T09:37:57Z" level=info msg="192.168.1.101 --> 13.250.168.23 match Match using Others[DigitalOcean]"
time="2019-12-12T09:37:59Z" level=info msg="192.168.1.100 --> collections.yandex.ru match DomainSuffix using Proxy[DigitalOcean]"
time="2019-12-12T09:38:00Z" level=info msg="192.168.1.101 --> 207.244.67.215 match Match using Others[DigitalOcean]"
time="2019-12-12T09:38:00Z" level=info msg="192.168.1.101 --> 207.244.67.215 match Match using Others[DigitalOcean]"
time="2019-12-12T09:38:19Z" level=info msg="192.168.1.101 --> 111.206.70.132 match GeoIP using Domestic[DIRECT]"
time="2019-12-12T09:38:19Z" level=info msg="192.168.1.101 --> 111.206.70.132 match GeoIP using Domestic[DIRECT]"
time="2019-12-12T09:38:38Z" level=info msg="192.168.1.101 --> 123.126.97.78 match GeoIP using Domestic[DIRECT]"
time="2019-12-12T09:38:38Z" level=info msg="192.168.1.101 --> 123.126.97.78 match GeoIP using Domestic[DIRECT]"
time="2019-12-12T09:38:40Z" level=info msg="192.168.1.101 --> 111.202.100.60 match GeoIP using Domestic[DIRECT]"
time="2019-12-12T09:38:55Z" level=info msg="192.168.1.101 --> 17.250.121.17 match IPCIDR using Apple[DIRECT]"
time="2019-12-12T09:38:56Z" level=info msg="192.168.1.101 --> 220.194.252.6 match GeoIP using Domestic[DIRECT]"
time="2019-12-12T09:38:56Z" level=info msg="192.168.1.101 --> 17.250.121.17 match IPCIDR using Apple[DIRECT]"
time="2019-12-12T09:38:57Z" level=info msg="192.168.1.101 --> 17.250.121.17 match IPCIDR using Apple[DIRECT]"
time="2019-12-12T09:39:00Z" level=info msg="192.168.1.101 --> 17.252.201.246 match IPCIDR using Apple[DIRECT]"
time="2019-12-12T09:39:02Z" level=info msg="192.168.1.101 --> 216.58.200.238 match IPCIDR using Proxy[DigitalOcean]"
time="2019-12-12T09:39:02Z" level=info msg="192.168.1.101 --> 172.217.160.78 match IPCIDR using Proxy[DigitalOcean]"
time="2019-12-12T09:39:02Z" level=info msg="192.168.1.101 --> 103.235.46.39 match Match using Others[DigitalOcean]"
time="2019-12-12T09:39:02Z" level=info msg="192.168.1.101 --> 172.217.160.78 match IPCIDR using Proxy[DigitalOcean]"
time="2019-12-12T09:39:03Z" level=info msg="192.168.1.101 --> 172.217.160.78 match IPCIDR using Proxy[DigitalOcean]"
time="2019-12-12T09:39:03Z" level=info msg="192.168.1.101 --> 172.217.160.78 match IPCIDR using Proxy[DigitalOcean]"
time="2019-12-12T09:39:03Z" level=info msg="192.168.1.101 --> 172.217.160.78 match IPCIDR using Proxy[DigitalOcean]"
time="2019-12-12T09:39:04Z" level=info msg="192.168.1.101 --> 61.135.169.125 match GeoIP using Domestic[DIRECT]"
time="2019-12-12T09:39:04Z" level=info msg="192.168.1.101 --> 61.135.169.125 match GeoIP using Domestic[DIRECT]"
time="2019-12-12T09:39:04Z" level=info msg="192.168.1.101 --> 61.135.169.125 match GeoIP using Domestic[DIRECT]"
time="2019-12-12T09:39:04Z" level=info msg="192.168.1.101 --> 61.135.169.125 match GeoIP using Domestic[DIRECT]"
time="2019-12-12T09:39:04Z" level=info msg="192.168.1.101 --> 123.125.132.33 match GeoIP using Domestic[DIRECT]"
time="2019-12-12T09:39:04Z" level=info msg="192.168.1.101 --> 123.125.132.32 match GeoIP using Domestic[DIRECT]"
time="2019-12-12T09:39:04Z" level=info msg="192.168.1.101 --> 220.181.38.148 match GeoIP using Domestic[DIRECT]"
time="2019-12-12T09:39:04Z" level=info msg="192.168.1.101 --> 61.135.169.125 match GeoIP using Domestic[DIRECT]"
time="2019-12-12T09:39:05Z" level=info msg="192.168.1.101 --> 123.125.132.32 match GeoIP using Domestic[DIRECT]"
time="2019-12-12T09:39:05Z" level=info msg="192.168.1.101 --> 61.135.169.125 match GeoIP using Domestic[DIRECT]"
time="2019-12-12T09:39:05Z" level=info msg="192.168.1.101 --> 61.135.169.125 match GeoIP using Domestic[DIRECT]"
time="2019-12-12T09:39:07Z" level=info msg="192.168.1.100 --> www.archlinux.org match Match using Others[DigitalOcean]"
time="2019-12-12T09:39:08Z" level=info msg="192.168.1.101 --> 123.125.132.33 match GeoIP using Domestic[DIRECT]"
time="2019-12-12T09:39:08Z" level=info msg="192.168.1.101 --> 123.125.132.33 match GeoIP using Domestic[DIRECT]"
time="2019-12-12T09:39:08Z" level=info msg="192.168.1.101 --> 123.125.132.33 match GeoIP using Domestic[DIRECT]"
time="2019-12-12T09:39:08Z" level=info msg="192.168.1.101 --> 123.125.132.33 match GeoIP using Domestic[DIRECT]"
time="2019-12-12T09:39:10Z" level=info msg="192.168.1.101 --> 123.125.132.35 match GeoIP using Domestic[DIRECT]"
time="2019-12-12T09:39:11Z" level=info msg="192.168.1.101 --> 123.125.132.35 match GeoIP using Domestic[DIRECT]"
time="2019-12-12T09:39:11Z" level=info msg="192.168.1.101 --> 123.125.132.35 match GeoIP using Domestic[DIRECT]"
time="2019-12-12T09:39:11Z" level=info msg="192.168.1.101 --> 103.235.46.39 match Match using Others[DigitalOcean]"
time="2019-12-12T09:39:11Z" level=info msg="192.168.1.101 --> 103.235.46.39 match Match using Others[DigitalOcean]"
time="2019-12-12T09:39:13Z" level=info msg="192.168.1.101 --> 103.235.46.39 match Match using Others[DigitalOcean]"
time="2019-12-12T09:39:14Z" level=info msg="192.168.1.101 --> 111.206.23.14 match GeoIP using Domestic[DIRECT]"
time="2019-12-12T09:39:20Z" level=info msg="192.168.1.101 --> 103.235.46.39 match Match using Others[DigitalOcean]"
time="2019-12-12T09:39:20Z" level=info msg="192.168.1.101 --> 121.40.43.188 match GeoIP using Domestic[DIRECT]"
time="2019-12-12T09:39:20Z" level=info msg="192.168.1.101 --> 42.121.254.191 match GeoIP using Domestic[DIRECT]"
time="2019-12-12T09:39:21Z" level=info msg="192.168.1.100 --> hm.baidu.com match DomainSuffix using Domestic[DIRECT]"
time="2019-12-12T09:39:21Z" level=info msg="192.168.1.101 --> 118.178.109.187 match GeoIP using Domestic[DIRECT]"
time="2019-12-12T09:39:21Z" level=info msg="192.168.1.101 --> 202.106.2.48 match GeoIP using Domestic[DIRECT]"
time="2019-12-12T09:39:21Z" level=info msg="192.168.1.101 --> 202.108.249.231 match GeoIP using Domestic[DIRECT]"
time="2019-12-12T09:39:21Z" level=info msg="192.168.1.101 --> 220.194.79.73 match GeoIP using Domestic[DIRECT]"
time="2019-12-12T09:39:21Z" level=info msg="192.168.1.101 --> 220.194.87.190 match GeoIP using Domestic[DIRECT]"
time="2019-12-12T09:39:21Z" level=info msg="192.168.1.101 --> 220.194.87.190 match GeoIP using Domestic[DIRECT]"
time="2019-12-12T09:39:21Z" level=info msg="192.168.1.101 --> 220.194.87.190 match GeoIP using Domestic[DIRECT]"
time="2019-12-12T09:39:21Z" level=info msg="192.168.1.101 --> 121.40.43.188 match GeoIP using Domestic[DIRECT]"
time="2019-12-12T09:39:21Z" level=info msg="192.168.1.101 --> 111.231.37.102 match GeoIP using Domestic[DIRECT]"
time="2019-12-12T09:39:22Z" level=info msg="192.168.1.101 --> 118.178.109.187 match GeoIP using Domestic[DIRECT]"
time="2019-12-12T09:39:23Z" level=info msg="192.168.1.101 --> 111.161.111.22 match GeoIP using Domestic[DIRECT]"
time="2019-12-12T09:39:25Z" level=info msg="192.168.1.101 --> 17.248.160.84 match IPCIDR using Apple[DIRECT]"
time="2019-12-12T09:39:26Z" level=info msg="192.168.1.101 --> 220.194.252.3 match GeoIP using Domestic[DIRECT]"
time="2019-12-12T09:39:26Z" level=info msg="192.168.1.101 --> 111.206.70.132 match GeoIP using Domestic[DIRECT]"
time="2019-12-12T09:39:26Z" level=info msg="192.168.1.101 --> 17.248.160.84 match IPCIDR using Apple[DIRECT]"
time="2019-12-12T09:39:26Z" level=info msg="192.168.1.101 --> 17.250.121.17 match IPCIDR using Apple[DIRECT]"
time="2019-12-12T09:39:28Z" level=info msg="192.168.1.101 --> 220.194.252.3 match GeoIP using Domestic[DIRECT]"
time="2019-12-12T09:39:38Z" level=info msg="192.168.1.101 --> 123.126.97.78 match GeoIP using Domestic[DIRECT]"
time="2019-12-12T09:39:38Z" level=info msg="192.168.1.101 --> 123.126.97.78 match GeoIP using Domestic[DIRECT]"
time="2019-12-12T09:39:40Z" level=info msg="192.168.1.161 --> applog.uc.cn match DomainSuffix using Domestic[DIRECT]"
time="2019-12-12T09:39:48Z" level=info msg="192.168.1.161 --> applog.uc.cn match DomainSuffix using Domestic[DIRECT]"
time="2019-12-12T09:39:53Z" level=info msg="192.168.1.161 --> applog.uc.cn match DomainSuffix using Domestic[DIRECT]"
time="2019-12-12T09:39:55Z" level=info msg="192.168.1.101 --> 67.208.88.211 match Match using Others[DigitalOcean]"
time="2019-12-12T09:40:07Z" level=info msg="192.168.1.101 --> 111.202.74.190 match GeoIP using Domestic[DIRECT]"
time="2019-12-12T09:40:08Z" level=info msg="192.168.1.101 --> 111.161.111.22 match GeoIP using Domestic[DIRECT]"
time="2019-12-12T09:40:18Z" level=info msg="192.168.1.101 --> 111.206.23.96 match GeoIP using Domestic[DIRECT]"
time="2019-12-12T09:40:18Z" level=info msg="192.168.1.101 --> 111.206.23.96 match GeoIP using Domestic[DIRECT]"
time="2019-12-12T09:40:27Z" level=info msg="192.168.1.101 --> 123.125.84.246 match GeoIP using Domestic[DIRECT]"
time="2019-12-12T09:40:34Z" level=info msg="192.168.1.101 --> 111.206.13.225 match GeoIP using Domestic[DIRECT]"
time="2019-12-12T09:40:34Z" level=info msg="192.168.1.101 --> 123.125.115.196 match GeoIP using Domestic[DIRECT]"
time="2019-12-12T09:40:34Z" level=info msg="192.168.1.101 --> 123.125.132.41 match GeoIP using Domestic[DIRECT]"
time="2019-12-12T09:40:41Z" level=info msg="192.168.1.101 --> 123.126.97.78 match GeoIP using Domestic[DIRECT]"
time="2019-12-12T09:40:41Z" level=info msg="192.168.1.101 --> 123.126.97.78 match GeoIP using Domestic[DIRECT]"

**Comment by vernesong** [comment]
![image](https://user-images.githubusercontent.com/42875168/70715299-f4b8c780-1d24-11ea-84d8-beacb08eef90.png)
BT
![image](https://user-images.githubusercontent.com/42875168/70715335-0a2df180-1d25-11ea-9953-e07c332ac22c.png)

**Comment by txl263** [comment]
多谢大佬，控制面板突然也好了。。
然后现在google又不能访问了。。。抓狂中  网站访问检查显示Facebook和yourube连接超时，是代理出问题吗还是DNS的问题
美团外卖APP的是可以加在自定义规则里吧
最后，全局设置里的规则设置和控制面板里的是同时生效吗？控制面板里的是内核？规则是套在外面的？

**Comment by vernesong** [comment]
一键生成的配置就够用了，其他不用动。
访问有问题你可以去wiki对照着排查，一个是先关闭ipv6，一个是dns劫持有没有受影响

**Comment by txl263** [comment]
把本地DNS都改成了网关就都OK了！
继续研究，感谢！

**Comment by txl263** [comment]
自定义规则(访问控制)  启用
- DOMAIN-SUFFIX,pcbeta.com,Proxy
在『配置文件』里也看到已经加了进去
然后没起作用，还是打不开，提示『未连接到互联网』
是规则写的不对还是有其他需要设置的地方？

**Comment by vernesong** [comment]
检查内核日志，每个访问连接的流量都有详细描述
