### ISSUE TITLE
openclash突然消失

### ISSUE THREAD

**Issue by 00LT00** [vernesong/OpenClash#894]
大佬，我今天进来看到我的版本可以升级，然后我就点了，后来看上面红字提示说固件版本不正确，然后没动静了，我重新连就已经没有openclash的服务了，刚刚路由器里搜了半天就只有两个名字里带着openclash的配置文件，然后无论安装还是卸载都会提示
![image](https://user-images.githubusercontent.com/47566260/96468658-edc0e680-125e-11eb-887f-41cb0cca3b85.png)

现在就完全没法使用，请问应该怎么办。。

**Comment by i5ean** [comment]
重刷系统，最快最简单的方法

**Comment by 00LT00** [comment]
行倒也行，但就不是很明白为啥会有这种问题。。更新了个内核一下子啥都不剩了

**Comment by i5ean** [comment]
我之前也出现过这种情况，主要还是程序不稳定造成的

**Comment by 00LT00** [comment]
根据 #839 中的描述，升级0.40.8的版本的时候新增了三个包，由于我的版本是18.06.4，已经属于过时的版本，在默认的源中并没有这几个包，可以通过添加源地址来解决
```
src/gz snapshots https://downloads.openwrt.org/snapshots/packages/mipsel_24kc/packages/
```

**Comment by matthuo333** [comment]
并未做版本升级，只要更换源，oc就消失了

**Comment by matthuo333** [comment]
> 根据 #839 中的描述，升级0.40.8的版本的时候新增了三个包，由于我的版本是18.06.4，已经属于过时的版本，在默认的源中并没有这几个包，可以通过添加源地址来解决
> 
> ```
> src/gz snapshots https://downloads.openwrt.org/snapshots/packages/mipsel_24kc/packages/
> ```

只要更换源，就导致oc从ui中消失

**Comment by cian179** [comment]
请问你是怎么解决的 我也遇到了这个问题

**Comment by i5ean** [comment]
> 请问你是怎么解决的 我也遇到了这个问题

更换老版本，这次消失跟之前的原因不一样
