### ISSUE TITLE
openclash 服务脚本修改防火墙 默认forward策略为ACCEPT？

### ISSUE THREAD

**Issue by jimmygc** [vernesong/OpenClash#895]
似乎不应该去修改防火墙默认规则，导致每次修改防火墙forward策略为DROP之后又被自动改成 ACCEPT。
是有什么特殊作用吗？我修改成DROP之后似乎也不影响使用。

相关代码：
https://github.com/vernesong/OpenClash/blob/758f403ae160061bd4f2c1d9765dc9e3d9c6b3ea/luci-app-openclash/root/etc/init.d/openclash#L1296-L1300

**Comment by vernesong** [comment]
tun路由需要
