### ISSUE TITLE
功能受限

### ISSUE THREAD

**Issue by cqmylx** [vernesong/OpenClash#896]
v0.40.10-beta版本后（包括最新的v0.40.11-beta）出现提示功能受限状态 尝试过多种模式都提示 功能受限状态
![QQ截图20201020203820](https://user-images.githubusercontent.com/67597378/96587108-78afe880-1314-11eb-89ba-38b7b787a4c5.jpg)

**Comment by LOVE2CMOL** [comment]
你看下调试日志，是不是少了某项插件

**Comment by vernesong** [comment]
某些配置文件经过脚本修改无法启动时会尝试使用原始的配置文件启动，此时显示受限状态
