### ISSUE TITLE
安装时提示找不到"iptables-mod-extra"这个依赖

### ISSUE THREAD

**Issue by moekyo** [vernesong/OpenClash#897]
安装最新版的时候，提示找不到`Installing luci-app-openclash (0.40.11-beta) to root...
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-app-openclash:
 *      iptables-mod-extra
 * opkg_install_cmd: Cannot install package luci-app-openclash.
`
在软件包里面也没有找到这个依赖，更新了也一样，请问要怎么解决？

**Comment by Gol2dragon** [comment]
我的也一样，网上也找不到

**Comment by i5ean** [comment]
opkg install iptables-mod-extra

**Comment by moekyo** [comment]
> opkg install iptables-mod-extra
提示下面, 试过opkg update也一样
opkg install iptables-mod-extra
Unknown package 'iptables-mod-extra'.
Collected errors:
 * opkg_install_cmd: Cannot install package iptables-mod-extra.

**Comment by i5ean** [comment]
> > opkg install iptables-mod-extra
> 
> opkg install iptables-mod-extra
> Unknown package 'iptables-mod-extra'.
> Collected errors:
> 
> * opkg_install_cmd: Cannot install package iptables-mod-extra.
> 
> 提示这些, 试过opkg update也一样

你的源有问题，换个源试试

**Comment by moekyo** [comment]
> > > opkg install iptables-mod-extra
> 
> > 
> 
> > opkg install iptables-mod-extra
> 
> > Unknown package 'iptables-mod-extra'.
> 
> > Collected errors:
> 
> > 
> 
> > * opkg_install_cmd: Cannot install package iptables-mod-extra.
> 
> > 
> 
> > 提示这些, 试过opkg update也一样
> 
> 
> 
> 你的源有问题，换个源试试

能贴一下吗，谢谢🤣

**Comment by i5ean** [comment]
手工替换
登录到路由器，并编辑 /etc/opkg/distfeeds.conf 文件，将其中的 downloads.openwrt.org 替换为 mirrors.tuna.tsinghua.edu.cn/openwrt 即可。

自动替换
执行如下命令自动替换

sed -i 's_downloads.openwrt.org_mirrors.tuna.tsinghua.edu.cn/openwrt_' /etc/opkg/distfeeds.conf

或者中科大的http://mirrors.ustc.edu.cn/

**Comment by moekyo** [comment]
> 手工替换
> 登录到路由器，并编辑 /etc/opkg/distfeeds.conf 文件，将其中的 downloads.openwrt.org 替换为 mirrors.tuna.tsinghua.edu.cn/openwrt 即可。
> 
> 自动替换
> 执行如下命令自动替换
> 
> sed -i 's_downloads.openwrt.org_mirrors.tuna.tsinghua.edu.cn/openwrt_' /etc/opkg/distfeeds.conf
> 
> 或者中科大的http://mirrors.ustc.edu.cn/

谢谢!

**Comment by matthuo333** [comment]
![image](https://user-images.githubusercontent.com/55862904/103137842-a3009680-4707-11eb-8542-dd67e72d5055.png)
已经替换，为啥仍然不行呢？

**Comment by lbx0502** [comment]
> ![image](https://user-images.githubusercontent.com/55862904/103137842-a3009680-4707-11eb-8542-dd67e72d5055.png) 已经替换，为啥仍然不行呢？

我也是啊，我用的清华的还显示cannot install

**Comment by TMXKWWZ** [comment]
依赖的软件包 iptables-mod-conntrack-extra 在所有仓库都未提供。
依赖的软件包 iptables-mod-iprange 在所有仓库都未提供。
这无解了吗？根本没办法弄，
