### ISSUE TITLE
luci设置定时任务后，系统日志里报错。

### ISSUE THREAD

**Issue by NV3S** [vernesong/OpenClash#9]
今天看系统日志发现有
`Mon Jul 29 10:13:00 2019 cron.err crond[23317]: user root: parse error at 7
`
用 crontab -l看了下，里面有
```
root@Openwrt:/koolshare/scripts# crontab -l

0 0 * * 7 /usr/share/openclash/openclash.sh
0 0 * * 1 /usr/share/openclash/openclash_ipdb.sh
```
这条目最后的 7 是前台luci设置了“周日”的两个定时任务，但其实openwrt里面最后这个字段支持是 [0-6（0代表周日）](https://openwrt.org/docs/guide-user/base-system/cron)

请确认。

**Comment by vernesong** [comment]
OK
