### ISSUE TITLE
显示IP问题

### ISSUE THREAD

**Issue by francis5959** [vernesong/OpenClash#901]
感谢大神的辛勤劳作。请教一下，记得以前的版本首页显示的ip国内的显示为国内ip，国外显示为国外ip，怎么现在都显示的是国外的ip？另外我家里架设了回国服务器，但拿不到国内的ip，还是看不了国内的视频，请教能解决吗？

**Comment by vernesong** [comment]
IP显示完全看你的规则怎么处理，查询IP的地址走代理就会显示代理IP，回国规则里需要代理国内地址你让他走代理，其他全部直连

**Comment by francis5959** [comment]
感谢大神回复。
我的openwrt上既架设了v2ray等回国服务器，也开了clash再fanqiang出去。国外的openwrt上运行clash，规则是默认的回国模式，看了一下，规则应该是对的，国内地址走代理，其他都直通。关键是我国外的客户端通过我国内的服务器回国拿到的还是国外的ip，所以提示地区限制不能观看，关闭clash，ip就是国内的了，观看正常，但是我也fanqiang不了了。目前只能用passwall，回国出去都正常了。同时测试过hello world和SSR plus等，回国都拿不到国内ip。
