### ISSUE TITLE
lede安装openclash后无法更新配置文件的原因已找到

### ISSUE THREAD

**Issue by yhl452493373** [vernesong/OpenClash#905]
根据V大发布说明，需要安装curl，但是lede自带了curl，版本为7.71.1-1，如果更新到最新的7.72，会因为缺少一个so库导致curl无法运行进而导订阅更新失败、插件版本检查失败、clash检测失败等一系列和网络有关的失败出现。

**因此lede安装openclash时，不要安装或升级curl！**

**Comment by OiCkilL** [comment]
我也发现了，curl启动不成功。会提示
Error loading shared library libwolfssl.so.24: No such file or directory (needed by /usr/bin/curl)

**Comment by KomoreKalu** [comment]
安装libwolfssl24就好咯

`opkg install libwolfssl24`

( x86_64 和 mt7621 确认可用)     @OiCkilL @yhl452493373

**Comment by yhl452493373** [comment]
> 安装libwolfssl24就好咯
> 
> `opkg install libwolfssl24`
> 
> ( x86_64 和 mt7621 确认可用) @OiCkilL @yhl452493373

不装了，反正没啥影响。担心安装了这个后其他又出问题，难得搞

**Comment by LostSmoch** [comment]
> 安装libwolfssl24就好咯
> 
> `opkg install libwolfssl24`
> 
> ( x86_64 和 mt7621 确认可用) @OiCkilL @yhl452493373

请问提示未知安装包怎么解决

**Comment by KomoreKalu** [comment]
> > 安装libwolfssl24就好咯
> > `opkg install libwolfssl24`
> > ( x86_64 和 mt7621 确认可用) @OiCkilL @yhl452493373
> 
> 请问提示未知安装包怎么解决

先执行 opkg update

**Comment by xiaokaig** [comment]
maye，终于解决了
