### ISSUE TITLE
0.40.12 连接数太多

### ISSUE THREAD

**Issue by gui-li** [vernesong/OpenClash#907]
安装0.40.12后连接数一直保持在16000左右，回退到0.40.7只有200左右
0.40.12还有连国内慢的问题，甚至是无法连接国内网络

**Comment by AntHp** [comment]
确实内存会占用很多，卡死软路由。

**Comment by vernesong** [comment]
内核更新没有？发下日志

**Comment by gui-li** [comment]
> 
> 
> 问题已知，暂时不要使用redir混合模式和redir-tun

当时是tun mixed mode和fake-ip
