### ISSUE TITLE
更新0.40.12版无法启动，重新安装也安装不了 0.40.12。

### ISSUE THREAD

**Issue by xpn282** [vernesong/OpenClash#912]
在线更新0.40.12的时候，不能启动，提示“错误：Capsh异常，请尝试重新安装依赖【libcap】和相应的Capsh库，终止启动...”

我尝试过其他帖子的方法，输入“opkg update opkg install libcap libcap-bin --force-depends --force-overwrite”也没用。。

然后卸载了，想重新安装0.40.12，也不能安装，提示如下2个图：
<img width="678" alt="截屏2020-10-23 下午12 58 07" src="https://user-images.githubusercontent.com/53807602/96963009-7af38c00-153a-11eb-8ab7-a39f2c82070d.png">
<img width="682" alt="截屏2020-10-23 下午12 52 04" src="https://user-images.githubusercontent.com/538076023/96963028-82b33080-153a-11eb-89cd-6b11df3880f2.png">

不知道该怎么办了，，

**Comment by evileonline** [comment]
opkg update opkg install libcap libcap-bin --force-depends --force-overwrite
使用这个命令在科学上网的环境可以下载，之后在openwrt的系统界面，软件包选项下安装libcap和libcap-bin。
在做着个动作之前，我有把libcap重新删除的动作，也把openclah.ipk通过系统界面，文件传输选项上传重新安装过。希望对你有帮助

**Comment by xpn282** [comment]
回复楼上的：
我试过了，在翻墙的情况下使用命令，并且重新更新了libcap2.43-1和libcap-bin2.43-1。
<img width="743" alt="截屏2020-10-23 下午10 31 36" src="https://user-images.githubusercontent.com/53807602/97016778-bd8b8780-157f-11eb-9077-65eb9b0c9444.png">



但是还是无法安装OpenClash。。。我已经没用办法了，是不是固件的原因？
<img width="671" alt="截屏2020-10-23 下午10 27 21" src="https://user-images.githubusercontent.com/53807602/97016788-bfede180-157f-11eb-912e-ca5b5aa5040d.png">

**Comment by evileonline** [comment]
删除重新安装呢，我是这样操作的

**Comment by xpn282** [comment]
就是删除了，重新安装不了。。
安装旧版的可以，比如0.40.7

**Comment by swxiaoqiang** [comment]
我也是这样，不过我能安装40.13版本
libcap libcap-bin这两个文件在哪里下载，找不到

**Comment by huiyuanfan** [comment]
> 我也是这样，不过我能安装40.13版本
> libcap libcap-bin这两个文件在哪里下载，找不到

https://downloads.openwrt.org/snapshots/packages/x86_64/packages/libcap_2.43-1_x86_64.ipk
https://downloads.openwrt.org/snapshots/packages/x86_64/packages/libcap-bin_2.43-1_x86_64.ipk

**Comment by swxiaoqiang** [comment]
@huiyuanfan 谢谢

**Comment by vernesong** [comment]
依赖确认装好，opkg install --force-depends

**Comment by Yohoa** [comment]
> 
> 
> 回复楼上的：
> 我试过了，在翻墙的情况下使用命令，并且重新更新了libcap2.43-1和libcap-bin2.43-1。
> <img alt="截屏2020-10-23 下午10 31 36" width="743" src="https://user-images.githubusercontent.com/53807602/97016778-bd8b8780-157f-11eb-9077-65eb9b0c9444.png">
> 
> 但是还是无法安装OpenClash。。。我已经没用办法了，是不是固件的原因？
> <img alt="截屏2020-10-23 下午10 27 21" width="671" src="https://user-images.githubusercontent.com/53807602/97016788-bfede180-157f-11eb-912e-ca5b5aa5040d.png">

我遇到了一样的问题，我的内核版本不能满足这个ipk 的dependence

**Comment by adminzt123** [comment]
> > 我也是这样，不过我能安装40.13版本
> > libcap libcap-bin这两个文件在哪里下载，找不到
> 
> https://downloads.openwrt.org/snapshots/packages/x86_64/packages/libcap_2.43-1_x86_64.ipk
> https://downloads.openwrt.org/snapshots/packages/x86_64/packages/libcap-bin_2.43-1_x86_64.ipk

谢谢，你的方法真好。
这样测试一下后，正常了。原因难道是固件太新了？
刚刚自制的固件。
