### ISSUE TITLE
请问怎样看软路由上的Transmission BT下载的流量是否走代理呢

### ISSUE THREAD

**Issue by warcns** [vernesong/OpenClash#919]
请问大佬怎样能看出软路由上的Transmission BT下载的流量是否走代理呢，可以从YACD控制面板的Connections看出来吗？

**Comment by vernesong** [comment]
控制面板筛选出来源是路由IP和TUN模式下来源是198.18.0.1的流量

**Comment by warcns** [comment]
好的，非常感谢。我软路由当作旁路网关用的，好像没这个问题。
