### ISSUE TITLE
无法安装问题

### ISSUE THREAD

**Issue by xiaogei** [vernesong/OpenClash#922]
Collected errors:
 * pkg_run_script: package "luci-app-openclash" preinst script returned status 1.
 * preinst_configure: Aborting installation of luci-app-openclash.
 * opkg_install_cmd: Cannot install package luci-app-openclash.

看过之前有个同样的问题。反馈闪存不足，我扩容了overlay，软件包还剩900M，重新安装，依旧无法安装。不知道软件包的容量是否就是您说的闪存不足，谢谢！不知道，还有什么原因导致这个问题，如何解决，请指教，谢谢！

安装iptables-mod-extra依赖，提示 kernel (= 5.4.72-1-eb5b21fb826061b04f221aa914052001) 内核不匹配这问题该如何解决？谢谢

**Comment by xiaogei** [comment]
不知道，还有什么原因导致这个问题，如何解决，请指教，谢谢！

**Comment by hcym** [comment]
重新编译固件就完事了，用master的源码加上相关依赖包，我的arm和x86都正常安装运行

**Comment by Nepmonts** [comment]
依赖最好编译的时候加进去

**Comment by xiaogei** [comment]
> 依赖最好编译的时候加进去

好的，我重新编译试试

**Comment by xiaogei** [comment]
> 重新编译固件就完事了，用master的二进制加上相关依赖包，我的arm和x86都正常安装运行

我的是X86架构，不是很理解master的二进制，能否简单讲下，编译时关于master的二进制的操作

**Comment by hcym** [comment]
没有什么二进制的事。 就是用主分支编译了，最新的每日更新的，其他都一样的，主要是担心那个什么cap依赖，从40.8到40.14都正常安装，不用clash新版本的话用1907.4也可以，没感觉什么变化

**Comment by xiaogei** [comment]
> 就是用主分区编译了，最新的每日更新的，其他都一样的，主要是担心那个什么cap依赖，从40.8到40.14都正常安装，不用clash新版本的话用1907.4也可以，没感觉什么变化

我编译的时候把所需要的依赖都编译进去了，但还是提示pkg_run_script: package "luci-app-openclash" preinst script returned status 1.

**Comment by xiaogei** [comment]
> > 就是用主分区编译了，最新的每日更新的，其他都一样的，主要是担心那个什么cap依赖，从40.8到40.14都正常安装，不用clash新版本的话用1907.4也可以，没感觉什么变化
> 
> 我编译的时候把所需要的依赖都编译进去了，但还是提示pkg_run_script：包“ luci-app-openclash” preinst脚本返回了状态1。

哪怕用--force-depends

**Comment by xiaogei** [comment]
安装luci-app-clash没问题。不知道，到底是什么问题无法安装openclash
