### ISSUE TITLE
无法安装问题

### ISSUE THREAD

**Issue by Material3600** [vernesong/OpenClash#923]
在之前的步骤均按照教程进行的情况下，出现了如此这般错误：
Collected errors:
 * check_data_file_clashes: Package dnsmasq-full wants to install file /etc/hotplug.d/ntp/25-dnsmasqsec
	But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /etc/init.d/dnsmasq
	But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /usr/lib/dnsmasq/dhcp-script.sh
	But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /usr/sbin/dnsmasq
	But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /usr/share/acl.d/dnsmasq_acl.json
	But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /usr/share/dnsmasq/dhcpbogushostname.conf
	But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /usr/share/dnsmasq/rfc6761.conf
	But that file is already provided by package  * dnsmasq
 * opkg_install_cmd: Cannot install package luci-app-openclash.

**Comment by Nepmonts** [comment]
和dnsmasq冲突了

**Comment by maddie** [comment]
```
opkg update
opkg remove dnsmasq
opkg install dnsmasq-full
```

Then try again.

**Comment by Geekiter** [comment]
> ```
> opkg update
> opkg remove dnsmasq
> opkg install dnsmasq-full
> ```
> 
> Then try again.

opkg remove dnsmasq && opkg install dnsmasq-full 安装和卸载一定要同时进行

```
opkg update
opkg remove dnsmasq && opkg install dnsmasq-full 
```

**Comment by Material3600** [comment]
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by AxisRay** [comment]
死循环了这……手动关闭吧

**Comment by Material3600** [comment]
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Material3600** [comment]
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
