### ISSUE TITLE
请教一下各位大神关于opclash代理vlan流量的问题

### ISSUE THREAD

**Issue by trombonist852** [vernesong/OpenClash#925]
家里单臂路由看iptv，设置的vlan85和vlan51，如果不开openclash的话iptv正常观看，开了openclash就看不了了，想请教一下各位大神，如何设置才能让openclash不代理vlan的流量呀？望各位大神给出个招，感激不尽！！

**Comment by vernesong** [comment]
iptv是DHCP校验的吧好像，DHCP没问题的话，你直接nat表和mangle表的openclash链return掉整个iptv所在的vlan的流量，模式选择redir

**Comment by trombonist852** [comment]
感谢大神回复！对的，是上海电信的iptv，建立vlan85和vlan51，iptv是dhcp拨号的，您说的模式选择我知道怎么操作，但是要如何return掉vlan流量，大神能否详细说说？有点没看懂…感激不尽！路由是x86软路由

vernesong <notifications@github.com>于2020年10月28日 周三下午8:59写道：

**Comment by vernesong** [comment]
iptables -t nat -I openclash -s 192.162.0.0/16 -j RETURN
iptables -t mangle -I openclash -s 192.162.0.0/16 -j RETURN

**Comment by trombonist852** [comment]
感谢大神！明白了！我现在试试！
vernesong <notifications@github.com>于2020年10月28日 周三下午10:18写道：

**Comment by trombonist852** [comment]
> iptables -t nat -I openclash -s 192.162.0.0/16 -j RETURN
> iptables -t mangle -I openclash -s 192.162.0.0/16 -j RETURN

反馈一下，大神，搞定了，实测不用写iptables，按您的思路，改成redir，然后把实验性：绕过中国大陆IP
这个启用就好了，看来如果要看iptv就不能用fake ip模式了...

**Comment by yyysuo** [comment]
> iptables -t nat -I openclash -s 192.162.0.0/16 -j RETURN iptables -t mangle -I openclash -s 192.162.0.0/16 -j RETURN

请教大佬，在fakeip+tun模式下，应该怎么处理呢？下面的这2条命令，只有第2条能添加上。
iptables -t nat -I openclash -s 239.253.0.0/16 -j RETURN
iptables -t mangle -I openclash -s 239.253.0.0/16 -j RETURN
