### ISSUE TITLE
cipher not supported 请教下，这个问题怎么解决

### ISSUE THREAD

**Issue by icucuio** [vernesong/OpenClash#929]
time="2020-10-28T22:27:27+08:00" level=fatal msg="Parse config error: proxy 1: ssr 0.000.rip:20050 initialize cipher error: cipher not supported"
新的配置文件，启动不了，就是这个错误。不知道如何处理？

**Comment by vernesong** [comment]
从下面选一个加密方式更换
#aes-128-cfb aes-192-cfb    aes-256-cfb
#aes-128-ctr aes-192-ctr    aes-256-ctr
#rc4-md5     chacha20-ietf  xchacha20

**Comment by chenliusuo** [comment]
cipher: 2022-blake3-aes-256-gcm，这样的加密方式目前openclash支持么

**Comment by muyuuuu** [comment]
> 从下面选一个加密方式更换
> #aes-128-cfb aes-192-cfb aes-256-cfb
> #aes-128-ctr aes-192-ctr aes-256-ctr
> #rc4-md5 chacha20-ietf xchacha20

24 年也遇到了这个问题，在哪修改呢....
