### ISSUE TITLE
请问大神 这个插件不支持斐讯k3 A1吗 （已经解决）

### ISSUE THREAD

**Issue by msfbao** [vernesong/OpenClash#933]
换了两个不同的固件 就是一直不能正常使用
也试着自己编辑了一个x86一个斐讯k3 A1版 用的是同一个模板的配置文件
 x86可以用 k3 a1死活就是不可以 是我那里没设置对吗

**Comment by OleStore** [comment]
支持，正常使用

**Comment by msfbao** [comment]
> 支持，正常使用

大神可以教 我怎么设置吗

**Comment by msfbao** [comment]
opkg install luci
opkg install luci-base
opkg install iptables
opkg install dnsmasq-full
opkg install coreutils
opkg install coreutils-nohup
opkg install bash
opkg install curl
opkg install jsonfilter
opkg install ca-certificates
opkg install ipset
opkg install ip-full
opkg install iptables-mod-tproxy
opkg install kmod-tun
opkg install luci-compat

安装这些依赖时出现 网络不通的情况也不知是怎么回事

**Comment by msfbao** [comment]
我恢复出厂设置后 查了下软件包 上面的插件都有发装 现在是把路由当旁路由用 不知是这样的原因才不可以正常使用还是我的操作有问题 
处理器内核我选arm7
不知是什么原因 大神可以出个通俗易懂的教程出来吗

**Comment by msfbao** [comment]
我是用k3网络接口lan接主路由的lan口的

**Comment by OleStore** [comment]
1.opkg update
2.opkg install luci luci-base iptables dnsmasq-full coreutils coreutils-nohup bash curl jsonfilter ca-certificates ipset ip-full iptables-mod-tproxy iptables-mod-extra libcap libcap-bin kmod-tun luci-compat ip6tables-mod-nat
3. opkg install openclash.ipk

**Comment by msfbao** [comment]
> 1.opkg update
> 2.opkg install luci luci-base iptables dnsmasq-full coreutils coreutils-nohup bash curl jsonfilter ca-certificates ipset ip-full iptables-mod-tproxy iptables-mod-extra libcap libcap-bin kmod-tun luci-compat ip6tables-mod-nat
> 3. opkg install openclash.ipk

第二条命令 安装后系统就蹦了 我初始化了

**Comment by msfbao** [comment]
Collected errors:
 * remove_obsolesced_files: unlinking /etc/uci-defaults/luci-base failed: No such file or directory.
 * resolve_conffiles: Existing conffile /etc/config/luci is different from the conffile in the new package. The new conffile will be placed at /etc/config/luci-opkg.
 * resolve_conffiles: Existing conffile /etc/config/ucitrack is different from the conffile in the new package. The new conffile will be placed at /etc/config/ucitrack-opkg.
 * resolve_conffiles: Existing conffile /etc/config/dhcp is different from the conffile in the new package. The new conffile will be placed at /etc/config/dhcp-opkg.
 * resolve_conffiles: Existing conffile /etc/dnsmasq.conf is different from the conffile in the new package. The new conffile will be placed at /etc/dnsmasq.conf-opkg.
出现这样的提示

**Comment by msfbao** [comment]
第三代命令
root@OpenWrt:~# opkg install openclash.ipk
Collected errors:
 * wfopen: openclash.ipk: No such file or directory.
 * pkg_init_from_file: Failed to extract control file from openclash.ipk.
root@OpenWrt:~#

**Comment by OleStore** [comment]
> 第三代命令
> root@OpenWrt:~# opkg install openclash.ipk
> Collected errors:
> 
> * wfopen: openclash.ipk: No such file or directory.
> * pkg_init_from_file: Failed to extract control file from openclash.ipk.
>   root@OpenWrt:~#
下载这里的https://github.com/vernesong/OpenClash/releases ipk
我只是比喻

**Comment by msfbao** [comment]
2.opkg install luci luci-base iptables dnsmasq-full coreutils coreutils-nohup bash curl jsonfilter ca-certificates ipset ip-full iptables-mod-tproxy iptables-mod-extra libcap libcap-bin kmod-tun luci-compat ip6tables-mod-nat
这个命令执行完后 web界面就蹦了

**Comment by msfbao** [comment]
Configuring ip-full.
Configuring ipset.
Configuring liblucihttp.
Configuring liblucihttp-lua.
Configuring luci-base.
Configuring libnettle7.
Configuring libnfnetlink0.
Configuring libnetfilter-conntrack3.
Configuring dnsmasq-full.
Configuring curl.
Configuring luci.
Configuring libcap.
Configuring libcap-bin.
Configuring coreutils.
Configuring coreutils-nohup.
Configuring luci-compat.
Configuring ip6tables-mod-nat.
Collected errors:
 * remove_obsolesced_files: unlinking /etc/uci-defaults/luci-base failed: No such file or directory.
 * resolve_conffiles: Existing conffile /etc/config/luci is different from the conffile in the new package. The new conffile will be placed at /etc/config/luci-opkg.
 * resolve_conffiles: Existing conffile /etc/config/ucitrack is different from the conffile in the new package. The new conffile will be placed at /etc/config/ucitrack-opkg.
 * resolve_conffiles: Existing conffile /etc/config/dhcp is different from the conffile in the new package. The new conffile will be placed at /etc/config/dhcp-opkg.
 * resolve_conffiles: Existing conffile /etc/dnsmasq.conf is different from the conffile in the new package. The new conffile will be placed at /etc/dnsmasq.conf-opkg.
root@OpenWrt:~# Collected errors:
-ash: Collected: not found
root@OpenWrt:~#  * remove_obsolesced_files: unlinking /etc/uci-defaults/luci-base failed: No such file or directory.
-ash: *: not found
root@OpenWrt:~#  * resolve_conffiles: Existing conffile /etc/config/luci is different from the conffile in the new package. The new conffile will be placed at /etc
/config/luci-opkg.
-ash: *: not found
root@OpenWrt:~#  * resolve_conffiles: Existing conffile /etc/config/ucitrack is different from the conffile in the new package. The new conffile will be placed at
/etc/config/ucitrack-opkg.
-ash: *: not found
root@OpenWrt:~#  * resolve_conffiles: Existing conffile /etc/config/dhcp is different from the conffile in the new package. The new conffile will be placed at /etc
/config/dhcp-opkg.
-ash: *: not found
root@OpenWrt:~#  * resolve_conffiles: Existing conffile /etc/dnsmasq.conf is different from the conffile in the new package. The new conffile will be placed at /et
c/dnsmasq.conf-opkg.
-ash: *: not found
root@OpenWrt:~#
出现以上的这样的错误

**Comment by msfbao** [comment]
OpenClash 调试日志

生成时间: 2020-10-27 23:41:00
插件版本: v0.40.14-beta

```

#===================== 系统信息 =====================#
主机型号: Phicomm K3
固件版本: OpenWrt SNAPSHOT r2935-365348f6b
LuCI版本: git-20.256.12360-1a54222-1
内核版本: 5.4.72
处理器架构: arm_cortex-a9

#此项在使用Tun模式时应为ACCEPT
防火墙转发: REJECT

#此项有值时建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: 

#此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 

#===================== 依赖检查 =====================#
dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
jsonfilter: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
iptables-mod-tproxy: 已安装
iptables-mod-extra: 已安装
libcap: 已安装
libcap-bin: 已安装
kmod-tun(TUN模式): 已安装
luci-compat(Luci-19.07): 已安装

#===================== 内核检查 =====================#
运行状态: 未运行
已选择的架构: linux-armv7

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 
Tun内核文件: 不存在
Tun内核运行权限: 否

Game内核版本: 
Game内核文件: 不存在
Game内核运行权限: 否

Dev内核版本: 
Dev内核文件: 存在
Dev内核运行权限: 正常

#===================== 插件设置 =====================#
当前配置文件: /etc/openclash/config/config.yaml
运行模式: redir-host
默认代理模式: global
UDP流量转发: 启用
DNS劫持: 启用
自定义DNS: 停用
IPV6-DNS解析: 停用
禁用Dnsmasq缓存: 停用
自定义规则: 停用
仅允许内网: 停用
仅代理命中规则流量: 启用
绕过中国大陆IP: 停用

#启动异常时建议关闭此项后重试
保留配置: 停用
第三方规则: 停用

#===================== 配置文件 =====================#
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090

#===================== 防火墙设置 =====================#

#NAT chain

# Generated by iptables-save v1.8.4 on Tue Oct 27 23:41:02 2020
*nat
:PREROUTING ACCEPT [74013:29519718]
:INPUT ACCEPT [63679:22929935]
:OUTPUT ACCEPT [2615:216694]
:POSTROUTING ACCEPT [2615:216694]
:MINIUPNPD - [0:0]
:MINIUPNPD-POSTROUTING - [0:0]
:postrouting_lan_rule - [0:0]
:postrouting_rule - [0:0]
:postrouting_vpn_rule - [0:0]
:postrouting_wan_rule - [0:0]
:prerouting_lan_rule - [0:0]
:prerouting_rule - [0:0]
:prerouting_vpn_rule - [0:0]
:prerouting_wan_rule - [0:0]
:zone_lan_postrouting - [0:0]
:zone_lan_prerouting - [0:0]
:zone_vpn_postrouting - [0:0]
:zone_vpn_prerouting - [0:0]
:zone_wan_postrouting - [0:0]
:zone_wan_prerouting - [0:0]
-A PREROUTING -p udp -m udp --dport 53 -j REDIRECT --to-ports 53
-A PREROUTING -p tcp -m tcp --dport 53 -j REDIRECT --to-ports 53
-A PREROUTING -m comment --comment "!fw3: Custom prerouting rule chain" -j prerouting_rule
-A PREROUTING -i br-lan -m comment --comment "!fw3" -j zone_lan_prerouting
-A PREROUTING -i eth0.2 -m comment --comment "!fw3" -j zone_wan_prerouting
-A PREROUTING -i tun0 -m comment --comment "!fw3" -j zone_vpn_prerouting
-A POSTROUTING -m comment --comment "!fw3: Custom postrouting rule chain" -j postrouting_rule
-A POSTROUTING -o br-lan -m comment --comment "!fw3" -j zone_lan_postrouting
-A POSTROUTING -o eth0.2 -m comment --comment "!fw3" -j zone_wan_postrouting
-A POSTROUTING -o tun0 -m comment --comment "!fw3" -j zone_vpn_postrouting
-A zone_lan_postrouting -j MINIUPNPD-POSTROUTING
-A zone_lan_postrouting -m comment --comment "!fw3: Custom lan postrouting rule chain" -j postrouting_lan_rule
-A zone_lan_prerouting -j MINIUPNPD
-A zone_lan_prerouting -m comment --comment "!fw3: Custom lan prerouting rule chain" -j prerouting_lan_rule
-A zone_vpn_postrouting -m comment --comment "!fw3: Custom vpn postrouting rule chain" -j postrouting_vpn_rule
-A zone_vpn_postrouting -m comment --comment "!fw3" -j FULLCONENAT
-A zone_vpn_prerouting -m comment --comment "!fw3: Custom vpn prerouting rule chain" -j prerouting_vpn_rule
-A zone_vpn_prerouting -m comment --comment "!fw3" -j FULLCONENAT
-A zone_wan_postrouting -m comment --comment "!fw3: Custom wan postrouting rule chain" -j postrouting_wan_rule
-A zone_wan_postrouting -m comment --comment "!fw3" -j FULLCONENAT
-A zone_wan_prerouting -m comment --comment "!fw3: Custom wan prerouting rule chain" -j prerouting_wan_rule
-A zone_wan_prerouting -m comment --comment "!fw3" -j FULLCONENAT
COMMIT
# Completed on Tue Oct 27 23:41:02 2020

#Mangle chain

# Generated by iptables-save v1.8.4 on Tue Oct 27 23:41:02 2020
*mangle
:PREROUTING ACCEPT [995767:110101572]
:INPUT ACCEPT [985433:103511789]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [30045:5523550]
:POSTROUTING ACCEPT [30142:5536172]
:qos_Default - [0:0]
:qos_Default_ct - [0:0]
-A FORWARD -o eth0.2 -p tcp -m tcp --tcp-flags SYN,RST SYN -m comment --comment "!fw3: Zone wan MTU fixing" -j TCPMSS --clamp-mss-to-pmtu
-A qos_Default -j CONNMARK --restore-mark --nfmask 0xf --ctmask 0xf
-A qos_Default -m mark --mark 0x0/0xf -j qos_Default_ct
-A qos_Default -p udp -m mark --mark 0x0/0xf0 -m length --length 0:500 -j MARK --set-xmark 0x22/0xff
-A qos_Default -p icmp -j MARK --set-xmark 0x11/0xff
-A qos_Default -p tcp -m mark --mark 0x0/0xf0 -m tcp --sport 1024:65535 --dport 1024:65535 -j MARK --set-xmark 0x44/0xff
-A qos_Default -p udp -m mark --mark 0x0/0xf0 -m udp --sport 1024:65535 --dport 1024:65535 -j MARK --set-xmark 0x44/0xff
-A qos_Default -j CONNMARK --save-mark --nfmask 0xff --ctmask 0xff
-A qos_Default_ct -p tcp -m mark --mark 0x0/0xf -m tcp -m multiport --ports 22,53 -m comment --comment "ssh, dns" -j MARK --set-xmark 0x11/0xff
-A qos_Default_ct -p udp -m mark --mark 0x0/0xf -m udp -m multiport --ports 22,53 -m comment --comment "ssh, dns" -j MARK --set-xmark 0x11/0xff
-A qos_Default_ct -p tcp -m mark --mark 0x0/0xf -m tcp -m multiport --ports 20,21,25,80,110,443,993,995 -m comment --comment "ftp, smtp, http(s), imap" -j MARK --set-xmark 0x33/0xff
-A qos_Default_ct -p tcp -m mark --mark 0x0/0xf -m tcp -m multiport --ports 5190 -m comment --comment "AOL, iChat, ICQ" -j MARK --set-xmark 0x22/0xff
-A qos_Default_ct -p udp -m mark --mark 0x0/0xf -m udp -m multiport --ports 5190 -m comment --comment "AOL, iChat, ICQ" -j MARK --set-xmark 0x22/0xff
-A qos_Default_ct -j CONNMARK --save-mark --nfmask 0xff --ctmask 0xff
COMMIT
# Completed on Tue Oct 27 23:41:02 2020

#===================== 路由表状态 =====================#
#route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.100.10  0.0.0.0         UG    0      0        0 br-lan
192.168.100.0   0.0.0.0         255.255.255.0   U     0      0        0 br-lan
#ip route list
default via 192.168.100.10 dev br-lan proto static 
192.168.100.0/24 dev br-lan proto kernel scope link src 192.168.100.2 
#ip rule show
0:	from all lookup local
32766:	from all lookup main
32767:	from all lookup default

#===================== 端口占用状态 =====================#

#===================== 测试本机DNS查询 =====================#
Server:		127.0.0.1
Address:	127.0.0.1#53

Name:      www.baidu.com
www.baidu.com	canonical name = www.a.shifen.com
Name:      www.a.shifen.com
Address 1: 14.215.177.39
Address 2: 14.215.177.38
*** Can't find www.baidu.com: No answer

#===================== resolv.conf.d =====================#
# Interface lan
nameserver 192.168.100.10

#===================== 测试本机网络连接 =====================#
HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: private, no-cache, no-store, proxy-revalidate, no-transform
Connection: keep-alive
Content-Length: 277
Content-Type: text/html
Date: Fri, 30 Oct 2020 09:40:02 GMT
Etag: "575e1f72-115"
Last-Modified: Mon, 13 Jun 2016 02:50:26 GMT
Pragma: no-cache
Server: bfe/1.0.8.18


#===================== 测试本机网络下载 =====================#

#===================== 最近运行日志 =====================#
2020-10-27 18:10:46 Warning: OpenClash Now Disabled, Need Start From Luci Page, Exit...
2020-10-27 23:38:13 Error: Config Not Found
2020-10-27 23:38:42 OpenClash 【Dev】 Core Update Successful
2020-10-27 23:38:46 Nameserver Option Must Be Setted, Auto Completed
2020-10-27 23:38:46 Error: OpenClash Can Not Start, Try Use Raw Config Restart Again
2020-10-27 23:38:46 Error: Get DNS 'listen' Option Error, OpenClash Can Not Start With Raw Config File
2020-10-27 23:38:46 Error: Get DNS 'enhanced-mode' Option Error, OpenClash Can Not Start With Raw Config File
2020-10-27 23:38:46 Error: Get General 'redir-port' Option Error, OpenClash Can Not Start With Raw Config File

```

**Comment by msfbao** [comment]
副上调试日记 请大神指导

**Comment by msfbao** [comment]
路由器是用lan 接主路由的lan口当旁路由的情况下 得出的调试日记

**Comment by OleStore** [comment]
> 路由器是用lan 接主路由的lan口当旁路由的情况下 得出的调试日记

找人有偿远程帮你解决，看你搞半天了

**Comment by msfbao** [comment]
插件是没问题 应该是那里做错了

**Comment by msfbao** [comment]
有了搞定了 现在启动起来了

**Comment by OleStore** [comment]
> 有了搞定了 现在启动起来了

既然问题解决了，可以关掉了

**Comment by msfbao** [comment]
怎么关掉

**Comment by msfbao** [comment]
> > 有了搞定了 现在启动起来了
> 
> 既然问题解决了，可以关掉了

怎么关掉

**Comment by fan-gh** [comment]
> 有了搞定了 现在启动起来了

 @msfbao，您好。请问怎么解决的？我的K3也是启动不了，我编译成X86就可以运行起来。
