### ISSUE TITLE
配置文件yaml 编辑 能不能更友好一点？因为稍微一个空格都会导致错误，根本发现不了

### ISSUE THREAD

**Issue by icucuio** [vernesong/OpenClash#938]
发现在修改yaml文件的时候，发现一个空格，一个没有对齐，或者都不知道那里不对，就会导致修改后无法启动或者修改了和没有修改一样，
能不能友好一点，只要结构对，不要在乎多一个空格和少一个空格，或者对齐没有对齐。

**Comment by bingfoon** [comment]
> 发现在修改yaml文件的时候，发现一个空格，一个没有对齐，或者都不知道那里不对，就会导致修改后无法启动或者修改了和没有修改一样，
> 能不能友好一点，只要结构对，不要在乎多一个空格和少一个空格，或者对齐没有对齐。

使用合适的编辑器（例如：vscode），yaml文件本来就对格式要求严格。

**Comment by VergilGao** [comment]
用vscode装好yaml插件就行了。
yaml本身的语法就一点点，网上找个文章看一下就好了。

**Comment by icucuio** [comment]
> 用vscode装好yaml插件就行了。
> yaml本身的语法就一点点，网上找个文章看一下就好了。

我是再openclash中修改，不是再本地修改，我的意思是在openclash中修改时候能不能友好点。

**Comment by VergilGao** [comment]
> > 用vscode装好yaml插件就行了。
> > yaml本身的语法就一点点，网上找个文章看一下就好了。
> 
> 我是再openclash中修改，不是再本地修改，我的意思是在openclash中修改时候能不能友好点。

不管在哪修改，yaml的语法规则都是一样的啊……
你可以在本地编辑器写好了再粘贴到浏览器里。
