### ISSUE TITLE
ip.pc这个已经失效

### ISSUE THREAD

**Issue by thank243** [vernesong/OpenClash#94]
状态监控里的已失效，望更新。

**Comment by vernesong** [comment]
没问题呀

**Comment by thank243** [comment]
![image](https://user-images.githubusercontent.com/11692994/71254673-b6e02280-2366-11ea-8346-b44336ca4936.png)
奇怪了。。。我这一直403，但是直接用浏览器是可以打开的。

**Comment by langjun** [comment]
@vernesong 我这也是403

![image](https://user-images.githubusercontent.com/7370806/79973887-ec3e7d80-84ca-11ea-8599-854c0ecc0325.png)
