### ISSUE TITLE
FackIP混合模式下 tun 内核无法启动

### ISSUE THREAD

**Issue by HashimotoSakura** [vernesong/OpenClash#943]
FackIP混合模式下 tun 内核无法启动，内核版本：2020.10.29.g5e54f48
日志
goroutine 89 [running]:
runtime/internal/atomic.lockAndCheck(...)
	runtime/internal/atomic/atomic_mipsx.go:40
runtime/internal/atomic.Xadd64(0x1d60074, 0x1be, 0x0, 0x8000, 0x1be)
	runtime/internal/atomic/atomic_mipsx.go:57 +0x20
github.com/Dreamacro/clash/tunnel.(*tcpTracker).Write(0x1d420a0, 0x1d68000, 0x1be, 0x8000, 0x1be, 0x0, 0x0)
	github.com/Dreamacro/clash/tunnel/tracker.go:50 +0xc8
io.copyBuffer(0x6fb1ac30, 0x1d420a0, 0x6fb1ac48, 0x225d0e0, 0x1d68000, 0x5000, 0x8000, 0x779980, 0x7e35c0, 0x73b800, ...)
	io/io.go:411 +0x204
io.CopyBuffer(0x6fb1ac30, 0x1d420a0, 0x6fb1ac48, 0x225d0e0, 0x1d68000, 0x5000, 0x8000, 0x7e35e4, 0x1b6dc, 0xc9f01c, ...)
	io/io.go:382 +0x7c
github.com/Dreamacro/clash/tunnel.relay(0x6fb1ac00, 0x225d0e0, 0x6fb1abd0, 0x1d420a0)
	github.com/Dreamacro/clash/tunnel/connection.go:147 +0x15c
github.com/Dreamacro/clash/tunnel.handleSocket(...)
	github.com/Dreamacro/clash/tunnel/connection.go:131
github.com/Dreamacro/clash/tunnel.handleTCPConn(0x902cc0, 0x225d0e0)
	github.com/Dreamacro/clash/tunnel/tunnel.go:350 +0x59c
created by github.com/Dreamacro/clash/tunnel.process
	github.com/Dreamacro/clash/tunnel/tunnel.go:134 +0xd8

**Comment by Orokapei** [comment]
是不是用了proxy-providers，我用proxy-providers就会这样，用不含proxy-providers的配置文件可以启动= =（终于看到一样启动错误的人了）
