### ISSUE TITLE
错误：Capsh异常，请尝试重新安装依赖【libcap】和相应的Capsh库，终止启动...

### ISSUE THREAD

**Issue by liaobadadi** [vernesong/OpenClash#945]
错误：Capsh异常，请尝试重新安装依赖【libcap】和相应的Capsh库，终止启动...

libcap 已经安装，
相应的Capsh库 ，不太明白，如何安装？

**Comment by lifetyper** [comment]
libcap-bin没装

**Comment by liaobadadi** [comment]
**### Great Thanks! Boss!**

**Comment by liaobadadi** [comment]
@lifetyper   ### Great Thanks! Boss!

**Comment by liaobadadi** [comment]
配置文件不存在，您已设置订阅信息，准备开始下载...
安装了libcap-bin    @@@，但是下载订阅信息卡住了，不知道怎么回事，我手动下载配置文件倒是可以的。@lifetyper

**Comment by yhl452493373** [comment]
> 配置文件不存在，您已设置订阅信息，准备开始下载...
> 安装了libcap-bin @@@，但是下载订阅信息卡住了，不知道怎么回事，我手动下载配置文件倒是可以的。@lifetyper

curl降级一下。或者更新下要给叫wolfssl的还是啥的来着

**Comment by gsion** [comment]
简单说一下，无非就是， libcap 一开始低版本，然后你们直接安装了 openclash，处理的办法
按流程
1、先卸载 openclash
2、这里下载 libcap 和 libcap-bin https://openwrt.proxy.ustclug.org/snapshots/packages/x86_64/packages/
3、重启
4、再次安装 openclash 即可

**Comment by lkisme** [comment]
试了所有的方法，还是不行

**Comment by matthuo333** [comment]
curl -Ok https://downloads.openwrt.org/snapshots/packages/x86_64/packages/libcap-bin_2.43-1_x86_64.ipk
curl -Ok https://downloads.openwrt.org/snapshots/packages/x86_64/packages/libcap_2.43-1_x86_64.ipk
opkg remove libcap --force-depends
opkg install libcap_2.43-1_x86_64.ipk
opkg install libcap-bin_2.43-1_x86_64.ipk

按照这个仍然不行。
update 卡在下图：
![image](https://user-images.githubusercontent.com/55862904/103172625-afaff680-488f-11eb-8b43-c8ce92183e30.png)

**Comment by matthuo333** [comment]
step1: opkg update
step2: 移除  libcab
step3: 按装libcab libcab-bin
![image](https://user-images.githubusercontent.com/55862904/103173503-6a42f780-4896-11eb-9ffd-e5c4fdf84e01.png)

step4: (由于oc自动消失),手动安装

仍然提示cashsh异常，不能启动

**Comment by D0zingcat** [comment]
> step1: opkg update
> step2: 移除 libcab
> step3: 按装libcab libcab-bin
> ![image](https://user-images.githubusercontent.com/55862904/103173503-6a42f780-4896-11eb-9ffd-e5c4fdf84e01.png)
> 
> step4: (由于oc自动消失),手动安装
> 
> 仍然提示Capsh异常，不能启动

It works, thanks man.

**Comment by delicopper** [comment]
根本现在就没有libcap和libcap-bin可以下载的地方，打开以后只有这个
<img width="1218" alt="截屏2021-06-15 上午1 02 51" src="https://user-images.githubusercontent.com/20332804/121931473-4016c080-cd76-11eb-825b-988587a3e954.png">
