### ISSUE TITLE
允许自定义fake-ip段？

### ISSUE THREAD

**Issue by sagan** [vernesong/OpenClash#946]
目前似乎 fake-ip 段固定为 198.18.0.1/16。是否能在界面上增加一个设置项允许修改这个值？

应用场景是局域网里有多个网络设备跑 openclash, 终端设备可能动态切换网关为不同的 openclash 设备。为了避免切换网关导致已缓存的 fake-ip 失效而断网，需要对每个网络设备上openclash指定不同的fake-ip段（以及配置到其他网络设备上 openclash fake-ip 段的静态路由）。

**Comment by vernesong** [comment]
特殊需求建议自行注释脚本，屏蔽对此参数的复写
