### ISSUE TITLE
openclash启动错误：panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by shiyush-git** [vernesong/OpenClash#947]
#===================== 最近运行日志 =====================#
time="2020-11-02T02:36:34Z" level=info msg="Start initial compatible provider GlobalTV"
time="2020-11-02T02:36:34Z" level=info msg="Start initial compatible provider Proxy"
time="2020-11-02T02:36:34Z" level=info msg="Start initial compatible provider Domestic"
time="2020-11-02T02:36:34Z" level=info msg="Start initial compatible provider Others"
time="2020-11-02T02:36:34Z" level=info msg="Start initial compatible provider AsianTV"
time="2020-11-02T02:36:34Z" level=info msg="Start initial rule provider ChinaIP"
time="2020-11-02T02:36:34Z" level=info msg="Start initial rule provider Unbreak"
time="2020-11-02T02:36:34Z" level=info msg="Start initial rule provider Streaming"
time="2020-11-02T02:36:34Z" level=info msg="Start initial rule provider StreamingSE"
time="2020-11-02T02:36:34Z" level=info msg="Start initial rule provider Global"
time="2020-11-02T02:36:34Z" level=info msg="Start initial rule provider China"
time="2020-11-02T02:36:34Z" level=info msg="DNS server listening at: 0.0.0.0:7874"
2020-11-02 10:36:27 OpenClash Start Successful
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x11ff4]

goroutine 68 [running]:
github.com/Dreamacro/clash/tunnel.(*udpTracker).WriteTo(0x28220a0, 0x2848000, 0x4, 0x8000, 0x792688, 0x2824540, 0xffffff01, 0x1, 0x56a3ec)
	github.com/Dreamacro/clash/tunnel/tracker.go:105 +0xb0
github.com/Dreamacro/clash/tunnel.handleUDPToRemote(0x794b70, 0x2822030, 0x798b90, 0x28220a0, 0x2816000, 0x0, 0x0)
	github.com/Dreamacro/clash/tunnel/connection.go:102 +0xb4
github.com/Dreamacro/clash/tunnel.handleUDPConn.func1(0x25483c0)
	github.com/Dreamacro/clash/tunnel/tunnel.go:245 +0x9c
github.com/Dreamacro/clash/tunnel.handleUDPConn.func2(0x0, 0x28242a0, 0x2824260, 0x2814080, 0x16, 0x2816000, 0x2822030, 0x2814040, 0x11, 0x0, ...)
	github.com/Dreamacro/clash/tunnel/tunnel.go:301 +0x2dc
created by github.com/Dreamacro/clash/tunnel.handleUDPConn
	github.com/Dreamacro/clash/tunnel/tunnel.go:258 +0x21c

```

运行日志
	/usr/lib/lua/luci/dispatcher.lua:478: in function </usr/lib/lua/luci/dispatcher.lua:477>
	/usr/lib/lua/luci/dispatcher.lua:922: in function 'dispatch'
stack traceback:
/usr/lib/lua/luci/dispatcher.lua:922: attempt to index local 'page' (a nil value)

**Comment by zhuqichen0310** [comment]
same bug

**Comment by shiyush-git** [comment]
貌似新版的tun内核（clash_tun）有问题，切换到游戏模式后成功启动。

**Comment by zhuqichen0310** [comment]
> 貌似新版的tun内核（clash_tun）有问题，切换到游戏模式后成功启动。

感谢 退回上一个版本的tun能正常启动了

**Comment by hcym** [comment]
.15的可以用，我的正常使用一晚上tun混合模式
