### ISSUE TITLE
[BUG] 不支持解析 yaml 配置文件中的索引数组形式

### ISSUE THREAD

**Issue by betaxab** [vernesong/OpenClash#949]
目前的 OpenClash 不支持解析索引数组形式，这将导致 DNS 字段解析失败从而无法正常启动。

DNS 配置字段例如：

```
    nameserver: [119.29.29.29, 223.5.5.5]
    fallback: ['tls://1.0.0.1:853', 'https://dns.google/dns-query']
    fallback-filter: { geoip: true, ipcidr: [240.0.0.0/4] }
```

上述字段均无法正常解析。使用 `[]` 方括号完全符合 yaml 规范。

一堆 grep awk 看的头疼，我就不研究并提 PR 了，希望开发人员可以修一下。

当然可以试试使用 yq 这个开源程序来处理 yaml 文件，全靠 awk grep 写起来真麻烦。

https://github.com/mikefarah/yq

**Comment by vernesong** [comment]
暂时没有找到合适的库，yq体积太大
