### ISSUE TITLE
可以用dnsmasq代替dnsmasq-full编译吗

### ISSUE THREAD

**Issue by remi-nd** [vernesong/OpenClash#95]
我卸载dnsmasq后安装dnsmasq-full会出现
Error relocating /usr/sbin/dnsmasq: nettle_lookup_hash: symbol not found
之后DHCP服务就失效了，google查不到原因，可以用dnsmasq代替dnsmasq-full编译吗

**Comment by vernesong** [comment]
建议编译前选择dnsmasq-full，取消dnsmasq。
如果你硬要使用dnsmasq，可以自己改下openclash的makefile取消依赖，效果自行测试

**Comment by phantastar** [comment]
安装dnsmasq-full和卸载dnsmasq的命令需要并列在同一条命令中进行，就解决问题了。我就是这么弄的。
`opkg remove dnsmasq && opkg install dnsmasq-full`
[第4项，用dnsmasq-full替换dnsmasq](https://www.dianlujitao.com/2015/10/19/openwrt-chaos-calmer-15-05%E4%BD%BF%E7%94%A8mwan3%E5%8D%95%E7%BA%BF%E5%A4%9A%E6%8B%A8%E6%95%99%E7%A8%8B/?replytocom=17)
