### ISSUE TITLE
fallback / url-test 模式优缺点下，能不能考虑fallback模式加入 延迟时间超过500s 就考虑切换节点？

### ISSUE THREAD

**Issue by icucuio** [vernesong/OpenClash#950]
url-test 缺点是切换节点太频繁，根本没有必要
fallback缺点是太傻瓜，延迟都超过1000s以上，实际就是连不上了，还不切换
所以能不能考虑fallback模式 考虑下延迟，比如设定500s延迟以上就切换，就有了url-test的优点
或者进一步，可以让用户自己设置fallback延时多少，就切换，那样更好了。
![image](https://user-images.githubusercontent.com/69136587/97875143-eddbde80-1d54-11eb-9ffc-e4571acca571.png)

**Comment by vernesong** [comment]
https://lancellc.gitbook.io/clash/clash-config-file/proxy-groups/auto#tolerance

**Comment by icucuio** [comment]
> https://lancellc.gitbook.io/clash/clash-config-file/proxy-groups/auto#tolerance

谢谢你这么及时回复，那这个tolerance可以应用在fallback上吗？或者怎么组合一下，可以切换不那么频繁

**Comment by vernesong** [comment]
只能urltest，这个容忍值，新节点比旧节点快这么多才会切换

**Comment by icucuio** [comment]
> 只能urltest，这个容忍值，新节点比旧节点快这么多才会切换
非常感谢，这个tolerance是加还是减，因为延时越小越好，没有弄反吧？

能不能给我解释下load balance 的具体是怎么实现的，我观察的现象是load balance延迟比较高，网速也不高，唯一感觉到好用的地方就是都可以连上

**Comment by vernesong** [comment]
负载均衡只要你节点是通的就会分配链接过去，默认是同网站同节点，你想灵活一点可以在新版里指定轮询策略

**Comment by hcym** [comment]
新模板有这个轮询范例就好了，一直没有😂

**Comment by icucuio** [comment]
> 负载均衡只要你节点是通的就会分配链接过去，默认是同网站同节点，你想灵活一点可以在新版里指定轮询策略

哪里又文档说明，能发下或者给个例子看下吗？

**Comment by vernesong** [comment]
![Uploading image.png…]()

**Comment by icucuio** [comment]
这种轮询机制，主要解决的是什么样的问题？

**Comment by hcym** [comment]
感谢大佬指教，试试看看轮询疗效🥰

**Comment by vernesong** [comment]
> 这种轮询机制，主要解决的是什么样的问题？或者说场景

集群用好一点，ip变动不大

**Comment by about300** [comment]
> ![图像](https://user-images.githubusercontent.com/42875168/97992126-3959bf80-1e1d-11eb-84e4-d1c7ad045d04.png)

你好，我想问下 如果在模板 sub 本地转换的ini文件应该怎么写才能使用 round-robin， Merlin clash的本地转换的ini文件上，如果使用负载均衡 ![image](https://github.com/vernesong/OpenClash/assets/131267104/e2bc7692-6b09-4611-8ff8-eab1afc17862),，结果出来的yaml 是只有负载均衡-散列模式，没有出来负载均衡-轮询模式

**Comment by vernesong** [comment]
subc的实现，这边没办法

**Comment by Commy2020** [comment]
你好，我现在也遇到的相同的问题，就是这个负载均衡的模式，如果轮训的节点延迟较高，应该也是会负载过去的把；有没有方案可以实现故障的自动切换的，就是延迟太高或者不可用就切换到可用的节点

**Comment by Commy2020** [comment]
@icucuio 我也遇到了相同的问题，你的问题解决了吗
