### ISSUE TITLE
在fack ip模式下，dota2 无法连接服务器

### ISSUE THREAD

**Issue by jindx0713** [vernesong/OpenClash#951]
dota2国服能进去游戏，但是在匹配游戏的时候，几个节点服务器显示连接失败。
关闭openclash后游戏正常。
感觉应该是dns方面的问题，但是局域网开的东西太多了，看不到详细日志。

能否根据现象给出一个排查问题的方向？

还有一些网站也一样，关闭后就可以打开。

**Comment by vernesong** [comment]
用混合模式，确保规则没让游戏走代理

**Comment by jindx0713** [comment]
切换到混合模式，问题解决了。但是部分网站依旧打不开，使用高级dns也无法解决。
