### ISSUE TITLE
更新40.15，tun最新内核后，无法正常启动

### ISSUE THREAD

**Issue by iadao** [vernesong/OpenClash#952]
OpenClash 调试日志

生成时间: 2020-11-03 13:38:18
插件版本: v0.40.15-beta
隐私提示: 上传此日志前请注意检查、屏蔽公网IP、节点、密码等相关敏感信息

```

#===================== 系统信息 =====================#
主机型号: XiaoYu XY-C5
固件版本: OpenWrt SNAPSHOT r2919-c39177efc
LuCI版本: git-20.256.12360-1a54222-1
内核版本: 5.4.69
处理器架构: mipsel_24kc

#此项在使用Tun模式时应为ACCEPT
防火墙转发: ACCEPT

#此项有值时建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: 

#此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 

#===================== 依赖检查 =====================#
dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
jsonfilter: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
iptables-mod-tproxy: 已安装
iptables-mod-extra: 已安装
libcap: 已安装
libcap-bin: 已安装
kmod-tun(TUN模式): 已安装
luci-compat(Luci-19.07): 已安装

#===================== 内核检查 =====================#
运行状态: 未运行
已选择的架构: linux-mipsle-softfloat

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 2020.10.29.g5e54f48
Tun内核文件: 存在
Tun内核运行权限: 正常

Game内核版本: 
Game内核文件: 不存在
Game内核运行权限: 否

Dev内核版本: v1.2.0-14-g87e4d94
Dev内核文件: 存在
Dev内核运行权限: 正常

#===================== 插件设置 =====================#
当前配置文件: /etc/openclash/config/20201013.yaml
运行模式: fake-ip-mix
默认代理模式: rule
UDP流量转发: 停用
DNS劫持: 启用
自定义DNS: 启用
IPV6-DNS解析: 停用
禁用Dnsmasq缓存: 启用
自定义规则: 启用
仅允许内网: 停用
仅代理命中规则流量: 停用
绕过中国大陆IP: 停用

#启动异常时建议关闭此项后重试
保留配置: 停用
第三方规则: 停用

#===================== 自定义规则 一 =====================#
##- DOMAIN-SUFFIX,google.com,Proxy 匹配域名后缀(交由Proxy代理服务器组)
##- DOMAIN-KEYWORD,google,Proxy 匹配域名关键字(交由Proxy代理服务器组)
##- DOMAIN,google.com,Proxy 匹配域名(交由Proxy代理服务器组)
##- DOMAIN-SUFFIX,ad.com,REJECT 匹配域名后缀(拒绝)
##- IP-CIDR,127.0.0.0/8,DIRECT 匹配数据目标IP(直连)
##- SRC-IP-CIDR,192.168.1.201/32,DIRECT 匹配数据发起IP(直连)
##- DST-PORT,80,DIRECT 匹配数据目标端口(直连)
##- SRC-PORT,7777,DIRECT 匹配数据源端口(直连)

##排序在上的规则优先生效,如添加（去除规则前的#号）：
##IP段：192.168.1.2-192.168.1.200 直连
##- SRC-IP-CIDR,192.168.1.2/31,DIRECT
##- SRC-IP-CIDR,192.168.1.4/30,DIRECT
##- SRC-IP-CIDR,192.168.1.8/29,DIRECT
##- SRC-IP-CIDR,192.168.1.16/28,DIRECT
##- SRC-IP-CIDR,192.168.1.32/27,DIRECT
##- SRC-IP-CIDR,192.168.1.64/26,DIRECT
##- SRC-IP-CIDR,192.168.1.128/26,DIRECT
##- SRC-IP-CIDR,192.168.1.192/29,DIRECT
##- SRC-IP-CIDR,192.168.1.200/32,DIRECT

##IP段：192.168.1.202-192.168.1.255 直连
##- SRC-IP-CIDR,192.168.1.202/31,DIRECT
##- SRC-IP-CIDR,192.168.1.204/30,DIRECT
##- SRC-IP-CIDR,192.168.1.208/28,DIRECT
##- SRC-IP-CIDR,192.168.1.224/27,DIRECT

##此时IP为192.168.1.1和192.168.1.201的客户端流量走代理（策略），其余客户端不走代理
##因为Fake-IP模式下，IP地址为192.168.1.1的路由器自身流量可走代理（策略），所以需要排除
##在线IP段转CIDR地址：http://ip2cidr.com



#===================== 自定义规则 二 =====================#
##- DOMAIN-SUFFIX,google.com,Proxy 匹配域名后缀(交由Proxy代理服务器组)
##- DOMAIN-KEYWORD,google,Proxy 匹配域名关键字(交由Proxy代理服务器组)
##- DOMAIN,google.com,Proxy 匹配域名(交由Proxy代理服务器组)
##- DOMAIN-SUFFIX,ad.com,REJECT 匹配域名后缀(拒绝)
##- IP-CIDR,127.0.0.0/8,DIRECT 匹配数据目标IP(直连)
##- SRC-IP-CIDR,192.168.1.201/32,DIRECT 匹配数据发起IP(直连)
##- DST-PORT,80,DIRECT 匹配数据目标端口(直连)
##- SRC-PORT,7777,DIRECT 匹配数据源端口(直连)

#===================== 配置文件 =====================#
redir-port: 7892
interface-name: pppoe-wan
port: 7890
socks-port: 7891
ipv6: false
mode: rule
log-level: info
external-controller: 0.0.0.0:9090
allow-lan: true
bind-address: "*"
external-ui: "/usr/share/openclash/dashboard"
tun:
  enable: true
  stack: system
  dns-hijack:
    - tcp://8.8.8.8:53
    - tcp://8.8.4.4:53
dns:
  use-hosts: true
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  listen: 127.0.0.1:7874
  fake-ip-filter:
##Custom fake-ip-filter##
    - '*.lan'
    - 'time.windows.com'
    - 'time.nist.gov'
    - 'time.apple.com'
    - 'time.asia.apple.com'
    - '*.ntp.org.cn'
    - '*.openwrt.pool.ntp.org'
    - 'time1.cloud.tencent.com'
    - 'time.ustc.edu.cn'
    - 'pool.ntp.org'
    - 'ntp.ubuntu.com'
    - 'ntp.aliyun.com'
    - 'ntp1.aliyun.com'
    - 'ntp2.aliyun.com'
    - 'ntp3.aliyun.com'
    - 'ntp4.aliyun.com'
    - 'ntp5.aliyun.com'
    - 'ntp6.aliyun.com'
    - 'ntp7.aliyun.com'
    - 'time1.aliyun.com'
    - 'time2.aliyun.com'
    - 'time3.aliyun.com'
    - 'time4.aliyun.com'
    - 'time5.aliyun.com'
    - 'time6.aliyun.com'
    - 'time7.aliyun.com'
    - '*.time.edu.cn'
    - 'time1.apple.com'
    - 'time2.apple.com'
    - 'time3.apple.com'
    - 'time4.apple.com'
    - 'time5.apple.com'
    - 'time6.apple.com'
    - 'time7.apple.com'
    - 'time1.google.com'
    - 'time2.google.com'
    - 'time3.google.com'
    - 'time4.google.com'
    - 'music.163.com'
    - '*.music.163.com'
    - '*.126.net'
    - 'musicapi.taihe.com'
    - 'music.taihe.com'
    - 'songsearch.kugou.com'
    - 'trackercdn.kugou.com'
    - '*.kuwo.cn'
    - 'api-jooxtt.sanook.com'
    - 'api.joox.com'
    - 'joox.com'
    - 'y.qq.com'
    - '*.y.qq.com'
    - 'streamoc.music.tc.qq.com'
    - 'mobileoc.music.tc.qq.com'
    - 'isure.stream.qqmusic.qq.com'
    - 'dl.stream.qqmusic.qq.com'
    - 'aqqmusic.tc.qq.com'
    - 'amobile.music.tc.qq.com'
    - '*.xiami.com'
    - '*.music.migu.cn'
    - 'music.migu.cn'
    - '*.msftconnecttest.com'
    - '*.msftncsi.com'
    - 'localhost.ptlogin2.qq.com'
    - '*.*.*.srv.nintendo.net'
    - '*.*.stun.playstation.net'
    - 'xbox.*.*.microsoft.com'
    - '*.*.xboxlive.com'
    - 'proxy.golang.org'
##Custom fake-ip-filter END##
  nameserver:
##Custom DNS##
    - 114.114.114.114
    - 119.29.29.29
  fallback-filter:
    geoip: true
    ipcidr:
      - 0.0.0.0/8
      - 10.0.0.0/8
      - 100.64.0.0/10
      - 127.0.0.0/8
      - 169.254.0.0/16
      - 172.16.0.0/12
      - 192.0.0.0/24
      - 192.0.2.0/24
      - 192.88.99.0/24
      - 192.168.0.0/16
      - 198.18.0.0/15
      - 198.51.100.0/24
      - 203.0.113.0/24
      - 224.0.0.0/4
      - 240.0.0.0/4
      - 255.255.255.255/32

#===================== 防火墙设置 =====================#

#NAT chain

# Generated by iptables-save v1.8.4 on Tue Nov  3 13:38:21 2020
*nat
:PREROUTING ACCEPT [534:45976]
:INPUT ACCEPT [198:14254]
:OUTPUT ACCEPT [189:13697]
:POSTROUTING ACCEPT [10:626]
:CLOUD_MUSIC - [0:0]
:postrouting_lan_rule - [0:0]
:postrouting_rule - [0:0]
:postrouting_wan_rule - [0:0]
:prerouting_lan_rule - [0:0]
:prerouting_rule - [0:0]
:prerouting_wan_rule - [0:0]
:zone_lan_postrouting - [0:0]
:zone_lan_prerouting - [0:0]
:zone_wan_postrouting - [0:0]
:zone_wan_prerouting - [0:0]
-A PREROUTING -p tcp -m set --match-set music dst -j CLOUD_MUSIC
-A PREROUTING -p udp -m udp --dport 53 -j REDIRECT --to-ports 53
-A PREROUTING -p tcp -m tcp --dport 53 -j REDIRECT --to-ports 53
-A PREROUTING -m comment --comment "!fw3: Custom prerouting rule chain" -j prerouting_rule
-A PREROUTING -i br-lan -m comment --comment "!fw3" -j zone_lan_prerouting
-A PREROUTING -i pppoe-wan -m comment --comment "!fw3" -j zone_wan_prerouting
-A POSTROUTING -m comment --comment "!fw3: Custom postrouting rule chain" -j postrouting_rule
-A POSTROUTING -o br-lan -m comment --comment "!fw3" -j zone_lan_postrouting
-A POSTROUTING -o pppoe-wan -m comment --comment "!fw3" -j zone_wan_postrouting
-A CLOUD_MUSIC -d 0.0.0.0/8 -j RETURN
-A CLOUD_MUSIC -d 10.0.0.0/8 -j RETURN
-A CLOUD_MUSIC -d 127.0.0.0/8 -j RETURN
-A CLOUD_MUSIC -d 169.254.0.0/16 -j RETURN
-A CLOUD_MUSIC -d 172.16.0.0/12 -j RETURN
-A CLOUD_MUSIC -d 192.168.0.0/16 -j RETURN
-A CLOUD_MUSIC -d 224.0.0.0/4 -j RETURN
-A CLOUD_MUSIC -d 240.0.0.0/4 -j RETURN
-A CLOUD_MUSIC -p tcp -m set ! --match-set music_http src -m tcp --dport 80 -j REDIRECT --to-ports 5200
-A CLOUD_MUSIC -p tcp -m set ! --match-set music_https src -m tcp --dport 443 -j REDIRECT --to-ports 5201
-A zone_lan_postrouting -m comment --comment "!fw3: Custom lan postrouting rule chain" -j postrouting_lan_rule
-A zone_lan_prerouting -m comment --comment "!fw3: Custom lan prerouting rule chain" -j prerouting_lan_rule
-A zone_wan_postrouting -m comment --comment "!fw3: Custom wan postrouting rule chain" -j postrouting_wan_rule
-A zone_wan_postrouting -m comment --comment "!fw3" -j FULLCONENAT
-A zone_wan_prerouting -m comment --comment "!fw3: Custom wan prerouting rule chain" -j prerouting_wan_rule
-A zone_wan_prerouting -m comment --comment "!fw3" -j FULLCONENAT
COMMIT
# Completed on Tue Nov  3 13:38:21 2020

#Mangle chain

# Generated by iptables-save v1.8.4 on Tue Nov  3 13:38:21 2020
*mangle
:PREROUTING ACCEPT [5356:489943]
:INPUT ACCEPT [2726:303386]
:FORWARD ACCEPT [2560:168898]
:OUTPUT ACCEPT [2736:767282]
:POSTROUTING ACCEPT [5254:933993]
-A FORWARD -o pppoe-wan -p tcp -m tcp --tcp-flags SYN,RST SYN -m comment --comment "!fw3: Zone wan MTU fixing" -j TCPMSS --clamp-mss-to-pmtu
COMMIT
# Completed on Tue Nov  3 13:38:21 2020

#===================== 路由表状态 =====================#
#route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         1.94.160.1      0.0.0.0         UG    0      0        0 pppoe-wan
1.94.160.1      0.0.0.0         255.255.255.255 UH    0      0        0 pppoe-wan
192.168.10.0    0.0.0.0         255.255.255.0   U     0      0        0 br-lan
#ip route list
default via 1.94.160.1 dev pppoe-wan proto static 
1.94.160.1 dev pppoe-wan proto kernel scope link src 1.94.190.55 
192.168.10.0/24 dev br-lan proto kernel scope link src 192.168.10.222 
#ip rule show
0:	from all lookup local
32765:	from all fwmark 0x162 lookup 354
32766:	from all lookup main
32767:	from all lookup default

#===================== Tun设备状态 =====================#

#===================== 端口占用状态 =====================#

#===================== 测试本机DNS查询 =====================#
Server:		127.0.0.1
Address:	127.0.0.1#53

Name:      www.baidu.com
www.baidu.com	canonical name = www.a.shifen.com
Name:      www.a.shifen.com
Address 1: 182.61.200.7
Address 2: 182.61.200.6
*** Can't find www.baidu.com: No answer

#===================== resolv.conf.d =====================#
# Interface lan
nameserver 114.114.114.114
nameserver 8.8.8.8
# Interface wan
nameserver 219.239.26.42
nameserver 124.207.160.106

#===================== 测试本机网络连接 =====================#
HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: private, no-cache, no-store, proxy-revalidate, no-transform
Connection: keep-alive
Content-Length: 277
Content-Type: text/html
Date: Tue, 03 Nov 2020 05:38:22 GMT
Etag: "575e1f60-115"
Last-Modified: Mon, 13 Jun 2016 02:50:08 GMT
Pragma: no-cache
Server: bfe/1.0.8.18


#===================== 测试本机网络下载 =====================#

#===================== 最近运行日志 =====================#

```

**Comment by vernesong** [comment]
日志空白，你再补充一下

**Comment by iadao** [comment]
> 日志空白，你再补充一下

	github.com/Dreamacro/clash/tunnel/tunnel.go:134 +0xd8
created by github.com/Dreamacro/clash/tunnel.process
	github.com/Dreamacro/clash/tunnel/tunnel.go:350 +0x59c
github.com/Dreamacro/clash/tunnel.handleTCPConn(0x902cc0, 0x10fa4c0)
	github.com/Dreamacro/clash/tunnel/connection.go:131
github.com/Dreamacro/clash/tunnel.handleSocket(...)
	github.com/Dreamacro/clash/tunnel/connection.go:147 +0x15c
github.com/Dreamacro/clash/tunnel.relay(0x6fbeb7a0, 0x10fa4c0, 0x6fbeb770, 0x1234b80)
	io/io.go:382 +0x7c
io.CopyBuffer(0x6fbeb7d0, 0x1234b80, 0x6fbeb7e8, 0x10fa4c0, 0x1496000, 0x5000, 0x8000, 0x7e35e4, 0x1b6dc, 0xc9f01c, ...)
	io/io.go:411 +0x204
io.copyBuffer(0x6fbeb7d0, 0x1234b80, 0x6fbeb7e8, 0x10fa4c0, 0x1496000, 0x5000, 0x8000, 0x779980, 0x7e35c0, 0x73b800, ...)
	github.com/Dreamacro/clash/tunnel/tracker.go:50 +0xc8
github.com/Dreamacro/clash/tunnel.(*tcpTracker).Write(0x1234b80, 0x1496000, 0x2ee, 0x8000, 0x2ee, 0x0, 0x0)
	runtime/internal/atomic/atomic_mipsx.go:57 +0x20
runtime/internal/atomic.Xadd64(0x12ac194, 0x2ee, 0x0, 0x8000, 0x2ee)
	runtime/internal/atomic/atomic_mipsx.go:40
runtime/internal/atomic.lockAndCheck(...)
goroutine 377 [running]:

[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11914]
panic: runtime error: invalid memory address or nil pointer dereference
2020-11-03 17:22:11 level=info msg="[TCP] 192.168.10.159:53304 --> 211.99.98.105 match RuleSet(ChinaIP) using Final[香港 特选01 华南]"
2020-11-03 17:22:08 level=info msg="Redir proxy listening at: :7892"
2020-11-03 17:22:08 level=info msg="RESTful API listening at: 0.0.0.0:9090"
2020-11-03 17:22:08 level=info msg="SOCKS proxy listening at: :7891"
2020-11-03 17:22:08 level=info msg="HTTP proxy listening at: :7890"
2020-11-03 17:22:08 level=info msg="DNS server listening at: 127.0.0.1:7874"
2020-11-03 17:22:08 level=info msg="Start initial rule provider StreamingSE"
2020-11-03 17:22:07 level=info msg="Start initial rule provider Streaming"
2020-11-03 17:22:07 level=info msg="Start initial rule provider Unbreak"
2020-11-03 17:22:07 level=info msg="Start initial rule provider ChinaIP"
2020-11-03 17:22:07 level=info msg="Start initial rule provider China"
2020-11-03 17:22:06 level=info msg="Start initial rule provider Global"
2020-11-03 17:22:06 level=info msg="Start initial compatible provider HKMTMedia"
2020-11-03 17:22:06 level=info msg="Start initial compatible provider Hijacking"
2020-11-03 17:22:06 level=info msg="Start initial compatible provider Proxies"
2020-11-03 17:22:06 level=info msg="Start initial compatible provider Auto"
2020-11-03 17:22:06 level=info msg="Start initial compatible provider GlobalMedia"
2020-11-03 17:22:06 level=info msg="Start initial compatible provider Advertising"
2020-11-03 17:22:06 level=info msg="Start initial compatible provider Final"
2020-11-03 17:22:06 level=info msg="Start initial compatible provider Apple"
2020-11-03 17:22:06 Watchdog: Clash Core Problem, Restart.
2020-11-03 17:21:07 OpenClash Start Successful
	github.com/Dreamacro/clash/tunnel/tunnel.go:134 +0xd8
created by github.com/Dreamacro/clash/tunnel.process
	github.com/Dreamacro/clash/tunnel/tunnel.go:350 +0x59c
github.com/Dreamacro/clash/tunnel.handleTCPConn(0x902cc0, 0x10d8210)
	github.com/Dreamacro/clash/tunnel/connection.go:131
github.com/Dreamacro/clash/tunnel.handleSocket(...)
	github.com/Dreamacro/clash/tunnel/connection.go:147 +0x15c
github.com/Dreamacro/clash/tunnel.relay(0x6fccae18, 0x10d8210, 0x6fccade8, 0x10d82e0)
	io/io.go:382 +0x7c
io.CopyBuffer(0x6fccae48, 0x10d82e0, 0x6fccae60, 0x10d8210, 0x1480000, 0x5000, 0x8000, 0x7e35e4, 0x1b6dc, 0xc9f01c, ...)
	io/io.go:411 +0x204
io.copyBuffer(0x6fccae48, 0x10d82e0, 0x6fccae60, 0x10d8210, 0x1480000, 0x5000, 0x8000, 0x779980, 0x7e35c0, 0x73b800, ...)
	github.com/Dreamacro/clash/tunnel/tracker.go:50 +0xc8
github.com/Dreamacro/clash/tunnel.(*tcpTracker).Write(0x10d82e0, 0x1480000, 0x301, 0x8000, 0x301, 0x0, 0x0)
	runtime/internal/atomic/atomic_mipsx.go:57 +0x20
runtime/internal/atomic.Xadd64(0x11920d4, 0x301, 0x0, 0x8000, 0x301)
	runtime/internal/atomic/atomic_mipsx.go:40
runtime/internal/atomic.lockAndCheck(...)
goroutine 339 [running]:

[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11914]
panic: runtime error: invalid memory address or nil pointer dereference
	github.com/Dreamacro/clash/tunnel/connection.go:138 +0x8c
created by github.com/Dreamacro/clash/tunnel.relay
	github.com/Dreamacro/clash/tunnel/connection.go:140 +0x100
github.com/Dreamacro/clash/tunnel.relay.func1(0x6fccae18, 0x10d8210, 0x6fccade8, 0x10d82e0, 0x102c540)
	io/io.go:382 +0x7c
io.CopyBuffer(0x6fb3ddf0, 0x10d8210, 0x6fb3de08, 0x10d82e0, 0x13ea000, 0x5000, 0x8000, 0x105f180, 0x6ad57c, 0x105f180, ...)
	io/io.go:409 +0x108
io.copyBuffer(0x6fb3ddf0, 0x10d8210, 0x6fb3de08, 0x10d82e0, 0x13ea000, 0x5000, 0x8000, 0x779980, 0x7ed480, 0x73b800, ...)
	github.com/Dreamacro/clash/tunnel/tracker.go:42 +0xc8
github.com/Dreamacro/clash/tunnel.(*tcpTracker).Read(0x10d82e0, 0x13ea000, 0x5000, 0x8000, 0x0, 0x1014000, 0x6fb3de08)
	runtime/internal/atomic/atomic_mipsx.go:57 +0x20
runtime/internal/atomic.Xadd64(0x11920dc, 0x0, 0x0, 0x8000, 0x0)
	runtime/internal/atomic/atomic_mipsx.go:40
runtime/internal/atomic.lockAndCheck(...)
goroutine 347 [running]:

[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11914]
panic: runtime error: invalid memory address or nil pointer dereference
2020-11-03 17:21:40 level=info msg="[TCP] 192.168.10.124:53758 --> 121.51.118.79 match RuleSet(ChinaIP) using Final[香港 特选01 华南]"
2020-11-03 17:21:33 level=info msg="RESTful API listening at: 0.0.0.0:9090"
2020-11-03 17:21:33 level=info msg="Redir proxy listening at: :7892"
2020-11-03 17:21:33 level=info msg="SOCKS proxy listening at: :7891"
2020-11-03 17:21:33 level=info msg="HTTP proxy listening at: :7890"
2020-11-03 17:21:33 level=info msg="DNS server listening at: 127.0.0.1:7874"
2020-11-03 17:21:33 level=info msg="Start initial rule provider China"
2020-11-03 17:21:33 level=info msg="Start initial rule provider Global"
2020-11-03 17:21:33 level=info msg="Start initial rule provider StreamingSE"
2020-11-03 17:21:33 level=info msg="Start initial rule provider Streaming"
2020-11-03 17:21:33 level=info msg="Start initial rule provider Unbreak"
2020-11-03 17:21:32 level=info msg="Start initial rule provider ChinaIP"
2020-11-03 17:21:32 level=info msg="Start initial compatible provider GlobalMedia"
2020-11-03 17:21:32 level=info msg="Start initial compatible provider Advertising"
2020-11-03 17:21:32 level=info msg="Start initial compatible provider Hijacking"
2020-11-03 17:21:32 level=info msg="Start initial compatible provider Apple"
2020-11-03 17:21:32 level=info msg="Start initial compatible provider Proxies"
2020-11-03 17:21:32 level=info msg="Start initial compatible provider Auto"
2020-11-03 17:21:32 level=info msg="Start initial compatible provider HKMTMedia"
2020-11-03 17:21:32 level=info msg="Start initial compatible provider Final"

**Comment by vernesong** [comment]
内核先回退版本吧，等修复

**Comment by de-conf** [comment]
> 内核先回退版本吧，等修复

tun内核历史下载地址找不到啊！

**Comment by shiyush-git** [comment]
历史版本要翻墙才能下载

**Comment by de-conf** [comment]
> 历史版本要翻墙才能下载

是没有下载地址的问题
https://github.com/vernesong/OpenClash/releases/tag/TUN-Premium
这个tag单独出来导致只能下最新版本的tun内核，旧的内核下载地址都没有！
这不是翻不翻墙的问题
