### ISSUE TITLE
Redir-Host(TUN)模式下，防火墙端口转发规则部分失效

### ISSUE THREAD

**Issue by JC-SYSU** [vernesong/OpenClash#954]
开启Redir-Host(TUN)模式后，防火墙的端口转发规则中，只有转发到路由器本身的规则可以正常生效，但转发到内网其他设备（比如NAS）的规则则会失效，从外网无法正常访问，关闭OpenClash后恢复，改用Redir-Host模式后亦可恢复。

**Comment by JC-SYSU** [comment]
另，采用Redir-Host(TUN 混合)模式，也是正常的

**Comment by JC-SYSU** [comment]
[Redir-Host模式下的防火墙.txt](https://github.com/vernesong/OpenClash/files/5485293/Redir-Host.txt)
[Redir-Host(TUN)模式下的防火墙.txt](https://github.com/vernesong/OpenClash/files/5485295/Redir-Host.TUN.txt)

**Comment by pikachullk** [comment]
同样的问题也存在于fake-ip和fake-ip混合模式
规则用的是dler的...
从tun核心从10.24版本开始失效

**Comment by pikachullk** [comment]
我还测试了一下...ping的话能ping通局域网设备...好像就是无法访问
