### ISSUE TITLE
*仅代理命中规则流量 功能问题 版本0.39.2-bate

### ISSUE THREAD

**Issue by gitelia** [vernesong/OpenClash#957]
在打开这个选项后，所有的规则全都走直连了。
![image](https://user-images.githubusercontent.com/44855037/98101888-ce1bf600-1ecd-11eb-84f2-f4d86e4b8c2c.png)
![image](https://user-images.githubusercontent.com/44855037/98102052-0cb1b080-1ece-11eb-8a57-5ed5bec3311f.png)

关闭后就正常。

**Comment by vernesong** [comment]
脚本处理问题吧，旧版的话不清楚具体原因

**Comment by gitelia** [comment]
> 脚本处理问题吧，旧版的话明显具体原因

这个bug 是在一个订阅下有ss 和V2ray 节点切换的时候出现的（ss切换到V2节点）  再切回ss  bug不会消失 包括重启固件
