### ISSUE TITLE
网站访问检查里facebook失效

### ISSUE THREAD

**Issue by lifetyper** [vernesong/OpenClash#96]
Sukka 的ip.skk.moe里好像已经没有facebook检查这一项了，openclash里还有，结果永远都显示facebook连接失败，麻烦更新一下，谢谢！

**Comment by vernesong** [comment]
连接失败就是连接不上，你实际也上不去，跟检测代码没关系

**Comment by lifetyper** [comment]
问题是我上得去facebook啊

--

**Comment by lifetyper** [comment]
似乎和浏览器相关，safari正常，firefox显示无法访问，但firefox可以正常访问facebook.com/favicon.ico

**Comment by lifetyper** [comment]
不知道是我firefox哪个插件或者设置的冲突，我重置了firefox后是正常的，但还是很奇怪为什么只影响了facebook的判断。
