### ISSUE TITLE
最新版本 TUN 内核无法启动

### ISSUE THREAD

**Issue by leschans** [vernesong/OpenClash#962]
请留意。

**Comment by hcym** [comment]
我的一直没问题，无论.14还是.15都正常运行tun增强模式，不行就用.7版本吧，性能几乎没有差异。这个clash确实有点复杂多变。

**Comment by de-conf** [comment]
> 我的一直没问题，无论.14还是.15都正常运行tun增强模式，不行就用.7版本吧，性能几乎没有差异。这个clash确实有点复杂多变。

求旧版本下载地址

**Comment by leschans** [comment]
> 我的一直没问题，无论.14还是.15都正常运行tun增强模式，不行就用.7版本吧，性能几乎没有差异。这个clash确实有点复杂多变。

同求

**Comment by hcym** [comment]
luci就是发布页啊，新的旧的都有。旧内核不知道了，但是我用.7的luci和最新版的内核正常启动，页面控制面板似乎比新的.15好使😂

**Comment by leschans** [comment]
> luci就是发布页啊，新的旧的都有。旧内核不知道了，但是我用.7的luci和最新版的内核正常启动，页面控制面板似乎比新的.15好使😂

log显示是TUN的问题，我试试7版本，谢谢提供信息。

**Comment by leschans** [comment]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11914]

goroutine 49 [running]:
runtime/internal/atomic.lockAndCheck(...)
	runtime/internal/atomic/atomic_mipsx.go:40
runtime/internal/atomic.Xadd64(0x1590254, 0x245, 0x0, 0x8000, 0x245)
	runtime/internal/atomic/atomic_mipsx.go:57 +0x20
github.com/Dreamacro/clash/tunnel.(*tcpTracker).Write(0x16027b0, 0x1662000, 0x245, 0x8000, 0x245, 0x0, 0x0)
	github.com/Dreamacro/clash/tunnel/tracker.go:50 +0xc8
io.copyBuffer(0x6f91b270, 0x16027b0, 0x6f91b288, 0x1682020, 0x1662000, 0x5000, 0x8000, 0x779980, 0x7e35c0, 0x73b800, ...)
	io/io.go:411 +0x204
io.CopyBuffer(0x6f91b270, 0x16027b0, 0x6f91b288, 0x1682020, 0x1662000, 0x5000, 0x8000, 0x7e35e4, 0x1b6dc, 0xc9f01c, ...)
	io/io.go:382 +0x7c
github.com/Dreamacro/clash/tunnel.relay(0x6f91b240, 0x1682020, 0x6f91b210, 0x16027b0)
	github.com/Dreamacro/clash/tunnel/connection.go:147 +0x15c
github.com/Dreamacro/clash/tunnel.handleSocket(...)
	github.com/Dreamacro/clash/tunnel/connection.go:131
github.com/Dreamacro/clash/tunnel.handleTCPConn(0x902cc0, 0x1682020)
	github.com/Dreamacro/clash/tunnel/tunnel.go:350 +0x59c
created by github.com/Dreamacro/clash/tunnel.process
	github.com/Dreamacro/clash/tunnel/tunnel.go:134 +0xd8
2020-11-07 17:49:43 OpenClash Can Not Start, Please Check The Error Info And Try Again

**Comment by leschans** [comment]
在7版本，若不启用第三方规则，则不启用 TUN 内核，此时调用 Dev 内核正常启用 OpenClash。先前版本始终使用第三方规则则未发现问题。

**Comment by leschans** [comment]
> luci就是发布页啊，新的旧的都有。旧内核不知道了，但是我用.7的luci和最新版的内核正常启动，页面控制面板似乎比新的.15好使😂

请问你有使用TUN内核吗？是否启用了第三方规则？

**Comment by hcym** [comment]
没有用什么规则，就是用模板照猫画虎一下，加几个广告规则，力求简单，clash操作过程太复杂了，就怕出差子

**Comment by de-conf** [comment]
> luci就是发布页啊，新的旧的都有。旧内核不知道了，但是我用.7的luci和最新版的内核正常启动，页面控制面板似乎比新的.15好使😂
下述界面只提供luci-app-clash下载，不提供clash-tun的下载 历史版本里也只有clash-dev的内核，
并没有tun的内核下载地址，而且貌似我看见TUN内核好像是闭源免费的

https://github.com/vernesong/OpenClash/releases

**Comment by FunkySamuel37** [comment]
我的卡在加载provider了，更新不了lhie1的规则文件
```
time="2020-11-07T21:04:44+08:00" level=fatal msg="Parse config error: initial rule provider Pandora error: Get \"https://git.dler.io/lhie1/Rules/master/Clash/Provider/Media/Pandora.yaml\": dial tcp4 203.86.232.164:443: connect: connection refused"
```

**Comment by leschans** [comment]
> > luci就是发布页啊，新的旧的都有。旧内核不知道了，但是我用.7的luci和最新版的内核正常启动，页面控制面板似乎比新的.15好使😂
> 
> ```
> 
> 下述界面只提供luci-app-clash下载，不提供clash-tun的下载 历史版本里也只有clash-dev的内核，
> 
> 并没有tun的内核下载地址，而且貌似我看见TUN内核好像是闭源免费的
> 
> 
> 
> https://github.com/vernesong/OpenClash/releases
> 
> ```

TUN是一个tag来的，目前只看到最新版本10.29的TUN，如果我配置都正确的话，这个版本可能有错误

**Comment by bingfoon** [comment]
不嫌麻烦的话，使用自定义模版，这样就不会调用tun内核。
首先找一个你用着习惯的模版，托管到自己的gist上，把你想用的第三方碎片规则的地址加到模版文件里就行了。

**Comment by leschans** [comment]
> 不嫌麻烦的话，使用自定义模版，这样就不会调用tun内核。
> 
> 首先找一个你用着习惯的模版，托管到自己的gist上，把你想用的第三方碎片规则的地址加到模版文件里就行了。

棒
