### ISSUE TITLE
AppleTV Netflix app总是被检测到ip Code 113

### ISSUE THREAD

**Issue by FrankieLEMON** [vernesong/OpenClash#963]
Apple TV, Netflix APP总是跳出Code113。。被检测到IP..局域网其他环境下iphone Mac 都能正常登入Netflix并且观看，是因为Apple TV接入的规则没有被OpenClash检测到么？

**Comment by jakeslee** [comment]
这是因为有部分规则遗漏导致的，建议使用  SRC-IP-CIDR 规则将 Apple TV 直接设置成 Netflix 对应的策略组，Apple TV 所有流量都会被代理。

**Comment by FrankieLEMON** [comment]
> 这是因为有部分规则遗漏导致的，建议使用 SRC-IP-CIDR 规则将 Apple TV 直接设置成 Netflix 对应的策略组，Apple TV 所有流量都会被代理。

如何使用SRC-IP-CIDR规则将AppleTV设置成Netflix对应的策略组呢？目前用的是lhie的策略组

**Comment by FrankieLEMON** [comment]
> 这是因为有部分规则遗漏导致的，建议使用 SRC-IP-CIDR 规则将 Apple TV 直接设置成 Netflix 对应的策略组，Apple TV 所有流量都会被代理。

我设置了Apple TV的SRC-IP-CIDR, 192.168.50.108/32,Proxy，还是Code 113

**Comment by FrankieLEMON** [comment]
现在还有一个问题就是在Global模式下也无法连上Netflix。但是其他的App，Youtube，Apple TV+都是可以上的

**Comment by jakeslee** [comment]
> > 这是因为有部分规则遗漏导致的，建议使用 SRC-IP-CIDR 规则将 Apple TV 直接设置成 Netflix 对应的策略组，Apple TV 所有流量都会被代理。
> 
> 我设置了Apple TV的SRC-IP-CIDR, 192.168.50.108/32,Proxy，还是Code 113

这种方式应该需要节点原生支持 Netflix

**Comment by FrankieLEMON** [comment]
> > > 这是因为有部分规则遗漏导致的，建议使用 SRC-IP-CIDR 规则将 Apple TV 直接设置成 Netflix 对应的策略组，Apple TV 所有流量都会被代理。
> 
> > 
> 
> > 我设置了Apple TV的SRC-IP-CIDR, 192.168.50.108/32,Proxy，还是Code 113
> 
> 
> 
> 这种方式应该需要节点原生支持 Netflix

您有联系方式吗～方便的话可以一起讨论一下…因为是我自建的VPS所以不确定是规则问题还是节点问题

**Comment by FrankieLEMON** [comment]
问题解决，SUFFIX- DOMAIN定义流量就好了！

**Comment by uygnef** [comment]
> 问题解决，SUFFIX- DOMAIN定义流量就好了！

想问下怎么设置

**Comment by zhaoooooooooo** [comment]
> 问题解决，SUFFIX-DOMAIN定义流量就好了！

你好，请问是单独给apple tv添加DOMAIN-SUFFIX吗，策略选择的什么。希望能得到楼主指点，非常感谢！

**Comment by tyhunter** [comment]
> 问题解决，SUFFIX- DOMAIN定义流量就好了！

@FrankieLEMON 请教下怎么设置的，换了N个节点，甚至启用了shadowsocksr plus作为全局代理都不行
