### ISSUE TITLE
Softether_VPN 提供的访问域名，无法正常解析WAN 公网ip，返回的是外网ip，应该如何设置【Bug】。

### ISSUE THREAD

**Issue by icucuio** [vernesong/OpenClash#965]
Softether_VPN 提供VPN服务，之前用它提供的访问域名，访问一点问题都没有，但是用了openclash后，解析域名就一直是代理的IP，不是我自己的公网ip了，应该如何破？

公网IP：
![image](https://user-images.githubusercontent.com/69136587/98467999-72c26e80-2213-11eb-9639-e6a331be8242.png)
外网代理IP：
![image](https://user-images.githubusercontent.com/69136587/98468014-88d02f00-2213-11eb-87a6-5d14858d4508.png)
ping 的时候返回的是外网代理IP：
![image](https://user-images.githubusercontent.com/69136587/98468054-b7e6a080-2213-11eb-9fd7-833bc89f551d.png)

**Comment by pwrliang** [comment]
- DOMAIN-SUFFIX,softether-network.net,DIRECT
 - DOMAIN-SUFFIX,softether.co.jp,DIRECT
 - DOMAIN-SUFFIX,flets-east.jp,DIRECT
 - DOMAIN-SUFFIX,flets-west.jp,DIRECT
 - DOMAIN-SUFFIX,ddns.uxcom.jp,DIRECT

**Comment by icucuio** [comment]
> 自定义规则添加如下内容
> 
> ```
>  - DOMAIN-SUFFIX,softether-network.net,DIRECT
>  - DOMAIN-SUFFIX,softether.co.jp,DIRECT
>  - DOMAIN-SUFFIX,flets-east.jp,DIRECT
>  - DOMAIN-SUFFIX,flets-west.jp,DIRECT
>  - DOMAIN-SUFFIX,ddns.uxcom.jp,DIRECT
> ```
大神，谢谢了，通过你的方法解决了，但是还是有问题，就是家里的软路由启动openclash，无线网局域网都可以成功科学上网，但是手机通过4g 连VPN，成功了家里局域网都没有问题，却不能科学上网，也不是都不行，youtube 和 google 都不行，提示是不是安全链接，不能访问，您知道怎么破吗？

**Comment by pwrliang** [comment]
> > 自定义规则添加如下内容
> > ```
> >  - DOMAIN-SUFFIX,softether-network.net,DIRECT
> >  - DOMAIN-SUFFIX,softether.co.jp,DIRECT
> >  - DOMAIN-SUFFIX,flets-east.jp,DIRECT
> >  - DOMAIN-SUFFIX,flets-west.jp,DIRECT
> >  - DOMAIN-SUFFIX,ddns.uxcom.jp,DIRECT
> > ```
> 
> 大神，谢谢了，通过你的方法解决了，但是还是有问题，就是家里的软路由启动openclash，无线网局域网都可以成功科学上网，但是手机通过4g 连VPN，成功了vpn后，访问家里局域网都没有问题，却不能科学上网，也不是都不行，youtube 和 google 都不行，提示是不是安全链接，不能访问，您知道怎么破吗？

你需要softether中设置桥接模式，然后在openwrt的lan接口的物理设置勾选上你创建的tap。

**Comment by icucuio** [comment]
> > > 自定义规则添加如下内容
> > > ```
> > >  - DOMAIN-SUFFIX,softether-network.net,DIRECT
> > >  - DOMAIN-SUFFIX,softether.co.jp,DIRECT
> > >  - DOMAIN-SUFFIX,flets-east.jp,DIRECT
> > >  - DOMAIN-SUFFIX,flets-west.jp,DIRECT
> > >  - DOMAIN-SUFFIX,ddns.uxcom.jp,DIRECT
> > > ```
> > 
> > 
> > 大神，谢谢了，通过你的方法解决了，但是还是有问题，就是家里的软路由启动openclash，无线网局域网都可以成功科学上网，但是手机通过4g 连VPN，成功了vpn后，访问家里局域网都没有问题，却不能科学上网，也不是都不行，youtube 和 google 都不行，提示是不是安全链接，不能访问，您知道怎么破吗？
> 
> 你需要softether中设置桥接模式，然后在openwrt的lan接口的物理设置勾选上你创建的tap。

你说的那个我肯定做了，否则vpn肯定连不上的。我的问题是访问youtube或者google网站的时候会报下面的错误：
![image](https://user-images.githubusercontent.com/69136587/98551975-e67a7f00-22d8-11eb-914a-bfa5d765c839.png)
