### ISSUE TITLE
opclash和ssrplus同样节点观看乃飞问题

### ISSUE THREAD

**Issue by noway2014** [vernesong/OpenClash#966]
在opCLASH里面，a机场已经分好了各个节点，我在他的节点里面选择某1号节点，有些电影还是不能看。提示解锁工具。但是在SSLPLUS里面，使用奶飞分流，同样机场同样的某1号点，却可以看。
请问为何？

**Comment by LeonZ19** [comment]
初步判断分为两种可能性：
1. OpenClash和SSRP分流规则不同，可能没有包含播放源的IP地址；
2. 其中一者用了主节点，而非分流节点。Netflix有一个栏目可以判断所在地，请楼主确认一下是否所在地不同。

**Comment by noway2014** [comment]
已经在奶飞显示是节点地区的，问题是ssrplus用该节点正常，opclash用，总不定期提示解锁。

**Comment by bingfoon** [comment]
> 已经在奶飞显示是节点地区的，问题是ssrplus用该节点正常，opclash用，总不定期提示解锁。
试试把下面这个碎片规则加进去，如果奈飞单独分流的话和奈飞用同样的代理
https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/Ruleset/AmazonIp.list

我之前用xbox看奈飞也不行，加了这个之后就可以了

**Comment by noway2014** [comment]
请问楼上，如何在路由opclash加上你给的那个连接规则呢？初步用，不打明白

**Comment by bingfoon** [comment]
> 请问楼上，如何在路由opclash加上你给的那个连接规则呢？初步用，不打明白

你在配置文件订阅那里，点转换模版 选择截图里红框那个模版试试先
[](https://github.com/bingfoon/img/blob/master/uPic/13671605176393_.pic_hd.jpg?raw=true)

**Comment by noway2014** [comment]
是不是自己的订阅地址，配置订阅文件_在线订阅选启用，然后下面订阅模板那里选择你说的这个

**Comment by noway2014** [comment]
可以电报请教吗

**Comment by noway2014** [comment]
按照https://github.com/vernesong/OpenClash/issues/966#issuecomment-725987554
这个操作，选择了这个自定义规则，还是出现某些电影提示使用解锁工具问题，而同样用ssrplus，同样节点，却没有这样的提示

**Comment by noway2014** [comment]
opclash上网速度明显比ssrplus速度快，所以很难取舍

**Comment by noway2014** [comment]
有办法解决吗

**Comment by nameless3721** [comment]
> 按照[#966 (comment)](https://github.com/vernesong/OpenClash/issues/966#issuecomment-725987554)
> 这个操作，选择了这个自定义规则，还是出现某些电影提示使用解锁工具问题，而同样用ssrplus，同样节点，却没有这样的提示

可能你的机场是用dns解锁的 然后你是用tv盒子观看 tv的乃飞客户端喜欢把nflxvideo.net域名走8888的dns解析 然后你的clash log应该会有ip走nf策略的记录 ip是无法dns解锁的所以容易出问题了 (虽然不知道ssrp是怎么劫持到域名给服务端到能看) 你可以试试把电脑的系统dns改为 8.8.8.8 的话上谷歌这类网站是不是大部分日志都是ip吧 就算你防火墙有个劫持53端口的规则  如果不是tv盒子出现就当我没说吧  一般就算dns解锁的节点 电脑手机是没啥问题的
