### ISSUE TITLE
[Feature Request]可否新增TProxy模式

### ISSUE THREAD

**Issue by R3pl4c3r** [vernesong/OpenClash#968]
这个 Dreamacro/clash@83efe2ae57c
还有就是有无可能把mixed-port也做了？

**Comment by YukawaMi** [comment]
附议

**Comment by YukawaMi** [comment]
> 这个 [Dreamacro/clash@83efe2a](https://github.com/Dreamacro/clash/commit/83efe2ae57c)
> 还有就是有无可能把mixed-port也做了？

mixed-prot有了

**Comment by crzidea** [comment]
什么时候 IPv4 TCP 能支持 TProxy 模式啊？
看了一下，IPv6、IPv4 UDP 都可以支持了，就差一个 IPv4 TCP 了，求求快支持了吧😂
