### ISSUE TITLE
用softether VPN 连接家中软路由，软路由启动openclash，HTTPS的网站不能科学上网，HTTP的网站就可以，局域网内都没有问题，应该怎么设置？

### ISSUE THREAD

**Issue by icucuio** [vernesong/OpenClash#973]
我在家里的软路由上成功运行了open clash， 为局域网内提供科学上网，离开家后，我手机也想科学上网，所以用softether VPN  在4G网络下，是可以成功VPN回家里的路由的，但是却不能科学上网，同时间局域网内的设备都可以。提示的错误如下：
应该怎么解决？
![image](https://user-images.githubusercontent.com/69136587/98691127-a97dbd80-23a8-11eb-8b79-a4b1af017f78.png)

**Comment by noway2014** [comment]
请问你siftvpn回家软路由的话，应该如何设置？

**Comment by icucuio** [comment]
> 请问你siftvpn回家软路由的话，应该如何设置？

网上很多，自己搜下

**Comment by vernesong** [comment]
插件机智不明，有试过其他vpn吗

**Comment by icucuio** [comment]
> 插件机制不明，有试过其他vpn吗

softetherVPN 是非常厉害的，而且提供免费的域名解析，这个域名解析的问题已经在社区朋友解答下已经成功了，现在就是访问的问题了。
我用v2rayN的时候是没有问题的，随时都可以，就是openclash不可以了，总是提示不安全连接，不管用fakeip 还是redirect都一样了。
