### ISSUE TITLE
Fake-ip 和 Redir-host 两个模式，从速度上看，那个有优势？如果综合看那个更有优势？

### ISSUE THREAD

**Issue by icucuio** [vernesong/OpenClash#974]
谁了解 Fake-ip 和 Redir-host 两个模式？ 在哪里可以看到相关的介绍或者技术文档？
速度上看那个更快？

**Comment by YukawaMi** [comment]
理论上fake-ip的响应会更快(因为会马上给你一个假IP)。。。。

**Comment by eggydutch** [comment]
> 谁了解 Fake-ip 和 Redir-host 两个模式？ 在哪里可以看到相关的介绍或者技术文档？
> 速度上看那个更快？

https://blog.skk.moe/post/what-happend-to-dns-in-proxy/
这篇就说得挺详细的，可以参考一下。

**Comment by Bitcion** [comment]
Redir-host就像是一个快递员，按照公司分配的任务，要么送件要么收件，完成一个业务才会收到下个任务；而fake ip既能收也能送，（如果把本地延迟忽略掉）收的同时把件寄了出去

**Comment by cyh303** [comment]
Fake-ip 模式下DNS好像无法解析IPV6  这个有没有办法解决呢

**Comment by zbceru** [comment]
> 

在dns高级设置里添加需要解析的域名

**Comment by shayu100861** [comment]
话说，redir-host和fake-ip是只能在tun或者tap模式下使用吗

**Comment by Karmylr** [comment]
> 

可以

**Comment by Leo4242** [comment]
怎么解决fake-ip模式下的黑白名单功能是失效的？

**Comment by zbceru** [comment]
> 怎么解决fake-ip模式下的黑白名单功能是失效的？

chatGPT4.0应该能解决

**Comment by Leo4242** [comment]
> > 怎么解决fake-ip模式下的黑白名单功能是失效的？
> 
> chatGPT4.0应该能解决

ChatGPT 4.0告诉你怎么解决了吗？

**Comment by zbceru** [comment]
> > > 怎么解决fake-ip模式下的黑白名单功能是失效的？
> > 
> > chatGPT4.0应该能解决
> 
> ChatGPT 4.0告诉你怎么解决了吗？

我没有gpt4.0，

**Comment by Oldcucumber** [comment]
> 怎么解决fake-ip模式下的黑白名单功能是失效的？
  启用防火墙转发DNS

**Comment by lingchenma** [comment]
> fake-ip

fake-ip 支持v6地址吗？
