### ISSUE TITLE
关于Clash升级至v0.40.13-beta后，frp远程控制不了YACD面板的问题。

### ISSUE THREAD

**Issue by super27035** [vernesong/OpenClash#976]
由于Clash版本为v0.40.13-beta之后，YACD控制面板回退至0.2.5，我的frp就不能远程控制YACD面板了。

以下是旧的登陆面板：
![旧](https://user-images.githubusercontent.com/43180500/99031616-7870d900-25b2-11eb-9b6a-16559586b3cd.jpg)

以下是新的登陆面板：
![Screen Shot 2020-11-12 at 10 43 40 PM](https://user-images.githubusercontent.com/43180500/99031631-858dc800-25b2-11eb-89c0-4bd4e5abcc21.jpg)

不知道哪位大神知道新的面板frp如何设置？

**Comment by YukawaMi** [comment]
yacd转发端口从来没成功，默认的那个面板可以。。。。。。

**Comment by super27035** [comment]
> yacd转发端口从来没成功，默认的那个面板可以。。。。。。

我可以远程进入YACD，但只能用老的登陆面板，新的搞不了。
请问你可以用frp远程访问Dashboard 控制面板？

**Comment by YukawaMi** [comment]
> > yacd转发端口从来没成功，默认的那个面板可以。。。。。。
> 
> 我可以远程进入YACD，但只能用老的登陆面板，新的搞不了。
> 请问你可以用frp远程访问Dashboard 控制面板？

我用的是DDNS，没用frp，理论上只是比你少了个中间服务器的转发，但是我OPENWRT并不是网关路由，所以，9090端口还是靠网关路由转发了一次

**Comment by abigchopstick** [comment]
> 由于Clash版本为v0.40.13-beta之后，YACD控制面板回退至0.2.5，我的frp就不能远程控制YACD面板了。
> 
> 以下是旧的登陆面板： ![旧](https://user-images.githubusercontent.com/43180500/99031616-7870d900-25b2-11eb-9b6a-16559586b3cd.jpg)
> 
> 以下是新的登陆面板： ![Screen Shot 2020-11-12 at 10 43 40 PM](https://user-images.githubusercontent.com/43180500/99031631-858dc800-25b2-11eb-89c0-4bd4e5abcc21.jpg)
> 
> 不知道哪位大神知道新的面板frp如何设置？

I figure it out.

1. 首先你要能打开YACD这个登陆面板。
2. 然后你要用FRP做一个TCP端口穿透，外网端口你自己决定，比如29090，内网是127.0.0.1:9090
3. 然后你在yacd这个登陆面板这里填上 yourfrp.domain:29090 （yourfrp.domain改成你自己的frp服务器域名或者IP）
4. Secret一般是123456，如果取消了可以留空。

ENJOY。

也就是说你需要做一个HTTP FRP穿透给LUCI，然后再用FRP做一个TCP端口穿透给面板，完美。
