### ISSUE TITLE
clash控制面板设置是每次更新订阅都会变成默认的吗

### ISSUE THREAD

**Issue by b911ss** [vernesong/OpenClash#979]
clash控制面板设置是每次更新订阅，策略规则选项都会变成默认的吗，每天都要重新设置一下，我也不清楚是固件问题，还是什么，有没有大佬知道的

**Comment by VergilGao** [comment]
同问，我这机场默认是低倍率下载线路，ping值高的飞起……我设置的每天早上4点更新订阅。
