### ISSUE TITLE
成功启动后无法上网， 你说你们写这个程序来干嘛啊？

### ISSUE THREAD

**Issue by capewang** [vernesong/OpenClash#984]
先是 DNS 上游服务器那里的bug，然后是俩面板的bug， 然后是config自定义规则的bug，然后是移除config的bug。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。

太秀了， 最后呢，bug弄完了，  成功启动了，

抱歉，无法连接网页

干嘛嘞？

**Comment by capewang** [comment]
面板中还不能设置成系统代理。

**Comment by BigDog66** [comment]
白嫖插件还理直气壮的质问作者，牛逼。
发现问题好好提出，开发者看到了 自然会在以后版本修复
而楼主这个态度，开发者会回复你才怪。

**Comment by zzcabc** [comment]
不满意可以不用，

**Comment by zzcabc** [comment]
不满意可以不用，你牛逼你可以自己写

**Comment by hcym** [comment]
，😂

**Comment by lifetyper** [comment]
你自己写一个更好的，我付钱买都可以。

**Comment by FlyingSmoke** [comment]
Talk is cheap. Show me the code.

**Comment by capewang** [comment]
哈哈，应该说出很多人心里话没？

**Comment by YukawaMi** [comment]
首先：我用的很正常，除了之前加新依赖有点问题，你说的这些我都没遇到，后来一直都用的很好；
其次：作者是欠你的吗，自己费时费力吃力不讨好被你白嫖了还要被你骂。。。。真的是白嫖当大爷当惯了吧

**Comment by YukawaMi** [comment]
看了下你在github仅有的两次活动，除了喷还是喷。。。。真的是绝了

**Comment by hermitli** [comment]
这人啥毛病…

**Comment by capewang** [comment]
你说啥毛病，就是啥毛病🐻

**Comment by LimonChoms** [comment]
也许这就是孤儿伸手党吧

**Comment by VergilGao** [comment]
不过 0.40.7 以上版本的确不是很稳。

**Comment by People-11** [comment]
一不提交log，二白嫖还骂人，作者会理你才怪
也许这就是被父母惯坏的孤儿吧…

**Comment by 1715173329** [comment]
求你用了还是咋？搁这找存在感呢¿
> 写来干嘛呢？

有意见自己写啊，有 bug 提 PR 修啊
没能力又在这里 BB，当你自己甲方呢？
你为这个项目做了什么贡献啊？

现在出来的成本太低，GitHub 的注册成本太低，以至于是不是人都能在这里叫唤。

送你三个字，
你不配

**Comment by LOVE2CMOL** [comment]
你配吗？

**Comment by LOVE2CMOL** [comment]
首先你可以自己写
其次你可以出钱叫别人写
要不你自己修也行？开源的

你对这个项目贡献了什么？

补充上面那句话，你不配

**Comment by Ahtaler** [comment]
你可以不用

**Comment by bslc981010** [comment]
果然人品差的人用啥都会出问题啊

**Comment by openips** [comment]
能力水平和个人素质成正比

**Comment by capewang** [comment]
一群人可真的是望眼欲穿啊。偏偏我我帖子下面找存在感。有几个扣字的时间，好好衡量自己一下。   我们没用，bug搞定后就没用过。  你免不免费，和你开发态度没关系。  你素质什么样，我也管不到，可能网络上出现个 他妈俩字，你们也要高潮。  你们把自己衡量的太高了。  或者就闭嘴🤐️。  你们点开这个标签时肯定有软件问题吧？你们问啊，跑我这下面找存在感啊？  白嫖的是你们吧。

**Comment by capewang** [comment]
@1715173329   你要是在我这气死了， 是活该，还是犯贱啊

**Comment by 1715173329** [comment]
> @1715173329 你要是在我这气死了， 是活该，还是犯贱啊

像你这种司马玩意儿也有那个能力气死你大爷？
还是洗洗睡做你的中国梦去吧

**Comment by R3pl4c3r** [comment]
@vernesong 建议把这个人ban了

**Comment by capewang** [comment]
@R3pl4c3r 别叨叨了 要ban我  找ban了。

**Comment by capewang** [comment]
> > @1715173329 你要是在我这气死了， 是活该，还是犯贱啊
> 
> 像你这种司马玩意儿也有那个能力气死你大爷？
> 还是洗洗睡做你的中国梦去吧

别人说啥你都管一管，你就像个儿子照顾爹一样

**Comment by capewang** [comment]
你们特别像某个网站得用户，特玻璃心，哪个网站你们猜下了？ 

之前被关过了，这不又被reopen了吗 自己看啊@R3pl4c3r 

一般团队里面都得有个拉后腿得。是不？

**Comment by vernesong** [comment]
相互尊重，使用自由，言论自由，欢迎吐槽。
这条我关闭了 @capewang

**Comment by 1715173329** [comment]
倘若真有二八原则，像你这种人只怕被圈养的资格都没有
至少那些被圈养的人不会反过来骂养他们的人

**Comment by 1715173329** [comment]
此外，按照你这个逻辑，Windows 的 bugs 也不是一天两天了，建议去微软公司问问他们开发 Windows 干嘛

**Comment by capewang** [comment]
@1715173329   某网站得重度用户吧， 说话的风格都一致。还windows ，还类比，你这么高大上，天天做的都高级梦，跟我类比？
G远点。

**Comment by 1715173329** [comment]
谁谁该滚心里没点逼数
张口闭口某网站，遮遮掩掩
你这能耐也就只配用垃圾 koolshare lede

**Comment by 1715173329** [comment]
你这能耐确实符合 koolshare 用户平均水平

**Comment by capewang** [comment]
> 垃圾 koolshare lede

傻b小学生  素质教育片看多了。 不是不能说别人垃圾吗

**Comment by 1715173329** [comment]
> > 垃圾 koolshare lede
> 
> 傻b小学生 素质教育片看多了。 不是不能说别人垃圾吗

傻逼，看来还说中了啊
我看你这高素质人才除了来 GitHub 喷粪以外也没干个什么

**Comment by 1715173329** [comment]
真的，连上 Internet 的成本太低，是不是人都能来黑屁

**Comment by capewang** [comment]
@1715173329 一个科学上网 能给你膨胀成这样？

**Comment by Ahtaler** [comment]
那要不你写一个？

**Comment by Ahtaler** [comment]
@capewang
那要不你写一个？

**Comment by 1715173329** [comment]
就事论事，大可不必扯开话题

**Comment by capewang** [comment]
@1715173329 你论啊  我听着呢

**Comment by 1715173329** [comment]
你论你🐴呢

**Comment by capewang** [comment]
小学生  三流教育片看多了

**Comment by 1715173329** [comment]
小学生素质能力比你们 koolshare 高多了

**Comment by 1715173329** [comment]
koolshare lede 何必用给 official openwrt 用的插件呢，就你这搞得好像还谁稀罕你了

**Comment by 1715173329** [comment]
张口闭口就一个科学上网，建议你这个高素质人才自己写一个没有 bug 的

**Comment by capewang** [comment]
软件用户歧视  秀啊    我都没用啊

**Comment by 1715173329** [comment]
或者说你们 koolshare，反正一个逼样
违反协议的垃圾玩意儿还敢来叫嚣

**Comment by capewang** [comment]
没意思了， 越扯越远  ，再见 ，小朋友。   少看点垃圾教育片，你还有救

**Comment by 1715173329** [comment]
偷换概念的能力太垃圾了，诡辩术再滚去好好学学吧
你们 koolshare 也就那样了

**Comment by 1715173329** [comment]
被踢出某 telegram 群的那个玩意儿不会就是你吧

**Comment by capewang** [comment]
我都没用 ，还telegram  我至于吗？

**Comment by 1715173329** [comment]
小学生都比你这明事，说你是三岁小屁孩还真是抬举你了
滚吧

**Comment by capewang** [comment]
再见吧    祖国未来的花朵

**Comment by 1715173329** [comment]
哪里哪里，你这你国当下的韭菜

**Comment by 1715173329** [comment]
此外有个现象是自己是什么，看别人也是什么
比如你是个小学生，看谁都是小学生

**Comment by capewang** [comment]
你懂得可真多啊， 
我们韭菜能折
花折了就死了

看来没救了。

**Comment by Catnipll** [comment]
什么玩意啊，好牛逼哦，那你自己写一个啊，可惜就只长了一张嘴叭叭个不停

**Comment by 1715173329** [comment]
你张口闭口小学生，无法不过你自己就是罢了
我也就闲得无聊逗逗猴子，仅此而已
