### ISSUE TITLE
yacd测试延迟有时候有数据，有时候没有

### ISSUE THREAD

**Issue by jaove** [vernesong/OpenClash#987]

**Comment by jaove** [comment]
如果是直连的vps每次测试延迟都有数据，套了cf的也都有延迟数据，如果是通过端口转发的节点，测试延迟数据有时候有，有时候就没有，看起来就像节点挂了，但其实并没有

**Comment by vernesong** [comment]
测试是get，就是实际的连接情况，可以尝试更换测速地址

**Comment by matthuo333** [comment]
更换许多204测速地址，但都发现通过自动测试type到了无效节点(无数据)上，哪的问题呢？
