### ISSUE TITLE
UDP问题

### ISSUE THREAD

**Issue by s2270661782** [vernesong/OpenClash#988]
我吧UDP关闭之后 玩方舟还是进入延迟 不能进服务器

**Comment by s2270661782** [comment]
![image](https://user-images.githubusercontent.com/37266454/99256197-f29c9a00-280c-11eb-8556-b494703285b6.png)

**Comment by s2270661782** [comment]
就是这样

**Comment by s2270661782** [comment]
一切外服游戏的都超时

**Comment by vernesong** [comment]
游戏建议用tun模式，普通模式普遍反应tproxy转发有问题，另外节点需要支持udp

**Comment by s2270661782** [comment]
> [tun]，[troxy]，[udp]
我说的是 我没有开启udp  gta5进游戏进不去 方舟 服务器也是进不去
