### ISSUE TITLE
Can not install the package which doesn't support kernel 4.14

### ISSUE THREAD

**Issue by a13519** [vernesong/OpenClash#989]
Hi, 

When I install the ipk or build the package by myself, it throws error:

`root@OW4:~# opkg install luci-app-openclash_0.40.15-beta_all.ipk 
Installing luci-app-openclash (0.40.15-beta) to root...
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-app-openclash:
 *      kernel (= 4.14.180-1-e1dd7676581672f6f0bdb1363506dee1)
 * opkg_install_cmd: Cannot install package luci-app-openclash.`

my kernel is 4.14.180, why does this have such restriction and how to overcome it?

Thanks,
Song

**Comment by YukawaMi** [comment]
I think you may solve this problem by installing the kernel ipk manually.  https://downloads.openwrt.org/releases/

**Comment by maddie** [comment]
Use `--force-depends` when installing
