### ISSUE TITLE
结合adguard home 使用 DNS 设置求教

### ISSUE THREAD

**Issue by xiaofami** [vernesong/OpenClash#99]
现在的设置是openclash将adguard home设置为上游DNS，adguard home 中将本地ISP的DNS设置为上游DNS。目前工作正常，家里所有设备既可以通过openclash策略上网，也可以得到adguard home的保护。但是我不知道这样设置是否可以实现DNS分流查询，即国外需要代理的域名转发到VPS，由VPS进行查询。如果不可以，应该怎样实现比较好呢

**Comment by vernesong** [comment]
* **clash的工作方式是按照你的配置文件内的规则进行策略分流。**
* **上游DNS查询主要是以下两个用途：**
1.用在没有匹配到域名规则，但规则内还有IP规则，需要解析后判断
2.判断不在规则内的连接是否是国外地址，走对应策略
3.选取DNS响应最快的地址
4.直连解析
* **两种运行模式下上游DNS的作用：**
1.Redir:正常时使用nameserver组和fallback组中响应最快的结果进行通信；污染时使用fallback组的DNS返回结果进行连接
2.Fake-ip:仅需要nameserver组的结果进行是否命中规则的判断，需要代理时会直接在服务器端进行DNS解析。
* **配合adguard home**
1.Redir模式下将clash上游服务器设置为adh的监听地址，并删除其他上游DNS服务器。
2.Fake-ip模式下DNS设置与上述相同，但还需要保证配置文件规则最后为
```
- MATCH,DIRECT
```
避免部分clash判定需要代理的广告进行服务器查询，此时adh失效。

**Comment by Mosney** [comment]
ADG只有在clash下游才能完全生效，否则clash只会将最终策略是DIRECT连接的DNS查询交给配置文件中的上游DNS去解析。

**Comment by xdaniel9** [comment]
可否直接将openclash所在设备的ip设置为adg的上游dns，上网设备的dns设置为adg所在设备的ip

**Comment by vernesong** [comment]
我很早前测试过，adg做下游时不会老老实实返回从clash那拿到的DNS结果，导致连接不稳定，具体能不能用，需要你们自己测试。

**Comment by Mosney** [comment]
> 我很早前测试过，adg做下游时不会老老实实返回从clash那拿到的DNS结果，导致连接不稳定，具体能不能用，需要你们自己测试。

大概是因为你用了多个上游？我这一直这么用，没问题的

**Comment by yanyingjie007** [comment]
> 现在的设置是openclash将adguard home设置为上游DNS，adguard home 中将本地ISP的DNS设置为上游DNS。目前工作正常，家里所有设备既可以通过openclash策略上网，也可以得到adguard home的保护。但是我不知道这样设置是否可以实现DNS分流查询，即国外需要代理的域名转发到VPS，由VPS进行查询。如果不可以，应该怎样实现比较好呢

这种方式设置DNS，局域网的设备的dns是openclash还是adguard home呢？

**Comment by hankclc** [comment]
> > 我很早前测试过，adg做下游时不会老老实实返回从clash那拿到的DNS结果，导致连接不稳定，具体能不能用，需要你们自己测试。
> 
> 大概是因为你用了多个上游？我这一直这么用，没问题的

adguard做下游该怎么设置？可以简单说一下吗？

**Comment by eyaeya** [comment]
> > > 我很早前测试过，adg做下游时不会老老实实返回从clash那拿到的DNS结果，导致连接不稳定，具体能不能用，需要你们自己测试。
> 
> > 
> 
> > 大概是因为你用了多个上游？我这一直这么用，没问题的
> 
> 
> 
> adguard做下游该怎么设置？可以简单说一下吗？

@Mosney 同文，OpenClash作为ADH的上游，该如何设置呢？
1. ADH的上游DNS该如何设置；
2. ADH该设置为什么重定向模式。

感恩。

**Comment by nancheung97** [comment]
> > > > 我很早前测试过，adg做下游时不会老老实实返回从clash那拿到的DNS结果，导致连接不稳定，具体能不能用，需要你们自己测试。
> > 
> > 
> > > 
> > 
> > 
> > > 大概是因为你用了多个上游？我这一直这么用，没问题的
> > 
> > 
> > adguard做下游该怎么设置？可以简单说一下吗？
> 
> @Mosney 同文，OpenClash作为ADH的上游，该如何设置呢？
> 
> 1. ADH的上游DNS该如何设置；
> 2. ADH该设置为什么重定向模式。
> 
> 感恩。

@hankclc @eyaeya 
1. 将AdGuard Home的**上游DNS**设置为OpenClash的DNS地址；
   >OpenClash开启**本地DNS劫持**，可以在**DHCP/DNS**项中看到OpenClash的DNS地址
2. 关闭OpenClash的**本地DNS劫持**；
3. AdGuard Home重定向模式使用**53端口替换dnsmasq**。

此方案可以显示局域网内的ip地址，非127.0.0.1

**Comment by eyaeya** [comment]
> > > > > 我很早前测试过，adg做下游时不会老老实实返回从clash那拿到的DNS结果，导致连接不稳定，具体能不能用，需要你们自己测试。
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 大概是因为你用了多个上游？我这一直这么用，没问题的
> 
> > > 
> 
> > > 
> 
> > > adguard做下游该怎么设置？可以简单说一下吗？
> 
> > 
> 
> > @Mosney 同文，OpenClash作为ADH的上游，该如何设置呢？
> 
> > 
> 
> > 1. ADH的上游DNS该如何设置；
> 
> > 2. ADH该设置为什么重定向模式。
> 
> > 
> 
> > 感恩。
> 
> 
> 
> @hankclc @eyaeya 
> 
> 1. 将AdGuard Home的**上游DNS**设置为OpenClash的DNS地址；
> 
>    >OpenClash开启**本地DNS劫持**，可以在**DHCP/DNS**项中看到OpenClash的DNS地址
> 
> 2. 关闭OpenClash的**本地DNS劫持**；
> 
> 3. AdGuard Home重定向模式使用**53端口替换dnsmasq**。
> 
> 
> 
> 此方案可以显示局域网内的ip地址，非127.0.0.1

我遇到的问题是，AdGuard Home 禁止设置“127.0.0.1:7874”这个OpenClash地址作为上游。

**Comment by srrshweee** [comment]
我的解决方案是在openwrt的lan设置里面写入6:192.168.10.1，这样就能成功获取DNS地址了

**Comment by magic3584** [comment]
> 1. AdGuard Home的**上游DNS**设置为OpenClash的DNS

@nancheung97 请教第一步
服务器 "127.0.0.1:7874"：无法使用，请检查你输入的是否正确
这个报错怎么解决？

**Comment by srrshweee** [comment]
> > 1. AdGuard Home的**上游DNS**设置为OpenClash的DNS
> 
> @nancheung97 请教第一步
> 服务器 "127.0.0.1:7874"：无法使用，请检查你输入的是否正确
> 这个报错怎么解决？

我也有这样的报错，但是不影响使用。

**Comment by srrshweee** [comment]
> > > > 1. AdGuard Home的**上游DNS**设置为OpenClash的DNS
> > > 
> > > 
> > > @nancheung97 请教第一步
> > > 服务器 "127.0.0.1:7874"：无法使用，请检查你输入的是否正确
> > > 这个报错怎么解决？
> > 
> > 
> > 我也有这样的报错，但是不影响使用。
> 
> 请教报错的话还保存吗？ adg 上游都填空？

我还是填127.00.1：7874，虽然提示报错但是目前正常使用

**Comment by magic3584** [comment]
> > > > > 1. AdGuard Home的**上游DNS**设置为OpenClash的DNS
> > > > 
> > > > 
> > > > @nancheung97 请教第一步
> > > > 服务器 "127.0.0.1:7874"：无法使用，请检查你输入的是否正确
> > > > 这个报错怎么解决？
> > > 
> > > 
> > > 我也有这样的报错，但是不影响使用。
> > 
> > 
> > 请教报错的话还保存吗？ adg 上游都填空？
> 
> 我还是填127.00.1：7874，虽然提示报错但是目前正常使用

感谢大佬，我试试

**Comment by icyleaf** [comment]
> > > > > 我很早前测试过，adg做下游时不会老老实实返回从clash那拿到的DNS结果，导致连接不稳定，具体能不能用，需要你们自己测试。
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > 大概是因为你用了多个上游？我这一直这么用，没问题的
> > > 
> > > 
> > > adguard做下游该怎么设置？可以简单说一下吗？
> > 
> > 
> > @Mosney 同文，OpenClash作为ADH的上游，该如何设置呢？
> > 
> > 1. ADH的上游DNS该如何设置；
> > 2. ADH该设置为什么重定向模式。
> > 
> > 感恩。
> 
> @hankclc @eyaeya
> 
> 1. 将AdGuard Home的**上游DNS**设置为OpenClash的DNS地址；
>    > OpenClash开启**本地DNS劫持**，可以在**DHCP/DNS**项中看到OpenClash的DNS地址
> 2. 关闭OpenClash的**本地DNS劫持**；
> 3. AdGuard Home重定向模式使用**53端口替换dnsmasq**。
> 
> 此方案可以显示局域网内的ip地址，非127.0.0.1

补充：

1. OpenClash 的 DNS 地址可以在 全局设置 -> 基本设置 -> DNS 监听端口看到即 7874，在 ADH 设置为 127.0.0.1:7874
2. OpenClash 不要使用 TUN 或 TUN 混合模式

**Comment by zane-ng** [comment]
> 补充：
> 
> 1. OpenClash 的 DNS 地址可以在 全局设置 -> 基本设置 -> DNS 监听端口看到即 7874，在 ADH 设置为 127.0.0.1:7874
> 2. OpenClash 不要使用 TUN 或 TUN 混合模式

可以请教一下为什么不要使用 TUN 或者 TUN 混合模式吗？

**Comment by xiaotianxt** [comment]
> > > > > 我很早前测试过，adg做下游时不会老老实实返回从clash那拿到的DNS结果，导致连接不稳定，具体能不能用，需要你们自己测试。
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > 大概是因为你用了多个上游？我这一直这么用，没问题的
> > > 
> > > 
> > > adguard做下游该怎么设置？可以简单说一下吗？
> > 
> > 
> > @Mosney 同文，OpenClash作为ADH的上游，该如何设置呢？
> > 
> > 1. ADH的上游DNS该如何设置；
> > 2. ADH该设置为什么重定向模式。
> > 
> > 感恩。
> 
> @hankclc @eyaeya
> 
> 1. 将AdGuard Home的**上游DNS**设置为OpenClash的DNS地址；
>    > OpenClash开启**本地DNS劫持**，可以在**DHCP/DNS**项中看到OpenClash的DNS地址
> 2. 关闭OpenClash的**本地DNS劫持**；
> 3. AdGuard Home重定向模式使用**53端口替换dnsmasq**。
> 
> 此方案可以显示局域网内的ip地址，非127.0.0.1

请教一个问题：为什么要将上游DNS设置为OpenClash的DNS地址？OpenClash的DNS服务不是用于解决污染站点解析的嘛？如果我保证ADH填写的上游DNS服务器可以正确解析，那么还需要OpenClash的本地DNS服务吗？

**Comment by kkfuzi** [comment]
> > > > > 我很早前测试过，adg做下游时不会老老实实返回从clash那拿到的DNS结果，导致连接不稳定，具体能不能用，需要你们自己测试。
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > 大概是因为你用了多个上游？我这一直这么用，没问题的
> > > 
> > > 
> > > adguard做下游该怎么设置？可以简单说一下吗？
> > 
> > 
> > @Mosney 同文，OpenClash作为ADH的上游，该如何设置呢？
> > 
> > 1. ADH的上游DNS该如何设置；
> > 2. ADH该设置为什么重定向模式。
> > 
> > 感恩。
> 
> @hankclc @eyaeya
> 
> 1. 将AdGuard Home的**上游DNS**设置为OpenClash的DNS地址；
>    > OpenClash开启**本地DNS劫持**，可以在**DHCP/DNS**项中看到OpenClash的DNS地址
> 2. 关闭OpenClash的**本地DNS劫持**；
> 3. AdGuard Home重定向模式使用**53端口替换dnsmasq**。
> 
> 此方案可以显示局域网内的ip地址，非127.0.0.1

请教个问题，我现在用这个推荐的方式设置openclash和adguardhome，AGH的上游DNS只填127.0.0.1:7874，国内国外访问正常。但出现一个小问题：openclash在更新配置文件的时候由于配置里一个小错误导致无法启动，AGH获取不到dns信息于是局域网内设备无法获取DNS从而无法上网。
所以在openclash和adguardhome的搭配下，有没有一个在openclash无法启动的情况下保证上网功能的方案？如果在AGH的上游DNS里加上比如114或者其他公共DNS，好像会导致不稳定？
谢谢。

**Comment by phlinhng** [comment]
分享我的做法：ISP → OpenClash → ADH

1. Openwrt 关闭 dnsmasq（即取消网络 → DHCP/DNS 里的 **DNS 重定向**）
2. OpenClash 关闭**本地DNS劫持**和**自定义上游DNS服务器**，并设置你喜欢的上游，可以是 ISP 的也可以是任何公共 DNS
3. ADH 的**唯一**上游设置为 **127.0.0.1:7874**
4. ADH 用非 53 端口，重定向模式选择重定向53端口到 AdGuardHome

这个方案下，OpenClash 可以用任何你喜欢的模式，我用的是 **Redir-Host（TUN-混合）**。
TCP、UDP皆运作正常；nslookup 能拿到正确的IP；AdGuardHome 日志可以拿到客户端地址而非 127.0.0.1。

此方案本质上是用 adguardhome 取代 dnsmasq，并使用 openclash 的 dns 做为 adh 上游。想要更改上游地址的时候从 OpenClash 里面改即可。

**Comment by magic3584** [comment]
> 分享我的做法：ISP → OpenClash → ADH
> 
> 1. Openwrt 关闭 dnsmasq（即取消网络 → DHCP/DNS 里的 **DNS 重定向**）
> 2. OpenClash 关闭**本地DNS劫持**和**自定义上游DNS服务器**，并设置你喜欢的上游，可以是 ISP 的也可以是任何公共 DNS
> 3. ADH 的**唯一**上游设置为 **127.0.0.1:7874**
> 4. ADH 用非 53 端口，重定向模式选择重定向53端口到 AdGuardHome
> 
> 这个方案下，OpenClash 可以用任何你喜欢的模式，我用的是 **Redir-Host（TUN-混合）**。 TCP、UDP皆运作正常；nslookup 能拿到正确的IP；AdGuardHome 日志可以拿到客户端地址而非 127.0.0.1。
> 
> 此方案本质上是用 adguardhome 取代 dnsmasq，并使用 openclash 的 dns 做为 adh 上游。想要更改上游地址的时候从 OpenClash 里面改即可。

大佬，我按您这方式并不能用啊。。。

**Comment by xxiaocheng** [comment]
> * 用在没有匹配到域名规则

请问第一条` 匹配到域名规则`
clash 是根据什么获取访问的域名的，如果浏览器在访问一个网站时，已经使用其他dns解析到了ip，那么clash是通过什么再过去的即将访问的网站的域名呢？是sni吗？麻烦大佬解答

**Comment by iamsweet** [comment]
> 

太棒了，这个是我找了一圈最完整的设置方法。
我自己调了2小时没调通，按照这个设置5分钟就好了，感谢感谢

**Comment by iamsweet** [comment]
> 分享我的做法：ISP → OpenClash → ADH
> 
> 1. Openwrt 关闭 dnsmasq（即取消网络 → DHCP/DNS 里的 **DNS 重定向**）
> 2. OpenClash 关闭**本地DNS劫持**和**自定义上游DNS服务器**，并设置你喜欢的上游，可以是 ISP 的也可以是任何公共 DNS
> 3. ADH 的**唯一**上游设置为 **127.0.0.1:7874**
> 4. ADH 用非 53 端口，重定向模式选择重定向53端口到 AdGuardHome
> 
> 这个方案下，OpenClash 可以用任何你喜欢的模式，我用的是 **Redir-Host（TUN-混合）**。 TCP、UDP皆运作正常；nslookup 能拿到正确的IP；AdGuardHome 日志可以拿到客户端地址而非 127.0.0.1。
> 
> 此方案本质上是用 adguardhome 取代 dnsmasq，并使用 openclash 的 dns 做为 adh 上游。想要更改上游地址的时候从 OpenClash 里面改即可。

太棒了，这个是我找了一圈最完整的设置方法。
我自己调了2小时没调通，按照这个设置5分钟就好了，感谢感谢

**Comment by wyfang** [comment]
> 分享我的做法：ISP → OpenClash → ADH
> 
> 1. Openwrt 关闭 dnsmasq（即取消网络 → DHCP/DNS 里的 **DNS 重定向**）
> 2. OpenClash 关闭**本地DNS劫持**和**自定义上游DNS服务器**，并设置你喜欢的上游，可以是 ISP 的也可以是任何公共 DNS
> 3. ADH 的**唯一**上游设置为 **127.0.0.1:7874**
> 4. ADH 用非 53 端口，重定向模式选择重定向53端口到 AdGuardHome
> 
> 这个方案下，OpenClash 可以用任何你喜欢的模式，我用的是 **Redir-Host（TUN-混合）**。 TCP、UDP皆运作正常；nslookup 能拿到正确的IP；AdGuardHome 日志可以拿到客户端地址而非 127.0.0.1。
> 
> 此方案本质上是用 adguardhome 取代 dnsmasq，并使用 openclash 的 dns 做为 adh 上游。想要更改上游地址的时候从 OpenClash 里面改即可。

求问是否可以把 “ISP → OpenClash → ADH” 改成 “ISP → ADH → OpenClash ”？因为我可能并不需要openclash有时候，或者当我不需要的时候，还得重新配置一遍ADH？

**Comment by alwyntang** [comment]
> > 分享我的做法：ISP → OpenClash → ADH
> > 
> > 1. Openwrt 关闭 dnsmasq（即取消网络 → DHCP/DNS 里的 **DNS 重定向**）
> > 2. OpenClash 关闭**本地DNS劫持**和**自定义上游DNS服务器**，并设置你喜欢的上游，可以是 ISP 的也可以是任何公共 DNS
> > 3. ADH 的**唯一**上游设置为 **127.0.0.1:7874**
> > 4. ADH 用非 53 端口，重定向模式选择重定向53端口到 AdGuardHome
> > 
> > 这个方案下，OpenClash 可以用任何你喜欢的模式，我用的是 **Redir-Host（TUN-混合）**。 TCP、UDP皆运作正常；nslookup 能拿到正确的IP；AdGuardHome 日志可以拿到客户端地址而非 127.0.0.1。
> > 此方案本质上是用 adguardhome 取代 dnsmasq，并使用 openclash 的 dns 做为 adh 上游。想要更改上游地址的时候从 OpenClash 里面改即可。
> 
> 太棒了，这个是我找了一圈最完整的设置方法。 我自己调了2小时没调通，按照这个设置5分钟就好了，感谢感谢

请教一下，关闭dnsmasq怎么操作？openclash关闭本地dns劫持和自定义上游dns服务器，意思是两个全部取消勾选吗？

**Comment by edgean** [comment]
> 我的解决方案是在openwrt的lan设置里面写入6:192.168.10.1，这样就能成功获取DNS地址了

我也是这样解决DHCP的问题，但发现IPv6状态模式废了，所以又改回去了

**Comment by zhoubingyi** [comment]
> 

我也遇到了这个问题，clash 一挂就全挂了，请问是怎么解决的么？

**Comment by zhzih** [comment]
> 分享我的做法：ISP → OpenClash → ADH
> 
> 1. Openwrt 关闭 dnsmasq（即取消网络 → DHCP/DNS 里的 **DNS 重定向**）
> 2. OpenClash 关闭**本地DNS劫持**和**自定义上游DNS服务器**，并设置你喜欢的上游，可以是 ISP 的也可以是任何公共 DNS
> 3. ADH 的**唯一**上游设置为 **127.0.0.1:7874**
> 4. ADH 用非 53 端口，重定向模式选择重定向53端口到 AdGuardHome
> 
> 这个方案下，OpenClash 可以用任何你喜欢的模式，我用的是 **Redir-Host（TUN-混合）**。 TCP、UDP皆运作正常；nslookup 能拿到正确的IP；AdGuardHome 日志可以拿到客户端地址而非 127.0.0.1。
> 
> 此方案本质上是用 adguardhome 取代 dnsmasq，并使用 openclash 的 dns 做为 adh 上游。想要更改上游地址的时候从 OpenClash 里面改即可。

想问一下这样跟不用adg有什么区别，是不是只多了个去广告，只是把dnsmasq换成了adguardhome。
