### ISSUE TITLE
极路由B70选什么内核版本

### ISSUE THREAD

**Issue by swxiaoqiang** [vernesong/OpenClash#992]
极路由B70选什么内核版本！openclash

**Comment by swxiaoqiang** [comment]
有人知道吗？
Does anyone know?

**Comment by ZerOri** [comment]
同问，目前是系统自带编译版本，无法更新。

**Comment by ZerOri** [comment]
查了下MT7621的架构是**mipsel_24kc** 对应的是 **mipsle-softfloat** 版本
