### ISSUE TITLE
功能受限

### ISSUE THREAD

**Issue by OleStore** [vernesong/OpenClash#995]
> 1.读取变得非常慢

正在读取【123.yaml】-【vmess】-【美国 planA】服务器节点配置...  
之前版本 读取非常快，50-60个节点，不到1分钟，现在读取大概需要3-4分钟

> 2. 之前的配置文件会提示功能受限

![2020-11-20_001349](https://user-images.githubusercontent.com/1283711/99692697-8c8e6c00-2ac5-11eb-9fab-470e932e8183.jpg)

> 3.使用本地 一键生成 黑洞规则无法启动

通过看配置文件，rule-providers 下面的规则都不存在
比如下方这些，
  Reject:
    type: http
    behavior: classical
    url: 'https://gitee.com/lhie1/Rules/raw/master/Clash/Provider/Reject.yaml'
    path: ./Rules/Reject
    interval: 86400
提示错误如下：
  a :错误: 无法获取DNS部分的运行模式设置, OpenClash 使用原始配置文件启动失败      
   b错误: 无法获取General部分的转发端口设置, OpenClash 使用原始配置文件启动失败
通过订阅转换无上述问题，启动正常

> 4. 通过在线订阅转换洞主规则，Yacd 控制面板 打开无限提示输入密码

![2020-11-20_003011](https://user-images.githubusercontent.com/1283711/99695755-e3e20b80-2ac8-11eb-9f9c-70c3886dbec0.jpg)
Dashboard 控制面板 ,根本就打不开
![2020-11-20_004417](https://user-images.githubusercontent.com/1283711/99696331-8e5a2e80-2ac9-11eb-8c5f-9e4c47780862.jpg)

以上是拉取最新源码编译后重刷的结果
软路由X86_64

**Comment by vernesong** [comment]
一键生成的也无法启动对吗

**Comment by OleStore** [comment]
> 一键生成的也无法启动对吗

对的

**Comment by gnusir** [comment]
> 
> 
> 一键生成的也无法启动对吗

ConnersHua 规则可以  
lhie1 规则不行

**Comment by yanyingjie007** [comment]
一样的问题，等更新规则吧
