### ISSUE TITLE
41.02版本启动时不写入配置

### ISSUE THREAD

**Issue by msylgj** [vernesong/OpenClash#996]
最新的41.02版本启动时，提示有修改配置，但实际未能写入dns等在luci界面配置的内容，查看启动使用的yaml文件中不包含上述配置，还是订阅转换后的配置内容。
app为本地编译更新的，ruby的依赖已经自动从makefile引入，应该不是依赖缺失。

**Comment by LOVE2CMOL** [comment]
我也是这个问题 
#===================== 依赖检查 =====================#
dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
jsonfilter: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
iptables-mod-tproxy: 已安装
iptables-mod-extra: 已安装
libcap: 已安装
libcap-bin: 已安装
ruby: 已安装
ruby-yaml: 已安装
kmod-tun(TUN模式): 已安装
luci-compat(Luci-19.07): 已安装

**Comment by sekaiacg** [comment]
确实有些订阅配置不会被openclash修改。

**Comment by msylgj** [comment]
> 确实有些订阅配置不会被openclash修改。

回滚到40.15是正常的 就很奇怪 配置删掉重新来也不行

**Comment by LOVE2CMOL** [comment]
我切换到新版本导个报告给作者看看先

**Comment by LOVE2CMOL** [comment]
@msylgj  貌似我的突然好了，不要在界面点升级，上传到路由器用命令安装

**Comment by LOVE2CMOL** [comment]
![image](https://user-images.githubusercontent.com/28857775/99832803-0f81f600-2b9c-11eb-8a7d-8b370cd8d880.png)
补张图

**Comment by LOVE2CMOL** [comment]
linux真的是个玄学东西

**Comment by LOVE2CMOL** [comment]
不对，定位到一个问题，走更新的时候，就再也保存不了了

**Comment by LOVE2CMOL** [comment]
问题依旧，我3点走了下自动更新，整个网络就炸了，检查了下发现自定义没有生效

**Comment by vernesong** [comment]
ruby修改失败会跳过，编译新commit试试

**Comment by msylgj** [comment]
> ruby修改失败会跳过，编译新commit试试

收到 感谢v大辛苦

**Comment by zhengwenxiao** [comment]
问题应该已经修复了 
wget https://raw.githubusercontent.com/vernesong/OpenClash/568c60fc66161ad62ee8749eb0da79e0f5286f63/luci-app-openclash/root/etc/init.d/openclash
wget https://github.com/vernesong/OpenClash/blob/568c60fc66161ad62ee8749eb0da79e0f5286f63/luci-app-openclash/root/usr/share/openclash/yml_groups_set.sh
wget https://github.com/vernesong/OpenClash/blob/568c60fc66161ad62ee8749eb0da79e0f5286f63/luci-app-openclash/root/usr/share/openclash/yml_proxys_set.sh
cp /etc/init.d/openclash cp /etc/init.d/openclash.bak
mv openclash /etc/init.d/openclash
mv yml_groups_set.sh /usr/share/openclash/yml_groups_set.sh
mv yml_proxys_set.sh /usr/share/openclash/yml_proxys_set.sh
chmod 755 /etc/init.d/openclash
chmod 755 /usr/share/openclash/yml_groups_set.sh
chmod 755 /usr/share/openclash/yml_proxys_set.sh

**Comment by sekaiacg** [comment]
> ruby修改失败会跳过，编译新commit试试

最新commit，修改前与修改后一致，没有被修改......

**Comment by vernesong** [comment]
找到原因了，文件过大，加载失败

**Comment by msylgj** [comment]
> 找到原因了，文件过大，加载失败

哇 v大辛苦了！周末好好休息不着急 我刚编译完但是发现现在的固件overlay丢了不敢刷，等晚上回去重新编译一个来测试
